### PR TITLE
dont apply jail search filter is on the root

### LINKED ISSUE #28108: No matches for search in external storage when external storage is not available for user but shared for user
A user that:
1. is not in the "Available For" of the external storage
2. receives a full share of the external storage

can explore and open files but not search them.

### Steps to reproduce

1. Install Nextcloud 21.0.3
2. Create a local folder with owner `www-data`
```
sudo mkdir /ext-storage
sudo chown www-data.www-data
```
3. In Nextcloud, enable External Storage app.
4. Create External Storage:

```
Folder Name: ext-storage
External Storage: local
Authentication: none
Configuration: /ext-storage
Available for: admin(group)
Options: Enable Preview, Enable Share
```
5. With admin, create user user1
6. With admin, share the folder ext-storage with user1
7. With admin, move all the default files (Nextcloud intro.mp3, ...) into ext-storage
8. With user1, search for "intro" => matches "Nextcloud intro.mp3"
9. Logout admin
10. With user1, remove all the default files, leave only ext-storage
11. With user1, search for "intro" => No results

### Expected behaviour
At step 11, user1 should find a match as in step 8

### Actual behaviour
At step 11, user1 doesn't find a match

### Server configuration
See the system report
[attached](https://github.com/nextcloud/server/files/6861587/system-report-2021-07-22.md)

### PR DESCRIPTION
**Pull request by icewind1991**
the extra '/' breaks things and the filter wouldn't do anything anyway except making the databases job harder

Fixes #28108

@pmarini-nc @xadhoom76 can you check if this fixes the problem for you

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: tested, works

@icewind1991 can you also adjust the unit tests ?

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by juliusknorr — APPROVED** [review]

**Comment by PVince81** [comment]
> The backport to stable20 failed. Please do this backport manually.

https://github.com/nextcloud/server/pull/28235#issuecomment-889201209

**Pull request merged**
