### PR TITLE
update theming icon in personal settings

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/pull/34069#issuecomment-1252118983

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by jancborchardt — APPROVED** [review]
Thank you! :)

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
