### PR TITLE
Focus trap contacts menu with NcHeaderMenu port

### PR DESCRIPTION
**Pull request by Pytal**
Wrap the existing contacts menu with NcHeaderMenu

### CODE REVIEW

**Comment by Pytal** [comment]
Screenshotable after https://github.com/nextcloud/server/pull/36110

**Comment by Pytal** [comment]
Code ready but unfortunately not screenshotable due to the reasons detailed in https://github.com/nextcloud/server/pull/36110

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Very clean :)

**Comment by skjnldsv** [comment]
Tests are failing though :cry:

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
acceptance-header still failing :)

**Pull request merged**
