### PR TITLE
Add "mod_security"

### PR DESCRIPTION
**Pull request by Valdnet**
Disabling "mod_security".

The problem described in issue: #29824.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
I have no clue about that stuff *unassigning*

**Comment by orandev** [comment]
Hello,
If you had a problem with modsecurity on your server, it's up to you to add modsecurity exclusions in your .htaccess or modsecurity config. I have multiple exclusions in my modsecurity config in order to avoid false positives or issues with Nextcloud.
But I strongly disagree with the merge of a PR like that in Nextcloud server code.

**Comment by acsfer** [comment]
I'm not a fan of disabling security measures "by default".
This should be put in the documentation (only), and not only how to disable it but, eventually, also how to configure it correctly.

**Comment by Valdnet** [comment]
> This should be put in the documentation (only), and not only how to disable it but, eventually, also how to configure it correctly.

Please add this so that in the future users will not have such a problem.

I close PR.

**Pull request closed without merging**
