### PR TITLE
fix appinfo parsing when a single localized option is provided

### PR DESCRIPTION
**Pull request by icewind1991**
See https://github.com/nextcloud/server/pull/8223

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Fixes this issue:

```
{
    "reqId": "pzYTbLf31SIos81QcAFn",
    "level": 3,
    "time": "2018-04-12T11:46:26+00:00",
    "remoteAddr": "172.20.0.1",
    "user": "admin",
    "app": "PHP",
    "method": "GET",
    "url": "/index.php/settings/apps/list?category=updates",
    "message": "Undefined index: @value at /var/www/html/lib/private/legacy/app.php#1019",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15",
    "version": "14.0.0.2"
}
```

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Rebased to trigger stuck CI.

**Comment by nickvergessen** [comment]
Should backport

**Comment by MorrisJobke** [comment]
stable13 #9233

**Pull request merged**
