### PR TITLE
Fixed issue #3524 and issue #8717

### LINKED ISSUE #3524: occ files_external:notify does not propogate changes to clients.
### Steps to reproduce
1. Mount a windows share in nextcloud
2. Let a desktop client sync the share.
2. Run occ files_external:notify -v <mount_id>
3. Make some changes remote, directly to the windows share by other means.

### Expected behaviour
The desktop clients should propogate the changes that happened directly to the SMB share.

### Actual behaviour
I get the changes listed out in the terminal output of the occ files_external:notify command, but nothing else happens.

### Server configuration
**Operating system**:
Ubuntu Server 16.04 
**Web server:**
Nginx 1.10

**Database:**
Mariadb 10
**PHP version:**
7.0/7.1 (tried both)
**Nextcloud version:** (see Nextcloud admin page)
11.0.1 and 11.0.2 (tried both)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade.
**Where did you install Nextcloud from:**
Wonderfall/nextcloud:latest

### Client configuration
**Operating system:**
Elementary with nextcloud-client 2.2.4

### PR DESCRIPTION
**Pull request by theroch**
Fixed #3524 and #8717 

Signed-off-by: Frank Rochlitzer <f.rochlitzer@b3-it.de>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@theroch Thanks for the contribution. Do you mind to explain a little bit the background of your changes and why they fix what?

**Comment by icewind1991** [comment]
The etag not being changed and only the direct parent being updated is the way it's intended to work, the background scanner should make the required changes to the cache. If there is a problem with that then it should be fixed there

**Comment by theroch** [comment]
I have very detailed explanation in #3524 why I have to do it this way.
Only if I reset the etag the nextcloud client recognized the changes.
>@MorrisJobke wrote:
>The scan is not needed then. If they show up in the notify command then they are properly recognized and are put into the file index

The explanation for #8717 is that dirname returns in linux always a string with a beginning slash, so the update query never matched anything.

**Comment by ChristophWurst** [comment]
> The etag not being changed and only the direct parent being updated is the way it's intended to work, the background scanner should make the required changes to the cache. If there is a problem with that then it should be fixed there

@icewind1991 shall we close this pull request then? https://github.com/nextcloud/server/issues/3524 tells me some people have used this and while first some report success, they conclude that it's not a real solution.

**Comment by theroch** [comment]
@ChristophWurst 
Why should I wait for the background scanner if the notifier already make some changes to the cache?
Here is also a note from my last comment in #3524:
>>In detail, the documentary even says:
>>"Note on remote discovery: Since a change to a file on the server causes the etags of all parent folders to change, folders with an unchanged etag can be read from the journal directly and don't need to be walked into."
>
>Resetting the ETAGs along the path through my patch seems to be the correct approach.
Sure there seems to be an issue while deleting files, but the patch is still better than the current implementation to work with SMB at all.

**Comment by icewind1991** [comment]
> Why should I wait for the background scanner if the notifier already make some changes to the cache?

Because the notifier can't always update the cache properly,
in situations where a single configured smb share is available to multiple users, not all users might see the exact same content (i.e. they have different permissions, or no access to some folders altogether).

With the current 2-part system, you can run a single notify process to detect changes from the smb share (using an account that has at least read permissions for the entire share) and leave the job of figuring out the exact cache content to the background scanner.

If you try to combine both "jobs", you'll need to either run a separate notify process for all users with access to a share, or add a significant amount of complexity to the notifier to handle all cases properly, complexity which already exists in the background scanner.

**Comment by MorrisJobke** [comment]
> Because the notifier can't always update the cache properly,
> in situations where a single configured smb share is available to multiple users, not all users might see the exact same content (i.e. they have different permissions, or no access to some folders altogether).
> 
> With the current 2-part system, you can run a single notify process to detect changes from the smb share (using an account that has at least read permissions for the entire share) and leave the job of figuring out the exact cache content to the background scanner.
> 
> If you try to combine both "jobs", you'll need to either run a separate notify process for all users with access to a share, or add a significant amount of complexity to the notifier to handle all cases properly, complexity which already exists in the background scanner.

This means we should not merge this change here?

**Comment by ChristophWurst** [comment]
> This means we should not merge this change here?

From @icewind1991's reply it sounds like a yes.

I'm closing this. Please re-open if this is still relevant.

**Pull request closed without merging**
