### PR TITLE
Fix remaining readdir() calls in loops with undesirable false evaluation potential

### PR DESCRIPTION
**Pull request by joshtrichards**
## Summary

Fixes all remaining `readdir()` calls within loops that had undesirable false evaluation potential (at least in `server`)

There weren't too many left and the bulk were in tests. The most notable *not* in tests were these:

- `copy()` in `\OC\Files\Storage\Common`
- `isEmpty()` in `OCA\Files_Trashbin\Trashbin`
- `copyRecursive()` in `OC\Files\Storage\PolyFill\CopyDirectory`

Ref: https://www.php.net/manual/en/function.readdir.php

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by solracsf — APPROVED** [review]
Sure, avoid "falsy" and ensure "false". 🆗

**Comment by solracsf** [comment]
I wonder if these Psaml warning worth something like:

```
// Open the directory and obtain a resource handle
$dh = opendir($directory);

// Check if the directory was opened successfully
if ($dh !== false) {
    // Iterate through directory entries
    while (($file = readdir($dh)) !== false) {
        // Process each file or directory
    }

    // Close the directory handle
    closedir($dh);
}
```

🤔

**Comment by joshtrichards** [comment]
I don't think any of these test fails are related to this PR. 😕

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Rebased! Let's hope it works this time !! :muscle:

**Comment by skjnldsv** [comment]
:tada: :tada: :tada:

**Pull request merged**
