### PR TITLE
Backport of translation string fixes

### PR DESCRIPTION
**Pull request by MorrisJobke**
* #6239 & #6780 
* also fixed a typo in there

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by rakekniven — APPROVED** [review]
Common grammar at Nextcloud

**Comment by jancborchardt** [comment]
Good on using proper ellipsis, but as in the other one please with space like "Uploading …" :)

**Comment by MorrisJobke** [comment]
> Good on using proper ellipsis, but as in the other one please with space like "Uploading …" :)

Done.

**Review by jancborchardt — APPROVED** [review]

**Comment by MorrisJobke** [comment]
vendor/core.js was outdated on stable12 -> fixed.

**Pull request merged**
