### PR TITLE
[stable25] fix(dav): Abort requests with 429 instead of waiting

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #38046

### CODE REVIEW

**Review by bigcat88 — APPROVED** [review]

**Review by mejo- — APPROVED** [review]

**Comment by kesselb** [comment]
Pushed a commit to fix the incomplete https://github.com/nextcloud/server/pull/37227 backport.

**Comment by kesselb** [comment]
Pushed another commit to fix the code style for \OC\Files\Node\Folder.

**Comment by kesselb** [comment]
@blizzz the psalm failure looks related to https://github.com/nextcloud/server/pull/39154. Can you suggest a fix?

**Comment by blizzz** [comment]
> @blizzz the psalm failure looks related to #39154. Can you suggest a fix?

unrelated, ignore for now. new check we enabled.

**Review by kesselb — APPROVED** [review]

**Pull request merged**
