### PR TITLE
Fix ie app menu loading click

### LINKED ISSUE #15887: Problem to open Contacts etc. with Edge Browser
Hello,

i can not open galery, contacts, activitys, talk or else with the edge browser…..when i click on it, i see only the waiting symbol but nothing happens. Only files or configurationlink is working. The Problem is since Nextcloud 16. I have 4 installations on Ubuntu 18.04 with Plesk, using Apache or Nginx. On all servers the same problem.

Nextcloud 16.0.1
Server-Version: 10.1.38-MariaDB-0ubuntu0.18.04.2 - Ubuntu 18.04 
Windows 10 Pro 1809
Anmerkung 2019-06-06 144509

### PR DESCRIPTION
**Pull request by skjnldsv**
fix #15887

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by jancborchardt** [comment]
cc @XBrainBug @Lars1963 for review as this fixes an issue you reported. :) https://github.com/nextcloud/server/issues/15887

**Comment by Lars1963** [comment]
Works for me.

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
Backport in https://github.com/nextcloud/server/pull/16668

**Pull request merged**
