### PR TITLE
new Group-Member association attribute (zimbraMailForwardingAddress)

### PR DESCRIPTION
**Pull request by tofuSCHNITZEL**
added "zimbraMailForwardingAddress" as a Group-Member association attribute to enable the use of Zimbra Distribution Lists as groups in nextcloud when connecting to a zimbra LDAP

### CODE REVIEW

**Comment by kesselb** [comment]
> First-time contributor

Thank you for your contribution :tada: 

Indentation needs to be fixed and code style looks wrong (https://docs.nextcloud.com/server/stable/developer_manual/general/codingguidelines.html).

 I personally don't like so many logic in wrapped in a switch-case :see_no_evil:

**Comment by tofuSCHNITZEL** [comment]
> I personally don't like so many logic in wrapped in a switch-case 🙈

yes I understand, but in this case I think it helps reusing code and improving readability (compared to a lot of if/elseifs) and it also makes future customization for different "ldapGroupMemberAssocAttr" easier

**Comment by kesselb** [comment]
Make Sense (and I'm not sure how to do it better right now). 

Do you think we could introduce a new variable for  `strtolower($this->access->connection->ldapGroupMemberAssocAttr)`?

**Comment by tofuSCHNITZEL** [comment]
> Do you think we could introduce a new variable for `strtolower($this->access->connection->ldapGroupMemberAssocAttr)`?

I created a new class variable for it - seems like a good idea as it is used quite often

**Comment by MorrisJobke** [comment]
@blizzz Mind to review?

**Comment by blizzz** [comment]
@tofuSCHNITZEL thanks for you contribution. I am sorry I have to ask you to rebase and some changes might be needed, because the group backend code also changed since. 

Further, I am thinking of moving out the attribute's logic specific parts out to to a to be created class, so it can do it's magic there. The reason is to take complexity out of the methods here and capsule them where they belong. That would help with the switch :) On the other hand it would extend the scope a lot, so perhaps that to be done in a different PR. If you're up to it. Otherwise it just the rebase and adaption.

**Comment by tofuSCHNITZEL** [comment]
> @tofuSCHNITZEL thanks for you contribution. I am sorry I have to ask you to rebase and some changes might be needed, because the group backend code also changed since.

I rebased (or at least I tried) and I applied all my changes to the current master but I'm not sure if I completely messed up everything with the rebase seeing how my pull request now has so many commits... Is there a way to fix this (if its wrong) or should we just close this request and I create a new one with a fresh branch based on the current master?

**Comment by tofuSCHNITZEL** [comment]
please see new pull request https://github.com/nextcloud/server/pull/16737

**Pull request closed without merging**
