### PR TITLE
Remove unnecessary translation in systemtags

### LINKED ISSUE #20059: l10n: Need context for string "({scope})"
https://github.com/nextcloud/server/blob/a0058fe60177c92c6257804d7115ebd1766e64a8/core/js/systemtags/systemtags.js#L48

Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/90994219?q=issue%3Aopen

### PR DESCRIPTION
**Pull request by gary-kim**
Closes #20059 

The text being appended is an already translated string so the second translation should not be required.

Signed-off-by: Gary Kim <gary@garykim.dev>

### CODE REVIEW

**Comment by gary-kim** [comment]
If you're about to ask me why a 6 line change causes more than 13000 lines to be removed: :man_shrugging:

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
> If you're about to ask me why a 6 line change causes more than 13000 lines to be removed: man_shrugging

Because some of those files are no longer used and can go :) That is why.

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
> If you're about to ask me why a 6 line change causes more than 13000 lines to be removed:

Best cleanup in history! :grin:

**Comment by skjnldsv** [comment]
JSunit not happy

```
PhantomJS 2.1.1 (Linux 0.0.0) OC.SystemTags tests scope FAILED
1052 | Expected 'Fourty Two invisible' to equal 'Fourty Two (invisible)'.
1053 | testScope@core/js/tests/specs/systemtags/systemtagsSpec.js:60:34
1054 | core/js/tests/specs/systemtags/systemtagsSpec.js:65:12
1055 | Expected 'Fourty Two invisible' to equal 'Fourty Two (invisible)'.
1056 | testScope@core/js/tests/specs/systemtags/systemtagsSpec.js:60:34
1057 | core/js/tests/specs/systemtags/systemtagsSpec.js:66:12
1058 | Expected 'Fourty Two restricted' to equal 'Fourty Two (restricted)'.
1059 | testScope@core/js/tests/specs/systemtags/systemtagsSpec.js:60:34
1060 | core/js/tests/specs/systemtags/systemtagsSpec.js:67:12
1061 | ..............
1062 | PhantomJS 2.1.1 (Linux 0.0.0) OC.SystemTags.SystemTagsInputField tests as admin formatResult renders tag name with visibility FAILED
1063 | Expected 'test invisible' to equal 'test (invisible)'.
1064 | core/js/tests/specs/systemtags/systemtagsinputfieldSpec.js:304:45
1065 | PhantomJS 2.1.1 (Linux 0.0.0) OC.SystemTags.SystemTagsInputField tests as admin formatSelection renders tag name with visibility FAILED
1066 | Expected 'test invisible' to equal 'test (invisible)'.
1067 | core/js/tests/specs/systemtags/systemtagsinputfieldSpec.js:309:37
```

**Review by rakekniven — COMMENTED** [review]
I am not a dev.

**Comment by skjnldsv** [comment]
Still failing

**Comment by gary-kim** [comment]
> Still failing

It **was** passing... <https://drone.nextcloud.com/nextcloud/server/27180>. Let me see what I can do.

**Pull request merged**
