### PR TITLE
Remove display name ellipsis in user menu

### LINKED ISSUE #42455: [Bug]: Top right menu ellipsizes short names
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Bildschirmfoto vom 2023-12-22 13-29-10

### Steps to reproduce

1. Have a relatively short name
2. Open the menu in the top right

### Expected behavior

I see the full name

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Fixes https://github.com/nextcloud/server/issues/42455

Screenshots made with NC 28.0.1 RC1 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by jancborchardt — CHANGES_REQUESTED** [review]
This leads to the width of the menu extending infinitely though depending on the name:
image

I suggest using a higher value for the max-width. Either a set one (208px works well in English) or if possible to just use whichever space is available in the menu. But not to extend the width of the menu. :)

**Review by jancborchardt — APPROVED** [review]
Works, but maybe it’s nicer to use something like `flex-grow` to make this entry fill the available width. :) Then we don’t need a fixed value.

**Review by szaimen — APPROVED** [review]
Fine by me

**Comment by Jerome-Herbinet** [comment]
There is a conflict ; what's the easiest way for me to solve it ?

**Comment by zak39** [comment]
Hello everyone :) 

@szaimen & @jancborchardt : Should @Jerome-Herbinet update the branch with rebase (please, look at the screenshot)?

I worked with him this morning and we rebased his branch.
Does he have to rebase again?

image

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
