### PR TITLE
Bump @nextcloud/vue from 7.5.0 to 7.6.0

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Bump `@nextcloud/vue` from https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.5.0 to https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.6.0

## Requires

- [x] https://github.com/nextcloud/server/pull/36738 to be merged first to fix the `Can't resolve 'vue-select'` error
  - This is due to the switch https://github.com/nextcloud/nextcloud-vue/pull/3703 in `v7.6.0`, so `vue-select` is no longer included within the dependency tree
- https://github.com/nextcloud/server/pull/36757
  - Resolve `exports is not defined` errors

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Comment by Pytal** [comment]
Seems to break script load order with many `OC is not defined` errors, there is also an
```
Uncaught ReferenceError: exports is not defined
    at ./node_modules/@nextcloud/dialogs/dist/index.js
```
error which is probably related to the recent https://github.com/nextcloud/nextcloud-dialogs/releases/tag/v4.0.0 release and may be similar to https://github.com/nextcloud/nextcloud-vue/issues/3753 though `resolve.fullySpecified = false` here doesn't seem to fix it

Any ideas @juliushaertl?

**Review by artonge — APPROVED** [review]

**Comment by juliushaertl** [comment]
Was fixed in https://github.com/nextcloud/nextcloud-dialogs/pull/761, bumping `@nextcloud/dialogs` to 4.0.1 should resolve this

**Comment by Pytal** [comment]
> Was fixed in [nextcloud/nextcloud-dialogs#761](https://github.com/nextcloud/nextcloud-dialogs/pull/761), bumping `@nextcloud/dialogs` to 4.0.1 should resolve this

The
```
Uncaught ReferenceError: exports is not defined
    at ./node_modules/@nextcloud/dialogs/dist/index.js
```
error is resolved on top of https://github.com/nextcloud/server/pull/36757 but the `OC is not defined` errors still persist

**Pull request closed without merging**
