### PR TITLE
Updates to new sharing flow

### LINKED ISSUE #40395: new share dropdown not good visible in dark mode
See 
image

### LINKED ISSUE #40438: ⛑️ Polishing for new sharing design and flow -> 27.1.2
This is a follow up to #40172 where the blocking issues were resolved for 27.1.0. Below are the enhancements planned for 27.1.1 and 27.1.2

- [x] The "Cancel" and primary button on the bottom need a backdrop to separate them a bit from the background, best a fade from color-main-background on the bottom to transparent on the top.
- [x] Currently links are sorted below emails once created, but sorting should be: Links, mails, users
- [x] QA: Needs side by side testing if all old options are possible or also properly limited with the new one
- [x] If allow public upload admin setting is unchecked we should rename "Allow upload and editing" to "allow editing" and file drop / create permission should be disabled state
- [x] The content of the sidebar is scroll-able when it should only be the content of the share tab
image
- [x] It is confusing to have the download permission under "Custom permissions" as it is not taken into account for bundles
- [x] [Do not show unnecessary password expired message #40493](https://github.com/nextcloud/server/issues/40493)

### LINKED ISSUE #40612: [Bug]: "Set expiration date" in share preview is not set when admin has set a default expiration date
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

"Set expiration date" in the share preview is not set when admin has set a default expiration date. Only once the share has been saved the expiration date is set.

This is confusing for the user: when the configured the share, there was seemingly no expiration date. But when they save it, there suddenly is one!

### Steps to reproduce

1. Admin: configure a "default expiration date for shares" under /settings/admin/sharing, e.g. to 7 days.
2. User: start the flow to share a new file
3. User: click on "Advanced Settings"

### Expected behavior

The "Set expiration date" should be checked and the date set to the default date configured by the admin.

### Actual behaviour (why is this not an Issue template field)

The "Set expiration date" is unchecked.

### Installation method

Community Docker image

### Nextcloud Server version

27.1

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "filelocking.enabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.goebel.family"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "mysql",
        "version": "27.1.1.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwritehost": "cloud.example.com",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "forcessl": true,
        "default_phone_region": "DE",
        "theme": "",
        "app_install_overwrite": [
            "whiteboard",
            "twofactor_nextcloud_notification",
            "suspicious_login",
            "qownnotesapi",
            "quota_warning",
            "twofactor_admin"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - cospend: 1.5.10
  - dav: 1.27.0
  - deck: 1.11.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.3.1
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - notify_push: 0.6.3
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - polls: 5.3.2
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - qownnotesapi: 23.6.0
  - quota_warning: 1.17.0
  - recognize: 4.3.2
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.0
  - richdocumentscode: 23.5.402
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - translate: 1.1.6
  - twofactor_backupcodes: 1.16.0
  - twofactor_nextcloud_notification: 3.7.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.2.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - dashboard: 7.7.0 (installed 7.0.0)
  - encryption: 2.15.0
  - files_external: 1.19.0
  - groupfolders: 15.3.1 (installed 15.3.1)
  - integration_deepl: 1.1.0 (installed 1.1.0)
  - twofactor_admin: 4.3.0 (installed 4.3.0)
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
can provide if needed
```

### Additional info

I *think* this is a regression and it used to work in 27.0, but broke in 27.1 -- but I'm only 80% sure.

### PR DESCRIPTION
**Pull request by nfebe**
Resolves : https://github.com/nextcloud/server/issues/40438, https://github.com/nextcloud/server/issues/40395, https://github.com/nextcloud/server/issues/40612

Dark mode

| Before | Now |
| --------- | ------ |
| Screenshot from 2023-09-26 12-13-19 | Screenshot from 2023-09-26 09-25-44 |

Footer background 

| Before | Now |
| --------- | ------ |
| Screenshot from 2023-09-26 12-11-29 | Screenshot from 2023-09-26 12-08-16 |

### CODE REVIEW

**Comment by Fenn-CS** [comment]
Follow up

| Item | Action |
| ------ | -------- |
| The "Cancel" and primary button on the bottom need a backdrop to separate them a bit from the background, best a fade from color-main-background on the bottom to transparent on the top.| Done see screenshots above |
| Currently links are sorted below emails once created, but sorting should be: Links, mails, users | It is the case |
| If allow public upload admin setting is unchecked we should rename "Allow upload and editing" to "allow editing" and file drop / create permission should be disabled state | Done |
| The content of the sidebar is scroll-able when it should only be the content of the share tab | Done |
| It is confusing to have the download permission under "Custom permissions" as it is not taken into account for bundles | Moved up, and it is now just an advanced setting | 
| [Do not show unnecessary password expired message #40493](https://github.com/nextcloud/server/issues/40493) | Done | 
| Others | Dark mode corrections, see screenshot above/below |

Dark mode view
----------------------

Screenshot from 2023-09-26 21-15-30

**Review by jancborchardt — COMMENTED** [review]
Nice improvements! Some feedback:
- [ ] The gradient for the bottom buttons should be color-main-background on the bottom, currently it seems to use primary-light. It should not really be actively visible.
- [ ] The gradient needs to extend to the full left and right of the sidebar and also to whichever much bottom padding the buttons have. Currently it starts directly at the buttons, which will lead to things looking cut off once you scroll.
- [ ] The "Delete share" button also has a gradient on it for some reason?

**Comment by Fenn-CS** [comment]
>  The gradient for the bottom buttons should be color-main-background on the bottom, currently it seems to use primary-light. It should not really be actively visible.

Yeah, this was mentioned from the original recommendation but I realized `color-main-background` makes not visual difference as it matches with the main background of the color theme. So can you please provide more context for me to understand the purpose of a non-visible gradient? 

> The gradient needs to extend to the full left and right of the sidebar and also to whichever much bottom padding the buttons have. Currently it starts directly at the buttons, which will lead to things looking cut off once you scroll.

I don't think it would be easy to achieve that, as everything is aligned inside the a container to keep the left-aligned items in place.

> The "Delete share" button also has a gradient on it for some reason?

On master "Delete share" has no bg, unlike with 27, so I added a similar gradient. Could easily revert this.

cc: @jancborchardt

**Comment by jancborchardt** [comment]
> > The gradient for the bottom buttons should be color-main-background on the bottom, currently it seems to use primary-light. It should not really be actively visible.
> 
> Yeah, this was mentioned from the original recommendation but I realized `color-main-background` makes not visual difference as it matches with the main background of the color theme. So can you please provide more context for me to understand the purpose of a non-visible gradient?

Yep, here you go :) The gradient is invisible, yes, but it becomes visible when the content is big enough to make the container scroll (or the viewport is small enough).
Note the screenshots are based on the old mockups, so disregard any of that, only the gradient. :)

Current situation when scrolled | With the gradient
-|-
image|image



> 
> > The gradient needs to extend to the full left and right of the sidebar and also to whichever much bottom padding the buttons have. Currently it starts directly at the buttons, which will lead to things looking cut off once you scroll.
> 
> I don't think it would be easy to achieve that, as everything is aligned inside the a container to keep the left-aligned items in place.

Right, actually if the gradient is color-main-background it is also not necessary to do that for left and right. For the bottom it is necessary though and could be done via negative margin?

> > The "Delete share" button also has a gradient on it for some reason?
> 
> On master "Delete share" has no bg, unlike with 27, so I added a similar gradient. Could easily revert this.

"Delete share" could just be a tertiary button as last element of the content, not as part of the button section which would then only have "Cancel" and "Update share".

**Comment by Fenn-CS** [comment]
Thanks for the clarification @jancborchardt...

Both your concerns have been addressed. 

Screenshot from 2023-09-28 11-35-10

**Review by jancborchardt — APPROVED** [review]
Looks good!

**Review by artonge — APPROVED** [review]

**Pull request merged**
