### PR TITLE
Shorten resource table names to allow install on oracle again

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://travis-ci.org/nextcloud/notifications/jobs/403034114

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]
Code changes look good 👍

**Comment by nickvergessen** [comment]
Invitation table is also too long

**Comment by georgehrke** [comment]
What's the exact limit that oracle enforces?

**Comment by MorrisJobke** [comment]
> What's the exact limit that oracle enforces?

32 AFAIK, but you need to mind the prefix ;)

**Review by MorrisJobke — APPROVED** [review]
👍

**Comment by nickvergessen** [comment]
i will write a checker for this

**Comment by nickvergessen** [comment]
https://travis-ci.org/nextcloud/notifications/builds/403051765 passing with this branch :+1:

**Pull request merged**
