### PR TITLE
 make table name configurable for db user backend 

### PR DESCRIPTION
**Pull request by icewind1991**
The main use case for this is to make it easy to create a separate user backend for the guest app (to prevent guests from becoming "real" users if the app gets disabled for any reason).

### CODE REVIEW

**Comment by rullzer** [comment]
Would it not be 'safer' to just have the guest app have its own tables? And implement a real backend?

**Comment by blizzz** [comment]
I guess he wants to save some code, but then this is not in the public namespace either

**Comment by rullzer** [comment]
I would really prefer to do it properly in its own backend. That way if we want to change something in either the app backend or the db user backend we can do so without worrying of breaking the other.

**Comment by icewind1991** [comment]
Creating a separate backend would be an almost complete copy paste from this backend

**Comment by icewind1991** [comment]
I created a separate PR with all changes from this one except the configurable table name

https://github.com/nextcloud/server/pull/9881

**Comment by MorrisJobke** [comment]
> I created a separate PR with all changes from this one except the configurable table name

Rebased after #9881 was merged ;)

**Review by MorrisJobke — APPROVED** [review]
I'm fine with this one.

**Review by rullzer — APPROVED** [review]
Ok fair enough. Lets do it like this. if it turns out it diverges to much we can later always move this over to the app.

So :+1: for now :D

**Pull request merged**
