### PR TITLE
[stable15] Fix password confirmation lib for ie11

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/12806 for Nextcloud 15.

The previous version did not convert arrow functions to es5 functions. Ref https://github.com/ChristophWurst/nextcloud-password-confirmation/pull/2.

@skjnldsv could you verify it works on IE?

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
:elephant:

**Comment by MorrisJobke** [comment]
@ChristophWurst What about master?

**Comment by ChristophWurst** [comment]
> @ChristophWurst What about master?

Fixed via https://github.com/nextcloud/server/pull/12859#event-2009054508.

**Comment by ChristophWurst** [comment]
> @skjnldsv could you verify it works on IE?

Can I take your positive review as a yes?

**Pull request merged**
