### PR TITLE
fix(styles): Make sure footer with legal links is shown correctly

### LINKED ISSUE #34305: Footer height in public view too small if imprint/privacy link set
Currently the footer-height is set to 65px:

https://github.com/nextcloud/server/blob/b739dd580743aa3c339eba28c45f14d930956135/core/css/public.scss#L1

This is too small if the imprint/privacy links are set in the settings of the instance and text gets cut off. (see https://github.com/nextcloud/forms/issues/1337)

If links are set a better value would be 95px.

### LINKED ISSUE #34399: [Bug]: Public view footer broken
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On latest master (26), public view footer is broken du to #34331.

1. the removed `position: sticky` property from `<footer>`, results in the footer being displayed on the top of the page.
2. The `- 65px` is not enough because `<footer>` actually takes 65px height plus 2x 8px padding on top and bottom. So this should probably be `65px + 8px + 8px` = `81px`.

@szaimen because you tried to fix public view footer in #34331.

### Steps to reproduce

1. Open a document in public share
2. Watch the footer being broken
3. Add `position: sticky` back to `footer` CSS
4. Watch the footer overlapping long content

### Expected behavior

Footer should be at the bottom and not overlap long content.

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Unrelated
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #36485: Fixed footer (banner) blocks view of public shares on smaller screens
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the latest theme change, the `position:fixed`-footer on the file drop upload page covers the list of uploaded files:

Here is a screenshot of the page after uploading a file. The page has been scrolled up for a tiny bit so that part of the file name can be seen between the static footer and the end of the browser window:

https://user-images.githubusercontent.com/476060/216149723-2ccf5323-352d-479f-b3ed-dc2f24d9d731.MOV

Furthermore, even without uploading, the page looks pretty odd and the difference in white space makes the overall appearance of the page look pretty ugly imho:

### Steps to reproduce

1. go to a "File drop (upload only)" share with a small screen device, e.g. iPhone SE
2. upload a file
3. see the file list covered by the page footer with the slogan and stuff

### Expected behavior

The footer should be static and always stay below anything else on the page.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Files
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/36485
* Resolves: https://github.com/nextcloud/server/issues/34399
* Resolves: https://github.com/nextcloud/server/issues/34305

## Summary

Fix public pages footer height. If there are legal links or a signup link or both we need different heights of the footer.
Otherwise the footer content will be clipped and overlay the app.

Adjusted colors in the screen shots to make clear what is which element:

before | after
---|---
Screenshot 2024-07-26 at 15-01-20 Dateien - Nextcloud|Screenshot 2024-07-26 at 15-00-15 Dateien - Nextcloud
Screenshot 2024-07-26 at 15-01-01 Dateien - Nextcloud|Screenshot 2024-07-26 at 14-59-50 Dateien - Nextcloud

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Looks good from the screenshots but didnt test and didnt review the code

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
