### PR TITLE
Activity: show if files are hidden or not

### PR DESCRIPTION
**Pull request by rullzer**
I'm not 100% sure I like the wording like this. But good enough for a first version It hink.

image

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
So this works for renaming, but not for eg `mv a/b.txt c/.d.txt` (so changing parent and name)

**Comment by rullzer** [comment]
> So this works for renaming, but not for eg `mv a/b.txt c/.d.txt` (so changing parent and name)

ah fair enough. well baby steps I guess

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
