### PR TITLE
Fix UnifiedSearch

### LINKED ISSUE #33963: Search modal design issues
This happens with latest master (not yet on tech-preview):

- The modal has too much margin on all sides, resulting in floating scrollbar and text being cut off on the bottom
- The boxed-in-ness might also be the reason for the horizontal scrollbar
- The text of the entries is not vertically aligned with the icon, but moved a bit to the bottom

Search screenshot

### PR DESCRIPTION
**Pull request by CarlSchwan**
- Fix too-big margins
- Fix horizontal scrollbar (caused by margins in the text field)
- Add some spacing between the items (4px)
- Center items (I love flex)

image

### CODE REVIEW

**Comment by CarlSchwan** [comment]
> @CarlSchwan can you post screenshots? :)

done :)

**Comment by szaimen** [comment]
> > @CarlSchwan can you post screenshots? :)
> 
> done :)

Thx! :)

**Review by szaimen — APPROVED** [review]

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Mich better, just 2 things:
- [x] The "Search" title is a bit too far left, should left-align with the subheadings of the categories below
- [x] The search modal could use some margin from the right edge of the viewport, like the other menus there (8px)

**Comment by CarlSchwan** [comment]
> Mich better, just 2 things:
> 
>     * [x]  The "Search" title is a bit too far left, should left-align with the subheadings of the categories below
> 
>     * [x]  The search modal could use some margin from the right edge of the viewport, like the other menus there (8px)

Done for both and also added the margin to the notifications to keep stuff nicely consistent https://github.com/nextcloud/notifications/pull/1272

**Review by szaimen — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Pull request merged**
