### PR TITLE
[stable25] Backport: Make the container fully fulfill PSR container interface

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: Backport of #36417

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by susnux** [comment]
To fix the psalm errors we would have to either update the psr container to 1.1.2.
But somehow it does not complain about the `@throws ContainerExceptionInterface` which was there before and did not extend `Throwable` either.

**Comment by blizzz** [comment]
CI unhappy, moving to 25.0.5

**Comment by susnux** [comment]
The OCP psalm check succeeds, but there seem to be unrelated other issues (not touched that code).

**Comment by susnux** [comment]
> /rebase

@blizzz Did not work, so I rebased it manually.

**Comment by come-nc** [comment]
I do not understand what the hell is happenning to psalm here. It’s removing stuff from the baseline and then complaining about it?

**Review by come-nc — APPROVED** [review]

**Comment by nickvergessen** [comment]
❌  Branch is currently frozen

**Comment by susnux** [comment]
@nickvergessen branch is no longer frozen

drone failure is unrelated

**Comment by blizzz** [comment]
just merged 3rdparty PR. Rebase needed?

**Comment by susnux** [comment]
> just merged 3rdparty PR. Rebase needed?

Done

**Pull request merged**
