### PR TITLE
Correctly handle multi-values when converting VCards to array

### PR DESCRIPTION
**Pull request by nickvergessen**
This affects "only" the php API of our implementation, not related to sync or whatever.
### Steps
1. Create a contact named "Hello Testing" (with the contacts app)
2. Add 2 cloud ids: `admin@nextcloud.com`, `admin@example.tld`
3. Open the share dropdown in the files view and type `admin@` into the box
### Expected

Two results for federated sharing:
- `Hello Testing (at nextcloud.com)`
- `Hello Testing (at example.tld)`
### Actual

Only one result for federated sharing (the second cloud id you entered):
- `Hello Testing (at example.tld)`

@karlitschek requesting backport to 10 and 9, since this is quite heavy. The same happens for emails and addresses (used by calendar) and it also makes the activity app not finding matches when it's not the first cloud id.

@rullzer @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
great.  backport makes sense :+1:

**Comment by rullzer** [comment]
Nice :+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by nickvergessen** [comment]
Stable10: https://github.com/nextcloud/server/pull/1207
Stable9: https://github.com/nextcloud/server/pull/1208

**Pull request merged**
