### PR TITLE
Ignore contact interaction with self

### PR DESCRIPTION
**Pull request by tcitworld**
No need to insert ourselves as a recent contact

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
No more interaction with me, myself and I :smiling_face_with_tear:

**Review by miaulalala — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by ChristophWurst** [comment]
our backport bot is somewhat unrelable recently :roll_eyes:

**Pull request merged**
