### PR TITLE
Hide quota bar if unlimited quota

### LINKED ISSUE #15380: unlimited quota still shows space usage bar
### Steps to reproduce
1. Open Users page
2. Change a user to unlimited quota
3. Check the space usage bar

### Expected behaviour
The space usage bar should not be shown

### Actual behaviour
The bar is shown, but the percentage of the bar makes no sense. First I thought it might show the remaining space on the server, but this is not the case:

```
Filesystem        Size  Used Avail Use% Mounted on
/dev/mapper/XXX  3.7T  1.4T  2.4T  37% /XXX
```
(As you can see, more than 50% are available, yet the bar is showing more than 50% used.)

It seems it still shows the usage against the previous quota.

image

## Server configuration detail

**Operating system:** Linux

**Webserver:** Apache/2.4.39

**Database:** mysql 5.6.25

**PHP version:** 

7.2.18
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gnupg, SPL, hkct, ibm_db2, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl, PDFlib, mysqli, PDO, pdo_ibm, pdo_mysql, pdo_sqlite, Phar, posix, readline, Reflection, imap, shmop, SimpleXML, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, cgi-fcgi, apcu, imagick, mongodb, igbinary, sodium, redis, mcrypt, luasandbox, Zend OPcache

**Nextcloud version:** 15.0.7 - 15.0.7.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 14.0.10

**Where did you install Nextcloud from:** updater.phar

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - admin_audit: 1.5.0
 - announcementcenter: 3.4.1
 - apporder: 0.6.0
 - bookmarks: 1.0.2
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.1
 - dav: 1.8.1
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notes: 2.6.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - phonetrack: 0.5.0
 - provisioning_api: 1.5.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - systemtags: 1.5.0
 - tasks: 0.9.8
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - twofactor_totp: 2.1.2
 - twofactor_u2f: 2.1.3
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - activitylog
 - encryption
 - files_markdown
 - support
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.7.0",
    "installed": true,
    "forcessl": true,
    "loglevel": 2,
    "maintenance": false,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "share_folder": "\/Shared",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logdateformat": "Y-m-d H:i:s O",
    "logtimezone": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "appstore.experimental.enabled": true,
    "trashbin_retention_obligation": "auto",
    "updater.release.channel": "production",
    "htaccess.RewriteBase": "\/",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": false,
    "theme": "",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:** macOS 10.14.4

## Logs

Nothing in the logs.

### PR DESCRIPTION
**Pull request by kesselb**
**Quota**
image

**Unlimited Quota**
image

I would like to propose two further changes:

- ~Remove the progress bar because it looks much cleaner without.~
- ~Change 3,3% of 5 GB to 169,9 MB of 5 GB used because its much easier to understand~

### CODE REVIEW

**Comment by bpcurse** [comment]
What about showing the percentage additionally? e.g. in parentheses

**Comment by jancborchardt** [comment]
> Change 3,3% of 5 GB to 169,9 MB of 5 GB used because its much easier to understand

Sounds good! The bar is already a percentage visualization, so we don’t need to have it additionally. I would only say to not have decimal spaces since in this case just saying "170 MB of 5 GB" is much better to read.

> Remove the progress bar because it looks much cleaner without.

The bar is an important visualization element so this should stay. :) In the future we want to do more with it as there’s also data which comes from other apps like Talk (shared files) and probably others. Compare to iPhone storage – that way you can easily see what uses how much:

**Comment by kesselb** [comment]
> The bar is an important visualization element so this should stay. :) In the future we want to do more with it as there’s also data which comes from other apps like Talk (shared files) and probably others. Compare to iPhone storage – that way you can easily see what uses how much:

Also for unlimited quota? If so this pr is superfluous :thinking:

**Comment by jancborchardt** [comment]
> Also for unlimited quota? If so this pr is superfluous thinking

If you have unlimited quota then it doesn’t really matter, so we don’t need the bar in that case. At least not there in Files. :) We can still see about it as soon as we do more visualization with the bar.

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Wrong button.
Bump @nextcloud/designers

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
