### PR TITLE
[stable22] Show registered breadcrumb detail views in breadcrumb menu

### PR DESCRIPTION
**Pull request by julien-nc**
Backport of #27946 

Not sure why the backportbot fails to backport that.

### CODE REVIEW

**Comment by eneiluj** [comment]
@szaimen No reaction from the buildbot. I tried to push the built js files in stable21, i'll do it here if it works.

**Review by szaimen — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure unrelated

**Pull request merged**
