### PR TITLE
Fx translations with trailing colon

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix https://github.com/nextcloud/serverinfo/pull/333#discussion_r858436514

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Review by Valdnet — APPROVED** [review]

**Comment by nickvergessen** [comment]
That's fine. I didn't know when we updated to symfony translation anymore, but then it was 22

**Pull request merged**
