### PR TITLE
[stable10] Update containers to latest version

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @rullzer @LukasReschke 

see also #2047

### CODE REVIEW

**Comment by MorrisJobke** [comment]
```
There was 1 failure:
1) Test\Memcache\APCuTest::testDec
Failed asserting that -1 is false.
/drone/src/github.com/nextcloud/server/tests/lib/Memcache/Cache.php:90
```

This looks like this PHP7.0 breaking change - let me check the PR for master for this.

**Comment by MorrisJobke** [comment]
To test on the current PHP 7 we should maybe backport #1227 and #1230 (otherwise APCu on PHP 7 is broken for stable10 🙈 ) - cc @karlitschek

**Comment by karlitschek** [comment]
please backport 👍

**Comment by nickvergessen** [comment]
👍

**Comment by rockihack** [comment]
@MorrisJobke `Call to undefined method OC\\LargeFileHelper::getFileSizeViaCOM()` since https://github.com/nextcloud/server/pull/2048/commits/3f457943b05dc17cfc8c8f5348c2050b5fd34fb2.

You forgot to remove the function call here: https://github.com/nextcloud/server/blob/f7a505ded6826cb024af7df787918bd2b78c925c/lib/private/LargeFileHelper.php#L101

**Pull request merged**
