### PR TITLE
Border-radius does not need the vendor prefixes anymore

### PR DESCRIPTION
**Pull request by MorrisJobke**
See http://caniuse.com/#search=border-radius

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by pixelipo** [comment]
Just a note for @nextcloud/designers - vendor prefixes should **never** be used in production. They were introduced for developers to test and experiment with work-in-progress CSS specs.

**Comment by jancborchardt** [comment]
Hm @pixelipo, using vendor-prefixes is quite a common way for progressive enhancement. It's unfortunate it has to be done, but basically everyone uses them in production, or used them for a long time when there were so many discrepancies.

**Comment by pixelipo** [comment]
@jancborchardt it's common. I know. We (the developers) screwed up the system. In fact, that's why all the new CSS WIP specs (e.g. grid) don't have vendor-prefixes. We overused them so much that they decided to scrape them altogether. Now, if you want to test experimental CSS spec, you must enable special flags in browser developer tools.

So, point in case is - they shouldn't be used in production code. 

https://www.quirksmode.org/blog/archives/2010/03/css_vendor_pref.html

**Comment by jancborchardt** [comment]
@pixelipo ok cool, thanks for the info! :) So it's good that they are not needed and @MorrisJobke is cleaning up. We'll then pay attention to not introducing any where not needed.

**Comment by mikebabb** [comment]
Vendor prefixes aren't just for experimentation - they help users of browsers not entirely up to date see things consistently until their browser vendor implements the non-prefixed version as well.

As you say, @pixelipo, `border-radius` doesn't need them any more so that's good. In general, it's a little tidier to remove unnecessary prefixes as you come across them, but it isn't true that you should "never have any vendor prefixes in production code". They serve a purpose other than developer experimentation.

**Comment by pixelipo** [comment]
@mikebabb nope. They were always meant __only for experimentation/testing__ . The fact that frontend developers started using them to push unfinished CSS features to production doesn't mean that was the purpose.

Quite the contrary, that fact has lead W3.org to start using browser flags instead.

**Comment by jancborchardt** [comment]
Kinda off-topic, but I love that we have so many cool people in our design team! :D

**Pull request merged**
