### PR TITLE
format links in comments

### PR DESCRIPTION
**Pull request by blizzz**
It adds an OCP.Comments API accessible for any consumers of the Comments  infrastructure to reuse it. The first methods are to transform between rich and plain representation, specifically for links. I kept mentions formatting out for now to keep the changes small. 

The File comments app also makes use of it and renders links as links.

As for the behaviour: https is hidden in the link text, insecure protocol is shown. Otherwise, the link text cannot be changed.

An alternative way would be to introduce markdown as a whole, but this would have a bigger impact. If desired → for 14.

One issue is left and I call out for help to @nextcloud/designers 

As soon as a <a> tag is present,  any white space between the neighbouring strings are eliminated. The source is correct. Any ideas?

screenshot_20180103_132019

solves #7609

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> As soon as a tag is present, any white space between the neighbouring strings are eliminated. The source is correct. Any ideas?

I fixed it by adding a margin. Works now.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]
Works!

**Comment by jancborchardt** [comment]
@blizzz I can't see specific target="_blank" there, do we make sure these links always open in a new tab to not throw out of the flow?

**Comment by blizzz** [comment]
> @blizzz I can't see specific target="_blank" there, do we make sure these links always open in a new tab to not throw out of the flow?

Is this 1990 asking? Of course not. It's upon the user's decision whether to open it on a new page,  tab, or not. The consistence way is to keep the default behaviour. Not even Google is so insane to act like this. No, don't let the mad Facebugs and Twitterrs reintroduce this anti pattern. Good citizens like Github, Wikipedia or the New York Times don't do it, too.

**Comment by jancborchardt** [comment]
@blizzz there's problems with that though:
- when you go back to files, the sidebar doesn't really open on that comment again, you need to manually get and scroll back
- in the Talk app, clicking a link would lead to a dropped call.

That's what causes the real problems. I don't care if it's 1990 or not, but if it breaks people's flow. And it clearly does here.

**Comment by blizzz** [comment]
I agree that software should be as easy to  use as possible, on the other side I don't think users  should be treated more stupid than they may be. No flow is broken in the current state, because

* the user can  open the  link in the current page
* the user can open the link in a new tab or window
  * this also works on mobile/touch
  * and even on IE6! http://www.whattoget.net/files/u2/ie6-addmurlin.png

However, adding _blank there brings the issue that the user cannot open the link on the current page due to our dictate. It is an irreversible action, because browser do not offer a context menu entry for  "Open Link in This Tab". It is added code that takes functionality away. It is an anti-feature.

**Comment by jancborchardt** [comment]
Please keep in mind that the default is that people simply tap the link. And in these cases the breakage mentioned above happens, dropped calls etc. It will be an annoying papercut. "Open in new tab" does not exist for a normal person.

I'm not arguing about ideological standards of web development and "user choice" here. Not being able to open an _external_ link in the current tab is _not_ an issue in this case, or at least not as grave as the break of flow and state which happens otherwise.

cc @MorrisJobke @skjnldsv @juliushaertl

**Comment by blizzz** [comment]
The default across browsers is, that the click or tap opens in the same page. That's what you can rely on. The user doesn't know what customization a website does until he figures out. So, website can create a mess and destroy consistent behaviour across browsers, needlessly. As user, you can only assume default behavior thus, as it is safest.

It's not about ideological whatever, i agree, it's about breaking functionality and consistent behaviour and patronizing users.

**Comment by jancborchardt** [comment]
Sorry, no. You are making the assumption that people are technical like you and know how to open links in new tabs. This is not the case for regular users, which we cater to.

Check https://talky.io or https://meet.jit.si – both similar products. They of course open links in new tabs because otherwise the state would be lost and the call would drop. If this happens by default for Nextcloud Talk, or even in Files or elsewhere where we have comments, people are not going to use it. So please let's make sure that external links open in new tabs.

(cc @karlitschek too, this is a really exhausting argument we should not need to have, and the issue needs to be fixed.)

**Comment by blizzz** [comment]
As stated with examples above you'll examples for both ways, which results in an unpredictable behaviour for all users. Using the long tap, context menu or middle click is not black magic, even for regular users. 

I get your point, but also after talking on IRC the case is not as clear cut as you may think. A suggestion popped up to have a config setting about this in Talk, though I doubt you'll be happy with that, are you?

**Comment by jancborchardt** [comment]
> Using the long tap, context menu or middle click is not black magic, even for regular users.

It might not be »black magic«, but it’s not as much of a routine as you expect, being a very tech-knowledgeable person. I did many user tests and you wouldn’t believe what comes up there.
And even for the people who know about context menus or long tap, this should not be something necessary to do to _not_ drop out of a call.

> I get your point, but also after talking on IRC the case is not as clear cut as you may think. A suggestion popped up to have a config setting about this in Talk, though I doubt you'll be happy with that, are you?

That just illustrates the problem more … we design Nextcloud for regular people, not for folks who hang out on IRC or like to wade through settings. I thought that was clear, and I recommend you check out the article »[Choosing our preferences](http://ometer.com/preferences.html)«.

-------------------

At this point I’m really out of the discussion. I don’t see why my arguments so far are not clear to illustrate the huge UX problem in this case. I really don’t like the lesson to come with the user annoyment and bug reports.

**Comment by Schmuuu** [comment]
Hi,

If I may add my opinion here. I'd consider myself a rather technical user and administer a server for family and friends. 
Speaking for me: Just to be sure I would always do a click with middle mouse button to not be thrown out of a session. And I learned to do that, because some web services really kill the current session when clicking a link, which I always found not user friendly. So for myself I would love to have the _blank added.

Speaking for the users of my servers: they will definitely not open the links in a new tab, will leave the server every time they click a link and will be annoyed. 

In my humble opinion: Nextcloud when actually used is the "center" of business. Why would I want to leave the Nextcloud web GUI (by following a link)? If I'm done, I close the tab - *after logging out*. 

So from reading I totally agree with @jancborchardt and would love to have it his way. 
No offense @blizzz

**Comment by tcitworld** [comment]
While were at it why not adding `rel=noopener noreferer` ? https://mathiasbynens.github.io/rel-noopener/

**Comment by blizzz** [comment]
@Schmuuu added in #7739

@tcitworld PR? :)

**Comment by blizzz** [comment]
@jancborchardt just  to check back: if you're having a call  in Talk and talk about some file and clikc on the Files app, it should also open in  a new tab, no?

**Comment by jancborchardt** [comment]
@blizzz yes – until we can basically switch to other parts of Nextcloud while not breaking the call, and display an overlay of the other person's video in a corner – we need to open even links to Files in new tabs.
However what would of course be great is to show the preview of that file inside the chat. :) Maybe even the ability to open it big from there, as the Gallery does, while staying in the Talk app. However that's a bigger feature, and the new tab opening we need anyway. :)

@Schmuuu thank you for the confirmation. And thanks to @blizzz for implementing it in Files and Talk. It really works very well. :)

**Pull request merged**
