### PR TITLE
Remove conflicting multiselect

### PR DESCRIPTION
**Pull request by skjnldsv**
See #1831 
@blizzz can you check the ldap please?

It should be using the other jQuery ui multiselect, this is the last location I could find where it was being used :)

@nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
@MorrisJobke ideally 15. But if this is too complicated, i'll add a stricter css rule to backport it to 15 and make sure we ignore this conflict :)

**Comment by skjnldsv** [comment]
I was able to complete the full setup and use the multiselect without any issues. The multiselect in core have nothing to do with the multiselect used in the ldap config
Let's review!

**Review by ChristophWurst — APPROVED** [review]
Checked with `rg multiselect -g \!3rdparty -t js -M 150` and couldn't find any occurences of a multiselect apart from the Vue one.

:+1: (50% :elephant:)

**Comment by MorrisJobke** [comment]
I'm unsure if we should do this that late in the cycle. Also it looks like ldap is depending on this.

**Review by MorrisJobke — APPROVED** [review]
Works 👍

**Comment by MorrisJobke** [comment]
> I'm unsure if we should do this that late in the cycle.

I would like to get some feedback from @juliushaertl @rullzer and @nickvergessen about this.

**Comment by rullzer** [comment]
It seems to work. Let's do it to avoid weird patches.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
