### PR TITLE
[stable9] Fixes not allowed increasing of link share permissions

### PR DESCRIPTION
**Pull request by rullzer**
Backport of #2100

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Missing the integration test here

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by nickvergessen** [comment]
What about 
> Missing the integration test here

@rullzer

**Pull request merged**
