### PR TITLE
Wrong email sender fix #18730

### LINKED ISSUE #18730: Wrong email sender in app sharebymail when sending password to owner
### Steps to reproduce
1. Configure share by email with "enforce password"
2. Configure share by email without "send password per email"
3. Share any file with an external receiver by email

### Expected behaviour
The email, which sends the automatical generated password to me (the owner of the shared file) is sent by the nextcloud configured email sender

### Actual behaviour
The email I receive is sent by me, i.e. sender and receiver are the same.
This behaviour is bad due to the fact, that the configured email sender ist not allowd to send as an other user

### Server configuration
share by email as described in steps to reproduce
email-server with SMTP, STARTTLS and login authentication
**Operating system:**
Linux nextcloud 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
**Web server:**
apache2 2.4.25-3+deb9u7

**Database:**
MariaDB 10.1.38-MariaDB-0+deb9u1 Debian 9.8

**PHP version:**
PHP 7.3.6-1+0~20190531112546.39+jessie~1.gbp6131b7
**Nextcloud version:** (see Nextcloud admin page)
17.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from older version
**Where did you install Nextcloud from:**
nextcloud-repository
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_antivirus: 2.2.1
  - files_downloadactivity: 1.6.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trackdownloads: 1.6.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.5
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - metadata: 0.10.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - systemtags: 1.7.0
  - text: 1.1.1
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - survey_client
  - theming
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
root@nextcloud:/var/www/nextcloud/apps/sharebymail/lib# sudo -u www-data /usr/bin/php /var/www/nextcloud/occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.imed.uni-magdeburg.de",
            "docshare-extern.med.ovgu.de",
            "ummd-drive.med.ovgu.de",
            "docshare-extern.imed.uni-magdeburg.de",
            "ummd-drive.imed.uni-magdeburg.de"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "auth.bruteforce.protection.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_language": "de",
        "defaultapp": "files",
        "allow_user_to_change_display_name": false,
        "updater.release.channel": "stable",
        "theme": "gradient",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Berlin",
        "logdateformat": "[Y-m-d H:i:s] ",
        "log_rotate_size": "104857600",
        "overwrite.cli.url": "https:\/\/docshare-extern.med.ovgu.de\/nextcloud",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 1200,
        "session_keepalive": true,
        "skeletondirectory": "",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory
Webdav
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by exner104**
Wrong email sender in app sharebymail when sending password to owner fix #18730

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Good catch!

**Review by kesselb — APPROVED** [review]

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/44eba5cdc68651cd0915891420f31af42b8de5c3/apps/sharebymail/lib/ShareByMailProvider.php#L434-L442

Probably not bad to have the same sender name as the other email. xyz via nextcloud.

**Comment by rullzer** [comment]
Good point @kesselb 
Could you fix that @exner104 ?

**Comment by kesselb** [comment]
@rullzer we failed :see_no_evil: `\OCP\Util::getDefaultEmailAddress($instanceName)` but `$instanceName` was undefined without the additional senderName logic.

**Comment by exner104** [comment]
@kesselb indeed I used in my 1 approch the variables $instanceName and $senderName without initializing them.
With the additional code from your advice theese variables are defined, so I think the code is now correct.

**Comment by rullzer** [comment]
Gave it a quick spin and it works.

@exner104 normally we require commits to be signed off. See https://github.com/nextcloud/server/pull/18733/checks?check_run_id=379067761.
But let me merge this and or your next PR you can :)

**Pull request merged**
