### PR TITLE
Register with potentially updated namespace

### LINKED ISSUE #2663: Failed to run Repair steps on ugrade to server 18 RC 1
From my private instances upgrade today:

### Steps to reproduce
1. Upgrade to 18 RC on beta channel via web updates

### Expected behaviour
Upgrade succeeds flawlessly

### Actual behaviour
Talk repair steps fail and have to be run via occ.

## Server configuration detail

**Operating system:** Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.28

**PHP version:** 

7.2.24-0ubuntu0.18.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, pspell, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.0 RC1 - 18.0.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** from 17.0.2

**Where did you install Nextcloud from:** tarball

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - audioplayer: 2.8.4
 - bookmarks: 2.3.4
 - calendar: 2.0.0-beta3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.6
 - cookbook: 0.5.7
 - dav: 1.14.0
 - deck: 0.7.0
 - drawio: 0.9.4
 - dropit: 0.3.0
 - event_update_notification: 1.0.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 0.21.0
 - maps: 0.1.2
 - news: 14.1.0
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - polls: 0.10.4
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - qownnotesapi: 19.9.0
 - ransomware_protection: 1.5.1
 - recommendations: 0.6.0
 - richdocuments: 3.5.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.0-alpha.2
 - support: 1.1.0
 - survey_client: 1.6.0
 - suspicious_login: 3.0.1
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - telephoneprovider: 1.0.2
 - text: 1.2.3
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.1
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - announcementcenter
 - audioplayer_editor
 - encryption
 - files_external
 - files_markdown
 - files_mindmap
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.0.8",
    "installedat": "1326327271.69",
    "lastupdatedat": "1338667774.87",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "maintenance": false,
    "loglevel": 2,
    "trusted_domains": [
        "o.schiwon.me",
        "ovin.schiwon.me"
    ],
    "secret": "***REMOVED SENSITIVE VALUE***",
    "share_folder": "\/Shared",
    "appstoreenabled": true,
    "trashbin_retention_obligation": "auto",
    "appstore.experimental.enabled": true,
    "updater.release.channel": "beta",
    "updater.server.url": "https:\/\/updates.nextcloud.com\/internal_updater_server\/",
    "mysql.utf8mb4": true,
    "debug": false,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "overwrite.cli.url": "https:\/\/ovin.schiwon.me",
    "htaccess.RewriteBase": "\/",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "PLAIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "app_install_overwrite": [
        "apporder",
        "audioplayer",
        "deck",
        "drawio",
        "qownnotesapi",
        "tasks",
        "dropit",
        "issuetemplate",
        "news",
        "polls",
        "telephoneprovider",
        "contacts",
        "event_update_notification",
        "maps",
        "files_mindmap",
        "ransomware_protection"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0

**Operating system:** Arch Linux

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
{
  "reqId": "5QiihPahIEbQeIfjTDaZ",
  "level": 1,
  "time": "2020-01-03T18:37:37+00:00",
  "remoteAddr": "92.195.38.130",
  "user": "--",
  "app": "updater",
  "method": "GET",
  "url": "/core/ajax/update.php?requesttoken=yXXAK8e4BdF%2F7z6fZt6XETlywn2h%2F3ui0FMj3SDsEDE%3D%3ArF6FZZfrUr45jVvtF5rzPl5FsS3NuEzDqBBvsw%2FdIQI%3D",
  "message": "\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"spreed\" in appstore",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
  "version": "17.0.2.1"
}
{
  "reqId": "5QiihPahIEbQeIfjTDaZ",
  "level": 1,
  "time": "2020-01-03T18:37:37+00:00",
  "remoteAddr": "92.195.38.130",
  "user": "--",
  "app": "updater",
  "method": "GET",
  "url": "/core/ajax/update.php?requesttoken=yXXAK8e4BdF%2F7z6fZt6XETlywn2h%2F3ui0FMj3SDsEDE%3D%3ArF6FZZfrUr45jVvtF5rzPl5FsS3NuEzDqBBvsw%2FdIQI%3D",
  "message": "\\OC\\Updater::upgradeAppStoreApp: Update app \"spreed\" from appstore",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
  "version": "17.0.2.1"
}
{
  "reqId": "5QiihPahIEbQeIfjTDaZ",
  "level": 3,
  "time": "2020-01-03T18:37:39+00:00",
  "remoteAddr": "92.195.38.130",
  "user": "--",
  "app": "no app in context",
  "method": "GET",
  "url": "/core/ajax/update.php?requesttoken=yXXAK8e4BdF%2F7z6fZt6XETlywn2h%2F3ui0FMj3SDsEDE%3D%3ArF6FZZfrUr45jVvtF5rzPl5FsS3NuEzDqBBvsw%2FdIQI%3D",
  "message": {
    "Exception": "OCP\\AppFramework\\QueryException",
    "Message": "Could not resolve OCA\\Talk\\AppInfo\\Application! Class OCA\\Talk\\AppInfo\\Application does not exist",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/minion/ovin-perm/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 115,
        "function": "resolve",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "OCA\\Talk\\AppInfo\\Application"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/ServerContainer.php",
        "line": 150,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "OCA\\Talk\\AppInfo\\Application",
          true
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/apps/spreed/appinfo/app.php",
        "line": 22,
        "function": "query",
        "class": "OC\\ServerContainer",
        "type": "->",
        "args": [
          "OCA\\Talk\\AppInfo\\Application"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/legacy/app.php",
        "line": 265,
        "args": [
          "/var/www/minion/ovin-perm/apps/spreed/appinfo/app.php"
        ],
        "function": "require_once"
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/legacy/app.php",
        "line": 155,
        "function": "requireAppFile",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameter replaced ***"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/legacy/app.php",
        "line": 964,
        "function": "loadApp",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameter replaced ***"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/legacy/app.php",
        "line": 907,
        "function": "executeRepairSteps",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameter replaced ***",
          {
            "step": "OCA\\Talk\\Migration\\FixNamespaceInDatabaseTables"
          }
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/Installer.php",
        "line": 199,
        "function": "updateApp",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/Updater.php",
        "line": 453,
        "function": "updateAppstoreApp",
        "class": "OC\\Installer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/Updater.php",
        "line": 263,
        "function": "upgradeAppStoreApps",
        "class": "OC\\Updater",
        "type": "->",
        "args": [
          [
            "announcementcenter",
            "audioplayer",
            "audioplayer_editor",
            "calendar",
            "contacts",
            "deck",
            "drawio",
            "dropit",
            "event_update_notification",
            "files_markdown",
            "files_mindmap",
            "groupfolders",
            "maps",
            "polls",
            "qownnotesapi",
            "ransomware_protection",
            "*** sensitive parameter replaced ***",
            "telephoneprovider"
          ],
          true
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/Updater.php",
        "line": 131,
        "function": "doUpgrade",
        "class": "OC\\Updater",
        "type": "->",
        "args": [
          "18.0.0.8",
          "17.0.2.1"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/core/ajax/update.php",
        "line": 213,
        "function": "upgrade",
        "class": "OC\\Updater",
        "type": "->",
        "args": []
      }
    ],
    "File": "/var/www/minion/ovin-perm/lib/private/AppFramework/Utility/SimpleContainer.php",
    "Line": 106,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
  "version": "17.0.2.1"
}
{
  "reqId": "5QiihPahIEbQeIfjTDaZ",
  "level": 3,
  "time": "2020-01-03T18:37:39+00:00",
  "remoteAddr": "92.195.38.130",
  "user": "--",
  "app": "updater",
  "method": "GET",
  "url": "/core/ajax/update.php?requesttoken=yXXAK8e4BdF%2F7z6fZt6XETlywn2h%2F3ui0FMj3SDsEDE%3D%3ArF6FZZfrUr45jVvtF5rzPl5FsS3NuEzDqBBvsw%2FdIQI%3D",
  "message": "\\OC\\Repair::error: Repair error: Repair step 'OCA\\Talk\\Migration\\FixNamespaceInDatabaseTables' is unknown",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
  "version": "17.0.2.1"
}
{
  "reqId": "5QiihPahIEbQeIfjTDaZ",
  "level": 3,
  "time": "2020-01-03T18:37:39+00:00",
  "remoteAddr": "92.195.38.130",
  "user": "--",
  "app": "no app in context",
  "method": "GET",
  "url": "/core/ajax/update.php?requesttoken=yXXAK8e4BdF%2F7z6fZt6XETlywn2h%2F3ui0FMj3SDsEDE%3D%3ArF6FZZfrUr45jVvtF5rzPl5FsS3NuEzDqBBvsw%2FdIQI%3D",
  "message": {
    "Exception": "Exception",
    "Message": "Repair step 'OCA\\Talk\\Migration\\FixNamespaceInDatabaseTables' is unknown",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/minion/ovin-perm/lib/private/legacy/app.php",
        "line": 972,
        "function": "addStep",
        "class": "OC\\Repair",
        "type": "->",
        "args": [
          "OCA\\Talk\\Migration\\FixNamespaceInDatabaseTables"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/legacy/app.php",
        "line": 907,
        "function": "executeRepairSteps",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameter replaced ***",
          {
            "step": "OCA\\Talk\\Migration\\FixNamespaceInDatabaseTables"
          }
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/Installer.php",
        "line": 199,
        "function": "updateApp",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/Updater.php",
        "line": 453,
        "function": "updateAppstoreApp",
        "class": "OC\\Installer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/Updater.php",
        "line": 263,
        "function": "upgradeAppStoreApps",
        "class": "OC\\Updater",
        "type": "->",
        "args": [
          [
            "announcementcenter",
            "audioplayer",
            "audioplayer_editor",
            "calendar",
            "contacts",
            "deck",
            "drawio",
            "dropit",
            "event_update_notification",
            "files_markdown",
            "files_mindmap",
            "groupfolders",
            "maps",
            "polls",
            "qownnotesapi",
            "ransomware_protection",
            "*** sensitive parameter replaced ***",
            "telephoneprovider"
          ],
          true
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/lib/private/Updater.php",
        "line": 131,
        "function": "doUpgrade",
        "class": "OC\\Updater",
        "type": "->",
        "args": [
          "18.0.0.8",
          "17.0.2.1"
        ]
      },
      {
        "file": "/var/www/minion/ovin-perm/core/ajax/update.php",
        "line": 213,
        "function": "upgrade",
        "class": "OC\\Updater",
        "type": "->",
        "args": []
      }
    ],
    "File": "/var/www/minion/ovin-perm/lib/private/Repair.php",
    "Line": 122,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
  "version": "17.0.2.1"
}
```
</details>

<details><summary>Browser log</summary>

</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix https://github.com/nextcloud/spreed/issues/2663

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant: I trust the almighty talk wizard :sparkles:

**Review by blizzz — APPROVED** [review]
reasonable

**Review by kesselb — APPROVED** [review]
LGTM :+1: I guess `getAppInfo` is not using autoload to fetch information.

**Pull request merged**
