### PR TITLE
Add OpenAPI scopes

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/openapi-extractor/pull/24

### CODE REVIEW

**Review by provokateurin — CHANGES_REQUESTED** [review]
The appropriate scopes should be set before this is merged

**Comment by provokateurin** [comment]
This should also be backported to 28

**Review by provokateurin — APPROVED** [review]

**Review by bigcat88 — APPROVED** [review]

**Comment by skjnldsv** [comment]
/skjnldsv-backport to stable28

(Testing)

**Pull request merged**
