### PR TITLE
Only show checkbox on hover/focus + accessibility fixes

### PR DESCRIPTION
**Pull request by skjnldsv**
@nextcloud/accessibility @nextcloud/designers 

kazam

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Fine by me. But @nextcloud/designers should have a look as well

**Comment by juliushaertl** [comment]
I think we should always show them on mobile, otherwise there would be no hint, that you could select multiple entries.

**Comment by skjnldsv** [comment]
@juliushaertl every app do that on mobile. I never seen any checkbox chown. you can always see that on long click (whatsapp, messenger, gallery...) or clicking the avatar (same here) :)

**Comment by juliushaertl** [comment]
Ok, didn't thought about that, but makes sense then :wink:

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
here, done! :)

**Comment by rullzer** [comment]
Failing CI: https://drone.nextcloud.com/nextcloud/server/9391/249

**Comment by skjnldsv** [comment]
@rullzer I'm not sure it's related: 
`sh: 1: kill: No such process`

**Comment by skjnldsv** [comment]
Yep, passes!
https://drone.nextcloud.com/nextcloud/server/9394/249

**Pull request merged**
