### PR TITLE
chore(3rdparty): update symfony/mailer to 5.4.22

### PR DESCRIPTION
**Pull request by kesselb**
## Summary

Update symfony mailer to 5.4.22.

## TODO

- [x] CI
- [x] Merge https://github.com/nextcloud/3rdparty/pull/1483
- [x] Rebase

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by mejo- — APPROVED** [review]
To rephrase Joas' words: "the CI is happy, so am I".

**Comment by come-nc** [comment]
> /update-3rdparty

Some day we’ll get it right :-(

It seems `${{ github.event.issue.pull_request.base.ref }}` was empty instead of being `master`: https://github.com/nextcloud/server/actions/runs/5739770063/job/15556134168

**Review by come-nc — APPROVED** [review]

**Comment by nickvergessen** [comment]
unit test is fixed in https://github.com/nextcloud/server/pull/39705

**Pull request merged**
