### PR TITLE
Add beame-insta-ssl integration for secure remote access

### PR DESCRIPTION
**Pull request by ilyash**
[beame-insta-ssl](https://github.com/beameio/beame-insta-ssl/) allows secure remote access, similarly to pagekite. This PR contains Nextcloud integration with beame-insta-ssl.

### CODE REVIEW

**Comment by ilyash** [comment]
Screenshots:

01-not-installed
02-no-creds
03-stopped
04-running
05-link-works

In case the beame-insta-ssl process was killed or after server restart:
06-crashed

**Comment by MorrisJobke** [comment]
We are not accepting apps in the server repo. If you want to have your app available to install in every instance, then publish it in the app store: https://apps.nextcloud.com

Thanks

**Comment by MorrisJobke** [comment]
See https://docs.nextcloud.com/server/12/developer_manual/app/publishing.html rough app store guidelines.


Thanks for creating an app anyways 👍

**Comment by jospoortvliet** [comment]
Yeah, great app - we can create a repo for it in the Nextcloud project, however. I'll shoot an email about that ;-)

**Pull request closed without merging**
