### PR TITLE
[stable12] Fix oracle db

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Check for additional `PDO::FETCH_KEY_PAIR` usages
- [x] Check for additional empty string comparisons
- [x] Execute oracle tests locally and in VM

### CODE REVIEW

**Comment by nickvergessen** [comment]
Ready for review, but lets merge for 12.0.2 only

**Review by MorrisJobke — APPROVED** [review]
Code change looks good 👍

**Comment by MorrisJobke** [comment]
@daita Could you also run this in your environment? That would be nice.

**Comment by daita** [comment]
run smooth. well as smooth as oracle can be.

Made some action, just a reminder that only few apps are working under oracle :]

**Review by ArtificialOwl — APPROVED** [review]

**Pull request merged**
