### PR TITLE
Theming: theme flow redirection page

### PR DESCRIPTION
**Pull request by juliusknorr**
Fix for #7104

please review @nextcloud/theming 

bildschirmfoto vom 2017-11-08 13-03-53

### CODE REVIEW

**Comment by skjnldsv** [comment]
An example of how to get to this page?

**Comment by juliushaertl** [comment]
You need to open index.php/login/flow with the OCS-APIREQUEST header set to "true" and click the button.

I use the ModHeader chrome extension to set custom header values.

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
Works perfectly fine!

**Review by LukasReschke — APPROVED** [review]
Neat :)

**Comment by MorrisJobke** [comment]
Backport in #7114

**Pull request merged**
