### PR TITLE
[stable17] relax strict getHome behaviour for LDAP users in a shadow state

### PR DESCRIPTION
**Pull request by blizzz**
backport of #17717

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
CI fails

**Comment by blizzz** [comment]
let's postpone

**Comment by blizzz** [comment]
> CI fails

were just phpunit version related incompatibilities

**Review by skjnldsv — APPROVED** [review]

**Comment by juliushaertl** [comment]
@blizzz Please squash the fixups. :wink:

**Review by ChristophWurst — APPROVED** [review]
:+1: (:elephant:)

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
