### PR TITLE
[stable27] Fix npm audit

### PR DESCRIPTION
**Pull request by nextcloud-command**
# Audit report

This audit fix resolves 21 of the total 30 vulnerabilities found in your project.

## Updated dependencies
* [@adobe/css-tools](#user-content-\@adobe\/css-tools)
* [@babel/traverse](#user-content-\@babel\/traverse)
* [@cypress/request](#user-content-\@cypress\/request)
* [@jimp/core](#user-content-\@jimp\/core)
* [@jimp/custom](#user-content-\@jimp\/custom)
* [@nextcloud/cypress](#user-content-\@nextcloud\/cypress)
* [browserify-sign](#user-content-browserify-sign)
* [cypress](#user-content-cypress)
* [ejs](#user-content-ejs)
* [express](#user-content-express)
* [follow-redirects](#user-content-follow-redirects)
* [load-bmfont](#user-content-load-bmfont)
* [nextcloud-vue-collections](#user-content-nextcloud-vue-collections)
* [node-vibrant](#user-content-node-vibrant)
* [parse-bmfont-xml](#user-content-parse-bmfont-xml)
* [phin](#user-content-phin)
* [select2](#user-content-select2)
* [tar](#user-content-tar)
* [wait-on](#user-content-wait-on)
* [webpack-dev-middleware](#user-content-webpack-dev-middleware)
* [xml2js](#user-content-xml2js)
### @adobe/css-tools <a href="#user-content-\@adobe\/css-tools" id="\@adobe\/css-tools">#</a>
* @adobe/css-tools Improper Input Validation and Inefficient Regular Expression Complexity
* Severity: **moderate** (CVSS 5)
* Reference: [https://github.com/advisories/GHSA-prr3-c3m5-p7q2](https://github.com/advisories/GHSA-prr3-c3m5-p7q2)
* Affected versions: <4.3.2
* Package usage:
  * `node_modules/@adobe/css-tools`

### @babel/traverse <a href="#user-content-\@babel\/traverse" id="\@babel\/traverse">#</a>
* Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code
* Severity: **critical** 🚨 (CVSS 9.4)
* Reference: [https://github.com/advisories/GHSA-67hx-6x53-jw92](https://github.com/advisories/GHSA-67hx-6x53-jw92)
* Affected versions: <7.23.2
* Package usage:
  * `node_modules/@babel/traverse`

### @cypress/request <a href="#user-content-\@cypress\/request" id="\@cypress\/request">#</a>
* Server-Side Request Forgery in Request
* Severity: **moderate** (CVSS 6.1)
* Reference: [https://github.com/advisories/GHSA-p8p7-x288-28g6](https://github.com/advisories/GHSA-p8p7-x288-28g6)
* Affected versions: <=2.88.12
* Package usage:
  * `node_modules/@cypress/request`

### @jimp/core <a href="#user-content-\@jimp\/core" id="\@jimp\/core">#</a>
* Caused by vulnerable dependency:
  * [phin](#user-content-phin)
* Affected versions: <=0.21.4--canary.1163.d07ed6254d130e2995d24101e93427ec091016e6.0
* Package usage:
  * `node_modules/@jimp/core`

### @jimp/custom <a href="#user-content-\@jimp\/custom" id="\@jimp\/custom">#</a>
* Caused by vulnerable dependency:
  * [@jimp/core](#user-content-\@jimp\/core)
* Affected versions: <=0.21.4--canary.1163.d07ed6254d130e2995d24101e93427ec091016e6.0
* Package usage:
  * `node_modules/@jimp/custom`

### @nextcloud/cypress <a href="#user-content-\@nextcloud\/cypress" id="\@nextcloud\/cypress">#</a>
* Caused by vulnerable dependency:
  * [cypress](#user-content-cypress)
* Affected versions: 
* Package usage:
  * `node_modules/@nextcloud/cypress`

### browserify-sign <a href="#user-content-browserify-sign" id="browserify-sign">#</a>
* browserify-sign upper bound check issue in `dsaVerify` leads to a signature forgery attack
* Severity: **high** (CVSS 7.5)
* Reference: [https://github.com/advisories/GHSA-x9w5-v3q2-3rhw](https://github.com/advisories/GHSA-x9w5-v3q2-3rhw)
* Affected versions: 2.6.0 - 4.2.1
* Package usage:
  * `node_modules/browserify-sign`

### cypress <a href="#user-content-cypress" id="cypress">#</a>
* Caused by vulnerable dependency:
  * [@cypress/request](#user-content-\@cypress\/request)
* Affected versions: 4.3.0 - 12.17.4
* Package usage:
  * `node_modules/cypress`

### ejs <a href="#user-content-ejs" id="ejs">#</a>
* ejs lacks certain pollution protection
* Severity: **moderate**
* Reference: [https://github.com/advisories/GHSA-ghr5-ch3p-vcr6](https://github.com/advisories/GHSA-ghr5-ch3p-vcr6)
* Affected versions: <3.1.10
* Package usage:
  * `node_modules/ejs`

### express <a href="#user-content-express" id="express">#</a>
* Express.js Open Redirect in malformed URLs
* Severity: **moderate** (CVSS 6.1)
* Reference: [https://github.com/advisories/GHSA-rv95-896h-c2vc](https://github.com/advisories/GHSA-rv95-896h-c2vc)
* Affected versions: <4.19.2
* Package usage:
  * `node_modules/express`

### follow-redirects <a href="#user-content-follow-redirects" id="follow-redirects">#</a>
* Follow Redirects improperly handles URLs in the url.parse() function
* Severity: **moderate** (CVSS 6.1)
* Reference: [https://github.com/advisories/GHSA-jchw-25xp-jwwc](https://github.com/advisories/GHSA-jchw-25xp-jwwc)
* Affected versions: <=1.15.5
* Package usage:
  * `node_modules/follow-redirects`

### load-bmfont <a href="#user-content-load-bmfont" id="load-bmfont">#</a>
* Caused by vulnerable dependency:
  * [phin](#user-content-phin)
* Affected versions: >=1.4.0
* Package usage:
  * `node_modules/load-bmfont`

### nextcloud-vue-collections <a href="#user-content-nextcloud-vue-collections" id="nextcloud-vue-collections">#</a>
* Caused by vulnerable dependency:
  * [@nextcloud/axios](#user-content-\@nextcloud\/axios)
  * [@nextcloud/vue](#user-content-\@nextcloud\/vue)
* Affected versions: 0.6.0 - 0.10.0
* Package usage:
  * `node_modules/nextcloud-vue-collections`

### node-vibrant <a href="#user-content-node-vibrant" id="node-vibrant">#</a>
* Caused by vulnerable dependency:
  * [@jimp/custom](#user-content-\@jimp\/custom)
* Affected versions: 3.1.5 - 3.1.6
* Package usage:
  * `node_modules/node-vibrant`

### parse-bmfont-xml <a href="#user-content-parse-bmfont-xml" id="parse-bmfont-xml">#</a>
* Caused by vulnerable dependency:
  * [xml2js](#user-content-xml2js)
* Affected versions: <=1.1.4
* Package usage:
  * `node_modules/parse-bmfont-xml`

### phin <a href="#user-content-phin" id="phin">#</a>
* phin may include sensitive headers in subsequent requests after redirect
* Severity: **moderate** (CVSS 4.3)
* Reference: [https://github.com/advisories/GHSA-x565-32qp-m3vf](https://github.com/advisories/GHSA-x565-32qp-m3vf)
* Affected versions: <3.7.1
* Package usage:
  * `node_modules/phin`

### select2 <a href="#user-content-select2" id="select2">#</a>
* Improper Neutralization of Input During Web Page Generation in Select2
* Severity: **moderate** (CVSS 6.1)
* Reference: [https://github.com/advisories/GHSA-rf66-hmqf-q3fc](https://github.com/advisories/GHSA-rf66-hmqf-q3fc)
* Affected versions: <4.0.6
* Package usage:
  * `node_modules/select2`

### tar <a href="#user-content-tar" id="tar">#</a>
* Denial of service while parsing a tar file due to lack of folders count validation
* Severity: **moderate** (CVSS 6.5)
* Reference: [https://github.com/advisories/GHSA-f5x3-32g6-xq36](https://github.com/advisories/GHSA-f5x3-32g6-xq36)
* Affected versions: <6.2.1
* Package usage:
  * `node_modules/tar`

### wait-on <a href="#user-content-wait-on" id="wait-on">#</a>
* Caused by vulnerable dependency:
  * [axios](#user-content-axios)
* Affected versions: 5.0.0-rc.0 - 7.1.0
* Package usage:
  * `node_modules/wait-on`

### webpack-dev-middleware <a href="#user-content-webpack-dev-middleware" id="webpack-dev-middleware">#</a>
* Path traversal in webpack-dev-middleware
* Severity: **high** (CVSS 7.4)
* Reference: [https://github.com/advisories/GHSA-wr3j-pwj9-hqq6](https://github.com/advisories/GHSA-wr3j-pwj9-hqq6)
* Affected versions: <=5.3.3
* Package usage:
  * `node_modules/webpack-dev-middleware`

### xml2js <a href="#user-content-xml2js" id="xml2js">#</a>
* xml2js is vulnerable to prototype pollution
* Severity: **moderate** (CVSS 5.3)
* Reference: [https://github.com/advisories/GHSA-776f-qx25-q3cc](https://github.com/advisories/GHSA-776f-qx25-q3cc)
* Affected versions: <0.5.0
* Package usage:
  * `node_modules/xml2js`

### CODE REVIEW

**Comment by blizzz** [comment]
Cypress error:

> `AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-cy-files-navigation-settings-quota]`, but never found it.`

**Comment by susnux** [comment]
> Related or flaky?

sounds flaky

**Comment by blizzz** [comment]
> > Related or flaky?
> 
> sounds flaky

There is a similar failing test with Selenium :thinking:  https://drone.nextcloud.com/nextcloud/server/55895/57/4

**Comment by blizzz** [comment]
@susnux *  │ ✖  Navigation.cy.ts                         00:55        9        5        4        -        - │* keeps failing

> AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-cy-files-navigation-settings-quota]`, but never found it.

**Comment by susnux** [comment]
Seems like the module export changed, so for mocking in the test we need to default import.
Long story short: Fixed.

**Pull request merged**
