### PR TITLE
Set a default request timeout

### PR DESCRIPTION
**Pull request by rullzer**
This to avoid endless running processes.
A default timeout of 30 seconds should cover the 99% case. If a job need
specific longer time it should set that.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]
Yes, makes sense :+1:

**Review by nickvergessen — APPROVED** [review]

**Comment by kesselb** [comment]
Please have a look at https://github.com/nextcloud/server/pull/16149 and why 30 seconds might be a bad default value.

**Comment by rullzer** [comment]
> Please have a look at #16149 and why 30 seconds might be a bad default value.

@kesselb that PR was about raising it to 30s.
But I'm fine with a followup for a different value. But for now the value is unlimited. And 30s seems more sane than unlimited :wink:

**Comment by andrewperry** [comment]
Here is where @kesselb suggested 30s might be sane (or at least more sane than 50s): https://github.com/nextcloud/server/issues/14926#issuecomment-493067602

This seems to be affecting a lot of people at the moment, so I also wonder whether the https://apps.nextcloud.com is running slower at present. When I test that page with Google it is suggesting times upwards of 50 seconds for "Time to interactive": https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fapps.nextcloud.com%2Fapi%2Fv1%2Fapps.json

This might mean that 30s won't fix the issue people are experiencing and that an initial DevOps focus within Nextcloud on increasing the speed of the response for https://apps.nextcloud.com/api/v1/apps.json would be good, without waiting for this patch to roll through.

**Comment by nickvergessen** [comment]
Well the idea of this PR is not to solely fix the issue you mentioned, but fix a general misbehave with long running tasks.

So yeah the apps.json should still be looked into.

**Comment by InfamousUser** [comment]
Not a crappy network thing. You can't reasonably expect a 300MB app to install in 30 seconds, not everyone runs Nextcloud on enterprise hardware. My connection allows it to download in about a minute in a pure, uncongested situation, not to mention the time it takes to actually install.

**Comment by nickvergessen** [comment]
The app download has been adjusted to 120s in the upcoming 18.0.1 already

**Comment by rscircus** [comment]
Nice, thanks!

**Comment by InfamousUser** [comment]
Wonderful!

**Comment by bernd-wechner** [comment]
This should be a setting available in config.php! 30 seconds did not suffice for us, and the consequences are a pain to diagnose (simply a lacking app store) and this and related issues a challenge to find. Clearly if performance is so poor on some networks it's no drama to up this to 300 (and then it does work) but one needs to know to do so, and perforce this setting belongs in config.php IMHO.

**Comment by ChristophWurst** [comment]
File a feature request please.

This is an old PR

**Pull request merged**
