### PR TITLE
Fix enable/disable user audit message

### LINKED ISSUE #16060: Enabling user writes "User disabled" log entry
### Steps to reproduce
Disable a user
enable the previously disabled user

### Expected behaviour
Two entries should be created in the audit.log file. The first one saying the user has been disabled, the second one saying the user has been enabled

### Actual behaviour
Two entries are created in the audit.log file. They both say the "User disabled"

## Server configuration detail

**Operating system:** Linux 4.4.0-150-generic #176-Ubuntu SMP Wed May 29 18:56:26 UTC 2019 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.26

**PHP version:** 

7.0.33-0ubuntu0.16.04.5
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 15.0.8 - 15.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - admin_audit: 1.5.0
 - audioplayer: 2.7.2
 - bruteforcesettings: 1.3.0
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.3
 - dashboard: 6.0.0
 - dav: 1.8.2
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_antivirus: 2.1.1
 - files_external: 1.6.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - previewgenerator: 2.1.0
 - provisioning_api: 1.5.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - sharelisting: 0.2.0
 - sharerenamer: 2.6.0
 - survey_client: 1.3.0
 - systemtags: 1.5.0
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - encryption
 - support
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "blah"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.8.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "loglevel": 1,
    "theme": "",
    "maintenance": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "overwritewebroot": "\/cloud",
    "trashbin_retention_obligation": "auto, 90",
    "versions_retention_obligation": "auto, 90",
    "updater.release.channel": "stable",
    "overwrite.cli.url": "http:\/\/blah\/cloud",
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "enabledPreviewProviders": {
        "0": "OC\\Preview\\PNG",
        "1": "OC\\Preview\\JPEG",
        "2": "OC\\Preview\\GIF",
        "14": "OC\\Preview\\TIFF"
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "simpleSignUpLink.shown": false,
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": []
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"9WJxfSt1q6lMNzudj0UN","level":1,"time":"2019-06-24T10:37:39+00:00","remoteAddr":"172.16.1.223","user":"blah","app":"admin_audit","method":"PUT","url":"\/cloud\/ocs\/v2.php\/cloud\/users\/test2\/disable","message":"User disabled: \"test2\"","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.8.1"}
{"reqId":"DiLbaOiAiL2sekEM0khK","level":1,"time":"2019-06-24T10:38:12+00:00","remoteAddr":"172.16.1.223","user":"blah","app":"admin_audit","method":"PUT","url":"\/cloud\/ocs\/v2.php\/cloud\/users\/test2\/enable","message":"User disabled: \"test2\"","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.8.1"}
```
</details>

<details><summary>Browser log</summary>

</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #16060

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Took me three attempts to see the difference

**Comment by rullzer** [comment]
> Took me three attempts to see the difference

phew... not just me...

**Pull request merged**
