### PR TITLE
Add missing doc changes and limit string length 4000 to new columns

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up to #31679 
Also adding #31513 even when disabled since #31580 so apps can keep it in mind for the future

Related https://github.com/nextcloud/documentation/pull/8174

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by skjnldsv** [comment]
cc @come-nc

**Comment by blizzz** [comment]
superseded by https://github.com/nextcloud/server/pull/31872 but the doc parts can be taken over still

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
(rebased on master, removed redundant commit, only doc changes left, good to merge)

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
no code change → merging

**Pull request merged**
