### PR TITLE
Move comments to webpack

### PR DESCRIPTION
**Pull request by rullzer**
One more app to move over ;)

* Bundles all the js statically
* Bundles the scss as well

Saves 2 requests and the file can be served statically by the webserver :) YAY!

TODO:
- [x] Currently breaks on the atwho and Caret (@ChristophWurst  can you have a look?)

Future work:
- [ ] Move Caret and AtWho to proper webpack dependencies so they are kept up to date

### CODE REVIEW

**Comment by ChristophWurst** [comment]
>     * Move Caret and AtWho to proper webpack dependencies so they are kept up to date

https://github.com/ichord/At.js <- not on npm and not maintained anymore :cry:

**Comment by ChristophWurst** [comment]
>     * @ChristophWurst  can you have a look?

Had a look. Fixed it :wink: 

Explanation: the comments app webpack bundles its own jQuery, but the way the files are structured, they don't properly include their dependencies and therefore js will resolve the *global* jQuery instead. And that instance does not have the `jQuery.fn.atwho`.

I now tell webpack to use a global `jQuery` variable for the jquery dependency, hence atwho registers on the global one. The local one won't be used/packaged. This is an ugly dependency on server again but I'm sure there might be edge cases where the comments app assumes other jquery plugins that are just registered globally but not locally, so this should be the safe bet.

In the long run we should adjust our js files to be proper modules. Not only will it make dependencies more clear, js can find the objects faster if they are scoped.

**Comment by ChristophWurst** [comment]
>     * Move Caret and AtWho to proper webpack dependencies so they are kept up to date

@rullzer mind opening a ticket for it so we don't forget?

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by rullzer** [comment]
Seems jsunit was not totally happy... lets see if this fixes it.

**Pull request merged**
