### PR TITLE
properly handle cases where cache wrappers block access

### LINKED ISSUE #1621: ACLCacheWrapper::formatCacheEntry must not return `false`
For (at least) one of our users I get the following error, when he logs in. Dashboard widget is empty.

`Return value of OC\\Files\\Cache\\Wrapper\\CacheWrapper::getCacheEntryFromSearchResult() must implement interface OCP\\Files\\Cache\\ICacheEntry or be null, bool returned`

I've also checked it for another user, no problems there.

<details>
<summary>Output from occ</summary>

```
./occ files:recommendations:recommend uid
An unhandled exception has been thrown:
TypeError: Return value of OC\Files\Cache\Wrapper\CacheWrapper::getCacheEntryFromSearchResult() must implement interface OCP\Files\Cache\ICacheEntry or be null, bool returned in /var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php:314
Stack trace:
#0 /var/www/html/lib/private/Files/Cache/Wrapper/CacheJail.php(323): OC\Files\Cache\Wrapper\CacheWrapper->getCacheEntryFromSearchResult(Object(OC\Files\Cache\CacheEntry))
nextcloud/recommendations#1 /var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php(312): OC\Files\Cache\Wrapper\CacheJail->getCacheEntryFromSearchResult(Object(OC\Files\Cache\CacheEntry))
nextcloud/recommendations#2 /var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php(312): OC\Files\Cache\Wrapper\CacheWrapper->getCacheEntryFromSearchResult(Object(OC\Files\Cache\CacheEntry))
nextcloud/recommendations#3 /var/www/html/lib/private/Files/Cache/QuerySearchHelper.php(151): OC\Files\Cache\Wrapper\CacheWrapper->getCacheEntryFromSearchResult(Object(OC\Files\Cache\CacheEntry))
nextcloud/recommendations#4 /var/www/html/lib/private/Files/Node/Folder.php(273): OC\Files\Cache\QuerySearchHelper->searchInCaches(Object(OC\Files\Search\SearchQuery), Array)
nextcloud/recommendations#5 /var/www/html/lib/private/Files/Node/Folder.php(504): OC\Files\Node\Folder->search(Object(OC\Files\Search\SearchQuery))
nextcloud/recommendations#6 /var/www/html/apps/recommendations/lib/Service/RecentlyEditedFilesSource.php(65): OC\Files\Node\Folder->getRecent(7)
nextcloud/recommendations#7 /var/www/html/apps/recommendations/lib/Service/RecommendationService.php(90): OCA\Recommendations\Service\RecentlyEditedFilesSource->getMostRecentRecommendation(Object(OC\User\User), 7)
nextcloud/recommendations#8 [internal function]: OCA\Recommendations\Service\RecommendationService->OCA\Recommendations\Service\{closure}(Array, Object(OCA\Recommendations\Service\RecentlyEditedFilesSource))
nextcloud/recommendations#9 /var/www/html/apps/recommendations/lib/Service/RecommendationService.php(91): array_reduce(Array, Object(Closure), Array)
nextcloud/recommendations#10 /var/www/html/apps/recommendations/lib/Command/GetRecommendations.php(78): OCA\Recommendations\Service\RecommendationService->getRecommendations(Object(OC\User\User))
nextcloud/recommendations#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Recommendations\Command\GetRecommendations->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud/recommendations#12 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud/recommendations#13 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Recommendations\Command\GetRecommendations), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud/recommendations#14 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud/recommendations#15 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud/recommendations#16 /var/www/html/console.php(99): OC\Console\Application->run()
nextcloud/recommendations#17 /var/www/html/occ(11): require_once('/var/www/html/c...')
nextcloud/recommendations#18 {main}
```

</details>

<details>
<summary>nextcloud.log</summary>

```
{"reqId":"oES00YxYifWrBJKi3CCt","level":3,"time":"2021-08-03T12:59:01+00:00","remoteAddr":"ip.address","user":"uid","app":"index","method":"GET","url":"/apps/recommendations/api/recommendations/always","message":"Return value of OC\\Files\\Cache\\Wrapper\\CacheWrapper::getCacheEntryFromSearchResult() must implement interface OCP\\Files\\Cache\\ICacheEntry or be null, bool returned","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36","version":"22.0.0.11","exception":{"Exception":"Exception","Message":"Return value of OC\\Files\\Cache\\Wrapper\\CacheWrapper::getCacheEntryFromSearchResult() must implement interface OCP\\Files\\Cache\\ICacheEntry or be null, bool returned","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Recommendations\\Controller\\RecommendationController"},"always"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Recommendations\\Controller\\RecommendationController","always",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"recommendations.recommendation.always"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/recommendations/api/recommendations/always"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"Return value of OC\\Files\\Cache\\Wrapper\\CacheWrapper::getCacheEntryFromSearchResult() must implement interface OCP\\Files\\Cache\\ICacheEntry or be null, bool returned","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Files/Cache/Wrapper/CacheJail.php","line":323,"function":"getCacheEntryFromSearchResult","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":[{"__class__":"OC\\Files\\Cache\\CacheEntry"}]},{"file":"/var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php","line":312,"function":"getCacheEntryFromSearchResult","class":"OC\\Files\\Cache\\Wrapper\\CacheJail","type":"->","args":[{"__class__":"OC\\Files\\Cache\\CacheEntry"}]},{"file":"/var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php","line":312,"function":"getCacheEntryFromSearchResult","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":[{"__class__":"OC\\Files\\Cache\\CacheEntry"}]},{"file":"/var/www/html/lib/private/Files/Cache/QuerySearchHelper.php","line":151,"function":"getCacheEntryFromSearchResult","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":[{"__class__":"OC\\Files\\Cache\\CacheEntry"}]},{"file":"/var/www/html/lib/private/Files/Node/Folder.php","line":273,"function":"searchInCaches","class":"OC\\Files\\Cache\\QuerySearchHelper","type":"->","args":[{"__class__":"OC\\Files\\Search\\SearchQuery"},{"0":"And 14 more entries, set log level to debug to see all entries","":{"__class__":"OC\\Files\\Cache\\Wrapper\\CacheJail"},"Kollektive/FG_Faschingsgilde/":{"__class__":"OCA\\Collectives\\Mount\\RootEntryCache"},"FG_Faschingsgilde/":{"__class__":"OC\\Files\\Cache\\Wrapper\\CachePermissionsMask"},"TS_Turnerschaft/Verträge/":{"__class__":"OC\\Files\\Cache\\Wrapper\\CachePermissionsMask"},"FG_Faschingsgilde/Medien/":{"__class__":"OC\\Files\\Cache\\Wrapper\\CachePermissionsMask"}}]},{"file":"/var/www/html/lib/private/Files/Node/Folder.php","line":504,"function":"search","class":"OC\\Files\\Node\\Folder","type":"->","args":[{"__class__":"OC\\Files\\Search\\SearchQuery"}]},{"file":"/var/www/html/apps/recommendations/lib/Service/RecentlyEditedFilesSource.php","line":65,"function":"getRecent","class":"OC\\Files\\Node\\Folder","type":"->","args":[7]},{"file":"/var/www/html/apps/recommendations/lib/Service/RecommendationService.php","line":90,"function":"getMostRecentRecommendation","class":"OCA\\Recommendations\\Service\\RecentlyEditedFilesSource","type":"->","args":[{"__class__":"OC\\User\\User"},7]},{"function":"OCA\\Recommendations\\Service\\{closure}","class":"OCA\\Recommendations\\Service\\RecommendationService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/recommendations/lib/Service/RecommendationService.php","line":91,"function":"array_reduce","args":[[{"__class__":"OCA\\Recommendations\\Service\\RecentlyCommentedFilesSource"},"*** sensitive parameter replaced ***",{"__class__":"OCA\\Recommendations\\Service\\RecentlySharedFilesSource"}],{"__class__":"Closure"},"*** sensitive parameter replaced ***"]},{"file":"/var/www/html/apps/recommendationas/lib/Controller/RecommendationController.php","line":88,"function":"getRecommendations","class":"OCA\\Recommendations\\Service\\RecommendationService","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"always","class":"OCA\\Recommendations\\Controller\\RecommendationController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Recommendations\\Controller\\RecommendationController"},"always"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Recommendations\\Controller\\RecommendationController"},"always"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Recommendations\\Controller\\RecommendationController","always",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"recommendations.recommendation.always"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/recommendations/api/recommendations/always"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php","Line":314},"CustomMessage":"--"},"id":"61093e9f33f12"}
```

</details>

### PR DESCRIPTION
**Pull request by icewind1991**
`CacheWrapper::formatCacheEntry` can return false for files that should be filtered out

Fixes https://github.com/nextcloud/groupfolders/issues/1621

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by PVince81** [comment]
possibly related, or needs additional fixing. https://github.com/nextcloud/groupfolders/issues/1464

**Comment by PVince81** [comment]
@icewind1991 seems psalm not happy

**Comment by skjnldsv** [comment]
Fixed psalm, ready to merge

**Comment by skjnldsv** [comment]
backport?

**Comment by MichaIng** [comment]
Is it possible and should be backport to `stable21` as well? If so, we should do from #29509 to not include the Psalm baseline change in the first place.

**Pull request merged**
