### PR TITLE
Change URL for desktop clients directly to pop-up

### PR DESCRIPTION
**Pull request by eppfel**
by adding `/#install-clients` to the URL

### CODE REVIEW

**Comment by rullzer** [comment]
LGTM

**Comment by nickvergessen** [comment]
👍

**Comment by jancborchardt** [comment]
Good stuff, also makes it work in the first run wizard :+1:

**Comment by eppfel** [comment]
That's why I even fixed a test over there: nextcloud/firstrunwizard#26 😉

**Pull request merged**
