### PR TITLE
[WIP] Port clear status after select

### PR DESCRIPTION
**Pull request by Pytal**
- For https://github.com/nextcloud/server/issues/35763

## Summary

Port the clear status after select to NcSelect

- [x] FIXME Initial dropdown width is not equal to input width https://github.com/nextcloud-deps/vue-select/pull/14

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Pytal** [comment]
The `width` property
https://github.com/sagalbot/vue-select/blob/857753655adbebae612518aab072ed7f4a8deaa0/src/directives/appendToBody.js#L4-L9
is ~10px less than it should be when opening the dropdown for the first time

Further investigations to be done

**Comment by Pytal** [comment]
The initial `width` issue on first open can be reproduced on Chrome on Windows and Linux

| | Screenshot |
--- | ---
**Chrome (Windows)** | image
**Chrome (Linux)** | image

<details>
<summary>Expected width</summary>

The width is normal when opening subsequent times

| | Screenshot |
--- | ---
**Opening subsequent times** | image

</details>

And also reproduces on Firefox on Windows but not Linux

| | Screenshot |
--- | ---
**Firefox (Windows)** | image
**Firefox (Linux)** | image

Further investigations needed

**Comment by Pytal** [comment]
Does the bug in https://github.com/nextcloud/server/pull/36372#issuecomment-1413037603 reproduce for you @artonge?

And based on the source of the `width` in https://github.com/sagalbot/vue-select/blob/v3.20.2/src/directives/appendToBody.js#L4-L9 and the assignment in https://github.com/nextcloud/nextcloud-vue/blob/v7.5.0/src/components/NcSelect/NcSelect.vue#L790-L791, any ideas how this could occur?

**Comment by artonge** [comment]
> Does the bug in [#36372 (comment)](https://github.com/nextcloud/server/pull/36372#issuecomment-1413037603) reproduce for you @artonge?

I can reproduce in Chrome on Linux and not on Firefox.

Maybe it is because the computation happens when the scale is less than 1 ?
It looks like we are animating the modal:
https://github.com/nextcloud/nextcloud-vue/blob/c1a15b3f6c5cec758cd0461b154821ef07fd5013/src/components/NcModal/NcModal.vue#L980-L983

**Comment by artonge** [comment]
It also happens if I open the modal, resize the window, which resize NcSelect. So probably nothing to do with the animation.

**Comment by Pytal** [comment]
Fixed upstream in https://github.com/nextcloud-deps/vue-select/pull/14

**Comment by Pytal** [comment]
Superseded by https://github.com/nextcloud/server/pull/36843

**Pull request closed without merging**
