### PR TITLE
fix encryption wrapper filesize for non existing files

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by artonge — COMMENTED** [review]
Shouldn't we throw a `OCP\Files\NotFoundException` ?

**Review by come-nc — CHANGES_REQUESTED** [review]
I think it should return `false` instead, since this is what is returned when `filesize` fails on local storage.

**Review by come-nc — APPROVED** [review]

**Pull request merged**
