### PR TITLE
[oc] Fix initMountPoints to set usersSetup earlier

### PR DESCRIPTION
**Pull request by rullzer**
This is needed because in some cases like LDAP, the user manager itself
might trigger avatar updates which would internally also call
initMountPoints with the same user. This could cause the same user to
be setup twice, and in some sharing situations could cause recursive
deduplication of shares by adding "(2)" every time.

See: https://github.com/owncloud/core/pull/26411

@blizzz @icewind1991 please have a look.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Ref #1915

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by blizzz** [comment]
useful anyway, but did we really suffer this underlying issue? thought it was fixed within LDAP or so. Well, good to have this either way.

**Pull request merged**
