### PR TITLE
Add Quick-Access to favorite folder in left sidepanel in files-app (Cleanup)

### PR DESCRIPTION
**Pull request by newhinton**
See #9714
See #9720
See #10176
@skjnldsv

### CODE REVIEW

**Comment by rullzer** [comment]
@newhinton cool stuff thanks.

But this has a ton of conflicts. Also a ton of commits.

Could I ask you to rebase on current master.
Also you can create branches in the main server repo so other people can more easily work on your branch as well :)

THNX.

**Comment by newhinton** [comment]
@rullzer Yes i have already seen that my forkupdate didn't work out as expected ;) I'll redo my latest PR's, tomorrow

**Comment by newhinton** [comment]
See #10320

**Comment by jospoortvliet** [comment]
@newhinton you coming to https://nextcloud.com/conf ?

**Pull request closed without merging**
