### PR TITLE
Apply black app icon style to newly installed app icons

### PR DESCRIPTION
**Pull request by juliusknorr**
When adding a new app the newly appearing icon will now also be in black.

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1: 

Please also backport?

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by juliushaertl** [comment]
@nickvergessen added the backport.to #665

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
