### PR TITLE
Sorts filepicker files by modified date

### LINKED ISSUE #645: Filepicker: sort by modified date (or better: respect sorting as in files app)
Oftentimes you want to pick files you recently uploaded or updated, like in mail attachments. Hence it would be cool if there would be a way to sort by modified date. Maybe even better, respect the sorting of the folders exactly as in the Files app.

cc @icewind1991

### PR DESCRIPTION
**Pull request by sagorika1996**
Fixes #645 

screenshot from 2018-03-14 16-23-11

### CODE REVIEW

**Comment by jancborchardt** [comment]
@icewind1991 @nextcloud/javascript need a code review here please :)

**Review by jancborchardt — COMMENTED** [review]
It’s great! What about the second part of the issue:

> Maybe even better, respect the sorting of the folders exactly as in the Files app.

**Comment by MorrisJobke** [comment]
Oh .. sorry we missed that one somehow :/

Code looks good so far. Getting the ordering of the folder could be tricky, because AFAIK we don't store this yet.

**Comment by jancborchardt** [comment]
@MorrisJobke ok, if that’s tricky let’s do @sagorika1996’s improvement here as a first step. :)

**Review by MorrisJobke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
I restarted the tests, there was an acceptance fail on files, so I want to be sure :)

Great work otherwise!

**Comment by MorrisJobke** [comment]
CI failures are unrelated.

**Pull request merged**
