### PR TITLE
Move OC.appswebroots to the bundle and deprecate oc_appswebroots

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@ChristophWurst Mind to rebase?

**Comment by MorrisJobke** [comment]
> @ChristophWurst Mind to rebase?

Let me do that.

**Comment by ChristophWurst** [comment]
> Let me do that.

Now waiting for you to `push --force-with-lease` :stuck_out_tongue:

**Comment by MorrisJobke** [comment]
CI is struggling with the Github problems and can't clone all steps. But JSUnit and the login acceptance tests are green -> merge

**Pull request merged**
