### PR TITLE
Allow using composer plugin with composer 2.2

### PR DESCRIPTION
**Pull request by juliusknorr**
Should fix the psalm test failure on prs

https://github.com/composer/composer/releases/tag/2.2.0
https://getcomposer.org/doc/06-config.md#allow-plugins

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by juliushaertl** [comment]
CI failure should be fixed by the next composer release https://github.com/composer/composer/issues/10387

**Comment by MichaIng** [comment]
Ah this fixes #30399, right? Missed that a fix is up already 👍.

**Review by MichaIng — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> Error: Cannot find file composer-bin-proxy:/home/runner/work/server/server/vendor-bin/psalm/vendor/vimeo/psalm/psalm to include

**Comment by juliushaertl** [comment]
Pushed a commit to ignore composers bin directory for now. Another related upstream issue https://github.com/vimeo/psalm/issues/7226

**Pull request merged**
