### PR TITLE
Adjust mysql parameters

### PR DESCRIPTION
**Pull request by juliusknorr**
Retrying https://github.com/nextcloud/server/pull/16328 to get our tests a bit more stable again. 

I also was wondering what the current timeout of drone tests is right now as the failing tests always seem to be around the 30 minute mark.

### CODE REVIEW

**Comment by kesselb** [comment]
It fails for pqsql too :disappointed: I think this might be related to the drone infrastructure and the database server running out of memory or into some timeout.

```
Index: tests/lib/TestCase.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/lib/TestCase.php	(revision b73df01945983c1deffe68b0964115fb8dddb4f9)
+++ tests/lib/TestCase.php	(date 1566209879109)
@@ -248,11 +248,11 @@
 		}
 		$dataDir = \OC::$server->getConfig()->getSystemValue('datadirectory', \OC::$SERVERROOT . '/data-autotest');
 		if (self::$wasDatabaseAllowed && \OC::$server->getDatabaseConnection()) {
-			$queryBuilder = \OC::$server->getDatabaseConnection()->getQueryBuilder();
+			$dbConnection = \OC::$server->getDatabaseConnection();
 
-			self::tearDownAfterClassCleanShares($queryBuilder);
-			self::tearDownAfterClassCleanStorages($queryBuilder);
-			self::tearDownAfterClassCleanFileCache($queryBuilder);
+			self::tearDownAfterClassCleanShares($dbConnection);
+			self::tearDownAfterClassCleanStorages($dbConnection);
+			self::tearDownAfterClassCleanFileCache($dbConnection);
 		}
 		self::tearDownAfterClassCleanStrayDataFiles($dataDir);
 		self::tearDownAfterClassCleanStrayHooks();
@@ -264,31 +264,31 @@
 	/**
 	 * Remove all entries from the share table
 	 *
-	 * @param IQueryBuilder $queryBuilder
+	 * @param IDBConnection $dbConnection
 	 */
-	static protected function tearDownAfterClassCleanShares(IQueryBuilder $queryBuilder) {
-		$queryBuilder->delete('share')
-			->execute();
+	static protected function tearDownAfterClassCleanShares(IDBConnection $dbConnection) {
+		$sql = $dbConnection->getDatabasePlatform()->getTruncateTableSQL('*PREFIX*share');
+		$dbConnection->executeUpdate($sql);
 	}
 
 	/**
 	 * Remove all entries from the storages table
 	 *
-	 * @param IQueryBuilder $queryBuilder
+	 * @param IDBConnection $dbConnection
 	 */
-	static protected function tearDownAfterClassCleanStorages(IQueryBuilder $queryBuilder) {
-		$queryBuilder->delete('storages')
-			->execute();
+	static protected function tearDownAfterClassCleanStorages(IDBConnection $dbConnection) {
+		$sql = $dbConnection->getDatabasePlatform()->getTruncateTableSQL('*PREFIX*storages');
+		$dbConnection->executeUpdate($sql);
 	}
 
 	/**
 	 * Remove all entries from the filecache table
 	 *
-	 * @param IQueryBuilder $queryBuilder
+	 * @param IDBConnection $dbConnection
 	 */
-	static protected function tearDownAfterClassCleanFileCache(IQueryBuilder $queryBuilder) {
-		$queryBuilder->delete('filecache')
-			->execute();
+	static protected function tearDownAfterClassCleanFileCache(IDBConnection $dbConnection) {
+		$sql = $dbConnection->getDatabasePlatform()->getTruncateTableSQL('*PREFIX*filecache');
+		$dbConnection->executeUpdate($sql);
 	}
 
 	/**
```

Most of the time `tearDownAfterClassCleanShares` is the last method until it fails. We could try to truncate the tables instead of deleting it.

**Comment by kesselb** [comment]
> Most of the time tearDownAfterClassCleanShares is the last method until it fails. We could try to truncate the tables instead of deleting it.

Does not work.

**Comment by kesselb** [comment]
@juliushaertl https://discourse.drone.io/t/resources-limitation-and-timeout/2316 there is a timeout setting for drone builds. Do you know the current value?

**Comment by juliushaertl** [comment]
Maybe @rullzer can check that in the drone UI, as I don't have access? 

But also just increasing the timeout isn't really fixing the issue. To me it seems that we have a slow drone runner node, where the database tests just take much longer than on the other ones. That would explain why they seem to be rather randomly failing.

**Comment by skjnldsv** [comment]
Please rebase :)

**Comment by juliushaertl** [comment]
Doesn't fix the issue, I'd say we close this until we have another idea or more computing power :disappointed:

**Pull request closed without merging**
