### PR TITLE
Contd: Add layer on top of LDAP methods to catch server disconnects and attempt re-connection

### PR DESCRIPTION
**Pull request by blizzz**
Continuation of #4992 

@bline I signed-off your commits so this test passes :) Please test whether my changes still work for you.

For Nc 13 we should aim for a cleaner solution, but this requires architectural changes. Alas, we need to backport it, so let's get this is as an intermediate step.

Fixes LDAP Server caused timeout with long-running processes where there is a too big gap between LDAP calls.

### CODE REVIEW

**Comment by bline** [comment]
Thanks @blizzz, I'll test this tonight.

**Comment by blizzz** [comment]
Unfortunately the ``controlPagedResultResponse`` does not work around this way.  With  https://github.com/nextcloud/server/pull/5122/files you can use the IntegrationTestPaging and will see it fails.  Likely ``invokeLDAPMethod()`` just does not handle this as reference.

**Comment by blizzz** [comment]
Possible solutions: 

(1) don't use this method against the invoker, because it is fired very soon after an LDAP operation took place. An idleTimeout sould not be effective here.

(2) expect the command name, accept ALL attributes as references (``invokeLDAPMethod($command, &...$arguments)``). Downside: many places where value instead of variables are passed. Makes it cumbersome.

For simplicity I'd go with (1), although I first liked the second more at first.  The final solution for 13 could adopt this.

**Comment by blizzz** [comment]
I created a backport to stable11 https://github.com/nextcloud/server/pull/5128

stable12 upcoming, but this is far easier as the code base is pretty much the same as master

**Comment by blizzz** [comment]
Tests succeeds, only ``DB=postgresENABLE_REDIS=truePHP=5.6`` runs into a timeout [sic!], but this is known from CI.

**Comment by blizzz** [comment]
Tested successfully by @bline as stated https://github.com/nextcloud/server/pull/5128#issuecomment-304537251

Still need a reviewer @nextcloud/ldap  :)

**Review by rullzer — APPROVED** [review]
Makes sense :+1:

**Comment by blizzz** [comment]
@karlitschek btw, backport OK? Down to 11?

**Comment by blizzz** [comment]
missing backport to 12: https://github.com/nextcloud/server/pull/5210

**Comment by karlitschek** [comment]
nice. definitely backport to 12 and 11

**Pull request merged**
