### PR TITLE
Add variable for border-radius and box-shadow

### PR DESCRIPTION
**Pull request by jancborchardt**
As mentioned in https://github.com/nextcloud/server/pull/6649

~~Already using the values for filter instead of box-shadow as used in https://github.com/nextcloud/server/pull/6669 – instead of the old `box-shadow: 0 1px 10px $color-box-shadow;`~~

### CODE REVIEW

**Comment by skjnldsv** [comment]
Don't you want to replace all the occurrences with the variable in this pr too? :)

**Comment by skjnldsv** [comment]
Where are we at here? :)

**Comment by jancborchardt** [comment]
Done and ready for review! :)

- I replaced all occurences of border-radius: 3px; in the files which are already scss. I would prefer to do the moving of other files to SCSS separately.
- I removed the popover-shadow variable again because it actually only had a single occurence, it’s very specific, and we already have the `$color-box-shadow`.

Let’s get this in, please review @nextcloud/designers – it’s just the border-radius standardization to 3px now. :)

**Review by pixelipo — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
Perfect!

**Comment by skjnldsv** [comment]
I always approve when I see the word "standardization"! :)

**Comment by jancborchardt** [comment]
Drone is irrelevant since this is CSS only → merging :)

**Pull request merged**
