### PR TITLE
harden seekable http stream a bit against failures

### LINKED ISSUE #20378: feof error in SeekableHttpStream.php
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Apply #20033, i.e., enable seeking in HTTP Storage Backends (e.g., S3 storage)
2. Sync Files via WebDAV

### Expected behaviour
Sync should work, nothing special

### Actual behaviour
I am getting errors in my log:

```
[PHP] Error: feof() expects parameter 1 to be resource, bool given at /var/www/html/lib/private/Files/Stream/SeekableHttpStream.php#156

GET /remote.php/webdav/<MoviePath/Movie.mp4
from XXX.XXX.XXX.211 by User.Name at 2020-04-09T08:17:22+00:00
```

### Server configuration

**Operating system:** Alpine Linux

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.3.16

**Nextcloud version:** 18.0.3 with changes from #20033 applied

**Updated from an older Nextcloud/ownCloud or fresh install:** Yes

**Where did you install Nextcloud from:** Docker Compose

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- lib/composer/composer/autoload_classmap.php
		- lib/composer/composer/autoload_static.php
		- lib/private/Files/ObjectStore/S3ObjectTrait.php
	- EXTRA_FILE
		- lib/private/Files/Stream/SeekableHttpStream.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/composer/composer/autoload_classmap.php] => Array
                        (
                            [expected] => 8548faf8c1ceb516d497ee9197e7294417f191ed0187ccb51ef08833f38ae51281282ddc7896826d2c28034650cf2a88c973654e52a5816647c02af53fc21426
                            [current] => 310208d69deed382f945b3cfda5c8040f52a71ded94c97729a1b3c79c758e566308da02667bcc187c29ec8c081719123ece0e02a1a90da2c2fed8cdcb20a9518
                        )

                    [lib/composer/composer/autoload_static.php] => Array
                        (
                            [expected] => 506d385c9cae5c011e3728d0f4a3d9c130e128351ef57e8611d9a7eaf0f6a0b6d46e642082d77681518e3a693024edb9af131861748a61e8ac2127d46f448461
                            [current] => 6fef2a2388646a2cb16266e0bdd9c42ae14ff52ec52e72683dd0052fa308bdeaf952cdf261fccdf0e34743239fb6e136bb566dcf6d2bbc5b1c895832fe660688
                        )

                    [lib/private/Files/ObjectStore/S3ObjectTrait.php] => Array
                        (
                            [expected] => c1ae283bbef18448dad20bd184c01f2b7b8754b794f6d5dafc6cd5ff822aec7c58611e6b229691e505aad1a4788cad49317f40fd505a1ed25ca040af28e7cfde
                            [current] => 956c0afb1cfc915c635b34a0d612d317cd57c953ce6adc7cadafce5930f0453f55937a71c57d4c4a97028a3bee6ccb2e636715674c30ef72f07e2182fef46def
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [lib/private/Files/Stream/SeekableHttpStream.php] => Array
                        (
                            [expected] => 
                            [current] => 74fc970be3597dd90e068096002a329a2317a6d98586a2db8f16f8963e608fb160852537b4777cba3debcf0964b89c43765fb5cc59befc0ee4f197a4a96e6f0f
                        )

                )

        )

)
```
</details>

**Are you using external storage, if yes which one:** S3 Primary Storage (Digitalocean Spaces)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome

**Operating system:** MacOS

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[PHP] Error: feof() expects parameter 1 to be resource, bool given at /var/www/html/lib/private/Files/Stream/SeekableHttpStream.php#156

GET /remote.php/webdav/<MoviePath/Movie.mp4
from XXX.XXX.XXX.211 by User.Name at 2020-04-09T08:17:22+00:00
```
</details>

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #20378

@stjosh can you check if this fixes the problem for you

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
make sense

**Review by juliusknorr — APPROVED** [review]
Sure

**Comment by stjosh** [comment]
Perfect, many thanks for the quick fix! 👌🏻

**Comment by MorrisJobke** [comment]
backport to stable18 is in #20965

**Comment by MorrisJobke** [comment]
backport to stable17 is in #20966

**Pull request merged**
