### PR TITLE
Fix file creation from template without ext

### PR DESCRIPTION
**Pull request by skjnldsv**
Reproducing:
1. Create a new text file 
2. Enter a name without the `.md` extension
3. Select any template

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
Code looks fine :+1:

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
⚙failures unrelated

**Comment by szaimen** [comment]
Were templates introduced with NC21?

**Comment by PVince81** [comment]
> Were templates introduced with NC21?

indeed, let's skip the NC 20 backport then

**Pull request merged**
