### PR TITLE
[downstream] Fix maindetailsview favorite star patch

### PR DESCRIPTION
**Pull request by LukasReschke**
From https://github.com/owncloud/core/pull/26658

### CODE REVIEW

**Comment by ChristophWurst** [comment]
js tests fail with 
```
PhantomJS 2.1.1 (Linux 0.0.0): Executed 835 of 837 (skipped 2) SUCCESS (21.785 secs / 20.841 secs)
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not a function (evaluating 'this.data.state()')
  at apps/files/js/file-upload.js:167
PhantomJS 2.1.1 (Linux 0.0.0): Executed 835 of 837 (skipped 2) ERROR (21.828 secs / 20.841 secs)
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not a function (evaluating 'this.data.state()')
  at apps/files/js/file-upload.js:167
PhantomJS 2.1.1 (Linux 0.0.0): Executed 835 of 837 (skipped 2) ERROR (21.831 secs / 20.841 secs)
```

**Comment by ChristophWurst** [comment]
@rullzer I assume https://github.com/nextcloud/server/blob/f0bb62f2fecd73e3ac828524d44796bf8d92fc32/apps/files/js/file-upload.js#L1171-L1176 will trigger the error, or at least that's why the error occurs *after* karma already prints its test summary. Apparently that callback is not fired when running the tests locally, therefore I don't get the errors either.

**Comment by ChristophWurst** [comment]
Found it: we pass in an OC.Uploader object, which does not have a ``state`` method. See https://github.com/nextcloud/server/blob/f0bb62f2fecd73e3ac828524d44796bf8d92fc32/apps/files/js/file-upload.js#L359-L1185.

**Comment by MorrisJobke** [comment]
@ChristophWurst Any news? I would love to see this fixed ;)

**Comment by ChristophWurst** [comment]
> @ChristophWurst Any news? I would love to see this fixed ;)

Done, but cannot verify whether it fixes the issue. Basically, I just removed the apparently dead code.

**Comment by ChristophWurst** [comment]
> All checks have passed
> 5 successful checks

Well, at least CI is happy :-)

**Pull request merged**
