### PR TITLE
fix(controller): Fix false booleans in multipart/form-data

### PR DESCRIPTION
**Pull request by nickvergessen**
## Summary
I was debugging an issue reported by our frontenders with a new API (ref https://github.com/nextcloud/spreed/pull/13871#discussion_r1858704769)
Turns out sending the boolean false in a post request sees it as `"false"` and therefore evaluates to `true`.
We have some code in place to "sometimes" translate that to `false` (see diff). I now need to extend this to `multipart/form-data`.

But at the same time I wonder why the check is there at all? When the controller requests a `boolean`, shouldn't we always convert `"false"` to `false` independent from request type?

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — COMMENTED** [review]
What about query parameters? There we currently only allow 0/1 for booleans and openapi-extractor has a quirk to workaround this, but it would be great if we could send proper boolean true/false

**Comment by nickvergessen** [comment]
> What about query parameters? There we currently only allow 0/1 for booleans and openapi-extractor has a quirk to workaround this, but it would be great if we could send proper boolean true/false

That is already working properly with the `settype` path:
https://3v4l.org/SolRs
```php
<?php

$value = '0';
settype($value, 'bool');
var_dump($value);
// bool(false)

$value = 'false';
settype($value, 'bool');
var_dump($value);
// bool(true)
```

In alignment via chat, I will make it match in all cases when the value is `'false'` and the controller wants a boolean

**Review by provokateurin — APPROVED** [review]
> That is already working properly with the settype path:

Hm ok then I have to check again :thinking:

**Review by Altahrim — APPROVED** [review]

**Pull request merged**
