### PR TITLE
Fix file permissions for SMB (read-only folders will be writeable) (#…

### PR DESCRIPTION
**Pull request by LukasReschke**
…25301)
- Fix file permissions for SMB (read-only folders will be writeable)
- Read-only folders won't be deletable
- Added comment for the read-only behaviour for folders

---

From https://github.com/owncloud/core/pull/25301

@icewind1991 please review.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@icewind1991 ❓ 😉

**Comment by icewind1991** [comment]
:+1:

**Comment by icewind1991** [comment]
Fixes #708

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
@LukasReschke @karlitschek This was in the 10 milestone. Should we backport this then?

**Comment by karlitschek** [comment]
yes. please backport

**Comment by icewind1991** [comment]
stable10: https://github.com/nextcloud/server/pull/743

**Pull request merged**
