### PR TITLE
Theming admin improvements

### PR DESCRIPTION
**Pull request by juliusknorr**
2nd part of #770 split
- Add preview of login screen
- Hide undo buttons on default values

requires #1026

### CODE REVIEW

**Comment by juliushaertl** [comment]
CI is happy, ready for review @nextcloud/designers @nextcloud/theming 

I've included #1026 for easier testing, will rebase to master once this is merged.

**Comment by mar1u5** [comment]
👍

**Comment by rullzer** [comment]
#1026 is in

**Comment by juliushaertl** [comment]
@rullzer rebase done.

**Comment by nickvergessen** [comment]
Works :+1:

**Comment by mar1u5** [comment]
Backport to `stable10` would be nice :grin: .. So that we have some more theming improvements up there :) @karlitschek

**Comment by nickvergessen** [comment]
Or we give people a reason to update to 11?
The fixes in this branch are not really critical but more like enhancements.

**Comment by LukasReschke** [comment]
Agreeing with @nickvergessen on that one.

**Comment by jancborchardt** [comment]
Yep, let’s not backport everything please. ;)

**Pull request merged**
