### PR TITLE
apps can have polyamorous relationships with bundles

### LINKED ISSUE #19104: Apps in bundle view appear only once
We list 7 entries in the enterprise bundle:

Screenshot_20200123_210119

Only 6 appear on the apps page:

Screenshot_20200123_210208

Because the SAML backend is also included in the enterprise bundle and only appears there.

Same behaviour down to Nc 16.

I guess some Vue Voodoo is needed :)

### PR DESCRIPTION
**Pull request by blizzz**
fixes #19104 

previously the backend was overwriting a bundle Id, if an app was having more. Now we send the whole list to the frontend.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
wtf :smile:

**Review by georgehrke — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Comment by blizzz** [comment]
would be smart of the backportbot would ignore commits by npmbuildbot

**Pull request merged**
