### PR TITLE
Bump symfony to 4.4.4

### PR DESCRIPTION
**Pull request by rullzer**
Requires:
- [x] https://github.com/nextcloud/3rdparty/pull/393
- [x] rebase

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> deprecated returning `null` from `Command::execute()`, return `0` instead

I think we do this in a lot of places

**Review by ChristophWurst — APPROVED** [review]

**Comment by rullzer** [comment]
> > deprecated returning `null` from `Command::execute()`, return `0` instead
> 
> I think we do this in a lot of places

I think so too. But depreactioin doesn't mean it breaks. So we should just fix it :)

**Comment by ChristophWurst** [comment]
> I think so too. But depreactioin doesn't mean it breaks. So we should just fix it :)

Let's document it :)

**Review by ChristophWurst — APPROVED** [review]
Let's do this!

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
