### PR TITLE
Improve readability of login logic

### PR DESCRIPTION
**Pull request by MorrisJobke**
* cleans up a bit call to the DI container
* improves readability of login logic

### CODE REVIEW

**Review by rullzer — DISMISSED** [review]
Makes sense to me! And some browsing did not make things blow up.

**Review by ChristophWurst — DISMISSED** [review]
Looks good!

**Review by nickvergessen — DISMISSED** [review]
Breaks integration tests:
> Trying to get property of non-object in /drone/src/github.com/nextcloud/server/build/integration/features/bootstrap/BasicStructure.php line 136

=> OCS response is invalid

**Comment by rullzer** [comment]
Ah yes. So it seems it is indeed still used. https://github.com/nextcloud/server/blob/master/lib/private/legacy/api.php#L102

So when using the (old deprectaed OCP\API::register).

**Comment by MorrisJobke** [comment]
> Ah yes. So it seems it is indeed still used. https://github.com/nextcloud/server/blob/master/lib/private/legacy/api.php#L102

Good point - but 🙌 for our integration tests to catch this one.

**Comment by rullzer** [comment]
Sure is.
So I guess we need to keep it around for a little while :disappointed:

**Comment by MorrisJobke** [comment]
I removed the drop of the methods and only kept the cleanup.

@rullzer @nickvergessen @LukasReschke Please re-review

**Review by rullzer — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
