### PR TITLE
dashboard: Add OpenAPI spec

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

From https://github.com/nextcloud/server/pull/36666. Adds the necessary annotations and descriptions.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by andrey18106 — APPROVED** [review]

**Review by bigcat88 — APPROVED** [review]

**Comment by juliushaertl** [comment]
General question, has there already been some discussion around stability requirements for the documented APIs? Just to be aware

**Review by juliusknorr — APPROVED** [review]

**Comment by bigcat88** [comment]
> General question, has there already been some discussion around stability requirements for the documented APIs? Just to be aware

AFAIK, no.

**Comment by provokateurin** [comment]
@juliushaertl Not yet, will follow later. Currently there are a bunch more things to do that have higher priority. If you try not introduce breaking changes that would be great though :)

**Comment by juliushaertl** [comment]
Sure :) Thanks for the update

**Pull request merged**
