### PR TITLE
Reduce indirection in AppManager

### PR DESCRIPTION
**Pull request by MorrisJobke**
Found while reviewing #16075

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
:eyes:

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Review by GretaD — APPROVED** [review]
shame on me then :D

**Comment by MorrisJobke** [comment]
> shame on me then :D

Not really, because it was not within your code, but was there already. Otherwise I would have fixed it in your PR ;)

**Pull request merged**
