### PR TITLE
enh(settings): Migrate admin settings for sharing to vue

### LINKED ISSUE #40588: [BITV] Replace all places with old NcMultiselect components with NcSelect components
There are still several places in our views where NcMultiselect components are used. Due to several reasons (inclusive contrast issues) we have to switch completely to NcSelect components.

Examples:

index.php/settings/admin/sharing
Screenshot from 2023-09-22 14-50-22

index.php/settings/admin
Screenshot from 2023-09-22 15-05-16

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #40588

## Summary
Migrate sharing settings to get rid of select2 group select. Needed for accessibility.
Also fixes the not working "exclude groups from sharing" select.

### Screenshots
before | after
---|---
Screen Shot 2023-11-17 at 17 06 01|Screen Shot 2023-11-17 at 17 04 13
Screen Shot 2023-11-17 at 17 05 37|Screen Shot 2023-11-17 at 17 04 57

#### Screen cast

https://github.com/nextcloud/server/assets/1855448/d53b2e1d-093d-4158-9355-9b99362ce57a

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by JuliaKirschenheuter — APPROVED** [review]
🥳 very nice!

**Review by Pytal — APPROVED** [review]

**Comment by ShGKme** [comment]
There is an issue with textarea:
image

I see a different state sometimes, not sure if it is an issue.
master | pr
---|---
image | image

**Comment by susnux** [comment]
> There is an issue with textarea: 

Will be fixed with the nextcloud-vue update

> I see a different state sometimes, not sure if it is an issue.

Thats because there is no such setting as disclaimer "disabled", before it just checks whether the disclaimer is falsy or truthy.
To distinguish I used following logic: If it is undefined then it is disabled, otherwise enabled.
It will be undefined if the setting is deleted on server, if you enable an empty string will be set on server.

**Review by ShGKme — APPROVED** [review]

**Comment by ShGKme** [comment]
Dron error is unrelated

**Comment by come-nc** [comment]
Drone error very related, this broke tests for master:
```
452	There were 4 errors:
453	
454	1) OCA\Settings\Tests\Settings\Admin\SharingTest::testGetFormWithoutExcludedGroups
455	ArgumentCountError: Too few arguments to function OCA\Settings\Settings\Admin\Sharing::__construct(), 4 passed in /drone/src/apps/settings/tests/Settings/Admin/SharingTest.php on line 68 and exactly 7 expected
456	
457	/drone/src/apps/settings/lib/Settings/Admin/Sharing.php:48
458	/drone/src/apps/settings/tests/Settings/Admin/SharingTest.php:68
459	
460	2) OCA\Settings\Tests\Settings\Admin\SharingTest::testGetFormWithExcludedGroups
461	ArgumentCountError: Too few arguments to function OCA\Settings\Settings\Admin\Sharing::__construct(), 4 passed in /drone/src/apps/settings/tests/Settings/Admin/SharingTest.php on line 68 and exactly 7 expected
462	
463	/drone/src/apps/settings/lib/Settings/Admin/Sharing.php:48
464	/drone/src/apps/settings/tests/Settings/Admin/SharingTest.php:68
465	
466	3) OCA\Settings\Tests\Settings\Admin\SharingTest::testGetSection
467	ArgumentCountError: Too few arguments to function OCA\Settings\Settings\Admin\Sharing::__construct(), 4 passed in /drone/src/apps/settings/tests/Settings/Admin/SharingTest.php on line 68 and exactly 7 expected
468	
469	/drone/src/apps/settings/lib/Settings/Admin/Sharing.php:48
470	/drone/src/apps/settings/tests/Settings/Admin/SharingTest.php:68
471	
472	4) OCA\Settings\Tests\Settings\Admin\SharingTest::testGetPriority
473	ArgumentCountError: Too few arguments to function OCA\Settings\Settings\Admin\Sharing::__construct(), 4 passed in /drone/src/apps/settings/tests/Settings/Admin/SharingTest.php on line 68 and exactly 7 expected
474	
475	/drone/src/apps/settings/lib/Settings/Admin/Sharing.php:48
476	/drone/src/apps/settings/tests/Settings/Admin/SharingTest.php:68
```

**Comment by nickvergessen** [comment]
Please update the documentation screenshots:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/file_sharing_configuration.html

**Comment by artonge** [comment]
Fix attempt here: https://github.com/nextcloud/server/pull/41637

**Comment by susnux** [comment]
> Please update the documentation screenshots

Done https://github.com/nextcloud/documentation/pull/11300

**Pull request merged**
