### PR TITLE
Allow to force a language and set it via the ocs api

### LINKED ISSUE #2686: Option to force a specific language
In NC11 `default_language` in `config.php` is ignored, right? In NC10 all was fine. 

Also I can't find `settings/languageCodes.php` file according to [this](https://docs.nextcloud.com/server/11/admin_manual/configuration_server/language_configuration.html).

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #2686

### CODE REVIEW

**Review by oparoz — COMMENTED** [review]
Good job in covering all options.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
I fixed the autoloader file.

**Comment by MorrisJobke** [comment]
cc @karlitschek for this backport 

@nickvergessen could you create the backport PR? Thanks

**Comment by karlitschek** [comment]
yes please 👍

**Comment by nickvergessen** [comment]
Backport in https://github.com/nextcloud/server/pull/5509

**Comment by MariusBluem** [comment]
Documentation (https://github.com/nextcloud/documentation/pull/514) ✅

**Review by LukasReschke — APPROVED** [review]

**Comment by dan-nkl** [comment]
I absolutely need this in Nextcloud 12. What options do I have?

**Comment by blizzz** [comment]
Wait for 12.0.1, it's already backported

**Pull request merged**
