### PR TITLE
add gpx mimetype

### PR DESCRIPTION
**Pull request by blizzz**
Just stumbled over https://gitlab.com/eneiluj/gpxpod-oc/wikis/admindoc#integration-in-files-app-optional-tested-with-owncloud-10-nextcloud-11-and-12 – why not shipping the mime type with us.

As opposite to further down I added an alias to "location" instead, perhaps we can have an icon for any location/geospatial/map/etc.-related files. GpxPod uses/suggests https://gitlab.com/eneiluj/gpxpod-oc/blob/master/img/gpx.svg (a location marker) but with the orange frame it does not look consistent to our other icons.

What do you think @jancborchardt @eneiluj ?

### CODE REVIEW

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Could you add a repair step with the current version number (to run only once): https://github.com/nextcloud/server/blob/c9e08a6445b50259d4450b65cf4ddb1515f762f2/lib/private/Repair/RepairMimeTypes.php#L146-L148

**Comment by blizzz** [comment]
@MorrisJobke thx for the hint!

Now, this is also offers a chance to include other related mime types of this makes sense. While at it, I also added kml, kmz, tcx.

**Comment by jancborchardt** [comment]
As filetype icon, you could use the Maps app icon: https://github.com/nextcloud/maps/blob/master/img/maps.svg (just needs to be made grey like the others).

cc @nextcloud/maps for checking out this nice integration step. :)

**Comment by blizzz** [comment]
@jancborchardt thx! Icon adjusted and added.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by eneiluj** [comment]
Nice ! Glad to see these mimetypes included.

**Comment by blizzz** [comment]
> Nice ! Glad to see these mimetypes included.

I take this as a 👍  :) → merging

**Pull request merged**
