### PR TITLE
[uc] Introduce pagination in files-filter report

### PR DESCRIPTION
**Pull request by icewind1991**
Downstream 26507

### CODE REVIEW

**Comment by rullzer** [comment]
Tests are not happy

**Comment by MorrisJobke** [comment]
@icewind Ping

**Comment by MorrisJobke** [comment]
@icewind1991 🏓

**Comment by icewind1991** [comment]
rebased, tests fixed

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Conflicts :(

**Comment by MorrisJobke** [comment]
@icewind1991 Failing unit tests

**Comment by MorrisJobke** [comment]
@icewind1991 Should we try to get this in 13 or is 14 fine?

**Comment by MorrisJobke** [comment]
Let's move this to 14.

**Comment by MorrisJobke** [comment]
@icewind1991 Ping

**Comment by MorrisJobke** [comment]
Let's close this for now. If we want this later we can reopen it easily.

**Pull request closed without merging**
