### PR TITLE
[stable16] Use handlebars from node_modules (on CI)

### PR DESCRIPTION
**Pull request by skjnldsv**

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by rullzer** [comment]
ci says no: https://drone.nextcloud.com/nextcloud/server/22032/4/3

**Comment by ChristophWurst** [comment]
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node
> 
> HTTP error 404 Not Found 

Apparently they remove their artifacts when new releases are published.

**Comment by ChristophWurst** [comment]
Found it. We need 4.12.0 for Node 12. Older release don't work: https://github.com/sass/node-sass/releases/tag/v4.11.0

**Comment by skjnldsv** [comment]
> Found it. We need 4.12.0 for Node 12. Older release don't work: https://github.com/sass/node-sass/releases/tag/v4.11.0

so what do we do?

**Comment by ChristophWurst** [comment]
> so what do we do?

Either downgrade the Docker image to Node <= 11 or update node-sass to 4.12.0

**Comment by skjnldsv** [comment]
> Node <= 11

I would prefer this, let's go for node lts?

**Comment by ChristophWurst** [comment]
> I would prefer this, let's go for node lts?

Fine by me. Or `node:11`

**Comment by skjnldsv** [comment]
Tests passed

**Review by rullzer — APPROVED** [review]

**Pull request merged**
