### PR TITLE
files: Local#writeStream should use it's own file_put_contents

### PR DESCRIPTION
**Pull request by kofemann**
The OC\Files\Storage\Local#writeStream use system provided file_put_contents.
However, it overrides file_put_contents, thus expects that the default behaviour
can be different.

Use Local#file_put_contents in writeStream to benefit from class specific functionality.

Signed-off-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Yes makes sense.

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Psalm is not happy about that.  Actually the annotation of file_put_contents in https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/public/Files/Storage/IStorage.php#L229 should be a `resource` instead of a `string` and we'd need to cast the return value of writeStream to be an integer.

**Comment by kofemann** [comment]
Ok. I can fix that.

**Comment by kofemann** [comment]
As in other places it used as systems `put_file_contents`, I will docs as `return int|false`

**Comment by juliushaertl** [comment]
> As in other places it used as systems put_file_contents, I will docs as return int|false

Yeah, that would indeed be the correct one :+1:

**Comment by juliushaertl** [comment]
Thanks a lot :tada:

**Pull request merged**
