### PR TITLE
New attempt at ignoring .htaccess modifications

### PR DESCRIPTION
**Pull request by come-nc**
Does not seem to work either, what did I miss?

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by come-nc** [comment]
https://stackoverflow.com/a/1274447

`.gitignore` does not work for tracked files :-(

**Comment by come-nc** [comment]
`git update-index --skip-worktree ./.htaccess`

This works but each of us needs to run it locally. No better solution I think.

**Comment by szaimen** [comment]
Why are you modifying the htaccess file in the first place?

**Comment by nickvergessen** [comment]
> Why are you modifying the htaccess file in the first place?

Integration tests and unit tests modify it

**Comment by szaimen** [comment]
> > Why are you modifying the htaccess file in the first place?
> 
> Integration tests and unit tests modify it

ah oh

**Pull request closed without merging**
