### PR TITLE
Wording detail fix for favorite emptycontent view

### PR DESCRIPTION
**Pull request by jancborchardt**
Just changing »No favorites« to the more friendly »No favorites yet«.

Please review @nextcloud/designers 

cc @marinofaggiana @mario @AndyScherzinger @tobiasKaminsky please make sure that the mobile apps use the same wording and style for the respective views :)
capture du 2017-04-21 14-12-52

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by Dennis1993** [comment]
Why is the Icon here yellow and not grey? In all links on the left panel the icons are grey :D

**Review by rullzer — APPROVED** [review]
fine

**Comment by MorrisJobke** [comment]
> Why is the icon here yellow and not grey? In all links on the left panel the icons are grey :D

Could you open a separate ticket about this or maybe directly open a PR. I guess it would be nice to be consistent here as well.

**Comment by jancborchardt** [comment]
@Dennis1993 the reason the icon is yellow is because if everything is grey it looks very very bland. :) For the same reason, the empty folder icon is blue (as the folder is always blue).

I’m actually thinking about coloring the »All files« folder icon blue also, and the favorites icon yellow. Because these are the most important entries, and to make it look a bit nicer and welcoming.

**Comment by marinofaggiana** [comment]
For me, Nextcloud need a own new style... not only a simple color of icon

**Comment by AndyScherzinger** [comment]
@jancborchardt Android fix is https://github.com/nextcloud/android/pull/867

**Pull request merged**
