### PR TITLE
Enable redis for theming acceptance tests

### PR DESCRIPTION
**Pull request by juliusknorr**
Signed-off-by: Julius Härtl <jus@bitgrid.net>

### CODE REVIEW

**Comment by danxuliu** [comment]
@juliushaertl Before `tests/acceptance/run-local.sh` is executed Nextcloud is not installed yet, so you can not run the OCC commands at that point; you should add them to _[tests/acceptance/installAndConfigureServer.sh](https://github.com/nextcloud/server/blob/801bf813178573b539a8d66bcb1420cd11455994/tests/acceptance/installAndConfigureServer.sh)_ with something like (I have not tested it, though ;-) ):
```
- echo "php occ config:system:set redis host --value=cache" >> tests/acceptance/installAndConfigureServer.sh
- echo "php occ config:system:set redis port --value=6379 --type=integer" >> tests/acceptance/installAndConfigureServer.sh
...
```

**Comment by juliushaertl** [comment]
Thanks for the hint @danxuliu I'll look into that.

**Review by skjnldsv — APPROVED** [review]
Code make sense!

**Review by danxuliu — CHANGES_REQUESTED** [review]
I have to check it more deeply, but I block the merge as a preventive measure.

If I am not mistaken the `$ENABLE_REDIS` environment variable would never be defined when _installAndConfigureServer.sh_ is executed, as [it is executed in a different shell than the one that calls it](https://github.com/nextcloud/server/blob/34f397fd225e94b1f4997806a8392de24b2e4a5a/tests/acceptance/run-local.sh#L209). @juliushaertl I can take care of this if you want.

Besides that the tests should be run both with and without Redis to make easier to distinguish whether a failure came from using Redis or it is present also in the base code.

**Comment by danxuliu** [comment]
>  Do you think adding --preserve-env to the sudo call is enough or does it require deeper work on the test scripts?

No, because it does not use `sudo`, but `su`; the equivalent parameter for `su` (`--preserve-environment`) only preserves a predefined subset of all the environment variables, so it requires a deeper work.

**Comment by juliushaertl** [comment]
Maybe I can have a look together with @danxuliu at the next hackweek. Closing for now.

**Pull request closed without merging**
