### PR TITLE
Remake website property saving with Vue

### PR DESCRIPTION
**Pull request by Pytal**
Remake website property saving with Vue for accessibility purposes

<details>
<summary>Deprecation</summary>

The `lookupServerUploadEnabled` block https://github.com/nextcloud/server/blob/16b06dd75889bef318881a4783cff03aaeb971d9/apps/settings/templates/settings/personal/personal.info.php#L164-L191 is deprecated and therefore not brought over as it is only displayed under the condition that your website is set and the scope is public which is never the case as the public scope was deprecated in 21.0.1 https://github.com/nextcloud/server/blob/16b06dd75889bef318881a4783cff03aaeb971d9/lib/public/Accounts/IAccountManager.php#L86-L91

</details>

### CODE REVIEW

**Comment by Pytal** [comment]
Rebased

**Review by skjnldsv — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@Pytal conflicts

**Comment by Pytal** [comment]
> @Pytal conflicts

There will be many rebases

**Pull request merged**
