### PR TITLE
update icewind/streams to 0.5.2

### PR DESCRIPTION
**Pull request by icewind1991**
- [x] requires https://github.com/nextcloud/3rdparty/pull/39

Backport of https://github.com/nextcloud/server/pull/3157

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 sign-off missing

**Comment by MorrisJobke** [comment]
> @icewind1991 sign-off missing

Ping

**Comment by icewind1991** [comment]
done

**Comment by MorrisJobke** [comment]
Let's wait for this after the current RC ;)

**Comment by icewind1991** [comment]
rebased and updated 3rdparty ref

**Review by rullzer — APPROVED** [review]
Fine by me :+1:

**Comment by MorrisJobke** [comment]
I updated the 3rdparty module

**Review by MorrisJobke — APPROVED** [review]
:+1: I mounted some external storages and it still works

**Pull request merged**
