### PR TITLE
extend anonymous options to work on every dav url

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Unit tests fail:

```
There was 1 failure:
1) OCA\DAV\tests\unit\DAV\AnonymousOptionsTest::testAnonymousOptionsNonRoot
Failed asserting that 200 matches expected 401.

/drone/src/github.com/nextcloud/server/apps/dav/tests/unit/DAV/AnonymousOptionsTest.php:57
```

**Comment by icewind1991** [comment]
!backport to stable15

**Pull request merged**
