### PR TITLE
Remove padding for longer wordings (like the future French one)

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
## Before

Capture d’écran du 2023-08-04 10-21-35

## After

Capture d’écran du 2023-08-04 10-21-25

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
The padding should remain. Better to have 2 lines than 1 that potentially touches the border?

**Comment by Jerome-Herbinet** [comment]
> The padding should remain. Better to have 2 lines than 1 that potentially touches the border?

If I remember well, one of the parent elements has got a padding I you look at it, so, the wording should never touch borders 🤔

**Review by jancborchardt — APPROVED** [review]
Looks good as per the padding inspector screenshot of @Jerome-Herbinet :)

**Review by szaimen — APPROVED** [review]
LGTM

**Pull request merged**
