### PR TITLE
[3rdparty] Bump to doctrine/dbal-2.7.2

### PR DESCRIPTION
**Pull request by rullzer**
Requires:
- [x] https://github.com/nextcloud/3rdparty/pull/219
- [x] https://github.com/nextcloud/3rdparty/pull/224
- [x] rebase

### CODE REVIEW

**Comment by rullzer** [comment]
Seems this fails on https://github.com/nextcloud/server/blob/da3004b8f5f6f96f817568c5cba002540d61150b/tests/lib/DB/OCPostgreSqlPlatformTest.php#L41

@nickvergessen @icewind1991 can one of you with postgres knowledge have a look?

**Comment by nickvergessen** [comment]
It's using `BIGSERIAL` instead of `BIGINT`, our hack was removed.

**Comment by nickvergessen** [comment]
Basically the test was added to prevent exactly this from happening.
The column is a Bigserial now instead of Bigint and the column is default value is being dropped instead of being kept.

But since we update doctrine, if we go straight to 2.7.1 we can drop it aparently: https://github.com/owncloud/core/pull/31059

**Comment by rullzer** [comment]
I did the tiny steps because diretion to 2.9 failed hard.
once this is in we can bump to 2.7

**Comment by rullzer** [comment]
but lets see about 2.7 tomorrow

**Comment by rullzer** [comment]
Bumped it to 2.7.2 Lets see

**Comment by rullzer** [comment]
@nickvergessen this is 2.7.2 now. Could you have another look?

**Comment by nickvergessen** [comment]
Well I guess now we need to delete the test, just like OC did?

**Comment by rullzer** [comment]
@nickvergessen actually CI seems to be happy

**Comment by rullzer** [comment]
Ready for review :D

**Review by nickvergessen — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
