### PR TITLE
Update the unencrypted file size when closing streams

### LINKED ISSUE #2102: Encryption header visible in newly created files
**Describe the bug**
When opening a new text document (`.md`), which was never written anything but empty text to, the encryption header will be shown instead of an empty document. The encryption header consists of `HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CTR:signed:true:HEND` followed by 8111 dashs (`-`). This issue only occurs when Nextcloud Office is installed and enabled and encryption with the default encryption module is active. A Collabora Online server doesn't need to be configured.

When removing the encryption header and closing the document, the encryption header will again be visible after reopening the document.
When instead replacing the encryption header by some arbitrary text (e.g. just the letter `a`), closing an reopening, just the letter `a` without any encryption header will be displayed. The file will still be encrypted on the disk, so this is not a security issue. Interestingly, after clearing the arbitrary text from the new document (such that the document is now empty again), and re-opening it, the document will be shown as empty, the encryption header will not be shown anymore.

So let's define two types of files:
1. Files that were newly created and new files that were saved as empty after removing the visible encryption header.
2. Files that were previously written arbitrary non-empty text to, but are now empty.

When creating a type 1 and a type 2 file, these files will have the same checksum on the disk. Thus there is probably something in the database that can differentiate between those file types, resulting in the encryption header being visible for type 1 files, but not for type 2 files.

When creating a new, non-markdown document it will by default be downloaded. When opening the downloaded file with an editor, the encryption header is also be contained in there.

I reproduced this issue on a fresh local Nextcloud 23.0.2 Docker install, with just the default apps (no recommended apps) and `Nextcloud Office` and `Default Encryption Module` installed.

**To Reproduce**
1. Make sure encryption is enabled and install the Nextcloud Office app.
2. Create a new empty text document, which will by default be opened afterwards

**Screenshots**
Video displaying the reproduction steps: https://screens.totally.rip/2022/03/623613089d8e0.mp4

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox Nightly 100, Chromium 99
 - Version: 23.0.2
 - Device: Desktop

## Server details

**Operating system**: Linux 5.16.15-arch1-1 x86_64 (don't know which distro the docker container uses), Linux 5.13.19-1-pve x86_64 (Arch Linux)

**Web server:** Apache 2.4.52, nginx 13.6

**Database:** sqlite3 3.34.1, PostgreSQL 13.6

**PHP version:** 8.0.16, 8.1

**Nextcloud version:** 23.0.2

**Version of the richdocuments app**: 5.0.3

**Version of Collabora Online**: None, Collabora Office 21.06.9.1 (git hash: [e60ec9f](https://hub.libreoffice.org/git-core/e60ec9f))

<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
Nothing is logged.

#### Browser log
Irrelevant because it's a server-side issue.

### PR DESCRIPTION
**Pull request by juliusknorr**
## Summary

* Fixes https://github.com/nextcloud/richdocuments/issues/2102

This PR fixes two issues related to primary object storage and master key encryption, both related to apps using the PHP Nodes api for file access. 

[77edd36](https://github.com/nextcloud/server/pull/35649/commits/77edd36583b7a12ba550d31c18df1138edb1a846) makes sure that the proper unencrypted size is written into the filecache when writing to a file through the putContent method. This for example is done by Collabora to save a file. Without updating the unencrypted size any follow up download would cause a BadSignature error.

[f6d6898](https://github.com/nextcloud/server/pull/35649/commits/f6d68987b2e8cd302add1b2aa42728ec92af98d6) Addresses a similar issue when a newFile was created with empty content. In this case the encryption stream writes just the header to the file but never updates the isEncrypted flag on it, so when creating a new empty file in the text app the encrypted content is returned to the user instead of the decrypted one.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: wow, nice catch!

**Comment by juliushaertl** [comment]
@icewind1991 @PVince81 Any hint on where the best place for a test case of this would be? 

To reproduce this I used the following plain code snippets:

```
<?php
require_once __DIR__ . '/../lib/versioncheck.php';
try {
	require_once __DIR__ . '/../lib/base.php';
	$root = \OC::$server->getRootFolder()->getUserFolder('admin');
	try {
		$root->delete('existingfile');
	} catch (\OCP\Files\InvalidPathException $e) {
	} catch (\OCP\Files\NotFoundException $e) {
	} catch (\OCP\Files\NotPermittedException $e) {
	}

	$file = $root->newFile('existingfile', '');
	$data = [
		'size' => $file->getSize(),
		'unencrypted_size' => $file->getFileInfo()['unencrypted_size'],
		'encrypted' => $file->isEncrypted()
	];
	var_dump($data);

	$file = $root->get('existingfile');
	$file->putContent(str_repeat('A', 64*1024));
	$data = [
		'size' => $file->getSize(),
		'unencrypted_size' => $file->getFileInfo()['unencrypted_size'],
		'encrypted' => $file->isEncrypted()
	];
	var_dump($data);
} catch (Error $ex) {
	echo $ex->getMessage();
}
```

## Before
array(3) { ["size"]=> int(8192) ["unencrypted_size"]=> int(0) ["encrypted"]=> bool(true) } array(3) { ["size"]=> int(74592) ["unencrypted_size"]=> int(0) ["encrypted"]=> bool(true) }

## After
array(3) { ["size"]=> int(8192) ["unencrypted_size"]=> int(0) ["encrypted"]=> bool(true) } array(3) { ["size"]=> int(65536) ["unencrypted_size"]=> int(65536) ["encrypted"]=> bool(true) }

**Comment by PVince81** [comment]
@juliushaertl it seems there's a matching test class that might be useable for a unit test: tests/lib/Files/Stream/EncryptionTest.php

for integration tests, it seems we don't have encryption there.
otherwise we could have added a test that uploads and then propfinds the size

another idea would be to simply add code like your snippet above either the storage tests or stream tests, and rely on https://github.com/nextcloud/server/blob/master/.github/workflows/s3-primary.yml#L59 to have them run on S3.

maybe we should copy that workflow to also have one with encryption enabled ?

**Review by skjnldsv — APPROVED** [review]

**Comment by juliushaertl** [comment]
Apparently the webdav API didn't trigger those issues, but maybe because they interact a bit differently with the file system apis through the view directly.

I adjusted the unit tests accordingly to have some basic coverage so we can get this in, but at some point dedicated integration tests with encryption might be nice to have.

**Pull request merged**
