### PR TITLE
Fix creating events with old (< unix time) lastoccurence

### LINKED ISSUE #20804: Webcal cache: fails with bad DTEND date
### Steps to reproduce
1. My google .ics feed has some birthday reminders with illegal end dates (no idea how that happened in the first place, probably a google bug or caused by whatever software originally produced those entries)
2. that value looks like `DTEND;VALUE=DATE:18991230`
3. CalDAV import will partially fail with `SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'lastoccurence' at row 1 at <<closure>>`

### Expected behaviour
- handle bogus dates in a controlled way
- proposed change in CalDavBackend:getDenormalizedData (end of `if ($componentType === 'VEVENT' && $component->DTSTART) {` block):
```
if ($lastOccurrence < 0) {
    $maxDate = new DateTime(self::MAX_DATE);
    $lastOccurrence = $maxDate->getTimestamp();
}
```

### Actual behaviour
- the import failure might get unnoticed if the log is not checked since the import errors message in the main UI hides itself after some seconds and the other entries appear to be inserted correctly
- as a consequence, subsequent auto refreshes of that calendar appear to be not working at all, i.e. not even the partially imported events get synch-ed or new events from the .ics feed get pulled in

### PR DESCRIPTION
**Pull request by tcitworld**
Makes sure the timestamp is > 0 in the `bigint` column.

Closes #20804

- [x] Check if there's no edge effects introduced by this
- [x] Add unit test

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by tcitworld** [comment]
Backports ?

**Review by miaulalala — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
