### PR TITLE
Keep all shipped apps enabled because they should be okay

### LINKED ISSUE #7865: Do not disable shipped apps on exceptions
* having redis set up
* having shares
* having a network hiccup
* once the connection to the redis server is somehow not working, the server catches the exception and will disable the app in which it happened - in this case it was files_sharing which caused all shares being deleted from user computers :/

cc @rullzer @schiessle @blizzz @ChristophWurst @nickvergessen @danxuliu Do you have an idea how to mitigate this?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #7865

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
At leasts fixes most of the effect from the issue

**Review by blizzz — APPROVED** [review]
it's a start :)

**Comment by MorrisJobke** [comment]
@nickvergessen Could you open the backport to stable13? Thanks

**Comment by MorrisJobke** [comment]
And stable12

**Comment by nickvergessen** [comment]
Done ^

**Pull request merged**
