### PR TITLE
Do not use userId as key for OCS API response

### LINKED ISSUE #20840: Provisioning API returns broken XML
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Send requests to provisioning API, see cURL requests below

### Expected behaviour
Valid XML

### Actual behaviour
Broken XML

The API is using the userId as name of the XML-element. This is breaking for obvious reasons.

### Suggested fix
- Do not use userId as element name. use `<user>` instead. The element already contains an `<id>` element.

Downside: Breaking change plus it's no longer possible to access users directly in JSON (via `data.users.admin`)

### Server configuration
**Nextcloud version:** reproducible on any supported version
**Where did you install Nextcloud from:** git

### API Response:
`curl  -H "OCS-APIRequest: true" http://admin:admin@nextcloud.local/ocs/v1.php/cloud/users/details`
```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <users>
   <admin>
    <enabled>1</enabled>
    <storageLocation>/usr/local/apache2/htdocs/public/nextcloud/data/admin</storageLocation>
    <id>admin</id>
    <lastLogin>1588766990000</lastLogin>
    <backend>Database</backend>
    <subadmin/>
    <quota>
     <free>51709734912</free>
     <used>164</used>
     <total>51709735076</total>
     <relative>0</relative>
     <quota>-3</quota>
    </quota>
    <email/>
    <displayname>admin</displayname>
    <phone></phone>
    <address></address>
    <website></website>
    <twitter></twitter>
    <groups>
     <element>admin</element>
    </groups>
    <language>en_GB</language>
    <locale></locale>
    <backendCapabilities>
     <setDisplayName>1</setDisplayName>
     <setPassword>1</setPassword>
    </backendCapabilities>
   </admin>
   <enabled>1</enabled>
   <storageLocation>/usr/local/apache2/htdocs/public/nextcloud/data/user@example.com</storageLocation>
   <id>user@example.com</id>
   <lastLogin>0</lastLogin>
   <backend>Database</backend>
   <subadmin/>
   <quota>
    <quota>none</quota>
    <used>0</used>
   </quota>
   <email/>
   <displayname>User with at sign</displayname>
   <phone></phone>
   <address></address>
   <website></website>
   <twitter></twitter>
   <groups/>
   <language>en</language>
   <locale></locale>
   <backendCapabilities>
    <setDisplayName>1</setDisplayName>
    <setPassword>1</setPassword>
   </backendCapabilities>
  </users>
 </data>
</ocs>
```

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #20840

### CODE REVIEW

**Comment by georgehrke** [comment]
New XML Output:

```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <users>
   <element>
    <enabled>1</enabled>
    <storageLocation>/usr/local/apache2/htdocs/public/nextcloud/data/admin</storageLocation>
    <id>admin</id>
    <lastLogin>1588842301000</lastLogin>
    <backend>Database</backend>
    <subadmin/>
    <quota>
     <free>51708792832</free>
     <used>164</used>
     <total>51708792996</total>
     <relative>0</relative>
     <quota>-3</quota>
    </quota>
    <email/>
    <displayname>admin</displayname>
    <phone></phone>
    <address></address>
    <website></website>
    <twitter></twitter>
    <groups>
     <element>admin</element>
    </groups>
    <language>en_GB</language>
    <locale></locale>
    <backendCapabilities>
     <setDisplayName>1</setDisplayName>
     <setPassword>1</setPassword>
    </backendCapabilities>
   </element>
   <element>
    <enabled>1</enabled>
    <storageLocation>/usr/local/apache2/htdocs/public/nextcloud/data/user@example.com</storageLocation>
    <id>user@example.com</id>
    <lastLogin>0</lastLogin>
    <backend>Database</backend>
    <subadmin/>
    <quota>
     <quota>none</quota>
     <used>0</used>
    </quota>
    <email/>
    <displayname>User with at sign</displayname>
    <phone></phone>
    <address></address>
    <website></website>
    <twitter></twitter>
    <groups>
     <element>/123/</element>
     <element>&lt;123&gt;</element>
     <element>🙈</element>
    </groups>
    <language>en</language>
    <locale></locale>
    <backendCapabilities>
     <setDisplayName>1</setDisplayName>
     <setPassword>1</setPassword>
    </backendCapabilities>
   </element>
  </users>
 </data>
</ocs>
```

**Comment by georgehrke** [comment]
@rullzer I'm not sure how we want to handle back porting here.
It's a breaking change for an API which has been there since NC 14.

**Review by skjnldsv — COMMENTED** [review]
I'm not fond of this.
Isn't it better to make sure we use array_values on xml output instead?

**Comment by georgehrke** [comment]
> Isn't it better to make sure we use array_values on xml output instead?

If we do that, every node will be renamed to `<element>` and you won't have the ability to set `<email>` and `<displayname>` etc, because those are just the array keys.

**Comment by skjnldsv** [comment]
> If we do that, every node will be renamed to `<element>` and you won't have the ability to set `<email>` and `<displayname>` etc, because those are just the array keys.

I don't fully get that. But For me this is about performance, as (not done here), but it's cleaner to store an associative array in javascript to access the user data by id directly. I mean you get the idea of course. In any future enhancement of users mgmt, it will need the first loading will require to map all the users into an associative array in the frontend, which get quickly bad performance wise.

**Comment by georgehrke** [comment]
> I don't fully get that. 

The OCS Controller method is just returning an array, no matter whether the accept-header says json or XML. How should the code that turns it into xml know that it should turn `['email' => 'email@foo.com']` into `<email>email@foo.com</email>`, but suddenly `['userId123' => []]` into `<user>...</user>`.

The OCS Api is already weird enough, we shouldn't make it more confusing by returning different structures in json and xml.

> But For me this is about performance, as (not done here), but it's cleaner to store an associative array in javascript to access the user data by id directly. I mean you get the idea of course. In any future enhancement of users mgmt, it will need the first loading will require to map all the users into an associative array in the frontend, which get quickly bad performance wise.

Users are loaded in chunks of 25. Iterating over an array and doing something as simple as `obj[user.id] = user` does really not affect performance.

**Comment by skjnldsv** [comment]
Was more talking globally. :)
But sure :wink:, I'm done with that!

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
Mmmm it is kinda shitty that this API is not versioned. So i'm relly not fond of just chaging it.
For sure nt something to just backport

Let me pull in my API homies. @ChristophWurst @juliushaertl @nickvergessen any idea here?

**Comment by nickvergessen** [comment]
:-1: from me.

This API was always like this, so if you are a new user please use `format=json`, if you are not, then that is what you always got. If we want to fix it at all, we could do this only for the XML part:

```php
if ($isXML) {
    $usersDetails = array_values($usersDetails);
}
```

get `isXML` from these options:
https://github.com/nextcloud/server/blob/cb057829f72c70e819f456edfadbb29d72dba832/lib/private/AppFramework/Http/Dispatcher.php#L175-L182

But this still breaks all existing usages, so I would say "won't fix" and if someone really needs it as XML, we can add a new API endpoint to do the same but "fixed" which is then properly `v2/`-ed

**Comment by georgehrke** [comment]
> so I would say "won't fix" and if someone really needs it as XML, we can add a new API endpoint to do the same but "fixed" which is then properly v2/-ed

Fine by me.

**Pull request closed without merging**
