### PR TITLE
BirthdayCalendar: fix issue with birthyear to high when birthday on Dec 31st

### LINKED ISSUE #2171: Problem with birthday on Dec 31st
Hi there,

First of all: Thanx a lot for doing such a great work :)

My problem: One of my colleagues is born on December 31st (lets say Dolly is born on 1984-12-31), but the entry in the contacts birthday calendar is "Dolly (*1985)", so Dolly was made a year younger. Well that's charming for Dolly ... but it's a bug I suppose (and not a feature).

Nexcloud is running in version 10.

Has anybody an idea?

Greetz (especially to georgehrke)
Jürgen

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #2171 

please review @drupalwonder @MariusBluem @MorrisJobke 

Example vcard data:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//Mac OS X 10.12.1//EN
N:BAR;FOO;;;
FN:FOO BAR
BDAY:1900-12-31
END:VCARD
```

On master it will show `FOO BAR (*1901)`, with this patch it'll be `FOO BAR (*1900)`

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Unit tests fail:

```
OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testBuildBirthdayFromContact with data set #7 (false, 'BEGIN:VCARD\nVERSION:3.0\nPRODI...VCARD\n', 'Dr. Foo Bar')
Failed asserting that null is an instance of class "Sabre\VObject\Component\VCalendar".
/drone/src/github.com/nextcloud/server/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:66
```

**Comment by georgehrke** [comment]
Ah, obviously. Stupid me 🙈

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer @icewind1991

**Comment by MorrisJobke** [comment]
Code is different on stable10 and thus no backport is needed

**Pull request merged**
