### PR TITLE
Fix l10n

### LINKED ISSUE #26286: Untranslated name of contact's birthday calendar
When you turn a contact's birthday calendar on or off, an untranslated name appears in the activities:

obraz

The name is correct in the calendar list:

obraz

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.2.0

### Server configuration

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
21.0.0

### PR DESCRIPTION
**Pull request by Valdnet**
Issue: #26286

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Whohoo

**Comment by nickvergessen** [comment]
Errm the display name is overwritten here already:
https://github.com/nextcloud/server/blob/d9015a8c94bfd71fe484618a06d276701d3bf9ff/apps/dav/lib/CalDAV/Calendar.php#L66-L68

not enough?

**Comment by nickvergessen** [comment]
I guess the problem is activity is generated not using the users language but any so when the email is sent its en/default?

**Comment by Valdnet** [comment]
@nickvergessen The problem with the birthday calendar is also this: https://github.com/nextcloud/calendar/issues/2976.

**Comment by nickvergessen** [comment]
Yeah but the change here is useless, as the value is always overwritten by the code I pointed out.

**Comment by Valdnet** [comment]
> but the change here is useless

I don't know if it's useless, but adding l10n to the text string fixes the display of the correct contact birthday calendar name in activities. See for yourself:

- Before change:

obraz

- After adding: `$ this-> l10n-> t ( `

obraz

**Pull request merged**
