### PR TITLE
feat: Serve well-known assetlinks json

### LINKED ISSUE #44650: Associating website with Android app For Better DeepLink Support
[Document](https://developer.android.com/training/app-links/verify-android-applinks)

Currently, when user wants to open deep link with latest Android version, Google Chrome opening instead of Nextcloud Android app. To prevent that, we need to do some configuration in server side.

We need to ensure that our app's digital asset links are correctly set up. Digital asset links are used by Android to verify ownership of deep links. We can set up digital asset links **by creating an assetlinks.json file and placing it in the website's .well-known directory.** This file should contain information about our app and the deep links it handles.

**assetlinks.json**

```
[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.nextcloud.client",
    "sha256_cert_fingerprints":
    ["APP_CERT_FINGERPRINT"]
  }
}]
```

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Resolve https://github.com/nextcloud/server/issues/44650

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Pytal** [comment]
cc @alperozturk96 feel free to edit the assetlinks.json in the second commit

**Comment by alperozturk96** [comment]
> cc @alperozturk96 feel free to edit the assetlinks.json in the second commit

We need to put "sha256_cert_fingerprints" please don't merge, until we put it. @tobiasKaminsky Can you edit assetlinks.json?

**Comment by Pytal** [comment]
> `package_name` and `sha256_cert_fingerprints` should be configurable via config.php similar to [`master`/config/config.sample.php#L1105-L1123](https://github.com/nextcloud/server/blob/master/config/config.sample.php?rgh-link-date=2024-04-05T15%3A38%3A20Z#L1105-L1123) for branded clients.

Makes sense 👍

Would we need to allow multiple `package_name` and `sha256_cert_fingerprints` @tobiasKaminsky?

**Comment by alperozturk96** [comment]
@Pytal assetlinks-json can contain multiple package names. @tobiasKaminsky but we don't have more than one package name "com.nextcloud.client" or do we have?

[Example](https://stackoverflow.com/a/52029912/16787943)

**Pull request closed without merging**
