### PR TITLE
Fix small previews with Imaginary

### LINKED ISSUE #38911: [Bug]: PDF previews don't work after upgrade to 27 - Error 400
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On one of my instances PDF previews do no longer work after upgrading to NC 27. On both my other instances it works as expected.

The failing one is using the official Docker images. The other two instances are classic installations at shared web hosters. Other differences: DB (pgsql <-> mariadb, redis <-> non redis)

PDF previews work with Imaginary disabled, so I think it's related to Imaginary.

Also, preview generation works for `x >= 257` and `y >= 257`

### Steps to reproduce

1. Browse to folder with PDF files
2. No previews, just the PDF logo

### Expected behavior

See previews of files

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tsmd.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "27.0.0.8",
        "overwrite.cli.url": "https:\/\/cloud.tsmd.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "occweb",
            "forms",
            "groupfolders",
            "announcementcenter",
            "metadata",
            "polls",
            "integration_whiteboard",
            "bruteforcesettings",
            "issuetemplate",
            "onlyoffice",
            "suspicious_login",
            "collectives",
            "impersonate",
            "approval"
        ],
        "maintenance": false,
        "loglevel": "2",
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "X-Forwarded-For",
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwritehost": "cloud.tsmd.de",
        "overwriteprotocol": "https",
        "default_language": "de",
        "default_locale": "de_DE",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/var\/www\/html\/data\/skeleton",
        "updater.release.channel": "stable",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,30",
        "default_phone_region": "DE",
        "simpleSignUpLink.shown": false,
        "data-fingerprint": "681e3987b71dbcf8a80c491511dce9f8",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "onlyoffice": {
            "jwt_header": "Jwt-Authorization"
        },
        "activity_use_cached_mountpoints": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita",
            "OC\\Preview\\Imaginary"
        ],
        "preview_imaginary_url": "http:\/\/imaginary:9000",
        "debug": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - announcementcenter: 6.6.1
  - approval: 1.0.12
  - bruteforcesettings: 2.7.0
  - calendar: 4.4.2
  - circles: 27.0.0
  - cloud_federation_api: 1.10.0
  - collectives: 2.5.0
  - comments: 1.17.0
  - contacts: 5.3.1
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.10.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_automatedtagging: 1.17.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.3.0
  - groupfolders: 15.0.0
  - impersonate: 1.14.0
  - integration_giphy: 1.0.6
  - integration_openstreetmap: 1.0.5
  - integration_whiteboard: 0.0.14
  - integration_youtube: 0.1.4
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.2.2
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - notify_push: 0.6.3
  - oauth2: 1.15.0
  - onlyoffice: 8.1.0
  - password_policy: 1.17.0
  - polls: 5.0.5
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.0.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tables: 0.5.1
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_nextcloud_notification: 3.7.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - contactsinteraction: 1.8.0 (installed 1.7.0)
  - encryption: 2.15.0
  - files_external: 1.19.0
  - issuetemplate: 0.7.0 (installed 0.7.0)
  - libresign: 7.1.1 (installed 7.1.1)
  - photos: 2.3.0 (installed 1.0.0)
  - support: 1.10.0 (installed 1.1.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Couldn't find anything in the logs, even with Debug mode
```

### Additional info

https://cloud.domain.tld/core/preview?fileId=280976&c=bb75d279726eb8ef826eb9764852a2a1&x=250&y=250&forceIcon=0&a=1

Response code: 400
Response: []

### PR DESCRIPTION
**Pull request by enoch85**
* Resolves: #38911

Context: https://github.com/nextcloud/server/issues/38911#issuecomment-1738946442

## Summary

Without this change PDF, TIF and some other formats aren't generated if Imaginary is used.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by enoch85** [comment]
/backport https://github.com/nextcloud/server/commit/0edcde404e4be8db9fa78851ce7283469e0db911 to stable 27

**Comment by enoch85** [comment]
/backport https://github.com/nextcloud/server/commit/0edcde404e4be8db9fa78851ce7283469e0db911 to stable27

**Comment by enoch85** [comment]
/backport https://github.com/nextcloud/server/pull/40670/commits/0edcde404e4be8db9fa78851ce7283469e0db911 to stable27

**Comment by enoch85** [comment]
Please backport to stable27, backport bot didn't like my efforts.

**Review by Chartman123 — APPROVED** [review]
Working for me this way

**Comment by Glandos** [comment]
Given the small change involved, I think everything will be OK.

However, I'm sorry to say that I don't have time right now to investigate more than that :cry:

**Comment by enoch85** [comment]
OK to merge?

**Comment by szaimen** [comment]
maybe we should revisit this due to https://github.com/nextcloud/server/issues/38911#issuecomment-1738946442?

**Comment by enoch85** [comment]
> maybe we should revisit this due to [#38911 (comment)](https://github.com/nextcloud/server/issues/38911#issuecomment-1738946442)?

Better to put that in a separate PR IMHO, this fixes the bug, then performance is another topic.

But sure, it's an easy fix if the decision is to remove it.

**Pull request closed without merging**
