### PR TITLE
Set max-width of image to 100px in Outlook as well

### PR DESCRIPTION
**Pull request by MorrisJobke**
Should™ fix the issues with the too stretched logos in emails in Outlook.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
See https://stackoverflow.com/a/20533703/520507 for the inspiration.

**Review by nickvergessen — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
sure....

**Comment by rullzer** [comment]
CI fails

**Review by rullzer — DISMISSED** [review]
update tests

**Review by rullzer — APPROVED** [review]

**Comment by LukasReschke** [comment]
Doesn't work :(

**Comment by MorrisJobke** [comment]
So this doesn't work in all cases - so better go for #5850

**Pull request merged**
