### PR TITLE
Fix File#putContents(string) on ObjectStorage

### PR DESCRIPTION
**Pull request by marcelklehr**
Jesus, I've never messed up a pull request so badly. This is the same as #16397 and #16409 but with a signed off commit and it shouldn't fail the tests.

### CODE REVIEW

**Comment by korelstar** [comment]
And again:
Plesse backport this to NC 15 and 16
 ;-)

**Comment by marcelklehr** [comment]
@rullzer Most of the tests are fixed, now

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Pull request merged**
