### PR TITLE
Harden apptoken check

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
Good enough for now

**Comment by dublutz** [comment]
Hi guys, thank you for your work on this one. 
I guess I'm missing the context but why do you return Http::STATUS_BAD_REQUEST status code when the `$this->checkAppToken()` returns TRUE. This means that the session exists, right? Thanks for clarifying!

**Comment by nickvergessen** [comment]
When the request is done by an apptoken it is not allowed to manage app tokens. Otherwise an app token could create another app token. This is not wanted.

**Pull request merged**
