### PR TITLE
Remove default token which is deprecated since Nextcloud 13

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by MichaIng** [comment]
Needs removal from Psalm baseline: https://github.com/nextcloud/server/blob/978b504/build/psalm-baseline.xml#L2875-L2892

**Comment by nickvergessen** [comment]
> Needs removal from Psalm baseline: https://github.com/nextcloud/server/blob/978b504/build/psalm-baseline.xml#L2875-L2892

Daily update will do

**Comment by MichaIng** [comment]
```
There was 1 failure:

1) Test\User\SessionTest::testTryTokenLoginWithDisabledUser
Failed asserting that exception of type "Error" matches expected exception "OC\User\LoginException". Message was: "Class 'OC\Authentication\Token\DefaultToken' not found" at
/home/runner/work/server/server/tests/lib/User/SessionTest.php:1019
```
https://github.com/nextcloud/server/blob/master/tests/lib/User/SessionTest.php#L12-L13 and several uses within the script.

**Comment by CarlSchwan** [comment]
```
1) Test\User\ManagerTest::testCallForSeenUsers
OC\HintException: Password needs to be at least 10 characters long.

/home/carl/project/nextcloud-docker-dev/server/apps/password_policy/lib/PasswordValidator.php:87
/home/carl/project/nextcloud-docker-dev/server/apps/password_policy/lib/Listener/ValidatePasswordPolicyEventListener.php:46
/home/carl/project/nextcloud-docker-dev/server/lib/private/EventDispatcher/ServiceEventListener.php:87
/home/carl/project/nextcloud-docker-dev/server/3rdparty/symfony/event-dispatcher/EventDispatcher.php:251
/home/carl/project/nextcloud-docker-dev/server/3rdparty/symfony/event-dispatcher/EventDispatcher.php:73
/home/carl/project/nextcloud-docker-dev/server/lib/private/EventDispatcher/EventDispatcher.php:88
/home/carl/project/nextcloud-docker-dev/server/lib/private/EventDispatcher/EventDispatcher.php:100
/home/carl/project/nextcloud-docker-dev/server/lib/private/User/Database.php:123
/home/carl/project/nextcloud-docker-dev/server/lib/private/User/Manager.php:463
/home/carl/project/nextcloud-docker-dev/server/lib/private/User/Manager.php:407
/home/carl/project/nextcloud-docker-dev/server/tests/lib/User/ManagerTest.php:646
```

Fixed the tests by adding one additional character to the password in ManagerTest.php, but I'm not 100% sure this an intended side-effect of this PR

**Comment by MichaIng** [comment]
```
There were 5 errors:
--
173 |  
174 | 1) Test\Lockdown\LockdownManagerTest::testCanAccessFilesystemAllowed
175 | Error: Class 'OC\Authentication\Token\DefaultToken' not found
176 |  
177 | /drone/src/tests/lib/Lockdown/LockdownManagerTest.php:46
178 |  
179 | 2) Test\Lockdown\LockdownManagerTest::testCanAccessFilesystemNotAllowed
180 | Error: Class 'OC\Authentication\Token\DefaultToken' not found
181 |  
182 | /drone/src/tests/lib/Lockdown/LockdownManagerTest.php:54
183 |  
184 | 3) OCA\OAuth2\Tests\Controller\OauthApiControllerTest::testGetTokenValidAppToken
185 | Error: Class 'OC\Authentication\Token\DefaultToken' not found
186 |  
187 | /drone/src/apps/oauth2/tests/Controller/OauthApiControllerTest.php:241
188 |  
189 | 4) OCA\OAuth2\Tests\Controller\OauthApiControllerTest::testGetTokenValidAppTokenBasicAuth
190 | Error: Class 'OC\Authentication\Token\DefaultToken' not found
191 |  
192 | /drone/src/apps/oauth2/tests/Controller/OauthApiControllerTest.php:333
193 |  
194 | 5) OCA\OAuth2\Tests\Controller\OauthApiControllerTest::testGetTokenExpiredAppToken
195 | Error: Class 'OC\Authentication\Token\DefaultToken' not found
196 |  
197 | /drone/src/apps/oauth2/tests/Controller/OauthApiControllerTest.php:428
```

**Comment by nickvergessen** [comment]
I fixed those already, but there is a backlog on drone so wrong results are reported

**Comment by MichaIng** [comment]
Nope, those are really missing 🙂:
- https://github.com/nextcloud/server/blob/techdebt/noid/remove-default-token-provider/tests/lib/Lockdown/LockdownManagerTest.php#L24
- https://github.com/nextcloud/server/blob/techdebt/noid/remove-default-token-provider/apps/oauth2/tests/Controller/OauthApiControllerTest.php#L30

**Comment by nickvergessen** [comment]
Right, pushed

**Comment by MichaIng** [comment]
php-cs check:
```
Warning: Found violation(s) of type: class_definition
Warning: Found violation(s) of type: braces
Warning: Found violation(s) of type: no_unused_imports
```
Can it be configured to be a bit more verbose, at best print file and line where these violations have been found? I cannot find them 🤔.

**Comment by nickvergessen** [comment]
> Can it be configured to be a bit more verbose, at best print file and line where these violations have been found? I cannot find them :thinking:

Everyone wished

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
