### PR TITLE
Add occ command to set theming values

### LINKED ISSUE #14321: Allow setting theming options from OCC
For large scale deployments it would be great to have the ability to automatically set themeing from the command line.

CC: @juliushaertl

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes https://github.com/nextcloud/server/issues/14321 by moving existing logic out of the controller and reusing it in a new occ command.

```
occ theming:config --help
Description:
  Set theming app config values

Usage:
  theming:config [options] [--] [<key> [<value>]]

Arguments:
  key                   Key to update the theming app configuration (leave empty to get a list of all configured values)
                        One of: name, url, imprintUrl, privacyUrl, slogan, color
  value                 Value to set (leave empty to obtain the current value)

Options:
  -r, --reset           Reset the given config key to default
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

Example commands

- Change the color: `occ theming:config color "#ff0000"`
- Change the logo: `occ theming:config logo /tmp/foo.png`
- Reset the color: `occ theming:config color`

### CODE REVIEW

**Comment by juliushaertl** [comment]
Guess i was a bit to quick, tests need adjustments as well

**Comment by kesselb** [comment]
> Value to set (leave empty to reset the key to the default value)

Fine by me (because documented) but I would expect that no value prints the current value.

**Comment by juliushaertl** [comment]
> Fine by me (because documented) but I would expect that no value prints the current value.

Now that you mention it, yeah let me add a reset flag.

**Comment by juliushaertl** [comment]
Ready for review

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by juliushaertl** [comment]
Already documented at https://github.com/nextcloud/documentation/pull/8078

**Pull request merged**
