### PR TITLE
Set notification email automatically after deleting additional email

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

When an additional email is set as the notification email and is deleted, the deleted email will remain as the notification email

This is unexpected behaviour so we fix this by automatically setting the system email as the notification email on deletion

### Additional email as notification email
image

### After deletion
| | Screenshot |
--- | ---
**Before** | image
**After** | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]
Would it make sense to do the change on the backend side instead of here?

**Comment by skjnldsv** [comment]
> Would it make sense to do the change on the backend side instead of here?

I agree with Louis @Pytal :)

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
also would prefer it on the backend side

**Comment by skjnldsv** [comment]
Closing this pull request due to lack of recent activity and updates; also seeing the two comments about backend :)

**Pull request closed without merging**
