### PR TITLE
Avoid locking on restore/delete and limit concurrent requests

### PR DESCRIPTION
**Pull request by juliusknorr**
## Summary

This is a frontend safeguard to avoid running into backend file locks when deleting or restoring multiple files. Even after https://github.com/nextcloud/server/pull/28438/files#diff-5450a6734b54a8b5e2c2f7521098ba6d05993e8bbebffeee140e93ec349e4127R978 this could still happen if the retry timeout was exceeding 15 seconds.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Comment by icewind1991** [comment]
I think it's fine to change the scanning logic to only scan `'files_trashbin/versions/'. $filename` instead of `'files_trashbin/versions/'`, which should help prevent conflicts

**Comment by icewind1991** [comment]
Note that I'm not sure if the scan logic is still needed, I know that in the past we didn't actively maintain the cache outside of `/$user/files` but I believe that is no longer the case

**Comment by juliushaertl** [comment]
> Note that I'm not sure if the scan logic is still needed, I know that in the past we didn't actively maintain the cache outside of `/$user/files` but I believe that is no longer the case

I had the same assumption in https://github.com/nextcloud/server/pull/28438/files#r691270467 so should we just drop it?

**Comment by juliushaertl** [comment]
Deleting and restoring versions seems to still work fine with that code part removed.

**Comment by icewind1991** [comment]
Do we want to increase the concurrency a bit if we remove the scan?

**Comment by juliushaertl** [comment]
Increased to 4 which seems a reasonable value for now.

**Review by icewind1991 — APPROVED** [review]

**Pull request merged**
