### PR TITLE
Fix hostname in Apple configuration profile

### LINKED ISSUE #19656: Configuration profile for macOS/iOS contains internal server ip and does not respect overwritehost
### Steps to reproduce
1. Install Nextcloud 18
2. Go to Settings / Mobile & Desktop
3. Review the configuration profile for mac/iOS

### Expected behaviour
CalDAVHostname is taken from the value provided in overwritehost in config.php

### Actual behaviour
CalDAVHostname is set to internal IP-address.

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache 2.4.29

**Database:** Mariadb 10.1.44

**PHP version:** 7.2.24

**Nextcloud version:** (see Nextcloud admin page) 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xx.xx.xxx.xx"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwritehost": "sub.domain.de",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "overwrite.cli.url": "https:\/\/sub.domain.de\/nextcloud",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "force_language": "de",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "updater.release.channel": "stable"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 73.0

**Operating system:** Ubuntu 18.04

### PR DESCRIPTION
**Pull request by Nils160988**
Closes #19656 

Signed-off-by: Nils Wittenbrink <nilswittenbrink@web.de>

### CODE REVIEW

**Comment by kesselb** [comment]
```
Index: apps/dav/tests/unit/Provisioning/Apple/AppleProvisioningPluginTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/dav/tests/unit/Provisioning/Apple/AppleProvisioningPluginTest.php	(revision 90c3e3bbeb566f73952f7e4c66b9f98ec84cdde2)
+++ apps/dav/tests/unit/Provisioning/Apple/AppleProvisioningPluginTest.php	(date 1582992422173)
@@ -158,10 +158,9 @@
 			->method('getServerProtocol')
 			->wilLReturn('https');
 
-		$this->sabreRequest->expects($this->at(1))
-			->method('getAbsoluteUrl')
-			->with()
-			->willReturn('https://nextcloud.tld/nextcloud/remote.php/dav/provisioning/apple-provisioning.mobileconfig');
+		$this->urlGenerator->expects($this->once())
+			->method('getBaseUrl')
+			->willReturn('https://nextcloud.tld/nextcloud');
 
 		$this->themingDefaults->expects($this->at(0))
 			->method('getName')
```

One test fails due the other method used to get the url. Above patch should mock getBaseUrl properly.

**Comment by Nils160988** [comment]
Fixed the test as @kesselb suggested

**Review by georgehrke — APPROVED** [review]

**Comment by georgehrke** [comment]
@Nils160988 Thx for the contribution!

**Review by rullzer — APPROVED** [review]

**Comment by Nils160988** [comment]
Thanks for merging :)
Backport to 18? Should not be a critical change I think

**Pull request merged**
