### PR TITLE
Phone number validation and search

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Requires 3rdparty `giggsey/libphonenumber-for-php` https://github.com/nextcloud/3rdparty/pull/539
- [x] Validate that the phone number is actually a phone number
- [x] Find a decent default region code we can use (admin setting? reverse try language selection?)
- [x] Store phone numbers in a defined format (Recommended https://en.wikipedia.org/wiki/E.164 supported by the library)
- [x] Store phone numbers (and other entries?) individually so we can search by them in a meaning full way instead of wildcard searching the json blob in oc_accounts.
- [x] Add an OCS Api to search again account data and return federation ids
- [x] Add a unit test for the cleaning of the phone number
- [x] Add a unit test for the search endpoint
- [x] Add integration tests for the search endpoint
- [x] Need a way to retrigger a full sync of the accounts table

Use https://giggsey.com/libphonenumber/ to find valid testing numbers

### Search API

* Endpoint: `POST ocs/v2.php/cloud/users/search/by-phone`
* Data (all 3 number formats are valid):
```json
{
	"location": "DE",
	"search": {
		"Unique-Idenifier-For-Contact-1": [
			"0711/25 24 28-90"
		],
		"Unique-Idenifier-For-Contact-2": [
			"+49 711/25 24 28-91",
			"0049 711/25 24 28-92"
		]
	}
}
```
* Response (map of provided identifier and cloudId):
```json
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "Unique-Idenifier-For-Contact-1": "admin@localhost/"
    }
  }
}
```

### CODE REVIEW

**Comment by nickvergessen** [comment]
As per opening post, the lib to validate/unify phone numbers needs a default region.

Best I have in mind is an admin setup warning about the missing region and until that is set only allow `+49` phone numbers and lie to the lib that the default region is `EN`. Falling back to default language "would also work", but e.g. Austrian numbers would be German as they use the same language, so it's not very sensitive/accurate.

Opinions on this? @MorrisJobke @rullzer @ChristophWurst

**Comment by ChristophWurst** [comment]
> As per opening post, the lib to validate/unify phone numbers needs a default region.

Would the locale be more accurate than the language? Like if one sets `de_AT` then you can guess the country. Possible not 100% accurate either but it seems like there is a locale for many countries.

**Comment by MorrisJobke** [comment]
> Best I have in mind is an admin setup warning about the missing region and until that is set only allow `+49` phone numbers and lie to the lib that the default region is `EN`.

Doesn't sound too bad IMO.

**Comment by nickvergessen** [comment]
Anyone an idea about:
> - Need a way to retrigger a full sync of the accounts table

**Comment by nickvergessen** [comment]
Added a repairstep to validate the existing entries. This is now ready to review.

**Review by rullzer — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
