### PR TITLE
Bump @nextcloud/dialogs from 4.0.0-beta.2 to 4.0.1

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Bump `@nextcloud/dialogs` from https://github.com/nextcloud/nextcloud-dialogs/releases/tag/v4.0.0-beta.2 to https://github.com/nextcloud/nextcloud-dialogs/releases/tag/v4.0.1

## Related

- https://github.com/nextcloud/server/pull/36739

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Pytal** [comment]
🤔 This bump alone results in many `OC is not defined` errors and neither `npm i process` nor setting `resolve.alias.process = 'process/browser'` resolve the errors

There are no errors coming from packages so this is probably a result of the core script loading or load order logic, would a dev familiar with the script load logic https://github.com/nextcloud/server/blame/d33fbbed1d20496387decde205f7cac9913b3421/lib/public/Util.php#L173-L217 be able to decipher these errors @mejo-?

**Comment by Pytal** [comment]
Checked the Network tab in devtools and all scripts are loaded in the exact same order as working `master`

Went through the package changes in https://github.com/nextcloud/nextcloud-dialogs/compare/v4.0.0-beta.2...v4.0.1 and cannot find a culprit

So currently out of ideas, does anything stand out to you @artonge?

**Comment by artonge** [comment]
I would look into the first error `process is not defined` from:

`OC/util.js` --> [`@nextcloud/files`](https://github.com/nextcloud/server/blob/c09d4d33138cecc82b53156d8038c340e06867f5/core/src/OC/util.js#L28) --> [`path`](https://github.com/nextcloud/nextcloud-files/blob/94bfe0e1a093dcb8ed6b0710e7bdd8214ba16427/lib/files/node.ts#L22) --> [`process.platform === 'win32'`](https://github.com/jinder/path/blob/7fbaede3ca9d224494cbdd47d7ca803ee96d2055/path.js#L25)

This is preventing OC from being defined.

Not sure why the error is being triggered now, maybe a change in the bundle order moved the initialization, and therefore error, in this code path, making it apparent.

Not familiar enough with modules, but we definitely need to use a browser compatible `path` module. The currently used one is for Node. From [`path-browserify`](https://github.com/browserify/path-browserify), it seems like bundle like webpack automatically use it when importing `path`. Maybe we need to configure rollup in `@nextcloud/files` to have the same behaviour.

**Comment by Pytal** [comment]
Superseded by https://github.com/nextcloud/nextcloud-vue/pull/3772 and https://github.com/nextcloud/server/pull/36813

**Pull request closed without merging**
