### PR TITLE
Sync from nextcloud/server into bugsbane/server

### PR DESCRIPTION
**Pull request by Bugsbane**

### CODE REVIEW

**Comment by Bugsbane** [comment]
Dang it! Syncing from upstream via the GitHub UI is harder than I imagined it would be... *sigh*

**Comment by mar1u5** [comment]
If you contact the GitHub support, they will be able to delete the whole PR :wink:

**Comment by Bugsbane** [comment]
Thanks. Is there a particular benefit to having it deleted (other than saving me some embarrassment? lol)

**Comment by mar1u5** [comment]
No 😜 ... its just cosmetic

**Pull request closed without merging**
