### PR TITLE
Fix for CardDAV/CalDAV Apple Provisioning

### LINKED ISSUE #29433: MacOSX CalDAV/CardDAV + LDAP not working ===> Nextcloud UUID used in LDAP authentication instead of Username
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Enable LDAP Authentication
2. Generate new users ==> UUID
3. Export "Nextcloud Profile" to iOS and install it
4. "Unable to authenticate with username/password"

### Expected behaviour
CalDav/CardDav should work with LDAP auth backend

### Actual behaviour
Nextcloud does not know the "UUID" of the LDAP generated (only available inside Nextcloud)

### Server configuration

**Operating system:** Doesn't matter

**Web server:** Nginx

**Database:** SQL

**PHP version:** 7.4

**Nextcloud version:** 22

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated gradually from 14

**Where did you install Nextcloud from:** Source

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by itmanagerro**
Closes #29433 

Signed-off-by: ITManager <3145531+itmanagerro@users.noreply.github.com>

### CODE REVIEW

**Comment by itmanagerro** [comment]
@acsfer hope all is good now, learned something new today with the DCO thingy

**Comment by itmanagerro** [comment]
@acsfer that samba job is... dead

**Comment by acsfer** [comment]
Yeah, not related to this.

**Review by tcitworld — CHANGES_REQUESTED** [review]
There's no reason for this. The UID should always be used to login and users can login even without an email filled in their account details.

If you're having an issue logging-in with LDAP I would suggest trying to change your configuration to match a better UID.

**Pull request closed without merging**
