### PR TITLE
Fix for high contrast theme

### PR DESCRIPTION
**Pull request by jancborchardt**
High contrast theme before. Note:
- The header icons are not full opacity, only the contacts menu icon.
- There is a dark line visible below the triangle of the user menu (top right), just a cosmetic issue but now fixed.

high contrast theme before

After:
high contrast theme after

Please check @nextcloud/designers @nextcloud/accessibility :heart:

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by jancborchardt** [comment]
> stale15

what are you calling stale, it was just released! :bread:

**Comment by skjnldsv** [comment]
/me get the :popcorn: to see how the bot will :boom:

**Pull request merged**
