### PR TITLE
[stable20] Remove stray compiled assets

### PR DESCRIPTION
**Pull request by PVince81**
This was automatically deleted and not regenerated by:
make dev-setup && make build-js-production

I ran those on stable20 and committed the result.

I didn't see this happen on stable21 or master, so probably it's assets that exist since a while and were never properly deleted.
Also: CI did not complain about those missing.

Removing these will avoid devs to be confused like I was in https://github.com/nextcloud/server/pull/25475 especially when changing seemingly related files.

### CODE REVIEW

**Comment by PVince81** [comment]
I've had a quick test of the users page and it seemed to work fine. The matching acceptance tests will also confirm this.

**Review by rullzer — APPROVED** [review]

**Comment by PVince81** [comment]
restarted CI for hopefully slightly greener results

**Review by ChristophWurst — APPROVED** [review]
Had to do the same in another PR

**Comment by juliushaertl** [comment]
Yes, the settings chunk names are chaning on every build update so they maybe a not cleaned up build has made it to the base branch.

**Comment by juliushaertl** [comment]
Actually we should have https://github.com/nextcloud/server/pull/24865 for stable20 as well

**Comment by PVince81** [comment]
failures seem unrelated: both in acceptance tests for sharing
and one failure is the DB coverage that got killed...

**Comment by PVince81** [comment]
I've raised https://github.com/nextcloud/server/issues/25491 to look into the failed sharing acceptance test as it seems to happen consistently on stable20.

**Comment by PVince81** [comment]
> Actually we should have #24865 for stable20 as well

here we go https://github.com/nextcloud/server/pull/25504

**Pull request merged**
