### PR TITLE
Update CRL after revoke deckimportfromtrello.csr

### PR DESCRIPTION
**Pull request by vitormattos**
References:
* https://github.com/nextcloud/app-certificate-requests/pull/479
* https://github.com/nextcloud/app-certificate-requests/pull/513

### CODE REVIEW

**Comment by mgallien** [comment]
@vitormattos sorry for the delay
do we still need this one ?

**Comment by vitormattos** [comment]
Yes, is the last.

**Review by mgallien — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Pull request merged**
