### PR TITLE
[stable25] Update some deps

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Comment by PVince81** [comment]
recompiling locally

**Review by artonge — APPROVED** [review]

**Comment by PVince81** [comment]
@skjnldsv can you confirm if the theming failure is legit or intermittent ? https://drone.nextcloud.com/nextcloud/server/26342/61/4

**Comment by PVince81** [comment]
unrelated: https://github.com/nextcloud/server/pull/35315#issuecomment-1326579419

**Pull request merged**
