### PR TITLE
Remove unneeded styles: everything is handled by NcVue

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
* For https://github.com/nextcloud/server/issues/41699
* Blocked by https://github.com/nextcloud-libraries/nextcloud-vue/pull/5022

## Summary

Vue-navigation | Unchanged non-vue navigation
---|---
Screenshot from 2024-01-03 15-31-17 | Screenshot from 2024-01-03 15-31-12

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ShGKme** [comment]
This PR changes styles for non-`@nextcloud-vue` navigation while linked PR in nextcloud-vue changes `@nextcloud/vue` navigation. Are they related?

**Review by emoral435 — APPROVED** [review]
I checked this on my dev env and saw that removing this did not cause anything big to stylistically change - it looks good to me. 

I do not know if there are any other apps that somehow depend on this, but to my understanding this only lets the elements that are for app navigation within a page have their border color be the primary color. When the changes to the `NcAppNavigationItem.scss` gets merged, this will be all good 👍

**Review by Pytal — APPROVED** [review]

**Comment by ShGKme** [comment]
> This PR changes styles for non-`@nextcloud-vue` navigation while linked PR in nextcloud-vue changes `@nextcloud/vue` navigation. Are they related?

So, these styles are not supposed to affect `@nextcloud/vue/NcAppNavigation`. But it does, because the layout of the `NcAppNavigation` was changed and the selector here is not actual anymore.

So the best could be to fix the selector.

but probably these styles are not actual anymore. Need to check if we still have any non-NcAppNavigation navigation.

**Comment by ShGKme** [comment]
I haven't found non-vue navigation anywhere. Should be save to remove.

**Review by ShGKme — APPROVED** [review]

**Pull request merged**
