### PR TITLE
Include favorites into normal sorting when not sorting by name

### LINKED ISSUE #2350: Make it possible to disable sticky favourites at the top of the list
### Steps to reproduce

1. Sort the file list by date
2. Mark some files and folder as favourites

### Expected behaviour

Favourites should stay where they are. If I need access to them, I have the favourite filter at my disposal

### Actual behaviour

Favourites are migrated to the top of the list, disrupting the order I picked.

If I order files by date, it's because I deem it important to always know which folders have been recently updated. I don't want to have to mentally re-arrange the order.

Since not everybody may agree with me, I would be fine with a Files setting which allows people like me to disable that "feature" :) 

--------
@jancborchardt

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #2350 

@oparoz @ChristophWurst

### CODE REVIEW

**Comment by ChristophWurst** [comment]
This feels weird. As a user I would either expect favorites to show first regardless of the sorted column or disable the feature completely as @oparoz wrote in #2350.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Agreed with @ChristophWurst

**Comment by nickvergessen** [comment]
Okay, fine by me.

**Comment by jancborchardt** [comment]
Yup, sorry this is strange. Especially since a very common sorting method is sorting by modified date.

And if the file isn’t important enough to be shown on top of the view, why is it favorited? I don’t see why we need a config switch here. Less settings, folks. ;)

**Pull request closed without merging**
