### PR TITLE
implement federated group sharing

### LINKED ISSUE #4252: Federation for groups
Right now Federation works only with users not with groups.

### PR DESCRIPTION
**Pull request by schiessle**
Allows you to share a file/folder with a group on a different server. The group is addressed similiar to a individual user: `<groupname>@<server>`. By default incoming and outgoing federated group shares are disabled in the admin settings.

- [x]  send federated group share
- [x] individual user can accept share
- [x] individual user can decline share
- [x] individual user can unshare from self
- [x] handle unshare notification from owner correctly
- [x] handle permission change from owner correctly
- [x] UI to create federated group share

Fixes #4252

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@schiessle Could you rebase to resolve the conflicts and have less changes as the other PR got merged.

**Comment by schiessle** [comment]
@MorrisJobke just done :slightly_smiling_face:

**Comment by rullzer** [comment]
I would feel a lot more comfortable if you could extend (or copy) the federated integration tests and move them to group shares. Just so we know when it does :boom:

**Comment by schiessle** [comment]
@rullzer I added some integration tests. Now it is your part :wink:

**Comment by rullzer** [comment]
Now the unit tests fail ;)

**Comment by rullzer** [comment]
And yay for tests!

**Comment by schiessle** [comment]
@rullzer unit tests should be fixed now

**Comment by MorrisJobke** [comment]
> Fixes #4252

I added this to the OP 😉

**Review by rullzer — APPROVED** [review]
Yay lets do this!

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Pull request merged**
