### PR TITLE
Show the path, when the filename conflicts

### LINKED ISSUE #1791: show shared files with full path - enhancement
If you share a more than a few files or folders per hyperlink than it would be an necessary enhancement to show the full path not only in the tooltip but directly on the page.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1791 

@jancborchardt @ChristophWurst @MorrisJobke 
### Steps
1. Create a/shared, b/shared, {root}shared
2. Share all with link
3. Go to the "Shared by link" tab and try to identify them...

> bildschirmfoto vom 2016-10-19 11-34-26

### CODE REVIEW

**Comment by rullzer** [comment]
LGTM! Awesome stuff!

**Comment by MorrisJobke** [comment]
Tested and works 👍 

bildschirmfoto 2016-10-20 um 00 26 55


(in this case `share` is also in `a` but doesn't has a name conflict so the full path is not shown ;))

**Comment by zwotzie** [comment]
I would say this solution is good, but not perfekt.

The preferred way would be to show the path always. I'll try to explain why:

* for me it is inconsistent
* you always want to know where
* (best would be to be able to customize the view in the settings, because everybody has his own opinion)
All the best.

**Comment by jancborchardt** [comment]
@zwotzie 

> * for me it is inconsistent

It’s only needed when the folder / file names actually conflict. Nothing inconsistent here. We also don’t show the full path of every file in the normal file list. So showing it always here would actually be inconsistent.

> * you always want to know where

How so? It’s a shortcut. Check the Nautilus sidebar for example or other apps where you have a favorites setting. None of them have the full path always. It’s just too much unnecessary info.

> * (best would be to be able to customize the view in the settings, because everybody has his own opinion)

Introducing a setting for every little thing is just not how we handle things at Nextcloud. If we have a ton of settings, the important settings can’t be found anymore. :) And then the software ends up like so much open source software: sadly very hard to use.

**Comment by roomanus** [comment]
https://github.com/nextcloud/server/issues/1791

**Pull request merged**
