### PR TITLE
Close session fast when doing a test to prevent blocking the next requests

### PR DESCRIPTION
**Pull request by schiessle**
upstream fix: https://github.com/owncloud/core/pull/25249

@blizzz a fix for a issue you also discussed here https://github.com/owncloud/core/issues/15930

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by schiessle** [comment]
@blizzz do you think that's a good solution?

**Comment by blizzz** [comment]
> @blizzz do you think that's a good solution?

Seems OK, works for me, and using the API: LGTM.

**Comment by MorrisJobke** [comment]
@blizzz @schiessle backport?

**Comment by blizzz** [comment]
> @blizzz @schiessle backport?

Considerable for 10, not seeing it a must. My tendency goes slightly against backporting.

**Pull request merged**
