### PR TITLE
Fix 2FA  blocks' width on login screen

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

* Resolves: # 

## Summary

Fixes this UI problem by replacing a fixed with (px) with a secure 100% (flexible) with : 

... so if the parent width changes (currently max-width: 290px), the 2FA blocks will still have a correct adaptive width.

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
CI failure unrelated

**Comment by Jerome-Herbinet** [comment]
Thanks for merging @artonge :-)
Could this be backported to the next minor updates of NC 24 25 26 ?

**Comment by Jerome-Herbinet** [comment]
> > Could this be backported to the next minor updates of NC 24 25 26 ?
> 
> Have you checked if the issue is also there?

Hmm, honestly not ...

**Pull request merged**
