### PR TITLE
[stable27] fix(files): race condition on web files view change

### LINKED ISSUE #39565: [Bug]: open shared folder doesn't work
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

First of all, sorry for my English, I'm using a translator.
If I share a folder and try to open it from shared with me, shared with others...
The url fails, investigating on my own I noticed that in the html of that part the data-path was empty, and in the normal menu it has '/' set, which is how I have it configured.
Since f12 I put data-path="/" to a folder and I was able to enter it.
So there is a bug with the path of the shared folders opened from shares.
This does not happen with files.

### Steps to reproduce

1.Share folder.
2.Move to shared.
3.Open shared folder from there.
4.See that the All Files menu opens.

### Expected behavior

Wait for me to open the shared folder.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
root@next04t:~# sudo -u www-data php  /var/www/nextcloud/occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "###################"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.1.2",
        "overwrite.cli.url": "https:\/\/#######\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "htaccess.RewriteBase": "\/",
        "default_phone_region": "ES",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpdebug": true,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpstreamoptions": {
            "ssl": {
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "logtimezone": "Europe\/Madrid",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "logfile_audit": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "tempdirectory": "\/nextcloud-datos\/tmp\/",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "skeletondirectory": "",
        "force_language": "es",
        "force_locale": "es_ES",
        "allow_user_to_change_display_name": false,
        "account_manager.default_property_scope": {
            "displayname": "v2-local",
            "email": "v2-local",
            "avatar": "v2-local",
            "address": "v2-private",
            "website": "v2-private",
            "phone": "v2-private",
            "twitter": "v2-private",
            "fediverse": "v2-private",
            "organisation": "v2-private",
            "role": "v2-private",
            "headline": "v2-private",
            "biography": "v2-private"
        },
        "profile.enabled": false,
        "auth.webauthn.enabled": false,
        "maintenance": false,
        "loglevel": 2,
        "share_folder": "received_shares"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - auto_groups: 1.5.2
  - bruteforcesettings: 2.7.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.0
  - files_automatedtagging: 1.17.0
  - files_pdfviewer: 2.8.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - group_default_quota: 0.1.7
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - socialsharing_email: 2.6.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - twofactor_admin: 4.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_email: 2.7.3
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - encryption: 2.15.0
  - files_external: 1.19.0
  - firstrunwizard: 2.16.0 (installed 2.16.0)
  - suspicious_login: 5.0.0
  - user_ldap: 1.17.0
  - weather_status: 1.7.0 (installed 1.7.0)
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ShGKme**
* Resolves: #39565

## Summary

A small regression from https://github.com/nextcloud/server/pull/35772/

This issue does not exist on Nextcloud 28 due to full files to view migration.

### How to reproduce

1. Share "Folder A" with some "User"
2. Log in as "User"
3. Open Files
4. Open "Shared with you"
5. Click on "Folder A"

- **Expected behavior:**
  - it opens the sahred folder
  - only "/FolderA" files are requested in "Network"
- **Actual behavior:**
  - root files are shown for a second or as the result
  - "/" and "/FolderA" twice are requested

Try several times to reproduce. Then more files in root then more chances to reproduce.

https://github.com/nextcloud/server/assets/25978914/a846313d-a666-41c7-a7c1-beeefc3483c0

### Root of the issue

There is a race condition.

Opening a shared folder makes 2 actions:

https://github.com/nextcloud/server/blob/6bfbb475ff376bc5f9bafeb7753b5a5050016be6/apps/files_sharing/js/app.js#L260-L263

Changing view from "sharingin" to "files" emits `files:legacy-navigation:changed`

https://github.com/nextcloud/server/blob/6bfbb475ff376bc5f9bafeb7753b5a5050016be6/apps/files/js/app.js#L223-L226

Then the Files view is open on root path `/` which causes **fetching the root files list**.

https://github.com/nextcloud/server/blob/6bfbb475ff376bc5f9bafeb7753b5a5050016be6/apps/files/src/views/Navigation.vue#L233-L242

See `this.show`:

https://github.com/nextcloud/server/blob/2aa15a1afe4ce99c60e8a721d4895e8339c0275e/apps/files/src/views/Navigation.vue#L214-L219

And the handler:

https://github.com/nextcloud/server/blob/2aa15a1afe4ce99c60e8a721d4895e8339c0275e/apps/files/js/filelist.js#L779-L788

Here is were the first request is made.

Then the initial `changeDirectory` is called. Which also results in changing directory (to the correct one) and **fetching the actual shared directory files list**.

🏎️ Here is a race. When the root directory is large, its response may come later so root files are shown instead of the shared folder.

---

Changing view also triggers a `shown` event that sets the current directory to `/` and reloads content. It causes duplicated file requests.

https://github.com/nextcloud/server/blob/2aa15a1afe4ce99c60e8a721d4895e8339c0275e/apps/files/js/filelist.js#L765-L774

Before Vue migration, there was a check for `this.shown` that avoided this behavior.

https://github.com/nextcloud/server/blob/f720d6e73065bc8ad84317981f301f085a600667/apps/files/js/filelist.js#L761-L773

If I'm not wrong, with migrating navigation to Vue, we can just remove this part. cc @skjnldsv 

## TODO

- [x] Add `silent` mode support for legacy navigation changed. Actually, the same that was there before migration to Vue.
- [x] Remove resetting and reloading on view show

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Make sense! Nice catch, this legacy router is a pain :baguette_bread:

**Review by sorbaugh — APPROVED** [review]

**Comment by ShGKme** [comment]
Want to check one more case with page reload when switching from the shared folder to "All files".

**Comment by ShGKme** [comment]
@skjnldsv Do know any edge cases with legacy navigation/apps here that should be tested?

**Comment by ShGKme** [comment]
> Want to check one more case with page reload when switching from the shared folder to "All files".

Unrelated to this issue.

`OC.Util.History` stores query param as a string in a native `history.state`. `vue-router` stores its own state there and crashes finding a string there.

**Pull request merged**
