### PR TITLE
[3rdparty] Bump symfony/routing

### PR DESCRIPTION
**Pull request by rullzer**
Requires:
- [x] https://github.com/nextcloud/3rdparty/pull/13

Lets see what CI says

### CODE REVIEW

**Comment by rullzer** [comment]
CI is happy.

CC: @nickvergessen @MorrisJobke @LukasReschke @icewind1991

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and still works 👍

**Comment by MorrisJobke** [comment]
@rullzer update 3rdparty please ;)

**Comment by rullzer** [comment]
Rebased

**Pull request merged**
