### PR TITLE
change order of keyboard shortcuts settings to be at the end

### PR DESCRIPTION
**Pull request by szaimen**
As today discussed with @nextcloud/designers

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Yup, thank you!

**Comment by jancborchardt** [comment]
And @szaimen the new "App order" section should be below the keyboard shortcut setting, as this is 1 setting and the other one is a possibly long list.

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Pull request merged**
