### PR TITLE
Better check reshare permissions part2

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Code makes sense :+1:

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Failures are due to #16198

**Comment by rullzer** [comment]
Ai more failing tests... https://drone.nextcloud.com/nextcloud/server/19714/14/4

**Comment by MorrisJobke** [comment]
```

631	Scenario: User is not allowed to reshare file with more permissions # /drone/src/build/integration/features/sharing-v1-part2.feature:234
632	As an "admin"
633	[Wed Jul 3 07:59:37 2019] 127.0.0.1:55796 [404]: /ocs/v2.php/cloud/users/user0
634	[Wed Jul 3 07:59:37 2019] 127.0.0.1:55802 [200]: /ocs/v1.php/cloud/users
635	[Wed Jul 3 07:59:37 2019] 127.0.0.1:55810 [200]: /ocs/v1.php/cloud/users/user0
636	[Wed Jul 3 07:59:38 2019] 127.0.0.1:55814 [200]: /ocs/v2.php/cloud/users/user0
637	Given user "user0" exists # FeatureContext::assureUserExists()
638	[Wed Jul 3 07:59:38 2019] 127.0.0.1:55818 [404]: /ocs/v2.php/cloud/users/user1
639	[Wed Jul 3 07:59:38 2019] 127.0.0.1:55820 [200]: /ocs/v1.php/cloud/users
640	[Wed Jul 3 07:59:38 2019] 127.0.0.1:55826 [200]: /ocs/v1.php/cloud/users/user1
641	[Wed Jul 3 07:59:38 2019] 127.0.0.1:55830 [200]: /ocs/v2.php/cloud/users/user1
642	And user "user1" exists # FeatureContext::assureUserExists()
643	[Wed Jul 3 07:59:38 2019] 127.0.0.1:55834 [404]: /ocs/v2.php/cloud/users/user2
644	[Wed Jul 3 07:59:39 2019] 127.0.0.1:55836 [200]: /ocs/v1.php/cloud/users
645	[Wed Jul 3 07:59:39 2019] 127.0.0.1:55842 [200]: /ocs/v1.php/cloud/users/user2
646	[Wed Jul 3 07:59:39 2019] 127.0.0.1:55846 [200]: /ocs/v2.php/cloud/users/user2
647	And user "user2" exists # FeatureContext::assureUserExists()
648	And As an "user0" # FeatureContext::asAn()
649	[Wed Jul 3 07:59:39 2019] 127.0.0.1:55850 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
650	And creating a share with # FeatureContext::creatingShare()
651	| path | /textfile0.txt |
652	| shareType | 0 |
653	| shareWith | user1 |
654	| permissions | 16 |
655	And As an "user1" # FeatureContext::asAn()
656	[Wed Jul 3 07:59:39 2019] 127.0.0.1:55856 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
657	When creating a share with # FeatureContext::creatingShare()
658	| path | /textfile0 (2).txt |
659	| shareType | 0 |
660	| shareWith | user2 |
661	| permissions | 31 |
662	Then the OCS status code should be "404" # FeatureContext::theOCSStatusCodeShouldBe()
663	Failed asserting that SimpleXMLElement Object &0000000072b4142c00000000301d57f1 (
664	0 => '100'
665	) matches expected '404'.
666	And the HTTP status code should be "200" # FeatureContext::theHTTPStatusCodeShouldBe()
667	[Wed Jul 3 07:59:39 2019] 127.0.0.1:55860 [200]: /ocs/v1.php/cloud/users/user0
668	[Wed Jul 3 07:59:39 2019] 127.0.0.1:55866 [404]: /ocs/v2.php/cloud/users/user0
669	[Wed Jul 3 07:59:40 2019] 127.0.0.1:55868 [200]: /ocs/v1.php/cloud/users/user1
670	[Wed Jul 3 07:59:40 2019] 127.0.0.1:55874 [404]: /ocs/v2.php/cloud/users/user1
671	[Wed Jul 3 07:59:40 2019] 127.0.0.1:55876 [200]: /ocs/v1.php/cloud/users/user2
672	[Wed Jul 3 07:59:40 2019] 127.0.0.1:55890 [404]: /ocs/v2.php/cloud/users/user2
673	[Wed Jul 3 07:59:40 2019] Login failed: 'user0' (Remote IP: '127.0.0.1')
674	[Wed Jul 3 07:59:40 2019] 127.0.0.1:55894 [401]: /remote.php/webdav/myFileToComment.txt
675	[Wed Jul 3 07:59:41 2019] 127.0.0.1:55896 [207]: /remote.php/dav/systemtags/
676	[Wed Jul 3 07:59:41 2019] Login failed: 'user0' (Remote IP: '127.0.0.1')
677	[Wed Jul 3 07:59:41 2019] 127.0.0.1:55900 [401]: /remote.php/webdav/myFileToTag.txt
678	[Wed Jul 3 07:59:41 2019] 127.0.0.1:55902 [404]: /remote.php/dav/addressbooks/users/admin/MyAddressbook
679	[Wed Jul 3 07:59:41 2019] 127.0.0.1:55906 [404]: /remote.php/dav/calendars/admin/MyCalendar
```

**Comment by nickvergessen** [comment]
Unified the handling in the `generalCreateChecks` method now, instead of checking it on the API for create and update. This makes it more robust against invalid changes using a different future API which neglects this case by accident.

**Comment by MorrisJobke** [comment]
:+1: from me

**Comment by MorrisJobke** [comment]
Backport are in #16215 and #16216

**Pull request merged**
