### PR TITLE
fix(appstore): Hide last modified information for shipped apps

### LINKED ISSUE #45717: Shipped apps previously released via the app store show "Last updated" date based on legacy app store entry not installed app
Examples: 

- Circles/Teams (circles) [Last updated: 3 years ago... but not really]
- PDF Viewer (files_pdfviewer) [Last updated: 6 years ago... but not really]

Other approach(es):

- Drop the "Last updated" field in the integrated app store for any shipped app
- Publish the current versions of these apps in the app store (which would *also* address the graveyard appearance in the web app store for these apps, which still appear there albeit frozen in time at their last release before they were elevated to "shipped status")

### PR DESCRIPTION
**Pull request by SystemKeeper**
* Resolves: https://github.com/nextcloud/server/issues/45717

## Summary

Don't show the last modified information for apps that are shipped.

Before: 
Bildschirmfoto 2024-10-16 um 23 43 41

After:
Bildschirmfoto 2024-10-16 um 23 45 36

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by provokateurin — APPROVED** [review]

**Comment by SystemKeeper** [comment]
In 28 we don't show the last modified information it seems -> skipping the backport.

**Pull request merged**
