### PR TITLE
Migrate files_sharing to IBootstrap

### LINKED ISSUE #23046: [Files sharing] Log message: "/appinfo/app.php is deprecated"
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

I keep getting the following message in my logs:
```
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:30+0200
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:29+0200
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:29+0200
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:29+0200
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:29+0200
```

### Server configuration

**Database:**
phpMyAdmin

**PHP version:**
7.3.16

**Nextcloud version:** (see Nextcloud admin page)
20.0.0 RC2

App:
Files sharing
1.12.0

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/23046

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@working-name @danielb42 @tocsinde @bdelwood @mardy @kiplingw @cvick @langfingaz please test and report back, then we can move this forward.

**Comment by MorrisJobke** [comment]
It did 💥 when I tried it last time: https://github.com/nextcloud/server/pull/24035 🙈

**Comment by kiplingw** [comment]
> @working-name @danielb42 @tocsinde @bdelwood @mardy @kiplingw @cvick @langfingaz please test and report back, then we can move this forward.

Thanks @ChristophWurst. My issue actually was already resolved. It turned out it was nothing wrong with NextCloud, but the 500s were being raised by `mod_security` using some incomplete rules. Although it might have helped if NextCloud was able to properly inform the user of this instead of having to look through raw Apache logs, as I unfortunately all too often have to.

**Comment by andyxheli** [comment]
@ChristophWurst 

I upgrade from NC 20.0.8 into NC 21.0.1 im running apache2, php8, mariadb started to notic that my error log keep on getting filled up and i see alot of the below errors this is only happening on NC 21.0.1 never had this issue before also i wanted to say the debug option is not checked so im not sure why the log keeps running. I don't know if this fix was suppose to stop this so I wanted to let you know

**Comment by ChristophWurst** [comment]
> debug option is not checked

This is not about *debug mode* but the *log level*. Set your *log level* to *warning* or higher.

**Comment by andyxheli** [comment]
Thank you for your response just so I understand it how do I get my log file to stoop filling up and restating all I see is the ibootstrap messages again not on the web interface but if I open the Nextcloud.log file.

**Comment by danielb42** [comment]
> Thank you for your response just so I understand it how do I get my log file to stoop filling up and restating all I see is the ibootstrap messages again not on the web interface but if I open the Nextcloud.log file.

Change the log level in your config, not just the filter in the web view.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level

**Comment by andyxheli** [comment]
> > Thank you for your response just so I understand it how do I get my log file to stoop filling up and restating all I see is the ibootstrap messages again not on the web interface but if I open the Nextcloud.log file.
> 
> Change the log level in your config, not just the filter in the web view.
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level

Thank you! Im not sure how that changed i always had it at 2 and it was set to 0 but thank you!

**Comment by MorrisJobke** [comment]
🏓

**Comment by ChristophWurst** [comment]
stale -> close

**Pull request closed without merging**
