### PR TITLE
Bump microsoft/azure-storage-blob to 1.5.4 in stable25

### PR DESCRIPTION
**Pull request by come-nc**
- [x] https://github.com/nextcloud/3rdparty/pull/1217
- [x] rebase

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

**Comment by come-nc** [comment]
Not clear what happened to drone

**Comment by ChristophWurst** [comment]
Yes, but why?

**Comment by come-nc** [comment]
> Yes, but why?

Because we need to bump aws/aws-sdk-php for https://github.com/nextcloud/server/issues/34787#issuecomment-1294825040 and that brings trouble with microsoft/azure-storage-blob, as learned on master, so I’m bumping in reverse order on stable25

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
