### PR TITLE
Add a function to get the unread count for multiple objects in one go

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by rullzer** [comment]
1. Create a file foo
2. Share foo with user1
3. Leave a comment on foo
4. Run this query (so find out the fileid of foo)

Don't get back the expected results...

**Comment by nickvergessen** [comment]
Just fixed that in the commit before

**Comment by rullzer** [comment]
> Just fixed that in the commit before

I tested that
But https://github.com/nextcloud/server/pull/23792/commits/a5d6f1d31609e86b0e1185cd1b5bef42cec9dba9 ;) The orX was closed to soon

**Comment by rullzer** [comment]
All working now.
Should be a lot faster!

**Comment by MorrisJobke** [comment]
With this and master I get the exact same 2 times 10 requests (10 against oc_comments and 10 against oc_comments_read_markers) 😢 

I basically shared 10 files and left a comment on each of them. Then did a PROPFIND.

**Comment by MorrisJobke** [comment]
> With this and master I get the exact same 2 times 10 requests (10 against oc_comments and 10 against oc_comments_read_markers) 😢
> 
> I basically shared 10 files and left a comment on each of them. Then did a PROPFIND.

Just checked again and it works 👍

**Review by MorrisJobke — APPROVED** [review]
Tested and works

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I don't know why Psalm triggers this only in that PR here:

```
/home/runner/work/server/server/lib/private/Comments/Manager.php:778:50:error - InvalidArgument: Argument 4 of OCP\DB\QueryBuilder\IQueryBuilder::leftJoin expects null|string, OCP\DB\QueryBuilder\ICompositeExpression provided
```

But other code in the same file also use it and thus I would see it as unrelated and needs to be fixed in a separate PR.

cc @rullzer @kesselb

**Pull request merged**
