### PR TITLE
Drop \OCP\User

### PR DESCRIPTION
**Pull request by ChristophWurst**
Inlines and remaining usages and drops the deprecated public API.

The methods and the class was deprecated three years ago -> :fire:

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Comment by rullzer** [comment]
:boom:

**Comment by shyim** [comment]
You should try https://bugs.php.net/bugs-generating-backtrace.php

**Comment by MorrisJobke** [comment]
CI was green in https://drone.nextcloud.com/nextcloud/server/5237 and only psalm had issues. Those are added now (they were just hidden before, but are now in the baseline).

**Review by MorrisJobke — APPROVED** [review]
Nice 👍

**Comment by MorrisJobke** [comment]
Usages in otherapps:

Bildschirmfoto 2021-05-21 um 15 08 07


I guess the only one is the circles one by @daita that needs immediate change. and maybe dropit.

**Comment by daita** [comment]
fixed in Circles 22

**Pull request merged**
