### PR TITLE
Remove not needed rule for .warning

### LINKED ISSUE #3615: Performance warning on install page not readable
### Steps to reproduce
1. do a clean install of nextcloud

### Expected behaviour
text of warning should be readable

### Actual behaviour
text of warning ain't readable

### Server configuration
**Nextcloud version:** latest master (d0980bec73)

### Screenshot
chromium

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #3615 

cc @skjnldsv @georgehrke

### CODE REVIEW

**Comment by skjnldsv** [comment]
Are you sure we're not using this in any situation?

**Review by skjnldsv — APPROVED** [review]
Seen your other message. Works fine.

**Comment by MorrisJobke** [comment]
> Are you sure we're not using this in any situation?

See https://github.com/nextcloud/server/pull/3618/files#diff-dc80044ed69944b90aacf3c35d781f94R426

**Review by juliusknorr — APPROVED** [review]
Makes sense to remove :+1:

**Pull request merged**
