### PR TITLE
Explicitly check hex2bin input

### PR DESCRIPTION
**Pull request by rullzer**
For #23197

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by axheli** [comment]
@rullzer any updates on this? Still have the issue on NC 20.0.8

**Comment by rullzer** [comment]
> @rullzer any updates on this? Still have the issue on NC 20.0.8

And this patchis not helping? Any different error?

**Comment by axheli** [comment]
@rullzer Testing it out dose this patch have to be added manual every time a new Nextcloud version comes out or will it be added to the next version ?

**Comment by axheli** [comment]
@rullzer so far so good. Do you know if this will be pushed on the next nextcloud release?

**Comment by pseguret** [comment]
> > @rullzer any updates on this? Still have the issue on NC 20.0.8
> 
> And this patchis not helping? Any different error?

@rullzer does this patch can be applied to NC 20.0.9 ? Thx

**Review by AndyXheli — APPROVED** [review]

**Comment by rullzer** [comment]
Hi sorry I was busy debyugging this with others still.
It seems to indeed to the trick let me make sure it gets in.

**Review by ChristophWurst — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Pull request merged**
