### PR TITLE
Fix sharing tab state not matching resharing admin settings

### PR DESCRIPTION
**Pull request by danxuliu**
This fixes a regression introduced probably in Nextcloud 18 when the Sharing tab was moved to Vue (as it worked in Nextcloud 17).

When resharing was disabled in admin settings the menu of a share showed the option to enable or disable resharing for that share, and the share input to search users, groups... to share a file was enabled also for received shares. As resharing was disabled using the menu or the input caused an error.

Besides that I have also added integration tests to check the default share permissions. I thought that there was an issue with the default share permissions, but after checking again I can no longer reproduce :shrug: But as I had already written the tests... I thought that it would be good to add them anyway :-)

~~It seems that I messed building the JavaScript files... I will change to _To review_ after fixing it.~~

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Seems to do the trick. but we should move a lot of those config stuff to the capabilities I think.

**Comment by rullzer** [comment]
> Seems to do the trick. but we should move a lot of those config stuff to the capabilities I think.

But in a future PR of course

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
