### PR TITLE
Some more Dashboard design polishing

### PR DESCRIPTION
**Pull request by jancborchardt**
Quick review @juliushaertl @eneiluj 

- Move widget headings to more semantically correct h2 (since widget entries can contain h3)
- Adjust design of 'Get more widgets' button (more padding)
- Fix text on background choices (was too far down, not vertically centered)
- Suppress scrollbar inside widgets

### CODE REVIEW

**Review by julien-nc — COMMENTED** [review]
> Move widget headings to more semantically correct h2 (since widget entries can contain h3)

Yes.

> Adjust design of 'Get more widgets' button (more padding)

Yes.

> Fix text on background choices (was too far down, not vertically centered)

Yyyyes. Didn't even notice that...

All good!

Any clue on how to fix the statuses color when menu open and hovering the items?

**Comment by jancborchardt** [comment]
Also added a commit to suppress any scrollbars inside widgets. I’m seeing one since https://github.com/nextcloud/mail/pull/3460 it seems – any idea @juliushaertl?

**Comment by jancborchardt** [comment]
> Any clue on how to fix the statuses color when menu open and hovering the items?

Fixed that one now too, ready to review – or anything else? :)

**Review by julien-nc — APPROVED** [review]
Very nice!

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
