### PR TITLE
fix(comments): center align submit button in new comment field

### PR DESCRIPTION
**Pull request by edward-ly**
* Resolves: (unknown, I was given this issue from a design review)

## Summary

A quick and dirty fix for centering the submit button when the comments are first shown. If I have extra time, I could investigate alternative solutions that don't require hardcoded values.

## Checklist

- [x] Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [x] [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

Before | After
-- | --
Screenshot 2024-07-17 at 16-45-04 Files - Nextcloud | Screenshot 2024-07-17 at 16-45-23 Files - Nextcloud

### CODE REVIEW

**Comment by edward-ly** [comment]
> If I have extra time, I could investigate alternative solutions that don't require hardcoded values.

I figured out how to do exactly that, with the added benefit being that the button remains centered regardless of the number of lines in the text box. Although, I'm not sure if that is preferable to before where the button is always on the last line, and the text may overlap with the button regardless.

(top is [983f121](https://github.com/nextcloud/server/pull/46595/commits/983f121dc3ad3f915ded3a1a3dd5a7e96bca9abd), bottom is [8f11535](https://github.com/nextcloud/server/pull/46595/commits/8f115353c8a94d71b002f49e46070ee5eeb506de))

Screenshot 2024-07-17 at 21-11-02 Files - Nextcloud
Screenshot 2024-07-17 at 21-04-00 Files - Nextcloud

**Comment by marcelklehr** [comment]
Thanks for the PR, edward! I think, personally, I'd prefer [983f121](https://github.com/nextcloud/server/pull/46595/commits/983f121dc3ad3f915ded3a1a3dd5a7e96bca9abd), even if that is more of a dirty fix :D

**Comment by edward-ly** [comment]
> Thanks for the PR, edward! I think, personally, I'd prefer [983f121](https://github.com/nextcloud/server/pull/46595/commits/983f121dc3ad3f915ded3a1a3dd5a7e96bca9abd), even if that is more of a dirty fix :D

Sorry for the wait, I reverted back to the quick and dirty fix now and cleaned up the branch commits.

**Review by marcelklehr — APPROVED** [review]

**Review by bigcat88 — APPROVED** [review]

**Pull request merged**
