### PR TITLE
Add clear search button

### LINKED ISSUE #2840: add 'x' to search box to clear search pattern with one click
## Expected behavior

The search box should allow to clear entered search pattern with one click. This is commonly be done by adding a 'x' to the end of an input field.

## Current behavior

The search box doesn't allow to clear entered search pattern with one click. All search pattern need to be deleted one by one.

Current search box layout:
20161223_nc_add_x_to_search_box
Search box mockup:
20161223_nc_add_x_to_search_box_new

### Steps to reproduce
1. Open e.g. the files app
2. Enter a search pattern.

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2

#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #2840

capture d ecran_2017-01-25_09-16-30

One issue is that clicking on the button loses the focus on the search input.
This could be fixed with some js on the button: 
`document.getElementById('searchbox').focus();`
But I don't know is there is a specific file where I should put this.

@nextcloud/javascript @nextcloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
Please make sure you always use the scour command from:
https://github.com/nextcloud/server/blob/master/core/img/image-optimization.sh#L10
Using that the file was reduced more than 50% in size. :)

Looks good btw! :+1: Only thing: Aren’t there some default X buttons in some browsers? Couldn’t find them in Firefox or Chrome (even though I thought Firefox had them), what about Safari @nextcloud/mac?

**Comment by skjnldsv** [comment]
Oups, indeed! 😆 
There is for webkit, but this pr override them as they're not properly customisable across browsers :)

**Comment by eppfel** [comment]
### Mac

#### Safari: 
bildschirmfoto 2017-01-25 um 11 42 44

#### Chrome: 
bildschirmfoto 2017-01-25 um 11 43 22

**Comment by jancborchardt** [comment]
@skjnldsv @eppfel do we want to override that or rather keep the macOS default? I’m fine with either, and if it’s a lot of hacking then I’d rather say we stick with the default.

**Comment by skjnldsv** [comment]
look at the commit, this is not a lot of hacking. Just the focus issue that bothers me. If you're not fine with a little js to fix this, we should indeed get back to the default webkit. 😃 
And at least it works on all browsers.

**Comment by claell** [comment]
Since the default button doesn't look good in some configurations (on Chrome and Linux for example) there has to be a "fallback" or standard-mode anyway.
So using the browsers' default version would require checks for certain configurations where it looks good/better, which means some extra work, but might be worth it.

Another argument against using browsers default would be to have the same look and feel of Nextcloud on all setups.

**Comment by MorrisJobke** [comment]
Works here in Firefox, Chrome, Safari and IE11 👍 

What are the remaining open points?

**Comment by blizzz** [comment]
Setting the focus goes easily with 

```diff
diff --git a/core/search/js/search.js b/core/search/js/search.js
index 4dd29ef917..a36ecf0073 100644
--- a/core/search/js/search.js
+++ b/core/search/js/search.js
@@ -405,6 +405,10 @@ $(document).ready(function() {
            OC.Search = new OCA.Search($('#searchbox'), $('#searchresults'));
        });
    }
+
+   $('#searchbox + .icon-close-white').click(function() {
+       $('#searchbox').focus();
+   });
 });
 
 /**
```

However, the results are not updated/reset. Needs some more magic…

**Comment by skjnldsv** [comment]
Here you go, tested ff and chromium! :)

**Review by LukasReschke — APPROVED** [review]
Works :) 👍

**Review by MorrisJobke — APPROVED** [review]
Works 👍

**Pull request merged**
