### PR TITLE
Fix wrong preserveAspectRatio at app menu icons

### PR DESCRIPTION
**Pull request by juliusknorr**
There was a wrong attribute causing an error in the javascript console with chrome, introduced with #627 

> Error: <image> attribute preserveAspectRatio: Unrecognized enumerated value, "true".

While "true" worked, this PR uses the correct values.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks good! :+1:

**Comment by mar1u5** [comment]
LGTM ... Backport to `stable10`? @karlitschek

**Comment by mar1u5** [comment]
Backport does already include this fix :sweat_smile:

**Comment by karlitschek** [comment]
please backport

**Pull request merged**
