### PR TITLE
Fix share permission checkboxes enabled when permissions can not be set

### PR DESCRIPTION
**Pull request by danxuliu**
Note that the acceptance tests will probably fail because [the Files app is currently broken due to the jQuery update](https://github.com/nextcloud/server/pull/20949#issuecomment-631057018), but I run them locally with jQuery 2.1.4 and they passed.

## How to test (scenario 1)

- As user A, share a file with user B
- Open the menu for the share and uncheck "Can edit"
- As user B, reshare the file with user C
- Open the menu for the share

### Result with this pull request

_Can edit_ is unchecked and disabled.

### Result without this pull request

_Can edit_ is unchecked and enabled. Trying to check it triggers an error.

## How to test (scenario 2)

- As user A, share a file with user B
- As user B, reshare the file with user C
- As user A, open the menu for the share and uncheck "Can edit"
- As user B, reload the page and open the menu for the share
- _Can edit_ is checked and enabled
- Uncheck _Can edit_

### Result with this pull request

_Can edit_ is unchecked and disabled.

### Result without this pull request

_Can edit_ is unchecked, but still enabled. Trying to check it triggers an error.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant: 
but with so many tests... :rocket:

**Comment by ChristophWurst** [comment]
> Note that the acceptance tests will probably fail because [the Files app is currently broken due to the jQuery update](https://github.com/nextcloud/server/pull/20949#issuecomment-631057018), but I run them locally with jQuery 2.1.4 and they passed.

Mind elaborating? Is the the one issue where the jQuery `load` event fires too soon, like before some of the script have been loaded?

**Review by ChristophWurst — APPROVED** [review]

**Comment by danxuliu** [comment]
> > Note that the acceptance tests will probably fail because [the Files app is currently broken due to the jQuery update](https://github.com/nextcloud/server/pull/20949#issuecomment-631057018), but I run them locally with jQuery 2.1.4 and they passed.
> 
> Mind elaborating? Is the the one issue where the jQuery `load` event fires too soon, like before some of the script have been loaded?

I am afraid that I do not know if the issue is the `load` event firing too soon or something else. It could very well be, though; the problem is that, sometimes, the file list does not load in the Files app if jQuery 2.2.4 is used (I recall seeing an error in the console about `OCA.Files.Sidebar.close()` (or something similar) not being defined), but it works fine if jQuery 2.1.4 is used.

**Comment by ChristophWurst** [comment]
I your observation matches with my problem because of the way our legacy *modules* register themselves on the global variables. If one of the modules is not loaded when I dependent of it is executed, you'll get an error.

**Comment by rullzer** [comment]
So... to merge or not to merge?

**Comment by danxuliu** [comment]
> So... to merge or not to merge?

Merge, we were talking about why the acceptance tests for the Files app fail since the jQuery bump, but it does not affect the fix itself :-)

**Pull request merged**
