### PR TITLE
feat(theming): Provide CSS variable for favorite color and adjust for dark mode

### PR DESCRIPTION
**Pull request by susnux**
## Summary
Provide the favorite color as a CSS variable and adjust it for the dark mode to look a bit nicer (bright mode does not work due to contrast issues).

Screenshot 2024-03-06 at 14-37-04 Files - Nextcloud

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM :)

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
```
There were 2 failures:

1) OCA\Theming\Tests\Themes\HighContrastThemeTest::testAccessibilityOfVariables with data set "status color elements on background" (array('--color-error', '--color-error-hover', '--color-warning', '--color-warning-hover', '--color-info', '--color-info-hover', '--color-success', '--color-success-hover', '--color-favorite'), array('--color-main-background', '--color-background-hover', '--color-background-dark', '--color-background-darker', '--color-main-background-blur'), 3.0)
Contrast is not high enough for --color-favorite (#a08b00) on --color-background-dark (#cccccc)
Failed asserting that 2.1132910819756194 is equal to 3.0 or is greater than 3.0.

/home/runner/work/server/server/apps/theming/tests/Themes/AccessibleThemeTestCase.php:185

2) OCA\Theming\Tests\Themes\DefaultThemeTest::testAccessibilityOfVariables with data set "status color elements on background" (array('--color-error', '--color-error-hover', '--color-warning', '--color-warning-hover', '--color-info', '--color-info-hover', '--color-success', '--color-success-hover', '--color-favorite'), array('--color-main-background', '--color-background-hover', '--color-background-dark', '--color-background-darker', '--color-main-background-blur'), 3.0)
Contrast is not high enough for --color-favorite (#a08b00) on --color-background-dark (#ededed)
Failed asserting that 2.898860431762695 is equal to 3.0 or is greater than 3.0.

/home/runner/work/server/server/apps/theming/tests/Themes/AccessibleThemeTestCase.php:185
```

**Review by marcoambrosini — APPROVED** [review]
Nice :)

**Comment by skjnldsv** [comment]
Still failing 

```
There was 1 failure:

1) OCA\Theming\Tests\Themes\DefaultThemeTest::testAccessibilityOfVariables with data set "status color elements on background" (array('--color-error', '--color-error-hover', '--color-warning', '--color-warning-hover', '--color-info', '--color-info-hover', '--color-success', '--color-success-hover', '--color-favorite'), array('--color-main-background', '--color-background-hover', '--color-background-dark', '--color-background-darker', '--color-main-background-blur'), 3.0)
Contrast is not high enough for --color-favorite (#B08008) on --color-background-darker (#dbdbdb)
Failed asserting that 2.554659656022142 is equal to 3.0 or is greater than 3.0.

```

**Pull request merged**
