### PR TITLE
A pending shares overview

### PR DESCRIPTION
**Pull request by rullzer**
Now that we accept shares we should show an overview of shares that are
pending. This first part is the small API to get a list of the currently
pending shares.

As noticed by @tobiasKaminsky 
If you now press X on a share. It just doesn't show.

For now I would go for a new section in the sharing section. But for 19 we should look into unifying this with the deleted shares. @nextcloud/designers

### CODE REVIEW

**Comment by juliushaertl** [comment]
@rullzer Pushed a commit for the frontend part. For now I've added a separate "pending shares" list where the user can either accept or reject them.

**Comment by rullzer** [comment]
@juliushaertl mmm it isn't working for me... I don't see the request in the network tab as well..

**Comment by rullzer** [comment]
Awesome!

Only thing. The details and show in folder in the '...' are kind of broken now...

**Comment by juliushaertl** [comment]
> Only thing. The details and show in folder in the '...' are kind of broken now...

Fixed :wink:

**Comment by wiswedel** [comment]
@juliushaertl Can you provide a screenshot please?

**Comment by tobiasKaminsky** [comment]
image

Behind "Name" is 123.txt, which is barely readable.

**Comment by tobiasKaminsky** [comment]
(might be because of my test system, but I did not got any notification (red alarm bell)?
I thought I received one on plain master?

**Comment by juliushaertl** [comment]
> Behind "Name" is 123.txt, which is barely readable.

Unrelated, please open a separate issue.

> (might be because of my test system, but I did not got any notification (red alarm bell)? I thought I received one on plain master?

Do you have the notifications app enabled and did you wait for some time as the web ui just polls regularly for new notifications.

**Comment by rullzer** [comment]
> (might be because of my test system, but I did not got any notification (red alarm bell)?
> I thought I received one on plain master?

This doesn't touch any notification code.
So lets review what this fixes and get it in and then we look at other things ;)

**Comment by tobiasKaminsky** [comment]
:+1: working otherwise

**Comment by jancborchardt** [comment]
> For now I would go for a new section in the sharing section. But for 19 we should look into unifying this with the deleted shares. @nextcloud/designers

:( I heard this often before … yes I guess it has to be done like this for lack of time, but I’m not happy as I doubt it will in fact be fixed for 19. The spec has been there for ages at https://github.com/nextcloud/server/issues/2192

**Comment by juliushaertl** [comment]
> :( I heard this often before … yes I guess it has to be done like this for lack of time, but I’m not happy as I doubt it will in fact be fixed for 19. The spec has been there for ages at #2192

If we schedule some time for that in 19, I think this should be doable with not to much effort. Just nothing we can implement properly 1 1/2 weeks before the actual release.

**Comment by rullzer** [comment]
> > For now I would go for a new section in the sharing section. But for 19 we should look into unifying this with the deleted shares. @nextcloud/designers
> 
> :( I heard this often before … yes I guess it has to be done like this for lack of time, but I’m not happy as I doubt it will in fact be fixed for 19. The spec has been there for ages at #2192

I know what you mean. But the alternative is that we have nothing right now. ;)

**Comment by rullzer** [comment]
Fixed the tests.
Lets do this.

**Review by john6361 — APPROVED** [review]

**Review by john6361 — APPROVED** [review]
Tq

**Pull request merged**
