### PR TITLE
Fix showConflict

### LINKED ISSUE #2680: Bad file info on conflicting upload
Webgui NC11.0:
Consider user A having the GUI showing a shared directory. User B uploads a file test.txt to that directory. Now user A tries to upload a test.txt to that directory as well. After the server-side conflict, the GUI will try to preview.png that B-Version of test.txt, but fails since an invalid URL is created. Apparently, the fileInfo.directory as expected by oc-dialogs isn't filled, so the URI is assembled as undefined/DirName. As a result, not only the preview image won't show up, but the file information isn't retrieved from B-test.txt but from the root directory.
This definitively did work correctly in NC10.

NB: If the A-GUI already shows the B-version, the conflict is identified right from the filelist without server roundtrip, giving the correct preview image and file information.

### PR DESCRIPTION
**Pull request by andreas-p**
This fixes #2680 
use getFullFileName to show conflicting file 
add original.directory to make fileExists happy

### CODE REVIEW

**Comment by andreas-p** [comment]
Hm, why is this bugfix marked enhancement/target NC12?

**Comment by LukasReschke** [comment]
> Hm, why is this bugfix marked enhancement/target NC12?

All changes in master target 12 by default and after this has been reviewed we can discuss here whether we should backport it to older releases :)

**Comment by LukasReschke** [comment]
@andreas-p The sign-off is missing, can you look into https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work? THX a lot! 🚀

**Comment by andreas-p** [comment]
Some trouble with eclipse git provider... finally done.

**Comment by schiessle** [comment]
@andreas-p First, thanks a lot for your pull request!

Your commit history looks messed up. Can you squash all commits into one:

````
git rebase -i 3714a6aaf0b565808bd1ec7f8552196447402f58
````

a texteditor will open and you will see something like this:

````
pick e0d0c2b025 Fix showConflict
pick 80c2db2438 signoff
pick ac15a71473 signoff
pick 180de69d28 signoff
pick 494b28efd2 Final sign-off fake commit...
````

change it to:

````
pick e0d0c2b025 Fix showConflict
f 80c2db2438 signoff
f ac15a71473 signoff
f 180de69d28 signoff
f 494b28efd2 Final sign-off fake commit...
````

save the file and exit the text editor.

now you should only have one commit. Run `git commit --amend -s`. Again a texteditor will show up with your commit message, the sign-off is already added. Adjust the commit message if you want, save the file and exit. Now you just need to force push it back to github: `git push origin fix-remote-conflict --force`. Done.

Hope you can follow this steps, if you have any problems please ask. Thanks!

**Comment by andreas-p** [comment]
@schiessle Thanks for that step-by-step instruction, I'm not that git guru :-)

**Comment by schiessle** [comment]
Thanks! Commit history looks good now. I could also reproduce the bug, your pr fixes it 👍

**Review by schiessle — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
