### PR TITLE
improve query to detect shared mountpoint in folder

### PR DESCRIPTION
**Pull request by icewind1991**
Added in #31610, the logic to find shared mountpoints in a folder relies on a `IN` expression which doesn't scale past 1000 items with oracle.

This changes the logic to not require any `IN`, it does require loading more results from the database though as there is no proper way to filter a path only for direct children in sql.

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by PVince81** [comment]
conflicts, and need to check if compatible with new NC 24 FS code

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@icewind1991 please resolve conflict

**Comment by PVince81** [comment]
is it covered by unit tests ?

**Comment by szaimen** [comment]
conflicts

**Comment by PVince81** [comment]
abandoned?

**Comment by skjnldsv** [comment]
Conflicts are a bit too big for me to rebase :see_no_evil:

**Comment by skjnldsv** [comment]
Closing this pull request due to lack of recent activity and updates. We appreciate your contribution and encourage you to reopen or provide further updates if necessary. :relaxed: 
Our aim is to keep the project moving forward with active collaboration. Thank you for your understanding and continued support! :pray:

**Pull request closed without merging**
