### PR TITLE
fix(apps): Fix type information of app manager

### PR DESCRIPTION
**Pull request by nickvergessen**
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — CHANGES_REQUESTED** [review]
Please add the return types to the method head (both interface and implementation).

**Comment by nickvergessen** [comment]
> Please add the return types to the method head (both interface and implementation).

Breaks public API, so not for now

**Review by ChristophWurst — COMMENTED** [review]
Looks good. Context? Is this a regression?

**Review by come-nc — APPROVED** [review]

**Comment by provokateurin** [comment]
> Breaks public API, so not for now

Why would it break something? If the data returned matches the type then it just adds additional information?

**Review by provokateurin — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
