### PR TITLE
Fix login page, because only guest.css is loaded now

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @rullzer @nickvergessen @skjnldsv 

Fixes https://github.com/nextcloud/server/pull/3795#issuecomment-285626474 - followup to #3791

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Looking good again!

**Comment by MorrisJobke** [comment]
Copy of https://github.com/nextcloud/server/blob/c1be2d80ad74efd9ce63e2eef17d53358cd1aa37/core/css/guest.css#L628-L639

**Comment by MorrisJobke** [comment]
Copy of https://github.com/nextcloud/server/blob/0c22a6696703225baabd6a4afaad5759745da8c5/core/css/global.scss#L27-L38

**Review by LukasReschke — APPROVED** [review]
Works :)

**Pull request merged**
