### PR TITLE
Fix inverted app icons on IE11

### LINKED ISSUE #7408: IE11 with white theming doesn't show black app icons
Safari ✅:

bildschirmfoto 2017-12-06 um 10 03 41

Edge ✅:

bildschirmfoto 2017-12-06 um 10 17 28

IE 11 :x::

bildschirmfoto 2017-12-06 um 10 17 52

Also happens on stable12.

cc @nextcloud/designers @nextcloud/theming 

@jancborchardt Could you have a look at this?

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes https://github.com/nextcloud/server/issues/7408

This PR also includes some minor fixes to the apps management on IE11.

Before:
bildschirmfoto vom 2018-01-03 09-20-50

After:
bildschirmfoto vom 2018-01-03 09-21-32

Tested with Chrome, Firefox and IE11

@nextcloud/designers

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@juliushaertl is it possible to backport this to stable12?

**Comment by MorrisJobke** [comment]
Now it does work in IE11 but not in Edge anymore :/ (the icon itself is white but the app icons are also invisible)

bildschirmfoto 2018-01-03 um 11 08 11

**Comment by juliushaertl** [comment]
@MorrisJobke Fixed for edge as well. 😉

**Comment by MorrisJobke** [comment]
IE is still not working (I used a light grey to check if the icons are there and rendered white or if they are somehow corrupted):

bildschirmfoto 2018-01-03 um 15 25 43


Top to bottom: Firefox, Chrome, Safari, Edge, IE11.

**Comment by juliushaertl** [comment]
@MorrisJobke That's quite strange. Works fine here with Edge and IE11

**Comment by MorrisJobke** [comment]
> @MorrisJobke That's quite strange. Works fine here with Edge and IE11

Let me retest this then :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works now ... I guess it was a caching issue, because I rolled back and forward a lot on this instance. With a fresh install it worked fine. 👍

**Comment by MorrisJobke** [comment]
@juliushaertl Could we backport this to stable12?

**Comment by juliushaertl** [comment]
I see no problem there, let me have a look.

**Comment by juliushaertl** [comment]
backported at https://github.com/nextcloud/server/pull/7684

**Pull request merged**
