### PR TITLE
Do not allow to delete/update group shares as a group member

### PR DESCRIPTION
**Pull request by nickvergessen**
@rullzer can you please take care of adding tests?

### CODE REVIEW

**Comment by rullzer** [comment]
O man that is nasty indeed.
I'll take care of the tests.

**Comment by schiessle** [comment]
setting to "developing" until tests are added

**Comment by rullzer** [comment]
And we have an intergration test!
:tada: 

@schiessle please review

**Comment by rullzer** [comment]
:+1: for @nickvergessen commit

**Comment by schiessle** [comment]
looks good :+1:

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
