### PR TITLE
fix parameter provided as string not array

### PR DESCRIPTION
**Pull request by blizzz**
array is enforced through TypeHint

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
🙈, is there no Psalm available for the ldap methods? *cough*

**Comment by blizzz** [comment]
> see_no_evil, is there no Psalm available for the ldap methods? _cough_

you're asking things. tbh, i did not look into Psalm much yet. Nevertheless I was having a false positive of it in LDAP code. In the Psalm config apps/ is included and there is no special treatment for anything LDAP related.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
