### PR TITLE
still include the share target in the cache key for validating share mount

### LINKED ISSUE #36153: Regression when renaming incoming shares
There seems to be a regression from https://github.com/nextcloud/server/pull/36047 where renaming shares is not working properly anymore.

Steps to reproduce:
- Share a file from A to B
- Login as B
- Rename the file
- Reload the file list

Expected:
- The new name should be shown

Actual:
- The old name is still shown

cc @icewind1991 @PVince81

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #36153, alternative for https://github.com/nextcloud/server/pull/36159

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]
Makes sense 👍

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by juliushaertl** [comment]
Text CI running https://github.com/nextcloud/text/actions/runs/3930450707/jobs/6720487571

**Review by nickvergessen — APPROVED** [review]

**Comment by PVince81** [comment]
stable25: https://github.com/nextcloud/server/pull/36169
stable24: https://github.com/nextcloud/server/pull/36170

**Pull request merged**
