### PR TITLE
chore(OCP): Remove deprecated dashboard interfaces and classes

### PR DESCRIPTION
**Pull request by juliusknorr**
## Summary

The old dashboard API interfaces and classes have been deprecated since Nextcloud 20 (older than 2 years and 6 releases) so we can drop those for 26 as they have been directly replaced with Nextcloud 20 with the new API.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by come-nc — APPROVED** [review]

**Comment by nickvergessen** [comment]
Should be documented in https://github.com/nextcloud/server/issues/34692

**Comment by DaphneMuller** [comment]
hello @come-nc  
Thank you so much for your work on this pull request! This ticket seems to have the tag 'pending documentation'. 
Is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

**Comment by juliushaertl** [comment]
Added to https://github.com/nextcloud/server/issues/34692 accordingly

**Pull request merged**
