### PR TITLE
Use native font stack

### PR DESCRIPTION
**Pull request by jancborchardt**
No screenshots since you have to try this yourself to see.

After discussions and deliberations in https://github.com/nextcloud/server/pull/16040, here’s a pull request to try out a native font stack.

⭕ This is what many big platforms (GitHub, Medium, Wordpress, Ghost, Bootstrap, Booking.com) actually do to make everything feel native on any platform. Just like we don’t mess with the fonts in our iOS and Android apps (and had backlash when we did) this makes Nextcloud feel more native.

㊗️ Fixes the whole mess we would have with needing to support different fonts and character sets by simply going for the native approach.

:zap: Apart from this it will of course make the web interface faster by not needing to load a specific font.

More info:
- https://css-tricks.com/snippets/css/system-font-stack/#article-header-id-1
- https://flaviocopes.com/css-system-fonts/

(We still need to fix the part with the generator for preview and avatar not having certain characters like Chinese, but that’s separate.)

For website and promo material we would keep using Open Sans / Noto Sans as we already do.

Please review @nextcloud/designers @chiyi4488 @R0maNNN @KekcuHa @kesselb @hbqclh @HuidaeCho @jospoortvliet @karlitschek

### CODE REVIEW

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/2d0337332d64065c5bf36dfb775c48976c0f730d/core/css/server.scss#L5

Please remove this line

**Comment by jancborchardt** [comment]
> https://github.com/nextcloud/server/blob/2d0337332d64065c5bf36dfb775c48976c0f730d/core/css/server.scss#L5
> 
> Please remove this line

Good catch, removed! :)

**Review by ChristophWurst — APPROVED** [review]
Still looks good on my system.

I use Arch, btw.

**Review by rullzer — APPROVED** [review]
Also looks good here.

Did I also mention that I also use Arch?

**Review by skjnldsv — APPROVED** [review]
Looks really good!

I also use arch btw

**Review by juliusknorr — APPROVED** [review]
Also looks good on arch btw :+1:

**Review by ChristophWurst — APPROVED** [review]
Looks good on IE11/Win7

Bildschirmfoto von 2019-06-25 22-38-21

**Review by tcitworld — APPROVED** [review]
Didn't test, but I too use arch.

**Review by kesselb — APPROVED** [review]
Looks good on Ubuntu (19.04) as well

**Comment by MorrisJobke** [comment]
Did I mentioned that I used Arch in the past? 👀

**Comment by eh8** [comment]
Consider using [Inter](https://rsms.me/inter/) over Roboto since it looks similar to macOS's San Francisco and Helvetica. IIRC Github already uses it on its landing page. I use Arch, btw.

**Comment by kesselb** [comment]
@eh8 mind to create a new enhancement issue?

**Comment by jancborchardt** [comment]
> Consider using [Inter](https://rsms.me/inter/) over Roboto since it looks similar to macOS's San Francisco and Helvetica. IIRC Github already uses it on its landing page. I use Arch, btw.

We are not delivering any fonts but using a native font stack, meaning we only reference fonts which are pre-installed on people’s systems. Roboto is set since that will be used by Android. I don’t know of any system which has Inter installed by default, so while it does look great, it doesn’t make a lot of sense to reference that.

Also, one of the main reasons we moved to a native font stack was that the font we used (Nunito) only supported Latin, Greek and Cyrillic character sets – this issue is the same with Inter so it would be a downgrade from the native font stack approach.

**Comment by eh8** [comment]
I discovered the custom CSS extension shortly after your response. I think that is a good compromise between maintaining compatibility with the native font stack and allowing customization.

**Pull request merged**
