### PR TITLE
[stable23] Bump underscore from 1.12.0 to 1.12.1

### PR DESCRIPTION
**Pull request by PVince81**
Like https://github.com/nextcloud/server/pull/31984 for stable23

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Comment by PVince81** [comment]
I did add the commit that fixes the test but it's not working here, needs further investigation

**Comment by PVince81** [comment]
seems my rebase/conflict-solving had annihilated the commit

I've brought it back now

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
