### PR TITLE
[stable11] popovermenu backport

### PR DESCRIPTION
**Pull request by skjnldsv**
Backport of the corrected popovermenu.

Main ref: #3024  #3118 #3035
Additional ref: https://github.com/nextcloud/contacts/pull/101

Tests: file action popover, calendar popover, user personal info privacy popover, mail account popover...

@nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
@nextcloud/designers bump

**Review by MorrisJobke — APPROVED** [review]
Tested and looks good :)

**Comment by skjnldsv** [comment]
Bump? 🐤

**Comment by nickvergessen** [comment]
Backporting this will break all apps that use this?

**Comment by skjnldsv** [comment]
@nickvergessen no it should not change a thing since most of the app were sort of close to the css guidelines. But it will greatly increase compatibility between stable11 and 12 for the popover! :)

**Review by LukasReschke — APPROVED** [review]
I'd say let's merge it for now and if we see massive problems in the RC we can revert it again.

**Comment by skjnldsv** [comment]
Youhouuu! :D

**Pull request merged**
