### PR TITLE
Add option to fetch specific user from LDAP

### PR DESCRIPTION
**Pull request by goyome**
Signed-off-by: Guillaume COLSON <guillaume.colson@univ-lorraine.fr>
Address issue #27948 
This PR is meant to replace #29326 after discussing about it with @blizzz

### CODE REVIEW

**Comment by come-nc** [comment]
I think this is obsolete because of https://github.com/nextcloud/server/pull/29837 which is already merged.
@goyome Can you confirm?

**Comment by goyome** [comment]
@come-nc Thanks for your improvement and sorry for the late reply. I had few times to make the appropriate tests.

I tried to fetch a new ldap user with 
`php occ ldap:check-user --update new_user`
but the script stop with the error
`The given user is not a recognized LDAP user.`
which is returned by the function `$this->confirmUserIsMapped($uid);` which is executed before `$exists = $this->backend->userExistsOnLDAP($uid, true);`

Anyway, I tried to move the call to confirmUserIsMapped after the update but no changes.

Maybe you should add a call to `$this->backend->loginName2UserName($uid)` in the update call instead of adding the new fetch option but to me the functionnality needs to be implemented in one way or the other.

**Comment by come-nc** [comment]
@goyome I think I tested check-ldap for newly-deleted users but not for newly-created users.

When I find time I will look into fixing this as well.

**Comment by goyome** [comment]
Thanks a lot :+1:

**Pull request closed without merging**
