### PR TITLE
Filepicker styling

### PR DESCRIPTION
**Pull request by icewind1991**
and some minor fixes.

Brings the filepicker styling closer to the normal file list styling

Before:

After:

cc @jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
Good stuff! :+1: please review too @nextcloud/designers 

@icewind1991 how about next thing being the #645 (sort by modified date / respect files sorting ;) ?

**Comment by MorrisJobke** [comment]
Tested and works 👍 

Only one nitpick: mimetype icons are too small on IE/Edge, but this is also the case with master -> separate issue:

bildschirmfoto 2016-10-14 um 18 27 01

**Comment by MariusBluem** [comment]
Nice work 👍

**Comment by MorrisJobke** [comment]
> Only one nitpick: mimetype icons are too small on IE/Edge, but this is also the case with master -> separate issue:

https://github.com/nextcloud/server/issues/1757

**Comment by MorrisJobke** [comment]
I backported those fixes to stable10 - #1758

**Pull request merged**
