### PR TITLE
Show registered breadcrumb detail views in breadcrumb menu

### PR DESCRIPTION
**Pull request by julien-nc**
So it's consistent with the full breadcrumb.

This way the sharing icon (for example) is there and can be clicked to open the sidebar.
breacrumb

Tested on stable20, stable21 and stable22.
Make sure you set `debug` to `true` in `config/config.php` to try these changes.

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Looks good but didn't test

**Review by artonge — APPROVED** [review]
LGTM

**Review by marcoambrosini — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failures unrelated.

**Comment by eneiluj** [comment]
@juliushaertl Would you agree it makes sense to backport this to stable20, 21 and 22?

**Comment by juliushaertl** [comment]
Fine by me, I'd rather consider that a bug for mobile anyways that the button would be no longer accessible.

**Pull request merged**
