### PR TITLE
Share api expanded by tags

### PR DESCRIPTION
**Pull request by MorrisJobke**
* downstream of https://github.com/owncloud/core/pull/26583
* add the favourites to the "Shared with you" & "Shared by you"

@rullzer @schiessle I adjusted the downstream to the new location of the sharing code.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I rebased to resolve a conflict

**Comment by MorrisJobke** [comment]
:+1: from me on this

**Review by rullzer — APPROVED** [review]
I'm stll not very happy with this. But I see no (or rather don't have time for) a better way.

@jancborchardt you can be happy...

**Review by rullzer — DISMISSED** [review]
Mmmm it seem the data is not properly re-requested....

**Comment by rullzer** [comment]
Rather rerendered.

Steps:

1. share a file as favorite
2. share that file to somebody
3. go to `shared by me`
4. go to `shared with me`
5. go to `shared by me`

The result is that the list is not rerendered....

**Comment by rullzer** [comment]
Once https://github.com/nextcloud/server/pull/4293 is in this should be good to go as well... Will rebase after that.

**Comment by MorrisJobke** [comment]
> Once #4293 is in this should be good to go as well... Will rebase after that.

Rebased.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
