### PR TITLE
revise updater.server.url to reflect nextcloud.org URL

### PR DESCRIPTION
**Pull request by rob-mosher**
Please see https://github.com/nextcloud/server/issues/102 for further information.

(meta: including from conversation in above url @LukasReschke )

### CODE REVIEW

**Comment by mar1u5** [comment]
LGTM 😉

**Comment by MorrisJobke** [comment]
👍

**Comment by mar1u5** [comment]
Backport? @karlitschek

**Comment by karlitschek** [comment]
obviously backport 👍

**Comment by hailthemelody** [comment]
I would be happy to backport though I've never done one before. If it's more efficient for someone else to do so that's fine, though I'd like to learn. Any pointers appreciated.

**Comment by mar1u5** [comment]
> I would be happy to backport though I've never done one before. If it's more efficient for someone else to do so that's fine, though I'd like to learn. Any pointers appreciated.

See my quote on your PR in `nextcloud/documentation` 😉 This would be the easiest way for "beginners".

**Pull request merged**
