### PR TITLE
25.0.4

### PR DESCRIPTION
**Pull request by blizzz**
:date: planned for release on Feb  ~~16th~~ 23rd

Pending PRs:

* none

### CODE REVIEW

**Comment by szaimen** [comment]
@blizzz should we fix this before the release as it is basically a regression new in 25.0.4?
https://github.com/nextcloud/server/issues/36676

**Comment by blizzz** [comment]
> @blizzz should we fix this before the release as it is basically a regression new in 25.0.4?
> #36676

Do we have a fix with which we can create an  RC2 on short term?

**Comment by szaimen** [comment]
> Do we have a fix with which we can create an RC2 on short term?

I dont have had the time to look into this. Lets hope @Pytal does this evening.

**Comment by blizzz** [comment]
> > Do we have a fix with which we can create an RC2 on short term?
> 
> I dont have had the time to look into this. Lets hope @Pytal does this evening.

Othwerwise i would not consider it critical enough to move the release.

**Review by AndyScherzinger — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by blizzz** [comment]
> > > Do we have a fix with which we can create an RC2 on short term?
> > 
> > 
> > I dont have had the time to look into this. Lets hope @Pytal does this evening.
> 
> Otherwise i would not consider it critical enough to move the release.

@szaimen I saw stuff was merged on master in the vue lib, but that's already about it. We should comminucate it, I guess, but will leave it for 25.0.5.

**Comment by stondino00** [comment]
When will 25.0.4 be released?  Thanks

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule says tomorrow

**Pull request merged**
