### PR TITLE
Update Nc Vue to 8.4.0

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Bump Nc Vue to 8.4.0 
https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.4.0

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
@JuliaKirschenheuter you need to update the snapshots when updating nextcloud-vue.
Should work with `npm run test -- --updateSnapshot` or something like this

**Comment by JuliaKirschenheuter** [comment]
Thank you @susnux!

Unfortunately i've got 50 failed tests ;( what should i do to fix it?

**Comment by para28711** [comment]
Stephen f Balogh

**Comment by ShGKme** [comment]
To update snapshots:
```sh
npm run test:coverage -- -u
# same as
npm run test:coverage -- --updateSnapshot
```

`--` here is used to pass options/arguments not to `npm run` command, but to the command it runs (`jest --coverage`).

Or fast version to skip coverage - directly run Jest:
```sh
npx jest -u
```

> Unfortunately i've got 50 failed tests ;( what should i do to fix it?

It happens when there are additional apps in `app` directory, e.g. `activity`, `photos`, `text`, `viewer`. Jest doesn't respect `.gitignore` and runs tests and `__mocks__` from extra apps.

**Pull request merged**
