### PR TITLE
Remove md5 from main bundle

### PR DESCRIPTION
**Pull request by rullzer**
:broom:

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by ChristophWurst — APPROVED** [review]
🪶🪶🪶

**Comment by ChristophWurst** [comment]
```
Chrome Headless 88.0.4298.0 (Linux x86_64): Executed 815 of 815 (8 FAILED) (18.007 secs / 17.814 secs)
TOTAL: 8 FAILED, 807 SUCCESS


1) adds file when size is below limits
     OC.Upload tests Adding files for upload
     ReferenceError: md5 is not defined
    at new OC.FileUpload (apps/files/js/file-upload.js:42:2)
    at HTMLInputElement.add (apps/files/js/file-upload.js:926:19)
    at apps/files/tests/js/fileUploadSpec.js:75:37
    at Function.Mt (core/js/dist/main.js:1:172646)

2) adds file when free space is unknown
     OC.Upload tests Adding files for upload
     ReferenceError: md5 is not defined
    at new OC.FileUpload (apps/files/js/file-upload.js:42:2)
    at HTMLInputElement.add (apps/files/js/file-upload.js:926:19)
    at apps/files/tests/js/fileUploadSpec.js:75:37
    at Function.Mt (core/js/dist/main.js:1:172646)

3) does not add file if it exceeds free space
     OC.Upload tests Adding files for upload
     ReferenceError: md5 is not defined
    at new OC.FileUpload (apps/files/js/file-upload.js:42:2)
    at HTMLInputElement.add (apps/files/js/file-upload.js:926:19)
    at apps/files/tests/js/fileUploadSpec.js:75:37
    at Function.Mt (core/js/dist/main.js:1:172646)

4) does not show conflict dialog when no client side conflict
     OC.Upload tests Upload conflicts
     ReferenceError: md5 is not defined
    at new OC.FileUpload (apps/files/js/file-upload.js:42:2)
    at HTMLInputElement.add (apps/files/js/file-upload.js:926:19)
    at apps/files/tests/js/fileUploadSpec.js:75:37
    at Function.Mt (core/js/dist/main.js:1:172646)

5) shows conflict dialog when no client side conflict
     OC.Upload tests Upload conflicts
     ReferenceError: md5 is not defined
    at new OC.FileUpload (apps/files/js/file-upload.js:42:2)
    at HTMLInputElement.add (apps/files/js/file-upload.js:926:19)
    at apps/files/tests/js/fileUploadSpec.js:75:37
    at Function.Mt (core/js/dist/main.js:1:172646)

6) cancels upload when skipping file in conflict mode
     OC.Upload tests Upload conflicts
     ReferenceError: md5 is not defined
    at new OC.FileUpload (apps/files/js/file-upload.js:42:2)
    at HTMLInputElement.add (apps/files/js/file-upload.js:926:19)
    at apps/files/tests/js/fileUploadSpec.js:75:37
    at Function.Mt (core/js/dist/main.js:1:172646)

7) overwrites file when choosing replace in conflict mode
     OC.Upload tests Upload conflicts
     ReferenceError: md5 is not defined
    at new OC.FileUpload (apps/files/js/file-upload.js:42:2)
    at HTMLInputElement.add (apps/files/js/file-upload.js:926:19)
    at apps/files/tests/js/fileUploadSpec.js:75:37
    at Function.Mt (core/js/dist/main.js:1:172646)

8) autorenames file when choosing replace in conflict mode
     OC.Upload tests Upload conflicts
     ReferenceError: md5 is not defined
    at new OC.FileUpload (apps/files/js/file-upload.js:42:2)
    at HTMLInputElement.add (apps/files/js/file-upload.js:926:19)
    at apps/files/tests/js/fileUploadSpec.js:75:37
    at Function.Mt (core/js/dist/main.js:1:172646)
```

have fun

**Comment by rullzer** [comment]
shit....

**Comment by rullzer** [comment]
yeah so we can only do this if we move the file stuff to vue... so for another time...

**Pull request closed without merging**
