### PR TITLE
Set umask before operations that create local files

### PR DESCRIPTION
**Pull request by icewind1991**
this solves issues where "other php stuff" is messing with the umask

### CODE REVIEW

**Comment by PVince81** [comment]
does this fix any known issue ?
could this have side effects ?

**Comment by rullzer** [comment]
What is the status here?

**Comment by icewind1991** [comment]
This should be good for review now.

This solves a case where some unknown external "thing" was messing with the umask, causing files and folders created by nextcloud to not be writable

**Comment by PVince81** [comment]
using this PR to retest CI after https://github.com/nextcloud/docker-ci/pull/274
curious to see if https://github.com/nextcloud/server/pull/26265 was really necessary

**Review by PVince81 — APPROVED** [review]
:+1: code looks fine

**Review by rullzer — APPROVED** [review]

**Comment by PVince81** [comment]
seems this has some side effect: https://github.com/nextcloud/server/issues/29041

**Comment by bgottschall** [comment]
This merge is quite unfortunate for the Unraid community, which uses the umask for Nextcloud to change the default permissions of files and folders created since they are working with docker mounts that require the group permissions to have write access.

You probably don't care about such scenarios where Nextcloud is working together with smb shares, but in any case I consider setting fixed permissions inside the PHP code as bad practice. I would very much like to see a configuration parameter here to change them.

**Comment by tatankat** [comment]
The issues mentioned should be fixed by fixing the "other php stuff" (whatever it may be...), as they are the cause of the problem. Not by hiding the real issues by forcefully changing a carefully admin-selected sensible umask in Nextcloud, which breaks stuff and makes Nextcloud part of the issue.
As @bgottschall, I consider this bad practice, but I think a configuration parameter is not really required as it can already be configured server wide.

**Pull request merged**
