### PR TITLE
Handle badly named version files more gracefully and log information

### LINKED ISSUE #34085: [Bug]: NC 25 Error: Undefined array key "extension" at /var/www/nextcloud/apps/files_versions/lib/Storage.php#489
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I was trying to delete alot of files and folders at once

### Steps to reproduce

1.Go into a group folder with alot of times
2. Delete the files and folder errors out but deletes 
3.

### Expected behavior

Should delete with no errors

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
NA
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
{"reqId":"lNyX2jZtca5uPedBAk5D","level":3,"time":"2022-09-14T16:38:00+00:00","remoteAddr":"10.99.0.65","user":"admin","app":"PHP","method":"DELETE","url":"/remote.php/dav/files/axheli/IT%20Share/KeePass","message":"Undefined array key \"extension\" at /var/www/nextcloud/apps/files_versions/lib/Storage.php#489","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"25.0.0.11","exception":{"Exception":"Error","Message":"Undefined array key \"extension\" at /var/www/nextcloud/apps/files_versions/lib/Storage.php#489","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":489,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":273,"function":"getVersions","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Hooks.php","line":71,"function":"delete","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":106,"function":"remove_hook","class":"OCA\\Files_Versions\\Hooks","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1284,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1212,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":349,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":305,"function":"rmdir","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"632203e06c6e9"}

{"reqId":"lNyX2jZtca5uPedBAk5D","level":3,"time":"2022-09-14T16:38:00+00:00","remoteAddr":"10.99.0.65","user":"admin","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/axheli/IT%20Share/KeePass","message":"Unsupported operand types: int - string","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"25.0.0.11","exception":{"Exception":"TypeError","Message":"Unsupported operand types: int - string","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":493,"function":"getHumanReadableTimestamp","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":273,"function":"getVersions","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Hooks.php","line":71,"function":"delete","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":106,"function":"remove_hook","class":"OCA\\Files_Versions\\Hooks","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1284,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1212,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":349,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":305,"function":"rmdir","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","Line":573,"message":"Unsupported operand types: int - string","exception":[],"CustomMessage":"Unsupported operand types: int - string"},"id":"632203e06c5d4"}
```

### Additional info

https://user-images.githubusercontent.com/59488153/190214133-de0a77e4-6c0e-4efb-9804-7f6df7d3033c.mp4

### PR DESCRIPTION
**Pull request by come-nc**
Fix https://github.com/nextcloud/server/issues/34085

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by PVince81** [comment]
@come-nc can you add an example file name ? (ideal would be in unit tests if possible)

any explanation why this is happening at all ? does PHP parse extensions differently in some versions ?

**Comment by blizzz** [comment]
master is 26 :eyes:

**Comment by come-nc** [comment]
> @come-nc can you add an example file name ? (ideal would be in unit tests if possible)
> 
> any explanation why this is happening at all ? does PHP parse extensions differently in some versions ?

To my knowledge this can only happen if there is a file in files_version with an incorrect name, but it’s better to log that correctly. See the linked issue.

PHP does not parse extension differently, but trying to access $array['undefinedkey'] was a silent error before PHP 8 if I recall correctly.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by come-nc** [comment]
CI failure unrelated

**Comment by come-nc** [comment]
Tagging this `do not merge` until I understand the actual source of the problem, might as well fix the real issue.

**Comment by come-nc** [comment]
> Tagging this `do not merge` until I understand the actual source of the problem, might as well fix the real issue.

Ok, I am reopening this for merging.
It appears the original ticket is caused by bad behavior of groupfolders application.
This should help have a better understanding of the error in such cases.

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Pull request merged**
