### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by rakekniven**

### CODE REVIEW

**Comment by rakekniven** [comment]
Have not found any test so I think the merge should be without any problem.

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@rakekniven Next time also add the sign-off message to your commit and the tests even get green ;) 
https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by rakekniven** [comment]
@MorrisJobke I am using the webinterface of GitHub to contribute my l10n changes.
The web UI does not allow me to sign my commits. Already discussed this with passman people.

**Comment by MorrisJobke** [comment]
> @MorrisJobke I am using the webinterface of GitHub to contribute my l10n changes.
> The web UI does not allow me to sign my commits. Already discussed this with passman people.

It's not signing, but adding a sign-off message 😉 

```
Signed-off-by: Random J Developer <random@developer.example.org>
```

Just add this to your commit message and the sign-off is done. It's basically that you checked that the code is yours and compatible with AGPL 3+ or any work that you copied from somewhere is released under a license that is compatible ;)

**Pull request merged**
