### PR TITLE
Files external settings polish

### PR DESCRIPTION
**Pull request by icewind1991**
The missing commits from #787

cc @MorrisJobke @schiessle

### CODE REVIEW

**Comment by schiessle** [comment]
Thanks Robin, works great! :+1:

**Comment by schiessle** [comment]
@mar1u5 please make sure to pull this commits over to your backport once it was reviewed

**Comment by mar1u5** [comment]
👍

**Comment by mar1u5** [comment]
As soon as these two commits are in `master`, i will add them to the backport #902 😉

**Comment by LukasReschke** [comment]
Tests do fail, @icewind1991 any idea?

**Comment by icewind1991** [comment]
tests all green

**Comment by mar1u5** [comment]
hc299b

**Pull request merged**
