### PR TITLE
fix: Also filter out undefined entries from the file list

### PR DESCRIPTION
**Pull request by juliusknorr**
Apparently I misread the cypress failure in https://github.com/nextcloud/server/pull/42006 which was actually related. This pr fixes that to also filter out undefined values from the list e.g. when a file was moved to another folder

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
👍 

Also the backport of the fix hasn't been picked up by the bot ye6t

**Review by nfebe — APPROVED** [review]
Cypress green.

**Review by ChristophWurst — APPROVED** [review]

**Comment by juliushaertl** [comment]
Manually backported both in https://github.com/nextcloud/server/pull/42023

**Review by miaulalala — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Pull request merged**
