### PR TITLE
fix(a11y): Aria-hide contacts menu icon images

### LINKED ISSUE #42708: [BITV]: Replace entries of action menu for contacts inside of contacts menu
Currently there are entries with images and text. This images are `` without any alternative text.

Screenshot from 2024-01-11 14-17-30

Images are not important in this part and we can replace them with `NcActionText`, like:

```
<NcActionText>
<template #icon>
	<Icon :size="20" />
</template>
{{ t('...', 'local time') }}
</NcActionText>						
```

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Resolves: https://github.com/nextcloud/server/issues/42708

## Summary

Add aria-hidden to the decorative image icons of the contacts menu.

I do not have the means to verify the accessibility of the icon after the change. Accessibility experts, please give this a test.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Antreesy — APPROVED** [review]
I'm not much into the a11y details :see_no_evil: 
But change looks good to me and aligned with issue discussion

**Review by JuliaKirschenheuter — APPROVED** [review]
works, thanks!

**Comment by JuliaKirschenheuter** [comment]
/backport 5198c1ce2b577535547e606ea82bdfdb9c6092c8 to stable28

**Pull request merged**
