### PR TITLE
make sure that we only update the email address if it really changed

### PR DESCRIPTION
**Pull request by schiessle**
this should fix what @MorrisJobke mentioned here https://github.com/nextcloud/server/pull/2468#issuecomment-264478485

@MorrisJobke please test and review... Thanks!

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Nevertheless the checkmark is always in the "Display name" section (even if the correct element in the dom is used, it somehow is moved to that section).

@schiessle Could you have a look at this too?

**Comment by schiessle** [comment]
> Nevertheless the checkmark is always in the "Display name" section (even if the correct element in the dom is used, it somehow is moved to that section).

Known bug, https://github.com/nextcloud/server/issues/2326
@ChristophWurst already assigned it to himself.

**Comment by schiessle** [comment]
second review... @nickvergessen @blizzz,...

**Comment by nickvergessen** [comment]
How can this be tested without ldap?

**Comment by MorrisJobke** [comment]
> How can this be tested without ldap?

Set the config.php switch ;)

**Comment by MorrisJobke** [comment]
> Set the config.php switch ;)

`allow_user_to_change_display_name`;)

**Comment by schiessle** [comment]
> How can this be tested without ldap?

As the description says, the if-statement should only be triggered if the email address really changed. The problem was in case there was never a email address set. Then `$user->getEMailAddress();` returns null but in the webform it will be a empty string.

So you can test it this way:

* take a user with no email address set.
* change something else in the personal settings (e.g. the twitter handle)
* step through the function with the debugger and check that we detect correctly that the email didn't changed and don't execute the code in the if statement.

**Comment by nickvergessen** [comment]
Anyway, works 👍

**Pull request merged**
