### PR TITLE
Return quota even if user is not initialised

### LINKED ISSUE #7212: Quota missing in "get user" API request after update
When having user created from Nextcloud web interface a response from API request

`curl --http1.1 -u myuser:mypass -X GET 'https://myhost.com/ocs/v1.php/cloud/users/myuser' -H "OCS-APIRequest: true"`

contains

```
<quota>
   <free>53687091200</free>
   <used>0</used>
   <total>53687091200</total>
   <relative>0</relative>
   <quota>53687091200</quota>
</quota>
```

However, if I create an user with CLI 

`curl --http1.1 -u myuser:mypass -X POST 'https://myhost.com/ocs/v1.php/cloud/users' -d 'userid=myuser1&password=somePwd!1' -H "OCS-APIRequest: true"`

and update quota

`curl --http1.1 -u myuser:mypass -X PUT 'https://myhost.com/ocs/v1.php/cloud/users/myuser1' -d 'key=quota&value=10GB' -H "OCS-APIRequest: true"`

Then quota in the response when retrieving user is 

```
<quota/>
```
 
It is being changed if viewed with web interface, though.

I have tried this with v2.php API as well.

### PR DESCRIPTION
**Pull request by skjnldsv**
Needed by https://github.com/nextcloud/server/pull/8824
fix #7212

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Seems to fix #7212

**Comment by skjnldsv** [comment]
> Seems to fix #7212

Awesome!! It's exactly that :) :tada:

**Comment by MorrisJobke** [comment]
* [ ] It says `<quota></quota>` instead of `<quota>-3</quota>` for unlimited for me :/
* [ ] querying your new API endpoint `ocs/v2.php/cloud/users/details` results in this:

```xml
<?xml version="1.0"?>
<ocs>
	<meta>
		<status>failure</status>
		<statuscode>998</statuscode>
		<message>The requested user could not be found</message>
	</meta>
	<data/>
</ocs>
```

**Comment by skjnldsv** [comment]
> querying your new API endpoint ocs/v2.php/cloud/users/details results in this:

This is not rebased :)

**Comment by skjnldsv** [comment]
Bump! :)

**Comment by skjnldsv** [comment]
Bump! :)

Test OK :anchor:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by blizzz — APPROVED** [review]
looks good

**Pull request merged**
