### PR TITLE
Highlight selected file version (Nextcloud Office)

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
After my PR #32492 fail, I create a new PR.

Signed-off-by: Jérôme Herbinet <jerome.herbinet@arawa.fr>

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by PVince81** [comment]
I assume that accessibility has been taken into consideration in the former PR's review

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by Jerome-Herbinet** [comment]
Is the fact that some checks are not successful related to my work or should I not worry?

**Comment by szaimen** [comment]
@Jerome-Herbinet do you mind rebasing and fixing the conflicts? Thanks a lot! :)

**Comment by szaimen** [comment]
CI failure unrleated

**Pull request merged**
