### PR TITLE
[stable23] fix showing of all apps are up-to-date in apps management

### PR DESCRIPTION
**Pull request by szaimen**
Manual backport of https://github.com/nextcloud/server/pull/32114

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks Greta but can we please first discuss the initial PR in https://github.com/nextcloud/server/pull/32114#pullrequestreview-951656301? :)

**Comment by szaimen** [comment]
⚠️ Please don't merge until https://github.com/nextcloud/server/pull/32114 is not merged!

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
samba failure unrelated

**Pull request merged**
