### PR TITLE
changes sessions and devices section order

### LINKED ISSUE #27: Settings: sessions and devices sections should be sorted below language and sync apps
Because it’s less important than the language and sync settings, and otherwise it messes up the whitespace in the layout as seen here:
capture du 2016-06-08 16-28-27

cc @schiessle @ChristophWurst

### PR DESCRIPTION
**Pull request by vincchan**
fixes #27

@jancborchardt please review

### CODE REVIEW

**Comment by jancborchardt** [comment]
@vincchan nice one! :+1: 

cc @ChristophWurst you could backport this to ownCloud if you like since you work on that feature. ;)

**Comment by LukasReschke** [comment]
> cc @ChristophWurst you could backport this to ownCloud if you like since you work on that feature. ;)

Not possible since the contributions here do not fall under the CLA.

**Comment by ChristophWurst** [comment]
I was faster hehe https://github.com/owncloud/core/commit/663459ca26d371731e0bc6409f746ebd7bac11ef

**Comment by jancborchardt** [comment]
:D nice @ChristophWurst – ok so @vincchan in that case we should just wait for the downstream with Christoph’s changes. Closing this PR hence. :)

**Pull request closed without merging**
