### PR TITLE
fix warnings when updating app password

### PR DESCRIPTION
**Pull request by icewind1991**
Left over from the plans of enabling-disabling apps

cc @MorrisJobke @rullzer

### CODE REVIEW

**Comment by rullzer** [comment]
Tests are failing

**Comment by icewind1991** [comment]
fixed tests

**Comment by MorrisJobke** [comment]
Failed test is unrelated

**Comment by rullzer** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Tested and fixes the issue 👍

**Pull request merged**
