### PR TITLE
Don't allow the user to set fields they can't see

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by schiessle — APPROVED** [review]
looks good to me

**Comment by blizzz** [comment]
the same issue exists in settings/Controller/UserController

**Comment by nickvergessen** [comment]
Done @blizzz

**Comment by blizzz** [comment]
@nickvergessen thx, works!

**Review by blizzz — APPROVED** [review]

**Comment by schiessle** [comment]
@nickvergessen seems like you need to adjust some tests...

**Comment by MorrisJobke** [comment]
> @nickvergessen seems like you need to adjust some tests...

Ping

**Comment by nickvergessen** [comment]
Yeah morris, sorry there was a long weekend in german, will fix now.

**Comment by MorrisJobke** [comment]
Failing tests (autoloader) fixed in another PR already.

**Comment by MorrisJobke** [comment]
Let me backport this.

**Comment by skjnldsv** [comment]
Hey everyone!
Any reason we're forbidding the editing of email with this?
I think it should be more clear. The name of the config is `allow_user_to_change_display_name` it never mention email :)

Also, it now prevent admin to edit those fields if they're the current user, I think we should always let the admin edit those fields then. Thoughts? cc @rullzer

**Comment by nickvergessen** [comment]
> The name of the config is allow_user_to_change_display_name it never mention email :)

Yeah well, this is one of the stories with a long history even on OC already.

> Also, it now prevent admin to edit those fields if they're the current user, I think we should always let the admin edit those fields then. 

fine by me

**Pull request merged**
