### PR TITLE
Make OCP\Security stricter

### PR DESCRIPTION
**Pull request by rullzer**
* Add typehints
* Add return types
* Opcode opts from phpstorm
* Made strict

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by juliusknorr — DISMISSED** [review]

**Comment by juliushaertl** [comment]
@rullzer Tests are failing:

```
1) Test\Security\HasherTest::testVerify with data set #0 (null, 'asf32äà$$a.|3', false)
TypeError: Argument 1 passed to OC\Security\Hasher::verify() must be of the type string, null given, called in /drone/src/github.com/nextcloud/server/tests/lib/Security/HasherTest.php on line 115
/drone/src/github.com/nextcloud/server/lib/private/Security/Hasher.php:147
/drone/src/github.com/nextcloud/server/tests/lib/Security/HasherTest.php:115

2) Test\Security\HasherTest::testVerify with data set #1 (null, false, false)
TypeError: Argument 1 passed to OC\Security\Hasher::verify() must be of the type string, null given, called in /drone/src/github.com/nextcloud/server/tests/lib/Security/HasherTest.php on line 115
/drone/src/github.com/nextcloud/server/lib/private/Security/Hasher.php:147
/drone/src/github.com/nextcloud/server/tests/lib/Security/HasherTest.php:115
```

**Comment by MorrisJobke** [comment]
ref #7392

**Comment by rullzer** [comment]
Test should be fixed :)

**Comment by MorrisJobke** [comment]
Waiting for https://drone.nextcloud.com/nextcloud/server/4129

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
