### PR TITLE
Do not empty config.php file if reading failed for any reason

### LINKED ISSUE #18620: complete config reset with filled disk
### Steps to reproduce
1. Fill entire available diskspace
2. Visit instance landingpage (might need to repeat this step a couple of times, not sure if instantly reproducible)

### Expected behaviour
Config should never be reset, even in edgecases.
Config should never ever be opened with write-permission from a public / non-admin endpoint. 

### Actual behaviour
Find your `config/config.php` truncated to a minimal config file with only the `instanceid` key filled in. This is serious.

Landing page says something like  "Looks like you're trying to reinstall nextcloud but file CAN_INSTALL was not found"

### Server configuration

**Operating system:** debian 9

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated since NC 15

**Where did you install Nextcloud from:** source tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - apporder: 0.8.0
  - audioplayer: 2.8.4
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - deck: 0.7.0
  - encryption: 2.5.0
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_linkeditor: 1.0.11
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.6.0
  - files_readmemd: 1.1.3
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_videoplayer: 1.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - polls: 0.10.4
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.2
  - survey_client: 1.5.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"",
            "***REMOVED SENSITIVE VALUE***"",
            "***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "loglevel": 2,
        "maintenance": false,
        "default_language": "de",
        "theme": "",
        "updater.release.channel": "stable",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "mysql.utf8mb4": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** latest firefox

**Operating system:** linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
At the point of config-reset, nothing is logged. Beforehand, redis complains about unavailable storage
</details>

### PR DESCRIPTION
**Pull request by come-nc**
Fixes https://github.com/nextcloud/server/issues/18620

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by szaimen** [comment]
Seens like the tests work now? :)

**Comment by come-nc** [comment]
> Seens like the tests work now? :)

Yes :smile:

**Review by szaimen — APPROVED** [review]

**Comment by szaimen** [comment]
@come-nc can you please link the issues that get fixed by this? Thanks! :)

**Comment by come-nc** [comment]
Fixes https://github.com/nextcloud/server/issues/18620

**Review by solracsf — APPROVED** [review]
🥳

**Comment by solracsf** [comment]
@come-nc should also fix https://github.com/nextcloud/server/issues/25175 https://github.com/nextcloud/server/issues/18620 or it doesn't cover these cases?

**Comment by come-nc** [comment]
> @come-nc should also fix #25175 or it doesn't cover these cases?

No it does not fix this one. It fixes cases where reading failed, not the ones where writing fails.
Maybe replacing ftruncate by opening the file in write mode would solve those? Not sure.

**Comment by andrey-utkin** [comment]
>  Maybe replacing ftruncate by opening the file in write mode would solve those? Not sure.

No. Create new + rename would solve this, as suggested [1](https://github.com/nextcloud/server/issues/18620#issuecomment-1153596155), [2](https://github.com/nextcloud/server/issues/25175#issuecomment-891275926)

I'm just following the issue, would get my hands on it but you seem to be almost done :)

**Comment by andrey-utkin** [comment]
I've created thiat PR to demonstrate the atomic update approach. To be continued.

**Pull request merged**
