### PR TITLE
fix(cypress): Fix selector for the user menu button

### PR DESCRIPTION
**Pull request by susnux**
## Summary

Adjusted the selector for the user menu toggle (upper right menu containing the logout button).

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
Wouldn't the old selector have worked as well? Anyway, fine with the change :)

**Comment by susnux** [comment]
> Wouldn't the old selector have worked as well? Anyway, fine with the change :)

No because it selected more than one button (when writing those tests it worked but now somehow a second button is there??).
So this simply selects only the direct child-button which is the menu toggle.

**Comment by susnux** [comment]
Cypress unrelated:
```
  │ ✖  theming/admin-settings.cy.ts             01:58       42       40        2        -        - │
  ```

**Comment by szaimen** [comment]
> No because it selected more than one button (when writing those tests it worked but now somehow a second button is there??).
> So this simply selects only the direct child-button which is the menu toggle.

Ah I see. That makes sense

**Pull request merged**
