### PR TITLE
Pass the proper share permissions to the create share call

### LINKED ISSUE #21188: Re-Sharing of readonly files not working
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. User A shares a  file/folder to user B with Re-Sharing permission, but without write/edit/create/delete  permission (readonly)
2. User B tries to re-share this File with user C
3. Error Message "Fehler beim Erstellen der Freigabe"

### Expected behaviour
File should be shared to user C (readonly)

### Actual behaviour
Error Message "Fehler beim Erstellen der Freigabe" in GUI

HTTP Answer: {"ocs":{"meta":{"status":"failure","statuscode":404,"message":"Kann die Berechtigungen von file nicht erhöhen"},"data":[]}}

### further information
Getting the FileInfo Object in JS Console, I got permission 27 (read/write/del/share) for the shared folder and sharePermission 17 (read/share).  The XHR API request contains no permission: "{"path":"/Folder","shareType":0,"shareWith":"_test01"}". It is using the defaults set in admin panel (shareapi_default_permissions). if this is set to create/edit/delete on, the error will occour.

If changing this default (no checkmarks set, shareapi_default_permissions to 1), the re-sharing is working again.

### Server configuration

**Operating system:** Debian 10
**Web server:** Apache, php-fpm
**Database:** MariaDB
**PHP version:** 7.2
**Nextcloud version:** 18.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated
**Where did you install Nextcloud from:** nextcloud.com
**Signing status:** disabled

**List of activated apps:**
<details>
<summary>App list</summary>
 ```
 - accessibility: 1.4.0
  - activity: 2.11.0
  - announcementcenter: 3.7.0
  - apporder: 0.10.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - circles: 0.18.5
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.1
  - drop_account: 0.2.1
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.4.1
  - files_downloadactivity: 1.7.0
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - gpxedit: 0.0.13
  - guests: 1.4.6
  - impersonate: 1.5.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - notes: 3.4.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - photos: 1.0.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - quotaadmin: 0.0.2
  - recommendations: 0.6.0
  - richdocuments: 3.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - spreed: 8.0.9
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "installed": true,
        "default_language": "de",
        "updatechecker": true,
        "has_internet_connection": true,
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "appstoreenabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/data\/nextcloud_skel",
        "theme": "tui",
        "activity_expire_days": 14,
        "integrity.check.disabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "knowledgebaseenabled": false,
        "defaultapp": "apporder",
        "sharing.minSearchStringLength": 4,
        "sharing.maxAutocompleteResults": 5,
        "maintenance": false,
        "debug": false,
        "htaccess.RewriteBase": "\/",
        "proxy": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "updater.release.channel": "stable",
        "lookup_server": "",
        "app_install_overwrite": [
            "files_upload_mtime",
            "quotaadmin",
            "drop_account"
        ],
        "preview_max_x": 800,
        "preview_max_y": 800,
        "preview_max_scale_factor": 1,
        "tempdirectory": "\/data\/tmp\/nextcloud"
    }
}
```

</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 76.0.1
**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
no log entries
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
no log entries
</details>

#### Browser log
<details>
<summary>Browser log</summary>

JS Konsole:
Error while creating share Error: "Request failed with status code 404"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
ShareRequests.js:61:12
</details>

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #21188

This way we do not run into the share permission issue

To test:

1. user0 shares a folder with read and share permissions to user1
2. user1 tries to share the folder to user2

before: :boom: 
now: 🌈

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
🙈

**Review by GretaD — APPROVED** [review]

**Pull request merged**
