### PR TITLE
Fix sticky header on users list

### LINKED ISSUE #11541: User table header
### Steps to reproduce
1. Go to the user section
2. Scroll down

### Expected behaviour
I would like to see the table header even if I scroll through a lot of users.

### Actual behaviour
After scrolling down one page I don't see the header anymore

### Server configuration

**Operating system**:CentOS

**Web server:** NginX

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #11541 
capture d ecran_2018-10-03_12-10-02

@XjeEDK @nextcloud/designers

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I wonder if it would look better if there were a little border on the bottom of the header :thinking:

**Comment by MorrisJobke** [comment]
> I wonder if it would look better if there were a little border on the bottom of the header 🤔

Thought the same 👍

**Review by MorrisJobke — APPROVED** [review]
Fixes the issue with the sticky header. 👍 Bonus points for a border at the bottom of the header.

**Comment by pixelipo** [comment]
Yeah, this definitely needs the bottom border.

However, I don't much like having two sticky lines. Makes more sense for the actual header to be sticky then for the "add user" form. Perhaps we could make the latter non-sticky and make the `#new-user-button` into a `<a href="/#newuser">` to always jump back to it wherever we are down the list?

**Comment by skjnldsv** [comment]
@pixelipo the new user header is only here if you click the new user button :)
So you can toggle it.
Most common case is only the header ;)

**Review by weeman1337 — APPROVED** [review]
✓

**Review by MorrisJobke — APPROVED** [review]
Looks so much better 👍

**Comment by MorrisJobke** [comment]
@skjnldsv Could you back port this small change as well?

**Review by jancborchardt — APPROVED** [review]
Looking good!

**Comment by MorrisJobke** [comment]
> @skjnldsv Could you back port this small change as well?

#11608

**Pull request merged**
