### PR TITLE
Add FilePath as a rule criteria

### LINKED ISSUE #19810: Flow check for containing directory
For user flows it would be very useful to add a check that can verify if a file event was performed on a file inside of a given directory.

Basically what we have shown in the [mockups of the preannouncement](https://nextcloud.com/blog/nextcloud-flow-makes-it-easy-to-automate-actions-and-workflows/):

image

@blizzz I guess this only makes sense for user scope? I don't remember exactly how those were implemented, if we assume a flow operation is triggered on file change, will the flow be executed only for file changes by the user who has configured or also if someone else changes a shared file that is owned by the user?

### PR DESCRIPTION
**Pull request by martin-rueegg**
May Fix #19810

Signed-off-by: Martin Rüegg <martin.rueegg@metaworx.ch>

This patch allows to create a rule based on the file path.

See #22976 for more details. I hope to get more attention by the devs by creating a PR.

### CODE REVIEW

**Comment by skjnldsv** [comment]
see https://github.com/nextcloud/server/pull/23451

**Comment by juliushaertl** [comment]
The main issue i have with the file path based rules is that this will not work properly with shares and might break as soon as the user renames a file or folder in the in the path. cc @blizzz @jancborchardt Since we discussed this during the flow hackweek iirc.

**Comment by blizzz** [comment]
> The main issue i have with the file path based rules is that this will not work properly with shares and might break as soon as the user renames a file or folder in the in the path. cc @blizzz @jancborchardt Since we discussed this during the flow hackweek iirc.

Exactly. And especially since share recipients can move the files and folders around, not effecting the owner's directory structure. That's why using tags is recommended. This even works with  subfolders, e.g. 

- 📁 tagged "Foobar"
  - 📁 (not tagged)
     - 📁 file "Barfoo" thrown into

The file upload of Barfoo then will apply to rules that have "Systemtag is Foobar"  as constraint.

**Comment by martin-rueegg** [comment]
Sorry guys for my late reply - I was on sick leave.

Yes, I have managed to get the thing working by adding a tag to the containing folder and then adjust the flow to use that tag instead. 

Unfortunately, I have not been able to find any documentation about this. There may be more information available at the https://portal.nextcloud.com, which is behind a paywall. Seems that this is now the new strategy of Nextcloud GmbH: open source but closed doc. That will make it harder to contribute in the future. A very sad development for the community ...

**Pull request closed without merging**
