### PR TITLE
App content list fixes

### PR DESCRIPTION
**Pull request by skjnldsv**
Since I'm an idiot, I haven't implemented the proper scrolling of the app list... 🙈 
You can test this with https://github.com/nextcloud/contacts/pull/438 and make two birds with one stone by reviewing both 😝

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Rebased to check if CI runs fine.

**Review by MorrisJobke — APPROVED** [review]
Tested and works - even in Edge and IE11 😉

**Comment by skjnldsv** [comment]
Wait before merging

**Review by rullzer — APPROVED** [review]
Seems to do the trick

**Comment by skjnldsv** [comment]
🙇

**Comment by jancborchardt** [comment]
Good stuff @skjnldsv! :) (Am currently crawling through issues after the week vacation :D)

**Pull request merged**
