### PR TITLE
Fix hardcoded messages in app details view

### LINKED ISSUE #10066: Hardcoded label in Accessibility App details
### Steps to reproduce
1. Navigate to Apps > Click on `Accessibility` app to open Details view

### Expected behaviour
The label should be translated and not hardcoded

### Actual behaviour
output 1

### Server configuration

**Nextcloud version:** 14.0.0 alpha

### PR DESCRIPTION
**Pull request by kevgathuku**
Fixes #10066 
cc @nextcloud/designers

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Some commits were not signed off!
Missing signatures on:
- f4c2a8125818b4cbe33d93298dfe58cda84a6d3c

**Review by juliusknorr — APPROVED** [review]
:+1:

**Comment by rullzer** [comment]
@kevgathuku good catch thnx.
For such small changes I'll just merge it without the sign off but for your next PR (yes I'm expecting more :wink: ) please use the sign-off :)

See https://github.com/nextcloud/server/blob/master/contribute/developer-certificate-of-origin

**Comment by kevgathuku** [comment]
Oops! I'll make sure I don't miss that next time 😉

**Pull request merged**
