### PR TITLE
[stable22] Bump aws/aws-sdk-php from 3.184.6 to 3.208.7

### PR DESCRIPTION
**Pull request by CarlSchwan**
- [x] Merge https://github.com/nextcloud/3rdparty/pull/1005
- [ ] Rebase

I tested locally creating directory, uploading big files and downloading big files with primary and external storage s3 and didn't found any regression.

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Comment by blizzz** [comment]
@CarlSchwan what's the state here?

**Comment by CarlSchwan** [comment]
> @CarlSchwan what's the state here?

Forgotten but I just updated it :)

**Comment by blizzz** [comment]
@CarlSchwan the azure test is failing, not sure whether related, but usually it is not red.

**Comment by solracsf** [comment]
Failure seem related to a deprecated/removed function `GuzzleHttp\Psr7\build_query()`, replace by `GuzzleHttp\Psr7\Query::build()`

Maybe the azure package needs an upgrade too for CI to pass.

**Comment by blizzz** [comment]
moving to 22.2.8

**Comment by blizzz** [comment]
moving to 22.2.9

**Comment by blizzz** [comment]
@CarlSchwan :ping_pong:

**Comment by CarlSchwan** [comment]
New PR in third party https://github.com/nextcloud/3rdparty/pull/1077

**Comment by blizzz** [comment]
> New PR in third party [nextcloud/3rdparty#1077](https://github.com/nextcloud/3rdparty/pull/1077)

this here is about AWS and the linked repo is about Azure?

**Comment by CarlSchwan** [comment]
The aws update updated the guzzle dependency and this means that azure also need a corresponding update

**Comment by nickvergessen** [comment]
Reverting in https://github.com/nextcloud/3rdparty/pull/1078

**Pull request closed without merging**
