### PR TITLE
Use mail for encrypting the password reset token as well

### PR DESCRIPTION
**Pull request by LukasReschke**
This uses the mail address as well as the instance secret for encrypting the password reset token. Causing the following advantages:
1. If a user changes their mail address, old reset tokens do expire.
2. If the entry in the DB leaks one won't be able to decrypt it without also having read access to the  config file.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@LukasReschke What is missing here?

**Comment by rullzer** [comment]
I rebased and fixed the tests

**Comment by LukasReschke** [comment]
THX @rullzer 

LGTM

**Comment by rullzer** [comment]
Almost forgot. :+1: for @LukasReschke stuff.

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
