### PR TITLE
Add quota to the files view

### PR DESCRIPTION
**Pull request by nickvergessen**
> bildschirmfoto vom 2017-06-08 16-04-09

cc @jancborchardt apply beautification 😸

### CODE REVIEW

**Comment by Dennis1993** [comment]
That's a very good idea. I think we can remove the quota overview in the personal settings and move it to the files overview.

My idea is to set it a little bit down and not of the top of the navigation. Here an example. Whats your opinion?

Normal state (free space available)
fullstate

Full state (free space is low)
normalstate

**Comment by MorrisJobke** [comment]
> My idea is to set it a little bit down and not of the top of the navigation. Here an example. Whats your opinion?

That was also our idea to put in down there.

**Comment by MariusBluem** [comment]
> I think we can remove the quota overview in the personal settings

👎 ... You'll get a nice overview there, and we need this bar for the quota-buttons (`apps/external`) 😉

**Comment by Dennis1993** [comment]
@mariusbluem oh okay. I don't know that, I don't use external storage :)

**Comment by jancborchardt** [comment]
There you go:
screenshot from 2017-06-09 15-40-08

- Can we move it to the bottom, above »Deleted files«? Otherwise this really takes too much attention away from the important things. Same for the mobile apps.
- The tooltip with the percentage can have the translation removed in the code. Couldn’t figure out how to do that last part.
- The link needs to be linked to the actual place where it should go. For the normal release, it should go to the personal settings.
- For the core version we should put a switch in which disables the »Do you need more space?« sentence, right?

**Comment by MorrisJobke** [comment]
> Can we move it to the bottom, above »Deleted files«? Otherwise this really takes too much attention away from the important things. Same for the mobile apps.

It is only in the branded apps on the top. :/

**Comment by MorrisJobke** [comment]
> The link needs to be linked to the actual place where it should go. For the normal release, it should go to the personal settings.

Why is it there for the normal version? This should be the "quota" type link from the external sites app and if this is not configured should not show up at all.

**Comment by MorrisJobke** [comment]
> For the core version we should put a switch in which disables the »Do you need more space?« sentence, right?

See comment above

**Comment by jancborchardt** [comment]
Ok, so TL;DR what to change here before we can merge? ;)

**Comment by nickvergessen** [comment]
I will have a look to bring the externals app link into this

**Comment by MariusBluem** [comment]
> I will have a look to bring the externals app link into this

What about simply using the first quota-link? @nickvergessen

**Comment by enoch85** [comment]
Will this PR also recognize the total amount of storage even if a quota isn't set, or will it still say "unlimited"?

**Comment by nickvergessen** [comment]
I removed the "of Unlimited" because I think it's useless, the blue bar however will should the percentage of the total available space

**Comment by nickvergessen** [comment]
So it's like this now:
> dateien_-_nextcloud_-_2017-06-12_10 02 14

I can only move it to the bottom when the box shall be below the deleted files link. Is that okay? @jancborchardt

**Comment by jancborchardt** [comment]
I'd say let's put it last in the list. If we add it to the sticky part on the bottom, it will obscire the list too much on mobile.

**Review by LukasReschke — COMMENTED** [review]
Super cool stuff 🚀

**Comment by MorrisJobke** [comment]
This is needed to put it to the bottom:

```css
position: fixed !important;
bottom: 88px;
width: inherit !important;
background-color: #fff;
border-right: 1px solid #eee;
z-index:1;
```

We also need to update the padding of the last element in the upper menu to have a padding of 44px by default:

```css
.app-files #app-navigation > ul li:nth-last-child(2) {
  margin-bottom: 44px;
}
```

and update the same rule in the trashbin to have `88px` (two menu entries):

```css
.app-files #app-navigation > ul li:nth-last-child(2) {
  margin-bottom: 44px;
}
```

let me update the CSS.

**Comment by MorrisJobke** [comment]
I fixed the CSS and it now looks like this:

bildschirmfoto 2017-06-12 um 17 04 24


:+1: from me now. (putting the DOM element to the bottom as well messes too much with the rest of the layout so I kept it where it is)

**Review by MorrisJobke — APPROVED** [review]

**Review by enoch85 — APPROVED** [review]

**Comment by enoch85** [comment]
This looks great!

**Comment by MorrisJobke** [comment]
@nickvergessen See e95e0fd6dac948611f96cfc031ae1c63ec11b668 for my changes.


@nextcloud/designers please have a look at the design as well.

**Comment by jancborchardt** [comment]
Yup, good modifications Morris! :+1:

**Comment by MorrisJobke** [comment]
> Yup, good modifications Morris! 👍

What do you think about this - without an icon it maybe looks more like info and not like a real menu entry and looks more like the Android version as well:

bildschirmfoto 2017-06-12 um 17 47 57

**Comment by MorrisJobke** [comment]
I like the one without logo more. 😉

**Comment by enoch85** [comment]
Would be cool with a "live" logo though that updated depending on how much is left. Don't know if it's possible?

**Comment by MorrisJobke** [comment]
> Would be cool with a "live" logo though that updated depending on how much is left. Don't know if it's possible?

Cool and what is useful is kind of not the same. I would like to have less distraction than a "cool" logo that updates itself. 

Just my 2 ct

**Comment by enoch85** [comment]
Cool was not the right word maybe... `s/cool/look better/g`

**Comment by MorrisJobke** [comment]
> Cool was not the right word maybe... s/cool/look better/g

The only problem I have with that is:

* duplicate info (the bar already says the same)
* more code to maintain that adds very few value for the user
* harder to interpret for a human than a filled straight line
* more distraction from the actual content (files)

**Comment by nickvergessen** [comment]
Since it is not in the list anymore, I'd prefer without the icon as well

**Comment by MariusBluem** [comment]
Looks more clean without the icon and does not attract attention that much. 👍

**Comment by enoch85** [comment]
I rest my case.

**Comment by LukasReschke** [comment]
Rebased on master for test execution.

**Review by LukasReschke — APPROVED** [review]

**Comment by LukasReschke** [comment]
@MorrisJobke Mind committing your patch for https://github.com/nextcloud/server/pull/5305#issuecomment-307956649?

**Review by MorrisJobke — APPROVED** [review]
Updated the quota bar to not have an icon 👍

**Comment by MariusBluem** [comment]
> Looked better before with the icon, in line with the others. Right now it might even be confused as being info of the Deleted files entry.

The quota bar is something different then the sidebar items (deleted files, ...). It is a static element and not something you should/can click on ;)

**Comment by jancborchardt** [comment]
It absolutely should be possible to click on in the future so you see how the storage is used. Like on iOS or Android where you see which apps / filetypes use most.

**Comment by nickvergessen** [comment]
> It absolutely should be possible to click on in the future so you see how the storage is used. 

Yeah but that is not part of todays story.

Currently 4 people prefer without the icon, and only you prefer with it. Do your thing, or merge. This needs to be merged and backported by friday, please take care of this @jancborchardt if you block this now.

**Comment by jancborchardt** [comment]
I did do it like this and it was overwritten. But sure, do design by voting.

**Comment by MorrisJobke** [comment]
> It absolutely should be possible to click on in the future so you see how the storage is used. Like on iOS or Android where you see which apps / filetypes use most.

But currently on iOS and Android this item also doesn't have an item. So I think this is more in line with that, but as always: we can improve on this if the icon is the better way: sure - we should go for it. Let's see what the users say.

**Comment by MorrisJobke** [comment]
I will take care of the backport.

**Comment by skjnldsv** [comment]
Nice work here! 👍

**Pull request merged**
