### PR TITLE
chore(appframework)!: Drop \OCP\AppFramework\Http\EmptyContentSecurityPolicy::allowInlineScript

### PR DESCRIPTION
**Pull request by ChristophWurst**
## Summary

Deprecated in Nextcloud 10, released 2016-08-25.

## TODO

- [x] https://github.com/nextcloud/richdocuments/issues/2979

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by juliushaertl** [comment]
Tests need some more adjustments:

```

There were 7 errors:

1) Test\AppFramework\Http\ContentSecurityPolicyTest::testGetPolicyScriptAllowInline
Error: Call to undefined method OCP\AppFramework\Http\ContentSecurityPolicy::allowInlineScript()

/drone/src/tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php:74

2) Test\AppFramework\Http\ContentSecurityPolicyTest::testGetPolicyScriptAllowInlineWithDomain
Error: Call to undefined method OCP\AppFramework\Http\ContentSecurityPolicy::allowInlineScript()

/drone/src/tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php:82

3) Test\AppFramework\Http\ContentSecurityPolicyTest::testGetPolicyScriptDisallowInlineAndEval
Error: Call to undefined method OCP\AppFramework\Http\ContentSecurityPolicy::allowInlineScript()

/drone/src/tests/lib/AppFramework/Http/ContentSecurityPolicyTest.php:89

4) Test\AppFramework\Http\ResponseTest::testOverwriteCsp
Error: Call to undefined method OCP\AppFramework\Http\ContentSecurityPolicy::allowInlineScript()

/drone/src/tests/lib/AppFramework/Http/ResponseTest.php:70

5) Test\AppFramework\Http\ResponseTest::testGetCsp
Error: Call to undefined method OCP\AppFramework\Http\ContentSecurityPolicy::allowInlineScript()

/drone/src/tests/lib/AppFramework/Http/ResponseTest.php:80

6) Test\Security\CSP\ContentSecurityPolicyManagerTest::testGetDefaultPolicyWithPolicies
Error: Call to undefined method OCP\AppFramework\Http\ContentSecurityPolicy::allowInlineScript()

/drone/src/tests/lib/Security/CSP/ContentSecurityPolicyManagerTest.php:59

7) Test\Security\CSP\ContentSecurityPolicyManagerTest::testGetDefaultPolicyWithPoliciesViaEvent
Error: Call to undefined method OC\Security\CSP\ContentSecurityPolicy::allowInlineScript()

/drone/src/tests/lib/Security/CSP/ContentSecurityPolicyManagerTest.php:113
```

**Review by juliusknorr — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure related

**Comment by ChristophWurst** [comment]
Which ones @szaimen except the expected fixup and DCO checks?

**Comment by szaimen** [comment]
> Which ones @szaimen except the expected fixup and DCO checks?

yes, I meant these :)

**Pull request merged**
