### PR TITLE
fix database select styling in setup page

### PR DESCRIPTION
**Pull request by icewind1991**
result

### CODE REVIEW

**Comment by icewind1991** [comment]
also removes a dangling space

**Comment by jancborchardt** [comment]
Nice! Can we also get rid of the visible radio circle, so it’s like it was before? The bolding and darker background & text is already sufficient. :)

**Comment by skjnldsv** [comment]
Done
Capture d’écran_2019-03-15_12-02-58

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
* [ ] on hover the text is not bold anymore causing the UI to flicker

Bildschirmfoto 2019-03-15 um 14 31 18
vs 
Bildschirmfoto 2019-03-15 um 14 32 04

**Comment by skjnldsv** [comment]
Done @MorrisJobke

**Comment by MorrisJobke** [comment]
Shouldn't it be bold? But I'm fine with both ways 👍 

cc @jancborchardt

**Review by MorrisJobke — APPROVED** [review]
Works 👍

**Comment by rullzer** [comment]
Lets do this. If it needs to be bold we fix it later. @jancborchardt

**Comment by MorrisJobke** [comment]
I talked with Jan about it and non-bold is fine.

**Pull request merged**
