### PR TITLE
chore: Fix update-psalm-baseline to use correct php version depending on branch

### PR DESCRIPTION
**Pull request by come-nc**
## Summary

~The workflow currently always use 8.1, it should use the same PHP version as the psalm run on the target branch.~
Adding the PHP version to psalm.xml so that the update-baseline workflow is aware of it. Backports will need to adapt the PHP version to the one used in their psalm workflow (the lowest PHP version supported usually).

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
Should add it like in apps, e.g. https://github.com/nextcloud/spreed/blob/main/psalm.xml#L8
So it locally also always runs with the expected php version

**Comment by come-nc** [comment]
> Should add it like in apps, e.g. https://github.com/nextcloud/spreed/blob/main/psalm.xml#L8 So it locally also always runs with the expected php version

Ok, trying this way then, putting 8.1 in master and will change to 8.0 in the backports.

**Review by provokateurin — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Backporting is not going to work, 29 and lower need 8.0 at least.
So let's save 2 CI cycles by backporting it after 29 was fixed...

**Pull request merged**
