### PR TITLE
fix(files): Adjust table header to look like on previous versions

### LINKED ISSUE #4871: Too much focus on the file list headings
This was discussed during the process of developing the heading toggles but must have fallen off. :)
It would be nice if the file list heading goes to the previous style of:
- Being color-text-maxcontrast
- Not being bold

Otherwise the heading overshadows the actual files and folders:
image

cc @marcoambrosini @szaimen – and also @susnux @ShGKme since you were in the discussions of the headings when we did that in person.

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud-libraries/nextcloud-vue/issues/4871
* Part of: https://github.com/nextcloud/server/issues/41450

## Summary
Adjust the files table header to look like on previous versions by changing the text color.
This now aligns with the table header example from the vue components were we already had a design review by @jancborchardt .

### Screenshots
before | after
---|---
Screen Shot 2023-11-24 at 00 26 43|Screen Shot 2023-11-24 at 00 23 49
Screen Shot 2023-11-24 at 00 24 37|Screen Shot 2023-11-24 at 00 24 08

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@JuliaKirschenheuter @susnux is this accessible contrast-wise?

**Comment by susnux** [comment]
> is this accessible contrast-wise?

Yes it is maxcontrast on main background and maxcontrast on background-hover. Both combinations are tests by our CI for accessibility.

**Review by AndyScherzinger — APPROVED** [review]

**Review by artonge — APPROVED** [review]
I assume this is still accessible :)

**Comment by susnux** [comment]
@jancborchardt @nimishavijay  I think this is mainly a design issue, so I would like to wait for your opinion on this.

**Review by nimishavijay — APPROVED** [review]
Yep, looks good! :)

**Pull request merged**
