### PR TITLE
[stable17] Fix axios csrf token update event

### PR DESCRIPTION
**Pull request by ChristophWurst**
Partial backport of https://github.com/nextcloud/server/pull/17404 that allows apps that use the new `@nextcloud/axios` to keep the request token in sync.

I'll try to update Axios for stable17 as well. But it's a bigger/riskier change, thus left it out of this manual backport.

To test this PR you can run _nc_event_bus.emit('csrf-token-update', {token: 123}) and observe that OC.requestToken updates.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
mmm webpack is not happy

**Comment by skjnldsv** [comment]
Same issue! you need npm ci.

@ChristophWurst shall we use npm i in the tests instead?

**Pull request merged**
