### PR TITLE
Move encrypt-all password email to EmailTemplate

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps

1. Install nextcloud
2. Configure an email address for the user
3. Enable encryption app `occ app:enable encryption`
4. Disable master key `occ encryption:disable-master-key` (confirm with y)
5. Enable encryption `occ encryption:enable`
6. Disable master key again to be sure `occ encryption:disable-master-key` (confirm with y)
7. Run encrypt all `occ encryption:encrypt-all`
    i. Do you really want to continue? (confirm with y)
    ii. Do you want to send the passwords directly to the users by mail? (confirm with y)

Before | Before | After
---|---|---
Regression from https://github.com/nextcloud/server/pull/10898 <br> grafik | with fixed logo path <br> grafik | grafik

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
Either this PR needs to be backported or:
```diff
diff --git a/apps/encryption/templates/mail.php b/apps/encryption/templates/mail.php
index 0db4b67d08d..545d080b1d3 100644
--- a/apps/encryption/templates/mail.php
+++ b/apps/encryption/templates/mail.php
@@ -7,7 +7,7 @@
 			<table cellspacing="0" cellpadding="0" border="0" width="600px">
 				<tr>
 					<td colspan="2" bgcolor="<?php p($theme->getColorPrimary());?>">
-						<img src="<?php p(\OC::$server->getURLGenerator()->getAbsoluteURL(image_path('core', 'logo-mail.png'))); ?>" alt="<?php p($theme->getName()); ?>"/>
+						<img src="<?php p(\OC::$server->getURLGenerator()->getAbsoluteURL(image_path('core', 'logo/logo-mail.png'))); ?>" alt="<?php p($theme->getName()); ?>"/>
 					</td>
 				</tr>
 				<tr><td colspan="2">&nbsp;</td></tr>
```

To prevent the exception from the first "Before" screenshot.

I would vote for backporting this PR here to 26 after 26.0.0 is out (string freeze) and backporting the above diff to all other versions.

**Review by kesselb — APPROVED** [review]
Cool :sunglasses: 

image

**Review by marcoambrosini — APPROVED** [review]

**Comment by joshtrichards** [comment]
Also fixes #35808 (but not for NC25 as-is until https://github.com/nextcloud/server/pull/36351#issuecomment-1460034829 gets created in a separate PR).

**Comment by nickvergessen** [comment]
Feel free to send it as a Pull Request

**Pull request merged**
