### PR TITLE
Reduce app container border radius

### PR DESCRIPTION
**Pull request by marcoambrosini**
Screenshot 2024-04-11 at 10 23 56

### CODE REVIEW

**Comment by marcoambrosini** [comment]
/ compile amend/

**Comment by marcoambrosini** [comment]
/ compile/

**Review by emoral435 — COMMENTED** [review]
Will hard-coding introduce any new regressions for designs around the server? If there is a specific spot that we want to handle, should we not change the radius there instead? I am just curious for the reason, if its something that the designers have decided then I am fine with this :)

**Review by jancborchardt — COMMENTED** [review]
@marcoambrosini what @emoral435 is saying though is that setting it to 12px only here is a bit strange. Do we never use 12px as radius anywhere else? Shouldn’t it be using a variable, maybe even just 3*default-grid-baseline?

**Review by emoral435 — APPROVED** [review]
Much nicer :) Thank you!

**Review by jancborchardt — APPROVED** [review]
Looks good! :)

**Comment by jancborchardt** [comment]
@nimishavijay @susnux @artonge do you have any further feedback? Otherwise let’s get this in while we are still early in the cycle. :)

**Review by susnux — APPROVED** [review]
code looks good, if this was discussed by the design team then :+1:

**Pull request merged**
