### PR TITLE
Don't show 'Personal' header in settings when Admin section is not there

### PR DESCRIPTION
**Pull request by jancborchardt**
For regular users we don’t need to show the "Personal" heading because there’s no other headings anyway. For admins nothing changes.
Personal settings before settings after

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
sure

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@jancborchardt Mind to rebase on current master, because there were quite some fixes merged lately.

**Comment by rullzer** [comment]
This breaks the acceptance tests that checks for the personal header :P

**Comment by jancborchardt** [comment]
Rebased on master, but the test is not so easy to fix, as if we would change the:

> Then I see that the "Personal" settings panel is shown

it wouldn’t test for the entire section? So it should check for the content instead of the heading. (FYI I’m on vacation and it’s out of my abilities, so I’m happy for someone to take over. :)

**Comment by MorrisJobke** [comment]
> it wouldn’t test for the entire section? So it should check for the content instead of the heading. (FYI I’m on vacation and it’s out of my abilities, so I’m happy for someone to take over. :)

I adjusted and fixed them 👍

**Review by MorrisJobke — APPROVED** [review]
Looks nice 👍

**Comment by MorrisJobke** [comment]
Let's get this into 16 as it is just a small fix

**Comment by MorrisJobke** [comment]
Completely unrelated failure. I haven't seen this before.

**Pull request merged**
