### PR TITLE
30.0.0 RC2

### PR DESCRIPTION
**Pull request by skjnldsv**
* #47229
* #47255
* #47260
* #47264
* #47276
* #47283
* #47292
* #47295
* #47305
* #47309
* #47322
* #47333
* #47338
* #47355
* #47362
* #47364
* #47374
* #47382
* #47385
* #47389
* #47390
* #47391
* #47392
* #47393
* #47395
* #47401
* nextcloud/activity#1746
* nextcloud/circles#1670
* nextcloud/files_pdfviewer#1013
* nextcloud/files_pdfviewer#1019
* nextcloud/firstrunwizard#1308
* nextcloud/firstrunwizard#1313
* nextcloud/firstrunwizard#1314
* nextcloud/firstrunwizard#1321
* nextcloud/logreader#1340
* nextcloud/notifications#2006
* nextcloud/notifications#2010
* nextcloud/notifications#2014
* nextcloud/recommendations#782
* nextcloud/serverinfo#668
* nextcloud/suspicious_login#903
* nextcloud/suspicious_login#907
* nextcloud/suspicious_login#913
* nextcloud/text#6212
* nextcloud/text#6216
* nextcloud/text#6229
* nextcloud/text#6231
* nextcloud/text#6232
* nextcloud/text#6233
* nextcloud/text#6234
* nextcloud/text#6241
* nextcloud/twofactor_totp#1551
* nextcloud/twofactor_totp#1553
* nextcloud/viewer#2434

## Pending PRs:
* @Abijeet
  * [ ] nextcloud/logreader#476
* @adriano-pinaffo
  * [x] nextcloud/photos#1834
* @akhil1508
  * [ ] nextcloud/activity#1635
* @ArtificialOwl
  * [ ] nextcloud/circles#1089
  * [ ] nextcloud/circles#1090
  * [ ] nextcloud/circles#1148
  * [ ] nextcloud/circles#1214
  * [ ] nextcloud/circles#1217
  * [ ] nextcloud/circles#1394
  * [ ] nextcloud/circles#891
  * [ ] nextcloud/circles#980
* @backportbot
  * [ ] #47249
  * [x] #47387
  * [ ] #47398
* @danxuliu
  * [ ] nextcloud/files_pdfviewer#654
* @fgsl
  * [ ] nextcloud/circles#226
  * [ ] nextcloud/circles#229
* @grnd-alt
  * [ ] nextcloud/text#5690
* @icewind1991
  * [ ] #46639
  * [x] nextcloud/text#6243
* @Jerome-Herbinet
  * [ ] nextcloud/circles#1422
* @joshtrichards
  * [ ] nextcloud/suspicious_login#875
  * [ ] nextcloud/updater#571
* @LakshayaTohan
  * [ ] nextcloud/logreader#857
* @madmas
  * [ ] nextcloud/activity#460
* @makoehr
  * [ ] nextcloud/updater#471
* @onny
  * [ ] nextcloud/circles#1349
* @ostasevych
  * [ ] nextcloud/files_pdfviewer#938
  * [ ] nextcloud/files_pdfviewer#939
* @rotdrop
  * [ ] nextcloud/circles#1297
* @ShGKme
  * [ ] nextcloud/viewer#1711
* @solracsf
  * [ ] nextcloud/activity#1700
* @sualko
  * [ ] nextcloud/recommendations#458
* @susnux
  * [ ] nextcloud/logreader#1041
  * [ ] nextcloud/photos#2312
* @tortuetorche
  * [ ] nextcloud/circles#392
  * [ ] nextcloud/circles#395
  * [ ] nextcloud/circles#398
  * [ ] nextcloud/circles#399
  * [ ] nextcloud/circles#400
  * [ ] nextcloud/circles#401
* (generated)
  * [ ] nextcloud/activity#1683
  * [ ] nextcloud/activity#1717
  * [ ] https://github.com/nextcloud/server/pull/47219 (ready to merge)

### CODE REVIEW

**Comment by susnux** [comment]
Would be good to include https://github.com/nextcloud/server/pull/47249 as there is a later migration for the same table already back ported :see_no_evil:

**Review by ChristophWurst — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by skjnldsv** [comment]
> Would be good to include #47249 as there is a later migration for the same table already back ported 🙈

Address Joas's comment and we can get it in before release :+1:

**Comment by susnux** [comment]
> Address Joas's comment and we can get it in before release 👍

It is already merged like that in master, not sure if it makes more sense to fix master and backport that annotation later.
(Especially as I currently have no clue what that is doing due to lack of documentation)
But also other migrations for 30 have already been backported without annotations, so maybe as said do that as a follow up for RC3?

**Pull request merged**
