### PR TITLE
Make the bootstrap context return ContainerInterface instances

### PR DESCRIPTION
**Pull request by ChristophWurst**
Let me quickly fine-tune my new API before it becomes stable :grimacing: 

Bildschirmfoto von 2020-07-16 17-06-55

### CODE REVIEW

**Comment by ChristophWurst** [comment]
You can review the two commits separately

1) Change the API
2) Adjust the apps

**Comment by MorrisJobke** [comment]
With #21891 some PHPDoc isn't needed anymore. I will adjust this tomorrow.

**Comment by MorrisJobke** [comment]
I fixed now also the failing unit tests for the BootContext

**Review by MorrisJobke — APPROVED** [review]
Looks good and works for me 👍

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
> ### Status of [30959](https://drone.nextcloud.com/nextcloud/server/30959): failure
> #### mysql5.6-php7.2

Nice!
Only one!

**Pull request merged**
