### PR TITLE
Only allow admins to delete tags

### PR DESCRIPTION
**Pull request by nickvergessen**
Step 5 of #1465

@MorrisJobke @rullzer @ChristophWurst 

Btw morris or christoph, can one of you fix the form and the label (admin only now). It seems somewhat cut off and the tooltip is behind it as well.
> bildschirmfoto vom 2016-12-05 16-55-01

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Btw morris or christoph, can one of you fix the form and the label (admin only now). It seems somewhat cut off and the tooltip is behind it as well.

cc @nextcloud/designers - maybe @skjnldsv want to look into this

**Comment by LukasReschke** [comment]
@MorrisJobke CI runs amok again – can you check?

**Comment by MorrisJobke** [comment]
> @MorrisJobke CI runs amok again – can you check?

Yes - tests are failing because of changed behaviour. *not-my-business*

**Comment by LukasReschke** [comment]
@MorrisJobke Thou shall click through all links:

https://drone.nextcloud.com/nextcloud/server/2689/37

**Comment by LukasReschke** [comment]
```
+ git init
0s
2
Initialized empty Git repository in /drone/src/github.com/nextcloud/server/.git/
0s
3
+ git remote add origin https://github.com/nextcloud/server.git
0s
4
+ git fetch --no-tags --depth=1 origin +refs/pull/2512/merge:
0s
5
From https://github.com/nextcloud/server
6s
6
 * branch            refs/pull/2512/merge -> FETCH_HEAD
6s
7
+ git checkout -qf FETCH_HEAD
6s
8
+ git submodule update --init --recursive
6s
9
Submodule '3rdparty' (https://github.com/nextcloud/3rdparty.git) registered for path '3rdparty'
6s
10
Cloning into '/drone/src/github.com/nextcloud/server/3rdparty'...
6s
11
fatal: write error: No space left on device
7s
12
fatal: index-pack failed
7s
13
fatal: clone of 'https://github.com/nextcloud/3rdparty.git' into submodule path '/drone/src/github.com/nextcloud/server/3rdparty' failed
7s
14
exit status 128
```

**Comment by icewind1991** [comment]
> Btw morris or christoph, can one of you fix the form and the label (admin only now). It seems somewhat cut off and the tooltip is behind it as well.

https://github.com/nextcloud/server/pull/2515

**Comment by MorrisJobke** [comment]
> @MorrisJobke Thou shall click through all links:

Fixed, but the tests are still broken ;)

**Comment by nickvergessen** [comment]
Updated the test

**Comment by MorrisJobke** [comment]
```
1) OCA\DAV\Tests\unit\SystemTag\SystemTagNodeTest::testDeleteTag with data set #1 (false)
Sabre\DAV\Exception\Forbidden: No permission to delete tag 1
/drone/src/github.com/nextcloud/server/apps/dav/lib/SystemTag/SystemTagNode.php:164
/drone/src/github.com/nextcloud/server/apps/dav/tests/unit/SystemTag/SystemTagNodeTest.php:256
```

**Comment by nickvergessen** [comment]
Fixed, then JS was failing, also fixed now. /me hopes for 💚

**Comment by LukasReschke** [comment]
@nickvergessen  Can we move that to 12? I'd prefer to consider 11 closed for any non-critical merges.

**Comment by nickvergessen** [comment]
Well since the same issue exist since 9 already I guess we can

**Comment by LukasReschke** [comment]
I'm not a huge fan of this, that said, I'm not even a huge fan of the tagging at all because it is so confusing that everybody can create a tag but now only admins can delete etc…

**Comment by nickvergessen** [comment]
Well the idea is to not list tags in the dropdown, a user does not have applied to any files himself. In which case "deleting" would mean its not assigned to anything they see.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍 

```
$.ajax('/remote.php/dav/systemtags/2', {'method': 'DELETE'});
```

This should fail for a normal user :wink:

**Review by rullzer — APPROVED** [review]
Fine by me.

**Pull request merged**
