### PR TITLE
do not lower case search provider names on web ui

### LINKED ISSUE #25282: Search provider names in unified search hint do not respect localized language rules
Fits:

Screenshot_20210122_182232

Should be capitalised:

Screenshot_20210122_182352

It is not a translation issue. The search providers only have to provide a `getName()` method for a translated string. The provides all return it in capitalized fashion ("Apps", …). In `core/src/views/UnifiedSearch.vue:47` they are hard-lowercased. 

The best distinction is done by the translators however. 

My suggestion would be to add another method (as another interface to avoid breakage) that would return a string to be used within a sentence. And fall back to `getName()`. The hard lowercasing in the view would be removed.

The alternative would be to only remove the forced lower cased, which would end up in a strange picture at least in English:

Screenshot_20210122_183238

@ChristophWurst @skjnldsv @jancborchardt   what do you think?

### PR DESCRIPTION
**Pull request by blizzz**
fixes #25282

### CODE REVIEW

**Comment by nickvergessen** [comment]
you didn't build production, right?

**Review by ChristophWurst — APPROVED** [review]

**Comment by blizzz** [comment]
> you didn't build production, right?

oops

**Review by rullzer — APPROVED** [review]
Fine by me but I think this was there for a reason

**Comment by nickvergessen** [comment]
> Fine by me but I think this was there for a reason

It was there to be correct in English. The current way this string is build is just not conforming with our translation system. But due to the lack of other ideas... (So it actually comes from the rule that in English we uppercase the first word always, because 'Talk', 'Files', and the other search provider names should actually not be uppercase to begin with.)

**Pull request merged**
