### PR TITLE
Allow to force enable apps via CLI

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Check out master of server
2. Check out stable17 of activity app
3. Try to enable it via CLI, to fix it for master :boom: 

The UI had the red button to force enable it. This is now possible via:
`occ app:enable activity --force`

cc @jancborchardt should help you a lot

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by kesselb** [comment]
`TypeError: Argument 2 passed to OC\App\AppManager::__construct() must implement interface OCP\IConfig, instance of Mock_AppConfig_4eb7dda7 given, called in /drone/src/tests/lib/App/AppManagerTest.php on line 114 `

Nice to have: A test case for `tests/Core/Command/Apps/AppsEnableTest.php` but a incompatible fake app might be required.

**Comment by ChristophWurst** [comment]
rebased, squashed and tests fixed :)

**Review by georgehrke — APPROVED** [review]
🐘

**Review by skjnldsv — APPROVED** [review]

**Comment by blizzz** [comment]
> TypeError: Argument 2 passed to OC\App\AppManager::__construct() must implement interface OCP\IConfig, instance of Mock_AppConfig_5b004e91 given, called in /drone/src/tests/lib/AppTest.php on line 556

**Pull request merged**
