### PR TITLE
use in objectstore copy

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
Is this copy actually called when you do a COPY on webdav?

**Comment by icewind1991** [comment]
> Is this copy actually called when you do a COPY on webdav?

[yes](https://github.com/nextcloud/server/blob/fedf9c69d9c84fc0399badef39ed765de72c08f1/apps/dav/lib/Connector/Sabre/ObjectTree.php#L231)

**Comment by icewind1991** [comment]
> > Is this copy actually called when you do a COPY on webdav?
> 
> [yes](https://github.com/nextcloud/server/blob/fedf9c69d9c84fc0399badef39ed765de72c08f1/apps/dav/lib/Connector/Sabre/ObjectTree.php#L231)

Spoke to soon, there are of course other code paths

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/24358 fixes that

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Pull request merged**
