### PR TITLE
Adapt files and app settings to @nc/vue changes

### PR DESCRIPTION
**Pull request by julien-nc**
AppSidebar `primary-actions` slot became `description` in @nc/vue v3.3.0 (https://github.com/nextcloud/nextcloud-vue/pull/1566).
This PR adapts the slot name in templates when this component is used in app settings and in files.

I've noticed it's also used in Calendar app but @nc/vue is still v2.9.0 there.

Let's keep that in mind in case @nc/vue version is bumped in `stable21` :grin:.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
:see_no_evil: 
Thanks :pray:

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by marcoambrosini — APPROVED** [review]

**Comment by rullzer** [comment]
Removed the extra settings files
We can merge once done

**Pull request merged**
