### PR TITLE
fix(files): add title for files list table header button

### PR DESCRIPTION
**Pull request by ShGKme**
In some languages `2 * --height` is not enough to fit some table header button texts. Adding `title`.

I'm not a fun of having `title` all the time, but I don't see a simple alternative.

## Screenshots

🏚️ Before | 🏡 After
---|---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by nickvergessen** [comment]
/backport f7498d0069ea0bed6b18effd1295ac77cdffdfed to stable30

**Comment by nickvergessen** [comment]
/backport f7498d0069ea0bed6b18effd1295ac77cdffdfed to stable29

**Comment by ShGKme** [comment]
/backport https://github.com/nextcloud/server/commit/f7498d0069ea0bed6b18effd1295ac77cdffdfed to stable28

**Pull request merged**
