### PR TITLE
Fix issue #12151: fix list formatting by correcting malformed html

### LINKED ISSUE #12151: Lists in EmailTemplate are incorrectly formatted
### Steps to reproduce
1.  Perform an action that creates a server email containing a list, for example, create a calendar event with an invitee
2.  Notice, in the invitee email, that the html list box is incorrectly formatted (in the source, you see width=100%% with two percent signs).

Note:  listBegin in lib/private/Mail/EMailTemplate.php is used directly, not passed as an argument to vsprintf, so its percent symbols should not be escaped.

### PR DESCRIPTION
**Pull request by brad2014**
Minor html syntax bugs in listBegin corrected. 
Fixes #12151.
Signed-off-by: Brad Rubenstein <brad@wbr.tech>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@brad2014 Thanks for your contribution. Do you mind to create a branch based on `stable14`, cherry pick the commit from here there and create a pull request so that this fix is also back ported to stable14? That would be nice 👍 

Also if you are looking for further small issues have a look at https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by brad2014** [comment]
@MorrisJobke Thanks.  I think I did the branch/pull-request as you like, but I'm new to this, so let me know if I got it wrong.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Thanks. I think I did the branch/pull-request as you like, but I'm new to this, so let me know if I got it wrong.

Looks perfect 👍 💯 You just did your first backport

Backport to stable14 can be found at #12202

**Comment by MorrisJobke** [comment]
@brad2014 I invited you also to the Nextcloud org so you can now push branches in this repo here and then collaboration is even easier. 

JFYI: Also once a backport PR is opened we remove the backport-request label. That makes it easier to spot the pending back ports.

Welcome aboard 🛫

**Pull request merged**
