### PR TITLE
Add app version to sidebar

### LINKED ISSUE #21093: Show app version in sidebar
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When using a small screen (e.g. on a smartphone) and visit the Apps page (https://<your_nextcloud_domain>/settings/apps), I can't see the version of the apps. On a large screen you see two extra columns per app: the 'featured' column and the 'app version' column. They are both removed on smaller screens. I understand this is necessary because of the little space on smaller screens. However when I click on an app, the sidebar does show if the app is featured or not, but it doesn't show the app version.

**Describe the solution you'd like**
Show the app version in the sidebar.

**Additional context**
Knowing the app version is useful, e.g., when you can upgrade to a new version of the app it is nice to see which version you are currently using so you can read up on the changes since your current version.

### PR DESCRIPTION
**Pull request by Brennii96**
Close #21093 

Signed-off-by: Brendan O'Neill <brendan.oneill96@hotmail.co.uk>

### CODE REVIEW

**Review by nimishavijay — COMMENTED** [review]
Sounds great, would love to have before/after screenshots to review the design :)

**Comment by Brennii96** [comment]
Before view (chrome desktop):
image
Before view (chrome mobile):
image

After view (chrome desktop):
image
After view (chrome mobile)
image

**Review by nimishavijay — APPROVED** [review]
Looks good design wise!

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Rebased and compiled

**Review by szaimen — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Looks good!

**Pull request merged**
