### PR TITLE
[WIP] experiment with opening menus on hover

### PR DESCRIPTION
**Pull request by jancborchardt**
Something I wanted to try out, ref https://github.com/owncloud/core/issues/23683. Already trying out this prototype for a bit I’m not sure it’s a good idea. It feels a bit twitchy and stuff opening when you don’t want it to. What do you think @nextcloud/designers @ChristophWurst @MorrisJobke?

What would still need to be done to make it proper:
- [ ] menu needs to stay open
- [ ] should still work on click too, needs to work on mobile
- [ ] file actions menu should do that too, as should the 3-dot menus in the sidebar of apps (Mail)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
- [ ] the menu should automatically close if the mouse leaves the element again after some time (e.g. 300ms)

**Comment by jancborchardt** [comment]
@ChristophWurst what are your general thoughts about it? Does it feel good? I’m not entirely sure but might be because it’s not polished at all yet.

**Comment by icewind1991** [comment]
Feel pretty good but it should have a small delay before opening, moving your mouse from one side of the screen to the other shouldn't trigger a load of menus.

**Comment by ChristophWurst** [comment]
I worked on this already, see https://github.com/owncloud/core/pull/23902. It's doable. The only things missing was to add it to all menus and to close the menu if the mouse leaves the element again.

**Comment by williambargent** [comment]
It's a nice idea not sure how practical it is, I agree with @ChristophWurst they need to stay open for a short period of them after the mouse leaves. The search bar should also expand on hover (might be a nice feature to have regardless).

**Comment by rullzer** [comment]
What is the status here?

**Comment by LukasReschke** [comment]
@jancborchardt Please reopen if still required.

**Comment by jancborchardt** [comment]
Yeah, I also thought about it more and this interaction seems unnecessary and inconsistent. Feel free to reopen the discussion @nextcloud/designers if you really have good arguments why we should have this. :)

**Pull request closed without merging**
