### PR TITLE
Change the comment icon to something more visually appealing

### PR DESCRIPTION
**Pull request by skjnldsv**
| Before | After |
|:---------:|:------:|
|dev skjnldsv com_apps_vueexample_ (2)|dev skjnldsv com_apps_vueexample_ (1)|

@nextcloud/designers

### CODE REVIEW

**Comment by juliushaertl** [comment]
I like it, just a small detail, I would make the arrow go a bit more straight out of the speech bubble: 

From
image
To
image

**Comment by skjnldsv** [comment]
@juliushaertl welcome to the secret PR! :lock: 🔮 🧙‍♀️

**Comment by skjnldsv** [comment]
comment

**Comment by juliushaertl** [comment]
Yes, looks a bit cleaner to me :+1:

**Comment by tcitworld** [comment]
Doesn't this icon means more "chat" than "comment" ? I feel like there's going to be a mixup in the sidebar between the talk app tab and the comment tab.

**Comment by skjnldsv** [comment]
@tcitworld talk icon is actually more close to the one we have than the one I'm suggesting: :wink: 

| Talk | New | Old |
|:---------:|:------:|:------:|
|dev skjnldsv com_apps_vueexample_|dev skjnldsv com_apps_vueexample_ (1)|dev skjnldsv com_apps_vueexample_ (2)|

**Review by MorrisJobke — APPROVED** [review]
I like it 👍

**Review by ChristophWurst — APPROVED** [review]
Fine by me

**Comment by skjnldsv** [comment]
Failure unrelated, sqlite-php7.3 fails on other tests randomly sometimes (other sqlite passes :thinking: )

And I don't see how an icon would break this test ^^

**Comment by jancborchardt** [comment]
@skjnldsv am a bit late to the party, but really good change! Especially that it looks more different than the Talk icon.

Hopefully Comments are merged into Activity soon though *wink* *wink* ;D

**Pull request merged**
