### PR TITLE
[stable10] Shake the login fields if password is wrong

### PR DESCRIPTION
**Pull request by MariusBluem**
Backport of #695 

cc @MorrisJobke @ChristophWurst

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@karlitschek I guess this port to stable10 is okay? ;)

**Comment by MorrisJobke** [comment]
I tested it and it works :+1: (cherry pick was done right)

**Comment by karlitschek** [comment]
nice. please backport :-)

**Comment by MorrisJobke** [comment]
@ChristophWurst @LukasReschke Please review

**Comment by jancborchardt** [comment]
Nice, 👍

**Pull request merged**
