### PR TITLE
fix(caldav): Add sharee to address list when calendar is shared 

### LINKED ISSUE #26668: Send invitations for shared calendars
Ref: https://github.com/nextcloud/server/pull/15676

It's not possible (anymore) to send invitations for an event for shared calendars. This behavior is confusing for end users.

> 
> Allowing sharees to send invitation in shared calendars was a mistake back then, there are many unresolved topics, especially if the sharee is also an attendee of the event:
> 
> - when editing, does the sharee edit for themselves or on behalf of the calendar owner?
> - when deleting, is the sharee declining the event for themselves or cancelling it for everyone?
> - ...
>
> The CalDAV standard does not have answers to these problems yet. Until then, we should not allow sharees to send invitations in shared calendars.

https://sabre.io/dav/caldav-sharing/ mentions 
- https://tools.ietf.org/html/draft-pot-webdav-resource-sharing-04 
- https://tools.ietf.org/html/draft-pot-caldav-sharing-00

Unfortunately there is no final RFC how shared calendars should work. Yet the drafts could be a starting point. draft-pot-caldav-sharing-00 describes those open issues:

   1.  DAV:owner requirement for scheduling.  I think this is
       problematic...

   2.  I don't think we should allow sharees that have access to an
       invite for which they are the attendee for, via the organizers
       shared calendar, to allow them to make attendee-related changes.
       The entire collection should operate as if the operation is on
       behalf of the organizer.

We don't implement https://github.com/sabre-io/dav/blob/master/lib/CalDAV/Backend/SharingSupport.php interface yet. That might be something to start with. There is already some logic connected to the above interface in sabre that might be useful.

The example implementation https://github.com/sabre-io/dav/blob/c1afdc77a95efea6ee40c03c45f57c3c0c80ec22/lib/CalDAV/Backend/PDO.php#L1308-L1465 uses a database table [calendarinstances](https://github.com/sabre-io/dav/blob/c1afdc77a95efea6ee40c03c45f57c3c0c80ec22/examples/sql/mysql.calendars.sql#L23-L41) that looks similar to `oc_calendars` and `oc_dav_shares`. For example `calendarcolor` is something we store with the calendar. But for a shared calendar the color is something a user may change. So this needs to go to `oc_dav_shares` (calendarinstance in the sabre example).

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #26668 

## Summary
Sabre invitation plugin skip invites if the organizer of the event is not the owner of the calendar. That happens for shared calendars because \OCA\DAV\CalDAV\Calendar::getOwner overwrites \Sabre\CalDAV\Calendar::getOwner. Upstream returns the principaluri of the owner, we return the principaluri of the sharee.
Want to test if this revives the invites in shared calendars. Adjustments for other places that use the getOwner method might be required.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Setting to draft because we have to test this locally before it's integrated. We do not want to experiment with this on production instances

**Comment by SebastianKrupinski** [comment]
> Setting to draft because we have to test this locally before it's integrated. We do not want to experiment with this on production instances

Agreed.

**Comment by kesselb** [comment]
## Test scenario 

- Calendar "A-Team"
- Owned by Alice
- Shared editable with Bob, readonly with Jane
- Reoccurring event created by Alice (Weekly, Mo, 9am, start date in the future - no invitations for events in the past)
- Attendees are Alice, Bob, Jane, John, veronica@mail.internal, kevin@mail.internal, mandy@mail.internal

### Case 1

Steps:
1. Alice: Create event and add Bob and veronica@mail.internal
2. Alice: Edit event and add Jane and kevin@mail.internal
3. Bob: Edit event and add John and mandy@mail.internal

Expected outcome: 
- [x] Alice can invite internal and external attendees 
- [x] and the invitations are sent by email

- [x] Bob sees the event two times (1x in the personal calendar because he is also an attendee, 1x in the shared calendar)
- [x] Bob can invite internal and external attendees to the event in the shared calendar
- [ ] and the invitations are sent by email

- [x] Internal users see the event in the calendar
- [x] Users can accept/decline the event
- [x] The status is updated properly for every user with a local account (note, it's important to accept the invitation for the right event - the copy in your personal calendar, if you accept the event in shared calendar the status for the copy in your personal calendar does not change until the next update from the event organizer)

- [x] External users receive an invitation by email
- [x] and can use the provided link to accept/decline

### Case 2

Steps:
1. Bob: Create event and add John and mandy@mail.internal
2. Bob: Edit event and add Jane and kevin@mail.internal

Expected outcome: 
- [x] Bob sees the event one time (the one in the shared calendar, there is no copy in bob's personal calendar)
- [x] Bob can invite internal and external attendees to the event in the shared calendar
- [x] and the invitations are sent by email

- [x] Jane sees the event two times (1x in the personal calendar because he is also an attendee, 1x in the shared calendar)
- [ ] Jane cannot edit the event in the shared calendar

- [x] Internal users see the event in the calendar
- [ ] Users can accept/decline the event
- [ ] The status is updated properly for every user with a local account (the reply sent to bob does not trigger a status update because the event is not found at https://github.com/nextcloud/3rdparty/blob/cbcfacd52639b3201dd2cf507da3d440ea3344fe/sabre/dav/lib/CalDAV/Schedule/Plugin.php#L492)

- [x] External users receive an invitation by email
- [ ] and can use the provided link to accept/declinee

**Comment by SebastianKrupinski** [comment]
> ## Summary
> 
> Sabre invitation plugin skip invites if the organizer of the event is not the owner of the calendar. That happens for shared calendars because \OCA\DAV\CalDAV\Calendar::getOwner overwrites \Sabre\CalDAV\Calendar::getOwner. Upstream returns the principaluri of the owner, we return the principaluri of the sharee. Want to test if this revives the invites in shared calendars. Adjustments for other places that use the getOwner method might be required.

Disregard... Initial comment...

The better solution is to supply both the Sharer and Sharee addresses to the iTipBroker... This keeps the calendar owner logic sounds and in tacked and fixes the reason the iTipBroker does not generate proper messages when a Sharee creates an event with attendees in the Sharers calendar.

**Comment by SebastianKrupinski** [comment]
Additional thoughts...

Some front end UI changes that would be beneficial...

* Drop down on attendee tab to selected the organizer of the event. Use cases...
- Sharee is an assistant with access to the Managers calendar (Sharer)... The organizer of the event should be the Sharer.
- Sharee is a employee with access to the Company calendar (Sharer)... The organizer of the event should be the Sharee.

Some back end changes that would be beneficial...

* Additional calendar property to control access to send on behalf of the Sharer.

Draw backs...
* The above features would only work in the NC UI. CalDAV dose support the "CALDAV:schedule-send"  ACL permission but I doubt that there are many if any clients that actually support this feature.

**Comment by SebastianKrupinski** [comment]
Testing Instructions:

1. Pull Patch
2. Create invite as an Sharee (User B) on a shared calendar (from User A) with attendees (User C). 
3. Check email of User C to see if invitation arrived.
4. Repeat step 2 and 3 by creating invite in personal calendar with attendees

**Comment by SebastianKrupinski** [comment]
Testing Instructions:

1. Pull Patch
2. Create invite as an Sharee (User B) on a shared calendar (from User A) with attendees (User C). 
3. Check email of User C to see if invitation arrived.
4. Repeat step 2 and 3 by creating invite in personal calendar with attendees

**Comment by ChristophWurst** [comment]
@SebastianKrupinski as discussed, this is a critical change. We will not send this into production without a good test coverage.
1. Tests that cover the old invitation workflows
2. Tests that cover the new invitation workflows

**Comment by SebastianKrupinski** [comment]
@ChristophWurst yes I am working on the tests, wasn't planning on merging this without them, just wanted some reviews on the subject.

**Comment by SebastianKrupinski** [comment]
Notes: Testing Current Shared Calendar Behavior
Configuration: User 2 (Sharer/Owner), User 1 (Sharee), User 3 (Non-Sharee), User External (Mail Address)

Case 1 Test:
User 2 (Owner) Creates event with all other users

Case 1 Outcome:
User 2 (Owner) - SEEs event in shared calendar and receives NO email 
User 1 (Sharee) - SEEs two events, one in personal and one in shared calendar and RECEIVES an email
User 3 (Non-Sharee) - SEEs event in personal calendar and RECEIVES an email
User E (External) - RECEIVES an email


Case 2 Test:
User 1 (Sharee) Creates event with all other users

Case 1 Outcome:
User 1 (Sharee) - SEEs event in shared calendar and receives NO email
User 2 (Owner) - SEEs event in shared calendar and receives NO email
User 3 (Non-Sharee) - Dose NOT see event in personal calendar and receives NO email
User E (External) - receives NO email

**Comment by SebastianKrupinski** [comment]
Notes: Testing New Shared Calendar Behavior
Configuration: User 2 (Sharer/Owner), User 1 (Sharee), User 3 (Non-Sharee), User External (Mail Address)

Case 3 Test:
User 2 (Owner) Creates event with all other users

Case 3 Outcome:
User 2 (Owner) - SEEs event in shared calendar and receives NO email
User 1 (Sharee) - SEEs two events, one in personal and one in shared calendar and RECEIVES an email
User 3 (Non-Sharee) - SEEs event in personal calendar and RECEIVES an email
User E (External) - RECEIVES an email

Case 4 Test:
User 1 (Sharee) Creates event with all other users

Case 4 Outcome:
User 1 (Sharee) - SEEs event in shared calendar and receives NO email
User 2 (Owner) - SEEs two events, one in personal and one in shared calendar and RECEIVES an email
User 3 (Non-Sharee) - SEEs event in personal calendar and RECEIVES an email
User E (External) - RECEIVES an email

**Comment by miaulalala** [comment]
I tried reproducing the 1st use case from Daniel but I can't add an additional attendee from the secondary user Bob with whom the calendar was shared. Am I missing something?

**Comment by SebastianKrupinski** [comment]
> Works, although the following issue might be confusing:
> 
> Admin invites Bob Bob has 2 copies of the VEVENT - one in the shared calendar, one in the personal calendar Bob deletes the VEVENT from the personal calendar Bob accepts the invitiation in the shared calendar The event in the personal calendar is recreated

Pretty sure we would need to rewrite the Sabre iTipBroker class to fix this.

**Review by miaulalala — APPROVED** [review]
Works - mentioned the double ics issue but that's not something essential.

**Review by ChristophWurst — APPROVED** [review]
Tested inviting myself in a calendar shared with me, setting the sharer as organizer

Works :+1:

**Comment by bpmartin20** [comment]
Thank you all, most especially [SebastianKrupinski](https://github.com/SebastianKrupinski), for the dedicated work on this.

I determined my skills at present were insufficient to assist in the testing, but I truly appreciate the work and am anxious to try it out.

**Pull request merged**
