### PR TITLE
Add filecache index on mtime

### PR DESCRIPTION
**Pull request by icewind1991**
Gives searching by mtime and "recent" a proper index to use

Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by rullzer — CHANGES_REQUESTED** [review]
Please make sure to also add it to the main migration files. So for new installations it is set by default.

**Comment by icewind1991** [comment]
@rullzer done

**Review by rullzer — APPROVED** [review]
:tada:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
