### PR TITLE
log class name, ID only is hard to debug

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @LukasReschke @schiessle 

ref owncloud/core#25743

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I tested it and it works 👍

**Comment by LukasReschke** [comment]
LGTM

**Comment by rullzer** [comment]
LGTM!

**Comment by MorrisJobke** [comment]
@karlitschek Backport to stable9 and 10?

**Comment by karlitschek** [comment]
please backport

**Comment by rullzer** [comment]
@MorrisJobke don't forget the backports ;)

**Comment by MorrisJobke** [comment]
> @MorrisJobke don't forget the backports ;)

Done.

**Pull request merged**
