### PR TITLE
Replace custom tooltips with native ones in users page

### LINKED ISSUE #35888: [BITV]: Replace custom tooltips with native one for Users page
## Problem

To show a tooltip on a several components we currently use v-tooltip. An example can be found in https://github.com/nextcloud/server/blob/master/apps/settings/src/components/UserList/UserRow.vue#L96

v-tooltip is not accessible and we want to migrate to native tooltips (title attribute) instead. An overview can be found in https://github.com/nextcloud/nextcloud-vue/issues/2503

## Solution

Add a `title` prop to several components that will render as `title` attribute on the HTML element.

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Signed-off-by: julia.kirschenheuter <julia.kirschenheuter@nextcloud.com>

* Resolves: https://github.com/nextcloud/server/issues/35888

## Summary

Replace custom tooltips with native ones in users page

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
The disappearance of ``dist/icons.css`` raises suspicion

**Comment by ChristophWurst** [comment]
> ## TODO
>    * [ ] Replace custom tooltips with native ones in users page

Check this once it's done.

**Review by Pytal — APPROVED** [review]
Other than the probably unintentional removal of `dist/icons.css`

**Comment by ChristophWurst** [comment]
conflicts

**Pull request merged**
