### PR TITLE
resolve user and groups in nested groups first before filtering the results

### PR DESCRIPTION
**Pull request by blizzz**
Continuation of https://github.com/nextcloud/server/pull/8227

* [x] perhaps unit tests need adjustments
* [x] add integration tests (needs https://github.com/nextcloud/docker-ci/pull/137)

As described by @Cybso in https://github.com/nextcloud/server/pull/8227#issue-167690057, when users were not part directly of a whitelisted group, but of an excluded subgroup, they would wrongly not appear as member of the top group. While the excluded groups should not be used and shown in Nextcloud, their users still qualify to be associated with the top group. Users are only subject to user filter and user base restrictions. 

We have had three places covering the nesting logic aka recursive lookup. I continued @Cybso approach to cover all cases, and consolidating it into one. Plus, integration tests make sure that all desired users are being found :)

### CODE REVIEW

**Comment by blizzz** [comment]
At least some tests fail due to a regression which should be fixed with #14529. Will rebase afterwards.

**Comment by MorrisJobke** [comment]
> At least some tests fail due to a regression which should be fixed with #14529. Will rebase afterwards.

Merged.

**Comment by blizzz** [comment]
failing tests are unrelated

**Review by ChristophWurst — APPROVED** [review]
:elephant:, but :+1: because there are tests :wink:

**Review by rullzer — APPROVED** [review]
Makes sense. And tests so lets :roller_coaster:

**Pull request merged**
