### PR TITLE
[stable12] Use realpath to obtain the webroot

### PR DESCRIPTION
**Pull request by derkostka**
Use realpath to obtain the webroot - backport of #5252 
Signed-off-by: Sebastian Kostka sebastian.kostka@gmail.com

### CODE REVIEW

**Comment by derkostka** [comment]
Please review @MorrisJobke

**Review by MorrisJobke — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@derkostka This commit needs a sign off message as well :wink: 

Little tip for the next time backporting, after creating a new branch from the stable branch you can use `git cherry-pick [commitid]` to apply the commit from the original branch.

**Comment by derkostka** [comment]
Thank you for the hint, i am just getting used to Git / Github.

There is a sign off message ? Is it at the wrong location ?

**Comment by juliushaertl** [comment]
@derkostka Ah I missed that, I guess CI complains because you forgot to wrap your email in < >

**Comment by MorrisJobke** [comment]
> @derkostka Ah I missed that, I guess CI complains because you forgot to wrap your email in < >

Fine anyways ;)

**Pull request merged**
