### PR TITLE
Setup: Databasehost may be an unix-socket

### LINKED ISSUE #35378: In the initial setup, entering an unix-socket returns error
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I tried to use an existing unix- socket (filename) for Database-Host in setup, which usually can be taken as hostname. It returned an error saying the hostname cannot be resolved.

**Describe the solution you'd like**
i'd like to have that working with giving full filenames as usual.

**Describe alternatives you've considered**
It is already possible to use a format localhost:filename, which didn't seem to be self explaining to me as this is not a common annotation and is not mentioned anywhere.

**Additional context**
i already made it work and try to deliver a small push. have fun

### PR DESCRIPTION
**Pull request by obel1x**
Make setup accept unix- sockets without the need to contain ':' in the name.

* Resolves: #35378 

## Summary
Makes it possible to enter fully qualified unix- socket- filenames as Database-Host in setup.

## Checklist
could be better next time... think its intuitive to use and works.

### CODE REVIEW

**Comment by kesselb** [comment]
> It is already possible to use a format localhost:filename, which didn't seem to be self explaining to me as this is not a common annotation and is not mentioned anywhere.

https://github.com/nextcloud/server/blob/cd9f538be98612deba6f082947fe035d0ef57d61/config/config.sample.php#L107-L113

Hi, I agree our documention is a bit vague about it. 
Please add your new syntax to  `config.sample.php`.

**Comment by obel1x** [comment]
> > It is already possible to use a format localhost:filename, which didn't seem to be self explaining to me as this is not a common annotation and is not mentioned anywhere.
> 
> https://github.com/nextcloud/server/blob/cd9f538be98612deba6f082947fe035d0ef57d61/config/config.sample.php#L107-L113
> 
> Hi, I agree our documention is a bit vague about it. Please add your new syntax to `config.sample.php`.

I don't understand. The file already contains that syntax as you can see - it is just not working that way without my change. Thats why i changed it to work like its written there.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by kesselb** [comment]
Hi @obel1x, thanks again for your pull request :+1: 

Could you please
- rebase your branch with the latest changes from master to fix some CI errors: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
- sign off the commit `git rebase HEAD~1 --signoff`, `git push --force-with-lease origin master`

Have a pleasant week :v:

**Comment by obel1x** [comment]
Thank you. i did as you said... after push, there were many differences, so i synced again. Hope now everything is fine

**Comment by kesselb** [comment]
```
Index: lib/private/Setup/AbstractDatabase.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/private/Setup/AbstractDatabase.php b/lib/private/Setup/AbstractDatabase.php
--- a/lib/private/Setup/AbstractDatabase.php	(revision 26eb0e8b7720616e0b30eca98e50abb509f5beb6)
+++ b/lib/private/Setup/AbstractDatabase.php	(date 1671396664081)
@@ -134,9 +134,9 @@
 			}
 			$connectionParams['host'] = $host;
 		} elseif (strpos($this->dbHost, '/') >= 0) {
-		    // Host variable may only be an unix socket.
-            $connectionParams['unix_socket'] = $this->dbHost;
-		    $connectionParams['host'] = 'localhost';
+			// Host variable may only be an unix socket.
+			$connectionParams['unix_socket'] = $this->dbHost;
+			$connectionParams['host'] = 'localhost';
 		}
 
 		$connectionParams = array_merge($connectionParams, $configOverwrite);
```

The linter is unhappy. Above patch should fix the linter warnings. 
If you have a local development setup you can also run `composer cs:fix`.

**Comment by obel1x** [comment]
what the hack... sorry eclipse. now better?

**Comment by obel1x** [comment]
ok, sorry, have not rebased anything before. That has not worked as expected. Also the signature is wrong, don't know how to set it right. think i have to read about signing and come back to this later.

**Comment by kesselb** [comment]
@obel1x Thank you :+1: 

It's a bit tricky with forks :confused: 

Your fork seems a bit out of sync. 

I guess it should work to reset your fork to be even with nextcloud/server and apply the patch again: https://github.com/nextcloud/server/commit/3f79a2223502350861d61cbfb5f1a1f526521672.diff

If you prefer I can take your patch and resubmit here.

**Pull request closed without merging**
