### PR TITLE
Fix mapper not properly casting int in oauth2 code

### PR DESCRIPTION
**Pull request by rullzer**
Else this does :boom:

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/97321f64a3be733ffe921bd8e4b47c6047b3d836/apps/oauth2/lib/Db/AccessToken.php#L36

I think we should fix the getter otherwise we have to cast it on every occurrence.

**Comment by nickvergessen** [comment]
Well actually https://github.com/nextcloud/server/blob/5f71805c35d04e585ea6d4227254b11204413dfd/apps/oauth2/lib/Db/AccessToken.php#L49 should do exactly that.

**Comment by nickvergessen** [comment]
So I would fix https://github.com/nextcloud/server/blob/ba87db3fccb40aa58d84d12932424c83a4db411f/lib/public/AppFramework/Db/Entity.php#L126-L128 instead.

**Comment by kesselb** [comment]
Any idea what is broken? If the record is populated from DB the values should be set through the setters. We could migrate to QBMapper.

**Comment by rullzer** [comment]
I have no idea why it does :boom: but it was reported and did :boom: for me on a 16 test with php 7.1 (no xdebug there).

I propose to just get this in and fix it properly later.

**Comment by kesselb** [comment]
Sure. I still vote for a getter in accesstoken and do the type cast there.

**Comment by rullzer** [comment]
Ah sure that is fine as well

**Comment by rullzer** [comment]
Ah. so it was actually because the wront names were used for setting the types :see_no_evil:

**Review by ChristophWurst — APPROVED** [review]
:see_no_evil:

**Review by kesselb — APPROVED** [review]
You found the real mistake :rocket:

**Pull request merged**
