### PR TITLE
handle postgres setup when we cant connect as admin

### LINKED ISSUE #482: PostgreSQL: faulty database connection upon completing installation wizard
Using PostgreSQL the first database connection upon completing the installation wizard ("Finish setup") is faulty both in current master checkouts and 9.0.53.

Both 020a2a6 and 9.0.53 first try to connect to database "postgres" instead of their dedicated one according to the PostgreSQL server's logs. As for the Git checkout this results in failure and a warning
nextcloud_postgres-installation-credentials_020a2a6
In 9.0.5{3,2} the installation wizard of which [still needs the vendor specific "psql" driver](https://github.com/nextcloud/server/issues/367) an attempt to connect to database "postgres" is made as well but it's followed by some other connection attempt and the resulting warning is
nextcloud_postgres-installation-credentials_9 0 52
Unlike the findings with branch master this isn't reproducible 100% but happens most of the time, so far I failed to figure out the exact conditions.
Both times `config.php` is written but incomplete, in particular `dbpassword` and `installed` are missing. The correct dedicated database of Nextcloud is filed in `dbname`, though. 

Arch Linux x86_64, hence PostgreSQL 9.5.3, PHP 7.0.8 and Apache 2.4.23 using the PHP module. Database server on an other host than the one running Apache / Nextcloud, credentials definitely valid as verified by invoking `psql` from the latter.

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/nextcloud/server/issues/482

@pmattern can you check if this fixes the problem for you?

### CODE REVIEW

**Comment by pmattern** [comment]
963c0e8 behaves like the current release as described in #482: First, a connection attempt is made to database "postgres" instead of the one of Nextcloud which obviously fails. Next a connection attempt using correct database and database username is made but fails due to a wrong password besides the one filed in the wizard's form is definitely correct. The error message is
nextcloud_wizard-initial-postgres_963c0e8
Bits from Apache's error log can be found in [this Gist](https://gist.github.com/pmattern/77241992241093c0cecb09f63ed08bb7), `./config/config.php` reads
```
<?php
$CONFIG = array (
  'instanceid' => 'oc1fhm06dego',
  'passwordsalt' => 'wgEOc8qBLhOmTgZfjP/S+nc6JZKCg5',
  'secret' => '05Tv0MrXnv5if3Ue5mfb6faCo0vOmNeXq4cT8gAiCS4qr2f1',
  'trusted_domains' => 
  array (
  0 => '<FQDN>',
  ),
  'datadirectory' => '/var/lib/nextcloud',
  'overwrite.cli.url' => '<FQDN>',
  'dbtype' => 'pgsql',
  'version' => '9.1.0.13',
  'dbname' => 'nextcloud1',
  'dbhost' => '<FQDN>',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'u_nextcloud1',
  'dbpassword' => 'on',
);
```

**Comment by andreas-p** [comment]
Testing with 10 beta, I found the behaviour even more problematic. I've set up a postgres database <dbname> upfront with full access granted to <dbuser>, including a specific pg_hba.conf entry, which should be sufficient for all nextcloud server access patterns.

First, the setup tries to connect using the www-data to the <dbname> database (1xssl, 1x nonssl), then it tries to connect using the <dbuser> to the postgres database. Both is wrong, it obviously should connect to <dbname> using <dbuser>, nothing else (at least as a first attempt).

**Comment by rullzer** [comment]
Moved to NC11 since it is against master

**Comment by LukasReschke** [comment]
@icewind1991 Any comments on above remarks?

**Comment by nebulade** [comment]
Ran into the same issue with our Cloudron app, where the database and db user are already pre-setup. Using that patch only worked by also adding 
```
'dbname' => $this->dbName,
```
to the `$connectionParams` at https://github.com/nextcloud/server/blob/master/lib/private/Setup/AbstractDatabase.php#L111

**Comment by nebulade** [comment]
Most likely `'port' => $this->dbPort,` should also be specified there, if the port is non standard.

**Comment by icewind1991** [comment]
It now sets the dbname explicitly

**Comment by pmattern** [comment]
Running 787f0e5 the error messages shown above and in #482 can no longer be seen. Also, `config.php` seems to be correct, in particular directives `dbpassword` and `installed` are now included.

The first connection attempt is still made to database `postgres` instead of the one filed in the wizard and correctly written in `config.php`, though, as can be seen both in the PostgreSQL server's logs and in `error_log` of Apache.

787f0e5 on Arch Linux x86_64, PostgreSQL 9.5.4, Apache 2.4.23, PHP 7.0.11 via mod_php.

**Comment by MorrisJobke** [comment]
@rullzer Would be nice to get this in - I will try to test this today too ;)

**Comment by MorrisJobke** [comment]
Rebased ontop of master ;)

**Comment by MorrisJobke** [comment]
I tested this and setup via postgres works fine 👍

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen Mind to review this one here?

It's not a huge diff: https://github.com/nextcloud/server/pull/497/files?w=1

**Comment by MorrisJobke** [comment]
@karlitschek We need more people testing postgres or we should kill the support for it. I would vote for only go for one nice solution instead of 4 different ones that only work half of the time 🙈

**Comment by karlitschek** [comment]
hmm. not sure it is realistic to drop support. Maybe we should ask in the forum for more testers?

**Comment by MorrisJobke** [comment]
> hmm. not sure it is realistic to drop support. Maybe we should ask in the forum for more testers?

We are should then check out how to get more traction on the postgres side. Because this is here sind end of July.

But maybe something like the Nginx guys also happen for the postgres support :)

**Review by Threeseven — APPROVED** [review]
Fix the issue for me. I've installed Nextcloud 10.0.1 with non admin postgres user and non standard port.

**Comment by MorrisJobke** [comment]
@Threeseven Thanks for the feedback 👍

**Comment by andreas-p** [comment]
I'd consider dropping postgres support as a major drawback, please drop thinking about it...
This installation issue was quite long-lasting because users usually don't install too often. I have several NC-on-pgsql instances running, and will certainly give feedback on issues.

**Comment by LukasReschke** [comment]
https://github.com/nextcloud/server/issues/1793 is another PGSQL issue that seems rather critical…

**Pull request merged**
