### PR TITLE
Fix strengthify issues

### LINKED ISSUE #105: Nextcloud Very Weak Password Notification
Fresh install nextcloud 

very weak password

UI still said my password very weak, sample of my 'weak password'
```
JAJrHd4B%bKakk*FgUY4d$
```

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #105 
- updates strengthify to latest version 

cc @sentabi  @LukasReschke @blizzz @mar1u5 @mikebabb

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I tested this with Chrome, Firefox, Safari and IE10

**Comment by schiessle** [comment]
tested, works :+1:

**Comment by mar1u5** [comment]
works 😉 👍

**Comment by mar1u5** [comment]
Backport? @karlitschek

**Comment by MorrisJobke** [comment]
> Backport? @karlitschek

This makes sense and I will prepare the backport

**Comment by MorrisJobke** [comment]
> Backport? @karlitschek

#118

**Comment by karlitschek** [comment]
nice. please backport 👍

**Comment by MorrisJobke** [comment]
This is the same stuff as https://github.com/owncloud/core/pull/26360 also tried to fix ;)

**Pull request merged**
