### PR TITLE
fix public view

### LINKED ISSUE #34206: [Bug]: Placeholder in public link share is too small
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

image

This happens on c.nc.c with latest NC25.

### Steps to reproduce

1. share a file via public link
2. open this link

### Expected behavior

Bigger image

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
/
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/34206

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by st3iny — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by juliushaertl** [comment]
This seems to have caused a regression on the public page:

Screenshot 2022-10-03 at 12 09 52

**Comment by szaimen** [comment]
Can you describe in words what the regression is?

**Comment by szaimen** [comment]
Ah, I see

**Comment by szaimen** [comment]
What is strange that it worked in my testing. Do you have the talk app enabled?

**Comment by szaimen** [comment]
Or is this coming frok the text app?

**Comment by juliushaertl** [comment]
Talk is disabled, text is enabled, but also happens on image/folder shares.

Pushed a possible fix for it with https://github.com/nextcloud/server/pull/34396 but I'm unsure about the original reasoning for switching to sticky with this PR. Maybe you can check that.

**Pull request merged**
