### PR TITLE
Fix accessing undefined offsets

### PR DESCRIPTION
**Pull request by CarlSchwan**
Move this to inside the else clause of the count($matches)

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
🙈

**Review by PVince81 — APPROVED** [review]
:+1: as discussed

**Review by skjnldsv — APPROVED** [review]

**Comment by PVince81** [comment]
samba test failed without results

since this PR is connected, I've restarted the build just in case, hoping for the best...

**Comment by CarlSchwan** [comment]
> samba test failed without results
> 
> since this PR is connected, I've restarted the build just in case, hoping for the best...

It indeed looks connected but at the same time it's also broken on master. 😱

Maybe the tests broke with the PR that added this feature?

**Comment by CarlSchwan** [comment]
Let's focus on fixing the tests on https://github.com/nextcloud/server/pull/30796

**Comment by skjnldsv** [comment]
> > samba test failed without results
> > since this PR is connected, I've restarted the build just in case, hoping for the best...
> 
> It indeed looks connected but at the same time it's also broken on master. scream
> 
> Maybe the tests broke with the PR that added this feature?

not connected, this was here after the SMB bump of yesterday, Robin have been notified :)

**Comment by acsfer** [comment]
@skjnldsv my suggestion was discarded :)

**Comment by skjnldsv** [comment]
@acsfer what do you mean?

**Comment by acsfer** [comment]
@skjnldsv see https://github.com/nextcloud/server/blob/29413b9e3a6cfa0421bd9c226e8bb3b0ef97213a/apps/files_external/lib/Lib/Backend/SMB.php#L115 (double `;;` on master and backports...)

**Comment by nickvergessen** [comment]
It works never the less?

**Comment by CarlSchwan** [comment]
> It works never the less?

yeah, it will work. The additional semicolon is just an empty statement, I will submit a PR to fix it in master but there is no need to backport this.

**Comment by acsfer** [comment]
Sure, but merge a PR with this "typo" after it was pointed-out it's a bit, let's say, strange... :)
`(and same thing for the backports)`

**Comment by CarlSchwan** [comment]
I'm not sure where this was pointed out. Did you maybe forgot to submit the comment? I only see your message about your suggestions being discarded but this one after merging this PR.

**Pull request merged**
