### PR TITLE
Bump jcrop from v0.9.12-npm to v0.9.12-npm3

### PR DESCRIPTION
**Pull request by ChristophWurst**
See https://github.com/nextcloud/server/pull/14354#issuecomment-468200789

### CODE REVIEW

**Comment by ChristophWurst** [comment]
(the lib did not change and therefore the bundle remains untouched)

**Comment by ChristophWurst** [comment]
These are the actual changes in the lib: https://github.com/ChristophWurst/Jcrop/compare/v0.9.12-npm...v0.9.12-npm3

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by feelepxyz** [comment]
@ChristophWurst hey sorry for the back and forth! I think it'll get fixed if you remove this submodule folder on 2.0.5 https://github.com/ChristophWurst/Jcrop/tree/cde153499107da550562b7543b8a79f57d7049b3/build/less

**Comment by ChristophWurst** [comment]
That worked :muscle: https://github.com/nextcloud/server/pull/14444

Thank you very much @feelepxyz!

**Comment by ChristophWurst** [comment]
(the error triangle on app.dependabot.com is gone)

**Comment by feelepxyz** [comment]
@ChristophWurst nice one! Thanks for helping reduce our Sentry/error load 💯

**Pull request merged**
