### PR TITLE
feat(trashbin): Show original location of deleted file

### LINKED ISSUE #35611: add directory location column to trashbin
### Why adding a column directory to trashbin is useful
As an owner of a larger installation (150k files, thousands of directories, several clients) and a lot of file movements and similar looking files I would like to get an easy overview of the deleted files in trashbin.

Unfortunately, it is almost impossible to trace where the deleted files come from.

For this it would be best if there was a sortable column that shows the directory 🙏.

Additional comment: same for "view=shareoverview", may for others too.

### LINKED ISSUE #44380: [Bug]: Original Path of deleted Files not shown
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the upgrade from 27 to 28 if you hover with your mouse over an item in the "deleted files" folder it only shows the name of the file and not the original path of the file. The same is in the activity feed. It only shows the file name but not the path where it was deleted.

### Steps to reproduce

1. Delete File
2. go to deleted files folder and hover over an item
3. take a look on the Activity feed

### Expected behavior

Show the path where the file was deleted from

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Pytal**
- Fix https://github.com/nextcloud/server/issues/44380
- Fix https://github.com/nextcloud/server/issues/35611

## Summary

- In versions <27 you could hover over the file to see the original location, see https://github.com/nextcloud/server/issues/40190
- Here a new column is added to show the original location

image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by skjnldsv** [comment]
We should probably work on making a hide/show UI for columns with Nc 30 :see_no_evil:

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
This is not a feature but a regression from 28, so

/backport to stable29

**Pull request merged**
