### PR TITLE
Fix download URL for versions

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Use the webroot in the download URL for versions

The webroot is auto-detected or explicitly set in https://github.com/nextcloud/server/blob/394ad988c7157c0f576b78d591e48e330fe6ca7f/config/config.sample.php#L554-L561

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]
♥️

**Comment by artonge** [comment]
CI failure look unrelated, merging

**Pull request merged**
