### PR TITLE
Stable9 Upload progress Colour Fix

### PR DESCRIPTION
**Pull request by williambargentball**
Upload progress colour fix from issue #35 move to stable9

Requested on #48 
cc @mar1u5 @jancborchardt

### CODE REVIEW

**Comment by LukasReschke** [comment]
LGTM

**Comment by stp-ip** [comment]
LGTM

**Comment by mar1u5** [comment]
Thank you for backporting 💪  @williambargent

**Comment by jancborchardt** [comment]
@mar1u5 this backport actually is the notification bar color. :) The upload progress bar color I already did in the stable9 theming PR #40 (backport design change)

**Pull request merged**
