### PR TITLE
display error icon on non-success

### PR DESCRIPTION
**Pull request by MorrisJobke**
Forward port of #5937 

This allows to show error state for failed update of username and email address.

### CODE REVIEW

**Comment by daita** [comment]
Lots of change since stable12 in here and I can't even make master displaying the checkmark. Worked few hours on it, removing the hidden class is not enough.

**Comment by pixelipo** [comment]
I can have a look tomorrow

**Comment by MorrisJobke** [comment]
> Lots of change since stable12 in here and I can't even make master displaying the checkmark. Worked few hours on it, removing the hidden class is not enough.

I also noticed that. It was even before the big personal settings PR, that the status icon was not shown anymore. :/

**Comment by pixelipo** [comment]
Should be ok now, @MorrisJobke @daita

**Review by pixelipo — APPROVED** [review]

**Comment by daita** [comment]
both icons work perfectly

**Comment by daita** [comment]
both icons work perfectly

**Review by ArtificialOwl — APPROVED** [review]

**Review by MorrisJobke — COMMENTED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Regression is fixed via #6098

**Pull request merged**
