### PR TITLE
Fix wording meaning (placeholder)

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

## Summary

Because, in that field, we only search for one user (the only next owner).

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM

**Review by artonge — APPROVED** [review]

**Comment by szaimen** [comment]
@Jerome-Herbinet a npm run build is missing in order to mergr this :)

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Actually we want to move from the "user" language to more proper "account". :) @Jerome-Herbinet would you mind adjusting to "Search for an account"?

**Review by jancborchardt — APPROVED** [review]
Looks good, thank you @Jerome-Herbinet! :)

**Comment by jancborchardt** [comment]
Btw @Jerome-Herbinet do you already have a guest account on our Nextcloud? I could add you to the Design team public talk channel if you are interested. :)

**Comment by Jerome-Herbinet** [comment]
> Btw @Jerome-Herbinet do you already have a guest account on our Nextcloud? I could add you to the Design team public talk channel if you are interested. :)

With pleasure @jancborchardt :-) 
I don't think (or don't remember) I've an account. 
Do you have my personal e-mail address ?

**Comment by szaimen** [comment]
Hi, please rebase and resolve the conflicts. Then we can merge this

**Comment by Jerome-Herbinet** [comment]
@szaimen  I close this PR and replace it with https://github.com/nextcloud/server/pull/37762

**Pull request closed without merging**
