### PR TITLE
Allow ldap_dynamic_group_member_url to be a filter

### PR DESCRIPTION
**Pull request by Cybso**
This change allows dynamic_group_member_url of the user_ldap module to
be the filter itself instead of an attribute where the filter can
be read from. The value is assumed to be a filter when it starts with
a round bracket. The substring '%gid' will be replaced by the group's
DN.

This allows group members to be resolved by LDAP_MATCHING_RULE_IN_CHAIN
on Active Directory servers. Example:

```
  (&(objectClass=person)(memberOf:1.2.840.113556.1.4.1941:=%gid))
```

Returns all persons that are either direct members of %gid or members
of another group that is member of %gid.

An alternative implementation would be to implement this as a dedicated settings field, but this "simple" solution _works for me_ ;-)

Signed-off-by: Roland Tapken <roland@bitarbeiter.net>

### CODE REVIEW

**Comment by Cybso** [comment]
Why has the jsunit test being aborted?! However, since this patch did not change the UI it shouldn't matter.

**Comment by MorrisJobke** [comment]
@nextcloud/ldap Please have a look at this as well.

**Comment by blizzz** [comment]
>  The substring '%gid' will be replaced by the group's DN.

Please don't use `%gid` as it is misleading. In nextcloud it is used to represent the group id, apart from that the DN is not really an ID. For instance, use `%gdn` .

Would it be feasable to write some unit tests for it?

**Comment by Cybso** [comment]
@blizzz  I've replaced the string. Is there any tutorial on how to setup a test environment where I can execute the unit tests myself before pushing them into the repository?

**Comment by blizzz** [comment]
@Cybso does this help? https://docs.nextcloud.com/server/13/developer_manual/core/unit-testing.html 

`[sudo] ./autotest.sh sqlite $TESTFILE` is my to-go approach, too.

**Comment by Cybso** [comment]
@blizzz Thanks, I will try

**Comment by blizzz** [comment]
@Cybso seems you did not have a chance yet, did you?

**Comment by ChristophWurst** [comment]
@Cybso any updates? This is conflicting with other changes of that file that happened in the meantime.

**Comment by Cybso** [comment]
I am very sorry, but at the moment I am extremely busy both professionally and privately, so I did not have the time to do that and probably will not find an opportunity to get into the test framework in the foreseeable future.

But since we still have to do the upgrade to Nextcloud 15 within my company I think I will at least be able to solve the merge conflicts this week.

**Comment by rullzer** [comment]
I'm going to close this.
@blizzz feel free to reopen and rebase

**Pull request closed without merging**
