### PR TITLE
Open exiration date picker directly on toggle

### PR DESCRIPTION
**Pull request by rullzer**
For #735

CC: @MorrisJobke @nickvergessen @schiessle @LukasReschke @mar1u5 @jancborchardt

### CODE REVIEW

**Comment by schiessle** [comment]
works great! :+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@rullzer could you open the backport PR?

**Comment by jancborchardt** [comment]
@rullzer thanks a lot, great fix! :)

**Pull request merged**
