### PR TITLE
Add directdownload endpoint

### LINKED ISSUE #9142: Stream endpoint
Assume:

1. A mobile user U using the Nextcloud App N that wants to view a video file in an external app
2. A video app like VLC that you trust
3. A mallware app EVIL that tries to hijack the url send from N to VLC

Because we are sending the link into the open basically we must assure:

1. The link is read only
2. The link is only valid for a limited amount of time (8 hours?)
3. The link does not contain the users username and password
  * Just a random generated token

Basically we'd need an endpoint where the app can say: "I want to have a link to read the file with fileID X". The endpoint will then generate a link that can be send to VLC.

This endpoint should be webdav since it already support range requests by default etc.

CC: @tobiasKaminsky

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #9142 

A basic endpoint to allow clients to have an easy streaming endpoint (for example opening a file in VLC).

1. post request is made to `<server>/ocs/v2.php/apps/dav/api/v1/direct` with `fileId=<x>`
2. A link is returned
3. This link is used by the client to stream

We first ask the storage for a link (S3 for example could provide this directly). Otherwise we generate a 60 char token.

The link thus only gives read access for a limited time.
The link is read only (of course)
The link is more than unique enough (just check 62^60)

Todo:
- [x] Links are valid for 8 hours. However after those 8 hours a request shoudl not directly trigger bruteforce protection.
- [x] Cleanup tokens expired more than a day ago in a cron job.
- [x] Some error handling
- [x] Tests

### CODE REVIEW

**Comment by rullzer** [comment]
@tobiasKaminsky

**Comment by nickvergessen** [comment]
Can I haz hooks for activities :nerd_face:

**Comment by rullzer** [comment]
@nickvergessen o yes please that would be awesome!

**Comment by rullzer** [comment]
@nickvergessen when do you want the hooks? On creation or on access? (or both?)

**Comment by rullzer** [comment]
Ok let do this. I can add the activity hooks later.

@tobiasKaminsky already played around with it on android and it seems to do the job ;)

**Comment by tobiasKaminsky** [comment]
Yes, from my side it is working :-)

**Review by icewind1991 — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
🐘

**Pull request merged**
