### PR TITLE
Bump @nextcloud/vue to 7.1.0-beta0

### LINKED ISSUE #33839: some elements in the sharing dropdown are not visible and no way to scroll down in certain screen resolutions
See 
image

### LINKED ISSUE #34777: [Bug]: Side menu is almost unusable on small resolution
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My laptop screen has this screen resolution : 1366x768px

Displaying the side menu of a file with a preview on firefox maximized (but not full screen) : 

image

It's very difficult to use the share drop-down list and to access internal link and other informations in side menu in these conditions.

### Steps to reproduce

1. Reduce the height of the browser window or use an old screen
2. Display the side menu of a file with a preview thumbnail
3. Try to share it or to get the internal link

### Expected behavior

UI should be responsive and should propose to minimize/toggle the thumbnail preview or detecting the height of the div, toggle it itself.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "merome.net",
            "cloud.merome.net",
            "192.168.1.100"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/merome.net\/owncloud",
        "dbtype": "mysql",
        "version": "25.0.0.18",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "calendar",
            "onlyoffice",
            "spreed",
            "files_mindmap",
            "files_texteditor",
            "external",
            "deck"
        ],
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "has_rebuilt_cache": true,
        "app.mail.verify-tls-peer": false,
        "default_phone_region": "FR",
        "debut": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.14.0
  - forms: 3.0.0
  - integration_mastodon: 1.0.3
  - integration_twitter: 1.0.3
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.3
  - maps: 0.2.1
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - onlyoffice: 7.6.6
  - password_policy: 1.15.0
  - photos: 2.0.0
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - snappymail: 2.19.2
  - spreed: 15.0.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.2.0
  - deck: 1.7.1
  - duplicatefinder: 0.0.15
  - emlviewer: 1.0.2
  - encryption
  - extract: 1.3.2
  - files_markdown: 2.3.6
  - passwords: 2022.10.10
  - tables: 0.2.0
  - twofactor_totp
  - user_ldap
  - workspace
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Not relevant
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
- Fix https://github.com/nextcloud/server/issues/34777 
- Fix https://github.com/nextcloud/server/issues/33839

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:tada:

**Review by artonge — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
Did some small testing and can confirm https://github.com/nextcloud/server/issues/34777 and https://github.com/nextcloud/server/issues/33839 get fixed by it :)

**Comment by skjnldsv** [comment]
> /compile amend /

Won't work, this needs https://github.com/nextcloud/calendar-availability-vue/pull/29

**Comment by skjnldsv** [comment]
Rebased, compiled and upgraded. let's go :rocket:

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
@Pytal can you take care of this? :)

**Comment by Pytal** [comment]
> @Pytal can you take care of this? :)

Please review https://github.com/nextcloud/server/pull/35188 :)

**Comment by szaimen** [comment]
Thanks and done :)

**Pull request merged**
