### PR TITLE
Only run code coverage CI on merge

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by georgehrke — APPROVED** [review]
makes sense 👍

**Comment by kesselb** [comment]
Make sense!

https://github.com/nextcloud/server/blob/5462d4bb5a7a12e929fb95c4760a9d1620a84d00/.drone.yml#L21-L23

I think removing `pull_request` should do the same.

**Comment by rullzer** [comment]
> Make sense!
> 
> https://github.com/nextcloud/server/blob/5462d4bb5a7a12e929fb95c4760a9d1620a84d00/.drone.yml#L21-L23
> 
> I think removing `pull_request` should do the same.

:man_facepalming: yes.... of course

**Review by kesselb — APPROVED** [review]
Guess this works :+1:  No codecov jobs here: https://drone.nextcloud.com/nextcloud/server/21354

**Pull request merged**
