### PR TITLE
Fix details view not closed when viewing a file in its folder

### PR DESCRIPTION
**Pull request by danxuliu**
As far as I understand, #1448 occurs because [`setActiveView` is called with `silent: true`](https://github.com/nextcloud/server/blob/d623763aac3c1c4c0480f0d3ca7182dd2eb68357/apps/files/js/gotoplugin.js#L43). This [prevents the `itemChanged` event to be triggered](https://github.com/nextcloud/server/blob/581227324a8510688c40e9effc8b2fe6a355eba1/apps/files/js/navigation.js#L105-L110), which [would have otherwise closed the details view](https://github.com/nextcloud/server/blob/0ecaf8e6023622393090c1f2ff4c728c96eb2718/apps/files/js/app.js#L221).

I suppose (but I do not really know) that setting the active item is done in silent mode to avoid an unnecessary [reload of the _/_ directory in `_onNavigationChanged`](https://github.com/nextcloud/server/blob/0ecaf8e6023622393090c1f2ff4c728c96eb2718/apps/files/js/app.js#L220) (as the plugin then loads the folder of the selected file). Therefore, I fixed it by closing the details view in the plugin itself, just like it would have been closed by `_onNavigationChanged`.

This does not tackle the other problem mentioned in the issue, which is having several details view with the same `app-sidebar` id. It could be solved by giving each details view its own id, which would require a change in the CSS as currently `#app-sidebar` is used to position its contents, or by using a single details view for all the file lists, although it will probably involve deeper changes as right now every file list expect its own details view to be available for its lifetime.

Anyway, despite being "wrong" the current approach of several details view with the same id works, and with [a possible redesign of the dashboard](https://github.com/nextcloud/server/issues/4273) being discussed a proper fix could be just wasted effort...

(Some files of this pull request conflict with those in other pull request that I have opened; I will rebase this pull request or the other one as needed if they got merged)

### CODE REVIEW

**Comment by blizzz** [comment]
> This does not tackle the other problem mentioned in the issue, which is having several details view with the same app-sidebar id.

It should be re-used, no additionally created. There should not be more than a sidebar.

Your solution works however, but I am not sure about the UX. Keeping the sidebar open seems reasonable and less noisy. cc @nextcloud/designers

**Comment by jancborchardt** [comment]
> with a possible redesign of the dashboard being discussed a proper fix could be just wasted effort

@danxuliu just FYI: That redesign is simply a proposal, so any bugfix is definitely _not_ wasted effort. :)

**Comment by danxuliu** [comment]
@blizzz
>  >  This does not tackle the other problem mentioned in the issue, which is having several details view with the same app-sidebar id.
>  
>  It should be re-used, no additionally created. There should not be more than a sidebar.
>  
>  Your solution works however, but I am not sure about the UX. Keeping the sidebar open seems reasonable and less noisy. cc @nextcloud/designers

Personally I would also prefer to keep the details view open when viewing the file in its folder. However, I made it to close because I thought it was more consistent with current behaviour (even if I do not like that behaviour ;) ). Right now, changing the file list or even changing the directory in the same file list closes the details view (although in this case it could be argued that the context of the file is kept even when changing to a different file list while in other cases it is not, so in this case the details view should be kept open even if in other cases it is closed).

But there was a technical reason to close the details view, and it was that as far as I know there is no way to copy the state from the sidebar of the original file list to the sidebar of the final file list, and I did not want to implement that to just remove it later when the sidebar was fixed to have a single one ;)

@jancborchardt
>  That redesign is simply a proposal, so any bugfix is definitely not wasted effort. :)

Then I can try to fix the multiple sidebar issue if you want. Although I think that it would be better to merge (if it is approved, of course ;) ) the fix for the user-facing bug here (to get it fixed as soon as possible) and then work in the "conceptual" bug in a different pull request.

**Review by blizzz — APPROVED** [review]

**Review by blizzz — COMMENTED** [review]
An acceptence test is failing, otherwise i am ok with it.

**Comment by MorrisJobke** [comment]
> An acceptence test is failing, otherwise i am ok with it.

@danxuliu Could you look into this?

**Comment by danxuliu** [comment]
It is a [false positive](https://github.com/nextcloud/server/issues/4498) (I have ensured running the tests in my computer).

**Comment by blizzz** [comment]
> It is a false positive (I have ensured running the tests in my computer).

Cool, thx. I am good. Then we need only a second reviewre.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
