### PR TITLE
Activity notifications for groupmates by Comments (when using Group Folder app)

### PR DESCRIPTION
**Pull request by ghost**
Currently:
Comments on files in group folders does not generate activity notifications for the groupmates.

With this PR:
Also include groupmates to receive the notifications.

### CODE REVIEW

**Comment by chrisfritsche** [comment]
Hi @nickvergessen and @ChristophWurst ! Pls, when you have time, could you make the review on this PR? Thanks a lot in advance!!

**Review by nickvergessen — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
@chrisfritsche can you rebase one last time?

**Comment by MorrisJobke** [comment]
> @chrisfritsche can you rebase one last time?

I rebased.

**Comment by rullzer** [comment]
CI is not happy

**Comment by rullzer** [comment]
Master is Nextcloud 22 now.
If this should go into 21 it should be backported.

**Comment by PVince81** [comment]
CI not happy, but could be outdated. Needs another rebase, then :-S

**Comment by J0WI** [comment]
The drone tests fails in all recent PRs

**Comment by MorrisJobke** [comment]
@nickvergessen Should we try to get this in or close it for now?

**Comment by nickvergessen** [comment]
Fine by me as per https://github.com/nextcloud/server/pull/23036#issuecomment-728106783

**Comment by juliushaertl** [comment]
Tests are not happy:

```
1) OCA\Comments\Tests\Unit\Activity\ListenerTest::testCommentEvent
ArgumentCountError: Too few arguments to function OCA\Comments\Activity\Listener::__construct(), 6 passed in /drone/src/apps/comments/tests/Unit/Activity/ListenerTest.php on line 84 and exactly 7 expected

/drone/src/apps/comments/lib/Activity/Listener.php:68
/drone/src/apps/comments/tests/Unit/Activity/ListenerTest.php:84
```

**Comment by blizzz** [comment]
@chrisfritsche do you mind checking https://github.com/nextcloud/server/pull/23036#issuecomment-845939734

**Comment by blizzz** [comment]
Closing for inactivity.

**Pull request closed without merging**
