### PR TITLE
limit constructing of result objects in file search

### PR DESCRIPTION
**Pull request by icewind1991**
even thought we currently have no proper way of limiting the search itself, we can at least limit the construction of the result objects.

this saves about 40% of the time spend in the search request in my local testing when the search query matches a large number of files.

Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
sure

**Review by rullzer — CHANGES_REQUESTED** [review]
psalm is not happy

**Comment by icewind1991** [comment]
> psalm is not happy

Looks happy enough to me?

**Comment by icewind1991** [comment]
extended it to also work for the old search endpoint (mainly for backport reasons)

**Review by rullzer — APPROVED** [review]

**Pull request merged**
