### PR TITLE
Code ordering for text strings

### PR DESCRIPTION
**Pull request by Valdnet**
Code cleanup for text strings and change apostrophe to quotation marks for `occ`.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by MichaIng** [comment]
Not sure whether those long lines are better, but doesn't hurt. That is everything you did regarding "Code cleanup", or did I overlook other changes?

Any rationale behind preferring apostrophe over quotation marks for commands in text? I personally always use the latter, especially when the whole string is wrapped into apostrophe already, to avoid required escaping, but I couldn't find any definite/global rule why one would be more correct than the other.

What we could actually to for a bit more consistency is wrapping the HTML tags into apostrophe as well, i.e. `"<ul>"` => `'<ul>'`.

**Comment by Valdnet** [comment]
> That is everything you did regarding "Code cleanup", or did I overlook other changes?

Yes. I added text strings on one line and changed the quotation marks to an apostrophe.

> Any rationale behind preferring apostrophe over quotation marks for commands in text?

I have standardized to other text strings. In general, I am also behind the quotation marks 😉.

> What we could actually to for a bit more consistency is wrapping the HTML tags into apostrophe as well, i.e. "<ul>" => '<ul>'.

Done 😉.

**Comment by MichaIng** [comment]
Are single quotes really used for code/settings/commands consistently in other cases? E.g. in the same file I (still) see:
```
The PHP function "set_time_limit" is not available.
```
```
Missing primary key on table "{tableName}".
```
```
Missing optional column "{columnName}" in table "{tableName}".
```
so all double quotes. Or is there an intended difference between settings and commands? I've not much objection about this, but generally consistency would be great.

About single-line vs split-line, similarly others who do more with this code need to decide. Some + on your change is that it is consistent now since in all other cases in this file (many more), its single lines as well.

**Comment by Valdnet** [comment]
@MichaIng I changed to quotes in all text strings from `occ` 😉.

**Review by MichaIng — APPROVED** [review]
Approving as it creates consistency, following the major coding standard in this file (single line `msg:`, single quoted strings, double quoted settings/commands in strings). Whether this coding standard is the wanted one, may however need to be decided by someone else 🙂.

**Review by rakekniven — APPROVED** [review]

**Comment by Valdnet** [comment]
@szaimen Can you also merge here? There is a problem with the drone. Thanks 😉.

**Comment by Valdnet** [comment]
@szaimen I am asking you for help in resolving the conflict and merge 😉.

**Comment by MichaIng** [comment]
Rebased and conflicts resolved.

**Comment by Valdnet** [comment]
@MichaIng Thanks a lot 👍.

**Pull request merged**
