### PR TITLE
feat(files): better breakpoints and sidebar responsive design

### PR DESCRIPTION
**Pull request by skjnldsv**
This uses 3 breakpoints for better visibility:
- 1024
- 768
- 512

Files kinda had those (480 instead of 512), and I think it's alright like this. What do you think @jancborchardt ? Shall we push that to other apps too?

## Without sidebar:

https://user-images.githubusercontent.com/14975046/231525923-65ba4763-5c13-489a-92f2-71a1d6a9d885.mp4

## With sidebar:

https://user-images.githubusercontent.com/14975046/231525979-b6ca3d12-a375-4cf0-a04b-06fe3016e907.mp4

## Various screenshots:

|| Without sidebar | With sidebar |
|:---------:|:---------:|:------:|
|1366|localhost_8080_index php_apps_files_trashbin|localhost_8080_index php_apps_files_trashbin (1)|
|1024|localhost_8080_index php_apps_files_trashbin (3)|localhost_8080_index php_apps_files_trashbin (2)|
|768|localhost_8080_index php_apps_files_trashbin (4)|localhost_8080_index php_apps_files_trashbin (5)|
|512|localhost_8080_index php_apps_files_trashbin (7)|localhost_8080_index php_apps_files_trashbin (6)|

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Looks great from the screnshots/casts and the code looks good! :)
(but didnt test)

**Comment by szaimen** [comment]
> There is one thing I would change, is increasing the breakpoint of the Sidebar going full screen (512 at the moment). This would need a fix in the vue components.

I agree, should we increase this to 768? (I could do the PR if you want)

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Review by artonge — APPROVED** [review]

**Pull request merged**
