### PR TITLE
Fix sharing note placeholder

### LINKED ISSUE #18452: 18b2: share note auto-save useless
The share note auto-save is completely useless. Unless you're a super-fast 10-finger-typer, it's auto-saving super-quickly and sending an email right away.
Also deleting the hint text (see also https://github.com/nextcloud/server/issues/18451) with the backspace key auto-saves all the time.

Example: The following video generated eight emails:

Peek 2019-12-17 18-35

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #18452 
Closes #18735

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Comment by rullzer** [comment]
So now there is no placeholder at all?
Fine by me but just wanted to double check.

**Comment by skjnldsv** [comment]
> So now there is no placeholder at all?

Ah, my mistake, I thought I added one! :O

**Review by rullzer — APPROVED** [review]
:rocket: works like a charm :star:

**Pull request merged**
