### PR TITLE
Add proper scope to files external CSS

### PR DESCRIPTION
**Pull request by MorrisJobke**
- for select2

cc @nickvergessen

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This messes up with other (especially smaller) select2 instances instances in the admin settings.

**Comment by nickvergessen** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I just noticed an issue. Will push an update soon.

**Comment by MorrisJobke** [comment]
I pushed a fixed version.

**Pull request merged**
