### PR TITLE
chore: stricter access to testremote endpoint

### PR DESCRIPTION
**Pull request by Altahrim**
## Summary
Add rate limit and stricter checks for testremote endpoint

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]
Can you add a comment explaining what the regexp is matching?

**Review by provokateurin — APPROVED** [review]
Agree with @artonge

**Comment by Altahrim** [comment]
Seems auto-merge did its job… It matches URI reserved characters (I removed the `:` to be able to specify a port)

**Pull request merged**
