### PR TITLE
extend storage api to allow directly writing a stream to storage

### PR DESCRIPTION
**Pull request by icewind1991**
this removes the need for temporary storages with some external storage backends.
The new method is added to a separate interface to maintain compatibility with
storage backends implementing the storage interface directly (without inheriting common)

Currently the interface is implemented for objectstorage based storages and local storage
and used by webdav uploads

This is a change I've been wanting to do forever but never got around to before.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
I'll give it a spin tomorrow.
But in general looks good. And awesome stuff :rocket:

**Comment by MorrisJobke** [comment]
> I'll give it a spin tomorrow.

😉

**Review by MorrisJobke — APPROVED** [review]
Code looks good and existing workflows still work fine 👍

**Review by rullzer — CHANGES_REQUESTED** [review]
Failing CI should be fixed

**Comment by rullzer** [comment]
Seems encryption is still not happy

**Comment by icewind1991** [comment]
I think the remaining failure is unrelated

**Review by rullzer — APPROVED** [review]

**Pull request merged**
