### PR TITLE
Fix AppMenu icons for firefox

### LINKED ISSUE #34969: [Bug]: Icons in the AppMenu not showing properly in Firefox
### Bug description

**Nextlcoud version:** 25.0.1

The app icons are not visible in firefox.

https://github.com/nextcloud/server/blob/f53abd3995cffcc0c0a3c5d9be80d993242d9b4e/core/src/components/AppMenu.vue#L186

The padding here causes (on firefox) to make the icon so small that it disappears.

adding a `box-sizing: content-box;` fixes the issue without breaking safari or chrome.

https://user-images.githubusercontent.com/14948823/199985819-89e59e72-3cfa-4d77-9921-d803b3a3b4bb.mp4

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/34969

Supersedes https://github.com/nextcloud/server/pull/34971

Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
@Pytal one review maybe? :)

**Review by Pytal — APPROVED** [review]

**Pull request merged**
