### PR TITLE
Fix vertical alignment of loading icon and status message in Theming app

### PR DESCRIPTION
**Pull request by danxuliu**
Before:
before-theming-loading

After:
after-theming-loading

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by juliusknorr — APPROVED** [review]
Really nice @danxuliu :+1:

**Comment by MorrisJobke** [comment]
I would propose to backport this to stable12.

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by pixelipo** [comment]
haven't tested this, but code looks cleaner than before and it only affects theming, so :+1:

**Comment by danxuliu** [comment]
> Really nice @danxuliu 👍

Thanks, although it would have been even nicer if I did not break the upload button xD

> I would propose to backport this to stable12.

If backported be aware of #5982!

**Comment by karlitschek** [comment]
backport makes sense :+1:

**Comment by danxuliu** [comment]
Done :-)

**Pull request merged**
