### PR TITLE
Provide contactsmenu as ocs

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref #28751 
Ref https://github.com/nextcloud/files-clients/issues/1

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
Oh, so I didn't know, but the contactmanager basically works on the (system)addressbook.
So there is no "id" because the systemaddressbook is not serving the user id or a contact id and that is also why the avatar is a dav resource.

Doesn't look fixable in short term. So either we just do it this way or we have to delay the PR I fear

**Comment by skjnldsv** [comment]
> * id is null?

https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Contacts/ContactsMenu/ContactsStore.php#L286-L290

We can fix that easily by making sure we set the id that is not set anymore `$contact['UID']` works, but might not make sense for normal contacts (non system addressbook I mean)

> * avatar should be the public avatar

Two options:
1. We fix the davAvatar provider and redirect to avatar endpoint if the addressbook is the system addressbook
2. We properly fix/store the user Avatar in the cached system addressbook vcard
3. We fix the contactsMenu method and if we encounter a contact from the system addressbook, we use the avatar endpoint 
  https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Contacts/ContactsMenu/ContactsStore.php#L296-L299

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
ID is fixed @tobiasKaminsky

**Review by Pytal — APPROVED** [review]

**Comment by nickvergessen** [comment]
I would instead go with https://github.com/nextcloud/server/pull/29269 
Much more usable for the clients and a better way forward then populating whatever the current private api tried to do.

**Pull request closed without merging**
