### PR TITLE
Strict typing tests

### PR DESCRIPTION
**Pull request by MorrisJobke**
* first commit is only cleanup

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer I would say, that we should first get this in and then have followup PRs that add the strict typing to subtrees of our code.

**Comment by MorrisJobke** [comment]
Or should we already add `lib/` already in this PR?

**Comment by nickvergessen** [comment]
Do we need to add it to each file?

**Comment by MorrisJobke** [comment]
> Do we need to add it to each file?

Yes.

**Comment by nickvergessen** [comment]
I shall run my other script than to update the php testing versions in travis.yml for all apps on master I guess 🙊

**Comment by MorrisJobke** [comment]
> Do we need to add it to each file?

There is a PHPStorm inspection for this: https://stackoverflow.com/a/43281565/520507

**Comment by nickvergessen** [comment]
> I shall run my other script than to update the php testing versions in travis.yml for all apps on master I guess 🙊

Added here: https://github.com/nextcloud/server/issues/7808#issuecomment-357209658

**Comment by MorrisJobke** [comment]
Rebased to check the current status.

**Comment by MorrisJobke** [comment]
Nothing for 14 it seems -> moved to 15

It's an ongoing improvement ;)

**Pull request closed without merging**
