### PR TITLE
Fix LDAP AD add-on not loading issue

### PR DESCRIPTION
**Pull request by HawksRepos**
Myself and multiple others have had issues when trying to set-up the LDAP/AD add-on. Seemed like no matter what we tried it would not load anything. After making these changes it now works perfectly!

Thanks @lbarnett83 for the pointing this out to me and helping to get my instance working!

### CODE REVIEW

**Comment by ibracorp** [comment]
Thanks Hawks, we need this fixed

**Comment by kesselb** [comment]
Thanks :+1: 

I'm closing this pull request as the issue is a broken nginx configuration: https://github.com/nextcloud/documentation/pull/2197

**Comment by ibracorp** [comment]
This isn't a NGINX issue. This happens locally connected to the address also

**Comment by kesselb** [comment]
> This isn't a NGINX issue

If the webserver is executing the files directly without piping through index.php it's an issue with the webserver configuration.

**Pull request closed without merging**
