### PR TITLE
Fix scss webroot and url rewrite

### LINKED ISSUE #7534: 13.0.0 Beta 3: Wrong paths in App CSS files with multiple app_paths
### Steps to reproduce
1. Open the Polls App without any existing polls (the same problem exists for example with the Mail App)

### Expected behaviour
In the middle of the screen, there is the icon of the polls app.

### Actual behaviour
There is no icon. There is no problem with the icon in the navigation bar on the top.

After looking at the CSS code, there is
```css
mask: url('../../apps/apps2/polls/css/../img/app-logo-polls.svg') no-repeat 50% 50%;
```
It should be
```css
mask: url('../../apps2/polls/css/../img/app-logo-polls.svg') no-repeat 50% 50%;
```

### Server configuration

Multiple app paths are set in the config.php:

<details>

```php
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/.../apps3',
      'url' => '/apps3',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/.../apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
    2 =>
    array (
      'path' => '/.../nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
```

</details>

**Operating system**:
Arch Linux

**Web server:**
nginx

**Database:**
mariaDb

**PHP version:**
7.2.0

**Nextcloud version:** (see Nextcloud admin page)
13.0.0 Beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.0 Beta 1, Version 12 was installed before.

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### PR DESCRIPTION
**Pull request by skjnldsv**
Fixes #7534
Also fixes the following situations:
- Sub-directory nc installation
- Sub-directory nc installation with a non-root app_path
- Basic nc installation with a non-root path

➡️ Fix the massiv log spamming of not finding the webroot

TODO:
- [x] Testing

### CODE REVIEW

**Comment by skjnldsv** [comment]
Test finally fixed! :)
@LukasReschke you forgot to revert back the original WEBROOT in multiple tests, it's now fixed. I added you as reviewer for that 😉 

@zauguin please test! 😃

**Review by juliusknorr — APPROVED** [review]

**Comment by zauguin** [comment]
Works fine. Awesome👍

**Review by MorrisJobke — APPROVED** [review]
Tested and works here 👍

**Comment by skjnldsv** [comment]
We need a backport imho :)
@karlitschek @MorrisJobke @rullzer

**Comment by MorrisJobke** [comment]
@skjnldsv Do it ;)

**Comment by karlitschek** [comment]
Backport is fine. Please note that this change has the potential to break in esoteric/non standard webserver setups. So good testing is important.

**Comment by skjnldsv** [comment]
@karlitschek that's why I added tests with various installation instances to  make sure it doesn't break. :)

**Pull request merged**
