### PR TITLE
ci: also check for uncompiled SCSS styles

### PR DESCRIPTION
**Pull request by susnux**
* Follow up on https://github.com/nextcloud/server/pull/45712

Also check that changes of `scss` files are compiled to `css` in PRs.

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
/backport 995aa67f12f234675b97814d4c166b7afd6a8200 to stable29

**Comment by nickvergessen** [comment]
/backport 995aa67f12f234675b97814d4c166b7afd6a8200 to stable28

**Review by skjnldsv — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Binary files a/core/css/server.css and b/core/css/server.css differ

**Comment by susnux** [comment]
> Binary files a/core/css/server.css and b/core/css/server.css differ

Yes someone merge something in the meantime. Rebased, should work now.

**Pull request merged**
