### PR TITLE
Only do stuff when its a remote-share activity

### LINKED ISSUE #2254: explode() expects parameter 2 to be string, array given at apps/files_sharing/lib/Activity/Providers/RemoteShares.php#162
I have several of these in my log file:

```
{"reqId":"1305x4uVWmrPMimM3l7T","remoteAddr":"10.211.55.2","app":"PHP","message":"explode() expects parameter 2 to be string, array given at \/media\/psf\/nextcloud\/apps\/files_sharing\/lib\/Activity\/Providers\/RemoteShares.php#162","level":3,"time":"2016-11-22T17:37:37+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/activity\/api\/v2\/activity\/filter?format=json&object_type=files&object_id=7","user":"admin","version":"11.0.0.2"}
```
cc @rullzer

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #2254 

## Steps
1. Share with a group
2. Share with a user
3. Set log level to debug
4. Visit activity page
5. See log spam

@LukasReschke @rullzer

### CODE REVIEW

**Comment by nickvergessen** [comment]
Also checked the other Providers, all are safe, only this one was faulty

**Comment by rullzer** [comment]
No more spam! 💃 

👍

**Comment by nickvergessen** [comment]
Failing test is an unrelated timeout issue...

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
