### PR TITLE
do onetime user setup before getting any mount from providers

### PR DESCRIPTION
**Pull request by icewind1991**
this fixes a race condition where wrappers weren't properly applied if when a mount provider creates the storage instance one mountpoint creation instead of lazily

To test:

- Setup an instance with encryption enabled, groupfolders and text
- Enable groupfolder encryption: `occ config:app:set groupfolders enable_encryption --value true`
- Create a groupfolder and navigate into it
- Click the "Add notes, lists, or links..." in the webui to create a `Readme.md` in the folder
- Check if the text editor gets filled with an encrypted blob or an empty textfile

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by Pytal** [comment]
Backportable to `stable24` @icewind1991?

**Pull request merged**
