### PR TITLE
relax strict getHome behaviour for LDAP users in a shadow state

### PR DESCRIPTION
**Pull request by blizzz**
* simplifies deletion process
* less strange behaviour when looking up home storage (as long as it is local)
* enables transfer ownerships after user went invisible on ldap (* not sure about behviour with external storages requiring auth)
* storages of deleted ldap users can still be accessed, apart form potential external storages that require auth
* decouples userExists from an LDAP check, allows for setting deleted state directly, solves some edge cases

* [x] adapt tests

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by moodlebeuth** [comment]
@blizzz: Can you backport this patch for nc 16 and/or nc 17?

Thanks & Greetings,
Michael form Berlin

**Comment by blizzz** [comment]
@moodlebeuth Heyo Michael :) As it contains elementary and behavorial changes, I hesitate to pour this into a stable release. On the other hand, the changes made are done with patching older versions in mind, in favour of "better" changes (which still might come in as an additional, explicit commit). So at least it would be easy to apply it to an older series. It's not a definite no however.

Did you try it on a test system yet?

**Comment by blizzz** [comment]
Some tests are failing also because of https://github.com/nextcloud/server/pull/18254, but another LDAP integration test, too, which does not seem related however. Let's rebase once #18254 is merged.

**Comment by rullzer** [comment]
@blizzz I moved this to 19.

**Comment by blizzz** [comment]
@rullzer np, probably gonna backport it anyway

**Comment by juliushaertl** [comment]
Still a failure:

```

--- Failed scenarios:
--
260 |  
261 | /drone/src/build/integration/ldap_features/openldap-numerical-id.feature:50

```

**Comment by blizzz** [comment]
yep

**Review by juliusknorr — APPROVED** [review]
Looks good otherwise :+1:

**Comment by blizzz** [comment]
okay, I know the reason, but have no good way around. yet. We know the user from the previous test scenario (mapped in DB), but the filter has changed. So we would need to check LDAP to see that the user has gone. Previously it would happen through userExists since it did a lookup in LDAP. Now we only report the local state (and a true is necessary to be able to delete a user locally...). Tricky. To be continued.

**Comment by blizzz** [comment]
Tests are passing now. When reading members of a group, and those were already mapped in Nextcloud, but now excluded by a filter, they would pass if not ensured that they are available for Nc.

**Pull request merged**
