### PR TITLE
Force hide tooltips on sidebar close

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

cc @pielonet

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by pielonet** [comment]
Hi John,
Thanks for fixing this too. I'll have to test it too :) !

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
Backport in https://github.com/nextcloud/server/pull/17500

**Pull request merged**
