### PR TITLE
Color the trusted domain to alert the admin a bit more

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @rullzer 

administration_-_nextcloud_-_2016-10-31_12 15 50

### CODE REVIEW

**Comment by schiessle** [comment]
Hm, the crucial question for me is, whether we really want to have a confirm dialog for every trusted server the admin adds? I tend to say now.

Cc @jancborchardt

**Comment by LukasReschke** [comment]
> Hm, the crucial question for me is, whether we really want to have a confirm dialog for every trusted server the admin adds? I tend to say no.

This is for trusted domains for the trusted domain check. Nothing to do with federated sharing or whatsoever. There it is required. Because you basically click the "Add trusted domain" link and get redirected to this.

**Comment by schiessle** [comment]
Ah, OK.... mixed this up. Then it makes sense. (Beside the stupid "!" at the front of the dialog, but I assume that this is a general issue and out of scope for this PR) :+1:

**Comment by rullzer** [comment]
LGTM

**Comment by jancborchardt** [comment]
Btw @nickvergessen can we have the button be more contextually relevant here?

Yes shoud be: »Yes, add trusted domain«x

**Comment by nickvergessen** [comment]
No, the JS thing only has options yes-no and ok

**Comment by jancborchardt** [comment]
@nickvergessen well, then it’s of course a request that we should fix it. Opened an issue at https://github.com/nextcloud/server/issues/2104 ;)

**Pull request merged**
