### PR TITLE
Fix login primary colour and feedback

### LINKED ISSUE #12404: Weblogin: strange submit button
Please see this video: https://cloud.nextcloud.com/s/mzESF9wXNsdwZSM

Happens on NC15 beta1 and NC master.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #12404 (not found)

| Before | After |
|:---------:|:------:|
|peek 16-11-2018 18-23|peek 16-11-2018 18-27|

@nextcloud/designers

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> #### Conflicting files
> `core/css/guest.css`

FYI

**Comment by skjnldsv** [comment]
Failure unrelated

**Review by juliusknorr — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Fine by me

**Comment by ChristophWurst** [comment]
@skjnldsv time to squash those commits!

**Comment by ChristophWurst** [comment]
@fixupbot squash

**Comment by ChristophWurst** [comment]
> I manually squashed because there were conflicts that where resolved by the merge, but due to the rebase the merge vanished.

FYI https://github.com/nextcloud/server/pull/12495#issuecomment-439865648 was a joke. That bot does not yet support that :wink:

**Pull request merged**
