### PR TITLE
Bugfix/noid/product name on updater

### PR DESCRIPTION
**Pull request by nickvergessen**
I modified `$tmpl->assign('productName', $defaults->getName());` in lib/base.php and prepended some `#` to take screenshots.

### Update screen in beginning
Bildschirmfoto von 2021-03-22 16-29-21

### Update with success
Bildschirmfoto von 2021-03-22 16-29-25

### Update with warnings
Bildschirmfoto von 2021-03-22 16-29-07

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
:elephant:

**Comment by MorrisJobke** [comment]
Do we want to backport this?

**Comment by nickvergessen** [comment]
Don't care too much. We can backport it for 21 if we want

**Comment by MorrisJobke** [comment]
Let's keep it like that now :)

**Pull request merged**
