### PR TITLE
Create app password by pressing enter

### LINKED ISSUE #3799: Pressing »enter« should also create app password
In this view in the app passwords:
capture du 2017-03-11 11-43-28
you can not just press enter while in the field. Should be possible though.

cc @nextcloud/designers @nextcloud/javascript

### PR DESCRIPTION
**Pull request by Thijsdh**
Fixes #3799 

Signed-off-by: Thijs den Hartog <Thijs@thijsbeer.nl>

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works here 👍

**Review by ChristophWurst — APPROVED** [review]
Nice! Thank you very much :-)

**Comment by MorrisJobke** [comment]
@Thijsdh Could we ask you to sign-off your commit? For details see: https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

`git commit --amend -s` will add the correct line and then a force push to this branch should update this PR.

**Comment by MorrisJobke** [comment]
> Signed-off-by: Thijs den Hartog Thijs@thijsbeer.nl

Weird - this is in the first comment but not in the commit 😕

**Comment by Thijsdh** [comment]
Fixed it. :+1:

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
