### PR TITLE
Bump scssphp/scssphp from 1.0.3 to 1.1.1

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [ ] Requires https://github.com/nextcloud/3rdparty/pull/456

This is the first scssphp bump that does not completely break our overall design, yay.

### CODE REVIEW

**Comment by kesselb** [comment]
image

1. Checkout `dependabot/composer/scssphp/scssphp-1.1.1`
2. Run `git submodule update --init`
3. Run `occ maintenance:repair`

:man_shrugging: :confused:

**Comment by ChristophWurst** [comment]
I just had this minor issue https://github.com/nextcloud/3rdparty/pull/456#pullrequestreview-425990027

**Comment by ChristophWurst** [comment]
I also ran `occ maintenance:repair`. Does that help?

**Comment by kesselb** [comment]
I run maintenance:repair. Maybe it's a issue with my dev setup. Let's see if anyone else can reproduce :)

**Comment by skjnldsv** [comment]
Pwet

**Comment by ChristophWurst** [comment]
stale and needs to be redone

**Pull request closed without merging**
