### PR TITLE
25.0.0 RC 1

### PR DESCRIPTION
**Pull request by blizzz**
* #31807
* #34117
* #34130
* #34133
* #34140
* #34144
* #34145
* #34147
* #34154
* #34161
* #34165
* #34170
* #34171
* #34180
* #34181
* #34184
* #34192
* #34195
* nextcloud/3rdparty#1173
* nextcloud/files_pdfviewer#657
* nextcloud/files_rightclick#144
* nextcloud/files_rightclick#145
* nextcloud/files_videoplayer#283
* nextcloud/firstrunwizard#740
* nextcloud/firstrunwizard#741
* nextcloud/nextcloud_announcements#103
* nextcloud/notifications#1276
* nextcloud/notifications#1279
* nextcloud/photos#1247
* nextcloud/photos#1259
* nextcloud/photos#1263
* nextcloud/photos#1264
* nextcloud/photos#1265
* nextcloud/photos#1266
* nextcloud/photos#1267
* nextcloud/photos#1268
* nextcloud/photos#1269
* nextcloud/photos#1270
* nextcloud/photos#1272
* nextcloud/photos#1273
* nextcloud/photos#1274
* nextcloud/photos#1276
* nextcloud/photos#1277
* nextcloud/serverinfo#399
* nextcloud/survey_client#144
* nextcloud/text#2922
* nextcloud/text#2970
* nextcloud/text#2972
* nextcloud/text#2973
* nextcloud/text#2978
* nextcloud/text#2981
* nextcloud/viewer#1353
* nextcloud/viewer#1354
* nextcloud/viewer#1355
* nextcloud/viewer#1358
* nextcloud/viewer#1360
* nextcloud/viewer#1362
* nextcloud/viewer#1366
* nextcloud/viewer#1370
* nextcloud/viewer#1374
* nextcloud/viewer#1375
* nextcloud/viewer#1376
* nextcloud/viewer#1377
* nextcloud/viewer#1378
* nextcloud/viewer#1379
* nextcloud/viewer#1380
* nextcloud/viewer#1381

Pending PRs:

* [ ] #34187 @nickvergessen
* [ ] #34196 @blizzz

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by CarlSchwan** [comment]
Can we try to get https://github.com/nextcloud/server/pull/34142 in the RC? this will make the update process faster

**Review by skjnldsv — APPROVED** [review]

**Comment by blizzz** [comment]
> Can we try to get #34142 in the RC? this will make the update process faster

if it is not critical rather rc2 next week

**Comment by blizzz** [comment]
waiting for backports of

* [ ] 34142
* [ ] 34190

**Comment by come-nc** [comment]
Would be good to have:
- [ ] https://github.com/nextcloud/server/pull/34195

**Comment by andyxheli** [comment]
Can we also include this please Fix User profile picture when performing the search #32635

**Comment by CarlSchwan** [comment]
> Can we also include this please Fix User profile picture when performing the search #32635

Sorry, we forgot about it but since this is a bugfix we can add it to the RC2 (I suppose)

**Comment by andyxheli** [comment]
No worries. Thank you! I believe its good to go after some changes that where recommend  just needs a few more approvals

**Pull request merged**
