### PR TITLE
Use the themed radio buttons for cron selection

### PR DESCRIPTION
**Pull request by nickvergessen**
### Before

Ugly OS color
admin_-_nextcloud_-_2016-07-19_16 43 28
### After

Beautiful nextcloud blue
admin_-_nextcloud_-_2016-07-19_16 43 07

### CODE REVIEW

**Comment by schiessle** [comment]
looks good :+1:

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by jancborchardt** [comment]
Awesome dude @nickvergessen! :) cc @Henni just for reference since he did all the checkbox stuff.

**Pull request merged**
