### PR TITLE
Remaining flow frontend polishing

### PR DESCRIPTION
**Pull request by juliusknorr**
- Checks will automatically pick up is/matches depending if the value is a regex or not. e.g. when choosing "Images" as mime type, the checker will only work when the operator is "matches", not "is"
- Add flow icon for app store category …
- Fix action listing alignment and show more button

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Looks good!

**Review by ChristophWurst — APPROVED** [review]
Looks good :)

**Comment by ChristophWurst** [comment]
needs a rebase

**Comment by ChristophWurst** [comment]
(and run the lint fix just in case)

**Review by blizzz — APPROVED** [review]
The link to the apps is not created correctly when running in a subfolder (the subfolder is cut away), but that was already the case before. All changed things shiny :)

**Comment by juliushaertl** [comment]
@blizzz Actually there was another polishing issue i forgot so I'm adding your comment to https://github.com/nextcloud/server/issues/18191 for the next batch

**Pull request merged**
