### PR TITLE
[3rdparty] PasswordCompat is no longer required

### PR DESCRIPTION
**Pull request by rullzer**
- [x] Requires https://github.com/nextcloud/3rdparty/pull/14
- [x] Rebase after https://github.com/nextcloud/server/pull/836 to fix tests

No longer needed since 5.4 is dropped

CC: @LukasReschke @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by LukasReschke** [comment]
👍

**Comment by nickvergessen** [comment]
3rdparty merged, needs update

**Comment by rullzer** [comment]
Rebased. CI is green!

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
