### PR TITLE
Unify headers menu design, fix click area

### LINKED ISSUE #11791: 14.0.x: Drop-down settings menu does not scale to accommodate additional entries
### Steps to reproduce
1. Add items to settings menu via (e.g.) External Sites
2. Open drop-down Settings Menu

### Expected behaviour
Menu is drawn around all entries

### Actual behaviour
Menu only drawn around 7 entries, remaining entries are drawn outside of menu. See screenshot:
image

### Server configuration
Problem introduced in 14, did not exist in 13. Persisting in 14.0.3

### LINKED ISSUE #12550: User-menu-dropdown: Full row should be clickable
In the user-menu dropdown, only the text and the icon of the specific row is clickable. It should be the whole row. Tested with Nextcloud 15 beta1.

bildschirmfoto 2018-11-20 um 13 16 33

@nextcloud/designers @skjnldsv

### LINKED ISSUE #12565: Usability of 3-dot "More Apps" Menu with many Apps
As admin I lately get mails with "I can't find app X anymore".
It's not a technical problem, as the apps are activated, but the users can't find them. To find them they need to scroll down in the "More Apps" popover, which is not clearly indicated and overseen by some users.

### Steps to reproduce
1. activate many apps (>15)
2. click on the 3 dots "More Apps" Icon in the Top Nav Bar
3. popover with apps is displayed, some apps are not in the "viewport" as the Popover has a max-height.
4. the scrollbar is not clearly visible (in Sarafi only a slim grey bar)

### Expected behaviour
Users should find all apps with ease

### Actual behaviour
As the target should be to make it easily usable to all users, I feel like this popover should be revisited.
I don't think it is good  to get rid of the popover max-height. Maybe we can indicate with some arrow  that more apps are below or redesign the popover to be fullscreen with a grid layout.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
14.0.3

### Client configuration
**Browser:**
Safari mainly, but Firefox sometimes too

### PR DESCRIPTION
**Pull request by skjnldsv**
- Merge the design of the apps menu and the settings menu for maintainability
- Fix the clickable area
- Fix the loading 
Closes #9752 
Fix #12550
Fix #11791
Fix #12565

### CODE REVIEW

**Comment by jancborchardt** [comment]
Oooooh großartig Herr @skjnldsv, thanks for picking that up! Will get to reviewing right away :1st_place_medal:

**Review by jancborchardt — DISMISSED** [review]
In both Firefox and Chrome, both for mouse and keyboard interaction, I see this for the "More apps" menu:
Opens and then immediately closes again, is only visible for a split second (is much quicker really, the gif is not really proper):
menu does not open

**Comment by jancborchardt** [comment]
Other than my review about the directly closing "More apps" menu it looks good! 

(My #9752 is/was not only about headers btw, but also about other menus like the "+ New" menu in Files as well as the 3-dot menu of every file which e.g. don’t have proper sizes and also no proper hover/focus feedback. :)

**Comment by skjnldsv** [comment]
> @skjnldsv this part would then be separate? :)

You mean actions inside the popovermenu?

**Comment by jancborchardt** [comment]
@skjnldsv yes. Or do you want to directly do it in this pull request too? Because the `Closes #9752` is not entirely correct as I mentioned. ;)

**Comment by skjnldsv** [comment]
I'll add this here :)

**Comment by skjnldsv** [comment]
All done @nextcloud/designers 
capture d ecran_2019-01-29_08-36-00
capture d ecran_2019-01-29_08-42-26
capture d ecran_2019-01-29_08-42-41

**Comment by MorrisJobke** [comment]
Still looks like this (Safari and Chrome)

bildschirmfoto 2019-01-29 um 12 17 58

**Comment by skjnldsv** [comment]
Done @MorrisJobke

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]
lets do this :elephant:

**Pull request merged**
