### PR TITLE
Do not target vue buttons with server rules

### PR DESCRIPTION
**Pull request by marcoambrosini**
Further exception for vue buttons.

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by juliushaertl** [comment]
Should we probably just use `.vue` as with the other parts were we already do this:
https://github.com/nextcloud/server/pull/16661/files
https://github.com/nextcloud/server/pull/21810/files

**Comment by ma12-co** [comment]
Done!

**Review by ChristophWurst — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
To the merge machine! :rocket:

**Comment by ChristophWurst** [comment]
Bildschirmfoto von 2021-03-11 13-39-10

this causes a regression where action menu icons (and text?) shows very faded. Observed in Mail. is this known/intended?

**Comment by skjnldsv** [comment]
> this causes a regression where action menu icons (and text?) shows very faded. Observed in Mail. is this known/intended?

I guess this needs fixing in the vue components now they are standalone?
:thinking:

**Pull request merged**
