### PR TITLE
Update app versions for 23

### PR DESCRIPTION
**Pull request by PVince81**
As discussed with @blizzz, we usually make sure that there is a minor version increment to match a major Nextcloud release.

### CODE REVIEW

**Comment by blizzz** [comment]
> As discussed with @blizzz, we usually make sure that there is a minor version increment to match a major Nextcloud release.

We have collisions in stable21 and stable22, so need to bump here in master – making room for 22 – and then also in stable22.

Example:
Systemtags 21: https://github.com/nextcloud/server/blob/stable21/apps/systemtags/appinfo/info.xml#L9
Systemtags 22: https://github.com/nextcloud/server/blob/stable22/apps/systemtags/appinfo/info.xml#L9

**Review by blizzz — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
How did i miss that in #25454

So yeah we need a +0.1 in master and stable22 i guess

**Comment by kesselb** [comment]
I'm afraid you have to update:
- https://github.com/nextcloud/server/blob/master/tests/Core/Command/Apps/AppsEnableTest.php
- https://github.com/nextcloud/server/blob/master/tests/Core/Command/Apps/AppsDisableTest.php

**Comment by kesselb** [comment]
It's on my list to work on my legacy and rework the tests to be independent of the actual version numbers :see_no_evil:

**Comment by blizzz** [comment]
> How did i miss that in #25454
> 
> So yeah we need a +0.1 in master and stable22 i guess

happens to the best. would be good to have 22 done tomorrow to include it into the release.

**Comment by nickvergessen** [comment]
Fixed the tests

**Review by kesselb — APPROVED** [review]

**Pull request merged**
