### PR TITLE
add option for delete external files without copy to trashbin

### LINKED ISSUE #14436: Disable trash per folder; Especially for external storage folder
**Is your feature request related to a problem? Please describe.**
When adding external storage folder (e.g. SMB) they integrate nicely. But when deleting elements out of those folder they will be moved to local trash bin, which can take a very long time depending on the file size, connection, etc. and this may sometimes even not be desired.

**Describe the solution you'd like**
A good general solution would be to disable trash bin manually on a per folder basis. Or in the settings where the user can list folders to be excluded.

**Describe alternatives you've considered**
One alternative would be to outsource the solution specifically to the external storage add-on and provide a similar option only there on a per share basis.

**Additional context**
-

### PR DESCRIPTION
**Pull request by dassio**
feature enhancement base on #18396  #14436

when deleting external files, the admin can choose using trashbin or not, default is using trashbin

Screenshot from 2020-09-06 20-49-58

### CODE REVIEW

**Comment by blizzz** [comment]
A problem with this addition is, that the end user likely does not know whether a file goes to the trashbin upon deletion, or not. It creates an inconsistency. If we accept it, then it should also be reflected to the end user, that deletion is permanent (@jancborchardt ?). In general i think it is a good addition – the default should be move to trashbin on the other hand, and the settings option positive, e.g. "[x] Deleted files are moved to trashbin".

**Comment by dassio** [comment]
> A problem with this addition is, that the end user likely does not know whether a file goes to the trashbin upon deletion, or not. It creates an inconsistency. If we accept it, then it should also be reflected to the end user, that deletion is permanent (@jancborchardt ?). In general i think it is a good addition – the default should be move to trashbin on the other hand, and the settings option positive, e.g. "[x] Deleted files are moved to trashbin".

sorry about the confusing screenshot, in default mode, the checkbox is not selected

**Comment by dassio** [comment]
> A problem with this addition is, that the end user likely does not know whether a file goes to the trashbin upon deletion, or not. It creates an inconsistency. If we accept it, then it should also be reflected to the end user

you mean like a popup when users delete files with this option on?

**Comment by icewind1991** [comment]
Code wise this looks good. I agree that there should be some indication to the user that the behaviour of deleting files from this specific storage is different than deleting other files

**Comment by blizzz** [comment]
> > A problem with this addition is, that the end user likely does not know whether a file goes to the trashbin upon deletion, or not. It creates an inconsistency. If we accept it, then it should also be reflected to the end user
> 
> you mean like a popup when users delete files with this option on?

Rather the the menu entry stating "Delete file permanently", perhaps turning it red, too. 

Screenshot_20200908_164633

but some indicator would be necessary for the batch action as well.

**Comment by dassio** [comment]
Screenshot from 2020-09-09 23-18-44
Screenshot from 2020-09-09 23-18-52

**Comment by dassio** [comment]
add alert for batch delete 
Screenshot from 2020-09-10 11-58-47

**Comment by jancborchardt** [comment]
Really skeptical about this, sorry to say @dassio :(

As @blizzz said:

> A problem with this addition is, that the end user likely does not know whether a file goes to the trashbin upon deletion, or not. It creates an inconsistency.

And it’s a real problem cause it’s basically a UX choice that is done by _the admin_, on a per-folder basis. So this not only creates confusion on a per-Nextcloud basis, but also per-folder.

------------

So while I really tend to say let’s please not do it, I’d like to know which problem you want to solve @dassio – I’m sure we can find a different approach which fits with other requirements too. :)

**Comment by jancborchardt** [comment]
(Btw @dassio since you are doing a bunch of contributions: We have a Nextcloud Talk instance where we also invite contributors and have channels for general discussion and also the different apps. I can invite you for a guest account with your email address? :)

**Comment by dassio** [comment]
> So while I really tend to say let’s please not do it, I’d like to know which problem you want to solve @dassio – I’m sure we can find a different approach which fits with other requirements too. :)

except from the issues I linked( #18396 #14436), I am really concerned about the download traffic from S3, this one can add up to a big amount compared to what the storage I have to pay.

once I used the MAP app that to extract all the metadata(longitude and latitude ), I ended up downloading 500G from S3, paying 25+ dollars compared to 2 or 1 dollar I have to pay for the storage.

also before I used a Linode that is 20 dollars/ Month because the 10 dollar instance does not have enough disk space, then later I found it is the S3 deleted files that are eating up the disk, I pay an extra 10 dollars for another 5-10 months

**Comment by dassio** [comment]
> And it’s a real problem cause it’s basically a UX choice that is done by _the admin_, on a per-folder basis. So this not only creates confusion on a per-Nextcloud basis, but also per-folder.

I see this one as a concrete requirement if I remember correctly, for the network-attached folder on windows, when you try to delete a file, Windows will not download to the trashbin 

as for the inconsistency, if the functionality is not enabled, there will be no inconsistency issue, if it is enabled, that means the user really needs it.

**Comment by dassio** [comment]
> (Btw @dassio since you are doing a bunch of contributions: We have a Nextcloud Talk instance where we also invite contributors and have channels for general discussion and also the different apps. I can invite you for a guest account with your email address? :) Also let me know which apps you’d like to be in the channels of.)

that will be great, yes you can use my github email
I'd like to be in the photos and serve app

**Comment by juliushaertl** [comment]
@jancborchardt In addition to the points @dassio mentioned there is also the case where a file on an external storage is larger than the users quota available for trashbin. In that case [the file will just be removed](https://github.com/nextcloud/server/pull/23023), since the user is not allowed to store so much data in there. 

So :+1: from my side for this PR.

**Comment by jancborchardt** [comment]
Right, thanks for the explanation @juliushaertl. Then it sounds good – my only feedback is that the correct wording and capitalization would be "Deletion without trashbin".

**Comment by MorrisJobke** [comment]
Close at it was moved to #23489

**Pull request closed without merging**
