### PR TITLE
Remove drone CI and move all CI to PHP 8.3 to test what breaks

### LINKED ISSUE #38828: Support PHP 8.3
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
With the [release of PHP 8.3.0 Alpha 1](https://www.php.net/archive/2023.php#2023-06-08-3) on June 8, it would be worthwhile to begin testing for compatibility in Nextcloud so that it can be ready not too long after [the anticipated release date on November 23, 2023](https://wiki.php.net/todo/php83).

**Describe the solution you'd like**
First, have PHP 8.3 nightly included in CI builds ASAP.
Later, include official support for PHP 8.3 once it's stable.

**Describe alternatives you've considered**
None

**Additional context**
* https://github.com/nextcloud/server/issues/32595

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: #38828 

## Summary

Test PHP 8.3 in our CI to see current support.

## TODO

- [x] Had to adapt to [ReflectionProperty::setValue signature deprecation](https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#reflectionpropertysetvalue), should be move to a PR

### CODE REVIEW

**Comment by come-nc** [comment]
Opened https://github.com/shivammathur/setup-php/issues/757

**Comment by come-nc** [comment]
php-oci pipeline is passing on 8.3.
It does not run the full pipeline though.

**Comment by kesselb** [comment]
Nice :partying_face: 

I migrated the nodb tests last week and documented my findings: https://github.com/nextcloud/server/pull/39734

**Comment by come-nc** [comment]
From https://wiki.php.net/rfc/datetime-exceptions :

> The “Epoch doesn't fit in a PHP integer” now returns a new DateRangeError instead of a generic ValueError, which it does not subclass. This is only an issue for 32-bit platforms.

This is breaking the 32bit test suite.

**Comment by come-nc** [comment]
Ouch, deprecation warnings were not failing in 32bit CI, activated them:
```
There were 173 errors:
There were 14 failures:
```

**Comment by come-nc** [comment]
```
There were 2 errors:
There were 18 failures:
```

**Comment by come-nc** [comment]
Opened https://github.com/phpseclib/phpseclib/issues/1931

**Comment by come-nc** [comment]
CI is green for 32bits on 8.3 :tada: 
https://github.com/nextcloud/server/pull/39734 would help adding 8.3 testing on 64bit as well.

I will make a separate PR to allow 8.3 in the version check and add it to some CI.

**Comment by come-nc** [comment]
Replaced by https://github.com/nextcloud/server/pull/40630 now that CI passes.

**Pull request closed without merging**
