### PR TITLE
validate file name before uploading in upload only folder

### LINKED ISSUE #4211: Show error messages in Files Drop (upload only)
* upload a file that causes an error message (for example upload a .part file)
* expected: show an error message
* actual: no feedback

### PR DESCRIPTION
**Pull request by individual-it**
before uploading in a upload-only folder the file name was not checked with JS and no error was presented to the user if an invalid file was uploaded.
Even worse the UI would list the invalid file in the "Uploaded files" list.
This PR adds a check that is the same as in https://github.com/nextcloud/server/blob/master/apps/files/js/file-upload.js#L793
fixes #4211

### CODE REVIEW

**Comment by individual-it** [comment]
I cannot find any tests for the upload-only page, are there any?

**Comment by blizzz** [comment]
perhaps here? ``apps/files_sharing/tests/js/publicAppSpec.js`` at least there is an upload-specific part, small though.

**Comment by individual-it** [comment]
@blizzz 
> perhaps here? `apps/files_sharing/tests/js/publicAppSpec.js` at least there is an upload-specific part, small though.
That does look to me like its for public upload generally not specific for upload-only folders. So this function might be pretty untested, at least the JS side of it

**Comment by rullzer** [comment]
yes unfortunatly it is pretty untested...

**Comment by blizzz** [comment]
So, let's go out without for now? Or are you eager do add tests @individual-it? :) :) :)

**Comment by individual-it** [comment]
> Or are you eager do add tests?

Generally speaking: Yes! Are you eager to pay me for that :-) ?

My business partner @phil-davis (from Australia) and me (from Germany), we both lived in Nepal for the past 6/8 years and have worked here for an big NGO, now we have moved on and are in the process of starting a Software Development Company in Nepal @JankariTech

Writing automated tests is exactly the service we are planing to offer. The idea is to teach young Nepali IT graduates to write good automated tests and to offer to write tests to companies that do not have enough testing for their projects.

If you are interested happy to keep on talking by Email (info@individual-it.net) or Skype

**Comment by schiessle** [comment]
> Generally speaking: Yes! Are you eager to pay me for that :-) ?
> Writing automated tests is exactly the service we are planing to offer.

Well, showing us and the rest of the world your test-writing-skills here would be the best possible advertisement for your new company 😉

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@schiessle @nickvergessen @blizzz Please review :)

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
