### PR TITLE
fix(htaccess): Serve images as static assets

### PR DESCRIPTION
**Pull request by susnux**
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by susnux** [comment]
I hope this fixes the daily instance not serving images correctly (especially `webp`).

**Review by SystemKeeper — APPROVED** [review]
Makes sense, but guess needs an htaccess update on daily then.

**Comment by susnux** [comment]
@SystemKeeper yes probably but maybe even some Caddy config update.

**Review by ChristophWurst — APPROVED** [review]
Makes sense

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx will need an update too and should be noted in https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_30.html

**Comment by susnux** [comment]
But I do not think this is the root cause as locally deployed with Apache it works, only the daily instance with Caddy seems to have problem :(

**Comment by susnux** [comment]
(I mean it is an improvement anyways)

**Pull request merged**
