### PR TITLE
Add current status in navbar

### PR DESCRIPTION
**Pull request by CarlSchwan**
This ports the code to Vue and if the user_status app is disabled this
goes back to the previous behavior.

The Avatar vue component detects changes of the status automatically.

image

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Very nice! :) One thing: We can go without the tooltip on hover/focus because when you click the avatar, you see the full status in the menu anyway.

**Review by jancborchardt — APPROVED** [review]

**Review by PVince81 — CHANGES_REQUESTED** [review]
some concerns about escaping in the PHP template

**Review by PVince81 — APPROVED** [review]
Code looks good :+1:

**Comment by CarlSchwan** [comment]
Test failure is not unrelated: ldap server disconnected. I'm going to squash the commits and then merge this with admin right (ci is really too slow currently)

**Pull request merged**
