### PR TITLE
[stable16] relax strict getHome behaviour for LDAP users in a shadow state

### PR DESCRIPTION
**Pull request by blizzz**
backport of #17717

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by rullzer** [comment]
CI does boom

**Comment by juliushaertl** [comment]
Pushed a quick fix for PHPUnit compatibility

**Comment by rullzer** [comment]
Doesn't seem to be enough https://drone.nextcloud.com/nextcloud/server/25471/14/4

**Comment by blizzz** [comment]
let's postpone

**Comment by blizzz** [comment]
I added the unit test compat fixes from the17 backport https://github.com/nextcloud/server/pull/18884

**Comment by skjnldsv** [comment]
Greeeen

**Pull request merged**
