### PR TITLE
Fix typo in occ

### PR DESCRIPTION
**Pull request by HarHarLinks**
Signed-off-by: Kim Brose <kim.brose@rwth-aachen.de>

### CODE REVIEW

**Review by gary-kim — APPROVED** [review]

**Comment by gary-kim** [comment]
Thank you for your contribution!

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Ah CI fails. Could you fix the tests as well?

**Comment by gary-kim** [comment]
This should do the trick
```
diff --git a/tests/Core/Command/User/SettingTest.php b/tests/Core/Command/User/SettingTest.php
index 7d71734334..8486e7fc3c 100644
--- a/tests/Core/Command/User/SettingTest.php
+++ b/tests/Core/Command/User/SettingTest.php
@@ -93,7 +93,7 @@ class SettingTest extends TestCase {
 				[['ignore-missing-user', false]],
 				[],
 				null,
-				'The user "username" does not exists.',
+				'The user "username" does not exist.',
 			],
 
 			[
```

**Comment by HarHarLinks** [comment]
@gary-kim that's about what I suspected, thanks for already finding it.
Let's hope this build succeeds.

**Comment by rullzer** [comment]
It did!

Welcome to the club @HarHarLinks

**Pull request merged**
