### PR TITLE
[stable15] Add activities for group membership changes

### PR DESCRIPTION
**Pull request by nickvergessen**
backport #14502

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
CI failures

**Comment by nickvergessen** [comment]
Fixed

**Comment by MorrisJobke** [comment]
Still some of them fail 🙈

**Comment by nickvergessen** [comment]
arg, `:void` is 7.1+

Fixed

**Pull request merged**
