### PR TITLE
fix(app-dashboard): fixes dashboard bg issues on larger screens

### PR DESCRIPTION
**Pull request by faust64**
as suggested per nextcloud/server#25447

changes content min-height, from 100% to 100vh.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@jospoortvliet @ethancedwards8 could you test this and confirm if it fixes the issue you reported? :)

**Comment by ethancedwards8** [comment]
I think its fixed it, but I am using a different computer than when I commented on the issue.

**Comment by juliushaertl** [comment]
I haven't tested yet but since this basically applies globally I would expect side effects similar to what was discussed in https://github.com/nextcloud/nextcloud-vue/issues/1384

I think for now we should only apply that inside of the dashboard app to fix the issue there and avoid breaking things in other places.

**Comment by rullzer** [comment]
So what is the status here after the comments from @juliushaertl ?

**Comment by faust64** [comment]
I moved my change to the dashboard, as requested. Let me know if there's anything else I can do.

**Comment by PVince81** [comment]
obsoleted by https://github.com/nextcloud/server/pull/26120

sorry that we didn't see this one first.
in any case, trying to get the solution merged now

**Pull request closed without merging**
