### PR TITLE
[stable25] Bump @nextcloud/password-confirmation from 4.0.1 to 4.0.2

### PR DESCRIPTION
**Pull request by Pytal**
Backport https://github.com/nextcloud/server/pull/34541

Fix https://github.com/nextcloud/server/issues/34611

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Not sure if the broken admin password confirmation qualifies for a merge into 25.0.0 thou.
Will be super inconvenient, but a workaround (pressing enter) is there, so maybe 25.0.1 is good enough.

**Review by skjnldsv — APPROVED** [review]

**Comment by PVince81** [comment]
@Pytal needs manual rebase with conflict resolution

**Comment by andyxheli** [comment]
https://github.com/nextcloud/server/issues/34782

**Pull request merged**
