### PR TITLE
[stable28] chore(deps): Bump @nextcloud/vue to v8.13.0

### PR DESCRIPTION
**Pull request by hamza221**
* Resolves: # 

## TODO

- [x] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by skjnldsv** [comment]
Duplicate of https://github.com/nextcloud/server/pull/46239

**Comment by hamza221** [comment]
@skjnldsv It's not, this is a bump to 8.13.O not 8.11.3

**Comment by skjnldsv** [comment]
@hamza221 we do not update minor or major for older stable versions unless we have a very good reason to do so :thinking:

**Comment by hamza221** [comment]
It's needed because of this https://github.com/nextcloud-libraries/nextcloud-vue/pull/5728

**Pull request closed without merging**
