### PR TITLE
[stable17] Handle token insert conflicts

### PR DESCRIPTION
**Pull request by ChristophWurst**
Backport of https://github.com/nextcloud/server/pull/17939

- [ ] Backport *this PR* to stable 16
- [ ] Backport *this PR* to stable 15

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by gary-kim — APPROVED** [review]

**Comment by skjnldsv** [comment]
Ah well, we should not need 15 as this is EOL

**Comment by skjnldsv** [comment]
Care to manually backport to stable16 @rullzer :)

**Pull request merged**
