### PR TITLE
[stable10] Add app icons for Comments and Tags

### PR DESCRIPTION
**Pull request by MariusBluem**
Backport of #579 

cc @jancborchardt @ChristophWurst @nextcloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
@mar1u5 usually we backport the commits by using `git cherry-pick <commit id>`. ;) That makes it easier to verify it’s the same commit. :)

**Comment by ChristophWurst** [comment]
:+1:

**Comment by mar1u5** [comment]
@jancborchardt Ah... Okay 😁 Will do this in the future 😉

**Comment by ChristophWurst** [comment]
> @mar1u5 usually we backport the commits by using git cherry-pick <commit id>. ;) That makes it easier to verify it’s the same commit. :)

right. @mar1u5 please use cherry-pick instead ;-)

**Comment by mar1u5** [comment]
Uhmm... Time to read some git documentation stuff 😅 For now, I do not trust myself in doing that correctly 😁

**Comment by nickvergessen** [comment]
@mar1u5 

```
git fetch origin master
git fetch origin stable10
git checkout stable10
git checkout -b backport-<pull request id>-10
git cherry-pick <commit id>
git push origin backport-<pull request id>-10
```

And then send a PR from `backport-<pull request id>-10` against `stable10`

**Comment by nickvergessen** [comment]
For now :+1: 

Btw app id as well as `app` are loaded as icons, it seems?

**Comment by schiessle** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Sadly I have no idea, why scrutinizer doesn't start the job. The hook is properly send (with a 200 from scrutinizer) but it doesn't show up in the list of jobs at scrutinizer-ci.org 🙈 

I will merge this now.

**Pull request merged**
