### PR TITLE
Enforce no notnull for boolean to store false

### LINKED ISSUE #24083: Improve error message for not existing column
Hello guys,
while upgrading from 17.0.1.10.1 to 18.0.10.2 the following error message occured. 

For context:
`Occured error: "InvalidArgumentException: Column name \"iqmUw_flow_operations\".\"entity\" is NotNull, but has empty string or null as default."`

It happens here:
https://github.com/nextcloud/server/blob/35be4fdb019da658a824f41dc4bf0f415c032cb8/lib/private/DB/MigrationService.php#L519

After a look in the source code i found that the real reason for this error is a missing column not else.
I think it would be a good improvement to change this message to:

`Column <column> with <type> in <table> not found`

I was able to solve my mistake on my own, but it would certainly be helpful for the future if the message were more meaningful.

Thanks.

Marco

### PR DESCRIPTION
**Pull request by nickvergessen**
Fails until #24053  is in

Fix #24083

### CODE REVIEW

**Comment by rullzer** [comment]
I get this is just how oracle works. But when you hae a boolean field that you can't store false is just somewhat insane.

**Comment by nickvergessen** [comment]
> But when you have a boolean field that you can't store false is just somewhat insane.

Well oracle has no boolean fields, doctrine maps it to an integer with length 1 byte. "You" manually tell it to not allow 0/null, so that's what we do wrapped by doctrine.

**Comment by rullzer** [comment]
> > But when you have a boolean field that you can't store false is just somewhat insane.
> 
> Well oracle has no boolean fields, doctrine maps it to an integer with length 1 byte. "You" manually tell it to not allow 0/null, so that's what we do wrapped by doctrine.

That is somehow more confusing. If doctrine maps it takes an int. Null and 0 are not the same. So if you have a mandatory int field. You can't set it to 0?

**Comment by rullzer** [comment]
Conflicts. BUta lso CI is not happy

**Comment by nickvergessen** [comment]
Rebased, lets see what CI says

**Review by MorrisJobke — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Hm haven't seen those tests failing before so I'd assume that might be a related failure: integration/sharing_features/sharing-v1-video-verification.feature I've retriggered drone once so let's see

**Comment by nickvergessen** [comment]
yeah, talk does not install anymore :(
I will make a PR

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/pull/5445

**Comment by ChristophWurst** [comment]
this should definitely go into our upgrade docs

**Comment by nickvergessen** [comment]
Added to https://github.com/nextcloud/server/issues/26407#issuecomment-814644608

**Pull request merged**
