### PR TITLE
Enhancements : improve most recent global search UI

### LINKED ISSUE #41381: Global search beta follow up
Follow up issues from https://github.com/nextcloud/server/pull/40823

### TODO

**High priority:**
- [x] Typing in the user search filter doesn't show all the users, it seems that it shows only the preloaded ones
- [x] When filtering the local view (e.g. users) it's impossible to reset the view. When reopening the search modal, it should be possible to reset the search.
- [x] Search result links that should be improved to be actual links for a11y reasons

**Other:** 
- [x] Icon inversion which does not work well now since icons come in white or black instead of one consistent color. (Black icons turn white and white icons turn black, leading to to white on white background issues)
- [x] Use the new people filter (selector) that @marcoambrosini is working on (Current people filter not completed) - DONE, however, NcPopover which is used has issues with closing triggers.
- [x] Update back-end API (if ability not already present) to show "Search in App" dynamically.
- [x] Remove person filter
- [x] BUG: Clicking outside the search modal needs two clicks on the magnifier icon to get the modal back.
- [x] BUG: Some app icons are white on white.
- [x] BUG: Modified timestamp bubbles change size on hover, have no pointing cursor.
- [x] BUG: Generally no feedback for no results.
- [x] BUG: Search people has white text on white background.
- [x] BUG: Search people has a tiny user bubble, barely wider than the avatar.
- [x] BUG: Search people No result goes to the top, overlaps other input.
- [x] BUG: Search people has no effect at all. The search string doesn't contain a person identifier.
- [x] Avatars are square. I guess that's because all previews are square so this makes sense *technically*. For a user, this is inconsistent with *avatars*, though
    image
- [x] When previews do not exist (endpoint returns 404) the browser renders a placeholder for the broken image
    Bildschirmfoto vom 2023-11-14 14-23-13
- [x] *x* on apps/person selection changes size on hover
- [x] No space for icons in modified (Fenn-CS : Best handled at component level, migrate to vue lib repo? "Do not reserve space for icon in NcActionButton if no icon is provided"???)
- [x] *x* on apps/person selection should have pointing cursor

image
- [ ] People are not sorted, at least not by name
    image

- [ ] Accidentally clicked the magnifier on mobile and found out it's impossible to close the modal
image

Needs full page reload to get back to the content.

### PR DESCRIPTION
**Pull request by nfebe**
- Fixes remove person filter/chip when applied
- Close person searchable filter via workaround

Resolves : https://github.com/nextcloud/server/issues/41381

### TODO

- [x] Icon inversion which does not work well now since icons come in white or black instead of one consistent color. (Black icons turn white and white icons turn black, leading to to white on white background issues)
- [x] Use the new people filter (selector) that @marcoambrosini is working on (Current people filter not completed) - DONE, however, NcPopover which is used has issues with closing triggers.
- [x] Update back-end API (if ability not already present) to show "Search in App" dynamically.
- [x] Remove person filter not possible

From @ChristophWurst

- [ ] BUG: Clicking outside the search modal needs two clicks on the magnifier icon to get the modal back.
- [x] BUG: Some app icons are white on white.
- [x] BUG: Modified timestamp bubbles change size on hover, have no pointing cursor.
- [x] BUG: Generally no feedback for no results.
- [ ] BUG: Search people has white text on white background.
- [ ] BUG: Search people has a tiny user bubble, barely wider than the avatar.
- [ ] BUG: Search people No result goes to the top, overlaps other input.
- [x] BUG: Search people has no effect at all. The search string doesn't contain a person identifier.

### CODE REVIEW

**Comment by marcoambrosini** [comment]
- [ ] filter buttons justified to the left
- [ ] Text in people regular not bold
- [ ] Empty content vertically centered
- [ ] No space for icons in modifyed
- [ ] Apply range primary to the right 
- [ ] Date range filter -> custom date range
- [ ] Apply range -> Search in date range
- [ ] Files should be the first search result
- [ ] 4px gap between all the elements in the input, filters, tags
- [ ] Icons shouldn’t be withe in filter tags (in regular theme)
- [ ] Contacts filter shouldn’t be available if contacts app is not available 
- [ ] Add empty content when no results (also clear search button)
- [ ] Broken folder icon in files results
- [ ] Messages: avatar in circles not squares
- [ ] Mail previews not right 
- [ ] “Search in app” is only available for a few apps

**Comment by Altahrim** [comment]
## Performance
- [ ] `/providers` should be called only when user interact with the search, not on every page load

## UI
- [ ] "Modified" button should be renamed as we are not always searching on a modification date

**Review by AndyScherzinger — APPROVED** [review]
can't judge, but 👍 for merging the improvements for beta3 build

**Comment by Fenn-CS** [comment]
FYI : @blizzz and others, open items on this ticket would be moved to the a new PR and issue would open (or re-opened).

_For beta3 merge considerations_

**Review by Pytal — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Pull request merged**
