### PR TITLE
Handle close GlobalSearchModal gracefully

### PR DESCRIPTION
**Pull request by nfebe**
Sorts out re-opening errors, such as needing two clicks after clicking outside, or modal flashes.

-------------------

The current close infrastructure modifies a prop which has no real effect aside bugs.

In addition, calling the `NcModal.close()` as the primary way to close the search modal instead of using the states defined in `GlobalSearch` view causing re-open bugs (Modal cannot open, needs to click twice, and other weird stuff).

Contributes to https://github.com/nextcloud/server/issues/41381

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Code looks good. Didn't test

**Review by artonge — APPROVED** [review]
I think that using the `.sync` modifier can help in such cases: https://v2.vuejs.org/v2/guide/components-custom-events.html#sync-Modifier
But code looks good like that

**Review by AndyScherzinger — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
drone error unrelated

**Pull request merged**
