### PR TITLE
Move OC.Plugins, OC.msg and OC.Notification to the server bundle

### PR DESCRIPTION
**Pull request by ChristophWurst**
This does not reduce the number of requests but slims down the dreaded `js.js` and brings the code into a maintainable format.

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Still works 👍

**Review by rullzer — APPROVED** [review]
Quick smoke tests did not do :boom:

**Comment by ChristophWurst** [comment]
jsunit isn't happy

**Comment by ChristophWurst** [comment]
The problem was that webpack hides exported functions behind es5 getters and sinon does not support them yet: https://github.com/sinonjs/sinon/issues/1762. I use https://github.com/webpack/webpack/issues/6979#issuecomment-379414342 as solution. It's not ideal as webpack can't do all optimizations but the current bundle did not grow in size.

**Comment by ChristophWurst** [comment]
:popcorn: https://drone.nextcloud.com/nextcloud/server/15387/264

**Comment by MorrisJobke** [comment]
> 🍿 https://drone.nextcloud.com/nextcloud/server/15387/264

💥

**Comment by ChristophWurst** [comment]
Yeah … I have to investigate.

> Can't find variable: oc_userconfig in core/js/dist/main.js

is what I see a lot. But that variable is set via php and I assume we add a stub for tests somewhere. I don't get how this changed in this PR.

**Comment by ChristophWurst** [comment]
I have to do this a bit differently.

**Pull request closed without merging**
