### PR TITLE
Use proper return function

### PR DESCRIPTION
**Pull request by LukasReschke**
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

@rullzer Please test.
@nickvergessen Can you check if that is what the code was intended to do?

### CODE REVIEW

**Comment by nickvergessen** [comment]
👍

**Comment by nickvergessen** [comment]
@ChristophWurst @MorrisJobke quick review

**Comment by MorrisJobke** [comment]
:+1:

**Comment by ChristophWurst** [comment]
LGTM

**Pull request merged**
