### PR TITLE
[stable27] Auto set password for new email shares

### PR DESCRIPTION
**Pull request by nfebe**
Manual backport : #40533

### CODE REVIEW

**Review by sorbaugh — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by blizzz** [comment]
@Fenn-CS jsunit and PHP linter are failing

**Comment by Fenn-CS** [comment]
> @Fenn-CS jsunit and PHP linter are failing

Not sure why, no PHP files where touched and no specific lint errors are seen. 

However, I have rebased, let's see.

**Comment by blizzz** [comment]
Right, the linter is unrelated

**Comment by blizzz** [comment]
tests that failed previously succeed now.

**Pull request merged**
