### PR TITLE
Do not clear new user form on failure

### PR DESCRIPTION
**Pull request by skjnldsv**
- And focus the failed input! :tada: 
Fix #11515

@nextcloud/designers

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@skjnldsv Could you recompile the vue app?

**Review by ChristophWurst — APPROVED** [review]
Looks good!

**Comment by skjnldsv** [comment]
@skjnldsv rebase

**Comment by MorrisJobke** [comment]
Acceptance tests fail:


```
  Scenario: create folder in a public editable shared folder        # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:207
    Given I act as John                                             # ActorContext::iActAs()
    And I am logged in                                              # LoginPageContext::iAmLoggedIn()
    And I create a new folder named "Editable shared folder"        # FileListContext::iCreateANewFolderNamed()
    And I close the details view                                    # FilesAppContext::iCloseTheDetailsView()
    And I see that the details view is closed                       # FilesAppContext::iSeeThatTheDetailsViewIsClosed()
    And I share the link for "Editable shared folder"               # FilesAppContext::iShareTheLinkFor()
    And I set the shared link as editable                           # FilesAppContext::iSetTheSharedLinkAsEditable()
    And I write down the shared link                                # FilesAppContext::iWriteDownTheSharedLink()
      Element is no longer attached to the DOM
      For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
      Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      System info: host: '0a91777a3a8d', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-38-generic', java.version: '1.8.0_91'
      Driver info: driver.version: unknown (WebDriver\Exception\StaleElementReference)
    When I act as Jane                                              # ActorContext::iActAs()
    And I visit the shared link I wrote down                        # FilesSharingAppContext::iVisitTheSharedLinkIWroteDown()
    And I see that the current page is the shared link I wrote down # FilesSharingAppContext::iSeeThatTheCurrentPageIsTheSharedLinkIWroteDown()
    And I create a new folder named "Subfolder"                     # FileListContext::iCreateANewFolderNamed()
    Then I see that the file list contains a file named "Subfolder" # FileListContext::iSeeThatTheFileListContainsAFileNamed()
```

**Comment by MorrisJobke** [comment]
> Acceptance tests fail:

Ah no - this is unrelated to the changes in here. Either a regression on master or a false positive. 🙈

**Pull request merged**
