### PR TITLE
[stable18]  Allow to edit admin/own user in the user management 

### LINKED ISSUE #18530: Editing my user via user managment not possible
### Steps to reproduce
1. Login as Admin
2. Go to user management
3. Try to change my quota

### Expected behaviour

I can change the quota.

### Actual behaviour

I can not change to quota for admin. It's possible to change the quota for other users.

Peek 2019-12-22 12-42

cc @nextcloud/designers

### LINKED ISSUE #18964: Current user cannot edit groups (18RC2)
### Steps to reproduce
1. Open user management, all users except logged-in user have "Edit"-pencil icons
2. Try to add the current (in my case admin) user to another group

### Expected behaviour
As logged-in (admin) user, I should be able to add myself to extra groups.

### Actual behaviour
As logged-in (admin) user, I cannot edit my group memberships.

### relevant Server configuration
**Nextcloud version:** 18.0.0 RC2, updated from 17.0.2, originally installed from nextcloud.com/install
**Signing status:**: No errors have been found.

### LINKED ISSUE #19004: NC18 - can not change own passwd / group
hi,
i have made fresh install of nextcloud 18 on my own debian 10 server.
i can not change my own groups / passwd etc. if i log in as user1 (admin)
so i create a new user (user2) with admin privilegs and log in as user2
now i can not change user2 own groups / passwd etc...
but from user1 i can change all now
so login as user1 again i can change groups + passwd only from user2
but not my own (user1)...
this must be a bug ?

nextcloud/index.php/settings/users

### LINKED ISSUE #19072: Can not change admin settings
Good morning, when i go to the settings users, i can modify all settings but not mine, the admin user.

So i can't join any group, change my quota etc.

Nextcloud : v18

### Steps to reproduce
1. Go to settings

### Expected behaviour
Change admin (my) settings

### Actual behaviour
Link for change settings is not showing

### Server configuration

**Operating system:**
Nextcloud docker V18

### PR DESCRIPTION
**Pull request by juliusknorr**
Partly backport of #18555 

- Fix own user editing (Fixes #18530, Fixes #18964, Fixes #19004, Fixes #19072)
- Fix height of user rows
- Fix missing submit button in the display name field

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant:

**Review by skjnldsv — APPROVED** [review]

**Comment by acs-ferreira** [comment]
@juliushaertl I've installed daily release and row height seems not fixed, at least with 2 users only. Here, the height of 3 rows is about 60% of my screen height.

image

When compared to **17.0.4**...

image

**Comment by juliushaertl** [comment]
@acs-ferreira Which daily exactly and on which browser? Could you open a new issue with the details as I cannot reproduce on 18/master: 
image

**Comment by acs-ferreira** [comment]
Well, we have a test instance on the update channel `daily`. Today it seems good 👍 
image

**Comment by juliushaertl** [comment]
Ok, thanks for the update. Maybe the last build then just had the pr included yet. :wink:

**Comment by daeavelwyn** [comment]
Hi here,
Sorry but ssue still persits on my side. I can't manage users and groups

Capture

my configuration :
nextcloud  '18.0.3'; build'2020-03-11T14:54:25+00:00 93cae9d2d17112084c882df902b31604151669c0';

**Comment by acs-ferreira** [comment]
@daeavelwyn wait for the next release, the PR will included.

**Comment by daeavelwyn** [comment]
@acs-ferreira : ok, so, as I can't manage users, I'm actually migrating from 16.0.1.1 to 18.0.3 can I safely exporrt/import database to get my users in the 18.0.3 ? I looked for clear documentation but can't find a clear answer :-/

**Comment by acs-ferreira** [comment]
@daeavelwyn You can manage users as usual, you just can't manage yourself.
_(please go to https://help.nextcloud.com if you need further assistance on this)_

**Comment by JB1985** [comment]
I upgraded to version 18.0.4, but I still can't change my own settings.

The User test000 is a Group Admin and cant change the own settings.

Nextcloud-settings

**Comment by JB1985** [comment]
Admin or Groupadmin? With Groupadmin is not working to edit the own account.

**Comment by GretaD** [comment]
Ah right, because this ticket is related to admin only, i misread it. Please, can you open an issue for group admin?

**Pull request merged**
