### PR TITLE
Add CI to stable9 🚀

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Comment by mar1u5** [comment]
Off-Topic: Emojis are not working in the title 😜 ...but you can just copy the emojis if you make such one in an comment, and then you can drop it into the title 😉 @LukasReschke

**Comment by LukasReschke** [comment]
> Off-Topic: Emojis are not working in the title 😜 ...but you can just copy the emojis if you make such one in an comment, and then you can drop it into the title 😉 @LukasReschke

Hehe. Adjusted now :)

**Comment by LukasReschke** [comment]
Passing => Merge.

**Comment by mar1u5** [comment]
...was this a backport of #17?

**Comment by LukasReschke** [comment]
> ...was this a backport of #17?

Yup. We want to have the CI running as soon as possible. At the moment our Drone setup only executes autotest with SQLite but we're trying to get getting more added soon.

Any help welcome, if you're a Docker friend it shouldn't be too hard ;-) For example there is also https://github.com/owncloud/core/blob/master/autotest-js.sh

**Pull request merged**
