### PR TITLE
[12] Improve performance when dealing with large numbers of shares

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/nextcloud/server/pull/10724

### CODE REVIEW

**Comment by icewind1991** [comment]
failing tests in codecov being unavailable

**Review by rullzer — APPROVED** [review]

**Comment by icewind1991** [comment]
@MorrisJobke @schiessle please review

**Review by MorrisJobke — APPROVED** [review]
🐘

**Comment by MorrisJobke** [comment]
All failures are due to a codecov.io outage -> merging.

**Pull request merged**
