### PR TITLE
[stable12] Top bar buttons in share view are wrong positioned

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #5920

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Gallery part: https://github.com/nextcloud/gallery/pull/311

**Review by skjnldsv — APPROVED** [review]
👍 of course

**Review by nickvergessen — APPROVED** [review]
Looks better, although the Download arrow and the label are not aligned yet

**Comment by MorrisJobke** [comment]
> Looks better, although the Download arrow and the label are not aligned yet

See nextcloud/gallery#311 😉

**Comment by pixelipo** [comment]
Thanks @MorrisJobke - I didn't have time to create this backport myself...

**Pull request merged**
