### PR TITLE
[stable25] Bump @nextcloud/vue from 7.2.0 to 7.3.0

### PR DESCRIPTION
**Pull request by PVince81**
Like https://github.com/nextcloud/server/pull/35996 for stable25

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by PVince81** [comment]
no need to recompile, I manually compiled this locally already (unlike dependabot)

**Comment by artonge** [comment]
Ah it's node tests that are failing

**Comment by artonge** [comment]
Need to update snapshots

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
Rebased + updated snapshots

**Comment by Pytal** [comment]
CI failure unrelated

**Pull request merged**
