### PR TITLE
Add Psalm type for the bootstrap registration context

### PR DESCRIPTION
**Pull request by ChristophWurst**
This can potentially catch a few bugs with wrong class strings.

Typed code is good code.

Kind-of follow-up to https://github.com/nextcloud/server/pull/23310 but not necessarily related.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Bildschirmfoto von 2020-10-12 11-30-40

huh, this unveiled the first API errors :rocket: :heart:

**Review by MorrisJobke — APPROVED** [review]
❤️

**Review by kesselb — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@ChristophWurst Psalm is 20+ only anyways

**Pull request merged**
