### PR TITLE
Don't break when one remote share is down

### PR DESCRIPTION
**Pull request by nickvergessen**
getFileInfo can also return false
Found while trying to improve on #14797

### CODE REVIEW

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/445274cf93dbae31c6995008dcc0f9834c05d9ca/apps/files_sharing/js/sharedfilelist.js#L308-L318

Please consider to update the code here. Right now all those fields are expected.

**Comment by nickvergessen** [comment]
Sure we can add something like:
```php
			$share['mimetype'] = 'httpd/unix-directory';
			$share['mtime'] = 0;
			$share['permissions'] = Constants::PERMISSION_READ | Constants::PERMISSION_DELETE;
			$share['type'] = 'dir';
			$share['file_id'] = 0;
```

But the main issue stays. The info is wrong and deleting doesnt work either. Also I don't see a problem in my console/UI without that (apart from no mimetype icon being displayed).

I think someone needs to have a proper look and handle unavailable shares in a much better fashion globally. For now getting rid of the broken part of the response is good enough for me.

**Review by rullzer — APPROVED** [review]
looks sane

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
