### PR TITLE
fix User Counts updates on user add/remove

### LINKED ISSUE #27607: Settings - counts of users are not incremented after user add
(Nextcloud v21.0.2)

How to reproduce:

Go to users, observe count of All and Admins. Then add normal user (or admin) and after confirming, you will se, that counts of users are not updated. Page refresh (or leaving, coming back there) makes numbers to update. I know, minor thing - but can cause confusion...

Thanks for your attention :-)
PB

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/27607

Superseds https://github.com/nextcloud/server/pull/31484

Signed-off-by: Petre T <petre.tudor@dorkfarm.com>

### CODE REVIEW

**Review by petre2dor — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by petre2dor** [comment]
Can someone here please assist me with fixing the failed checks?

I have no clue how to handle this fail:
image

**Comment by artonge** [comment]
@petre2dor you'll also need to fix DCO: https://github.com/nextcloud/server/pull/31697/checks?check_run_id=5723583117

**Comment by petre2dor** [comment]
> @petre2dor you'll also need to fix DCO: https://github.com/nextcloud/server/pull/31697/checks?check_run_id=5723583117

Hey @artonge,
I fixed the DCO a couple times using the instructions there and it passed, but now I keep getting all kinds of conflicts and after I fixed them I can't do 'git rebase --continue' because there are no changes, so I'm stuck. 
Is there an way out of this?

**Comment by artonge** [comment]
> > @petre2dor you'll also need to fix DCO: https://github.com/nextcloud/server/pull/31697/checks?check_run_id=5723583117
> 
> Hey @artonge, I fixed the DCO a couple times using the instructions there and it passed, but now I keep getting all kinds of conflicts and after I fixed them I can't do 'git rebase --continue' because there are no changes, so I'm stuck. Is there a way out of this?

Ok, I am handling it :)

**Comment by artonge** [comment]
Thanks for the fix @petre2dor !

**Pull request merged**
