### PR TITLE
Revert "Set umask before operations that create local files"

### LINKED ISSUE #29041: Created files/directories on local storage ignore web server umask and therefore have incorrect permissions set
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set Apache umask to 0007 in /etc/apache2/envvars or equivalent
2. Create a file or directory on local storage

### Expected behaviour
Created files/directories should observe Apache's umask,
 i.e. if Apache's umask is 0007 and if I have a directory with permissions
`drwxrwsr-x me mygroup`

And I create a file within that directory in nextcloud, it should have the permissions
`-rw-rw---- www-data mygroup`

and I as member of mygroup should be able to write to the file.

My use case is that I access files in local storage externally as well as via Nextcloud. It should be possible for me (as a member of the group the files are created under) to locally edit a file or write to a directory created via Nextcloud.

### Actual behaviour
Apache's umask is ignored and the file is created with rw-r--r-- permissions therefore I can't write to it from outside of nextcloud.

Note that as well as not being group writeable, they are also other-readable, which could be unexpected.

This issue didn't happen in earlier versions of nextcloud - it appears to have been introduced by this commit https://github.com/nextcloud/server/commit/e5dc1a8085226492b6d323142381fd163451c06d which forces umask to be 022. Also this replaced an earlier commit https://github.com/nextcloud/server/commit/d182043e83a277a7f95e4d689b1e96d7b1b9a6fb which forcibly set permissions on created directories to 755.

### Server configuration

**Operating system:** Ubuntu 20.04.3

**Web server:** Apache

**Database:** mariadb

**PHP version:** 7.4.3

**Nextcloud version:** Nextcloud 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** tarball

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - bruteforcesettings: 2.2.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
  'dbtype' => 'mysql',
  'version' => '22.2.0.2',
</details>
the rest is not relevant

**Are you using external storage, if yes which one:** yes - local

**Are you using encryption:** no but not relevant

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** not relevant

**Operating system:** not relevant

### Logs
not relevant

### PR DESCRIPTION
**Pull request by bgottschall**
This reverts the pull request #25280, 'fixing' undescribed issues with "other php stuff". It actually forces folder and file permissions on all files created by nextcloud from within the PHP code which should violate common coding standards in my opinion.

The merge completely ignores the umask from the system that is set by an administrator for various reasons. Just by mentioning one example when someone uses an external folder over the external files plugin, nextcloud will create folder and files there without the group having write permissions which breaks with many NAS setups e.g. Unraid (#29041).

Instead of fixating the servers file and folder permissions within nextcloud ignoring settings carefully chosen by the administrator, the "other php stuff" should be fixed.

Fix #29041

### CODE REVIEW

**Comment by acsfer** [comment]
What about https://github.com/nextcloud/server/issues/29041#issuecomment-932990080 instead of just reverting? 🤔

**Comment by bgottschall** [comment]
> What about [#29041 (comment)](https://github.com/nextcloud/server/issues/29041#issuecomment-932990080) instead of just reverting? thinking

This comment only takes the group and other permission portion of the umask and forces the owner umask to 0. While it make sense from the nextcloud perspective to make sure that it always has read/write permissions on the files it creates it is a unecessary change to begin with. A process umask is set by whoever starts it (systemctl service e.g.) which is typically 022. 
If a system administrator chooses a different mask he should be allowed to and nextcloud should not change it. If the administrator chooses a mask that crashes with nextcloud, it is a configuration problem and it should not be nextcloud task to alleviate this potential wrong doing. One could add in the adminstrator documentation that nextcloud expects a umask that preserves read/write permissions of files and folders, but hardcoding this safeguard into the php code?

**Comment by bgottschall** [comment]
I've removed the chmod inside mkdir, which is a line that is also not necessary. 

Referring to the PHP doc [https://www.php.net/manual/en/function.mkdir.php](https://www.php.net/manual/en/function.mkdir.php) mkdir respects the umask of the system, meaning the folders are created with the 755 permissions if the umask is 022 for example. Another aspect is that mkdir is called with recursive set to true. Setting only the last directory using chmod is incomplete as all parent directories that might have been created as well would not be affected.

**Review by come-nc — COMMENTED** [review]
Maybe we could add a check in https://github.com/nextcloud/server/blob/master/apps/settings/lib/Controller/CheckSetupController.php that checks the umask? But maybe this is not possible if umask can be set differently in each storage or folder, not sure.

**Comment by bgottschall** [comment]
> Maybe we could add a check in https://github.com/nextcloud/server/blob/master/apps/settings/lib/Controller/CheckSetupController.php that checks the umask? But maybe this is not possible if umask can be set differently in each storage or folder, not sure.

The umask is a process configuration (not folder or storage related), however the process can change its umask at any given time. That means php code (apps/extensions) could change the umask simply with `umask(...)`. I don't see a reason why they ever should do that and if, they should fix it there or revert it back to the process default after being finished. 
Though if one changes the umask in the php code, it will only be changed for the local execution context and the next request starts with the process default again.

**Comment by come-nc** [comment]
> > Maybe we could add a check in https://github.com/nextcloud/server/blob/master/apps/settings/lib/Controller/CheckSetupController.php that checks the umask? But maybe this is not possible if umask can be set differently in each storage or folder, not sure.
> 
> The umask is a process configuration (not folder or storage related), however the process can change its umask at any given time. That means php code (apps/extensions) could change the umask simply with `umask(...)`. I don't see a reason why they ever should do that and if, they should fix it there or revert it back to the process default after being finished. Though if one changes the umask in the php code, it will only be changed for the local execution context and the next request starts with the process default again.

So if it is the same for the whole process we can test it in CheckSetupController and warn if it is a mask that will cause problem (if it will disallow editing what we create). Ideally with a link to the documentation about this.

**Comment by bgottschall** [comment]
> > > Maybe we could add a check in https://github.com/nextcloud/server/blob/master/apps/settings/lib/Controller/CheckSetupController.php that checks the umask? But maybe this is not possible if umask can be set differently in each storage or folder, not sure.
> > 
> > 
> > The umask is a process configuration (not folder or storage related), however the process can change its umask at any given time. That means php code (apps/extensions) could change the umask simply with `umask(...)`. I don't see a reason why they ever should do that and if, they should fix it there or revert it back to the process default after being finished. Though if one changes the umask in the php code, it will only be changed for the local execution context and the next request starts with the process default again.
> 
> So if it is the same for the whole process we can test it in CheckSetupController and warn if it is a mask that will cause problem (if it will disallow editing what we create). Ideally with a link to the documentation about this.

Added a check, would appreciate if somebody could take over the frontend including testing as my setup doesn't allows testing currently and I haven't touched anything on the frontend yet.

**Comment by bgottschall** [comment]
A bit unfortunate that this is not moving forward. I mean there is a missing frontend message of the umask server check but this pull request is mainly about removing faulty code not introducing something new in the server.

**Comment by PVince81** [comment]
obsoleted by https://github.com/nextcloud/server/pull/32723

**Pull request closed without merging**
