### PR TITLE
don't try to log the currently logged in user, this fails on cronjobs…

### LINKED ISSUE #143: PHP error on cron jobs (trashbin.php)
### Steps to reproduce
1. Configure system cron jobs

### Expected behaviour
No fatal php errors should be triggered.

### Actual behaviour
Fatal error is sent by cron :
`PHP Fatal error:  Call to a member function getUID() on null in /.../apps/admin_audit/lib/actions/trashbin.php on line 49`

line is : 
`'user' => $this->userSession->getUser()->getUID()`

### Server configuration
**Operating system**:
Debian GNU/Linux 8.5 (jessie)

**Web server:**
Apache 2.4

**Database:**
Mysql 5.5

**PHP version:**
PHP 5.6.22

**Nextcloud version:** (see Nextcloud admin page)
9.0.50.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from ownlcloud

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-9.0.50.zip

**Signing status (Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_versions
  - provisioning_api
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "forcessl": true,
        "defaultapp": "files",
        "appstoreenabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "127.0.0.1",
        "appcodechecker": false,
        "updatechecker": true,
        "log_type": "owncloud",
        "loglevel": 3,
        "datadirectory": "...\/owncloud",
        "asset-pipeline.enabled": false,
        "has_internet_connection": true,
        "apps_paths": [
            {
                "path": "...\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "...\/apps-extra",
                "url": "\/apps-extra",
                "writable": true
            }
        ],
        "instanceid": "50ae344a0fcbe",
        "version": "9.0.50.0",
        "maxZipInputSize": 536870912,
        "allowZipDownload": true,
        "maintenance": false,
        "theme": "",
        "trusted_domains": [
            "cloud.sbaron.fr"
        ],
        "mail_from_address": "no-reply",
        "mail_domain": "",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
```
n/a
```

#### Nextcloud log (data/owncloud.log)
```
{"reqId":"5faYdfqPMSFzBcPg7RCC","remoteAddr":"","app":"core","message":"starting upgrade from 9.0.2.2 to 9.0.50.0","level":0,"time":"2016-06-16T17:48:42+00:00","method":"--","url":"--","user":"--"}
{"reqId":"lNNvoh8ZM1EnN7GaO6Db","remoteAddr":"","app":"PHP","message":"Call to a member function getUID() on null at \/home\/htdocs\/cloud.sbaron.fr\/apps\/admin_audit\/lib\/actions\/trashbin.php#49","level":3,"time":"2016-06-16T18:00:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"aoGZO0Mn8fOCjuKevlYA","remoteAddr":"","app":"PHP","message":"Call to a member function getUID() on null at \/home\/htdocs\/cloud.sbaron.fr\/apps\/admin_audit\/lib\/actions\/trashbin.php#49","level":3,"time":"2016-06-16T18:45:02+00:00","method":"--","url":"--","user":"--"}

```

### PR DESCRIPTION
**Pull request by schiessle**
don't try to log the currently logged in user, this fails on cronjobs. The users are logged anyway.

fix https://github.com/nextcloud/server/issues/143#issuecomment-226990570

@LukasReschke @s7b4 @hostingnuggets please review/try. This should fix the logging issue with the trash bin.

### CODE REVIEW

**Comment by schiessle** [comment]
cc @karlitschek should be backported to Nextcloud 9

**Comment by karlitschek** [comment]
please backport 👍

**Comment by LukasReschke** [comment]
LGTM

**Comment by schiessle** [comment]
stable9: https://github.com/nextcloud/server/pull/203

**Pull request merged**
