### PR TITLE
Submit comments with Enter and use Shift+Enter for new lines

### PR DESCRIPTION
**Pull request by danxuliu**
Imported from nextcloud/spreed#474 as [requested by @jancborchardt](https://github.com/nextcloud/spreed/issues/463#issuecomment-346340427).

### CODE REVIEW

**Comment by nickvergessen** [comment]
I still think we shouldn't do this, because on comments people should write longer, not more often...

**Comment by blizzz** [comment]
> I still think we shouldn't do this, because on comments people should write longer, not more often...

Seconded, I am not convinced of the change.

**Comment by danxuliu** [comment]
>  Seconded, I am not convinced of the change.

[Me neither](https://github.com/nextcloud/spreed/issues/463#issuecomment-345838364); I am just granting @jancborchardt a wish :-P

**Comment by jancborchardt** [comment]
As commented on the other issue in Talk:

> The issue atm is more that not really a lot of people know we have Comment functionality, so we need to make it as dead-simple to use as possible.

Also, we should have this consistent with the Talk app.

**Review by jancborchardt — APPROVED** [review]

**Comment by jancborchardt** [comment]
(That is also, every time I used comments myself or had it tested by other people, when they used enter they were confused as to why it didn't submit. That's also why I asked for the change in Talk too.
Saying "Comments should be longer" is wishful thinking but not how people actually use it.)

**Comment by nickvergessen** [comment]
It used to be a two lines textarea, but then our designer wanted a self-growing one-line div-element. A single line suggests enter to be send. So yes, currently it does not match your expectations, because you changed one part but not the other. I still think we should just make the input-div a bit bigger then it is clear that enter will create new lines.

**Review by MorrisJobke — APPROVED** [review]

**Comment by jancborchardt** [comment]
@danxulius @MorrisJobke what about the failures? I'd lile to merge this. :)

**Comment by jancborchardt** [comment]
@danxuliu  @MorrisJobke what about the failures? I'd lile to merge this. :)

**Comment by danxuliu** [comment]
>  what about the failures?

Basically it is complaining that no unit tests were added. And it is right :-O

>  I'd lile to merge this. :)

Give me a second to add the tests ;-)

**Comment by danxuliu** [comment]
That was a long second... :-P 

Anyway I could not add proper unit tests for entering a new line instead of posting a comment when _shift+enter_ was used, as apparently the exact behaviour in that case depends on the browser. PhantomJS does not seem to handle key events on content editable divs, so the test only verifies that the default behaviour would have been executed when typing _shift+enter_. Better than nothing...

**Comment by danxuliu** [comment]
I have noticed that pressing Enter when the autocomplete popover for mentions was shown caused the comment to be submitted instead of the mention to be completed; I have fixed that in the last commit.

**Comment by danxuliu** [comment]
I have amended the last commit to include unit tests too for pressing Enter when the autocomplete popover for mentions is shown (it was trickier than expected... but it is done now ;-) ).

**Comment by MorrisJobke** [comment]
All CI failures are unrelated.

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
