### PR TITLE
Properly redirect if accessing invalid file though /f/ entrypoint

### PR DESCRIPTION
**Pull request by juliusknorr**
Make sure we redirect to the files app and show a proper error message instead of a technical page caused by the NotFoundException.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
make sense!

**Review by ChristophWurst — APPROVED** [review]
:+1:

**Comment by kesselb** [comment]
Could you consider a backport?

**Comment by juliushaertl** [comment]
No backport for stable15 needed, it has been broken with 16 only.

**Pull request merged**
