### PR TITLE
Add support for a highlighted navigation counter

### PR DESCRIPTION
**Pull request by nickvergessen**
As per https://github.com/nextcloud/spreed/pull/824

Could also be used for the "updates available" section in the apps management.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Actually this breaks with `999+`, @skjnldsv can you take a look?

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Failure unrelated :)

**Comment by juliushaertl** [comment]
> Actually this breaks with 999+, @skjnldsv can you take a look?

Still an issue. @skjnldsv Mind to have a look? I'm not sure if it has any downsides to just remove the `width: 44px !important` for the counters.

**Comment by nickvergessen** [comment]
> Okay, the highlighted class must now go to the counter element

Will adjust the docs, thanks!

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Review by danxuliu — COMMENTED** [review]
I said that it worked too fast... @juliushaertl is right, the [`width: 44px !important`](https://github.com/nextcloud/server/blob/dbfd00897ffed6bb09a9527401af081f97a83b18/core/css/apps.scss#L412) is still problematic with more than 3 characters, at least in the _Users_ app.

Edit: to give a little more context, the problem is also related to the use of `box-sizing: border-box` in `#app-navigation *`; due to the border-box sizing the 44px of width include the content and the padding, so the extra padding added for the highlight reduces the available space for the content.

**Comment by skjnldsv** [comment]
@danxuliu please update review :)

**Comment by danxuliu** [comment]
@skjnldsv As far as I can tell my review is still _Approved_; the comment after it does not change that. But I can request changes if you want, I am pretty sure that I can find something to complain about :-P

**Comment by danxuliu** [comment]
>  I fixed the display, did you try again?

Yes, yes, it can show up to five characters now ;-)

Although with five characters then there is no space between the counter and the right edge of the navigation bar... but space is finite, and it is impossible to have enough room for any number of characters (in fact the non-highlighted counter can hold up to four characters instead of five) so, as I said, approved :+1: ;-) (see? I can also complain and approve at the same time :-P ).

**Comment by skjnldsv** [comment]
That's why we have the limit filter in the documentations :)
Let's merge this :)

**Pull request merged**
