### PR TITLE
get only vcard which match both the address book id and the vcard uri

### LINKED ISSUE #229: Addressbooks CardDav Backend "createUid" has a strange behaviour and nearly always finds a conflict
See Code
https://github.com/nextcloud/server/blob/master/apps/dav/lib/CardDAV/CardDavBackend.php#L851

shouldn't this be a ```andWhere``` instead of ```where```?

It is called by createUid and my mysql log shows that owncloud always only queries for the addressbookId instead of addressbookId and uri.

Because of this I cannot create a new Addressbook Entry with this code:

```

$cm = \OC::$server->getContactsManager();
$result = $cm->search($LABEL, array('LABEL')); //Returns nothing as Expected;
$entry = $result[0] || array();

$entry["FN"] = "My Name";
... more stuff ...
$cm->createOrUpdate($entry, $addrbookkey);

```

 * this calles createOrUpdate
 * then runs in the create branch
 * then calls createUid and hangs there

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/nextcloud/server/issues/229

cc @kellertobi91 this should fix your issue, maybe you can verify it?

### CODE REVIEW

**Comment by mar1u5** [comment]
Try to give yourself a approval please 😉

**Comment by schiessle** [comment]
:+1: (just a test)

**Comment by schiessle** [comment]
:+1: (let's hope that it doesn't work)

**Comment by schiessle** [comment]
@mar1u5 seems to work... now two real +1 please :wink:

**Comment by mar1u5** [comment]
:+1:

**Comment by mar1u5** [comment]
It does still work :unamused: ... One approval of you ... And one of me :cry: You should not be able to approve ... Not multiple times ... But also not once if you created the PR by yourself :smiling_imp:

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
@schiessle I guess this should be backported, right?

**Comment by kellertobi91** [comment]
Seems Legit. I cannot check it before Friday, but it looks like the Fix I have made my own.

**Comment by schiessle** [comment]
> @schiessle I guess this should be backported, right?

yes, @karlitschek do you agree?

**Comment by karlitschek** [comment]
absolutely. please backport!

**Pull request merged**
