### PR TITLE
fix new file menu

### LINKED ISSUE #30640: File picker scrolling issues when breadcrumb too long
### Steps

1. Create a set of folders with long names: "first folder > second folder > third folder > fourth folder > fifth folder"
2. Make the window narrow horizontally
3. Open the three dots menu of another entry in the root and pick "move or copy"
4. Navigate into "fifth folder" (or make it so that the "+" button is on the right side of the dialog)
5. Try creating another subdirectory from within the dialog

### Expected result
Able to see the field properly

### Actual result
Field cannot be fully viewed even with horizontal scrolling

### Versions
22.2.0 and git master
image

### Notes
Ideally the breadcrumb should replace itself with an ellipsis so that no scrollbars become visible,
or the dropdown needs to position itself more to the left

### PR DESCRIPTION
**Pull request by skjnldsv**
Fixes https://github.com/nextcloud/server/issues/30640

## After
| Right | Left |
|---|---|
| image | image |

### CODE REVIEW

**Comment by PVince81** [comment]
@skjnldsv mind posting a screenshot also where there's a long breadcrumb that would cause the scrollbar ?
the "after" screenshot is in the root folder instead

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by skjnldsv** [comment]
> @skjnldsv mind posting a screenshot also where there's a long breadcrumb that would cause the scrollbar ? the "after" screenshot is in the root folder instead

image

**Review by szaimen — COMMENTED** [review]
I tested this and in some situations it still happens that the element goes a bit beyond the modal:
image
image

**Comment by szaimen** [comment]
This is ready for review!
How it looks now:
| Right | Left |
|---|---|
| image | image |

**Review by szaimen — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Pull request merged**
