### PR TITLE
Add uid_owner and uid_initiator share tabe indices

### PR DESCRIPTION
**Pull request by rullzer**
For #10926

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by Arvidas** [comment]
if (!$table->hasIndex('owner_index')) 
not if (!$table->hasIndex('uid_owner')) {
and so on

**Comment by MorrisJobke** [comment]
> if (!$table->hasIndex('owner_index'))
> not if (!$table->hasIndex('uid_owner')) {
> and so on

🙈

**Comment by MorrisJobke** [comment]
Thanks for spotting this.

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/nextcloud/server/pull/12312

**Pull request merged**
