### PR TITLE
Fix avatar in file list for users with an @ in the uid

### LINKED ISSUE #19545: displayName not used in the "shared by" Hover
This is an addendum to https://github.com/nextcloud/user_saml/issues/144, which is not implemented fully yet.

### Steps to reproduce
1. Log in with SAML as User A 
2. Logout
3. Login in with SAML as User B (ID: ABCDEFGHIJK@insititution.org, DisplayName: "User B")
4. Create and share some document with User A
5. Logout
6. Login as User A

### Expected behaviour
When hovering over the Sharing link of this document, I expect "Shared by User B"

### Actual behaviour
When hovering over the Sharing link of this document, "Shared by ABCDEFGHIJK@insititution.org" is displayed.

### Server configuration
**Operating system**: Centos 7

**Web server:** ngingx

**Database:** MariaDB10.3

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 15.05

**Where did you install Nextcloud from:** official nextcloud site, .ZIP

**List of activated apps:** SAML authenticaton, Collabora Online,

### PR DESCRIPTION
**Pull request by juliusknorr**
User ids can be email addresses and therefore should not be treated as federated shares.

Steps to reproduce:
- Add a local account with `@` in the user id: `user@example.com`
- Share a file from `user@example.com` to `admin`
- Check the file list

Before:
- The uid is shown

After:
- The avatar is shown as it would be expected for local users

Regex proove: https://regex101.com/r/tw142O/3/

Fixes https://github.com/nextcloud/server/issues/19545

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Make sense

**Review by georgehrke — APPROVED** [review]
Seems reasonable 👍

**Review by wiswedel — APPROVED** [review]

**Comment by juliushaertl** [comment]
Backport in https://github.com/nextcloud/server/pull/19803

**Pull request merged**
