### PR TITLE
fix(ShareApiClients): Maintain meaning of `''` and null for share api cli…

### PR DESCRIPTION
**Pull request by nfebe**
Fix regression from : https://github.com/nextcloud/server/pull/44485

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]

**Comment by ShGKme** [comment]
Should also be backported to 28 and 29 after https://github.com/nextcloud/server/pull/44485 is backported

**Comment by Fenn-CS** [comment]
> Should also be backported to 28 and 29 after https://github.com/nextcloud/server/pull/44485 is backported to 28 and 29

I would fix up? on 29 and 28? Since they are not merged yet? @ShGKme

**Pull request merged**
