### PR TITLE
hide mail share if a cloud share is possible

### PR DESCRIPTION
**Pull request by blizzz**
When a user has both email and a federated cloud id set,  both are shown currently. There are cases where it is desired to user cloud share where possible (thus, email should be possible on the other cases). This is part of discussion to reduce entries of the same user in the share dialog. The change filters out mail entries when remote shares are possible, but does not come with a switch or anything. Email shares are still possible by writing the whole address.

Before:

share-before

After:

share-after

What do you think? @nextcloud/sharing  @nextcloud/designers

### CODE REVIEW

**Comment by tcitworld** [comment]
So I wouldn't be able to share by email with a contact that also has a federated ID by searching their name, I'd have to know their entire email address. 🤔

**Comment by tobiasKaminsky** [comment]
Having this only on web ui means that this must also be done on every client.
I think it is better to simplify it on backend side, so that only the desired share options are returned for an user.

**Comment by blizzz** [comment]
> So I wouldn't be able to share by email with a contact that also has a federated ID by searching their name, I'd have to know their entire email address. thinking

This. Or remove the federated id from the contact. Or create a second addressbook entry. Yes, it is all extra work. In the end it is balancing the pros and cons. The sad truth is, people are overwhelmed of (technical) choices they do not understand.

**Comment by blizzz** [comment]
> Having this only on web ui means that this must also be done on every client.
> I think it is better to simplify it on backend side, so that only the desired share options are returned for an user.

Valid point. I am afraid it is not just the files_sharing dialog calling the files_sharing endpoint to populate the share dialogue however, and other apps might not have support for remote shares. Could be worth another look.

**Comment by tobiasKaminsky** [comment]
In my opinion this should be centralized via files_sharing endpoint.
If needed there can be options like "show remote shares", "simplify way of sharing", which should have sane default values, so that every client (also web ui) provide the same UX.

**Comment by blizzz** [comment]
closing in favor of https://github.com/nextcloud/server/pull/26550

**Pull request closed without merging**
