### PR TITLE
display file list in flexbox

### LINKED ISSUE #20130: Cannot move or copy file when the target path take more than one line
### Steps to reproduce

When moving a file and the target folder has only five element and the path take more than one line, the buttons move along with the scrollbar and the fifth item does not appears:

nextcloud

nextcloud2

### PR DESCRIPTION
**Pull request by rmanibus**
fixes #20130

### CODE REVIEW

**Comment by rmanibus** [comment]
this fix #20130

**Comment by GretaD** [comment]
Thank you @rmanibus for your contribution :) 
The problem with buttons and scrolling is good now, but now the upload button stays always below the path.
**Before the change**
move_before

**After the change**
move

**Comment by rmanibus** [comment]
oh yes I missed that. 
I will try something (sorry I'm not a frontend developer haha)

**Comment by rmanibus** [comment]
Ok so the breadcrumb is an inline flex, I don't see how we can put the add button after the last breadcrumb item without putting it in the same flex context.

This is working if the breadcrumb is less than a line long, but if it is two line long the add button will not be on the same line than the last breadcrumb item.
```
<div style="display: inline-flex; flex-direction:row;">
  <span class="dirtree breadcrumb" style="flex-shrink: 1;">
    <div data-dir="" class="crumb"><a></a></div>
    <div data-dir="/..." class="crumb"><a>long name destination</a></div>
  </span>
  <span class="actions creatable">...</span>
</div>
```
I think the button must be the last breadcrumb item for it to work. Do you see any other solution ?

**Comment by rmanibus** [comment]
The main breadcrumb is also broken if the path is too long

main breadcrumb

**Comment by GretaD** [comment]
> Ok so the breadcrumb is an inline flex, I don't see how we can put the add button after the last breadcrumb item without putting it in the same flex context.
> 
> This is working if the breadcrumb is less than a line long, but if it is two line long the add button will not be on the same line than the last breadcrumb item.
> 
> ```
> <div style="display: inline-flex; flex-direction:row;">
>   <span class="dirtree breadcrumb" style="flex-shrink: 1;">
>     <div data-dir="" class="crumb"><a></a></div>
>     <div data-dir="/..." class="crumb"><a>long name destination</a></div>
>   </span>
>   <span class="actions creatable">...</span>
> </div>
> ```
> 
> I think the button must be the last breadcrumb item for it to work. Do you see any other solution ?

Hey, thank you for rechecking, no, i dont have any better solution tbh.

**Comment by rmanibus** [comment]
so, the breadcrumb shows up correctly but the button is non functioning for now. what do you think of this ? I did not commit the compiled file for now because it is generating a lots of noise, I think you will have to rebuild the JS.

**Comment by rmanibus** [comment]
Fetching the button with detach() effectively preserve all event handlers attached with it (https://stackoverflow.com/questions/29461969/appending-element-and-removing-it-destroys-all-event-handlers-in-jquery). So I think we are good now.

**Comment by rmanibus** [comment]
Do you want me to commit all the generated js ? I dont now why it generated files in the app folder, I only made change in the core.

**Comment by gary-kim** [comment]
You can just comment `/compile amend /` and and @npmbuildbot will come in and compile it for you :).

**Comment by rmanibus** [comment]
hi, can someone review this ?

**Review by skjnldsv — APPROVED** [review]
code looks good
Hopefully we create our own new component for it soon :)

**Review by GretaD — APPROVED** [review]

**Comment by GretaD** [comment]
please squash it and resolve the conflicts. Thank you :+1: 1

**Comment by rmanibus** [comment]
I think we are good !

**Comment by skjnldsv** [comment]
Thanks a lot @rmanibus :hugs:

**Pull request merged**
