### PR TITLE
Do not transfer shares for deleted users

### LINKED ISSUE #28981: Transfer ownership issue failing if recipient of share is deleted
### Steps

0. Create users alice, charles, and dave
1. Login as Alice
2. Create a folder "share_to_deleted"
3. Share the folder with "Dave"
4. Delete "Dave" from oc_users directly (might simulate a deletion from LDAP of sorts)
5. Run "occ files:transfer-ownership alice charles"

### Expected result
The share entry is skipped / deleted

### Actual result
Failure to result

```
% occ files:transfer-ownership alice charles
Validating quota
Analysing files of alice ...
   1 [============================]
Collecting all share information for files and folders of alice ...
   1 [============================]
Transferring files to charles/files/transferred from Alice on 2021-09-28 15-41-45 ...
Restoring shares ...
Could not restore share with id 49:#0 /srv/www/htdocs/server/lib/private/Share20/Manager.php(973): OC\Share20\Manager->generalCreateChecks()
#1 /srv/www/htdocs/server/apps/files/lib/Service/OwnershipTransferService.php(348): OC\Share20\Manager->updateShare()
#2 /srv/www/htdocs/server/apps/files/lib/Service/OwnershipTransferService.php(179): OCA\Files\Service\OwnershipTransferService->restoreShares()
#3 /srv/www/htdocs/server/apps/files/lib/Command/TransferOwnership.php(120): OCA\Files\Service\OwnershipTransferService->transfer()
#4 /srv/www/htdocs/server/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\TransferOwnership->execute()
#5 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#6 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#7 /srv/www/htdocs/server/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#8 /srv/www/htdocs/server/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#9 /srv/www/htdocs/server/console.php(100): OC\Console\Application->run()
#10 /srv/www/htdocs/server/occ(11): require_once('/srv/www/htdocs...')
#11 {main}
1/1 [============================] 100%
```

### Versions
Tested on Nextcloud 21.0.4

- [x] Need to test on master
- [x] Fix if necessary

### PR DESCRIPTION
**Pull request by PVince81**
Whenever a user was deleted but is still recipient of share entries,
delete these entries upon transfer.

Usually such entries would disappear after running cleanup background
jobs.

Fixes https://github.com/nextcloud/server/issues/28981

Acceptance test too tricky to add as we can't skip hooks when deleting a user to prevent share deletion.

### CODE REVIEW

**Review by artonge — APPROVED** [review]
Looks good

**Comment by artonge** [comment]
Could have been nice to find why some shares are not deleted though.

**Review by Pytal — APPROVED** [review]

**Pull request merged**
