### PR TITLE
[stable25] Fix the login log entry

### PR DESCRIPTION
**Pull request by szaimen**
Manual backport of https://github.com/nextcloud/server/pull/36443

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by nickvergessen — DISMISSED** [review]
> Block merges during feature freezes

Has to wait until Thursday+

**Review by come-nc — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by TomW80** [comment]
Hello,

I have now updated to NC 25.0.4 and tested the login with php8.
I get again an error from LoginController:

```
[index] Fehler: Exception: OC\Core\Controller\LoginController::tryLogin(): Argument #1 ($user) must be of type string, null given, called in /volume1/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/volume1/web/nextcloud/core/Controller/LoginController.php' line 298 at <<closure>>

0. /volume1/web/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(["OC\\Core\\Controller\\LoginController"], "tryLogin")
1. /volume1/web/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OC\\Core\\Controller\\LoginController", "tryLogin", ["OC\\AppFramewo ... "], ["core.login.tryLogin"])
2. /volume1/web/nextcloud/lib/base.php line 1047
   OC\Route\Router->match("/login")
3. /volume1/web/nextcloud/index.php line 36
   OC::handleRequest()
```

and this Error:

`[PHP] Fehler: Unknown: POST Content-Length of 185 bytes exceeds the limit of 2 bytes at Unknown#0`

**Comment by szaimen** [comment]
Hi, yes the PR will be included in 25.0.5

**Comment by TomW80** [comment]
Hello,

I have now updated to NC 25.0.5 and tested login with php8.
Error from LoginController is solved, but when I login I am always redirected back to the login page and still get this error:

Unknown: POST Content-Length of 196 bytes exceeds the limit of 2 bytes at Unknown#0.

**Comment by nickvergessen** [comment]
Sounds like you are missing an M or G in your php.ini config and just set the post/upload max size to `2 B`which is `2 bytes` instead of `2 MB`

**Comment by TomW80** [comment]
You are right, at post max size I had written 2GB.
Thank you!

**Pull request merged**
