### PR TITLE
Bump @nextcloud/vue to 7.2.0

### PR DESCRIPTION
**Pull request by Pytal**
https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.2.0

### CODE REVIEW

**Review by szaimen — DISMISSED** [review]
This reintroduces https://github.com/nextcloud/server/issues/34777

**Review by nickvergessen — APPROVED** [review]
The reopening of #34777 is an acceptable trade for me :)

**Comment by Pytal** [comment]
> This reintroduces #34777

Blocking or not @PVince81?

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@Pytal not blocking because then we can't progress on a11y if we don't merge this

still, I asked @skjnldsv to help with https://github.com/nextcloud/server/issues/34777

**Comment by skjnldsv** [comment]
Rebased and ready to merge

**Pull request merged**
