### PR TITLE
Set X-XSS-Protection: 0

### PR DESCRIPTION
**Pull request by Hello71**
It reduces security, see owncloud/core#38305.

Signed-off-by: Alex Xu (Hello71) <alex_y_xu@yahoo.ca>

### CODE REVIEW

**Comment by acsfer** [comment]
Well, the real question should be, as we're relying on CSP, is this header useful **at all**?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection#browser_compatibility

**Comment by kesselb** [comment]
> thanks for your contribution +1 Would you mind to update your pr and set X-XSS-Protection to 0. That seems the recommended value according to [OWASP/CheatSheetSeries#378](https://github.com/OWASP/CheatSheetSeries/pull/378).

https://github.com/nextcloud/server/pull/26434#issuecomment-814394802

**Comment by Hello71** [comment]
i think it's better to set it to 0, since some old browsers may default to 1 which is the "very insecure" mode. that's what google does for example.

**Comment by J0WI** [comment]
`X-XSS-Protection` in the docs:
- https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/harden_server.rst#serve-security-related-headers-by-the-web-server
- https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx-root.conf.sample#L56
- https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx-subdir.conf.sample#L83

**Comment by LukasReschke** [comment]
@Hello71, can you also add the change to https://github.com/nextcloud/server/blob/b260ef954d66de61a7d063295ca43a9a00cf7039/.htaccess#L36 ?

**Comment by Hello71** [comment]
Sorry for the slow followup, but I don't have time to work on this anymore. I would appreciate it greatly if someone else could pick up this work.

**Pull request closed without merging**
