### PR TITLE
downgrade ubuntu in order to fix CI

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: Simon L <szaimen@e.mail.de>
image

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by skjnldsv** [comment]
WHat's the context of this? :)

**Comment by szaimen** [comment]
> WHat's the context of this? :)

See the failing phpunit tests e.g. in https://github.com/nextcloud/server/pull/35547 and in other PRs. For further context see the engineering chat.

**Comment by nickvergessen** [comment]
Refering to an internal chat is not the best documentation. Just summarize it here?
Should also do it in the workflow template repository

**Comment by MichaIng** [comment]
I'd be also interested about the reason why it fails on Ubuntu Jammy runners. But good to know that there is a workaround for the CI failures 👍.

**Comment by szaimen** [comment]
I updated the description 👍

**Review by blizzz — APPROVED** [review]

**Comment by MichaIng** [comment]
Wouldn't it be better to apply the workaround in #32003 instead? However, doesn't matter so much, both can be a short-term workaround only. Looks like #25551 needs to be done not not force admins of recent distros, with server-side encryption enabled, to enable legacy OpenSSL ciphers.

**Comment by szaimen** [comment]
all backports done. Looks like the stable22 and below does not need this.

**Pull request merged**
