### PR TITLE
[stable9] Backport files drop feature

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/nextcloud/server/pull/19

@blizzz As discussed

### CODE REVIEW

**Comment by mar1u5** [comment]
👍

**Comment by blizzz** [comment]
Will add commits from https://github.com/nextcloud/server/pull/57 when this is merged

**Comment by LukasReschke** [comment]
> Will add commits from #57 when this is merged

I cherry-picked the commits into this one.

**Comment by LukasReschke** [comment]
👍  for Arthur's changes.

**Comment by MorrisJobke** [comment]
This broke the js unit tests on stable9 :( https://github.com/nextcloud/server/pull/72

**Pull request merged**
