### PR TITLE
Mark user_saml official and kill user_shibboleth

### PR DESCRIPTION
**Pull request by LukasReschke**
Otherwise the app is marked as experimental in the admin interface 🙈

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by LukasReschke** [comment]
@mar1u5 Mind reviewing? :)

**Comment by mar1u5** [comment]
- since `user_shibboleth` is EE it is ok that we remove that from the list (until we may have rewritten that 😜)
- fixing the space used in `comments` is obviously fine 😉 
- `user_saml` is still WIP i think 😕 ... so marking it as _Experimental_ might be legit. Because it is the `stable9`-branch ... when will `user_saml` be finished ... and will it really be part of 9.0.52 😅

**Comment by LukasReschke** [comment]
> user_saml is still WIP i think 😕 ... so marking it as Experimental might be legit. Because it is the stable9-branch ... when will user_saml be finished ... and will it really be part of 9.0.52 😅 ...but I think you can explain me that 😄 @LukasReschke

Will be in 9.0.52, WIP mainly means "don't check out the code right _NOW_ as config options might change" :-)

**Comment by LukasReschke** [comment]
> since user_shibboleth is EE it is ok that we remove that from the list (until we may have rewritten that 😜)

user_saml replaces user_shibboleth. Shibboleth is basically just SAML 😄

**Comment by mar1u5** [comment]
Then ... 👍 THX!

**Comment by mar1u5** [comment]
Will you port it to `master` 🙈

**Comment by LukasReschke** [comment]
> Will you port it to master 🙈 @LukasReschke

As soon as the app is compatible: Yes. At the moment it only works on stable9 :)

**Pull request merged**
