### PR TITLE
Check the user on remote wipe

### PR DESCRIPTION
**Pull request by nickvergessen**
This has been released with 18.0.3 and 17.0.5 already

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by kesselb** [comment]
cc @nextcloud/docker @nextcloud/snap

**Review by gary-kim — APPROVED** [review]
Here it is!

> cc @nextcloud/docker

I opened the PR to get the images updated on Docker Hub. Hope you don't mind :).

**Comment by rullzer** [comment]
Yeah apologies for the tag messup

**Pull request merged**
