### PR TITLE
change core to server

### PR DESCRIPTION
**Pull request by oparoz**
@jospoortvliet @MorrisJobke

### CODE REVIEW

**Comment by mar1u5** [comment]
:+1: ... Backport? @karlitschek

**Comment by mar1u5** [comment]
Good Catch :+1: ...could you prepare an backport to `stable10` and `stable9`?
Interessting that /core is redirecting anyway ... :stuck_out_tongue_closed_eyes:

**Comment by rullzer** [comment]
LGTM

**Comment by karlitschek** [comment]
backport makes sense. thanks a lot!!!

**Pull request merged**
