### PR TITLE
Remove limit from axios call that retrieves groups

### LINKED ISSUE #24547: Workflowengine doesnt return all criteria values
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create more then 20 Groups in your system
2. Create a workflow with group membership as criteria
3. Check if all Groups are displayed in the Dropdownbox

Also, aftern an Update, the workflows show up but some might not have a value, even if it's actually set and active

### Expected behaviour
I would expect all groups to be displayed.

### Actual behaviour
Amount of Records is limited to 20

### Server configuration

**Operating system:**
Ubuntu 18.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
19.0.5.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
updater.phar

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.2
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.2
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - metadata: 0.12.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.11
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.6
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.9.0
  - user_external: 1.0.0
  - user_ldap: 1.9.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "debug": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.niedermayr.net",
            "oc.niedermayr.net",
            "nct.niedermayr.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "defaultapp": "activity",
        "theme": "",
        "activity_expire_days": 90,
        "maintenance": false,
        "forcessl": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "auth.bruteforce.protection.enabled": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "X",
                    993,
                    "ssl",
                    ""
                ]
            }
        ],
        "loglevel": 2,
        "trashbin_retention_obligation": 30,
        "updater.release.channel": "stable",
        "singleuser": false,
        "overwrite.cli.url": "https:\/\/nc.X",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

OC_USer_IMAP

### Client configuration
**Browser:**
FF 83

**Operating system:**
Ubuntu Linux 18.04

### PR DESCRIPTION
**Pull request by lephisto**
Fixes #24547

Signed-off-by: Mephisto <mephisto@mephis.to>

### CODE REVIEW

**Comment by lephisto** [comment]
Will this PR make it?

**Review by nickvergessen — CHANGES_REQUESTED** [review]
This is a bad idea and will bring down servers with a lot of groups.
Why can't you type ahead to search?

**Comment by lephisto** [comment]
This is not the Issue. Please read it. The Comboboxes will stay empty for existing workflows, if the groups are not within the first 20.

**Comment by nickvergessen** [comment]
Then this needs fixing. Loading potentially 2k or more groups which breaks the UI completely is not the option

**Comment by lephisto** [comment]
Limiting breaks the UI as well. How could this be fixed? It could be limited if the actually selected group in a workflowcondition would be guaranteed to be part of the result from the axios call. This would guarantee that the combo wouldn't be empty.. 

Is having 2k groups really a realistic case? Seems to be rather theoretical to me.

**Comment by rullzer** [comment]
> Limiting breaks the UI as well. How could this be fixed? It could be limited if the actually selected group in a workflowcondition would be guaranteed to be part of the result from the axios call. This would guarantee that the combo wouldn't be empty..
> 
> Is having 2k groups really a realistic case? Seems to be rather theoretical to me.

There are several customer running with far more than 2k groups ;)

**Comment by juliushaertl** [comment]
Showing not all groups is expected here, since as already mentioned this would be quite an issue with larger amount of groups. However I do not see any issue with the original implementation as you can still get to groups that are not displayed by searching for them.

**Comment by kesselb** [comment]
> However I do not see any issue with the original implementation as you can still get to groups that are not displayed by searching for them.

It's not confusing if one add a group to a workflow and after a page reload the group is not shown anymore? :thinking:

**Comment by juliushaertl** [comment]
Ah, then I misunderstood the issue. In that case we most likely fail because we don't have a group match (with a displayname) in https://github.com/nextcloud/server/blob/f9b4084f522f9112f69d672e25e5545302f2341c/apps/workflowengine/src/components/Checks/RequestUserGroup.vue#L69

I'm not sure how to best solve this other than doing a request for each currently set value yet, but that might of course also cause a high amount of requests for each rule that has a different group set.

**Comment by juliushaertl** [comment]
> I'm not sure how to best solve this other than doing a request for each currently set value yet, but that might of course also cause a high amount of requests for each rule that has a different group set.

It actually seems to be the case already, so maybe @lephisto can clarify a bit on the original issue.

**Comment by ClCfe** [comment]
you have two ways to fix this

1) simple but not the cleanest
adding a limit parameter to the method `searchAsync(searchQuery, limit=20)`
if limit is null, no limit parameter should be added to the axios query

```
if (this.groups.length === 0) {
	await this.searchAsync('', null)
}
```
=> so it will retrieve all groups ONLY at initialization

2) cleanest but more complex
you pass to the axios query an array of groups IDs (as a new parameter values[]) already involved in the rules of the edited workflow, but this implies changes on the backend

**Comment by lephisto** [comment]
> 
> 
> > I'm not sure how to best solve this other than doing a request for each currently set value yet, but that might of course also cause a high amount of requests for each rule that has a different group set.
> 
> It actually seems to be the case already, so maybe @lephisto can clarify a bit on the original issue.

No this is not the case. The current behaviour is, that if you load an existing workflow and there is one group assignment which isn't coincidentally in the first 20 results of the result-limited query, the Dropdown just stays empty, which is confusing.

This is why i formulated the PR to not limit it at all, but I get that it might result in an uncool behaviour if ppl use groups excessively.. As proposed earlier, one idea might be to pass the currently assigned groups to the axios call, to guarantee that they're part of the resultset thus avoiding the confusion. But this exceeds my Nextcloud Coding style awareness to not make it totally ugly. :)

**Comment by nickvergessen** [comment]
Closing again. This is not the right way. The required data needs to be loaded manually or with initial state on the settings module. But removing the limit and returning all groups is not an option.

**Pull request closed without merging**
