### PR TITLE
[stable11] Treat PHP Errors on User session regenerate

### PR DESCRIPTION
**Pull request by blizzz**
There are code paths that could disable apps (>= PHP 7)

fyi @LukasReschke

### CODE REVIEW

**Comment by blizzz** [comment]
Perhaps related: https://github.com/phpredis/phpredis/issues/1062 despite redis module 3.1.2 is in use

**Review by LukasReschke — DISMISSED** [review]

**Comment by blizzz** [comment]
This works here, but i would rework the whole class and wrap any session_* call into an ``try…catcht(Error)`` to consistently have a similar experience to PHP 5.6 times.

**Comment by blizzz** [comment]
I throw the session_* calls now into the invoker that does the error transformation.

**Comment by blizzz** [comment]
Needs forward ports to 12 and master @karlitschek

**Comment by karlitschek** [comment]
👍  makes sense

**Review by LukasReschke — APPROVED** [review]
I guess we have to do that then. Nice catch!

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@blizzz Could you please do the forward ports? thanks

**Comment by blizzz** [comment]
Thx for merging - will do!

**Comment by blizzz** [comment]
Done → #5421 & #5422

**Pull request merged**
