### PR TITLE
Revert "Temp disable bundle tests"

### PR DESCRIPTION
**Pull request by rullzer**
Once all apps have a 16 version (of the enterprise bundle) the test should work again.

### CODE REVIEW

**Comment by nickvergessen** [comment]
ToS has been released

**Comment by rullzer** [comment]
I guess we need another release. I'll check later

**Comment by rullzer** [comment]
Ah seems we also need a new files access control release @nickvergessen 
https://apps.nextcloud.com/apps/files_accesscontrol

**Comment by MorrisJobke** [comment]
Restarted https://drone.nextcloud.com/nextcloud/server/17441

**Review by MorrisJobke — APPROVED** [review]
Time for a rebase and signed-off-by message 😉

**Pull request merged**
