### PR TITLE
Align password reset arrow

### LINKED ISSUE #19939: [Design] Password reset arrow
Check this screenshot, arrow is far away from the button.
Both Firefox and Chrome, **fresh install of NC 18.0.2.**

image

**On NC 17.0.3** (not great but at least they're inline)
image

### PR DESCRIPTION
**Pull request by kesselb**
Fix #19939 

Before | After
---|---
image | image

Turns out the fieldset was missing.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
Could we get a right padding for the button so the text is not under the arrow? :)

**Comment by kesselb** [comment]
> Could we get a right padding for the button so the text is not under the arrow? :)

I'm against it. It looks weird for french but okay for most other languages. 

image

padding-right 30px. The text is not cantered anymore then. That should be solved in a different way (probably by using a shorter term).

**Comment by skjnldsv** [comment]
Then migrate to a button and not an input so we can have the arrow inside and push the ellipsis to the left?

**Comment by kesselb** [comment]
> Then migrate to a button and not an input so we can have the arrow inside and push the ellipsis to the left?

Sounds like a plan but a different story.

**Review by jancborchardt — APPROVED** [review]
Looks good and fixes the issue of the arrow being outside. We can do a follow-up about the other issue, but let’s get this in first. :)

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
