### PR TITLE
fix(external_storage): Cast id to int

### PR DESCRIPTION
**Pull request by oleksandr-nc**
follow up to https://github.com/nextcloud/server/pull/49464

Should solve error:

`"message": "OCA\\Files_External\\Service\\DBConfigService::getMountById(): Argument #1 ($mountId) must be of type int, string given, called in /var/www/html/nextcloud_test1/apps/files_external/lib/Service/StoragesService.php on line 164 in file '/var/www/html/nextcloud_test1/apps/files_external/lib/Service/DBConfigService.php' line 69"`

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Comment by oleksandr-nc** [comment]
`
{"reqId":"CKVFUb9FTOrJUfb8qPKq","level":3,"time":"2024-11-01T13:19:54+00:00","remoteAddr":"172.30.104.10","user":"V1_4089","app":"index","method":"GET","url":"/index.php/apps/files_external/userstorages/undefined?testOnly=false","message":"OCA\\Files_External\\Service\\DBConfigService::getMountById(): Argument #1 ($mountId) must be of type int, string given, called in /var/www/html/nextcloud_test1/apps/files_external/lib/Service/StoragesService.php on line 164 in file '/var/www/html/nextcloud_test1/apps/files_external/lib/Service/DBConfigService.php' line 67","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"28.0.11.1","exception":{"Exception":"Exception","Message":"OCA\\Files_External\\Service\\DBConfigService::getMountById(): Argument #1 ($mountId) must be of type int, string given, called in /var/www/html/nextcloud_test1/apps/files_external/lib/Service/StoragesService.php on line 164 in file '/var/www/html/nextcloud_test1/apps/files_external/lib/Service/DBConfigService.php' line 67","Code":0,"Trace":[{"file":"/var/www/html/nextcloud_test1/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud_test1/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud_test1/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud_test1/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud_test1/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"TypeError","Message":"OCA\\Files_External\\Service\\DBConfigService::getMountById(): Argument #1 ($mountId) must be of type int, string given, called in /var/www/html/nextcloud_test1/apps/files_external/lib/Service/StoragesService.php on line 164","Code":0,"Trace":[{"file":"/var/www/html/nextcloud_test1/apps/files_external/lib/Service/StoragesService.php","line":164,"function":"getMountById","class":"OCA\\Files_External\\Service\\DBConfigService","type":"->"},{"file":"/var/www/html/nextcloud_test1/apps/files_external/lib/Controller/StoragesController.php","line":296,"function":"getStorage","class":"OCA\\Files_External\\Service\\StoragesService","type":"->"},{"file":"/var/www/html/nextcloud_test1/apps/files_external/lib/Controller/UserStoragesController.php","line":110,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->"},{"file":"/var/www/html/nextcloud_test1/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"show","class":"OCA\\Files_External\\Controller\\UserStoragesController","type":"->"},{"file":"/var/www/html/nextcloud_test1/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud_test1/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud_test1/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud_test1/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud_test1/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud_test1/apps/files_external/lib/Service/DBConfigService.php","Line":67},"message":"OCA\\Files_External\\Service\\DBConfigService::getMountById(): Argument #1 ($mountId) must be of type int, string given, called in /var/www/html/nextcloud_test1/apps/files_external/lib/Service/StoragesService.php on line 164 in file '/var/www/html/nextcloud_test1/apps/files_external/lib/Service/DBConfigService.php' line 67","exception":{},"CustomMessage":"OCA\\Files_External\\Service\\DBConfigService::getMountById(): Argument #1 ($mountId) must be of type int, string given, called in /var/www/html/nextcloud_test1/apps/files_external/lib/Service/StoragesService.php on line 164 in file '/var/www/html/nextcloud_test1/apps/files_external/lib/Service/DBConfigService.php' line 67"}}
`

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
