### PR TITLE
fix(files): fix list gap at bottom

### LINKED ISSUE #46860: File list footer is to far away from the list
The file list footer is too far off if some header is shown in the file list (e.g. folder description or recommended files):

Screenshot 2024-07-30 at 08 29 33

This seems to be caused by:
https://github.com/nextcloud/server/blob/968d41241baac08b9a2a09f104f77c755908d477/apps/files/src/components/VirtualList.vue#L219

@susnux It seems adding the beforeHeight is the problematic part but I cannot tell if that was needed for the scroll behaviour in https://github.com/nextcloud/server/commit/75dcf901ffe9ced33407a765a76874abb1698449

### PR DESCRIPTION
**Pull request by elzody**
* Resolves: #46860

## Summary
Due to a dynamic CSS property in the `VirtualList.vue` component, there was extra space after the final file in the list whenever the rich workspace is active. This PR removes the naughty part of the height calculation as specified in the issue

## Screenshots
<details>
<summary>Before</summary>

image

</details>

<details>
<summary>After</summary>

image

</details>

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by skjnldsv** [comment]
I guess the calculation of the height changed at some point and we forgot to remove the beforeHeight. :thinking: 

@elzody have you tested with a few headers ? Like recommendations and text with a readme ?

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by susnux** [comment]
> I guess the calculation of the height changed at some point and we forgot to remove the beforeHeight. 🤔

Last time I touched that logic and copy-pasted but shame on me I did not tested with recommended-files or text installed :see_no_evil:

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
@skjnldsv 
> EDIT: just did, it's perfect! 👍

Did you also test with a fileid in the URL? So that the scrolling still works? Because the scroll position still takes `beforeHeight` into account.

**Comment by elzody** [comment]
@susnux I just gave it a whirl, it seems like it still auto-scrolls so the selected file is still visible.

**Pull request merged**
