### PR TITLE
Re-add labels for password inputs for usability

### PR DESCRIPTION
**Pull request by MorrisJobke**
- ref https://github.com/nextcloud/server/pull/112#discussion_r67245286

cc @Henni @LukasReschke @mar1u5 @blizzz

### CODE REVIEW

**Comment by mar1u5** [comment]
Missed that :grin: Drone build failed :confused:

**Comment by MorrisJobke** [comment]
> Drone build failed

Also fails on master. I'm already investigating

**Comment by MorrisJobke** [comment]
> Also fails on master. I'm already investigating

Ignore it for this PR: #124

**Comment by MorrisJobke** [comment]
@mar1u5 I rebased on master to fix the failing unit test

**Comment by vincchan** [comment]
LGTM

**Comment by MorrisJobke** [comment]
@blizzz @Henni @schiessle @jancborchardt Please review :) It's easy :)

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
