### PR TITLE
Sync master

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @blizzz @LukasReschke @schiessle @mar1u5

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I used the version of upstream for the folder traversal: owncloud/core#25368 (instead of #278) but included our JS unit tests into the code. That means that for "/abc/../def" we go directly to "/" instead of how we implemented it go to "/abc/def".

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer

**Comment by MorrisJobke** [comment]
I reverted https://github.com/owncloud/core/pull/25356 and https://github.com/owncloud/core/pull/24957

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by blizzz** [comment]
Admin page gives me a 500

```

Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: 127.0.0.1
    Request ID: Qsa2ySxcM4Av9OnRhFZT
    Type: RuntimeException
    Code: 0
    Message: image not found: image:actions/info.png webroot:/master serverroot:/srv/http/nextcloud/master
    File: /srv/http/nextcloud/master/lib/private/URLGenerator.php
    Line: 194


Trace

#0 /srv/http/nextcloud/master/lib/private/legacy/template/functions.php(169): OC\URLGenerator->imagePath('', 'actions/info.pn...')
#1 /srv/http/nextcloud/master/apps/user_ldap/templates/part.wizardcontrols.php(13): image_path('', 'actions/info.pn...')
#2 /srv/http/nextcloud/master/lib/private/Template/Base.php(173): include('/srv/http/nextc...')
#3 /srv/http/nextcloud/master/lib/private/Template/Base.php(148): OC\Template\Base->load('/srv/http/nextc...', NULL)
#4 /srv/http/nextcloud/master/lib/private/legacy/template.php(226): OC\Template\Base->fetchPage(NULL)
#5 /srv/http/nextcloud/master/apps/user_ldap/settings.php(41): OC_Template->fetchPage()
#6 /srv/http/nextcloud/master/lib/private/legacy/app.php(737): include('/srv/http/nextc...')
#7 /srv/http/nextcloud/master/settings/admin.php(176): OC_App::getForms('admin')
#8 /srv/http/nextcloud/master/lib/private/Route/Route.php(154) : runtime-created function(1): require_once('/srv/http/nextc...')
#9 [internal function]: __lambda_func(Array)
#10 /srv/http/nextcloud/master/lib/private/Route/Router.php(280): call_user_func('\x00lambda_57', Array)
#11 /srv/http/nextcloud/master/lib/base.php(868): OC\Route\Router->match('/settings/admin')
#12 /srv/http/nextcloud/master/index.php(39): OC::handleRequest()
#13 {main}
```

**Comment by MorrisJobke** [comment]
> Admin page gives me a 500

Seems to be https://github.com/owncloud/core/pull/25405 -> I will update this PR

**Comment by blizzz** [comment]
@MorrisJobke yeah, wanted to point to the same now :) Thx!

**Comment by MorrisJobke** [comment]
@blizzz Done :)

**Comment by blizzz** [comment]
@MorrisJobke :+1:

**Pull request merged**
