### PR TITLE
Add drone step for postgres with php 7.1

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
two failures:

```
There were 2 failures:

1) Test\Files\ViewTest::testLockBasicOperation with data set #20 ('file_exists', array('dir'), 'dir', null)
File not locked before operation
Failed asserting that 1 is null.

/drone/src/github.com/nextcloud/server/pull/5994/tests/lib/Files/ViewTest.php:1840

2) Test\Files\ViewTest::testLockBasicOperationUnlocksAfterException with data set #20 ('file_exists', array('dir'), 'dir', null)
File got unlocked after exception
Failed asserting that 1 is null.

/drone/src/github.com/nextcloud/server/pull/5994/tests/lib/Files/ViewTest.php:1987
````

@icewind1991 can you take a look?

**Comment by MorrisJobke** [comment]
FYI @benediktg

**Comment by MorrisJobke** [comment]
Rebased - let's see if it is fixed by the PR of @icewind1991

**Comment by MorrisJobke** [comment]
Ran fine: https://drone.nextcloud.com/nextcloud/server/1095/23/postgres-php7.1

Let's merge it

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
