### PR TITLE
fix: acceptance test for comments requires activity app

### PR DESCRIPTION
**Pull request by azul**
The presence of the activity app makes the details sidebar reload
after creating a new folder.

The reload is required for the comment form to work.
Otherwise it will trigger a page reload.

Clone the activity app just like notifications
when preparing the test environment.

refs #20454

This at least fixes the first test for comments starting in line 21. Other comments tests are still failing for me locally.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Nice!
I don't think this is used by our CI setup though

**Comment by skjnldsv** [comment]
Ah yes it is: `run-local.sh`, `run.sh` is used by devs when local testing :)

**Comment by azul** [comment]
Looks like the tests are failing after activity app is installed because the behavior changed in the meantime.

I added another commit to test the current behavior:
When clicking on a comment related link
such as the "new comment" icon
or the search results for comments
Nextcloud opens the activity tab of the corresponding file.

I am not sure if this is desired.
But it is the current behavior.
Make the comment tests pass
by clicking on the "Comments" tab
whenever we want to see the actual comment
instead of the activity list.

This used to be hidden
because the activity app was not installed by default.
However other comment related tests require the app to be installed.
Since it is a default err on the side of documenting the current default behavior.

**Comment by azul** [comment]
@skjnldsv and `run.sh` will call run-local.sh inside the docker container. So this fixes both if devs have not cloned the activity app locally.

**Review by skjnldsv — APPROVED** [review]

**Comment by azul** [comment]
@skjnldsv I rerequested your review because i added a new commit that might be controversial... as in i don't know if we should adjust the tests to the current behavior or the other way round.

**Comment by nickvergessen** [comment]
> I added another commit to test the current behavior:
When clicking on a comment related link
such as the "new comment" icon
or the search results for comments
Nextcloud opens the activity tab of the corresponding file.

That is a regression from the new sidebar I guess.

**Review by nickvergessen — CHANGES_REQUESTED** [review]
> And I open the unread comments for "shared.txt"

This should really open the comments tab, not the activity app

**Comment by azul** [comment]
@nickvergessen I agree the test should document the desired behavior.
So I removed the second commit.
I also created #20463 to track the regression.
I think this fix to the test setup still makes sense because it reveals the regression more clearly.

**Review by nickvergessen — APPROVED** [review]

**Comment by skjnldsv** [comment]
> @skjnldsv I rerequested your review because i added a new commit that might be controversial

ah, github showed me the page was not up to date, I did not refreshed!
Yeah, I would not do that, that is a regression, teste should reflect the proper ux, which is not to have to click the comment tab again :)

Please revert it and fix the main cause if possible. This is due to legacy code ported to the new sidebar:
https://github.com/nextcloud/server/blob/43f0d2a3b5bc76ed72693695451398b4b7b78411/apps/files/js/filelist.js#L635
https://github.com/nextcloud/server/blob/43f0d2a3b5bc76ed72693695451398b4b7b78411/apps/files/js/filelist.js#L675

I guess OCA.Files.Sidebar.setActiveTab needs to be updated as well since https://github.com/nextcloud/server/pull/18929

**Review by danxuliu — CHANGES_REQUESTED** [review]
Blocking to prevent a merge.

Sorry for the terse message :-P I will give more details once I know more ;-)

**Comment by azul** [comment]
@skjnldsv I reduced this pull request to only fix the test setup issue. Not sure i will get to fixing the regression itself soon. Opened #20463 for that so others can also take a stab at it.

**Comment by skjnldsv** [comment]
So mysterious Daniel ;)  🔮

**Comment by danxuliu** [comment]
Sorry for the suspense :-P

The failures in the acceptance tests for comments are legit, so the tests do not need to be fixed ;-) If you perform the steps manually you would see that the sidebar does not behave as it should.

The failure in _app-comments.feature:21_ is a regression introduced in #18764. The other failures (233, 288, 308) are a regression introduced in #18929, but in fact their root cause seem to be in #18764 too; if #18764 is reverted those test pass too, even if they started failing in #18929.

I will try to find some time later this week to see what is going on (unless someone else figures it before, of course ;-) ).

In any case I will close this pull request, as the tests do not require the activity app. Thanks anyway! :-)

**Pull request closed without merging**
