### PR TITLE
Cache tokens when using swift's v2 authentication

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Couldn't really test since my v2 doesn't work anymore. But makes sense.

**Comment by Arvi89** [comment]
I've patched my installation 14.0.4 and it worked.

**Comment by rullzer** [comment]
@Arvi89 thanks! I'm counting that as a :+1:

**Pull request merged**
