### PR TITLE
Honor permissions of new link share via OCS API

### LINKED ISSUE #32611: OCS Share API - "permissions" parameter has no effect
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The OCS Share API doesnt work properly. One is not able to set the permissions, it always stays "17".

### Steps to reproduce

1. Create Share Link via API with the desired permissions

### Expected behavior

Permissions are set correctly

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Only default apps, fresh install
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by jplitza**
The API currently overrides the supplied permissions with "read only" when a file is shared via link. It allows to update the permissions later, however.

Fixes #32611

### CODE REVIEW

**Comment by juliushaertl** [comment]
It would be still nice to preserve the default of read only permissions for the share links, maybe by moving that to the first condition in https://github.com/nextcloud/server/pull/35213/files#diff-dbbe017dd357504abc442a6f1d0305166520ebf80353f42814b3f879a3e241bcR481

What do you think?

**Comment by jplitza** [comment]
+1 for keeping defaults - although it seems wrong to willfully ignore the setting. Changed nonetheless.

**Comment by jplitza** [comment]
The 3 failing tests all explicitly sets PERMISSION_ALL but expects the share to only have read permissions. Fixed two of them to expect PERMISSION_ALL and one to not set permissions at all and expect READ|SHARE.

**Comment by jplitza** [comment]
The amount of tests that cement the old behavior is staggering. After fixing 4 unit tests, now acceptance-app-files-sharing is failing in a way I don't quite understand yet. Apparently a readonly user (!) share can now be re-shared readwrite. I don't yet see any connection to my patch, but it's close enough to probably be caused by it.

**Comment by nickvergessen** [comment]
The acceptance tests can be randomly failing from time to time.

**Comment by juliushaertl** [comment]
I've restarted the drone job to double check

**Comment by jplitza** [comment]
Indeed, now the a acceptance-app-files-sharing tests all succeed (but acceptance-app-theming still fails, though probably unrelatedly, and samba now failed, which it previously didn't).

**Review by juliusknorr — APPROVED** [review]

**Comment by jplitza** [comment]
Sooo... what is the process to get a second review on this?

**Review by artonge — COMMENTED** [review]
Looks good.

@skjnldsv you added a TODO about it in the front-end, but I don't understand what it is referring too. Should we do something there too ? As this PR seems to "fix the createShare method".

https://github.com/nextcloud/server/blob/4f68d13e21590773f25864c06b30e47af1c73bb1/apps/files_sharing/src/components/SharingEntryLink.vue#L697-L701

**Comment by skjnldsv** [comment]
> @skjnldsv you added a TODO about it in the front-end, but I don't understand what it is referring too. Should we do something there too ? As this PR seems to "fix the createShare method".

Backend permissions are always tricky for sharing.
I haven't looked deep into that PR, but we need to make sure the front is compliant to this PR. I don't remember adding any check, but this is usually the thing to adjust and check

**Comment by jplitza** [comment]
Without having looked into the frontend code, I don't see how this PR could pose a problem. It preserves the default, and the frontend always first creates the share link without specifying permissions, and only allows setting permissions later on.

**Review by artonge — APPROVED** [review]
:+1:

**Comment by juliushaertl** [comment]
Failures unrelated

**Comment by juliushaertl** [comment]
Thanks for the pull request @jplitza 🎉

**Comment by timowevel1** [comment]
Problem is still there, also with updating share doesnt work for me. Newest version.

**Pull request merged**
