### PR TITLE
Add confirm button in new link share pending expire/password menu

### LINKED ISSUE #19526: Add confirm button in new link share pending expire/password menu
nc1

When there is a forced expiration date set and a link is shared, the user gets a dialog suggesting he has to enter required information. In the dialog there is only a cancel button, but no ok/accept button. it is counterintuitive to have to click outside the dialog to create the share. please add an ok/accept button (above the cancel button).

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #19526

share-confirm-button

### CODE REVIEW

**Comment by st3iny** [comment]
@skjnldsv @juliushaertl  @jancborchardt Your reviews are apreciated (as always :smile:).

**Comment by jancborchardt** [comment]
- The actions should be buttons, ideally on the same row, instead of just entries.
- The confirm button should be primary, that is blue color.
- "Confirm" would better be labeled "Create share"
- The indent on a lot of the text is off. I guess component error, but still looks weird

**Comment by jancborchardt** [comment]
Btw @st3iny we have a Nextcloud Talk instance where we also invite contributors for easier communication. I could give you a guest account e.g. with your email address from the commits? :)

**Comment by st3iny** [comment]
@jancborchardt Sure, go ahead :) Just use the email address from my commit.

**Comment by skjnldsv** [comment]
> * The actions should be buttons, ideally on the same row, instead of just entries.

We do not support this @jancborchardt

**Comment by st3iny** [comment]
> The indent on a lot of the text is off. I guess component error, but still looks weird

I traced this issue to the ActionText component of nextcloud/vue. It applies `width: 150px` and `margin: auto` to long texts which causes weird indentation.

**Comment by st3iny** [comment]
I rebased and changed the label of the confirm button to `Create share`.

**Review by skjnldsv — APPROVED** [review]

**Review by GretaD — APPROVED** [review]
code looks fine, didnt test

**Pull request merged**
