### PR TITLE
Drop PHP7.3

### LINKED ISSUE #29258: Deprecation of php7.3
Continuation of https://github.com/nextcloud/server/issues/19341

php7.3 will run out of security support end of year. So I assume Nextcloud 23 will still support it but for 24 it makes no sense.

Should Nextcloud 23 warn that it's the last version to support 7.3? We did that for previous releases.

Ref https://www.php.net/supported-versions.php

cc @skjnldsv @nickvergessen @juliushaertl

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/29258

Todo
- [x] Adjust versioncheck.php
- [x] Adjust composer.json and run `composer update php`
- [x] Add to developer infos https://github.com/nextcloud/documentation/pull/9329

To be merged once 23 is branched off.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by come-nc** [comment]
It seems a lot of images in .drone.yml use PHP 7.3.

It also needs to be removed from .github/workflows/oci.yml

**Comment by nickvergessen** [comment]
> It also needs to be removed from .github/workflows/oci.yml

I can use my script to drop this from all the app repositories.

**Comment by come-nc** [comment]
It would be good to finish and merge this before 8.1 is added to CI to avoid queuing too much jobs.

**Comment by skjnldsv** [comment]
@ChristophWurst ready when you are :wink:

**Comment by ChristophWurst** [comment]
CI needs adjustment. Feel free to take over.

**Comment by come-nc** [comment]
The following images still need 7.4 equivalents:  
```
image: ghcr.io/nextcloud/continuous-integration-acceptance-php7.3:acceptance-php7.3-3
      image: ghcr.io/nextcloud/continuous-integration-integration-php7.3:latest
  image: ghcr.io/nextcloud/continuous-integration-integration-php7.3:latest
  image: nextcloudci/litmus-php7.3:litmus-php7.3-1
  image: nextcloudci/php7.3-memcached:php7.3-memcached-3
  image: nextcloudci/samba-native-php7.3:samba-native-php7.3-1
  image: nextcloudci/samba-non-native-php7.3:samba-non-native-php7.3-1
  image: nextcloudci/webdav-apache-php7.3:webdav-apache-php7.3-3
```

**Comment by skjnldsv** [comment]
> The following images still need 7.4 equivalents:
> 
> ```
> image: ghcr.io/nextcloud/continuous-integration-acceptance-php7.3:acceptance-php7.3-3
>       image: ghcr.io/nextcloud/continuous-integration-integration-php7.3:latest
>   image: ghcr.io/nextcloud/continuous-integration-integration-php7.3:latest
>   image: nextcloudci/litmus-php7.3:litmus-php7.3-1
>   image: nextcloudci/php7.3-memcached:php7.3-memcached-3
>   image: nextcloudci/samba-native-php7.3:samba-native-php7.3-1
>   image: nextcloudci/samba-non-native-php7.3:samba-non-native-php7.3-1
>   image: nextcloudci/webdav-apache-php7.3:webdav-apache-php7.3-3
> ```

You can trigger them in https://github.com/nextcloud/docker-ci/actions/workflows/docker.yml

**Comment by come-nc** [comment]
> You can trigger them in https://github.com/nextcloud/docker-ci/actions/workflows/docker.yml

I actually cannot: "Error: The user required level is not sufficient"

**Comment by nickvergessen** [comment]
> I actually cannot: "Error: The user required level is not sufficient"

@come-nc you have been promoted :)

**Comment by come-nc** [comment]
«php7.3 lint Expected — Waiting for status to be reported» pops up in the check report despite being removed from CI. From what I understood this is because the check was marked as «Require status checks to pass before merging» in the branch protection rules. This should be changed to 7.4.

**Comment by come-nc** [comment]
What did I do wrong?
`litmus: Error response from daemon: pull access denied for nextcloudci/litmus-php7.4, repository does not exist or may require 'docker login': denied: requested access to the resource is denied` ( https://drone.nextcloud.com/nextcloud/server/12691/2/3 )

https://github.com/nextcloud/docker-ci/actions/runs/1548433456

**Comment by nickvergessen** [comment]
Before we merge this I shall run my script to bump all tests of apps

**Comment by come-nc** [comment]
@nickvergessen All tests are finally passing, except samba which is broken as well on master.

So what are the next steps to get this merged?

**Comment by nickvergessen** [comment]
I will bump all apps friday, after that is in we can merge this here

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/issues/30896 Review time

**Review by MichaIng — APPROVED** [review]

**Comment by come-nc** [comment]
Good to merge then?
The only drone failure is the samba one and is not related.

**Pull request merged**
