### PR TITLE
Fix navigation layout for items that are added on a re-render

### LINKED ISSUE #12464: Hover effect in apps menu broken right after enabling app
* go to app management 
* enable an app with an entry in the app menu (i.e. contacts)
* do not reload the page - the icon will be added on the fly
* expected: the added item behaves like all others
* actual: hovering the app menu reveals the app name and moves the icon a bit up - this happens for all except the one that was just added

The entry looks good:
bildschirmfoto 2018-11-15 um 10 35 39

Not anymore when hovered:
bildschirmfoto 2018-11-15 um 10 35 33

cc @juliushaertl @skjnldsv @nextcloud/designers

### PR DESCRIPTION
**Pull request by nickvergessen**
Bug was not visible until #12153 
Now it looks awkward with the externals app
> bildschirmfoto von 2018-11-16 10-54-33

Fixes #12464

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> Fix #12464 ?

Already added ;)

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I don't get it. For me the code is locally executed but the result still looks wrong:

bildschirmfoto 2018-11-16 um 11 12 59

I refreshed multiple times, reinstalled, used different browsers ... and still - the newly added apps are still rendered wrongly.

So this does not fix #12481 somehow. for me.

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Let me fix that

**Review by skjnldsv — APPROVED** [review]
Done.
The `span` is next to the `a`, not within it.
I also fixed the size of the apps icons that did not reflect what the php was initially outputting.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
