### PR TITLE
Move AutoComplete::filterResults to new event dispatcher and GenericE…

### PR DESCRIPTION
**Pull request by nickvergessen**
…vent

Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
- [ ] To post in #20953 
```
* `OCP\Collaboration\AutoComplete\AutoCompleteEvent` now extends `OCP\EventDispatcher\GenericEvent`  instead of `Symfony\Component\EventDispatcher\GenericEvent`: https://github.com/nextcloud/server/pull/21439
```

**Review by blizzz — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> To post in #20953

And https://github.com/nextcloud/server/pull/21439#event-3452205001

**Review by rullzer — APPROVED** [review]

**Comment by blizzz** [comment]
CI: 
says no

**Comment by nickvergessen** [comment]
Documentation added in https://github.com/nextcloud/documentation/pull/9319

**Pull request merged**
