### PR TITLE
Change Workflow to Tag Management

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
Also @karlitschek

**Comment by karlitschek** [comment]
As discussed 👍

**Comment by nickvergessen** [comment]
hmm so the workflow scripts @blizzz wrote are now in "Tag management"?

**Review by skjnldsv — APPROVED** [review]
More understandable! :+1:

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
