### PR TITLE
fix white scrollbar corner in dark mode

### LINKED ISSUE #37125: white square in dark mode when overflow: scroll is activated
See 

| Before | After |
|---|---|
| image | image |

Reproduced in an up-to-date chromium based browser.

Is fixable with `::-webkit-scrollbar-corner {background-color: transparent;}`. 

cc @nextcloud/server-frontend where should we add this? Maybe in server?

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/37125

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by come-nc — APPROVED** [review]
:elephant:

**Pull request merged**
