### PR TITLE
Master is now Nextcloud 21 runs on PHP 7.3 to 8.0 only

### PR DESCRIPTION
**Pull request by MorrisJobke**
Following #22766 and #19580

### CODE REVIEW

**Comment by MorrisJobke** [comment]
❌ Do not merge yet - it's Nextcloud 21 only ❌

**Review by kesselb — APPROVED** [review]

**Comment by nickvergessen** [comment]
Bump the maximum to 8 too?

**Comment by MorrisJobke** [comment]
> Bump the maximum to 8 too?

Not yet test nor in CI. I would do that once we have at least done some smoke testing locally.

**Comment by MorrisJobke** [comment]
> Bump the maximum to 8 too?

I added it to allow apps to test on this version without another round trip to the server repo.

**Comment by kesselb** [comment]
Time to update the CI images :partying_face:

**Comment by MorrisJobke** [comment]
Okay - we need to change our CI container as well. :)

**Review by blizzz — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
sure

**Comment by MorrisJobke** [comment]
Thanks @nickvergessen

**Pull request merged**
