### PR TITLE
Fix invite guest for new sharing flow

### LINKED ISSUE #40172: ⛑️ Polishing for new sharing design and flow 🤝
Follow-up to #26691 listing the remaining open issues to be fixed in `master` as well as `stable27`

---

https://github.com/nextcloud/server/pull/39472#issuecomment-1680970478
## Share list
- [x] BUG: Quick access menu should close when click outside

### Bugs specific to share settings
- [x] BUG: Setting "Allow public upload" disabled should also disable options to set file drop, according permissions

Screenshot 2023-08-17 at 12 23 33

- [x] BUG: Lots of optional share settings for the ones that should affect front-end:
  - [x] BUG: Public upload can be blocked
- [x] BUG: https://github.com/nextcloud/server/issues/40289
---

- [x] BUG: https://github.com/nextcloud/server/issues/40228 - Edit (louis): seem unrelated
- [x] BUG: https://github.com/nextcloud/server/issues/40299

---

- [x] BUG: Create a new share to a user, change to custom permission, click save share, go back to the share details -> now update and share check-boxes are missing (the custom permissions are the same as view only, but nevertheless the check-boxes should of course still be available)
- [x] BUG: Creating shares should probably not reload the full file list. Edit (louis): only an issue with 27 as the logic to handle share changes is not fine-grained enough to only refresh the share status of a file. Also, it was not introduced by the new sharing flow.
- [x] BUG: Related resources should not appear in the share details view - https://github.com/nextcloud/server/pull/40365

## Non-blocking
- [x] Accessibility fixes for quick menu
- [x] "Delete share" button does not need to be sticky, can just be a tertiary button (no background by default) below the advanced settings toggle (not inside advanced settings)
- [ ] The "Cancel" and primary button on the bottom need a backdrop to separate them a bit from the background, best a fade from color-main-background on the bottom to transparent on the top.
- [ ] Currently links are sorted below emails once created, but sorting should be: Links, mails, users
- [x] Too many share saved/updated notifications when updating/creating shares
- [ ] QA: Needs side by side testing if all old options are possible or also properly limited with the new one
- [ ] #40436
- [ ] If allow public upload admin setting is unchecked we should rename "Allow upload and editing" to "allow editing" and file drop / create permission should be disabled state

---

https://github.com/nextcloud/server/pull/39472#pullrequestreview-1599979725

### Follow-ups:
- [x] Switching between permissions presets should not close the advanced settings view
- [ ] The content of the sidebar is scroll-able when it should only be the content of the share tab

Screenshot from 2023-08-29 11-52-15

### UI comments:
- [x] Button at the bottom of the details view should not move when scrolling to the bottom
- [x] "Delete share" button text seems smaller than other buttons
- [ ] It is confusing to have the download permission under "Custom permissions" as it is not taken into account for bundles

### LINKED ISSUE #40299: [Bug]: Unable to invite guest
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Can't create guest share.
On attempt the following is thrown `Error creating the share: Unknown share type`

### Steps to reproduce

1. Set up https://github.com/nextcloud/guests/
2. Open the sharing sidebar
3. Enter an email address
4. Click Invite guest
5. Click on "Save share"

### Expected behavior

Save share, should successfully register a new share of type guest. 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
Resolves : https://github.com/nextcloud/server/issues/40172
Resolves : https://github.com/nextcloud/server/issues/40299

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Important point here is the backport then, which from what I understood will differ from the main branch one.

**Comment by Fenn-CS** [comment]
> Important point here is the backport then, which from what I understood will differ from the main branch one.

I did this on stable27 and realized it would work on master so decide to send the PR here at once, would backport to stable27 from this. (If your comment is related to this)

**Comment by blizzz** [comment]
conflicts and red cypress

**Review by juliusknorr — APPROVED** [review]
Tested and works

**Comment by artonge** [comment]
Rebased

**Comment by Fenn-CS** [comment]
Threw in a commit to  fix share entry alignments

| Before | Now |
| --------  | ------ |
| Screenshot from 2023-09-14 14-46-42 | Screenshot from 2023-09-14 15-37-15 |

**Comment by artonge** [comment]
> Threw in a commit to fix share entry alignments

This commit will need to be backported as well, as the rest is already merged into stable27

**Comment by Fenn-CS** [comment]
> This commit will need to be backported as well, as the rest is already merged into stable27

Exactly! already did :)

**Comment by AndyScherzinger** [comment]
> This commit will need to be backported as well, as the rest is already merged into stable27

Well this one is too late for 27.1.0 but would then go into 27.1.1 - it that a problem? @artonge @Fenn-CS  ?

**Comment by Fenn-CS** [comment]
> Well this one is too late for 27.1.0 but would then go into 27.1.1 - it that a problem? @artonge @Fenn-CS ?

It went in via this backport : https://github.com/nextcloud/server/pull/40415 thanks to @artonge the only thing that didn't go with that is the alignment commit which is non critical and is already back-ported now too.

cc: @AndyScherzinger

**Comment by AndyScherzinger** [comment]
The backport et alignment we will probably need to dig in a bit deeper so it is also aligned with related resources (if present).

So I expect the alignment will see a further small update.

Do you happen to have a screenshot with shares and related resources?

**Pull request merged**
