### PR TITLE
Removed additional and uneccessary request on password reset 

### PR DESCRIPTION
**Pull request by lal12**
Addition to this PR: https://github.com/nextcloud/server/pull/7651

### CODE REVIEW

**Comment by rullzer** [comment]
This slipped past my radar. I'll have a look here :)

**Review by rullzer — APPROVED** [review]
Still works and makes sense!

**Comment by rullzer** [comment]
@lal12 works like a charm. Could you sign-off and squash your commits?

**Comment by MorrisJobke** [comment]
@lal12 Do you need help with this? Just ask here or in our IRC at #nextcloud-dev on freenode.

**Comment by lal12** [comment]
@MorrisJobke I would or actually already tried, but my internet provider currently isn't providing internet. And over my neighbours connection I currently use, for what ever reason I cannot clone a git repo. 

So it can take a week until I am able to to it. But if it has some kind of hurry, it would be no problem for me if you did?

**Comment by MorrisJobke** [comment]
> So it can take a week until I am able to do it. But if it has some kind of hurry, it would be no problem for me if you do it?

Don't worry - we are not in a hurry here. Take your time and as soon as you have it we are here to guide you if you need assistance.

**Pull request closed without merging**
