### PR TITLE
Add checkbox to install recommended apps during setup

### LINKED ISSUE #17634: Enhance installer
When installting Nextcloud we should offer to install recommended apps.
A simple (by default checked) checkbox should do the trick.

This has some advantages in my opinion

1. We can slim down the size of the release tarball so more apps can be released out of bounds (viewer, right click, pdf viewer etc etc)
2. We can promote more usefull apps that the 90% of admins install anyways (mail, calendar, contacts)
3. Admins that do not want any of this (or that do not have a proper internet connection) just uncheck and are left with a very clean tiny nextcloud.

This all should of course come with some explanatory text. But the basics are straight forward in my opinion.

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/17634

Todo
- [x] Checkbox should be checked by default (doesn't work right now)
- [x] Checkbox checked state should be visually distinguishable (always look unchecked right now)
- [x] Generate route to the actual apps page
- [x] Show view with recommended apps
- [x] Automatically start download if redirected from the setup
- [x] Redirect back to default page once done

### CODE REVIEW

**Comment by rullzer** [comment]
- [ ] Need to enter password before apps are installed

**Comment by rullzer** [comment]
I say lets do this and get design feedback later on to make teh first run smoother.

**Review by rullzer — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@ChristophWurst Please squash :wink:

**Pull request merged**
