### PR TITLE
feat: Added Elestio as one-click deploy option

### LINKED ISSUE #47835: Adding Elestio as deployment option
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing NextCloud application as shown [here](https://elest.io/open-source/nextcloud). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

### PR DESCRIPTION
**Pull request by kaiwalyakoparkar**
* Resolves: #47835 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by solracsf** [comment]
Why should an external provider be featured on Git readme?

**Comment by AndyScherzinger** [comment]
agreeing with @solracsf - we are independent in terms of not promoting specific services of any kind

**Comment by AndyScherzinger** [comment]
So thanks for the PR, but based on the above argument we have to decline the contribution. In any case we are happy to have you and any future contribution may it be code, documentation, translations, or else 💙

**Comment by kaiwalyakoparkar** [comment]
Hey @solracsf @AndyScherzinger, Thank you for the review and feedback ❤️

**Pull request closed without merging**
