### PR TITLE
Allow to find local users by their email address

### PR DESCRIPTION
**Pull request by nickvergessen**
* Allow type-ahead of local users via email address
* If we match a complete email address, use a local user share and hide email + remote share options

I guess tests may fail, will adjust them then later.

### CODE REVIEW

**Comment by schiessle** [comment]
It looks like two things are missing:

- We should hide the email option if we match a exact federated cloud id (we query the local address books and the lookup server for it)
- We should hide the remote share option if we match a exact email address of non-local users.

**Comment by nickvergessen** [comment]
Those two things should already be the case, did you test them?

**Comment by schiessle** [comment]
I tested it now with a user who where email address === login name. I think that's quite common on some LDAP setups and the reason why we didn't searched the system address book.

Setup:

- a user with the username "user@server.com" and a email address "user@server.com"
- create system address book `sudo -u www-data ./occ dav:sync-system-addressbook`

Now I typed "user@server":

autocomplete1

Since there is no exact match this seems to be fine.

Then after I completed the email address it looks like that:

appmenu2

Now we have a exact match and the result is a bit confusing to me. We have two options but what are the differences? I assume that `user@server.com (user@server.com)` is the local user, but what happens if the user selects `user@server.com` I think this should be gone.

**Comment by nickvergessen** [comment]
Ah okay, yeah I didn't think about name === email, will have a look

**Comment by nickvergessen** [comment]
Done and added a test

**Review by schiessle — APPROVED** [review]
looks good now!

**Review by MorrisJobke — APPROVED** [review]
Tested and works:

bildschirmfoto 2017-06-14 um 17 53 48

And then the share drop down only shows the display name: 

bildschirmfoto 2017-06-14 um 18 02 26


👍

**Comment by MorrisJobke** [comment]
Ping @nickvergessen for the backport

**Comment by blizzz** [comment]
I backported it quickly → https://github.com/nextcloud/server/pull/5428

**Pull request merged**
