### PR TITLE
Fixed firefox guest header height

### PR DESCRIPTION
**Pull request by skjnldsv**
After https://github.com/nextcloud/server/pull/7249

capture d ecran_2017-12-12_16-11-46

### CODE REVIEW

**Comment by jancborchardt** [comment]
It’s fine by me. :) But FYI on mobile there’s a scrollbar very early (which was the issue originally to be solved by this whole working on the log in screen I think ;)
screenshot from 2017-12-12 16-38-19

**Comment by skjnldsv** [comment]
@jancborchardt what kind of mobile is this? This looks very small! :/

**Comment by jancborchardt** [comment]
@skjnldsv it’s Firefox responsive design mode, but looks the same on a Fairphone 2 for example (5" screen). And keep in mind the keyboard will also be shown there.

**Comment by skjnldsv** [comment]
Okay, fixed, It was an old div designed to push the footer 😱

**Review by jancborchardt — APPROVED** [review]
Looks good to me now! :rocket: :)

**Review by rullzer — APPROVED** [review]
Lets do this!

**Pull request merged**
