### PR TITLE
Allow to override #app-content and #app-navigation hrefs for content skipping

### PR DESCRIPTION
**Pull request by juliusknorr**
This allows apps that use a different id for the navigation or content to override the anchor used for the skip content/navigation buttons. Setting to `null` would not add the button, e.g. for cases when there is no navigation in the app.

```
		$response = new TemplateResponse('dashboard', 'index', [
 			'id-app-content' => '#app-dashboard',
 			'id-app-navigation' => null,
 		]);
```

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
nice :)

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by nickvergessen** [comment]
Should also add this to guests and public templates?

**Comment by juliushaertl** [comment]
Did a follow up https://github.com/nextcloud/server/pull/33266, but only for the public layout as described in the PR.

**Comment by juliushaertl** [comment]
Follow up to also add skipping to public pages https://github.com/nextcloud/server/pull/33266

**Pull request merged**
