### PR TITLE
Move file sharing activities to the new API

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up to #2092

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by MorrisJobke** [comment]
Tested and still works 👍

**Comment by MorrisJobke** [comment]
c @rullzer

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by MorrisJobke** [comment]
@rullzer @icewind1991 @schiessle Please review :)

**Comment by rullzer** [comment]
LGTM

**Pull request merged**
