### PR TITLE
Make 'Add to your website' toggleable

### PR DESCRIPTION
**Pull request by rullzer**
For https://github.com/nextcloud/server/issues/735

CC: @nickvergessen @MorrisJobke @icewind1991 @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
👍

**Comment by schiessle** [comment]
:+1:

**Comment by schiessle** [comment]
will you prepare a backport, @rullzer ?

**Comment by rullzer** [comment]
Yes will do

**Comment by rullzer** [comment]
Backport in https://github.com/nextcloud/server/pull/785

**Pull request merged**
