### PR TITLE
Add datetime support to QBMapper

### PR DESCRIPTION
**Pull request by nickvergessen**
Example implementation with integration tests: https://github.com/nickv-nextcloud/lifeline/pull/6

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Good stuff

**Comment by nickvergessen** [comment]
@kesselb and I talked a bit about it and wondered if we should switch the definitions to those constants:
https://github.com/nextcloud/server/blob/d4e6463eb27c44d2aad5befe1c687934ded5164e/lib/public/DB/Types.php#L35

And then add support for all of them.

**Comment by nickvergessen** [comment]
Maybe we can do this now and do the generic restructuring to OCP\DB\Types later?

**Review by MorrisJobke — APPROVED** [review]
Fine with me 👍

**Comment by nickvergessen** [comment]
Any strong opinions on a backport? 😬

**Comment by MorrisJobke** [comment]
> Any strong opinions on a backport? 😬

Not from my side.

**Comment by nickvergessen** [comment]
Docs done in https://github.com/nextcloud/documentation/pull/9311

**Pull request merged**
