### PR TITLE
frame-src doesn't respect the nonce attribute

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by kesselb** [comment]
Hmm. Code looks good. As per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src nonce is supported :confused:

**Comment by juliushaertl** [comment]
@kesselb Probably a copy-paste issue since the description of the nonce seems to be related to inline scripts: "A whitelist for specific inline scripts..." At least firefox and chrome don't respect the nonce on frames.

**Review by juliusknorr — APPROVED** [review]

**Comment by rullzer** [comment]
@kesselb yeah it is listed everywhere (see for example also https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src ) but doesn't work yet...

**Comment by kesselb** [comment]
> Probably a copy-paste issue since the description of the nonce seems to be related to inline scripts

image

Indeed. They included the sources from "default-src" for "img-src" and "frame-src".

**Pull request merged**
