### PR TITLE
Fix issue #31692 of occ files:scan

### LINKED ISSUE #31692: occ files:scan reports error "Implicit conversion from float XXX to int loses precision"
Linux archlinux 5.16.11-arch1-1, nextcloud 23.0.2, nginx/1.20.2, PHP 8.1.3, mariadb 10.7.3, preview generator 4.0.0
Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (12 cores), 24GB RAM

command:
sudo -u nextcloud /usr/bin/php /usr/share/webapps/nextcloud/occ files:scan --all

should result in completing scan for all users without errors but runs into following issue:

sudo -u nextcloud /usr/bin/php /usr/share/webapps/nextcloud/occ files:scan --all
Starting scan for user 1 out of 3 (joe)
Starting scan for user 2 out of 3 (david)
Starting scan for user 3 out of 3 (herb)

In Scan.php line 293:

  Implicit conversion from float 39.31666666666667 to int loses precision

### PR DESCRIPTION
**Pull request by cld4h**
occ files:scan reports error "Implicit conversion from float XXX to int loses precision"
@st3iny 
@spicemint

fixes #31692

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
@cld4h Please fix the DCO (https://github.com/nextcloud/server/pull/32059/checks?check_run_id=6122135498), but otherwise this looks good :+1:

**Review by st3iny — APPROVED** [review]
LGTM! Thank you for the fix.

**Comment by st3iny** [comment]
Other backports are not necessary because this deprecation was introduced in PHP v8.1.

**Comment by cld4h** [comment]
@CarlSchwan
@st3iny 
Sorry for the late response.
Just figured out how to modify the previous commit and add a Sign-off line.

**Comment by st3iny** [comment]
Looks good now. Drone failure seems to be unrelated.

**Pull request merged**
