### PR TITLE
Update DAV availability vue component to standard

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by ChristophWurst** [comment]
What standard?

**Comment by nickvergessen** [comment]
Using the shared component library instead of doing custom divs?
Don't be so picky with the words :P

**Comment by ChristophWurst** [comment]
I'm just trying to review.

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Pull request merged**
