### PR TITLE
Allow to overwrite the email template again

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Failing tests are fixed in master

**Review by LukasReschke — APPROVED** [review]

**Comment by phatair** [comment]
Hello,

so if i want to theme my mail template (change the Logo from "custom cloud" to "my logo") i can do this with nextcloud release 13 or is this possible with nextcloud 12 too?

**Comment by nickvergessen** [comment]
Logo is replaced with the theming app. But when you want to add something to the footer on all emails etc. you need this part

**Comment by MorrisJobke** [comment]
Will be also available in 12.0.1

**Comment by phatair** [comment]
Hi Nickvergessen and MorrisJobke,

thanks for the reply. I'm using a custom Nextcloud theme and i thought if i use a custom theme i should disable the theming app. If i disable the theming app there is always the "custom cloud" logo in my mail template.

I dont want to add any text or something like this in my mails, i just want to add my own logo.  If i do the changes in the config.php and mailer.php - where can i set the logo file?

**Comment by LukasReschke** [comment]
> Will be also available in 12.0.1

I don't find this commit in stable12, did we forget a backport here?

**Comment by LukasReschke** [comment]
I opened a backport PR at https://github.com/nextcloud/server/pull/5796

**Pull request merged**
