### PR TITLE
Don't write back .htaccess file on a RO filesystem

### LINKED ISSUE #42286: [Bug]: `occ maintenance:install` fails on read-only htdocs directory
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since Nextcloud 27.1.5 and Nextcloud 28.0.0 the occ command for manual install requires write-access to the htdocs directory. This were not the case before and allowed Nextcloud to be deployed via the SNAP environment.

Ref: https://github.com/nextcloud-snap/nextcloud-snap/pull/2631#issuecomment-1855931895

This prevents us from updating our snap packges at the moment as the snap environment is read-only for security reasons.

Is there a workaround for this to execute manual install without the need for write-access?

### Steps to reproduce

1. Create a read-only webspace.
2. Install Nextcloud 27.1.5 or 28.0.0 there.
3. Execute the installation process via the command `occ maintenance:install`.
4. The command will fail because it requires write-access to the htdocs direcotry.

### Expected behavior

Do not require write-access on `occ maintenance:install` or at least try-catch and skip the steps that would write to the htdocs directory, so the command will execute successfully - like in v27.1.4 and earlier.

### Installation method

Community SNAP package

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/42286

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Altahrim — APPROVED** [review]

**Comment by come-nc** [comment]
Shouldn’t we at least log something? Not being able to update the htaccess has consequences, no?

**Comment by solracsf** [comment]
We can, but here we're dealing with RO filesystems mainly.
Nevertheless, we can also add a log line, can't hurt :)

In RW filesystems, it will throw and log here: https://github.com/nextcloud/server/blob/cd32db63f7acba753888c8f5b60a30d1d10035e1/lib/private/Setup.php#L562-L573

**Comment by Pilzinsel64** [comment]
Would be cool to get (backports of this) into the next minor updates for 28 and 27 if applicable, so we can push the latest security fixes to our users. :) https://github.com/nextcloud-snap/nextcloud-snap/pull/2631#issuecomment-1861831961

**Review by come-nc — APPROVED** [review]

**Comment by stondino00** [comment]
Any way we can patch this on 27.1.5 for the snap rather than waiting until the backport in 27.1.6?  Thanks

**Comment by kyrofa** [comment]
> Any way we can patch this on 27.1.5 for the snap rather than waiting until the backport in 27.1.6? Thanks

I don't believe we can do that without violating the integrity checks. We're going to have to wait for 27.1.6.

**Pull request merged**
