### PR TITLE
l10n: Correct text string

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by rakekniven** [comment]
Dup of #32537

**Comment by Valdnet** [comment]
I know, that's why I closed it quickly 😉.

**Comment by rakekniven** [comment]
Added my comment for reference.

**Comment by Valdnet** [comment]
Yes, I know 😉. I was translating another text string and thought there was no comment. It was only after the PR was released that I noticed your comment for this string and that's why I quickly closed this PR.

**Pull request closed without merging**
