### PR TITLE
Add new "Recent files" icon to files app

### PR DESCRIPTION
**Pull request by Bugsbane**
Includes both the compressed svg and the new nav-icon-recent CSS class

### CODE REVIEW

**Comment by icewind1991** [comment]
The icon should be colored black instead of gray (showing it in different grayscale values is handled in css with opacity)

Icon looks good otherwise

**Comment by Bugsbane** [comment]
Ok, black version is added to my repo.

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by jancborchardt** [comment]
Nice, very cool @Bugsbane :) Happy to have you on board as fellow icon designer!

**Comment by jancborchardt** [comment]
Btw @Bugsbane you have been invited to the Nextcloud organization (and the design team) some time ago already, you need to accept it at https://github.com/nextcloud :)

**Comment by Bugsbane** [comment]
Oh, cool. Thanks! Happy to be able to help out. :)

**Comment by Bugsbane** [comment]
So, @jan, I joined Nextcloud, but couldn't see how to join the design group.

**Comment by jancborchardt** [comment]
You're already part of it as I added you. :)

**Comment by jancborchardt** [comment]
(It's the tab »Teams« on the organization page.)

**Pull request merged**
