### PR TITLE
15.0.13 RC1

### PR DESCRIPTION
**Pull request by rullzer**
* #17013 Return the proper jailed path when requesting the root path
* #17272 Fix directory detection for s3
* #17297 Correctly detect the mimetype from uploads
* #17442 Don't call basename on null
* #17540 Only cache the mimetype if the file exists
* #17587 Added documentation links on settings pages
* #17642 Stable17] Load additional scripts on help page
* #17660 Stable16] fix method scope
* #17733 Fix DAV mimetype search
* [gallery#549](https://github.com/nextcloud/gallery/pull/549) Force close all tooltips when closing sharing menu
* [nextcloud_announcements#58](https://github.com/nextcloud/nextcloud_announcements/pull/58) Use correct route to generate
* [nextcloud_announcements#59](https://github.com/nextcloud/nextcloud_announcements/pull/59) Adjust target branch
* [survey_client#100](https://github.com/nextcloud/survey_client/pull/100) Name of the collector is `Php`.

### CODE REVIEW

**Comment by kesselb** [comment]
Please don't forget about: https://github.com/nextcloud/server/pull/17540#discussion_r338396256

**Comment by rullzer** [comment]
Was done in 965a7b392ff49c0d4a97c9a968a0afc023264805 ;)

**Comment by kesselb** [comment]
Sneaky ;) Is it enough? If `$this->path` is null it will :boom:

**Comment by rullzer** [comment]
> Sneaky ;) Is it enough? If `$this->path` is null it will boom

Yeah fair point
care to shoot in a PR?

**Comment by rullzer** [comment]
> > Sneaky ;) Is it enough? If `$this->path` is null it will boom
> 
> Yeah fair point
> care to shoot in a PR?

let me do it actually and then you press approve ;)

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/pull/17760

**Pull request merged**
