### PR TITLE
Tag cleanup

### PR DESCRIPTION
**Pull request by rullzer**
This gets rid of an internal route that was already broken for a long time.

Part of the big, ongoing, technical debt cleanup.

CC: @LukasReschke @nickvergessen @icewind1991 @MorrisJobke

### CODE REVIEW

**Comment by icewind1991** [comment]
This is replaced by the dav stuff right?

**Comment by rullzer** [comment]
Kind of.
Favorites is done via DAV already.

Those were the routes for https://github.com/nextcloud/server/blob/master/lib/public/ITagManager.php basically. But that old had important broken routes so we can be pretty sure it wasn't used.

**Comment by nickvergessen** [comment]
:+1:

**Comment by LukasReschke** [comment]
lgtm

**Pull request merged**
