### PR TITLE
ownCloud -> Nextcloud

### PR DESCRIPTION
**Pull request by enoch85**
cc @nextcloud/developers

### CODE REVIEW

**Comment by LukasReschke** [comment]
👍

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by jancborchardt** [comment]
Hahahaha :+1: – can you also prepare backports to stable10 and stable9?

**Comment by enoch85** [comment]
@jancborchardt Maybe ;)

**Comment by nickvergessen** [comment]
I hope this doesn't break integration tests :see_no_evil:

**Comment by LukasReschke** [comment]
Oh. Right. It likely will do that 🎉

**Comment by nickvergessen** [comment]
Viola, please fix @enoch85 files:
* build/integration/features/webdav-related.feature
* build/integration/features/dav-v2.feature

**Comment by nickvergessen** [comment]
And while you are on it, there is more ownCloud writing in the integration tests ;)

**Comment by enoch85** [comment]
Tried `find . -type f -exec sed -i 's|ownCloud|Nextcloud|g' {} +` but it wasn't that easy. :(

**Comment by MorrisJobke** [comment]
```


    /drone/src/github.com/nextcloud/server/build/integration/features/dav-v2.feature:12
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:12
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:35
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:44
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:62
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:144
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:151
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:165
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:179
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:191
```

**Comment by enoch85** [comment]
@MorrisJobke and what does that mean?

**Comment by MorrisJobke** [comment]
> @MorrisJobke and what does that mean?

I will fix them.


Oh sorry. Those are the failing tests. Forgot to copy the line above.

**Comment by enoch85** [comment]
> I will fix them.

@MorrisJobke Thanks!!

**Comment by rullzer** [comment]
@MorrisJobke you missed a few:

```
--- Failed scenarios:

    /drone/src/github.com/nextcloud/server/build/integration/features/sharing-v1.feature:304
    /drone/src/github.com/nextcloud/server/build/integration/features/sharing-v1.feature:488
    /drone/src/github.com/nextcloud/server/build/integration/features/sharing-v1.feature:509
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:35
    /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:44
````

**Comment by MorrisJobke** [comment]
> @MorrisJobke you missed a few:

Fixed them too.

**Pull request merged**
