### PR TITLE
[stable28] fix: Properly take show_hidden user setting into account for file listing

### PR DESCRIPTION
**Pull request by juliusknorr**
- fix: Properly take show_hidden user setting into account for file listing
- fix: Also filter out undefined entries from the file list

Combined backport of #42006 and #42021

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by blizzz** [comment]
new or old  :x: ?  

> │ ✖  settings/apps.cy.ts                      01:39        6        5        1        -        - │

**Comment by juliushaertl** [comment]
"Newer" but unrelated, also fails on the last merged commit https://github.com/nextcloud/server/actions/runs/7104000542/job/19338247398

**Pull request merged**
