### PR TITLE
docs: trusted_proxies support IPv6 ranges

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: /

## Summary

Support for IPv6 ranges was added by https://github.com/nextcloud/server/pull/32615

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by kesselb** [comment]
cc @sleiner

**Review by szaimen — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Review by christianlupus — APPROVED** [review]
That should be fine from my understanding.

**Review by come-nc — APPROVED** [review]

**Comment by kesselb** [comment]
Backport for stable25: https://github.com/nextcloud/server/pull/35963

**Pull request merged**
