### PR TITLE
[stable11] Directly fix invalid values of DTEND and DTSTART

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #4066

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
nice. Worked here... lets see if it works for everybody...

**Review by MorrisJobke — APPROVED** [review]
Tested and works - at least for my calendar

**Comment by toeff** [comment]
Updated from 11.0.2.7 to 11.0.3.2
Sadly doesn't work with one of my calendars. Still geting an "Internal Server Error" when exporting. Logfile says: "Fatal	webdav	Sabre\VObject\InvalidDataException: Unsupported VALUE parameter for DTEND property. You supplied """

**Comment by nickvergessen** [comment]
@rullzer empty DTEND?! Ever heard of that?

**Comment by rullzer** [comment]
Nope :confused: 
Maybe there was nothing supplied at all?

**Comment by toeff** [comment]
I have solved my problem through an export via thunderbird and then re-import as a new calendar.

**Comment by PiQuer** [comment]
Just a heads up if someone still gets the internal server error: check your database for `DTEND;VALUE=;`. I had 8 year old entries of the form

`DTEND;VALUE=;TZID=Europe/Vienna:20110330T120000`

with no idea where they came from. They could be fixed by replacing `;` for `:` in the following lines of ` apps/dav/lib/Migration/CalDAVRemoveEmptyValue.php`:

line 61:
`                $pattern = ';VALUE=:';`
line 69:
`                        $data = preg_replace('/' . $pattern . '/', ':', $calObject['calendardata']);`

Then run `occ maintenance:repair`. Maybe the script could look for both patterns?

**Pull request merged**
