### PR TITLE
[Small] warning is now selecteable

### PR DESCRIPTION
**Pull request by ArtificialOwl**
Signed-off-by: Maxence Lange <maxence@nextcloud.com>

### CODE REVIEW

**Comment by daita** [comment]
warning/error message should be selecteable so the user can copy the text in clipboard.

**Comment by MorrisJobke** [comment]
This worked for me before already. Which browser did you use?

**Comment by daita** [comment]
firefox 54, the issue is during a nextcloud installation

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
