### PR TITLE
Add Neon user-agent

### LINKED ISSUE #9: Submit user-agent for detection in Nextcloud
https://github.com/nextcloud/server/blob/279e06/apps/settings/src/components/AuthToken.vue#L95

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/nextcloud/server/pull/33296

Closes https://github.com/jld3103/nextcloud-neon/issues/9

@CarlSchwan

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
Nice new name :)

**Comment by jld3103** [comment]
Yeah I actually like it a lot more than the old one :)

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by jld3103** [comment]
Thanks a lot!

**Pull request merged**
