### PR TITLE
Expose subscription calendars

### LINKED ISSUE #5628: Events from subscribed calendar not showing up in Upcoming widget.
### Steps to reproduce

1. Install the latest calendar app (4.6.0 at time of writing)
2. Subscribe to a public calendar (e.g. an group event list)
3. Open dashboard.
(This is not reproduceable using app version <4.5.0)

### Expected behavior

Events from subscribed calendar is showing up in the list.

### Actual behaviour

Only events from non-subscribed calendars are appearing.

### Calendar app version

4.6.0 (any version >= 4.5.0)

### CalDAV-clients used

Not relevant.

### Browser

Microsoft Edge 120, Firefox 120

### Client operating system

Windows, Ubuntu, Android

### Server operating system

Cloudlinux

### Web server

Other

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.4

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - appointments: 1.15.4
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.0
  - camerarawpreviews: 0.8.4
  - cfg_share_links: 4.2.0
  - checksum: 1.2.2
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.2
  - emlviewer: 1.0.8
  - epubviewer: 1.5.3
  - external: 5.2.1
  - externalportal: 1.2.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_3dmodelviewer: 0.0.12
  - files_downloadactivity: 1.16.0
  - files_external: 1.19.0
  - files_markdown: 2.4.1
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - files_zip: 1.4.0
  - forms: 3.4.3
  - imageconverter: 1.3.5
  - integration_github: 2.0.6
  - integration_youtube: 0.1.5
  - libresign: 7.1.1
  - login_notes: 1.3.1
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.0
  - metadata: 0.19.0
  - music: 1.9.1
  - news: 24.0.0
  - notes: 4.9.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - occweb: 0.1.1
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quicknotes: 0.8.10
  - quota_warning: 1.18.0
  - richdocuments: 8.2.3
  - secrets: 1.5.2
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - sharepoint: 1.15.0
  - side_menu: 3.11.2
  - socialsharing_email: 3.0.1
  - spreed: 17.1.3
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.15.0
  - transfer: 0.6.1
  - twofactor_backupcodes: 1.16.0
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.17.0
  - video_converter: 1.0.6
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - circles: 27.0.1 (installed 26.0.0)
  - contactsinteraction: 1.8.0 (installed 1.7.0)
  - encryption: 2.15.0
  - firstrunwizard: 2.16.0 (installed 2.16.0)
  - nextcloud_announcements: 1.16.0 (installed 1.15.0)
  - password_policy: 1.17.0 (installed 1.16.0)
  - photos: 2.3.0 (installed 2.2.0)
  - recommendations: 1.6.0 (installed 1.5.0)
  - related_resources: 1.2.0 (installed 1.1.0-alpha1)
  - support: 1.10.0 (installed 1.9.0)
  - survey_client: 1.15.0 (installed 1.14.0)
  - suspicious_login: 5.0.0 (installed 4.4.0)
  - systemtags: 1.17.0 (installed 1.16.0)
  - user_ldap: 1.17.0
  - user_status: 1.7.0 (installed 1.7.0)
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "en",
        "default_locale": "en_gb",
        "app_install_overwrite": [
            "theming_customcss",
            "checksum",
            "emlviewer",
            "metadata",
            "socialsharing_email",
            "transfer",
            "weather",
            "files_3d",
            "podcast",
            "libresign",
            "files_downloadactivity"
        ],
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "simpleSignUpLink.shown": false,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": " 465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "music.enable_radio_hls": true,
        "music.podcast_auto_update_interval": 1,
        "remember_login_cookie_lifetime": 1296000,
        "htaccess.RewriteBase": "\/",
        "session_lifetime": 86400,
        "session_keepalive": true,
        "filelocking.enabled": false,
        "appcodechecker": false,
        "enable_previews": false,
        "auto_logout": false,
        "maintenance": false,
        "loglevel": 0,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [
            "guest_app"
        ],
        "connectivity_check_domains": [
            "www.google.cn",
            "one.one.one.one"
        ]
    }
}
```

### Web server error log

_No response_

### Log file

_No response_

### Browser log

_No response_

### Additional info

Server: LiteSpeed Enterprise.

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: https://github.com/nextcloud/calendar/issues/5628

## Summary

Make calendar subscriptions available via php api. 

## TODO

- [x] Check getPermissions
- [x] Tests
- [x] ~PR for Calendar to increase the event limit~ Replaced by https://github.com/nextcloud/server/pull/45222

## Test cases

- [ ] Add subscription
- [ ] Delete subscription
- [ ] Show/Hide/Rename subscription
- [ ] Export subscription
- [ ] Export event

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by kesselb** [comment]
Patch the calendar app like below for easier testing:

```
diff --git a/lib/Dashboard/CalendarWidget.php b/lib/Dashboard/CalendarWidget.php
index f1bbd231e..83d978d2d 100644
--- a/lib/Dashboard/CalendarWidget.php
+++ b/lib/Dashboard/CalendarWidget.php
@@ -144,7 +144,7 @@ class CalendarWidget implements IAPIWidget, IButtonWidget, IIconWidget, IOptionW
                        return [];
                }
                $dateTime = (new DateTimeImmutable())->setTimestamp($this->timeFactory->getTime());
-               $inTwoWeeks = $dateTime->add(new DateInterval('P14D'));
+               $inTwoWeeks = $dateTime->add(new DateInterval('P60D'));
                $options = [
                        'timerange' => [
                                'start' => $dateTime,
@@ -153,7 +153,7 @@ class CalendarWidget implements IAPIWidget, IButtonWidget, IIconWidget, IOptionW
                ];
                $widgetItems = [];
                foreach ($calendars as $calendar) {
-                       $searchResult = $calendar->search('', [], $options, $limit);
+                       $searchResult = $calendar->search('', [], $options);
                        foreach ($searchResult as $calendarEvent) {
                                // Find first recurrence in the future
                                $recurrence = null;
```

**Comment by kesselb** [comment]
Example calendar for testing: https://www.feiertage-deutschland.de/kalender-download/ics/feiertage-deutschland.ics

**Comment by tcitworld** [comment]
Can this expose the subscription source as well? Would be handy for https://github.com/nextcloud/calendar/issues/5168 too

**Comment by kesselb** [comment]
> Can this expose the subscription source as well? 

Added getSource to CachedSubscriptionImpl

**Review by ChristophWurst — APPROVED** [review]
Makes sense

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
