### PR TITLE
replace close:// streamwrapper with CallBackWrapper

### PR DESCRIPTION
**Pull request by icewind1991**
The `close://` stream wrapper is from an ancient time before I mastered the magic of php stream wrappers.

`CallBackWrapper` is better doesn't rely on hidden static state.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 Conflicts and failing tests

**Comment by icewind1991** [comment]
all fixed

**Comment by rullzer** [comment]
If somebody could give the external file backends a try then I'm fine.

**Comment by MorrisJobke** [comment]
I rebased to fix the merge conflict.

**Comment by rullzer** [comment]
@MorrisJobke do it again!

**Comment by MorrisJobke** [comment]
> @MorrisJobke do it again!

Done :)

**Comment by AdamWill** [comment]
Is there some way I can be blacklisted from this MentionBot thing? I am not at all interested in working on own/nextcloud any more, sorry.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]

**Pull request merged**
