### PR TITLE
Dependabot/various

### PR DESCRIPTION
**Pull request by skjnldsv**
Merge all dependabots updates into one release for easier management

### CODE REVIEW

**Comment by skjnldsv** [comment]
@rullzer did you force push to the wrong branch?

**Comment by rullzer** [comment]
No. I force pushed because all of the unit tests did boom ;-)

**Comment by skjnldsv** [comment]
ok :)

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
Let's try to get this in today to finish #19125

**Review by ChristophWurst — APPROVED** [review]

**Review by georgehrke — APPROVED** [review]

**Pull request merged**
