### PR TITLE
perf(autoloading): Add authoritative autoloader for theming

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Resolves: # 

## Summary

Improves autoloading performance. Benchmarks in https://github.com/nextcloud/server/pull/36112.

## TODO

- [x] Add composer config
- [x] Update autoloaders

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
CI fails because of https://github.com/nextcloud/server/commit/4e1d50169651f608e4728d72c07e463c62a39b87

**Review by rullzer — APPROVED** [review]

**Review by come-nc — APPROVED** [review]
:elephant:

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@ChristophWurst Mind to rebase?

**Comment by ChristophWurst** [comment]
E2E cypress fails. Can I ignore that?

**Comment by juliushaertl** [comment]
Looks unrelated, but restarted them as I haven't seen that specific error before.

**Comment by juliushaertl** [comment]
Usual failure now

**Pull request merged**
