### PR TITLE
Allow hidden smb shares

### LINKED ISSUE #15567: Dollar sign in SMB external storage not supported anymore
After updating from v15 to v16, my SMB storages with a dollar sign in the configuration name (useful to hide shares in a Windows network) doesn't work anymore. If I rename with share without the dollar sign it works

_EDIT: The bug is just on the home page of the file app; if I try to access the storage with /?dir=myshare in the URL it works_

### Steps to reproduce
1. Configure a SMB storage with a dollar in the name
2. Go to file app

### Expected behaviour
I should be able to click on the share and access its files

### Actual behaviour
The share name is red and when I click on it I have an error message: "Mount configuration incomplete. Do you want to review mount point config in admin settings page?"
In the admin logs I have this error: "A placeholder was not substituted: myshare$ for mount type \OCA\Files_External\Lib\Storage\SMB"

### Server configuration
Docker image nextcloud:16

### PR DESCRIPTION
**Pull request by kesselb**
Fix #15567 

A hidden smb share ends with $. This patch changes the placeholder
detection to allow shares with $ at the end.

### CODE REVIEW

**Comment by kesselb** [comment]
@blizzz i tried to add some test cases for the array as $option but not sure which format is expected. 

https://github.com/nextcloud/server/blob/ae7f89fd9f2bb87c0254f5fa087d0d9472612644/apps/files_external/lib/config.php#L288-L294

I guess we should pass `$optionItem` instead of `$option` to `arePlaceholdersSubstituted`?

**Comment by blizzz** [comment]
> @blizzz i tried to add some test cases for the array as $option but not sure which format is expected.

Anything that is entered in the external storage configuration (but the mount name) will be passed there (just for the password there should be some exception somewhere). We pass only strings, and if it is an array we go a level deeper.

**Comment by kesselb** [comment]
> > @blizzz i tried to add some test cases for the array as $option but not sure which format is expected.
> 
> Anything that is entered in the external storage configuration (but the mount name) will be passed there (just for the password there should be some exception somewhere). We pass only strings, and if it is an array we go a level deeper.

Thank you ;) Mind to check the code? I think we call `arePlaceholdersSubstituted` with the wrong variable here.

**Comment by kesselb** [comment]
As reference: #15654 

I guess $ is a valid character for an smb share name: https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata Do you think we could use another character for placeholders?

**Review by icewind1991 — APPROVED** [review]

**Comment by kesselb** [comment]
As reference: https://github.com/nextcloud/server/issues/15934

Looks like $ is also a valid character for an smb username.

**Comment by wiswedel** [comment]
Fix #15934

**Comment by Trujo-Dilar** [comment]
Like wiswedel I can confirm this patch resolve hidden share problem, with this you can use //server/share$.
but $user substitution fail (with and without patch).

**Comment by skjnldsv** [comment]
To merge?

**Comment by wiswedel** [comment]
> To merge?

@skjnldsv At least @icewind1991 already approved.
@schiessle or/and @blizzz would make good 2nd reviewers.

**Comment by kesselb** [comment]
> https://github.com/nextcloud/server/blob/ae7f89fd9f2bb87c0254f5fa087d0d9472612644/apps/files_external/lib/config.php#L288-L294
> 
> I guess we should pass `$optionItem` instead of `$option` to `arePlaceholdersSubstituted`?

@schiessle / @blizzz If you do a second review please look at the comment. I still think there is something broken. Thank you :+1:

**Comment by icewind1991** [comment]
@kesselb you are correct I think, also the 2nd `is_array` check seems wrong and should be removed.

**Comment by hessercan** [comment]
16.0.3 breaks this patch

**Comment by blizzz** [comment]
@kesselb yes, in hindsight, i agree with @icewind1991

**Comment by kesselb** [comment]
Pushed a fix for the invalid recursion. I'm not sure if the feature now works as expected. Could not find any information under which conditions `$option` should be an array.

**Comment by skjnldsv** [comment]
Failure unrelated :)

**Review by skjnldsv — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Pull request merged**
