### PR TITLE
fix-dialog-buttons

### PR DESCRIPTION
**Pull request by marcoambrosini**
No clickable things shorter / narrower than 44px :) 

| Before | After |
| ------ | ----- |
| Screenshot from 2020-12-18 15-37-37  |  Screenshot from 2020-12-18 15-38-56 |

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Review by jancborchardt — DISMISSED** [review]
The buttons need more left and right padding, so that it doesn't visually look less than the top and bottom padding.

**Comment by ma12-co** [comment]
Screenshot from 2020-12-22 11-33-40

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@ma12-co The bundles need an update:

```
Uncommited changes in webpack build
HEAD detached at pull/24770/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   core/js/dist/main.js
	modified:   core/js/dist/main.js.map
```

**Comment by skjnldsv** [comment]
Good to go

**Pull request merged**
