### PR TITLE
Various flow related fixes

### LINKED ISSUE #18495: Flow: Browse the app store is not possible for users
### Steps to reproduce
1. Login as user (without admin permission)
2. Visit personal settings
3. Go to flow
4. See "More flows" button

### Expected behaviour

I can either add more flows or don't see this button. Probably something like "there are no flows yet. ask your admin to add more flows via the app store".

### Actual behaviour
image

### LINKED ISSUE #18510: Flow: fail to pick a third party entity event
Can be tried with otherwise incomplete https://github.com/blizzz/flow_http_requests

1. Have spreed master running
2. Have flow_http_requests enabled (or anything else that registers a new entity)
3. Go to personal flow settings
4. start a "Write to conversation" flow
5. Try to pick "Web request" (or your event)

The expected check mark does not show up, and the event is not written to the list. Only selecting the files related events is functioning.

@juliushaertl

### PR DESCRIPTION
**Pull request by juliusknorr**
- [x] Allow selecting other event types (fix #18510) 
- [x] Fix app store link and hide it for users (fix #18495 #18500)
- [x] Flow: Invalid rule will emit a log message #18496
- [x] https://github.com/nextcloud/server/issues/18191
  - [x] The icons in the action boxes can be a bit closer to the text below. Should have same distance from the text as the button below #17997 (comment)
  - [x] The link to the apps is not created correctly when running in a subfolder

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by blizzz — DISMISSED** [review]
I always see "The configuration is invalid" even if it is not (existing and new rules). Despite saving works.

**Comment by juliushaertl** [comment]
> I always see "The configuration is invalid" even if it is not (existing and new rules). Despite saving works.

Ah indeed, seems to only occur with multiple checks. Fix pushed.

**Review by blizzz — COMMENTED** [review]
Thanks, works now!

Just, an other thing: unconditional flows (without a check) were OK before. Rejecting them could potentially break older once… Not that I have an idea where they would be useful. That might come back to us. Otherwise, +1.

**Review by kesselb — APPROVED** [review]
- Fix app store link and hide it for users (fix #18495 #18500) 
- Flow: Invalid rule will emit a log message #18496

:+1:

**Comment by juliushaertl** [comment]
> Just, an other thing: unconditional flows (without a check) were OK before. Rejecting them could potentially break older once… Not that I have an idea where they would be useful. 

Yes, I was thinking the same, but I also could not think of a rule that would make sense without any check.

**Comment by blizzz** [comment]
> > Just, an other thing: unconditional flows (without a check) were OK before. Rejecting them could potentially break older once… Not that I have an idea where they would be useful.
> 
> Yes, I was thinking the same, but I also could not think of a rule that would make sense without any check.

Config switch :p 

Okay. Existing ones should run, but not be modifyable anymore. Let's just be sure to document it in the release notes.

**Review by blizzz — APPROVED** [review]

**Pull request merged**
