### PR TITLE
adjust autotest.sh to also wait 600 seconds for mysqlmb4

### PR DESCRIPTION
**Pull request by MorrisJobke**
@LukasReschke This should solve your problem ;)

All other DBs also wait 600 seconds ;)

cc @nickvergessen @rullzer

### CODE REVIEW

**Comment by LukasReschke** [comment]
:rocket: :+1:

**Comment by rullzer** [comment]
Fine by me.
:+1:

**Comment by nickvergessen** [comment]
Postgres timed out... 🎢

**Comment by MorrisJobke** [comment]
> Postgres timed out... 🎢

Different topic :(

**Pull request merged**
