### PR TITLE
[stable28] fix(files): drag and drop

### PR DESCRIPTION
**Pull request by AndyScherzinger**
manual backport of #42366

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Manual backport for your convenience @skjnldsv

**Review by skjnldsv — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by b90g** [comment]
thanks for the good work, hoping things will be fixed with next release.

**Comment by HLFH** [comment]
I don't think it works on Safari @AndyScherzinger, only on Chrome.

**Comment by supr4s** [comment]
I confirm that the problem has been corrected by upgrading to 28.0.2.

**Comment by melroy89** [comment]
Thank you....

**Pull request merged**
