### PR TITLE
enh(SpeechToText): Allow providers to declare a dynamic ID instead of using className

### PR DESCRIPTION
**Pull request by marcelklehr**
this allows AppAPI to register anonymous classes as SpeechToText providers

see [https://github.com/cloud-py-api/app_api/pull/60](https://github.com/cloud-py-api/app_api/pull/60)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by marcelklehr** [comment]
(I'm sort of sad about the beauty we lose with this, but alas)

**Comment by marcelklehr** [comment]
Please review

**Review by juliusknorr — APPROVED** [review]
Code looks good 👍

**Review by andrey18106 — APPROVED** [review]

**Review by bigcat88 — APPROVED** [review]

**Review by julien-nc — APPROVED** [review]
:elephant:

**Pull request merged**
