### PR TITLE
fix(files): Remove confusing table header labels

### LINKED ISSUE #41833: [BITV] 9.1.3.1e/3.1 - Although the table with directories and files visually has correct headings, these headings are being overridden by the use of the "aria-label" attribute, resulting in the content of data cells being announced with column headers like "Sort list by..." during screen reader output. The "aria-label" attribute should be removed, as the sorting status is conveyed through the "aria-sort" attribute. (2)
image

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-3f0ff0bc0e-v3-n1

9.1.3.1e/11.1 - https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-3f0ff0bc0e-v11-n1

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #41833

## Summary
For screen readers the table header was very verbose and confusing, as the SR reads out e.g. "sort list by name button FILENAME" for every row / file. Instead reduce it to "name button FILENAME" and add information about sorting to caption, as recommended by WCAG [1]

[1]: https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/sortable-table/

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
While I'm here

**Comment by susnux** [comment]
/backport bb12b8e0427e9a3845d8d618727f5644930e4f0f to stable28

**Comment by susnux** [comment]
/backport bb12b8e0427e9a3845d8d618727f5644930e4f0f to stable28

**Pull request merged**
