### PR TITLE
Add OpenAPI CI

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

This will automatically check for changes and require the OpenAPI specifications to be up-to-date. The CI will fail right now because the `files_external` app has changed since I added all my changes. I will fix that and then this CI will go green and catch any future problems.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by marcelklehr — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by provokateurin** [comment]
Yep, will mark it as ready as soon as the other PR is merged and the CI will no longer fail

**Comment by provokateurin** [comment]
lol apparently the ci php version sorts files in a different order than my local php version...

**Comment by provokateurin** [comment]
something is really strange, the ci only works sometimes and i have zero clue why. locally it works all the time (also with https://github.com/nektos/act)

**Comment by provokateurin** [comment]
Alright, it was the sorting of the capabilities files which seems to be different on our self-hosted runners. I accidentally first used ksort on the files list which didn't change anything, but now it works. Now I'm waiting for https://github.com/nextcloud/server/pull/39809 so that this CI would actually turn green.

**Pull request merged**
