### PR TITLE
Add settings to not match userID during full match

### PR DESCRIPTION
**Pull request by artonge**
This option allow to not match the `userID` when disabling username autocompletion in share dialog, but enabling autocompletion on exact match.

Setting | userID search | Display Name search
-- | -- | --
Screenshot from 2022-04-06 12-41-26 | Screenshot from 2022-04-06 12-47-03 | Screenshot from 2022-04-06 12-47-20
Screenshot from 2022-04-06 12-41-19 | Screenshot from 2022-04-06 12-47-29 | Screenshot from 2022-04-06 12-47-20

Default to true.
Is hidden when full match is disabled:
Screenshot from 2022-04-06 12-52-32

Fix https://github.com/nextcloud-gmbh/customer-feature-requests/issues/6

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
integration tests need more adjustments

**Review by Pytal — APPROVED** [review]

**Comment by skjnldsv** [comment]
@artonge  Documentation missing?

**Pull request merged**
