### PR TITLE
Strict typing lib/base.php

### PR DESCRIPTION
**Pull request by come-nc**
Use `strict_types` and fix as many psalm errors as possible in `lib/base.php` and a few related classes.

### CODE REVIEW

**Comment by CarlSchwan** [comment]
I like this but if we are gonna merge it we should do it very early in the release cycle ;)

**Comment by come-nc** [comment]
Tests are failing, let me look into it.

**Comment by come-nc** [comment]
ping @CarlSchwan @ChristophWurst Can I get reviews before this get into conflicts?

**Comment by come-nc** [comment]
(rebased on master)

**Review by ChristophWurst — APPROVED** [review]
The file is still a mess but a lot fancier now :)

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
