### PR TITLE
Make sure we only use numbers as length

### LINKED ISSUE #1707: [DAV] Download fails for big files: stream_copy_to_stream() throws an error
### Steps to reproduce
1. Try to download a big file on Nextcloud, PHP7.0, 32 Bit arm (> 2 GB)
2. Check downloaded file and log
3. File is empty, log shows the error immediately
### Expected behaviour

File with size of 9 GB should be downloaded
### Actual behaviour

0 Byte file created, no error message but logged error
### Server configuration

**Operating system**: 
Ubuntu 16.04

**Web server:** 
Apache

**Database:** 
MySQL

**PHP version:** 
PHP 7

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Owncloud 9 -> Nextcloud 10 -> Nexcloud 11 alpha
**Where did you install Nextcloud from:**
Git
**Signing status:**
**List of activated apps:**
**The content of config/config.php:**
**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:** Chrome

**Operating system:** MacOS 10.12
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
{"reqId":"He91ouATEMBQ7rkEw65e","remoteAddr":"127.0.0.1","app":"PHP","message":"stream_copy_to_stream() expects parameter 3 to be integer, string given at \/media\/data\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#78","level":3,"time":"October 11, 2016 20:58:34","method":"GET","url":"\/remote.php\/webdav\/Media-Fernsehaufnahmen\/arte_HD\/arte_HD_Der_Tag_der_Kr%C3%A4hen20160615_135900.ts","user":"name","version":"9.2.0.4"}
{"reqId":"DKWW6ajns8HKX8pETQS+","remoteAddr":"127.0.0.1","app":"PHP","message":"stream_copy_to_stream() expects parameter 3 to be integer, string given at \/media\/data\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#78","level":3,"time":"October 11, 2016 20:58:58","method":"GET","url":"\/remote.php\/webdav\/Media-Fernsehaufnahmen\/arte_HD\/arte_HD_Die_wahre_Macht_des_Vatikan_(2_2)20160207_144900.ts","user":"name","version":"9.2.0.4"}
```

</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
A try to fix #1707

### CODE REVIEW

**Comment by derkostka** [comment]
@nickvergessen . Sorry, does not help for #1707 . I have tried to understand the Architecture, in order to find things out for myself, but i didn´t get it right now.

**Comment by nickvergessen** [comment]
Added the unit tests, ready for review since this is fixing a different issue.
cc @LukasReschke @MorrisJobke

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@karlitschek We should backport this to stable9 and stable10

@nickvergessen Could you open the backport PRs? Thanks

**Comment by karlitschek** [comment]
please backport 👍

**Pull request merged**
