### PR TITLE
feat: Ship downloadlimit

### LINKED ISSUE #44038: Ship files_downloadlimit and enable by default
- [x] commit compiled js assets https://github.com/nextcloud/files_downloadlimit/pull/231
- [ ] Update shipped.json https://github.com/nextcloud/server/pull/44040
- [x] Add to release script https://github.com/nextcloud-gmbh/release-script/pull/169
- [x] Add to documentation https://github.com/nextcloud/documentation/pull/11618
- [x] Add to github helpers https://github.com/nextcloud/github_helper/pull/106

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Resolve https://github.com/nextcloud/server/issues/44038

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by blizzz — APPROVED** [review]
The PR is in draft state though?

**Comment by Pytal** [comment]
> The PR is in draft state though?

Ready!

**Comment by blizzz** [comment]
rebase was not necessary here, was it?

**Comment by Pytal** [comment]
> rebase was not necessary here, was it?

Nope sorry my bad 🙈, should've just restarted the specific workflow I wanted to rerun

**Review by sorbaugh — APPROVED** [review]

**Comment by Pytal** [comment]
Cypress unrelated, already fixed on master

Safe to merge I believe now @blizzz?

**Pull request merged**
