### PR TITLE
Users page lazy multiselect group dropdowns

### PR DESCRIPTION
**Pull request by blizzz**
Backport from https://github.com/owncloud/core/pull/25922

Improves rendering time of Users page. Upstream backported it down to 9.0, so i request also backporting this down to Nextcloud 9. @karlitschek 

Please review @nickvergessen  @icewind1991 @LukasReschke

### CODE REVIEW

**Comment by karlitschek** [comment]
agreed. please backport

**Comment by nickvergessen** [comment]
Page loads really a lot faster now :+1:

**Comment by rullzer** [comment]
LGTM

**Comment by blizzz** [comment]
Backports
stable10: https://github.com/nextcloud/server/pull/1174
stable9: https://github.com/nextcloud/server/pull/1175

**Pull request merged**
