### PR TITLE
Add setting to ignore email during search

### PR DESCRIPTION
**Pull request by artonge**
Same as https://github.com/nextcloud/server/pull/31857 be for email.

## Technical changes when the option is disabled

- Add a check in [lib/private/Collaboration/Collaborators/UserPlugin.php](https://github.com/nextcloud/server/blob/master/lib/private/Collaboration/Collaborators/UserPlugin.php) to not check if the email matches the search
- Disable [lib/private/Collaboration/Collaborators/MailPlugin](https://github.com/nextcloud/server/blob/master/lib/private/Collaboration/Collaborators/MailPlugin.php) when full match is enabled.
- Remove search options from the Share settings and restrict setting them from the CLI

## Result

Enabled | Disabled
-- | --
Screenshot from 2022-04-13 15-34-33 | Screenshot from 2022-04-13 15-34-41

### CODE REVIEW

**Comment by artonge** [comment]
@jancborchardt should we keep those settings in the Share admin settings view. We could also remove them from the web UI and let the user set them from the CLI with `occ`. We could also move them in the config.php.

**Comment by jancborchardt** [comment]
@artonge CLI setting for both this and the other setting seems enough, yes.

**Comment by artonge** [comment]
Search options removed from the Share settings

**Comment by artonge** [comment]
CI failure unrelated

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by come-nc — APPROVED** [review]

**Comment by skjnldsv** [comment]
@artonge  Documentation missing?

**Pull request merged**
