### PR TITLE
Select2 fix bis

### PR DESCRIPTION
**Pull request by skjnldsv**
Ref: https://github.com/nextcloud/server/pull/2133#issuecomment-262059604

Please review @jancborchardt @MorrisJobke @juliushaertl 
capture d ecran_2016-11-22_09-37-18
capture d ecran_2016-11-22_09-37-37
capture d ecran_2016-11-22_09-37-46

### CODE REVIEW

**Comment by MorrisJobke** [comment]
A lot better 👍

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by MorrisJobke** [comment]
@skjnldsv I added the fix for #2226 here ;)

**Comment by MorrisJobke** [comment]
@LukasReschke Please test this too - #2226 is a high DPI screen issue only ;)

**Comment by skjnldsv** [comment]
👍 LGTM

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
