### PR TITLE
Improve CertificateManager to not be user context dependent

### PR DESCRIPTION
**Pull request by MorrisJobke**
* removes the ability for users to import their own certificates (for external storage)
* reliably returns the same certificate bundles system wide (and not depending on the user context and available sessions)

The user specific certificates were broken in some cases anyways, as they are only loaded if the specific user is logged in and thus causing unexpected behavior for background jobs and other non-user triggered code paths.

* [x] think about existing user specific certificates (maybe detect them and show them in the setup warnings so that the admin either imports them into the system wide chain or drops them)

Bildschirmfoto 2020-11-02 um 23 59 09

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Comment by rullzer** [comment]
>  think about existing user specific certificates (maybe detect them and show them in the setup warnings so that the admin either imports them into the system wide chain or drops them)

Yeah so the mroe I think about the harder it is.
A setup check is most likely to slow. Maybe a background job that collects this info. And then shows it in the setupchecks if needed. Then we have an occ command to migrate the certificates? Or we just say. Well to bad. REmove the user thing. Add a release note and move on.

**Comment by rullzer** [comment]
Rebases and pushed another commit to fix other parts of the system as well.

**Comment by MorrisJobke** [comment]
While digging through the code I found that the controller was removed in #21224. I will check when the routes and UI was removed to give some estimates on the usage.

**Comment by MorrisJobke** [comment]
> While digging through the code I found that the controller was removed in #21224. I will check when the routes and UI was removed to give some estimates on the usage.

The settings part was removed in 13: #4890. So let's just check if there are user certificates and then show this to the admin.

**Comment by MorrisJobke** [comment]
Fixed the tests, added a one time background job, added texts for the setup checks and rebased and squashed everything. Ready for review IMO. I also added a screenshot to the OP.

**Comment by MorrisJobke** [comment]
Fixed the tests. Ready for review 🚀

**Review by rullzer — APPROVED** [review]

**Pull request merged**
