### PR TITLE
Fix SCSS usage in apps

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fix the web root detection of the ResourceLocator for apps

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Seems to fix the loading of the compiled css file, but the log shows this after loading the Tasks app:
```
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"css","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/core\/styles.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"css","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/core\/header.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"css","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/core\/icons.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"css","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/core\/apps.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"css","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/core\/multiselect.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"css","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/core\/tooltip.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"core","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/core\/share.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"css","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/core\/inputs.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
{"reqId":"3PK1Nsw4KSUukJz0r8HN","remoteAddr":"192.168.56.1","app":"tasks","message":"Could not find resource file \"\/nextcloud\/index.php\/css\/tasks\/style.css\"","level":0,"time":"2017-02-25T08:19:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/tasks\/","user":"admin","version":"12.0.0.13"}
``` 

Also the images referenced with `url("../img/sprites.svg");` in the css/scss file cannot be found anymore.

**Review by raimund-schluessler — CHANGES_REQUESTED** [review]
The reason for the errors in the log seems to be that line https://github.com/nextcloud/server/blob/cf3e2eb200e60678d063eaa5f95f21db9f4ba45e/lib/private/Template/ResourceLocator.php#L156 is called although the resource was found.

The images not loaded seems to be a separate issue: https://github.com/nextcloud/server/issues/3606#issuecomment-282472252

**Comment by rullzer** [comment]
Ok I *think* (tm) this works now!

**Review by raimund-schluessler — APPROVED** [review]

**Review by raimund-schluessler — APPROVED** [review]
It works on my testing instance now. The css file is generated, the file is included and loads correctly and also the paths to icon files are calculated correctly now (although ```url('../../../apps/tasks/css/../img/sprites.svg')``` could be shortened to ```url('../../../apps/tasks/img/sprites.svg')```.

**Comment by skjnldsv** [comment]
@raimund-schluessler yes, but it's easier to just add a piece of string than splitting it, popping an entry and remerging it again :)

**Comment by dirigit** [comment]
@skjnldsv 
Constructs like being shown by raimund-schuessler ('../../xyadf/../) are considered insecure because they are often used in attacks (directory traversal). You can block such attacks in core successfull and easy only when you don't use those constructs for yourself. Otherwise you need a lot of exceptions even at firewall or proxy parsing URLs for possible attacks ...

**Comment by raimund-schluessler** [comment]
@skjnldsv Would you have time to review if the PR is working for you?

> Constructs like being shown by raimund-schuessler ('../../xyadf/../) are considered insecure because they are often used in attacks (directory traversal). You can block such attacks in core successfull and easy only when you don't use those constructs for yourself. Otherwise you need a lot of exceptions even at firewall or proxy parsing URLs for possible attacks ...

I think we should merge the PR if it fixes the issue. Regarding the security implications I can't say anything. However, I would still merge this PR since the paths are already created like this in server. In case the security impact is real I would prefer fixing this in a separate PR. Also @LukasReschke.

**Comment by juliushaertl** [comment]
> Constructs like being shown by raimund-schuessler ('../../xyadf/../) are considered insecure because they are often used in attacks (directory traversal). You can block such attacks in core successfull and easy only when you don't use those constructs for yourself. Otherwise you need a lot of exceptions even at firewall or proxy parsing URLs for possible attacks ...

I don't see any security issue here, since those path traversals are only used in CSS url statements and will be resolved by your webserver.

**Review by skjnldsv — APPROVED** [review]
Can't test right now, but seems good to me :)

**Comment by MorrisJobke** [comment]
I tested it and it works 👍

**Comment by derkostka** [comment]
Hey guys how can i find out if this works for me or not ? 

With 12.0 Beta 4, my log is full with the following:
"ResourceLocator can not find a web root"

`{"reqId":"ZSJXEJo5bclf3Ktb6aRi","level":3,"time":"May 20, 2017 19:38:49","remoteAddr":"127.0.0.1","user":"admin","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files, file: css\/files\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.21"}
{"reqId":"ZSJXEJo5bclf3Ktb6aRi","level":3,"time":"May 20, 2017 19:38:50","remoteAddr":"127.0.0.1","user":"admin","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files_sharing, file: css\/files_sharing\/mergedAdditionalStyles.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.21"}
`

**Comment by derkostka** [comment]
@MorrisJobke : I did several tests. I still get an exception thrown, but only on my NC that was upgraded from 11 to 12 (RC3 right now).
If i open a clean installation, everything is fine.

How can i debug the following:
`{"reqId":"44JIuvpq9gxa8N2z7B6B","level":3,"time":"May 21, 2017 11:51:08","remoteAddr":"127.0.0.1","user":"sebastian.kostka@gmail.com","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files, file: css\/files\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.26"}`

**Pull request merged**
