### PR TITLE
Allow redis cluster to use password

### PR DESCRIPTION
**Pull request by MorrisJobke**
This allows to specify a password in the same way it already works for normal redis configuration.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I also extended the PHPDoc version, because it was missing this: https://github.com/zgb7mtr/phpredis_cluster_phpdoc/pull/3

**Review by blizzz — APPROVED** [review]
looks good

**Review by rullzer — APPROVED** [review]
:+1:

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
