### PR TITLE
fix(files): improve delete display name when trashbin is disabled

### PR DESCRIPTION
**Pull request by st3iny**
* Resolves: _none_

## Summary

1. Have an incoming share from another user.
2. Disable `files_trashbin`.
3. Observe that the three dot menu of the incoming share shows `Delete permanently` instead of `Leave this share`. This confuses some users.

Both display names `Leave this share` and `Disconnect storage` should not be influenced by the presence of the trashbin (`isTrashbinEnabled()`).

### Before

| Leave share | Disconnect from external storage |
| --- | --- |
| grafik | grafik |

### After

| Leave share | Disconnect external storage |
| --- | --- |
| grafik | grafik  |

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Makes sense for me, but lets wait on @skjnldsv as there was a lot of trouble on this action in the past.

**Comment by st3iny** [comment]
cc @skjnldsv Friendly ping as you are the expert on this code :)

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Looks good, make sense.

**Pull request merged**
