### PR TITLE
Add version naming UI

### PR DESCRIPTION
**Pull request by artonge**
:warning: :warning: 
**New elements are not visible by default. Need to set `OC.experimental = true` in the console before opening the sidebar.**
:warning: :warning: 

Context | Screenshot
-- | --
List of version with the actions menu opened for **the current version** | Screenshot from 2022-11-17 17-07-56
List of version with the actions menu opened for **a previous version** | Screenshot from 2022-11-17 17-07-46
Name editor when the version **do** have a name | Screenshot from 2022-11-16 14-52-17
Name editor when the version **does not** have a name | Screenshot from 2022-11-16 14-52-08

Need https://github.com/nextcloud/server/pull/34769

### CODE REVIEW

**Comment by artonge** [comment]
@jancborchardt or @nimishavijay for early design review :)

- I did not add a "Cancel" button" in the name version modal, as it seems like we do not do that in other place.
- Should I add a "Create new version" at the top of the list or something ?

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Very nice! :) Some design feedback:

- [x] The pencil icon for "Name this version" is a bit complex, just use the regular "pencil" material design icon
- [x] "Restore version" can go before "Download version" in the menu
- [x] The modal needs a heading inside, saying "Version name"
- [x] The "Named versions are persisted …" info text should go below the input field, and be in `color-text-maxcontrast`
- [x] Is the "Version name" input field focused by default?
- [x] If there is no version name or if the field is empty, the "Remove version name" button can be disabled?
- [x] Let’s use a better icon than the floppy for saving :D Just the "done" checkmark is fine


> I did not add a "Cancel" button" in the name version modal, as it seems like we do not do that in other place.

I’d say an "x" in the top right would be nice though. :)

> Should I add a "Create new version" at the top of the list or something ?

I’d say no, since the current version is already there? You can name the current version, right? So that is enough.


Great work @artonge! :)

**Comment by artonge** [comment]
> I’d say no, since the current version is already there? You can name the current version, right? So that is enough.

Now you can :)

**Comment by jancborchardt** [comment]
Very very nice @artonge! One last thing: Both "Current version" and "Initial version" i'd consider "virtual" names, not actual version names, so I'd label the action "Name this version" and have an empty input field in the modal. (But if the name is left empty for either the initial or current version, ofc this "virtual" name stays displayed in the version list.)

Does that make sense? :D

**Comment by artonge** [comment]
> Both "Current version" and "Initial version" i'd consider "virtual" names

"Initial version" is a "random" name I set myself for testing. Do you want to have this "virtual" label for the first version as well ?

The other part make sense

**Review by szaimen — CHANGES_REQUESTED** [review]
just tested a bit and how can I set the version? Also I have two initial versions?
image

**Comment by artonge** [comment]
Ah, forgot to properly set the condition for initial version.
New buttons are not visible by default. You need to set OC.experimental = true in the console before opening the sidebar.
I just pushed a fix

**Review by szaimen — CHANGES_REQUESTED** [review]
okay found it. A few more findings:
- showing the menu dots and/or icons only on hover does not work well on mobile
- I can use the same name for multiple items?

image

**Comment by artonge** [comment]
> * showing the menu dots and/or icons only on hover does not work well on mobile
That should probably be fixed in nc-vue, no ?
 
> * I can use the same name for multiple items?
Yes, unless @jancborchardt says otherwise :)

**Review by szaimen — CHANGES_REQUESTED** [review]
Also, shouldnt the save version name button not only be enabled after you type in something?
image

**Comment by artonge** [comment]
> Also, shouldnt the save version name button not only be enabled after you type in something?

This is so the user can remove the name. From Jan:

>  If there is no version name or if the field is empty, the "Remove version name" button can be disabled?

If we disable "Remove version name" then we can't also disable "Save version name".

**Comment by XueSheng-GIT** [comment]
@artonge thanks a lot! I really appriciate this approach to add version naming (and make such versions persistent)! I was looking for such a feature for quite some time.

Topics which might be considered:
* version numbers (e.g. automatically increased or manually defined), personally I'm used to SharePoint and a M.N version scheme (Major, minor numbers, whereas e.g. 4.0 would be a stable/released version and 4.8 would be a draft version ahead of 5.0). This provides a quick overview about the versions.
* descriptive text (optional) in addition to the the version name. Like you typically do for a github commit. This would be helpful to add some additional text about the version (and why it is important to keep or what was changed in comparison to previous versions).

**Comment by skjnldsv** [comment]
`OC.experimental = true`, what is this? This is no standard we have, right?
I'm not sure it's a good idea to add.

**Comment by artonge** [comment]
Closing as it will get merged by https://github.com/nextcloud/server/pull/35160

**Pull request closed without merging**
