### PR TITLE
display name fix for thunderbird

### PR DESCRIPTION
**Pull request by avinash-0007**
* Resolves: # 
https://github.com/nextcloud/calendar/issues/4784
## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by tcitworld** [comment]
It's odd we should have to do this. :thinking:

**Comment by avinash-0007** [comment]
@tcitworld i checked this and the case is display name is blank in case of thunderbird mail client.

**Comment by OlexTratisky** [comment]
This issue is really frustrating , is it solved?

**Comment by AndyScherzinger** [comment]
@ChristophWurst what do you think? Also cc @sorbaugh since it touches the server code base.

**Comment by skjnldsv** [comment]
@avinash-0007 there was a few comments that went unanswered :confused: 
As a cleanup step, we've closed that PR. If you want to take it back up again and re-open after addressing those comments, we'll be happy to help :pray: :hugs:

**Pull request closed without merging**
