### PR TITLE
Fix empty file uploads to S3 (and other streaming storages)

### LINKED ISSUE #14192: Uploading zero byte length file via webdav to s3 primary or external storage files (deleting files fails, too)
### Steps to reproduce
1. upload zero byte length file to Nextcloud to primary or external S3 Storage
2.
3.

### Expected behaviour
Empty file should be uploaded

### Actual behaviour
The following error is shown, and file does not turn up
[webdav] Fatal: Sabre\DAV\Exception: An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "https://crgw.itc.global.mahle/nextcloudcluster/urn%3Aoid%3A3099037?uploadId=2~Ok8YksG_8OK2jnjSoe0EyMQawpoq3PX"; AWS HTTP error: Client error: `POST https://crgw.itc.global.mahle/nextcloudcluster/urn%3Aoid%3A3099037?uploadId=2~Ok8YksG_8OK2jnjSoe0EyMQawpoq3PX` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>MalformedXML</Code><BucketName>nextcloudcluster</BucketName><RequestI (truncated...)
 MalformedXML (client):  - <?xml version="1.0" encoding="UTF-8"?><Error><Code>MalformedXML</Code><BucketName>nextcloudcluster</BucketName><RequestId>tx000000000000000103796-005c651fb6-b261918-dest</RequestId><HostId>b261918-dest-de</HostId></Error> at <<closure>>

0. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 209
   convertToSabreException(Aws\S3\Exception ... {})
1. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
   put(null)
2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
   createFile("New Text Document.txt", null)
3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
   createFile("Photos/New Text Document.txt", null, null)
4. <<closure>>
   httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
5. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   call_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   emit("method:PUT", [Sabre\HTTP\Requ ... }])
7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
8. /var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
   exec()
9. /var/www/html/nextcloud/remote.php line 163
   require_once("/var/www/html/n ... p")

PUT /remote.php/webdav/Photos/New%20Text%20Document.txt
from 10.145.60.164 by 27EB840B-643D-495C-A770-1B7CB954E14E at 2019-02-14T07:58:46+00:00

### Server configuration

**Operating system**:
CentOS Linux release 7.6.1810 (Core)

**Web server:**
httpd-2.4.6-88.el7.centos.x86_64
**Database:**
mariadb cluster
**PHP version:**
php7.2
**Nextcloud version:** (see Nextcloud admin page)
15.004
**Updated from an older Nextcloud/ownCloud or fresh install:**
15.02
**Where did you install Nextcloud from:**
standard update repo

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Accessibility
1.1.0
Official
Activity
2.8.2
Official
Auditing / Logging
1.5.0
Official
Circles
0.16.0
Official
Collaborative tags
1.5.0
Official
Comments
1.5.0
Official
Deleted files
1.5.0
Official
External storage support
1.6.0
Official
Federation
1.5.0
Official
File access control
1.5.0
Official
File sharing
1.7.0
Official
Files automated tagging
1.5.0
Official
First run wizard
2.4.0
Official
Gallery
18.2.0
Official
LDAP user and group backend
1.5.0
Official
Log Reader
2.0.0
Official
Markdown Editor
2.0.5
Monitoring
1.5.0
Official
Nextcloud announcements
1.4.0
Official
Notifications
2.3.0
Official
Password policy
1.5.0
Official
PDF viewer
1.4.0
Official
README.md
1.0.1
Share by mail
1.5.0
Official
Support
1.0.0
Official
Text editor
2.7.0
Official
Theming
1.6.0
Official
Update notification
1.5.0
Official
Usage survey
1.3.0
Official
Versions
1.8.0
Official
Video player
1.4.0
Official
Default encryption module
2.3.0
Official
Workflow external scripts 
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dest-docl03.itc.global.mahle",
            "dest-docllb1.itc.global.mahle",
            "intmcs.mahle.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/var\/big_temp_file\/",
        "overwrite.cli.url": "https:\/\/intmcs.mahle.com",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "log_type": "file",
        "loglevel": 2,
        "logfile": "\/nextcloud_data\/data\/nextcloud.log",
        "log_rotate_size": 104857600,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "LOGIN",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloudcluster",
                "autocreate": true,
                "key": "8rMTVnPGQCGwNvdKstNi",
                "secret": "",
                "hostname": "crgw.itc.global.mahle",
                "port": 443,
                "use_ssl": true,
                "region": "optional",
                "use_path_style": true
            }
        },
        "auth.bruteforce.protection.enabled": false,
        "updater.release.channel": "stable",
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "proxy": "dest-prxl00.itc.global.mahle:3128",
        "lost_password_link": "https:\/\/intmcs.mahle.com\/password_reset.html",
        "theme": "",
        "mail_sendmailmode": "smtp"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
S3

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP AD connect

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+-------------------------------------------------------------------------------+
| Configuration                 |                                                                               |
+-------------------------------+-------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                             |
| homeFolderNamingRule          |                                                                               |
| lastJpegPhotoLookup           | 0                                                                             |
| ldapAgentName                 | cn=S0002190,ou=system,ou=users,ou=st,ou=de,ou=mahle,DC=itc,DC=global,DC=mahle |
| ldapAgentPassword             | ***                                                                           |
| ldapAttributesForGroupSearch  |                                                                               |
| ldapAttributesForUserSearch   | mail;givenname;sn                                                             |
| ldapBackupHost                |                                                                               |
| ldapBackupPort                |                                                                               |
| ldapBase                      | DC=global,DC=mahle                                                            |
| ldapBaseGroups                | DC=global,DC=mahle                                                            |
| ldapBaseUsers                 | DC=global,DC=mahle                                                            |
| ldapCacheTTL                  | 600                                                                           |
| ldapConfigurationActive       | 1                                                                             |
| ldapDefaultPPolicyDN          |                                                                               |
| ldapDynamicGroupMemberURL     |                                                                               |
| ldapEmailAttribute            | Mail                                                                          |
| ldapExperiencedAdmin          | 1                                                                             |
| ldapExpertUUIDGroupAttr       |                                                                               |
| ldapExpertUUIDUserAttr        |                                                                               |
| ldapExpertUsernameAttr        |                                                                               |
| ldapGidNumber                 | gidNumber                                                                     |
| ldapGroupDisplayName          | cn                                                                            |
| ldapGroupFilter               |                                                                               |
| ldapGroupFilterGroups         |                                                                               |
| ldapGroupFilterMode           | 1                                                                             |
| ldapGroupFilterObjectclass    |                                                                               |
| ldapGroupMemberAssocAttr      | member                                                                        |
| ldapHost                      | ldaps://10.200.95.191                                                         |
| ldapIgnoreNamingRules         |                                                                               |
| ldapLoginFilter               | (&(|(objectclass=person)(objectclass=user))(samaccountname=%uid))             |
| ldapLoginFilterAttributes     |                                                                               |
| ldapLoginFilterEmail          | 0                                                                             |
| ldapLoginFilterMode           | 1                                                                             |
| ldapLoginFilterUsername       | 1                                                                             |
| ldapNestedGroups              | 0                                                                             |
| ldapOverrideMainServer        |                                                                               |
| ldapPagingSize                | 500                                                                           |
| ldapPort                      | 3269                                                                          |
| ldapQuotaAttribute            |                                                                               |
| ldapQuotaDefault              |                                                                               |
| ldapTLS                       | 0                                                                             |
| ldapUserAvatarRule            | default                                                                       |
| ldapUserDisplayName           | mail                                                                          |
| ldapUserDisplayName2          |                                                                               |
| ldapUserFilter                | (&(|(sAMAccountType=805306368)))                                              |
| ldapUserFilterGroups          |                                                                               |
| ldapUserFilterMode            | 1                                                                             |
| ldapUserFilterObjectclass     | person                                                                        |
| ldapUuidGroupAttribute        | auto                                                                          |
| ldapUuidUserAttribute         | auto                                                                          |
| turnOffCertCheck              | 0                                                                             |
| turnOnPasswordChange          | 0                                                                             |
| useMemberOfToDetectMembership | 1                                                                             |
+-------------------------------+-------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
No relevant entries
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
[webdav] Fatal: Sabre\DAV\Exception: An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "https://crgw.itc.global.mahle/nextcloudcluster/urn%3Aoid%3A3099037?uploadId=2~Ok8YksG_8OK2jnjSoe0EyMQawpoq3PX"; AWS HTTP error: Client error: `POST https://crgw.itc.global.mahle/nextcloudcluster/urn%3Aoid%3A3099037?uploadId=2~Ok8YksG_8OK2jnjSoe0EyMQawpoq3PX` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>MalformedXML</Code><BucketName>nextcloudcluster</BucketName><RequestI (truncated...)
 MalformedXML (client):  - <?xml version="1.0" encoding="UTF-8"?><Error><Code>MalformedXML</Code><BucketName>nextcloudcluster</BucketName><RequestId>tx000000000000000103796-005c651fb6-b261918-dest</RequestId><HostId>b261918-dest-de</HostId></Error> at <<closure>>

0. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 209
   convertToSabreException(Aws\S3\Exception ... {})
1. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
   put(null)
2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
   createFile("New Text Document.txt", null)
3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
   createFile("Photos/New Text Document.txt", null, null)
4. <<closure>>
   httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
5. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   call_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   emit("method:PUT", [Sabre\HTTP\Requ ... }])
7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
8. /var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
   exec()
9. /var/www/html/nextcloud/remote.php line 163
   require_once("/var/www/html/n ... p")

PUT /remote.php/webdav/Photos/New%20Text%20Document.txt
from 10.145.60.164 by 27EB840B-643D-495C-A770-1B7CB954E14E at 2019-02-14T07:58:46+00:00
</details>

#### Browser log
<details>
<summary>Browser log</summary>
N/a
</details>

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #14192

TODO:
- [x] Requires https://github.com/nextcloud/3rdparty/pull/240
- [x] Requires https://github.com/nextcloud/3rdparty/pull/242
- [ ] Add an integration tests for empty files (@juliushaertl @danxuliu)

### CODE REVIEW

**Comment by rullzer** [comment]
Rebased

**Comment by MorrisJobke** [comment]
before: 💥 
after: upload works

There are still some warnings in the log:

```
{"reqId":"9bcr1G2Wjy9bPCjeibs4","level":3,"time":"2019-02-15T10:49:57+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"PUT","url":"\/remote.php\/webdav\/a","message":"A non-numeric value encountered at \/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Files\/ObjectStore\/S3ObjectTrait.php#81","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.0.2 Safari\/605.1.15","version":"16.0.0.0"}
{"reqId":"6Mutt2YZH11krtCeaH6R","level":3,"time":"2019-02-15T10:49:58+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/theming\/img\/core\/filetypes\/file.svg?v=0","message":"A non-numeric value encountered at \/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Files\/ObjectStore\/S3ObjectTrait.php#81","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.0.2 Safari\/605.1.15","version":"16.0.0.0"}
{"reqId":"6Mutt2YZH11krtCeaH6R","level":3,"time":"2019-02-15T10:49:58+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/theming\/img\/core\/filetypes\/file.svg?v=0","message":"A non-numeric value encountered at \/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Files\/ObjectStore\/S3ObjectTrait.php#81","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.0.2 Safari\/605.1.15","version":"16.0.0.0"}
```

**Comment by rullzer** [comment]
Needs https://github.com/icewind1991/Streams/pull/10

**Comment by rullzer** [comment]
@MorrisJobke fixed with https://github.com/nextcloud/3rdparty/pull/242 please have another look :smile:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
> * [x]  Requires [nextcloud/3rdparty#242](https://github.com/nextcloud/3rdparty/pull/242)

It's merged now 👍

**Review by icewind1991 — APPROVED** [review]

**Comment by rullzer** [comment]
Rebased. Then lets get this in.

**Pull request merged**
