### PR TITLE
fix: invalid usage of IQueryBuilder::createNamedParameter()

### PR DESCRIPTION
**Pull request by st3iny**
* Followup to: #47832 

## Summary

I'm sorry, I missed some issues during my code review.

1. Creating a parameter without a value is done via `IQueryBuilder::createParameter()`.
2. Fixed a small typo.
3. Fixed inconsistent and missing types for parameters to improve compatibility with oci.

See also https://github.com/nextcloud/server/pull/49428#discussion_r1853896702

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by SebastianKrupinski** [comment]
He, can we cancel the back ports of this? I was just going to adjust the original backports.

**Comment by st3iny** [comment]
> He, can we cancel the back ports of this? I was just going to adjust the original backports.

I'd say no. For consistency it is better to merge them and then backport this.

**Review by SebastianKrupinski — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
