### PR TITLE
fix(TextProcessing): Add task type template param to IManager and registerTPProvider

### PR DESCRIPTION
**Pull request by marcelklehr**
otherwise we cannot use them reasonably

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by provokateurin** [comment]
Where and why is it failing?

**Comment by marcelklehr** [comment]
It is failing when using implementations of IProvider, ie. when registering a provider or when passing a Task object to IManager#runTask or IManager#scheduleTask

**Review by provokateurin — APPROVED** [review]

**Comment by come-nc** [comment]
Can you give a minimal example on what did not work which will now work, ideally on psalm.dev?

**Comment by marcelklehr** [comment]
and https://psalm.dev/r/62efc9b86a

**Review by come-nc — APPROVED** [review]
Thanks for the details :+1:

**Comment by marcelklehr** [comment]
@come-nc  Do you think we should do the covariant or add new template  to the methods in questions as in my latest comment?

**Comment by come-nc** [comment]
> @come-nc Do you think we should do the covariant or add new template to the methods in questions as in my latest comment?

The covariant thing, because you might have a function that accept both template<B> and template<C> if both inherit A.
Then if you have a function which only accepts template<SubType> you should also reflect it in phpdoc typing but that’s another story.

**Pull request merged**
