### PR TITLE
Make regions translatable

### PR DESCRIPTION
**Pull request by MorrisJobke**
Together with https://github.com/nextcloud/docker-ci/commit/f24eb135369a7b57e9544a4eb199c551dfc46b95 this properly extracts and localizes the locale regions

### CODE REVIEW

**Comment by MorrisJobke** [comment]
For #14822

**Review by georgehrke — APPROVED** [review]
👍 🐘

**Review by rullzer — APPROVED** [review]
:elephant: 

But is the locale actually somewhere in text? Else it can't be translated?

**Comment by MorrisJobke** [comment]
> But is the locale actually somewhere in text? Else it can't be translated?

See https://github.com/nextcloud/docker-ci/commit/f24eb135369a7b57e9544a4eb199c551dfc46b95

**Pull request merged**
