### PR TITLE
Show most recently deleted files first in trash can

### LINKED ISSUE #16412: When opening the trashbin it doesn't show the most recently deleted files first.
### Steps to reproduce
1. create some files/folders
2. delete one file
3. delete another file
4. open the trashbin/deleted files app

### Expected behaviour
it should show the most recently deleted files first

### Actual behaviour
It shows the least recently deleted files first
Just when clicking twice on the "deleted"-section it show the most recently deleted files first.

I am running Nextcloud 16.0.3 on Ubuntu 18.04.2 LTS and using a Chromium-75-based browser.

### PR DESCRIPTION
**Pull request by orzuionut**
Fix #16412

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Seems to work in my testing 👍

<details>
<summary>tested with</summary>

```
docker run -it \
-e SERVER_BRANCH=newroco:bugfix/16412/show-most-recently-deleted-files-first \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.130 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

Thanks for fixing this! 🚀

**Comment by szaimen** [comment]
But @orzuionut please fix `Node / node (pull_request)` by compiling the code and pushing the production js here. Thanks! :)

**Comment by szaimen** [comment]
Thanks! Looks like the test needs an adjustment now:
https://github.com/nextcloud/server/blob/70c10f09fe9050bd5e578fa74ba9dc36147dfab6/apps/files_trashbin/tests/js/filelistSpec.js#L139

**Review by szaimen — APPROVED** [review]
Thanks! Failure unrelated, afaics.

**Review by CarlSchwan — APPROVED** [review]

**Comment by CarlSchwan** [comment]
Test failure is indeed unrelated (user settings)

**Pull request merged**
