### PR TITLE
allow group backends to mark that a group should now be shown in search dialogs

### PR DESCRIPTION
**Pull request by icewind1991**
use case here is hiding the virtual "guests" group from sharing when using the guests app

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
some tests would be nice

**Review by blizzz — CHANGES_REQUESTED** [review]
Looks fine, generally, but autoloader files needs to get updated and some PHP docs are missing (see CI)

**Comment by MorrisJobke** [comment]
> Looks fine, generally, but autoloader files needs to get updated and some PHP docs are missing (see CI)

I updated the autoloader files.

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Pull request merged**
