### PR TITLE
[stable27] fix(i18n): Changed grammar

### PR DESCRIPTION
**Pull request by rakekniven**
fix(i18n): Changed grammar

### CODE REVIEW

**Review by Valdnet — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Block merges during freezes / Block merges during freezes (pull_request) 

Has to wait until next releases

**Comment by blizzz** [comment]
moving to 27.1.6

**Comment by nickvergessen** [comment]
> Please merge :-)

JS needs recompiling and the release is already in progress.

**Comment by nickvergessen** [comment]
Maybe you can set yourself a reminder for next friday, then rebase and recompile the JS assets and get it merged then.

**Comment by blizzz** [comment]
Also there would be no time for translation updates if squeezed in last minute.

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
actually it was not compiling that failed, but the js unit test :D

**Pull request merged**
