### PR TITLE
fix detecting cyclic group memberships

### PR DESCRIPTION
**Pull request by blizzz**
When there is a cyclic group membership of groups (AD, Samba4), this was not being detected as not all information was taken into  account, resulting in an infinite loop.

To reproduce:
1. In AD/Samba4 have three groups Group A, Group B and Group C.
2. Group B is member of Group A, Group C is member of Group B and Group A is member of Group C.
3. LDAP settings Nested groups are enabled and hasMemberOfFilterSupport is disabled.
4. php occ group:list

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
I know some of these words

**Comment by awaw9** [comment]
في الجمعة، ٢٦ فبراير ٢٠٢١ ١٢:٥٨ م blizzz <notifications@github.com> كتب:

**Comment by tofuSCHNITZEL** [comment]
LGTM.
while checking the code and testing it with my local setup I found a rather small and simple addition to make the nested groups work with non DN group member attribute groups. you can check it out here:
https://github.com/tofuSCHNITZEL/server/tree/feature_nested_groups_for_nonDN_member_attribute
if it makes sense we could include it also here since its a rather small fix. (I tested it with my zimbra ldap - but I guess it should be tested with another ldap that uses eg uid as a member attribute as well.)

**Review by tofuSCHNITZEL — APPROVED** [review]

**Comment by blizzz** [comment]
> LGTM.
> while checking the code and testing it with my local setup I found a rather small and simple addition to make the nested groups work with non DN group member attribute groups. you can check it out here:
> [tofuSCHNITZEL@5bf4fea](https://github.com/tofuSCHNITZEL/server/commit/5bf4feab46af850e239c39675edb620c23932f44)
> if it makes sense we could include it also here since its a rather small fix. (I tested it with my zimbra ldap - but I guess it should be tested with another ldap that uses eg uid as a member attribute as well.)

Nice one. I am happy to take it, but prefer it in a follow up PR for issue separation.

**Pull request merged**
