### PR TITLE
[stable9] Set content-type to "application/octet-stream"

### PR DESCRIPTION
**Pull request by LukasReschke**
Some browsers such as Firefox on Microsoft Windows otherwise do offer to open the file directly which is kinda silly.

Backport of https://github.com/nextcloud/server/pull/258

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by mar1u5** [comment]
:+1:

**Comment by mar1u5** [comment]
...LGTM is not working :cry:

**Comment by mar1u5** [comment]
Ah ... You were faster :stuck_out_tongue_winking_eye:

**Pull request merged**
