### PR TITLE
[OC] Fix unmerged shares repair targetdecision

### PR DESCRIPTION
**Pull request by rullzer**
See https://github.com/owncloud/core/pull/25810

CC: @schiessle @nickvergessen @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by rullzer** [comment]
Backport for 10 is in https://github.com/owncloud/core/pull/25812 but lets first see how this goes

**Comment by schiessle** [comment]
There is a follow-up PR which we might consider as well: https://github.com/owncloud/core/pull/25829

**Comment by rullzer** [comment]
@schiessle yep picked as well now from https://github.com/owncloud/core/pull/25829

please review

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
