### PR TITLE
Fix username prefill and allow using it in flow auth

### LINKED ISSUE #29468: Allow to prefill username with login v2
Normal login (e.g. https://nextcloud.server.com/login?user=eoeoeo&direct=1) can already prefill any username.
This is wanted also for login flow v2 for Desktop.

@skjnldsv if this is more than 2 days of work, please put it on board.

### PR DESCRIPTION
**Pull request by juliusknorr**
- [x] Fix regular login page username prefill, which seemed to sometimes not work as the initial state was loaded too late after applying the initial data attribute value
- [x] Flow v1
- [x] Flow v2

Implements https://github.com/nextcloud/server/issues/29468

FYI @tobiasKaminsky

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@allexzander this is for https://github.com/nextcloud/desktop/issues/3769 via https://github.com/nextcloud/server/issues/29468

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by allexzander** [comment]
> @allexzander this is for [nextcloud/desktop#3769](https://github.com/nextcloud/desktop/issues/3769) via #29468

@juliushaertl @tobiasKaminsky 

When will this be deployed to cloud.nextcloud.com? Right now I still can't use `user` in query for `login/flow`

**Comment by skjnldsv** [comment]
> When will this be deployed to cloud.nextcloud.com? Right now I still can't use `user` in query for `login/flow`

This is a feature, so Nextcloud 24

**Review by Pytal — APPROVED** [review]

**Comment by juliushaertl** [comment]
Tests adjusted

**Comment by szaimen** [comment]
This needs a manual rebase...

**Comment by allexzander** [comment]
@juliushaertl I was not able to run a custom branch with docker to test my Desktop Client changes against these changes. Now, which endpoint I should append with the `username` parameter?

1. https://cloud.nextcloud.com/index.php/login/v2
2. https://cloud.nextcloud.com/login/v2/flow/

Is it the first one, or the second one?

**Comment by juliushaertl** [comment]
@allexzander Could you try the rebased latest version of that branch again? The user parameter needs to be added to the URL that gets returned from the anonymous POST request:

`https://nextcloud.local/index.php/login/v2/flow/0tgcnB09glveMWeNkLEcGJMVUXfToiICqN2s0XEGtG6CZf8xzpMabXC34IorfzdlQ7uVsXYxHYPRZRIhaUxyFi4usYphngOycwU8XeZ2wpbRk3oqPMAvo2fMlJ9ROFo?user=myTestUser`

**Comment by juliushaertl** [comment]
Samba test failures seem unrelated

**Pull request merged**
