### PR TITLE
chore(deps): Update nextcloud/coding-standard to v1.3.1

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

Psalm baseline had to be updated due to it referencing code snippets where the formatting was changed.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Comment by come-nc** [comment]
```diff
diff --git a/apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php b/apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
index d8abbc39631..7e48867fcfa 100644
--- a/apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
+++ b/apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php
@@ -68,7 +68,9 @@ class PushProvider extends AbstractProvider {
                $eventUUID = (string)$vevent->UID;
                if (!$eventUUID) {
                        return;
-               };
+               }
+
+;
                $eventUUIDHash = hash('sha256', $eventUUID, false);
 
                foreach ($users as $user) {
```
:thinking:

**Comment by provokateurin** [comment]
Unfortunately it also seems to generate a different result than locally.

**Comment by come-nc** [comment]
```diff
diff --git a/apps/dav/templates/schedule-response-error.php b/apps/dav/templates/schedule-response-error.php
index 9604c83f922..7bdb37f73dd 100644
--- a/apps/dav/templates/schedule-response-error.php
+++ b/apps/dav/templates/schedule-response-error.php
@@ -11,6 +11,8 @@
                <p><?php p($l->t('Please contact the organizer directly.'));?></p>
                <?php if (isset($_['organizer'])): ?>
                        <p><a href="<?php p($_['organizer']) ?>"><?php p(substr($_['organizer'], 7)) ?></a></p>
-               <?php endif; ?>
+               <?php endif;
+
+ ?>
        </div>
 </div>
```
also not ideal

**Comment by come-nc** [comment]
You also need to composer install --no-dev before commit

**Comment by come-nc** [comment]
I used `git diff master..chore/deps/nextcloud-coding-standard --ignore-all-space --ignore-blank-lines` to keep my sanity.
It basically looks good everywhere but in templates files, where it’s not that nice :confused:

**Comment by provokateurin** [comment]
> Unfortunately it also seems to generate a different result than locally.

Deleting the cache did the trick and it also changed some things in the templates.

**Comment by provokateurin** [comment]
Changes to the templates seem to break *DAV.

**Comment by nickvergessen** [comment]
Yeah let's just revert the 2 new line rules

**Review by kesselb — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]

**Comment by provokateurin** [comment]
Sharding tests are expected to fail, can someone force-merge?

**Review by come-nc — APPROVED** [review]

**Pull request merged**
