### PR TITLE
UI : Improved presentation of personal information

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

## Summary

**Before :** 

**After :** 

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by jancborchardt — COMMENTED** [review]
Very nice! @Jerome-Herbinet only details:
- It seems the display name text is bigger or has higher cardinality?
- Also next to it, the email and phone number headings are lower than the avatar and display name text?

**Comment by Jerome-Herbinet** [comment]
I redid a test from scratch, and here is the screenshot I got @jancborchardt (I think I messed up something while simulating the first time just before make the screenshot)

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet there seems to have been a problem, maybe you hit comment while the image was still uploading? :)

**Review by nimishavijay — APPROVED** [review]
Very nice! :)

**Review by Pytal — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
