### PR TITLE
dont return private storage interface from public mount interface

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
sure

**Review by kesselb — APPROVED** [review]

**Comment by kesselb** [comment]
Psalm is a bit unhappy.

https://github.com/nextcloud/server/blob/d1bdd1ceba961b0899f504f7417a5c23271c5391/lib/public/Files/Storage/IStorage.php#L439

https://github.com/nextcloud/server/blob/d1bdd1ceba961b0899f504f7417a5c23271c5391/lib/private/Files/Storage/Common.php#L334

**Comment by icewind1991** [comment]
and now psalm just crashes...

**Comment by kesselb** [comment]
:disappointed: It seems that a dev version is used for the security checks. I would ignore them for now and just care about


image

**Comment by rullzer** [comment]
Master is Nextcloud 22 now.
If this should go into 21 it should be backported.

**Comment by PVince81** [comment]
@icewind1991 please rebase for psalm and/or fix psalm issues

**Comment by rullzer** [comment]
Seems psalm is right. Also with respect to the failed cache that doesn't fit the hierarchy...

**Comment by icewind1991** [comment]
psalm is happy

**Comment by rullzer** [comment]
Ah but conflicts now :(

**Comment by blizzz** [comment]
@icewind1991  conflicts

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
