### PR TITLE
Move the initCore function to the bundle

### PR DESCRIPTION
**Pull request by ChristophWurst**
This is a big one. It's moving the dreaded `initCore` into a module of its own, plus splitting it a bit into a few submodules where easily possible and switching code constructs to newer syntax.

I'm pretty sure jsunit won't like it, but let's see what Drone reports.

Ref https://github.com/orgs/nextcloud/projects/31#card-21177484.

Todo
- [x] expose `initCore` globally again, but deprecate it as well

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> PhantomJS 2.1.1 (Linux 0.0.0): Executed 1073 of 1077 (skipped 4) SUCCESS (14.128 secs / 13.737 secs)

… locally but Drone fails. Yay.

**Comment by ChristophWurst** [comment]
Time to review :rocket:

**Review by georgehrke — APPROVED** [review]
✅ contacts menu works 
✅ User menu works
✅ Snap.js works
✅ Session heartbeat works 
✅ Resize App menu works 
✅ ...

Anything else that's important in this context?

**Comment by ChristophWurst** [comment]
> Anything else that's important in this context?

I think you have covered the important ones :+1: Some of the code is hard to understand. I think some is even dead or unused.

**Review by rullzer — APPROVED** [review]
Coke make sense. And a smoke test with me clicking around like a maniac didn't have anything blow up. Lets do this.

**Pull request merged**
