### PR TITLE
fix fileactions for sharing overview

### LINKED ISSUE #27671: Webdav link in share overview instead of openfile link
### Steps to reproduce
1. Share a file
2. Examine the link of this file in your "All files" view, it looks like "https://yourcloud.com/index.php/apps/files?dir=/&openfile=1234"
3. Examine the link of the same file in your "Share overview" view, it looks like "https://yourcloud.com/remote.php/webdav/name_of_file.ext"

### Expected behaviour
The links should be equal

### Actual behaviour
Links are different, and when you click on a "webdav" link in the share overview, file association is incorrect, you cannot open the file in onlyoffice or KeeWeb, you have to download it.

### Server configuration

**Operating system:**
Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64

**Web server:**
Apache/2.4.38 (Debian) (apache2handler)

**Database:**
mysql 10.3.27

**PHP version:**
7.3.27-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, memcache, mysqli, pdo_mysql, pdo_sqlite, apc, posix, pspell, readline, recode, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page)
21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated install

**Where did you install Nextcloud from:**
unknown

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - bruteforcesettings: 2.2.0
 - calendar: 2.2.2
 - circles: 0.21.2
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - drawio: 1.0.0
 - emlviewer: 0.0.21
 - event_update_notification: 1.2.0
 - external: 3.8.1
 - extract: 1.3.1
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_downloadactivity: 1.10.0
 - files_external: 1.12.0
 - files_frommail: 0.4.0
 - files_mindmap: 0.0.24
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_texteditor: 2.14.0
 - files_trackdownloads: 1.10.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - flow_notifications: 1.1.0
 - group_everyone: 0.1.7
 - groupfolders: 9.0.1
 - impersonate: 1.8.0
 - integration_whiteboard: 0.0.14
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - metadata: 0.13.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.0.2
 - password_policy: 1.11.0
 - pdfdraw: 0.1.2
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - rainloop: 7.1.2
 - ransomware_protection: 1.10.1
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - sharingpath: 0.3.0
 - spreed: 11.2.2
 - support: 1.4.0
 - survey_client: 1.9.0
 - suspicious_login: 4.0.0
 - systemtags: 1.11.0
 - talk_simple_poll: 1.3.1
 - tasks: 0.13.6
 - text: 3.2.0
 - theming: 1.12.0
 - theming_customcss: 1.8.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_ldap: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - welcome: 0.0.5
 - workflow_script: 1.6.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - announcementcenter
 - auto_groups
 - collectives
 - encryption
 - ldap_contacts_backend
 - ldapcontacts
 - mail
 - nextcloud_announcements
 - quicknotes
 - recommendations
 - weather_status
 - workflow_pdf_converter

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "next.agglo-montbeliard.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.2.1",
    "overwrite.cli.url": "https:\/\/next.agglo-montbeliard.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "skeletondirectory": "",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "loglevel": 2,
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud.log",
    "logfilemode": 416,
    "debug": false,
    "maintenance": false,
    "app.mail.verify-tls-peer": false,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "bruteforcesettings",
        "emlviewer",
        "files_frommail",
        "mindmap_app",
        "issuetemplate",
        "pdfdraw"
    ]
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

irrelevant
</details>

### Client configuration
**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

irrelevant
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

irrelevant
</details>

#### Browser log
<details>
<summary>Browser log</summary>
irrelevant
</details>

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/27671

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=enh/27671/fix-sharing-overview-actions \
-e VIEWER_BRANCH=master \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
Tested locally, just need npm run build :)

**Comment by szaimen** [comment]
Thanks Carl! :)

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
Failure unrelated, afaics (timeout)

**Comment by szaimen** [comment]
Okay, i am pretty sure now that the backport bot is broken

**Pull request merged**
