### PR TITLE
Fix deleting folders when using s3 external storage

### LINKED ISSUE #7667: Unable to delete folder inside S3
### Steps to reproduce
1.Add S3
2.Create a new folder in S3（e.g.  occ）
3.Delete the occ folder

### Expected behaviour
Folder 'occ' deleted

### Actual behaviour
Prompt folder 'occ' deletion failed

### Server configuration

**Operating system**:CentOS 7.4.1708

**Web server:**Apache 2.4.6

**Database:**MariaDB 10.1.30

**PHP version:**5.6.32

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**no

**Where did you install Nextcloud from:**zip file

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** no

### Client configuration
**Browser:**FireFox 57.0.3

**Operating system:**WIN 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Error | no app in context | OCP\Files\NotFoundException: /SCP/occ not found while trying to get owner

    /home/ownadmin/public_html/apps/activity/lib/FilesHooks.php - line 633: OC\Files\View->getOwner('/SCP/occ')
    /home/ownadmin/public_html/apps/activity/lib/FilesHooks.php - line 190: OCA\Activity\FilesHooks->getSourcePathAndOwner('/SCP/occ')
    /home/ownadmin/public_html/apps/activity/lib/FilesHooks.php - line 146: OCA\Activity\FilesHooks->addNotificationsForFileAction('/SCP/occ', 'file_created', 'created_self', 'created_by')
    /home/ownadmin/public_html/apps/activity/lib/FilesHooksStatic.php - line 47: OCA\Activity\FilesHooks->fileCreate('/SCP/occ')
    [internal function] OCA\Activity\FilesHooksStatic fileCreate(Array)
    /home/ownadmin/public_html/lib/private/legacy/hook.php - line 106: call_user_func(Array, Array)
    /home/ownadmin/public_html/lib/private/Files/View.php - line 1271: OC_Hook emit('OC_Filesystem', 'post_create', Array)
    /home/ownadmin/public_html/lib/private/Files/View.php - line 1197: OC\Files\View->runHooks(Array, '/SCP/occ', true)
    /home/ownadmin/public_html/lib/private/Files/View.php - line 269: OC\Files\View->basicOperation('mkdir', '/SCP/occ', Array)
    /home/ownadmin/public_html/apps/dav/lib/Connector/Sabre/Directory.php - line 180: OC\Files\View->mkdir('/SCP/occ')
    /home/ownadmin/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1210: OCA\DAV\Connector\Sabre\Directory->createDirectory('occ')
    /home/ownadmin/public_html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('SCP/occ', Object(Sabre\DAV\MkCol))
    [internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/ownadmin/public_html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /home/ownadmin/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)
    /home/ownadmin/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/ownadmin/public_html/apps/dav/appinfo/v1/webdav.php - line 76: Sabre\DAV\Server->exec()
    /home/ownadmin/public_html/remote.php - line 162: require_once('/home/ownadmin/...')
    {main}

Fatal | webdav | InvalidArgumentException: Found 1 error while validating the input provided for the DeleteObjects operation: [Delete] is missing and is a required parameter

    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/Middleware.php - line 80: Aws\Api\Validator->validate('DeleteObjects', Object(Aws\Api\StructureShape), Array)
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/S3/S3Client.php - line 421: Aws\Middleware Aws\{closure}(Object(Aws\Command), NULL)
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/S3/S3Client.php - line 444: Aws\S3\S3Client Aws\S3\{closure}(Object(Aws\Command), NULL)
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/S3/S3Client.php - line 378: Aws\S3\S3Client Aws\S3\{closure}(Object(Aws\Command), NULL)
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/S3/S3Client.php - line 397: Aws\S3\S3Client Aws\S3\{closure}(Object(Aws\Command), NULL)
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/Middleware.php - line 55: Aws\S3\S3Client Aws\S3\{closure}(Object(Aws\Command), NULL)
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/S3/SSECMiddleware.php - line 59: Aws\Middleware Aws\{closure}(Object(Aws\Command), NULL)
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php - line 77: Aws\S3\SSECMiddleware->__invoke(Object(Aws\Command), NULL)
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/AwsClientTrait.php - line 65: Aws\IdempotencyTokenMiddleware->__invoke(Object(Aws\Command))
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/AwsClientTrait.php - line 59: Aws\AwsClient->executeAsync(Object(Aws\Command))
    /home/ownadmin/public_html/3rdparty/aws/aws-sdk-php/src/AwsClientTrait.php - line 78: Aws\AwsClient->execute(Object(Aws\Command))
    /home/ownadmin/public_html/apps/files_external/lib/Lib/Storage/AmazonS3.php - line 256: Aws\AwsClient->__call('deleteObjects', Array)
    /home/ownadmin/public_html/apps/files_external/lib/Lib/Storage/AmazonS3.php - line 256: Aws\S3\S3Client->deleteObjects(Array)
    /home/ownadmin/public_html/apps/files_external/lib/Lib/Storage/AmazonS3.php - line 224: OCA\Files_External\Lib\Storage\AmazonS3->batchDelete('occ')
    /home/ownadmin/public_html/lib/private/Files/Storage/Wrapper/Wrapper.php - line 87: OCA\Files_External\Lib\Storage\AmazonS3->rmdir('occ')
    /home/ownadmin/public_html/lib/private/Files/Storage/Wrapper/Availability.php - line 95: OC\Files\Storage\Wrapper\Wrapper->rmdir('occ')
    /home/ownadmin/public_html/lib/private/Files/Storage/Wrapper/Wrapper.php - line 87: OC\Files\Storage\Wrapper\Availability->rmdir('occ')
    /home/ownadmin/public_html/lib/private/Files/Storage/Wrapper/PermissionsMask.php - line 106: OC\Files\Storage\Wrapper\Wrapper->rmdir('occ')
    [internal function] OC\Files\Storage\Wrapper\PermissionsMask->rmdir('occ')
    /home/ownadmin/public_html/apps/files_trashbin/lib/Storage.php - line 258: call_user_func_array(Array, Array)
    /home/ownadmin/public_html/apps/files_trashbin/lib/Storage.php - line 189: OCA\Files_Trashbin\Storage->doDelete('occ', 'rmdir')
    /home/ownadmin/public_html/lib/private/Files/Storage/Common.php - line 645: OCA\Files_Trashbin\Storage->rmdir('occ')
    /home/ownadmin/public_html/lib/private/Files/Storage/Local.php - line 450: OC\Files\Storage\Common->moveFromStorage(Object(OCA\Files_Trashbin\Storage), 'occ', 'files_trashbin/...')
    /home/ownadmin/public_html/lib/private/Files/Storage/Wrapper/Wrapper.php - line 569: OC\Files\Storage\Local->moveFromStorage(Object(OCA\Files_Trashbin\Storage), 'occ', 'files_trashbin/...')
    /home/ownadmin/public_html/apps/files_trashbin/lib/Trashbin.php - line 251: OC\Files\Storage\Wrapper\Wrapper->moveFromStorage(Object(OCA\Files_Trashbin\Storage), 'occ', 'files_trashbin/...')
    /home/ownadmin/public_html/apps/files_trashbin/lib/Storage.php - line 247: OCA\Files_Trashbin\Trashbin move2trash('SCP/occ', false)
    /home/ownadmin/public_html/apps/files_trashbin/lib/Storage.php - line 189: OCA\Files_Trashbin\Storage->doDelete('occ', 'rmdir')
    /home/ownadmin/public_html/lib/private/Files/View.php - line 1156: OCA\Files_Trashbin\Storage->rmdir('occ')
    /home/ownadmin/public_html/lib/private/Files/View.php - line 348: OC\Files\View->basicOperation('rmdir', '/SCP/occ', Array)
    /home/ownadmin/public_html/apps/dav/lib/Connector/Sabre/Directory.php - line 303: OC\Files\View->rmdir('/SCP/occ')
    /home/ownadmin/public_html/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179: OCA\DAV\Connector\Sabre\Directory->delete()
    /home/ownadmin/public_html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 287: Sabre\DAV\Tree->delete('SCP/occ')
    [internal function] Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/ownadmin/public_html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /home/ownadmin/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method DELETE', Array)
    /home/ownadmin/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/ownadmin/public_html/apps/dav/appinfo/v1/webdav.php - line 76: Sabre\DAV\Server->exec()
    /home/ownadmin/public_html/remote.php - line 162: require_once('/home/ownadmin/...')
    {main}

</details>

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/nextcloud/server/issues/7667

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@wildlifechorus @schnaser @Flandoll Please help testing this :)

**Review by rullzer — APPROVED** [review]
Makes sense

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I guess this needs to be backported tos table12/13?

**Comment by Disco1** [comment]
I'm having the same issue. Trying to delete certain files and folders from S3 causes an error "unable to delete". There is nothing in the nextcloud.log that points to anything of interest. I have verified that the attached fix patch has been applied to my instance (newly downloaded). Any ideas?

**Comment by kesselb** [comment]
@Disco1 would you mind to create a issue report https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md for this? This pull request is not the right place.

**Pull request merged**
