### PR TITLE
AutoCompletion backend

### PR DESCRIPTION
**Pull request by blizzz**
* introduce a Controller for requests
* introduce result sorting mechanism
* extend Comments to retrieve commentors (actors) in a tree
* add commenters sorter
* add share recipients sorter

provides API Endpoint and ServerAPI for #2443 (and as specified there)

This is just the backend, there is no UI code yet. Unit tests however.

---

### Controller

* the optional sorter parameter can take different sorters, by chaining them with pipes. For example "commenters|share-recpients" will sort commentors on top, followed by sharees, and the rest at the end.
* I added an optional "shareTypes" parameter instead of hardcoding "users"

### Sorters

* https://github.com/nextcloud/server/issues/2443#issuecomment-298234750: sorters for 1. and 2. are implemented
* @jancborchardt: question about 3: is the scope limited to the a) comments on the current subject (probably not since 1.), b) to comments in general (could be too wide) or c) not even only with comments, but in any other  possible way (e.g. sharing, calls, …)?
  * this can be added as subsequent PR (also at a later stage)

### Appinfo

* [x] Adjust appstore schema file (not a blocker) – https://github.com/nextcloud/appstore/pull/524

### CODE REVIEW

**Comment by jancborchardt** [comment]
@blizzz I would say the scope of »people you most mentioned or interacted with« is not limited really. Especially as we have sharing, Mail, Calendar events with invites, Contacts, Video calls / chat, etc etc. there are so many sources of interaction which we should all take into account.

However I agree that if 1 and 2 are solved that’s already great and this one can be tackled in a separate pull request. :)

**Comment by blizzz** [comment]
> @blizzz I would say the scope of »people you most mentioned or interacted with« is not limited really. Especially as we have sharing, Mail, Calendar events with invites, Contacts, Video calls / chat, etc etc. there are so many sources of interaction which we should all take into account.

Make sense, requires us to invent another component to collect this data from the various sources (or rather enable them to carry it somewhere). Or perhaps we can extract this from activities somehow, that would be much better. As it already exists and apps are reporting to it.

> However I agree that if 1 and 2 are solved that’s already great and this one can be tackled in a separate pull request. :)

👍

**Comment by blizzz** [comment]
Woke up to today with the realization that the approach has a big disadvantage with large user bases. As spec'd the idea is to fetch all possible users upon opening the comments tab, a bit like Github is doing it. 

The big benefit if this approach is that having users loaded in advance provides us immediate results: you type and have the suggestions without delay, not compromising your writing and train of thought. With big users bases (especially on LDAP) the initial loading might still take too long, making auto complete not available in time. If a huge amount of data is loaded, browsers could act laggish, although I do not expect this since no DOM elements are created for all of them, just on demand.

I still think the basic approach is still the right one. Look up on typing will be too slow and may disturb writing and thinking. Would ruin the experience for everybody. So, how to improve this?

* Regular fetching and caching of all users? Having a background job looking them up every 10 minute sounds a bit stupid, and an overkill. A database table with all users for auto completion is also stupid and almost redundant (an all accounts table would simplify it in this case indeed). Nevertheless, a caching mechanism seems to be reasonable. Perhaps some background job that will be registered on any user- or group-related hook (otherwise runs once a day) and keeps the results in memcache – the approach would miss newly created LDAP users for a while (perhaps good enough).

* Improving LDAP getUsers might be worth and offers potential, but will it be enough? 

Anyhow, i see this as optimization and thus should be build after the feature is standing and complete. it would not change anything fundamentally.

**Comment by blizzz** [comment]
🙋 begging for reviews

**Comment by blizzz** [comment]
OK, this is obviously bullshit, already with 150k users (and the fixed recursion in LDAP's Access, as well as limit of null in the AutoComplete Controller)  I run into exhausted memory. Won't work like spec'd and required, we must limit users anyhow.

**Comment by blizzz** [comment]
> OK, this is obviously bullshit, already with 150k users (and the fixed recursion in LDAP's Access, as well as limit of null in the AutoComplete Controller) I run into exhausted memory. Won't work like spec'd and required, we must limit users anyhow.

Mostly frustration speaking. Backend requires only little changes, frontend needs to change to on-demand requests :-/ Anyway closing and opening a common PR with both backend and gui code, since nobody cared about this one anyway

**Pull request closed without merging**
