### PR TITLE
LDAP simplify User_Proxy and Group_Proxy signatures

### PR DESCRIPTION
**Pull request by blizzz**
… and look what a rat tail it had! 

- make User_Proxy and Group_Proxy easy to instantiate
- simplify dependent code
- move commands to info.xml
- make UpdateGroups job class non-static

### CODE REVIEW

**Comment by blizzz** [comment]
the psalm.xml change fixes 

```
Problem parsing /home/runner/work/server/server/psalm.xml:
  Could not resolve config path to /home/runner/work/server/server//apps/*/appinfo/register_command.php
Script psalm handling the psalm event returned with error code 1
Error: Process completed with exit code 1.
```

since this was the last register_command.php within apps/ dir and has been removed with this PR

**Review by MorrisJobke — APPROVED** [review]
Nice 👍

**Comment by MorrisJobke** [comment]
CI still has some errors due to changed constructor arguments.

**Comment by blizzz** [comment]
> CI still has some errors due to changed constructor arguments.

oh, indeed, slipped through

**Review by nickvergessen — APPROVED** [review]
:shark:

**Pull request merged**
