### PR TITLE
Replace CalDAV availability component with component lib

### PR DESCRIPTION
**Pull request by ChristophWurst**
Requires https://github.com/nextcloud/calendar-availability-vue/pull/6

`/settings/user/groupware` should work like before. This is an internal clean-up/refactoring to deduplicate some code.

This also fixes the regression from https://github.com/nextcloud/server/pull/30020 that all of the personal settings front-end was missing.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@st3iny 

```
ERROR in ./node_modules/@nextcloud/calendar-availability-vue/node_modules/vue-material-design-icons/DotsHorizontal.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template functional>
|   <span :aria-hidden="props.decorative"
|         :aria-label="props.title"
 @ ./node_modules/@nextcloud/calendar-availability-vue/node_modules/@nextcloud/vue/dist/Components/DatetimePicker.js 24:7395-7446
 @ ./node_modules/@nextcloud/calendar-availability-vue/lib/index.esm.js
 @ ./apps/dav/src/service/CalendarService.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./apps/dav/src/views/Availability.vue?vue&type=script&lang=js&
 @ ./apps/dav/src/views/Availability.vue?vue&type=script&lang=js&
 @ ./apps/dav/src/views/Availability.vue
 @ ./apps/dav/src/settings-personal-availability.js
```

**Comment by ChristophWurst** [comment]
https://github.com/npm/npm/issues/7742

**Comment by ChristophWurst** [comment]
@st3iny found the culprit: https://github.com/nextcloud/server/blob/fe7dbb555743671de00f2d27f8689bf3b9d12b9a/webpack.common.js#L133

**Review by miaulalala — CHANGES_REQUESTED** [review]
I can't save working hours any more:

```
could not save availability TypeError: Object(...) is not a function
    at _callee2$ (CalendarService.js:134)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:294)
    at Generator.next (runtime.js:119)
    at asyncGeneratorStep (CalendarService.js:19)
    at _next (CalendarService.js:21)
    at CalendarService.js:21
    at new Promise (<anonymous>)
    at CalendarService.js:21
    at _saveScheduleInboxAvailability (CalendarService.js:152)```

**Comment by ChristophWurst** [comment]
Bildschirmfoto von 2022-01-03 13-08-04

I can not reproduce yet

**Comment by ChristophWurst** [comment]
did you check out the branch and use my commited bundles or did you build it yourself @miaulalala?

**Comment by miaulalala** [comment]
Firefox is telling me it's somewhere in Availability.vue, catching in the try-catch- block on case 8.

**Comment by ChristophWurst** [comment]
According to your trace it must be inside `saveScheduleInboxAvailability`. Do you see the `New availablity ical created` message?

**Comment by miaulalala** [comment]
No.

> According to your trace it must be inside `saveScheduleInboxAvailability`. Do you see the `New availability ical created` message?

No, just the error.

**Comment by ChristophWurst** [comment]
Please build your own artifacts with

```
npm ci
MODULE=dav npm run dev
```

and reproduce another time. There should be more elaborative traces/errors.

**Comment by miaulalala** [comment]
Right, there really isn't much more:


On page load:

``` 
could not load existing availability TypeError: _yield$findScheduleIn is undefined
    _callee$ Availability.vue:149
    tryCatch runtime.js:63
    invoke runtime.js:294
    defineIteratorMethods runtime.js:119
    asyncGeneratorStep Availability.vue:13
    _next Availability.vue:15
    promise callback*asyncGeneratorStep Availability.vue:13
    _next Availability.vue:15
    _asyncToGenerator Availability.vue:15
    _asyncToGenerator Availability.vue:15
    mounted Availability.vue:189
    VueJS 4
        invokeWithErrorHandling
        callHook
        mountComponent
        $mount
    js settings-personal-availability.js:6
    Webpack 3
        __webpack_require__
        <anonymous>
        <anonymous>
Availability.vue:176
    _callee$ Availability.vue:176
    tryCatch runtime.js:63
    invoke runtime.js:294
    defineIteratorMethods runtime.js:119
    asyncGeneratorStep Availability.vue:13
    _next Availability.vue:15
    (Async: promise callback)
    asyncGeneratorStep Availability.vue:13
    _next Availability.vue:15
    _asyncToGenerator Availability.vue:15
    _asyncToGenerator Availability.vue:15
    mounted Availability.vue:189
    VueJS 4
        invokeWithErrorHandling
        callHook
        mountComponent
        $mount
    js settings-personal-availability.js:6
    Webpack 3
        __webpack_require__
        <anonymous>
        <anonymous>

```

On saving:

```
could not save availability TypeError: Object(...) is not a function
    _callee2$ CalendarService.js:134
    tryCatch runtime.js:63
    invoke runtime.js:294
    defineIteratorMethods runtime.js:119
    asyncGeneratorStep CalendarService.js:19
    _next CalendarService.js:21
    _asyncToGenerator CalendarService.js:21
    _asyncToGenerator CalendarService.js:21
    _saveScheduleInboxAvailability CalendarService.js:152
    saveScheduleInboxAvailability CalendarService.js:117
    _callee2$ Availability.vue:232
    tryCatch runtime.js:63
    invoke runtime.js:294
    defineIteratorMethods runtime.js:119
    asyncGeneratorStep Availability.vue:13
    _next Availability.vue:15
    _asyncToGenerator Availability.vue:15
    _asyncToGenerator Availability.vue:15
    save Availability.vue:254
    VueJS 17
        invokeWithErrorHandling
        invoker
        _wrapper
        add$1
        updateListeners
        updateDOMListeners
        invokeCreateHooks
        createElm
        createChildren
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mountComponent
        $mount
    js settings-personal-availability.js:6
    Webpack 3
        __webpack_require__
        <anonymous>
        <anonymous>
Availability.vue:241
```

**Review by miaulalala — APPROVED** [review]

**Comment by miaulalala** [comment]
Works now!

**Review by st3iny — APPROVED** [review]
Tested and works.

**Comment by miaulalala** [comment]
Drone failure unrelated.

**Comment by ChristophWurst** [comment]
> Uncaught ReferenceError: assignment to undeclared variable ICAL

doesn't work anymore, yay.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/blob/0554ef4ddc45369872db41f84ffca08559d76f7b/webpack.config.js#L67-L73 might be necessary

**Comment by st3iny** [comment]
> https://github.com/nextcloud/calendar/blob/0554ef4ddc45369872db41f84ffca08559d76f7b/webpack.config.js#L67-L73 might be necessary

Done! Tested and it works fine again.

**Comment by st3iny** [comment]
I tried to rebase and have bad news: server requires @nextcloud/vue v5 but calendar-availability-vue requires v4.2 as a peer. We have to update and release the lib first.

**Pull request merged**
