### PR TITLE
Fix sorting of favorite files in file list

### PR DESCRIPTION
**Pull request by danxuliu**
Fix for #5410

In the end I decided that making the sort comparator extensible by plugins was not worth it right now; I prefer to defer that until there are more use cases in order to get a better idea of the needed API. Also, as @nickvergessen  pointed out, favorite files is a core feature of the file list even if implemented as a plugin, so it is not so terrible if it is taken into account in the main sorting logic ;)

Acceptance tests for the original issue could not be provided, as at this time the acceptance test system only supports tests that exclusively depend on the core server (and the original issue was related to the text editor, which is a separate app). However, acceptance tests were provided for a related issue: marking a file as a favorite should sort again the file list.

I assumed that it was a bug, but I prefer to notify @nextcloud/designers  just in case: before, when you marked a file as a favorite, the file stayed in the same position in the file list. However, when you reloaded the file list (for example reloading the page, or changing to a different folder and then going back to the original one), the file the appeared at the top of the file list with the other favorite files. Now, when you mark a file as a favorite, the file is immediately moved to the top with the other favorite files (personally I would add a quick animation for that position change, but that is another matter ;) ). As I said I assumed that it was a bug, but maybe it was an explicit design decision to prevent a "Where did my file just go?" reaction from the user.

In any case, once it is confirmed that it now works as it should, should I backport the fix to Nextcloud 12? I would say yes, as it is just a small bugfix, but you know better than me ;)

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Works perfectly

**Comment by MorrisJobke** [comment]
> I assumed that it was a bug, but I prefer to notify @nextcloud/designers just in case: before, when you marked a file as a favorite, the file stayed in the same position in the file list. However, when you reloaded the file list (for example reloading the page, or changing to a different folder and then going back to the original one), the file the appeared at the top of the file list with the other favorite files. Now, when you mark a file as a favorite, the file is immediately moved to the top with the other favorite files (personally I would add a quick animation for that position change, but that is another matter ;) ). As I said I assumed that it was a bug, but maybe it was an explicit design decision to prevent a "Where did my file just go?" reaction from the user.

I'm fine with this. At least it is more consistent then.

Also the bug is fixed 👍

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> In any case, once it is confirmed that it now works as it should, should I backport the fix to Nextcloud 12? I would say yes, as it is just a small bugfix, but you know better than me ;)

I would not backport it.

**Comment by jancborchardt** [comment]
> Now, when you mark a file as a favorite, the file is immediately moved to the top with the other favorite files (personally I would add a quick animation for that position change, but that is another matter ;) )

Awesome, yes it's a great fix! :) An additional pull request to add the animation would be greatly appreciated, as that indeed fixes the "where did the file just go?" case. :)

**Pull request merged**
