### PR TITLE
Fix unselecting items on multi select dropdowns

### LINKED ISSUE #5510: Select2 broken on 12 - Can not unselect items on multi-select anymore
We use select2 in many locations:
* Automated tagging (assign tag block)
* Group selection for:
  - Sharing disabled for groups
  - Update notification group
  - Announcement center posting group
* System tag assignments

In all those places you can not unselect an item. When you click on it, it will select the next item, until there are no items left over.
This is crucial for those features and needs immediate fixing for 12.0.1 and backporting to 11 as well

@nextcloud/javascript

### PR DESCRIPTION
**Pull request by danxuliu**
Fixes #5510

By default, items in a multi-select dropdown can not be unselected by clicking on them. That feature is provided by an extension, [select2-toggleselect](https://github.com/nextcloud/server/blob/ffba6d0a7e1988bed1c0f0dfa2334092a65c568d/core/js/select2-toggleselect.js), which must be explicitly enabled in the property `toggleSelect` of each Select2 object. For example, as it is done in the [system tags](https://github.com/nextcloud/server/blob/a9ccfe06d95905d923b2871a3acd162f3d1aec1a/core/js/systemtags/systemtagsinputfield.js#L413).

However, unselecting items was also broken in the system tags; the reason is that _select2-toggleselect.js_ was never loaded, and thus the `toggleSelect` property had no effect. It seems that it slipped through when moving things around in commit 6a470e5935.

This pull request provides acceptance tests for unselecting items in the system tags dropdown in the details view of the _Files_ app, loads again _select2-toggleselect.js_ and enables `toggleSelect` in the rest of the multi-select dropdowns (I would have made instead that all the multi-select dropdowns use `toggleSelect` by default unless explicitly disabled, but I do not know if that could break other apps).

However, note that the markup and/or style of items in the multi-select dropdowns was not modified. Thus, the system tags dropdown in the details view of the _Files_ app shows a checkmark in those items that are selected, but other dropdowns (like the one in the _Tags_ section of the _Files_ app) do not. The common style for dropdowns uses a different background color for those items that are selected, though, so feedback about the selected items is provided anyway (however, that background is the same used for highlighted but not selected yet items, which persists even if the cursor is moved outside the dropdown; the difference between a selected item and an highlighted but not selected yet item then is just a subtle stronger font in the case of the highlighted item. I do not know if @nextcloud/designers are aware of that).

Just for the record, the markup of items in the dropdown is set through the function assigned to the `formatResult` property of the Select2 object. See, for example, [the function assigned to that property in the system tags](https://github.com/nextcloud/server/blob/a9ccfe06d95905d923b2871a3acd162f3d1aec1a/core/js/systemtags/systemtagsinputfield.js#L312).

Finally, should this be backported to Nextcloud 12? I would say yes but, again, you know better than me ;-) (however this time at least @nickvergessen [also thinks that it should](https://github.com/nextcloud/server/issues/5510#issue-237774708) :-P ).

### CODE REVIEW

**Comment by danxuliu** [comment]
Oops, one of the acceptance tests failed when run in Drone. The reason was that if the dropdown is opened it is not automatically updated when a new tag is added to the server. Thus, if the dropdown is opened after creating the tag but before the tag was really added to the server the dropdown would not show it; it would be necessary to close the dropdown and open it again for the tag to be shown.

It is not possible to wait for the tag to be really added to the server to then open the dropdown, as no explicit feedback is given to the user about that. Therefore, I have amended the commit and modified the test to open and close the dropdown several times until the tag appears or the timeout expires.

**Comment by danxuliu** [comment]
Well, this time it should work... :-P After the previous fix the acceptance tests still failed when run in Drone. There were two reasons for that: first, Select2 loads the dropdown contents once the dropdown was opened, so it is not possible to wait for the dropdown to open and then inmediately look for the tag; a timeout must be used when looking for a tag in the dropdown. And second, when creating the tags in the settings it is necessary to ensure that they were really added before trying to use them in the Files app.

I have amended again the commits to fix those issues.

**Comment by danxuliu** [comment]
And, once again, the acceptance tests fail. I hereby proclaim myself _Clumsiest developer of the week_ ― bows bashfully before the audience, humbled by the recognition ― I was not expecting this, but I would like to thank my lack of sleep; I could only get this far thanks to its support. I would like to add that I have no further aspirations, but let's see how all this evolves; maybe I will be able to contend for the _Clumsiest developer of the month_ title :-) ― Descends from stage and changes _to review_ label to _developing_ until acceptance tests run successfully in Drone.

**Comment by danxuliu** [comment]
The acceptance tests failed because the button to create a tag in the settings does nothing before JavaScript is loaded; the only way to know when that happens is waiting for the button to select tags to appear, so the tests were modified to check that before trying to create a tag.

**Comment by danxuliu** [comment]
At last the acceptance tests introduced here seem to be working in Drone; of course the fact that they worked once does not mean that they are definitely working, but it looks good anyway ;-) Thus I am promoting the pull request again to _to review_.

**Comment by nickvergessen** [comment]
Fixes the systemtags 👍 
But group selections is still not working. E.g. Settings > Sharing > Exclude groups from sharing

Try to add a group and remove it again.

**Comment by danxuliu** [comment]
>  But group selections is still not working. E.g. Settings > Sharing > Exclude groups from sharing
>  Try to add a group and remove it again.

Strange, I have just tried it and it works fine here. Maybe a cache issue with the old JavaScript files?

**Review by nickvergessen — APPROVED** [review]
Works, very good work again 🎉

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
There were just too many failure - I restarted the jobs ;)

**Comment by MorrisJobke** [comment]
> Finally, should this be backported to Nextcloud 12? I would say yes but, again, you know better than me ;-) (however this time at least @nickvergessen also thinks that it should :-P ).

Yes - do it ;)

**Comment by nickvergessen** [comment]
@danxuliu can you do it? we plan to do the next maintenance release this week ;)

**Comment by danxuliu** [comment]
Done ;-)

**Pull request merged**
