### PR TITLE
Bump the Symfony polyfills

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Review by manning-ncsa — APPROVED** [review]

**Review by anaqreon — APPROVED** [review]
I'm no expert on this part of the code, but after scanning through the files changes, it looks like all that has occurred is that the version of a library dependency was updated from v1.22.0 to v1.22.1 in the 3rdparty submodule.

**Comment by anaqreon** [comment]
I accidentally submitted my review through my professional account. Please delete that manninga-ncsa comment above as well as this one.

**Comment by ChristophWurst** [comment]
I can't delete the review comment :/

**Comment by anaqreon** [comment]
> I can't delete the review comment :/

No worries. On the bright side, it looks like you already have the two approvals you need :laughing:

**Review by rullzer — APPROVED** [review]

**Pull request merged**
