### PR TITLE
Port admin federated files sharing to vue

### PR DESCRIPTION
**Pull request by CarlSchwan**
image

Use the fancy new vue components (good for accessibility)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Some eslint issues, otherwise good! :rocket:

**Review by artonge — APPROVED** [review]

**Comment by skjnldsv** [comment]
```
There were 4 errors:
228 |  
229 | 1) OCA\FederatedFileSharing\Tests\Settings\AdminTest::testGetForm with data set #0 (true)
230 | ArgumentCountError: Too few arguments to function OCA\FederatedFileSharing\Settings\Admin::__construct(), 3 passed in /drone/src/apps/federatedfilesharing/tests/Settings/AdminTest.php on line 50 and exactly 5 expected
231 |  
232 | /drone/src/apps/federatedfilesharing/lib/Settings/Admin.php:45
233 | /drone/src/apps/federatedfilesharing/tests/Settings/AdminTest.php:50
234 |  
235 | 2) OCA\FederatedFileSharing\Tests\Settings\AdminTest::testGetForm with data set #1 (false)
236 | ArgumentCountError: Too few arguments to function OCA\FederatedFileSharing\Settings\Admin::__construct(), 3 passed in /drone/src/apps/federatedfilesharing/tests/Settings/AdminTest.php on line 50 and exactly 5 expected
237 |  
238 | /drone/src/apps/federatedfilesharing/lib/Settings/Admin.php:45
239 | /drone/src/apps/federatedfilesharing/tests/Settings/AdminTest.php:50
240 |  
241 | 3) OCA\FederatedFileSharing\Tests\Settings\AdminTest::testGetSection
242 | ArgumentCountError: Too few arguments to function OCA\FederatedFileSharing\Settings\Admin::__construct(), 3 passed in /drone/src/apps/federatedfilesharing/tests/Settings/AdminTest.php on line 50 and exactly 5 expected
243 |  
244 | /drone/src/apps/federatedfilesharing/lib/Settings/Admin.php:45
245 | /drone/src/apps/federatedfilesharing/tests/Settings/AdminTest.php:50
246 |  
247 | 4) OCA\FederatedFileSharing\Tests\Settings\AdminTest::testGetPriority
248 | ArgumentCountError: Too few arguments to function OCA\FederatedFileSharing\Settings\Admin::__construct(), 3 passed in /drone/src/apps/federatedfilesharing/tests/Settings/AdminTest.php on line 50 and exactly 5 expected
249 |  
250 | /drone/src/apps/federatedfilesharing/lib/Settings/Admin.php:45
251 | /drone/src/apps/federatedfilesharing/tests/Settings/AdminTest.php:50
```

**Comment by CarlSchwan** [comment]
ci failure unrelated

**Pull request merged**
