### PR TITLE
[Automated] Update psalm-baseline.xml

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated update psalm-baseline.xml with fixed psalm warnings

Replace https://github.com/nextcloud/server/pull/29299

### CODE REVIEW

**Comment by skjnldsv** [comment]
```
Error: Argument 2 of OCP\DB\QueryBuilder\IQueryBuilder::set expects OCP\DB\QueryBuilder\IParameter|string, OCP\DB\QueryBuilder\IQueryFunction provided with a __toString method
Error: Argument 1 of OCP\Files\IMimeTypeDetector::detectContent expects string, bool|string provided
Error: The declared return type 'resource' for OC\Archive\TAR::getStream is incorrect, got 'bool|resource'
Error: The inferred type 'bool|resource' does not match the declared return type 'resource' for OC\Archive\TAR::getStream
Error: The declared return type 'resource' for OC\Archive\ZIP::getStream is incorrect, got 'bool|resource'
Error: The inferred type 'bool|resource' does not match the declared return type 'resource' for OC\Archive\ZIP::getStream
Error: Found a redundant condition when evaluating $result and trying to reconcile type 'true' to !falsy
Error: The declared return type 'bool|string' for OC\Files\Storage\Wrapper\Availability::filetype is not nullable, but 'bool|null|string' contains null
Error: The inferred type 'bool|int' does not match the declared return type 'int' for OC\Files\Storage\Wrapper\Encryption::filesize
Error: The declared return type 'string' for OC\Files\Storage\Wrapper\Encryption::file_get_contents is incorrect, got 'bool|string'
Error: The inferred type 'bool|string' does not match the declared return type 'string' for OC\Files\Storage\Wrapper\Encryption::file_get_contents
Error: Argument 12 of OC\Files\Stream\Encryption::wrap expects int, bool|int provided
Error: Argument 2 of OC\Files\Storage\Wrapper\Encryption::fixUnencryptedSize expects int, bool|int provided
Error: Argument 2 of OC\Files\Storage\Wrapper\Encryption::touch expects int|null, bool|int provided
Error: The declared return type 'string' for OC\Files\Storage\Wrapper\Encryption::getLocalFile is incorrect, got 'bool|string'
Error: The inferred type 'bool|string' does not match the declared return type 'string' for OC\Files\Storage\Wrapper\Encryption::getLocalFile
Error: The declared return type 'array<array-key, mixed>' for OC\Files\Storage\Wrapper\Encryption::stat is incorrect, got 'array{7: int, hasHeader: bool, size: int}<array-key, mixed>|bool'
Error: The inferred type 'array{7: int, hasHeader: bool, size: int}<array-key, mixed>|bool' does not match the declared return type 'array<array-key, mixed>' for OC\Files\Storage\Wrapper\Encryption::stat
Error: The declared return type 'int' for OC\Files\Stream\Encryption::writeHeader does not allow false, but the function returns 'false|int'
Error: The declared return type 'string' for OC\Preview\ProviderV2::getLocalFile is incorrect, got 'bool|string'
Error: The inferred type 'bool|string' does not match the declared return type 'string' for OC\Preview\ProviderV2::getLocalFile
Script psalm handling the psalm event returned with error code 1
Error: Process completed with exit code 1.
```

**Comment by skjnldsv** [comment]
@PVince81 wanna continue fixing this somehow? Tried my best, really not sure what I'm doing...

**Comment by MichaIng** [comment]
I don't understand the second error:
```php
while ($result and ($file = readdir($dh)) !== false) {
```
> Found a redundant condition when evaluating $result and trying to reconcile type 'true' to !falsy

But at least due to low precedence of `and` (vs `&&`) only the resulting `$file` is compared to `false`, isn't it? Probably the following mutes it, but it shouldn't change anything about the logic:
```php
while ($result and (($file = readdir($dh)) !== false)) {
```

**Comment by MichaIng** [comment]
Is this still relevant as of NC20 being EOL?

**Comment by skjnldsv** [comment]
Maybe not yeah

**Pull request closed without merging**
