### PR TITLE
Deferred script loading

### PR DESCRIPTION
**Pull request by michaelletzgus**
Discussed here: https://github.com/nextcloud/server/issues/2272

### CODE REVIEW

**Comment by benediktg** [comment]
I would recommend to squash these commits into a single one. 😉

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Before we merge that I'd love to have some official feedback from Mozilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1342781

**Comment by LukasReschke** [comment]
@jancborchardt @jospoortvliet Knowing any Mozilla people? 😉

**Comment by michaelletzgus** [comment]
@benediktg 
Can I squash the 4 commits or do I need write access to this repository?
Or should I commit all 4 files together? I did the changes online, without a local repository. My local test-repository is not working yet, there is some trouble with nginx and a repository as root...

**Comment by benediktg** [comment]
(slightly off-topic)

> Can I squash the 4 commits or do I need write access to this repository?

You can squash the latest 4 commits in the current branch by doing
```sh
git rebase -i HEAD~4
# replace the lower 3 occurences of 'pick' by 's'
git push --force-with-lease
```
in the branch of you own fork. Otherwise also the project maintainers could squash the commits at merging.

**Comment by michaelletzgus** [comment]
Done

**Comment by michaelletzgus** [comment]
Please see PR #3696

**Pull request closed without merging**
