### PR TITLE
Allow external actions to users list

### LINKED ISSUE #10571: The userRow in User Management needs a way to register menu entries
otherwise apps like impersonate cannot add an entry anymore. Cf. https://github.com/nextcloud/impersonate/issues/53

### PR DESCRIPTION
**Pull request by skjnldsv**
@juliushaertl thoughts?

```js
OCA.Settings.UserList.registerAction('icon-edit','Log event',console.log)
OCA.Settings.UserList.registerAction('icon-edit','Log userID', event => {console.log(event.target.closest('.row').dataset.id)})
```

Fix https://github.com/nextcloud/server/issues/10571

### CODE REVIEW

**Comment by blizzz** [comment]
That's great, yet I am having difficulties to get the user id from an external app. Suggestions? `this` inside the function is bound to the window object.

**Comment by skjnldsv** [comment]
@blizzz `event.target.closest('.row').dataset.id`
The event is passed into the function :)

**Comment by blizzz** [comment]
That ^ said, it would make sense if the userRow object could be provided as parameter to the `action` callback.

**Comment by blizzz** [comment]
That ^ said, it would make sense if the userRow object could be provided as parameter to the `action` callback.

**Comment by blizzz** [comment]
@skjnldsv that does the trick! thx.

**Review by blizzz — APPROVED** [review]
Looks good from my PoV, and satisfies the needs for impersonate

**Review by blizzz — APPROVED** [review]

**Comment by rullzer** [comment]
While ok from my point of view. I'd like @juliushaertl to have a look as his javascript fu is superior to mine ;)

**Comment by juliushaertl** [comment]
@blizzz Are there any cases where those actions should not be added, like for the current user? Because right now there is no way to exclude certain entries from adding the additional popovermenu entry.

**Comment by rullzer** [comment]
Rebase needed

**Comment by blizzz** [comment]
@skjnldsv could ya rebase?

**Review by rullzer — APPROVED** [review]
Then lets do this :elephant:

**Pull request merged**
