### PR TITLE
Upload time and Creation time

### PR DESCRIPTION
**Pull request by icewind1991**
This adds the logic to use the `filecache_extended` table, it allows storing and retrieving `metadata_etag`, `creation_time` and `upload_time` in the filecache, however `metadata_etag` is not exposed trough the public api for now and any logic for tracking it is left for future work.

- Upload time is set automatically for every file uploaded over DAV
- Creation time is not set automatically at the moment, but has to to be set by sync clients (either trough `PROPFIND` or as a header during upload)

We might want to add some automated logic for setting ctime in the future.

Now the `filecache_extended` table is getting used, we should think of any fields we might want to store in the future (even if they remain unused for a while) before we release 18

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Awesome!
Seems to work. Lets get this in now and discuss the rest separately. It already got big enough IMO.

**Review by ChristophWurst — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
> `metadata_etag` is not exposed trough the public api for now and any logic for tracking it is left for future work.

Can we schedule this also for 18, if possible? @rullzer 
Client are waiting since ~13 for it…

**Comment by rullzer** [comment]
@tobiasKaminsky sure we can expose it. But right now it doesn't do anything so there is no use.

It is an empty column. Just adding some value there doesn't help as it would need to duplicate the propagation logic as well because other wise you'd still need to check all files separately and then you can just do what you do now.

**Comment by tobiasKaminsky** [comment]
Damn…I only read the first part with "exposing"…

**Comment by marinofaggiana** [comment]
@icewind1991 @rullzer I have create a search dav as :

```
<?xml version="1.0"?>
<d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"> 
<d:basicsearch>
...
<d:lte>
  <d:prop>
    <nc:upload_time />
  </d:prop>
  <d:literal>1591716364.299685</d:literal>
</d:lte>
...

```
 but do not works (errro 400) ... It's a my error ?

**Comment by tobiasKaminsky** [comment]
upload time needs to be a unix timestamp as far as I understand this, so e.g. 1591767801.
It is only seconds, nothing more.

**Comment by marinofaggiana** [comment]
@tobiasKaminsky do not change, the error 400 continues ...

**Comment by marinofaggiana** [comment]
@icewind1991 please, the new properties works with the searchrequest ?

**Pull request merged**
