### PR TITLE
fix strange-looking button

### LINKED ISSUE #33835: New folder input fields look strange
See 
image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/33835

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by blizzz** [comment]
i thought scss is dead, but then i may have misunderstood?

**Comment by blizzz** [comment]
> > i thought scss is dead, but then i may have misunderstood?
> 
> the files app is not ported to vue yet so why should scss be dead?

Excellent question.

**Review by CarlSchwan — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
CI faolure unrelated

**Pull request merged**
