### PR TITLE
Remove input id on login form

### LINKED ISSUE #10209: Submit button of login page should not use `id="submit"`
The 57th line of the file `/core/templates/login.php` have a potential bug
```
<input type="submit" id="submit" class="login primary" title="" value="<?php p($l->t('Log in')); ?>" disabled="disabled" />
```
When I run the code `document.querySelector('form[name="login"]').submit()` under login page and an error will be thrown
```
VM78:1 Uncaught TypeError: document.querySelector(...).submit is not a function
    at <anonymous>:1:46
```
I can't submit this form because `document.querySelector('form[name="login"]').submit` is not a function but a HTMLElement of the submit button.

Please fix it and thanks!

Version Of Server: v13.0.4 and v14

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #10209

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
sure

**Comment by rullzer** [comment]
Uhm... all acceptance tests do boom...

**Pull request merged**
