### PR TITLE
Bump @nextcloud/vue to 6.0.0-beta.1 and vue-template-compiler

### PR DESCRIPTION
**Pull request by PVince81**
- [x] resolve compilation issues (see below)
- [ ] :no_entry_sign: missing icons
- [ ] smoke test

I was advised by @juliushaertl to update vue-template-compiler to 2.7 which I did here

### CODE REVIEW

**Comment by juliushaertl** [comment]
Either changing each import to add .js for the vue components or https://github.com/nextcloud/eslint-config/pull/383 should fix the listing issue, but there seems to be another version incompatibility:

```
npm ERR! While resolving: @nextcloud/calendar-availability-vue@0.3.1
[9](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:10)
npm ERR! Found: @nextcloud/vue@6.0.0-beta.1
[10](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:11)
npm ERR! node_modules/@nextcloud/vue
[11](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:12)
npm ERR!   @nextcloud/vue@"^6.0.0-beta.1" from the root project
[12](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:13)
npm ERR! 
[13](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:14)
npm ERR! Could not resolve dependency:
[14](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:15)
npm ERR! peer @nextcloud/vue@"^4.2||^5.0" from @nextcloud/calendar-availability-vue@0.3.1
[15](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:16)
npm ERR! node_modules/@nextcloud/calendar-availability-vue
[16](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:17)
npm ERR!   @nextcloud/calendar-availability-vue@"^0.3.1" from the root project
[17](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:18)
npm ERR! 
[18](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:19)
npm ERR! Conflicting peer dependency: @nextcloud/vue@4.4.0
[19](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:20)
npm ERR! node_modules/@nextcloud/vue
[20](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:21)
npm ERR!   peer @nextcloud/vue@"^4.2||^5.0" from @nextcloud/calendar-availability-vue@0.3.1
[21](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:22)
npm ERR!   node_modules/@nextcloud/calendar-availability-vue
[22](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:23)
npm ERR!     @nextcloud/calendar-availability-vue@"^0.3.1" from the root project
[23](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:24)
npm ERR! 
[24](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:25)
npm ERR! Fix the upstream dependency conflict, or retry
[25](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:26)
npm ERR! this command with --force, or --legacy-peer-deps
[26](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:27)
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[27](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:28)
npm ERR! 
[28](https://github.com/nextcloud/server/runs/7786946170?check_suite_focus=true#step:6:29)
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.
```

**Comment by PVince81** [comment]
I've renamed ButtonVue to Button and the local compilation is fixed.

Now the next problem, missing icon:
image

I'll recheck/recompile just to be sure

**Comment by PVince81** [comment]
with node v14 there was no error about @nextcloud/calendar-availability-vue@"^0.3.1

after upgrading to node v16 that error appears for me as well

**Comment by PVince81** [comment]
- [ ] update the failing lib: https://github.com/nextcloud/calendar-availability-vue/pull/22

**Comment by juliushaertl** [comment]
Icons can be fixed by running `npm run build` and `npm run sass` before `npm run sass:icons`. Doesn't work out of the box on this branch as the dist/ folder is not present.

**Comment by PVince81** [comment]
seems I deleted the dist folder by mistake, I'll bring it back

**Comment by PVince81** [comment]
I did "npm ci --force" to bypass the dep issue for now and brought back the dist folder, and run `npm run sass && npm run sass:icons`, force refreshed the browser. Icon still missing.

**Comment by PVince81** [comment]
I remember that usually the files app icons would disappear when we forget "sass:icons", but they're here:
image

so perhaps it's not the icon compilation and maybe a CSS problem or other problem with the Actions component ?

also see that the favorite icon now has a border, so either a bug or needs adjustments here

**Comment by PVince81** [comment]
as far as I can see the working buttons have the CSS classes `button-vue button-vue--icon-only button-vue--vue-tertiary action-item__menutoggle` the the one with missing icon only has `button-vue sharing-entry__actions button-vue--vue-tertiary action-item action-item--single new-share-link v-popper--has-tooltip`, no mention of icon

I'll see if we're missing a vue attribute

**Comment by PVince81** [comment]
this is the button in question: https://github.com/nextcloud/server/blob/update-nextcloud-vue-6.0.0-beta.1/apps/files_sharing/src/components/SharingEntryLink.vue#L299

based on the conditions it would be a single action button which is then supposed to render inline
as far as I can see inline rendering is NOT broken: https://nextcloud-vue-components.netlify.app/#/Components/Actions?id=actions-1 or at least not when using Vue icons

**Comment by PVince81** [comment]
the missing icon on ActionButton is a regression, raised here: https://github.com/nextcloud/nextcloud-vue/pull/3006

**Comment by PVince81** [comment]
cool, at least it compiles now

waiting for the action button regression fixes to attempt another update

**Comment by PVince81** [comment]
next iteration: https://github.com/nextcloud/server/pull/33516

**Pull request closed without merging**
