### PR TITLE
Remove unused legacy ajax/list.php in files app

### PR DESCRIPTION
**Pull request by PVince81**
## Summary

Remove unused legacy ajax/list.php in files app

## Tests

- [x] spreed app is not using the code block saying that spreedme was using it: file picker works fine still
- [x] tested file list
- [x] tested public file list
- [x] tested trashbin file list

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes) => none

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Can you rebase onto https://github.com/nextcloud/server/pull/35772?
So I don't have to rebase? Or we merge after it

**Comment by PVince81** [comment]
@skjnldsv let's merge yours first, it has higher priority. then I'll rebase :-)

**Review by artonge — APPROVED** [review]

**Review by come-nc — APPROVED** [review]
:broom:

**Comment by PVince81** [comment]
rebased with conflicts solved

**Comment by skjnldsv** [comment]
Needs a node compile then :)

**Pull request merged**
