### PR TITLE
Add heading to account access page

### PR DESCRIPTION
**Pull request by jancborchardt**
It would also be awesome if we could bold the client requesting access so it stands out. Like:

> You are about to grant **Fairphone** access to your Nextcloud account.

Is that possible @MorrisJobke @LukasReschke?

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Is that possible @MorrisJobke @LukasReschke?

I would say so. Just escape the client name and print the text itself unescaped. Right @LukasReschke ?

**Comment by jancborchardt** [comment]
Cool! How would that be written syntactically?

**Comment by MorrisJobke** [comment]
> Cool! How would that be written syntactically?

print_unescaped in the middle and an `\OCP\Util::sanitizeHTML()` for the name. Let me check and update this PR.

**Comment by MorrisJobke** [comment]
I added it:

bildschirmfoto 2017-08-14 um 10 40 39

@LukasReschke Please have a look, but it should be fine.

**Review by MorrisJobke — APPROVED** [review]

**Comment by MariusBluem** [comment]
If the device name is bolt, I see no reason for those " " 🤔

**Comment by MorrisJobke** [comment]
> If the device name is bolt, I see no reason for those " " 🤔

Dropped.

**Review by MariusBluem — APPROVED** [review]

**Comment by jancborchardt** [comment]
Oh wow that's a lot of strange code needed :D thanks @MorrisJobke!

Good feedback @MariusBluem, would have also dropped the "" :)

**Pull request merged**
