### PR TITLE
fix linebreak on public share page

### LINKED ISSUE #10849: public share footer linebreak in "Get your own free account"
### Steps to reproduce
1. update to 14 RC1
2. visit a public share link
3. see a linebreak in "Get your own free account" even though there is more than enough space for the text

### Expected behaviour
no line break

### Actual behaviour
line break

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.5

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 14.0.0RC1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 13

**Where did you install Nextcloud from:** official nextcloud download page

### Browser
Firefox 61.0.2

### PR DESCRIPTION
**Pull request by violoncelloCH**
same changes as in #10850 but hopefully correctly signed off this time
fixes #10849
Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@jancborchardt you and @skjnldsv discussed about this quite heavily ... could you have a look at this please.

**Comment by skjnldsv** [comment]
@juliushaertl @MorrisJobke this is what I talked to you about. Basically this is to allow links to have a bigger clickable area, but css can go :boom: with those kind of 'hacks'

**Comment by MorrisJobke** [comment]
> @juliushaertl @MorrisJobke this is what I talked to you about. Basically this is to allow links to have a bigger clickable area, but css can go 💥 with those kind of 'hacks'

I know, but as this was a longer offline discussion I would like to have it written down here as well and to get to a common conclusion and not just merge the stuff without have a common view.

**Comment by rullzer** [comment]
@jancborchardt did you fix this in a different PR yesterday?

**Comment by violoncelloch** [comment]
@rullzer I think @juliushaertl at least startet with a fix in #10912

**Comment by jancborchardt** [comment]
And also for the record – the padding is intended, for better clickability. And the negative margin is needed to make the text flow ok again left and right. Yes it can use improvement, but let’s not remove it. :)

**Pull request closed without merging**
