### PR TITLE
make chunksize (used to check for gone LDAP users) configurable

### PR DESCRIPTION
**Pull request by blizzz**
with a fair amount of users it could take a bit until a user was recognized as unavailable

Set it via `php occ config:app:set --value=300 user_ldap cleanUpJobChunkSize`

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]
:+1: 

Would be nice to have the config flag documented somewhere.

**Review by ChristophWurst — APPROVED** [review]

**Comment by blizzz** [comment]
(rebased for CI)

**Pull request merged**
