### PR TITLE
Let the user confirm the remote wipe

### LINKED ISSUE #15645: Use confirmation modal for wipe
Once we have https://github.com/nextcloud/nextcloud-vue/issues/408 it would be great to have a pre-wipe confirmation modal since it is a pretty destructive action.

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/15645

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
image


Looks a bit blurry to me, and ! is out of place?
Functional it is working :+1:

**Comment by ChristophWurst** [comment]
> Looks a bit blurry to me

resize the browser window. this is bad rending of a font that is positioned at a fraction of a pixel. unfortunately there are many spots where this is an issue in Nextcloud.

> ! is out of place?

yes, but that is an issue with the confirm modal in general. mind opening a ticket for that and pinging our designers? thx

**Review by rullzer — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Amended the commit with a little fix that removes the `@PasswordConfirmationRequired` annotation from the controller method.

**Review by MorrisJobke — APPROVED** [review]
tested and works 👍

**Comment by MorrisJobke** [comment]
@skjnldsv @ChristophWurst Mind to rebuild the JS files?

**Comment by skjnldsv** [comment]
Needs rebase :(

**Comment by ChristophWurst** [comment]
> Needs rebase :(

done

**Pull request merged**
