### PR TITLE
Replace custom tooltips with native ones and add description to all e…

### LINKED ISSUE #37179: [Bug]: Tooltips in LDAP wizard unreadable
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

image

### Steps to reproduce

1. Enable ldap app
2. Add a new ldap connection
3. Wonder about the grey boxes ;)

### Expected behavior

Readable tooltips

### Installation method

Other Community project

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
age_of_empires_2
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Replace custom tooltips with native ones and add description to all elements which have `title`. 

* Resolves: https://github.com/nextcloud/server/issues/37179

## Summary

Make tooltips in LDAP wizard readable and accessible.

Before: 

image

After: 

Screenshot from 2023-03-15 18-26-55

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Review by artonge — APPROVED** [review]
Can you explain shortly why is a title and a description needed ?

**Comment by JuliaKirschenheuter** [comment]
> Can you explain shortly why is a title and a description needed ?

Of coarse. Well `title` was already there and was implemented as hints for user. But they are working only for users with a mouse. Additionally I've added a description for screen reader users. Actually such hint have to be accessible for keyboard users too (now it is not). But that would need much more UI changes as we have it how. 

https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/

We don't have LDAP integration (app) in out test instance and because of this i would leave it like this for now ;)

**Review by Pytal — APPROVED** [review]

**Review by blizzz — CHANGES_REQUESTED** [review]
one remark

**Review by blizzz — APPROVED** [review]

**Pull request merged**
