### PR TITLE
l10n: Add dot

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Comment by kesselb** [comment]
As reference: https://github.com/nextcloud/server/pull/22961#issuecomment-695779003

**Comment by nickvergessen** [comment]
Too late, thuraday was string freeze, so translators can finish their work for Nextcloud 20. Will have to wait until 20 is out.

**Review by jancborchardt — COMMENTED** [review]
The summary is more like a short tagline and not a sentence. It should not have a dot at the end.

**Comment by Valdnet** [comment]
@jancborchardt I changed the summary. Just not sure what to do as there will be other punctuations in the slogan. A sentence with a punctuation in the middle that does not end with a dot looks like an unfinished sentence.

We also need to think about adding dots to the end of the description in all applications.

**Comment by nickvergessen** [comment]
Diff is empty, so I close this?!

**Pull request closed without merging**
