### PR TITLE
Allow keyup enter in user status

### PR DESCRIPTION
**Pull request by nickvergessen**
* Resolves: # 

## Summary

* Use an ibus keyboard extension to e.g. write chinese/japanese/emoji characters
* Try to use them in user status, e.g. switch to emoji keyboard type `dog` and then enter to select the emoji
* While with emojis it's a luxury problem, with unicodes it's so disruptive rendering the feature almost useless. You have to type the status outside and copy paste it there, or open the modal again after each. and. every. character.

## Screenshots

Before | After
---|---
Modal closes | Modal stays open and cursor is behind the emoji
🚫 | grafik

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
/backport 5506229d7696a8db20da99a196eee373d07fe85e to stable25

**Review by PVince81 — APPROVED** [review]
works fine with fcitx (another input method like ibus): hitting enter while in the input method doesn't close the dialog any more

also hitting enter while in the input field still submits the dialog

:+1:

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Rah

**Comment by nickvergessen** [comment]
I'll take care after the release. Added a deck card to my todo

**Pull request merged**
