### PR TITLE
Refine files comments design

### PR DESCRIPTION
**Pull request by quentinguidee**
## Motivation

* Currently, the files > about > comments section margins/paddings are a little bit off (more vertical padding than horizontal, and comments are too much spread.

## This PR

* Fixes the paddings/margins ;
* Adds a box around the messages making it easier to understand the interface layout quickly ;
* This is more a side effect than something planned, but the input now have more space, so the text fits better in the input for some screen size.

## Screenshots

<details>
<summary>Before/after</summary>

Capture d’écran 2021-12-27 à 11 12 32

Capture d’écran 2021-12-27 à 11 13 01
</details>

<details>
<summary>Before/after (video)</summary>

https://user-images.githubusercontent.com/12123721/147463566-99459daf-ea22-4d07-84a8-4a34d479e1a2.mov

</details>

### CODE REVIEW

**Review by marcoambrosini — COMMENTED** [review]
I really like how it tidies up things, but I would loose the gray background and play with white space instead to separate the elements

**Comment by quentinguidee** [comment]
> I really like how it tidies up things, but I would loose the gray background and play with white space instead to separate the elements

Something like this?

<details>
<summary>Screenshot</summary>

image

</details>

**Comment by jancborchardt** [comment]
> I really like how it tidies up things, but I would loose the gray background and play with white space instead to separate the elements

Yup, agree with that. :)
Also, the indentation of the text is intentional (and as usually chat apps with avatars on the side do it), without that it looks quite crowded.

**Comment by quentinguidee** [comment]
> Also, the indentation of the text is intentional (and as usually chat apps with avatars on the side do it), without that it looks quite crowded. That way the comment text can also be closer to the line of author/timestamp, where it belongs to, instead of having almost the same distance to that as it has to the next comment.

Yeah I recognised that and tried to keep it, but I think we're facing a problem here. If the text is aligned with the username like many apps, I think the message should be placed higher ("in the header") :

image

I think it looks way better like this, but the problem is that NC want 44px height buttons, so the "…" will looks totally off.

**Comment by jancborchardt** [comment]
Exactly, that looks great @quentinguidee! :) (Only one thign: No all-caps in the timestamp as per our design ghideliens for readability.)
The 3-dot action could get enough padding and some negative margin to fix that?

@marcoambrosini how do you think we could account for this?

**Comment by marcoambrosini** [comment]
I actually think it makes a lot of sense to have the paragraph span the whole width in the sidebar, given the very limited width of the sidebar itself. I've been thinking about doing the same exact thing in talk's chat sidebar. If we do that there's going to be more space for the text anyway and we can afford a little bit more vertical whitespace if separation is still a concern

**Comment by jancborchardt** [comment]
> I actually think it makes a lot of sense to have the paragraph span the whole width in the sidebar, given the very limited width of the sidebar itself. I've been thinking about doing the same exact thing in talk's chat sidebar. If we do that there's going to be more space for the text anyway and we can afford a little bit more vertical whitespace if separation is still a concern

Not sure about that – I was actually going to say that it would be good if comments and Talk (chat in sidebar) simply uses the same component, but with the indentation, as it is in both Talk and Comments atm. The width is completely fine, it’s a similar form factor as e.g. for document comments in Office.

**Comment by jancborchardt** [comment]
@quentinguidee your last version looked really nice, is there a follow-up pull request or how come you closed this one? :)

**Comment by quentinguidee** [comment]
> @quentinguidee your last version looked really nice, is there a follow-up pull request or how come you closed this one? :)

That was not planned as I thought there was not a big interest around this PR, but I'll reopen one

**Pull request closed without merging**
