### PR TITLE
user_ldap: Add support for gidNumber 

### PR DESCRIPTION
**Pull request by blizzz**
https://github.com/nextcloud/server/pull/3218 by @Xuanwo with one adjustement due to changed method name.

Works for me. 

Another reviewer? @nextcloud/ldap

### CODE REVIEW

**Comment by blizzz** [comment]
👍 (since i cannot github-review self-opened PRs even if the code but one line isn't mine)

**Comment by Xuanwo** [comment]
OK, It's the same for me, hoping for the merge. :smile:

**Review by rullzer — APPROVED** [review]
Lets do this!

**Comment by blizzz** [comment]
One test failed, I pushed a fix.

Signoff fails for the merge commit → ignore.

**Pull request merged**
