### PR TITLE
Fix non LGC glyphs in avatars and txt file previews

### PR DESCRIPTION
**Pull request by danxuliu**
Previews

(Sorry for the wall of text, but hey, it has an image too!)

Generated avatars as well as text file previews are rendered using the `core/fonts/NotoSans-Regular.ttf` font. The file was the standard [hinted](https://en.wikipedia.org/wiki/Font_hinting) `NotoSans-Regular.ttf` file from https://www.google.com/get/noto/. However that file does not cover some non LGC (Latin, Greek, Cyrillic) scripts, like Arabic, Devanagari or Hebrew, to name a few.

Markdown file previews also use `core/fonts/NotoSans-Bold.ttf`, which is in the same situation as the regular one.

Due to limitations in the TTF format it is not possible to provide a single file for each style that includes all Noto fonts. However, it is possible to add more scripts to the standard `NotoSans-Regular.ttf` and `NotoSans-Bold.ttf` files (although no CJK (Chinese, Japanese, Korean) glyph can be included due to the aforementioned limitations).

This pull request replaces the standard files with an extended version created using the [Noto Tools](https://github.com/googlefonts/nototools). The build script (as well as a patch for the Noto Tools) is also included for reference and to be able to update the font files in the future if needed.

Besides that an OCC command was added to easily remove generated avatars and text files. This should ease updating the rendered texts in those instances that used scripts not supported before in the fonts.

Due to the additional scripts added the font files are now much larger, although this does not seem to increase the time spent rendering LGC scripts. Due to event handling by the CardDAV converter the command to reset the avatars also causes the avatars to be generated again, and in my tests running it with 1000 users did not increase the time to finish the command. Of course there are a lot of other operations executed in that case, it is not an isolated performance test of the rendering time, but at least it shows that any extra time needed to render the texts with a larger font is not noticeable in comparison with the rest of operations.

Note that the file for the bold style still contains less scripts than the regular one, as not all scripts supported by Noto have a bold weight.

### Right-to-left languages

libgd, the library used to render texts to images, [added support for complex text layouts in 2.3.0](https://github.com/libgd/libgd/commit/1dbccb737c5e9634085c9a3239fa1e0d0b988966). However, it is not enough to use libgd 2.3.0; it must be compiled with [libraqm](https://github.com/HOST-Oman/libraqm) support (as well as FreeType support). If libraqm is not available then right-to-left text will be rendered left-to-right, which is obviously wrong (specially because it seems that for example in the Arabic script [the glyph of a character changes depending on the following character](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub), see screenshot above).

See below for an example using Docker to rebuild libgd with libraqm support.

However, even if right-to-left text is properly rendered with libraqm please note that the text will still be left aligned in the previews. It would be necessary to [check if the characters of a paragraph are mostly left-to-right or right-to-left](https://stackoverflow.com/questions/13071717/how-to-identify-if-user-is-typing-in-rtl-or-ltr-language/41671177#41671177) (it seems that [PHP does not provide a convenient way to do that](https://stackoverflow.com/questions/20861663/detect-string-direction-from-string-in-php) :-( ) and then align the paragraph to one side or the other. That would be a simplification, [a proper implementation would be quite more involved](http://unicode.org/reports/tr9/)... but let's not forget that we are taking just about previews here ;-)

In any case, right-to-left text is not aligned to the right in the text editor from Nextcloud, so for the time being right-to-left text is also aligned to the left in previews to make it look similar (yes, it is a lame excuse, you do not need to point it out :-P ).

### Chinese, Japanese and Korean scripts

#4198 is NOT fixed by this pull request, as CJK glyphs are not properly rendered yet. As mentioned above this is due to technical limitations of the TrueType format. Specifically, the problem is that TrueType files can not contain more than 65535 glyphs, and the font for Chinese, Japanese and Korean scripts alone already includes 65535 glyphs.

The only possible way (as far as I know) to support CJK scripts along with other scripts (beyond basic LGC scripts, as they are included in the CJK font) would be to ship both the non-CJK and the CJK fonts and then use one or the other to render each paragraph depending on the characters in it.

Of course the fun would not stop there ;-) Turns out that [the same character may be rendered using a different glyph depending on the language of the text](https://github.com/adobe-fonts/locl-test) (although it seems that it happens too in other scripts, like Cyrillic when written in Bulgarian or in Russian). The Noto fonts support that, but [it must be supported too by the rendering engine](https://docs.microsoft.com/es-es/typography/opentype/spec/features_ko#locl) and, although I have not checked, I do not think that it is supported by libgd (I guess that the functions to render text would need a parameter to specify the locale).

For that reason [Noto provides the CJK fonts in four different variants](https://www.google.com/get/noto/help/cjk/); all the files include the same glyphs, but each one uses one language variant by default if the "locl" property is not specified. However, that would still require to ship the four different CJK font files (which are ~16 MiB each :-O ) and also switch between them when rendering depending on the locale.

And all that is even ignoring that those scripts (and others, like [Mongolian](https://en.wikipedia.org/wiki/Mongolian_script)) can be written vertically instead of horizontally :shrug:

So... if someone wants to implement all that please be my guest. It is far above my limited knowledge in this field :-)

### Example of how to rebuild libgd with libraqm support to test this pull request:
```
docker run --rm --interactive --tty --volume /home/dani/Nextcloud/nextcloud-server/:/var/www/html --volume /var/www/html/data --volume /var/www/html/config ubuntu:20.10 bash

# Enable deb-src repositories
sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list
apt-get update

# Prepare build system for packages
mkdir build
cd build
apt-get install -y build-essential fakeroot dpkg-dev

# Get sources of libgd3 and install build dependencies
apt-get source libgd3
apt-get build-dep -y libgd3
# Manual installation, it is not a dependency, but it is automatically used when
# building the package if found.
apt-get install -y libraqm-dev

# Rebuild the package (which now will use libraqm) and install it
cd libgd2-2.3.0
dpkg-buildpackage -rfakeroot -b
dpkg -i ../libgd3_2.3.0-2_amd64.deb

# Install standard PHP packages and Apache for Nextcloud
apt-get install -y php-intl php-cli php-curl php-pgsql php-zip php-xml php-mysql php-mbstring php-xdebug php-imagick php-apcu php-gd php-sqlite3 libapache2-mod-php

service apache2 restart

# Install Nextcloud
chown -R www-data /var/www/html/config /var/www/html/data
su --shell /bin/bash --login www-data
cd /var/www/html
php occ maintenance:install --admin-pass=admin
php occ config:system:set trusted_domains 0 --value={IP-OF-THE-CONTAINER}
```

### CODE REVIEW

**Comment by rullzer** [comment]
CI is not happy.
I'd also say lets not backport this. This has been this way since ages. I'd rather not risk breaking things on stable branches.

**Comment by danxuliu** [comment]
Rebased on master, guest avatar test file regenerated with the updated font, and psalm baseline updated based on the [ignored error](https://github.com/nextcloud/server/blob/8b6144aae763395d2dac9e72ee20e45b6cd4de2b/build/psalm-baseline.xml#L4511-L4515) for [BackgroundCleanupJob](https://github.com/nextcloud/server/blob/6c603e8e7d1ac52eeefdda939fa96a0c27b7c3da/lib/private/Preview/BackgroundCleanupJob.php#L120) that the command is based on.

**Comment by danxuliu** [comment]
_Somebody_  forgot to execute `composer run cs:fix` before the previous rebase :facepalm:

**Review by rullzer — APPROVED** [review]
sure...

**Review by juliusknorr — APPROVED** [review]
:elephant:

**Comment by PVince81** [comment]
if you had to rebuild the font with a patched version of Noto Tools, does it mean we are the first ever to meet this kind of issue ?
I was just wondering how other projects are dealing with this problem and am surprised that there is no library or tool that makes it work.

For CJK as far as I know, at least on desktop, there's "font substitution" logic built-in where if a glyph is missing in one font it will pick it in another. This makes it possible to mix different fonts. (I remember that Linux desktops had a bug where sometimes font substitution mixed Japanese with Chinese glyphs which rendered those with a different font style and made it ugly, haven't seen this issue since).

**Pull request merged**
