### PR TITLE
Reset bruteforce on token refresh OAuth

### PR DESCRIPTION
**Pull request by rullzer**
When using atoken obtained via OAuth the token expires. Resulting in
brute force attempts hitting the requesting IP.

This resets the brute force attempts for that UID on a valid refresh of
the token.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by Dagefoerde — APPROVED** [review]
I suppose this mitigates the current problem with the brute force protection. #12131 still required as it would solve the actual problem.

**Review by ChristophWurst — APPROVED** [review]
Looks good and changes make sense!

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by MorrisJobke** [comment]
Unit tests fail.

**Pull request merged**
