### PR TITLE
perf(files): Adjust default chunk size for chunked upload to 100MiB

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

Step 1 of https://github.com/nextcloud/server/issues/47682

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Comment by joshtrichards** [comment]
If we do this at 100 (rather just under it, like 99 I suppose?), it's going to hit installations using the Web client via Cloudflare immediately with breakage. This already happened with the Desktop client and is why we have nextcloud/desktop#4278 as a top-3 most reacted to bug at the moment (with solutions proposed such as nextcloud/desktop#5813 and nextcloud/desktop#4826).

At a minimum, we need to document this as a breaking change IMO because people are going to suddenly have problems with our Web client too and therefore will need to figure out how to change the `max_chunk_size`.

Even if documented, we're going to be spending time fielding false bug reports (but legitimate feedback IMO) + hear about it over and over again on the forum.

I want to increase this value too, but we need to decide whether it's acceptable to deal with the headaches introduced before we have the dynamic chunk size stuff in place. Or choose a choose a pragmatic intermediate path I guess like going with an odd number like 99.

I don't like accommodating for an arbitrary outside vendor, but we can't avoid reality. The two biggest external limits are:

- Cloudflare (must be <100MiB) <-- impossible for user to adjust via CF
- Apache (must be <1GiB) <-- possible to adjust and we document it as of nextcloud/documentation#10989

**Comment by provokateurin** [comment]
@joshtrichards Thanks for the hint, so 99 would actually be the limit we should chose to avoid problems? That would at least make sense if Cloudflare limits to 100 and the little overhead each HTTP request has.

**Comment by joshtrichards** [comment]
I just went back and reviewed things again more closely. 100 may be fine actually. The 99 was in my brain to be conservative. :) I don't see any substantial evidence we had any problems until nextcloud/desktop#3600 was merged and released via 3.4.x (which bumped 100->1000 so I guess all was good right at 100).

**Comment by provokateurin** [comment]
Yeah I also just found https://developers.cloudflare.com/workers/platform/limits/#request-limits and it says that the body size is limited to 100MB and not the overall size. I'm not sure if they really mean MB or MiB, as with the former the actual limit in MiB would be around 95.37MiB.
If we find problems later we can fix them, hopefully that happens before final releases (but there is plenty of time until 31).

**Review by joshtrichards — APPROVED** [review]

**Comment by susnux** [comment]
@provokateurin how did this influence performance?
Because this can lead to a bad default UX, 100MB is rather huge. Width average upstream it takes a minute per chunk.
This is a rather long time and prone to failed tries, so e.g. from mobile network if that chunk failed you need to wait another minute for the retry.

If the performance improvement is not significant I would recommend to reduce this back to something like 25MiB or 50MiB and let administrators increase the value if they know their network conditions are good. But for the majority I think we need to keep slow network in mind.

**Comment by provokateurin** [comment]
@susnux see the benchmark results from https://github.com/nextcloud/server/issues/47682

**Pull request merged**
