### PR TITLE
Fix login as non ldap user

### PR DESCRIPTION
**Pull request by icewind1991**
cc @blizzz

### CODE REVIEW

**Comment by MorrisJobke** [comment]
The login works for me even without this change. Could you please comment what this change will address?

**Comment by icewind1991** [comment]
I'm not sure about the exact reason but when trying to make a dav request for a non ldap user (while having ldap users configured) `$user` ends up being null which currently breaks login

**Comment by MorrisJobke** [comment]
@blizzz Any comment on this?

**Comment by blizzz** [comment]
I am bewildered, need to verify.

**Comment by blizzz** [comment]
@icewind1991 I cannot verify the issue

```
$ cadaver http://nc.zara/master/remote.php/webdav
Authentication required for Nextcloud on server `nc.zara':
Username: master
Password: 
dav:/master/remote.php/webdav/> ls
Listing collection `/master/remote.php/webdav/': succeeded.
        welcome.txt                          164  Aug 19 12:26
```

do you have detailed reproduction steps?

**Comment by icewind1991** [comment]
No, it probably depends on the specific ldap setup but I don't have enough ldap knowledge to know why

**Comment by blizzz** [comment]
What might happened here is that the provided loginname resulted into an LDAP result when looking up a user for the provided loginname. Then there are only few cases were it could fail, e.g. there is no displayname set on LDAP for that user (should result in a log line like ``No or empty name for $dn``) or a new mapping would not succeed (includes trying alternate names), would result in a log line like ``Could not create unique name for $dn``.

But because we do not check for null in that case it does not gracefully deny login for that LDAP user, but ends up with an error. 

The check could be reverted to only look for ``OCA\User_LDAP\User`` resulting in just one condition, the effect would be the same however. Typically, the result would be a user one so changing it accordingly might be a bit of micro optimization.

**Comment by MorrisJobke** [comment]
@icewind1991 Do you still have an instance where this is reproducible? Otherwise I would close this, because we can't reproduce it locally. Also fixing symptoms is not that good.

**Comment by MorrisJobke** [comment]
No response yet and this doesn't seem to be reproucible -> closing

**Comment by MorrisJobke** [comment]
@icewind1991 feel free to reopen once you know more about this issue 😉

**Pull request closed without merging**
