### PR TITLE
Fix duplicate sentence in 'Reasons to use Nextcloud.pdf'

### PR DESCRIPTION
**Pull request by jancborchardt**
Thanks @jakobroehrl for the note and Marija for the fix! 

On Page 10 this sentence was doubled: "Create any number of private or shared Kanban-style task boards"

Please review @jospoortvliet @rullzer @karlitschek 

Also, is it possible that we put this file next to the "welcome.txt" of the example files in the empty dev instance as well? This will also spread the file further to people who are already more excited about Nextcloud so they can use it to spread it, which is kind of the idea?

### CODE REVIEW

**Comment by karlitschek** [comment]
Looks good.
Sure, we can also put it into the example_files files. Good idea!

**Comment by rullzer** [comment]
> Also, is it possible that we put this file next to the "welcome.txt" of the example files in the empty dev instance as well? This will also spread the file further to people who are already more excited about Nextcloud so they can use it to spread it, which is kind of the idea?

my bet is that makes a lot of tests do boom. So that would need fixing.
But this will be part of the skeleton files. So people that use the demo will see it. I really doubt a lot of people that never tried nextcloud directly start with deploying from git. ;)

**Comment by jancborchardt** [comment]
> I really doubt a lot of people that never tried nextcloud directly start with deploying from git. ;)

The idea was more that _if_ you are as excited about Nextcloud already that you set up a local development environment, having this "Reasons to use Nextcloud.pdf" file directly in the dev instance as well might give you the nudge to share that further. Possibly that person is a sysadmin or technical contact in some company and can share it with decision makers.

**Comment by rullzer** [comment]
So my guess was right. It does make a lot of tests do boom.

I vote to just get this in. People that are excited don't just setup a dev environment. They also have a full setup running. So they will see the file.

**Pull request merged**
