### PR TITLE
patch for avatar getAvatarText()

### PR DESCRIPTION
**Pull request by tqjason**
if enable user_ldap and set '2nd User Display Name Field'
so getDisplayName() would be like 'john (john@some.com)'
getAvatarText() will return firstTwoLetters as 'j('
so have to remove email.
but if avatar shown as txt instead of img, it still be 'j('
I didn't find how to fix it.

### CODE REVIEW

**Comment by kesselb** [comment]
I guess we need a method for each user backend to return a appropriate text to generate the avatar. 

This patch fixes the symptoms but not the actual problem.

cc @blizzz @rullzer

**Comment by blizzz** [comment]
> I guess we need a method for each user backend to return a appropriate text to generate the avatar.
> 
> This patch fixes the symptoms but not the actual problem.
> 
> cc @blizzz @rullzer

The way to go then would be for the user backends to optionally implement an getInitials method, and fall back to the current method.

LDAP could also query initials, otherwise … it will become complicated :) Because differnt cultures have different sets of names. Could just go for the first two first letters or the first and last first latter of available names in the display name.

The Avatar would need to have access to the `IUser`, not sure whether this is currently the case or whether the is some abstraction on top.

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
I agree with https://github.com/nextcloud/server/pull/21369#issuecomment-643813728 on this one. It's a more complex path to take but we should indeed fix this properly instead of trying to guess and catch a few of the edge cases.

**Comment by ChristophWurst** [comment]
But @tqjason thanks a lot for looking into this. Would you like to work on the proposed fix? If so we can give you some pointers to get started :)

**Pull request closed without merging**
