### PR TITLE
refactor chunked assembly stream 

### PR DESCRIPTION
**Pull request by icewind1991**
For when doing chunked uploads using primary object storage

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by blizzz** [comment]
Since it's an op at the heart… no tests?

**Comment by MorrisJobke** [comment]
@icewind1991 Ping

**Comment by icewind1991** [comment]
did additional refactoring to simplify the code, the code is covered by existing tests

**Comment by blizzz** [comment]
Tests are failing

**Review by rullzer — APPROVED** [review]
Sure.

* We do have intergration tests that handle chunking as well
* We should maybe setup intergration tests against ObjectStore as well then?

**Comment by MorrisJobke** [comment]
> We should maybe setup intergration tests against ObjectStore as well then?

They are just failing right now due to the drone update - so they are commented out 🙈

**Comment by MorrisJobke** [comment]
@icewind1991 Ping for the backport

**Comment by MorrisJobke** [comment]
@icewind1991 Ping

**Pull request merged**
