### PR TITLE
ownCloud -> Nextcloud

### PR DESCRIPTION
**Pull request by enoch85**
Potential fix for https://github.com/nextcloud/server/issues/633

### CODE REVIEW

**Comment by enoch85** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
:+1: Looks good to me.

**Comment by enoch85** [comment]
@jancborchardt @mar1u5 Need 2 more :+1: :)

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
@enoch85 Could you create the backport to stable9 and stable10?

**Pull request merged**
