### PR TITLE
[stable30] chore: add .git-blame-ignore-revs

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: "fatal: could not open object name list: .git-blame-ignore-revs"

## Summary

If you enabled `git config blame.ignoreRevsFile .git-blame-ignore-revs`  and checkout an older branch without the file an error "fatal: could not open object name list: .git-blame-ignore-revs" is shown.  

There's no way to tell git that a missing file is okay; therefore we need an empty file.

## TODO

- [ ] CI
- [ ] Review

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Comment by provokateurin** [comment]
Maybe also backport it to even older stable branches?

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
