### PR TITLE
Add core/js/dist/ to l10nignore

### PR DESCRIPTION
**Pull request by juliusknorr**
As discussed, this should fix the transifex sync

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by georgehrke — APPROVED** [review]

**Review by tobiasKaminsky — COMMENTED** [review]
/me is crossing fingers

**Comment by georgehrke** [comment]
do we really need to backport?
We don't backport translations anyway, do we?

**Comment by skjnldsv** [comment]
@georgehrke is it not broken on 16 as well?

**Comment by juliushaertl** [comment]
Iirc there was also some mechanism to backport translation fixes.

**Comment by MorrisJobke** [comment]
> We don't backport translations anyway, do we?

We backport translations. We fetch translations from all branches and then put them on all branches.

**Pull request merged**
