### PR TITLE
Polishing fixes

### PR DESCRIPTION
**Pull request by skjnldsv**
- Removed the sidebar animations causing some hidden entries to be still focusable on keyboard navigation
- Fixed the grid view and default for the filepicker
- Fixed the filepicker grid view design on the files list 
- Fixed the edit entries buttons in the appnavigation (big round borders)

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by ChristophWurst — APPROVED** [review]
Not tested and don't know if works but code looks good :+1:

**Comment by ChristophWurst** [comment]
>     * Removed the sidebar animations causing some hidden entries to be still focusable on keyboard navigation

Tested this with Mail and works :+1:

**Pull request merged**
