### PR TITLE
Fix for issue #13319: load oc-backbone-webdav before loading versions app

### PR DESCRIPTION
**Pull request by felixn**
See issue #13319

### CODE REVIEW

**Comment by felixn** [comment]
Inspired by the comments app:
https://github.com/nextcloud/server/blob/b0c0bf84f6219509900855ee99d7565809016e61/apps/comments/lib/AppInfo/Application.php#L64-L65

**Review by rullzer — APPROVED** [review]
Yes good point!

**Review by ChristophWurst — APPROVED** [review]
Makes sense :+1:

**Comment by ChristophWurst** [comment]
@rullzer backport?

**Comment by rullzer** [comment]
I think this only affects 15.
In 16 this si alays bundled. And before 15 doesn't use the webdav yet I think

**Comment by juliushaertl** [comment]
Yes, just tested and works fine with 16.

**Pull request merged**
