### PR TITLE
Bump doctrine/dbal from 2.9.2 to 2.10.2

### PR DESCRIPTION
**Pull request by ChristophWurst**
For https://github.com/nextcloud/server/issues/16876

After ages this will pull in my upstream patch https://github.com/doctrine/dbal/pull/3843

- [x] Requires https://github.com/nextcloud/3rdparty/pull/436

### CODE REVIEW

**Review by yarons — APPROVED** [review]
I don't really know what to do but I approve.

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
CI says no https://drone.nextcloud.com/nextcloud/server/29482/10/4

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/3rdparty/pull/452

**Comment by ChristophWurst** [comment]
Fixed. Thanks a lot.

**Comment by nickvergessen** [comment]
Fixed

**Comment by ChristophWurst** [comment]
CI is not fully done but looks promising :pray:

**Pull request merged**
