### PR TITLE
Allow to log queries to db, ldap and redis

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by acsfer** [comment]
Maybe also add and document `query_log_file` in `config.sample.php` file?

**Comment by acsfer** [comment]
Also, I don't know if adding an extra https://www.php.net/manual/en/function.is-writable.php to the `query_log` could avoid any errors in case the file is set to a non-writable file location... 🤔

**Review by solracsf — APPROVED** [review]

**Comment by come-nc** [comment]
I intended to do something like this as I was annoyed that LDAP queries were not logged even in debug level.
What is the rationale behind logging to a file and not through the logging system?

For LDAP queries we also need to log errors, in processLDAPError, I would say even the ignored error codes should be logged to help debugging.

**Pull request merged**
