### PR TITLE
Convert more columns to bigint

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]
Code looks good, tested and works 👍 

We might want to consider renaming `occ db:convert-filecache-bigint` in the future, since it's no longer only about the file-cache

**Comment by georgehrke** [comment]
@rullzer Backport?

**Review by ChristophWurst — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
