### PR TITLE
fix: no secondary button for now-> use primary and tertiary instead.

### PR DESCRIPTION
**Pull request by vanpertsch**
buttons changed to primary
https://github.com/nextcloud/server/pull/31340

buttons changed to tertiary
[add new button component #31397](https://github.com/nextcloud/server/pull/31397)

Signed-off-by: Vanessa Pertsch <vanessa.pertsch@nextcloud.com>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Comment by marcoambrosini** [comment]
@vanpertsch should we keep an issue with a list of all the buttons to be reverted to secondary when that's available?

**Comment by vanpertsch** [comment]
not longer needed

https://github.com/nextcloud/nextcloud-vue/pull/2562

**Pull request closed without merging**
