### PR TITLE
Add regex to match Gnome and KDE calendar user-agents, for propagating calendar subscriptions

### PR DESCRIPTION
**Pull request by msrn**
Refers: #17754 
This pull requests adds Gnome Calendar/Evolution and KDE PIM/Akonadi calendars to the list of user-agents in WebCalCaching -plugin, and exposes subscribed calendars to these calendar clients.

User-agent of Gnome Calendar/Evolution
`Evolution/3.40.3`

KDE PIM/Akonadi user-agent
`Mozilla/5.0 (X11; Linux x86_64) KIO/5.86 akonadi_davgroupware_resource_1/5.18.2 (21.08.2)`

### CODE REVIEW

**Review by tcitworld — COMMENTED** [review]
As per the comment above « calendar user agents that do not support subscriptions on their own », this doesn't look very right to me, as Evolution supports subscriptions, it just lacks subscription discovery for automatic configuration. We intentionally don't expose cached subscribed calendars for every calendar user agent because of performance reasons, it will be far better if every client lists the subscriptions and configures them manually (as of today, I think only DAVx⁵ does it properly).

I thought that KOrganizer or Kalendar supported adding manual calendar subscriptions, but it doesn't seem so, is that correct @CarlSchwan?

So KIO would be acceptable but instead of adding Evolution as well, I'd file a bug against https://gitlab.gnome.org/GNOME/evolution/-/issues to ask for subscriptions discovery.

For reference, this is the issue discussing the topic https://github.com/nextcloud/server/issues/17754

**Comment by CarlSchwan** [comment]
Yeah we don't support calendar subscription in Kalendar. Currently, we only support fetching a remote file one time when configuring the resource but we don't monitor for change. That wouldn't be too complex to implement I think but #notEnoughtTimeTooMuchTodo I created https://invent.kde.org/pim/kalendar/-/issues/206 to keep this in mind

**Comment by JackRoublard** [comment]
> We intentionally don't expose cached subscribed calendars for every calendar user agent because of performance reasons, it will be far better if every client lists the subscriptions and configures them manually (as of today, I think only DAVx⁵ does it properly).

I understand the performance concerns, however as mentioned in #1497 there are also privacy concerns supporting the decision of adding even clients that **do** support subscriptions - not to mention that for those users who turned to self-hosting especially for the sake of being as independent and self-contained as possible, this solution just makes sense.

Why not just leave this tradeoff for every nextcloud admin to figure out ? The solution could be as basic as checkboxes in the admin settings UI.

**Comment by msrn** [comment]
💤

**Comment by Vivida1** [comment]
Would be nice, or at least give the option to manually enable user-agents.

**Comment by msrn** [comment]
> > (as of today, I think only DAVx⁵ does it properly).
> 
> I think it is going to stay that way for a while. Looks like clients really don't care about adding this feature.
> 
> > as Evolution supports subscriptions, it just lacks subscription discovery for automatic configuration
> 
> Window calendar also supports subscriptions, but lacks the Nextcloud specific subscription discovery. [PR ](https://github.com/nextcloud/server/pull/27488)regarding for that was accepted but not for these clients, why?

Would still be nice to have reply to latter question.

**Comment by skjnldsv** [comment]
Closing this pull request due to lack of recent activity and updates. We appreciate your contribution and encourage you to reopen or provide further updates if necessary. :relaxed: 
Our aim is to keep the project moving forward with active collaboration. Thank you for your understanding and continued support! :pray:

**Comment by skjnldsv** [comment]
I was a bit too fast, sorry @msrn :)

> Window calendar also supports subscriptions, but lacks the Nextcloud specific subscription discovery. https://github.com/nextcloud/server/pull/27488regarding for that was accepted but not for these clients, why?

I think it's a valid question. I see no reason we would accept one and not the others. :+1:

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
@msrn you don't have to keep rebasing, but it would be nice if you could sign-off your commits and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) syntax like: `feat(dav): add regex to match Gnome and KDE calendar user-agents `

**Comment by msrn** [comment]
> @msrn you don't have to keep rebasing, but it would be nice if you could sign-off your commits and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) syntax like: `feat(dav): add regex to match Gnome and KDE calendar user-agents `

Thanks, I was rebasing as some of the tests are not passing and thought that might be the reason. Will force push renamed commit in a bit.

**Comment by skjnldsv** [comment]
Rebase fail?
@msrn can you open a new PR maybe?

**Pull request closed without merging**
