### PR TITLE
Make rename file tooltip error text change

### PR DESCRIPTION
**Pull request by phil-davis**
Issue: #5001 

Problem:
1) Create 2 files in a folder
2) Rename one file, first blank out the whole file name and file type. "File name cannot be empty" is displayed in the tooltip -good.
3) Now type a name that exactly matches the name of the other file in the folder. The tooltip displays again, but it still says "File name cannot be empty".

After this fix, at step (3) the tooltip pops up and says "file.type already exists"
and as you blank out the filename, put a single "." etc, the tooltip text changes.

### CODE REVIEW

**Comment by phil-davis** [comment]
Same problem also when typing a file name into the "New text file" file name box. Fixed by 2nd commit above.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@karlitschek I would propose to backport this at least to stable12.

**Comment by MorrisJobke** [comment]
Could I ask you to add the sign-off to your commits? See https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work for details.

**Comment by karlitschek** [comment]
nice. backport makes sense

**Comment by phil-davis** [comment]
These edits were so easy that I did them online. I wonder how I sign an existing commit? I guess I can pull the branch back to my local git and somehow add signing to the commits, or just start again "properly" from local git.

**Comment by MorrisJobke** [comment]
> I will remember in future that "easy editing" in GitHub online is not the way to go!

You could, but you need to add the text to the commit message yourself ;)

**Review by ChristophWurst — APPROVED** [review]
Makes sense. Thanks!

**Comment by phil-davis** [comment]
Now it just needs the CI to actually work. Looks like that fails for everybody recently.

**Comment by MorrisJobke** [comment]
> Now it just needs the CI to actually work. Looks like that fails for everybody recently.

A fix for this was just merged. And the timeouts are still weird - we suspect that the machine is overloaded. New CI hardware should be in soon. So if a timeout: ignore for now 🙈 Sorry for this.

**Comment by MorrisJobke** [comment]
CI looks okay.

**Comment by MorrisJobke** [comment]
@phil-davis Could I ask you to create a PR against stable12 for the backport? Thanks

**Comment by MorrisJobke** [comment]
And thanks for this PR :) Feel free to join our IRC #nextcloud-dev on freenode and maybe also checkout the other issues. The "starter issue" labeled ones are maybe a good point to start with :) Thanks

**Pull request merged**
