### PR TITLE
[stabl26] LDAP: Increase profile picture limit to 512

### PR DESCRIPTION
**Pull request by marcelklehr**
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
Looks like a reasonable change :+1:

**Comment by blizzz** [comment]
first master, then backports?

**Comment by marcelklehr** [comment]
If you insist. The customer we needed a patch for was on 26, so this is how it went :shrug:

**Comment by blizzz** [comment]
> If you insist. The customer we needed a patch for was on 26, so this is how it went 🤷

You know, it ends up too often that stuff is then merged in older versions, but does not make its way up. A stitch in time saves nine! ;)

**Pull request closed without merging**
