### PR TITLE
Register the app management in the normal way

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Comment by jancborchardt** [comment]
Just one thing, as this now leads to a bit strange issue: When you have 9 apps enabled, there are 8 being shown in the header directly, plus the »more« button. But the »more« menu just shows one app, which makes no sense. :)

There should be a maximum of 8 apps, and if there’s more, there should be 7 shown, the more-menu should be shown on the 8th position, and the additional two apps should be inside the more-menu.

cc @juliushaertl  :)

**Comment by nickvergessen** [comment]
Fixed @jancborchardt

**Comment by BernhardPosselt** [comment]
I'm late to the party, just a quick question: how are translations handled? Just add all languages in the navigation entry?

Another thing: instead of using \<navigations>\<navigation> what about naming the tags \<navigation>\<entry>. ?

**Comment by nickvergessen** [comment]
> how are translations handled? Just add all languages in the navigation entry?

```php
...
$l = $this->l10nFac->get($app);
...
'name' => $l->t($nav['name']),
...
```

So they are translated automatically. with `<name>English name</name>`

> instead of using `<navigations><navigation>` what about naming the tags `<navigation><entry>`.

Any real-world reason why we should go away from ownclouds definition?

**Comment by MorrisJobke** [comment]
I fixed this, @jancborchardt 

> Oh and btw @nickvergessen @schiessle I guess someone of you can help me with placing it correctly – I actually want the »Apps« entry between »Admin« and »Users« in the menu. Currently it’s just between Help and Log out which is strange.

bildschirmfoto 2017-03-26 um 14 29 51

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by BernhardPosselt** [comment]
> Any real-world reason why we should go away from ownclouds definition?

Oh, didn't know that this was a cherry-pick from ownCloud, I thought we were implementing this ourselves :)

Thanks for the answer!

**Review by MorrisJobke — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]

**Pull request merged**
