### PR TITLE
Make files drop more visible

### PR DESCRIPTION
**Pull request by rullzer**
Implement the suggestions from #2207

Somebody with CSS magic should make it look not ugly. @nextcloud/designers 

radio

### CODE REVIEW

**Comment by blizzz** [comment]
> Somebody with CSS magic should make it look not ugly. @nextcloud/designers

→ Rather Developing state then?

**Comment by MorrisJobke** [comment]
Rebased on current master

**Comment by rullzer** [comment]
@jancborchardt care to take a look? Or should I close this?

**Comment by jancborchardt** [comment]
Yep I will check. :) Can you rebase on master and fix the conflict?

**Comment by rullzer** [comment]
@jancborchardt done

**Comment by MorrisJobke** [comment]
@jancborchardt Ping

**Comment by rullzer** [comment]
So no action here... closing... please reopen if somebody wants to work on it still.

**Comment by Espina2** [comment]
| show here how to improve this feature.

https://github.com/nextcloud/server/issues/4273

**Comment by MorrisJobke** [comment]
> | show here how to improve this feature.

The problem here is, that we need some CSS help from @jancborchardt but he is ignoring this ticket somehow. :/

**Comment by Espina2** [comment]
I can help with that, if hou help me setup a dev enviroment on my machine.

**Comment by eppfel** [comment]
@Espina2 This might work:
> git clone git@github.com:nextcloud/server.git
> cd server
> git submodule update --init
> php -S localhost:8080
Then you should be able do run the setup in the browser... 

Maybe you need to update php.

I have unfinished / partly obsolete documentation for more: https://pad.epp.cloud/s/B1vqv1fMe

**Pull request closed without merging**
