### PR TITLE
[stable24] Fix size calculation on copying the skeleton files

### PR DESCRIPTION
**Pull request by juliusknorr**
Backport of #34834

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Review by icewind1991 — APPROVED** [review]

**Comment by nickvergessen** [comment]
This breaks skeleton file creation for guest app users.

Easily testable with running talks integration test: [features/conversation/find-listed.feature:22](https://drone.nextcloud.com/nextcloud/spreed/10662/4/4)

```
git bisect start
# status: waiting for both good and bad commits
# good: [6b5a8eec4cd044d74dae9b0add4ccaf812abbaae] [tx-robot] updated from transifex
git bisect good 6b5a8eec4cd044d74dae9b0add4ccaf812abbaae
# status: waiting for bad commit, 1 good commit known
# bad: [5643a62fcc44695853d2be9a5d35c981cc209ebb] [tx-robot] updated from transifex
git bisect bad 5643a62fcc44695853d2be9a5d35c981cc209ebb
# good: [fd452e51c15d53b20cbfdf03cc45eeeab1afd205] Merge pull request #35039 from nextcloud/backport/32211/stable24
git bisect good fd452e51c15d53b20cbfdf03cc45eeeab1afd205
# bad: [7b7ae291c5ca1bbf9ade47a43c0d4b503432c1bf] Merge pull request #35101 from nextcloud/backport/35077/stable24
git bisect bad 7b7ae291c5ca1bbf9ade47a43c0d4b503432c1bf
# bad: [af87f280d038df4f75a3de08f9b0e85278da593d] Merge pull request #35049 from nextcloud/backport/34834/stable24
git bisect bad af87f280d038df4f75a3de08f9b0e85278da593d
# good: [97f2518b9e22318702998c44133ecbc42444d9d2] Merge pull request #35065 from nextcloud/backport/35063/stable24
git bisect good 97f2518b9e22318702998c44133ecbc42444d9d2
# bad: [ed6ef37dd18881f239aec62e060c241352e1d2a8] Use proper storage method for writing skeleton files
git bisect bad ed6ef37dd18881f239aec62e060c241352e1d2a8
# first bad commit: [ed6ef37dd18881f239aec62e060c241352e1d2a8] Use proper storage method for writing skeleton files
```

**Comment by nickvergessen** [comment]
```json
{
  "Exception": "OCP\\Files\\GenericFileException",
  "Message": "file_put_contents failed",
  "Code": 0,
  "Trace": [
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/private/legacy/OC_Util.php",
      "line": 257,
      "function": "putContent",
      "class": "OC\\Files\\Node\\File",
      "type": "->"
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/private/legacy/OC_Util.php",
      "line": 216,
      "function": "copyr",
      "class": "OC_Util",
      "type": "::"
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/private/User/Session.php",
      "line": 553,
      "function": "copySkeleton",
      "class": "OC_Util",
      "type": "::"
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/private/User/Session.php",
      "line": 403,
      "function": "prepareUserLogin",
      "class": "OC\\User\\Session",
      "type": "->"
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/private/User/Session.php",
      "line": 616,
      "function": "completeLogin",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/private/User/Session.php",
      "line": 355,
      "function": "loginWithPassword",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/private/User/Session.php",
      "line": 450,
      "function": "login",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/private/User/Session.php",
      "line": 575,
      "function": "logClientIn",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/lib/base.php",
      "line": 1081,
      "function": "tryBasicAuthLogin",
      "class": "OC\\User\\Session",
      "type": "->"
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/ocs/v1.php",
      "line": 59,
      "function": "handleLogin",
      "class": "OC",
      "type": "::"
    },
    {
      "file": "/home/nickv/Nextcloud/24/server/ocs/v2.php",
      "line": 23,
      "args": [
        "/home/nickv/Nextcloud/24/server/ocs/v1.php"
      ],
      "function": "require_once"
    }
  ],
  "File": "/home/nickv/Nextcloud/24/server/lib/private/Files/Node/File.php",
  "Line": 72,
  "CustomMessage": "--"
}
```

**Comment by juliushaertl** [comment]
Strange, I've tried to debug this a bit but could not figure out why 24 would behave different yet.

Overall it seems that the guests app on 24 does not trigger a failure of the newFile call. On master this properly throws a NotPermittedException which is catched and expected in the copy skeleton.

To be continued.

Small test script to trigger the issue directly:

```php
<?php
// curl http://stable24.dev.local/playground/test.php -H 'Cookie: XDEBUG_SESSION=PHPSTORM' -u "guest@guest.com:guest@guest.com"
try {
	require_once __DIR__ . '/../lib/versioncheck.php';
	require_once __DIR__ . '/../lib/base.php';

	// v1.php
	OC_App::loadApps(['session']);
	OC_App::loadApps(['authentication']);
	OC_App::loadApps();

	if (!\OC::$server->getUserSession()->isLoggedIn()) {
		OC::handleLogin(\OC::$server->getRequest());
	}

	$userFolder = \OC::$server->getUserFolder('guest@guest.com');
	OC_Util::copySkeleton('guest@guest.com', $userFolder);
} catch (\Exception $e) {
	echo '<pre>';
	echo get_class($e) . PHP_EOL;
	echo $e->getMessage() . PHP_EOL;
	echo $e->getTraceAsString();
}
```

**Comment by juliushaertl** [comment]
Filed https://github.com/nextcloud/server/issues/35248 for follow up investigations

**Pull request merged**
