### PR TITLE
Add typed create user events

### PR DESCRIPTION
**Pull request by ChristophWurst**
Discovered while working on https://github.com/nextcloud/mail/pull/2259.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
I like it. very elegant

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Rebased and updateded autoloader as it had conflicts

**Comment by rullzer** [comment]
Failing tests...

**Comment by rullzer** [comment]
Tests do :boom:

**Comment by MorrisJobke** [comment]
ref #14552

**Pull request merged**
