### PR TITLE
Design fixes for recommended apps

### LINKED ISSUE #18363: Dedicated app install page polishing
From #18233 by @jancborchardt 

-----

I will only have time to look into this in the next days as I’ll be traveling. If someone else wants to have a quick look (a lot of these things look nice already on the 2FA choice page for example, maybe patterns to get from there):
- [ ] App title should be white (same as text color)
- [ ] App icon should be white (same as text color)
- [ ] App icon is a bit large in comparison to the text.
- [ ] App description text should be left-aligned
- [ ] Spacing between app title and app description is too much – could be halved
- [ ] Error should just be bold (in a `<strong>` element) instead of in a `class="error"` container
- [ ] The width of the dialog should be fixed to what we had before. See **Container on update screen is too wide #17556**
- [ ] The "Go back" link is a bit confusing? Should it be "Cancel"?

### PR DESCRIPTION
**Pull request by jancborchardt**
### Before
recommended apps before

### After
- White icons and text
- Some spacing fixes
- Made icons smaller
- Fix all of https://github.com/nextcloud/server/issues/18363

recommended apps after

Fix https://github.com/nextcloud/server/issues/18363, please review @ChristophWurst @rullzer @juliushaertl

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Screenshots looks good

Bundle was not updated

**Comment by jancborchardt** [comment]
@rullzer from what I can tell, the Drone failures are unrelated?

**Comment by jancborchardt** [comment]
Also thanks to @gary-kim for the in-person review! :) Feel free to check the code if you like

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
