### PR TITLE
dashboard should not have a scrollbar by default

### LINKED ISSUE #33868: dashboard app has an outer scrolling but shouldn't have one
See in blue on the right
image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/33868

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by andyxheli** [comment]
Hey guy this is still present on beta 6. Should i open a new ticket ? 

image

**Comment by szaimen** [comment]
> or is it being implemented in #33993

Yes

**Comment by andyxheli** [comment]
Thanks @szaimen sorry to bother.

**Pull request merged**
