### PR TITLE
Don't call session_start() when PHP session is still or already open.

### LINKED ISSUE #31248: SessionInternal::clear() erroneously calls start_session() when session is still open
`SessionInternal::clear()` does strange things:

https://github.com/nextcloud/server/blob/f5d1365bbd32fdcf2084eb2ad727a574529898d0/lib/private/Session/Internal.php#L103-L108

```
Error: session_start(): Ignoring session_start() because a session is already active at /var/www/localhost/htdocs/nextcloud-git/lib/private/Session/Internal.php#208 
```

1. session_unset() -- ok, destroys all values
2. regenerateId() -- ok, generate a new session id
3. start_session() -- oops. But the session is still open.

So either the start_session is  superfluous and can be omitted -- at least in current versions of php -- or there is missing something like a `session_destroy()` (but then regenerate_id() could be omitted?) or a `session_write_close()` which would write the (now empty) session file to disk.

### PR DESCRIPTION
**Pull request by rotdrop**
Signed-off-by: Claus-Justus Heine <himself@claus-justus-heine.de>

See #31248

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]
Makes sense 👍

**Comment by PVince81** [comment]
https://github.com/nextcloud/server/pull/28695 was an older alternative, not sure which is best

**Comment by come-nc** [comment]
> #28695 was an older alternative, not sure which is best

No idea :confused:

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
`session_write_close` should basically break `@UseSession` annotation?

**Comment by juliushaertl** [comment]
> session_write_close should basically break @UseSession annotation?

No as the session_start would reopen it for writing.

**Comment by solracsf** [comment]
> #28695 was an older alternative, not sure which is best
Both perform a similar goal, this on seems more clean.

**Review by solracsf — APPROVED** [review]

**Comment by solracsf** [comment]
Is this still a thing after https://github.com/nextcloud/server/commit/9e1d4312555ddc1009450b1f6b7078ae35790593?
Cc @juliushaertl

**Comment by juliushaertl** [comment]
> Is this still a thing after [9e1d431](https://github.com/nextcloud/server/commit/9e1d4312555ddc1009450b1f6b7078ae35790593)?
> Cc @juliushaertl

Yes, that linked commit only reduced one common case where a session would be opened for writing. This might still occur later in the code path.

**Comment by juliushaertl** [comment]
@rotdrop Can you maybe rebase your PR so we trigger CI again and can get this merged?

**Pull request merged**
