### PR TITLE
Rename "Security" to "Devices & sessions"

### PR DESCRIPTION
**Pull request by MariusBluem**
Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by juliushaertl** [comment]
Since two factor auth settings also go there, "Security" actually makes more sense to me.

**Comment by MariusBluem** [comment]
Twofactor etc. has its own Headlines :)

**Comment by juliushaertl** [comment]
Ah right, it is just about renaming the section headline. Fine by me then :+1:

**Review by blizzz — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Works 👍

**Pull request merged**
