### PR TITLE
Fix folder path containing leading slash when getting mount root by id

### LINKED ISSUE #225: Access denied when opening files from shared group folder
When sharing an entire group folder through the normal user interface (share link) the permissions are broken/not checked correctly. The link is working for displaying the contents, but when opening a file I always get **access denied**.

**Steps to reproduce:**

1. Create a new groupfolder and add a group with sharing permission
2. Swith to the normal user UI, where the group folder now shows up
3. Open the share dialog for the newly created group folder and create a share link with "write permissions".
4. Create a new text file `test.txt` in the group folder
5. Open a different browser/private window and use the share link
6. You can see the test file `test.txt` in the directy listing. Click on the file.
7. You now get **access denied** → this is wrong

When sharing a subfolder from within the group folder the share links are working as expected. This only applies when sharing the entire group folder.

**Versions:**

- Nextcloud 14.0.3
- Groupfolder 1.3.3
- Collabora 3.0.5

### PR DESCRIPTION
**Pull request by icewind1991**
This fixes collabora on public link shared groupfolders

Fixes https://github.com/nextcloud/groupfolders/issues/225

Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by icewind1991** [comment]
@klada can you confirm that this fixes the issue for you

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Review by rullzer — APPROVED** [review]

**Comment by klada** [comment]
@icewind1991 Very nice, I can confirm that the fix is working :smiley:

**Comment by MorrisJobke** [comment]
@klada Nice to hear 👍

**Pull request merged**
