### PR TITLE
Shake the login fields if password is wrong

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @jancborchardt @mar1u5 @nextcloud/designers

### CODE REVIEW

**Comment by ChristophWurst** [comment]
:+1:

**Comment by mar1u5** [comment]
👍 ...do we want to have this in `stable10`

**Comment by mar1u5** [comment]
...and if yes, let me try to do backporting 😁 #traintocherrypick 😜

**Comment by mar1u5** [comment]
backport at #696 ... I've done a cherry pick 💪😜

**Comment by jancborchardt** [comment]
Very cool! We're getting more and more nice animations where it makes sense :)

**Pull request merged**
