### PR TITLE
Workaround for PHP bug when calling imagescale

### PR DESCRIPTION
**Pull request by juliusknorr**
Fix for #2208 

@MorrisJobke  @ace0024 @nextcloud/theming

### CODE REVIEW

**Comment by juliushaertl** [comment]
This should also be backported to stable10. cc @karlitschek

**Comment by karlitschek** [comment]
backport is fine once this is reviewed and tested.

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
@juliushaertl Could you open the backport PR? Thanks :)

**Comment by juliushaertl** [comment]
backport at https://github.com/nextcloud/server/pull/2291

**Pull request merged**
