### PR TITLE
Set file search by certain number of characters in config.php

### PR DESCRIPTION
**Pull request by ghost**
solution for issue #12139 

Solves the problem when you want to search in folder with thousands of files and the search freezes.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
My arguments from https://github.com/nextcloud/server/pull/12065#issuecomment-433391261 are still valid here.

Input from @nextcloud/designers is very welcome.

**Comment by MorrisJobke** [comment]
@Studna95 Don't get me wrong: I really like that you contribute something 👍 I just want to have it fixed properly, because in this way it is basically only fixed for you and for nobody else, because nobody else will configure this special item. So I would love to go one step back and check what the actual problem is. In the meantime you can use your fix on your machine and work around the problems you described until we have a real solution to the problem.

**Comment by jancborchardt** [comment]
Same here. As I said in https://github.com/nextcloud/server/issues/12139#issuecomment-434340008

> Agree with @MorrisJobke – this is a technical issue which needs to be properly fixed. **A configuration option makes _no_ sense here** since then _everyone_ would have to fix it for themselves. ;)

**Comment by jancborchardt** [comment]
So how do we continue here? @rullzer @MorrisJobke we don’t want to add a setting, so we have to reject the pull request in its current form. @Studna95 sorry again about this – maybe we come up with a better solution?

**Comment by skjnldsv** [comment]
I would suggest closing and directly fix the files list implementation

**Comment by jancborchardt** [comment]
@skjnldsv sounds good! If you have further pointers for @Studna95 if they want to work on that, let them know :)

**Pull request closed without merging**
