### PR TITLE
Fix setup checks for ocm/ocs-provider

### PR DESCRIPTION
**Pull request by MorrisJobke**
After some feedback from @schiessle it turns out that those two don't need to be accessible via root folder but only in the nextcloud (sub-)folder.

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> After some feedback from @schiessle it turns out that those two don't need to be accessible via root folder but only in the nextcloud (sub-)folder.

Ref #14255

**Comment by MorrisJobke** [comment]
stable15: #14854

**Pull request merged**
