### PR TITLE
Public interfaces Files_FullTextSearch

### PR DESCRIPTION
**Pull request by ArtificialOwl**
Signed-off-by: Maxence Lange <maxence@artificial-owl.com>

### CODE REVIEW

**Comment by daita** [comment]
based on https://github.com/nextcloud/server/pull/12046

**Review by ChristophWurst — APPROVED** [review]
:elephant: as discussed

**Comment by daita** [comment]
@rullzer some users want to extract more data from files, 2 mains examples I have in mind are OCR image files and metadata.

The idea is that when a file is indexed, an event is created by the files_fulltextsearch and the FilesDocument can be filled by a 3rd app:

https://github.com/daita/files_fulltextsearch_tesseract/blob/master/lib/Service/TesseractService.php#L93

**Comment by daita** [comment]
Please note than in the current files_fulltextsearch_tesseract, the PHPDoc still use `@var OCA\Files_FullTextSearch\...`, but should use `@var \OCP\Files_FullTextSearch\Model\AFilesDocument $document`

**Comment by rullzer** [comment]
@daita in that case would it not make sense to have a final class for files that is apssed around. Instead of all the apps ahving an interface they need to work with?

**Comment by daita** [comment]
The final class in files_fulltextsearch is slightly more complex, and because the object is only created by the Files_FullTextSearch and dispatched throw events, I wanted to keep it clean and simple for the core.

**Comment by rullzer** [comment]
Ah ok then :)

**Review by rullzer — APPROVED** [review]
:elephant:

**Comment by rullzer** [comment]
Autolaoders need an update

**Pull request merged**
