### PR TITLE
Allow SHARE_TYPE_GUEST as a share type

### PR DESCRIPTION
**Pull request by skjnldsv**
No idea why we have this guest share type if we never use it :man_shrugging:

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Does this fix any specific issue? If so please link it :)

**Comment by skjnldsv** [comment]
@ChristophWurst it doesn't directly.
But if you request the shares list, al guest shares are marked as being user share (which they also are, but either we remove the guest type, or we also allow to be outputted as guest type) :)

**Comment by ChristophWurst** [comment]
> remove the guest type

Have you checked if any apps use it? :) Also git blame might help you find people that might know more about the feature.

**Comment by skjnldsv** [comment]
@ChristophWurst https://github.com/nextcloud/server/pull/4575 https://github.com/nextcloud/guests/issues/4

But now the app use the type 0 (which should then be changed to 8) https://github.com/nextcloud/guests/blob/d7146b22fe27a720864fcb4331601024d0dfcc0a/src/GuestForm.vue#L147

**Comment by ChristophWurst** [comment]
lol the PR description and review comments in https://github.com/nextcloud/server/pull/4575 raise confidence in removing this

**Comment by skjnldsv** [comment]
xD
I'm fine with that as well, though I will not be able to indicate, in the sharing tab, that a share is a guest share (compared to other where we get an additional info like mail, groups, circle...)

But we should not have something we do not use in our code :)

**Comment by skjnldsv** [comment]
So, shall we instead remove all traces of the GUEST share type?

Since it's in the end, never used!

**Comment by skjnldsv** [comment]
So, there is a migration here, meaning we cannot really remove the guest type
https://github.com/nextcloud/server/blob/7800a9bc24d50d3eed40f8b1d40236a262b4f8ef/apps/files_sharing/lib/Migration/OwncloudGuestShareType.php#L69-L73

Question is, since we don't use it anywhere and that since the guests app is creating users share instead of guests shares, what do we do with those?
cc @rullzer @nickvergessen @blizzz

**Pull request closed without merging**
