### PR TITLE
fix(search): Close unified search at the second ctrl+f

### PR DESCRIPTION
**Pull request by ChristophWurst**
Maybe I'm too stupid by I find myself in the same situation every time I want to find something on a Nextcloud page

1) I press ctrl+f
2) I type my search string
3) I realize search went into Nextcloud's unified search. Useful but not what I wanted.
4) I click ctrl+f again (because I know it will be handled by the browser now)
5) I type my search string

master: the browser finds my string in the unified search
here: the browser finds my string in the main content

| Before | After |
|--------|--------|
| Bildschirmfoto vom 2023-10-12 18-23-44 | Bildschirmfoto vom 2023-10-12 18-23-06 | 

## Summary

Closes the unified search menu when the user clicks ctrl+f while the menu is open.

## TODO

- [x] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nimishavijay — APPROVED** [review]
Totally agreed! 🚀

**Review by Pytal — APPROVED** [review]

**Review by susnux — APPROVED** [review]
Hint: Use F3 ;)

**Review by jancborchardt — APPROVED** [review]
Absolutely agree, ran into this as well but forgot to open an issue – thanks a lot for the fix! :)

**Comment by ChristophWurst** [comment]
CI fails because the tests run so long, Nextcloud is asking for password confirmation.

**Comment by ChristophWurst** [comment]
So be it

**Pull request merged**
