### PR TITLE
#34969 Fix AppMenu icons for firefox

### LINKED ISSUE #34969: [Bug]: Icons in the AppMenu not showing properly in Firefox
### Bug description

**Nextlcoud version:** 25.0.1

The app icons are not visible in firefox.

https://github.com/nextcloud/server/blob/f53abd3995cffcc0c0a3c5d9be80d993242d9b4e/core/src/components/AppMenu.vue#L186

The padding here causes (on firefox) to make the icon so small that it disappears.

adding a `box-sizing: content-box;` fixes the issue without breaking safari or chrome.

https://user-images.githubusercontent.com/14948823/199985819-89e59e72-3cfa-4d77-9921-d803b3a3b4bb.mp4

### PR DESCRIPTION
**Pull request by cupcakearmy**
- fixes #34969

### CODE REVIEW

**Comment by cupcakearmy** [comment]
@szaimen thanks for looking at this :) Is there any way this could land in 25 and not 26? it's quite a critical visual bug for anyone using firefox, as the icons on the homescreen simply stop showing up :)

**Comment by skjnldsv** [comment]
@cupcakearmy it will make it for 26 first, then backported to 25

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Can you rebase, compile and ship the compiled dist files too @cupcakearmy please? :)

**Comment by cupcakearmy** [comment]
@skjnldsv I see :) perfect!

Rebase on what? I'm not a huge rebase expert xD

**Comment by cupcakearmy** [comment]
I tried installing the deps in the github codespaces (don't want to install it locally) but for some reason I get errors when running `make dev-setup` (to rebuild the dist file)

```sh
Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/nextcloud/strengthify.git
```

Otherwise running `npm i` leaves ~25 peer deps uninstalled and the build fails.

I don't have time to go down this rabbit hole unfortunately. Feel free to use the code at free will.

**Pull request closed without merging**
