### PR TITLE
SharePoint support

### PR DESCRIPTION
**Pull request by blizzz**
Contributes to https://github.com/nextcloud/server/issues/2672

Add a SharePoint Backend to files_external

## configuration:

spectacle k24324

## requirements

* NTLM Auth enabled on SP. We strictly require NTLM Auth. Basic did not work for me, I assume because of the SP/IIS configuration. Apparently NTLM is > then Basic anyhow.

## environment

* tested and  developed against SharePoint 2016, but
* SharePoint 2013 should work, however this is not proven
* https://github.com/vgrem/phpSPO/pull/63 is applied to phpSPO lib

## features

* dir listings, trying to identify and hide hidden system directories (e.g. "Forms").
* creating dirs
* down- and upload of files (via streams, exception: new files)
* renames
* removing files and folders (using recycle method i.e. putting it into the wastebin)
* determine CRUD permissions

### CODE REVIEW

**Comment by icewind1991** [comment]
Any chance we can keep the dragons contained in their own app?

**Comment by blizzz** [comment]
@icewind1991 i caught one dragon for you: on mkdir('foo/bar') an opendir against 'foo' is performed. why?

**Comment by blizzz** [comment]
spectacle n27143

Lol, Github, you're living in teh past?!

**Comment by blizzz** [comment]
After some off-github discussions, this is deprecated in favor of a separate app → https://github.com/nextcloud/sharepoint

**Pull request closed without merging**
