### PR TITLE
Set default max_chunk_size for files app to 100MB

### LINKED ISSUE #26977: Set default max_chunk_size for files app to 100MB
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The default chunk size of 10MB for the uploads in the web app is much too less in the current time. Please consider to change it to 100MB.

**Describe the solution you'd like**
By changing the default value of the max_chunk_size to 100MB, I was able to tremendously improve the upload speed for big files using the files web app.

**Describe alternatives you've considered**
Maybe change it to 1000MB but thats probably already too much.

**Additional context**
I talk about this value: https://docs.nextcloud.com/server/20/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=chunk#adjust-chunk-size-on-nextcloud-side

### PR DESCRIPTION
**Pull request by szaimen**
fix #26977
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by blizzz** [comment]
it's a low default to work with  server limits, I would keep it that way tbh. The config can always be changed by the admin who knwis their environment.

**Comment by szaimen** [comment]
Okay 👍

**Comment by devnoname120** [comment]
> it's a low default to work with server limits, I would keep it that way tbh. The config can always be changed by the admin who knwis their environment.

Do we have evidence that `10 MB` is a reasonable server limit?
I see countless of threads of people on internet complaining that their uploads are slow. But they don't have the necessary technical expertise to link it to chunk size.

**Comment by blizzz** [comment]
When admins can configure their webserver and PHP, they can also increase the chunk size. When other admins have only limited access and need to leave with default values by their hoster they cannot and might not even have access to the occ utility.

**Comment by devnoname120** [comment]
@blizzz What would you think about setting the default to `auto` and calling this function to determine the max upload size?

```php
<?php
$default_max_chunk_size = ini_get('upload_max_filesize');

if ($default_max_chunk_size === false) {
	$default_max_chunk_size = 10 * 1024 * 1024;
}
```

This wouldn't work for misconfigured apache/nginx servers though.

**Pull request closed without merging**
