### PR TITLE
Files version improvements

### PR DESCRIPTION
**Pull request by CarlSchwan**
For now frontend only, backend will follow soon™
    
- Add avatar of the user who made the change
- Allow to mark a version as favorite (goal is that these versions are
      persistent)

image

Build on top of #34769

### CODE REVIEW

**Comment by juliushaertl** [comment]
Some general thoughts on showing the user that made the change, for collaborative editing it would be quite nice if the version could also be created by an app (in terms of the metadata stored) and have a list of users that worked on the version. 

Common use cases would be apps like text or Office where users work together on a certain set of changes until the save is happening either through autosave or the manual save operation of a user.

I'm not sure in which phase you are regarding the backend implementation and if this would be in scope for the planned change, so just leaving this here for consideration.

**Comment by CarlSchwan** [comment]
> Some general thoughts on showing the user that made the change, for collaborative editing it would be quite nice if the version could also be created by an app (in terms of the metadata stored) and have a list of users that worked on the version.
> 
> Common use cases would be apps like text or Office where users work together on a certain set of changes until the save is happening either through autosave or the manual save operation of a user.
> 
> I'm not sure in which phase you are regarding the backend implementation and if this would be in scope for the planned change, so just leaving this here for consideration.

Backend is currently not implemented, but I had some rough idea how it would work. I didn't think about multiple users could be doing one change scenario from office. Thanks for pointing it out, if you have any ideas on how this would look like api wise, let me know ;)

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Nice! :) Some design feedback:

- [ ] The wording of the menu is much too complex – as per the spec at https://github.com/nextcloud-gmbh/customer-feature-requests/issues/189#issuecomment-1257905430 it can simply be: "Name this version" (or "Edit version name" if name is set), "Download version", "Restore version" and "Delete version".
- [ ] The icon in the tab header can be the same as the one you used for the emptycontent and the buttons
- [ ] Modal:
  - [ ] "Name this version" could be modal heading _and_ the input label as well for simplicity?
  - [ ] The explanatory note below the field can be `color-text-maxcontrast`
  - [ ] The button should be "Save version name" and on the right, also as per spec
  - [ ] We should have a specific "Cancel" button on the left

**Comment by artonge** [comment]
Ah, didn't see this PR before starting https://github.com/nextcloud/server/pull/35080
Closing in favor of mine :grimacing:

**Pull request closed without merging**
