### PR TITLE
Revert "[stable24] Fix quota type to int"

### PR DESCRIPTION
**Pull request by PVince81**
Reverts nextcloud/server#34032 to unbreak 32-bit quota setting.

See https://github.com/nextcloud/server/issues/34961#issuecomment-1323719794

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
CI is unhappy

**Comment by PVince81** [comment]
cherry-picked 7bcd4193b8f58ea36d76d03d672b1b5c92831dc1 to hopefully fix CI

**Comment by PVince81** [comment]
@CarlSchwan @come-nc can you help ?

**Review by szaimen — CHANGES_REQUESTED** [review]
Id say lets move it to 24.0.9

**Comment by PVince81** [comment]
seems I managed to make psalm happy by updating the baseline

I'll fix the DCO next

**Comment by szaimen** [comment]
@PVince81can you make sure that this is tested?

**Comment by PVince81** [comment]
tested, looks fine

**Review by szaimen — APPROVED** [review]
okay for me then

**Pull request merged**
