### PR TITLE
Fix various theming bugs

### PR DESCRIPTION
**Pull request by Pytal**
- Fix flashing background color with new `--color-main-background-plain` CSS variable and `--color-main-background` fallback
- Fix missing checkmark when plain background is selected
- Fix plain background not being used on pages other than Appearance and accessibility and dashboard pages
- Fix plain background not being set without a reload by automatically refreshing server-side generated CSS
- Remove js style overrides in favour of automatically refreshing server-side generated CSS on background change

### CODE REVIEW

**Comment by Pytal** [comment]
The CSS isn't being refetched from the server on background change @skjnldsv, how was it done before?

**Comment by szaimen** [comment]
Does this also resolve https://github.com/nextcloud/server/issues/33840?

**Comment by skjnldsv** [comment]
> The CSS isn't being refetched from the server on background change @skjnldsv, how was it done before?

Seems indeed. Here is a snipet how to reload all themes instantly
```js
[...document.head.querySelectorAll('link.theme')].forEach(theme => {
	const url = new URL(theme.href)
	url.searchParams.set('v', Date.now())
	const newTheme = theme.cloneNode()
	newTheme.href = url.toString()
	newTheme.onload = () => theme.remove()
	document.head.append(newTheme)
})
```

Maybe just setting

**Comment by Pytal** [comment]
> Does this also resolve #33840?

Cannot reproduce but changed code does not seem related so probably needs to be fixed separately 🤔

**Review by szaimen — APPROVED** [review]
🐘

**Comment by szaimen** [comment]
@Pytal needs a rebase...

**Comment by blizzz** [comment]
master is 26, please trigger a backport if necessary.

**Comment by Pytal** [comment]
Please review as this is needed to fix theming bugs and to auto-refresh styles in https://github.com/nextcloud/server/pull/34298 :)

**Comment by szaimen** [comment]
Already approved... Kaybe @skjnldsv can do the other review?

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
please check CI, the app theming seems to have found a bug

**Pull request merged**
