### PR TITLE
added documentation links on settings pages

### PR DESCRIPTION
**Pull request by wiswedel**
⚠️ depending on https://github.com/nextcloud/documentation/pull/1666 ⚠️

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by wiswedel** [comment]
@skjnldsv @juliushaertl Can one of you please check on the blocking CI error? I don't know the first thing about that or how to fix it 🥺

**Comment by skjnldsv** [comment]
Failures are irrelevant to your changes :)

**Pull request merged**
