### PR TITLE
fix(AmazonS3):  fix loop $result['Contents'] error

### PR DESCRIPTION
**Pull request by lanxenet**
Invalid argument supplied for foreach() at /var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php#295

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by MorrisJobke** [comment]
Seems to fix #9403

**Comment by MorrisJobke** [comment]
@lanxenet Sorry that this somehow was not seen by anybody of us.

**Review by icewind1991 — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Backport is in #9650

**Pull request merged**
