### PR TITLE
move versions webui over to the dav api

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
Then https://github.com/nextcloud/server/pull/9450 can go I guess :wink:

**Comment by icewind1991** [comment]
@MorrisJobke @nickvergessen  @rullzer please review

**Review by MorrisJobke — APPROVED** [review]
Tested the web UI and it works 👍

**Comment by MorrisJobke** [comment]
CI failure is unrelated.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
