### PR TITLE
Fix untranslated "User disabled" on login screen

### LINKED ISSUE #24549: Untranslated "User disabled" on login screen
Hello,

I have noticed that “User disabled" is not translated on login screen:

Lithuanian login screen:
https://help.nextcloud.com/uploads/default/original/3X/b/f/bfb9a0fba9526170af1074ad5743cbf6698b280c.png

German login screen:
https://help.nextcloud.com/uploads/default/original/3X/2/0/20a7e4bab37f5ee9df6772c92dbce71e6230f7c4.png

These words are translated on Transifex, e.g. Lithuanian:
https://help.nextcloud.com/uploads/default/original/3X/c/d/cdd7a732005aeb1a058b35aa229d0b8a8f756ca5.png

Regards

### PR DESCRIPTION
**Pull request by nina-py**
Signed-off-by: Nina Pypchenko <22447785+nina-py@users.noreply.github.com>

Closes #24549.

Verified on my dev checkout. Before:

before

After:

after

### CODE REVIEW

**Comment by nina-py** [comment]
Uhm. If someone can explain what this job failure means and if I need to do something about it, it would be very helpful: https://github.com/nextcloud/server/runs/1563267635?check_suite_focus=true

**Comment by kesselb** [comment]
> Uhm. If someone can explain what this job failure means and if I need to do something about it, it would be very helpful: https://github.com/nextcloud/server/runs/1563267635?check_suite_focus=true

The job fails because the compiled javascript is not up to date. Run `make build-js-production` and commit the result to fix it. 

> /compile /core/js

I asked the bot to compile the javascript for us. If the bot is not able to do compile it do the above steps.

**Review by kesselb — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
@dependabot merge

**Comment by nina-py** [comment]
> The job fails because the compiled javascript is not up to date. Run `make build-js-production` and commit the result to fix it.

Thank you for the explanation @kesselb, will make sure to run this next time.

**Pull request merged**
