### PR TITLE
Cache non existing DB user

### PR DESCRIPTION
**Pull request by rullzer**
We always query the database backend. Even if we use a different one
(ldap for example). Now we do this everytime we try to get a user object
so caching that a user is not in the DB safes some queries on each
request then (at least 2 what I found).

CC: @nickvergessen @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
Bad luck with parallel requests, but I guess this is acceptable.

👍

**Comment by nickvergessen** [comment]
Should we update the flag on delete?

**Comment by rullzer** [comment]
We could. Altough it is probabaly not needed. Will result in at most one 1 extra query in that request. (the request where you delete a DB user).

**Comment by LukasReschke** [comment]
LGTM

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
