### PR TITLE
Make sure group management works with all types of group names

### PR DESCRIPTION
**Pull request by juliusknorr**
Group ids currently don't have any character limitations, which means that you can create groups like "Department A/B" which will fail on both the provisioning API as well as the routes provided by our user management. 

This PR ensures that all group ids are encoded and properly handled by both the backend and the frontend then.

I'm not to happy about the double encoding here, but this is the only way that we can keep the groupId as part of the URL without making it a query parameter and therefore breaking the provisioning api.

In general I would prefer to add some character limitation to the group id, similar to how we do it for the user id, where `/` is blocked, but that would still leave us with instances that might have those broken ids.

### CODE REVIEW

**Comment by juliushaertl** [comment]
cc @rullzer @GretaD for review since it also fails for me to request that now.

**Comment by skjnldsv** [comment]
Maybe add some phpunit testing? :see_no_evil:

**Comment by juliushaertl** [comment]
Yeah, I'll do that. Anyone has concerns/ideas regarding the double encoding?

**Comment by skjnldsv** [comment]
Looks sane to me

**Comment by gary-kim** [comment]
> Yeah, I'll do that. Anyone has concerns/ideas regarding the double encoding?

Not a fan but if it works..,

**Comment by juliushaertl** [comment]
Added some test cases :wink:

**Comment by juliushaertl** [comment]
Rebased and ready for review.

**Review by skjnldsv — APPROVED** [review]

**Review by GretaD — APPROVED** [review]
tested and works :+1:

**Pull request merged**
