### PR TITLE
[stable9] Remove notifications upon user deletion

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #1558 

@blizzz @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Review by MorrisJobke — APPROVED** [review]

**Comment by blizzz** [comment]
Unit tests failing :scream:

**Comment by nickvergessen** [comment]
Fixed, failed on conflict resolution

**Comment by blizzz** [comment]
tested and works :+1:

**Pull request merged**
