### PR TITLE
Fix sharer name overlap with filename

### LINKED ISSUE #6498: Share info is overlapping filename when sidebar is opened
* having a received share (the name of the owner is shown in the file list)
* open the sidebar for this file
* actual: sometimes the filename is overlapped by the share info
* expected: filename should get cropped and an ellipsis should be added

bildschirmfoto 2017-09-14 um 11 14 14

----

bildschirmfoto 2017-09-14 um 11 14 02

cc @nextcloud/designers Do you have an idea how to implement this?

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #6498, please review @MorrisJobke @skjnldsv @nextcloud/designers 
screenshot from 2017-09-14 16-44-10
screenshot from 2017-09-14 16-43-52

### CODE REVIEW

**Comment by skjnldsv** [comment]
Still a bit confusing
capture d ecran_2017-09-14_16-46-15


But hey, that's a fix.
We should aim for a fresh rebuild of the table for a next version.

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
@skjnldsv yup – the right sidebar is an overlapping element in that sense though. I didn’t change anything there, but we could do things like make the filelist even narrower. Otherwise at some point we have to overlap anyway. :)

**Comment by skjnldsv** [comment]
@jancborchardt we could hide stuff like I did on the mobile view, try changing the width of the window without the sidebar opened. This is true responsiveness 😃

**Review by MorrisJobke — APPROVED** [review]
Better than nothing, but still a bit confusing. Sadly until we properly fixed the table there is not much we can do here. 👍

**Comment by MorrisJobke** [comment]
Waiting for CI: https://drone.nextcloud.com/nextcloud/server/1536

**Comment by MorrisJobke** [comment]
Backport is in #6524

**Pull request merged**
