### PR TITLE
fix(session): Avoid race condition for cache::get() vs. cache::hasKey()

### PR DESCRIPTION
**Pull request by nickvergessen**
- Follow up to https://github.com/nextcloud/server/pull/44446

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by nickvergessen** [comment]
Seems to solve the issue, so merging

**Comment by jerome-micucci** [comment]
It's work like a charm with 28.0.5

**Pull request merged**
