### PR TITLE
feat: add `block-unconventional-commits` workflow

### PR DESCRIPTION
**Pull request by skjnldsv**
@nextcloud/server

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]
I think we can both agree, something about conventional commits are sexy 😍
LGTM 🐘

**Comment by skjnldsv** [comment]
Only `sharing/download-share-disabled.cy.ts` is failing it seems, haven't took the time to fix them for now.

**Review by come-nc — COMMENTED** [review]
This should be accompanied with a documentation update, maybe here:
https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md
Or/and here:
https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html

**Comment by skjnldsv** [comment]
Done @come-nc

**Review by come-nc — APPROVED** [review]

**Pull request merged**
