### PR TITLE
Fix "Invalid argument supplied for foreach()"

### LINKED ISSUE #7804: Log file flooded with apps/user_ldap/lib/Access.php#1852
Hello,

We’ve recently started using LDAP with more than just test users. I am seeing this error in the log.

Nextcloud version (eg, 12.0.2): 12.0.4.3
Operating system and version (eg, Ubuntu 17.04): ubuntu xenial
Apache or nginx version (eg, Apache 2.4.25): Apache/2.4.18 (Ubuntu)
PHP version (eg, 7.1): PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

Is this the first time you’ve seen this error? (Y/N): Y

Steps to replicate it: Unknown

The output of your Nextcloud log in Admin > Logging:
**The log file is absolutely flooded with this message
Invalid argument supplied for foreach() at /var/www/nextcloud/apps/user_ldap/lib/Access.php#1852**

The output of  config.php file

```
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx,
  'trusted_domains' => 
  array (
    0 => 'my_domain.com',
  ),
  'datadirectory' => '/opt/nextcloud-data',
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'http://my_domain.com',
  'htaccess.RewriteBase' => '/',
  'dbtype' => 'mysql',
  'version' => '12.0.4.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'default_language' => 'ca',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => 
  array ( 
    'host' => 'localhost',
    'port' => 6379,
  ),
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpmode' => 'sendmail',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'no-reply',
  'mail_domain' => 'mydomain.com',
);
```

Thanks for any help!

### PR DESCRIPTION
**Pull request by GitHubUser4234**
Fixes #7804

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Review by blizzz — APPROVED** [review]
:+1: make sense. 

In future, please use short notations ``[ … ]`` for arrays.

**Comment by blizzz** [comment]
@GitHubUser4234 tests are failing

**Comment by rullzer** [comment]
Awesome stuff once agian @GitHubUser4234 thnx

**Comment by MorrisJobke** [comment]
@GitHubUser4234 @blizzz @rullzer Maybe worth a backport, right?

**Comment by MorrisJobke** [comment]
backport is in #9654

**Pull request merged**
