### PR TITLE
additional attempt to get a useful user name to put in the From line of a calendar invite email

### LINKED ISSUE #45081: [Bug]: From Name is not setting properly in Calendar invitations created from Thunderbird
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When sending calendar invite from Thunderbird or other CalDAV supported calendars, the From Name is not correct. When sent from within nextcloud web UI, the invitation email is sent with From name being "user via nextcloud". But when the calendar event is created from Thunderbird, the invitation email is sent with From name being "nextcloud". 

I wasn't sure if this is related to this issue - https://github.com/nextcloud/server/issues/5080 because I am not asking to chagne the from email Address. I am reporting an issue with the from name. I also have a fix for this. So, I thought that I can create a new issue and try to send a PR for this fix 

### Steps to reproduce

**These steps work fine:**
1. Login to NextCloud Web UI. 
2. Open the Calendar App. 
3. Add a new event in the Calendar 
4. The invitation email sent from the server contains the From name "User via Nextcloud"

**These steps produces the issue:** 
1. Add/Connect the Nexcloud CalDAV in Thunderbird (or any email client that supports CalDAV
2. Ensure that the calendar is setup to leverage server side scheduling
3. Add a new event in the Calendar
4. The invitation email sent from the server contains the From name "Nextcloud"

### Expected behavior

The invitation email sent from the server when the calendar event is created in Thurderbird should also be "User via Nextcloud". 

### Installation method

None

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by jpmg-mb**
* Resolves: #45081 

## Summary

When generating a calendar event invite email from an event generated within thunderbird or similar application, nextcloud generates a From line that does not identify the person generating the invite.  This patch makes a further attempt to extract a real name and add it to the From line.  I've been running this patch informally against most nextcloud versions from v25.0.4 onwards, and it has fixed the issue, and not caused any observed problems.  

@GalacticWave @SebastianKrupinski 

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]
Nice :shipit:

**Comment by tcitworld** [comment]
Please change the target branch to master instead. The change may then be backported to earlier versions.

**Comment by artonge** [comment]
@jpmg-mb You need to base your branch on master :)

**Comment by jpmg-mb** [comment]
@artonge I realised 5s too late ...    (very embarrassed)

**Comment by st3iny** [comment]
This is already fixed/implemented if the new mail provider is used and the organizing user has a mail account set up in the Mail app.

**Pull request closed without merging**
