### PR TITLE
fix(comments): Use proper icon components instead of icon classes to fix dark mode

### PR DESCRIPTION
**Pull request by susnux**
## Summary

When using the comments app with dark mode the icons are hard to see because they are all black.
This is fixed with using proper icon components.

### Screenshots

before | after
---|---
Screenshot 2024-06-13 at 18-06-37 Files - Nextcloud|Screenshot 2024-06-13 at 18-12-13 img_3236 jpg - Nextcloud

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by skjnldsv** [comment]
Awesome!!

**Comment by solracsf** [comment]
@skjnldsv should this re-backported to stable28 ?

**Pull request merged**
