### PR TITLE
User is not found when is searched by name and one of surnames #7510

### LINKED ISSUE #7510: User is not found when is searched by name and one of surnames
### Premise
User backend in LDAP

### Steps to reproduce
1. Upload a file
2. Click on sharing icon
3. Search for a user, using name and first of surnames. For example: User is "Roger Luis Padilha de Souza". Then, search for "Roger Luis". User will be found.
3. After, search for same user, using name and one for surnames, except the first of them. For example: User is "Roger Luis Padilha de Souza". Then, search for "Roger Padilha"
4. User won't be found

### Expected behaviour
User must be found using name and one of surnames

### Actual behaviour
User is found only if search uses name and first of surnames

### Constraint
Behaviour must be defined by configuration (config.php). Default must be actual behaviour. Expected behaviour must be enabled by key **user_ldap.enable_medial_search** equals to **true**.

### PR DESCRIPTION
**Pull request by fgsl**
Fixes #7510

### CODE REVIEW

**Comment by blizzz** [comment]
wrt https://github.com/nextcloud/server/pull/8178#issuecomment-371808794, $this->connection->ldapMedialSearch would not need to be needed, but it would check the presence of an asterisk at the beginning of the word. So, all that needs to be done is breaking up the term into words.

The queston is whether you need to have an asterisk before each word (less user friendly, more exact) or just once in the beginning of it (easier, less flexbile, potential for frustration, but essentially the same as if the setting would be set → I'd favor this).

**Comment by fgsl** [comment]
> wrt #8178 (comment), $this->connection->ldapMedialSearch would not need to be needed, but it would check the presence of an asterisk at the beginning of the word. So, all that needs to be done is breaking up the term into words.
> 
> The queston is whether you need to have an asterisk before each word (less user friendly, more exact) or just once in the beginning of it (easier, less flexbile, potential for frustration, but essentially the same as if the setting would be set → I'd favor this).

@blizzz, let me understand, do you propose something like this?

```
// remove $allowMedialSearch = $this->connection->ldapMedialSearch;
if ($term === '') {
    $result = '*';
} else if ($allowEnum !== 'no') {
    if ($term[0] == '*'){ // checks for asterisk at beginning
        $term = $substr($term,1);
        $term = explode(' ',$term); // break up the term in words based on space
        array_walk($term, function(&$value, $key) {
            $value = '*' . $value; // prepend each word with asterisk
        });
        $result = implode(' ',$term);
    } else {
        $result = $term . '*';
    }    
}
```

**Comment by blizzz** [comment]
> @blizzz, let me understand, do you propose something like this?

yes… well sort of. breaking up words is dependend on whether spaces are provided, and only then asterisk are prepended or not.

**Comment by blizzz** [comment]
The method will get single words, only, see ``getAdvancedFilterPartForSearch`` which breaks up the words.

**Comment by fgsl** [comment]
> The method will get single words, only, see getAdvancedFilterPartForSearch which breaks up the words.

Yes, @blizzz, excuse me, I was, as we say here, "traveling on mayonnaise". Last snippets are unuseful because only repeat what previous method does. Variable $term already is a single word because `getAdvancedFilterPartForSearch` has exploded searched term.

Then, I think that following change maybe is that you should favor for `prepareSearchTerm`:
```

// remove $allowMedialSearch = $this->connection->ldapMedialSearch;
if ($term === '') {
    $result = '*';
} else if ($allowEnum !== 'no') {
    if ($term[0] !== '*'){ // checks for absence of asterisk at beginning
        $result = '*' . $term . '*';  // round term with asterisks
    } else {
        $result = $term . '*'; // only appends asterisk
    }    
}
```

**Comment by blizzz** [comment]
In that case you will end up with double asterisk in front. When passing any word to ``prepareSearchTerm`` you need to ensure that they will have an asterisk in the beginning, when the very first word begins with one.

**Comment by fgsl** [comment]
> In that case you will end up with double asterisk in front. When passing any word to prepareSearchTerm you need to ensure that they will have an asterisk in the beginning, when the very first word begins with one.

Hey, @blizzz, then it is a bug in current code, because if $term is equal to asterisk, $result will be a double asterisk:

`$result = $term . '*';`

I want to say that this code needs to be changed anyway. It seems to me that is enough to check the length of string, so:

Replace:

`} else {`

for:

`} elseif (strlen($term)>1){`

Can it be so?

**Comment by blizzz** [comment]
No, there can be only an asterisk at the beginning of the whole search term, any other occurrence is escaped.

**Comment by fgsl** [comment]
Right, if I understand now - otherwise I will generate a test case because it's getting confused - we can change if.. else.. structure to two if statements so:

```
if ($term === '' xor ($allowEnum !== 'no')) {
    $result = $term . '*'; // only appends asterisk
}
if ($term !== '*' && $term[0] !== '*'){ // checks for absence of asterisk at beginning
        $result = '*' . $term;  // prepend  asterisks
}

```
if $term is equal to '', $result will be '*'.
if $term is different to '' and $allowEnum is different of 'no', $result is $term concatenated to '*'. If current code is correct, $term is not equal to '*', so this condition won't produce a double asterisk. Otherwise, current code already produces double asterisk - and I understand that it doesn't happen.
For any $result, an asterisk is prepended before return it.

I hope I didn't drink this time.

**Comment by fgsl** [comment]
If "prepending should only happen, when the whole phrase was started with an asterisk", I think that proposal change can be discarded and replaced by that:

```
	private function getAdvancedFilterPartForSearch($search, $searchAttributes) {
		if(!is_array($searchAttributes) || count($searchAttributes) < 2) {
			throw new \Exception('searchAttributes must be an array with at least two string');
		}
		$searchWords = explode(' ', trim($search));
		$wordFilters = array();
                $prepend = ($searchWords[0][0] == '*' ? '*' : ''); // checks for asterisk at beginning
		foreach($searchWords as $word) {
			$word = $this->prepareSearchTerm($word);
                        $word = (($word[0] == '*' ? '' : $prepend) . $word); // prepend asterisk if phrase starts with asterisk
			//every word needs to appear at least once
			$wordMatchOneAttrFilters = array();
			foreach($searchAttributes as $attr) {
				$wordMatchOneAttrFilters[] = $attr . '=' . $word;
			}
			$wordFilters[] = $this->combineFilterWithOr($wordMatchOneAttrFilters);
		}
		return $this->combineFilterWithAnd($wordFilters);
	}
```

**Comment by blizzz** [comment]
@fgsl yes, the approach in https://github.com/nextcloud/server/pull/8760#issuecomment-389633459 looks good. Just, when doing comparions, always do it strictly: `===`

For the tests I had unit tests in mind (apps/user_ldap/tests/AccessTest.php). If feasible?

**Comment by MorrisJobke** [comment]
Nothing for 14 it seems -> moved to 15

**Pull request closed without merging**
