### PR TITLE
Translate the "Passwords are enforced..." exception

### PR DESCRIPTION
**Pull request by er-vin**
Signed-off-by: Kevin Ottens <kevin.ottens@nextcloud.com>

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Exceptions in this file are all not translated. So I guess it should be translated at another point.

**Comment by er-vin** [comment]
> Exceptions in this file are all not translated. So I guess it should be translated at another point.

I'd need guidance there, it's very much outside my area of understanding how this server is organized.

**Comment by GretaD** [comment]
> > Exceptions in this file are all not translated. So I guess it should be translated at another point.
> 
> I'd need guidance there, it's very much outside my area of understanding how this server is organized.

I guess what Joas means is that none of the other string at that file is translated: https://github.com/nextcloud/server/blob/master/lib/private/Share20/Manager.php#L222
so we either translate them all, or none of it for now. Or we can ask a community member to do it as part of the hacktober :)

**Comment by er-vin** [comment]
> > > Exceptions in this file are all not translated. So I guess it should be translated at another point.
> > 
> > 
> > I'd need guidance there, it's very much outside my area of understanding how this server is organized.
> 
> I guess what Joas means is that none of the other string at that file is translated: https://github.com/nextcloud/server/blob/master/lib/private/Share20/Manager.php#L222
> so we either translate them all, or none of it for now. Or we can ask a community member to do it as part of the hacktober :)

My understanding was that there was another point in the stack where it'd have been more clever to translate this. But sure, even though that's not what I understood of @nickvergessen reply, we could translate all in that file instead. I'm a bit swamped right now to update that PR though.

**Comment by nickvergessen** [comment]
I think the password should be verified here (or handled on the updateShare at the end of that block)
 https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/Controller/ShareAPIController.php#L1106
and return a ocs exception with a translated string like here:

https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/Controller/ShareAPIController.php#L1075

**Comment by er-vin** [comment]
Sorry, but turns out I got zero bandwidth for that at the moment. So either someone adopts it or I'll close it I think.

**Comment by juliushaertl** [comment]
Let's close this for now. Anyone who wants to pick up, feel free to take over.

**Pull request closed without merging**
