### PR TITLE
[21] dont apply jail search filter is on the root

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #28175

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: tested, works

**Comment by PVince81** [comment]
@icewind1991 seems you'll need to appease the Oracle:
```
2021-07-29T11:54:25.3526402Z 1) OCA\Files_Sharing\Tests\CacheTest::testSearchByMime
2021-07-29T11:54:25.3527204Z Failed asserting that 6 matches expected 3.
```

guessing that there might be a cleanup issue ?

**Comment by icewind1991** [comment]
> @icewind1991 seems you'll need to appease the Oracle:
> 
> ```
> 2021-07-29T11:54:25.3526402Z 1) OCA\Files_Sharing\Tests\CacheTest::testSearchByMime
> 2021-07-29T11:54:25.3527204Z Failed asserting that 6 matches expected 3.
> ```
> 
> guessing that there might be a cleanup issue ?

fix

**Review by PVince81 — APPROVED** [review]
:+1: re-tested, re-works

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
