### PR TITLE
Temporary fix for project translations

### PR DESCRIPTION
**Pull request by juliusknorr**
This is a temporary fix to let our translation extractor take the project related strings into consideration. 

Ideally the translations should be included in the library (as described in https://github.com/juliushaertl/nextcloud-vue-collections/issues/120) but this requires some deeper work on the l10n handling. Since we need to either make the library use the Nextcloud language to load the matching translations or somehow make the server extract the strings from the library and append it to the existing translations during the webpack build.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by georgehrke — APPROVED** [review]

**Comment by skjnldsv** [comment]
Webpack build failed

**Comment by skjnldsv** [comment]
Lots of failure :/

**Comment by juliushaertl** [comment]
jsunit is happy now, unit tests are failing on master as well.

**Comment by skjnldsv** [comment]
Backport @juliushaertl ?

**Comment by skjnldsv** [comment]
Backport in https://github.com/nextcloud/server/pull/15893

**Pull request merged**
