### PR TITLE
Drop obsolete tables: gallery_albums and gallery_photos

### PR DESCRIPTION
**Pull request by nblock**
Commit 34a21a63ce5730a4f45af6745b4acd6f702e6e79 renamed gallery_albums
to pictures_images_cache and removed gallery_photos entirely.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Makes sense 👍

**Comment by MorrisJobke** [comment]
cc @LukasReschke @blizzz @schiessle

**Comment by mar1u5** [comment]
👍

**Comment by mar1u5** [comment]
THX.

**Pull request merged**
