### PR TITLE
[stable25] Fix theming tests

### PR DESCRIPTION
**Pull request by Pytal**
Fix tests for https://github.com/nextcloud/server/pull/35346

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Seems to work, thanks!

**Comment by Pytal** [comment]
> /backport to master

master is already passing though?

**Comment by szaimen** [comment]
> master is already passing though?

yeah, I dont understant why...

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by szaimen** [comment]
Manual backport in https://github.com/nextcloud/server/pull/35420

**Pull request merged**
