### PR TITLE
Remove obsolete GD function overwrites

### PR DESCRIPTION
**Pull request by J0WI**
pick from #28279, those functions are part of PHP (7.2+)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by szaimen** [comment]
Not sure if phpunit failure is related...

**Comment by szaimen** [comment]
I think PHPunit failure is unrelated

**Comment by szaimen** [comment]
nodb failure...

**Comment by szaimen** [comment]
> `getJpegQuality` does not work as expected...

Maybe a mock is missing somewhere?

**Comment by szaimen** [comment]
Thanks a lot @J0WI ! :)

**Pull request merged**
