### PR TITLE
Fixed notifications position

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by ChristophWurst** [comment]
How do I test this?

**Comment by skjnldsv** [comment]
@ChristophWurst find a page who scrolls, create a temp notification, scroll and see the notification fly up as you scroll
With this patch, it stays at the top :)

**Comment by ChristophWurst** [comment]
Thanks! Can verify the patch working. Isn't this fixing the visual bug I was asking you about a few days ago and you said there was no bug? :stuck_out_tongue:

**Review by ChristophWurst — APPROVED** [review]
Perfect :raised_hands:

**Comment by skjnldsv** [comment]
> and you said there was no bug? :stuck_out_tongue:

telechargement

**Comment by danopz** [comment]
Does not work for me with multi line notifications or multiple ones.

Just copied the style using dev-tools and added some notifications with `OC.Notification.show('foobar')`.
The container is in the top most layer and makes it impossible to use the navigation and some elements.

**Comment by skjnldsv** [comment]
@danopz the notification always have been on top of the header. This fixes the scrolling issue on the notification. 
Aside from the (very) unpractical way the notifications are displayed, is there anything wrong? :)

**Pull request merged**
