### PR TITLE
update icewind/streams to 0.5.2

### PR DESCRIPTION
**Pull request by icewind1991**
For https://github.com/nextcloud/server/issues/1166

- [x] requires https://github.com/nextcloud/3rdparty/pull/31

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested together with #3157

**Comment by MorrisJobke** [comment]
@schiessle @nickvergessen @blizzz @rullzer Mind to review this one here?

**Comment by MorrisJobke** [comment]
I updated the 3rdparty module to reflect the rebase there.

**Comment by icewind1991** [comment]
Rebased since 3rdparty is merged

**Review by rullzer — APPROVED** [review]
LGTM

**Comment by MorrisJobke** [comment]
@karlitschek Backport for #1166?

**Comment by karlitschek** [comment]
please backport

**Comment by MorrisJobke** [comment]
@icewind1991 Could you create the backport PRs, thanks :)

**Comment by MorrisJobke** [comment]
Ping @icewind1991

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/3293

**Pull request merged**
