### PR TITLE
Disable fragile comments tests

### PR DESCRIPTION
**Pull request by MorrisJobke**
Those tests are actual problems in our code. See https://github.com/nextcloud/server/pull/20462#issuecomment-613380650 for a summary by @danxuliu

Basically they are introduced by #18929 but are only revealed by #18764.

Right after the merge I will revert those changes in another PR to investigate the root problem.

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by skjnldsv — COMMENTED** [review]
Why not fix them? I think they are actually real issues

**Comment by MorrisJobke** [comment]
> Why not fix them? I think they are actually real issues

Feel free, but I'm not capable of debugging the files app sidebar plugin initialization stuff. As of now this basically hides real CI failures and thus I will remove them as they don't add value at all. 🙈

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Now there are only some tests that fail sometimes 🙈 (files versions for example)

**Comment by MorrisJobke** [comment]
> Right after the merge I will revert those changes in another PR to investigate the root problem.

#21938

**Pull request merged**
