### PR TITLE
Add button disable on submit for login grant

### LINKED ISSUE #33164: [Bug]: OAuth login flow allows users to submit multiple times
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using the OAuth login feature of Nextcloud, after logging in, the user sees a button "grant access". After clicking this button, a spinner is shown, **but the submit button is not disabled**. Therefore, a user could think the button is to be clicked again. 

However, this sends another request to the server and cancels the last one. (normal form submit action) This leads to a failed authentication with the error message "status token does not match".

This has already been reported to be an issue with the following browsers:
Chrome, Chromium (103.0.5060.53), Edge, Safari
It is currently not a problem with Firefox (102.0.1).

### Steps to reproduce

1. Setup the Nextcloud instance for OAuth authentication
2. Start OAuth authentication by visiting the login flow page (instance.com/login/flow/grant...)
3. Click on Login (to get to the next login flow step)
4. You should now see a button with a label like "grant access". For better results, enable throttling in devtools
5. Hit the "grant access" button multiple times. Be fast enough to click it at least once while the server is still processing your first click.
6. You should be greeted with an error screen

### Expected behavior

The submit button should be disabled, so the user can't click it multiple times.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - activity: 2.15.0
  - apporder: 0.15.0
  - calendar: 3.3.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - deck: 1.6.1
  - external: 3.10.2
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - forms: 2.5.0
  - login_notes: 1.0.4
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.14.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - terms_of_service: 1.9.3
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_email: 2.4.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.13.0
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - accessibility: 1.7.0
  - admin_audit
  - announcementcenter: 6.3.0
  - circles: 22.1.1
  - contacts: 4.1.1
  - dashboard: 7.1.0
  - encryption
  - federation: 1.12.0
  - files_external
  - firstrunwizard: 2.11.0
  - nextcloud_announcements: 1.11.0
  - recommendations: 1.1.0
  - user_ldap
  - user_status: 1.1.1
  - weather_status: 1.1.0
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Lukasdoe**
Fixes #33164

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
@Lukasdoe we'll need a signoff on the commit as well, please refer to [these steps](https://github.com/nextcloud/server/pull/33166/checks?check_run_id=7242366761) on how to do that

**Comment by Lukasdoe** [comment]
Commit is signed-off.

**Comment by Lukasdoe** [comment]
@Pytal is there anything else I can do?

**Comment by artonge** [comment]
@Lukasdoe yes, could you rebase, compile and force push ? :)

Something like:

```bash
git rebase origin/master
npm ci
npm run build
git commit --amend
git push --force
```

**Comment by Lukasdoe** [comment]
Done. Build now failing, though. However, I guess that's not because of my change :)

**Comment by Pytal** [comment]
@Lukasdoe does the build still fail after syncing your fork first with the commands below?

```bash
git remote add upstream https://github.com/nextcloud/server.git
git pull --rebase upstream master
npm ci
npm run build
git commit --amend
git push --force
```

**Review by artonge — APPROVED** [review]
I only see unrelated failing CI, looks good to me :)

**Comment by Lukasdoe** [comment]
> @Lukasdoe does the build still fail after syncing your fork first with the commands below?
> 
> ```shell
> git remote add upstream https://github.com/nextcloud/server.git
> git pull --rebase upstream master
> npm ci
> npm run build
> git commit --amend
> git push --force
> ```

These are the exact steps I executed before the last force push^^

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by artonge** [comment]
Thanks for the PR @Lukasdoe !

**Pull request merged**
