### PR TITLE
switch reshares to true (display reshares in the folder/filelist)

### PR DESCRIPTION
**Pull request by ArtificialOwl**
Signed-off-by: Maxence Lange <maxence@nextcloud.com>

### CODE REVIEW

**Comment by daita** [comment]
I find really disturbing that the owner of a shared folder have to open the details of all the file of his folder to check if any of them have be reshared, even after he remove the shares on the folder:

- **Owner** share a folder to **User1**
- **User1** re-share a file from the folder to **User2**
- Owner is browsing the folder he shared to **User1** but can't see the files shared to **User2** until he selected the file and display the Sharing panel.

Meaning that if an owner want to remove all the sharing on a folder, he will need to select all the files of the folder.

**Review by rullzer — APPROVED** [review]
Makes sense to me!

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
But unit tests fail and you should update the mocks :wink

**Comment by schiessle** [comment]
Works and makes absolutely sense! 👍

**Review by schiessle — APPROVED** [review]

**Comment by daita** [comment]
@MorrisJobke mock found and fixed

**Pull request merged**
