### PR TITLE
favicon-touch image corners

### PR DESCRIPTION
**Pull request by elsiehupp**
The default `favicon-touch` renders incorrectly in Firefox:

Screen Shot 2021-01-24 at 3 11 44 AM

(shown on Mac, but also applicable on Linux and iOS)

This is because the `apple-touch-icon` specification (to the extent that it exists) expects the image referenced in `<link rel='apple-touch-icon' href='favicon-touch.png'>` to have squared corners. An icon with rounded corners is only expected by `<link rel='apple-touch-icon-precomposed' href='favicon-touch.png'>`. When a favicon is referenced *without* the `-precomposed`, Apple devices will go ahead and apply the rounded-corner mask to an image with square corners.

Note that the DigitalOcean and NYTimes `apple-touch-icon` images flanking the Nextcloud icon in the above screenshot both have square corners:

[digitalocean](https://cloud.digitalocean.com/apple-touch-icon.png) [nytimes](https://www.nytimes.com/vi-assets/static-assets/apple-touch-icon-28865b72953380a40aa43318108876cb.png)

And, yes, they look fine in Safari (aside from the text wrapping):

Screen Shot 2021-01-24 at 3 38 33 AM

The current recommendation seems to be that icons referenced as `apple-touch-icon` have a resolution of 180px x 180px (the size of the DigitalOcean icon), though previously it was 144px x 144px (the size of the NYTimes icon). Firefox and Chrome on desktop seem to render icons at 192px x 192px, so it might actually be safer to default to that. [Or something](https://realfavicongenerator.net/favicon_compatibility). The `<link rel ...>` tag can actually specify a large set of variations for a wide variety of circumstances.

There are plenty of other mindnumbing subtleties to getting a favicon to render correctly in every possible circumstance, and I am getting my information from [realfavicongenerator.net](https://realfavicongenerator.net/faq). Nextcloud could plausibly integrate the [Real Favicon Generator API ](https://realfavicongenerator.net/api/#favicon-generation)in order to cover all its bases, but that's kind of above my pay grade at the moment, lol.

The changes I've made here are the bare minimum that should (hopefully) make the default Nextcloud favicon render correctly in Firefox (i.e. with the correct corner radius).

<s>Oh, and I apparently neglected to [sign my `git` commits](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md), so... uh... let me know if and how I should fix that. Thanks!</s> The ["Details"](https://github.com/nextcloud/server/pull/25299/checks?check_run_id=1756597019) link explained to me.

### CODE REVIEW

**Comment by elsiehupp** [comment]
One thing I should clarify is that I don't know what `manifest.json` does, and I did not go through the effort of building and testing the cloned repository, so [my change to `manifest.json`](https://github.com/nextcloud/server/commit/7f54eaf00288fa7eed2cfaa3dc9f55a92f717728) is just an educated guess.

**Comment by rullzer** [comment]
Thanks. @jancborchardt and co please have a look.

**Comment by ma12-co** [comment]
Thanks for that @elsiehupp :)

**Review by marcoambrosini — APPROVED** [review]

**Comment by elsiehupp** [comment]
FWIW it might be possible and/or better to have `favicon-touch` be 192px x 192px (for [Firefox, Chrome, and Android](https://realfavicongenerator.net/favicon_compatibility)), but I haven't been able to test anything because, again, I'm running `nextcloud-snap`. Here's a tentative 192px x 192px PNG if you'd like to test it:

favicon-touch


Getting hi-res favicons working in every possible scenario is kind of a rabbit hole, not to mention getting hi-res favicons auto-generated from a single image, like Nextcloud is apparently able to do with custom logos...

**Review by jancborchardt — APPROVED** [review]
Perfect, thanks a lot @elsiehupp! :)

**Comment by jancborchardt** [comment]
By the way @elsiehupp we are always looking for more design contributors! :) If you are interested, maybe some of the design bugs are interesting to check out? https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Adesign+label%3Abug

**Pull request merged**
