### PR TITLE
Focus the input after clicking the "Tags" label

### LINKED ISSUE #2102: When user clicks 'Tags' the cursor should move directly to the tag filter box
Currently:
User wants to filter files by Tags
User clicks on 'Tags'
User has to click in tag filter bar to start typing tags

Expected:
The cursor will be in the tag filter bar, and User can type immediately.

This would save time for User and make workflow smoother. It may not seem much, but when sorting a lot of files this is an important usability point, and makes the software feel slow psychologically.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #2102 

@olantrust Can you test this?

Review @MorrisJobke @jancborchardt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by nickvergessen** [comment]
@jancborchardt review?

**Comment by MorrisJobke** [comment]
@jancborchardt @rullzer Mind to review?

**Comment by jancborchardt** [comment]
@nickvergessen I guess it’s ok … bit strange that directly the giant dropdown opens but also useful.

Just one thing: if you click the »Tags« button again directly, the dropdown _and_ input field should close. Now it’s a two-step process, but should be a toggle.

**Comment by nickvergessen** [comment]
No, that is not possible, just like you can't use anything else anywhere on the page while the dropdown is open.
The next click closes the dropdown anywhere, not just on the "Tags".

So setting back to "please merge"

**Comment by jancborchardt** [comment]
I have to say I’m not sure, it’s a bit overwhelming when you don’t know what’s coming. Autofocus is usually good but in this case it makes a whole dropdown appear.

But might be just me. What do you think @MorrisJobke @nextcloud/designers?

**Comment by MorrisJobke** [comment]
> But might be just me. What do you think @MorrisJobke @nextcloud/designers?

I like it, mostly because I actively clicked on the tags element - and then having a listing pop up is totally fine.

**Comment by ChristophWurst** [comment]
what's the status here? Can we review/merge this?

**Comment by nickvergessen** [comment]
From my POV yes

**Comment by rullzer** [comment]
Lets do this! 👍

**Pull request merged**
