### PR TITLE
Hide but leave the collapse button above link

### PR DESCRIPTION
**Pull request by skjnldsv**
This will greatly improve our retro-compatibility with the new app-navigation guidelines
@nextcloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
cc @BernhardPosselt for the News app and @ChristophWurst @lcalaresu @Gomez for the Mail app could you also check this out?

**Comment by skjnldsv** [comment]
I don't think the mail app is using a collapse button :)

**Comment by skjnldsv** [comment]
Bump? 😭

**Comment by ChristophWurst** [comment]
How can I test this?

**Comment by skjnldsv** [comment]
Let me provide a sample template.

**Comment by skjnldsv** [comment]
Template test: [templatetest.tar.gz](https://github.com/nextcloud/server/files/1352857/templatetest.tar.gz)

You should have 3 menus:
 - First is opening a link but you can collapse the menu with the arrow (thanks to this pr)
 - Second is opening a link by default, so clicking the link nor the arrow will open the menu
 - Third works on the whole entry because no link is processed.

**Comment by ChristophWurst** [comment]
> First is opening a link but you can collapse the menu with the arrow (thanks to this pr)

Tested and confirmed before/after behavior :+1:

> Second is opening a link by default, so clicking the link nor the arrow will open the menu

Both the arrow *and* the text will open the link

> Third works on the whole entry because no link is processed.

Works nicely :+1:

**Review by ChristophWurst — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Sorry, missed this! Looks good :)

**Pull request merged**
