### PR TITLE
Fix star stroke color on hover

### LINKED ISSUE #4872: Background of favorite star border has different color on hover
In the Files list for example, if you hover an entry the border around the favorite star has a different background than the hovered list entry. However the border of the star should be the same tone of grey as for the hover background so it does not appear as a visible border.
image

cc @marcoambrosini @szaimen

### PR DESCRIPTION
**Pull request by marcoambrosini**
* Resolves: https://github.com/nextcloud-libraries/nextcloud-vue/issues/4872

## Summary

**Before**
Screenshot from 2023-11-23 14-54-11

**After**
Screenshot from 2023-11-23 14-53-43

## TODO

- [x] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM from the screenshots

**Review by JuliaKirschenheuter — APPROVED** [review]

**Review by jancborchardt — COMMENTED** [review]
Awesome, looks clean @marcoambrosini :sparkles:

**Pull request merged**
