### PR TITLE
Document updater channel & check for correct PHP version in updater

### PR DESCRIPTION
**Pull request by MorrisJobke**
* see https://github.com/nextcloud/updater/issues/53

cc @rullzer @LukasReschke

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]
LGTM

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
We maybe want to backport this too. 🙈

**Comment by rullzer** [comment]
LGTM

**Pull request merged**
