### PR TITLE
Add SPDX header - batch 14

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Resolves: # more headers
## Summary

last missing app and replaced file ytep icons in alignment with Jan with M3 icons

* files with copyright information: 10689 / 11030
* files with license information: 10672 / 11030

## TODO

- [x] compile
- [x] review and merge

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by blizzz — COMMENTED** [review]
:elephant:

**Review by blizzz — APPROVED** [review]
:elephant:

**Review by szaimen — APPROVED** [review]
🐘

**Pull request merged**
