### PR TITLE
Update operationprogressbar.js

### PR DESCRIPTION
**Pull request by jameslao**
To fix issue #16137

### CODE REVIEW

**Comment by ghjjkbbh** [comment]
---Original---

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
@georgehrke @ChristophWurst @juliushaertl could you review the JS here? Fixes a papercut issue for 17 polishing. :)

**Review by GretaD — APPROVED** [review]
tested and looks good, thank you jameslao

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by dossantg** [comment]
We have the same issue on nextcloud 16.0.3.

Is it possible to add this fix to 16.0.4?

Regards,

**Pull request merged**
