### PR TITLE
Restore the padding on the home icon

### LINKED ISSUE #2079: Breadcrumbs padding error on home folder
After 742ece8b7a054ce16152d721f91936d04b5d22c2
@MorrisJobke 

capture d ecran_2016-11-10_16-51-46
capture d ecran_2016-11-10_17-05-44

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #2079 

@MorrisJobke @skjnldsv

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Also tested with IE11 ;)

**Comment by LukasReschke** [comment]
LGTM

**Comment by skjnldsv** [comment]
👍

**Comment by MorrisJobke** [comment]
issue does not apply to stable10 and stable9

**Pull request merged**
