### PR TITLE
Include "Product Name" in status.php printout

### PR DESCRIPTION
**Pull request by blizzz**
From https://github.com/owncloud/core/pull/25823

please review @nickvergessen @rullzer @LukasReschke

### CODE REVIEW

**Comment by rullzer** [comment]
fine... but why?

**Comment by blizzz** [comment]
Staying in sync is the only half-way reasonable answer. I won't be sad if we just skip it. Or leave it for a while.

**Comment by MorrisJobke** [comment]
Tested and works 👍 

I'm fine with that. The only issue I see here is that the product name could be themed and then isn't useful for apps to determine if it is OC or NC.

**Comment by rullzer** [comment]
LGTM then

**Pull request merged**
