### PR TITLE
compress some images with tinypng.com

### PR DESCRIPTION
**Pull request by rubo77**
Signed-off-by: Ruben Barkow-Kuder <github@r.z11.de>

### CODE REVIEW

**Comment by Dragon988** [comment]
Thank you!

**Comment by rubo77** [comment]
There could be achieved an even better compression using the online tool https://tinypng.com, but that would cause some minor, barely noticable losses in quality.

**Comment by rubo77** [comment]
Those would be the tinified images by tinypng.com:

add-color
background
copy
delete-color
download
favicon
guest_avatar_einstein_32
starred
testimage-wide
touch-comments
touch-core-red
touch-original
touch-original-png
touch-testing-red
ui-icons_1d2d44_256x240
ui-icons_ffd27a_256x240
ui-icons_ffffff_256x240

**Review by rullzer — APPROVED** [review]
Fine by me!

**Review by juliusknorr — APPROVED** [review]
Sure :+1:

**Comment by rubo77** [comment]
I also compressed 3 jpgs, where there occured no extra artefacts

**Review by jancborchardt — APPROVED** [review]
Looks good, thanks!

**Comment by rullzer** [comment]
Could you rebase your changes?

**Comment by rubo77** [comment]
rebas where? I already rebased this morning

**Comment by rullzer** [comment]
Ah the tests fail :S. Will take a look tomorrow

**Comment by rubo77** [comment]
There is also `image-optimization.sh` which was lately improved in #20586, but this is only called on build, not on the original images, maybe we should call this script also on the other images in this repository?

**Pull request merged**
