### PR TITLE
Bump jquery from 3.2 to 3.3

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
nice!

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
So 3.4 is the faulty one :grin:

**Comment by ChristophWurst** [comment]
yep :grinning:

**Comment by ChristophWurst** [comment]
Which is funny because there is no documented breaking change https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/ …

**Pull request merged**
