### PR TITLE
13.0.0 beta 2

### PR DESCRIPTION
**Pull request by MorrisJobke**
Anything crucial that should go into the beta 2? Maybe check https://github.com/nextcloud/server/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+13%22 and then comment here

cc @ChristophWurst @rullzer @schiessle @blizzz @skjnldsv @georgehrke @karlitschek 

### Requested to get into 13 by owner

* [x] #7418 - cache LDAP users properly to reduce requests
* [x] #7115 - fix login flow
* [x] #7249 - flex layout in guests.css (login, update, error pages)
* [x] #7244 - css suffix based on app version
* [x] #7342 - CardDAV convertor check should not be to wide
* [x] #7427 - fix email button color for white themes
* [x] #6590 - Create activities for (un)publishing calendar events 
* [x] #6715 - free/busy handling in calendar
* [x] #6079 - Parse Sabre Exception in OC.Files.Client and file-upload
* [x] #6668 - Remove avatar on user deletion
* [x] #7450 - Catch the errors related to untrusted self signed certificates for federation
* [x] #7431 - app content lists fixes 
* [x] #6637 - Make ContactsStore a public API
* [x] #7453 - Properly detect if fopen fails for txt previews
* [x] ~~#7196 - Add confirmation button to share input~~ moved to 14
* [x] #7458 - Fix unit tests for CalendarManager
* [x] #6884 - Opt out of birthday calendar
* [x] #6830 - Nextcloud 13 is not compatible with newer than php 7.2

### Easy to review

* [x] #6651 - Add api clients for talking to remote clouds 
* [x] #6682 - Fallback to filename based detection if the remote dav server doesn't know the mime type 
* [x] #7313 - Ensure that X-OC-MTime header is an integer with chunked uploads 
* [x] #7324 - don't create sorter instances when none was requested
* [x] #7461 - Set autocomplete on share password input

### 13, but help needed

* [x] ~~#6805 - Can not change encryption directory (@schiessle)~~ moved to 14

### 13 or 14?

* [x] ~~#4528 - Properly decode id from URI~~ moved to 14
* [x] ~~#7363 - Let admin configure default share permissions~~ moved to 14
* [x] ~~#7196 - Add confirmation button to share input~~ moved to 14
* [x] ~~#4530 - Introduce pagination in files-filter report~~ moved to 14

### CODE REVIEW

**Comment by skjnldsv** [comment]
I will push the app content list fix this afternoon l

**Review by rullzer — APPROVED** [review]

**Comment by blizzz** [comment]
I'd like to have #7418 and #7321 included

**Comment by skjnldsv** [comment]
Can we include #7249 and #7431 please?

**Comment by MorrisJobke** [comment]
> Can we include #7249 and #7431 please?

Sure - just find somebody who helps with reviewing #7249 because I already did ;)

**Comment by MorrisJobke** [comment]
I updated the initial post with a list of all PRs that still have the milestone 13 assigned. I would prefer to either get them in or move them to 14 before the beta 2. And afterwards only have pure fixes and also do the branching quite soon. Opinions?

**Comment by MorrisJobke** [comment]
Also maintainers of apps that are close to the server (e2e, talk, ...) should raise their voice if there is stuff to be merged until the beta2. cc @Ivansss @schiessle

**Comment by Ivansss** [comment]
I'm not aware of anything that need to merged in server for Talk.
@danxuliu what about mentions in chat? you were discussing something with @blizzz recently about moving something from comments to server.
I'm happy that #6876 is merged so it can be used in Talk mobile apps 😊

**Comment by danxuliu** [comment]
>  I'm not aware of anything that need to merged in server for Talk.

Some changes may be needed regarding touch screens and gestures, but the code is not ready yet for Talk so there is no need to delay the beta.

>  what about mentions in chat? you were discussing something with @blizzz recently about moving something from comments to server.

Not a showstopper for beta 2; it is just a corner case and a minor detail (if Comments app is disabled and Talk is enabled the formatted mentions show the user name instead of the display name).

**Comment by MorrisJobke** [comment]
> * #6805 - Can not change encryption directory (@schiessle)
> * #4530 - Introduce pagination in files-filter report
> * #6884 - Opt out of birthday calendar

It looks like those three PRs will not make it to 13 and will be moved to 14. cc @georgehrke @schiessle @icewind1991 

I will move them later this evening and have a last look at everything. Thanks to @blizzz and @rullzer for todays review session of all the pending PRs.

**Comment by MorrisJobke** [comment]
Rebased to see if CI complains about the beta 2

**Comment by rullzer** [comment]
CI error seems to be some weird checkout hickup

**Comment by MorrisJobke** [comment]
Let's do it :)

**Pull request merged**
