### PR TITLE
add a way to open the admin settings overview directly

### PR DESCRIPTION
**Pull request by szaimen**
This is best reviewed like this: https://github.com/nextcloud/server/pull/33756/files?diff=unified&w=1

### Motivation

I think this is a good idea and the community seems to agree: https://redd.it/x11gue

Also Jan said that it is fine by him :)

### Screenshot
<details>
<summary>click here</summary>

image

</details>

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=enh/noid/admin-settings-directly \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.130 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looks good! :)

We should also replace the icons with Material Design icons, but separate issue probably.

Then we can also use separate icons for the settings:
- Personal: person
- Admin: settings

**Comment by come-nc** [comment]
But then it should be two separated pages, with each its own menu?

If I understand the current PR both menu entry lead to the same page, just with a different default "tab"?

**Comment by szaimen** [comment]
> If I understand the current PR both menu entry lead to the same page, just with a different default "tab"?

Yes but that already makes a huge positive difference in my personal testing!

**Comment by szaimen** [comment]
> Looks good! :)
> 
> We should also replace the icons with Material Design icons, but separate issue probably.

Yes separate issuey however I could replace the personal settings icon with https://github.com/nextcloud/server/blob/master/apps/settings/img/personal.svg. WDYT?

**Review by CarlSchwan — APPROVED** [review]

**Comment by danxuliu** [comment]
_I visit the admin settings page_ should open the admin settings, not the personal settings of the admin, so I added a fixup commit for that; if the personal settings of the admin need to be opened a new _I visit the personal settings page_ step should be added, but it is not currently needed, as all* the acceptance tests that open the admin settings do that to access an admin-level settings section.

*Except the one in _access-levels_ test, which just needs to open the settings page to check the available panels.

**Comment by szaimen** [comment]
> _I visit the admin settings page_ should open the admin settings, not the personal settings of the admin, so I added a fixup commit for that; if the personal settings of the admin need to be opened a new _I visit the personal settings page_ step should be added, but it is not currently needed, as all* the acceptance tests that open the admin settings do that to access an admin-level settings section.
> 
> *Except the one in _access-levels_ test, which just needs to open the settings page to check the available panels.

fine by me as long as the tests pass :)

BTW, is `/drone/src/tests/acceptance/features/users.feature:48` a flaky test?

**Comment by szaimen** [comment]
> And can you please squash or shall I do it?

done

**Comment by jancborchardt** [comment]
> > Looks good! :)
> > 
> > We should also replace the icons with Material Design icons, but separate issue probably.
> 
> Yes separate issuey however I could replace the personal settings icon with https://github.com/nextcloud/server/blob/master/apps/settings/img/personal.svg. WDYT?

@szaimen yes, that would be a good fix! :)

**Comment by szaimen** [comment]
> @szaimen yes, that would be a good fix! :)

done :)

**Comment by danxuliu** [comment]
> BTW, is `/drone/src/tests/acceptance/features/users.feature:48` a flaky test?

It seems so. Unfortunately I do not see why, and I locally run it 50 times and all of them passed, so... something for later ;-)
 
> > And can you please squash or shall I do it?
>
> Done

Thanks :-)

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
