### PR TITLE
fix(settings): Hide forbidden UI elements for group managers

### LINKED ISSUE #24749: Improve user management for group admins
If I'm a group admin the user management looks like this:

image

But if I try to add a group I get this error message:

image

The reason is obvious. Group admins can't create new groups. But in this case we should hide the "Add group" button so that the user not even try it.

On the other hand if I try to add a user, the interface looks like this:

image

If I try to create a user and don't chose a group I get an error that I have to select a group. Would be nice of the group would be already pre-filled.

### LINKED ISSUE #46778: [Bug]: accounts -> recently active visible for group admins, but xhr request returns 403
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

image

```json

{
	"meta": {
		"status": "failure",
		"statuscode": 403,
		"message": "Logged in account must be an admin, a sub admin or gotten special right to access this setting"
	}
}
```

### Steps to reproduce

1. Login as group admin (a user that is allowed to manage groups)
2. Go to accounts
3. Click on Recently active
4. :boom: 

### Expected behavior

If the section is not available for a group admin, then the menu item should be hidden.

### Additional info

https://github.com/nextcloud/server/blob/87dc0614d703536843b878808a2721899df798b4/apps/provisioning_api/lib/Controller/UsersController.php#L304-L305

cc @sorbaugh @Pytal

### LINKED ISSUE #46831: [Bug]: accounts -> add new group visible for group admin, but not allowed
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The button, to create a new group, is shown for group admins despite they are not allowed to create new groups.

[Screencast from 2024-07-28 19-40-39.webm](https://github.com/user-attachments/assets/354a0d57-3df1-4cf6-a120-51f5ad751433)

### Steps to reproduce

1. Login as group admin
2. Visit accounts
3. Create a new group

### Expected behavior

Hide the button if operation is not possible anyway. 

cc @sorbaugh  @Pytal

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/24749
* Resolves: https://github.com/nextcloud/server/issues/46831
* Resolves: https://github.com/nextcloud/server/issues/46778

## Summary

1. The "recent" accounts API only works for admin and delegated admin -> hide for group managers
2. group managers can not create new groups -> Hide the UI to add a new group for them
3. Accounts created by group managers require one of the groups, which is managed by the group manager, assigned. So if the group manager only manages a single group, we should pre-select that group.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by kesselb** [comment]
> line managers

You mean group admins, right?

**Review by kesselb — APPROVED** [review]
Thank you

It fixes the issues I reported :pray:

**Comment by kesselb** [comment]
I've run into another issue while testing your pr. 

There's a xhr request for the "manager". However the "manager" is not necessarily a member of the current group and therefore the xhr request for the manager fails if the group manager cannot manage the line manager. 



[Screencast from 2024-08-30 15-51-30.webm](https://github.com/user-attachments/assets/2b49e522-c739-4ced-84f2-4c49107e9cf9)

I'm seeing the same problem on main. Do you want me to log a fresh issue or still in scope for this issue/pr?

**Comment by susnux** [comment]
> You mean group admins, right?

I think they were renamed lately to `line mangers` as the proper term

> I'm seeing the same problem on main. Do you want me to log a fresh issue or still in scope for this issue/pr?

I would prefer a fresh issue to track that :)

**Comment by kesselb** [comment]
> I think they were renamed lately to line mangers as the proper term


image

I see both, the group admin if you are a manager for a group and the line manager the sab / orgchart?

**Comment by kesselb** [comment]
> I would prefer a fresh issue to track that :)

There you go https://github.com/nextcloud/server/issues/47642

**Comment by susnux** [comment]
> I see both, the group admin if you are a manager for a group and the line manager the sab / orgchart?

Well I confused myself :see_no_evil:

**Review by Pytal — APPROVED** [review]

**Pull request merged**
