### PR TITLE
Move legacy classes from PSR0 to PSR4

### PR DESCRIPTION
**Pull request by ChristophWurst**
Latest composer complains that these files won't be loaded with composer v2, so I guess it's time to migrate them.

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
When is the :fire: festival?

**Comment by ChristophWurst** [comment]
What do you want to :fire:? :)

**Review by juliusknorr — APPROVED** [review]

**Comment by ChristophWurst** [comment]
`Test\TemplateFunctionsTest` fails

**Comment by nickvergessen** [comment]
> What do you want to 🔥? :)

legacy/

**Pull request merged**
