### PR TITLE
DirectController: Let users choose the link expiration time

### PR DESCRIPTION
**Pull request by iscle**
Previously the expiration time for direct download links was hardcoded to 8 hours (although on the documentation 24 hours is stated).

Right now, a new optional body parameter can be added, "expirationTime". In case it is set, then that value will be used as the duration (in seconds) of the direct download link, else he default value of 8 hours is used.

### CODE REVIEW

**Comment by rullzer** [comment]
> although on the documentation 24 hours is stated).

ai. Could you shoot in a PR there.

what is the reason for having this time configurable?
I would in case case go for a max timeout. Else this could expose your files for a loooooong time

**Comment by Iscle** [comment]
We're using Nextcloud to host some files which can be downloaded by our fourm (discourse) users. Since they don't have an account on our Nextcloud storage, and we don't want hot-linking in other pages, we are generating individual links that we want to expire in 2 hours.

The original implementation left it for 8 hours (although, as stated before, we thought it was 24 hours before looking at the code), which was too long for us.

Since I made this change, and I don't want to keep having to build Nextcloud locally, I thought it would be a good idea to merge it to the official version so that other users can also take advantage of it.

**Comment by rullzer** [comment]
OK fair enough :)
Could you add in a check that the maximum time is not exceeded?

**Comment by Iscle** [comment]
Of course! 
What should I use as the maximum value?

I think 24h is a good value, as that's what was stated before in the documentation (my correction was merged today).
This way, the functionality would be like this:
No value => Defaults to 8h
Custom value => If bigger than 24h, set it to 24h, else, use the given value.

**Comment by Iscle** [comment]
I ended up throwing an exception if expirationTime is not bigger than 0 or if it is bigger than 24h.

I don't know what would the behaviour be in case a negative value or 0 gets passed, so the best thing is to check for it. 0 seconds wouldn't be of much use anyway.

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Fine with me 👍 

Please add a PR to the documentation at https://docs.nextcloud.com/server/20/developer_manual/client_apis/OCS/ocs-api-overview.html#direct-download

**Pull request merged**
