### PR TITLE
fix setupcheck test

### PR DESCRIPTION
**Pull request by szaimen**
Follow-up to https://github.com/nextcloud/server/pull/38915

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by susnux** [comment]
1. If it is just "recommended" why it is an error?
2. HSTS is not required for "copy to clipboard" and "service workers", just HTTPS for connection (or wss) is enough, so this message might be misleading?

**Comment by szaimen** [comment]
You are right. I adjusted the wrong place.

**Comment by szaimen** [comment]
See https://github.com/nextcloud/server/pull/39014

**Pull request closed without merging**
