### PR TITLE
fix: Always apply fullscreen styling to sidebar

### PR DESCRIPTION
**Pull request by juliusknorr**
## Summary

Make sure that the full screen styling is always applied to the sidebar even if the loading hasn't finished yet.

Fixes a small UI glitch where a small space was left between the viewer modal and the sidebar.

This is a different approach I came up before stumbling over https://github.com/nextcloud/viewer/pull/1711 so I'd appreciate feedback especially from @ShGKme on this. It seems to also cover the drawback that the viewer PR has.

### Before

Screenshot 2023-07-13 at 22 15 23

### After

https://github.com/nextcloud/server/assets/3404133/69136fa3-3a6c-4006-ad8f-501f6c1a44fb

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ShGKme — COMMENTED** [review]
I like this solution!

I didn't finish that PR in viewer because didn't find a good solution from the viewer side but didn't want to modify the server part :D
But this is definitely better.

---

Unfortunately, it still doesn't work in one case:
1. Open files
2. Open sidebar
3. Open viewer

image

It works in combination with my PR in viewer, but with a 0.2s transition...

**Review by ShGKme — APPROVED** [review]
Approved, regardless viewer, IMO it is better to have correct fullscreen state in all sidebar states in files.

Also, I'd consider to make fullscreen mode `NcAppSidebar` component feature, so we would be able to use it in any apps and have better sidebar integration in apps (for example, having shared fullscreen / resize events).

**Review by jancborchardt — COMMENTED** [review]
@juliushaertl in your screen recording the viewer and sidebar open and close visibly at slightly different times when clicking the close "x" and the file name respectively. Is this something new based on the approach? (Maybe it’s also just because of the screen recording.)

**Review by jancborchardt — APPROVED** [review]
Looks good design-wise.

**Pull request merged**
