### PR TITLE
Users management enhancements and fixes

### LINKED ISSUE #13953: User management: new group field should have focus after clicking 'add group'
When in the user management an admin clicks on `Add group` the input field should be selected. Currently the admin needs to select this manually.

cc: @skjnldsv

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #13953

- **Fix**: when removing the last user of a group, there was no message stating that the list is empty with an `emptycontent` warning
- **Fix**: when adding a user to an empty group, the `emptycontent` message was still present
- **Enhancement**: when adding a group, this one gets automatically selected
- **Fix**: when creating a new user with a selected group (on the app-navigation), the form get reset but the group get reset too (it is supposed to be the same as the navigation-selected one)
- **Fix**: when users list empty, the app-navigation showed a loading icon

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Works as advertised

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Webpack build fails and the diff also seems to be a bit big. Maybe it's built in the dev flavor?

**Comment by skjnldsv** [comment]
@MorrisJobke no idea! That is weird indeed! Maybe webpack decided to create a new vendor chunk and therefore have a bigger set of code? :thinking:

**Comment by rullzer** [comment]
@skjnldsv maybe you have a left over node_modules somewhere.
Anyways my rebuild seems to have fixed it. Merge it :D :rocket:

**Pull request merged**
