### PR TITLE
fix(config): Avoid error messages for restricted opcache API

### LINKED ISSUE #47562: [Bug]: Warning: Zend OPcache API is restricted by "restrict_api" configuration directive
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dear Nextcloud Support,
we have tried to install the Nextcloud Versions 28 and 29 on PHP 8.2.22 using the installation script "https://download.nextcloud.com/server/installer/setup-nextcloud.php" and both fail with the same error before the main install dialog appears where we can input the database connection settings:

```
Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /www/doc/www.data-business.de/www/cloud/lib/private/Config.php on line 218
Config file has leading content, please remove everything before "<?php" in config.php
Fatal error: Uncaught Error: Typed static property OC::$server must not be accessed before initialization in /www/doc/www.data-business.de/www/cloud/index.php:98 Stack trace: #0 {main} thrown in /www/doc/www.data-business.de/www/cloud/index.php on line 98
```

The Nextcloud Version 27.1.11 works on PHP 8.2.22 without any issues, however when we try to upgrade to 28 after a successfull install it fails with the same error above.

Our hosting provider has a setting restrict_api for all customers and is not willing to change this: 
`opcache.restrict_api	/www/doc/local`

When we comment out the line /www/cloud/lib/private/Config.php on line 218 [//opcache_invalidate($file, false);] it works.

Best regards

### Steps to reproduce

1. Install Nextcloud 28 or 29 on PHP 8.2.22 where opcache.restrict_api is set to a restricted folder
2. Or Upgrade from Nextcloud 27 to 28
3.

### Expected behavior

Fresh install should work 
Upgrade for 27 to 28 should work

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: #47562 

## Summary

Make changes recently added via #44230 match #8188 to avoid failures in restricted hosting environments.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by solracsf — APPROVED** [review]

**Review by pulsejet — APPROVED** [review]

**Review by susnux — APPROVED** [review]
Looks good. 

<details>(Should probably get the label: Stupid hosting providers 😅)</details>

**Comment by joshtrichards** [comment]
/backport 3e434bcebfdeacf18daf3f0a5757098c0ea45630 to stable30

**Pull request merged**
