### PR TITLE
Allow dir-listing also when one child is blocked by access control

### PR DESCRIPTION
**Pull request by nickvergessen**
Regression from https://github.com/nextcloud/server/issues/4524
Fix https://github.com/nextcloud/files_accesscontrol/issues/65

### CODE REVIEW

**Comment by alterratz** [comment]
OK. 41b185baedd8f992b4ee55d15469b1732f28669e fixes the issue.
However, when an unauthorized user clicks a restricted folder the directory changes to his home directory, which not a very intuitive behavior at least. It would be nicer if this behaviour could be changed to: do not do anything at all (and eventually popup a message box "restricted....") or display an empty folder stub with some hint that the access has been denied.

**Comment by icewind1991** [comment]
please dont leave commented out code lying around

**Comment by nickvergessen** [comment]
> please dont leave commented out code lying around

I will add a comment to it.
Would like to keep the code to know that we had it and what it caused...

**Review by JiriMON — APPROVED** [review]
Works for fixing nextcloud/files_accesscontrol#65

**Comment by alterratz** [comment]
The pull request fixes the issue but it open an other can of worms:
file access control can be removed if user has access to parent folder #66
(which is for me a grave issue since it effectively disables access control based on the FAC application)

**Comment by nickvergessen** [comment]
@MorrisJobke @icewind1991 please review as this needs backporting for 12.0.1

**Review by MorrisJobke — APPROVED** [review]

**Comment by icewind1991** [comment]
Instead of not throwing the exception it seems better to me to handle the exception in folder listing and hide the problematic entry

**Comment by nickvergessen** [comment]
That's bad, as it would cause sync clients to delete the file?

**Comment by nickvergessen** [comment]
Lets just revert the change from vincent which caused this by accident. Our codebase worked fine without it

**Comment by nickvergessen** [comment]
there are 2 +1 and robin +1ed the comment, so merging

**Pull request merged**
