### PR TITLE
Update Admin.php

### PR DESCRIPTION
**Pull request by praveenraonp**
Modified the theming error message grammar , this fix is related to Issue #1107

### CODE REVIEW

**Comment by rullzer** [comment]
Thanks!

It seems we have very strict unit tests here: https://github.com/nextcloud/server/blob/master/apps/theming/tests/Settings/AdminTest.php#L115

Could you update that one as well so the tests pass :)

**Comment by iamfool** [comment]
@rullzer   yes I have made the changes , thanks for guiding me through :)  

This is my first contribution to open source community. I know its extremely simple fix but feeling very excited :D

**Comment by rullzer** [comment]
:+1: 

You have to start out small. Lets hope it is the first for many to come :smile: 
Feel free to join our irc channel #nextcloud-dev on freenode or join the [forums](https://help.nextcloud.com)

**Comment by LukasReschke** [comment]
Thanks a lot for your contribution, @iamfool 🚀 🎉 🎈 👍

**Pull request merged**
