### PR TITLE
Set the contactsmenu height without min calculation

### PR DESCRIPTION
**Pull request by juliusknorr**
Fix for scss tests and browser compatibility

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
This is getting complicated ^^

**Comment by juliushaertl** [comment]
> This is getting complicated ^^

We could just use flexbox (which would make the css a lot simpler), but that would require more work as the parent container always gets a `display: block` due to the popover menu handling.

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Review by JanDragon — APPROVED** [review]
👍

**Pull request merged**
