### PR TITLE
Clear backupcode reminder when no 2fa

### LINKED ISSUE #14125: Two factor backup code notifications keep coming back even though enforcing is disabled
### Steps to reproduce
1. After upgrade to 15, I enforced TOTP for the admin group. Maybe I did a mistake, because it was suddenly active for everyone
2. Switched of forced TOTP
3. Deleted the notifications manually from the oc_notifications table

### Expected behaviour
After switching off forced TOTP, the notifications should go away.
At least after deleting them from oc_notifications, there should be no more recurring notifications
### Actual behaviour
With each upgrade of Nextcloud, the notifications somehow come back and I have to manually delete them again from oc_notifications, because they really irritate the users.

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Nginx 1.14.0 
**Database:**
Mariadb 1:10.1.34
**PHP version:**
7.2 FPM 7.2.10

**Version:** (see admin page)
1.5.0.4

**Updated from an older version or fresh install:**
updated

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - deck: 0.5.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ocsms: 2.1.1
  - password_policy: 1.5.0
  - piwik: 0.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.2.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - social: 0.1.3
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_admin: 0.2.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - external
  - files_downloadactivity
  - files_external
  - grauphel
  - polls
  - user_external
  - user_ldap`

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "cron.lockfile.location": "\/var\/www\/chrooted\/jrweb\/data\/ocfiles\/",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "PLAIN",
        "trusted_domains": [
            "cloud.enip.eu",
            "owncloud.uferwerk.org",
            "owncloud.rohr.org",
            "owncloud.drillisch.info",
            "cloud.uferwerk.org",
            "cloud.rohr.org",
            "cloud.infoe.de",
            "cloud.drillisch.info"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "loglevel": 2,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": false,
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/cloud.rohr.org",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
#### Client configuration
(affects all clients)

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #14125

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Review by ChristophWurst — APPROVED** [review]
Looks good!

**Comment by ChristophWurst** [comment]
We should backport this to 15

**Pull request merged**
