### PR TITLE
Support Tencentcloud COS Object Storage as Primary Storage

### PR DESCRIPTION
**Pull request by hankzzhang**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@rullzer @icewind1991 Is this something we want to integrate in the server or is there a way to ship this inside an app? See also the needed 3rdparty update: nextcloud/3rdparty#489

**Comment by rullzer** [comment]
I don't think we can ship it as app right now. BUt I really would avoid adding more to server itself. As it will force us to maintain it forever. So I'd rather word on making it possible for an app to provide it.

**Comment by kesselb** [comment]
> So I'd rather word on making it possible for an app to provide it.

That seems to be rather low on the priority list 😟 I remember a similar discussion a while ago with a pull request for backblaze B2. I neither use b2 or tencent but would be nice to have the functionality to use different providers for object store as well.

**Comment by rullzer** [comment]
Yeah. It is all a matter of priorities. The problem is that once it is in server we have to keep supporting it. And there is only so many hours in a week. So we have to make choices.

**Comment by kesselb** [comment]
@rullzer it's also a quite complex topic to offer object store implementations via the app store. 

> Tencent Cloud Object Storage (COS) is a distributed storage service offered by Tencent Cloud for unstructured data and accessible via HTTP/HTTPS protocols. COS provides a web-based management interface, multilingual SDK as well as command-line and graphical tools and **is fully compatible with S3's API**, allowing direct access to community tools and plugins with ease.

_taken from: https://intl.cloud.tencent.com/product/cos_

@hankzzhang would the S3 API work for you?

**Comment by hankzzhang** [comment]
> @rullzer it's also a quite complex topic to offer object store implementations via the app store.
> 
> > Tencent Cloud Object Storage (COS) is a distributed storage service offered by Tencent Cloud for unstructured data and accessible via HTTP/HTTPS protocols. COS provides a web-based management interface, multilingual SDK as well as command-line and graphical tools and **is fully compatible with S3's API**, allowing direct access to community tools and plugins with ease.
> 
> _taken from: https://intl.cloud.tencent.com/product/cos_
> 
> @hankzzhang would the S3 API work for you?

yeah

**Pull request closed without merging**
