### PR TITLE
Rename “Server settings”

### LINKED ISSUE #4587: Server settings should be renamed to General or Overview
All sections are Server settings ... I think **General** or **Overview** is the better wording here 🤔 

bildschirmfoto 2017-04-28 um 21 57 48

@nickvergessen @jancborchardt

### PR DESCRIPTION
**Pull request by MariusBluem**
fixes #4587

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by blizzz** [comment]
Imho Overview is misleading. It does not give an overview about the admin settings, but is specifically about the server. "Basic settings" or "General settings" if you want…

**Comment by MariusBluem** [comment]
> Imho Overview is misleading. It does not give an overview about the admin settings, but is specifically about the server. "Basic settings" or "General settings" if you want…

I thought about the wordings **Overview** and **Gerneral** 😅 
On the Server settings page are not that much settings, that we can talk about ... well ... settings 😜 

Overview because of: It gives you an overview about whether you have configured your instance correctly (Setup & Security warnings"), information on the version and the ability to update. The cron-settings are a bit outstanding here - I thought about moving them to "Additional settings", but the red "your cron is not up and running" lamp might also be interesting if you are going to admin page and your server does not behave as you expect.

**Comment by juliushaertl** [comment]
General settings sounds right to me. 

@MariusBluem Unit tests need some adjustments too. :wink:

**Comment by MariusBluem** [comment]
> Unit tests need some adjustments too. 😉

Whuuuut 😱

**Comment by blizzz** [comment]
@MariusBluem in /drone/src/github.com/nextcloud/server/tests/lib/Settings/ManagerTest.php (``testGetAdminSections()``) and /drone/src/github.com/nextcloud/server/tests/lib/Settings/ManagerTest.php (``testGetAdminSectionsEmptySection()``).

**Review by jancborchardt — CHANGES_REQUESTED** [review]
@MariusBluem can you call it »Basic settings« to be fitting with »Additional settings« down below?

(Also best squash it to one commit ;)

**Comment by MariusBluem** [comment]
See #4603

**Pull request closed without merging**
