### PR TITLE
Clarify `preview_max_filesize_image` behavior

### LINKED ISSUE #30220: Image file size bigger than `preview_max_filesize_image` won't display
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
```
'preview_max_filesize_image' => 50,
```
> max file size for generating image previews with imagegd (default behavior) If the image is bigger, it’ll try other preview generators, but will most likely show the default mimetype icon. Set to -1 for no limit.

If I upload an image bigger than 50 Mo, the thumbnail is indeed not generated and a generic icon is displayed.

But when I click on that image, I have an error saying "Error loading test.jpg".

The image is good. I checked the file info and size between my computer and the server, and both are identical.

If I set the option preview_max_filesize_image to a bigger size than the image, the thumbnail is created and the image is correctly displayed when I click on it.

**Expected behavior**

I expected to have a generic icon for images bigger than preview_max_filesize_image value, but clicking on the image should open and display the image, not showing an error msg.

Did I misanderstood the purpose of this option and it's a max-file-size image you accept to display?
For me, it's only about the preview icon, not the image itself.

If indeed I misanderstood the option, at least, the error message should be clearer, like "This image is too big to be displayed".

**Screenshots**
 
Capture d’écran de 2021-12-11 15-19-27

### Server configuration

<details>

**Operating system:**

Debian bullseye

**Web server:**

nginx v1.18.0-6.1 (behind haproxy v2.2.9-2+deb11u2)

**Database:**

mariadb-server-10.5 v1:10.5.12-0+deb11u1

**PHP version:**

php8.0 v8.0.13-1+0~20211122.27+debian10~1.gbp1675bc

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud v22.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh install with v22.2 and 1 update to v22.2.3.

**Where did you install Nextcloud from:**

http://apt.jurisic.org/debian bullseye

**Signing status:**

<details>

The failed integrity for the 4 files in Activity appeared after the update to v22.2.3.
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- activity
	- EXTRA_FILE
		- l10n/ta.js
		- l10n/ug.json
		- l10n/ta.json
		- l10n/ug.js

Raw output
==========
Array
(
    [activity] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [l10n/ta.js] => Array
                        (
                            [expected] => 
                            [current] => a868738d9ee40b83f7ce64de8811231c15e257633ce3fecc871f95f113ad6afd6a765a503b01eaa9cb19ce801adfa080464404f2bc2de532d7194de87fb19677
                        )

                    [l10n/ug.json] => Array
                        (
                            [expected] => 
                            [current] => f8c23504c2f924518ff872a48c4d54e427805feb9fe1c6b91889252ce55829db55ef31c2c3d579094eb8ae78bbb8ba0dddf9983ab2ca9216c2c75fd9d48225b2
                        )

                    [l10n/ta.json] => Array
                        (
                            [expected] => 
                            [current] => c061ca61d1012a7c8ae1cff66b7161171e09fa3a932602d5eaf94643f2d63862b696d60f4ce0bc198c6180a44e05701f5a068a38e4a8492e8d6080894181e103
                        )

                    [l10n/ug.js] => Array
                        (
                            [expected] => 
                            [current] => b9028c713a8b2d8895bb0771236aa991cc6d9c1da4018abad098b86df0cff0a454550f15611de038f497782dda0ac67c338a6bee8e34ce2e5b82cfb918cf36b0
                        )

                )

        )
)
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - apporder: 0.13.0
  - bookmarks: 10.0.2
  - bruteforcesettings: 2.2.0 
  - calendar: 3.0.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.6
  - cospend: 1.4.3
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.3.1
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - lookup_server_connector: 1.10.0
  - notes: 4.2.0
  - oauth2: 1.10.0
  - oidc_login: 2.1.0
  - photos: 1.4.0
  - polls: 3.3.0
  - provisioning_api: 1.12.0
  - richdocuments: 4.2.3
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - twofactor_backupcodes: 1.11.0
  - user_external: 2.1.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
```

</details>

**Nextcloud configuration:**

<details>

<summary>Config report</summary>

```
{
    "system": {
        "trusted_domains": [  
            "cloud.mydomain.tld" 
        ],
        "activity_expire_days": 180,
        "appstoreenabled": true,
        "appstore.experimental.enabled": false,
        "auth.bruteforce.protection.enabled": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "6033",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "default_language": "fr",
        "default_phone_region": "be",
        "htaccess.RewriteBase": "\/",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/nextcloud.log",
        "logdateformat": "F d, Y H:i:s",
        "loglevel": 2,
        "log_type": "file",   
        "logtimezone": "Europe\/Brussels",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpport": 25,  
        "maintenance": false, 
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "minimum.supported.desktop.version": "2.1.0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_max_filesize_image": 15,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "secret": "***REMOVED SENSITIVE VALUE***",
        "simpleSignUpLink.shown": false,
        "trashbin_retention_obligation": "60, 90",
        "updatechecker": false,
        "upgrade.disable-web": "true",
        "version": "22.2.3.0",
        "versions_retention_obligation": "60, 90",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.tld",
        "theme": "nubo",
        "overwritehost": "cloud.mydomain.tld",
        "overwriteprotocol": "https",
        "allow_user_to_change_display_name": false,
        "lost_password_link": "disabled",
        "oidc_login_provider_url": "https:\/\/auth.mydomain.tld",
        "oidc_login_client_id": "nextcloud",
        "oidc_login_client_secret": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_auto_redirect": true,
        "oidc_login_logout_url": "https:\/\/auth.mydomain.tld\/",
        "oidc_login_hide_password_form": true,
        "oidc_login_attributes": {
            "id": "sub",
            "name": "name",
            "mail": "email",
            "quota": "nextCloudQuota",
            "groups": "groupsNc",
            "is_admin": "admin_bool"
        },
        "oidc_login_end_session_redirect": true,
        "oidc_login_default_group": "",
        "oidc_login_use_external_storage": true,
        "oidc_login_scope": "email profile openid",
        "oidc_login_proxy_ldap": false,
        "oidc_login_disable_registration": false,
        "oidc_login_redir_fallback": false,
        "oidc_login_tls_verify": true,
        "oidc_login_default_quota": "10737418240",
        "oidc_create_groups": true,
        "oidc_login_webdav_enabled": true,
        "oidc_login_public_key_caching_time": 86400,
        "oidc_login_min_time_between_jwks_requests": 10,
        "oidc_login_well_known_caching_time": 86400
    }
}
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Webdav to access address books from Roundcube.

</details>

### Client configuration

<details>

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - Browser FF v81.0 (64 bits)
 - Client Version  3.3.5
 
But same problems with various Os (Ubuntu / Windows).

</details>

### Logs

<details>

#### Browser log

<details>

<summary>Browser log</summary>

a) The javascript console log
```
GET https://cloud.mydomain.tld/core/preview?fileId=175119&x=1680&y=1050&a=true       [HTTP/2 404 Not Found 95ms]

Error loading /test.jpg 
error { target: img.viewer__file.viewer__file--active, isTrusted: true, srcElement: img.viewer__file.viewer__file--active, currentTarget: img.viewer__file.viewer__file--active, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
```

b) The network log (HAR export)
```
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "81.0"
    },
    "browser": {
      "name": "Firefox",
      "version": "81.0"
    },
    "pages": [
      {
        "startedDateTime": "2021-12-11T16:11:42.491+01:00",
        "id": "page_4",
        "title": "Files - NextCloud",
        "pageTimings": {
          "onContentLoad": -1,
          "onLoad": -1
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_4",
        "startedDateTime": "2021-12-11T16:11:42.491+01:00",
        "request": {
          "bodySize": 661,
          "method": "PROPFIND",
          "url": "https://cloud.mydomain.tld/remote.php/dav/files/userX/test.jpg",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "Host",
              "value": "cloud.mydomain.tld"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
            },
            {
              "name": "Accept",
              "value": "text/plain"
            },
            {
              "name": "Accept-Language",
              "value": "fr-BE,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "requesttoken",
              "value": "reQ5AyS7LULTrBEAPcy08sIdhoXIsdw3ykJa8hIM=:3LNhQmD3SCeDwydveqLgtRSxhN0sZRGKn47mN1sU="
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            },
            {
              "name": "Depth",
              "value": "0"
            },
            {
              "name": "Content-Type",
              "value": "text/plain;charset=UTF-8"
            },
            {
              "name": "Content-Length",
              "value": "661"
            },
            {
              "name": "Origin",
              "value": "https://cloud.mydomain.tld"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Cookie",
              "value": "oc_sessionPassphrase=xxxxx; PHPSESSID=yyyyy; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; lemonldap=zzzzz"
            },
            {
              "name": "TE",
              "value": "Trailers"
            }
          ],
          "cookies": [
            {
              "name": "oc_sessionPassphrase",
              "value": "xxxxx"
            },
            {
              "name": "PHPSESSID",
              "value": "yyyyy"
            },
            {
              "name": "__Host-nc_sameSiteCookielax",
              "value": "true"
            },
            {
              "name": "__Host-nc_sameSiteCookiestrict",
              "value": "true"
            },
            {
              "name": "lemonldap",
              "value": "zzzzz"
            }
          ],
          "queryString": [],
          "headersSize": 910,
          "postData": {
            "mimeType": "text/plain;charset=UTF-8",
            "params": [],
            "text": "<?xml version=\"1.0\"?>\n\t\t\t<d:propfind  xmlns:d=\"DAV:\"\n\t\t\t\txmlns:oc=\"http://owncloud.org/ns\"\n\t\t\t\txmlns:nc=\"http://nextcloud.org/ns\"\n\t\t\t\txmlns:ocs=\"http://open-collaboration-services.org/ns\">\n\t\t\t\t<d:prop>\n\t\t\t\t\t<d:getlastmodified />\n\t\t\t\t\t<d:getetag />\n\t\t\t\t\t<d:getcontenttype />\n\t\t\t\t\t<d:resourcetype />\n\t\t\t\t\t<oc:fileid />\n\t\t\t\t\t<oc:permissions />\n\t\t\t\t\t<oc:size />\n\t\t\t\t\t<d:getcontentlength />\n\t\t\t\t\t<nc:has-preview />\n\t\t\t\t\t<nc:mount-type />\n\t\t\t\t\t<nc:is-encrypted />\n\t\t\t\t\t<ocs:share-permissions />\n\t\t\t\t\t<oc:tags />\n\t\t\t\t\t<oc:favorite />\n\t\t\t\t\t<oc:comments-unread />\n\t\t\t\t\t<oc:owner-id />\n\t\t\t\t\t<oc:owner-display-name />\n\t\t\t\t\t<oc:share-types />\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>"
          }
        },
        "response": {
          "status": 207,
          "statusText": "Multi-Status",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "server",
              "value": "nginx"
            },
            {
              "name": "date",
              "value": "Sat, 11 Dec 2021 15:11:42 GMT"
            },
            {
              "name": "content-type",
              "value": "application/xml; charset=utf-8"
            },
            {
              "name": "expires",
              "value": "Thu, 19 Nov 1981 08:52:00 GMT"
            },
            {
              "name": "cache-control",
              "value": "no-store, no-cache, must-revalidate"
            },
            {
              "name": "pragma",
              "value": "no-cache"
            },
            {
              "name": "referrer-policy",
              "value": "no-referrer"
            },
            {
              "name": "x-content-type-options",
              "value": "nosniff"
            },
            {
              "name": "x-download-options",
              "value": "noopen"
            },
            {
              "name": "x-frame-options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "x-permitted-cross-domain-policies",
              "value": "none"
            },
            {
              "name": "x-robots-tag",
              "value": "none"
            },
            {
              "name": "x-xss-protection",
              "value": "1; mode=block"
            },
            {
              "name": "content-security-policy",
              "value": "default-src 'none';"
            },
            {
              "name": "vary",
              "value": "Brief,Prefer"
            },
            {
              "name": "dav",
              "value": "1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, nc-calendar-search, nc-enable-birthday-calendar"
            },
            {
              "name": "content-encoding",
              "value": "gzip"
            },
            {
              "name": "X-Firefox-Spdy",
              "value": "h2"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/xml; charset=utf-8",
            "size": 1137,
            "text": "<?xml version=\"1.0\"?>\n<d:multistatus xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\" xmlns:oc=\"http://owncloud.org/ns\" xmlns:nc=\"http://nextcloud.org/ns\"><d:response><d:href>/remote.php/dav/files/userX/test.jpg</d:href><d:propstat><d:prop><d:getlastmodified>Sat, 11 Dec 2021 14:16:43 GMT</d:getlastmodified><d:getetag>&quot;b5903a17ae640051ea675e880e2&quot;</d:getetag><d:getcontenttype>image/jpeg</d:getcontenttype><d:resourcetype/><oc:fileid>175119</oc:fileid><oc:permissions>RGDNVW</oc:permissions><oc:size>17878139</oc:size><d:getcontentlength>17878139</d:getcontentlength><nc:has-preview>true</nc:has-preview><nc:mount-type></nc:mount-type><x1:share-permissions xmlns:x1=\"http://open-collaboration-services.org/ns\">19</x1:share-permissions><oc:tags/><oc:favorite>0</oc:favorite><oc:comments-unread>0</oc:comments-unread><oc:owner-id>userX</oc:owner-id><oc:owner-display-name>User X</oc:owner-display-name><oc:share-types/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><nc:is-encrypted/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>\n"
          },
          "redirectURL": "",
          "headersSize": 693,
          "bodySize": 1253
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 91,
          "receive": 0
        },
        "time": 91,
        "_securityState": "secure",
        "serverIPAddress": "11.22.33.44",
        "connection": "443"
      },
      {
        "pageref": "page_4",
        "startedDateTime": "2021-12-11T16:11:43.999+01:00",
        "request": {
          "bodySize": 661,
          "method": "PROPFIND",
          "url": "https://cloud.mydomain.tld/remote.php/dav/files/userX/",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "Host",
              "value": "cloud.mydomain.tld"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
            },
            {
              "name": "Accept",
              "value": "text/plain"
            },
            {
              "name": "Accept-Language",
              "value": "fr-BE,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "requesttoken",
              "value": "reQ5AyS7LULTrBEAPcy08sIdhoXIsdw3ykJa8hIM=:3LNhQmD3SCeDwydveqLgtRSxhN0sZRGKn47mN1sU="
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            },
            {
              "name": "Depth",
              "value": "1"
            },
            {
              "name": "Content-Type",
              "value": "text/plain;charset=UTF-8"
            },
            {
              "name": "Content-Length",
              "value": "661"
            },
            {
              "name": "Origin",
              "value": "https://cloud.mydomain.tld"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Cookie",
              "value": "oc_sessionPassphrase=zHcF%2B%2B44eFNhh%2B7ZmdubEZ0eiHHa5xcvJL8dggj9cbASeoBqlWO35t1vFBLZmFv2Bj0xh16uKuk%2By2I2dvHLshXUk3MKikL50fkLE7bgevce%2BMzN2XazgId4OxAduC%2Fy; PHPSESSID=nq9hv51vqdg63v4gc3n1vkv3mm; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; lemonldap=0036f185a32d1c674b51b2272da9e0469c061f3eebda169bc1d45ce1877319a5"
            },
            {
              "name": "TE",
              "value": "Trailers"
            }
          ],
          "cookies": [
            {
              "name": "oc_sessionPassphrase",
              "value": "zHcF++44eFNhh+7ZmdubEZ0eiHHa5xcvJL8dggj9cbASeoBqlWO35t1vFBLZmFv2Bj0xh16uKuk+y2I2dvHLshXUk3MKikL50fkLE7bgevce+MzN2XazgId4OxAduC/y"
            },
            {
              "name": "PHPSESSID",
              "value": "nq9hv51vqdg63v4gc3n1vkv3mm"
            },
            {
              "name": "__Host-nc_sameSiteCookielax",
              "value": "true"
            },
            {
              "name": "__Host-nc_sameSiteCookiestrict",
              "value": "true"
            },
            {
              "name": "lemonldap",
              "value": "0036f185a32d1c674b51b2272da9e0469c061f3eebda169bc1d45ce1877319a5"
            }
          ],
          "queryString": [],
          "headersSize": 902,
          "postData": {
            "mimeType": "text/plain;charset=UTF-8",
            "params": [],
            "text": "<?xml version=\"1.0\"?>\n\t\t\t<d:propfind  xmlns:d=\"DAV:\"\n\t\t\t\txmlns:oc=\"http://owncloud.org/ns\"\n\t\t\t\txmlns:nc=\"http://nextcloud.org/ns\"\n\t\t\t\txmlns:ocs=\"http://open-collaboration-services.org/ns\">\n\t\t\t\t<d:prop>\n\t\t\t\t\t<d:getlastmodified />\n\t\t\t\t\t<d:getetag />\n\t\t\t\t\t<d:getcontenttype />\n\t\t\t\t\t<d:resourcetype />\n\t\t\t\t\t<oc:fileid />\n\t\t\t\t\t<oc:permissions />\n\t\t\t\t\t<oc:size />\n\t\t\t\t\t<d:getcontentlength />\n\t\t\t\t\t<nc:has-preview />\n\t\t\t\t\t<nc:mount-type />\n\t\t\t\t\t<nc:is-encrypted />\n\t\t\t\t\t<ocs:share-permissions />\n\t\t\t\t\t<oc:tags />\n\t\t\t\t\t<oc:favorite />\n\t\t\t\t\t<oc:comments-unread />\n\t\t\t\t\t<oc:owner-id />\n\t\t\t\t\t<oc:owner-display-name />\n\t\t\t\t\t<oc:share-types />\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>"
          }
        },
        "response": {
          "status": 207,
          "statusText": "Multi-Status",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "server",
              "value": "nginx"
            },
            {
              "name": "date",
              "value": "Sat, 11 Dec 2021 15:11:44 GMT"
            },
            {
              "name": "content-type",
              "value": "application/xml; charset=utf-8"
            },
            {
              "name": "expires",
              "value": "Thu, 19 Nov 1981 08:52:00 GMT"
            },
            {
              "name": "cache-control",
              "value": "no-store, no-cache, must-revalidate"
            },
            {
              "name": "pragma",
              "value": "no-cache"
            },
            {
              "name": "referrer-policy",
              "value": "no-referrer"
            },
            {
              "name": "x-content-type-options",
              "value": "nosniff"
            },
            {
              "name": "x-download-options",
              "value": "noopen"
            },
            {
              "name": "x-frame-options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "x-permitted-cross-domain-policies",
              "value": "none"
            },
            {
              "name": "x-robots-tag",
              "value": "none"
            },
            {
              "name": "x-xss-protection",
              "value": "1; mode=block"
            },
            {
              "name": "content-security-policy",
              "value": "default-src 'none';"
            },
            {
              "name": "vary",
              "value": "Brief,Prefer"
            },
            {
              "name": "dav",
              "value": "1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, nc-calendar-search, nc-enable-birthday-calendar"
            },
            {
              "name": "content-encoding",
              "value": "gzip"
            },
            {
              "name": "X-Firefox-Spdy",
              "value": "h2"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/xml; charset=utf-8",
            "size": 13507,
            "text": "......."
          },
          "redirectURL": "",
          "headersSize": 693,
          "bodySize": 2026
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 105,
          "receive": 0
        },
        "time": 105,
        "_securityState": "secure",
        "serverIPAddress": "11.22.33.44",
        "connection": "443"
      },
      {
        "pageref": "page_4",
        "startedDateTime": "2021-12-11T16:11:44.468+01:00",
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "https://cloud.mydomain.tld/core/preview?fileId=175119&x=1680&y=1050&a=true",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "Host",
              "value": "cloud.mydomain.tld"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
            },
            {
              "name": "Accept",
              "value": "image/webp,*/*"
            },
            {
              "name": "Accept-Language",
              "value": "fr-BE,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Cookie",
              "value": "oc_sessionPassphrase=xxxxx; PHPSESSID=yyyyy; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; lemonldap=zzzzzzzzz"
            },
            {
              "name": "TE",
              "value": "Trailers"
            }
          ],
          "cookies": [
            {
              "name": "oc_sessionPassphrase",
              "value": "xxxxx"
            },
            {
              "name": "PHPSESSID",
              "value": "yyyyy"
            },
            {
              "name": "__Host-nc_sameSiteCookielax",
              "value": "true"
            },
            {
              "name": "__Host-nc_sameSiteCookiestrict",
              "value": "true"
            },
            {
              "name": "lemonldap",
              "value": "zzzzzz"
            }
          ],
          "queryString": [
            {
              "name": "fileId",
              "value": "175119"
            },
            {
              "name": "x",
              "value": "1680"
            },
            {
              "name": "y",
              "value": "1050"
            },
            {
              "name": "a",
              "value": "true"
            }
          ],
          "headersSize": 675
        },
        "response": {
          "status": 404,
          "statusText": "Not Found",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "server",
              "value": "nginx"
            },
            {
              "name": "date",
              "value": "Sat, 11 Dec 2021 15:11:44 GMT"
            },
            {
              "name": "content-type",
              "value": "application/json; charset=utf-8"
            },
            {
              "name": "content-length",
              "value": "2"
            },
            {
              "name": "expires",
              "value": "Thu, 19 Nov 1981 08:52:00 GMT"
            },
            {
              "name": "pragma",
              "value": "no-cache"
            },
            {
              "name": "referrer-policy",
              "value": "no-referrer"
            },
            {
              "name": "x-content-type-options",
              "value": "nosniff"
            },
            {
              "name": "x-download-options",
              "value": "noopen"
            },
            {
              "name": "x-frame-options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "x-permitted-cross-domain-policies",
              "value": "none"
            },
            {
              "name": "x-xss-protection",
              "value": "1; mode=block"
            },
            {
              "name": "cache-control",
              "value": "no-cache, no-store, must-revalidate"
            },
            {
              "name": "content-security-policy",
              "value": "default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'"
            },
            {
              "name": "feature-policy",
              "value": "autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'"
            },
            {
              "name": "x-robots-tag",
              "value": "none"
            },
            {
              "name": "X-Firefox-Spdy",
              "value": "h2"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/json; charset=utf-8",
            "size": 2,
            "text": "[]"
          },
          "redirectURL": "",
          "headersSize": 707,
          "bodySize": 709
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 85,
          "receive": 0
        },
        "time": 85,
        "_securityState": "secure",
        "serverIPAddress": "11.22.33.44",
        "connection": "443"
      }
    ]
  }
}
```

</details>

#### Web server error log

<details>

<summary>Web server error log</summary>

```
11.22.33.44 - - [11/Dec/2021:16:02:16 +0100] "PROPFIND /remote.php/dav/files/userX/test.jpg HTTP/2.0" 207 560 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" "-" "cloud.mydomain.tld"
11.22.33.44 - - [11/Dec/2021:16:02:16 +0100] "PROPFIND /remote.php/dav/files/userX/ HTTP/2.0" 207 1333 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" "-" "cloud.mydomain.tld"
11.22.33.44 - - [11/Dec/2021:16:02:16 +0100] "GET /core/preview?fileId=175119&x=1680&y=1050&a=true HTTP/2.0" 404 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" "-" "cloud.mydomain.tld"
11.22.33.44 - - [11/Dec/2021:16:02:16 +0100] "GET /core/preview?fileId=805&x=1680&y=1050&a=true HTTP/2.0" 200 50545 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" "-" "cloud.mydomain.tld"
```
</details>

#### Nextcloud log (data/nextcloud.log)

<details>

<summary>Nextcloud log</summary>
Only warnings about deprecated things, no error.

```
{"reqId":"T1sbtavGsDDUItFNVQm8","level":0,"time":"December 11, 2021 16:29:13","remoteAddr":"11.22.33.44","user":"userX","app":"user_external","method":"PROPFIND","url":"/remote.php/dav/files/userX/test.jpg","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"22.2.3.0"}
```
</details>

</details>

### PR DESCRIPTION
**Pull request by solracsf**
Fix https://github.com/nextcloud/server/issues/30220

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Drone failure is unrelated: https://github.com/nextcloud/server/pull/31143#issuecomment-1046268944

**Comment by szaimen** [comment]
@acsfer please fix dco then I'll merge

**Comment by acsfer** [comment]
Fixed

**Comment by szaimen** [comment]
> Fixed

That was not what I meant but okay 😂

**Comment by szaimen** [comment]
BTW: @acsfer do you mind also clarifying the flag in the documentation?

**Comment by acsfer** [comment]
Where exactly?

**Comment by szaimen** [comment]
here: https://github.com/nextcloud/documentation/blob/b0d15109fa8140593f14f8751d944e6781076ca8/admin_manual/configuration_server/config_sample_php_parameters.rst#:~:text='preview_max_filesize_image'%20%3D%3E%2050%2C

**Comment by acsfer** [comment]
https://github.com/nextcloud/documentation/pull/8082

**Pull request merged**
