### PR TITLE
Fix log_type errorlog: should behave like other log handlers

### PR DESCRIPTION
**Pull request by znerol**
Configuration with `'log_type' => 'errorlog'` are affected by #33313. This is due to the fact that the `ErrorLog` handler currently doesn't correctly implement the `write()` method. According to other implementations, the `$message` parameter can be either a string or an array.

Other implementations use `logDetailsAsJSON` to convert a structured log message into a `string`. `ErrorLog` should do the same.

Note: This PR also removes the `$tag` instance variable. A log tag is important for writers like `syslog` and `systemd` where log messages of multiple subsystems are merged into a common journal. This is clearly not the case for the `errlog` writer.

### CODE REVIEW

**Comment by k-popov** [comment]
Is there any activity on having this patch accepted?
IMO this patch is important as running NextCloud in kubernetes ofter implies logging to STDERR (with later collection to Kibana). And currently the entire logging to `errorlog` is broken, images are required to be rebuilt with local patches applied.

**Comment by ChristophWurst** [comment]
I coincidentally submit a very similar PR at https://github.com/nextcloud/server/pull/35614.

Let's take this one. But please revive the `$tag` constructor arg.

**Comment by znerol** [comment]
> Let's take this one. But please revive the $tag constructor arg.

If `$tag` needs to remain, then yours is already there.

**Comment by ChristophWurst** [comment]
Then let's continue in https://github.com/nextcloud/server/pull/35614. Mind giving the other PR a review? :)

**Pull request closed without merging**
