### PR TITLE
add (hidden) option to always show smb root as writable

### PR DESCRIPTION
**Pull request by icewind1991**
some smb servers are very insistent in reporting that the root of the share is readonly, even if it isn't.

This works around the problem by adding a hidden option to overwrite the permissions of the root of the share.

This can be enabled using

```bash
occ files_external:config <mount id> root_force_writable true
```

where you can find your mount id using

```bash
occ files_external:list
```

Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:elephant:

**Review by MorrisJobke — APPROVED** [review]
🦒

**Pull request merged**
