### PR TITLE
fix(files): Allow Ctrl/Command click on file entries to open in a new tab

### LINKED ISSUE #42288: [Bug]: Cannot open documents/files in new tabs anymore (using Ctrl+Click) since NC 28
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the update to NC 28 you cannot open files in a new tab anymore.

### Steps to reproduce

1. Upload any file (for example a pdf)
2. Hold the CTRL button and click on the PDF
3. The PDF opens in the same tab

### Expected behavior

The PDF should open in a new tab, like in NC 27 and below.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "default_language": "de",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.cvjm-fellbach.de",
            "nextcloud.cvjm-fellbach.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.cvjm-fellbach.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "skeletondirectory": "\/var\/nextcloud_skeleton",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "updater.release.channel": "stable",
        "filesystem_check_changes": "0",
        "app_install_overwrite": [
            "keeweb",
            "richdocuments",
            "ransomware_protection",
            "bruteforcesettings",
            "previewgenerator",
            "impersonate",
            "files_retention",
            "files_downloadactivity"
        ],
        "default_phone_region": "DE",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - announcementcenter: 6.7.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - deck: 1.12.0
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - groupfolders: 16.0.1
  - impersonate: 1.15.0
  - keeweb: 0.6.13
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - notify_push: 0.6.6
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.0.1
  - previewgenerator: 5.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - ransomware_protection: 1.14.0
  - recommendations: 2.0.0
  - richdocuments: 8.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - sociallogin: 5.6.0
  - spreed: 18.0.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - theming_customcss: 1.15.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 0.21.0)
  - dashboard: 7.8.0 (installed 7.4.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.3.0)
  - files_automatedtagging: 1.18.0 (installed 1.18.0)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - related_resources: 1.3.0 (installed 1.0.4)
  - support: 1.11.0 (installed 1.0.0)
  - survey_client: 1.16.0 (installed 1.1.0)
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

Newest Firefox and Chrome version

### PR DESCRIPTION
**Pull request by juliusknorr**
Bring back opening files in a new tab by Ctrl-clicking on the file list entry. metaKey is needed for macOS support.

### CODE REVIEW

**Review by nfebe — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
The bot is soooo weird @juliushaertl

**Comment by juliushaertl** [comment]
I restarted the action as it didn't seem to be working smoothly on self-hosted runnsers

**Comment by juliushaertl** [comment]
Reference for the failure https://github.com/nextcloud/server/actions/runs/7336566796/job/19976090810?pr=42457

**Comment by skjnldsv** [comment]
Oooh, it fails if `init` ran on a different runner type than `process`

**Comment by ShGKme** [comment]
This solution overrides browser default behavior. While it allows to open link on new tab, the link is still invalid:
- Middle click is invalid
- Context menu is invalid
- title and attributes are invalid

For example, for a folder it says that it is a link to download a file via `/remote.php` while actually click opens a folder.

**Comment by ShGKme** [comment]
This line doesn't work, we cannot take data from another child through parent on initial render. There is no another child on this moment.

https://github.com/nextcloud/server/blob/7c79521cbe83f20d1c1659c05be3d9fac24103eb/apps/files/src/components/FileEntry/FileEntryName.vue#L150

And anyway I don't think it is a good approach to transfer data by manually going through nodes...

**Comment by ShGKme** [comment]
Link should be the same as it opens. If a link opens `/foo/bar`, then it should have href `/foo/bar`.

Here it also makes the link download link and the title says "Download".

The source of the issue is that this line, that was supposed to find the default action, fails on initial rendering.

**Comment by D592VN5** [comment]
any news on this?

**Comment by susnux** [comment]
@D592VN5 please open an issue if you encounter any problems.

**Pull request merged**
