### PR TITLE
Dashboard - fix touch layout

### LINKED ISSUE #24404: Dashboard - Unwanted movement of widgets and new functions on mobile
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The movement of the widgets of the dashboard application generates a bad user experience on a touch device because when you try to slide the screen, you tend to select and move the widgets.

**Describe the solution you'd like**
I think that a function should be incorporated that avoids this edition unless the user presses the personalization button. Also incorporate in the global administration options that make it possible to manage which application is enabled by default for all users, what order the widgets should have and another option that allows administrators to decide whether users can make modifications.

**Describe alternatives you've considered**

**Additional context**
Screenshot_20201126-214711_Chrome

### PR DESCRIPTION
**Pull request by szaimen**
Fix #24404

<details>
<summary>For my own testing</summary>

```
docker run -d \
-e SERVER_BRANCH=fix/24404/touch-layout-dashboard \
-p 8443:443 \
-e CALENDAR_BRANCH=master \
-e TASKS_BRANCH=master \
-e TRUSTED_DOMAIN=192.168.178.34 \
--name nextcloud-easy-test \
--user=www-data \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
Failing tests are unrelated, afaics.

**Review by artonge — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure unrelated

**Pull request merged**
