### PR TITLE
vendor: Update davclient.js to 0.1.2

### PR DESCRIPTION
**Pull request by leonklingele-work**
This includes https://github.com/owncloud/davclient.js/pull/31

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
commit is not signed-off though

**Comment by leonklingele-work** [comment]
> commit is not signed-off though

Argh. How do you guys handle this? Is there some way to always sign-off when committing to a specific repo? Have you set up a shell / Git alias? I've not found an option to enable this behavior via `.gitconfig`.

Anyways, commit is signed-off now.

**Comment by MorrisJobke** [comment]
> Argh. How do you guys handle this? Is there some way to always sign-off when committing to a specific repo? Have you set up a shell / Git alias? I've not found an option to enable this behavior via .gitconfig.

`git commit -s` is my way ... it's just in my fingers nowadays.

**Comment by MorrisJobke** [comment]
Rebased to get fixes of master in here.

**Pull request merged**
