### PR TITLE
Replace custom tooltips with native ones in apps page

### LINKED ISSUE #35887: [BITV]: Replace custom tooltips with native one for Apps page
## Problem

To show a tooltip on a several components we currently use v-tooltip. An example can be found in https://github.com/nextcloud/server/blob/master/apps/settings/src/components/AppList/AppItem.vue#L56

v-tooltip is not accessible and we want to migrate to native tooltips (title attribute) instead. An overview can be found in https://github.com/nextcloud/nextcloud-vue/issues/2503.

## Solution

Add a `title` prop to several components that will render as `title` attribute on the HTML element.

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Replace custom tooltips with native ones in apps page

* Resolves: https://github.com/nextcloud/server/issues/35887

## Summary

Replace custom tooltips with native ones in apps page

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
weird error about package-lock.json even though it wasn't touched

**Review by Pytal — APPROVED** [review]
Other than the probably unintentional removal of `dist/icons.css`

**Comment by ChristophWurst** [comment]
conflicts

**Pull request merged**
