### PR TITLE
Bump jQuery to v2.2

### PR DESCRIPTION
**Pull request by ChristophWurst**
As announced in the deprecation warning we will slowly upgrade jquery. This time to v2.2. A quick smoke test showed me a working files list and some basic settings, so the breakage might be minimal.

I would suggest to get this in as early as possible. So we notice the breaking changes in various apps and fix them before the 20 release.

:eyes: @nextcloud/javascript

### CODE REVIEW

**Comment by ChristophWurst** [comment]
:eyes: @blizzz as our friend the ldap :mage: might cause trouble

**Comment by MorrisJobke** [comment]
> 👀 @blizzz as our friend the ldap 🧙 might cause trouble

Fully tested one LDAP wizard go from first to last page. Adding credentials, login details, users and groups worked just fine and there were no JS errors in the console (just a lot of deprecation warnings).

**Review by MorrisJobke — APPROVED** [review]
Tested and still works 👍

**Comment by e-alfred** [comment]
Do you have some kind of list of apps that still use JQuery and could potentially be affected by this?

**Comment by ChristophWurst** [comment]
> Do you have some kind of list of apps that still use JQuery and could potentially be affected by this?

No, this information is hard to acquire. Rule of thumb is the apps that still don't use webpack but have some UI to render

**Review by juliusknorr — APPROVED** [review]
:tada: Seems to work still fine

**Comment by e-alfred** [comment]
> Rule of thumb is the apps that still don't use webpack but have some UI to render

The JQuery warning comes up on pretty much every app at the moment, even the Files or Calendar etc., so it is not that helpful currently.

**Comment by ChristophWurst** [comment]
I know. This is something we have to work on. For Files it's probably the most complex task to get this app into shape. But others should be easier.

**Comment by ChristophWurst** [comment]
You can, for example, add https://github.com/nextcloud/eslint-config and it will automatically tell you which of the deprecated/removed globals are still used.

**Comment by juliushaertl** [comment]
There actually seems to be a regression with this that causes the files app to fail loading (sometimes on firefox but more often in chromium)

image

It seems to be somehow related to the order how things are executed since the issue is mainly that the OCA.Files.FileList is not ready when the `$(document).ready` is being called.

image

Any idea @ChristophWurst ? I couldn't find anything helpful in the 2.2 changelog. :disappointed:

**Comment by ChristophWurst** [comment]
> It seems to be somehow related to the order how things are executed since the issue is mainly that the OCA.Files.FileList is not ready when the `$(document).ready` is being called.

ah yeah. I do remember that this loading order issue arose when I attempted to upgrade to v2.2 in the past. Now it seemed resolved when I tested and I just assume the bundled scripts helped.

IIRC removing the `defer` from the scripts tags would solve the problem. The load event is handled differently in jQuery <2.2 and after.

**Comment by skjnldsv** [comment]
Still an issue for me :shrug: 
Fix in https://github.com/nextcloud/server/pull/21921

**Comment by ChristophWurst** [comment]
Documented at https://github.com/nextcloud/documentation/pull/5160

**Pull request merged**
