### PR TITLE
Rename sync clients section to mobile & desktop

### PR DESCRIPTION
**Pull request by juliusknorr**
Rename the sync clients section in personal settings to "Mobile & desktop" as proposed by @jancborchardt in https://github.com/nextcloud/spreed/pull/913

image

### CODE REVIEW

**Comment by MariusBluem** [comment]
Would go for desktop.svg here 🤔

**Comment by juliushaertl** [comment]
I chose the mobile icon, since @jancborchardt also mentioned Mobile first in the name. I also think it looks a bit better in the size that is used in the sidebar, but I have no strong opinion on that.

image

**Review by MorrisJobke — APPROVED** [review]
I like the mobile icon as well 👍

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I restarted the jobs

**Comment by jancborchardt** [comment]
Prefer the phone icon – people use more and more phones. ;)

**Review by jancborchardt — APPROVED** [review]

**Pull request merged**
