### PR TITLE
OCA\ShareByMail\Capabilities add unit test

### PR DESCRIPTION
**Pull request by MasterOfDeath**

### CODE REVIEW

**Comment by danielkesselberg** [comment]
Hey @MasterOfDeath :tada: 

Thank you for your contribution :+1: Could you please sign off your commits? [Here](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work) are some information why this is required and how it works.

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
> First-time contributor

:tada: welcome to the club :rocket: 

As @danielkesselberg mentioned we require commits to be signed off. You can do this by using `git commit -s` when committing.

**Review by kesselb — APPROVED** [review]
Works :+1:

**Comment by MorrisJobke** [comment]
> As @danielkesselberg mentioned we require commits to be signed off. You can do this by using `git commit -s` when committing.

Beside that it would be nice to have only one commit in here. Just squash the 3 commits into one. If you need help with this we can guide you through this and assist.

Thanks for contributing 👍

**Comment by MasterOfDeath** [comment]
> Beside that it would be nice to have only one commit in here. Just squash the 3 commits into one. If you need help with this we can guide you through this and assist.

Made it and signed-off commit.

**Pull request merged**
