### PR TITLE
[stable25] Log switching to LDAP backup host because main one is not available

### PR DESCRIPTION
**Pull request by come-nc**
Manual backport of #35230

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

won't the pollute the log though to have it as "warning" instead of "debug" ?

**Comment by come-nc** [comment]
> +1
> 
> won't the pollute the log though to have it as "warning" instead of "debug" ?

Indeed, maybe we should not backport then, as this fits better with https://github.com/nextcloud/server/pull/35839 , but this one depends on https://github.com/nextcloud/server/pull/35229
Or should we backport all of them?

**Comment by skjnldsv** [comment]
> Indeed, maybe we should not backport then, as this fits better with #35839 , but this one depends on #35229
> Or should we backport all of them?

Closing then?

**Comment by come-nc** [comment]
Yeah closing, it’s nitpick anyway.

**Pull request closed without merging**
