### PR TITLE
fix: Change scroll container for sharing details

### LINKED ISSUE #41304: [BITV]: Sharing tab: sticky buttons "update share" and "cancel" overlapping important interactive content
That should not be a case ;(

Peek 2023-11-06 14-32

@nimishavijay @marcoambrosini how could we solve a problem?

### LINKED ISSUE #41421: [Bug]: Unneeded vertical scrollbar appears in sharing sidebar
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Unneeded vertical scrollbar appears in sharing sidebar

Peek 2023-11-13 13-24

### Steps to reproduce

1. Open details for any file or folder
2. Open sharing Tab
3. Click to "share link"
4. Click to "customize link" inside the action menu
5. See that a unneeded vertical scrollbar appears

### Expected behavior

Unneeded vertical scrollbar won't appear

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by juliusknorr**
Fix #41421 
Fix https://github.com/nextcloud/server/issues/41304
Replaces https://github.com/nextcloud/server/pull/41424

Best to be reviewed without whitespace changes https://github.com/nextcloud/server/pull/41444/files?w=1 as I introduce one wrapping container for the new scroll area

### CODE REVIEW

**Review by nfebe — COMMENTED** [review]
It's better for the white space changes to first have commit followed by the actual change.

**Review by ShGKme — APPROVED** [review]

**Comment by ShGKme** [comment]
@juliushaertl Do you have understanding, what property and why fixes the problem with the scrolling?
Why there is a large padding in Julia's PR.

**Comment by Fenn-CS** [comment]
> Hm, I don't see a point in that, can you elaborate what the benefit would be? To me having one atomic change with all required adjustemnts seems more reasonable.

It's confusing for me now and it would definitely be more confusing in future if anyone looks at the commit. The fix says "Change scroll container for sharing details" then the diff shows bunch for white space changes.

Unless I am missing something, I think it would be okay if the formatting changes only affected the areas that need to be reviewed. Otherwise, what if aside actual functional tests something is introduced in the unconcerned sections. 

That said, given, there no strict commit culture here at Nextcloud, it would be helpful then to highlight the actual changes via comment or something or best in my opinion, separate the commits (for this and similar kind of changes in the future).

**Review by nfebe — APPROVED** [review]
Tested works....

**Comment by juliushaertl** [comment]
> It's confusing for me now and it would definitely be more confusing in future if anyone looks at the commit. The fix says "Change scroll container for sharing details" then the diff shows bunch for white space changes.
> 
> Unless I am missing something, I think it would be okay if the formatting changes only affected the areas that need to be reviewed. Otherwise, what if aside actual functional tests something is introduced in the unconcerned sections.
> 
> That said, given, there no strict commit culture here at Nextcloud, it would be helpful then to highlight the actual changes via comment or something or best in my opinion, separate the commits (for this and similar kind of changes in the future).

Right, thanks for elaborating. This should be mostly relevant when running git blame where the `-w -M` flags are quite useful generally. I'd for now just extend the commit message to take the large whitespace change into account then.

**Comment by juliushaertl** [comment]
> Do you have understanding, what property and why fixes the problem with the scrolling?
> Why there is a large padding in Julia's PR.

I think the main lacking part was setting `position: relative;` on all wrapping containers as otherwise the flexbox would exceed the height even with enforcing 100%. The extra bottom margin was also a bit of a mystery to me tough.

**Comment by jancborchardt** [comment]
Just one detail @juliushaertl – the "Delete share" button is not supposed to be sticky, but the last button in the content area. As proposed by @JuliaKirschenheuter and approved by Michael in https://github.com/nextcloud/server/issues/41304#issuecomment-1808090609

**Pull request merged**
