### PR TITLE
Filter magic dot object when swift directory

### PR DESCRIPTION
**Pull request by icewind1991**
For https://github.com/nextcloud/server/issues/5868

### CODE REVIEW

**Comment by icewind1991** [comment]
@jmdeboer-surfsara can you check if this fixes the problem for you

**Comment by jmdeboer-surfsara** [comment]
Yes, this fixes it, $cachedNames and $contents are now equal arrays.
This in 11.0.3.2 (I have not yet had the opportunity to test in 12)

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@icewind1991 I gutes this needs to be backported to stable11 and 12, right?

**Comment by icewind1991** [comment]
Yes, will make PR's

**Pull request merged**
