### PR TITLE
Avatar picker improvements

### PR DESCRIPTION
**Pull request by icewind1991**
- Don't flash the full size image before the cropper can load
- Float the cropper over the page instead of the awkward, half overlapping, half messing with the layout it was before
- Hide the cropper dialog until it's loaded
- Show spinner while while loading/cropping the avatar

Before:

After:

cc @nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
Nice!! Can't review right now, but looks great!

**Comment by MariusBluem** [comment]
You are reading my minds 😜 ... much better and more responsive now 👍

**Comment by jancborchardt** [comment]
@icewind1991 Great stuff, just one point: Can you make the cropper tool by default be as big as the whole image? If the image is not square, center the cropper both horizontally and vertically.

**Comment by icewind1991** [comment]
> Can you make the cropper tool by default be as big as the whole image? If the image is not square, center the cropper both horizontally and vertically.

Done

**Comment by rullzer** [comment]
Awesome stuff!
Works like a charm :+1:

**Comment by jancborchardt** [comment]
One issue:
- [ ] if the screen is too small (just zoom in 150% or so), the avatar picker overflows on the bottom. It’s impossible to get out of this because it’s an overlay. It should instead always be centered, and scrollable if it overflows.

**Comment by MorrisJobke** [comment]
Tested and works 👍 

Tested in IE11, Firefox, Safari, Chrome

**Comment by icewind1991** [comment]
It now centers the dialog vertically and the dialog scales down to fit on large screens (not dynamically while resizing, you have to re-open the dialog if testing with a small window)

**Comment by MorrisJobke** [comment]
Retested and works now 👍

**Comment by jancborchardt** [comment]
@icewind1991 awesome work on all these modal dialogs! :)

**Pull request merged**
