### PR TITLE
Automatically open and copy the menu on public link share activation

### PR DESCRIPTION
**Pull request by skjnldsv**
@nextcloud/designers 
I really dislike what I have done right here, feels terrible!
Is there no way of waiting for a dom element to appear?

@jancborchardt Or we can find another way to fix this issue

### CODE REVIEW

**Comment by skjnldsv** [comment]
capture d ecran_2018-10-02_11-07-54

**Comment by jancborchardt** [comment]
@skjnldsv definitely looks better than currently! :) :+1: 

(As discussed, let’s try with "Copy" for text next to the copy icon.)

**Comment by jancborchardt** [comment]
@skjnldsv I’ll try and look into it. :)

**Comment by schiessle** [comment]
@skjnldsv are you aware of https://github.com/nextcloud/server/issues/11169 and https://github.com/nextcloud/server/pull/11844 I have the feeling that we duplicate work here and changing the same stuff at the same time in two different pull request.

Maybe you want to join me on my PR and while making multiple links possible improve toe UX. Your JS experience would be much appreciated. You can already find some suggestions in the issue linked here.

**Comment by jancborchardt** [comment]
@schiessle please see my comment at https://github.com/nextcloud/server/issues/11169#issuecomment-430984992 – these two issues are actually separate, and the "multiple link shares" addition should not change the entire flow of how links work. There is a spec we designed which defines it, and if we throw around stuff midway, that’s recipe for confusion and breakage.

**Comment by schiessle** [comment]
@jancborchardt but we touch and change exactly the same code which creates a hell of merge conflicts. Let's implement the multiple share links and while touching the code anyway make it work smooth.

**Comment by mmuman** [comment]
Thanks for working on this, last upgrade made me wonder what was happening.

I'd just point a few things though: 
- there is a natural way to show links (A HREF),
- there is more than one way to use them, not only clipboard (drag-n-drop, setting a bookmark…),
- not everyone likes others tampering with their clipboard,
- the input field (rather having the link as selectable text on the page, a text link would do alike) had the nice side-effect of being able to select the text and paste it with middle button on GNU/Linux without having to actually touch the clipboard (although IIRC the code which selected the whole content made it hard to actually get the whole string in the kill-ring).

**Comment by newhinton** [comment]
@skjnldsv @jancborchardt What if we dump the checkbox?
We could use the shareicon as an indicator, it is grey when it isnt shared, and we could color it in the main color if it is shared. Also the text next to it would change from "share link" to "You shared this", and display the groups/users/urls below.

**Comment by jancborchardt** [comment]
> What if we dump the checkbox? We could use the shareicon as an indicator, it is grey when it isnt shared, and we could color it in the main color if it is shared.

I’m not super excited about this – checkboxes are a very clear indicator of state. Having our own standard for color & text needs people to read text and be able to view color. We just need to integrate the checkbox nicely, like move it slightly over the icon maybe.

**Comment by mcarpenterjr** [comment]
Have you guys considered just having the text be a link to open the share menu for the item? I have about 5 users that complain constantly about how that UI is very misleading like they want to click the text or the icon to get to the menu. but instead they have to home in on the Kabob which is fine for when you want to do more than just share.

**Comment by jancborchardt** [comment]
@mcarpenterjr I added a point in my comment of the spec:

> Do we want to automatically open the 🞄🞄🞄 menu here too? (Maybe at least for the first link so it kind of shows people the options?)

This would maybe take care of that? 


-------

Btw @skjnldsv feel free to close this when it’s rolled into #11844

**Comment by mcarpenterjr** [comment]
@jancborchardt Thanks man, looks great.

**Pull request closed without merging**
