### PR TITLE
l10n: Add a dot

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by artonge** [comment]
Hmm, not sure if we put dots at the end of error messages, or if it's good practice

**Comment by Valdnet** [comment]
If it is an error message then it needs to be standardized. The following text string is also an error message that includes a dot at the end of the sentence. The same rules should be applied for text strings in similar functions.

https://github.com/nextcloud/server/blob/098dfe15c1e932a2acc8bb4853979040339a3ad7/apps/files_sharing/lib/Controller/ShareAPIController.php#L1122

So I remove the dots.

**Review by CarlSchwan — APPROVED** [review]
:+1:

**Review by rakekniven — APPROVED** [review]

**Comment by Valdnet** [comment]
ping @artonge

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
Tests need to be fixed:

```
 There were 2 failures:

1) OCA\Files_Sharing\Tests\Controller\ShareAPIControllerTest::testUpdateLinkShareSetInvalidCRUDPermissions2 with data set #0 (12)
Failed asserting that exception message 'Share must have READ permission if UPDATE or DELETE permission is set' contains 'Share must have READ permission if UPDATE or DELETE permission is set.'.

2) OCA\Files_Sharing\Tests\Controller\ShareAPIControllerTest::testUpdateLinkShareSetInvalidCRUDPermissions2 with data set #1 (6)
Failed asserting that exception message 'Share must have READ permission if UPDATE or DELETE permission is set' contains 'Share must have READ permission if UPDATE or DELETE permission is set.'.
```

**Comment by Valdnet** [comment]
@artonge Thanks for pointing out the test error 😉. I fixed it.

**Pull request merged**
