### PR TITLE
Allow to fetch the creation time of folders

### PR DESCRIPTION
**Pull request by juliusknorr**
- Merge duplicate if condition into one
- Allow to fetch the creation time of folders through propfind requests

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@juliushaertl seen that you tagged it v24, does it need backport love back to v22?

**Comment by juliushaertl** [comment]
Yes, should be backported but since the pr is against master I added it to the 24 milestone.

**Review by nickvergessen — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1: nice

**Pull request merged**
