### PR TITLE
Add autocomplete to migration commands

### PR DESCRIPTION
**Pull request by nickvergessen**
Start typing `occ migration:generate <forget your appid>` 
Now with `tab` you can autocomplete it just fine.

Also works for the version suggestion and for the other commands it suggestions the available migrations

### CODE REVIEW

**Comment by blizzz** [comment]
> Start typing occ migration:generate <forget your appid>
Now with tab you can autocomplete it just fine.

Doesn't work… perhaps i am missing an extra step? or has requirements on the host system?

**Comment by MorrisJobke** [comment]
> Doesn't work… perhaps i am missing an extra step? or has requirements on the host system?

Yes - you need to add something to your shell env: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/occ_command.html?highlight=autocomplete#enabling-autocompletion

**Review by blizzz — APPROVED** [review]
tested and works

**Comment by blizzz** [comment]
@MorrisJobke thanks, this totally went past me

**Review by MorrisJobke — APPROVED** [review]
🐘

**Pull request merged**
