### PR TITLE
Added Drozone to favorites quickaccess

### PR DESCRIPTION
**Pull request by newhinton**
This adds the ability to drop a folder on the quickaccess and add it to it

### CODE REVIEW

**Review by skjnldsv — CHANGES_REQUESTED** [review]
- The drop background stays after I stopped dragging :)
- If you remove the last directory from the favorite and add a new one it doesn't get appended to the quickaccess list :)

Otherwise it works great on files and folder!

**Comment by newhinton** [comment]
If i remember correctly #10888 should fix the second isssue, but ill have to look into the first one :D

**Comment by MorrisJobke** [comment]
@newhinton Just change the labels from "2. developing" to "3. to review" once you are done with your changes ;)

**Comment by MorrisJobke** [comment]
@newhinton Could you rebase this one please? Thanks :)

**Comment by MorrisJobke** [comment]
Let's move this one to 16.

**Comment by newhinton** [comment]
See #12917

**Comment by jancborchardt** [comment]
@newhinto so should we close this in favor of https://github.com/nextcloud/server/pull/12917 ?

**Comment by newhinton** [comment]
@jancborchardt yes, i wasnt shure if it was the proper thing todo ;)

**Pull request closed without merging**
