### PR TITLE
16.0.1 RC 1

### PR DESCRIPTION
**Pull request by MorrisJobke**
Changelog to 16.0.0 (#15202):

* #15223 Fix setupcheck for intl module
* #15303 Take return of mkdir into consideration; photocache to not create a folder for deletion
* #15312 Remove the custom prefix from the table name length when checking on …
* #15341 Check if the data is in the lookup server
* #15345 Do NOT assume all files are selected if the first checkbox is
* #15389 Fix collapse button in app navigation in IE11
* #15399 Make sure all middlewares are only registered once
* #15405 Allow to send the password of protected conversations
* #15409 Remove extra margin from warning messages in authenticate page
* #15417 Set Edge < 16 as incompatible with css vars
* #15418 Remove extra param in cache update call
* #15424 Handle 0 B default quota properly in the web UI
* #15433 Fix multiselect min width
* #15434 Make access column a real boolean
* #15439 Fix public upload by also load the semaphore method
* #15442 Remove setup args from logging
* #15447 Run phan tests only on high memory machines
* #15452 Use non-absolute logout URL to fix wrong URL in reverse proxy scenario
* #15465 Revert "Run phan tests only on high memory machines"
* #15469 Fix mobile vertical scrolling
* #15471 Remove recommendation for opcache on CLI
* #15482 Update file-upload.js
* [files_pdfviewer#132](https://github.com/nextcloud/files_pdfviewer/pull/132) Only call setViewerMode if FileList is available
* [files_texteditor#150](https://github.com/nextcloud/files_texteditor/pull/150) Use correct CSS URL, remove default marked settings and change to GFM rendering
* [firstrunwizard#189](https://github.com/nextcloud/firstrunwizard/pull/189) Use correct method to determine if HTTPS is used

### CODE REVIEW

**Comment by kesselb** [comment]
What about https://github.com/nextcloud/server/pull/15259?

**Comment by kesselb** [comment]
A fix for https://github.com/nextcloud/server/issues/14986 would be cool :sunglasses:

**Comment by MorrisJobke** [comment]
Ready for review 🚀

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
# RC phase (up to one week before the release date)

* [ ] get all the pending backports merged to the stable branches ([check the milestones accross the organisation](https://github.com/issues?utf8=✓&q=is%3Aopen+user%3Anextcloud+archived%3Afalse+milestone%3A%22Nextcloud+13.0.2%22+))
* [ ] sent customer newsletter with security and release date information
* [ ] create the RC packages
* [ ] upload the RC packages to the `/server/prereleases` folder of the download server
* [ ] update the beta channel of the [updater_server](https://github.com/nextcloud/updater_server)
* [ ] test the updater_server on the internal URL (`https://updates.nextcloud.com/internal_updater_server/`)
* [ ] ask in the forums for help (use the [changelog generator script](https://github.com/nextcloud/github_helper#changelog-generator))
* [ ] prepare "What's new" server - [Example](https://github.com/nextcloud/changelog_server/pull/5)

# Release (~1 day before the planned release)

* [ ] prepare blog post, newsletter, social media messages (check the changelog for interesting features/fixes and possible screenshots)
* [ ] update the changelog on the website (use the [changelog generator script](https://github.com/nextcloud/github_helper#changelog-generator))
* [ ] update version number on website (in `strings.php`)
* [ ] update version number in documentation (in `admin_manual/release_schedule.rst`)
* [ ] create the final packages
* [ ] upload the final packages to `/server/prereleases` folder of the download server

## T - 30 minutes

* [ ] copy the final packages to `/server/releases` folder of the download server
* [ ] update the stable channel of the [updater_server](https://github.com/nextcloud/updater_server)
* [ ] test the updater_server on the internal URL (`https://updates.nextcloud.com/internal_updater_server/`)
* [ ] merge the website PR
* [ ] deploy the website PR (maybe update caches)
* [ ] update [wiki page](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule)

## T

* [ ] publish blog posts
* [ ] send newsletter
* [ ] post on social media

# Post processing (non-coding)

* [ ] update the milestones in all repos (use the [milestone updater](https://github.com/nextcloud/github_helper/tree/master/milestoneupdater) for this)
* [ ] update app store releases (see [documentation](https://nextcloudappstore.readthedocs.io/en/latest/prodinstall.html#sync-nextcloud-releases-from-github))
* [ ] update user content proxy of app store (see https://github.com/nextcloud/usercontent.apps.nextcloud.com)
* [ ] update security scanner
* [ ] update owncloud-migration config on update server
* [ ] update install page on website
* [ ] update installer script on download server (see [repo](https://github.com/nextcloud/web-installer))
* [ ] check wikipedia pages for release information - update pages if necessary
* [ ] check wikimedia content for outdated media e.g. screenshots

**Pull request merged**
