### PR TITLE
Reintroduce HackerOne into CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by MariusBluem**
cc @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by schiessle** [comment]
Do we want that all security reports go to hacker one? As far as I know not everything provided by Nextcloud is part of the hacker one program... @LukasReschke your call :wink:

**Comment by MorrisJobke** [comment]
👍

**Comment by mar1u5** [comment]
You are right. But this repository does only contain stuff which is covered by HackerOne (the "core") ... Same applies to the android app :wink: ...because the CONTRIBUTING.md is not global and only for this repository ... I think it would be ok :grin:

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
