### PR TITLE
Fix branch selection in stable22

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Open question: Anything I shall do to https://github.com/nextcloud/server/blob/master/.github/dependabot.yml to make it security updates only on stable22? => https://github.com/nextcloud/server/pull/27648

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
:elephant:

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@nickvergessen force merge needed ?

**Review by danxuliu — APPROVED** [review]
Acceptance test failure should be a hiccup :+1:

**Pull request merged**
