### PR TITLE
Correctly determinate the owner in case of shared external storages

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. add an external storage
2. created a file "shared.txt"
    i. user gets notified
3. modified this file
    i. user gets notified
4. shared it with another user (B)
    i. both users are getting notified
5. user B modified this file
    i. only user B gets notified, not the creator

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Code makes sense.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Failing tests:

```
There were 2 errors:
1) Test\Share20\ManagerTest::testGetAccessList
Error: Call to a member function getUID() on null

/drone/src/github.com/nextcloud/server/lib/private/Share20/Manager.php:1427
/drone/src/github.com/nextcloud/server/tests/lib/Share20/ManagerTest.php:3506

2) Test\Share20\ManagerTest::testGetAccessListWithCurrentAccess
Error: Call to a member function getUID() on null

/drone/src/github.com/nextcloud/server/lib/private/Share20/Manager.php:1427
/drone/src/github.com/nextcloud/server/tests/lib/Share20/ManagerTest.php:3624
```

**Comment by nickvergessen** [comment]
fixed

**Pull request merged**
