### PR TITLE
Update email template for lost password email

### PR DESCRIPTION
**Pull request by MorrisJobke**
* [x] requires #4307 to be merged first (only review the last commit in this PR)
* followup to #4304 and #4244 on our way to fix issue #2071
 
Before and after:

bildschirmfoto 2017-04-11 um 17 14 23
bildschirmfoto 2017-04-11 um 17 12 49

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> requires #4307 to be merged first (only review the last commit in this PR)

https://github.com/nextcloud/server/pull/4308/commits/64873bd4110878f616a1d144311752a97f332c76

I'm here as well open for help with the texts - cc @nextcloud/designers @Espina2

**Comment by nickvergessen** [comment]
> Conflicting files
lib/private/Mail/EMailTemplate.php

**Comment by Espina2** [comment]
Why not something like this?

new password

**Review by schiessle — DISMISSED** [review]
Seems like the plain text version suffers from the same issues we discussed and solved here: https://github.com/nextcloud/server/pull/4307

So I would suggest to wait for the other PR to get merged, then rebase and adjust it.

**Comment by rullzer** [comment]
#4307 is in. Rebase needed

**Comment by MorrisJobke** [comment]
I rebased this one and fixed the plain text email:

> Password reset
> 
> Click the following link to reset your password. If you have not requested the password reset, then ignore this email.
> 
> http://192.168.99.100/server/lostpassword/reset/form/KC0Va7NeBbrnXVK11UVLm/admin
> 
> --
> Nextcloud - ein sicherer Ort für all Ihre Daten
> Dies ist eine automatisch generierte E-Mail, bitte nicht antworten.

bildschirmfoto 2017-04-12 um 15 17 06

**Review by rullzer — APPROVED** [review]
Whee!

**Comment by enoch85** [comment]
Would it be possible to implement @Espina2s fix?

**Comment by eppfel** [comment]
Yeah, @Espina2 copy would be much appreciated. 

Too minor edits:

This ~~reset~~ password _reset_ is only available... 

Or:

This password reset link is only.... 


And 

~~For security,~~ this request...

**Comment by MorrisJobke** [comment]
> Would it be possible to implement @Espina2 fix and use the Sessions + add more text?

Not in this PR. Additional PR for sure, but please keep it small.

**Comment by MorrisJobke** [comment]
@LukasReschke @rullzer Could one of you update the texts like @eppfel proposed? Thanks :)

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
