### PR TITLE
Fix regex for office documents

### LINKED ISSUE #19695: Flow file retention for Office-Documents not saveble
### Steps to reproduce
1. Add a new file retention flow
2. Choose file type is Office Document form the predefined list
3. Hit save button

### Expected behaviour
Flow should be saved without error message

### Actual behaviour
An error occurrs telling that the configuration is invalid and the regular expression used is invalid. As the regex is given from the predefined list item, the regex should be fixed. 

### Server configuration

**Operating system:**
FreeBSD 11.2-STABLE (FreeNAS.amd64)

**Web server:**
nginx/1.16.1

**Database:**
postgres

**PHP version:**
7.3.14

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
source

**Signing status:**
No errors have been found.

**List of activated apps:**
<details>
<summary>Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - admin_notifications: 1.0.2
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - breezedark: 18.0.6
  - calendar: 2.0.1
  - checksum: 0.4.4
  - circles: 0.18.3
  - cloud_federation_api: 1.1.0
  - cms_pico: 1.0.5
  - comments: 1.8.0
  - contacts: 3.1.9
  - dav: 1.14.0
  - deck: 0.8.0
  - dicomviewer: 1.2.1
  - event_update_notification: 1.0.1
  - external: 3.5.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_antivirus: 2.2.1
  - files_automatedtagging: 1.8.0
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_readmemd: 1.1.3
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - forms: 1.1.0
  - group_everyone: 0.1.4
  - groupfolders: 6.0.1
  - impersonate: 1.5.0
  - ldap_write_support: 1.1.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextbackup: 19.12.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.5
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocdownloader: 1.7.6
  - onlyoffice: 4.1.4
  - orcid: 1.1.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.4
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login: 3.1.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.2.0
  - twofactor_totp: 4.1.2
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0 
  - user_ldap: 1.8.0
  - user_saml: 3.0.1
  - viewer: 1.2.0
  - workflowengine: 2.0.0
  - zenodo: 1.1.0  
Disabled:
  - encryption
  - occweb
  - twofactor_admin

</summary>
</details>

**Nextcloud configuration:**
<details>
<summary>{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.intraepigliom.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "orcid",
            "zenodo",
            "admin_notifications",
            "files_readmemd",
            "dicomviewer",
            "twofactor_yubikey",
            "ocdownloader",
            "uploaddetails"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        }
    }
}
</summary>
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:**
Firefox 71.0 (64-Bit)

**Operating system:**
Linux Mint 18.3 'Sylvia' Xfce 64-bit
#### Web server error log
<details>
<summary>Web server error log</summary>

No logs generated
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

no log entries generated
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Failed to save operation workflowengine.js:397:13378
    e https://cloud.intraepigliom.de/apps/workflowengine/js/workflowengine.js?v=6cc944a3-15:397
    c https://cloud.intraepigliom.de/apps/spreed/js/flow.js?v=6cc944a3-15:53
    _invoke https://cloud.intraepigliom.de/apps/spreed/js/flow.js?v=6cc944a3-15:53
    e https://cloud.intraepigliom.de/apps/spreed/js/flow.js?v=6cc944a3-15:53
    B https://cloud.intraepigliom.de/apps/workflowengine/js/workflowengine.js?v=6cc944a3-15:397
    s https://cloud.intraepigliom.de/apps/workflowengine/js/workflowengine.js?v=6cc944a3-15:397

</details>

### PR DESCRIPTION
**Pull request by kesselb**
Fix #19695

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by rullzer** [comment]
rebase ;)

**Comment by kesselb** [comment]
> rebase ;)

Done @rullzer

**Pull request merged**
