### PR TITLE
Fix jsunit tests

### PR DESCRIPTION
**Pull request by kesselb**
JSUnit tests are failing for some reason. It seems to be related to a new karma-coverage version published a few hours ago.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Thanks! :rocket:

**Comment by kesselb** [comment]
Shit :see_no_evil:  `^2.0.1` is also matching `2.0.2` :rofl: Probably the error is gone if you use a newer node version for running the tests. I'm not able to reproduce locally with Node 10.3.

**Review by MorrisJobke — APPROVED** [review]
Change makes sense 👍

**Pull request merged**
