### PR TITLE
Only use readable chars in Share Tokens

### LINKED ISSUE #5688: Avoid look-alike characters in shared link token
From time to time, I need to manually type a shared link. Such situations are usually rare but urgent.

Bonus point: use only lowercase alphabetical characters, i. e. no uppercase and no digits because it impedes typing the token especially on mobile touchscreen keyboard.

It's better to make token longer to have same complexity rather than use bigger but inconvenient character sets.

This issue duplicates Discourse topic: https://help.nextcloud.com/t/feature-request-avoid-look-alike-characters-in-shared-link-token/15227 — I haven't found consistent way of making feature requests, I apologize for the extra noise.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #5688

### CODE REVIEW

**Comment by tcitworld** [comment]
Could you also patch https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalDavBackend.php#L1928 ?

**Comment by nickvergessen** [comment]
Done, please review @tcitworld

**Review by schiessle — APPROVED** [review]
looks good

**Review by rullzer — APPROVED** [review]
yeah sure... fine by me... just note that this does bring down the possible combinations from 768 septillion to 54 septellion.

Or from ~89 bits of entropy down to ~85.

All still very much enough imo.

**Review by tcitworld — APPROVED** [review]
👍

**Pull request merged**
