### PR TITLE
invert colors of favicons to match header and log in site, white on blue

### PR DESCRIPTION
**Pull request by jancborchardt**
Before & after
capture du 2016-06-10 18-08-22

favicon-touch favicon-touch

Fits a lot better with the rest like header and log in view. Please review @nextcloud/designers @jospoortvliet @skjnldsv 
Also cc @AndyScherzinger regarding icon for the Android app. :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Regarding Android as well – it will work a lot better with the header color in the app switcher so that theres only the white icon, and it’s a lot more visible on the home screen that way. :)

**Comment by mar1u5** [comment]
:+1:

**Comment by skjnldsv** [comment]
Don't know what am I doing here, but looks great! :+1: 
ps: you can gain a few kb by optimizing your svgs with svgo :)

**Comment by jancborchardt** [comment]
@mar1u5 please only merge stuff after it received two :+1: :)

**Comment by skjnldsv** [comment]
Says the merging machine! ;)
https://github.com/owncloud/mail/pull/1434#issuecomment-212583693

**Comment by mar1u5** [comment]
Shit ... mistaken with #40 😒 Will never happen again 😉 @jancborchardt

**Comment by jancborchardt** [comment]
@skjnldsv we forked ownCloud to Nextcloud. If you want to hear about the reasons check https://www.youtube.com/watch?v=iMfokaX2r8g :)
Welcome again – I also invited you to the Nextcloud design team, you should have gotten an email. :)

Also, I optimized the svgs with scour, as in the image-optimization.sh script. ;)

**Comment by skjnldsv** [comment]
```
$ svgo favicon-mask.svg 
Done in 103 ms!
1.331 KiB - 32.9% = 0.894 KiB
```

We can do better!

**Comment by jancborchardt** [comment]
Oi, nice! Isn’t that very lossy at some point though? Cause scour already is.

**Comment by skjnldsv** [comment]
Don't think so, I think it's optimising the redundancy of the code. Didn't looked too much to be honest :/

**Comment by jancborchardt** [comment]
Ok, I guess we should play around with it on new icons we create. I would not compress all files right now with it because I’m pretty sure in the past I read that scour is lossy. And I also noticed some tiny tiny different position values when I opened files back up. Nothing really important but still – if it’s an even crazier compression we should check it on a case-by-case basis. Is that cool? :)

**Comment by AndyScherzinger** [comment]
Integrated on android master :) https://github.com/nextcloud/android/commit/f63d421777751743845bf5139484c97803f4b8ab

**Pull request merged**
