### PR TITLE
Save sharing note on close or submit

### LINKED ISSUE #18452: 18b2: share note auto-save useless
The share note auto-save is completely useless. Unless you're a super-fast 10-finger-typer, it's auto-saving super-quickly and sending an email right away.
Also deleting the hint text (see also https://github.com/nextcloud/server/issues/18451) with the backspace key auto-saves all the time.

Example: The following video generated eight emails:

Peek 2019-12-17 18-35

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #18452

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by nickvergessen** [comment]
Needs a rebase after #18859

**Comment by jancborchardt** [comment]
Will increasing to 1000 really fix this? For slow typers it’s still not so good, or if you change it after some thinking.

Either let’s say 5000, or kill it altogether as discussed? cc @rullzer

**Comment by rullzer** [comment]
Yep, can't we kill it all together?
So either on enter on when you clone the menu?

**Comment by skjnldsv** [comment]
On it

**Comment by skjnldsv** [comment]
Done!
@nickvergessen the escape to cancel will be done separately as it requires a vue component update

**Review by rullzer — APPROVED** [review]

**Pull request merged**
