### PR TITLE
Clean up 2FA provider registry when a user is deleted

### LINKED ISSUE #18723: User credentials und 2FA providers are not properly deleted
### Steps to reproduce
1. Create a new user
2. Set up an F2A method for this user
3. Delete this user again
4. Create a new user with the same name
5. Log in as new user

### Expected behaviour
The User is logged in

### Actual behaviour
The user is asked to authenticate with the second factor (which should not exist anymore)

I looked into the databases `oc_credentials` and `oc_twofactor_providers`, there were still entries of deleted users. After these were deleted, this bug did not occur anymore.

### Server configuration

**Operating system:** Arch Linux

**Web server:** nginx 1.16.1

**Database:** MariaDB 10.4.11

**PHP version:** 7.3.12

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older NC version

**Where did you install Nextcloud from:** ZIP file from the NC webpage

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - checksum: 0.4.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - deck: 0.7.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.5
  - impersonate: 1.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 0.21.0
  - news: 14.1.0
  - notes: 3.1.1
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ownbackup: 19.9.0
  - password_policy: 1.7.0
  - polls: 0.10.4
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - ransomware_protection: 1.5.1
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.3
  - spreed: 7.0.2
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.1.1
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - accessibility
  - encryption
  - firstrunwizard
  - nextcloud_announcements
  - recommendations
  - support
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 1,
            "timeout": 1.5
        },
        "logtimezone": "Europe\/Berlin",
        "trashbin_retention_obligation": "auto,90",
        "versions_retention_obligation": "90,auto",
        "skeletondirectory": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 4,
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "simpleSignUpLink.shown": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "twofactor_enforced_excluded_groups": [
            "***REMOVED SENSITIVE VALUE***"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### PR DESCRIPTION
**Pull request by ChristophWurst**
Partly fixes https://github.com/nextcloud/server/issues/18723

cc @TalviT

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
So clean.... :heart_eyes:

**Comment by rullzer** [comment]
master is NC19 now.
Please backport if it needs to go into 18

**Review by georgehrke — APPROVED** [review]
Code looks good
🐘

**Pull request merged**
