### PR TITLE
Adjust background image to the one used on the website

### PR DESCRIPTION
**Pull request by jancborchardt**
Another step towards more consistency between website and app. :) Also adjusted the button style to use the actual theming color instead of a lighter shade, which looked a bit off always.

Please review @nextcloud/designers @MorrisJobke @LukasReschke, this uses the background image made by @Espina2 for https://nextcloud.com

Before:

screenshot from 2017-08-29 15-27-22

After:
screenshot from 2017-08-29 16-06-08

Works well with theming cc @nextcloud/theming 
screenshot from 2017-08-29 16-05-42

### CODE REVIEW

**Review by MariusBluem — APPROVED** [review]
Really love it :heart:

**Review by MorrisJobke — APPROVED** [review]
Awesome sauce :rocket:

**Comment by Espina2** [comment]
Looks good to me. 🚀

**Review by Espina2 — APPROVED** [review]

**Comment by dartcafe** [comment]
Hey @jancborchardt, 
great work. I like it. But maybe some enhancement is to be done, if a light theme is choosen. I tried it on a black and a white theme. 
black_theme
white_theme

**Comment by MorrisJobke** [comment]
@dartcafe Could you open a new ticket for this? Thanks

**Comment by skjnldsv** [comment]
Perfect!!!

**Pull request merged**
