### PR TITLE
Move OC_Mount_Config to proper classname and remove OC::$CLASSPATH us…

### PR DESCRIPTION
**Pull request by MorrisJobke**
…age in files_external

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Plus those 3 apps use it as well, but it's private namespace anyways:

Bildschirmfoto 2020-07-09 um 23 39 00

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> Plus those 3 apps use it as well, but it's private namespace anyways:
> 
> Bildschirmfoto 2020-07-09 um 23 39 00

I notified the authors of all three apps to update their apps.

**Review by rullzer — APPROVED** [review]
:see_no_evil: :elephant:

**Comment by MorrisJobke** [comment]
Let's put it also in https://github.com/nextcloud/server/issues/20953

**Pull request merged**
