### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by andypl78**
Adjusting the size of fonts.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Heya @andypl78! :)

What’s the reason for this change? And why 15px?
The log in view should be big and welcoming and easy to read. 20px is our standard text size for h2 headings, so it fits with the style.

cc @nextcloud/designers

**Comment by andypl78** [comment]
See how it looks ugly and the whole text is not visible

20px
nt2

15px look better 
nt1

**Comment by eppfel** [comment]
mh, that's more an issue of localization and width, than font-size. With just changing font-size, the padding looks odd. Is there no way to shorten the translation? Is this happening in other locales, too?

**Comment by andypl78** [comment]
That is why I gave the fix to reduce the font size.
What to translate this is correct in Polish.
I have not tested with other translations

**Comment by eppfel** [comment]
I think 14 characters is not that much, so we definitely could improve this:
bildschirmfoto 2016-12-16 um 14 08 59
I think 15px is just too small, mh...

**Comment by andypl78** [comment]
On Onedrive from Microsoft text is smaller and appears to be more orderly.
I checked on the 17-inch laptop screen and 24 inch screen FHD and I think 15px is ok value.

Of course, I myself changed in the style.css but all the time I get information about the inconsistencies css file in the panel Nextcloud

**Comment by jancborchardt** [comment]
Because keeping it short and concise is important anyway.

**Comment by LukasReschke** [comment]
Closing to keep the PR counter low. If still required please reopen.

**Pull request closed without merging**
