### PR TITLE
Add icon for the theming app

### PR DESCRIPTION
**Pull request by eppfel**
As discussed in #856

### CODE REVIEW

**Comment by rullzer** [comment]
CC: @nextcloud/designers

**Comment by rullzer** [comment]
I like it!
viewBox set. :+1:

**Comment by MorrisJobke** [comment]
Tested and looks great 👍

**Comment by MorrisJobke** [comment]
I created backports for this image :)

And thanks @eppfel for this logo :)

**Comment by jancborchardt** [comment]
Good stuff @eppfel :)

**Pull request merged**
