### PR TITLE
Correct name in Console Application.php

### PR DESCRIPTION
**Pull request by blizzz**
see changes :)

@rullzer @MorrisJobke

### CODE REVIEW

**Comment by blizzz** [comment]
needs backports @karlitschek

**Comment by MorrisJobke** [comment]
:+1:

**Comment by icewind1991** [comment]
👍

**Comment by rullzer** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by karlitschek** [comment]
please backport

**Comment by MorrisJobke** [comment]
stable9 backport is not needed for this

**Pull request merged**
