### PR TITLE
Remove js navigation on alternative login click

### PR DESCRIPTION
**Pull request by zorn-v**
First of all it is no needed, as it already have href and work via native browser way.
Moreover it can bring some problems. If you set custom click handler (to open popup for example) and prevent browser to go by href you need some tricks instead simple `e.preventDefault()`.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Make sense!

@CarlSchwan since you did this code, was there any reason here?

**Comment by zorn-v** [comment]
Will be nice to be merged, but v25 already "poisoned" and you should do something like `removeEventListener` or use `javascript:;` or `#` in href. 
So everyone should do it for supporting v25.
But it is not right and should be fixed for future generations )

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by szaimen** [comment]
Somehow my rebase failed but I cherry-picked and will handle this in https://github.com/nextcloud/server/pull/36065. Thanks for your PR @zorn-v ! :)

**Pull request closed without merging**
