### PR TITLE
Password modification and password policy features for user_ldap

### PR DESCRIPTION
**Pull request by GitHubUser4234**
Please refer to owncloud/core#25114 .

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Same as #519 -> closing

**Comment by GitHubUser4234** [comment]
@MorrisJobke it's a related but different feature and different branch. As long as #519 stays open, this one should also.

**Comment by MorrisJobke** [comment]
> @MorrisJobke it's a related but different feature and different branch. As long as #519 stays open, this one should also.

It has the exact same commits, so it is exactly the same. There is not a single difference. Could you please clarify what the difference of those two PRs should be?

**Comment by MorrisJobke** [comment]
> There is not a single difference. Could you please clarify what the difference of those two PRs should be?

Sorry if this sounds rude, it shouldn't, but I can't spot a difference 😢

**Comment by GitHubUser4234** [comment]
@MorrisJobke You are right, currently the committed source code is the same because this is a branch using the code of #519 as its base. However there are further commits outstanding that will make it different from it's base. Please see above:

_GitHubUser4234  wants to merge 2 commits into nextcloud:master from GitHubUser4234:ldap_password_pr_

"ldap_password_pr" is the branch name as opposed to "master" in #519

Thanks.

**Comment by MorrisJobke** [comment]
> However there are further commits outstanding that will make it different from it's base.

But until there is no additional commit in the PR it makes no sense to keep two identical PRs open. Feel free to open a new PR once those additional commits are available for review :)

**Pull request closed without merging**
