### PR TITLE
Cleanup share by mail a bit

### PR DESCRIPTION
**Pull request by rullzer**
* Moved to ned IBootstrap
* Register everything via the capabilities api (So clients can use it as
  well)
  - This applies to the enforcing passwords
* Updated the sharing js code to use it
* removed app.php
* removed unused settings now
* typehints
* strict typing

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
CC: @tobiasKaminsky for the capabilities. Just check them before and after this PR. Now we have the info if the password is enforced for this share type.

**Review by ChristophWurst — APPROVED** [review]
:koala: :rocket:

**Comment by MorrisJobke** [comment]
I fixed the CS warnings 👍

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Comment by skjnldsv** [comment]
Thanks for doing this! :hugs:

**Pull request merged**
