### PR TITLE
Delete calendar subscriptions as well when deleting user

### LINKED ISSUE #28418: Calendar subscriptions Survive User deletion
### Steps to reproduce

1. make a user
2. subscribe to a calendar url
3. delete the user
4. create a new user with the same name

### Expected behaviour
The calendar subscription is gone (as this is a new user)

### Actual behaviour
The new user has the calendar subscription of the old one

Nexctloud version : 22.1.0
Calendar version : 2.3.1
Database backend: postgresql 13.3

### PR DESCRIPTION
**Pull request by tcitworld**
Who forgot that... Oh wait, that's me. (https://github.com/nextcloud/server/pull/1545 was after https://github.com/nextcloud/server/pull/1197) :see_no_evil: 

Closes #28418

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by tcitworld** [comment]
Now that I think about it, should we add a repair job to delete subscriptions whose URIs don't match any existing users?

**Review by LukasReschke — APPROVED** [review]

**Comment by szaimen** [comment]
Merge?

**Comment by tcitworld** [comment]
Repair job in #28716

**Pull request merged**
