### PR TITLE
Fix whitespace between sharee name and icons #2384

### LINKED ISSUE #2384: Too much whitespace between  sharee name and icons
spectacle n20685

The names are elided, but there is still  so much space :(

@nextcloud/designers

### PR DESCRIPTION
**Pull request by skjnldsv**
Too much whitespace between sharee name and icons #2384
capture d ecran_2016-11-29_07-05-57

@blizzz @nextcloud/designers

### CODE REVIEW

**Comment by blizzz** [comment]
That's cool, it works now nicely on big as well as small windows. One last glitch is that the *can edit* checkbox and the ``…`` are not right-aligned anymore (on Firefox). Is this still possible to do?

**Comment by skjnldsv** [comment]
@blizzz Not sure if related to this issue only. I see every checkboxes mis-aligned with their label, are you too?

**Comment by schiessle** [comment]
It becomes more obvious with short user names.

This is how it looks on master:

share1

and this is how it looks on this branch:

share2

**Comment by blizzz** [comment]
@skjnldsv in https://github.com/nextcloud/server/issues/2384  they were all right-aligned

**Comment by skjnldsv** [comment]
Oh by bad, i didn't understood what you meant. i was thinking about the checkbox beeing misaligned with the text, like 3/4 px above :)

Will fix asap!

**Comment by skjnldsv** [comment]
Here you go :)
capture d ecran_2016-11-29_10-52-22

**Comment by skjnldsv** [comment]
@jancborchardt, @blizzz, @rullzer, @MorrisJobke 
Why do we have similar css values on share.css and sharetabview.css?

https://github.com/nextcloud/server/blame/master/apps/files_sharing/css/sharetabview.css#L57
https://github.com/nextcloud/server/blame/master/core/css/share.css#L80

**Comment by schiessle** [comment]
Almost done ;-)

Here it looks short before the user name gets shortened

share1

Everything looks good. But if I continue to reduce the size of the window the permissions get align to the left as soon as the user name gets shortened:

share2

**Comment by skjnldsv** [comment]
@schiessle Doesn't happen in chromium for me :/
Testing on firefox right now.

**Comment by rullzer** [comment]
@skjnldsv it is a email share.

**Comment by skjnldsv** [comment]
@rullzer I tried but I still have the checkboxes :)

**Comment by MorrisJobke** [comment]
> @rullzer I tried but I still have the checkboxes :)

@schiessle @skjnldsv The checkboxes for email shares are only there for folders. If it is  a file then it's not available ;)

**Comment by skjnldsv** [comment]
Fixed!

**Comment by MorrisJobke** [comment]
Tested in Firefox, Safari, IE11, Edge and Chrome 👍

**Comment by skjnldsv** [comment]
Build failed on mysqlmb4PHP 5.6?

**Comment by MorrisJobke** [comment]
> Build failed on mysqlmb4PHP 5.6?

Ignore it - I'm already debugging: #2401

**Comment by blizzz** [comment]
awesome @skjnldsv 👍

**Comment by jancborchardt** [comment]
@skjnldsv you’re killing it! :) If you had Twitter I would have linked to you in https://twitter.com/jancborchardt/status/803906610280202240 instead of just your name ;)

**Comment by skjnldsv** [comment]
@jancborchardt No twitter! It's evil ;)

**Comment by jancborchardt** [comment]
@skjnldsv I know! :) I already don’t use Facebook ;)

Soon we can all communicate via Nextcloud ;D

**Pull request merged**
