### PR TITLE
fixes the return type of BeforeUserLoggedInEvent

### PR DESCRIPTION
**Pull request by blizzz**
the constructor receives the login name only

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
backport?

**Comment by blizzz** [comment]
> backport?

according to the @since info, the event is there as of NC 18.

**Review by rullzer — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> /backport to stable18

didn't see that before. I wanted to suggest this :)

**Pull request merged**
