### PR TITLE
Fix mobile menu on users management

### LINKED ISSUE #14252: Missing hamburger menu in mobile mode
### Steps to reproduce
1. Log-in as an admin user with a smartphone/tablet browser or in a small size browser
2. Go to Users settings
3. try to add new user or group

### Expected behaviour
I can create a new user or a new group

### Actual behaviour
menu for new user or new group disappears and can't add a new user or a new group, I can only see users already active

### Server configuration
**Nextcloud version:** 15.0.4

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #14252 

Capture d’écran_2019-04-02_15-10-25

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Doesn't work for me somehow 🤷‍♂️ It simply does not show up even after cleaned browser caches.

**Review by ChristophWurst — APPROVED** [review]
Works for me on FF

**Comment by MorrisJobke** [comment]
Not here (tested with FF and Safari - ignore the failing avatar - there the PHP build-in server crashes, but only for this request):


Bildschirmfoto 2019-04-02 um 16 22 53

**Review by rullzer — APPROVED** [review]
Works for me as well.
Lets ignore @MorrisJobke

**Comment by rullzer** [comment]
But conflicts!

**Comment by Octopus2** [comment]
I am on 16 RC1 and this fix doesn´t work for me on my android device (Galaxy S7, Android 8, Chrome)....

**Comment by skjnldsv** [comment]
@Octopus2 make sure to clear your cache :)

**Comment by Octopus2** [comment]
I cleaned the Chrome-Cache and it still doesn´t work.
Just tried it with Firefox on Windows 7 and same behavior when i resize the browserwindow. No menu/Burger on the left in user- and appmanagement.... 
Even tried this but nothing changes: https://github.com/nextcloud/server/issues/10436#issuecomment-408896858

Anything else I can do to test?

**Comment by Octopus2** [comment]
sorry, correct is for my setup with this problem: 16.0.1 RC 1

**Pull request merged**
