### PR TITLE
Remove duplicate unit test in sharing that checks for group permission updates

### PR DESCRIPTION
**Pull request by MorrisJobke**
* it was skipped anyways
* it is covered for example in build/integration/sharing_features/sharing-v1-part3.feature#L517-L548 (see https://github.com/nextcloud/server/blob/54f8f75f6f82ca102b1cfdb88caf0d06e6c9ba31/build/integration/sharing_features/sharing-v1-part3.feature#L517-L548)
* more permission updates are tested in the webdav section, where an OCS API is called and the WebDAV response is checked for the properly changed permission
* nice side effect: removes ~1300 lines of logs in the CI output (out of 2100)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:+1: for removing *skipped tests*

but a test coverage overlap from integration tests on unit tests is expected and wanted. in general as much as possible should be tested with unit tests and integration tests should be rare. then we can actually make tests fast, independent of environments as much as possible and easily runnable locally :pray:

**Comment by MorrisJobke** [comment]
> but a test coverage overlap from integration tests on unit tests is expected and wanted. in general as much as possible should be tested with unit tests and integration tests should be rare. then we can actually make tests fast, independent of environments as much as possible and easily runnable locally 🙏

True point, but having to setup the whole stack for tests that are inside a folder called "unit" doesn't make them unit tests. I just want to reduce complexity here. The maintenance of those integration tests inside the "unit" folder is huge and it's already fully covered by easier to maintain integration tests, that run nearly as fast as this one here.

**Comment by PVince81** [comment]
the "unit" test seemed more thorough though with its extensive data provider ?

**Comment by MorrisJobke** [comment]
> the "unit" test seemed more thorough though with its extensive data provider ?

Yes - we could try to add all combinations of before and after permissions to the other integration tests as well, but the typical cases (upload only, read only, all permissions, reshare forbidden) are already covered and having them tested there additionally doesn't add much value IMO.

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
