### PR TITLE
Call proper function when fetching link shares in the breadcrumb view

### LINKED ISSUE #13056: Clicking on the share icon in breadcrumbs puts an error into the console
```
TypeError: shareModel.hasLinkShare is not a function[Weitere Informationen] sharebreadcrumbview.js:87:9
_onClick/<
https://nextcloud16.local/apps/files_sharing/js/sharebreadcrumbview.js:87:9
triggerEvents
https://nextcloud16.local/core/vendor/backbone/backbone.js:369:32
triggerApi
https://nextcloud16.local/core/vendor/backbone/backbone.js:356:19
eventsApi
https://nextcloud16.local/core/vendor/backbone/backbone.js:155:16
Events.trigger
https://nextcloud16.local/core/vendor/backbone/backbone.js:346:5
render/<
https://nextcloud16.local/apps/files_sharing/js/sharetabview.js:77:6
```

@nextcloud/javascript 

also affects 15, didnt notice any real impact, but i guess the icon doesnt display as intended?

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes call to undefined method.

> TypeError
> shareModel.hasLinkShare is not a function

Steps to reproduce:
1. Create a folder
2. Go into the folder
3. Click on the share icon in the breadcrumbs

Fixes #13056

### CODE REVIEW

**Comment by juliushaertl** [comment]
Sentry issue: [NEXTCLOUD-H5](https://sentry.rullzer.com/sentry/nextcloud/issues/831/)

**Review by skjnldsv — APPROVED** [review]
:see_no_evil:

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Comment by skjnldsv** [comment]
```
ERROR: 'Unhandled promise rejection', TypeError: null is not an object (evaluating 'xml.getElementsByTagNameNS')
_getSabreException@http://localhost:9876/base/core/js/files/client.js?45fcb98ff347716e68e4804dd65d22a9aee6777e:9:16109
http://localhost:9876/base/core/js/files/client.js?45fcb98ff347716e68e4804dd65d22a9aee6777e:9:24521
o@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:53950
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:54095
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:51:98901
ERROR: 'Unhandled promise rejection', TypeError: null is not an object (evaluating 'xml.getElementsByTagNameNS')
_getSabreException@http://localhost:9876/base/core/js/files/client.js?45fcb98ff347716e68e4804dd65d22a9aee6777e:9:16109
http://localhost:9876/base/core/js/files/client.js?45fcb98ff347716e68e4804dd65d22a9aee6777e:9:24521
o@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:53950
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:54095
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:51:98901
..................................................................
ERROR: 'Unhandled promise rejection', TypeError: null is not an object (evaluating 'xml.getElementsByTagNameNS')
_getSabreException@http://localhost:9876/base/core/js/files/client.js?45fcb98ff347716e68e4804dd65d22a9aee6777e:9:16109
http://localhost:9876/base/core/js/files/client.js?45fcb98ff347716e68e4804dd65d22a9aee6777e:9:19225
o@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:53950
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:54095
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:51:98901
.............
ERROR: 'Unhandled promise rejection', TypeError: undefined is not an object (evaluating 'fileList.isEmpty')
http://localhost:9876/base/apps/files_trashbin/tests/js/filelistSpec.js?5fd90656cff4f49039c67b7230239608a2d9fa60:351:21
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:39:47789
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:39:45231
fireWith@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:39:46034
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:39:47909
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:39:45231
fireWith@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:39:46034
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:39:48208
http://localhost:9876/base/core/js/files/client.js?45fcb98ff347716e68e4804dd65d22a9aee6777e:9:28741
o@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:53950
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:54095
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:51:98901
ERROR: 'Unhandled promise rejection', TypeError: undefined is not an object (evaluating 'fileList.findFileEl')
http://localhost:9876/base/apps/files_trashbin/tests/js/filelistSpec.js?5fd90656cff4f49039c67b7230239608a2d9fa60:333:21
o@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:53950
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:54095
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:51:98901
ERROR: 'Unhandled promise rejection', TypeError: undefined is not an object (evaluating 'fileList.findFileEl')
http://localhost:9876/base/apps/files_trashbin/tests/js/filelistSpec.js?5fd90656cff4f49039c67b7230239608a2d9fa60:371:21
o@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:53950
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:54095
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:51:98901
ERROR: 'Unhandled promise rejection', TypeError: undefined is not an object (evaluating 'fileList.isEmpty')
http://localhost:9876/base/apps/files_trashbin/tests/js/filelistSpec.js?5fd90656cff4f49039c67b7230239608a2d9fa60:393:21
o@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:53950
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:54095
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:51:98901
................................................................................
22 01 2019 12:31:25.555:WARN [web-server]: 404: /svg
...................22 01 2019 12:31:25.714:WARN [web-server]: 404: /svg
...........................
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Sharing.ShareBreadCrumbView tests Rendering Add link share to user share FAILED
	Expected 1 to equal 0.
	apps/files_sharing/tests/js/sharedbreadcrumviewSpec.js:235:54
	Expected 0 to equal 1.
	apps/files_sharing/tests/js/sharedbreadcrumviewSpec.js:237:54
......................................
ERROR: 'Unhandled promise rejection', TypeError: undefined is not an object (evaluating 'url.indexOf')
parseIdFromLocation@http://localhost:9876/base/core/js/oc-backbone-webdav.js?eb6c6fbf288c2521fa6d474b8d5ae163ee4eee2d:9:2145
parsePropFindResult@http://localhost:9876/base/core/js/oc-backbone-webdav.js?eb6c6fbf288c2521fa6d474b8d5ae163ee4eee2d:9:1904
http://localhost:9876/base/core/js/oc-backbone-webdav.js?eb6c6fbf288c2521fa6d474b8d5ae163ee4eee2d:9:4933
o@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:53950
http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:46:54095
u@http://localhost:9876/base/core/js/dist/main.js?5eb97d6cf4ea8eaa6eff53f9a2a9ca1ae5ce0ca2:51:98901
.................................................................
PhantomJS 2.1.1 (Linux 0.0.0): Executed 1067 of 1071 (1 FAILED) (skipped 4) (12.732 secs / 12.404 secs)
```

**Comment by juliushaertl** [comment]
Fixed the failing tests, however those `Unhandled promise rejection` messages appear on master as well: https://github.com/nextcloud/server/issues/13743

**Review by danxuliu — APPROVED** [review]
Tested and works :+1: 

Fixes #13056

**Comment by rullzer** [comment]
So this can go in?

**Comment by danxuliu** [comment]
>  So this can go in?

I think so.

**Pull request merged**
