### PR TITLE
fix(UnifiedSearch): Focus search input on open

### LINKED ISSUE #47056: [Bug]: Advanced search does not focus input when opened
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When opening the advanced search modal there is no focus on the search input. It makes searching very tedious.

### Steps to reproduce

1. Press *Ctrl+f* **OR** click on the magnifier icon at the top right

### Expected behavior

Adanced search opens, input field is focused

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

cc @Fenn-CS

### PR DESCRIPTION
**Pull request by nfebe**
Resolves : https://github.com/nextcloud/server/issues/47056

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Nice!

**Review by artonge — APPROVED** [review]

**Comment by solracsf** [comment]
/backport https://github.com/nextcloud/server/pull/47319/commits/cf59575120bee70e7573f94251d7b08bbd07e0a2 to stable29

**Pull request merged**
