### PR TITLE
properly block file upload to non-active filelist

### PR DESCRIPTION
**Pull request by icewind1991**
This fixes users being able to upload by dragging files into custom filelists (recent, favorites, etc).

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by ChristophWurst — APPROVED** [review]
Awesome! LGTM

**Comment by MorrisJobke** [comment]
JSUnit tests fail 👎

**Comment by icewind1991** [comment]
> JSUnit tests fail

Fixed

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@icewind1991 Could you create the backport to stable12 at least?

**Pull request merged**
