### PR TITLE
[stable22] Increase email main buttons width for non-english languages

### PR DESCRIPTION
**Pull request by solracsf**
Manual backport of https://github.com/nextcloud/server/pull/30653

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by acsfer** [comment]
@skjnldsv merge to final?

**Comment by acsfer** [comment]
@CarlSchwan is this good?

**Review by CarlSchwan — APPROVED** [review]
Looks good from my side and the tests are now happy :)

**Pull request merged**
