### PR TITLE
Make dashboard installable as Chrome desktop PWA

### PR DESCRIPTION
**Pull request by nhirokinet**
Tried to address https://github.com/nextcloud/server/issues/8563.

### CODE REVIEW

**Comment by lazerl0rd** [comment]
I gave this a try and while I do have #23520 applied, Chromium reports that it failed to get (_GET_, hehe) the Manifest icon:

`Failures: Manifest icon failed to be fetched.`

I manually tried to reach the URL stated in the manifest (`/apps/theming/image/logo?v=51`) and got a copy of the favicon (as a PNG).

Oh, and I had to add this to the NGINX server block:

```
location ~* (serviceworker\.js)$
{
        add_header Service-Worker-Allowed "/";
}
```

**Comment by nhirokinet** [comment]
@lazerl0rd Oh, I've forgotten that I changed nginx.conf for that. Thank you for your comment!
add_header must be added because js file is served as static file.

**Comment by nhirokinet** [comment]
For `/apps/theming/image/logo?v=51` I couldn't find it in manifest in my environment. `/apps/theming/favicon?v=8` and `/apps/theming/icon?v=8` are referred. Did you find the URL in `/apps/theming/manifest`?

**Comment by lazerl0rd** [comment]
> 
> 
> For `/apps/theming/image/logo?v=51` I couldn't find it in manifest in my environment. `/apps/theming/favicon?v=8` and `/apps/theming/icon?v=8` are referred. Did you find the URL in `/apps/theming/manifest`?

Yupp, my manifest is as follows:

image

I'm not sure if it's a bug related to my theming options but here they are:

image

(the logo, header image, favicon, and login image are all manually set to different images). And yeah, I do have php-imagick up and running but Nextcloud didn't seem to auto-generate anything beforehand (maybe it's not working, for some reason).

PS: I manually just applied your two patches on top of the latest stable Nextcloud, heh. Please do inform me if that means I'm missing something.

**Comment by nhirokinet** [comment]
I'm not sure what is happening on your server, but if you mean `/apps/theming/favicon?v=51` returns the icon with not 512x512 size, I met the same situation while my setup.

Auto resize in /app/theming/favicon requires php-imagick, with SVG support. In my Ubuntu 20.04 environment I needed to install libmagickcore in addition to php-imagick.

**Comment by lazerl0rd** [comment]
> 
> 
> I'm not sure what is happening on your server, but if you mean `/apps/theming/favicon?v=51` returns the icon with not 512x512 size, I met the same situation while my setup.
> 
> Auto resize in /app/theming/favicon requires php-imagick, with SVG support. In my Ubuntu 20.04 environment I needed to install libmagickcore in addition to php-imagick.

The thing is, I have `php-imagick` and `imagemagick` installed (_I use Arch, btw_ - this means that the library for imagick is integrated with the main package).

About my previous message, the logo/favicon/icon/whatever version number (`?v=X`) is irrlevant. It is used to denote a change and force the browser cache to "collect" the new image.

About the `/apps/theming/image/logo?v=51` - please do ignore that. I was mixing up a few different images that Nextcloud provides by mistake.

I manually tried to reach /apps/theming/icon?v=X and /apps/theming/favicon?v=X which are defined in my manifest and can successfully reach them (albeit the same image appearing). I'm not sure if this is due to me passing Nextcloud PNGs instead of SVGs for the custom favicon/header/icon/etc. images.

**Comment by skjnldsv** [comment]
> ```
> location ~* (serviceworker\.js)$
> {
>         add_header Service-Worker-Allowed "/";
> }
> ```

This can be handled by nextcloud directly with proper csp and serving the service worker. 
https://github.com/nextcloud/photos/blob/a69d3ef71a675094d8bd2586747800763a339e4c/appinfo/routes.php#L27
https://github.com/nextcloud/photos/blob/a69d3ef71a675094d8bd2586747800763a339e4c/lib/Controller/ApiController.php#L80

**Comment by nhirokinet** [comment]
@skjnldsv Thank you for your advice, I modified this pull request not to require additional nginx.conf lines.

**Comment by skjnldsv** [comment]
Thanks!

Could you elaborate on how to test this?
And the purpose of said service worker? Because It looks like it is just catching and forwarding any fetch?
Thanks! :)

**Comment by nhirokinet** [comment]
Testing environment is
  - server with proper HTTPS certificate
  - client with Google Chrome 86.0.4240.111 official build, 64bits, Windows 10.

Then install button is available on the address bar.

> And the purpose of said service worker? Because It looks like it is just catching and forwarding any fetch?

Surely,  it is just catching and forwarding any fetch, as you said. This is just to be installable PWA for desktop Chrome. Of course this is not ideal PWA, but I thought better than current status.

**Comment by szaimen** [comment]
@nhirokinet is this for any app for "just" for the dashboard app? Great would be if it would work with any app because then not every app would need to implement this feature on its own :)

**Comment by nhirokinet** [comment]
@szaimen This PR only works for dashboard, because manifest.json is already targeting dashboard.

Well... actually I want some features like non-official audio player to be run under PWA.

This pull request is intended not to make additional prevention for other app, but still giving nothing to enable other app.

In my limited idea at least:

- manifest.json must be hosted by each app. Maybe adding some modification should be added to core to enable freely direct manifest.json to each app.
- some interface to direct files to cache. this PR caches nothing, but for proper PWA both core js/img files and app data should be cached.

**Comment by szaimen** [comment]
Superseded by https://github.com/nextcloud/server/pull/28459

**Pull request closed without merging**
