### PR TITLE
debug drone

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Seems to be a Heisenberg bug ... let's ramp up the count of executions.

**Comment by MorrisJobke** [comment]
```
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #4 (array(''), '', 'yes', true, true, array(0, 1, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #5 (array('folder'), '', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #6 (array(0), '', 'yes', true, true, array(0, 1, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #7 (array('call'), '', 'yes', true, true, array(0, 1, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #8 (array('folder'), '', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #9 (array('folder', 0), '', 'yes', true, false, array(0), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #10 (array('folder', '0'), '', 'yes', true, false, array(0), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #11 (array('folder', 1), '', 'yes', true, false, array(1), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #12 (array('folder', 12), '', 'yes', true, false, array(), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #13 (array('folder', 'foobar'), '', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #14 (array('folder', array(0, 1, 2)), '', 'yes', false, false, array(0, 1), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #15 (array('folder', array(0, 1)), '', 'yes', false, false, array(0, 1), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #16 (array('folder', array(0, 1, 6, 4)), '', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #17 (array('folder', array(0, 1, 6, 4)), '', 'yes', false, false, array(0, 1), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #18 (array('folder', array(0, 1, 6, 4)), '', 'yes', true, false, array(0, 6), false, true, false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #19 (array('folder', array(0, 1, 6, 4)), '', 'yes', false, true, array(0, 4), false, true, false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #20 (array('folder', 1), '', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #21 (array('folder', 10), '', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #22 (array('folder', 1), '', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #23 (array('folder', 10), '', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #24 (array('folder'), 'no', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #25 (array('folder'), 'yes', 'yes', true, true, array(0, 1, 6, 4), true, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #26 (array('folder'), 'no', 'yes', true, true, array(0, 1, 6, 4), false, true, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearch with data set #27 (array('folder'), 'no', 'no', true, true, array(0, 1, 6, 4), false, false, true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchInvalid with data set #0 (array(0), 'Invalid page')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchInvalid with data set #1 (array('0'), 'Invalid page')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchInvalid with data set #2 (array(-1), 'Invalid page')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchInvalid with data set #3 (array(0), 'Invalid perPage argument')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchInvalid with data set #4 (array('0'), 'Invalid perPage argument')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchInvalid with data set #5 (array(-1), 'Invalid perPage argument')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testIsRemoteSharingAllowed with data set #0 ('file', true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testIsRemoteSharingAllowed with data set #1 ('folder', true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testIsRemoteSharingAllowed with data set #2 ('', false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testIsRemoteSharingAllowed with data set #3 ('contacts', false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchSharees with data set #0 ('test', 'folder', array(0, 1, 6), 1, 2, false, array(), array(), array(array(), array(), false), array(array(array(), array(), array(), array()), array(), array(), array(), array(), array()), false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchSharees with data set #1 ('test', 'folder', array(0, 1, 6), 1, 2, false, array(), array(), array(array(), array(), false), array(array(array(), array(), array(), array()), array(), array(), array(), array(), array()), false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchSharees with data set #2 ('test', 'folder', array(0, 1, 6), 1, 2, false, array(array('test One', array(0, 'test1'))), array(array('testgroup1', array(1, 'testgroup1'))), array(array(array('testz@remote', array(6, 'testz@remote'))), array(), false), array(array(array(), array(), array(), array()), array(array('test One', array(0, 'test1'))), array(array('testgroup1', array(1, 'testgroup1'))), array(array('testz@remote', array(6, 'testz@remote'))), array(), array()), true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchSharees with data set #3 ('test', 'folder', array(0, 6), 1, 2, false, array(array('test One', array(0, 'test1'))), null, array(array(array('testz@remote', array(6, 'testz@remote'))), array(), false), array(array(array(), array(), array(), array()), array(array('test One', array(0, 'test1'))), array(), array(array('testz@remote', array(6, 'testz@remote'))), array(), array()), false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchSharees with data set #4 ('test', 'folder', array(0), 1, 2, false, array(array('test One', array(0, 'test1'))), null, null, array(array(array(), array(), array(), array()), array(array('test One', array(0, 'test1'))), array(), array(), array(), array()), false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchSharees with data set #5 ('test', 'folder', array(0), 1, 2, false, array(array('test 1', array(0, 'test1')), array('test 2', array(0, 'test2'))), null, null, array(array(array(), array(), array(), array()), array(array('test 1', array(0, 'test1')), array('test 2', array(0, 'test2'))), array(), array(), array(), array()), true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSearchShareesNoItemType'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testGetPaginationLink with data set #0 (1, '/ocs/v1.php', array(2), '<?perPage=2&page=2>; rel="next"')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testGetPaginationLink with data set #1 (10, '/ocs/v2.php', array(2), '<?perPage=2&page=11>; rel="next"')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testIsV2 with data set #0 ('/ocs/v1.php', false)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testIsV2 with data set #1 ('/ocs/v2.php', true)'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #0 ('user@name@localhost', 'user@name', 'localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #1 ('user@name@localhost/', 'user@name', 'localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #2 ('user@name@localhost/index.php', 'user@name', 'localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #3 ('user@name@localhost/index.php/s/token', 'user@name', 'localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #4 ('user@name@http://localhost', 'user@name', 'http://localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #5 ('user@name@http://localhost/', 'user@name', 'http://localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #6 ('user@name@http://localhost/index.php', 'user@name', 'http://localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #7 ('user@name@http://localhost/in.../token', 'user@name', 'http://localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #8 ('user@name@https://localhost', 'user@name', 'https://localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #9 ('user@name@https://localhost/', 'user@name', 'https://localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #10 ('user@name@https://localhost/index.php', 'user@name', 'https://localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #11 ('user@name@https://localhost/i.../token', 'user@name', 'https://localhost')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #12 ('user@name@local.host', 'user@name', 'local.host')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #13 ('user@name@local.host/', 'user@name', 'local.host')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #14 ('user@name@local.host/index.php', 'user@name', 'local.host')'.
Starting test 'OCA\Files_Sharing\Tests\Controller\ShareesAPIControllerTest::testSplitUserRemote with data set #15 ('user@name@local.host/index.php/s/token', 'user@name', 'local.host')'.
. 3721 / 4330 ( 85%)
```

@rullzer @schiessle One of them is causing the actual issue. (just running an endless loop somehow, because there is no progress for over 20 minutes even if it runs only for some seconds usually. Any idea, which of them could cause trouble? Once I enable debug and verbose mode this is not reproducible anymore. Let me try to only test this controller.

**Comment by MorrisJobke** [comment]
All run fine 😞

**Comment by rullzer** [comment]
No clue. But summoning our ShareeAPI guru @nickvergessen

**Comment by nickvergessen** [comment]
Should we just add https://phpunit.de/manual/current/en/risky-tests.html#risky-tests.test-execution-timeout ?
Set the small timeout to 1 minute, just to be on the save side, but then it just kills tests when they take longer then 1 minute and makes them fail?
Then we can see if it even is this test, or if phpunit itself just dies somehow

**Comment by MorrisJobke** [comment]
@nickvergessen sounds like a plan - can you add this?

**Pull request closed without merging**
