### PR TITLE
fix overlapping buttons in apps-management

### LINKED ISSUE #31069: [Bug]: App navigation toggle overlaps content
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The app-navigation-toggle overlaps content on multiple pages.

On the Apps page:
image

On contacts:
image

### Steps to reproduce

1. Open the contacts/apps page in a PC browser.
2. Check if the navigation toggle button overlaps the main content.

### Expected behavior

The content is not overlapped by the menu functionality.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REDACTED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "23.0.1.2",
        "overwrite.cli.url": "REDACTED",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 3,
        "app_install_overwrite": [
            "calendar",
            "checksum",
            "bruteforcesettings",
            "imageconverter"
        ],
        "theme": "",
        "default_phone_region": "UK",
        "knowledgebaseenabled": true,
        "updatechecker": true,
        "cache_path": "\/tmp",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ]
    }
}
```

### List of activated Apps

```shell
-
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

OS: Arch Linux
Browser: Firefox 96.0.3 (64-bit)

### PR DESCRIPTION
**Pull request by szaimen**
Fix #31069 

### After: 
image

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=fix/31069/fix-overlapping-buttons-apps-management \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Comment by GretaD** [comment]
Looks ok, but i would propose to be aligned with the text. Also, this is a problem we have will all apps, should we change it only here? AFAIK we dont have a final solution yet.

**Comment by szaimen** [comment]
> Looks ok, but i would propose to be aligned with the text.

What shall be aligned?

**Comment by GretaD** [comment]
> > Looks ok, but i would propose to be aligned with the text.
> 
> What shall be aligned?

sorry :) i meant the text that you added to be aligned with the toggle menu

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
> sorry :) i meant the text that you added to be aligned with the toggle menu

done and updated the screenshot :)

**Review by GretaD — APPROVED** [review]
code looks good, didnt test it

**Pull request merged**
