### PR TITLE
Allow to send the password of protected conversations

### PR DESCRIPTION
**Pull request by nickvergessen**
Rel nextcloud/spreed#1768

### CODE REVIEW

**Comment by nickvergessen** [comment]
Regression from https://github.com/nextcloud/server/pull/14626

Before all http methods were redirected to the controller. Now it was only get, but we also need post.

**Review by danxuliu — DISMISSED** [review]
Maybe I did something wrong, but it does not work for me. Now not only the authentication ends in a blank page, but loading any _/call/_ URL ends in a blank page.

I guess that [the router only admits one route with the same name](https://github.com/nextcloud/server/blob/4e8b033281a1ecb4bd1fd8651cd91630022e9d38/lib/private/AppFramework/Routing/RouteConfig.php#L177), so the second route for POST overwrites the first route for GET.

**Review by Ivansss — APPROVED** [review]
Tested and works 👍

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Pull request merged**
