### PR TITLE
Fix filepicker styling

### LINKED ISSUE #2252: Filepicker dialog has strange shadow
screen shot 2016-11-22 at 18 38 56

cc @icewind1991 @jancborchardt

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #2252

Also now limits the filepicker size to fit in small screens.

cc @jancborchardt @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Really nice. There is only one issue:

* [ ] cause a file conflict dialog and then resize the window: the modal is always increasing size and can't be closed anymore, because the elements are out of the view

**Comment by MorrisJobke** [comment]
Potentially also fixes #1864

**Comment by icewind1991** [comment]
> cause a file conflict dialog and then resize the window: the modal is always increasing size and can't be closed anymore, because the elements are out of the view

Fixed

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
> Tested and works 👍

Chrome, Safari, IE11 and Edge ;)

**Review by LukasReschke — APPROVED** [review]

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
