### PR TITLE
fix header-elements being not shown correctly

### LINKED ISSUE #42620: Some themes not correclty inverting the header icons anymore
See e.g. 
image
and
image

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/42620

### Before

https://github.com/nextcloud/server/assets/42591237/6950030f-606a-4255-bb20-f6a7ecbef358

### After

https://github.com/nextcloud/server/assets/42591237/c9edada2-6ddc-4bc3-a59f-ad89d4ce0e56

<details>
<summary>For my own testing</summary>

```
docker run -it --rm ^
--name nextcloud-easy-test ^
-p 8443:443 ^
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" ^
-e SERVER_BRANCH=enh/42620/header-menues ^
-e COMPILE_SERVER=1 ^
ghcr.io/szaimen/nextcloud-easy-test:latest

```

</details>

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
/backport 6acc2b3f4b9b988fe481e986a523f911b6114e86 to stable28

**Review by JuliaKirschenheuter — APPROVED** [review]

**Comment by szaimen** [comment]
Needs a rebase...

**Comment by szaimen** [comment]
/backport a96a7f0c82c1ca22e78c42120e104ed46b9b08aa to stable28

**Review by emoral435 — APPROVED** [review]

**Comment by ShGKme** [comment]
While filter inverts the icon, it also breaks the whole header menu.

Without filter | With filter
---|---
image | image

**Comment by szaimen** [comment]
Lets track it in https://github.com/nextcloud/server/issues/42962

**Pull request merged**
