### PR TITLE
Fix bad revert commit

### PR DESCRIPTION
**Pull request by artonge**

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
I think it’s good, I get this diff with the last known good state from my side:
```diff
--- a/apps/files_versions/lib/Command/CleanUp.php
+++ b/apps/files_versions/lib/Command/CleanUp.php
@@ -24,7 +24,6 @@
  */
 namespace OCA\Files_Versions\Command;
 
-use OCA\Files_Versions\Db\VersionsMapper;
 use OCP\Files\IRootFolder;
 use OCP\IUserBackend;
 use OCP\IUserManager;
@@ -38,7 +37,6 @@ class CleanUp extends Command {
        public function __construct(
                protected IRootFolder $rootFolder,
                protected IUserManager $userManager,
-               protected VersionsMapper $versionMapper,
        ) {
                parent::__construct();
        }
@@ -122,7 +120,6 @@ class CleanUp extends Command {
                \OC_Util::setupFS($user);
 
                $fullPath = '/' . $user . '/files_versions' . ($path ? '/' . $path : '');
-               $this->versionMapper->deleteAllVersionsForUser($user);
                if ($this->rootFolder->nodeExists($fullPath)) {
                        $this->rootFolder->get($fullPath)->delete();
                }
diff --git a/apps/files_versions/lib/Db/VersionsMapper.php b/apps/files_versions/lib/Db/VersionsMapper.php
index 9b5d7a52c13..bc6e8b264de 100644
--- a/apps/files_versions/lib/Db/VersionsMapper.php
+++ b/apps/files_versions/lib/Db/VersionsMapper.php
@@ -27,7 +27,6 @@ declare(strict_types=1);
 namespace OCA\Files_Versions\Db;
 
 use OCP\AppFramework\Db\QBMapper;
-use OCP\DB\QueryBuilder\IQueryBuilder;
 use OCP\IDBConnection;
 
 /**
@@ -84,20 +83,4 @@ class VersionsMapper extends QBMapper {
                         ->where($qb->expr()->eq('file_id', $qb->createNamedParameter($fileId)))
                         ->executeStatement();
        }
-
-       public function deleteAllVersionsForUser(string $userId): int {
-               $deleteQuery = $this->db->getQueryBuilder();
-               $filesVersionSelect = $this->db->getQueryBuilder();
-               $filesVersionSelect->select('fileid')
-                       ->from('filecache', 'f')
-                       ->join('f', 'mounts', 'm', $filesVersionSelect->expr()->eq('f.storage', 'm.storage_id'))
-                       ->where($filesVersionSelect->expr()->like('f.path', $deleteQuery->createNamedParameter('files/%', IQueryBuilder::PARAM_STR)))
-                       ->andWhere($filesVersionSelect->expr()->eq('m.user_id', $deleteQuery->createNamedParameter($userId, IQueryBuilder::PARAM_STR)))
-                       ->andWhere($filesVersionSelect->expr()->eq('m.mount_point', $deleteQuery->createNamedParameter("/$userId/", IQueryBuilder::PARAM_STR)));
-
-               $deleteQuery->delete($this->getTableName())
-                       ->where($deleteQuery->expr()->in('file_id', $deleteQuery->createFunction($filesVersionSelect->getSQL()), IQueryBuilder::PARAM_INT_ARRAY));
-
-               return $deleteQuery->executeStatement();
-       }
 }
```

**Comment by artonge** [comment]
> I think it’s good, I get this diff with the last known good state from my side:

That's good I think, this is probably the commit I had locally and that vscode merged with master.

**Comment by come-nc** [comment]
```

There were 4 errors:

1) OCA\Files_Versions\Tests\Command\CleanupTest::testDeleteVersions with data set #0 (true)
ArgumentCountError: Too few arguments to function OCA\Files_Versions\Command\CleanUp::__construct(), 2 passed in /home/runner/work/server/server/apps/files_versions/tests/Command/CleanupTest.php on line 60 and exactly 3 expected

/home/runner/work/server/server/apps/files_versions/lib/Command/CleanUp.php:38
/home/runner/work/server/server/apps/files_versions/tests/Command/CleanupTest.php:60

2) OCA\Files_Versions\Tests\Command\CleanupTest::testDeleteVersions with data set #1 (false)
ArgumentCountError: Too few arguments to function OCA\Files_Versions\Command\CleanUp::__construct(), 2 passed in /home/runner/work/server/server/apps/files_versions/tests/Command/CleanupTest.php on line 60 and exactly 3 expected

/home/runner/work/server/server/apps/files_versions/lib/Command/CleanUp.php:38
/home/runner/work/server/server/apps/files_versions/tests/Command/CleanupTest.php:60

3) OCA\Files_Versions\Tests\Command\CleanupTest::testExecuteDeleteListOfUsers
ArgumentCountError: Too few arguments to function OCA\Files_Versions\Command\CleanUp::__construct(), 2 passed in /home/runner/work/server/server/apps/files_versions/tests/Command/CleanupTest.php on line 60 and exactly 3 expected

/home/runner/work/server/server/apps/files_versions/lib/Command/CleanUp.php:38
/home/runner/work/server/server/apps/files_versions/tests/Command/CleanupTest.php:60

4) OCA\Files_Versions\Tests\Command\CleanupTest::testExecuteAllUsers
ArgumentCountError: Too few arguments to function OCA\Files_Versions\Command\CleanUp::__construct(), 2 passed in /home/runner/work/server/server/apps/files_versions/tests/Command/CleanupTest.php on line 60 and exactly 3 expected

/home/runner/work/server/server/apps/files_versions/lib/Command/CleanUp.php:38
/home/runner/work/server/server/apps/files_versions/tests/Command/CleanupTest.php:60
```

**Comment by come-nc** [comment]
The tests expect the 3rd constructor param to be there

**Comment by come-nc** [comment]
diff is empty now :partying_face:

**Review by nickvergessen — APPROVED** [review]
Looks good from what I can tell atm, so I'm merging this before translation sync break the PR tonight or a dist/ PR breaks it.

**Pull request merged**
