### PR TITLE
add id to editor of direct editing

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
@juliushaertl 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
lots of integration failure?

**Comment by rullzer** [comment]
mmm "General error: 1 RIGHT and FULL OUTER JOINs are not currently supported" like wut....

**Comment by juliushaertl** [comment]
also on master https://drone.nextcloud.com/nextcloud/server/23984/29/3

**Comment by juliushaertl** [comment]
Seems like https://github.com/nextcloud/server/pull/17920 caused this

**Pull request merged**
