### PR TITLE
fix: only use jquery once it is available

### PR DESCRIPTION
**Pull request by azul**
publicpage.js is loaded very early and cannot rely on jquery being loaded already.

Move the use of `$` into the `DomContentLoaded` handler.

### CODE REVIEW

**Comment by azul** [comment]
Noticed this because [cypress tests](https://github.com/nextcloud/text/runs/4758963925?check_suite_focus=true) in text started failing complaining:
```
  > $ is not defined
https://on.cypress.io/uncaught-exception-from-application
      at http://localhost:8081/core/js/public/publicpage.js?v=16d6118e-0:36:1
```

This seems to be the easiest fix for now. Could also rewrite this without relying on jquery - but i guess that's for another time.

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by acsfer** [comment]
Backport?

**Pull request merged**
