### PR TITLE
Check free space of target folder after drag and drop

### LINKED ISSUE #5437: Dragging a file on a shared folder checks your quota while dragging a file inside an *opened* shared folder checks quota of folder owner
#I am running nextcloud 12.0.0 and set up my users to have a very small quota (1MiB) to force them to write in a shared folder, created by the administrator. However, in the web interface, if the user drags a file on the icon of the shared folder, a "Not enough storage" error is displayed. If she opens the shared folder first and drags the file inside subsequently, the upload starts. My theory is that the quota of the uploading user is checked in the first case, even though the quota of the shared folder owner should be checked in both cases.

### Steps to reproduce
1. Create two users: "joe", with small quota (1MiB) and "admin", with unlimited quota
2. "admin", shares a folder to "joe".
3. "joe" uses the web interface to log in. In the home screen, he drags a large file (>1M) on the folder shared to him by "admin". A message "Not enough free storage" is displayed.
4. "joe" now opens the shared folder and drags the file into the web interface now. File upload works

### Expected behaviour
The file should be uploaded, because the shared folder belongs to "admin" and not to the quota of "joe", regardless of whether "joe" drags the file onto the folder symbol or opens the folder and drags the file inside afterwards.

### Actual behaviour
A "Not enough storage" error is displayed to "joe", and he can't upload the file, if he drags the file onto the folder symbol. 

### Server configuration

**Operating system**: Arch Linux

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.24

**PHP version:** 7.1.6

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** From Nextcloud homepage

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
 
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
    
```
{
"system": {
        "instanceid": "oc21fut1jvx3",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/srv\/http\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 53.0.3 (64-bit)

**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

-- No error logged --

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

-- no error logged --

</details>

#### Browser log
<details>
<summary>Browser log</summary>

-- no log entries added --

</details>

### PR DESCRIPTION
**Pull request by ChristophWurst**
This is a revival of https://github.com/nextcloud/server/pull/6508

* [ ] I don't know where this `add` function is called, so I can't change that to be able to work with async operations
* [ ] The error handling is most likely not sufficient
* [ ] Not sure if the propfind is always necessary or correct. It works for external storage, tho.

@nextcloud/javascript I know this is some of our ugliest code but any help is HIGHLY appreciate :pray: 

Fixes https://github.com/nextcloud/server/issues/5437

### CODE REVIEW

**Comment by kesselb** [comment]
Looks like fun 😆

**Comment by ChristophWurst** [comment]
> Looks like fun laughing

Thanks for the supportive comment :wink:

**Comment by juliushaertl** [comment]
I just had a quick look, but I'll check it more in detail next week.

> I don't know where this add function is called, so I can't change that to be able to work with async operations

It is called by the jquery.fileupload plugin, I'd probably stay away from patching around in that :see_no_evil: 

> Not sure if the propfind is always necessary or correct. It works for external storage, tho.

We could probably just extend the existing profind with the d:quota-available-bytes property so we have the infomation around already in the filelist, but that might have a performance impact, not sure about that right now.

**Comment by juliushaertl** [comment]
I've pushed my idea of the implementation to https://github.com/nextcloud/server/pull/24102

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/24102 works very nicely and is less hacky.

**Pull request closed without merging**
