### PR TITLE
Stopped scrollbar being hidden by rounded corners

### PR DESCRIPTION
**Pull request by pepper-lees**
NOTE: I didn't include the compiled apps.css, server.css, etc. because I'm not sure what the procedure for those autogenerated files are. I figured it's easier for a maintainer to merge the PR then re-generate the files, rather than deal with a potential merge conflict

## Summary

I find the fact that Material Design 3 allows for scrollbars to be hidden behind rounded corners incredibly offensive from a design standpoint. I checked the design guidelines and I couldn't find any explicit rules stating that they **should** be this way. I believe that it is much more aesthetically pleasing to stop the scrollbar before it starts being rounded. This code only modifies the scrollbar in the main app content, since that's the only container I could find that had a scrollbar hidden behind a rounded corner.

Before:

mstsc_2023-04-27_22-29-01

After:
mstsc_2023-04-27_22-25-44

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [N/A] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by provokateurin** [comment]
@JL102 you need to add the changes to the autogenerated files to this PR. The CI won't go green unless you do it.

**Comment by JL102** [comment]
> @JL102 you need to add the changes to the autogenerated files to this PR. The CI won't go green unless you do it.

Understood. Fixing

**Review by Jerome-Herbinet — COMMENTED** [review]
Nice idea ! ... but sadly, this CSS property seams to be not supported by FF. 
Please check : https://developer.mozilla.org/fr/docs/Web/CSS/::-webkit-scrollbar 
I let other reviewers verify this information.
If confirmed, it might be necessary to imagine a workaround or a different way to get the same result.

**Comment by JL102** [comment]
> Nice idea ! ... but sadly, this CSS property seams to be not supported by FF. Please check : https://developer.mozilla.org/fr/docs/Web/CSS/::-webkit-scrollbar I let other reviewers verify this information. If confirmed, it might be necessary to imagine a workaround or a different way to get the same result.

Firefox has been doing scrollbars differently from Webkit/Blink-based browsers for a long time. I don't believe it's possible to do the same trick in Firefox, because the only three W3c-standard scrollbar related attributes I can see are scrollbar-color, scrollbar-gutter, and scrollbar-width; none of which can control the buttons.

**Review by artonge — APPROVED** [review]

**Review by Jerome-Herbinet — APPROVED** [review]

**Pull request merged**
