### PR TITLE
chore(deps): Bump @nextcloud/dialogs to v5.3.1

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Bring in fixes from https://github.com/nextcloud-libraries/nextcloud-dialogs/releases/tag/v5.3.1

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]

**Comment by susnux** [comment]
conflicts

**Comment by Pytal** [comment]
/backport 40cd042896c2f747269e3e667441a1a23b171bb6 to stable29

**Comment by Pytal** [comment]
/backport 40cd042896c2f747269e3e667441a1a23b171bb6 to stable28

**Pull request merged**
