### PR TITLE
NavigationDuplicated: catch uncaught (in promise)

### PR DESCRIPTION
**Pull request by kesselb**
How to reproduce:

1) Use master or stable17
2) Go to App Store
3) Open development tools
4) Click on the same app 2x

Peek 2019-10-06 21-01

Looks like $router.push returns a promise. If the route is identical a NavigationDuplicated exception is thrown. Consume the promise and catch the exception.

### CODE REVIEW

**Comment by kesselb** [comment]
Pushed only the change to `appItem.vue`. `make build-js-production` modifies to many unrelated files :see_no_evil:

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
@kesselb fixed it for you :)

**Review by GretaD — APPROVED** [review]
:+1:

**Review by skjnldsv — APPROVED** [review]
code make sense :+1:

**Pull request merged**
