### PR TITLE
Ldap password renewal fixes for NC12

### PR DESCRIPTION
**Pull request by GitHubUser4234**
Here are small code changes for four issues related to LDAP password renewal that were found in the official NC12 release:

- Missing function parameter causes the password renewal page to fail. While this is a bug and certainly has to be fixed, it is quite a mystery why it worked on NC11. Maybe due to some dependency injection magic?

 - Wrong removal of `needsPasswordReset `flag from session.

- A superfluous PHP error occurs when a password change is rejected due to password policy. As this is not an error that should be shown in the server logs (let alone as log level 3), this is now suppressed.

- Since css files have been moved around in NC12 and among others a new guest.css has been introduced, the submit button for password renewal doesn't look the same as the login button anymore. Assuming that adding the password renewal path to https://github.com/nextcloud/server/blob/master/lib/private/TemplateLayout.php#L169 wouldn't be appropriate, the simplest solution was to just copy over the correct css code from guest.css to renewPassword.css.

### CODE REVIEW

**Review by blizzz — APPROVED** [review]
code looks good and makes sense

**Comment by blizzz** [comment]
@nextcloud/ldap pls review

**Review by MorrisJobke — APPROVED** [review]

**Comment by blizzz** [comment]
@GitHubUser4234 can you create the backport for stable12?

**Comment by GitHubUser4234** [comment]
Thanks at all :)

> @GitHubUser4234 can you create the backport for stable12?

Sure, it's here: #5665

**Pull request merged**
