### PR TITLE
add new button component

### PR DESCRIPTION
**Pull request by vanpertsch**
**Before**
Screenshot 2022-03-02 at 15 23 24

**After**
Screenshot 2022-03-02 at 15 22 05

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]
<3

**Comment by jancborchardt** [comment]
Looks good generally, but – @marcoambrosini it does look a bit weird that a clear/delete button is primary-colored, right?
And the full-on red "Error" button would be a bit much, so here and for other cases (e.g. decline attendance for an event), a less aggressive "Delete" button would be good:
image
This uses `var(--color-error)` as text color, and 10% of that color for background, just like we do for the secondary buttton.

**Comment by marcoambrosini** [comment]
@jancborchardt don't you think we can just use tertiary there? 
Tbh I think we have plenty of button states for now and for the sake of standardisation I'd prefer to tweak them instead of adding more states. If you think that the "error" state is too punchy we can make it into the one you've posted, but I would advise against having a "light error" alongside a "punchy error"

**Comment by vanpertsch** [comment]
@jancborchardt can we use tertiary here?

Screenshot 2022-03-10 at 16 10 43

**Comment by jancborchardt** [comment]
@vanpertsch @marcoambrosini tertiary looks good! :)

@marcoambrosini and yes, I'd say error should be less punchy, at least when we use it for remove, delete and "decline event". Not sure about " Leave call", maybe that needs to stay more obvious as it's the only main action in the case.

**Review by marcoambrosini — APPROVED** [review]

**Pull request merged**
