### PR TITLE
Restore dav error response

### PR DESCRIPTION
**Pull request by kesselb**
## Summary

Revert https://github.com/nextcloud/server/commit/9992e7d4395a773fec7148cf5b4111f894cb40b7
Revert https://github.com/nextcloud/server/commit/d2bf3613f6c9210a720bebdcf82284bbfc604319
Revert https://github.com/nextcloud/server/commit/e202896a7476f6c3ad74793e6524293fd8a93224

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by kesselb** [comment]
**Test case 1: Report with unsupported limit**

```
curl -X REPORT "https://server30.internal/remote.php/dav/calendars/admin30/personal/" \
    -H "Content-Type: application/xml" \
    -H "Cookie: XDEBUG_SESSION=PHPSTORM" \
    -d '<sync-collection xmlns="DAV:">
<sync-token />
    <sync-level>1</sync-level>
    <limit>
    <nresults>100</nresults>
    </limit>
    <prop>
    <getetag />
    </prop>
</sync-collection>' \
    --basic --user admin30:admin30
```

Expected outcome:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Exception\UnsupportedLimitOnInitialSyncException</s:exception>
  <s:message/>
  <d:number-of-matches-within-limits/>
</d:error>
```

**Comment by kesselb** [comment]
**Test case 2: Mask type errors**

1. Patch photos app
2. Create album "Test"
3. Send http request

```
Index: lib/Sabre/PropFindPlugin.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/Sabre/PropFindPlugin.php b/lib/Sabre/PropFindPlugin.php
--- a/lib/Sabre/PropFindPlugin.php	(revision c30f81f85f372981fc603ee9a0c998524c6f5a0d)
+++ b/lib/Sabre/PropFindPlugin.php	(date 1732785829587)
@@ -131,9 +131,9 @@
 		$node = $this->tree->getNodeForPath($path);
 		if ($node instanceof AlbumRoot) {
 			$propPatch->handle(self::LOCATION_PROPERTYNAME, function ($location) use ($node) {
-				if ($location instanceof Complex) {
-					$location = $location->getXml();
-				}
+//				if ($location instanceof Complex) {
+//					$location = $location->getXml();
+//				}
 
 				$this->albumMapper->setLocation($node->getAlbum()->getAlbum()->getId(), $location);
 				return true;
```


```
curl -X PROPPATCH "https://server30.internal/remote.php/dav/photos/admin30/albums/Test" \
    -H "OCS-APIRequest: true" \
    -H "Content-Type: application/xml" \
    -H "Cookie: XDEBUG_SESSION=PHPSTORM" \
    -d '<?xml version="1.0"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns"
				  xmlns:nc="http://nextcloud.org/ns"
				  xmlns:ocs="http://open-collaboration-services.org/ns">
	<d:set>
		<d:prop>
			<nc:location>
				<a></a>
			</nc:location>
		</d:prop>
	</d:set>
</d:propertyupdate>' \
    --basic --user admin30:admin30
```



Expected outcome with debug = false:

Internal server error without stack trace.

**Comment by sorbaugh** [comment]
This should have been aligned with with @artonge, since a security that was originally addressed by the reverted PRs are back and he is the author of all of them. At the VERY least he should have been contacted and requested as a reviewer 🤷‍♂️

**Pull request merged**
