### PR TITLE
[stable10] add fullscreen icon

### PR DESCRIPTION
**Pull request by jancborchardt**
Backport of https://github.com/nextcloud/server/pull/1803

Please review @LukasReschke @skjnldsv @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by skjnldsv** [comment]
LGTM 👍

**Comment by nickvergessen** [comment]
So you really want to break your app so it does require a minor update before being usable?

**Comment by jancborchardt** [comment]
No, but it will take some time for it to be released anyway. We backported the audio and video icons already so it would be a bit stupid to not do it with the fullscreen icon either.

**Pull request merged**
