### PR TITLE
Return back theme config after web upgrade

### LINKED ISSUE #2785: after upgrade theme setting is gone
After upgrading from 10.0.1 to 10.0.2 theme setting in `config.php` has been set to `  'theme' => '',`

(reopened from [here](https://github.com/nextcloud/updater/issues/71))

### PR DESCRIPTION
**Pull request by zorn-v**
It is very annoying to go on server and edit `config.php` after web upgrade. 
Is not web upgrade should prevent "go on server" ?

Close https://github.com/nextcloud/server/issues/2785

### CODE REVIEW

**Comment by kesselb** [comment]
Hmm. This pr does not restore the theme after upgrade. It restores the theme after printing the update page but before the actual update.

**Comment by kesselb** [comment]
I think the following could work:

1) `$systemConfig->setValue('old_theme', $oldTheme);`  store the current theme as oldTheme 
2) https://github.com/nextcloud/server/blob/637d89727c4c8b2ba6ca9486f876617c8b51722a/lib/private/Updater.php#L148-L149 Do something like this for the theme. Is there a "old_theme" key in config.php and set it as theme again and delete old_theme.

Thanks for your contribution :+1:

**Comment by zorn-v** [comment]
> Hmm. This pr does not restore the theme after upgrade. It restores the theme after printing the update page but before the actual update.

Yes, but default theme sets before printing update page and nowhere else. 
I think this was done to show actual updated page of upgrader

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Pull request closed without merging**
