### PR TITLE
Fail the translation test when there are multiple single placeholders

### PR DESCRIPTION
**Pull request by nickvergessen**
Temp solution to detect failing strings

### CODE REVIEW

**Comment by MorrisJobke** [comment]
this is more and administrative thing right? We should update all those strings. Isn't it better to wait for 15 or do we want to overhaul all the strings now? I guess this is for RTL languages, correct?

**Comment by MorrisJobke** [comment]
> Yeah, one more "broken" version, but well better then all in english for everyone

We could also do it now ... still one months to go.

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by MorrisJobke** [comment]
Rebased. Let's try to get this in.

**Comment by MorrisJobke** [comment]
I noticed following:

* this is checking the translation files - thus a failure will only be noticed once the code is in master, was synced to transifex, was translated there and then got synced back - that's too late. We maybe should use the `translationtool.phar` to extract the current strings and check this.
* `"_%s group found_::_%s groups found_"` is a false positive, because it is a plural string and not a string with two placeholders

**Comment by MorrisJobke** [comment]
Beside that all mentioned strings are already fixed.

**Comment by nickvergessen** [comment]
> "_%s group found_::_%s groups found_" is a false positive, because it is a plural string and not a string with two placeholders

is a error in itself, if it is a plural it should use `%n`

**Comment by nickvergessen** [comment]
> this is checking the translation files - thus a failure will only be noticed once the code is in master, was synced to transifex, was translated there and then got synced back - that's too late. We maybe should use the translationtool.phar to extract the current strings and check this.

Yeah, although it is still visible after the first pull from transifex because of `en`.
I just didn't find a better way.

**Comment by MorrisJobke** [comment]
> Yeah, although it is still visible after the first pull from transifex because of `en`.
> I just didn't find a better way.

I would let https://github.com/nextcloud/docker-ci/tree/master/translations/translationtool run in here and then check the generated `.pot` files for those strings. Then we can tackle it right away.

**Comment by ChristophWurst** [comment]
> I would let https://github.com/nextcloud/docker-ci/tree/master/translations/translationtool run in here and then check the generated `.pot` files for those strings. Then we can tackle it right away.

What were the results? :D

**Comment by MorrisJobke** [comment]
> What were the results? :D

It was never implemented 🙈

**Comment by rullzer** [comment]
Let me close this.
If somebody wants to pick this up feel free to reopen.

**Pull request closed without merging**
