### PR TITLE
Adjust badges

### PR DESCRIPTION
**Pull request by LukasReschke**
- Removes the Drone badge
  - This one is lying most of the time since it isn't checking master but the latest build. Thus it fails when it effectively doesn't fail. Let's remove that since it makes us look bad.
- Add CodeCov badge
- Add CII badge

cc @rullzer @MorrisJobke @jospoortvliet 

---

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by nickvergessen** [comment]
😢  👍

**Comment by MorrisJobke** [comment]
> This one is lying most of the time since it isn't checking master but the latest build. Thus it fails when it effectively doesn't fail. Let's remove that since it makes us look bad.

Wrong - we build master and it showed the correct one - but mostly it was in the "Running" state because the next merge came in ;)

**Comment by ypid** [comment]
Awesome work! [CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/209) Nice :wink:

**Pull request merged**
