### PR TITLE
Fix: duplicating contacts with the Recently contacted feature

### LINKED ISSUE #31606: [Bug]: "Recently contacted" feature creates duplicates in Contacts
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The "Recently contacted" feature adds duplicates there even if a user with that email address is already in contacts. This could possibly be if an instance uses a shared address book and yourself is not owner of that address book?

The "Recently contacted" mechanism needs to check if an address already exists in Contacts, in which case they should not create another entry, also in other address books you have (at least those which are enabled).

@ChristophWurst as mentioned

### Steps to reproduce

1. Send a mail to an email of a person you already have in contacts
2. Check in contacts, they will be twice in the "All contacts" list

### Expected behavior

No duplicates should be created. :)

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
This is on our `cloud.nc.com` instance
```

### List of activated Apps

```shell
This is on our `cloud.nc.com` instance
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
* Resolves: #31606

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Makes sense

**Review by JohannesGGE — APPROVED** [review]
Tested and works :+1:

**Review by miaulalala — APPROVED** [review]
Drone seems to be having a wobble :grimacing:

**Comment by jdaviescoates** [comment]
I'm hoping this will also fix a related issue I'm observing, but I'm wondering if I should create a new issue:

1. If someone who is in already in my contacts books me using my Cal.com page at https://cal.com/jdaviescoates/quick-chat?duration=30 
2. But they typo their email address whilst doing so
3. And I then I attempt to add them to the event in Nextcloud Calendar as an attendee using their correct email
4. Nextcloud emails their recently contacted incorrect email instead of their correct email!

**Pull request merged**
