### PR TITLE
15.0.0 beta 1

### PR DESCRIPTION
**Pull request by MorrisJobke**
Critical changed for devs & admins: #11045

Pending issues:

* [ ] #12294 blurry buttons

Pending enhancements:

* [x] #11968 Replace $verbose with VERBOSITY_VERBOSE for scanFiles method
* [x] [activity#300](https://github.com/nextcloud/activity/pull/300) Add the mimetype to the preview arrays
* [x] #10059 Cache webcal calendars on server

Pending technical debt PRs: 

* [ ] #10921 Cleanup filecache database handling a bit
* [ ] #11942 Use the defined func()->count() instead of manual counting

Pending bug fix PRs:

* [x] #11836 Comment mentions with spaces
* [x] #12273 Fix password enforce on public share links
* [x] #12284 Properly search the root of a shared external storage
* [x] #12303 Add grid toggle for every files view
* [x] #12306 Disabled ldap fix
* [x] #12312 Fix index names
* [x] #12324 Add "password" parameter to the response data of link shares
* [x] #12332 Also use default label if share label is null
* [x] #12334 Only show label if the shareWith value is relevant
* [x] #12317 Add es6-shim as polyfill and minify core vendor scripts (replaced #12083)
* [x] #12313 Clear avatar cache with frontend repair
* [x] #12316 Better primary visual on public pages
* [ ] #10555 Only enforce schema limits for supported apps
* [ ] #10825 Copy a file to the same directory
* [ ] #10842 LIMIT is no column but a SQL keyword, allow limit on initial sync
* [ ] #11200 Fix interaction with groups that contain a slash
* [ ] #11949 Selecting files inside search results produces wrong download link
* [ ] #12087 Indicate default quota
* [ ] #12173 Ensure filename is possibly centered below file icons in grid view
* [ ] #12275 Fix Calendarsubscriptions source column change on Oracle
* [ ] #12292 Avoid logging of "Partial search results returned: Sizelimit exceeded…"
* [ ] #12315 Bug 6160: Deadlock removed
* [ ] #12335 Do not offer to change display name or password, if not possible.

cc @danxuliu @rullzer @blizzz @icewind1991 @schiessle @nickvergessen @jancborchardt @skjnldsv @danielkesselberg @weeman1337 @karlitschek @jospoortvliet @tobiasKaminsky @camilasan @mario @ChristophWurst

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
For mobile we would need
https://github.com/nextcloud/server/issues/8477
https://github.com/nextcloud/server/issues/11138

We discussed this at our NC15 meeting, but even though I did some reminders, nothing was done. So I doubt that this will get :disappointed:

**Comment by MorrisJobke** [comment]
> For mobile we would need
> #8477
> #11138
> 
> We discussed this at our NC15 meeting, but even though I did some reminders, nothing was done. So I doubt that this will get 😞

Yes - does not good to be solved within 8 hours :/

**Comment by georgehrke** [comment]
Removed:
* [ ] #10068 Add Apple Provisioning profile
* [ ] #11832 Set birthday year to 1970 if no year, take X-APPLE-OMIT-YEAR into account

Because first one will have to wait for 16 and the second is a bug fix anyway, so we can always backport it.

**Comment by nickvergessen** [comment]
I removed "#11871 Collaboration resources" as discussed with frank. Will be delayed to 16

**Comment by tobiasKaminsky** [comment]
Looking at pending enhancements half of it is related to apps, that are currently shipped with release.
Wouldn't it make sense to release the apps independent? Of course we can bundle them into release, but having it separately means that we only need any NC15 capable app version. 
Same like other apps, like News, Mail, …

**Comment by MorrisJobke** [comment]
> * [ ] #11663 Show a more specific error message if config file is not writable
> * [ ] #12119 Add Circle to Caldav and Filepanel
> * [ ] [files_pdfviewer#7](https://github.com/nextcloud/files_pdfviewer/pull/7) Change view design from dark to light
> * [ ] [gallery#265](https://github.com/nextcloud/gallery/pull/265) No need to construct the image in memory
> * [ ] [gallery#434](https://github.com/nextcloud/gallery/pull/434) Add livephotos support

Moved all of them to 16.

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Those are the failing tests of the first run:

* `tests/acceptance/features/users.feature:24`
* `tests/acceptance/features/app-files-tags.feature:4`
* `tests/acceptance/features/app-files-tags.feature:11`
* `tests/acceptance/features/app-files-tags.feature:31`
* `tests/acceptance/features/app-files-tags.feature:59`

Let's trigger a rerun and see how the second run goes and check if there are overlapping issues.

**Review by blizzz — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Thanks - this is good to be merged now 👍 Let's build it and check out how it works

**Pull request merged**
