### PR TITLE
fix(unified-search): Close on second ctrl+f

### PR DESCRIPTION
**Pull request by susnux**
* Part of #47424 

## Summary

A second ctrl+f should close the unified search again to use the native browser search.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by provokateurin** [comment]
Why workaround it first instead of removing this shortcut override completely?

**Comment by susnux** [comment]
> Why workaround it first instead of removing this shortcut override completely?

Because we can not break existing behavior on stable branches. For 31 we then can on a follow up remove the behavior.

**Review by nfebe — APPROVED** [review]
I realized this recently and it's a bit frustrating when you are trying to find something on page. Thank you!

**Review by provokateurin — APPROVED** [review]

**Comment by Fenn-CS** [comment]
> Because we can not break existing behavior on stable branches. For 31 we then can on a follow up remove the behavior.

Moreover this was not a thing with new unified search we had to actually re-introduce it because it has always been a Nextcloud feature.

I think, (CTRL+F)*2 is a decent way to handle this as still keep this "feature"

**Review by ChristophWurst — APPROVED** [review]
Merci

**Pull request merged**
