### PR TITLE
Add title attribute for app navigation items.

### PR DESCRIPTION
**Pull request by AasthaGupta**
Fix: #11923

### CODE REVIEW

**Comment by AasthaGupta** [comment]
Made some changes in the appNavigationItem.vue: https://github.com/nextcloud/vue-components/pull/73

**Comment by skjnldsv** [comment]
Hey!
You also need to ship the compiled file for the tests to pass 😉

**Comment by MorrisJobke** [comment]
> You also need to ship the compiled file for the tests to pass 😉

@skjnldsv Could you provide the command that builds the JS files? That would help a lot I guess.

**Comment by jancborchardt** [comment]
Any update here? Seems it was fixed in the components already, so should go in here too. :) @skjnldsv if you don’t mind, can you just compile the files? (Also – we need documentation there. ;)

**Comment by skjnldsv** [comment]
> (Also – we need documentation there. ;)

Hopefully we will have upgraded the modules to better suitable vue ones

**Comment by MorrisJobke** [comment]
It looks like a push went wrong :( Could we somehow help you to resolve the issues in the git history here?

**Comment by rullzer** [comment]
I found the commit. Took it and compiled the asset.

Lets do this. :rocket:

**Review by skjnldsv — APPROVED** [review]
https://github.com/nextcloud/nextcloud-vue/blob/bf2e56ee3b017dd09040acf07cbd3c2f6ef231b4/src/components/AppNavigationItem/AppNavigationItem.vue#L30

Yes! :+1:

**Review by rullzer — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure unrelated

**Pull request merged**
