### PR TITLE
Makes select2 in settings/admin look the same like everywhere else

### PR DESCRIPTION
**Pull request by vincchan**
Makes this:

screen shot 2016-06-23 at 12 38 18

look like this:

screen shot 2016-06-23 at 12 41 25

please review @nextcloud/designers thanks :)

### CODE REVIEW

**Comment by williambargent** [comment]
I think the field should be the same height as before; other than that looks good.

**Comment by vincchan** [comment]
@williambargent oh my bad, that is not the same select field. Height is still the same

screen shot 2016-06-23 at 12 57 27

**Comment by jancborchardt** [comment]
@vincchan aaawesome! I wanted to do that since some time. Did you check it also works everywhere else we use select2, like the tags sidebar and the apps menu where you can restrict apps to specific groups?

**Comment by vincchan** [comment]
@jancborchardt I don't see it anywhere else where it looks out of place, but if you want to make sure that every select2 is replaced with the css we could put the changes into a core css file where it is sure to be included in the template

**Comment by williambargent** [comment]
:+1:

**Comment by LukasReschke** [comment]
LGTM. Awesome stuff 🚀

**Pull request merged**
