### PR TITLE
Log trace when deprecated globals are used

### PR DESCRIPTION
**Pull request by ChristophWurst**
this is *very* verbose but will only be active when debug mode is on

@nextcloud/javascript what do you think?

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Fine for me :)

**Review by juliusknorr — APPROVED** [review]
:+1:

**Review by blizzz — APPROVED** [review]

**Review by gary-kim — APPROVED** [review]

**Comment by ChristophWurst** [comment]
I think this was a bad idea. This kills my FF when debugging other stuff.

**Comment by MorrisJobke** [comment]
> I think this was a bad idea. This kills my FF when debugging other stuff.

Then revert it.

**Comment by ChristophWurst** [comment]
By bad. I assumed Github would automatically link the two PRs. So here it is: https://github.com/nextcloud/server/pull/20936

**Pull request merged**
