### PR TITLE
l10n: Change apostrophe

### PR DESCRIPTION
**Pull request by Valdnet**
@szaimen Not noticed in previous approval 😉.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by rakekniven — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by szaimen** [comment]
Added this change manuallly to https://github.com/nextcloud/server/pull/32133

**Pull request merged**
