### PR TITLE
fix password reset if encryption is enabled

### LINKED ISSUE #2546: Resetting password with encryption enabled shows spinning wheel forever
When encryption is enabled and a user resets his password by clicking the "Reset password" button, an error message is displayed and a spinning wheel which spins forever. The password is successfully changed though.  It would great if the user could be informed about the successful change and the error could be for example an appropriate warning instead. 

Sceenshots:

1)
image
All fine here, let's tick the checkbox and click Reset password"

2)
image
Ooops, unexpected error message and spinning wheel spinning forever. But password was changed successfully.

Tested with the latest master.

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/nextcloud/server/issues/2546

Steps to test:

1. enable encryption
2. try to reset the users password

cc @GitHubUser4234

### CODE REVIEW

**Comment by nickvergessen** [comment]
Okay, I can reset the password now, but that doesnt really help at all.
I get the following message afterwards:
> Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.

But this is not possible since you forgot it and reset it, right? And the user can't even hard reset his key to start from scratch?

**Comment by schiessle** [comment]
That's how it is. That's because you get the warning in advance which you have to accept. If you lost the password and don't have a recovery key your files are lost. But this way you can at least login again, e.g. to get to your contacts, calendar, etc

**Comment by nickvergessen** [comment]
Yeah no problem with "your key is lost" my problem is you can not create a new one. Maybe when we show that box thingy, we should also show a button/link to screw the old key and generate a new one. So you can upload new files afterwards.

**Comment by schiessle** [comment]
> Maybe when we show that box thingy, we should also show a button/link to screw the old key and generate a new one. So you can upload new files afterwards.

Maybe... Maybe not 😉 But that's out of the scope for this PR. This PR should just fix the password reset to work again as before. New features like "replace my private" key can be discussed separately.

**Comment by GitHubUser4234** [comment]
Yep , agree, there's some room for improvements which could be discussed in another PR.

@schiessle : I tested, the user gets logged in automatically after the password reset, which is great. However as mentioned in #2546, a PrivateKeyMissingException is logged with log level 3. As resetting password with encryption is a feature, it looks reasonable to remove the error or at least to lower the log level. What'd you say?

**Review by nickvergessen — APPROVED** [review]

**Comment by schiessle** [comment]
@GitHubUser4234 The problem is that the error and the logging happens at a level where we don't know that we reset the password and therefore it is not critical.

**Comment by GitHubUser4234** [comment]
@schiessle Hehe, I didn't understand the "therefore it is not critical" part, could you please elaborate? Thing is when the nc log is monitored in a production environment for log level 3 entries and the PrivateKeyMissingException is thrown without actually being an error, the administrator would be falsely alerted. Last but not least, the purpose of log levels is to make distinguishing between error, warning, info messages etc. possible? On the other hand, I understand that it might involve some more work to implement this...maybe something for another PR? :D

**Comment by LukasReschke** [comment]
Seconding @GitHubUser4234 here.

@schiessle Should we fix this here or do a new issue about that and merge this one?

**Comment by schiessle** [comment]
I consider the logging issue a flaw, but nothing critical because everything works fine with this PR. As said, the problem is that the exception happens at a point in the code where we can't say what's the reason for it, so we can't distinguish the logging level or decide to ignore it completely because it is a password change. We can look into improving error messages, sure. But this is out of scope for this PR.

Here I want to fix the password reset.

Please just review if password reset works with this PR or not. I would like to get this in in time and also backported to stable11 because password reset should work.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
