### PR TITLE
Migrate TagMapper to QBMapper instead of deprecated Mapper

### PR DESCRIPTION
**Pull request by come-nc**
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by CarlSchwan** [comment]
Similar to https://github.com/nextcloud/server/pull/32012 

But blocked due to an unit test failures 😔

**Comment by come-nc** [comment]
> Similar to #32012
> 
> But blocked due to an unit test failures pensive

Hum but #32012 does not touch lib/private/Tagging/TagMapper.php ?

**Review by CarlSchwan — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:hatching_chick:

**Pull request merged**
