### PR TITLE
Add back the deleted.png file

### LINKED ISSUE #32757: [Bug]: delete.png doesn't exist in core/img/actions/
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In apps/settings/lib/Activity/SecurityProvider.php on line 90 and 101 we reference a PNG that does not exist:

https://github.com/nextcloud/server/blob/b7bce42078369fc48df8234fb8e2f110f7b6484d/apps/settings/lib/Activity/SecurityProvider.php#L90

This bug is triggered when the PNG format is enforced for the Activity app emails in MailQueueHandler::sendEmails.

### Steps to reproduce

1. Install the activity app
2. Have a case of "remote_wipe_start`or'remote_wipe_finish' to report
3. The sending of the activity email fails because the PNG does not exist.

### Expected behavior

The email sends.

### Installation method

Manual installation

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
--
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
{
    "reqId": "TKpiD97xm0eCaMFj0LKO",
    "level": 3,
    "time": "2022-06-02T08:00:03+00:00",
    "remoteAddr": "",
    "user": "--",
    "app": "activity",
    "method": "",
    "url": "--",
    "message": {
        "Exception": "RuntimeException",
        "Message": "image not found: image:actions/delete.png webroot: serverroot:/var/www/nextcloud",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/nextcloud/apps/settings/lib/Activity/SecurityProvider.php",
                "line": 91,
                "function": "imagePath",
                "class": "OC\\URLGenerator",
                "type": "->",
                "args": [
                    "core",
                    "actions/delete.png"
                ]
            },
            {
                "file": "/var/www/nextcloud/apps/activity/lib/MailQueueHandler.php",
                "line": 454,
                "function": "parse",
                "class": "OCA\\Settings\\Activity\\SecurityProvider",
                "type": "->",
                "args": [
                    "de",
                    {
                        "__class__": "OC\\Activity\\Event"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/apps/activity/lib/MailQueueHandler.php",
                "line": 359,
                "function": "parseEvent",
                "class": "OCA\\Activity\\MailQueueHandler",
                "type": "->",
                "args": [
                    "de",
                    {
                        "__class__": "OC\\Activity\\Event"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/apps/activity/lib/MailQueueHandler.php",
                "line": 164,
                "function": "sendEmailToUser",
                "class": "OCA\\Activity\\MailQueueHandler",
                "type": "->",
                "args": [
                    "fjldksjfdslkjflkdsjflkdsjlfkjdskjfkl",
                    "axxxxx@xxx.de",
                    "de",
                    "Europe/Berlin",
                    1654156802
                ]
            },
            {
                "file": "/var/www/nextcloud/apps/activity/lib/BackgroundJob/EmailNotification.php",
                "line": 61,
                "function": "sendEmails",
                "class": "OCA\\Activity\\MailQueueHandler",
                "type": "->",
                "args": [
                    500,
                    1654156802
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/BackgroundJob/Job.php",
                "line": 52,
                "function": "run",
                "class": "OCA\\Activity\\BackgroundJob\\EmailNotification",
                "type": "->",
                "args": [
                    null
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php",
                "line": 59,
                "function": "execute",
                "class": "OC\\BackgroundJob\\Job",
                "type": "->",
                "args": [
                    {
                        "__class__": "OC\\BackgroundJob\\JobList"
                    },
                    {
                        "__class__": "OC\\Log"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/cron.php",
                "line": 127,
                "function": "execute",
                "class": "OC\\BackgroundJob\\TimedJob",
                "type": "->",
                "args": [
                    {
                        "__class__": "OC\\BackgroundJob\\JobList"
                    },
                    {
                        "__class__": "OC\\Log"
                    }
                ]
            }
        ],
        "File": "/var/www/nextcloud/lib/private/URLGenerator.php",
        "Line": 238,
        "CustomMessage": "Failed sending activity email to user \"{user}\""
    },
    "userAgent": "--",
    "version": "20.0.14.4"
}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by miaulalala**
as SVG forwarding doesn't work for /core/img

Fixes https://github.com/nextcloud/server/issues/32757

@marcoambrosini would you be able to extract a 32x32 png from the SVG? The old version is only 16x16.

### CODE REVIEW

**Comment by marcoambrosini** [comment]
Yes I think so, Is it ok if I use the material design icon? We're adopting those everywhere

**Comment by marcoambrosini** [comment]
done!

**Review by marcoambrosini — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
