### PR TITLE
[stable20] Explicitly allow some routes without 2FA

### PR DESCRIPTION
**Pull request by blizzz**
Backport of #29752

### CODE REVIEW

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Let's get #29556 merged 😄.

**Comment by rakekniven** [comment]
v20.0.14 is already out since 12 Nov.
Can I remove milestone?

**Comment by MichaIng** [comment]
Ah, so no more NC20 release?

**Comment by blizzz** [comment]
> If wanted for customers, it can be always reopened.

Aye

**Pull request merged**
