### PR TITLE
Fix installing with MySQL 8.0.4+

### PR DESCRIPTION
**Pull request by nickvergessen**
See https://help.nextcloud.com/t/the-server-requested-authentication-method-unknown-to-the-client/33038

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by georgehrke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Review by gary-kim — APPROVED** [review]

**Comment by ofrancois** [comment]
Hi,

This message to report a potential regression due to this merge.
The regression occurs when using MariaDb server.
It occurs during the initial setup wizard (first failure when createSpecificUser method is called)

Reverting this commit makes the setup wizard work again.

This issue is reproducible.

Test environment:
Database: MariaDb version 1:10.3.17-0+deb10u1
OS: Raspbian GNU/Linux 10 (buster)
Nextcloud: v17.0.2

**Comment by kesselb** [comment]
Thanks @ofrancois :+1: 

That's the related report: https://github.com/nextcloud/server/issues/18513

**Pull request merged**
