### PR TITLE
fix mail template

### PR DESCRIPTION
**Pull request by mkofahl**
Mail clients may hide the content if the table showing the logo is at 100% height.

### CODE REVIEW

**Comment by gary-kim** [comment]
Could you add a [DCO](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work) to your commit? The easiest way would be to add the `-s` flag from the command line. You can run the following command to add a DCO from the head of your commit: `git commit -s --amend` then `git push --force-with-lease`.
Otherwise, you can also add the following to the bottom of your commit message.
```
Signed-off-by: Random J Developer <random@developer.example.org>
```

**Comment by nickvergessen** [comment]
@mkofahl any specific client you had a problem with?

**Comment by mkofahl** [comment]
> @mkofahl any specific client you had a problem with?

Yes, Zimbra.

**Comment by MorrisJobke** [comment]
@jancborchardt @skjnldsv Do you think this is okay CSS-wise?

**Comment by skjnldsv** [comment]
@mkofahl can you post before/after screenshotsplease, we usually like to have direct comparison on design pull requests!
Thanks for your work!! :rocket:

**Comment by J0WI** [comment]
ping @mkofahl

**Comment by MorrisJobke** [comment]
Let's close it as we can reopen it at any time anyways.

**Pull request closed without merging**
