### PR TITLE
[stable9] Add JS Unit tests

### PR DESCRIPTION
**Pull request by MorrisJobke**
Use proper PhantomJS library and run the tests as separate step
- add dependency for phantomjs

@schiessle @LukasReschke I guess this was broken while working on the hidden file upload feature

Backport of #33

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> @schiessle @LukasReschke I guess this was broken while working on the hidden file upload feature

Bisecting shows that 68c38ae8c297ea2cca73d75d9a6cc047cde8d4d7 bricked it. I will try to fix this.

**Comment by MorrisJobke** [comment]
@blizzz @LukasReschke @schiessle Please test the hell out of this! :)

**Comment by LukasReschke** [comment]
LGTM, thanks for taking care @MorrisJobke 🚀 🎉

**Comment by MorrisJobke** [comment]
I tested this and it works here LGTM

**Pull request merged**
