### PR TITLE
update icewind/smb to 3.2.5

### PR DESCRIPTION
**Pull request by icewind1991**
Should fix the "Uninitialized string offset: 0" issue described in https://github.com/nextcloud/server/issues/21177

@beckenc @altae7 can you check if this fixes the issue for you

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant:

**Comment by beckenc** [comment]
> Should fix the "Uninitialized string offset: 0" issue described in #21177
> 
> @beckenc @altae7 can you check if this fixes the issue for you

Looks quite good! No exception so far...
Thanks!

**Comment by altae7** [comment]
Unfortunately I cannot test it anymore as the issue disappeared with the update of NC to 18.0.5. But thanks for your effort anyway.

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
