### PR TITLE
Indicate users default quota (issue: #11393)

### LINKED ISSUE #11393: [Enhancement] Indicate users default quota
In the administrators user list, the quota for each user is displayed. At the moment, it is not apparent which users have the default quota and which have the same quota defined manually, as only the number is displayed.

When changing a users quota to default, it reads `Default quota`. However, after a page reload, only the number is displayed again.

It would be nice to have a reading such as `10 GB (default)` or similar instead of only `10 GB`.

### PR DESCRIPTION
**Pull request by MasterOfDeath**
fixes #11393

### CODE REVIEW

**Comment by violoncelloch** [comment]
PR #12087 targets the same issue

**Comment by juliushaertl** [comment]
Thank you very much for your pull request @MasterOfDeath and welcome as a Nextcloud contributor. As @violoncelloch mentioned there is another PR #12087, that uses existing data in the frontend to indicate the default quota. I'd vote to go this approach instead of extending the backend code with another parameter.

**Comment by juliushaertl** [comment]
cc @skjnldsv for feedback

**Comment by danielkesselberg** [comment]
Ref #12159

**Comment by juliushaertl** [comment]
Let's go with #12087, since that seems to be the cleanest approach code wise. Anyway thanks for the work @MasterOfDeath, I hope to see more contributions from you soon :wink:

**Pull request closed without merging**
