### PR TITLE
Loss of performance on Login after upgrade from NC10 + LDAP to NC 12 …

### PR DESCRIPTION
**Pull request by fgsl**
…+ LDAP #6732

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
IMO it's safe to immediately flag the token as checked to prevent it being checked right after the login. I don't see any scenario where a check would be necessary or even fail.

**Comment by ChristophWurst** [comment]
@LukasReschke thoughts?

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Review by LukasReschke — APPROVED** [review]

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Will open a new PR including this change and fixed tests. Thanks a lot!

**Comment by LukasReschke** [comment]
PR with fixed tests is at https://github.com/nextcloud/server/pull/7297

**Pull request closed without merging**
