### PR TITLE
Improved exception messages

### PR DESCRIPTION
**Pull request by MorrisJobke**
- downstream of https://github.com/owncloud/core/pull/26250

@LukasReschke Should the path be removed from the exception message? Or is this no problem?

cc @rullzer @icewind1991 @nickvergessen

### CODE REVIEW

**Comment by LukasReschke** [comment]
> @LukasReschke Should the path be removed from the exception message? Or is this no problem?

Remove and log additionally.

**Comment by MorrisJobke** [comment]
> Remove and log additionally.

Done - ready for review.

cc @nickvergessen @rullzer

**Comment by rullzer** [comment]
LGTM!

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
