### PR TITLE
Add back missing personal Groupware settings bundle

### PR DESCRIPTION
**Pull request by ChristophWurst**
Regression of https://github.com/nextcloud/server/pull/30020.

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
This is not the first regression due to this PR and probably not the last :(

**Comment by artonge** [comment]
> This is not the first regression due to this PR and probably not the last :(

I guess every new bundle created between 01/12/2021 and  10/01/2022 are missing.

**Review by artonge — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Superseded by https://github.com/nextcloud/server/pull/31134

**Pull request closed without merging**
