### PR TITLE
Refactors files app commands

### PR DESCRIPTION
**Pull request by fsamapoor**
I have made some adjustments to the `apps/files/lib/Command` classes to improve the code readability.

The improvements in this PR include but are not limited to:

- Using PHP8's constructor property promotion
- Adding return types
- Replacing return code integers with more readable strings.
- Using early returns

### CODE REVIEW

**Comment by solracsf** [comment]
Psaml still failing with:

```
Error: apps/files/lib/Command/ScanAppData.php:170:21: InvalidArgument: Argument 1 of set_error_handler expects callable(int, string, string=, int=, array<array-key, mixed>=):bool|null, but list{OCA\Files\Command\ScanAppData&static, 'exceptionErrorHandler'} provided
```

**Comment by fsamapoor** [comment]
> Psaml still failing with:
> 
> ```
> Error: apps/files/lib/Command/ScanAppData.php:170:21: InvalidArgument: Argument 1 of set_error_handler expects callable(int, string, string=, int=, array<array-key, mixed>=):bool|null, but list{OCA\Files\Command\ScanAppData&static, 'exceptionErrorHandler'} provided
> ```

@solracsf I was searching for the solution since it seems to be a Psalm false positive error.

It does have a [hacky solution](https://github.com/vimeo/psalm/issues/3571) indeed that I didn't like to be quite honest.

In the end, I figured to just remove the return type from the method, as there are multiple similar methods in the codebase that do not have a return type and this way, the codebase remains consistent regarding the issue.
Anyways, all good now. Thanks for reminding me.

**Review by artonge — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by fsamapoor** [comment]
Resolving conflicts with web ide messed things up. Gonna fix the issue and report back ASAP.

**Comment by fsamapoor** [comment]
> Resolving conflicts with web ide messed things up. Gonna fix the issue and report back ASAP.

Fixed.

**Pull request merged**
