### PR TITLE
[stable29] fix(setupcheck): Fix mimetype server version check in backport

### PR DESCRIPTION
**Pull request by nickvergessen**
* Resolves: https://github.com/nextcloud/server/issues/47359

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Review by Trasted1 — APPROVED** [review]
Thank you! Error gone.

**Review by AndyScherzinger — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by supett** [comment]
running "occ setupchecks" shows  "✓ Mimetype migrations available: None". Error does not show there anymore neither.

Thanks

**Comment by AleksCee** [comment]
How can I become the fix if I just updated before the commit? 
If I run the updater there is no new version to install. 
Thanks

**Comment by WM-Loose** [comment]
@supett  Please... Not everyone here is an IT professional and it would be nice if the complete command was given. So the complete line that you have to enter in the directory. php83 ./occ.......

**Comment by supett** [comment]
> @supett Please... Not everyone here is an IT professional and it would be nice if the complete command was given. So the complete line that you have to enter in the directory. php83 ./occ.......
Hope this helps:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html

**Comment by AleksCee** [comment]
The call of the occ command is not the problem. But witch of the will update the fixed file? Upgrade say : everything is uptodate. Only patch the file manually will break the checksum. So what is the right way. Or have Wochenende wait for 29.0.6?

**Comment by 7ts-it** [comment]
Hi there! 
If I understand correctly and you have nc29, edit lib/private/Repair/RepairMimeTypes.php. 
This file is in the root of your webserver (eg. /var/www/nextcloud/lib/private/Repair/RepairMimeTypes.php)
Got to line 427 and change it from
		_if (version_compare($mimeTypeVersion, '**30.0.0.0**', '<') && $this->introduceExcalidrawType()) {
to_
		_if (version_compare($mimeTypeVersion, '**29.0.5.0**', '<') && $this->introduceExcalidrawType()) {_

as described above in [fix(setupcheck): Fix mimetype server version check in backport](https://github.com/nextcloud/server/pull/47378/commits/9be51b38e3c1c6df19e550d68c230932062cad18)

Have a nice day...
chris

**Comment by AleksCee** [comment]
Yes, this works for me too, but if you then do an integrity check the file was marked as broken:
occ integrity:check-core  
  - INVALID_HASH:
    - lib/private/Repair/RepairMimeTypes.php:
      - expected: cbe37950a516bdaa081a318a5ea934c424c4fcd16d8690efdfa68a09241c553cdb41f3994a451dd20d69d15a6525f988e3fcb3668e8fb50f6f9afd60bc0aa9d1
      - current: 1e88dcb09eeb47ad50485ff0eeb6483ee36607c14c409595a690ecf12f7b30ae9309b801a732187596eb717e2fd55f77c0588e8e3696e4878787329a7b922412

**Comment by mritzmann** [comment]
@WM-Loose You can ignore the warning. Simply wait for the next Nextcloud version. You have no advantage if you fix it now, it's just a false warning with no disadvantage.

**Comment by WM-Loose** [comment]
Yes, I do that with all customer installations and wait for the update. 

I made the adjustment (fix) for our own installations and that is completely sufficient for me.

 

Von: Markus Ritzmann ***@***.***> 
Gesendet: Freitag, 23. August 2024 08:44
An: nextcloud/server ***@***.***>
Cc: Dirk ***@***.***>; Mention ***@***.***>
Betreff: Re: [nextcloud/server] [stable29] fix(setupcheck): Fix mimetype server version check in backport (PR #47378)

 

@WM-Loose <https://github.com/WM-Loose>  You can ignore the warning. Simply wait for the next Nextcloud version. You have no advantage if you fix it now, it's just a false warning with no disadvantage.

**Comment by filerem** [comment]
> * Resolves: [[Bug]: Warning: One or more mimetype migrations are available #47359](https://github.com/nextcloud/server/issues/47359)
> 
> 
> ## Checklist
> 
>     * Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
> 
>     * [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
> 
>     * [x]  Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
> 
>     * [x]  Screenshots before/after for front-end changes
> 
>     * [x]  Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
> 
>     * [x]  [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

Thanks! it's work for me.

**Comment by sultanoswing** [comment]
Fix by changing line 427 works for me - thanks!

Interestingly, I don't get the invalid_hash error by doing so. Could be something to do with running my instance in docker, since I don't remember changing a setting or config file elsewhere!

And can I just say, this is a terrible bug for all of the (many) nextcloud users with OCD over that green tick :)

**Comment by 7ts-it** [comment]
You have to run 
_sudo -u www-data php  occ integrity:check-core_ 
in to see  
  _- INVALID_HASH:
    - lib/private/Repair/RepairMimeTypes.php:
      - expected: cbe37950a516bdaa081a318a5ea934c424c4fcd16d8690efdfa68a09241c553cdb41f3994a451dd20d69d15a6525f988e3fcb3668e8fb50f6f9afd60bc0aa9d1
      - current: 1e88dcb09eeb47ad50485ff0eeb6483ee36607c14c409595a690ecf12f7b30ae9309b801a732187596eb717e2fd55f77c0588e8e3696e4878787329a7b922412_

Have a nice day
chris

**Comment by sultanoswing** [comment]
Ahhh - that'll be it - thanks! It's been a while since I used the web updater or via CLI, and you don't get that message when updating your instance via docker and docker build file, so I'd forgotten :)

**Pull request merged**
