### PR TITLE
Class defaultTokenProvider does not exist

### PR DESCRIPTION
**Pull request by JaroSu**
Fix for:
PHP Fatal error: Uncaught OCP\AppFramework\QueryException: Could not resolve defaultTokenProvider! Class defaultTokenProvider does not exist

### CODE REVIEW

**Comment by JaroSu** [comment]
It's work perfect.

**Comment by danielkesselberg** [comment]
Do you have any idea why the test suite is failing? https://drone.nextcloud.com/nextcloud/server/11166 Can you still reproduce the issue (when you revert your or?). Maybe https://github.com/nextcloud/server/pull/11316 would help to find the reason for this error.

**Comment by JaroSu** [comment]
I think it will fix all errors with defaultTokenProvider, which starts with a lowercase letter. This is name of property. Class name (type) is DefaultTokenProvider. Class defaultTokenProvider does not exist and it's true.
I no idea why tests fails.

**Comment by danielkesselberg** [comment]
Test-Suite works for me when `getType()` => `getType()->getName()`. Is error fixed for you with this as well?

**Comment by JaroSu** [comment]
Yes.
This should by getType()->getName() or getType()->__toString(). [reflectiontype](http://php.net/manual/en/class.reflectiontype.php)
My mistake.

**Comment by ChristophWurst** [comment]
> Class name (type) is DefaultTokenProvider

As far as I can tell, it's either queried with lower case (constructor parameter name) or its fully-qualified class name which is prefixed by the namespace.

**Comment by rullzer** [comment]
Could I ask you to open an issue with what you are trying to fix here.
The code is actually doing what is should. If the DI is not working that is then probably because something is not injected at the right place.

**Pull request closed without merging**
