### PR TITLE
disable timeout on app install via cli

### PR DESCRIPTION
**Pull request by blizzz**
this helps at least with installation/updating of big apps via CLI. Web UI is a different story, still.

### CODE REVIEW

**Comment by blizzz** [comment]
related issues: https://github.com/nextcloud/server/issues/17808 https://github.com/nextcloud/server/issues/17776 https://github.com/nextcloud/documentserver_community/issues/26 (they are also all web ui related)

**Review by ChristophWurst — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

**Comment by nickvergessen** [comment]
Well most of the issues suggest a value of 120, which we now have in 18.0.1 it was jsut not released yet

**Comment by blizzz** [comment]
> Well most of the issues suggest a value of 120, which we now have in 18.0.1 it was jsut not released yet

```
curl -Lm 0 --output /dev/null https://github.com/nextcloud/documentserver_community/releases/download/v0.1.5/documentserver_community.tar.gz 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   622    0   622    0     0   1026      0 --:--:-- --:--:-- --:--:--  1026
100  301M  100  301M    0     0  2324k      0  0:02:12  0:02:12 --:--:-- 2994k
```

**Comment by nickvergessen** [comment]
Yeah sure, just be aware people will still run into this from the web, but well don't care, continue

**Comment by blizzz** [comment]
> Yeah sure, just be aware people will still run into this from the web, but well don't care, continue

Yes, I discussed it with @rullzer earlier today, and agreed on doing the CLI change for now only.

**Comment by rullzer** [comment]
Yeah from the CLI I'm fine. Poeple can then easily cancel it anyways.

**Review by icewind1991 — APPROVED** [review]

**Pull request merged**
