### PR TITLE
fix(files): reset menu pos when opening in grid mode

### LINKED ISSUE #45556: [Bug]: Right-click context menu on wrong position after switiching to grid view
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you are in the Files UI, use the right-click there, then switch to the grid view and try to use right-click as well, then the context menu will always appear on the last position when it was opened in list view. A reload fixes it. Please confer the screen recording.

[Screencast_20240528_213110.webm](https://github.com/nextcloud/server/assets/2184312/cca2c59f-a8b0-485e-a5cb-b0ae98656092)

This affects also NC 28 (did not try further down).

### Steps to reproduce

1. In the Files list view, right-click an item
2. Switch to grid view
3. Right-click any item now

### Expected behavior

The context menu is opened below or above the grid view item.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

No warning or error in the browser console.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/45556

### CODE REVIEW

**Review by blizzz — APPROVED** [review]
Works! Assets have to be built though.

**Review by Pytal — APPROVED** [review]

**Pull request merged**
