### PR TITLE
Improved display of app links

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Respawn of [#37823](https://github.com/nextcloud/server/pull/37823/)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by nimishavijay — APPROVED** [review]

**Comment by Jerome-Herbinet** [comment]
May it be added to Nextcloud 27 Milestone ?

**Comment by szaimen** [comment]
> May it be added to Nextcloud 27 Milestone ?

you can summon the backport for this

**Comment by Jerome-Herbinet** [comment]
> > May it be added to Nextcloud 27 Milestone ?
> 
> you can summon the backport for this

Hmmm, I've never done that before ; can you tell me the method ? @szaimen

**Comment by Jerome-Herbinet** [comment]
> > > May it be added to Nextcloud 27 Milestone ?
> > 
> > 
> > you can summon the backport for this
> 
> Hmmm, I've never done that before ; can you tell me the method ? @szaimen

This way ?
Capture d’écran du 2023-05-30 16-44-22

**Comment by szaimen** [comment]
> This way ?

No, the milestone should stay Nextcloud 28. But you can summon the backport bot by so:

**Review by nfebe — APPROVED** [review]
screenshots?

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet `/backport to stable27` (as comment here would do)

Thanks :-)

**Comment by Jerome-Herbinet** [comment]
> screenshots?

**Comment by Jerome-Herbinet** [comment]
> > Thanks @Jerome-Herbinet just to add that, when you are adding a screen add the before and after. Also you can add it as part of the original PR description (or first comment).
> > Thanks for the work!
> 
> Yep you are right, I did all that in a bit of a rush, sorry.
> 
> Before : 

@Fenn-CS I updated the top first comment with the "before" and "after" screenshot.

**Comment by szaimen** [comment]
/backport e25fb29975ed99a3a0b8607b5a177d83e6beafcc to stable27

**Pull request merged**
