### PR TITLE
enforcement of two-factor authentication for specific network ranges

### PR DESCRIPTION
**Pull request by mkofahl**
Support enforcement of two-factor authentication for specific network ranges (refs #20857). This patch still has some work open for the ui (someone familiar with vue?) and for translations.

The patch uses code from the Symfony package, MIT licensed. I expect this to be compatible with AGPLv3. Can anybody confirm this?

### CODE REVIEW

**Comment by rullzer** [comment]
I am not a fan of this. It creates so much more issues that it solves in my opinion

Login is something that happens very rarely, on my prodution setup the last time I saw my login screen was when I got my new phone.

There are some unsolved issues here.

* Lets say you login on your laptop at work and take it home. You will still be logged in.
Is this what you want. Or you can create as many app password as you'd like without having to every validate your second factor.

What this is effectively is doing is adding a way in Nextcloud do disable 2FA in some cases. I really don't like that.

What might be a solution if this is really wanted is to extend the 2FA providers interfaces to also have an interface that can signal that they passed already. I'm not 100% sure how this would look but then it would need to be an app enabled by the admin and not a core feature of Nextcloud. Because adding ti like this really feels like poking holes where we should not.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/server/issues/2035 for the detailed discussion and the many linked tickets. I'm also opposed to this change.

The risk of a security issue arising from this is higher than the UX gain. As @rullzer said the login happen so rarely that you would not have to worry about this often. Github also does it very similar to us. You're logged in forever if you use the platform regularly. If you're absent for ~2 weeks then you have to fully re-authenticate, including 2FA.

**Comment by mkofahl** [comment]
The logon and logoff is handled differently by the users. I observe that many log in to the web interface in the morning and log out again in the evening.
To enforce 2FA by IP is basically the same as by user group. In a trustworthy network area, perhaps the standard case, one could forgo a second factor and nevertheless automatically request it for (new) logins from other network areas. Because the default setting requires 2FA for all networks, the security of NextCloud in my opinion is not generally softened.

**Comment by rullzer** [comment]
Groups are different. Because it is either you have it for all admins for example or not. This is effectively disabling 2FA in certain cases. (even if it is enforced for all users).

Like I said. I would feel more for an approach where the current system is extended. So that app can provide already if their 2FA is met when requesting the list. That way you could just have an app where you could set these ranges.

Or have an app where you could record IPs with successfull 2fa login and record them to not ask again etc.

**Comment by rullzer** [comment]
So as to move this forward. I would like to have this not in core. But rather have the mechanism to allow direct (non user input) providers. If this is required by people. Then this provider will just be another 2fa provider.

But doing this in the core itself is undesirable from my point of view.

**Pull request closed without merging**
