### PR TITLE
fix(files): Adjust sidebar - remove deprecated function calls and add aria label for favorite icon

### PR DESCRIPTION
**Pull request by susnux**
## Summary

1. Replace some deprecated function calls with the replacement (mostly `OC.` -> `@nextcloud/...`).
2. Replace star symbol with image and proper `aria-label` for the favorite marker

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by JuliaKirschenheuter — APPROVED** [review]
great, thank you!

**Review by ShGKme — APPROVED** [review]
Works and fixes a11y issue.

I've noticed one non-comfortable place in the `NcAppSidebar` - actions if the next element after header, so reading the page in browse mode, you read:
1. File name
2. Actions
3. Close button
4. Favorite, size, date (aka description for the file from 1)

**Pull request merged**
