### PR TITLE
Allow 0 quota by provisioning api

### LINKED ISSUE #9553: Cannot set 0 bytes quota with new user management
After #8824 it's not possible to set 0 Bytes (0 B) Quota on a user, because this is not supported by the provisioning api.

0 B results always in Unlimited.

@skjnldsv @MorrisJobke

### PR DESCRIPTION
**Pull request by skjnldsv**
@nextcloud/designers @michag86

Fix #9553

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Solves the issue in the user list 👍 

In the settings for the default quota it then shows "none" and when clicking on the drop down it shows that "Unlimited" is selected. Maybe some refinements are needed there as well.

bildschirmfoto 2018-05-28 um 15 50 19
bildschirmfoto 2018-05-28 um 15 50 28

**Comment by skjnldsv** [comment]
@MorrisJobke yeah, I added this fix as well (sneaky fix ;) )

**Comment by MorrisJobke** [comment]
> @MorrisJobke yeah, I added this fix as well (sneaky fix ;) )

But I have the latest version fetched 😕

**Comment by MorrisJobke** [comment]
> But I have the latest version fetched 😕

Maybe caching :/

**Comment by MorrisJobke** [comment]
> Maybe caching :/

No - even after a cleared cache it still doesn't work

**Comment by skjnldsv** [comment]
Bump! :)
Rebased to latest vue testing

**Comment by rullzer** [comment]
Ha this does :boom: when you set the quota to 0 before they are logged in.

But this is not caused by this PR but was already the case.
Let me fix that.

**Review by rullzer — APPROVED** [review]
Seems good to me now!

**Pull request merged**
