### PR TITLE
Fix share owner not being displayed in sharing tab

### PR DESCRIPTION
**Pull request by CarlSchwan**
This only concerns subfolder and files inside a shared folder and is
used as fallback when the OCS api returns a empty result, because it
only works on the shared folder and not the content inside of it.
This unify the tab with the folder list.

This offers a less descriptive share information but making the
OCS api returns all the details even for the subfolder would very
probably be bad for performance (since we would need to fetch the shares
for all the parent folders until we found one or are in the root folder).

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by Pytal — COMMENTED** [review]
As the folder owner somehow it got to this state 
image
due to `this.fileInfo.shareOwnerId` being `undefined` but not sure why 🤷‍♂️

**Comment by CarlSchwan** [comment]
> As the folder owner somehow it got to this state image due to `this.fileInfo.shareOwnerId` being `undefined` but not sure why man_shrugging

Yeah I noticed that and forgot to push the change. Now I need to fix the conflict and compile the assets again

**Review by Pytal — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Backports?

**Pull request merged**
