### PR TITLE
Check for PASSWORD_ARGON2ID

### PR DESCRIPTION
**Pull request by solracsf**
As we already check for it at https://github.com/nextcloud/server/blob/master/lib/private/Security/Hasher.php

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
Good idea!

The entire reason for this check to exist is that we saw users who updated from php7.2 (using third party repo for centos/rhel) to 7.4 from rhel and then wondered why their password doesn't work anymore since rhel insist on not packaging argon2.

Ideally, we should also check if the database contains a password encrypted with this password using something like: SELECT COUNT(1) FROM oc_users WHERE password LIKE "3$argon2%"; and a similar check for shares passwords. If there is no such password, we don't really need to show a message. I'm just not sure if this is worth the work... Anyway, this is a separate issue to this PR :)

**Comment by MichaIng** [comment]
Shouldn't it be an `(!Argon2I || !Argon2ID)` instead of AND, since we do not know whether any password is currently hashed with the one or the other? An actual check for how passwords are hashed would be great, especially since with <1s hashing time bcrypt seems to be actually better (hence changing the default would then be). But not sure how practical this can be done for all cases/apps/backends.

**Comment by acsfer** [comment]
@MichaIng With OR, you check if one OR another aren't defined. So, even if only one is installed, warning would be triggered.

When you check https://github.com/nextcloud/server/blob/223ae801fedca9fe5d4d8a11aa9ab28a667e0f93/lib/private/Security/Hasher.php#L67 is checks for one or another, so warning makes sense only if BOTH (so, AND) aren't defined. 

With AND, you check if one AND another aren't defined, so the warning is triggered only if none is defined (which is the correct behavior, correct me if i'm wrong, year has been long 😝).

**Comment by MichaIng** [comment]
For the hasher it makes sense to check for one OR the other since both take the same hashing parameters and currently any of both is preferred over bcrypt. But for compatibility checks, when we do not know whether one or the other both algorithms are/were used for stored password hashes, we consequently need to assure that both are present to rule out errors after PHP upgrades/migrations, hence print a warning already when only one is missing, isn't it? If it was not about passwords which are stored already but only about a recommendation to have any Argon2 algorithm available over bcrypt, then AND indeed would be fine.

**Pull request closed without merging**
