### PR TITLE
fix(user-management): Fix deleting user in hidden group(s)

### PR DESCRIPTION
**Pull request by ChristophWurst**
E.g. guest_app

* Resolves: # 

## Summary

1) Set up https://github.com/nextcloud/guests
2) Create a guest user
3) Open user management
4) Delete the user

Master/stable25/stable24: :boom: TypeError because e.groups.find(...) is undefined
Here: warning but :sunglasses: 

## TODO

- [x] Do

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by ChristophWurst** [comment]
CI failures look unrelated, especially the S3 ones.

**Pull request merged**
