### PR TITLE
fix background shadow in high-contrast-mode

### LINKED ISSUE #33833: popups in dark mode are missing better visible background shadow or outlines
See 
image
image

This gets even more serious with high-contrast-mode enabled:
image
image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/33833

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by skjnldsv** [comment]
Should it even have shadows?

**Comment by szaimen** [comment]
> Should it even have shadows?

Otherwise it will not be separated from the background so no high-contrast anymore...

**Review by skjnldsv — APPROVED** [review]

**Comment by andyxheli** [comment]
@szaimen what do you think about doing the same think here ?

image

**Comment by szaimen** [comment]
This will look strange in the default dark mode. cc @jancborchardt @CarlSchwan

**Pull request merged**
