### PR TITLE
Fix share input id

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Fix sharing `label` → `input` element association

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by szaimen** [comment]
What does this fix?

**Review by artonge — APPROVED** [review]

**Comment by Pytal** [comment]
> What does this fix?

This correctly associates the `label` with the VueSelect `input` element as described in https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-explicitly

**Review by szaimen — APPROVED** [review]
Fine by me then

**Review by JuliaKirschenheuter — APPROVED** [review]

**Pull request merged**
