### PR TITLE
Kill stale bot

### PR DESCRIPTION
**Pull request by kesselb**
Bot is not working. People are confused because issues are tagged as stale without a reason.

FYI: https://github.com/probot/stale/issues/207

### CODE REVIEW

**Comment by skjnldsv** [comment]
Actually I'd rather leave it.
It's tagging unsorted issues and it's pigging old ones. :)

**Comment by skjnldsv** [comment]
@kesselb since you've been doing lots of triage as well lately, let me give you a recent guidelines we talked about internally (we figured we should make them public somewhere on the server repo, but did not have the time, it was 4 days ago ;) )

___

All new issues have the `0. Needs triage` label.
All issues in the repo should have at least one blue status label
(either `1. to develop`, or a progress one like `2. developing`...)

## Bugs:
  - If the bug is reproducible, we remove the `0. Needs triage` and
apply the `1. to develop`
  - If we need more info, we MUST add the 'needs info' after pinging the
author. We leave the `0. Needs triage` label.
  - If it is not, we close
  - We should never remove the `0. Needs triage` without adding another
blue progress label

## Features.
We come to a point where we cannot really handle al the feature request
load. So we have to draw a line.
We all have different opinions, but I think we can all agree that we
globally have the same vision for our project. So it's fine to say this
is not a feature we want in nextcloud. Lots of them are redundant, so
it's easy to manage ('can you add an option for xxx?')

  - If the feature really make sense, we remove the '0. Needs triage'
and add `1. to develop` label
  - If we need more info, same as bugs, we add the 'needs info' label
and ping the author or other devs for input
  - If the request clearly does NOT register itself into our product,
it's safe to say that the request is quite low and that we think it does
not fit here.
  - If the request is interesting, but most likely not going to happen
by one of us as this is a very low priority, don't hesitate to mention
it.


Thanks a lot everyone for the help!
See you soon! 

Barth

**Comment by skjnldsv** [comment]
I'm going to also add that I've been sorting old issues a lot lately!
Pinging old ones if needed or adding back the 0.needs triage on unknown status.

https://github.com/nextcloud/server/issues?q=-label%3A%220.+Needs+triage%22+-label%3A%221.+to+develop%22+-label%3A%222.+developing%22+-label%3A%223.+to+review%22+sort%3Aupdated-desc+label%3Abug+is%3Aopen

**Comment by go2sh** [comment]
@skjnldsv I can understand the intentions of @kesselb. I saw a lot of issues with valid bugs, which are now closed by the stale bot. The only thing missing was a propper triage, which often can't be performed by the reporter and I think this is not good.

**Comment by skjnldsv** [comment]
@go2sh oh yes, I totally get this as well :)
I thought about killing it as well!

Okay, let's turn it off for now, and figure how to get the onlylabel working.
I guess we can still ping people manually! :hugs:

**Comment by skjnldsv** [comment]
Disabled!

**Pull request closed without merging**
