### PR TITLE
More meaningfull message when a public authenticated share's password is wrong or has expired.

### LINKED ISSUE #31952: [Bug]: UX issues when requesting share by mail password
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

At step 5 the user is more likely to quickly click the "Request password" button instead of the little arrow to submit the current one.

After step 7, an extra click is needed to go back.

### Steps to reproduce

1. Share a folder by mail
2. Set a password for that share
3. Log out
4. Open the link from the email
5. Quickly enter the known password and click the submit button: here I often click the **big** button instead of the arrow out of reflex
6. Click on "Request password"
7. Enter email address and submit
8. Be frustrated to have to click "Back"

### Expected behavior

At step 5, find a way to make the "Request password" button less visible. Or maybe allow the user to first enter a wrong password and only then show the button ? @jancborchardt thoughts ?

At step 7, as soon as the email is set, redirect back to the password field and show a message there "The password was sent by email". This way the user can copy paste and directly enter instead of having to go back.

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - oauth2: 1.12.0
  - photos: 1.6.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - calendar
  - contacts
  - deck
  - email_template_example-0.0.1
  - encryption
  - files_3d
  - files_accesscontrol
  - files_antivirus
  - files_automatedtagging
  - files_downloadlimit
  - files_retention
  - files_texteditor
  - files_versions_s3
  - groupfolders
  - guests
  - mail
  - music
  - officeonline
  - password_policy: 1.14.0
  - previewgenerator
  - ransomware_protection
  - registration
  - richdocuments
  - shareimporter
  - sharepermissions
  - spreed
  - support: 1.7.0
  - suspicious_login
  - terms_of_service
  - testing
  - twofactor_totp
  - user_ldap
  - user_migration
  - user_saml
  - workflow_script
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

master is df14579173708b380f75a6f5680748e37fdbc419

### PR DESCRIPTION
**Pull request by StCyr**
Fixes #31952

Signed-off-by: Cyrille Bollu <cyrpub@bollu.be>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: thanks!

**Review by nimishavijay — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]

**Comment by StCyr** [comment]
No idea why drone fails

**Comment by danxuliu** [comment]
The locators are already separated, the one that fails is in [PublicShareContext.php](https://github.com/nextcloud/server/blob/8951f069fef6916bd293d278c2491b82bc349fc1/tests/acceptance/features/bootstrap/PublicShareContext.php#L51), not in _LoginPageContext.php_ :-)

Using specific messages should be fine if they are stable enough, although I would also favour relaying instead on CSS classes and things like that. However, in this case the text needs to be used because the other elements are not specific enough; the message just has a `warning` class, so removing the text would make the locator a bit brittle.

Having said that, rather than adjusting the text in the locator I think it would be OK to add an explicit class to the message (like `wrong-password` or something like that) and use it instead of the text in the locator.

**Comment by StCyr** [comment]
I think I did good @PVince81 ;-)

**Comment by PVince81** [comment]
let's move on. thanks a lot @StCyr and @danxuliu !

**Pull request merged**
