### PR TITLE
Only match http(s) URLs for references

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/vue-richtext/issues/790

### CODE REVIEW

**Comment by szaimen** [comment]
image

**Review by szaimen — APPROVED** [review]
🐘

**Review by skjnldsv — APPROVED** [review]

**Comment by blizzz** [comment]
master is still 26

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
JSunit would need some adjustments for comments to not match nextcloud.com anymore

1) should parse URLs only
     OCP.Comments tests
     Expected 'nextcloud.com' to equal '<a class="external" target="_blank" rel="noopener noreferrer" href="https://nextcloud.com/">nextcloud.com</a>'.
    at core/js/tests/specs/public/commentsSpec.js:48:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (core/js/tests/specs/public/commentsSpec.js:46:18)
     Expected 'hi nextcloud.com' to equal 'hi <a class="external" target="_blank" rel="noopener noreferrer" href="https://nextcloud.com/">nextcloud.com</a>'.
    at core/js/tests/specs/public/commentsSpec.js:48:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (core/js/tests/specs/public/commentsSpec.js:46:18)
     Expected 'nextcloud.com foobar' to equal '<a class="external" target="_blank" rel="noopener noreferrer" href="https://nextcloud.com/">nextcloud.com</a> foobar'.
    at core/js/tests/specs/public/commentsSpec.js:48:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (core/js/tests/specs/public/commentsSpec.js:46:18)
     Expected 'hi nextcloud.com foobar' to equal 'hi <a class="external" target="_blank" rel="noopener noreferrer" href="https://nextcloud.com/">nextcloud.com</a> foobar'.
    at core/js/tests/specs/public/commentsSpec.js:48:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (core/js/tests/specs/public/commentsSpec.js:46:18)
     Expected 'hi help.nextcloud.com/category/topic foobar' to equal 'hi <a class="external" target="_blank" rel="noopener noreferrer" href="https://help.nextcloud.com/category/topic">help.nextcloud.com/category/topic</a> foobar'.
    at core/js/tests/specs/public/commentsSpec.js:48:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (core/js/tests/specs/public/commentsSpec.js:46:18)

**Comment by nickvergessen** [comment]
Fixed

**Pull request merged**
