### PR TITLE
fix background id selector for the first run wizard

### PR DESCRIPTION
**Pull request by schiessle**
a small but important character got lost during the last rebase before https://github.com/nextcloud/server/pull/620 was merged.

@LukasReschke @jancborchardt @MorrisJobke  please test and review

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by jancborchardt** [comment]
Very nice, works perfectly now! :+1:

**Comment by schiessle** [comment]
stable10: https://github.com/nextcloud/server/pull/639

**Pull request merged**
