### PR TITLE
Do not show shares of disabled users

### PR DESCRIPTION
**Pull request by rullzer**
If a user is disabled their shares should be disabled as well.
This makes sure that if the owner of a share is disabled nobody receives
those shares anymore.

The sharer can be disabled as it is not their data that is shared.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by nickvergessen** [comment]
This means it will resync once the account is enabled again 🙈

**Comment by rullzer** [comment]
> This means it will resync once the account is enabled again 🙈

Yeah. But so be it I guess... Or should we make it a config.php thing?

**Comment by MorrisJobke** [comment]
> This means it will resync once the account is enabled again 🙈

Can't we make it "temporarily unavailable" like with external storages? Then the name is at least blocked and it does not cause sync issues.

**Comment by rullzer** [comment]
> > This means it will resync once the account is enabled again see_no_evil
> 
> Can't we make it "temporarily unavailable" like with external storages? Then the name is at least blocked and it does not cause sync issues.

Ah right i guess we can make it a failed storage....

**Comment by rullzer** [comment]
> > > This means it will resync once the account is enabled again see_no_evil
> > 
> > 
> > Can't we make it "temporarily unavailable" like with external storages? Then the name is at least blocked and it does not cause sync issues.
> 
> Ah right i guess we can make it a failed storage....

@icewind1991 could you check that?

**Comment by blizzz** [comment]
closing for inactivity, also discussion was not finished here.

**Pull request closed without merging**
