### PR TITLE
Fix reshare with circle

### PR DESCRIPTION
**Pull request by tcoupin**
See https://github.com/nextcloud/circles/issues/346

Reshare with circle does not work. This PR fix this.

### CODE REVIEW

**Comment by tcoupin** [comment]
This PR is very important for my work installation since we use "circle quota" (technical account who shares root with circles of local admin, with reshare permission). Today, local admin can not share a folder shared by the technical account. It's very blocking...

**Review by ArtificialOwl — APPROVED** [review]
looks good

**Review by gary-kim — APPROVED** [review]
Oh my! The CI tests actually all passed for once! This should not be something unusual...

**Review by ChristophWurst — APPROVED** [review]

**Comment by tcoupin** [comment]
Will this PR be released in version 17.x ?

**Pull request merged**
