### PR TITLE
PSR-4 for the Theming app

### LINKED ISSUE #433: Remove static util from theming app
static is bad, should use DI instead.

Introduced with https://github.com/nextcloud/server/pull/412

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Based on #405 
- [x] Waiting for #415 

Fix #433

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by schiessle** [comment]
:+1:

**Comment by schiessle** [comment]
@nickvergessen merge conflicts... please rebase

**Comment by nickvergessen** [comment]
No, will wait for #415 and then also fix #433

**Comment by nickvergessen** [comment]
Rebased, now also fixes #433 and does not use private API anymore.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by schiessle** [comment]
please let's wait a second until https://github.com/nextcloud/server/pull/636 is merged... Rebasing this branch is way easier than the other way arround.

**Comment by MorrisJobke** [comment]
@schiessle Could you resolve the conflicts now? #636 is merged

**Comment by schiessle** [comment]
rebased, let's run the test once more and then merge it

**Comment by schiessle** [comment]
@nickvergessen can you take care of the stable10 backport? Thanks!

**Pull request merged**
