### PR TITLE
Fix width of input on contacts menu

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
* Part of https://github.com/nextcloud/server/issues/36965

## Summary

Fix width of input on contacts menu.

🏚️ Before | 🏡 After
---|---
image | Screenshot from 2023-10-11 16-34-08

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — CHANGES_REQUESTED** [review]
Should this wait for https://github.com/nextcloud/server/pull/40749?

**Comment by szaimen** [comment]
> > Should this wait for #40749?
> 
> #40749 doesn't fix a width. I think there is no reason to wait

Reason would be not to get into merge conflicts with  #40749?

**Review by ShGKme — APPROVED** [review]

**Comment by ShGKme** [comment]
> Reason would be not to get into merge conflicts with #40749?

This is just a 1 line of unnecessary CSS change. IMO, we can merge this change as it is and port it to the mentioned PR

**Review by szaimen — APPROVED** [review]
Good to go now but conflicts

**Review by Pytal — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]
Tested after the vue migration

**Comment by JuliaKirschenheuter** [comment]
failed acceptance-header unrelated

**Pull request merged**
