### PR TITLE
Bump @nextcloud/vue, @nextcloud/l10n and @nextcloud/calendar-availability

### PR DESCRIPTION
**Pull request by Pytal**
https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.4.0
https://github.com/nextcloud/nextcloud-l10n/releases/tag/v2.0.0
https://github.com/nextcloud/calendar-availability-vue/releases/tag/v0.5.0-rc2

### CODE REVIEW

**Comment by Pytal** [comment]
`npm ci` fails currently due to the version requirement of `@nextcloud/calendar-availability-vue`
```jsonc
"@nextcloud/vue": "^6.0.0-0 || ^7.0.0-0 || ^7.1.0-0",
```

Bumping to `@nextcloud/calendar-availability-vue@0.5.0-rc1` which changes the requirement to
```jsonc
"@nextcloud/vue": "^6.0 || ^7.0",
```
still fails as it doesn't allow prereleases

Not sure if it's worth changing it to
```jsonc
"@nextcloud/vue": "^6.0 || ^7.0 || ^7.4.0-0",
```
or if we can just go ahead and release 7.4.0 final @skjnldsv?

**Comment by skjnldsv** [comment]
> or if we can just go ahead and release 7.4.0 final @skjnldsv?

If nothing else is needed, I'm up for final release :)

**Review by skjnldsv — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by skjnldsv** [comment]
Fixed calendar availability snapshot tests...

**Comment by Pytal** [comment]
Fixes needed for `stable25` as well

**Comment by Pytal** [comment]
> The backport to stable25 failed. Please do this backport manually.

Superseded by https://github.com/nextcloud/server/pull/36322

**Pull request merged**
