### PR TITLE
upload new files in objectstore to a .part path first 

### PR DESCRIPTION
**Pull request by icewind1991**
This prevent the object store and cache from getting out of sync
when an objectstore silently fails or the php process get's killed
during the upload without giving us the chance to cleanup

### CODE REVIEW

**Comment by rullzer** [comment]
So why only for new files? ANd not in general?

**Comment by MorrisJobke** [comment]
@icewind1991 🏓

**Comment by icewind1991** [comment]
>So why only for new files? ANd not in general?

For existing files we can't do this because we use fileid as object name and object stores generally don't support renaming objects.
Thus we can upload the new file as a different object and "move it into place" after successful upload.

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Pull request merged**
