### PR TITLE
Fix theming autoloader magic

### LINKED ISSUE #1032: Theming admin settings doesn't show set values
The theming app admin settings doesn't show set values.

**Steps to reproduce:**
1. Set a new name/slogan/..
2. Wait for it to be saved
3. Reload the admin page
4. Changes are not shown

This bug was introduced by https://github.com/nextcloud/server/pull/1006, as the Admin settings will get an OC_Defaults instance instead of ThemingDefaults even when the app is already enabled.

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #1032

Basically to agressive composer caching kills us here.

CC: @juliushaertl @blizzz @nickvergessen @LukasReschke 

This also needs to go into stable10 else theming is basically broken.

### CODE REVIEW

**Comment by blizzz** [comment]
a bit magical, but works and best we can do short term :+1: thanks @rullzer

**Comment by blizzz** [comment]
@juliushaertl can you verify?

**Comment by juliushaertl** [comment]
yes, works fine here :+1:

**Comment by LukasReschke** [comment]
🙈 👍

**Pull request merged**
