### PR TITLE
WIP: Allow admins to select installed app version

### LINKED ISSUE #31564: Install specific app version via admin panel
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Some app releases come with regressions. After installing the latest release I cannot roll back to the previous version using the admin panel. With managed instances I also do not have a CLI to bypass the admin panel.

**Describe the solution you'd like**
I can select the app version that I would like to install in the app admin panel.

### PR DESCRIPTION
**Pull request by max65482**
This PR allows admins to select the version of apps via web UI. Currently, only the latest version can be installed. This is especially painful when new app versions come with regressions. With this change, admins can roll back to any previous version without using CLI (esp. relevant for managed instances).

grafik

Current implementation status:
:x: cleanly implemented
:x: nicely designed
:heavy_check_mark: sketches the concept

If there is interest, I can follow up. Otherwise, feel free to close it.

Closes #31564

### CODE REVIEW

**Comment by szaimen** [comment]
Yes, this is indeed useful! Thanks for tackling this! :)

**Comment by szaimen** [comment]
cc @jancborchardt @nimishavijay

**Comment by jancborchardt** [comment]
Is this something we want in general @AndyScherzinger @karlitschek?

If we do, then it certainly shouldn't need its own tab. It would be fine as a simple 3-dot action menu next to the install button (or version number) with the versions as the entries.

**Comment by max65482** [comment]
> @max65482 what are the regressions you are referring to?

[#4033](https://github.com/nextcloud/calendar/issues/4033) in calendar.

**Comment by szaimen** [comment]
@karlitschek I agree. Having a way to install a beta release from the apps Managment page would be really great and is not possible, yet, if I remember correctly? 
@max65482 would that be something you'd be interesting working on? This would make testing of beta releases much easier for everyone and would probably increase the beta release testing coverage by a lot.

**Comment by max65482** [comment]
After installing a beta release, the user should always be able to install the latest stable, right? So, this could be either a downgrade (no stable version of the beta) or an upgrade (stable has been released).

**Comment by szaimen** [comment]
> After installing a beta release, the user should always be able to install the latest stable, right? So, this could be either a downgrade (no stable version of the beta) or an upgrade (stable has been released).

yes

**Comment by szaimen** [comment]
> > @max65482 would that be something you'd be interesting working on, instead?
> 
> Sure. However, I will need support with UI design and (possibly) the implementation.

Great, thank you! lets ping @jancborchardt and @nimishavijay for that :)

**Comment by AndyScherzinger** [comment]
I agree with @karlitschek and @jancborchardt also thinking about database changes coming with a new version which might break running older versions on it is just impossible to manage and design for. Which is why for mobile apps (just as an example) there is only one way which is up.

So like Frank said, we should rather look into QA, enable use of betas. While for betas it is the same pattern, one-way. To get out of the beta release you need to upgrade, no support for downgrades.

**Comment by max65482** [comment]
Let's continue in #31611.

**Pull request closed without merging**
