### PR TITLE
Fix : Hides hidden files and folder in modal (beginning with a dot)

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

## Summary

**Fixes the mentioned problem in this modal (IMO this is a problem) :** 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]
Works, but a bit of a hack, no?
What would a solution in js look like?

**Comment by Jerome-Herbinet** [comment]
> Works, but a bit of a hack, no? What would a solution in js look like?

@artonge, I have no skill on JS, so I don't know what could be the solution.

**Comment by artonge** [comment]
I dug a little, and looks like [a condition already exist](https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/core/src/OC/dialogs.js#L1174-L1179), but it is wrong in my opinion.

https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/core/src/OC/dialogs.js#L1174-L1179
The code is searching for `#showHiddenFiles`, but no component with this id is created for the settings page. [It is only created for files.](https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/apps/files/templates/index.php#L35) The code then default to showing hidden files, which is unexpected, it should be the opposite.

Replacing the code by the following works. @Jerome-Herbinet can you handle that? I don't think I can push to your branch.

```js
		const showHiddenInput = document.getElementById('showHiddenFiles')
		if (showHiddenInput?.value !== "1") {
			files = files.filter(function (file) {
				return !file.name.startsWith('.')
			})
		}
```

Commit: https://github.com/nextcloud/server/commit/1fa58be1aa78ff6216b7a129925a7bb270ac9fe1

**Comment by Jerome-Herbinet** [comment]
> I dug a little, and looks like [a condition already exist](https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/core/src/OC/dialogs.js#L1174-L1179), but it is wrong in my opinion.
> 
> https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/core/src/OC/dialogs.js#L1174-L1179
> 
> The code is searching for `#showHiddenFiles`, but no component with this id is created for the settings page. [It is only created for files.](https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/apps/files/templates/index.php#L35) The code then default to showing hidden files, which is unexpected, it should be the opposite.
> 
> Replacing the code by the following works. @Jerome-Herbinet can you handle that? I don't think I can push to your branch.
> 
> ```js
> 		const showHiddenInput = document.getElementById('showHiddenFiles')
> 		if (showHiddenInput?.value !== "1") {
> 			files = files.filter(function (file) {
> 				return !file.name.startsWith('.')
> 			})
> 		}
> ```
> 
> Commit: [1fa58be](https://github.com/nextcloud/server/commit/1fa58be1aa78ff6216b7a129925a7bb270ac9fe1)

Done @artonge :-)

**Comment by Jerome-Herbinet** [comment]
> 



> > I dug a little, and looks like [a condition already exist](https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/core/src/OC/dialogs.js#L1174-L1179), but it is wrong in my opinion.
> > https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/core/src/OC/dialogs.js#L1174-L1179
> > 
> > The code is searching for `#showHiddenFiles`, but no component with this id is created for the settings page. [It is only created for files.](https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/apps/files/templates/index.php#L35) The code then default to showing hidden files, which is unexpected, it should be the opposite.
> > Replacing the code by the following works. @Jerome-Herbinet can you handle that? I don't think I can push to your branch.
> > ```js
> > 		const showHiddenInput = document.getElementById('showHiddenFiles')
> > 		if (showHiddenInput?.value !== "1") {
> > 			files = files.filter(function (file) {
> > 				return !file.name.startsWith('.')
> > 			})
> > 		}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Commit: [1fa58be](https://github.com/nextcloud/server/commit/1fa58be1aa78ff6216b7a129925a7bb270ac9fe1)
> 
> Done @artonge :-)

Can you test on your side @artonge ?

**Comment by artonge** [comment]
Can you remove the original change? It should not be needed anymore

**Comment by Jerome-Herbinet** [comment]
> Can you remove the original change? It should not be needed anymore

Done + npm run sass @artonge

**Comment by artonge** [comment]
Perfect :ok_hand: 
CI is complaining about the compiled files, your local `node_modules` might need an update with `npm ci`, then compile again.

**Comment by Jerome-Herbinet** [comment]
> Perfect ok_hand CI is complaining about the compiled files, your local `node_modules` might need an update with `npm ci`, then compile again.

Done

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
