### PR TITLE
Add seperator in high contrast mode

### PR DESCRIPTION
**Pull request by CarlSchwan**
Between navigation and content and between entry in breadcrump

image

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Lgtm but didnt test

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — CHANGES_REQUESTED** [review]
To specific imho, this is not the place to add such rules :thinking:

**Comment by CarlSchwan** [comment]
> To specific imho, this is not the place to add such rules thinking

what is the place then? There is unfortunately no easy way to add css code that will only be used when a theme is used :(

**Comment by skjnldsv** [comment]
> what is the place then? There is unfortunately no easy way to add css code that will only be used when a theme is used :(

Fair enough, I'll optimize this for 26 :)

**Review by skjnldsv — APPROVED** [review]

**Review by YasinAshorian — APPROVED** [review]

**Comment by Pytal** [comment]
stable25 backport https://github.com/nextcloud/server/pull/34546

**Pull request merged**
