### PR TITLE
Fix apps list issues caused by redesign

### LINKED ISSUE #33861: icons in the apps overview are not visible in dark mode
See 
image

### LINKED ISSUE #33926: [Bug]: NC 25 App Stores Icons not showing up properly in dark mode
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

image

### Steps to reproduce

1. Set theme to dark mode
2. open app store

### Expected behavior

Should show up white not black

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_videoplayer: 1.14.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - officeonline: 1.1.3
  - password_policy: 1.15.0
  - photos: 1.7.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0-beta.2
  - survey_client: 1.13.0
  - suspicious_login: 4.2.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.6.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.4.0
  - circles: 23.1.1
  - encryption
  - files_downloadactivity: 1.13.0
  - groupfolders: 12.0.1
  - impersonate: 1.11.0
  - notify_push: 0.4.0
  - socialsharing_email: 2.5.0
  - support: 1.8.0
  - twofactor_admin: 3.2.0
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by CarlSchwan**
- Make icons work on dark theme
- Use new buttons (a18y ++)
- Fix some eslint warnings
 
image

image

Fix #33926
Close https://github.com/nextcloud/server/issues/33861

### CODE REVIEW

**Comment by skjnldsv** [comment]
Not convinced by the choices of colours
I would do:
- Enable = primary
- Enable untested = secondary
- Remove = error

@jancborchardt ?

**Review by skjnldsv — APPROVED** [review]
Other than the comment, good :+1:

**Comment by CarlSchwan** [comment]
> Not convinced by the choices of colours I would do:
> 
>     * Enable = primary
> 
>     * Enable untested = secondary
> 
>     * Remove = error
> 
> 
> @jancborchardt ?

Fine by me, I'll change that 👍

**Comment by jancborchardt** [comment]
@skjnldsv good point, I would even go with just text-only for "Remove". Otherwise we have red buttons all over.

**Comment by CarlSchwan** [comment]
New screenshot with the suggestions from Jan and 'John'

 image

**Review by nimishavijay — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Looks much much nicer and less scary, great work! :)

**Review by szaimen — APPROVED** [review]
Nice!

**Pull request merged**
