### PR TITLE
Fix CI failures when building settings app

### LINKED ISSUE #28201: Settings app build output hashes cause CI failures
When building the settings app, hashes are included in the filenames which cause CI failures as the build action / npmbuildbot does not remove the old hashed files.

Related https://github.com/skjnldsv/npmbuildbot/issues/174

### PR DESCRIPTION
**Pull request by Pytal**
Closes #28201 

May or may not be feasible, please take into account some additonal context in the PR introducing chunkhash here https://github.com/nextcloud/server/pull/22395

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by MichaIng** [comment]
I haven't really noticed that its the settings app only, but indeed. Could then make https://github.com/skjnldsv/npmbuildbot/issues/174 obsolete, although there may be other reasons for renamed files.

As John approved, I guess #21024 would not appear again? Looks like the existence of an old `nextcloud/settings` dir was at least part of the issue.

**Comment by skjnldsv** [comment]
> As John approved, I guess #21024 would not appear again?

Seems like it works now yep :thinking: 
Webpack changed a lot in between :crossed_fingers:

**Review by MichaIng — APPROVED** [review]

**Comment by Pytal** [comment]
CI is going haywire atm 💀, for the node workflow errors I believe the `ubuntu-latest` images were updated recently and as such no longer include python2 which node-gyp depends on as seen in the logs, resolutions welcome :)

**Comment by skjnldsv** [comment]
> Also saw that we're using self-hosted runners `skjnldsv-runner-o87nbcrcbnm40cv059kebobmk` and `skjnldsv-runner-mvh6njed8c0viktutgaz1nk13`

It was testing to go faster but it doesn't seems to work :(

**Comment by skjnldsv** [comment]
> EDIT: oh wow, it seems to work now

I deactivated them because of https://github.com/actions/runner/issues/406

**Review by juliusknorr — APPROVED** [review]

**Comment by MichaIng** [comment]
The self-hosted runners seems to have issues to pick up queries actions. I recognised it starting yesterday, you can see it now when filtering actions by status "queried", there are lots stalled up to three hours. Yesterday I manually cancelled all of them (the obviously stalled ones), to see whether, once clean, this solves the issue.

**Comment by Pytal** [comment]
Manual backports:

stable22 https://github.com/nextcloud/server/pull/28274
stable21 https://github.com/nextcloud/server/pull/28275
stable20 sometime :)

**Comment by Pytal** [comment]
Backports:

stable22 https://github.com/nextcloud/server/pull/28274
stable21 https://github.com/nextcloud/server/pull/28275
stable20 sometime :)

**Comment by skjnldsv** [comment]
Hum, i'm not sure about backporting though :thinking: 
What do you think @juliushaertl ? Safe enough?

**Comment by juliushaertl** [comment]
Would be fine for me since we use that chunkName pattern in lots of other places without issues, though I'd wait for the next round of maintennace releases as we are in rc already.

**Pull request merged**
