### PR TITLE
Fix app overflow menu on bright color theme

### LINKED ISSUE #35760: [Bug]: Wrong colour of menu icons with a small screen (smartphone)
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 25.0.2: Menu icons have wrong colors (light instead of dark) on a small screen (smartphone)

20221213_081841_defaced

### Steps to reproduce

See Picture

### Expected behavior

Icons are visible

### Installation method

Community Web installer on a VPS or web space

### Operating system

None

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Nextcloud themes
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #35760

## Summary
The background color of the popover on bright color themes is also bright, so icons (which are white) need to be inverted.
Additionally the overflow menu toggle, if active, should be visible. Currently the toggle is fixed to primary text color which might be white which collides on bright color themes as the background of the button is also a bright color.

## Screenshots

before | after
---|---
Screenshot_20230503_150443|Screenshot_20230503_150058

Maybe you find the screen recordings helpful to see what I have changed:\
**Before**

https://user-images.githubusercontent.com/1855448/235926936-8cf08d45-9183-4935-a1d2-d9b73d90e64f.mp4

**After**

https://user-images.githubusercontent.com/1855448/235926972-a8bf6bde-fd42-4c3a-ae65-9dce0f38d31f.mp4

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Screenshots before/after for front-end changes
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
There was a change on the coloring behaviour in the vue library recently I think. Can you check if the lib update is already in server and if not make sure it's not breaking there again?

**Comment by susnux** [comment]
> There was a change on the coloring behaviour in the vue library recently I think. Can you check if the lib update is already in server and if not make sure it's not breaking there again?

@nickvergessen 
Server is currently using 7.10 (works as my screen recordings are from current `master` branch). The 7.11 release is currently not published on NPM and as such not used by server, but I tested it locally and it works too.

**Review by Pytal — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
