### PR TITLE
Merge pull request #43589 from nextcloud/feat/reminder-status

### LINKED ISSUE #42611: security.txt should end with a newline
https://github.com/nextcloud/server/blob/9416778ed2e21e961d1a0c5222f718c545138671/apps/settings/lib/WellKnown/SecurityTxtHandler.php#L45

Or at least, according to sectxt: https://github.com/DigitalTrustCenter/sectxt/blob/27d8524ca215d4663539a218e048023da07172f8/sectxt/__init__.py#L308-L315

The grammar in the official standard seems to indicate the same: https://www.rfc-editor.org/rfc/rfc9116#name-file-format-description-and

### PR DESCRIPTION
**Pull request by lovelgeorge99**
security.txt should end with a newline #42611

* Resolves: #42611

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

BEFORE IMAGE
image

AFTER IMAGE
image

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hey!
Thanks for the PR, but I think you messed up your commit :thinking:

**Comment by lovelgeorge99** [comment]
> Hey! Thanks for the PR, but I think you messed up your commit 🤔

yes i was trying to sign off but did something wrong..i am new to contribution. can you help me to fix it

**Comment by skjnldsv** [comment]
Yes, you need to recreate the branch from master and create a new commit with the changes you were trying t do. Do not amend the previous commit (which I think is what you did here) :)

**Comment by lovelgeorge99** [comment]
> Yes, you need to recreate the branch from master and create a new commit with the changes you were trying t do. Do not amend the previous commit (which I think is what you did here) :)

ok ..can u delete this commit that I made or I have to do it?

**Comment by Pytal** [comment]
You may close this PR and open a new one with the desired change @lovelgeorge99 :)

**Comment by joshtrichards** [comment]
You want to give this change another attempt, @lovelgeorge99, or shall I do it so we can close the associated open issue out? :-)

**Pull request closed without merging**
