### PR TITLE
fix(systemtags): Correctly load tagged files in "tags"-files-view

### PR DESCRIPTION
**Pull request by susnux**
* Regression of https://github.com/nextcloud/server/pull/46921

When splitting the path it is `/{ID}` to the splitted array is `['', '{ID}']` -> we need to use the last part otherwise we only get 404.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
We need tests for this :see_no_evil:

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Merged to have it in Beta5 but created a follow-up at #47127 to have an issue for implementing tests

**Comment by susnux** [comment]
> We need tests for this 🙈

I am already writing some, but this was more urgent :sweat_smile:

**Pull request merged**
