### PR TITLE
LGTM: no self approval

### PR DESCRIPTION
**Pull request by MariusBluem**
According to https://github.com/nextcloud/android/pull/13 

cc @LukasReschke @tobiasKaminsky

### CODE REVIEW

**Comment by blizzz** [comment]
LGTM

**Comment by LukasReschke** [comment]
LGTM

**Comment by tobiasKaminsky** [comment]
:+1: does this help, as I am not a maintainer of this repo ;)

**Comment by LukasReschke** [comment]
> 👍 does this help, as I am not a maintainer of this repo ;)

It does. We don't have any Maintainer file and thus it falls back to https://github.com/orgs/nextcloud/teams/maintainers :)

**Pull request merged**
