### PR TITLE
Remove the need for CSRF check on ocs::getCurrentUser

### LINKED ISSUE #5694: Remove (additional) CSRF check from public endpoints if a Bearer authentication header is present (OAuth 2)
OCS APIs cannot be used in a straightforward way if OAuth-authenticated clients perform requests, due to CSRF checks. If a Bearer authentication header is present, it should be sufficient to assume that no CSRF attack takes place. As discussed below in this thread, it would be great if additional CSRF checks were disabled if requests are authenticated by a bearer token.

(Edited on 2017-08-07, 2:53 pm) -- Original Text:

> If you add Nextcloud as an OAuth 2 service provider to a Moodle (3.3) installation, Moodle's OAuth API queries a `userinfo_endpoint` in order to obtain information about the authorising Nextcloud user. This fails since such an endpoint does not exist. Although actually from the OpenID spec, such an endpoint is useful to find out who was just logged in. It is also useful to check whether an access token is still valid without actually performing an operation on files. :)
> 
> Specs for the userinfo endpoint: https://openid.net/specs/openid-connect-core-1_0.html#UserInfo (general) and https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse (response).
> 
> Elements of the response can be: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims, of which `sub` is a MUST (identifier of a Nextcloud user; what do you suggest? ID or username?). Moodle currently relies on a username and an email being present in the userinfo response. I already found out that you do not necessarily know an email adress, so I reported this there: https://tracker.moodle.org/browse/MDL-59511. I would suggest that you add an email address if it is known, instead of mocking one.

### PR DESCRIPTION
**Pull request by pierreozoux**
Fixes #5694

I tested on my server, and worked like a charm :)

I think in term of security it is fine to open this route. What do you think?

### CODE REVIEW

**Comment by rullzer** [comment]
Well yes this fixes it but it removes the CSRF protection... also it is not a generic approach we basically need to fix the middleware to not check for CSRF if the bearer auth is set much like the OCS-APIREQUEST header

**Comment by MorrisJobke** [comment]
The proper fix seems to be #7873 - @pierreozoux could you check if this works for you?

**Comment by rullzer** [comment]
Yes lets do it in #7873

**Comment by Dagefoerde** [comment]
`@NoCSRFRequired` would be fine here, though, wouldn't it? After all, that endpoint is purely informational and does not cause side effects. 
Nevertheless, for #5694 this fix wouldn't be sufficient. #7873, as a more general approach, looks more suited to me. (Haven't gotten around to testing that one against Moodle, yet, though. It's on my agenda.)

**Comment by rullzer** [comment]
@Dagefoerde well yes. However I'm not a fan of multiple hacks to fix the same issue ;) Also since it is not enough for #5694 fixing it properly and making sure if you chose to extend NC support in moodle with other endpoints this just works makes more sense imo :). 

Looking forward to your review of #7873, THNX :)

**Comment by Dagefoerde** [comment]
> not a fan of multiple hacks to fix the same issue
I agree, me neither ☺. My point is rather that this PR fixes an entirely different issue. It is just labeled as fixing the same one. 

Regardless, for my (and Moodle's) needs the fix of #7873 is exactly the way to go, so thanks (again) for that, @rullzer.

In the present PR the real issue is that the `@NoCSRFRequired` is redundant here (in my opinion) and therefore might harm understanding of what `@NoCSRFRequired` is good for. But since functionality is unharmed it's at your discretion whether you incorporate this fix as well, or maybe even look for other instances of unneeded annotations.

**Comment by rullzer** [comment]
The CSRF protection is on by default. You have to add the annotation to disable it ;). So there is no @CSRFrequired annotation.

**Comment by Dagefoerde** [comment]
A right, it was the other way round. Sorry for that. So I have to revise: You could consider adding the `@NoCSRFRequired` here because it makes sense. But, as I said, it's not exactly necessary because everything works regardless.

**Pull request closed without merging**
