### PR TITLE
Inputs.scss rewritting and optimisation

### PR DESCRIPTION
**Pull request by skjnldsv**
See #3121 

cc @nextcloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Go to personal page:

* [ ] activity checkboxes are odd:
bildschirmfoto 2017-01-20 um 22 52 09
* [ ] eye button for password input field is not within the input field anymore:
bildschirmfoto 2017-01-20 um 22 52 51
* [ ] quota bar has a hovered state (but shouldn't):
bildschirmfoto 2017-01-20 um 22 53 26


Files app:

* [ ] bottom shadow of the "switch to gallery" button on the right looks odd:
bildschirmfoto 2017-01-20 um 22 53 56

**Comment by skjnldsv** [comment]
Okay, I decided to go with the svg background for the checkmark and the mixed one. Colors are still defined with css, it's easier for everyone, let's not complicate things too much! :)

**Comment by skjnldsv** [comment]
@MorrisJobke Updated!
The gallery button is to be fixed on the gallery app :)

**Comment by MorrisJobke** [comment]
* [ ] download button on public link page looks out of place
bildschirmfoto 2017-01-21 um 16 59 17

* [ ] login page looks a broken:
bildschirmfoto 2017-01-21 um 17 00 56

* [ ] password protected link page:
bildschirmfoto 2017-01-21 um 17 02 01

* [ ] LDAP wizard: buttons look a bit too big compared to input (maybe okay)
* [ ] LDAP wizard: copy button icon looks a bit too big:
bildschirmfoto 2017-01-21 um 17 04 02


Sorry @skjnldsv for not finding those things earlier.

**Comment by skjnldsv** [comment]
@MorrisJobke Don't be sorry! :D 
Good work takes time and thoroughness!

**Comment by skjnldsv** [comment]
@MorrisJobke ldap will be fixed in #2529 when I will be done with scss (we're close :D )

Everything else have been fixed.
More reviews? ❤️

**Review by LukasReschke — APPROVED** [review]
Works in Chrome and Safari here. 👍 🚀

**Review by MorrisJobke — APPROVED** [review]
Tested again and works here fine 👍  (even in IE11)

**Pull request merged**
