### PR TITLE
feat(files): add uploader

### LINKED ISSUE #30069: [F2V] Upload manager
This ticket is part of the [files to vue migration](https://github.com/nextcloud/server/issues/28063)

### Goal
Have a dedicated upload managemnt module that can be invoked in multiple areas

### QA
- [x] Independent source code
- [x] Can be invoked without Files (standalone)
- [ ] Can be invoked externally (e.g dropping from the Files app to a folder)
- [ ] Can be invoked with external auth (e.g used for public upload)
- [x] Support direct upload
- [x] Support chunk upload

#### First step
- [ ] API: `OCA.Files.Uploader`
- [x] Dedicated service running in the background
  - [x] Can add files/folder
  - [x] Can retrieve the current summary of background service
  - [x] Summary shall contain the following: Files/Folder count, size, remaining time.
- [x] Files UI shall contain the progress bar with a cancel button following this design:
    image
    First line files/folder count, second line: total size + remaining time
    Location of this UI remains unchanged: after the breadcrumbs
  - How shall we handle that ?
    - Does  `OCA.Files.Uploader` provides a way to inject the component in the page directly?
    - Does it stays a service-api only and Files implements the display of the raw summary data?
    - Do we provide both to allow other apps to interact with the service on the page?

#### Second step (not 24)
- [x] Have a dedicated UI showing each files/folders opening when clicking the summary (like onedrive)
- [ ] Only show folder if uploading multiple files, show file if uploading individually 
- [ ] Being able to cancel each file or folder being uploaded

#### Optional TBD
- [x] :question: Pause/resume uploads (https://github.com/nextcloud/server/issues/673)
- [ ] :question: Support bulk upload 
- [x] :question: Provides upload methods so it can be invoked without UI

### Design
@nimishavijay @jancborchardt

### LINKED ISSUE #38041: Set new folder name inline like renaming
ref #28645

### PR DESCRIPTION
**Pull request by skjnldsv**
Ref https://github.com/nextcloud/server/issues/39914
Closes #30069
Closes #38041

- [x] Needs https://github.com/nextcloud-libraries/nextcloud-upload/pull/912
- [x] Needs https://github.com/nextcloud-libraries/nextcloud-files/pull/731

## Screenshots
image
image
image
image

### Followups:
- Ignore this blank space, this is from the components
  image
- Add more `new XXXXXXX` items
- Implement template picker

### CODE REVIEW

**Comment by szaimen** [comment]
One small remark: the new button looks like this  image since https://github.com/nextcloud/server/pull/39884. can we do the same here?

**Comment by szaimen** [comment]
Also the progress bar does not seem to work well on mobile currently

**Comment by skjnldsv** [comment]
> One small remark: the new button looks like [this](https://user-images.githubusercontent.com/42591237/260985728-4f91f152-8ef4-491e-bc40-bf29fad1474b.png) since #39884. can we do the same here?

https://github.com/nextcloud-libraries/nextcloud-upload/issues/922

> Also the progress bar does not seem to work well on mobile currently

Not scheduled for now
https://github.com/nextcloud-libraries/nextcloud-upload/issues/816

**Review by juliusknorr — APPROVED** [review]
Works like charm 👍

**Review by szaimen — APPROVED** [review]
Did a fast test and seems to work good :)

**Comment by szaimen** [comment]
🎉🎉🎉

**Pull request merged**
