### PR TITLE
Revert minimum length for tags

### PR DESCRIPTION
**Pull request by kesselb**
Revert https://github.com/nextcloud/server/commit/e1d9b0bae20510526b0d00c2afe464945847face from https://github.com/nextcloud/server/pull/34096

Joas:

> Need to have a submit button then, 3 characters is too long for some languages
> (where even names can be a single character)
> It' fine to not automatically search, but it needs to be submitable. 
> Similar like the normal unified search etc

Community:

> The reason would be that nothing is displayed so you have to click and type three characters (four actions) 
> with no option to one click on a tag (as before).
> It feels like a regression for tag users.  Example, a small tag user only needs to see a limited number of tags.  
> Or, you are simply re-using the same tag over and over. 

https://help.nextcloud.com/t/collaborative-tags-no-longer-visible-in-25-until-user-inputs-3-characters/147647

### CODE REVIEW

**Comment by szaimen** [comment]
Conflicts

**Comment by TheNomad11** [comment]
Is this issue still on your todo list or do you prefer to leave it like it is? 

In my case, I have lots of tags with only two letters (for documents relating to language level A1, A2, B1 and B2), so now my whole organisation of files is no longer usable. Furthermore, I don't remember all the other tags that I have used, and there is no way to see previously used tags. The tagging system could be such a powerful tool in Nextcloud, now with version 25 it is totally broken. So at least I hope that you consider reverting the minimum length of tags. Thanks a lot!

**Comment by szaimen** [comment]
@kesselb ? :)

**Comment by kesselb** [comment]
Hey, rebased the branch and recompiled the assets.

**Review by szaimen — APPROVED** [review]
🐘

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
