### PR TITLE
[13] Remove base url from global cache prefix

### PR DESCRIPTION
**Pull request by juliusknorr**
backport of #8716

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
CI failure :/

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Fix CI failure.

**Comment by MorrisJobke** [comment]
Still one failure:

```
There was 1 failure:
57s
177

57s
178
1) Test\Template\SCSSCacherTest::testResetCache
57s
179
Expectation failed for method name is equal to <string:clear> when invoked 1 time(s).
57s
180
Method was expected to be called 1 times, actually called 0 times.
```

Let me look into it.

**Comment by juliushaertl** [comment]
Thanks for fixing the tests @rullzer @MorrisJobke :+1:

**Pull request merged**
