### PR TITLE
Use same lightness calculation as the SCSS compiler for theming

### PR DESCRIPTION
**Pull request by juliusknorr**
Fix for https://github.com/nextcloud/server/issues/4776#issuecomment-319015016

cc @nickvergessen @nextcloud/theming 

Signed-off-by: Julius Härtl <jus@bitgrid.net>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Works, now the notifications app icon is also white 👍

**Review by skjnldsv — APPROVED** [review]
Very good!!! Good work!

**Review by LukasReschke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@juliushaertl What about the backport to stable12 🏓 😉

**Comment by juliushaertl** [comment]
backport at https://github.com/nextcloud/server/pull/5977

**Pull request merged**
