### PR TITLE
fix change permission on mail shares of folders

### PR DESCRIPTION
**Pull request by blizzz**
1. Create a mail share on a folder
2. Change "can edit"

As found in https://github.com/nextcloud/server/pull/2398#issuecomment-265129906

Please test and review @schiessle @rullzer @ChristophWurst

### CODE REVIEW

**Comment by schiessle** [comment]
button works again but the permissions for "can edit" are wrong, they should be 15 (create, read, update, delete)

**Comment by blizzz** [comment]
@schiessle please check again. Could there be any corner cases were we should not set it to 15?

**Comment by rullzer** [comment]
Yes for files. Files dont' get DELETE or CREATE permissions

**Comment by blizzz** [comment]
@schiessle @rullzer should be settled now I hope.

**Comment by schiessle** [comment]
works great! 👍

**Comment by skjnldsv** [comment]
👍

**Comment by rullzer** [comment]
Why do we do this? Any reason why we don't have the regual checkboxes for mail shares as well (create/update/delete?) ???

**Comment by schiessle** [comment]
> Why do we do this? Any reason why we don't have the regual checkboxes for mail shares as well (create/update/delete?) ???

Because at the end it is a link share and the public link view can't really distinguish between this permissions. So we chose to use the same permissions we have for public links (either 1 or 15), at least for now.

**Comment by schiessle** [comment]
@blizzz js unit tests fail, can you have a look? Thanks!

**Comment by blizzz** [comment]
👀

**Comment by blizzz** [comment]
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not a function (evaluating 'this.data.state()')
  at apps/files/js/file-upload.js:157
PhantomJS 2.1.1 (Linux 0.0.0): Executed 835 of 837 (skipped 2) ERROR (18.498 secs / 17.433 secs)
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not a function (evaluating 'this.data.state()')
at apps/files/js/file-upload.js:157
```

how is that related? the output is as useful as a matchstick in the ocean.

**Comment by schiessle** [comment]
> how is that related? the output is as useful as a matchstick in the ocean.

good question. I also can't reproduce it locally. Maybe just a rebase and let Drone try it once more? 😉

**Comment by blizzz** [comment]
I restarted the tests, but it fails on the same place.

**Comment by blizzz** [comment]
And no related changes in master since.

**Comment by blizzz** [comment]
On another this test succeeds, so it has something to do with the changes, somewhow. A stacktrace could be helpful, but somehow the suite does not print it out? 

I get the same error. autotest-js.sh is your friend. Investigating.

**Comment by blizzz** [comment]
> I get the same error. Investigating.

… some fruitless attempts to get the stack trace later tests succeed without further changes. 🏴

```
 PhantomJS 2.1.1 (Linux 0.0.0): Executed 835 of 837 (skipped 2) SUCCESS (25.776 secs / 24.039 secs)
root@jessica:/drone/src/github.com/nextcloud/server# git status
HEAD detached at FETCH_HEAD
nothing to commit, working directory clean
root@jessica:/drone/src/github.com/nextcloud/server# git log
commit b9bc708ffad5e940a09aaef4de922bf252913047
Author: blizzz <blizzz@arthur-schiwon.de>
Date:   Tue Dec 6 16:10:06 2016 +0000

    Merge c2062a93a3eb57c01609a89775c8551b92cc9013 into 0b0f27358f67382f4c45f469db50de8f17f72bce
```

Cannot restart from the  UI anymore. So, merging master again.

**Comment by blizzz** [comment]
Test succeeded now without actual changes 🃏 waiting for the rest and then 🚢

**Comment by blizzz** [comment]
LGTM not working somehow, but approvals from @schiessle  and @skjnldsv (https://github.com/nextcloud/server/pull/2530#issuecomment-265176616 && https://github.com/nextcloud/server/pull/2530#issuecomment-265179350) thus merging.

**Pull request merged**
