### PR TITLE
Fix gap by filter svg and empty search message overflow

### PR DESCRIPTION
**Pull request by eppfel**
The svg with the filter definition was using space, fixed with float.

With the change to flexbox the display:none of the .hidden class was overwritten.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
How can I reproduce the old behaviour?

**Review by MorrisJobke — APPROVED** [review]
Found the difference. It's a small gap at the top. With this fix the content is more on the top.

👍

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Please do it with css in css files, not in the templates.
:)

**Comment by eppfel** [comment]
Please review again!

Anyone knows what's with the codecov/patch check?

**Comment by skjnldsv** [comment]
I added a class just to be more specific and clear :)

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> Anyone knows what's with the codecov/patch check?

it's there to check for the change in code coverage compared to what was there before. So it fails everytime the coverage is less than before 🙈

**Pull request merged**
