### PR TITLE
only allow a single concurrent dav write to a file

### PR DESCRIPTION
**Pull request by icewind1991**
While concurrent writes wont lead to file corruption it's a waste of bandwith and multiple chunked upload assemblies can lead to the server running out of space

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 Could you explain a bit more the use case and scenario here?

**Comment by icewind1991** [comment]
Something was causing a sync client to have send multiple requests to do chunk assembly for a 100gb file at the same time.
The different part files were filling up the disk, causing the assemblies to fail and the whole thing to start over.

With this we can be sure that only one assembly can run at the same time

**Comment by rullzer** [comment]
So you just lock some specific file (which doesn't exist at that point) right? Just to prevent multiple trying to do it at the same time right?

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@icewind1991 @rullzer Should we backport this to stable13?

**Comment by rullzer** [comment]
Probably!

**Pull request merged**
