### PR TITLE
fix(preview): don't create folder structure when previews are disabled

### LINKED ISSUE #45697: [Bug]: Disabling the preview does not stop the creation of the folder tree
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am encountering an issue: my NextCloud instance is installed on an ext4 partition with limited inode resources. The preview feature generates a very large number of folders that consume all available inodes and block the entire system. Despite disabling the preview feature in the configuration file, this folder tree continues to be created empty. Could you please fix the problem quickly?

For more information:
https://help.nextcloud.com/t/the-preview-feature-consumes-too-many-inodes/194129

### Steps to reproduce

1. `sudo -u www-data php /var/www/nextcloud/occ files:scan-app-data`
2. `df -i /dev/sda1`
3. `systemctl stop apache2`
4. `rm -rf /var/www/nextcloud/data/appdata_xxx/preview/*`
5. `sudo -u www-data php /var/www/nextcloud/occ files:scan-app-data`
6. `df -i /dev/sda1`
7. `systemctl start apache2`

### Expected behavior

Disabling the preview feature stops the creation of all files and folders, not just files.

### Installation method

None

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: #45697 

## Summary

Don't create the folder structure for previews when previews are disabled. 

## TODO

- [ ] CI
- [ ] Review

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
Tested and works.

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
works :)

**Comment by SystemKeeper** [comment]
Failing tests should be fixed with https://github.com/nextcloud/server/pull/45883

**Comment by st3iny** [comment]
Do we want to backport this?

**Pull request merged**
