### PR TITLE
[stable12] Backport appmenu fixes

### PR DESCRIPTION
**Pull request by juliusknorr**
backport of #5135 and #5191 

cc @nextcloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
Let’s not backport these for now because of the feedback https://github.com/nextcloud/server/pull/5191#issuecomment-305772805

After some longer-term testing I would say it’s better like it was before, with not that many icons filling up the top bar. Just because we do have the space doesn’t mean we should fill everything up. That’s a lot of visual noise. :)

cc @karlitschek

**Review by jancborchardt — CHANGES_REQUESTED** [review]
See comment

**Comment by karlitschek** [comment]
I agree with @jancborchardt . We could show a few more apps then we do today if everyone wants that. But definitely not the full title bar. Maybe 2-4 more than today? Or x% of the space in the title bar? But let's please keep some space empty.

**Comment by Luticus** [comment]
Why not make it configurable?  Just put a configuration in the admin page so admins can set the site default and then one in user preferences so users can override it.

As it is now the app menu bugs me because it just chooses a few random apps and pins them, but everything else is in overflow.  It would make more sense and I would worry less about the number of apps shown if we could pin our favourite apps to the app bar and everything else goes in overflow.  I think that would be a great "ultimate goal".  Then the number of apps and the order is set by how many pins, and then by available space.  If there's no space then the last pins that get pushed to overflow should be pinned to the top of the overflow.  I do like how the last icon (before the overflow) gets switched to the active app if it's an overflow app though.  Again though, admins should choose the default and users should be able to override with their preferences.

Those are my thoughts on it anyway.

**Comment by jancborchardt** [comment]
@Luticus we are discussing a configurable app order at https://github.com/nextcloud/server/issues/4917 :)

**Comment by juliushaertl** [comment]
Let's wait with this as well for #5244

**Pull request closed without merging**
