### PR TITLE
fix(deleteAction): Bump up delete requests concurrency to 5

### PR DESCRIPTION
**Pull request by nfebe**
A concurrency of who is not efficient. Low throughput, underutilization, high latency etc...

### CODE REVIEW

**Review by SystemKeeper — APPROVED** [review]
Thank you!

**Comment by SystemKeeper** [comment]
Since the original was also included in 27.1, can we backport to stable27 as well?

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
> Since the original was also included in 27.1, can we backport to stable27 as well?

I think you need to align on this with @blizzz  or @Altahrim ?

**Comment by SystemKeeper** [comment]
/backport 08323ee8344fc147511c428cfcc91efd5a64eeb8 to stable28

**Comment by blizzz** [comment]
/backport 08323ee8344fc147511c428cfcc91efd5a64eeb8 to stable29

**Pull request merged**
