### PR TITLE
Fix flow

### PR DESCRIPTION
**Pull request by mario**
Fixing issues found in https://github.com/nextcloud/server/pull/6879 + solved conflicts.

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by blizzz** [comment]
@LukasReschke

**Comment by LukasReschke** [comment]
Tests seem to be failing.

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Tests seem to be failing.

**Review by LukasReschke — APPROVED** [review]
🐘

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
