### PR TITLE
Update notifications ++

### PR DESCRIPTION
**Pull request by nickvergessen**
Preparing the apps could base before starting to merge "Can I update?" into the app.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Will do more stuff in seperate PRs so its not growing infinite?

**Comment by rullzer** [comment]
CI is not happy

**Comment by nickvergessen** [comment]
Fixed CI

**Review by rullzer — APPROVED** [review]
:rocket:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
