### PR TITLE
Split link share provider

### PR DESCRIPTION
**Pull request by rullzer**
To make the sharing more modular and the providers simpler.

Lets see what our CI says.

@schiessle as discussed.

### CODE REVIEW

**Comment by rullzer** [comment]
Whee! Lets get this in so I can continue cleaning this all up

CC: @schiessle @nickvergessen @MorrisJobke @icewind1991 @LukasReschke

**Comment by MorrisJobke** [comment]
Ummm ... that's a lot ... I will test this tomorrow

**Comment by rullzer** [comment]
Looks like a lot. It is actually just splitting ;)

**Comment by rullzer** [comment]
Setting back to to develop since I need to rethink the parent thingy.
We might need to add it to the general providers since all shares can have parents. For example if I reshare (internally) an incomming federated share.

**Comment by rullzer** [comment]
Ah no that is not the case. Because we don't store incomming federates shares the same way. 

@schiessle are you on board with only adding the getParent call to link shares?

**Comment by rullzer** [comment]
Ok I'm going to do this slightly different. Lets close this.

**Pull request closed without merging**
