### PR TITLE
Bring back the description for app passwords

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up to #5166

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
LGTM! thanks for taking over! :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MariusBluem** [comment]
Please backport.

**Comment by nickvergessen** [comment]
It's already in the PR of the initial backport which caused this regression:
https://github.com/nextcloud/server/issues/5266

**Comment by jancborchardt** [comment]
Nice, thanks! :)

**Pull request merged**
