### PR TITLE
Fix installing on Oracle

### PR DESCRIPTION
**Pull request by nickvergessen**
Empty strings are stored as null in Oracle,
so a column with NotNull can not have an empty string as default

Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
I will write a method into the oracle checker to error on this.

**Review by ChristophWurst — APPROVED** [review]
:see_no_evil:

**Comment by nickvergessen** [comment]
Pushed an addition to the checker.

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
