### PR TITLE
added method needsPartFile() in Storage

### PR DESCRIPTION
**Pull request by viniciuscb**
Added the method needsPartFile in Storage, as expected in the TODO.

I need this method because I am creating a files_external storage that does not support part file.

### CODE REVIEW

**Comment by nickvergessen** [comment]
@viniciuscb thanks for your PR, can you please also sign your commit?
https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

Thanks in advance!

**Comment by nickvergessen** [comment]
👍 fine by me, but depends on icewind.

**Review by icewind1991 — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
Fine by me. And since our filesystem overload says it is OK...

**Comment by rullzer** [comment]
@viniciuscb in order to merge your work we need you to sign-off on your commit.

1. Checkout your branch
2. git commit --amend -s
3. git push -f

That should do it.

**Comment by viniciuscb** [comment]
Signed!!!

**Pull request merged**
