### PR TITLE
avatar generation - disable setimageformat

### LINKED ISSUE #34755: [Bug]: Single letter avatars in Nextcloud 24 have become all white icons in Nextcloud 25 on Alpine Linux with imagemagick installed
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Before updating to Nextcloud 25, some of my cloud users had letter avatars (e.g. an A on a colorful background if the name was Abcde). Now all avatars have this white image (512x512):
avatar 512

I have:
- checked that I have a correct installation of `imagemagick` (I'm using [this Dockerfile](https://github.com/nextcloud/docker/blob/de77074a55a7d181276de5cddf9fbdb5b9e56f3e/.examples/dockerfiles/full/fpm-alpine/Dockerfilee))
- run `occ preview:reset-rendered-texts` (this command was introduced with [this commit](https://github.com/nextcloud/server/commit/9f96a47125c47ec6c5695fc263d86dadea62aabe), but is there any opposite command to regenerate the avatars?), `occ preview:generate-all`, `occ preview:pre-generate`, and `occ preview:repair`
- run `occ files:scan --all`, `occ files:scan-app-data`, `occ files:repair-tree`

### Steps to reproduce

1. update Nextcloud 24 to Nextcloud 25 (my journey: https://github.com/nextcloud/server/issues/34679)
2. wait a few hours
3. text avatars are gone
4. try steps above

### Expected behavior

The text avatars are shown correctly.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "mail_smtpmode": "sendmail",
        "remember_login_cookie_lifetime": "7200",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": "false",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": ***REMOVED SENSITIVE VALUE***
        },
        "logtimezone": "Europe\/Rome",
        "htaccess.RewriteBase": "\/",
        "enable_previews": true,
        "enabledPreviewProviders": {
            "11": "OC\\Preview\\PNG",
            "12": "OC\\Preview\\JPEG",
            "13": "OC\\Preview\\GIF",
            "14": "OC\\Preview\\BMP",
            "15": "OC\\Preview\\MarkDown",
            "16": "OC\\Preview\\MP3",
            "17": "OC\\Preview\\TXT",
            "18": "OC\\Preview\\Movie"
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "maintenance": false,
        "app_install_overwrite": [
            "drawio",
            "end_to_end_encryption",
            "files_external_dropbox",
            "unsplash",
            "groupfolders",
            "onlyoffice",
            "twofactor_webauthn",
            "breezedark",
            "deck",
            "fulltextsearch"
        ],
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "default_phone_region": "IT",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "version": "25.0.0.18",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - breezedark: 24.0.2
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - forms: 3.0.0
  - fulltextsearch: 24.0.0
  - groupfolders: 13.0.0
  - integration_dropbox: 1.0.5
  - integration_github: 1.0.12
  - integration_google: 1.0.8
  - integration_reddit: 1.0.5
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 0.2.1
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.6
  - password_policy: 1.15.0
  - photos: 2.0.0
  - previewgenerator: 5.1.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - spreed: 15.0.0
  - support: 1.8.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - unsplash: 2.0.1
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings
  - deck: 1.8.0
  - drawio: 1.0.3
  - encryption
  - external: 5.0.0
  - extract: 1.3.5
  - federation: 1.11.0
  - files_external_dropbox: 1.4.3
  - files_fulltextsearch: 24.0.1
  - firstrunwizard: 2.13.0
  - fulltextsearch_elasticsearch: 24.0.1
  - issuetemplate: 0.7.0
  - mail: 2.0.3
  - metadata: 0.16.0
  - news: 18.3.0
  - podcast: 0.3.1
  - sharebymail: 1.12.0
  - survey_client: 1.12.0
  - suspicious_login
  - twofactor_webauthn: 1.0.0
  - user_ldap
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [related_resources] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

### Nextcloud Logs

_No response_

### Additional info

The white text avatar is downloaded from Nextcloud Talk iOS and Nextcloud Talk web independently. I can also check the avatar picture by going to https://my.cloud.tld/index.php/avatar/<username>/96.

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/34755

See https://github.com/nextcloud/server/issues/34755#issuecomment-1365863711 and https://github.com/nextcloud/server/issues/34755#issuecomment-1365947532 for context

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by juliushaertl** [comment]
This actually causes segfaults on cypress tests when creating a new user in text. https://github.com/nextcloud/text/pull/3610#issuecomment-1366449973

@szaimen Do you have any further technical insights on why the png conversion failed? The segfault is also weird, but more elaboration on this fix would be good. Is the Imagick format now kept as svg? In that case OC_Image further down https://github.com/nextcloud/server/blob/a0f21800feccb601f562c14b7fc9ce3654da6aed/lib/private/Avatar/Avatar.php#L141 would receive an svg which GD cannot handle. So maybe this just hides the issue and uses the fallback from https://github.com/nextcloud/server/blob/f98ae2b5b0567f28a875106724c0475d6395f3c5/lib/private/Avatar/UserAvatar.php#L245 ?

**Comment by juliushaertl** [comment]
I actually also have the segfault on my dev instance. It happens when trying to get the image data from imagick using `(string)$avatar` without setting a format. Would vote to revert this and rather try to check for the reason why the generation fails originally.

**Comment by juliushaertl** [comment]
@szaimen Since you could reproduce the original issue can you maybe try if the following patch works instead of this one?

```diff
diff --git a/lib/private/Avatar/Avatar.php b/lib/private/Avatar/Avatar.php
index 791cb8b2e7f..fcec7f2dd27 100644
--- a/lib/private/Avatar/Avatar.php
+++ b/lib/private/Avatar/Avatar.php
@@ -126,7 +126,7 @@ abstract class Avatar implements IAvatar {
         * Generate png avatar from svg with Imagick
         */
        protected function generateAvatarFromSvg(int $size, bool $darkTheme): ?string {
-               if (!extension_loaded('imagick')) {
+               if (!extension_loaded('imagick') || count(\Imagick::queryFormats('SVG')) === 0) {
                        return null;
                }
                try {
```

**Comment by szaimen** [comment]
> Since you could reproduce the original issue can you maybe try if the following patch works instead of this one?
> 
> ```diff
> diff --git a/lib/private/Avatar/Avatar.php b/lib/private/Avatar/Avatar.php
> index 791cb8b2e7f..fcec7f2dd27 100644
> --- a/lib/private/Avatar/Avatar.php
> +++ b/lib/private/Avatar/Avatar.php
> @@ -126,7 +126,7 @@ abstract class Avatar implements IAvatar {
>          * Generate png avatar from svg with Imagick
>          */
>         protected function generateAvatarFromSvg(int $size, bool $darkTheme): ?string {
> -               if (!extension_loaded('imagick')) {
> +               if (!extension_loaded('imagick') || count(\Imagick::queryFormats('SVG')) === 0) {
>                         return null;
>                 }
>                 try {
> ```

I tried it but it doesnt work. This is the output: 
image

So maybe it is indeed a font problem? However I don't understand why...

**Comment by szaimen** [comment]
I think I might have found the relying issue.

**Comment by szaimen** [comment]
It might be indeed an AIO issue: https://github.com/nextcloud/all-in-one/pull/1624

**Pull request merged**
