### PR TITLE
[stable23] Hide shares by disabled users

### PR DESCRIPTION
**Pull request by come-nc**
Manual backport of https://github.com/nextcloud/server/pull/39699

### CODE REVIEW

**Comment by blizzz** [comment]
what is the outlook here?

**Review by Altahrim — APPROVED** [review]

**Comment by blizzz** [comment]
@come-nc do we still need it?

**Comment by come-nc** [comment]
> @come-nc do we still need it?

Yes, can I force merge? I believe freeze is over?

**Review by blizzz — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
#39699

**Pull request merged**
