### PR TITLE
Fixing issues with themed icons

### PR DESCRIPTION
**Pull request by juliusknorr**
This PR fixes some minor issues with the themed icons:

- Increase border radius to make it visible in the favicons
Before/After:
2016-12-04-131515_202x28_scrot

- Fix transparency when using homescreen shortcuts on android
screenshot_20161204-131414

please review @nextcloud/designers @nextcloud/theming

### CODE REVIEW

**Comment by skjnldsv** [comment]
👍 YES

**Comment by eppfel** [comment]
:+1:

**Comment by jancborchardt** [comment]
:heart:ing our design team! :)

**Comment by jancborchardt** [comment]
By the way @juliushaertl @skjnldsv @eppfel @nextcloud/designers we have some job openings, including frontend dev: https://nextcloud.com/jobs/ - would be cool to work with you :)

**Pull request merged**
