### PR TITLE
Bump doctrine

### PR DESCRIPTION
**Pull request by rullzer**
Requires: https://github.com/nextcloud/3rdparty/pull/18
With test fixes from https://github.com/owncloud/core/pull/26085

CC: @nickvergessen @MorrisJobke @LukasReschke @icewind1991

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks good and works as before 👍

**Comment by nickvergessen** [comment]
👍

**Comment by rullzer** [comment]
seem mysql is not happy. I'll have a look tomorrow

**Comment by nickvergessen** [comment]
```
1) Test\DB\ConnectionTest::testSetValuesOverWrite
570s
98
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_table` (`integerfield`, `textfield`) VALUES(?, ?)' with params [1, "bar"]:
570s
100
SQLSTATE[HY000]: General error: 1364 Field 'clobfield' doesn't have a default value
```

So this is a BC breaking minor update... great 🎉 
Tables that need adjustments:
* **appconfig:** https://github.com/nextcloud/server/blob/master/db_structure.xml#L37-L41
* **preferences:** https://github.com/nextcloud/server/blob/master/db_structure.xml#L669-L673
* **credentials:** https://github.com/nextcloud/server/blob/master/db_structure.xml#L1946-L1950
* **dav:** https://github.com/nextcloud/server/blob/06e969cb74aacc3d6490d3207a625cc712941968/apps/dav/appinfo/database.xml#L359-L362
* **user_ldap:** https://github.com/nextcloud/server/blob/fe8bae31dc80ac832323fa8d9a75fd4b543d36e0/apps/user_ldap/appinfo/database.xml#L128-L132
* ... I stop here

I guess we need to fix the schema reader and hack it in. We can't break all these apps on 5.6 + mysql (I guess this is the greatest part of instances)

**Comment by rullzer** [comment]
Mmm I must say I'm surprised this even worked before. But the big question is why did it work before and not anymore.

**Comment by rullzer** [comment]
Ok so it fails now because of: https://github.com/nextcloud/3rdparty/pull/18/files#diff-f1134e2d70bff8e3d0e698f41c3a652bL111

Which is a line added by @MorrisJobke in https://github.com/doctrine/dbal/commit/e73ef8bd5ed631d12417800b0bfd097340ae3aee

But has no trace in the 2.5 branch aparently anymore.

**Comment by rullzer** [comment]
Pushed 3rdparty patch lets see

**Comment by rullzer** [comment]
Whee mysql is happy.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Upps .. 3rdparty needs to be updated to current master -> @rullzer could you update this?

**Pull request merged**
