### PR TITLE
fix(files): Implement `SortingService` to fix sorting of files

### LINKED ISSUE #42826: [Bug]: File sorting based on numbers (with points ) changed in NC 28
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

File sorting based on numbers with points ( YYYY.MM.DD ) has changed in 28.0.1. No problem is 27.1.5
For example, with 3 folders named 2023.01.08, 2023.04.09, 2023.10.12, if I to do descending sort order or ascending, 2023.01.08 will be in the middle, not at the beginning or the end.
If you replace points with hyphens (2023-01-08, 2023-04-09, 2023-10-12), 2023-01-08 will be at beginning or at the end.

### Steps to reproduce

1.Create 3 folder named  2023.01.08, 2023.04.09, 2023.10.12
2.Clich on file sort by name
3.

### Expected behavior

NOK : Descending sort order or ascending, 2023.01.08 will be in the middle, not at the beginning or the end.
OK  : Replace points with hyphens (2023-01-08, 2023-04-09, 2023-10-12), 2023-01-08 will be at beginning or at the end.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.XXX.XXX",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/XXX.XXX.XXX.fr\/nextcloud",
        "overwritehost": "XXX.XXX.XXX.fr",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "default_phone_region": "FR",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_sendmailmode": "smtp",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "skeletondirectory": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "user_email_visible": "true"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - groupfolders: 16.0.2
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - systemtags: 1.18.0
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0 (installed 2.4.0)
  - comments: 1.18.0 (installed 1.10.0)
  - contactsinteraction: 1.9.0 (installed 1.1.0)
  - dashboard: 7.8.0 (installed 7.0.0)
  - encryption: 2.16.0
  - files_antivirus: 5.4.0 (installed 5.4.0)
  - files_automatedtagging: 1.18.0 (installed 1.18.0)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.20.0
  - files_retention: 1.16.0 (installed 1.16.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - files_trackdownloads: 1.11.0 (installed 1.11.0)
  - firstrunwizard: 2.17.0 (installed 2.9.0)
  - nextcloud_announcements: 1.17.0 (installed 1.9.0)
  - photos: 2.4.0 (installed 1.1.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - sharelisting: 1.2.0 (installed 1.2.0)
  - side_menu: 3.11.2 (installed 3.11.2)
  - support: 1.11.0 (installed 1.3.0)
  - survey_client: 1.16.0 (installed 1.8.0)
  - suspicious_login: 6.0.0
  - text: 3.9.1 (installed 3.1.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1 (installed 1.0.1)
  - weather_status: 1.8.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/42826
* Resolves: Ticket#9661489

## Summary
The previously used library was parsing strings to try to detect dates, but for filenames it makes no sense to parse them as dates.
Overall the library is parsing a lot of stuff we do not need, so instead of a 3rd party library we can use the native browser solution and use `Intl.Collator`.

### Screenshots
before | after
---|---
Screenshot 2024-05-21 at 14-54-02 Files - Nextcloud|Screenshot 2024-05-21 at 14-53-41 Files - Nextcloud

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — COMMENTED** [review]
Having this in the `@nextcloud/files` would be helpful :see_no_evil:

**Comment by susnux** [comment]
@skjnldsv what of this? The `orderBy` function? Not really files related more a generic sorting function.
And the whole files sorting is very implementation related, meaning we need to know the current view, the user settings etc.

The only place I know where this could be reused would be the file picker. Or do you have something other in mind?

**Comment by skjnldsv** [comment]
> Or do you have something other in mind?

Viewer

**Comment by susnux** [comment]
But do we want to backport the files library update then on stable28 and stable29? If not we need to merge this for stable branches.

**Comment by skjnldsv** [comment]
> But do we want to backport the files library update then on stable28 and stable29? If not we need to merge this for stable branches.

Fair point!! Let's migrate this after backports to the lib ?

**Review by skjnldsv — APPROVED** [review]

**Comment by susnux** [comment]
> Let's migrate this after backports to the lib ?

Yes sounds good!

**Review by szaimen — APPROVED** [review]
🐘

**Pull request merged**
