### PR TITLE
Bump @nextcloud/vue to 7.1.0

### PR DESCRIPTION
**Pull request by Pytal**
https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.1.0

### CODE REVIEW

**Comment by szaimen** [comment]
Do we need to adjust our multiselects manually or will it work automatically?

**Comment by Pytal** [comment]
This is only for bumping the lib which includes all the other enhancements and bugfixes from 7.1.0 and is not meant to do anything else @szaimen

**Review by skjnldsv — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Comment by szaimen** [comment]
Can somone restart drone?

**Comment by szaimen** [comment]
@Pytal can you rebase? There seem to be some merge conflict with the package-lock.json

**Pull request merged**
