### PR TITLE
rename owncloud to nextcloud in Official apps button popup

### PR DESCRIPTION
**Pull request by Spacefish**
Fixed a typo ;)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Thanks. I will look into how to fix the translations for this one :)

**Comment by MorrisJobke** [comment]
I pushed some fixes for the translations.

**Comment by MorrisJobke** [comment]
👍 from me

**Comment by MorrisJobke** [comment]
cc @LukasReschke @jancborchardt @blizzz @schiessle @karlitschek

**Comment by karlitschek** [comment]
👍 good catch

**Pull request merged**
