### PR TITLE
[stable12] Allow upgrading from OC 10.0.6 & 10.0.7

### LINKED ISSUE #8542: migration from oc 10.0.6.1 to nc 12 fails
I know this version is not yet supported by the migrator but since the 10.0.6 is a small hotfix [https://github.com/owncloud/core/pull/30265](url) i wonder if there is any trick to void the 

> Exception: Updates between multiple major versions and downgrades are unsupported.

thanks

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixed #8542

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Seems to work for people

**Review by rullzer — APPROVED** [review]
uhm fine by me (I didn't test).
But why not have them upgrade to 13?

**Comment by MorrisJobke** [comment]
10 -> 13 is not tested and thus not supported

**Comment by rullzer** [comment]
fair enough

**Pull request merged**
