### PR TITLE
[stable27] Fix alignments for share different share entry types.

### PR DESCRIPTION
**Pull request by nfebe**
Backport commit in https://github.com/nextcloud/server/pull/40389

| Before | Now |
| --------  | ------ |
| Screenshot from 2023-09-14 14-46-42 | Screenshot from 2023-09-14 15-37-15 |

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
@Fenn-CS can we align the other share type on the one with the status, so things don't feel so "squeezed". I can post a example later today.

**Comment by Fenn-CS** [comment]
@AndyScherzinger Do, you mean, there should be more padding left to accommodate the status icons? (When present)

**Comment by AndyScherzinger** [comment]
Like this @Fenn-CS 

268013160-ed588d04-b131-4960-824f-4d77cd07be92

**Comment by Fenn-CS** [comment]
What about this?

Screenshot from 2023-09-14 16-18-47

Basically shifting everything together for more room.

cc: @AndyScherzinger

**Comment by AndyScherzinger** [comment]
I'd say fine for now and something we can further polish and discuss with @nextcloud/designers

**Comment by AndyScherzinger** [comment]
> For more context : All items are now at the point where you drew the red line but unlike you I don't have photoshop :), so look hard :)

I did this with M$ Paint 😆

**Review by AndyScherzinger — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Pull request merged**
