### PR TITLE
feat(core): add selection for recommended apps

### LINKED ISSUE #45084: Check/Uncheck button to install specific recommended app from "/apps/recommended" page
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I just want to install Nextcloud Office from recommended apps but I need to install all of them. I know you can install app from "Apps".  But if we have option to check/uncheck particular apps it would be great 
image

**Describe the solution you'd like**
There should be option to check/uncheck for individual recommended apps

### PR DESCRIPTION
**Pull request by sanskar-soni-9**
* Resolves: #45084

## Summary
Added functionality to selectively install recommended apps

## Before
240611_14h57m50s_screenshot

## After

https://github.com/nextcloud/server/assets/88997516/9202f245-877c-4b0e-bf50-23b6b7dee143

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by sanskar-soni-9** [comment]
I need opinion for this arrow should I remove it?

240611_15h56m45s_screenshot

**Comment by susnux** [comment]
> I need opinion for this arrow should I remove it?

I would say yes.

**Comment by sanskar-soni-9** [comment]
> I need opinion for this arrow should I remove it?

arrow?!, I meant icon 😅, anyways removed!

**Comment by sanskar-soni-9** [comment]
Now looking at the diff I think it can be there can be more solutions for it, like adding another state variable for selected app ids instead of introducing new property in all apps or something similar, in any case pls let me know if any approach is more preferred here

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Very nice! Just some feedback:
- [ ] All apps should be pre-checked to be selected, at least the ones which are compatible (which on a release should be all of them)
- [ ] If none is selected, the buttons below can be disabled rather than hidden to prevent jumping of the interface
- [ ] Checking and unchecking of the box shouldn’t need a spinner, since the installing/downloading is only in the next step? Checking/unchecking should be instant

Nice work @sanskar-soni-9! :)

**Comment by sanskar-soni-9** [comment]
Thanks @jancborchardt, and checking/unchecking is instant I am using checkbox loading state as an indicator that which app is downloading/installing which I think looks better and cleaner, so I removed previous spinner and installed check icon and overloaded checkbox for every state/step:
1) when user will select app to install checkbox will be blue and enabled
2) then when he will click on install button then loading checkbox will indicate which app is currently getting installed
3) and then when app will be installed the checkbox will be disabled and will indicate that the app is installed

I can always bring back previous spinner and check icon if that is needed?

**Comment by sanskar-soni-9** [comment]
Here is the updated UI flow:

https://github.com/nextcloud/server/assets/88997516/e2edccfa-df82-4b94-92f8-a3f06feba557

Current UI shift is due to installing status line which get added when apps are installing
240615_17h17m10s_screenshot

and I still kept loading checkbox because of the previous reason so please let me know your review on this

**Review by jancborchardt — COMMENTED** [review]
Awesome, really nice @sanskar-soni-9, and thanks for the explanation! :)

> Current UI shift is due to installing status line which get added when apps are installing

I would recommend to put this line next to the "Install recommended apps" button, or better yet change the button to "Installing apps …", cause up there the line is not really visible, and then also the layout does not shift. :)

**Comment by sanskar-soni-9** [comment]
@jancborchardt done! 😃

**Review by jancborchardt — APPROVED** [review]
Looks good design-wise now! :) But has to be checked regarding code.

**Review by susnux — APPROVED** [review]
:rocket:

**Comment by susnux** [comment]
Can you rebase onto current master?

**Comment by sanskar-soni-9** [comment]
@susnux done :)

**Comment by sanskar-soni-9** [comment]
Oops I forgot about this and deleted the repo, new PR in progress

**Pull request closed without merging**
