### PR TITLE
Fix occ maintenance:install database connect failure

### LINKED ISSUE #15560: mysql port syntax in config
nextcloud-server：16.0.1

If the mysql server port not default 3306, then your config.php `dbport` not have effect. 
error log show us : refuse to connect mysql server

and the solution, is make the dbhost `ip:port`

like 
```php
    'dbport' => '192.168.1.3:3358',
```

### LINKED ISSUE #18513: [17.0.2] "occ maintenance:install" uses "oc_<admin>" before creating it
### Steps to reproduce
0. Install MariaDB database and any working webserver
1. Download and extract https://download.nextcloud.com/server/releases/nextcloud-17.0.2.tar.bz2 into webserver dirs
2. Run
```
sudo -u www-data php /path/to/nextcloud/occ maintenance:install --no-interaction --database 'mysql' --database-name 'nextcloud' --database-user 'root' --database-pass 'password' --admin-user 'admin' --admin-pass 'password' --data-dir '/path/to/nextcloud_data'
```
3. Watch
> Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user 'oc_admin'@'localhost'

### Expected behaviour
`oc_admin` user should be created before using it for any further actions, install should succeed. This is the case when using previous Nextcloud v17.0.1 on exactly same system + install steps: https://download.nextcloud.com/server/releases/nextcloud-17.0.1.tar.bz2
Hence I'm pretty sure that it related to a change/regression from v17.0.2.

### Actual behaviour
`oc_admin` does not even exist when checking `mysql.user` database table, hence the above error message.
Reference: https://github.com/MichaIng/DietPi/issues/3275

### Server configuration

**Operating system:** Debian Buster

**Web server:** not relevant

**Database:** MariaDB 10.3.18

**PHP version:** 7.3.11

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-17.0.2.tar.bz2

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
root@VM-Buster:~# cat /var/www/nextcloud/config/config.php
<?php
$CONFIG = array (
  'passwordsalt' => 'zGc5ZyTHqxRUX9mhprT69nDuf0hMZ7',
  'secret' => 'rjzCM7W5LZVLfXq7uSS+O/PDGsx9r8YSk8AOyLBzJmU2qLr0',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/path/to/nextcloud_data',
  'dbtype' => 'mysql',
  'version' => '17.0.2.1',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_admin',
  'dbpassword' => 'XlN7PYIyqCKIQZCkThrerBFRwHRUFi',
);
```
- As can be seen, the config.php is created with user + password, but the user does not exist in database.
</details>

**MariaDB log:**
```
2019-12-21 16:26:04 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.3.18-MariaDB-0+deb10u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 10
2019-12-21 16:26:05 39 [Warning] Access denied for user 'oc_admin'@'localhost'
2019-12-21 16:26:05 40 [Warning] Access denied for user 'oc_admin'@'localhost'
root@VM-Buster:~# mysql -e 'select user,host from mysql.user'
+----------+-----------+
| user     | host      |
+----------+-----------+
| allo_db  | localhost |
| ompd     | localhost |
| root     | localhost |
| tmp_root | localhost |
+----------+-----------+
```
But the database itself has been created already:
```
root@VM-Buster:~# ls -l /path/to/mysql/nextcloud/
total 4.0K
-rw-rw---- 1 mysql mysql 60 Dec 21 16:26 db.opt
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #18513
Fix #15560

### CODE REVIEW

**Comment by skjnldsv** [comment]
Those gotta be the best commits I've ever seen :grin: 
image

**Comment by kesselb** [comment]
You probably fixed https://github.com/nextcloud/server/issues/15560 as well.

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Failures unrelated

**Comment by nickvergessen** [comment]
Marking offtopic hides the comments only, or aborts the backport? The commits 1+4 should be backported until. 2+3 could be skipped, as they just make debugging easier as it makes handling of exceptions more explicit, but they don't fix a primary error.

**Comment by skjnldsv** [comment]
> Marking offtopic hides the comments only, or aborts the backport?

only hide :)
This was for visibility :wink:

**Comment by MichaIng** [comment]
Okay this fixes the authentication plugin situation currently, but e.g. requires maintenance when new MySQL version come up or MariaDB switches to a different default authentication method, when a password is supplied that way.

An alternative that would be more future prove:
```
$query = "CREATE USER '$name'@'localhost' IDENTIFIED WITH mysql_native_password;"
$connection->executeUpdate($query);
$query = "ALTER USER '$name'@'localhost' IDENTIFIED BY '$password';"
$connection->executeUpdate($query);
```
- The syntax here is the same with all MySQL and MariaDB versions: https://github.com/nextcloud/server/issues/18513#issuecomment-575847516
- Ah but to be true I am currently not sure if creating the user with plugin works without applying a password in the same query for all MySQL/MariaDB versions.

**Comment by nickvergessen** [comment]
I checked that and it didn't work on mysql 8 and mariadb 10.4 with the same Syntax. Password needs to be hashed manually for mariadb etc. So i think that's the better story for now

**Review by juliusknorr — APPROVED** [review]

**Comment by MichaIng** [comment]
@nickvergessen 
> I checked that and it didn't work on mysql 8 and mariadb 10.4 with the same Syntax. Password needs to be hashed manually for mariadb etc. So i think that's the better story for now

Strange, works perfectly fine here with MariaDB:
```
2020-02-06 23:28:45 root@VM-Buster:~$ mariadb
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 47
Server version: 10.3.18-MariaDB-0+deb10u1 Debian 10

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select user,host,plugin,password from mysql.user;
+------+-----------+-------------+----------+
| user | host      | plugin      | password |
+------+-----------+-------------+----------+
| root | localhost | unix_socket |          |
+------+-----------+-------------+----------+
1 row in set (0.000 sec)

MariaDB [(none)]> create user test@localhost identified with mysql_native_password;
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> select user,host,plugin,password from mysql.user;
+------+-----------+-------------+----------+
| user | host      | plugin      | password |
+------+-----------+-------------+----------+
| root | localhost | unix_socket |          |
| test | localhost |             |          |
+------+-----------+-------------+----------+
2 rows in set (0.000 sec)

MariaDB [(none)]> alter user test@localhost identified by 'test';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> select user,host,plugin,password from mysql.user;
+------+-----------+-------------+-------------------------------------------+
| user | host      | plugin      | password                                  |
+------+-----------+-------------+-------------------------------------------+
| root | localhost | unix_socket |                                           |
| test | localhost |             | *94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29 |
+------+-----------+-------------+-------------------------------------------+
2 rows in set (0.000 sec)
```
Also the docs state clearly that plain test password must be used here: https://mariadb.com/kb/en/alter-user/
Hashed password is possible/required when using:
```
... IDENTIFIED BY PASSWORD 'password_hash'
```
Such a solution would solve the issue with Nextcloud 16 as well: https://github.com/nextcloud/server/pull/19328#discussion_r376099039

Sadly Debian does not ship MariaDB even on Bullseye+Sid and no MySQL, hence I cannot test with these.

**Comment by nickvergessen** [comment]
Well yes it works like that, but that doesn't work with mysql8. And if you specify the plugin it requires the hash in mariadb. Anyway the PR we use now fixes it for all supported dbs... Good enough

**Comment by MichaIng** [comment]
@nickvergessen 
> And if you specify the plugin it requires the hash in mariadb.

That must be either wrong or new in MariaDB 10.4, as with 10.3 it's not true, as of the two different syntax for plain and hashed password, see above.

> but that doesn't work with mysql8

Okay, no chance then. A pain that syntax differs on such basic SQL commands 😢.

**Pull request merged**
