### PR TITLE
Update system tags icon

### PR DESCRIPTION
**Pull request by Bugsbane**
Replaces system tags magnifying glass icon with a newly created tag icon, as per discussion with Jan in issue https://github.com/nextcloud/server/issues/232

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I like it 👍

**Comment by MorrisJobke** [comment]
Could I ask you to optimize the SVG? There is a tool that shrinks the SVG significantly. @jancborchardt knows the name.

**Comment by nickvergessen** [comment]
:+1:

**Comment by Bugsbane** [comment]
Ok, I found the optimization script, installed scour and ran the script over the svg which worked fine. I've uploaded the optimized SVG into my branch and committed. Not sure if I need to create a new pull request or not. It seems to have included my optimized svg commit in my current pull request.

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
No, when you push to your local branch, the PR is also updated, until it is merged, as you can see above.

**Comment by jancborchardt** [comment]
Nice, good stuff!

The tool I use to compress PNG is Trimage. And for SVG scour indeed, but @mikebabb or @skjnldsv I think suggested svgo cause that's better.

**Comment by Bugsbane** [comment]
OK. Thanks @jan! I'll try running Trimage+svgo over these when I have a minute.

**Pull request merged**
