### PR TITLE
add groupOfUniqueNames as valid group object class

### PR DESCRIPTION
**Pull request by icewind1991**
cc @blizzz

### CODE REVIEW

**Comment by icewind1991** [comment]
ping @blizzz

**Comment by LukasReschke** [comment]
@blizzz Can you comment on that? :)

**Comment by MorrisJobke** [comment]
👍 from my side

**Comment by blizzz** [comment]
LGTM

**Comment by blizzz** [comment]
btw, what is the reason behind this PR?

**Comment by icewind1991** [comment]
> btw, what is the reason behind this PR?

Some setups use `groupOfUniquenames` to associate groups, without this pr the ldap wizzard does not see it as a valid group type.

Backport to 10? other people are running into the bug in [the wild](btw, what is the reason behind this PR?) (cc @karlitschek )

**Comment by karlitschek** [comment]
backport is fine with @blizzz agrees 👍

**Pull request merged**
