### PR TITLE
Fix vendor name in PHP version warning

### PR DESCRIPTION
**Pull request by nickvergessen**
Only missing on stable10

@LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by marinofaggiana** [comment]
I would understand if some external API reports Nextcloud or ownCloud ?

**Comment by MorrisJobke** [comment]
> I would understand if some external API reports Nextcloud or ownCloud ?

`/status.php` will report with Nextcloud 11+ the product name:

```json
{"installed":true,"maintenance":false,"version":"9.2.0.3","versionstring":"11.0 alpha","edition":"","productname":"Nextcloud"}
```

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/pull/529

**Pull request merged**
