### PR TITLE
[stable23] Fix accept/reject remote share action

### PR DESCRIPTION
**Pull request by szaimen**
Manual backport of #31910

This is the fix for the described problem in
https://github.com/nextcloud/server/issues/31301

Signed-off-by: MSe1969 <mse1969@posteo.de>
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
The compile command fails :/
image

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
@blizzz merge or wait for the next release?

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
> @blizzz merge or wait for the next release?

in time for the RC :)

**Pull request merged**
