### PR TITLE
fix(files): prevent dragging previews and appear as an external files DnD

### LINKED ISSUE #42751: [Bug]: Moving NC Files using drag&drop
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Until NC 27 I was able to move around files using drag & drop: just select one or more files and drop it in one of the following items:
* any folder in the current view (problem n.1)
* any folder name in the current folder breadcrumb, such as a file in located in HOME-ICON->Documents->Work could easly moved: selected, dragged and dropped on the "Documents" or the "HOME-ICON"  (problem n.2)
 

### Steps to reproduce

for problem n.1:

1. go to any folder
2. select a file located in this folder
3. drag it: the "Drop files there" widget starts blinking, making almost impossible to drop the file since the folder contents rapidly offsets down as the widget appears.

for problem n.2:
1. go to any folder under the home, let's we call it "Documents->Work"
2. select a file located in this folder
3. drag it on the "Documents" label in the breadcrumb (the name highlights)
4. drop it to move there

### Expected behavior

the selected file shall be moved to the doped location, as it worked in NC 27

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.fedibox.com:8080",
            "cloud.fedibox.com:80",
            "cloud.fedibox.com:443"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwritehost": "cloud.fedibox.com",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "overwrite.cli.url": "https:\/\/cloud.fedibox.com\/",
        "installed": true,
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "IT",
        "loglevel": 1,
        "log_rotate_size": 10485760,
        "theme": "",
        "app_install_overwrite": [
            "carnet",
            "fulltextsearch_elasticsearch",
            "workflow_ocr",
            "richdocuments",
            "impersonate",
            "spreed",
            "fulltextsearch",
            "files_fulltextsearch"
        ],
        "has_rebuilt_cache": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - calendar: 4.6.2
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_fulltextsearch: 28.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - fulltextsearch: 28.0.0
  - fulltextsearch_elasticsearch: 28.0.0
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflow_ocr: 1.28.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0 (installed 2.3.0)
  - dashboard: 7.8.0 (installed 7.2.0)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.2.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
nextcloud        | 127.0.0.1 - - [13/Jan/2024:07:26:44 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.57 (Debian) PHP/8.2.14 (internal dummy connection)"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:26:50 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:27:17 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 931 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:27:21 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:27:51 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:28:19 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 931 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:28:22 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:28:52 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:29:19 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 931 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:29:22 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:29:53 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:30:17 +0000] "PUT /ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json HTTP/1.1" 204 688 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:30:20 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:30:23 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:30:54 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:31:21 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:31:25 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:31:55 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:32:16 +0000] "GET /csrftoken HTTP/1.1" 200 894 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:32:22 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:32:26 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:32:56 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:33:23 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:33:27 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:33:57 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:34:23 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:34:28 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:34:58 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:35:13 +0000] "GET /index.php/settings/integrity/failed HTTP/1.1" 200 808 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:35:14 +0000] "GET /index.php/apps/files/preview-service-worker.js HTTP/1.1" 200 6698 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/42751

If you drag the preview, the event will carry the image as File data.
This fixes that issue. Now every `FileEntry` drag will appear as internal and NOT show the Drop area

## Before:
https://github.com/nextcloud/server/assets/14975046/b5a1010d-c94c-4d7a-b484-949578a9bb5e

### CODE REVIEW

**Review by artonge — COMMENTED** [review]
That almost looks like a feature !

Isn't the fix a bit hacky? Is this method really made for those use cases?
Can we use that instead? https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

**Comment by skjnldsv** [comment]
> Isn't the fix a bit hacky ?
> Can we use that instead? [developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable)

I think it's actually the cleanest approach. We want to clear all data if the drag comes from an internal file. If I add the `draggable` to the img, there's no guarantee the issue won't come back in a few months after we discover another element that also carry a file when dragged (an action, maybe even the shared status user's avatar :thinking:)

Cleanest is to only carry the dragging event imho :)

**Review by artonge — APPROVED** [review]
Ok, I think I get the fix now, it makes sense :).

**Comment by pierre-alain-b** [comment]
Hello all, thank you for the fix. I see this is marked for NC 29. As this is disturbing the use of NC 28, wouldn't it be wise to push it for the next maintenance release of NC28 ?

**Comment by skjnldsv** [comment]
@pierre-alain-b master is 29, this will get backported to 28 after merge

**Review by susnux — APPROVED** [review]

**Pull request merged**
