### PR TITLE
Add a section for groups in share overview

### PR DESCRIPTION
**Pull request by mamatt**
Here is the idea, 
we want to be able to see from which group files/folders has been shared !

The idea is to show group shareds in a same place.
This is to facilitate the usage of group sharing in a working context where there can be a big amount of sharing

capture d ecran de 2019-02-27 15-51-25

### CODE REVIEW

**Comment by ChristophWurst** [comment]
cc @nextcloud/sharing for review

**Comment by jancborchardt** [comment]
Hmm, this is part of "Shared with others", is it not? Why the necessity to have a separate section? :)

@mamatt we try to do stuff as simple as possible, and from experience, adding another section does not facilitate use of something as it makes everything more obscure. (E.g. commenting is not widely used because it’s a separate tab in the sidebar, which is why we want to combine the chronological activity: https://github.com/nextcloud/server/issues/658 )

**Comment by mamatt** [comment]
Hum in fact, this more a part of "shared whith you" and as I write it I see the confusing part :)

One main use case is, as an example:
"Some file were shard with the financial service group , one week after some other files, and so on.
Some month later, some users from this group want to know what files were shared with financial services groups ? For now there is no place to find this information !"

I understand you're feeling about keeping the interface simple, so maybe it should be integrated with "shared with you".

Maybe in the "shared with you" filelist, it should have sections.

I had try to keep the PR simple, maybe this not a simple problem at all :)

**Comment by jancborchardt** [comment]
> "Some file were shard with the financial service group , one week after some other files, and so on.
Some month later, some users from this group want to know what files were shared with financial services groups ? For now there is no place to find this information !"

Thanks a lot for describing the requirements, that’s very important! :)

Would this section then take care of that even? Because if you are part of multiple groups, you don’t really know which group it is?

Alternatively we could show the group icon (or overlapped avatars) on the right where normally the original sharer is shown. That way you directly know it’s a group share, and we don’t need a specific section.

Because when your question is "What has been shared with the 'Financial Services' group" (for example) then this question should not need navigating to a specific section to be answered. As then we have to tell everyone they find that information there. :)

**Comment by mamatt** [comment]
I think that adding the group name /avatar to the filelist directly in "the shared with you" overview is the right way, as long as it is possible to sort by group !

Should we close this PR as i think it is now not relevant !

**Comment by mamatt** [comment]
I'm closing the PR as it is not relevant anymore !

**Pull request closed without merging**
