### PR TITLE
Bump doctrine/dbal to 3.5.1 in master

### PR DESCRIPTION
**Pull request by come-nc**
For https://github.com/nextcloud/server/issues/32595

- [ ] https://github.com/nextcloud/3rdparty/pull/1218
- [ ] rebase

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

**Comment by nickvergessen** [comment]
> Error: lib/private/DB/Connection.php:127:12: InternalMethod: The method Doctrine\DBAL\Connection::connect is internal to Doctrine but called from OC\DB\Connection

🪦

**Comment by come-nc** [comment]
> lib/private/DB/Connection.php:127:12

@nickvergessen Do we have any other choice than to ignore those errors?
From what I understand real changes will only happen with dbal 4.x.

Should I add those Internal* errors to the baseline?

(Note that there is also a test error that needs to be looked into)

**Comment by come-nc** [comment]
ref: https://github.com/morozov/dbal/blob/3.5.x/UPGRADE.md

A lot of things got deprecated or marked as internal

**Pull request closed without merging**
