### PR TITLE
Add recognize to recommended apps

### PR DESCRIPTION
**Pull request by marcelklehr**

### CODE REVIEW

**Comment by marcelklehr** [comment]
I'll get on it :)

**Comment by marcelklehr** [comment]
Recognize v3.0.0-beta.1 is out

**Comment by PVince81** [comment]
yesterday discussed with @karlitschek and @jospoortvliet that we'd add it to the notification instead, I've raised it here: https://github.com/nextcloud/firstrunwizard/pull/739

@marcelklehr feel free to push the icon / description there instead

**Pull request closed without merging**
