### PR TITLE
Fix legacy cal/card dav endpoint

### PR DESCRIPTION
**Pull request by rullzer**
#2685 against master

### CODE REVIEW

**Review by LukasReschke — CHANGES_REQUESTED** [review]
See https://github.com/nextcloud/server/commit/710be0c9c3f5cffd37aafa98ed86f6d6343c0176#commitcomment-20198501

**Comment by pbek** [comment]
PUT on <http://localhost:8081/remote.php/caldav/calendars/admin/admin-test/ownCloud-48x0fj081ahtxyn5tdwv6j38frc6787302w69b2re4wrhkw3ik9.ics> causes still:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
    <s:sabredav-version>3.2.0</s:sabredav-version>
    <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
    <s:message>File not found: groups in 'principals'</s:message>
</d:error>
```

**Comment by LukasReschke** [comment]
Yep - same reason I rejected this. Adjusting the test file is not really a solution @rullzer :wink:

**Comment by rullzer** [comment]
Let me close this till I ahve it working on stabel11

**Pull request closed without merging**
