### PR TITLE
Update PHP-Parser for 7.1 compatibility

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] https://github.com/nextcloud/3rdparty/pull/236

how to test:
* Run `occ app:check-code spreed` on https://github.com/nextcloud/spreed/pull/1532 before and after this

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:tada:

**Comment by MorrisJobke** [comment]
> * [x]  [nextcloud/3rdparty#236](https://github.com/nextcloud/3rdparty/pull/236)

merged

**Review by MorrisJobke — APPROVED** [review]

**Comment by nickvergessen** [comment]
Rebased and set 3rdparty to the merge commit

**Comment by MorrisJobke** [comment]
Phan fails: https://drone.nextcloud.com/nextcloud/server/15791/273

PHPUnit fails as well:

```
1) Test\Command\CronBusTest::testClosure
Error: Class 'SuperClosure\Serializer' not found

/drone/src/github.com/nextcloud/server/lib/private/Command/CronBus.php:70
/drone/src/github.com/nextcloud/server/lib/private/Command/CronBus.php:45
/drone/src/github.com/nextcloud/server/lib/private/Command/AsyncBus.php:46
/drone/src/github.com/nextcloud/server/tests/lib/Command/AsyncBusTest.php:132
```

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/3rdparty/pull/238

**Comment by rullzer** [comment]
Updated 3rdparty

**Comment by rullzer** [comment]
CI happy

**Pull request merged**
