### PR TITLE
add global site selector as user back-end which doesn't support password confirmation

### PR DESCRIPTION
**Pull request by schiessle**
beside user_saml, also the user management implemented in the global site selector doesn't support password verification.

### CODE REVIEW

**Comment by rullzer** [comment]
Let me drop this here: https://github.com/nextcloud/server/pull/11786

:wink:

**Comment by schiessle** [comment]
@rullzer #11786 looks good! :+1: But we also need something for 14, that's why I would like to get this in and backported as a intermediate step.

**Review by rullzer — APPROVED** [review]
Fine by me

**Review by MorrisJobke — APPROVED** [review]
Code makes sense as an intermediate step 👍

**Pull request merged**
