### PR TITLE
[stable12] Don't trigger activity when the email didn't change

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #5126

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Review by blizzz — COMMENTED** [review]
Not necessary with more recent https://github.com/nextcloud/server/pull/5216, unless you want an additional safety net

**Comment by nickvergessen** [comment]
I would keep it, just to be sure and since this was already given out to multiple users as a patch.

**Comment by blizzz** [comment]
makes sense. 👍  then

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
