### PR TITLE
Add audio formats to htaccess

### PR DESCRIPTION
**Pull request by therealklanni**
ref: #21561

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks :+1: 

If this change is accepted https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst needs to be updated as well.

**Review by juliusknorr — APPROVED** [review]
Fine by me :+1:

**Comment by therealklanni** [comment]
> Thanks 👍
> 
> If this change is accepted https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst needs to be updated as well.

I can do that as well, should I add it to this PR?

**Comment by therealklanni** [comment]
Does anyone understand the CI failure?

**Comment by kesselb** [comment]
> Does anyone understand the CI failure?

Safe to ignore.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
