### PR TITLE
+nodeinfo public service

### PR DESCRIPTION
**Pull request by ArtificialOwl**
needed by the social app.

> NodeInfo is an effort to create a standardized way of exposing metadata about a server running one of the distributed social networks. The two key goals are being able to get better insights into the user base of distributed social networking and the ability to build tools that allow users to choose the best fitting software and server for their needs.

source: https://github.com/jhass/nodeinfo

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@daita Mind to add a setup check as well and add it to the Nginx config in the docs? The setup check should only run if the social app is enabled.

**Comment by MorrisJobke** [comment]
> @daita Mind to add a setup check as well and add it to the Nginx config in the docs? The setup check should only run if the social app is enabled.

🏓

**Comment by daita** [comment]
So, there is some check. Also, this should fix #13088.

I think more logical to returns 404 if the public_*service* is not set, or if the app is not available/installed (instead of 501)

**Comment by rullzer** [comment]
So is this ready?

**Comment by daita** [comment]
My bad, totally forgot to push.

However, we also need to define what [error code should be returned](https://github.com/nextcloud/server/blob/master/public.php#L47-L73):

- when no public service as been assigned.
- when public service as been assigned, the app is still enabled but the linked php file is not readable.
- when public service as been assigned but the app is not enabled anymore.

Also: https://github.com/nextcloud/server/issues/13088#issuecomment-515220945

@MorrisJobke :ping_pong:

**Comment by daita** [comment]
@rullzer can you have a look to my last post regarding this issue?

**Comment by rullzer** [comment]
> * when no public service as been assigned.
> * when public service as been assigned, the app is still enabled but the linked php file is not readable.
> * when public service as been assigned but the app is not enabled anymore.

in all those cases a 404 seems appropriate. And do proper logging to the log file.
For the end user it is all a not found error basically.

**Review by rullzer — APPROVED** [review]

**Comment by daita** [comment]
Alright, so I checked the current implementation, and confirm that this PR:

- change the public.php to fit the last comment from @rullzer (returning 404 for each described cases) (should fix #13088)
- add .well-known/nodeinfo public service
- add tests

also rebased.

@nickvergessen @ChristophWurst @danxuliu please review before next beta/rc

**Comment by nickvergessen** [comment]
So the social app is going to set that config?

**Comment by daita** [comment]
like the webfinger public service, yes

**Review by nickvergessen — APPROVED** [review]

**Comment by daita** [comment]
@rullzer i'll make a light backport of the fix on the tests

**Pull request merged**
