### PR TITLE
Issues#26293-Chinese search optimize(v20.0.8)

### PR DESCRIPTION
**Pull request by jgzh**
#26293 
@szaimen

### CODE REVIEW

**Review by szaimen — CHANGES_REQUESTED** [review]
Hi @jgzh,

Thanks for taking the time to create this PR!

Can you please make your changes on this file, though and create a new PR with that? https://github.com/nextcloud/server/edit/master/lib/private/Files/Cache/Cache.php
(We usually make changes on master and backport them to other stable branches afterwards).

Thank you very much!

**Comment by jgzh** [comment]
Yeh, but I found the implements of search function on the master branch are quit different with the branch stable20.

It may take a few days to me to test and verify whether it works on the master branch or not.

And after that I will create another PR  : )

**Comment by szaimen** [comment]
Thanks a lot :)

**Comment by szaimen** [comment]
I hope it is fine when I close this then...

**Pull request closed without merging**
