### PR TITLE
\OC\Settings\Personal: Emit 'preRenderForm' event before rendering the personal settings form

### PR DESCRIPTION
**Pull request by leonklingele-work**
This allows other apps to hook in and add their own section to the
'Personal Settings' page via:

    \OC_Hook::connect('\OC\Settings\Personal', 'preFormRender',\
        $this, 'onPreFormRender');

### CODE REVIEW

**Comment by nickvergessen** [comment]
1. We don't use emitter stuff anymore, but the symfony event dispatcher
2. You should be able to register your own setting in your info.xml, for examples see:
https://github.com/nextcloud/server/blob/2cb346114685ded69f5291812503c278298c1bce/apps/files_external/appinfo/info.xml#L32-L33

**Comment by leonklingele-work** [comment]
> You should be able to register your own setting in your info.xml, for examples see:

This is not what we want to achieve. The info.xml settings you mentioned adds a new tab to the personal settings page, see this screenshot:
nextcloud-personal-settings-new-tab-infoxml

We want to extend the 'Personal Info' page directly as shown here:
nextcoud-personal-settings-pr

I had a discussion with @schiessle about this. Please don't close the PR prematurely.

**Comment by nickvergessen** [comment]
Yeah as mentioned in the chat.
If you dont want your own section, use the existing ones. You can find the IDs in:
https://github.com/nextcloud/server/blob/da6dd4898ae90b8a692426d0b341dae7e1c235d8/lib/private/Settings/Manager.php#L464

Additional when this is about timezone/date settings, I would hardcode them in since tasks app, activity and others also make use of this.

**Comment by leonklingele-work** [comment]
This is indeed already possible without adding any events.
The solution:

1. Add this to your `info.xml`:
```xml
<settings>
	<personal>OCA\YOUR_APP_ID\Settings\Personal</personal>
</settings>
```
2. Create a `Personal` class in that namespace which extends `OCP\Settings\ISettings`, e.g. https://github.com/nextcloud/server/blob/2cb346114685ded69f5291812503c278298c1bce/apps/files_external/lib/Settings/Personal.php
3. Increase your app's version
4. Run the upgrader

**Pull request closed without merging**
