### PR TITLE
Master is now 29

### PR DESCRIPTION
**Pull request by nickvergessen**
# ⚠️ To be merged only

- [x] After stable28 creation
- [x] By release manager: @blizzz 

## Todos
- [x] `.github/dependabot.yml`
  - [x] Add a new section about the new `stableY` branch
- [x] `.github/workflows/update-cacert-bundle.yml`
  - [x] Adjust backport list of cacert automation to include `stableY`
- [x] `.github/workflows/update-psalm-baseline.yml`
  - [x] Adjust backport list of psalm automation to include `stableY`
- [x]  `.github/workflows/npm-audit-fix.yml`
  - [x] Adjust backport list of psalm automation to include `stableY`
- [x] `apps/settings/lib/WellKnown/SecurityTxtHandler.php`
  - [x] Bump `Expires` date to be 5 months in the future
  - [x] Trigger the backport bot for all still supported versions
- [x] `version.php`
  - [x] Increase the major version in `$OC_Version` and 0-ify the other digits
  - [x] Set `$OC_VersionString` to `Major.0.0 dev`
  - [x] Add the newest major to `$OC_VersionCanBeUpgradedFrom`
  - [x] Remove the oldest major to `$OC_VersionCanBeUpgradedFrom`
- [x] `apps/*/appinfo/info.xml`
  - [x] Update Minor version of all apps and 0ify the patch version
  - [x] Bump version requirement to the new Major
- [x] Rebuilt frontend `npm ci && npm run build`
- [x] Fix other apps on stable branch:
    - [x] Create stable branch in https://github.com/nextcloud-deps/ocp
    - [x] Add stable branch to cron: https://github.com/nextcloud-deps/ocp/pull/18 + https://github.com/nextcloud-deps/ocp/pull/19
    - [x] Adjust version on stable28 https://github.com/nextcloud-deps/ocp/pull/20
    - [x] Run the cron 
- [x] Branch-off the stable28 branch in all affected apps, before sending this PR
    - [x] https://github.com/nextcloud/server/pull/41679

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by nickvergessen** [comment]
- [x] Add stable28 to `.github/workflows/npm-audit-fix.yml`

**Comment by nickvergessen** [comment]
Version number seems to be part of core common....
image


So rebuilt it

**Comment by nickvergessen** [comment]
/backport 61572c1985f93ddc634c893415026e2cae826bf4 to stable28

**Comment by nickvergessen** [comment]
/backport 61572c1985f93ddc634c893415026e2cae826bf4 to stable27

**Comment by nickvergessen** [comment]
/backport 61572c1985f93ddc634c893415026e2cae826bf4 to stable26

**Pull request merged**
