### PR TITLE
merge file activity settings into a single 'favorite changed' item

### PR DESCRIPTION
**Pull request by icewind1991**
Activity PR: https://github.com/nextcloud/activity/pull/481

Before:

image

After:

image

- share option are moved into "Files" section
- "created", "changed", "renamed", "deleted" and "restored" are merged into "changed"
- activity and notifications are only generated for changes made by other users
- activity feed shows changes for all shared files
- email/notifications only for favorited files

### CODE REVIEW

**Comment by rullzer** [comment]
@icewind1991 could you which such PRs always include before and after screenshots. Makes the review a lot easier

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by nickvergessen** [comment]
> activity and notifications are only generated for changes made by other users

😿

This makes activity so much less useful for home instances. All files will basically never have any activity and I think it's a rather bad regression.
I agree you shouldn't get notifications in that case, but removing the activities is rather bad and should be reverted from my pov. I think we also discussed in the past to just always show these in the streams, like you also see you own tweets, toots, posts and everything else.
Also it might be important in a shared context, to be able to quickly see whether another user modified the file after or before yourself.

**Comment by MorrisJobke** [comment]
> This makes activity so much less useful for home instances. All files will basically never have any activity and I think it's a rather bad regression.
> I agree you shouldn't get notifications in that case, but removing the activities is rather bad and should be reverted from my pov. I think we also discussed in the past to just always show these in the streams, like you also see you own tweets, toots, posts and everything else.
> Also it might be important in a shared context, to be able to quickly see whether another user modified the file after or before yourself.

Makes sense and I thought this was discussed with you in advance.

**Comment by jancborchardt** [comment]
Yeah, removing your own actions from the _Activity_ app was never part of the plan as far as I remember. It should stay as it is not only useful in single-user setups, but also for teams it gives important context. @icewind1991

**Comment by icewind1991** [comment]
All valid points but it can also cause the activity feed to be flooded with items that are usually irrelevant.

Either way I'm open for changing it if we have a consensus to include it.

cc @MorrisJobke @rullzer @jancborchardt

**Pull request merged**
