### PR TITLE
[3rparty] Bump symfony/console

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/nextcloud/3rdparty/pull/12

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:boom:

```
1) Tests\Core\Command\Config\App\GetConfigTest::testGet with data set #2 ('name', null, false, 'newvalue', true, 'json', 0, '"newvalue"')
Failed asserting that 1 is identical to 0.

/drone/src/github.com/nextcloud/server/tests/Core/Command/Config/App/GetConfigTest.php:155

2) Tests\Core\Command\Config\System\GetConfigTest::testGet with data set #2 ('name', null, false, 'newvalue', true, 'json', 0, '"newvalue"')
Failed asserting that 1 is identical to 0.

/drone/src/github.com/nextcloud/server/tests/Core/Command/Config/System/GetConfigTest.php:164

3) Tests\Core\Command\Config\System\GetConfigTest::testGet with data set #22 (array('name', 'c'), array(1, 2), true, true, true, 'json', 0, 'true')
Failed asserting that 1 is identical to 0.

/drone/src/github.com/nextcloud/server/tests/Core/Command/Config/System/GetConfigTest.php:164

4) Tests\Core\Command\User\SettingTest::testCheckInput with data set #3 (array(array('uid', 'username'), array('key', '')), array(array('ignore-missing-user', true)), array(array('--default-value', true)), false, 'The "default-value" option ca...a key.')
Failed asserting that 'The "default-value" option can only be used when specifying a key.' is false.

/drone/src/github.com/nextcloud/server/tests/Core/Command/User/SettingTest.php:219

5) Tests\Core\Command\User\SettingTest::testCheckInput with data set #6 (array(array('uid', 'username'), array('key', 'configkey'), array('value', '')), array(array('ignore-missing-user', true)), array(array('--default-value', true)), false, 'The value argument can not be...alue".')
Failed asserting that 'The value argument can not be used together with "default-value".' is false.

/drone/src/github.com/nextcloud/server/tests/Core/Command/User/SettingTest.php:219

6) Tests\Core\Command\User\SettingTest::testCheckInput with data set #11 (array(array('uid', 'username'), array('key', 'configkey')), array(array('ignore-missing-user', true), array('delete', true)), array(array('--default-value', true)), false, 'The "delete" option can not b...alue".')
Failed asserting that 'The "delete" option can not be used together with "default-value".' is false.

/drone/src/github.com/nextcloud/server/tests/Core/Command/User/SettingTest.php:219

7) Tests\Core\Command\User\SettingTest::testExecuteDelete with data set #0 ('config', false, null, 0)
Symfony\Component\Console\Output\OutputInterface::writeln('config', 0) was not expected to be called.

/drone/src/github.com/nextcloud/server/core/Command/User/Setting.php:190
/drone/src/github.com/nextcloud/server/tests/lib/TestCase.php:182
/drone/src/github.com/nextcloud/server/tests/Core/Command/User/SettingTest.php:300

8) Tests\Core\Command\User\SettingTest::testExecuteDelete with data set #1 ('config', true, null, 0)
Symfony\Component\Console\Output\OutputInterface::writeln('config', 0) was not expected to be called.

/drone/src/github.com/nextcloud/server/core/Command/User/Setting.php:190
/drone/src/github.com/nextcloud/server/tests/lib/TestCase.php:182
/drone/src/github.com/nextcloud/server/tests/Core/Command/User/SettingTest.php:300

9) Tests\Core\Command\User\SettingTest::testExecuteDelete with data set #2 (null, false, null, 0)
Symfony\Component\Console\Output\OutputInterface::writeln('<error>The setting does not e...error>', 0) was not expected to be called.

/drone/src/github.com/nextcloud/server/core/Command/User/Setting.php:197
/drone/src/github.com/nextcloud/server/tests/lib/TestCase.php:182
/drone/src/github.com/nextcloud/server/tests/Core/Command/User/SettingTest.php:300

10) Tests\Core\Command\User\SettingTest::testExecuteSet with data set #3 (null, true, '<error>The setting does not e...error>', 1)
OCP\IConfig::setUserValue('username', 'appname', 'configkey', 'setValue', null) was not expected to be called.

/drone/src/github.com/nextcloud/server/core/Command/User/Setting.php:177
/drone/src/github.com/nextcloud/server/tests/lib/TestCase.php:182
/drone/src/github.com/nextcloud/server/tests/Core/Command/User/SettingTest.php:368

11) Tests\Core\Command\User\SettingTest::testExecuteGet with data set #1 (null, 'config', 'config', 0)
Expectation failed for method name is equal to <string:writeln> when invoked 1 time(s)
Parameter 0 for invocation Symfony\Component\Console\Output\OutputInterface::writeln('<error>The setting does not e...error>', 0) does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'config'
+'<error>The setting does not exist for user "username".</error>'

/drone/src/github.com/nextcloud/server/core/Command/User/Setting.php:197
/drone/src/github.com/nextcloud/server/tests/lib/TestCase.php:182
/drone/src/github.com/nextcloud/server/tests/Core/Command/User/SettingTest.php:434
```

**Comment by rullzer** [comment]
Test fixed. Ready for review: @MorrisJobke @nickvergessen @LukasReschke

**Comment by MorrisJobke** [comment]
Commands still work 👍 

@rullzer This PR has conflicts

**Comment by rullzer** [comment]
Ah right I fixed the tests in a different PR.
Rebased.

**Comment by nickvergessen** [comment]
User report fails

**Comment by nickvergessen** [comment]
db:convert-type uses removed ProgressHelper and DialogHelper
user:report uses removed TableHelper
install uses removed DialogHelper
user:add uses removed DialogHelper
user:resetpassword uses removed DialogHelper

**Comment by rullzer** [comment]
Thanks for checking @nickvergessen so we have no tests in place for all that... nice :S
I'll look into it

**Comment by rullzer** [comment]
@nickvergessen I think I got them all

**Comment by nickvergessen** [comment]
:+1:

**Comment by rullzer** [comment]
Ai slightly to fast needed to merge 3rdparty still

**Pull request merged**
