### PR TITLE
Remove Flysystem storage class

### PR DESCRIPTION
**Pull request by LukasReschke**
This seems unused as per https://github.com/nextcloud/server/issues/27768 and may allow us to get rid of one more dependency.

Once merged we can also try to get rid of league/flysystem in the third-party repository.

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by LukasReschke** [comment]
@icewind1991 Ping?

**Comment by skjnldsv** [comment]
> @icewind1991 Ping?

vacations

**Comment by LukasReschke** [comment]
@icewind1991 Ping? 🙏

**Comment by ChristophWurst** [comment]
> Once merged we can also try to get rid of league/flysystem in the third-party repository.

:+1: According to https://github.com/search?l=PHP&p=1&q=org%3Anextcloud+Flysystem&type=Code only https://github.com/nextcloud/queue/blob/06ce13892ecba4de72d4d7623df5c26f51561172/vendor/illuminate/filesystem/FilesystemManager.php uses Flysystem in our organization.

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
