### PR TITLE
allow admin to disable groups on personal page

### PR DESCRIPTION
**Pull request by schiessle**
cc @MorrisJobke @nickvergessen @rullzer

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Failing test is due to outdated autoloader - fixed in master.

**Review by MariusBluem — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Regression: #5277

**Comment by MorrisJobke** [comment]
Reverted in #5383

**Pull request merged**
