### PR TITLE
set default CSP on NotFoundResponse

### PR DESCRIPTION
**Pull request by rullzer**
Found when working on https://github.com/nextcloud/server/pull/17077

To test just navigate to an invalid link share.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Why in NotFoundResponse and not the Response base class?

**Comment by rullzer** [comment]
> Why in NotFoundResponse and not the Response base class?

Because not all responses should have the main CSP set.
Only user facing responses should

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
So actually this could just extend the TemplateResponse?

**Comment by rullzer** [comment]
> So actually this could just extend the TemplateResponse?

yes that would also make sense I guess

**Pull request merged**
