### PR TITLE
fix(migration): Check if column exits before adding it

### LINKED ISSUE #48372: [Bug]: Exception: Database error when running migration The column "scheduled_at" on table "oc_taskprocessing_tasks" already exists.
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to upgrade after migration to a new Server.
The following error appears.
Exception: Database error when running migration 30000Date20240708160048 for app core The column "scheduled_at" on table "oc_taskprocessing_tasks" already exists.
I I've tried  to find a workaround for this error on google but can't find anything about it.
I I've searched https://help.nextcloud.com also.
Is there a way to manipulate the db before upgrading so that the upgrade runs through?
For me it is hard to say if it is a bug or I did something wrong.....
Thanks and best regards.

### Steps to reproduce

1. Migrated data-folder like it is described in your documentation (Backup/restore)
2. Dumped and restored mariadb-server database like it is described in your documentation (Backup/restore)
3. In the end it is a move from LTS 18.04 to 24.04....so not sure if you will call it bug...or just out of scope...

### Expected behavior

get the db upgraded ....

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/48372

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Makes sense! Can we somehow add a test for this so that such an if clause is never forgotten?

**Review by joshtrichards — APPROVED** [review]
Check makes sense, but I don't understand the state people are ending up in in that bug report: upgrading from v29 directly shouldn't have that column anyhow.

**Comment by joshtrichards** [comment]
> Makes sense! Can we somehow add a test for this so that such an if clause is never forgotten?

Integration testing focused on the the upgrade path should catch these. Particularly if we have a matrix covering major->major, beta->major, rc->major, etc.

**Pull request merged**
