### PR TITLE
Use GitHub container registry

### PR DESCRIPTION
**Pull request by LukasReschke**
To avoid Docker ratelimit issues.

TODO:

- [x] Update with GitHub Container Registry images

### CODE REVIEW

**Comment by LukasReschke** [comment]
@MorrisJobke Do we have a GitHub bot account that we can use to reference the Secret for pulling? 

Ref https://docs.drone.io/pipeline/docker/syntax/images/#pulling-private-images

(Currently GitHub registry requires authentication)

**Comment by MorrisJobke** [comment]
> @MorrisJobke Do we have a GitHub bot account that we can use to reference the Secret for pulling?

Yep - there is @nextcloud-bot and @nextcloud-pr-bot. Depends on how fine granular the permission for this token can be set. I would like to have a token purely for this registry pull. I assume that selecting no scope would do that, right? 

Bildschirmfoto 2021-05-26 um 22 34 28

**Comment by MorrisJobke** [comment]
Otherwise I would create a new account for that.

**Comment by LukasReschke** [comment]
@MorrisJobke `read:packages` is required, which should not be too bad even if the token leaks probably :)

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

**Comment by splitt3r** [comment]
What about using the shiny new GitHub container registry instead of the old Packages? https://github.blog/2020-09-01-introducing-github-container-registry/ You would not have to migrate and later on and it seems to have some cool feautres even if it is still in beta phase.

**Comment by LukasReschke** [comment]
> <div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0OTM2MzE0MA==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0OTM2MzE0MA==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0OTM2MzE0MA==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-849363140" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists" data-body-version="f57a9645e24361d65ef24ce0228b92a14d222d59a9db2905ff454978a557a779" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-top-left-radius: 6px; border-top-right-radius: 6px; border-bottom-right-radius: 6px; border-bottom-left-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">What about using the shiny new GitHub container registry instead of the old Packages?&nbsp;https://github.blog/2020-09-01-introducing-github-container-registry/&nbsp;You would not have to migrate later on and it seems to have some cool feautres even if it is still in beta phase.</task-lists></div><form class="js-comment-update" id="issuecomment-849363140-edit-form" action="/nextcloud/server/issue_comments/849363140" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div id="partial-timeline" class="js-timeline-marker js-socket-channel js-updatable-content" data-channel="eyJjIjoicHVsbF9yZXF1ZXN0OjY1NDE0MjkzNyIsInQiOjE2MjIxMTIwMTV9--2d1ff8e9c165347568f0ad1550e15e0e96469218d41eccedb25dfaf1212c14ba" data-url="/_render_node/MDExOlB1bGxSZXF1ZXN0NjU0MTQyOTM3/pull_requests/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-05-27T06%3A25%3A28Z" data-last-modified="Thu, 27 May 2021 06:25:28 GMT" data-gid="MDExOlB1bGxSZXF1ZXN0NjU0MTQyOTM3" style="box-sizing: border-box;"></div><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--color-bg-canvas); border-top: 2px solid var(--color-border-primary);"><div id="partial-pull-merging" class="pull-merging js-pull-merging js-socket-channel js-updatable-content js-pull-refresh-on-pjax " aria-live="polite" data-channel="eyJjIjoicmVwbzo2MDI0MzE5NzpicmFuY2g6dXNlLWdpdGh1Yi1yZWdpc3RyeSIsInQiOjE2MjIxMTIwMTZ9--04c4e382c7f45ae2aa44d51e23c02a2721ce556ca46ba2e61169a573c9e1f356 eyJjIjoicmVwbzo2MDI0MzE5NzpicmFuY2g6bWFzdGVyIiwidCI6MTYyMjExMjAxNn0=--d253083b28860b276803e2139459ccf25d14bb541b304b3cb0a5cf32c4685be7 eyJjIjoicmVwbzo2MDI0MzE5Nzpjb21taXQ6MjhlZThiYmQ2NTM4MmFmNzk3MjIwNjFhYzA1YTVkMjBiODRmOGE4MiIsInQiOjE2MjIxMTIwMTZ9--a8bc9dfaeab4029b1b29fb73f2b3b7fb740f567b6c998a4cd5abf982c6902494 eyJjIjoiaXNzdWU6OTAyODE0MTUzOnN0YXRlIiwidCI6MTYyMjExMjAxNn0=--94fab5ecbf81ce4c3bcba337b22ae540a740be16c63c76c07cd56e541ecb3c42 eyJjIjoicHVsbF9yZXF1ZXN0OjY1NDE0MjkzNzpyZXZpZXdfc3RhdGUiLCJ0IjoxNjIyMTEyMDE2fQ==--cbd607abef237b3dbd8c682ba08ae25a1ed0fb0d1e0cd08c4543571f0a73ebd2 eyJjIjoicHVsbF9yZXF1ZXN0OjY1NDE0MjkzNzp3b3JrZmxvd19ydW4iLCJ0IjoxNjIyMTEyMDE2fQ==--9d2bce1baf6aa5f541c06ea94c83e2f8c9b95237e936c63d45af6dba57eeda63" data-url="/nextcloud/server/pull/27125/show_partial?merge_type=merge&amp;partial=pull_requests%2Fmerging" style="box-sizing: border-box; caret-color: rgb(36, 41, 46); color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"></div><br class="Apple-interchange-newline"></div>

Giving that a try with https://github.com/nextcloud/docker-ci/commit/a38d00cbb70331eb44a800ef3a28a1d260de8f5c. Thanks :)

**Review by skjnldsv — APPROVED** [review]
Failure unrelated

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
