### PR TITLE
add a heading to the login form

### LINKED ISSUE #34037: Title for log in page
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The log in page feels a bit off at the moment, possibly due to directly having fields, but not a title like we have on other pages like for errors etc.
image

**Describe the solution you'd like**
Standard heading above the fields:
image

What do you think @nimishavijay @CarlSchwan?

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/34037

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by nimishavijay — APPROVED** [review]
🚀 :)

**Review by jancborchardt — COMMENTED** [review]
Thank you! :)

**Pull request merged**
