### PR TITLE
Fix example theme

### PR DESCRIPTION
**Pull request by juliusknorr**
Otherwise the login page will not be themed. #5036

Move styles.css to server.css

Before:
2017-05-23-111809_943x456_scrot

After:
2017-05-23-111726_951x440_scrot

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
cc @karlitschek @juliushaertl For the backport

**Comment by karlitschek** [comment]
nice. please backport :+1:

**Comment by juliushaertl** [comment]
backport at #5489

**Pull request merged**
