### PR TITLE
Enh/load less assets

### PR DESCRIPTION
**Pull request by rullzer**
We probably can do more. but for now this already saves 3 extra loads.

### CODE REVIEW

**Comment by skjnldsv** [comment]
Do we have tests for that? So they're not outdated on the repo?

**Comment by rullzer** [comment]
No. Because this is the JSCombiner way. So it happens on the fly.

When we move them to webpack we should add tests yes.

**Comment by rullzer** [comment]
Ah moved the files so should fix the unit tests as well... will take care this evening.

**Comment by skjnldsv** [comment]
@rullzer but didn't we just moved to webpack for that? :p

**Comment by rullzer** [comment]
Not for those files yet. But @ChristophWurst wanted to cleanup some stuff with the webpack as well.

**Comment by rullzer** [comment]
Long story short yes it will happen ;)

**Comment by rullzer** [comment]
Actually lets first move this to webpack before doing more crazy stuff.

**Pull request closed without merging**
