### PR TITLE
Make user status heartbeat API publicly accessible

### PR DESCRIPTION
**Pull request by provokateurin**
I want to use the heartbeat in my app, but the API currently can't be access without CSRF stuff.

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
I would be fine with this

**Comment by CarlSchwan** [comment]
Please fix the dco 😅

**Comment by jld3103** [comment]
@CarlSchwan fixed it and rebased. Anything missing?

**Comment by jld3103** [comment]
Fixed the DCO and the broken JS

**Review by skjnldsv — APPROVED** [review]

**Comment by jld3103** [comment]
Fixed the lint once again :see_no_evil:

**Comment by jld3103** [comment]
Will this just get merged right before the 25.0.0 release? Sorry I'm unsure what the status here is.

**Comment by CarlSchwan** [comment]
> Will this just get merged right before the 25.0.0 release? Sorry I'm unsure what the status here is.

sorry this was forgotten but is ready to go, can you fix the conflict?

```
git rebase master
npm ci && npm run build && npm run sass && npm run sass:icons
git push -f
```

**Comment by jld3103** [comment]
Will do!

**Comment by jld3103** [comment]
Done

**Comment by CarlSchwan** [comment]
cool thanks now let see if the ci is still happy :)

**Comment by jld3103** [comment]
Hm errors don't look related.

**Comment by CarlSchwan** [comment]
It wasn't related

**Comment by jld3103** [comment]
Thanks!

**Pull request merged**
