### PR TITLE
Fixes in files_drop.js

### PR DESCRIPTION
**Pull request by danxuliu**
The `singleFileUploads` option, which is enabled by default, causes the jQuery File Upload plugin to call the `add` callback once for each file to be uploaded. The `add` callback set in `OCA.FilesSharingDrop.initialize` stored the file name in the `fileName` variable; that variable was later used in the `done` callback to find the appropriate file in the list whose loading icon had to be replaced with a MIME type icon. However, when several files were added at the same time the `fileName` variable is overwritten with the name of each new file in the upload set. Thus, when the `done` callback was later called `fileName` contained the name of the last file and therefore the replaced icon was that of the last file.

There was no need to store the file name, though; as `singleFileUploads` is enabled the `files` property of the `data` parameter given to all the callbacks always contains a single file, which is the one that has been added, has finished uploading, or has failed uploading.

While fixing that (reported in #6060) I found other issues in _files_drop.js_ that I have partially fixed (like a `<li>` element nested inside another `<li>` element when a file upload failed); however, there are still some pending issues related to escape characters (like _"_ or _\\_) in file names that need to be fixed before merging this.

There are no automated tests for these issues yet, as they were way more cumbersome to set than I had expected; I will try to add them in the future.

Also, this fixes the issue with multiple uploaded files in _master_. However, #6060 is reported against Nextcloud 12.0.1; if there are no objections I will backport this pull request to _stable12_ once it is finished.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Also, this fixes the issue with multiple uploaded files in master. However, #6060 is reported against Nextcloud 12.0.1; if there are no objections I will backport this pull request to stable12 once it is finished.

:+1:

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@danxuliu I guess it's ready for review, right? I tested it, it worked and the code looks good.

**Comment by danxuliu** [comment]
@MorrisJobke 
> I guess it's ready for review, right? I tested it, it worked and the code looks good.

Not yet, unless you want to merge this now and then fix the issues with names that include escape characters like _"_ or _\_ in another pull request.

Also I had not time yet to study how to add unit tests for this (which would be pretty useful for the escape characters issue); on the other hand, acceptance tests are, unfortunately, not technically feasible for the file drop use case (at least, not in a clean, non-hacky way due to how upload is handled in Selenium and how it is done in the file drop page) :-(

**Comment by MorrisJobke** [comment]
> Not yet, unless you want to merge this now and then fix the issues with names that include escape characters like " or __ in another pull request.

Yes :)

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@danxuliu Could you open the backport please?

**Comment by danxuliu** [comment]
@MorrisJobke Done!

**Comment by MorrisJobke** [comment]
Just as a sidenote: the backport request label should then be removed to properly find PRs that are not yet backporten ;)

**Pull request merged**
