### PR TITLE
Replace coffin emoji with cross

### PR DESCRIPTION
**Pull request by georgehrke**
Signed-off-by: Georg Ehrke <developer@georgehrke.com>

### CODE REVIEW

**Comment by skjnldsv** [comment]
It's the same issue, the cross doesn't make sense in Hinduism, Islam, Shintoism, Buddhism... :)

**Comment by georgehrke** [comment]
@skjnldsv As roeland said, Google calendar uses the same. Otherwise pull-requests are always welcome 😉

**Comment by skjnldsv** [comment]
@georgehrke I'd remove the emoji totally. :)

**Comment by georgehrke** [comment]
But then you end up with `Name (year)`. That's now very self-explanatory.
If anything, we could change it to `Death of Name`

**Comment by skjnldsv** [comment]
Sounds good to me :)
What do you think? (also cc @jancborchardt)

**Comment by jancborchardt** [comment]
Alright, so relevant reading:
- [Symbols of death](https://en.wikipedia.org/wiki/Symbols_of_death)
- [Dagger (typography) – Modern usage](https://en.wikipedia.org/wiki/Dagger_(typography)#Modern_usage)
   > While daggers are freely used in English-language texts, they are often avoided in other languages because of their similarity to the Christian cross.
- [Symbols of Death: Cultural and Visual Representations](https://www.academia.edu/38495457/Symbols_of_Death_Cultural_and_Visual_Representations)
- [Death Icons in Different Cultures – Infographic](https://www.finder.com.au/death-icons-in-different-cultures-infographic)


So there just seem to be too many symbols and too many connotations.


-----------------

The only symbol that _could_ maybe work as also in symmetry with the birthday cake might be:
**[🥀 wilted flower](https://emojipedia.org/wilted-flower/)**

What do you think?

**Comment by skjnldsv** [comment]
Feels a bit sad to me :)
A good shape flower would be nice :stuck_out_tongue:

**Comment by jancborchardt** [comment]
Then let’s just avoid any symbolic issues and simply go with "Death of Name (Year)" as @georgehrke mentioned previously.

**Comment by georgehrke** [comment]
Okay, i will look into this next week.

**Comment by georgehrke** [comment]
See https://github.com/nextcloud/server/blob/bf59f4889142154dce525960723bc686123baa38/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php#L401L406 for  the new labels.

**Review by jancborchardt — APPROVED** [review]
Much better now

**Review by rullzer — APPROVED** [review]

**Review by rullzer — CHANGES_REQUESTED** [review]
CI does :boom:

**Review by skjnldsv — APPROVED** [review]

**Comment by georgehrke** [comment]
CI is happy except for the usual couple of databases that went away

**Pull request merged**
