### PR TITLE
[stable22] Bump guzzlehttp to 7.4.5

### PR DESCRIPTION
**Pull request by CarlSchwan**

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by CarlSchwan** [comment]
> Error: Call to undefined function GuzzleHttp\Psr7\build_query() in /drone/src/3rdparty/microsoft/azure-storage-common/src/Common/Internal/ServiceRestProxy.php:300

This needs a corresponding azure bump :(

**Comment by szaimen** [comment]
Closing due to https://github.com/nextcloud/3rdparty/pull/1078#issue-1267347802

**Comment by CarlSchwan** [comment]
we still need to either update to 7.4.5 or at least backport some important patch from the dependency

**Comment by szaimen** [comment]
> we still need to either update to 7.4.5 or at least backport some important patch from the dependency

Joas recommended to update to the latest 6.x release for stable22...

**Comment by CarlSchwan** [comment]
Replaced with a simpler patch of the affected bug instead of a big dependency bump

**Pull request closed without merging**
