### PR TITLE
Enhance identify proof storage

### PR DESCRIPTION
**Pull request by rullzer**
Todo:
- [ ] Tests

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by blizzz** [comment]
@nickvergessen still useful?

**Comment by nickvergessen** [comment]
I guess so

**Comment by rullzer** [comment]
So chances of me finishing this are low but since I saw activity in my github notifications let me write some things down that came to mind.

1. Test should still be written
2. I think the code at the moment is fine but I'd add a few things
  * Write a migration job to loop over all users and move their stuff
  * Release
  * Remove the migration stuff a release or so later

Else you will keep this hacky code around for all eternity

**Comment by skjnldsv** [comment]
Still seems important :see_no_evil:

**Pull request closed without merging**
