### PR TITLE
Better error message on invalid sharing link

### LINKED ISSUE #5346: "Unspecified share exception" instead of proper 404 page on unknown public share tokens
* open a public share page with a not available share token - like http://example.org/s/abcdef
* expected: get a proper 404 page
* actual: get a "Unspecified share exception"

bildschirmfoto 2017-06-12 um 11 18 12

Ideas when this came in?

@nextcloud/sharing @nickvergessen

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #5346

### CODE REVIEW

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Tests are failing now 🙈

**Review by LukasReschke — APPROVED** [review]

**Comment by nickvergessen** [comment]
👍 thanks

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by nickvergessen** [comment]
Backport in https://github.com/nextcloud/server/issues/5387

**Pull request merged**
