### PR TITLE
Change name of the product in update message

### LINKED ISSUE #96: Last message during upgrade says ownCloud instead of Nextcloud
### Steps to reproduce
1.Upgrade oC to Nc: https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551
2.hit the update button

### Expected behaviour
The last message during update is "redirecting to Nextcloud"

### Actual behaviour
The last message during update is "redirecting to ownCloud"

### Server configuration
**Operating system**:
?
**Web server:**
?
**Database:**
mySQL
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
9.0.50
**Updated from an older Nextcloud/ownCloud or fresh install:**
9.0
**Where did you install Nextcloud from:**
https://nextcloud.com/install/

...I ignored any other requests for information from the issue template since this seems like a simple language file issue

### PR DESCRIPTION
**Pull request by MorrisJobke**
- also update all german translations
- fixes #96 

cc @AndyScherzinger  @mar1u5 @mikebabb @LukasReschke @blizzz @schiessle

### CODE REVIEW

**Comment by mar1u5** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mar1u5** [comment]
THX. Merging. As soon as Transifex is up, we should not make translation changes inside of GitHub 😁 ...do you prepare an backport? @MorrisJobke

**Comment by MorrisJobke** [comment]
@karlitschek Backport was requested. I would vote for a backport ;)

**Comment by karlitschek** [comment]
totally. let's backport

**Comment by MorrisJobke** [comment]
Backport is in https://github.com/nextcloud/server/pull/108

**Pull request merged**
