### PR TITLE
Remove not existent function call

### PR DESCRIPTION
**Pull request by LukasReschke**
- Removes a not existent function call
- Removes a fallback for Windows

Signed-off-by: Lukas Reschke lukas@statuscode.ch

### CODE REVIEW

**Comment by rullzer** [comment]
Whee remove code :dancing_women: 

LGTM

**Comment by nickvergessen** [comment]
Nice 👍 

Maybe that also fixes https://github.com/nextcloud/server/issues/1707
I asked them to test it.

**Comment by bantu** [comment]
LGTM

**Comment by derkostka** [comment]
@nickvergessen does not fix #1707 . Apart from that 👍  for the change

**Pull request merged**
