### PR TITLE
switching to LoggerInterface

### PR DESCRIPTION
**Pull request by ArtificialOwl**

### CODE REVIEW

**Comment by PVince81** [comment]
please resolve the conflicts

**Comment by rullzer** [comment]
What is the status here?

**Comment by daita** [comment]
rebased, and added also the `LoggerInterface` to the class `CacheQueryBuilder` that extend `QueryBuilder`

**Review by juliusknorr — CHANGES_REQUESTED** [review]
Needs some more adjustments:

```
/home/runner/work/server/server/lib/private/DB/QueryBuilder/QueryBuilder.php:234:20:error - UndefinedInterfaceMethod: Method Psr\Log\LoggerInterface::logException does not exist
/home/runner/work/server/server/lib/private/DB/QueryBuilder/QueryBuilder.php:249:20:error - UndefinedInterfaceMethod: Method Psr\Log\LoggerInterface::logException does not exist
/home/runner/work/server/server/lib/private/DB/QueryBuilder/QueryBuilder.php:270:19:error - UndefinedInterfaceMethod: Method Psr\Log\LoggerInterface::logException does not exist
/home/runner/work/server/server/lib/private/DB/QueryBuilder/QueryBuilder.php:280:19:error - UndefinedInterfaceMethod: Method Psr\Log\LoggerInterface::logException does not exist
```

**Pull request closed without merging**
