### PR TITLE
Use TTF fonts for avatar generation

### LINKED ISSUE #8189: Text is not generated along avatar in NC 13.0.0 RC 4
### Steps to reproduce
Install 12.0.0 from https://download.nextcloud.com/server/releases on CentOS 7 with PHP 7.1.13

Packages that I have installed along PHP are

>     - policycoreutils-python
>     - lbzip2-utils
>     - openssl
>     - php71w-fpm
>     - php71w-opcache
>     - php71w-common # ctype, iconv, json, libxml, simplexml, zip, zlib, curl, fileinfo, bz2, openssl, ftp, exif, gmp
>     - php71w-xml
>     - php71w-gd 
>     - php71w-xml # dom, xmlreader, xmlwriter
>     - php71w-mbstring 
>     - php71w-intl # intl
>     - php71w-mcrypt
>     - php71w-mysql
>     - php71w-ldap
>     - php71w-imap
>     - php71w-pecl-apcu 
>     - php71w-pecl-redis
>     - php71w-pecl-imagick
>     - php71w-process # posix
>     - libreoffice

Update to NC 13.0.0 RC 4 via web based updater.

Go to settings and update your Full name

Avatar (circle) will change colour but it won't have any letters.

Error log will include:

> imagettftext(): Could not read font at /var/www/nextcloud/lib/private/Avatar.php#266
> imagettfbbox(): Could not read font at /var/www/nextcloud/lib/private/Avatar.php#260

### Expected behaviour

Avatar should get updated with letters generated using `OpenSans-Semibold.woff`

### Actual behaviour

Avatar does not gain any letters inside it, it just changes a colour.

I have tried setting up a separate new CentOS 7 with fresh NC, and this error occurred there again.

When I changed `OpenSans-Semibold.woff` with ttf `OpenSans-Regular.ttf`, it worked. 

I have GD2, FreeType enabled:

screen shot 2018-02-06 at 12 54 06 am

### Server configuration
 
**Operating system**:

CentOS Linux release 7.4.1708 (Core)

**Web server:**

nginx/1.12.2

**Database:**

mysql  Ver 15.1 Distrib 10.2.12-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**

PHP 7.1.13 (cli)

**Nextcloud version:** (see Nextcloud admin page)

13.0.0 RC4

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from 12.0.0

**Where did you install Nextcloud from:**

https://download.nextcloud.com/server/releases 

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - announcementcenter: 3.1.1
  - bruteforcesettings: 1.0.3
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - dav: 1.4.6
  - external: 3.0.1
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - unsplash: 1.0.5
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - contacts
  - encryption
  - files_downloadactivity
  - files_external
  - keeweb
  - quota_warning
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.0.13",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0"
        },
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloud",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": ***REMOVED SENSITIVE VALUE***,
                "use_ssl": false,
                "region": "optional",
                "use_path_style": true
            }
        },
        "asset-pipeline.enabled": "true",
        "skeletondirectory": "",
        "enable_previews": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": "1",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "default_language": "ka_GE",
        "tempdirectory": "\/data\/nextcloud\/tmp",
        "updater.release.channel": "stable",
        "preview_max_x": "2000",
        "preview_max_y": "2000",
        "trashbin_retention_obligation": "31, 31"
    }
}
```
</details>

**Are you using external storage, if yes which one:** 

Local minio server

**Are you using encryption:** 

no

**Are you using an external user-backend, if yes which one:**

no

### Client configuration
**Browser:**

63.0.3239.132 (Official Build) (64-bit)

**Operating system:**

macOS High Sierra 10.13.4 Beta

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2018/02/05 22:00:19 [error] 21865#0: *68 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: **Removed sentivive value**, server: **Removed sentivive value**, request: "GET /apps/logreader/poll?lastReqId=MuV0nZ1bDKwB72tgA5Jh HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "**Removed sentivive value**"
2018/02/05 22:39:13 [error] 22587#0: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: **Removed sentivive value**, server: **Removed sentivive value**, request: "GET /apps/logreader/poll?lastReqId=SPY3on4JiibTTMGMhimH HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "**Removed sentivive value**"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"ewO5hqPWBrq66EqTYqvC","level":3,"time":"2018-02-05T20:07:01+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"GET","url":"\/avatar\/dachi\/64?v=-373","message":"imagettfbbox(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#259","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"ewO5hqPWBrq66EqTYqvC","level":3,"time":"2018-02-05T20:07:01+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"GET","url":"\/avatar\/dachi\/64?v=-373","message":"imagettftext(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#265","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"TbHKpvTfeBp3vUwED4kA","level":3,"time":"2018-02-05T20:07:01+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"GET","url":"\/avatar\/dachi\/290?v=-373","message":"imagettfbbox(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#259","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"TbHKpvTfeBp3vUwED4kA","level":3,"time":"2018-02-05T20:07:01+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"GET","url":"\/avatar\/dachi\/290?v=-373","message":"imagettftext(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#265","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"ZBip1VJ8810wB7HNn0OQ","level":3,"time":"2018-02-05T20:47:04+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"PUT","url":"\/settings\/users\/dachi\/settings","message":"imagettfbbox(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#259","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"ZBip1VJ8810wB7HNn0OQ","level":3,"time":"2018-02-05T20:47:04+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"PUT","url":"\/settings\/users\/dachi\/settings","message":"imagettftext(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#265","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"2nyZPoezfOTKtImXXzj5","level":3,"time":"2018-02-05T20:47:04+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"GET","url":"\/avatar\/dachi\/64?v=-796","message":"imagettfbbox(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#259","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"2nyZPoezfOTKtImXXzj5","level":3,"time":"2018-02-05T20:47:04+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"GET","url":"\/avatar\/dachi\/64?v=-796","message":"imagettftext(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#265","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"OWipKMFlQyIEpSqWAFSG","level":3,"time":"2018-02-05T20:47:04+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"GET","url":"\/avatar\/dachi\/290?v=-796","message":"imagettfbbox(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#259","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
{"reqId":"OWipKMFlQyIEpSqWAFSG","level":3,"time":"2018-02-05T20:47:04+00:00","remoteAddr":"**Removed sentivive value**","user":"dachi","app":"PHP","method":"GET","url":"\/avatar\/dachi\/290?v=-796","message":"imagettftext(): Could not read font at \/var\/www\/nextcloud\/lib\/private\/Avatar.php#265","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.13"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
64?v=-86 | 200 | png | merged-template-prepend.js?v=3793cd21-6:5178 | 895 B | 59 ms
-- | -- | -- | -- | -- | --
290?v=-86 | 200 | png | merged-template-prepend.js?v=3793cd21-6:5178 | 1.6 KB | 82 ms
```
</details>

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #8189 

Use ttf fonts for avatar generation. So it also works on CentOS

Could any of you test this (should apply pretty easy on 13): @Temtaime @tmaff @DeC1pher @MrLordy @splitt3r

### CODE REVIEW

**Comment by thegcat** [comment]
I had the same issue in the same circumstances and this seems to have fixed the issue for see, thanks!

**Comment by DeC1pher** [comment]
Fixed the issue. Thanks!

**Comment by rullzer** [comment]
Thanks for testing! I'll make sure this also lands in 13.0.1

**Review by ChristophWurst — APPROVED** [review]
Didn't test but makes sense to use these fonts if that fixes the issue with Centos

**Comment by splitt3r** [comment]
Fixed the issue for me too :+1:

**Comment by DeC1pher** [comment]
Now the Avatar disappeared in the Android app. Can anyone relate?

**Comment by DeC1pher** [comment]
Ah, I temporary switched my name, so it recreated the Avatar and deletet the app cache - all good.

**Comment by Franck2A** [comment]
In my side, the patch fixed the message error log but still no profil letter avatar.
RHEL 7.4 (CENTOS)

**Comment by rullzer** [comment]
@Franck2A did you change the display name of the user? So the avatar gets regenerated?

**Comment by Franck2A** [comment]
@rullzer Tnx for your response, how to change display name ? I'm using ldap authenticated.
Please help, regards

**Comment by splitt3r** [comment]
You could also upload a dummy avatar and delete it so the default one gets regenerated. Did the job for me.

**Comment by Franck2A** [comment]
@splitt3r Tnx that's work find on my account. Is it possible to do it massively for all accounts ?
Regards

**Comment by susadm** [comment]
Not working for me :(
Centos 7 NExtcloud 13
After downloading the fonts and changing the Avatar.ini there are still no letters and the error is still present

imagettftext(): Could not read font at /var/www/html/nextcloud/lib/private/Avatar.php#266 | 2018-02-21T14:16:31+0100
-- | --
Error | PHP | imagettfbbox(): Could not read font at /var/www/html/nextcloud/lib/private/Avatar.php#260

I have changed the name of an user and created a new one...


drwxr-xr-x.  2 apache apache   4096 Feb 21 13:57 .
drwxr-xr-x. 17 apache apache   4096 Feb 10 21:29 ..
-rw-r--r--.  1 apache apache  11560 Feb 10 21:29 LICENSE.txt
-rw-r--r--.  1 apache apache 156148 Feb 21 13:56 OpenSans-Light.ttf
-rw-r--r--.  1 apache apache  62844 Feb 10 21:29 OpenSans-Light.woff
-rw-r--r--.  1 apache apache 217360 Feb 10 21:29 OpenSans-Regular.ttf
-rw-r--r--.  1 apache apache  20544 Feb 10 21:29 OpenSans-Regular.woff
-rw-r--r--.  1 apache apache 156735 Feb 21 13:57 OpenSans-Semibold.ttf
-rw-r--r--.  1 apache apache  69888 Feb 10 21:29 OpenSans-Semibold.woff

Avater.ini

$background = imagecolorallocate($im, $backgroundColor[0], $backgroundColor[1], $backgroundColor[2]);
                $white = imagecolorallocate($im, 255, 255, 255);
                imagefilledrectangle($im, 0, 0, $size, $size, $background);

                $font = __DIR__ . '/../../core/fonts/OpenSans-Semibold.ttf';

                $fontSize = $size * 0.4;
                $box = imagettfbbox($fontSize, 0, $font, $text);

                $x = ($size - ($box[2] - $box[0])) / 2;
                $y = ($size - ($box[1] - $box[7])) / 2;
                $x += 1;

any Idea?

**Pull request merged**
