### PR TITLE
Port password settings to vue

### PR DESCRIPTION
**Pull request by CarlSchwan**
- Port to vue
- Update nextcloud vue component to latest beta to use ncpasswordfield component
- Update the visual look
image

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looks nice design-wise! :)

cc @marcoambrosini since you worked on the TextInput – are you good with how it looks together with the button?

**Review by marcoambrosini — APPROVED** [review]
lgtm too, but shouldn't we wait for the input component and use that @CarlSchwan?

**Comment by CarlSchwan** [comment]
NcPasswordField is now merged, just need a new release of the nextcloud vue library ;)

**Comment by CarlSchwan** [comment]
Ci failures unrelated

**Pull request merged**
