### PR TITLE
Allow attaching plugins to the ShareTabView and trigger event on render

### PR DESCRIPTION
**Pull request by juliusknorr**
This allows apps to register custom plugins and listen to the render event on the share tab view. It can be used for apps like groupfolders to show more advanced data inside of the sharing tab.

Example usage for groupfolders:

```
OCA.Groupfolders = {};
OCA.Groupfolders.ShareTabPlugin = {
	attach: function (shareTabView) {
		shareTabView.on('rendered', function() {
			if (this.model && this.model.get('mountType') === 'group') {
				// Add more info the share tab here
			}
		});
	}
};
OC.Plugins.register('OCA.Sharing.ShareTabView', OCA.Groupfolders.ShareTabPlugin);
```

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Review by rullzer — APPROVED** [review]
:elephant:

**Review by skjnldsv — APPROVED** [review]
Looks ok to me

**Review by danxuliu — APPROVED** [review]
I have not tested it, but the code looks good :+1:

**Pull request merged**
