### PR TITLE
Use the cache also for UserBackend::getPassword

### PR DESCRIPTION
**Pull request by nickvergessen**
Bildschirmfoto von 2022-02-16 17-55-42

(Screenshot together with #31217 )

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by CarlSchwan** [comment]
Tests are not happy :/

**Comment by nickvergessen** [comment]
Test fixed

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
acceptance test for users failed
now since this PR is about user management, I've restarted the tests just to be sure

**Comment by nickvergessen** [comment]
I would consider it after we know an instance that uses Database backend ran good for some days.
In general I think it's fine to backport

**Pull request merged**
