### PR TITLE
Allow single file downloads so the video player works again

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up to #19348

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
@nickvergessen apparently it also happen on folder :)
Videoplayer also fails then :see_no_evil:

**Comment by nickvergessen** [comment]
Was fixed in https://github.com/nextcloud/server/pull/20044 already

**Comment by skjnldsv** [comment]
Ah, 18.0.3

**Pull request merged**
