### PR TITLE
fix(theming): Fix color inverted icons based on theming and dark mode

### LINKED ISSUE #41352: Settings icons are color inverted based on wrong metrix
The icons of the `app-navigation-*` are influenced by the dark/bright theme. However for the active entry this behaviour is wrong and it would always need to use the color of `var(--color-primary-element-text)` instead of a filter `var(--background-invert-if-dark)`

Basically we need the opposite of https://github.com/nextcloud/server/blob/3378a73e99171ac31860ccca81b1b3197e63417f/apps/theming/lib/Themes/CommonThemeTrait.php#L55

Bright theme | Dark theme
---|---
Bildschirmfoto vom 2023-11-09 07-18-08 | Bildschirmfoto vom 2023-11-09 07-18-04
Bildschirmfoto vom 2023-11-09 07-18-26 | Bildschirmfoto vom 2023-11-09 07-18-30

### PR DESCRIPTION
**Pull request by nickvergessen**
* Resolves: #41352 

## Summary

Mode | Before | After
---|---|---
Bright mode + text-on-primary "white" | Bildschirmfoto vom 2023-11-29 11-23-17 |Bildschirmfoto vom 2023-11-29 11-26-21
Dark mode + text-on-primary "white" | Bildschirmfoto vom 2023-11-29 11-23-23 | Bildschirmfoto vom 2023-11-29 11-26-17
Bright mode + text-on-primary "black" | Bildschirmfoto vom 2023-11-29 11-29-01 | Bildschirmfoto vom 2023-11-29 11-26-54
Dark mode + text-on-primary "black" | Bildschirmfoto vom 2023-11-29 11-28-46 | Bildschirmfoto vom 2023-11-29 11-26-59

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Thanks a lot for fixing this @nickvergessen! :)

Tested and seems to work fine but found one remaining spot where it is broken:
image

**Comment by nickvergessen** [comment]
Found and fixed the user header menu and the arrow-down/up option for the nested share files list:

Bildschirmfoto vom 2023-11-29 11-56-48
Bildschirmfoto vom 2023-11-29 11-58-18

**Review by AndyScherzinger — APPROVED** [review]

**Comment by szaimen** [comment]
Seems like it didnt work :/

**Comment by nickvergessen** [comment]
Compiled assets... will do manually

**Pull request merged**
