### PR TITLE
Cast query result to int

### PR DESCRIPTION
**Pull request by rullzer**
Else we never create the default address book

CC: @icewind1991 @LukasReschke @MorrisJobke @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
Yeah, good step. However when a group you are a member of has received a shared calendar already (read only) no calendar will be created either. Happen for me on the company instance. Maybe you can also have a look at that?

**Comment by rullzer** [comment]
Yeah I could do that. But let's get this minor fix in first.

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
