### PR TITLE
Fix IE11 upload fallback methods

### PR DESCRIPTION
**Pull request by skjnldsv**
:rage: 

https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsBinaryString#Browser_compatibility

Steps:
- Try uploading a file without extension, see an error without any more informations

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
🙈

**Comment by nickvergessen** [comment]
@ma12-co do we need this in talk too?

**Comment by skjnldsv** [comment]
> @ma12-co do we need this in talk too?

Now I'm afraid to look at the code you're using in talk :see_no_evil:

**Review by juliusknorr — APPROVED** [review]

**Review by danxuliu — APPROVED** [review]
Tested and works :+1: 

However, note that the problem was not in files without extension, but in files without extension, with size divisible by 4096 and smaller than 102400 bytes. How did you find this? xD

**Comment by skjnldsv** [comment]
> How did you find this? xD

I have my reasons xD

**Pull request merged**
