### PR TITLE
Added integration tests for sharees using v2.php

### PR DESCRIPTION
**Pull request by MorrisJobke**
* downstream of https://github.com/owncloud/core/pull/26915

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by icewind1991** [comment]
Seems to fail

**Comment by MorrisJobke** [comment]
Rebased to fix the failing integration tests (hopefully)

**Comment by MorrisJobke** [comment]
I updated the bash syntax because there was an error with the run.sh in the integration test.

**Comment by nickvergessen** [comment]
I pushed a fix for the failing test... deleting a group was not compatible on ocs v2
```xml
<?xml version="1.0"?>
    <ocs>
     <meta>
      <status>failure</status>
      <statuscode>100</statuscode>
      <message/>
     </meta>
     <data/>
    </ocs>
```

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
