### PR TITLE
Fix removing groups that have a slash in the name

### LINKED ISSUE #18211: Remove group with slash in the name impossible
### Steps to reproduce
1. create a group with a slash in its name. e.g /test
2. try to delete that group

### Expected behaviour
The group should be delete.

### Actual behaviour
I receive a message "An error occured during the request. Unable to proceed."

### Server configuration

**Operating system:**
Docker image based on debian:buster-slim
**Web server:**

**Database:**
sqllite3

**PHP version:**
7.3.12

**Nextcloud version:** (see Nextcloud admin page)
17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
No, it is a new install 

**Where did you install Nextcloud from:**
https://github.com/nextcloud/docker/blob/149daa299df22713c26e383daf9ffd1f28d94ecb/17.0/fpm/Dockerfile

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>

Accessibility | 1.3.0
Activity | 2.10.1
Brute-force settings | 1.4.0
Collaborative tags | 1.7.0
Comments | 1.7.0
Deleted files | 1.7.0
Federation | 1.7.0
File sharing | 1.9.0
First run wizard | 2.6.0
Gallery | 18.4.0
Log Reader | 2.2.0
Monitoring | 1.7.0
Nextcloud announcements | 1.6.0
Notifications | 2.5.0
Password policy | 1.7.0
PDF viewer | 1.6.0
Privacy | 1.1.0
Recommendations | 0.5.0
Right click | 0.15.1
Share by mail | 1.7.0
Support | 1.0.1
Text | 1.1.1
Theming | 1.8.0
Update notification | 1.7.0
Usage survey | 1.5.0
Versions | 1.10.0
Video player | 1.6.0
Viewer | 1.2.0
Auditing / Logging | 1.7.0
Default encryption module | 2.5.0
External storage support | 1.8.0
LDAP user and group backend |  1.7.0

</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8090"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "17.0.1.1",
        "overwrite.cli.url": "http:\/\/localhost:8090",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
No used
```
</details>

### Client configuration
**Browser:**
chrome 78
**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Nothing</summary>

```
Insert your webserver log here
172.17.0.1 - - [03/Dec/2019:16:27:59 +0000] "POST /login/confirm HTTP/1.1" 200 782 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

172.17.0.1 - - [03/Dec/2019:16:27:59 +0000] "DELETE /ocs/v2.php/cloud/groups//test HTTP/1.1" 400 808 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

127.0.0.1 - - [03/Dec/2019:16:28:00 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.12 (internal dummy connection)"

127.0.0.1 - - [03/Dec/2019:16:28:01 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.12 (internal dummy connection)"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
None
```

### PR DESCRIPTION
**Pull request by gary-kim**
Closes #18211 

Fix removing groups that have a slash in the name such as `/test`.

I will backport manually once this is merged.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by gary-kim — COMMENTED** [review]
Should add some acceptance tests

EDIT: Oh, acceptance tests for this are currently disabled because of a needed patch?
https://github.com/nextcloud/server/blob/81b919ed9f497c975d1b8158abdcdabb0712f39e/tests/acceptance/features/users.feature#L71-L79
@skjnldsv Do you think these could be reenabled now? Should probably be a different PR.

**Comment by skjnldsv** [comment]
> @skjnldsv Do you think these could be reenabled now? Should probably be a different PR.

Highly doubt it, we're late by one major on selenium.
Too hard to upgrade.
We need to migrate our tests to cypress

**Review by GretaD — APPROVED** [review]

**Comment by rullzer** [comment]
Needs a rebase

**Comment by gary-kim** [comment]
@rullzer Done

**Pull request merged**
