### PR TITLE
fix(Navigation): ensure NavManager is inited when adding an entry

### PR DESCRIPTION
**Pull request by blizzz**
## Summary

otherwise custom order cannot be applied

Needed by https://github.com/nextcloud/tables/pull/904

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Pytal** [comment]
Would adding as a closure entry be better? ref: https://github.com/nextcloud/server/commit/970846624feb154800666c7c3293d9ec27861c71

**Comment by blizzz** [comment]
> Would adding as a closure entry be better? ref: [9708466](https://github.com/nextcloud/server/commit/970846624feb154800666c7c3293d9ec27861c71)

Ah, probably, but it does not make this fix less useful.

Even better would be an Event one could listen to. Right now I react to `BeforeTemplateRenderedEvent`, but it does only feel so right.

**Comment by Pytal** [comment]
> Ah, probably, but it does not make this fix less useful.

Agreed!

> Even better would be an Event one could listen to. Right now I react to `BeforeTemplateRenderedEvent`, but it does only feel so right.

👍

**Review by Pytal — APPROVED** [review]

**Comment by blizzz** [comment]
:ballot_box_with_check:  Changed my code to supply a Closure – thanks!

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
