### PR TITLE
Update psalm-baseline.xml in stable21

### PR DESCRIPTION
**Pull request by nickvergessen**
Should make CI green again

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
`Static code analysis / static-code-analysis (pull_request) Failing after 2m — static-code-analysis`

**Comment by skjnldsv** [comment]
```
/home/runner/work/server/server/apps/files_external/lib/Lib/Storage/SFTPReadStream.php:175:10:error - FalsableReturnStatement: The declared return type 'int' for OCA\Files_External\Lib\Storage\SFTPReadStream::stream_write does not allow false, but the function returns 'false'
/home/runner/work/server/server/apps/files_external/lib/Lib/Storage/SFTPReadStream.php:187:10:error - FalsableReturnStatement: The declared return type 'array<array-key, mixed>' for OCA\Files_External\Lib\Storage\SFTPReadStream::stream_stat does not allow false, but the function returns 'false'
/home/runner/work/server/server/apps/files_external/lib/Lib/Storage/SFTPWriteStream.php:129:10:error - FalsableReturnStatement: The declared return type 'string' for OCA\Files_External\Lib\Storage\SFTPWriteStream::stream_read does not allow false, but the function returns 'false'
/home/runner/work/server/server/apps/files_external/lib/Lib/Storage/SFTPWriteStream.php:140:12:error - FalsableReturnStatement: The declared return type 'int' for OCA\Files_External\Lib\Storage\SFTPWriteStream::stream_write does not allow false, but the function returns 'false'
/home/runner/work/server/server/apps/files_external/lib/Lib/Storage/SFTPWriteStream.php:156:10:error - FalsableReturnStatement: The declared return type 'array<array-key, mixed>' for OCA\Files_External\Lib\Storage\SFTPWriteStream::stream_stat does not allow false, but the function returns 'false'
/home/runner/work/server/server/lib/private/Files/Stream/SeekableHttpStream.php:124:11:error - FalsableReturnStatement: The declared return type 'string' for OC\Files\Stream\SeekableHttpStream::stream_read does not allow false, but the function returns 'false'
/home/runner/work/server/server/lib/private/Files/Stream/SeekableHttpStream.php:157:11:error - FalsableReturnStatement: The declared return type 'array<array-key, mixed>' for OC\Files\Stream\SeekableHttpStream::stream_stat does not allow false, but the function returns 'false'
/home/runner/work/server/server/lib/private/Files/Stream/SeekableHttpStream.php:176:10:error - FalsableReturnStatement: The declared return type 'int' for OC\Files\Stream\SeekableHttpStream::stream_write does not allow false, but the function returns 'false'
```

**Comment by nickvergessen** [comment]
Seems local version was too different 🤔

**Comment by MorrisJobke** [comment]
> Should make CI green again



> Should make CI green again

The problem was fixed by #27346. 

As this only removes stuff it could not fix issues, as fewer issues is not an error case for psalm. So I will close this here as it is fixed with a different PR.

**Pull request closed without merging**
