### PR TITLE
use closure to properly defer l10n initialization (#27328)

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by nickvergessen** [comment]
Another product backported this, I guess we could too.
Should help a little bit for all the web dav requests...

**Review by rullzer — APPROVED** [review]
Fine by me. But I see no real reason to backport.

**Review by ChristophWurst — APPROVED** [review]
Makes sense, code looks good

**Comment by icewind1991** [comment]
Missing signed off

**Pull request merged**
