### PR TITLE
Rename "External storages" to "External storage"

### PR DESCRIPTION
**Pull request by jbicha**
Do I need to update the translations too or does that already happen more or less automatically?

### CODE REVIEW

**Comment by eppfel** [comment]
I think it would be nice, if you changed the translation keys / english translation. Look for these:


```
/apps/files_external/lib/Settings/Section.php:
52  	 */
53  	public function getName() {
54: 		return $this->l->t('External storages');
55  	}
56  
```

The translations into other languages will be handled by transifex.

**Comment by rullzer** [comment]
No need to update all the translations. They are handled by transifex as @eppfel 

@icewind1991 please have a quick look. Maybe renaming the routes is also not such a good idea?

**Comment by rullzer** [comment]
O and. @jbicha thanks a lot for the PR :smile:

**Comment by jbicha** [comment]
I thought it also looked bad to have https://cloud.example.com/settings/admin/externalstorages as a URL

**Comment by eppfel** [comment]
> Maybe renaming the routes is also not such a good idea?

I would take the risk. It is just the UI, I think the only thing that could break are references from other parts of nextcloud. And we changed from `#` to `/` in the settings URLs as well. :wink:

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
I would go for this. But the changes in l10n/ are not needed (they will be overwritten by transifex anyways). Could you revert them? Besides that it looks good 👍

**Comment by jbicha** [comment]
@MorrisJobke Thanks. I rebased without the l10n changes.

**Comment by MorrisJobke** [comment]
If the app was enabled before the table `oc_admin_section` would need a rename. To avoid this I would vote for keeping the name `externalstorages` but rename all the user visible texts only.

**Comment by eppfel** [comment]
> If the app was enabled before the table oc_admin_section would need a rename. To avoid this I would vote for keeping the name externalstorages but rename all the user visible texts only.

Is a migration a lot of work?

**Comment by MorrisJobke** [comment]
> Is a migration a lot of work?

Writing it like this: https://github.com/nextcloud/server/blob/master/lib/private/Repair/Collation.php

Shouldn't be hard, but should be tested quite well ;)

**Comment by jbicha** [comment]
@MorrisJobke I'm not familiar with the NextCloud code. Why does `oc_admin_section` need a rename? I thought I only changed a few strings and the URL. And the change seemed to work fine when I tested the change on a site where the External storage plugin was already active.

**Comment by MorrisJobke** [comment]
> @MorrisJobke I'm not familiar with the NextCloud code. Why does oc_admin_section need a rename? I thought I only changed a few strings and the URL. And the change seemed to work fine when I tested the change on a site where the External storage plugin was already active.

We store all the registered sections in the database to not load all the registration code again. So this needs to be updated there.

**Comment by jbicha** [comment]
@MorrisJobke Thanks, but I'm not a PHP developer and I don't know how to do that.

This started as a simple typo bug which I thought I could submit a fix for. Are you interested in taking over this merge proposal since I don't know how to make my merge proposal do what you're asking?

**Comment by MorrisJobke** [comment]
Let's keep it as it is for now. The app allows to mount multiple external storages and the name is okay.

**Comment by jbicha** [comment]
It's not great English grammar, but I'm probably not going to be able to fix this up myself.

**Comment by MorrisJobke** [comment]
> It's not great English grammar, but I'm probably not going to be able to fix this up myself.

The problem is, that this currently causes more problems. Sorry to say that, but we are all busy with other tasks. Maybe we can look into this in the future. Thanks anyways for your help. Could you create an issue to not forget about this? Thanks

**Comment by jbicha** [comment]
@MorrisJobke Already done. #2973 Thanks!

**Pull request closed without merging**
