### PR TITLE
fix: Update `@nextcloud/files` to fix public link shares

### LINKED ISSUE #42009: [Bug]: Move or copy file on link share does not work
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is a bug when you're trying to move files inside of a full access link share. The modal "Choose target files" not getting directory listing for move or copy target, because the `userid` and  `path` for DAV request is missing in the context of link share.

### Steps to reproduce

1. Create directory `d1`
2. Create directory `d2` inside of `d1`
3. Create file `f1.txt` inside of `d1`
4. Create link share of `d1` with full access (`Can edit`)
5. Open link share in other browser (does not matter if you are being logged in to Nextcloud)
6. Select `f1.txt`
7. Try to move `f1.txt` into `d2` via  `actions -> move or copy`
8. See error: "Choose target folder" modal list is not loading

### Expected behavior

The files in "Choose target folder" modal displayed correctly with only shared items to perform operations allowed with "Full access link share", and these operations are successfully made.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
From browser console:

`PROPFIND https://stable27.local/remote.php/dav/files/undefined/`
```

### Additional info

image

### LINKED ISSUE #45420: [Bug]: The FilePicker does not load for moving or copying a file or a folder when not logged in
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The file picker does not load for moving or copying a file or a folder when not logged in.

image

### Steps to reproduce

1. While being logged in, share link of any folder
    1. Click on image at the right of the folder name,
    2. "Open details", "Sharing" tab, "+" at the right of "Share link"
2. Set the sharling link as "can edit" (Screenshot below)
    1. after the preceding steps, click on "View only", then click on "Can edit" in the drop-down list.
3. Go into the folder and create a new file (any type) or folder.
4. Log-out of Nextcloud or open a Private window of your web browser.
5. Paste the sharing link of your newly shared folder.
6. Click on image at the right of the previously created file.
7. Click on "Move or copy".

image

### Expected behavior

The file picker should load and display the current directory.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

The browser console output

```
Error: No user id found
    M index.mjs:871
    l FilePicker-DBGB1Rec.mjs:797
    f FilePicker-DBGB1Rec.mjs:825
    async* FilePicker-DBGB1Rec.mjs:829
    VueJS 25
    render index.mjs:33
    VueJS 8
    s index.mjs:30
    pick index.mjs:88
    pick index.mjs:87
    filepicker dialogs.js:360
    actionHandler fileactions.js:701
    action fileactions.js:136
    _onClickAction fileactionsmenu.js:63
    jQuery 10
    Backbone 6
    _showMenu fileactions.js:375
    Underscore 3
    _renderInlineAction fileactions.js:467
    jQuery 5
vue.runtime.esm.js:3065:16
    VueJS 29
    render index.mjs:33
    VueJS 8
    s index.mjs:30
    pick index.mjs:88
    pick index.mjs:87
    filepicker dialogs.js:360
    actionHandler fileactions.js:701
    action fileactions.js:136
    _onClickAction fileactionsmenu.js:63
    jQuery 10
    Backbone 6
    _showMenu fileactions.js:375
    Underscore 3
    _renderInlineAction fileactions.js:467
    jQuery 5
```

This is the error thrown:
https://github.com/nextcloud/server/blob/5a6e48e85034aa81862b1fcbd93cb4ce58165e72/apps/files/src/services/Files.ts#L45

I think it is where it is called from:
https://github.com/nextcloud/server/blob/5a6e48e85034aa81862b1fcbd93cb4ce58165e72/apps/files/src/actions/moveOrCopyAction.ts#L145

The call of `getContents` seems to be the culprit there. And it is not systematic in this file.
- When `method === MoveCopyAction.COPY`, it's using `client.getDirectoryContents`.
- Otherwise (e.g., `MoveCopyAction.MOVE_OR_COPY`) ,  `getContents` (which looks for the user id) is used.

Moreover, it seems the comments are not consistent with the code.
Example:

https://github.com/nextcloud/server/blob/5a6e48e85034aa81862b1fcbd93cb4ce58165e72/apps/files/src/actions/moveOrCopyAction.ts#L144C1-L146C52

```ts
// show conflict file popup if we do not allow overwriting
const otherNodes = await getContents(destination.path)
if (hasConflict([node], otherNodes.contents)) {
```

It seems nothing is testing of we allow or not overwriting since https://github.com/nextcloud/server/commit/9d613d049ed560f5ea22a20fafff26d0ebecde99.

@emoral435, do you have an insight on this?

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/45420
* Resolves: https://github.com/nextcloud/server/issues/42009

## Summary
A regression on the files library was causing issues on public shares where no user could be found to set the owner.
This is fixed in the library and just needs to be bumped here.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ShGKme — APPROVED** [review]
- Fixes https://github.com/nextcloud/server/issues/42009
- Smoke checked that everything works

**Comment by ShGKme** [comment]
No backport to stable27?

**Comment by susnux** [comment]
> No backport to stable27?

This is not possible. 27 depends on a beta version which had breaking changes.

**Review by Pytal — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
