### PR TITLE
[stable15] Reset and init new user form language

### PR DESCRIPTION
**Pull request by skjnldsv**
Backport of https://github.com/nextcloud/server/pull/16727

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
Failures are weird.
@ChristophWurst we encountered the weird node-sass building before, right?
https://drone.nextcloud.com/nextcloud/server/22683/2/3

**Comment by ChristophWurst** [comment]
Yep. It's then the Node version is too high for the sass versions.

**Comment by skjnldsv** [comment]
> Yep. It's then the Node version is too high for the sass versions.

though we're already using `node:lts` in drone :thinking:

**Comment by juliushaertl** [comment]
node:lts is node 12 but node-sass 4.10 is only compatible up to node 11, so we either need to bump node-sass or some older node version for stable15. I guess bumping node-sass makes more sense?

**Comment by juliushaertl** [comment]
Actually it was today when node lts was moved to 12: https://medium.com/@nodejs/node-js-12-to-lts-and-node-js-13-is-here-e28d6a4a2bd

**Comment by skjnldsv** [comment]
God dammit node!

**Comment by skjnldsv** [comment]
> /compile amend /

NC15 doesn't have a single package.json at the root :)
So the compile bot is not compatible ;)

**Pull request merged**
