### PR TITLE
Append / to data('path') for folder content request

### LINKED ISSUE #17283: Move / Copy - New Folder Created But Dialogue Stuck
**Server:** Debian 10
**PHP:** 7.3
**Browser:** Chrome
**Nextcloud:** 16.0.5

**Issue**
When moving / copying items, using the "new folder" option results in a soft freeze. After entering the new folder name and pressing the arrow to create it, the panel goes blank and just has the spinning icon. You have to navigate to a different folder within the move / copy dialogue and come back to where you just placed the new folder to see it, or you have to close the dialogue and re-try.

The folder is created correctly, it just doesn't refresh the view and show the updated folder tree or navigate into the new folder as expected.

Creating a folder:
image

Freezing:
image
image

This isn't a problem in the root folder, it works correctly there. It only gets stuck when in a sub-folder.

I assumed it was due to the "&", but it happened in another folder with a single word name too.

**Expected Behaviour**
New folder is created and either the view refreshes to show it in the list, or you enter the new folder for selection.

### PR DESCRIPTION
**Pull request by kesselb**
Close #17283

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Makes sense

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Backports in https://github.com/nextcloud/server/pull/17310 and https://github.com/nextcloud/server/pull/17311

**Comment by kesselb** [comment]
> Backports in #17310 and #17311

:rocket:

**Comment by a1pilot** [comment]
@skjnldsv Do I need to do anything to get a backport update, or is it just in the next release?

**Comment by skjnldsv** [comment]
@a1pilot what do you mean?
How to create the backports pull request?

**Comment by a1pilot** [comment]
@skjnldsv I have version 16.0.5 now. Do I get the backported changes in the next update, or do I need to do something to get them?

**Comment by skjnldsv** [comment]
Next update, 16.0.5 have been released before this backport :)

**Comment by skjnldsv** [comment]
You can see the milestone in the bottom right of the backport pull request
https://github.com/nextcloud/server/pull/17310

**Comment by a1pilot** [comment]
@skjnldsv Thanks.

**Pull request merged**
