### PR TITLE
Trashbin: Delete => Delete permanently

### PR DESCRIPTION
**Pull request by rullzer**
For #14639

However it seems the gridview has a limited size for the menu...

delperm_grid

And the name overlays the restore icon

### CODE REVIEW

**Comment by skjnldsv** [comment]
> And the name overlays the restore icon

You need #14695 and then add a css exception for the grid view mode to show the menu entry and hide the outside ones :)
@jancborchardt maybe we could create a global css rule to hide every action outside the menu in grid?
Instead of specific ones :thinking:

**Comment by jancborchardt** [comment]
> However it seems the gridview has a limited size for the menu

Yes, this is intentionally set to the width of the grid as otherwise it looks off. We could make it wider, but it should be centered below the element.


@skjnldsv yep, good point about the standard rule! Needs to happen in the JS, does it?

**Review by jancborchardt — APPROVED** [review]
:+1:

**Comment by rullzer** [comment]
All fine by me. But indeed let's fix that all separately

**Comment by skjnldsv** [comment]
> Needs to happen in the JS, does it?

No, css only :)

**Comment by jancborchardt** [comment]
So, second thumbs up on this as first step? ;)

**Review by ChristophWurst — APPROVED** [review]
:+1:

**Pull request merged**
