### PR TITLE
Respect exit code of lint run - changed from -exec to xargs as this exits properly

### PR DESCRIPTION
**Pull request by MorrisJobke**
Found while debugging #20951

So this one will fail for now until #20951 is merged. Then I will rebase.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
rebase time!

**Comment by MorrisJobke** [comment]
> rebase time!

Already done ... now there are errors 🙈

**Review by georgehrke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Stable 16-18 don't need this.

**Comment by gary-kim** [comment]
Oh fun. I'll merge it into my app as well. Thanks!

**Pull request merged**
