### PR TITLE
fix styling of development-notice

### LINKED ISSUE #42642: [BITV]: hover contrasts on links are not ok
Screenshot from 2024-01-08 17-48-19

Dark theme on index.php/settings/user

`Nextcloud community`, `source code`, `AGPL` links.

Create instead another links like

Screenshot from 2024-01-08 17-52-02

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/42642

### Before

https://github.com/nextcloud/server/assets/42591237/188e609f-bbcb-4423-9945-dd9cdb69143c

### After

https://github.com/nextcloud/server/assets/42591237/10c8c822-656e-4360-b311-f2752b0eada7

<details>
<summary>For my own testing</summary>

```
docker run -it --rm ^
--name nextcloud-easy-test ^
-p 8443:443 ^
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" ^
-e SERVER_BRANCH=enh/42642/fix-development-notice-styling ^
-e COMPILE_SERVER=1 ^
-e VIEWER_BRANCH=master ^
ghcr.io/szaimen/nextcloud-easy-test:latest

```

</details>

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
should we fix the icon? Probably missing `filter: var(--primary-invert-if-dark)` (or similar)

**Review by emoral435 — APPROVED** [review]
Looks great!

**Comment by szaimen** [comment]
/backport 500471881b7deb4ffdd7d99e7ff930c4e0c53d42 to stable28

**Comment by szaimen** [comment]
/backport cf1726723a4839b18986d8d23dee65ed66c9bb7a to stable28

**Pull request merged**
