### PR TITLE
Remove the matching on ancient /ocs routes

### PR DESCRIPTION
**Pull request by rullzer**
The appframework has been the default for quite some time now. So time
to take proper advantage of it.

Should shave off matching and loading some routes. Should help with response times for OCS routes.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@kesselb Any idea about those random Psalm failures?

**Comment by danxuliu** [comment]
Note that before this pull request `OC_App::loadApps()` was called before `OC::handleLogin`, but now it is called after it. This has caused Talk to no longer create room shares in the _Talk_ folder in some cases.

It seems that [`VerifyMountPointEvent`](https://github.com/nextcloud/server/blob/2a054e6c04e0a40421510eb889cbf59f153c5177/apps/files_sharing/lib/SharedMount.php#L96) is no longer [handled in Talk](https://github.com/nextcloud/spreed/blob/b3ebce7a25451bc2645ccde222bab8ae742a4eab/lib/Share/Listener.php#L39) if a share information is got when the sharee is not logged in. For example, if the share information is got through OCS, like done in the sharing integration tests: https://drone.nextcloud.com/nextcloud/spreed/10104/12/3.

It can also be reproduced in a real instance:
- Log in as user A
- Open Talk
- Create a conversation and add user B
- Share a file to that conversation
- Get the ID of the share
- In a console, get the share information as user B with something like `curl -u {userB}:{password} -X GET -H "OCS-APIRequest: true" "http://127.0.0.1:8000/ocs/v2.php/apps/files_sharing/api/v1/shares/{shareId}`

If user B now logs in the shared file will be in the root instead of in the _Talk_ folder. However, if now, while user B is logged in, user A shares another file in the conversation and user B reloads the Files app the new shared file will be in the _Talk_ folder of user B.

**Comment by PVince81** [comment]
The tests in Talk are broken on master, see https://github.com/nextcloud/spreed/issues/4736.

It likely makes more sense to load the apps before handling login, because some apps might do stuff at that time.

**Comment by rullzer** [comment]
Let's revert this then and try to fix it better in 22

**Comment by PVince81** [comment]
it might be enough to move loadApps() to the top to not change the initialization order

I tried automatic revert and it failed, will need to do manually

**Comment by PVince81** [comment]
here's a PR that just changes the order: https://github.com/nextcloud/server/pull/24628

I guess in the future if we want to fix the order we might need to make it a v3.php and allow enough time for apps to migrate...

**Pull request merged**
