### PR TITLE
delete the --image-background-size variable

### PR DESCRIPTION
**Pull request by szaimen**
Address https://github.com/nextcloud/firstrunwizard/pull/789#discussion_r1036477355

Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Review by skjnldsv — COMMENTED** [review]
The entire block can be removed then
```diff 
- if ($image === 'background') {
- 	// If background deleted is set, ignoring variable
- 	if ($backgroundDeleted) {
- 		continue;
- 	}
- }
```

**Comment by juliushaertl** [comment]
> The entire block can be removed then

Isn't it still relevant for the background image url below?

**Comment by skjnldsv** [comment]
No, it was onl there because of the apps icons gradient being applied as well as the primary.
Now that we only have full-screen images or not at all, we don't need different background sizes

**Comment by szaimen** [comment]
> The entire block can be removed then
> 
> ```diff
> - if ($image === 'background') {
> - 	// If background deleted is set, ignoring variable
> - 	if ($backgroundDeleted) {
> - 		continue;
> - 	}
> - }
> ```

done 👍

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
