### PR TITLE
Upload autorename on client side

### PR DESCRIPTION
**Pull request by MorrisJobke**
Removes the need for POST to collection which would hit against upload
limits.

The client tries to auto rename the file by adding a suffix "(2)".
It tries to use the file list on the client side to guess a
suitable name. In case a file still cannot be uploaded and creates a
conflict, which can happen when the file was concurrently uploaded, the
logic will continue increasing the suffix.

Downstreams https://github.com/owncloud/core/pull/26078

cc @rullzer @icewind1991

### CODE REVIEW

**Comment by rullzer** [comment]
@icewind1991 this should make you happy I think ;)

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen @icewind1991 @ChristophWurst Please review :)

**Comment by rullzer** [comment]
LGTM!

**Comment by MorrisJobke** [comment]
I tested this too and it works 👍 

The failing test is the sign off check -> merge

**Pull request merged**
