### PR TITLE
No longer add trusted servers on federated share creation

### PR DESCRIPTION
**Pull request by rullzer**
It was disabled by default for ages. And often resulted in unwanted
behavior. If admins want trusted servers they just have to do it
manually.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Yep - makes sense 👍  Thanks for the cleanup 🧹

**Pull request merged**
