### PR TITLE
Master is now 30

### PR DESCRIPTION
**Pull request by nickvergessen**
# ⚠️ To be merged only

- [x] After stable29 creation
- [x] By release manager: @skjnldsv

## Todos

possible "up front"

- [ ] https://github.com/nextcloud/docker-ci/pull/650
- [ ] https://github.com/nextcloud/.github/pull/418

---

"live"

- [x] `.github/dependabot.yml`
  - [x] Add a new section about the new `stableY` branch
- [x] `.github/workflows/update-cacert-bundle.yml`
  - [x] Adjust backport list of cacert automation to include `stableY`
- [x] `.github/workflows/update-code-signing-crl.yml
  - [x] Adjust backport list of cacert automation to include `stableY`
- [x] `.github/workflows/update-psalm-baseline.yml`
  - [x] Adjust backport list of psalm automation to include `stableY`
- [x]  `.github/workflows/npm-audit-fix.yml`
  - [x] Adjust backport list of psalm automation to include `stableY`
- [x] `apps/settings/lib/WellKnown/SecurityTxtHandler.php`
  - [x] Bump `Expires` date to be 5 months in the future
  - [x] Trigger the backport bot for all still supported versions
- [x] `version.php`
  - [x] Increase the major version in `$OC_Version` and 0-ify the other digits
  - [x] Set `$OC_VersionString` to `Major.0.0 dev`
  - [x] Add the newest major to `$OC_VersionCanBeUpgradedFrom`
  - [x] Remove the oldest major to `$OC_VersionCanBeUpgradedFrom`
- [x] `apps/*/appinfo/info.xml`
  - [x] Update Minor version of all apps and 0ify the patch version
  - [x] Bump version requirement to the new Major
- [x] Rebuilt frontend `npm ci && npm run build`
- [x] Fix other apps on stable branch:
    - [x] Create stable branch in https://github.com/nextcloud-deps/ocp
    - [x] Add stable branch to cron: https://github.com/nextcloud-deps/ocp/pull/21
    - [x] Adjust version on stable29 https://github.com/nextcloud-deps/ocp/pull/22
    - [x] Run the cron 
- [x] Branch-off the stable29 branch in all affected apps, before sending this PR
    - [x] https://github.com/nextcloud/server/pull/44531
- [x] https://github.com/nextcloud/3rdparty/pull/1768

### CODE REVIEW

**Comment by nickvergessen** [comment]
/backport b08563df3209b234948271a912a4d233ae1aa974 to stable29

**Comment by nickvergessen** [comment]
/backport b08563df3209b234948271a912a4d233ae1aa974 to stable28

**Comment by nickvergessen** [comment]
/backport b08563df3209b234948271a912a4d233ae1aa974 to stable27

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
/backport b08563df3209b234948271a912a4d233ae1aa974 to stable29

**Pull request merged**
