### PR TITLE
Added Hooks CardDavBackend

### PR DESCRIPTION
**Pull request by tacruc**
Addressing the disscussions:
#14971
nextcloud/contacts#211

### CODE REVIEW

**Comment by rullzer** [comment]
I'd much rather emit proper events with the event dispatcher... @MorrisJobke @ChristophWurst

**Comment by tacruc** [comment]
@rullzer I'm fine with it, as long I can connect to them with an app. Is there somewhere a documentation how this would work. In the app documentation only Hooks are mentioned for this.

**Comment by georgehrke** [comment]
@rullzer Event dispatcher are already in place: https://github.com/nextcloud/server/pull/14973/files#diff-cec75d1f60809c8d36dd837cfdc60531L645

They are used by the activity app.

**Comment by georgehrke** [comment]
@tacruc please check https://github.com/nextcloud/server/blob/ec5f4200ad402a7ee9fc68c677c6cea8d4437052/apps/dav/lib/AppInfo/Application.php :) 

You have to get the event dispatcher: https://github.com/nextcloud/server/blob/ec5f4200ad402a7ee9fc68c677c6cea8d4437052/apps/dav/lib/AppInfo/Application.php#L103

and simply add a listener like here: https://github.com/nextcloud/server/blob/ec5f4200ad402a7ee9fc68c677c6cea8d4437052/apps/dav/lib/AppInfo/Application.php#L127L136

Do you have a use-case for the `preDelete`, `preUpdate`, and `preCreate` hooks? If not, i would go ahead and close this pull-request if you don't mind.

**Review by georgehrke — CHANGES_REQUESTED** [review]
👎 Event-dispatcher is already in place. No need for hooks

**Comment by tacruc** [comment]
@georgehrke thanks for the hint how to use the Event dispatcher. I was somehow focused on Hooks. I will have a look and close this for now.

**Comment by tacruc** [comment]
@georgehrke  thank's for the hint again, I now implemented everything and it worked out.  :+1:

**Pull request closed without merging**
