### PR TITLE
Use sabre function directly rather than duplicating it

### PR DESCRIPTION
**Pull request by come-nc**
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by come-nc** [comment]
@CarlSchwan Do you know how I can import the function from Sabre? It seems the autoloader can’t find it.

**Comment by come-nc** [comment]
The point is to fix https://github.com/nextcloud/server/issues/31212
I opened a bug on sabre side: https://github.com/sabre-io/http/issues/181
Using their function would avoid having to fix it on our side.

We can also fix it on our side and hope it will be enough, I do not know if our code goes through the sabre function or not, if we fix on our side it may fix it in UI but not through dav or something.

**Comment by PVince81** [comment]
I've updated the psalm baseline for the new entry

**Review by CarlSchwan — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Pull request merged**
