### PR TITLE
Merge similar properties and standardize the arrow to the menu class

### PR DESCRIPTION
**Pull request by skjnldsv**
1. set the menu class
2. define the position of the :after element

~~fix~~ ref #3274

capture d ecran_2017-01-26_15-58-48 capture d ecran_2017-01-26_15-58-54 capture d ecran_2017-01-26_15-59-02

@nextcloud/designers

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works - but doesn't fix #3274 entirely (because the PR from the notification repo is needed as well;))

**Comment by skjnldsv** [comment]
You're right. This is a split pr! :)

**Review by ChristophWurst — APPROVED** [review]
looks good!

**Comment by ChristophWurst** [comment]
Failing CI run seems unrelated

**Comment by skjnldsv** [comment]
Restarted the test

**Pull request merged**
