### PR TITLE
Add migration for oc_share_external columns

### PR DESCRIPTION
**Pull request by PVince81**
- [x] TEST: regular install
- [x] TEST: migrate from NC 21.0.0beta2
- [x] TEST: migrate from v20.0.4
- [x] TEST: on my own server

Partial fix for https://github.com/nextcloud/server/issues/24813

### CODE REVIEW

**Comment by PVince81** [comment]
yeah, so I had this locally as well and double checked everything, class name, file name, etc.
but have no clue what's wrong...
```
Migration step 'OCA\Files_Sharing\Migration\Version21000Date20201223143245' is unknown
```

**Comment by PVince81** [comment]
- [ ] BUG: can't drop assignable without also dropping/recreating the index

**Comment by PVince81** [comment]
I decided to discard the change about the assignable column for now. Solving it will need more gymnastics as it will need to adjust the index (possibly in the occ command) and only then we can drop the column.

**Comment by PVince81** [comment]
ouch, I redid a diff and:
- [ ] share_type is missing too

**Comment by PVince81** [comment]
Unrelated fails:
```
1) Test\Files\ViewTest::testRenameFailDeleteTargetKeepSource
Trying to configure method "writeStream" which cannot be configured because it does not exist, has not been specified, is final, or is static

2) Test\Files\ViewTest::testCopyFailDeleteTargetKeepSource
Trying to configure method "writeStream" which cannot be configured because it does not exist, has not been specified, is final, or is static
```


the failing acceptance test also seems unrelated:
```
  Scenario: users navigation without disabled users                                   # /drone/src/tests/acceptance/features/users.feature:47
    Given I act as Jane                                                               # ActorContext::iActAs()
    And I am logged in as the admin                                                   # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the User settings                                                      # SettingsMenuContext::iOpenTheUserSettings()
    And I open the "Disabled users" section                                           # AppNavigationContext::iOpenTheSection()
    And I see that the list of users contains the user disabledUser                   # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
    And I open the actions menu for the user disabledUser                             # UsersSettingsContext::iOpenTheActionsMenuOf()
      Row for user disabledUser in Users Settings could not be found
      Actions menu for user disabledUser in Users Settings could not be found (NoSuchElementException)
```

**Review by rullzer — APPROVED** [review]
:elephant:

**Review by juliusknorr — APPROVED** [review]
Tested and works :+1:

**Pull request merged**
