### PR TITLE
dispatch NodeAddedToCache and FileCacheUpdated event during file upload

### PR DESCRIPTION
**Pull request by dassio**
@icewind1991  please help to review

### CODE REVIEW

**Comment by rullzer** [comment]
Why would you need this actually?

**Comment by dassio** [comment]
> Why would you need this actually?

I am trying to write a storage wrapper, during the upload process, i will extract the metadata after the upload finished i want to update the metadata table with correct  fileid(duiing the upload the fileid has not created yet)

i see that we have hooks, but it seems we are moving away from hook, and try to use event

**Comment by skjnldsv** [comment]
@dassio I guess this is not needed anymore?

**Comment by ChristophWurst** [comment]
closing due to lack of activity

**Pull request closed without merging**
