### PR TITLE
fix(settings): Fix sharing exclude groups from password requirement option not working

### LINKED ISSUE #47569: [Bug]: "Exclude groups from password requirements" setting not saved
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After setting `  'sharing.allow_disabled_password_enforcement_groups' => true,` in `config.php`, the "Exclude groups from password requirements" select shows up as expected. But when I enter a group there, it's not really saved. After reloading, set groups disappear. Also, the setting doesn't work as the groups are not actually excluded. 

## Video of the problem:

https://github.com/user-attachments/assets/4f8c3ff0-5c26-4a97-b4aa-a1650e503296

cc: @susnux , since you recently edited this. 

### Steps to reproduce

1. `'sharing.allow_disabled_password_enforcement_groups' => true,` in `config.php`
2. Visit /settings/admin/sharing
3. Enter groups in the "Exclude groups from password requirements"

### Expected behavior

The groups should be saved and visible after reloading. Plus, the groups should be excluded from the password requirement. 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

I checked the requests, and see the request is made and claims to be successful. But apparently not? 

192.xxx.xx.x - - [28/Aug/2024:12:21:58 +0000] "POST /ocs/v2.php/apps/provisioning_api/api/v1/config/apps/core/shareapi_password_excluded_groups HTTP/1.1" 200 935 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"

### PR DESCRIPTION
**Pull request by provokateurin**
* Resolves: https://github.com/nextcloud/server/issues/47569

## Summary

In the backend the appconfig key is `shareapi_enforce_links_password_excluded_groups`. The key in the initial state needs to match this as it is used to save the config.
To the user it looked like the option wasn't saved because a reload would not show the saved data because it was read from a different key than it was written to.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
:+1: 

...This settings are pure horror to me, maybe this is something that should be done as declarative settings...

**Comment by provokateurin** [comment]
True, that would prevent bugs like these. Unfortunately there is still not proper type-safe PHP abstraction available, but it shouldn't be too hard to create.

**Comment by provokateurin** [comment]
Created https://github.com/nextcloud/server/issues/47688 :)

**Review by artonge — APPROVED** [review]

**Review by nfebe — APPROVED** [review]

**Pull request merged**
