### PR TITLE
[stable23] Add share search tweaks

### PR DESCRIPTION
**Pull request by artonge**
Grouped backport of

- https://github.com/nextcloud/server/pull/31857
- https://github.com/nextcloud/server/pull/31927
- https://github.com/nextcloud/server/pull/31932
- https://github.com/nextcloud/server/pull/31964
- https://github.com/nextcloud/server/pull/31963
- https://github.com/nextcloud/calendar/pull/4198

### CODE REVIEW

**Comment by blizzz** [comment]
@artonge conflicts

**Comment by blizzz** [comment]
moving to 23.0.6 for lack of reviews

**Comment by blizzz** [comment]
moving to 23.0.7

**Review by CarlSchwan — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Pull request merged**
