### PR TITLE
Move personal settings to css grid layout

### LINKED ISSUE #3654: Text-box break for Federation fields on personal page
On iPad with 9.7 inch for example (Pro and Air series) the Personal settings looks strange, since there is a break after every text box - but in my naive way of going trough life, I think there would be enough place putting 2 in one row in this case ... this is only one use-case where this is behaving "creative" since the introuducing of the Federation Items with Nextcloud 11, but 
unknown-3

@schiessle 

...and of course the text "Für Passwort Wiederherstellungen und Benachrichtigungen" which makes many noise for German users and some browsers 🙄😜

### PR DESCRIPTION
**Pull request by juliusknorr**
This PR aims to make the personal settings page make proper use of the available space and behave better on different screen sizes.

@nextcloud/designers 

image
image
image
image

Also fixes https://github.com/nextcloud/server/issues/3654

### CODE REVIEW

**Comment by skjnldsv** [comment]
YES!! 10 thousand time yes! :D 
I'll review it after breakfast :D

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍 

In Edge and IE it behaves for all screen sizes as a one column grid. But this should be fine for the personal page.

**Review by skjnldsv — APPROVED** [review]
Meep meep  :bullettrain_front::train::train::train::train:

**Comment by jancborchardt** [comment]
@juliushaertl just saw this, sorry. This change makes it very apparent that the visibility switcher (Private, Contacts, Public) of the fields needs to not be right-aligned but right next to the text instead. Currently it is too far away. Also, the profile picture block should be left-aligned.

And for profile picture, either the title and the "png or jpg …" notice should also be centered, or the content should be left-aligned.

**Comment by juliushaertl** [comment]
@jancborchardt Good points. I'll do that in a follow up pr.

**Comment by MorrisJobke** [comment]
Just want to let you know - this is not fully supported in Edge/IE and thus it is full with for all entries:

bildschirmfoto 2018-05-03 um 10 35 02

**Comment by juliushaertl** [comment]
@MorrisJobke https://github.com/nextcloud/server/pull/9218#pullrequestreview-113112186

We could support IE with some additional vendor prefixed rules, not sure if it is worth the work here.

**Pull request merged**
