### PR TITLE
Fix popover layout

### PR DESCRIPTION
**Pull request by skjnldsv**
Somehow the various popover layouts broke appart.
My guess is the cleanup we did on various part of the css which may have influenced this.

I also added support for radio since we also support checkboxes after #6976.

Please tests from various locations. Example:
- Privacy menu in user details
- Session list
- Calendar menu
- ....

| Before | After |
|:---:|:---:|
|kazam_screenshot_00005|kazam_screenshot_00004|

Test template: [templatetest.tar.gz](https://github.com/nextcloud/server/files/1443188/templatetest.tar.gz)

@nextcloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Popup in the files table is now a bit to low:

bildschirmfoto 2017-11-07 um 09 28 15

**Comment by MorrisJobke** [comment]
Sharing looks a bit unordered (icons/checkboxes are not in line) and the margin per line is too high.

bildschirmfoto 2017-11-07 um 09 29 30

**Comment by skjnldsv** [comment]
Thanks will fix when home from work! 👌

**Comment by skjnldsv** [comment]
@MorrisJobke All fixed. Please check again :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by skjnldsv** [comment]
@nextcloud/designers bump! :)
@jancborchardt 💟

**Review by rullzer — APPROVED** [review]
looks good

**Pull request merged**
