### PR TITLE
Fix video verification tests

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by danxuliu — COMMENTED** [review]
This should have worked, but the integration tests still fail. Maybe something was wrongly cached (by Drone, I mean)? :thinking:

**Comment by nickvergessen** [comment]
I changed the target branch of the PR maybe that screwed something over

**Review by danxuliu — APPROVED** [review]
> I changed the target branch of the PR maybe that screwed something over

Could be :shrug: Anyway I run the test locally and it passes with server and Talk both on _stable23_, so :+1:

**Comment by nickvergessen** [comment]
Drone says:
>Fix video verification tests
> nickvergessen opened pull request #29673 to master

So yeah, making a new PR

**Pull request closed without merging**
