### PR TITLE
Add new recommended 18 apps

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by kesselb** [comment]
OnlyOffice needs an external service. Why make it a recommended app? I would expect from a recommended app that no other services / additional setup required.

**Comment by gary-kim** [comment]
> OnlyOffice needs an external service. Why make it a recommended app? I would expect from a recommended app that no other services / additional setup required.

Well, I guess that question is answered now. I was really confused as well.

**Comment by kesselb** [comment]
> Well, I guess that question is answered now

Do I have to watch the announcement to understand that? :confused:

**Comment by ChristophWurst** [comment]
There is a new app in the app store. It's a document server written in php. So you can actually use OO now without running the external service on smaller instances.

**Comment by kesselb** [comment]
Thanks @ChristophWurst :+1: I'll hide my post as off topic :see_no_evil:

**Comment by kesselb** [comment]
Serious question: Has anyone of you tested this? :smile: 

Here are some reports about timeout issues: https://github.com/nextcloud/documentserver_community/issues/11

AppFetcher has a default value of 10 seconds. How do you think this is going to work?

**Comment by jancborchardt** [comment]
@kesselb we have similar issue with Maps app updates getting timeouts now that it’s 25 MB. Would increasing AppFetcher work to fix that, and work across server setups?

**Comment by kesselb** [comment]
> @kesselb we have similar issue with Maps app updates getting timeouts now that it’s 25 MB. Would increasing AppFetcher work to fix that, and work across server setups?

Perhaps for the maps app if the connection is fast enough. Documentserver is around 300mb. That's not possible with 10 seconds (in theory it is but only if the connection is fast enough and the connectivity between the server and github is good).

I'm puzzled that you are (not you in person but the organization) announcing such a feature (documentserver will be installed by default) without testing it before. This is not going to work this way. 

At least there is now an issue for that: https://github.com/nextcloud/server/issues/18999

**Comment by ChristophWurst** [comment]
Maps fails on extraction, not on download. And they should just use a bundler instead of shipping all of `node_modules`.

The download was tested. But apparently with systems with a fast connection.

I guess we could dispatch a background job for an async installation.

**Comment by jancborchardt** [comment]
> I'm puzzled that you (not you in person but the organization) are announcing such a feature (documentserver will be installed by default) without testing it before. This is not going to work this way.

As Christoph said it was tested but only internally, so not all cases were caught. We also had to balance not leaking the big announcement before. :)

It’s a learning to test not only on ideal setups for sure, as we always should do.

**Pull request closed without merging**
