### PR TITLE
[3rdparty] Static classmap for 3rdparty

### PR DESCRIPTION
**Pull request by rullzer**
This speedsup classmap loading significantly on php 5.6 and higher.
Older php versions are not affected.

Lets see how CI feels

Requires https://github.com/nextcloud/3rdparty/pull/4

### CODE REVIEW

**Comment by LukasReschke** [comment]
Any Blackfire comparison for the autoloader itself? ;)

**Comment by rullzer** [comment]
> Any Blackfire comparison for the autoloader itself? ;)

I have to wait for my new laptop for that to redo them....

**Comment by rullzer** [comment]
Rebased to have 5.4, 5.5, 5.6 and 7.0 unit tests running...

**Comment by rullzer** [comment]
@LukasReschke see https://blackfire.io/profiles/compare/3a2a4c5a-25b1-4cd1-a2d0-10211cc0afb0/graph

Take a look at the CPU time saved. That is more interesting than the I/O wait since that is just random noise.

**Comment by LukasReschke** [comment]
LGTM 👍

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Rebased to get latest 3rdparty submodule ;)

**Pull request merged**
