### PR TITLE
Allow to hide download option for folders shared by link

### PR DESCRIPTION
**Pull request by juliusknorr**
- Enable "Hide download" share option for folders
- Remove file selection and download option
- Remove file action to download

Files we cannot display inline will still be downloaded. Right-clicking and opening the file in a new tab will also still cause the file to be downloaded.

### CODE REVIEW

**Comment by juliushaertl** [comment]
Companion PR to remove the download button from the gallery app slideshow: https://github.com/nextcloud/gallery/pull/484

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — COMMENTED** [review]
Tested and works, but I see some unexpected  whitespace on the right:

bildschirmfoto von 2018-11-20 10-31-14

**Comment by MorrisJobke** [comment]
> Tested and works, but I see some unexpected whitespace on the right:

Same here - is not there on master.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
JSUnit test fails:

```
PhantomJS 2.1.1 (Linux 0.0.0) OC.Share.ShareDialogLinkShareView hide download is not shown if the share is a folder FAILED
	Expected 1 to be falsy.
	core/js/tests/specs/sharedialoglinkshareview.js:117:50
```

**Comment by juliushaertl** [comment]
@MorrisJobke Fixed as well https://drone.nextcloud.com/nextcloud/server/12857/287

**Comment by MorrisJobke** [comment]
Conflicts 🙈

**Pull request merged**
