### PR TITLE
Use clearer name setUpScenario

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #3558 
The name tearUpScenario was confusing when I was looking at how some existing tests were set up. In English, "tear up" is what you do with a printed contract when you do not like it! It is a destructive thing.

Rename it to setUpScenario

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Makes sense! Thanks!

**Review by nickvergessen — APPROVED** [review]

**Comment by phil-davis** [comment]
Matching change in ownCloud https://github.com/owncloud/core/pull/27189 also

**Comment by phil-davis** [comment]
CI drone pr failure:
```
Some commits were not signed off!
Missing signatures on:
- b801ca4f35492b91916e20560fa79b676c994e46
Build has failed
```
what is that all about?

**Comment by ChristophWurst** [comment]
Please see https://github.com/nextcloud/server#contribution-guidelines. We require all commits to this repository to be signed (using `git commit -s …`).

**Comment by phil-davis** [comment]
This is not going to work like this. Resubmitted as #3566

**Pull request closed without merging**
