### PR TITLE
adviced should be advised

### PR DESCRIPTION
**Pull request by kotp**

### CODE REVIEW

**Comment by gary-kim** [comment]
You seem to have edited the translation files directly. Those files get updated automatically when you add or change translations in the code. Could you drop all the changes other then the ones to `core/js` files?

**Comment by kotp** [comment]
Sure, I wondered about that.

**Review by gary-kim — CHANGES_REQUESTED** [review]
I think you dropped your changes to the `.js` files that were using the translation. Could you put back the changes that were made to the files outside `core/l10n` and drop the changes to all the files in `core/l10n`?

Also, could you add a [DCO](https://github.com/nextcloud/server/blob/master/contribute/developer-certificate-of-origin) to your commit? The easiest way would be to add the `-s` flag from the command line. You can also add the following to the bottom of your commit message.
```
Signed-off-by: Random J Developer <random@developer.example.org>
```

**Comment by kotp** [comment]
I finally realized your desire to make only changes to `core/js` folder.

**Comment by gary-kim** [comment]
Sorry I didn't make that clear. My bad.

**Review by gary-kim — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Pull request merged**
