### PR TITLE
Move install scripts to a bundle

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes broken installation due to a [missing global `getURLParameter`](https://github.com/nextcloud/server/commit/bb1d8b318964b5b778e4c381db2f9ff281164384#diff-5573ace4a9317c80af53e68f60114575L137)

- Move install scripts to a bundle
- Get rid of most global usages
- Reduce loaded scripts on install page

The main bundle is still required to be loaded since our translation handling is still to tightly coupled with the global OC object.

### CODE REVIEW

**Comment by rullzer** [comment]
Awesome.
Lets also createa an issue to move this to vue sooner rather than later.
Since getting rid of jquery (or at least the current version) is also still on the todo

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by danxuliu** [comment]
I am late to the party, but:
- As _core/js/setup.js_ was removed I guess that [`\OC_Util::addScript('setup');`](https://github.com/nextcloud/server/blob/302558cfd2b3dd37e6332c0d9c650174b64f20fb/core/Controller/SetupController.php#L108) can be removed too.
- Although the bar with the strength of the admin password is still shown below the input field the tooltip with the texts _Very weak password_, _Weak password_... is not shown anymore.

**Comment by rullzer** [comment]
I think that last one was broken for some time no not?

**Comment by danxuliu** [comment]
Maybe it was fixed recently, I do not know, but I have checked and it works on the parent commit of a5b0f41a9ffc.

**Pull request merged**
