### PR TITLE
Fix small glitches in update notification page

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fix border in update notification admin settings
* fix warning for eol version in update notification admin settings

Before:

bildschirmfoto 2019-02-13 um 14 00 17
bildschirmfoto 2019-02-13 um 14 04 47

After:

bildschirmfoto 2019-02-13 um 14 00 31
bildschirmfoto 2019-02-13 um 14 04 15

### CODE REVIEW

**Comment by MorrisJobke** [comment]
The warning was back ported to stable15 and 14 - see #13664

**Review by ChristophWurst — APPROVED** [review]
Looks great!

**Review by skjnldsv — APPROVED** [review]
Yes! :)

**Comment by MorrisJobke** [comment]
Backports are in #14205 and #14207

**Pull request merged**
