### PR TITLE
Handle device login like an alternative login

### PR DESCRIPTION
**Pull request by nickvergessen**
New+old without a alternative login | Old with alt. login | New with alt. login
---|---|---
It's okay | "Login with a device" looks like a caption to the registration option | Now it looks like an alternate login, which it is. Ignore the color change on the registration button.
Bildschirmfoto von 2021-04-16 11-00-49 | Bildschirmfoto von 2021-04-16 11-06-02 | Bildschirmfoto von 2021-04-16 10-59-29

Rel #26349

### CODE REVIEW

**Comment by jotoeri** [comment]
👍 ...how about additionally moving the 'forgot password' upwards, closer to the login button? These are semantically connected, while the others are different things? 🤔

**Comment by nickvergessen** [comment]
Well there are many opinions in https://github.com/nextcloud/server/issues/26349 which is why i dont want to resolve this atm, until a design decision was made, wther it would maybe even go up above the login button e.g.

**Comment by rullzer** [comment]
Why are the buttons all of a sudden blue in your screenshot?

**Review by marcoambrosini — COMMENTED** [review]
I'm a bit confused by the colors, shouldn't the login button be the primary one?

**Comment by nickvergessen** [comment]
Because guest.css is not scss and can't be as it's used for error pages. Login button is colored via vue.

As said ignore the registration app color change, it is/was setting it's own color before. Any other alt_login that registered was always blue

**Review by marcoambrosini — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Makes more sense indeed.

Agree with the remark that the "Forgot password" should be closer to the "Log in" button. Also – the buttons for the alternative login options should maybe be a bit smaller than the main "Log in" button? But yeah, separate.

**Comment by acsfer** [comment]
If "Log in" and "Log in with a device" are bot Login methods, shouldn't they be grouped and distinguished from Register?

image

**Comment by nickvergessen** [comment]
> If "Log in" and "Log in with a device" are bot Login methods, shouldn't they be grouped and distinguished from Register?

Well Register might be an exception. But the API is called "alternative login methods" 
Other apps that use it are e.g.:
https://apps.nextcloud.com/apps/sociallogin
https://apps.nextcloud.com/apps/oidc_login

for them it makes more sense to be combined with "login with a device"

**Comment by bes1002t** [comment]
I agree with @acsfer, the user is not interested in implementation details. The user is parsing both buttons as login buttons and not grouping them is somehow causing a bad feeling.

as mentioned several times before, in a future version it would be good to have the "Forgot password" string next to the password input.

**Comment by nickvergessen** [comment]
Yes there is still #26349 to deal with that

**Pull request merged**
