### PR TITLE
fix(files): Fix file names alignment in Files List in UI RTL mode.

### LINKED ISSUE #48902: [Bug]: File names incorrect alignment in UI RTL mode.
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello everyone,

There is a minor bug in the newly introduced UI RTL mode for languages such as Arabic and Persian. When switching the UI language to Arabic, file names in Arabic are properly aligned to the right, but non-Arabic file names remain aligned to the left. Although the names are readable, this alignment doesn't align with expectations for a fully RTL-supported interface.

Image

### Steps to reproduce

1. Switch Nextcloud UI interface to non-Latin languages. More specifically, switch to languages with RTL mode such as Arabic or Persian.
2. Go to the file app.

### Expected behavior

Right align all file names in RTL mode. 

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by falghamdi125**
* Resolves: #48902 

## Summary
This PR fixes the alignment of file names in RTL mode.

Before:
image

After:
image
The PR doesn't break non-RTL UI  (English below)
image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
@falghamdi125 can you compile with `npm run build` please?
I cannot push here as you used `master` as branch name I think

**Comment by falghamdi125** [comment]
Files assets have been compiled!

**Comment by falghamdi125** [comment]
You may reopen the PR and update source to this branch:
`https://github.com/falghamdi125/server/commits/fix-files-names-align-in-rtl`

**Comment by susnux** [comment]
@falghamdi125 could you please open a PR from that branch?

**Pull request closed without merging**
