### PR TITLE
Fix backgroundjobs mode radio

### PR DESCRIPTION
**Pull request by kesselb**
Radio input's for background jobs mode (ajax, webcron, cron) do not work anymore for main and stable24.

image

Change event works but `$(_this).is(':checked')` is always false. It's related to the arrow syntax and lexical this binding. 

Helpful reading:  https://stackoverflow.com/questions/27670401/using-jquery-this-with-es6-arrow-functions-lexical-this-binding

### CODE REVIEW

**Comment by Pytal** [comment]
It seems that https://github.com/nextcloud/server/pull/32443 supersedes this one @CarlSchwan?

**Comment by CarlSchwan** [comment]
> It seems that #32443 supersedes this one @CarlSchwan?

We still need a fix for stable24

**Review by CarlSchwan — APPROVED** [review]

**Comment by kesselb** [comment]
> It seems that https://github.com/nextcloud/server/pull/32443 supersedes this one @CarlSchwan?

Nice :tada: 

> We still need a fix for stable24

OK! I will rebase the branch to stable24, recompile and delete the backport request.

**Pull request closed without merging**
