### PR TITLE
Change color of displayname and ellipsis status message

### PR DESCRIPTION
**Pull request by georgehrke**
Signed-off-by: Georg Ehrke <developer@georgehrke.com>
| Before | After |
|:---------:|:------:|
|8C59817F-ADDD-4EE0-A5AD-D6A08911E4C0|BFBE6BA4-F93F-43A0-BC05-892BD76617DD|

### CODE REVIEW

**Review by tcitworld — COMMENTED** [review]
Maybe add a `title` attribute on the ellipsised text to show the full status on hover?

**Review by tcitworld — COMMENTED** [review]
Maybe add a `title` attribute on the ellipsised text to show the full status on hover?

**Review by nickvergessen — APPROVED** [review]

**Comment by georgehrke** [comment]
> Maybe add a `title` attribute on the ellipsised text to show the full status on hover?

We are using the `Actions` component here, so this needs to be done upstream in nc/vue.
Already on my list :)

**Comment by jancborchardt** [comment]
> Maybe add a title attribute on the ellipsised text to show the full status on hover?

I wouldn’t do that, we shouldn’t have tooltips all over. When one wants to check the full message, they can go to the "Set custom status" dialog – and it’s their status in the first place. :) @georgehrke otherwise it looks good!

**Review by marcoambrosini — APPROVED** [review]

**Pull request merged**
