### PR TITLE
Add apple-touch-icon-precomposed (fixes #14818)

### LINKED ISSUE #14818: Custom favicon not showing up in Mac Safari
Nextcloud 15.0.5
Theming app 1.6.0 

Using theming app. in Firefox all good. Favicon is working properly. In Safari only default all over whole site.
Screen Shot 2019-03-23 at 11 22 33
Screen Shot 2019-03-23 at 11 22 51

### PR DESCRIPTION
**Pull request by wenz**
Fix #14818

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
I can't test. But sure....

**Review by juliusknorr — APPROVED** [review]
Code makes sense but can't test either.

**Comment by vendeka** [comment]
When this fix will be available?

**Comment by gary-kim** [comment]
Should be part of the Nextcloud 21 release that is officially release Feb 2nd: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Pull request merged**
