### PR TITLE
[stable27] Backport Polish new sharing flow : accesibility, expand bahavior, click outside behaviour

### PR DESCRIPTION
**Pull request by nfebe**
Manual backport : #40266

### CODE REVIEW

**Comment by blizzz** [comment]
Please add milestone and labels when opening a PR :)

**Comment by blizzz** [comment]
Tests were all satisfactory, only need to rebuild assets → can merge when they were compiled

**Review by AndyScherzinger — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
