### PR TITLE
[Stable10] Backport 796

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/nextcloud/server/pull/796

Please test carefully. [Had some conflicts](https://gist.github.com/LukasReschke/061e77cfb068ebf47679924f2c083bf7).

### CODE REVIEW

**Comment by blizzz** [comment]
LGTM, works, thanks for backporting @LukasReschke :bouquet:

**Comment by blizzz** [comment]
@schiessle mind another look at the tenner?

**Comment by mar1u5** [comment]
:shipit: ... Works fine 🎆

**Comment by schiessle** [comment]
:tada: I just merged the remaining pull requests for the survey_client and for serverinfo.... so we are complete :rocket:

**Comment by blizzz** [comment]
thx @mar1u5 🙋

**Pull request merged**
