### PR TITLE
Give the sharing tab a unique id so it also opens properly on other languages

### PR DESCRIPTION
**Pull request by juliusknorr**
Steps to reproduce:
- change language to something other than english
- click the share icon in the file list

Expected: The share tab opens
Actual: The first tab (activity) opens

- [x] Requires https://github.com/nextcloud/nextcloud-vue/pull/833

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
1.2.8 released

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
@juliushaertl mind to do the rebase dance?

**Comment by juliushaertl** [comment]
Done.

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
once this is passed and merged, I'll create a pr for all npm updates
https://drone.nextcloud.com/nextcloud/server/25566

**Comment by skjnldsv** [comment]
Sharing tests fails 

> Share link row in the details view in Files app could not be found after 50 seconds

**Comment by skjnldsv** [comment]
Rebased and ready to go

**Comment by skjnldsv** [comment]
Ah right, still the same issue, we need https://github.com/nextcloud/nextcloud-vue/pull/840

**Comment by skjnldsv** [comment]
1.3.0 released and integrated here!

**Comment by skjnldsv** [comment]
It seems there is some issue with acceptance tests in master
`/drone/src/tests/acceptance/features/users.feature:47`


Accept share needs to be disabled as this is enabled by default now, right @rullzer ?
```json
Scenario: share a file with another user # /drone/src/tests/acceptance/features/app-files-sharing.feature:3
83 | Given I act as John # ActorContext::iActAs()
84 | And I am logged in as the admin # LoginPageContext::iAmLoggedInAsTheAdmin()
85 | And I act as Jane # ActorContext::iActAs()
86 | And I am logged in # LoginPageContext::iAmLoggedIn()
87 | And I act as John # ActorContext::iActAs()
88 | And I rename "welcome.txt" to "farewell.txt" # FileListContext::iRenameTo()
89 | And I see that the file list contains a file named "farewell.txt" # FileListContext::iSeeThatTheFileListContainsAFileNamed()
90 | When I share "farewell.txt" with "user0" # FilesAppSharingContext::iShareWith()
91 | And I see that the file is shared with "user0" # FilesAppSharingContext::iSeeThatTheFileIsSharedWith()
92 | And I act as Jane # ActorContext::iActAs()
93 | And I accept the share for "farewell.txt" in the notifications # NotificationsContext::iAcceptTheShareForInTheNotifications()
94 | Notification of incoming share for file farewell.txt could not be found after 350 seconds
95 | Actions in notification of incoming share for file farewell.txt could not be found after 350 seconds
```

**Comment by skjnldsv** [comment]
Yep, tests fails on master as well

**Comment by skjnldsv** [comment]
Dam, stable18 is still on old vue components branch xD

**Comment by skjnldsv** [comment]
Backport in https://github.com/nextcloud/server/pull/19212

**Pull request merged**
