### PR TITLE
Most of us don't use IRC anymore

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by gary-kim** [comment]
Wait, we don't?

**Comment by ChristophWurst** [comment]
do you? I was under the impression that IRC isn't used that much anymore. It was our primary communication channel in the past. but now we have the forums and public Talk rooms for that

**Comment by gary-kim** [comment]
It doesn't seem to be used much but there also don't seem to be public talk rooms for most of the repos including this one.

**Comment by ChristophWurst** [comment]
What would be your suggestion then? Feels wrong to me to promote IRC when it's not the main channel of communication.

**Comment by gary-kim** [comment]
Removing the mention of irc was probably the right decision. Any chance a public Talk room could be created for more general use similar to what `#nextcloud-dev` was used for?

**Comment by ChristophWurst** [comment]
> Any chance a public Talk room could be created for more general use similar to what `#nextcloud-dev` was used for?

We have https://cloud.nextcloud.com/call/xs25tz5y :)

**Pull request merged**
