### PR TITLE
[stable23] Fix top margin in empty versions list

### PR DESCRIPTION
**Pull request by st3iny**
Manual backport of #35063

Tested locally via nc-easy-test.

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/work/server/server/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/work/server/server/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/runner/work/server/server/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/runner/work/server/server/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/runner/work/server/server/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/runner/work/server/server/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/runner/work/server/server/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/runner/work/server/server/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/runner/work/server/server/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/runner/work/server/server/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/runner/work/server/server/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by szaimen** [comment]
Seems like node 18 does not work for stable23... @skjnldsv any idea how to downgrade the used node version?

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
> Seems like node 18 does not work for stable23... @skjnldsv any idea how to downgrade the used node version?

Use nvm.

Also we require node 16 for Nextcloud on master, not node 18.
https://github.com/nextcloud/github_helper/blob/d752b259a66855d3bbed60ef43b5b913f3207bb4/.github/workflows/dispatch-npm-engines.yml#L52-L53

**Comment by szaimen** [comment]
> > Seems like node 18 does not work for stable23... @skjnldsv any idea how to downgrade the used node version?
> 
> Use nvm https://github.com/nvm-sh/nvm
> 
> Also we require node 16 for Nextcloud on master, not node 18. https://github.com/nextcloud/github_helper/blob/d752b259a66855d3bbed60ef43b5b913f3207bb4/.github/workflows/dispatch-npm-engines.yml#L52-L53

I meant how to downgrade Node on CI :)

Screenshot_20221111_085924_Brave

**Comment by skjnldsv** [comment]
Edit the package.json and use `^` instead of `>=`

**Comment by szaimen** [comment]
Thanks! :)

**Pull request merged**
