### PR TITLE
Create activities for (un)publishing calendar events

### PR DESCRIPTION
**Pull request by tcitworld**
Creates corresponding activities whenever a calendar is (un)published.

### CODE REVIEW

**Comment by tcitworld** [comment]
I wrote `You published calendar {calendar}` but maybe we could have the same as the files app : `You shared Calendar {calendar} as public link`.

**Comment by nickvergessen** [comment]
I would go for "shared as public link yeah

**Comment by tcitworld** [comment]
In that case, there's a lot of wording to change in the calendar app too.

**Comment by georgehrke** [comment]
I think we should go for `You shared Calendar {calendar} as public link`, because that's how it's called in the files app. We should rename the wording in the calendar app too I guess.

**Comment by georgehrke** [comment]
@tcitworld Can you please change the wording accordingly? :)

**Comment by georgehrke** [comment]
Failing test looks unrelated

**Comment by MorrisJobke** [comment]
Let me update the wording.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]
Fine by me

**Comment by rullzer** [comment]
Failing tests

**Comment by rullzer** [comment]
Should be OK now but lets wait for CI to be nice and green

**Comment by tcitworld** [comment]
Thx, missed https://github.com/nextcloud/server/commit/bdb0265644b43ba807dcc4ed1655fde6bb8c6174

**Comment by MorrisJobke** [comment]
Tests pass -> merging.

**Pull request merged**
