### PR TITLE
Align collaborative tags differently

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
## IMO, centering makes reading difficult (a bit messy, don't you think 🤔, especially because of tags length and number differences ? )
before

## What I propose
**Aligned to the right (currently committed in this PR) :** 
after
**Or aligned to the left:**

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Jerome-Herbinet** [comment]
Question : why my "npm run build" re-build dist/settings-vue-settings-personal-info.js and dist/settings-vue-settings-personal-info.js.map ? Is it normal ?

**Comment by skjnldsv** [comment]
It should be aligned right already.
The file name expand and push everything to the right, the `justify-content: center` should not apply here.
Are you on Firefox?

Ref: see screenshots from https://github.com/nextcloud/server/pull/37938

**Comment by skjnldsv** [comment]
> Question : why my "npm run build" re-build dist/settings-vue-settings-personal-info.js and dist/settings-vue-settings-personal-info.js.map ? Is it normal ?

Seems like master has a discrepancy, so you fixed it here.
You can ignore, that's alright

**Comment by Jerome-Herbinet** [comment]
> It should be aligned right already. The file name expand and push everything to the right, the `justify-content: center` should not apply here. Are you on Firefox?
> 
> Ref: see screenshots from #37938

@skjnldsv I use FF, but a new test made this morning shows up the same problem.

**Comment by Jerome-Herbinet** [comment]
> Right, something must have slept through Can you remove the `flex: 1 1 100%` on the `table td.filename .system-tags` instead then? :) So it doesn't take more space than necessary?
> 
> image

@skjnldsv your suggestion was the good one. It's all folks now ! 🙂 (+ commit squashing)

**Review by skjnldsv — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Pull request merged**
