### PR TITLE
Graceful error handling and logging

### PR DESCRIPTION
**Pull request by LukasReschke**
Right now a failed "copyr" will result in the error log being spammed with not really helpful error messages. Also situations such as `$dir` returning `false` are not really caught.

This adds more error handling and logging to make debugging such situations easier.

cc @MorrisJobke This is for the customer case I've replied to.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works. :+1:

Instead of endlessly logging stuff like this:

```
{"reqId":"vXs0IxaivFu6mGlavKYP","remoteAddr":"::1","app":"PHP","message":"fopen(\/Users\/morrisjobke\/Projekte\/nextcloud\/server\/abc\/): failed to open stream: No such file or directory at \/Users\/morrisjobke\/Projects\/nextcloud\/server\/lib\/private\/legacy\/util.php#347","level":3,"time":"2016-09-26T07:02:40+00:00","method":"PROPFIND","url":"\/server\/remote.php\/webdav\/","user":"abc"}
{"reqId":"vXs0IxaivFu6mGlavKYP","remoteAddr":"::1","app":"PHP","message":"fopen(\/Users\/morrisjobke\/Projects\/nextcloud\/server\/data\/abc\/files): failed to open stream: Is a directory at \/Users\/morrisjobke\/Projects\/nextcloud\/server\/lib\/private\/Files\/Storage\/Local.php#274","level":3,"time":"2016-09-26T07:02:40+00:00","method":"PROPFIND","url":"\/server\/remote.php\/webdav\/","user":"abc"}
{"reqId":"vXs0IxaivFu6mGlavKYP","remoteAddr":"::1","app":"PHP","message":"stream_copy_to_stream() expects parameter 1 to be resource, boolean given at \/Users\/morrisjobke\/Projects\/nextcloud\/server\/lib\/private\/legacy\/util.php#347","level":3,"time":"2016-09-26T07:02:40+00:00","method":"PROPFIND","url":"\/server\/remote.php\/webdav\/","user":"abc"}
{"reqId":"vXs0IxaivFu6mGlavKYP","remoteAddr":"::1","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/Users\/morrisjobke\/Projects\/nextcloud\/server\/lib\/private\/legacy\/util.php#340","level":3,"time":"2016-09-26T07:02:40+00:00","method":"PROPFIND","url":"\/server\/remote.php\/webdav\/","user":"abc"}
{"reqId":"vXs0IxaivFu6mGlavKYP","remoteAddr":"::1","app":"PHP","message":"Uninitialized string offset: 0 at \/Users\/morrisjobke\/Projects\/nextcloud\/server\/lib\/private\/Files\/Node\/Node.php#296","level":3,"time":"2016-09-26T07:02:40+00:00","method":"PROPFIND","url":"\/server\/remote.php\/webdav\/","user":"abc"}
```

There are now two more descriptive error messages in the log and the user can login and use webdav without problem:

```
{"reqId":"aUFADoOr2PBaWClJhYOe","remoteAddr":"::1","app":"PHP","message":"opendir(\/Users\/morrisjobke\/Projekte\/nextcloud\/server\/abc): failed to open dir: No such file or directory at \/Users\/morrisjobke\/Projects\/nextcloud\/server\/lib\/private\/legacy\/util.php#342","level":3,"time":"2016-09-26T07:03:04+00:00","method":"PROPFIND","url":"\/server\/remote.php\/webdav\/","user":"def"}
{"reqId":"aUFADoOr2PBaWClJhYOe","remoteAddr":"::1","app":"core","message":"Could not opendir \"\/Users\/morrisjobke\/Projekte\/nextcloud\/server\/abc\"","level":3,"time":"2016-09-26T07:03:04+00:00","method":"PROPFIND","url":"\/server\/remote.php\/webdav\/","user":"def"}
```

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer Please test this.

* setup in config.php a skeleton dir: `'skeletondirectory' => '/Users/morrisjobke/Projekte/nextcloud/server/abc',`
* create a new user
* do a PROPFIND for the new user (never logged in before): `curl -i -X PROPFIND http://localhost/server/remote.php/webdav/ -u abc:abc`

**Comment by MorrisJobke** [comment]
@karlitschek we should backport this

**Comment by karlitschek** [comment]
great. please backport :+1:

**Comment by nickvergessen** [comment]
👍

**Pull request merged**
