### PR TITLE
Fix valid storages removed when cleaning remote storages

### PR DESCRIPTION
**Pull request by danxuliu**
The remote URL of a share [is always stored in the database with a trailing slash](https://github.com/nextcloud/server/blob/2a054e6c04e0a40421510eb889cbf59f153c5177/apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php#L187-L191). However, when a cloud ID is generated [trailing slashes are removed](https://github.com/nextcloud/server/blob/d89a75be0b01f0423a7c1ad2d58aac73c3cc1f3a/lib/private/Federation/CloudIdManager.php#L112).

The ID of a remote storage [is generated from the cloud ID](https://github.com/nextcloud/server/blob/d89a75be0b01f0423a7c1ad2d58aac73c3cc1f3a/apps/files_sharing/lib/External/Storage.php#L135), but the `cleanup-remote-storage` command directly used the remote URL stored in the database. Due to this, even if the remote storage was valid, its ID did not match the ID of the remote share generated by the command and ended being removed.

Now the command generates the ID of remote shares using the cloud ID instead, just like done by the remote storage, so there is no longer a mismatch.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by PVince81** [comment]
so after just merging this, psalm is unhappy about the merge: https://github.com/nextcloud/server/actions/runs/664180405

**Comment by MorrisJobke** [comment]
Bildschirmfoto 2021-03-18 um 11 30 10


Is this triggered by our change?

**Comment by PVince81** [comment]
seems not, probably a hiccup from Github.
just had a unicorn page even recently...

**Pull request merged**
