### PR TITLE
Fix Sharing app description

### LINKED ISSUE #3357: files_sharing app info.xml change ownCloud to Nextcloud
### Expected behaviour
Use "Nextcloud" in info.xml description

server/apps/files_sharing/appinfo/info.xml

### Actual behaviour
"ownCloud" in info.xml description

**Nextcloud version**: 11.0.1

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @MorrisJobke 

Fix #3357

### CODE REVIEW

**Review by MariusBluem — APPROVED** [review]
👍

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
cc @karlitschek @nickvergessen I would like to see this backported.

**Comment by karlitschek** [comment]
please backport

**Comment by nickvergessen** [comment]
Backported to 11 and 10

**Pull request merged**
