### PR TITLE
Move core/js/files to webpack

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Conflicts

**Comment by rullzer** [comment]
> Conflicts

I know. Wanted to have something else in to avoid the rebase dance. All good now.

**Comment by juliushaertl** [comment]
Should be removed from here as well then https://github.com/nextcloud/server/blob/334c4fddfe632bad94746c1b0b3ec4bb8209a4d5/core/js/core.json#L19-L20

**Review by juliusknorr — COMMENTED** [review]
Otherwise good to go from my side :+1:

**Comment by rullzer** [comment]
> Should be removed from here as well then
> 
> https://github.com/nextcloud/server/blob/334c4fddfe632bad94746c1b0b3ec4bb8209a4d5/core/js/core.json#L19-L20

right that files... I mean ideally we'd just kill it entirely :P Saving client side compile steps... added to the list :P

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Comment by rullzer** [comment]
ah pff jsunit does :boom:

**Pull request merged**
