### PR TITLE
Only run phpunit when "php" changed

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Maybe also changes to `.sh` files should be taken as valid test cases (looking at `autotest.sh` here)

**Comment by MorrisJobke** [comment]
And `.json` like the `shipped.json`

**Comment by nickvergessen** [comment]
json is meh, but I will check for not package.json and package-lock.json

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
