### PR TITLE
dont get bruteforce delay twice

### PR DESCRIPTION
**Pull request by icewind1991**
No need to make two db queries

cc @LukasReschke

### CODE REVIEW

**Comment by rullzer** [comment]
Makes sense.  But CI is failing

**Comment by LukasReschke** [comment]
```
There were 3 failures:

1) Test\User\SessionTest::testLogClientInNoTokenPasswordWith2fa
Expectation failed for method name is equal to <string:getDelay> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

2) Test\User\SessionTest::testLogClientInWithTokenPassword
Expectation failed for method name is equal to <string:getDelay> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

3) Test\User\SessionTest::testLogClientInNoTokenPasswordNo2fa
Expectation failed for method name is equal to <string:getDelay> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

--
```

**Comment by rullzer** [comment]
LGTM

**Comment by icewind1991** [comment]
tests all green

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
