### PR TITLE
Set proper root path for single file shares originating from other storages

### LINKED ISSUE #16617: Federated shares reshared with local users are not accessible
I just encountered the following issue:
- Share a file from userA1@instanceA to userB1@instanceB using federated sharing
- as user B1@instanceB reshare the file to userB2 on instanceB as a user share
- the file is added
- downloading the file fails, as it is mounted as a SharedStorage which tries to access the file by path which doesn't exist

@schiessle @rullzer How should we handle this properly? Should we make sure the local share is working properly or should we instead try to initiate another remote share to the original file on instanceA?

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes https://github.com/nextcloud/server/issues/16617

The main issue here seems to be that the SharedStorage assumes an non-empty result of getUnjailedPath in https://github.com/nextcloud/server/blob/d5f19c1031c4abc7abe9986d1f0b786df5885dbf/apps/files_sharing/lib/SharedStorage.php#L249 which is not given for shares that originate in the root of a mountpoint (like single file federated shares).

I'm not 100% sure this is the right approach, so some input from @icewind1991 or @rullzer  would be highly appreciated. :wink: Maybe we could even just obit the if statement checking for the getUnjailedPath not being empty?

### CODE REVIEW

**Review by nickvergessen — DISMISSED** [review]

**Comment by rullzer** [comment]
@icewind1991 I'd like your take on this.

**Comment by icewind1991** [comment]
remove the check for empty `getUnjailedPath`

**Comment by ChristophWurst** [comment]
> remove the check for empty `getUnjailedPath`

Applied. Please have a look at the new diff as I didn't test this nor have a clue what I just changed :wink:

**Comment by rullzer** [comment]
@juliushaertl kill or redo?

**Comment by rullzer** [comment]
let me rebase...

**Comment by MorrisJobke** [comment]
@icewind1991 🏓

**Comment by icewind1991** [comment]
fixed the test and removed the if statement that isn't relevant anyway

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
@icewind1991 +1 then?

**Pull request merged**
