### PR TITLE
use ? instead of X for avatar name fallback

### PR DESCRIPTION
**Pull request by jancborchardt**
When the name can’t be found or there’s another error, we show an X currently. This is a bit strange especially since there are names starting with X. ;) Changed it to a »?«.

Please review @rullzer @Kondou-ger @nextcloud/javascript

### CODE REVIEW

**Comment by skjnldsv** [comment]
👍

**Review by LukasReschke — DISMISSED** [review]
JS unit tests do fail.

**Comment by skjnldsv** [comment]
Ouuups I should have waited for the tests!

**Comment by MorrisJobke** [comment]
I fixed the unit tests and this works 👍

**Comment by LukasReschke** [comment]
LGTM

**Comment by jancborchardt** [comment]
Damn, I thought I made a global search but missed the tests! Thanks @MorrisJobke :)

**Comment by MorrisJobke** [comment]
> Damn, I thought I made a global search but missed the tests! Thanks @MorrisJobke :)

Use a decent IDE :wink:

**Comment by jancborchardt** [comment]
@MorrisJobke global search worked, but apparently the code editor isn’t using a decent human.

**Pull request merged**
