### PR TITLE
[stable13] workflow rules error when changing operation

### PR DESCRIPTION
**Pull request by nickvergessen**
Relevant backport of https://github.com/nextcloud/server/pull/9393

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:35392->[::1]:53: read: connection refused

still all tests are green?

**Comment by MorrisJobke** [comment]
> still all tests are green?

Let me retrigger CI for this job.

**Comment by MorrisJobke** [comment]
https://drone.nextcloud.com/nextcloud/server/7062

**Comment by MorrisJobke** [comment]
https://drone.nextcloud.com/nextcloud/server/7067

**Pull request merged**
