### PR TITLE
 Allow to search for real pattern in contacts 

### PR DESCRIPTION
**Pull request by tacruc**
at the moment the patterns get escaped while creating the SQL Query this removes the possibity to use the wildcards _%. With this PR there would be an $option to disable this behavior.

### CODE REVIEW

**Comment by tacruc** [comment]
Does somebody has an Idea why it is failing on SQLlite? I think it is something which probably would fail even without the changes.

**Comment by MorrisJobke** [comment]
cc @georgehrke @ChristophWurst @blizzz

**Comment by blizzz** [comment]
>  Does somebody has an Idea why it is failing on SQLlite? I think it is something which probably would fail even without the changes.

Try to get the final sql statement by debugging. Perhaps some abstraction does some magic?

**Comment by tacruc** [comment]
@blizzz Tanks for the tip. At the moment I have not environment wit SQLlite running. Do you know if it is possible to login on the testing container, or to get the testing container and start it local?

**Comment by tacruc** [comment]
@blizzz  Thank you will have a look soon

**Comment by ChristophWurst** [comment]
> @blizzz Thank you will have a look soon

@tacruc any update? :ping_pong:

**Comment by MorrisJobke** [comment]
I guess we can close this for now. The PR can be reopened at any time once the changes were made. I hope that is okay for you @tacruc

**Pull request closed without merging**
