### PR TITLE
Fix mtimes for share root

### PR DESCRIPTION
**Pull request by icewind1991**
Also known as "https://github.com/nextcloud/server/pull/1151, the good parts"

cc @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 You haven't signed off ;)

**Comment by icewind1991** [comment]
@LukasReschke @MorrisJobke please review

**Comment by rullzer** [comment]
@icewind1991 do you have steps to tests?

**Comment by rullzer** [comment]
@icewind1991 testing steps?

**Comment by MorrisJobke** [comment]
> @icewind1991 testing steps?

@icewind1991 Ping

**Comment by ChristophWurst** [comment]
ping 😉

**Comment by icewind1991** [comment]
> do you have steps to tests?

Files that are hidden in smb should no longer show up, for the mtime part I'm not sure since that came from https://github.com/owncloud/core/pull/25954

**Comment by LukasReschke** [comment]
@icewind1991 Can we move that to 12? I'd prefer to consider 11 closed for any non-critical merges.

**Comment by rullzer** [comment]
I tested this by just adding an SMB mount and syncing against it. Didn't break so LGTM

**Review by LukasReschke — APPROVED** [review]
LGTM

**Pull request merged**
