### PR TITLE
fixes dav share issue with owner

### PR DESCRIPTION
**Pull request by georgehrke**
Please review @rullzer @MorrisJobke @skjnldsv

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Still working! :+1:

**Review by rullzer — APPROVED** [review]
Works as advertised!

**Comment by rullzer** [comment]
CI is not totally happy

**Comment by MorrisJobke** [comment]
@georgehrke There are a few failures in the Caldav and Carddav tests 🙈

**Pull request merged**
