### PR TITLE
get files_external mounts more efficiently

### PR DESCRIPTION
**Pull request by icewind1991**
With bit of sql magic we can go from using 4 separate queries to one single query.

The other methods are still needed for files_external settings

### CODE REVIEW

**Comment by icewind1991** [comment]
@MorrisJobke @rullzer @LukasReschke please review

**Comment by rullzer** [comment]
Looks fine to me but I'm not to much into the external storage code.

Is all this covered by tests?

**Comment by icewind1991** [comment]
Yes

**Comment by rullzer** [comment]
Then LGTM

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
