### PR TITLE
Hide expiration date field for remote shares

### PR DESCRIPTION
**Pull request by PVince81**
Remote shares currently do not support expiration date.

See https://github.com/nextcloud/server/pull/25320 for a former research I did where I discovered that the backend doesn't save it yet. Making it actually work is more involved, so for now we just hide it.

It is possible that at the time where the sharing panel got converted to Vue, this specific case has not been thought of.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]

**Comment by PVince81** [comment]
rebased and solved manually

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
