### PR TITLE
don't translate a variable

### LINKED ISSUE #29584: l10n: No need to translate variable
https://github.com/nextcloud/server/blob/b12d24707cbddb7fe334a3d45e94028be5e47296/apps/settings/src/components/PersonalInfo/ProfileVisibilitySection/VisibilityDropdown.vue#L28

Just a variable, no need to have it at Transifex.

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/29584

Disclaimer: I didnt test this since I dont know how

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
