### PR TITLE
Open the file when the fileid changes and openfile is set

### LINKED ISSUE #45486: [Bug]: Fail to create a second file in the Files web interface, unless I reload
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating a file in the web interface via "+ New", it will be created and opened immediately. When this document is closed and a second document is created, it will appear, but it will not be opened – it needs a page refresh. For some 3rd party applications it is bad, because the created files are just plain empty 0 bytes files, but e.g. MS's Office Online expects a setup office document.

It's probably a sharp corner from the F2V effort.

### Steps to reproduce

1. After a refresh of Nextcloud Files, it is possible to create a new speadsheet document. It opens automatically.
2. Then you close the document and create a new spreadsheet document. It does not open automatically and stays at 0 bytes.
3. When you reload the browser, creating a new document will open open Office Online again.
4. If you try steps 1-3 for a simple "New text file" instead of a spreadsheet, the results are the same (only that it opens with the Text editor the first time after a refresh).

### Expected behavior

It works just as the first time.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by artonge**
When opening a file, the `openfile` query parameter is set to true. This stays in the URL even after the viewer was closed.
After that, when creating a new file, the `fileId` in the URL changes, but the `openfile` parameter stays to true. This does not trigger the watcher: https://github.com/nextcloud/server/blob/a5fd623469b40c44881e4635de073d334b371bae/apps/files/src/components/FilesListVirtual.vue#L196-L200

If we want to automatically open newly created files, then we need to either:
- check the `openfile` value in the `fileId` watcher: https://github.com/nextcloud/server/blob/a5fd623469b40c44881e4635de073d334b371bae/apps/files/src/components/FilesListVirtual.vue#L192-L194
- or reset the `openfile` parameter to false when the Viewer is closed

I am not sure whether we want the `openfile` parameter to be reset when the Viewer is closed, so I went for the first solution.

Fix https://github.com/nextcloud/server/issues/45486

### CODE REVIEW

**Review by susnux — COMMENTED** [review]
what happens if `fileId` and `openFile` change in the same tick?

**Comment by skjnldsv** [comment]
> I am not sure whether we want the `openfile` parameter to be reset when the Viewer is closed

I think we used to, it should definitely be the case.
The openfile should reflect the current view, if nothing is opened (aka, Viewer), then openfile should not be set. Refreshing the page should always lead to seeing the same UI (Grigorii mentionned that in another ticket too and I agree)

**Comment by artonge** [comment]
Replaced by https://github.com/nextcloud/viewer/pull/2322

**Pull request closed without merging**
