### PR TITLE
Add file action to move files and folders

### PR DESCRIPTION
**Pull request by icewind1991**
Will look into improving the file picker in a seperate PR for some beter ux

### CODE REVIEW

**Comment by icewind1991** [comment]
> Will look into improving the file picker in a seperate PR for some beter ux

https://github.com/nextcloud/server/pull/1756

**Comment by MorrisJobke** [comment]
Tested and works 👍 

@jancborchardt we need an icon for the move action - currently it's the pencil

**Comment by jancborchardt** [comment]
Very cool! Here you go with a more fitting icon, the »external« icon looks nice and I’m not sure if it warrants creating a different one:
capture du 2016-10-17 18-52-55


:+1: from my side

**Comment by jancborchardt** [comment]
Btw @icewind1991 can you change the filepicker title to »Move `file/foldername` to …« and the »Choose« button to »Move«? Then it’s way nicer and contextual.

**Pull request merged**
