### PR TITLE
[stable19] Bump 3rdparty ref

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Comment by MichaIng** [comment]
Isn't NC19 EOL anyway?

**Comment by LukasReschke** [comment]
> Isn't NC19 EOL anyway?

Not for Nextcloud Enterprise customers :-)

**Review by skjnldsv — APPROVED** [review]

**Review by MichaIng — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by LukasReschke** [comment]
🎉 ?

**Pull request merged**
