### PR TITLE
Fix multiselect min width

### LINKED ISSUE #15246: NC 16 - breadcrumb menu in user management not shown anymore
## Expected behavior
Behind each user entry a breadcrumb drop-down menu should provide options to delete or disable a user etc.

## Current behavior
The breadcrumb drop-down menu isn't shown anymore although its functions are still functional if clicking on the white background where it is being expected.

grafik

## Steps to reproduce
1. Open the users menu
2. Check if the breadcrumb menu exists.

#### Server Configuration
OS: Linux 3.16.63
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 16.0.0

#### Client Configuration
Browser: Mozilla Firefox 66.0.3
Operating system: Windows 10

### PR DESCRIPTION
**Pull request by skjnldsv**
fix #15246

@nextcloud/designers @j-ed

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by jancborchardt** [comment]
Please check if this fixes your issue @j-ed @mmccarn :)

**Comment by j-ed** [comment]
The original problem, the missing breadcrumbs behind a record, has been solved but now the whole user list looks a little bit shaky:

grafik

**Comment by skjnldsv** [comment]
@j-ed it should absolutely not look like that.
Could you refresh your cache? :)

**Comment by j-ed** [comment]
@skjnldsv I've explicitly tested it with a Firefox test profile, where I had deleted all cached data before I logged-into Nextcloud. For you I've repeated the test and got the same result.

**Comment by skjnldsv** [comment]
Even the server css cache? (occ maintenance:repair)
Capture d’écran_2019-04-30_19-10-09

**Comment by j-ed** [comment]
Sorry, I cannot see any improvement although I've cleared the server cache as you requested.

**Comment by MorrisJobke** [comment]
> The original problem, the missing breadcrumbs behind a record, has been solved but now the whole user list looks a little bit shaky:

I can't reproduce this here.

**Comment by skjnldsv** [comment]
Me neither. I'd say a checkout issue maybe? Or a cache problem again. :woman_shrugging:

**Comment by skjnldsv** [comment]
Bump

**Review by MorrisJobke — APPROVED** [review]
Works here 👍

**Pull request merged**
