### PR TITLE
Fix incorrect quota in upload to shared folder by PROPFIND

### PR DESCRIPTION
**Pull request by mlell**
This is still WIP. This fixes issue #5437. It replaces reading the folder's free space from
the #free_space HTML element by a WebDAV PROPFIND request. This is
relevant if uploading by dragging onto a shared folder's icon in the web
interface, as #free_space reports the user's quota whereas PROPFIND
returns the quota of the share's owner in that case.

I am new to this code base and need feedback on the following remaining issues:
 
  * I determine the upload target folder name by `upload._targetFolder`, which looks like a private function name. Is there a better way to get the upload target name?
  * I do the PROPFIND by OC.Files.getClient()._client.propFind(...), which looks hacky to me. Is this the public API?
  * It would save network bandwith if the PROPFIND would only be performed in the case that a file was dragged to the icon of a shared folder. Otherwise the content of `$("#free_space")` could still be used. How do I determine in JavaScript if the target folder is a shared folder?

### CODE REVIEW

**Comment by rullzer** [comment]
Thnx for starting this @mlell!
@danxuliu if you want to have more js fun ;)

**Comment by MorrisJobke** [comment]
Could somebody from @nextcloud/javascript have a look at this?

**Comment by MorrisJobke** [comment]
@danxuliu @skjnldsv @juliushaertl Hasn't one of you recently looked into this?

**Comment by skjnldsv** [comment]
Not me :)

**Comment by rullzer** [comment]
I'm going to close this.
If anybody wants to pick this up feel free to reopen and rebase.

**Pull request closed without merging**
