### PR TITLE
fix(login): Disable login button when already logging in

### PR DESCRIPTION
**Pull request by SystemKeeper**
## Summary

Fixes "State token does not match" in some cases (e.g. double click on the login button)

## How to reproduce:

* Start a login flow (V1 or V2), e.g. by logging in via the desktop client
* Enter username and password
* Click "Log in" and when the button changes to "Logging in" click the button again
* You're now prompted with a "temporary error". 
* Enter your password
* See the error "State token does not match"

## Before

image

## After

image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
To prevent double submit through enter we could adjust LoginForm.vue and ignore form submit while loading=true as well. Apparently this would be possible with a disabled field set: https://stackoverflow.com/questions/3507958/how-can-i-make-an-entire-html-form-readonly

**Comment by SystemKeeper** [comment]
Right, I didn’t think of enter. Let me adjust the PR

**Comment by SystemKeeper** [comment]
> Apparently this would be possible with a disabled field set

I tried that, but then I am unable to login in any way (it always ends up in a temporary error). Therefore I prevented another submit of the form, as we already have a submit handler.

**Review by ChristophWurst — APPROVED** [review]

**Review by provokateurin — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
