### PR TITLE
Bump jquery from 3.1 to 3.5

### PR DESCRIPTION
**Pull request by ChristophWurst**
Updates jquery and jquery-migrate to the latest versions.

~~Test just very shortly, nothing breaking found yet. Let's see what CI has to say.~~

https://jquery.com/upgrade-guide/3.5/#jquery-htmlprefilter-changes is the most critical change. Cause file list actions to render wrongly. It's easy to fix. We might want to grep through our code to find all self-closing `div`s and `span`s.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
jsunit found five new errors locally :popcorn:

**Comment by ChristophWurst** [comment]
Let's do a smaller bump to 3.4 https://github.com/nextcloud/server/pull/24173 and rebase this one afterwards.

**Comment by skjnldsv** [comment]
What is the status here?

**Comment by ChristophWurst** [comment]
I don't have time to finish this. You may close.

**Pull request closed without merging**
