### PR TITLE
fix(files): focus file name on renaming also initially

### LINKED ISSUE #41876: [BITV] 9.2.4.3/3.2 - When the "New folder" menu item is activated, a new row is created in the table with the "New folder" input field. (2)
However, the keyboard focus is not moved to the input field; it remains on the menu item. To change the folder name, a user has to navigate through all the other elements on the page. 

image

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-89806fe784-v3-n2

9.2.4.3/11.2 - https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-89806fe784-v11-n2

### PR DESCRIPTION
**Pull request by ShGKme**
* Resolves: #41876 

## Summary

When a new folder is created, the new file entry is initially in renaming mode
Watch should handle renaming not only on change, but also on init.

## Screenshots

Before | After
---|---
new-folder-before | new-folder-after

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]
Tested, works, and LGTM! Nice use of deep handlers :)

**Comment by ShGKme** [comment]
Drone error seems related

**Comment by susnux** [comment]
> Drone error seems related

Yes

**Comment by ShGKme** [comment]
> Drone error seems related

It was not related 👀

**Comment by ShGKme** [comment]
No changes, just rebased onto `master`. All test passes now

**Pull request merged**
