### PR TITLE
Really cleanup the content-wrapper

### PR DESCRIPTION
**Pull request by skjnldsv**
After https://github.com/nextcloud/server/pull/10363
And https://github.com/nextcloud/server/pull/9982

No idea why I left this despite saying I removed it ^^

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]
:see_no_evil: Yes, let's also get rid of this as well.

**Review by danxuliu — CHANGES_REQUESTED** [review]
Last commit broke the file list layout in the Files app:
content-wrapper-cleanup-file-list

**Comment by skjnldsv** [comment]
@danxuliu can you review again please?

**Review by danxuliu — APPROVED** [review]
Tested (in **desktop** versions of Firefox and Chromium) and works :+1:

**Pull request merged**
