### PR TITLE
Bugfix/change password changes

### PR DESCRIPTION
**Pull request by raghunayyar**
Fixes all issues stated in 
https://github.com/nextcloud/server/issues/1061

Please review @nextcloud/designers @jancborchardt

### CODE REVIEW

**Comment by raghunayyar** [comment]
I see there is an issue with the tipsy positioning in my last commit, fixing that.

**Comment by raghunayyar** [comment]
Fixed, up for review now. :)

**Comment by MorrisJobke** [comment]
* [ ] BUG: enter a wrong password and click "Change password" causes the spinner to stay endless

**Comment by raghunayyar** [comment]
@MorrisJobke done ;)

**Comment by raghunayyar** [comment]
@nextcloud/designers need a couple of thumbs up here. ;)

**Comment by MorrisJobke** [comment]
* [ ] BUG: enable password policy app and try to change password to abc -> error message is not shown
* [ ] BUG: on clicking "change password" the page jumps down a whole screen and the app password section is shown and focused - looks like duplicate use of an ID

**Comment by MorrisJobke** [comment]
@raghunayyar sorry for those new issues :(

**Comment by MorrisJobke** [comment]
Beside the two points it works very well.

**Comment by MorrisJobke** [comment]
> BUG: enable password policy app and try to change password to abc -> error message is not shown

I think this one could be done in an additional ticket.

**Comment by raghunayyar** [comment]
@MorrisJobke I still can't reproduce the bug you are talking about and you showed me in the conference on my machine. Can you take this up if you got some extra time?

**Comment by MorrisJobke** [comment]
> @MorrisJobke I still can't reproduce the bug you are talking about and you showed me in the conference on my machine. Can you take this up if you got some extra time?

Is this the only thing left? Then change the label to "3 - To review" and I will give this another try ;)

**Comment by raghunayyar** [comment]
All your @MorrisJobke

**Comment by MorrisJobke** [comment]
I removed the old "Saving ..." and "Successfully saved" messages, because they only duplicate the feedback.

Beside that it works nicely :+1:

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen Please review

**Comment by MorrisJobke** [comment]
I will fix the issue with the password policy app in a separate PR

**Comment by MorrisJobke** [comment]
> I will fix the issue with the password policy app in a separate PR

https://github.com/nextcloud/server/pull/1634

**Comment by raghunayyar** [comment]
thanks @MorrisJobke, much appreciated. :D

**Comment by raghunayyar** [comment]
Also, should this be backported? @karlitschek

**Comment by karlitschek** [comment]
nice. please backport 👍

**Comment by MorrisJobke** [comment]
> Also, should this be backported? @karlitschek

I would not backport this one here. It's mostly cosmetic stuff and it works in stable versions.

**Comment by MorrisJobke** [comment]
> I would not backport this one here. It's mostly cosmetic stuff and it works in stable versions.

Is this okay with you, @raghunayyar? @nickvergessen @LukasReschke Opinions?

**Comment by jancborchardt** [comment]
It’s polishing and non-critical, so I wouldn’t backport it really.

**Pull request merged**
