### PR TITLE
[stable9] Show spinner for files_drop again

### PR DESCRIPTION
**Pull request by LukasReschke**
Somehow the spinner wasn't there anymore after some changes. This makes it appear again.

@jancborchardt @blizzz Mind reviewing? THX a lot.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@jospoortvliet Btw. https://github.com/nextcloud/server/pull/19#issuecomment-225175466 has a screenshot, or you can just create one yourself by creating a public link, then making it editable and selecting "Hide file list".

**Comment by MorrisJobke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Works 👍

**Comment by blizzz** [comment]
:+1:

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
