### PR TITLE
fix(styles): Adjust heading styles

### LINKED ISSUE #43393: [Bug]: h3 to h6 look like text
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Bildschirmfoto vom 2024-02-06 14-25-27

h2 isn't great, h3 is bad.

Another example:
image

*Encryption* is a h3. It doesn't look like one at all. This makes it super hard to recognize the structure of a text page in Nextcloud, like the settings.

Another one:

image

*Update channel* looks like ordinary text. It gives no structure except for the increased spacing.

h1 to h6 all share the same base styling: https://github.com/nextcloud/server/blob/375dade49b28d3ca3d670c585c44b1651458b17f/core/css/styles.scss#L19-L30. The font weight of h2 is set to bold. The rest stays *initial*, which is too light IMO. https://github.com/nextcloud/server/blob/375dade49b28d3ca3d670c585c44b1651458b17f/core/css/apps.scss#L60-L78

### Steps to reproduce

1. Open settings, apps, etc

### Expected behavior

Headings that help me recognize the structure of text, paragraps and sections.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #43393

## Summary
Make headings look like real headings and not just ordinary text.
The styles are copied from the **text**-app where a design review was done on them.

### Screenshots

before | after
---|---
Screenshot 2024-02-18 at 13-04-13 Overview - Administration settings - Nextcloud|Screenshot 2024-02-18 at 13-03-09 Overview - Administration settings - Nextcloud

Code used:
```html
<h2>This is a h2</h2>
  <p>This is a paragraph</p>
<h3>This is a h3</h3>
  <p>This is a paragraph</p>
<h4>This is a h4</h4>
  <p>This is a paragraph</p>
<h5>This is a h5</h5>
  <p>This is a paragraph</p>
<h6>This is a h6</h6>
  <p>This is a paragraph</p>
```

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — COMMENTED** [review]
Looks great!

Settings are a bit inconsistent because those rendered with Vue are using NcSetttingsSection and it has font-size: 20px for .settings-section__name.

There are also a few headings that should be demoted to simple text, like here for external storage:

image

Not sure if we want to do this here or in a follow-up. Settings probably need a bit of a design review after this change.

**Comment by szaimen** [comment]
> Not sure if we want to do this here or in a follow-up. Settings probably need a bit of a design review after this change.

I would do it in a follow-up

**Review by szaimen — APPROVED** [review]
Screenshots look great :)

**Comment by ChristophWurst** [comment]
Apps that use NcAppNavigationCaption

| Before | After |
|--------|--------|
| Bildschirmfoto vom 2024-02-19 15-33-00 | Bildschirmfoto vom 2024-02-19 15-32-28 |

**Comment by susnux** [comment]
If we agree on this changes here we should adjust nextcloud-vue styles accordingly.

**Comment by susnux** [comment]
@jancborchardt do we want to use this styles or adjust them because of https://github.com/nextcloud/text/issues/5515 ?

**Review by ChristophWurst — APPROVED** [review]
It's showtime

**Comment by ChristophWurst** [comment]
Let's add this to the app dev upgrade docs as "breaking" frontend change

**Review by jancborchardt — APPROVED** [review]
Looks good @susnux but maybe as a follow-up it would make sense to adjust it to the sizes in https://github.com/nextcloud/text/pull/5594/files ? Maybe from h1 → h2 though because h2 is the first visible one (h1 is always the logo).

**Comment by susnux** [comment]
> But maybe as a follow-up it would make sense to adjust it to the sizes in https://github.com/nextcloud/text/pull/5594/files ?

Sizes adjusted :white_check_mark: 

> Maybe from h1 → h2 though because h2 is the first visible one (h1 is always the logo).

Done, but the latter is not always true. h1 is not the logo but for apps the app name (e.g. "Dashboard") or similar (for files it is the view (e.g. "All files").

**Pull request merged**
