### PR TITLE
fix paged search with multiple bases (LDAP)

### PR DESCRIPTION
**Pull request by blizzz**
* [x] Integration test
* [x] actual fix
* [ ] ~~refactor (not to backport)~~ will do as seperate PR, less mess

There are a couple concepts in LDAP around the search. On is that parallel searches in multiple bases are allowed. The other one are paged searches, that allows to browse through the directory. Alas, they are incompatible to each other. Since we do paged results by default (if present, which in 99% is), we leave the parallel search asside. This PR goes the quick way with so it is easy to backport. A follow up PR will follow to refactor functions for 16.

Included is an integration test (commit 2) that establishes the failing scenario, commit 3 contains the simple, backportable fix.

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by juliushaertl** [comment]
Tests are failing: 

```
/drone/src/github.com/nextcloud/server/build/integration/ldap_features/openldap-uid-username.feature:90

[Mon Jan 28 13:54:59 2019] 127.0.0.1:43498 [200]: /ocs/v2.php/cloud/users?limit=10&offset=2
    And sending "GET" to "/cloud/users?limit=10&offset=2"                            # LDAPContext::sendingTo()
    Then the OCS status code should be "200"                                         # LDAPContext::theOCSStatusCodeShouldBe()
    And the "users" result should contain "5" of                                     # LDAPContext::theResultShouldContainOf()
      | ebba    |
      | eindis  |
      | fjolnir |
      | gunna   |
      | juliana |
      | leo     |
      | stigur  |
      Failed asserting that 0 is identical to 5.
    And the "users" result should contain "3" of                                     # LDAPContext::theResultShouldContainOf()
      | allisha   |
      | dogukan   |
      | lloyd     |
      | priscilla |
      | shannah   |
[Mon Jan 28 13:54:59 2019] 127.0.0.1:43510 [200]: /ocs/v2.php/apps/user_ldap/api/v1/config/s01
```

**Review by juliusknorr — APPROVED** [review]
Tested and works :+1:

**Comment by blizzz** [comment]
@juliushaertl is drone showing something different to me?

screenshot_20190129_105850


Or, if that was from the second commit that introduced the integration test only, then this is what should have happened, otherwise the test wouldn't work.

**Comment by juliushaertl** [comment]
> Or, if that was from the second commit that introduced the integration test only, then this is what should have happened, otherwise the test wouldn't work.

Yes, just checked the status on the 2nd commit, since the other one was not on the screen. :see_no_evil: Sorry for the noise there.

**Comment by juliushaertl** [comment]
@blizzz 

> The backport to stable14 failed. Please do this backport manually.

**Pull request merged**
