### PR TITLE
enh(settings): Refactor UI for session and app token management

### LINKED ISSUE #42318: [Bug]: Rename device token → "[object InputEvent]"
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Renaming a "devices & session" in /settings/user/security no longer works in NC 28.0.0.11 and 28.1.0 RC1 (regression).

### Steps to reproduce

1. create a "device/session token" (aka "app pin")
2. (try to) rename it

As soon as one hits any key to edit the old token, the edit field's content changes to "[object InputEvent]" and remains so. No text entry possible.

https://github.com/nextcloud/server/assets/8425483/e74d81f3-d6a3-4249-9eac-91781ab12c1d

### Expected behavior

One should be able to rename a token.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 8,
            "timeout": 1.5
        },
        "logtimezone": "Europe\/Berlin",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "theme": "",
        "loglevel": 2,
        "simpleSignUpLink.shown": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "htaccess.IgnoreFrontController": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mars.seyfarth.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "overwrite.cli.url": "https:\/\/mars.seyfarth.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "version": "28.0.1.0",
        "updater.release.channel": "beta",
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_excluded_groups": [
            "2FA_exception"
        ],
        "app_install_overwrite": [
            "impersonate",
            "twofactor_webauthn"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_reminders: 1.1.0
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_email: 2.7.4
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0 (installed 1.13.0)
  - circles: 28.0.0-dev (installed 25.0.0-alpha.0)
  - comments: 1.18.0 (installed 1.12.0)
  - contactsinteraction: 1.9.0 (installed 1.4.0)
  - dashboard: 7.8.0 (installed 7.2.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.12.0)
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0 (installed 2.5.0)
  - files_rightclick: 0.15.1 (installed 1.2.0)
  - files_sharing: 1.20.0 (installed 1.19.0)
  - files_trashbin: 1.18.0 (installed 1.17.0)
  - files_versions: 1.21.0 (installed 1.17.0)
  - firstrunwizard: 2.17.0 (installed 2.12.0)
  - nextcloud_announcements: 1.17.0 (installed 1.12.0)
  - photos: 2.4.0 (installed 1.5.0)
  - privacy: 1.12.0 (installed 1.7.0)
  - recommendations: 2.0.0 (installed 1.2.0)
  - sharebymail: 1.18.0 (installed 1.12.0)
  - support: 1.11.0 (installed 1.6.0)
  - survey_client: 1.16.0 (installed 1.11.0)
  - suspicious_login: 6.0.0 (installed 4.2.0)
  - systemtags: 1.18.0 (installed 1.12.0)
  - text: 3.9.1 (installed 3.8.0)
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.2.0)
  - weather_status: 1.8.0 (installed 1.2.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"wklFPsb7rNQJZSeNgyJo","level":3,"time":"2023-12-15T23:59:18+01:00","remoteAddr":"192.168.0.10","user":"admin","app":"index","method":"PUT","url":"/settings/personal/authtokens/404","message":"OCA\\Settings\\Controller\\AuthSettingsController::update(): Argument #3 ($name) must be of type string, array given, called in PATH/lib/private/AppFramework/Http/Dispatcher.php on line 230 in file 'PATH/apps/settings/lib/Controller/AuthSettingsController.php' line 229","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"28.0.1.0","exception":{"Exception":"Exception","Message":"OCA\\Settings\\Controller\\AuthSettingsController::update(): Argument #3 ($name) must be of type string, array given, called in PATH/lib/private/AppFramework/Http/Dispatcher.php on line 230 in file 'PATH/apps/settings/lib/Controller/AuthSettingsController.php' line 229","Code":0,"Trace":[{"file":"PATH/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"PATH/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"PATH/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"PATH/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"PATH/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"TypeError","Message":"OCA\\Settings\\Controller\\AuthSettingsController::update(): Argument #3 ($name) must be of type string, array given, called in PATH/lib/private/AppFramework/Http/Dispatcher.php on line 230","Code":0,"Trace":[{"file":"PATH/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"update","class":"OCA\\Settings\\Controller\\AuthSettingsController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"PATH/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"PATH/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"PATH/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"PATH/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"PATH/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"PATH/apps/settings/lib/Controller/AuthSettingsController.php","Line":229},"message":"OCA\\Settings\\Controller\\AuthSettingsController::update(): Argument #3 ($name) must be of type string, array given, called in PATH/lib/private/AppFramework/Http/Dispatcher.php on line 230 in file 'PATH/apps/settings/lib/Controller/AuthSettingsController.php' line 229","exception":{},"CustomMessage":"OCA\\Settings\\Controller\\AuthSettingsController::update(): Argument #3 ($name) must be of type string, array given, called in PATH/lib/private/AppFramework/Http/Dispatcher.php on line 230 in file 'PATH/apps/settings/lib/Controller/AuthSettingsController.php' line 229"}}
```

### Additional info

Firefox 120.0.1 (on Arch) DevConsole:

renaming app token 405 test 
input { target: input#inputzfbbr.input-field__input, isTrusted: true, isComposing: false, inputType: "insertText", data: "a", view: Window, detail: 0, layerX: 0, layerY: 0, which: 0, … }
AuthTokenSection.vue:126
TypeError: this.token.name.match is not a function
    iconName AuthToken.vue:188
    VueJS 3
    AuthToken AuthToken.vue:1
    VueJS 14
    rename AuthToken.vue:251
    VueJS 33
vue.runtime.esm.js:3049:16
XHRPUT
https://mars.seyfarth.de/settings/personal/authtokens/405
[HTTP/2 500  36ms]

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/42318

## Summary
This modernizes the auth token / app password / app token (what ever name you like) UI:
1. Fix some accessibility issues due to not grouped form elements
2. Group API related functions within a store
3. Cleanup and fix styles (e.g. background color on wiped devices is broken on before)
4. Remove deprecated functions

### Screenshots
before|after
---|---
Screenshot_20231216_235113|Screenshot_20231216_234948
Screenshot_20231216_235121|Screenshot_20231216_235001
Screenshot_20231216_235128|Screenshot_20231216_235007

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]
Tested, and looked over the code - Looks good to me, really nice PR, however, best for others to also agree with my opinion :) 👍

**Comment by TtuxX** [comment]
Hi there :) Really nice UI improvement, thanks a lot !
Would there be a possible solution to solve having a too long list with many sessions ?
I have been using Nextcloud for several years and I literally need to scroll for few seconds to arrive to the app password creation field.
Would it be possible to move the app password creation section at the top, and have the history list afterwards ?

**Review by skjnldsv — APPROVED** [review]

**Comment by susnux** [comment]
/backport 960bec949aa08a5c67a5fd2699213048f56ea0b7 to stable28

**Comment by jospoortvliet** [comment]
> > I have been using Nextcloud for several years and I literally need to scroll for few seconds to arrive to the app password creation field.
> 
> Why are there so many sessions? Do you keep using them? If not they probably should be better revoked? (Maybe we need a batch / select-all-and-revoke action?).
> 
> But yes, moving to the top will be possible.

Hi, did you? This would be really a good move - most ppl probably have a ton of open sessions and having to scroll down for this makes no sense. It should ideally be always on top, not below the sessions.

As a matter of fact, I think this belongs in the 2FA settings... it is for use with 2FA, is it not? @nextcloud/designers

**Comment by jospoortvliet** [comment]
Sorry, don't mean to be negative, it was very important that this was redesigned, but if it's not made more visible it still won't be used by people. Honestly, there should imho simply be a big button completely on top of the user security settings that says something like "log in with QR code or app password" and when you press it, it shows the QR code you can then just scan with your mobile phone.

Honestly, what would be even better would be to just show a QR code there, always. Why not?

We support this feature, it is prominent on the phone, showing you can scan a QR instead of entering all those details, but no user will realistically ever find WHERE TO SCAN THE QR CODE!

The app password is secondary - show QR first, always. And maybe the app password below it. Steps to log in using QR now:
1. open the 'login' on Nextcloud app on phone
2. Click the small QR code icon & allow video access
3. go to Nextcloud, personal settings/security (**note: this is NOT explained on your phone - it should be**)
4. scroll all the way down
5. enter a name like 'my phone'
6. choose "show QR code for mobile apps"
7. scan the QR code

It should be:
1. open the 'login' on Nextcloud app on phone
2. Click the small QR code icon & allow video access. Your phone now explains you need to:
3. go to Nextcloud, personal settings/security
4. Scan the QR code

That would make it easy and practical to use for many, perhaps even most users...

Another idea: show it on the "about" screen. Just show the users' qr code and tell them - scan this with your phone - it links to app store, then scan a 2nd time after installing the app and you are logged in. Bet it's not possible, but if it is... we should do it!

**Comment by JonasMayerDev** [comment]
I agree with @jospoortvliet. It should be easier to get to the qr code. What about having a general QR Code or a shortcut on the /index.php/settings/user/sync-clients page. I don't see much value there but a collection of links. I think this is the best fitting place for an QR Code to quickly log in with a mobile device and has the advantage that it not overcrowds the security page... Just an idea, I have no idea if it is feasible :)

**Pull request merged**
