### PR TITLE
Downstream 2016-06-09

### PR DESCRIPTION
**Pull request by blizzz**
Today's downstream from ownCloud master

### CODE REVIEW

**Comment by blizzz** [comment]
Hm, I am not so confident. It appeard to work for me, but here are some commits (with a different hash though) that were already included in #25. A ``rebase -i`` presented me only the relevant commits, however. I did not continue with that. Maybe I should… *doing*

**Comment by blizzz** [comment]
@LukasReschke @mar1u5 @MorrisJobke

**Comment by blizzz** [comment]
My theory is now that this happens, because I did a rebase with the first downstream PR. I'll revert #25 and try to do this in a more proper and cleaner manner.

**Comment by blizzz** [comment]
> Lesson learnt: Always

> ``git pull upstream master``

> No rebase. Ever. This rewrites history and follow-up downstream PRs will always bring in already merged commits. 

> (upstream is the remote git repo, initialized by ``git remote add upstream https://github.com/owncloud/core.git``)

(https://help.nextcloud.com/t/downstreams-from-core/463/7)

The first downstream PR is revoked, I will update this one. And then we have everything proper and clean.

**Comment by blizzz** [comment]
Done. Locally, you can test with following the merge steps as described under *command line instructions* and afterwards run a ``git pull upstream master`` (prerequisite: have the "upstream" remote configure, see comment above). It's either clean like

```
From https://github.com/owncloud/core
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

or if new stuff was merged over there only that will show up. → Proof that this approach works now.

**Comment by LukasReschke** [comment]
:+1:

**Comment by blizzz** [comment]
@MorrisJobke gave verbal :+1:

**Pull request merged**
