### PR TITLE
LDAP Wizard: primary-style buttons

### PR DESCRIPTION
**Pull request by blizzz**
Split off from #5568 

~~⚠️ based on feature branch from #5568~~

### CODE REVIEW

**Comment by jancborchardt** [comment]
Why use a separate class and not the core class?

**Comment by blizzz** [comment]
> Why use a separate class and not the core class?

IIRC it does not work with jQ Ui. Some stuff is overwritten, or it looks horrible (or both).

**Comment by juliushaertl** [comment]
@blizzz I've added a commit to provide the primary style also for jquery ui buttons. That should work fine now since we have migrated the jquery-ui-fixes to SCSS as well in #6341

**Comment by blizzz** [comment]
@juliushaertl awesome, thanks! That's much better.

I rebased.

**Comment by blizzz** [comment]
Rebased again, and now to master. 

Want to have it in? @jancborchardt @skjnldsv @nextcloud/ldap ?

**Comment by jancborchardt** [comment]
Seems fine by me. @juliushaertl @skjnldsv what do you think?

**Comment by juliushaertl** [comment]
Fine by me, but I would like to have another reviewer since i committed the primary class use.

**Comment by blizzz** [comment]
@juliushaertl i am happy about your changes

**Review by juliusknorr — APPROVED** [review]

**Comment by blizzz** [comment]
> Seems fine by me

Interpreting this as 👍  and merging

**Comment by skjnldsv** [comment]
> Seems fine by me. @juliushaertl @skjnldsv what do you think?

I did not have enough time to review! @blizzz is the fastest merger of the far west! 🔫  😆

**Comment by blizzz** [comment]
😁

**Pull request merged**
