### PR TITLE
[stable25] Fix default primary for user theming

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/35002

26 is fixed already

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by artonge — APPROVED** [review]

**Comment by skjnldsv** [comment]
Fixed acceptance. They were wrongly adjusted to pass.

**Comment by PVince81** [comment]
conflict in the theming test

**Comment by skjnldsv** [comment]
> conflict in the theming test

resolved

**Comment by PVince81** [comment]
@skjnldsv theming test in CI is failing, probably needs adjusting as well

**Comment by skjnldsv** [comment]
Fixed

**Pull request merged**
