### PR TITLE
Use CSP nonces

### PR DESCRIPTION
**Pull request by LukasReschke**
CSP nonces are a feature available with CSP v2. Basically instead of saying "JS resources from the same domain are ok to be served" we now say "Ressources from everywhere are allowed as long as they add a `nonce` attribute to the script tag with the right nonce.

At the moment the nonce is basically just a `<?php p(base64_encode($_['requesttoken'])) ?>`, we have to decode the requesttoken since `:` is not an allowed value in the nonce. So if somebody does on their own include JS files (instead of using the `addScript` public API, they now must also include that attribute.)

IE does currently not implement CSP v2, thus there is a whitelist included that delivers the new CSP v2 policy to newer browsers. Check http://caniuse.com/#feat=contentsecuritypolicy2 for the current browser support list. An alternative approach would be to just add `'unsafe-inline'` as well as `'unsafe-inline'` is ignored by CSPv2 when a nonce is set. But this would make this security feature unusable at all in IE. Not worth it at the moment IMO.

Implementing this offers the following advantages:
1. **Security:** As we host resources from the same domain by design we don't have to worry about 'self' anymore being in the whitelist
2. **Performance:** We can move oc.js again to inline JS. This makes the loading way quicker as we don't have to load on every load of a new web page a blocking dynamically non-cached JavaScript file.

If you want to toy with CSP see also https://csp-evaluator.withgoogle.com/

---

cc @rullzer

### CODE REVIEW

**Comment by rullzer** [comment]
Awesome! :balloon:

**Comment by ChristophWurst** [comment]
> So if somebody does on their own include JS files (instead of using the addScript public API, they now must also include that attribute.)

😢 how? This will break the mail app as we're using requirejs to dynamically load scripts in debug mode. On production, we use ``addScript`` for the packaged version though.

**Comment by LukasReschke** [comment]
> 😢 how? This will break the mail app as we're using requirejs to dynamically load scripts in debug mode. On production, we use addScript for the packaged version though.

Fix it? 😉 

… or tell me how to setup that mail app to that state to experience that together with that branch. Like with stupid commands including `composer install` etc.

Everything that goes further than `git clone` is annoying ;-)

**Comment by BernhardPosselt** [comment]
> Everything that goes further than git clone is annoying and I won't figure out magically ;-)

Running make should take care of exactly that

**Comment by LukasReschke** [comment]
> Running make should take care of exactly that

Been there. Done that. 90% of the fancy makefiles that people include in apps explode totally on OS X. I won't execute random makefiles anymore ;-)

**Comment by LukasReschke** [comment]
Plus having to install `npm`,  `bower` and all other kind of random tools just sucks big time…

**Comment by BernhardPosselt** [comment]
@LukasReschke should IMHO be addressed, I'd recommend to file bugs on the respective repos

**Comment by LukasReschke** [comment]
Ok. https://gist.github.com/LukasReschke/3eebebb7a87802c5b786d09b05642fe0 should be what requireJS needs to work again ;)

**Comment by rullzer** [comment]
Very cool especially the cool things we can do with it.
Looking good and even tests!
LGTM!

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
