### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by MorrisJobke**
- removes unneeded method that is windows only
- properly loads APCu to run these tests

cc @rullzer @nickvergessen

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Before:

PHP 5.6: There were 88 skipped tests
PHP 7.0: There were 87 skipped tests

**Comment by MorrisJobke** [comment]
After:

PHP 5.6: There were 68 skipped tests
PHP 7.0:  Failing ... I will split out the PHP 7 part in a separate PR.

**Comment by rullzer** [comment]
Shouldn't we do proper test splits for the different cache backends?

**Comment by MorrisJobke** [comment]
> Shouldn't we do proper test splits for the different cache backends?

That too

**Comment by MorrisJobke** [comment]
@LukasReschke mind to review this easy one?

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen mind to review this one as well?

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Stable10: #2048

**Pull request merged**
