### PR TITLE
Add large sidebar previews for text files

### PR DESCRIPTION
**Pull request by icewind1991**
Before:

before

After:

after

Instead of showing a small, unreadable image of the text, we load in the full text to make it easy to quickly tell the contents of a file.
The size of the text preview is the same as the preview of (landscape) images and long texts can be scrolled.

This also adds the ability for apps to register custom thumbnails.

cc @nextcloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
Just a small detail: since it's text, it should have some margin to the sides unlile images. (My computer is in repair today, can't do it. :( Just give it the same amount of margin/padding the content below it has.)

**Comment by MorrisJobke** [comment]
> Just a small detail: since it's text, it should have some margin to the sides unlile images. (My computer is in repair today, can't do it. :( Just give it the same amount of margin/padding the content below it has.)

I will do.

**Comment by MorrisJobke** [comment]
With my change it looks like this:

bildschirmfoto 2016-07-04 um 15 37 25

**Comment by jancborchardt** [comment]
Can we get rid of the excess whitespace below if the text file is short? Looks good otherwise!

**Comment by MorrisJobke** [comment]
> Can we get rid of the excess whitespace below if the text file is short? Looks good otherwise!

I will give this a try.

**Comment by MorrisJobke** [comment]
I fixed it:

short text:
bildschirmfoto 2016-07-04 um 17 37 50
more text:
bildschirmfoto 2016-07-04 um 17 37 54
images:
bildschirmfoto 2016-07-04 um 17 37 57

**Comment by MorrisJobke** [comment]
👍 from me for the actual feature

**Comment by williambargent** [comment]
:+1:

**Comment by mar1u5** [comment]
:+1:

**Comment by mar1u5** [comment]
THX.

**Comment by jancborchardt** [comment]
Great work everyone! :)

**Pull request merged**
