### PR TITLE
Indicate default quota

### LINKED ISSUE #11393: [Enhancement] Indicate users default quota
In the administrators user list, the quota for each user is displayed. At the moment, it is not apparent which users have the default quota and which have the same quota defined manually, as only the number is displayed.

When changing a users quota to default, it reads `Default quota`. However, after a page reload, only the number is displayed again.

It would be nice to have a reading such as `10 GB (default)` or similar instead of only `10 GB`.

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes #11393

This is a rebased and fixed version of #12087. I have not tested the patch.

Supersedes https://github.com/nextcloud/server/pull/12087 by @AasthaGupta :)

### CODE REVIEW

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
The problem with this approach is that you can't change a person to the default quota anymore. It will always set it to the specific one. Thus I would say that it needs to be done the other way around: There is still the default quota entry but it will show inline the amount that it currently is set to.

**Comment by MorrisJobke** [comment]
@ChristophWurst Any news here?

**Comment by ChristophWurst** [comment]
I have no clue about the code tbh. I just tried to clean up #11393 to finally get it merged.

**Comment by MorrisJobke** [comment]
Let's close it for now. We can reopen at any time, when somebody want to work on this.

**Pull request closed without merging**
