### PR TITLE
Remove warning in case of external storage error

### PR DESCRIPTION
**Pull request by skjnldsv**

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:fire: :fire: :fire:

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
There was a regression from this: https://github.com/nextcloud/server/issues/14022


Fix is in https://github.com/nextcloud/server/pull/14076

**Comment by blizzz** [comment]
what was the reason for the removal?

**Comment by MorrisJobke** [comment]
> what was the reason for the removal?

There was a banner at the top that was not dismissible and caused a lot of confusion, because already the entry shows the "this mount is not available" information. Thus we decided to remove the notification banner.

**Comment by blizzz** [comment]
makes sense, ideally in future this is part of the PR text or better the commit message. In a couple months nobody knows anymore :)

**Pull request merged**
