### PR TITLE
Fix visibility switcher for avatar

### LINKED ISSUE #2223: Visibility switcher of profile picture doesn’t work
All the other switchers in the personal settings work, but that one doesn’t. Console error:

```
federationscopemenu.js? line 114 Uncaught TypeError: Cannot read property 'value' of undefined
```

@schiessle @LukasReschke @nextcloud/javascript

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes #2223

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Comment by rullzer** [comment]
👍

**Comment by ChristophWurst** [comment]
👍 

But I don't see any icons on the other input headers. Is that intended or a bug?
bildschirmfoto von 2016-11-21 23-06-17

**Comment by LukasReschke** [comment]
@ChristophWurst They appear here in my Chrome… Strange…… 🤔 

Any idea why they don't appear for you?

**Comment by LukasReschke** [comment]
Also where is you "Folder" icon there? Are the SVG resources loading for you?

**Comment by ChristophWurst** [comment]
I have no idea. Tried with FF & Chrome. Also tried nginx & php's built-in server. Same result across different setups. Totally weird.

**Comment by LukasReschke** [comment]
Guess we won't merge that here then for now 🙈

**Comment by ChristophWurst** [comment]
Well, it happens on master too 🙈 

Strangely enough, after the page appears to be loaded the browser still shows its loading spinner. After a while this
bildschirmfoto von 2016-11-21 23-14-24

popped up.

**Comment by ChristophWurst** [comment]
```
SyntaxError: for-in loop head declarations may not have initializers federationscopemenu.js:116:17
SyntaxError: for-in loop head declarations may not have initializers federationscopemenu.js:116:15
```
https://github.com/nextcloud/server/blame/1e06d0bb47a3751865205fdcad4201b76ddf5df7/settings/js/federationscopemenu.js#L116-L118 I think I know who broke it 🙊

**Comment by LukasReschke** [comment]
>https://github.com/nextcloud/server/blame/1e06d0bb47a3751865205fdcad4201b76ddf5df7/settings/js/federationscopemenu.js#L116-L118 I think I know who broke it 🙊

And do you also know who is fixing it? – At least me has no idea about this JS stuff 😉

**Comment by ChristophWurst** [comment]
sure, replace ``for(var i in this._scopes) {`` with ``for(var i = 0 in this._scopes) {``.

**Comment by LukasReschke** [comment]
> sure, replace ``for(var i in this._scopes) {`` with ``for(var i = 0 in this._scopes) {``. 

I guess you mean the opposite around… But fair enough. Pushed. Please test. 😉

**Comment by ChristophWurst** [comment]
yay, syntax error is gone. The other issues still remains.

``https://localhost/apps/theming/img/core/filetypes/folder.svg?v=8`` loads forever and Chrome shows "ERR_CONTENT_LENGTH_MISMATCH".

I've changed the color in my setup. Maybe something in the theming app causes weird bugs?

**Comment by ChristophWurst** [comment]
Okay, so I have the same behavior in files. Folder icons do not show up. It takes the browser ages to load the page.

**Comment by rullzer** [comment]
Mmmm theming... I'll see if I can reproduce and debug.

**Comment by rullzer** [comment]
Nope all working here...

**Comment by LukasReschke** [comment]
So let's ignore @ChristophWurst's problem here then ;)

**Comment by ChristophWurst** [comment]
> So let's ignore @ChristophWurst's problem here then ;)

Yeah won't make a difference. Happens on master already too ;-)

**Pull request merged**
