### PR TITLE
Consolidate account property getters

### PR DESCRIPTION
**Pull request by Pytal**
Share logic for getting account properties to reduce repetition required for further accessibility improvements e.g. propagation of https://github.com/nextcloud/server/pull/33163 to all properties

### CODE REVIEW

**Comment by PVince81** [comment]
why is this needed ? a short explanation would be nice

**Comment by Pytal** [comment]
> why is this needed ? a short explanation would be nice

Description updated

**Review by PVince81 — APPROVED** [review]
:+1: thanks

**Comment by Pytal** [comment]
Review ping @reviewers

**Comment by Pytal** [comment]
One more review would be appreciated to unblock upcoming accessibility improvements https://github.com/nextcloud/server/issues/27869 :)

**Review by CarlSchwan — APPROVED** [review]

**Pull request merged**
