### PR TITLE
Comment mentions with spaces

### LINKED ISSUE #2443: Missing pieces: user mentions in Comments
With 11 we put the cornerstones for user mentioning in comments (cf. #753). It's not end user friendly yet, though. For Nc 12 we have left to accomplish:

* [ ] When writing or editing a comment and typing an @ in the beginning of a word followed by another character an auto-complete is offered. It only includes users that have access to the file. Results are supposed to show up with a slight delay. For scaling reasons, it needs to be figured out whether all possible users are fetched in the background in advance, or on demand (like search dialog).

* [ ] Usernames are somehow allowed to contain whitespaces. They are currently not supported by our regex syntax. To be truly compatible we need to change the underlying markup and, for instance, wrap the mention into ``[ ]``brackets (see below). Changes needs to be reflected into clients so they render properly (comments UI in sidebar, notifications, activites, …)

### Not fully supported username examples

"Let's talk about it today, @foobar."

Since we allow dots, `@foobar` and `@foobar.` are possible scenarios here. If you have both? Would be silly to insert a space between the username and the fullstop.

But even better it is that we allow white spaces in usernames now:

"@Alice Bernadette wants to talk"

Username can be  `'@Alice Bernadette``or`'@Alice``(or both).

For now, I improve the Regexp to have the 98% solution, butt when going with autocomplete I am afraid we need to wrap the mention into brackets to be able to support all these funny usernames.

### PR DESCRIPTION
**Pull request by nickvergessen**
1. Create a user with a space in the user id: `foo bar`
2. Share a file with the user
3. Mention the user using autocompletion
4. Look at the message

Before: `Hi {{@Unknown user}} bar test`
After: `Hi {{@User with space in ID}} test`

Fix #2443

### CODE REVIEW

**Comment by nickvergessen** [comment]
The problem at the moment is, that the `&quot;` is a word seperator, and therefor the regex does not match anymore, as the `\b` is not there:
https://github.com/nextcloud/server/blob/52723f0a4426e3d6af00179934c568a712d16a9e/apps/comments/js/commentstabview.js#L426

In Talk we do the replacement in php with a simple str_replace and therefor do not have this problem.

**Review by blizzz — COMMENTED** [review]
Would you mind adding another test case to `\Test\Comments\CommentTest::mentionsProvider()` that supports the uid-with-space-scenario? 

Otherwise, the code looks good and i like the simplicity

**Comment by MorrisJobke** [comment]
Even after rebase of this branch the user is not properly shown:

bildschirmfoto 2018-11-02 um 12 38 03


I used `foo bar`

**Comment by nickvergessen** [comment]
@MorrisJobke this is not retro-active, because the saved comment is different (old: `@foo bar` new: `@"foo bar"`). Did you create a new comment and use the autocompletion for it?

**Comment by nickvergessen** [comment]
Added a unit test and rebased.

still working for me, so ready for review.

**Review by blizzz — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> @MorrisJobke this is not retro-active, because the saved comment is different (old: `@foo bar` new: `@"foo bar"`). Did you create a new comment and use the autocompletion for it?

Ah - I created the comment first and then changed the branch. Let me test again.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
