### PR TITLE
Use proper ALTER ROLE syntax

### LINKED ISSUE #1260: postgresql syntax error, can not install nextcloud [resolved]
nextcloud verison 10.0.0-1

go inside:
lib/private/Setup/PostgreSQL.php
then change at line 146:
CREATEDB WITH PASSWORD
by
WITH CREATEDB PASSWORD

then error syntax 7 for SQL request is now fixed.

Also, the way to pass variable to Database is unsafe and full open to SQL injection attacks. it is a serious secure problem. you should improve this code by use PDO API for postgresql and function for "bind" variables.
Also, this addslashes() is not good.
actually, nextcloud is unsafe.

having fun.

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #1260

See https://www.postgresql.org/docs/9.0/static/sql-alterrole.html

CC: @MorrisJobke @icewind1991 @nickvergessen @jerome-diver

### CODE REVIEW

**Comment by LukasReschke** [comment]
LGTM

**Comment by nickvergessen** [comment]
:+1:

**Comment by jerome-diver** [comment]
and for increase safety connection and variable attribution passed to the database without risk of SQL injections, do you need an example of PDO API use to help you for rewrite this part of code, or you will arrive without ?

**Comment by MorrisJobke** [comment]
Backport to stable10: #2591

**Pull request merged**
