### PR TITLE
Update containers to latest version

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @rullzer @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
```
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
194s
75
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
194s
76
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
195s
77
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
195s
78
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
195s
79
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
195s
80
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
195s
81
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
195s
82
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
195s
83
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
196s
84
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
196s
85
PHP Warning:  file_get_contents(/drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/../../public/RichObjectStrings/definitions.json): failed to open stream: No such file or directory in /drone/src/github.com/nextcloud/server/lib/private/RichObjectStrings/Validator.php on line 46
196s
86
PHP Fatal error:  Class 'OCA\Files_Sharing\Exceptions\BrokenPath' not found in /drone/src/github.com/nextcloud/server/apps/files_sharing/lib/SharedMount.php on line 172
```

@nickvergessen do you have an idea why this happens?

**Comment by nickvergessen** [comment]
Not really, https://github.com/nextcloud/server/blob/20986488505616654177da1f861238f0232656fa/lib/private/RichObjectStrings/Validator.php#L46-L46

Feel free to adjust if you find a better solution.

**Comment by MorrisJobke** [comment]
> @nickvergessen do you have an idea why this happens?

Now it didn't happen again 😕

**Comment by rullzer** [comment]
Lets do this! :+1:

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen @ChristophWurst Please review :)

**Comment by ChristophWurst** [comment]
👍

**Pull request merged**
