### PR TITLE
Update Sabre (and friends) to 4.0

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] https://github.com/nextcloud/3rdparty/pull/398
- [x] Rebase

I'm doing this to to help @skjnldsv. If tests fail I'm out :speak_no_evil:

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Changelog at https://github.com/sabre-io/dav/releases/tag/4.0.0 does not sound like there are any breaking changes for us.

**Comment by ChristophWurst** [comment]
Files load but folder icons are missing and permissions are incorrect. A DAV expert needs to look into this

**Comment by skjnldsv** [comment]
> Files load but folder icons are missing and permissions are incorrect. A DAV expert needs to look into this

Pinging Dr @georgehrke :D

**Comment by georgehrke** [comment]
Looking at the Changelog of version 4, this point will probably cause us most work:

> Event listeners that in the past listened to beforeMethod or method
no longer get called. They must listen to beforeMethod:* and method:* now.

**Comment by kesselb** [comment]
https://github.com/nextcloud/user_saml/blob/6734601db801fc4ee232ed643d94a92f37dc1398/lib/DavPlugin.php#L51

https://github.com/nextcloud/end_to_end_encryption/blob/9e71e2d282ccd106cbe3f5f62ad60abd5d05d072/lib/Connector/Sabre/LockPlugin.php#L100

Please don't forget ;)

**Comment by georgehrke** [comment]
- user_saml: https://github.com/nextcloud/user_saml/pull/407
- e2e: https://github.com/nextcloud/end_to_end_encryption/pull/125

**Comment by georgehrke** [comment]
As far as i can tell, the `beforeMethod` thing was pretty much the only change necessary.
Let's wait to see if Litmus is happy and do more in-deep testing.

**Comment by ChristophWurst** [comment]
We can also check how [similar projects](https://github.com/owncloud/core/pull/34559) did the upgrade :)

**Comment by georgehrke** [comment]
We already fixed all the usages of `URIUtil::split` before: https://github.com/nextcloud/server/commit/fc369dd86ea03f3bccb0e1af0686730a0dcb8b9f :)

**Comment by ChristophWurst** [comment]
:+1: (can't approve my own PR :grinning: )

**Comment by georgehrke** [comment]
There are a couple of more test cases we need to fix:
> 4) OCA\DAV\Tests\unit\Connector\Sabre\RequestTest\UploadTest::testBasicUpload
--
122 | TypeError: Argument 3 passed to Sabre\HTTP\Request::__construct() must be of the type array, null given, called in /drone/src/apps/dav/tests/unit/Connector/Sabre/RequestTest/RequestTestCase.php on line 102



On it ...

**Comment by georgehrke** [comment]
please test @icewind1991 @rullzer @juliushaertl

**Comment by rullzer** [comment]
Looks like I don't have permissions to upload files

**Comment by rullzer** [comment]
> Looks like I don't have permissions to upload files

Or at least that is what the js thinks ;)

**Comment by icewind1991** [comment]
Apps that will require updating their `beforeMethod` hooks:

- [ ] guests
- [ ] user_saml

**Comment by icewind1991** [comment]
> > Looks like I don't have permissions to upload files
> 
> Or at least that is what the js thinks ;)

works for me

**Comment by ChristophWurst** [comment]
> user_saml

That https://github.com/nextcloud/user_saml/pull/407?

**Review by rullzer — APPROVED** [review]
Does the trick for me. Lets do this.

**Review by georgehrke — APPROVED** [review]

**Pull request merged**
