### PR TITLE
Cache avatars

### PR DESCRIPTION
**Pull request by rullzer**
We finally start to cache avatars. Because there is absolutely no reason to hit the server for every avatar all the time. Since avatars are rarely updated anyway there is also no need to ask the server every time. If we combine this with https://github.com/nextcloud/server/pull/1121 the avatars create a lot less load on the server.
- Cache all avatars for 15 minutes by defaults. This means that if your friend changes their avatar it will be max 15 minutes before you see it popup.
- Your own avatar has a version parameter. So that if you update your own avatar you will see it directly.

CC: @LukasReschke @nickvergessen @MorrisJobke @icewind1991

### CODE REVIEW

**Comment by LukasReschke** [comment]
When opening http://10.211.55.7/stable9/index.php/settings/personal I get `Uncaught ReferenceError: version is not defined$.fn.avatar @ jquery.avatar.js?v=ff9977c…:85(anonymous function) @ personal.js?v=ff9977c…:379j @ jquery.js:3099fireWith @ jquery.js:3211ready @ jquery.js:3417I @ jquery.js:3433`

**Comment by LukasReschke** [comment]
Well. Also in all other views 🙈

**Comment by rullzer** [comment]
Rabased to hard.
All *should* be good now

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen Mind to review?

**Comment by LukasReschke** [comment]
Good stuff 👍

**Pull request merged**
