### PR TITLE
[stable12] Fix anchor name for federated sharing settings

### LINKED ISSUE #5911: [stable12] Federated share icon is missing in Swedish translation
This is what it looks like on 12.0.1RC3 in `Personal settings`

screenshot from 2017-07-27 22 42 22

As you can see the icon is missing. Is this a Transifex error or is it in the server code? It works with English translation.

### PR DESCRIPTION
**Pull request by MorrisJobke**
* backport of #5913 
* fixes #5911

### CODE REVIEW

**Review by enoch85 — APPROVED** [review]

**Comment by enoch85** [comment]
Thanks!

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@lukasreschke Merge or not merge?

**Comment by enoch85** [comment]
> Merge or not merge?

It solves the problem, so why not?

**Comment by LukasReschke** [comment]
@morrisjobke Merge is okay but then I'm gonna build an RC5 :)

**Comment by MorrisJobke** [comment]
Then 12.0.2

**Comment by enoch85** [comment]
Yet, you released an 12.0.1RC5.

**Comment by nickvergessen** [comment]
So what? we dont need to include everything in the next release, otherwise its never going out because there is always stuff to review?!

**Comment by enoch85** [comment]
> @MorrisJobke Merge is okay but then I'm gonna build an RC5 :)

> Then 12.0.2

@nickvergessen No, just pointing out the fact that this was moved to 12.0.2 because Lukas wanted to release RC5 if this was merged.

In other words, it could have been merged, but now we have to wait another month or so.

But hey, better to wait. :)

**Comment by MorrisJobke** [comment]
> In other words, it could have been merged, but now we have to wait another month or so.

No. Monday is still the planned date, because the reason for the RC5 was to give some minor minor minor stuff a chance to be tested. 😉 

With this here we would need to have wait. We just want to get back to a more serious release testing and not just merge stuff in very late without an RC. 😉

**Comment by enoch85** [comment]
@MorrisJobke Makes sense.

@nickvergessen Not my intention to seem offensive.

**Pull request merged**
