### PR TITLE
Changing name of default logfile

### PR DESCRIPTION
**Pull request by Faldon**
# Change 'owncloud.log' to 'nextcloud.log'

The default name for the logfile should reflect the projects name.
Fixing #293

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks really good 👍

**Comment by MorrisJobke** [comment]
cc @LukasReschke @schiessle @icewind1991

**Comment by icewind1991** [comment]
:+1:

**Comment by LukasReschke** [comment]
LGTM. Needs a changelog entry for 10

**Comment by MorrisJobke** [comment]
Thanks a lot @Faldon :)

**Pull request merged**
