### PR TITLE
fix(files): Node loading information should be accessible

### PR DESCRIPTION
**Pull request by susnux**
## Summary

The loading icon visually informs that the node is currently loading, but there is no non-visual information (accessible information).
So this icon is not just visually pleasing, so add the accessible name.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Needs a rebase and conflicts resolved, else 👍

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
