### PR TITLE
Fix for #26526 

### LINKED ISSUE #26526: Database Versioncheck syntax error
Using Nextcloud v.20.0.8 and MariaDB v.10.5.9

Issue: 
Nextcloud systemcheck returns syntax error:

Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SHOW VARIABLES LIKE "version";':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"version"' at line 1

I suspect the error in line 65 `NEXTCLOUD_DIR/apps/settings/lib/SetupChecks/SupportedDatabase.php`

`$result = $this->connection->prepare('SHOW VARIABLES LIKE "version";');`

It seems that quotes and double quotes should be switched in this case. 
As every other sql call also uses single quotes for sql variables.

Changing this manually to:
`$result = $this->connection->prepare("SHOW VARIABLES LIKE 'version';");`
has resolved the issue for me.

### PR DESCRIPTION
**Pull request by ZitronePlus**
Fix #26526
fix for sql query
replaced double quotes with single quotes.
Query should now also work for dbs with sql_mode including "ANSI" and "ANSI_QUOTES"

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
Nice and quick to review, thanks @ZitronePlus !

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
There are two commits now, you may want to
```bash
git reset --soft HEAD~2
git commit --signoff -m '<Your message>'
git push --force-with-lease origin master
```

**Comment by szaimen** [comment]
@ZitronePlus any update here?
Do you mind addressing this comment https://github.com/nextcloud/server/pull/27731#issuecomment-872432402 ?
Otherwise creating a new PR with your changes is probably faster...

**Pull request merged**
