### PR TITLE
fix(cypress): Check for local changes before trying to apply them

### PR DESCRIPTION
**Pull request by SystemKeeper**
## Summary

Running a `chown` command inside of docker on a machine that has `CONFIG_OVERLAY_FS_METACOPY` disabled takes unnecessarily long. In case of cypress, we try to apply local changes and run a `chown` command afterwards, even when no files were actually changed/added.
This PR checks if any of the files exist, before copying them to the container and executing a `chown` command.

Example:
image

## TODO

According to the comment at

https://github.com/nextcloud/server/blob/8359b806f4fdc6ca7270c38744684de8ef830174/cypress/dockerNode.ts#L124-L130

This method was never intended to run on CI, but it seems to be the case since this method was introduced (https://github.com/nextcloud/server/pull/34696). It might make sense to just check for `process.env.CI` and never execute that method, but I am not sure if it serves a purpose for _something_ on CI?!

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by st3iny** [comment]
Why not disable the check entirely on CI?

See also https://github.com/nextcloud/server/pull/45894

**Comment by SystemKeeper** [comment]
> Why not disable the check entirely on CI?

Yea, see above:

> This method was never intended to run on CI, but it seems to be the case since this method was introduced (https://github.com/nextcloud/server/pull/34696). It might make sense to just check for process.env.CI and never execute that method, but I am not sure if it serves a purpose for something on CI?!

If it doesn't serve any purpose, we should disable it completely on CI. But I think this change here might even make sense when not running on CI?

**Comment by st3iny** [comment]
I agree, let's have both PRs then.

**Review by st3iny — APPROVED** [review]

**Comment by susnux** [comment]
This breaks local testing. You are now forced to have your nextcloud repository in '/var/www/html' because otherwise it will always skip uploading.

**Comment by SystemKeeper** [comment]
But the path was `/var/www/html` before that PR already or did I mis-interpreted the old code ?

**Comment by susnux** [comment]
It is uploaded to `/var/www/html` on the docker image, but you are checking if the *local* path is `/var/www/html/something` which is not the case (probably)

**Comment by SystemKeeper** [comment]
Sorry, I mis-interpreted the tar command... Was going to take a look at this, but seems it was already fixed in https://github.com/nextcloud/server/pull/46370 - correct?

**Comment by susnux** [comment]
Yes

**Pull request merged**
