### PR TITLE
always setup the root mounts early

### PR DESCRIPTION
**Pull request by icewind1991**
apparently in some cases there is currently a code path that end up not setting up any root mounts.

Also includes some extra checks that there are root mounts provided.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

does it affect performance though ?

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
merge?

**Comment by PVince81** [comment]
@icewind1991 from the various places where we sent this as patch this hasn't helped solve any issues, so I'm hesitant to move forward with this change without better proof

**Pull request closed without merging**
