### PR TITLE
Make color-success less dull

### PR DESCRIPTION
**Pull request by marcoambrosini**
Before: 

Screenshot from 2020-04-27 10-14-22

After: 

Screenshot from 2020-04-27 14-40-30

### CODE REVIEW

**Comment by skjnldsv** [comment]
Btw, we also have a `--color-error`

**Comment by juliushaertl** [comment]
I guess your screenshots are in the wrong order :wink:

**Comment by juliushaertl** [comment]
Ah no, but that is way to bright imo then.

**Comment by ma12-co** [comment]
> Ah no, but that is way to bright imo then.

Should we separate color-success from --color-join-call then? We need a pretty bright color in talk, but I get that the "success" color is mostly used to dismiss things? So the use cases are probably not very similar..

**Comment by ma12-co** [comment]
> Btw, we also have a --color-error

That looks bright enough to me already.. Inf act it's more saturated and has more luminance than this green I'm proposing

**Comment by ma12-co** [comment]
Screenshot from 2020-04-27 14-57-29
Screenshot from 2020-04-27 14-57-38

**Comment by juliushaertl** [comment]
So color-success is used in some places in settings, where it also has white text on top of it so I would not make that brighter in general.

**Comment by ma12-co** [comment]
Ok, so should I create a different one? Do you reckon a brighter green will be needed elsewhere or just in talk?

**Comment by juliushaertl** [comment]
Can you share how you want to use the brighter color in talk, because honestly I think the screenshot in the first post looks worse after ;)

**Comment by ma12-co** [comment]
Basically I'd use it just for the join-call, I mean, I can dial it back a bit but the idea is that it needs to be super catchy

This are ios' colors for example:

**Comment by juliushaertl** [comment]
Ah ok, for such a case I would just do it in Talk. We can get this in server if we see other use cases over time I'd say.

**Comment by jancborchardt** [comment]
> Basically I'd use it just for the join-call, I mean, I can dial it back a bit but the idea is that it needs to be super catchy
> 
> This are ios' colors for example:
> 

The problem with this example is that here there’s only an icon on it and not text that you need to read. I would go for just making the "Join call" button green for now with our standard green, the specifics of the color (and making sure any new one we choose is accessible as well) is something for a separate pull request.

**Pull request closed without merging**
