### PR TITLE
Fix unified search

### PR DESCRIPTION
**Pull request by skjnldsv**
After the rebase failure of https://github.com/nextcloud/server/pull/21971

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
:shark:

**Review by georgehrke — APPROVED** [review]
🐘

**Comment by skjnldsv** [comment]
I'm waiting for tests! Do not merge!

**Comment by skjnldsv** [comment]
https://drone.nextcloud.com/nextcloud/server/31307
Seems good so far, npm rebuilt, let's see

**Pull request merged**
