### PR TITLE
Also expire share type email

### LINKED ISSUE #22586: Enforce expiration date on mail sharing
When Sharing Files or Folders via e-mail you have to manually set an expiration date everytime beacause there (still) is no option in the settings to enforce (or maybe just have a standard) expiration date for mail-shares.
(Refer to: Enforce Password & expiration date on mail sharing #11547 ; https://github.com/nextcloud/server/issues/11547 In my Opition this is not closed)

NC 19.0.1, Ubuntu 18.04

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/22586

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Yes 🙈

**Review by ChristophWurst — APPROVED** [review]
:ghost:

**Comment by MorrisJobke** [comment]
CI is not happy:

```
1) OCA\Theming\Tests\Controller\ThemingControllerTest::testGetManifest
252	Failed asserting that two objects are equal.
253	--- Expected
254	+++ Actual
255	@@ @@
256	             0 => Array (
257	                 'src' => 'touchicon?v=0'
258	                 'type' => 'image/png'
259	-                'sizes' => '128x128'
260	+                'sizes' => '512x512'
261	             )
262	             1 => Array (...)
263	         )
264	
265	/drone/src/apps/theming/tests/Controller/ThemingControllerTest.php:831
266	
```

**Comment by skjnldsv** [comment]
> CI is not happy:

not related. Damn, haven't seen this error when merging yesterday!
I can fix in a followup

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/23581

**Pull request merged**
