### PR TITLE
Enable SCSS for guest pages

### PR DESCRIPTION
**Pull request by danxuliu**
SCSS is disabled for several types of pages, as the SCSS compiler uses the cache system, which is not available for example when Nextcloud is not installed yet. However, in regular guest pages the cache system is available, so SCSS is now enabled for them too.

Enabling SCSS causes the main _server.scss_ file to be automatically loaded in guest pages. The _server.scss_ file included some CSS rules that conflicted with the guest styles; this pull request also fixes most of those conflicts.

The rendering of guest pages before and after this pull request is not a pixel-perfect match; some of those differences are not very important (like a 5px increase in the distance between the logo and the form caused by [the logo now being displayed as `display: inline-flex`](https://github.com/nextcloud/server/blob/de5d5ee0e7fcc1ad29bf8c6cfeac2aa987557740/core/css/header.scss#L105) instead of as `display: block`), while others are nice improvements from _server.scss_ that were not ported to _guest.css_ (like the confirm button being _highlighted_ on hover).

Guest pages that I have verified:
- Public share page
- Public share authentication page
- Error 404 page

In any case, apps using guest pages may require some minor adjustment in their CSS files to override some of the rules introduced by _server.scss_ (for example, [the authentication page for Talk should include the same changes added in _publicshareauth.css_](https://github.com/nextcloud/spreed/blob/cb8c33105f69eab4cd11560940d5638565493e48/css/authenticate.css#L17)), although the biggest offender (the `#body-login` rules) were fixed by this pull request.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
You're incredible! :heart_eyes:

**Review by MorrisJobke — APPROVED** [review]
Install, error and upgrade pages look fine 👍

**Review by juliusknorr — COMMENTED** [review]
:+1:

**Comment by juliushaertl** [comment]
Looks like my tab didn't refresh :see_no_evil:

**Pull request merged**
