### PR TITLE
fix(files_sharing): Password field must not be required if already set

### LINKED ISSUE #48468: [Bug]: Sharing via email errors with missing password
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When trying to share folder via an email address, with enforced passwords on sharing, clicking on the share button causing the password box to go blank, flash a red border but still save. The share will not work due to having a missing password. If you go in and edit the share and make a new password, the share will start to work again.

### Steps to reproduce

1.From the root view of the folders, click on share icon 
image
2 Enter in a valid email address and click the email box below.
image
3. Form is prefilled and generated password is viewable when clicking show/hide password eye.
image
4. Click on "Save Share" the password box empties and has a red border around it
image
5. If you go in and edit the share, there is still a red box around the password box and an email was not sent.
image
6. Entering a new password and clicking "Update share" will add the new, manually entered password and email the password to the email address.

 

### Expected behavior

The auto generated password should be saved and emailed to the email address.
 

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

Edge Version 129.0.2792.65 (Official build) (64-bit)
Chrome Version 129.0.6668.71 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by susnux**
* Resolves https://github.com/nextcloud/server/issues/48468

If there is already a password, there is no need to require the password in the setting ('newPassword'). It is only required for new shares.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nfebe — APPROVED** [review]
LGTM.

Wondering what would happen if someone attempts to remove password on an existing share, if possible.

**Review by provokateurin — APPROVED** [review]

**Pull request merged**
