### PR TITLE
handle AccessDenied error when checking if external s3 support versions

### PR DESCRIPTION
**Pull request by mgallien**
Signed-off-by: Matthieu Gallien <matthieu.gallien@nextcloud.com>

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by blizzz — APPROVED** [review]
:elephant:

**Comment by PVince81** [comment]
rebasing as I hope to see the S3 tests pass (and as they randomly fail to init)

**Comment by PVince81** [comment]
again
```
curl: (7) Failed to connect to localhost port 9000: Connection refused
```

:cry:

**Comment by mgallien** [comment]
@PVince81 may I merge it ?
is it possible to backport it to older releases (has been reported even in v22)

**Pull request merged**
