### PR TITLE
Newdav tagsplugin

### PR DESCRIPTION
**Pull request by LukasReschke**
From https://github.com/owncloud/core/pull/26098

Let's see if the tests pass 🙈

### CODE REVIEW

**Comment by ChristophWurst** [comment]
rebased to resolve conflicts

**Comment by MorrisJobke** [comment]
Tested and works :+1: 

```
$ curl -H 'Depth:1' -u admin:admin -H 'Content-Type:text/xml; charset=UTF-8' -X PROPFIND 'http://localhost:7000/remote.php/webdav/' --data-binary '<?xml version="1.0" encoding="UTF-8"?><D:propfind xmlns:D="DAV:"><D:prop><D:resourcetype/><D:getlastmodified/><favorite xmlns="http://owncloud.org/ns"/><D:creationdate/><id xmlns="http://owncloud.org/ns"/><D:getcontentlength/><D:displayname/><D:quota-available-bytes/><D:getetag/><permissions xmlns="http://owncloud.org/ns"/><D:quota-used-bytes/><D:getcontenttype/></D:prop></D:propfind>'
```

Then there is a `<oc:favorite>1</oc:favorite>` element, that is set to 1 if the favorite is set or empty if not set.

**Review by MorrisJobke — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Tested and works 👍
>
> `$ curl -H 'Depth:1' -u admin:admin -H 'Content-Type:text/xml; charset=UTF-8' -X PROPFIND 'http://localhost:7000/remote.php/webdav/' --data-binary '<?xml version="1.0" encoding="UTF-8"?><D:propfind xmlns:D="DAV:"><D:prop><D:resourcetype/><D:getlastmodified/><favorite xmlns="http://owncloud.org/ns"/><D:creationdate/><id xmlns="http://owncloud.org/ns"/><D:getcontentlength/><D:displayname/><D:quota-available-bytes/><D:getetag/><permissions xmlns="http://owncloud.org/ns"/><D:quota-used-bytes/><D:getcontenttype/></D:prop></D:propfind>'`
>
> Then there is a <oc:favorite>1</oc:favorite> element, that is set to 1 if the favorite is set or empty if not set.

Works already before.

`http://localhost:7000/remote.php/dav/files/admin/` is what has been fixed.

**Comment by nickvergessen** [comment]
👍

**Pull request merged**
