### PR TITLE
Add acceptance test for public folder navigation

### PR DESCRIPTION
**Pull request by juliusknorr**
Acceptance test for #14962

### CODE REVIEW

**Comment by danxuliu** [comment]
Do you mind if I simplify the test a bit? :-)

**Comment by danxuliu** [comment]
I have rebased on master now that #14985 was merged.

For reference, these are the changes and the rationale behind them:
- Sharing a link for a folder after the folder is created requires some careful handling due to the sidebar behaviour (or at least it required it; it is problably no longer the case since the animation was removed, but anyway ;-) ); instead now all the descendant folders are created first and, once done, the Files app is reloaded again to go back to the root and then the folder is shared without needing a lengthy explanation.
- Between _I create a folder named XXX_ and _I enter in the folder named XXX_ there is no need to include _I see that the file list contains a file named XXX_ because _I enter in the folder named XXX_ will automatically wait until the file list contains a folder named XXX (otherwise it could not enter in it).
- I renamed the grandchild folder from _Another subfolder_ to _Subsubfolder_, because _Another subfolder_ looks like a sibling of _Subfolder_ instead of its child.

**Comment by juliushaertl** [comment]
Thanks a lot for helping out @danxuliu :heart: 

Ready for review I'd say then.

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I squashed the mixup.

**Pull request merged**
