### PR TITLE
Fix CSRF token generation / validation

### PR DESCRIPTION
**Pull request by leonklingele**
Operate on raw bytes instead of base64-encoded strings.
Issue was introduced in a977465

### CODE REVIEW

**Comment by leonklingele** [comment]
Whoops. Tests have now been updated as well.
Code used to generate the values:

```go
package main

import (
	"encoding/base64"
	"fmt"
)

func main() {
	a := []byte("abc")
	fmt.Println("a:", print(a)) // a: byteslice: [97 98 99], b64: YWJj
	b := []byte("def")
	fmt.Println("b:", print(b)) // b: byteslice: [100 101 102], b64: ZGVm
	// Ignore b's len :)
	xor := make([]byte, len(a))
	for i := range a {
		xor[i] = a[i] ^ b[i]
	}
	fmt.Println("xor:", print(xor)) // xor: byteslice: [5 7 5], b64: BQcF
}

func print(b []byte) string {
	return fmt.Sprintf("byteslice: %d, b64: %s", b, base64.StdEncoding.EncodeToString(b))
}
```

**Comment by rullzer** [comment]
@leonklingele you need to sign off on your commits.

Code looks good to me. But lets wait what @LukasReschke has to say since it is his code ;)

**Comment by leonklingele** [comment]
Updated PR to include 'Signed-off-by' label

**Comment by LukasReschke** [comment]
LGTM

**Review by LukasReschke — APPROVED** [review]

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
