### PR TITLE
Catch forbidden http status code

### PR DESCRIPTION
**Pull request by rullzer**
If you try to do something on a DAV mount (external or federated share)
that is not allowed. We should not mark the storage as not available but
just fail somewhat gracefully.

Now by catching this and just properly returning the operation will just
fail (and notify the user) which is already a lot better then marking
the storage as unavailable and doing boom.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by kesselb** [comment]
Probably something for https://github.com/nextcloud/server/issues/17552 / https://github.com/nextcloud/server/issues/14797 :thinking:

**Comment by rullzer** [comment]
> Probably something for #17552 / #14797 thinking

I'm not sure.

**Comment by rullzer** [comment]
Ah mmm so maybe this needs more handling. As if it is forbidden in mkcol then we fail. Or in put. but if stat fails then I guess the storage is not availabe etc. @icewind1991 mind to have a look?

**Comment by icewind1991** [comment]
throwing a `ForbiddenException` is probably better

**Comment by rullzer** [comment]
@icewind1991 done

**Review by ChristophWurst — APPROVED** [review]

**Review by icewind1991 — APPROVED** [review]

**Pull request merged**
