### PR TITLE
Move personal auth token settings to Vue

### PR DESCRIPTION
**Pull request by ChristophWurst**
Required for #429 

Todo
- [x] Rewrite front-end in Vue
- [x] Implement server communication (ajax)
- [x] Fix design regressions
- [x] Add clipboardjs to new code
- [x] Requires https://github.com/nextcloud/server/pull/14410

Optional
- [ ] Switch to initial state API
- [x] Move (s)css to the bundle as well

Bugs
- [x] Clipboardjs vanishes when the copy `<a>` is clicked. The mouse has to be moved away and back to make it visible
- [x] Popovermenu does not close when "Rename" is clicked -> https://github.com/nextcloud/nextcloud-vue/pull/278

### CODE REVIEW

**Comment by ChristophWurst** [comment]
>     * Clipboardjs vanishes when the copy `<a>` is clicked. The mouse has to be moved away and back to make it visible

cc @juliushaertl @rullzer @skjnldsv for input. I assume the problem is that when the `a` is clicked the focus changes. I tried setting it manually but that doesn't help either. The mouse still has to move away and back to make the tooltip visiable.

**Comment by rullzer** [comment]
@ChristophWurst is that a regression or?

**Comment by ChristophWurst** [comment]
Yes, this is a regression in this PR.

**Comment by ChristophWurst** [comment]
This also reduces the number of requests on the personal security settings page by three.

**Review by juliusknorr — APPROVED** [review]

**Review by rullzer — CHANGES_REQUESTED** [review]
If create a new apptoken. And press done. The list of apptokens is not updated.

**Comment by ChristophWurst** [comment]
> If create a new apptoken. And press done. The list of apptokens is not updated.

Yep, https://github.com/nextcloud/server/pull/14392/files#diff-f57c51aacf630692a4a5d90e51cf3f11R86 was missing.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
