### PR TITLE
l10n: Change "rain" to "rainfall"

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
I looked a bit on the internet and it seems like rainfall is used when describing the quantity of the rain, so this change looks correct.

Maybe we should change keep 'rain' for the simple 'rain' category and only use rainfall for light rainfall, heav rainfall, ... but I'm not sure :)

**Comment by Valdnet** [comment]
@CarlSchwan I am asking for help in resolving the conflict and merging 😉.

**Comment by Valdnet** [comment]
I am asking for help in resolving the conflict and conducting tests. It looks like it is stuck.

@rakekniven Please check and approve 😉.

**Comment by Valdnet** [comment]
@artonge Can you help me with this PR? I am trying to resolve the conflict, but to no avail.

**Comment by artonge** [comment]
> @artonge Can you help me with this PR? I am trying to resolve the conflict, but to no avail.

Done, in future case:

```shell
# From your branch:
git rebase origin/master
npm ci
npm run build
git add dist/
git rebase --continue
git push --force-with-lease
```

**Review by artonge — APPROVED** [review]

**Comment by Valdnet** [comment]
@artonge Thanks a lot 👍. Mostly I only use GitHub which has limited capabilities for commits.

**Pull request merged**
