### PR TITLE
[Bugfix]: Titles of pages (dashboard, apps-settings, users-settings)

### LINKED ISSUE #43327: [Bug]: title of dashboard is "Dashboard - Dashboard - NextCloud"
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since updating from 28.0.1 to 28.0.2 Dashboard is displayed twice in the title.

Previously (28.0.1): 
Displayed `Dashboard - NextCloud`

Page source
```
<title>
			Dashboard - Nextcloud		</title>
```
Now (28.0.2):
Displayed  ` Dashboard - Dashboard - NextCloud`

Page source
```
<title>
			Dashboard - Dashboard - NextCloud		</title>
```
File and other groups seem unaffected. I wounder if its related to #42413

### Steps to reproduce

1. Update from 28.0.1 to 28.0.2

### Expected behavior

Dashboard title should be as it was in 28.0.1

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by arublov**
* Resolves: #43327 

## Summary

1. Change logic in title, added the condition:
- print application name only if it's equal to the page title

2. Changed on Settings/App from (Apps - Apps - Nextcloud) to (Settings - Apps - Nextcloud)
3. Changed on Users from (Users - Users - Nextcloud) to (Settings - Users - Nextcloud)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by arublov** [comment]
@emoral435 and @szaimen ,

Done ✅ Please review :)

**Review by emoral435 — APPROVED** [review]
Tested. and works on local dev env! Dashboard (main issue in the OG PR for a11y team) has correct semantic labeling, and so does all other templates / views 👍

Big thank you for the contribution from the team over at Nextcloud 💙

**Review by szaimen — APPROVED** [review]
🐘

**Comment by arublov** [comment]
@emoral435 / @szaimen , "Some checks were not successful" something happened on my side? Is there anything I can do to help with this?

**Comment by emoral435** [comment]
@arublov Yes, of course!
So, from the looks of it, it seems that the PHP just need some linting, which further steps can be seen in the error messages these actions / checks throw out:

image

They detail what the script ran to complete the action and if the status came back as a fail code or a success code. In this case, for PHP lint, it seems that you just need to run the lint action on your local machine, fix the changes, rebase the code to get it updates, and push the changes.

For the cypress failures, since we made frontend changes, it is likely that they are related, but I tried running them again. If they are still not passing by the time the linting has been fixed, I will fix it.

Feel free to ping me if this happens! :) Anything for our contributors 🫡😤

**Comment by arublov** [comment]
@emoral435 , cypress - still with errors, PHP lint - I've run and updated this PR.

But the thing is, why?) the right version has more clean and structured code.
Screenshot 2024-02-23 at 6 40 15 PM

**Comment by arublov** [comment]
@skjnldsv , resolved

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
@arublov thanks!
On an unrelated note, please favour `rebase` instead of `merge` to make your PR up to date again. That helps keeping the git history clean :)
image

**Pull request merged**
