### PR TITLE
Do not include mountpoints when calculating quota usage on WebDAV

### PR DESCRIPTION
**Pull request by juliusknorr**
Otherwise the quota calculation shown in the desktop client differs from how we calculate quota and show it in the web interface.

cc @misch7 as discussed

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Yeah sure. Altough I guess we'll get back complains at some point.
But yes it should be consistent.

**Review by icewind1991 — APPROVED** [review]

**Comment by rullzer** [comment]
CI fails

**Comment by rullzer** [comment]
> CI fails

ping

**Comment by juliushaertl** [comment]
Let's see what CI says about that.

**Pull request merged**
