### PR TITLE
Revert "Disable codecov comments"

### PR DESCRIPTION
**Pull request by LukasReschke**
Reverts nextcloud/server#1949

### CODE REVIEW

**Comment by rullzer** [comment]
I could do without the sunburst. But LGTM

**Comment by LukasReschke** [comment]
Let's remove the sunburst then.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
Thanks for removing the giant sunburst diagram at least! :) Good point @rullzer

**Pull request merged**
