### PR TITLE
getUnjailedPath() fix for duplicated parts

### LINKED ISSUE #32178: [Bug]: Can't open/view files, `disk_free_space(): No such file or directory`
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When navigating into folders (group folders in this case), into some of them (not all) we can't open anything (nor PDF neither Collabora) and the log is spammed with several errors:

The error seems to be similar to this one : 

- https://github.com/nextcloud/server/issues/30992

### Steps to reproduce

1. navigate into the tree
2. try to open files

### Expected behavior

Files should be readable

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "brume.felinn.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.4.1",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "\/etc\/nextcloud\/skeleton",
        "maintenance": false,
        "theme": "",
        "loglevel": 3,
        "updater.release.channel": "stable"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - apporder: 0.15.0
  - audioplayer: 3.3.0
  - bookmarks: 10.3.1
  - calendar: 3.2.2
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - dav: 1.21.0
  - event_update_notification: 1.5.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - groupfolders: 11.1.2
  - integration_gitlab: 1.0.3
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - richdocuments: 5.0.3
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - side_menu: 2.3.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_saml: 5.0.0
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - announcementcenter: 6.1.1
  - breezedark: 23.2.1
  - bruteforcesettings: 2.4.0
  - circles: 0.21.4
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - deck: 1.6.1
  - encryption
  - end_to_end_encryption: 1.9.1
  - federation: 1.10.1
  - files_external
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.9.0
  - recommendations: 0.8.0
  - spreed: 13.0.5
  - systemtags: 1.10.0
  - user_ldap
  - user_status: 1.0.0
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

**When accessing the folder**

```json
{"reqId":"Q2ceosRMwuaZuFF8Y3rV","level":3,"time":"2022-04-27T10:16:52+00:00","remoteAddr":"192.168.10.100","user":"ornanovitch","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/ornanovitch/Nid%20de%20Poule/01_ASSO_GNDP/03_ADMINISTRATION/01_COMPTABILIT%C3%89/01_JOURNAUX/03_BANQUE/02_Ecriture%20de%20compte","message":"disk_free_space(): No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#381","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"23.0.4.1","exception":{"Exception":"Error","Message":"disk_free_space(): No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#381","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":381,"function":"disk_free_space"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Jail.php","line":344,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","line":110,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Quota","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":534,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":330,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":765,"function":"getQuotaInfo","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"Sabre\\DAV\\{closure}","class":"Sabre\\DAV\\CorePlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":769,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1646,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":166,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6269181922fe7"}
```

**Also when accessing the folder**

```shell
{"reqId":"itwsJaP3uc7zryU0Pk9h","level":3,"time":"2022-04-27T10:17:23+00:00","remoteAddr":"192.168.10.100","user":"ornanovitch","app":"PHP","method":"GET","url":"/remote.php/dav/files/ornanovitch/Nid%20de%20Poule/01_ASSO_GNDP/03_ADMINISTRATION/01_COMPTABILIT%C3%89/01_JOURNAUX/03_BANQUE/02_Ecriture%20de%20compte/EXPORTS/ilovepdf_merged.pdf","message":"fopen(/home/__groupfolders/2/01_ASSO_GNDP/03_ADMINISTRATION/01_COMPTABILITÉ/01_JOURNAUX/03_BANQUE/02_Ecriture de compte/EXPORTS/ilovepdf_merged.pdf): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#363","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"23.0.4.1","exception":{"Exception":"Error","Message":"fopen(/home/__groupfolders/2/01_ASSO_GNDP/03_ADMINISTRATION/01_COMPTABILITÉ/01_JOURNAUX/03_BANQUE/02_Ecriture de compte/EXPORTS/ilovepdf_merged.pdf): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#363","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":363,"function":"fopen"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":301,"function":"fopen","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Jail.php","line":311,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","line":163,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":301,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Quota","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php","line":117,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":301,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\PermissionsMask","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1169,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1005,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":479,"function":"fopen","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":85,"function":"get","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpGet","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":166,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6269185528002"}
```

**When opening a file**

```shell
{"reqId":"itwsJaP3uc7zryU0Pk9h","level":4,"time":"2022-04-27T10:17:23+00:00","remoteAddr":"192.168.10.100","user":"ornanovitch","app":"webdav","method":"GET","url":"/remote.php/dav/files/ornanovitch/Nid%20de%20Poule/01_ASSO_GNDP/03_ADMINISTRATION/01_COMPTABILIT%C3%89/01_JOURNAUX/03_BANQUE/02_Ecriture%20de%20compte/EXPORTS/ilovepdf_merged.pdf","message":"Impossible d'ouvrir le fichier","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"23.0.4.1","exception":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Impossible d'ouvrir le fichier","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":85,"function":"get","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpGet","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":166,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":484,"CustomMessage":"--"},"id":"6269185527bdd"}
```

**After having left collabora**

```shell
{"reqId":"YGkzf9Z1RqjrELwJhqRo","level":3,"time":"2022-04-27T10:17:38+00:00","remoteAddr":"192.168.10.100","user":"ornanovitch","app":"index","method":"GET","url":"/apps/richdocuments/index?fileId=170638&requesttoken=qEAIDnw1WcQbJc6CEZ8dSnZdfrdVITi5SJgLPBFsyyg%3D%3A0AtCQDFta5J0FaPjQ9R6CSw3BO48ZRfhG9JDbF8Cqmw%3D&path=%2FNid%20de%20Poule%2F01_ASSO_GNDP%2F03_ADMINISTRATION%2F01_COMPTABILIT%C3%89%2F01_JOURNAUX%2F03_BANQUE%2F02_Ecriture%20de%20compte%2FEXPORTS%2FBQ_CM_01-04%3A21.xlsx","message":"fclose(): Argument #1 ($stream) must be of type resource, bool given in file '/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php' line 195","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"23.0.4.1","exception":{"Exception":"Exception","Message":"fclose(): Argument #1 ($stream) must be of type resource, bool given in file '/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php' line 195","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"fclose(): Argument #1 ($stream) must be of type resource, bool given","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php","line":195,"function":"fclose"},{"file":"/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php","line":207,"function":"getToken","class":"OCA\\Richdocuments\\TokenManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php","Line":195},"CustomMessage":"--"},"id":"626918552767a"}
```

**After having left the folder**

```shell
{"reqId":"P2a5qEmEgeNNulRfGRmy","level":3,"time":"2022-04-27T10:18:18+00:00","remoteAddr":"192.168.10.100","user":"ornanovitch","app":"PHP","method":"GET","url":"/apps/richdocuments/index?fileId=172039&requesttoken=qEAIDnw1WcQbJc6CEZ8dSnZdfrdVITi5SJgLPBFsyyg%3D%3A0AtCQDFta5J0FaPjQ9R6CSw3BO48ZRfhG9JDbF8Cqmw%3D&path=%2FNid%20de%20Poule%2F01_ASSO_GNDP%2F03_ADMINISTRATION%2F01_COMPTABILIT%C3%89%2F01_JOURNAUX%2F03_BANQUE%2F02_Ecriture%20de%20compte%2FBQ_CM_01-04%3A21-2.csv","message":"fopen(/home/__groupfolders/2/01_ASSO_GNDP/03_ADMINISTRATION/01_COMPTABILITÉ/01_JOURNAUX/03_BANQUE/02_Ecriture de compte/BQ_CM_01-04:21-2.csv): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#363","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"23.0.4.1","exception":{"Exception":"Error","Message":"fopen(/home/__groupfolders/2/01_ASSO_GNDP/03_ADMINISTRATION/01_COMPTABILITÉ/01_JOURNAUX/03_BANQUE/02_Ecriture de compte/BQ_CM_01-04:21-2.csv): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#363","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":363,"function":"fopen"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":301,"function":"fopen","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Jail.php","line":311,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","line":163,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":301,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Quota","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php","line":117,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":301,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\PermissionsMask","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1169,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1005,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":114,"function":"fopen","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php","line":194,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php","line":207,"function":"getToken","class":"OCA\\Richdocuments\\TokenManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"626918911a899"}
```

**Also after having left the folder**

```shell
{"reqId":"fYhOS3rGtIRLEnptenm5","level":3,"time":"2022-04-27T10:18:41+00:00","remoteAddr":"192.168.10.100","user":"ornanovitch","app":"index","method":"GET","url":"/apps/richdocuments/index?fileId=261951&requesttoken=qEAIDnw1WcQbJc6CEZ8dSnZdfrdVITi5SJgLPBFsyyg%3D%3A0AtCQDFta5J0FaPjQ9R6CSw3BO48ZRfhG9JDbF8Cqmw%3D&path=%2FNid%20de%20Poule%2F01_ASSO_GNDP%2F03_ADMINISTRATION%2F01_COMPTABILIT%C3%89%2F01_JOURNAUX%2F03_BANQUE%2F02_Ecriture%20de%20compte%2F2021_OCT-NOV%2FExtrait%20de%20comptes%20Compte%2007314%20000217903%2001%20COMPTE%20COURANT%20ASSOCIATION%20LE%20GRAND%20NID%20DE%20POULE%20au%202021-11-01.xlsx","message":"fclose(): Argument #1 ($stream) must be of type resource, bool given in file '/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php' line 195","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"23.0.4.1","exception":{"Exception":"Exception","Message":"fclose(): Argument #1 ($stream) must be of type resource, bool given in file '/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php' line 195","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"fclose(): Argument #1 ($stream) must be of type resource, bool given","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php","line":195,"function":"fclose"},{"file":"/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php","line":207,"function":"getToken","class":"OCA\\Richdocuments\\TokenManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php","Line":195},"CustomMessage":"--"},"id":"626918911a158"}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by solracsf**
See https://github.com/nextcloud/server/issues/32178 for complete context.
PR for fix submitted at https://github.com/nextcloud/server/issues/32178#issuecomment-1118648018 for review/CI tests.

It fixed those problems for everyone (me including).
Fix https://github.com/nextcloud/server/issues/32178

### CODE REVIEW

**Comment by solracsf** [comment]
Fix for failing S3 tests at https://github.com/nextcloud/server/pull/32318

**Comment by solracsf** [comment]
Ci is failing 😞
@RoggerTan can you check this codebase please?

**Comment by solracsf** [comment]
Doesn't seem the right fix (see original post comments), closing.

**Comment by RoggerTan** [comment]
Found the problem. 
[testMoveFromStorageJailed](https://github.com/nextcloud/server/blob/master/tests/lib/Files/Storage/CommonTest.php#L72) created 'foo.txt' file in 'foo' directory (root), then try to rename it to 'bar.txt'. strpos('foo.txt', 'foo') returned 0 to assumed it was duplicated path (although it wasn't). I think this shouldn't happen in production, as documents are stored in ncdata/{username}/files. 
Thanks @solracsf. I'll fix it to bypass the test soon.

**Pull request closed without merging**
