### PR TITLE
[stable20] Run unit tests against oracle

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #23882

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Psalm is unhappy about those two:

```
lib/private/Files/Stream/Encryption.php:449:16:error - UndefinedInterfaceMethod: Method OCP\Files\Cache\ICacheEntry::offsetGet does not exist
lib/private/Files/Stream/Encryption.php:501:59:error - InvalidScalarArgument: Argument 2 of OCP\Encryption\IEncryptionModule::decrypt expects string, int|non-empty-lowercase-string provided
```

**Comment by nickvergessen** [comment]
What? I updated the baseline after running it locally....

**Review by icewind1991 — CHANGES_REQUESTED** [review]
requires https://github.com/nextcloud/server/pull/24072 to be backported to

**Comment by rullzer** [comment]
> requires #24072 to be backported to

cherry-picked on this branch

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
