### PR TITLE
l10n: Triple dot to ellipsis.

### PR DESCRIPTION
**Pull request by rakekniven**
Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by gary-kim** [comment]
I feel like these triple to to ellipsis PRs are more than half of what you do here :).

**Review by gary-kim — APPROVED** [review]

**Comment by rakekniven** [comment]
> I feel like these triple dot to ellipsis PRs are more than half of what you do here :).

Hmmh, if you think…

**Comment by gary-kim** [comment]
> Hmmh, if you think…

I'll see if I can create a checker to check for triple dots in translations

**Review by CHRINIMUE — APPROVED** [review]

**Comment by CHRINIMUE** [comment]
Oh, ok. So I had implemented the three dots in the wrong way? 🙈 
Thanks @rakekniven for fixing it 👍

**Review by rullzer — APPROVED** [review]

**Pull request merged**
