### PR TITLE
fix(core): unsupported browser redirect url

### LINKED ISSUE #43142: [Bug]: Wrong redirection with the button Continue with this unsupported browser
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I try to access to Nextcloud 28.0.1 from an unsupported browser (Firefox ESR 102 on Windows).
I redirected on the page : https://HOST/index.php/unsupported
If a acknowledge with the button "Continue with this unsupported browser" i have a 404 error because the URI is in double. I redirected to  https://HOST/index.php/index.php/apps/dashboard/

### Steps to reproduce

1. Install Nextcloud 28.0.1 from archive
2. Login with unsupported browser
3. See the issue

### Expected behavior

Redirect to https://HOST/index.php/apps/dashboard/ instead of https://HOST/index.php/index.php/apps/dashboard/

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/43142

To easily try this, just use a php webserver on a freshly cloned server repo

### CODE REVIEW

**Comment by szaimen** [comment]
Hey @skjnldsv I'd like to test this but don't know how to get an unsupported browser onto my PC. Do you have any idea which browser I could try?

**Comment by skjnldsv** [comment]
> but don't know how to get an unsupported browser onto my PC.

On the dev tools you can change the user agent into the "other network conditions". You can select and edit a chrome version for example
image

**Review by szaimen — APPROVED** [review]
Tested and works

**Review by Pytal — CHANGES_REQUESTED** [review]
Doesn't seem to work when there is a webroot e.g. "/nextcloud" 🤔

**Comment by skjnldsv** [comment]
image
Fixed @Pytal

**Comment by skjnldsv** [comment]
image
Fixed @Pytal

**Review by Pytal — COMMENTED** [review]
Needs a quickfix, `ReferenceError: getRootUrl is not defined` 🙈

**Review by Pytal — APPROVED** [review]

**Pull request merged**
