### PR TITLE
Replace loading icon GIF with pure CSS in login button

### LINKED ISSUE #4470: login spinner looks ugly
You only see it for a few seconds but it always disturbs me, look at the screenshot:

login

You can almost see every individual pixel of the circle, by contrast the logout spinner looks much smoother:

logout

@nextcloud/designers anything we can do about it?

### PR DESCRIPTION
**Pull request by danxuliu**
Fixes #4470

Before:
before-login

After:
after-login

Instead of converting the button from `<input>` to `<a class="button">` (which required several CSS changes) I kept the button as is and applied the `icon-loading-small` class to a different element. I used the same approach as, for example, in the _Sharing_ tab of the details view of the Files app to position the icons to the right of the input fields, that is, the icon is absolutely positioned inside a wrapper that contains both the input field and the icon.

The margins used for the confirm-white icon are 23px and 23px, but the margins used for the loading icon are 22px and 24px, which serve as an example of the issue #5970.

Using a different element positioned on the button has a problem, though: visually, the icon is part of the button, so clicking on the icon should be the same as clicking on the button. As it is a different element that is not the case, so I used JavaScript to redirect clicks on the icon to the button (although it feels a little hacky...). Only clicks are taken into account; I do not know if this could cause an accessibility problem with other types of interactions, although as the icon is not focusable I suppose it would be ignored anyway.

Another option would have been to use `pointer-events: none` on the icon so it ignored the clicks and let the element underneath it (that is, the button) receive them. [It seems to have good support in browsers](http://www.caniuse.com/#feat=pointer-events), so it may be a better option than using JavaScript. Any thoughts on this?

Finally, please note that __I have not tested the rules added in `styles.scss`__, as I do not know where they are being used; I have added them based on their neighbour rules assuming that they are used somewhere along with _core/templates/login.php_, but I do not even know if that assumption is right!

### CODE REVIEW

**Comment by danxuliu** [comment]
There is another issue that I would like to get input from @nextcloud/designers: the color of the loading icon.

[The RGB values of the white variant of the pure CSS loading icon](https://github.com/nextcloud/server/blob/master/core/css/guest.css#L613) are `(150, 150, 150)` (with opacity 0.5) for the main circle and `(100, 100, 100)` for the dark border, while [the RGB values of the dark variant](https://github.com/nextcloud/server/blob/master/core/css/guest.css#L617) are `(187, 187, 187)` (with opacity 0.5) for the main circle and `(187, 187, 187)` for the dark border.

The RGB values of the white variant of the loading icon GIF are around `(200, 200, 200)` for the main circle, which roughly translates to a full white with 0.8 opacity on a black background (although the icon has no transparency), and `(100, 100, 100)` for the dark border, while the RGB values of the dark variant are around `(90, 90, 90)` for the main circle, which roughly translates to `(50, 50, 50)` with 0.8 opacity on a white background, and `(187, 187, 187)` for the white border.

The question is, should the colors of the pure CSS loading icon be left as is, or should they be updated to mimic the colors used by the loading icon GIF (or other colors)? I am refering only to the specific case of the loading icon on the login button, not in general.

Below you can see an example of the current colors, the colors modified to mimic the loading icon GIF (with a slight transparency in the main circle but not on the border), the colors modified to a middle ground between the current colors and the loading icon GIF (white variant with RGBA values `(200, 200, 200, 0.5)` for the main circle and `(200, 200, 200, 1.0)`for the dark border, dark variant with RGBA values `(50, 50, 50, 0.5)` for the main circle and `(50, 50, 50, 1.0)` for the dark border), and the colors modified taking into account the color of the text of the button (white variant with RGBA values `(255, 255, 255, 0.5)` for the main circle and `(255, 255, 255, 1.0)`for the dark border, dark variant with RGBA values `(0, 0, 0, 0.5)` for the main circle and `(0, 0, 0, 1.0)` for the dark border).

Current:
current-white
current-dark

Modified to mimic the loading icon GIF:
modified-white-gif
modified-dark-gif

Modified with a mix between current and loading icon GIF:
modified-white-mix
modified-dark-mix

Modified taking into account the color of the text of the button:
modified-white-font
modified-dark-font

**Comment by MorrisJobke** [comment]
> Another option would have been to use pointer-events: none on the icon so it ignored the clicks and let the element underneath it (that is, the button) receive them. It seems to have good support in browsers, so it may be a better option than using JavaScript. Any thoughts on this?

Yep - use it instead of the hacky way.

Regarding the colours: I would go for the last option, but keep it out of this PR. Once the instance is themed of course the spinner should also adjust, but only in cases it is in a primary button or the header bar. Those are the two types when the background is the same as the themed color and not white. Best would be of course if this could be done fully via transparency, but I guess this is not possible.

Also then the tweaks should reside in the theming app.

**Comment by skjnldsv** [comment]
Didn't test, but commits looks very good! 
Thank you for your work!! 👍😉

**Comment by pixelipo** [comment]
Great work, @danxuliu ! Tested and works as expected.

Regarding colors, I have one suggestion - don't use rgba. Rather, you should use `opacity: 0.5;` for alpha and existing color values (`$color-loadin*`) in [variables.scss](https://github.com/nextcloud/server/blob/master/core/css/variables.scss). while guess.css is still not _sassified_, it probably should (will?) be in the future, so let's be ready for that.

**Review by pixelipo — APPROVED** [review]
Works as expected, but I haven't tested dark version.

**Comment by skjnldsv** [comment]
| while guess.css is still not sassified , it probably should (will?) be in the future, so let's be ready for that.

I seriously doubt that. The scss engine isn't initialized before nextcloud setup. Therefore no scss compilation is allowed! :)

**Comment by pixelipo** [comment]
That's too bad, @skjnldsv - I see a lot of places where common color scheme is not preserved. We should try to figure out some other way to at least push common variables over to non-compiled css files. Perhaps we could add helper classes for those Sass variables? Like a variables.css file (improvising, beware possibly stupid idea ahead :wink: ):
```
.color-main-text {
  color: #000;
}
...
.color-loading {
  border-color: #969696;
}
```

**Comment by danxuliu** [comment]
@MorrisJobke
> > Another option would have been to use pointer-events: none on the icon so it ignored the clicks and let the element underneath it (that is, the button) receive them. It seems to have good support in browsers, so it may be a better option than using JavaScript. Any thoughts on this?
> 
> Yep - use it instead of the hacky way.

Done.

> Regarding the colours: I would go for the last option, but keep it out of this PR.

Ok, then this PR is ready for review.

> Also then the tweaks should reside in the theming app.

But only those for the dark variant, right? I mean, the colours for the _"white"_ variant should be set in the _guest.css_ file anyway so they are used as the default theme if the Theming app is disabled, shouldn't they?

@skjnldsv
> Thank you for your work!! 👍😉

@pixelipo
> Great work, @danxuliu

Thanks :-)

> Regarding colors, I have one suggestion - don't use rgba. Rather, you should use opacity: 0.5; for alpha and existing color values ($color-loadin*) in variables.scss. while guess.css is still not sassified, it probably should (will?) be in the future, so let's be ready for that.

Yes, a change in opacity with the same colour for both the main circle and the dark border is what it is used in the last two proposals. Anyway, let's discuss the details in another pull request as requested by @MorrisJobke ;-)

**Review by MorrisJobke — APPROVED** [review]
Tested and looks awesome

**Review by MorrisJobke — APPROVED** [review]

**Comment by jancborchardt** [comment]
@danxuliu awesome work! :) A follow-up pull request with the color changes as you proposed in https://github.com/nextcloud/server/pull/5972#issuecomment-320073720 would be cool! The spinner should have the same color as the text, so I agree with @MorrisJobke that the last option looks best :)

**Pull request merged**
