### PR TITLE
Run all matrix mysql jobs only on PHP 7.1

### PR DESCRIPTION
**Pull request by MorrisJobke**
As discussed with @LukasReschke and @rullzer

### CODE REVIEW

**Comment by rullzer** [comment]
I forgot the reasoning here.

But this basically makes us assume that the different php versions handle db's the same way. I'm fine with that but it is kind of tricky.

**Comment by rullzer** [comment]
Also conflicts

**Comment by rullzer** [comment]
also conflicts

**Comment by MorrisJobke** [comment]
> I forgot the reasoning here.

No real need to waste a lot of computing time here. ;)



> Also conflicts

Fixed.

**Pull request closed without merging**
