### PR TITLE
Inputs border to main bg and fix white inputs

### PR DESCRIPTION
**Pull request by skjnldsv**
During the variable pr, the white radio/checkboxes have been broken. 
They need to be base on the white colour only, and not relative to the text colour or bg colour.

Therefore, this is fixed.

On the other hand, the border & bg of the inputs needs to be based on the main background colour, not the text. This will ensure a better contrast! :)

@nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
Bump? 😭

**Comment by juliushaertl** [comment]
@skjnldsv Maybe you can add some variables for the border color values? Otherwise it will get messy to maintain those different transparency levels used.

**Comment by skjnldsv** [comment]
Hum, it's not supposed to be edited. But it doesn't hurt I guess! :)

**Comment by skjnldsv** [comment]
@juliushaertl Done ;)
I don't think we should add this to the variable.scss since it's not supposed to be easily changeable. It's just to be easier to understand.

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
@nextcloud/designers the drone fails but not because of this :)

**Review by rullzer — APPROVED** [review]

**Pull request merged**
