### PR TITLE
Allow rich object strings in messages as well

### PR DESCRIPTION
**Pull request by nickvergessen**
So comment notifications can have user mentions in the notification message text

Forgot that in #1800

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by LukasReschke** [comment]
```
+ git init
0s
2
Initialized empty Git repository in /drone/src/github.com/nextcloud/server/.git/
0s
3
+ git remote add origin https://github.com/nextcloud/server.git
0s
4
+ git fetch --no-tags --depth=1 origin +refs/pull/1937/merge:
0s
5
fatal: write error: No space left on device
6s
6
fatal: index-pack failed
6s
7
exit status 128
```

@MorrisJobke Fix it .;)

**Comment by nickvergessen** [comment]
Rebased, lets see if we have more luck

**Comment by rullzer** [comment]
LGTM :tada:

**Pull request merged**
