### PR TITLE
Move OC.get and OC.set to the bundle

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
What is it used for? :thinking: 

Code looks good though :wink:

**Comment by georgehrke** [comment]
What exactly is the purpose of OC.get and OC.set? I've never seen anyone use them.

**Comment by ChristophWurst** [comment]
I have no idea tbh. It's some pretty old code by @icewind1991: https://github.com/nextcloud/server/commit/8990855f88c8cf0803bcf7220699c54b46b0d546.

**Comment by ChristophWurst** [comment]
https://github.com/orgs/nextcloud/projects/31#card-21153825

**Review by georgehrke — APPROVED** [review]

**Pull request merged**
