### PR TITLE
Add cbz preview

### PR DESCRIPTION
**Pull request by murlock**
This PR will add preview of CBZ (if enabled): it will use the first file as source to generate thumbnail:
it still requires to add `OC\\Preview\\CBZ'` in `config.php`.

Notes:
- It could be extended for `cbr` with help of use of `unrar` external commands.
- It could be partially factorized by `Preview\Image.php` to reuse logic instead of copy/paste
- It is enabled only for LocalStorage at this time

Let me know how

### CODE REVIEW

**Comment by kesselb** [comment]
Thank you @murlock :+1: Mind to rebase your branch? Then we can run the tests again.

**Comment by murlock** [comment]
Of course, I'll rebase it this week

**Comment by kesselb** [comment]
> The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh 
And commit the result

**Comment by murlock** [comment]
Done

**Comment by rullzer** [comment]
I must say I'm not a fan of adding more of this into the server code.
It makes maintaining and updating it very hard.

@icewind1991 @MorrisJobke @ChristophWurst we should have the file/mimetype list more flexible for apps to register them. And then also make it even easier for apps to register preview providers. So we can fasilitate this as an app. I think in the end that would make things easier.

**Comment by murlock** [comment]
I can work on an example and move this PR as external application.

**Comment by murlock** [comment]
This will be done in dedicated app

**Pull request closed without merging**
