### PR TITLE
Fix update notification text

### PR DESCRIPTION
**Pull request by MorrisJobke**
- thanks to ungesundes_halbwissen @ transifex

@LukasReschke @schiessle

### CODE REVIEW

**Comment by ungesundes-halbwissen** [comment]
Sorry for nitpicking, but IMO the suggested correction does not make it better. Please consider changing it to one of the following (in descending order):

- Only notification for app updates are available, because the selected update channel does not allow notifications for the server itself.
- Only notification for app updates are available, because the selected update channel does not allow other notifications.
- Only notification for app updates are available, because the selected update channel does not allow low-level notifications.

This said, I might get it all wrong and the sense behind it escapes me. in this case, please do not hesitate to correct me :-)

**Comment by MorrisJobke** [comment]
All it should say is: There won't be any notifications shown for the server, because there would be either always one (daily) or they are handled manually anyways (git). How to make this more easy to understand?

Maybe @jospoortvliet can help here.

**Comment by ungesundes-halbwissen** [comment]
If you think my initial suggestion is too misleading, I'd go for two separate, less complicated sentences to get the meaning across:

Please note, that notifications are available for apps only. The selected update channel does not support updates (manual) or makes dedicated notifications obsolete (daily).

**Comment by MorrisJobke** [comment]
I updated the text.

**Comment by ungesundes-halbwissen** [comment]
Thx for your consideration. Lgtm 👍

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
> Thx for your consideration. Lgtm 👍

Thanks! Let's count this as a 👍 and merge it :)

**Pull request merged**
