### PR TITLE
get shared storage storage id without setting up the storage

### PR DESCRIPTION
**Pull request by icewind1991**
Alternative to #813

### CODE REVIEW

**Comment by schiessle** [comment]
Thanks @icewind1991  :+1:

**Comment by schiessle** [comment]
We should try to get this in stable10 for the beta, fixes potential upgrade bug:  https://github.com/owncloud/core/issues/25557

@icewind1991 can you prepare the backport? Thanks!

**Comment by icewind1991** [comment]
stable10: https://github.com/nextcloud/server/pull/822

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
