### PR TITLE
21.0.6

### PR DESCRIPTION
**Pull request by blizzz**
Changes relative to RC1

* #29520
* #29550
* #29551
* #29576
* #29579
* #29596
* #29599
* [text#1895](https://github.com/nextcloud/text/pull/1895) Bump @babel/core from 7.15.5 to 7.15.8
* [viewer#1056](https://github.com/nextcloud/viewer/pull/1056) Build(deps-dev): bump babel-loader from 8.2.2 to 8.2.3

Pending PRs

* none

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by szaimen** [comment]
Would be nice to wait for #29629

**Comment by blizzz** [comment]
> Would be nice to wait for #29629

is this critical to go in after RC1, right before final?

**Comment by szaimen** [comment]
> is this critical to go in after RC1, right before final?

Thats up to you, I would say.

**Comment by blizzz** [comment]
> > is this critical to go in after RC1, right before final?
> 
> Thats up to you, I would say.

I don't have the impression tbh.

**Comment by szaimen** [comment]
> I don't have the impression tbh.

Then lets merge this after the release 👍

**Pull request merged**
