### PR TITLE
Add support for sending the password for a link share by Nextcloud Talk

### PR DESCRIPTION
**Pull request by danxuliu**
Requires nextcloud/spreed#1273

Sending the password by Nextcloud Talk for a link share behaves slightly different than [when doing it for an e-mail share](https://github.com/nextcloud/server/pull/10238). When an e-mail share is protected with a password an e-mail is sent with the password. Due to this, when the password is protected by Talk a new password must be always set; otherwise the recipient would already have the password, and thus she would not need to request it to the sharer and protecting it by Talk would be pointless.

However, in the case of link shares, just setting the password does not disclose it to anyone; the sharer must explicitly send it to someone to be known. Therefore, when protecting the password of a link share by Talk it is not mandatory to set a different password than the one set before; protecting the password by Talk in this case is an additional step to protecting the share with a password. Due to this the checkbox to protect the password by Talk is shown only when there is a password set for the link share.

share-link-menu-no-password
share-link-menu-password

**Reviewers:** Although the Talk counterpart is still in development state the server part is ready for review and can be merged now even if the Talk part is not ready yet; the missing parts in Talk are just better naming of rooms and a more useful text in the notifications, but besides that it just works (or, at least, it should :-) ).

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Code looks good. And yay for tests

**Review by skjnldsv — COMMENTED** [review]
:elephant:

**Review by skjnldsv — APPROVED** [review]
:elephant: :elephant:

**Comment by MorrisJobke** [comment]
@danxuliu Could you resolve the conflicts? Most likely due to #12163

**Comment by MorrisJobke** [comment]
CI failure due to the newly added "hide_download" setting ;)

**Comment by danxuliu** [comment]
>  CI failure due to the newly added "hide_download" setting ;)

"Someone" forgot to run the PHP tests before pushing... :-P Fixed now, and as an extra I also added some missing (minor) tests for _notes_ and _hide download_ ;-)

**Comment by MorrisJobke** [comment]
CI failure is a segfault in the memcache tests -> ignore it.

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Comment by MorrisJobke** [comment]
I will wait with the merge of this after I merged https://github.com/nextcloud/server/pull/11844

**Comment by MorrisJobke** [comment]
@danxuliu The failing acceptance tests in here are the ones you mentioned that they also fail on master, right?

**Comment by danxuliu** [comment]
I have fixed the rendering by making the view to render again [only when the password changes](https://github.com/nextcloud/server/pull/11875/commits/376704e83413d093d596f1b9168daf24907189aa#diff-da7df34db49581af77bd59e4f269dc36R100); it is not optimal, but at least it does not render again the whole view whenever a link share changed (and thus respects the changes made in #11844 ;-) ).

>  The failing acceptance tests in here are the ones you mentioned that they also fail on master, right?

Yes, fixed in #12215

**Comment by jancborchardt** [comment]
Especially considering this added _yet another_ entry to the menu, I would really love your feedback on https://github.com/nextcloud/server/issues/12178 ;)

**Pull request merged**
