### PR TITLE
Use SettingsSection in workflowengine settings

### PR DESCRIPTION
**Pull request by CarlSchwan**
Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Comment by CarlSchwan** [comment]
ci failure is unrelated, (php-cs issue already fixed in master)

**Comment by artonge** [comment]
Rebased to fix CI (linting warnings)

**Review by artonge — APPROVED** [review]

**Comment by skjnldsv** [comment]
Tests are failing

`Node / test (pull_request) Failing after 1m — test`

**Pull request merged**
