### PR TITLE
feat: Update supported PostgreSQL versions

### LINKED ISSUE #48495: Support PostgreSQL 17
Current i got a Warning:

> PostgreSQL version "17.0" detected. PostgreSQL >=12 and <=16 is suggested for best performance, stability and functionality with this version of Nextcloud.

### PR DESCRIPTION
**Pull request by susnux**
* Requires https://github.com/nextcloud/docker-ci/pull/680
* Resolves https://github.com/nextcloud/server/issues/48495
* Documentation: https://github.com/nextcloud/documentation/pull/12363

## Summary
12 is now EOL but 17 was released and should be supported and tested.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
Btw I use MySQL 9.x since many months without an issue :D

**Comment by nickvergessen** [comment]
CI fails :P

**Comment by susnux** [comment]
> I use MySQL 9.x since many months without an issue :D

They have so short lifespan, I would wait for 9.7 lts. Otherwise we need to update the workflows regularly, no?

**Comment by nickvergessen** [comment]
I was more talking about the warning in the setup check.
Doctrine is also testing against the latest 9.x:
https://github.com/doctrine/dbal/blob/4.2.x/.github/workflows/continuous-integration.yml#L375

So I guess it would be nice to add it. 
- 9.0 was released in July https://dev.mysql.com/doc/relnotes/mysql/9.0/en/
- 9.1 was released in October https://dev.mysql.com/doc/relnotes/mysql/9.1/en/

So ~once per our major. Sounds good enough?

**Comment by susnux** [comment]
> So ~once per our major. Sounds good enough?

Well, yes that makes sense. So we can spot issues early.
But would you also add this to the setup check?

**Comment by susnux** [comment]
> "backport requested" is checked but i do not see any backport

Just means backports are requested if needed. We do not backport features so there is no backport.

**Pull request merged**
