### PR TITLE
[Copy] New core setting : shareapi_only_share_with_group_members_exclude_gro…

### PR DESCRIPTION
**Pull request by artonge**
Copy of https://github.com/nextcloud/server/pull/38173 to hopefully have it merged.

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
```
There were 7 errors:

1) Tests\Contacts\ContactsMenu\ContactsStoreTest::testGetContactsWhenUserIsInExcludeGroups
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:219
/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:165
/home/runner/actions-runner/_work/server/server/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php:249

2) Tests\Contacts\ContactsMenu\ContactsStoreTest::testGetContactsOnlyShareIfInTheSameGroup
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:219
/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:165
/home/runner/actions-runner/_work/server/server/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php:320

3) Tests\Contacts\ContactsMenu\ContactsStoreTest::testGetContactsOnlyEnumerateIfInTheSameGroup
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:219
/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:165
/home/runner/actions-runner/_work/server/server/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php:394

4) Tests\Contacts\ContactsMenu\ContactsStoreTest::testGetContactsOnlyEnumerateIfPhoneBookMatchWithOwnGroupsOnly
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:219
/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:165
/home/runner/actions-runner/_work/server/server/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php:533

5) Tests\Contacts\ContactsMenu\ContactsStoreTest::testGetContactsOnlyEnumerateIfPhoneBookOrSameGroupInOwnGroupsOnly
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:219
/home/runner/actions-runner/_work/server/server/lib/private/Contacts/ContactsMenu/ContactsStore.php:165
/home/runner/actions-runner/_work/server/server/tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php:686

6) OCA\Settings\Tests\Settings\Admin\SharingTest::testGetFormWithoutExcludedGroups
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

/home/runner/actions-runner/_work/server/server/apps/settings/lib/Settings/Admin/Sharing.php:87
/home/runner/actions-runner/_work/server/server/apps/settings/tests/Settings/Admin/SharingTest.php:178

7) OCA\Settings\Tests\Settings\Admin\SharingTest::testGetFormWithExcludedGroups
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

/home/runner/actions-runner/_work/server/server/apps/settings/lib/Settings/Admin/Sharing.php:87
/home/runner/actions-runner/_work/server/server/apps/settings/tests/Settings/Admin/SharingTest.php:270
```

**Review by susnux — APPROVED** [review]

**Comment by zak39** [comment]
Hi @artonge :)

Why did you create a copy of PR https://github.com/nextcloud/server/pull/38173 ?

**Comment by artonge** [comment]
> Why did you create a copy of PR #38173 ?

For some CI steps to get executed. But it looks like we just moved them from drone to GH actions this week.

Can you try to rebase your PR ?

You will need to add the following changes to make tests greens:
- [apps/settings/tests/Settings/Admin/SharingTest.php](https://github.com/nextcloud/server/pull/43186/files#diff-e026f42c7a963e58e31fda9b288f348ba8cc988f537df0d88de84f400c68b854)
- [tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php](https://github.com/nextcloud/server/pull/43186/files#diff-c3ffe4d47c912fe61d37caa623f8a0030a30aa4ae1b7fea23153031e6e067cb0)

You will also need to compile the front-end code again.

We can have a call tomorrow at 16h to do it together to make sure that your PR is merged this week.

**Comment by zak39** [comment]
> > Why did you create a copy of PR #38173 ?
> 
> For some CI steps to get executed. But it looks like we just moved them from drone to GH actions this week. It is also easier for us to rebase and edit if the source branch is in our repo.
> 
> Can you try to rebase your PR ?
> 
> You will need to add the following changes to make tests greens:
> 
>     * [apps/settings/tests/Settings/Admin/SharingTest.php](https://github.com/nextcloud/server/pull/43186/files#diff-e026f42c7a963e58e31fda9b288f348ba8cc988f537df0d88de84f400c68b854)
> 
>     * [tests/lib/Contacts/ContactsMenu/ContactsStoreTest.php](https://github.com/nextcloud/server/pull/43186/files#diff-c3ffe4d47c912fe61d37caa623f8a0030a30aa4ae1b7fea23153031e6e067cb0)
> 
> 
> You will also need to compile the front-end code again.
> 
> We can have a call tomorrow at 16h to do it together to make sure that your PR is merged this week.

Sure, I'm going to rebase and build our PR in the early afternoon.
I will create an appointment with you :+1:

Thanks :slightly_smiling_face:

**Comment by smarinier** [comment]
Hi, the documentation PR is here: [](https://github.com/nextcloud/documentation/pull/11537)

**Comment by smarinier** [comment]
Hi, the documentation PR is here : https://github.com/nextcloud/documentation/pull/11537

**Pull request closed without merging**
