### PR TITLE
Allow limit and offset in webdav search

### PR DESCRIPTION
**Pull request by rullzer**
This will allow the android client to do smarter image display by limiting the returned set. @tobiasKaminsky

### CODE REVIEW

**Comment by rullzer** [comment]
Requesting backport since the change is so small. And would be good to have this funcitonality for the clients also on 13.

**Comment by icewind1991** [comment]
The problem is that search results from multiple storages are merged, which means that the limit/offset is applied to the results of each individual storage, not the the full result set.

I've discussed this with @mario before and we came to the conclusion that for now it's best to cache all results on the server only return a subset to the client where the client would use a "search token" so the server can use the cached results for the next page

**Comment by rullzer** [comment]
Caching search results will be huge... for what I discussed with @tobiasKaminsky we just need the limit. This we could of course also apply that after all the data is retrieved.

**Comment by mario** [comment]
@rullzer this brings the limit in the way you want it. We need to cache, otherwise, you NEVER get exactly the same data and the pages might change, results might change, etc. So much mess.

**Comment by rullzer** [comment]
Caching is just not a viable option. Lets say I want to search for all the images on my instance. This will return roughly 30k entries. Now caching this will be several MB.

Where will you cache this? When will this cache expire? How does this scale if you have a few thousand users on your instance?

And even if you manage to solve that this still doesn't solve the fact that this cache can also easily be out of date. By the time I get to the end of scrolling trough my 30k pictures somebody could have deleted or renamed a folder. leaving me with broken paths and previews in the client.

The way I see it this search is just another way of querying the database. So you have the same issues. You database also doesn't solve them by caching datasets for you if you use limit and offset.

**Comment by rullzer** [comment]
anyway if it is per storge then this is maybe not the best approach. Probably best to just fetch per day then as discused already...

**Pull request closed without merging**
