### PR TITLE
Add explanation text to SSL root certificates

### PR DESCRIPTION
**Pull request by jancborchardt**
Can anyone explain to me though what it is so I can add the actual text @icewind1991 @karlitschek @LukasReschke 

Also – why is this in the personal settings of every user? This sounds awfully admin-like and technical to me.

ref nextcloud/server#4478 nextcloud/server#4540

### CODE REVIEW

**Comment by MariusBluem** [comment]
> Also – why is this in the personal settings of every user? This sounds awfully admin-like and technical to me.

I think this is only on personal page if you have enabled external storages app, where you might need to import own certificates to reach specific mounts for user-specified storages 😉 But I have to agree with you. @jancborchardt

**Comment by karlitschek** [comment]
Nice. If you as core contributor need explanation what this is then it is pretty clear that we need to provide explanation to 'normal' users too.

**Comment by LukasReschke** [comment]
> Also – why is this in the personal settings of every user? This sounds awfully admin-like and technical to me.

As a remark: I still consider it a bad functionality design that we allow regular users to accept any SSL certificates. Should be an admin only functionality, but well, I'm repeating myself.

But yes, @MariusBluem explanation is as usual correct 😉

**Comment by jancborchardt** [comment]
Ok, so how can we force this to be part of the »External storages« section, just below it? Currently it’s broken up by the twofactor stuff. It shouldn’t even get its own navigation entry. It was like that before and thus a regression.

**Comment by MariusBluem** [comment]
What about removing this section and adding this `upload custom TLS certificate`-section as an individual storage popup to the (few) use-case storages where its really needed 🤔 @icewind1991 

This could also harden Nextcloud security-wise if we restrict the certificates to the individual storages and not to the whole user, am I right 😁 @LukasReschke

**Comment by jancborchardt** [comment]
@icewind1991 @LukasReschke so how do we proceed here? Remove or relayout?

**Comment by MorrisJobke** [comment]
This one here is not useful. Please open an issue describing the actual issue.

**Pull request closed without merging**
