### PR TITLE
Fetch translate for Tags from files app

### LINKED ISSUE #19754: No display of the translated word "Tags"
### Steps to reproduce

1. Select file details, e.g. pdf.
2. Choose three dots for the file from the menu.

### Expected behaviour
The word "Tags" translated.

### Actual behaviour
The word "Tags" has not been translated.

obraz

All translations in Transifex of the word were translated much earlier than version 18.0.1.

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

### PR DESCRIPTION
**Pull request by kesselb**
Fix #19754 

Thanks @Valdnet :+1:

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Please rebase :)

**Comment by juliushaertl** [comment]
Backport in https://github.com/nextcloud/server/pull/19762

**Pull request merged**
