### PR TITLE
[stable13] allow local delivery of schedule message while prohibiting FreeBusy requests 

### PR DESCRIPTION
**Pull request by georgehrke**
Backport of  #11822

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Seems to do the trick

**Comment by georgehrke** [comment]
Related CI issues, fixing ...

**Comment by georgehrke** [comment]
Fixed CI issues as in remove `string` typehinting for PHP5 compatibility

**Review by MorrisJobke — APPROVED** [review]
🐘

**Comment by MorrisJobke** [comment]
```
There was 1 failure:

1) Test\User\DatabaseTest::testSearch
Failed asserting that 3 is identical to 2.

/drone/src/github.com/nextcloud/server/tests/lib/User/Backend.php:112
```

**Comment by georgehrke** [comment]
@MorrisJobke not sure how that failure is related. I didn’t touch anything even remotely close to the user backends

**Comment by rullzer** [comment]
Most likely isn;t, It is some timing issue somewhere. I restarted CI to double check.

**Comment by rullzer** [comment]
yep: https://drone.nextcloud.com/nextcloud/server/11772

**Pull request merged**
