### PR TITLE
[stable25] fix event moving

### PR DESCRIPTION
**Pull request by tcitworld**
Manual backport of https://github.com/nextcloud/server/pull/37046

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by solracsf — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]

**Comment by blizzz** [comment]
please fix the signoff

**Comment by blizzz** [comment]
also drone is fully red

**Comment by tcitworld** [comment]
Should be fine

**Review by ChristophWurst — APPROVED** [review]

**Comment by blizzz** [comment]
related?

```
1) OCA\DAV\Tests\unit\CalDAV\CalDavBackendTest::testSearchPrincipal
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 END:VTIMEZONE\n
 BEGIN:VEVENT\n
 DTSTART;TZID=Europe/Berlin:20160419T130000\n
-SUMMARY:My Test (public)\n
-CLASS:PUBLIC\n
+SUMMARY:My Test (confidential)\n
+CLASS:CONFIDENTIAL\n
 TRANSP:OPAQUE\n
 STATUS:CONFIRMED\n
 DTEND;TZID=Europe/Berlin:20160419T140000\n
@@ @@
 LAST-MODIFIED:20160419T074202Z\n
 DTSTAMP:20160419T074202Z\n
 CREATED:20160419T074202Z\n
-UID:2e468c48-7860-492e-bc52-92fa0daeeccf.1461051722310-1\n
+UID:2e468c48-7860-492e-bc52-92fa0daeeccf.1461051722310-3\n
 END:VEVENT\n
 END:VCALENDAR'
```

**Comment by blizzz** [comment]
→ 25.0.8

**Comment by szaimen** [comment]
So merge @ChristophWurst ?

**Pull request merged**
