### PR TITLE
Fix webdav support for OneNote clients

### PR DESCRIPTION
**Pull request by brandonkirsch**
Microsoft OneNote WebDAV Client requires some special handling on the server side that is enabled by User Agent detection.  This PR updates the User Agent detection string to be compatible with all versions of OneNote.

### CODE REVIEW

**Comment by brandonkirsch** [comment]
Current version of One Note has User Agent string:

OneNote/16.0.8431.2110 (Windows/6.1; Desktop WOW64; en-US; Desktop app; LENOVO/20AQ006HUS)

**Review by rullzer — APPROVED** [review]
Pfff I hate this magic... but yeah fair enough :see_no_evil:

**Comment by nickvergessen** [comment]
No microsoft anymore?

**Comment by brandonkirsch** [comment]
No, over the years they have removed "Microsoft", "Office" and the release year from User Agent. Thanks for reviewing the patch it will be easier for me to stay up to date.

**Review by schiessle — APPROVED** [review]
no idea about OneNote, but it sounds reasonable

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer @schiessle I guess we should backport this to stable13 at least, right?

**Comment by schiessle** [comment]
@MorrisJobke yes, I think it would make sense... @brandonkirsch do you want to create a PR for the backport angainst stable13? This would be awesome!

**Comment by MorrisJobke** [comment]
Backported in #9236

**Pull request merged**
