### PR TITLE
chore: use local variable for remote address

### PR DESCRIPTION
**Pull request by miaulalala**
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included 
- [ ] ~~Screenshots before/after for front-end changes~~
- [ ] ~~Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required~~
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by miaulalala** [comment]
Drone failure unrelated (?):

```
latest: Pulling from nextcloud/continuous-integration-alpine-git
--
2 | Digest: sha256:d4aa4eb5c7f6923bd80454a44722f0e35f2916e08f2627210df18652062661b3
3 | Status: Image is up to date for ghcr.io/nextcloud/continuous-integration-alpine-git:latest

```

**Pull request merged**
