### PR TITLE
Sort favorite files first

### PR DESCRIPTION
**Pull request by ryanwr**
Shows the favorited files first in the file list, Issue #1802 

I'd appreciate feedback on this!

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Awesome! I tested it with a directory with many files (where pagination is used) and it works fine 👍

**Comment by MorrisJobke** [comment]
@ryanwr There is only the sign-off missing. See https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work for more details about it. To fix this you could do `git commit --amend -s` then the sign-off message is added and you only need to force push (because you have changed an existing commit) via `git push --force origin feature-sort-favorite`.

Thanks a lot for your contribution 😃 Feel free to join our IRC channel #nextcloud-dev on freenode and check out other starter issues: https://github.com/nextcloud/server/labels/starter%20issue

**Comment by ryanwr** [comment]
Thanks!

@MorrisJobke It should be signed off now! 😄

**Comment by ryanwr** [comment]
Looks like drone ci failed, doesn't look related to my changes though

**Comment by rullzer** [comment]
Agreed looks unrelated.
Lets merge this. But we probabaly need js tests for this behaviour. Just so it doesn't break.

**Comment by jancborchardt** [comment]
@ryanwr awesome work! :) Sometimes when favoriting a file further down it seems to jump up a row.
Did you intend for it to jump up all the way, or nothing to happen until next reload / navigation / sort change?

**Comment by nickvergessen** [comment]
There is no jumping here

**Comment by ryanwr** [comment]
There shouldn't be any jumping, it shouldnt change anything until it's sorted again by reloading or resorting

**Comment by jancborchardt** [comment]
Ok, maybe a problem with my dev setup.

**Pull request merged**
