### PR TITLE
Update root.crl due to revocation of transmission.crt

### PR DESCRIPTION
**Pull request by MorrisJobke**
Due to https://github.com/nextcloud/app-certificate-requests/pull/360

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by nickvergessen** [comment]
This somehow broke all appstore apps

**Comment by MorrisJobke** [comment]
> This somehow broke all appstore apps

All? ... Is there more details than "it breaks things"? What is the error? Any logs?

**Comment by rullzer** [comment]
> This somehow broke all appstore apps

No it did not
The guzzle update did

**Comment by rullzer** [comment]
See https://github.com/nextcloud/server/pull/25088

**Pull request merged**
