### PR TITLE
Change header semantic in the user status dialog

### LINKED ISSUE #35098: Headings need to be h2
@jancborchardt @PVince81 @Pytal could you please give me some examples where should i check headings? I've checked a bit and could find them in ```app-sidebar-header```, ```tags```, everywhere in ```settings/``` (besides ```settings/user```) -> have already ```<h2>```. Besides this there are sites with tables. And i don't really know where should i place ```<h2>``` in this case.

Thanks!

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes https://github.com/nextcloud/server/issues/35098

| Before      | After |
| ----------- | ----------- |
| Screenshot from 2022-11-28 17-12-45      | Screenshot from 2022-11-28 17-13-42       |

### CODE REVIEW

**Comment by szaimen** [comment]
@JuliaKirschenheuter can you please post a before after screeenshot? Thanks :)

**Review by ChristophWurst — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
