### PR TITLE
mail-template - don't show hyphen if slogan is empty

### LINKED ISSUE #25174: Hyphen is shown after instance name in email footer, even when slogan is undefined or empty
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Unset the slogan using the "Themeing" app
2. Send a test email via "Basic Settings"

### Expected behaviour
In case the slogan is undefined, the hyphen in the email footer should not be displayed, as is the case for the login page. E. g. "Nextcloud"

### Actual behaviour
The hyphen is displayed, looking a little weird. E. g. "Nextcloud -"

### Server configuration
Irrelevant in this case; See info below

### Additional information
I've traced back the cause for the issue to the following line in the EmailTemplate class: https://github.com/nextcloud/server/blob/3a30ac495bd9663ef8233aacc8ce5b21a8adce67/lib/private/Mail/EMailTemplate.php#L623

Theroetically the slogan needs a simple empty check. However, I'm not sure if this is the correct solution, as I'm not familiar with how the internals of the themeing system work. The slogan being a localized value is actually new for me.

### PR DESCRIPTION
**Pull request by szaimen**
Fix #25174
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Comment by szaimen** [comment]
The test failures are unrelated, afaics.
@nextcloud/server please review

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by LukasReschke** [comment]
@szaimen I don't think they are all unrelated. Check https://drone.nextcloud.com/nextcloud/server/6463/9/4

```
-				<p class="text-center float-center" align="center" style="Margin:0;Margin-bottom:10px;color:#C8C8C8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen-Sans,Ubuntu,Cantarell,'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:400;line-height:16px;margin:0;margin-bottom:10px;padding:0;text-align:center">TestCloud - <br>This is an automatically sent email, please do not reply.</p>\n
157 | +				<p class="text-center float-center" align="center" style="Margin:0;Margin-bottom:10px;color:#C8C8C8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen-Sans,Ubuntu,Cantarell,'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:400;line-height:16px;margin:0;margin-bottom:10px;padding:0;text-align:center">TestCloud<br>This is an automatically sent email, please do not reply.</p>\n
158

<br class="Apple-interchange-newline">
```

**Comment by szaimen** [comment]
> @szaimen I don't think they are all unrelated. Check https://drone.nextcloud.com/nextcloud/server/6463/9/4
> 
> ```
> -				<p class="text-center float-center" align="center" style="Margin:0;Margin-bottom:10px;color:#C8C8C8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen-Sans,Ubuntu,Cantarell,'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:400;line-height:16px;margin:0;margin-bottom:10px;padding:0;text-align:center">TestCloud - <br>This is an automatically sent email, please do not reply.</p>\n
> 157 | +				<p class="text-center float-center" align="center" style="Margin:0;Margin-bottom:10px;color:#C8C8C8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen-Sans,Ubuntu,Cantarell,'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:400;line-height:16px;margin:0;margin-bottom:10px;padding:0;text-align:center">TestCloud<br>This is an automatically sent email, please do not reply.</p>\n
> 158
> 
> <br class="Apple-interchange-newline">
> ```

Thanks! in which file does this test need to be adjusted?

**Comment by LukasReschke** [comment]
Should be  the following as per Drone output:


- /drone/src/apps/settings/tests/Mailer/NewUserMailHelperTest.php:384
- /drone/src/apps/settings/tests/Mailer/NewUserMailHelperTest.php:835
- /drone/src/apps/settings/tests/Mailer/NewUserMailHelperTest.php:616

(the drone UI is a bit unintuitive with failures as the errors are only shown at top in the text)

**Comment by szaimen** [comment]
Thanks! I'll have a look.

**Comment by szaimen** [comment]
I was able to fix the NewUserMailHelperTest test :)

**Comment by LukasReschke** [comment]
Error looks indeed unrelated now :)

**Pull request merged**
