### PR TITLE
Fix controls background

### LINKED ISSUE #9993: Controls bar background missing
The controls bar in Files doesn’t have a background anymore (used to be white with 90 or 95% opacity):
screenshot from 2018-06-25 19-02-11

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #9993

@nextcloud/designers

### CODE REVIEW

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
With this the background is now completely intransparent. It was slightly transparent before.

**Comment by skjnldsv** [comment]
> With this the background is now completely intransparent. It was slightly transparent before.

You mean opaque? :D 
Yes, to be fair I'm not sure anyone saw the difference with a .5 opacity.
Opacity is incompatible with rgba sass calculation :)

**Comment by MorrisJobke** [comment]
> You mean opaque? :D

Yes. I'm also fine with an rgba background, because the buttons should stay like they are.

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
After some discussion about possibilities the current approach is fine. Maybe we can check later how to make the background slightly opaque. CSS variables do not support separate opacity for now.

**Review by MorrisJobke — APPROVED** [review]

**Comment by jancborchardt** [comment]
Hm, that's unfortunate as we basically had `rgba(255, 255, 255, .9)` before and it was nice to slightly see the file list scroll below the bar as it felt less cramped. Really no way to do thos again?

**Comment by skjnldsv** [comment]
Not with css variables though.
It was set to `0.95` I actually never noticed the transparency before looking at this issue :)

**Comment by juliushaertl** [comment]
@skjnldsv Couldn't we use something like this:

variables.scss
$color-main-background-translucent: rgba($color-main-backgorund, 0.95);

css-variables.scss
--color-main-background-translucent: $color-main-background-translucent;

The only downside would then be, that the accessibility app could not set the opacity there.

**Comment by skjnldsv** [comment]
Yes we could, but we need to be careful not to use 100000 variables ^^

**Comment by juliushaertl** [comment]
Actually I don't think it is worth here, since I also kind of never recognized the opacity. :wink:

**Comment by jancborchardt** [comment]
@juliushaertl @skjnldsv well, it was intended there. ;) Just like there’s slight transparency in the headers on https://apple.com and https://medium.com :)

**Pull request merged**
