### PR TITLE
[stable25] Wrap long productName on login form

### PR DESCRIPTION
**Pull request by nfebe**
Backport : https://github.com/nextcloud/server/pull/39848

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by Fenn-CS** [comment]
@skjnldsv Please verify that this can be merged?

**Comment by skjnldsv** [comment]
@Fenn-CS you need to rebase and compile :)

**Comment by blizzz** [comment]
I merge this, but we really do not need to backport every small fix.

**Comment by Fenn-CS** [comment]
Thanks @blizzz ... The customer who ran into this is on stable25.... Hence he need.

**Pull request merged**
