### PR TITLE
Fix upload of folders in Chrome

### PR DESCRIPTION
**Pull request by MorrisJobke**
* this fixes the problem with the uploads of folders in Chrome, that you noticed
* thanks for @georgehrke for helping to fix this
* @karlitschek I will backport this to stable11 as well

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I tested this and it fixes the issue.

**Comment by MorrisJobke** [comment]
Backport is in #4154

**Comment by MorrisJobke** [comment]
@georgehrke Could I ask you to look into fixing the unit tests for this? That would be nice. Thanks :) (feel free to take over those two PRs, because I will be not available Thursday and Friday)

**Comment by karlitschek** [comment]
great. please backport

**Comment by nickvergessen** [comment]
What does this actually fix? Because I uploaded folders just fine this week on the latest chromium and nextcloud?

**Review by nickvergessen — DISMISSED** [review]
> FAILED
	TypeError: undefined is not an object (evaluating 'this._uploads[data.uploadId].data = data') in apps/files/js/file-upload.js (line 541)
	getUpload@apps/files/js/file-upload.js:541:32
	fail@apps/files/js/file-upload.js:897:33
	_trigger@core/vendor/jquery-ui/ui/jquery-ui.custom.js:789:18
	add@apps/files/js/file-upload.js:850:18
	apps/files/tests/js/fileUploadSpec.js:72:41
	collect@core/vendor/underscore/underscore.js:172:32
	addFiles@apps/files/tests/js/fileUploadSpec.js:63:15
apps/files/tests/js/fileUploadSpec.js:103:21

**Comment by MorrisJobke** [comment]
@georgehrke @ChristophWurst @nextcloud/javascript Could one of you help with the JS unit tests? That would be nice :)

**Comment by MorrisJobke** [comment]
@LukasReschke @georgehrke @rullzer @nickvergessen Please re-review - I fixed it

**Review by rullzer — APPROVED** [review]
Fine by me... altough I could not reproduce the original issue....

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
