### PR TITLE
l10n: Replace "mail" to "email"

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Review by rakekniven — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by blizzz** [comment]
> Conflicting files
apps/settings/js/vue-settings-personal-info.js
apps/settings/js/vue-settings-personal-info.js.map

Needs a rebase

**Review by CarlSchwan — APPROVED** [review]

**Pull request merged**
