### PR TITLE
Allow clients to request an apppassword if they still use the real password

### PR DESCRIPTION
**Pull request by rullzer**
Now that we can enforce 2FA it is good if we can have client automatically switch from the real password to apppasswords.

### CODE REVIEW

**Review by ChristophWurst — DISMISSED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Review by kesselb — COMMENTED** [review]
Code looks nice.

**Comment by danielkesselberg** [comment]
1. I just created a new user test and tried to fetch a apppassword :heavy_check_mark: 
2. Disabled the new user and tried again - works as well :question:

**Comment by rullzer** [comment]
@danielkesselberg thanks for the review.

Mmmm disabled users should already be blocked before they reach this part of the code I think.
If not than that is a different bug.

Let me try.

**Comment by rullzer** [comment]
Ok I rebased and force pushed (sorry @ChristophWurst).

I had forgotten to add the NoAdminRequired annotations.

**Comment by rullzer** [comment]
@danielkesselberg for me this is correctly blocked if the user is disabled.

**Review by kesselb — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Looks good :rocket:

**Pull request merged**
