### PR TITLE
fix alignment of radio button and its label in encryption settings

### LINKED ISSUE #5611: Radiobuttons not align correctly since Nc 12
Since the merge of the personal and the admin settings the radio-buttons are now longer align correctly, see:

checkboxes

You can see this if you enable server side encryption in the admin settings, load the "default encryption module" app, re-login, go to the admin settings -> encryption -> enable the recovery key and then go to the personal settings -> security

### PR DESCRIPTION
**Pull request by blizzz**
kudos to @Henni 

fixes #5611 and should be backported to 12

### CODE REVIEW

**Comment by jancborchardt** [comment]
Just 2 details:

- [ ] the labels don't need the radio class, right?
- [ ] please use "double quotes" in HTML according to our coding guidelines

**Comment by schiessle** [comment]
looks good... Thanks @Henni and @blizzz ! 👍

**Comment by blizzz** [comment]
@jancborchardt ty, addressed your findings

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@blizzz Please do the backport

**Comment by blizzz** [comment]
Backport to 12: https://github.com/nextcloud/server/pull/5667

**Pull request merged**
