### PR TITLE
add carddav-search (vCard2Array) option for X-ADDRESSBOOKSERVER-MEMBER

### PR DESCRIPTION
**Pull request by labor4**
Hi,
First PR, sorry if I don't get all the ways just now. Bit of a training. But I'm happy to learn.

Adding said field,
which in reverse can be used to relate persons back to groups (macos behaviour), based on CardDAV only.

- groups are cards with field X-ADDRESSBOOKSERVER-KIND == 'group'
- and all members' UUID/URI in the X-ADDRESSBOOKSERVER-MEMBER "array" of that group-card.

Based on NC 15.0 from the official beta channel

Cheers
Manu

BTW:
I'm very glad the vCard2Array 'types' option was introduced upstream. Thanks a lot!

### CODE REVIEW

**Comment by danielkesselberg** [comment]
Thank you for your contribution :tada: 

I'm going to reference your issue here https://github.com/nextcloud/server/issues/9369.

According to https://www.davx5.com/manual/supported-contact-fields/
- `MEMBER` for VCard4
- `X-ADDRESSBOOKSERVER-KIND` for VCard3

Is this correct? Is `X-ADDRESSBOOKSERVER-KIND` supported by VCard4 as well?

**Comment by labor4** [comment]
I guess you are right. And I think I researched even at the same place as you. 

I dont know what's the story behind the change, but as for support: I expect a v4 tag makes the client expect v4 syntax. The right choice would be to serve the right thing but "understand" as much as possible. this vcardarray function is of the latter and doesn't define the standard inside NC AFAIK. so if there is v3/v4 cleanup needed in the code, it should be thought of globally.

**Comment by skjnldsv** [comment]
What exactly does this function?
https://github.com/nextcloud/server/blob/6bde9245ee539f1891c0636fb298f52776abf1d9/apps/dav/lib/CardDAV/AddressBookImpl.php#L262
Because if I read this comment properly, we should add faaaar more data here. There is a lot of properties than can be set twice, not only those 5/6 :/

**Comment by labor4** [comment]
> Because if I read this comment properly, we should add faaaar more data here. There is a lot of properties than can be set twice, not only those 5/6 :/

you mean: "should it reflect the whole spec, and if so, is this the way to do it"?

I cannot answer about the weight for the NC ecosystem, but I use it to parse contacts for a VOIP phone connector.

**Comment by labor4** [comment]
could there be a consensus to include just this request, or a handfull common attributes,
until it is decided whether this is a big scale question?

thanks

**Review by georgehrke — COMMENTED** [review]
Please rebase so we can see up to date CI results.

Change itself looks good 👍

**Review by skjnldsv — APPROVED** [review]
Let's move on

**Comment by labor4** [comment]
Thanks!

**Review by nickvergessen — APPROVED** [review]
:elephant:

**Pull request merged**
