### PR TITLE
Rename setting 'sendEventRemindersToSharedGroupMembers' -> 'sendEventRemindersToSharedUsers'.

### PR DESCRIPTION
**Pull request by dzatoah**
@tcitworld https://github.com/nextcloud/server/pull/31337#discussion_r831458382:

> Of course I forgot to say we should rename sendEventRemindersToSharedGroupMembers to sendEventRemindersToSharedUsers, as the share can be done with groups as well as direct users.

### CODE REVIEW

**Review by tcitworld — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by D0n1elT** [comment]
In which Nextcloud version will this feature come later?

**Comment by ChristophWurst** [comment]
24

**Comment by szaimen** [comment]
Hi @dzatoah can you please fix the conflicts so that we can merge this? Thanks in advance! :)

**Comment by dzatoah** [comment]
Thanks, @szaimen. I was confused af for a moment there...

**Comment by ChristophWurst** [comment]
@dzatoah  @szaimen what's the upgrade path? If this went into 24 it would be fine but now there is a good chance there are instances with a setting for `sendEventRemindersToSharedGroupMembers`. We have to migrate the old setting over to the new name.

**Comment by szaimen** [comment]
@dzatoah would you be up for creating the migration from the old to the new setting? :)

**Comment by dzatoah** [comment]
I'm sorry, but I have to decline.

**Comment by szaimen** [comment]
I see. 

So what then @ChristophWurst? Revert?

**Comment by dzatoah** [comment]
How would you estimate the effort? Is this doable for a Nextcloud newbie?

**Comment by ChristophWurst** [comment]
This could be done with a repair step that reads any old value and write it under the new name. Repair steps look like this: https://github.com/nextcloud/server/blob/master/lib/private/Repair/OldGroupMembershipShares.php.

**Comment by ChristophWurst** [comment]
The repair step would belong to the dav app, so maybe https://github.com/nextcloud/server/blob/master/apps/dav/lib/Migration/RemoveObjectProperties.php is better example. The step is then registered in https://github.com/nextcloud/server/blob/a1ed1db01b1e6cb798277baddfa41458631595c6/apps/dav/appinfo/info.xml#L30-L43

**Comment by szaimen** [comment]
Done in https://github.com/nextcloud/server/pull/38177

**Pull request merged**
