### PR TITLE
Keep share dropdown open while loading

### LINKED ISSUE #4208: the NCSelect should not close and keep displaying current results until it has found new results
As discussed with @jancborchardt and @nimishavijay, the NCSelect should not close and keep displaying current results until it has found new results.

See the following screenshot:
image

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Close https://github.com/nextcloud/nextcloud-vue/issues/4208

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
This seems to fix the problem in my testing. Thanks a lot for fixing this so fast Chris! :)

**Comment by artonge** [comment]
Shouldn't it be fixed on the @nc/vue side?

**Comment by Pytal** [comment]
Superseded by https://github.com/nextcloud/nextcloud-vue/pull/4209

**Pull request closed without merging**
