### PR TITLE
[stable9] Transifex Owncloud > NextCloud

### PR DESCRIPTION
**Pull request by tifredfr**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Oh, we didn’t have the prompt to help translate in version 9? I thought we had it since ages … cc @karlitschek @MorrisJobke should we backport this then anyway to get translators on board?

**Comment by jancborchardt** [comment]
@thelinuxfr by the way, probably best to squash both commits into one. :)

**Comment by MorrisJobke** [comment]
> @thelinuxfr by the way, probably best to squash both commits into one, for a cleaner history. :)

I will do so on merge for this PR

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
I'm fine with a backport.

**Comment by karlitschek** [comment]
please backport

**Comment by mar1u5** [comment]
Everybody is fine with a backport 😎 ... LGTM 👍 Merged by squashing both commits into one!

**Comment by mar1u5** [comment]
THX 💪

**Pull request merged**
