### PR TITLE
Fix undefined share object during expirationDate update

### LINKED ISSUE #43256: [Bug]: Unable to update share expiration date
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Changing share expiration date does not work immediately, unless expiration date is completely unset and then set again.

### Steps to reproduce

1. Create share with expiration date
2. Update expiration date to value allowed by configuration
3. Save
4. Verify 

### Expected behavior

Once a new date is entered and save is clicked, the new date should be applied

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
In 04e87337211351127cd02a0404936de8cb1b0837 a regression was introduced. `this` means nothing inside arrow functions, hence this.share was referring to an undefined object and so all attempted updates for expiration dates would fail.

Resolves : https://github.com/nextcloud/server/issues/43256

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]
LGTM! 🐘

**Review by Altahrim — APPROVED** [review]

**Pull request merged**
