### PR TITLE
Popovermenu files css fix

### PR DESCRIPTION
**Pull request by skjnldsv**
from 
screen shot 2017-02-14 at 22 44 28
to 
capture d ecran_2017-02-15_00-06-39

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]
Should get into 11 as well then :)

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
@skjnldsv just, event if it is such a small change, please use more descriptive commit messages in future 😎

**Comment by MorrisJobke** [comment]
@blizzz always remove the backport-request label once you opened the backport pr - this helps to see which prs still need the backport ;)

**Comment by skjnldsv** [comment]
@blizzz 😊

**Comment by blizzz** [comment]
@MorrisJobke Scusi! 😖

**Pull request merged**
