### PR TITLE
Move OCP.AppConfig, OCP.Comments and OCP.WhatsNew to the server bundle

### PR DESCRIPTION
**Pull request by ChristophWurst**
This moves three more modules to the bundle and finishes the migration of `OCP` to webpack/babel :rocket:

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:rocket:

**Review by skjnldsv — APPROVED** [review]
gif

**Comment by MorrisJobke** [comment]
@ChristophWurst Mind to rebase due to the conflicts?

**Comment by ChristophWurst** [comment]
CI failure is unrelated

**Pull request merged**
