### PR TITLE
Add Mastodon icon to personal page

### PR DESCRIPTION
**Pull request by benediktg**
I thought that it would make sense to mention the Nextcloud Mastodon account on the 'Personal' page.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Cc @jancborchardt

**Review by jancborchardt — APPROVED** [review]
Yup, seems good! :)

**Review by MariusBluem — CHANGES_REQUESTED** [review]
Discussed with @NinaNC ... account is not maintained enough ... an aspect I want to mention is, that this is "only" popular in the Open Source community and could irritate in professional use-cases 😉

**Comment by MariusBluem** [comment]
Discussed with @jancborchardt ... Closing. But thanks for your contribution @benediktg

**Comment by jancborchardt** [comment]
Yeah, good point. We also don’t have Diaspora or Instagram listed cause it’s not the main channels. :) But thanks @benediktg :)

**Pull request closed without merging**
