### PR TITLE
Listen to the right even for auto share accept

### PR DESCRIPTION
**Pull request by rullzer**
Else it just doesn't work...

Kudos to @daita for spotting

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:eyes:

**Comment by daita** [comment]
Is it possible that the event is called by the creator of the share, not the recipient. Meaning that the userId on the check of the settings is _userA_ not _userB_ ?

**Comment by rullzer** [comment]
@daita ooo you are right!

**Comment by rullzer** [comment]
@daita please recheck

**Review by ArtificialOwl — APPROVED** [review]

**Comment by daita** [comment]
looks good to me!

**Pull request merged**
