### PR TITLE
chore: bump nikic/php-parser from 4.10.5 to 4.15.2

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: /

## Summary

Update php-parser to avoid incompatibility with php-code-coverage. 
For example: https://github.com/nextcloud/contacts/pull/3164#pullrequestreview-1240131218

## TODO

- [x] Merge https://github.com/nextcloud/3rdparty/pull/1275
- [x] Rebase

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by szaimen — APPROVED** [review]
🐘

**Review by ChristophWurst — APPROVED** [review]
Nice

**Review by st3iny — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Checkers passed. You can merge 3rdparty and rebase this PR

**Pull request merged**
