### PR TITLE
l10n: Spelling unification

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Transifex.

Signed-off-by: Valdnet 47037905+Valdnet@users.noreply.github.com

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Comment by Valdnet** [comment]
@nickvergessen Can you approve and merge?

**Comment by Valdnet** [comment]
@nickvergessen There is no text string to be corrected in the `apps/user_ldap/tests/Settings/SectionTest.php` file on line 64. How to solve it?

**Comment by Valdnet** [comment]
@nickvergessen Can you merge now?

**Review by blizzz — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by blizzz** [comment]
maybe we can squash the commits? 11 are a bit over the top:)

**Comment by Valdnet** [comment]
> maybe we can squash the commits?

I am asking for squash. I cannot do it from the GitHub level.

**Comment by nickvergessen** [comment]
Done

**Pull request merged**
