### PR TITLE
improve personal settings on mobile

### PR DESCRIPTION
**Pull request by szaimen**
| Before | After |
|---|---|
| 192 168 146 128_8443_index php_settings_user(Moto G4) (1) | 192 168 146 128_8443_index php_settings_user(Moto G4) |

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=enh/noid/improve-personal-settings-mobile \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Comment by szaimen** [comment]
Seems like `Lint / php-cs check (pull_request) Failing after 1m — php-cs check` is currently broken on master...

**Review by CarlSchwan — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
