### PR TITLE
Fix color of app menu entries and background color

### LINKED ISSUE #43298: [Bug]: NC 28.0.2 - Icons in toolbar are black instead of white
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

All icons in the toolbar are black instead of white.

### Steps to reproduce

1. Upgrade von NC 28.0.1 to 28.0.2
2. Go to personal settings, Appearanc and accessibility
3. Selelect "Default background" to get the default background and color
4. Select "no background" for the background, so only the color is used as background without an image
5. See icons in the tab bar to turn black instead of staying white - also the small pill below the "active" icon is still white even with the icons in black.

### Expected behavior

Icons in the tab bar are white and not black.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

image

image

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/43298

## Summary
This fixes two issues:
1. a96a7f0c82c1ca22e78c42120e104ed46b9b08aa introduced a regression because it applied the color invert filter on the text which is already colored correctly (`primary-text`).
2. Most of the time the background color is `color-primary` but for some shipped background images the primary color does not lead to the same text color -> app menu names and the right header menu entries have wrong colors.

Especially try following: Set default background -> white text -> click "remove image" -> suddenly the app menu color is black on the same blue.

A better solution will be #42977 but for the moment this one is simpler.

before | after
---|---
Screenshot_20240203_140942|Screenshot_20240203_141051
Screenshot_20240203_141005|Screenshot_20240203_141035

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
:see_no_evil:

**Review by JuliaKirschenheuter — APPROVED** [review]

**Comment by skjnldsv** [comment]
@AndyScherzinger the failure was related, revert in https://github.com/nextcloud/server/pull/43401

**Comment by Jerome-Herbinet** [comment]
Hi @AndyScherzinger 
Not sure to understand this PR's history.
I still have the problem with Nextcloud 28.0.6. 
Is this normal ? Bad fix or revert ? ... or will it be only fixed from NC 29?
Thanks

**Comment by AndyScherzinger** [comment]
@Jerome-Herbinet according to the backport at https://github.com/nextcloud/server/pull/43392 it is shipped with 28.0.3, so if you already face issues in later versions of 28 I expect it to either be a regression or a new bug. So best to raise that in a new ticket since the source of the issue might be different.

**Pull request merged**
