### PR TITLE
Bump nextcloud/event-bus to 0.2.1

### PR DESCRIPTION
**Pull request by rullzer**
lets see if CI is happy again

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by ChristophWurst** [comment]
it's also use in axios ;)

**Review by ChristophWurst — APPROVED** [review]
Anyway :)

**Comment by skjnldsv** [comment]
> it's also use in axios ;)

I use axios btw

**Comment by rullzer** [comment]
https://drone.nextcloud.com/nextcloud/server/22376/2/1 happy ci

**Pull request merged**
