### PR TITLE
Reduce indent for `app-navigation-caption`

### PR DESCRIPTION
**Pull request by meichthys**

### CODE REVIEW

**Review by meichthys — COMMENTED** [review]
Slight improvement to the settings navigation sidebar.

Prior to change:
image

After change:
image

**Comment by jancborchardt** [comment]
I think it always looks better if the text is aligned, and in the case of these headings it gives them the necessary breathing room to highlight them more too.

But what do you think @nimishavijay @marcoambrosini?

**Comment by nimishavijay** [comment]
Agreed with @jancborchardt, we always try to make sure all text is left aligned.

**Comment by meichthys** [comment]
Every time I view the settings screen, I see the headings of Personal and Admin and think they are additional items in the list that can be clicked on. Perhaps we can increase the heading level or font size if we don't use left-alignment ?

**Comment by jancborchardt** [comment]
Alright, @meichthys then let’s get in your improvement – however, how come it is 15px? We should work with multiples of 4px which is our baseline. So you could use e.g.: `calc(var(--default-grid-baseline, 4px) * 4)` for 16px.

Regarding the increased font-size: That is only for headings, but not for simple captions like this. :) The focus should be on the content, the entries themselves.

**Comment by meichthys** [comment]
@jancborchardt  we should be good to go.
IMO, the navigation captions would look better if they were headings, but I can get behind the focus on the content instead -  the indentation will be an improvement :)

**Comment by szaimen** [comment]
@meichthys can you please rebase, run npm ci and npm run build and commit the files here? Thanks a lot!

**Comment by skjnldsv** [comment]
Closing this pull request due to lack of recent activity and updates. We appreciate your contribution and encourage you to reopen or provide further updates if necessary. :relaxed: 
Our aim is to keep the project moving forward with active collaboration. Thank you for your understanding and continued support! :pray:

**Pull request closed without merging**
