### PR TITLE
Type the \OCP\IUserManager::callForSeenUsers closure with Psalm

### PR DESCRIPTION
**Pull request by ChristophWurst**
Companion of https://github.com/nextcloud/server/pull/23743, didn't see there is two methods that take a closure.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Those double doc blocks with identical data always seem weird to me

**Comment by ChristophWurst** [comment]
> Those double doc blocks with identical data always seem weird to me

you mean the two lines for one parameter? yeah. but that is a limitation of what the original phpdoc can express and what psalm can do. one day I'm sure the phpdoc will be updated. today is not that day.

**Comment by MorrisJobke** [comment]
> you mean the two lines for one parameter? yeah. 

We can also just drop it, because it adds nothing over the type hint itself.

**Review by MorrisJobke — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> We can also just drop it, because it adds nothing over the type hint itself.

Here it doesn't. But many times we still have a short parameter description and then we shouldn't drop it because that influences how the API docs are rendered.

**Comment by rullzer** [comment]
I was more meaing the double stuff on the interface and the implementation... this always struck me as error prone to get out of sync.

**Comment by ChristophWurst** [comment]
Fair enough. It's getting better with php8 and union types but without native support for generics there is still a lot you can't express with php alone.

**Comment by ChristophWurst** [comment]
Weird that Psalm is failing now.

**Comment by kesselb** [comment]
> Weird that Psalm is failing now.

Why? Psalm warns you about the callable definition. 

https://github.com/nextcloud/server/blob/ffa8be40432d11d308a16e30fffe8e936a33b5d0/lib/private/User/Manager.php#L563-L566

Because void is defined as return type for the callable. Awesome that Psalm is also able to detect this case.

**Comment by ChristophWurst** [comment]
> Psalm warns you about the callable definition

where do you see that? I only see (unrelated?) changes of the baseline

**Comment by kesselb** [comment]
image

Here you go

**Comment by kesselb** [comment]
It seems (for nextcloud/server) that false is not returned from the callable. Don't know if an app is using this mechanism to interrupt the process.

**Review by kesselb — APPROVED** [review]

**Pull request merged**
