### PR TITLE
fix: Always create user directory when transfering files to new users

### LINKED ISSUE #35111: [Bug]: occ transfer ownership of files will fail if the new created user has never been logged in
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using the occ command to transfer files and the owndership to newly created user will fail if the newly created user has never been logged in.
Either the new user was created via "occ user:add" or via WebUI.

### Detailed CLI steps
1. List available Users
```
root@host-001: ~  $ occ-ti user:list
  - ti-user-A: Testuser A
  - ti1admin: ti1admin
```

2. Create a new user "ti-user-B"  
```
root@host-001: ~  $ occ-ti user:add --display-name "Testuser B" ti-user-B
Enter password:
Confirm password:
The user "ti-user-B" was created successfully
Display name set to "Testuser B"
```

3. Set the users quota to default
`root@host-001: ~  $ occ-ti user:setting ti-user-B files quota "default"`

4. Show user settings
```
root@host-001: ~  $ occ-ti user:setting ti-user-B
  - avatar:
    - generated: true
    - version: 1
  - files:
    - quota: default
  - settings:
    - display_name: Testuser B
```

5. List user information
```
root@host-001: ~  $ occ-ti user:info ti-user-B
  - user_id: ti-user-B
  - display_name: Testuser B
  - email:
  - cloud_id: ti-user-B@192.168.132.102/nextcloud/test-instance
  - enabled: true
  - groups:
  - quota: 25 GB
  - storage:
  - last_seen: 1970-01-01T00:00:00+00:00
  - user_directory: /mnt/NextcloudData/test-instance/ti-user-B
  - backend: Database
```

6. List available Users
```
root@host-001: ~  $ occ-ti user:list
  - ti-user-A: Testuser A
  - ti-user-B: Testuser B
  - ti1admin: ti1admin
```

7. Transfer ownership of files with moving the files to the destination user  
```
root@host-001: ~  $ occ-ti files:transfer-ownership -v --move --transfer-incoming-shares=1 ti-user-A ti-user-B
Validating quota
Target user does not have enough free space available.

In OwnershipTransferService.php line 243:

  [Exception]
  Execution terminated.


Exception trace:
  at /var/www/html/nextcloud/test-instance/apps/files/lib/Service/OwnershipTransferService.php:243
 OCA\Files\Service\OwnershipTransferService->analyse() at /var/www/html/nextcloud/test-instance/apps/files/lib/Service/OwnershipTransferService.php:159
 OCA\Files\Service\OwnershipTransferService->transfer() at /var/www/html/nextcloud/test-instance/apps/files/lib/Command/TransferOwnership.php:150
 OCA\Files\Command\TransferOwnership->execute() at /var/www/html/nextcloud/test-instance/3rdparty/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/nextcloud/test-instance/3rdparty/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/nextcloud/test-instance/3rdparty/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/html/nextcloud/test-instance/3rdparty/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/html/nextcloud/test-instance/lib/private/Console/Application.php:211
 OC\Console\Application->run() at /var/www/html/nextcloud/test-instance/console.php:100
 require_once() at /var/www/html/nextcloud/test-instance/occ:11

files:transfer-ownership [--path PATH] [--move] [--transfer-incoming-shares [TRANSFER-INCOMING-SHARES]] [--] <source-user> <destination-user>
```

8. List the users home directory
```
root@host-001: ~  $ ll /mnt/NextcloudData/test-instance/ti-user-B
total 8,0K
drwxr-xr-x 2 www-data www-data 4,0K Nov 11 18:39 ./
drwxrwx--- 8 www-data www-data 4,0K Nov 11 18:39 ../
```

9. create directory "files" at the users home and set the privilieges to www-data
```
root@host-001: ~  $ mkdir /mnt/NextcloudData/test-instance/ti-user-B/files && chown www-data:www-data /mnt/NextcloudData/test-instance/ti-user-B/files && chmod 755 /mnt/NextcloudData/test-instance/ti-user-B/files
```

10. Transfer ownership of files with moving the files to the destination user
```
root@host-001: ~  $ occ-ti files:transfer-ownership -v --move --transfer-incoming-shares=1 ti-user-A ti-user-B
Validating quota
Analysing files of ti-user-A ...
   32 [============================] < 1 sec
Collecting all share information for files and folders of ti-user-A ...
    0 [-------------->-------------] < 1 sec
Transferring files to ti-user-B/files/ ...
Restoring shares ...
    0 [>---------------------------] < 1 sec
Collecting all incoming share information for files and folders of ti-user-A ...
    0 [->--------------------------] < 1 sec
Collecting all incoming share information for files and folders of ti-user-B ...
    0 [->--------------------------] < 1 sec
Restoring incoming shares ...
    0 [>---------------------------] < 1 sec
```

11. Transfer ownership of files vice versa
```
root@host-001: ~  $ occ-ti files:transfer-ownership -v --move --transfer-incoming-shares=1 ti-user-B ti-user-A
Validating quota
Analysing files of ti-user-B ...
   32 [============================] < 1 sec
Collecting all share information for files and folders of ti-user-B ...
    0 [-------------->-------------] < 1 sec
Transferring files to ti-user-A/files/ ...
Restoring shares ...
    0 [>---------------------------] < 1 sec
Collecting all incoming share information for files and folders of ti-user-B ...
    0 [->--------------------------] < 1 sec
Collecting all incoming share information for files and folders of ti-user-A ...
    0 [->--------------------------] < 1 sec
Restoring incoming shares ...
    0 [>---------------------------] < 1 sec
```

### Summary
If a new user is created and the new user has never been logged in, the directory "files" inside the users home directory will not be created.
This leads to the missleading information of step No. 7 where it reports an issue to not have enough space available.
```
occ-ti files:transfer-ownership -v --move --transfer-incoming-shares=1 ti-user-A ti-user-B
Validating quota
Target user does not have enough free space available.
```

### Expected behavior

Whenever a new user will be created either via commandline with occ command or via the WebUI the "files" folder has to be created immediately inside the useres home directory independent from the "last_seen" status of the newly created user.

The workaround at the moment is to create first the "files" directory inside the newly created user and adapt the ownership and permission on it and then execute the occ command to transfer the ownership files.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
not necessary
```

### List of activated Apps

```shell
not necessary, because it is an fresh install from the release archive https://download.nextcloud.com/server/releases/
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
not necessary, no logs belonging to this issue
```

### Additional info

Tested with both instances v24.0.7 and v25.0.1 and observed identical behavior.
```
  - installed: true
  - version: 24.0.7.1
  - versionstring: 24.0.7
  - edition:
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
```

```
  - installed: true
  - version: 25.0.1.1
  - versionstring: 25.0.1
  - edition:
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
```

### PR DESCRIPTION
**Pull request by juliusknorr**
https://github.com/nextcloud/server/pull/30953 was originally there to fix this however with the partial file system setup in 24 we no longer setup the full file system when requesting the user root. This means that the call for getUserFolder does not create the folder but returns a LazyRootFolder instead. However since further handling of transfer ownership does not go through the Nodes API the actual RootFolder handling is never triggered. Explicitly calling for a full FS setup fixes this.

Steps to reproduce:
- Create a new user that has never logged in
- call occ files:transfer-ownership admin newuser

Fixes https://github.com/nextcloud/server/issues/35111

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Pull request merged**
