### PR TITLE
Add some whitespace around change.svg icon

### PR DESCRIPTION
**Pull request by pixelipo**
It became obvious in the NC Android app (https://github.com/nextcloud/android/pull/2217) that this icon requires some whitespace to fit with all the other ones. This PR should fix the problem.

CC @nextcloud/designers

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Ps: the standardisation tag is for the unification of html templates/css design amongst all of our apps :)

LGTM :+1:

**Comment by tobiasKaminsky** [comment]
Great, thank you for this fast fix :+1:

**Review by MorrisJobke — APPROVED** [review]
Fits a lot better into the activity app as well:

Before:
bildschirmfoto 2018-02-23 um 10 35 07

After:

bildschirmfoto 2018-02-23 um 10 35 12

**Comment by MorrisJobke** [comment]
@pixelipo Could you backport this to stable13 and stable12 please? That would be awesome 🚀

**Comment by pixelipo** [comment]
@MorrisJobke thanks for testing in the activity app - looks much better now!

Sure, I will create backport PRs today

**Pull request merged**
