### PR TITLE
[WIP] Grid view for files

### PR DESCRIPTION
**Pull request by jancborchardt**
This is a very basic start, moving Files from table to div layout. In the first step we should try to change as little as possible except the elements.

The old table layout also is present in other places:
- [ ] Container of other views (favorites, recent etc)
- [ ] File picker dialog (used in Mail for attachments, or personal settings for image)

TODO for the views:
- [ ] File actions, sharing and favorite don’t show up, probably something broken in the fileactions.js?
- [ ] In the grid view, favorite star should be left of the filename, share and fileactions on the right
- [ ] We need bigger thumbnails for the grid view (but for list view should keep the small ones for quicker loading)
- [ ] Selection view has some issues
- [ ] Header and footer do not show up
- [ ] Probably more, add your findings

From looking at it we really should focus on a minimally invasive change first, as outlined at https://github.com/nextcloud/server/issues/6 in the edited top post. cc @skjnldsv @danxuliu @juliushaertl @MorrisJobke

Current master:
screenshot from 2018-09-04 16-19-10

This branch currently (missing actions, header, stars and more)
screenshot from 2018-09-04 16-18-50

For the grid view design we can take the design of the [Bookmarks app](https://github.com/nextcloud/bookmarks) into account, where I worked with the maintainer on the design:

### CODE REVIEW

**Comment by jancborchardt** [comment]
And here’s the first quick and dirty grid view, with a toggle:

(TODOs added in the main post)
screenshot from 2018-09-04 17-11-02

**Comment by skjnldsv** [comment]
The tiles are too small imho. :)
Depends on where we want to be heading, mozaique like file browsers? Or a grid like galleries?

**Comment by sneibel** [comment]
### Please show any images without cropping.

I know using square / quadratic thumbnails gives a better looking page, but for me, as a photographer, it is really necessary to see the full image in any overview or thumbnails page. Dropbox uses sqare thumbnails and because of that, Dropbox is useless for me and I think about using Nextcloud instead. And I am sure, many users will see their images without cropping to be able to compare them easily on one page and decide which one to choose/share/download. Thank you for considering that.

**Comment by jancborchardt** [comment]
Superseded by https://github.com/nextcloud/server/pull/11573

**Pull request closed without merging**
