### PR TITLE
Add interfaces to interact with subscription from support app

### PR DESCRIPTION
**Pull request by MorrisJobke**
Build around the concept that @ChristophWurst already integrated for the sentry app.

It could be that we will backport those new interfaces down to stable14 to allow this nice integration of supported apps, etc. there as well.

The code in here is fully tested.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I'm also happy to adjust the names of the interfaces or methods.

**Review by rullzer — APPROVED** [review]
Good start. I like it

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Just that you know: I will most likely remove all unneeded methods in here again (it seems that as of now only `hasSubscription` and `getSupportedApps` is needed). Then it's easier to maintain for now and we can add more stuff later anyways.

**Comment by MorrisJobke** [comment]
> Just that you know: I will most likely remove all unneeded methods in here again (it seems that as of now only `hasSubscription` and `getSupportedApps` is needed). Then it's easier to maintain for now and we can add more stuff later anyways.

Done 👍

**Pull request merged**
