### PR TITLE
ShareByMail: Migrate to GenerateSecurePasswordEvent

### PR DESCRIPTION
**Pull request by kesselb**
Use GenerateSecurePasswordEvent for ShareByMail. 

What a trip! I thought migrating to GenerateSecurePasswordEvent would be easy :rofl:

### CODE REVIEW

**Comment by masayomitan** [comment]
oh

**Review by skjnldsv — APPROVED** [review]
Make sense!

**Comment by splitt3r** [comment]
The failing tests in `mysql8.0-php7.2` look quite related. Shouldn't they be fixed here too? Or am i wrong?

**Review by MorrisJobke — APPROVED** [review]
Code looks good, tested and works 👍

**Comment by MorrisJobke** [comment]
> The failing tests in `mysql8.0-php7.2` look quite related. Shouldn't they be fixed here too? Or am i wrong?

But then they should also fail on the other DBs 🧐 Let's rerun them.

**Comment by MorrisJobke** [comment]
Failure seems unrelated. Let me rebase and then we can merge this.

**Comment by MorrisJobke** [comment]
Was just the change to phpunit.xml which was already done in master -> merge

**Pull request merged**
