### PR TITLE
13.0.0 beta 4

### PR DESCRIPTION
**Pull request by MorrisJobke**
Diff to beta 3 (#7475):

* #7478 Fixed breadcrumbs calculation and actions flow
* #7480 Check for FreeType functions required for avatars
* #7485 Also cache invalid DiscoveryService response
* #7490 Respect sharing options when searching using MailPlugin
* #7498 Better handle avatars
* #7502 Use proper authorative-autoloader for app autoloaders
* #7504 Reduce length of md5 in scss caching
* #7505 Do not update apps if it comes from git
* #7506 Use cached app list
* #7517 Add index to share_with column in the share table
* #7523 Also check for empty content length
* #7527 Fix drag shadow not visible when dragging a file on a narrow screen
* #7531 Don't use deprecated method for requesting memcache
* #7553 Upgrade leafo/scssphp to 0.7.2
* #7554 Fix default parameter of OC_DB::executeAudited()
* #7555 Additional debug logging on smb copy/rename failures
* #7556 Handle exceptions in SMB::stat
* #7560 Use injected AppManager
* #7561 Let DI handle the background job
* #7562 Cache final result of update check
* #7566 Fix opening the menu in a share page
* #7572 Fix box shadow of header elements
* #7576 Use javascript to send the actual password reset
* #7583 Spelling: No ...., upgrades and email.
* #7590 Hide stay logged in checkbox when flow authentication is used
* #7591 Trigger events before and after a file action is executed
* #7592 Update quota on files upload
* #7597 Fix anchor change when clicking on sharing page menu
* #7605 Wait for the shared link to be set in the acceptance tests
* #7608 Fixes for TimestampFormatter
* #7624 Fix "fileActions.currentFile" not set before using it
* #7626 Fixed top position of multiselected files table
* #7644 Do not run SyncJob in cron
* #7646 Don't spam the log when we could not properly connect to the appstore
* #7648 Show max warning comment lenth again
* #7659 Get correct translations for SecurityProvider

Stuff that should go into beta 4 as well:

* [x] #7477 Date time picker position fix & design fixes
* [x] #7487 Disable password confirmation with SSO
* [x] #7526 Make possible for apps to disable the navigation bar slide gesture
* [x] #7533 Handle OC-Total-Length in new chunking
* [x] #7570 Add option to use legacy v2 auth with s3
* [x] ~~#7580 Use correct SVG icon on share view~~ merged via #7670 
* [x] #7598 Fix closing menu on second click in sharing page
* [x] #7599 Don't show recurring log msg when paged result was turned off
* [x] #7611 Don't attempt to translate login names to uids when uids are provided
* [x] #7631 Fix scss webroot and url rewrite
* [x] #7634 Fixes the delete button not appearing on certain lower resolutions
* [x] #7658 Update "External storages" to current file list layout
* [x] #7660 Also log exception for failed appstore request
* [x] #7662 throw ServerNotAvailableException when LDAP is caught shutting down
* [x] #7663 Fix file list visible behind the multiselect header
* [x] #7668 Fix popover menu not closing in user settings
* [x] #7669 Fix inverted app icons on IE11
* [x] #7670 Fix logo URL in SCSS variables
* [x] #7676 Show warning if slash is entered as filename
* [x] #7678 Use guest css on sharing authentication page
* [x] #7680 Format links in comments
* [x] #7681 Update quotas on each upload 
* [x] #7685 Make update notification open the new update view from apps management
* [x] #7686 Fixed quota update on upload and on delete
* [x] #7693 Fixed js typehint for showHtml method
* [x] #7696 Fix small issues with the app menu
* [x] #7698 Clear login token once apppassword is generated
* [x] #7699 Drop the ownCloud migration table instead of reusing it
* [x] #7702 Composer updated
* [x] #7710 Fix url rebase when changing the theming color

Moved to 13 RC1:

* ~~#7692 Don't lie about the preview mimetype~~

Moved to 14:
* ~~#7525 Add support for touch events to jQuery UI~~
* ~~#7514 Adjust avatar and its line height to comment message style~~

### CODE REVIEW

**Comment by Mr-Maniac** [comment]
Any chance that https://github.com/nextcloud/server/issues/7639 will land in beta 4? I've patched it locally, but not being able to upload anything via WebDAV (Android App or Windows Explorer) in vanilla Nextcloud is not very good, I think.

**Comment by MorrisJobke** [comment]
> Any chance that #7639 will land in beta 4? I've patched it locally, but not being able to upload anything via WebDAV (Android App or Windows Explorer) in vanilla Nextcloud is not very good, I think.

Looks like a setup problem - commented in the issue itself.

**Comment by MorrisJobke** [comment]
Just for the statistics: 66 PRs were added to beta 4 in comparison to beta 3.

**Review by nickvergessen — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
Wouhouuu! 🎉

**Pull request merged**
