### PR TITLE
Disable style override on vue-select elements

### PR DESCRIPTION
**Pull request by Pytal**
This fixes the styling of vue-select elements as we will soon use the https://github.com/sagalbot/vue-select library in place of the https://github.com/shentao/vue-multiselect library

### CODE REVIEW

**Review by artonge — APPROVED** [review]
This is only adding `:not([class^=vs__])` filter, right ?

For context, vue-select uses `vs_` prefix for its classes.

Looks good :)

**Comment by Pytal** [comment]
Rebased

**Review by PVince81 — APPROVED** [review]
:+1: assuming there is no better way

**Comment by Pytal** [comment]
Also disable style override on NcActionButton with `:not(.action-button)` due to increased specificity over scoped Vue styles when only `:not([class^="vs__"])` is added to fix https://github.com/nextcloud/nextcloud-vue/issues/3542 with next automated styling update from server in https://github.com/nextcloud/nextcloud-vue

**Comment by skjnldsv** [comment]
Unfortunately, this selector is too strong, it override the default scoping most vue apps do

image

We need to revert and find a different selector without brackets
image
image

**Pull request merged**
