### PR TITLE
[stable11] Add CSS for styling of keyboard shortcuts view

### PR DESCRIPTION
**Pull request by jancborchardt**
Manual backport of https://github.com/nextcloud/server/pull/4183

Please review @BernhardPosselt @Gomez @nextcloud/mail, needed for https://github.com/nextcloud/mail/pull/91

### CODE REVIEW

**Comment by rullzer** [comment]
Why do we backport this? This is not a bugfix but stuff for a new mail app feature... The new feature should just only be released for NC 12. :-1:

**Comment by jancborchardt** [comment]
@rullzer just like the icons we needed for the Video calls app, this is purely an addition (not a change), indented to improve backwards-compatibility. Otherwise we have to add this code to every single app before we can use it.

**Comment by rullzer** [comment]
@jancborchardt and if you remeber I was against that as well.

You just have to add it to every single app that is not min NC12. That is the way it is. We don't backport features just (essential) fixes.

**Comment by ChristophWurst** [comment]
👎 I'm also not a big fan of this kind of backport. You would have to expect everyone to be on the very latest minor version to have a working setup with the Mail app. However, people might be one version behind because they do not update immediately.

Let's add the backwards-compatibility to Mail 😉

**Comment by LukasReschke** [comment]
Closing thus.

**Comment by jancborchardt** [comment]
Ok, true. :)

**Pull request closed without merging**
