### PR TITLE
Fix overwriting parameter

### LINKED ISSUE #2641: Potential bug in SharedMount
apps/files_sharing/lib/SharedMount.php

> bildschirmfoto vom 2016-12-13 12-28-50

@rullzer

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #2641

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Please backport to 11

**Comment by rullzer** [comment]
@nickvergessen why. It was just hiding the original parameter. Which isn't nice but not breaking anything.

**Comment by nickvergessen** [comment]
Since `&$share` is passed by reference it's replacing it?

**Comment by rullzer** [comment]
aaah right :S let me fix.

**Comment by rullzer** [comment]
Stable11: #2825 
Stable10: #2826

**Pull request merged**
