### PR TITLE
26.0.0 beta 2

### PR DESCRIPTION
**Pull request by blizzz**
* #35160
* #35474
* #35557
* #36210
* #36257
* #36310
* #36331
* #36332
* #36341
* #36348
* #36363
* #36370
* #36371
* #36380
* #36389
* #36395
* #36402
* #36407
* #36420
* #36433
* #36434
* #36440
* #36444
* #36445
* #36453
* #36455
* #36458
* nextcloud/3rdparty#1292
* nextcloud/3rdparty#1294
* nextcloud/activity#1065
* nextcloud/activity#1066
* nextcloud/activity#1068
* nextcloud/files_pdfviewer#695
* nextcloud/firstrunwizard#815
* nextcloud/firstrunwizard#818
* nextcloud/firstrunwizard#821
* nextcloud/nextcloud_announcements#155
* nextcloud/nextcloud_announcements#158
* nextcloud/notifications#1429
* nextcloud/notifications#1430
* nextcloud/notifications#1432
* nextcloud/notifications#1433
* nextcloud/notifications#1434
* nextcloud/notifications#1435
* nextcloud/notifications#1437
* nextcloud/photos#1611
* nextcloud/photos#1617
* nextcloud/related_resources#178
* nextcloud/viewer#1525
* nextcloud/viewer#1532
* nextcloud/viewer#1533
* nextcloud/viewer#1534

### CODE REVIEW

**Comment by blizzz** [comment]
Pending PRs:

* [ ] #17425 @xklonx
* [ ] #23036 @chrisfritsche
* [ ] #23695 @rullzer
* [ ] #23825 @rullzer
* [ ] #23914 @rullzer
* [ ] #24579 @danxuliu
* [ ] #25023 @RafaOP
* [ ] #25109 @icewind1991
* [ ] #25192 @blizzz
* [ ] #25471 @rullzer
* [ ] #25551 @rullzer
* [ ] #26155 @blizzz
* [ ] #26318 @icewind1991
* [ ] #26320 @icewind1991
* [ ] #26408 @kevin147147
* [ ] #26540 @juliushaertl
* [ ] #26686 @schlimmchen
* [ ] #26716 @skjnldsv
* [ ] #26940 @rullzer
* [ ] #27034 @juliushaertl
* [ ] #27398 @skjnldsv
* [ ] #27531 @juliushaertl
* [ ] #27538 @icewind1991
* [ ] #27613 @Dreamsorcerer
* [ ] #27806 @p5n
* [ ] #27820 @juliushaertl
* [ ] #27961 @CarlSchwan
* [ ] #28226 @gary-kim
* [ ] #28279 @J0WI
* [ ] #28310 @juliushaertl
* [ ] #28601 @juliushaertl
* [ ] #28635 @TSI-yogeshshejwadkar
* [ ] #28636 @TSI-yogeshshejwadkar
* [ ] #28645 @TSI-kavitasonawane
* [ ] #28772 @icewind1991
* [ ] #28832 @TSI-yogeshshejwadkar
* [ ] #28834 @TSI-kavitasonawane
* [ ] #28911 @danxuliu
* [ ] #29010 @mattian
* [ ] #29143 @julien-nc
* [ ] #29430 @CarlSchwan
* [ ] #29642 @szaimen
* [ ] #29643 @szaimen
* [ ] #29729 @julien-nc
* [ ] #29861 @Zocker1999NET
* [ ] #29892 @Pytal
* [ ] #29940 @jonathanmmm
* [ ] #29988 @MichaIng
* [ ] #30147 @Phlogi
* [ ] #30183 @Pytal
* [ ] #30359 @juliushaertl
* [ ] #30472 @juliushaertl
* [ ] #30512 @come-nc
* [ ] #30654 @pavelkryl
* [ ] #30777 @AsamK
* [ ] #30796 @icewind1991
* [ ] #30895 @mdoggydog
* [ ] #30957 @rotdrop
* [ ] #30972 @icewind1991
* [ ] #30980 @kominoshja
* [ ] #30986 @rotdrop
* [ ] #31001 @takahiro-blab
* [ ] #31038 @itmanagerro
* [ ] #31160 @CarlSchwan
* [ ] #31286 @rotdrop
* [ ] #31346 @CarlSchwan
* [ ] #31396 @skjnldsv
* [ ] #31469 @nextcloud-command
* [ ] #31660 @dzatoah
* [ ] #31699 @CommanderRoot
* [ ] #31790 @tcitworld
* [ ] #31793 @CarlSchwan
* [ ] #31859 @max65482
* [ ] #31905 @icewind1991
* [ ] #31938 @szaimen
* [ ] #32006 @thomasrockhu-codecov
* [ ] #32018 @CarlSchwan
* [ ] #32019 @CarlSchwan
* [ ] #32028 @icewind1991
* [ ] #32032 @Valdnet
* [ ] #32038 @nickvergessen
* [ ] #32163 @icewind1991
* [ ] #32197 @blizzz
* [ ] #32231 @skjnldsv
* [ ] #32257 @artonge
* [ ] #32314 @icewind1991
* [ ] #32321 @tcitworld
* [ ] #32343 @skjnldsv
* [ ] #32400 @skjnldsv
* [ ] #32466 @Pytal
* [ ] #32499 @julien-nc
* [ ] #32562 @icewind1991
* [ ] #32631 @ASerbinski
* [ ] #32632 @icewind1991
* [ ] #32775 @Pytal
* [ ] #32781 @unteem
* [ ] #32787 @jcjveraa
* [ ] #32827 @ArtificialOwl
* [ ] #32877 @icewind1991
* [ ] #32912 @CarlSchwan
* [ ] #32961 @CarlSchwan
* [ ] #33061 @pboguslawski
* [ ] #33105 @nickvergessen
* [ ] #33106 @vitormattos
* [ ] #33161 @vincentdh
* [ ] #33203 @solracsf
* [ ] #33221 @tcitworld
* [ ] #33239 @juliushaertl
* [ ] #33292 @icewind1991
* [ ] #33322 @PVince81
* [ ] #33381 @luzpaz
* [ ] #33397 @cneukom
* [ ] #33434 @Jerome-Herbinet
* [ ] #33484 @danxuliu
* [ ] #33545 @karlitschek
* [ ] #33546 @JustAdamHere
* [ ] #33578 @nickvergessen
* [ ] #33579 @icewind1991
* [ ] #33581 @icewind1991
* [ ] #33582 @icewind1991
* [ ] #33597 @icewind1991
* [ ] #33722 
* [ ] #33755 @juliushaertl
* [ ] #33779 @CarlSchwan
* [ ] #33795 @pboguslawski
* [ ] #33918 @icewind1991
* [ ] #33928 @justin-sleep
* [ ] #33985 @icewind1991
* [ ] #34056 @icewind1991
* [ ] #34082 @meichthys
* [ ] #34115 @cdammanintopix
* [ ] #34132 @smesterheide
* [ ] #34141 @Adambean
* [ ] #34143 @ativarsoft
* [ ] #34146 @ativarsoft
* [ ] #34178 @PVince81
* [ ] #34266 @marcelklehr
* [ ] #34290 @Jerome-Herbinet
* [ ] #34391 @RyanAveritt
* [ ] #34419 @Dany1718
* [ ] #34425 @rubo77
* [ ] #34443 @come-nc
* [ ] #34491 @rullzer
* [ ] #34492 @rullzer
* [ ] #34553 @rullzer
* [ ] #34562 @rullzer
* [ ] #34586 @artonge
* [ ] #34605 @skjnldsv
* [ ] #34607 @icewind1991
* [ ] #34655 @icewind1991
* [ ] #34773 @artonge
* [ ] #34873 @tcitworld
* [ ] #34891 @Jerome-Herbinet
* [ ] #34918 @starypatyk
* [ ] #34956 @artonge
* [ ] #35030 @ArtificialOwl
* [ ] #35092 @Messj1
* [ ] #35121 @susnux

**Comment by blizzz** [comment]
Pending PRs:

* [ ] #17425 @xklonx
* [ ] #23036 @chrisfritsche
* [ ] #23695 @rullzer
* [ ] #23825 @rullzer
* [ ] #23914 @rullzer
* [ ] #24579 @danxuliu
* [ ] #25023 @RafaOP
* [ ] #25109 @icewind1991
* [ ] #25192 @blizzz
* [ ] #25471 @rullzer
* [ ] #25551 @rullzer
* [ ] #26155 @blizzz
* [ ] #26318 @icewind1991
* [ ] #26320 @icewind1991
* [ ] #26408 @kevin147147
* [ ] #26540 @juliushaertl
* [ ] #26686 @schlimmchen
* [ ] #26716 @skjnldsv
* [ ] #26940 @rullzer
* [ ] #27034 @juliushaertl
* [ ] #27398 @skjnldsv
* [ ] #27531 @juliushaertl
* [ ] #27538 @icewind1991
* [ ] #27613 @Dreamsorcerer
* [ ] #27806 @p5n
* [ ] #27820 @juliushaertl
* [ ] #27961 @CarlSchwan
* [ ] #28226 @gary-kim
* [ ] #28279 @J0WI
* [ ] #28310 @juliushaertl
* [ ] #28601 @juliushaertl
* [ ] #28635 @TSI-yogeshshejwadkar
* [ ] #28636 @TSI-yogeshshejwadkar
* [ ] #28645 @TSI-kavitasonawane
* [ ] #28772 @icewind1991
* [ ] #28832 @TSI-yogeshshejwadkar
* [ ] #28834 @TSI-kavitasonawane
* [ ] #28911 @danxuliu
* [ ] #29010 @mattian
* [ ] #29143 @julien-nc
* [ ] #29430 @CarlSchwan
* [ ] #29642 @szaimen
* [ ] #29643 @szaimen
* [ ] #29729 @julien-nc
* [ ] #29861 @Zocker1999NET
* [ ] #29892 @Pytal
* [ ] #29940 @jonathanmmm
* [ ] #29988 @MichaIng
* [ ] #30147 @Phlogi
* [ ] #30183 @Pytal
* [ ] #30359 @juliushaertl
* [ ] #30472 @juliushaertl
* [ ] #30512 @come-nc
* [ ] #30654 @pavelkryl
* [ ] #30777 @AsamK
* [ ] #30796 @icewind1991
* [ ] #30895 @mdoggydog
* [ ] #30957 @rotdrop
* [ ] #30972 @icewind1991
* [ ] #30980 @kominoshja
* [ ] #30986 @rotdrop
* [ ] #31001 @takahiro-blab
* [ ] #31038 @itmanagerro
* [ ] #31160 @CarlSchwan
* [ ] #31286 @rotdrop
* [ ] #31346 @CarlSchwan
* [ ] #31396 @skjnldsv
* [ ] #31469 @nextcloud-command
* [ ] #31660 @dzatoah
* [ ] #31699 @CommanderRoot
* [ ] #31790 @tcitworld
* [ ] #31793 @CarlSchwan
* [ ] #31859 @max65482
* [ ] #31905 @icewind1991
* [ ] #31938 @szaimen
* [ ] #32006 @thomasrockhu-codecov
* [ ] #32018 @CarlSchwan
* [ ] #32019 @CarlSchwan
* [ ] #32028 @icewind1991
* [ ] #32032 @Valdnet
* [ ] #32038 @nickvergessen
* [ ] #32163 @icewind1991
* [ ] #32197 @blizzz
* [ ] #32231 @skjnldsv
* [ ] #32257 @artonge
* [ ] #32314 @icewind1991
* [ ] #32321 @tcitworld
* [ ] #32343 @skjnldsv
* [ ] #32400 @skjnldsv
* [ ] #32466 @Pytal
* [ ] #32499 @julien-nc
* [ ] #32562 @icewind1991
* [ ] #32631 @ASerbinski
* [ ] #32632 @icewind1991
* [ ] #32775 @Pytal
* [ ] #32781 @unteem
* [ ] #32787 @jcjveraa
* [ ] #32827 @ArtificialOwl
* [ ] #32877 @icewind1991
* [ ] #32912 @CarlSchwan
* [ ] #32961 @CarlSchwan
* [ ] #33061 @pboguslawski
* [ ] #33105 @nickvergessen
* [ ] #33106 @vitormattos
* [ ] #33161 @vincentdh
* [ ] #33203 @solracsf
* [ ] #33221 @tcitworld
* [ ] #33239 @juliushaertl

**Comment by blizzz** [comment]
* [ ] #33292 @icewind1991
* [ ] #33322 @PVince81
* [ ] #33381 @luzpaz
* [ ] #33397 @cneukom
* [ ] #33434 @Jerome-Herbinet
* [ ] #33484 @danxuliu
* [ ] #33545 @karlitschek
* [ ] #33546 @JustAdamHere
* [ ] #33578 @nickvergessen
* [ ] #33579 @icewind1991
* [ ] #33581 @icewind1991
* [ ] #33582 @icewind1991
* [ ] #33597 @icewind1991
* [ ] #33722 
* [ ] #33755 @juliushaertl
* [ ] #33779 @CarlSchwan
* [ ] #33795 @pboguslawski
* [ ] #33918 @icewind1991
* [ ] #33928 @justin-sleep
* [ ] #33985 @icewind1991
* [ ] #34056 @icewind1991
* [ ] #34082 @meichthys
* [ ] #34115 @cdammanintopix
* [ ] #34132 @smesterheide
* [ ] #34141 @Adambean
* [ ] #34143 @ativarsoft
* [ ] #34146 @ativarsoft
* [ ] #34178 @PVince81
* [ ] #34266 @marcelklehr
* [ ] #34290 @Jerome-Herbinet
* [ ] #34391 @RyanAveritt
* [ ] #34419 @Dany1718
* [ ] #34425 @rubo77
* [ ] #34443 @come-nc
* [ ] #34491 @rullzer
* [ ] #34492 @rullzer
* [ ] #34553 @rullzer
* [ ] #34562 @rullzer
* [ ] #34586 @artonge
* [ ] #34605 @skjnldsv
* [ ] #34607 @icewind1991
* [ ] #34655 @icewind1991
* [ ] #34773 @artonge
* [ ] #34873 @tcitworld
* [ ] #34891 @Jerome-Herbinet
* [ ] #34918 @starypatyk
* [ ] #34956 @artonge
* [ ] #35030 @ArtificialOwl
* [ ] #35092 @Messj1
* [ ] #35121 @susnux
* [ ] #35129 @Glandos
* [ ] #35189 @charleypaulus
* [ ] #35263 @szaimen
* [ ] #35270 @Mazhoon
* [ ] #35324 @CarlSchwan
* [ ] #35360 @juliushaertl
* [ ] #35365 @MichaIng
* [ ] #35384 @pulsejet
* [ ] #35388 @ChristophWurst
* [ ] #35406 @nickvergessen
* [ ] #35424 @CarlSchwan
* [ ] #35432 @pulsejet
* [ ] #35451 @RonaldBarnes
* [ ] #35459 @akhil1508
* [ ] #35460 @CarlSchwan
* [ ] #35461 @jlssmt
* [ ] #35526 @ArtificialOwl
* [ ] #35539 @CarlSchwan
* [ ] #35553 @avinash-0007
* [ ] #35555 @michielbdejong
* [ ] #35561 @tcitworld
* [ ] #35567 
* [ ] #35581 @J0WI
* [ ] #35587 @J0WI
* [ ] #35599 @ChristophWurst
* [ ] #35610 @come-nc
* [ ] #35625 @Jerome-Herbinet
* [ ] #35677 @tcitworld
* [ ] #35691 @clivinghouse
* [ ] #35694 
* [ ] #35696 
* [ ] #35697 
* [ ] #35698 
* [ ] #35699 
* [ ] #35701 @alpapan
* [ ] #35716 
* [ ] #35728 @skjnldsv
* [ ] #35732 @smesterheide
* [ ] #35733 @ffried
* [ ] #35736 @CarlSchwan
* [ ] #35743 @miaulalala
* [ ] #35744 @tcitworld
* [ ] #35748 @PVince81
* [ ] #35754 @tcitworld
* [ ] #35806 
* [ ] #35823 @grusch-it
* [ ] #35867 @akhil1508
* [ ] #35872 @nickvergessen
* [ ] #35884 @obel1x
* [ ] #35898 @szaimen
* [ ] #35907 @szaimen
* [ ] #35915 @ArtificialOwl
* [ ] #35916 @yahesh
* [ ] #35932 @luxifr
* [ ] #35961 @icewind1991
* [ ] #36033 @individual-it
* [ ] #36045 @michielbdejong
* [ ] #36068 @icewind1991
* [ ] #36097 @icewind1991
* [ ] #36110 @Pytal

**Comment by blizzz** [comment]
* [ ] #36118 @ChristophWurst
* [ ] #36120 @come-nc
* [ ] #36173 @come-nc
* [ ] #36192 @ChristophWurst
* [ ] #36217 @tcitworld
* [ ] #36220 @simonspa
* [ ] #36228 @michielbdejong
* [ ] #36232 @Pytal
* [ ] #36239 @the-djmaze
* [ ] #36252 @tcitworld
* [ ] #36263 @ChristophWurst
* [ ] #36267 @nickvergessen
* [ ] #36286 @SystemKeeper
* [ ] #36287 @susnux
* [ ] #36313 @tcitworld
* [ ] #36314 @icewind1991
* [ ] #36316 @R0Wi
* [ ] #36327 @tcitworld
* [ ] #36337 @summersab
* [ ] #36343 @ChristophWurst
* [ ] #36351 @nickvergessen
* [ ] #36355 @provokateurin
* [ ] #36356 @provokateurin
* [ ] #36360 @icewind1991
* [ ] #36375 @come-nc
* [ ] #36377 @ChristophWurst
* [ ] #36383 @juliushaertl
* [ ] #36396 @susnux
* [ ] #36408 @provokateurin
* [ ] #36409 @szaimen
* [ ] #36417 @susnux
* [ ] #36428 @icewind1991
* [ ] #36443 @szaimen
* [ ] #36449 @Pytal
* [ ] #36450 @Pytal
* [ ] #36452 @juliushaertl
* [ ] #36462 @susnux
* [ ] #36465 @juliushaertl
* [ ] #36469 @ChristophWurst
* [ ] nextcloud/3rdparty#1000 
* [ ] nextcloud/3rdparty#1019 
* [ ] nextcloud/3rdparty#1114 
* [ ] nextcloud/3rdparty#922 
* [ ] nextcloud/activity#327 @tinko92
* [ ] nextcloud/activity#460 @madmas
* [ ] nextcloud/activity#504 @chrisfritsche
* [ ] nextcloud/activity#530 @tintou
* [ ] nextcloud/activity#693 @fschrempf
* [ ] nextcloud/activity#698 @icewind1991
* [ ] nextcloud/circles#226 @fgsl
* [ ] nextcloud/circles#229 @fgsl
* [ ] nextcloud/circles#338 @hoxia
* [ ] nextcloud/circles#384 @tortuetorche
* [ ] nextcloud/circles#392 @tortuetorche
* [ ] nextcloud/circles#395 @tortuetorche
* [ ] nextcloud/circles#398 @tortuetorche
* [ ] nextcloud/circles#399 @tortuetorche
* [ ] nextcloud/circles#400 @tortuetorche
* [ ] nextcloud/circles#401 @tortuetorche
* [ ] nextcloud/circles#878 @ArtificialOwl
* [ ] nextcloud/circles#891 @ArtificialOwl
* [ ] nextcloud/circles#966 @ArtificialOwl
* [ ] nextcloud/circles#971 @rexbron
* [ ] nextcloud/circles#980 @ArtificialOwl
* [ ] nextcloud/circles#992 @solracsf
* [ ] nextcloud/files_pdfviewer#202 @skjnldsv
* [ ] nextcloud/files_pdfviewer#620 @skjnldsv
* [ ] nextcloud/files_pdfviewer#654 @danxuliu
* [ ] nextcloud/files_rightclick#129 @FreesphereTom
* [ ] nextcloud/files_rightclick#135 @Cdisk2022
* [ ] nextcloud/files_rightclick#62 @dnviti
* [ ] nextcloud/firstrunwizard#816 @Pytal
* [ ] nextcloud/logreader#476 @Abijeet
* [ ] nextcloud/logreader#827 @icewind1991
* [ ] nextcloud/notifications#728 @nickvergessen
* [ ] nextcloud/password_policy#414 @CarlSchwan
* [ ] nextcloud/photos#1062 @marcelklehr
* [ ] nextcloud/photos#1310 @artonge
* [ ] nextcloud/photos#1334 @artonge
* [ ] nextcloud/photos#1335 @artonge
* [ ] nextcloud/photos#1337 @artonge
* [ ] nextcloud/photos#1417 @jkellerer
* [ ] nextcloud/photos#1419 @jkellerer
* [ ] nextcloud/photos#1450 @artonge
* [ ] nextcloud/photos#1602 @starypatyk
* [ ] nextcloud/photos#1621 @artonge
* [ ] nextcloud/photos#1622 @artonge
* [ ] nextcloud/photos#515 @Mikescops
* [ ] nextcloud/photos#607 @cnmicha
* [ ] nextcloud/recommendations#354 @blkqi
* [ ] nextcloud/recommendations#458 @sualko
* [ ] nextcloud/serverinfo#331 @overhacked
* [ ] nextcloud/viewer#1063 @ktprograms
* [ ] nextcloud/viewer#15 @skjnldsv
* [ ] nextcloud/viewer#1530 @szaimen
* [ ] nextcloud/viewer#650 @skjnldsv
* [ ] nextcloud/viewer#915 @skjnldsv

**Comment by blizzz** [comment]
* [ ] #36118 @ChristophWurst
* [ ] #36120 @come-nc
* [ ] #36173 @come-nc
* [ ] #36192 @ChristophWurst
* [ ] #36217 @tcitworld
* [ ] #36220 @simonspa
* [ ] #36228 @michielbdejong
* [ ] #36232 @Pytal
* [ ] #36239 @the-djmaze
* [ ] #36252 @tcitworld
* [ ] #36263 @ChristophWurst
* [ ] #36267 @nickvergessen
* [ ] #36286 @SystemKeeper
* [ ] #36287 @susnux
* [ ] #36313 @tcitworld
* [ ] #36314 @icewind1991
* [ ] #36316 @R0Wi
* [ ] #36327 @tcitworld
* [ ] #36337 @summersab
* [ ] #36343 @ChristophWurst
* [ ] #36351 @nickvergessen
* [ ] #36355 @provokateurin
* [ ] #36356 @provokateurin
* [ ] #36360 @icewind1991
* [ ] #36375 @come-nc
* [ ] #36377 @ChristophWurst
* [ ] #36383 @juliushaertl
* [ ] #36396 @susnux
* [ ] #36408 @provokateurin
* [ ] #36409 @szaimen
* [ ] #36417 @susnux
* [ ] #36428 @icewind1991
* [ ] #36443 @szaimen
* [ ] #36449 @Pytal
* [ ] #36450 @Pytal
* [ ] #36452 @juliushaertl
* [ ] #36462 @susnux
* [ ] #36465 @juliushaertl
* [ ] #36469 @ChristophWurst
* [ ] nextcloud/3rdparty#1000 
* [ ] nextcloud/3rdparty#1019 
* [ ] nextcloud/3rdparty#1114 
* [ ] nextcloud/3rdparty#922 
* [ ] nextcloud/activity#327 @tinko92
* [ ] nextcloud/activity#460 @madmas
* [ ] nextcloud/activity#504 @chrisfritsche
* [ ] nextcloud/activity#530 @tintou
* [ ] nextcloud/activity#693 @fschrempf
* [ ] nextcloud/activity#698 @icewind1991
* [ ] nextcloud/circles#226 @fgsl
* [ ] nextcloud/circles#229 @fgsl
* [ ] nextcloud/circles#338 @hoxia
* [ ] nextcloud/circles#384 @tortuetorche
* [ ] nextcloud/circles#392 @tortuetorche
* [ ] nextcloud/circles#395 @tortuetorche
* [ ] nextcloud/circles#398 @tortuetorche
* [ ] nextcloud/circles#399 @tortuetorche
* [ ] nextcloud/circles#400 @tortuetorche
* [ ] nextcloud/circles#401 @tortuetorche
* [ ] nextcloud/circles#878 @ArtificialOwl
* [ ] nextcloud/circles#891 @ArtificialOwl
* [ ] nextcloud/circles#966 @ArtificialOwl
* [ ] nextcloud/circles#971 @rexbron
* [ ] nextcloud/circles#980 @ArtificialOwl
* [ ] nextcloud/circles#992 @solracsf
* [ ] nextcloud/files_pdfviewer#202 @skjnldsv
* [ ] nextcloud/files_pdfviewer#620 @skjnldsv
* [ ] nextcloud/files_pdfviewer#654 @danxuliu
* [ ] nextcloud/files_rightclick#129 @FreesphereTom
* [ ] nextcloud/files_rightclick#135 @Cdisk2022
* [ ] nextcloud/files_rightclick#62 @dnviti
* [ ] nextcloud/firstrunwizard#816 @Pytal
* [ ] nextcloud/logreader#476 @Abijeet
* [ ] nextcloud/logreader#827 @icewind1991
* [ ] nextcloud/notifications#728 @nickvergessen
* [ ] nextcloud/password_policy#414 @CarlSchwan
* [ ] nextcloud/photos#1062 @marcelklehr
* [ ] nextcloud/photos#1310 @artonge
* [ ] nextcloud/photos#1334 @artonge
* [ ] nextcloud/photos#1335 @artonge
* [ ] nextcloud/photos#1337 @artonge
* [ ] nextcloud/photos#1417 @jkellerer
* [ ] nextcloud/photos#1419 @jkellerer
* [ ] nextcloud/photos#1450 @artonge
* [ ] nextcloud/photos#1602 @starypatyk
* [ ] nextcloud/photos#1621 @artonge
* [ ] nextcloud/photos#1622 @artonge
* [ ] nextcloud/photos#515 @Mikescops
* [ ] nextcloud/photos#607 @cnmicha
* [ ] nextcloud/recommendations#354 @blkqi
* [ ] nextcloud/recommendations#458 @sualko
* [ ] nextcloud/serverinfo#331 @overhacked
* [ ] nextcloud/viewer#1063 @ktprograms
* [ ] nextcloud/viewer#15 @skjnldsv
* [ ] nextcloud/viewer#1530 @szaimen
* [ ] nextcloud/viewer#650 @skjnldsv
* [ ] nextcloud/viewer#915 @skjnldsv

**Comment by blizzz** [comment]
(payload too large)

**Review by AndyScherzinger — APPROVED** [review]

**Comment by blizzz** [comment]
Mandatory PRs to merge for Beta 2:

* [ ] https://github.com/nextcloud/server/pull/30349
* [ ] https://github.com/nextcloud/server/pull/36393
* [ ] https://github.com/nextcloud/server/pull/36375

**Pull request merged**
