### PR TITLE
Move away from database xml

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Time to add this to https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html

**Review by rullzer — APPROVED** [review]

**Comment by nickvergessen** [comment]
I'm confused, installing works locally. But I can see the issue drone it having.

**Comment by nickvergessen** [comment]
F this part of our code… The sharing app has so many hacks....

**Comment by nickvergessen** [comment]
So calling the tests individually any only the sharing tests `NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite apps/files_sharing/tests/` works.
Seems like a previous test is clearing a list of registered mount providers or something somewhere and not restoring it properly.

The fun debugging begins :snake:

**Comment by MorrisJobke** [comment]
What about removing the sharing app from this PR and get the remaining stuff in. Then debug the sharing stuff in a separate PR?

**Comment by nickvergessen** [comment]
yeah well, fine by me, but it still blocks #21641 then

**Comment by nickvergessen** [comment]
Moved to #21718

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Tested and works 👍 

The failures are fixed in #21717

**Comment by nickvergessen** [comment]
Docs at https://docs.nextcloud.com//server/stable/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_21.html#last-version-with-database-xml-support-and-migration

**Comment by rullzer** [comment]
Docs are right on time 👍

**Comment by nickvergessen** [comment]
Just forgot to link them and was cleaning up my PRs witht he pending documentation label 😅

**Pull request merged**
