### PR TITLE
Prevent self-xss via invalid mysql user name on install screen

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]

**Comment by georgehrke** [comment]
@nickvergessen Backport?

**Comment by nickvergessen** [comment]
Yeah lets do that, although the impact is rather minimal on this page

**Review by rullzer — APPROVED** [review]

**Pull request merged**
