### PR TITLE
smb update notifications

### PR DESCRIPTION
**Pull request by icewind1991**
Requires https://github.com/nextcloud/server/pull/393

Usage `occ files_external:notify <mount_id> [-user=<user>] [--password=<password>]`
(user and password are only needed if the configured auth backend doesn't provide it)

It uses the configured mount to start listening to smb notifications and marks cache entries as incomplete for incoming changes.
This "mark as incomplete" will either cause the background scanner (cron) to update the cache or automatically update the cache entries when the folder is accessed.

It uses the mount<->storage mapping (from #393) to update _all_ cache entries related to the mount, this means that it works as expected in cases where a single configured mount creates a lot storage entries (such as when using per-user auth backends such as login or user entered credentials)

### CODE REVIEW

**Comment by LukasReschke** [comment]
Tests failing

**Comment by icewind1991** [comment]
Fixed tests

**Comment by LukasReschke** [comment]
👍

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
