### PR TITLE
Check proper case for user UID

### LINKED ISSUE #9532: OCS API user info returns incomplete data
### Steps to reproduce
1. Request Userinfo via OCS API https://example.com/ocs/v1.php/cloud/users/USERID

### Expected behaviour
Correct info like doku https://docs.nextcloud.com/server/13/admin_manual/configuration_user/instruction_set_for_users.html

### Actual behaviour
broken info (quota, email, groups) same for ocs/v1.php/cloud/users/USERID/groups

```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <enabled>true</enabled>
  <id>USERID</id>
  <quota/>
  <email/>
  <displayname>Username</displayname>
  <phone></phone>
  <address></address>
  <website></website>
  <twitter></twitter>
  <groups/>
  <language></language>
 </data>
</ocs>
``` 

### Server configuration

**Operating system**: 

**Web server:**  Apache 2.2.15

**Database:** MySQL 5.1.73

**PHP version:** 7.1.16

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** zip

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - piwik: 0.4.1
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.8
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_versions
  - firstrunwizard
  - survey_client
  - systemtags
  - theming
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
 {
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/var\/www\/virtual\/xxx\/skeleton",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "versions": "false",
        "loglevel": 0,
        "log_rotate_size": 52428800,
        "forcessl": true,
        "blacklisted_files": [
            ".htaccess"
        ],
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "xframe_restriction": true,
        "maintenance": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/virtual\/xxx\/html\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "theme": "xxx",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/",
        "mail_smtpmode": "php",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "htaccess.RewriteBase": "\/",
        "upgrade.disable-web": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.nextcloud.com\/v1"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** curl

**Operating system:** ubuntu 18.04

#### Web server error log
<details>
<summary>Web server error log</summary>

none
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
none
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #9532 

Testing:
`$.get('/ocs/v2.php/cloud/users/admin')` 200 
`$.get('/ocs/v2.php/cloud/users/Admin')` 404

### CODE REVIEW

**Comment by rullzer** [comment]
Nope!

This is not the way to go. A lot of things will do :boom:. (like people that use case insentivie login from the desktop or android client).

The loginname is case insensitive on our database backend.

**Comment by skjnldsv** [comment]
> The loginname is case insensitive on our database backend.

I never knew! :o 

Well, I don't see any other proper way to do it. Adding a check on every userExists function in the provisioning api seems like a terrible way to implement such verification. :/

**Comment by rullzer** [comment]
Well then the provisioningAPI will just return non sensible data if you don't case the userid correctly. Better than the alternative now ;)

**Comment by skjnldsv** [comment]
@rullzer our current backend return the uid we request, so there is no way to check if getUID === requestedUID since it will always be true.
Our cache is populated that way :/

**Review by blizzz — DISMISSED** [review]

**Comment by rullzer** [comment]
@skjnldsv k let me think if there is a solutoion. But this is not it ;)

**Comment by blizzz** [comment]
loadUser is called from `userExists` and `getDisplayName`. Both expect the current uid. Auth goes via checkpassword, which is and stays case insensitive.

**Comment by rullzer** [comment]
@blizzz mmmm that might be true... lets see.

**Comment by rullzer** [comment]
Ok we should do some extensive testing here to make sure it keeps working.

**Comment by skjnldsv** [comment]
Well, we already know that with this patch, we can create 'test0' and Test0' users.
So we need an extensive testing here as well :)

Maybe keep the non sensitive case check on the userExists check?

**Comment by blizzz** [comment]
one valid case that @rullzer described: the local backend uses it when creating users, it would still need to make sure that the user id is not taken. what createuser does not do however: asking the User Managers userExists to check against other user backends.

Suggestion:  we could phase out userExists, point towards getUser('uid') as a test for existence, and introduce a isUserIDReserved or something like that for user backends to see whether they can give away that one.

**Comment by skjnldsv** [comment]
@blizzz @rullzer don't forget about this please :D

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by MorrisJobke** [comment]
I guess we need to move this to 16 😢

**Comment by skjnldsv** [comment]
I'm guessing we can close @MorrisJobke

**Pull request closed without merging**
