### PR TITLE
Use tooltip instead of tipsy

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @rullzer @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by schiessle** [comment]
I remember, that the last time I used a tooltip I was told by @nextcloud/designers to always use tipys. So I wonder what are the rationals behind this changes?

**Comment by juliushaertl** [comment]
Tipsy is deprecated ... See https://github.com/owncloud/core/issues/13646 for details

**Comment by juliushaertl** [comment]
:+1:

**Comment by schiessle** [comment]
@juliushaertl thanks! :+1:

**Comment by MorrisJobke** [comment]
> I remember, that the last time I used a tooltip I was told by @nextcloud/designers to always use tipys. So I wonder what are the rationals behind this changes?

@schiessle Tipsy is the old library and was unmaintained. So we looked into providing a wrapper for a newer and maintained tooltip library. In the end we have chosen tooltip from the Bootstrap project. This here only moves the code finally over :)

**Comment by jancborchardt** [comment]
@schiessle to clarify: We just say »Tipsy« cause Bootstrap tooltip is basically a fork of tipsy, and the word »tooltip« already describes the normal tooltip any browser has. »Tipsy« is basically the way of saying »we want the nice, directly appearing, dark tooltip with the arrow here« :)

**Pull request merged**
