### PR TITLE
[stable26] Add bruteforce protection in OauthApiController

### PR DESCRIPTION
**Pull request by julien-nc**
Manual backport of #38773

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by solracsf** [comment]
Why not 26.0**.4** instead? 🤔

**Comment by julien-nc** [comment]
@solracsf Because I didn't pay attention and thought 26.0.4 was the one currently being released. All good now.

**Comment by julien-nc** [comment]
@solracsf Btw, the associated project does not change anything. It's just for tracking purposes. Once a PR is merged in stableX, it will be included in the next X minor release anyway.

**Review by miaulalala — APPROVED** [review]

**Comment by julien-nc** [comment]
CI failures are not related.

**Pull request merged**
