### PR TITLE
Hack to prevent warning for read-only wrapper in public links

### LINKED ISSUE #1652: Storage wrapper warnings
I see following two warnings in the logs:

```
Storage wrapper 'readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.
Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.
```

They are added in https://github.com/owncloud/core/pull/24335

They are registered in https://github.com/nextcloud/server/blob/0215b004da6af887b3e3efa28c425d41a1c76b9b/apps/files_sharing/ajax/shareinfo.php#L66 and https://github.com/nextcloud/server/blob/1fef5d3d06752f1a2a686681ae81fd13d88e535a/apps/dav/appinfo/v1/publicwebdav.php#L79

I talked with @nickvergessen about this and he proposed to change the check to 

``` php
if (self::$logWarningWhenAddingStorageWrapper && $wrapperName !== 'readonly') {
```

@icewind1991 What do do here? Is this the correct approach or should it be done somehow differently?

### PR DESCRIPTION
**Pull request by MorrisJobke**
* downstream of https://github.com/owncloud/core/pull/26520
* fixes #1652
* followup to #1722

I tested this and it works 👍 

cc @rullzer @icewind1991 @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
Please fix it in one way only, either the upstream way or our way:
https://github.com/nextcloud/server/pull/1722

**Comment by rullzer** [comment]
didn't you add a check in the register method to check for `read-only`? That can go now then right?

**Comment by MorrisJobke** [comment]
> Please fix it in one way only, either the upstream way or our way:
> #1722

I fixed it in the one hacky way to align with upstream ;)

**Comment by nickvergessen** [comment]
👍 fine by me

> Conflicting files
lib/private/Files/Filesystem.php

Will rebase

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen @rullzer Should we backport this to stable10? @enoch85 requested it

**Comment by nickvergessen** [comment]
fine by me

**Pull request merged**
