### PR TITLE
[Part2] Make thunderbird and outlook addons identifyable

### PR DESCRIPTION
**Pull request by nickvergessen**
part 2 of too early merged #8565 (if back ported it should be back ported together with that fix)

Let's wait with merging for confirmation by:
- [ ] @oparoz https://github.com/nextcloud/nextcloud-filelink/issues/49
- [x] @usselite https://github.com/nextcloud/files_automatedtagging/issues/48#issuecomment-369843835

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Nothing for 14 it seems -> moved to 15

**Comment by rullzer** [comment]
@nickvergessen so merge this for 14 is the plan right? Then the outlook plugin (and soonish maybe the filelink thunderbird thingy) can be used as well there.

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Looks good :elephant:

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer I guess we don't backport this, right?

**Comment by nickvergessen** [comment]
Fine by me

**Comment by MorrisJobke** [comment]
> Fine by me

Let's do it for 13.0.7

**Comment by MorrisJobke** [comment]
Let's not backport it.

**Pull request merged**
