### PR TITLE
Work around snap.js state mess

### LINKED ISSUE #21459: High energy impact reported by Firefox - Continously calling setInterval
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open NextCloud in Firefox in a window on one screen, on any app
2. Open about:performance in another window on another screen, so both page are visible at the same time
3. Firefox shows a medium to high energy impact for the NC page, even above a playing Youtube video
4. Open Firefox developer tools and go to the performance tab while on the NC page
5. Record a short session (10-15s is enough)
6. The record is full of call to setInterval, the stack show "easeTo/n.animatingInterval< main.js:791

### Expected behaviour
Energy impact should be low when doing nothing on the page.

### Actual behaviour
Energy impact is medium to high while doing nothing.

### Server configuration
Official Docker image: fpm-alpine (NC 19.0.0)

### Client configuration
**Browser:**
Firefox 77.0.1

**Operating system:**
Windows 10 x64

### PR DESCRIPTION
**Pull request by PVince81**
Snap.js is not robust enough to prevent multiple calls to open() or
close(), so we added more checks to prevent these happening even when an
animation is in progress.

Because if we let this through, the bug in question will lead to a
setInterval() call in the library that will hog the CPU forever as the
animation for which its waiting will never finish.

Fixes https://github.com/nextcloud/server/issues/21459

These should not hog the CPU any more:

- [x] open/closing by clicking the button multiple times
- [x] open/closing by hitting enter key on the button
- [x] dragging the hamburger
- [x] resizing the window multiple times
- double clicking the hamburger for closing :warning: => I can't fix this as the doubling is happening inside snap.js, cannot block the event reliably. Fortunately this is a rare case...

Tested with:
- [x] Firefox
- [x] Chrome
- [x] Edge

Note: when testing, add a `console.log()` inside the "animated" event to see if there is recurring unstoppable animation there... if not, then it works

### CODE REVIEW

**Comment by PVince81** [comment]
So, enough time wasted with these issues... I managed to mitigate the bug with most of the interactions except the double click, which is hopefully rare.

I separately also explored the possibility of programmatically triggering the "transitionend" event but it didn't work out because when snap.js starts a duplicate animation, it discards its reference to the former interval, so won't be able to cancel it later... so only the latest interval is cancelled and the others continue forever...

**Comment by PVince81** [comment]
(and also wanted to avoid forking a library that is unmaintained since many years, considering that the sidebar will eventually be replaced by Vue components)

**Comment by PVince81** [comment]
did some adjustments for the unit tests and checked that the fix works also in Chromium

**Comment by PVince81** [comment]
Tested in Edge and it looks ok.

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
