### PR TITLE
l10n: Fix escaping issue

### PR DESCRIPTION
**Pull request by rakekniven**
At Transifex the string is cut and only the part left of `'` is shown, `For the server to work properly, it`.

I modified this without vue knowledge. @CarlSchwan Can you check please?

Reported at Transifex.

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Comment by CarlSchwan** [comment]
It needs to be escaped with a backslash

@Pytal looks like using template string is bad for our translation tooling.

**Comment by CarlSchwan** [comment]
> It needs to be escaped with a backslash

Oh actually scrape that, i see that you changed the character used for the apostrophe so it should work

**Review by CarlSchwan — APPROVED** [review]

**Review by Valdnet — APPROVED** [review]

**Comment by Valdnet** [comment]
Please merge.

**Review by Pytal — APPROVED** [review]

**Comment by nickvergessen** [comment]
Restarted the failed job

**Pull request merged**
