### PR TITLE
Add expiration date row

### PR DESCRIPTION
**Pull request by MorrisJobke**
bildschirmfoto 2016-07-04 um 17 18 21

I also added unit tests

### CODE REVIEW

**Comment by MorrisJobke** [comment]
It's basically the same as #19513

**Comment by mar1u5** [comment]
Why is `owncloud/core` not integrating it in the PR you submittied there :confused: I like it :facepunch:

**Comment by MorrisJobke** [comment]
> Why is owncloud/core not integrating it in the PR you submittied there

Because the unit tests were added just today 😉

**Comment by mar1u5** [comment]
Shouldnt we wait here because we overwrite it via downstream anyway, or do you want to bring in this ASAP :grin:

**Comment by LukasReschke** [comment]
Yeah. This is a hell for rebasing and merging. It would be way easier to NOT submit stuff upstream if we have it in downstream.

**Comment by mar1u5** [comment]
...otherwise: or we simply close the PR in ownCloud - because @MorrisJobke "owns" it :wink:

**Comment by MorrisJobke** [comment]
> It would be way easier to NOT submit stuff upstream if we have it in downstream.

It was already there. The only thing I added (instead of somebody else) was the unit test. So it was only a matter of time that it is merged upstream.

**Comment by schiessle** [comment]
@nickvergessen do you want to review this? :wink:

**Comment by schiessle** [comment]
@nickvergessen

**Comment by schiessle** [comment]
@nickvergessen

**Comment by LukasReschke** [comment]
> or we simply close the PR in ownCloud - because @MorrisJobke "owns" it 😈

I'd say we should do it the other way. Get it merged upstream and then have it included in our downstream syncs. Let's not be evil 😉

**Comment by MorrisJobke** [comment]
@LukasReschke @mar1u5 Then please review upstream ;)

**Pull request closed without merging**
