### PR TITLE
[stable21] Use npm ci when running JS tests

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/nextcloud/server/pull/30581 with manual recompile

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by PVince81** [comment]
seems I messed up the lock file.

I've now re-run "npm i" from scratch and it looks fine, so the build should pass now.

**Comment by artonge** [comment]
Static code failing:

```
Error: Cannot find file phpvfscomposer:/home/runner/work/server/server/lib/composer/vimeo/psalm/psalm to include
```

**Comment by PVince81** [comment]
static code of psalm unrelated, probably the baseline needs to be updated

**Pull request merged**
