### PR TITLE
Move remote_shares OCS endpoint to AppFramework

### PR DESCRIPTION
**Pull request by rullzer**
CC: @LukasReschke @nickvergessen @MorrisJobke @schiessle

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by nickvergessen** [comment]
Not before the other thing is in. Otherwise status/codes break

**Comment by MorrisJobke** [comment]
> Not before the other thing is in. Otherwise status/codes break

Link?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/1275

**Comment by rullzer** [comment]
Rebases since #1275 is in and that touches OCS stuff

**Comment by MorrisJobke** [comment]
@nickvergessen Mind to review?

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
