### PR TITLE
fix(files_sharing): add missing subtitle on search for share recipients

### LINKED ISSUE #46444: [Bug]: Remote server name missing from search result in sharing tab
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Remote server name missing from search result in sharing tab when searching remote user.

### Steps to reproduce

1. Setup Federation sharing
2. Sync address books
3. Access Files app
4. Open sharing tab on a File/Folder
5. Search a user from remote server

### Expected behavior

Search result should show user display name and remote server name.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by luka-nextcloud**
* Resolves: #46444

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Pytal — CHANGES_REQUESTED** [review]
We should rename the subtitle key in `options` to subname instead of reimplementing the option slot

**Comment by luka-nextcloud** [comment]
> We should rename the subtitle key in `options` to subname instead of reimplementing the option slot

Changing subtitle to subname does not work. It is because subname is only visible on avatar size of 32 and above (https://nextcloud-vue-components.netlify.app/#/Components/NcListItems?id=nclistitemicon)

**Comment by Pytal** [comment]
> Changing subtitle to subname does not work. It is because subname is only visible on avatar size of 32 and above ([nextcloud-vue-components.netlify.app](https://nextcloud-vue-components.netlify.app/#/Components/NcListItems?id=nclistitemicon))

I see, in that case it is a bug in the lib so we should be increase it there to 32px + do the subname rename here

**Comment by luka-nextcloud** [comment]
> > Changing subtitle to subname does not work. It is because subname is only visible on avatar size of 32 and above ([nextcloud-vue-components.netlify.app](https://nextcloud-vue-components.netlify.app/#/Components/NcListItems?id=nclistitemicon))
> 
> I see, in that case it is a bug in the lib so we should be increase it there to 32px + do the subname rename here

I made a PR on the lib side. We first need to check and release it.

**Comment by luka-nextcloud** [comment]
@juliushaertl  Should we wait until the new version of the library is released?

**Review by juliusknorr — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Since this is reported broken for v28+, can this be backported then @juliushaertl @luka-nextcloud ? Can't tell since it mentioned a lib change, so slightly more complex to do eventually.

**Comment by juliushaertl** [comment]
Yes, I'd leave that to @luka-nextcloud for the case he has ;)

**Pull request merged**
