### PR TITLE
Add label to sharing search field

### PR DESCRIPTION
**Pull request by Pytal**
### Screenshot

image

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by artonge — COMMENTED** [review]
Alignment is a bit weird, no ?

I would remove the left margin

**Comment by Pytal** [comment]
> Alignment is a bit weird, no ?
> 
> I would remove the left margin

Was done similarly to the global search menu
image

Can change it though @nimishavijay @jancborchardt?

**Comment by nimishavijay** [comment]
Nice! I think we could remove the left margin as well as the bolding to make it similar to the vue component :)

image

**Comment by artonge** [comment]
A niec addition to NSelect

**Review by nimishavijay — APPROVED** [review]
🚀 Nice!

**Pull request merged**
