### PR TITLE
[stable20] Properly cleanup entries of WebAuthn on user deletion

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of #27532

### CODE REVIEW

**Comment by LukasReschke** [comment]
```
/home/runner/work/server/server/lib/private/Authentication/WebAuthn/Db/PublicKeyCredentialMapper.php:95:8:error - UndefinedInterfaceMethod: Method OCP\DB\QueryBuilder\IQueryBuilder::executeStatement does not exist
```

😢

**Review by ChristophWurst — APPROVED** [review]

**Comment by LukasReschke** [comment]
Failing tests seem unrelated. Merging as this is a backport of Morris.

**Pull request merged**
