### PR TITLE
Fix loader colours for better visibility

### LINKED ISSUE #12091: Loading dark icon not visible enough
capture d ecran_2018-10-28_09-51-45

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #12091 

| Before |
|:---------:|
|capture d ecran_2018-11-16_13-39-37|
| After |
capture d ecran_2018-11-16_13-39-06|
@nextcloud/designers

### CODE REVIEW

**Review by JanDragon — APPROVED** [review]
👍

**Comment by ChristophWurst** [comment]
> better visibility

How's this better when the contrast decreases?

**Comment by ChristophWurst** [comment]
Thought the spinner itself was made darker but it's actually the background, right? (Don't know where that css var is used)

**Comment by skjnldsv** [comment]
> Thought the spinner itself was made darker but it's actually the background, right? (Don't know where that css var is used)
It's the dark part of the spinner that got darker to increase the contrast between the light part and the dark.

**Review by juliusknorr — APPROVED** [review]
Nice. :+1:

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Pull request merged**
