### PR TITLE
Fix #3205

### LINKED ISSUE #3205: Search box: background flashes white when clicked and box has no border
The box has no border, except when out of focus. Should _always_ have a white border, as before.

And the background flashes white when clicked. The background should _always_ be the same color as the header bar color (which is the theme color).

@skjnldsv yours ;)

cc @nextcloud/designers

### PR DESCRIPTION
**Pull request by skjnldsv**
Force border of the search input

### CODE REVIEW

**Comment by jancborchardt** [comment]
@skjnldsv nice! :) The flashing white background (from »active«) is still there though.

**Comment by MorrisJobke** [comment]
> @skjnldsv nice! :) The flashing white background (from »active«) is still there though.

I fixed it 😉

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I just rebased to get in the latest header.scss changes.

**Comment by skjnldsv** [comment]
Works fine. Thanks @MorrisJobke .

**Pull request merged**
