### PR TITLE
Fix comment mentions in activities

### PR DESCRIPTION
**Pull request by nickvergessen**
### Before

activity_-_nextcloud_-_2016-10-26_17 34 51
### After

activity_-_nextcloud_-_2016-10-26_17 34 35

@blizzz @MorrisJobke @jancborchardt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@nextcloud/designers Do we really want to have avatars inside the text? I think this is really awkward - also because the icon is a lot higher than the line height and destroys the view of a text.

**Comment by nickvergessen** [comment]
Well this just copies the comments view, so I guess. 
And yes @jancborchardt said usernames shall always have avatars next to them

**Comment by LukasReschke** [comment]
> @nextcloud/designers Do we really want to have avatars inside the text? I think this is really awkward - also because the icon is a lot higher than the line height and destroys the view of a text.

I think it looks ok. Especially since you usually don't mention 40 people on a post :)

**Comment by eppfel** [comment]
I agree, that that inline avatars could be improved and I don't like dogmas like "usernames shall always have avatars", but it looks ok to me for now.

**Comment by blizzz** [comment]
@nickvergessen oops, you stepped into the same trap i did…

spectacle t10278

The first mention has id ``user_1`` and the second ``user_11``, of which only the ``user_1`` part was replaced.

**Comment by blizzz** [comment]
Aside of this, avatars in activities are ok… they are already present with shares, too. With a lot of users it can look very colorful, however in production the benefit might be bigger. Perhaps it's also an experience that we need to make in usage and adjust if necessary?

**Comment by jancborchardt** [comment]
> also because the icon is a lot higher than the line height and destroys the view of a text

That’s a problem we need to fix then (separately).

> I don't like dogmas like "usernames shall always have avatars"

Why not though? Same for filenames, they should always have the preview or filetype icon next to them. It’s not only consistent but also very easy to recall, and makes the whole interface friendlier.


Anyway – as the others said it looks good! :+1:

**Comment by MorrisJobke** [comment]
> BUG: The first mention has id user_1 and the second user_11, of which only the user_1 part was replaced.

This is still broken - beside that it works nicely :)

**Comment by nickvergessen** [comment]
Updated

**Comment by MorrisJobke** [comment]
Tested and works 👍 

I already retriggered the build

**Comment by eppfel** [comment]
> @eppfel Why not though? Same for filenames, they should always have the preview or filetype icon next to them. It’s not only consistent but also very easy to recall, and makes the whole interface friendlier.

@jancborchardt I don't have a particular case for nextcloud, I just don't like "always". I have the impressions it is easier to read through the list of github mentions, than the list of nextcloud commenters:
> bildschirmfoto 2016-10-28 um 18 44 20

And if used on github, inline avatars have the same line height as the text.

**Comment by MorrisJobke** [comment]
> And if used on github, inline avatars have the same line height as the text.

We should move that discussion out of this PR -> this is ready to be merged

**Comment by jancborchardt** [comment]
@eppfel want to open a new issue? One consideration for this context could be to show the name without placeholder when there’s no avatar. And show _only_ the avatar of everyone when there’s more than 3 people.

**Pull request merged**
