### PR TITLE
[stable22] Fix apps settings error message timeout

### PR DESCRIPTION
**Pull request by Pytal**
Backport of https://github.com/nextcloud/server/pull/31359, including refactor from https://github.com/nextcloud/server/pull/31116/files#diff-ef3ffcc0045532b590135a9a184996ea35cbf55a6366737aa4f8c87cfc45c19a

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
conflicts, moving to 2.2.7

**Comment by blizzz** [comment]
needs manual rebase it seems. moving to 22.2.8.

**Comment by artonge** [comment]
Samba tests failing, but unrelated.

**Pull request merged**
