### PR TITLE
Fix recent files

### LINKED ISSUE #10770: Recent Files sometimes don't work
If you click on recent files in the left side bar you should see your recent changed files. This works on my private instance but on cloud.nc.com I only see an empty page.

### PR DESCRIPTION
**Pull request by rullzer**
The code is not that pretty. And not that efficient. But at least now it seems to work.

Fixes #10770

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Slow but works :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works again with shared folders 👍

**Pull request merged**
