### PR TITLE
fix(files): Adjust margin at the file list bottom

### PR DESCRIPTION
**Pull request by susnux**
## Summary
IIRC this was added when the drop notice was placed on the bottom, but the notice is now always set on the top. So this just causes weird whitespace on the files list.

### Screenshots (scrolled fully down)

before | after
---|---
Screenshot 2024-08-24 at 17-11-47 Files - Nextcloud|Screenshot 2024-08-24 at 17-34-36 Files - Nextcloud
Screenshot 2024-08-24 at 17-12-38 Files - Nextcloud|Screenshot 2024-08-24 at 17-35-02 Files - Nextcloud

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by skjnldsv** [comment]
> IIRC this was added when the drop notice was placed on the bottom, but the notice is now always set on the top. So this just causes weird whitespace on the files list.

This was also more visually appealing.
It gives a feeling of completion and you know you've reached the bottom.
I don't really mind, whatever we go for here, just adding some old input I remember hearing about :)

**Review by artonge — APPROVED** [review]

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Yes, as @skjnldsv mentioned, the bottom spacing is intentional, so that:
- It is obvious you reached the end and it’s not loading anymore
- The last items and summary are nicely readable in the center of the screen and not stuck at the bottom

(Some other apps like some text editors do this similarly.)

**Comment by susnux** [comment]
> It is obvious you reached the end and it’s not loading anymore

I thought exactly the opposite, as scrolling into a blank page looks like something needs to load there :sweat_smile: 

But if this was a design decision, then maybe at least adjust the number to not be hard coded pixels but something variable like `25vh`, so it works on all screens?

**Comment by artonge** [comment]
> (Some other apps like some text editors do this similarly.)

But this is not a text editor. Cursed words incoming: "What's the competition doing?". I don't think this is expected from a file list, or any list in general, no?

**Comment by jancborchardt** [comment]
> But if this was a design decision, then maybe at least adjust the number to not be hard coded pixels but something variable like 25vh, so it works on all screens?

Sounds good @susnux! :) 

@artonge it looks better, and some times inbetween the space was also missing and it resulted in it looking off. It’s just weird when the last files and the summary is stuck to the bottom of the screen.

**Comment by susnux** [comment]
I can understand both (personally I also tend to say a list that overflows one page should only be scroll able to the bottom), but also the design decision to have the margin seems reasonable, so I will adjust the PR to be relative to screen size.

(Because whats worse is e.g. VS code where you can scroll a whole page below the last line of code :see_no_evil: )

**Review by jancborchardt — APPROVED** [review]
Thank you! :)

**Comment by susnux** [comment]
Done looks like this now:

before | after
---|---
Screen Shot 2024-08-26 at 16 29 46|Screen Shot 2024-08-26 at 16 28 53

**Pull request merged**
