### PR TITLE
Add L10N support

### LINKED ISSUE #577: Missing L10N everywhere in workflow
Ref https://github.com/nextcloud/server/pull/565#discussion_r72242105

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Depends on #582

Fix #577

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I rebased because #582 was merged.

**Comment by icewind1991** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
