### PR TITLE
fix overlapping

### LINKED ISSUE #18414: First entry is overlapped by header (again)
### Steps to reproduce
1. Checkout master
2. Have at least one favorite
3. Goto favorite section

### Expected behaviour
See the file

### Actual behaviour
image

This issue was already part of https://github.com/nextcloud/server/issues/16076 and was fixed by https://github.com/nextcloud/server/pull/16366. https://github.com/nextcloud/server/pull/17989 reverted #16366 then to fix https://github.com/nextcloud/server/issues/17891 and here we are.

cc @nextcloud/designers

### PR DESCRIPTION
**Pull request by GretaD**
fixes #18414

### CODE REVIEW

**Comment by kesselb** [comment]
LGTM :+1: 

nextcloud test_apps_files__dir=_ (3)
nextcloud test_apps_files__dir=_ (2)
nextcloud test_apps_files__dir=_ (1)
nextcloud test_apps_files__dir=_

**Review by kesselb — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by kesselb** [comment]
@skjnldsv do you want me to test it again? There is no change since I approved it :confused:  Perhaps you forgot to rebase? ;)

**Review by gary-kim — APPROVED** [review]
LGTM

**Comment by GretaD** [comment]
@skjnldsv @kesselb @gary-kim is this ready for release?

**Review by skjnldsv — APPROVED** [review]
:elephant:

**Pull request merged**
