### PR TITLE
send share notification instead of erroring on duplicate share

### PR DESCRIPTION
**Pull request by icewind1991**
when creating a share that already exists, instead of erroring, resend the notifications

Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Need to test and confirm this doesn't break Talks reposting behaviour

**Review by nickvergessen — APPROVED** [review]
Seems to work

**Review by rullzer — APPROVED** [review]
Sure

**Comment by rullzer** [comment]
Ah you need the since annotation I guess

**Comment by skjnldsv** [comment]
@icewind1991 @nickvergessen 
Now we can add the same share an unlimited amount of times.
Having the api NOT throw on conflict seems like a bad idea to me. Please fix this for 22!

**Pull request merged**
