### PR TITLE
Disable fragile tests for now

### PR DESCRIPTION
**Pull request by MorrisJobke**
Those are the ones that fail on all the branches and just hide the real errors. After merging this I will open a revert of this PR to properly analyze where this broke.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Fine by me. But will CI pass on this one? :see_no_evil:

**Comment by MorrisJobke** [comment]
> Fine by me. But will CI pass on this one? 🙈

Now there are other failing ones 😭 Let me retrigger the job.

**Comment by MorrisJobke** [comment]
https://drone.nextcloud.com/nextcloud/server/16789

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
And there is the revert: #14557

**Pull request merged**
