### PR TITLE
Fix tag label removed when share view is opened

### LINKED ISSUE #4944: Tag UI missing
### Steps to reproduce
1. Try to tag a file that has no tags yet in the UI

### Expected behaviour
Click on the Tags label and add them

### Actual behaviour
Tag label is missing

The problem is, that the `Tag` label is somehow removed from the UI. You can see it show up for a split second:
https://github.com/nextcloud/server/blob/a06398f804fa95ec8b6d9249a3c3c571fe4cb4b8/apps/systemtags/js/systemtagsinfoview.js#L151

@ChristophWurst you have some minutes to check this before the final?

### PR DESCRIPTION
**Pull request by danxuliu**
When `ShareTabiew` is rendered [it triggers a _sharesChanged_ event](https://github.com/nextcloud/server/blob/628284a34c08bbc16a4cff06245ed5aee4c96aac/apps/files_sharing/js/sharetabview.js#L76) (due to `this._dialog.model.fetch()`). When that event is handled [it modifies the `fileInfoModel`](https://github.com/nextcloud/server/blob/628284a34c08bbc16a4cff06245ed5aee4c96aac/apps/files_sharing/js/share.js#L195). `MainFileInfoView` [is rendered again when the model changes](https://github.com/nextcloud/server/blob/628284a34c08bbc16a4cff06245ed5aee4c96aac/apps/files/js/mainfileinfodetailview.js#L138), which [resets its element](https://github.com/nextcloud/server/blob/628284a34c08bbc16a4cff06245ed5aee4c96aac/apps/files/js/mainfileinfodetailview.js#L176); as [the _Tags_ label is added by `SystemTagsInfoView` when it is rendered](https://github.com/nextcloud/server/blob/628284a34c08bbc16a4cff06245ed5aee4c96aac/apps/systemtags/js/systemtagsinfoview.js#L151) and nothing triggers a new render of `SystemTagsInfoView` when `MainFileInfoView` is rendered that is why it disappears when the _Sharing_ tab is loaded.

To fix this, `MainFileInfoView` now triggers a _post-render_ event after it is rendered so the _Tags_ label can be added again.

Besides the fix itself this pull request includes acceptance tests for the issue. I have also extracted the toggle element from `SystemTagsInfoView` to its own view, as even if the toggle is very close to that view conceptually they are different views anyway.

Fixes #4944

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Works, very nice work and good job with all the tests included 👍

**Review by LukasReschke — APPROVED** [review]
Awesome work! Consider me impressed as usual 😄

**Comment by nickvergessen** [comment]
Now the question is, backport this or do the evil hack with not hiding the input at all: https://github.com/nextcloud/server/pull/4954/files

I'd vote for the proper solution to be backported, since it has tests and all?

**Comment by LukasReschke** [comment]
👍

**Comment by nickvergessen** [comment]
@danxuliu can you create a PR against stable12 as well? Thanks!

**Comment by danxuliu** [comment]
> Works, very nice work and good job with all the tests included 👍

> Awesome work! Consider me impressed as usual 😄

Consider me thankful as usual :P

@nickvergessen 
> can you create a PR against stable12 as well? Thanks!

Here you have: #5379

**Pull request merged**
