### PR TITLE
Bump @nextcloud/vue to 6.0.0-beta.4 and related

### PR DESCRIPTION
**Pull request by PVince81**
~~Update @nextcloud/vue to 6.0.0-beta.3
Update vue and vue-template-compiler to 2.7.8
Update calendar-availability-vue to 0.5.0-beta.1 to fix conflicts.~~

```
% npm install "@nextcloud/calendar-availability-vue@^0.5.0-beta.1" "@nextcloud/vue@6.0.0-beta.4" "vue-template-compiler@^2.7.8" "vue@^2.7.8"
```

- [x] BUG: create link share, unshare it, then ALL of the action menus stop working until page refresh

### CODE REVIEW

**Comment by PVince81** [comment]
## Issue: Broken action menus
### Steps to reproduce

1. Open the sharing sidebar
2. Create a share (link share or user share)
3. Click the three dots behind the share can select "Unshare" or "Add another link"
4. Click on any other actions menu (three dots anywhere on the page)

### Expected:
Menus still working.

### Actual:
Menus not opening any more, no errors in console.

### Notes:
When opening any other menu and picking an action, like rename files, it doesn't break the other menus.

The other sharing actions that change the checkbox don't cause trouble.
So there's something fishy about "Unshare" and "Add another link", maybe because they force-close the dropdown somehow ?

**Comment by PVince81** [comment]
it's likely a logic issue of sorts.
I checked the DOM and no popover appears any more on clicking, so it's not a CSS / scrolling / visibility issue

**Comment by PVince81** [comment]
the menu item closes the actions popup by setting `this.open = false`: https://github.com/nextcloud/server/blob/update-nextcloud-vue-6.0.0-beta.2/apps/files_sharing/src/mixins/SharesMixin.js#L205

if I comment it out the dropdown still closes and the bug persists, so there's something else at play

**Comment by PVince81** [comment]
even the "new" menu for creating folders doesn't open any more after that
AFAIK it's not even an actions menu

aha, and tabbing also doesn't work any more, so perhaps it's the **focus trap** that is not disabled properly ?! @vinicius73

**Comment by PVince81** [comment]
I've compared with master where we are on nextcloud-vue 5.4.0 and the problem doesn't appear, probably because we don't have the focus trap

so:
1) is the way that the sharing menus close themselves  and should we fix it here ?
or
2) there's a more general issue to handle in nextcloud-vue to cover more closing cases ?

**Comment by raimund-schluessler** [comment]
>     1. is the way that the sharing menus close themselves broken/illegal/unusual  and should we fix it here ?
>        or

I don't know enough about the server code to answer this really, but `Actions` can be closed after one clicks an action e.g. `ActionButton` by setting the `close-after-click` prop to `true`, see https://github.com/nextcloud/nextcloud-vue/blob/master/src/mixins/actionText.js#L43-L49

**Comment by PVince81** [comment]
the focus trap is supposed to deactivated when the popover's "isShown" property becomes false: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Popover/Popover.vue#L138

maybe that specific dropdown is bypassing this somehow, will need to dig into the sharing code to find out

**Comment by vinicius73** [comment]
> maybe that specific dropdown is bypassing this somehow, will need to dig into the sharing code to find out

Probably yes
I will send a PR removing focus-trap not only in afterHide, but also in before destroy

**Comment by PVince81** [comment]
- [ ] will wait for beta.3 at least for the focus trap fix

**Comment by ChristophWurst** [comment]
> will wait for beta.3 at least for the focus trap fix

Then this PR will fix https://github.com/nextcloud/server/issues/33637

**Comment by PVince81** [comment]
damn, so now we'll need to rename all component names to prefix with Nc

**Comment by PVince81** [comment]
another challenge:
- [ ] update nextcloud-vue again and add "Nc" prefix in calendar-availability-vue:

ERROR in ./node_modules/@nextcloud/calendar-availability-vue/lib/index.esm.js 1:0-75
Module not found: Error: Can't resolve '@nextcloud/vue/dist/Components/DatetimePicker' in '/srv/www/htdocs/server/node_modules/@nextcloud/calendar-availability-vue/lib'

**Comment by PVince81** [comment]
yeah, I missed a thing... https://github.com/nextcloud/calendar-availability-vue/pull/26

**Comment by PVince81** [comment]
rebasing, re-updating, recompiling, etc etc etc... stay tuned

**Comment by PVince81** [comment]
okay, pushed again. I haven't tested anything, we should retest again!

**Comment by PVince81** [comment]
rebased... again... and fixed some renaming parts that I missed

**Comment by PVince81** [comment]
- [ ] https://github.com/nextcloud/nextcloud-vue/pull/3092

**Comment by PVince81** [comment]
updated to beta4 and recompiled

**Review by CarlSchwan — APPROVED** [review]

**Comment by PVince81** [comment]
I did a quick smoke test and the share dialog works fine and no more weird focus trap blocking on unshare

**Review by ChristophWurst — APPROVED** [review]
Tested the user mgmt for https://github.com/nextcloud/server/issues/33637 and it's still there

but the rest looks super nice. currently there is quite a noticeable design gap between e.g. settings pages and user mgmt, but that will be streamlined, right?

**Comment by PVince81** [comment]
Hmmm, some acceptance tests fail.
Like "Not favorited state icon in file details in details view in Files app could not be found after 100 seconds (NoSuchElementException)", maybe the selector changed

**Comment by PVince81** [comment]
I guess we can merge this after fixing the acceptance tests, this needs more exposure despite the bugs.

**Comment by PVince81** [comment]
I fixed some XPaths, there might be more...

**Comment by PVince81** [comment]
rebased to solve the conflict

**Comment by PVince81** [comment]
@ChristophWurst I found it: it seems the password dialog is an old style oc-dialog, which is why the focus trap is not moving: https://github.com/nextcloud/server/blob/update-nextcloud-vue-6.0.0-beta.2/core/src/OC/password-confirmation.js#L90

we'd need to port that dialog to Vue then to make it work, or have a way to manually pause the focus trap

**Comment by PVince81** [comment]
I've raised https://github.com/nextcloud/server/issues/33675 for the password dialog specifically.
I think this one will also appear on other pages so we should port it to Vue anyway.
@Pytal can you take care ? (I took the liberty to assign you there, thanks!)

**Comment by PVince81** [comment]
this means that if we have other flows where two dialogs appear and the first one is a nextcloud-vue Dialog and the second one an old style dialog, it might fail as well. @juliushaertl I suggest you test the file picker in the text app as this might be exactly this kind of scenario.

**Comment by PVince81** [comment]
seems I made it worse :-(
```
 AppNavigationContext::iOpenTheSection()
      Recent section item in App Navigation could not be found after 100 seconds (NoSuchElementException)
```

**Comment by PVince81** [comment]
ok, I made the test selector more generic and it worked for the "Recent" section, let's hope it works for everything now

**Comment by PVince81** [comment]
more stuff to fix...
- [ ] create menu button
```
# FileListContext::iCreateANewFolderNamed()
      │ Create menu button in file list could not be clicked
      │ Exception message: element not interactable
      │   (Session info: chrome=90.0.4430.85)
      │   (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 5.4.0-121-generic x86_64)
      │ Trying again
```

- [ ] selectors for share permissions
```


# FilesAppSharingContext::iSetTheShareWithAsNotCreatable()
--


      Share with 
user0 menu trigger in the details view in Files app could not be found 
after 20 seconds (NoSuchElementException)
```

- [ ] section selector still buggy
```
AppNavigationContext::iOpenTheSectionOf()
      invalid selector: Unable to locate an element with the xpath expression (//html//*[@id="app-navigation" or contains(@class, 'app-navigation')])[1]//li[normalize-space() = 'Administration']/following-sibling::li/*[contains(normalize-space(), 'Basic settings'])/.. because of the following error:
      SyntaxError: Failed to execute 'evaluate' on 'Document': The string '(//html//*[@id="app-navigation" or contains(@class, 'app-navigation')])[1]//li[normalize-space() = 'Administration']/following-sibling::li/*[contains(normalize-space(), 'Basic settings'])/..' is not a valid XPath expression.
```

- [ ] and many more...

**Comment by PVince81** [comment]
more selectors fixed...

**Comment by PVince81** [comment]
more tests fixed :mountain:

**Comment by PVince81** [comment]
failing tests unrelated, the acceptance one passes for me so it must be one of the random ones...

merging

**Pull request merged**
