### PR TITLE
Enable redis cluster CI step

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by rullzer** [comment]
I guess drone and this cluster are not friends: https://drone.nextcloud.com/nextcloud/server/695/1/cache-cluster

```
Creating cluster
Invalid IP or Port (given as 172.27.0.2) - use IP:Port format
```

**Comment by MorrisJobke** [comment]
> I guess drone and this cluster are not friends:

Good find - I always just read the last lines. Let me check the container that we use.

**Comment by MorrisJobke** [comment]
> Invalid IP or Port (given as 172.27.0.2) - use IP:Port format

This is caused by that line: https://github.com/Grokzen/docker-redis-cluster/blob/master/docker-data/docker-entrypoint.sh#L25

https://github.com/antirez/redis/blob/3.2/src/redis-trib.rb#L61

Weird thing is: why is the port not appended?

**Comment by MorrisJobke** [comment]
This is now fixed and currently uses the patched image for redis-cluster.

**Comment by MorrisJobke** [comment]
> This is now fixed and currently uses the patched image for redis-cluster.

The patch is also proposed to upstream: https://github.com/Grokzen/docker-redis-cluster/pull/28

**Comment by MorrisJobke** [comment]
redis-cluster runs again: merge

**Comment by MorrisJobke** [comment]
stable12 d9301a5b07

**Pull request merged**
