### PR TITLE
[stable26] Store encrypted OAuth2 client secrets

### PR DESCRIPTION
**Pull request by julien-nc**
Manual backport of https://github.com/nextcloud/server/pull/38398 and https://github.com/nextcloud/server/pull/38701

I kept the original migration version so it does not reflect the actual app version.

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/server/pull/38398#issuecomment-1587263501

**Review by ChristophWurst — APPROVED** [review]

**Comment by blizzz** [comment]
What about Cypress failing?

**Comment by blizzz** [comment]
moving to 26.0.4

**Comment by julien-nc** [comment]
@blizzz Failing Cypress tests are related with files_versions and theming.

Failing jsunit seems unrelated too:
image

**Pull request merged**
