### PR TITLE
Bump sabre dav to 4.4.0 in stable24

### PR DESCRIPTION
**Pull request by come-nc**
Fixes encoding problems on PHP 8.1

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
note: seems there are laravel updates as well ? make sure these are/were safe

**Comment by come-nc** [comment]
I do not understand the current state of 3rdparty submodule on stable24, it does not match stable24 branch of 3rdparty I think, it contains laravel/serializable-closure which was only added in master to my knowledge.

**Comment by PVince81** [comment]
@come-nc maybe someone submit a PR to 3rdparty/stable24 and forgot to update the pointer on stable24 ?

you might be able to trace it back

**Comment by come-nc** [comment]
I think it is from https://github.com/nextcloud/server/pull/33009

**Review by CarlSchwan — APPROVED** [review]
the unrelated change are due to the fact that the stable24 3rdparty submodule is not pointing to the correct commit. This commit also fix it

**Pull request merged**
