### PR TITLE
init Session/privateKeys on Master Key

### PR DESCRIPTION
**Pull request by ArtificialOwl**
I can't find another way to init the session ...

### CODE REVIEW

**Comment by schiessle** [comment]
Normally we call init() during login, with your approach you decrypt the private key and write it to the session every time you read a file. This is not a good idea performance wise.

**Comment by daita** [comment]
I know that this is not a real solution, and it might need some optimisation but with Nextant I am in a situation where I need to decrypt any file using the master key while running a background process (or from command line). And from what I saw, SystemPrivateKey is not initiated when I try to open a file this way.

**Comment by schiessle** [comment]
yes, but unfortunately I fear that this will kill performance for any other use case.
Give me a minute, then I will add a hook you can call to setup encryption only once.

**Comment by schiessle** [comment]
@daita can you test my changes? This should do the same but avoid that we initialize the keys on every file operation again.

**Comment by daita** [comment]
Perfect !

I haven't check the tests file, but after patching _Crypto/Encryption.php_ and _Session.php_ I was able to decrypt any file from my background process <3

**Comment by schiessle** [comment]
@daita great.... Second reviewer... @MorrisJobke or @LukasReschke ? Thanks!

**Review by LukasReschke — APPROVED** [review]

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
