### PR TITLE
Ignore AppData in encryption wrapper

### PR DESCRIPTION
**Pull request by rullzer**
Fixes part of #2407

CC: @schiessle

### CODE REVIEW

**Comment by nickvergessen** [comment]
appdata_* is not encrypted without this aswell? So what is this doing exactly?

**Comment by rullzer** [comment]
AppData is not encrypted without it.

So what happens is that on file deletion we also delete the previews. Then the trashbin logic kicks in which talks to the encryption wrapper. This encryption wrapper then wants to delete all the keys for it. But it can't find keys for the appdata stuff. Which throws an exception.

This exception is catched. But by doing so we do delete the previews from disk but not from the DB. Which means that when we request previews for files in the trashbin it will think the previews are still there. Which they are obviously not so it errors out when reading the file.

**Comment by nickvergessen** [comment]
Ah okay, works 👍

**Review by LukasReschke — APPROVED** [review]

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
