### PR TITLE
[stable18] Allow to await the sidebar

### PR DESCRIPTION
**Pull request by skjnldsv**
bacport of #18929

### CODE REVIEW

**Comment by skjnldsv** [comment]
Bump

**Comment by skjnldsv** [comment]
So, yes, no? :p

**Review by juliusknorr — APPROVED** [review]

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/18929#issuecomment-577175671 :man_shrugging:

**Comment by juliushaertl** [comment]
I'd say it is not really an api change since it basically adds returning a promise, so any previous implementation will continue to work.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
