### PR TITLE
Port global search menu to focus trapped NcHeaderMenu

### PR DESCRIPTION
**Pull request by Pytal**
* Part of #36202

## Summary

Tabbing after hitting the last result will loop back focus to the search input

No visual changes 🔎
image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
I added back the pull request template you accidentally removed.

> - [ ] Screenshots before/after for front-end changes

Can you add the screenshots, even if they are supposed to look the same?

**Comment by Pytal** [comment]
> I added back the pull request template you accidentally removed.
> 
> > Screenshots before/after for front-end changes
> 
> Can you add the screenshots, even if they are supposed to look the same?

Done! Also removed the link to prevent having to reopen for the backport

**Review by nickvergessen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
Great job! :rocket:

**Pull request merged**
