### PR TITLE
Files : Left panel dropdown improvement for NC 25

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Respawn of https://github.com/nextcloud/server/pull/38217 (which is now closed)

## Before : 
[before 2.webm](https://github.com/nextcloud/server/assets/33763786/823c8457-145a-423d-a9a9-39996205f607)

## After : 
[after 2.webm](https://github.com/nextcloud/server/assets/33763786/fe22628f-f9cf-4645-8e90-db76bbc458bc)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet do you have some screenshots?

Could you check the previous PR that contained the same commits #38217 ?

**Comment by szaimen** [comment]
Can you please add them to the PRs description?

**Comment by Jerome-Herbinet** [comment]
> Can you please add them to the PRs description?

Done :-)

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

btw, why is the dropdown button of shares not shown all the time?

**Comment by Jerome-Herbinet** [comment]
Can somebody test the Mail app with this PR ?
@GretaD warned me about some side-effects there (see equivalent PR for NC 26 https://github.com/nextcloud/nextcloud-vue/pull/4103).

**Comment by szaimen** [comment]
> Can somebody test the Mail app with this PR ?

Mail is using the vue components so this specific PR should not change the behaviour there...

**Comment by blizzz** [comment]
moving to 25.0.8

**Comment by blizzz** [comment]
Why is it open against stable25 in first place?

**Comment by szaimen** [comment]
> Why is it open against stable25 in first place?

Because starting with 26 the files app uses the vue component. 25 still has the old aidebar

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Very nice improvement to make it more obvious @Jerome-Herbinet!

One thing I also noted in the other PR: The triangle pointing to the right is confusing, it would be expected to have a triangle pointing down when in closed state, indicating more things open downwards. :)

When open, the arrow should still point down too. Then it would behave exactly like a standard HTML select element.

**Comment by Jerome-Herbinet** [comment]
> > Very nice improvement to make it more obvious @Jerome-Herbinet!
> > One thing I also noted in the other PR: The triangle pointing to the right is confusing, it would be expected to have a triangle pointing down when in closed state, indicating more things open downwards. :)
> > When open, the arrow should still point down too. Then it would behave exactly like a standard HTML select element.
> 
> It should be OK with the commit I just made @jancborchardt ; could you test it ? I have one question ; when I do a "npm run sass", I obtain a large amount of modified files ; is it more than necessary ? Can I commit and push all of them ? 

... and concerning the other PR, I'll do a complementary PR a little later because [#38338 ](https://github.com/nextcloud/nextcloud-vue/pull/4103) has already been merged.

**Comment by blizzz** [comment]
moving to 25.0.9

**Comment by blizzz** [comment]
moving to 25.0.10

**Comment by blizzz** [comment]
moving to 25.0.11

**Comment by susnux** [comment]
@Jerome-Herbinet 
I think you just need to sign the last commit (or squash them and ensure the resulting one is signed).
Build the assets (`npm ci && npm run build`) *(and commit)*.

Otherwise the PR seems to be fine.

**Comment by Jerome-Herbinet** [comment]
New PR https://github.com/nextcloud/server/pull/39779

**Pull request closed without merging**
