### PR TITLE
Fix mimetype detection on public uploads for the workflow engine 

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. activate the file access control app
2. create a file mime type rule that matches text/plain
2. create a share via link of a folder with allow upload and editing
3. open the share via the provided link
4. upload a file with the .txt extension

Fix https://github.com/nextcloud/files_accesscontrol/issues/55

@karlitschek should backport to 11 and 10

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport

**Comment by schiessle** [comment]
works for me also on master without this PR...

**Comment by schiessle** [comment]
but I can verify that the error message in the js console is gone with this PR.... so 👍

**Review by schiessle — APPROVED** [review]

**Comment by Schmuuu** [comment]
I tested the changes with following rules:
1. file media type -- IS -- application/x-sh
2. file media type -- IS -- application/x-httpd-php
3. file media type -- IS -- application/javascript

1. uploading of *.sh files still possible
2. uploading of *.php files still possible
3. *.js files blocked as expected

So only third rule shows expected behavior. Just wanted to share this, maybe something is still not correct or I defined the media type in my rules incorrect.

**Comment by nickvergessen** [comment]
Yeah you are using wrong mimetypes.
sh: https://github.com/nextcloud/server/blob/ade91c8fe2e9230dea62cbf47a19cd5907646864/resources/config/mimetypemapping.dist.json#L152-L152
php: https://github.com/nextcloud/server/blob/ade91c8fe2e9230dea62cbf47a19cd5907646864/resources/config/mimetypemapping.dist.json#L126

Maybe we should add some validation to the field and cross check it against the file

**Review by rullzer — APPROVED** [review]

**Pull request merged**
