### PR TITLE
Fix color-box-shadow variable

### PR DESCRIPTION
**Pull request by marcoambrosini**
The color-box-shadow variable wasn't properly transparentized

BEFORE: 
Screenshot from 2020-03-06 13-45-05

AFTER:
Screenshot from 2020-03-06 13-45-34

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Review by skjnldsv — CHANGES_REQUESTED** [review]
> The color-box-shadow variable wasn't properly transparentized

What was the original issue? Please gives more details.
Also do not remove the !default please :)

**Comment by ma12-co** [comment]
> What was the original issue? Please gives more details.

The 0.5 alpha channel wasn't working.

> Also do not remove the !default please :)

OK, fixingup

**Review by jancborchardt — APPROVED** [review]
Looking much better now! :)

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Please also fix https://github.com/nextcloud/server/blob/bcc3fbd3251a5a0b071120aab00f666e58746c40/apps/accessibility/css/dark.scss#L15

**Comment by nickvergessen** [comment]
Can you check all rgba usages?

**Comment by ma12-co** [comment]
> Can you check all rgba usages?

It's only these 2 @nickvergessen

**Comment by skjnldsv** [comment]
> Please also fix
> 
> https://github.com/nextcloud/server/blob/bcc3fbd3251a5a0b071120aab00f666e58746c40/apps/accessibility/css/dark.scss#L15

still happening

**Review by skjnldsv — CHANGES_REQUESTED** [review]
> Please also fix
> 
> https://github.com/nextcloud/server/blob/bcc3fbd3251a5a0b071120aab00f666e58746c40/apps/accessibility/css/dark.scss#L15

still happening

**Comment by ma12-co** [comment]
so sorry!

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
