### PR TITLE
Update UpdateNotification.vue

### PR DESCRIPTION
**Pull request by jospoortvliet**
I've updated the text, but the 'learn more about updates and update channels' should link to https://nextcloud.com/release-channels/ and I don't know how to do that ;-)

### CODE REVIEW

**Comment by skjnldsv** [comment]
Labels? Reviewers?

**Comment by StCyr** [comment]
Doesn't `the update only shows up after the first minor release or later.` only apply to the stable channel?

If so, this sentence shouldn't be displayed when the beta channel is selected

**Comment by jospoortvliet** [comment]
> Doesn't `the update only shows up after the first minor release or later.` only apply to the stable channel?
> 
> If so, this sentence shouldn't be displayed when the beta channel is selected

yeah, we could even note that the beta channel is a quick way to get the release. But I don't want this text to become super long and complicated. I think it is fine this way, to be honest - ppl will get it and they can click the link (to be added) and just check the website.
There I explain it all ;-)

**Comment by StCyr** [comment]
Yeah, having the link would definitively be a good thing 👍

**Comment by jospoortvliet** [comment]
> Yeah, having the link would definitively be a good thing

if you know how it works, feel free to suggest how to add the link - I just have no idea how to do this in vue!

**Comment by StCyr** [comment]
Ah! This is not a change of the `settings/admin/overview` page... :-(

**Comment by jospoortvliet** [comment]
> Ah! This is not a change of the `settings/admin/overview` page... :-(

it is not? That is certainly what I was trying to accomplish! Again, please, if you can do better, please please do. I just can't do this myself, I lack the technical knowledge but what I'm trying to do is improve the text on the admin overview page and add a link.

I mean for the text to change into this:

> Note that after a new release the update only shows up after the first minor release or later. We roll out new versions spread out over time to our users and sometimes skip a version when issues are found. Learn more about updates and release channels.

Obviously, the last sentence should link to https://nextcloud.com/release-channels/

Anyone else who can help with this?

**Comment by jospoortvliet** [comment]
@skjnldsv you can probably do this fairly quickly as I believe you know vue.js a bit... Please? It'd be really nice to have it in 21 :(

**Comment by StCyr** [comment]
> 
> 
> @skjnldsv you can probably do this fairly quickly as I believe you know vue.js a bit... Please? It'd be really nice to have it in 21 :(

I'm looking at it. I've realized I hadn't re-compile the code prior testing

**Comment by StCyr** [comment]
Is it what you want @jospoortvliet ?

image

**Comment by StCyr** [comment]
I don't understand the build failure. Is it related to our changes at all?

**Comment by jospoortvliet** [comment]
> Is it what you want @jospoortvliet ?
> 
> image

Thank you and yes, that is it, very nice!

> I don't understand the build failure. Is it related to our changes at all?

It says "this is most likely a problem with the node-sass package"...

**Comment by jospoortvliet** [comment]
@nickvergessen offered to fix it, claiming we broke translations with this ;-)

**Review by nickvergessen — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Pull request merged**
