### PR TITLE
Use file path for direct editing

### PR DESCRIPTION
**Pull request by juliusknorr**
The main issue with using the file id is that we cannot determine the correct permissions if the first file is picked. Therefore the direct editing API should always use the path for the current user.

Sorry for coming up with this so late, this was just reported by OnlyOffice implementing the API and I didn't have it on my radar since Collabora only works with file ids.

### CODE REVIEW

**Comment by rullzer** [comment]
Either that or you add backend logic to iterate over all the files you get back. To determine if we have edit permissions

**Comment by juliushaertl** [comment]
> Either that or you add backend logic to iterate over all the files you get back. To determine if we have edit permissions

This seems to be the cleaner approach to me, so we actually hand over the correct file that was selected by the user to the editor. Iterating is what collabora does but will break as soon as the app also wants to check for share permissions for example.

**Comment by juliushaertl** [comment]
Rebased and squashed again

**Review by rullzer — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Can we get this in soon? (As Julius is on vacation until Monday).
Can I assist you in any way?

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
