### PR TITLE
13.0.0 beta3

### PR DESCRIPTION
**Pull request by MorrisJobke**
Includes:

* Fix error log on PHP 7.2 #7466 <- that is the main reason for the beta 3 to not have issues with users, that test it on PHP 7.2
* The user displayNameResolver is specific to users, not the comments app #7472
* Fixed firefox guest header height #7470
* Fix filename typo #7465
* allow 'Nextcloud' in the user agent string of Android #7462
* Show tha copy share link button properly inline #7476 
* Fixes hex2bin() in LDAP #7479

### CODE REVIEW

**Review by jospoortvliet — APPROVED** [review]
go for it...

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I would block this until @blizzz had time to had a look into https://github.com/nextcloud/server/issues/7400 because we experience this as well.

**Comment by MorrisJobke** [comment]
> I would block this until @blizzz had time to had a look into #7400 because we experience this as well.

Fix for this is in: #7479

**Comment by tiiiecherle** [comment]
It would be nice to see a fix for this [#7380](https://github.com/nextcloud/server/issues/7380) included as this error is still present when using php 7.2 with the latest git nextcloud version.

According to
[https://stackoverflow.com/questions/47656426/magento-2-2-1-unable-to-save-product-error-narrowing-occurred-during-type-infe](https://stackoverflow.com/questions/47656426/magento-2-2-1-unable-to-save-product-error-narrowing-occurred-during-type-infe)

`opcache_reset();`

has to be included at the correct position.

Thanks in advance

**Comment by MorrisJobke** [comment]
> opcache_reset();

We already do this: https://github.com/nextcloud/server/blob/c603f54a1b96c71396af33652484eef3644ff421/lib/base.php#L297

That code is executed everytime the upgrade page is shown (just before you click the "Upgrade now" button.

**Comment by MorrisJobke** [comment]
Rebased to latest master.

**Comment by tiiiecherle** [comment]
> > opcache_reset();
> We already do this:
> 
> server/lib/base.php
> Line 297 in c603f54
>  				opcache_reset(); 
> That code is executed everytime the upgrade page is shown (just before you click the "Upgrade now" button.

ok, but the error from [#7380](https://github.com/nextcloud/server/issues/7380) is shown on every restart of the webserver. Would be nice to see this fixed as this is the last error in the log for me after upgrading to php 7.2 and using the latest git version of nextcloud from around 5 hours ago.

Thanks

**Comment by rullzer** [comment]
@tiiiecherle we won't put an opcache_reset(); in the index.php. That would clear all caching of the compiled php files. This would put more load on your server and slow down each and all requests.

**Comment by tiiiecherle** [comment]
> @tiiiecherle we won't put an opcache_reset(); in the index.php. That would clear all caching of the compiled php files. This would put more load on your server and slow down each and all requests.

ok, how can the error be solved? Or is it something that has to be fixed in the php packages?

**Comment by MorrisJobke** [comment]
> ok, how can the error be solved? Or is it something that has to be fixed in the php packages?

It looks like this can only be fixed by an upcoming PHP release. I just checked and the opcache_reset does not solve the issue.

**Comment by tiiiecherle** [comment]
> It looks like this can only be fixed by an upcoming PHP release. I just checked and the opcache_reset does not solve the issue.

ok, thanks. Perhaps the issue can be forwarded to their developers.

**Comment by MorrisJobke** [comment]
> ok, thanks. Perhaps the issue can be forwarded to their developers.

AFAIK it is already fixed by PHP and the next release is in January.

**Pull request merged**
