### PR TITLE
fix(files): dav owner and mime types

### LINKED ISSUE #43269: [Bug]: No more files after update to 28.0.2
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the update from 28.0.1 to 28.0.2, the group folders in the files were no longer displayed. Instead of the "New" button, there was an "Add" button. However, the button could not be clicked, so I rule out a Groupfolders problem as it generally no longer worked. After going back to 28.0.1 and a DB restore it works again and files can be uploaded again. The behavior is the same with php8.2 and php8.3.

### Steps to reproduce

1. update from 28.0.1 to 28.0.2
2. open Nextcloud Files in the browser
3. an "Add" button (up to 28.0.1 "New") is displayed
4. the button cannot be clicked and no new files or folders can be created

### Expected behavior

The group folders should be displayed and you should be able to create new folders or files using the "Add" button.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Unfortunately, I had to switch to the previous version immediately as it is a productive system.

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.hgverwaltung.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.hgverwaltung.ch",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "filelocking.ttl": 3600,
        "default_language": "de",
        "force_language": "de",
        "default_locale": "de-ch",
        "force_locale": "de-ch",
        "skeletondirectory": "",
        "knowledgebaseenabled": false,
        "updater.release.channel": "stable",
        "default_phone_region": "CH",
        "app_install_overwrite": [
            "user_sql",
            "files_trackdownloads",
            "files_antivirus",
            "user_backend_sql_raw",
            "activity"
        ],
        "data-fingerprint": "fd880a1281a2f40887e135eaa81bc8d4",
        "maintenance_window_start": "1",
        "lost_password_link": "https:\/\/hgverwaltung.ch\/#\/password-reset",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - announcementcenter: 6.7.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - external: 5.3.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_antivirus: 5.4.1
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - groupfolders: 16.0.3
  - impersonate: 1.15.0
  - login_notes: 1.4.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - notify_push: 0.6.9
  - oauth2: 1.16.3
  - previewgenerator: 5.4.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.18.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.1
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - suspicious_login: 6.0.0
  - terms_of_service: 2.3.2
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_sql: 4.7.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 27.0.1)
  - comments: 1.18.0 (installed 1.11.0)
  - contactsinteraction: 1.9.0 (installed 1.2.0)
  - dashboard: 7.8.0 (installed 7.1.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.11.0)
  - files_external: 1.20.0
  - firstrunwizard: 2.17.0 (installed 2.10.0)
  - password_policy: 1.18.0 (installed 1.11.0)
  - photos: 2.4.0 (installed 1.2.3)
  - privacy: 1.12.0 (installed 1.6.0)
  - recommendations: 2.0.0 (installed 1.0.0)
  - support: 1.11.0 (installed 1.3.0)
  - survey_client: 1.16.0 (installed 1.9.0)
  - systemtags: 1.18.0 (installed 1.11.0)
  - text: 3.9.1 (installed 3.2.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.1.1)
  - weather_status: 1.8.0 (installed 1.1.0)
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
The log files did not show an error and no entry was written because I could not click the button to create a new file.
```

### Additional info

I could run the update again in a maintenance window to analyze the error.

### PR DESCRIPTION
**Pull request by skjnldsv**
Library fix in https://github.com/nextcloud-libraries/nextcloud-files/pull/882
Partially fix https://github.com/nextcloud/server/issues/43269#issuecomment-1923675343

```
[ERROR] files: Error while fetching content 
Object { app: "files", uid: "21341", level: 0, error: Error }
app: "files"
error: Error: Invalid owner type
uid: "21341"
```

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Review by emoral435 — APPROVED** [review]
🐘

**Comment by ChildLearningClub** [comment]
Hi, I also have an account with just numbers and upgrading to 28.04 fixed Folders displaying within Nextcloud with your patch, thank you. 

I am however also experiencing a similar issue when attempting to add additional paths to Timeline view within the Memories app. The console window provides a very similar error. Is this the same issue by chance? 

Additionally, I do not have this same problem within my other account with a username that is not just numbers.

Screenshot 2024-04-03 032941

**Comment by susnux** [comment]
@ChildLearningClub best you report this on the Memories app. Here: https://github.com/pulsejet/memories/issues

Might be that they use an old library version.

**Comment by ChildLearningClub** [comment]
@susnux Thank you.

**Pull request merged**
