### PR TITLE
fix the login log entry

### LINKED ISSUE #23063: Exception: Argument 1 passed to OC\Core\Controller\LoginController::tryLogin() must be of the type string, null given
Hello,

i got this error message in Nextcloud.
I can´t reproduce it when i try to login with an unkown user.

Maybe related to the Social App, but i don´t know.

File":"/var/www/nextcloud/core/Controller/LoginController.php","Line":287},"CustomMessage":"--"},"userAgent":"Friendica 'Red Hot Poker' 2020.09-1-1369; https://social.isurf.ca","version":"19.0.3.1","id":"5f7039de46ce8"}

https://social.isurf.ca is an Friendica Site, but i have already disabled the Social App. 

### Expected behaviour
Maybe an security issue when an Error Message appears.

### Actual behaviour
Error Message from Social App?

### Server configuration

**Operating system:**
Ubuntu 19.04.3
**Web server:**
nginx version: nginx/1.14.0 (Ubuntu)
**Database:**
mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper
**PHP version:**
php 7.4.3 FPM
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 19.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated 
**Where did you install Nextcloud from:**
Nextcloud page
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - audioplayer: 2.11.2
  - bookmarks: 3.3.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - camerarawpreviews: 0.7.8
  - checksum: 0.4.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.0.5
  - duplicatefinder: 0.0.2
  - extract: 1.2.4
  - facerecognition: 0.6.3
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_automatedtagging: 1.9.0
  - files_downloadactivity: 1.8.0
  - files_fulltextsearch: 1.4.3
  - files_fulltextsearch_tesseract: 1.4.2
  - files_pdfviewer: 1.8.0
  - files_photospheres: 1.19.1
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.0.4
  - fulltextsearch: 1.4.2
  - fulltextsearch_elasticsearch: 1.5.2
  - gpxpod: 4.2.2
  - imageconverter: 1.2.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - maps: 0.1.6
  - metadata: 0.12.0
  - news: 14.2.2
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - ocdownloader: 1.7.7
  - password_policy: 1.9.1
  - phonetrack: 0.6.4
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - qownnotesapi: 20.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.4
  - richdocumentscode: 4.2.800
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - side_menu: 1.15.0
  - socialsharing_diaspora: 2.1.0
  - socialsharing_email: 2.1.0
  - socialsharing_facebook: 2.1.0
  - socialsharing_twitter: 2.1.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - talk_simple_poll: 1.1.1
  - tasks: 0.13.3
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - unsplash: 1.1.6
  - updatenotification: 1.9.0
  - video_converter: 0.1.4
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - analytics
  - audioplayer_editor
  - documentserver_community
  - drawio
  - dropit
  - encryption
  - files_antivirus
  - files_external
  - onlyoffice
  - social
  - telephoneprovider
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.larsmueller.net",
            "cloud.dasnetzundich.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "overwrite.cli.url": "https:\/\/cloud.dasnetzundich.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "versions_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "app_install_overwrite": [
            "folderplayer",
            "camerarawpreviews",
            "fulltextsearch",
            "fulltextsearch_elasticsearch",
            "files_fulltextsearch",
            "files_fulltextsearch_tesseract",
            "ocdownloader",
            "onlyoffice",
            "files_photospheres",
            "socialsharing_twitter",
            "socialsharing_facebook",
            "socialsharing_diaspora",
            "socialsharing_email",
            "issuetemplate",
            "files_frommail"
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "updater.release.channel": "stable",
        "loglevel": 2,
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"5cP9Cyt1EVFLxIyGQgmZ","level":3,"time":"2020-09-27T06:01:03+00:00","remoteAddr":"108.162.237.16","user":"--","app":"index","method":"POST","url":"/login","message":{"Exception":"Exception","Message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 170","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1012,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 170","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1012,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/core/Controller/LoginController.php","Line":287},"CustomMessage":"--"},"userAgent":"Friendica 'Red Hot Poker' 2020.09-1-1369; https://social.isurf.ca","version":"19.0.3.1","id":"5f7039de46ce8"}
```
</details>

### PR DESCRIPTION
**Pull request by szaimen**
fix https://github.com/nextcloud/server/issues/23063

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:+1:

**Comment by blizzz** [comment]
Just to be on the safe side: this does not conflict with any passwordless login things?

**Comment by kesselb** [comment]
The fix looks wrong to me. 

```json
{
   "method":"POST",
   "url":"/login",
   "message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 217",
}
```

The error is triggered by post request but the form data / inputs for username and password are missing. 
A default value for username and password will not address the actual issue. 

I believe the actual issue is something like https://github.com/nextcloud/server/pull/36286.

**Comment by szaimen** [comment]
@kesselb I rather think this is someone trying to log in without providing a username. However I don't think that this should be logged as error. So changing the level of the error would be fine by me as well but is this even possible technically?

**Comment by kesselb** [comment]
Username and Password are required fields. You cannot submit the login form without them. 

This patch is a workaround to hide another error :see_no_evil:

**Comment by szaimen** [comment]
> This patch is a workaround to hide another error 🙈

Since you seem to be sure about this I'm going to close this attempt.

**Comment by szaimen** [comment]
Too bad. I hoped to get rid of these logs that spam the logs on my test instance: 
image

**Comment by szaimen** [comment]
I mean this was fine to log as loglevel warning or info but it seems rather overkill as error...

**Comment by kesselb** [comment]
Mind to have a look at the webserver's access log? Maybe it tells us more about the origin of the request.

**Comment by szaimen** [comment]
The webservers access log is not kept on my test server so I cannot tell you anything except it seems to be always the same external ip-address (not mine) and a Windows device likely with chrome browser: `"user":"--","app":"index","method":"POST","url":"/login","message":"OC\\Core\\Controller\\LoginController::tryLogin(): Argument #1 ($user) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/core/Controller/LoginController.php' line 298","userAgent":"Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36"`

**Review by kesselb — APPROVED** [review]
:+1:

**Comment by szaimen** [comment]
Backport to stable25 here: https://github.com/nextcloud/server/pull/36672

**Pull request merged**
