### PR TITLE
chore: update `@nextcloud/files` to 3.4.1

### LINKED ISSUE #44026: [Bug]: Share views show everything as modified a few seconds ago
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Bildschirmfoto vom 2024-03-06 12-09-49

### Steps to reproduce

1. Open `/apps/files/sharingout`

### Expected behavior

Real modified dates

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
fix https://github.com/nextcloud/server/issues/44026

### CODE REVIEW

**Comment by skjnldsv** [comment]
29 update: https://github.com/nextcloud/server/pull/45601

**Review by miaulalala — APPROVED** [review]

**Review by bigcat88 — APPROVED** [review]

**Pull request merged**
