### PR TITLE
Allow to register instances of IAlternativeLogin

### LINKED ISSUE #25060: Allow to register instances of IAlternativeLogin
In social login app may be many alternative logins with no determined parameters or even names, so it is impossible to just create "class" for all providers.

### PR DESCRIPTION
**Pull request by zorn-v**
Closes https://github.com/nextcloud/server/issues/25060

### CODE REVIEW

**Comment by zorn-v** [comment]
Maybe better to add one more method to reg context like
```php
registerAlternativeLoginObject(IAlternativeLogin $obj)
``` 
?

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/server/issues/25060#issuecomment-772719715 sorry I didn#t see your ticket earlier but let's discuss this change first :)

**Comment by zorn-v** [comment]
@ChristophWurst
I apologize if I was harsh, but what "status" of alt logins ?

**Comment by zorn-v** [comment]
I found a way - use static property, so this PR will not needed.

**Pull request closed without merging**
