### PR TITLE
[stable21] Fix search results filtering

### PR DESCRIPTION
**Pull request by CarlSchwan**
Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by CarlSchwan** [comment]
TODO: change array_map + array_filter to array_filter

**Comment by CarlSchwan** [comment]
> TODO: change array_map + array_filter to array_filter

Ended up using only one foreach loop instead of 2 array_map and one array_filter.

**Comment by CarlSchwan** [comment]
Ping?

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
