### PR TITLE
Fix dark theme primary mix

### PR DESCRIPTION
**Pull request by skjnldsv**
| Before | After |
|:---------:|:------:|
|Peek 26-04-2022 08-38|Peek 26-04-2022 08-37|

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]
❤️

**Review by szaimen — DISMISSED** [review]
On the screenshot the new accent color is nearly not visible in contrast to the surroundings espwcially in dark mode. Can we add a bit more contrast there?

**Comment by skjnldsv** [comment]
> On the screenshot the new accent color is nearly not visible in contrast to the surroundings espwcially in dark mode. Can we add a bit more contrast there?

We're back on the previous values, please raise the issue to the design team :wink:

**Comment by szaimen** [comment]
> > On the screenshot the new accent color is nearly not visible in contrast to the surroundings espwcially in dark mode. Can we add a bit more contrast there?
> 
> We're back on the previous values, please raise the issue to the design team 😉

Cc @jancborchardt @nimishavijay

**Comment by skjnldsv** [comment]
> > We're back on the previous values, please raise the issue to the design team wink
> 
> Cc @jancborchardt @nimishavijay

Better as a dedicated issue please

**Review by jancborchardt — APPROVED** [review]
Looks good as fix, but yes let’s improve the contrast on dark mode as follow-up, issue at https://github.com/nextcloud/server/issues/32150

**Pull request merged**
