### PR TITLE
Replace deprecated String.prototype.substr()

### PR DESCRIPTION
**Pull request by CommanderRoot**
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

### CODE REVIEW

**Comment by CommanderRoot** [comment]
I have rebased the PR on current master and fixed the merge conflict

**Comment by skjnldsv** [comment]
far too much conflicts, feel free to run your bot again and create a new PR @CommanderRoot :)

**Pull request closed without merging**
