### PR TITLE
Disable unreliable app-files-sharing.feature:338

### PR DESCRIPTION
**Pull request by MorrisJobke**
https://github.com/nextcloud/server/issues/22305#issuecomment-709242406

cc @danxuliu sorry, but it fails quite often and it just hurts the other CI jobs.

### CODE REVIEW

**Review by danxuliu — APPROVED** [review]
> cc @danxuliu sorry, but it fails quite often and it just hurts the other CI jobs.

No problem, thanks for doing the clean up :-)

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
