### PR TITLE
Remove replace call which does not replace anything

### PR DESCRIPTION
**Pull request by stweil**
The original code replaced / by /.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Please review carefully as I assume so but don't know whether it was intended to replace / by \/.

**Comment by MorrisJobke** [comment]
@stweil What is the initial problem with this? Either link a ticket or describe what was broken and how this fixes it. Thanks :)

**Comment by stweil** [comment]
The initial problem was that code which replaces a slash by a slash does not make sense. Either it could be removed, or it needs some kind of fix. @juliushaertl might know better what was intended and where that part of the code is used.

**Comment by juliushaertl** [comment]
I cannot remember any reason why this was needed. It should be fine to totally remote the replace and just use the value from `cssFile`

**Comment by stweil** [comment]
Thanks @juliushaertl for checking. I changed the commit and updated the subject line accordingly.

**Review by MorrisJobke — APPROVED** [review]
Code change makes sense 👍

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
CI failure unrelated - this is broken on master as well 🙈

**Pull request merged**
