### PR TITLE
Fix ellipsis breadcrumb

### LINKED ISSUE #2387: Missing space around ellipsis in breadcrumb
### Steps to reproduce

1. Create a deep folder structure
2. Go to the last folder

### Expected behaviour

There should be ample space around the ellipsis 

### Actual behaviour

The angle brackets are squashing the ellipsis 

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 11 beta2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** beta channel

----------
@jancborchardt @ChristophWurst @skjnldsv

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #2387 
capture d ecran_2016-11-29_07-13-33

@oparoz @nextcloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Tested in Firefox, Safari, Chrome, IE11, Edge

**Comment by MorrisJobke** [comment]
cc @rullzer @LukasReschke @nickvergessen @juliushaertl easy one ;)

**Comment by rullzer** [comment]
LGTM

**Comment by jancborchardt** [comment]
Btw @skjnldsv what’s up with that dark blue color there … looks like a bug. ;DDDD

**Comment by skjnldsv** [comment]
@jancborchardt it's not a bug! It's a feature!!!

**Pull request merged**
