### PR TITLE
Bump scssphp/scssphp to 1.11 in master

### LINKED ISSUE #37362: [Bug]: Error: Using ${var} in strings is deprecated (fixed on v27, not on v26)
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to PHP 8.2, the error log throws following error:

PHP] Error: Using ${var} in strings is deprecated, use {$var} instead at /var/www/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php#3491
GET /apps/theming/theme/dark.css?plain=0&v=3832917f
from xxx.xxx.xxx.xxx by xxx at 2023-03-22T22:05:57+01:00

### Steps to reproduce

restart Nextcloud

### Expected behavior

no error

update Compiler.php to the latest version

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
irrelevant
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: #37362 

## TODO

- [x] https://github.com/nextcloud/3rdparty/pull/1357
- [x] Rebase

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
Backport to stable26?

**Comment by nickvergessen** [comment]
at least not right now, maybe later this week or next week when the currently opened 3rdparty bumps are in

**Comment by MaxXor** [comment]
Backport? :slightly_smiling_face:  Deprecation warning is still in NC 26.0.2

**Comment by solracsf** [comment]
Friendly reminder to backport it to stable26, if possible, as per @nickvergessen [comment](https://github.com/nextcloud/server/pull/37444#issuecomment-1516409468).
Thanks 👍

**Comment by nickvergessen** [comment]
26 is a stable version by now so updating 3rdparty libs with minor/major updates is not planned.
Also a deprecation warning is a warning, not an error. If you don't want to see them, downgrade the log level to error+fatal only.

So nothing to do at the moment.

**Pull request merged**
