### PR TITLE
Make timeout a optional parameter

### LINKED ISSUE #17846: External SMB/CIFS Broken on 17.0.1 Beta
After upgrading to 17.0.1 Beta, I am no longer able to add External SMB/CIFS storage. Existing storage remains available to users.

### Steps to reproduce
1. Update to 17.0.1 Beta
2. Add SMB/CIFS external storage

### Expected behaviour
When correct information is added, a green check mark should appear to the left of the entry. The storage should be available via frontend.

### Actual behaviour
Red exclamation mark appears and storage is not saved nor available.

### Server configuration

**Operating system**:
Ubuntu 18.04 LTS

**Web server:**
Apache 2.4.29

**Database:**
MySQL 5.7

**PHP version:**
7.2.24

**Nextcloud version:** (see Nextcloud admin page)
17.0.1 Beta

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 17

I have reverted back to 17 from a snapshot.

### PR DESCRIPTION
**Pull request by kesselb**
Fix #17846 

otherwise you cannot create a new smb storage via gui

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
whoops

**Comment by henrikx** [comment]
I thought I was going crazy and I've been searching for hours. And I was so confused when adding the storage via occ worked fine.
Turns out everything in my setup was correct and it was this all along.

Got reply message "Unsatisfied backend parameters" from webserver when trying to update anything related to external storage via GUI.

**Comment by Golffies** [comment]
Applied the fix described in #17846 on a 17.0.1 stable NC. Did not solve the issue for me. From the web GUI:

```
Using backend: php-smbclient

Error while loading share content.

Icewind\SMB\Exception\ConnectionRefusedException:

    /var/www/html/nc1/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php - line 62:

    Icewind\SMB\Exception\Exception::fromMap({ 1: "Icewin ... "}, 111, null)

    /var/www/html/nc1/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php - line 74:

    Icewind\SMB\Native\NativeState->handleError(null)

    /var/www/html/nc1/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php - line 105:

    Icewind\SMB\Native\NativeState->testResult(false, "smb:///")

    /var/www/html/nc1/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php - line 92:

    Icewind\SMB\Native\NativeState->opendir("smb:///")

    /var/www/html/nc1/apps/smb_test/lib/Controller/SmbController.php - line 95:

    Icewind\SMB\Native\NativeShare->dir(null)

    /var/www/html/nc1/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\SMBTest\Controller\SmbController->dir(null, null, null, null, Icewind\SMB\ ... {}, null)

    /var/www/html/nc1/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\SMBTest\ ... {}, "dir")

    /var/www/html/nc1/lib/private/AppFramework/App.php - line 126:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\SMBTest\ ... {}, "dir")

    /var/www/html/nc1/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\SMBTes ... r", "dir", OC\AppFramew ... {}, { _route: "smb_test.smb.dir"})

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "smb_test.smb.dir"})

    /var/www/html/nc1/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "smb_test.smb.dir"})

    /var/www/html/nc1/lib/base.php - line 1000:

    OC\Route\Router->match("/apps/smb_test/dir")

    /var/www/html/nc1/index.php - line 42:

    OC::handleRequest()
```

**Pull request merged**
