### PR TITLE
Cleanup cron.php method calls

### PR DESCRIPTION
**Pull request by come-nc**
## Summary

Cleanup cron.php and bring it to the modern world. Added `strict_types` as well.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]

**Comment by solracsf** [comment]
Doesn't this need an adjustement?
https://github.com/nextcloud/server/blob/3b77df94e2d359221939c4637bc9f35e89a9bbdc/lib/public/BackgroundJob/IJob.php#L49-L58

**Comment by come-nc** [comment]
> Doesn't this need an adjustement?
> 
> https://github.com/nextcloud/server/blob/3b77df94e2d359221939c4637bc9f35e89a9bbdc/lib/public/BackgroundJob/IJob.php#L49-L58

No, why?
The method was already deprecated as you see in the lines you linked to.
It will be removed along with ILogger class, I do not think it’s useful to remove it before.

**Comment by solracsf** [comment]
Because it espects `ILogger` and we're now passing `LoggerInterface`.

> The method was already deprecated as you see in the lines you linked to.

Fine :)

**Comment by solracsf** [comment]
I've saw it somewhere in PSALM for another PR... 🤔 
But if PSALM is happy now, i'm hapy too :)

**Pull request merged**
