### PR TITLE
Display changes in file versions tab view and detailsView

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @nextcloud/designers @nickvergessen 

downstream of owncloud/core#26511

Before:

bildschirmfoto 2016-11-14 um 15 23 25

After:

bildschirmfoto 2016-11-14 um 15 23 27

### CODE REVIEW

**Comment by jancborchardt** [comment]
Seems good :+1:

**Comment by icewind1991** [comment]
:+1:

**Comment by skjnldsv** [comment]
👍

**Comment by mjobst-necls** [comment]
You might also be interested in this fix https://github.com/owncloud/core/pull/26658

**Comment by jancborchardt** [comment]
@mjobst-necls thanks a lot for the fix and for the pointer! Cool to have you in the community :)

**Pull request merged**
