### PR TITLE
Wrong warning when running HTTP instance

### LINKED ISSUE #26726: Setupcheck return confusing error message on HTTP installation
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. setup a docker instance to run locally over HTTP (not HTTPS) - used for test only, not for production
2. Go to Settings / Overview

### Expected behaviour

It should only warn me about the fact that my connection is not secure (which it does).
It should  not warn me that I am accessing my instance over a secure connection and it is returning insecure URL (which is contradictory with the first warning.

### Actual behaviour

The check is telling me:
1- Accessing site insecurely via HTTP. You are strongly advised to set up your server to require HTTPS instead, ... => This is correct
2- You are accessing your instance over a secure connection, however your instance is generating insecure URLs. This most likely means that you are behind a reverse proxy and the overwrite config variables are not set correctly. Please read => This is incorrect and not relevant compare to point 1

### Server configuration

**Operating system:** docker official image (20-fpm)

**Web server:** nginx

**Database:** postgresql

**PHP version:** official docker image (20-fpm)

**Nextcloud version:** 20.0.9

**Where did you install Nextcloud from:** docker official image (20-fpm)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - cospend: 1.3.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.6
  - documentserver_community: 0.1.9
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_markdown: 2.3.3
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - gpxpod: 4.2.8
  - keeweb: 0.6.5
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.5
  - maps: 0.1.8
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.3.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.7
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.9.1",
        "overwrite.cli.url": "http:\/\/cloud.localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "skeletondirectory": "",
        "maintenance": false,
        "loglevel": 2,
        "data-fingerprint": "ae6f96d7ebbfad52c59f184b8da257e9"
    }
}
```
</details>

**Are you using external storage, if yes which one:** None

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None
### Client configuration

**Browser:** Firefox

**Operating system:** Linux

### Logs

None relevant found

#### Web server error log

None relevant found

#### Nextcloud log (data/nextcloud.log)

None relevant found

#### Browser log

None relevant found

### PR DESCRIPTION
**Pull request by doc75**
fix #26726.
I checked the test suite, but I cannot see if it has to be modified (I cannot understand where the window.protocol is retrieved from in tests ;-(  )
Let me know if anything needs to be modified.

### CODE REVIEW

**Comment by doc75** [comment]
I just updated the js tests to remove the failure. I added one test to ensure the error is not raised when HTTP server return HTTP links. But I commented the existing test as I did not find a way to trick the `window.location.protocol` during test execution. If you have a way to do this, I'll be more than happy to re-activate previous test and make sure the error is raised when HTTPS server return HTTP links.

**Review by nickvergessen — APPROVED** [review]
🙈

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
