### PR TITLE
Fix copy in view-only mode

### PR DESCRIPTION
**Pull request by PVince81**
with shiny tests :star2:

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by PVince81** [comment]
I forgot to adjust the frontend, incoming...

**Comment by PVince81** [comment]
image

done

**Review by skjnldsv — APPROVED** [review]

**Comment by PVince81** [comment]
seems my optimistic behat sentence extension broke other tests :-S

I'll have a look...

**Pull request merged**
