### PR TITLE
Test PHP 8.2 through CI

### PR DESCRIPTION
**Pull request by come-nc**
The point of this PR is to test master with PHP 8.2 nightly/beta builds.
Fix for the problems found should go in other PRs, and this one can be rebased on master to validate.

I may remove non-relevant CI from the branch to speed things up.

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

Contributes to https://github.com/nextcloud/server/issues/32595

### CODE REVIEW

**Comment by PVince81** [comment]
let's try to group the things that need fixing into issues, for the easy ones set the label "good first issue"
for the tricky / urgent ones, we can discuss if we want to do them right away

**Comment by come-nc** [comment]
> ```
> There were 271 errors:
> ```
> 
> (Some are false-positive)

```
There were 119 errors:
```

20 are also there on 8.1 so are false positives.

**Comment by come-nc** [comment]
- mysql/8.1 Tests: 14461, Assertions: 37167, Errors: 14, Failures: 7, Warnings: 168, Skipped: 130.
1532
- mysql/8.2 Tests: 14461, Assertions: 35960, Errors: 100, Failures: 89, Warnings: 149, Skipped: 130.
3159
- sqlite/8.2 Tests: 14461, Assertions: 35960, Errors: 100, Failures: 89, Warnings: 149, Skipped: 130.
3161

**Comment by PVince81** [comment]
@come-nc as dicussed yesterday, please add a list of checkboxes in the top post or the ticket so we get an overview what's left to fix and what challenges we have, for example updating Doctrine, etc.

if a topic gets bigger, like deciding what Doctrine version to pick for 8.2, please also raise a separate ticket to handle that topic separately and link to the checkbox.

thanks!

**Comment by come-nc** [comment]
> @come-nc as discussed yesterday, please add a list of checkboxes in the top post or the ticket so we get an overview what's left to fix and what challenges we have, for example updating Doctrine, etc.
> 
> if a topic gets bigger, like deciding what Doctrine version to pick for 8.2, please also raise a separate ticket to handle that topic separately and link to the checkbox.
> 
> thanks!

https://github.com/nextcloud/server/issues/32595#issuecomment-1315594229

**Comment by come-nc** [comment]
> * mysql/8.1 Tests: 14461, Assertions: 37167, Errors: 14, Failures: 7, Warnings: 168, Skipped: 130.
>   1532
> * mysql/8.2 Tests: 14461, Assertions: 35960, Errors: 100, Failures: 89, Warnings: 149, Skipped: 130.
>   3159
> * sqlite/8.2 Tests: 14461, Assertions: 35960, Errors: 100, Failures: 89, Warnings: 149, Skipped: 130.
>   3161

* mysql/8.1 Tests: 14461, Assertions: 37168, Errors: 14, Failures: 7, Warnings: 168, Skipped: 130.
1532
* mysql/8.2 Tests: 14461, Assertions: 35966, Errors: 99, Failures: 89, Warnings: 149, Skipped: 130.
3147
* sqlite/8.2 Tests: 14461, Assertions: 35965, Errors: 99, Failures: 89, Warnings: 149, Skipped: 130.
3149

Only one error fixed :-(

**Comment by come-nc** [comment]
> > * mysql/8.1 Tests: 14461, Assertions: 37167, Errors: 14, Failures: 7, Warnings: 168, Skipped: 130.
> >   1532
> > * mysql/8.2 Tests: 14461, Assertions: 35960, Errors: 100, Failures: 89, Warnings: 149, Skipped: 130.
> >   3159
> > * sqlite/8.2 Tests: 14461, Assertions: 35960, Errors: 100, Failures: 89, Warnings: 149, Skipped: 130.
> >   3161
> 
> * mysql/8.1 Tests: 14461, Assertions: 37168, Errors: 14, Failures: 7, Warnings: 168, Skipped: 130.
>   1532
> * mysql/8.2 Tests: 14461, Assertions: 35966, Errors: 99, Failures: 89, Warnings: 149, Skipped: 130.
>   3147
> * sqlite/8.2 Tests: 14461, Assertions: 35965, Errors: 99, Failures: 89, Warnings: 149, Skipped: 130.
>   3149
> 
> Only one error fixed :-(

* mysql/8.1 Tests: 14465, Assertions: 37184, Errors: 13, Failures: 7, Warnings: 168, Skipped: 130.
1526
* mysql/8.2 Tests: Tests: 14465, Assertions: 36344, Errors: 75, Failures: 99, Warnings: 150, Skipped: 130.
2896

**Comment by come-nc** [comment]
rebased

**Comment by come-nc** [comment]
(rebased)

**Pull request closed without merging**
