### PR TITLE
Adapt user_migration APIs to have information about failures

### PR DESCRIPTION
**Pull request by come-nc**
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Review by blizzz — DISMISSED** [review]
syntax errors…

**Comment by PVince81** [comment]
I've fixed the syntax error and the psalm warning about void not being bool

**Review by PVince81 — APPROVED** [review]
:+1: if CI passes now

**Comment by PVince81** [comment]
I fixed the cases in the app also https://github.com/nextcloud/user_migration/pull/103 and discovered further fixes needed here in server, see last commit

**Pull request merged**
