### PR TITLE
Fixes related key issue.

### PR DESCRIPTION
**Pull request by lynn-stephenson**
This should fix it, I implemented tests, too. Everything seems to work fine when I ran the tests. I decided to leave additional changes for a later pull request. I don't really see any sense in overhauling the encryption scheme to where it breaks a bunch of unit tests if I'm not going to just pull in [Halite](https://github.com/paragonie/halite), which would be far better than my implementation anyways.

Here you go. :smile:

### CODE REVIEW

**Comment by lynn-stephenson** [comment]
Well, nobody's perfect. Accidentally said version 1 and 2; not 2 and 3. Oops.

**Comment by nickvergessen** [comment]
@kesselb I remember that you pinged me on an issue that also changed this function, right?

**Comment by nickvergessen** [comment]
Ah, it's from you too, ref #23427

**Comment by kesselb** [comment]
Looks good to me :+1: 

I understand (roughly) why using key material derived from the password is better then using the password directly. But my knowledge about crypto is limited hence someone else needs to decide on this.

Please keep in mind that `hash_hkdf` may return false on failure. But that looks more like a theoretical issue because the password is never empty, sha512 shipped with php and length is set by the hash function. If you see any other issues from this method we may use v2 as fallback.

**Comment by lynn-stephenson** [comment]
> I understand (roughly) why using key material derived from the password is better then using the password directly.

@kesselb It's not just that. You don't want to use passwords directly, NOR use practically the same key for encryption and MAC.

I could have improved so much more, and I did on my last PR as a draft (even then I didn't include all cryprography improvements due to a lot of work). But then I realized it broke so much stuff I might as well have swapped out NextCloud's crypto with Halite.

**Comment by lynn-stephenson** [comment]
But switching to Libsodium and Halite is definitely something NextCloud should look into.

**Review by rullzer — APPROVED** [review]
Nice one.
This crypto file is so weird (not passing the cipher around but having it as a class member etc. But that is not related to this PR.

Also kudos for the tests!

**Pull request merged**
