### PR TITLE
Adjust provisioning API tests after #36665

### PR DESCRIPTION
**Pull request by julien-nc**
Sorry, we didn't see the drone failures were because of missing adjustments in tests.

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by julien-nc** [comment]
The Nodb failure seems unrelated.

Acceptance header failure:
image

@nickvergessen @szaimen Any clue?

**Comment by provokateurin** [comment]
The nodb failure is related:
image
It's just not shown when you don't show all the lines (why??).

**Comment by szaimen** [comment]
> It's just not shown when you don't show all the lines (why??).

bad UX I'd say

**Review by provokateurin — APPROVED** [review]

**Comment by szaimen** [comment]
> > @szaimen Should we ignore the acceptance-header failure?
> 
> Possibly it is a flaky test...

seems like it passes now?

**Comment by julien-nc** [comment]
> seems like it passes now?
:see_no_evil: 

Failing cypress test is related with files_versions. Any chance it is related with #36665?

**Comment by nickvergessen** [comment]
cypress and accept-header are flaky atm yeah

**Pull request merged**
