### PR TITLE
Fix expiration date changing for file shared by link

### PR DESCRIPTION
**Pull request by adduxa**
### Problem
Disabling expiration date for the link share leads to creation of a new link share.
### Reason
Since https://github.com/nextcloud/server/commit/1bd6d39b39dd527ad095510173e9012afaafd3b0 `setExpirationDate()` accepts not only `expireDate`, but also `shareId`: https://github.com/nextcloud/server/blob/1bd6d39b39dd527ad095510173e9012afaafd3b0/core/js/sharedialoglinkshareview.js#L625
It was applied at https://github.com/nextcloud/server/blob/1bd6d39b39dd527ad095510173e9012afaafd3b0/core/js/sharedialoglinkshareview.js#L616 but not at https://github.com/nextcloud/server/blob/1bd6d39b39dd527ad095510173e9012afaafd3b0/core/js/sharedialoglinkshareview.js#L596
So it ends up with creating a new link share, and not editing the existing one instead.
https://github.com/nextcloud/server/blob/1bd6d39b39dd527ad095510173e9012afaafd3b0/core/js/shareitemmodel.js#L149
### Solution
Pass correct `shareId` to `setExpirationDate()`

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works. 👍 I also checked in the compiled assets because that is what we are doing here. It's not obvious to new contributors, so don't worry. We are currently about to improve our on boarding here 😃

**Comment by MorrisJobke** [comment]
We also use "signed-off-by" messages inside the commit body to indicate that the developer certificate of origin is respected. You can read more about this in https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work and what this means and how to apply it. Don't be scare it sounds more than it actually is.

And welcome aboard 🚀

**Comment by adduxa** [comment]
@MorrisJobke thanks for the clarification

**Review by danxuliu — APPROVED** [review]
Tested and works :+1: 

Nice explanation, thanks :-)

**Comment by danxuliu** [comment]
@MorrisJobke Wait for the "Signed-off-by"? Squash both commits? Merge as is?

**Comment by MorrisJobke** [comment]
Backport is in #14212

**Pull request merged**
