### PR TITLE
set mountid for personal external storage mounts

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 Any more info on how to test this?

**Comment by MorrisJobke** [comment]
And what it fixes.

**Comment by icewind1991** [comment]
I ran into this with [permissions_overwrite](https://github.com/icewind1991/permissions_overwrite) which uses the mountid to identity external storage and register storage wrappers for specific external storages, this didn't work for user configured storages since they didn't have the mount id set (i have also worked around the issue for now in the app).

In general this is an issue for any code that tries to map mountpoints/storages to an external storage configuration

**Review by rullzer — APPROVED** [review]
Seems fine

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
