### PR TITLE
Only show link share menu if needed

### PR DESCRIPTION
**Pull request by juliusknorr**
The menu for share links does not need to be opened by default any more since the copy icon has been moved out of it. Therefore it makes more sense to me to just open it if we enable password protection by default so the user can enter a password. Otherwise there is no need to open the menu.

@nextcloud/designers

### CODE REVIEW

**Comment by juliushaertl** [comment]
- [ ] Acceptance tests fail

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
Don’t you think it’s useful to open the menu (or at least for the first link of a file)? It is only shown when relevant, when you create the link. People who are not familiar with Nextcloud (= most people) will discover the settings directly then.

**Comment by juliushaertl** [comment]
> Don’t you think it’s useful to open the menu (or at least for the first link of a file)? It is only shown when relevant, when you create the link. People who are not familiar with Nextcloud (= most people) will discover the settings directly then.

Hm thats a good point, on the other side if you just want to create a link and share it, opening the menu will actually require two clicks to get the link (one to close the menu and one to click the clipboard icon). Maybe we could just do that once for every user?

**Comment by jancborchardt** [comment]
> Maybe we could just do that once for every user?

Once for every user is fine too, if that’s possible. :)

**Comment by danxuliu** [comment]
>  Acceptance tests fail

Sorry, I missed this; I will fix them... once you confirm that there are not going to be more changes to the behaviour ;-)

**Comment by juliushaertl** [comment]
> Sorry, I missed this; I will fix them... once you confirm that there are not going to be more changes to the behaviour ;-)

Thanks, I'll ping you if I need some help. :+1:

**Comment by juliushaertl** [comment]
Obsolete with 18 and https://github.com/nextcloud/server/issues/276 which is done during the sidebar rewrite.

**Pull request closed without merging**
