### PR TITLE
Add app config option to disable "Email was changed by admin" email

### PR DESCRIPTION
**Pull request by MorrisJobke**
As discussed with @blizzz @rullzer

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
entry in the sample? Or did you leave it out intentionally?

**Comment by MorrisJobke** [comment]
> entry in the sample? Or did you leave it out intentionally?

It's an app config. Documentation is in https://github.com/nextcloud/documentation/pull/2981

**Pull request merged**
