### PR TITLE
Don't log parameters on user creation in case of error/exception

### PR DESCRIPTION
**Pull request by nickvergessen**
Method in question:
https://github.com/nextcloud/server/blob/cf266ee00491bc0e70fbbb7dc9720a9e2f8c3708/apps/provisioning_api/lib/Controller/UsersController.php#L199-L221

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> The backport to stable13 failed. Please do this backport manually.

@nickvergessen Mind to do this as well?

**Pull request merged**
