### PR TITLE
Fix missing native submit type from OAuth client add button

### LINKED ISSUE #35045: [Bug]: can't add oauth2 client
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

nothing happens when trying to add oauth2 client

### Steps to reproduce

1. go to /settings/admin/security
2. scroll down to  "OAuth 2.0 clients" section, fill Name and Redirection URI
3. click Add

### Expected behavior

oauth2 credentials should be created and showed

### Installation method

Community Docker image

### Operating system

Other

### PHP engine version

_No response_

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
# /usr/bin/docker exec --user 82 -ti nextcloud-app-1 php occ config:list system
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "deepnull.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Etc\/UTC",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "user_backends": [
            {
                "class": "\\OCA\\UserExternal\\BasicAuth",
                "arguments": [
                    "***REMOVED SENSITIVE VALUE***"
                ]
            },
            {
                "class": "\\OCA\\UserExternal\\IMAP",
                "arguments": [
                    "mail.deepnull.com",
                    993,
                    "ssl",
                    "deepnull.com",
                    true,
                    true
                ]
            },
            {
                "class": "\\OCA\\UserExternal\\IMAP",
                "arguments": [
                    "***REMOVED SENSITIVE VALUE***",
                    993,
                    "ssl",
                    "***REMOVED SENSITIVE VALUE***",
                    true,
                    true
                ]
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app.mail.verify-tls-peer": false,
        "data-fingerprint": "34da58b4d28a4249718f0e27e160a387",
        "maintenance": false,
        "loglevel": 0,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_webdav": false,
        "check_for_working_wellknown_setup": false,
        "upgrade.disable-web": true,
        "mysql.utf8mb4": true,
        "has_rebuilt_cache": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "default_phone_region": "US",
        "app_install_overwrite": [
            "user_external",
            "rainloop",
            "phonetrack",
            "jitsi"
        ]
    }
}
```

### List of activated Apps

```shell
# /usr/bin/docker exec --user 82 -ti nextcloud-app-1 php occ app:list
Enabled:
  - activity: 2.17.0
  - analytics: 4.5.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.1.0
  - cfg_share_links: 3.0.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - cospend: 1.5.2
  - dashboard: 7.5.0
  - dav: 1.24.0
  - external: 5.0.0
  - externalpassword: 1.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.1
  - jitsi: 0.15.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 0.2.1
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - phonetrack: 0.7.2
  - photos: 2.0.0
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - rainloop: 7.2.6
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.7.1
  - twofactor_nextcloud_notification: 3.5.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - user_external: 3.0.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflow_pdf_converter: 1.10.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - appointments: 1.14.0
  - apporder: 0.15.0
  - breezedark: 24.0.2
  - checksum: 1.1.5
  - drawio: 1.0.3
  - encryption
  - extract: 1.3.5
  - files_markdown: 2.3.6
  - gpxpod: 4.3.0
  - health: 1.5.1
  - keeweb: 0.6.10
  - money: 0.7.0
  - news: 19.0.0
  - pdf_downloader: 1.0.6
  - suspicious_login
  - transfer: 0.6.0
  - user_ldap
  - video_converter: 1.0.5
  - webhooks: 0.4.0
  - workflow_media_converter: 1.6.0
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- money
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature could not get verified.

Raw output
==========
Array
(
    [money] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature could not get verified.
                )

        )

)
```

### Nextcloud Logs

_No response_

### Additional info

looks like already reported in https://help.nextcloud.com/t/unable-to-add-oauth2-client/149223/2

### PR DESCRIPTION
**Pull request by ChristophWurst**
~~Untested because I'm unable to build server atm.~~

Regression of https://github.com/nextcloud/server/pull/32521. An ordinary button doesn't make a form submit. A native submit button is required for that.

Fixes https://github.com/nextcloud/server/issues/35045

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by giteichi** [comment]
Could not test this fix with my running server, but adding `type="submit"` to the button via browser debugger fixes the problem

**Review by Pytal — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Tried with the compiled assets. The button doesn't have the native type.

**Review by Pytal — APPROVED** [review]

**Comment by ckvtz** [comment]
Hi ChristophWurst,

I am facing a similar issue trying to integrate openproject with my nextcloud community version 25.0.3. 

Has this issue been fixed in this version? Can you help if there is any workaround?

Thank you.

**Pull request merged**
