### PR TITLE
Run cs:check a second time to show diff

### PR DESCRIPTION
**Pull request by kesselb**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks like you need to execute the diff first, because now the GitHub integration is not available anymore.

**Comment by kesselb** [comment]
Haha :) It's not that bad. I added --quiet to suppress the output. Goal was to disable unused status information but it seems also the report itself is not printed anymore.

**Comment by MorrisJobke** [comment]
> Haha :) It's not that bad. I added --quiet to suppress the output. Goal was to disable unused status information but it seems also the report itself is not printed anymore.

🤦

**Review by MorrisJobke — APPROVED** [review]
I like it - also makes it easier for new contributors to understand the problem the linter highlights 👍

**Comment by MorrisJobke** [comment]
Merge because it is only administrative stuff :)

**Pull request merged**
