### PR TITLE
[stable23] Temporarily disable samba-non-native as it times out too often

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of https://github.com/nextcloud/server/pull/31088

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
ironically we still see samba failures

**Comment by nickvergessen** [comment]
> ironically we still see samba failures

yes due to:

> didnt we backport the image change yet?

**Pull request closed without merging**
