### PR TITLE
[Automated] Update psalm-baseline.xml

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated update psalm-baseline.xml with fixed psalm warnings

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by skjnldsv** [comment]
Success! :tada:

**Comment by skjnldsv** [comment]
`@nextcloud-command nextcloud-command force-pushed the automated/noid/psalm-baseline-update branch from d6152bf to 284c039 4 minutes ago`

Hum, something weird happened here :thinking:

**Pull request merged**
