### PR TITLE
Migrate Scrutinizer to new PHP Analysis

### PR DESCRIPTION
**Pull request by stweil**
See this article for details:
https://scrutinizer-ci.com/docs/tools/php/php-analyzer/guides/migrate_to_new_php_analysis

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
We don't run scrutinizer anymore :/ 

cc @ChristophWurst as we talked today about this. 

cc @rullzer for maybe re-adding it

**Comment by ChristophWurst** [comment]
I'm aware of this and I'm actually using this for "my" apps:
* https://github.com/nextcloud/twofactor_u2f/blob/dc4360a2df6b545ceae4f3c7ffc17c4ee6a20d5f/.scrutinizer.yml#L6
* https://github.com/nextcloud/mail/blob/15a659930b950e85c6737ff7f802d2e9f209909f/.scrutinizer.yml#L6
* https://github.com/nextcloud/twofactor_gateway/blob/ed638a4e18c2e8fc5dcd2a67d3aac3ec87c5bc9e/.scrutinizer.yml#L6
* https://github.com/nextcloud/twofactor_totp/blob/e291256abc6b95c1f74c4b83e3bcd060eec1153b/.scrutinizer.yml#L6

Regarding re-enabling Scrutinizer for server I'm undecided. I personally like the reports and check them when I do (bigger) PRs with new methods/classes in the apps above because there have been many occasions where the checks found some bugs I otherwise would have missed. If nobody cares about the reports in server, we wouldn't gain much from re-enabling this integration though.

**Comment by ChristophWurst** [comment]
If we decide to not use Scrutinizer again, I'd suggest to also remove its config file.

**Comment by MorrisJobke** [comment]
I'm totally fine with enabling it, but on my side there is very little time to actually look into it, but if others like @danielkesselberg or @rullzer would occasionally check it: fine :) Then enable it and try to get something out of it :)

**Comment by rullzer** [comment]
Sometimes I check it. Altough lately I did not have time.
I'm fine with enabling it again if indeed @ChristophWurst or others check it. Can't hurt to have more analysis

**Review by ChristophWurst — APPROVED** [review]
Yesss :rocket:

**Review by kesselb — APPROVED** [review]

**Pull request merged**
