### PR TITLE
Update CRL to contain revoked files_external_dropbox, passman & payback

### PR DESCRIPTION
**Pull request by MorrisJobke**
* see https://github.com/nextcloud/app-certificate-requests/pull/221

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
failing CI on the cert stuff

**Comment by MorrisJobke** [comment]
> failing CI on the cert stuff

Tests seem to be against now revoked certs :/

**Comment by MorrisJobke** [comment]
Let me also update due to https://github.com/nextcloud/app-certificate-requests/pull/219#issuecomment-463577509

**Comment by MorrisJobke** [comment]
> failing CI on the cert stuff

the `passman` cert was also revoked. I updated the test cert to be the new one and the tests now work locally again.

**Pull request merged**
