### PR TITLE
Only add the vue exeption to actual button elements

### LINKED ISSUE #29591: Button regressions in 23
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade to Nextcloud 23 (dev instance)
2. Use Calendar or Mail

### Expected behavior

Buttons render the same way as in Nextcloud 22

Bildschirmfoto von 2021-11-08 11-42-26
Bildschirmfoto von 2021-11-08 11-43-37

^ latest and greatest 22 production instance

### Actual behavior

Bildschirmfoto von 2021-11-08 11-43-01
Bildschirmfoto von 2021-11-08 11-44-47
^ today's server master

---

This is possibly caused by https://github.com/nextcloud/server/pull/25721

cc @GretaD @marcoambrosini

### PR DESCRIPTION
**Pull request by marcoambrosini**
Fixes https://github.com/nextcloud/server/issues/29591

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Do you have examples of where this helps or not? I'm not able to verify it would actually fix the regressions

**Comment by marcoambrosini** [comment]
There is this https://github.com/nextcloud/nextcloud-vue/issues/2371
Maybe it's too late for this?

**Review by Valdnet — APPROVED** [review]

**Comment by Valdnet** [comment]
As for me, it works fine after the changes 👍.

@marcoambrosini Thanks for the memory and fix 😉.

**Review by skjnldsv — APPROVED** [review]

**Comment by ChristophWurst** [comment]
will we backport to 22 as well?

**Review by st3iny — APPROVED** [review]
Fixes https://github.com/nextcloud/nextcloud-vue/issues/2371 but does not fix https://github.com/nextcloud/server/issues/29591.

However, I just realized that the button regression in calendar is caused by a local css rule. We should fix it in the calendar repo directly.

**Comment by st3iny** [comment]
PS: I could not reproduce the reply button problem from https://github.com/nextcloud/server/issues/29591. It's working fine for me with and without this patch.

**Comment by marcoambrosini** [comment]
> will we backport to 22 as well?

Yes I think we should

**Comment by blizzz** [comment]
if you backport to 22, backport to 23, too

**Pull request merged**
