### PR TITLE
Fix pop over menu opacity

### LINKED ISSUE #3522: Three dots menu in files in greyed out
bildschirmfoto 2017-02-17 um 00 23 49

@skjnldsv Do you have an idea why it looks like that? I would say this change came in during the last 1-2 days roughly.

### PR DESCRIPTION
**Pull request by MorrisJobke**
Before:

bildschirmfoto 2017-03-26 um 14 10 34
bildschirmfoto 2017-03-26 um 14 10 37

After:

bildschirmfoto 2017-03-26 um 14 10 10
bildschirmfoto 2017-03-26 um 14 10 13

Fixes #3522

cc @nextcloud/designers @ChristophWurst @nickvergessen @rullzer @skjnldsv @juliushaertl

### CODE REVIEW

**Comment by MorrisJobke** [comment]
In comparison to #3728 this PR here doesn't change the opacity of the permanent entries in the file list  itself and it additionally also fixes other pop over menus, because they were also greyed out.

**Comment by MorrisJobke** [comment]
> it additionally also fixes other pop over menus, because they were also greyed out.

bildschirmfoto 2017-03-26 um 14 16 47

vs

bildschirmfoto 2017-03-26 um 14 16 32

**Comment by jancborchardt** [comment]
> it additionally also fixes other pop over menus, because they were also greyed out.

This was intended to show which of the states is active and it’s a regression that it’s gone. Fixed it with my commit :)
capture du 2017-03-27 11-17-26

**Review by jancborchardt — APPROVED** [review]
Let’s do it! :)

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer @LukasReschke

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
