### PR TITLE
Make fewer fields mandatory in the bug reporting

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by acsfer** [comment]
IMO checkboxes/dropdowns shoud be keep; they are quick & easy to fill and provide good information.

**Review by artonge — APPROVED** [review]

**Comment by acsfer** [comment]
And also disable **List of activated Apps**

**Comment by nickvergessen** [comment]
> IMO checkboxes/dropdowns shoud be keep; they are quick & easy to fill and provide good information.

Complains already started a discussion on our mailing list.
Nop, we will only make mandatory what is really required. In some cases reports don't even know the information and would therefor be forced to give maybe wrong one, or give up on reporting

**Comment by acsfer** [comment]
I understand, but an issue template without required information to correctly debug it, I just ignore it :)
But i'm just a contributor, not a maintainer, so decision is yours 👼

**Comment by nickvergessen** [comment]
> but an issue template without required information to correctly debug it, I just ignore it :)

yeah, but e.g. as a maintainer I also want to be able to quickly report something and maybe fill in more information later, or I know the app list doesn't matter or so and would still have to fill lots of fields and checkboxes.

**Comment by acsfer** [comment]
Sure. On checkboxes I'm just talking about NC version, PHP version and SQL engine.
I believe these 3 can help a lot debugging some things, and it takes 10sec to select them all.

But still, **fields are there** so one can always fill it if he/she wants. 👍

**Review by PVince81 — APPROVED** [review]
:+1: thanks

**Pull request merged**
