### PR TITLE
Improve email results for sharing

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Search for `Foo Bar <foo.bar@example.tld>` in the share sidebar
2. See a broken entry

Before 💥 invalid remote share | After ✨ working email share
---|---
`<` in user id is invalid<br>`>` in server part is invalid | ✅
Bildschirmfoto vom 2022-11-11 09-49-34 | Bildschirmfoto vom 2022-11-11 09-49-24
Bildschirmfoto vom 2022-11-11 09-49-45 | Bildschirmfoto vom 2022-11-11 09-49-02

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
```
There was 1 failure:

1) Test\User\DatabaseTest::testSearch

/drone/src/tests/lib/User/Backend.php:114
/drone/src/tests/lib/User/DatabaseTest.php:125
```

I don't think it's related (also only pgsql 13 failing), but restarting ci in case. Everything else is green.

**Pull request merged**
