### PR TITLE
Make background cover whole viewport

### PR DESCRIPTION
**Pull request by localjo**
Without a min-height, wider viewports can result in a blank white space at the bottom of the screen. This CSS ensures that doesn't happen.

Here's the issue (note the white bar at the bottom):
Screen Shot 2021-03-15 at 2 44 46 PM

With this change the purple extends to the bottom of the viewport and there is no white bar.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by localjo** [comment]
I'm not sure what the failing Node check is about. It's saying that there's something uncommitted, which doesn't make sense to me in this context. Maybe a problem with the webpack config or another build script, which I didn't touch.

**Review by marcoambrosini — APPROVED** [review]

**Comment by szaimen** [comment]
> I'm not sure what the failing Node check is about. It's saying that there's something uncommitted, which doesn't make sense to me in this context. Maybe a problem with the webpack config or another build script, which I didn't touch.

I guess the js needs to get recompiled and submitted. But I forgot how to do this. (I know that there was a command here an github that you could trigger for this)

**Comment by szaimen** [comment]
> /compile amend /

That was it, thanks! :)

**Comment by PVince81** [comment]
taking over, let me rebase and rerun this locally since the bot is not able to

**Comment by PVince81** [comment]
since I can't push here, I made a new PR here: https://github.com/nextcloud/server/pull/26212

**Pull request closed without merging**
