### PR TITLE
Add a magic wrapper to allow phpunit4 to run the code again 

### PR DESCRIPTION
**Pull request by nickvergessen**
Review please @oparoz @LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by nickvergessen** [comment]
Fixes the issue: https://github.com/nextcloud/gallery/pull/172

**Comment by nickvergessen** [comment]
Review please @oparoz @LukasReschke @MorrisJobke

**Comment by oparoz** [comment]
I love magic! :+1:

**Comment by oparoz** [comment]
This test PR proves that it fixes things: 
https://github.com/nextcloud/gallery/pull/172

**Comment by rullzer** [comment]
Fine by me. As long as we still have apps that need to support <NC11 :+1:

**Pull request merged**
