### PR TITLE
[IAppConfig] add RepairStep to migrate lazy appconfig

### PR DESCRIPTION
**Pull request by ArtificialOwl**
A SetupCheck to initialize the migration of a list of config value to lazy loading

### CODE REVIEW

**Review by come-nc — CHANGES_REQUESTED** [review]
This is not what setup checks are for, this should be a migration.
It’s not even checking anything.

**Comment by ArtificialOwl** [comment]
> This is not what setup checks are for, this should be a migration. It’s not even checking anything.

ok, it is still checking that all lazy config from a list have been migrated but I switched it to a daily background job

**Comment by ArtificialOwl** [comment]
The job is now created during Setup and Repair (upgrade) process.

**Review by come-nc — COMMENTED** [review]
But why does it need to run daily?

**Comment by ArtificialOwl** [comment]
it's a light process. can be weekly, but the idea is that the list is not final and more elements might be added in the future

**Comment by come-nc** [comment]
Then it should be a repair step, no?
https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/repair.html#repair-steps

**Pull request closed without merging**
