### PR TITLE
Apply group limit on remove from group

### PR DESCRIPTION
**Pull request by come-nc**
## Summary

When removing a user from a group, remove shares which would not be creatable anymore according to group limit on sharing.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]

**Review by yemkareems — APPROVED** [review]

**Review by bigcat88 — APPROVED** [review]

**Comment by jonas2515** [comment]
Tbh this seems not very thought through, it makes the behavior of existing shares on settings and group membership changes super inconsistent.

While now existing shares are removed when manipulating the groups of a user, they aren't removed when enabling the "only share between users of group" setting. Neither are they removed when disabling the whole share API, nor when changing the "limit/exclude sharing to/from groups" settings. I assume the behavior for re-shared shares would also have to be considered.

I don't think a simple action like toggling group membership (or toggling a checkbox in settings) should do such destructive things as deleting shares, can we maybe just remove this behavior again?

@come-nc ping just in case you don't receive notifications for merged PRs.

**Comment by come-nc** [comment]
> While now existing shares are removed when manipulating the groups of a user, they aren't removed when enabling the "only share between users of group" setting. Neither are they removed when disabling the whole share API, nor when changing the "limit/exclude sharing to/from groups" settings. I assume the behavior for re-shared shares would also have to be considered.
> 
> I don't think a simple action like toggling group membership (or toggling a checkbox in settings) should do such destructive things as deleting shares, can we maybe just remove this behavior again?

I think it’s for this reason that changing settings is not directly deleting shares. But it would be a nice feature to have a button to apply current settings to existing shares indeed.

But this PR is not when changing settings but when changing groups.
It’s fixing what was reported as a security issue, see https://github.com/nextcloud/security-advisories/security/advisories/GHSA-35gc-jc6x-29cm
When configuring sharing restriction based on groups, it should be expected that removing a user from a group has consequences.

**Pull request merged**
