### PR TITLE
chore(deps): Bump @nextcloud/vue to v8.14.0

### PR DESCRIPTION
**Pull request by hamza221**
- https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.14.0
- https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.13.0
- https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.12.0
- https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.11.3

### CODE REVIEW

**Review by sorbaugh — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Cypress restarted

**Comment by skjnldsv** [comment]
Settings App management -- Can enable an installed app (failed)
Timeout failure, we should catch the loading request

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
:tada: :tada:

**Comment by AndyScherzinger** [comment]
🎉

**Pull request merged**
