### PR TITLE
Unbreak browser back button not working

### PR DESCRIPTION
**Pull request by pawohl**
Removed comment left over from https://github.com/nextcloud/server/commit/ab73c9c3282fa3550fcf349ea30e399de202f4ed#diff-c493b80ad1a9bcfa6b69637097972371L1314

Resolves: #15265

### CODE REVIEW

**Comment by pawohl** [comment]
Verified locally. After removing the line removed by this commit, browser navigation works again.

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
> /backport to master

Seems like this has been fixed on master already by @ChristophWurst when getting rid of js.js

**Comment by skjnldsv** [comment]
@MorrisJobke only 16 is broken I think :)

**Pull request merged**
