### PR TITLE
Deprecate String.prototype.toRgb

### PR DESCRIPTION
**Pull request by ChristophWurst**
:fire:  aint nobody need that. And according to a quick ripgrep search we also don't really use it anywhere.

:eyes: @nextcloud/javascript

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
The talk app seem to use it - @nickvergessen

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
conflicts

**Comment by rullzer** [comment]
> The talk app seem to use it - @nickvergessen

that is why we deprecate it ;)
But yeah like I said maybe we move this to a dedicated package or something somewhere

**Comment by ChristophWurst** [comment]
> But yeah like I said maybe we move this to a dedicated package or something somewhere

Or if it's just Talk then we move it there ;)

**Comment by skjnldsv** [comment]
Where shall we put this function btw? We should have a util library maybe?

**Comment by ChristophWurst** [comment]
Is it used in more than one app? Yeah, should be a utility lib then.

**Comment by skjnldsv** [comment]
Well, we use it in the vue components, the colour generator :)

**Comment by nickvergessen** [comment]
Then move it there and expose it so talk can use it from there?

**Pull request merged**
