### PR TITLE
Fix encoding of sanitized translation strings

### LINKED ISSUE #1735: Calendar settings menu has wrong title
### Steps to reproduce
1. Open the Calendar
2. Look at the settings menu bottom-left

### Expected behaviour
The title should be "Settings & import"

### Actual behaviour
The title is "Settings &amp;amp; import"

scrot20191219145413

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1) 2.0.0 beta 3

### Client configuration
**Browser:** (e.g. Firefox 48) Firefox 70.0

**Operating system:** (e.g. Arch Linux) Fedora 29

### Server configuration

**Operating system**: (e.g. Debian 8) DSM 6.2

**Web server:** (e.g. Apache, Nginx,...) Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL) MariaDB

**PHP version:** (e.g. 7.0.3) 7.3

**Nextcloud Version:** (see admin page, e.g. 17.0.2) 18.0.0 Beta 3

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:** N/A

### LINKED ISSUE #18662: Escaping of Ampersand "&" in translation strings broken
### Steps to reproduce
1. Open the security section in the settings and look at the headline of "Devices & sessions"

### Expected behaviour
It should be `Devices & sessions` or `Geräte & Sitzungen`.

### Actual behaviour
It is `Devices &amp; sessions` or `Geräte &amp; Sitzungen`.
I think this is caused by the replacement for escapeHTML as i have seen the same issue in my own app.

In NC 17 `t('core', 'A&B');` returns  `"A&B"`, in NC 18 `t('core', 'A&B');` returns `"A&amp;B"`

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3.13

**Nextcloud version:** 18.0.0 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** releases page on Github (also happens with official docker image nextcloud:18-beta-fpm)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - passwords: 2020.1.0-BUILD
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 1.2.3
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "passwords.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.8",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "defaultapp": "passwords",
        "theme": "",
        "maintenance": false,
        "updater.release.channel": "beta"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 71

**Operating system:** Ubuntu 18.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
no errors
```
</details>

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/calendar/issues/1735

Before `/settings/user/security` showed `Devices &amp; sessions`, not it shows `Devices & session` again. 

~~Trick stolen from https://forum.vuejs.org/t/how-to-display-escaped-html-special-characters-the-right-way/33845/5 and https://jsfiddle.net/jamesbrndwgn/3pfmw4cd/1/~~

Edited by @georgehrke:
fixes https://github.com/nextcloud/server/issues/18662

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Review by georgehrke — CHANGES_REQUESTED** [review]
If I'm not completely mistaken, this will also return stuff like `<` instead of `&lt;`, possible allowing injection of HTML.

Since this is used all over the place and not just inside Vue or Handlebar templates, I'm not sure that we can assume that it will later on be escaped.

Or am i wrong here?

**Comment by rullzer** [comment]
> If I'm not completely mistaken, this will also return stuff like `<` instead of `&lt;`, possible allowing injection of HTML.
> 
> Since this is used all over the place and not just inside Vue or Handlebar templates, I'm not sure that we can assume that it will later on be escaped.
> 
> Or am i wrong here?

Am mmm yes.
but then those will have the same issues I guess... with escaping the & again...

**Comment by ChristophWurst** [comment]
> Since this is used all over the place and not just inside Vue or Handlebar templates, I'm not sure that we can assume that it will later on be escaped.

That would only be a problem for the cases where we use jQuery's `.html(...)`, Vue's `v-html` or write HTML code to nodes manually, right?

**Comment by georgehrke** [comment]
> That would only be a problem for the cases where we use jQuery's .html(...), Vue's v-html or write HTML code to nodes manually, right?

Yes, and I wouldn't be surprised if in some dark corner of javascript we haven't touched since 2015 we write code to nodes manually. Or I wouldn't rule out that some apps do that, since up until now `translate` was supposed to escape translations.

**Comment by ChristophWurst** [comment]
> Yes, and I wouldn't be surprised if in some dark corner of javascript we haven't touched since 2015 we write code to nodes manually. Or I wouldn't rule out that some apps do that, since up until now `translate` was supposed to escape translations.

True, but up until https://github.com/nextcloud/server/pull/17123 `translate` returned `&`s.

**Comment by georgehrke** [comment]
> True, but up until #17123 translate returned &s.

Which most Browsers can deal with, can't they? And returning unescaped ampersands is still less of a threat than not escaping at all.

My point is just that this is a pretty severe breaking change and I'm worried about introducing XSSs or other injections.

My suggestion would be to keep the current behaviour as default and put the proposed behaviour behind an option `useForTemplating` (or some better name). I would also be fine with defaulting `useForTemplating` to true in the nextcloud-l10n package.

**Comment by rullzer** [comment]
Or we do it the stupid sumple way for now.

just do a replace of `&amp;` with `&` of the string we get back from DOMPurify

**Review by georgehrke — APPROVED** [review]

**Comment by nickvergessen** [comment]
This looks very  dangerous. I think it should be fixed in the respective place instead?

**Comment by ChristophWurst** [comment]
> I think it should be fixed in the respective place instead?

Easier said than done as we're talking about translations. You might assume `&` is only used where it's found in the original string but you can't be sure.

**Comment by nickvergessen** [comment]
Same for `'` from french translations. Just fix it once reported, instead of potentially creating security problems

**Comment by nickvergessen** [comment]
Okay, seems I misunderstood this a bit. I thought this was a misbehaviour of the single instance here and you tried to fix it globally.
But instead the problem is that an update of DOMPurify broke all usages and automatically escapes them now.

E.g.:

```js
			console.info(t('spreed', 'You: {lastMessage}', {
				lastMessage: '<3',
			}))
			// Before 'You: &lt;3'
			// After 'You: &lt;3'
			console.info(t('spreed', 'You: {lastMessage}', {
				lastMessage: '<3',
			}, undefined, {
				escape: false,
			}))
			// Before 'You: <3'
			// After 'You: &lt;3'
```

this worked before, but it doesn't work now anymore. You can see this e.g. in the last message line of talk. I'd very much like to not have to do things like: https://github.com/nextcloud/spreed/pull/2815

**Comment by georgehrke** [comment]
Yet another problem caused by DomPurify: https://github.com/nextcloud/calendar/issues/1915

**Comment by georgehrke** [comment]
Alternative suggestion:
- Introduce `unescapedTranslate` and `unescapedTranslatePlural`, which doesn't call the final `DomPurify` on the entire string:
https://github.com/nextcloud/server/blob/6bc9969e87bcae373f94fb56bf04aa5502b1be60/core/src/OC/l10n.js#L125

Everywhere you know that you will use proper escaping (like in vue or handlebar templates), just use the unescaped one and let vue do it.

For most vue apps we have, changing to the unescaped version is just a matter of changing one line:
https://github.com/nextcloud/calendar/blob/master/src/main.js#L56

**Comment by nickvergessen** [comment]
That would work, although from my pov what we would want is: Purify the translations, just not the inserted parameters.

**Comment by ChristophWurst** [comment]
>  although from my pov what we would want is: Purify the translations

I think this is where the evil comes from. We assume that translations are put into HTML as they are. But they might be used in other APIs or put somewhere where escaping is done automatically. Hence the double escaping. IMO the translation helper should only translate. Escaping should be an explicit step.

**Comment by ChristophWurst** [comment]
Closing due to lack of progress. None of the proposed solutions were acceptable.

**Pull request closed without merging**
