### PR TITLE
Make activity events strict

### PR DESCRIPTION
**Pull request by nickvergessen**
I think it should be fine, because the methods throw already anyway, so we can also do it via type hints.

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Review by rullzer — APPROVED** [review]
Cool stuff!
Just add it to https://github.com/nextcloud/server/issues/11045 as well

**Comment by MorrisJobke** [comment]
https://drone.nextcloud.com/nextcloud/server/11443

**Comment by nickvergessen** [comment]
fixed

**Pull request merged**
