### PR TITLE
unlink(....): No such file or directory at ..../lib/private/Preview/Movie.php#98

### LINKED ISSUE #17661: unlink(....): No such file or directory at ..../lib/private/Preview/Movie.php#98
Hello,
when creating preview files of movies, the following error occurs:
unlink(.....): No such file or directory at ..../lib/private/Preview/Movie.php#98

I think you can solve the problem like this:

File: /lib/private/Preview/Movie.php
```
		if ($returnCode === 0) {
			$image = new \OC_Image();
			$image->loadFromFile($tmpPath);
			unlink($tmpPath);
			if ($image->valid()) {
				$image->scaleDownToFit($maxX, $maxY);
				return $image;
			}
		}
               if(is_file($tmpPath)){ //-- check if the file exists before deleting
		     unlink($tmpPath);
                }
		return null;
```

regards
Schneidoa

### PR DESCRIPTION
**Pull request by Schneidoa**
Fix #17661

### CODE REVIEW

**Comment by Schneidoa** [comment]
fix: #17661

**Comment by kesselb** [comment]
Thanks :+1: 

This will handle the case positive return code but invalid image correctly by not calling unlink twice.

**Review by kesselb — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Nice catch!

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Backports?

**Pull request merged**
