### PR TITLE
Fix design of 2FA login screens

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Fix rending of empty selection screen (ul missing)
* Fix rendering of backup codes inputs

---
# Selection screen, before
bildschirmfoto von 2018-10-03 15-25-33
# Selection screen, after
bildschirmfoto von 2018-10-03 15-25-49

# Backup codes, before
bildschirmfoto von 2018-10-03 15-30-32
# Backupcodes, after
bildschirmfoto von 2018-10-03 15-30-13

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Review by rullzer — APPROVED** [review]
Looking good

**Review by jancborchardt — APPROVED** [review]
Looks good! :+1:

**Comment by jancborchardt** [comment]
For separate pull request:
- Add lock icon to the initial page
- Make sure "Use backup code" uses `primary` button class

**Pull request merged**
