### PR TITLE
User management polishing

### PR DESCRIPTION
**Pull request by juliusknorr**
From #10094

- [x] "no more results" is not necessary, the whitespace is enough
- [x] Header labels don't match up with new user input placeholders ("Full name" vs "Display name")
- [ ]  Table headers should be lighter font color than the rest of the text
- [x]  "Groups" header doesn't need to be shown when there are no groups
- [x]  Clear button (x) on new user entry not needed, also too dangerous for misclicks to put it next to the confirm button
- [x] Layout is not responsive at all. Should narrow down column widths
- [x] Commit updated webpack production build

### CODE REVIEW

**Comment by juliushaertl** [comment]
Regarding the responsiveness of the layout, there are still two small issues, but I cannot figure out how we could address them with the grid layout. 

- [ ] The last column with actions cannot be forced to a specific width
image
- [ ] When resizeing the window there is a small area when the grid layout is somehow broken. This happens when resizeing between a width where the scrollbar appears and a width when all columns are shown.
image

@skjnldsv Maybe you can help me with some grid magic here?

**Comment by MorrisJobke** [comment]
@juliushaertl @skjnldsv @jancborchardt Do we want to get it in as it is, because it fixes stuff already and fix the remaining this additionally. They do happen on master as well, right @juliushaertl ?

**Comment by juliushaertl** [comment]
@MorrisJobke Yes, we can still fix the remaining issues later.

**Comment by MorrisJobke** [comment]
Could you push the compiled JS file? Then we will review it and merge it.

**Comment by MorrisJobke** [comment]
> Could you push the compiled JS file? Then we will review it and merge it.

Let me do it, because I compiled it anyways 🙈

**Review by MorrisJobke — APPROVED** [review]
Works nice 👍

**Review by rullzer — APPROVED** [review]
whoohoo! :beers:

**Comment by juliushaertl** [comment]
> Let me do it, because I compiled it anyways

Sorry, hadn't those comments in the tab i had open when I pushed again :see_no_evil:

**Comment by MorrisJobke** [comment]
> Sorry, hadn't those comments in the tab i had open when I pushed again 🙈

Don't worry ;)

**Comment by MorrisJobke** [comment]
Acceptance tests fail:

```
    Then I see that the "Languages" column is shown            # UsersSettingsContext::iSeeThatTheColumnIsShown()
      The Languages column in Users Settings could not be found after 100 seconds (NoSuchElementException)
```

**Comment by jancborchardt** [comment]
Great stuff as always @juliushaertl! :)

**Pull request merged**
