### PR TITLE
Fix apps menu on mobile

### LINKED ISSUE #10851: Mobile app menu misplaced
on RC1:

screenshot_chrome_20180825-141055

I think it only happens when on mobile beacuse the screen is small enough.

@skjnldsv @juliushaertl @weeman1337

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #10851

### CODE REVIEW

**Review by juliusknorr — DISMISSED** [review]
@skjnldsv This breaks the other popovers on mobile:

image

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
@skjnldsv see the comment from @juliushaertl

**Comment by skjnldsv** [comment]
@juliushaertl updated and fixed the typo!

**Comment by skjnldsv** [comment]
@juliushaertl :ping_pong:

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
