### PR TITLE
Fix tests with email templates

### PR DESCRIPTION
**Pull request by CarlSchwan**
Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by solracsf — APPROVED** [review]
🙈 🙉 (should be backported too)

**Review by szaimen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by acsfer** [comment]
@CarlSchwan manual backports of https://github.com/nextcloud/server/pull/30653 have been pushed.

**Comment by CarlSchwan** [comment]
Weird it seems like it didn't fix the tests on the server :( It worked locally. I will investigate a bit more

**Review by nickvergessen — APPROVED** [review]

**Comment by CarlSchwan** [comment]
the static analysis issue is unrelated, fix in https://github.com/nextcloud/server/pull/30745

**Pull request merged**
