### PR TITLE
Improve mountmanager

### PR DESCRIPTION
**Pull request by rullzer**
@icewind1991 does this make sense to you?

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
🐘

**Comment by MorrisJobke** [comment]
Restarted CI run: https://drone.nextcloud.com/nextcloud/server/6267

**Comment by MorrisJobke** [comment]
Many failures in the CI jobs :/

**Comment by rullzer** [comment]
Fixed them

**Pull request merged**
