### PR TITLE
OAuth2: move to scoped css in vue app

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by skjnldsv** [comment]
Any reason why? :)

**Comment by rullzer** [comment]
Because it is not used anywhere else anyways.
Keeps the css close to the objects that use it.

And. Why not :wink:

**Comment by rullzer** [comment]
> @rullzer it's just that now it's harder for people to simply edit the design if it's needed ;)
> They have to compile it again :)

Ah well fair enough. However this css has not been changed since the dawn of time.
And it saves the CSS loading (which is a separate request)

**Review by skjnldsv — APPROVED** [review]
Then if you think it's good, good for me :)

**Review by ChristophWurst — APPROVED** [review]
Woohoo, one request less per page load :rocket:

**Pull request merged**
