### PR TITLE
PHP 7.0 CI

### PR DESCRIPTION
**Pull request by rullzer**
Now for real php 7.0 CI.

Lets see what drone tells us

### CODE REVIEW

**Comment by rullzer** [comment]
Disabled coverage for now. Since it took > 2 hours.

**Comment by rullzer** [comment]
It seems we run out of terminal space.
So let me fix some of those warnings...

**Comment by rullzer** [comment]
Sine 7.0 has postgres failures. And I feel we should move to a full test coverage matrix anyways the situation now is the following (and passing at the moment).

- [x] sqlite
  * [x] 5.4
  * [x] 5.5
  * [x] 5.6
  * [x] 7.0
- [ ] mysql
  * [ ] 5.4
  * [ ] 5.5
  * [x] 5.6
  * [ ] 7.0
- [ ] postgres
  * [ ] 5.4
  * [ ] 5.5
  * [x] 5.6
  * [ ] 7.0
- [ ] oracle
  * [ ] 5.4
  * [ ] 5.5
  * [ ] 5.6
  * [ ] 7.0

So we still have some to add. (Also mariaDB makes sense).
But lets get this in so we have at least php7.0 tests.

**Comment by MorrisJobke** [comment]
makes sense 👍 and the change

**Pull request merged**
