### PR TITLE
[27] kerberos sso ci fixes

### PR DESCRIPTION
**Pull request by icewind1991**
Selective backport from https://github.com/nextcloud/server/pull/40165 with just the ci fixes.

Since 27 shouldn't need user_saml changes this can be merged early

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by blizzz** [comment]
Um, the test should be triggered, but it is not in the list

**Comment by blizzz** [comment]
let's deal with this after the RCs are done, it's not prod code

**Comment by blizzz** [comment]
re-enabled kerberos test

**Comment by blizzz** [comment]
Cannot connect to the DC-AD

```
Failed to connect host 172.17.0.2 on port 135 - NT_STATUS_CONNECTION_REFUSED
Failed to connect host 172.17.0.2 (krb.domain.test) on port 135 - NT_STATUS_CONNECTION_REFUSED.
```

**Comment by blizzz** [comment]
moving to 27.1.5

**Comment by blizzz** [comment]
closing for no activity

**Pull request closed without merging**
