### PR TITLE
Add support for touch events to jQuery UI

### PR DESCRIPTION
**Pull request by danxuliu**
Although [jQuery UI is expected to be removed in the future](https://github.com/nextcloud/server/issues/4134) this will not happen before Nextcloud 13. jQuery UI does not support touch events out of the box, so the features that depend on jQuery UI, like dragging files in the Files app, are not available on touch screens.

[jQuery UI Touch Punch](https://github.com/furf/jquery-ui-touch-punch) adds support to touch events by mapping them to their mouse counterparts, takes just 1.3KiB minified, and requires no changes to the existing code; [it is the recommended way to add support for touch events](https://github.com/jquery/jquery-ui/pull/1771#issuecomment-264015959) by [the project lead of jQuery UI](http://jqueryui.com/about/#scott-gonz-lez-project-lead).

It is dual licensed under the MIT license and the GNU GPL v2, so we can use it under the MIT license (as GNU GPL v2 only, without the _or later_ part, is not compatible with the GNU AGPL V3+ if I recall correctly).

Unfortunately the latest version is a few years old, and probably it will not be able to handle every situation, but it is better anyway than what we have now which is no support at all ;-)

Finally, should this be backported to Nextcloud 12?

### CODE REVIEW

**Comment by jancborchardt** [comment]
Guess this is best reviewed by @nextcloud/javascript? :)

**Review by rullzer — APPROVED** [review]
sure...

**Comment by MorrisJobke** [comment]
@danxuliu What problem does it solve? I don't have a particular problem as of now. 🤔

**Comment by danxuliu** [comment]
@MorrisJobke It makes possible, for example, to drag and drop files on touch screens in the Files app, but it may affect other elements either in the server or in apps using jQuery UI features.

If it works fine in your mobile device maybe your browser translates touch events to mouse events or something like that. In that case you can see the problem toggling the touch events in the responsive design mode of Firefox or toggling the device toolbar in the _Developer tools_ of Chromium (although this pull request was created before #7527 was merged, so better rebase onto master before checking it ;-) ).

**Comment by MorrisJobke** [comment]
But now the scrolling is not possible anymore (except ontop of the checkboxes) :/

**Comment by danxuliu** [comment]
>  But now the scrolling is not possible anymore (except ontop of the checkboxes) :/

Ugh, you are totally right.

The drag and drop on touch screens could be changed to be initiated only after a long press on a file, but that would interfere with the common behaviour of showing a context menu with that gesture. Probably it would be better to disable drag and drop of files on touch screens (if support for touch events is added to jQuery UI; if it is not added then nothing needs to be done, as in current master it is implicitly disabled due to touch events not being handled).

Regardless of that adding support for touch events to jQuery UI would be needed at least for Nextcloud Talk to be able to drag the right sidebar to show it on touch screens. I do not know if it could benefit other apps, or if it could cause other problems like the scrolling one :-S So... maybe it would be better to add it directly on each app that needs it?

**Comment by MorrisJobke** [comment]
> So... maybe it would be better to add it directly on each app that needs it?

I would say so. At least I would not add it right now to 13 and blindly backport it.

**Comment by rullzer** [comment]
Ok lets move this out of 13 then.

**Comment by MorrisJobke** [comment]
@danxuliu @rullzer What are the next steps here? I would close this PR and fix it in the apps.

**Comment by danxuliu** [comment]
@MorrisJobke I agree.

**Pull request closed without merging**
