### PR TITLE
Transfer ownership only analyze home storage

### PR DESCRIPTION
**Pull request by rullzer**
From: https://github.com/owncloud/core/pull/26533

When transferring ownership, only the local files will be transferred
during the rename operation. This means that the analyzing code doesn't
need to recurse into any mount points.

Furthermore this fixes issues where FailedStorage might appear as mount
points as a result of inaccessible external storages or shares. So this
makes it more robust.

### CODE REVIEW

**Comment by rullzer** [comment]
CC: @MorrisJobke @nickvergessen @LukasReschke @icewind1991 @schiessle

**Comment by rullzer** [comment]
:+1:

**Comment by icewind1991** [comment]
> // sub-storages have an empty internal path

Is not true

Instead this should use something like `$storage->instanceOfStorage('\OCP\Files\IHomeStorage')` instead

**Comment by rullzer** [comment]
@icewind1991 happy now?

**Comment by nickvergessen** [comment]
Fine by me 👍

**Comment by icewind1991** [comment]
I would be more happy if it was covered by unit tests

**Comment by MorrisJobke** [comment]
> I would be more happy if it was covered by unit tests
 
*commented by "Unittest Icewind"*

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
