### PR TITLE
[stable27] Move deprecation warnings to debug

### PR DESCRIPTION
**Pull request by szaimen**
Manual backport of https://github.com/nextcloud/server/pull/38852 to stable27

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
@skjnldsv looks like the compile command fails?
https://github.com/nextcloud/server/actions/runs/5365075296/jobs/9733658146

**Comment by skjnldsv** [comment]
> @skjnldsv looks like the compile command fails? [nextcloud/server/actions/runs/5365075296/jobs/9733658146](https://github.com/nextcloud/server/actions/runs/5365075296/jobs/9733658146)

Looks like the path is different, I think we need to fix the workflow
https://github.com/nextcloud/.github/blob/4eca92e0661636a7815ad98e4c38c2408f71bef2/workflow-templates/command-compile.yml#L37-L45

**Comment by szaimen** [comment]
Why does it work now?

**Comment by skjnldsv** [comment]
giphy

**Review by nfebe — APPROVED** [review]

**Pull request merged**
