### PR TITLE
Prevent archieved download on secure view

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by davewkzn** [comment]
Hi Nextcloud team.

Thank you for a great product.

Sadly it looks like this bug is back again - simply adding /download in the URL allows a bypass of NextCloud's "Secure view" feature. 
Line 402 of ShareController.php in master and our version (27.0.1) seems to have regressed to:
if (!$this->validateShare($share)) {

Manually applying the following patch resolves the problem:
https://github.com/nextcloud/server/pull/19349/commits/35d4ca4d5de716f874181a15c49773e32e641b22

Please may I ask for this to be investigated?
Many thanks

**Comment by davewkzn** [comment]
Thank you Nick. Correct. I only tested using a single file, and found that adding "/download" then downloads the file.
I should have mentioned that I tested using a PDF file.

**Pull request merged**
