### PR TITLE
Fixed Dashboard widgets height

### PR DESCRIPTION
**Pull request by AndyXheli**
Should fix  NC 25 Dashboard widget is height are off #34582

Signed-off-by: Andy Xheli <axheli@axtsolutions.com>

image

### CODE REVIEW

**Comment by julien-nc** [comment]
I'm fine with this change but I wonder if this could rather be fixed in a cleaner way by removing the top margin of NcEmptyContent.

cc @juliushaertl

**Comment by andyxheli** [comment]
@julien-nc do you mind making a request change ? I'd be happy apply it :)

**Comment by julien-nc** [comment]
@andyxheli I'm refering to a change in https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcEmptyContent/NcEmptyContent.vue

But I'm not sure it's the right thing to do either. I guess the empty content top margin has a purpose.

Any idea about a clean fix for that? @marcoambrosini @jancborchardt @juliushaertl

**Comment by CarlSchwan** [comment]
Alternative fix https://github.com/nextcloud/nextcloud-vue/pull/3372

**Pull request closed without merging**
