### PR TITLE
fix video fullscreen on public page

### LINKED ISSUE #35896: [Bug]: A full screen video in Safari browser of iPhone bacomes blank or tiny size at landscape orientation. (Nextcloud 25)

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/35896

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]
Dang, you're on fire this week !

**Review by max-nextcloud — APPROVED** [review]
Looks good to me.

**Comment by szaimen** [comment]
> Dang, you're on fire this week !

Thanks 😅

**Comment by jdanna** [comment]
FYI This is still broken on iOS mobile devices - the same behavior as before

**Pull request merged**
