### PR TITLE
fix(files_versions): don't call getUid() on null

### LINKED ISSUE #559: Upload incompatible with the file_versions app: Call to a member function getUid() on null
Upload won't work when the "file versions" app is turned on. Disabling the "file versions" app allows the upload to start.

```
# occ backup:point:upload 20230911051503-full-XouUx7Feg6jQZHh                                                                                                                   
- uploading 20230911051503-full-XouUx7Feg6jQZHh to external folders                                                                                                                                         
 - checking external folder 9:caradilnik-cloud-backup                                                                                                                                                       
  > restoring point not found                                                                                                                                                                               
  * Creating Restoring Point on external folder: ok                                                                                                                                                         
  > restoring point created                                                                                                                                                                                 
  * initiating health check                                                                                                                                                                                 
An unhandled exception has been thrown:                                                                                                                                                                     
Error: Call to a member function getUid() on null in /var/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php:361                                                                         
Stack trace:                                                                                          
#0 /var/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php(209): OCA\Files_Versions\Listener\FileEventsListener->getPathForNode()
#1 /var/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php(107): OCA\Files_Versions\Listener\FileEventsListener->write_hook()
#2 /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(86): OCA\Files_Versions\Listener\FileEventsListener->handle()
#3 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\EventDispatcher\ServiceEventListener->__invoke()
#4 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#5 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(94): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#6 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(106): OC\EventDispatcher\EventDispatcher->dispatch()                                                                                  
#7 /var/www/nextcloud/lib/private/Files/Node/HookConnector.php(112): OC\EventDispatcher\EventDispatcher->dispatchTyped()                                                                                    
#8 /var/www/nextcloud/lib/private/legacy/OC_Hook.php(105): OC\Files\Node\HookConnector->write()                                                                                                             
#9 /var/www/nextcloud/lib/private/Files/View.php(1252): OC_Hook::emit()                                                                                                                                     
#10 /var/www/nextcloud/lib/private/Files/View.php(1126): OC\Files\View->runHooks()                                                                                                                          
#11 /var/www/nextcloud/lib/private/Files/View.php(670): OC\Files\View->basicOperation()                                                                                                                     
#12 /var/www/nextcloud/lib/private/Files/Node/File.php(73): OC\Files\View->file_put_contents()                                                                                                              
#13 /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php(223): OC\Files\Node\File->putContent()                                                                                             
#14 /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php(388): OCA\Backup\Service\ExternalFolderService->getRestoringPoint()
#15 /var/www/nextcloud/apps/backup/lib/Service/UploadService.php(318): OCA\Backup\Service\ExternalFolderService->confirmPoint()
#16 /var/www/nextcloud/apps/backup/lib/Service/UploadService.php(178): OCA\Backup\Service\UploadService->uploadToExternalFolder()
#17 /var/www/nextcloud/apps/backup/lib/Command/PointUpload.php(143): OCA\Backup\Service\UploadService->uploadPoint()                                                                                        
#18 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\Backup\Command\PointUpload->execute()                                                                                         
#19 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()                                                                                                         
#20 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()                                                                                                          
#21 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()                                                                                 
#22 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()                                                                                        
#23 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()                                                                                               
#24 /var/www/nextcloud/console.php(100): OC\Console\Application->run()                                                                                                                                      
#25 /var/www/nextcloud/occ(11): require_once('...')                                                   
#26 {main}⏎                                                                                           
```

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/backup/issues/559

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by susnux** [comment]
drone  seems unrelated

**Pull request merged**
