### PR TITLE
enh(a11y): User management settings dialog

### PR DESCRIPTION
**Pull request by Pytal**
- For https://github.com/nextcloud/server/issues/37017

## Summary

| | Screenshot |
--- | ---
**Before** | image
**After** | image image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by JuliaKirschenheuter — CHANGES_REQUESTED** [review]
Thank you @Pytal for extracting modal elements to an extra component and cleaning up!
Unfortunately contrast issue for default theme is still there:

Screenshot from 2023-07-19 10-22-16
Screenshot from 2023-07-19 10-22-09

**Comment by szaimen** [comment]
@JuliaKirschenheuter where is the contrast issue here? I think it looks fine? Can xou explain in words?

**Comment by susnux** [comment]
If it is about the focus state of the settings button, then it should be fixed on the nextcloud-vue library, as this does not introduce any custom styling there.

**Review by kesselb — APPROVED** [review]
Very nice :+1:

**Review by szaimen — APPROVED** [review]
Tested and works but didnt review the code

**Comment by Pytal** [comment]
Referring to the hover state in the second image @JuliaKirschenheuter? As a11y only concerns keyboard focus then I'd say that should be addressed separately with the design team

**Comment by Pytal** [comment]
Feel free to suggest any followups @JuliaKirschenheuter :)

**Pull request merged**
