### PR TITLE
Set file search by certain number of characters in config.php

### PR DESCRIPTION
**Pull request by ghost**
I could not push it to branch, coz "access denied", so i try it this way.

[server/config/config.php](https://github.com/nextcloud/server/blob/master/config/config.php)

```
<?php
$CONFIG = array(
...
    'searchby' => 2, //file search starts after this number of characters is typed
);
```

[server/core/templates/layout.user.php](https://github.com/nextcloud/server/blob/master/core/templates/layout.user.php)

```
<div class="header-right">
				<form class="searchbox" action="#" method="post" role="search" novalidate>
					<label for="searchbox" class="hidden-visually">
						<?php p($l->t('Search'));?>
                        <input id="searchby" type="hidden" value="<?php p(\OC::$server->getConfig()->getSystemValue('searchby')) ?>"> //add this line
					</label>
					<input id="searchbox" type="search" name="query"
						value="" required class="hidden icon-search-white"
						autocomplete="off">
					<button class="icon-close-white" type="reset"><span class="hidden-visually"><?php p($l->t('Reset search'));?></span></button>
				</form>`
```

[server/core/search/js/search.js](https://github.com/nextcloud/server/blob/master/core/search/js/search.js)

```
            /**
             * Search
             */
            this.search = function(event) {
                event.preventDefault();
                var query = document.getElementById('searchbox').value;
                var searchby = document.getElementById('searchby').value;  //add this line
                if (query.length >= searchby) {
                    self.searchCallback(query);
                } else {
                    self.resetCallback();
                }
            };
```

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> I could not push it to branch, coz "access denied", so i try it this way.

You need to create a fork on GitHub to which you then have push access and create a pull request based on. But first of all we should discuss if this is something that should be configurable. Best is to have an issue first where we can collect arguments. We should address the underlying issue and not come up with a solution to something where we don't know why it should be added. Could you describe your use case and your reason to solve it that way? Thanks

**Comment by Studna95** [comment]
Well, at first, thank you for the advice. 

This "solution" is for corporate use. They usually have large amount of files in nextcloud so when they search for some files it freezes and the browser crashes. The reason i solve it this way is that i had no other clue how to do it. I understand it is not the best solution.

**Comment by MorrisJobke** [comment]
> This "solution" is for corporate use. They usually have large amount of files in nextcloud so when they search for some files it freezes and the browser crashes. The reason i solve it this way is that i had no other clue how to do it. I understand it is not the best solution.

Even then it should not freeze. 

If you wish to have this feature implemented by the Nextcloud GmbH or wish further corporate support there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by tomtomas99911** [comment]
I think it is a good function also for personal use. When you have many files in folder you cannot search it effectively - with this function you can. 

Why it cannot be implemented into upstream?

**Comment by MorrisJobke** [comment]
> I think it is a good function also for personal use. When you have many files in folder you cannot search it effectively - with this function you can.
> 
> Why it cannot be implemented into upstream?

The question here is why should we add a "feature" (that we need to maintain) if there are other and better solutions to this. That option also needs to be discovered by users that run into the problems. So it is from our point of view better to improve the default behavior than to add a setting for every input field or menu bar. We - as the Nextcloud project - want an easy to use product that works as good as possible out of the box. Adding settings just hides the problems for some users and most users will not benefit from it. Thus we should look into why it doesn't work for you and improve those use cases for everyone and not only when the setting is properly configured.

**Pull request closed without merging**
