### PR TITLE
Add local cache to redis backend

### PR DESCRIPTION
**Pull request by rullzer**
We often do a lot of identical redis reads. Now redis is fast but still
there is a round trip. Caching the reads makes sure we don't do unneeded
double reads.

Right now it only caches reads and the cache is invalidated upon other
actions.

Future work could mean we also try to cache writes properly. But for now
this should mean we catch the low hanging fruits.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
What about the distributed setup? Is it still save then? The locking is handled natively on redis without this class in between, right?

**Comment by rullzer** [comment]
Ah mmm fuck. yes Let me double check that.

On a somewhat unrelated note. We should probably try to come up with some test setup to verify that.

**Comment by rullzer** [comment]
Ok so, this is probably not the right way. Let me think about just a wrapper or so that we can use this cache just in some places (like the appinfo parser)

**Comment by icewind1991** [comment]
We support setting different local, distributed and locking memcaches for cases like that, appinfo caching etc should be using a local apcu and never touch redis

**Comment by rullzer** [comment]
Ah fuck yes. See this is what I get for reading static code late at night...

**Pull request closed without merging**
