### PR TITLE
Fix log_query config flag

### LINKED ISSUE #28563: Crash with "log_query" infinite loop on NC 22
### Steps

1. Git checkout v22.1.0
2. Set "log_query => 'true'" in config.php
3. Run a search in the web UI

### Expected result
Queries are logged, no errors.

### Actual result
Nothing is logged.
Apache error log says:
```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /srv/www/htdocs/server/lib/private/AppFramework/Utility/SimpleContainer.php on line 138
```

I even tried to raise the allowed memory to 4 GB but it also fails

### Version
NC 22.1.0

### Analysis

If I replace the log statements in QueryBuilder->execute() with `file_put_contents('/tmp/query_log.log', $this->getSQL(), FILE_APPEND);` the logging works fine in the target file.

So I suspect that the call to `$this->logger` might be causing some kind of infinite loop.
I tried also with `\OC::$server->getLogger()` but it also doesn't log anything and crashes.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #28563

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Review by st3iny — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1: ooooh, you found it

**Comment by PVince81** [comment]
`/home/runner/work/_temp/c99534d6-6a0b-4205-9e2e-a5291a6f3534.sh: line 1: phpunit: command not found`

:thinking:

**Comment by PVince81** [comment]
`phpunit 403: rate limit exceeded`

alright... restarting the build

**Comment by ChristophWurst** [comment]
(backporting to 20 just to check something, won't merge due to EOL I know :v:)

**Pull request merged**
