### PR TITLE
Handle invalid ext storage backend to keep mount point visible

### PR DESCRIPTION
**Pull request by MorrisJobke**
Keep mount point visible and also ext storage config visible when
dealing with configs relating to storage backends or auth mechanisms
that were provided by an app that is currently disabled.

Downstream of owncloud/core#26539 

Separate PR because @icewind1991 commented:

> There is an `OC\Files\Storage\FailedStorage` that should probably bne reused instead

To test:

* checkout master at  6e3b8db or something similar
* setup external storage
* change to a master without a external storage or disable the app that provides the class (like the separate FTP external storage app)
* before: broken, because of unknown configuration
* after: working and showing that it is currently not connected - also the admin/user can delete the invalid config

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 Updated as discussed.

**Comment by icewind1991** [comment]
enhanced it to show the failed item in red in the filelist like other invalid external storages

**Review by icewind1991 — APPROVED** [review]
👍 for morris' part

**Comment by MorrisJobke** [comment]
:+1: for @icewind1991's part

**Pull request merged**
