### PR TITLE
Re-open popover on link password save failure

### PR DESCRIPTION
**Pull request by skjnldsv**
After https://github.com/nextcloud/server/pull/17848

Peek 23-12-2019 12-07

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
@gary-kim hum, the edited script is not part of the compiled sources :thinking:

**Comment by gary-kim** [comment]
Oh no, not again

**Comment by skjnldsv** [comment]
@gary-kim maybe the stable17 branch needed compile, let's wait for ci :)

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
Tests fixed, no need to compile pls :p

**Review by gary-kim — APPROVED** [review]

**Comment by rullzer** [comment]
@skjnldsv https://github.com/nextcloud/server/pull/18551 ci disagrees ;)

**Pull request merged**
