### PR TITLE
[stable10] Fix mimetype detection inside hidden folders (#26138) (#2…

### PR DESCRIPTION
**Pull request by LukasReschke**
…6151)

Downstreaming of https://github.com/owncloud/core/pull/26151

Signed-off-by: Lukas Reschke lukas@statuscode.ch

### CODE REVIEW

**Comment by nickvergessen** [comment]
👍

**Comment by MorrisJobke** [comment]
Tested and still works :+1:

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Until 10.0.1 is released

**Review by MorrisJobke — APPROVED** [review]
10.0.1 is tagged

**Pull request merged**
