### PR TITLE
Add new border color variable and adjust primary color for increased contrast

### PR DESCRIPTION
**Pull request by Pytal**
Add a new CSS variable instead of changing the existing ones so developers can explicitly opt-in to using this border color with increased contrast

Dark mode (`--color-border-maxcontrast`): `#646464`
Light mode (`--color-border-maxcontrast`): `#949494`

Also lighten the original primary color slightly `#00639a` → `#006aa3` for increased contrast

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]
Chosen contrast should be fine. Thanks you!

**Comment by Pytal** [comment]
Revert https://github.com/nextcloud/server/pull/35563 must go in first after discussions with @skjnldsv for cleaner git history

**Pull request merged**
