### PR TITLE
Add proper PHPDoc tags to files ApiController

### PR DESCRIPTION
**Pull request by MorrisJobke**
Should make Psalm a bit more happy (because it does not need to infer it)

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Psalm is not happy

**Comment by J0WI** [comment]
`getUser()` may return `null`:
https://github.com/nextcloud/server/blob/f99f463834456984d1e9cede1167f50a829606ee/lib/private/User/Session.php#L227-L229

**Comment by MorrisJobke** [comment]
Rebased - maybe Psalm is happy.

**Comment by MorrisJobke** [comment]
CI failure is unrelated

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by LukasReschke** [comment]
This broke tests on master :(

**Pull request merged**
