### PR TITLE
Respect sharing options when searching using MailPlugin #7428

### LINKED ISSUE #7428: NC12.0.4 - Sharing dialog leaks data with LDAP backend
Sharing dialog leaks data with LDAP backend.

### Steps to reproduce
1. Create some test users (local and in active directory)

image
 
2. Logon with "Test321"-User

image

3. Open share dialog and type "test"

image

### Expected behaviour

test2 (LDAP/AD User) should not be listet, because he is not in the same group...

image

### Sharing options

image

### Actual behaviour

See "Steps to reproduce/3."

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 12.0.4 Build:2017-12-06T01:01:26+00:00 e04dd405161271cccebe922ac53522d1c19914e6

**Updated from an older Nextcloud/ownCloud or fresh install:**  Owncloud --> [..] --> Update NC 11

**Where did you install Nextcloud from:** Nextcloud website / download

**List of activated apps:**
<details>
<summary>App list</summary>

```
 - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_antivirus: 1.1.0
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - music: 0.5.4
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - federation
  - files_external
  - files_versions
  - firstrunwizard
  - nextcloud_announcements
  - survey_client
  - systemtags
  - user_external
```
</details>

**Are you using external storage, if yes which one:** -/-

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

If you need ldap:show-config... just ask, i need to clean it before posting...

### PR DESCRIPTION
**Pull request by LEDfan**
I think I found the problem with #7428, basically when a user `gr2_foo` has set an email address and is in group `gr2` and a user of `gr1` tries to share something `gr2_foo` will show up. This is of course because there is a match based on the email address. However there shouldn't be searched for systemusers using the mail plugin, because there is the UserPlugin.

This can very easily be backported to 12 (I have already pushed a branch) if wanted.

### CODE REVIEW

**Comment by LEDfan** [comment]
Mmm, actually, it seems like my fix isn't 100% correct, because now if you type the full e-mail address the user won't show up....

**Comment by LEDfan** [comment]
I managed to create a better fix. The commit 9d60f7fc643dd48f4c90fcf73b0dcac0a00b4817 is now fixing:

## Steps to reproduce
1. create groups `gr1` and `gr2`, create users `gr1_foo`, `gr1_bar1`, `gr2_foo` and `gr2_bar`, add the users to the corresponding groups
2. add the email `email@email.be` to `gr1_foo` and add the email `abc@abc.be` to `gr2_bar`
3. without changing settings you should now be able to lookup all users and `gr2_bar` and `gr1_foo` by their email addresses
4. enable the option `shareapi_only_share_with_group_members`

## Expected behaviour
1. only users in your own group should show up
2. searching for `abc` or `email` should not popup users from other groups

## Actual behaviour
1. the other users do show up

**Review by blizzz — APPROVED** [review]
code looks good and works

**Comment by blizzz** [comment]
Tests need to be adjusted, though

**Comment by LEDfan** [comment]
@blizzz I fixed the tests and add some test cases for this patch.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
> This can very easily be backported to 12 (I have already pushed a branch) if wanted.

Yes - please open a backport PR.

**Pull request merged**
