### PR TITLE
Check if the X-XSS-Protection header contains the required fields

### PR DESCRIPTION
**Pull request by dpeukert**
As opposed to a simple string comparison, this considers a header containing the [report directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection#Syntax) to be valid.

### CODE REVIEW

**Comment by danielkesselberg** [comment]
Hey @dpeukert welcome to Nextcloud and thank you for your contribution :tada: 

You set X-XSS-Protection to `X-XSS-Protection: 1; mode=block; report=<reporting-uri>` and nextcloud shows a warning for this right? So your pr checks if at least `1; mode=block` is set?

**Comment by danielkesselberg** [comment]
I guess you use the split.map.trim approach to make this work for `1; mode=block` and `1;mode=block`? If so i would recommend something like this `replace(/\s+/g, '')` to remove all whitepace from string first and then use indexOf to assert that `1;mode=block` is present. Anyway your way is fine just my 2 cents :smile:

**Comment by dpeukert** [comment]
Yep. I did it this way because I assumed (there is no official spec for this header AFAIK) that the order of the directives doesn't matter.

**Comment by dpeukert** [comment]
Looks like I broke some tests with this, looking into it now.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by kesselb — APPROVED** [review]
:+1:

**Comment by MorrisJobke** [comment]
@danielkesselberg Feel free to press the big green button, because we have all the checks usually in place. That means if there is a green button you can merge it. only don't merge if there are some comments about further improvements. ;)

**Pull request merged**
