### PR TITLE
Fix translation phpunit test

### PR DESCRIPTION
**Pull request by skjnldsv**
Regression from https://github.com/nextcloud/server/pull/27063

### CODE REVIEW

**Review by Valdnet — APPROVED** [review]

**Comment by LukasReschke** [comment]
:-/

**Comment by skjnldsv** [comment]
> Why do we merge things in which CI fails?

That's called a mistake and we're currently merging pending PRs for release

**Comment by skjnldsv** [comment]
> :-/ - This means another rebase round.

Welcome to my life

**Comment by LukasReschke** [comment]
> That's called a mistake and we're currently merging pending PRs for release

Not blaming you, @skjnldsv. More trying to find solutions as I saw CI red on master several times this week.

Would more hardware help here to process the tests for all PRs faster?

**Comment by skjnldsv** [comment]
> Would more hardware help here to process the tests for all PRs faster?

Maybe :)
Drone is capricious :see_no_evil: 

Moving al lthe phpunit to github action would help make it faster already I think :wink:

**Pull request merged**
