### PR TITLE
[3rdparty] Bump sabre/dav to 3.2.2

### PR DESCRIPTION
**Pull request by rullzer**
Depends on
- [x] https://github.com/nextcloud/3rdparty/pull/40

Lets see what CI thinks

### CODE REVIEW

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Tests need an adjustment :)

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
tags integration tests fail

**Comment by rullzer** [comment]
Tags test pass.

**Comment by rullzer** [comment]
3rdparty merged. Rebased this.

**Review by ChristophWurst — APPROVED** [review]
Apart from three timeouts all tests are green, changes look good, my local instance still seems to work -> LGTM :-)

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
