### PR TITLE
Set proper content type on OCS responses

### PR DESCRIPTION
**Pull request by rullzer**
My bad :see_no_evil: 

CC: @nickvergessen @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
Yay, I can finally share again. Thanks!

:+1:

**Comment by nickvergessen** [comment]
Add a check for the header in the integration test?

**Comment by rullzer** [comment]
Yep will add

**Comment by rullzer** [comment]
@nickvergessen done. I want to extend this a bit in the future but this should catch an error like this at least

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
