### PR TITLE
Proxy server could cache http response when it is not private

### PR DESCRIPTION
**Pull request by kklem0**
Proxy server could cache http response when it is not private
Need this for https://github.com/nextcloud/mail/pull/3071

### CODE REVIEW

**Comment by clementhk** [comment]
See https://www.nginx.com/blog/nginx-caching-guide/

How Does NGINX Determine Whether or Not to Cache Something?

By default, NGINX respects the Cache-Control headers from origin servers. It does not cache responses with Cache-Control set to Private, No-Cache, or No-Store or with Set-Cookie in the response header. NGINX only caches GET and HEAD client requests. You can override these defaults as described in the answers below.

**Comment by clementhk** [comment]
Note that there are situations when proxy caching make sense like avatar, so I'm not 100% sure of this PR if we should just make everything only cache by browser or if we wanna have another function for private caching.

**Comment by rullzer** [comment]
right yes. This was on my list for ages.

So avatars is not a good example. But the endpoints that server bundle js or compiled scss are public of course.

Would you mind adding an optional argument 'public' (set to false by default)?

**Comment by clementhk** [comment]
Don't think the failed tests are related.

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> Don't think the failed tests are related.

https://drone.nextcloud.com/nextcloud/server/28807/10/4

Bildschirmfoto von 2020-05-12 10-31-50

That one is :)

**Comment by ChristophWurst** [comment]
@rullzer backport?

**Comment by clementhk** [comment]
> > Don't think the failed tests are related.
> 
> https://drone.nextcloud.com/nextcloud/server/28807/10/4
> 
> Bildschirmfoto von 2020-05-12 10-31-50
> 
> That one is :)

Missed that, and was looking at the wrong test file.
Thanks!

**Comment by clementhk** [comment]
> @rullzer backport?

Would be cool if it can be backported as I need to use it with the mail app and I'm hoping to ditch my custom code in it.

**Comment by rullzer** [comment]
I'm not 100% sure about the backport. Since it changes the API.

Of course it just adds a parameter which php will happily swallow....

**Comment by ChristophWurst** [comment]
> I'm not 100% sure about the backport. Since it changes the API.

If we don't want to change the API we should backport the default to private caching IMO.

**Comment by clementhk** [comment]
Shall I default to `$public = true` for now?

**Comment by clementhk** [comment]
Shall I default to `$public = true` for now?

**Comment by rullzer** [comment]
Nah leave it to false I'd say. Like in the worst case you don't cache something in the proxy that could be cached in theory.

**Pull request merged**
