### PR TITLE
Fix style of password button on protected link shares

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @nextcloud/designers 

Before:
bildschirmfoto 2018-06-06 um 18 24 37

After:

bildschirmfoto 2018-06-06 um 18 23 45

The little key is from my browser ;)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Seems ok!

**Review by rullzer — APPROVED** [review]
Fine by me

**Comment by MariusBluem** [comment]
For Login (and two factor) we re-introduced a dedicated button. I think this would be a nice idea here too, since this page is often used by people which were never in contact with the Nextcloud UI in the past ... What do you think? Worth open an issue for? @nextcloud/designers

**Comment by MorrisJobke** [comment]
Sounds useful. Also we don’t need to save on space here

**Comment by jancborchardt** [comment]
Yup, separate button below would be fine here, also might look more balanced.

**Pull request merged**
