### PR TITLE
Mailer: discover sendmail path instead of hardcoding it to /usr/sbin/sendmail

### PR DESCRIPTION
**Pull request by flokli**
`sendmail` can very well be in a path different from
`/usr/sbin/sendmail`.

We already search` $PATH` at `lib/private/Settings/Admin/Mail.php` to
detect whether we want to offer sendmail as a mail transfer method, so
let's be consistent and actually initialize `\Swift_SendmailTransport`
with this path to sendmail, instead of just hardcoding
`/usr/sbin/sendmail`.

### CODE REVIEW

**Comment by flokli** [comment]
ping @rullzer @nickvergessen

**Review by kesselb — APPROVED** [review]
Works for me

**Comment by danielkesselberg** [comment]
CI fails
 https://github.com/nextcloud/server/blob/be7db1573dc8c6e7309ec9db124a7a74b8b41199/tests/lib/Mail/MailerTest.php#L51-L59
I'm not sure howto fix this. Apparently there is no sendmail binary on drone. But there should be some warning when `$binaryPath` is empty.

		if ($binaryPath === null) {
			throw new \Swift_TransportException('Could not find sendmail binary');
		}
Something like this could work but test needs to be adjusted.

**Comment by danielkesselberg** [comment]
> I'm not really familiar with PHP tests - but can we, inside that test, mock the call to `\OC_Helper::findBinaryPath` to return a hardcoded path, and assert a `\Swift_SendmailTransport` class pointed to that path being returned?

Yes but the only way i know is to add a method `findBinaryPath` to `Mailer` and call `\OC_Helper::findBinaryPath` inside this method. In TestCase we could mock these method and return a fixed value.

**Review by rullzer — APPROVED** [review]

**Comment by flokli** [comment]
@rullzer Seems like I came away from setting up my phpunit environment to debug tests to not spam this PR ;-)
Thanks a lot for taking over, and looking forward to seeing it in the next release :-)

**Comment by rullzer** [comment]
@flokli thanks you for the PR :) Keep them comming :wink:

**Comment by flokli** [comment]
CI barfed on https://drone.nextcloud.com/nextcloud/server/12302/266 , cancelled. Somebody mind kicking it again?

**Pull request merged**
