### PR TITLE
Fix the SharesPlugin

### PR DESCRIPTION
**Pull request by rullzer**
Another attempt to fix all the typing and handling in the sharesplugin.
In short we should probably have a lot more type hinting in several
places.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
yay https://github.com/nextcloud/server/pull/25881/checks?check_run_id=2014389681

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Comment by nerzhul** [comment]
why should i review that ? i'm not server develop, only app :D can you drop me from such list ? 
thanks

**Comment by nickvergessen** [comment]
Just drop yourself => right sidebar => reviewers => modify and remove yourself

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Pull request merged**
