### PR TITLE
fix(log): remove debug log in _formatRemoteShare, suggested by @maxbes

### PR DESCRIPTION
**Pull request by faust64**
Removes debug log in files_sharing app.
Fix indentation on comment while we're here ...

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

**Comment by faust64** [comment]
checking de Node / build test locally, I can confirm there's a diff in the `apps/files_sharing/js/dist/additionalScripts.js` & `apps/files_sharing/js/dist/additionalScripts.js.map` files -- diff unreadable / some console.error removed in a 17500+ chars line.
Should I add these to that PR, or are those generated by some other script I've missed?

I've been looking at .github/workflows/node.yml: using node 12.13.0, running steps from the build job.

**Comment by rullzer** [comment]
YEah please submit the newly build assets. I have no ieda why the build bot is failing on it

**Pull request merged**
