### PR TITLE
Fix filepicker's add button design

### PR DESCRIPTION
**Pull request by skjnldsv**
@nextcloud/designers 

| Before | After |
|:---------:|:------:|
|Capture d’écran_2019-03-22_10-36-45|Capture d’écran_2019-03-22_10-36-36|

### CODE REVIEW

**Comment by ChristophWurst** [comment]
- [ ] BUG the popover is slightly misplaced

Bildschirmfoto von 2019-03-22 10-41-24

**Comment by MorrisJobke** [comment]
* [ ] bug: clicking the "->" results in `ReferenceError: Can't find variable: Files`

Bildschirmfoto 2019-03-22 um 11 45 28

**Comment by MorrisJobke** [comment]
Why is there the add button at all? In 15 there was no such button. Couldn't it be removed?

**Comment by ChristophWurst** [comment]
> Why is there the add button at all? In 15 there was no such button. Couldn't it be removed?

I was wondering as well. I guess we need it for copy and move. When you literally *pick a file* it doesn't make sense to have this button.

**Comment by skjnldsv** [comment]
I have no idea X)

**Comment by MorrisJobke** [comment]
Could this PR hides the button, so that it works like before?

**Comment by skjnldsv** [comment]
Sure!

**Comment by skjnldsv** [comment]
Ah nope! This was a feature: https://github.com/nextcloud/server/pull/13177
Approved by Jan!

**Comment by ChristophWurst** [comment]
> Approved by Jan!

:see_no_evil: :speak_no_evil: :hear_no_evil:

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/pull/14806#issuecomment-475573547 <- this is still broken 😉 (on the personal settings page)

**Comment by ChristophWurst** [comment]
cc'ing the original author @rummatee for help

**Comment by MorrisJobke** [comment]
> [#14806 (comment)](https://github.com/nextcloud/server/pull/14806#issuecomment-475573547) <- this is still broken 😉 (on the personal settings page)

Anyway - was broken before as well -> let's merge this first fix.

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Extracted issue to #14834

**Pull request merged**
