### PR TITLE
chore(ci): Force github CI for tests failing on self-hosted runners

### PR DESCRIPTION
**Pull request by come-nc**
## Summary

2 jobs are always failing on self hosted runners, so for now force them on github CI to avoid false-negative.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by come-nc** [comment]
smb-kerberos-sso is flaky on github CI as well, it failed :cry:

**Comment by come-nc** [comment]
For `php8.3-s3` it works.

**Review by nickvergessen — APPROVED** [review]

**Comment by come-nc** [comment]
@susnux I see you have pushed things to docker-ci, what is your take on this, should we merge it? Or is there a better solution?

**Comment by susnux** [comment]
> I see you have pushed things to docker-ci, what is your take on this, should we merge it? Or is there a better solution?

Nothing related to this. So probably we need this until someone can figure out whats up with kerberos

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
Kerberos still failing?

https://github.com/nextcloud/server/actions/runs/7712512770/job/21024244130

**Comment by susnux** [comment]
But only for PHP8.3 I see this errors, so there might be a real issue with our code?

**Comment by nickvergessen** [comment]
> But only for PHP8.3 I see this errors, so there might be a real issue with our code?

unknown, I forwarded this internally and an engineer of the team will be assigned to investigate if we can disable it safely or if a work item needs to be scheduled

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/server/pull/43296

**Pull request merged**
