### PR TITLE
[Stable10] Nextcloud is being updated. Not ownCloud

### LINKED ISSUE #948: Update to Nextcloud 10 RC1 shows ownCloud 10 RC1
I think there is any issue/pr about that already, but i could not find it here 😁 ...or is it a bug with the german translation?!

owncloud_instead_of_nextcloud

cc @MorrisJobke @LukasReschke

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #948

Easy one

CC: @mar1u5 @nickvergessen @MorrisJobke @blizzz @LukasReschke

### CODE REVIEW

**Comment by mar1u5** [comment]
:+1:

**Comment by blizzz** [comment]
LGTM

**Comment by nickvergessen** [comment]
master?

**Comment by rullzer** [comment]
Already in master by a commit from @jancborchardt that changed the general update page I believe.

**Comment by jancborchardt** [comment]
Yup. Must have forgotten to backport that since the rest wasn’t backported. Thanks! :)

**Pull request merged**
