### PR TITLE
fix(theming): replace standard generic package icon by material design

### PR DESCRIPTION
**Pull request by skjnldsv**
From https://github.com/nextcloud/server/issues/42517

Considering we have replaced the office icons and other filetypes are the standard grey color, ket's replace that old `#0082c9` Nextcloud blue by the same `#969696` grey.
I also used that opportunity to update the icon from the material design, like it was done with others in the last months.

| Before | After |
|:---------:|:------:|
|||

cc @nextcloud/designers

### CODE REVIEW

**Review by marcoambrosini — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
BTW if the icon has `#0082c9` as color then it will be automatically themed using the current primary color (see IconController).
But for this I think package in grey is better

**Comment by skjnldsv** [comment]
yeah, I think we need to discuss what we really want to do with the theming mime colour api. I'm not sure this is really relevant anymore :thinking:

**Comment by skjnldsv** [comment]
Discussion: https://github.com/nextcloud/server/issues/45579

**Pull request merged**
