### PR TITLE
25.0.2 RC1

### PR DESCRIPTION
**Pull request by blizzz**
* #34577
* #34862
* #34905
* #34921
* #34922
* #34925
* #34928
* #34944
* #34946
* #34953
* #34955
* #34964
* #34978
* #34998
* #35010
* #35011
* #35023
* #35034
* #35035
* #35048
* #35058
* #35060
* #35064
* #35078
* #35082
* #35085
* #35086
* #35099
* #35117
* #35118
* #35130
* #35133
* #35135
* #35137
* #35161
* #35164
* #35166
* #35172
* #35174
* #35180
* #35183
* #35188
* #35190
* #35191
* #35199
* #35214
* #35216
* #35220
* #35232
* #35233
* #35235
* #35237
* #35255
* #35256
* #35261
* #35265
* #35291
* #35298
* #35312
* #35322
* #35326
* #35327
* #35330
* #35335
* #35338
* #35340
* #35346
* #35354
* #35366
* #35375
* #35377
* #35382
* #35390
* #35394
* #35404
* #35408
* #35411
* #35414
* #35415
* nextcloud/3rdparty#1217
* nextcloud/3rdparty#1227
* nextcloud/3rdparty#1229
* nextcloud/activity#1001
* nextcloud/activity#1003
* nextcloud/activity#1015
* nextcloud/activity#1017
* nextcloud/bruteforcesettings#420
* nextcloud/circles#1203
* nextcloud/files_pdfviewer#681
* nextcloud/firstrunwizard#752
* nextcloud/firstrunwizard#780
* nextcloud/firstrunwizard#784
* nextcloud/logreader#817
* nextcloud/nextcloud_announcements#136
* nextcloud/notifications#1355
* nextcloud/notifications#1366
* nextcloud/notifications#1368
* nextcloud/notifications#1369
* nextcloud/notifications#1373
* nextcloud/notifications#1377
* nextcloud/password_policy#410
* nextcloud/password_policy#411
* nextcloud/photos#1443
* nextcloud/photos#1449
* nextcloud/photos#1460
* nextcloud/photos#1482
* nextcloud/photos#1493
* nextcloud/photos#1495
* nextcloud/privacy#814
* nextcloud/privacy#817
* nextcloud/privacy#822
* nextcloud/related_resources#132
* nextcloud/related_resources#133
* nextcloud/related_resources#135
* nextcloud/related_resources#138
* nextcloud/related_resources#145
* nextcloud/text#3314
* nextcloud/text#3323
* nextcloud/text#3337
* nextcloud/text#3338
* nextcloud/text#3343
* nextcloud/text#3355
* nextcloud/text#3359
* nextcloud/text#3371
* nextcloud/text#3377
* nextcloud/text#3383
* nextcloud/text#3385
* nextcloud/text#3386
* nextcloud/text#3395
* nextcloud/text#3397
* nextcloud/text#3406
* nextcloud/text#3409
* nextcloud/text#3412
* nextcloud/text#3415
* nextcloud/text#3416
* nextcloud/text#3420
* nextcloud/text#3426
* nextcloud/text#3431
* nextcloud/text#3433
* nextcloud/text#3437
* nextcloud/text#3439
* nextcloud/text#3440
* nextcloud/text#3447
* nextcloud/text#3455
* nextcloud/text#3456
* nextcloud/text#3463
* nextcloud/text#3466
* nextcloud/text#3468
* nextcloud/text#3471
* nextcloud/text#3479
* nextcloud/text#3480
* nextcloud/text#3481
* nextcloud/text#3485
* nextcloud/twofactor_totp#1301
* nextcloud/viewer#1452
* nextcloud/viewer#1454
* nextcloud/viewer#1459
* nextcloud/viewer#1460
* nextcloud/viewer#1463
* nextcloud/viewer#1468
* nextcloud/viewer#1471
* nextcloud/viewer#1476
* nextcloud/viewer#1479

Pending PRs:

* [ ] #35412 @ChristophWurst

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
Would be really great to get this in before the rc: https://github.com/nextcloud/server/pull/35350

**Comment by blizzz** [comment]
> Would be really great to get this in and backported before the rc: #35350

I see it in 25.0.3 rather tbh

**Comment by szaimen** [comment]
> I see it in 25.0.3 rather tbh

It is almost complete: https://github.com/nextcloud/server/pull/35375

**Comment by blizzz** [comment]
> > I see it in 25.0.3 rather tbh
> 
> It is almost complete: #35375

:four_leaf_clover:

**Pull request merged**
