### PR TITLE
fix(deps)!: Upgrade symfony/event-dispatcher to supported version 5.4.26

### PR DESCRIPTION
**Pull request by nickvergessen**
## Summary

- [x] https://github.com/nextcloud/server/pull/38545
- [x] https://github.com/nextcloud/server/pull/39086
- [x] https://github.com/nextcloud/server/pull/39190
- [x] https://github.com/nextcloud/server/pull/39304
- [x] https://github.com/nextcloud/server/pull/39305
- [x] https://github.com/nextcloud/server/pull/39485
- [x] https://github.com/nextcloud/server/pull/39487
- [x] https://github.com/nextcloud/server/pull/39571
- [x] https://github.com/nextcloud/server/pull/39595
- [x] https://github.com/nextcloud/server/pull/39605

## TODO

- [x] https://github.com/nextcloud/3rdparty/pull/1423

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
There are hundreds of psalm errors now because our legacy SymfonyAdapter claims to be a `Symfony\Component\EventDispatcher\EventDispatcherInterface` and it's typed in all kind of places like that, but at the same time the order change Symfony announced.

I see 2 ways forward at the moment:
1. Swap the order of the event and eventName everywhere and continue
    * breaks only emitting code, so apps are only affected when they create events, not when they listen to events
2. move to typed events
    * breaks listening apps too

**Comment by ChristophWurst** [comment]
> here are hundreds of psalm errors now because our legacy SymfonyAdapter claims to be a `Symfony\Component\EventDispatcher\EventDispatcherInterface` and it's typed in all kind of places like that, but at the same time the order change Symfony announced.

Deprecated in 20 and was never a public API. I'm fine dropping it and only maintaining the OCP dispatcher with 28+

Ref https://github.com/nextcloud/server/pull/21848

**Review by Altahrim — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:poodle:

**Review by kesselb — APPROVED** [review]
Nice :clap:

**Comment by nickvergessen** [comment]
Rebasing to see if the failing acceptance tests are linked or temporary

**Pull request merged**
