### PR TITLE
Adjust wording to make the separation between sharing and files more clear

### PR DESCRIPTION
**Pull request by nickvergessen**
@jancborchardt @karlitschek as discussed

### CODE REVIEW

**Comment by karlitschek** [comment]
awesome 👍

**Comment by jancborchardt** [comment]
Cool :+1:  can you also fix the missing files-dark icon?

**Comment by nickvergessen** [comment]
Its already here locally, not sure why it is missing for you.

**Comment by nickvergessen** [comment]
Merging

**Comment by jancborchardt** [comment]
Works now after I changed to the right branch ;D thanks

**Pull request merged**
