### PR TITLE
Login: Implements the "user disabled" message like the "wrong password" message

### LINKED ISSUE #9978: Login as deactivated user shows an error
### Steps to reproduce
1. add an user account
2. deactivate this user
3. try login for this user on web interface

### Expected behaviour
* The same behaviour as login with wrong user name **or**
* the same behaviour as login with wrong password. 

### Actual behaviour
* Login with wrong password will work as expected.
* Login with right password will show an error "user disabled". No login fields displayed. Page reload in web-browser does also not display login screen.

I suspect for privacy reasons login for an deactivated user should work as login for an non existent user. 

### Server configuration

**Nextcloud version:** 13.0.4.0

### PR DESCRIPTION
**Pull request by weeman1337**
It now looks like the password message:
image

closes #9978

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested, works and the code looks good 👍

**Comment by MorrisJobke** [comment]
@weeman1337 Thanks for this nice PR. The code looks nice. If you are up for some other tasks you could have a look at the "good first issues" ones https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

beside that feel free to join the IRC channel #nextcloud-dev for developer related chat. ;)

**Comment by danxuliu** [comment]
I amended the commit with the acceptance tests to just fix some indentation and to set the same password for the disabled user as for the other user (consistency nitpicking ;-) ). Otherwise really nice @weeman1337, thanks a lot!

**Review by skjnldsv — APPROVED** [review]

**Comment by weeman1337** [comment]
> fix some indentation

@skjnldsv does that mean the 80 chars limit from the dev docs "is adjustable"? :)

**Comment by danxuliu** [comment]
@weeman1337 
>  does that mean the 80 chars limit from the dev docs "is adjustable"? :)

Oh, please, you add unit tests, acceptance tests... and even read and try to abide by the dev docs? I am going to cry with joy ;-)

Anyway, as Hector Barbossa would tell you :-P , _the 80 char limit is more what you would call a guideline than an actual rule_. Of course better to stick to it as much as possible, but it is one of those things that can be not respected in favour of better legibility or consistency.

**Pull request merged**
