### PR TITLE
Add trashbin:restore occ command

### LINKED ISSUE #18921: [Feature Request] php occ trashbin:restore
Hey there!

I am dealing with customers, who sometimes delete files on their Nextcloud in huge quantities by accident. Restoring thousands of files through the webgui is pretty tedious. I know, you can select all files, but still it doesn't work clean for so many files, since it brings the web interface to it's limit (in my experience).

Now my suggestions would be to add a command line option to solve this easier in the future. Personally I'd add the option restore to the existing php occ trashbin command. Some useful arguments to define would probably be usernames to locate the correct trashbin and a verbose option.

Thanks for your work.

Best regards,
Tim

### LINKED ISSUE #20781: Add occ command to restore files from trashbin
### Problem
A user deletes files in a shared folder. But does not respond to "Please restore the files"-request.
Since the files have been deleted via sync app at the other users too there is no copy left.
### Expected Feature
An admin / the user who's share the files belong to can restore them via the deleted files app.
### Solution
For admins and/or share owners there should be an option to restore any file / any file which belonged to one of their shares to the original location / with the original access rights.
Deleted files should be sortable by the user who deleted them.
For a configurable period an admin should be able to restore even files removed from the user's trash bin.

### PR DESCRIPTION
**Pull request by cahogan**
Adds feature requested in #18921 and #20781 to allow trashed file restoration with occ.

Close https://github.com/nextcloud/server/issues/18921
Close https://github.com/nextcloud/server/issues/20781

### CODE REVIEW

**Comment by cahogan** [comment]
Hi @szaimen, noticed that you were looking for someone to implement this feature. I've used the command as presented to restore files, but still have to add tests. However, if you have feedback on the current work I would appreciate it as well.

**Comment by szaimen** [comment]
Hey, thank you very much for creating this PR and sry for the late answer!

**Comment by icewind1991** [comment]
rebased, fixed code style issues and changed output to be a bit more concise

**Review by icewind1991 — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by cahogan** [comment]
I think this will also potentially:
Close #30074

**Comment by szaimen** [comment]
Looks like this is ready to go?

**Comment by Grunthos** [comment]
Looking forward to this going live, but would be nice if it had the option if restoring a specific file based on path or id.

**Comment by cahogan** [comment]
@Grunthos I think it would be fairly easy to add that in an inelegant way -- restoreDeletedFiles already handles the individual files it restores by $filename, so you could accept an optional input list of filenames to restore, then check for membership. I am sure there is a faster and better way to accomplish this, though.

@szaimen as far as I am concerned yes :)

**Comment by Grunthos** [comment]
@cahogan I was just thinking of something based on internal object IDs from the database; in many cases where accidental deletions have occurred they are pretty easy to find.

**Comment by szaimen** [comment]
I rebased manually.

**Comment by szaimen** [comment]
I think the failures are unrelated.
cc @PVince81 if we can merge this

**Comment by PVince81** [comment]
@cahogan can you update the documentation as well ? https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html?highlight=occ#trashbin-label

the repo is here: https://github.com/nextcloud/documentation/tree/master/admin_manual/configuration_server

**Comment by PVince81** [comment]
@cahogan ping, can you add the docs as per my previous comment ?
let me know if you can't so someone else can take care.
thanks!

**Comment by allinappli** [comment]
seems the documentation is not yet updated: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#trashbin

**Comment by PVince81** [comment]
https://github.com/nextcloud/documentation/pull/9521

**Comment by cahogan** [comment]
Hi all, my apologies -- I didn't receive notifications from this thread. Thank you very much for adding documentation -- is there any additional info that I could help with at this point, or is the PR complete?

**Comment by PVince81** [comment]
@cahogan it is complete now. thanks!

**Pull request merged**
