### PR TITLE
[stable29] fix(Token): add FILESYSTEM scope with SCOPE_SKIP_PASSWORD_VALIDATION

### PR DESCRIPTION
**Pull request by blizzz**
backport of #46071

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by solracsf** [comment]
Will this land on very-next minor versions (actually RCs)?

**Review by juliusknorr — APPROVED** [review]

**Comment by blizzz** [comment]
> Will this land on very-next minor versions (actually RCs)?

Will go right into todays finals :crossed_fingers: :four_leaf_clover:

**Pull request merged**
