### PR TITLE
UI updates for global search

### PR DESCRIPTION
**Pull request by nfebe**
- Use standard font of filter tags/chips
- No bold
- Use close icon and no close thick

https://github.com/nextcloud/server/issues/41651

### CODE REVIEW

**Comment by Fenn-CS** [comment]
| Before | After |
---------- | --------
| Screenshot from 2023-11-27 23-46-54 | Screenshot from 2023-11-27 23-44-55 |
| Screenshot from 2023-11-27 23-47-16 | Screenshot from 2023-11-27 23-45-09 |

@nimishavijay

**Review by artonge — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by blizzz** [comment]
likely will not backport because of the compiled assets. if they were in a separate commit, only those can be picked with the source changes.

**Pull request merged**
