### PR TITLE
[Stable16] Fix mobile vertical scrolling

### PR DESCRIPTION
**Pull request by skjnldsv**
Backport of #15462

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by skjnldsv** [comment]
For some reasons it changed some compiled files in settings :man_shrugging:

**Comment by MorrisJobke** [comment]
> [@skjnldsv](/skjnldsv) [skjnldsv](/skjnldsv) changed the base branch from master  to stable16  [2 hours ago](#event-2329813890)

This causes CI to fail :/

**Review by rullzer — APPROVED** [review]
:elephant:

**Comment by kesselb** [comment]
Looks like the node_modules are wrong. Try `npm ci` and build the assets again?

**Comment by MorrisJobke** [comment]
> Looks like the node_modules are wrong. Try `npm ci` and build the assets again?

Could also that another PR didn't updated it, or am I wrong here?

**Comment by ChristophWurst** [comment]
> For some reasons it changed some compiled files in settings man_shrugging

Do you have `node_modules` inside `settings`? If so -> :fire:

**Comment by skjnldsv** [comment]
> Do you have `node_modules` inside `settings`? If so ->

That was it! :tada:

**Pull request merged**
