### PR TITLE
Populate the mention-notification with the actual message

### PR DESCRIPTION
**Pull request by nickvergessen**
Write a comment where you mention a user on a shared file.
The notification so far only says you where mentioned.
Now it includes the text of the comment (as plain text).
With https://github.com/nextcloud/notifications/pull/190 it will also be parsed and the mentions should be clickable (if there where more than your own).

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:rocket: 

Quick smoke tests looks awesome

**Review by blizzz — COMMENTED** [review]
I did not include the whole message initially to avoid leaking content wherever it may show up. It seems to be the state of the art across apps though, to display it immediately. 

In itself it looks good. However, the notifications app itself does not seem to pull notifications (git master), I never see anything… thus, cannot really smoke test. The `prepare()` method is not being entered either.

**Review by blizzz — APPROVED** [review]
~~However, the notifications app itself does not seem to pull notifications (git master), I never see anything… thus, cannot really smoke test. The prepare() method is not being entered either.~~ Another make build-js was missing… works!

**Comment by juliushaertl** [comment]
@blizzz Maybe a bit to early, unit tests are failing on master:

https://drone.nextcloud.com/nextcloud/server/12138

**Comment by blizzz** [comment]
damn, scrolled to far and waived it off as unrelated noise :(

**Comment by blizzz** [comment]
Let me have a quick look about adjusting those tests, as they don't seem to be fundamentally broken

**Comment by blizzz** [comment]
take a few minutes more, I add a reverting PR. Sorry for the mess.

**Comment by blizzz** [comment]
@nickvergessen can you reopen with adjusted tests, please?

**Pull request merged**
