### PR TITLE
[master] Port Same-Site Cookies to master

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/nextcloud/server/issues/50

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:boom:

```
PHP Fatal error:  Class 'OC\Appframework\Middleware\Security\Exceptions\StrictCookieMissingException' not found in /drone/src/github.com/nextcloud/server/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php on line 141
[info] build failed (exit code 255)
```

**Comment by LukasReschke** [comment]
> PHP Fatal error:  Class 'OC\Appframework\Middleware\Security\Exceptions\StrictCookieMissingException' not found in /drone/src/github.com/nextcloud/server/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php on line 141
[info] build failed (exit code 255)

How much I love case-sensitive and case-insensitive OS…

**Comment by LukasReschke** [comment]
Casing changed. Let's see if Drone is happy now… Tests are passing locally… (well they also passed before but 🙈 yay … computers 😉 )

**Comment by rullzer** [comment]
:+1:

**Comment by LukasReschke** [comment]
Since it's a simple port to master: Merge.

**Pull request merged**
