### PR TITLE
Explicitly name node tests workflow

### PR DESCRIPTION
**Pull request by Pytal**
See title 👆

### CODE REVIEW

**Comment by MichaIng** [comment]
Great, so it can be better distinguished from the build/webpack tests. I wonder whether it's beneficial to rename the latter as well to express this more explicitly?

**Review by MichaIng — APPROVED** [review]

**Comment by Pytal** [comment]
> Great, so it can be better distinguished from the build/webpack tests. I wonder whether it's beneficial to rename the latter as well to express this more explicitly?

Good idea, feel free to open a PR :)

**Comment by MichaIng** [comment]
Done: #30121

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
Oh no :(
That was actually on purpose. You can agregate the same tests under the same test sute name.

All of those are node workflows, so they all end up in the same group.
Now we have duplicate wording like 
image

Please also note those names are the same across Nextcloud, so changing one here is just gonna be confusing. See the template at https://github.com/nextcloud/.github/blob/master/workflow-templates/node.yml

**Comment by skjnldsv** [comment]
Reverted in https://github.com/nextcloud/server/pull/30126

**Pull request merged**
