### PR TITLE
Update doctrine

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/3rdparty/pull/32, Ref OC#26946

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Basic smoke testing went fine and the changes look fine too 👍

**Review by blizzz — APPROVED** [review]
Did some successful smoke testing,  too. Quickly went through changes, looked OK.

**Comment by nickvergessen** [comment]
Merged 3rdparty and updated this with the new commit-id

**Comment by MorrisJobke** [comment]
Rebase to fix the conflict.

**Pull request merged**
