### PR TITLE
Add workflowengine to check-code call

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @rullzer @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by mar1u5** [comment]
LGTM. When will the other Apps follow (according to #235)?

**Comment by MorrisJobke** [comment]
> LGTM. When will the other Apps follow (according to #235)?

When they are actually compatible 🙈

**Comment by mar1u5** [comment]
We want to port this to `stable10`, right?

**Comment by nickvergessen** [comment]
Added to 602

**Pull request merged**
