### PR TITLE
We are working on 13 now!

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Happy app upgrading ;) ... we should start to make apps "multi version" to avoid this weird thing. Every app in the app store should ideally only have one version that works for all server versions.

**Review by ChristophWurst — APPROVED** [review]
🚀

**Comment by rullzer** [comment]
@MorrisJobke well that is just not feasible. As apps might depend on new stuff etc. And our team and ecosystem is not large enough the have API versions etc.

**Comment by nickvergessen** [comment]
Let me continue this and fix all the app requirements as promised

**Comment by nickvergessen** [comment]
## Stable12 target adjusted
- [ ] https://github.com/nextcloud/activity/pull/158
- [ ] https://github.com/nextcloud/quota_warning/pull/5
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/31
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/63
- [ ] https://github.com/nextcloud/user_saml/pull/110
- [ ] https://github.com/nextcloud/survey_client/pull/57
- [ ] https://github.com/nextcloud/templateeditor/pull/21
- [ ] https://github.com/nextcloud/serverinfo/pull/91
- [ ] https://github.com/nextcloud/password_policy/pull/46
- [ ] https://github.com/nextcloud/notifications/pull/84
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/26
- [ ] https://github.com/nextcloud/firstrunwizard/pull/40
- [ ] https://github.com/nextcloud/files_texteditor/pull/36
- [ ] https://github.com/nextcloud/files_retention/pull/32
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/31
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/18
- [ ] https://github.com/nextcloud/files_antivirus/pull/28
- [ ] https://github.com/nextcloud/admin_notifications/pull/11

Would be nice to merge this PR, so my master PRs to require 13 are passing on all the apps.

**Review by ArtificialOwl — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
