### PR TITLE
Remove transparent top

### LINKED ISSUE #33949: header transparent
See 
image

### PR DESCRIPTION
**Pull request by CarlSchwan**
Replace 3px of absolute positioning with top padding.

Fix #33949

### CODE REVIEW

**Review by szaimen — CHANGES_REQUESTED** [review]
I fear this doesnt close the issue completely (have look at the screenshot: the background color below that gap is still transparent)

**Comment by CarlSchwan** [comment]
> I fear this doesnt close the issue completely (have look at the screenshot: the background color below that gap is still transparent)

But I think this is a design decision from before the UI redesign, since this is using the same backdrop-filter blur settings we also use in the profile page and left sidebars

**Comment by szaimen** [comment]
> But I think this is a design decision from before the UI redesign, since this is using the same backdrop-filter blur settings we also use in the profile page and left sidebars

okay, but we should fix this, no?

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
