### PR TITLE
Let memory limit set in tests fit the used amount

### PR DESCRIPTION
**Pull request by juliusknorr**
With the recent bump of the php8.0 container it seems that setting a memory limit smaller than the currently used amount of memory is throwing an error in the tests. This PR makes sure that the values we use for testing fits with what is used by running the full testsuite in phpunit.

Should make the nodb tests pass again.

For some background it seems that https://github.com/php/php-src/commit/1b3b5c94e52d10eb7a3f69b486a51b3f4d214d4f introduced a warning for that case while fixing a bug and phpunit is letting the tests fail due to the convertWarningsToExceptions="true" default. However with the php upstream fix the tests would also no longer have passed as the previous memory limit value would have been kept then.

### CODE REVIEW

**Review by julien-nc — APPROVED** [review]
Didn't try it but seems :heavy_check_mark: to me

**Comment by juliushaertl** [comment]
Backports to stable20 as it might also occur with php-7.4.21 or later

**Review by Pytal — APPROVED** [review]

**Pull request merged**
