### PR TITLE
[stable27] Correctly switch/revert from custom to bundled perms

### PR DESCRIPTION
**Pull request by blizzz**
backport of #40434

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Review by AndyScherzinger — APPROVED** [review]

**Comment by blizzz** [comment]
now waiting for the compiled assets :bricks: :spades:

**Comment by blizzz** [comment]
build failed:

Screenshot_20230915_154501

That's does not seem to be an issue with the code, rather with the action?

**Comment by blizzz** [comment]
@Fenn-CS could you compile and push?

**Comment by blizzz** [comment]
second attempt succeeded

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
