### PR TITLE
fix(files): Right click menu offset and list scrolled glitch

### LINKED ISSUE #43300: [Bug]: NC 28.0.2 Context menu in "files" app does not work at all
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When clicking a file in the "files" app, the context menu opens and the closes immediately again, so you can not use it.

### Steps to reproduce

1. Open a the "files" app
2. Click a file entry with the right mouse button
3. See that the context menu opens and closes again

### Expected behavior

The context menu works as expected (as in NC 28.0.1).

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #43842: [Bug]: Right click menu wrong position
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dear Community, since NC 28 (first in release channel and now the latest beta 28.0.3 RC2) the right click menu is on a wrong position:

click

### Steps to reproduce

1. Login to Nextcloud instance.
2. Open file view.
3. Right click on a file or folder.
4. Menu is shown with a large distance to the courser.

### Expected behavior

Right click menu should be shown on the position of the courser / mouse.

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #44123: files app - if scrolling down and right-clicking, the view jumps to the top and opens the menu there
Just tested on nc29.0.0b1

files app - if scrolling down and right-clicking, the view jumps to the top and opens the menu there

https://github.com/nextcloud/server/assets/42591237/050df38c-a7dd-48ce-ab66-7c26b7835895

### PR DESCRIPTION
**Pull request by Pytal**
- Fix https://github.com/nextcloud/server/issues/43842
- Fix https://github.com/nextcloud/server/issues/43300
- Fix https://github.com/nextcloud/server/issues/44123
- Supersede https://github.com/nextcloud/server/pull/43254

## Summary

Before | After
--- | ---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by Pytal** [comment]
> While it works now when scrolled, the position is now off :-(. Is this part missing from the previous PR?

Had another look through git history and it turns out that the menu is supposed to open to the bottom-left of the cursor, fixed!

**Comment by SystemKeeper** [comment]
Much better now! Only thing I noticed is an offset issue when the menu opens to the top:

https://github.com/nextcloud/server/assets/1580193/8d748d99-068b-4d52-a991-02f72336d726

**Review by SystemKeeper — APPROVED** [review]
As discussed, works fine in the tested scenarios. A small mis-alignment can still happen if the menu is rerendered with less items than before, but nothing to adjust for this PR.

**Pull request merged**
