### PR TITLE
Fixed Logo not showing with 'accessability' themes

### LINKED ISSUE #26578: [Accessibility][Dark theme] Invalid logo.svg URL is tried to be loaded
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Disable Theming app
2. Enable Accessibility app
3. Enable Dark theme

### Expected behaviour
The default Nextcloud logo from `/core/img/logo/logo.svg` is loaded and shown.

### Actual behaviour
`/apps/accessibility/css/../img/logo/logo.svg?v=1` is tried to be loaded, which does not exist, hence no logo is shown.

### Server configuration

**Operating system:** Debian Bullseye

**Web server:** Apache/2.4.46

**Database:** MariaDB v10.5.9

**PHP version:** v7.4.15

**Nextcloud version:** v21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 21.0.0

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - apporder: 0.12.0
  - calendar: 2.2.0
  - cloud_federation_api: 1.4.0
  - contacts: 3.5.1
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_rightclick: 1.0.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - impersonate: 1.8.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - notify_push: 0.1.7
  - oauth2: 1.9.0
  - photos: 1.3.0
  - previewgenerator: 3.1.1
  - provisioning_api: 1.11.0
  - ransomware_protection: 1.10.0
  - settings: 1.3.0
  - spreed: 11.1.2
  - survey_client: 1.9.0
  - tasks: 0.13.6
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - comments
  - contactsinteraction
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_sharing
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - password_policy
  - privacy
  - recommendations
  - serverinfo
  - sharebymail
  - support
  - systemtags
  - text
  - theming
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "logtimezone": "Europe\/Berlin",
        "default_phone_region": "DE",
        "filesystem_check_changes": 0,
        "hashingThreads": 4,
        "hashingMemoryCost": 16384,
        "hashingTimeCost": 3,
        "trashbin_retention_obligation": "disabled",
        "versions_retention_obligation": "disabled",
        "skeletondirectory": "",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/my.domain.org\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "knowledgebaseenabled": false,
        "mysql.utf8mb4": true,
        "updater.release.channel": "beta",
        "tempdirectory": "\/mnt\/sda\/ncdata\/tmp",
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "jpeg_quality": 60,
        "app_install_overwrite": [
            "apporder",
            "calendar",
            "impersonate",
            "ransomware_protection",
            "contacts",
            "spreed"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera 77.0.4023.0

**Operating system:** Windows 10 20H2

#### Web server error log
None

#### Nextcloud log (data/nextcloud.log)
None

#### Browser log
Nothing aside of a million messages about deprecated `$` and jQuery in general. Not sure if it's possible to mute those messages, which are coming from the jQuery migration scripts, AFAIK, but they make debugging via browser console, especially for inexperienced users, a nightmare.

### PR DESCRIPTION
**Pull request by fuchsi3010**
hack-y (?) fix for #26578
fixed the relative path to the img directory in the accessability .scss files.
i'm not sure if this is the best way to fix this, please refer to the discussion at the issue.

I tested the fix with the dark theme on my nextcloud instance running Nextcloud 21.0.1 on docker.
I did not test with the other themes.

### CODE REVIEW

**Comment by fuchsi3010** [comment]
the DCO check didn't go through, i hope i fixed it now

**Comment by MichaIng** [comment]
Many thanks for opening the PR. I verified that the overrides need to be done in all four style sheets, as enabling any of the accessibility flags (dark mode, high contrast, dyslexia font) alone or in combination is changing the style variable to point to a `logo.svg` inside the accessibility app directory.

Did you or could you test whether using the theming app to change the logo, in combination with an accessibility flag, still works?

And yes, it is a bit hacky without knowing the underlying idea/concept behind these (logo) variables, why the style root directory is changed at all by the theming app and whether this can be done more selectively for the shipped style sheets only in the first place etc. But it works.

**Comment by fuchsi3010** [comment]
> Did you or could you test whether using the theming app to change the logo, in combination with an accessibility flag, still works?

I tested on my Nextcloud 21.0.1 (docker), with a PNG and a SVG image for the logo in the theming app, and they both worked with my modified dark theme from the accessability app.

**Comment by MichaIng** [comment]
Okay, let's run the static tests. I can only confirm that it is working like that, but since it looks more like a symptom-side fix, John (the app maintainer) should have a look whether there is a fix possible that grabs the issue by its root 🙂.

**Comment by skjnldsv** [comment]
Tests are saying no

**Comment by MichaIng** [comment]
Psalm errors are unrelated to this PR. I triggered a rerun of the Lint checks, as they only show "GitHub Actions has encountered an internal error when running your job.". Not sure if probably the logs have been removed in the meantime, so we need to review faster?

**Comment by MichaIng** [comment]
@skjnldsv 
Tests are now saying yes 🙂. Can you have a look?

It's actually quite similar to https://github.com/nextcloud/server/commit/f1f113c5232f6c191a431140624b0fe4e44770ce, where as well an asset path is manually overwritten to use a core asset. Not sure whether `!default` makes sense.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
> /rebase

This is from a fork. @fuchsi3010 would you mind to rebase this commit onto the current master?

**Review by Pytal — APPROVED** [review]

**Comment by fuchsi3010** [comment]
hi,
ad @MichaIng:  i wanted to remove the '!default' for a while and took the opportunity to do it now. 
the '!default' doesnt seem to have an effect, i think i copied it from the 'main' CSS file and worked from there.
sorry for the late change.

ad rebase: I'm a git noob, this is what i did:
```
mkdir src && cd src
git clone git@github.com:fuchsi3010/server.git
git checkout -b css-reroute
```
then i made the changes (first time around i edited straight to fuchsi3010/server master branch)
**note**: i did edit dark.scss, highcontrast.scss and fontdyslexic.scss, but highcontrastdark.scss can remain unchanged.
with this, _all the different combinations of accessibility themes work_ in my Nextcloud 22.1.1 stable on docker.
```
git commit -a
git checkout master
git pull git@github.com:nextcloud/server.git
git checkout css-reroute
git rebase master
git checkout master
git push
```

i hope i did everything alright, thanks for your patience! :-)

**Comment by fuchsi3010** [comment]
ok that didn't work as intended :-( made the changes again and pushed, seems ok now.
also noticed i could have fetched changes from the github web-gui... oops.

**Comment by MichaIng** [comment]
I think the fix is missing now for the `highcontrastdark.scss` which is still the only single CSS used when selecting high contrast as well as dark mode in accessibility, isn't it?

I do rebase like that:
```sh
git remote add upstream 'https://github.com/nextcloud/server.git'
git fetch upstream
git rebase upstream/master
git commit --amend --no-edit # Currently not sure if this is even required
git push -f origin HEAD
```
But your way worked as well, while generally you should be able to skip merging thinks between `css-reroute` and `master` branch and use your local `master` branch only?

**Comment by fuchsi3010** [comment]
Any way i try it (resetting cache, private mode, different browser, server restart) i can't get the logo to disappear, with dark & highcontrast enabled in the Accessability App.
In a 'minimalist' approach to this hack-y fix, i would suggest the least amount of changes necessary to reach the result.
Can anybody reproduce the missing logo with the current changes?

@MichaIng Thanks the detailed reply! I thought, maybe it would be easier if all of 'my' changes were on a single branch... but i guess rebasing scraps that anyway? i'll do a bit more reading-up on git when i get the time :-)

**Comment by MichaIng** [comment]
This is strange, I wonder if [this](https://github.com/nextcloud/server/commit/ede5db1) changed the behaviour that the combined high contrast and dark mode is not used anymore. On the other hand it should only have an effect on guests (no logged in user) and only sets `OCA.Accessibility.theme` while `OCA.Accessibility.highcontrast` remains the same. Here is the code responsible to selecting the `highcontrastdark` CSS: https://github.com/nextcloud/server/blob/215aef3/apps/accessibility/lib/Controller/AccessibilityController.php#L119-L126
I haven't tried to understand how those are connected 😅.

Can you verify that when you select high contrast and dark mode, that the `--color-main-text` variable is set to `#fff`, like here:

theme

In my case it's `#d8d8d8` from dark mode only, in case of high contrast only it's `#000`. So this is a reliable way to check which SCSS has been used 😄. If high contrast + dark mode indeed shows `--color-main-text: #000`, then the expected CSS was loaded, but then the icon should be currently broken without the fix being applied to `highcontrastdark.scss`.

**Comment by fuchsi3010** [comment]
i have both dark + highcontrast enabled and `--color-main-text` is `#FFF`
image
(this is firefox developer tools, not sure what you are using?)

how would one choose the theme without logging in? is it a browser setting?

**Comment by MichaIng** [comment]
Okay so the correct CSS is loaded, and the logo is still present? The variables should then actually still point to the invalid path with high contrast + dark theme 🤔.

**Comment by fuchsi3010** [comment]
ok, i checked both `dark` and `highcontrast` checkboxes, reloaded the page.
filtering for `logo.svg?v=1`, network monitor in firefox devtools shows me `200` and `GET`,  so i conclude it was not cached.
Request Headers:
```
GET /core/img/logo/logo.svg?v=1 HTTP/2
Host: [REDACTED]
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0
Accept: image/webp,*/*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=fuchsi3010; nc_token=[REDACTED]; oc_sessionPassphrase=[REDACTED]
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Cache-Control: max-age=0
TE: trailers
```
Response Headers:
```
HTTP/2 200 OK
accept-ranges: bytes
cache-control: max-age=15778463
content-type: image/svg+xml
date: Mon, 20 Sep 2021 13:06:22 GMT
etag: "141-5cad15803bb26"
last-modified: Tue, 31 Aug 2021 02:02:37 GMT
referrer-policy: no-referrer
server: Apache/2.4.48 (Debian)
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
content-length: 321
X-Firefox-Spdy: h2
```
the inspector shows:
```
:root {
    --color-main-text: #fff;
```
so i think it loads the correct one?

as i said, my approach would be: this is a hacky fix, so i want to make as little changes as necessary.
anything i tried with the current changes **could not yield a missing logo** on NC 22.1.1 .

but if you want me to add the lines to `highcontrastdark.scss` i'll do it right away. 
just say your preference please, whatever is easiest to close this PR finally.

**Comment by MichaIng** [comment]
Strange, then probably all three (or two) of these CSS are loaded now or they are merged in the first place. If it works, it works 🙂.

Yes it is hacky somehow, but there are other such hacky things in these stylesheets. It is generally not clean that these accessibility themes are treated as themes but are in fact no complete themes. Internally the variables are set as if all required theme files were present, but they are not. Best would be a native way to have the variables changed only for shipped files and else fall back to core assets automatically.

**Pull request merged**
