### PR TITLE
[14] Fixes the move/copy picker buttons

### PR DESCRIPTION
**Pull request by weeman1337**
see  #11524

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Backport of #11522

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Fixes also #11315

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
Thanks a lot @weeman1337! :tada:

**Pull request merged**
