### PR TITLE
Fix tense in email

### LINKED ISSUE #16119: Share By Mail Spelling Mistake
### Steps to reproduce
1. Share file with Email with Password being sent to the Sender first
2. Receive Email including the password to view the file
3. Email body should use the word "sent" instead of "send" in this section "The share was already send to the recipient." 

### Expected behaviour
The email body should say "sent"

### Actual behaviour
The email body says "send"

### PR DESCRIPTION
**Pull request by wernerfred**
Change send to sent in the following line:
>
https://github.com/nextcloud/server/blob/d9df34158f0556867181d957360b582e08d4731d/apps/sharebymail/lib/ShareByMailProvider.php#L590

and adapt all l10n files that contained the sentences appropriate

This PR closes #16119 if accepted

### CODE REVIEW

**Comment by kesselb** [comment]
Thank you :tada: 

Translations are managed with transifex (https://www.transifex.com/nextcloud/nextcloud/) and synced daily to this repository. Could you please revert the l10n files?

**Review by gary-kim — APPROVED** [review]
Looks good to me!
Maybe squash the commits but otherwise, no other issues.

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
