### PR TITLE
Add mysql job to CI

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Woot

```
1) Test\DB\ConnectionTest::testSetValuesOverWrite
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_table` (`integerfield`, `textfield`) VALUES(?, ?)' with params [1, "bar"]:

SQLSTATE[HY000]: General error: 1364 Field 'clobfield' doesn't have a default value

/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
/drone/src/github.com/nextcloud/server/lib/private/DB/Connection.php:209
/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/drone/src/github.com/nextcloud/server/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/drone/src/github.com/nextcloud/server/lib/private/DB/Connection.php:280
/drone/src/github.com/nextcloud/server/tests/lib/DB/ConnectionTest.php:135
```

https://github.com/nextcloud/server/blob/94ad54ec9b96d41a614fbbad4a97b34c41a6901f/tests/lib/DB/ConnectionTest.php#L122-L138

**Comment by MorrisJobke** [comment]
How could that ever have been working -.-

**Comment by MorrisJobke** [comment]
I have no idea why there is an insert instead of an update triggered.

**Comment by MorrisJobke** [comment]
I just tested this with master@{2016-06-01} and it is also there broken. Somehow not an `ConstraintViolationException` is thrown but a `DriverException` that is not catched.

**Comment by MorrisJobke** [comment]
Whaat?

```
1) Test\Files\Cache\CacheTest::testFolder with data set #2 ('😐, NEUTRAL_FACE, UTF-8 hex F09F9890')
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`size`,`mtime`,`mimepart`,`mimetype`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [100, 50, "1", "2", "729b662513f13a316202fb5b7f62a62a", "\ud83d\ude10, NEUTRAL_FACE, UTF-8 hex F09F9890", -1, "\ud83d\ude10, NEUTRAL_FACE, UTF-8 hex F09F9890", "25", "25", "729b662513f13a316202fb5b7f62a62a"]:

SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x90, ...' for column 'path' at row 1

/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:116
/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
/drone/src/github.com/nextcloud/server/lib/private/DB/Connection.php:209
/drone/src/github.com/nextcloud/server/lib/private/DB/Adapter.php:113
/drone/src/github.com/nextcloud/server/lib/private/DB/Connection.php:247
/drone/src/github.com/nextcloud/server/lib/private/Files/Cache/Cache.php:265
/drone/src/github.com/nextcloud/server/lib/private/Files/Cache/Cache.php:220
/drone/src/github.com/nextcloud/server/tests/lib/Files/Cache/CacheTest.php:118

Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x90, ...' for column 'path' at row 1

/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:989
/drone/src/github.com/nextcloud/server/lib/private/DB/Connection.php:209
/drone/src/github.com/nextcloud/server/lib/private/DB/Adapter.php:113
/drone/src/github.com/nextcloud/server/lib/private/DB/Connection.php:247
/drone/src/github.com/nextcloud/server/lib/private/Files/Cache/Cache.php:265
/drone/src/github.com/nextcloud/server/lib/private/Files/Cache/Cache.php:220
/drone/src/github.com/nextcloud/server/tests/lib/Files/Cache/CacheTest.php:118

Caused by
PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x90, ...' for column 'path' at row 1

/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
/drone/src/github.com/nextcloud/server/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:989
/drone/src/github.com/nextcloud/server/lib/private/DB/Connection.php:209
/drone/src/github.com/nextcloud/server/lib/private/DB/Adapter.php:113
/drone/src/github.com/nextcloud/server/lib/private/DB/Connection.php:247
/drone/src/github.com/nextcloud/server/lib/private/Files/Cache/Cache.php:265
/drone/src/github.com/nextcloud/server/lib/private/Files/Cache/Cache.php:220
/drone/src/github.com/nextcloud/server/tests/lib/Files/Cache/CacheTest.php:118
```

**Comment by LukasReschke** [comment]
LGTM, let's get in some more testing.

**Comment by MorrisJobke** [comment]
👍 (as this is administrative only)

**Pull request merged**
