### PR TITLE
LDAP Group Backend optimizations

### PR DESCRIPTION
**Pull request by blizzz**
In some test scenarios I reduced page loading of users page over ~~20%~~ 40% (with 4k of groups), and OCS calls to fetch user details ~~10% down~~ stagnate (also with 4k groups). Extreme cases of course, but the changes make sense either way. In the end, it is also very individual, depending on the config and setup.

### CODE REVIEW

**Comment by rullzer** [comment]
@blizzz 19?

**Review by skjnldsv — APPROVED** [review]
:elephant:

**Review by rullzer — APPROVED** [review]
:elephant: your call @blizzz

**Comment by blizzz** [comment]
> elephant your call @blizzz

Aye! Lemme adjust the formatting commit for the remaining stuff the csfixer is complaining about and then merge

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Comment by skjnldsv** [comment]
Failures seems unrelated

**Pull request merged**
