### PR TITLE
allow grouping of activity settings

### PR DESCRIPTION
**Pull request by icewind1991**
Allow apps to group their activity settings, includes a group for "Files" as example

settings frontend here: https://github.com/nextcloud/activity/pull/477

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
That's how it looks like:

Bildschirmfoto 2020-08-05 um 22 26 05


cc @jancborchardt

**Review by rullzer — APPROVED** [review]

**Review by jancborchardt — DISMISSED** [review]
Regarding the wording, the spec says this:

> - Specific settings section "Notifications", not called "Activity" (All the settings go to Notifications, Activity has none as there you can filter in the interface)
> - Each setting has checkmarks for "Mail" and "Push" – and you can of course also leave both unchecked

Any specific reason why the wording is not like that?

**Comment by icewind1991** [comment]
Adjusted the wording,

not that the wording/merging/etc of the individual items are not in the scope of the PR and will be changed separately

**Comment by MorrisJobke** [comment]
Now looks like this:

Bildschirmfoto 2020-08-11 um 11 22 30

**Review by MorrisJobke — APPROVED** [review]

**Comment by nickvergessen** [comment]
regression:


1) Test\Activity\ManagerTest::testGetConsumers
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

2) Test\Activity\ManagerTest::testGetConsumersInvalidConsumer
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

3) Test\Activity\ManagerTest::testGetUserFromTokenThrowInvalidToken with data set #0 (null, array())
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

4) Test\Activity\ManagerTest::testGetUserFromTokenThrowInvalidToken with data set #1 ('', array())
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

5) Test\Activity\ManagerTest::testGetUserFromTokenThrowInvalidToken with data set #2 ('12345678901234567890123456789', array())
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

6) Test\Activity\ManagerTest::testGetUserFromTokenThrowInvalidToken with data set #3 ('1234567890123456789012345678901', array())
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

7) Test\Activity\ManagerTest::testGetUserFromTokenThrowInvalidToken with data set #4 ('123456789012345678901234567890', array())
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

8) Test\Activity\ManagerTest::testGetUserFromTokenThrowInvalidToken with data set #5 ('123456789012345678901234567890', array('user1', 'user2'))
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

9) Test\Activity\ManagerTest::testGetUserFromToken with data set #0 (null, '123456789012345678901234567890', 'user1')
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

10) Test\Activity\ManagerTest::testGetUserFromToken with data set #1 ('user2', null, 'user2')
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

11) Test\Activity\ManagerTest::testGetUserFromToken with data set #2 ('user2', '123456789012345678901234567890', 'user2')
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

12) Test\Activity\ManagerTest::testPublishExceptionNoApp
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

13) Test\Activity\ManagerTest::testPublishExceptionNoType
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

14) Test\Activity\ManagerTest::testPublishExceptionNoAffectedUser
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

15) Test\Activity\ManagerTest::testPublishExceptionNoSubject
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

16) Test\Activity\ManagerTest::testPublish with data set #0 (null, '')
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

17) Test\Activity\ManagerTest::testPublish with data set #1 ('test_author', 'test_author')
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

18) Test\Activity\ManagerTest::testPublishAllManually
Cannot stub or mock class or interface "Test\Activity\IL10N" which does not exist

**Pull request merged**
