### PR TITLE
feat: add option to disable scanner transactions

### PR DESCRIPTION
**Pull request by icewind1991**
I'm not a 100% sure about the full impact of disabling this regarding performance/deadlocks/etc. But having a config flag for this makes it easier to figure out the impact.

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by nfebe — APPROVED** [review]
Add `filescanner_no_transactions` to sample config?

**Comment by icewind1991** [comment]
> Add filescanner_no_transactions to sample config?

Given the uncertainty around the effects I think it's better not to advertise this at the moment. Instead I would rather change the behavior for everyone once we've done more testing around this.

**Comment by icewind1991** [comment]
stable27: https://github.com/nextcloud/server/pull/45681

**Pull request merged**
