### PR TITLE
[stable27] fix(files_sharing): Create passwords when enforced for mail shares

### PR DESCRIPTION
**Pull request by susnux**
## Summary

Currently when trying to create a mail share there are a lot of errors in the browser console + if passwords are enforced mail shares will not work as the password is not set correctly.
This fixes some TypeErrors that prevent the password from being set.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nfebe — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Comment by susnux** [comment]
drone unrelated. cc @sorbaugh

**Review by emoral435 — APPROVED** [review]

**Pull request merged**
