### PR TITLE
Add liberapay

### PR DESCRIPTION
**Pull request by skjnldsv**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@jancborchardt I think I remember that there was a problem with liberapay, as it could not be connected to an org account, but only to single users?

**Comment by jospoortvliet** [comment]
yeah, who runs this, where does the money go... Note that we don't use donations for GmbH development but ofc perhaps we can save it up for a pizza round at the conference ;-)

**Comment by skjnldsv** [comment]
@jospoortvliet or put the money back into bountysource

**Comment by thibaultamartin** [comment]
@skjnldsv so far it appears that bountysource is mostly enriching the company behind it. It doesn’t look like many bounties were delivered.

If there actually is a high demand for donation, maybe a sister company working only on home-user features could work? I know hiring people is time consuming and pretty hard though :)

**Comment by skjnldsv** [comment]
> working only on home-user features

We do both here, any specific areas you seems we're lacking presence?

**Comment by thibaultamartin** [comment]
Yes you do, and as a home-user I’m more than satisfied with Nextcloud, thanks for the great work :)

I was thinking of more advanced features that are not a priority such as
* Sorting photos by EXIF date (already planned for NC19)
* Polishing Live Photo display (already works with File Viewer but not quite there with Gallery)
* Creating albums à la Apple Photos to share with family members
* Helping migrate components to Vue, as home-users tend to be a lot more picky regarding UI and design

**Comment by skjnldsv** [comment]
Thanks :)
Keep in mind that polishing and fixing bugs are more a priority than features too ;)

**Comment by jospoortvliet** [comment]
I don't think there is a high interest in donations - at least not on the scale that it could pay a salary, let alone multiple. That's why I'm happy with Bountysource - yes, they take a cut, but only when money is paid out to a contributor, so that's fine with me. Until then it gets moved around. If Liberapay could go into bountysource that's ok with me, I suppose. But right now, I don't know where it goes, so let's not promote it please until we know who is receiving this money ;-)

**Comment by skjnldsv** [comment]
Let's close then?

**Comment by skjnldsv** [comment]
Maybe we should disable the liberapay account then @jospoortvliet

**Comment by jospoortvliet** [comment]
@skjnldsv well again, I don't know who owns the account, who made it etc. Might be a random person in Australia who is taking the money right now... Until we know that, we shouldn't even consider promoting it, of course.

**Comment by jospoortvliet** [comment]
@jancborchardt can decide, as far as I'm concerned. I'm perfectly fine if he uses the donations for a round of pizza during a contributor week..

**Pull request closed without merging**
