### PR TITLE
Fix app nav img margin

### LINKED ISSUE #6622: Settings menu layout is broken
on current master:
bildschirmfoto vom 2017-09-23 11-06-12

Seems to be related to #6399

@nextcloud/designers @skjnldsv

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #6622
@nextcloud/designers

### CODE REVIEW

**Comment by juliushaertl** [comment]
@skjnldsv  Also happens to be an issue without an image, see the app management: 

bildschirmfoto vom 2017-09-23 14-30-02

**Comment by skjnldsv** [comment]
@juliushaertl This is @jancborchardt's will. He wants users to be 'forced' to have some icons! :)

**Comment by juliushaertl** [comment]
Ah ok, is there already an issue for the parts missing an icon in the server repo?

**Comment by skjnldsv** [comment]
You mean in the apps management section?

**Comment by skjnldsv** [comment]
@nextcloud/designers please review :)

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@skjnldsv Yes. Found it https://github.com/nextcloud/server/issues/3987

**Review by rullzer — APPROVED** [review]

**Comment by jancborchardt** [comment]
@skjnldsv see, it pushes us to add icons ;)

**Comment by skjnldsv** [comment]
@jancborchardt well done fine sir! You tricked me well! 😱😱

**Pull request merged**
