### PR TITLE
Fix .hidden class specificity, should not be overridable, ref #12138

### PR DESCRIPTION
**Pull request by jancborchardt**
Follow-up fix to https://github.com/nextcloud/server/pull/12138 as described by @pixelipo 

Please review @nextcloud/designers @violoncelloch :)

### CODE REVIEW

**Review by pixelipo — APPROVED** [review]
I'm approving based only on the code-review. I haven't tested this in real life, but the code makes sense

**Review by violoncelloCH — APPROVED** [review]
works, however only tested locally in browser...
will need to create a dev setup... will probably try out https://github.com/jancborchardt/nextcloud-scripts/blob/master/nextcloud-setup.sh as soon as I'll get some spare time for it...

**Comment by violoncelloch** [comment]
as @te-online brought in the idea of `display: inline-block`, maybe you could take a look at this too?

**Review by skjnldsv — APPROVED** [review]
You're too fast for me 😂😉
🚀

**Comment by jancborchardt** [comment]
@violoncelloch @pixelipo @kevgathuku @te-online @nextcloud/designers btw, it’s off-topic but we have an upcoming **hackweek in Stuttgart, November 26-30!** :smiley: Everyone is welcome, and for contributors like you there’s 80% travel/lodging support as usual! :tada: There will be a blog post the next few days with more info, but for now please mark your calendar, and hope to see you there! :heart:

**Comment by te-online** [comment]
> You're too fast for me 😂😉

For me too 😅

**Comment by rullzer** [comment]
This broke the generation of apptokens in the webui.

1. Go to your security settings
2. Try to generate an apptokens
3. Do not see your actual new apptoken.

**Comment by juliushaertl** [comment]
This broke also the popover menu in files sharing. Probably hidden items, that use some jquery code to show it. Maybe we should revert this and do the change in a less invasive way.

**Pull request merged**
