### PR TITLE
Sharee API GS fixes

### PR DESCRIPTION
**Pull request by rullzer**

### CODE REVIEW

**Comment by skjnldsv** [comment]
@rullzer I did the front, but there is one thing that was used that is not compliant to your new config:

https://github.com/nextcloud/server/blob/39d55623c3571cf5ed3c23b14ef70c0e534b5fa8/apps/files_sharing/lib/Controller/ShareesAPIController.php#L222

**Comment by rullzer** [comment]
> @rullzer I did the front, but there is one thing that was used that is not compliant to your new config:
> 
> https://github.com/nextcloud/server/blob/39d55623c3571cf5ed3c23b14ef70c0e534b5fa8/apps/files_sharing/lib/Controller/ShareesAPIController.php#L96
> 
> https://github.com/nextcloud/server/blob/39d55623c3571cf5ed3c23b14ef70c0e534b5fa8/apps/files_sharing/lib/Controller/ShareesAPIController.php#L222

right. Let me fix that. Thanks for the work.

**Review by ChristophWurst — APPROVED** [review]
Looks good!

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Rebased

**Comment by skjnldsv** [comment]
@rullzer one more test to make sure everything is how you wanted?

**Comment by rullzer** [comment]
Fixed the tests.

@skjnldsv it does what it should do it hink. What I find weird is that when you press search globally that the dropdown vanishes and you don't get proper feedback 'no results found'  or something. But lets get this in and fix that later..

**Review by juliusknorr — APPROVED** [review]
Looks good :+1:

**Comment by rullzer** [comment]
We should backport the functinality to 17 and 16 (maybe even 15) but will require manual work.

**Pull request merged**
