### PR TITLE
Prevent XSS in links which open a new browser window

### PR DESCRIPTION
**Pull request by staabm**
see https://twitter.com/iammerrick/status/914988292637990912

### CODE REVIEW

**Comment by staabm** [comment]
not sure why some of the checks are faillin but it looks unrelated.

**Comment by MariusBluem** [comment]
@LukasReschke

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Note that this isn't really an XSS vulnerability but rather allows the opened page to change window.opener.location.

In this specific case, `noreferrer` has the same impact  since window.opener.location is also set to null. See https://mathiasbynens.github.io/rel-noopener/ for an example.

That said, the change looks good but please don't change the translations manually. This may cause problems with our Transifex sync. So just the changes to the templates and I'd :+1:  this :) 

Thanks!

**Comment by staabm** [comment]
removed the l10n changes

**Comment by staabm** [comment]
@LukasReschke ping

**Review by LukasReschke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Pull request merged**
