### PR TITLE
Moving between storages is not a rename

### PR DESCRIPTION
**Pull request by rullzer**
For https://github.com/nextcloud/server/issues/16419
Based on https://github.com/nextcloud/server/pull/16696

### CODE REVIEW

**Comment by rullzer** [comment]
Master is Nextcloud 22 now.
If this should go into 21 it should be backported.

**Comment by PVince81** [comment]
@icewind1991 since you've been working on copy recently, any hints on this ?

**Comment by PVince81** [comment]
I've tested the steps above **without** this PR and moving worked file and the file can be downloaded properly.
So either I'm missing some details about the env or the problem has disappeared recently on master (2a632195365be77889428e85801a00c74ab6a836)

**Comment by PVince81** [comment]
also works on v20.0.10 without patching.

note: I've created the users on the CLI and made sure to login as them before sharing, just in case. Not sure if the test case implies that the target users did NOT log in and might not be fully initialized.

**Comment by PVince81** [comment]
aha, I jumped back in time to a commit close to the date of this PR: v21.0.0beta7 (without the PR applied)
here I am able to reproduce the problem, and the "encrypted" version of "foo.txt" is 0 in the target, even though the file is encrypted

**Comment by PVince81** [comment]
so one theory is that this fix is not really needed any more, but would be good to know what other code path has fixed the issue

**Comment by PVince81** [comment]
closing as obsolete

**Pull request closed without merging**
