### PR TITLE
add enable flag to occ app:install

### LINKED ISSUE #5834: Add --enable trigger to app:install command
As discussed in https://github.com/nextcloud/server/pull/5644 it would be nice with a `--enable` trigger so that you can install the app in just one command instead of two.

### PR DESCRIPTION
**Pull request by sualko**
cc @enoch85 

fix #5834

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks a lot! Unfortunately I don't have the time to test right now.

**Comment by nickvergessen** [comment]
In my opinion it should default to enable and have a `--keep-disabled` option instead...
I guess in most cases people want to enable what they just installed?

**Comment by enoch85** [comment]
> In my opinion it should default to enable and have a --keep-disabled option instead... I guess in most cases people want to enable what they just installed?


I agree with @nickvergessen

Would it be possible @sualko?

**Comment by enoch85** [comment]
@sualko Any update here?

@nickvergessen Do you think you could take over if @sualko "has left the building"?

**Comment by sualko** [comment]
@enoch85 here you go

**Comment by enoch85** [comment]
@nickvergessen I know nothing about the tests, but now we have the desired function at least.

@sualko Thank you very much!

**Review by nickvergessen — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Rebased on current master.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
