### PR TITLE
User is not found when is searched by name and one of surnames #7510

### PR DESCRIPTION
**Pull request by fgsl**

### CODE REVIEW

**Review by blizzz — CHANGES_REQUESTED** [review]
it fundamentally changes the behaviour of the method, breaking current way of finding records

**Comment by ChristophWurst** [comment]
Closing as the proposed change seems to be rejected by the code owner and there were no updated since.

**Comment by ChristophWurst** [comment]
@fgsl I would suggest to discuss the implementation at https://github.com/nextcloud/server/issues/7510 and submit a new pull request :)

**Comment by fgsl** [comment]
Right! I will do it.

Em Seg, 28 de jan de 2019 14:34, Christoph Wurst <notifications@github.com
escreveu:

**Pull request closed without merging**
