### PR TITLE
Revert "Fix table view"

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
This reverts commit cb852ef6

* Resolves regression of https://github.com/nextcloud/server/issues/38245

"Manager" column was wrong implemented, you can see it via editing rows:

Screenshot from 2023-05-25 11-55-12

**But this is not a regression of cb852ef6**

## Summary

| Before | After |
|--------|--------|
| Screenshot from 2023-05-24 17-41-23 | Screenshot from 2023-05-25 11-52-23 |

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by szaimen** [comment]
> there were added some things like "manager" column

I see. shouldnt we keep the manager column?

**Comment by ChristophWurst** [comment]
I still see the manager code. @szaimen could you please give this a test? thanks

**Review by szaimen — APPROVED** [review]
seems to work fine in my smoke testing

**Review by ChristophWurst — APPROVED** [review]
:+1: Looks gut

**Pull request merged**
