### PR TITLE
fix(userstatus): set user status to 'In a meeting' if calendar is busy

### LINKED ISSUE #31177: Set user status to busy when own calendar contains busy event
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Is your feature request related to a problem? Please describe.
Availability status seems not to be synced with Nextcloud Calendar like Microsoft Outlook with Teams.

### Describe the solution you'd like
When a "busy" event is in progress in Nextcloud Agenda, set availability status in Talk as "busy" or "to not disturb" and eventually share informations about the event in progress as status message (in option).

### Describe alternatives you've considered**
Microsoft does the same with Outlook and Teams/Skype for Business. If a calendar event is in progress with "busy" status, Teams status is "busy" or "in a meeting". If an event is "out of office", Teams status is "out of office".

Nextcloud is an open source and very powerful alternative to GAFAM, so it would be very interesting, in my opinion.

## Work packages

- [ ] Status automation
- [ ] User documentation
- [ ] Admin documentation (if any)

### Follow up
- https://github.com/nextcloud/server/issues/40760

### PR DESCRIPTION
**Pull request by miaulalala**
* Fixes: https://github.com/nextcloud/server/issues/31177

## Summary

A calendar query looks at the calendar to see if there are any events. TRANSPARENT calendars are ignored.

We ignore events if they're
- an OOO calendar event as that status is already handled
- a TRANSPARENT event
- an event that started before the user has set a custom status

We also do not overwrite a "DND" or "INVISIBLE" status or the Talk "In a Call" message.

## How to test

- For OOO: set an OOO period and see that the OOO status stays persistent and is not overwritten by the calendar automation
- For calendar events: set an event in your calendar. Wait until it begins and wait until after it ends, status should be set to "In a meeting" and reset after. I use 5 / 10 minute events to test.
- For transparent calendar events - the same, see that the staus DOES NOT change to "In a meeting"
- For all day events, the status should stay "In a meeting" at all times unless overwritten by a custom status and should not revert back
- Overwriting with a custom status: See "In a meeting" status, set a custom status, reload. See that custom status still exists until next event.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Review by hamza221 — APPROVED** [review]

**Comment by miaulalala** [comment]
Documentation: https://github.com/nextcloud/documentation/pull/11405

**Comment by skjnldsv** [comment]
Please get this in asap if needed for 28.0.1

**Comment by miaulalala** [comment]
Drone failure down to checkers, ran `bash build/autoloadchecker.sh` and ` git restore **/installed.php` as per @nickvergessen but no changes to commit.

**Pull request merged**
