### PR TITLE
30.0.0 RC1

### PR DESCRIPTION
**Pull request by skjnldsv**
- Scheduled for the 14th of August :warning: 
- This will result in a BRANCH-OFF

## Required:
- [x] https://github.com/nextcloud/text/pull/6200

## Merged:
* #46987
* #47135
* #47147
* #47149
* #47152
* #47153
* #47157
* #47177
* #47188
* nextcloud/bruteforcesettings#629
* nextcloud/bruteforcesettings#630
* nextcloud/files_downloadlimit#345
* nextcloud/files_downloadlimit#346
* nextcloud/files_pdfviewer#1006
* nextcloud/files_pdfviewer#1010
* nextcloud/firstrunwizard#1305
* nextcloud/firstrunwizard#1307
* nextcloud/logreader#1328
* nextcloud/logreader#1331
* nextcloud/logreader#1335
* nextcloud/nextcloud_announcements#371
* nextcloud/notifications#1973
* nextcloud/notifications#2000
* nextcloud/password_policy#633
* nextcloud/serverinfo#656
* nextcloud/serverinfo#658
* nextcloud/viewer#2392
* nextcloud/viewer#2414

## Pending PRs:
* @a-bran
  * [ ] #42352
* @abangtor
  * [ ] #25300
* @Abijeet
  * [ ] nextcloud/logreader#476
* @adriano-pinaffo
  * [ ] nextcloud/photos#1834
* @ahmadsaadkhan
  * [ ] #44188
* @akhil1508
  * [ ] #35867
  * [ ] #37328
  * [ ] #42039
  * [ ] nextcloud/activity#1635
* @aleixq
  * [ ] #37896
* @alpapan
  * [ ] #35701
* @Antreesy
  * [ ] nextcloud/logreader#1338
  * [ ] nextcloud/notifications#1998
* @arnowelzel
  * [ ] #42497
* @ArtificialOwl
  * [ ] #32827
  * [ ] #35526
  * [ ] #39134
  * [ ] #39957
  * [ ] #41478
  * [ ] #41743
  * [ ] #44371
  * [ ] #45979
  * [ ] nextcloud/circles#1089
  * [ ] nextcloud/circles#1090
  * [ ] nextcloud/circles#1148
  * [ ] nextcloud/circles#1214
  * [ ] nextcloud/circles#1217
  * [ ] nextcloud/circles#1394
  * [ ] nextcloud/circles#891
  * [ ] nextcloud/circles#980
* @artonge
  * [ ] #46218
* @arublov
  * [ ] #43366
  * [ ] #43512
* @avinash-0007
  * [ ] #35553
* @bigcat88
  * [ ] #47186
* @blizzz
  * [ ] #38624
  * [ ] #44341
  * [ ] #44767
  * [ ] #44848
  * [ ] #46991
  * [ ] #46992
* @camilasan
  * [ ] #43281
* @charleypaulus
  * [ ] #35189
* @chrisfritsche
  * [ ] nextcloud/activity#504
* @ChristophWurst
  * [x] #45221
* @come-nc
  * [ ] #37149
  * [ ] #38946
  * [ ] #43527
  * [ ] #43689
  * [ ] #44555
  * [ ] #46114
  * [ ] #46887
  * [ ] #47180
* @danialRahimy
  * [ ] #39192
* @danxuliu
  * [ ] #46859
  * [ ] nextcloud/files_pdfviewer#654
* @djon2003
  * [ ] #41370
* @dpschen
  * [ ] #45030
* @drjoeycadieux
  * [ ] #45628
* @elzody
  * [ ] nextcloud/text#6199
* @FedericoHeichou
  * [ ] #40019
* @fgsl
  * [ ] nextcloud/circles#226
  * [ ] nextcloud/circles#229
* @fitrahmunir
  * [ ] #41659
* @fsamapoor
  * [ ] #39692
  * [ ] #39882
  * [ ] #45135
  * [ ] #45137
  * [ ] #45145
  * [ ] #45146
* @func0der
  * [ ] #40468
* @grnd-alt
  * [ ] nextcloud/text#5690
* @hamza221
  * [x] #41740
* @hardviper
  * [ ] #43684
* @haslersn
  * [ ] #40407
* @hellodarkness
  * [ ] #42610
* @HolgerHees
  * [ ] #43573
* @hopleus
  * [ ] #43660
  * [ ] #44274
* @icewind1991
  * [ ] #33579
  * [ ] #33582
  * [ ] #33597
  * [ ] #33918
  * [ ] #33985
  * [ ] #34655
  * [ ] #35523
  * [ ] #36526
  * [ ] #38367
  * [ ] #38489
  * [ ] #38765
  * [ ] #39168
  * [ ] #39231
  * [ ] #39366
  * [ ] #40394
  * [ ] #41434
  * [ ] #43655
  * [ ] #43851
  * [ ] #45139
  * [ ] #45330
  * [ ] #45456
  * [ ] #45457
  * [ ] #45880
  * [ ] #46013
  * [ ] #46021
  * [ ] #47038
  * [ ] #47182
* @iLinaza
  * [ ] #45036
* @individual-it
  * [ ] #37761
* @J0WI
  * [ ] #35587
* @jadjoud
  * [ ] #44594
* @JanisPlayer
  * [ ] #40048
* @jbmolle
  * [ ] #36791
* @JeaNugroho
  * [ ] #39022
* @Jerome-Herbinet
  * [ ] #36831
  * [ ] #41155
  * [ ] nextcloud/circles#1422
* @jlehtoranta
  * [ ] #44090
* @jmechnich
  * [ ] #45085
* @joshtrichards
  * [ ] #37581
  * [ ] #38630
  * [ ] #38857
  * [ ] #39242
  * [ ] #44322
  * [ ] #45261
  * [ ] #46040
  * [ ] #46140
  * [ ] #46176
  * [ ] #46480
  * [ ] #46516
  * [ ] #46617
  * [ ] #46888
  * [ ] nextcloud/suspicious_login#875
  * [ ] nextcloud/updater#571
* @jpsn123
  * [ ] #43226
* @juliushaertl
  * [ ] #27531
  * [ ] #38407
  * [ ] #39303
  * [ ] #43429
  * [x] nextcloud/text#6181
  * [x] nextcloud/viewer#2416
* @kesselb
  * [ ] #38385
  * [ ] #38445
  * [ ] #38632
  * [ ] #42534
  * [ ] #46255
* @klondi
  * [ ] #40208
* @LakshayaTohan
  * [ ] nextcloud/logreader#857
* @luka-nextcloud
  * [ ] #43025
* @lwenderoth
  * [ ] #46908
* @madmas
  * [ ] nextcloud/activity#460
* @makoehr
  * [ ] nextcloud/updater#471
* @marcelklehr
  * [ ] #46222
* @marcoambrosini
  * [ ] #41718
* @Mazhoon
  * [ ] #35270
* @miaulalala
  * [ ] #46723
* @MichaIng
  * [ ] #46151
* @mutazawadorg
  * [ ] #34198
* @nickvergessen
  * [ ] #45382
  * [x] #47189
  * [ ] nextcloud/photos#2593
* @Noodlesalat
  * [ ] #45020
* @onny
  * [ ] nextcloud/circles#1349
* @ostasevych
  * [ ] nextcloud/files_pdfviewer#938
  * [ ] nextcloud/files_pdfviewer#939
* @p5n
  * [ ] #27806
* @pboguslawski
  * [ ] #33795
* @pointhi
  * [ ] #44574
* @provokateurin
  * [x] #46806
  * [x] #46809
  * [x] #46812
  * [x] #46813
  * [x] #46814
  * [x] #46816
  * [x] #46821
* @Psycojoker
  * [ ] #40763
* @Pytal
  * [ ] #38477
  * [ ] #44141
  * [ ] #44665
  * [ ] #46124
  * [ ] #47158
* @rakekniven
  * [ ] #44945
* @remicollet
  * [ ] #45027
* @rotdrop
  * [ ] nextcloud/circles#1297
* @rullzer
  * [ ] #34491
  * [x] #34562
* @Schnoop
  * [ ] #43364
* @shdehnavi
  * [ ] #39235
  * [ ] #39245
  * [ ] #39246
* @ShGKme
  * [ ] #41065
  * [ ] nextcloud/notifications#2002
  * [ ] nextcloud/viewer#1711
* @simonspa
  * [ ] #36220
* @skazi0
  * [ ] #46840
* @smarinier
  * [ ] #45555
* @smesterheide
  * [ ] #34132
  * [ ] #35732
* @solracsf
  * [ ] #40164
  * [ ] #46845
  * [ ] #47155
  * [ ] nextcloud/activity#1700
* @Sprinterfreak
  * [ ] #45740
* @starypatyk
  * [ ] #33426
  * [ ] nextcloud/viewer#1952
* @StCyr
  * [ ] #42886
* @stellarpower
  * [ ] #44334
  * [ ] #44335
* @sualko
  * [ ] nextcloud/recommendations#458
* @summersab
  * [ ] #40046
* @susnux
  * [ ] #40537
  * [ ] #40621
  * [ ] #43575
  * [ ] #44901
  * [ ] #45431
  * [x] #46966
  * [x] #47016
  * [x] #47181
  * [ ] #47185
  * [ ] nextcloud/logreader#1041
  * [x] nextcloud/password_policy#513
  * [ ] nextcloud/photos#2312
* @taminob
  * [ ] #41321
* @tanganellilore
  * [ ] #38587
* @tcitworld
  * [ ] #34873
  * [ ] #35754
  * [ ] #36522
  * [ ] #37170
  * [ ] #37193
  * [ ] #37303
  * [ ] #38093
  * [ ] #39372
  * [ ] #39977
  * [ ] #40997
  * [ ] #42347
  * [ ] #42763
* @the-djmaze
  * [ ] #36239
* @TheKhanj
  * [ ] #41002
* @theronakpatel
  * [ ] #40796
  * [ ] #42356
* @tortuetorche
  * [ ] nextcloud/circles#392
  * [ ] nextcloud/circles#395
  * [ ] nextcloud/circles#398
  * [ ] nextcloud/circles#399
  * [ ] nextcloud/circles#400
  * [ ] nextcloud/circles#401
* @whlsxl
  * [ ] #38750
* @wronny
  * [ ] #41947
* @yemkareems
  * [ ] #46352
* @yrlchn
  * [ ] #44997
* @zak39
  * [ ] #44392
* @ze42
  * [ ] #45396
* @zevlee
  * [ ] #36769
* (generated)
  * [ ] nextcloud/activity#1683
  * [ ] nextcloud/activity#1717

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Before doing the RC1 of every major release we have to branch off the server and related app repositories from their default branch to stableXY.

So this should be based on stable30?! Or you want to merge this and then directly branch-off?

**Comment by skjnldsv** [comment]
> So this should be based on stable30?! Or you want to merge this and then directly branch-off?

I'll probably switch base right before release.
This PR is mostly for a dev ping on various PRs

**Comment by juliushaertl** [comment]
## Required pull requests

- [ ] https://github.com/nextcloud/text/pull/6200

**Review by juliusknorr — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
I see no differences between this branch's 3rdparty and stable30. Looks like a false negative

image
image

**Pull request merged**
