### PR TITLE
Change color for primary element on hover

### LINKED ISSUE #4193: [BITV] Buttons accessibility improvements
Update: I hid the previous conversation as we were going in the wrong direction. I'm updating the description with the specific accessibility problems that we have in the button component as per the call with the expert last week.  

To be addressed:

- [x] Focus state: currently there's not enough contrast between the background of the buttons and the dark outline we have. 
Solution: Add 2 outlines as focus state to buttons, both 2px thick. The inner should be `--color-main-text`, and the outer `--color-main-background`

Screenshot 2023-06-30 at 11 12 46

- [x] Primary button hover state doesn't meet text contrast requirements (needs solution)
- [x] Special buttons don't meet text contrast requirements (needs solution)

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
* Fixes: https://github.com/nextcloud/nextcloud-vue/issues/4193

## Summary

Fixes color for primary element on hover state https://github.com/nextcloud/nextcloud-vue/issues/4193#issuecomment-1630476883

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Please adjust generation script 

https://github.com/nextcloud/server/blob/0fca8238dd86d572f0f15eaa8e8a5ea836cc76bf/apps/theming/lib/Themes/CommonThemeTrait.php#L67

**Comment by JuliaKirschenheuter** [comment]
@skjnldsv could you please help me how should this mix looks like?

**Comment by skjnldsv** [comment]
> @skjnldsv could you please help me how should this mix looks like?

I can't, i have no idea how your hex colour got chosen.
Usage is as follow


> mix($hex, [$amount] ) : Allows you to mix another color to your color. Optionally you can decide to set the percent of second color or original color amount is ranged -100...0...100.

You have to pick the right amount to get as close as your `#2c7cae` as possible :shrug:

**Review by nimishavijay — APPROVED** [review]

**Comment by skjnldsv** [comment]
> > I can't, i have no idea how your hex colour got chosen.
> 
> It is the slightly darker and bluer version of the previous hover color, but there was no logic per se. I can try and find another close color, how does the mix work?

Using `65` as a mix factor, we get `#2c84b3`. Which seems close to your `#2c7cae` @nimishavijay 

___
You can try this here: https://play.phpsandbox.io/mexitek/phpcolors
```php
<?php
use Mexitek\PHPColors\Color;

$color = new Color('#006AA3');
$background = new Color('#ffffff');

echo '#' . $color->mix($background, 65) . PHP_EOL;
```

**Comment by nimishavijay** [comment]
Super nice! Thank you @skjnldsv :)

Unfortunately the color code you suggested does not have enough contrast against the main background color. However, using `75` as the mix factor, we get `#1f7cae` which is also basically the same and is accessible 🎉 so @JuliaKirschenheuter we can use  `#1f7cae` as the color here :) 

image

**Comment by skjnldsv** [comment]
> Unfortunately the color code you suggested does not have enough contrast against the main background color.

This is not a variable used for text btw, so contrast rules are a bit more flexible for big elements iirc :)
But all good for me with `#1f7cae`  too

**Comment by JuliaKirschenheuter** [comment]
@nimishavijay @skjnldsv 

After several tryings just saw you discussion. 
Thanks a lot for your cooperation, i've taken a mix factor `75` and `#1f7cae` as color ;))

**Review by nimishavijay — APPROVED** [review]
🚀 :)

**Review by Pytal — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
