### PR TITLE
feat: Split display name and username columns

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Split the columns in preparation for making the table sortable and adding header sort buttons

Before | After
--- | ---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Makes sense for me, lets wait for designers.

**Comment by joshtrichards** [comment]
Might be some intersection with #34178 (to avoid future code debt) though I didn't really follow where that stands since it's merged and the menu entry to get to *Accounts* is still labeled as *Users* so dunno.

In any case, seems header *Username* -> *Login* I think?

**Comment by Pytal** [comment]
> Might be some intersection with #34178 (to avoid future code debt) though I didn't really follow where that stands since it's merged and the menu entry to get to _Accounts_ is still labeled as _Users_ so dunno.

I think this was intentional @skjnldsv ?

> In any case, seems header _Username_ -> _Login_ I think?

On the login page it is also "username" so I will keep it the same

**Review by jancborchardt — APPROVED** [review]
Seems good!

Agree with @joshtrichards that Username should be "Account name" (same on the login screen). But it’s something for a separate pull request. :)

**Comment by Pytal** [comment]
> Agree with @joshtrichards that Username should be "Account name" (same on the login screen). But it’s something for a separate pull request. :)

Sure, can do in a followup :)

> Also question @Pytal – isn’t the sorting we add by "Last login" only? (And display name which is the default.) Or are we just going to make everything sortable?

Will just be displayname, userId, and last login for now as that is what has been implemented on the backend, not sure about others as it may be complicated

**Pull request merged**
