### PR TITLE
Disable translucency on high contrast themes

### LINKED ISSUE #34514: header transparent in files app in high-contrast mode
See 
image

present on latest c.nc.c with 25 rc3

### PR DESCRIPTION
**Pull request by CarlSchwan**
Fix #34514

### CODE REVIEW

**Comment by blizzz** [comment]
master is 26

**Review by Pytal — APPROVED** [review]

**Review by szaimen — CHANGES_REQUESTED** [review]
I think we need to fix fhe variable for these themes. See https://github.com/nextcloud/server/blob/6003f8c07bcc49c54115b656963187a51f1ad645/apps/theming/lib/Themes/DarkTheme.php#L56 and https://github.com/nextcloud/server/blob/6003f8c07bcc49c54115b656963187a51f1ad645/apps/theming/lib/Themes/DarkTheme.php#L68

**Comment by CarlSchwan** [comment]
> I think we need to fix fhe variable for these themes. See 

@szaimen I'm not sure I understand correctly what you mean here. What is the problem with this variables?

**Comment by szaimen** [comment]
> > I think we need to fix fhe variable for these themes. See
> 
> @szaimen I'm not sure I understand correctly what you mean here. What is the problem with this variables?

in high contrast mode dark is `--color-main-background-rgb` `23,23,23` but it should be `0,0,0`

**Comment by CarlSchwan** [comment]
> in high contrast mode dark is --color-main-background-rgb 23,23,23 but it should be 0,0,0

Contrast is already 17 this is already way higher than the required contrast for AAA. High contrast theme doesn't mean black on white theme ;)

**Comment by szaimen** [comment]
> Contrast is already 17 this is already way higher than the required contrast for AAA. High contrast theme doesn't mean black on white theme ;)

fine but it is still wrong. will push the change to the branch shortly

**Comment by szaimen** [comment]
> > Contrast is already 17 this is already way higher than the required contrast for AAA. High contrast theme doesn't mean black on white theme ;)
> 
> fine but it is still wrong. will push the change to the branch shortly

done with f1b3842

**Review by szaimen — APPROVED** [review]
lgtm now but didn't test

**Pull request merged**
