### PR TITLE
Csp/more moving handlebars

### PR DESCRIPTION
**Pull request by rullzer**

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:+1:

**Comment by rullzer** [comment]
Seems CI is not happy

**Review by MorrisJobke — DISMISSED** [review]

**Review by danxuliu — DISMISSED** [review]
The _*templates.js_ files should be added to _core/js/core.json_ and _apps/files_versions/js/merged.json_.

**Comment by MorrisJobke** [comment]
Regarding the templates: do they contain any l10n strings, because they are then not extracted? And then I need to add all the compiled files into the translation tool like https://github.com/nextcloud/docker-ci/commit/4861ca66a6ea13ca634d30b7142bbbcc556e15e4 to avoid problems when extracting.

**Comment by rullzer** [comment]
@MorrisJobke no the templates should not contain any translated strings.  If they still do we should extract it and make it a parameter.

**Comment by rullzer** [comment]
All green! https://drone.nextcloud.com/nextcloud/server/11091

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
