### PR TITLE
[app:files] Use current directory for hashing.

### LINKED ISSUE #10527: Upload via web  interface of file with same name in different subfolders
### Steps to reproduce
1. Create a folder structure like that: 
   +subfolder001 (contain the file: filename.txt)
   +subfolder002 (contain the file: filename.txt)
   +subfolder003 (contain the file: filename.txt)
   +subfolder004 (contain the file: filename.txt)
   +subfolder005 (contain the file: filename.txt)

2.  Drag and drop the five folders at the same time into the nextcloud file area. 

### Expected behaviour
The five folder with the same structure copied without errors. 

### Actual behaviour
The files are not copied and the web interface remain blocked. It appens quite always also with just two folders. 
NOTE: I have also tryed the same procedure in the official demo of nextcloud.com and it have the same behaviour. 

### Server configuration

**Operating system**: Debian 9 

**Web server:** Nginx 

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:**  13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**  Fresh install 

**Where did you install Nextcloud from:** from git repository

**Signing status:**
<details>
<summary>Signing status</summary>

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Tested also disabling all apps. 
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Default unmodified config 
</details>

**Are you using external storage, if yes which one:**  no external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
no ldap
</details>

### Client configuration
**Browser:** Tested with multiple browser chrome, firefox (not possible with edge because do not support folder upload)

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

Nothing appears in system logs.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Nothing appears in nextcloud logs also in debug
</details>

#### Browser log
<details>
<summary>Browser log</summary>

</details>

### PR DESCRIPTION
**Pull request by evilham**
This fixes collisions that were causing uploads to break in a very
terrible way.

Kudos to @kesselb for finding the problematic place and to
@hottwister for the proposed solution.

Fixes #10527.

It would be great if this were backported to 15.0.

### CODE REVIEW

**Comment by kesselb** [comment]
Please keep in mind that these changes are only a part of the fix from owncloud. I'm still unsure if we need the other changes for something.

https://github.com/owncloud/core/pull/29393/files

**Comment by kesselb** [comment]
@evilham could you please sign off your commits (check https://github.com/nextcloud/server/pull/14674/checks?check_run_id=77759184 for help)?

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
> @evilham could you please sign off your commits (check https://github.com/nextcloud/server/pull/14674/checks?check_run_id=77759184 for help)?

@evilham Any chance that you can add this?

**Comment by MorrisJobke** [comment]
Should also be fine without, because it's very little code change itself.

**Review by kesselb — APPROVED** [review]

**Comment by evilham** [comment]
Sorry for the delay and thank you for merging.

Just as a comment: although I understand the motivation, I strongly disagree with the legal-name requirement; and indeed those bits of code are already unmistakeably under a compatible license.

**Pull request merged**
