### PR TITLE
Theming app: Add plain background color option

### PR DESCRIPTION
**Pull request by juliusknorr**
Implements https://github.com/nextcloud/server/issues/1414

ToDo:
- [x] Adjust tests

@MorrisJobke @nextcloud/theming

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks good and works, but I would make the button border coloured in the same way as the button background. 👍

**Comment by jancborchardt** [comment]
@MorrisJobke the thing is that by default the background color should be / is the same as the primary color (which is header color and button color). So there would be no difference between button and background.

On dark backgrounds, the primary button should probably have a bright border by default. I also thought about that for the share link view for the headers in the top (blue button with white border).

**Comment by MorrisJobke** [comment]
> @MorrisJobke the thing is that by default the background color should be / is the same as the primary color (which is header color and button color). So there would be no difference between button and background.

This is not the case - the button is darkened by 20% 😉 

```
background-color: nc-darken($color-primary, 20%);
```

**Review by MorrisJobke — APPROVED** [review]
Perfect! Looks awesome! 👍

**Comment by MariusBluem** [comment]
What about the usage of those 🌎-like pattern in the background of the homepage? 🤔

**Comment by juliushaertl** [comment]
> What about the usage of those ￼-like pattern in the background of the homepage? ￼

I'd prefer to keep it as simple as possible, if anyone wants that kind of a pattern they can upload an image. :wink:

**Comment by MorrisJobke** [comment]
> What about the usage of those 🌎-like pattern in the background of the homepage? 🤔

Yep. Small steps. 😉

**Comment by eppfel** [comment]
Button vs background could use some more contrast, but good enough...

**Review by LukasReschke — DISMISSED** [review]
Needs rebase.

**Review by LukasReschke — CHANGES_REQUESTED** [review]
The OCS API is still advertising the background image at `/ocs/v1.php/cloud/capabilities`. Should we change that to either return an URL or a hex code?

**Comment by LukasReschke** [comment]
That said. I'm ok with merging now and fixing that later. Filed at https://github.com/nextcloud/server/issues/4731

**Review by LukasReschke — APPROVED** [review]

**Comment by skjnldsv** [comment]
👍

**Comment by toddpfaff** [comment]
I'm confused.  These changes appear to have been committed back in May, but I'm not seeing any option in Nextcloud-12.0.2 for setting a solid colour background instead of an image.

So I tried to fall back to my method mentioned here:
  https://github.com/nextcloud/server/issues/1414
but that is no longer working in 12.0.2.

Now in the Admin->Settings->Theming screen, after I upload my tiny image, I see "Saved" pop up in green, and then I get a non-stop spinning wheel, and sometimes "Loading preview..." is displayed.  I have to reload the page for this to stop.

After I upload my image, I find an upscaled version of that image in

   appdata_<instance_id>/theming/images/background

and I can copy that image elsewhere, display it, and it looks like the solid colour I was expecting.
But this solid colour image never shows up on the login screen.

**Comment by nickvergessen** [comment]
You just have to delete the login background, then the color will be used.

**Comment by toddpfaff** [comment]
I've tried that but it's not working for me.

**Comment by toddpfaff** [comment]
Please see my Nextcloud support forum post here:

https://help.nextcloud.com/t/nextcloud-12-theming-login-screen-solid-background-color/19939/1

**Comment by MariusBluem** [comment]
...and please: If something does not work, please open a new Issue and do not hijack Pull Requests merged weeks ago 😅 THX!

**Comment by toddpfaff** [comment]
Understood, and I apologize for that.  I realized my mistake and followed
up with a post this morning to the Nextcloud support forum.

**Pull request merged**
