### PR TITLE
Fix condition

### PR DESCRIPTION
**Pull request by ArtificialOwl**

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
🙈 👍

**Comment by MorrisJobke** [comment]
Sign off is missing: https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

**Review by nickvergessen — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> not sure there is a way to add the signed-off line now

`git commit --amend -s`

Let me do this, because this is a minor change anyway :)

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
Needs backporting to 11

**Pull request merged**
