### PR TITLE
fix(user_ldap): Catch DB Exceptions when updating group memberships

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: # 

## Summary

When inserting/deleting group membership, it may simply fail because another job or request is doing the same thing concurrently. In this case we must not crash but simply ignore the error. When it fails for unexpected reason, we must log it but not crash.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by icewind1991** [comment]
it probably makes sense to catch the unique errors in the `GroupMembershipMapper`

**Comment by come-nc** [comment]
> it probably makes sense to catch the unique errors in the `GroupMembershipMapper`

But no other mapper is doing so, the insert/delete methods are standard from parent class?

**Comment by icewind1991** [comment]
> > it probably makes sense to catch the unique errors in the `GroupMembershipMapper`
> 
> But no other mapper is doing so, the insert/delete methods are standard from parent class?

Fair enough

**Review by icewind1991 — APPROVED** [review]

**Review by ArtificialOwl — APPROVED** [review]

**Pull request merged**
