### PR TITLE
Mapping of m3u, m3u8, pls to audio streams

### PR DESCRIPTION
**Pull request by Rello**
Usage of m3u, m3u8, pls as audio playlists according to their standard

### CODE REVIEW

**Comment by Rello** [comment]
https://en.m.wikipedia.org/wiki/M3U
https://en.m.wikipedia.org/wiki/PLS_(file_format)

**Comment by MorrisJobke** [comment]
@Rello Could you add the same repair steps as in #6297? Thanks

**Comment by Rello** [comment]
@MorrisJobke I added the repair step. let me know if anything else is needed of if anything is incorrect

**Comment by MorrisJobke** [comment]
@Rello Looks good. Could you rebase on the latest master as there is a conflict and then this is good to go in. Thanks :)

**Comment by nickvergessen** [comment]
Please also increase the version.php number so it is actually triggered

**Comment by Rello** [comment]
@MorrisJobke @nickvergessen 
would you mind supporting me on this and perhaps doing the fixes requested?
I don´t really know what to do to fulfill your requests.

I just tried to add a mime-type which was missing to make Nc even better. I don´t know about the details of the NC-Server repo.

thank you,
Rello

**Pull request closed without merging**
