### PR TITLE
Remove old sccsphp dependency

### PR DESCRIPTION
**Pull request by CarlSchwan**
Todos

- [x] Merge https://github.com/nextcloud/3rdparty/pull/1040
- [x] Rebase

### CODE REVIEW

**Comment by nickvergessen** [comment]
Pr is merged, now rebase here?

**Comment by CarlSchwan** [comment]
this breaks the dyslexia font, I'm working on a fix

**Review by skjnldsv — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/server/blob/eb45a6ca404524bad6416ba3b3a755f9faa5e9b8/apps/theming/lib/Controller/ThemingController.php#L333-L335

**Comment by CarlSchwan** [comment]
> https://github.com/nextcloud/server/blob/eb45a6ca404524bad6416ba3b3a755f9faa5e9b8/apps/theming/lib/Controller/ThemingController.php#L333-L335

See this PR this removes the usage of it and do the simple CSS prefixing directly.

**Comment by skjnldsv** [comment]
> See this PR this removes the usage of it and do the simple CSS prefixing directly.

I tested the perf of the scsscacher and it seemed more than ok.
I think this is much more complex and difficult to read. Also it now means themes can inject code that doesn't impact their theme only. I prefer a safe scope :)

**Comment by CarlSchwan** [comment]
> > See this PR this removes the usage of it and do the simple CSS prefixing directly.
> 
> I tested the perf of the scsscacher and it seemed more than ok. I think this is much more complex and difficult to read. Also it now means themes can inject code that doesn't impact their theme only. I prefer a safe scope :)

This is a 15 lines patch that would allow us to remove 19 000 lines of code. I still think it is worth it, even if the performance reasons are really minor. This is less work in the long term for handling the dependency bump (we are currently minor 2 versions in master and 6 in stable22) and limit a bit more the risk of supply chain attacks.

I'm actually even surprised that `@font-face` works currently since `@font-face` can't be nested inside a CSS query and it seems that scssphp will unnest it differently from that node-sass will do. And I don't like depending on nonstandard behavior.

**Comment by skjnldsv** [comment]
> And I don't like depending on nonstandard behavior.

With scss it's proper.

> This is a 15 lines patch that would allow us to remove 19 000 lines of code

This is very different since we're talking about a dependency :)
I'm talking about our code maintainability. I don't think the approach this PR do is acceptable :shrug:

**Pull request closed without merging**
