### PR TITLE
Allow user to run console if he can write config via group membership

### PR DESCRIPTION
**Pull request by pvi-github**
Hello,

If the web server is set up to tighten security with a different user for web server process and ssh user activities either the web server will have access to the config file through group membership or (reverse case) the logged user will have access to the config file through group membership.

This PR deals with the case of www-data owning the file and the logged-in user being able to read/write it through group membership.

Kind regards,
PVI

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks :+1: 

We have a lot of issues with `posix_getpwuid` for configurations with unreadable /etc/passwd. I would always suggest to run a php-fpm process with the user the files belongs to. 

Patch not acceptable from my POV.

**Comment by pvi-github** [comment]
Hello kesselb,

Thanks a lot for your feedback :  even if my PR is not acceptable as is this quick response is very kind and welcoming and explains things!

I understand very well the unreadable /etc/passwd objection... maybe there is an other way to check that the config file is writable? I'll dig tofind something cleverer.

For the php-fpm remark I hope you'll agree with my additive explanation : one of the good practices I like to apply is to give write access to the web server proccesses only on files/directories where there is a legit reason to write : upload zones, temp files  & cache zones, logs (and hopefully nothing more). 
In some cases like Wordpress or Nextcloud there is also the need to write in apps and config directories.. for them I derogate to my rule but the less the better.

I do this mainly by running the web server with an other user than the one owning the php files and I use linux acl to give specific write access just where it is required.

Of course for nextclouds installed on shared hosting platforms it's not easy to do but for bigger nextcloud installs with higher security needs it might make sense.

 Kind regards,
PVI

**Comment by MorrisJobke** [comment]
> cc @MorrisJobke @rullzer do you know what the config owner check is about?

It is there to avoid running a CLI command which then renders the web part broken, because the file is not readable anymore or not writable anymore. Mostly to block the usage of sudo, but this can be the case with any other user that would write to it and cause privilege changes during that execution.

**Comment by MichaIng** [comment]
IMO it makes sense to keep the strict behaviour. Potentially CLI can create files which must be later writable for the webserver/PHP. Better to force the use of `sudo` in the first place than dealing which various possibly hard to debug issues later that users report.

To shorten the `occ` command execution, we do:
```
alias occ='sudo -u www-data php /var/www/nextcloud/occ "$@"'
```

I'm regularly dealing with other software implementations which have a CLI that can be executed by anyone. When running such as system service (with dedicated system user) it is always a pain to find a way that the CLI is easily called with the correct user, otherwise we face bug reports either about missing configs/data because of wrong home dir or wrong permissions later on. Creating system-wide shell aliases helps but does not rule out the case, so I'm very happy that Nextcloud prohibits wrong user executions in the first place 😃.

**Comment by skjnldsv** [comment]
Closing see last comment

**Pull request closed without merging**
