### PR TITLE
Adjust drone config to drone 1.0.0

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by kesselb** [comment]
Drone 1.0 :clap: Is it possible to stop my own ci builds now?

**Comment by kesselb** [comment]
Peek 2019-04-04 15-15

I can create and delete secret variables. I have not tested to remove `GITHUB_TOKEN`

**Comment by MorrisJobke** [comment]
Yep - looking into it :/ they changed all the names of their configs and missing the one for admins :(

**Comment by MorrisJobke** [comment]
* [ ] handlebars looks weird:

```
1 | npm install handlebars -g
2 | /usr/local/bin/handlebars -> /usr/local/lib/node_modules/handlebars/bin/handlebars
3 | + handlebars@4.1.1
4 | added 8 packages from 40 contributors in 0.597s
5 | + ./build/compile-handlebars-templates.sh
6 |  
7 | /usr/local/lib/node_modules/handlebars/bin/handlebars:120
8 | throw err;
9 | ^
10 | Error: Unable to open template file "apps/comments/js/templates"
11 | at /usr/local/lib/node_modules/handlebars/dist/cjs/precompiler.js:103:25
12 | at FSReqCallback.oncomplete (fs.js:158:21)
13 |  
14 | /usr/local/lib/node_modules/handlebars/bin/handlebars:120
15 | throw err;
16 | ^
17 | Error: Unable to open template file "apps/files_versions/js/templates"
18 | at /usr/local/lib/node_modules/handlebars/dist/cjs/precompiler.js:103:25
19 | at FSReqCallback.oncomplete (fs.js:158:21)
20 | All up to date! Carry on :D
```

**Comment by MorrisJobke** [comment]
> [ ] handlebars looks weird:

Also on master - I have a change locally but will do this in a separate PR.

**Comment by MorrisJobke** [comment]
> I can create and delete secret variables. I have not tested to remove `GITHUB_TOKEN`

Seems to be because you are a member of the org. Acceptable - if somebody goes wild we readd the secret and then maybe block the user.

**Comment by MorrisJobke** [comment]
> Drone 1.0 👏 Is it possible to stop my own ci builds now?

It should be - also all others ;)

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Ready to merge - some of the jobs ran into the timeout of 30 minutes, but the general config is working.

**Pull request merged**
