### PR TITLE
Allow to have mutliple buttons on the filepicker

### PR DESCRIPTION
**Pull request by nickvergessen**
Required for Talk for Nextcloud 18:
https://github.com/nextcloud/spreed/pull/2193

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Code looks ok

**Review by juliusknorr — APPROVED** [review]
Tested and works :+1:

**Comment by juliushaertl** [comment]
@nickvergessen Mind to rebase?

**Comment by szaimen** [comment]
@nickvergessen any update here?
Would be really nice to get https://github.com/nextcloud/spreed/pull/2193 ready for Nextcloud 18 :)

**Comment by skjnldsv** [comment]
please rebase

**Comment by nickvergessen** [comment]
Rebasing every 4 days? Just rebase it and merge it 😬

**Pull request merged**
