### PR TITLE
feat(request): Allow to match the client version with the IRequest::U…

### PR DESCRIPTION
**Pull request by nickvergessen**
…SER_AGENT_* regex

## Summary

* The idea is to allow APIs to "block" clients based on their versions, similar to:
https://github.com/nextcloud/server/blob/c63ff42410107570eef49cd0deea75821c5aeae1/apps/dav/lib/Connector/Sabre/BlockLegacyClientPlugin.php#L69-L71

    - [x] Need to clarify when the desktop client started to use a correct user agent and whether we can switch to that const there as well. If that is still a thing we could extend the regex to `/^(?:Mozilla\/5\.0 \([A-Za-z ]+\) )?(?:mirall|csyncoC)\/([^ ]*).*$/` cc @tobiasKaminsky @mgallien 

* Similar plan is developed in Talk and we would like to avoid duplicating the constants:
https://github.com/nextcloud/spreed/pull/9632

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by mgallien** [comment]
Starting with version 1.3.0 the user agent was following the pattern `/^(Mozilla\/5\.0 \([A-Za-z ]+\) )(mirall)\/([^ ]*).*$/`

**Comment by nickvergessen** [comment]
That 1.3.0 version is from 2013, so that is save enough. Thanks for checking!

**Review by ChristophWurst — APPROVED** [review]
Nice

**Review by nfebe — APPROVED** [review]
LGTM :)

**Pull request merged**
