### PR TITLE
[stable9] check permissions before rollback

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/nextcloud/server/pull/253

@LukasReschke @MorrisJobke please review.

cc @karlitschek fyi

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport

**Comment by mar1u5** [comment]
Is already the Backport :stuck_out_tongue_winking_eye: @karlitschek

**Comment by karlitschek** [comment]
hehe. faster then expected!!!

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by schiessle** [comment]
second review needed... maybe  @mar1u5 or @LukasReschke

**Comment by LukasReschke** [comment]
:

**Pull request merged**
