### PR TITLE
Fix detection of file types a bit

### PR DESCRIPTION
**Pull request by nickvergessen**
@icewind1991 Do you have any better idea?

@oparoz @LukasReschke

### CODE REVIEW

**Comment by oparoz** [comment]
What happens if the media type is not `application/octet-stream`, but `application/x-zip-compressed`? Wouldn't it bypass the new test?

**Comment by nickvergessen** [comment]
Well you can use regex to match that

**Comment by oparoz** [comment]
I'll add something to the doc.

**Comment by oparoz** [comment]
https://github.com/nextcloud/documentation/pull/162

**Comment by rullzer** [comment]
LGTM

**Comment by nickvergessen** [comment]
Second +1 so we can do the backport to 10? @MorrisJobke @oparoz @LukasReschke

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
