### PR TITLE
fix(dav): drop unwanted RemoteException class

### LINKED ISSUE #44719: [Bug]: Class "RemoteException" not found
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The check for "webfinger" causes the following to be logged in my `nextcloud.log`:
```
{"reqId":"9hxvgm2X8w9eL5RBw6WA","level":3,"time":"2024-04-08T11:35:44+00:00","remoteAddr":"127.0.0.1","user":"--","app":"public","method":"GET","url":"/.well-known/webfinger","message":"Class \"RemoteException\" not found","userAgent":"Nextcloud Server Crawler","version":"29.0.0.15","exception":{"Exception":"Error","Message":"Class \"RemoteException\" not found","Code":0,"Trace":[],"File":"/path/to/nextcloud/server29/public.php","Line":80,"message":"Class \"RemoteException\" not found","exception":{},"CustomMessage":"Class \"RemoteException\" not found"}}
```

### Steps to reproduce

1. Checkout `stable29` (I'm runing bad51ef63bd84c69e6cc39bb0d09701d48980ec2)
2. Browse the admin settings
3. Check the `nextcloud.log`

### Expected behavior

No error should be logged.

Looks like this was introduced by https://github.com/nextcloud/server/commit/7b6a650b6e09b07d4b85a4ae84eb64a6c32b217f (cc @skjnldsv).

### Installation method

None

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/44719

### CODE REVIEW

**Comment by come-nc** [comment]
From what I can see the exception is never caught, you can directly throw `\Exception` instead? That would avoid confusing psalm with having the same class name in 2 files.

**Comment by skjnldsv** [comment]
done @come-nc 
Took the opportunity to add more comments to the file

**Review by susnux — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Pull request merged**
