### PR TITLE
Adding test for table schedulingobjects and fixing postgres LOB

### PR DESCRIPTION
**Pull request by janLo**
This is a fix for #8825. It was fixed in Owncloud in https://github.com/owncloud/core/pull/27914/commits/afd4ebf0404e8bcd7cba0bec2dce177e97632f8a So this is just a cherry-pick of that fix.

### CODE REVIEW

**Review by blizzz — APPROVED** [review]
makes sense

**Review by nickvergessen — APPROVED** [review]

**Comment by enoch85** [comment]
LGTM, not tested.

**Review by enoch85 — APPROVED** [review]

**Comment by blizzz** [comment]
@janLo could you signoff your commit, so that the checker test passes?

**Comment by janLo** [comment]
Are you sure, that I should sign off the work from another person? Shouldn't be the original commit be signed in the first place?

**Comment by schiessle** [comment]
@janLo you don't have to be the copyright owner to sign the commit. By signing you just declare:

````
By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
````

see https://github.com/nextcloud/server/blob/master/contribute/developer-certificate-of-origin

So if you copied the fix from the public repository of ownCloud and checked that it is licensed under a compatible license then it is absolutely OK to sign it. Actually that's the purpose, you basically say that you checked "to the best of my knowledge" that you can contribute the code to Nextcloud under the license used by Nextcloud.

**Comment by janLo** [comment]
done.

**Pull request merged**
