### PR TITLE
Throw exception if decryption fails

### PR DESCRIPTION
**Pull request by rullzer**
For #11868

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Looks better ¯\\\_(ツ)\_/¯

**Comment by nickvergessen** [comment]
SHould we backport this, because of the type hinting?

**Comment by rullzer** [comment]
Backport should be safe

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
