### PR TITLE
[stable12] Don't load navigation entries of restricted apps

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #5615

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@nickvergessen Somehow the unit tests fail :/

**Comment by nickvergessen** [comment]
yeah I know why... the merged settings thing is two navigation entries in stable12

**Review by juliusknorr — APPROVED** [review]
Works as expected! :+1:

**Pull request merged**
