### PR TITLE
dont spam log when request can't access filesystem

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I guess this fixed #4288, right?

**Review by rullzer — APPROVED** [review]
Works as advertised.

**Review by MorrisJobke — APPROVED** [review]
Yep - doesn't show any problems here too

**Comment by MorrisJobke** [comment]
Rebased to trigger CI

**Comment by MorrisJobke** [comment]
I let the jobs run local -> merge

**Comment by MorrisJobke** [comment]
@icewind1991 @LukasReschke Backport to stable11 because #4288 was scheduled for the 11 series?

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/4622

**Pull request merged**
