### PR TITLE
Fix clearing the label of a share

### PR DESCRIPTION
**Pull request by danxuliu**
Follow up to #21357

When the label is being edited its value is stored in `newLabel`, and the original label is shown only if `newLabel` is not set. However, as it was checked against any falsy value instead of only undefined when the label was cleared and thus it has an empty value the original label was shown instead.

## How to test
- Open _Sharing_ tab for a file
- Create a link share
- Set a label in the link share
- Place the cursor at the end of the label and clear it by pressing backspace*

### Result with this pull request
The label is cleared.

### Result without this pull request
After pressing the last backspace the original label appears again.

*Note that if the whole label is selected and backspace or delete are pressed then the label is cleared as expected.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
🐘

**Comment by rullzer** [comment]
Needs a rebase

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
