### PR TITLE
Improved display of app links

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by jancborchardt — CHANGES_REQUESTED** [review]
@Jerome-Herbinet this looks a bit nonstandard, not an element we use anywhere else. What do you think about a simple list with the default bullet points on the left?

**Comment by jancborchardt** [comment]
@Jerome-Herbinet yep, simply adding line breaks already improves it a lot! :)

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet yep, simply adding line breaks already improves it a lot! :)

Done @jancborchardt :-)

**Review by nimishavijay — APPROVED** [review]

**Comment by szaimen** [comment]
conflicts

**Comment by szaimen** [comment]
@Jerome-Herbinet can you please rebase and commit the compile js again? Sorry for the inconvenience!

**Pull request closed without merging**
