### PR TITLE
SVG defintions always take the first one

### PR DESCRIPTION
**Pull request by rullzer**
- Move filter definition out

Fixes: #922

@MorrisJobke @nickvergessen please test

### CODE REVIEW

**Comment by nickvergessen** [comment]
🌀All magic

:+1:

**Comment by nickvergessen** [comment]
Tests fail

**Comment by MorrisJobke** [comment]
Tested and works in Firefox, Chrome, Edge and IE11.

**Comment by MorrisJobke** [comment]
Somehow the clone failed. I restarted it.

**Comment by LukasReschke** [comment]
Conflicts :(

**Comment by MorrisJobke** [comment]
Um what:

```
[info] Pulling image plugins/drone-git:latest
Drone Git Plugin built from 43dcd64
$ git init
Initialized empty Git repository in /drone/src/github.com/nextcloud/server/.git/
$ git remote add origin https://github.com/nextcloud/server.git
$ git fetch --no-tags origin +refs/pull/937/merge:
fatal: Couldn't find remote ref refs/pull/937/merge
[info] build failed (exit code 1)
```

Ah ... because of the conflicts.

**Comment by MorrisJobke** [comment]
Let me try to resolve this.

**Comment by MorrisJobke** [comment]
Resolved. Still works 👍

**Pull request merged**
