### PR TITLE
Remove unused 'Base64' polyfill

### PR DESCRIPTION
**Pull request by ChristophWurst**
This isn't required anymore as `atob` and `btoa` is now supported in all major browsers according to caniuse.

Ref https://github.com/nextcloud/server/pull/13460#issuecomment-453137318
Replaces #13460

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:fire:

**Review by juliusknorr — APPROVED** [review]

**Comment by rullzer** [comment]
conflicts ;)

**Review by skjnldsv — APPROVED** [review]
More cleanup! :tada: 🧹🧹🧹

**Comment by ChristophWurst** [comment]
@rullzer merge

**Comment by ChristophWurst** [comment]
Btw, if you've ever wondered why our current bundle is 1MB big, here's a little visualization: 
bildschirmfoto von 2019-01-11 10-57-40

Time to get rid of jquery-ui and modularize the moment l10n code :D

**Comment by skjnldsv** [comment]
> modularize the moment l10n code

An interesting discussion needs to happen: https://github.com/nextcloud/nextcloud-vue/pull/146#issuecomment-453045027 :)

**Pull request merged**
