### PR TITLE
fix DBAL exception handling in setValues

### PR DESCRIPTION
**Pull request by blizzz**
* ~~Might be related to post-close comments in #6343~~

## Summary

This seems to be a left over after abstracting DBAL. Nowadays, IQueryBuilder::executeStatement() only throws a \OCP\DB\Exception, where previously original DBAL exceptions where thrown. These are now wrapped, the orignal classes are now mapped to a reason.

(This is a by-catch of testing ldap_contacts_backend and wondering/debugging why its occ edit command was failing).

P.S.: There might be more opportunities for adjustment in this file, did not check further.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] ~~Screenshots before/after for front-end changes~~
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by blizzz** [comment]
25 and below are not affected, since it delegates execution the original Doctrine QueryBuilder and does not catch Exceptions.

**Comment by nickvergessen** [comment]
Can we have a test if this is still used :)

**Comment by blizzz** [comment]
> Can we have a test if this is still used :)

definitely, not ticked in the boxes up there yet

**Comment by blizzz** [comment]
Tests added. Without the fix, they would fail with:

```
PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.13
Configuration: phpunit-autotest.xml

..EE                                                                4 / 4 (100%)

Time: 00:00.020, Memory: 46.88 MB

There were 2 errors:

1) Test\Security\CredentialsManagerTest::testUpdate with data set #0 ('alice', 'privateCredentials')
OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_storages_credentials.user, oc_storages_credentials.identifier

/srv/http/nextcloud/stable26/lib/private/DB/Exceptions/DbalException.php:70
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:328
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:396
/srv/http/nextcloud/stable26/lib/private/DB/ConnectionAdapter.php:114
/srv/http/nextcloud/stable26/lib/private/Security/CredentialsManager.php:72
/srv/http/nextcloud/stable26/tests/lib/Security/CredentialsManagerTest.php:61

Caused by
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_storages_credentials.user, oc_storages_credentials.identifier

/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Driver/API/SQLite/ExceptionConverter.php:44
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1814
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1749
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1163
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:297
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php:354
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:280
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:326
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:396
/srv/http/nextcloud/stable26/lib/private/DB/ConnectionAdapter.php:114
/srv/http/nextcloud/stable26/lib/private/Security/CredentialsManager.php:72
/srv/http/nextcloud/stable26/tests/lib/Security/CredentialsManagerTest.php:61

Caused by
Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_storages_credentials.user, oc_storages_credentials.identifier

/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php:30
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php:103
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1153
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:297
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php:354
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:280
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:326
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:396
/srv/http/nextcloud/stable26/lib/private/DB/ConnectionAdapter.php:114
/srv/http/nextcloud/stable26/lib/private/Security/CredentialsManager.php:72
/srv/http/nextcloud/stable26/tests/lib/Security/CredentialsManagerTest.php:61

Caused by
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_storages_credentials.user, oc_storages_credentials.identifier

/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php:101
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1153
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:297
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php:354
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:280
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:326
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:396
/srv/http/nextcloud/stable26/lib/private/DB/ConnectionAdapter.php:114
/srv/http/nextcloud/stable26/lib/private/Security/CredentialsManager.php:72
/srv/http/nextcloud/stable26/tests/lib/Security/CredentialsManagerTest.php:61

2) Test\Security\CredentialsManagerTest::testUpdate with data set #1 ('', 'systemCredentials')
OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_storages_credentials.user, oc_storages_credentials.identifier

/srv/http/nextcloud/stable26/lib/private/DB/Exceptions/DbalException.php:70
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:328
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:396
/srv/http/nextcloud/stable26/lib/private/DB/ConnectionAdapter.php:114
/srv/http/nextcloud/stable26/lib/private/Security/CredentialsManager.php:72
/srv/http/nextcloud/stable26/tests/lib/Security/CredentialsManagerTest.php:61

Caused by
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_storages_credentials.user, oc_storages_credentials.identifier

/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Driver/API/SQLite/ExceptionConverter.php:44
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1814
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1749
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1163
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:297
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php:354
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:280
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:326
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:396
/srv/http/nextcloud/stable26/lib/private/DB/ConnectionAdapter.php:114
/srv/http/nextcloud/stable26/lib/private/Security/CredentialsManager.php:72
/srv/http/nextcloud/stable26/tests/lib/Security/CredentialsManagerTest.php:61

Caused by
Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_storages_credentials.user, oc_storages_credentials.identifier

/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php:30
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php:103
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1153
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:297
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php:354
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:280
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:326
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:396
/srv/http/nextcloud/stable26/lib/private/DB/ConnectionAdapter.php:114
/srv/http/nextcloud/stable26/lib/private/Security/CredentialsManager.php:72
/srv/http/nextcloud/stable26/tests/lib/Security/CredentialsManagerTest.php:61

Caused by
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_storages_credentials.user, oc_storages_credentials.identifier

/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php:101
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Connection.php:1153
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:297
/srv/http/nextcloud/stable26/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php:354
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:280
/srv/http/nextcloud/stable26/lib/private/DB/QueryBuilder/QueryBuilder.php:326
/srv/http/nextcloud/stable26/lib/private/DB/Connection.php:396
/srv/http/nextcloud/stable26/lib/private/DB/ConnectionAdapter.php:114
/srv/http/nextcloud/stable26/lib/private/Security/CredentialsManager.php:72
/srv/http/nextcloud/stable26/tests/lib/Security/CredentialsManagerTest.php:61

ERRORS!
Tests: 4, Assertions: 4, Errors: 2.
```

**Review by nickvergessen — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Pull request merged**
