### PR TITLE
Unshare from mail activity is missing

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/activity/issues/317#issuecomment-441221681

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Makes sense.

**Comment by MorrisJobke** [comment]
PHPUnit tests are failing.

**Comment by nickvergessen** [comment]
Fixed and rebased

**Review by schiessle — APPROVED** [review]
didn't tested it, but makes sense and the code looks good

**Pull request merged**
