### PR TITLE
Make sure the accounts table exists

### LINKED ISSUE #6078: accounts table missing, can't view personal settings page
After I ran into #5695 last week, I'm now having a similar problem with the (still not existent) accounts table whenever I navigate to the settings page of my dev instance:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: 127.0.0.1
    Request ID: fE1ZFEzwRyY5l6RGdQVz
    Type: Doctrine\DBAL\Exception\TableNotFoundException
    Code: 0
    Message: An exception occurred while executing 'SELECT "data" FROM "oc_accounts" WHERE "uid" = ?' with params ["admin"]: SQLSTATE[HY000]: General error: 1 no such table: oc_accounts
    File: /home/christoph/workspace/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
    Line: 58


Trace

#0 /home/christoph/workspace/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /home/christoph/workspace/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT "data" F...', Array)
#2 /home/christoph/workspace/nextcloud/lib/private/DB/Connection.php(193): Doctrine\DBAL\Connection->executeQuery('SELECT "data" F...', Array, Array, NULL)
#3 /home/christoph/workspace/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): OC\DB\Connection->executeQuery('SELECT "data" F...', Array, Array)
#4 /home/christoph/workspace/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(213): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /home/christoph/workspace/nextcloud/lib/private/Accounts/AccountManager.php(141): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /home/christoph/workspace/nextcloud/lib/private/Settings/Personal/PersonalInfo.php(104): OC\Accounts\AccountManager->getUser(Object(OC\User\User))
#7 /home/christoph/workspace/nextcloud/settings/Controller/CommonSettingsTrait.php(110): OC\Settings\Personal\PersonalInfo->getForm()
#8 /home/christoph/workspace/nextcloud/settings/Controller/PersonalSettingsController.php(70): OC\Settings\Controller\PersonalSettingsController->formatSettings(Array)
#9 /home/christoph/workspace/nextcloud/settings/Controller/CommonSettingsTrait.php(120): OC\Settings\Controller\PersonalSettingsController->getSettings('personal-info')
#10 /home/christoph/workspace/nextcloud/settings/Controller/PersonalSettingsController.php(60): OC\Settings\Controller\PersonalSettingsController->getIndexResponse('personal', 'personal-info')
#11 [internal function]: OC\Settings\Controller\PersonalSettingsController->index('personal-info')
#12 /home/christoph/workspace/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)
#13 /home/christoph/workspace/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\PersonalSettingsController), 'index')
#14 /home/christoph/workspace/nextcloud/lib/private/AppFramework/App.php(114): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\PersonalSettingsController), 'index')
#15 /home/christoph/workspace/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OC\\Settings\\Con...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#16 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#17 /home/christoph/workspace/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#18 /home/christoph/workspace/nextcloud/lib/base.php(1004): OC\Route\Router->match('/settings/user')
#19 /home/christoph/workspace/nextcloud/index.php(40): OC::handleRequest()
#20 {main}
```

@nickvergessen should a migration create that table?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #6078 

@tcitworld

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
LGTM, thanks! :)

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I updated the autoloader. 😉

**Comment by tcitworld** [comment]
Didn't fixed it for me. Sad. :(

**Comment by jancborchardt** [comment]
Same here actually, still have the same problem. cc @nickvergessen

**Comment by nickvergessen** [comment]
Yeah well find out what actually deletes this table for you guys. Maybe some app or something...

The migration here will only fix it once, then it knows it ran and the table should already exist.....

**Comment by pellaeon** [comment]
I'm also hitting this issue, even the migration was run:

```
sqlite> SELECT * FROM oc_migrations;
core|13000Date20170705121758
core|13000Date20170718121200
core|13000Date20170814074715
twofactor_backupcodes|1002Date20170607104347
twofactor_backupcodes|1002Date20170607113030
```

**Comment by nickvergessen** [comment]
There was an issue with sqlite, which was fixed for 12.0.3:
https://github.com/nextcloud/server/issues/6406#issuecomment-328052916

**Pull request merged**
