### PR TITLE
Revert "[stable22] Hash job argument"

### PR DESCRIPTION
**Pull request by skjnldsv**
Reverts nextcloud/server#30736

### CODE REVIEW

**Comment by acsfer** [comment]
Any reason to also revert on 22?
https://github.com/nextcloud/server/pull/30470#discussion_r789116892

**Comment by skjnldsv** [comment]
@acsfer look the number of changes :)

**Comment by acsfer** [comment]
image

**Review by solracsf — APPROVED** [review]

**Comment by nickvergessen** [comment]
Fixed backport in https://github.com/nextcloud/server/pull/30786

**Review by Pytal — APPROVED** [review]

**Pull request closed without merging**
