### PR TITLE
Collapse 2FA admin detail settings if disabled

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Only show details when 2FA is enforced
* Don't immediately save 2FA enforced setting but only when the save button is clicked

Ref https://github.com/nextcloud/server/issues/14639

### CODE REVIEW

**Comment by MorrisJobke** [comment]
* [ ] save button should also be hidden

Bildschirmfoto 2019-03-15 um 14 24 32

**Comment by ChristophWurst** [comment]
> save button should also be hidden

But then you can't disable enforced 2FA anymore :thinking:

**Comment by jancborchardt** [comment]
> But then you can't disable enforced 2FA anymore

Either:
- On unchecking there is no save confirmation needed
- Or the save button only shows in this case if it has been checked before.

**Comment by ChristophWurst** [comment]
The save button now only shows if the user made any local changes and vanishes once saved.

This PR now also fixes a regression of the group selection. This seems to be broken otherwise with the move to the Vuex store.

**Comment by MorrisJobke** [comment]
Rebased and squashed.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
