### PR TITLE
Update the license headers for Nextcloud 19

### PR DESCRIPTION
**Pull request by ChristophWurst**
First I thought seeing my name in so many files was a bug, but it appears to be because of #20168

### CODE REVIEW

**Comment by tcitworld** [comment]
`nextcloud@tcit.fr` isn't a typo. :)
I'll like all the `tcit@tcit.fr` changed to `nextcloud@tcit.fr`, since you're doing this.

**Review by rullzer — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Comment by kesselb** [comment]
> `nextcloud@tcit.fr` isn't a typo. :)
> I'll like all the `tcit@tcit.fr` changed to `nextcloud@tcit.fr`, since you're doing this.

Good news! Just add the mapping to https://github.com/nextcloud/server/blob/master/.mailmap

**Comment by tcitworld** [comment]
> Good news! Just add the mapping to /.mailmap@master 

Many thanks, forgot this existed at all!

**Review by gary-kim — APPROVED** [review]

**Review by tcitworld — APPROVED** [review]
🙏

**Pull request merged**
