### PR TITLE
Remove IE8 APIs

### PR DESCRIPTION
**Pull request by ChristophWurst**
@rullzer as discussed.

@MorrisJobke could you maybe grep your magic *all apps* directory for possible leftovers? How did you find the git repos of all apps, btw? :v:

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> @MorrisJobke could you maybe grep your magic _all apps_ directory for possible leftovers? How did you find the git repos of all apps, btw? ✌️

Github searches, apps.nextcloud.com, issue with installed apps listings, requests for app certificates, ... 😉

**Comment by MorrisJobke** [comment]
That is the only occurence of those two methods: 
https://github.com/nextcloud/passman/blob/c0de19650a6f5398fbfd443240f955ffb3b9e80d/tests/unit/js/mocks/OC.js#L1531-L1559

**Comment by ChristophWurst** [comment]
> Github searches, apps.nextcloud.com, issue with installed apps listings, requests for app certificates, ... wink

You're a magician, @MorrisJobke. I thought you had a magic script that would crawl that info ;)

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Could you add this to https://github.com/nextcloud/server/issues/11045?

**Review by rullzer — APPROVED** [review]

**Pull request merged**
