### PR TITLE
Support subdir in the OCS v2 endpoint

### PR DESCRIPTION
**Pull request by rullzer**
We should check against the ending substring since people could
run their nextcloud in a subfolder.
- Added test

Thanks to @MorrisJobke 

CC: @nickvergessen @MorrisJobke @LukasReschke @icewind1991

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Works 👍

**Comment by MorrisJobke** [comment]
@schiessle Please review

**Comment by nickvergessen** [comment]
:see_no_evil: :+1:

**Comment by nickvergessen** [comment]
Backport to 10 and 9 please

**Comment by rullzer** [comment]
This code is not in stable9.

Stable10: https://github.com/nextcloud/server/pull/609

**Pull request merged**
