### PR TITLE
Various unified search fixes

### PR DESCRIPTION
**Pull request by skjnldsv**
1. Removed dual filter invert conflict. `NcHeaderMenu` already handles it
  https://github.com/nextcloud/nextcloud-vue/blob/82168c242b29e794f8e5177bea90bbd7d48322b4/src/components/NcHeaderMenu/NcHeaderMenu.vue#L293-L295
2. Fixed a somehow reserved variable that was breaking code highlighting in IDEs
3. Fixed EmptyContent broken since https://github.com/nextcloud/nextcloud-vue/pull/3106

| Before | After |
|:---------:|:------:|
|||

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Comment by ostasevych** [comment]
Please, consult, how to apply the patch manually to make the unified search workable? Thanks!

**Pull request merged**
