### PR TITLE
Encode URI for file sidebar

### LINKED ISSUE #18721: Question mark in folder breaks sidebar file info
### Steps to reproduce
1. Name a folder with a question mark at the end like "Question ?"
2. Try to open details, sidebar fail loading file info

image

### Expected behaviour
File info should open properly.

### Actual behaviour
File info is not loading. Console states: `Error while loading the file data Error: "Request failed with status code 404"`

### Server configuration

**Operating system:**
5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
PHP 7.2.24-0ubuntu0.18.04.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install 

**Nextcloud version:**
Nextcloud 18.0.0 Beta3

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #18721 

Something to add to my checklist of "things to check for when reviewing javascript code".

Signed-off-by: Gary Kim <gary@garykim.dev>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by kesselb — APPROVED** [review]
I have no idea but encoding seems the right thing ;)

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by Mikescops** [comment]
@gary-kim I'd better recommend escape()

**Comment by kesselb** [comment]
> Deprecated. Not for use in new websites.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape

**Comment by Mikescops** [comment]
@kesselb oh okay, i didn't knew, i was just wondering if encoding `/` could break things

**Pull request merged**
