### PR TITLE
Fix disabled federated scope

### PR DESCRIPTION
**Pull request by Pytal**
With all settings in Vue let's bring this https://github.com/nextcloud/server/pull/26725 into Vue-land as well

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by Pytal** [comment]
Rebased

**Review by artonge — APPROVED** [review]

**Review by danxuliu — CHANGES_REQUESTED** [review]
If the _Federation_ app is disabled the `Federated` entry is disabled, but the text reads `Not available as publishing user specific data to the lookup server is not allowed, contact your system administrator if you have any questions`, which is not the actual reason. Should the text be fixed or the `Federated` entry be fully hidden (like in #26725)?

Independently of that [`federationEnabled` is still used by _personal.info.php_](https://github.com/nextcloud/server/blob/f922b2fd7072ace8211467e3627f2a44a5c09fe3/apps/settings/templates/settings/personal/personal.info.php#L46) to set `data-federation-enabled`. However, as it was moved from the template parameters to the initial state now it will be always set to `false`. Is `data-federation-enabled` still used anywhere? If it is that should be fixed, and if not it would be better to clean it :-)

**Comment by Pytal** [comment]
> If the _Federation_ app is disabled the `Federated` entry is disabled, but the text reads `Not available as publishing user specific data to the lookup server is not allowed, contact your system administrator if you have any questions`, which is not the actual reason. Should the text be fixed or the `Federated` entry be fully hidden (like in #26725)?

Text has been updated to `Not available as federation has been disabled for your account, contact your system administrator if you have any questions`

Was decided previously by @jancborchardt to show all scopes even if disabled

> Independently of that [`federationEnabled` is still used by _personal.info.php_](https://github.com/nextcloud/server/blob/f922b2fd7072ace8211467e3627f2a44a5c09fe3/apps/settings/templates/settings/personal/personal.info.php#L46) to set `data-federation-enabled`. However, as it was moved from the template parameters to the initial state now it will be always set to `false`. Is `data-federation-enabled` still used anywhere? If it is that should be fixed, and if not it would be better to clean it :-)

Cleaned it up as it is not used anymore :)

**Pull request merged**
