### PR TITLE
Do not load versions tab view if the files app is not available

### LINKED ISSUE #27762: OCA.Files.DetailTabView is undefined on dashboard page
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Run Nextcloud 22 RC2
2. Open the dashboard on your Android tablet using FF Mobild 89

### Expected behavior

No errors.

### Actual behavior

`TypeError: OCA.Files.DetailTabView is undefined` at https://github.com/nextcloud/server/blob/129214e430865836dad57b271f49e63412d5c842/apps/files_versions/src/versionstabview.js#L36

This could be a loading order issue.

https://sentry.io/share/issue/9d856dc0bcdc4d5e995a3676d0c9b466/

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes https://github.com/nextcloud/server/issues/27762

This avoids an error logged on any page that loads the files sidebar without the files app itself being in place (e.g. dashboard where the viewer pulls in the sidebar).

```
TypeError: undefined is not an object (evaluating 'OCA.Files.DetailTabView.extend')
  at call(./apps/files_versions/src/versionstabview.js:36:36)
  at __webpack_require__(webpack/bootstrap:19:22)
  at ? (webpack/bootstrap:83:10)
  at global code(apps/files_versions/js/files_versions.js:83:54)
```

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: :tada: :tada: :tada: :tada:

**Review by ChristophWurst — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
⚙⚙⚙

**Pull request merged**
