### PR TITLE
Remove auto focus of share input field on dialog open, fix #15261

### LINKED ISSUE #15261: Auto focus after clicking on share shows drop down list and scrolling issue
Sometimes you just would like to open the file inspector to copy an already created shared link or to display file details. By clicking on the file (or even by clicking on "details"), the auto focus on "username or e-mail" fires the drop down list with users and groups to select. This hides your created shared links. 

The behaviour is becoming worse if you start scrolling. The drop down has no fix position next to the input textfiled. Instead it starts scrolling as well.

### Steps to reproduce
1. click on a file in list (or on share, or on date, or on "details")
2. file inspector is shown

### Expected behaviour
nothing else

### Actual behaviour
1. auto focus on input filed -> drop down list appears --> is hiding essential information 
2. on scrolling the list is also scrolling

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache/2.4.38
**Database:** MariaDB 10.3.14
**PHP version:** PHP 7.3.4
**Nextcloud version:** 16.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** update
**Where did you install Nextcloud from:** web updater

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - audioplayer: 2.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - user_ldap
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### PR DESCRIPTION
**Pull request by jancborchardt**
Because of the new suggestion dropdown, this interfered with the other options for link sharing and adding to projects. So it’s best to just remove the autofocus.

Would also be good to backport I think. Please review @nextcloud/javascript @AInteriorB 

Fix #15261

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
Backport in https://github.com/nextcloud/server/pull/16010

**Pull request merged**
