### PR TITLE
remove leading slash

### PR DESCRIPTION
**Pull request by ArtificialOwl**
follow up of https://github.com/nextcloud/server/issues/40794

This will make the redirection works also on nextcloud installed in a subfolder.
Tested on 2 subfolder instances. Can confirm federated sharing works the same _pre-ocm-rewrite_ way

### CODE REVIEW

**Comment by ArtificialOwl** [comment]
(backport will be manual)

**Review by nfebe — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]

**Comment by blizzz** [comment]
the backport to stable27 should work, for stable26 we need to merge https://github.com/nextcloud/server/pull/40781

**Pull request merged**
