### PR TITLE
Fix pagination of contacts search

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up for #20720

### CODE REVIEW

**Comment by tacruc** [comment]
Are there not tests for this backend, which could be adapted?

**Comment by nickvergessen** [comment]
There are tests and they still work :sunglasses: 

But yeah, I guess I could add a test with 5 users and use a limit and offset of 1 e.g.

**Comment by nickvergessen** [comment]
Tests added @tacruc

**Review by tacruc — APPROVED** [review]
LGTM

**Review by J0WI — APPROVED** [review]

**Comment by nickvergessen** [comment]
Rebased and squashed

**Pull request merged**
