### PR TITLE
refactor(apps): Use constructor property promotion when possible

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

Done with rector. Maybe this PR is a bit too big, I can make separate PRs for individual apps if needed.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Checked apps/dav and some other random samples. Can't see any issues

**Comment by nickvergessen** [comment]
In terms of backporting I'm a fan of not doing it, unless it's touched anyway :see_no_evil: 
But of course clean code is also fine and resolving the conflict should be doable

**Comment by provokateurin** [comment]
I would not backport this, I tried to apply it locally and there are too many conflicts that are not worth spending the time on.

**Comment by nickvergessen** [comment]
- Psalm has some comments
- the one thing I wonder is in some cases we type hint the member to an actual implementation, while the injection is done with the public interface, because not all methods are in the public interface. Of course I don't know a place out of my head, but do you know how it handles that?

**Comment by provokateurin** [comment]
As far as I can tell it just removes the property and adds the promotion in the constructor. That means if the injection uses the interface we will also use that internally. Judging from the failed tests and the psalm results this doesn't seem to cause problems with every used method already being in the interface (which is really good :tada:)

**Comment by provokateurin** [comment]
Only problem I found was where the property was called `uid` which was then renamed in the constructor as well, so it was no longer `userId` and could not be resolved.

**Review by andrey18106 — APPROVED** [review]

**Comment by danxuliu** [comment]
> Only problem I found was where the property was called `uid` which was then renamed in the constructor as well, so it was no longer `userId` and could not be resolved.

_Security_ section in _Personal_ settings is no longer shown with this pull request due to that. It needs to be fixed too in:
- [apps/settings/lib/Settings/Personal/Security/Authtokens.php](https://github.com/nextcloud/server/pull/48790/files#diff-26613b2516b49923dc1192f2790b5d6790451a179d6e6053aa6806661e6bf246L48)
- [apps/settings/lib/Settings/Personal/Security/Password.php](https://github.com/nextcloud/server/pull/48790/files#diff-8d2c77f33a08fcf0c4a9196ff1d15cbdb748e09f67a038c6c95df7b8fa5887deL26)
- [apps/settings/lib/Settings/Personal/Security/TwoFactor.php](https://github.com/nextcloud/server/pull/48790/files#diff-30d73ec621c9e1e40d58fdcd3b0e8777841a8dcb32421b3d9688351d694029eaL50)
- [apps/settings/lib/Settings/Personal/Security/WebAuthn.php](https://github.com/nextcloud/server/pull/48790/files#diff-207fb3a68720813e9cbb6553f97af292939d7863e67d10d7ee7610492b44ccb3L37)

**Comment by provokateurin** [comment]
@danxuliu thanks for letting me know, I'll make a PR tomorrow to fix it.

**Pull request merged**
