### PR TITLE
Enh/unified search

### LINKED ISSUE #9917: Unified search introduction
Since the implementation of the ISearch component, apps have the possibility to add their search provider classes to our instance. One of the downside is the way it's been implemented. 
Currently the script is looking for a specific div id on the page and IFF it's present the global search is enabled and added into this div.

That means if I add this div on the contacts app, for example, I will be able to search the FileSearchProvider on the contacts page... Which is a nonsense.

## Changes
- With the new standard on #9912 we can register per-app javascript search handler.
- This should stay this way. Search on the top right header need to stay this way.
- In the meantime, the idea of a global search is great. I'm suggesting adding this for the whole instance with a popup similar to the contactsmenu.

### PR DESCRIPTION
**Pull request by skjnldsv**
| a | b |
|:---------:|:------:|
|Capture d’écran_2020-07-28_16-44-53|Capture d’écran_2020-07-28_16-44-37|

## API changes
``GET https://cloud.domain/search/providers``

Now returns a structure like

```js
    [
        { id: 'files', name: 'Files' },
        { id: 'mails', name: 'Mails' },
    ]
```

## Issues
- [x] Open & focus with ctrl+f
- [x] Auto-focus first result
- [x] No results EmptyContent
- [x] Whole row clickable
- [ ] Open in new tab
- [ ] Shift header menu a bit to the right

## Questions
- Do we need an indicator to display when we reached the end
- How do we sort the results types? Alphabetically?

### CODE REVIEW

**Comment by nickvergessen** [comment]
As for sorting, maybe the current app could be preferred somehow? So in talk Talk results, on files the file results, etc

**Comment by jancborchardt** [comment]
@nickvergessen absolutely, good call! :) We even discussed that for apps which don’t have their own in-app search (like Talk), this way they don’t even have to implement their own search but only hook into the unified search.

**Comment by raimund-schluessler** [comment]
> As for sorting, maybe the current app could be preferred somehow? So in talk Talk results, on files the file results, etc

For the rest of the apps, I would propose the app order as it is shown in the header (but with current app first ofc.).

**Comment by skjnldsv** [comment]
Notes from the call:
- [] Coordinate with developers of the apps which currently have search → @mention them on the issue and invite them to this channel and a call to help them port
- [] First result should open on pressing enter
- [] Sort results of currently active app first
- [] Highlight/bold the part in the results list which is a fit
- [x When searching for folder "Earth", instead of subline "/Photos/Space/Earth" say "in Photos/Space" (but still show the whole item path as subline for Comment results)
- [x] Show folder icons and filetype icons → possibly needs adjustment in the API
- [x] Similar: Comments needs avatar = round, filetypes rounded off. Possibly directly in API.
- [x] Show avatar of person for comment results
- [] Alignment further to the right
- [x] Action icon can go away with whole area being clickable
- [x] Load more results can be color-text-maxcontrast, and remove arrow
- [] Check on accessibility
- [] Ellipsize the search input placeholder
- [] Check the additional filters feature, interface for the "in:files" etc

Stuff for future iterations:
- [] Suggestions as emptycontent e.g. pre-filters
- [] Ref "sort results of currently active app first" – if it’s well integrated, maybe apps don’t even need their own search in the AppNavigation at all
- [] See how unified search relates to the Contacts menu (depending on how we improve the Contacts menu)

**Comment by skjnldsv** [comment]
Failures seems unrelated!

**Review by georgehrke — DISMISSED** [review]
79AC6EA9-2D66-46D2-A2A4-8064478D21CC

The search icon should remain white even in dark mode.

**Comment by nickvergessen** [comment]
When you set the theming color to `#FFFFFF` and `#181818` respectively the section headers are invisible on bright/dark theme.

**Comment by georgehrke** [comment]
An icon size of 44x44 pixels looks a bit big for me:
1AD2DAB9-307C-4063-89AF-0C6395D41EE0

**Comment by marcelklehr** [comment]
Bookmarks has its own search currently. Any recommendations on how this should be handled?

**Comment by skjnldsv** [comment]
> ### Status of [31299](https://drone.nextcloud.com/nextcloud/server/31299): failure
> #### jsunit

```
curl: (7) Failed to connect to codecov.io port 443: Connection timed out
```


This is a false negative, we can get this in

**Review by nickvergessen — APPROVED** [review]
:shark: Bite by bite

**Review by georgehrke — APPROVED** [review]
Très Bien

**Comment by raimund-schluessler** [comment]
Will there be a migration guide or anything for apps which use the old search already (forgive me if I missed the answer to that)?

**Comment by skjnldsv** [comment]
> Will there be a migration guide or anything for apps which use the old search already (forgive me if I missed the answer to that)?

Yes, there is a documentation start in https://github.com/nextcloud/documentation/pull/2166
And I'm planning to extend it right after this is done :)

**Comment by skjnldsv** [comment]
BTW: this pr got wrongly merged. I failed the rebase it seems
Fix is in https://github.com/nextcloud/server/pull/22088

**Pull request merged**
