### PR TITLE
fix - Add to favorites not working in IE11 - polyfill needed #12007

### PR DESCRIPTION
**Pull request by z0iberg**
Fix issue that has @Req. This commit was proposed by @Req, but he doesn't make this commit.
https://github.com/nextcloud/server/issues/12007#issuecomment-432546085

### CODE REVIEW

**Comment by violoncelloch** [comment]
consider https://github.com/nextcloud/server/issues/12007#issuecomment-433692285 by @Req before merging this

**Comment by juliushaertl** [comment]
I would rather vote to add a more complete ES6 polyfill or fix the occurenced of `startsWith`. Probably the first one would be nice, since it would make developing plain js code a bit easier in the future. IE11 seems to be the only browser that would still need those polyfills.

https://github.com/paulmillr/es6-shim might be an oppinion. We currently already have a es6-promise polyfill (which is included unminified and has about 32kb) es6-shim has a minified size of 55kb. cc @nextcloud/javascript

**Comment by juliushaertl** [comment]
As discussed I've created a pr to add es6-shim in #12317 however for backporting, i would just use the startsWith polyfill from this PR to keep the stable branches clean from the dependency change. cc @nextcloud/javascript

**Comment by MorrisJobke** [comment]
@juliushaertl Didn't we want to backport this one to stable14?

**Comment by juliushaertl** [comment]
@MorrisJobke Backport of this in https://github.com/nextcloud/server/pull/12339

**Pull request closed without merging**
