### PR TITLE
Update config.sample.php

### LINKED ISSUE #21674: occ maintenance:install fails when Postgres is socket-only
### Steps to reproduce
1. Prepare s/w per Linux installations instructions with Postgres using a local socket only (port access is disabled)
2. Try to install NC using sudo -u www-data php occ maintenance:install --database=pgsql --database-name=...  --database-user=... --database-pass=...  --admin-user=... --admin-pass=... --database- host='localhost:/run/postgresql/.s.PGSQL.5432' 
3. Error message: SQLSTATE[08006] [7] could not connect to server: Connection refused
4. --database-host points to PG socket directory,  pg_hba.conf is set up correctly as psql connection works with same credentials
5: If port access is enabled on 5432, occ installation works.

### Expected behaviour
Tell us what should happen
Nextcloud should install w/o error

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**
Debian Buster on amd64
**Web server:**
Apache 2.4.38

**Database:**
PostgreSQL 11.7
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
19
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
zip archive

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
HTTPS
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by JensTimmerman**
fixes nextcloud/server#21674

### CODE REVIEW

**Review by mteam88 — APPROVED** [review]
This does seem to help clarity.

**Review by szaimen — APPROVED** [review]
LGTM

**Comment by MichaIng** [comment]
`/run/postgresql/` is definitely correct on Debian and Ubuntu 👍. The trailing slash can be omitted, though.

**Review by MichaIng — APPROVED** [review]

**Comment by mteam88** [comment]
@JensTimmerman 
Please fix DCO.

**Pull request merged**
