### PR TITLE
Add support for `\OCP\Share\IShare::getMailSend` back

### PR DESCRIPTION
**Pull request by LukasReschke**
This adds back the support for `\OCP\Share\IShare::getMailSend`, one example is creating bulk shares via API which where previously blocking due to the share notification emails.

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Any change we can add tests for this?

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Please have a look at the failing integration test. Looks 🐟y because only one of many tests has a different value for mail_send

**Comment by MorrisJobke** [comment]
Rebased to fix CI hiccup.

**Comment by MorrisJobke** [comment]
Weird failure in the integration tests (but only one occurence):

```
FederationContext::checkShareFields()
      | id                     | A_NUMBER           |
      | item_type              | file               |
      | item_source            | A_NUMBER           |
      | share_type             | 0                  |
      | file_source            | A_NUMBER           |
      | path                   | /textfile0 (2).txt |
      | permissions            | 19                 |
      | stime                  | A_NUMBER           |
      | storage                | A_NUMBER           |
      | mail_send              | 0                  |
      | uid_owner              | user1              |
      | file_parent            | A_NUMBER           |
      | displayname_owner      | user1              |
      | share_with             | user2              |
      | share_with_displayname | user2              |
      mail_send doesn't have value 0
```

**Comment by MorrisJobke** [comment]
I fixed the integration test.

**Comment by MorrisJobke** [comment]
> Weird failure in the integration tests (but only one occurence):

It was not weird - I just misread it. 🙈

**Comment by MorrisJobke** [comment]
@LukasReschke Said that it is fine like that. Merging.

**Pull request merged**
