### PR TITLE
Show "Uploading..." in web UI for long uploads

### PR DESCRIPTION
**Pull request by MorrisJobke**
If the estimated upload time is bigger than 4 hours it shows the text "Uploading..." because the time then doesn't give any good hint to the user anyways.

cc @oparoz

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by oparoz** [comment]
Simple enough fix :) 👍

**Review by danxuliu — APPROVED** [review]

**Comment by oparoz** [comment]
One thing to check though is that the blue bar gets filled and doesn't drop back to a small value.

**Review by jancborchardt — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> One thing to check though is that the blue bar gets filled and doesn't drop back to a small value.

Will fix in a separate PR.

**Comment by MorrisJobke** [comment]
Because @jancborchardt asked for it: I added a commit to replace the ... with … (ellipsis), but will not backport this to stable12.

**Pull request merged**
