### PR TITLE
update icewind/smb to 1.1.2

### PR DESCRIPTION
**Pull request by icewind1991**
- depend on `stdbuf` in less cases
- explicitly check if the `smbclient` binary is available
- misc code improvements

cc @MorrisJobke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Tests failing?

**Comment by icewind1991** [comment]
> Tests failing?

All fixed

**Comment by icewind1991** [comment]
> All fixed

Ignore the postgres build timing out :see_no_evil:

**Comment by LukasReschke** [comment]
@icewind1991 Can we move that to 12? I'd prefer to consider 11 closed for any non-critical merges.

**Comment by icewind1991** [comment]
Sure

**Comment by icewind1991** [comment]
Superseded by #2676

**Pull request closed without merging**
