### PR TITLE
fix(events): Log deprecated events as debug, not info

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Ref https://github.com/nextcloud/server/issues/24380

## Summary

There is nothing an admin can. So let's not log this with info level.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Chartman123 — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
Great idea! :)

**Comment by szaimen** [comment]
backports?

**Comment by ChristophWurst** [comment]
Trigger them if you think they are save and necessary. I am hesitant with this type of change.

**Comment by szaimen** [comment]
All right, fine for me to leave it like this for now 👍

**Pull request merged**
