### PR TITLE
Fix #2408

### LINKED ISSUE #2408: Cannot select last item in file picker
The last item in the file picker file list is overlapped by a white gradient and therefore not selectable.

You can see the gradient on the folder icon here:
bildschirmfoto von 2016-11-29 16-58-56
(resized the window to have a shorter list)

cc @icewind1991 @skjnldsv

### PR DESCRIPTION
**Pull request by skjnldsv**
Checked with ff and chrome.

@ChristophWurst

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Still looks a lot different on FF and Chrome

bildschirmfoto von 2016-11-29 17-46-05

I can even unset the padding-bottom on FF and it looks the same :-/

**Comment by skjnldsv** [comment]
Looks good here
can't do much abou tthe ugly scrollbar though.
capture d ecran_2016-11-29_17-54-28
capture d ecran_2016-11-29_17-54-35

**Comment by ChristophWurst** [comment]
👍

**Comment by icewind1991** [comment]
:+1:

**Comment by LukasReschke** [comment]
@skjnldsv Commits are not signed-off 😉

**Comment by skjnldsv** [comment]
Tsss :)

**Pull request merged**
