### PR TITLE
Init fileinfo for all tabs

### LINKED ISSUE #21239: [Updating to 18.0.5.] The document does not display versions, comments, events. (Sidebar)
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
After updating to 18.0.5 version. 

### Expected behaviour
The document should display versions, comments, events.

### Actual behaviour
The document does not display versions, comments, events. (sidebar)

### Server configuration

**Operating system: Ubuntu 18.04**

**Web server:*Apache 2. *

**Database:*PostgreSQL 10.12*

**PHP version:*PHP 7.2.24.*

**18.0.5** (see Nextcloud admin page)

**18.0.4**

### PR DESCRIPTION
**Pull request by skjnldsv**
After https://github.com/nextcloud/server/pull/20564

No idea why this works on master, reactivity seems to behave better.
Anyway, it works now™

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by kklem0 — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Review by kesselb — APPROVED** [review]
Works for me.

**Comment by go2sh** [comment]
[This commit](https://github.com/nextcloud/nextcloud-vue/commit/765dc82116221ba3005e8bba1b388d417fa637c0) is the reason, why it works on master an stable19. As I said old nextcloud-vue version...

**Comment by clementhk** [comment]
> [This commit](https://github.com/nextcloud/nextcloud-vue/commit/765dc82116221ba3005e8bba1b388d417fa637c0) is the reason, why it works on master an stable19. As I said old nextcloud-vue version...

Just to make sure, it commit was also in stable18 as https://github.com/nextcloud/nextcloud-vue/commit/ee1826970eae76a6f8511f8e13f51a28f03e4648, but I'm probably missing something.

**Review by go2sh — APPROVED** [review]
Tested on an freshly checkout instance of the branche and activity app. Fixes both the old issue and my regression. Sorry for that...

**Comment by go2sh** [comment]
@clementhk Hmm okay, maybe you are right. I just saw during my debugging, that the watched `fileProp` function I use, was not part of the actualy `fileProp` object watcher list and so the loaded `fileProp` did not propagate to the tabs :(

**Comment by clementhk** [comment]
> @clementhk Hmm okay, maybe you are right. I just saw during my debugging, that the watched `fileProp` function I use, was not part of the actualy `fileProp` object watcher list and so the loaded `fileProp` did not propagate to the tabs :(

So if we can confirm that stable19/master actually work and don't need porting, we could either just go with this (everything works for me so I guess no harm there) or we could try to find out which commit made stable19/master work and backport it to keep consistency?

**Pull request merged**
