### PR TITLE
Improve mention matches

### PR DESCRIPTION
**Pull request by nickvergessen**
The previous regex didn't correctly match users with . ' or -

Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/pull/5041

**Review by danxuliu — COMMENTED** [review]
Tested and notifications when a comment is something like `Hi @user0 and @user0-2` now work :+1: 

Mentioning a user using quotes does not work, though. But id did not work before even for users with spaces in the name (`Hello @"&quot;user0 1&quot;"` is shown in the comment), so it might be something for a different pull request.

**Edit:** clarification, it does not work when rendered in the comments app. But it does in the notification.

**Review by danxuliu — APPROVED** [review]

**Comment by rullzer** [comment]
Linter says no

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Master is Nextcloud 22 now.
If this should go into 21 it should be backported.

**Pull request merged**
