### PR TITLE
Detect weird local ips

### PR DESCRIPTION
**Pull request by come-nc**
Use new dependency to detect weird syntaxes

- [x] https://github.com/nextcloud/3rdparty/pull/1173
- [x] rebase

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks for taking care :+1: 

In theory we can drop the iputils (symfony http-foundation) again and only use the ip-lib package: https://github.com/mlocati/ip-lib#check-if-an-address-is-contained-in-a-range

This could also help with https://github.com/nextcloud/server/issues/33567

**Comment by come-nc** [comment]
> Thanks for taking care +1
> 
> In theory we can drop the iputils (symfony http-foundation) again and only use the ip-lib package: https://github.com/mlocati/ip-lib#check-if-an-address-is-contained-in-a-range
> 
> This could also help with #33567

Hum but I trust the range detection in symfony more, especially it correctly tests ipv6 in ipv4 ranges, which ip-lib does not.
But as our code translates the IP to v4 if it maps, maybe it is not a problem.

**Comment by come-nc** [comment]
@kesselb I can make a PR to use ip-lib instead of iputils but I’d like to do so in a separate PR once this one is merged.

**Comment by nickvergessen** [comment]
3rdparty merged

**Review by nickvergessen — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
