### PR TITLE
feat(sharebymail): improve share email format

### LINKED ISSUE #15680: Add expiration date on sharing notification mail
When the first share notification mail is sent, it would be nice to have the expiration date on it.

### PR DESCRIPTION
**Pull request by skjnldsv**
|Before|After|
|:---:|:---:|
|image|image|

As discussed:
1. Removed `»` and `«`
2. Add expiration
3. Improve layout

Fix https://github.com/nextcloud/server/issues/15680
cc @jancborchardt @nimishavijay @marcoambrosini

### CODE REVIEW

**Comment by szaimen** [comment]
I just looked at the after screenshot and I was wondering if technically these elements could be bold? 
image

Also, the button on the bottom should probably have the same border-radius that we are useing in Nextcloud for buttons?

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
> I just looked at the after screenshot and I was wondering if technically these elements could be bold?

- For `Note` and `Expiration`, the place to fix it is [here](https://github.com/nextcloud/server/blob/693a81bfa367089de4b61ee1ea104c85e6bc6d1c/lib/private/Mail/EMailTemplate.php#L437). This will change for all apps using our email templating (like calendar events) 
image
 
For the folder title, that would be nice, but it's not supported for now.
We don't support custom html. We could add some custom support like `**` to convert to bold during the template processing.
But I'd say this is something for 31 or later

**Comment by skjnldsv** [comment]
> Also, the button on the bottom should probably have the same border-radius that we are useing in Nextcloud for buttons?

This is an issue older than internet :see_no_evil: 
Not all email clients support border radius. :exploding_head: 
Maybe things changed since, but that was the reason this is not possible :see_no_evil:

**Comment by szaimen** [comment]
> > Also, the button on the bottom should probably have the same border-radius that we are useing in Nextcloud for buttons?
> 
> This is an issue older than internet 😁 Not all email clients support border radius. 🤯 Maybe things changed since, but that was the reason this is not possible 🙈
> 
> EDIT: nope, still the case ahahah https://www.caniemail.com/features/css-border-radius/

OMG 🙈

**Comment by skjnldsv** [comment]
Addressed the border radius, see first post

**Review by nimishavijay — APPROVED** [review]
Super nice! Very cool that the buttons are rounded now :) 

All looks good, only small change I would suggest is to remove the message in gray at the bottom "X shared Y with you. Click the button below to open it." as it seems redundant now :) 

Approving to not block

**Review by sorbaugh — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Pull request merged**
