### PR TITLE
Added IPv6 example

### LINKED ISSUE #19597: IPV6 Trusted Domain Not Recognized with any settings including wildcards
/var/www/nextcloud/config/config.php
array ('::1', '[::1]','5555:*', '[5555:asterisk],'[asterisk]','[asterisk:asterisk],'asterisk',),

(* wont show properly here on github, so I put asterisk)
I found my IPV6 from ip6only.me , tried the whole address inside [] and without.(5555 just an example, _not_ my real IP)
Still get error webpage
"Access through untrusted domain"
What is the proper format to allow all IPV6?
Documentation is not clear at all about IPV6

### PR DESCRIPTION
**Pull request by sndrr**
Closes #19597 

Signed-off-by: Sander Ruitenbeek <sander@getgoing.nl>

### CODE REVIEW

**Comment by sndrr** [comment]
This closes #19597

**Review by kesselb — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by Starbix** [comment]
According to RFC5952 the text representation of an IPv6 address `MUST` be lowercase: https://tools.ietf.org/html/rfc5952#section-4.3

**Comment by sndrr** [comment]
@Starbix I took the IPv6 documentation prefix from [RFC 3849 section 4](https://tools.ietf.org/html/rfc3849#section-4), but thanks for the catch. I will update the PR.

**Review by Starbix — CHANGES_REQUESTED** [review]
@sndrr The documentation-only prefix is actually 2001:db8::/32, not 2001:dbb::/32. And it looks like you added a `t` by mistake.

**Comment by sndrr** [comment]
@Starbix You are correct. The capital B and 8 look alike. I've corrected the faults.

**Review by georgehrke — APPROVED** [review]

**Comment by rullzer** [comment]
@sndrr good stuff thanks
Could you squash all your commits into 1?

**Comment by ChristophWurst** [comment]
@sndrr some help with squashing: https://davidwalsh.name/squash-commits-git :)

**Comment by sndrr** [comment]
@ChristophWurst Thanks! It should be one commit now.

**Pull request merged**
