### PR TITLE
Add activities when email or password is changed

### PR DESCRIPTION
**Pull request by nickvergessen**
> bildschirmfoto vom 2017-04-12 15-22-39

Administrator Of Localhost changed your email => Admin settings
You changed your email => Personal settings
Your password was reset by an administrator => console
Administrator Of Localhost changed your password => Admin settings
You changed your password => Personal settings

### CODE REVIEW

**Comment by nickvergessen** [comment]
We could also sent emails for those events. But on email change I'm not sure where we should send the mail to, new/old/both

**Comment by schiessle** [comment]
I think it would make most sense to send a mail to the old address so that people notice if the mail address changed unintended.

Sending to the new address would only make sense if we would have some kind of activate-link to verify the new address.

**Comment by rullzer** [comment]
We should send e-mails yes. But that is not the job of the activity app IMO. This is a basic security thing we need to add :wink:

**Comment by nickvergessen** [comment]
Added emails for both cases 
bildschirmfoto vom 2017-04-13 12-31-21

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Also the emails look really nice 👍

**Review by rullzer — APPROVED** [review]
I like it!

**Pull request merged**
