### PR TITLE
Actually set the TTL on redis set

### PR DESCRIPTION
**Pull request by rullzer**
Else well the keys remain for ever and ever.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by PVince81** [comment]
was wondering why we can't use setex as well, found this but not sure: https://www.reddit.com/r/redis/comments/8suupj/expire_option_for_setnx_command/

maybe PHP doesn't have a mapping

**Comment by PVince81** [comment]
from the docs:
```
// Will set the key, if it doesn't exist, with a ttl of 10 seconds
$redis->set('key', 'value', ['nx', 'ex'=>10]);
```
see https://github.com/phpredis/phpredis

**Comment by rullzer** [comment]
> was wondering why we can't use setex as well, found this but not sure: https://www.reddit.com/r/redis/comments/8suupj/expire_option_for_setnx_command/
> 
> maybe PHP doesn't have a mapping

Yeah well it is not in the docs of phpredis.
Also I think setEx doesn't care if the key already exists.

This was the cleanest I could come up with for now ;)

**Comment by rullzer** [comment]
> from the docs:
> 
> ```
> // Will set the key, if it doesn't exist, with a ttl of 10 seconds
> $redis->set('key', 'value', ['nx', 'ex'=>10]);
> ```
> 
> see https://github.com/phpredis/phpredis

aaah that would be fine as well of course

**Comment by rullzer** [comment]
See the fixup for review

**Review by PVince81 — APPROVED** [review]
Code looks fine, not tested :+1:

**Review by ChristophWurst — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
