### PR TITLE
Rewrite admin theming in Vue

### PR DESCRIPTION
**Pull request by Pytal**
image

Move away from the legacy PHP implementation to improve UX parity for user and admin theming + enhance accessibility

- [x] Fix background preview showing user background
- [x] Fix unable to set plain background and usage on login page

### Requires

- [x] https://github.com/nextcloud/nextcloud-vue/pull/3324
- [x] https://github.com/nextcloud/nextcloud-vue/pull/3323
- [x] https://github.com/nextcloud/nextcloud-vue/pull/3336
- [x] https://github.com/nextcloud/server/pull/34437

<details>
<summary>Before</summary>

image

</details>

### CODE REVIEW

**Comment by Pytal** [comment]
Keeping as draft until required PRs are in

**Comment by blizzz** [comment]
master is 26

**Comment by Pytal** [comment]
Are the accessibility and UX enhancements here still go for 25 @PVince81 @skjnldsv? If so then let's get this in and add https://github.com/nextcloud/server/pull/34576 in Vue ontop

Or if 26, then https://github.com/nextcloud/server/pull/34576 can go in without this

**Comment by skjnldsv** [comment]
> Are the accessibility and UX enhancements here still go for 25 @PVince81 @skjnldsv? If so then let's get this in and add #34576 in Vue ontop
> 
> Or if 26, then #34576 can go in without this

I would say this.

#34576 is minimal and can go for 25
#34359 is a bit too much and should stay for 26

**Comment by Pytal** [comment]
Slated for 26

**Comment by PVince81** [comment]
@Pytal accessibility needs to go into NC 25 still

**Comment by Pytal** [comment]
Rebased and incorporated latest changes + updated screenshots

**Review by PVince81 — APPROVED** [review]
:+1: went through it with @Pytal

**Comment by szaimen** [comment]
@jancborchardt I have the feeling that the text fields are too long bases on the screenshot. Wdyt?

**Comment by skjnldsv** [comment]
@szaimen no, but the input were set to `width: 230px;`

**Review by artonge — APPROVED** [review]

**Comment by szaimen** [comment]
Drone failure related

**Comment by Pytal** [comment]
> @jancborchardt I have the feeling that the text fields are too long bases on the screenshot. Wdyt?

Text fields have been set to `max-width: 400px` (updated screenshot) like in https://github.com/nextcloud/server/blob/c723daaa561f621496a416e20a7988727303580c/apps/settings/src/components/PasswordSection.vue#L96 and other settings

> @Pytal @CarlSchwan wasnt there a max element widht applied to all settings sections automatically?
> > @szaimen no, but the input were set to `width: 230px;`

Yes `900px` was for the entire settings section in https://github.com/nextcloud/nextcloud-vue/pull/3192, `230px` was specifically for these inputs

**Comment by Pytal** [comment]
⚠ Do not merge until the https://github.com/nextcloud/nextcloud-vue additions (undo icon and maxlength attribute) are available on server

**Comment by skjnldsv** [comment]
I would prefer to merge and wait for the next vue version, or else we'll keep rebasing this PR over and over :(

**Comment by szaimen** [comment]
> I would prefer to merge and wait for the next vue version, or else we'll keep rebasing this PR over and over :(

+1

**Comment by skjnldsv** [comment]
We said no backports in the end iirc :)

**Pull request merged**
