### PR TITLE
l10n: Unify spelling

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Nextcloud applications.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Review by rakekniven — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by Valdnet** [comment]
@MorrisJobke Can you approve and merge?

**Comment by MorrisJobke** [comment]
There are merge conflicts.

**Comment by Valdnet** [comment]
@MorrisJobke Thanks for the help 😉.

**Pull request merged**
