### PR TITLE
Fix sharing panel lighthouse warnings

### PR DESCRIPTION
**Pull request by PVince81**
Replaced h5 with span and adjusted selectors.
Fixed ul/li hierarchy of some elements.

Found by running the Lighthouse chromium tool in snapshot mode while having the share panel open AND the link share dropdown

### CODE REVIEW

**Comment by PVince81** [comment]
I tried using the exact same versions of node and npm like CI and there's no difference.
Also in parallel I had a PR to document the versions to use: https://github.com/nextcloud/server/pull/33322

**Comment by PVince81** [comment]
- [ ] next attempt: try with a clean env

(and yes I can summon the bot but now I'm really tired that every PR doesn't match expectations)

**Comment by PVince81** [comment]
even with a fresh clone I get the same result as the previous commit...

**Comment by PVince81** [comment]
ah, so it's the icons: dist/icons.css

I thought we added a step to build it as part of "make build-js-production"

**Comment by PVince81** [comment]
alright... need to finish https://github.com/nextcloud/server/pull/32753

**Review by Pytal — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Pull request merged**
