### PR TITLE
Multiselect line-height fix

### PR DESCRIPTION
**Pull request by skjnldsv**
There is no small pull requests :grin: 
Look at the line height :mag: 

|Before|After|
|:--:|:--:|
|capture d ecran_2018-09-24_22-54-43|capture d ecran_2018-09-24_22-54-37|

@nextcloud/designers

### CODE REVIEW

**Comment by nickvergessen** [comment]
The workflow and access control selections look still off.

**Comment by skjnldsv** [comment]
@nickvergessen the workflow doesn't use the multiselect.

**Review by MorrisJobke — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Pull request merged**
