### PR TITLE
25.0.0 RC3

### PR DESCRIPTION
**Pull request by blizzz**
* #34332
* #34335
* #34337
* #34340
* #34354
* #34356
* #34357
* #34365
* #34367
* #34370
* #34371
* #34373
* #34374
* #34380
* #34382
* #34405
* #34408
* #34409
* #34413
* #34432
* #34434
* nextcloud/activity#944
* nextcloud/circles#1171
* nextcloud/firstrunwizard#755
* nextcloud/nextcloud_announcements#116
* nextcloud/notifications#1299
* nextcloud/photos#1309
* nextcloud/recommendations#551
* nextcloud/related_resources#64
* nextcloud/text#3072
* nextcloud/text#3073
* nextcloud/text#3116
* nextcloud/text#3118
* nextcloud/text#3119
* nextcloud/text#3120
* nextcloud/text#3122
* nextcloud/text#3124
* nextcloud/viewer#1393
* nextcloud/viewer#1398

Pending PRs:

* [ ] #34359 @Pytal
* [ ] #34446 
* [ ] nextcloud/suspicious_login#708 @ChristophWurst

### CODE REVIEW

**Comment by szaimen** [comment]
I guess this should go in before? https://github.com/nextcloud/server/pull/34298

**Comment by blizzz** [comment]
> I guess this should go in before? #34298

better it gets green checkmarks sonner :)

**Review by AndyScherzinger — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
I guess it would be cool to get this in before: https://github.com/nextcloud/server/pull/34437. however I don't feel like it is ready yet...

**Comment by blizzz** [comment]
> I guess it would be cool to get this in before: #34437. however I don't feel like it is ready yet...

This will be for RC 4 then.

**Pull request merged**
