### PR TITLE
Adjust the design to Nextcloud

### PR DESCRIPTION
**Pull request by jancborchardt**
Check it out @nextcloud/designers! cc @karlitschek @jospoortvliet – did I miss anything? I’ll prepare the backport as soon as this is in.
design-files
design-login

Everything looks much nicer with the brighter blue, way more friendly.

(Credit to @ChristophWurst for the background change inspiration. :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
The only thing which isn’t bright yet is the apps menu. The reason being that all apps icons are bright and it would take considerable effort to change this. We need to check that out for Nextcloud 10.

**Comment by nbebout** [comment]
+1 I think it looks very nice

**Comment by karlitschek** [comment]
nice 👍

**Comment by LukasReschke** [comment]
🚀 👍

**Comment by elioqoshi** [comment]
@jancborchardt I like it so far! Can you provide us with the source files so we can tinker a bit as well?

**Comment by mar1u5** [comment]
I love it :+1:

**Comment by mar1u5** [comment]
Many thumbs up - All checks passed - Merged! THIS IS NEXTCLOUD 🚀

**Comment by mar1u5** [comment]
Just uploaded your screenshots as initial commits for `nextcloud/screenshots` 😉

**Comment by oparoz** [comment]
There is a problem with the light blue on medium blue text in the header, it's barely readable. cc @BernhardPosselt

**Comment by mar1u5** [comment]
:confused: ... Maybe we can make the font bigger :stuck_out_tongue_winking_eye: @oparoz

**Comment by oparoz** [comment]
Either "brighter" or thicker I think.

**Comment by bes1002t** [comment]
mh would suggest a small shadow under your toolbar.

**Comment by mikebabb** [comment]
Beautiful! Looking really nice 👍

I'm on my phone at the moment so I can't check it out in detail, but I do find the font weight in ownCloud to be a little too light. In Nextcloud could we perhaps make it a little heavier, or increase the font size ever so slightly to compensate for the light weight and aid readability?

**Comment by Bugsbane** [comment]
I like it, too. I agree with the lighter blue being friendlier. Right now the size of the Nextcloud logo on the menu bar seems just a touch large, drawing a bit more attention than I would choose, but not by a huge amount. Overall, it looks great. May I also add, that I found the ownCloud icon to be quite... suboptimal.  The Nextcloud icon is so very much cleaner, more minimal and beautiful for it. Together this all looks very nice.

**Comment by DamirRT** [comment]
yeah :+1:

**Comment by elioqoshi** [comment]
@jancborchardt under what license will the photo be available btw?

**Comment by Bugsbane** [comment]
@elioqoshi - I don't personally know, but I believe other graphic assets are licensed under CC BY-SA iirc...

**Comment by ldonis** [comment]
I really like it!!

**Comment by jancborchardt** [comment]
@elioqoshi all the software is AGPLv3 (AGPLv3 or later for newer files) and any assets which can not be covered by that are Creative Commons Attribution Share-Alike indeed.

**Comment by jancborchardt** [comment]
@oparoz regarding the font contrast in the header, I’m thinking of making it white by default, and light greyish on hover/focus. Currently it’s the other way around and that causes the contrast to be lower.

**Comment by jancborchardt** [comment]
@bes1002t we had the shadow in older releases but we decided to remove it because it just looked odd and outdated. It’s much cleaner that way.
Similarly there is no need for even/odd list coloring since the vertical whitespace already distinguishes the entries a whole lot without looking like 1990's list design. ;)

**Comment by jancborchardt** [comment]
@Bugsbane haha, yes – the logo was designed to be much simpler and friendly also to reflect the ease of use and approachability of the software, even though it is complex and powerful. Glad to hear we achieved that. :)

**Comment by vincchan** [comment]
@jancborchardt great job, I like it :) 👍

**Comment by zhaofengli** [comment]
Wow. This is pure awesomeness.

**Comment by bes1002t** [comment]
@jancborchardt I disagree imho it looks not outdated because many websites and the whole android universe is using this shadow. Even our discussion board http://help.nextcloud.com does!

But I totally agree that the even and odd colouring of lists is something we could omit :P

**Comment by erikkn** [comment]
It's nice, but why don't change the whole design? Now it's a look a like of OC (which I understand) but a new project/company should have a new design in my opinion.

**Comment by bes1002t** [comment]
@erikkn I think that design is soo simple, you can not change many things. You have a toolbar, a navigationbar and a list of files. Just details could be changed like the position of that add button next to the breadcrumb.

**Comment by jancborchardt** [comment]
@erikkn some reasons:
- We want people to be able to easily upgrade from ownCloud to Nextcloud.
- Other themes should still work.
- Apps should still look good.
- Also, I was the design lead at ownCloud (now Nextcloud) and stuff was designed like that for a reason. Change for the sake of change does not make a lot of sense.

There’s definitely design improvements I have in mind and which are also open as issues since some time (in the old repo of course at this point), and they will come in as people implement them. :) As always I am very happy to work with anyone who is also up for actually realizing some interface improvements.

**Comment by erikkn** [comment]
@jancborchardt & @bes1002t ,, those are good arguments, I never thought about the existing apps. @jancborchardt I'll look forward to your improvements ideas.

**Comment by oparoz** [comment]
The good news is that we can still write our own themes :)

**Comment by Bugsbane** [comment]
> As always I am very happy to work with anyone who is also up for actually realizing some interface improvements.

I always enjoy turning ideas into a good UI mockup etc. so the question is... what issue do we start with?

**Comment by mar1u5** [comment]
You are welcome on our IRC #nextcloud-design where we can talk about that :wink:

**Pull request merged**
