### PR TITLE
Add min-version/max-version to fulltextsearch provider element

### PR DESCRIPTION
**Pull request by juliusknorr**
@daita In https://github.com/nextcloud/server/pull/14302#issuecomment-465680038 you mentioned a version parameter but in deck you actually used min-version. Can you clarify what is actually used, since I couldn't find where this is checked.

### CODE REVIEW

**Comment by daita** [comment]
nice, can you add a `max-version` too ?

**Comment by juliushaertl** [comment]
@daita Done. 

Just for reference the attributes are checked in the full text search app to see if a provider should be loaded for a specific Nextcloud version: https://github.com/nextcloud/fulltextsearch/pull/463/files

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Review by ArtificialOwl — APPROVED** [review]

**Review by ArtificialOwl — APPROVED** [review]
Maxence :+1:

**Pull request merged**
