### PR TITLE
Look up nextcloud instance based off SRV

### PR DESCRIPTION
**Pull request by jhesketh**
This change allows a federated user/share to be added using a hostname
different to the real hostname of the nextcloud server.

This is useful in cases where a cloud is on a different domain to an
email address as it will allow users to share directly with the email
address and have it resolve to the nextcloud user.

For example, if somebody has the email address 'me@example.com', and
a nextcloud instance at 'cloud.example.com', this change will resolve
the federated user to 'me@cloud.example.com'.

This requires the username to be the same as the email address prefix.
It also requires an appropriate _nextcloud._tcp SRV record.

Related issue: #365

### CODE REVIEW

**Comment by jhesketh** [comment]
This is a first pass that is untested. Looking for feedback on implementation.

A few things to consider:

 - Should we make it possible to query a remote cloud for a full email address. For example, if a users email prefix differs from their nextcloud username we could return the nextcloud user by looking up the email address.

 - Should we support methods other than SRV for discovering the service?

 - This doesn't retain the originally entered address. Once resolved a user will see "name@cloud.example.com" even if they just entered "name@example.com". Do we want to try and preserve it as entered. (I investigated this but it added significant complexity).

**Comment by juliushaertl** [comment]
> This requires the username to be the same as the email address prefix.
It also requires an appropriate _nextcloud._tcp SRV record.

Maybe we should go for something more generic here, so that we also can lookup the instance of e.g. pydio instances?

@nextcloud/sharing for further comments

**Comment by rullzer** [comment]
First of all great initiative!

As @juliushaertl said making it more generic is good
Also adding maybe different fallbacks in the future.

But for now I would say just adding this is good enough. We can think about other means later if we want. It would of course (maybe now maybe future work?) be good to have a proper interface that can be implemented.).

But most importantly this has to be properly and cached (and refreshed in the background). Doing extra DNS requests on each call to the server won't scale. Especially on larger instance where there might be a whole lot of federated shares.

**Comment by jhesketh** [comment]
> Maybe we should go for something more generic here, so that we also can lookup the instance of e.g. pydio instances?

Right, we could perhaps name it something more generic (eg _federatedcloud._tcp). Also, looking closer at how federation works, an SRV record does not cover the case where a cloud is located in a sub-path (eg: username@sub.example.com/nextcloud). We would also need to extend the path by looking up a corresponding TXT record similar to how caldav works (https://tools.ietf.org/html/rfc6764#section-4).

> But most importantly this has to be properly and cached (and refreshed in the background). Doing extra DNS requests on each call to the server won't scale. Especially on larger instance where there might be a whole lot of federated shares.

Agreed. I hadn't looked closely at how the CloudId object was managed and had assumed after the federated lookup it stored the resulting server information. This is my lack of experience in the codebase but either way we need to only look it up when it makes sense to.

**Comment by rullzer** [comment]
@jhesketh did you have more time to look into this?

Feel free to drop by in #nextcloud-dev on freenode to discuss!

**Comment by dbenoy** [comment]
I'm a NextCloud user and looking forward to a feature like this. It should be common practice that every federated service should have some way of delegating services on the base domain to specific servers or subdomains. Having every federated service user ID match their email address is the sort of thing that makes life a lot easier for supporting users.

I also like the idea of having multiple methods (SRV, TXT, .well-known) but I think DNS should have priority. You may give a web designer access to your site and you don't necessarily want him to have the power to redirect all your cloud ids, too.

I think this should be merged, but one thing that would have to be fixed as well is that the web interface is telling users 'Your Federated Cloud ID:', and it just tells you the hostname that it detects. A new admin configuration option should be added for 'canonical server address'

Also this opens the door to multiple domains pointing at the same Nextcloud server. If you really wanted to get fancy, you could embrace that fact and allow a single server to have users on multiple domains. For example if you have one domain for staff accounts and one domain for customer accounts (Like somebody@google.com vs. somebody@gmail.com) then you wouldn't be forced to set up two NextCloud servers if you wanted to serve them both.

**Comment by dbenoy** [comment]
Webfinger could be used for this purpose, too, and may be the best choice if Nextcloud is ever going to have any social networking style features.

**Comment by poVoq** [comment]
Has something like this ever been implemented?

**Comment by krejcar25** [comment]
Hello,
let's un-stale this. I would really love to see this feature implemeneted. And since the code is already there, don't let it go to waste. I personally think that looking up the DNS records by the server and then caching them (either for the TTL of the record or longer) would be sufficient. I feel like this would be much more comprehensive for the non-technical user. "Oh look, my federeted ID is the same as my biz email, that's cool, I will remember it." And since sharing via email is already there, the server could just look if there is a federated cloud with this and insert it directly there and if not then send an email. The creator of the share wouldn't even have to care about it. It would fit with the whole Nextcloud Hub all-in-one business place kind of vibe.

Any other points? 😊
Michal

**Comment by Cam-B** [comment]
would love to see this too

**Comment by Mactory** [comment]
+1

**Pull request closed without merging**
