### PR TITLE
don't remove owner property for public calendars

### PR DESCRIPTION
**Pull request by georgehrke**
we can't remove the owner property as done in https://github.com/nextcloud/server/pull/4224/files#diff-d93b2e65badfbda223ac46eecdceb00bR50

We need the owner prop for https://github.com/nextcloud/calendar/pull/372

### CODE REVIEW

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Tests do fail, @georgehrke

**Comment by georgehrke** [comment]
@LukasReschke fixed :)

**Comment by georgehrke** [comment]
I will send PR for back ports when this was approved

**Review by LukasReschke — APPROVED** [review]
Works nicely

**Review by rullzer — APPROVED** [review]

**Pull request merged**
