### PR TITLE
Wrap contact search result in a link

### LINKED ISSUE #24807: Contacts menu, more intuitive link to contact details
Would suggest to make the contact name the link to the detailed contact page, instead the additional "i" which then would be obsolete. Which would give room to link multiple mail addresses directly and/or link first mail address + first phone number in quick search.

Thanks for considering :-)

quick-search-details-link

### PR DESCRIPTION
**Pull request by artonge**
Supersede https://github.com/nextcloud/server/pull/31824
Fix https://github.com/nextcloud/server/issues/24807

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
looks good but didn't test

**Comment by devsekar-1992** [comment]
> @devsekar-1992 can you check that the change is still good ?

Yes @artonge

**Review by Pytal — APPROVED** [review]

**Comment by artonge** [comment]
Thank you @devsekar-1992 ! Sorry it was such a drag for you, hopefully it will be smoother next time! :)

**Comment by devsekar-1992** [comment]
@artonge  No problem. It's one of the learnings of my first open-source contribution. 

Thank you @szaimen  @artonge @Pytal  for accepting my first open-source contribution

**Pull request merged**
