### PR TITLE
Restructure server settings

### PR DESCRIPTION
**Pull request by juliusknorr**
As described in https://github.com/nextcloud/server/issues/9003

- Add cron check to security and setup checks
- Add general server settings
- Move caldav, mail, file upload, cron settings to the general section
- ~Move update settings to general section and add plain update notification to the overview~
- Only show additional settings for legacy forms, if they are used somewhere
- Add line separator between settings sections
- Increase space at the headline to increase readability
- Separate sharing settings to make federated sharing options its own section

image
image
image

### CODE REVIEW

**Comment by jancborchardt** [comment]
cc @karlitschek, this is the PR related to https://github.com/nextcloud/server/issues/9003 – server settings restructuring

**Comment by juliushaertl** [comment]
fixes https://github.com/nextcloud/server/issues/4600 as well

**Comment by juliushaertl** [comment]
Ready for review @nextcloud/designers

**Comment by nickvergessen** [comment]
Any reason why the "Version" is now split from the "Update" information?

Since this is where you start your update and see if you can update, I think it should be on the front page.

**Comment by juliushaertl** [comment]
@nickvergessen The idea was to just show an overview page with details about the server status and move all settings to other pages. Since the updatenotifications app basically does both, configuring the update channel and showing, if there is an update available, i split those two up. But after thinking about it, it is kind of weird to have this in two sections.

Any ideas how we could solve that @nextcloud/designers ? Otherwise I'm fine with just showing it on the overview page, as it was before.

**Comment by MorrisJobke** [comment]
> Any ideas how we could solve that @nextcloud/designers ? Otherwise I'm fine with just showing it on the overview page, as it was before.

I would do that. maybe shorten a bit the text.

**Comment by juliushaertl** [comment]
Ok, I removed the updatenotification changes from the branch. Please have another look. I'll check if we can simplify the text in a separate PR then.

**Comment by juliushaertl** [comment]
CI failure is unrelated, ready to review @nextcloud/designers

**Comment by karlitschek** [comment]
looks good 👍

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
