### PR TITLE
Add SPDX header - batch 10

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Resolves:  SPDX header, next batch

## Summary

more apps, yet they lack data for the media items, i.e. images/icons, to be added in follow-up PRs when license could be clarified.

* files with copyright information: 10133 / 10970
* files with license information: 9345 / 10970

## TODO

- [x] compile
- [x] review and merge

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
Almost done :tada:

**Comment by AndyScherzinger** [comment]
> Almost done 🎉

Yes, while some aspects will need extra time to get resolved, images/icons are the most prominent/biggest one...but we are getting there

**Review by susnux — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Pull request merged**
