### PR TITLE
Don't resolve public share token if public sharing is disabled

### PR DESCRIPTION
**Pull request by LukasReschke**
Otherwise disabling sharing does prevent access to the view controllers but one can still access the shares using the public preview route or the public WebDAV endpoint.

Discovered while porting https://github.com/nextcloud/server/pull/2759

While security related I believe that the impact is minimal and backporting this has the potential to break stuff. So let's keep this master only for now.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@rullzer I'd appreciate your feedback on this.

**Review by schiessle — CHANGES_REQUESTED** [review]
This method is also used to resolve federated shares, see L1066-L1073. This should still work, even if public links are disabled.

Another open question, should Share by Mail still work if public link sharing is disabled? I tend to say yes, because share by mail can be enabled/disabled independently. So we should take this also into account (L1076-L1083)

**Comment by rullzer** [comment]
Ah no. Lets not do this. I want to fix (for 12) the way we register providers. So that we don't do fancy magic. That way if link sharing is disabled we won't register the provider at all. Thus also solving this.

**Comment by schiessle** [comment]
> Ah no. Lets not do this. I want to fix (for 12) the way we register providers. So that we don't do fancy magic. That way if link sharing is disabled we won't register the provider at all. Thus also solving this.

I agree that we need to decouple share provider more from the server. Also writing a share provider should be possible without touching a single line of the server.

Nevertheless, I would be fine with merging this three line fix if the problem I mentioned above are fixed. Then we don't have to worry that we will forget about it if we don't finish the changes you described in time for Nc12, if you get all this done then it also don't hurt if we merge now a three line fix.

**Comment by rullzer** [comment]
@schiessle I ment in its current form ;) I'll adjust the PR to fix

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Now I'm good :smile:

**Comment by LukasReschke** [comment]
@schiessle Can you take a look at @rullzer's changes? THX a lot.

**Comment by schiessle** [comment]
@LukasReschke added already a comment above... Will take care of it

**Comment by schiessle** [comment]
remove unnecessary exception... I'm fine with it if the final tests pass 👍

**Review by schiessle — APPROVED** [review]

**Pull request merged**
