### PR TITLE
Fix damaged UI userlist

### LINKED ISSUE #37188: [Bug]: Damaged UI userlist (browser layout) if a user has a lot of entries of single group admin rights in users section backend.
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The Nextcloud backend UI layout (CSS) is somehow damaged and overlapping entry info among several user entries, if one user has an bigger amount of group administration entries.
That makes it very difficult to edit a specific users entry.
...
I have an actual Nextcloud 25.0.4 with actual OS and Browser.
Layout problem occurs an Safari, Chrome and Firefox.

### Steps to reproduce

1. Create about 10 or more groups within Nextcloud. Each group name with a name longer name (more than 8Chars).
2. Create 10 or more users. Name the users that way, so that the group admin users later on appear in-between others in the user list of the backend.
4. Assign two users the administration rights for every(!) single group of the 10 groups.
5. The height of each row in the user list seems to be at the same value, what makes the entries overlap other user entries.

Probably a CSS layout problem!
...

### Expected behavior

The row height of a single user in the user list of the backend should auto adjust dependent of the amount of content (group entries) and not overlap other user content.
...

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{    "system": {        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "xyz.de",            "xyz-nc.xyz.de"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "overwrite.cli.url": "https:\/\/xyz-nc.xyz.de",        "dbtype": "mysql",        "version": "25.0.4.1",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "oc_",        "mysql.utf8mb4": true,        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "maintenance": false,        "theme": "",        "loglevel": 2,        "mail_from_address": "***REMOVED SENSITIVE VALUE***",        "mail_smtpmode": "smtp",        "mail_domain": "***REMOVED SENSITIVE VALUE***",        "mail_smtpsecure": "tls",        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",        "mail_smtpport": "25",        "mail_smtpauth": 1,        "mail_smtpauthtype": "LOGIN",        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",        "app_install_overwrite": [            "occweb",            "richdocuments",            "impersonate"        ],        "data-fingerprint": "xyzxyzxyz",        "default_phone_region": "DE"    }}
```

### List of activated Apps

```shell
Enabled:  - activity: 2.17.0  - announcementcenter: 6.5.1  - calendar: 4.2.4  - circles: 25.0.0  - cloud_federation_api: 1.8.0  - comments: 1.15.0  - contacts: 5.1.0  - contactsinteraction: 1.6.0  - dashboard: 7.5.0  - dav: 1.24.0  - external: 5.0.2  - federatedfilesharing: 1.15.0  - federation: 1.15.0  - files: 1.20.1  - files_accesscontrol: 1.15.1  - files_pdfviewer: 2.6.0  - files_rightclick: 1.4.0  - files_sharing: 1.17.0  - files_versions: 1.18.0  - firstrunwizard: 2.14.0  - forms: 3.2.0  - groupfolders: 13.1.1  - impersonate: 1.12.0  - logreader: 2.10.0  - lookup_server_connector: 1.13.0  - nextcloud_announcements: 1.14.0  - notes: 4.6.0  - notifications: 2.13.1  - oauth2: 1.13.0  - occweb: 0.1.0  - password_policy: 1.15.0  - photos: 2.0.1  - privacy: 1.9.0  - provisioning_api: 1.15.0  - recommendations: 1.4.0  - related_resources: 1.0.4  - serverinfo: 1.15.0  - settings: 1.7.0  - spreed: 15.0.4  - support: 1.8.0  - systemtags: 1.15.0  - tasks: 0.14.5  - theming: 2.0.1  - twofactor_backupcodes: 1.14.0  - updatenotification: 1.15.0  - user_status: 1.5.0  - viewer: 1.9.0  - weather_status: 1.5.0  - workflowengine: 2.7.0Disabled:  - admin_audit: 1.15.0  - backup: 1.2.0  - bruteforcesettings: 2.4.0  - encryption  - files_external  - files_texteditor: 2.15.0  - files_trashbin: 1.9.0  - mail: 2.2.4  - nextbackup: 21.1.0  - richdocuments: 7.1.1  - richdocumentscode: 22.5.802  - sharebymail: 1.3.0  - survey_client: 1.1.0  - suspicious_login  - text: 3.5.1  - twofactor_totp  - user_ldap
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by inet-cologne**
* Resolves: https://github.com/nextcloud/server/issues/37188

## Summary

Fix CSS for user list backend to dont overlap entries - from grid-auto-rows:minmax(60px, max-content) to grid-auto-rows:minmax(max-content, max-content).

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@szaimen if you triage a PR and request a review from engineers please make sure the PR is in a reviewable state. To judge the changes here we'd need a description or a linked ticket and before/after screenshots for the visual change. Cheers.

**Comment by inet-cologne** [comment]
Hi @szaimen and @ChristophWurst,
thanks a lot for your time to try to review my PR.
I am sorry for the confusion but I am totally new in Github! (Gitlab is so much more intuitive! 😬)

Here are the requested and hopefully sufficient infos for you to acknowledge the changes:
Bug report reference:
https://github.com/nextcloud/server/issues/37188

Screenshots before and after the changes as attachment.

Please let me know if something is missing!

Best,
Chris
Before (bug):
Nextcloud-25-0-5_Error-Overlapping-Userlist_Screenshot_2023-03-31_annotated

After (fix):
Nextcloud-25-0-5_Fix-Userlist_Screenshot_2023-03-31_annotated

**Review by JuliaKirschenheuter — APPROVED** [review]
Thank you @inet-cologne for fixing this issue!
Not tested but looks good!

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
@inet-cologne please compile and ship changed dist files :)

**Comment by szaimen** [comment]
So basically please rebase, run npm ci and npm run bild and commit the changed files here. Thanks in advance! :)

**Comment by inet-cologne** [comment]
Hi there,
sorry, I need some help here.
I only changed one small CSS userlist setting in an earlier Nextcloud version from
   minmax(60px, max-content)
to
   minmax(max-content, max-content

Unfortunately the change was not merged in the follower versions of Nextcloud and the rebase produced now a merge conflict.
I don't know exactly what do do here to solve the merge conflict as my change was only a tiny setting, not the whole class.

Everything was documented in the related PR. Perhaps someone can assist in resolving the conflict please.
Thanks in advance as unfortunately the error is back in the actual Nextcloud versions 27.0.0 to 27.0.2.
Chris

**Comment by inet-cologne** [comment]
As said above.
I need somebody to that stuff here, as I don't know how to get all the Github stuff done.
So please can someone of your experts could repair the above 60px to max-content css in the current release in a way that it remains in future versions?
I give up! I'm sorry!
Chris

**Comment by skjnldsv** [comment]
Hey @inet-cologne after seeing the few issues we had with the user list, it received a refresh which makes your fix not required anymore! :wink: 

Thanks for taking the time to create this PR and help Nextcloud, and my apologies for taking this long to update this ticket :bow:

**Pull request closed without merging**
