### PR TITLE
add better index for finding unindexed paths

### PR DESCRIPTION
**Pull request by icewind1991**
for the following query `SELECT "path" FROM "oc_filecache" WHERE ("storage" = $storage) AND ("size" < 0) ORDER BY "fileid" DESC LIMIT 1;` which is used by the background scanner.

currently the database will in some cases decide to prioritize the sort by fileid over the filter when picking what index to use, resulting in a much slower query.

by creating an index that allows first sorting by fileid and also filter by storage and size this case will be greatly sped up

Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: makes sense

so this is for the BackgroundScanner

**Review by CarlSchwan — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by PVince81** [comment]
@icewind1991 backports? wouldn't be too good for patch releases if we don't want DB updates

**Pull request merged**
