### PR TITLE
Split long running features/sharing-v1.feature into two smaller parts

### PR DESCRIPTION
**Pull request by MorrisJobke**
We are nearly always waiting for this integration test. So I split it up in two parts. Hopefully this will also avoid the timeout on those (because the run longer than allowed 😉 )

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @icewind1991 @ChristophWurst

**Review by rullzer — APPROVED** [review]
fine by me

**Review by icewind1991 — APPROVED** [review]

**Comment by rullzer** [comment]
conflicts!

**Comment by MorrisJobke** [comment]
> conflicts!

Fixed! 😝

**Pull request merged**
