### PR TITLE
Send an email once a file/folder is shared with a user

### PR DESCRIPTION
**Pull request by MorrisJobke**
* only if user has set an email address
* only for user shares (no group shares for now)

The sharing email is basically the same as for the "share by email". 😉

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested with an instance with index.php and without. Worked both fine:

bildschirmfoto 2017-07-26 um 23 45 15

**Comment by mario** [comment]
Considering there is only one available action, putting "Click the button below to open it" (also what is "it"?) is redundant. Please remove that part.

**Comment by mario** [comment]
Actually, like mentioned in the chat, the entire body text is largely useless and redundant.

**Comment by MorrisJobke** [comment]
Then the email looks super empty. I guess we need some adjusted text in there (also it avoid to be classified as spam, because they check for a given word count sometimes).

bildschirmfoto 2017-07-27 um 12 20 50

**Comment by mario** [comment]
The white rectangle is also ugly. Maybe just button below the text?

**Comment by MorrisJobke** [comment]
> The white rectangle is also ugly. Maybe just button below the text?

This is super hard to accomplish due to the weird stuff, that HTML emails need to be compatible with the new stuff like gmail and the old stuff like Outlook (old regarding rendering engine).

**Review by LukasReschke — APPROVED** [review]
😀

**Comment by schiessle** [comment]
In the default activity settings email notifications are enabled for "A file or folder has been shared". Does this mean that users will get now two mails by default. One immediately after the share was created and one later when the activity mails are send out?

**Comment by MorrisJobke** [comment]
> Does this mean that users will get now two mails by default. One immediately after the share was created and one later when the activity mails are send out?

Seems so. We should disable the activity email then.

**Comment by MorrisJobke** [comment]
This would then look like this:

bildschirmfoto 2017-07-28 um 08 32 45


I still don't like it. Can we get this in like it is now, because those are already the emails that are send out for email shares and then do the rewording in an additional step? Thanks

**Comment by mario** [comment]
@MorrisJobke sure. Would you be so kind to open an issue with all emails that we send like this (and assign them to me) so I can re-word them together with you? :)

**Comment by schiessle** [comment]
> Seems so. We should disable the activity email then.Seems so. We should disable the activity email then.

I fear that this will always lead to confusions because with this PR we only send notifications for individual shares, so if someone want to have notification about group shares they have to enable the activity settings which will then lead to duplicates for individual shares. Maybe we should reduce the activity mails than to non-individual shares only... But this will also be confusing "why can I disable mails for group shares but not for individual shares"?

In general I really like the idea about direct mail notifications for shares as introduced here but I fear that we create two parallel worlds of notification which will become quite confusing.

As a minimum I would suggest to change at least the activity defaults with this PR directly to disable activity mails for shares.

**Comment by LukasReschke** [comment]
> I still don't like it. Can we get this in like it is now, because those are already the emails that are send out for email shares and then do the rewording in an additional step? Thanks

👍 🙈

**Comment by MorrisJobke** [comment]
> I fear that this will always lead to confusions because with this PR we only send notifications for individual shares, so if someone want to have notification about group shares they have to enable the activity settings which will then lead to duplicates for individual shares.

I would simply add group emails as well, but those need more code and those I would also not backport. 😉 



> In general I really like the idea about direct mail notifications for shares as introduced here but I fear that we create two parallel worlds of notifications which will become quite confusing.

Of course we should streamline everything.

> As a minimum I would suggest to change at least the activity defaults within this PR to disable activity mails for shares.

I thought the activity defaults are set in the activity app. Let me create a PR there.

**Comment by MorrisJobke** [comment]
> I thought the activity defaults are set in the activity app. Let me create a PR there.

Was done in files_sharing. So I added a commit here.

**Review by rullzer — APPROVED** [review]
Fine lets get this in. Then I'll spend some time getting more event ready so we can decouple this.

**Comment by LukasReschke** [comment]
Pro-tip: If CI says stuff doesn't work then don't merge it. This here is broken.

**Comment by jancborchardt** [comment]
@MorrisJobke @mario if there is that wording discussion issue please CC me. I also agree the notification mails should be cleaner, but of course also not too empty. :) We could think about using filetype icons, or even generated previews.

**Pull request merged**
