### PR TITLE
fix(files_sharing): Stop infinite loop blocking link share requests

### LINKED ISSUE #49678: [Bug]: 30.0.3 share link completely broken
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the update from 30.0.2 to 30.0.3 it is impossible to create a share link. Clicking on the arrow in the password field or the "create share" button only creates another "share link" entry. All created share link entries lack a link. This process can be repeated:
Image

Console logs did not throw any errors.

### Steps to reproduce

1. Update from 30.0.3 to 30.0.3
2. Try to create a share link
3. Fail

### Expected behavior

To create a share link, as it worked up until 30.0.2

### Nextcloud Server version

30

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "default_phone_region": "DE",
        "version": "30.0.2.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 0
        },
        "session_lifetime": 3600,
        "session_keepalive": false,
        "tempdirectory": ***REMOVED SENSITIVE VALUE***,
        "remember_login_cookie_lifetime": 0,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "default_language": "en",
        "default_locale": "en_GB",
        "knowledgebaseenabled": false,
        "simpleSignUpLink.shown": false,
        "auth.webauthn.enabled": false,
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 7",
        "versions_retention_obligation": "auto, 7",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 2,
        "preview_max_filesize_image": 100
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - announcementcenter: 7.0.1
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - checksum: 1.2.5
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - files_zip: 2.1.0
  - impersonate: 1.17.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - previewgenerator: 5.7.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - quota_warning: 1.20.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - circles: 30.0.0 (installed 22.1.1)
  - contacts: 6.1.1 (installed 6.1.1)
  - dashboard: 7.10.0 (installed 7.0.0)
  - encryption: 2.18.0
  - federation: 1.20.0 (installed 1.10.1)
  - files_automatedtagging: 1.20.0 (installed 1.20.0)
  - files_external: 1.22.0
  - firstrunwizard: 3.0.0 (installed 2.9.0)
  - recommendations: 3.0.0 (installed 0.8.0)
  - suspicious_login: 8.0.0
  - text: 4.1.0 (installed 3.1.0)
  - theming_customcss: 1.17.0 (installed 1.17.0)
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
  - user_status: 1.10.0 (installed 1.0.1)
  - weather_status: 1.10.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

I immediately reverted back to 30.0.2 (vm snapshot) after becoming aware of this bug. So I can't provide any further information.

### PR DESCRIPTION
**Pull request by nfebe**
- fix(files_sharing): Stop infinite loop blocking link share requests

        Fixes infinite loop preventing share link creation requests from being sent to the backend.

- fix: Delete link update code in ShareEntryLink

        Since Nexcloud27, all share edits can only be done from the `SharingDetailsTab` or the `QuickShareSelect` so this concerned component does not need to handle updates.

### CODE REVIEW

**Comment by nfebe** [comment]
This should resolve : https://github.com/nextcloud/server/issues/49678

**Comment by nfebe** [comment]
backport to stable30

**Review by Pytal — APPROVED** [review]
🐘

**Comment by Pytal** [comment]
Only see backports for 30 + 28, I guess https://github.com/nextcloud/server/pull/49115 should also be on 29?

**Comment by Pytal** [comment]
Seems partially fixed but the behaviour is unexpected

When clicking the + button, instead of creating the share like before it opens a menu so you have to click "Add another link" to actually create it
image
image

**Comment by nfebe** [comment]
> Seems partially fixed but the behaviour is unexpected
> 
> When clicking the + button, instead of creating the share like before it opens a menu so you have to click "Add another link" to actually create it


Should work now properly for all these cases:

- Default password set but not enforced, and no default expiration date set.
- Default password set and enforced, and no default expiration date set.
- Default expiration date set but not enforced, and default password not set and therefore not enforced.
- Default expiration date set and enforced, and default password not set and therefore not enforced.
- Default password set but not enforced, and default expiration date set but not enforced.
- Default password set but not enforced, and default expiration date set and enforced.
- Default password set and enforced, and default expiration date set but not enforced.
- Default password set and enforced, and default expiration date set and enforced.

**Review by sorbaugh — APPROVED** [review]

**Pull request merged**
