### PR TITLE
Remove unneeded and problematic vue-cli-plugin-unit-test

### PR DESCRIPTION
**Pull request by PVince81**
It was causing issues during dependency upgrades and wasn't really used except for its preset definition.

Similar to https://github.com/nextcloud/spreed/pull/7683.

Resolves the problematic dependency update from https://github.com/nextcloud/server/pull/33999

### CODE REVIEW

**Review by marcoambrosini — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
🐘

**Comment by PVince81** [comment]
stable24 and earlier don't have vue-cli-plugin-unit-test

**Pull request merged**
