### PR TITLE
Update root certificate list

### PR DESCRIPTION
**Pull request by LukasReschke**
Syncs with the newest certificate list by Mozilla.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Review by MorrisJobke — APPROVED** [review]

**Comment by nickvergessen** [comment]
👍

**Comment by MariusBluem** [comment]
Is this something we need to backport 😁 @nickvergessen

**Comment by MorrisJobke** [comment]
stable10: #1649 
stable9: #1950

**Pull request merged**
