### PR TITLE
Mark more config values as sensitive

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by blizzz** [comment]
Should be done on app side via `$context->registerSensitiveMethods`, e.g. https://github.com/nextcloud/sharepoint/pull/143

**Comment by nickvergessen** [comment]
> Should be done on app side via

We can do that going forward, but we also need to backport this one 🙈

**Comment by nickvergessen** [comment]
> Should be done on app side via $context->registerSensitiveMethods, e.g

Wait, that is about methods. Not about the system report / config list. While still good and mostlikely related it's a different thing.
Will queue a task to check if both are properly documented and then suggest a dev news update with it.

**Comment by blizzz** [comment]
> > Should be done on app side via $context->registerSensitiveMethods, e.g
> 
> Wait, that is about methods. Not about the system report / config list. While still good and mostlikely related it's a different thing. Will queue a task to check if both are properly documented and then suggest a dev news update with it.

Good point, didn't realize it (need more coffee). Probably need to add support to register var names.

**Comment by nickvergessen** [comment]
Manual backports above

**Pull request merged**
