### PR TITLE
Properly handle resources in ReminderService

### LINKED ISSUE #17951: ReminderService::parseCalendarData() must be of the type string
### Steps to reproduce
No idea. I think it's when sending calendar invitations from the Web calendar.

### Expected behaviour
No errors

### Actual behaviour
See nextcloud.log

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
1.7.1

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
DAVx5

### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox

**Operating system:** (e.g. Arch Linux)
Ubuntu 18.04

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.04

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
PosgreSQL 10

**PHP version:** (e.g. 7.0.3)
7.2

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
17.0.1

**Updated from an older installed version or fresh install:**
Updated

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
[cron] Error: TypeError: Argument 1 passed to OCA\DAV\CalDAV\Reminder\ReminderService::parseCalendarData() must be of the type string, resource given, called in /var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php on line 110 at <<closure>>

0. /var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php line 110
   OCA\DAV\CalDAV\Reminder\ReminderService->parseCalendarData(null)
1. /var/www/nextcloud/apps/dav/lib/BackgroundJob/EventReminderJob.php line 62
   OCA\DAV\CalDAV\Reminder\ReminderService->processReminders()
2. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
   OCA\DAV\BackgroundJob\EventReminderJob->run(null)
3. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
4. /var/www/nextcloud/cron.php line 124
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-11-14T12:00:27+01:00

[core] Error: OCP\AppFramework\QueryException: Could not resolve PageController! Class PageController does not exist at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 114
   OC\AppFramework\Utility\SimpleContainer->resolve("PageController")
1. /var/www/nextcloud/lib/private/ServerContainer.php line 145
   OC\AppFramework\Utility\SimpleContainer->query("PageController", true)
2. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 388
   OC\ServerContainer->query("PageController", true)
3. /var/www/nextcloud/apps/phonetrack/lib/Cron/AutoExport.php line 24
   OC\AppFramework\DependencyInjection\DIContainer->query("PageController")
4. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
   OCA\PhoneTrack\Cron\AutoExport->run(null)
5. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
6. /var/www/nextcloud/cron.php line 124
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-11-12T21:15:27+01:00
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #17951

### CODE REVIEW

**Comment by georgehrke** [comment]
waiting for responses in #17951, will request reviews after that

**Comment by georgehrke** [comment]
Responses in #17951 are positive that this fixes the issue

**Comment by kesselb** [comment]
Code looks good. Have you found a way to reproduce it? https://github.com/nextcloud/server/blob/c7d5b8fc493520ab40076ddade3632152dbfef00/apps/dav/lib/CalDAV/Reminder/Backend.php#L207 probably it's possible to do `stream_get_contents` here. No duplicate code than ;)

**Comment by tcitworld** [comment]
I reproduce it too on my own production server.

**Review by kesselb — APPROVED** [review]

**Review by gary-kim — APPROVED** [review]
LGTM

**Comment by enoch85** [comment]
Thanks! I don't see any backport request, would that be possible?

**Pull request merged**
