### PR TITLE
Move to escape-html

### PR DESCRIPTION
**Pull request by rullzer**
* If there is a package that does exactly the same then lets us use that
* Import it properly in the internals (less deprecation warnings)

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:+1: :+1: :+1:

**Review by juliusknorr — APPROVED** [review]

**Review by skjnldsv — COMMENTED** [review]
I think we should not offer it as a standalone function then.
We deprecated it, let's remove the windows binding and import it where we need it? @ChristophWurst what do you think? Too soon? Shall we wait for another version?

**Comment by rullzer** [comment]
> I think we should not offer it as a standalone function then.
> We deprecated it, let's remove the windows binding and import it where we need it? @ChristophWurst what do you think? Too soon? Shall we wait for another version?

the deprecation said it will be removed in 19 ;)

**Comment by skjnldsv** [comment]
ok then :)

**Pull request merged**
