### PR TITLE
Deprecate the internal IDBConnection event name constants

### PR DESCRIPTION
**Pull request by ChristophWurst**
I'm also ok with doing this even for 21.0.0 …

### CODE REVIEW

**Comment by ChristophWurst** [comment]
CI is happy, checkers are fixed with https://github.com/nextcloud/server/pull/25542

**Review by rullzer — APPROVED** [review]
Lets do this and move https://github.com/nextcloud/server/pull/25471 forward then. Maybe by adding the remaining things as well.

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Did we add this for 20 or 21, then we could just remove it

**Comment by nickvergessen** [comment]
Ah two were backported to 20 and the others were there before

**Pull request merged**
