### PR TITLE
[stable10] Allow to retrieve the quota itself via the provisioning api

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #890

### CODE REVIEW

**Comment by rullzer** [comment]
LGTM

**Comment by LukasReschke** [comment]
LGTM

**Comment by AndyScherzinger** [comment]
any reason for not (also) backporting it to stable9? :smiley:

**Comment by mar1u5** [comment]
#901 is the backport to `stable9` 😁 @AndyScherzinger THX.

**Pull request merged**
