### PR TITLE
Disable HEIC image preview provider for performance concerns

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
Fine by me

**Review by juliusknorr — APPROVED** [review]

**Comment by Starbix** [comment]
Where exactly is the problem with performance? Where can I find a discussion on this decision?

**Comment by dotlambda** [comment]
I would also like to know the rationale.

**Comment by kesselb** [comment]
https://hackerone.com/reports/1261413

**Pull request merged**
