### PR TITLE
Use toasts from @nextcloud/dialogs, deprecate OCP.Toast and fix usages

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/nextcloud-dialogs/pull/84#issue-369995246

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by rullzer** [comment]
jsunit does boom https://drone.nextcloud.com/nextcloud/server/25909/1/2

**Comment by ChristophWurst** [comment]
@juliushaertl it's the `selector` option in Toastify. It was changed with https://github.com/nextcloud/nextcloud-dialogs/pull/84/files#diff-1355aca4c744fdba046148edea3fb816R70. The current one is https://github.com/nextcloud/server/blob/6a1ba818f5cd0553fb1dc2ef49d6717b64bb07bf/core/src/OCP/toast.js#L78. Was this changed intentionally?

**Comment by juliushaertl** [comment]
> Was this changed intentionally?

Ah no, it was mainly because i wasn't thinking that we still might need the fallback for the old jsunit tests. I'd say we make the selector an option in the nextcloud-dialogs implementation and then can just pass in `!window.TESTING ? 'content' : 'testArea'` in the OCP.Toast wrapper.

**Comment by ChristophWurst** [comment]
> I'd say we make the selector an option in the nextcloud-dialogs implementation and then can just pass in `!window.TESTING ? 'content' : 'testArea'` in the OCP.Toast wrapper.

- [ ] https://github.com/nextcloud/nextcloud-dialogs/pull/94

**Comment by ChristophWurst** [comment]
Tests finally pass locally :sweat_smile:

**Comment by rullzer** [comment]
get in or 20?

**Comment by ChristophWurst** [comment]
> get in or 20?

let me rebase. I'd prefer to get this in sooner than later

**Pull request merged**
