### PR TITLE
20.0.6

### PR DESCRIPTION
**Pull request by rullzer**
* #25219 Bump CA bundle
* #25225 Update handling of user credentials
* #25244 Fix encoding issue with OC.Notification.show
* #25261 Also use storage copy when dav copying directories
* #25263 Silence log message
* #25276 Extend ILDAPProvider to allow reading arbitrairy ldap attributes for users
* #25278 Do not obtain userFolder of a federated user
* [activity#551](https://github.com/nextcloud/activity/pull/551) Clear event array on getting them

### CODE REVIEW

**Comment by LecrisUT** [comment]
Could you also include these 2 commits from #25214?
- d751fedffb110aca956e9f786cd9ecdafdfa6ecd
- fcbbcacab4dc0178c7fdf1a61cfb81f922c60209

**Comment by rullzer** [comment]
> Could you also include these 2 commits from #25214?
> 
>     * [d751fed](https://github.com/nextcloud/server/commit/d751fedffb110aca956e9f786cd9ecdafdfa6ecd)
> 
>     * [fcbbcac](https://github.com/nextcloud/server/commit/fcbbcacab4dc0178c7fdf1a61cfb81f922c60209)

I fail to see how those would help on 20 as we there did not upgrade phpseclib

**Comment by LecrisUT** [comment]
I've reported in #25243 that due to an update in 20.0.5 (or maybe even earlier), the certificate verification fails. The relevant commits that fix it are above, and are independent of phpsec update, it's just that it is first fixed in that PR.

**Comment by rullzer** [comment]
> I've reported in #25243 that due to an update in 20.0.5 (or maybe even earlier), the certificate verification fails. The relevant commits that fix it are above, and are independent of phpsec update, it's just that it is first fixed in that PR.

But then there is something else at play. Because I just checked and on 3 test system 20.0.5 validates just fine.

**Comment by LecrisUT** [comment]
I've updated 2 production instances and this problem occurred in both of them. According to the open issue others have the same problem.

At the very least those changes are backwards compatible, and will not break anything if included.

**Comment by rullzer** [comment]
> I've updated 2 production instances and this problem occurred in both of them. According to the open issue others have the same problem.

They are all on 21.
I'll check but the tagging and building of this release is very close. So else it will be 20.0.7

**Pull request merged**
