### PR TITLE
Use an icon for the update notifications

### PR DESCRIPTION
**Pull request by nickvergessen**
cc @jancborchardt 

> bildschirmfoto vom 2016-12-01 15-34-48

Fix https://github.com/nextcloud/notifications/issues/43

### CODE REVIEW

**Comment by skjnldsv** [comment]
Wouldn't it be interesting to use the app icon? :)

Otherwise: 👍

**Comment by nickvergessen** [comment]
No, see https://github.com/nextcloud/notifications/issues/43

**Comment by skjnldsv** [comment]
Makes sense!! 😄 
LGTM?

**Comment by rullzer** [comment]
Test fail

**Comment by nickvergessen** [comment]
Fixed tests

**Comment by jancborchardt** [comment]
Nice, looks good also with the bold app name! :) :+1:

**Pull request merged**
