### PR TITLE
Display the proper language strings in setttings

### PR DESCRIPTION
**Pull request by rullzer**
Since this was moved to lib, we have to the lib language files.

To verify:

1. Open personal settings
2. Check the languages

* [x] external app also uses this and maybe should get an update as well (see https://github.com/nextcloud/external/pull/78)

### CODE REVIEW

**Comment by nickvergessen** [comment]
There are still a lot of languages without names...

**Comment by MorrisJobke** [comment]
> There are still a lot of languages without names...

Let me check that.

**Comment by MorrisJobke** [comment]
> Let me check that.

Okay - this string is in lib and in settings :/ Let me sync those

**Comment by MorrisJobke** [comment]
Settings is the more complete one. It only extracts this to "lib" because it was found in the `lib/` folder 😉 Anyways - I fixed it for lib and settings and it should be better now.

**Comment by MorrisJobke** [comment]
> Settings is the more complete one. It only extracts this to "lib" because it was found in the lib/ folder 😉 Anyways - I fixed it for lib and settings and it should be better now.

Ah - got it. Yeah I fixed lib and settings to be in sync ;)

**Comment by MorrisJobke** [comment]
> Ah - got it. Yeah I fixed lib and settings to be in sync ;)

Sync is running :)

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> external app also uses this and maybe should get an update as well

https://github.com/nextcloud/external/blob/99a8fd48ba10453e5cc9fb1972cb5a68212e0f40/lib/SitesManager.php#L425-L426

**Comment by rullzer** [comment]
PR in external: https://github.com/nextcloud/server/pull/8225

**Comment by MorrisJobke** [comment]
@nickvergessen Mind to review?

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
