### PR TITLE
Fix #11873 by making default font weight "normal"

### LINKED ISSUE #11873: Default font-weight is too light, almost unreadable
### Steps to reproduce
1. Log in to NextCloud
2. View a text-heavy page (e.g. News app articles)

### Expected behaviour
Reading should be easy, using a regular font

### Actual behaviour
NextCloud defaults to a "light" weight of font, which is uncomfortable to read in large blocks of text.

screenshot_2018-10-16 news 13 - nextcloud

(The "S" in particular doesn't work well in "light" at this font size)

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.60

**PHP version:** 7.2.10

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Tarball from the web site, then web-based updater

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - apporder: 0.5.0
  - bookmarks: 0.13.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - news: 13.0.2
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - passman: 2.1.4
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
…
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** HTTPS? Yes. 

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 62.0.3

**Operating system:** openSUSE Tumbleweed

### PR DESCRIPTION
**Pull request by IBBoard**
It's a small change, but it greatly improves readability (and I don't have any accessibility or tech issues, so I can only imagine it is worse for others)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Thanks for this, but as written in https://github.com/nextcloud/server/issues/11873#issuecomment-430556644 I would prefer first to try something out and showcase it via screenshots before actually touching the CSS, because more than this change is needed (font files, different styles like bold/italic, ...).

I would close this one here in favor of #11873. I hope that is okay for you. We still really appreciate your effort here and would like to welcome you in the discussion. 👍

**Comment by MorrisJobke** [comment]
We could at any time reopen this one here and continue our work :)

**Comment by IBBoard** [comment]
Ah. It worked on my machine, but as I'm on Linux then I probably have OpenSans installed locally.

Although, tweaking values in the Firefox inspector suggests that it *is* picking up the proper "normal" weight font rather than trying to approximate it from a light font (presumably from the `@media (-webkit-max-device-pixel-ratio: 1.3), (max-resolution: 124.8dpi) { @font-face }` rule) but I've not looked at what's in the WOFF file so I don't know what it's missing and what it picked up from my local font.

fontfacelight
fontfacenormal

**Comment by MorrisJobke** [comment]
> Although, tweaking values in the Firefox inspector suggests that it _is_ picking up the proper "normal" weight font rather than trying to approximate it from a light font (presumably from the `@media (-webkit-max-device-pixel-ratio: 1.3), (max-resolution: 124.8dpi) { @font-face }` rule) but I've not looked at what's in the WOFF file so I don't know what it's missing and what it picked up from my local font.

Exactly - we also need to test then on IE 11 and so ;) But thanks for your help here. And the feedback 👍

**Pull request closed without merging**
