### PR TITLE
open admin settings overview directly if user is admin

### PR DESCRIPTION
**Pull request by szaimen**
This is best reviewed like this: https://github.com/nextcloud/server/pull/30961/files?diff=unified&w=1

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=enh/noid/open-admin-settings-directly-as-admin \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Comment by blizzz** [comment]
> /backport to stable23

Features especially behavorial ones are typically not  backported.

**Comment by blizzz** [comment]
Also, I am not sure this  should be like this? Takes away consistency, not sure this is worth the little benefit?

**Comment by szaimen** [comment]
> Features especially behavorial ones are typically not backported.

I thought this would be fine since it is a pretty small change...

**Comment by szaimen** [comment]
> Also, I am not sure this should be like this? Takes away consistency, not sure this is worth the little benefit?

Lets as @jancborchardt and @nimishavijay.

My idea was that as an admin you want to make sure that everything works -> hence the admin overview is more important than your personal settings, imo. The personal settings can then also be opened with a single additional click.

**Comment by jancborchardt** [comment]
> My impression is that as an admin you want to make sure that your instance is correctly configured and that everything works

This seems to be the main goal, and yeah agree with that. But yes it would be inconsistent to open personal settings for some people and admin settings for others, especially since people can be admins on some instances and regular users on others.

So how about a different solution here to highlight that there are config issues? We could have the "Overview" icon reflect the actual status instead of being a generic list icon. So in this case it would display an orange "Warning" icon. (And would accordingly change to the green or red one.) That gives the added benefit of seeing that something is wrong from whichever navigation entry you are in.

**Comment by szaimen** [comment]
> So how about a different solution here to highlight that there are config issues? We could have the "Overview" icon reflect the actual status instead of being a generic list icon. So in this case it would display an orange "Warning" icon. (And would accordingly change to the green or red one.) That gives the added benefit of seeing that something is wrong from whichever navigation entry you are in.

This sounds good in general but I don't think that it is possible since the tests only run when you visit the overview, afaik and running it on every settings page sounds like a bad idea to me performance wise...

**Comment by szaimen** [comment]
Based on this observation, do you think having the admin overview as default for admins would be okay?

**Comment by szaimen** [comment]
> But yes it would be inconsistent to open personal settings for some people and admin settings for others, especially since people can be admins on some instances and regular users on others.

In my opinion would this inconsistency be fine and not really dramatic... Maybe we should do some user testing on this? ;)

**Comment by szaimen** [comment]
BTW: especially regarding the external storage configuration I know that there is regularly a confusion in which settings a user has to navigate to change global settings. With this PR I am pretty sure that there would be much less confusion because the admin external storage settings become much better visible with this change ;)

**Comment by jancborchardt** [comment]
> Based on this observation, do you think having the admin overview as default for admins would be okay?

I’d still agree with @blizzz that this would be inconsistent, especially cause usually these config issues are resolved once and then they don’t come up again?

Any other ideas @nimishavijay?

**Comment by szaimen** [comment]
> especially cause usually these config issues are resolved once and then they don’t come up again?

Not necessarily because it happens often during major updates that new tests get added to this overview in my experience...

**Comment by szaimen** [comment]
> I’d still agree with @blizzz that this would be inconsistent

In my opinion having the overview directly presented to you when opening the settings is more important than consistency here but I've already pointed that out....

**Comment by szaimen** [comment]
> especially cause usually these config issues are resolved once and then they don’t come up again?

I could argue the other way around: how often do you change your personal settings (for me I set it once and never again)? :D

**Comment by szaimen** [comment]
After thinking about this a bit more, @jancborchardt what do you think about adding an additional entry for the admin settings that allow to jump to the admin settings direclty? It could be entitled as `Admin settings` and would like this follow the pattern that we already use for e.g. the User or Apps settings...

**Comment by nimishavijay** [comment]
Hmm, pretty interesting. I'd say an admin would open admin settings more than personal settings, eg. for updating, etc, 

But I don't know if it would be important enough to give up the consistency of showing the personal settings when you open the settings page. Personal settings are also the first entry in the navigation, so it makes sense to show that when you go to your settings. So it's not only about consistency across users, but also across Nextcloud apps of showing the contents of the first entry of the navigation.

Another idea that may be worth thinking about: remember the settings that the user was last on. If it was admin settings, show that. If it was personal settings show that. What do you think?

**Comment by szaimen** [comment]
@nimishavijay so basically adding a second entry to that menu that is called `admin settings` or so wouldn't work in your opinion?

**Comment by nimishavijay** [comment]
Okay, so I think it's worth doing a review of the settings in general, and then I'd say everything that the admin can configure would go in a separate admin settings (including Users and Apps) and that could be its own entry. That would require a lot of moving around of links and rearranging the UI in some cases. I'd say for now we can stick with how it is, and if decide to do an overhaul of the settings we could make the admin settings easier to access, and include more things that are relevant to admins too :)

**Comment by szaimen** [comment]
> Okay, so I think it's worth doing a review of the settings in general, and then I'd say everything that the admin can configure would go in a separate admin settings (including Users and Apps) and that could be its own entry. That would require a lot of moving around of links and rearranging the UI in some cases. I'd say for now we can stick with how it is, and if decide to do an overhaul of the settings we could make the admin settings easier to access, and include more things that are relevant to admins too :)

Okay, Could you maybe open a new Issue for that idea so that it doesn't get lost? That would be great, thanks!

I'll close this then for now since this change doesn't seem to get positive reviews ;)

**Pull request closed without merging**
