### PR TITLE
Adjust stale bot message

### PR DESCRIPTION
**Pull request by te-online**
I noticed two tiny inconsistencies in the stale bot message.

* Include that not every stale issue is missing information.
* Fix plural of information.

### CODE REVIEW

**Comment by kesselb** [comment]
Only issues with the label "needs info" are tagged as stale.

**Comment by te-online** [comment]
Alright, I'll try re-phrasing 😉

**Comment by te-online** [comment]
@kesselb What do you think about the new string?

**Comment by kesselb** [comment]
Fine by me. I think there is nothing wrong with the original phrase beside the informations.

**Comment by skjnldsv** [comment]
Hey @te-online 
I actually prefer the original phrasing :)
Since we want to close only issues that we marked as needs info, we really need the emphasis on the lack of information/relevancy ;)

What bothered you on the original phrasing? :thinking:

**Comment by te-online** [comment]
I don't want to get nerdy about the exact phrasing. 😅  It just sounded a little awkward reading it in my head with that “because“. For me it didn't really relate to the second statement. After understanding how the mechanism works, I see how my suggested change misrepresents what the sentence is supposed to express.

Would that be more precisely what you mean, maybe?
> This issue has been automatically marked as stale because it has not had recent activity and **because** it seems to be missing some essential information.

**Comment by skjnldsv** [comment]
Well, I'm no native English speaker, so any correcting of this wording is nice :)
But it should still be straightforward: There was no activity and the issue is still missing some crucial informations. :)

**Review by nickvergessen — APPROVED** [review]

**Comment by skjnldsv** [comment]
@nickvergessen you feel like it's a better wording?

**Comment by nickvergessen** [comment]
Yeah, because maybe the information was provided but the label accidentally not removed.
anyway not worth big discussions.

I think it's fine to merge or should be closed, but not be discussed over several days

**Comment by skjnldsv** [comment]
Closing then, I thing the "Additionally, it is marked as missing essential information" is not strong enough to make someone give more info.
Let's leave it like that.

if someone forgot to remove the label, then the two messages are irrelevant anyway

**Comment by te-online** [comment]
Yes, I agree, the “Additionally,...“ thing was a bad idea. But I still think the “informations“ should be fixed.

> Well, I'm no native English speaker
Me neither 😳 But I had the chance to ask one:

He said, keeping the current phrasing and removing the “it“ will do the trick. What do you think? 

If you don't agree, I don't want to waste your time and would only ask for the wrongly added `s` to be removed. 😊

**Review by nickvergessen — APPROVED** [review]

**Comment by skjnldsv** [comment]
ahaha Sure let's do it then :p
To quote some wise man: 

> I think it's fine to merge or should be closed, but not be discussed over several days

;)

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Thanks a lot @te-online :)

**Pull request merged**
