### PR TITLE
Allow translations of the comments activity in the emails too

### LINKED ISSUE #5684: Error Message "undefined offset" with comments
### Steps to reproduce
In the Log file i got a lot of error messages if i create a comment. They appear not immediately after the comment is created. 
The error looks like this: 
`

Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T17:00:01+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T17:00:01+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T17:00:01+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:01+0200
`

Also in the mails that inform about activities on nextcloud, there is just a information like this

> Today at 14:00
> "add_comment_subject"

### Expected behaviour
There should no error message in the log file
and there should be a detailed information in the activity mail

### Server configuration

**Operating system**: Ubuntu 16.04.2

**Web server:** apache 2.4.18

**Database:** mariadb 10.0.29

**PHP version:** 7.0.18

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** No

### LINKED ISSUE #6211: activity e-mail does not translate  "add_comment_subject" field into Dutch language + logo missing + bottom header not translated
See picture:
activity e-mail

### Steps to reproduce
1. use activity e-mail

### Expected behaviour
1. when I add a reaction to an folder or file it should translate the 'add_comment_subject' field to Dutch into the thex:  "Reactie toegevoegd op "{foldername}". As reactions can be given anywhere so mentioning the file or folder where an activity was given to would be helpful!

2. I changed my override URL to http instead o https and then I added to apach2 conf file the / on the end of the URL as I forgot that. Now my top of the notification e-mail shows the name of the nextcloud but the picture (logo) is no longer included.  When I look at an browser e-mai inbox and I right mouseclick on the name of the nextcloud then I can do " Open image {logo} in new tab" and it will show the picture; I'm not sure if this is something you can look at ?

3.  the bottom disclaimer shows: 
"This is an automatically sent email, please do not reply."
However can we not translate it as well to Dutch like: 
" Dit is een automatisch gegenereerde e-mail; reageren is niet mogelijk"     
edit: a new user will get a correct bottom header beeing: " Dit is een automatisch gegenereerde e-mail, dus niet reageren." so maybe look at that e-mail template and copy the right translation from there?" ?

4. make the URL of nextcloud an hyperlink; its now put in the e-mail as flat text.

### Actual behaviour
for item 1: it shows 'add_comment_subject' 
for item 2: shows the logo (does not show logo now)
for item 3: make the text Dutch as well on  the last row.
for item 4: the url of the nextcloud is not shows as hyperlink just flat text

thnx again, jeroen
=====================================================================================

### General server configuration

**Operating system:** Linux nextcloud 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
- Core
- date
- libxml
- openssl
- pcre
- zlib
- filter
- hash
- Reflection
- SPL
- session
- standard
- apache2handler
- mysqlnd
- PDO
- xml
- apcu
- calendar
- ctype
- curl
- dom
- mbstring
- fileinfo
- ftp
- gd
- gettext
- iconv
- igbinary
- json
- exif
- mysqli
- pdo_mysql
- Phar
- posix
- readline
- redis
- shmop
- SimpleXML
- sockets
- sysvmsg
- sysvsem
- sysvshm
- tokenizer
- wddx
- xmlreader
- xmlwriter
- xsl
- zip
- Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install: from 11.0 > 11.x > 12.0 > 12.0.1 12.0.2

**Where did you install Nextcloud from:**  local storage

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
- activity: 2.5.2
- admin_audit: 1.2.0
- admin_notifications: 1.0.0
- announcementcenter: 3.1.0
- bruteforcesettings: 1.0.2
- calendar: 1.5.3
- circles: 0.12.4
- comments: 1.2.0
- contacts: 1.5.3
- dav: 1.3.0
- external: 2.0.3
- federatedfilesharing: 1.2.0
- federation: 1.2.0
- files: 1.7.2
- files_automatedtagging: 1.2.2
- files_downloadactivity: 1.1.1
- files_external: 1.3.0
- files_pdfviewer: 1.1.1
- files_retention: 1.1.2
- files_sharing: 1.4.0
- files_texteditor: 2.4.1
- files_trashbin: 1.2.0
- files_versions: 1.5.0
- files_videoplayer: 1.1.0
- firstrunwizard: 2.1
- gallery: 17.0.0
- groupfolders: 1.1.0
- issuetemplate: 0.2.2
- logreader: 2.0.0
- lookup_server_connector: 1.0.0
- nextcloud_announcements: 1.1
- notes: 2.3.1
- notifications: 2.0.0
- oauth2: 1.0.5
- password_policy: 1.2.2
- provisioning_api: 1.2.0
- quota_warning: 1.0.1
- ransomware_protection: 1.0.1
- serverinfo: 1.2.0
- sharebymail: 1.2.0
- spreed: 2.0.1
- survey_client: 1.0.0
- systemtags: 1.2.0
- tasks: 0.9.5
- theming: 1.3.0
- twofactor_backupcodes: 1.1.1
- updatenotification: 1.2.0
- workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
- activitylog
- encryption
- files_antivirus
- user_external
- user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocaacnf00r5p",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxx.xxx",
        "xxx.xx",
        "192.168.x.x",
        "192.168.x.x"
    ],
    "datadirectory": "\/xxx",
    "overwrite.cli.url": "https:\/\/xxx\/xxx",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "xxx",
    "dbhost": "xxx",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0
    },
    "session_lifetime": 3600,
    "htaccess.RewriteBase": "\/nextcloud",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "noReply",
    "mail_domain": "xxx",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "xxx",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 0,
    "cron_log": true,
    "log_rotate_size": 104857600,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\Movie"
    ],
    "preview_max_filesize_image": 200,
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "singleuser": true,
    "updater.release.channel": "production"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Message and object data is not available on emails atm,
so we can not use them either...

Fix #6211 
Fix #5684

cc @JK74

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I commented on a file and the activity email looks a bit empty:

bildschirmfoto 2017-09-05 um 20 20 23

**Comment by nickvergessen** [comment]
Which language are you using? German DU is working fine here:
* Du hast test kommentiert
* User One kommentierte test

**Comment by nickvergessen** [comment]
bildschirmfoto vom 2017-09-06 09-48-44

Also "Sie" works great

**Comment by MorrisJobke** [comment]
> Also "Sie" works great

I guess this one. :/ Let me redo the check.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by ChristophWurst — APPROVED** [review]
LGTM

**Pull request merged**
