### PR TITLE
Nextcloud 13 is not compatible with newer than php 7.2

### PR DESCRIPTION
**Pull request by rullzer**
Easy one.
Just so we don't forget and have people try NC13 with a to new version of php.

### CODE REVIEW

**Comment by nickvergessen** [comment]
There should be more? remote.php? ocs/?

**Comment by rullzer** [comment]
@nickvergessen they include base.php

**Comment by ChristophWurst** [comment]
> There should be more? remote.php? ocs/?

Based on what/where we currently check for a min-version, also `console.php` should have a check: https://github.com/nextcloud/server/search?utf8=%E2%9C%93&q=PHP_VERSION

**Comment by nickvergessen** [comment]
> they include base.php

yes @rullzer but I don't see any checking there either?

**Comment by LukasReschke** [comment]
> There should be more? remote.php? ocs/?

If we do that we need  to also add a 500 error status code. Otherwise our sync clients may get a 200 and sync down the text error message … 😱

**Comment by nickvergessen** [comment]
Well the same happens when there is another language based error?
That's exactly why I would like to "stop" these pages as well

**Comment by MorrisJobke** [comment]
@rullzer Could you make this a 500 page?

**Comment by MorrisJobke** [comment]
Let's move this to 14 and maybe backport it.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍 It now also serves a 500 status code

**Comment by MorrisJobke** [comment]
CI failure should be fixed by #7458

**Comment by rullzer** [comment]
Lets get this into 13 then. So it is there from the start.

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
Should also be documented somewhere, docs or release notes, or both

**Comment by MorrisJobke** [comment]
> Should also be documented somewhere, docs or release notes, or both

Already is ;)

**Comment by MorrisJobke** [comment]
Let me rebase - to check if CI is green.

**Comment by MorrisJobke** [comment]
Failure is due to a connection issue while cloning -> merge

**Pull request merged**
