### PR TITLE
fix CacheJail::filterCacheEntry when entry is already filtered

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Is there no way to not call it then? because then we can type hint it as array instead of doing it that way.

**Comment by icewind1991** [comment]
I'm not sure what code path triggers this, I only have the error being logged that the method is being called with `false`.

Adding a type hint would be nice in the long term but would require either being able to reproduce things locally or debug patch cycles to properly figure out where this issue comes from.

**Comment by rullzer** [comment]
Master is Nextcloud 22 now.
If this should go into 21 it should be backported.

**Review by rullzer — APPROVED** [review]

**Comment by GitWidi** [comment]
This error also appears on NC 20 and my provider does not support MySQL 8 yet.
Is there a chance for a backport to NC 20?

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@icewind1991 a wild conflict appears

**Comment by icewind1991** [comment]
No longer needed with https://github.com/nextcloud/server/pull/25136

**Pull request closed without merging**
