### PR TITLE
Improve 2FA provider selection screen

### PR DESCRIPTION
**Pull request by ChristophWurst**
@jancborchardt do your magic 🧙

Fixes https://github.com/nextcloud/server/issues/10728.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Screenshots

bildschirmfoto von 2018-10-01 20-39-40
bildschirmfoto von 2018-10-01 20-39-49
bildschirmfoto von 2018-10-01 20-39-56

**Review by jancborchardt — APPROVED** [review]
Design magic done 🔮✨

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
There is a `<span>` wrapping the Submit text on the button which is unnecessary and have no cursor:pointer :)

Otherwise all fine

**Comment by ChristophWurst** [comment]
> There is a `<span>` wrapping the Submit text on the button which is unnecessary and have no cursor:pointer :)

@jancborchardt fix it :point_up:

**Comment by jancborchardt** [comment]
@skjnldsv that I actually fixed (on Christoph’s computer ;), but it’s in the twofactor_totp app, which is not part of the server: https://github.com/nextcloud/twofactor_totp/pull/277/

**Comment by skjnldsv** [comment]
Ah yes! You rocks! :guitar:

**Pull request merged**
