### PR TITLE
fix missing semicolon to fix themed logo on log in page

### PR DESCRIPTION
**Pull request by jancborchardt**
Seems it was lost in acd11729 @juliushaertl ;) Was that backported somewhat? If so we need to backport this fix as well.

Please review @nextcloud/theming

### CODE REVIEW

**Comment by jancborchardt** [comment]
PR was backported to stable10 so I’ll create a backport of this fix as well. :)

**Comment by nickvergessen** [comment]
Unit test needs adjustments as well, see `OCA\Theming\Tests\Controller\ThemingControllerTest`

**Comment by jancborchardt** [comment]
@nickvergessen already force pushed ;)

**Comment by jancborchardt** [comment]
Backport at https://github.com/nextcloud/server/pull/683

**Comment by nickvergessen** [comment]
Yeah, but the tabs are missing ;)

**Comment by juliushaertl** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
