### PR TITLE
Make sure the file information is available when sending the email

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix https://github.com/nextcloud/activity/issues/108

@Huster-at-github can you test this? Would be awesome.
Note: it only works for new actions. Already triggered action can not be adjusted.

### Steps
1. Un-/Favorite a file and select to receive emails for it.
2. Send the email by running cron (change activity_mq.amq_latest_send and jobs.last_run and jobs.last_checked for cheating)
3. See the email

### CODE REVIEW

**Comment by nickvergessen** [comment]
@schiessle @LukasReschke please review this easy thing ;)

**Comment by Huster-at-github** [comment]
Don't know what to do:

* Marked a new file as favorite
* Run cron.php as user www-data
* 1,5 hours later got this e-mail:

* Du hast  zu deinen Favoriten hinzugefügt - Heute um 21:59:11

**Comment by nickvergessen** [comment]
@MorrisJobke @rullzer easy to test ;)

**Comment by MorrisJobke** [comment]
I only can confirm that the body is not complete:

> Sie haben  zu Ihren Favoriten hinzugefügt (Heute um 20:03)

**Comment by nickvergessen** [comment]
Works here:
```
- You added test.txt;rm -rf test to your favorites (Today at 2:46 PM)
- You added whitepaper.odt to your favorites (Today at 2:46 PM)
- You added test to your favorites (Today at 2:46 PM)
- You removed test from your favorites (Today at 2:46 PM)
- You added test to your favorites (Today at 2:46 PM)
```

Also tested german:
```
- Sie haben test aus Ihren Favoriten entfernt (Heute um 14:47)
- Sie haben test.txt;rm -rf test aus Ihren Favoriten entfernt (Heute um 14:47)
- Sie haben whitepaper.odt aus Ihren Favoriten entfernt (Heute um 14:47)
- Sie haben test zu Ihren Favoriten hinzugefügt (Heute um 14:47)
```

@MorrisJobke since it fails for you, can you step in with the debugger?

**Review by MorrisJobke — APPROVED** [review]
Works now here. 👍

**Review by schiessle — APPROVED** [review]

**Pull request merged**
