### PR TITLE
Remove unneeded more-white icon

### PR DESCRIPTION
**Pull request by jancborchardt**
As a follow-up to @jenniferpiperek’s https://github.com/nextcloud/server/pull/17178 improving the more icon. :) Now also in the white version.

Quick review @nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
Why do you need this icon? 
We only use dark icons and use a dedicated scss mixin to generate variants :)
https://docs.nextcloud.com/server/17/developer_manual/design/css.html#scss-icon-mixins

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — CHANGES_REQUESTED** [review]
See comment

**Comment by jancborchardt** [comment]
Alright, so we remove it instead @skjnldsv?

Should I do the same with these icons:
info-white.svg
more-white.svg
caret-white.svg
error-white.svg
public-white.svg
confirm-white.svg
password-white.svg
checkmark-white.svg
checkbox-mark-white.svg
checkbox-mixed-white.svg

Are they not used anywhere directly using the path or so?

**Comment by skjnldsv** [comment]
No, I mean that's a lot of potential failing :p
We don't know if they're really not used anywhere else :see_no_evil: 

But for your icon-more, you can sure :)

**Comment by jancborchardt** [comment]
Changed it to removing the icon

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
What an event turn :grin:

**Comment by ChristophWurst** [comment]
Bildschirmfoto von 2019-11-13 15-51-11

:thinking: :thinking: :thinking: 

This breaks backup codes.

**Comment by ChristophWurst** [comment]
> No, I mean that's a lot of potential failing :p
> We don't know if they're really not used anywhere else see_no_evil

Guess ^ answers this.

**Comment by jancborchardt** [comment]
@ChristophWurst I totally understand why you prefer people to stick to the original purpose of a pull request. :D

**Pull request merged**
