### PR TITLE
Bump @nextcloud/vue from 7.7.0 to 7.8.0

### PR DESCRIPTION
**Pull request by blizzz**
* Resolves: # hopefully #36934

## Summary

- Merges @nextcloud/vue-richtext into @nextcloud/vue 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by AlvaroBrey — APPROVED** [review]
Does solve the login issue on Android webviews, although styles still look wrong

**Review by AndyScherzinger — APPROVED** [review]

**Comment by nickvergessen** [comment]
Since this PR CI is red again:
grafik

**Comment by nickvergessen** [comment]
Fix in https://github.com/nextcloud/server/pull/37069

**Pull request merged**
