### PR TITLE
Typecast shared mount's storage_id to int as documented + some refactor to avoid similar bugs

### LINKED ISSUE #3461: oc_mounts is updated all the time with the same information
### Steps to reproduce
1. Have a basic new NC11 or master instance, with local storage, mysql database
2. Create user{1,2}
3. Create n (5 in the following logs) folders in user1, share them with user2
4. Logon with user2, let the first time logon and database be populated, etc.
5. Log off user2
6. Start logging sql queries
7. Log on user2

### Expected behaviour
Performance is relatively smooth, and already being up to date, oc_mounts is not updated

### Actual behaviour
Login, and every page load is slow as **** (~10 sec on test instance with 5 folders shared)

Query log is full of 
```
		33661 Query	UPDATE `oc_mounts` SET `storage_id` = '1', `mount_point` = '/user2/files/folder 5/', `mount_id` = NULL WHERE (`user_id` = 'user2') AND (`root_id` = 36)
		33661 Query	UPDATE `oc_mounts` SET `storage_id` = '1', `mount_point` = '/user2/files/folder 4/', `mount_id` = NULL WHERE (`user_id` = 'user2') AND (`root_id` = 35)
170212 18:00:18	33661 Query	UPDATE `oc_mounts` SET `storage_id` = '1', `mount_point` = '/user2/files/folder 3/', `mount_id` = NULL WHERE (`user_id` = 'user2') AND (`root_id` = 34)
		33661 Query	UPDATE `oc_mounts` SET `storage_id` = '1', `mount_point` = '/user2/files/folder 2/', `mount_id` = NULL WHERE (`user_id` = 'user2') AND (`root_id` = 33)
		33661 Query	UPDATE `oc_mounts` SET `storage_id` = '1', `mount_point` = '/user2/files/folder 1/', `mount_id` = NULL WHERE (`user_id` = 'user2') AND (`root_id` = 31)
```

Full means, for 5 folders shared, when logging in then logging out, 95 updates (or 19/share), all updating to exactly the same values.

On my (relatively small) production system, each update (ie for each share) on oc_mounts takes 0.05 to 0.5s, with 10-30 shares/user...

### Server configuration
**Operating system**: Centos 7

**Web server:** apache

**Database:** mysql

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page) 11.0.1, master (as of f9d94edb0fd0ce)

**Updated from an older Nextcloud/ownCloud or fresh install:** Irrelevant (happens in local test setup as well as production instance)

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Irrelevant (happens in local test setup as well as LDAP instance)

### Diagnostics and hack-fix

Digging into the code, it seems that the function findChangedMounts() (lib/private/Files/Config/UserMountCache.php#L138), which determines if the db needs to be updated always returns all the mounts as having changed, because this condition is always true:
``` PHP
if (
	$newMount->getRootId() === $cachedMount->getRootId() &&
	(
		$newMount->getMountPoint() !== $cachedMount->getMountPoint() ||
		$newMount->getStorageId() !== $cachedMount->getStorageId() ||
		$newMount->getMountId() !== $cachedMount->getMountId()
	)
) {
	$changed[] = $newMount;
}
```

Looking into details, it seems that $newMount->getStorageId() is a string while $cachedMount->getStorageId() is an int (or vice versa, I don't remember), at least for the test case presented at the top.

I would have done a pull request, but I'm unsure whether getStorageID should be an int or a string. In the meantime, changing the !== to != solves the issue, and everything is fast and smooth again and I now believe the "Nextcloud 11 is faster" claims.

Note  that this might be related to people having issues in #2272 and #3134.

### PR DESCRIPTION
**Pull request by GreenArchon**
Fixes #3461 

Basically both paths of apps/files_sharing/lib/SharedMount.php/getNumericStorageId() returned a string (oups), which caused (maybe among other things) an === comparison to fail in determining if the mounts should be updated in the database. In my ~30 users/desktop clients 11.0.1 instance with ~20 folders shared each, this caused a ~10s extra delay in every page load.

55a37c1 fixes the problem with casts were applicable, and cc511ac refactors "CacheEntry" object creation in Cache.php to use the already existing and wonderful cacheEntryFromData() function which does all casts properly to allow CacheEntry data to return results as documented, instead of semi-regularly casting some of that data. 

Feel free to merge any of these commits separately if needed. Also, this should be backported to at least stable11 (as it is affected by #3461) and maybe older versions (haven't tested the bug on them).

Finally, note that I'm not that familiar with (or setup for) web development so the master checkout I did (**before these changes**) had some test failures (when running autotest) - I didn't know if it was the master failing or some system php packages missing and these changes don't cause more failures, but it should nevertheless be retested before merging.

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]

**Comment by GreenArchon** [comment]
This (or at least cc511ac which is the bugfix) should also be backported to stable11, as it is affected by #3461

I think @karlitschek is the one to ask?

**Comment by LukasReschke** [comment]
@icewind1991 Your thoughts on that? I'd tend to agree on that. Any objections?

**Comment by karlitschek** [comment]
@icewind1991 your call if this should be backpoted or not.

**Comment by icewind1991** [comment]
Backport is fine

**Pull request merged**
