### PR TITLE
Implemented short quota-design v2

### LINKED ISSUE #10124: Quota in Files-App takes to much space
### Steps to reproduce
1. Set Quota to >100Gb
2. Fill Nextcloud with big Files 
3. Open File-App

**Nextcloud version:**
13.0.4

The Quota can break out of the intended bounds. This breaks the style.
I propose to cut off sub-zero decimal places to gather more space if the used and or available exceeds a given size.

### PR DESCRIPTION
**Pull request by newhinton**
Closes #10124
See #10245
See #10321

### CODE REVIEW

**Comment by newhinton** [comment]
jancborchardt MorrisJobke While i was recreating the pr, i discussed this with some people, and we had the great idea to not show the used size at all. Something like 65% of 6TB would be way more informative to the user on the first glance, and when he needs more precise information, he can look at the tooltip/his settings.

( Maybe we could create a modal in the future, which opens when the quota item is clicked, as i discussed with jancborchardt )

**Comment by newhinton** [comment]
quota

**Review by MorrisJobke — APPROVED** [review]
Looks nice 👍

**Comment by MorrisJobke** [comment]
> See #10124
> Closes #10245
> Closes #10321

Once you do this the other way around it makes more sense IMO. Because it then closes actually the issue and you reference the closed PRs.

> Closes #10124
> See #10245
> See #10321

;) Github does the closing then automatically the issue.

**Review by jancborchardt — APPROVED** [review]
Looks good! :+1:

**Comment by MorrisJobke** [comment]
let me rebase this one and then we can merge it.

**Comment by rullzer** [comment]
CI is failing

**Comment by MorrisJobke** [comment]
Let's move this to 16.

**Comment by newhinton** [comment]
@rullzer This error seems to be caused by the new value in the files-app navigationbar valueholder, which gets an additional value of 'usage_relative_unprecise'. I have added it to the template in the test, but the tests are not expecting this value. Where would i need to add this value to the expected ones?

**Comment by newhinton** [comment]
I hope this fixes the CI, so we can merge it

**Comment by newhinton** [comment]
Actually i dont know why ci is failing. There is an additional value in the array ( 'usage_relative_unprecise' => 123.0), but the last commit does not contain that value or the code that adds this. So it should not fail because of that

**Comment by danielkesselberg** [comment]
Could you rebase your branch again and fix the conflicts? CI should pass than.

**Comment by danielkesselberg** [comment]
Rebased your branch and moved '%' into the string.

**Review by kesselb — APPROVED** [review]

**Comment by jancborchardt** [comment]
Btw @newhinton @danielkesselberg will you come to our next Contributor Week in Stuttgart in March? :)
https://nextcloud.com/blog/the-contributor-week-is-over-time-to-plan-for-the-next-one/
As you probably know, as contributors you can apply for travel/accomodation support!

**Pull request merged**
