### PR TITLE
Handle non existing settings again

### PR DESCRIPTION
**Pull request by CarlSchwan**
See https://github.com/nextcloud/server/pull/28189#issuecomment-1140874991

### CODE REVIEW

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by CarlSchwan** [comment]
ci failures unrelated

**Comment by nickvergessen** [comment]
CI failure "NoDB" is related

**Comment by nickvergessen** [comment]
Follow up in https://github.com/nextcloud/server/pull/32667

**Pull request merged**
