### PR TITLE
Avatar fixes for access-control app

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix https://github.com/nextcloud/files_accesscontrol/issues/32
### Steps
1. Create files access rule to block by "File tagged with `test`"
2. Upload an image
3. Assign tag `test` to the image
4. Go to personal settings, select avatar from folder and select the tagged image
### Before

> An error occurred: Internal Server Error (500)
### After

> The selected file cannot be read

### CODE REVIEW

**Comment by rullzer** [comment]
So the first part we can catch. (If preview endpoint return 403 then just display the mimetype icon).

The second one might be a bit trickier.

**Comment by rullzer** [comment]
Of course all the logic in oc-dialogs is slightly different. Basically we want to call lazyloadpreview on the previews in the dialog. But for some reason this fails hard for me.

I'm not sure howe we can go around not displaying those items. As migcally filtering them out is also kind of weird.

**Comment by nickvergessen** [comment]
Ready to review, since the open issues have been addressed by https://github.com/nextcloud/server/pull/1756

@MorrisJobke @LukasReschke @rullzer

**Comment by MorrisJobke** [comment]
> Ready to review, since the open issues have been addressed by #1756

Could you post reproduction steps?

**Comment by nickvergessen** [comment]
Added steps in first post

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@nickvergessen Unit tests are failing

**Comment by nickvergessen** [comment]
Should be fixed

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Ignore CI (hiccup of todays testing)-> merge

**Pull request merged**
