### PR TITLE
Fix admin password strengthify tooltip

### PR DESCRIPTION
**Pull request by st3iny**
Fixes the admin password strengthify tooltip not being shown on the install page.

Unfortunately, the console is spammed with unavoidable deprecation warnings (ref #12980):   
`tooltip.js:36 Deprecated call $.tooltip('fixTitle') has been deprecated and should be removed`

This has to be fixed in the upstream library at https://github.com/MorrisJobke/strengthify.

# Before
tooltip-before

Console error:
```
jquery.strengthify.js:158 Uncaught TypeError: $wrapper.attr(...).tooltip is not a function
    at HTMLInputElement.drawStrengthify (jquery.strengthify.js:158)
    at HTMLInputElement.dispatch (jquery.js:5183)
    at HTMLInputElement.elemData.handle (jquery.js:4991)
```

# After
tooltip-after

### CODE REVIEW

**Comment by st3iny** [comment]
Rebased and fixed node build job

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
