### PR TITLE
Require PHPUnit 6.5 or higher 

### PR DESCRIPTION
**Pull request by nickvergessen**
`\PHPUnit_Framework_MockObject_MockObject` is still available and not deprecated, so we can keep that for now and have an easy diff on the transition.

Only "problem" for apps should be that `setExpectedException` is now `expectException`

### CODE REVIEW

**Comment by rullzer** [comment]
Ah we need to update the docker images as they ship phpunit 5.5.4 ;)

**Comment by rullzer** [comment]
Building in https://github.com/nextcloud/docker-ci/pull/71

**Comment by nickvergessen** [comment]
Fixed all risky and warnings, lets see

**Comment by MorrisJobke** [comment]
Memcached container fails. I pushed a fix to docker hub and waiting for the image to be available. Will then raise the version number here.

**Comment by MorrisJobke** [comment]
A @rullzer already pushed it. I just used his version now - let's see if this works.

**Comment by nickvergessen** [comment]
All ✅  😱 🎉

**Comment by rullzer** [comment]
WHOOHOO!!!!

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Nice 👍

**Pull request merged**
