### PR TITLE
fix(files): Correctly parse external shares for files UI

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/47618

## Summary

Sadly the attributes of internal and external shares are named differently, this adds handling for all remote share attributes so we handle them similar to internal shares.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Antreesy — COMMENTED** [review]
Can confirm that file_id is now correctly interpreted, and previews are shown.
image

I there a possibility to consider mountpoint? Redirecting doesn't work correctly unless file is not in the root folder
image

Received | Expected
-- | --
image | image

**Comment by susnux** [comment]
> I there a possibility to consider mountpoint? Redirecting doesn't work correctly unless file is not in the root folder

Sure fixed :)

**Review by Antreesy — APPROVED** [review]
Tested! 🥳

**Review by artonge — APPROVED** [review]

**Pull request merged**
