### PR TITLE
Fix "Error loading the shares list TypeError: "this is undefined"" fo…

### PR DESCRIPTION
**Pull request by nickvergessen**
…r conversation shares

### Steps
1. Enable talk app
2. As user 1 share a file in a conversation with user 2
3. As user 2 open the share tab of the file :boom: 

> Error loading the shares list TypeError: "this is undefined"
    i SharedWithMe.js:42
    processSharedWithMe SharingTab.vue:300
    e SharingTab.vue:231

UI only shows: "Unable to load the shares list"

### CODE REVIEW

**Comment by skjnldsv** [comment]
wow

**Review by skjnldsv — APPROVED** [review]

**Review by danxuliu — APPROVED** [review]
Tested and works (with the fixup) :+1: 

The condition is probably unneeded as now all conversations have a name, but it feels safer to keep it just in case I am missing something and it is still somehow possible that `shareWithDisplayName` is null/undefined.

**Review by juliusknorr — APPROVED** [review]

**Comment by nickvergessen** [comment]
backport to stable18 in https://github.com/nextcloud/server/pull/19824

**Pull request merged**
