### PR TITLE
Add action to clear all weather favorites

### PR DESCRIPTION
**Pull request by julien-nc**
Small weather widget improvement allowing users to delete all favorites at once.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by jancborchardt** [comment]
I’d say we’re adding a bit too many controls here? :D We also e.g. don’t have the ability to "Remove all favorites" in e.g. Files or Talk, so we don’t really need that in the small weather widget?

**Comment by eneiluj** [comment]
@jancborchardt I agree it makes the menu grow. I just thought it would be more convenient than to delete them one by one which is more fastidious than in Files.

An alternative would be to provide a way to delete a favorite directly in the menu instead of having to select it and then press "remove from favorites". What do you think?

Or we just keep it like that, fine by me :grin:.

**Comment by eneiluj** [comment]
How about that?
del-fav

**Comment by jancborchardt** [comment]
> How about that?
> del-fav
> 

Sorry for the late reply – that is a nice solution! :)

**Pull request merged**
