### PR TITLE
Create a login bundle for login page scripts

### PR DESCRIPTION
**Pull request by ChristophWurst**
Once done this will make it obsolete to load 95% or the scripts we currently load on the login page, meaning that users will see faster page loads when the open the login page on a (new) device with empty caches.

- [x] Requires `OC.config` to be migrated to the main bundle https://github.com/nextcloud/server/pull/15293
- [x] Requires `OC.generateUrl` to be migrated to the main bundle https://github.com/nextcloud/server/pull/15291
- [x] Requires `OC.getRootPath` to be migrated to the main bundle #15295

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Once done this will make it obsolete to load 95% or the scripts we currently load on the login page, meaning that users will see faster page loads when the open the login page on a (new) device with empty caches.

Or after an update :wink:

**Comment by ChristophWurst** [comment]
Tested and works :rocket: :dancer: :confetti_ball:

**Review by skjnldsv — APPROVED** [review]
Wow!! Yeeeeesss!!  :rocket:  :rocket: :pray:

**Review by MorrisJobke — APPROVED** [review]
Works, but for me the `main.js` with 1,2 MB is still loaded. Is this correct?

**Comment by MorrisJobke** [comment]
Also before it was 32 requests with 1,7 MB in total and after it is 29 requests with 2,1 MB. 🤔

**Comment by ChristophWurst** [comment]
> Works, but for me the `main.js` with 1,2 MB is still loaded. Is this correct?

I actually haven't checked recently. But it could very well be the case as it's just loaded everywhere.

**Comment by ChristophWurst** [comment]
It's loaded for every template https://github.com/nextcloud/server/blob/65964a537adbb5d68c014e0acf0aabd432b00f7b/lib/private/legacy/template.php#L121. This has to be adjusted slightly to only load a predefined set of scripts for the different types of templates we have.

**Comment by MorrisJobke** [comment]
I fixed the conflicts here.

**Comment by MorrisJobke** [comment]
Looks good except the git clone problems. Merging now.

**Comment by icewind1991** [comment]
This change breaks password reset

**Pull request merged**
