### PR TITLE
Update crl after revoke shifts.csr

### PR DESCRIPTION
**Pull request by vitormattos**
Reference: nextcloud/app-certificate-requests#597

### CODE REVIEW

**Review by mgallien — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by vitormattos** [comment]
@blizzz I think that the backport bot got an error and didn't executed. Wasn't created the backport's PR.

**Comment by blizzz** [comment]
if that fails again we have to copy that file manually

**Pull request merged**
