### PR TITLE
Add base unit

### PR DESCRIPTION
**Pull request by marcoambrosini**
Suggested by @jenniferpiperek some time ago, I've been using it for padding, margins and so forth. Thought it was good to have a variable for it.

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by skjnldsv** [comment]
I think this needs to receive a lot more comments and documentation for people to understand the implications of such variables. I don't think having this laying around will change anything or make developers use it :thinking:

**Comment by ma12-co** [comment]
Right.. Do you have any suggestion? @jancborchardt you too: how should we explain this?
As said, I mainly have used this for spacing (paddings and margins), I think with good results. Should we encourage the use of it only for that or also for other things? 
Would It make sense to make some of the other variables dependent from this??
e.g.
```
$clickable-area: $base-unit * 11;    // 44px
$default-line-height: $base-unit * 6;    // 24px
$default-font-size: $base-unit * 0,9375;    // 15px
```

**Comment by skjnldsv** [comment]
> Should we encourage the use of it only for that or also for other things?
> Would It make sense to make some of the other variables dependent from this??

I think it is a good thing to have have everything rely on dedicated variables. :)
This is why we have the icon-margin/spacing and clickable-area in the components.
But I'm afraid adding this requires us to elaborate and have a dedicated page on our docs for it. As this would be a very important thing to push in the NC ecosystem :wink:

**Comment by rullzer** [comment]
What are the next steps here?

**Comment by ma12-co** [comment]
Yeah, next step is Marco cleans up his open PR after vacation :see_no_evil:

**Comment by jancborchardt** [comment]
@marcoambrosini will there be a follow-up to this though? It’s still a good and valid concept.

**Comment by marcoambrosini** [comment]
Let's discuss this in design call maybe?

**Pull request closed without merging**
