### PR TITLE
only need to setup root for groupfolders

### PR DESCRIPTION
**Pull request by icewind1991**
This is done before the `substr_count($path, '/') < 2` because it needs to trigger with `$path=="/__groupfolders"`

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by icewind1991** [comment]
> wondering if this will break for nested group folders though ?

It shouldn't matter nested group folders don't "care" about their parent groupfolder

**Comment by PVince81** [comment]
@CarlSchwan said he would test it, that will make it a certainty :smile:

**Comment by PVince81** [comment]
I'm preemptively merging this to save some time for the backport, would still be good to test to confirm

**Pull request merged**
