### PR TITLE
fix: gracefully parse non-standard trusted certificates

### PR DESCRIPTION
**Pull request by st3iny**
* Resolves: _none_

## Summary

The format `-----BEGIN TRUSTED CERTIFICATE-----` is non-standard and only used by OpenSSL. However, they can still be parsed by PHP through OpenSSL if the separator strings are simply replaced.

I also added a simple unit test with a sample certificate.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM and new unit test seem to pass 😎

**Review by provokateurin — APPROVED** [review]

**Pull request merged**
