### PR TITLE
fix(files): allow silent batch actions errors

### PR DESCRIPTION
**Pull request by skjnldsv**
For [approval](https://github.com/nextcloud/approval/pull/114), after a few discussions with @julien-nc 

If some actions returned null, we assume the dev wants a silent batch action.
That way a failure can still keep the failed items selected, but not display the failure (and letting the dev do so!)

### CODE REVIEW

**Review by julien-nc — APPROVED** [review]
:blue_heart:

**Review by juliusknorr — APPROVED** [review]

**Review by nfebe — APPROVED** [review]

**Comment by skjnldsv** [comment]
/backport 1c30e0793486af12214ac8b688d14e18609a620c to stable28

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/42490

**Pull request merged**
