### PR TITLE
[stable 17] Fix removing groups that have a slash in the name

### PR DESCRIPTION
**Pull request by gary-kim**
Backport of #18228

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Comment by skjnldsv** [comment]
Ah well, we should not need 15 as this is EOL

**Comment by skjnldsv** [comment]
Care to manually backport to stable16 @gary-kim :)

**Comment by gary-kim** [comment]
> Care to manually backport to stable16 @gary-kim :)

Can do!

**Comment by MorrisJobke** [comment]
> EDIT: Wait... #18284

@gary-kim Thanks for the manual backports 👍 Could I ask you to remove the "backport-request" label from PRs that are backported? In this way we can easily find the closed PRs with this label that haven't been backported yet. :) Thanks

**Pull request merged**
