### PR TITLE
Add timeout for requests to appstore

### PR DESCRIPTION
**Pull request by MorrisJobke**
Otherwise the request runs nearly endless. I'm also fine with a higher value, but 10 seconds is already quite long. If you need to wait that long for every app during the update you have already spend some while ;)

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
I'd still vote for making this the default 🙈

**Comment by LukasReschke** [comment]
> If you need to wait that long for every app during the update you have already spend some while ;)

Shouldn't that only happen once anyways since the response is cached or does this not work on upgrade scenarios?

**Comment by MorrisJobke** [comment]
> Shouldn't that only happen once anyways since the response is cached or does this not work on upgrade scenarios?

Nope ... it is re-requested, because we don't log failures ;)

**Review by rullzer — APPROVED** [review]
YES!

**Comment by MorrisJobke** [comment]
Could anybody of you look into those weird failures? I will leave you now :P

**Comment by nickvergessen** [comment]
The "weird" failures where non-matching mock calls

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
