### PR TITLE
Theming: Add logo and background to ThemingDefaults

### PR DESCRIPTION
**Pull request by juliusknorr**
This PR adds logo and background to the ThemingDefaults class. This allows further code in the theming app to query the current logo/background image url.

### CODE REVIEW

**Comment by juliushaertl** [comment]
Ok, I've tried to figure out why the tests of #770 are failing. This PR contains the set of backend changes for the theming app that I think introduce the failing tests.

@icewind1991 it would be really great if you could have a look.

**Comment by juliushaertl** [comment]
cc @nickvergessen as you mentioned something about the loading order in #770.
what loading order were you refering to?

**Comment by nickvergessen** [comment]
Had a quick look, and we can fix this by using the lazy root, but well that is not as clean as it should be. But will push this never the less now.

**Comment by juliushaertl** [comment]
@nickvergessen Awesome! Thanks for the cleanup as well.

Ready for review now. I'll create a new PR for the rest of #770 and after merge we also continue with #771 and #840.

**Comment by juliushaertl** [comment]
cc @schiessle @LukasReschke for review

**Comment by nickvergessen** [comment]
:+1:

**Comment by rullzer** [comment]
LGTM

**Pull request merged**
