### PR TITLE
add marker interface to mark system mount points for encryption

### PR DESCRIPTION
**Pull request by icewind1991**
This allows apps to decide whether a system or user key should be used for encryption instead of having to add app-specific logic in the encryption logic.

### CODE REVIEW

**Comment by icewind1991** [comment]
needed for https://github.com/nextcloud/groupfolders/pull/2057

**Comment by PVince81** [comment]
see CI failures

**Comment by icewind1991** [comment]
"backport" is here: https://github.com/nextcloud/server/pull/33700

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by CarlSchwan — APPROVED** [review]

**Pull request merged**
