### PR TITLE
Nextcloud 13

### PR DESCRIPTION
**Pull request by MorrisJobke**
No change (beside translations) to RC3 (#8027)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@jospoortvliet Just for clarity: tomorrow is the day, right?

**Comment by pasxalisk** [comment]
Hello,

I noticed on the last versions of nextcloud (currently RC3 running on my raspberry pi 3) that althought with the latest upload in chuncks of 8192 fix when a large file(>2 GB) upload is completed i get the error message "Chunks on server do not sum up to XXX but to XXX" (same number).

A fix for that is done by changing the file /var/www/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php
This line :    if ((int)$expectedSize !== $actualSize) {
With this:   if ($expectedSize !== (string)$actualSize) { 

Is this fix or any other workaround included in the 13 version?

Thank you

**Review by blizzz — APPROVED** [review]

**Comment by MorrisJobke** [comment]
If the release is shifted by another week we maybe include https://github.com/nextcloud/server/pull/8112 into the 13.0.0 as well.

**Comment by Arjoni** [comment]
@MorrisJobke I think the release should not be shifted again. Many people are looking forward to the new release with all the new features. It makes sense to add it to the next release.

**Comment by voxdemonix** [comment]
We really want the new features (Nextcloud talk!), but if without #8112  it's not working on no 64bit machine it's can be really boring with ARM machine (not compatible with x64).

**Comment by Arjoni** [comment]
@voxdemonix I see. That makes sense. I am curious why a week is needed to just change the variable from int to flow.

**Comment by MorrisJobke** [comment]
> @MorrisJobke I think the release should not be shifted again. Many people are looking forward to the new release with all the new features. It makes sense to add it to the next release.

Talk with @jospoortvliet and @karlitschek about this 😉

**Comment by testbird** [comment]
Well, always watch out seriously if doing "float comparison" !
http://floating-point-gui.de/errors/comparison/

**Comment by jospoortvliet** [comment]
Hey,

So the server is ready but we wanted to have a seriously testable desktop client release with E2EE ready. The first decent builds were made yesterday, today we felt it was time to move to Windows builds and hopefully by the end of the week we have Mac OS builds - so we think we can release next week, give people something to really test and play with.

Hope was we'd even have the E2EE stable by now but sadly, it is hard to do it right and we have to do it right (don't want to lose data, neither to hackers nor to crashes) so this will simply take a bit more time. Help welcome 😄

**Comment by MorrisJobke** [comment]
Let's do a final RC until next week: #8127

**Comment by tflidd** [comment]
I pushed the realease date about one week on:
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by MorrisJobke** [comment]
@tflidd Thanks 👍

**Pull request closed without merging**
