### PR TITLE
make .button inline-block

### LINKED ISSUE #3752: Backupcodes button sizes
If you want to call something a **papercut** ... then ... this 😅😜 The buttons should all have the same size 😉 @nextcloud/designers 

bildschirmfoto 2017-03-07 um 16 14 01

### PR DESCRIPTION
**Pull request by violoncelloCH**
fixes #3752

hope this is the right place to insert this

Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

### CODE REVIEW

**Comment by skjnldsv** [comment]
> hope this is the right place to insert this

Should be :)

@nextcloud/designers

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
It shouldn't break the design in a lot of places, but we will need to keep an eye open :+1:

**Comment by jancborchardt** [comment]
Found an issue with this, a `.hidden` rule is overwritten in the Versions tab of the Files sidebar:
hidden element showing

No quick idea how to best fix this. `!important` would probably overwrite everything the other way around, so that’s not good. ;) @violoncelloch @skjnldsv any idea?

**Comment by pixelipo** [comment]
`.hidden` class should probably actually be `!important`, as it (in theory) should override any other displays. That's the whole point of that class - control the visibility of an item by toggling a single class.

The problem is, changing it now could cause all sorts of trouble who-knows-where...

**Comment by jancborchardt** [comment]
> `.hidden` class should probably actually be `!important`, as it (in theory) should override any other displays. That's the whole point of that class - control the visibility of an item by toggling a single class.

True – pull request at https://github.com/nextcloud/server/pull/12167

> The problem is, changing it now could cause all sorts of trouble who-knows-where...

Also true – but that’s what bugfixing phase is for. And we already know that not having it for sure causes an issue.

**Comment by skjnldsv** [comment]
@jancborchardt i agree. Could you propose a pr for that? :)

**Comment by violoncelloch** [comment]
@skjnldsv 
> True – pull request at #12167

**Pull request merged**
