### PR TITLE
fix(files_sharing): Cleanup error messages

### PR DESCRIPTION
**Pull request by provokateurin**
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nfebe — APPROVED** [review]
Maybe some of the messages can be more specific? For example the try-catch that fails due to date parsing and only that can be a bit more explicit at maybe the expense of consistency with the same "Failed to..."

**Review by Altahrim — APPROVED** [review]

**Comment by provokateurin** [comment]
> Maybe some of the messages can be more specific? For example the try-catch that fails due to date parsing and only that can be a bit more explicit at maybe the expense of consistency with the same "Failed to..."

Fixed. The called method was already returning a proper error message, so I aligned all the uses of it.

**Pull request merged**
