### PR TITLE
[stable17] Fix listing users in groups with slash in the name

### PR DESCRIPTION
**Pull request by gary-kim**
Backport of #18462

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
Needs a rebase

**Comment by skjnldsv** [comment]
Ah well, we should not need 15 as this is EOL

**Comment by skjnldsv** [comment]
Care to manually backport to stable16 @gary-kim :)

**Comment by gary-kim** [comment]
Wait... #18486

**Pull request merged**
