### PR TITLE
Allow sub-admins to access delegated settings.

### LINKED ISSUE #30927: SubAdmins cannot access delegated admin settings???
According to this line:

https://github.com/nextcloud/server/blob/764e452ef6980c344617e6ad2214763e9781d0b7/lib/private/Settings/Manager.php#L341

sub-admins get access to admin-settings which inherit from `ISubAdminSettings`. However, PR #28189 introduced admin-settings delegation. But the corresponding line following

https://github.com/nextcloud/server/blob/764e452ef6980c344617e6ad2214763e9781d0b7/lib/private/Settings/Manager.php#L350

are never reached for sub-admins. As a result, If a member of a group with for which admin settings have been delegated, is also a sub-admin, then this user will not have access to the delegated settings.

I would assume that this was not intended? I have proposed a fix in PR #30926

### PR DESCRIPTION
**Pull request by rotdrop**
Close #30927

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
@rotdrop your commit needs DCO :)

**Comment by rotdrop** [comment]
OK, I have signed the commit and force-pushed it to my fork.

**Comment by artonge** [comment]
Thanks @rotdrop ! :)

**Comment by gmaxbass** [comment]
Hi, I've a similar need: letting a sub admin promote a normal user to sub admin (sub admin delegation) within the same group.
I'm wondering if this pull-request covers this case delegating a sub-admin to administer only specific group(s).

**Pull request merged**
