### PR TITLE
Correct spelling of Brute Force and other fixes

### PR DESCRIPTION
**Pull request by Valdnet**
1. Correcting the spelling of "Bruteforce" to "Brute Force".
2. Adding quotation marks.
3. Fixed a typo.

### CODE REVIEW

**Review by come-nc — APPROVED** [review]
Not an english native speaker so I do not know about the change itself but the PR won’t break anything :+1:

**Review by rakekniven — CHANGES_REQUESTED** [review]
"brute-force" is correct from my pov. Can you double check?

**Comment by Valdnet** [comment]
"brute-force" is an alternative spelling of this word.

**Comment by Valdnet** [comment]
I propose "Brute force" 😁.

**Review by rakekniven — APPROVED** [review]

**Comment by Valdnet** [comment]
So we change it to "Brute-force" 😉.

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
