### PR TITLE
fix: Make app menu overflow entries vertically aligned

### PR DESCRIPTION
**Pull request by susnux**
* For https://github.com/nextcloud/server/issues/46016#issuecomment-2268410817
## Summary

The `name` property expects a `text` and just adds basically a "heading" for the text, so lets instead just utilize the default slot.

image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by st3iny** [comment]
What happened here? :

Over 100 commits doesn't look right.

**Comment by AndyScherzinger** [comment]
@st3iny nope, I did a rebase but GH went nuts, showed the processing changes spinner next to the PR title and now this....
I'll try another rebase... Let's see what GH thinks about that then...

**Comment by AndyScherzinger** [comment]
@susnux sorry for any mess I might have caused. Tryed to warp it up and get it merged. However currently I can't clone the repo or fetch latest changes on an existing checkout, nor do a git pull all of them fail against GH...

**Pull request merged**
