### PR TITLE
Fix type error in Sabre/Connector/Directory

### PR DESCRIPTION
**Pull request by CarlSchwan**

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]
Tested and works

**Review by come-nc — APPROVED** [review]

**Review by tobiasKaminsky — CHANGES_REQUESTED** [review]
Can we have (at least) one test that checks this?

**Comment by blizzz** [comment]
related to some SabeDav update or a general error?

**Comment by PVince81** [comment]
see https://github.com/nextcloud/server/blob/master/build/integration/features/bootstrap/WebDav.php#L402 and extend

**Comment by tobiasKaminsky** [comment]
🚨🚨🚨 This breaks 3 of our android-library tests and this we always need to check for red CI…

**Comment by CarlSchwan** [comment]
I added a tests and the cal-dav-2 integration tests are now passing. still need one review

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
