### PR TITLE
Suppress 'PhanUndeclaredClassConstant'

### PR DESCRIPTION
**Pull request by rullzer**
Only way for now I found out how to make it pass again :see_no_evil:

### CODE REVIEW

**Comment by nickvergessen** [comment]
What, that sounds wrong

**Comment by rullzer** [comment]
It is. But I suspect this to be a bug in phan. Because those constants are properly declared.

**Comment by nickvergessen** [comment]
Than please open an issue there?

**Comment by rullzer** [comment]
Well I don't know if that is it. I didn't go into the internals or ran double checks. I just know that at some point this all started failing. I'm happy to close this but then we have failing CI.

**Comment by nickvergessen** [comment]
Fixed by https://github.com/phan/phan/commit/2d57fb00eca0c8587b480f39f5d5667e54a926a1

**Pull request closed without merging**
