### PR TITLE
[stable10] Opening the trashbin causes errors in log for files without preview

### PR DESCRIPTION
**Pull request by MorrisJobke**
- put a file without a generated preview in the trashbin
  (e.g. a *.docx file)
- open the trashbin
- following errors will show up in the nextcloud.log:
  - filesize(): stat failed for ...
  - fopen(...): failed to open stream: No such file or directory at ...
  - fread() expects parameter 1 to be resource, boolean given at ...
  - fclose() expects parameter 1 to be resource, boolean given at ...
  - imagecreatefromstring(): Empty string or invalid image at ...

This is because the preview code tries to load an SVG image, which
is obviously only text.

The fix simply handles this before the loading happens and the web UI
keeps showing the default mimetype icon.

cc @nickvergessen @rullzer @icewind1991 @LukasReschke @blizzz

### CODE REVIEW

**Comment by MorrisJobke** [comment]
backport of #1338

**Comment by nickvergessen** [comment]
Works, but the log spam was debug only anyway. :+1:

**Comment by rullzer** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Rebased to send the drone hook again.

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Restarted drone to fix the mysql race condition.

**Comment by MorrisJobke** [comment]
I added https://github.com/nextcloud/server/pull/1400 to this to avoid the mysql race condition

**Pull request merged**
