### PR TITLE
[oc] Register commands in info.xml

### PR DESCRIPTION
**Pull request by rullzer**
From https://github.com/owncloud/core/pull/26248

CC: @nickvergessen @MorrisJobke @LukasReschke @icewind1991

### CODE REVIEW

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Please add those to be tested with https://github.com/nextcloud/server/blob/master/tests/lib/InfoXmlTest.php

**Comment by rullzer** [comment]
Fixed

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Review by MorrisJobke — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
👍

**Pull request merged**
