### PR TITLE
chore: drop depedency php-parser

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: /

## Summary

Dear php-parser,

You were a great help to check that apps are compliant and we did not forget the since and deprecated annotations.
Thank you for all the service you provided us over the years.

## TODO

- [x] Check CI
- [x] Wait for https://github.com/nextcloud/server/pull/30349
- [x] Merge https://github.com/nextcloud/3rdparty/pull/1293
- [x] Rebase
- [x] Update documentation

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by vitormattos — APPROVED** [review]

**Comment by kesselb** [comment]
> Check CI

Failing integration-sharing-v1-video-verification should be fixed by https://github.com/nextcloud/server/pull/36389.

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Currently brings in Symfony Mailer change. So this is blocked by #30349

**Comment by kesselb** [comment]
Thanks, added a Todo to wait for #30349.

**Comment by blizzz** [comment]
> Thanks, added a Todo to wait for #30349.

Just merged

**Comment by nickvergessen** [comment]
Taking over since kessel is sick

**Comment by nickvergessen** [comment]
Repushed to have `--no-dev` committed https://github.com/nextcloud/3rdparty/pull/1303

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Update documentation

@kesselb please take care of this.

**Pull request merged**
