### PR TITLE
Enable sorting in file picker

### LINKED ISSUE #645: Filepicker: sort by modified date (or better: respect sorting as in files app)
Oftentimes you want to pick files you recently uploaded or updated, like in mail attachments. Hence it would be cool if there would be a way to sort by modified date. Maybe even better, respect the sorting of the folders exactly as in the Files app.

cc @icewind1991

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes #645 

This allows sorting the entries in the file picker by name, size or mtime.

List view:
image

Grid view:
image

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Working fine here!

**Comment by MorrisJobke** [comment]
* [ ] header also shown in the empty file list
bildschirmfoto 2018-11-13 um 16 27 47
* [ ] loading spinner is placed over the header
bildschirmfoto 2018-11-13 um 16 27 52

**Comment by MorrisJobke** [comment]
@juliushaertl Moved to 16, but we maybe want to back port this anyways, right?

**Comment by rullzer** [comment]
@MorrisJobke yes that is right

**Comment by juliushaertl** [comment]
@MorrisJobke Fixed.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by rullzer** [comment]
The backport failed in a way the bot did not handle it properly. I'll look into that

**Comment by juliushaertl** [comment]
We'll not backport this for now as discussed with @MorrisJobke

**Pull request merged**
