### PR TITLE
Use 11.0 instead 9.2

### PR DESCRIPTION
**Pull request by LukasReschke**
As discussed we're changing the version from 9.2 to 11.0 to make some more sense. (ref https://github.com/nextcloud/server/issues/2134)

This still requires the following work that I'm on at the moment:

- [x] Increase versions of apps in the Nextcloud organisation
  - [x] spreed (https://github.com/nextcloud/spreed/pull/87)
  - [x] calendar (already done)
  - [x] contacts (already done)
  - [x] nextant (already done)
  - [x] logreader (already done)
  - [x] firstrunwizard (https://github.com/nextcloud/firstrunwizard/pull/23)
  - [x] activity (https://github.com/nextcloud/activity/pull/73)
  - [x] files_pdfviewer (https://github.com/nextcloud/files_pdfviewer/pull/14)
  - [x] twofactor_sms (https://github.com/nextcloud/twofactor_sms/pull/11)
  - [x] files_texteditor (https://github.com/nextcloud/files_texteditor/pull/17)
  - [x] files_videoplayer (https://github.com/nextcloud/files_videoplayer/pull/10)
  - [x] gallery (https://github.com/nextcloud/gallery/pull/174)
  - [x] notifications (https://github.com/nextcloud/notifications/pull/39)
  - [x] serverinfo (https://github.com/nextcloud/serverinfo/pull/63)
  - [x] survey_client (https://github.com/nextcloud/survey_client/pull/42)
  - [x] external (https://github.com/nextcloud/apps/pull/17)
  - [x] files_automatedtagger (https://github.com/nextcloud/files_automatedtagging/pull/18)
  - [x] files_accesscontrol (https://github.com/nextcloud/files_accesscontrol/pull/47)
  - [x] templateeditor (https://github.com/nextcloud/templateeditor/pull/12)
  - [x] files_retention (https://github.com/nextcloud/files_retention/pull/12)
  - [x] announcementcenter (https://github.com/nextcloud/announcementcenter/pull/56)
  - [x] files_antivirus (https://github.com/nextcloud/files_antivirus/pull/11)
  - [x] user_saml (https://github.com/nextcloud/user_saml/pull/52)
  - [x] twofactor_totp (https://github.com/nextcloud/twofactor_totp/pull/83)
  - [x] twofactor_u2f (https://github.com/nextcloud/twofactor_u2f/pull/10)
  - [x] bookmarks (https://github.com/nextcloud/bookmarks/pull/304)
  - [x] nextcloud_announcements (https://github.com/nextcloud/nextcloud_announcements/pull/9)
- [x] Mail people that have uploaded already their app on the beta on apps.nextcloud.com
- [x] Adjust previous fallbacks
- [x] Replace `@since 9.2` with `@since 11.0`

cc @rullzer @icewind1991 @schiessle 

----

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Comment by MariusBluem** [comment]
I'm lovin it 😍🙈

**Comment by rullzer** [comment]
@since 9.2.0 => @since 11.0.0 :white_check_mark:

**Comment by MorrisJobke** [comment]
Works here 👍

**Comment by MorrisJobke** [comment]
Offline @rullzer said 👍 to this too ;) -> merge

**Pull request merged**
