### PR TITLE
Avoid having the same name for several workflows

### PR DESCRIPTION
**Pull request by come-nc**
## Summary

Trying to improve this situation:
Screenshot_20230321_095846

## TODO

- [ ] Do the same changes upstream in nextcloud/.github

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Those needs to be in the github template repository.

**Comment by come-nc** [comment]
> Those needs to be in the github template repository.

Removed changes to the workflow comming from the templates, see https://github.com/nextcloud/.github/pull/132 for those ones.

**Comment by come-nc** [comment]
@skjnldsv @nickvergessen This one is still needed for the workflows which are not from .github

**Review by nickvergessen — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM

**Pull request merged**
