### PR TITLE
theming: Separate `primary` and `background` colors - fix the header menu colors

### LINKED ISSUE #35482: The header icons are not visible when choosing a light background
How can we work around the following issue?

The header icons are not visible when choosing a light background image (same for admin chosen background image):
image

What about adding a switch that allows to invert the header icons? (I fear Ii don't see any other good solution to automate this)

cc @nimishavijay @jancborchardt

### LINKED ISSUE #42954: Topbar icons and text are controlled by wrong variable
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps

* Use default background image
* Change theming color to the yellow option

Default blue | Option yellow
---|---
✅  | 💥  Text and all icons on the right side have the wrong color (based on primary and not if background is bright/dark, but that fact is used by the app icons in top left with `var(--background-image-invert-if-bright)` vs. `var(--color-primary-text)`
Bildschirmfoto vom 2024-01-19 09-24-58 | Bildschirmfoto vom 2024-01-19 09-24-50

Default blue | Option yellow
---|---
💥  "More apps" icon has wrong color | 💥  "More apps" icon has wrong color 
Bildschirmfoto vom 2024-01-19 09-25-12 | Bildschirmfoto vom 2024-01-19 09-25-22

### LINKED ISSUE #44325: [Bug]: dark icon colore
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the v28 update I have the problem that the icons are displayed in black, also the text under the navigation
image

### Steps to reproduce

dont know

### Expected behavior

text and icons are white

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "rollenspiel.cloud",
            "192.168.100.11",
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/rollenspiel.cloud",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbtype": "pgsql",
        "version": "28.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "installed": true,
        "maintenance": false,
        "default_language": "de",
        "default_locale": "de",
        "default_phone_region": "DE",
        "allow_user_to_change_display_name": true,
        "knowledgebaseenabled": true,
        "theme": "",
        "defaultapp": "",
        "skeletondirectory": "\/mnt\/hdd\/skeleton",
        "trashbin_retention_obligation": "120, auto",
        "versions_retention_obligation": "120, auto",
        "appcodechecker": true,
        "updatechecker": true,
        "updater.release.channel": "stable",
        "check_for_working_webdav": true,
        "maintenance_window_start": 3,
        "loglevel": 2,
        "logdateformat": "d.m.Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 10485760,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_filesize_image": 50,
        "preview_max_scale_factor": 10,
        "data-fingerprint": "d76fcffe3970dd2910ea5d733e3ed673",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 1,
            "timeout": 1.5
        },
        "filelocking.enabled": "true",
        "twofactor_enforced": false,
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mail_sendmailmode": "smtp",
        "migrate_guest_user_data": true,
        "remove_guest_account_on_conversion": true,
        "keep_users_without_login": "no",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "gpgmailer",
            "oidc_login",
            "registration",
            "files_downloadactivity"
        ],
        "oidc_login_provider_url": "https:\/\/auth.rollenspiel.monster\/application\/o\/nextcloud\/",
        "oidc_login_client_id": "TjkzVgMvkHJnbZriUAGn9YsqyE0xzWwoa84hzlAk",
        "oidc_login_client_secret": "tqTH4KAbGLyYRFO7hyIHyJAMcEKWO2goMLUWQ3tslWUIiwjkstwqJ6r9yXDMUpwQ",
        "oidc_login_button_text": "Log in with Authentik",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - approval: 1.2.0
  - calendar: 4.6.6
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - collectives: 2.10.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.2
  - drop_account: 2.5.0
  - end_to_end_encryption: 1.14.3
  - event_update_notification: 2.3.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_antivirus: 5.4.2
  - files_lock: 28.0.2
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - fileslibreofficeedit: 1.1.0
  - firstrunwizard: 2.17.0
  - forms: 4.1.1
  - groupfolders: 16.0.4
  - guests: 3.0.1
  - integration_openai: 1.2.1
  - integration_openstreetmap: 1.0.12
  - integration_replicate: 1.1.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.7
  - maps: 1.3.1
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - oidc_login: 3.0.2
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.1.6
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - qownnotesapi: 23.12.0
  - quota_warning: 1.18.0
  - registration: 2.4.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.2
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - socialsharing_email: 3.1.0
  - spreed: 18.0.5
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tables: 0.6.6
  - tasks: 0.15.0
  - text: 3.9.1
  - text_templates: 1.0.5
  - theming: 2.3.0
  - translate: 2.1.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_email: 2.7.4
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.18.0
  - user_migration: 5.0.0
  - user_retention: 1.11.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0 (installed 1.3.0)
  - contactsinteraction: 1.9.0 (installed 1.3.0)
  - drawio: 3.0.2 (installed 3.0.2)
  - encryption: 2.16.0
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.20.0
  - files_linkeditor: 1.1.16 (installed 1.1.16)
  - files_markdown: 2.4.1 (installed 2.4.1)
  - metadata: 0.19.0 (installed 0.19.0)
  - recommendations: 2.0.0 (installed 1.3.0)
  - support: 1.11.0 (installed 1.5.0)
  - suspicious_login: 6.0.0 (installed 5.0.0)
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Fixes #42954
* Fixes #35482
* Fixes #44325

## Summary
This will fix one of the main issues we face with our theming: Currently primary color used to highlight elements is mixed and directly connected to the background color.

So the goal is to have two different colors:
1. `primary` to highlight elements - meaning used as an accent color
2. `background` to be used as background on the body or fallback if images failes to load, moreover this will be used to calculate the header menu text color.

To make this possible this PR is sadly bigger then I hoped, it contains following changes:
1. Add background / primary color for custom images\
Previously we had a primary color predefined for every shipped background image, but not for custom images so that users had to select a color manually. As preparation for the other steps I added a function to automatically calculate the mean color of the image so it can be used as the primary / background color.
2. Separate background and primary color\
While the primary color is intended to highlight elements, it can not always be used as the background color. So now primary is independent from background a user sets, the background color is, if not set directly, calculated as the mean color of the background image. That color is then used as a fallback if the background image could not be loaded and for calculating the color of the text used on the app menu and dashboard (they render directly on the background).
3. Adjust *dashboard* and the *header menu* to use that new color instead of `primary`
4. Adjust theming setting to configure primary and background color
5. Fixed our provided apps that have header menus to use color variables instead of the infamous color-filter.

## TODO

- [x] Tests
- [ ] How to implement migration? IRepairStep? All users need to copy `background_color` to `primary_color` user value

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by jancborchardt — COMMENTED** [review]
@susnux in which cases was the current state specifically a problem? :) I was even thinking we can phase out color-primary-element in favor of just color-primary – since for our default that is now unified to the darker blue.

I really like your point 1) for example so things are automatically generated
4) though seems to make stuff more complex, not sure we need the separation. But that's why I'm asking. :) cc @juliushaertl

**Comment by nickvergessen** [comment]
> I was even thinking we can phase out color-primary-element in favor of just color-primary – since for our default that is now unified to the darker blue.

Please keep our clients in mind that rely on these values and need a non-manipulated primary color, so they can do their own math using material design on Android and ... on iOS to generate colors matching their standards.

**Comment by juliushaertl** [comment]
> 4) though seems to make stuff more complex, not sure we need the separation. But that's why I'm asking

I think it would be good to have this separation, especially for cases where people disable user theming (like in corporate environments) and then want to have a static background image (+color). Icon inversion in the header menu needs to be based on the background color or image and not the primary element color so splitting that makes a lot of sense to me.

**Review by jancborchardt — COMMENTED** [review]
@nickvergessen @juliushaertl right, if you say it makes sense let’s go with it. :) I can’t judge the code though.

**Review by szaimen — COMMENTED** [review]
I just tested this and it works great! Amazing work @susnux :)

The only thing that did not work yet in my testing is this setting:
image

However we could also do this in a follow-up if you prefer. 
This PR is a huge improvement in my opinion :)

**Comment by susnux** [comment]
@szaimen

> I just tested this and it works great! Amazing work :)
> The only thing that did not work yet in my testing is this setting:

You need to use the "choose" button, this is a upstream (vue-library) issue and will be fixed soon!

**Review by szaimen — APPROVED** [review]
> @szaimen
> 
> > I just tested this and it works great! Amazing work :)
> > The only thing that did not work yet in my testing is this setting:
> 
> You need to use the "choose" button, this is a upstream (vue-library) issue and will be fixed there :)

Approving this then in order to not block this PR :)

**Review by st3iny — APPROVED** [review]
Let's get it in ASAP. Tested and works.

**Comment by szaimen** [comment]
seems like psalm and cypress ist still red :/

**Comment by szaimen** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by skjnldsv** [comment]
docs in https://github.com/nextcloud/documentation/pull/11850

**Pull request merged**
