### PR TITLE
Fix placeholder issues with multiplace spaces in the name

### LINKED ISSUE #21433: Error in contacts menu
### Steps to reproduce
1. Open the contacts menu in the top right
2. Close the menu again
3. open the menu again

Peek 2020-06-16 16-08

### Expected behaviour
Works

### Actual behaviour
Console error spam:
```
 TypeError: "e[0] is undefined"
    jQuery 2
    render contactsmenu.js:172
    render contactsmenu.js:99
    Y Underscore
    E/</e.prototype[i]</< Backbone
    render contactsmenu.js:95
    showContacts contactsmenu.js:352
    _loadContacts contactsmenu.js:480
```

### Server configuration

**Nextcloud version:** c.nc.c

cc @skjnldsv @juliushaertl

### PR DESCRIPTION
**Pull request by juliusknorr**
Steps to reproduce:

- Add a user with two spaces in its name `"Alice[space][space]twospaces"`
- Open the contacts menu

Fixes #21433

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
🙈🦾

**Review by georgehrke — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Comment by skjnldsv** [comment]
Needs rebase :(

**Pull request merged**
