### PR TITLE
fix(i18n): Corrected grammar

### PR DESCRIPTION
**Pull request by rakekniven**
Reported on Transifex

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by szaimen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Conflicting files
dist/files-main.js
dist/files-main.js.map

**Comment by szaimen** [comment]
@rakekniven this needs a manual rebase and then you can run the compile command again

**Review by Valdnet — APPROVED** [review]

**Comment by szaimen** [comment]
@rakekniven can you rebase the pr and fix conflicts or recreate it from master?

**Comment by szaimen** [comment]
> Why is it so difficult to apply such tiny changes?

Because of the compiled js

**Comment by szaimen** [comment]
> Isn't this done by switch "compile amend"?

No, because that command cannot resolve conflicts

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
