### PR TITLE
Add avatar contact img description

### PR DESCRIPTION
**Pull request by Pytal**
- For https://github.com/nextcloud/server/issues/36713

## Summary

Add descriptive text to the contacts menu avatar `img` elements

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by jotoeri — COMMENTED** [review]
Hmm, isn't that worse, as the screenreader reads the name on the avatar and then once again on the actual full-name text?

**Comment by Pytal** [comment]
> Hmm, isn't that worse, as the screenreader reads the name on the avatar and then once again on the actual full-name text?

Do you think we should add a separate label for the avatar @michaelnissenbaum?

**Comment by michaelnissenbaum** [comment]
@JuliaKirschenheuter From my perspective, Avatar should not be implemented as a link because we already have a 'View Profile' link that provides the same functionality. Avatar should simply be implemented as an img element with an "alt" attribute set to an empty string, so that screen readers will ignore this element. However, if you really want the Avatar element to remain interactive and be displayed, then you can use the aria-label attribute with an "a"-element or the "alt" attribute of the image.

**Review by JuliaKirschenheuter — COMMENTED** [review]
would be better to set `Avatar of __name__`? Or should we through away a link from avatar https://github.com/nextcloud/server/pull/36740#issuecomment-1439878082?

**Comment by Pytal** [comment]
> would be better to set `Avatar of __name__`? Or should we through away a link from avatar [#36740 (comment)](https://github.com/nextcloud/server/pull/36740#issuecomment-1439878082)?

Makes sense UX-wise to have it clickable so updated the description!

**Review by kesselb — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]

**Pull request merged**
