### PR TITLE
[stable23] Toggle profile globally

### PR DESCRIPTION
**Pull request by Pytal**
Backport of https://github.com/nextcloud/server/pull/29372

### CODE REVIEW

**Review by szaimen — APPROVED** [review]

**Comment by szaimen** [comment]
Is it expected that this changes much less files and code than in NC24? I didn't try it out but could do so...

**Comment by artonge** [comment]
> Is it expected that this changes much less files and code than in NC24? I didn't try it out but could do so...

It's due to the changes we did on the frontend files bundling.  The 24 PR changes all the output files, and this PR only changes the settings output files. So way less files.

It should be good :)

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by Pytal** [comment]
CI failure unrelated

**Pull request merged**
