### PR TITLE
fix linebreak on public share page

### LINKED ISSUE #10849: public share footer linebreak in "Get your own free account"
### Steps to reproduce
1. update to 14 RC1
2. visit a public share link
3. see a linebreak in "Get your own free account" even though there is more than enough space for the text

### Expected behaviour
no line break

### Actual behaviour
line break

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.5

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 14.0.0RC1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 13

**Where did you install Nextcloud from:** official nextcloud download page

### Browser
Firefox 61.0.2

### PR DESCRIPTION
**Pull request by violoncelloCH**
in text "Get your own free account"
fixes #10849

### CODE REVIEW

**Comment by MorrisJobke** [comment]
That's the one @tobiasKaminsky also experienced. @jancborchardt @skjnldsv Is this how you want it?

**Comment by tobiasKaminsky** [comment]
@MorrisJobke no, my problem is that on the border there is a link to the current page, and a little bit below there is then the link to /signup.
--> I'll create an issue.

**Comment by tobiasKaminsky** [comment]
After testing this PR with Julius, I can confirm that this is working now as expected.
The other issue is https://github.com/nextcloud/server/issues/10024, where the Cloud name points all the time to the current page, when no theming url is set.

:+1:

**Review by tobiasKaminsky — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@violoncelloch The line needs to be added to your commit message.

**Comment by violoncelloch** [comment]
@juliushaertl sorry, I'm a beginner with git... I try to find a way to do this

**Comment by violoncelloch** [comment]
managed to do a rebase, create a new signed commit locally and pushed it but only to a new branch
created a new pr with the same changes but signed and with the signed-off-by line in #10878
@juliushaertl @tobiasKaminsky could you reapprove the new pr? sorry for any inconvenience

**Pull request closed without merging**
