### PR TITLE
Refactor encryption app commands

### PR DESCRIPTION
**Pull request by fsamapoor**
## Summary
I have made some adjustments to the `apps/encryption/lib/Command` classes to improve the code readability.

The improvements in this PR include but are not limited to:

- Using PHP8's constructor property promotion
- Adding return types
- Replacing return code integers with more readable strings.
- Using early returns

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

### CODE REVIEW

**Comment by fsamapoor** [comment]
Conflicts resolved.

**Review by nfebe — APPROVED** [review]
Please, rebase this against latest master.

**Comment by fsamapoor** [comment]
> Please, rebase this against latest master.

Done. But it has already got out-of-dated. Should I rebase it again?
I think we can wait for the second review for now.

**Comment by Fenn-CS** [comment]
@fsamapoor thanks, all good! I was hoping CI might get green if you rebase but no, it's fine. Just wait for other reviews.

**Review by icewind1991 — APPROVED** [review]

**Comment by fsamapoor** [comment]
@Fenn-CS Cypress workflows are failing on almost all of my PRs. I don't know if there is anything that I can do to fix them.

**Comment by Fenn-CS** [comment]
@fsamapoor Not to worry, those failures are unrelated (most likely as they are UI tests).

**Comment by fsamapoor** [comment]
Conflicts resolved.

**Comment by Fenn-CS** [comment]
> Conflicts resolved.

Thank you, please rebase.

**Comment by fsamapoor** [comment]
> Thank you, please rebase.

Done.

**Review by icewind1991 — APPROVED** [review]

**Comment by Fenn-CS** [comment]
@fsamapoor now that this has another approval kindly, update/rebase it with master I would put my eyes on the jobs to get it in asap.

Thank you!

**Comment by fsamapoor** [comment]
> @fsamapoor now that this has another approval kindly, update/rebase it with master I would put my eyes on the jobs to get it in asap.
> 
> Thank you!

Sure. Thank you! Other than Cypress workflows, I think there will be no issues.

**Pull request merged**
