### PR TITLE
Refactors "strpos" calls in /apps/settings

### PR DESCRIPTION
**Pull request by fsamapoor**
## Summary
Following https://github.com/nextcloud/server/pull/38261 and https://github.com/nextcloud/server/pull/38260, I have replaced `strpos` calls in `/apps/settings` namespace as well to improve code readability.

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
Thanks!

**Review by nfebe — APPROVED** [review]
Looks good! Thanks

**Review by icewind1991 — APPROVED** [review]

**Comment by szaimen** [comment]
conflicts

**Comment by fsamapoor** [comment]
@szaimen Resolved.

**Pull request merged**
