### PR TITLE
Do not hide the progress bar while the chunked upload is being assembled

### LINKED ISSUE #9554: No indication of file assembling in chunked upload via web
1. Upload a big file via the web (2GB or something)
2. See it upload
3. Once the final byte is send the upload bar disappears
4. The file still needs to be assembled which takes time
5. The file list is refreshed

Now at step 4 we have no feedback that something is still going on. But assembling a 2GB file can take some time.

Possible solutions:

1. Show a spinner?
2. Don't remove the progress bar until it is all finished

### PR DESCRIPTION
**Pull request by danxuliu**
Fixes #9554

Large files are not uploaded in a single operation, but uploaded in several chunks; once all the chunks are uploaded then the server needs to assemble them to get the final file.

Before, once the chunks were uploaded the progress bar was hidden. However, this was confusing for the users, as the file could still need some time to appear in the file list due to the assembling. Now once all the chunks are uploaded the text in the progress bar changes to inform the user that there are still some pending operations, and only when the file is finally assembled the progress bar is hidden.

**How to test:**
- Force a long move operation by adding `sleep(10);` to [`performMove` in _ChunkingPlugin.php_](https://github.com/nextcloud/server/blob/fc4e0501f03de66eafb0a3a2d04024a40be17756/apps/dav/lib/Upload/ChunkingPlugin.php#L70)
- In the Files app, upload a file > 10MiB

**Current result:**
The text in the progress bar changes to _Processing files..._ when all the chunks are uploaded, and it is hidden once the move finishes and the file appears in the file list.

**Previous result:**
The progress bar was hidden as soon as all the chunks were uploaded, and after some seconds the file appeared in the file list.

**Reviewers**, if you cancel a chunked upload you will notice that it does not work as expected; it is a known problem and it will be fixed in a different pull request.

@nextcloud/javascript

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@michag86 😉

**Review by rullzer — APPROVED** [review]
Seems to do the trick

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by danxuliu** [comment]
> Could you backport this to stable14?

Sure; I intended to backport it to _stable13_ too, should I do it only for _stable14_?

**Comment by danxuliu** [comment]
>  Fine with me to backport it to both.

Done :-)

**Pull request merged**
