### PR TITLE
Fix legacy DAV endpoint

### PR DESCRIPTION
**Pull request by rullzer**
Master forward port of #2685

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Comment by rullzer** [comment]
@pbek mind to give the the one against master a quick test as well?

**Comment by pbek** [comment]
You mean `master-2648`? I can do that tomorrow.

**Comment by rullzer** [comment]
> You mean master-2648? I can do that tomorrow.

yep! Thanks a lot!

**Comment by pbek** [comment]
@rullzer, I terribly sorry! On `master-2648` GET works, PUT throws

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
    <s:sabredav-version>3.2.0</s:sabredav-version>
    <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
    <s:message>File not found: groups in 'principals'</s:message>
</d:error>
```

```
[Sat Dec 17 10:06:04 2016] 127.0.0.1:57720 [200]: /remote.php/caldav/calendars/admin/admin-test/ownCloud-48x0fj081ahtxyn5tdwv6j38frc6787302w69b2re4wrhkw3ik9.ics
[Sat Dec 17 10:06:11 2016] 127.0.0.1:57738 [404]: /remote.php/caldav/calendars/admin/admin-test/ownCloud-48x0fj081ahtxyn5tdwv6j38frc6787302w69b2re4wrhkw3ik9.ics
```

**Comment by rullzer** [comment]
:S I don't get that. master and stable11 are not that far diverged :S...

**Comment by MorrisJobke** [comment]
@rullzer Merge conflicts

**Comment by rullzer** [comment]
Rebased.

@LukasReschke I vote to get this in. The tests pass now. We still need to debug the issue of @pbek but lets not keep master without tests because we don't fix everything.

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
