### PR TITLE
Sharing in list: Use .hidden-visually instead of display:none for accessibility, fix #11661

### LINKED ISSUE #11661: Sharing UI accessibility
### Steps to reproduce
1. Open the sharing UI for any file with, lets say NVDA
2. Observe missing buttons, and maybe more

### Expected behaviour
Everything should be read correctly

### Actual behaviour
There at least two instances of, i assume buttons, which have only an icon - namely the confirmation button for the share with action and the more button for public link sharing.
I did not notice it sooner, i should probably have tested the betas, but i naively assumed that if it worked in 13, it would not be broken with 14.
### Client configuration
**Browser:** Firefox 62.0.3

**Operating system:** Windows 10

**Screen reader tested:** NVDA, latest development snapshot

### Notes
I suspect that we can not avoid those regressions entirely, because it would require some sort of integration test or something like that, but i have honestly no idea how testing those kinds of interactions would even work, anyone any ideas?

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #11661, please review @nextcloud/accessibility @nextcloud/designers 

And thanks to @javido @tyrylu for reporting! (This is still quite old code and we hope to replace it with the new Vue components soon. :)

Also could make sense to backport to 16, what do you think?

### CODE REVIEW

**Review by javido — APPROVED** [review]
Good, now I have tested this request and fixed the issue with "Share" link accessibility in Master.
would be nice to have it in 16.x version if it's possible.
Many thanks!

**Review by tyrylu — APPROVED** [review]
Thanks for these. They will help.

**Comment by jancborchardt** [comment]
@tyrylu @javido thanks a lot for reporting, and again sorry for the issue in the first place! Please don’t hesitate to report more if anything comes up.

**Pull request merged**
