### PR TITLE
fix(caldav): limit property length

### PR DESCRIPTION
**Pull request by miaulalala**
## Summary
Make longer properties searchable for the property index

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Review by come-nc — COMMENTED** [review]
Won’t that apply to event description or stuff like that which might need more than 255 chars?

**Comment by miaulalala** [comment]
> Won’t that apply to event description or stuff like that which might need more than 255 chars?

it's just the search index - the data itself is stored in oc_calendar_objects

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
