### PR TITLE
Add sidebar icon we use in Talk and Viewer already

### PR DESCRIPTION
**Pull request by jancborchardt**
Just housekeeping so we don’t need to add it to every app individually. Ref https://github.com/nextcloud/viewer/pull/142

Please review @nextcloud/designers :) We should probably also backport this to stable16 since it’s low-risk and then we need to handle less backward compatibility.

viewer icons

### CODE REVIEW

**Comment by skjnldsv** [comment]
I'm not sold on the icon choice :thinking: 
For me it look like a list of contacts. It make sense in talk because the sidebar is where the list is, but in server it doesn't. Could we find something more generic?

@juliushaertl @ChristophWurst ?

**Comment by juliushaertl** [comment]
I agree with @skjnldsv, while the hamburger icon is a good indicator, the people icon looks a bit wrong here. The sidebar is more about details of the file or "object" an app presents. A list of people is only one type of that. 

How about using a hamburger icon with either a small i which is probably a good pictogram to indicate that there is more information?

**Comment by jancborchardt** [comment]
The icon is meant to denote that it’s a menu, and there’s also stuff regarding people in it. Most of the details like activity, comments, sharing relate to people. And one of the most important tasks of the icon is to let people know that this is the thing they have to click to get to sharing.

… which is why currently we use this "Sharing" icon, which is too extreme in one direction. And a more generic icon like a list with an info-i would go into the other extreme and downplay the "people" aspect and leave people confused as to how to share.

So I’d say this icon change here goes a good step in the right direction.

**Comment by skjnldsv** [comment]
> So I’d say this icon change here goes a good step in the right direction.

I agree, but not with this icon :)
A few suggestions:

|1|2|3|4|
|:--:|:--:|:--:|:--:|
|sidebar|sidebar|sidebar|sidebar|

Any thoughts? :)

**Comment by georgehrke** [comment]
I like 4 most 👍

**Comment by jancborchardt** [comment]
While 4 looks nice, there’s some issues with all of them:
- It is not very iconographic, but a visual representation of the sidebar. It focuses on what it _looks_ like, not what it _does_.
- On mobile, the sidebar does not look like that.
- If you don’t know what the sidebar has, you have no context of what will await you.
- It’s quite generic, like only a "Fullscreen" icon could do.
- Does any other popular app use an icon comparable to this?
- It doesn’t answer the question "What do I need to click to share this thing with someone?"

**Comment by jancborchardt** [comment]
Case in point, we have people being confused about how to get to the chat and collaboration features when they are in Collabora:
https://github.com/nextcloud/server/issues/15386

An even more generic icon will not help here but make it worse. We all know what the sidebar has to offer, but people who don’t work every day with Nextcloud _do not_. That’s why the icon has to be iconographic.

**Comment by skjnldsv** [comment]
> * It is not very iconographic, but a visual representation of the sidebar. It focuses on what it _looks_ like, not what it _does_.

This is exactly like what the icon you suggested does. Contains a list of contacts (from talk)

> * On mobile, the sidebar does not look like that.
> * If you don’t know what the sidebar has, you have no context of what will await you.

Also valid for your icon choice. Why is there a contact list in the header?

> * It’s quite generic, like only a "Fullscreen" icon could do.
> * Does any other popular app use an icon comparable to this?

I have no example of a website using a sidebar icon :thinking: 

> * It doesn’t answer the question "What do I need to click to share this thing with someone?"

Same as your first icon.

**Comment by jancborchardt** [comment]
So @skjnldsv and I discussed and will go for the solution in this pull request for now as we’re in a deadlock otherwise.

**Review by skjnldsv — APPROVED** [review]

**Review by georgehrke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Backport canceled because of https://github.com/nextcloud/server/pull/16287#issuecomment-509196145

**Pull request merged**
