### PR TITLE
Format code to a single space around binary operators

### PR DESCRIPTION
**Pull request by ChristophWurst**
This should give the code more consistency. See https://github.com/nextcloud/coding-standard/pull/1 for the propose CS fixer change.

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
CI says no :x:

**Comment by kesselb** [comment]
> CI says no x

https://github.com/nextcloud/server/pull/23193

**Comment by MorrisJobke** [comment]
> > CI says no x
> 
> #23193

Let's see if this is true and rebase this one here.

**Comment by MorrisJobke** [comment]
Looks good 👍

**Pull request merged**
