### PR TITLE
fix(ci): Align mariadb versions with list of supported versions

### PR DESCRIPTION
**Pull request by susnux**
## Summary

We currently support 10.3, 10.5, 10.6 (old LTS) and 10.11 (current LTS) so we can drop 10.4 from CI and save a bit of CI time.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by nickvergessen — COMMENTED** [review]
Also in .github?

**Review by nickvergessen — APPROVED** [review]

**Comment by susnux** [comment]
> Also in .github?

The templates only check for LTS version 10.6 and 10.11 (and in few weeks probably 11.4)

**Comment by solracsf** [comment]
Why have dropped 10.4 isntead of 10.3?
https://endoflife.date/mariadb

**Comment by nickvergessen** [comment]
Sounds like a mistake. I think someone mentioned .3 to be an LTS, but .4 actually is the LTS

**Comment by susnux** [comment]
No 10.3 is supported because of Ubuntu 20.04 shipping it and we support Ubuntu 20.04

10.4 was dropped on purpose as it is only a short term stable and will be eol when Nextcloud 30 is released

**Pull request merged**
