### PR TITLE
fix(deps): Update phpseclib from 2.0.45 to 2.0.47

### PR DESCRIPTION
**Pull request by susnux**
* For https://github.com/nextcloud/3rdparty/pull/1751

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
Psalm error is related:
> apps/files_external/lib/MountConfig.php:260:12: InternalMethod: The method phpseclib\Crypt\Base::setKey is internal to phpseclib but called from OCA\Files_External\MountConfig::getCipher

**Comment by susnux** [comment]
@nickvergessen I think this can be ignored in our baseline as this is introduced by removing the extending `setKey` and falling back to `Base::setKey`. Reported this behavior change upstream: https://github.com/phpseclib/phpseclib/issues/1990

**Review by nickvergessen — APPROVED** [review]

**Comment by susnux** [comment]
Adjusted 3rdparty submodule, PR ready now :heavy_check_mark:

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
