### PR TITLE
[stable25] Fix default theming variables

### PR DESCRIPTION
**Pull request by skjnldsv**
@Pytal fixed part of it in the vue migration: https://github.com/nextcloud/server/pull/34359

Here is a pick of the fixes only without vue

Fix https://github.com/nextcloud/server/issues/34968
Fix https://github.com/nextcloud/server/issues/35002
Fix reverting default admin colour using user primary instead of default Nextcloud colour

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by Pytal** [comment]
Also backports https://github.com/nextcloud/server/pull/34546

**Review by Pytal — APPROVED** [review]

**Comment by melyux** [comment]
Still seeing this issue in 26.0.3

**Pull request merged**
