### PR TITLE
add contacts popover

### PR DESCRIPTION
**Pull request by georgehrke**
adds popover as discussed in https://github.com/nextcloud/server/issues/207

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> adds popover as discussed in #207

And what about #3233?

**Comment by MorrisJobke** [comment]
cc @ChristophWurst

**Comment by georgehrke** [comment]
This is the popover you will see when clicking on the avatar / name of the user.
#3233 is about the contacts menu in the upper right corner.

#3233 is ready to review while this  is still in development, that's why I created a dedicated PR

**Comment by jancborchardt** [comment]
@georgehrke there are a bunch of conflicts with master now seemingly, could you resolve them? :)

**Review by jancborchardt — DISMISSED** [review]
Tested this in two scenarios where it doesn’t work:
- [x] in the sharing section of the sidebar, clicking a name does nothing
- [ ] Same for the Activity app, clicking a name in the stream does nothing.

@georgehrke how to test this?

**Comment by georgehrke** [comment]
>  in the sharing section of the sidebar, clicking a name does nothing

That should work, what exactly did you test? 


>  Same for the Activity app, clicking a name in the stream does nothing.

Requires changes in the activity app. Will not be part of this pr

**Comment by jancborchardt** [comment]
@georgehrke a file shared with another internal user. Should bring up at least info that there is no contact info available, for example. Otherwise it’s confusing. :)

**Comment by georgehrke** [comment]
kapture 2017-04-24 at 18 50 56

**Comment by georgehrke** [comment]
add contacts popover by georgehrke pull request 4374 nextcloud-server safari today at 6 52 03 pm

**Comment by georgehrke** [comment]
@schiessle Can you test this especially with regard to remote sharing please? :) Thx!

**Comment by georgehrke** [comment]
@jancborchardt Maybe try to enable `debug => true` in config.php, so it loads the js/css directly and doesn't take the cached one.

**Comment by jospoortvliet** [comment]
@georgehrke this is what I get with a remote share:
screenshot_20170425_212658
Note that this instance runs on localhost so while the remote share is real, it can't reach it, or at least the remote can't get back. Nor is it in my addressbook.

**Comment by georgehrke** [comment]
Addressed Jos' issue.

Will rebase and change base branch to master once #3233 is in

**Comment by MorrisJobke** [comment]
> Will rebase and change base branch to master once #3233 is in

Done

**Comment by jancborchardt** [comment]
Some drone failures – @georgehrke can you fix them?

cc @nextcloud/javascript @MorrisJobke @schiessle

**Comment by georgehrke** [comment]
»ERROR: maximum time limit exceeded, build cancelled« is not in my power to fix

**Comment by jancborchardt** [comment]
Is there a way to restart @MorrisJobke @LukasReschke?

**Comment by jospoortvliet** [comment]
@georgehrke the other error, though, seems a css thingy: https://drone.nextcloud.com/nextcloud/server/7482/33 an element is not visible. Not sure if that's caused by you but I do notice an issue:
screenshot_20170426_1328192
screenshot_20170426_1333312
So this user, doglover, has no email set, neither does the other user that has no actions.

It might be that at some point I added an email to doglover and removed it but I'm not sure.

**Comment by georgehrke** [comment]
> https://drone.nextcloud.com/nextcloud/server/7482/33 

I have absolutely no clue what this test is about. Where is it defined? Can someone point me?

> So this user, doglover, has no email set, neither does the other user that has no actions.
It might be that at some point I added an email to doglover and removed it but I'm not sure.

Can you reproduce the same issue in the contacts menu in the top right corner?

**Comment by georgehrke** [comment]
> https://github.com/nextcloud/server/blob/master/tests/acceptance/features/app-files.feature#L31
> And I see that a wrong password for the shared file message is shown

I didn't touch any public sharing code. Not sure that's related to my changes

**Comment by MorrisJobke** [comment]
The drone server is highly overloaded causing the timeouts - let me remove some workers. Regarding the acceptance tests: the problem there is also due to the high load -.-

**Comment by georgehrke** [comment]
>  Doglover also shows up with an email sign in the contacts menu by @ChristophWurst with no mouse-over (as there is actually no mail address).

Any clue what causes this @ChristophWurst ?

**Comment by jancborchardt** [comment]
I think @ChristophWurst is at uni today so we need to fix this without him.

**Comment by georgehrke** [comment]
> I think @ChristophWurst is at uni today so we need to fix this without him.

I haven't been able to tackle the bug so far. As it with introduced with the already merged #3233 and not with this PR I'd vote to fix it in a follow up PR (and potentially beta 2)

**Comment by LukasReschke** [comment]
I agree with @georgehrke here.

**Review by LukasReschke — APPROVED** [review]
Not a critical bug => Let's get this in.

**Review by jancborchardt — APPROVED** [review]
Looks good! :+1:

**Comment by jancborchardt** [comment]
Who will make the required changes to also make this work in other main shipped apps like:
- Activity @nickvergessen 
- Gallery share dialog @oparoz 

And sooner or later also:
- Mail @ChristophWurst 
- Calendar @georgehrke 
- Tasks @raimund-schluessler @Henni 

cc @georgehrke would be cool if you can drive that.

**Comment by jancborchardt** [comment]
I also restarted the tests on Drone.

**Comment by LukasReschke** [comment]
> I also restarted the tests on Drone.

Drone is overloaded. The previous test execution was okay if you ignore the other failing tests. => Let's just merge instead of waiting 10 hours until the Drone backlog is done. Also adding more won't help 🙈

**Comment by jancborchardt** [comment]
kk :)

**Comment by jancborchardt** [comment]
Opened a new issue about adding the contacts popover to other apps at https://github.com/nextcloud/server/issues/4532 – would be cool if you can push this @georgehrke, especially for Activity and Gallery as they are shipped.

**Comment by nickvergessen** [comment]
I can add it to activities if sample code is posted somewhere

**Comment by georgehrke** [comment]
> I can add it to activities if sample code is posted somewhere

I will send a pr tomorrow :)

**Comment by nickvergessen** [comment]
Please also create a topic in https://help.nextcloud.com/c/dev/ so app devs get notified

**Comment by ChristophWurst** [comment]
> I can add it to activities if sample code is posted somewhere

https://github.com/nextcloud/contacts/pull/173 and https://github.com/ChristophWurst/contactsmenu_social

**Comment by ChristophWurst** [comment]
Ah, you mean the popover I guess. Nvm then …

**Pull request merged**
