### PR TITLE
Directly fix invalid values of DTEND and DTSTART

### LINKED ISSUE #2741: Calendar app: internal server error after upgrading to Nextcloud 11
**Steps to reproduce:**

 - Use calendar app 1.4.1 with Nextcloud 10
- Upgrade to Nextcloud 11.0
- Re-Activate the Calendar App within the new App Store
- Open the Calendar App

**Expected behavior:**
The calendars created with the calendar app in Nextcloud 10 are loaded without any errors. 

**Actual behaviour:**
The Chrome and Firefox consoles print an internal server error when existing calendars are loaded. The Nextcloud log says:

`{"reqId":"hZjDhApmqGjwQIX\/MvRp","remoteAddr":"87.xxx.xxx.xxx","app":"webdav","message":"Exception: {\"Message\":\"Unsupported VALUE parameter for DTEND property. You supplied \\\"\\\"\",\"Exception\":\"Sabre\\\\VObject\\\\InvalidDataException\",\"Code\":0,\"Trace\":\"#0 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(453): Sabre\\\\VObject\\\\Document->createProperty('DTEND', NULL, Array)\\n#1 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(234): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty('DTEND;TZID=Euro...')\\n#2 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(217): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('DTEND;TZID=Euro...')\\n#3 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(181): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('DTEND;TZID=Euro...')\\n#4 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(89): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#5 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(46): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#6 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(142): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#7 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(1123): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#8 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(248): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->calendarQuery('1', Array)\\n#9 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(624): OCA\\\\DAV\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#10 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(250): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport))\\n#11 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport), 'calendars\\\/Ben\\\/o...')\\n#12 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(718): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#17 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#19 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#20 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/remote.php(165): require_once('\\\/share\\\/MD0_DATA...')\\n#21 {main}\",\"File\":\"\\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Document.php\",\"Line\":220,\"User\":\"Ben\"}","level":4,"time":"2016-12-18T21:09:06+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/dav\/calendars\/Ben\/owncloudkalender\/","user":"Ben","version":"11.0.0.10"}`

Enabled apps:
Calendar 	1.4.1
Contacts 1.5.2

PHP-Version: 7.0.5
OS: Embedded QNAP-Linux

### LINKED ISSUE #3350: Unsupported VALUE parameter for DTEND property
### Steps to reproduce
1. Update from Nextcloud 10.x
2. See error logs in administration screen

### Expected behaviour
No error logs

### Actual behaviour
Following error is repeated several times:

    Sabre\VObject\InvalidDataException: Unsupported VALUE parameter for DTEND property. You supplied ""

This seems to be related to #2249.
However, a fix of the database should be available: #2807. 
I don't know if the database was not repaired, or if this is another issue. Is there a way to manually trigger the database repair?
Unfortunately, the error message does not give any hint, what entry makes the problem.
I created an vcf export of my calendar, but I don't know for what pattern I have to look?
DTEND without VALUE, or without DATE?

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
PHP 7

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

### LINKED ISSUE #3734: No calendar export possible, internal server error
### Steps to reproduce
1. Go to Calendar
2. Try to export Calendar (a big one)

### Expected behaviour
A ics file should be downloaded.

### Actual behaviour
In the new tab that opens there is a error message, saying "Internal Server Error", followed by the local IP Adress and a request token.

In the log, I am getting the following exception:
<details>

```
Sabre\VObject\InvalidDataException: Unsupported VALUE parameter for DTEND property. You supplied ""
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 453: Sabre\VObject\Document->createProperty('DTEND', NULL, Array)
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 234: Sabre\VObject\Parser\MimeDir->readProperty('DTEND;VALUE=;TZ...')
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 217: Sabre\VObject\Parser\MimeDir->parseLine('DTEND;VALUE=;TZ...')
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 181: Sabre\VObject\Parser\MimeDir->parseLine('DTEND;VALUE=;TZ...')
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 89: Sabre\VObject\Parser\MimeDir->parseDocument()
/volume1/cloud/3rdparty/sabre/vobject/lib/Reader.php - line 46: Sabre\VObject\Parser\MimeDir->parse('BEGIN VCALENDAR...', 0)
/volume1/cloud/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 307: Sabre\VObject\Reader read('BEGIN VCALENDAR...')
/volume1/cloud/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 222: Sabre\CalDAV\ICSExportPlugin->mergeObjects(Array, Array)
/volume1/cloud/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 151: Sabre\CalDAV\ICSExportPlugin->generateResponse('calendars/valen...', NULL, NULL, false, false, 'text/calendar', Array, Object(Sabre\HTTP\Response))
[internal function] Sabre\CalDAV\ICSExportPlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/volume1/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/volume1/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method GET', Array)
/volume1/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/volume1/cloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
/volume1/cloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
/volume1/cloud/remote.php - line 165: require_once('/volume1/cl...')
{main}
```
</details>
URL is: 
"/cloud/remote.php/dav/calendars/***USER***/kalender?export"

Something must be broken in this particular calendar. When I try it with a different user (with a mostly empty calendar) it works.

It is related to this error:
https://help.nextcloud.com/t/no-calendar-export-possible-11-0-0/7293/2

Maybe this issue report can help you guys somehow to fix this in a next NC release!

### Server configuration
**Operating system**:
Synology DSM 6.0.2

**Web server:**
Apache 2.2.31

**Database:**
MariaDB 5.5.53

**PHP version:** 7.0.15

**Nextcloud version:** (see Nextcloud admin page)
11.0.2 stable

**Updated from an older Nextcloud/ownCloud or fresh install:**
update

**Where did you install Nextcloud from:** 
from your source

**Signing status:**
<details>
<summary>Signing status</summary>

`No errors have been found.`

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
  - user_saml
```

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        [shortened]
        "dbtype": "mysql",
        "version": "11.0.2.7",
        [shortened]
        "logtimezone": "UTC",
        "installed": true,
        "filesystem_check_changes": "0",
         [shortened]
        "theme": "",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:**
local

**Are you using encryption:** 
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
</details>

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing relevant found.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
See the exception above, nothing else.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
The only log the console shows is a Stylesheet error (multiple times Refused to load the script [...] because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

I don't think this matters in this case!
```
</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref #4014

Fix #2741 
Fix #3350
Fix #3734

@georgehrke @rullzer

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@nickvergessen So this is intended to be run on every upgrade? Otherwise add a version number check.

**Comment by nickvergessen** [comment]
Basically yes. It only does stuff for broken entries anyway

**Review by MorrisJobke — APPROVED** [review]
Looks good 👍

**Review by rullzer — APPROVED** [review]
Looks good to me. And fixed some broken stuff I threw at it.

So lets do it...

**Pull request merged**
