### PR TITLE
Remove md5 from js globals

### PR DESCRIPTION
**Pull request by rullzer**
In our fight against bit waste this is a few kb saves.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
🧹

**Comment by MorrisJobke** [comment]
The file upload seems to still need it 🙈

**Comment by ChristophWurst** [comment]
> [ChristophWurst](/ChristophWurst) added the [pending documentation](/nextcloud/server/labels/pending%20documentation) label [now](#event-3843993694)

Please please please always add this. Otherwise we will forget to document this critical change :pray:

**Comment by MorrisJobke** [comment]
> Please please please always add this. Otherwise we will forget to document this critical change 🙏

tenor

**Pull request closed without merging**
