### PR TITLE
enh: Allow prefetch-src self in CSP

### PR DESCRIPTION
**Pull request by juliusknorr**
## Summary

Make sure that we can prefetch resources from our own domain e.g. with [webpack module prefetching](https://webpack.js.org/guides/code-splitting/#prefetchingpreloading-modules)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by tcitworld** [comment]
Not exposed to public API?

**Review by marcelklehr — APPROVED** [review]

**Comment by juliushaertl** [comment]
> Not exposed to change via public API?

Mainly did this for apps to prefetch their javascript, so I'd keep it rather simple for now. We can extend this if we have use cases for adding external sources.

**Comment by marcelklehr** [comment]
[No browser seems to support this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src#browser_compatibility), yet.

**Comment by tcitworld** [comment]
Latest Safari [has support for it](https://webkit.org/blog/13691/webkit-features-in-safari-16-3/), but Chromium [wants to remove it](https://bugs.chromium.org/p/chromium/issues/detail?id=1406444). It was also removed from the spec a few weeks ago: https://github.com/w3c/webappsec-csp/pull/582

**Comment by juliushaertl** [comment]
Good catch, so I actually had a CSP error when testing this the first time, but I cannot reproduce that anymore, so maybe I was just lacking he nonce to be set with web pack there. Will close this.

**Pull request closed without merging**
