### PR TITLE
Fix markup and style of mentions in comments

### PR DESCRIPTION
**Pull request by danxuliu**
This pull request ensures that the user name is shown in bold (as the default font weight for `strong` elements changes between browsers) and that mentions to the current user are highlighted.

It also fixes some minor markup issues and reformats the embedded HTML code to better resemble HTML code.

**Before:**
comment-mentions-before

**After:**
comment-mentions-after

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Looking nice!!! :taco:

**Review by blizzz — APPROVED** [review]
looks good and works on FF

**Comment by danxuliu** [comment]
I have added a few more fixes; the most relevant one to keep the avatar and the user name together.

**Before:**
comment-mentions-wrap-before

**After:**
comment-mentions-wrap-after

**Comment by danxuliu** [comment]
Oops, the JS unit tests fail due to the change from `div` to `span`; I will fix that.

**Pull request merged**
