### PR TITLE
add option to use legacy v2 auth with s3

### LINKED ISSUE #7569: Nextcloud 12.0.4 and 13 doesn't support S3 Backend using V2 authentication
### Steps to reproduce
1. Upgrade Nextcloud from 12.0.3 to 12.0.4 or 13.0.0 Beta
2. Use S3 as backed which only support V2 authentication
3.

### Expected behaviour
Should work as normal

### Actual behaviour
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

### Server configuration

**Operating system**: 

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by icewind1991**
For s3 implementations that only support v2.

- fixes #7569 
- Tested by running against v2+v4 and v4 only capable aws regions
- [x] requires proper testing with a backend that only supports v2.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 Could you add the config option to the sample config?

**Comment by icewind1991** [comment]
the sample config uses swift so this is not applicable there.

Did add it to the docs: https://github.com/nextcloud/documentation/pull/637

**Comment by rullzer** [comment]
> requires proper testing with a backend that only supports v2.

@icewind1991 did you find a way and time to do this?

**Review by MorrisJobke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
Makes sense :elephant: 
I don't have a v2 only setup unfortunately to test against....

**Comment by MorrisJobke** [comment]
@icewind1991 Could you do the backport for this to fix all s3 problems on 12.0.4

**Pull request merged**
