### PR TITLE
SCSS: add background on app section:hover

### PR DESCRIPTION
**Pull request by IGLOU-EU**
Very little SCSS PR.
Avoid miss click on app, focus attention.

### CODE REVIEW

**Comment by rullzer** [comment]
@nextcloud/designers

**Comment by rullzer** [comment]
Welcome @IGLOU-EU! And thanks for your first PR.

**Comment by IGLOU-EU** [comment]
Hi all,
sorry for the screen screenshot,
I add a gif for this PR.
PS: PR only for :hover stuff

peek 2019-02-02 11-50

**Review by rullzer — APPROVED** [review]
Looks good!

**Review by skjnldsv — APPROVED** [review]
Perfect! :+1:

**Comment by rullzer** [comment]
@IGLOU-EU next time we'd need you to sign of your commits. But lets get this in now :smile:

**Pull request merged**
