### PR TITLE
Fix input field not disabled while a comment is being sent

### LINKED ISSUE #7240: Input field for comments is not disabled when a new comment is being sent
Since [the change of the text area to a content editable div](https://github.com/nextcloud/server/commit/ec5607544c32797901f82c4e06161938a50fe322) the input field is no longer disabled while a new comment is being sent.

The problem seems to come from [trying to disable the div still using the _disable_ property](https://github.com/nextcloud/server/blob/2b4b3b1986e58305c08941f77a693a80cc3d5b85/apps/comments/js/commentstabview.js#L623); I guess that the right way to disable a content editable div would be by setting `contenteditable=false`, but that would need support in the [core input.scss file](https://github.com/nextcloud/server/blob/bd7d0de86f93bcdf0a521544a92795d5725f57f4/core/css/inputs.scss) so it has the same appearance of an input field with the _:disabled_ pseudo-class.

@blizzz @nextcloud/designers

### PR DESCRIPTION
**Pull request by danxuliu**
Fixes #7240 

**Pending:** @nextcloud/designers CSS masters, please amend and force push again the last commit :-) It is an ugly copy paste, so there are several duplicated and overriden rules ;-)

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍 

I would keep the CSS for now. We could refactor later, but it is okay from my side.

**Comment by MorrisJobke** [comment]
> Pending: @nextcloud/designers CSS masters, please amend and force push again the last commit :-) It is an ugly copy paste, so there are several duplicated and overriden rules ;-)

See my inline comment 😉

**Comment by MorrisJobke** [comment]
@jancborchardt @pixelipo @skjnldsv Other opinions?

**Review by LukasReschke — APPROVED** [review]
Works nicely 👍

**Pull request merged**
