### PR TITLE
Sort tags

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
## Summary
sorts tags before returning via webdav

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by blizzz** [comment]
This should fail with `PHP Warning:  Array to string conversion in php shell code on line x`

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — CHANGES_REQUESTED** [review]
See @blizzz comment

**Review by icewind1991 — APPROVED** [review]

**Comment by skjnldsv** [comment]
Will push fix

**Comment by skjnldsv** [comment]
Done

**Review by skjnldsv — APPROVED** [review]

**Comment by blizzz** [comment]
@skjnldsv in parallel i did  https://github.com/nextcloud/server/pull/38067 as alternative

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/38067 is probably the better place to do the sorting

**Pull request closed without merging**
