### PR TITLE
change primary button text color to white

### PR DESCRIPTION
**Pull request by jancborchardt**
As mentioned by @irgendwie  ;) Looks much nicer with the white arrow on the log in button and overall too.

Please review @nextcloud/designers

### CODE REVIEW

**Comment by MariusBluem** [comment]
Finally :+1:

**Comment by irgendwie** [comment]
LGTM :+1:

**Comment by skjnldsv** [comment]
Ahahah 👍

**Comment by jancborchardt** [comment]
YO! Don’t say »Finally« if you never opened an issue for it. ;D For any small thing you find, simply open an issue or directly fix it ;) :tada:

**Comment by MariusBluem** [comment]
Someone had written in the forum or said it to me ... My fault 😅 ...People are telling me about soooo many of those papercuts every day 😜🙈

**Comment by jancborchardt** [comment]
@MariusBluem I was joking ;D so whenever someone tells you about it, simply open an issue and we @nextcloud/designers can fix it! :)

**Comment by te-online** [comment]
Very good 😊 

Don't know if that's too much to ask, but would be cool to see screenshots of visual changes 🙈 
Also makes it easier to review, whether it looks like it's supposed to look.

**Comment by jancborchardt** [comment]
@te-online yeah, normally I always do that. Screenshots are useful! :)

**Comment by Espina2** [comment]
I already comment in another issue that its difficult to see design related issues if we don't have print screen's. :)

**Comment by jancborchardt** [comment]
@Espina2 @te-online sure – but folks please do not forget that this whole design thing is not only about interface and graphics but about the whole UX and interaction. So running a local development environment to test it is pretty important too. ;)

**Comment by te-online** [comment]
@jancborchardt Sure! But then my second argument kicks in: You can't check if something is looking as expected, if you don't know what it's supposed to look like 😜

**Comment by jancborchardt** [comment]
Of course, all true. :) Just wanna make sure that we don’t only judge improvements by reading the text and looking at images, but also on how it actually works. :)

**Pull request merged**
