### PR TITLE
Object store trashbin fixes

### PR DESCRIPTION
**Pull request by icewind1991**
object stores are "special" given how they interact with the cache on their own

I'm not very happy about adding special cases like this but it's the best I can come up with

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
This fixes a regression from #21628

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Not needed - the big was introduced in the above linked pull request which wasn’t backported

**Comment by icewind1991** [comment]
there are backports for that, but those aren't merged yet.

I'll put this in the original backports instead

**Comment by MorrisJobke** [comment]
> I'll put this in the original backports instead

👍

**Review by solracsf — APPROVED** [review]

**Pull request merged**
