### PR TITLE
dont open the file on dav HEAD request

### PR DESCRIPTION
**Pull request by icewind1991**
Upstream version: https://github.com/sabre-io/dav/pull/1058

- [x] requires https://github.com/nextcloud/3rdparty/pull/98

Not only does opening the file lead to unneeded overhead, it also requires locking the file which can lead to locking conflicts.

### CODE REVIEW

**Comment by icewind1991** [comment]
rebased and updated to keep changes in line with upstream

**Comment by rullzer** [comment]
rebased

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
🐘

**Comment by MorrisJobke** [comment]
@icewind1991 Please backport to stable13

**Pull request merged**
