### PR TITLE
Allow target="_blank" in apps navigation items

### PR DESCRIPTION
**Pull request by tcitworld**
Which was removed in the Vue rewrite in #33728. This breaks things like https://github.com/nextcloud/external/issues/79

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by PVince81** [comment]
@tcitworld needs manual rebase

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Conflicting files
dist/core-main.js
dist/core-main.js.map 

:(

There are quite some PRs in the queue atm.

**Comment by nickvergessen** [comment]
/backport 56c5273206316125f0311566f895ece85c792930 to stable25

**Comment by nickvergessen** [comment]
Manual backport in https://github.com/nextcloud/server/pull/36007

**Pull request merged**
