### PR TITLE
[frontend] Add possibility to set default app

### LINKED ISSUE #29474: Ability turnoff dashboard (or choose the default app) on a per user basis
Hey all, first: I love NC. :D To my point: My Org recently installed the NC dashboard app and maybe other ppl find it useful, but I certainly don't. However I cannot turn the dashboard off for me. I also cannot chose to always land in the calendar page after login (not dashboard or files). Could a setting like this maybe be added somewhere or did I miss something? Thanks for all your work

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/29474

## Summary
The adds support for setting the default app, that is the app opened after login or when clicking the logo in the navigation.

First I had to extend the `IAppManager` class to support setting the default app(s) (for current user or global as a admin setting).

Secondly I added settings to the theming app to allow configure global default apps (as the admin) and to enable user defined default apps. Also a personal setting for the user defined default app is added.

### Example recording
*(Sorry for German UI)*

https://github.com/nextcloud/server/assets/1855448/d467e178-9595-4491-9b3e-a6b7fb797edb

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by szaimen** [comment]
Hi, I wonder if this might conflict with https://github.com/nextcloud/server/issues/40245?

**Comment by susnux** [comment]
> Hi, I wonder if this might conflict with #40245?

I created this initially during the hack week, just polished it now. What do you think? (I attached a screen recording).

**Comment by jancborchardt** [comment]
So during the discussion for https://github.com/nextcloud/server/issues/40241 we said, as also written in the issue:
> This is a user-setting only, no admin setting

And I would stick to that, as it introduces a lot of complexity into something that is not as important, right? So let’s only go forward with the user setting.
If the existing default_app variable is set in the config.php by the admin that of course will still get honored, but the user-specific setting will override it.

cc @sorbaugh @AndyScherzinger

**Comment by susnux** [comment]
Close in favor of https://github.com/nextcloud/server/pull/40844

**Pull request closed without merging**
