### PR TITLE
Rename renderHTML to renderHtml

### LINKED ISSUE #4383: Inconsistency in casing
\OC\Mail\EMailTemplate::render**HTML**

vs.

\OC\Mail\Message::set**Html**Body

Quite annoying as those are especially usually in the same line. I'd vote for changing the new `EMailTemplate` one into `renderHtml`.

cc @MorrisJobke @nickvergessen

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #4383
* improves consistency

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by georgehrke** [comment]
We are touching a public API here. Can we have a deprecated `renderHTML` that just calls `renderHtml`?

**Comment by rullzer** [comment]
@georgehrke it is only public API once 12 is released.

**Comment by georgehrke** [comment]
Ok, never mind then :)

**Review by georgehrke — APPROVED** [review]

**Comment by rullzer** [comment]
@MorrisJobke conflicts!

**Pull request merged**
