### PR TITLE
Throttle getstoragestats.php calls and allow simultaneous uploads

### PR DESCRIPTION
**Pull request by tomasz-grobelny**
Improves speed on https://github.com/nextcloud/server/issues/13854 and https://github.com/nextcloud/server/issues/13696. Does not address reliability in any way.

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works nicely 👍  Also the `getStorageStats` call on every upload is not there anymore. Nice finding 💯

**Review by ChristophWurst — APPROVED** [review]
Looks good :+1:

**Comment by ChristophWurst** [comment]
@danielkesselberg but but but what if I upload 100 tiny files? Then 10 concurrent will probably be faster :wink:

**Comment by tomasz-grobelny** [comment]
> Cool 👍
> 
> `limitConcurrentUploads: 10` if you select 10 files a 50mb they are uploaded in parallel. not sure if this is a sensible default. i would vote for a lower value (e.g. 4).

This heavily depends on your uplink, server speed and filesize. I believe one could justify just about any value. I did my tests on a pcengines apu2c4 and I was still far from reaching the link speed (got 10Mbit/s).

**Comment by danielkesselberg** [comment]
Ok if this is a reasonable standard that works for most of your users.

**Comment by BloodyIron** [comment]
Why not make this an admin setting that we can set in the webGUI as an admin to tune it for our setup? I mean, hiding the setting seems like asking for trouble. Yes? :)

**Pull request merged**
