### PR TITLE
Remove bold font-weight and lower font-size for empty search box

### LINKED ISSUE #22978: [user_status] Change the font size and bold
I propose to change the font size and bold in "Recent statuses" for the text string:

- No recent status changes

obraz

Proposal for a change:

obraz

https://github.com/nextcloud/server/blob/1a312c4d2a38296fe208c4399ba97a76c88aea11/apps/user_status/src/views/Dashboard.vue#L22-L35

App:
Nextcloud 20.0.0 beta4
User status 1.0.0

### LINKED ISSUE #22987: Reduce font size and remove bold of search empty content notice
I propose to change the font size and bold in "Start typing to search" for the text string:

obraz

Proposal for a change:

obraz

App:
Nextcloud 20.0.0 beta4

### PR DESCRIPTION
**Pull request by jacobneplokh**
Fixes #22987 
--
Simple changes to the `h2` part. Let me know if there is anything wrong, of course :)

Signed-off-by: Jacob Neplokh <me@jacobneplokh.com>

### CODE REVIEW

**Comment by jancborchardt** [comment]
Hi @jneplokh :) This change would change _all_ h2 styles, and that is a bit much. Could you limit it to only change the h2 of the search emptycontent? As far as I could see, you would simply have to do your changes in this file:
https://github.com/nextcloud/server/blob/master/core/src/views/UnifiedSearch.vue#L745-L748

**Comment by jancborchardt** [comment]
@ma12-co did you define the new 15px default as a variable? If not, could you do that, so we can use them elsewhere where we need to bring semantically different elements down visually, like in this case?

**Comment by jneplokh** [comment]
> This change would change _all_ h2 styles, and that is a bit much. 

Ok, yeah, I was not sure if that was changing too much, but opened a PR anyways (as if I am wrong, I would get corrected, like now 😄)

> As far as I could see, you would simply have to do your changes in this file:
> [https://github.com/nextcloud/server/blob/master/core/src/views/UnifiedSearch.vue#L745-L748](https://github.com/nextcloud/server/blob/master/core/src/views/UnifiedSearch.vue?rgh-link-date=2020-10-08T14%3A20%3A50Z#L745-L748)

Unfortunately, when I added `font-weight: normal;` and even `font-size: 40px;` (the latter is just to further test it) on my dev server, the changes were not reflected (while the h2 changes are). I imagine I have to do something in order to reflect the changes?

Also, I was hoping to close #22978 in the same PR as they seem related. Where would the code be to change the status font size and font weight? Or would it be better to open a separate PR?

Thank you!

**Comment by jneplokh** [comment]
Hey, just bumping this! Do you know what I would have to do to reflect the changes on my dev server?

**Comment by jancborchardt** [comment]
@jneplokh sorry for the late reply! If you do changes to parts like search, you need to compile them with this terminal command: `npm ci && MODULE=core npm run build` :)

**Comment by jneplokh** [comment]
> `npm ci && MODULE=core npm run build`

Awesome, that worked! Just pushed the commit to fix the issue :)

**Comment by skjnldsv** [comment]
Hey! What is the status here?

**Comment by jneplokh** [comment]
> Hey! What is the status here?

Hello! It seems to be working (on my end), but there was a failed check: https://github.com/nextcloud/server/pull/23267/checks?check_run_id=1316328378

Not sure what is going on there? Do I have to change something here: https://github.com/nextcloud/server/blob/master/core/js/dist/unified-search.js?

**Comment by skjnldsv** [comment]
Yes, you need to ship the compiled files :)

You can rebase and then use the command `/compile /core/js/dist` as a github comment to have a bot do it for you :)

**Comment by jneplokh** [comment]
> Yes, you need to ship the compiled files :)
> 
> You can rebase and then use the command `/compile /core/js/dist` as a github comment to have a bot do it for you :)

Ah ok, got it. Just rebased and commented :)

**Comment by jneplokh** [comment]
Hmm now it seems the static code analysis has failed: https://github.com/nextcloud/server/pull/23267/checks?check_run_id=1336555393

with a few different errors it seems.

**Comment by skjnldsv** [comment]
> Hmm now it seems the static code analysis has failed: [#23267 (checks)](https://github.com/nextcloud/server/pull/23267/checks?check_run_id=1336555393)
> 
> with a few different errors it seems.

Yes, it fails on master, let's ignore :)

**Comment by skjnldsv** [comment]
> /compile /core/js/dist

Ah, you don't need to use the bot if you already shipped the up-to-date compiled files :)
It seems to pass now! :rocket:

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Also @jneplokh, as a good habit, when you create PRs that touches design, you can add screenshots so it's easier to review :)

**Comment by jneplokh** [comment]
> Also @jneplokh, as a good habit, when you create PRs that touches design, you can add screenshots so it's easier to review :)

Makes sense! Will do in the future ;) 

Thank you for the help here, too!

**Comment by jneplokh** [comment]
For the requested reviewers here is a screenshot:

Screen Shot 2020-10-31 at 11 51 30 AM

**Review by marcoambrosini — COMMENTED** [review]
Any particular reason behind lowering the font size in the search box? Shouldn't we keep 15px?

**Comment by skjnldsv** [comment]
Right, we're now using 15. Let's fix this with https://github.com/nextcloud/server/pull/23798?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEyODU2NDMxMjk6MTQ5NzUwNDY%3D&notifications_query=is%3Aunread#pullrequestreview-521410262

**Pull request merged**
