### PR TITLE
[stable24] invalidate existing tokens when deleting an oauth client

### LINKED ISSUE #35068: [Bug]: deleting oauth client does not delete the tokes given out by the client
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After an oAuth client is deleted in NC the tokens that it has given out are still valid and can be used for authentication

We have encountered this issue while developing the [OpenProject integration app](https://github.com/nextcloud/integration_openproject)
The only workaround we have found is to get all tokens of a oauth client before deleting it and invalidate them one by one:  https://github.com/nextcloud/integration_openproject/pull/261 but IMO it would be better if that would happen automatically when the client gets deleted

### Steps to reproduce

1. create an oauth client
2. connect to NC using that oauth client
3. delete the oauth client
4. try to use the issued tokens to connect to NC

### Expected behavior

tokens should be invalidated

### Installation method

_No response_

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.108.156",
            "host.docker.internal",
            "172.17.0.1",
            "192.168.10.29"
        ],
        "apps_paths": [
            {
                "path": "\/home\/artur\/www\/nextcloud-server\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/home\/artur\/www\/nextcloud-server\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.1",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud-server",
        "htaccess.RewriteBase": "\/nextcloud-server\/",
        "installed": true,
        "debug": true,
        "allow_local_remote_servers": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "\u00fc\u00e4\u00fc\u00fc",
        "0": [
            [
                "localhost",
                11211
            ]
        ],
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.0
  - integration_openproject: 2.1.0
  - lookup_server_connector: 1.14.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - provisioning_api: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - systemtags: 1.16.0
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - testing
  - user_ldap
```

### Nextcloud Signing status

```shell
Integrity checker has been disabled. Integrity cannot be verified.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by individual-it**
When an oauth client is deleted all the existing tokens should be invalidated

fixes #35068

I've created a PR to `stable24` and not `master` because of #35045 that makes it harder to test the fix

### CODE REVIEW

**Comment by individual-it** [comment]
@come-nc I could not find anything in OCP that would do the job.
When deleting the oauth client the tokens get deleted from the `oc_oauth2_access_tokens` table but there are still present in the `oc_authtoken` table. I don't quite understand how the complete workflow works, but it looks to me that the the real authentication happens with data from `oc_authtoken`.

**Comment by individual-it** [comment]
I believe the last test that is failing is not relevant to the code changes

**Comment by julien-nc** [comment]
### OC vs OCP
@nickvergessen @juliushaertl @blizzz As `OC\Authentication\Token\IProvider` is used by quite some apps
* https://github.com/nextcloud/notifications/blob/c61830aa40ae5430cc0e143cffbffbdba653384a/lib/Controller/PushController.php#L28
* https://github.com/nextcloud/spreed/blob/2d3c1b294127473cad08dcc42f2c1144cb897c4d/lib/MatterbridgeManager.php#L26
* https://github.com/nextcloud/user_oidc/blob/4ad91f540ed18c2f67aab685449a48a98bfc7a3a/lib/Controller/LoginController.php#L31

Can/should we consider providing an interface in the `OCP` namespace?

### Token management

In the `oauth2` app, it seems tokens are duplicated between an oauth2 table and `oc_authtoken`.
Same in the `notifications` app with `oc_notifications_pushhash`.
So when we delete a token in the app-specific tables, it stays in `oc_authtoken` if we don't take care of it (with `OC\Authentication\Token\IProvider`).
For example in https://github.com/nextcloud/notifications/blob/c61830aa40ae5430cc0e143cffbffbdba653384a/lib/Controller/PushController.php#L264-L271
@nickvergessen Is this intentional or does it leave a token alive while we expect it to be gone?

**Comment by nickvergessen** [comment]
> Same in the notifications app with oc_notifications_pushhash.
So when we delete a token in the app-specific tables, it stays in oc_authtoken if we don't take care of it (with OC\Authentication\Token\IProvider).

Notification is only additional. Not every authtoken has a pushhash entry (only the ones from devices that register for push afterwards). It is also self healing, stray entries from oc_notifications_pushhash are deleted on first push after oc_authtoken got deleted. So ignore that part. It's never used for authentication and basically only in another table to not bloat the oc_authtoken table with columns that are notification app specific.

> Can/should we consider providing an interface in the OCP namespace?

I would welcome that. Also the current IToken interface does not have all columns, so apps need to even type hint to an actual implementation.

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
```
There were 3 errors:

1) OCA\OAuth2\Tests\Controller\SettingsControllerTest::testAddClient
TypeError: Argument 7 passed to OCA\OAuth2\Controller\SettingsController::__construct() must implement interface OCP\Authentication\Token\IProvider, instance of Mock_IProvider_ce21455d given, called in /home/runner/work/server/server/apps/oauth2/tests/Controller/SettingsControllerTest.php on line 79

/home/runner/work/server/server/apps/oauth2/lib/Controller/SettingsController.php:63
/home/runner/work/server/server/apps/oauth2/tests/Controller/SettingsControllerTest.php:79

2) OCA\OAuth2\Tests\Controller\SettingsControllerTest::testDeleteClient
TypeError: Argument 7 passed to OCA\OAuth2\Controller\SettingsController::__construct() must implement interface OCP\Authentication\Token\IProvider, instance of Mock_IProvider_ce21455d given, called in /home/runner/work/server/server/apps/oauth2/tests/Controller/SettingsControllerTest.php on line 79

/home/runner/work/server/server/apps/oauth2/lib/Controller/SettingsController.php:63
/home/runner/work/server/server/apps/oauth2/tests/Controller/SettingsControllerTest.php:79

3) OCA\OAuth2\Tests\Controller\SettingsControllerTest::testInvalidRedirectUri
TypeError: Argument 7 passed to OCA\OAuth2\Controller\SettingsController::__construct() must implement interface OCP\Authentication\Token\IProvider, instance of Mock_IProvider_ce21455d given, called in /home/runner/work/server/server/apps/oauth2/tests/Controller/SettingsControllerTest.php on line 79

/home/runner/work/server/server/apps/oauth2/lib/Controller/SettingsController.php:63
/home/runner/work/server/server/apps/oauth2/tests/Controller/SettingsControllerTest.php:79
```

**Comment by individual-it** [comment]
@come-nc sorry I pushed that commit yesterday just before going home from work, I know the unit tests need to be fixed / adjusted. I will try to do that today

**Comment by come-nc** [comment]
```
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
```

**Comment by individual-it** [comment]
@come-nc a lot of files got changed, see https://github.com/nextcloud/server/pull/35094/commits/63fedca10d791f8813ffe0e738da453e61060563 I hope that is correct

**Comment by come-nc** [comment]
> @come-nc a lot of files got changed, see [63fedca](https://github.com/nextcloud/server/commit/63fedca10d791f8813ffe0e738da453e61060563) I hope that is correct

I think it is correct, the CI is happy. It seems you ran into a composer new version, which often moves a few thing around.

**Comment by individual-it** [comment]
yes I believe the last failing test is not related to my changes

**Comment by szaimen** [comment]
This is missing one approval...

**Review by julien-nc — APPROVED** [review]

**Comment by blizzz** [comment]
moving to 24.0.9

**Comment by individual-it** [comment]
forward port to master in #36033
forward port to stable25 in #36034

**Pull request merged**
