### PR TITLE
[stable10] Fix update notification

### PR DESCRIPTION
**Pull request by MorrisJobke**
- backport of #1307 
- tested and works locally

cc @LukasReschke @nextcloud/designers @nickvergessen @rullzer @karlitschek @MariusBluem

### CODE REVIEW

**Comment by MorrisJobke** [comment]
and of course I forgot the test fixing commit -.-

**Comment by karlitschek** [comment]
makes sense 👍

**Comment by nickvergessen** [comment]
:+1:

**Comment by MariusBluem** [comment]
THX.

**Pull request merged**
