### PR TITLE
fix(dashboard): html validation

### PR DESCRIPTION
**Pull request by ShGKme**
* Resolves: a part of https://github.com/nextcloud/andy/issues/5
## Summary

> Error: Element [`div`](https://html.spec.whatwg.org/multipage/#the-div-element) not allowed as child of element [`h2`](https://html.spec.whatwg.org/multipage/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements) in this context. (Suppressing further errors from this subtree.)

> Error: Element [`div`](https://html.spec.whatwg.org/multipage/#the-div-element) not allowed as child of element [`label`](https://html.spec.whatwg.org/multipage/#the-label-element) in this context. (Suppressing further errors from this subtree.)

## TODO

- [x] Replace `div` icon with `span` icon

No Visual Changes.

image

image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Makes sense :+1: 

I wonder if we should add a HTML validation CI step to prevent this in the first place.

**Review by szaimen — APPROVED** [review]

**Comment by ShGKme** [comment]
> Makes sense 👍
> 
> I wonder if we should add a HTML validation CI step to prevent this in the first place.

We should (there is an issue somewhere from Andy), but after the end of the main accessibility project

**Comment by ShGKme** [comment]
Drone fail is unrelated, but I cannot merge if CI is red

**Comment by szaimen** [comment]
Drone failure urelated

**Pull request merged**
