### PR TITLE
Fix LDAP user unable to accept/reject group share

### PR DESCRIPTION
**Pull request by g1smo**
Fix for issue here:
https://github.com/nextcloud/server/issues/21896

### CODE REVIEW

**Comment by blizzz** [comment]
From https://github.com/nextcloud/server/issues/21896#issuecomment-660290651:

> The problem was that when checking if the logged in user is a member of the group that the folder was shared with, the list of members was not populated.

**Comment by ChristophWurst** [comment]
> From [#21896 (comment)](https://github.com/nextcloud/server/issues/21896#issuecomment-660290651):
> 
> > The problem was that when checking if the logged in user is a member of the group that the folder was shared with, the list of members was not populated.

so … close?

**Comment by blizzz** [comment]
> > From [#21896 (comment)](https://github.com/nextcloud/server/issues/21896#issuecomment-660290651):
> > > The problem was that when checking if the logged in user is a member of the group that the folder was shared with, the list of members was not populated.
> 
> so … close?

No, the quoted message is the reason behind the PR. Someone more familiar with the share code ought to say whether this is the proper fix.

**Comment by g1smo** [comment]
This PR is one of the two possible ways to fix the issue I linked above.
It could be useful in understanding what is going wrong, it would make sense to close it once the issue is fixed, IMO.

**Comment by PVince81** [comment]
the issue seems to have disappeared in recent versions, see https://github.com/nextcloud/server/issues/21896

close ?

**Comment by PVince81** [comment]
I'll close this. Feel free to reopen if this was still valid. Thanks

**Pull request closed without merging**
