### PR TITLE
fix(updatenotification): a11y of channel menu and new icons

### PR DESCRIPTION
**Pull request by ShGKme**
### A11y fix

Before there were custom attributes for `menuitemradio` which were not fully correct.
- `button` was inside `menuitemradio` but has to be `menuitemradio` itself
- `aria-label` is not needed
- `aria-checked` should be on the same element as `menuitemradio`

Since `NcActionButton` now supports radio out of the box, use it to have correct a11y attributes and consistent styles.

Before | After
---|---
image | image

### Icons update

`Check` icon on **Stable** doesn't look good together with `Check` on **checked** variant. 

Before | After
---|---
image | image

Replaced with Check in clouds. Also added icons for Daily and Git channels.

Daily | Git
---|---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
lgtm

ref for icons: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5284

**Review by Pytal — APPROVED** [review]
Code looks clean!

**Review by skjnldsv — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]

**Review by jancborchardt — COMMENTED** [review]
@ShGKme small detail: The icons seem to have gone from top-aligned with the headings (as intended design-wise) to center-aligned. Could that be fixed back? :)

**Comment by susnux** [comment]
@jancborchardt see https://github.com/nextcloud-libraries/nextcloud-vue/issues/5284

**Comment by jancborchardt** [comment]
@susnux ah thanks! :)

**Pull request merged**
