### PR TITLE
fix searching and ordering on getlastmodified

### PR DESCRIPTION
**Pull request by icewind1991**
Example query:

    curl -u test:test -X SEARCH https://localcloud.icewind.me/remote.php/dav -H 'Content-Type: text/xml' --data '<?xml version="1.0" encoding="UTF-8"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://nextcloud.com/ns"><d:basicsearch><d:select><d:prop><d:getcontenttype/><d:resourcetype/><d:getcontentlength/><d:getlastmodified/><d:getetag/><oc:permissions xmlns:oc="http://owncloud.org/ns"/><oc:id xmlns:oc="http://owncloud.org/ns"/><oc:size xmlns:oc="http://owncloud.org/ns"/><oc:favorite xmlns:oc="http://owncloud.org/ns"/></d:prop></d:select><d:from><d:scope><d:href>/files/test</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:gt><d:prop><d:getlastmodified/></d:prop><d:literal>2017-03-10T22:06:30Z</d:literal></d:gt></d:where><d:orderby><d:order><d:prop><d:getlastmodified/></d:prop><d:descending/></d:order></d:orderby></d:basicsearch></d:searchrequest>'

### CODE REVIEW

**Comment by icewind1991** [comment]
Fixes https://github.com/nextcloud/server/issues/3815

**Comment by mario** [comment]
@icewind1991 looks good as far as d:getlastmodified is concerned, but ordering (d:ascending or d:descending) seems to have no influence on the output?

**Comment by icewind1991** [comment]
Will fix in a separate PR

**Comment by mario** [comment]
👍  @icewind1991 then this one is fine.

**Review by mario — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
I fixed the unit tests and it works 👍

**Pull request merged**
