### PR TITLE
Allow IPv6 database hosts

### LINKED ISSUE #9157: IPv6 in mysql address
there could be more then one `:` in it, so `explode` is no solution for it.

```
php > print_r (explode(":","[::1]:3306",2));
Array
(
    [0] => [
    [1] => :1]:3306
)
```

https://github.com/nextcloud/server/blob/01482b32a171bb8529bc8baacbe764107e52e14c/lib/private/DB/ConnectionFactory.php#L198

### PR DESCRIPTION
**Pull request by nickvergessen**
Replace #7621 
Fix #9157

### CODE REVIEW

**Comment by nickvergessen** [comment]
Done

**Comment by MorrisJobke** [comment]
I just added some more tests to cover also domain names 😉

**Review by MorrisJobke — APPROVED** [review]
Code makes sense and still works 👍

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@nickvergessen Could you open the backport for stable13?

**Pull request merged**
