### PR TITLE
Do not create local world-readable files and directories per default

### PR DESCRIPTION
**Pull request by Flowdalic**
Starting with e5dc1a808 ("Set umask before operations that create
local files") Nextcloud would create local files and directories with
their permission set to world readable. While you can protect access
to nextcloud's data/ directory by -x'ing it, when it comes to
permissions and security, a defensive approach is always
preferable. Hence this changes the used umask from 022 to 027.

This partly addresses #29041.

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Comment by Flowdalic** [comment]
Rebased on the latest master and added DCO. Please approve the workflows. Thanks.

**Comment by come-nc** [comment]
My preference would really go toward leaving umask alone, or at least make it an option.

**Review by come-nc — COMMENTED** [review]
My preference would really go toward leaving umask alone, or at least make it an option.

**Comment by szaimen** [comment]
Something like https://github.com/nextcloud/server/pull/31293 ?

**Comment by szaimen** [comment]
obsoleted by https://github.com/nextcloud/server/pull/32723

**Pull request closed without merging**
