### PR TITLE
[stable9] revise updater.server.url to reflect nextcloud.org URL

### PR DESCRIPTION
**Pull request by rob-mosher**
Please see https://github.com/nextcloud/server/issues/102 for more info

With thanks to @MorrisJobke and @mar1u5 for their help!

### CODE REVIEW

**Comment by mar1u5** [comment]
OK. URL seems to bee correct already ... you've just changed "ownCloud" to "Nextcloud" :)
👍 from my side

**Comment by hailthemelody** [comment]
Bizarre, it was owncloud.com in the URL beforehand - perhaps someone else made the change when I sent a PR to the master? Please see https://github.com/nextcloud/server/pull/133/commits/60f4f99002edf269c7bd3bee4bf774d9e341f6a8 and https://github.com/nextcloud/documentation/pull/18/commits/0032cb98e77dbde5383ee128834cebb3b4789956

**Comment by mar1u5** [comment]
Was changed here https://github.com/nextcloud/server/commit/eb7ed2356fa3b614c48a1afa2fb7449d1c8d1dc7 by @LukasReschke

**Comment by hailthemelody** [comment]
Please note that the nextcloud URL was changed in the earlier commit and for reasons I'm currently unable to determine it appears to already be changed above. Please see https://github.com/nextcloud/server/pull/133/commits/60f4f99002edf269c7bd3bee4bf774d9e341f6a8 and https://github.com/nextcloud/documentation/pull/18/commits/0032cb98e77dbde5383ee128834cebb3b4789956

**Comment by hailthemelody** [comment]
Thanks @mar1u5

**Comment by mar1u5** [comment]
Could we have a 2nd review? @MorrisJobke @LukasReschke

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
