### PR TITLE
Run acceptance tests on macOS

### PR DESCRIPTION
**Pull request by MorrisJobke**
Another step to have the acceptance tests running on macOS.

cc @danxuliu @rullzer @LukasReschke 

They are not fully running but this is already one step closer to this goal.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This works so far on macOS and if this runs on drone and linux as well I would like to merge it.

**Review by rullzer — APPROVED** [review]
Looks good to me

**Comment by MorrisJobke** [comment]
As the tests run fine and this is only for macOS test execution I will merge it :)

**Comment by danxuliu** [comment]
I'm late to the party, but I confirm that it works fine in GNU/Linux (although I'd have applied [these minor changes](https://github.com/nextcloud/server/compare/17c7b64f04510e9f37e105c579fb4314d4460fc5...danxuliu:acceptance-macos-nitpicking) before the merge (I know that you are rolling your eyes, don't bother answering, but I couldn't help it :P )).

**Comment by MorrisJobke** [comment]
> I'm late to the party, but I confirm that it works fine in GNU/Linux (although I'd have applied these minor changes before the merge (I know that you are rolling your eyes, don't bother answering, but I couldn't help it :P )).

😆 Could you open a PR to bring your changes in? That would be wonderful :)

**Pull request merged**
