### PR TITLE
fix(TagSearchProvider): Short circuit if no tag matches the query

### PR DESCRIPTION
**Pull request by marcelklehr**
## Summary
Avoids running a full files search if no tag matches in the first place.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by juliushaertl** [comment]
Psalm complains about the parameter of getAllTags but otherwise looks reasonable :)

**Review by miaulalala — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by marcelklehr** [comment]
Fingers crossed you have better luck than me :)

**Pull request merged**
