### PR TITLE
Cleanup of leftover-sorting-code from quickaccess-feature #9714 #9720

### PR DESCRIPTION
**Pull request by newhinton**
See #9714
See #9720
See #10176
See #10246

### CODE REVIEW

**Comment by newhinton** [comment]
@skjnldsv Can you verify that i did not delete any routes or code that is important? There have been some changes, and i don't want to break stuff

@rullzer This one should be better, i'll just close #10246 now

**Review by MorrisJobke — APPROVED** [review]
Tested and works still totally fine. 👍

**Review by skjnldsv — APPROVED** [review]

**Comment by newhinton** [comment]
@skjnldsv Can you give me a little hint here? How do i fix the missing sign-off's for the older commits?

**Comment by rullzer** [comment]
@newhinton you'd need to do a `git rebase -i` to edit the commits step by step. But I can sign them off for now :)

**Comment by MorrisJobke** [comment]
JSUnit tests fail :/

**Comment by newhinton** [comment]
I think i know why, but i'll need some time to fix it

**Comment by skjnldsv** [comment]
@newhinton any news? :)

**Comment by newhinton** [comment]
@skjnldsv I am currently writing exams, and also the heat is very problematic at the moment. I will return developing early next week, though!

**Comment by skjnldsv** [comment]
Okay, i'll see if I can help before your return! :)
If not, we'll wait for you! ;)

**Pull request merged**
