### PR TITLE
Make sure the function signatures of the backgroundjob match

### PR DESCRIPTION
**Pull request by rullzer**
Else PHP says no

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Review by blizzz — APPROVED** [review]
:elephant:

**Review by nickvergessen — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@rullzer Backport?

**Pull request merged**
