### PR TITLE
Bump jquery-ui from 1.10 to 1.12.1

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] Requires/based on #11701 

Full jquery-ui 0.12 changelog: https://jqueryui.com/changelog/1.12.0/

Motivation for updating this: our ancient jQuery version and the numerous warnings from jquery-migrate which many originate from jquery-ui 0.10.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Wasn't the main idea to drop jquery-ui? Wasn't it only the LDAP wizard that used it?

**Comment by ChristophWurst** [comment]
Aren't modals (file picker for example) also jq-ui?

If it really is just the LDAP app then we could move the dependency out of server.

**Comment by MorrisJobke** [comment]
> Loading the files app without jquery-ui.min.js 🙈

🙈

**Comment by MorrisJobke** [comment]
Problem with this is, that we highly tweaked the file :/

**Comment by ChristophWurst** [comment]
> Problem with this is, that we highly tweaked the file :/

Is this in any way reproducible? Do we have patches?

I just don't want to ditch the idea of keeping these libraries up to date again.

**Comment by MorrisJobke** [comment]
> Is this in any way reproducible? Do we have patches?

Not that I'm aware of. I could also be wrong here :/ Browsing the history of that folder it looks like I did an extraction of the changes back in 2014 🙈

**Comment by ChristophWurst** [comment]
Are you talking about https://github.com/nextcloud/server/blob/master/core/js/jquery-ui-fixes.js?

Anyway, I quickly tested the server UI with this branch and I couldn't spot any obvious regressions.

**Comment by rullzer** [comment]
@ChristophWurst could you creata an issue with the places we still us jquery-ui? Then maybe we can work towards dropping it case by case?

**Comment by ChristophWurst** [comment]
Easier said than done, but I'll try my best to build such a list :+1:

**Comment by MorrisJobke** [comment]
> These are jus the very obvious usages, but it gives an idea of how much jquery UI we still use:

Okay ... didn't expected that. But also testing this will be very interesting :/

**Comment by ChristophWurst** [comment]
> Okay ... didn't expected that. But also testing this will be very interesting :/

If you look at the jquery UI changelogs, there is very little that was removed. I think the APIs haven't changed much, so almost everything should *just work* :crossed_fingers:

**Comment by ChristophWurst** [comment]
> If you look at the jquery UI changelogs, there is very little that was removed. I think the APIs haven't changed much, so almost everything should just work crossed_fingers

> MorrisJobke reacted with laugh emoji

Because I jinxed it? :D

**Comment by blizzz** [comment]
sharing auto-completion seems broken (and why do we expose the user id!?):

sharing

Otherwise file upload, filepicker, datepicker, LDAP looked fine to me.

**Comment by juliushaertl** [comment]
> and why do we expose the user id

@blizzz Does this happen on master as well? Might be a bug from #11899, I haven't tested it with LDAP yet.

**Comment by blizzz** [comment]
> @blizzz Does this happen on master as well? Might be a bug from #11899, I haven't tested it with LDAP yet.

Yes, I opened a separate issue

**Comment by MorrisJobke** [comment]
Let's do this in 16.

**Comment by ChristophWurst** [comment]
> Let's do this in 16.

Wanna do this now? Better have this earlier than later, then we will notice any breakage more likely.

**Review by MorrisJobke — APPROVED** [review]
Fine with me 👍

**Review by juliusknorr — APPROVED** [review]
Let's do this. :+1:

**Comment by ChristophWurst** [comment]
Thank you :fireworks:

**Pull request merged**
