### PR TITLE
l10n: Spelling unification

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Transifex.

Note: Once confirmed, change other text strings where menu path information appears.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by szaimen** [comment]
Not sure about this one. cc @jancborchardt

**Review by rakekniven — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
fine by me then

**Comment by Valdnet** [comment]
@szaimen Please merge 😉.

**Comment by szaimen** [comment]
I cannot. There seems to be still one related failure...

**Review by rakekniven — APPROVED** [review]

**Pull request merged**
