### PR TITLE
fix: Move contacts menu JSON format to public interface

### PR DESCRIPTION
**Pull request by ChristophWurst**
## Summary

Doesn't really fix anything but the spec should be on the interface IMO.

PHP allows this: https://3v4l.org/JbouL

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
I know this can cause problems, but if psalm is green then it's good

**Comment by ChristophWurst** [comment]
which problems?

**Comment by provokateurin** [comment]
Some places only work with the implementation so psalm doesn't understand that it needs to inherit the annotation from the interface. But as I said, if psalm is green the change is good.

**Comment by ChristophWurst** [comment]
Conflicts and has to be redone.

**Pull request closed without merging**
