### PR TITLE
Feature/shares overview

### LINKED ISSUE #5559: Overview of all shared files
What we are missing is a simple overview of all shared files regardless if shared with you, by you or by link. Right now we only have the specific views. Oftentimes you might not know how it was shared, but you just want an overview.

Especially with the upcoming entry for pending & rejected shares https://github.com/nextcloud/server/issues/2192 we also need one simple main entry to show _all_ shares. The others can be sub-entries like subfolders in the Mail or News app.

cc @nextcloud/sharing

### PR DESCRIPTION
**Pull request by skjnldsv**
Fixes #5559 

Found bugs (unrelated):
- [ ] All sharing in sidebar appear as "reshare not allowed" (master as well)
- [ ] Error in console when opening the sidebar (master as well)
```
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object
    at FileList.updateRow (sharedfilelist.js:165)
```

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
One small thing:

* [ ] in the overview received shares are listed as "Shared with MYNAME" instead of "Shared by OTHERPERSON" (which is the case in the section "Shared with you"):

bildschirmfoto 2018-07-13 um 17 45 44
bildschirmfoto 2018-07-13 um 17 46 32

**Comment by skjnldsv** [comment]
@MorrisJobke : Fixed! :)

**Comment by jancborchardt** [comment]
- Should be called "Shares" instead of "Share overview"
- Why is "Deleted shares" not a subentry of it?
- The highlight bar of the subentries is floating in mid-air? Should also be on the left side of the viewport

**Review by jancborchardt — APPROVED** [review]
Looking good, checked with @MorrisJobke :)

**Comment by jancborchardt** [comment]
Follow-up polishing issue at https://github.com/nextcloud/server/issues/10261

**Comment by MorrisJobke** [comment]
@skjnldsv Mind to look at the failing jsunit tests? :(

**Comment by skjnldsv** [comment]
@MorrisJobke I cry so much with those tests! ^^

> Why is "Deleted shares" not a subentry of it?

it was not to be confusing since the deleted shares are not compatible with the overview. So the user does not thinks they should appear on the overview :)

**Comment by skjnldsv** [comment]
@MorrisJobke I cry so much with those tests! ^^

> Why is "Deleted shares" not a subentry of it?

it was not to be confusing since the deleted shares are not compatible with the overview. So the user does not thinks they should appear on the overview :)

**Comment by skjnldsv** [comment]
All fix! :)

LGTM :ship:

**Pull request merged**
