### PR TITLE
29.0.0 beta 2

### PR DESCRIPTION
**Pull request by Altahrim**
* #39990
* #42170
* #42628
* #42661
* #42707
* #43425
* #43589
* #43778
* #43907
* #43946
* #43982
* #43983
* #43992
* #44049
* #44062
* #44064
* #44073
* #44074
* #44076
* #44082
* #44083
* #44091
* #44092
* #44103
* #44117
* #44119
* #44134
* #44138
* #44140
* #44142
* #44151
* nextcloud/bruteforcesettings#569
* nextcloud/bruteforcesettings#570
* nextcloud/bruteforcesettings#571
* nextcloud/circles#1525
* nextcloud/files_downloadlimit#232
* nextcloud/files_downloadlimit#233
* nextcloud/files_downloadlimit#234
* nextcloud/files_downloadlimit#235
* nextcloud/firstrunwizard#1119
* nextcloud/firstrunwizard#1121
* nextcloud/logreader#1099
* nextcloud/logreader#1129
* nextcloud/logreader#1138
* nextcloud/logreader#1141
* nextcloud/logreader#1144
* nextcloud/logreader#1146
* nextcloud/logreader#1149
* nextcloud/logreader#1156
* nextcloud/logreader#1161
* nextcloud/logreader#1167
* nextcloud/logreader#1169
* nextcloud/logreader#1173
* nextcloud/logreader#1174
* nextcloud/logreader#1178
* nextcloud/logreader#1179
* nextcloud/nextcloud_announcements#302
* nextcloud/nextcloud_announcements#305
* nextcloud/notifications#1798
* nextcloud/notifications#1845
* nextcloud/notifications#1846
* nextcloud/notifications#1847
* nextcloud/notifications#1849
* nextcloud/photos#2377
* nextcloud/photos#2379
* nextcloud/privacy#1042
* nextcloud/privacy#1043
* nextcloud/recommendations#706
* nextcloud/recommendations#707
* nextcloud/recommendations#712
* nextcloud/serverinfo#569
* nextcloud/serverinfo#570
* nextcloud/text#5447
* nextcloud/text#5449
* nextcloud/text#5452
* nextcloud/text#5453
* nextcloud/text#5461
* nextcloud/text#5462
* nextcloud/text#5463
* nextcloud/text#5464
* nextcloud/viewer#2020
* nextcloud/viewer#2053
* nextcloud/viewer#2054
* nextcloud/viewer#2136
* nextcloud/viewer#2143
* nextcloud/viewer#2160
* nextcloud/viewer#2168
* nextcloud/viewer#2173
* nextcloud/viewer#2174
* nextcloud/viewer#2175
* nextcloud/viewer#2180
* nextcloud/viewer#2191
* nextcloud/viewer#2192
* nextcloud/viewer#2193
* nextcloud/viewer#2194
* nextcloud/viewer#2195
* nextcloud/viewer#2196
* nextcloud/viewer#2197
* nextcloud/viewer#2198
* nextcloud/viewer#2199
* nextcloud/viewer#2200
* nextcloud/viewer#2201
* nextcloud/viewer#2211
* nextcloud/viewer#2222

## Pending PRs:
* @2lar
  * [ ] #37878
* @a-bran
  * [ ] #42352
* @aaygupta
  * [ ] #39291
* @abangtor
  * [ ] #25300
* @Abijeet
  * [ ] nextcloud/logreader#476
* @adam-blakey
  * [ ] #33546
* @adriano-pinaffo
  * [ ] nextcloud/photos#1834
* @aentwist
  * [ ] #37564
* @ajabep
  * [ ] #39074
* @akhil1508
  * [ ] #35867
  * [ ] #37328
* @aleixq
  * [ ] #37896
* @alpapan
  * [ ] #35701
* @Altahrim
  * [ ] nextcloud/updater#516
* @ArtificialOwl
  * [ ] #32827
  * [ ] #33051
  * [ ] #35526
  * [ ] #38603
  * [ ] #39134
  * [ ] #39957
  * [ ] #41478
  * [ ] #43258
  * [ ] #43534
  * [ ] #43574
  * [ ] nextcloud/circles#1089
  * [ ] nextcloud/circles#1090
  * [ ] nextcloud/circles#1148
  * [ ] nextcloud/circles#1214
  * [ ] nextcloud/circles#1217
  * [ ] nextcloud/circles#1320
  * [ ] nextcloud/circles#1394
  * [ ] nextcloud/circles#878
  * [ ] nextcloud/circles#891
  * [ ] nextcloud/circles#966
  * [ ] nextcloud/circles#980
* @artonge
  * [ ] #34956
  * [ ] #40536
  * [ ] #44069
  * [ ] nextcloud/photos#1450
  * [ ] nextcloud/photos#2126
* @arublov
  * [ ] #43366
  * [ ] #43512
* @ASerbinski
  * [ ] #32631
* @avinash-0007
  * [ ] #35553
* @blizzz
  * [ ] #32197
  * [ ] #38624
  * [ ] #43942
  * [ ] nextcloud/updater#506
* @camilasan
  * [ ] #43281
* @CarlSchwan
  * [ ] #33127
  * [ ] #35324
  * [ ] #35460
* @cdammanintopix
  * [ ] #34115
* @charleypaulus
  * [ ] #35189
* @chrisfritsche
  * [ ] nextcloud/activity#504
* @ChristophWurst
  * [ ] #35388
  * [ ] #35599
  * [ ] #35767
  * [ ] #37950
  * [ ] #38542
  * [ ] #40628
  * [ ] #40655
  * [ ] #40878
  * [ ] #40960
  * [ ] #44130
* @cneukom
  * [ ] #33397
* @come-nc
  * [ ] #43527
  * [ ] #44067
* @danialRahimy
  * [ ] #39192
  * [ ] #39883
* @danxuliu
  * [ ] #33484
  * [ ] nextcloud/files_pdfviewer#654
* @dertuxmalwieder
  * [ ] nextcloud/serverinfo#425
* @djon2003
  * [ ] #41370
* @emoral435
  * [ ] #44109
* @FedericoHeichou
  * [ ] #39611
  * [ ] #40019
* @Fenn-CS
  * [ ] #38476
* @fgsl
  * [ ] nextcloud/circles#226
  * [ ] nextcloud/circles#229
* @fitrahmunir
  * [ ] #41659
* @flooxo
  * [ ] #41183
* @fsamapoor
  * [ ] #39692
  * [ ] #39882
* @func0der
  * [ ] #40468
* @GretaD
  * [ ] #40163
* @haikyuu
  * [ ] #39730
* @hamza221
  * [ ] #37871
  * [ ] #38369
* @hardviper
  * [ ] #43684
* @haslersn
  * [ ] #40407
* @hellodarkness
  * [ ] #42610
* @helmo
  * [ ] #44094
* @HolgerHees
  * [ ] #43573
* @HolonProduction
  * [ ] #41189
* @hopleus
  * [ ] #43652
* @hoxia
  * [ ] nextcloud/circles#338
* @hrenard
  * [ ] #42931
* @icewind1991
  * [ ] #29886
  * [ ] #30972
  * [ ] #31905
  * [ ] #32028
  * [ ] #33579
  * [ ] #33581
  * [ ] #33582
  * [ ] #33597
  * [ ] #33918
  * [ ] #33985
  * [ ] #34056
  * [ ] #34655
  * [ ] #35523
  * [ ] #36526
  * [ ] #36613
  * [ ] #36783
  * [ ] #36942
  * [ ] #37742
  * [ ] #38367
  * [ ] #38470
  * [ ] #38489
  * [ ] #38547
  * [ ] #38765
  * [ ] #39168
  * [ ] #39231
  * [ ] #39247
  * [ ] #39366
  * [ ] #39399
  * [ ] #40105
  * [ ] #40109
  * [ ] #40165
  * [ ] #40394
  * [ ] #40522
  * [ ] #41116
  * [ ] #41434
  * [ ] #41973
  * [ ] #43531
  * [ ] #43613
  * [ ] #43655
  * [ ] #43851
  * [ ] #44004
  * [ ] #44132
  * [ ] nextcloud/activity#698
  * [ ] nextcloud/logreader#906
* @individual-it
  * [ ] #37761
* @inet-cologne
  * [ ] #37477
* @J0WI
  * [ ] #28279
  * [ ] #35581
  * [ ] #35587
* @JanisPlayer
  * [ ] #40048
  * [ ] nextcloud/photos#2047
  * [ ] nextcloud/viewer#1973
* @jbmolle
  * [ ] #36791
* @JeaNugroho
  * [ ] #38952
  * [ ] #39022
* @Jerome-Herbinet
  * [ ] #36831
  * [ ] #37862
  * [ ] #38096
  * [ ] #38670
  * [ ] #40161
  * [ ] #41155
  * [ ] nextcloud/circles#1422
* @JiyaGupta-cs
  * [ ] #41226
* @jkellerer
  * [ ] nextcloud/photos#1417
  * [ ] nextcloud/photos#1419
* @JonathanTreffler
  * [ ] #37289
* @joshtrichards
  * [ ] #37581
  * [ ] #38151
  * [ ] #38364
  * [ ] #38630
  * [ ] #38857
  * [ ] #39242
  * [ ] #43794
* @julien-nc
  * [ ] #29729
  * [ ] #43862
  * [ ] #43993
* @juliushaertl
  * [ ] #27531
  * [ ] #37150
  * [ ] #37736
  * [ ] #38407
  * [ ] #38722
  * [ ] #39290
  * [ ] #39303
  * [ ] nextcloud/viewer#1862
* @karlitschek
  * [ ] #33545
* @kesselb
  * [ ] #37178
  * [ ] #38385
  * [ ] #38445
  * [ ] #38632
  * [ ] #38933
  * [ ] #39702
  * [ ] #42534
* @klondi
  * [ ] #40208
* @Koc
  * [ ] #41582
* @ktprograms
  * [ ] nextcloud/viewer#1063
* @kyteinsky
  * [ ] #41684
* @LakshayaTohan
  * [ ] nextcloud/logreader#857
* @linuzer
  * [ ] #44096
* @madmas
  * [ ] nextcloud/activity#460
* @makoehr
  * [ ] nextcloud/updater#471
* @marcelklehr
  * [ ] nextcloud/photos#1121
* @marcoambrosini
  * [ ] #41718
* @max-nextcloud
  * [ ] nextcloud/text#3799
* @Mazhoon
  * [ ] #35270
* @meichthys
  * [ ] #34082
* @Mikescops
  * [ ] nextcloud/photos#515
* @moan0s
  * [ ] #37953
* @mrvahedi68
  * [ ] #39411
* @msrn
  * [ ] #33729
* @mutazawadorg
  * [ ] #34198
* @nickvergessen
  * [ ] #41234
* @nooblag
  * [ ] #39669
* @onny
  * [ ] #43601
  * [ ] nextcloud/circles#1349
* @pboguslawski
  * [ ] #33715
  * [ ] #33795
  * [ ] #33879
* @privatemaker
  * [ ] #40544
* @provokateurin
  * [ ] #42678
  * [ ] #42973
  * [ ] #43699
  * [ ] #43877
* @pstumpe
  * [ ] nextcloud/serverinfo#461
* @Psycojoker
  * [ ] #40763
* @Pytal
  * [ ] #29892
  * [ ] #30183
  * [ ] #36812
  * [ ] #38477
  * [ ] #39825
  * [ ] #43041
  * [ ] #44139
  * [ ] #44141
* @rexbron
  * [ ] nextcloud/circles#971
* @RonaldBarnes
  * [ ] #35451
* @rotdrop
  * [ ] #36756
  * [ ] #36766
  * [ ] nextcloud/circles#1297
* @rullzer
  * [ ] #26940
  * [ ] #34491
  * [ ] #34553
  * [ ] #34562
* @Schnoop
  * [ ] #43364
* @shdehnavi
  * [ ] #39163
  * [ ] #39177
  * [ ] #39212
  * [ ] #39217
  * [ ] #39235
  * [ ] #39245
  * [ ] #39246
  * [ ] #39249
* @ShGKme
  * [ ] #41065
  * [ ] #42456
  * [ ] nextcloud/viewer#1711
* @simonspa
  * [ ] #36220
* @skjnldsv
  * [ ] #39674
  * [ ] #43254
  * [ ] nextcloud/files_pdfviewer#620
  * [ ] nextcloud/viewer#1456
* @smesterheide
  * [ ] #34132
  * [ ] #35732
* @solracsf
  * [ ] #40164
  * [ ] #42800
  * [ ] nextcloud/activity#1281
* @sorbaugh
  * [ ] #44011
* @sshambar
  * [ ] #20757
* @st3iny
  * [ ] #39592
  * [ ] #39942
  * [ ] nextcloud/recommendations#667
  * [ ] nextcloud/twofactor_totp#1467
* @starypatyk
  * [ ] #33426
  * [ ] #34918
  * [ ] nextcloud/viewer#1952
* @StCyr
  * [ ] #32647
* @sualko
  * [ ] nextcloud/recommendations#458
* @summersab
  * [ ] #36337
  * [ ] #36572
  * [ ] #40046
  * [ ] #40112
  * [ ] #40113
  * [ ] #40115
  * [ ] #40116
  * [ ] #40117
  * [ ] #40118
  * [ ] #40119
  * [ ] #40120
  * [ ] #40121
  * [ ] #40122
  * [ ] #40123
  * [ ] #40124
  * [ ] #40125
  * [ ] #40127
  * [ ] #40128
  * [ ] #40129
  * [ ] #40130
  * [ ] #40131
  * [ ] #40132
  * [ ] #40133
  * [ ] #40134
  * [ ] #40136
  * [ ] #40137
  * [ ] #40138
  * [ ] #40139
  * [ ] #40140
  * [ ] #40141
  * [ ] #40142
  * [ ] #40143
  * [ ] #40144
  * [ ] #40145
  * [ ] #40146
  * [ ] #40147
  * [ ] #40148
  * [ ] #40149
  * [ ] #40150
  * [ ] #40151
  * [ ] #40152
  * [ ] #40153
  * [ ] #40154
  * [ ] #40156
  * [ ] #40157
  * [ ] #40206
  * [ ] #40207
  * [ ] #40449
* @susnux
  * [ ] #36462
  * [ ] #40537
  * [ ] #40621
  * [ ] #41252
  * [ ] #41952
  * [ ] #42977
  * [ ] #43334
  * [ ] #43516
  * [ ] #43575
  * [ ] nextcloud/logreader#1041
  * [ ] nextcloud/password_policy#512
  * [ ] nextcloud/password_policy#513
  * [ ] nextcloud/password_policy#514
  * [ ] nextcloud/password_policy#516
  * [ ] nextcloud/password_policy#517
  * [ ] nextcloud/photos#2312
  * [ ] nextcloud/text#3331
* @szaimen
  * [ ] #35263
  * [ ] #35907
  * [ ] #37757
  * [ ] #43082
* @taminob
  * [ ] #41321
* @tanganellilore
  * [ ] #38587
* @tcitworld
  * [ ] #32321
  * [ ] #33221
  * [ ] #34873
  * [ ] #35754
  * [ ] #36252
  * [ ] #36313
  * [ ] #36327
  * [ ] #36522
  * [ ] #36681
  * [ ] #37170
  * [ ] #37193
  * [ ] #37303
  * [ ] #38093
  * [ ] #39084
  * [ ] #39372
  * [ ] #39589
  * [ ] #39977
  * [ ] #40464
  * [ ] #40997
  * [ ] #41255
  * [ ] #42347
  * [ ] #42763
* @the-djmaze
  * [ ] #36239
* @TheKhanj
  * [ ] #41002
* @theronakpatel
  * [ ] #40796
* @ThibautPlg
  * [ ] #40427
* @tortuetorche
  * [ ] nextcloud/circles#384
  * [ ] nextcloud/circles#392
  * [ ] nextcloud/circles#395
  * [ ] nextcloud/circles#398
  * [ ] nextcloud/circles#399
  * [ ] nextcloud/circles#400
  * [ ] nextcloud/circles#401
* @tsdicloud
  * [ ] #39464
* @unteem
  * [ ] #32781
* @vitormattos
  * [ ] nextcloud/password_policy#469
* @walec51
  * [ ] #40821
* @whlsxl
  * [ ] #38750
* @zevlee
  * [ ] #36769
* (generated)
  * [ ] #41588
  * [ ] #41590
  * [ ] nextcloud/files_pdfviewer#856

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
> Could not find base or head reference on text.

git pull against the github_helper?

**Comment by Altahrim** [comment]
## Required PRs
- https://github.com/nextcloud/server/pull/42661

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
@sorbaugh what's up with https://github.com/nextcloud/server/pull/44011 as well as https://github.com/nextcloud/server/pull/44129 ?

**Comment by nooblag** [comment]
Hi there, will [#39669](https://github.com/nextcloud/server/pull/39669) make it into NC 29?

**Comment by AndyScherzinger** [comment]
> Hi there, will https://github.com/nextcloud/server/pull/39669 make it into NC 29?

Can't say for sure at the moment. If it is in a mergable state before RC1 gets tagged I would say it can make it into v29

**Pull request merged**
