### PR TITLE
Update link to the docs to 11

### PR DESCRIPTION
**Pull request by LukasReschke**
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Is that actually used somewhere? https://github.com/nextcloud/server/search?utf8=%E2%9C%93&q=defaultDocVersion

**Comment by ChristophWurst** [comment]
but change makes sense though 👍 😉

**Comment by LukasReschke** [comment]
GitHub search lies. Open https://github.com/nextcloud/server/blob/7eaaffeee0782c89c1a7f505f622e8304d62f93b/lib/private/legacy/defaults.php#L271 directly ;)

**Comment by ChristophWurst** [comment]
ah thanks :-)

**Comment by MorrisJobke** [comment]
.+1:

**Pull request merged**
