### PR TITLE
Bump league/flysystem from 1.0.37 to 1.0.64

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] https://github.com/nextcloud/3rdparty/pull/395
- [x] Merge #19632 (unrelated changes shown here)
- [x] Rebase

Easy to review: no code actually changed :D

### CODE REVIEW

**Comment by kesselb** [comment]
> Easy to review: no code actually changed

Yeah :tada: 

But the php extension `fileinfo` is now a required dependency for `league/flysystem`. But for nextcloud itself the extension is not required (but recommended). If you merge this PR `fileinfo` needs to be mandatory. Guess who run into a similar problem: https://github.com/thephpleague/flysystem/commit/9386fec2c1fe40fef20354b5ee068c6a2852ca7e

**Comment by ChristophWurst** [comment]
Hmmmm https://github.com/thephpleague/flysystem/issues/968#issuecomment-425419038

**Comment by kesselb** [comment]
All right ;) Probably not bad to tell the user that fileinfo is not only recommended but required for some external storage.

**Comment by ChristophWurst** [comment]
Yes, we should totally add it to our docs.

**Comment by ChristophWurst** [comment]
And possibly update our setup checks?

**Review by kesselb — APPROVED** [review]

**Comment by ChristophWurst** [comment]
OTOH on https://www.php.net/manual/en/fileinfo.installation.php I read

> This extension is enabled by default as of PHP 5.3.0

**Comment by kesselb** [comment]
Yes but distributions like FreeBSD tend to disable such extensions:https://github.com/nextcloud/documentation/pull/1549

So updating docs and setupcheck is a good plan.

**Pull request merged**
