### PR TITLE
add KerberosApacheAuth support to files_external

### PR DESCRIPTION
**Pull request by blizzz**
* [x] requires https://github.com/icewind1991/SMB/pull/68 (was merged manually)
* [x] … and 3rdparty bump
* [x] requires https://github.com/icewind1991/SMB/pull/111
* [x] … and 3rdparty bump

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by blizzz** [comment]
@icewind1991 we got 1) OCA\Files_External\Tests\Storage\SmbTest::testNotifyGetChanges failing, but that should be fairly unaffected by the addition. Any idea?

**Comment by skjnldsv** [comment]
> @icewind1991 we got 1) OCA\Files_External\Tests\Storage\SmbTest::testNotifyGetChanges failing, but that should be fairly unaffected by the addition. Any idea?

ping @icewind1991  :)

**Comment by blizzz** [comment]
https://github.com/icewind1991/SMB/pull/111 is also needed now (added as todo in the description)

**Comment by icewind1991** [comment]
Also added an end-to-end test CI job

**Comment by skjnldsv** [comment]
Samba test is failing

**Pull request merged**
