### PR TITLE
Add share indicator for mail shares

### LINKED ISSUE #2369: Files shared via email have no icon indication
The file is shared by public link
The folder is shared via email

> files_-_nextcloud_-_2016-11-28_11 48 28

@schiessle 

Problem 1 is the share type is not handled in
https://github.com/nextcloud/server/blob/1190ce1dd5530865c6a5465e1e93a64002bcda47/apps/files_sharing/js/share.js#L114-L114

```js
						_.each(shareTypes.split(',') || [], function(shareType) {
							shareType = parseInt(shareType, 10);
```

Problem 2 is the share type is not returned by the dav endpoint

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #2369 

### steps
1. Share an item by mail
2. Refresh the page and try to find the share indicator in the file list

@rullzer @schiessle

### CODE REVIEW

**Comment by schiessle** [comment]
works, but wonder if we should use the link share symbol or better have a specific "share by mail" icon, maybe a envelope? cc @nextcloud/designers

**Comment by nickvergessen** [comment]
Well I think the difference is "public" or "private", but I guess then it should use the link icon. Will change after lunch

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by nickvergessen** [comment]
Updated the icon

**Comment by schiessle** [comment]
Directly after I shared a file by link it shows the internal share icon:

share-mail1

only after reload it gets updated to the link-share icon

share-mail2

**Comment by nickvergessen** [comment]
Not sure why, but that also is wrong for link shares, so lets fix separatly

**Comment by MorrisJobke** [comment]
Retested and works 👍

**Comment by schiessle** [comment]
I don't have the same issue for link shares... let me test once more

**Comment by schiessle** [comment]
> I don't have the same issue for link shares... let me test once more

Tested again (Firefox 50). For link shares the right icon is shown directly after the file gets shared. Seems there need to be one more code path where you have to do something similar to this  https://github.com/nextcloud/server/pull/2371/commits/a7aa80867a936cd4b3b6245c208b7bef2f7c97f8

**Comment by nickvergessen** [comment]
I can't seem to find it, also for me there is no icon at all until I reload the page.

**Comment by rullzer** [comment]
Should be fixed now.
@schiessle please have a look

**Pull request merged**
