### PR TITLE
handle abortion of fetching more data in infiniteHandler

### PR DESCRIPTION
**Pull request by chiefbrain**
See issue #25133.

`$state.loaded()` needs to be called if users are present.

Introduced in 824b10956f5891f70b9af74bf6bae96620949193.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Code make sense

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Comment by PVince81** [comment]
@eneiluj seems like an early alternative to your fix in https://github.com/nextcloud/server/pull/25879

**Comment by eneiluj** [comment]
@PVince81 This won't work in some cases IMO.

Here, `usersCount` does not reflect the actual displayed list length but only the raw user list count we get from the API.

`$state.loaded()` is called even if filtered users list is empty. So the empty content message won't be displayed when filtering to show disabled users while there is no disabled users. That's why `filteredUsers.length` is used to determine if we call `$state.loaded()` in #25879.

**Comment by chiefbrain** [comment]
> `$state.loaded()` is called even if filtered users list is empty. So the empty content message won't be displayed when filtering to show disabled users while there is no disabled users. That's why `filteredUsers.length` is used to determine if we call `$state.loaded()` in #25879.

length ist still used in users.js: `const usersCount = Object.keys(response.data.ocs.data.users).length`.

**Comment by eneiluj** [comment]
@chiefbrain As I couldn't push to your branch, I applied your changes to my branch in #25879, rebased on master and resolved the conflicts. I hope you don't mind :grin:

@ChristophWurst @skjnldsv #25879 is the same as this PR and it's ready to be merged.

**Pull request closed without merging**
