### PR TITLE
Display app names in user's language when upgrading.

### PR DESCRIPTION
**Pull request by tcitworld**
Fixes https://github.com/nextcloud/server/issues/6024

Before: 
selection_092

After:
selection_093

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by LukasReschke** [comment]
Rebased to retrigger tests.

**Comment by MorrisJobke** [comment]
```
There was 1 failure:

1) Test\Authentication\TwoFactorAuth\ManagerTest::testGetBackupProvider

Failed asserting that null is identical to an object of class "Mock_IProvider_8d699353".

/drone/src/github.com/nextcloud/server/pull/6025/tests/lib/Authentication/TwoFactorAuth/ManagerTest.php:218
```

**Comment by rullzer** [comment]
failing tests

**Comment by tcitworld** [comment]
So I don't know why but it seems phpunit's `returnValueMap()` was causing trouble with optional arguments.

**Comment by nickvergessen** [comment]
You have to specify optional arguments all the time in the map

**Comment by tcitworld** [comment]
> You have to specify optional arguments all the time in the map

I tried that too, but it didn't work. :'(

**Comment by MorrisJobke** [comment]
I still vote for extracting this in the l10n process and let transifex handle this. Then we should read the app name and description for the l10n files instead of hacking this into the info.xml.

**Comment by tcitworld** [comment]
@MorrisJobke I'm not sure to understand your comment. 😕

**Comment by MorrisJobke** [comment]
> @MorrisJobke I'm not sure to understand your comment. 😕

Currently translations of an app are handled via our l10n/ folder holding all the translated files. This is also the case for the app name. The app name is already extracted from info.xml and put on transifex. That means that our UI (apps management, app navigation) can use the translated app name without any further requirements.

The info.xml somehow still has this `lang="fr"` attribute build in, that is nowhere used (beside in 2 apps) and the same for the description. It would just make sense to not maintain those translations within the info.xml, but also take them, put them on transifex and put the translated terms into the l10n folder like all other translations of an app.

**Comment by tcitworld** [comment]
OK, so this would mean : 
* extract the description text just like the app name and put it into transifex
* tweak the nextcloud apps page and the app store to display name and description according to contents of `l10n` and not just `info.xml`
* Explain to app maintainers who don't use transifex for their app that they need to put the name and description strings in the `l10n` files.

**Comment by nickvergessen** [comment]
> tweak the nextcloud apps page and the app store to display name and description according to contents of l10n and not just info.xml

Well it's easier, we "just" do `\OC::$server->getL10N($appId)->t($appName)` and `\OC::$server->getL10N($appId)->t($data['description'])`

**Comment by MorrisJobke** [comment]
> Explain to app maintainers who don't use transifex for their app that they need to put the name and description strings in the l10n files.

They either don't translate or reach out to us to get the transifex integration. So I don't see this as a problem.

**Pull request closed without merging**
