### PR TITLE
Show icon only with dnd status in the message

### PR DESCRIPTION
**Pull request by juliusknorr**
Required for the status widget once we have https://github.com/nextcloud/nextcloud-vue/pull/1422

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
It needs a rebuild anyway after https://github.com/nextcloud/server/pull/23113 is in, but well so be it :P

**Comment by nickvergessen** [comment]
Bildschirmfoto von 2020-10-02 14-15-09

Uses the non-compact mode now, so icon + status are displayed (when suitable)

**Review by jancborchardt — APPROVED** [review]

**Pull request merged**
