### PR TITLE
Return ETag and OC-ETag in case of a move (#25683)

### PR DESCRIPTION
**Pull request by LukasReschke**
Downstreaming of https://github.com/owncloud/core/pull/25683

Signed-off-by: Lukas Reschke lukas@statuscode.ch

### CODE REVIEW

**Comment by nickvergessen** [comment]
👍

**Comment by MorrisJobke** [comment]
Tested and works :+1: Header is now included

**Comment by LukasReschke** [comment]
Rebased upon master.

**Comment by MorrisJobke** [comment]
Retested and works :+1:

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
This was backported upstream - https://github.com/owncloud/core/pull/26334

Should we also backport this?

**Comment by LukasReschke** [comment]
I guess so, assuming the clients use that probably 🙈

**Pull request merged**
