### PR TITLE
Fix password length limitation

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
/backport ab055418c613cfc0781fa6addab81aa2ce181bde to stable25

**Comment by nickvergessen** [comment]
/backport ab055418c613cfc0781fa6addab81aa2ce181bde to stable24

**Comment by nickvergessen** [comment]
/backport ab055418c613cfc0781fa6addab81aa2ce181bde to stable23

**Comment by nickvergessen** [comment]
/backport ab055418c613cfc0781fa6addab81aa2ce181bde to stable22

**Review by blizzz — APPROVED** [review]
preferably 469 goes into a const, but acceptable.

**Comment by nickvergessen** [comment]
Probably should in a follow up across the board.
https://github.com/nextcloud/server/blob/60c42914d8d4ef815b239cb3b83ee682e56c5c22/apps/settings/lib/Controller/ChangePasswordController.php#L98

For now magic number to improve backportability

**Review by artonge — APPROVED** [review]
Is this documented somewhere ?

**Pull request merged**
