### PR TITLE
remove LDAP::hasPagedResultSupport() from PHP < 5.4 days

### LINKED ISSUE #10923: remove LDAP::hasPagedResultSupport() as it is always present in supported PHP versions
Remove check for presence of `ldap_control_paged_result` and `ldap_control_paged_result_response` (LDAP::hasPagedResultSupport) since they are present in any supported PHP version.

### PR DESCRIPTION
**Pull request by blizzz**
/me coughs out all the dust ;) Resolves #10923

### CODE REVIEW

**Comment by blizzz** [comment]
failing tests are unrelated

**Review by rullzer — APPROVED** [review]
YAY for cleanup

Didn't test but makes sense

**Comment by blizzz** [comment]
My smoke testing went fine. If there were issues also pagination related integration tests should failfail, they don't.

**Review by MorrisJobke — APPROVED** [review]
🐘

**Pull request merged**
