### PR TITLE
unbundle files_videoplayer and clean up a little

### PR DESCRIPTION
**Pull request by blizzz**
contributes to #34203

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Lint / php-cs check (pull_request) Failing after 55s

**Comment by blizzz** [comment]
> Lint / php-cs check (pull_request) Failing after 55s

how dare it

**Comment by szaimen** [comment]
image

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
