### PR TITLE
[27/testing] improve di performance for cache

### PR DESCRIPTION
**Pull request by icewind1991**
Testing backport of https://github.com/nextcloud/server/pull/39889

### CODE REVIEW

**Comment by blizzz** [comment]
moving to 27.1.6

**Comment by blizzz** [comment]
@icewind1991 should this eventually be merged, actually?

**Comment by blizzz** [comment]
→ 27.1.7

**Comment by icewind1991** [comment]
This backport is no longer needed for test, once the master pr is merged we can do a fresh backport is desired

**Pull request closed without merging**
