### PR TITLE
fix(files): Add rounded corners back in grid view

### PR DESCRIPTION
**Pull request by artonge**
Was removed intentionally due to mockups.

- Follow-up of https://github.com/nextcloud/server/pull/46307

Before | After
-- | --
image | image

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM

**Review by jancborchardt — CHANGES_REQUESTED** [review]
`var(--border-radius)` for the image preview itself looks good, but the outside element (the hover/focus background) should have a bigger radius to match, so best use `var(--border-radius-large)` for that.

This is the same how it is in the action menus for example.

**Comment by artonge** [comment]
Updated

**Review by jancborchardt — APPROVED** [review]
:sparkles: :blue_square:

**Review by susnux — APPROVED** [review]

**Pull request merged**
