### PR TITLE
chore(3rdparty): update symfony http-foundation, routing and translat…

### PR DESCRIPTION
**Pull request by kesselb**
## Summary

Update symfony http-foundation, routing and translation to 5.4.24.

## TODO

- [x] Upgrade guide
- [x] CI
- [x] Merge https://github.com/nextcloud/3rdparty/pull/1482
- [x] Rebase

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by kesselb** [comment]
## UPGRADE FROM 4.4 to 5.0

**Routing**

- [ ] The `generator_base_class`, `generator_cache_class`, `matcher_base_class`, and `matcher_cache_class` router
   options have been removed. If you are using multiple Router instances and need separate caches for them, set a unique `cache_dir` per Router instance instead.
- [ ] `Serializable` implementing methods for `Route` and `CompiledRoute` are final.
   Instead of overwriting them, use `__serialize` and `__unserialize` as extension points which are forward compatible
   with the new serialization methods in PHP 7.4.
- [ ] Removed `ServiceRouterLoader` and `ObjectRouteLoader`.
- [ ] Service route loaders must be tagged with `routing.route_loader`.
- [ ] The `RoutingConfigurator::import()` method has a new optional `$exclude` argument.

**Translation**

- [ ] Support for using `null` as the locale in `Translator` has been removed.
- [ ] The `FileDumper::setBackup()` method has been removed.
- [ ] The `TranslationWriter::disableBackup()` method has been removed.
- [ ] The `TranslatorInterface` has been removed in favor of `Symfony\Contracts\Translation\TranslatorInterface`
- [ ] The `MessageSelector`, `Interval` and `PluralizationRules` classes have been removed, use `IdentityTranslator` instead
- [ ] The `Translator::getFallbackLocales()` and `TranslationDataCollector::getFallbackLocales()` method are now internal
- [ ] The `Translator::transChoice()` method has been removed in favor of using `Translator::trans()` with "%count%" as the parameter driving plurals
- [ ] Removed support for implicit STDIN usage in the `lint:xliff` command, use `lint:xliff -` (append a dash) instead to make it explicit.

**Comment by kesselb** [comment]
>  Added argument $priority to RouteCollection::add()

https://github.com/nextcloud/server/blob/8b3b5ff8d86613c2f9c85ff5c9c5441a451961b8/lib/private/Route/Router.php#L237
https://github.com/nextcloud/server/blob/8b3b5ff8d86613c2f9c85ff5c9c5441a451961b8/lib/private/AppFramework/Routing/RouteParser.php#L63
https://github.com/nextcloud/server/blob/8b3b5ff8d86613c2f9c85ff5c9c5441a451961b8/lib/private/AppFramework/Routing/RouteParser.php#L80
https://github.com/nextcloud/server/blob/8b3b5ff8d86613c2f9c85ff5c9c5441a451961b8/lib/private/AppFramework/Routing/RouteParser.php#L203

**Review by mejo- — APPROVED** [review]
Really nice to see how you went through the upgrade instructions :blush:

**Review by nickvergessen — APPROVED** [review]
Tests are happy, so am I

**Pull request merged**
