### PR TITLE
Move ShareByMail activities to new API

### PR DESCRIPTION
**Pull request by nickvergessen**
@MorrisJobke @schiessle for https://github.com/nextcloud/activity/pull/79

### CODE REVIEW

**Comment by rullzer** [comment]
Failing tests

**Comment by MorrisJobke** [comment]
Tested with nextcloud/activity#79 and works 👍 

Only the failing tests needs to be fixed.

**Comment by nickvergessen** [comment]
Fixed missing contact names and tests

**Comment by MorrisJobke** [comment]
I get this when opening the activities page:

```
{"reqId":"52RqvQeK5xnQtbMBNk96","remoteAddr":"::1","app":"PHP","message":"Undefined offset: 2 at \/Users\/morrisjobke\/Projects\/nextcloud\/server\/apps\/sharebymail\/lib\/Activity.php#176","level":0,"time":"2016-11-25T10:38:46+00:00","method":"GET","url":"\/server\/index.php\/apps\/activity\/api\/v2\/activity\/all?format=json&previews=true&since=0","user":"admin","version":"11.0.0.2"}
```

**Comment by nickvergessen** [comment]
Fixed

**Comment by MorrisJobke** [comment]
Works 👍

**Comment by schiessle** [comment]
tested... works :+1:

**Pull request merged**
