### PR TITLE
Fix input field for new folder 

### LINKED ISSUE #2245: Folder name input cut off
Try to create a folder using the web UI

@jancborchardt @nextcloud/designers 

> bildschirmfoto vom 2016-11-22 16-32-23

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #2245

cc @nickvergessen @rullzer @nextcloud/designers @skjnldsv @juliushaertl

### CODE REVIEW

**Comment by jancborchardt** [comment]
:+1: nice work.

I also added a commit to fix the vertical expansion of the popover because the input element was higher than the text.

**Comment by MorrisJobke** [comment]
Nice @jancborchardt 👍

**Comment by nickvergessen** [comment]
Works, should we make the dropdown a bit bigger?
Not even the default file name displayes fully, and we have enough space there:
files_-_nextcloud_-_2016-12-02_14 17 33

**Comment by MorrisJobke** [comment]
> Not even the default file name displayes fully, and we have enough space there:

Let me add this quickly.

**Comment by MorrisJobke** [comment]
@nickvergessen Please retest

**Comment by nickvergessen** [comment]
much better 👍

**Pull request merged**
