### PR TITLE
Add unified search options

### PR DESCRIPTION
**Pull request by juliusknorr**
- Change debounce timeout to 500ms to trigger search less often when typing slowly
- Allow to set custom value for minimum character limit
- Allow to set custom value for number of results
- Add option to disable type ahead functionality and only trigger search on enter/click on the submit button

https://user-images.githubusercontent.com/3404133/146520039-b6df9beb-f936-45b3-b5ba-357e9b936a8d.mp4

```
occ config:app:set core unified-search.live-search --value=no
occ config:app:set core unified-search.min-search-length --value=4
```

### CODE REVIEW

**Review by artonge — COMMENTED** [review]
Would rename `typeAhead` to something more explicit, like `enableLiveSearch`. But else, looks fine :).

**Review by PVince81 — APPROVED** [review]
:+1: code looks fine

I agree with @artonge that "type-ahead" sounds more confusing than "live search"

**Comment by juliushaertl** [comment]
Sure, I'll adjust to live search, thanks for the suggestion.

**Review by CarlSchwan — APPROVED** [review]
Code looks good!

**Review by skjnldsv — CHANGES_REQUESTED** [review]
`minSearchLength` is not used? What is it being used for?

**Review by jancborchardt — APPROVED** [review]
Looks good design-wise when the settings are customized. :) Also ok on upping the debounce timeout.

**Comment by juliushaertl** [comment]
> minSearchLength is not used? What is it being used for?

It is used in the code already for letting the search only start after a certain amount of characters, just that it was made an option now to configure.

**Comment by juliushaertl** [comment]
Rebased to latest master

**Comment by szaimen** [comment]
@juliushaertl what is missing here? :)

**Comment by juliushaertl** [comment]
Just another rebase, pushed and waiting for CI.

**Comment by szaimen** [comment]
acceptance-access-levels is failing. Not sure if related though

**Comment by juliushaertl** [comment]
Doesn't seem so, but restarted that drone run.

**Comment by szaimen** [comment]
Seems to pass now..

**Comment by juliushaertl** [comment]
Let's get that in then :)

**Comment by PVince81** [comment]
@juliushaertl maybe we should backport this also ?

at least for the increased debounce

**Comment by juliushaertl** [comment]
Will do them manually

**Pull request merged**
