### PR TITLE
Allow to get activities for files by email again

### PR DESCRIPTION
**Pull request by nickvergessen**
Regression from #22205

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
🐘

**Comment by NextClaus** [comment]
Hello guys,

What is the current status of this issue? We are missing the e-mail notification feature a lot and want to have it back.
I still don't understand why it has been removed at all in [22205](https://github.com/nextcloud/server/pull/22205)... . Please help us to get it back.

Our users want to have e-mail notifications if someone else changed/uploaded/removed a file/folder.

**Comment by nickvergessen** [comment]
That is still possible and works as it always did.

What was removed was a setting for "only email/push for favorited folders". This was never working and can therefor not be missed

**Comment by NextClaus** [comment]
No, it does not work for me and others:
https://help.nextcloud.com/t/no-activity-notifications/115225/13
https://help.nextcloud.com/t/test-mail-works-mail-notifications-dont-work/125450/13

The test email works, but regular notifications don't get sent since upgradeing to v21 (we skipped v20).

**Comment by NextClaus** [comment]
Although we are using a completely different setup and version in the meantime, we struggled to get email notifications upon folder/file changes. The reason/solution is that "Group folders" app is behaving differently than normal shares:

https://help.nextcloud.com/t/test-mail-works-mail-notifications-dont-work/125450/32?u=nextclaus

**Pull request merged**
