### PR TITLE
fix: only keep major as server version

### PR DESCRIPTION
**Pull request by skjnldsv**
For the releases, will lower the amount of times we need to compile during releases, this is often more cumbersome than necessary

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Should work, problem here is we do not do semantic versioning here, but currently this should not break anything.

**Review by blizzz — APPROVED** [review]

**Comment by skjnldsv** [comment]
> /compile rebase /

For some reason Github is not showing me merged PR...

**Pull request merged**
