### PR TITLE
try to fix regression with public file upload button

### PR DESCRIPTION
**Pull request by szaimen**
On public link shares where files are editable, there the add button is broken after https://github.com/nextcloud/server/pull/39884. Fix this:

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Comment by szaimen** [comment]
btw @susnux the file/folder picker does not seem to work on public link shares currently...

**Comment by susnux** [comment]
@szaimen 
> the file/folder picker does not seem to work on public link shares currently... Or is it not merged yet?

Not merged for master currently.

**Review by susnux — APPROVED** [review]

**Comment by szaimen** [comment]
> @szaimen
> 
> > the file/folder picker does not seem to work on public link shares currently... Or is it not merged yet?
> 
> Not merged for master currently.

all right 👍

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/pull/39921

**Comment by nickvergessen** [comment]
@susnux @szaimen 

If there is compiled JS backporting mostly never works.

You can help yourself by having the compiling in another commit, by using `/compile /` (without the amend) and then only requesting the backport bot to backport the source code change only `/backport <commit sha> to stable27`. After the backport is done, you do `/compile /` there again.

**Comment by susnux** [comment]
@nickvergessen the last of my requests did not contain any compiled assets but still failed.

**Comment by nickvergessen** [comment]
Yeah sorry, it contains compiled CSS not JS. but same problem. all the scss files are reduced to a single line. so conflicts are just going to happen.
But also for compiled CSS the mentioned "trick" works.

**Pull request merged**
