### PR TITLE
Fix contrast of global search headings

### PR DESCRIPTION
**Pull request by Pytal**
### WCAG AA

> “WCAG 2.0 level AA requires a contrast ratio of at least . . . 3:1 for large text.” ([Source](https://webaim.org/resources/contrastchecker/))

> “Large text is defined as 14 point (typically 18.66px) and bold or larger, or 18 point (typically 24px) or larger.” ([Source](https://webaim.org/resources/contrastchecker/))

### Dark mode

Before (18px, normal) | After (19px, bold)
--- | ---
image | image

<details>
<summary>Contrast ratio</summary>

image

</details>

### Light mode
Before (18px, normal) | After (19px, bold)
--- | ---
image | image

<details>
<summary>Contrast ratio</summary>

image

</details>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by jancborchardt** [comment]
Shouldn’t we adjust color-primary-element to be lighter in dark mode? Cause where do we use it anyway, if as text color it doesn’t work?

**Comment by Pytal** [comment]
> Shouldn’t we adjust color-primary-element to be lighter in dark mode? Cause where do we use it anyway, if as text color it doesn’t work?

It's used by primary buttons
image

With the recent switch from `#0082c9` to `#00639a` if we switch to a lighter color `#0088d1` (lighter than `#0082c9`) to meet contrast requirements for text on dark backgrounds then we would simultaneously no longer meet contrast requirements for the primary button

Any suggestions @jancborchardt?

**Comment by Pytal** [comment]
Using `--color-text-maxcontrast` work for you @nimishavijay?

**Comment by nimishavijay** [comment]
If the field is focused it should be `--color-primary-element`. If it's not focused then it can be `--color-text-maxcontrast` :)
Regarding what @jancborchardt was mentioning, I think he meant that since there is a darker variant of the primary color for light mode, there could similarly be a lighter variant for dark mode. So that would be 2 variants of `--color-primary-element` one for light mode, one for dark mode. Would that make sense?

**Comment by Pytal** [comment]
> If the field is focused it should be `--color-primary-element`. If it's not focused then it can be `--color-text-maxcontrast` :) Regarding what @jancborchardt was mentioning, I think he meant that since there is a darker variant of the primary color for light mode, there could similarly be a lighter variant for dark mode. So that would be 2 variants of `--color-primary-element` one for light mode, one for dark mode. Would that make sense?

With the recent switch from `#00639a` → `#006aa3` we could instead keep the primary color and meet heading contrast requirements by increasing the font size to 19px and bolding 

image
image

Soung good @nimishavijay?

**Comment by Pytal** [comment]
> Alright that sounds good :)

Code + screenshots updated :)

**Review by artonge — APPROVED** [review]

**Review by nimishavijay — APPROVED** [review]

**Pull request merged**
