### PR TITLE
Switch to 1 share api integration test

### PR DESCRIPTION
**Pull request by rullzer**
This was split at some point because it was to slow. It seems to run
fine now. So better save jobs and combine them.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
> acceptance-app-files-sharing: Cancelled

Took too long?

**Comment by rullzer** [comment]
Old drone job I think. But it fails now for some reason.
https://drone.nextcloud.com/nextcloud/server/22325/41/3

@danxuliu any clue why?

**Comment by danxuliu** [comment]
> But it fails now for some reason.
> any clue why?

[The old _sharing-v1-part3.feature_ used the new DAV path](https://github.com/nextcloud/server/blob/f663154adfb81848295bbb6ddcc7ac9582c3a475/build/integration/sharing_features/sharing-v1-part3.feature#L4), but its tests were added to _sharing-v1.feature_ [which uses the old DAV path](https://github.com/nextcloud/server/blob/6d4f4c1c700ca6fb017f01c5272d48db74221f86/build/integration/sharing_features/sharing-v1.feature#L4). It seems that although most of the tests work with both paths some of them only work with the new path.

**Comment by rullzer** [comment]
Ok then we need to take a proper look later to fix it all thnx.

**Pull request closed without merging**
