### PR TITLE
Sharebymail: set expiration on creation

### PR DESCRIPTION
**Pull request by rullzer**
@tobiasKaminsky now sure if this is used by clients at all? But they can now.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: code makes sense.

I see that in update it's already stored.
Guess the frontend probably doesn't use this either.

**Comment by rullzer** [comment]
> Guess the frontend probably doesn't use this either.

Nah you first create it and then set it.
Never the less still good to be consistent.

**Review by ChristophWurst — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky now sure if this is used by clients at all? But they can now.

Workflow on all clients is to first share via mail and then add those options (expiration date, password, etc.) in a second step.
And this already worked.

But thanks, once/if we change the workflow, we can use this!

**Pull request merged**
