### PR TITLE
Allow OCS resources as well

### PR DESCRIPTION
**Pull request by nickvergessen**
Better to look at the commits one by one

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Awesome! Code looks good! I guess we should also add this to the dev manual.

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by MorrisJobke** [comment]
PHPUnit fails :/

**Comment by rullzer** [comment]
rebase and autosquash time!

**Pull request merged**
