### PR TITLE
Fix missing text for downloads on mobile

### LINKED ISSUE #2362: Dropdown on mobile missing text next to icons
### Steps to reproduce
1. Create a public shared folder
2. Open link on mobile
3. Open the "..." menu

### Expected behaviour
`⬇️ Download`

### Actual behaviour
`⬇️ `

bildschirmfoto vom 2016-11-28 09-56-09

Happens on both, 10 and 11 beta/master.

@jancborchardt @nextcloud/designers

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #2362

cc @nextcloud/designers @nickvergessen

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I tested this and it works 👍

**Comment by MorrisJobke** [comment]
cc @eppfel

**Comment by skjnldsv** [comment]
> I tested this and it works 👍

Cheater! You can't review your own PR! 😆

**Comment by skjnldsv** [comment]
👍

**Comment by MorrisJobke** [comment]
> Cheater! You can't review your own PR! 😆

It was not really mine ;) https://github.com/nextcloud/server/issues/2362#issuecomment-263324618

**Comment by LukasReschke** [comment]
LGTM

**Comment by skjnldsv** [comment]
Like I said to rullzer, the .action class is causing a lot of issues on the Files app. It's used everywhere and has far too many properties :/

We should really clean things up one day :)

**Pull request merged**
