### PR TITLE
Move CONTRIBUTUNG and issue template into .github subfolder

### PR DESCRIPTION
**Pull request by MariusBluem**
Do we want to do this? 😁 

cc @MorrisJobke @nickvergessen @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
hmm. what exactly would be the benefit? :-)

**Comment by nickvergessen** [comment]
Well those files are not “found“, but github creates magic links to them. It knows both locations.

**Comment by MariusBluem** [comment]
I think the / directory should be as clean as possible, and upstream has done this too :grin:

**Comment by LukasReschke** [comment]
LGTM

**Comment by nickvergessen** [comment]
👍

**Pull request merged**
