### PR TITLE
fix several admin settings problems

### PR DESCRIPTION
**Pull request by szaimen**
Address part of https://github.com/nextcloud/server/issues/36965

This is best reviewed like this: https://github.com/nextcloud/server/pull/40887/files?w=1

| Before | After |
|---|---|
| image | image |
| image | image |
| image | image |

### CODE REVIEW

**Review by JuliaKirschenheuter — APPROVED** [review]
works, thank you!

**Review by ShGKme — CHANGES_REQUESTED** [review]
It broke the position of the "i" icon for me:

image

Including desktop layout

before | after
---|---
image | image

**Comment by szaimen** [comment]
@ShGKme I cannot reproduce your problem. See my screen recording:

https://github.com/nextcloud/server/assets/42591237/2eefae99-38c9-4444-9ebc-a2c156ef6502

**Comment by ShGKme** [comment]
Same other issues with default apps

Basic settings | Sharing (small issue with checkbox)
---|---
image | image

**Comment by szaimen** [comment]
> Same other issues with default apps

@ShGKme did you compile the scss? It needs to be compiled first (is currently not commitwd to this branch)

**Review by ShGKme — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
