### PR TITLE
Fix upload via shared link

### LINKED ISSUE #14986: Upload via shared link fails on nextcloud 16.0.0RC2
### Steps to reproduce
1. create a folder in nextcloud
2. share this folder via public link (select allow editing)
3. on the public link, try to upload a new file

### Expected behaviour
The file should be imported in nextcloud

### Actual behaviour
nothing happens. There is an error in the JS console and a ressource not found error in nextcloud logs (see below)

### Server configuration

**Operating system**:
ubuntu 18.04

**Web server:**
apache 2.4

**Database:**
mysql 8

**PHP version:**
php7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.0 beta3
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.0
  - admin_audit: 1.6.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.0.5
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/drive.pandore2015.fr",
        "dbtype": "mysql",
        "version": "16.0.0.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_scale_factor": 1,
        "theme": "",
        "updater.release.channel": "beta",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "htaccess.RewriteBase": "\/",
        "loglevel": "1",
        "dbport": "",
        "installed": true,
        "mail_smtpauthtype": "LOGIN",
        "log_type": "owncloud",
        "logfile": "\/home\/data\/nextcloud.log",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "audioplayer",
            "calendar",
            "files_markdown",
            "occweb",
            "sharerenamer"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 67.0b6
**Operating system:**
Windows10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"vajcfDSVNMYw221dE912","level":3,"time":"2019-04-08T09:16:33+00:00","remoteAddr":"83.202.81.194","user":"--","app":"jsresourceloader","method":"GET","url":"\/s\/4SgkqPMxniTqGFa","message":"Could not find resource core\/vendor\/marked\/marked.min.js to load","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.0.5"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). 4SgkqPMxniTqGFa:1:1
La ressource à l’adresse « https://REDACTED/apps/files/ » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
4SgkqPMxniTqGFa
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:531
The escapeHTML library is deprecated! It will be removed in nextcloud 19.
main.js:750:58
The humanFileSize library is deprecated! It will be removed in nextcloud 19. main.js:750:58
Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : https://REDACTED/core/js/dist/share_backend.js?v=a022c0f6-2
URL du lien source : share_backend.js.map

Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : https://REDACTED/core/js/dist/main.js?v=a022c0f6-2
URL du lien source : main.js.map

Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : https://REDACTED/apps/files_videoplayer/js/main.js?v=a022c0f6-2
URL du lien source : main.js.map

TypeError: OCA.Files.Semaphore is not a constructorfile-upload.js:564:19
    submitUploads https://REDACTED/apps/files/js/file-upload.js?v=a022c0f6-2:564
    onNoConflicts https://REDACTED/apps/files/js/file-upload.js?v=a022c0f6-2:992
    checkExistingFiles https://REDACTED/apps/files/js/file-upload.js?v=a022c0f6-2:777
    add https://REDACTED/apps/files/js/file-upload.js?v=a022c0f6-2:1010
    _trigger https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:290
    _onAdd jQuery
    each https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:28
    _onAdd jQuery
    i/e.widget/</a[t]</< https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:290
    _onChange jQuery
    u https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
    add https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
    always https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
    _onChange jQuery
    i/e.widget/</a[t]</< https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:290
    a https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:290
    dispatch https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
    handle https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
```
</details>

### PR DESCRIPTION
**Pull request by rmanibus**
Fix #14986

### CODE REVIEW

**Comment by rmanibus** [comment]
After a closer look at the code it seems that this should only be included if it's a folder. I will update the PR

**Comment by rmanibus** [comment]
it seems that file_sharing scripts
```
			\OCP\Util::addScript('files_sharing', 'public');
			\OCP\Util::addScript('files_sharing', 'templates');
			\OCP\Util::addScript('files_sharing', 'files_drop');
```
need to be included before files app scripts for the folder view and after the files app scripts for the single file view.

**Comment by rmanibus** [comment]
There is still an problem on new folder creation. The folder is correctly created but the in the js console there is the following error: 
```
TypeError: this._detailsView is null
```
This error is also existing without this fix.

**Comment by enoch85** [comment]
@rullzer I'm not 100% sure here, but [his fix](https://github.com/nextcloud/server/issues/14986#issuecomment-484451455) solved the issue for me at least.

Maybe we can add this in 16.0.1? Public shares are currently broken without this.

**Comment by violoncelloCH** [comment]
this was fixed in the meantime by #15432 so I guess we can close this? cc @MorrisJobke

**Comment by enoch85** [comment]
Thanks for your efforts @rmanibus!

**Comment by MorrisJobke** [comment]
This is still there.

@nextcloud/javascript Does it still make sense to go for this approach?

**Pull request closed without merging**
