### PR TITLE
Make sure we use the correct storage id and parent id when scanning a jailed storage

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
How to test this?

**Comment by icewind1991** [comment]
I ran into the problem while testing [wip migration](https://github.com/icewind1991/migration) but I can't seem to reproduce the exact circumstances that trigger the bug with a seperate testcase

**Review by MorrisJobke — APPROVED** [review]
fiels scan didn't explode and code looks good 👍

**Review by rullzer — APPROVED** [review]
Makes sense. And my test instance did not explode. :+1:

**Pull request merged**
