### PR TITLE
Make sure the AppFetcher fetches the new applist from the appstore

### PR DESCRIPTION
**Pull request by rullzer**
When in the upgrade process the version in the config is still the old
version. (Since we only upgrade it after the upgrade is complete).
However the app list fetched from the appstore must be the new list.

Fixes https://github.com/nextcloud/server/issues/4642

To test:

1. Install stable11
2. Upgrade to master
3. Error about not being able to install core bundle

Now:
1. Install stable11
2. Checkout this branch
3. :rocket: :guitar: :drum: :beer:

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]
Makes sense

**Review by MorrisJobke — APPROVED** [review]
Tested and works

**Comment by devurandom** [comment]
I think I just ran into this issue with 12.0.3:
```
su -c "php7.1 $PWD/occ upgrade" -s /bin/bash - lighttpd
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug                                          
Turned on maintenance mode                             
Updating database schema                                        
Updated database                                              
Updating <federatedfilesharing> ...                           
Updated <federatedfilesharing> to 1.2.0                      
Updating <files_pdfviewer> ...                                
Updated <files_pdfviewer> to 1.1.1                          
Updating <files_texteditor> ...                               
Updated <files_texteditor> to 2.4.1                       
Updating <files_videoplayer> ...                           
Updated <files_videoplayer> to 1.1.0                           
Updating <gallery> ...                                              
Updated <gallery> to 17.0.0                                                                                                                          
Updating <password_policy> ...                        
Updated <password_policy> to 1.2.2               
Updating <provisioning_api> ...                    
Updated <provisioning_api> to 1.2.0            
Updating <serverinfo> ...                        
Updated <serverinfo> to 1.2.0                        
Updating <survey_client> ...                            
Updated <survey_client> to 1.0.0                                 
Updating <twofactor_backupcodes> ...                                                                                                                 
Copy twofactor backup codes from legacy table               
                                                              
 Done                                                
    0/0 [>---------------------------]   0%            
Updated <twofactor_backupcodes> to 1.1.1                   
Updating <updatenotification> ...                            
Updated <updatenotification> to 1.2.0            
Updating <federation> ...                          
Updated <federation> to 1.2.0                                                     
Updating <user_ldap> ...                               
Updated <user_ldap> to 1.2.1                                                                
Updating <files> ...                                    
Updated <files> to 1.7.2                                
Updating <activity> ...                                 
Updated <activity> to 2.5.2                         
Updating <dav> ...                                         
Fix broken values of calendar objects                                 
 Done                                                                                                                     
    0/0 [>---------------------------]   0%          
Updated <dav> to 1.3.0                                 
Updating <encryption> ...                                   
Updated <encryption> to 1.6.0                           
Updating <files_sharing> ...                               
Updated <files_sharing> to 1.4.0                          
Updating <files_trashbin> ...                                               
Updated <files_trashbin> to 1.2.0                       
Updating <files_versions> ...                                   
Updated <files_versions> to 1.5.0                       
Updating <sharebymail> ...                                              
Updated <sharebymail> to 1.2.0
Updating <workflowengine> ...                                 
Updated <workflowengine> to 1.2.0                               
Updating <comments> ...                                       
Updated <comments> to 1.2.0                                     
Updating <firstrunwizard> ...                          
Updated <firstrunwizard> to 2.1                                 
Updating <nextcloud_announcements> ...                        
Updated <nextcloud_announcements> to 1.1                      
Updating <notifications> ...                                 
Updated <notifications> to 2.0.0                              
Updating <systemtags> ...                                   
Updated <systemtags> to 1.2.0                                 
Updating <theming> ...                                    
Updated <theming> to 1.3.0                                 
Checking for update of app activity in appstore                
Checked for update of app "activity" in appstore                    
Checking for update of app audioplayer in appstore                                                                                                   
Checked for update of app "audioplayer" in appstore   
Checking for update of app bookmarks in appstore 
Checked for update of app "bookmarks" in appstore  
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore 
Checking for update of app comments in appstore      
Checked for update of app "comments" in appstore        
Checking for update of app contacts in appstore                  
Checked for update of app "contacts" in appstore                                                                                                     
Checking for update of app dav in appstore                  
Checked for update of app "dav" in appstore                   
Checking for update of app encryption in appstore    
Checked for update of app "encryption" in appstore     
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore 
Checking for update of app files in appstore                                      
Checked for update of app "files" in appstore          
Checking for update of app files_pdfviewer in appstore                                      
Checked for update of app "files_pdfviewer" in appstore 
Checking for update of app files_retention in appstore  
Checked for update of app "files_retention" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore      
Checking for update of app files_texteditor in appstore               
Checked for update of app "files_texteditor" in appstore                                                                  
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore       
Checked for update of app "files_versions" in appstore  
Checking for update of app files_videoplayer in appstore   
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app firstrunwizard in appstore                       
Checked for update of app "firstrunwizard" in appstore  
Checking for update of app gallery in appstore                  
Checked for update of app "gallery" in appstore         
Checking for update of app logreader in appstore                        
Checked for update of app "logreader" in appstore
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app notifications in appstore   
Checked for update of app "notifications" in appstore           
Checking for update of app oauth2 in appstore                 
Checked for update of app "oauth2" in appstore                
Checking for update of app password_policy in appstore       
Checked for update of app "password_policy" in appstore       
Checking for update of app provisioning_api in appstore     
Checked for update of app "provisioning_api" in appstore      
Checking for update of app serverinfo in appstore         
Checked for update of app "serverinfo" in appstore         
Checking for update of app sharebymail in appstore             
Checked for update of app "sharebymail" in appstore                 
Checking for update of app survey_client in appstore                                                                                                 
Checked for update of app "survey_client" in appstore 
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore 
Checking for update of app tasks in appstore
Checked for update of app "tasks" in appstore 
Checking for update of app templateeditor in appstore
Checked for update of app "templateeditor" in appstore  
Checking for update of app theming in appstore                   
Checked for update of app "theming" in appstore                                                                                                      
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app twofactor_totp in appstore
Checked for update of app "twofactor_totp" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app user_ldap in appstore
Checked for update of app "user_ldap" in appstore 
Checking for update of app workflowengine in appstore                             
Checked for update of app "workflowengine" in appstore 
Repair warning: Could not install core app bundle: Could not download app bruteforcesettings
Starting code integrity check...                 
Finished code integrity check                           
Update successful                        
Turned off maintenance mode                
Reset log level
```

I come here from: https://help.nextcloud.com/t/upgrade-to-nc-12-beta-1-problems/12225/4

**Comment by ChristophWurst** [comment]
@devurandom if you've encountered a problem, please file a new issue. Thanks.

**Pull request merged**
