### PR TITLE
fix for issue #11281

### PR DESCRIPTION
**Pull request by cwiedmann**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@cwiedmann Could we ask you to create the same PR to master as well. Usually we work like this:

* work on a fix in a branch against master
* then decide whether we want to backport this (if it is possible at all)
* then do the backport PR

Let's keep this one open here for now and work do the same against master and merge it first. :)

**Comment by MorrisJobke** [comment]
Any news on this one here?

**Comment by MorrisJobke** [comment]
@cwiedmann Could you include the change of @danielkesselberg? Then this is good to go in :)

**Comment by danielkesselberg** [comment]
@cwiedmann let me know if you dont have time :ping_pong:

**Comment by MorrisJobke** [comment]
@danielkesselberg fixed the comments from this one and opened #12424. Let's close this one here then.

**Pull request closed without merging**
