### PR TITLE
fix(build): Allow update-apps.sh script to work with non-master branches

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

The script only worked for apps which use master as their main branch.
This change also makes the script easier to read and also catch errors properly.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by sorbaugh — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by come-nc** [comment]
Fails with sh:
```
$ sh build/update-apps.sh
build/update-apps.sh: 18: set: Illegal option -o pipefail
```
Fails with french locale:
```
$ bash build/update-apps.sh

activity
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```
(because `git remote show origin` does not contain `HEAD branch` but a french translation)

**Comment by provokateurin** [comment]
For the later we could do a stupid `git checkout master || git checkout main`. If both fail then the whole script will fail as expected.

**Comment by susnux** [comment]
> Ugh I didn't know and think about that. Not sure how to make that work. I tried a few alternatives, but none of them worked for me at all.

I think in that script just `export LANG=C` in the beginning should be enough (and should not conflict as long as you do not source it)

**Comment by provokateurin** [comment]
@come-nc can you try that and if it works make a PR?

**Comment by provokateurin** [comment]
> and should not conflict as long as you do not source it

Instead of using export the env variable could just be applied to the git command that is problematic.

**Comment by susnux** [comment]
> Instead of using export the env variable could just be applied to the git command that is problematic.

Sure this also works :)
I just export to have a consistent scripting env. The env is not leaking into your personal shell session (as long as you do not source it, but why should you? :sweat_smile: )

**Comment by provokateurin** [comment]
Yeah it would be weird to do that, but you mentioned it so we can also just prevent it :D

**Pull request merged**
