### PR TITLE
Properly cleanup entries of WebAuthn on user deletion

### PR DESCRIPTION
**Pull request by MorrisJobke**
Add listener on user deletion to clean up the webauthn table.

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]
🥳

**Review by ChristophWurst — APPROVED** [review]
Beautiful

**Comment by MorrisJobke** [comment]
Code style fixed ✅

**Comment by LukasReschke** [comment]
Manual backport at https://github.com/nextcloud/server/pull/27596

**Pull request merged**
