### PR TITLE
Admin user settings - change Everyone to Active users

### LINKED ISSUE #27206: App settings/users: "Everyone" is not everyone
List of users: The naming or counting for the categories on the left side could be improved.

* "Everyone": The wording is wrong. "Everyone" just shows enabled users, including the Admin. So it should be renamed to "Enabled + Admin" (or should count disabled users, too).
* "Admin" is included in "Everyone", so it could be indented.
* "Disabled": if "Everyone" would count disabled users, this should be indented.

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/27206
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
Hm, not sure why `Node / build (12.x)` is still failing... @skjnldsv any hint?

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
The compile bot doesn't clean up old files that got removed:

```
Uncommited changes in webpack build
HEAD detached at pull/27842/merge
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    apps/settings/js/vue-settings-users-8a973f1b2b78e43a05ac.js
	deleted:    apps/settings/js/vue-settings-users-8a973f1b2b78e43a05ac.js.map
```

**Comment by szaimen** [comment]
> The compile bot doesn't clean up old files that got removed:

So how do I fix this?

**Comment by juliushaertl** [comment]
> Thanks! So how do I fix this?

You can checkout the branch with the commited changes from the bot and run:

```
git rm apps/settings/js/vue-settings-users-8a973f1b2b78e43a05ac.js{,.map}
git commit --amend
```

**Review by artonge — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks! Fixed it :)

**Comment by artonge** [comment]
> Thanks! Fixed it :)

You can usually run `make clean` to make sure old files are removed

**Pull request merged**
