### PR TITLE
Fix default internal expiration date

### PR DESCRIPTION
**Pull request by danxuliu**
Follow up to #17725

The default expiration date for internal shares was set from the default link expiration date instead of the internal one.

The fix itself is in the fourth to last commit. The commits before that are fixes to the unit tests of `validateExpirationDate`, and the commits after that are unit and integration tests for the internal expiration date.

## How to test

- Open the settings
- Open the "Sharing" section in "Administration"
- Enable "Set default expiration date for shares" and set "Expire after" to 4
- Open the Files app
- Open the sidebar for a file
- Open the "Sharing" tab
- Share the file with another user
- Open the menu for the share

### Result with this pull request

The expiration date is set in four days.

### Result without this pull request

The expiration date is set in seven days.

### CODE REVIEW

**Comment by danxuliu** [comment]
Mmm, [`shareApiInternalDefaultExpireDays` returns an int](https://github.com/nextcloud/server/blob/de7026f6e4662ff42e0a3c12021a3cee25c5d91f/lib/private/Share20/Manager.php#L1783), but `getAppValue` expects and string so [now](https://github.com/nextcloud/server/pull/24069/commits/a884daeb6ef7d1c63ee6100f4c6108427ea88d41#diff-6c825986578290fe355bffe05c5232629a36e554d48f5d889bb2c1ec73645265R411) psalm [complains](https://github.com/nextcloud/server/runs/1390053642).

What would be the best approach? Just cast to a string? Tell psalm to ignore the mismatch? Something else? Thanks :-)

**Comment by rullzer** [comment]
> Mmm, [`shareApiInternalDefaultExpireDays` returns an int](https://github.com/nextcloud/server/blob/de7026f6e4662ff42e0a3c12021a3cee25c5d91f/lib/private/Share20/Manager.php#L1783), but `getAppValue` expects a string so [now](https://github.com/nextcloud/server/pull/24069/commits/a884daeb6ef7d1c63ee6100f4c6108427ea88d41#diff-6c825986578290fe355bffe05c5232629a36e554d48f5d889bb2c1ec73645265R411) psalm [complains](https://github.com/nextcloud/server/runs/1390053642).
> 
> What would be the best approach? Just cast to a string? Tell psalm to ignore the mismatch? Something else? Thanks :-)

probably cast yes

**Comment by danxuliu** [comment]
Fixed up, ready for review :-)

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
