### PR TITLE
Allow downgrades of maintenance accross vendors

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @schiessle @karlitschek 

As discussed earlier, this is the solution I would go with. If @DeepDiver1975 confirms on the implementation I will create the PR on OC as well.

### CODE REVIEW

**Comment by mar1u5** [comment]
> ... I will create the PR on OC as well.

What is the intention behind that? @nickvergessen

**Comment by nickvergessen** [comment]
> What is the intention behind that? @nickvergessen

The idea is to prevent a version number raise to avoid confusion on the user side, while allowing people to switch back and forth on the same major level.

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I fear that this will cause more issues when both implementation differentiate more and more in the future 🙈

**Comment by nickvergessen** [comment]
> I fear that this will cause more issues when both implementation differentiate more and more in the future :see_no_evil:

Yes, but for 9 and 10/9.1 this shouldn't be a problem.

**Comment by nickvergessen** [comment]
Also no one said, that this is going to work forever :wink:

**Comment by LukasReschke** [comment]
🙈 🙊 🙉 

👍

**Pull request merged**
