### PR TITLE
Added cache override to ensure an always up-to-date accessibility css

### LINKED ISSUE #10960: Nextcloud 14 theming quite broken in RC2 due to caching
### Steps to reproduce
1. Enable high contrast theme
2. load Files - all good
3. go back and enable dark theme
4. load Files - it is back to high contrast theme

### Expected behaviour
The Dark theme should show.

Doing the opposite also works:
1. Enable dark theme
2. load Files - all good
3. go back and enable another
4. load Files - it is back to Dark theme
5. Go to accessibility settings and you can easily get this:
screenshot_20180901_135918

Here's a video of me trying to desperately make it work:

broken

### Actual behaviour
Dark theme doesn't show, a previously selected theme shows.

### Server configuration
**Operating system**:
openSUSE
**Web server:**
Apache
**Database:**
sqlite
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14RC2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from beta and earlier from fresh 13

**Where did you install Nextcloud from:**
zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
The current PHP memory limit is below the recommended value of 512MB.
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - admin_notifications: 1.0.2
  - announcementcenter: 3.3.0
  - calendar: 1.6.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_automatedtagging: 1.4.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.1
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 3.99.12
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - dashboard
  - encryption
  - files_rightclick
  - initialcheck
  - keeporsweep
  - terms_of_service
  - unsplash
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "14.0.0.18",
        "overwrite.cli.url": "http:\/\/127.0.0.1\/nextcloud",
        "installed": true,
        "updater.release.channel": "beta",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

### Client configuration
**Browser:**
chromium
**Operating system:**
openSUSE
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Sat Sep 01 13:57:30.735312 2018] [authz_core:error] [pid 18208] [client 127.0.0.1:43382] AH01630: client denied by server configuration: /home/jospoortvliet/server/nextcloud/data/.ocdata
[Sat Sep 01 13:57:33.029767 2018] [authz_core:error] [pid 17863] [client 127.0.0.1:43434] AH01630: client denied by server configuration: /home/jospoortvliet/server/nextcloud/data/.ocdata
[Sat Sep 01 13:57:39.563578 2018] [authz_core:error] [pid 19878] [client 127.0.0.1:43390] AH01630: client denied by server configuration: /home/jospoortvliet/server/nextcloud/data/.ocdata
[Sat Sep 01 13:57:48.305213 2018] [authz_core:error] [pid 19794] [client 127.0.0.1:43388] AH01630: client denied by server configuration: /home/jospoortvliet/server/nextcloud/data/.ocdata
[Sat Sep 01 13:57:50.039263 2018] [authz_core:error] [pid 13442] [client 127.0.0.1:43384] AH01630: client denied by server configuration: /home/jospoortvliet/server/nextcloud/data/.ocdata
[Sun Sep 02 10:47:50.793813 2018] [authz_core:error] [pid 11223] [client 127.0.0.1:41548] AH01630: client denied by server configuration: /home/jospoortvliet/server/nextcloud/data/.ocdata
[Sun Sep 02 10:47:57.246228 2018] [authz_core:error] [pid 12653] [client 127.0.0.1:41556] AH01630: client denied by server configuration: /home/jospoortvliet/server/nextcloud/data/.ocdata
[Sun Sep 02 10:49:19.564686 2018] [php7:error] [pid 13163] [client 127.0.0.1:41654] script '/home/jospoortvliet/server/index.php' not found or unable to stat, referer: http://127.0.0.1/nextcloud/index.php/settings/integrity/failed
[Sun Sep 02 10:49:19.589933 2018] [php7:error] [pid 13163] [client 127.0.0.1:41654] script '/home/jospoortvliet/server/index.php' not found or unable to stat, referer: http://127.0.0.1/nextcloud/index.php/settings/integrity/failed
[Sun Sep 02 10:49:20.577081 2018] [php7:error] [pid 13163] [client 127.0.0.1:41654] script '/home/jospoortvliet/server/index.php' not found or unable to stat, referer: http://127.0.0.1/nextcloud/index.php/settings/integrity/failed
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Bey6KAHM1sDhiDdm0fvm","level":3,"time":"2018-07-24T23:08:26+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"core","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":{"Exception":"Exception","Me
ssage":"Could not find category \"_$!<Favorite>!$_\"","Code":0,"Trace":[{"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private\/Tags.php","line":628,"function":"getIdsForTag","class":"OC\\Tags","type":"->","args":["_$!
<Favorite>!$_"]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/lib\/Activity\/Helper.php","line":51,"function":"getFavorites","class":"OC\\Tags","type":"->","args":[]},{"file":"\/home\/jospoortvliet\/server\/n
extcloud\/apps\/files\/lib\/Controller\/ViewController.php","line":163,"function":"getFavoriteFilePaths","class":"OCA\\Files\\Activity\\Helper","type":"->","args":["jos"]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\
/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["","",null,false]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private
\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/home\/j
ospoortvliet\/server\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"ind
ex"]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["ViewController","index",{"__
class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files.view.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"files.view.index"}]},{
"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"files.view.index"}]},{"f
ile":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/"]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/index.php","lin
e":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private\/Tags.php","Line":282,"CustomMessage":"OC\\Tags::getFavorites"},"userAgent":"Mozilla\/5.0 (X11
; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.0.12"}
{"reqId":"Bey6KAHM1sDhiDdm0fvm","level":3,"time":"2018-07-24T23:08:26+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"count(): Parameter must be a
n array or an object that implements Countable at \/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/lib\/Controller\/ViewController.php#169","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Ge
cko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.0.12"}
{"reqId":"Bey6KAHM1sDhiDdm0fvm","level":3,"time":"2018-07-24T23:08:26+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Invalid argument supplied fo
r foreach() at \/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/lib\/Controller\/ViewController.php#177","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/5
37.36","version":"14.0.0.12"}
{"reqId":"Bey6KAHM1sDhiDdm0fvm","level":3,"time":"2018-07-24T23:08:26+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Undefined index: classes at 
\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/templates\/appnavigation.php#67","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.
0.12"}
{"reqId":"Bey6KAHM1sDhiDdm0fvm","level":3,"time":"2018-07-24T23:08:26+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Undefined index: classes at 
\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/templates\/appnavigation.php#67","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.
0.12"}
{"reqId":"Bey6KAHM1sDhiDdm0fvm","level":3,"time":"2018-07-24T23:08:26+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Undefined index: classes at 
\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/templates\/appnavigation.php#67","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.
0.12"}
{"reqId":"Bey6KAHM1sDhiDdm0fvm","level":3,"time":"2018-07-24T23:08:26+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Undefined index: classes at 
\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/templates\/appnavigation.php#67","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.
0.12"}
{"reqId":"M18Cvrc8s2DPwxMq8pl4","level":3,"time":"2018-07-24T23:08:31+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"core","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":{"Exception":"Exception","Me
ssage":"Could not find category \"_$!<Favorite>!$_\"","Code":0,"Trace":[{"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private\/Tags.php","line":628,"function":"getIdsForTag","class":"OC\\Tags","type":"->","args":["_$!
<Favorite>!$_"]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/lib\/Activity\/Helper.php","line":51,"function":"getFavorites","class":"OC\\Tags","type":"->","args":[]},{"file":"\/home\/jospoortvliet\/server\/n
extcloud\/apps\/files\/lib\/Controller\/ViewController.php","line":163,"function":"getFavoriteFilePaths","class":"OCA\\Files\\Activity\\Helper","type":"->","args":["jos"]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\
/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["","",null,false]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private
\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/home\/j
ospoortvliet\/server\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"ind
ex"]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["ViewController","index",{"__
class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files.view.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"files.view.index"}]},{
"file":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"files.view.index"}]},{"f
ile":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/"]},{"file":"\/home\/jospoortvliet\/server\/nextcloud\/index.php","lin
e":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/home\/jospoortvliet\/server\/nextcloud\/lib\/private\/Tags.php","Line":282,"CustomMessage":"OC\\Tags::getFavorites"},"userAgent":"Mozilla\/5.0 (X11
; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.0.12"}
{"reqId":"M18Cvrc8s2DPwxMq8pl4","level":3,"time":"2018-07-24T23:08:31+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"count(): Parameter must be a
n array or an object that implements Countable at \/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/lib\/Controller\/ViewController.php#169","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Ge
cko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.0.12"}
{"reqId":"M18Cvrc8s2DPwxMq8pl4","level":3,"time":"2018-07-24T23:08:31+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Invalid argument supplied fo
r foreach() at \/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/lib\/Controller\/ViewController.php#177","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/5
37.36","version":"14.0.0.12"}
{"reqId":"M18Cvrc8s2DPwxMq8pl4","level":3,"time":"2018-07-24T23:08:31+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Undefined index: classes at 
\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/templates\/appnavigation.php#67","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.
0.12"}
{"reqId":"M18Cvrc8s2DPwxMq8pl4","level":3,"time":"2018-07-24T23:08:31+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Undefined index: classes at 
\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/templates\/appnavigation.php#67","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.
0.12"}
{"reqId":"M18Cvrc8s2DPwxMq8pl4","level":3,"time":"2018-07-24T23:08:31+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Undefined index: classes at 
\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/templates\/appnavigation.php#67","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.
0.12"}
{"reqId":"M18Cvrc8s2DPwxMq8pl4","level":3,"time":"2018-07-24T23:08:31+00:00","remoteAddr":"127.0.0.1","user":"jos","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Undefined index: classes at 
\/home\/jospoortvliet\/server\/nextcloud\/apps\/files\/templates\/appnavigation.php#67","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Nothing
```
</details>

When I enable the devtools in Chrome, the problem goes away - so it is certainly caching related.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #10960

### CODE REVIEW

**Comment by MorrisJobke** [comment]
🏓 for the review 😉

**Comment by skjnldsv** [comment]
Even I forgot about this pr :grin:

**Review by rullzer — APPROVED** [review]
Probably not the most performant way. But we cache agressively. So yeah lets go for it.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by jospoortvliet** [comment]
Great work guys! Several ppl did indeed point it out about 14.0.3 - still has this issue. 15 is fine, though, it isn't something that hits users in day-to-day so much, you pick one theme and stick with it, usually.

**Comment by MorrisJobke** [comment]
@skjnldsv Could you backport it?

**Comment by MorrisJobke** [comment]
> @skjnldsv Could you backport it?

@skjnldsv 🏓

**Comment by skjnldsv** [comment]
backport In https://github.com/nextcloud/server/pull/12432

**Pull request merged**
