### PR TITLE
[stable10] Added integration test (#25675) 

### PR DESCRIPTION
**Pull request by rullzer**
See https://github.com/owncloud/core/pull/25675 and https://github.com/nextcloud/server/pull/1130

CC: @icewind1991 @schiessle @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks good :+1:

**Comment by Mitchou** [comment]
Looks good to me too :+1:

**Comment by MorrisJobke** [comment]
I merged this without travis -> let's see if the stable10 travis run succeeds: https://travis-ci.org/nextcloud/server/builds/156147574

**Comment by MorrisJobke** [comment]
Somehow the hook doesn't triggered any action on travis for this PR before :(

**Comment by MorrisJobke** [comment]
All tests are green :)

**Pull request merged**
