### PR TITLE
Catch node for share not found

### LINKED ISSUE #24891: An error occured while searching files
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Type something in searchbar

### Expected behaviour
List of Files, Decks, Talks etc. containing the searchstring should be listet.

### Actual behaviour
Everything gets listet except the files. An error ist displayed "an error occured while searching files"

### Server configuration

**Operating system:** Linux 3.10.0-1127.8.2.el7.x86_64 x86_64
**Web server:**
**Database:** mysql, 5.5.68 
**PHP version:** 7.4.13
**Nextcloud version:** 20.0.04
**Updated from an older Nextcloud/ownCloud or fresh install:** updated
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

</details>

### Client configuration
**Browser:** Chrome 87 
**Operating system:** Ubuntu 20.04, macOS Catalina

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #24891 

Is this a god time to delete the share if the node doesn't exists?

### CODE REVIEW

**Review by blizzz — COMMENTED** [review]
Not sure it's the right spot to catch it. The manager (or somewhere up the stack) might make more sense to call it? Same with unsharing (provided it is free of side effects – e.g. temporarily unavailable storage, but that SHOULD fail differently).

**Review by nickvergessen — APPROVED** [review]
Reviewed https://github.com/nextcloud/server/pull/26411/files?w=1

**Comment by juliushaertl** [comment]
I'm wondering a bit if in that scenario the cache is actually an instance of a FailedCache so we can just skip the search call in such a case in the view directly before the search is called when iterating over the mounts https://github.com/nextcloud/server/blob/f98fed3f8a11bb71d4c10443b20a59c3864a3617/lib/private/Files/View.php#L1663-L1669

That would be a bit cleaner in my opinion, but hard to tell from the trace if that would work.

**Comment by skjnldsv** [comment]
Fell free to find a better way. This is way out of my current php focus, this was a quickfix for proper catching.

**Comment by PVince81** [comment]
please resolve the conflict, looks like a quick win

**Comment by solracsf** [comment]
Any chance to see this on v25 and backported?

**Comment by skjnldsv** [comment]
Fixed already by https://github.com/nextcloud/server/commit/e198dc1b200f3ade93498e0ea7b468c87d46748a

**Comment by solracsf** [comment]
@skjnldsv this happens in latest v22, isn't that commit included?

```
{
  "reqId": "5nyjmyhZ2oEdxcE8qk6U",
  "level": 3,
  "time": "2022-09-06T12:38:25+00:00",
  "app": "no app in context",
  "method": "POST",
  "url": "/ocs/v2.php/apps/files_sharing/api/v1/shares",
  "message": "Node for share not found, fileid: 61504727",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "version": "22.2.10.0",
  "exception": {
    "Exception": "OCP\\Files\\NotFoundException",
    "Message": "Node for share not found, fileid: 61504727",
    "Code": 0,
    "Trace": [
      {
        "file": "/app/lib/private/Share20/LegacyHooks.php",
        "line": 161,
        "function": "getNode",
        "class": "OC\\Share20\\Share",
        "type": "->",
        "args": []
      },
      {
        "file": "/app/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 264,
        "function": "postShare",
        "class": "OC\\Share20\\LegacyHooks",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\EventDispatcher\\GenericEventWrapper"
          },
          "OCP\\Share::postShare",
          {
            "__class__": "Symfony\\Component\\EventDispatcher\\EventDispatcher"
          }
        ]
      },
      {
        "file": "/app/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 239,
        "function": "doDispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          [
            {
              "__class__": "Closure"
            },
            {
              "__class__": "Closure"
            },
            {
              "__class__": "Closure"
            }
          ],
          "OCP\\Share::postShare",
          {
            "__class__": "OC\\EventDispatcher\\GenericEventWrapper"
          }
        ]
      },
      {
        "file": "/app/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 73,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          [
            {
              "__class__": "Closure"
            },
            {
              "__class__": "Closure"
            },
            {
              "__class__": "Closure"
            }
          ],
          "OCP\\Share::postShare",
          {
            "__class__": "OC\\EventDispatcher\\GenericEventWrapper"
          }
        ]
      },
      {
        "file": "/app/lib/private/EventDispatcher/SymfonyAdapter.php",
        "line": 123,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\EventDispatcher\\GenericEventWrapper"
          },
          "OCP\\Share::postShare"
        ]
      },
      {
        "file": "/app/lib/private/Share20/Manager.php",
        "line": 820,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\SymfonyAdapter",
        "type": "->",
        "args": [
          "OCP\\Share::postShare",
          {
            "__class__": "Symfony\\Component\\EventDispatcher\\GenericEvent"
          }
        ]
      },
      {
        "file": "/app/apps/files_sharing/lib/Controller/ShareAPIController.php",
        "line": 661,
        "function": "createShare",
        "class": "OC\\Share20\\Manager",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Share20\\Share"
          }
        ]
      },
      {
        "file": "/app/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "createShare",
        "class": "OCA\\Files_Sharing\\Controller\\ShareAPIController",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Files\\Node\\Folder"
          },
          31,
          0,
          "jeanmichel.ledoux@alixiomobilite.fr",
          "false",
          "",
          null,
          "",
          ""
        ]
      },
      {
        "file": "/app/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Files_Sharing\\Controller\\ShareAPIController"
          },
          "createShare"
        ]
      },
      {
        "file": "/app/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Files_Sharing\\Controller\\ShareAPIController"
          },
          "createShare"
        ]
      },
      {
        "file": "/app/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Files_Sharing\\Controller\\ShareAPIController",
          "createShare",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "ocs.files_sharing.ShareAPI.createShare"
          }
        ]
      },
      {
        "file": "/app/ocs/v1.php",
        "line": 62,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/ocsapp/apps/files_sharing/api/v1/shares"
        ]
      },
      {
        "file": "/app/ocs/v2.php",
        "line": 23,
        "args": [
          "/app/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/app/lib/private/Share20/Share.php",
    "Line": 190,
    "CustomMessage": "--"
  },
  "id": "631760490f92a"
}
```

**Comment by andyxheli** [comment]
@skjnldsv just got this error on NC 25.0.3  should i open a new issue regarding this ? loooks like is simular to this 

```
{"reqId":"O9DzFvvrkGNfP8GgFdFS","level":3,"time":"2023-01-20T09:50:01-06:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Files_Sharing\\ExpireSharesJob, arguments: )","userAgent":"--","version":"25.0.3.2","exception":{"Exception":"OCP\\Files\\NotFoundException","Message":"Node for share not found, fileid: 581588","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/sendent/lib/Listener/ShareDeletedListener.php","line":49,"function":"getNode","class":"OC\\Share20\\Share","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OCA\\Sendent\\Listener\\ShareDeletedListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1241,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1556,"function":"deleteShare","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1457,"function":"checkExpireDate","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/ExpireSharesJob.php","line":99,"function":"getShareById","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Files_Sharing\\ExpireSharesJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Share20/Share.php","Line":194,"message":"Error while running background job (class: OCA\\Files_Sharing\\ExpireSharesJob, arguments: )","exception":[],"CustomMessage":"Error while running background job (class: OCA\\Files_Sharing\\ExpireSharesJob, arguments: )"},"id":"63cacd19b7ecd"}

```

**Pull request closed without merging**
