### PR TITLE
Distinguish 'done' from 'configuring' in 2FA

### LINKED ISSUE #35554: Confusing variable name in 2FA
When there is a token in the session for which the user is still [setting up 2FA](https://raw.githubusercontent.com/nextcloud/twofactor_totp/master/screenshots/settings.png), setting `self::SESSION_UID_DONE` ("two_factor_auth_passed") is a misnomer.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by michielbdejong**
* Resolves: #35554

## Summary

When there is a token in the session for which the user is still [setting up 2FA](https://raw.githubusercontent.com/nextcloud/twofactor_totp/master/screenshots/settings.png), setting `self::SESSION_UID_DONE` ("two_factor_auth_passed") is a misnomer.

AFAICT, everything works fine if you set nothing into the session and just return 'false' from this if-statement, but in case there is some code (now or in the future) that needs to know if the user is configuring 2FA, to play it safe I would suggest storing `self::SESSION_UID_CONFIGURING` ("two_factor_auth_configuring") into the session.

## TODO

- [ ] add tests
- [ ] test manually
- [ ] consider removing this session variable once configuration is successfully completed

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by st3iny** [comment]
Test need to be fixed:

```
There was 1 failure:
--
264 |  
265 | 1) Test\Authentication\TwoFactorAuth\ManagerTest::testNeedsSecondFactorSessionAuthFailDBPass
266 | Expectation failed for method name is "set" when invoked 1 time(s)
267 | Parameter 0 for invocation OCP\ISession::set('two_factor_auth_configuring', 'user') does not match expected value.
268 | Failed asserting that two strings are equal.
269 | --- Expected
270 | +++ Actual
271 | @@ @@
272 | -'two_factor_auth_passed'
273 | +'two_factor_auth_configuring'
274 |  
275 | /drone/src/lib/private/Authentication/TwoFactorAuth/Manager.php:363
276 | /drone/src/tests/lib/Authentication/TwoFactorAuth/ManagerTest.php:679
```

**Comment by michielbdejong** [comment]
* performance tests `Errors during submodule fetch` - will investigate
* Will sign off latest commit so DCO passes
* Cypress `Default cloud background is not rendered` seems unrelated?
* continuous-integration/drone/pr `integration-contacts-menu` test is failing, seems unrelated?

**Comment by st3iny** [comment]
> * performance tests `Errors during submodule fetch` - will investigate
> * Will sign off latest commit so DCO passes
> * Cypress `Default cloud background is not rendered` seems unrelated?
> * continuous-integration/drone/pr `integration-contacts-menu` test is failing, seems unrelated?

Failures seem to be unrelated. Please fix DCO and we should be good to go.

**Comment by michielbdejong** [comment]
DCO fixed

**Comment by miaulalala** [comment]
Drone failure is 
```
--- Failed scenarios:
--
1366 |  
1367 | /drone/src/build/integration/features/contacts-menu.feature:27

**Comment by miaulalala** [comment]
Something is wrong with the submodule 3rd party reference hash. can you rebase on the current master?

**Comment by mickenordin** [comment]
Any news on getting this merged?

**Comment by michielbdejong** [comment]
I think the rebase was successful and now all we're waiting for is for someone to actually click "merge", right?
CC @ChristophWurst @st3iny @miaulalala

**Comment by miaulalala** [comment]
Unfortunately the rebase wasn't successful. Can you do it @michielbdejong or do you need some help?

**Comment by miaulalala** [comment]
```
--
290 |  
291 | There was 1 failure:
292 |  
293 | 1) Test\Authentication\TwoFactorAuth\ManagerTest::testNeedsSecondFactorSessionAuthFailDBPass
294 | Expectation failed for method name is "set" when invoked 1 time(s)
295 | Parameter 0 for invocation OCP\ISession::set('two_factor_auth_configuring', 'user') does not match expected value.
296 | Failed asserting that two strings are equal.
297 | --- Expected
298 | +++ Actual
299 | @@ @@
300 | -'two_factor_auth_passed'
301 | +'two_factor_auth_configuring'
302 |  
303 | /drone/src/lib/private/Authentication/TwoFactorAuth/Manager.php:363
304 | /drone/src/tests/lib/Authentication/TwoFactorAuth/ManagerTest.php:678
305 |  
306 | --
```
@michielbdejong test is failing in drone.

**Comment by mrvahedi68** [comment]
@miaulalala Tests passing now.

**Comment by michielbdejong** [comment]
@miaulalala what is the status of this PR, is it going to be merged now?

**Comment by miaulalala** [comment]
> @miaulalala what is the status of this PR, is it going to be merged now?

Just checking if the changes to the .devcontainer can stay, otherwise looks good. in the meantime, can you update your branch to the latest master?

**Review by miaulalala — CHANGES_REQUESTED** [review]
Unfortunately the .devconatiner changes have to go to keep everything tidy.

If you would like to keep the changes, you can open a second PR to update the devcontainer to 8.1 - would be nice to have that in, but not in this PR :)

**Comment by michielbdejong** [comment]
superseded by #39411

**Pull request closed without merging**
