### PR TITLE
Move change password to Vue

### PR DESCRIPTION
**Pull request by ChristophWurst**
Supersedes https://github.com/nextcloud/server/pull/15368

cc @listrate

### CODE REVIEW

**Comment by ChristophWurst** [comment]
This does not seem to work right now.

**Comment by ChristophWurst** [comment]
@listrate feel free to push your local HEAD to the old feature branch and re-open your PR. I thought this feature was ready for a final touch and integration but it seems a few pieces are still missing.

**Comment by skjnldsv** [comment]
Here you go @ChristophWurst

**Comment by ChristophWurst** [comment]
> Here you go @ChristophWurst

I meant to the original PR. You just overwrote my carefully rebased branch that also bundles the zxcvb via npm :see_no_evil:

**Comment by skjnldsv** [comment]
> I meant to the original PR. You just overwrote my carefully rebased branch that also bundles the zxcvb via npm

Soo, I did the exact same? :p

**Comment by ChristophWurst** [comment]
Closing as I don't see any progress on this.

**Pull request closed without merging**
