### PR TITLE
add share by mail icon, fix #1979

### LINKED ISSUE #1979: Need a nice app icon for share by mail
The "share by mail" is a new share provider which allows you to directly send a personalized link to a give email address. This all will be shipped with Nextcloud 11 and needs a nice app icon.

app: https://github.com/nextcloud/server/tree/master/apps/sharebymail

cc @nextcloud/designers

### PR DESCRIPTION
**Pull request by jancborchardt**
I’m confused as to why this has to be a separate app and is not directly combined with sharing. It’s starting to get really overwhelming for admins with all these standard apps which populate the apps management. But anyway here’s the icon @schiessle 

Maybe we need a separate filtered out category for »System apps« like all the viewers and essential stuff? cc @karlitschek @LukasReschke

### CODE REVIEW

**Comment by karlitschek** [comment]
Hmm. From a code and flexibility perspective it is always good to have it as separate app. We have to make sure that the app description is good so that people understand what it does IMHO

**Comment by MorrisJobke** [comment]
> Maybe we need a separate filtered out category for »System apps« like all the viewers and essential stuff? cc @karlitschek @LukasReschke

It then also feels more like "enabling features" instead of having a "ton of settings" - I don't know if this makes it from a UX point of view better or worse. 😕

**Comment by MorrisJobke** [comment]
:+1:

**Comment by schiessle** [comment]
icon looks good :+1:

**Comment by schiessle** [comment]
> It then also feels more like "enabling features" instead of having a "ton of settings"

Exactly and if a admin don't want to allow any kind of "external sharing" he can just disable the app (aka share provider). IMHO much better than adding yet another option to the sharing settings.

**Pull request merged**
