### PR TITLE
[stable10] deleted files, fix mimetype detection

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/nextcloud/server/pull/1346

cc @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
cc @rullzer @LukasReschke

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
