### PR TITLE
Always show the tagging tabview so it is available after switching to…

### LINKED ISSUE #4944: Tag UI missing
### Steps to reproduce
1. Try to tag a file that has no tags yet in the UI

### Expected behaviour
Click on the Tags label and add them

### Actual behaviour
Tag label is missing

The problem is, that the `Tag` label is somehow removed from the UI. You can see it show up for a split second:
https://github.com/nextcloud/server/blob/a06398f804fa95ec8b6d9249a3c3c571fe4cb4b8/apps/systemtags/js/systemtagsinfoview.js#L151

@ChristophWurst you have some minutes to check this before the final?

### PR DESCRIPTION
**Pull request by nickvergessen**
… sharing

Partly reverting c5c403b57467fb3df83f4f7ffe4df9705d86c3ea

Fix #4944

In case @ChristophWurst can't fix the rendering issue, we should merge this @LukasReschke

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> In case @ChristophWurst can't fix the rendering issue, we should merge this @LukasReschke

Could reproduce the issue but not follow the code paths that cause this problem. Apparently it only occurs as soon as the share tab in the sidebar is opened. Then, the `sharesChanged` is fired and the share model gets updated. This causes the view to re-render and hence the tags icon disappears because it's added by jquery (it's not part of the template/view).

**Review by LukasReschke — APPROVED** [review]
Better than nothing…

**Comment by schiessle** [comment]
hm, now that Nc12 is out I would prefer to invest the time we have now until 12.0.1 to look for a proper solution. Does nobody has an idea? cc @nextcloud/javascript @nextcloud/designers ?

**Comment by jancborchardt** [comment]
Well it should work as intended: Showing only the "Tags" text with icon by default. On click open the input field and focus it. When there are tags for a file already, show the input field directly.

So, what broke it?

**Comment by nickvergessen** [comment]
When you switch to the sharing tab the sidebar is somewhat refreshed, which removes the “Tags“ label+icon and you have no way to add a tag. When comments and activity are off, this is always the case

**Comment by danxuliu** [comment]
> hm, now that Nc12 is out I would prefer to invest the time we have now until 12.0.1 to look for a proper solution. Does nobody has an idea?

Please see #5310

**Comment by nickvergessen** [comment]
Replaced by #5310

**Pull request closed without merging**
