### PR TITLE
Let the admin configure the default share permissions

### PR DESCRIPTION
**Pull request by schiessle**
Let the admin configure the default share permissions

Possible look:

default-share2

or (currently implemented)

default-share1

### CODE REVIEW

**Comment by schiessle** [comment]
@jancborchardt please have a look at the two screenshots above. What do you prefer? Or something complete different?

**Comment by jancborchardt** [comment]
Do we still want to stick to this complicated CRUD-mechanic? I thought at some point we only do two permissions:
- Can edit
- Can reshare

**Comment by schiessle** [comment]
Since Nextcloud 13 is out I think now it is the right time to pick this up, looking forward to your reviews

**Comment by MorrisJobke** [comment]
> Since Nextcloud 13 is out I think now it is the right time to pick this up, looking forward to your reviews

First of all: looking forward for your merge conflict fixes 😜 😉

**Comment by schiessle** [comment]
@MorrisJobke done... now it is your turn 😉

**Comment by jancborchardt** [comment]
What about my comment above? "Can edit", "Can reshare" should be the permissions, none other.

**Comment by schiessle** [comment]
@jancborchardt I think that's a bit out of context. I'm completely open for simplifying the permissions. But this is one is just about making the default permissions configurable.

**Review by MorrisJobke — APPROVED** [review]

**Comment by schiessle** [comment]
waiting for a second review... Would be great to get this finally in before we have to rebase it again and again. Thanks!

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen @skjnldsv Review would be nice :)

**Comment by rullzer** [comment]
I rebased to make sure it all still works. Fails somehow. I'll look into the why....

**Comment by rullzer** [comment]
Ah was just cached stuff. Works like a charm.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
