### PR TITLE
Add SVG support check to setup check

### PR DESCRIPTION
**Pull request by nhirokinet**
For proper display of favicon, SVG support in imagemagick should be installed in addition to php-imagick.

https://github.com/nextcloud/server/blob/ca1dc0009dfde447c90db826465defbb156966da/apps/theming/lib/ImageManager.php#L300-L302

I installed php-imagick to Ubuntu 20.04, but this did not have SVG support. Manually installing `libmagickcore-6.q16-6-extra` solved the problem and got icon with proper resolution.

So I thought this should be noticed in `Security & setup warnings`.

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks :+1: 

Sounds good to me. There is a long discussion to recommend imagick or not: https://github.com/nextcloud/server/issues/13099

https://github.com/nextcloud/server/blob/031054a3c367691b30807d9c8f86b1040e0d5170/apps/settings/lib/Controller/CheckSetupController.php#L596-L600

I would suggest to run the check only if the theming app is enabled like with the imagick modul.

**Comment by nhirokinet** [comment]
Thanks for comment, I updated this to run only when theming app is enabled.

**Comment by skjnldsv** [comment]
> I would suggest to run the check only if the theming app is enabled like with the imagick modul.

Actually we also need it for good avatars.
So I would leave it as follows: if we have imagick, warn if you don't have svg support. Regardless of theming app status

**Comment by nhirokinet** [comment]
Hmm, so it may be checked regardless of theming app status. Theming app is default app, so I feel no much meaning for limiting to the case theming app is installed.

**Review by skjnldsv — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

**Comment by skjnldsv** [comment]
```
npmbuildbot_1  | 09:33:57.719Z  WARN probot: The provided path / does not contain any changes to commit
npmbuildbot_1  | 09:33:57.721Z  INFO probot: Invalid request: nextcloud/server#23677
```

Weird

**Comment by skjnldsv** [comment]
on it

**Comment by nhirokinet** [comment]
Ah, it seems 2 lines have space indents on my commit.

**Comment by nhirokinet** [comment]
fixed it in 7c94728 . Can you check it again?

**Comment by skjnldsv** [comment]
> fixed it in [7c94728](https://github.com/nextcloud/server/commit/7c9472803359a9e2396b14fa935ad5f31d830cd2) . Can you check it again?

Raah, no, I was on it ^^

> on it

**Comment by skjnldsv** [comment]
No more touching, let me do :p

**Comment by nhirokinet** [comment]
Oh, sorry. I will leave this pull request in this state.

**Comment by skjnldsv** [comment]
Tests fixes pushed, rebased and squashed ! :rocket:

**Comment by kesselb** [comment]
Safe to ignore Psalm. It's broken on master as well.

**Comment by skjnldsv** [comment]
:rocket: Thanks @nhirokinet :rabbit:

**Comment by ccoenen** [comment]
I would like to suggest clarifying the error message. Right now, a good portion of users might be tempted to just install the package without considering the implications.

I would like to suggest adding a link to documentation with (roughly) this text by @J0WI: https://github.com/nextcloud/docker/issues/1414#issuecomment-798781132

**Pull request merged**
