### PR TITLE
Prompt on destructive user actions

### LINKED ISSUE #17261: Require confirmation when trying to delete an account
**Is your feature request related to a problem? Please describe.**
As an administrator it is too easy to delete a user in the user selection by a wrong click, because no confirmation is asked for. The same applies to deactivating the user and wipe all of it's devices, while the impersonation option asks for confirmation.

**Describe the solution you'd like**
Require confirmation from the administrator when trying to delete or disable the user, or wipe the user's devices, as done with the impersonate option.

**Additional context**
Menu
Impersonation

### PR DESCRIPTION
**Pull request by gary-kim**
Closes #17261 

More or less copied what @jancborchardt wrote in #17261.

Screenshot from 2019-11-05 14-48-41
Screenshot from 2019-11-05 14-48-30

### CODE REVIEW

**Comment by skjnldsv** [comment]
I think just a confirm action is enough. If an admin want to delete 10 users, this will be quite exhausting. :)
I would not go for an input.

**Comment by jancborchardt** [comment]
Right, we could go for confirmation first, without needing to put in the username, as right now we don’t do _anything_. Step by step. :)

@gary-kim only 2 things:
- "Account deletion" should have lowercase "d" as we only capitalize the first word
- Is it possible to force the dialogs to a max-width? It looks very wide at the moment, and the long sentences are not really readable.

**Comment by gary-kim** [comment]
> * "Account deletion" should have lowercase "d" as we only capitalize the first word
> 
> * Is it possible to force the dialogs to a max-width? It looks very wide at the moment, and the long sentences are not really readable.

Done!

**Comment by jancborchardt** [comment]
Sorry, 2 more things :)
- The exclamation mark on the left of the text can be removed, it’s a bit off.
- If it’s a destructive action like user deletion and remote wipe, the confirm/primary button should be destructive red: `var(--color-error)` – that’s the last line of defense and keeps people from accidentally clicking confirm.

Thanks a lot @gary-kim!

**Comment by gary-kim** [comment]
> Sorry, 2 more things :)
> 
>     * The exclamation mark on the left of the text can be removed, it’s a bit off.
> 
>     * If it’s a destructive action like user deletion and remote wipe, the confirm/primary button should be destructive red: `var(--color-error)` – that’s the last line of defense and keeps people from accidentally clicking confirm.
> 
> 
> Thanks a lot @gary-kim!

Done!

**Review by jancborchardt — APPROVED** [review]
Perfect! :sparkles: The button being red is really the key here, so people don’t mindlessly click.

Great work @gary-kim! :) (Also thanks a lot for always updating the screenshots)

**Review by skjnldsv — APPROVED** [review]
Yes!! :rocket: 
Great job

**Comment by jancborchardt** [comment]
The Drone failures seem unrelated? One failed on clone and one on some detail view?

**Comment by gary-kim** [comment]
Reran the test. Failed at a different place so it's probably unrelated.

**Comment by jancborchardt** [comment]
@skjnldsv @ChristophWurst review please :)

**Comment by skjnldsv** [comment]
> @skjnldsv @ChristophWurst review please :)

I mean, I already reviewed :p

**Comment by jancborchardt** [comment]
@skjnldsv right, I meant "check please if we can merge this despite the failures since they seem unrelated". :D

**Pull request merged**
