### PR TITLE
Bump aws/aws-sdk-php to 3.240

### PR DESCRIPTION
**Pull request by come-nc**
See https://github.com/nextcloud/server/issues/34787#issuecomment-1294825040

- [x] https://github.com/nextcloud/3rdparty/pull/1210
- [x] rebase

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

**Review by PVince81 — APPROVED** [review]
:+1: after rebase/adjusting commit id

**Comment by come-nc** [comment]
> +1 after rebase/adjusting commit id

Done, waiting on CI.

**Comment by come-nc** [comment]
> +1 after rebase/adjusting commit id

Done, waiting on CI.

**Comment by szaimen** [comment]
Not sure but seems like autoloaders are not up-to-date?

**Comment by szaimen** [comment]
@come-nc should we revert https://github.com/nextcloud/3rdparty/pull/1210?

**Comment by come-nc** [comment]
> @come-nc should we revert [nextcloud/3rdparty#1210](https://github.com/nextcloud/3rdparty/pull/1210)?

No, it was merged with https://github.com/nextcloud/server/pull/34996

**Pull request closed without merging**
