### PR TITLE
Rename delete label to Delete folder/file

### LINKED ISSUE #16660: The "view shares" screen is counter intuitive and could lead to unintentional data deletion.
Let's say that I have just installed nextcloud and shared 3 or 4 files from my uploaded collection. If I follow the workflow from the Nextcloud homepage of clicking on "Files" and then clicking on "Shares" - I am presented with a nice, neat, uniform list of file shares: 

nc1

Particularly with only shared folders displayed on this screen, it appears to me as though all functions on this page pertain directly to the file shares. Therefore it seems as though the "delete" function here relates only to the share, and clicking it is going to delete the share.

In this case the delete button actually deletes the file, which is probably not what I want to do. I think that most users deleting an object from this screen will be thinking "delete the share", so in my opinion this UI is counter-intuitive and will probably lead to accidental data destruction.

I can foresee a case in which someone has accidentally emailed their boss an inflammatory document / image / etc, and just wants to unshare it - they go to the share screen in a panic and then just hit "delete" - boom!

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #16660 

Capture d’écran_2019-08-14_18-28-57

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Fine by me

**Review by rullzer — APPROVED** [review]

**Review by tobiasKaminsky — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]

**Comment by skjnldsv** [comment]
Unrelated failures https://drone.nextcloud.com/nextcloud/server/20863

**Pull request merged**
