### PR TITLE
Also hide group from direct matches

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/server/blob/af03f5d516f43a6b34c66b57f4a00659caf8ccb3/lib/private/Collaboration/Collaborators/GroupPlugin.php#L96-L98

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Backporting?

**Comment by nickvergessen** [comment]
Should backport to where the method was introduced.
https://github.com/nextcloud/server/pull/14347

But it seems to be quie old already, so 20 it is?

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failures unrelated, lets get this in

**Pull request merged**
