### PR TITLE
NC16 is php >= 7.1

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:heart:

**Review by nickvergessen — APPROVED** [review]

**Comment by rullzer** [comment]
Well. This requires of course all the CI containers of php7 to be upgraded

**Comment by skjnldsv** [comment]
We'll have to update the docs as well :)

**Comment by tcitworld** [comment]
Oh yeah, finally we can use PHPUnit 7!

**Pull request merged**
