### PR TITLE
Fix unit test compatibility issues with phpunit 5.2+

### PR DESCRIPTION
**Pull request by nickvergessen**
@schiessle should reduce the number of fails, I'm not done yet tough

### CODE REVIEW

**Comment by nickvergessen** [comment]
Should be ready for review, removes 57 Errors and ~30 Fatals for me, using phpunit 5.2.x

**Comment by nickvergessen** [comment]
Please reviewerino @LukasReschke @MorrisJobke

**Comment by MorrisJobke** [comment]
Indeed. Looks a lot better (with 5.3.2):

> Tests: 8728, Assertions: 38742, Errors: 1, Failures: 11, Skipped: 368.

Thanks :)

Also the changes looks good 👍

**Comment by schiessle** [comment]
great :+1:

**Pull request merged**
