### PR TITLE
fix references to ownCloud in the federations app

### PR DESCRIPTION
**Pull request by schiessle**
cc @LukasReschke @MorrisJobke @blizzz please review

### CODE REVIEW

**Comment by MorrisJobke** [comment]
In #162 I changed the sentences that the federation isn't bound to our server anymore, because we also welcome 3rdparty implementations (like pydio) to federate with us :)

**Comment by schiessle** [comment]
at the moment you can't add a pydio as trusted server. But you will get a error message anyway, so it should be ok

**Comment by vincchan** [comment]
LGTM

**Comment by LukasReschke** [comment]
LGTM

**Comment by LukasReschke** [comment]
Conflicts. Yay ;)

**Comment by MorrisJobke** [comment]
This is superseeded by https://github.com/nextcloud/server/pull/162#issuecomment-227129155 for master (also see the comment there).

But @schiessle and I agreed on doing only a stupid search and replace (like in this PR) for stable9 to keep the existing translations.

I will close this now, because @schiessle is already working on the port of this to stable9 (cherry-picking doesn't work because of changed translations around the changed lines).

**Pull request closed without merging**
