### PR TITLE
Show reset to default button for theming values on hover, fix #3198

### LINKED ISSUE #3198: Show reset to default button for theming values on hover
When in the Theming section of administration there are "restore to default" options offered when changing the logo or Login image. When changing other theming settings this is not offered.
bildschirmfoto vom 2017-01-22 21-00-20

At least for the color it would make sense to also offer a reset button.

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #3198, please review @claell @nextcloud/theming @juliushaertl @schiessle @eppfel @MorrisJobke

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]
:+1:

**Comment by MorrisJobke** [comment]
It is somehow shown to the far right:

bildschirmfoto 2017-06-12 um 11 04 54

And this is with cleared cache, but it works (the on hover)

**Comment by jancborchardt** [comment]
@MorrisJobke which browser is this in? And does this also appear on master? Cause the change is purely to add hover, it's very unlikely that this bug is caused by this change.

**Comment by MorrisJobke** [comment]
> @MorrisJobke which browser is this in? And does this also appear on master? Cause the change is purely to add hover, it's very unlikely that this bug is caused by this change.

Yes - looks like this is also the case on master. I use Safari.

**Comment by MorrisJobke** [comment]
> Yes - looks like this is also the case on master. I use Safari.

Only happens on Safari. Chrome works fine and master is as well broken, but only in Safari. So let's get this in and fix Safari separately

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
