### PR TITLE
IMip emails should state the next appearance of events

### PR DESCRIPTION
**Pull request by nickvergessen**
1. Create a repeating event in the past using the calendar
2. Add an email address in the Attendees tab
3. Modify the time of the event

### Expected
Email says next meeting: `Wed., 30.01.2019, 14:30 - 15:30 (Europe/Berlin)`

### Actually
Email says first meeting: `Wed., 02.01.2019, 14:30 - 15:30 (Europe/Berlin)`

### CODE REVIEW

**Comment by georgehrke** [comment]
👎 
This needs proper fixing in the calendar app. Instead of adding the attendee to the repeating event itself, it needs to create a recurrence exception for one or all future events and assign the attendee to that exception. 

Related https://github.com/nextcloud/calendar/issues/7

**Comment by nickvergessen** [comment]
But even than the email which is sent has dtstart instead of the next future event. You an verify that this is independent from calendar, by changing the event with another client e.g. thunderbird+lightning or davx5 on android.

**Comment by jancborchardt** [comment]
@georgehrke is there a related issue open in the Calendar app already?

**Comment by georgehrke** [comment]
Yes: https://github.com/nextcloud/calendar/issues/7

**Comment by georgehrke** [comment]
btw, it won't show an annoying modal, it will just offer you two buttons:

06E6E7DB-5F2E-4356-B65E-4D1F7FEA1A27

**Comment by nickvergessen** [comment]
This is still happening and soooo annoying.

Just again I got an invitation email for:
> Di., 31.08.2021, 10:00 - 10:30 (Europe/Berlin)

Which is 3 weeks ago. What actually happened is that a future occurrence was modified/deleted. But instead of getting to know this I get a useless info text with the first occurrence. I don't know if 1 date was modified or all future dates either.

**Pull request closed without merging**
