### PR TITLE
"Too few arguments in L10NString" for all federated share notifications

### LINKED ISSUE #20562: PHP Warning - vsprintf(): Too few arguments in L10NString.php:79
When I look in my server logs i have several appearances of this warning:
```
vsprintf(): Too few arguments at /opt/nextcloud/lib/private/L10N/L10NString.php#79
```
Probably happens if `$this->parameters` is empty. Simple check if `$this->parameters` is empty, should solve it.

### Server configuration

**Operating system:** Debian GNU/Linux 10 (buster)

**Web server:** nginx

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 18.0.3

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #20562 

cc @anoadragon453 @DanScharon @Deltachaos

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
LGTM

**Comment by anoadragon453** [comment]
Hmm, what about this code would fail a `0 > 0` check :thinking:

**Comment by nickvergessen** [comment]
@blizzz this is what i ment in the other PR. We wont need this anymore if we get rid of the additional parameters in your pr

**Comment by nickvergessen** [comment]
Replaced by 22062

**Pull request closed without merging**
