### PR TITLE
Interpolate the log message also for logged exceptions

### PR DESCRIPTION
**Pull request by ChristophWurst**
According to PSR-3 the log message can have placeholders that are
replaced from the context object. Our logger implementation did that for
all PSR-3 logger methods. The only exception was our custom `logException`.

Since PsrLoggerAdapter calls logException when an exception key is
present in the context object, log messages were no longer interpolated.

Tested with the following snippet
```php
		try {
			throw new \InvalidArgumentException('henlo');
		} catch (\Throwable $e) {
			$logger->debug('oh {no}', [
				'no' => 'no',
				'exception' => $e,
			]);
		}
```

On master I get `oh {no}` in my log. With this patch it's `oh no`.

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
Fine by me also with backports, but 20 is EOL

**Comment by ChristophWurst** [comment]
> 20 is EOL

TIL!

**Pull request merged**
