### PR TITLE
Correctly calculate used space for quota with external storage

### LINKED ISSUE #4348: External storage quota
### Steps to reproduce
1. Add a openstack swift external storage device
2. upload a content on the storage

### Expected behaviour
The system should counts the external storage in the usage quota 

### Actual behaviour
External storage is exclude from the calculation

### Server configuration

**Operating system**: Debian 8.0

**Web server:** apache2

**Database:** mariadb 10.0

**PHP version:** 5.6.30

**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
No errors have been found.

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** openstack swift

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 

### Client configuration
**Browser:** Chrome

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
empty
```
</details>

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #4348
* #4357 + fixes of unit tests 

I tested this and it works here.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @Ardinis

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Missing signatures on:
> - 46b398e45be835fb5533f3997e12ee15829f99c1

and the remaining checks are not executed anymore. Maybe we should extract the signature one or move it to the end.

**Review by icewind1991 — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Fixed the signature.

**Comment by MorrisJobke** [comment]
They run fine now -> merge

**Pull request merged**
