### PR TITLE
Use AccountPlusIcon in broadcrombs

### LINKED ISSUE #40202: adjust icon of shared state in broadcrumb
> Shared
> image

I am not sure about this icon. Shouldn't we better use a different icon, e.g. this one?
image
https://fonts.google.com/icons?icon.style=Outlined&icon.set=Material+Symbols&selected=Material+Symbols+Outlined:folder_shared:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=shar

_Originally posted by @szaimen in https://github.com/nextcloud/server/issues/40192#issuecomment-1702890351_

cc @nextcloud/designers

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/40202
Close https://github.com/nextcloud/server/pull/42502
Supercedes https://github.com/nextcloud/server/pull/42502

| Before | After |
|---|---|
| image | image |

<details>
<summary>For my own testing</summary>

```
docker run -it --rm ^
--name nextcloud-easy-test1 ^
-p 8444:443 ^
-e SERVER_BRANCH=enh/40202/use-correct-icon ^
-e COMPILE_SERVER=1 ^
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" ^
ghcr.io/szaimen/nextcloud-easy-test:latest

```

</details>

### CODE REVIEW

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Nice @szaimen! Only one remark: The opacity is there to give a slight indication about the shared state, but maybe we can do it with the same colors as in the file list instead? (color-main-text and color-primary)

**Comment by szaimen** [comment]
> Nice @szaimen! Only one remark: The opacity is there to give a slight indication about the shared state, but maybe we can do it with the same colors as in the file list instead? (color-main-text and color-primary)

Should be fixed now :)

**Review by jancborchardt — APPROVED** [review]
Did not test the code but seems good

**Review by nimishavijay — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
> > /compile rebase /
> 
> this does NOT ignore conflicts

Yeah, figured that out already 😅😥

**Pull request merged**
