### PR TITLE
fix(UnifiedSearch): Remove title prop from modal

### PR DESCRIPTION
**Pull request by susnux**
## Summary

The `title` prop was renamed to `name` and is already provided, so the `title` prop is now the native `title` attribute which we should not set on the modal wrapper as it has no semantically meaning there.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nfebe — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]

**Comment by susnux** [comment]
drone unrelated

**Pull request merged**
