### PR TITLE
Recommend a device PIN for passwordless auth

### PR DESCRIPTION
**Pull request by ChristophWurst**
This is the first step towards https://github.com/nextcloud/server/issues/21215.

## Todo

- [x] Recommend a PIN during device regirstration
- [x] Recommend a PIN during login
- [x] Possible bug: Chrome respects the recommended PIN and asks for it. FF doesn't ask for it, because it doesn't support it. Yet if I add the key with Chrome and then log in with FF it works.

Right now ``"attestationType": "none",`` is saved with the key despite using a key. So it is not asked for at login.

cc @jans23

### CODE REVIEW

**Comment by jans23** [comment]
It would be great if this could go into the upcoming NC release. Any chance?

The reason why Firefox behaves differently than Chorme is that it doesn't support WebAuthn yet but only FIDO U2F, which is the predecessor. I see some activity at Firefox's code in this regards so hope that they will support WebAuthn one day. However, nothing we should wait for.

**Comment by rullzer** [comment]
@ChristophWurst I do not know the standard by heart anymore. But I believe the response you get back tells you if a pin is used or not. I'd say in case a pin is used on registration you should require it to be used.

**Comment by jans23** [comment]
Yes, just trusting an own request is insufficient. The response needs to be checked if a PIN had been used or not. See [the article linked here](https://github.com/nextcloud/server/issues/21215#issuecomment-1286724972) for more details.

**Comment by ChristophWurst** [comment]
I'm not working on this right now.

**Comment by p1gp1g** [comment]
Does this mean it won't be implemented in Nextcloud 29 ? This is a security issue for users of hardware tokens: anyone with physical access to the token can obtain an authenticated session.

At least changing the verification requirement to AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED for new registration would allow one to secure their access.

**Comment by ChristophWurst** [comment]
> AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED for new registration would allow one to secure their access.

It would not. The browser is still free to log in without asking for a pin.

**Comment by ChristophWurst** [comment]
@p1gp1g please take over if you have some time to complete the change :+1:

**Comment by p1gp1g** [comment]
@ChristophWurst done here: #44442. Is it possible to add it back to the 29 milestone ? This is a security issue I'm not comfortable with :)

**Pull request closed without merging**
