### PR TITLE
Fix colorizeSvg with transformations that contain a comma (,)

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/spreed/pull/1451#issuecomment-455163576

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looking good together with https://github.com/nextcloud/spreed/pull/1451 :+1:

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure unrelated: https://drone.nextcloud.com/nextcloud/server/14813/234

**Comment by skjnldsv** [comment]
Stable14 https://github.com/nextcloud/server/pull/13654

**Pull request merged**
