### PR TITLE
refactor(files): Migrate logger to Typescript

### PR DESCRIPTION
**Pull request by susnux**
1. This is just a tiny rename to make our files code base more consistent by using Typescript where possible.
2. Plus another small refactor to fix invalid doc block and resort imports

### CODE REVIEW

**Review by Pytal — COMMENTED** [review]
Maybe make it a named export?

**Review by artonge — APPROVED** [review]

**Comment by susnux** [comment]
> Maybe make it a named export?

In general I would agree, here it is so small and single use-case, so both work. I have not strong opinion on either of them.
Meaning I can do so if that is preferred :sweat_smile:

**Review by Pytal — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
