### PR TITLE
Refactor README

### PR DESCRIPTION
**Pull request by MariusBluem**
It's time to get rid of all the "getting things done" stuff ... Nextcloud **is** ready 💪 
This is also introducing some support information and more specified information about apps, the appstore, the code of conduct and our contributing file 😉 

Feedback welcome 😅 

cc @karlitschek @schiessle @MorrisJobke @LukasReschke @nickvergessen @rullzer @nextcloud/designers

### CODE REVIEW

**Comment by MariusBluem** [comment]
@Henni @irgendwie The contacts readme is next 😅😈

**Comment by karlitschek** [comment]
makes sense 👍

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
Great work on this @MariusBluem! :)

**Pull request merged**
