### PR TITLE
Fix contacts menu sizing

### PR DESCRIPTION
**Pull request by juliusknorr**
Reported by @nickvergessen 

Peek 2020-01-08 15-23

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Nice

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
master is NC19 now.
Please backport if it needs to go into 18

**Comment by skjnldsv** [comment]
Might be related 

```php
Scenario: just added users are seen in the contacts menu # /drone/src/tests/acceptance/features/header.feature:31
111 | Given I am logged in as the admin # LoginPageContext::iAmLoggedInAsTheAdmin()
112 | And I open the User settings # SettingsMenuContext::iOpenTheUserSettings()
113 | And I click the New user button # UsersSettingsContext::iClickTheNewUserButton()
114 | New user button in Users Settings could not be found (NoSuchElementException)
115 | And I see that the new user form is shown # UsersSettingsContext::iSeeThatTheNewUserFormIsShown()
116 | And I create user user1 with password 123456acb # UsersSettingsContext::iCreateUserWithPassword()
117 | And I see that the list of users contains the user user1 # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
118 | When I open the Contacts menu # ContactsMenuContext::iOpenTheContactsMenu()
119 | Then I see that the Contacts menu is shown # ContactsMenuContext::iSeeThatTheContactsMenuIsShown()
120 | And I see that the contact "user0" in the Contacts menu is shown # ContactsMenuContext::iSeeThatTheContactInTheContactsMenuIsShown()
121 | And I see that the contact "user1" in the Contacts menu is shown # ContactsMenuContext::iSeeThatTheContactInTheContactsMenuIsShown()
122 | And I see that the contact "admin" in the Contacts menu is not shown # ContactsMenuContext::iSeeThatTheContactInTheContactsMenuIsNotShown()
```

**Comment by juliushaertl** [comment]
As far as I understand it the failure is here:

112 | And I open the User settings # SettingsMenuContext::iOpenTheUserSettings()
113 | And I click the New user button # UsersSettingsContext::iClickTheNewUserButton()
**114 | New user button in Users Settings could not be found (NoSuchElementException)**

Doesn't seem related to me

**Comment by rullzer** [comment]
Yep seems fine.

**Comment by rullzer** [comment]
Ah mmmmm. seems this breaks the SCSS tests...

@juliushaertl or @skjnldsv do you have a clue?

**Comment by juliushaertl** [comment]
Hm aparently min is not well supported yet, let me see what we can do as an alternative.

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/server/pull/18806 for reference

**Pull request merged**
