### PR TITLE
Change status popover container

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This PR prevents the status popover from fluttering when scrolling. Requires https://github.com/nextcloud/nextcloud-vue/pull/1389 and https://github.com/nextcloud/server/pull/22614.

### CODE REVIEW

**Comment by georgehrke** [comment]
Can we actually use `header` here? I remember that PR from @ma12-co that you have to pass an `Element` object to the popover component.

**Comment by raimund-schluessler** [comment]
> 
> 
> Can we actually use `header` here? I remember that PR from @ma12-co that you have to pass an `Element` object to the popover component.

For the `container` a selector is necessary, see https://github.com/nextcloud/nextcloud-vue/pull/1389/files#diff-2bfd37a0e52db490178eb64c7675ecc9R277 and the fundamental implementation in `v-tooltip`: https://github.com/Akryum/v-tooltip#other-options

A DOM `Element` must be used for the `boundariesElement` though (that's why you probably remember this).

**Review by marcoambrosini — APPROVED** [review]

**Review by georgehrke — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
Rebased.

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
