### PR TITLE
Add activities for group membership changes

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Looks good!

**Comment by MorrisJobke** [comment]
### Status of [16703](https://drone.nextcloud.com/nextcloud/server/16703): failure

 * TESTS=checkers
<details><summary>Show full log</summary>

```
The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result

```
</details>


 * TESTS=acceptance, TESTS-ACCEPTANCE=app-comments
     * tests/acceptance/features/app-comments.feature:233
<details><summary>Show full log</summary>

```
  Scenario: search a comment in a child folder                            # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-comments.feature:233
    Given I am logged in                                                  # LoginPageContext::iAmLoggedIn()
    And I create a new folder named "Folder"                              # FileListContext::iCreateANewFolderNamed()
    And I enter in the folder named "Folder"                              # FileListContext::iEnterInTheFolderNamed()
    And I create a new folder named "Child folder"                        # FileListContext::iCreateANewFolderNamed()
    And I open the details view for "Child folder"                        # FileListContext::iOpenTheDetailsViewFor()
    And I open the "Comments" tab in the details view                     # FilesAppContext::iOpenTheTabInTheDetailsView()
      │ Tab header named Comments in details view in Files app could not be clicked
      │ Exception message: Offset within element cannot be scrolled into view: (0, 0): [object HTMLLIElement]
      │ Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      │ System info: host: '457abf857efd', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-43-generic', java.version: '1.8.0_91'
      │ Driver info: driver.version: unknown
      │ Trying again
      │ 
      Offset within element cannot be scrolled into view: (0, 0): [object HTMLLIElement]
      Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      System info: host: '457abf857efd', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-43-generic', java.version: '1.8.0_91'
      Driver info: driver.version: unknown (WebDriver\Exception\MoveTargetOutOfBounds)
    And I create a new comment with "Hello world" as message              # CommentsAppContext::iCreateANewCommentWithAsMessage()
    And I see a comment with "Hello world" as message                     # CommentsAppContext::iSeeACommentWithAsMessage()
    And I open the Files app                                              # FilesAppContext::iOpenTheFilesApp()
    When I search for "hello"                                             # SearchContext::iSearchFor()
    Then I see that the search result 1 is "user0Hello world"             # SearchContext::iSeeThatTheSearchResultIs()
    And I see that the search result 1 was found in "Folder/Child folder" # SearchContext::iSeeThatTheSearchResultWasFoundIn()
```
</details>


 * TESTS=acceptance, TESTS-ACCEPTANCE=app-files
   * cancelled - typically means that the tests took longer than the drone CI allows them to run
 * TESTS=acceptance, TESTS-ACCEPTANCE=app-files-sharing-link
     * tests/acceptance/features/app-files-sharing-link.feature:40
<details><summary>Show full log</summary>

```
  Scenario: creation is not possible by default in a public shared folder # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files-sharing-link.feature:40
    Given I act as John                                                   # ActorContext::iActAs()
    And I am logged in                                                    # LoginPageContext::iAmLoggedIn()
    And I create a new folder named "Shared folder"                       # FileListContext::iCreateANewFolderNamed()
    And I close the details view                                          # FilesAppContext::iCloseTheDetailsView()
      Details view in Files app could not be found after 100 seconds
      Close details view in Files app could not be found after 100 seconds (NoSuchElementException)
    And I see that the details view is closed                             # FilesAppContext::iSeeThatTheDetailsViewIsClosed()
    And I share the link for "Shared folder"                              # FilesAppSharingContext::iShareTheLinkFor()
    And I write down the shared link                                      # FilesAppSharingContext::iWriteDownTheSharedLink()
    When I act as Jane                                                    # ActorContext::iActAs()
    And I visit the shared link I wrote down                              # PublicShareContext::iVisitTheSharedLinkIWroteDown()
    And I see that the current page is the shared link I wrote down       # PublicShareContext::iSeeThatTheCurrentPageIsTheSharedLinkIWroteDown()
    And I see that the file list is eventually loaded                     # FileListContext::iSeeThatTheFileListIsEventuallyLoaded()
    Then I see that it is not possible to create new files                # FileListContext::iSeeThatItIsNotPossibleToCreateNewFiles()
sh: 1: kill: No such process
```
</details>


 * TESTS=acceptance, TESTS-ACCEPTANCE=login
     * tests/acceptance/features/login.feature:38
<details><summary>Show full log</summary>

```
  Scenario: log in with invalid user once fixed by admin              # /drone/src/github.com/nextcloud/server/tests/acceptance/features/login.feature:38
    Given I act as John                                               # ActorContext::iActAs()
    And I can not log in with user unknownUser and password 123456acb # LoginPageContext::iCanNotLogInWithUserAndPassword()
    When I act as Jane                                                # ActorContext::iActAs()
    And I am logged in as the admin                                   # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the User settings                                      # SettingsMenuContext::iOpenTheUserSettings()
    And I click the New user button                                   # UsersSettingsContext::iClickTheNewUserButton()
    And I see that the new user form is shown                         # UsersSettingsContext::iSeeThatTheNewUserFormIsShown()
    And I create user unknownUser with password 123456acb             # UsersSettingsContext::iCreateUserWithPassword()
    And I see that the list of users contains the user unknownUser    # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
    And I act as John                                                 # ActorContext::iActAs()
    And I log in with user unknownUser and password 123456acb         # LoginPageContext::iLogInWithUserAndPassword()
    Then I see that the current page is the Files app                 # FilesAppContext::iSeeThatTheCurrentPageIsTheFilesApp()
      Failed asserting that 'http://acceptance-login/index.php/login?user=unknownUser' starts with "http://acceptance-login/index.php/apps/files/".
```
</details>


 * TESTS=acceptance, TESTS-ACCEPTANCE=users
     * tests/acceptance/features/users.feature:13
     * tests/acceptance/features/users.feature:25
     * tests/acceptance/features/users.feature:35
     * tests/acceptance/features/users.feature:47
<details><summary>Show full log</summary>

```
  Scenario: create a new user with a custom display name                       # /drone/src/github.com/nextcloud/server/tests/acceptance/features/users.feature:13
    Given I am logged in as the admin                                          # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the User settings                                               # SettingsMenuContext::iOpenTheUserSettings()
    When I click the New user button                                           # UsersSettingsContext::iClickTheNewUserButton()
    And I see that the new user form is shown                                  # UsersSettingsContext::iSeeThatTheNewUserFormIsShown()
    And I set the user name for the new user to "test"                         # UsersSettingsContext::iSetTheUserNameForTheNewUserTo()
    And I set the display name for the new user to "Test display name"         # UsersSettingsContext::iSetTheDisplayNameForTheNewUserTo()
    And I set the password for the new user to "123456acb"                     # UsersSettingsContext::iSetThePasswordForTheNewUserTo()
    And I create the new user                                                  # UsersSettingsContext::iCreateTheNewUser()
    Then I see that the list of users contains the user "test"                 # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
    And I see that the display name for the user "test" is "Test display name" # UsersSettingsContext::iSeeThatTheDisplayNameForTheUserIs()
      Row for user test in Users Settings could not be found after 100 seconds
      displayName cell for user test in Users Settings could not be found after 100 seconds
      displayName input for user test in Users Settings could not be found after 100 seconds (NoSuchElementException)
  Scenario: delete a user                                                      # /drone/src/github.com/nextcloud/server/tests/acceptance/features/users.feature:25
    Given I act as Jane                                                        # ActorContext::iActAs()
    And I am logged in as the admin                                            # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the User settings                                               # SettingsMenuContext::iOpenTheUserSettings()
    And I see that the list of users contains the user user0                   # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
    And I open the actions menu for the user user0                             # UsersSettingsContext::iOpenTheActionsMenuOf()
    And I see that the "Delete user" action in the user0 actions menu is shown # UsersSettingsContext::iSeeTheAction()
      Failed asserting that false is true.
    When I click the "Delete user" action in the user0 actions menu            # UsersSettingsContext::iClickTheAction()
    Then I see that the list of users does not contains the user user0         # UsersSettingsContext::iSeeThatTheListOfUsersDoesNotContainsTheUser()
  Scenario: disable a user                                                      # /drone/src/github.com/nextcloud/server/tests/acceptance/features/users.feature:35
    Given I act as Jane                                                         # ActorContext::iActAs()
    And I am logged in as the admin                                             # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the User settings                                                # SettingsMenuContext::iOpenTheUserSettings()
    And I see that the list of users contains the user user0                    # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
    And I open the actions menu for the user user0                              # UsersSettingsContext::iOpenTheActionsMenuOf()
    And I see that the "Disable user" action in the user0 actions menu is shown # UsersSettingsContext::iSeeTheAction()
      Failed asserting that false is true.
    When I click the "Disable user" action in the user0 actions menu            # UsersSettingsContext::iClickTheAction()
    Then I see that the list of users does not contains the user user0          # UsersSettingsContext::iSeeThatTheListOfUsersDoesNotContainsTheUser()
    When I open the "Disabled users" section                                    # AppNavigationContext::iOpenTheSection()
    Then I see that the list of users contains the user user0                   # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
  Scenario: users navigation without disabled users                                   # /drone/src/github.com/nextcloud/server/tests/acceptance/features/users.feature:47
    Given I act as Jane                                                               # ActorContext::iActAs()
    And I am logged in as the admin                                                   # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the User settings                                                      # SettingsMenuContext::iOpenTheUserSettings()
    And I open the "Disabled users" section                                           # AppNavigationContext::iOpenTheSection()
    And I see that the list of users contains the user disabledUser                   # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
    And I open the actions menu for the user disabledUser                             # UsersSettingsContext::iOpenTheActionsMenuOf()
    And I see that the "Enable user" action in the disabledUser actions menu is shown # UsersSettingsContext::iSeeTheAction()
      Failed asserting that false is true.
    When I click the "Enable user" action in the disabledUser actions menu            # UsersSettingsContext::iClickTheAction()
    Then I see that the section "Disabled users" is not shown                         # AppNavigationContext::iSeeThatTheSectionIsNotShown()
    When I open the User settings                                                     # SettingsMenuContext::iOpenTheUserSettings()
    Then I see that the section "Disabled users" is not shown                         # AppNavigationContext::iSeeThatTheSectionIsNotShown()
```
</details>


 * TESTS=acceptance, TESTS-ACCEPTANCE=apps
     * tests/acceptance/features/apps.feature:66
<details><summary>Show full log</summary>

```
  Scenario: Show section from app store                       # /drone/src/github.com/nextcloud/server/tests/acceptance/features/apps.feature:66
    Given I act as Jane                                       # ActorContext::iActAs()
    And I am logged in as the admin                           # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the Apps management                            # SettingsMenuContext::iOpenTheAppsManagement()
    And I see that the current section is "Your apps"         # AppNavigationContext::iSeeThatTheCurrentSectionIs()
    When I open the "Files" section                           # AppNavigationContext::iOpenTheSection()
      Files section item in App Navigation could not be found after 100 seconds (NoSuchElementException)
    Then I see that there some apps listed from the app store # AppsManagementContext::iSeeThatThereSomeAppsListedFromTheAppStore()
    And I see that the current section is "Files"             # AppNavigationContext::iSeeThatTheCurrentSectionIs()
```
</details>

**Review by MorrisJobke — APPROVED** [review]
Nice and working 👍 

bildschirmfoto 2019-03-05 um 10 47 37

**Comment by skjnldsv** [comment]
> Nice and working 

Though design is off, is it related to this pr?

**Comment by MorrisJobke** [comment]
> Though design is off, is it related to this pr?

Was due to resizing and juggling with the window. :/

**Pull request merged**
