### PR TITLE
Dont reparse info xml + cache AppInfo XML

### PR DESCRIPTION
**Pull request by LukasReschke**
This is a cherry-pick of https://github.com/owncloud/core/pull/25968, which we wouldn't necessary require since we have this optimised already at another place. But it's nice to keep the code kinda aligned for now.

In addition, I noticed that it's easily possible to gain at least 20ms on every request. By caching the appinfo in the configured memory cache, see https://github.com/nextcloud/server/commit/0c2b17c80f54027aaebbc43b8efb21fdaffe8d45

Trace: https://blackfire.io/profiles/compare/fc326ad3-100d-49b8-8ea9-8343240f53f3/graph

### CODE REVIEW

**Comment by LukasReschke** [comment]
cc @rullzer As discussed.

**Comment by rullzer** [comment]
I like it!
LGTM

**Comment by MorrisJobke** [comment]
Tested and also works fine with no configured cache 👍

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Drone fails due to the signed-off check for the upstream commit. -> merge

**Comment by MorrisJobke** [comment]
@LukasReschke This was backported upstream to 9.1 - for https://github.com/owncloud/core/issues/25603

Should we also backport this?

**Comment by LukasReschke** [comment]
Nah. We have another patch for that in 9.1 :)

**Pull request merged**
