### PR TITLE
fix: Use viewBox instead of viewbox in SVGs

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

The correct attribute name is `viewBox` and not `viewbox`: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by bigcat88 — APPROVED** [review]

**Review by come-nc — APPROVED** [review]
Should we have some kind of lint svg CI workflow?

**Comment by nickvergessen** [comment]
> Should we have some kind of lint svg CI workflow?

We should at least make sure this here is not breaking it again any time soon:
https://github.com/nextcloud/server/blob/master/build/image-optimization.sh#L89-L97

We can of course also run that script on CI and ensure an empty diff. But I would see it as a different task

**Comment by provokateurin** [comment]
> We should at least make sure this here is not breaking it again any time soon

I ran it, it didn't modify the attribute :+1:

**Pull request merged**
