### PR TITLE
Allow app type session which we load in base.php

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref 
https://github.com/nextcloud/server/blob/80f6a5834ab9e679c1a0df6a1aee82107ca5cfe3/lib/base.php#L674

### CODE REVIEW

**Review by blizzz — COMMENTED** [review]
please also adjust https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/api/v1/release/info.xsd

**Comment by nickvergessen** [comment]
> please also adjust https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/api/v1/release/info.xsd

Will do, once this was merged

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by ChristophWurst** [comment]
With https://docs.nextcloud.com/server/stable/developer_manual/app_development/bootstrap.html#bootstrapping-process app types should be more or less obsolete, right? The historic issue was that the loading order need to be adjusted so that some apps run earlier then others. With the two step process we first register, then we act. So the order doesn't matter.

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Comment by nickvergessen** [comment]
> With https://docs.nextcloud.com/server/stable/developer_manual/app_development/bootstrap.html#bootstrapping-process app types should be more or less obsolete, right? The historic issue was that the loading order need to be adjusted so that some apps run earlier then others. With the two step process we first register, then we act. So the order doesn't matter.

While you got a point there, I don't dare to touch this yet

**Pull request merged**
