### PR TITLE
Remove leftover '

### PR DESCRIPTION
**Pull request by rullzer**
Followup to #11583

Spotted by @danxuliu

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
🙈

**Review by ChristophWurst — APPROVED** [review]
Whoops

**Review by danxuliu — COMMENTED** [review]
Not exactly a ', but something to be fixed too (either in this or in other pull request):
[`...tor}}"> t('core', '{{shareInitiatorDisplayName}} shared via link') + '</sp...`](https://github.com/nextcloud/server/blob/b0fd31496b5edb95264c0ea3139692b5969f40e0/core/js/share/sharedialogshareelistview.handlebars#L22)
[`...tem">' + t('settings', 'Allow filesystem access') </la...`](https://github.com/nextcloud/server/blob/d66e662492185f742bebd9ec95bfc6bf6379cd9a/settings/js/authtoken.handlebars#L16)
[`...tle="' + t('settings', 'Disconnect') ">' + t('settings', 'Revoke') +'</a...`](https://github.com/nextcloud/server/blob/d66e662492185f742bebd9ec95bfc6bf6379cd9a/settings/js/authtoken.handlebars#L21)

**Comment by rullzer** [comment]
O they should go as well where are they?

**Pull request merged**
