### PR TITLE
Rewrite getNumberOfUnreadCommentsForFolder query

### PR DESCRIPTION
**Pull request by rullzer**
Before the joining and filtering removed unkown files. Resulting in
manual queries for all the files with no (unread) comments (the 99%).

Long story short. This will return a list of all the files in the parent
folder with their unread comment count (can be 0). But this makes sure
that the result is properly cached. In the dav handling.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Change makes sense and code looks good!

:+1: as discussed

**Comment by icewind1991** [comment]
@rullzer can you cleanup your testing commits

**Comment by rullzer** [comment]
@icewind1991 once phan is happy I will ;)

**Comment by rullzer** [comment]
Ok gave up. Just suppressed the warning

**Comment by rullzer** [comment]
@icewind1991 work your review magic

**Comment by blizzz** [comment]
According to EXPLAIN $query on mysql it eventually does not make a difference, identical output.

**Review by blizzz — APPROVED** [review]

**Pull request merged**
