### PR TITLE
Update update-psalm-baseline workflow

### PR DESCRIPTION
**Pull request by skjnldsv**
- use proper versions
- request server backend team as reviewers
- allow to run manually

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
Hum,
https://github.com/nextcloud/server/runs/4102839306?check_suite_focus=true

Maybe we should still continue on failure :thinking:

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/29546

**Comment by juliushaertl** [comment]
Makes sense. The error itself seems to come from https://github.com/nextcloud/server/pull/29502/files#diff-64a02ee1149d33d0747360694c2abf4ef1bdbfc379b4bb40f76c22b5b1fc06d9R1085

**Comment by skjnldsv** [comment]
> Makes sense. The error itself seems to come from [#29502 (files)](https://github.com/nextcloud/server/pull/29502/files#diff-64a02ee1149d33d0747360694c2abf4ef1bdbfc379b4bb40f76c22b5b1fc06d9R1085)

Added in https://github.com/nextcloud/server/pull/29547

**Pull request merged**
