### PR TITLE
feat(out-of-office): Add OCS endpoint to set and clear absence

### LINKED ISSUE #41458: Out of office: expose setting endpoint via OCS
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

As a Nextcloud client developer I want to integrate with https://github.com/nextcloud/server/issues/40616. The APIs added are only usable for the web app.

**Describe the solution you'd like**

Expose the APIs as OCS instead. This makes them consumable by clients.

**Describe alternatives you've considered**

N/a

**Additional context**

Suggested by @nickvergessen in https://github.com/nextcloud/server/pull/40767#issuecomment-1805873647

### PR DESCRIPTION
**Pull request by nickvergessen**
* Resolves: #41458 

## TODO

- [x] Add OCS endpoint so that clients can set this in the future
- [x] Migrate frontend to OCS endpoint
- [x] Remove unused index.php endpoint

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
OpenAPI looks good

**Review by ChristophWurst — APPROVED** [review]
Sure

**Comment by nickvergessen** [comment]
Backport in https://github.com/nextcloud/server/pull/41963

**Pull request merged**
