### PR TITLE
Fix link share avatar icon

### LINKED ISSUE #23908: Link share sidebar entry has overlapped letter
On master:
image

On NC 20.0.0.1 it looks fine.

Regression might be due to recent changes in nextcloud-vue

### PR DESCRIPTION
**Pull request by PVince81**
Use "icon-class" instead of "class" as this is how to tell the component
that we don't want initials displayed.

Fixes https://github.com/nextcloud/server/issues/23908

image

### CODE REVIEW

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Nop, that is by design https://nextcloud-vue-components.netlify.app/#/Components/Avatar

But the superposition of the two is fixed on https://github.com/nextcloud/nextcloud-vue/pull/1501
Just need to update the server deps

**Review by skjnldsv — APPROVED** [review]
Ah, I'm an idiot, I read the diff the other way!
yeeep, let get this in!  :rocket:

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Ha, but the missing primary colour is a regression then

**Comment by PVince81** [comment]
indeed. it's probably just by pure chance that it was blue before, probably because of the hash generated for the space character :smile:

I don't see any way to set the circle color directly, might need to extend the component for that.

**Comment by skjnldsv** [comment]
> indeed. it's probably just by pure chance that it was blue before

No it's not, this was deliberate :)
Source: I did it :stuck_out_tongue:

**Comment by PVince81** [comment]
@skjnldsv link to the code ? I didn't find what would make it explicitly blue. This is on 20.0.0:
image

so it seems to be the computed background value.

Anyway, I've pushed a quickfix now, sadly had to use v-deep to override the background color.
If this becomes a regular use case we can later look into adding a new property for setting a custom background color style string (not only rgb values but also CSS variables...)

**Comment by skjnldsv** [comment]
> Anyway, I've pushed a quickfix now, sadly had to use v-deep to override the background color.

It's fine for those cases :)

**Comment by skjnldsv** [comment]
> @skjnldsv link to the code ? I didn't find what would make it explicitly blue. This is on 20.0.0:

Can't find it, that was part of the specs.
But it's actually a bug then as it doesn't apply the primary! :see_no_evil: 

Nice catch then! :rocket:

**Review by skjnldsv — APPROVED** [review]

**Comment by PVince81** [comment]
seems I forgot to stop the watcher while building the production assets... (not the first time) rebuilding...

**Comment by PVince81** [comment]
```
% git fetch

% git rebase origin/master
Current branch bugfix/23908/fix-share-link-avatar is up to date.

% git status
On branch bugfix/23908/fix-share-link-avatar
nothing to commit, working tree clean

% MODULE=files_sharing make build-js-production

...

% git status

On branch bugfix/23908/fix-share-link-avatar
nothing to commit, working tree clean
```

Why?!

I'll try a full rebuild then

**Comment by PVince81** [comment]
had a stray "npm link" of nextcloud-vue

pushed again

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
