### PR TITLE
Use latest ca-bundle.crt from https://curl.haxx.se/docs/caextract.html

### PR DESCRIPTION
**Pull request by kesselb**
Looks like nextcloud uses a custom certificate store for connections through IClient. 

image

:see_no_evil:

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Makes sense - let me add a check for that to our CI system.

**Comment by MorrisJobke** [comment]
> let me add a check for that to our CI system.

14373

**Pull request merged**
