### PR TITLE
Fixed design zindex

### LINKED ISSUE #10512: Date picker is not accessible
When trying to set a expiration date for share links, the date picker is not accessible, since it is hidden behind the sidebar.

@nextcloud/designers

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #10512
Fix https://github.com/nextcloud/files_texteditor/issues/105

### CODE REVIEW

**Comment by skjnldsv** [comment]
@juliushaertl we should create a file where we have variables for every zindex stuff ^^'

**Review by rullzer — APPROVED** [review]

**Review by schiessle — APPROVED** [review]

**Comment by juliushaertl** [comment]
> we should create a file where we have variables for every zindex stuff ^^'

Yes! :+1: Good idea to have that together so we have a better overview.

**Comment by skjnldsv** [comment]
@juliushaertl you want to do that here or in a followup pr?

**Comment by juliushaertl** [comment]
I'd say a follow up. It is more an enhancement than an urgent bugfix right now. :wink:

**Pull request merged**
