### PR TITLE
Fix Spanish typo "segudos"

### PR DESCRIPTION
**Pull request by sim6**
```
sed -i 's/segudos/segundos/' apps/files_external/l10n/es_*.js*
```

### CODE REVIEW

**Comment by kesselb** [comment]
Thank you for reporting :+1: 

We are using Transifex to manage translations. Please join https://www.transifex.com/nextcloud/nextcloud/ to help. It's also possible to sign up with your GitHub account.

Translations are synced daily from Transifex to GitHub. Any change related to translation must be done there otherwise they are lost.

**Comment by sim6** [comment]
OK. Is there a way to do it quickly? Otherwise is tedious to join to each `es_*` team and change the string for each one.

**Comment by kesselb** [comment]
@rakekniven @Valdnet would you mind to answer the question?

**Comment by Valdnet** [comment]
You can download a file from Transifex with the translation. Change interesting text strings and send back separately for each section (application) of the translation.

**Comment by rakekniven** [comment]
For addition: section = resource (nomenclature at Transifex).

**Comment by sim6** [comment]
I'm sorry. How I can download a file or files with translations for all `es_*` languages?

**Comment by Valdnet** [comment]
You choose the source:

obraz

You click on and this window appears:

obraz

**Comment by sim6** [comment]
Sorry for the delay. When I click the resource a list of languages are loaded:
https://www.transifex.com/nextcloud/nextcloud/files_external/
How I can download all 18 Spanish dialects?

**Comment by Valdnet** [comment]
Each dialect must be downloaded separately.

**Comment by rakekniven** [comment]
Done it.

**Pull request closed without merging**
