### PR TITLE
Add appconfig to always show the unique label of a sharee

### PR DESCRIPTION
**Pull request by juliusknorr**
It is quite common in larger environments or in setups that use a lot of guest users that with sharing autocompletion the display name doesn't give enough hint on whom a file is shared with in the end. This PR adds a appconfig flag that can be set in order to always show the email or userid unique shareee label if this is wanted by the admin.

image

```
occ config:app:set files_sharing always_show_unique --value 'yes'
```

### CODE REVIEW

**Comment by juliushaertl** [comment]
As some additional note, in older versions we just had a tooltip on the avatar with the userid which was used as kind of a workaround for this, but with the new multiselect users cannot really see who they share a file to then.

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Pull request merged**
