### PR TITLE
[uc] Improve chunk upload AssemblyStream performance

### PR DESCRIPTION
**Pull request by icewind1991**
Downstreaming of https://github.com/owncloud/core/pull/26062

### CODE REVIEW

**Comment by nickvergessen** [comment]
Let me smash this, to be sure

**Comment by nickvergessen** [comment]
Ran the tests for big files, they still pass

**Comment by MorrisJobke** [comment]
I pushed the updated autoloader code. cc @rullzer

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
> I pushed the updated autoloader code. cc @rullzer

Ah ... @icewind1991 just pushed shortly before me 😄

**Comment by MorrisJobke** [comment]
> Ah ... @icewind1991 just pushed shortly before me 😄

Rebased to resolve the conflict

**Comment by rullzer** [comment]
LGTM

**Pull request merged**
