### PR TITLE
Register services early in case they might already be queried though other registrations

### PR DESCRIPTION
**Pull request by juliusknorr**
Otherwise services might not be resolved since they are registered too late

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by ChristophWurst** [comment]
:thinking: where is that a problem? Shouldn't the registration part be as lazy as possible? Like in a sense that nothing really is executed yet.

**Comment by juliushaertl** [comment]
> thinking where is that a problem? Shouldn't the registration part be as lazy as possible? Like in a sense that nothing really is executed yet.

Ideally yes, just found this when debugging https://github.com/nextcloud/deck/pull/2275 and thought it might be a good hardening to avoid possible issues in case app developers don't properly handle lazy registration like myself ;)

**Comment by ChristophWurst** [comment]
> At this very early stage of the process lifetime, no other apps nor all of the server components are ready. Therefore the app must not try to use anything except the API provided by the context.

https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html#nextcloud-20-and-later

:see_no_evil: so I would not see this as a hardening step. The premise of of the register and boot separation is to not have any assumptions about what's there in the early call of register.

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
:-1: as of https://github.com/nextcloud/server/pull/22727#issuecomment-688827967 :)

**Comment by juliushaertl** [comment]
Ok, let's close then :+1:

**Pull request closed without merging**
