### PR TITLE
Changes the Birthday calendar color to slightly brighter one

### PR DESCRIPTION
**Pull request by georgehrke**
As requested per https://github.com/nextcloud/calendar/pull/1551#issuecomment-545600513

### CODE REVIEW

**Review by tcitworld — APPROVED** [review]

**Comment by tcitworld** [comment]
Made me think of #17148 that’s still waiting :(

**Review by jancborchardt — APPROVED** [review]
You mean slightly _darker_, but yes looks nice! :) :yellow_heart:

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
