### PR TITLE
returns a 404 instead of exception if app is not installed - #13088

### LINKED ISSUE #13088: [ Nextcloud 15 ] : Social app missing trigger error about /.well-known/webfinger
### Steps to reproduce
1. Update nextcloud 14 to 15
2. Install Social app
3. Disable or uninstall social app

### Expected behaviour
There should be no error in the overview of administration page.

### Actual behaviour
There is the following error.

<details>
<summary>Error from Overview in Administration page</summary>
Security warnings & configuration

It is important for the security and performance of your instance that it is properly configured. In order to help you, your Nextcloud instance performs some automatic checks. For more information, please consult the related documentation.
There are some warnings about your configuration.

     The configuration of the web server does not reach "/.well-known/webfinger". You will find more information in the documentation.

Please consult the installation guides ↗ and check the log errors or warnings.

</details>

### Server configuration

**Operating system**: CentOs 7.6

**Web server:** httpd-2.4.6-88.el7.centos.x86_64

**Database:** mariadb-server-5.5.60-1.el7_5.x86_64

**PHP version:** php72

**Nextcloud version:** Nextcloud 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** From official site.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - bookmarks: 0.14.3
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 2.1.8
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 4.99.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - unsplash: 1.1.3
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "213.32.64.170"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/213.32.64.170",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "token_auth_enforced": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

I tried to fix .htaccess file with manual update and with the occ command to generate a new one but I'm not sure it had something to do with that.
I've already open topic on help.nextcloud.com : https://help.nextcloud.com/t/nextcloud-15-update-well-known-webfinger-impossible-to-reach/43082

I'm not alone in this case like you can see in the topic, I don't think it is a big issue but I report it anyway.

Sorry for bad enslish, not my native language.

### PR DESCRIPTION
**Pull request by ArtificialOwl**
Fixes #13088

### CODE REVIEW

**Comment by daita** [comment]
backport to 15 will be needed

**Comment by juliushaertl** [comment]
As discussed with @daita we use a 501 Not implemented now, so we can properly check if the url rewrite is properly setup even if there is no app hooking into the webfinger endpoint.

**Comment by juliushaertl** [comment]
Would be good to get this in, so we probably can get the backport for stable15 in 15.0.1.

**Review by rullzer — APPROVED** [review]
Fine by me

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
