### PR TITLE
use the configured forwarded headers for the setup check

### PR DESCRIPTION
**Pull request by icewind1991**
instead of always checking against the same header (which isn't even the correct one 🙈 )

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Comment by kesselb** [comment]
Picked `X-Forwarded-Host` to prevent a false positive on plesk hostings: https://github.com/nextcloud/server/pull/14261

I don't have a hosting with plesk to try. But the change itself looks good.

**Review by kesselb — APPROVED** [review]

**Comment by rullzer** [comment]
Shit merged to soon. Let me revert

**Comment by rullzer** [comment]
@icewind1991 can you resubmit?

**Pull request merged**
