### PR TITLE
Fix app navigation flickering on hover

### PR DESCRIPTION
**Pull request by alion300**
i change the file by xaviterando done and fix
and i will do pull request to the solution becouse xavirando did pull request to him self

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Ref #13263

**Comment by ChristophWurst** [comment]
@nickvergessen isn't that the bug that annoyed you? ;)

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Thanks a lot for your contribution @alion300  :rocket: 

There is only one thing missing - you need to add a sign-off message to the commits you made. Read more about this in https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work

cc @xaviterando As he was the original author of the change.

**Comment by juliushaertl** [comment]
CI failure unrelated

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by jancborchardt** [comment]
Great fix @alion300! :) Welcome to Nextcloud – any design fixes are always very welcome, if you like have a look at our [Design page](https://nextcloud.com/design/) for more pointers. :tada:

**Pull request merged**
