### PR TITLE
Make the ShareAPIController strict

### LINKED ISSUE #9279: Cant share files to users with integer uid and without display name
```
TypeError: Return value of OC\\User\\Database::getDisplayName() must be of the type string, integer returned at \/home\/nickv\/Nextcloud\/14\/server\/lib\/private\/User\/Database.php#226
```

In https://github.com/nextcloud/server/blob/373a1d53918db011ca36351ad8e5240567ad999c/lib/private/User/Manager.php#L257 the user id is the array key. PHP autotransforms it to an int, therefor from here on the user has an integer uid and falling back to it in https://github.com/nextcloud/server/blob/8edbeb159e4aaea295a18eb7f9fe2329535d1e22/lib/private/User/Database.php#L226 fails, because int !== string...

cc @rullzer @MorrisJobke

### PR DESCRIPTION
**Pull request by rullzer**
With types we can force php to not cast a full nummeric user to an int.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by nickvergessen** [comment]
Doesnt fix the issue... The sharees endpoint is the oroblem

**Comment by rullzer** [comment]
I'll look at the failing tests tomorrow

**Comment by rullzer** [comment]
@nickvergessen aaah right. then lets maket that strict as well ;)

**Review by icewind1991 — APPROVED** [review]

**Comment by nickvergessen** [comment]
Removed the fixes so it doesn't autoclose.
Merging

**Pull request merged**
