### PR TITLE
Gmright2

### PR DESCRIPTION
**Pull request by bitokenja3**
The gmright2 create by george makulu

### CODE REVIEW

**Comment by kesselb** [comment]
Hi @bitokenja3, what is this pull request about?

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Unclear what this PR is about

**Comment by rullzer** [comment]
Sorry for closing but I always get triggered when i see that many files changed without explanation.
So basically joining @kesselb and @LukasReschke in what does it do and why?

**Comment by jospoortvliet** [comment]
So it compresses all the images. I'd say that is a step that should not happen in the repo, but when packaging Nextcloud (and it might already happen).

**Comment by szaimen** [comment]
It doesn't looks like it is compressing the images to me but just reformatting the svg code...

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/3f5473d86f99da9cdc07cc0c94981ba125200a05/contribute/Gmright.io/flap.io

**Comment by bitokenja3** [comment]
I'm sorry for this late reply but this pull request is base on the version of  security vulnerabilities has change , that's why I pull this request snyk as change the value of each vulnerabilities

**Comment by bitokenja3** [comment]
Vulnerable versions it helps to scan and ready all the  dependence version which it lead to create new vulnerabilities , this is important to understand  example `Dependabot cannot update immer to a non-vulnerable version`

**Pull request closed without merging**
