### PR TITLE
Fix user status emoji picking

### LINKED ISSUE #34208: User status picker does not show selected emoji anymore
Peek 2022-09-23 09-08

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/34208

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by blizzz** [comment]
master is still 26 :)

**Comment by skjnldsv** [comment]
> master is still 26 :)

This is to make sure we remember this needs to be in 25

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
