### PR TITLE
Build weather-status to solve design issues

### PR DESCRIPTION
**Pull request by julien-nc**
Weather status had to be built again. Padding issues and button background size issues are now gone. Too bad those design issues are in beta3 :smile:.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Build is still not happy :wink:

**Comment by eneiluj** [comment]
> Build is still not happy wink

@juliushaertl I don't get why. Any idea?

**Comment by skjnldsv** [comment]
> @juliushaertl I don't get why. Any idea?

here you go

**Pull request merged**
