### PR TITLE
handle stream wrappers in SeekableHttpStream

### PR DESCRIPTION
**Pull request by icewind1991**
When the `SeekableHttpStream`'s `openCallback` returns a stream wrapper, the `stream_get_meta_data` call returns the wrapper, not the http headers we're looking for.

This changes it to try and get the source of the stream so we can get the http headers.

Additionally I'll look if it's possible to make the wrappers transparent for `stream_get_meta_data`

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by juliusknorr — APPROVED** [review]

**Comment by PVince81** [comment]
- [ ] backports down to stable20
- [ ] release stable20 ??
- [ ] communicate to AMX somehow ?

**Pull request merged**
