### PR TITLE
Do not show social menu when there is no link share

### PR DESCRIPTION
**Pull request by rullzer**
Easy one...

1. Have a socialsharing plugin enabled
2. open the share dialog

before: weird ...
after: no weird ...

### CODE REVIEW

**Review by schiessle — APPROVED** [review]
Works! 😃

**Comment by MorrisJobke** [comment]
What about crewmating alink while clicking on it? 😉 Cc @nextcloud/designers for a nice UX

**Comment by rullzer** [comment]
@MorrisJobke not in this PR. This is to fix it. If we want a differnt flow lets do that in an issue.

**Review by ChristophWurst — APPROVED** [review]

**Comment by jancborchardt** [comment]
@MorrisJobke yep, please open an issue with what you mean :)

**Comment by MorrisJobke** [comment]
> @MorrisJobke yep, please open an issue with what you mean :)

There it is: #4196

**Pull request merged**
