### PR TITLE
cache isCached state for scss resources

### PR DESCRIPTION
**Pull request by icewind1991**
This saves a significant amount of filecache operations when loading a page.

This extra caching layer is disabled when debug mode is enabled to ensure it doesn't get in the way of development

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Code make sense! :)

**Review by MorrisJobke — APPROVED** [review]
Teste and works 👍

**Comment by MorrisJobke** [comment]
Unit tests fail:

```

581s
127
1) Test\Template\SCSSCacherTest::testIsCachedNoFile
581s
128
TypeError: Argument 2 passed to OC\Template\SCSSCacher::isCached() must be of the type string, object given
581s
129

581s
130
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:181
581s
131
/drone/src/github.com/nextcloud/server/tests/lib/TestCase.php:210
581s
132
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:262
581s
133

581s
134
2) Test\Template\SCSSCacherTest::testIsCachedNoDepsFile
581s
135
TypeError: Argument 2 passed to OC\Template\SCSSCacher::isCached() must be of the type string, object given
581s
136

581s
137
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:181
581s
138
/drone/src/github.com/nextcloud/server/tests/lib/TestCase.php:210
581s
139
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:283
```

**Comment by MorrisJobke** [comment]
> Let me check if I can fix the tests.

Fixed them. They worked locally. Let's wait for CI then.

**Pull request merged**
