### PR TITLE
Bump phpunit

### PR DESCRIPTION
**Pull request by rullzer**
Use the latest phpunit (which supports 5.6 and 7.0)

Fixed getMock warnings. More need to be fixed. But that is for a later PR.

Lets see what CI says.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I rebased this to fix a conflict.

**Comment by MorrisJobke** [comment]
And the next conflict ... I will rebase

**Comment by MorrisJobke** [comment]
Rebased :)

**Comment by rullzer** [comment]
@MorrisJobke can you also review ;)?

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
cc @nickvergessen @LukasReschke

**Comment by nickvergessen** [comment]
Hardcore :see_no_evil: :+1:

**Pull request merged**
