### PR TITLE
fix(files_sharing): fix sharing status indicator side after component update

### PR DESCRIPTION
**Pull request by skjnldsv**
| Before | After |
|:---------:|:------:|
|||

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Fine by me but wondering why this is needed

**Review by nfebe — APPROVED** [review]

**Comment by skjnldsv** [comment]
> Fine by me but wondering why this is needed

It is in the commit comments :)

> Seems like the components now have max-height/width set too

**Comment by skjnldsv** [comment]
`files/files_copy-move.cy.ts` also failing on master

**Comment by skjnldsv** [comment]
Backport in https://github.com/nextcloud/server/pull/42735

**Pull request merged**
