### PR TITLE
added CORS skip if session was created by AppAPI

### PR DESCRIPTION
**Pull request by bigcat88**
Related to: cloud-py-api/app_api/issues/80

This PR is about for the discussion, how to implement it in a right way.

### CODE REVIEW

**Comment by bigcat88** [comment]
Changes in AppAPI related to this: cloud-py-api/app_api/pull/81

After merge of this and backport to 27 we can publish AppAPI in the AppStore, and say all is working starting from 27.1.2

**Comment by julien-nc** [comment]
Maybe we don't need this. We don't have to support non-OCS endpoints in the app ecosystem.
WDYT @AndyScherzinger @nickvergessen ?

**Comment by bigcat88** [comment]
Just to clarify why I propose to add the support:


1. These all are not OCS, but RestAPI:

* https://nextcloud-bookmarks.readthedocs.io/en/latest/
* https://github.com/nextcloud/notes/blob/main/docs/api/v1.md
* https://nextcloud.github.io/cookbook/dev/api/0.1.0/index.html#/Misc/get_api_v1_config
* https://nextcloud.github.io/news/

2. We can easy add support for them, without breaking any existing stuff(if I didn't miss anything)

**Comment by julien-nc** [comment]
@bigcat88 You're right, those APIs are not just internal but made to be used by clients. It would be nice to be able to use them in external apps.

**Comment by blizzz** [comment]
master is 28

**Comment by bigcat88** [comment]
> master is 28

why this can not be backported to 27.1.2?

**Comment by nickvergessen** [comment]
This PR targets master, so the milestone must be what master is which is 28.
Backporting can still be done, and then the backport PR will have a 27.x.y milestone assigned.

**Comment by DaphneMuller** [comment]
@AndyScherzinger could you perhaps help us with merging this in the right milestone? 27.1.2

**Comment by nickvergessen** [comment]
> could you perhaps help us with merging this in the right milestone? 27.1.2

Just needs the backport bot summoned. Then it will be backported to stable27 and be part of 27.1.3 (.1.2 is already being released at the moment).

But first CI needs fixing:
grafik

**Comment by AndyScherzinger** [comment]
@DaphneMuller what @nickvergessen said, so when this is merged (for 28) the already requested backport bot (thanks to nick) will take care of the backport and will also assign the right v27.1.x version number. 👍

**Review by AndyScherzinger — APPROVED** [review]

**Comment by bigcat88** [comment]
Done. Cypress errors looks unrelated to this, as the same Cypress errors are currently in other PRs.

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Cypress errors looks unrelated to this

On this PR all cypress requests fail in "before", so it can't even log in.
Are we sure it's unrelated?

**Comment by bigcat88** [comment]
> > Cypress errors looks unrelated to this
> 
> On this PR all cypress requests fail in "before", so it can't even log in. Are we sure it's unrelated?

it was unrelated, now CI is green

**Pull request merged**
