### PR TITLE
fix(files): Adjust Cache::searchQuery() parameter name to match interface

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

https://github.com/nextcloud/server/blob/bcb4e781a407798ef9d071dc3a15a1d0ac9e0e8d/lib/public/Files/Cache/ICache.php#L237

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by susnux — APPROVED** [review]
Is there no psalm warning for this?

**Comment by provokateurin** [comment]
There is, but it was hidden by the baseline :/

**Comment by provokateurin** [comment]
Can someone force merge? Cypress fails hard for unknown reason and this change can not possibly affect cypress results anyway.

**Pull request merged**
