### PR TITLE
add icon if no versions are available

### LINKED ISSUE #2476: Nice emptycontent for »No previous versions available«
Currently the emptycontent view of versions in the sidebar is very bland:
capture du 2016-12-02 14-59-23

Instead we should use the emptycontent view like for Comments:
```
<div class="emptycontent">
  <div class="icon-history"></div>
  <p>No prevous versions available</p>
</div>
```

@schiessle currently only text can be used there. Can you change it so we can put that HTML in there?

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/nextcloud/server/issues/2476

vrsions

cc @jancborchardt

### CODE REVIEW

**Comment by mjobst-necls** [comment]
I don't like the revert icon in case that no version is available.

**Comment by MorrisJobke** [comment]
> Which icon set is used by nextcloud?

Our own. @jancborchardt and @babelouest did them.

**Comment by MorrisJobke** [comment]
I like it - at least it is better than before. Maybe @nextcloud/designers can come up with a better icon if wanted.

👍

**Comment by skjnldsv** [comment]
👍 Nice!

**Comment by mjobst-necls** [comment]
@MorrisJobke @schiessle  Maybe, instead of using another icon, we could signalize a impossible revert with a red color - maybe a dark red color like this:

410b6b9c-b8a6-11e6-8e4d-7faf107fa06f

**Comment by skjnldsv** [comment]
I disagree, it doesn't fit the nextcloud design guidelines :)

**Comment by mjobst-necls** [comment]
Only on mouse over? Where are the design guidelines? Link?

**Comment by MorrisJobke** [comment]
> Only on mouse over?

Why adding this? There is no interaction possible with this icon and therefore changing it on hover would be weird.



> Where are the design guidelines? Link?

I guess @skjnldsv meant the overall design. Everything is meant to be in the same look and then you open the versions and there is out of the sudden a red icon for the empty content message. All other empty content messages are in the same shade of black.

**Comment by MorrisJobke** [comment]
I will merge this for now. 

@mjobst-necls We can discuss the other stuff independent from this ticket here ;)

**Comment by jancborchardt** [comment]
Thanks @schiessle, exactly what I meant!

@mjobst-necls that icon-history is the icon for versions. It’s also used for the revert action for the ones in the list.

**Comment by mjobst-necls** [comment]
@jancborchardt Okay, now I understand. This icon is the history icon and also used for revert action. It was a little bit confusing, because I just know this icon as revert action. That's why I proposed to color this icon red due to inform the user that revert is not possible.

**Pull request merged**
