### PR TITLE
Fix Axios CSRF token update

### PR DESCRIPTION
**Pull request by ChristophWurst**
I found a bug in the `nextcloud-axios` (now `@nextcloud/axios`) package: we read the `OC.requesttoken` just once. But the token can actually change over time.

As there is no simple solution to intercept *every* request with Axios (only PUT, POST, DELETE and PATCH), I updated the package (and `@nextcloud/auth`) to listen to an event on the new event bus.

The server now emits the events so that other modules that need the token can stay in sync.

This PR is split into two parts

* Emit the CSRF token change event
* Update to `@nextcloud/axios` which listens to the event (via `@nextcloud/auth`) and thus always uses the correct token

---

To test this PR you can either wait for the CSRF token to expire or just run ``_nc_event_bus.emit('csrf-token-update', {token: 123})``. On the apps page, for example, you should see 412 errors if you emit an invalid token.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
I like it!

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
```
modified: apps/accessibility/js/accessibility.js
12 | modified: apps/accessibility/js/accessibility.js.map
13 | modified: apps/oauth2/js/oauth2.js
14 | modified: apps/oauth2/js/oauth2.js.map
15 | modified: apps/settings/js/vue-settings-admin-security.js
16 | modified: apps/settings/js/vue-settings-admin-security.js.map
17 | modified: apps/settings/js/vue-settings-apps-users-management.js
18 | modified: apps/settings/js/vue-settings-apps-users-management.js.map
19 | modified: apps/settings/js/vue-settings-personal-security.js
20 | modified: apps/settings/js/vue-settings-personal-security.js.map
21 | modified: apps/twofactor_backupcodes/js/settings.js
22 | modified: apps/twofactor_backupcodes/js/settings.js.map
23 | modified: apps/workflowengine/js/workflowengine.js
24 | modified: apps/workflowengine/js/workflowengine.js.map
25 | modified: core/js/dist/login.js
26 | modified: core/js/dist/login.js.map
27 | modified: core/js/dist/main.js
28 | modified: core/js/dist/main.js.map
29 | modified: core/js/dist/maintenance.js
30 | modified: core/js/dist/maintenance.js.map
```

I don't understand why :thinking:

**Comment by skjnldsv** [comment]
> I don't understand why

Let's try if the lockfile was an issue, since tests are using `npm ci` but we aren't in the makefile nor the npmbuildbot :thinking:

**Comment by skjnldsv** [comment]
Built it again and suddenly it works --"

**Pull request merged**
