### PR TITLE
User management layout improvements

### PR DESCRIPTION
**Pull request by jancborchardt**
- fix list height and border to be as in Files
- improve look of Add group flow

Before
capture du 2016-10-18 12-18-09

After
capture du 2016-10-18 12-17-10

Much nicer look, better whitespace. A long overdue improvement here ;) Please review @nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
👍 
Much clearer!

**Comment by Espina2** [comment]
Nice improvement.

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
CI job is pending because I recently played around with workers and this seem to have failed here.

**Comment by MariusBluem** [comment]
I'm lovin it 🍟👍🏼👍🏼

**Pull request merged**
