### PR TITLE
Fix naming of languages

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fix one point in #2134 - cc @jancborchardt 
* done together with https://github.com/nextcloud/docker-ci/commit/1df73e3ac4168a8cf7a0cd6b84971943736101c0
* this basically only cleans up the code - I moved all the names of the languages to Transifex and fetched all translations for the settings l10n
* uses the languages available in core/l10n to render this list anyways: https://github.com/nextcloud/server/blob/0245dd7221b6901aab0118688a1a16328248d530/lib/private/L10N/Factory.php#L364

Now looks like this:

bildschirmfoto 2016-11-30 um 15 20 13

Instead of what it looked like before (with many not really translated languages):

bildschirmfoto 2016-11-30 um 15 20 27
bildschirmfoto 2016-11-30 um 15 20 34
bildschirmfoto 2016-11-30 um 15 20 37

cc @rullzer @nickvergessen @LukasReschke

### CODE REVIEW

**Comment by rullzer** [comment]
👍

**Comment by jancborchardt** [comment]
@MorrisJobke so before there were a lot more languages in the list, without proper title but also some with a good title. Do we now do the cutoff by translation percentage or what? If so, what percentage do we cut off at?

Because you could argue that even having 30% or so translated is better than nothing, and then we have the »Help translate« link to get involved.

**Comment by MorrisJobke** [comment]
> @MorrisJobke so before there were a lot more languages in the list, without proper title but also some with a good title. Do we now do the cutoff by translation percentage or what? If so, what percentage do we cut off at?

We cut off at 50% of translation of `core/` l10n. Most of the languages in there were only dummy leftovers. And they will reappear once the translation percentage raises.

**Comment by MorrisJobke** [comment]
> We cut off at 50% of translation of core/ l10n. Most of the languages in there were only dummy leftovers. And they will reappear once the translation percentage raises.

https://www.transifex.com/nextcloud/nextcloud/core/

Just check it out. But the actual percentage has nothing to do with this PR. This only cleans up. So feel free to +1 this one here and I can change the percentage to a lower value over in the tranifex script.

**Comment by LukasReschke** [comment]
LGTM

**Comment by jancborchardt** [comment]
@MorrisJobke ah ok, it was only dummies. Thanks!

**Pull request merged**
