### PR TITLE
Redirect to default page after login

### LINKED ISSUE #560: Wrong redirect after login
See https://github.com/owncloud/core/pull/25600

### PR DESCRIPTION
**Pull request by schiessle**
upstream fix https://github.com/owncloud/core/pull/25600
Fix #560

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@schiessle What about the backport?

**Comment by MorrisJobke** [comment]
> @schiessle What about the backport?

#599

**Pull request merged**
