### PR TITLE
Move updatenotifications to unified webpack

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by juliushaertl** [comment]
@rullzer I've pushed better a fix for the hot reload issue, which causes differences in the bundled files. The actual issue is that webpack doesn't set the NODE_ENV variable when setting the mode to 'production' so vue-loader was still behaving as if it was in development mode. (https://github.com/webpack/webpack/issues/7074) Setting the environment variable as well seems to fix that: https://github.com/nextcloud/server/pull/14232/commits/b6335e9b3de347d779bfc3c465da4be2317046b1

**Comment by skjnldsv** [comment]
@juliushaertl does this impact the bundle size ? Shall we edit all of our configs?

**Comment by rullzer** [comment]
@juliushaertl nice catch. Lets fix this in a seperate PR so we keep it clean. See https://github.com/nextcloud/server/pull/14258

**Comment by juliushaertl** [comment]
> @juliushaertl does this impact the bundle size ? Shall we edit all of our configs?

I didn't found any huge difference, for the server bundles it was like <1kb less.

**Comment by rullzer** [comment]
Rebased. Ready to get in!

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
