### PR TITLE
Floating files header

### LINKED ISSUE #3872: Table header in file list should be always visible
Imagine you have a large file listing and you are scrolling down the road (the table header is vanished) and now you want to change the sort order, you would have to scroll back to the top.
I think it would be nicer if the table header is always visible to allow a quicker change of the sorting order.

What do you think @jancborchardt ?

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #3872 
Capture d’écran_2019-04-30_09-20-31

Not compatible with ie, ie will behave as it currently is.

@nextcloud/designers

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:dancer:

**Review by juliusknorr — DISMISSED** [review]
Nice, but this seems to break the file list in IE11 (width is not calculated properly):

image

**Comment by skjnldsv** [comment]
> Nice, but this seems to break the file list in IE11 (width is not calculated properly):

Oh thanks!! I did not noticed! :see_no_evil:

**Comment by tobiasKaminsky** [comment]
You are my hero of the day! @skjnldsv

**Comment by jancborchardt** [comment]
I’m not sure about this. As you see in your screenshot, on small screen sizes this will result in 3 permanent bars sticky on top. This will be very bad espeacially for people who receive shared folder links and open it on mobile.

Probably a better solution is to:
- Get rid of the table header bar for sorting. Instead have one "Sort" icon on the top right next to the view switcher where people can switch between sorting methods much like in [the Android app](https://github.com/nextcloud/android/pull/575):


- When you initiate multiselect, show the multiselect bar _instead_ of the breadcrumb bar, just like Android does.

That way we fix the problem _and_ simplify the interface in one go. What do you think?

**Review by jancborchardt — CHANGES_REQUESTED** [review]
See comment :)

**Comment by skjnldsv** [comment]
@jancborchardt this is a simple fix for now I'd say! :)
If we want to go into a more complicated version (as in me not touching the terrible legacy code :grin:), we should wait for a new view of the files app I think :wink:

**Comment by jancborchardt** [comment]
> this is a simple fix for now I'd say! :)

It does impact the design heavily though, as mentioned. :) So then I’d rather say let’s not do it.

> If we want to go into a more complicated version (as in me not touching the terrible legacy code grin), we should wait for a new view of the files app I think wink

;D If that is ever going to happen?

**Comment by skjnldsv** [comment]
> It does impact the design heavily though, as mentioned. :) So then I’d rather say let’s not do it.

I'll let you announce it to @tobiasKaminsky  then ;)

**Comment by jancborchardt** [comment]
Sorry @tobiasKaminsky! :) But soon™ we will get a nice new Files app in Vue – I guess. ;D

**Comment by juliushaertl** [comment]
> I’m not sure about this. As you see in your screenshot, on small screen sizes this will result in 3 permanent bars sticky on top. This will be very bad espeacially for people who receive shared folder links and open it on mobile.

I still think this is a really good enhancement. The 3 bars will be visible on page load anyway. How about making this change desktop only? I agree this could be better, but on a small screen like 320x480 there is still about 70% space available for the actual file list even with 3 sticky headers.

**Comment by tobiasKaminsky** [comment]
> Sorry @tobiasKaminsky! :) But soon™ we will get a nice new Files app in Vue – I guess. ;D

Wasn't it you who said that small steps are better? So having this in (with a fix like Julius described) and then sometimes later changing it is maybe better/easier than trying to do all in a big rush?

**Comment by jancborchardt** [comment]
> How about making this change desktop only?

Sure, that sounds good @juliushaertl! :)


> Wasn't it you who said that small steps are better? So having this in (with a fix like Julius described)

Yes, indeed. So I’m happy about the additional suggestion. Because otherwise this small step would have also been a step back (as described above). :)

:heart:

**Comment by skjnldsv** [comment]
Done @jancborchardt

**Comment by MorrisJobke** [comment]
I added a fix for Safari. 😉

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by tobiasKaminsky** [comment]
When I scroll down a bit and then see that sort is wrong and I click on e.g. name, the list jumps to top again.
I think it should stay at the current position?

**Comment by MorrisJobke** [comment]
> When I scroll down a bit and then see that sort is wrong and I click on e.g. name, the list jumps to top again.
> I think it should stay at the current position?

Open a new ticket please.

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/server/issues/15438

**Pull request merged**
