### PR TITLE
Do not process the same shares twice

### PR DESCRIPTION
**Pull request by skjnldsv**
Shares are processed twice. Vue is smart to not replace the whole data.
So when it's updated again, the share objects are changed but because the share id is the same, vue don't care and does not refresh everything (specifically the [reactive state](https://github.com/nextcloud/server/blob/f9ff454784cc135fe0b59060b4e88c705e0fe69b/apps/files_sharing/src/mixins/SharesMixin.js#L67)) and the objects references break....

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
YEEHAA
Works again!

**Review by gary-kim — APPROVED** [review]
:tada:

**Comment by skjnldsv** [comment]
I'm wondering if we should backport :thinking:

**Comment by MorrisJobke** [comment]
> I'm wondering if we should backport 🤔

Let's leave it in 19 for now.

**Pull request merged**
