### PR TITLE
Add white version of the calendar.svg icon

### PR DESCRIPTION
**Pull request by pixelipo**
There's no reason for not including it and it is needed for Deck app in nextcloud/deck#189

@nextcloud/designers @juliushaertl 

Signed-off-by: Marin Treselj <marin@pixelipo.com>

### CODE REVIEW

**Review by jancborchardt — COMMENTED** [review]
We need to keep the viewbox attribute though, so all icon resizing in the apps menu and app management works on Firefox, right? cc @MorrisJobke

**Comment by pixelipo** [comment]
@jancborchardt then what about [core/img/places/files-dark.svg](https://raw.githubusercontent.com/nextcloud/server/master/core/img/places/files-dark.svg) ?

**Comment by MorrisJobke** [comment]
> We need to keep the viewbox attribute though, so all icon resizing in the apps menu and app management works on Firefox, right? cc @MorrisJobke

Correct



> @jancborchardt then what about core/img/places/files-dark.svg ?

Please add it there as well. We had weird rendering issues in firefox, especially if the view box is not there and the path is defined in a bigger scope, then firefox misrendered it

**Comment by pixelipo** [comment]
Ok, now all the places icons (apart from `home.svg` - that is in #5229 ) have viewport. I've also cleaned up some extra styles.

**Comment by juliushaertl** [comment]
We should also introduce a class icon-calendar like there is one for icon-calendar-dark already.

**Comment by jancborchardt** [comment]
Yup, what @juliushaertl said also - you can add that in the core/css/icons.scss

**Review by MorrisJobke — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by jancborchardt** [comment]
Failures unrelated, merging. :)

**Pull request merged**
