### PR TITLE
CSP: Allow fonts to be provided in data

### PR DESCRIPTION
**Pull request by rullzer**
Required for the dark mode of the vue components.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Comment by skjnldsv** [comment]
```
7) Test\AppFramework\Http\ContentSecurityPolicyTest::testGetPolicyDisallowScriptDomainMultipleStacked
Failed asserting that two strings are identical.

```

**Comment by rullzer** [comment]
Right. I'll fix the tests :see_no_evil:

**Comment by raimund-schluessler** [comment]
Could this be backported to stable14 as well? Otherwise some apps will have to require NC15 just for the datepicker component.

**Comment by rullzer** [comment]
@raimund-schluessler I discussed this with @skjnldsv. THe trouble is of course that if an app is 14 compliant. It might still do :boom: if a user is not on the latest patch level...

**Comment by raimund-schluessler** [comment]
> 
> 
> @raimund-schluessler I discussed this with @skjnldsv. THe trouble is of course that if an app is 14 compliant. It might still do 💥 if a user is not on the latest patch level...

True, but that is also the case for 15.

**Comment by skjnldsv** [comment]
let's continue on https://github.com/nextcloud/nextcloud-vue/pull/193 ?

**Pull request merged**
