### PR TITLE
Sign in form best practice

### PR DESCRIPTION
**Pull request by kevin147147**
This should enable the registration app to set a new-password autocomplete field.

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hum, this was specifically here so tthat we do not allow the browser's auto-completion. I don't understand what this has to do with the registration app, could you explain the issue a bit further please? :)

**Comment by kevin147147** [comment]
This does not affect autocomplete off setting. If we also set autocomplete=“new-password” in the registration app. The browsers are able to generate safe new passwords for users and not be confused about the type of input field.

**Comment by skjnldsv** [comment]
I have no clue about this tbh. :shrug:

**Review by MorrisJobke — APPROVED** [review]
Fine with me 👍 

See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete for the details

**Comment by kevin147147** [comment]
@skjnldsv Maybe look also at this file from owncloud. They are using the same autocomplete fields:
https://github.com/owncloud/web/blob/83bdd1fc5410cdc6e3a3502677c5305eb566fab9/tests/acceptance/pageObjects/ocisLoginPage.js

**Review by blizzz — APPROVED** [review]

**Comment by szaimen** [comment]
@kevin147147 please rebase

**Comment by blizzz** [comment]
obsoloted by https://github.com/nextcloud/server/pull/33781

**Pull request closed without merging**
