### PR TITLE
better cleanup of filecache when deleting an external storage

### LINKED ISSUE #26842: Storage and Filecache entries not be cleaned up upon global storage deletion
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have an external global storage configured, enabled for users and/or groups. No global auth, but for instance Login Credentials
2. Delete this storage

### Expected behaviour

Storage should be deleted and relevant database tables cleaned up

### Actual behaviour

- InsufficientDataForMeaningfulAnswerException is being logged, with message "No login credentials saved"
- Tables are not being cleaned up

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
  "reqId": "QKjSuvn0KpR7zWY4VuhI",
  "level": 3,
  "time": "2021-04-30T10:47:01+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "master",
  "app": "files_external",
  "method": "DELETE",
  "url": "/master/index.php/apps/files_external/globalstorages/41",
  "message": {
    "Exception": "OCA\\Files_External\\Lib\\InsufficientDataForMeaningfulAnswerException",
    "Message": "No login credentials saved",
    "Code": 2,
    "Trace": [
      {
        "file": "/srv/http/nextcloud/master/apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php",
        "line": 105,
        "function": "getCredentials",
        "class": "OCA\\Files_External\\Lib\\Auth\\Password\\LoginCredentials",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/apps/files_external/lib/Service/StoragesService.php",
        "line": 565,
        "function": "manipulateStorageConfig",
        "class": "OCA\\Files_External\\Lib\\Auth\\Password\\LoginCredentials",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/apps/files_external/lib/Service/StoragesService.php",
        "line": 534,
        "function": "getRustyStorageIdFromConfig",
        "class": "OCA\\Files_External\\Service\\StoragesService",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/apps/files_external/lib/Service/StoragesService.php",
        "line": 525,
        "function": "deleteStoragesAndFilecacheEntries",
        "class": "OCA\\Files_External\\Service\\StoragesService",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/apps/files_external/lib/Controller/StoragesController.php",
        "line": 375,
        "function": "removeStorage",
        "class": "OCA\\Files_External\\Service\\StoragesService",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 218,
        "function": "destroy",
        "class": "OCA\\Files_External\\Controller\\StoragesController",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 127,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/srv/http/nextcloud/master/lib/base.php",
        "line": 998,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/srv/http/nextcloud/master/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/srv/http/nextcloud/master/apps/files_external/lib/Lib/Auth/Password/LoginCredentials.php",
    "Line": 94,
    "Hint": "Storage is temporarily not available",
    "CustomMessage": "No login credentials saved"
  },
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0",
  "version": "22.0.0.3"
}

```
</details>

The reason is that we do not even try to delete the storage per applicable user: https://github.com/nextcloud/server/blob/master/apps/files_external/lib/Service/StoragesService.php#L483-L484

Also some storages need to have auth credentials being provided in the constructor. This cannot always be satisfied (e.g. Login credentials on Session),  but should not be necessary for removing the storage.

### PR DESCRIPTION
**Pull request by icewind1991**
this way it can delete the cache entries even with per-user credentials

Fixes #26842

### CODE REVIEW

**Review by blizzz — COMMENTED** [review]
I like the simplification. Should the deletes not be within a transaction, though?

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Comment by icewind1991** [comment]
> I like the simplification. Should the deletes not be within a transaction, though?

makes sense, done

**Review by blizzz — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Tests fail now.

**Comment by MorrisJobke** [comment]
Still failing :/

**Comment by icewind1991** [comment]
CI happy

**Pull request merged**
