### PR TITLE
Don't influence toastify errors and always use white

### PR DESCRIPTION
**Pull request by nickvergessen**
Found while testing #23175 

Before | After
---|---
Bildschirmfoto von 2020-10-05 14-11-45 | Bildschirmfoto von 2020-10-05 14-11-14

### CODE REVIEW

**Review by marcoambrosini — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
God I hate this file, :sweat_smile:

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Pull request merged**
