### PR TITLE
Mount Profile view after DOMContentLoaded

### LINKED ISSUE #32187: [NC 24.0.0 RC2] l10n: There are no translated text strings
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is no translation of the text strings in the user profile:

obraz

In NC 23, the strings are displayed correctly.

### Steps to reproduce

1. Select the menu.
2. Select "View profile".

### Expected behavior

Translated text strings in your native language.

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
-
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

Nextcloud 24.0.0 RC2

### PR DESCRIPTION
**Pull request by artonge**
Fix https://github.com/nextcloud/server/issues/32187

### CODE REVIEW

**Comment by skjnldsv** [comment]
Yeah allright, two options i'd say:
image

1. We move the profile to a dedicated app in `server/apps`
2. We load the profile script after l10n

**Comment by skjnldsv** [comment]
1 should be best, but it's not a tiny amount of work, so I'd vote to get this in in the meantime

@Pytal any estimate on how much would be necessary to move `profile` into `/apps` ?

**Review by skjnldsv — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
works

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by Pytal** [comment]
> @Pytal any estimate on how much would be necessary to move `profile` into `/apps` ?

Never transferred a portion of server functionality into a separate server app so no idea :) ETA to 100% calibration of my dev time estimator device currently says "Unknown"

**Pull request merged**
