### PR TITLE
Fix password changes in link and mail shares

### PR DESCRIPTION
**Pull request by danxuliu**
This pull request fixes some issues with passwords in link and mail shares and extend the unit and integration tests for them.

For further details please refer to the commit messages :-)

### CODE REVIEW

**Comment by danxuliu** [comment]
Integration and acceptance test failures happen in _master_ too and are unrelated.

**Review by rullzer — APPROVED** [review]
Looks good.
And I'm quite confident with so many tests :P

**Review by ChristophWurst — APPROVED** [review]
I'm a simple reviewer. I see a high test-to-code ratio and I approve.

**Pull request merged**
