### PR TITLE
Sort deleted files by most recently deleted first

### PR DESCRIPTION
**Pull request by jancborchardt**
Currently when opening the deleted files, I see the oldest files first, which is strange. People should see the most recently deleted files first.

Disclaimer: Due to there being an error in my local instance which causes it to be impossible to delete files (not sure why, but separate issue) I couldn’t actually test this so I hope this is the correct place. :O

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by jancborchardt** [comment]
More reviews @MorrisJobke @gary-kim @kesselb maybe? :)

**Review by kesselb — APPROVED** [review]

**Review by gary-kim — APPROVED** [review]
Thank you for this. I was just starting to get annoyed of this :)

**Review by gary-kim — CHANGES_REQUESTED** [review]
Tests need to be adjusted: 
https://github.com/nextcloud/server/blob/e1a0b3f98fb28ec3d193f32a85dd77795baf88f7/apps/files_trashbin/tests/js/filelistSpec.js#L132

**Review by MorrisJobke — APPROVED** [review]
Code looks good and I fixed the tests 👍

**Review by gary-kim — APPROVED** [review]

**Pull request merged**
