### PR TITLE
Use correct input type for website url

### PR DESCRIPTION
**Pull request by coliff**
type="url"

REF: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

Signed-off-by: Christian Oliff christian@christianoliff.com

### CODE REVIEW

**Comment by juliushaertl** [comment]
Thanks for your pull request @coliff 

The change looks good to me. Can you add your signoff to the commit message? Otherwise the CI won't be happy. :wink:

**Comment by coliff** [comment]
Hi @juliushaertl - I made the change via Github.com (not command line) and don't think I can sign off on the commit message. Would it be possible for you to skip that part of the CI test?

**Comment by MorrisJobke** [comment]
> The change looks good to me. Can you add your signoff to the commit message? Otherwise the CI won't be happy. 😉

I guess it's fine for such minor changes.

**Review by MorrisJobke — APPROVED** [review]

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Only problem, the field is now shrinked: 
bildschirmfoto 2018-02-02 um 14 05 57

Just add the type=url to the SCSS here: https://github.com/nextcloud/server/blob/f8910ad898f6c24dcd5a7d14dff6d33dc754ea8f/settings/css/settings.scss#L140

**Comment by coliff** [comment]
Thanks @MorrisJobke for spotting that. I updated the scss file

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Failures are unrelated.

**Pull request merged**
