### PR TITLE
Cron should run every 5 mins

### LINKED ISSUE #1587: Documentation: backgroud jobs 15 min vs. 5 min
The background jobs configuration page [1] of my installation offers three options [german]: 
"AJAX
Eine Aufgabe bei jedem Laden einer Seite ausführen

Webcron
cron.php ist als Webcron-Dienst registriert, der die cron.php alle 15 Minuten per HTTP aufruft.

Cron
Nutzen Sie den System-Cron-Service um cron.php alle 15 Minuten aufzurufen. Die cron.php muss durch den Systemnutzer "wwwrun" ausgeführt werden. "

Both cron options mention a 15 minute cycle.
The corresponding documentation [2] mentions in the examples always a 5 minute cycle.
(e.g. "To run a cron job on a *nix system, every 5 minutes, under the default Web server user (often, www-data or wwwrun), you must set up the following cron job to call the cron.php script:")

I suggest to change the documentation to 15 minutes (6 hits on that page).

[1] https://<myhomepage>/index.php/settings/admin
[2] https://docs.nextcloud.com/server/16/admin_manual/configuration_server/background_jobs_configuration.html

### PR DESCRIPTION
**Pull request by nickvergessen**
Fixes https://github.com/nextcloud/documentation/issues/1587

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by blizzz** [comment]
tests please

**Comment by nickvergessen** [comment]
Done

**Review by blizzz — APPROVED** [review]

**Comment by kesselb** [comment]
cc @enoch85 @kyrofa

**Comment by enoch85** [comment]
Thanks @kesselb!

**Pull request merged**
