### PR TITLE
Gpg Interface and Emails

### PR DESCRIPTION
**Pull request by tacruc**
With an interface there is functionallity for gpg added to use it where ever you want. 
This interface is used to extend the Mailer, so that it is possible to send Gpg encrypted Emails. 

- [x] Sending encrypted emails
- [x] Sending encrypted and signed emails
- [x] create nextcloud_data/.gnupg  and server keys on setup or upgrade
- [x] allow users to upload public key
- [x] Gpg.php unit test
- [x] user.php unit test
- [x] DummyGpg to resolve hard dependency on gnupg
- [x] DummyGpg unit tests, is it needed?
- [x] update Message unit tests
- [ ] Fix phar error
- [ ] Fix checkers error
- [ ] Add a ci runner with gnupg enabled
- [ ] Add optional dependency on gnupg
- [ ] Remove the Key input fields in the settings, if gnupg is not there

## Pro Contra  Core Implementation or as an app with an hook on mailer::send()
Because the discussion came up on irc and on help.nextcloud.com I would like to collect the arguments. This is not a finished list and I'm happy to collect more arguments on both sides to get the best solution.
### Contra
- propably more maintenance do to more code on serverside,
- only few people uses gpg
- maybe new external dependency for only a few users
  - a dummy class which is loaded when external dependency is not avalible could be implemeted to avoid this
- ...
### Pro
- strate forward implementation and not a fix at the email output
- in some cases a bedder workflow is possible
  - share by email dialog
The app has to decide based on the email address, if the email should be encrypted or not. It could load the public key's from the contacts, and maybe (depending if the hook can provide the information, not clear to me) it could check if the contact is in a addressbook of the current user. But there is no simple way to give a feedback to the user if the email share is going to be encrypted or not. You could propably do some javascript hack to bring this information to the dialog, but the information for the encryption is going over a complitly different way than the email. Just to meet up in the and on the mailer:send hook.
- Gpg as an backend can be used for more than just sign and encrypt emails
  - Encrypt Notes
  - Implement a serverside GPG assistens in mails (usefull when trusting the server more than the pc in a internetcoffee for example)
  - Vertfy and sign Files
  - easy to use in every app
  - ...
- ...

## This PR is a basement for more Ideas:
Issue: https://github.com/nextcloud/server/issues/7310 and the Community
https://help.nextcloud.com/t/gpg-encrypted-emails-for-nextcloud/26129/4

### Contacts 
import public key's form contacts vCard and allow to upload them to the vCard
Server PR: https://github.com/nextcloud/server/pull/7997
Contacts App PR: https://github.com/nextcloud/contacts/pull/460

### Use the key from the Contacts to encrypt "share by email" emails
still allot to do
Server Branch: https://github.com/tacruc/server/tree/GPG-Share-By-eMail 

### More key managment features
There is an app https://github.com/tacruc/keymanager providing more features, but I'm not a desinger or a HTML/Javascript person so help with the interface would be appriciated
- [x] Providing an overview over all key's
- [x] showing contacts connected to a key (only in the json file)
- [x] suggesting contacts to connect with an key (only in the json file)
- [ ] deleting and revoking keys
- [ ] much more ...

### CODE REVIEW

**Comment by tacruc** [comment]
@georgehrke here is the PR of the first branch

**Comment by tacruc** [comment]
So allot of failings is due to ther merge commit 4e74cfcd58d50acf833a222a3f3492bac34bc0ff. I'm totaly failing in removing it.

**Comment by tacruc** [comment]
Could somebody pleas add the help needed label?

OK forgot about the new external dependency [gnupg]( http://php.net/manual/en/book.gnupg.php). 

There is a second implementation which could use as external dependency https://github.com/pear/Crypt_GPG. 
Which at the moment I'm using the fist one, but I think it shoudln't be to much work implementing the second one or supporting both. For nextcloud internal everything calls the IGpg class.

So which of the external dependency's is to one is to prefer? 
And how can it be added to the nextcloud dependencys?

**Comment by tflidd** [comment]
@jospoortvliet This is a first-time contributor seeking for help. Perhaps you can find somebody who could give a few hints and feedback if such an enhancement could be integrated in NC 14.

**Comment by tacruc** [comment]
Hi @rullzer,
thanks for your reply. I already expected this answer and can understand it, looking at the number of people using GPG. But I would still like this feature. 

My problem is a little bit, that I think the more code I move into an app, the less user friendly the behavior will get, because in the end one can't automate the decision which Email to encrypt and which key to use. This is a decision the user would have to make on the event triggering the email. 

So I think the changes to the email Interface, to enable not only to pass an email as address, but to pass a optional key, would be nice to integrate it in the core of the server.
All the stuff handling the key's and the email encryption can then be handled by an app.

So the solution with the max needed changes to the core would be something like the dummyGPG interface. Which than triggers the app. On the other extreme it would be an encryption gateway hooked, to the email send function, and does the automate the decision based on known public key's for the email address. In this extreme the app woudn't know which user has triggered the email, so having one user importing an public key for alice would probably end up in every user sending encrypted emails to alice, which could be used to brake the email system, when a bad user imports random public keys for all known email addresses.

I would be willing to split the code into a server and an app part, but I think the boarder should be chosen wise. If your interested we could have a talk or I could join the next hack week to work out wich is the best line to split.

**Comment by jospoortvliet** [comment]
@tacruc hey, if you still want to work on this, perhaps you join the conference so we can make some decisions? The hackweek would have been nice, too, of course - otherwise, just come to the next, there will be another before the end of the year for sure :rocket:

**Comment by tacruc** [comment]
@jospoortvliet I'm still interested in continuing  and already thought about the conference, but I can't make it this time. But hopefully I can make it to the next Hack week.

**Pull request closed without merging**
