### PR TITLE
Format Nextcloud Talk clients sessions.

### PR DESCRIPTION
**Pull request by Ivansss**
Format Nextcloud Talk clients (Android & iOS) sessions in Settings.

screen shot 2018-11-16 at 14 50 42

### CODE REVIEW

**Comment by rullzer** [comment]
Well first of all we also do not show this for the main apps.

> @Ivansss Would it be possible to send the iOS device name? Because they are quite descriptive (Ivan's iPad, Mario's iPhone, …).

@MorrisJobke the reason for this was exactly that. Iphone apparently encodes the whole string as weird unicode if there is a umlaut or whatever. Which made the DB do :boom:

**Comment by mario** [comment]
@Ivansss and me will take a look at this together next week :)

**Review by jancborchardt — APPROVED** [review]
Fixed some wording. Looks good to me now :+1: 

We can do fancy device name display or other things in a follow-up pull request?

**Review by MorrisJobke — APPROVED** [review]
Fine with me 👍

**Comment by MorrisJobke** [comment]
> We can do fancy device name display or other things in a follow-up pull request?

Yep 👍

**Pull request merged**
