### PR TITLE
Drop php 7.4 support

### PR DESCRIPTION
**Pull request by rullzer**
php 7.4 is EOL end of November.

I guess this might need some CI cleanup. But I'm not deep enough in that.
Feel free to push commits to this branch

### CODE REVIEW

**Comment by solracsf** [comment]
Please note, to move Drone to php8.0 some images need to be pushed to https://github.com/nextcloud/docker-ci/ as they only exist for php7.4

**Comment by nickvergessen** [comment]
It's a bit sad as that means we don't have a common PHP version anymore to deal with all security supported versions.
Also our CI actions need updating:
https://github.com/nextcloud/.github/blob/master/workflow-templates/psalm.yml#L28

**Comment by ChristophWurst** [comment]
- [ ] composer.json needs an update

**Comment by ChristophWurst** [comment]
Dropped with https://github.com/nextcloud/server/pull/34997

**Pull request closed without merging**
