### PR TITLE
Update icewind/streams

### LINKED ISSUE #10430: Undefined isDirectoryHandle() method breaking encryption.
https://github.com/nextcloud/server/blob/3f2a5c9335a0a96858edb65785eec149b16f1a0e/lib/private/Files/Stream/Encryption.php#L198

```
Error: Call to undefined method OC\Files\Stream\Encryption::isDirectoryHandle()
/usr/share/nginx/cloud.familie-boeh.de/lib/private/Files/Stream/Encryption.php - line 181:

OC\Files\Stream\Encryption::wrapSource(null, null, "ocencryption", "OC\\Files\\Stream\\Encryption", "r")
```

**Workaround:**
Disable the **External Files Application** as specified here: https://github.com/nextcloud/server/issues/10430#issuecomment-410657768

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #10430

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
this should fix it. FOr 15 it would make sense to remove it from files_external I think...

**Review by icewind1991 — APPROVED** [review]

**Comment by icewind1991** [comment]
For dropping the duplicate dependency, it would probably be best to move `icewind/smb` from the files_external 3rdparty folder to the main one, composer isn't really made for the whole "multiple vendor folders" thing

**Comment by rullzer** [comment]
@schiessle can you verify this fixes it?

**Review by ChristophWurst — APPROVED** [review]
Sure :elephant:

**Pull request merged**
