### PR TITLE
30.0.0

### PR DESCRIPTION
**Pull request by Altahrim**

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by melroy89** [comment]
aha I was also confused by the missing release in GitHub.

**Comment by melroy89** [comment]
You might want to automate creating a release as well using GitHub Actions? Eg. using https://github.com/softprops/action-gh-release or https://github.com/elgohr/Github-Release-Action

**Comment by skjnldsv** [comment]
@melroy89 official release is tomorrow

**Comment by skjnldsv** [comment]
@Altahrim releases are missing :wink:

**Pull request merged**
