### PR TITLE
Accessibility and design fixes for update and redirect pages

### PR DESCRIPTION
**Pull request by jancborchardt**
- Regular links now have an underline effect on hover/focus. Makes more sense than the transparency on hover and looks especially nice in Webkit cause it does not cut through descenders.
- The buttons now have hover/focus state for proper accessibility
- Buttons have proper padding for clickability
- Style update button as primary (blue)

Log in now, with nice hover/focus effect (there was none before):
screenshot from 2018-10-02 20-38-07

Redirect of Mail app before & after, had no hover/focus effect either. General style adjusted like the modal in https://github.com/nextcloud/server/pull/11536
screenshot from 2018-10-02 20-45-48
screenshot from 2018-10-02 20-38-44

Same for upgrade, had no hover/focus effect, and some spacing on top and bottom was fixed:
screenshot from 2018-10-02 20-42-38
screenshot from 2018-10-02 20-40-43

Please review @nextcloud/designers @nextcloud/accessibility

### CODE REVIEW

**Review by skjnldsv — DISMISSED** [review]
Not really fond of the shadow, feels too strange :)
I feel like when using opacity, having a neat delimitation is easier for us to find where to focus, but the eye tend to get confused by gradual shadow.

But the rest is :fire: :fire: :fire:

**Comment by jancborchardt** [comment]
@skjnldsv removed the shadow! :sun_with_face: 
screenshot from 2018-10-02 23-13-47

**Review by MorrisJobke — APPROVED** [review]
:+1: I like it with the shadow 👍

**Comment by jancborchardt** [comment]
For the record: I also like it better with the shadow, but am also fine without. :) Let’s just get it in like this, we can do the shadow later.

**Review by weeman1337 — APPROVED** [review]
I like it more without the shadow. It somehow looks cleaner.
With shadow this also looks like the new rounded dialogs - but it isn't one...

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
Let me merge this now and you can discuss further changes in followup issues :)

**Pull request merged**
