### PR TITLE
feat(system-tags): show inline in files 

### PR DESCRIPTION
**Pull request by skjnldsv**
Rebase after https://github.com/nextcloud/server/pull/37609 is merged

### Light
localhost_8080_index php_apps_files__dir=_ fileid=2 (2)

### Dark
localhost_8080_index php_apps_files__dir=_ fileid=2 (1)

### CODE REVIEW

**Comment by szaimen** [comment]
I've tested this and it seems to work in general :)

Some remarks:
- choosing a really long name might overlap things in certain resolutions:
  image
- newly added or removed labels via the sidebar will only be shown after a reload of the files app:
image

**Review by nimishavijay — COMMENTED** [review]
> choosing a really long name might overlap things in certain resolutions:

Great catch, we can ellipsise for more than ~30 characters

No other comments from my side, it looks great :)

**Comment by skjnldsv** [comment]
> newly added or removed labels via the sidebar will only be shown after a reload of the files app:

It depends how much time we actually want to spend on this.
It should be fixed with the new Files to Vue, but I'm not sure I should spend more time on this

**Review by jancborchardt — APPROVED** [review]
Looks awesome! :) I'd say the ellipsizing is good to fix as @nimishavijay said, but the refresh can be handled later.

**Comment by skjnldsv** [comment]
image
Done

**Review by szaimen — APPROVED** [review]
> It depends how much time we actually want to spend on this.
> It should be fixed with the new Files to Vue, but I'm not sure I should spend more time on this

Fine by me then

**Comment by fechnert** [comment]
This looks awesome, thank you for adding this! I'm very happy that it kinda looks like [my proposal](https://github.com/nextcloud/server/issues/6424#issuecomment-784198993). Awesome work!

**Comment by skjnldsv** [comment]
Thanks for the positive feedback @fechnert :hugs:

**Comment by jancborchardt** [comment]
@fechnert suggestions and contributions like that are always welcome! :)

**Comment by gonzalo** [comment]
Awesome! They way that we use tags in our organization really would thank this new feature. We're still on 26, but planning to move to 27. Is this feature enabled by default in 27.0.5? or it will be in next releases?

**Comment by jancborchardt** [comment]
@gonzalo if tags are enabled, this is how they will be shown by default from 27 on. :)

**Comment by gonzalo** [comment]
Just looks awesome!!
image

**Comment by Glandos** [comment]
This is really great, but I have one question before opening a new issue: is it normal that tags don't show up in a public link view? They are displayed in the list of a logged in user.

**Comment by jancborchardt** [comment]
@Glandos at least in the current form and implementation, tags are considered information private to the instance. So they will indeed not show in the list, just like they didn’t show before in the link share view.

**Pull request merged**
