### PR TITLE
enh(a11y): Add navigation labels

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- For https://github.com/nextcloud/server/issues/41865

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Pytal** [comment]
/backport 0167f671f5795b42ff661220746feae823fb18d6 to stable28

**Comment by Pytal** [comment]
/backport 7c479aad512575f8f2712ac68d6a72bc5808b42e to stable28

**Review by nickvergessen — APPROVED** [review]
Should make it a required prop on the component, so you can not write in-accessible stuff by default in the future?

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
