### PR TITLE
fix(settings): Align user management table columns

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Resolves the first regression in https://github.com/nextcloud/server/issues/38245

## Summary

| Before | After |
|--------|--------|
| Bildschirmfoto vom 2023-05-23 18-26-12 | Bildschirmfoto vom 2023-05-23 18-25-57 |

## TODO

- [x] Fix the regression

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
No look how the groups header and the contents don't align before ;)

**Comment by szaimen** [comment]
> No look how the groups header and the contents don't align before ;)

Ah I looked at the wrong place 😅

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by JuliaKirschenheuter — CHANGES_REQUESTED** [review]
unfortunately that doesn't work like this. please test with more columns

**Comment by ChristophWurst** [comment]
is it done?

**Comment by JuliaKirschenheuter** [comment]
> is it done?

unfortunately not. do you have any ideas?

**Comment by ChristophWurst** [comment]
@AndyScherzinger this won't make it for RC2 apparently. Shall we revert https://github.com/nextcloud/server/pull/37870 instead and redo the restructuring cleanly for 28?

**Comment by AndyScherzinger** [comment]
> Shall we revert https://github.com/nextcloud/server/pull/37870 instead and redo the restructuring cleanly for 28?

@ChristophWurst @JuliaKirschenheuter yes, let's do that then

**Comment by JuliaKirschenheuter** [comment]
https://github.com/nextcloud/server/pull/38458

**Comment by JuliaKirschenheuter** [comment]
@ChristophWurst please let this branch be alife for a bit

**Comment by ChristophWurst** [comment]
You can restore the branch at any time.

**Pull request closed without merging**
