### PR TITLE
Only run integration tests when PHP was modified

### PR DESCRIPTION
**Pull request by nickvergessen**
Integration tests are now only run when:
* PHP was modified
* a file in `build/integration` was modified
* The commit is a merge commit

### CODE REVIEW

**Comment by skjnldsv** [comment]
Nice idea!!

**Comment by kesselb** [comment]
Integration tests are not relevant for pull requests like https://github.com/nextcloud/server/pull/16798?

**Comment by skjnldsv** [comment]
> Integration tests are not relevant for pull requests like #16798?

no, they're only testing apis :)

**Comment by nickvergessen** [comment]
> Integration tests are not relevant for pull requests like #16798?

No, integration tests make API calls only. No JS or browser involved.
Acceptance tests run the JS code

**Comment by kesselb** [comment]
> No, integration tests make API calls only. No JS or browser involved.
> Acceptance tests run the JS code

Thank you for explaining :+1:

**Comment by blizzz** [comment]
Mh, do I understand correctly, you want to run them only after a PR was merged?

**Comment by skjnldsv** [comment]
> Mh, do I understand correctly, you want to run them only after a PR was merged?

No, only if the commits include changes on a php file, an integration test or if it's a merge commit! :)

**Comment by nickvergessen** [comment]
What @skjnldsv said. We do it like that since some weeks in Talk and it helped to improve the queue timers for JS/CSS only changes quite a lot. Now server is the biggest time drain and at least for pushes to JS/CSS only changes it is unnecessary to repeatedly check the integration tests.

Merge commits always run the integration tests on master/stableX afterwards

**Comment by rullzer** [comment]
Could probably do the same on all the DB runs right?

**Comment by nickvergessen** [comment]
> Could probably do the same on all the DB runs right?

The time gain there is not a lot, but yeah. Anyway lets start like this and see how it works out.

**Review by tobiasKaminsky — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

**Comment by kesselb** [comment]
We could replace the default clone step with a custom one (https://docs.drone.io/user-guide/pipeline/cloning/#custom-logic) like for the submodules and run the check there. 

Benefits:
- Merge the submodule step with the clone step
- Cache is not initialized

**Pull request merged**
