### PR TITLE
Fix email verification

### LINKED ISSUE #30374: VerifyUserData job always gets readded
In cases the VerifyUserData job fails or terminates immediately (due to no validation being required) the job is instantly readded again due tot he updateAccount logic. It seems that there was some change to fetch the old account data now in an indexed array rather then one with the property names as key. In the following $oldMail will just always be null and the job gets readded:

image

Steps to reproduce:
- set `'lookup_server' => '',` in config.php
- run the cron job runs and is removed due to https://github.com/nextcloud/server/blob/f49a7512837ff5d297d9c75389a55660f0556272/apps/settings/lib/BackgroundJobs/VerifyUserData.php#L99

Expected:
- There is no job present anymore after the removal

Actual:
- The job gets added again right away

@blizzz @Pytal As a quick fix i thought about just bringing back the property name array key but I don't feel familiar enough with the code to tell if that is a good idea right away. Maybe you have a better insight there.

Could potentially cause quite some cron delay or unnecessary load on systems with larger user count.

### PR DESCRIPTION
**Pull request by Pytal**
Fix https://github.com/nextcloud/server/issues/30374

### CODE REVIEW

**Comment by blizzz** [comment]
can we have a unit test for this?

**Review by come-nc — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by Pytal** [comment]
Test updated and passing, would appreciate a re-review or another review now with the updated test :)

**Review by blizzz — APPROVED** [review]

**Pull request merged**
