### PR TITLE
 	Only allow colons in db host for IPv6 addresses

### LINKED ISSUE #6642: Do not allow to specify a colon within the dbhost
* the dbhost should not be allowed to hold a colon (except it is an IPv6 address and then at least needs to hold 7 `:` or at least `::`)
* also check this in the CLI tool (--database-host)

cc @icewind1991 @nickvergessen @rullzer

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #6642 

@MorrisJobke backport the first commit?

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
> @MorrisJobke backport the first commit?

Makes sense 👍

**Comment by MorrisJobke** [comment]
First commit is reverted in #7107

**Comment by xekon** [comment]
was this ever resolved?
I am trying to setup nextcloud now:
`wget https://download.nextcloud.com/server/releases/latest-13.tar.bz2
tar -xjvf latest-13.tar.bz2
	rm -f latest-13.tar.bz2
sudo mv nextcloud /var/www/html/nextcloud/`

using ubuntu 18.04, nginx, postgresql10

on the installer page I get the following error that suggests its still trying to use IPV6 instead of my unix socket, in pg_hba.conf I have commented out everything except for the unix socket, I have tested the socket from the command line and it does indeed work, so my only guess is this issue is not yet resolved?:

under the database configuration I specified the socket:
localhost:/run/postgresql/.s.PGSQL.5432

which can be found with the following command:
sudo find / -type s

nextcloud-error

If you require any more input from me, I would be happy to help. Thanks.

**Pull request merged**
