### PR TITLE
Refactors dav app commands.

### PR DESCRIPTION
**Pull request by fsamapoor**
## Summary

I have made some adjustments to the `apps/dav/lib/Command` classes to improve the code readability.

The improvements in this PR include but are not limited to:

- Using PHP8's constructor property promotion
- Adding return types
- Replacing return code integers with more readable strings.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits

### CODE REVIEW

**Comment by fsamapoor** [comment]
Hey @szaimen, sorry to bother you.
There have been [a number of my PRs in the past two weeks](https://github.com/nextcloud/server/pulls?q=is%3Aopen+is%3Apr+author%3Afsamapoor+review%3Anone+milestone%3A%22Nextcloud+28%22) that haven't been assigned to any reviewers yet.
Is there anything that I could do in these situations?

**Comment by fsamapoor** [comment]
Conflicts resolved.

**Review by ChristophWurst — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]

**Review by icewind1991 — APPROVED** [review]

**Comment by fsamapoor** [comment]
Hey @icewind1991, It's been more than a month now that not a single pull request of mine has been able to pass the Cypress workflows.

**Comment by miaulalala** [comment]
I will rebase the branch - if you want to do some additional work, you will need to pull first @fsamapoor

**Pull request merged**
