### PR TITLE
Bump nikic/php-parser from 4.10.4 to 4.10.5

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/3rdparty/pull/662

This isn't used much except for CI -> green CI means we merge this.

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by MichaIng** [comment]
> green CI means we merge this.

Drone acceptance files sharing test fails at:
```
    And I create a new folder named "Subfolder" # FileListContext::iCreateANewFolderNamed()
      │ Create New folder menu item in file list could not be clicked
      │ Exception message: element not interactable
      │   (Session info: chrome=90.0.4430.85)
      │   (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 4.15.0-124-generic x86_64)
      │ Trying again
      │ 
      element not interactable
        (Session info: chrome=90.0.4430.85)
        (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 4.15.0-124-generic x86_64) (WebDriver\Exception\ElementNotVisible)
```

**Comment by ChristophWurst** [comment]
I've seen one failing acceptance test all day long :shrug:

**Comment by ChristophWurst** [comment]
Restarted. Let's see :hourglass:

**Comment by blizzz** [comment]
Was it `Scenario: resharee sees a folder created by the owner in a shared folder # /drone/src/tests/acceptance/features/app-files-sharing.feature:197` before? That was not the only failing one.

**Comment by blizzz** [comment]
another restart fwiw

**Comment by ChristophWurst** [comment]
done via https://github.com/nextcloud/server/pull/27449#event-4868965346

**Pull request closed without merging**
