### PR TITLE
23.0.1 Final

### PR DESCRIPTION
**Pull request by skjnldsv**
* #29798
* #29965
* #30009
* #30014
* #30021
* #30025
* #30026
* #30036
* #30037
* #30041
* #30053
* #30058
* #30062
* #30083
* #30088
* #30106
* #30115
* #30132
* #30136
* #30144
* #30151
* #30175
* #30176
* #30180
* #30187
* #30190
* #30212
* #30213
* #30214
* #30215
* #30236
* #30238
* #30245
* #30252
* #30267
* #30272
* #30289
* #30301
* #30306
* #30315
* #30325
* #30339
* #30343
* #30344
* #30351
* #30356
* #30390
* #30411
* #30431
* #30433
* #30443
* #30449
* #30455
* #30462
* #30480
* #30486
* #30522
* #30525
* #30528
* #30557
* #30576
* #30580
* #30592
* #30594
* #30602
* #30611
* #30619
* #30621
* #30623
* #30627
* #30636
* #30643
* #30659
* #30662
* #30663
* #30671
* #30672
* #30674
* #30684
* #30685
* #30688
* #30689
* #30695
* #30698
* #30722
* #30728
* #30734
* #30740
* #30747
* #30753
* #30759
* #30773
* #30782
* #30799
* #30811
* [3rdparty#971](https://github.com/nextcloud/3rdparty/pull/971) Create block-merge-freeze.yml
* [circles#865](https://github.com/nextcloud/circles/pull/865) Filter allowed type of member
* [circles#867](https://github.com/nextcloud/circles/pull/867) Lighten select for single circle
* [circles#873](https://github.com/nextcloud/circles/pull/873) Bypass moderator check on CFG_FRIEND
* [circles#876](https://github.com/nextcloud/circles/pull/876) Better display of federated user
* [circles#882](https://github.com/nextcloud/circles/pull/882) Strtolower on mail address
* [circles#885](https://github.com/nextcloud/circles/pull/885) Only returns population on direct request from the front-end or occ command
* [circles#887](https://github.com/nextcloud/circles/pull/887) Enforce password on new share
* [circles#894](https://github.com/nextcloud/circles/pull/894) Ignore exception to group sync
* [circles#896](https://github.com/nextcloud/circles/pull/896) Exception on null token
* [circles#898](https://github.com/nextcloud/circles/pull/898) L10n: Improved grammar
* [circles#907](https://github.com/nextcloud/circles/pull/907) Create block-merge-freeze.yml
* [files_pdfviewer#530](https://github.com/nextcloud/files_pdfviewer/pull/530) Bump actions
* [files_pdfviewer#534](https://github.com/nextcloud/files_pdfviewer/pull/534) Bump @nextcloud/eslint-config from 6.1.0 to 6.1.2
* [files_pdfviewer#535](https://github.com/nextcloud/files_pdfviewer/pull/535) Bump @nextcloud/webpack-vue-config from 4.1.0 to 4.1.4
* [files_pdfviewer#544](https://github.com/nextcloud/files_pdfviewer/pull/544) Create block-merge-freeze.yml
* [files_pdfviewer#549](https://github.com/nextcloud/files_pdfviewer/pull/549) Updating lint-php.yml workflow from template
* [files_rightclick#131](https://github.com/nextcloud/files_rightclick/pull/131) Create block-merge-freeze.yml
* [files_videoplayer#256](https://github.com/nextcloud/files_videoplayer/pull/256) Create block-merge-freeze.yml
* [firstrunwizard#652](https://github.com/nextcloud/firstrunwizard/pull/652) Fix overlapping buttons
* [firstrunwizard#661](https://github.com/nextcloud/firstrunwizard/pull/661) Create block-merge-freeze.yml
* [logreader#636](https://github.com/nextcloud/logreader/pull/636) Create block-merge-freeze.yml
* [nextcloud_announcements#92](https://github.com/nextcloud/nextcloud_announcements/pull/92) Create block-merge-freeze.yml
* [notifications#1137](https://github.com/nextcloud/notifications/pull/1137) Create block-merge-freeze.yml
* [password_policy#315](https://github.com/nextcloud/password_policy/pull/315) Create block-merge-freeze.yml
* [photos#1009](https://github.com/nextcloud/photos/pull/1009) Bump autoprefixer from 10.3.6 to 10.3.7
* [photos#1010](https://github.com/nextcloud/photos/pull/1010) Bump @nextcloud/eslint-config from 6.1.0 to 6.1.2
* [photos#1011](https://github.com/nextcloud/photos/pull/1011) Bump postcss-loader from 6.2.0 to 6.2.1
* [photos#1012](https://github.com/nextcloud/photos/pull/1012) Bump @nextcloud/event-bus from 2.1.0 to 2.1.1
* [photos#1013](https://github.com/nextcloud/photos/pull/1013) Bump @nextcloud/initial-state from 1.2.0 to 1.2.1
* [photos#951](https://github.com/nextcloud/photos/pull/951) Fix default previews
* [photos#960](https://github.com/nextcloud/photos/pull/960) Fix Tags: Don't display tags without photos
* [photos#981](https://github.com/nextcloud/photos/pull/981) Update workflows
* [photos#985](https://github.com/nextcloud/photos/pull/985) Bump @nextcloud/webpack-vue-config from 4.1.0 to 4.1.4
* [photos#986](https://github.com/nextcloud/photos/pull/986) Bump url-parse from 1.5.3 to 1.5.4
* [photos#987](https://github.com/nextcloud/photos/pull/987) Bump vue-router from 3.5.2 to 3.5.3
* [photos#988](https://github.com/nextcloud/photos/pull/988) Bump qs from 6.10.1 to 6.10.3
* [photos#989](https://github.com/nextcloud/photos/pull/989) Bump camelcase from 6.2.0 to 6.2.1
* [photos#998](https://github.com/nextcloud/photos/pull/998) Create block-merge-freeze.yml
* [privacy#676](https://github.com/nextcloud/privacy/pull/676) Fix label of account name and hide parts with subscription
* [privacy#684](https://github.com/nextcloud/privacy/pull/684) Create block-merge-freeze.yml
* [recommendations#470](https://github.com/nextcloud/recommendations/pull/470) Create block-merge-freeze.yml
* [recommendations#473](https://github.com/nextcloud/recommendations/pull/473) Update test.yml
* [serverinfo#352](https://github.com/nextcloud/serverinfo/pull/352) Create block-merge-freeze.yml
* [survey_client#123](https://github.com/nextcloud/survey_client/pull/123) Create block-merge-freeze.yml
* [text#1976](https://github.com/nextcloud/text/pull/1976) Update mark input/paste rules to tiptap v2 regular expressions
* [text#1979](https://github.com/nextcloud/text/pull/1979) Don't show "Link file" button when using direct edition
* [text#1984](https://github.com/nextcloud/text/pull/1984) Make sure translations are detected
* [text#2005](https://github.com/nextcloud/text/pull/2005) Fix only the first item gets tasklist-ified issue
* [text#2023](https://github.com/nextcloud/text/pull/2023) Fix: use stable23 branch for cypress tests
* [text#2035](https://github.com/nextcloud/text/pull/2035) Fix autofocus on empty documents without a node (Fixes: #1974)
* [text#2041](https://github.com/nextcloud/text/pull/2041) Add stylelint to github actions
* [text#2046](https://github.com/nextcloud/text/pull/2046) Fix: cypress login with new session feature
* [text#2078](https://github.com/nextcloud/text/pull/2078) Bump @nextcloud/event-bus from 2.1.0 to 2.1.1
* [text#2081](https://github.com/nextcloud/text/pull/2081) Bump @nextcloud/initial-state from 1.2.0 to 1.2.1
* [text#2084](https://github.com/nextcloud/text/pull/2084) Bump @nextcloud/webpack-vue-config from 4.1.0 to 4.1.4
* [text#2085](https://github.com/nextcloud/text/pull/2085) Bump @cypress/browserify-preprocessor from 3.0.1 to 3.0.2
* [text#2086](https://github.com/nextcloud/text/pull/2086) Bump prosemirror-markdown from 1.6.0 to 1.6.2
* [text#2088](https://github.com/nextcloud/text/pull/2088) Bump @nextcloud/eslint-config from 6.1.0 to 6.1.2
* [text#2100](https://github.com/nextcloud/text/pull/2100) Bump prosemirror-view from 1.23.5 to 1.23.6
* [text#2105](https://github.com/nextcloud/text/pull/2105) Fix closing the editor modal in public folder view
* [text#2109](https://github.com/nextcloud/text/pull/2109) Fix: 2020 let heading menu overflow workspace
* [text#2115](https://github.com/nextcloud/text/pull/2115) Create block-merge-freeze.yml
* [viewer#1066](https://github.com/nextcloud/viewer/pull/1066) Disable fade-out because of accessbility reasons
* [viewer#1089](https://github.com/nextcloud/viewer/pull/1089) Fix german (Sie) translations comming from nextcloud-vue
* [viewer#1094](https://github.com/nextcloud/viewer/pull/1094) Add cypress summary for easier branch protection mgmt
* [viewer#1099](https://github.com/nextcloud/viewer/pull/1099) Add engines support for cypress tests
* [viewer#1108](https://github.com/nextcloud/viewer/pull/1108) Always check for `OCA.Files` before using it (Fixes: #1106)
* [viewer#1114](https://github.com/nextcloud/viewer/pull/1114) Disable swiping on viewer video controls
* [viewer#1122](https://github.com/nextcloud/viewer/pull/1122) Disable swiping on viewer audio controls
* [viewer#1133](https://github.com/nextcloud/viewer/pull/1133) Create block-merge-freeze.yml
* [viewer#1138](https://github.com/nextcloud/viewer/pull/1138) Update lint-php.yml

Pending PRs:

* [ ] #30800 
* [x] #30814 
* [ ] [circles#914](https://github.com/nextcloud/circles/pull/914) Fix loosing memberships in low depth

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by artonge** [comment]
PHP cs is failing: PR to fix it: https://github.com/nextcloud/server/pull/30845

**Comment by gw0** [comment]
Not sure about the process, but it looks that official packages for this release were not yet uploaded?

**Comment by nickvergessen** [comment]
They will be made available when we think it's good.
Currently there is investigation about a small regression and we might skip the publishing and just continue with the next version soon.

**Comment by blizzz** [comment]
> we might skip the publishing and just continue with the next version soon.

That's what happened today.

**Comment by Ejdesgaard** [comment]
> > we might skip the publishing and just continue with the next version soon.
> 
> That's what happened today.

but it was and is published !
https://hub.docker.com/layers/nextcloud/library/nextcloud/23.0.1-apache/images/sha256-5b97169f2f986237472b0a0da84bab98b199cc36439e29f9a9b56d17343b50b4?context=explore

**Pull request merged**
