### PR TITLE
Bump @nextcloud/password-confirmation from 4.0.1 to 4.0.2

### LINKED ISSUE #34217: [Bug]: Confirm button on password confirmation dialogue not enabled
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When trying to do an administrative change on Nextcloud and the password confirmation dialog appears, the "confirm" button is not enabled, thus pressing it does not have any effect. Pressing [ENTER] is a work around.

Screenshot_20220923_124823

### Steps to reproduce

1. Run NC 25  for a bit
2. Do an action that may require password confirmation (e.g. app handling)
3. Enter your password
4. Try to confirm with a click

### Expected behavior

The "Confirm" button gets enabled when the input field is not empty.

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
- activity: 2.17.0
  - admin_audit: 1.15.0
  - announcementcenter: 6.4.0-beta.1
  - calendar: 4.0.0-alpha.1
  - calendar_resource_management: 0.3.1
  - circles: 25.0.0-alpha.0
  - cloud_federation_api: 1.8.0
  - collectives: 2.0.0-beta1
  - comments: 1.15.0
  - contacts: 5.0.0-alpha.3
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.0-beta.1
  - droneci_fast_lane: 1.0.2
  - end_to_end_encryption: 1.11.0-beta.1
  - external: 4.1.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.0
  - files_lock: 24.0.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_videoplayer: 1.14.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.0-beta.1
  - groupfolders: 13.0.0-beta.1
  - guests: 2.3.0
  - integration_discourse: 1.0.4
  - integration_github: 1.0.5
  - integration_mastodon: 1.0.3
  - integration_reddit: 1.0.5
  - integration_twitter: 1.0.3
  - integration_zammad: 1.0.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.0-beta.7
  - nextcloud_announcements: 1.14.0
  - notes: 4.5.1
  - notifications: 2.13.1
  - notify_push: 0.4.0
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 1.7.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.0
  - richdocuments: 7.0.0-beta.1
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0-rc.1
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.4
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_nextcloud_notification: 3.5.0-beta.1
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0-beta.2
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
  - zammad_organisation_management: 1.1.3
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #34516: [Bug]: 25 RC3 App updater asks for password, entering followed by enter works, pressing button fails
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When updating a app (apps, udpate all) sometimes a password is requested.
If the password is entered the button stays disabled, pressing enter will allow to continue.

### Steps to reproduce

1. Have 25 RC3, and a app to be updated
2. do update after being loggedon several hours, so a password gets requested
3. Try to enter the password using  the button.

### Expected behavior

A working button

### Installation method

Community VM appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Not relevant.
```

### List of activated Apps

```shell
various
```

### Nextcloud Signing status

```shell
N/A
```

### Nextcloud Logs

```shell
N/A
```

### Additional info

N/A

### PR DESCRIPTION
**Pull request by Pytal**
Fix https://github.com/nextcloud/server/issues/34217
Fix https://github.com/nextcloud/server/issues/34516

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by nickvergessen — DISMISSED** [review]
All acceptance tests fail

**Comment by Pytal** [comment]
> Failed asserting that 'http://acceptance-access-levels/index.php/login?user=user0&direct=1' starts with "http://acceptance-access-levels/index.php/apps/files/"

Never seen this before, ring any bells @danxuliu?

**Comment by danxuliu** [comment]
> > Failed asserting that 'http://acceptance-access-levels/index.php/login?user=user0&direct=1' starts with "http://acceptance-access-levels/index.php/apps/files/"
> 
> Never seen this before, ring any bells @danxuliu?

After the user logs in it is verified that the Files app is shown (Dashboard is disabled) based on the URL. That failed assertion means that, instead of the Files app, the user ended again in the login page.

I have tried and it also happens outside of the acceptance tests, in a _real_ system (the login page is shown again with the _Wrong username or password_ message). This does not happen in the root of the branch, so I do not know what, but something is broken by this pull request :-)

**Review by YasinAshorian — APPROVED** [review]

**Comment by Pytal** [comment]
Not sure why login failed in the way described by @danxuliu above in this PR or why https://github.com/nextcloud/server/pull/34541/commits/dbaf8f3b89678de481a3214728dbec99df4ac57e fixes it but fyi @CarlSchwan

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
