### PR TITLE
 Add support for using kerberos ticket to authenticate to smb servers

### PR DESCRIPTION
**Pull request by icewind1991**
- [x] requires https://github.com/nextcloud/server/pull/9578

Requires the server to already have a valid ticket to authenticate

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Please rebase because the required PR got merged.

**Comment by icewind1991** [comment]
rebased

**Review by MorrisJobke — APPROVED** [review]
🐘

**Review by rullzer — APPROVED** [review]
:elephant:

**Pull request merged**
