### PR TITLE
Unify the HTML encoding handling with other ROS apps

### PR DESCRIPTION
**Pull request by nickvergessen**
While looking into https://github.com/nextcloud/android/issues/3487 I noticed, that the apps which use the most famous RichObjectStrings (Activity and Notifications) have an inconsistent handling in terms of HTML encoding. Or to phrase it better, neither cared and it worked for most, because the providing app happened to escape the HTML (sometimes).

So now we simply define, that ROS should not be HTML escaped, similar to their plain-text variants. Instead the viewing part is responsible to escape the HTML properly, which was provided before the ROS rendering happens.

### :warning: The rendering PRs below need to be merged/backported before, otherwise we create a stored XSS in the comments app. :warning: 

- [x] https://github.com/nextcloud/notifications/pull/261
- [x] https://github.com/nextcloud/activity/pull/343

I checked all apps, and I only could find HTML handling in comments (for activities only, notifications are fine) and announcementcenter (both fixed for upcoming)

---

Client devs please confirm that this works as intended on your side then:
- [x] Desktop: @camilasan 
- [x] Android: @tobiasKaminsky @AndyScherzinger 
- [x] iOS: @marinofaggiana 

You can test this, by mentioning your user `@test1` in a comment:
```
@test1 <strong>this should not be bold</strong>
This is on a new line

<em>And this is two lines away and NOT italic</em>
```

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
As mentioned on IRC, this is working on Android.
But as soon as I enable this PR, I do get html tags parsed after a refresh of the web site:
- open details on any file
- enter a comment with html tag
- see that they are not parsed
- refresh site
- see html tags parsed, e.g. text is bold

**Comment by nickvergessen** [comment]
Which is expected as per the bold warning in the PR description

**Comment by tobiasKaminsky** [comment]
Hm. I assumed that if I enable all three PRs, that then everything would work…
Then sorry for the noise ;-)

**Comment by tobiasKaminsky** [comment]
Hm. I assumed that if I enable all three PRs, that then everything would work…
Then sorry for the noise ;-)

**Comment by marinofaggiana** [comment]
Sure, no problem !

**Comment by nickvergessen** [comment]
@rullzer yeah basically make sure all HTML is shown as plain text `<strong>`.
Markup should only be done via the Rich message stuff.

**Comment by rullzer** [comment]
I'll try to verify this evening then

**Comment by rullzer** [comment]
ros

Properly escaped on desktop.,

**Review by MorrisJobke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Pull request merged**
