### PR TITLE
Files : Left panel dropdown improvement for NC 25

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Respawn of https://github.com/nextcloud/server/pull/38338

**/!\ Reviewers' test needed**

## Before : 
[before 2.webm](https://github.com/nextcloud/server/assets/33763786/823c8457-145a-423d-a9a9-39996205f607)

## After : 
[after 2.webm](https://github.com/nextcloud/server/assets/33763786/fe22628f-f9cf-4645-8e90-db76bbc458bc)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Let me know if the video is outdated @Jerome-Herbinet, just same feedback as in the other review. :)

The triangle pointing to the right is confusing, it would be expected to have a triangle pointing down when in closed state, indicating more things open downwards. :)

When open, the arrow should still point down too. Then it would behave exactly like a standard HTML select element.

**Comment by Jerome-Herbinet** [comment]
> Let me know if the video is outdated @Jerome-Herbinet, just same feedback as in the other review. :)
> 
> The triangle pointing to the right is confusing, it would be expected to have a triangle pointing down when in closed state, indicating more things open downwards. :)
> 
> When open, the arrow should still point down too. Then it would behave exactly like a standard HTML select element.

@jancborchardt here is an updated video : 
[Capture vidéo du 10-08-2023 11:11:35.webm](https://github.com/nextcloud/server/assets/33763786/36a5f22d-49a0-4915-94c7-839762e15509)

**Review by jancborchardt — APPROVED** [review]
Very nice! Would be good to also habe hover/focus feedback on the triangle button, but that can also be done in a follow-up.

**Comment by Jerome-Herbinet** [comment]
> Very nice! Would be good to also habe hover/focus feedback on the triangle button, but that can also be done in a follow-up.

Thanks @jancborchardt ! Can you mention another appropriate reviewer for testing + approval ?

**Comment by jancborchardt** [comment]
@skjnldsv @szaimen @susnux another review needed. :)

**Comment by jancborchardt** [comment]
Also cc @AndyScherzinger would be nice to get this fix in for 27.1.0 as it makes the navigation subitems more obvious.

**Comment by AndyScherzinger** [comment]
Checked with the devs, this PR is v25-only (!)
v26+ the left sidebar got migrated to vue in contrast to 25 being legacy JS. So this can't be used on anything but 25 and would need to be completely re-implemented for 26+ -> not happening for 27.1 then

**Comment by jancborchardt** [comment]
@Jerome-Herbinet do you think this is still applicable then? I’d even say since it will soon be 3 versions old anyway, let’s look to the future instead?

**Comment by AndyScherzinger** [comment]
> Ah got it, sorry for the noise then!

All good, still worth the question.

> @Jerome-Herbinet do you think this is still applicable then? I’d even say since it will soon be 3 versions old anyway, let’s look to the future instead?

I'd second that question. @Jerome-Herbinet would you be willing to work on the solution for the `master` branch? That is targeting v28 but we could then still discuss a back-port to `stable27` even though I believe it won't make it for the September release, so best maybe then to aim straight for v28.

**Comment by skjnldsv** [comment]
I',m not sure I get it.
This is only about the triangle on the right instead of left, right?
Then Nextcloud 27 and 28 already have those :thinking: 

What's left to do on master then? :thinking:

**Comment by Jerome-Herbinet** [comment]
> I'm not sure I get it. This is only about the triangle on the right instead of left, right?
> Then Nextcloud 27 and 28 already have those :thinking: 
> 
> What's left to do on master then? :thinking: 

ASFAIK recent major NC versions (since 26 ?), manage this in nextcloud-vue and it might be already done ; testing and confirmation might be necessary on 26 27 and 28 if possible.

**Comment by skjnldsv** [comment]
Absolutely, since 26 this is nc/vue, so we're good.
I think we can close then :)

**Comment by AndyScherzinger** [comment]
Well, then we could also just merge this one, no? Since it is already "resolved" on 26+ @skjnldsv @Jerome-Herbinet 
Or we drop it since it is resolved on 26+

**Comment by skjnldsv** [comment]
I would tend to be on the careful side here and avoid touching `core/css/apps.scss` on a version that's going unsupported in a few weeks :)

**Comment by Jerome-Herbinet** [comment]
> Well, then we could also just merge this one, no? Since it is already "resolved" on 26+ @skjnldsv @Jerome-Herbinet Or we drop it since it is resolved on 26+

@AndyScherzinger, I've just checked if my personal 26.0.5 instance ships this UI enhancement ... but it's not the case 🤔 ... that's strange, although this PR was merged https://github.com/nextcloud-libraries/nextcloud-vue/pull/4103
Cc @skjnldsv

**Comment by skjnldsv** [comment]
Indeed, this is v8.0.0 and  v7.11.5+ only
So it will come in upcoming 26.0.6 https://github.com/nextcloud/server/pull/39812

**Pull request closed without merging**
