### PR TITLE
fix highcontrast theme

### LINKED ISSUE #33836: high-contrast-mode bright makes icons unvisilbe
See 
image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/33836

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by skjnldsv — COMMENTED** [review]
What about `ThemesService.php` ?
https://github.com/nextcloud/server/issues/33836#issuecomment-1256235743

**Comment by skjnldsv** [comment]
This at least sanitize the loop
Try setting your theme to `highcontrast` (switching to master or editing your db), then checkout this branch.
Now it's broken and you cannot select another theme (error 500)

**Comment by szaimen** [comment]
> It at least sanitize the loop Try setting your theme to `highcontrast` (switching to master or editing your db), then checkout this branch. Now it's broken and you cannot select another theme (error 500)

I see. Can we fix this in a follow-up or not? (I don't feel like I am able to solve the issue myself...)

**Comment by skjnldsv** [comment]
> I see. Can we fix this in a follow-up or not? (I don't feel like I am able to solve the issue myself...)

You can at least use my code from https://github.com/nextcloud/server/issues/33836#issuecomment-1256235743

**Comment by szaimen** [comment]
> You can at least use my code from [#33836 (comment)](https://github.com/nextcloud/server/issues/33836#issuecomment-1256235743) :)

all right! I had a look and it seems like the code is already present in master or shaall I revert this?

**Comment by szaimen** [comment]
Ping @skjnldsv :)

**Comment by skjnldsv** [comment]
I thought I didn't push it, my bad @szaimen ! Nice catch :)

**Review by skjnldsv — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
