### PR TITLE
Update 'Appstore.svg' (official App Store badge)

### PR DESCRIPTION
**Pull request by coliff**
Updated official artwork for the App Store badge. (it's slightly different now)
Optimised with SVGO from original badge artwork at: https://developer.apple.com/app-store/marketing/guidelines/images/badge-download-on-the-app-store.svg

Tested in a production installation of Nextcloud 12.0.4 with no issues

Signed-off-by: Christian Oliff christian@christianoliff.com

### CODE REVIEW

**Comment by juliushaertl** [comment]
Same here @coliff Please add the signed-off message to the commits.

**Comment by juliushaertl** [comment]
@nextcloud/designers

**Comment by pixelipo** [comment]
While you're at it, I'd suggest also fixing the width and viewBox, which are currently non-integer numbers (that can cause problems in certain cases).
Is there any reason to have `data-name` tags? Also, usage of `<g>` groups is a bit strange - does it make sense to keep those groupings?

**Comment by pixelipo** [comment]
I also noticed that there is a grey border around the badge - is that on purpose? Doesn't look very "Nextcloud", @jancborchardt ?

**Comment by coliff** [comment]
@pixelipo - its the official artwork and technically the only one you're supposed to use. You can't edit it. The grey border is intentional. I think its ok to slightly adjust the width and viewbox to round up to nearest pixel though. I don't think we should change the data-name or g tags. It's already optimised with SVGO and only 
8 KB.
REF: https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore

**Comment by coliff** [comment]
Related: the Google Play badge artwork should be updated too.. the latest official one has a grey border too and a brighter, flatter triangle icon
REF: https://play.google.com/intl/en_us/badges/

**Comment by pixelipo** [comment]
You're correct about not modifying the look, @coliff but the pixel issue seems to have popped out in this version - previous width was whole 135px.

Regarding attribution, are we also adding the obligatory legal text on all the views where this badge is used?

**Comment by coliff** [comment]
The view where I saw it used on Nextcloud - the HTML used to display it just set the images height and didn't specify width so swapping this image in doesn't alter the layout negatively.

If we were to manually edit the SVG code to make the width 135px it would still appear the same width - on the screen but would have to have either a gap to the left or right to adjust for the fact that the badge artwork is 119.664px.

**Comment by MorrisJobke** [comment]
@nextcloud/designers What about this? Merge, change or close?

**Comment by skjnldsv** [comment]
We should also probably use the default ones. @coliff can you bump the play store as well?

**Comment by coliff** [comment]
@skjnldsv  - sure shall I do a seperate PR for Google Play badge or add it to this one?

**Comment by MorrisJobke** [comment]
> @skjnldsv - sure shall I do a seperate PR for Google Play badge or add it to this one?

Just add it to this PR.

**Comment by coliff** [comment]
strange, not sure what happened but it doesn't look like I can add to this PR. It says this branch is `unknown repository`. Think I'd have to make a separate PR - unless someone at Nextcloud could add it?
The official Google Play badge is: https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png

**Comment by rullzer** [comment]
@coliff mind to submit a new PR. As github seems to be confused a bit.

IMO we should indeed use official artwork. If we are not supposed to modify it we should not do that then.

**Pull request closed without merging**
