### PR TITLE
fix(sharing): migrate QuickShareSelect to NcActions

### LINKED ISSUE #43139: [BITV]: Sharing tab: permissions dropdown is not accessible
Screenshot from 2024-01-26 08-39-29

It is just a `<div>` with buttons inside, not a list ;(. Actually it should be a full `NcActions`, but don't know how to solve it without design changes.

### PR DESCRIPTION
**Pull request by ShGKme**
* ⚠️ Requires `@nextcloud/vue@8.6.0`
* Resolves: https://github.com/nextcloud/server/issues/43139

## Summary

The current custom quick share select implementation has a number of a11y issues:
- The toggle button
  - is not focusable
  - has no button role
  - has no `aria-expanded="false"`
- The menu has popup role, better to have menu or select semantics
- Selected button is marked by `aria-selected` only on `true`, which is not allowed here and should has `false` value
- Keyboard navigation works, but the best is if <kbd>Tab</kbd> moves to the next UI element instead of the next option in the list

Having all of that, it seems that moving to `NcActions` with `menu` + `menuitemradio` semantics and some custom styles for the trigger is the best and easiest way to fix all a11y issues.

## Screenshots

🏚️ Before | 🏡 After
---|---
image | image
image | image
before-sharing-focus | after-sharing-focus

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]
😍 works great!

**Comment by ShGKme** [comment]
Waiting for `@nextcloud/vue@8.6.0`

**Review by emoral435 — APPROVED** [review]
LGTM 👍 Tested with NcVue 8.6.1 and works perfectly :)

**Comment by ShGKme** [comment]
Rebased onto master after upgrading `@nextcloud/vue`

**Pull request merged**
