### PR TITLE
Fix avatar on exif rotated images

### LINKED ISSUE #1928: Avatar doesn't rotate JPEGs based on EXIF data
### Steps to reproduce
1. Settings > Personal > Profile Picture
2. Upload a JPEG which has EXIF rotation
3. Or.. Choose a JPEG which has EXIF rotation
    * Example JPEG available here. This image should show in portrait.
https://cloud.githubusercontent.com/assets/1018807/14191717/4a47f866-f74e-11e5-9030-e1add9fc4db1.jpg

### Expected behaviour
Image should be automatically rotated based on EXIF data

### Actual behaviour
JPEG's EXIF data is ignored. Images in crop area, and after cropping, are not rotated properly

### Notes
This issue also exists in ownCloud https://github.com/owncloud/core/issues/23697
I presented a working fix, but it is not ideal because it uses views and not the Node API https://github.com/owncloud/core/issues/23697#issuecomment-204000138

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #1928

Basically \OC_Image is a freaking mess. Lets hope CI is happy.

### CODE REVIEW

**Comment by rullzer** [comment]
@josh4trunks please test

**Comment by josh4trunks** [comment]
@rullzer the changes work, goodjob!

**Comment by josh4trunks** [comment]
:+1:

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
