### PR TITLE
fix issue #1482 - mail invites through v1 webdav

### LINKED ISSUE #1482: Invitations not sent when added meetings from Android and Gnome
### Steps to reproduce
1. configure DAVDroid or Gnome Online Accounts to connect to a Calendar on nextcloud
2. add a new meeting with at least one other mandatory participant

### Expected behaviour
Mail invites should be sent to participants

### Actual behaviour
No message is sent

### Server configuration
**Operating system**: Debian Stretch

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 10.0

I've researched this problem and noted that it is because when connecting from Gnome Online Accounts or DAVDroid `apps/dav/appinfo/v2/remote.php` isn't executed, and `v1/caldav.php` is executed in its place. Digging a little more I've found that on `caldav.php` the plugins for invites aren't loaded.

I've made it work with a two line changes:

```diff
--- nextcloud/apps/dav/appinfo/v1/caldav.php	2016-08-25 03:59:50.000000000 -0300
+++ nextcloud-imip/apps/dav/appinfo/v1/caldav.php	2016-09-21 14:23:36.251450162 -0300
@@ -78,6 +78,8 @@
 }
 
 $server->addPlugin(new \Sabre\CalDAV\ICSExportPlugin());
+$server->addPlugin(new \Sabre\CalDAV\Schedule\Plugin());
+$server->addPlugin(new OCA\DAV\CalDAV\Schedule\IMipPlugin( \OC::$server->getMailer(), \OC::$server->getLogger()));
 $server->addPlugin(new ExceptionLoggerPlugin('caldav', \OC::$server->getLogger()));
 
 // And off we go!
```

After this changes, invites are sent both from Gnome and Android.

As I do not know the impact of this change on other parts of nextcloud / calendar, I am submitting this issue report.

### PR DESCRIPTION
**Pull request by allgood**
Add Schedule and IMip plugins when receiving webdav v1 api calendar calls, allowing clients like Google Online Authenticator and DAVDroid to send mail invitations for meetings.

Fix #1482

### CODE REVIEW

**Comment by LukasReschke** [comment]
Can you add a "Signed-Off-By" line? Thx! https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by ctodobom** [comment]
> Can you add a "Signed-Off-By" line? Thx!
@LukasReschke , how can I do this after commit? should I make a new clean commit and new pull request?

**Comment by ctodobom** [comment]
@LukasReschke , think this should do... found how to add an empty commit on top of my original one, with a new commit message. Please let me know!

**Comment by rullzer** [comment]
@ctodobom thanks for the fix! The bot wasn't happy yet. So to move this forward I created #1713. Should be in soon!

**Pull request closed without merging**
