### PR TITLE
Support arbitrary number of arguments for d:or and d:and in search queries

### PR DESCRIPTION
**Pull request by icewind1991**
The sabredav plugin already handles this case, just have to properly transform it to the db query

See https://github.com/nextcloud/server/pull/3360#issuecomment-357682769

### CODE REVIEW

**Comment by mario** [comment]
@icewind1991 yey :D

**Comment by barrydegraaff** [comment]
This fix works for me! Thanks very much to @icewind1991

**Review by rullzer — APPROVED** [review]
Works as expected!

**Comment by MorrisJobke** [comment]
Waiting for https://drone.nextcloud.com/nextcloud/server/4093

**Review by MorrisJobke — APPROVED** [review]

**Comment by barrydegraaff** [comment]
Hello All,

I would like to understand how PR's like this end up in a release.
Does the `Nextcloud 14` milestone set to this PR indeed mean, it will
be in 14.0?

Or is there still a change that it will be sooner. I am not in a hurry,
but I am interested to understand how you guys plan the project around git.

Thanks!

Barry

**Comment by MorrisJobke** [comment]
> Or is there still a change that it will be sooner. I am not in a hurry,
> but I am interested to understand how you guys plan the project around git.

There is already a backport to stable13 approved and will be included in 13.0.0 😉 See #7883 for the backport

**Pull request merged**
