### PR TITLE
add fallback for trashbin original location

### LINKED ISSUE #13005: Deleted files not working after upgrade to Nextcloud 15
Can't access files in trash bin after upgrade to NC 15.

TypeError: Argument 2 passed to OCA\Files_Trashbin\Trash\TrashItem::__construct() must be of the type string, null given, called in /var/www/nextcloud/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php on line 62

Nextcloud 15.0.0
Ubuntu 16.04
PHP 7.0.32

### PR DESCRIPTION
**Pull request by icewind1991**
Should fix https://github.com/nextcloud/server/issues/13005

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Thank you very much Robin!!

**Comment by maghog** [comment]
It works, thanks!

**Review by rullzer — APPROVED** [review]
I could not reproduce but the code makes sense.

**Pull request merged**
