### PR TITLE
[stable9] Add Same Site Cookie protection

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Comment by LukasReschke** [comment]
@MorrisJobke @blizzz @schiessle Could you test whether it still works for you with your browser and locally as well? THX a lot! :)

**Comment by blizzz** [comment]
@LukasReschke login works, up- and downloading files, too. Anything more specific to test?

**Comment by LukasReschke** [comment]
> @LukasReschke login works, up- and downloading files, too. Anything more specific to test?

A quick test on the Android app and locally syncing would be appreciated as well. Especially in the case of: Stable9 without this patch then apply stable9 with this patch.

It should actually just show a failed connection quickly (or not even that) and then continue syncing for the future without any problems. So syncing should basically work 😄

**Comment by blizzz** [comment]
* configured with the Android app and sync client
* edited a file locally
* was synced up to server and down to android app

→ :+1:

**Pull request merged**
