### PR TITLE
add missing check for OC.currentUser for updateStorageQuotas

### PR DESCRIPTION
**Pull request by joernhees**
side for #13696 
see https://github.com/nextcloud/server/issues/13696#issuecomment-455875196

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@joernhees :ping_pong:

**Comment by kesselb** [comment]
I cannot reproduce this issue anymore. https://github.com/nextcloud/server/blob/af62b963c79e016f1cd2667d9918d6ad2c77bf1f/apps/files/js/filelist.js#L3434 Looks like the done event is not emitted on file-drop.js

**Comment by joernhees** [comment]
sorry for the slow reply, currently sadly not enough free time to pick this up again...

IIRC this was such a minor thing that it's probably easiest if a member/owner just takes the minute to make sure there is a check if there is currently a user...

no hurt feelings if this PR is lost (so don't bother with git knitting pls) and this closed.

**Comment by rullzer** [comment]
Then lets close this for now.

@joernhees if you have time again feel free to shoot more PRs our way ;)

**Pull request closed without merging**
