### PR TITLE
Fix remaining upload time calculation

### PR DESCRIPTION
**Pull request by nickvergessen**
Replaces https://github.com/nextcloud/server/pull/3727

### CODE REVIEW

**Comment by jancborchardt** [comment]
So does this look good @xx621998xx @aarushi15002 @ChristophWurst @MorrisJobke? :)

**Comment by luckydonald** [comment]
Please don't bump me

**Review by MorrisJobke — APPROVED** [review]
It's a lot smoother now 👍 from me

**Comment by MorrisJobke** [comment]
I fixed the sign-off

**Comment by MorrisJobke** [comment]
@nextcloud/javascript Please review :)

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
