### PR TITLE
remove deprecated OCP\Files

### PR DESCRIPTION
**Pull request by rullzer**
Deprecated since NC14. :fire:

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by PVince81** [comment]
moving from a public legacy class (at least it was public), to another private legacy one :thinking: 

I guess at least it means one less legacy class, public or not

**Review by ChristophWurst — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by szaimen** [comment]
@rullzer can you please fix the tests? Thanks in advance!

**Comment by rullzer** [comment]
Do not count on that any time soon

**Pull request closed without merging**
