### PR TITLE
Rename setting name to reduce its length

### PR DESCRIPTION
**Pull request by artonge**
Follow up of https://github.com/nextcloud/server/pull/31932

DB is limiting setting name to 64, but this was 72.

+ Remove legacy jQuery event listener as those settings are not part of the web UI anymore

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by ArtificialOwl — APPROVED** [review]

**Comment by blizzz** [comment]
/drone/src/tests/lib/Collaboration/Collaborators/UserPluginTest.php:825
/drone/src/apps/settings/tests/Settings/Admin/SharingTest.php:150

**Comment by artonge** [comment]
I forgot some rename here and there, all green now.

I also removed some legacy frontend note that are linked to the setting but not needed anymore.

**Pull request merged**
