### PR TITLE
Remove unnecessary 'Delete' title from 'Revoke' menu entry

### PR DESCRIPTION
**Pull request by jancborchardt**
This looked off:
delete tooltip for revoking devices

So I removed the extra tooltip. Please review @nextcloud/designers :)

### CODE REVIEW

**Comment by juliushaertl** [comment]
@jancborchardt For changed handlebars templates you need to run `./build/compile-handlebars-templates.sh`. No need to commit the js/ changes here, I even wonder why there are changes.

**Comment by juliushaertl** [comment]
Btw. maybe we should think about adding proper makefiles to the server, so it is easier to just run what needs to be run for settings or apps. cc @skjnldsv @ChristophWurst

**Comment by skjnldsv** [comment]
> Btw. maybe we should think about adding proper makefiles to the server, so it is easier to just run what needs to be run for settings or apps. cc @skjnldsv @ChristophWurst

Since we want to remove the handlebars, I'd say this is a temp solution and we should remove this for 16

**Comment by rullzer** [comment]
> Btw. maybe we should think about adding proper makefiles to the server, so it is easier to just run what needs to be run for settings or apps. cc @skjnldsv @ChristophWurst

Feel free to submit something. Even if we eventually want to get rid of handlebars. Still a simple make file to do a lot of heavy lifting would already help :D

**Comment by jancborchardt** [comment]
> Btw. maybe we should think about adding proper makefiles to the server, so it is easier to just run what needs to be run for settings or apps.

Yes please. I am fairly involved in Nextcloud (right? :D) and even I have no idea where to do which make and dev-setup and npm install and handlebars stuff. And where / if to commit compiled files. It’s confusing.

**Comment by MorrisJobke** [comment]
But the diff looks weird - "+63,025 −1,404" 🙈

**Comment by jancborchardt** [comment]
Oh and about the handlebars build step, I’m getting errors I could not resolve through searching yesterday:
`Error: Cannot find module 'optimist'`

Any idea? How did you install handlebars? (I needed to do via apt get cause otherwise the handlebars command was not found.) Need some docs :)

I will create a separate pull request then cause this is messed up.

**Comment by MorrisJobke** [comment]
> Any idea? How did you install handlebars? (I needed to do via apt get cause otherwise the handlebars command was not found.) Need some docs :)
> 
> I will create a separate pull request then cause this is messed up.

I guess we should do this in the install command via npm/yarn. Installing from the repos will give you super old stuff. If it is not the the path, then you either add the node_modules/bin to the path or always call it with the full path ;)

**Comment by danxuliu** [comment]
>  Any idea? How did you install handlebars?

If it is of any help, I run the Handlebars compiler inside the same Docker image used by Drone with:
```
docker run --rm --volume /PATH/TO/YOUR/NEXTCLOUD/DEVELOPMENT/DIRECTORY:/nextcloud --name nextcloud-handlebars --interactive --tty node bash
```

This opens a Bash session inside the container (which will be automatically removed once the Bash session ends). Then, in that Bash session I run:
```
cd /nextcloud
npm install handlebars -g
```

And then compile the Handlebars templates by running (also in the Bash session inside the container):
```
./build/compile-handlebars-templates.sh
```

This way I keep my system clean from NPM :-P

**Comment by jancborchardt** [comment]
Thanks! So possible short docs:

----------------

We still use Handlebars templates some places in Files and Settings. We will replace these step-by-step with Vue.js, but in the meantime you need to compile them separately.

If you don’t have Handlebars installed yet, you can do it with this terminal command:
```
sudo npm install -g handlebars
```

Then inside the root folder of your local Nextcloud development installation, run this command in the terminal every time you changed a `.handlebars` file to compile it:
```
./build/compile-handlebars-templates.sh
```

When making changes, also commit the compiled .js files!

----------------------------

Ideally we should have all that quickstart-stuff in the README.md, right now it’s only a link to the docs. I would like to add this, and a section on the Vue compilation with make dev-setup etc.

I will move the contents of https://github.com/nextcloud/server/blob/master/settings/README.md (cause no one finds that) into the main readme to a section called `👩‍💻 Development setup`, and add my part about Handlebars. Anyone opposed to that?

**Comment by jancborchardt** [comment]
Hehe @danxuliu we duplicated text ;D Sorry

**Comment by jancborchardt** [comment]
Replacement pull request at https://github.com/nextcloud/server/pull/12191 – need some small JS help with triggering the action on pressing enter. :)

Will do a pull request for the documentation to readme too.

**Comment by jancborchardt** [comment]
As mentioned, pull request for documentation in readme is open at https://github.com/nextcloud/server/pull/12192 – please review. :)

**Pull request closed without merging**
