### PR TITLE
[us] Ensure the user exists before calling a method on it 

### PR DESCRIPTION
**Pull request by rullzer**
See https://github.com/owncloud/core/pull/25652

CC: @LukasReschke @nickvergessen @MorrisJobke @icewind1991

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1: 

underlying issue is also fixed with https://github.com/nextcloud/server/pull/848 but this still makes sense

**Comment by MorrisJobke** [comment]
We should backport this, right?

cc @karlitschek

**Comment by karlitschek** [comment]
yes. please backport

**Comment by MorrisJobke** [comment]
@rullzer could you take over this backport?

**Comment by rullzer** [comment]
Stable9 #911
Stable10 #910

**Pull request merged**
