### PR TITLE
[stable25] Revert "[stable25] Fix border color contrast"

### PR DESCRIPTION
**Pull request by szaimen**
Workaround for https://github.com/nextcloud/server/issues/35457 to not block 25.0.2

Signed-off-by: Simon L <szaimen@e.mail.de>

| Before | After |
|---|---|
| image | image |
| image | image |

Tested with:
```
docker run -it \
--name nextcloud-easy-test \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.24.128 \
-e SERVER_BRANCH=revert-35346-backport/35315/stable25 \
-e CALENDAR_BRANCH=main \
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Mind adding a reason for the revert?

**Comment by szaimen** [comment]
> Mind adding a reason for the revert?

See the disscussion in the engineering chat.

**Comment by PVince81** [comment]
the chat is not available for the public

the reason is: 25.0.2 RC1 is out and causes a regression in some apps.
since we plan to release final this week, the quickest way to solve the regression is to revert for now, for 25.0.2, and then work on the proper fix (not rushed) after 25.0.2 is out.

I'll leave this PR open until we get the feedback from @Pytal later today, if the proper fix is indeed not trivial

**Review by PVince81 — APPROVED** [review]
:+1: as discussed

up to @Pytal to merge it

**Review by jancborchardt — APPROVED** [review]
Ok for me if a revert is needed quickly. After that an ideal fix would be with an extra variable as said in the issue. :)

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
Discussion with design team and accessibility reviewer will be tracked in https://github.com/nextcloud/server/issues/35457

**Pull request merged**
