### PR TITLE
Add bruteforce protection to the shareinfo endpoint

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by juliushaertl** [comment]
Tests need adjustments:

```

There were 3 failures:

1) OCA\Files_Sharing\Tests\Controller\ShareInfoControllerTest::testNoShare
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
     'ETag' => null
     'contentSecurityPolicy' => null
     'featurePolicy' => null
-    'throttled' => false
+    'throttled' => true
     'throttleMetadata' => Array (
+        'token' => 'token'
     )
 )

/drone/src/apps/files_sharing/tests/Controller/ShareInfoControllerTest.php:69

2) OCA\Files_Sharing\Tests\Controller\ShareInfoControllerTest::testWrongPassword
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
     'ETag' => null
     'contentSecurityPolicy' => null
     'featurePolicy' => null
-    'throttled' => false
+    'throttled' => true
     'throttleMetadata' => Array (
+        'token' => 'token'
     )
 )

/drone/src/apps/files_sharing/tests/Controller/ShareInfoControllerTest.php:85

3) OCA\Files_Sharing\Tests\Controller\ShareInfoControllerTest::testNoReadPermissions
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
     'ETag' => null
     'contentSecurityPolicy' => null
     'featurePolicy' => null
-    'throttled' => false
+    'throttled' => true
     'throttleMetadata' => Array (
+        'token' => 'token'
     )
 )

/drone/src/apps/files_sharing/tests/Controller/ShareInfoControllerTest.php:103
```

**Pull request merged**
