### PR TITLE
Add support for translations of move/rename activities

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] https://github.com/nextcloud/activity/issues/43

### CODE REVIEW

**Comment by nickvergessen** [comment]
Ready to review @MorrisJobke @LukasReschke

**Comment by nickvergessen** [comment]
Rebased, please review @MorrisJobke @rullzer @LukasReschke

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Review by MorrisJobke — APPROVED** [review]

**Comment by rullzer** [comment]
LGTM

**Comment by nickvergessen** [comment]
Rebased because drone didnt start

**Pull request merged**
