### PR TITLE
[stable15] Handle 0 B default quota properly in the web UI

### PR DESCRIPTION
**Pull request by juliusknorr**
Backport of #15359

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Have you run `npm i` inside `settings` before building? I have the feeling unrelated webpack bundles got touched.

**Comment by ChristophWurst** [comment]
Bildschirmfoto von 2019-05-07 19-53-24
rebuilding this branch locally gives me these changes

**Comment by juliushaertl** [comment]
> Have you run npm i inside settings before building? I have the feeling unrelated webpack bundles got touched.

npm ci, yes ... let me recheck

**Comment by juliushaertl** [comment]
@ChristophWurst No, even after a make this is the result :confused:

**Comment by juliushaertl** [comment]
Ok the files are actually not up to date on the stable15 branch:
image

**Review by MorrisJobke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
