### PR TITLE
fix multiselect actions for files

### LINKED ISSUE #18871: Multiselect bar is not sticky anymore
Scroll down in a folder, select some files to delete, then notice you can’t find the actions of the multiselect.

That’s cause the multiselect bar is not sticky anymore :O 

cc @GretaD @nextcloud/designers

### PR DESCRIPTION
**Pull request by GretaD**
fixes #18871

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
It doesn’t seem to be the right element as it’s not the whole width.

What seems to work is:
```
thead {
   position: sticky;
  top: 94px;
}
```

Can you confirm?

**Review by jancborchardt — APPROVED** [review]
See comment ^

**Review by jancborchardt — CHANGES_REQUESTED** [review]
See comment ^

**Comment by GretaD** [comment]
> It doesn’t seem to be the right element as it’s not the whole width.
> 
> What seems to work is:
> 
> ```
> thead {
>    position: sticky;
>   top: 94px;
> }
> ```
> 
> Can you confirm?

Position sticky at thead is already there(see below). Changing the #headerName does the trick, but maybe I'm missing something
```
/* Multiselect bar */
table.multiselect thead {
	@include position('sticky');
	top: 94px;
```

**Comment by juliushaertl** [comment]
Time for review, @rullzer had issues with Firefox when testing this shortly before 18.0.0 but I cannot reproduce them actually. Works fine for me in Firefox/Chromium. Please test @nextcloud/designers

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Review by rullzer — APPROVED** [review]

**Pull request merged**
