### PR TITLE
make a button out of 'What's new' so it's obvious it can be clicked on

### PR DESCRIPTION
**Pull request by violoncelloCH**
for #12694

Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> #### Conflicting files
> `apps/updatenotification/js/updatenotification.js`
> `apps/updatenotification/js/updatenotification.js.map`

FYI :wink:

**Review by ChristophWurst — APPROVED** [review]
Makes sense!

**Review by skjnldsv — APPROVED** [review]

**Comment by violoncelloch** [comment]
> > #### Conflicting files
> > `apps/updatenotification/js/updatenotification.js`
> > `apps/updatenotification/js/updatenotification.js.map`
> 
> FYI wink

@ChristophWurst Does this mean I have to rebase my PR?

**Comment by skjnldsv** [comment]
@violoncelloch rebase, ignore the changes on those two files, compile again, git add changes and finish rebase :)

**Comment by jancborchardt** [comment]
Btw @violoncelloch for design fixes it’s always good to add a quick screenshot so others can verify it looks like you want it to. :slightly_smiling_face:

**Comment by violoncelloch** [comment]
@skjnldsv thank you -- rebase done
@jancborchardt yes, I will do this next time. Problem is for a correct screenshot I would have needed to fake an update response from the server again, what would have taken me some time... here a screenshot of the button but with a empty popover:
image

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/pull/12677#issuecomment-442554180 when you need a faked update response ;-)

**Comment by jancborchardt** [comment]
@violoncelloch no problem! :) It looks good, but could you also add `class="primary"` to the "Open updater" button? Because now the 2 same-looking buttons next to each other look a bit strange, and we should signify which is the important one.

I'd even say we should put the "What's new" right next to the other button.

What do you think?

**Comment by violoncelloch** [comment]
> It looks good, but could you also add class="primary" to the "Open updater" button? Because now the 2 same-looking buttons next to each other look a bit strange, and we should signify which is the important one.

of course, will do this

> I'd even say we should put the "What's new" right next to the other button.

so we've got "Open updater", "Download now" and "What's new" all in one row? should I change it like that? @jancborchardt

**Comment by violoncelloch** [comment]
hmm, the "open updater" and "download now" buttons are inside a `<p>` which cannot include `<div>`s, but "what's new" needs `<div>`s...
I now changed the `<p>` to a `<div>` as well what should work. Hope this doesn't break something else

**Comment by jancborchardt** [comment]
Yes, I think having all buttons in one row looks better. With the most important action being on the left and with `class="primary"`. Thanks a lot @violoncelloch! :)

**Comment by skjnldsv** [comment]
Test restarted. Lots of timeouts

**Comment by skjnldsv** [comment]
Backport in https://github.com/nextcloud/server/pull/12848

**Pull request merged**
