### PR TITLE
Respect default share permissions for federated reshares

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
makes sense 👍

**Comment by MorrisJobke** [comment]
PHP CS says no.

**Comment by rullzer** [comment]
> PHP CS says no.

rebased and all is right in the world again it seems

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
