### PR TITLE
Fix quota calculation on new dav upload endpoint

### LINKED ISSUE #6354: Users with a quota of 1 Bytes cannot upload data on a shared folder with the desktop client.
### Steps to reproduce
1. Create a share with a user with unlimited quota.
2. Share it with a user which got a quota of 1 Byte.
3. Upload data to the shared folder with the user which got a quota of 1 Bytes with the nextcloud windows client (2.3.2 Build 1).
4.With the webclient it is possible to upload data to the shared folder.

### Expected behaviour
The user should be able to upload data to the shared folder.

### Actual behaviour
The user receives the following error message:
Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)

### General server configuration

**Operating system:** Linux RB00SRV061 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.31

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - gmp
 - iconv
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11.0.4

**Where did you install Nextcloud from:**  tar.bz2 from Webpage

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_notifications: 1.0.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - dav: 1.3.0
 - deck: 0.2.1
 - drawio: 0.8.8
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - onlyoffice: 1.1.3
 - ownbackup: 17.5.0
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - weather: 1.5.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - activitylog
 - admin_audit
 - contacts
 - encryption
 - federation
 - files_external
 - systemtags
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocgdaki4wkwv",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "127.0.0.1",
        "nextcloud.recretix.ch"
    ],
    "datadirectory": "\/sdb_data\/owncloud\/data\/",
    "overwrite.cli.url": "https:\/\/nextcloud.recretix.ch\/",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "ocdb",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "smtp",
    "maintenance": false,
    "loglevel": 0,
    "theme": "",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "notifications",
    "mail_domain": "recretix.ch",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "mail.cyon.ch",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "session_lifetime": 5400,
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Operating system:** Windows 10

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
#=#=#=# Syncrun started 2017-09-04T11:25:22
#=#=#=#=# Propagation starts 2017-09-04T11:25:22 (last step: 83 msec, total: 83 msec)
||Test_Share/E - Copy.txt|INST_ERROR|Up|1504515955||9||6|The item is not synced because of previous errors: Error transferring https://nextcloud.recretix.ch/remote.php/dav/files/Test/Test_Share/E - Copy.txt - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)|0|0|0|||INST_NONE|
||Test_Share/E.txt|INST_ERROR|Up|1504515955||9||6|The item is not synced because of previous errors: Error transferring https://nextcloud.recretix.ch/remote.php/dav/files/Test/Test_Share/E.txt - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)|0|0|0|||INST_NONE|
||Test_Share/sap - Copy.txt|INST_ERROR|Up|1503393144||302||6|The item is not synced because of previous errors: Error transferring https://nextcloud.recretix.ch/remote.php/dav/files/Test/Test_Share/sap - Copy.txt - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)|0|0|0|||INST_NONE|
||Test_Share/sap.txt|INST_ERROR|Up|1503393144||302||6|The item is not synced because of previous errors: Error transferring https://nextcloud.recretix.ch/remote.php/dav/files/Test/Test_Share/sap.txt - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)|0|0|0|||INST_NONE|
#=#=#=# Syncrun finished 2017-09-04T11:25:22 (last step: 66 msec, total: 149 msec)

```
</details>

### PR DESCRIPTION
**Pull request by rullzer**
Fixes: #6354

Should fix the QuotaPlugin for the new dav endpoint

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Comment by icewind1991** [comment]
Do we have a way to get the target location of the upload before the client does the move?

Would be nice to be able to check the quote when uploading the chunks instead of having the client upload all the chunks only to fail in the end.

**Comment by rullzer** [comment]
No we don't

**Comment by icewind1991** [comment]
Maybe adding a "Destination" header to the client would be something to do "some day™"

**Comment by rullzer** [comment]
I'm rewriting a bit based on https://github.com/owncloud/core/commit/f7748f4d6a36fd907e2b8f0261ede912f4ed4c89#diff-1bb741253641504b7fa5bc8417f56e6a so new commits will be coming in

**Comment by rullzer** [comment]
@icewind1991 yeah some day

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
