### PR TITLE
[stable11] Fix legacy DAV endpoint

### PR DESCRIPTION
**Pull request by LukasReschke**
This is https://github.com/nextcloud/server/pull/2684 for stable11, as the test fail this clearly proofs that something is broken 😢 

See https://drone.nextcloud.com/nextcloud/server/3075/32 and https://drone.nextcloud.com/nextcloud/server/3075/35

cc @rullzer

### CODE REVIEW

**Comment by LukasReschke** [comment]
@rullzer Can you revert your changes to the test file? In my opinion we should 1:1 use the same test file on this branch as in stable10 and if something fails then … well, then we should adjust the endpoint. Not the test file.

**Comment by rullzer** [comment]
@pbek could you try this patch?

**Comment by rullzer** [comment]
@LukasReschke also you please try again. Hopefully this works...

**Comment by pbek** [comment]
@rullzer the last test brought my NC version up to 12.0.0.10, after checking out `stable11-2648` I get an error message `Downgrading is not supported and is likely to cause unpredictable issues (from 12.0.0.10 to 11.0.0.10)`, is there a way to get around that?

**Comment by rullzer** [comment]
@pbek uhm. If it is a live instance better not. If this works for @LukasReschke I'll create a master PR you should then be able to test.

**Comment by pbek** [comment]
@rullzer, no, I just created that instance for testing the CalDAV PRs.

**Comment by rullzer** [comment]
ah uhm. Well either install again. Or edit the version in `config/config.php`

**Comment by pbek** [comment]
I went for the latter.
Now I'm happy to confirm that the PUT request went through (with an empty return body) and the ICS was modified on the server. QOwnNotes also works again with that branch!
Great job, @rullzer!

**Comment by mariokorte** [comment]
@rullzer I too can confirm your fix works! Thanks a million!

**Comment by rullzer** [comment]
Phew. Ok let me wait for a review of @LukasReschke and then this can hopefully soon go in :D

**Comment by rullzer** [comment]
Failing tests are unrelated (jsunit + timeout)

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
