### PR TITLE
fix versions icons

### LINKED ISSUE #33860: download button not visible in versions sidebar with dark mode
See 
image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/33860

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by Leptopoda** [comment]
According to the screenshot it looks like the small revert icon on the right is still black.
Couldn't find a separate issue for that so just mentioning it here :)

**Comment by szaimen** [comment]
> According to the screenshot it looks like the small revert icon on the right is still black.
> Couldn't find a separate issue for that so just mentioning it here :)

right, didn't see that. will see how to fix that 👍

**Comment by szaimen** [comment]
> > According to the screenshot it looks like the small revert icon on the right is still black.
> > Couldn't find a separate issue for that so just mentioning it here :)
> 
> right, didn't see that. will see how to fix that 👍

fixed

**Review by CarlSchwan — APPROVED** [review]

**Review by blizzz — APPROVED** [review]
screenshot convinced me

**Pull request merged**
