### PR TITLE
Fix hidden file list master

### LINKED ISSUE #388: Can't hide file list - "Can't change permissions for public share links"
### Steps to reproduce
1. Create a folder
2. Share with link
3. Allow editing
4. Hide file list

### Expected behaviour
:ballot_box_with_check: 

### Actual behaviour

> **Error while sharing**
Can't change permissions for public share links

### Server configuration
**Operating system**: Linux Mint 18

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.6.23

**Nextcloud version:** master

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** git

**Signing status (Nextcloud 9.0 and above):**
Unchanged

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - password_policy: 1.0.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - theming: 0.1.0
  - updatenotification: 0.2.1
Disabled:
  - admin_audit
  - comments
  - encryption
  - files_external
  - firstrunwizard
  - testing
  - user_ldap
  - user_saml
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 47, Chromium 51

**Operating system:** Linux Mint 18

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
Empty

#### Browser log
Empty

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #388 

Regression from 955635c7aaaf932c698069a08ff8f218f0ea990c

### CODE REVIEW

**Comment by rullzer** [comment]
Nice catch.
Could you add intergration tests?

**Comment by schiessle** [comment]
tested, works and code looks good :+1:

**Comment by nickvergessen** [comment]
I fixed the tests (they didn't check the return on the update call) and then added a new one that fails before and works afterwards

**Comment by LukasReschke** [comment]
👍

**Pull request merged**
