### PR TITLE
Remove Google+ from Social Sharing Bundle

### PR DESCRIPTION
**Pull request by MariusBluem**

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
sure

**Review by MorrisJobke — APPROVED** [review]

**Comment by rBradderzz** [comment]
Brad.roberts@cloud53.co.uk<mailto:Brad.roberts@cloud53.co.uk> left the company sometime ago however hundreds of emails per day are being sent to him from yourself – could the address be removed from your database please?

[Cloud53 Ltd]

Craig Robinson | Director

T: 0333 444 5353 | M: 07710 100 949

E: craig.robinson@cloud53.co.uk

W: http://www.cloud53.co.uk<http://www.cloud53.co.uk/>

[cid:image002.png@01D06D56.B6D93E50]<http://www.cloud53.co.uk/brochures/cloud53.pdf>Click here for the Cloud53 Service summary<http://www.cloud53.co.uk/brochures/cloud53.pdf>
[icon-googleplus_28x28]<https://plus.google.com/112106875848692053939/about>[icon-facebook_28x28]<https://www.facebook.com/pages/Cloud53/1401200130189347>[icon-linkedin_28x28]<https://www.linkedin.com/company/cloud53-ltd>[icon-twitter_28x28]<http://www.twitter.com/Cloud53ltd>

[http://www.linkedin.com/img/webpromo/btn_viewmy_160x25.gif]<http://uk.linkedin.com/in/craigrobinson>

**Comment by MorrisJobke** [comment]
> Brad.roberts@cloud53.co.uk<mailto:Brad.roberts@cloud53.co.uk> left the company sometime ago however hundreds of emails per day are being sent to him from yourself – could the address be removed from your database please?

@rBradderzz Please contact Github.

**Pull request merged**
