### PR TITLE
Add CSS for styling of keyboard shortcuts view

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @nextcloud/mail & @nextcloud/designers cc @BernhardPosselt 

capture du 2017-03-30 12-51-15

CSS needed for https://github.com/nextcloud/mail/pull/91

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Oh wow, that looks really neaet

**Comment by BernhardPosselt** [comment]
:+1:

**Comment by jancborchardt** [comment]
@BernhardPosselt thanks! :) I just modified the styles that I think came from you (or the News app) originally. Or they are from @Gomez.

Anyhow now we can simply use the `class="section"` on the outer part and `<dl>` definition list for the shortcuts and it will look nice. :)

**Review by LukasReschke — APPROVED** [review]

**Comment by jancborchardt** [comment]
Please also review the backports for stable11 https://github.com/nextcloud/server/pull/4257 and stable10 https://github.com/nextcloud/server/pull/4258

**Comment by MorrisJobke** [comment]
@jancborchardt If you create the backports then please also remove the label

**Pull request merged**
