### PR TITLE
Better dav display names

### PR DESCRIPTION
**Pull request by nickvergessen**
### Before

`calendar(uid)`
- missing space before the brackets?
- uid instead of display name
### After

`calendar (display name)`

Ref https://help.nextcloud.com/t/ok-to-use-username-in-all-big-caps-with-nextcloud/2309/4

### CODE REVIEW

**Comment by LukasReschke** [comment]
> PHP Fatal error:  Access level to OCA\DAV\Tests\unit\DAV\Migration\ClassificationTest::$userManager must be protected (as in class OCA\DAV\Tests\unit\CalDAV\AbstractCalDavBackendTest) or weaker in /drone/src/github.com/nextcloud/server/apps/dav/tests/unit/Migration/ClassificationTest.php on line 37

**Comment by nickvergessen** [comment]
Test files depending on each others :see_no_evil:

**Comment by rullzer** [comment]
Rebased so cal/card dav tests can run again

**Comment by rullzer** [comment]
Mmmm so does this break syncing? Because the name can change?

**Comment by nickvergessen** [comment]
> Mmmm so does this break syncing? Because the name can change?

The URI stays the same, only the display name changes. I didn't experience any problems

**Comment by rullzer** [comment]
Right. Seems davdroid agress with you ;)
:+1:

**Comment by LukasReschke** [comment]
👍

**Pull request merged**
