### PR TITLE
[Stable12] fix scss webroot and url rewrite

### PR DESCRIPTION
**Pull request by skjnldsv**
Backport of #7631 
  
Allow scss to proberly work and cache file whatever situation they're in:

- Sub-directory nc installation
- Sub-directory nc installation with a non-root app_path
- Basic nc installation with a non-root path

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by juliushaertl** [comment]
This breaks core icons after changing the color value in the theming app (what triggers rebuilding the core scss):

```
.icon-settings {
    background-image: url('//core/css/../img/actions/settings.svg?v=1');
}
```

**Review by juliusknorr — CHANGES_REQUESTED** [review]
See comment.

**Comment by skjnldsv** [comment]
@juliushaertl Hum, strange, I fixed it though. I don't get why there was this error.
Could you check again?

**Comment by juliushaertl** [comment]
Opened #7704 so we don't forget to fix that on master as well.

**Comment by kyrofa** [comment]
I see what @juliushaertl is saying on the snap as well (but not in 12.0.4).

**Review by kyrofa — APPROVED** [review]
I see what @juliushaertl is saying on the snap as well (but not in 12.0.4). Assuming that wasn't introduced in this PR (was it?), +1 from me. I see no behavioral change other than that.

**Review by kyrofa — CHANGES_REQUESTED** [review]
Oh wait, #7631 was this PR to master, huh. Doh! That means this PR does introduce this behavior.

**Comment by skjnldsv** [comment]
@kyrofa yes! :p 
Let me check

**Comment by skjnldsv** [comment]
@juliushaertl can you check again, Maybe we could get rid of the cache reset now that it will proberly erase the files when compiling again? :)

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@kyrofa Please have another look :)

> Maybe we could get rid of the cache reset now that it will proberly erase the files when compiling again? :) 

I don't think so, since we only detect changed variables globally and not per file, we need to make sure that all scss files are invalidated when variables change.

**Comment by skjnldsv** [comment]
@juliushaertl Okay here for me! :)

**Review by kyrofa — APPROVED** [review]
There we go, that seems to work perfectly, even when changing the theme color.

**Pull request merged**
