### PR TITLE
remove trailing space(s) from `var_export`

### PR DESCRIPTION
**Pull request by xerc**
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_whitespace
```diff
-  'enabledPreviewProviders' => 
+  'enabledPreviewProviders' =>
```

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks @xerc for sending a pull request :+1: 

Would you mind to add some words what this patch does and why?

**Comment by xerc** [comment]
"remove trailing space(s) from `var_export`" to NOT show error-mark caused within `git` default turned on `blank-at-eol`

Bildschirmfoto 2022-06-13 um 01 30 27

**Review by xerc — COMMENTED** [review]
`TaintedHtml` false-positives

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Pull request closed without merging**
