### PR TITLE
Remove long depreated AppFramework/Db/Mapper

### PR DESCRIPTION
**Pull request by rullzer**
Deprecated since NC14. :fire:

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
> The autoloaders are not up to date
Please run: bash build/autoloaderchecker.sh
And commit the result

**Comment by rullzer** [comment]
Done @nickvergessen
Seems the drone job just yolo fails

**Review by nickvergessen — APPROVED** [review]

**Comment by DaphneMuller** [comment]
hello @rullzer , 
Thank you for your work on this pull request! This ticket seems to have the tag 'missing documentation', is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/issues/34692#issuecomment-1400843824

**Pull request merged**
