### PR TITLE
Check quota on file copy

### LINKED ISSUE #34975: [Bug]: Quota is not checked and im able to copy files even when i dont have storage
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have reached my quota storage and i try to copy a file that i have already uploaded. The file is copied even though i dont have more space for it. 

Error messages are shown (see below)

### Steps to reproduce

1. Upload files on your NC to reach the maximum storage
2. Copy one of those using action menu of that file
3. See what happens

### Expected behavior

The file is not copied

### Installation method

_No response_

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
mail
calendar
contacts
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

Screenshot from 2022-11-04 17-11-18
Screenshot from 2022-11-04 17-11-05
Screenshot from 2022-11-04 17-02-28

### PR DESCRIPTION
**Pull request by come-nc**
Fixes #34975 

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
psalm not happy and an integration test fails now due to beforeCopy and a dot file that is not allowed. I suspect that the latter is more about a test case doing something dodgy than a bug

**Comment by szaimen** [comment]
Seems like https://drone.nextcloud.com/nextcloud/server/25500/20/3 fails. Not sure if related though...

**Comment by nickvergessen** [comment]
```json
{
  "Exception": "OCA\\DAV\\Connector\\Sabre\\Exception\\InvalidPath",
  "Message": "Dot files are not allowed",
  "Code": 0,
  "Trace": [
    {
      "file": "/drone/src/apps/dav/lib/Connector/Sabre/QuotaPlugin.php",
      "line": 158,
      "function": "getNodeForPath",
      "class": "OCA\\DAV\\Connector\\Sabre\\ObjectTree",
      "type": "->"
    },
    {
      "file": "/drone/src/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
      "line": 89,
      "function": "beforeCopy",
      "class": "OCA\\DAV\\Connector\\Sabre\\QuotaPlugin",
      "type": "->"
    },
    {
      "file": "/drone/src/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
      "line": 648,
      "function": "emit",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/drone/src/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
      "line": 89,
      "function": "httpCopy",
      "class": "Sabre\\DAV\\CorePlugin",
      "type": "->"
    },
    {
      "file": "/drone/src/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 472,
      "function": "emit",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/drone/src/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 253,
      "function": "invokeMethod",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/drone/src/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 321,
      "function": "start",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/drone/src/apps/dav/appinfo/v1/webdav.php",
      "line": 85,
      "function": "exec",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/drone/src/remote.php",
      "line": 171,
      "args": [
        "/drone/src/apps/dav/appinfo/v1/webdav.php"
      ],
      "function": "require_once"
    }
  ],
  "File": "/drone/src/apps/dav/lib/Connector/Sabre/ObjectTree.php",
  "Line": 124,
  "message": "Dot files are not allowed",
  "exception": {},
  "CustomMessage": "Dot files are not allowed"
}
```

Sounds very related

**Comment by icewind1991** [comment]
`basename` will return `"."` if the input has no "/"

**Pull request merged**
