### PR TITLE
fix(files): validate input when creating file/directory

### LINKED ISSUE #46688: [Bug]: 'forbidden_chars' not respected when creating File / Directory
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Creating a new file / directory do not validate for forbidden chars and allows to send a request to server (and fails there)
image

### Steps to reproduce

1. Add forbidden character with `occ config:system:set forbidden_chars 0 --value :`
2. Try to add it when renaming the file
3. Try to add it when creating the file

### Expected behavior

Both are respected as for renaming
image

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"forbidden_chars": [
            ":",
            "\/"
        ],
```
```


### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Antreesy**
* Resolves: #46688

## Summary

Before | After
-- | --
image | image
image | image
image | image

## TODO

- [ ] Review
- [ ] Compile
- [ ] Backport back to stable28

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — CHANGES_REQUESTED** [review]
There is common filename validation now with new nextcloud-files, this function will be removed until beta1 of Nextcloud 30 ;)

**Comment by Antreesy** [comment]
> There is common filename validation now with new nextcloud-files, this function will be removed until beta1 of Nextcloud 30 ;)

I saw some PRs on this, but they're not backported, so - not coming to stable branches?
In that case I can rebase my PR directly on stable29 and continue from there

**Comment by susnux** [comment]
> I saw some PRs on this, but they're not backported, so - not coming to stable branches?

Yes and no, the plan is to use the feature introduced here:
https://github.com/nextcloud-libraries/nextcloud-files/pull/1013

This also works for Nextcloud 28 and 29.

As it is too much work to maintain all three versions if they diverge too much :)

**Comment by Antreesy** [comment]
> This also works for Nextcloud 28 and 29.

Got you there 😉

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
Lets go with this first, as there is a lot of good stuff!
I will then add the library stuff ontop of your changes.

Thank you!

**Review by artonge — APPROVED** [review]

**Pull request merged**
