### PR TITLE
Appstore rating nextcloud blue

### PR DESCRIPTION
**Pull request by williambargentball**
screenshot 20

Personally I wasn't to keen on the yellow, changed the app store ratings to the Nextcloud blue.

Opinions? cc @nextcloud/designers

### CODE REVIEW

**Comment by mar1u5** [comment]
Nah ... I think we should use green, yellow and red for the several categories of apps to make more visible how much you can trust an app 😉

**Comment by jancborchardt** [comment]
I’m not entirely sure we should make _everything_ blue. ;) For example the star to mark files as favorites should stay yellow. And making these rating stars blue would look strange for stars and also reduce contrast in the UI. It shouldn’t become a sea of blue, if you know what I mean. :)

It looks ok though for the »Official« tag, and I’m interested what other @nextcloud/designers @skjnldsv @MorrisJobke @mikebabb @vincchan think.

**Comment by mikebabb** [comment]
@jancborchardt makes a good point about not needing absolutely everything to be Nextcloud blue, particularly things like favouriting and other UI controls. In this instance though I think the stars look quite good; they had a slight gradient to the yellow before and the flat colour in this pull request does make them look a bit more modern.

**Comment by juliushaertl** [comment]
I think the blue stars look far better. The yellow ones have a little less contrast, especially the half stars are kind of hard to see when they are yellow.

**Comment by oparoz** [comment]
I suggest moving this to NC10 since there is no review system in the app store yet.

**Comment by williambargent** [comment]
@oparoz There will still be stars in 9, if we're changing the colour I don't think there is much point in waiting till 10.

**Comment by oparoz** [comment]
@williambargent - Only if you use the ownCloud app store, but that would be strange.

**Comment by williambargent** [comment]
@oparoz Well the owncloud app store is still included, is it being removed until Nextcloud gets its own in 10?

**Comment by oparoz** [comment]
@williambargent - I have no idea what the plan is, but that's a good question to ask at help.nexcloud.com, choosing between the wrong store or a beta version of the new store.

**Comment by williambargent** [comment]
Good ided.
https://help.nextcloud.com/t/nc9-the-wrong-store-or-remove/524

**Comment by jancborchardt** [comment]
> they had a slight gradient to the yellow before and the flat colour in this pull request does make them look a bit more modern

@mikebabb actually on master the stars are flat yellow already.

**Comment by williambargent** [comment]
@oparoz The OwnCloud app store is staying for NextCloud 9, all of the apps will be tested to ensure compatibility. If this PR is approved I think its fine going into this release.

**Comment by jancborchardt** [comment]
I’d prefer to leave the stars at yellow for aforementioned reasons. They are flat in master already too. :)

@williambargent the blue for the »Official« tag is quite nice though! Can you prepare a separate pull request with just that change? We can then get that in.
(As you probably already noticed, it’s best to always keep unrelated stuff in separate pull requests. Yes it’s a bit tedious especially for small changes, but often enough there are partly great changes and partly ones we need to modify or are better in master already. :)

**Comment by MorrisJobke** [comment]
> Can you prepare a separate pull request with just that change?

#131

**Comment by MorrisJobke** [comment]
Overall view:

bildschirmfoto 2016-06-16 um 13 14 02


Compared to only change the color of the border (#131):

bildschirmfoto 2016-06-16 um 13 14 15

@nextcloud/designers What do you think? I would go for now with the yellow stars

**Comment by vincchan** [comment]
@MorrisJobke yup yellow stars look better to me.

**Comment by MorrisJobke** [comment]
Maybe make the grey of the empty stars a bit lighter :)

**Comment by jancborchardt** [comment]
Yup, @MorrisJobke a lot better with yellow stars as said. And yeah, the grey can be lighter. Also as @skjnldsv said, please compress the SVG images with svgo.

**Comment by jancborchardt** [comment]
(The grey should be the same grey as the background of the app icons, which is `#ccc`.)

**Pull request closed without merging**
