### PR TITLE
VerifyUserData shall use IAccountManager, not private API

### PR DESCRIPTION
**Pull request by blizzz**
Another yak shaved for #26866

### CODE REVIEW

**Comment by blizzz** [comment]
```
Run composer run cs:check -- --format=checkstyle | cs2pr
> php-cs-fixer fix --dry-run --diff '--format=checkstyle'
Loaded config default from "/home/runner/work/server/server/.php_cs.dist".
Script php-cs-fixer fix --dry-run --diff handling the cs:check event returned with error code 8
Warning: Found violation(s) of type: class_definition
Warning: Found violation(s) of type: no_unused_imports
Warning: Found violation(s) of type: braces
Error: Process completed with exit code 1.
```

not happening locally :-/ Also I do not spot unused imports or such.

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by nickvergessen — APPROVED** [review]
No tests that complain?

**Comment by blizzz** [comment]
> No tests that complain?

Not knowingly and probably not:

Screenshot_20210512_135145

another unrelated test

**Pull request merged**
