### PR TITLE
Add black version of system tags icon

### PR DESCRIPTION
**Pull request by Bugsbane**
Includes PNG (16x16px) and SVG (scoured) versions in black, to be uniform with the other icon files. Addresses https://github.com/nextcloud/server/issues/626#issuecomment-238151238

### CODE REVIEW

**Comment by blizzz** [comment]
@nextcloud/designers

**Comment by mar1u5** [comment]
This fixes #626 - Backport to Nextcloud 10 requested :wink: 

cc @karlitschek

**Comment by karlitschek** [comment]
Awesome!! Please backport :-)

**Comment by mar1u5** [comment]
:+1:

**Comment by rullzer** [comment]
For NC 11 we can do only SVG if I'm not mistaken.

**Comment by mar1u5** [comment]
Thats correct but this is also not done at the other apps. Would be nice if we could have a statement from @jancborchardt :wink:

**Comment by rullzer** [comment]
:+1:

**Comment by mar1u5** [comment]
I will merge this now, as it fixes the problem. I will backport this to Nextcloud 10 💪 
...removing the .png for Nextcloud 11 can be done via a bulk remove of all .png's of the other apps and all other components. For now, it is important to get this fixed in Nextcloud 10 😉

**Comment by jancborchardt** [comment]
Thanks a lot @Bugsbane! :)

**Comment by Bugsbane** [comment]
No problem. Happy to help. :)

**Pull request merged**
