### PR TITLE
Change text color in search box in darktheme, ref #15598

### LINKED ISSUE #15598: Text color in search box is black with darktheme (should stay white)
### Steps to reproduce
1. i.e  https://cloud.nextcloud.com
2. On settings, change your theme into dark
3. Click on search icon and type something

### Expected behaviour
The font color should stay white (or color-primary-text)

### Actual behaviour
The font color is black ( color-primary-text seems to get inverted for some reasons)

### Server configuration

**Operating system**:
Ubuntu 18
**Nextcloud version:** (see Nextcloud admin page)
Latest master

@nextcloud/theming 
font_darktheme

### PR DESCRIPTION
**Pull request by GretaD**
I need to fix the color-primary-text variable so it is inverted when the primary-colour is too bright as suggested by skjnldsv here: https://github.com/nextcloud/server/commit/7c10ef6298eb88a2f4ae422950150d9eeb344c75. Another patch will follow.

Fixes #15598

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Tested and looks good :+1:

**Comment by jancborchardt** [comment]
@ChristophWurst @GretaD it’s set to "developing", anything left to do? Cause it does seem to work nicely.

cc @nextcloud/designers for review. :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
CI failures are only timeouts -> good to be merged.

**Comment by MorrisJobke** [comment]
> @ChristophWurst @GretaD it’s set to "developing", anything left to do? Cause it does seem to work nicely.

I guess that was fixed after @ChristophWurst changed it to that. Let's merge it as it is working as expected.

**Pull request merged**
