### PR TITLE
Fix various errors reported by eslint

### PR DESCRIPTION
**Pull request by CarlSchwan**
And also make sure eslint doesn't try to index apps-extra that contains
other repo with not necessarely the same eslint rules

Todo need a `npm run build && npm run sass && npm run sass:icons` and a rebase before merging

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by skjnldsv** [comment]
> And also make sure eslint doesn't try to index apps-extra that contains other repo with not necessarely the same eslint rules
> 
> Todo need a `npm run build && npm run sass && npm run sass:icons` and a rebase before merging

Btw, we could add a `postbuild` running `npm run sass && npm run sass:icons` so that everytime we run npm run build, it also builds the sass and icons automatically afterwards! :wink:

**Comment by nickvergessen** [comment]
Could also add a CI step to make sure it was ran.

**Comment by skjnldsv** [comment]
> Could also add a CI step to make sure it was ran.

Already here :wink:

**Comment by CarlSchwan** [comment]
Ci is completely green :exploding_head:  , I still need one approval ;)

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
