### PR TITLE
Migrate backup codes settings to Vue

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/11034.

ToDo:
- [x] Check if bundled js is up-to-date on Drone. cc @skjnldsv

### CODE REVIEW

**Comment by ChristophWurst** [comment]
>     * Check if bundled js is up-to-date on Drone. cc @skjnldsv

Could you help with that? Or at least give me some pointers? :smile:

**Comment by skjnldsv** [comment]
> > ```
> > * Check if bundled js is up-to-date on Drone. cc @skjnldsv
> > ```
> 
> Could you help with that? Or at least give me some pointers?

https://github.com/nextcloud/notifications/blob/master/tests/vue-build.sh
https://github.com/nextcloud/notifications/blob/master/.drone.yml#L22 :grin:

**Comment by rullzer** [comment]
Seems also some webpack stuff etc needs to be moved to the standard format

**Comment by rullzer** [comment]
Once this is in I'll also setup dependabot for it

**Comment by ChristophWurst** [comment]
@rullzer thanks a lot!

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Works here :D thnx for fixing it.
Lets get it in :D

**Review by skjnldsv — CHANGES_REQUESTED** [review]
- [ ] buttons should be hidden if 2fa is disabled?
    capture d ecran_2018-09-26_12-26-32
- [ ] Clicking the generate code did not worked, I had to click regenerate

**Comment by ChristophWurst** [comment]
>     * buttons should be hidden if 2fa is disabled?

What buttons? TOTP and backup codes are completely separate, there is no connection between the two (yet, see #11380).

**Comment by ChristophWurst** [comment]
>     * Clicking the generate code did not worked, I had to click regenerate

Fixed :+1:

**Comment by skjnldsv** [comment]
> What buttons? TOTP and backup codes are completely separate, there is no connection between the two (yet, see #11380).

Well, those don't do anything if 2fa is disabled (the generate bttons), so I was confused :)

**Comment by rullzer** [comment]
@skjnldsv could you retry?

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
