### PR TITLE
[3rdparty] Bump id3parser to 0.10

### LINKED ISSUE #17291: id3parser does not use 'tempdirectory', violating open_basedir
### Steps to reproduce
1. Have some music files in nextcloud
2. Visit the containing folder

### Expected behaviour
No error

### Actual behaviour
Nextcloud issues error messages

### Server configuration

**Operating system**: Debian unstable

**Web server:** apache 2.4.41-1

**Database:** mariadb 1:10.3.18-1

**PHP version:** 7.3.9-1

**Nextcloud version:** 16.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "tempdirectory": "\/var\/www\/nextcloud\/tmp",
        "log_type": "syslog",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "mydomain"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Sep 26 22:58:12 server02 Nextcloud[9532]: {PHP} tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/var/www/) at /var/www/sites/nextcloud/3rdparty/lukasreschke/id3parser/src/getID3/getid3_lib.php#1001
</details>

### PR DESCRIPTION
**Pull request by kesselb**
Fix #17291

Requires:

- [x] https://github.com/nextcloud/3rdparty/pull/356
- [x] Happy CI :robot:

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
>     * nextcloud/3rdparty#356

Please rebase to the new 3rdparty commit

**Review by gary-kim — APPROVED** [review]

**Comment by gary-kim** [comment]
Looks like the CI isn't happy

**Comment by ChristophWurst** [comment]
Closed accidentally?

**Comment by kesselb** [comment]
Yes and No ;) I rebased the branch to master and dropped the commit thus GitHub closing it. Somehow I failed to push a fixed commit and created a new pull request but now the commit is back. Hmm :man_shrugging:

**Comment by gary-kim** [comment]
Even GitHub is confused. None of the webhooks were called. Do you want to just push an empty fixup commit or something?

**Comment by gary-kim** [comment]
Other than the errored tests, no failed tests in CI.

**Pull request merged**
