### PR TITLE
Vueify the login page

### LINKED ISSUE #15584: Vue login page
**Is your feature request related to a problem? Please describe.**

The login page is plain old jQuery.

**Describe the solution you'd like**

I would like to replace that with a Vue component.

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/orgs/nextcloud/projects/31

---

@nextcloud/javascript @nextcloud/vue objects? Could this break any third party apps that inject random stuff into that page? If so, should we add proper APIs for that stuff?

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes #15584 

Todo

- [x] Basic component
- [x] Template vars to initial state migration
- [x] Apache auth error
- [x] Login message rendering
- [x] Internal exception handling
- [x] Username from URL handling
- [x] Wrong password message
- [x] User disabled message
- [x] Autofocus
- [x] Autocomplete
- [x] Animations
- [x] Password lost email
- [x] Password reset
- [x] LoginController tests

Bugs

- [x] `.shake` does not shake :cry:

### CODE REVIEW

**Comment by ChristophWurst** [comment]
>     * `.shake` does not shake cry

@skjnldsv ideas? :)

**Comment by skjnldsv** [comment]
> @skjnldsv ideas? :)

Done!
Could you merge the style from guest into the scope one? It will allow us to only load what we need and have a nice cleanup here :)

**Review by rullzer — APPROVED** [review]
I like it!

**Comment by ChristophWurst** [comment]
CI failure is unrelated and fixed in https://github.com/nextcloud/server/pull/15789

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Could you open an issue for the style cleanup? :heart:

**Pull request merged**
