### PR TITLE
13.0.9 RC 1

### PR DESCRIPTION
**Pull request by MorrisJobke**
Changelog to 13.0.8 (#12585):

* #12595 Load apps that have a dav type set before the dav server plugins
* #12616 Fix typo in original english string and all translations
* #12818 Fix the system address book
* #12827 PHP module is named mbstring
* #12835 Do not update child all child shares on group share update
* #12864 Only execute query in propagateChange once
* #13125 Fix SAML Client login flow on Apple devices
* #13153 Prevent special characters from breaking the file drop remote url
* #13220 Do not forgot to store the second displayname portion
* #13359 Update the CRL
* [files_pdfviewer#116](https://github.com/nextcloud/files_pdfviewer/pull/116) Fix PDF sidebar shown in PDF thumbnails

Pending PRs:

* [x] #13374 Fix loginflow with apptoken enter on iOS

cc @rullzer @skjnldsv @juliushaertl

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Something in the git history is weird:

That is the tag: https://github.com/nextcloud/server/releases/tag/v13.0.8

If the tag is used as comparison base it looks like there are even commits from 13.0.6 included: https://github.com/nextcloud/server/compare/v13.0.8...stable13

But if the commit hash is used it looks fine: https://github.com/nextcloud/server/compare/a966d7f...stable13

Any ideas?

**Comment by rullzer** [comment]
Fixed. Seems I crated a branch somewhere once with that name.

**Comment by juliushaertl** [comment]
Looks on a local `git log v13.0.8...stable13` maybe a github issue?

**Comment by MorrisJobke** [comment]
> Fixed. Seems I crated a branch somewhere once with that name.

Ah - didn't thought about this 🙈

**Comment by rullzer** [comment]
Rebased since all is in now

**Pull request merged**
