### PR TITLE
Fix display name ignored when creating new user

### PR DESCRIPTION
**Pull request by danxuliu**
Follow-up to #7600

Before #7600 when a new user was created it was possible to set its user name, password and groups. In #7600 the display name and the e-mail were added to the form, but the display name was not taken into account when the new user was created (the e-mail, on the other hand, was).

This pull request adds an optional parameter to the create user endpoint to make possible to specify the display name and sends the display name set (if any) in the form when creating a user.

**How to test**
- Open the _Users_ settings
- Create a new user with an explicit display name

**Expected result**
The display name of the new user is set to the desired one.

**Actual result**
The display name of the new user is the default display name, which is the same as the user name.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
That explains why I was confused because the displays me was not how I thought I typed it in😅

**Comment by skjnldsv** [comment]
Since we're going to switch to the new users list, all of this is fixed already since we're now using our ocs api to create users. Old legacy code like this one is being cleaned :/

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by danxuliu** [comment]
I have amended the last commit as I had forgotten to add the step to the matrix (and thus it was not executed by Drone).

**Comment by MorrisJobke** [comment]
CI failure is unrelated.

**Comment by skjnldsv** [comment]
Did someone read my message above? :grin: :heart:

**Comment by danxuliu** [comment]
@skjnldsv 
>  Since we're going to switch to the new users list, all of this is fixed already since we're now using our ocs api to create users. Old legacy code like this one is being cleaned :/

All of this is fixed already... but where? :-P I mean, in current master if you create a user with a custom display name that name is ignored, so I guess that it is fixed in some branch that will become a pull request in the future. Therefore, if these changes affect or conflict in any way with your work you can close this, but if they do not I would merge this now even if it is going to be thrown away in the future.

**Comment by skjnldsv** [comment]
@danxuliu aaand you're right, somehow I missed that!
I thought I pushed it already :/

https://github.com/nextcloud/server/blob/master/apps/provisioning_api/lib/Controller/UsersController.php#L205

**Comment by MorrisJobke** [comment]
@skjnldsv @danxuliu What is the status here?

**Comment by skjnldsv** [comment]
My point (tell me what you think @danxuliu :) ) is: since we want to drop old legacy stuf (so the Userscontroller users management parts), maybe we should edit this pr to add the new method to the ocs api instead :)

This way we can easily add this ti the vue settings pr as well ;)

**Comment by danxuliu** [comment]
@skjnldsv 
>  since we want to drop old legacy stuf (so the Userscontroller users management parts), maybe we should edit this pr to add the new method to the ocs api instead :)

But then you would be using the OCS API to create new users while the rest of [settings/js/users/users.js](https://github.com/nextcloud/server/blob/51ec928623fe5d2aa0b010546f59807513c32052/settings/js/users/users.js) would be using the legacy AJAX calls. The new and the legacy parts can work together without problems, right?

Personally I would merge the fix now and then add another pull request to move to the new API instead of fixing while moving, but it is just my usual nitpicking, so you have my blessing if you want to do it that way too ;-)

**Comment by skjnldsv** [comment]
@danxuliu could you add the input to the ocs api anyway?
It will be a pain to rebase though :p 

As a record, this will be override completely this week with the new migration ;)

**Comment by danxuliu** [comment]
>  could you add the input to the ocs api anyway?

Sure ;-)

>  It will be a pain to rebase though :p

Rebase what onto what?

>  this will be override completely this week with the new migration ;)

You do not need to _subtly_ try to change my mind, I already told you that you can do it the other way if you want :-P

**Comment by MorrisJobke** [comment]
Rebased on master. Basically the code was dropped but then we have at least the acceptance tests 😉

**Comment by skjnldsv** [comment]
We still need to add this to the ocs api

**Comment by MorrisJobke** [comment]
@skjnldsv Status of this?

**Comment by skjnldsv** [comment]
@MorrisJobke ocs api is still not included in this pr: @danxuliu 
https://github.com/nextcloud/server/blob/3ffeb4ae060d97b9306a2c243332d3a137b1e464/apps/provisioning_api/lib/Controller/UsersController.php#L210-L216

**Comment by danxuliu** [comment]
> ocs api is still not included in this pr

I will take care of that, although I want to fix some things in the acceptance tests before doing it (of course if that takes me longer than expected I will send these changes anyway before Beta 1).

**Comment by danxuliu** [comment]
>  >  ocs api is still not included in this pr
>  
>  I will take care of that, although I want to fix some things in the acceptance tests before doing it

I will not be able to fix those things in the acceptance tests before Beta 2, so I have updated this pull request with the fix to the OCS API. This is now ready to be reviewed.

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
I pushed the compiled vue stuff

**Comment by danxuliu** [comment]
@rullzer 
>  I pushed the compiled vue stuff

I had built (running just `make` in the _settings_ dir) and pushed the built files along with the commit in which I modified the JavaScript, so I do not know why https://drone.nextcloud.com/nextcloud/server/9344/85 failed. Any idea of what I did wrong?

Anyway thanks for the fix ;-)

**Comment by rullzer** [comment]
@danxuliu no idea. Maybe the rebase messed things up?
Anyway good to go now I guess :D

**Pull request merged**
