### PR TITLE
fix(settings): set viewBox on SVG icons

### PR DESCRIPTION
**Pull request by ShGKme**
## Summary

Added missing `viewBox` to SVG icons in settings. Without `viewBox` they don't scale.

For example, on the Users page when there are no users.

No changes in other places.

🏚️ Before | 🏡 After
---|---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by giantmolecules1** [comment]
Run

**Review by artonge — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
Makes sense

**Comment by ShGKme** [comment]
Drone is not related, I cannot restart it...

**Review by Pytal — APPROVED** [review]

**Pull request merged**
