### PR TITLE
Fix permissions when copying from ObjectStorage

### PR DESCRIPTION
**Pull request by CarlSchwan**
Make sure that when a user copy a file from a directory they don't have
all permissions to a directory where they have more permissions, the
permissions are correctly set to the one from the parent taget folder.

This was caused by the ObjectStoreStorage::copyFromStorage using
the jailed storage and cache entry instead of the unjailed one like other
storages (the local one).

## Steps to reproduce

1. Use object storage
2. Create a groupfolder with one group having full permission and another one
who can just read files.
3. With an user who is in the second group, copy a file from the groupfolder to
    the home folder of this user.
4. The file in the home folder of the user will be read only and can't be deleted
    even though it is in their home folder and they are the owner.
    In oc_filecache, the permissions stored for this file are 1 (READ)

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Comment by PVince81** [comment]
> Wouldn't it make more sense to create a new scanner dedicated to object storage?

There is nothing to scan in a primary object storage, so having one would semantically mismatch.

Strange that conceptually it's usually the Scanner that sets the permission.

**Review by icewind1991 — COMMENTED** [review]
Instead of unwrapping the `Jail` wrappers it should unwrap the `PermissionsMask`

alternatively you can check for `$cacheEntry['scan_permissions']`, (not available trough a getter on `ICacheEntry` only trough array access) which is used already used to set the proper permissions while scanner a permissions masked storage

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by CarlSchwan** [comment]
friendly ping :D

**Comment by PVince81** [comment]
@icewind1991 can you approve ? it follows your suggestion from last time about "scan_permissions"

**Review by juliusknorr — APPROVED** [review]
Some code comment would be nice as @skjnldsv suggested, otherwise seems fine :+1:

**Pull request merged**
