### PR TITLE
Principals can be principal/user/<name> or principal/<name> from lega…

### PR DESCRIPTION
**Pull request by nickvergessen**
…cy installs

At least there is a conversion method:
https://github.com/nextcloud/server/blob/d3d045dd5c5af5f29268727afe63f3c53d22af6c/apps/dav/lib/Connector/LegacyDAVACL.php#L53-L59
And a matching report by @cunningwasabi in https://github.com/nextcloud/server/issues/13499#issuecomment-453795334

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Review by blizzz — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
:+1:

**Comment by skjnldsv** [comment]
Failure seems unrelated

**Pull request merged**
