### PR TITLE
Mount configuration handlers for external storages

### PR DESCRIPTION
**Pull request by blizzz**
This introduces configuration handlers (and a registration method) for files_external. Previously, replacing of "$user" with the uid was hardcoded.

The LDAP backend was extended to take advantage of this mechanism, implementing a placeholder for "$home".

LDAP config:

screenshot_20190213_125756

External storage config example (one invalid with unreplaced placeholder, and the one valid):

screenshot_20190213_130157

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Comment by blizzz** [comment]
_rebased to resolve merge conflict_

**Review by rullzer — APPROVED** [review]
Looks good to me but I'd like @icewind1991 to have a look as well.

**Comment by icewind1991** [comment]
Code and documentation seem to disagree between using `@` or `$` as the placeholder prefix

looks good otherwise

**Comment by blizzz** [comment]
Thx @icewind1991, good catch, i'll fix the doc later this evening. then it also should be good to merge .

**Comment by MorrisJobke** [comment]
Regression: #15654

**Pull request merged**
