### PR TITLE
Add app config for default template path

### PR DESCRIPTION
**Pull request by tcitworld**
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — COMMENTED** [review]
Is this a new configuration options ? If so, this will need to be added to the documentation. :)

**Comment by tcitworld** [comment]
I used an app config instead of a system config value as this can be sensitive (could be a bad idea to use a path mounted on external storage for instance) and I don't think we document those. But otherwise I don't have any specific opinion on this.

**Review by juliusknorr — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by tcitworld** [comment]
Docs are in https://github.com/nextcloud/documentation/pull/9569

**Comment by juliushaertl** [comment]
Failures seem unrelated.

**Pull request merged**
