### PR TITLE
Mark all content in search field

### LINKED ISSUE #2310: When using Ctrl-F and there’s already content in the Nextcloud search field, mark it all
This is also how other search functions work, like the one in the browser. It allows you to just directly start typing to search for something new, or modify the existing search term.

### PR DESCRIPTION
**Pull request by Morlinest**
Fix #2310

### CODE REVIEW

**Comment by nickvergessen** [comment]
Works 👍

**Review by nickvergessen — APPROVED** [review]

**Comment by LukasReschke** [comment]
LGTM

**Comment by jancborchardt** [comment]
Awesome @Morlinest, thanks a lot for your contribution and welcome to Nextcoud! :) :tada:

**Comment by Morlinest** [comment]
Thanks @jancborchardt

**Pull request merged**
