### PR TITLE
Use the external initial state implementation

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/nextcloud-initial-state/pull/22

- [x] Requires github.com/nextcloud/server/pull/17367 for green CI

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> +403,821 −1,666 

:thinking: :thinking: :thinking:

**Comment by rullzer** [comment]
Rebased and fixed the eslint warnings...

**Comment by rullzer** [comment]
> +23,925 −263

still a lot

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Let's figure out what the heck is going on before merging :)

**Comment by ChristophWurst** [comment]
> +245 −268

@skjnldsv better?

**Comment by skjnldsv** [comment]
Tests will not pass, right?
We need to edit drone.yml?

**Comment by ChristophWurst** [comment]
> Tests will not pass, right?
> We need to edit drone.yml?

They also passed at https://github.com/nextcloud/server/pull/17392#event-2689549037, where I think you've used "npm ci" because master build is not reproducible for me right now.

**Comment by skjnldsv** [comment]
Failed ;)

**Pull request merged**
