### PR TITLE
Settings icon for LDAP and encryption

### PR DESCRIPTION
**Pull request by MorrisJobke**
* follow up to #3151 

bildschirmfoto 2017-01-24 um 13 01 27
bildschirmfoto 2017-01-24 um 13 01 33

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
fancy!

**Review by nickvergessen — CHANGES_REQUESTED** [review]
```
There was 1 failure:
1) OCA\User_LDAP\Tests\Settings\SectionTest::testGetIcon
Expectation failed for method name is equal to <string:imagePath> when invoked 1 time(s)
Parameter 1 for invocation OCP\IURLGenerator::imagePath('user_ldap', 'app-dark.svg') does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'app.svg'
+'app-dark.svg'
/drone/src/github.com/nextcloud/server/apps/user_ldap/lib/Settings/Section.php:80
/drone/src/github.com/nextcloud/server/apps/user_ldap/tests/Settings/SectionTest.php:74

**Review by nickvergessen — APPROVED** [review]

**Review by jancborchardt — DISMISSED** [review]
Can you use the icon for multiple people instead of a single person? :) That makes more sense.

**Comment by nickvergessen** [comment]
Well that is the current app icon:
> apps_-_nodesign_-_2017-01-25_11 32 20


So if we change this, we should change both.

**Review by blizzz — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
