### PR TITLE
Feature/10124/quota takes too much space

### PR DESCRIPTION
**Pull request by newhinton**
See #10124
Closes #10245

### CODE REVIEW

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Some cleanup of the git history would be nice, but the code looks good 👍

**Comment by jancborchardt** [comment]
@newhinton as review, but also answering to your comment at https://github.com/nextcloud/server/issues/10124#issuecomment-406748110


> Consider a combination like this:
> 200B of 500GB

In that case simply use "less than":

> <0.1 of 500 GB used

We should not show the unit twice, and using two different units is confusing for quick info gathering.

**Comment by newhinton** [comment]
@jancborchardt I have implemented the minimalistic way

@MorrisJobke I would sqash, or change the history (i messed it quite up) but git for windows and the pgp-signing don't play well together. If you wish, i could make a new branch?

**Comment by newhinton** [comment]
@jancborchardt @MorrisJobke While i was recreating the pr, i discussed this with some people, and we had the great idea to not show the used size at all. Something like 65% of 6TB would be way more informative to the user on the first glance, and when he needs more precise information, he can look at the tooltip/his settings.

( Maybe we could create a modal in the future, which opens when the quota item is clicked, as i discussed with @jancborchardt )

**Pull request closed without merging**
