### PR TITLE
Use shared browserslist config

### LINKED ISSUE #13962: browserslist config package
While in the process of defining a list of supported browsers. We should create a package out of this so all apps can easily use it as well. See https://github.com/browserslist/browserslist#shareable-configs

I could envision this as follows.

* A basic package version that just defines what we support.
* Packages bound to the nextcloud version. Because NC13 supports different firefox versions than NC16 will.

@nextcloud/javascript

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/13962

Ref https://github.com/ChristophWurst/browserslist-config-nextcloud
Ref https://www.npmjs.com/package/browserslist-config-nextcloud

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
:heart:

**Review by georgehrke — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
`modified: apps/files_sharing/js/dist/files_sharing.3.js.map`

**Comment by ChristophWurst** [comment]
> modified: apps/files_sharing/js/dist/files_sharing.3.js.map

Fixed. And rebased. And fixed some outdated bundle files from other PRs …

**Review by GretaD — APPROVED** [review]

**Comment by ChristophWurst** [comment]
@skjnldsv merge

**Comment by danxuliu** [comment]
I guess that this should be applied too to the [Babel configuration in settings](https://github.com/nextcloud/server/blob/5cec23d840ed0adc10ea717a59df4e42bfbdbf30/settings/.babelrc.js), although note that in that configuration the `@babel/plugin-syntax-dynamic-import` plugin is used (I do not know if it can be dropped nor how to keep it in the new configuration, I just mention it so it is kept in mind ;-) ).

**Comment by ChristophWurst** [comment]
@danxuliu hmmmm good point. I wonder if we still need the custom babel config for settings. Can't we just remove that one?

**Comment by skjnldsv** [comment]
There are places where we use specific plugins still :)

**Comment by ChristophWurst** [comment]
Why is that? Can we unify that?

**Comment by skjnldsv** [comment]
I guess we can have a global plugin for nextcloud and we can still use specific ones if we need them? :)

**Comment by ChristophWurst** [comment]
Of course! Just extend the new share config and add your plugin additionally. https://github.com/nextcloud/viewer/blob/ae514800feb2c25d8fc79f15bd267a24b26e0022/.babelrc.js#L9-L18 is the part that should die :)

**Comment by danxuliu** [comment]
@ChristophWurst If I am not mistaken the part that should die would be https://github.com/nextcloud/viewer/blob/ae514800feb2c25d8fc79f15bd267a24b26e0022/.babelrc.js#L12-L16 instead (like in this pull request that `@babel/preset-env` was kept in the presets and [only the target browsers were removed from the Babel configuration](https://github.com/nextcloud/server/pull/15988/files#diff-e56633f72ecc521128b3db6586074d2cL7)).

**Comment by ChristophWurst** [comment]
> @ChristophWurst If I am not mistaken the part that should die would be https://github.com/nextcloud/viewer/blob/ae514800feb2c25d8fc79f15bd267a24b26e0022/.babelrc.js#L12-L16 instead (like in this pull request that `@babel/preset-env` was kept in the presets and [only the target browsers were removed from the Babel configuration](https://github.com/nextcloud/server/pull/15988/files#diff-e56633f72ecc521128b3db6586074d2cL7)).

Oh, yes, of course. We have a shared browserslist config and not babel config. You're right :)

**Pull request merged**
