### PR TITLE
Prevent harder to share your root

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Makes sense

**Review by marcoambrosini — APPROVED** [review]

**Review by georgehrke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
CI says no

**Comment by nickvergessen** [comment]
Right, adjusted

**Pull request merged**
