### PR TITLE
[stable20] Do not escape display name in dashboard welcome text

### LINKED ISSUE #26113: Very annoying welcome message issue with data-user-displayname
Hi to all,
can you suggest me how to solve this encoding problem (letters with accents in data-user-displayname)?
it is present only on the welcome message, not anywhere.
Thanks a lot.

Screen Shot 2021-03-15 at 08 40 01

### PR DESCRIPTION
**Pull request by julien-nc**
fixes #26113

Same as #27912 for stable20

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by szaimen** [comment]
conflicts

**Review by szaimen — APPROVED** [review]

**Pull request merged**
