### PR TITLE
fix(log): Log exception class when message is empty

### PR DESCRIPTION
**Pull request by nickvergessen**
* Resolves:
*  Before is first line
* After is last line

grafik

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by tcitworld — APPROVED** [review]
Maybe add an `"Exception thrown:"` prefix for context?

**Review by ChristophWurst — APPROVED** [review]
Can we also find out where an empty log message is logged?

**Comment by nickvergessen** [comment]
> Can we also find out where an empty log message is logged?

The error from production was in logged via this: https://github.com/nextcloud/server/blob/bb2c2bb7f0aa57ad7e77a914fb341e2535801da9/index.php#L81

**Comment by nickvergessen** [comment]
Added the prefix

**Pull request merged**
