### PR TITLE
Checksum verification

### PR DESCRIPTION
**Pull request by nickvergessen**
Downstream 27689 + others

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I cherry picked the fixed stuff from @icewind1991 from #4023 and the only diff that my PR and your PR had.

@icewind1991 @nickvergessen Please have a look at it if this still makes sense.

**Comment by nickvergessen** [comment]
I have no idea, I just cherry-picked. Hopefully icewind can

**Comment by MorrisJobke** [comment]
@icewind1991 @rullzer we need your help here

**Comment by MorrisJobke** [comment]
> @icewind1991 @rullzer we need your help here

Ping

**Comment by MorrisJobke** [comment]
Also nothing for 12.

**Comment by MorrisJobke** [comment]
@nickvergessen Any news here?

**Comment by nickvergessen** [comment]
Well I only did the port, I have no idea whether we want this and how good it is and if it works for us...

**Pull request closed without merging**
