### PR TITLE
Remove Acrobat logo from PDF filetype icon

### PR DESCRIPTION
**Pull request by jancborchardt**
The Adobe PDF file icon guidelines are not really clear: https://www.adobe.com/legal/permissions/icons-web-logos.html#pdfs

But there’s a very similar question where there’s a clear answer: https://community.adobe.com/t5/acrobat/pdf-icon-use-legality/m-p/9883407?page=1#M103287

→ We shouldn’t use the Acrobat trefoil, even referring to PDF.

I did a version of the text document in red but it just didn’t look like PDF. Other platforms like Google Drive also use a similar solution with a red icon and "PDF" letters.

Please review @karlitschek @juliushaertl @skjnldsv – we should probably backport to whatever we still support. Also cc @marinofaggiana @tobiasKaminsky as we should also update that in the mobile apps.

(cc @skjnldsv I tried to pixel-align but it’s basically not possible on this small 16px grid while making it look good. It is sort-of aligned to 32px. Looking at it in the different sizes it seems nice.)

### CODE REVIEW

**Comment by skjnldsv** [comment]
> (cc @skjnldsv I tried to pixel-align but it’s basically not possible on this small 16px grid while making it look good. It is sort-of aligned to 32px. Looking at it in the different sizes it seems nice.)

It should looks ok as preview, we're using 32 there :)

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
