### PR TITLE
sidebar: allow turning off tags view by default

### PR DESCRIPTION
**Pull request by pulsejet**
With #37065, there is no way to hide the tags from the sidebar by default when they are not relevant or redundant (e.g. the tab may already show the file's tags). This can be annyoing especially when the file has many tags. This patch adds an option to hide the tags from the sidebar by default (the user can still open the tags tab manually).

This also reduces one request when opening the sidebar when the tags are turned off, since all tags don't need to be fetched anymore.

Screenshot: tags are redundant and take up a lot of space.

image

### CODE REVIEW

**Review by artonge — APPROVED** [review]
This won't be persisted, right ?

**Comment by pulsejet** [comment]
> This won't be persisted, right ?

Yeah, a reload will switch it back to showing the tags again (current behavior). But I expect the app to call this method to not show the tags on load.

**Comment by Pytal** [comment]
> With #37065, there is no way to hide the tags from the sidebar by default when they are not relevant or redundant (e.g. the tab may already show the file's tags).

Worked this way actually since legacy times :)

**Review by Pytal — APPROVED** [review]

**Comment by pulsejet** [comment]
> Worked this way actually since legacy times :)

Well there was `OCA.SystemTags.View.toggle()`. Technically you could combine that with a `MutationObserver` ...

**Comment by Pytal** [comment]
> Well there was `OCA.SystemTags.View.toggle()`. Technically you could combine that with a `MutationObserver` ...

🤯, I suppose default was the same then

**Comment by pulsejet** [comment]
Any reason this was ignored for 28?

**Comment by artonge** [comment]
Beside red CI, I see no reason :)

**Comment by artonge** [comment]
> is it okay if I enable auto-merge on my PRs?

Sure, but some CI steps are not required to auto-merge, so the merge won't get blocked if they don't pass. If you're confident that all tests will pass then go for it :).

> EDIT2: another issue is the quick merge conflict that arises

That's hard to do without. But if you have the needed approvals, and if CI failures are not related, ping one of us stating the situation, and we'll force merge for you.

**Comment by artonge** [comment]
You can also try to restart some failing CI steps. Note that for cypress, you need to restart all the steps and not only the failing ones.

**Comment by solracsf** [comment]
/backport https://github.com/nextcloud/server/commit/424eb124ef2c7b8360d1ed39f006e82f18d9d0f5 to stable28

**Comment by solracsf** [comment]
/backport 424eb124ef2c7b8360d1ed39f006e82f18d9d0f5 to stable28

**Pull request merged**
