### PR TITLE
Port files sharing selector

### PR DESCRIPTION
**Pull request by Pytal**
Before | After
--- | ---
image | image
image | image
image | image

- [x] Verify that selector behaves identically as expected
- [x] Guests app inserts invite guest option and opens modal on select

### CODE REVIEW

**Comment by PVince81** [comment]
@Pytal can you also test with the guests app ? IIRC it injects some results in the dropdown.

in case you're not familiar with the app, after enabling it you can share to an external user by typing an email address, then an extra result will appear that you can pick to send an email to invite that user to the system

**Review by artonge — APPROVED** [review]

**Comment by Pytal** [comment]
Tested and updated description @PVince81

**Comment by Pytal** [comment]
Rebased

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
conflict

**Comment by Pytal** [comment]
Originally opened this PR when vue-select was on `v3.20.0` but retesting now on `v3.20.2` focus is kept on the input after selection so triggering `.focus()` will no longer reopen the dropdown as intended. Adjustments have been made and would appreciate one re-review :)

**Comment by Pytal** [comment]
> Originally opened this PR when vue-select was on `v3.20.0` but retesting now on `v3.20.2` focus is kept on the input after selection so triggering `.focus()` will no longer reopen the dropdown as intended. Adjustments have been made and would appreciate one re-review :)
> 
> Or would accessing it via ref instead of `$children` be better?

Re-ping @PVince81 :) 👆

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
