### PR TITLE
User Status: Display hint that DND mutes all notifications

### PR DESCRIPTION
**Pull request by georgehrke**
73947C1A-92C4-4607-9FB3-C7BECE6E088F

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by georgehrke** [comment]
Should we merge after review or wait until the notifications app was actually adapted to respect the user-status?

**Comment by nickvergessen** [comment]
Reviews please

**Comment by georgehrke** [comment]
Let me rebase

**Review by juliusknorr — APPROVED** [review]

**Comment by georgehrke** [comment]
Rebased yet again

**Pull request merged**
