### PR TITLE
Only load viewer in settings if the viewer app is enabled

### PR DESCRIPTION
**Pull request by MorrisJobke**
Found by Psalm:

```
2 errors fixed
/github/workspace/apps/settings/lib/Settings/Personal/ServerDevNotice.php:83:37:error - UndefinedClass: Class or interface OCA\Viewer\Event\LoadViewer does not exist
/github/workspace/apps/settings/lib/Settings/Personal/ServerDevNotice.php:83:60:error - UndefinedClass: Class or interface OCA\Viewer\Event\LoadViewer does not exist
```

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Regression from #22136

**Comment by kesselb** [comment]
Viewer app is always enabled afaik.

**Review by kesselb — APPROVED** [review]

**Comment by skjnldsv** [comment]
> Viewer app is always enabled afaik.

This :+1: 
You cannot disable nor remove viewer

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> You cannot disable nor remove viewer

Didn't knew that. I thought it is only default enabled. Then we should add it to the external dependencies that are available.

**Comment by MorrisJobke** [comment]
I changed it to a zero-cost check that asserts the obvious, but fails in development environments properly.

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
