### PR TITLE
[11] round the mtime in touch

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/nextcloud/server/pull/4096

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@sf-janz please test this

**Comment by MorrisJobke** [comment]
```
There was 1 error:
1) Test\Files\ViewTest::testTouchFloat
Error: Class 'Test\Files\Filesystem' not found
/drone/src/github.com/nextcloud/server/tests/lib/Files/ViewTest.php:567
```

**Comment by MorrisJobke** [comment]
> @sf-janz please test this

Nevermind - you tested it already: https://github.com/nextcloud/server/issues/4794#issuecomment-300529159

**Comment by icewind1991** [comment]
@MorrisJobke fixed

**Review by rullzer — APPROVED** [review]

**Pull request merged**
