### PR TITLE
add postgresql 10 compatibility to dbal

### PR DESCRIPTION
**Pull request by icewind1991**
- [x] requires https://github.com/nextcloud/3rdparty/pull/70

Update doctrine/dbal to include https://github.com/doctrine/dbal/pull/2893 and https://github.com/doctrine/dbal/pull/2916 to make it work with postgresql 10

### CODE REVIEW

**Review by rullzer — DISMISSED** [review]
Can you add a drone job for postgres10 so we actually know it works ;)

**Comment by icewind1991** [comment]
@rullzer done

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Please update 3rdparty to contain current master.

**Review by LukasReschke — COMMENTED** [review]
Code looks good. Updated the thirdparty ref. Let's see what CI says :)

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
