### PR TITLE
trim filename in webfrontend for windows compatibility

### PR DESCRIPTION
**Pull request by aignerat**
Added trim function in javascript to ensure compatibility with windows

scenario: I create the file "test.txt " and can't synchronize it with my local file-base. The same issue happens with folders with whitespaces at the begin or end. This feature ensures that a windows-user can't create the same circumstance for himself accidentally.

### CODE REVIEW

**Review by juliusknorr — COMMENTED** [review]
Makes sense :+1:

**Comment by juliushaertl** [comment]
Thanks a lot for your contribution. :rocket: 

There is only one thing missing - you need to add a sign-off message to the commits you made. Read more about this in https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work

**Review by juliusknorr — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Thanks!

**Comment by rullzer** [comment]
while @juliushaertl is correct for small changes it is ok. Just sign your next contribution :D Welcome to the club @aignerat

**Comment by MorrisJobke** [comment]
> Ah my bad I merged to soon. 15 is in RC.
> @MorrisJobke shall we revert?

Yep - let's revert this for now and then backport #13972 again.

@aignerat Sorry for the trouble here.

**Pull request merged**
