### PR TITLE
provisioning API to use only public API of IAccountManager

### PR DESCRIPTION
**Pull request by blizzz**
helps with https://github.com/nextcloud/server/issues/26866

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Integration tests are failing

**Review by nickvergessen — DISMISSED** [review]
Failing integration test is related

**Comment by blizzz** [comment]
> Failing integration test is related

yes, addressing this after the dav stuff in the other PR.

**Comment by blizzz** [comment]
So the test failed, because the AccountProperty does not accept an invalid value, but falls back to `IAccountManager::SCOPE_LOCAL` in `mapScopeToV2()` via `setScope`. The test  would work however, if the provided value was `v2-invalid` instead of `invalid`.

@PVince81 I removed the auto-fallback to v2-local, to react properly on invalid data (and satisfy integration test). Was there a specific reason why it was there in first place? Not that I am breaking something else.

**Comment by PVince81** [comment]
> So the test failed, because the AccountProperty does not accept an invalid value, but falls back to `IAccountManager::SCOPE_LOCAL` in `mapScopeToV2()` via `setScope`. The test would work however, if the provided value was `v2-invalid` instead of `invalid`.
> 
> @PVince81 I removed the auto-fallback to v2-local, to react properly on invalid data (and satisfy integration test). Was there a specific reason why it was there in first place? Not that I am breaking something else.

I don't remember whether the fallback from "invalid value" to "v2-local" was important.
I do remember that it's important to convert the legacy ones to the new ones, and I saw that you left this bit.
Should be fine.

**Pull request merged**
