### PR TITLE
Fix video verification tests

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by danxuliu — APPROVED** [review]

**Comment by szaimen** [comment]
@skjnldsv stable23 is not protected?

**Review by CarlSchwan — APPROVED** [review]

**Comment by nickvergessen** [comment]
> skjnldsv stable23 is not protected?

It was, what makes you think it would be not?

**Comment by szaimen** [comment]
> It was, what makes you think it would be not?

Looked like merging was green although only 1 person did approve. and it didn't show that 2 people are required to approve...

**Comment by nickvergessen** [comment]
Right, bumped the approval count to 2

**Pull request merged**
