### PR TITLE
Introduce a default refresh rate app setting for calendar subscriptions

### PR DESCRIPTION
**Pull request by tcitworld**
Unfortunately many people find it too low, so let's at least make it configurable.

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by ChristophWurst** [comment]
@tcitworld please rebase :)

**Comment by tcitworld** [comment]
Rebased

**Comment by georgehrke** [comment]
@tcitworld Should we backport this to 18 and 17>

**Comment by tcitworld** [comment]
I would personally like to have it, yes. And it's related to #19398 anyway.

**Comment by georgehrke** [comment]
Okay. Let's wait until the back ports of #19398 in. Then we can backport this.

**Comment by darmbrust** [comment]
Is there a reason why 1 week was selected?  I can see that might make sense for a holiday calendar or something, but for anyone that wants to sync a daily work calendar with meetings on it, this just makes it look broken...

https://github.com/nextcloud/calendar/issues/1895#issuecomment-745530386

I'd suggest once a day, or even once an hour for the default.

Ideally, we could enter our sync interval when we add the subscription in the GUI, but I imagine that would be a larger feature, since it would be per calendar and not global....

**Comment by dud1337** [comment]
Agreed; this is insane as a default that requires hunting to figure out the solution. Hunting that a non-technical user might not be successful in.

# CHANGE THE DEFAULT 2022!

I couldn't find another issue tracking this. Anyone else?

**Comment by ChristophWurst** [comment]
If you can't find an issue then please open one and refrain from commenting old pull requests. Thank you.

**Pull request merged**
