### PR TITLE
fix postgresql tests

### PR DESCRIPTION
**Pull request by blizzz**

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
I guess we need to change this in all apps as well?

**Comment by blizzz** [comment]
> I guess we need to change this in all apps as well?

Only, if they make use of postgresql docker somewhere. Thus, if they use drone and have it specified like here. For travis – if the issue happens there – the fix would go somewhere against https://github.com/nextcloud/travis_ci

**Comment by blizzz** [comment]
spectacle r21360

🎉

**Review by rullzer — APPROVED** [review]
Yep :)

**Comment by rullzer** [comment]
Please backport as well ;)

**Comment by blizzz** [comment]
Here you go: #6792 #6793

**Pull request merged**
