### PR TITLE
Avoid shared folder inside another shared folder to appear in root

### PR DESCRIPTION
**Pull request by viniciuscb**
This is our proposal to solve issue #9957, as explained in this comment:

https://github.com/nextcloud/server/issues/9957#issuecomment-399938649

### CODE REVIEW

**Comment by kxu1988** [comment]
hi @viniciuscb ,  will there be any update for this feature?

**Review by icewind1991 — CHANGES_REQUESTED** [review]
If we want to implement this then it should not be done in the view but in the share app

**Comment by MorrisJobke** [comment]
> If we want to implement this then it should not be done in the view but in the share app

Let's close this here then and try to tackle this in the sharing app.

@viniciuscb Thanks for the help hear anyways. Every contribution is helpful. 👍 

If you are looking for other tickets to tackle you could also look into https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by viniciuscb** [comment]
Hi @MorrisJobke it is a pleasure to help.

**Pull request closed without merging**
