### PR TITLE
IE fix for apps menu

### PR DESCRIPTION
**Pull request by skjnldsv**
@nextcloud/designers

### CODE REVIEW

**Review by danxuliu — COMMENTED** [review]
In general it works, but there is a minor issue:
- Resize the window (or install a lot of apps ;-) ) so the _More_ item is shown
- Click on _More_
- Click anywhere else (except on _More_ itself) to hide again the menu
- Hover on other app icon

Expected result:
The name is shown for the app

Actual result:
The name is hidden

**Comment by skjnldsv** [comment]
@danxuliu I'd rather have this then. IE experience is reduced anyway by other incompatible features. So I'd guess sooner or later we'll have different things like that :)

**Comment by danxuliu** [comment]
>   I'd rather have this then. IE experience is reduced anyway by other incompatible features. So I'd guess sooner or later we'll have different things like that :)

Sure, but in this case it is not a different behaviour, but a bug ;-) Anyway I am OK with merging it in its current state, that is why I added it as a comment instead of as a request for changes ;-)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@rullzer Mind to give a review?

**Review by rullzer — APPROVED** [review]
🐘

**Pull request merged**
