### PR TITLE
opens comments links in _blank 🙊

### PR DESCRIPTION
**Pull request by blizzz**
cf. https://github.com/nextcloud/server/pull/7680#issuecomment-355969435 ff

I'll go and do an app  that fixes this bug (imo) then later.

@jancborchardt

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by jancborchardt** [comment]
Thanks a lot for fixing this @blizzz! :) :tada:

**Comment by jancborchardt** [comment]
@blizzz as soon as you or someone you have a call with accidentally drops from it as a result of clicking a link, I suggest you take it out of the store. ;)

**Comment by blizzz** [comment]
🙊

**Comment by jancborchardt** [comment]
Btw, see this article: [When to use target=”_blank” ](https://css-tricks.com/use-target_blank/#article-header-id-7)

> A Good Reason: The user is working on something on the page, that might be lost if the current page changed.

@blizzz ;D

**Pull request merged**
