### PR TITLE
Add integration test for web based installer

### PR DESCRIPTION
**Pull request by MorrisJobke**
Detects if the index.php on a not installed instance is not "200". Detects stuff like #2209 - follow-up to #2212 

cc @rullzer @LukasReschke @schiessle

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]
LGTM if the tests pass ;)

**Comment by rullzer** [comment]
test fail :(

**Comment by MorrisJobke** [comment]
Ah - very detailed output:

bildschirmfoto 2016-11-21 um 20 47 54

... not

**Comment by MorrisJobke** [comment]
Ah - typo in the test name 🙈

**Comment by MorrisJobke** [comment]
Better to review in this mode: https://github.com/nextcloud/server/pull/2215/files?w=1

Tests pass now ;)

**Pull request merged**
