### PR TITLE
[stable25] Add brute force protection on all methods wrapped by PublicShareMiddleware

### PR DESCRIPTION
**Pull request by julien-nc**
manual backport of #35057

### CODE REVIEW

**Comment by skjnldsv** [comment]
Moving to 25.0.4 (unless merged in the upcoming hours)

**Comment by blizzz** [comment]
moving to 25.0.5

**Comment by julien-nc** [comment]
@ChristophWurst @juliushaertl @blizzz :ping_pong:

**Review by blizzz — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
