### PR TITLE
Add config.php option for transfer ownership

### PR DESCRIPTION
**Pull request by PVince81**
For https://github.com/nextcloud/server/pull/28118

Add option to specify whether to transfer incoming shares by default.

### CODE REVIEW

**Comment by acsfer** [comment]
Even if it's obvious, maybe inserting something like:

"Defaults to false, so incoming shares are not transfered if not specifically requested"

**Review by ipasanec — COMMENTED** [review]
_Maybe_ a note like 'Can be overwritten by command line argument.' might be helpful. (just a thought)

**Comment by PVince81** [comment]
@acsfer @ipasanec adjusted, please recheck

**Review by solracsf — APPROVED** [review]

**Review by ipasanec — APPROVED** [review]

**Comment by PVince81** [comment]
doc is here: https://github.com/nextcloud/documentation/pull/7134

removing label

**Pull request merged**
