### PR TITLE
Add "Password protected by Talk" option to shares

### PR DESCRIPTION
**Pull request by danxuliu**
I just used the wording from Nextcloud 17, but as the translations were moved from `core` to `files_sharing` they need to be redone (or copied over). So this might be a good time to improve the wording of the option if someone is inspired ;-)

@skjnldsv _SharingEntryLink_ is applied to link shares and mail shares only, right? Or are there any other shares shown using that component? In that case a check should be added to `isPasswordProtectedByTalkAvailable` to enable it only for link and mail shares.

## How to test
- Open the Files app
- Open the _Sharing_ tab for a file
- Create a link share
- Set a password

### Result with this pull request
_Password protected by Talk_ checkbox is shown when a password is set, and hidden if the password is removed. Reloading the page and showing again the share menu shows the value last set.

### Result without this pull request
No _Password protected by Talk_ checkbox is shown.

### CODE REVIEW

**Comment by danxuliu** [comment]
Renamed to _Video verification_ as requested by @jospoortvliet

**Comment by skjnldsv** [comment]
> @skjnldsv _SharingEntryLink_ is applied to link shares and mail shares only, right? Or are there any other shares shown using that component? In that case a check should be added to `isPasswordProtectedByTalkAvailable` to enable it only for link and mail shares.

Only link and mail yes (mail are link) :)

**Review by nickvergessen — APPROVED** [review]

**Review by Ivansss — APPROVED** [review]
Tested and works 👍

**Comment by nickvergessen** [comment]
@danxuliu please rebase

**Pull request merged**
