### PR TITLE
Do not trigger appconfig queries when we are not yet installed

### LINKED ISSUE #2209: can't install fresh nextcloud
I can't setup a fresh Nextcloud on master (ba9b17c9069c5d9fe8595ffd306647f33067c927)

If I load the page I get:

````
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
````

The nextcloud log shows:

````
{"reqId":"d32NJOFRivtzAOS0EjcP","remoteAddr":"::1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM \\\"oc_appconfig\\\"':\\n\\nSQLSTATE[HY000]: General error: 1 no such table: oc_appconfig\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM \\\"...', Array)\\n#2 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/DB\\\/Connection.php(194): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array, NULL)\\n#3 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array)\\n#4 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(177): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(275): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(78): OC\\\\AppConfig->loadConfigValues()\\n#7 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(254): OC\\\\AppConfig->getApps()\\n#8 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/App\\\/AppManager.php(105): OC\\\\AppConfig->getValues(false, 'enabled')\\n#9 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/App\\\/AppManager.php(157): OC\\\\App\\\\AppManager->getInstalledAppsValues()\\n#10 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/app.php(341): OC\\\\App\\\\AppManager->isEnabledForUser('theming')\\n#11 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/public\\\/App.php(132): OC_App::isEnabled('theming')\\n#12 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/URLGenerator.php(161): OCP\\\\App::isEnabled('theming')\\n#13 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template\\\/functions.php(170): OC\\\\URLGenerator->imagePath('', 'actions\\\/caret.s...')\\n#14 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/core\\\/templates\\\/installation.php(60): image_path('', 'actions\\\/caret.s...')\\n#15 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(174): include('\\\/home\\\/schiesbn\\\/...')\\n#16 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(149): OC\\\\Template\\\\Base->load('\\\/home\\\/schiesbn\\\/...', NULL)\\n#17 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template.php(228): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#18 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(130): OC_Template->fetchPage()\\n#19 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template.php(312): OC\\\\Template\\\\Base->printPage()\\n#20 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/core\\\/Controller\\\/SetupController.php(96): OC_Template::printGuestPage('', 'installation', Array)\\n#21 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/core\\\/Controller\\\/SetupController.php(76): OC\\\\Core\\\\Controller\\\\SetupController->display(Array)\\n#22 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/base.php(952): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#23 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/index.php(40): OC::handleRequest()\\n#24 {main}\",\"File\":\"\\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":58}","level":3,"time":"2016-11-21T09:29:48+00:00","method":"GET","url":"\/master\/","user":"--","version":""}
{"reqId":"d32NJOFRivtzAOS0EjcP","remoteAddr":"::1","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM \\\"oc_appconfig\\\"':\\n\\nSQLSTATE[HY000]: General error: 1 no such table: oc_appconfig\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM \\\"...', Array)\\n#2 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/DB\\\/Connection.php(194): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array, NULL)\\n#3 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array)\\n#4 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(177): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(275): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(78): OC\\\\AppConfig->loadConfigValues()\\n#7 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(254): OC\\\\AppConfig->getApps()\\n#8 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/App\\\/AppManager.php(105): OC\\\\AppConfig->getValues(false, 'enabled')\\n#9 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/App\\\/AppManager.php(157): OC\\\\App\\\\AppManager->getInstalledAppsValues()\\n#10 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/app.php(341): OC\\\\App\\\\AppManager->isEnabledForUser('theming')\\n#11 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/public\\\/App.php(132): OC_App::isEnabled('theming')\\n#12 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/URLGenerator.php(161): OCP\\\\App::isEnabled('theming')\\n#13 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template\\\/functions.php(170): OC\\\\URLGenerator->imagePath('', 'actions\\\/caret.s...')\\n#14 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/core\\\/templates\\\/installation.php(60): image_path('', 'actions\\\/caret.s...')\\n#15 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(174): include('\\\/home\\\/schiesbn\\\/...')\\n#16 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(149): OC\\\\Template\\\\Base->load('\\\/home\\\/schiesbn\\\/...', NULL)\\n#17 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template.php(228): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#18 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(130): OC_Template->fetchPage()\\n#19 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template.php(312): OC\\\\Template\\\\Base->printPage()\\n#20 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/core\\\/Controller\\\/SetupController.php(96): OC_Template::printGuestPage('', 'installation', Array)\\n#21 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/core\\\/Controller\\\/SetupController.php(76): OC\\\\Core\\\\Controller\\\\SetupController->display(Array)\\n#22 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/base.php(952): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#23 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/index.php(40): OC::handleRequest()\\n#24 {main}\",\"File\":\"\\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":58}","level":3,"time":"2016-11-21T09:29:48+00:00","method":"GET","url":"\/master\/","user":"--","version":""}
{"reqId":"d32NJOFRivtzAOS0EjcP","remoteAddr":"::1","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM \\\"oc_appconfig\\\"':\\n\\nSQLSTATE[HY000]: General error: 1 no such table: oc_appconfig\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM \\\"...', Array)\\n#2 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/DB\\\/Connection.php(194): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array, NULL)\\n#3 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array)\\n#4 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(177): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(275): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(78): OC\\\\AppConfig->loadConfigValues()\\n#7 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/AppConfig.php(254): OC\\\\AppConfig->getApps()\\n#8 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/App\\\/AppManager.php(105): OC\\\\AppConfig->getValues(false, 'enabled')\\n#9 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/App\\\/AppManager.php(157): OC\\\\App\\\\AppManager->getInstalledAppsValues()\\n#10 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/app.php(341): OC\\\\App\\\\AppManager->isEnabledForUser('theming')\\n#11 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/public\\\/App.php(132): OC_App::isEnabled('theming')\\n#12 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/URLGenerator.php(161): OCP\\\\App::isEnabled('theming')\\n#13 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template\\\/functions.php(170): OC\\\\URLGenerator->imagePath('', 'favicon.ico')\\n#14 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/core\\\/templates\\\/layout.guest.php(13): image_path('', 'favicon.ico')\\n#15 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(174): include('\\\/home\\\/schiesbn\\\/...')\\n#16 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(149): OC\\\\Template\\\\Base->load('\\\/home\\\/schiesbn\\\/...', NULL)\\n#17 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template.php(228): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#18 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template.php(250): OC_Template->fetchPage()\\n#19 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/Template\\\/Base.php(130): OC_Template->fetchPage()\\n#20 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/lib\\\/private\\\/legacy\\\/template.php(363): OC\\\\Template\\\\Base->printPage()\\n#21 \\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/index.php(59): OC_Template::printExceptionErrorPage(Object(Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException))\\n#22 {main}\",\"File\":\"\\\/home\\\/schiesbn\\\/repos\\\/nextcloud\\\/server\\\/master\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":58}","level":3,"time":"2016-11-21T09:29:48+00:00","method":"GET","url":"\/master\/","user":"--","version":""}
````

Any idea? I'm the only one with this problem?

cc @LukasReschke @nickvergessen @icewind1991 

@karlitschek need to be solved before we can create the beta

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #2209

CC: @schiessle @LukasReschke @nickvergessen @MorrisJobke 

steps:

1. try to install via web

before: BOOM
now: NO BOOM

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
I will add an integration test for this

**Comment by MorrisJobke** [comment]
> I will add an integration test for this

See #2215

**Pull request merged**
