### PR TITLE
Add app icons for Comments and Tags

### PR DESCRIPTION
**Pull request by jancborchardt**
Makes it look way nicer in the Apps management. Please review @nextcloud/designers @schiessle @blizzz @Bugsbane 

Before & after:
capture du 2016-07-26 18-31-10 capture du 2016-07-26 18-30-51

### CODE REVIEW

**Comment by ChristophWurst** [comment]
:+1: nice, oida!

**Comment by mar1u5** [comment]
:+1:

**Comment by mar1u5** [comment]
Backport? @karlitschek

**Comment by karlitschek** [comment]
please backport

**Pull request merged**
