### PR TITLE
Menu elements not displayed as block

### LINKED ISSUE #34653: [Bug]: File actions menu links don't span over whole menu width
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In `fileActionsMenu`, the action item links don't span over the whole menu width, which leads to a poor user experience:

screenshot

### Steps to reproduce

1. Open three-dot actions menu of a file in the files list
2. Hover over the white space after an item

### Expected behavior

The links should span over the whole menu width, so it's possible to click behind the text of an action (e.g. "Details").

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
files
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #35153: [Bug]: Context menu too narrow for text when triggered from grid view
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I trigger the context menu in the File app using the three dots, some menu items of the context menu overflow the border:

Bildschirm­foto 2022-11-14 um 15 17 42

This only happens when grid view is active.

### Steps to reproduce

1. Open files app
2. Switch to grid view
3. Click the 3 dots on a random item to open the context menu

### Expected behavior

When I right-click on the same item instead of left clicking on the three dots, the context menu looks fine:

Bildschirm­foto 2022-11-14 um 15 21 04

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.host.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.1.1",
        "overwrite.cli.url": "https:\/\/my.host.tld",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "trashbin_retention_obligation": "auto, 30"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - bookmarks: 11.0.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - music: 1.7.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.1
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.17.0
  - admin_audit
  - bruteforcesettings
  - dashboard: 7.5.0
  - encryption
  - firstrunwizard: 2.14.0
  - photos: 2.0.0
  - suspicious_login
  - twofactor_gateway: 0.20.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

Language set to German (informal) in personal settings.

### PR DESCRIPTION
**Pull request by Dennis1993**
Close https://github.com/nextcloud/server/issues/34653
Close https://github.com/nextcloud/server/issues/35153

Fix for https://github.com/nextcloud/server/issues/34870 to set the width to 100% for all elements.

### CODE REVIEW

**Comment by Pytal** [comment]
From my testing this would reintroduce https://github.com/nextcloud/server/issues/33857

So I suggest we restore the deleted snippet and scope it like
```scss
...
	.popovermenu {
		&:not(.fileActionsMenu) {
			li {
				> button,
				> a,
				> .menuitem {
					width: fit-content;
					/* DEPRECATED! old img in popover fallback
					* TODO: to remove */
					> img {
						width: $popoveritem-height;
						height: $popoveritem-height;
					}
				}
			}
		}
	}
...
```

The DEPRECATED part introduced in https://github.com/nextcloud/server/pull/11054 doesn't seem to apply anymore, at least in the files sharing sidebar, but would need @danxuliu to confirm

**Comment by szaimen** [comment]
@nextcloud/server-frontend how to continue with this?

**Comment by szaimen** [comment]
I'd vote for Chris' proposal. 

@Pytal can you take this over? :)

**Comment by PVince81** [comment]
@skjnldsv please take over

**Comment by szaimen** [comment]
> Ping @skjnldsv ? :)

I could also do this if we agree that @Pytal's suggestion is the way to go :)

**Comment by szaimen** [comment]
hm... I just tried the latest 25 with

```
docker run -it \
--name nextcloud-easy-test \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.24.128 \
-e SERVER_BRANCH=stable25 \
-e RIGHTCLICK_BRANCH=stable25 \
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

And I somehow cannot reproduce the problem. It seems to work...

But really no idea what has fixed it...

**Pull request closed without merging**
