### PR TITLE
Remove old code to be compatible with Nextcloud 9 and before

### PR DESCRIPTION
**Pull request by MorrisJobke**
Even 10 is already EoL

cc @nextcloud/sharing @nickvergessen @blizzz 

Ref #8375

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Fine by me :fire:

**Comment by rullzer** [comment]
Ah well. In principal I'm fine. But this does mean that you might not be able to mount shares of other people. You can't control their instance.

@schiessle what is your take on this.

**Comment by MorrisJobke** [comment]
> Ah well. In principal I'm fine. But this does mean that you might not be able to mount shares of other people. You can't control their instance.

Sure, but at some point we need to drop support for old instances. And let's hope that there are no instances with 9 out there that want to federate with 14 ...

**Comment by MorrisJobke** [comment]
> Sure, but at some point we need to drop support for old instances. And let's hope that there are no instances with 9 out there that want to federate with 14 ...

In other words: the code on those instances might have security issues, that we only fixed in 10+ because of the EoL state.

**Review by rullzer — APPROVED** [review]

**Review by MariusBluem — APPROVED** [review]

**Pull request merged**
