### PR TITLE
Theming: Show loading spinner while uploading files

### PR DESCRIPTION
**Pull request by juliusknorr**
show spinner on button during upload 

as proposed in https://github.com/nextcloud/server/issues/735

2016-08-30-062322_413x275_scrot

please review @nextcloud/theming

### CODE REVIEW

**Comment by LukasReschke** [comment]
Nice 👍 

cc @ChristophWurst since you also complained about that :)

**Comment by nickvergessen** [comment]
:+1:

**Comment by juliushaertl** [comment]
@karlitschek Shall we backport this, as it was requested in #735?

**Comment by karlitschek** [comment]
i think that a nice fix. please backport 👍

**Pull request merged**
