### PR TITLE
#33036 [Bug]: Set default expiration date

### PR DESCRIPTION
**Pull request by Xavierando**
two input with same id and content
probably a never done clean up after a duplication of the line of code for beautify

#33036

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by Pytal — APPROVED** [review]

**Comment by PVince81** [comment]
@Xavierando nice catch! thanks a lot

**Comment by come-nc** [comment]
This is from here: https://github.com/nextcloud/server/pull/31194#pullrequestreview-1093673925

Thank you for testing and fixing this!

**Comment by szaimen** [comment]
Backport to 24?

**Pull request merged**
