### PR TITLE
Load apps before running repair steps

### LINKED ISSUE #15042: Repair in maintenance mode
### Steps to reproduce
1. Start maintenance:repair in maintenance mode on

### Expected behaviour
The process completes without an error

### Actual behaviour
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\FixBirthdayCalendarComponent' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\CalDAVRemoveEmptyValue' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\BuildCalendarSearchIndex' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\RefreshWebcalJobRegistrar' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\RemoveClassifiedEventActivity' is unknown

Seems we need backport https://github.com/owncloud/core/pull/25650/files
With this fix the error is gone

### PR DESCRIPTION
**Pull request by Temtaime**
Fixes #15042

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Could you fix the DCO?

**Review by ChristophWurst — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
> Could you fix the DCO?

Well, it's a small change and coming from oc, i'll make it pass manually

**Pull request merged**
