### PR TITLE
apply theme to the firstrunwizard

### PR DESCRIPTION
**Pull request by schiessle**
apply theme to first run wizard, needed for https://github.com/nextcloud/firstrunwizard/pull/5

cc @jancborchardt  @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Unit tests failing now :)

**Comment by schiessle** [comment]
@LukasReschke will take care of the unit tests

**Comment by LukasReschke** [comment]
Works nicely 👍

**Comment by jancborchardt** [comment]
This works nicely! :+1:

**Comment by jancborchardt** [comment]
This works nicely! :+1:  Thanks @schiessle

**Comment by schiessle** [comment]
stable10: https://github.com/nextcloud/server/pull/639

**Pull request merged**
