### PR TITLE
Unify look of the strengthify password hint

### LINKED ISSUE #7719: Inconsistent appearance of the password strength bar
The password strength bar during the installation appears [centered on the password input](https://github.com/nextcloud/server/blob/21fbcba68d3ce49bf31960276c0cbfe0f158dda4/core/css/guest.css#L292-L298) (although it is 1px off to the right, as the bar width is 250px with a margin of 15px and the password input width is 249px with a padding of 10px and a margin of 5px ;-) ), but in the user settings it appears [aligned to the left and covers only half of the password input](https://github.com/nextcloud/server/blob/a79d276324f1c5e44aec9a54c909ca47b31fb532/settings/css/settings.scss#L1119-L1124).

Installation:
strengthify-installation

User settings:
strengthify-settings

The password strength bar [is also used in the LDAP app](https://github.com/nextcloud/server/blob/1d8e73b10843d60789010008902017530f8b2121/apps/user_ldap/css/renewPassword.css#L6-L11), but I have not checked its appearance.

@nextcloud/designers

### PR DESCRIPTION
**Pull request by skjnldsv**
Fixes #7719

capture d ecran_2018-03-01_16-56-47capture d ecran_2018-03-01_17-03-02

Same design as our quota in users management
capture d ecran_2018-03-01_17-11-25

@nextcloud/designers

### CODE REVIEW

**Review by danxuliu — CHANGES_REQUESTED** [review]
In the settings the strength bar does not line up with the borders of its field (although it does in the installation); `margin-left: 1px;` should be removed, and `width: calc(100% - 2px);` should be replaced with `width: 100%`. See:

Current:
strengthify-settings-current

Fixed:
strengthify-settings-fixed

**Comment by skjnldsv** [comment]
@danxuliu it was supposed to be inside the borders, like the quota (under as a matter of fact) But then the margin would not have been good.
I prefer your option :)

**Review by danxuliu — APPROVED** [review]
Tested (:warning: although not in the LDAP app :warning:) and works :+1:

**Comment by skjnldsv** [comment]
Where does the ldap uses this?

**Comment by danxuliu** [comment]
@skjnldsv 
> Where does the ldap uses this?

Apparently (I have never checked it in the running app) here: https://github.com/nextcloud/server/blob/b83204bf2cac18ed2fa1f07770a172932392abcc/apps/user_ldap/js/renewPassword.js#L39

**Review by MorrisJobke — APPROVED** [review]

**Comment by juliushaertl** [comment]
> Where does the ldap uses this?

Maybe @blizzz knows a way to test if it works for the ldap password renewal ?

**Review by juliusknorr — APPROVED** [review]

**Comment by blizzz** [comment]
> Maybe @blizzz knows a way to test if it works for the ldap password renewal ?

1. comment out the Redirect Response in RenewPasswordController::88
2. go to http://nextcloud.server/index.php/apps/user_ldap/renewpassword/$user ($user being a valid username)

I don't see many differences. 

Before the merge:

screenshot_20180302_153425

After:

screenshot_20180302_153600

**Comment by skjnldsv** [comment]
May I suggest a cache clear? :)

**Comment by blizzz** [comment]
you may, but that does not change anything

**Comment by skjnldsv** [comment]
@blizzz Firefox?
Also, tried with another browser?

**Comment by blizzz** [comment]
yes, yes

**Pull request merged**
