### PR TITLE
[us] Disable NFD encoding wrapper by default

### PR DESCRIPTION
**Pull request by icewind1991**
see https://github.com/owncloud/core/pull/25818

needs stable10 backport ( @karlitschek )

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport

**Comment by schiessle** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by icewind1991** [comment]
stable10: https://github.com/nextcloud/server/pull/907

**Pull request merged**
