### PR TITLE
Fix header menu & contact popover

### PR DESCRIPTION
**Pull request by skjnldsv**
@nickvergessen can you edit this to your notification app?

```
.notification .avatar-name-wrapper .avatar {
	margin: 0 5px 3px;
}
```

capture d ecran_2018-08-09_12-43-51

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@skjnldsv please don't :apple: @rullzer :speak_no_evil:

**Comment by nickvergessen** [comment]
Should the popover start below the avatar, or in the middle?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notifications/pull/154

**Comment by rullzer** [comment]
jsunit is not happy

**Review by rullzer — APPROVED** [review]
Fine by me. But maybe starting below the avatar is better. Yet still nice to get this in :D

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
