### PR TITLE
Unlock files even if an exception occurs (stable12)

### PR DESCRIPTION
**Pull request by korelstar**
Backport of #7014 for stable12.

### CODE REVIEW

**Comment by korelstar** [comment]
Can we put this into 12.0.4?

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Let's wait for this merge until 12.0.4 is out

**Review by LukasReschke — DISMISSED** [review]
Blocking with "Request changes" so it doesn't accidentally get merged :)

**Pull request merged**
