### PR TITLE
fix(files): properly update paths and folder children on node move

### LINKED ISSUE #48322: [Bug]: Delete file does not refresh the files view if previously renamed
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a file is deleted, there is a confirmation message, but file remains in the view, altough it is deleted.

### Steps to reproduce

1. Upload a file
2. Rename it
3. Delete it

### Expected behavior

File is gone from the list when moved to the trash bin.

Tested on v28.0.11 and 29.0.8

explorer_c7rxBK7UHm

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/48322

### CODE REVIEW

**Comment by solracsf** [comment]
Does it possibly fix any of these too?
https://github.com/nextcloud/server/issues/48322#issuecomment-2444649984

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
@solracsf no, they are a bit different :)

**Comment by skjnldsv** [comment]
Viewer delete fix: https://github.com/nextcloud/viewer/pull/2620

**Review by artonge — APPROVED** [review]

**Pull request merged**
