### PR TITLE
Allow to create directories when they are selectable

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Seems the create option is broken since some time:
```
11:36:19.215 TypeError: u.$form is undefined
2 dialogs.js:321:5
    filepicker dialogs.js:321
    jQuery 3
11:36:21.043
Deprecated call $.tooltip('fixTitle') has been deprecated and should be removed tooltip.js:32:12
    tooltip tooltip.js:32
    filepicker dialogs.js:360
    filepicker dialogs.js:371
    jQuery 9
    filepicker dialogs.js:336
    jQuery 2
```

**Comment by nickvergessen** [comment]
Next error:
`ReferenceError: Files is not defined`

The files app is not loaded in talk, so
https://github.com/nextcloud/server/blob/c340e42abc5102e149b41e1682c3053323ac34f7/core/src/OC/dialogs.js#L342
provided by
https://github.com/nextcloud/server/blob/b9bc2417e7a8dc81feb0abe20359bedaf864f790/apps/files/js/files.js#L514

is not available :(

**Comment by nickvergessen** [comment]
- [ ] Files.* is not loaded outside the files app
- [ ] Files. depends on nextcloud global: `OC.config.blacklist_files_regex` and uses translations from the files app, so its harder to move it to https://github.com/nextcloud/nextcloud-files
- [ ] Next up it depends on the files table: https://github.com/nextcloud/server/blob/c340e42abc5102e149b41e1682c3053323ac34f7/core/src/OC/dialogs.js#L344 (could check for null first, because the API endpoint will throw an error on duplicates anyway)

**Review by ChristophWurst — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]
Tested and works!

**Comment by nickvergessen** [comment]
> Conflicting files
core/js/dist/login.js.map
core/js/dist/main.js.map
core/js/dist/maintenance.js
core/js/dist/maintenance.js.map

rebased

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
