### PR TITLE
#6307 fix page title not changed

### LINKED ISSUE #6307: [files app] a minor cosmetic "naming"-bug
### Steps to reproduce
1. open the files-app in the web-interface at nextcloud 12 (nextcloud 11 is NOT affected!)
2. choose an other group (like shared, favorites, etc. or even deleted) and the title of the site/tab gets accordingly renamed.
3. now choose "all files" within the side-menu of the app, not the general app-button and the site-/tab-name stays the same as before.

### Expected behaviour
the site/tab should be renamed "files" like it is when you access the files-app.

### Actual behaviour
see _Steps to reproduce 3._

### Server configuration

**Operating system**: Linux 3.13.0-128-generic Ubuntu (i guess my hoster told me some time ago it is Ubuntu 14.04)

**Web server:** Apache

**Database:** mysql 5.6.33

**PHP version:** 7.0.20

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated just from 12.0.1

**Where did you install Nextcloud from:** hoster-script

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
<details>
<summary>App list</summary>

```
activity
bruteforcesettings
calendar
comments
contacts
dav
federatedfilesharing
federation
files
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoplayer
firstrunwizard
gallery
logreader
lookup_server_connector
nextcloud_announcements
notifications
oauth2
password_policy
provisioning_api
serverinfo
sharebymail
twofactor_backupcodes
updatenotification
user_external
workflowengine

apporder
checksum
files_downloadactivity
files_opds
files_reader
keeweb
metadata
notes
qownnotesapi
quota_warning
socialsharing_email
spreed
tasks
telephoneprovider

**INACTIVE:**
admin_audit
systemtags
encryption
files_external
user_ldap
theming
survey_client

ransomware_protection
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'cloud.mydomain.tld',
  ),
  'datadirectory' => '/www/htdocs/server/nextcloud/data',
  'overwrite.cli.url' => 'http://cloud.mydomain.tld',
  'dbtype' => 'mysql',
  'version' => '12.0.2.0',
  'dbname' => 'dbname',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'xxxxx_',
  'mysql.utf8mb4' => false,
  'dbuser' => 'dbuser',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'default_language' => 'de',
  'allow_user_to_change_display_name' => false,
  'skeletondirectory' => '',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{mail.mydomain.tld:993/imap/ssl/novalidate-cert/readonly}INBOX',
        1 => 'mydomain.tld',
      ),
    ),
  ),
  'updater.release.channel' => 'production',
  'loglevel' => 2,
  'customclient_desktop' => 'https://nextcloud.com/install/#install-clients',
  'customclient_android' => 'https://f-droid.org/packages/com.nextcloud.client',
  'customclient_ios' => 'https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/www/htdocs/server/nextcloud/apps_neu',
      'url' => '/apps_neu',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/www/htdocs/server/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
  'theme' => '',
  'filesystem_check_changes' => 1,
  'tempdirectory' => '/www/htdocs/server/nextcloud/tmp/',
  'maintenance' => false,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Epub',
    5 => 'OC\\Preview\\FB2',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\OpenDocument',
    8 => 'OC\\Preview\\StarOffice',
    9 => 'OC\\Preview\\MSOfficeDoc',
    10 => 'OC\\Preview\\MSOffice2003',
    11 => 'OC\\Preview\\MSOffice2007',
  ),
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** Firefox

**Operating system:** Linux Mint 17 (based on Ubuntu 14.04)

### PR DESCRIPTION
**Pull request by burned42**
Fixes (on master) #6307 
With this changes the page title gets set when switching to file list and tag list.

### CODE REVIEW

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Thanks a lot for your Pull Request! :rocket:

Unfortunately, this seems to make the JSUnit tests fail as per https://drone.nextcloud.com/nextcloud/server/2180/241. Would you mind looking into this?

Also cc @danxuliu as he may be able to help here :)

**Comment by burned42** [comment]
@LukasReschke Sorry, I did only read about PHPUnit tests in the `CONTRIBUTING.md`. I will check the errors and see if I can fix them.

**Comment by burned42** [comment]
@LukasReschke It seems like there are still some failing tests but I'm not sure if my commits are the cause. The JSUnit test is not failing anymore.

**Review by LukasReschke — APPROVED** [review]
The failing tests are indeed unrelated. Thanks a lot for your pull request!

@icewind1991  @danxuliu Opinions here? :)

**Comment by danxuliu** [comment]
Thanks for your contribution, @burned42 :-D

These changes make the base file list and the system tags file list follow the same approach used with the file lists for favorites, recents and so on, and consistency is good ;-)

The only problem is that calling `_setCurrentDir` in `reload` is redundant in some cases in which `_setCurrentDir` is called just before `reload` (for example, in [`changeDirectory`](https://github.com/nextcloud/server/blob/f392e78d5b525abbb04057b91c0adfba212c00c4/apps/files/js/filelist.js#L1530-L1534)), and probably the other file lists should have not been calling `_setCurrentDir` in `reload` in the first place; the code of the file lists needs some review and clean up anyway, so I am OK with merging this now and taking care of those things later ;-)

Note, however, that #6307 is not fixed by this pull request, because that issue is filled against Nextcloud 12, and these changes will be merged into master and thus Nextcloud 13. @burned42, once these changes are merged, could you backport this to the _stable12_ branch too? :-)

**Comment by burned42** [comment]
@danxuliu Since I am unfamiliar with the codebase I checked the other modules/files and tried to make it consistent above these.

Sure, I could try to backport these changes. Is there a best practice on how to do that? Should I just checkout stable12 and try to apply the same changes?

**Comment by danxuliu** [comment]
@burned42
>  Since I am unfamiliar with the codebase I checked the other modules/files and tried to make it consistent above these. I noticed the redundant call but didn't want to start big refactoring since, as I said, I am not really familiar with the codebase.

Of course! Please do not see my comment as a critic to your changes; it was just a comment about the general state of the `FileList` code :-)

>  Sure, I could try to backport these changes. Is there a best practice on how to do that? Should I just checkout stable12 and try to apply the same changes?

Yes, basically that is it.

What I usually do is, on the branch that I want to backport, create a new branch with `git checkout -b stable12-{original-PR-number}-{original-PR-branch-name}` (but that is just how I name it; others use different name schemes) and then rebase the new branch onto _stable12_ using `git rebase --onto stable12 {commit-id-where-the-branch-to-be-backported-diverged-from-master} stable12-{original-PR-number}-{original-PR-branch-name}`.

And then, of course, test to ensure that everything works as expected ;-)

By the way, before backporting, may I ask you to fold the third and fourth commit into the first one (for example, with `git rebase -i HEAD~4`, replacing `pick` with `fixup` in the third and fourth commits, and then moving the second commit to the end) to get a cleaner commit history? Sorry, I am a professional nitpicker :-P

Thank you! :-)

**Comment by burned42** [comment]
@danxuliu just to clarify, 'branch that I want to backport' would be my current branch `6307-fix_page_title_not_changed`, correct?

Regarding your other request, by 'before backporting' do you mean I should do the rebase now or after this pull request is merged?

**Comment by danxuliu** [comment]
@burned42 
>  to clarify, 'branch that I want to backport' would be my current branch 6307-fix_page_title_not_changed, correct?

Correct.

>  Regarding your other request, by 'before backporting' do you mean I should do the rebase now or after this pull request is merged?

If possible please do it before this pull request is merged so we have a cleaner commit history also in _master_ :-) You will have to force push the _6307-fix_page_title_not_changed_ branch to discard the previous commits already on the GitHub server.

**Comment by burned42** [comment]
@danxuliu  Rebased as suggested and force pushed the changes.

**Review by danxuliu — APPROVED** [review]
Great! Thank you very much! :-)

**Comment by burned42** [comment]
@danxuliu Thank you for your help, also @LukasReschke. I already followed your other request and after testing the changes with _stable12_ I will create a pull request for that, too.

**Pull request merged**
