### PR TITLE
chore: Update PSR container to 2.0.2

### PR DESCRIPTION
**Pull request by susnux**
- [ ] This is the server PR for the update of the `3rdparty` repo: nextcloud/3rdparty#1311

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
We'll need to wait for the 26 branch-off, though

https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule/de2553401ea6869015cf1f6f12f3758b4be7ca89#nextcloud-26

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud-deps/ocp/blob/5c5b6d8600ddaf9f466736e34103b2921cc9b0e3/composer.json#L15 needs an update too to keep app static analysis in sync with what's hipped in server

**Comment by ChristophWurst** [comment]
Like with https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/psr.html#psr-3-logger-interface we should probably mention the upgrade in the dev docs

**Comment by susnux** [comment]
> We should probably mention the upgrade in the dev docs

Pending documentation: nextcloud/documentation#9906

> Needs an update too to keep app static analysis in sync with what's hipped in server

Pending PR: nextcloud-deps/ocp#6

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
But the question from Joas is still pending, this would mean master will require PHP 8.0.2 which is more restricting than current 8.0

**Comment by susnux** [comment]
@szaimen done

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by susnux** [comment]
Should not the 3rdparty PR get merged first so that the submodule can be updated?

**Comment by szaimen** [comment]
Fuck you are right!

**Comment by szaimen** [comment]
Can you create a follow-up PR for server?

**Comment by szaimen** [comment]
3rdparty was merged. @susnux can you please do the follow-up?

**Comment by susnux** [comment]
@szaimen sure

**Comment by susnux** [comment]
Done in #37794

**Comment by DaphneMuller** [comment]
Hello!
Thank you for your work on this! I noticed that your PR still has the label 'documentation'. I'm not sure if you already had a look at the documentation for your PR, but at Nextcloud we strive to document changes that affect other app developers or other admins before the release takes place, and I'm pinging you with the hope to get this done. 

Are you familiar with our documentation process already? 
Changes that affect app developers should be documented here:
https://docs.nextcloud.com/server/27/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_27.html

Changes that affect administrators should be documented here:
https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html

While I understand sometimes it's handy to merge fast to get your changes in, it would be great if next time you could try to add the documentation before merging. You can find more information on that here:
https://docs.nextcloud.com/server/27/developer_manual/prologue/compatibility_app_ecosystem.html#documentation-procedures-of-changes-that-affect-app-developers

If all your documentation efforts are done, please remove the label 'documentation' and check the checkbox in your opening note and I'll stop bugging you :) 

Many thanks in advance and thanks again for your work!

**Pull request merged**
