### PR TITLE
restricted the height of the settings area in core/css/apps.css

### PR DESCRIPTION
**Pull request by pgys**
to max 80%

### CODE REVIEW

**Comment by rullzer** [comment]
@pgys thanks for your PR!

@nextcloud/designers please have a look!

**Comment by schiessle** [comment]
Thanks for your contribution! Would be nice to have a short description what it fixes/improves. Maybe with screenshot from before and after your changes.

**Comment by pgys** [comment]
@rullzer @schiessle thanks for your feedback! 
The request refers to nextcloud/contacts#14

**Comment by juliushaertl** [comment]
@pgys Awesome, thanks for the contribution. Changes look good :+1:

To get this in, you need to sign your commit. Running `git commit --amend --signoff` and force push to the branch should work fine here. 
See https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work for more details.

**Comment by rullzer** [comment]
LGTM

**Comment by jancborchardt** [comment]
Awesome work @pgys, welcome to the Nextcloud community! :)

**Comment by skjnldsv** [comment]
Welcome!

**Pull request merged**
