### PR TITLE
Shortcut Ctrl+F for different keyboard layouts

### PR DESCRIPTION
**Pull request by AIlkiv**
## Summary

For example, on the Ukrainian keyboard layout, when you press the 'f' button, event.key is equal to "а", and event.code is equal to "KeyF".
Documentation: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

If you activate the Caps Lock and then press CTRL+f on an English keyboard layout, event.key becomes "F" instead of 'f', causing the search window not to open.

This pull request solves both of these problems.

image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by susnux** [comment]
> For example, on the Ukrainian keyboard layout, when you press the 'f' button, event.key is equal to "а", and event.code is equal to "KeyF".

Should it not be the opposite? `event.key` should always be the letter that is "printed" and `event.code` should be the physical code. Meaning if you press `f` you get `event.key = f` but `event.code` depends on your keyboard layout.
E.g. if I press `z` I get `event.key = z` but `event.code = keyY` because of QWERTZ vs QWERTY.

So my problem is: If for Ukrainian keyboards search shortcut is "ctrl + a" (and a is on the place were on qwerty is the f) then this will work, but I am not sure this is valid for all languages.

**Review by susnux — APPROVED** [review]
Generally ok with this, but see my comment.

**Comment by AIlkiv** [comment]
> Should it not be the opposite? `event.key` should always be the letter that is "printed" and `event.code` should be the physical code. Meaning if you press `f` you get `event.key = f` but `event.code` depends on your keyboard layout.
> E.g. if I press `z` I get `event.key = z` but `event.code = keyY` because of QWERTZ vs QWERTY.

@susnux Thanks for the answer. Many languages lack the letter "F," but there is an overlay of QWERTY + the native language. We use the physical placement of keys (tested: Chrome, LibreOffice, Office365).

Here are examples of several keyboard layouts:

Keyboards with Ukrainian layout

image

Keyboards with Greek layout

image

I've corrected the use of keyCode; it is more accurate for different layouts. It works correctly even on the Dvorak keyboard layout.

**Comment by susnux** [comment]
Thank you for the explanation! Makes sense now.
But please revert to use `.code` as `.keyCode` is deprecated

**Comment by AIlkiv** [comment]
> Thank you for the explanation! Makes sense now. But please revert to use `.code` as `.keyCode` is deprecated

Reverted

**Review by Pytal — APPROVED** [review]

**Pull request merged**
