### PR TITLE
Show modified in filepicker grid

### PR DESCRIPTION
**Pull request by Pytal**
- For https://github.com/nextcloud/server/issues/36943

## Summary

Before | After
--- | ---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Jerome-Herbinet — COMMENTED** [review]
Technically, for me, it's OK. I tested on a Nextcloud 26 instance which has the same problem as Nextcloud 27 for which this Pull Request is initially intended. Before I give my approval, I wonder why this is done here, but not also in the grid view of all Nextcloud Files (which in this case will require a different code change presumably). In my opinion, there should be consistency between this copy/move popup and Nextcloud Files at large (unless this is already planned in the Nextcloud 27 developments, and I am not aware of it). What do you think about this ?

**Comment by Pytal** [comment]
This scoped change is only for the filepicker and it is true that this change does not also show it in the files grid view but that is because the code is, as you guessed, separate

I agree that there should be consistency but as the files and filepicker grid views already diverge, i.e. files does not show the size while filepicker already does, I'd like to not scope creep this beyond what is described by the PR title @Jerome-Herbinet :)

**Review by Jerome-Herbinet — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
Tested and works

**Review by susnux — APPROVED** [review]
Works and resolved the specific issue :)

**Review by nimishavijay — APPROVED** [review]
Agreed with @Jerome-Herbinet about the consistency, so any adjustments in files can be a separate PR :) Look great, nice work!

**Review by JuliaKirschenheuter — APPROVED** [review]

**Pull request merged**
