### PR TITLE
Fix federated shares and permissions/resharing

### PR DESCRIPTION
**Pull request by solracsf**
See https://help.nextcloud.com/t/problems-with-federated-shares-and-permissions-resharing/60927 for the whole thread

### CODE REVIEW

**Comment by nickvergessen** [comment]
The thread is 2 years old, is this still a problem? There have been some changes regarding permissions also recently

**Comment by acsfer** [comment]
I was facing the exact same error message with 20.0.9, hence the PR

`Error: Unsupported operand types at /lib/private/Share20/Manager.php#325`

This fixed it.

**Comment by nickvergessen** [comment]
But permissions is defined in https://github.com/nextcloud/server/blame/2b8e47dcace5d329a874c0dfa9a30cfbc551ca80/lib/private/Share20/Manager.php#L303 already

**Comment by acsfer** [comment]
You are absolutely right, my mistake, the instance causing the issue is under 18, not 20... 🐘 
The one under 20 has no such problem, so considering fixed.

**Pull request closed without merging**
