### PR TITLE
add oauth2 password authentication

### LINKED ISSUE #25894: Support the 'password' grant type for OAuth2 clients
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

`grant_type=password` is convenient way to set up application passwords for mail clients using `dovecot` mail server. I implemented draft which looks working but only for `dovecot`, `Dovecot` just checks token existence to decide if user can login or not.

```
--- OauthApiController.php	2021-02-21 10:56:58.000000000 -0700
+++ OauthApiController.php.my	2021-03-02 12:22:31.023346218 -0700
@@ -90,15 +90,38 @@
 	 * @param string $client_secret
 	 * @return JSONResponse
 	 */
-	public function getToken($grant_type, $code, $refresh_token, $client_id, $client_secret): JSONResponse {
+	public function getToken($grant_type, $code, $refresh_token, $client_id, $client_secret, $username, $password): JSONResponse {
 
 		// We only handle two types
-		if ($grant_type !== 'authorization_code' && $grant_type !== 'refresh_token') {
+		if ($grant_type !== 'authorization_code' && $grant_type !== 'refresh_token' && $grant_type !== 'password') {
 			return new JSONResponse([
 				'error' => 'invalid_grant',
 			], Http::STATUS_BAD_REQUEST);
 		}
 
+		if ($grant_type === 'password') {
+			try {
+				$client = $this->clientMapper->getByIdentifier($client_id);
+			} catch (ClientNotFoundException $e) {
+				return new JSONResponse(['error' => 'invalid_client'], Http::STATUS_BAD_REQUEST);
+			}
+
+			if ($client->getClientIdentifier() !== $client_id || $client->getSecret() !== $client_secret) {
+				return new JSONResponse(['error' => 'invalid_client'], Http::STATUS_BAD_REQUEST);
+			}
+
+			try {
+				$token = $this->tokenProvider->getToken($password);
+				if ($token->getLoginName() !== $username) {
+					return new JSONResponse(['error' => 'Forbidden'], Http::STATUS_FORBIDDEN);
+				}
+			} catch (InvalidTokenException $e) {
+				return new JSONResponse(['error' => 'Invalid app password'], Http::STATUS_FORBIDDEN);
+			}
+
+			return new JSONResponse(['access_token' => 'fake-for-dovecot', 'username' => $username], Http::STATUS_OK);
+		}
+
 		// We handle the initial and refresh tokens the same way
 		if ($grant_type === 'refresh_token') {
 			$code = $refresh_token;
```

### PR DESCRIPTION
**Pull request by p5n**
Fix https://github.com/nextcloud/server/issues/25894

### CODE REVIEW

**Comment by kesselb** [comment]
This change looks wrong/incomplete. According to https://oauth.net/2/grant-types/password/ grant_type=password exchange username and password for a access token. This change calls getToken and passes $password as $tokenId. So $password ist actually the tokenId?

https://doc.dovecot.org/configuration_manual/authentication/oauth2/#proxy-with-password-grant seems the use case for this pull request.

@p5n your users are using a token already to authenticate with dovecot? And you need a way to validate that the token is valid?

**Comment by p5n** [comment]
I was able to set up test instance with dovecot `mechanisms = plain login`

Users can authenticate and get mail with username and application password, created on settings/security page.

I am sure that it is incomplete (I implemented only part required to make dovecot work) and maybe it is wrong.

**Comment by szaimen** [comment]
@p5n would you be willing to implement it correctly?

**Comment by p5n** [comment]
I'll try, but not sure when I can do it

**Comment by sorbaugh** [comment]
Hello @p5n, reading through the PR it seems unfortunately you didn't find the time to complete the PR and it got caught in our cleanup. Please feel free to reopen (or create a new PR) if you ever feel like tackling this again. We would be happy about that! :)

**Pull request closed without merging**
