### PR TITLE
Don't throw an exception when php-xml is missing

### LINKED ISSUE #2180: PHP7 Check for missing modules incomplete (should check for php-xml)
Nextcloud seems to check if a required php module is missing. This does not seem to be the case for php-xml. If this module is missing only a 500 server error is reported when accessing the page.

### Steps to reproduce
1. Install nextcloud on a machine using php7.0 and WITHOUT the php7.0-xml module installed
2. Access the nextcloud login page

### Expected behaviour
Nextcloud should tell me that the xml php module is missing as it does for other modules (like mbstring for example).

### Actual behaviour
A 500 server error is thrown and then I need to check the log. The log tells me: 
```
Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined function OC\\\\AppFramework\\\\simplexml_load_file()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(177): OC\\\\AppFramework\\\\App::buildAppNamespace('files')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(115): OC_App::registerAutoloading('files', '\\\/var\\\/www\\\/nextcl...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(658): OC_App::loadApps(Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1059): OC::init()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/index.php(46): require_once('\\\/var\\\/www\\\/nextcl...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php\",\"Line\":60}
```
And then I have to figure out myself that this may be due to a missing php module.

### Server configuration
**Operating system**: Ubuntu Xenial

**Web server:** Apache 2x

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from owncloud -> nextcloud 9 -> nextcloud 10.0.1

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke I guess we can also backport this later, so up to you if 11 or not

Fix #2180

### CODE REVIEW

**Comment by LukasReschke** [comment]
I guess this is because the compatibility check is performed later? Would an alternative be to move the compatibility check higher?

**Comment by nickvergessen** [comment]
Well the check uses language, therefor requires the user session, therefor session apps need to be loaded already => 'see no evil'

**Comment by nickvergessen** [comment]
On the otherhand this stuff doesnt happen accidentially. So I guess an english only message would also be fine.

**Comment by rullzer** [comment]
I would be fine by not having this message translated.

**Comment by MorrisJobke** [comment]
@nickvergessen Could you fix this?

**Comment by MorrisJobke** [comment]
> @nickvergessen Could you fix this?

Why do we even initialize a session if the instance is not yet installed. Maybe we could fix this the other way around.

**Comment by nickvergessen** [comment]
Sorry that will be way more work. Feel free to do that. It needs major changes in base.php and the Setup class.

**Pull request closed without merging**
