### PR TITLE
Hash cache key

### PR DESCRIPTION
**Pull request by Pytal**
Hash cache key to ensure that only valid characters are used 🔑

### CODE REVIEW

**Comment by skjnldsv** [comment]
Why and when did you encounter an issue with this? We need more explanations :wink:

**Review by skjnldsv — APPROVED** [review]
Code make sense

**Review by blizzz — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Review by szaimen — CHANGES_REQUESTED** [review]
many tests are failing?

**Comment by juliushaertl** [comment]
Looks like a temporary issue with composer but lets restart

**Comment by juliushaertl** [comment]
Failure unrelated

**Pull request merged**
