### PR TITLE
Deprecate marked, escapeHTML, formatDate, getURLParameter, humanFileS…

### PR DESCRIPTION
**Pull request by skjnldsv**
…ize, relative_modified_date and select2

Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:heart:

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Would be nice to also print which method to use instead then.

**Comment by MorrisJobke** [comment]
Conflicts 🙈

**Comment by danxuliu** [comment]
> Would be nice to also print which method to use instead then.

Even if it is not printed it would be good to at least have it documented in this pull request (just in case someone else besides me ends here when checking the commit history ;-) ); @skjnldsv could you mention which functions should be used instead? Thanks :-)

**Comment by ChristophWurst** [comment]
I think there was an existing npm package that does exactly what our function did. @skjnldsv what was its name?

**Comment by skjnldsv** [comment]
@ChristophWurst for the escapeHtml?

**Comment by ChristophWurst** [comment]
> Published 4 years ago

**Comment by skjnldsv** [comment]
Well, it's such a simple library I don't really see what you can do more to upgrade it xD

**Comment by ChristophWurst** [comment]
oh, lol, yes https://github.com/component/escape-html/blob/master/index.js#L33-L78 :laughing:

**Pull request merged**
