### PR TITLE
Fix undefined error on add-share

### PR DESCRIPTION
**Pull request by skjnldsv**
Not all calls of `add:share` provide a resolve function
https://github.com/nextcloud/server/blob/a100186e5e7dcbe95faa453d28b5cf0d20948639/apps/files_sharing/src/components/SharingInput.vue#L491

Prevents a call of an undefined function.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> The backport to stable21 failed. Please do this backport manually.

@skjnldsv 🏓

**Comment by skjnldsv** [comment]
Jesus christ
how

**Comment by skjnldsv** [comment]
Ah, It does not need backporting. awaitForShare was introduce for 22

**Pull request merged**
