### PR TITLE
fix(files): use backend error message if provided

### LINKED ISSUE #42551: [Bug]: SQL errors when inserting data (Data too long for column 'name')
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

An user try to upload file with a big file name, but the SQL column size is too small.
The frontend should already decline the upload of that file.

### Steps to reproduce

1. Select a file with a real long filename ( for example: remote.php/webdav/123/abc-defg-hijklmn/img/qr/SnhJUDAwdDU0WHNEWEloYlZNV2RLTnJEdk9xQUt3Z3NEcEZNUk9SL0V2NVFLamJ1TzdJT2dNMzVrSm5IcGVGWFdXUzI3aDZ1QU84S0NVZno5UTZheUdXZExqenkzMTYrd2xYZWJTczlnSEpqdENXL0hqcGFMVTZNOW5NR3ZlM1poK3ZJQUczYwdesgrdhfghnvcbcxfsefsqzedddcferzfdsdxvfseffdfgfgfgdgggfvcvxdf%3D%3D.jpg )
2. Upload it

### Expected behavior

Frontend should decline the upload wit a info/error popup/message

### Installation method

Other Community project

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/42551

image

Followup: use the same handling for [the drag and drop](https://github.com/nextcloud/server/blob/dbfd8f612bbf4b243fbce9d223746cc5355975eb/apps/files/src/services/DropService.ts#L67-L76) @susnux

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
/backport 9296efad91bcad6cf62fafc94604da88c8b42ca5 to stable28

**Review by skjnldsv — COMMENTED** [review]
/backport to stable28

**Comment by skjnldsv** [comment]
/skjnldsv-backport 90d50323d8a5c5808f238a76bc2f11f9b82493c0 to stable28

**Pull request merged**
