### PR TITLE
[stable14] always query the lookup server in a global scale setup 

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/nextcloud/server/pull/11714

I added the "developing" label as a indicator that you can ignore it until the master pr is merged. But please keep it open. So that in the unlikely case that this will not be merged before we are approaching 14.0.4 we have the PR with the milestone as a reminder that there is something which should be part of the release.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> I added the "developing" label as a indicator that you can ignore it until the master pr is merged. But please keep it open. So that in the unlikely case that this will not be merged before we are approaching 14.0.4 we have the PR with the milestone as a reminder that there is something which should be part of the release.

Don't worry I always go through all the "backport-request" PRs upon the arrival of a new maintenance release. It's just a mess to keep two branches in sync just for the reminder. THat's the reason I closed the other one. We do this way with so many PRs. So we are quite skilled to handle it this way. 😉 But because it is you I will keep it open. But for the next time you know that we will not forget to backport your PR. 🎉

**Comment by schiessle** [comment]
> It's just a mess to keep two branches in sync just for the reminder. 

Don't worry, I will take care of it. :slightly_smiling_face:   As long as it is labeled as "in development" it is also not a problem if it is not always 100% in sync.

**Review by rullzer — APPROVED** [review]
Code makes sense.

**Review by MorrisJobke — APPROVED** [review]
🐘

**Pull request merged**
