### PR TITLE
Migrations

### LINKED ISSUE #5155: Migrations
### Doctrine vs. ownCloud
I looked into Doctrine and ownCloud Migrations today, to see what would fit better with our needs. I saw that the difference is quite minimal:

* Doctrine comes with dependencies for better symfony support (yml instead of a class etc) and to trigger zend-events (a forth event system in nc?)
* ownCloud migrations have no "revert schema change" thing, but when you dropped a table/column you can't revert it back to get the data magically and I can see this point from DeepD

The code they come with is also rather minimal, since most of the PRs are the actual migrations.

I would now propose to go with ownCloud migration, only with two little changes:

### Change 1 - Single type only
They have 3 migration types: schema, sql and simple: https://github.com/owncloud/core/pull/27041/files#diff-333567435f8bef9975c29c5e73ab7dd0R372

I would merge them all into one kind with:
* preSchemaChange
* schemaChange
* postSchemaChange

Any of those can be empty. But it allows you e.g. to store data  inmemory instead of temp dir, change your db schema and then restore the data again, like we already did it in https://github.com/nextcloud/server/blob/master/apps/twofactor_backupcodes/lib/Migration/CopyEntriesFromOldTable.php

If you dont change the schema, you just leave it unchanged and only change your data in pre/post.

### Change 2 - Location

They have the migration files in appinfo/Migrations/ and load them via require_once. I would chose lib/Migration so we have normal autoloading.

cc @LukasReschke @rullzer

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Order problem with multiple major versions: https://github.com/nextcloud/server/issues/5155#issuecomment-305763805
- [x] Change one app to test it
- [x] Bring back oci table/column/index length check from `app:check-code`
- [x] Fix tests

Fix #5155

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Awesome stuff. I think we should get this in ASAP to iron out bugs in the dev cycle!

**Comment by MorrisJobke** [comment]
I fixed the merge conflict, but now the personal_sections table is not existent. @nickvergessen Could you fix that?

**Comment by MorrisJobke** [comment]
I did an update from stable12 to this and it caused that error:

```
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT "class" FROM "oc_personal_sections" WHERE "class" = ? LIMIT 1' with params ["OCA\\FederatedFileSharing\\Settings\\PersonalSection"]: SQLSTATE[HY000]: General error: 1 no such table: oc_personal_sections
```

**Comment by nickvergessen** [comment]
Wonderful, I love merge conflicts and follow up problems.

**Comment by nickvergessen** [comment]
Fixed, please merge asap.
Then we can move the existing DB to migrations as well and be done with this.

**Review by MorrisJobke — APPROVED** [review]
Works well

**Pull request merged**
