### PR TITLE
bump acceptance test suite to use php 7.1 image

### PR DESCRIPTION
**Pull request by blizzz**
For some reason I required the changes to run them locally…

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
fine by me

**Comment by blizzz** [comment]
also, with recent commit, added composer generated files to gitingore, since we don't include em

**Review by danxuliu — APPROVED** [review]
>  For some reason I required the changes to run them locally...

Strange... I have just run the acceptance tests locally on a freshly cloned server with the _nextcloudci/php7.0:php7.0-7_ image without problems. Maybe you have an application in the _apps_ directory that requires _php-7.1_?

Anyway, the tests also run without problems with _php-7.1_, so fine by me too ;-)

**Comment by blizzz** [comment]
>  Maybe you have an application in the apps directory that requires php-7.1?

That might actually be… since it works, merging. 7.1 is longer supported than 7.0 anyhow and should not cause any side effects.

**Pull request merged**
