### PR TITLE
make help available to ordinary users again

### PR DESCRIPTION
**Pull request by blizzz**
To reproduce:

* in master, log in as ordinary user. No admin, no subadmin
* open Help from settings menu

Screenshot_20191121_125443

SAML integration tests are failing because of that…

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Fair enough

**Review by ChristophWurst — APPROVED** [review]
Works. But I don't get why we need this annotation here. Could you elaborate? :confused:

**Comment by blizzz** [comment]
> Works. But I don't get why we need this annotation here. Could you elaborate? confused

Otherwise the settings app's Subadmin middleware is being triggered: https://github.com/nextcloud/server/blob/master/apps/settings/lib/Middleware/SubadminMiddleware.php#L69

**Comment by rullzer** [comment]
> Works. But I don't get why we need this annotation here. Could you elaborate? confused

Settings has additional middleware ;)

**Pull request merged**
