### PR TITLE
use unmasked permissions in shared scanner

### LINKED ISSUE #2658: Sharing and permissions
### Steps to reproduce
1. User A creates folder and share it with User B without deleting permissions
2. User B uploads file to sharing folder

### Expected behaviour
User A should be able to delete uploaded file in folder which he owns and shares with User B

### Actual behaviour
User A cannot delete uploaded file, like sharing permissions on User B also affects User A. In `filecache` table I can see limited `permissions` column parameters. This behavior could be "fixed" with `occ files:scan User A` command - after that User A can delete file, User B can't, `permissions` in `filecache` table transfers to expected. 

### Server configuration
**Operating system**:
Linux
**Web server:**
nginx 1.10.2
**Database:**
Mariadb 10.1.19
**PHP version:**
7.0.14
**Nextcloud version:** (see Nextcloud admin page)
11.0.0, previous 10.something was affected too
**Updated from an older Nextcloud/ownCloud or fresh install:**
from Nextcloud 10.something, from owncloud 9.something
**Where did you install Nextcloud from:**
AUR
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - external
  - files_accesscontrol
  - files_retention
  - firstrunwizard
  - tasks
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
<details>
<summary>Web server error log</summary>
no logs
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
no logs
</details>

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #2658

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Good stuff! Works and fixes the issue!

@LukasReschke @MorrisJobke @nickvergessen please have a look.

**Comment by LukasReschke** [comment]
Can we add an actual integration test using HTTP requests?

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Can we add an actual integration test using HTTP requests? – I won't accept it like that due to the risk of regressions. Thanks.

**Comment by icewind1991** [comment]
@LukasReschke done

**Comment by LukasReschke** [comment]
Thanks, @icewind1991.

Can you also add one for the original issue from https://github.com/nextcloud/server/pull/2486 / https://hackerone.com/reports/169680 ?

**Comment by icewind1991** [comment]
> Can you also add one for the original issue from #2486 / https://hackerone.com/reports/169680 ?

No, since the route that triggered that doesn't exist in 11 (upload.php)

**Comment by LukasReschke** [comment]
Fair enough.

**Review by LukasReschke — APPROVED** [review]

**Comment by LukasReschke** [comment]
I suppose this requires backports? :)

**Comment by icewind1991** [comment]
stable11 only afaik

**Comment by icewind1991** [comment]
stable10: https://github.com/nextcloud/server/pull/2697
stable11: https://github.com/nextcloud/server/issues/2696

**Comment by karlitschek** [comment]
backport makes sense

**Pull request merged**
