### PR TITLE
If cronErros is empty json_decode will return NULL

### LINKED ISSUE #9867: Setupcheck loaded on every settings page and js error
``` js
setupchecks.js:150 Uncaught TypeError: Cannot read property 'length' of null
    at Object.afterCall (setupchecks.js:150)
    at Object.<anonymous> (jquery.min.js:2)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
afterCall @ setupchecks.js:150
(anonymous) @ jquery.min.js:2
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
x @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
load (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
checkSetup @ setupchecks.js:305
(anonymous) @ admin.js:253
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
I @ jquery.min.js:2
```

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #9867

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
:heart:  :dancer:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
I added some fixes for the tests.

**Comment by MorrisJobke** [comment]
CI failure is a hiccup -> merging.

**Pull request merged**
