### PR TITLE
Date time picker position fix & design fixes

### LINKED ISSUE #7007: Expiry date calendar for shares is misplaced
* create a share
* open the menu of that share
* activate the expiry date
* actual: calendar widget is misplaced
* expected: calendar widget is positioned correctly

bildschirmfoto 2017-10-30 um 09 32 02

It is also unrelated to #6976 because it was broken before

cc @nextcloud/javascript @skjnldsv @jancborchardt

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #7007 

# Position 
|Before|After|
|:--:|:--:|
|kazam_screenshot_00009|kazam_screenshot_00008|

# Design
|Before|After|
|:--:|:--:|
|kazam_screenshot_00003|kazam_screenshot_00002|
|kazam_screenshot_00005|kazam_screenshot_00007|
|kazam_screenshot_00004|kazam_screenshot_00006|

### CODE REVIEW

**Comment by MorrisJobke** [comment]
* [ ] if the sidebar is scrolled (due to too small window) it adds the datepicker to the top:

bildschirmfoto 2017-12-13 um 12 26 23

**Comment by skjnldsv** [comment]
> if the sidebar is scrolled (due to too small window) it adds the datepicker to the top:

Not sure this is fixable. The datepicker uses a fixed positioning and does not allow direction settings! 😕

**Comment by jancborchardt** [comment]
Looks good! Can we also make sure that the triangle pointer of the popover is aligned to be centered below the input field? This looks especially off in the calendar timepicker, where the popover is off to the right. cc @georgehrke 

(Of course we have to make sure this also works on mobile.)

**Review by pixelipo — CHANGES_REQUESTED** [review]
Whitespace on the left when 24-hour scheme used:
image

**Comment by pixelipo** [comment]
@skjnldsv I've noticed the :arrow_up: issue while testing a non-absolute solution for AM/PM - Maybe you want to try with that as well:

```
        /* AM/PM fix */
+       table.ui-timepicker tr .ui-timepicker-hour-cell:first-child {
+               margin-left: 30px;
        }
        .ui-timepicker-table {
                th {
                        font-weight: normal;
                        color: nc-lighten($color-main-text, 33%);
                        opacity: .8;
+                       &.periods {
+                               padding: 0;
+                               width: 30px;
+                               line-height: 30px;
+                       }
                }
```
``` 
                        &.ui-timepicker-hours {
                                border-right: 1px solid $color-border;
-                               /* AM/PM fix */
-                               .ui-timepicker tr {
-                                       position: relative;
-                                       margin-left: 25px;
-                               }
                        }
```

**Comment by skjnldsv** [comment]
@pixelipo better?
How do you set 24h format btw?

**Comment by pixelipo** [comment]
@skjnldsv change the NC language (for example, Italian, German)

**Comment by pixelipo** [comment]
Still there, @skjnldsv :(
image

**Review by pixelipo — DISMISSED** [review]
Two more things needed here:

- [ ] Remove "Invalid date" text when no date is selected
- [ ] Add a placeholder `{{expirationDatePlaceholder}}`

**Comment by skjnldsv** [comment]
@pixelipo if you want to add your fixes directly here, please do :)

**Comment by rullzer** [comment]
@pixelipo @skjnldsv any chance to get this done? Beta4 is coming

**Comment by skjnldsv** [comment]
@rullzer yes, it's going in!

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@pixelipo Could you again review this? Thanks

**Comment by skjnldsv** [comment]
Need the fixes that pixelipo requested. But the alignment can't be fixed properly.

**Review by rullzer — APPROVED** [review]
Let's do this 🐘

**Comment by skjnldsv** [comment]
@pixelipo All clear! Default expiry date is set to NOW+1day (can't expire the same day)
And default placeholder fixed :)

**Comment by MorrisJobke** [comment]
I would go with this for now in the beta 4. The original issue was much more obvious and killed the proper selection of the expiry date. It is fixed in this PR and we should fix the other little paper cut regressions in followup PRs that will not make it into beta 4 but that should be fine.

**Comment by MorrisJobke** [comment]
I just tested again and it is fine as it is now.

**Comment by pixelipo** [comment]
Sorry I couldn't help you, guys - I'm sick and far away from my PC...

**Comment by MorrisJobke** [comment]
> Sorry I couldn't help you, guys - I'm sick and far away from my PC...

Don't worry :) Was just to get stuff fixed, that is actually broken and fix the small issues later on. :)

**Comment by MorrisJobke** [comment]
And @pixelipo rest and get well soon :)

**Comment by skjnldsv** [comment]
@pixelipo never apologise for being sick! :)
Get well soon! 🎈

**Comment by jancborchardt** [comment]
Just one thing, was the default expiry date now+1day? Seems a bit short, and now+1week seems better. Otherwise a lot of links will expire by default without opening.

@pixelipo get well soon! :)

**Pull request merged**
