### PR TITLE
Allow to validate the password_policy app

### PR DESCRIPTION
**Pull request by nickvergessen**
The problem is, that the 6MB files of the password lists take too much resources to be validated.
Therefor I added an ignore for that dir on the app.

@LukasReschke @MorrisJobke @rullzer 

Ref https://github.com/nextcloud/password_policy/pull/22

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by rullzer** [comment]
Yeah fair enough. LGTM

**Comment by MorrisJobke** [comment]
@nickvergessen is it already backported?

**Comment by nickvergessen** [comment]
Will backport to 10

**Pull request merged**
