### PR TITLE
Use new vue components in login form

### LINKED ISSUE #33822: Password visibility icon in login page out of place
Not sure if it’s a bug here on in the Vue components. cc @marcoambrosini:
image

### PR DESCRIPTION
**Pull request by CarlSchwan**
Close https://github.com/nextcloud/server/issues/33822

- Improve accessibility
- Simply code
- needs nextcloud vue component for missing props
- Needs https://github.com/nextcloud/nextcloud-vue/pull/3140 for being functional (name -> id change)

Error handling:

image

### CODE REVIEW

**Comment by juliushaertl** [comment]
master now has the vue components bump :)

**Review by nimishavijay — APPROVED** [review]
Looks good design wise!
Maybe this is irrelevant to this PR but 2 primary buttons close to each other is generally avoided, instead the `Login with Keycloak` button can have secondary button styling.

**Comment by CarlSchwan** [comment]
> Looks good design wise! Maybe this is irrelevant to this PR but 2 primary buttons close to each other is generally avoided, instead the `Login with Keycloak` button can have secondary button styling.

Good idea, it looks indeed nicer :)

image

**Review by artonge — APPROVED** [review]
Looks good :)

**Review by skjnldsv — APPROVED** [review]

**Review by jancborchardt — COMMENTED** [review]
Very nice! Just 2 details, possibly separate issues from this:

- Wording-wise we want to get away from saying "user" so should be "account name or email" here

- Not sure if it was introduced with this, but container has more space to the top than to the left

**Comment by CarlSchwan** [comment]
> Very nice! Just 2 details, possibly separate issues from this:
> 
>     * Wording-wise we want to get away from saying "user" so should be "account name or email" here
> 
>     * Not sure if it was introduced with this, but container has more space to the top than to the left

Done, new screenshot :)

image

**Review by jancborchardt — APPROVED** [review]
Nice! :)

**Pull request merged**
