### PR TITLE
[stable25] Avoid double ldap_unbind in Wizard.php

### PR DESCRIPTION
**Pull request by come-nc**
Manual backport of #34523

### CODE REVIEW

**Comment by come-nc** [comment]
Hum started as PR on master instead of stable25 by mistake, changed but it still failed DCO because of that it seems. Also sorry for all the PR request it was done by the code owner system when on the wrong target.

**Comment by skjnldsv** [comment]
Moved to 25.0.2

**Review by miaulalala — APPROVED** [review]
:elephant:

**Review by ChristophWurst — APPROVED** [review]
https://github.com/nextcloud/server/pull/34577/files?w=1 looks good

**Comment by come-nc** [comment]
CI failure unrelated

**Pull request merged**
