### PR TITLE
[stable12] Use separate element color in theming

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #6082 

I did a small adjustment for the border color of the login page, because the new layout isn't used yet on stable12. It works nicely 👍

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Ping - please review

**Comment by nickvergessen** [comment]
Works, but the top bar still has no bottom border, correct?

**Comment by MorrisJobke** [comment]
> Works, but the top bar still has no bottom border, correct?

Yes - this is a separate thing.

**Comment by MorrisJobke** [comment]
> Works, but the top bar still has no bottom border, correct?

Ummm wait - this was merged 2 weeks ago: #6108 😕

**Comment by MorrisJobke** [comment]
> Works, but the top bar still has no bottom border, correct?

Works for me just fine:

bildschirmfoto 2017-09-11 um 23 18 37

The bottom border is only shown if the color is pure white. Otherwise the border is not there (because it is not needed).

So this still works for me and is fine to be reviewed.

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
Fine by me :)

**Pull request merged**
