### PR TITLE
Allow shared versions again in legacy backend

### LINKED ISSUE #13750: Versions of files only visible for creator of shared folder
### Steps to reproduce
1. Create a folder and put files in it
2. Share the folder with other users or groups 
3. Change the file
4. Get the details of a shared file
5. look at the versions tab "No other versions available"

### Expected behaviour
I would expect that the version of the files are shown

### Actual behaviour
it says "No other versions available".
Only the user who created the folder can see the versions.

### Server configuration

**Operating system**:
Docker 15.02 Image

**Nextcloud version:** (see Nextcloud admin page)
15.02

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
docker repository

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

**Are you using external storage, if yes which one:** local/smb/sftp/...
nfs

**Are you using encryption:** yes/no
no
```

### PR DESCRIPTION
**Pull request by rullzer**
To make sure that the versions in the legacy backend are shared again we
have to check the storage of a file. Since all shared files are still on
the owners storage.

It is not the cleanest but it gets the job done

Fixes #13750

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by ChristophWurst — APPROVED** [review]
Tested and works :+1:

**Comment by LoiX07** [comment]
Hi,
I still got the issue on Nextcloud 18.0.4 with Group Folders.
Do you have any idea how to deal with ?

**Pull request merged**
