### PR TITLE
remove space between quota and colon

### PR DESCRIPTION
**Pull request by lihua-meow**
simple typo fix

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looks good to me! Welcome to Nextcloud @jinlin-wright :tada:

**Comment by jinlin-wright** [comment]
oops I don't understand the CI error

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
@jinlin-wright hey, thanks for your pr :)
You need to ship the compiled file as well

Please make `build-js-production` and commit the js + map files

**Review by jancborchardt — APPROVED** [review]
Looks good – @skjnldsv can you check?

**Comment by skjnldsv** [comment]
`./settings/js/settings-vue.js build is NOT up-to-date! Please send the proper production build within the pull request`

Apparently still not the proper files :)
And you forgot to sign the commit ;)

**Comment by skjnldsv** [comment]
@jinlin-wright I'm guessing you were not in the settings directory.
@rullzer updated the file, but we're still missing your signature on the 464696b5dc2dbdc1544b92f1ce4332c1b83084cc commit :)

Can you rebase and update the files?

**Comment by rullzer** [comment]
No sign off is fine in this case.
Thnx for the fix @jinlin-wright

**Pull request merged**
