### PR TITLE
Refine dashboard edit widget design

### PR DESCRIPTION
**Pull request by quentinguidee**
## Motivation

Currently, the dashboard "edit widget" section is not consistent (see before/after). This PR makes this menu more readable.

### Before

screenshot-before

### After

screenshot-after

### CODE REVIEW

**Comment by jancborchardt** [comment]
@quentinguidee very nice! :) Only one thing: The move from 160px to 170px width makes it so that these tiles are wider than the background image selector below. It would be good to keep them the same. It’s fine to keep it 160px width and ellipsize the text I’d say, what do you think?

**Comment by quentinguidee** [comment]
@jancborchardt Yeah it was intensional. It was because :
* Maybe subjectively, the 3 column version is more readable for me;
* Technically, the images don't have to be the same size as the component is not the same at all : the first are tickable buttons and the second is more of an image library. Different sizes allows to see directly that it's not the same setting/component.

But it's very subjective. To choose, I did 3 different versions (before review, after review and a narrower 3 column version). All 3 work, so take what you prefer.

<details>
<summary>3 columns, 170px (current PR)</summary>

Capture d’écran 2021-12-20 à 13 46 03
</details>

<details>
<summary>4 columns, 160px</summary>

Capture d’écran 2021-12-20 à 13 46 23
</details>

<details>
<summary>3 columns (another try with a smaller size)</summary>

Capture d’écran 2021-12-20 à 13 45 52
</details>

**Comment by quentinguidee** [comment]
Just fixed a bug with the overflow behaviour. Now working :

image

**Comment by quentinguidee** [comment]
I rebased this PR with master and reverted back the width of the cards.

<details>
<summary>Before</summary>

Capture d’écran 2022-03-19 à 12 02 40

</details>

<details>
<summary>After</summary>

Capture d’écran 2022-03-19 à 12 03 08

</details>

I don't know if the very small widget size was intended, so if not here's what it looks like with the large modal size :

<details>
<summary>Large</summary>

Capture d’écran 2022-03-19 à 11 49 09

</details>

**Comment by szaimen** [comment]
> don't know if the very small widget size was intended (as it is currently on `master`), so if not here's what it looks like with the large modal size :
> 
> Large

Large is fine by me 👍

**Comment by szaimen** [comment]
Please alao add screenshots for mobile :)

**Comment by quentinguidee** [comment]
Switched back to large.

@szaimen This PR doesn't change the layout, only the cards themselves, but here're the screenshots for different sizes :

<details>
<summary>Screenshots</summary>

Capture d’écran 2022-03-19 à 19 47 33

Capture d’écran 2022-03-19 à 19 48 08

And for *really small* screens :

Capture d’écran 2022-03-19 à 19 51 53

<details>

**Review by jancborchardt — APPROVED** [review]
Looks great now! :)

**Review by szaimen — APPROVED** [review]
fine by me

**Review by artonge — APPROVED** [review]

**Comment by szaimen** [comment]
CLI failure is unrelated

**Pull request merged**
