### PR TITLE
remove noise from detectUuid and cache results

### LINKED ISSUE #19418: NC17.0.3: log flooded with "Could not autodetect the UUID attribute"
With the update to 17.0.3 the `user_ldap` app floods the log with

`[user_ldap] Error: Could not autodetect the UUID attribute`

raw:
```
{"reqId":"enyG4OzyuY0jSGxQDRpO","level":3,"time":"2020-02-12T07:45:25+00:00","remoteAddr":"","user":"--","app":"user_ldap","method":"","url":"--","message":"Could not autodetect the UUID attribute","userAgent":"--","version":"17.0.3.1","id":"5e43ad16295d2"}
```

See also https://help.nextcloud.com/t/nc-17-0-3-could-not-autodetect-the-uuid-attribute/70350

#19097 and it's fix #19118 is not applicable to 17.0.3, also this is on ERROR level.

### PR DESCRIPTION
**Pull request by blizzz**
fixes #19418 

* error level reduced to debug, often it is just false positives
* result is also mem-cached now, so it is not redone too often, if left to default
* stops further read requests when the user is invalid

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
