### PR TITLE
Fix Borken UUID Attribute Detection

### PR DESCRIPTION
**Pull request by blizzz**
With https://github.com/nextcloud/server/pull/1729 (downstreamed…) UUID detection got broken. On default installations, the LDAP backend would figure out the correct UUID attribute fetch the value accordingly. Because an empty was replaced wrongly in one place, detection was never really done, instead the UUID was indeed written for users, but falsely using the username.

The UUID is used to recognize users on the directory even when they were moved within the LDAP tree and have a different DN. A fix could lead to the point that this detection will fail, if the wrong value was written.

Affects master and 11.

* [x] Write an integration test specifically for UUID attribute detection
* [ ] Figure out why a "fallback value was written at all, usually the user would be skipped
* [x] Most likely needs an update / repair step routine 

Also fixes a faulty test.

fyi @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@karlitschek @LukasReschke I would love to see this fixed in 11.0.2. Otherwise moving users in the LDAP tree would not be detected properly. I would avoid the risk of delaying this for the next release.

**Comment by karlitschek** [comment]
backport ia fine

**Comment by blizzz** [comment]
We should be complete now. Reviews welcome, @MorrisJobke @LukasReschke @rullzer @nextcloud/ldap

**Comment by blizzz** [comment]
Now, the reproducing the issue is harder than it seemed to be first. On the classical way, via the LDAP wizard, it is very very tough if not impossible to get into this scenario. It seems rather to happen when a more programmatic approach is being used to configure LDAP (e.g. occ commands, or the OCS API). Thus, the possible impact (as affected instances) is far smaller than thought first.

**Review by MorrisJobke — APPROVED** [review]
Code looks good and didn't destroyed my existing setup 👍

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
