### PR TITLE
l10n improvements from transifex

### PR DESCRIPTION
**Pull request by rakekniven**
Fixed typo and removed doclink symbol.
Reported at transifex

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by rakekniven** [comment]
@ChristophWurst Thank you for approving.
Test failed. Same as here #5160 
Something is wring on CI system.

**Comment by rakekniven** [comment]
@MorrisJobke Same here with missing signature.
Next time I will try to add signature using github webinterface. I do not use git at command line.
Thank you for merging.

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@rakekniven Don't worry - I fixed it for you and also fixed the unit tests that also contained that string. 😉

**Comment by rakekniven** [comment]
@MorrisJobke Now there are two positive reviews.
Beginner question: Who will finally merge the PR?

**Comment by MorrisJobke** [comment]
> Beginner question: Who will finally merge the PR?

Somebody :D If the tests fail an admin needs to decide.

**Pull request merged**
