### PR TITLE
Add .bower.json to version control

### PR DESCRIPTION
**Pull request by rullzer**
We need .bower.json to have bower functioning correctly

Part of the 3rdparty cleanup

CC: @nickvergessen @MorrisJobke @icewind1991

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Review by MorrisJobke — APPROVED** [review]

**Comment by nickvergessen** [comment]
Can you check that https://github.com/nextcloud/server/blob/master/core/vendor/.gitignore is okay with this?

**Comment by MorrisJobke** [comment]
> Can you check that https://github.com/nextcloud/server/blob/master/core/vendor/.gitignore is okay with this?

I added the rules.

**Comment by nickvergessen** [comment]
@MorrisJobke I guess that is the reason, why adding markup failed and updated jquery back then 😝 

👍

**Comment by nickvergessen** [comment]
@MorrisJobke drone died?

**Comment by MorrisJobke** [comment]
> @MorrisJobke drone died?

Nope, somehow some hooks are not properly delivered :(

**Pull request merged**
