### PR TITLE
[Integration Tests] Clear opcode cache after config change

### PR DESCRIPTION
**Pull request by LukasReschke**
Let's see…

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> All checks have passed

soooo… what did you debug/test here? I'm just curious …

**Comment by LukasReschke** [comment]
```
13:13:12 R<rullzer> mmm I rebased https://github.com/nextcloud/server/pull/3905 on master... but your fancy new test fails... https://drone.nextcloud.com/nextcloud/server/6992/7 ... known?
```

😃

**Comment by LukasReschke** [comment]
Also failing on https://github.com/nextcloud/server/pull/4304 … mhm…

**Comment by nickvergessen** [comment]
If all failes, use the testing apps api

**Comment by LukasReschke** [comment]
> If all failes, use the testing apps api

Yeah. I suspect the OPCode cache to be to blame… Let me add a small PHP file to the testing app that cleans the OPCode. For testing purposes only of course :-)

**Comment by LukasReschke** [comment]
Ok. This seems to do now 🚀

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
