### PR TITLE
 Top bar buttons in share view are wrong positioned

### PR DESCRIPTION
**Pull request by pixelipo**
Fixes nextcloud/gallery#269

### CODE REVIEW

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Not fully - now the normal share page is a bit broken (but looks the same on share and gallery share)

Before & after:
bildschirmfoto 2017-07-31 um 10 49 59
bildschirmfoto 2017-07-31 um 10 50 01

**Comment by pixelipo** [comment]
That's because I missed adding one file while committing last time... Thanks for noticing, @MorrisJobke 

By the way, I consider this PR only a quick-fix. Long-term, I don't see any reason to have 2 named container inside the main `#header` object. Right-hand-side elements could easily be positioned with simple CSS `margin-left: auto` I could do some cleanup later - @schiessle can you tell me what the ".logo-claim" element does? It was added by you [years ago](https://github.com/nextcloud/server/commit/2141c41d0d76e0363324018d52272ebb82fa7b36), but it doesn't seem to be maintained (or used for that matter). Legacy ownCloud code?

**Comment by LukasReschke** [comment]
> It was added by you years ago, but it doesn't seem to be maintained (or used for that matter). Legacy ownCloud code?

Yes. Can be removed. The ownCloud Enterprise Edition also displays that it is an Enterprise Edition in the header. Basically a brand awareness thing :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
> Yes. Can be removed. The ownCloud Enterprise Edition also displays that it is an Enterprise Edition in the header. Basically a brand awareness thing :)

I would say, that we should not put everything in an endless PR. Best ist to make a separate one for this change.

**Review by jancborchardt — APPROVED** [review]
Looks good now, and yeah let’s solve the extra element issue in a separate PR. :)

**Comment by jancborchardt** [comment]
I’m guessing the Drone sqlite samba failure is unrelated? https://drone.nextcloud.com/nextcloud/server/487/54

**Comment by pixelipo** [comment]
I added back `id` selectors just to make sure this doesn't brake apps that might still use them. It's better for the code to "work everywhere" than "look nice" :wink: 

Ready for merging.

**Comment by MorrisJobke** [comment]
I will merge once the CI jobs are finished.

**Comment by MorrisJobke** [comment]
@pixelipo Could you create a branch with the same commits based on stable12 and open this as a PR here? (the backport PR)

**Comment by MorrisJobke** [comment]
Backport is in #6112

**Pull request merged**
