### PR TITLE
25.0.0 beta 7

### PR DESCRIPTION
**Pull request by skjnldsv**
* #24596
* #32740
* #33502
* #33512
* #33658
* #33718
* #33733
* #33793
* #33819
* #33921
* #33941
* #33947
* #33964
* #33992
* #33993
* #34001
* #34009
* #34018
* #34019
* #34020
* #34022
* #34023
* #34024
* #34026
* #34028
* #34030
* #34031
* #34035
* #34039
* #34042
* #34043
* #34044
* #34045
* #34048
* #34050
* #34051
* #34055
* #34057
* #34060
* #34062
* #34063
* #34065
* #34066
* #34067
* #34068
* #34069
* #34071
* #34072
* #34073
* #34076
* #34081
* #34084
* #34091
* #34096
* #34097
* #34098
* #34100
* #34101
* #34105
* #34107
* #34108
* #34110
* #34113
* #34118
* #34122
* nextcloud/activity#867
* nextcloud/activity#912
* nextcloud/activity#916
* nextcloud/activity#920
* nextcloud/activity#923
* nextcloud/activity#925
* nextcloud/activity#926
* nextcloud/example-files#25
* nextcloud/files_rightclick#142
* nextcloud/firstrunwizard#738
* nextcloud/firstrunwizard#739
* nextcloud/logreader#776
* nextcloud/logreader#777
* nextcloud/logreader#778
* nextcloud/logreader#779
* nextcloud/logreader#781
* nextcloud/logreader#782
* nextcloud/logreader#783
* nextcloud/logreader#784
* nextcloud/notifications#1273
* nextcloud/notifications#1274
* nextcloud/notifications#1275
* nextcloud/photos#1161
* nextcloud/photos#1225
* nextcloud/photos#1228
* nextcloud/photos#1231
* nextcloud/photos#1232
* nextcloud/photos#1233
* nextcloud/photos#1234
* nextcloud/photos#1235
* nextcloud/photos#1236
* nextcloud/photos#1240
* nextcloud/photos#1241
* nextcloud/photos#1242
* nextcloud/photos#1243
* nextcloud/photos#1244
* nextcloud/photos#1245
* nextcloud/photos#1246
* nextcloud/photos#1248
* nextcloud/photos#1249
* nextcloud/photos#1251
* nextcloud/photos#1253
* nextcloud/photos#1254
* nextcloud/photos#1256
* nextcloud/photos#1258
* nextcloud/text#2863
* nextcloud/text#2866
* nextcloud/text#2867
* nextcloud/text#2877
* nextcloud/text#2878
* nextcloud/text#2882
* nextcloud/text#2884
* nextcloud/text#2893
* nextcloud/text#2895
* nextcloud/text#2907
* nextcloud/text#2908
* nextcloud/text#2912
* nextcloud/text#2913
* nextcloud/text#2914
* nextcloud/text#2918
* nextcloud/text#2926
* nextcloud/text#2927
* nextcloud/text#2928
* nextcloud/text#2929
* nextcloud/text#2930
* nextcloud/text#2931
* nextcloud/text#2932
* nextcloud/text#2933
* nextcloud/text#2934
* nextcloud/text#2965
* nextcloud/text#2967
* nextcloud/viewer#1371

Pending PRs:

* [ ] #17425 @xklonx
* [ ] #23036 @chrisfritsche
* [ ] #23695 @rullzer
* [ ] #23825 @rullzer
* [ ] #23914 @rullzer
* [ ] #25023 @RafaOP
* [ ] #25109 @icewind1991
* [ ] #25192 @blizzz
* [ ] #25471 @rullzer
* [ ] #25551 @rullzer
* [ ] #25768 @icewind1991
* [ ] #26155 @blizzz
* [ ] #26318 @icewind1991
* [ ] #26320 @icewind1991
* [ ] #26408 @kevin147147
* [ ] #26496 @christlang
* [ ] #26871 @brueckner
* [ ] #26940 @rullzer
* [ ] #27034 @juliushaertl
* [ ] #27492 @cyclops8456
* [ ] #27538 @icewind1991
* [ ] #27613 @Dreamsorcerer
* [ ] #27806 @p5n
* [ ] #27820 @juliushaertl
* [ ] #27961 @CarlSchwan
* [ ] #28019 @Pytal
* [ ] #28226 @gary-kim
* [ ] #28310 @juliushaertl
* [ ] #28311 @juliushaertl
* [ ] #28601 @juliushaertl
* [ ] #28635 @TSI-yogeshshejwadkar
* [ ] #28636 @TSI-yogeshshejwadkar
* [ ] #28645 @TSI-kavitasonawane
* [ ] #28772 @icewind1991
* [ ] #28832 @TSI-yogeshshejwadkar
* [ ] #28834 @TSI-kavitasonawane
* [ ] #28911 @danxuliu
* [ ] #29010 @mattian
* [ ] #29143 @eneiluj
* [ ] #29430 @CarlSchwan
* [ ] #29642 @szaimen
* [ ] #29643 @szaimen
* [ ] #29729 @eneiluj
* [ ] #29861 @Zocker1999NET
* [ ] #29892 @Pytal
* [ ] #29940 @jonathanmmm
* [ ] #29988 @MichaIng
* [ ] #30147 @Phlogi
* [ ] #30183 @Pytal
* [ ] #30223 @CarlSchwan
* [ ] #30359 @juliushaertl
* [ ] #30366 @marcelklehr
* [ ] #30412 @quentinguidee
* [ ] #30472 @juliushaertl
* [ ] #30498 @juliushaertl
* [ ] #30586 @solracsf
* [ ] #30608 @solracsf
* [ ] #30613 @blizzz
* [ ] #30654 @pavelkryl
* [ ] #30777 @AsamK
* [ ] #30796 @icewind1991
* [ ] #30895 @mdoggydog
* [ ] #30957 @rotdrop
* [ ] #30972 @icewind1991
* [ ] #30980 @kominoshja
* [ ] #30986 @rotdrop
* [ ] #31001 @takahiro-blab
* [ ] #31038 @itmanagerro
* [ ] #31064 @tcitworld
* [ ] #31160 @CarlSchwan
* [ ] #31286 @rotdrop
* [ ] #31346 @CarlSchwan
* [ ] #31469 @nextcloud-command
* [ ] #31499 @juliushaertl
* [ ] #31571 @michielbdejong
* [ ] #31660 @dzatoah
* [ ] #31699 @CommanderRoot
* [ ] #31790 @tcitworld
* [ ] #31793 @CarlSchwan
* [ ] #31807 @jotoeri
* [ ] #31859 @max65482
* [ ] #31905 @icewind1991
* [ ] #31938 @szaimen
* [ ] #31944 @PVince81
* [ ] #31947 @andyxheli
* [ ] #32006 @thomasrockhu-codecov
* [ ] #32012 @CarlSchwan
* [ ] #32018 @CarlSchwan
* [ ] #32019 @CarlSchwan
* [ ] #32028 @icewind1991
* [ ] #32032 @Valdnet
* [ ] #32038 @nickvergessen
* [ ] #32163 @icewind1991
* [ ] #32197 @blizzz
* [ ] #32211 @artonge
* [ ] #32226 
* [ ] #32231 @skjnldsv
* [ ] #32257 @artonge
* [ ] #32309 @CarlSchwan
* [ ] #32314 @icewind1991
* [ ] #32321 @tcitworld
* [ ] #32440 @carlcsaposs
* [ ] #32441 
* [ ] #32466 @Pytal
* [ ] #32499 @eneiluj
* [ ] #32523 @carlcsaposs
* [ ] #32524 @carlcsaposs
* [ ] #32530 
* [ ] #32562 @icewind1991
* [ ] #32565 @ChristophWurst
* [ ] #32631 @ASerbinski
* [ ] #32632 @icewind1991
* [ ] #32635 @andyxheli
* [ ] #32739 @artonge
* [ ] #32761 @nickvergessen
* [ ] #32775 @Pytal
* [ ] #32781 @unteem
* [ ] #32787 @jcjveraa
* [ ] #32877 @icewind1991
* [ ] #32899 @Retidurc
* [ ] #32912 @CarlSchwan
* [ ] #32961 @CarlSchwan
* [ ] #33061 @pboguslawski
* [ ] #33087 @szaimen
* [ ] #33091 
* [ ] #33104 @miaulalala
* [ ] #33105 @nickvergessen
* [ ] #33106 @vitormattos
* [ ] #33161 @vincentdh
* [ ] #33203 @solracsf
* [ ] #33221 @tcitworld
* [ ] #33239 @juliushaertl
* [ ] #33292 @icewind1991
* [ ] #33322 @PVince81
* [ ] #33381 @luzpaz
* [ ] #33397 @cneukom
* [ ] #33434 @Jerome-Herbinet
* [ ] #33458 @icewind1991
* [ ] #33482 @juliushaertl
* [ ] #33484 @danxuliu
* [ ] #33511 @artonge
* [ ] #33545 @karlitschek
* [ ] #33546 @JustAdamHere
* [ ] #33578 @nickvergessen
* [ ] #33579 @icewind1991
* [ ] #33581 @icewind1991
* [ ] #33582 @icewind1991
* [ ] #33597 @icewind1991
* [ ] #33669 @Jerome-Herbinet
* [ ] #33709 @juliushaertl
* [ ] #33737 @andyxheli
* [ ] #33755 @juliushaertl
* [ ] #33779 @CarlSchwan
* [ ] #33795 @pboguslawski
* [ ] #33915 @JuliaKirschenheuter
* [ ] #33918 @icewind1991
* [ ] #33928 @justin-sleep
* [ ] #33930 @ChristophWurst
* [ ] #33945 @blizzz
* [ ] #33977 @CarlSchwan
* [ ] #33985 @icewind1991
* [ ] #34056 @icewind1991
* [ ] #34082 @meichthys
* [ ] #34103 @ArtificialOwl
* [ ] #34115 @cdammanintopix
* [ ] #34117 @solracsf
* [ ] #34130 @nextcloud-command
* [ ] #34135 @eneiluj
* [ ] #34136 @blizzz
* [ ] #34137 @nickvergessen
* [ ] nextcloud/3rdparty#902 @kvikshaug
* [ ] nextcloud/activity#327 @tinko92
* [ ] nextcloud/activity#460 @madmas
* [ ] nextcloud/activity#504 @chrisfritsche
* [ ] nextcloud/activity#530 @tintou
* [ ] nextcloud/activity#646 @TSI-nareshrai
* [ ] nextcloud/activity#693 @fschrempf
* [ ] nextcloud/activity#698 @icewind1991
* [ ] nextcloud/circles#190 @Shinrai
* [ ] nextcloud/circles#226 @fgsl
* [ ] nextcloud/circles#229 @fgsl
* [ ] nextcloud/circles#338 @hoxia
* [ ] nextcloud/circles#384 @tortuetorche
* [ ] nextcloud/circles#392 @tortuetorche
* [ ] nextcloud/circles#395 @tortuetorche
* [ ] nextcloud/circles#398 @tortuetorche
* [ ] nextcloud/circles#399 @tortuetorche
* [ ] nextcloud/circles#400 @tortuetorche
* [ ] nextcloud/circles#401 @tortuetorche
* [ ] nextcloud/circles#878 @ArtificialOwl
* [ ] nextcloud/circles#891 @ArtificialOwl
* [ ] nextcloud/circles#966 @ArtificialOwl
* [ ] nextcloud/circles#971 @rexbron
* [ ] nextcloud/circles#980 @ArtificialOwl
* [ ] nextcloud/circles#992 @solracsf
* [ ] nextcloud/files_rightclick#129 @FreesphereTom
* [ ] nextcloud/files_rightclick#135 @Cdisk2022
* [ ] nextcloud/files_rightclick#62 @dnviti
* [ ] nextcloud/files_videoplayer#115 @KiritoStudio
* [ ] nextcloud/files_videoplayer#196 @0xpr03
* [ ] nextcloud/files_videoplayer#249 @TSI-sangramdesai
* [ ] nextcloud/firstrunwizard#610 @mcnesium
* [ ] nextcloud/logreader#476 @Abijeet
* [ ] nextcloud/notifications#1266 @natoponen
* [ ] nextcloud/notifications#728 @nickvergessen
* [ ] nextcloud/notifications#939 @nickvergessen
* [ ] nextcloud/photos#1027 @TSI-ashishsharma
* [ ] nextcloud/photos#1062 @marcelklehr
* [ ] nextcloud/photos#1247 @artonge
* [ ] nextcloud/photos#466 @dassio
* [ ] nextcloud/photos#502 @Mikescops
* [ ] nextcloud/photos#515 @Mikescops
* [ ] nextcloud/photos#607 @cnmicha
* [ ] nextcloud/photos#649 @DeJQit
* [ ] nextcloud/recommendations#354 @blkqi
* [ ] nextcloud/recommendations#458 @sualko
* [ ] nextcloud/serverinfo#194 @hackerESQ
* [ ] nextcloud/serverinfo#257 @sausix
* [ ] nextcloud/serverinfo#264 @dertuxmalwieder
* [ ] nextcloud/serverinfo#267 @akhil1508
* [ ] nextcloud/serverinfo#331 @overhacked
* [ ] nextcloud/text#2163 @rotdrop
* [ ] nextcloud/text#2832 @juliushaertl
* [ ] nextcloud/text#2920 @vinicius73
* [ ] nextcloud/updater#312 @fermulator
* [ ] nextcloud/updater#90 @dlichtenberger
* [ ] nextcloud/viewer#1365 @pulsejet

### CODE REVIEW

**Comment by PVince81** [comment]
possibly higher priority:
- https://github.com/nextcloud/server/pull/34095
- https://github.com/nextcloud/server/pull/34072

**Comment by kofemann** [comment]
please consider https://github.com/nextcloud/server/pull/24596 PR as well

**Review by ArtificialOwl — APPROVED** [review]

**Comment by andyxheli** [comment]
Hi all please also consider https://github.com/nextcloud/server/pull/32635 PR as well :)

**Comment by blizzz** [comment]
Required PRs:

* [ ] https://github.com/nextcloud/server/pull/34137

**Comment by PVince81** [comment]
- [ ] required revert as it causes regressions: https://github.com/nextcloud/server/pull/34137

**Comment by blizzz** [comment]
> Hi all please also consider #32635 PR as well :)

There is still action items open from the reviews, so I build the next beta without it. But certainly would be great to have it for the first RC planned for Thu.

**Pull request merged**
