### PR TITLE
[Stable 10] Group shares with same source and target 

### PR DESCRIPTION
**Pull request by rullzer**
Backport of https://github.com/nextcloud/server/pull/474

Lets see if CI is happy.

CC: @LukasReschke @nickvergessen @MorrisJobke @schiessle

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Nope:

```

--- Failed scenarios:

    /drone/src/github.com/nextcloud/server/build/integration/features/sharing-v1.feature:763
    /drone/src/github.com/nextcloud/server/build/integration/features/sharing-v1.feature:907

```

**Comment by rullzer** [comment]
@MorrisJobke fix it!

**Comment by MorrisJobke** [comment]
:+1:

**Comment by schiessle** [comment]
:+1:

**Pull request merged**
