### PR TITLE
Workaround for disappearing app icons for Firefox before version 51

### PR DESCRIPTION
**Pull request by juliusknorr**
Fix for #2005

Please review and test @Luticus @nickvergessen

### CODE REVIEW

**Comment by MorrisJobke** [comment]
For me this still happens if I open the menu before the file list is completely loaded. Once the filelist appears the icons disappear. Maybe there is an interference between the loading of the file list and the app menu. 

https://cloud.morrisjobke.de/s/foMi2BUi61dTdLR

- after the first refresh: I wait until everything is loaded and then open the menu ✅ 
- after the second refresh: I open the menu before the file list is loaded :x:

**Comment by nickvergessen** [comment]
I guess this means we need to move it outside of the if?

**Comment by juliushaertl** [comment]
@MorrisJobke @nickvergessen Right, replaceState is also affected. :see_no_evil: 

Fixed and pushed.

**Comment by Mannshoch** [comment]
This Pach work for me.

Firefox: 49.0.2
Apps: AppOrder and DirectMenu

**Comment by MorrisJobke** [comment]
Tested and works 👍 

Code looks also good

**Comment by MorrisJobke** [comment]
Even works in IE and Edge without issues. 

Counting https://github.com/nextcloud/server/pull/2018#issuecomment-258466452 as :+1: -> merge

**Comment by MorrisJobke** [comment]
@karlitschek This should get backported.

@juliushaertl Could you create the backport PR for stable10? Thanks

**Comment by karlitschek** [comment]
please backport

**Comment by juliushaertl** [comment]
backport at #2025

**Comment by Mannshoch** [comment]
Uh.. strange side effect. Since I add this line of codes i'm not anymore able to open any directory in Owncloud. If I remove it, it works again.

**Comment by MorrisJobke** [comment]
> Uh.. strange side effect. Since I add this line of codes i'm not anymore able to open any directory in Owncloud. If I remove it, it works again.

Thanks for this - I can reproduce this. But this only happens in Firefox - in Chrome everything works

**Comment by MorrisJobke** [comment]
> Thanks for this - I can reproduce this. But this only happens in Firefox - in Chrome everything works

#2033

**Pull request merged**
