### PR TITLE
Update ca bundle checker

### PR DESCRIPTION
**Pull request by kesselb**
Match `version/noid/14.0.1` and `version/14.0.1`.
Use DRONE_SOURCE_BRANCH because DRONE_COMMIT_REFSPEC is not available anymore.

(build with version/01.01.01 as branch name https://drone.nextcloud.com/nextcloud/server/18626/3/3 and executed check)

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> Match `version/noid/14.0.1` and `version/14.0.1`.
> Use DRONE_SOURCE_BRANCH because DRONE_COMMIT_REFSPEC is not available anymore.

Thanks! I didn't sticked to the old convention :/

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
