### PR TITLE
Fix redundant urldecode() 

### LINKED ISSUE #6822: redirect_url seems to be double URL-decoded after login
### Steps to reproduce
1. open index.php/login?redirect_url=/index.php/apps/discoursesso%3Fsso%3Dbm9uY2U9YjVlYzMxNDE3MjFiZTY5Nzg2OGZiMzRiZTMwY2RmZDQmcmV0dXJu%250AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmRpc2NvdXJzZS5oYWJpZGF0Lm9yZyUy%250ARnNlc3Npb24lMkZzc29fbG9naW4%253D%250A%26sig%3D99e5cf7ede3c4819595321f1b0139a226820bb2ae4336a2d3b4a7180244a85df

### Expected behaviour
This should actually redirect to my app with the parameters sso and sig

### Actual behaviour
Instead it shows a blank page and below error message in the logs. The reason is that the parameter sso contains string "%0A" (URL encoded %250A), which is the URLencoded version of newline. Somewhere this is decoded to the actual new line character, therefore somewhere urldecode is called too often. 

> {"reqId":"OFod0w9WrbeszhcZQkVk","level":0,"time":"2017-10-12T09:07:55+00:00","remoteAddr":"90.146.106.214","user":"fhumer","app":"PHP","method":"GET","url":"\/index.php\/login?redirect_url=\/index.php\/apps\/discoursesso%3Fsso%3Dbm9uY2U9YjVlYzMxNDE3MjFiZTY5Nzg2OGZiMzRiZTMwY2RmZDQmcmV0dXJu%250AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmRpc2NvdXJzZS5oYWJpZGF0Lm9yZyUy%250ARnNlc3Npb24lMkZzc29fbG9naW4%253D%250A%26sig%3D99e5cf7ede3c4819595321f1b0139a226820bb2ae4336a2d3b4a7180244a85df","message":"**Header may not contain more than a single header, new line detected at** \/var\/www\/html\/lib\/private\/AppFramework\/Http\/Output.php#68","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.101 Safari\/537.36","version":"12.0.3.3"}

I checked the generateRedirect function in the LoginController and there the parameter $redirectUrl is already passed like this:

> \/index.php\/apps\/discoursesso?sso=bm9uY2U9YjVlYzMxNDE3MjFiZTY5Nzg2OGZiMzRiZTMwY2RmZDQmcmV0dXJu%0AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmRpc2NvdXJzZS5oYWJpZGF0Lm9yZyUy%0ARnNlc3Npb24lMkZzc29fbG9naW4%3D%0A&sig=99e5cf7ede3c4819595321f1b0139a226820bb2ae4336a2d3b4a7180244a85df

Therefore it has already been decoded once, but in the functioin it gets decoded (urldecode()) again which leads to the error. 

### Server configuration

**Operating system**: Debian

**Web server:** Apache 2

**Database:** Mysql 10.1.21

**PHP version:** 7.1.10

**Nextcloud version:** 12.0.3.3.

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "ocw8n0b1uteh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.willy-fred.org",
            "cloud.habidat.org",
            "cloud.lebeningemeinschaft.ag",
            "cloud.lebeningemeinschaft.at",
            "office.willy-fred.org",
            "office.habidat.org",
            "discourse.habidat.org"
        ],
        "trusted_proxies": [
            "172.19.0.200"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "habidat-mysql-db",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "appstore.experimental.enabled": true,
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mail.xaok.org",
        "mail_domain": "willy-fred.org",
        "mail_smtpport": "25",
        "maintenance": false,
        "loglevel": 0,
        "log_rotate_size": 10485760,
        "ldapUserCleanupInterval": 10,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "debug": true,
        "overwrite.cli.url": "https:\/\/cloud.habidat.org",
        "overwriteprotocol": "https"
    }
}

</details>

### PR DESCRIPTION
**Pull request by soudis**
Fixes #6822

### CODE REVIEW

**Comment by skjnldsv** [comment]
Thanks for your contribution, please sign your work when committing!

https://github.com/nextcloud/appstore/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by soudis** [comment]
is it sufficient to do this here?

Signed-off-by: Florian Humer <soudis@gmx.at>

**Comment by skjnldsv** [comment]
@soudis for such small change, yes! :+1: :wink:

**Review by nickvergessen — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Unit tests fail:

```
1) Tests\Core\Controller\LoginControllerTest::testLoginWithoutPassedCsrfCheckAndLoggedIn
Expectation failed for method name is equal to "getAbsoluteURL" when invoked 1 time(s)
Parameter 0 for invocation OCP\IURLGenerator::getAbsoluteURL('another%20url'): string does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'another url'
+'another%20url'

/drone/src/github.com/nextcloud/server/core/Controller/LoginController.php:254
/drone/src/github.com/nextcloud/server/core/Controller/LoginController.php:287
/drone/src/github.com/nextcloud/server/tests/Core/Controller/LoginControllerTest.php:558

2) Tests\Core\Controller\LoginControllerTest::testLoginWithValidCredentialsAndRedirectUrl
Expectation failed for method name is equal to "getAbsoluteURL" when invoked 1 time(s)
Parameter 0 for invocation OCP\IURLGenerator::getAbsoluteURL('another%20url'): string does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'another url'
+'another%20url'

/drone/src/github.com/nextcloud/server/core/Controller/LoginController.php:254
/drone/src/github.com/nextcloud/server/core/Controller/LoginController.php:373
/drone/src/github.com/nextcloud/server/tests/Core/Controller/LoginControllerTest.php:595
```

**Comment by ChristophWurst** [comment]
Apparently this was submitted twice, so I closed the other PR https://github.com/nextcloud/server/pull/10681.

**Comment by leonklingele-work** [comment]
This fixes an issue where logged out users accessing
`/ocs/v2.php/cloud/users/details?search=leon%3Ftest` are redirected to
`/ocs/v2.php/cloud/users/details?search=leon?test` after logging in whereas
`/ocs/v2.php/cloud/users/details?search=leon%3Ftest` is the correct redirect URL.

**Comment by soudis** [comment]
I do not really know the whole unit test area of this project very well, e.g. how they come about and who makes them, but it seems that the unit test that is failing is tailored to the current wrong behaviour of this function. Can a more experienced person take on this and have a look? The unit test is the only thing blocking this change to finally get in. @ChristophWurst maybe? 

Also @leonklingele-work now also found a case where this is a problem without the discoursesso app. 

Thanks in advance!

**Comment by nickvergessen** [comment]
Since the origin repo does not exist anymore, someone needs to redo the patch

**Comment by leonklingele-work** [comment]
```sh
$ wget -qO- https://github.com/nextcloud/server/pull/13137.patch | git am
```

?

**Comment by nickvergessen** [comment]
Feel free to do it and also fix the tests while you are on it:
https://github.com/nextcloud/server/pull/13137#issuecomment-452319343

**Pull request closed without merging**
