### PR TITLE
[stable23] Update autoloaders and Node package-lock.json

### PR DESCRIPTION
**Pull request by MichaIng**
Autoloaders update is required to solve Drone checkers, `package-lock.json` update to solve all Node checks.

I simply did:
```sh
bash build/autoloaderchecker.sh
npm i
```
PHP version was 8.1, in case it is relevant.

### CODE REVIEW

**Comment by artonge** [comment]
The issue might come from npm `v8.6` https://github.com/npm/cli/issues/4684

**Comment by MichaIng** [comment]
Ah, so the local build was not the issue, but since the workflow installs `npm i -g npm@">=7.0.0"`. I'll try to fix it by using `"~8.5"`.

**Review by blizzz — APPROVED** [review]

**Review by blizzz — CHANGES_REQUESTED** [review]
Please rerun the npm step with `npm ci` for CI

**Comment by MichaIng** [comment]
Okay worked now. The three Node modules have now been added to `package-lock.json`. Please someone with more insights into Node dependencies have a look whether those are the intended versions.

**Comment by blizzz** [comment]
@skjnldsv ^

**Review by blizzz — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
