### PR TITLE
Move away from legacy OC_L10N

### PR DESCRIPTION
**Pull request by rullzer**
This file was still lying around used in a few places that could (and should) use `\OCP\IL10N` etc.
- Convert OC_L10N usages
- Cleanup tests
- Remove OC_L10N
- Remove OC_L10N tests

CC: @LukasReschke @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I will review this and while doing this also fix all the apps in our repo.

**Comment by MorrisJobke** [comment]
We should put this in the release notes ;)

**Comment by MorrisJobke** [comment]
Tested and works so far 👍

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@rullzer Doc update? Release notes ;)

**Pull request merged**
