### PR TITLE
Fix l10n in federated file sharing

### PR DESCRIPTION
**Pull request by ChristophWurst**
Otherwise it uses the core l10n files.

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]
Good catch 👍

**Comment by nickvergessen** [comment]
Oh wow

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> There was 1 error:
> --
> 1) OCA\FederatedFileSharing\Tests\FederatedShareProviderTest::testCreate


Seems related

**Comment by ChristophWurst** [comment]
> Seems related

Seems like a random failure. Passes now?

**Pull request merged**
