### PR TITLE
Javascript code coverage

### PR DESCRIPTION
**Pull request by rullzer**

### CODE REVIEW

**Comment by rullzer** [comment]
Ok good to go. Lets get this bad boy in so we can also keep an eye on js coverage.

CC: @ChristophWurst @LukasReschke @MorrisJobke @nickvergessen

**Comment by MorrisJobke** [comment]
👍

**Comment by LukasReschke** [comment]
Awesome! 🚀

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
