### PR TITLE
Fix OC.linkToOCS so it works as before @nextcloud/router v2.0.0

### PR DESCRIPTION
**Pull request by nickvergessen**
### Todo:
- [x] Revert "fixes" to `OC.linkToOCS` calls in https://github.com/nextcloud/server/pull/27281

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
Fixed the occurances

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
```
  OCA.Files_External.FileList tests
    loading file list for external storage
      ✗ render storage list
	Expected 'http://localhost:9876http://localhost/ocs/v2.php/apps/files_external/api/v1/mounts?format=json' to equal 'http://localhost:9876http://localhost/ocs/v1.php/apps/files_external/api/v1/mounts?format=json'.
	    at Object.<anonymous> (apps/files_external/tests/js/mountsfilelistSpec.js:119:24)

```

**Comment by nickvergessen** [comment]
Fixed

**Comment by szaimen** [comment]
Conflicts

**Pull request merged**
