### PR TITLE
Update license headers for 18

### PR DESCRIPTION
**Pull request by ChristophWurst**
Files will still change until the 18 final, but this brings us closer to correct author comments.

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by kesselb** [comment]
Is the license headers script able to parse the [mailmap](https://github.com/nextcloud/server/blob/master/.mailmap)? In that case we should probably map

```
skjnldsv@users.noreply.github.com -> skjnldsv@protonmail.com
28480705+MichaIng@users.noreply.github.com -> micha@dietpi.com
```

**Comment by juliushaertl** [comment]
> Is the license headers script able to parse the mailmap ? In that case we should probably map

Yes, sould work: https://github.com/nextcloud/server/blob/master/build/license.php#L355

**Review by juliusknorr — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Updated the script to exclude these special github users. Will push once the run is done (this scrip is slooooooooooooow)

**Comment by kesselb** [comment]
> Updated the script to exclude these special github users. Will push once the run is done (this scrip is slooooooooooooow)

Fine by me but they are not so special. You can use them to hide your real mail address. I would rather put them to mailmap for those cases.

**Review by skjnldsv — APPROVED** [review]

**Comment by kesselb** [comment]
Hmm. You removed some people now. They are probably sad. Please update the mailmap accordingly and include them again.

**Comment by ChristophWurst** [comment]
> Hmm. You removed some people now. They are probably sad. Please consider to update the mailmap accordingly and include them again.

It's hard. Because some of these noreply addresses are from review change suggestions

**Review by kesselb — APPROVED** [review]

**Pull request merged**
