### PR TITLE
Fixes the delete button not appearing on certain lower resolutions

### LINKED ISSUE #7539: The Delete action is not available in the file list header on narrow screens
When the window width is 688px or less and one or more files and/or folders are selected the _Delete_ action is not available in the file list header.

files-header-delete-not-available

@nextcloud/designers

### PR DESCRIPTION
**Pull request by Abijeet**
Greetings,

@danxuliu  - Please find the merge request that fixes #7539

I've done the following,
- Fixed the delete icon not appearing on all views where we have file selection and deletion option. 

Not exceptionally happy with this fix, but not sure how to fix this while making the least amount of changes. 

Please let me know if you'd like me to fix this in another way.

Signed-off-by: Abijeet <abijeetpatro@gmail.com>

### CODE REVIEW

**Comment by rullzer** [comment]
@Abijeet thanks for this :)

@danxuliu @skjnldsv can you guys have a look?

**Comment by danxuliu** [comment]
@Abijeet Thanks!

Unfortunately there are two issues with this approach:
  - the table header now has three columns, while the table body has two; I am not sure if that is valid HTML or not.
  - the actions in the header require more space, so they overlap with the _X folder(s)/X file(s)/X folder(s) and Y file(s)_ text "sooner" (I mean, they already overlapped before when the screen was narrow, but now they overlap on broader screens too).

To be honest I do not know what would be the best approach to solve those issues. Maybe collapse the actions in a menu when there is not enough space? Show the number of selected files and folder in one row and the actions in another one? Do not show the number of selected files and folders? @nextcloud/designers

**Comment by skjnldsv** [comment]
Hum, this is problematic indeed!
Can't we have two table headers and only show one with css? :)

**Comment by Abijeet** [comment]
OK, I've thrown out the older solution and now added the delete link in two places. I feel its a an *acceptable lesser evil*.

Note that I've changed the position of the icon in the delete link. In lower resolution it appears to the left of the text. It was looking out of place on the right hand side.

Here is a screenshot at 600px width - 

600px


I've also gone ahead and tried to fix the overlapping issue that @danxuliu mentioned. I'm hiding the text, and displaying only the icons on resolutions < 480px which takes care of most devices.

Let me know what you guys think.

Here are a few screenshots,

### Galaxy S5
galaxy-s5

### Apple SE
apple-se

### Nexus 6
nexus-6

### Nexus 5
nexus-5

### Apple 6 Plus Horizontal
apple-6-plus-horizontal

### Apple 6 Plus Vertical
apple-6-plus-vertical

**Comment by rullzer** [comment]
@danxuliu happy with the new solution?

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for review

**Comment by danxuliu** [comment]
@rullzer 
>  happy with the new solution?

Really happy! ;-)

@Abijeet Thanks a lot for the fix and the comprehensive set of screenshots! :-)

I took the liberty to amend your commit to fix the indentation (tabs instead of spaces). Besides that I have enlarged the touch area of the icons (although visually I prefer them packed together like in your screenshots the touch area for icons should be larger, like in the inline icons shown in the file list contents). Due to that the icons now need more space, so I have removed too the margin from the selected files summary, as they overlapped in narrow screens (specially with some languages like Japanese).

Unfortunately the overlapping still happens with some combinations of languages and screen widths, but I vote for getting this in and fix the overlapping in a different pull request.

**Review by danxuliu — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Awesome stuff @Abijeet ! Thnx again

**Comment by jancborchardt** [comment]
Sorry I only saw this now - and thanks @Abijeet! :)

- The buttons need proper 44*44px of clickable area according to the guidelines. They are too close together atm.
- On mobile these actions really need to go into a 3-dot-menu because there are no text labels at all and 3 actions.
- The "Delete" label should be right of the icon, like with the other icons

@Abijeet mind opening a follow-up pull request? :) Already adjusting the padding only would be great.

(Also, I added you to @nextcloud/designers, welcome! :)

**Comment by Abijeet** [comment]
@jancborchardt - Thanks for the invitation. I'll take a look at this tomorrow or day after.

**Comment by danxuliu** [comment]
>  - The buttons need proper 44*44px of clickable area according to the guidelines. They are too close together atm.

The touch area was already made larger than in the screenshots [in a later commit](https://github.com/nextcloud/server/pull/7634/commits/64c0874a153a9acbc55e761e4c8de6e47f4b7a6d), although it is not exactly 44x44px (it is slightly larger; I was thinking on the 48x48dp guideline of Android :-P And now that I check them the areas are 47x49 and 45x49... Oops :-) ).

>  - The "Delete" label should be right of the icon, like with the other icons

Just for the record, it has been in the wrong order [since some time ago](https://github.com/nextcloud/server/commit/b634f1e2c70809a4fde7f738cb7c252b6fc3f4dc#diff-92e2995b57237c4e192a9ff5bb620e2eR67), it was not caused by @Abijeet changes; in fact, @Abijeet [added them in the right order for narrow screens](https://github.com/nextcloud/server/commit/361aaf0c95ef17dfdf79c5e1f11efc005e2babcf#diff-92e2995b57237c4e192a9ff5bb620e2eR63) ;-)

**Comment by jancborchardt** [comment]
Ah ok, thanks for the clarification. :) Bigger tap area is fine, mainly the visual issue is that it doesn't line up with the icons on the other rows, and there being 3 unlabeled icons on mobile. :)

**Comment by Abijeet** [comment]
@jancborchardt  - This is what I'm going to be doing in a separate PR - 

1. On mobile the actions - Move to, download and delete will be going into a 3-dot-menu.
2. Ensure that the *Delete* label should be right of the icon, like with the other icons on all resolutions.

Please note that there will be some HTML that will be duplicated.

**Comment by jancborchardt** [comment]
@Abijeet yes, sounds good! Additionally on mobile the 3-dot-menu should be right of the "2 folders & 1 file" text. That way it is connected to it and findable, unlike when it would be all the way on the right (which will especially be problematic on tablets).

And another thing: In the guest view for a read-only shared folder, there will only be a single action: Download. In that case there should not be a 3-dot-menu, but the single action shown directly.

**Pull request merged**
