### PR TITLE
chore(theming): fix warning of incorrect `NcCheckboxRadioSwitch` usage

### PR DESCRIPTION
**Pull request by ShGKme**
## Summary

No visual changes.

Removes error:

image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
:pray: this was there for too long :+1:

**Review by emoral435 — APPROVED** [review]
love this change, especially because of how many lines this will declutter within the console!

Unrelated, but we should definitely fix our style guides problem for displaying this components props. Something I will assign myself for now, but do when we are done with all the accessibility issues :) [here](https://nextcloud-vue-components.netlify.app/#/Components/NcCheckboxRadioSwitch)

**Comment by ShGKme** [comment]
> Unrelated, but we should definitely fix our style guides problem for displaying this components props

https://github.com/nextcloud-libraries/nextcloud-vue/pull/5079

**Comment by emoral435** [comment]
/skjnldsv-backport 9310dbab7a132652a32b1b0c89a859b117dbdf08 stable28

**Pull request merged**
