### PR TITLE
fix: remove other shares from ui when deleted

### PR DESCRIPTION
**Pull request by max-nextcloud**
Remove the share entry in question
when unsharing a folder
from within the `others with access` section
of a file within that folder.

Using the code from the ShareList view here as well. Just copying the code here as this is a bugfix
that will need to be backported.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] ~~Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or~~ is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by mejo- — APPROVED** [review]
Code looks good to me. Didn't test, but I guess you did so :wink:

**Review by artonge — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failures are unrelated.

**Pull request merged**
