### PR TITLE
fix button on public upload page for mobile

### PR DESCRIPTION
**Pull request by jancborchardt**
Before & after:
capture du 2016-10-24 23-28-19capture du 2016-10-24 23-27-21

Please review @nextcloud/designers @xmartin

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
CI had hiccups - it passed in the push job -> merge

**Comment by jancborchardt** [comment]
Btw, this really seems like a bugfix we should backport (@rullzer do you agree? ;)

**Comment by jancborchardt** [comment]
Backports at https://github.com/nextcloud/server/pull/2056 and https://github.com/nextcloud/server/pull/2057

**Comment by MorrisJobke** [comment]
@jancborchardt Once the backport PRs are opened please remove the "backport-request" label 😉

**Comment by jancborchardt** [comment]
@MorrisJobke right, done!

**Pull request merged**
