### PR TITLE
Accessibility & design fixes on installation

### PR DESCRIPTION
**Pull request by jancborchardt**
- Keyboard focus and mouse hover feedback for 'Show password' toggle
- Fix tabbability of 'Storage & database' in install 
- Installation: Fix focus of database password toggle
- Fix .infield labels not being readable by screenreaders 

Please review @nextcloud/designers @nextcloud/accessibility :)

Help needed from @nextcloud/javascript for:
- [x] Open 'Storage & database' section on pressing enter when focused on the toggle (currently only works via mouse click)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Looks good to me!! :+1: 

EDIT: ah, did not see you were asking for help for the last point. :see_no_evil:

**Review by tyrylu — APPROVED** [review]
Looks okay to me, thanks.

**Comment by juliushaertl** [comment]
@jancborchardt I pushed a fix to open the "Storage & database" section on keypress.

**Review by juliusknorr — APPROVED** [review]

**Comment by jancborchardt** [comment]
@juliushaertl ah, thanks so much! Totally missed adding the `href="#"` and forgot that’s all that’s needed. :)

**Comment by jancborchardt** [comment]
The Drone failures seem unrelated to the installation part?

**Comment by skjnldsv** [comment]
@jancborchardt could you rebase to trigger a new drone test? :)

**Comment by rullzer** [comment]
I rebased since the base branch seemed to be a bit behind. Will merge once CI is done

**Pull request merged**
