### PR TITLE
Fix autocomplete suggestions with numeric users

### PR DESCRIPTION
**Pull request by nickvergessen**
1. Create a user with user id `123456`
2. Share a file with them
3. Mention the user in a comment on that file :boom: in console

### CODE REVIEW

**Review by marcoambrosini — APPROVED** [review]
Works!

**Review by blizzz — APPROVED** [review]
looks good

**Comment by blizzz** [comment]
I guess the failing tests are because of the share-acceptance thing. Would be good to re-run CI, when it is resolved.

**Comment by rullzer** [comment]
Rebased

**Review by gary-kim — APPROVED** [review]

**Pull request merged**
