### PR TITLE
Avoid double ldap_unbind in Wizard.php

### LINKED ISSUE #34086: [Bug]: Nc 25 TypeError: ldap_unbind(): supplied resource is not a valid ldap link resource
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Please see logs

### Steps to reproduce

N/A

### Expected behavior

N/A

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
NA
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
{"reqId":"aLmOBlDMzHDLmXCrghhl","level":3,"time":"2022-09-13T18:26:24+00:00","remoteAddr":"10.99.0.65","user":"admin","app":"index","method":"POST","url":"/apps/user_ldap/ajax/wizard.php","message":"ldap_unbind(): supplied resource is not a valid ldap link resource","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"25.0.0.11","exception":{"Exception":"TypeError","Message":"ldap_unbind(): supplied resource is not a valid ldap link resource","Code":0,"Trace":[{"function":"ldap_unbind","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/user_ldap/lib/LDAP.php","line":306,"function":"call_user_func_array"},{"file":"/var/www/nextcloud/apps/user_ldap/lib/LDAP.php","line":255,"function":"invokeLDAPMethod","class":"OCA\\User_LDAP\\LDAP","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/user_ldap/lib/Wizard.php","line":1096,"function":"unbind","class":"OCA\\User_LDAP\\LDAP","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/user_ldap/lib/Wizard.php","line":689,"function":"connectAndBind","class":"OCA\\User_LDAP\\Wizard","type":"->"},{"file":"/var/www/nextcloud/apps/user_ldap/ajax/wizard.php","line":96,"function":"guessPortAndTLS","class":"OCA\\User_LDAP\\Wizard","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Route.php","line":155,"args":["/var/www/nextcloud/apps/user_ldap/ajax/wizard.php"],"function":"require_once"},{"function":"OC\\Route\\{closure}","class":"OC\\Route\\Route","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":306,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/user_ldap/lib/LDAP.php","Line":306,"CustomMessage":"--"},"id":"632205fb4d581"}
```

### Additional info

https://stackoverflow.com/questions/34113844/php-ldaps-supplied-argument-is-not-a-valid-ldap-link-resource

### PR DESCRIPTION
**Pull request by come-nc**
Fix https://github.com/nextcloud/server/issues/34086

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by come-nc** [comment]
First commit is codesniffer only, what needs reviewing is the second commit, which removes a second call to unbind.
The first call is on https://github.com/nextcloud/server/pull/34523/commits/1d2d6e864dfd66397f277f32e7910e93058f674a#diff-03b35462543a3b900e8f873748210bae9370322383d5acd5c17913f31df1db96L1090

**Comment by blizzz** [comment]
master is 26

**Review by blizzz — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by come-nc** [comment]
CI failure unrelated

**Pull request merged**
