### PR TITLE
fix(settings): User management app navigation styles

### LINKED ISSUE #39940: [Bug]: User managment *+ Add group* button has strange inner border on hover
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is an unbalanced border

| Default | Hover |
|--------|--------|
| Bildschirmfoto vom 2023-08-17 16-54-51 | Bildschirmfoto vom 2023-08-17 16-54-54 | 

### Steps to reproduce

1. Open the user management

### Expected behavior

Good design

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

Tested with a820e3d036741ad1194361eca11bc1cbcdda0a47

### PR DESCRIPTION
**Pull request by Pytal**
- Fix https://github.com/nextcloud/server/issues/39940

## Summary

Before | After
--- | ---
image | image

- Increase keyboard focus outline contrast for app nav button
- Invert app nav icons when active
- Remove margin on app nav button
- Remove add group hover border

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by skjnldsv** [comment]
Why not material design icons?

- https://pictogrammers.com/library/mdi/icon/account-off/
- https://pictogrammers.com/library/mdi/icon/shield-account/
- https://pictogrammers.com/library/mdi/icon/account-group/

**Comment by Pytal** [comment]
> Why not material design icons?
> 
> * [pictogrammers.com/library/mdi/icon/account-off](https://pictogrammers.com/library/mdi/icon/account-off/)
> * [pictogrammers.com/library/mdi/icon/shield-account](https://pictogrammers.com/library/mdi/icon/shield-account/)
> * [pictogrammers.com/library/mdi/icon/account-group](https://pictogrammers.com/library/mdi/icon/account-group/)

Would also prefer that, sound good @jancborchardt?

**Review by ChristophWurst — APPROVED** [review]
Beautiful

**Comment by nimishavijay** [comment]
Always a yes for material design icons! :)

**Review by szaimen — APPROVED** [review]
LGTM from the screenshots

**Pull request merged**
