### PR TITLE
Update DAVx5 in AuthToken.vue

### PR DESCRIPTION
**Pull request by rfc2822**
Hi,

Please have a look at these changes:

1. It's named DAVx5 (only very old clients have DAVdroid in the User-Agent)
2. Use passive matching (?:droid|x5) because otherwise, "x5" is recognized and shown as operating system
3. Also include the version postfix which contains information like "-beta2", which is important for the user

Is renaming the constant `davDroid` to `davx5` somehow problematic?

### CODE REVIEW

**Comment by rfc2822** [comment]
This is how DAVx5 is shown before the MR:

Bildschirmfoto von 2021-01-11 19-33-01

1. "-beta2" is missing next to "3.3.8"
2. "x5" is shown as operating system

**Review by ChristophWurst — APPROVED** [review]
Sounds good!

I'm also fine if we leave the old user agent in for any older clients? Or is that too unlikely that someone still uses the davDroid app?

**Comment by rfc2822** [comment]
Yes I'd keep the `(?:droid|x5)` (as I have done in the MR) which should match both ones, just to be sure. I think they should both be displayed as DAVx5, which is the official name since 1.1.2019.

**Review by skjnldsv — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Pull request merged**
