### PR TITLE
Allow lazy app registration

### LINKED ISSUE #3784: Can not activate Mail app after migration 19 to 20
### Expected behavior
I was hoping to find my apps after the migration.
When activating Mail it should activate the app
When clicking "download and activate" it should activate the app

### Actual behavior
Mail was disabled during migration (after causing an error during migration)
Upon reactivation, a prompt appears saying `An error occurred during the request. Could not process the request.`
When I deleted and reinstalled the app, the same warning appeared after downloading the app.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)

**Mailserver or service:**Infomaniak 

### Server configuration

**Operating system**: ?

**Web server:** Apache 2.4.34

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.0

#### Client configuration
**Browser:** all

**Operating system:** all

### PR DESCRIPTION
**Pull request by ChristophWurst**
During app installation we run migration steps. Those steps may use
services the app registers or classes from composer. Hence we have to
make sure the app runs through the registration.

Fixes https://github.com/nextcloud/mail/issues/3784

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Very nice, fixes Mail and Deck not working with master for me! :)

**Comment by ChristophWurst** [comment]
At least the mysql test is also showing on other PRs, so that seems unrelated. Also the acceptance test looks like a random failure

**Comment by danxuliu** [comment]
> Also the acceptance test looks like a random failure

May look like, but it is not :-) The "Comments" tab no longer appears in the Files app sidebar (I guess now it is not loaded). Due to this, when the Files app sidebar is open for a directory it only has one tab (Sharing), which causes the tab header to be hidden. As the tab header is hidden but the test expects it to be there it fails.

**Comment by rullzer** [comment]
ouch yes we should fix that

**Pull request merged**
