### PR TITLE
[Stable 10] Fix Nextcloud vs oldCloud wording

### PR DESCRIPTION
**Pull request by jospoortvliet**
Fix Nextcloud vs oldCloud wording

### CODE REVIEW

**Comment by nickvergessen** [comment]
user "server" like in master, so we can backport the translated strings?

**Comment by tflidd** [comment]
It can be a different Nextcloud setup, but it could be any other federated cloud solution as well (ownCloud, pydio, ...)

**Comment by MorrisJobke** [comment]
> user "server" like in master, so we can backport the translated strings?

Don't worry - transifex fetches stable10 and master and also pushes this back - so no manual backporting needed ;)

**Comment by jospoortvliet** [comment]
Ok, so it says 'server' now (not sure who made that change, but :+1: ) - good?

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
👍

**Pull request merged**
