### PR TITLE
feat: Allow shared calendars as appointment conflict calendars

### LINKED ISSUE #3786: Allow shared calendars as appointment conflict calendars
**Is your feature request related to a problem? Please describe.**

As a user I might have calendars shared to me by other users, e.g. a company-wide calendar.

**Describe the solution you'd like**

It would be nice if I could select that shared calendar for appointment conflicts as well. Then company-wide events would also block appointment slots.

**Describe alternatives you've considered**

N/a

**Additional context**

- [x] https://github.com/nextcloud/server/issues/30068

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
Resolves: https://github.com/nextcloud/calendar/issues/3786
Requires: https://github.com/nextcloud/calendar/pull/6411

## Summary
Adjusted logic to use getCalendarsForUser to retrieve calendars, as this returns all personal and shared calendars.

### CODE REVIEW

**Review by tcitworld — COMMENTED** [review]
This looks not very efficient? Since you're always fetching all of the user's calendars even if you want to get a single one?

Maybe something like this old PR instead ? https://github.com/nextcloud/server/pull/36681

**Comment by ChristophWurst** [comment]
@SebastianKrupinski what do you think about Thomas' suggestion? Is it doable?

**Comment by SebastianKrupinski** [comment]
@ChristophWurst I did have a look at the old PR. It can not be applied/used for this situation directly as the CalendarProvider uses the back end directly and not through the CalendarHome class, we could add the getSharedCalendarByUri method to the back end and then do a separate call in the CalendarProvider for any shared calendars.

As the CalendarProvider->getCalendars() takes in a array of uri's I though it would be more efficient to just make two calls to the database (all shared and all personal) and then filter out the required calendars instead of making two calls to the database for each uri (one for shared and one for personal). If the getCalendars() is called with 4 uris, one way we only make 2 database quires the other we make 8.

What do you prefer?

**Comment by tcitworld** [comment]
Ah yes, it's a different case than https://github.com/nextcloud/server/pull/36681. You're right.

**Review by ChristophWurst — COMMENTED** [review]
I'm not opposed this change but it has to be tested carefully.

Listing all calendars, also those which are shared by others, influences all places that use the ``\OCP\Calendar\IManager::getCalendarsForPrincipal`` public API. We can't easily build an exhaustive list of users because this API is also used by apps.

Some places that use it:
* dav app - user status automation. Events in shared calendars will make you show as *In a meeting*. Intended?
* dav app - TimezoneService. If a shared calendar with timezone information is listed before a owned calendar, it will influence the detected timezone of the user. Intended?
* polls app

**Comment by SebastianKrupinski** [comment]
> I'm not opposed this change but it has to be tested carefully.
> 
> Listing all calendars, also those which are shared by others, influences all places that use the `\OCP\Calendar\IManager::getCalendarsForPrincipal` public API. We can't easily build an exhaustive list of users because this API is also used by apps.
> 
> Some places that use it:
> 
>     * dav app - user status automation. Events in shared calendars will make you show as _In a meeting_. Intended?
> 
>     * dav app - TimezoneService. If a shared calendar with timezone information is listed before a owned calendar, it will influence the detected timezone of the user. Intended?
> 
>     * polls app

As per our conversation, the returns are logically the same. The previous code path would return all calendars if no uri's are provided and only the asked for calendars if uri's are provided. The only real change is where the calendars list is sourced and how its filtered.

**Review by ChristophWurst — APPROVED** [review]
Code looks good! Did not test

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
