### PR TITLE
Make page loading faster, deferred script loading, now switchable:

### PR DESCRIPTION
**Pull request by michaelletzgus**
Deferred script loading can not be turnes on/off via config.php:

`'deferred_script_loading' => true,`

### CODE REVIEW

**Comment by michaelletzgus** [comment]
Default page load (file manager): 23 sec
With `deferred` enabled: 10 sec

Enabled Apps:

```
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.2
  - checksum: 0.3.4
  - circles: 0.9.6
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.1.4
  - direct_menu: 0.10.0
  - external: 2.0.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_automatedtagging: 1.2.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_external_sia: 0.1.2
  - files_markdown: 1.0.1
  - files_opds: 0.8.2
  - files_reader: 1.0.4
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - githubmergetracker: 0.0.17
  - gpxedit: 0.0.5
  - gpxpod: 2.1.1
  - groupfolders: 1.0.2
  - impersonate: 1.0.1
  - issuetemplate: 0.2.1
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - news: 11.0.0
  - nextant: 1.0.8
  - notes: 2.2.0
  - ocsms: 1.12.0
  - onlyoffice: 1.0.4
  - ownbackup: 17.5.0
  - passman: 2.1.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - qownnotesapi: 17.5.0
  - rainloop: 4.28.1
  - registration: 0.2.3
  - sharebymail: 1.2.0
  - sharepoint: 1.0.2
  - socialsharing_diaspora: 1.0.1
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - socialsharing_twitter: 1.0.1
  - spreed: 2.0.0
  - spreedme: 0.3.8
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - testing: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - twofactor_totp: 1.3.0
  - twofactor_u2f: 1.3.1
  - updatenotification: 1.2.0
  - weather: 1.4.1
  - workflowengine: 1.2.0
```

**Comment by MorrisJobke** [comment]
> Deferred script loading can not be turnes on/off via config.php:
> 
> 'deferred_script_loading' => true,

I really don't like such kind of things. If we think this is the way to go: we should do it. If not: then not. But we should definitely not offload this to administrators. That is a bad excuse for developers about being not sure about the outcome of a change and being able to blame the admin then if something breaks. :/

I would go for adding this by default right after we branched of stable12 and are heading to the 13 release.

**Comment by ChristophWurst** [comment]
> I would go for adding this by default right after we branched of stable12 and are heading to the 13 release.

Makes a lot of sense.

Deferred loading makes a huge difference on FF page loaded, even cached assets are loaded faster it seems and I don't see blank pages when switching apps – which is pretty cool :)

**Comment by rullzer** [comment]
Agreed. Lets do it early for 13!

**Comment by michaelletzgus** [comment]
It's now enabled by default - but can still be disabled with `"disable_deferred_script_loading" => true`.
The disabling mechanism is easy to remove, if desired...

**Comment by MorrisJobke** [comment]
> The disabling mechanism is easy to remove, if desired...

Kill it. Less options means less code that can break and less permutations of possible configurations.

**Comment by MorrisJobke** [comment]
stable12 is branched of. So I'm now fine with this, once my comment is addressed :)

**Comment by michaelletzgus** [comment]
Done!
No config option any more.

**Review by MorrisJobke — APPROVED** [review]
Works here 👍  (even in IE and Edge ;))

**Comment by MorrisJobke** [comment]
Ignore CI - the tests failures are unrelated.

**Review by ChristophWurst — APPROVED** [review]

**Comment by andrewborell** [comment]
Didn't dig into this very far yet but I tested this patch in my NC v12.0.3 instance where it seemed to break OnlyOffice integration. I notice NC v13 milestone and I have not tested against that version to confirm if the issue persists.  

Browser debug console indicates a "reference error: **OCA is not defined**" ( across all browsers, including mobile). No error is logged in nextcloud.log.   Removed with patch -p1 -R < 4854.patch  -- error went away immediately and integration resumed working as expected.  

That issue aside I saw a very big improvement in the load times.  Let me know if you need more info to reproduce integration issue.

**Comment by ChristophWurst** [comment]
Please open a new issue. Thanks.

**Comment by andrewborell** [comment]
@ChristophWurst After a little debugging I came to find 100% of my performance issue ( and evidently a javascript issue for jsxc.xmpp... CAPS error and jsxc.xmpp failed to load settings error ) were all resolved by configuring the site to use php-fpm.  Hard to believe I overlooked that configuration.  Speaking in terms of the compatibility of this fix with NCv12/13 as I posted in my previous message, I havent had a moment to go back and test things out since configuring fpm for the site.  

I went back through the NCv12 guide and searched for FPM\FCGI to check best practice and all I really found was this: 
> mod_spdy together with libapache2-mod-php5 / mod_php (use fcgi or php-fpm instead)

I cannot speak on behalf of nginx however under apache2 I find this software only performs well using fpm.  Testing with a single user connected you would never notice a difference, but when you get 15 or 20 users connected it's a difference of **minutes** for TTFB just to bring up the login page.

**Pull request merged**
