### PR TITLE
[stable24] Add bruteforce protection in OauthApiController

### PR DESCRIPTION
**Pull request by julien-nc**
Manual backport of #38773

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Review by nfebe — APPROVED** [review]

**Comment by julien-nc** [comment]
@blizzz Should we force merge this or is the EOL flag going to be removed for stable24 at some point?

**Comment by AndyScherzinger** [comment]
I think it'll be force merge 👍

**Comment by blizzz** [comment]
integration-auth did not run on drone.

**Comment by julien-nc** [comment]
@blizz It was a random failure. It has now ran and was successful.
The other failure is not related.

**Pull request merged**
