### PR TITLE
add a check for disk_free_space in Config.php

### PR DESCRIPTION
**Pull request by szaimen**
Follow-up to https://github.com/nextcloud/server/pull/36691

This is best reviewed like this: https://github.com/nextcloud/server/pull/37070/files?diff=unified&w=1

### CODE REVIEW

**Review by artonge — APPROVED** [review]
When does the `disk_free_space` function not exist ?

**Comment by szaimen** [comment]
> When does the `disk_free_space` function not exist ?

If it is whyever disabled by purpose by the admin...

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
> > When does the `disk_free_space` function not exist ?
> 
> If it is whyever disabled by the admin...

You had an actual usecase or is that extra caution?
Because any function can be disabled in php.ini and we cannot test all functions we use.

**Comment by szaimen** [comment]
> You had an actual usecase or is that extra caution?
> Because any function can be disabled in php.ini and we cannot test all functions we use.

https://github.com/nextcloud/server/pull/37062#discussion_r1127475570

**Pull request merged**
