### PR TITLE
contact hyperlink issue fixed

### LINKED ISSUE #24807: Contacts menu, more intuitive link to contact details
Would suggest to make the contact name the link to the detailed contact page, instead the additional "i" which then would be obsolete. Which would give room to link multiple mail addresses directly and/or link first mail address + first phone number in quick search.

Thanks for considering :-)

quick-search-details-link

### PR DESCRIPTION
**Pull request by devsekar-1992**
Close https://github.com/nextcloud/server/issues/24807

Signed-off-by: Gnana Sekar <developersekar1992@gmail.com>

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by szaimen** [comment]
@devsekar-1992 it seems like the compiled js is not up-to-date. Could you please compile it and push it to this branch? Thank you! :)

**Comment by devsekar-1992** [comment]
> @devsekar-1992 it seems like the compiled js is not up-to-date. Could you please compile it and push it to this branch? Thank you! :)


Am I need to run make build-js-production?

**Comment by szaimen** [comment]
> After run this command, no changes to commit and push

I will rebase your branch now. Please try again afterwards.

**Comment by devsekar-1992** [comment]
> > > After run this command, no changes to commit and push
> > 
> > 
> > I will rebase your branch now. Please try again afterwards.
> 
> @devsekar-1992 Please try again now :)

Need to pull my branch and run the command right?

**Comment by artonge** [comment]
> > > > After run this command, no changes to commit and push
> > > 
> > > 
> > > I will rebase your branch now. Please try again afterwards.
> > 
> > 
> > @devsekar-1992 Please try again now :)
> 
> Need to pull my branch and run the command right?

`git pull --rebase`

Could you also change the commit message to make it something more descriptive ? :)

**Comment by devsekar-1992** [comment]
> git pull --rebase

Nope still no changes in git  status

**Review by Pytal — APPROVED** [review]

**Comment by devsekar-1992** [comment]
@szaimen  Can you please help on this conflict issue?

**Comment by devsekar-1992** [comment]
> > That or `npm ci && npm run build`
> 
> @devsekar-1992 please try that again now :)

I ran this script. it shows nothing to commit

**Comment by szaimen** [comment]
> > > That or `npm ci && npm run build`
> > 
> > 
> > @devsekar-1992 please try that again now :)
> 
> Thanks. Conflicts has been fixed and I ran this script. it shows nothing to commit

Then the command is probably not working for you. Do you see some errors when running this command?

**Comment by devsekar-1992** [comment]
> > > > That or `npm ci && npm run build`
> > > 
> > > 
> > > @devsekar-1992 please try that again now :)
> > 
> > 
> > Thanks. Conflicts has been fixed and I ran this script. it shows nothing to commit
> 
> Then the command is probably not working for you. Do you see some errors when running this command?

No . please see below image

image

**Comment by szaimen** [comment]
Okay, does `git add .` work?

**Comment by szaimen** [comment]
> > Okay, does `git add .` work?
> 
> show only .rnd file

no idea then :/

---

lets try another approach: @skjnldsv can you please invite @devsekar-1992 to the org? I can then push the changes to a branch in this repo and we can use the compile bot :)

**Comment by artonge** [comment]
@devsekar-1992 

Looks like you are doing a rebase. Can you checkout the remote branch into another local branch?
Something like that should work:

```shell
git checkout -b contact-popover-hyperlink-issue-2 --track devsekar-1992/contact-popover-hyperlink-issue
```

**Comment by devsekar-1992** [comment]
> ```shell
> ```shell
> git checkout -b contact-popover-hyperlink-issue-2 --track devsekar-1992/contact-popover-hyperlink-issue
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

`git checkout -b contact-popover-hyperlink-issue-2 --track origin/contact-popover-hyperlink-issue` 
use above command and run npm ci & npm run build command. 

Created a new branch pull request
Conflicts 
https://github.com/nextcloud/server/pull/31928

**Pull request closed without merging**
