### PR TITLE
Allow to detect mimetype by content

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by rullzer** [comment]
Needs a rebase

**Comment by rullzer** [comment]
mmm CI does :boom:

**Comment by nickvergessen** [comment]
> 1) Test\Files\Type\DetectionTest::testDetectContent with data set #1 ('/data.tar.gz', 'application/x-gzip')
--
-'application/x-gzip'
+'application/octet-stream'

Great, works locally. I guess some package is missing. Let's try if testing all the content detections helps. If not someone else needs to take over, as this needs to go into the maintenance releases this week.

**Pull request merged**
