### PR TITLE
Fix checkboxes when theming color is enabled

### LINKED ISSUE #2089: Checkbox alignment is broken
Just looks not okay anymore

## Sharing
files_-_nextcloud_-_2016-11-11_09 21 55

## Activity settings
bildschirmfoto vom 2016-11-11 09-19-42

When all are checked or unchecked, they are all aligned @nextcloud/designers

### PR DESCRIPTION
**Pull request by juliusknorr**
fix #2089

Before
2016-11-16-140019_354x186_scrot
After
2016-11-16-140025_353x185_scrot

Checkboxes in user management also still work (#1782) - These should also be tested since the original fix #1971 has been reverted here.

Please review @nextcloud/designers @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
Works, as soon as the css file is rewritten (by changing the color)

👍

**Comment by skjnldsv** [comment]
What about the previous issue with the select in dropdown from the users management? Is it still fixed?

**Comment by juliushaertl** [comment]
@skjnldsv It is. :wink:

**Comment by skjnldsv** [comment]
👍

**Comment by jancborchardt** [comment]
Awesome work @juliushaertl :metal:  :)

**Pull request merged**
