### PR TITLE
Popovermenu fix and token settings design fixes

### PR DESCRIPTION
**Pull request by skjnldsv**
Update tokens devices list to popover standards, fix popover positionning with border (dark theme)
and alignment

### CODE REVIEW

**Review by ChristophWurst — COMMENTED** [review]
Popover on apps/sessions list looks the same on `master` and this branch – correct?

**Comment by rullzer** [comment]
@skjnldsv see @ChristophWurst comment ;)

**Comment by skjnldsv** [comment]
@ChristophWurst no, we respect the 44px sizes and the ui looks a bit nicer

**Comment by skjnldsv** [comment]
|Before|After|
|:--:|:--:|
|capture d ecran_2018-08-09_17-32-11|capture d ecran_2018-08-09_17-32-34|

**Review by rullzer — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> Before 	After

Didn't notice any difference while testing but here it's obvious :+1:

**Review by ChristophWurst — APPROVED** [review]
Fine by me :+1:

**Pull request merged**
