### PR TITLE
Add 2FA to logfile

### PR DESCRIPTION
**Pull request by Berzerker**
Signed-off-by: Berzerker <a.akker214@gmail.com>

Better auditing, support for third-party security tools like fail2ban

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Nice! Thanks a lot

**Review by LukasReschke — APPROVED** [review]

**Review by LukasReschke — CHANGES_REQUESTED** [review]
I'd prefer this being used in https://github.com/nextcloud/server/blob/9236733a838c91d8b275404f5f3497ddd200686e/apps/admin_audit/lib/Actions/Auth.php instead.

**Comment by LukasReschke** [comment]
Let me try to come up with an replacement here.

**Comment by ChristophWurst** [comment]
> LukasReschke approved these changes 4 minutes ago
> LukasReschke requested changes 3 minutes ago

🙈

**Comment by LukasReschke** [comment]
> LukasReschke approved these changes 4 minutes ago
> LukasReschke requested changes 3 minutes ago

All those buttons ;-)

**Comment by Berzerker** [comment]
Thanks. Ofc this was just pretty quick/dirty and with suggestions from @ChristophWurst.

It, at least, works for me for now, but I'll definitely keep up with this if you have a better solution.

**Comment by LukasReschke** [comment]
@nickvergessen I want to add a consumer to https://github.com/nextcloud/server/blob/9236733a838c91d8b275404f5f3497ddd200686e/lib/private/Authentication/TwoFactorAuth/Manager.php#L246-L259 so that the admin_audit log performs the logging here.

Is there a way to make the admin_audit app listen to the activity events or should I change this here to use the regular EventDispatcher and then make a PR to the activity app to listen to this event?

**Comment by nickvergessen** [comment]
> or should I change this here to use the regular EventDispatcher and then make a PR to the activity app to listen to this event?

This, but well server should listen to it's own hook, not the activity app.

**Comment by rullzer** [comment]
See #7916

**Pull request closed without merging**
