### PR TITLE
add owner-displayname property to calendars and addressbooks

### PR DESCRIPTION
**Pull request by georgehrke**

### CODE REVIEW

**Comment by georgehrke** [comment]
I get dozens of `Argument 1 passed to OCA\DAV\CalDAV\CalDavBackend::__construct() must implement interface OCP\IDBConnection, null given,` when executing the tests locally. Anyone having similar issues? 😕

**Comment by nickvergessen** [comment]
tests run fine here.

**Comment by rullzer** [comment]
Test work fine here as well. But I'd like to see the unit tests for this extended :wink:

**Comment by georgehrke** [comment]
>  But I'd like to see the unit tests for this extended

Yes, on it :)

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
I'm not a DAV expert, but changes look good to me

**Pull request merged**
