### PR TITLE
[downstream] Add submit button to validate the federated server,

### PR DESCRIPTION
**Pull request by LukasReschke**
fixes issue owncloud/core#25364

From https://github.com/owncloud/core/pull/26189 – tested it and it works here.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@jancborchardt Please review the smart button.

**Comment by LukasReschke** [comment]
Test is failing because missing sign-off and can thus be ignored.

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by jancborchardt** [comment]
Works nicely :+1: 

@schiessle?

**Pull request merged**
