### PR TITLE
Add ability to rename Groups in the frontend

### PR DESCRIPTION
**Pull request by martin-jnl**
Added the ability to change the display name of a group in the user settings menu, as discussed in #9209.

Added a popover menu to a group item in the group list, where the rename and delete actions of the group are now located.
Introduced a new component GroupListItem, so that the loading state of each group can be updated and each popover menu can be opened/closed individually.

First pull request, so please give me feedback. @nickvergessen 
Didn't commit the changed vue js files, because 14 files were changed and I'm fairly sure my changes should only change two of them (vue-settings-apps-users-management.js & .js.map)

### CODE REVIEW

**Comment by nickvergessen** [comment]
> Didn't commit the changed vue js files, because 14 files were changed and I'm fairly sure my changes should only change two of them (vue-settings-apps-users-management.js & .js.map)

The compile bot can help with that, just leave a comment with `/compile amend /`

**Review by nickvergessen — APPROVED** [review]
Works fine and looks good to me

**Review by skjnldsv — APPROVED** [review]

**Comment by ArcticFall** [comment]
> > Didn't commit the changed vue js files, because 14 files were changed and I'm fairly sure my changes should only change two of them (vue-settings-apps-users-management.js & .js.map)
> 
> The compile bot can help with that, just leave a comment with `/compile amend /`

Hm did not work with error: The user required level is not sufficient

**Comment by ArcticFall** [comment]
So what is the status on this?
Can I do something to move this forward?

**Comment by artonge** [comment]
I can't push changes to your repository.

Can you locally rebase and compile and push your changes ?

Should be enough:

```
git rebase origin/master
npm ci
npm run build
```

**Comment by ArcticFall** [comment]
Did that.

**Comment by szaimen** [comment]
@artonge you closed this?

**Comment by artonge** [comment]
Wrong git manipulation... will fix in a few minutes

**Comment by artonge** [comment]
Why are some CI steps not triggered?

**Comment by artonge** [comment]
CI failure unrelated

**Comment by artonge** [comment]
Thanks for this @ArcticFall, and sorry for the delay :)

**Comment by ArcticFall** [comment]
Thanks for carrying it over the finish line. I was completely lost at the end :D

**Pull request merged**
