### PR TITLE
Check if an app provide two-factor-auth providers before we try to use them

### PR DESCRIPTION
**Pull request by icewind1991**
Prevents log spam

### CODE REVIEW

**Comment by ChristophWurst** [comment]
:+1: makes sense. I think the error only occurs if ``$this->appManager->getEnabledAppsForUser($user)`` returns app IDs of apps that do not exist any more on the file system and therefore the info.xml file can not be loaded.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/534/files?w=1

:see_no_evil: :+1:

**Comment by nickvergessen** [comment]
Backport to stable10?

**Comment by MorrisJobke** [comment]
cc @icewind1991 @ChristophWurst @karlitschek

**Comment by karlitschek** [comment]
great. please backport 👍

**Comment by icewind1991** [comment]
Stable 10: https://github.com/nextcloud/server/pull/756

**Pull request merged**
