### PR TITLE
Use a better error message and point the users to the support channels

### LINKED ISSUE #1956: PHP Fatal error: repair-appconfig.php
### Steps to reproduce

This script is intended to repair data in ownCloud 8.2.1 data before upgrade to Nextcloud 9.0.54. 
Script was written by Nextcloud member @nickvergessen as a result of incident postings #297 and #1669.
1. Placed script in owncloud (renamed from nextcloud) directory. 
2. Created new ownCloud database.
3. Restored database from backups.
4. From command-line ran php repair-appconfig.php
5. Fatal PHP error raised while script was running
### Expected behaviour

Completion of PHP script with no fatal errors.
### Actual behaviour

Tell us what happens instead

Fixing missing records for app: systemtagsPHP Fatal error:  Call to undefined method OC_App::registerAutoloading() in /var/www/html/owncloud/repair-appconfig.php on line 59

**Please see previous two referenced incident postings at beginning of this incident.**
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Close #1956 

@schiessle @karlitschek @MorrisJobke as discussed

should backport this until 9

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport

**Comment by schiessle** [comment]
looks good :+1:

**Comment by schiessle** [comment]
`The class Doctrine\DBAL\Exception\TableExistsException does not exist. Did you forget a USE statement, or did you not list all dependencies?`

https://scrutinizer-ci.com/g/nextcloud/server/inspections/c293ed04-8094-4510-8124-b8c2fa1f1387/issues/files/lib/private/Installer.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

**Comment by nickvergessen** [comment]
Scrutinizer doesn't grab 3rdparty ;)

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
