### PR TITLE
Increase width of other active navigation indicators to 4px

### PR DESCRIPTION
**Pull request by juliusknorr**
Follow up of https://github.com/nextcloud/server/pull/8886

Before:
image

image

After:
image
image

@nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
Maybe we should standardise that into a variable?

**Review by skjnldsv — APPROVED** [review]
Otherwise, +1 of course :)

**Review by MariusBluem — APPROVED** [review]

**Comment by juliushaertl** [comment]
> Maybe we should standardise that into a variable?

I'd say we can do that if we use it on some other places as well, for now i'd just go with the plain values.

**Review by jancborchardt — APPROVED** [review]
Looks good!

**Pull request merged**
