### PR TITLE
Unit tests for ZIP getAllFilesStat()

### PR DESCRIPTION
**Pull request by PVince81**
Surprise! Bonus unit tests! :coin:

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Review by blizzz — DISMISSED** [review]
milestone not set

**Review by Pytal — APPROVED** [review]

**Comment by PVince81** [comment]
damn "Failed asserting that 1329531894 matches expected 1329528294"

I didn't expect the timestamps in the test file to change. I'll have a look later...

**Review by blizzz — CHANGES_REQUESTED** [review]
cf. https://github.com/nextcloud/server/pull/31944#issuecomment-1097657926

**Comment by PVince81** [comment]
will finish this another time, don't wait for it

**Comment by PVince81** [comment]
abandoned, I don't have time for this minor detail

**Pull request closed without merging**
