### PR TITLE
chore(files_sharing): use `OCSResponse` from `@nextcloud/typings`

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix technical debt
Lockfile was updated, that's why there are so many lines changed :)

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]

**Comment by emoral435** [comment]
Dunno why cypress is failing for version_naming 🤔 will rerun it

**Comment by skjnldsv** [comment]
> Dunno why cypress is failing for version_naming 🤔

flaky: fix in https://github.com/nextcloud/server/pull/43762

**Comment by susnux** [comment]
The type are not released yet? Still need to publish 1.8.0 ;)

**Comment by skjnldsv** [comment]
> The type are not released yet? Still need to publish 1.8.0 ;)

Done!

**Comment by skjnldsv** [comment]
Two errors:
```
WARNING in ./node_modules/moment/min/moment-with-locales.js 2159:16-50
Module not found: Error: Can't resolve './locale' in '/home/admin/git/server/node_modules/moment/min'
 @ ./node_modules/@nextcloud/moment/dist/index.mjs 1:0-50 2:0-65 6:0-8 9:58-72 9:73-81 15:0-17:2
 @ ./apps/files_trashbin/src/main.ts 24:0-39 48:21-32 49:27-38
```

And the dialogs
```
vue.runtime.esm.js:3065 TypeError: Cannot read properties of undefined (reading 'mounted')
    at injectHook (vue.runtime.esm.js:3320:1)
    at vue.runtime.esm.js:3306:1
    at useMounted (index.mjs:501:1)
    at useSupported (index.mjs:509:1)
    at useResizeObserver (index.mjs:2518:1)
    at useElementSize (index.mjs:2676:1)
    at setup (NcDialog-652A8lMI.mjs:158:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:3033:1)
    at initSetup (vue.runtime.esm.js:2457:1)
    at initState (vue.runtime.esm.js:5385:1)
```

**Comment by susnux** [comment]
@skjnldsv the first issue is `@nextcloud/moment` as `moment.js` is importing invalid files. We fixed that for `@nextcloud/webpack-config` but server is not using that so you have to adjust the server webpack config:
https://github.com/nextcloud-libraries/webpack-vue-config/pull/533

**Review by susnux — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]

**Pull request merged**
