### PR TITLE
Make it possible to filter by tags with REPORT method

### PR DESCRIPTION
**Pull request by rullzer**
From https://github.com/owncloud/core/pull/26099

Enhanced the REPORT method on the Webdav endpoint and added a
"oc:favorite" filter rule. When set, it will return a flat list of
results filtered with only favorite files.

The web UI was also adjusted to use this REPORT method instead of the
private API endpoint.

CC: @nickvergessen @MorrisJobke @icewind1991 @LukasReschke 

Test steps:
1. Favorite a few files in folders and subfolders, share one of them with link (for the share indicator).
2. Go to the "Favorites" section in the web UI.
3. Check the network console and see that it's using REPORT to get the results.
4. Check that the displayed results look fine and also contain the share indicator from the previous link share (it's part of the Webdav response)

### CODE REVIEW

**Comment by icewind1991** [comment]
Iirc favorites are just a system tag, wouldn't it be possible to reuse that filtering system

**Comment by rullzer** [comment]
@icewind1991 correct. But maybe do that seperatly from this port.

**Comment by nickvergessen** [comment]
No favorites are not system tags but the personal tags. otherwise favorites would be shared.

**Comment by MorrisJobke** [comment]
Tested and works 👍 

@nickvergessen @LukasReschke Could this get reviewed? It blocks https://github.com/owncloud/core/pull/26186/files to be downstreamed ;)

**Comment by LukasReschke** [comment]
World didn't explode 👍

**Pull request merged**
