### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by rullzer**
Kept internal number on the 9.x range to not make apps incompatible right away.

CC: @karlitschek @nickvergessen @LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
Yes. Let's keep it at 9.2 for now to stay compatible. Do you agree @DeepDiver1975 ?

**Comment by nickvergessen** [comment]
I also bumped all the app versions

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
@schiessle @LukasReschke @nickvergessen Mind to review this one?

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
