### PR TITLE
fix width of filename in sidebar to accommodate local link

### PR DESCRIPTION
**Pull request by jancborchardt**
Before / after:
capture du 2016-12-02 14-48-14
capture du 2016-12-02 14-49-42
Please review @nextcloud/designers

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I fixed this properly and it now has no whitespace to the right of the copy icon and properly ellipsises.

I tested this on Safari, Chrome, Firefox, IE11, Edge, Chrome on Android, Safari on iOS

👍 From me

**Comment by MorrisJobke** [comment]
@jancborchardt Could you have a look at my change

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
Much better @MorrisJobke 
@jancborchardt :whip:!

**Comment by icewind1991** [comment]
:+1:

**Comment by jancborchardt** [comment]
@MorrisJobke yeah, good call on the calc! :)

**Pull request merged**
