### PR TITLE
Fixes delete empty groups

### LINKED ISSUE #10234: Empty groups have no delete icon
Empty groups have no delete icon

This occours only in the new user management of NC14

grafik

### PR DESCRIPTION
**Pull request by weeman1337**
Displays the group actions also for groups without a count (because why not).  
Also adds a test, but (!) they're currently disabled...

closes #10234

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
@weeman1337 thanks a lot for your contribution. great stuff!

**Comment by rullzer** [comment]
@danxuliu could you have a quick look at the integration tests?

**Review by danxuliu — APPROVED** [review]
Tested and works :+1: 

@weeman1337 I took the liberty of amending your last commit (the one that added the acceptance test); the test is still not run, but I reworded _don't_ to _do not_ and changed how it is checked that there is no count for the section (it is needed to repeatedly check that there is no element, as otherwise it could be found before it was removed, and there is no need to throw an exception in the test, just use `PHPUnit_Framework_Assert::fail` :-) ).

**Comment by weeman1337** [comment]
@danxuliu thanks. Good to know for the next time.

**Comment by danxuliu** [comment]
@weeman1337 Thanks to you for your contribution and for making the effort to add the test :-)

**Comment by skjnldsv** [comment]
@weeman1337 We invited you to the nextcloud organisation! :)
Thanks you for your amazing work, and welcome onboard!

**Pull request merged**
