### PR TITLE
Add Flow app icon

### PR DESCRIPTION
**Pull request by jancborchardt**
Check it out @juliushaertl @blizzz :)

contributes to https://github.com/nextcloud/server/issues/12790

### CODE REVIEW

**Comment by blizzz** [comment]
That's how it looks in the settings:

Screenshot_20191106_161133

What is not sooo consistent, is that the drawing does not take the full height, compared to the others.

**Comment by rullzer** [comment]
> That's how it looks in the settings:
> 
> Screenshot_20191106_161133
> 
> What is not sooo consistent, is that the drawing does not take the full height, compared to the others.

Also looks a bit to small compared to the others...

**Comment by jancborchardt** [comment]
Right, will fix! :) (Bit difficult atm since my local setup is broken :O)

**Comment by jancborchardt** [comment]
@blizzz can you show me a screenshot how it looks like with this? https://cloud.nextcloud.com/s/PX7RTkZX66wykDN (it’s not compressed and adjusted yet, will do that if it looks fine)

**Comment by blizzz** [comment]
Screenshot_20191106_180305

@jancborchardt slightly better

**Comment by rullzer** [comment]
@jancborchardt I'm still not a big fan as I fear if you don't know what it is just looks to small. Beause of the two blocks when you look quickly it almost looks like the not supported emoji icon thingy.

**Comment by jancborchardt** [comment]
Yep, totally agree. Will sketch some more with simpler form, more square so it can be larger, and only with one of the boxes.

**Comment by jancborchardt** [comment]
Updated the icon as discussed @rullzer @blizzz, also squashed the commits by just transferring @blizzz’s changes by hand :O

**Review by blizzz — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by jancborchardt** [comment]
Drone failures unrelated?

**Comment by gary-kim** [comment]
> Drone failures unrelated?

Yes, the failures have been fixed by #17854

**Pull request merged**
