### PR TITLE
Show comments and restore in popover menu

### PR DESCRIPTION
**Pull request by skjnldsv**
| 0 | 1 | 2 |
|:-:|:-:|:-:|
|Capture d’écran_2019-04-02_10-56-19|Capture d’écran_2019-04-02_11-31-25|Capture d’écran_2019-04-02_11-31-50|

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks nice! Do we want to just say "1 comment" without the "new"? (Will probably be worse in other translations.)

**Comment by skjnldsv** [comment]
> Looks nice! Do we want to just say "1 comment" without the "new"? (Will probably be worse in other translations.)

I agree, but then it would not really be appropriate if you think about the real comments count? :thinking: 
`1 comment` would mean that there is only one comment, but it's only the unread ones :wink:

**Review by MorrisJobke — APPROVED** [review]
Looks good 👍

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
@jancborchardt so what do we do in the end?
Maybe we should not block the popovermenu size?

**Comment by jancborchardt** [comment]
Hm, then let's just go for it like it is in the PR now. :)

**Review by jancborchardt — APPROVED** [review]
:+1:

**Pull request merged**
