### PR TITLE
Ignore Enter key up event on menu button toggles

### PR DESCRIPTION
**Pull request by danxuliu**
Like links, buttons generate a `click` event as well as the regular `keydown` and `keyup` events when pressing Enter. Due to this, if both the `click` and the `keyup` events are handled, when the menu is open and Enter is pressed in the toggle the menu is first hidden when the first event is handled, but then shown again when the second event is handled. To prevent that only the `click` event should be handled, like already done with links.

I would backport this to _stable16_ (although manually, as the sources changed in Nextcloud 17).

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Make sense :)

**Comment by danxuliu** [comment]
The fix can be tested by clicking twice in the three dots button next to the call button in https://github.com/nextcloud/spreed/pull/2122

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
Rebased and ready to go :rocket:

**Review by nickvergessen — APPROVED** [review]
Fixes the issue in talk

**Pull request merged**
