### PR TITLE
remove reminders from read-only shared calendars

### LINKED ISSUE #679: Calendar: Remove valarms from objects in read-only shared calendars
In ownCloud once there was a patch that removed valarms on shared calenders.
The purpose is to not be flooded by alarms by read-only shared calenders.

Ref: https://github.com/owncloud/core/issues/24377

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #679

### CODE REVIEW

**Review by tcitworld — APPROVED** [review]
As a temporary fix for https://github.com/nextcloud/server/issues/679 this looks good, but what you said
> calendarobjects_per_user table to store custom custom alarms and transparency settings on a per sharee basis

 should be implemented instead, as I'm finding useful to have reminders from calendars shared with me as read-only.

**Comment by nickvergessen** [comment]
> should be implemented instead, as I'm finding useful to have reminders from calendars shared with me as read-only.

While I agree in general, I'd say lets fix the 99% usecase first ;)
So fine by me :)

**Comment by tobiasKaminsky** [comment]
Great :-)
Thank you, I am really looking forward to use this 👍

**Comment by nursoda** [comment]
Why is this commit not contained in 12.0.4?

**Comment by georgehrke** [comment]
Because we didn't backport it.
it's gonna be part of Nextcloud 13

**Comment by nursoda** [comment]
I'm on 13b3 now but I still get alarms for calendars I have no write access to. Am I missing something?

**Comment by georgehrke** [comment]
@nursoda Can you please open a bug report with detailed reproduction steps?

**Comment by nursoda** [comment]
You are right: After I deleted my DAVdroid account, re-added it and re-synced, old calendar entries with alarms in other user's calendars that are shared to me read-only no longer have an alert for me. Sorry I did not realize myself that caching may be the cause. And thanks for your swift answer!

Sidenote: I'm using DAVdroid and BusinessCalendar2. It's a PITA to delete and re-add an account since all BC settings (grouping, colors, reminder tones etc. must be re-set manually). Isn't there an easier way to flush its cache in DAVdroid? Not a nextcloud issue, though.

**Comment by CNeutron** [comment]
I just updated to 13, but Birthday Contacts still have reminders (directly in the webinterface, and on all my clients)
I deleted my birthday calendar, and did the "occ dav:sync-birthday-calendar username", but still have reminders

**Comment by georgehrke** [comment]
@CNeutron Yes, birthday contacts is **your** calendar, not a shared one.

**Comment by CNeutron** [comment]
Well I thought as it is a read only calendar, the reminders would stop waking me up at night. Also kinda because nursoda comments pointed in that direction

**Comment by nursoda** [comment]
As @georgehrke wrote, in bug #1505 wich deals with that enhancement, it's not implemented yet. THIS bug is solved for me (99%, see @nickvergessen's 1st comment above). Thus, should it remain open?

**Comment by georgehrke** [comment]
@nursoda Should what remain open? #1505 is about birthday calendars, which still contain alarms.

**Comment by nursoda** [comment]
Clearification:
1505 IS open, and that's correct (not implemented yet.
6903 (THIS bug) is "merged". Should it be "closed"?

**Comment by georgehrke** [comment]
> Should it be "closed"?

No, we can't close it, because this is not an issue but a pull-request.
While issues only have two states ("Open" / "Closed"), pull-requests have an additional state "Merged". 

- "Open" - the pull request is still in development / in review
- "Merged" - Changes were merged into Nextcloud and will be part of an upcoming release
- "Closed" - Changes were not merged into Nextcloud and won't be part of an upcoming release

So if you want to take changes from a pull-request into Nextcloud, you merge them, if you don't want to take the changes, you simply close the pull-request. 

The corresponding issue requesting this feature was automatically closed when merging this pull-request: https://github.com/nextcloud/server/issues/679

If you want to learn more details about pull-requests I recommend https://help.github.com/articles/about-pull-requests/

:)

**Comment by nursoda** [comment]
Thank you for your very easy yet comprehensive answer.
And sorry for my laziness not to have looked this up myself.

**Pull request merged**
