### PR TITLE
Prepare 14.0.1 release

### LINKED ISSUE #10894: Deprecated php warning
### Steps to reproduce
1. Use nextcloud

### Expected behaviour
No Warning/log entry

### Actual behaviour
Log entry on every page

### Server configuration

**Operating system**: Debian stretch

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.3.0 Beta2

**Nextcloud version:** (see Nextcloud admin page) 14 RC 1

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated at 
```
</details>

-----

**PS: PHP 7.3 works really well & fast!**

### PR DESCRIPTION
**Pull request by nickvergessen**
:no_entry: **Do NOT merge** :no_entry: 

## Changelog

* #11039 Fixes the upload progress bar layout - 14 backport
* #11077 [stable14] Fix markup and style of mentions in comments
* #11090 [stable14] Do not invalidate main token on OAuth
* #11103 [stable14] Expire tokens hardening
* #11152 [14] fix js files client for user names with spaces
* #11186 [stable14] Fix user and group listing with users that have an integer user id
* #11187 [stable14] Fix exception class
* #11191 [14] Remove posix_getpwuid and compare only userid
* #11201 [stable14]  fix check for more users in sharing dialogue
* #11237 [stable14] Remove filter_var flags due to PHP 7.3 deprecation, fixes #10894
* #11276 [stable14] Fix size of icons in menus inside apps when shown as images
* #11277 [stable14] Prevent comment being composed from overlapping the submit button
* #11280 [stable14] replace setcookie value with '' instead of null.
* #11282 [stable14] Fix the link and anchor for the update notifications
* #11283 [stable14] Include empty directories in the default state of acceptance tests
* #11287 [stable14] Get permission of storage for shares
* #11288 [stable14] Shared by info for room shares without names
* #11291 [stable14] Fix icons cacher regex for compressed output
* #11293 [stable14] Revert "Use APCu caching of composer"
* #11294 [stable14] Use user locale as default in the template
* #11302 [stable14] Fix expiration code of tokens
* [activity#295](https://github.com/nextcloud/activity/pull/295) 14 scroll fix
* [files_texteditor#111](https://github.com/nextcloud/files_texteditor/pull/111) Update stable14 target versions
* [firstrunwizard#80](https://github.com/nextcloud/firstrunwizard/pull/80) Update stable14 target versions
* [gallery#467](https://github.com/nextcloud/gallery/pull/467) Update stable14 target versions
* [nextcloud_announcements#32](https://github.com/nextcloud/nextcloud_announcements/pull/32) Update stable14 target versions
* [notifications#158](https://github.com/nextcloud/notifications/pull/158) Update stable14 target versions
* [notifications#161](https://github.com/nextcloud/notifications/pull/161) [stable14] Update config and babel for ie11

### CODE REVIEW

**Comment by danielkesselberg** [comment]
Any change to get https://github.com/nextcloud/server/pull/11091 in? It fixes a confusing message for some users.

**Comment by blizzz** [comment]
> Any change to get #11091 in? It fixes a confusing message for some users.

Makes sense, it's essentially ready. Can you prepare a backport for the stable14  branch?

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
created the backport, iirc needs two reviewers until this evening. updated desc.

**Comment by skjnldsv** [comment]
Added [stable14] Fix icons cacher regex for compressed output #11291

**Pull request merged**
