### PR TITLE
Do not setup the default FS on normal routes

### PR DESCRIPTION
**Pull request by rullzer**
This should help with load times hopefully. Only initialize the FS if we
actually ned it.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I would expect it to cause more issues on the endpoints that use the non-node base API, right? Also the getstoragestats endpoint seem to fail:

```json
{"Exception":"Exception","Message":"Call to a member function getFileInfo() on null","Code":0,"Trace":[{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Route\/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\AjaxController","getStorageStats",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"files.ajax.getStorageStats"}]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/ajax\/getstoragestats.php"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","Line":159,"Previous":{"Exception":"Error","Message":"Call to a member function getFileInfo() on null","Code":0,"Trace":[{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/legacy\/OC_Helper.php","line":488,"function":"getFileInfo","class":"OC\\Files\\Filesystem","type":"::","args":["\/",false]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/apps\/files\/lib\/Helper.php","line":51,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/apps\/files\/lib\/Controller\/AjaxController.php","line":47,"function":"buildFileStorageStatistics","class":"OCA\\Files\\Helper","type":"::","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":218,"function":"getStorageStats","class":"OCA\\Files\\Controller\\AjaxController","type":"->","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Route\/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\AjaxController","getStorageStats",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"files.ajax.getStorageStats"}]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/ajax\/getstoragestats.php"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Files\/Filesystem.php","Line":864},"CustomMessage":"--"} 
```

**Comment by rullzer** [comment]
> I would expect it to cause more issues on the endpoints that use the non-node base API, right? Also the getstoragestats endpoint seem to fail:
> 
> ```json
> {"Exception":"Exception","Message":"Call to a member function getFileInfo() on null","Code":0,"Trace":[{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Route\/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\AjaxController","getStorageStats",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"files.ajax.getStorageStats"}]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/ajax\/getstoragestats.php"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","Line":159,"Previous":{"Exception":"Error","Message":"Call to a member function getFileInfo() on null","Code":0,"Trace":[{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/legacy\/OC_Helper.php","line":488,"function":"getFileInfo","class":"OC\\Files\\Filesystem","type":"::","args":["\/",false]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/apps\/files\/lib\/Helper.php","line":51,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/apps\/files\/lib\/Controller\/AjaxController.php","line":47,"function":"buildFileStorageStatistics","class":"OCA\\Files\\Helper","type":"::","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":218,"function":"getStorageStats","class":"OCA\\Files\\Controller\\AjaxController","type":"->","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Route\/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\AjaxController","getStorageStats",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"files.ajax.getStorageStats"}]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/ajax\/getstoragestats.php"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Files\/Filesystem.php","Line":864},"CustomMessage":"--"} 
> ```

Yes we should fix that.
And yes endpoints that do not use the node API will have to call that themselves indeed.

But the issue here is that at some point we need to make a switch. Else we keep setting up the storage on those routes untill the end of days. The main issue is that it happens so early so we can't even have routes opt out or in via an annotation.

**Comment by MorrisJobke** [comment]
> Yes we should fix that.
> And yes endpoints that do not use the node API will have to call that themselves indeed.
> 
> But the issue here is that at some point we need to make a switch. Else we keep setting up the storage on those routes untill the end of days. The main issue is that it happens so early so we can't even have routes opt out or in via an annotation.

Full ack. We just should fix our endpoints then also in this PR here.

**Review by skjnldsv — APPROVED** [review]
:elephant:

**Comment by rullzer** [comment]
> I would expect it to cause more issues on the endpoints that use the non-node base API, right? Also the getstoragestats endpoint seem to fail:
> 
> ```json
> {"Exception":"Exception","Message":"Call to a member function getFileInfo() on null","Code":0,"Trace":[{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Route\/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\AjaxController","getStorageStats",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"files.ajax.getStorageStats"}]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/ajax\/getstoragestats.php"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","Line":159,"Previous":{"Exception":"Error","Message":"Call to a member function getFileInfo() on null","Code":0,"Trace":[{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/legacy\/OC_Helper.php","line":488,"function":"getFileInfo","class":"OC\\Files\\Filesystem","type":"::","args":["\/",false]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/apps\/files\/lib\/Helper.php","line":51,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/apps\/files\/lib\/Controller\/AjaxController.php","line":47,"function":"buildFileStorageStatistics","class":"OCA\\Files\\Helper","type":"::","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":218,"function":"getStorageStats","class":"OCA\\Files\\Controller\\AjaxController","type":"->","args":["\/"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/AppFramework\/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Route\/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\AjaxController","getStorageStats",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"files.ajax.getStorageStats"}]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/ajax\/getstoragestats.php"]},{"file":"\/Users\/morris\/Projects\/nextcloud\/server\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/Users\/morris\/Projects\/nextcloud\/server\/lib\/private\/Files\/Filesystem.php","Line":864},"CustomMessage":"--"} 
> ```

Fixed that

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
> But the issue here is that at some point we need to make a switch. Else we keep setting up the storage on those routes untill the end of days. The main issue is that it happens so early so we can't even have routes opt out or in via an annotation.

I added it to #23210 for visibility.

**Comment by skjnldsv** [comment]
I think it broke `integration-comments-search`

**Comment by skjnldsv** [comment]
```json
{
  "Exception": "Exception",
  "Message": "Call to a member function search() on null",
  "Code": 0,
  "Trace": [
    {
      "file": "/drone/src/lib/private/AppFramework/App.php",
      "line": 157,
      "function": "dispatch",
      "class": "OC\\AppFramework\\Http\\Dispatcher",
      "type": "->",
      "args": [
        {
          "__class__": "OC\\Core\\Controller\\SearchController"
        },
        "search"
      ]
    },
    {
      "file": "/drone/src/lib/private/Route/Router.php",
      "line": 309,
      "function": "main",
      "class": "OC\\AppFramework\\App",
      "type": "::",
      "args": [
        "OC\\Core\\Controller\\SearchController",
        "search",
        {
          "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
        },
        {
          "action": null,
          "_route": "core.Search.search"
        }
      ]
    },
    {
      "file": "/drone/src/lib/base.php",
      "line": 1009,
      "function": "match",
      "class": "OC\\Route\\Router",
      "type": "->",
      "args": [
        "/core/search"
      ]
    },
    {
      "file": "/drone/src/index.php",
      "line": 37,
      "function": "handleRequest",
      "class": "OC",
      "type": "::",
      "args": []
    }
  ],
  "File": "/drone/src/lib/private/AppFramework/Http/Dispatcher.php",
  "Line": 159,
  "Previous": {
    "Exception": "Error",
    "Message": "Call to a member function search() on null",
    "Code": 0,
    "Trace": [
      {
        "file": "/drone/src/lib/private/Search/Provider/File.php",
        "line": 47,
        "function": "search",
        "class": "OC\\Files\\Filesystem",
        "type": "::",
        "args": [
          "first"
        ]
      },
      {
        "file": "/drone/src/lib/private/Search.php",
        "line": 61,
        "function": "search",
        "class": "OC\\Search\\Provider\\File",
        "type": "->",
        "args": [
          "first"
        ]
      },
      {
        "file": "/drone/src/core/Controller/SearchController.php",
        "line": 60,
        "function": "searchPaged",
        "class": "OC\\Search",
        "type": "->",
        "args": [
          "first",
          [
            "files"
          ],
          1,
          30
        ]
      },
      {
        "file": "/drone/src/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 218,
        "function": "search",
        "class": "OC\\Core\\Controller\\SearchController",
        "type": "->",
        "args": [
          "first",
          [
            "files"
          ],
          1,
          30
        ]
      },
      {
        "file": "/drone/src/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 127,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Core\\Controller\\SearchController"
          },
          "search"
        ]
      },
      {
        "file": "/drone/src/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Core\\Controller\\SearchController"
          },
          "search"
        ]
      },
      {
        "file": "/drone/src/lib/private/Route/Router.php",
        "line": 309,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OC\\Core\\Controller\\SearchController",
          "search",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "action": null,
            "_route": "core.Search.search"
          }
        ]
      },
      {
        "file": "/drone/src/lib/base.php",
        "line": 1009,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/core/search"
        ]
      },
      {
        "file": "/drone/src/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/drone/src/lib/private/Files/Filesystem.php",
    "Line": 763
  },
  "CustomMessage": "--"
}
```

**Comment by rullzer** [comment]
> ```json
> {
>   "Exception": "Exception",
>   "Message": "Call to a member function search() on null",
>   "Code": 0,
>   "Trace": [
>     {
>       "file": "/drone/src/lib/private/AppFramework/App.php",
>       "line": 157,
>       "function": "dispatch",
>       "class": "OC\\AppFramework\\Http\\Dispatcher",
>       "type": "->",
>       "args": [
>         {
>           "__class__": "OC\\Core\\Controller\\SearchController"
>         },
>         "search"
>       ]
>     },
>     {
>       "file": "/drone/src/lib/private/Route/Router.php",
>       "line": 309,
>       "function": "main",
>       "class": "OC\\AppFramework\\App",
>       "type": "::",
>       "args": [
>         "OC\\Core\\Controller\\SearchController",
>         "search",
>         {
>           "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
>         },
>         {
>           "action": null,
>           "_route": "core.Search.search"
>         }
>       ]
>     },
>     {
>       "file": "/drone/src/lib/base.php",
>       "line": 1009,
>       "function": "match",
>       "class": "OC\\Route\\Router",
>       "type": "->",
>       "args": [
>         "/core/search"
>       ]
>     },
>     {
>       "file": "/drone/src/index.php",
>       "line": 37,
>       "function": "handleRequest",
>       "class": "OC",
>       "type": "::",
>       "args": []
>     }
>   ],
>   "File": "/drone/src/lib/private/AppFramework/Http/Dispatcher.php",
>   "Line": 159,
>   "Previous": {
>     "Exception": "Error",
>     "Message": "Call to a member function search() on null",
>     "Code": 0,
>     "Trace": [
>       {
>         "file": "/drone/src/lib/private/Search/Provider/File.php",
>         "line": 47,
>         "function": "search",
>         "class": "OC\\Files\\Filesystem",
>         "type": "::",
>         "args": [
>           "first"
>         ]
>       },
>       {
>         "file": "/drone/src/lib/private/Search.php",
>         "line": 61,
>         "function": "search",
>         "class": "OC\\Search\\Provider\\File",
>         "type": "->",
>         "args": [
>           "first"
>         ]
>       },
>       {
>         "file": "/drone/src/core/Controller/SearchController.php",
>         "line": 60,
>         "function": "searchPaged",
>         "class": "OC\\Search",
>         "type": "->",
>         "args": [
>           "first",
>           [
>             "files"
>           ],
>           1,
>           30
>         ]
>       },
>       {
>         "file": "/drone/src/lib/private/AppFramework/Http/Dispatcher.php",
>         "line": 218,
>         "function": "search",
>         "class": "OC\\Core\\Controller\\SearchController",
>         "type": "->",
>         "args": [
>           "first",
>           [
>             "files"
>           ],
>           1,
>           30
>         ]
>       },
>       {
>         "file": "/drone/src/lib/private/AppFramework/Http/Dispatcher.php",
>         "line": 127,
>         "function": "executeController",
>         "class": "OC\\AppFramework\\Http\\Dispatcher",
>         "type": "->",
>         "args": [
>           {
>             "__class__": "OC\\Core\\Controller\\SearchController"
>           },
>           "search"
>         ]
>       },
>       {
>         "file": "/drone/src/lib/private/AppFramework/App.php",
>         "line": 157,
>         "function": "dispatch",
>         "class": "OC\\AppFramework\\Http\\Dispatcher",
>         "type": "->",
>         "args": [
>           {
>             "__class__": "OC\\Core\\Controller\\SearchController"
>           },
>           "search"
>         ]
>       },
>       {
>         "file": "/drone/src/lib/private/Route/Router.php",
>         "line": 309,
>         "function": "main",
>         "class": "OC\\AppFramework\\App",
>         "type": "::",
>         "args": [
>           "OC\\Core\\Controller\\SearchController",
>           "search",
>           {
>             "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
>           },
>           {
>             "action": null,
>             "_route": "core.Search.search"
>           }
>         ]
>       },
>       {
>         "file": "/drone/src/lib/base.php",
>         "line": 1009,
>         "function": "match",
>         "class": "OC\\Route\\Router",
>         "type": "->",
>         "args": [
>           "/core/search"
>         ]
>       },
>       {
>         "file": "/drone/src/index.php",
>         "line": 37,
>         "function": "handleRequest",
>         "class": "OC",
>         "type": "::",
>         "args": []
>       }
>     ],
>     "File": "/drone/src/lib/private/Files/Filesystem.php",
>     "Line": 763
>   },
>   "CustomMessage": "--"
> }
> ```

could be let me check

**Pull request merged**
