### PR TITLE
Remove internal tag routes

### PR DESCRIPTION
**Pull request by rullzer**
As far as I can tell this is not used at all by any of our internal stuff. It is basically the predecesor of the systemtags as I understand it but is never used.

Any objections? @MorrisJobke @nickvergessen @icewind1991 @schiessle @blizzz @LukasReschke

### CODE REVIEW

**Comment by rullzer** [comment]
If it is used we should move it to a real (tested) controller. But I could find no such things.

**Comment by nickvergessen** [comment]
Those are the favorite icon tags?

**Comment by rullzer** [comment]
No that is done via a route in the files app

**Comment by nickvergessen** [comment]
No, those are the routes, to manually control those tags (like file favorites). It maybe that we don't use them, but any app could use those personal tags. So not sure if we should delete it.

I'd vote for moving to a normal controller.

**Comment by rullzer** [comment]
> I'd vote for moving to a normal controller.

Fair enough. Should not be to hard.

On a side note we need to think how we define 'internal' routes. So stuff that might change at any given time.

**Comment by nickvergessen** [comment]
> On a side note we need to think how we define 'internal' routes. So stuff that might change at any given time.

Anything that is not OCS is internal as far as i know :wink:

**Comment by rullzer** [comment]
Well then other apps should not use it as well ;)

**Comment by MorrisJobke** [comment]
> Well then other apps should not use it as well ;)

Correct.

**Comment by rullzer** [comment]
I moved it over to a real Controller in #958 
But lets deprecate the routes and remove them in NC12 or so?

**Pull request closed without merging**
