### PR TITLE
Remove unused, deprecated icons

### PR DESCRIPTION
**Pull request by pixelipo**
As discussed in the SVG re-optimization tasks, several icons seem to be unused:

- core/img/actions/pause-big.svg
- core/img/actions/play-big.svg
- core/img/actions/user-plus.svg
- core/img/actions/user-times.svg

Does anyone know if these are used in an app? Last two don't even have a CSS class that calls them in `core`. @nextcloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> core/img/actions/play-big.svg

Not used in any app of the appstore.



> core/img/actions/pause-big.svg

Not used in any app of the appstore.




> core/img/actions/user-plus.svg
> core/img/actions/user-times.svg

Those two are also not used in any app of the appstore.

**Review by MorrisJobke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
I mean, as far as I knew the play/pause big is used in the Gallery app for the details view / slideshow in the bottom right, but I'll check. (In any case  we could use the normal icons and enlarge then.)

**Comment by pixelipo** [comment]
@jancborchardt I think Gallery is using `icon-view-play`, which is still there (but I'm working on a PR for gallery to deprecate it as well)

**Comment by jancborchardt** [comment]
@pixelipo ah of course, yes. The big play icon was only used in the old Music app then, so good on removing. :)

**Pull request merged**
