### PR TITLE
Fix database configuration

### PR DESCRIPTION
**Pull request by nickvergessen**
* commit 1 actual fix
* commit 2 spaces vs. tabs

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Makes more sense - also it should not work before that or do I miss something? 🧐

**Comment by nickvergessen** [comment]
> also it should not work before that or do I miss something? 

yeah, thats also my understanding

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Comment by MorrisJobke** [comment]
The integration errors are fixed by #14529 and #14519

**Pull request merged**
