### PR TITLE
fix(settings): stop reloading after force-enabling an app

### PR DESCRIPTION
**Pull request by skjnldsv**
## Steps
1. have an incompatible app
2. Click `Allow untested app`
3. The page reloads

## Fixed:
The page does NOT reload anymore

https://github.com/nextcloud/server/assets/14975046/7624798d-956c-422f-9a7d-bfb878788f36

### CODE REVIEW

**Review by artonge — APPROVED** [review]
:rofl: Not sure why, but this makes me laugh

**Comment by skjnldsv** [comment]
> 🤣 Not sure why, but this makes me laugh

It's the little things™ :sparkles: :sparkles: :sparkles:  :see_no_evil:

**Review by szaimen — APPROVED** [review]
Tested and seems to work.

Maybe the idea of a reload was that a potential icon is directly shown in the header which it might not be now?

**Comment by skjnldsv** [comment]
> Maybe the idea of a reload was that a potential icon is directly shown in the header which it might not be now?

That's what happens when you enable an app, not force-enable :)

**Pull request merged**
