### PR TITLE
Use shared Babel.js configuration

### PR DESCRIPTION
**Pull request by francoisfreitag**
Keep in sync with other repositories by using the centralized
configuration for Babel.js.

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by francoisfreitag** [comment]
I regenerated the JS and source map files after the config change, hopefully that’ll make the Node build green.

**Comment by francoisfreitag** [comment]
Figured it out, I had `make watch-js` running in another tab :facepalm:.

**Comment by francoisfreitag** [comment]
I do not understand what is going on yet, but it is due to the switch from `modules: false` to `modules: 'commonjs'`.
I can reproduce the failure locally, will get more familiar with the karma test setup and hopefully report back within a few days.

**Comment by francoisfreitag** [comment]
Changing the config is a large change.

Previously, because module was `false`, the “compiled” JavaScript could execute directly in the global context. When `modules` is set to `'commonjs'`, the scripts are limited to their own module. The globals should likely be registered through the [`ProvidePlugin`](https://webpack.js.org/plugins/provide-plugin/).
I’ll investigate how large of a change that is and report back.

**Comment by skjnldsv** [comment]
> I do not understand what is going on yet, but it is due to the switch from `modules: false` to `modules: 'commonjs'`.
> I can reproduce the failure locally, will get more familiar with the karma test setup and hopefully report back within a few days.

Ah, yes, unfortunately our test suite might not be compatible with our babel config. It's not a trivial change.
I started addressing this in #23973, but it's a mess.

**Pull request closed without merging**
