### PR TITLE
Update mimetypes

### PR DESCRIPTION
**Pull request by rullzer**
replaces https://github.com/nextcloud/server/pull/857

Thanks @FortressBuilder.
- Added mobi mimetype => text
- ran the mimetype update part

CC: @MorrisJobke @nickvergessen @icewind1991

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by rullzer** [comment]
@FortressBuilder yes no issues since the texteditor is smart enough to only open 'real' text files ;)

**Comment by rullzer** [comment]
@FortressBuilder can I count your somment as a review and thus a :+1: ?

**Comment by mar1u5** [comment]
👍

**Comment by mar1u5** [comment]
should we port that to `stable10` .. I think this would not cause any bugs, so i think should be fine. @karlitschek

**Comment by karlitschek** [comment]
please backport 👍

**Comment by mar1u5** [comment]
Backport is in #973 💪

**Pull request merged**
