### PR TITLE
[stable10] Allow the config dir to be specified via the enviroment

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #660 to make @jospoortvliet happy.

### CODE REVIEW

**Comment by nickvergessen** [comment]
@gdamjan @kyrofa feel free to review this.

@karlitschek for backport approval (requested by the snappy guys so they dont have to patch it after each update again)

**Comment by karlitschek** [comment]
nice feature. please backport

**Comment by gdamjan** [comment]
looks good to me

**Comment by LukasReschke** [comment]
LGTM

**Comment by jospoortvliet** [comment]
Thanks all! Love and hugs ;-)

**Comment by Mehlstaub** [comment]
Having a problem with this. If there is no config.php in webroot/config/ folder the occ commands seem to be broken.

I've tried to put the config.php only in /etc/nextcloud

System itself works fine but occ commands return these errors

```
sudo -u www-data php occ maintenance:mode --on
Nextcloud is not installed - only a limited number of commands are available


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "maintenance:mode" is not defined.
  Did you mean this?
      maintenance:install
```

**Comment by gdamjan** [comment]
if you use this feature for the server, you need to define the envrinment variable in your shell too, before calling occ.

one example , with sudo is:
`sudo -u www-data NEXTCLOUD_CONFIG_DIR=/etc/nextcloud  php occ maintenance:mode --on`

**Comment by Mehlstaub** [comment]
@gdamjan thanks i missed that, works now

**Pull request merged**
