### PR TITLE
Dont show menu automatically when share link is clicked

### PR DESCRIPTION
**Pull request by GretaD**
ref #16076 

> Share link should not open menu automatically

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]

**Comment by juliushaertl** [comment]
If we do it, acceptance tests will need to be adjusted :wink:

**Comment by jancborchardt** [comment]
Yeah, but this came up in the polishing session, and opening the menu every time is quite annoying.

We could still add an enhancement that opens the menu only once per user. But we definitely should merge this here as papercut.

**Comment by georgehrke** [comment]
@juliushaertl Can you give @GretaD some hints about the integration tests? :)

**Comment by juliushaertl** [comment]
@GretaD For running them locally have a look at the run script https://github.com/nextcloud/server/blob/master/tests/acceptance/run.sh#L20 which also has some nice writeup by @danxuliu Note that it will require you to have docker setup on your local system.

Those tests are probably the ones that need adjustments:
https://github.com/nextcloud/server/blob/09683430614ca873d5cba831a8a06f296a71c897/tests/acceptance/features/app-files-sharing-link.feature#L11
https://github.com/nextcloud/server/blob/09683430614ca873d5cba831a8a06f296a71c897/tests/acceptance/features/app-files-sharing-link.feature#L37

**Comment by danxuliu** [comment]
Rebased and fixed up

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Pull request merged**
