### PR TITLE
chore(CI): Improve rate limit situation when installing phpunit

### PR DESCRIPTION
**Pull request by nickvergessen**
* Ref https://github.com/shivammathur/setup-php/issues/679#issuecomment-1363380571
* Before sample execution: https://github.com/nextcloud/server/actions/runs/3829199066/jobs/6515628919

### CODE REVIEW

**Review by szaimen — COMMENTED** [review]
Should we also do this in our .github repo?

**Review by come-nc — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Should we also do this in our .github repo?

Yes, first wanted to confirm it's working here.

**Review by szaimen — APPROVED** [review]
okay

**Pull request merged**
