### PR TITLE
Fix popover and styling in user management

### PR DESCRIPTION
**Pull request by juliusknorr**
- Fix popover positioning 
- Always show the 3-dots icon
- Remove margin between new user form and table

Before:
bildschirmfoto vom 2018-01-11 12-15-39

After:
bildschirmfoto vom 2018-01-11 12-15-15

@nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
Popover fix already included in the new user menu pr I did! :)

**Comment by MorrisJobke** [comment]
> Popover fix already included in the new user menu pr I did! :)

But it will not go into Nextcloud 13 ;)

**Comment by skjnldsv** [comment]
> But it will not go into Nextcloud 13 ;)

:'(

**Review by MariusBluem — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
