### PR TITLE
fix(files): Focus filename input in new-node dialog when opened

### LINKED ISSUE #43659: [Bug]: New file name modal does not always set focus
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As a Nextcloud user enjoying https://github.com/nextcloud/server/pull/42993 I noticed that *sometimes* I can use my keyboard to change the default file name, other times there is no focus and I have to click into the input first.

Bildschirmfoto vom 2024-02-19 15-46-27

(hard to screenshot but there is no cursor inside the input)

### Steps to reproduce

1. Open Files
2. Click *+ New*
3. Click *New text file*

### Expected behavior

Focus of the filename input is always set.

Nit: set it to the last character before the file extension, or set the focus to the filename without extension, like 
image. That's how Nautilus does it, for example.

Bildschirmfoto vom 2024-02-19 15-51-22

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

Tested on FF for Linux.

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/43659

## Summary
Always focus the filename input when the dialog is opened

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Makes sense :pray:

**Review by szaimen — APPROVED** [review]
Tested and seems to work :)

**Comment by kesselb** [comment]
Thank you :+1:

**Pull request merged**
