### PR TITLE
enh(appconfig): only try to insert new value if in doubt

### PR DESCRIPTION
**Pull request by ArtificialOwl**
we filter out existing config values from trying to insert a new row but directly update it

### CODE REVIEW

**Comment by susnux** [comment]
@ArtificialOwl tests conflict

**Comment by ArtificialOwl** [comment]
_note to myself: do not use gh webtools to manage conflicts ..._

**Review by artonge — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]
LGTM!

**Comment by skjnldsv** [comment]
conflicts

**Pull request merged**
