### PR TITLE
allow use of rememberme cookies for IApacheAuth backends

### LINKED ISSUE #609: `remember_login` cookie is not created
### Steps to reproduce
1. keep the Nextcloud user backend activated alongside with the SAML one
2. Log in with SAML and close your tab
3. Wait around two hours
4. Go to Nextcloud

### Expected behaviour
I should be already logged in and should not have to select the backend neither to send an IdP request

### Actual behaviour
I need to select the user backend and to log in again

Keeping the Nextcloud user backend activated is necessary to see the behavior because with SAML only I guess that an IdP request is sent automatically, and therefor the "remember me" behavior seems to work although it doesn't.

FYI, user_odic creates a Remember me token : 
- https://github.com/nextcloud/user_oidc/pull/425

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "brume.felinn.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.4.1",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "\/etc\/nextcloud\/skeleton",
        "maintenance": false,
        "theme": "",
        "loglevel": 3,
        "updater.release.channel": "stable"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - apporder: 0.15.0
  - audioplayer: 3.3.0
  - bookmarks: 10.3.1
  - calendar: 3.2.2
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - dav: 1.21.0
  - event_update_notification: 1.5.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - groupfolders: 11.1.2
  - integration_gitlab: 1.0.3
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - richdocuments: 5.0.3
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - side_menu: 2.3.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_saml: 5.0.0
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - announcementcenter: 6.1.1
  - breezedark: 23.2.1
  - bruteforcesettings: 2.4.0
  - circles: 0.21.4
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - deck: 1.6.1
  - encryption
  - end_to_end_encryption: 1.9.1
  - federation: 1.10.1
  - files_external
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.9.0
  - recommendations: 0.8.0
  - spreed: 13.0.5
  - systemtags: 1.10.0
  - user_ldap
  - user_status: 1.0.0
  - weather_status: 1.0.0
```

### PR DESCRIPTION
**Pull request by blizzz**
- e.g. enables it for SAML backend. Fixes https://github.com/nextcloud/user_saml/issues/609

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by Ornanovitch** [comment]
Works well with NC24: know I get the three missing cookies with user_saml (`nc_session_id`, `nc_token` and `nc_username`), and they all expire in 15 days so everything seems find! Thanks a lot :+1:

**Review by juliusknorr — APPROVED** [review]
Tested and works also with manually deleting the session from the php save path.

**Pull request merged**
