### PR TITLE
fix filename input

### LINKED ISSUE #33801: rename box overlaps with the thumbnail
From https://github.com/nextcloud/server/pull/33568#issuecomment-1232662966

image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/33801

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
