### PR TITLE
delay creation of the cert bundle

### LINKED ISSUE #18148: certification bundle is created before user fs is setup properly
1. Have user folders that are non-default, for instance per SAML or LDAP
2. Trigger the file system being setup (at least requiring an external storage from file_sharing being setup)
2. The DAV Storage initialization requests the certification bundle path in its constructor (https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/DAV.php#L118-L121). This happens within initMounPoints for the logged in user and write the file to the wrong location (the path as according to the mount, not the real one).

introduced with https://github.com/owncloud/core/pull/25274

### PR DESCRIPTION
**Pull request by blizzz**
fixes #18148

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Failing CI

**Comment by blizzz** [comment]
was dependent on the $secure property. combined it with some logic further on, looks good now

**Comment by blizzz** [comment]
i take care of backports this week

**Pull request merged**
