### PR TITLE
Dispatch event for all removed entries

### PR DESCRIPTION
**Pull request by artonge**
When removing a folder, dispatch the event for all the deleted entries and not only for the folder.

Does it make sense, or was the old behavior on purpose ?

### CODE REVIEW

**Comment by juliushaertl** [comment]
Sounds like something we should have, I'd just be cautious about possible performance impact on large folder deletion. Did you attempt to fix a specific case with this?

**Comment by artonge** [comment]
> Sounds like something we should have, I'd just be cautious about possible performance impact on large folder deletion. Did you attempt to fix a specific case with this?

Performance wise, I think that the change simply move the iteration work from the listener to the dispatcher. Meaning, when a folder is deleted, instead of having to look for children in every listener, we do it once on the dispatcher side.

So we are comparing the load of emitting more events to the load of listing directories multiple times.

I think it also makes more sense regarding the naming of the event. If you listen to `CacheEntryRemovedEvent` you expect to receive the event for every entry, no ? So without this change, you miss on a lot of entry deletion.

I have one case on photos, where I want to delete file entry from albums when they are deleted:
https://github.com/nextcloud/photos/blob/f034ce6517b0c523dacce17d976da0945c5cdb7e/lib/Listener/CacheEntryRemovedListener.php

And this PR that improves how we manage metadata with events:
https://github.com/nextcloud/server/pull/34586

**Comment by artonge** [comment]
Ping :)

**Comment by PVince81** [comment]
I'd like to know what @icewind1991 thinks

I vaguely remember that some events are purposefully only triggered on the container and not on all children, for performance reasons

**Comment by juliushaertl** [comment]
🏓 @icewind1991 for some input

**Review by icewind1991 — APPROVED** [review]

**Comment by icewind1991** [comment]
Not the best in case of performance but probably better than the alternatives that can be done easily

**Review by come-nc — APPROVED** [review]

**Comment by marcelklehr** [comment]
This is kinda a breaking change. Should be added here: https://github.com/nextcloud/server/issues/37039

**Pull request merged**
