### PR TITLE
This fix the overlay of the complexity bar

### PR DESCRIPTION
**Pull request by ArtificialOwl**
Signed-off-by: Maxence Lange <maxence@nextcloud.com>

### CODE REVIEW

**Comment by daita** [comment]
selection_058

**Comment by daita** [comment]
backport: #5889

**Review by schiessle — APPROVED** [review]
Works!

**Comment by schiessle** [comment]
Will also fix https://github.com/nextcloud/server/issues/4839

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
