### PR TITLE
Use proper authorative-autoloader for app autoloaders

### PR DESCRIPTION
**Pull request by rullzer**
Because I'm an idiot I used some non existing keyword to try to set an authoritative classmap.

I noticed we were spending an insane amount of time in findFileWithExtention. This should make that a lot better.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Is the classmap also dumped for those apps? 🤔

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍 
bildschirmfoto 2017-12-14 um 09 23 52

**Comment by MorrisJobke** [comment]
> Is the classmap also dumped for those apps? 🤔

Just checked and yes it is 😉

**Comment by skjnldsv** [comment]
I'll get the whip!!! 😠

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
