### PR TITLE
Remove notify recipient function

### PR DESCRIPTION
**Pull request by rullzer**
This functionality is not needed as recipients can decide themselfs if they want to get a notification.

CC: @schiessle @nickvergessen @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
Delete all the code 👍

**Comment by LukasReschke** [comment]
LGTM

**Comment by nickvergessen** [comment]
Should we also delete such configs with a repairstep?
Otherwise if someone by accident reuses the same config name one day, it may have unintended default values on some instances.

**Comment by rullzer** [comment]
@nickvergessen fair enough. I'll take of that later today.

**Comment by MorrisJobke** [comment]
> @nickvergessen fair enough. I'll take of that later today.

@rullzer Is this already done?

**Comment by nickvergessen** [comment]
It's done in https://github.com/nextcloud/server/pull/1978

**Comment by rullzer** [comment]
See the problem solves itself :)

**Pull request merged**
