### PR TITLE
Workflow cleanup

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref #735

### CODE REVIEW

**Comment by schiessle** [comment]
looks good to me :+1: 

second reviewer... @MorrisJobke or @LukasReschke maybe?

**Comment by LukasReschke** [comment]
LGTM

**Comment by LukasReschke** [comment]
Does this require a backport?

**Comment by schiessle** [comment]
yes, I will prepare it

**Comment by schiessle** [comment]
backport: https://github.com/nextcloud/server/pull/776

**Pull request merged**
