### PR TITLE
Animated log in logo

### PR DESCRIPTION
**Pull request by jancborchardt**
Extracted from https://github.com/nextcloud/server/pull/6507 since the background-animation impacts performance way too much for now.

cc @nextcloud/designers @MorrisJobke @karlitschek 

Two things we need to fix still:
- [ ] Make sure the right parts are activated/deactivated when the logo is themed – see the code comments @juliushaertl 
- [ ] The logo-sprite should have higher resolution so it looks nice on retina displays. Roughly so the logo would be 512px width/height. Can you export that @Espina2, or is there a source file for the animation?

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Espina2 cool, thanks! :)

**Comment by karlitschek** [comment]
👍

**Comment by Espina2** [comment]
@jancborchardt 
Re-rendered sequence. You have to do the sprite for yourself. The render is blue, but you just need to fill the content with white.

If any doubt let me know.
[sequence.zip](https://github.com/nextcloud/server/files/1445922/sequence.zip)

**Comment by MorrisJobke** [comment]
I rebased this to fix the conflicts. Sadly the resolution is too low:

bildschirmfoto 2018-03-07 um 23 27 30



> If any doubt let me know.
> sequence.zip

@Espina2 Could you provide a file similar to https://github.com/nextcloud/server/blob/8dd73a0fd6dd3b89ad12e02edbc4a186448ab0e6/core/img/logo-sprite.png (basically all in one sprite) and also not the blue logo, but a white logo on transparent background.

Thanks 👍

**Comment by MorrisJobke** [comment]
@espina2 could you please remove the „Nextcloud“ below the logo and then it should be good:+1:

**Comment by skjnldsv** [comment]
Also, if it could be one line, it would actually simplify our css a lot :p 
(prettyplease :pray: )

**Comment by jancborchardt** [comment]
@Espina2 is it maybe also possible to export it as SVG animation? Might be less in size, and better for HiDPi displays?

**Comment by Espina2** [comment]
@jancborchardt I can export to SVG if you use the bodymoving plugin (I saw the right now is called lottie https://github.com/airbnb/lottie-web), but I think this will be an overkill for this case only.

@skjnldsv the css is the same, you just need to specify the the x,y background position instead of only one. ;)

@MorrisJobke I will try to find the source file and rerender again without the nextcloud name.

**Comment by skjnldsv** [comment]
> @skjnldsv the css is the same, you just need to specify the the x,y background position instead of only one. ;)

I'm a lazy slug :D

**Comment by rullzer** [comment]
What is the status here?

Can we get this is soon?

**Comment by juliushaertl** [comment]
We need the logo sprite without the Nextcloud text to finish this. @Espina2 Do you have some time to render it again?

**Comment by MorrisJobke** [comment]
Nothing for 14 it seems -> moved to 15

**Comment by AnonymousPolarbearFan** [comment]
This looks really good.

**Comment by MorrisJobke** [comment]
As we are missing a high-dpi resource of the animation I will close this for now. As discussed with @jancborchardt

**Pull request closed without merging**
