### PR TITLE
revert to old setup connection logic

### PR DESCRIPTION
**Pull request by icewind1991**
mostly reverts 8a79d314cf544cf2ca261cbac7ea07570e9ed8e5

@blizzz can you check if this fixes setup for you

### CODE REVIEW

**Comment by blizzz** [comment]
@icewind1991 yes, this fixes it! Thanks :bouquet: 

LGTM

**Comment by blizzz** [comment]
requires backport to stable10 @karlitschek 

please review @MorrisJobke @Faldon

**Comment by karlitschek** [comment]
please backport

**Comment by Faldon** [comment]
Works good for me.

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
