### PR TITLE
Dashboard polishing

### PR DESCRIPTION
**Pull request by juliusknorr**
- Add loading indicator until widgets are mounted
- Add class to handle styling when body has been scrolled

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Added the fade below navigation when scrolled, rebased → good to go from my view. :)

**Comment by jancborchardt** [comment]
Added another fix for Safari background blur since the -webkit prefix is needed as per https://caniuse.com/#search=backdrop-filter
Also removed one level of indent from the CSS so it’s proper/easier to write.

**Comment by nickvergessen** [comment]
> Node / build (12.x) (pull_request) 

Forgot to build after that @jancborchardt ?

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
