### PR TITLE
Do not trigger a full filelist reload after creating a new file from a template

### PR DESCRIPTION
**Pull request by juliusknorr**
Instead of reloading the full file list after creating a file from a template this will now just fetch the single file info and add it to the existing file list. This makes sure we can also provide the regular context parameters when calling the file action.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
Nice!

**Comment by rullzer** [comment]
php-cs is not happy..

**Comment by juliushaertl** [comment]
Rebased

**Review by rullzer — APPROVED** [review]

**Pull request merged**
