### PR TITLE
Do not convert email addresses with idn_to_ascii if…

### PR DESCRIPTION
**Pull request by JaredBoone**
… INTL_IDNA_VARIANT_UTS46 is undefined.

Fixes https://github.com/nextcloud/server/issues/8387.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by JaredBoone** [comment]
I pushed a commit log rewrite to add my sign-off

**Comment by rullzer** [comment]
@JaredBoone thanks!

Could you also open a PR against master for this?

**Comment by JaredBoone** [comment]
@rullzer Sure. Here's the PR against master: https://github.com/nextcloud/server/pull/9100.

**Review by blizzz — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Retriggered CI: https://drone.nextcloud.com/nextcloud/server/6354

**Comment by MorrisJobke** [comment]
Somehow drone reported the wrong status here - this is the correct one and it is green: https://drone.nextcloud.com/nextcloud/server/6339

**Pull request merged**
