### PR TITLE
[stable10] Add repair step and revert "Open updater" button

### PR DESCRIPTION
**Pull request by MorrisJobke**
- stable10 backport of #1499
- fixes both items in #1485
- repair step moves the update step file `data/updater-INSTANCEID/.step` to a file named `.step-previous-update` to not show all steps as done on the next update
- reverts  202ae42

cc @LukasReschke @nickvergessen @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
👍

**Comment by nickvergessen** [comment]
👍 worked

**Comment by MorrisJobke** [comment]
I added the wrongly removed tests here (see comment in master PR).

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
