### PR TITLE
Properly log the full exception instead of only the message

### PR DESCRIPTION
**Pull request by MorrisJobke**
Cleans up all the occurrences where we missed the full stack trace.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:rocket: :elephant:

**Review by icewind1991 — APPROVED** [review]

**Comment by rullzer** [comment]
failing CI

**Comment by rullzer** [comment]
No you did not ;) https://drone.nextcloud.com/nextcloud/server/4267/78

**Comment by MorrisJobke** [comment]
> No you did not ;) https://drone.nextcloud.com/nextcloud/server/4267/78

Yes I did 😝

**Pull request merged**
