### PR TITLE
[stable11] fix wording for apps mgmt buttons

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #2643

### CODE REVIEW

**Review by LukasReschke — DISMISSED** [review]
Not a critical issue but fair enough…

**Review by blizzz — CHANGES_REQUESTED** [review]
Bad to backport changes to translatable strings as we do not backport translations.

**Comment by nickvergessen** [comment]
We do backport translations as per @MorrisJobke

**Review by blizzz — COMMENTED** [review]
trusting https://github.com/nextcloud/server/pull/2751#issuecomment-267966999

**Review by blizzz — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> We do backport translations as per @MorrisJobke

Correct. But not to stable11 yet - I will add a fix for this.

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
