### PR TITLE
fix(streamer): zip64 should work on 32-bit now

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: # 

## Summary

This should work again now that DeepDiver1975/PHPZipStreamer#11 is merged. We've already bumped v28-v30 up to >2.0.1 of ZipStreamer (in nextcloud/3rdparty#1673 and nextcloud/3rdparty#1863).

Untested since I no longer have a 32-bit environment set up for testing.

Came up while looking into nextcloud/files_zip#200.

Maybe @bcutter feels like testing this change too for the standard built-in zip mechanism? :)

To test:

- source needs to consist of  >4GB worth of files (or)  >65536 files.

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Comment by bcutter** [comment]
Tested with a folder of 5.38 GB in total.

1) Without the patch: took quite some time (5 minutes on a Pi 4 with external SSD), but worked without an issue. During generation there was a 0 KB "place holder" zip file.
grafik

2) Because of 1 I did not try to use it with the patched `Streamer.php` file.

Please note I have patched the file 20 minutes before but reverted that changes, see https://github.com/nextcloud/files_zip/issues/200#issuecomment-2453109413 for details.

**Comment by szaimen** [comment]
> 1. Pi 4

The Pi 4 supports 64bit OS and php afaik

**Comment by bcutter** [comment]
Sure. Back in the days it did not and a migration takes a lot of time - so it still runs on a 32 bit OS. Great you asked.

**Comment by come-nc** [comment]
https://github.com/nextcloud/server/actions/runs/11668606807 I can run 32bit CI on this branch, but it seems there is no test for the streamer.
I’m not sure it’s worth it to add a test with `>4GB` files, it will eat up a lot of CI resources.

Can someone with a 32bit setup test locally instead?

Or @joshtrichards if you push a test to this branch I can run the CI again and afterwards we remove or comment out the test.

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
