### PR TITLE
LDAP: configurable user update  interval

### PR DESCRIPTION
**Pull request by blizzz**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Please also downstream the documentation: https://github.com/owncloud/user_ldap/pull/120/files

**Comment by blizzz** [comment]
> Please also downstream the documentation: https://github.com/owncloud/user_ldap/pull/120/files

Yes, this will go to the doc repo.

**Comment by blizzz** [comment]
ah, yet another dusty and forgotten PR… let me rebase

**Review by MorrisJobke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by blizzz** [comment]
Doc additions in https://github.com/nextcloud/documentation/pull/603

**Pull request merged**
