### PR TITLE
Sort files in dialog by name.

### PR DESCRIPTION
**Pull request by panovotn**
Sort file picker dialog entries alphanumerically. #9011 

Signed-off-by: Patrik Novotný <patrik.novotny@gmx.com>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
A different sorting was merged with #8820 - @nextcloud/designers which way do we want to go? Name or modified date.

**Comment by tomtomas99911** [comment]
Please take into consideration that sorting by name is much better option for huge amount of directories. In enterprise use case is not good idea to sort folders by mtime. When you have thousand of folders you need to alphanumerical sorting.

**Comment by MorrisJobke** [comment]
> Please take into consideration that sorting by name is much better option for huge amount of directories. In enterprise use case is not good idea to sort folders by mtime. When you have thousand of folders you need to alphanumerical sorting.

Makes sense IMO

**Comment by juliushaertl** [comment]
Just as in the regular file list we should have the option to sort by both though clicking the table headers. As this is obviously a bigger change, I'd say we should use the sort by name for now. @UncleAlbie Can you rebase your branch on current master?

**Comment by UncleAlbie** [comment]
@juliushaertl Branch rebased on current master.

**Review by MorrisJobke — APPROVED** [review]
For now this makes sense and we should look into refine this by clicking the header in a separate PR.

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
