### PR TITLE
fix permissions for drag-n-drop uploads

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by kesselb** [comment]
Could that fix https://github.com/nextcloud/server/issues/16165?

**Review by ChristophWurst — APPROVED** [review]

**Comment by icewind1991** [comment]
> Could that fix #16165?

I dont think this is related, this fixes an error on master where dnd always gives a permission error

**Comment by AInteriorB** [comment]
This also fixes #15493.

**Pull request merged**
