### PR TITLE
Fix typos in apps/ subdirectory

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S l10n,./apps/files_external/3rdparty -L adn,ba,boxs,keypair,jus,optionel,ressource,tabel ./apps/`

Signed-off-by: luz paz <luzpaz@github.com>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
@luzpaz Can you rebase please?

**Comment by luzpaz** [comment]
@come-nc, indeed, rebased.

**Comment by come-nc** [comment]
@CarlSchwan It needs a compile-amend I think, but I suppose the bot cannot do that on an external repo? Do you know the manual command required to fix it?

**Comment by come-nc** [comment]
@luzpaz Can you run `npm ci && npm run build` and commit the result ?

If not I can import your branch in a local branch and do it.

**Comment by luzpaz** [comment]
I'd rather not run `npm` :rofl:

**Comment by come-nc** [comment]
> I'd rather not run `npm` rofl

I’ll take it from here then.

**Comment by come-nc** [comment]
Superseeded by trusted_proxies

**Comment by come-nc** [comment]
@luzpaz Merged, thanks a lot.

**Pull request closed without merging**
