### PR TITLE
fix `Add to your Nextcloud`

### PR DESCRIPTION
**Pull request by szaimen**
See https://help.nextcloud.com/t/label-add-to-your-nextcloud-hanssonit-vm-is-confusing-people/142101/12

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by CarlSchwan — APPROVED** [review]

**Review by juliusknorr — COMMENTED** [review]
This was a change on purpose to be brandable through https://github.com/nextcloud/server/pull/25950 but from my perspective the product name of the "HanssonIT VM" should still be "Nextcloud".

**Comment by szaimen** [comment]
> This was a change on purpose to be brandable through #25950 

cc @jancborchardt

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Not okay 👎🏼

**Comment by szaimen** [comment]
Closing as discussed internally

**Pull request closed without merging**
