### PR TITLE
Move files_sharing from app.php to IBootstrap

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
CI says nop nop nop

**Comment by PVince81** [comment]
please rebase and hope the Oracle will be kind

**Comment by skjnldsv** [comment]
oracle said no

**Comment by MorrisJobke** [comment]
> oracle said no

All DBs say "no" ;)

**Comment by MorrisJobke** [comment]
Maybe also look into b156cf8c6bf22d44bf38bfe4bb5d7e3900ff19ec (from #21641

**Comment by MorrisJobke** [comment]
Seems to be worked on in #28314 - let me close this one then.

**Pull request closed without merging**
