### PR TITLE
Move oc_appconfig/OC.appConfig to the main bundle

### PR DESCRIPTION
**Pull request by ChristophWurst**
Moves that global variable to the bundle. Deprecation is not possible right now. See details below.

<details>
The `oc_appconfig` var can't be deprecated though, as dirty hacks like https://github.com/nextcloud/server/blob/3d42d4c9dc75f0bddda5140835ff0a232768d529/apps/sharebymail/lib/Settings.php#L37-L52 hook into the config array and write `oc_appconfig`. For the deprecation property getter we'd can't have an existing `window.oc_appconfig` property though.

How *public* is that config hook? What if I just renamed all `oc_appconfig` occurences to `_oc_appconfig` in this repo. @MorrisJobke could you maybe check with your local apps if the `\OCP\Config::js` hook is used anywhere outside server?

If possible I will make `window.oc_appconfig` a deprecated prop in a follow-up PR.
</details>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> How _public_ is that config hook? What if I just renamed all `oc_appconfig` occurences to `_oc_appconfig` in this repo. @MorrisJobke could you maybe check with your local apps if the `\OCP\Config::js` hook is used anywhere outside server?

two third party apps use it at least:

Bildschirmfoto 2019-05-06 um 10 17 21

**Comment by ChristophWurst** [comment]
Okay, thanks for checking. Then I won't fiddle with that yet and leave that to the deprecation of that ugly event/hook.

**Review by MorrisJobke — APPROVED** [review]
Change makes sense 👍

**Comment by ChristophWurst** [comment]
CI fails with MySQL has gone away -> unrelated

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
