### PR TITLE
Change files sharing text

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @schiessle @JSoko @rullzer 

Does this makes sense?

### CODE REVIEW

**Comment by rullzer** [comment]
Yes... and no...

Do we want a more generic test. Because you can also share with ownCloud or Pydio...

**Comment by MorrisJobke** [comment]
> Do we want a more generic test. Because you can also share with ownCloud or Pydio...

Other ideas?

**Comment by rullzer** [comment]
By lack of ideas for other tests here is my :+1: 

We can always change it if somebody has a good idea.

**Comment by oparoz** [comment]
I agree with @rullzer's initial statement.
You could replace ownCloud with "federated cloud" or simply "remote cloud".

**Comment by Bugsbane** [comment]
What about:

"No compatible web app to share with found at {remote}"?

**Comment by mar1u5** [comment]
What about: 

- Instance 
- Cloud 
- Enviroment 
- Server (I like personally best!)

**Comment by MorrisJobke** [comment]
> Server (I like personally best!)

I like this too. @schiessle @karlitschek ?

**Comment by karlitschek** [comment]
yes. i like server too

**Comment by MorrisJobke** [comment]
I changed it to "compatible server"

**Comment by rullzer** [comment]
LGTM

**Pull request merged**
