### PR TITLE
Do not request node when creating a user-group share

### LINKED ISSUE #1862: Error  - no app in context  - OCP\Files\NotFoundException:
### Steps to reproduce
1. Running system
   2.
   3.
### Expected behaviour

Tell us what should happen
### Actual behaviour

The log is filled with the error message - Error

no app in context

OCP\Files\NotFoundException:
### Server configuration

**Operating system**:
ubuntu
**Web server:**
apache
**Database:**
mariadb
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
10.0.1 (updated per snap)
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 10.0
**Where did you install Nextcloud from:**
nextcloud website
**Signing status:**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

<?php
$CONFIG = array (
  'passwordsalt' =>
  'secret' => 
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '10.7.50.19',
    2 => 'nextcloud',
    3 => 'nextcloud',
    4 => 
  ),
  'datadirectory' => '/var/ncdata',
  'overwrite.cli.url' => 
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ncadmin',
  'dbpassword' => 
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'ocy9r9oj7fyg',
  'appstore.experimental.enabled' => 'true',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '465',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 
  'mail_domain' => 'gmail.com',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpname' => 
  'mail_smtppassword' => 
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'maintenance' => false,
);



Error log shows following

OCP\Files\NotFoundException:
1. /var/www/nextcloud/lib/private/Share20/DefaultShareProvider.php - line 437: OC\Share20\Share->getNode()
2. /var/www/nextcloud/lib/private/Share20/Manager.php - line 878: OC\Share20\DefaultShareProvider->move(Object(OC\Share20\Share), 'Intranet')
3. /var/www/nextcloud/apps/files_sharing/lib/SharedMount.php - line 120: OC\Share20\Manager->moveShare(Object(OC\Share20\Share), 'Intranet')
4. /var/www/nextcloud/apps/files_sharing/lib/SharedMount.php - line 102: OCA\Files_Sharing\SharedMount->updateFileTarget('/Klasse 2010 (2...', Object(OC\Share20\Share))
5. /var/www/nextcloud/apps/files_sharing/lib/SharedMount.php - line 73: OCA\Files_Sharing\SharedMount->verifyMountPoint(Object(OC\Share20\Share), Array)
6. /var/www/nextcloud/apps/files_sharing/lib/MountProvider.php - line 91: OCA\Files_Sharing\SharedMount->__construct('\OC\Files\Stora...', Array, Array, Object(OC\Files\Storage\StorageFactory))
7. /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php - line 77: OCA\Files_Sharing\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
8. [internal function] OC\Files\Config\MountProviderCollection->OC\Files\Config{closure}(Object(OCA\Files_Sharing\MountProvider))
9. /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php - line 78: array_map(Object(Closure), Array)
10. /var/www/nextcloud/lib/private/Files/Filesystem.php - line 423: OC\Files\Config\MountProviderCollection->getMountsForUser(Object(OC\User\User))
11. /var/www/nextcloud/apps/files_sharing/lib/sharedstorage.php - line 94: OC\Files\Filesystem initMountPoints('Intranet')
12. /var/www/nextcloud/apps/files_sharing/lib/sharedstorage.php - line 413: OC\Files\Storage\Shared->init()
13. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 486: OC\Files\Storage\Shared->getWrapperStorage()
14. /var/www/nextcloud/lib/private/legacy/util.php - line 149: OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\OC\Files\Stora...')
15. /var/www/nextcloud/lib/private/Files/Storage/StorageFactory.php - line 101: OC_Util {closure}('/a.thoma/files/...', Object(OC\Files\Storage\Shared), Object(OCA\Files_Sharing\SharedMount))
16. /var/www/nextcloud/lib/private/Files/Mount/MountPoint.php - line 146: OC\Files\Storage\StorageFactory->wrap(Object(OCA\Files_Sharing\SharedMount), Object(OC\Files\Storage\Shared))
17. /var/www/nextcloud/lib/private/Files/Mount/MountPoint.php - line 170: OC\Files\Mount\MountPoint->createStorage()
18. /var/www/nextcloud/lib/private/Files/Utils/Scanner.php - line 121: OC\Files\Mount\MountPoint->getStorage()
19. /var/www/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php - line 88: OC\Files\Utils\Scanner->backgroundScan('')
20. /var/www/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php - line 112: OCA\Files\BackgroundJob\ScanFiles->runScanner(Object(OC\User\User))
21. /var/www/nextcloud/lib/private/BackgroundJob/Job.php - line 53: OCA\Files\BackgroundJob\ScanFiles->run(NULL)
22. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php - line 54: OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
23. /var/www/nextcloud/cron.php - line 121: OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
24. {main}


Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #1862 

We don't cleanup the shares table when a file is deleted, Which means that constructing a node fails hard.

To test:

1. UserB has a folder `foo`
2. UserA has a folder `foo`
3. UserB is in group `group1`
4. userA shares `foo` with `group1`
5. userA deletes `foo`
6. Do a propfind as UserB

Before: BOOM
After: NO BOOM

CC: @wherf @enboig @MorrisJobke @nickvergessen @LukasReschke @icewind1991

### CODE REVIEW

**Comment by nickvergessen** [comment]
Integration test?

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
> To test:
> 
> UserB has a folder foo
> UserA has a folder foo
> UserB is in group group1
> userA shares foo with group1
> userA deletes foo
> Do a propfind as UserB

I can't reproduce this :(

**Comment by MorrisJobke** [comment]
> I can't reproduce this :(

It doesn't make 💥

**Comment by rullzer** [comment]
@MorrisJobke did you test stable10?

**Comment by MorrisJobke** [comment]
> @MorrisJobke did you test stable10?

yes (and master before - before I noticed that this only applies to stable10 :()

**Comment by wherf** [comment]
Stupid question, what do I do now? is there some file I need to download and replace? or do I need to run an apt-get update?

Von: Morris Jobke [mailto:notifications@github.com]
Gesendet: Freitag, 11. November 2016 22:52
An: nextcloud/server
Cc: Wolf Dieter Herf; Mention
Betreff: Re: [nextcloud/server] Do not request node when creating a user-group share (#2091)


@MorrisJobke<https://github.com/MorrisJobke> did you test stable10?

yes (and master before - before I noticed that this only applies to stable10 :()

**Comment by rullzer** [comment]
@MorrisJobke ah I was to much into debug mode. Probabaly the exception is thrown but it is catched. Just put a breakpoint at https://github.com/nextcloud/server/blob/master/lib/private/Share20/DefaultShareProvider.php#L438

Now if you have a path that triggers this (like in the original issue) this fails hard.
Basically we can't construct the node because it is no longer in the users files.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by Huster-at-github** [comment]
Same here:

Old:
- External storage, mounted at **/Musik**, shared with User **Share-Account**
- User **Share-Account** shared **/Musik** with a group **Musikliebhaber**
- Had some trouble with this configuration
- Removed external storage **/Musik** for User **Share-Acccount**

Now:
- External Storage, mounted at **/Mucke**, shared with group **Musikliebhaber**
- Access to **/Mucke** works for all users of group **Musiklibhaber** (including user **Userxxx**)

 
**1. "occ audioplayer:scan Userxxx" results into**

Start scan for Userxxx
                                 
  [OCP\Files\NotFoundException]  
  /Userxxx/files/Musik         
                                 
**2. Pressing "Scan for new audio files" in Audio Player app results into log entry:**

```
 Error	index	OCP\Files\NotFoundException: /Userxxx/files/**Musik**	2016-12-29T22:33:09+0100
	OCP\Files\NotFoundException: /Userxxx/files/**Musik**
```

```
0.    /var/www/nextcloud/lib/private/Files/Node/Folder.php - line 122: OC\Files\Node\Root->get('/Userxxx/file...')
1.    /var/www/nextcloud/apps/audioplayer/controller/scannercontroller.php - line 897: OC\Files\Node\Folder->get('/Musik/')
2.    /var/www/nextcloud/apps/audioplayer/controller/scannercontroller.php - line 526: OCA\audioplayer\Controller\ScannerController->getAudioObjects(NULL, NULL)
3.    [internal function] OCA\audioplayer\Controller\ScannerController->scanForAudios(NULL, NULL, NULL)
4.    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
5.    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\audioplayer\Controller\ScannerController), 'scanForAudios')
6.    /var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\audioplayer\Controller\ScannerController), 'scanForAudios')
7.    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\audioplayer...', 'scanForAudios', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
8.    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
9.    /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
10.    /var/www/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/audioplay...')
11.    /var/www/nextcloud/index.php - line 40: OC handleRequest()
12.    {main}
```

**Background:**
- NC 11.0.0
- Audio Player 1.4.0
- occ files:scan --all made no change

**Pull request merged**
