### PR TITLE
Clarify "Delete share" action in sharing sidebar

### LINKED ISSUE #18477: Use "Unshare" instead of "Delete share" for the sharing sidebar
Follow up of https://github.com/nextcloud/server/issues/18202

- [ ] "Delete share" sounds like it deletes some content. Can it be "Unshare"
- [ ] Also, can it have the icon-close as icon instead of the delete icon?

### PR DESCRIPTION
**Pull request by alexandregv**
As requested in #18477 (originally #18202), this PR:
- changes "Delete share" to "Unshare"
- changes icon-delete to icon-close

Fixes: #18477

Signed-off-by: Alexandre Guiot--Valentin <contact@alexandregv.fr>

### CODE REVIEW

**Review by gary-kim — APPROVED** [review]
Thank you for your contribution and welcome!

**Comment by alexandregv** [comment]
No problem :)
I wasn't sure of what I had to include about webpack files haha

**Comment by skjnldsv** [comment]
Hi @alexandregv! Thanks a lot!
Could you also change the others location for this?
You will probably also have it under here
https://github.com/nextcloud/server/blob/176d8e8ab3af0509d8e2fa4d745123b917f52d44/apps/files_sharing/src/components/SharingEntry.vue#L124
https://github.com/nextcloud/server/blob/aa46fc26a46cc6b375ba732bcf3e0dc04a08a2f7/apps/files_sharing/src/components/SharingEntryInherited.vue#L44

I think they were forgotten :)

**Review by skjnldsv — APPROVED** [review]

**Comment by gary-kim** [comment]
Oh, that's why it didn't work!

**Review by juliusknorr — APPROVED** [review]

**Review by jancborchardt — COMMENTED** [review]
Only saw it now, thanks a lot for fixing this detail @alexandregv – and welcome to Nextcloud! :)

**Pull request merged**
