### PR TITLE
Clear multiselect after selection in share panel

### LINKED ISSUE #23468: Share field not cleared/reset after adding recipient
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test"
1. Open the sidebar for "test"
1. Type "user1" in the share field
1. Hit enter or click the result

### Expected result
After the recipient got added, the field should clear itself and focus should go back to that field.

### Actual result
"user1" is still displayed in the field and focus is lost.

This is important to be able to share with multiple people in a row and not having to re-click on the field every time.

### Versions

- Nextcloud 20.0.0 (from git tag v20.0.0)

### PR DESCRIPTION
**Pull request by PVince81**
@skjnldsv not sure why this was disabled in the first place ? Are there use cases where we want to keep the input contents after clicking ?

Fixes https://github.com/nextcloud/server/issues/23468

### CODE REVIEW

**Comment by skjnldsv** [comment]
> Are there use cases where we want to keep the input contents after clicking ?

Yeah, iirc that was a request we had a long time ago, so you could easily batch-add similar searches. Like search for a mail domain `@nextcloud.com` and add multiple results without typing every time

**Comment by jancborchardt** [comment]
Good question – @skjnldsv I also don’t remember a specific request like this.

I’d say @PVince81’s change is good. Also e.g. in the case of emails, people probably copy-paste rather than typing. :+1:

**Review by skjnldsv — APPROVED** [review]
Let's go then! :)

**Review by marcoambrosini — APPROVED** [review]
Sounds good!

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
