### PR TITLE
[stable27] Revert change that made `OC.Util.humanFileSize` return decimal sizes instead of binary

### LINKED ISSUE #38874: wrong user quota in the user administration
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Entering 10GB will allocate 10.7GB as the storage size.  1GB becomes 1.1GB, 500 becomes 575.5GB.

### Steps to reproduce

1. Go to user management
2.Specify an Arbitrary size for the user disk space and see how it becomes a different size.

### Expected behavior

-

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/38874

## Summary
Previously the `OC.Util.humanFileSize` was returning file sizes base 2, meaning 1024 bytes = 1 KiB, but the `@nextcloud/files` library had a regression that set the default to base 10. Meaning 1000 bytes = 1 KB.

This is fixed for current `@nextcloud/libraries` (3.0.0-beta.23) but for stable27 we need to fix this manually by wrapping the function.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by susnux** [comment]
PS: This is just a bugfix so I will not touch the issue that we using binary sizes but showing decimal units. This just restores the previous behavior.

**Comment by susnux** [comment]
drone unrelated

**Review by artonge — APPROVED** [review]

**Comment by come-nc** [comment]
I think this broke node tests: https://github.com/nextcloud/server/actions/runs/6301358504/job/17107304772
```
  OCA.Files.FileList tests
    Removing files from the list
      ✗ Removes file from list when calling remove() and updates summary
	Expected '69 KB' to equal '70 KB'.
	    at Object.<anonymous> (apps/files/tests/js/filelistSpec.js:542:46)

    Deleting files
      ✗ calls delete.php, removes the deleted entries and updates summary
	Expected '57 KB' to equal '58 KB'.
	    at apps/files/tests/js/filelistSpec.js:612:47

    List rendering
      ✗ updates summary using the file sizes
	Expected '69 KB' to equal '70 KB'.
	    at Object.<anonymous> (apps/files/tests/js/filelistSpec.js:1141:46)


  OCA.Files.FileSummary tests
    ✗ renders summary as text
	Expected '250 KB' to equal '256 KB'.
	    at Object.<anonymous> (apps/files/tests/js/filesummarySpec.js:47:47)

    ✗ increases summary when adding files
	Expected '500 KB' to equal '512 KB'.
	    at Object.<anonymous> (apps/files/tests/js/filesummarySpec.js:71:47)

    ✗ decreases summary when removing files
	Expected '125 KB' to equal '128 KB'.
	    at Object.<anonymous> (apps/files/tests/js/filesummarySpec.js:89:47)

    ✗ renders filtered summary as text
	Expected '250 KB' to equal '256 KB'.
	    at Object.<anonymous> (apps/files/tests/js/filesummarySpec.js:107:47)

    ✗ increases filtered summary when adding files
	Expected '500 KB' to equal '512 KB'.
	    at Object.<anonymous> (apps/files/tests/js/filesummarySpec.js:136:47)

    ✗ decreases filtered summary when removing files
	Expected '125 KB' to equal '128 KB'.
	    at Object.<anonymous> (apps/files/tests/js/filesummarySpec.js:158:47)

```

**Comment by luzfcb** [comment]
@susnux @artonge Do you have any idea if the problem that this PR fixes could possibly also be the cause of https://github.com/nextcloud/android/issues/11974 ?

**Comment by come-nc** [comment]
> @susnux @artonge Do you have any idea if the problem that this PR fixes could possibly also be the cause of [nextcloud/android#11974](https://github.com/nextcloud/android/issues/11974) ?

No, this PR only touches the web UI

**Comment by Jerome-Herbinet** [comment]
* Resolves: https://github.com/nextcloud/server/issues/2553

**Pull request merged**
