### PR TITLE
make user status usable on mobile

### PR DESCRIPTION
**Pull request by szaimen**
## Mobile
| Before | After |
|---|---|
| image | image |

## Desktop (no change)
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by nimishavijay — APPROVED** [review]

**Comment by jancborchardt** [comment]
Thanks a lot @szaimen, actually ran into this when setting the status for my vacation. :D

**Pull request merged**
