### PR TITLE
Disable CSS hover behavior on quota information

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Disable CSS hover behavior on quota information (because it's not a button)

### CODE REVIEW

**Comment by szaimen** [comment]
Thanks for your PR! Please do your changes on this file: https://github.com/nextcloud/server/blob/master/core/css/apps.scss and run `npm run sass` and commit the changed css files. Thank you! :)

**Comment by Jerome-Herbinet** [comment]
> Thanks for your PR! Please do your changes on this file: https://github.com/nextcloud/server/blob/master/core/css/apps.scss and run `npm run sass` and commit the changed css files. Thank you! :)

You're welcome :-)
I didn't have time to do it yesterday. It's done now.
Have nice day !

**Comment by Jerome-Herbinet** [comment]
Some errors are remaining ; do you know what could be going on ?

**Comment by Jerome-Herbinet** [comment]
Hi @szaimen,
I manually fixed some conflicts a few days ago. OK for this now.
But, I have now a problem with Drone CI which is failing. 
I've been looking at it with @zak39, but we don't understand what this CI problem has to do with what has been done in the modified SCSS file (+ other files generated by npm run sass). 
What do you think ?

**Comment by szaimen** [comment]
I fear this will need a rebase. Also can you check if this still happens with nc26 since the sidebae was written there afaik

**Pull request closed without merging**
