### PR TITLE
feat(DeclarativeSettings): Allow to define getter and setters in declarative settings form class

### LINKED ISSUE #47108: Declarative Settings: Allow to get and set value inside of form
The new declarative settings are nice because you do not have to care about the front end for simple settings.
Also it reduces the amount of duplicated JS assets that needs to be loaded within the settings.
But currently it is quite complex:

Either you register 3 event listeners for "register", "setValue" and "getValue".
Or you register 2 event listeners ("setValue" and "getValue") and pass the form in the boot logic to the manager.

But even in the second case you have to register two event listeners, instead it would be nice to be able to implement the `setValue` and `getValue` functions within the `DeclarativeForm` class, maybe as a new interface.

So all you have to do is implementing:

```php
class MyForm implements IDeclarativeSettingsWithValue {
    public function getSchema(): array { /**/ }

    /* Called before rendering to get the value to render */
    public function getValue(string $fieldId, IUser $user): mixed { /**/ }

    /* Called on submit to save the value */
    public function setValue(string $fieldId, IUser $user): void { /**/ }
}
```

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #47108 

## Summary

Instead of being required to write 3 event listeners this short cuts the declarative settings by being able to implement the `DeclarativeSettingsFormWithHandlers` interface to have a class providing `getSchema`, `setValue` and `getValue`.
There is also an example implementation in the files app that I migrated for demonstration purpose.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
Mh sure :D

**Review by come-nc — COMMENTED** [review]
Hum wouldn’t listening to the three events with the same listener results in the same code more or less?

**Comment by susnux** [comment]
> more or less

yes, but with "a lot" more boilerplate code (register event listener, wrapping things in the listener). And also potentially slower as all event listeners are called, no problem if only one app is using this, but if there are many apps then every app would be called to handle other settings.

For exapps this makes sense but for native PHP apps this I would say is cleaner.

**Comment by come-nc** [comment]
> > more or less
> 
> yes, but with "a lot" more boilerplate code (register event listener, wrapping things in the listener). And also potentially slower as all event listeners are called, no problem if only one app is using this, but if there are many apps then every app would be called to handle other settings.
> 
> For exapps this makes sense but for native PHP apps this I would say is cleaner.

I don’t get it.

Why is it more code to register for the 3 events a listener rather than registering a "Declarative settings"?
The only boilerplate code is a switch on the event class to call the matching function?

"all event listeners are called", yes but also with your solution they are all called, no? I do not see the performance difference.

**Review by skjnldsv — APPROVED** [review]

**Comment by susnux** [comment]
> Why is it more code to register for the 3 events a listener rather than registering a "Declarative settings"?
> The only boilerplate code is a switch on the event class to call the matching function?

Switch on event listener + registering the event listener in the first place.
But in general we have already two ways:
1. Register by event -> This is still the case here I would also expect using events for get and set.
2. Register a settings class -> We register a class, why should this class only provide the form but not the getter setter? No events needed.

> "all event listeners are called", yes but also with your solution they are all called, no? I do not see the performance difference.

No the `getValue` and `setValue` terminate if the form was registered as a class with handlers.

**Pull request merged**
