### PR TITLE
Replaced history icon by the Material one

### PR DESCRIPTION
**Pull request by Kilian-Perisset**
Asked here : https://github.com/nextcloud/android/pull/4865
The purpose is to replace the "too small" restore icon on server and Android.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
Upon Jan's request :)

**Review by juliusknorr — APPROVED** [review]
Please also update the `history.png` as well, since it is used for activity mails iirc

**Review by juliusknorr — CHANGES_REQUESTED** [review]
Wrong button :wink:

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Good stuff! :) Just as @juliushaertl already said, also make sure to replace the `history.png`.

The line to compress png files is at
https://github.com/nextcloud/server/blob/master/build/image-optimization.sh#L5

**Comment by Shagequi** [comment]
It should be good now :)

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
