### PR TITLE
Revert "[stable25] Fix quota type to int"

### PR DESCRIPTION
**Pull request by PVince81**
Like https://github.com/nextcloud/server/pull/35334 for stable25.
Reverts https://github.com/nextcloud/server/pull/34019

For https://github.com/nextcloud/server/issues/34961#issuecomment-1323719794

### CODE REVIEW

**Comment by szaimen** [comment]
@PVince81 are you sure with the exact revert? https://github.com/nextcloud/server/pull/34019/files looked a bit different...

**Comment by PVince81** [comment]
I cherry-picked the stable24 commit

but can double check in case there's more there

**Comment by PVince81** [comment]
@szaimen looks fine to me. please let me know if you saw something I missed

**Comment by szaimen** [comment]
> @szaimen looks fine to me. please let me know if you saw something I missed

@PVince81 the wxact revert would look like this: https://github.com/nextcloud/server/pull/35336/files

**Review by blizzz — APPROVED** [review]

**Review by blizzz — DISMISSED** [review]
https://github.com/nextcloud/server/pull/35335#issuecomment-1323808306

**Comment by PVince81** [comment]
right, let me redo this then. thanks

**Comment by PVince81** [comment]
should be better now @blizzz @szaimen

**Review by szaimen — APPROVED** [review]
Seems to.be good now

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
CI is red

**Comment by PVince81** [comment]
that thing not even related to the diff:
```
 Error: lib/private/legacy/OC_Helper.php:511:39: InvalidScalarArgument: Argument 1 of OC_Helper::getGlobalStorageInfo expects int, false|float provided (see https://psalm.dev/012)
```

I'll update the baseline

**Review by CarlSchwan — APPROVED** [review]

**Comment by CarlSchwan** [comment]
>  Error: lib/private/legacy/OC_Helper.php:511:39: InvalidScalarArgument: Argument 1 of OC_Helper::getGlobalStorageInfo expects int, false|float provided (see https://psalm.dev/012)

It is related `private static function getGlobalStorageInfo(int $quota, IUser $user, IMountPoint $mount): array;`  int need be changed to float

**Comment by PVince81** [comment]
I ran `lib/composer/bin/psalm --threads=1 --update-baseline --set-baseline=build/psalm-baseline.xml` but it did not update anything related to that function.

Looks like I'll need to fiddle with the baseline file manually again :rage: 

or do I need to run it with a specific php version ? PHP 8.1 here

**Comment by PVince81** [comment]
@szaimen mind testing it ?

**Comment by szaimen** [comment]
> @szaimen mind testing it ?

Honestly I dont know what I need to test. Only changing the quota?

**Comment by PVince81** [comment]
tested on 64-bit system by setting the quota of a user to 5 GB (which is more than the usual 4 GB or 2 GB 32-bit limit), and uploading and reporting that value in the files app worked fine

**Comment by PVince81** [comment]
rebased and DCO'd

**Comment by szaimen** [comment]
> tested on 64-bit system by setting the quota of a user to 5 GB (which is more than the usual 4 GB or 2 GB 32-bit limit), and uploading and reporting that value in the files app worked fine

All right. Fine by me then 👍

However looks like tests are failing?

**Comment by PVince81** [comment]
drone test failures unrelated

also there's this mysterious "push" entry that appeared again. codecov fails but not the tests there

I'll restart the timed out workflow ones

**Pull request merged**
