### PR TITLE
Compile contactmenu handlebars templates

### LINKED ISSUE #11029: Contacts menu uses javascript eval
For https://github.com/orgs/nextcloud/projects/18

The contacts menu still uses handlebars and compiles the templates on the fly. This means that it uses unsafe eval and prevents a stricter CSP

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #11029
For https://github.com/orgs/nextcloud/projects/18

Ship the compiled handlebars templates. This makes it possible to have a
scricter CSP.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by danxuliu — DISMISSED** [review]
There are some extra `'` in the resulting HTML that need to be removed (see https://github.com/nextcloud/server/pull/11414/files#diff-c507f8bb125161aa4ce14d65829a1399R1 or https://github.com/nextcloud/server/pull/11414/files#diff-ed39afd2b2498db3bfb8542af14024c8R2).

**Review by danxuliu — APPROVED** [review]

**Comment by danxuliu** [comment]
For future reference, [to know how to update the templates see this note in `filesummary.js`](https://github.com/nextcloud/server/blob/ae1250f422126808691a99de45ec1ae0574678da/apps/files/js/filesummary.js#L194-L198) (maybe it would be a good idea to include the note in `contactsmenu.js` too? Although if more and more templates are compiled we would end having the same note everywhere).

**Comment by ChristophWurst** [comment]
> For future reference, [to know how to update the templates see this note in `filesummary.js`](https://github.com/nextcloud/server/blob/ae1250f422126808691a99de45ec1ae0574678da/apps/files/js/filesummary.js#L194-L198) (maybe it would be a good idea to include the note in `contactsmenu.js` too? Although if more and more templates are compiled we would end having the same note everywhere).

As discussed in private IRC with @rullzer, I would suggest to add a script that builds all Handlebars templates at once. That will make it easier for devs and also enable us to easily check if they are up to date on CI.

**Review by MorrisJobke — APPROVED** [review]
Still works 👍

**Pull request merged**
