### PR TITLE
clone depth of 1 and execute integration tests first

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
\o/ clone time went down from ~250 seconds to 15 seconds

**Comment by nickvergessen** [comment]
Looks good

**Comment by rullzer** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Before: 26-30 minutes
After:  28 minutes (mostly because of the integration tests ... they run the whole time ... all other jobs where done after 10 minutes)

**Comment by ChristophWurst** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
> Before: 26-30 minutes
> After: 28 minutes

Yes it seems confusing ... but during test execution another PR came in and caused higher load on the server -> the integration test even ran longer.

**Pull request merged**
