### PR TITLE
Increase email main buttons width for non-english languages

### PR DESCRIPTION
**Pull request by solracsf**
Like "Set your password" (en) vs "Créer votre mot de passe" (fr).

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
Ci failure seems to be unrelated (login page related, src/tests/acceptance/features/login.feature:38)

**Review by artonge — APPROVED** [review]

**Comment by CarlSchwan** [comment]
Actually this broke the tests: a fix is available here https://github.com/nextcloud/server/pull/30735

**Comment by nickvergessen** [comment]
Failing  "NODB" section is never unrelated :D

**Pull request merged**
