### PR TITLE
IQueryBuilder::PARAM_STR should CAST(? AS TEXT)

### PR DESCRIPTION
**Pull request by ArtificialOwl**
Signed-off-by: Maxence Lange <maxence@nextcloud.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Is this still needed @daita

**Comment by daita** [comment]
Well, Circles 0.12.0 will might not need it anymore as I will use the uniqueId of the Circle as the share_with (instead of the numerical Id as it is right now) 

However this PR should still be merged to avoid this kind of useless condition:

>		if ($qb->getConnection()->getDatabasePlatform() instanceof PostgreSqlPlatform) {
>			$tmpOrX = $expr->eq('s.share_with', $qb->createFunction('CAST(c.id AS TEXT)'));
>		} else {
>			$tmpOrX =
>				$expr->eq('s.share_with', $expr->castColumn('c.id', IQueryBuilder::PARAM_STR));
>		}

And the oracle version should be done too, but it won't be ready for 12.0.1 for sure.

**Comment by MorrisJobke** [comment]
@nickvergessen @daita @rullzer @icewind1991 What is the status of this in regards of 13?

**Comment by nickvergessen** [comment]
Since I don't know if there are any consequences and it seems to work atm, I'd go with "never touch a running system"

**Comment by daita** [comment]
Also, I do not need it anymore

**Pull request closed without merging**
