### PR TITLE
[stable23] Remove iconv from dependencies and tests

### PR DESCRIPTION
**Pull request by MichaIng**
Manual backport of: #29958
As of: #29965

I removed `iconv` from some additional tests which were missed before, assured to catch all cases via `grep -ir` now 😉. Done for `master` here: #30352

Requires a backport of the documentation change: https://github.com/nextcloud/documentation/pull/7860

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by MichaIng** [comment]
Related docs update: https://github.com/nextcloud/documentation/pull/7864

**Review by blizzz — APPROVED** [review]

**Comment by MichaIng** [comment]
Manual backport to `stable22`: #30515

**Pull request merged**
