### PR TITLE
fix(files): Ensure scrolled file list does not leak through file filters

### LINKED ISSUE #46772: File filter has no background when sticky during scroll
- Have a long file list
- Scroll down

As seen on daily:

Screenshot 2024-07-26 at 10 19 32

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/46772

## Summary

1. when scrolling the file list should not be visible behind the filters
2. on mobile we need to remove the padding of the filters to ensure they are accessible

[Bildschirmaufnahme_20240726_132643.webm](https://github.com/user-attachments/assets/75a3b9b1-1770-4275-a016-bc1044919b9f)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by juliushaertl** [comment]
Would be nice to address the cut off select input as well ;) 

Also seems to happen when opening it:
Screenshot 2024-07-26 at 14 50 41

**Comment by susnux** [comment]
> Would be nice to address the cut off select input as well ;)

Unrelated to this and seems like a component issue :)

**Comment by juliushaertl** [comment]
I'm not sure where the of users is originating from but 99dcbxiv seems to be what is assumed as a user id on daily for me causing this one broken entry.

**Review by juliusknorr — APPROVED** [review]

**Comment by susnux** [comment]
> I'm not sure where the of users is originating

@juliushaertl two sources:
1. `owner` property of the node
2. `sharee` of the node 

I think there might be a problem if 2 is a group(?) I will investigate this.

**Pull request merged**
