### PR TITLE
Fix height for horizontal scrollbar

### PR DESCRIPTION
**Pull request by artemanufrij**
Signed-off-by: Artem Anufrij <artem.anufrij@live.de>

### CODE REVIEW

**Comment by artemanufrij** [comment]
fix for #5306

**Comment by artemanufrij** [comment]
screenshot_20170608_193041

**Review by juliusknorr — APPROVED** [review]
Makes sense to apply the change to the height as well. :+1:

**Review by jancborchardt — APPROVED** [review]
Good catch! :)

**Comment by jancborchardt** [comment]
Btw @artemanufrij since you are part of the Nextcloud Github organization, you can just create branches in this main repository and you don’t need your fork. :) This makes collaboration much easier.

**Comment by jancborchardt** [comment]
Drone failure unrelated, CSS change only. Merging. :)

**Pull request merged**
