### PR TITLE
Touch to zoom img preview

### PR DESCRIPTION
**Pull request by rullzer**
* Request a preview that covers the area and not fills it (better to have a few more pixels)
* Remove link of the preview so that tapping it works once again

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by jancborchardt** [comment]
Hm, clicking an image doesn’t really seem to do anything? (Previously it opened the /preview URL)

**Comment by rullzer** [comment]
@jancborchardt well now I'm confused... https://github.com/nextcloud/server/issues/7614#issuecomment-355734140

if you want to keep opening the /preview then we can just close this PR... However, we can't make it open the full original image as I mentioned. So your call.

**Comment by rullzer** [comment]
Mmmm ok so after thinking I think the opening of the preview just makes more sense. And now that we have higher default sizes (only for newly uploaded pictures). Opening /preview should be enough for now.

Lets close this and if we want to have it do more/different think about this for 14.

**Comment by jancborchardt** [comment]
Ok, cool. I guess we were both confused there. :)

And yeah, your other fix already does a lot of good towards not always needing to get a larger image.

**Pull request closed without merging**
