### PR TITLE
Always renew apppasswords on login

### PR DESCRIPTION
**Pull request by rullzer**
Else you can end up that you renewed your password (LDAP for example).
But they still don't work because you did not use them before you logged
in.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by juliushaertl** [comment]
Code makes sense, but still one failure:


1) Test\Authentication\Token\PublicKeyTokenProviderTest::testUpdatePasswordsNotRequired
OC\Authentication\Token\PublicKeyTokenMapper::getTokenByUser('myUID'): array was not expected to be called.

/drone/src/lib/private/Authentication/Token/PublicKeyTokenProvider.php:418
/drone/src/tests/lib/Authentication/Token/PublicKeyTokenProviderTest.php:578

**Comment by zimmersi** [comment]
these changes breaking the webauthn login (not 2FA). NC 21.0.3 and NC 22
The login process itself is working though, but the users are constantly logged out after a short period of time. this affects not only the sessions in the browser, also all sync clients are logged out every few minutes, which makes it unusebale!

after reverting this changes in my NC 21.0.3, everything is working again as expected!

**Comment by akhil1508** [comment]
There was a major increase in the number of `UPDATE` queries of the form: ```UPDATE `authtoken` SET `password` = <redacted> ==' WHERE `id` = <redacted>``` due to the changes in this PR after updating from 20.0.12 to 21.0.7. To avoid this increase in load on the database, this PR's changes had to be reverted.

- Stats on day before reverting the changes(one hour time frame):
before
- Stats on day after reverting the changes(one hour time frame):
after
We see a decrease after reverting the changes in:
- Number of `UPDATE` queries
- Number of open tables cache
- Rate of questions
- Network traffic
- Thread activity

On another smaller nextcloud instance with less than 10 active users, we had ~2k `UPDATE` queries every minute. 
This [comment](https://github.com/nextcloud/server/issues/26502#issuecomment-821983093) is related to the issue and was also the fix for our problem.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/29682 should fix that

**Comment by akhil1508** [comment]
> #29682 should fix that That being said, I'm not aware that 21 is impacted as the faulty other part is not there.

21 is indeed impacted with high database load. The above screenshots are from a 21.0.7 server.

**Comment by nickvergessen** [comment]
Maybe you can create a new issue then as the author of the PR is no longer with the project and therefore commenting on a ~1 year old PR is not the best way forward.

**Pull request merged**
