### PR TITLE
cache loginName2UserName and cover the method with unit tests

### PR DESCRIPTION
**Pull request by blizzz**
@LukasReschke saw a code path that was talking to LDAP on any request. Turns out, it did not cache the result. Covered by unit tests, please review. @nextcloud/ldap

### CODE REVIEW

**Comment by blizzz** [comment]
Somehow I cannot assingn the milestone?!

**Comment by LukasReschke** [comment]
> Somehow I cannot assingn the milestone?!

Me neither…

**Comment by rullzer** [comment]
Does the trick for me!
LGTM!

**Comment by MorrisJobke** [comment]
Tested and works for me :+1:

**Review by MorrisJobke — APPROVED** [review]

**Comment by blizzz** [comment]
A candidate for backporting. Not a serious issue, but fixing the missing caching for that method brings cyber-performance benefits. @karlitschek

**Comment by LukasReschke** [comment]
To put it relative: Without that nearly every request takes 400ms longer on cloud.nextcloud.com because it does quite some LDAP queries. 🙈

**Comment by LukasReschke** [comment]
https://blackfire.io/profiles/compare/e572e269-b74e-4e75-bcbf-a198b1850072/graph

**Comment by karlitschek** [comment]
👍

**Comment by blizzz** [comment]
Backport is here: https://github.com/nextcloud/server/pull/1654

**Pull request merged**
