### PR TITLE
Css4 variables migration

### LINKED ISSUE #6727: Meet WCAG 2.0 AA(AAA?) for contrast
Currently there are still a lot of colors that NC uses that do not meet the guidelines for WCAG AA. I feel like this is something that probably is a goal for NC and if not, should be. There have been small commits to fix issues like this in the past but it would be nice to see most of the issues fixed once and for all and then keeping the level for new commits and features.

This came up as a discussion in IRC relating to the Admin page notes about stuff like "Execute one task with each page loaded" but in addition to those there seems to be a lot of other places that use poor contrast. I feel like even I could use the contrast increase for most of the things and I don't have an issue with my eyesight.

So a quick list of the things I found for now that could use some improvement, there's probably more unfortunately:

- settings-hint elements found almost everywhere
- cpuFooterInfo and memFooterInfo under Monitoring
- table column titles in various places like Security, Activity and Logging
- The little "(Stream only)" <em\> under Activity
- "Select tag..." under Workflow > Collaborative tags
- file extension, small filesize and old file text in Files
- The space usage text and bar in bottom left
- Under a file, in Comments your username over the new comment field is very light
- Possibly the box and placeholder too
- Box and placeholder under file's sharing tab ("Name, federated cloud" etc)

@nextcloud/designers @nextcloud/accessibility

### PR DESCRIPTION
**Pull request by skjnldsv**
## Why?
- **Reactivity**: css4 variables can be changed on-the-fly and provide a theming possibility preview far easier and smooth
- **External css**: others apps/modules can use our variables without scss
- **Vue components**: we can't process our scoped scss from the vue components and exclude the variables compilation from the process. If we want to allow the use of variables, this is the only way.

Fixes #6727

## How
- [x] Convert our scss vars to css4
- [x] Cleanup our multiple darken/lighten functions (who are incompatible with css4 vars)
- [x] rgba fixes
- [x] theming migration
- [x] Implement [IE11 ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill) (~~which works perfectly~~ only a small downside, see comments)

### CODE REVIEW

**Comment by rullzer** [comment]
Question time!

* This works in all supported browsers?
* Would this mean we could eventually move to generated CSS (not on the fly like we do now but in a make file?) This just shipping plain files?

**Comment by skjnldsv** [comment]
> This works in all supported browsers?

Yes, except IE11 (but the ponyfill is working fine and will be added into this pr as well)

> Would this mean we could eventually move to generated CSS (not on the fly like we do now but in a make file?) This just shipping plain files?

No because scss also add more stuff like the colour manipulation functions, calculation and most importantly, our nesting css properties :)

**Comment by rullzer** [comment]
> No because scss also add more stuff like the colour manipulation functions, calculation and most importantly, our nesting css properties :)

I wasn't suggesting killing SCSS. More like if we could do it only once when creating tarballs basically. But I guess not if we need colour manipulating functions etc.

**Comment by skjnldsv** [comment]
@rullzer sorry, I misunderstood :)
Since scss are pre-processed scripts, we can already do that.
So yes, in the end the only colours manipulations functions are used (and can only be used for this exact purpose) in the variables.scss function. Since the vars are going to be forwarded to css4 variables, we could probably ship fully compiled css files within tarballs. It will still require to migrate the thming app to css4 vars before doing so though :)

**Comment by skjnldsv** [comment]
@juliushaertl would you take a look at the theming part?
I guess you just need to redefine the variables you need to change into the css `:root` ?

**Comment by juliushaertl** [comment]
@skjnldsv Sure, I'll have a look.

**Comment by juliushaertl** [comment]
@skjnldsv I adjusted the theming preview code to just reload the css variables and the theming.scss file (which has some additional customizations) It is indeed a lot faster than rebuilding the whole server.scss file.

I didn't move the whole theming to css vars for now, since that would actually be something i would tackle in a separate PR. Would that be ok for you?

**Comment by skjnldsv** [comment]
> I didn't move the whole theming to css vars for now, since that would actually be something i would tackle in a separate PR. Would that be ok for you?

perfect!
For 14, we'll keep them both since theming is designed to be instance-wide, I like it a lot that we have both available
For 15 I'll say we remove the variables.scss from the compile import to ensure no apps use them anymore. Like that we force the css4 variables everywhere and they're still managed by our scss variables and the neat colours functions sass provides. What do you think?

**Comment by skjnldsv** [comment]
@danxuliu There is some strange behaviour with some acceptance tests. Sometimes it passes, sometimes not, maybe a timeout issue? Could you take a quick look please? <3

**Comment by skjnldsv** [comment]
@nextcloud/designers I know we all hate IE11, but I need your opinion.
The css4 ponyfill script works fine but have a little downside to it. I'll let you see it in action. Is this still acceptable ? If not we'll have to go for something else and theming per-user won't be compatible with ie11.

kazam

**Comment by MorrisJobke** [comment]
> @nextcloud/designers I know we all hate IE11, but I need your opinion.
> The css4 ponyfill script works fine but have a little downside to it. I'll let you see it in action. Is this still acceptable ? If not we'll have to go for something else and theming per-user won't be compatible with ie11.

Is the flickering the downside? Then it should be okay.

**Comment by skjnldsv** [comment]
@MorrisJobke Yes, the flickering! :)

**Comment by danxuliu** [comment]
@skjnldsv
> There is some strange behaviour with some acceptance tests. Sometimes it passes, sometimes not, maybe a timeout issue? Could you take a quick look please? <3

Sure, here is the summary:
- failures in _app-theming_ were caused by the new transition added to the header colour; while I really love it, in the future please add those type of enhancements in a different pull request, specially with pull requests as big as this one ;-)
- step _I close the details view_ in _app-files_ is a known race condition that I have to fix
- step _I click the New user button_ in _app-users_ is expected to fail sometimes with its current implementation (remember my pending clean up? ;-) )
- although I have a hunch, I need to take a deeper look to why step _I open the XXX section_ in _app_ fails; it should not be related to the changes in this pull request, though

As they are not related to this one, the pending changes to the acceptance tests will be done in other pull requests ;-)

**Comment by skjnldsv** [comment]
@danxuliu thanks!! <3

**Comment by skjnldsv** [comment]
@nextcloud/designers please review :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works (also in Edge and IE11) 👍

**Comment by MorrisJobke** [comment]
Apps that need the migration (after a quick search):

* calendar
* contacts
* data_request
* deck
* tropft
* firstrunwizard
* keeporsweep
* mail
* notifications
* spreed
* tasks

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Conflicts :wink:

**Comment by skjnldsv** [comment]
Failure not related 

`sh: 1: kill: No such process
`

**Pull request merged**
