### PR TITLE
Single block for PHP Mod not installed error

### PR DESCRIPTION
**Pull request by williambargentball**
Groups the PHP Mod not installed errors on installation into one block.

### CODE REVIEW

**Comment by blizzz** [comment]
@williambargent Thank you for the pull request! I need to point out that our guide lines are that  you need to have two reviewers giving their :+1: before merging. Now the change is not critical, but please keep in mind for the future :) :sun_with_face: 

@jancborchardt fyi

**Comment by williambargent** [comment]
Sorry, wasn't aware.

**Comment by blizzz** [comment]
No prob :)

**Comment by jancborchardt** [comment]
Um @williambargent can you show a before-after screenshot of this? It’s likely this was intentional and the removal of the rule has unintended side-effects.

For a design pull request, please always provide screenshots. And yep – again, there need to be 2 reviews of others. cc @nextcloud/designers

**Pull request merged**
