### PR TITLE
Fix some minor settings UI issues

### PR DESCRIPTION
**Pull request by juliusknorr**
- [x] Move social icons to the personal settings (as discussed with @karlitschek)
image
- [x] Add left padding to icons in the security session list
- [x] Fix layout for adding collaborative tags
Before:
image
After:
image
image
- [x] Improve description for collaborative tags
> Collaborative tags are available for all users. Restricted tags are visible to users but cannot be assigned by them. Invisible tags are for internal use, since users cannot see or assign them.
- [x] Minor alignment fix for automated tagging
Before:
image
After:
image

Once we have some docs about the collaborative tags we should also add a link to that in the settings. https://github.com/nextcloud/documentation/issues/789

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
I like it and it works 👍

**Comment by MorrisJobke** [comment]
Unit tests fail and it needs to be merged: `Please run: php build/mergejs.php`

**Comment by juliushaertl** [comment]
@MorrisJobke Fixed the CI failure. The current one seems unrelated to me in acceptance-app-files https://drone.nextcloud.com/nextcloud/server/8517/230

Since the js merge is not related i moved it to #10043

**Comment by skjnldsv** [comment]
Failure unrelated it seems :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
It seems that the acceptance test are broken then:

```
  Scenario: create tags using the Administration settings                                    # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:167
    Given I am logged in as the admin                                                        # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I visit the settings page                                                            # SettingsMenuContext::iVisitTheSettingsPage()
    And I open the "Workflow" section                                                        # AppNavigationContext::iOpenTheSection()
    And I see that the button to select tags is shown                                        # SettingsContext::iSeeThatTheButtonToSelectTagsIsShown()
    When I create the tag "tag1" in the settings                                             # SettingsContext::iCreateTheTagInTheSettings()
      │ Reset button in system tags section in Administration Settings could not be clicked
      │ Exception message: Offset within element cannot be scrolled into view: (16, 16): 
      │ Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      │ System info: host: '62d11aeaa494', ip: '172.17.0.24', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-22-generic', java.version: '1.8.0_91'
      │ Driver info: driver.version: unknown
      │ Trying again
      │ 
      Offset within element cannot be scrolled into view: (16, 16): 
      Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      System info: host: '62d11aeaa494', ip: '172.17.0.24', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-22-generic', java.version: '1.8.0_91'
      Driver info: driver.version: unknown (WebDriver\Exception\MoveTargetOutOfBounds)
    Then I see that the dropdown for tags in the settings eventually contains the tag "tag1" # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()

  Scenario: add tags using the dropdown in the details view                                 # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:178
    Given I am logged in as the admin                                                       # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I visit the settings page                                                           # SettingsMenuContext::iVisitTheSettingsPage()
    And I open the "Workflow" section                                                       # AppNavigationContext::iOpenTheSection()
    And I see that the button to select tags is shown                                       # SettingsContext::iSeeThatTheButtonToSelectTagsIsShown()
    And I create the tag "tag1" in the settings                                             # SettingsContext::iCreateTheTagInTheSettings()
      │ Reset button in system tags section in Administration Settings could not be clicked
      │ Exception message: Offset within element cannot be scrolled into view: (16, 16): 
      │ Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      │ System info: host: '62d11aeaa494', ip: '172.17.0.24', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-22-generic', java.version: '1.8.0_91'
      │ Driver info: driver.version: unknown
      │ Trying again
      │ 
      Offset within element cannot be scrolled into view: (16, 16): 
      Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      System info: host: '62d11aeaa494', ip: '172.17.0.24', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-22-generic', java.version: '1.8.0_91'
      Driver info: driver.version: unknown (WebDriver\Exception\MoveTargetOutOfBounds)
    And I create the tag "tag2" in the settings                                             # SettingsContext::iCreateTheTagInTheSettings()
    And I create the tag "tag3" in the settings                                             # SettingsContext::iCreateTheTagInTheSettings()
    And I create the tag "tag4" in the settings                                             # SettingsContext::iCreateTheTagInTheSettings()
    And I see that the dropdown for tags in the settings eventually contains the tag "tag1" # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
    And I see that the dropdown for tags in the settings eventually contains the tag "tag2" # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
    And I see that the dropdown for tags in the settings eventually contains the tag "tag3" # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
    And I see that the dropdown for tags in the settings eventually contains the tag "tag4" # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
    And I log out                                                                           # SettingsMenuContext::iLogOut()
    And I am logged in                                                                      # LoginPageContext::iAmLoggedIn()
    And I open the details view for "welcome.txt"                                           # FileListContext::iOpenTheDetailsViewFor()
    And I open the input field for tags in the details view                                 # FilesAppContext::iOpenTheInputFieldForTagsInTheDetailsView()
    When I check the tag "tag2" in the dropdown for tags in the details view                # FilesAppContext::iCheckTheTagInTheDropdownForTagsInTheDetailsView()
    And I check the tag "tag4" in the dropdown for tags in the details view                 # FilesAppContext::iCheckTheTagInTheDropdownForTagsInTheDetailsView()
    Then I see that the tag "tag2" in the dropdown for tags in the details view is checked  # FilesAppContext::iSeeThatTheTagInTheDropdownForTagsInTheDetailsViewIsChecked()
    And I see that the tag "tag4" in the dropdown for tags in the details view is checked   # FilesAppContext::iSeeThatTheTagInTheDropdownForTagsInTheDetailsViewIsChecked()
    And I see that the input field for tags in the details view contains the tag "tag2"     # FilesAppContext::iSeeThatTheInputFieldForTagsInTheDetailsViewContainsTheTag()
    And I see that the input field for tags in the details view contains the tag "tag4"     # FilesAppContext::iSeeThatTheInputFieldForTagsInTheDetailsViewContainsTheTag()

  Scenario: remove tags using the dropdown in the details view                                  # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:206
    Given I am logged in as the admin                                                           # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I visit the settings page                                                               # SettingsMenuContext::iVisitTheSettingsPage()
    And I open the "Workflow" section                                                           # AppNavigationContext::iOpenTheSection()
    And I see that the button to select tags is shown                                           # SettingsContext::iSeeThatTheButtonToSelectTagsIsShown()
    And I create the tag "tag1" in the settings                                                 # SettingsContext::iCreateTheTagInTheSettings()
      │ Reset button in system tags section in Administration Settings could not be clicked
      │ Exception message: Offset within element cannot be scrolled into view: (16, 16): 
      │ Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      │ System info: host: '62d11aeaa494', ip: '172.17.0.24', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-22-generic', java.version: '1.8.0_91'
      │ Driver info: driver.version: unknown
      │ Trying again
      │ 
      Offset within element cannot be scrolled into view: (16, 16): 
      Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
      System info: host: '62d11aeaa494', ip: '172.17.0.24', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-22-generic', java.version: '1.8.0_91'
      Driver info: driver.version: unknown (WebDriver\Exception\MoveTargetOutOfBounds)
    And I create the tag "tag2" in the settings                                                 # SettingsContext::iCreateTheTagInTheSettings()
    And I create the tag "tag3" in the settings                                                 # SettingsContext::iCreateTheTagInTheSettings()
    And I create the tag "tag4" in the settings                                                 # SettingsContext::iCreateTheTagInTheSettings()
    And I see that the dropdown for tags in the settings eventually contains the tag "tag1"     # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
    And I see that the dropdown for tags in the settings eventually contains the tag "tag2"     # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
    And I see that the dropdown for tags in the settings eventually contains the tag "tag3"     # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
    And I see that the dropdown for tags in the settings eventually contains the tag "tag4"     # SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
    And I log out                                                                               # SettingsMenuContext::iLogOut()
    And I am logged in                                                                          # LoginPageContext::iAmLoggedIn()
    And I open the details view for "welcome.txt"                                               # FileListContext::iOpenTheDetailsViewFor()
    And I open the input field for tags in the details view                                     # FilesAppContext::iOpenTheInputFieldForTagsInTheDetailsView()
    And I check the tag "tag2" in the dropdown for tags in the details view                     # FilesAppContext::iCheckTheTagInTheDropdownForTagsInTheDetailsView()
    And I check the tag "tag4" in the dropdown for tags in the details view                     # FilesAppContext::iCheckTheTagInTheDropdownForTagsInTheDetailsView()
    And I check the tag "tag3" in the dropdown for tags in the details view                     # FilesAppContext::iCheckTheTagInTheDropdownForTagsInTheDetailsView()
    When I uncheck the tag "tag2" in the dropdown for tags in the details view                  # FilesAppContext::iUncheckTheTagInTheDropdownForTagsInTheDetailsView()
    And I uncheck the tag "tag4" in the dropdown for tags in the details view                   # FilesAppContext::iUncheckTheTagInTheDropdownForTagsInTheDetailsView()
    Then I see that the tag "tag2" in the dropdown for tags in the details view is not checked  # FilesAppContext::iSeeThatTheTagInTheDropdownForTagsInTheDetailsViewIsNotChecked()
    And I see that the tag "tag4" in the dropdown for tags in the details view is not checked   # FilesAppContext::iSeeThatTheTagInTheDropdownForTagsInTheDetailsViewIsNotChecked()
    And I see that the tag "tag3" in the dropdown for tags in the details view is checked       # FilesAppContext::iSeeThatTheTagInTheDropdownForTagsInTheDetailsViewIsChecked()
    And I see that the input field for tags in the details view does not contain the tag "tag2" # FilesAppContext::iSeeThatTheInputFieldForTagsInTheDetailsViewDoesNotContainTheTag()
    And I see that the input field for tags in the details view does not contain the tag "tag4" # FilesAppContext::iSeeThatTheInputFieldForTagsInTheDetailsViewDoesNotContainTheTag()
    And I see that the input field for tags in the details view contains the tag "tag3"         # FilesAppContext::iSeeThatTheInputFieldForTagsInTheDetailsViewContainsTheTag()
```

@danxuliu Could you help with that?

**Comment by juliushaertl** [comment]
Seems that is was caused by the reset button being hidden, but it makes sense to keep it, so you can abort the action before you create a new tag.

**Comment by danxuliu** [comment]
>  Seems that is was caused by the reset button being hidden,

Indeed; before a new tag is created the reset button was clicked to ensure that no tag was being updated (there is currently no test in which that could happen, but it was added just to be sure). As the reset button was hidden it could not be clicked and the test failed.

>  but it makes sense to keep it, so you can abort the action before you create a new tag.

I was going to remove the click on the reset button instead, but you are right in that it makes sense to keep it visible :+1:

>  Let's see if that works.

It does :-)

**Comment by rullzer** [comment]
Rebased for CI

**Comment by jancborchardt** [comment]
@juliushaertl just a small comment on the collaborative tags UI: Seeing as there are 3 icons without label, the "Delete" and "Reset" buttons should be in a 3-dot-menu, no?

**Comment by juliushaertl** [comment]
@jancborchardt I'd say this is a special case, since the user is already in edit mode when this ui is shown. Therefore those 3 actions are equally important and we cannot determine a default action which will always be used. So having all those in a 3 dot menu would lead to one additional click for any action the user would take.

**Pull request merged**
