### PR TITLE
Only clear share password model when actually saved

### PR DESCRIPTION
**Pull request by PVince81**
Instead of always clearing the password in the share model, now only do
it when it was actually saved.

Fixes an issue where saving another field would clear the password too
early and prevent it to be saved when the dropdown closed.

### CODE REVIEW

**Comment by PVince81** [comment]
pfff, so compiling with `MODULE=files_sharing make build-js-production` didn't produce the expected result

**Review by rullzer — APPROVED** [review]

**Comment by PVince81** [comment]
pfff, why isn't the amend working ?

**Comment by PVince81** [comment]
let me do this manually...

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
> pfff, why isn't the amend working ?

you're not alone, let me check

**Pull request merged**
