### PR TITLE
fix setting quota to default or unlimited

### PR DESCRIPTION
**Pull request by icewind1991**
cc @ChristophWurst

### CODE REVIEW

**Comment by rullzer** [comment]
LGTM

**Comment by LukasReschke** [comment]
LGTM

**Comment by icewind1991** [comment]
should be backported to 10 I guess

**Comment by MorrisJobke** [comment]
@icewind1991 Could you create the backport PR? Thanks

**Comment by MorrisJobke** [comment]
> @icewind1991 Could you create the backport PR? Thanks

@icewind1991 Ping

**Comment by icewind1991** [comment]
stable10: https://github.com/nextcloud/server/pull/1327

**Comment by mama21mama** [comment]
will not let me change the size of disk to each user. it is in unlimited. As you change the quota ?

**Comment by ChristophWurst** [comment]
> will not let me change the size of disk to each user. it is in unlimited. As you change the quota ?

Please use https://help.nextcloud.com/ for general questions or file a new issue if you've found a bug. Thanks

**Pull request merged**
