### PR TITLE
Add a migration step to save the data from the accounts table before …

### PR DESCRIPTION
**Pull request by nickvergessen**
…migrating

- [x] Copy data
- [x] Make sure you can upgrade from 10.0.0
- [x] Copy avatars to new location
- [x] Recreate accounts table with our data

Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I get this when running an update from OC 10 to NC master: 

```
Failed to update database structure (Doctrine\\DBAL\\Schema\\SchemaException: There is no column with name 'uid' on table 'oc_accounts'. in 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:86\nStack trace:
    #0 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php(671): Doctrine\\DBAL\\Schema\\SchemaException::columnDoesNotExist('uid', 'oc_accounts')
    #1 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php(702): Doctrine\\DBAL\\Schema\\Table->getColumn('uid')
    #2 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php(630): Doctrine\\DBAL\\Platforms\\MySqlPlatform->getPreAlterTableAlterPrimaryKeySQL(Object(Doctrine\\DBAL\\Schema\\TableDiff), Object(Doctrine\\DBAL\\Schema\\Index))
    #3 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php(612): Doctrine\\DBAL\\Platforms\\MySqlPlatform->getPreAlterTableIndexForeignKeySQL(Object(Doctrine\\DBAL\\Schema\\TableDiff))
    #4 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php(199): Doctrine\\DBAL\\Platforms\\MySqlPlatform->getAlterTableSQL(Object(Doctrine\\DBAL\\Schema\\TableDiff))
    #5 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php(136): Doctrine\\DBAL\\Schema\\SchemaDiff->_toSql(Object(Doctrine\\DBAL\\Platforms\\MySQL57Platform), false)
    #6 lib/private/DB/Migrator.php(254): Doctrine\\DBAL\\Schema\\SchemaDiff->toSql(Object(Doctrine\\DBAL\\Platforms\\MySQL57Platform))
    #7 lib/private/DB/Migrator.php(86): OC\\DB\\Migrator->applySchema(Object(Doctrine\\DBAL\\Schema\\Schema))
    #8 lib/private/DB/MDB2SchemaManager.php(122): OC\\DB\\Migrator->migrate(Object(Doctrine\\DBAL\\Schema\\Schema))
    #9 lib/private/legacy/db.php(186): OC\\DB\\MDB2SchemaManager->updateDbFromStructure('/srv/projects/s...')
    #10 lib/private/Updater.php(288): OC_DB::updateDbFromStructure('/srv/projects/s...')
    #11 lib/private/Updater.php(237): OC\\Updater->doCoreUpgrade()
    #12 lib/private/Updater.php(130): OC\\Updater->doUpgrade('12.0.0.20', '10.0.0.12')
    #13 core/ajax/update.php(197): OC\\Updater->upgrade()
    #14 {main})
```

Any idea why it fails with this error, because it properly detects that this needs to be added.

**Comment by nickvergessen** [comment]
Grml, Maria DB? I think we need to kill the table completly because it tries to update the primary index instead  of deleting + recreating. But that doesn't work, because it still contains wrong columns after adding and before removing of the old columns

**Comment by MorrisJobke** [comment]
> Grml, Maria DB?

No - MySQL 5.7.18 on Ubuntu 16.04

**Comment by nickvergessen** [comment]
Fixed, also adjusted the background job that copies the avatars to work with ownclouds new location.

**Comment by nickvergessen** [comment]
@schiessle please help with generating the account table entries

**Review by rullzer — APPROVED** [review]
Makes sense. :+1:  Avatars got moved for me

**Comment by nickvergessen** [comment]
So aparently the account entries are created on next usage then. So should be fine.

**Comment by nickvergessen** [comment]
Rebased for version.php change

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
