### PR TITLE
improve app settings design

### LINKED ISSUE #33802: Settings panel in sidebar, separation a bit too weak visually
BUG: design: settings panel in sidebar, separation a bit too weak visually

image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/33802

This is best reviewed like this: https://github.com/nextcloud/server/pull/33900/files?diff=unified&w=1

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
@szaimen do you have a before/after screenshot of the settings when they are collapsed? (Ideally should look the same). Regarding my concern at https://github.com/nextcloud/server/issues/33802#issuecomment-1234585912
I tried to test on my local instance but for some reason the area is not updated.

**Comment by szaimen** [comment]
> I tried to test on my local instance but for some reason the area is not updated.

I gues it is because the js is not compiled yet...

**Comment by szaimen** [comment]
> > I tried to test on my local instance but for some reason the area is not updated.
> 
> I gues it is because the scss is not compiled yet...

should work now

**Comment by szaimen** [comment]
| closed | opened |
|---|---|
| image | image |

**Comment by szaimen** [comment]
CI failing unrelated

**Pull request merged**
