### PR TITLE
External delete directly

### LINKED ISSUE #14436: Disable trash per folder; Especially for external storage folder
**Is your feature request related to a problem? Please describe.**
When adding external storage folder (e.g. SMB) they integrate nicely. But when deleting elements out of those folder they will be moved to local trash bin, which can take a very long time depending on the file size, connection, etc. and this may sometimes even not be desired.

**Describe the solution you'd like**
A good general solution would be to disable trash bin manually on a per folder basis. Or in the settings where the user can list folders to be excluded.

**Describe alternatives you've considered**
One alternative would be to outsource the solution specifically to the external storage add-on and provide a similar option only there on a per share basis.

**Additional context**
-

### PR DESCRIPTION
**Pull request by dassio**
same as #22632

I accidentally deleted the forked repo, here i created  a new repo and did a rebase 

Edit: @jancborchardt @icewind1991 @ChristophWurst please help to review

### CODE REVIEW

**Comment by kevinkk525** [comment]
Thank you for implementing this! Have been looking forward to this feature for a very very long time.

(Hope it'll make it to Nextcloud 20.01 and 19.05 soon :-) )

**Comment by rullzer** [comment]
> Thank you for implementing this! Have been looking forward to this feature for a very very long time.
> 
> (Hope it'll make it to Nextcloud 20.01 and 19.05 soon :-) )

won't. We don't backport features

**Comment by kevinkk525** [comment]
:( nextcloud 20 was just released. 21 will take ages and this is basically a bugfix for external_storages.. but ok. Thanks for the answer, at least now I know not to expect it anytime soon.

**Comment by skjnldsv** [comment]
Please rebase @dassio :pray:

**Comment by InfamousUser** [comment]
Any update on this?

**Comment by jancborchardt** [comment]
@PVince81 @skjnldsv @szaimen since it doesn't seem @dassio will update this, what's your call: We rebase & review it, or we close it?

**Comment by szaimen** [comment]
> We rebase & review it, or we close it?

I could try to rebase it but question is if we want this since it seems like it was not getting much attention...

Maybe lets also ping @artonge and @CarlSchwan ...

**Comment by artonge** [comment]
Same opinion as @szaimen, @jancborchardt if you think this make sens for Nextcloud then we'll push to have it merged :)

**Comment by jancborchardt** [comment]
Product-wise we don't seem to have gotten requests for it, and I was also unsure about it in the previous pull request. So I'd say we close for now, can always be revived by someone who wants to work on it.

**Comment by gmaxbass** [comment]
Hi,
too I'm in the need to delete files from external storage since my users need to manage big file sizes. I think that moving external files to user's trash bin for deletion is not a working solution neither technically efficient and it's resource/time consuming.
So the alternatives are:

1) Create a ".trash" in each external storage mount

or

2) Enable an option to delete permanently files on external storage without moving them in user's trash bin.

Maybe the second option it's a bit wiser..it'll be up to admin decide or not to enable it and inform their users about it.

I think that this needs to be fixed.

**Comment by kevinkk525** [comment]
+1 same for my setup.

**Comment by ryester19** [comment]
This would be useful for my setup, also. I use external S3 storage for very large files that gets deleted regularly, and having the deletes move it to my smaller primary storage is often a burden

**Comment by Oriann** [comment]
How is it going ? My files from external storage still move to local trash bin..

**Comment by Grubersky** [comment]
Was happy to see that this problem got addressed, but sad to see that it didn't make it all the way in the end. I do understand why, though. Still hoping that this feature makes it at some point into Nextcloud.

**Comment by labor4** [comment]
Very sorry too to see this fading.

We do video filesharing, usually with multiples of GB filesizes, on multiple of filesystems (for backup tiering).
Earlier we just disabled the "Deleted Files" App to prevent system hangups. But in the current NC version this produces missing-class errors.

**Moving GBs of trash across FS'es is no comfort, because it is so very heavy.**
An in-FS rename should do this.

**Having a .trash bin on each filesystem is a very old concept, proven and very fast.**
Yes, it requires a transparent merge in the GUI, cross-FS, but the underlying reason is essential.

Otherwise there is a strong need to safely disable the trash completely, without errors.

Thank you.

**Comment by albert-a** [comment]
Indeed, in every storage system I've dealt with, deletions are done by moving items to a trash folder on the same file system, rather than copying them anywhere. I'm surprised that NC does things differently. I really wish it were implemented!

Like many of the people mentioned above, I too have a small, fast NC setup on NVMe with attached storage, and deletions quickly eat up the free space on the system disk.

**Comment by jancborchardt** [comment]
Since this is now indeed requested a lot, it’s something to re-evaluate @sorbaugh @AndyScherzinger

**Comment by Oriann** [comment]
I wish this will be worked out soon. I have a terabytes of videos and moving them to trash bin to another (smaller) fs is a really big problem. I look forward to improving this.

**Comment by albert-a** [comment]
I'm just writing to say that  it is still relevant. My Nextcloud instance hangs about every 3 weeks (root disk is full):
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```
Desktop client shows:
Screenshot 2024-09-11 at 21 18 56

The way I resolve it: 
- I extend the root disk a little
- Now the users are able to login to Nextcloud and empty their trashes.
- Breath normally :)

**Comment by Gugiman** [comment]
Just for pushing the need for this feature, I also suffer from files beeing downloaded from external filesystem to the smaller local one...
Also I'm paying for every GB i downloaded from my S3 Storage...

So there is also a monetary reason for this.

**Comment by sorbaugh** [comment]
Fyi this topic has gained a lot of traction lately, we looked into reopening this PR but due to the frontend having been migrated to vue and a few other backend-side nitpicks, it would be better to create a PR from scratch.

Still, thank you very much for this! It motivated us to re-discuss this topic which will definitely make Nextcloud better!

**Pull request closed without merging**
