### PR TITLE
Don't perform CSRF check on OCS routes with Bearer auth

### LINKED ISSUE #5694: Remove (additional) CSRF check from public endpoints if a Bearer authentication header is present (OAuth 2)
OCS APIs cannot be used in a straightforward way if OAuth-authenticated clients perform requests, due to CSRF checks. If a Bearer authentication header is present, it should be sufficient to assume that no CSRF attack takes place. As discussed below in this thread, it would be great if additional CSRF checks were disabled if requests are authenticated by a bearer token.

(Edited on 2017-08-07, 2:53 pm) -- Original Text:

> If you add Nextcloud as an OAuth 2 service provider to a Moodle (3.3) installation, Moodle's OAuth API queries a `userinfo_endpoint` in order to obtain information about the authorising Nextcloud user. This fails since such an endpoint does not exist. Although actually from the OpenID spec, such an endpoint is useful to find out who was just logged in. It is also useful to check whether an access token is still valid without actually performing an operation on files. :)
> 
> Specs for the userinfo endpoint: https://openid.net/specs/openid-connect-core-1_0.html#UserInfo (general) and https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse (response).
> 
> Elements of the response can be: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims, of which `sub` is a MUST (identifier of a Nextcloud user; what do you suggest? ID or username?). Moodle currently relies on a username and an email being present in the userinfo response. I already found out that you do not necessarily know an email adress, so I reported this there: https://tracker.moodle.org/browse/MDL-59511. I would suggest that you add an email address if it is known, instead of mocking one.

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #5694

Todo:
- [x] Validate if this works
  - [x] @daita has it working :balloon: 
  - [x] @pierreozoux has it working too
  - [x] @Dagefoerde has it working as well :)
- [x] Fix tests
- [x] Extend tests

@daita please verify
@Dagefoerde could you also check this out? THNX.

### CODE REVIEW

**Comment by daita** [comment]
clean nc14 (with the fix)+moodle34+plugin for moodle from owncloud :


nextcloud.log:
```
 {
  "reqId": "0RVGuWfh1lauoLRxJaXi",
  "level": 2,
  "time": "2018-01-16T10:54:30+00:00",
  "remoteAddr": "165.90.126.124",
  "user": "--",
  "app": "core",
  "method": "POST",
  "url": "/index.php/apps/oauth2/api/v1/token",
  "message": "Login failed: 'MQvMykk8q2JuLDs8tuMx6gRpDmOiyS7AqZl0f8PJ8bimg33SQ6bAuLMMuoDkFeYz' (Remote IP: '165.90.126.124')",
  "userAgent": "MoodleBot/1.0",
  "version": "14.0.0.0"
}
```


apache:
```
165.90.126.124 - - [16/Jan/2018:10:54:24 +0000] "GET /index.php/apps/oauth2/authorize?client_id=MQvMykk8q2JuLDs8tuMx6gRpDmOiyS7AqZl0f8PJ8bimg33SQ6bAuLMMuoDkFeYz&response_type=code&redirect_uri=http%3A%2F%2Fmoodle%2Fadmin%2Foauth2callback.php&state=%2Frepository%2Frepository_callback.php%3Fcallback%3Dyes%26repo_id%3D19%26sesskey%3DkHGEq3wjlO&scope=openid%20profile%20email%20files%20ocs HTTP/2.0" 303 -
165.90.126.124 - - [16/Jan/2018:10:54:24 +0000] "GET /index.php/login/flow?clientIdentifier=MQvMykk8q2JuLDs8tuMx6gRpDmOiyS7AqZl0f8PJ8bimg33SQ6bAuLMMuoDkFeYz HTTP/2.0" 200 2912
165.90.126.124 - - [16/Jan/2018:10:54:25 +0000] "GET /core/css/login/authpicker.css?v=ad8161bf-0 HTTP/2.0" 200 146
165.90.126.124 - - [16/Jan/2018:10:54:25 +0000] "GET /core/css/guest.css?v=ad8161bf-0 HTTP/2.0" 200 4758
165.90.126.124 - - [16/Jan/2018:10:54:25 +0000] "GET /core/js/login/authpicker.js?v=ad8161bf-0 HTTP/2.0" 200 274
165.90.126.124 - - [16/Jan/2018:10:54:26 +0000] "GET /core/img/background.jpg?v=0 HTTP/2.0" 302 -
165.90.126.124 - - [16/Jan/2018:10:54:26 +0000] "GET /core/img/actions/confirm-white.svg?v=2 HTTP/2.0" 200 405
165.90.126.124 - - [16/Jan/2018:10:54:26 +0000] "GET /index.php/apps/files/ HTTP/2.0" 200 5912
165.90.126.124 - - [16/Jan/2018:10:54:28 +0000] "GET /index.php/login/flow/redirect?stateToken=Mj1KtGayVkdRVUFN4kSv5mcL6KoIfdLyK88nPxrafCSiTy6EuY3xqurhaq2QrhgQ&clientIdentifier=MQvMykk8q2JuLDs8tuMx6gRpDmOiyS7AqZl0f8PJ8bimg33SQ6bAuLMMuoDkFeYz&oauthState=/repository/repository_callback.php%3Fcallback%3Dyes%26repo_id%3D19%26sesskey%3DkHGEq3wjlO HTTP/2.0" 200 2709
165.90.126.124 - - [16/Jan/2018:10:54:28 +0000] "GET /core/js/login/redirect.js?v=ad8161bf-0 HTTP/2.0" 200 102
165.90.126.124 - - [16/Jan/2018:10:54:28 +0000] "GET /core/img/background.jpg?v=0 HTTP/2.0" 302 -
165.90.126.124 - - [16/Jan/2018:10:54:29 +0000] "POST /index.php/login/flow HTTP/2.0" 303 -
165.90.126.124 - - [16/Jan/2018:10:54:29 +0000] "GET /index.php/apps/files/ HTTP/2.0" 401 43
165.90.126.124 - MQvMykk8q2JuLDs8tuMx6gRpDmOiyS7AqZl0f8PJ8bimg33SQ6bAuLMMuoDkFeYz [16/Jan/2018:10:54:30 +0000] "POST /index.php/apps/oauth2/api/v1/token HTTP/1.1" 200 296
165.90.126.124 - - [16/Jan/2018:10:54:31 +0000] "PROPFIND /index.php/remote.php/webdav/ HTTP/1.1" 405 -
165.90.126.124 - - [16/Jan/2018:10:54:35 +0000] "PROPFIND /index.php/remote.php/webdav/ HTTP/1.1" 405 -

```

**Comment by daita** [comment]
nevermind, wrong endpoint for the webdav

**Comment by rullzer** [comment]
@pierreozoux maybe you can test this as well?

**Comment by pierreozoux** [comment]
I confirm it works! Thanks for the proper fix :)
(sorry, I'm a bit new to this code, so it is difficult for me, I thought that it was not that much of a big deal to allow people on this route :) )

**Comment by rullzer** [comment]
@pierreozoux thanks for testing! And also thanks for your first PR, getting to know the code indeed takes time. Looking forward to the next one :smile: !

**Comment by Dagefoerde** [comment]
Hi @rullzer, I tested your fix and it seems to work ok on Nextcloud 12.0.5 (+applied patch) in combination with the Moodle plugin. Thanks a lot for fixing this issue!! :+1: 

Some general remarks:
 * Why limit this to requests to `OCSController`? If requests are authenticated via a Bearer token then we can rule out CSRF issues. I feel that this should be extended towards all endpoints, not just OCS ones.
 * Is the documentation on the OCS API outdated?  [NC 12 docs](https://docs.nextcloud.com/server/12/developer_manual/core/externalapi.html#output) and [NC 13 docs](https://docs.nextcloud.com/server/13/developer_manual/core/externalapi.html#output) say that the response format defaults to XML, but without the `format=xml` parameter the returned result was JSON. Of course this will lead to problems with our users as we assumed that the specification was correct and therefore relied on XML. Or am I experiencing a configuration issue? (unlikely as this was a fresh install of Nextcloud).
* https://github.com/nextcloud/server/pull/7873/files#diff-0bb5cca5abd6cda96b669c31856a3f59R174 says that "we allow Bearer authenticated requests **to fail** on OCS routes", but it's the check that we allow to fail (but we let the request succeed regardless).

**Comment by rullzer** [comment]
@Dagefoerde thanks for testing!

> Why limit this to requests to OCSController? If requests are authenticated via a Bearer token then we can rule out CSRF issues. I feel that this should be extended towards all endpoints, not just OCS ones.

Because basically the OCS endpoints and the webdav endpoints are the 'official' endpoints we use. If you need more we can look into it. But I'd like to keep the rest of the system as locked down as possible ;)

> Is the documentation on the OCS API outdated? NC 12 docs and NC 13 docs say that the response format defaults to XML, but without the format=xml parameter the returned result was JSON. Of course this will lead to problems with our users as we assumed that the specification was correct and therefore relied on XML. Or am I experiencing a configuration issue? (unlikely as this was a fresh install of Nextcloud).

Mmmm maybe you set Accept headers?
Can you show me the call you made?

> https://github.com/nextcloud/server/pull/7873/files#diff-0bb5cca5abd6cda96b669c31856a3f59R174 says that "we allow Bearer authenticated requests to fail on OCS routes", but it's the check that we allow to fail (but we let the request succeed regardless).

My bad. Fixed!

**Comment by Dagefoerde** [comment]
> If you need more we can look into it.

Not yet, but thank you. This was just intended as a general remark because I was wondering what would be the "right" extent of this patch.

> Mmmm maybe you set Accept headers?
> Can you show me the call you made?

Fair enough. Moodle's API sets an accept header (see below). Does Nextcloud use the value of this header? Thanks for the hint, I should be able to change that.
```
‌array (
  0 => 'Content-type: multipart/form-data',
  1 => 'Authorization: Bearer <>',
  2 => 'Accept: application/json',
)
```

**Comment by rullzer** [comment]
Yes we use the accept header :) I shall fire of an issue to the doc repo to clarify this

**Review by MorrisJobke — APPROVED** [review]

**Comment by rullzer** [comment]
https://github.com/nextcloud/documentation/pull/659

**Comment by nickvergessen** [comment]
Fine by me 👍

**Comment by MorrisJobke** [comment]
@rullzer Backport to stable13?

**Pull request merged**
