### PR TITLE
Report ui regression status to github api

### PR DESCRIPTION
**Pull request by juliusknorr**
Replaces #10507 

- [x] Fix server container to work with current master
- [ ] Fix tests
  - [ ] Create share link
  - [ ] Unshare link

### CODE REVIEW

**Comment by juliushaertl** [comment]
@rullzer Any idea if the github api key that is setup in drone is from the nextcloud-bot? Can you check if it has `repo:status` permissions, so we can set the pull request status for the regression tests?

**Comment by rullzer** [comment]
@juliushaertl I'm not sure what API key is used to do that... it is a normal OAuth token I think

**Comment by juliushaertl** [comment]
@rullzer The github_token secret in drone for the server repo needs to have that permission. Since it is manually set, I thought it might be one from the nextcloud bot, where we can just enable the repo:status permission in the github access token settings.

**Comment by MorrisJobke** [comment]
> @rullzer The github_token secret in drone for the server repo needs to have that permission. Since it is manually set, I thought it might be one from the nextcloud bot, where we can just enable the repo:status permission in the github access token settings.

Done :)

**Comment by rullzer** [comment]
@juliushaertl what si the status here?

**Comment by juliushaertl** [comment]
@MorrisJobke Maybe you can check again? Either the token used in drone for nextcloud/server is some different or it doesn't have the permissions, as it keeps returning a 404 (which is what github returns if not properly authenticated https://developer.github.com/v3/#authentication)

**Comment by MorrisJobke** [comment]
> @MorrisJobke Maybe you can check again? Either the token used in drone for nextcloud/server is some different or it doesn't have the permissions, as it keeps returning a 404 (which is what github returns if not properly authenticated https://developer.github.com/v3/#authentication)

But it has this permission:

bildschirmfoto 2019-01-16 um 17 31 15


Also the documentation does only state that this is the only required one: https://developer.github.com/v3/repos/statuses/#create-a-status

**Comment by MorrisJobke** [comment]
@juliushaertl What is missing here?

**Comment by juliushaertl** [comment]
The actual tests are broken right now, probably due to the webpack bundling. I'll put this on my list for next week.

**Comment by skjnldsv** [comment]
> 4 hours ago

He's back! :tada: :bowing_woman: :grin:

**Comment by MorrisJobke** [comment]
For drone 1.0 the secrets need to be exposed via ENV variables: https://docs.drone.io/user-guide/secrets/pre-repository/

**Comment by rullzer** [comment]
I'm going to close this for now.
@juliushaertl feel free to reopen if you have time to work on this again.

**Pull request closed without merging**
