### PR TITLE
[stable14] Add pipe mode for sendmail

### PR DESCRIPTION
**Pull request by ChristophWurst**
(squashed) backport of https://github.com/nextcloud/server/pull/12424

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Restarted CI: https://drone.nextcloud.com/nextcloud/server/13482

**Comment by danielkesselberg** [comment]
Fixed failing unit tests (https://github.com/nextcloud/server/commit/876ee05b36bb79e8aa8334fa9303f295c9c44137), rebased and signed-off.

**Pull request merged**
