### PR TITLE
fix(settings): Align contents of profile picture heading

### LINKED ISSUE #48411: Profile settings: Profile image visiblity button not aligned
The visibility button for the profile image is not aligned with the text like the other.

image

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Fix https://github.com/nextcloud/server/issues/48411

Before | After
--- | ---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Aminzarbani** [comment]
#2

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
@Pytal conflicts :pensive:

**Comment by Aminzarbani** [comment]
aminzarmani7@gmail.com

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
