### PR TITLE
Support seeking also from the end of file on S3 storage

### PR DESCRIPTION
**Pull request by paulijar**
The PR https://github.com/nextcloud/server/pull/20033 added support for `fseek` for  the S3 storage backend. However, the seek mode SEEK_END was left out that time. This PR adds this support.

The motivation for this was that the getID3 library uses the seek mode SEEK_END and doesn't work properly without it. After the PR https://github.com/JamesHeinrich/getID3/pull/328 got merged, the getID3 library no longer works at all on file system where `fseek` returns error with any used seek mode. This was the root cause for the issue https://github.com/owncloud/music/issues/887.

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
Thanks :+1:

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure unrelated

**Comment by kesselb** [comment]
does it make sense to backport?

**Comment by paulijar** [comment]
> does it make sense to backport?

In my opinion, yes. This fixes an actual problem, and the patch should be applicable all the way starting from NC17.

**Comment by paulijar** [comment]
So who should decide if this gets backported?

**Pull request merged**
