### PR TITLE
Changed anchor

### LINKED ISSUE #2711: Personal settings page wrong anchor
Hi!
The anchor for personal information is wrong. it's `#avatar` but should be `#personal-settings` [link](https://github.com/nextcloud/server/blob/master/settings/templates/personal.php#L35)

NC: 11

### PR DESCRIPTION
**Pull request by amittel**
from `avatar` to `personal-settings`

fixes #2711

Signed-off-by: Arnulf Mittelstädt <arnulf.mittelstaedt@gmail.com>

### CODE REVIEW

**Comment by MariusBluem** [comment]
Thank you 🎉 Please see: https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md (Sign your work) 🙈

**Comment by MariusBluem** [comment]
Mention bot not working 😱 Let me do this for him 😅 @schiessle

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Failing tests are my fault and already fixed on current master.

**Comment by jancborchardt** [comment]
Awesome stuff @amittel, thanks for the report and the fast fix! :) Welcome to Nextcloud :tada:

**Comment by MariusBluem** [comment]
Merged without signed-off is now possible?! @rullzer

**Comment by MariusBluem** [comment]
Backport? @karlitschek

**Comment by LukasReschke** [comment]
> Merged without signed-off is now possible?! @rullzer 

1 line changes have no copyright (=> Schöpfungshöhe) and thus in this case I consider it more effective to just merge instead of getting into a repeating limbo about how to sign stuff :)

**Comment by MariusBluem** [comment]
> 1 line changes have no copyright and thus in this case I consider it more effective to just merge instead of getting into a repeating limbo about how to sign stuff :)

Did not know that we can merge small commits without 😅

**Comment by jancborchardt** [comment]
Yes, below 7 lines is considered exempt. And signing is quite a barrier for new contributors so it’s unneeded hassle we shouldn’t put people through if we want to be welcoming. ;)

**Comment by karlitschek** [comment]
please backport 👍

**Comment by MorrisJobke** [comment]
> please backport 👍

Done in #2805

**Pull request merged**
