### PR TITLE
Fixed date/time picker on IE11

### LINKED ISSUE #8484: The date packer does not show the day of the month in IE
### Steps to reproduce
1. open  site in ver 13 with IE 11
2. Goto either contacts or share files and choose a date field 
3. Using the pick a date field the days of the month that have more than 1 digit the second digit is blocked. 

### Expected behaviour
Tell us what should happen
the day of the month should be available    ie   12 , 22 
### Actual behavior
The data shows as 1.. or 2.. 
Tell us what happens instead

### Server configuration
clean vev 13 install or a upgraded version from 12
**Operating system**:
ubunto
**Web server:**
apachie 7 
**Database:**
my sql 
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
both 
**Where did you install Nextcloud from:**
techandme.com as a VM 
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
both
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
IE 11
**Operating system:**
windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #8484 @nextcloud/designers @jpimlott

|Before|After|
|:--:|:--:|
|virtualbox_ie11 - win7_01_03_2018_21_36_03|virtualbox_ie11 - win7_01_03_2018_21_36_05|
|virtualbox_ie11 - win7_01_03_2018_21_42_56|virtualbox_ie11 - win7_01_03_2018_21_35_52|

### CODE REVIEW

**Comment by pixelipo** [comment]
Sorry @skjnldsv - I'm not able to test on IE11. Code looks ok, though

**Review by MorrisJobke — APPROVED** [review]
tested and works 👍

**Comment by MorrisJobke** [comment]
@skjnldsv Could you open a Backport PR?

**Comment by skjnldsv** [comment]
Of course!

**Comment by skjnldsv** [comment]
Backport of https://github.com/nextcloud/server/pull/8663

**Pull request merged**
