### PR TITLE
Fix TypeError on large folder downloads

### PR DESCRIPTION
**Pull request by j-be**
As requested in #15117, here a PR for discussion.

Additionally, I propose to add Linux to the `preferTarFor` user agent matches.

Please note the `TODO`: I would not consider this PR ready to be merged until that is fixed.

### CODE REVIEW

**Comment by szaimen** [comment]
cc @ChristophWurst @juliushaertl @nickvergessen for input on this

**Comment by ChristophWurst** [comment]
> cc @ChristophWurst @juliushaertl @nickvergessen for feedback on this

FYI I do mostly auth, APIs and dependencies in the server repo :)

**Review by skjnldsv — APPROVED** [review]
Code looks good to me
A bit of testing would be nice :)

**Comment by j-be** [comment]
@skjnldsv I'm more than happy to help, but I have not written PHP since high school (must have been PHP4 or early PHP5 - can't really remember). So I'm not sure if I am more help than hazard here :smile:

I am currently running the "smaller" fix using `TarStreamer` for anything that doesn't fit Zip32 on my Nextcloud, as I only need to support Linux (personal use only). Finally, my server is an Odroid HC-2 (i.e. ARMv7 32Bit), so I may not even be able to manually test Zip64, assuming https://github.com/McNetic/PHPZipStreamer/issues/38 is still accurate.

**Comment by szaimen** [comment]
What is missing here?

**Comment by j-be** [comment]
@szaimen I wrote this fix off the top of my head - and I have not written anything substantial in PHP for about a decade. Also, the code is untested.

I created the PR as a base for discussion, as requested in #15117. If you guys think the code is good enough to be merged, I will obviously not object. But I advice extra caution 😄

**Comment by blizzz** [comment]
What's the state here?

**Comment by j-be** [comment]
@blizzz @skjnldsv Is there anything I can contribute to get this merged?

**Comment by szaimen** [comment]
sorry for the delay. We discussed this internally and decided that it should not be done like this. There should rather be a config option which allows the admin to specify the archive format. cc @skjnldsv @PVince81 @nickvergessen

**Comment by j-be** [comment]
@szaimen no worries 😃 

That sounds like a good idea. Feel free to close this PR if it is not needed anymore.

**Comment by nfp0** [comment]
@szaimen Sounds good.
Is there a place where I can follow that feature to know when it lands?

**Comment by MichaIng** [comment]
Probably not relevant anymore due to: https://github.com/nextcloud/documentation/pull/9071

But I like the idea to have an option for specifying the archive format. zip is really the worst possible option, as long as you don't run one of these Windows systems without any proper archiver installed.

**Comment by skjnldsv** [comment]
> https://github.com/nextcloud/server/pull/27562#issuecomment-1088881536

Closing then

**Comment by j-be** [comment]
@skjnldsv For the record: the issue is still present on 32 Bit machines. But taken this is now over 2 and a half years old and I see there is no interest in tackling this, I am beyond caring.

To close some honest feedback: Trying to contribute to the project sucks. My working PR was declined for alternative solution, which never materialized leaving the actual issue present to this day.

**Comment by MichaIng** [comment]
@j-be are you sure it is still an issue? I just successfully downloaded a 2.4 GiB directory from my NC 28.0.1, hosted on a Raspberry Pi 2 ARMv7 with 32-bit Linux OS.

**Comment by j-be** [comment]
@MichaIng Not entirely sure as I am applying my patch (i.e. this PR) on every update of Nextcloud.

Did you try to download a folder, that will lead to a Zip bigger than 4GB from non Mac (it will correctly fall back to Tar only on MacOSX, not on Windows and Linux)? I feel like you should end up with either an error, or an invalid Zip file.

**Comment by MichaIng** [comment]
I just downloaded a 4.3 GiB archive, packaged as 4.1 GiB sized zip archive. It is all complete.

There have been a number of 32-bit bit related fixes, after it broke completely with NC25 (IIRC), after which 32-bit support was aimed to be removed, and then the decision was reverted, with fixed 32-bit support in NC26. This included fixes for old 32-bit issues, like downloads and trashbin.

**Comment by j-be** [comment]
@MichaIng That is very weird. If you look at the comment in the constructor of https://github.com/nextcloud/server/blob/master/lib/private/Streamer.php it would indicate, that a Zip32 file with more than 4GB should not be valid. But assuming `PHP_INT_SIZE` is `4` on 32 bit would mean, that a 32 Bit instance of Nextcloud would always create a Zip32 archive for Windows and Linux, regardless of size or content.

I seem to remember I saw somewhere, that the used library cannot create Zip64 files on 32Bit machines (not sure why, never cared), which is why the Tar thingy is there to begin with.

Am I missing something, or how is it possible this code produces a valid Zip archive with more than 4GB content on a 32Bit machine?

**Comment by MichaIng** [comment]
Hmm, strange indeed. This interface is definitely used? The condition to set `zip64` to false should definitely apply and the overall size was above 4 GB:
```sh
root@micha:~# php -r 'echo PHP_INT_SIZE . PHP_EOL;'
4
```
I could add some debug code to just verify that this particular condition was met/code line reached, just to be sure. And is there a way to check the format of the downloaded zip? I'll just re-download it and see.

I find this "32-bit workaround" strange anyway. I mean if the size is above 4 GB (first condition is false), and 32-bit zips are really not able to contain >4 GiB data, then NC shouldn't try to generate that zip in the first place. But it just generates a 32-bit zip then. So either 32-bit zips are able to contain data >4 GiB size, or this is complete nonsense. The comments above the code indicate that it is complete nonsense, but on the other hand, for me it just works.

Actually I do not understand either why a 32-bit zip is used when the size is below 4 GB, as even the comments state that it can fail when the "central directory" is larger (whatever this is). Is there any benefit of 32-bit zip over 64-bit zip? Otherwise, on non-mac (what about Linux clients?), why not use 64-bit zip always and disable it for 32-bit servers only?

**Comment by MichaIng** [comment]
I just tested a tarball download, and that one was complete. So we can use that as fallback for larger directories on 32-bit servers. Not sure about the max number of files there, but that should be a rare case compared to the max size.

So taking everything together, unless someone finds time for proper GUI adjustments (GUI error message, archive type selector etc) NOW, I suggest this quick "fix":
```php
		// Use TAR if preferred, it does support > 4 GiB on 32-bit servers
		if ($request->isUserAgent($this->preferTarFor)) {
			$this->streamerInstance = new TarStreamer();
		// 32-bit server
		} elseif (PHP_INT_SIZE !== 4) {
			// Use 32-bit zip if size and numberOfFiles allow it
			if ($size > 0 && $size < 4 * 1000 ** 3 && $numberOfFiles < 65536) {
				$this->streamerInstance = new ZipStreamer(['zip64' => false]);
			} else {
				<log info that zip archives with > 4 GiB data or > 65535 files are not supported on 32-bit systems, and an uncompressed TAR archive is downloaded instead>
				$this->streamerInstance = new TarStreamer();
			}
		// 64-bit server: Use 64-bit zip, respectively whatever the streamer does by default in this case
		} else {
				$this->streamerInstance = new ZipStreamer();
		}
```
Since the tarball is completely uncompressed, I would not add further client to prefer it. Not sure whether zip is really so badly supported on Apple systems, but we might even want to prefer zip in every case, and use the raw tarball really only as fallback for large directories on 32-bit systems? For smaller directories it is already the case now, so this would mean a change only for large directories, where the compression is even more reasonable.

**Pull request closed without merging**
