### PR TITLE
Increase the fair-use push limit to 1.000 users

### PR DESCRIPTION
**Pull request by nickvergessen**
As discussed

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by AndyScherzinger** [comment]
@nickvergessen backports would be needed below 25 too, no?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/33770

No 25+

**Pull request merged**
