### PR TITLE
Setupfs before access a users keys

### PR DESCRIPTION
**Pull request by MorrisJobke**
* downstream of https://github.com/owncloud/core/pull/26917

@icewind1991 @schiessle Please check this one out

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> @icewind1991 @schiessle Please check this one out

Ping

**Review by schiessle — APPROVED** [review]
I could verify the issue and that this PR fixes it. Code looks good to me

**Comment by schiessle** [comment]
I would recommend to backport it at least to Nextcloud 11 and 12.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@schiessle Could you have a look at the failing tests:

```
There were 2 errors:
887s
91
1) Test\Encryption\Keys\StorageTest::testBackupUserKeys with data set #0 (true)
TypeError: Argument 3 passed to OC\Encryption\Keys\Storage::__construct() must implement interface OCP\IUserSession, none given
/drone/src/github.com/nextcloud/server/lib/private/Encryption/Keys/Storage.php:70
/drone/src/github.com/nextcloud/server/tests/lib/Encryption/Keys/StorageTest.php:580
2) Test\Encryption\Keys\StorageTest::testBackupUserKeys with data set #1 (false)
TypeError: Argument 3 passed to OC\Encryption\Keys\Storage::__construct() must implement interface OCP\IUserSession, none given
/drone/src/github.com/nextcloud/server/lib/private/Encryption/Keys/Storage.php:70
/drone/src/github.com/nextcloud/server/tests/lib/Encryption/Keys/StorageTest.php:580
```

**Comment by nickvergessen** [comment]
will this kill performance on creating files, etc? Because we set up the filesystem for all recipients to get their keys?

**Comment by MorrisJobke** [comment]
Out of scope for 12 I think

**Comment by MorrisJobke** [comment]
> @schiessle Could you have a look at the failing tests:

@schiessle 🏓

**Pull request closed without merging**
