### PR TITLE
Set headings to Semibold for better information architecture

### PR DESCRIPTION
**Pull request by jancborchardt**
See for yourself @nextcloud/designers – much better to distinguish and see what is in focus:

Before & after in files:
screenshot from 2018-10-02 11-37-51
screenshot from 2018-10-02 11-37-03

Before and after in admin settings:
screenshot from 2018-10-02 12-03-04
screenshot from 2018-10-02 12-01-12

### CODE REVIEW

**Comment by jancborchardt** [comment]
Also cc @karlitschek @jospoortvliet – it's something we should also consider for the website and other materials.

**Comment by skjnldsv** [comment]
I have to disagree again. This feels out of place. :confused: 
It looks like you've changed the font family. Maybe try regular? Or something like that?
It looks like we've gone too far here. 

I agree with the concept, but this looks worst than before :wink: 
dkgk-ibueae58ll

**Comment by jancborchardt** [comment]
@skjnldsv maybe you'd prefer if in the settings it stays h2? Just cherry-pick only the first commit.

**Comment by MorrisJobke** [comment]
> EDIT: precision: I'm talking about the headings on the personal settings :)

We also noticed that and were thinking about making it not a heading there but normal text. But all the other settings look far better

**Comment by skjnldsv** [comment]
> @skjnldsv maybe you'd prefer if in the settings it stays h2? Just cherry-pick only the first commit.
> 
> And no, the fon-family isn't changed as you can see from the code. It's simply semibild, what we use for highlights and buttons already.

No, actually I think I prefere without the bold, only going back to  the original weight.
BUT without the lightness, so `font-weight: 300`
capture d ecran_2018-10-02_12-27-25

What do you think? It doesn't draw that much attention, but is still perfectly readable (far better than the previous light) :)

**Comment by pixelipo** [comment]
Or perhaps try with bold, but leave opacity at .57?

I agree about the visibility - something definitely needs to be done here, but bold&black stands out too much. We seem to lose this light, airy feeling that NC interface has.

@jancborchardt - I think you tagged screenshots incorrectly -> personal are described as admin and vice versa.

@MorrisJobke - related to :arrow_up: which headings are you referring to?

**Review by ChristophWurst — APPROVED** [review]
Yesssssss

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I like this a lot 👍 Especially on settings pages with a lot of a text between the sections it makes the layout more readable and easier to scan quickly.

**Review by weeman1337 — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by pixelipo — APPROVED** [review]

**Pull request merged**
