### PR TITLE
add dav plugin to trigger recalculating of checksums

### PR DESCRIPTION
**Pull request by icewind1991**
Allows clients to ask the server to recalculate the stored checksums by sending a `PATCH` request with the `X-Recalculate-Hash` hash set.

For example

    curl -X PATCH -u admin:admin -H 'X-Recalculate-Hash: sha1' https://cloud.example.com/remote.php/dav/files/admin/test.md

This will both update the stored checksum using the provided algorithm and return the new checksum in the `OC-Checksum` header

cc @allexzander

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Comment by nickvergessen** [comment]
@icewind1991 mind to have a look at the code scanner warnings?

**Comment by icewind1991** [comment]
ci happu

**Comment by PVince81** [comment]
> ci happy

the code scanner issues are still there like missing return types

**Comment by allexzander** [comment]
@icewind1991 I wonder if this needs to be followed up?

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Damn, that was a feature, not a bugfix, should not have merged, reverting and postponing for 24

**Pull request merged**
