### PR TITLE
Code style changes from downstream

### PR DESCRIPTION
**Pull request by MorrisJobke**
- downstreams owncloud/core#26366 
- it only contains namespacing and code style changes to streamline upstream code base with our code base
- backport of this is not needed

cc @rullzer @nickvergessen @icewind1991

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Our fix for this issue is in:

11: https://github.com/nextcloud/server/pull/1740
10: https://github.com/nextcloud/server/pull/1798
9: https://github.com/nextcloud/server/pull/1799

**Comment by nickvergessen** [comment]
Fine by me, but as said. No backport

**Comment by MorrisJobke** [comment]
> Fine by me, but as said. No backport

Is this a +1 then? 😉

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
I tested this and it works 👍

**Pull request merged**
