### PR TITLE
27.1.0 RC1

### PR DESCRIPTION
**Pull request by blizzz**
* #39728
* #39900
* #40032
* #40034
* #40039
* #40045
* #40060
* #40062
* #40066
* #40074
* #40078
* #40080
* #40081
* #40101
* #40162
* #40175
* #40179
* nextcloud/nextcloud_announcements#229
* nextcloud/notifications#1650
* nextcloud/text#4704
* nextcloud/text#4731
* nextcloud/text#4737
* nextcloud/text#4738
* nextcloud/text#4739
* nextcloud/text#4748
* nextcloud/viewer#1907
* nextcloud/viewer#1908
* nextcloud/viewer#1933
* nextcloud/viewer#1937

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
We currently try to get the new share flow merged for RC1. So please align with @artonge and @Fenn-CS on the packaging time of RC1 please. 🙏

**Comment by blizzz** [comment]
> We currently try to get the new share flow merged for RC1. So please align with @artonge and @Fenn-CS on the packaging time of RC1 please. 🙏

do we have a PR?

**Comment by AndyScherzinger** [comment]
> do we have a PR?

https://github.com/nextcloud/server/pull/39472 is the `master`-targeting PR, we do not yet have a backport for `stable27` since the polishing work is still ongoing. So direct communication with the devs might work best. I'll add them to the release talk room.

**Comment by blizzz** [comment]
> I added the PR in a dedicated section.

This will be overwritten by script. I add another comment.

**Comment by blizzz** [comment]
## Watiting for backport (Hub feature)
  * [ ] https://github.com/nextcloud/server/pull/39472

**Comment by artonge** [comment]
> ## Watiting for backport (Hub feature)
> 
>     * [ ]  [Improve sharing flow #39472](https://github.com/nextcloud/server/pull/39472)

The PR is merged. The backport was accidentally pushed to stable27. CI is mostly green, beside drone, as sharing tests need to be removed. Sorry for that.

**Comment by blizzz** [comment]
> > ## Watiting for backport (Hub feature)
> > ```
> > * [ ]  [Improve sharing flow #39472](https://github.com/nextcloud/server/pull/39472)
> > ```
> 
> The PR is merged. The backport was accidentally pushed to stable27. CI is mostly green, beside drone, as sharing tests need to be removed. Sorry for that.

@artonge the tests are failing on stable27. Please revert the commit on stable27 and let's follow the regular PR approach

**Pull request merged**
