### PR TITLE
[stable28] chore(deps): Bump calendar-availability-vue from 2.1.0 to 2.2.0

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Bump `calendar-availability-vue` from `2.1.0` to `2.2.0`

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]

**Comment by emoral435** [comment]
checked - despite getting the thumbs down, the bot did indeed compile things correctly 👍

**Comment by ShGKme** [comment]
> the bot did indeed compile things correctly 👍

Julia has force pushed assets manually 😀

**Pull request merged**
