### PR TITLE
Add border around previews

### PR DESCRIPTION
**Pull request by jancborchardt**
@skjnldsv as discussed, so it looks a bit nicer. I think it was suggested by @jospoortvliet 
grid view border

### CODE REVIEW

**Comment by jancborchardt** [comment]
Once we have this extra class or mechanism, we also need to do this for the Recommendations app cc @ChristophWurst

**Comment by ChristophWurst** [comment]
Looks good for files with preview, but looks a bit strange for the default MIME icons, esp. for folders.

**Comment by jancborchardt** [comment]
@ChristophWurst that’s why it’s set to "Developing" and why I said:

> However it should only be shown for files with generated previews. That is, not for folders and regular filetype icons like here. Do we need to introduce a new class here?

:wink:

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
Btw @Ivansss this is also the CSS code you will need for the border around the previews in the Talk app :) https://github.com/nextcloud/server/pull/14637/commits/e1e65021b105309269e4b2d5a213e23f9904d199

**Comment by jancborchardt** [comment]
Quick review please @nextcloud/designers :)

**Review by MorrisJobke — APPROVED** [review]
Looks a lot better 👍

**Comment by MorrisJobke** [comment]
> * tests/acceptance/features/apps.feature:83

"fixed" in #14681

**Comment by jospoortvliet** [comment]
Very nice, and yeah, I suggested it as I am always taking screenshots, those have a lot of white on sides and bottom and thus look odd without a border ;-)

**Pull request merged**
