### PR TITLE
build(autoloader): Remove noisy changes when regenerating

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

When executing the script all the app/*/composer/composer/installed.php files change as they reference the current HEAD commit hash. To avoid having to manually discard the changes, just drop them automatically.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by artonge — APPROVED** [review]
Is there no option to prevent those updates in the first place?
Approved, as fine with this solution thought.

**Comment by susnux** [comment]
> Is there no option to prevent those updates in the first place?

Skip the `composer install ...` part and only run `composer dump-autoload ...`.

**Comment by provokateurin** [comment]
> Skip the composer install ... part and only run composer dump-autoload ....

I wonder if not doing it could cause any problems. I don't see why we need to do it first before dumping the autoloaders, so we might just get rid of it in the first place?

**Comment by provokateurin** [comment]
> I wonder if not doing it could cause any problems. I don't see why we need to do it first before dumping the autoloaders, so we might just get rid of it in the first place?

I checked and it is necessary, so this is the way to go for now.

**Pull request merged**
