### PR TITLE
perf(autoloading): Add authoritative autoloader for files_external

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Resolves: # 

## Summary

Extracted from https://github.com/nextcloud/server/pull/36112 for green CI.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by skjnldsv** [comment]
Should we also have a dedicated workflow to check for outdated autoloaders here too?

**Comment by ChristophWurst** [comment]
> Should we also have a dedicated workflow to check for outdated autoloaders here too?

https://github.com/nextcloud/server/pull/36112 https://github.com/nextcloud/server/pull/36112/commits/f4ff9083073aee66d360c7c9d0dff7d9208f9364 addresses that.

**Comment by ChristophWurst** [comment]
> Should we also have a dedicated workflow to check for outdated autoloaders here too?

We have a workflow to check for *outdated* workflows. The issue here is that they were missing. And the update script skips apps without an autoloader.

**Comment by ChristophWurst** [comment]
> **Samba Kerberos SSO / kerberos (pull_request) ** Failing after 1m

It wasn't me: https://github.com/nextcloud/server/actions/workflows/smb-kerberos.yml

**Comment by ChristophWurst** [comment]
Shall we do this?

**Comment by ChristophWurst** [comment]
> Failed to connect to localhost port 9000 after 0 ms: Connection refused

**Review by icewind1991 — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
