### PR TITLE
Do not emit UserCreatedEvent twice

### LINKED ISSUE #23797: UserCreatedEvent emitted twice when creating user via user management webui
When creating a user account via the user management web ui, the '\OCP\User\Events\UserCreatedEvent' is emitted twice.

### Steps to reproduce
1. Create a listener for the '\OCP\User\Events\UserCreatedEvent' event and let it log or do something
2. Create a user via the user management webui
3. See the handle function of the listener is called twice

### Expected behaviour
'\OCP\User\Events\UserCreatedEvent' should be emitted once only.

### Actual behaviour
'\OCP\User\Events\UserCreatedEvent' is emitted twice.

### Server configuration
Tested in official docker based Nextcloud 19.0.4 and 20.0.1 

I think this causes the behaviour:
* Emit Hook and Event in UserManager:
https://github.com/nextcloud/server/blob/f94af85749f1c98564c7b4f503a13309a24595fb/lib/private/User/Manager.php#L375-L378
* React on Hook and emit Event a second time:
https://github.com/nextcloud/server/blob/f94af85749f1c98564c7b4f503a13309a24595fb/lib/private/Server.php#L539-L546

If commenting L544-L545of Server.php the listener is only triggerd once.

### PR DESCRIPTION
**Pull request by 7118path**
no more translation from postCreateUser hook to UserCreatedEvent anymore, as event is already emitted in user manager

Fixes https://github.com/nextcloud/server/issues/23797

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
DCO check failed: https://github.com/nextcloud/server/pull/23887/checks?check_run_id=1351716573

Please *sign off* your commit :)

**Review by kesselb — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@ecsecta Mind to also remove the `use` statement for this at the top of the file (that's the complaining code style about).

**Comment by ecsecta** [comment]
Yup, sorry.

**Comment by MorrisJobke** [comment]
> Yup, sorry.

Don't worry - that's what we have the CI jobs for. Reminding us of the easy to forget stuff.

**Comment by MorrisJobke** [comment]
Static code analysis fail is unrelated. That is from a wrong merge from yesterday.

**Comment by MorrisJobke** [comment]
Was added in #18028 and #18348. Also the emit does only happen in this one place so there is no need to translate it (for another app for example) anymore.

**Comment by MorrisJobke** [comment]
Backport in #23917

**Pull request merged**
