### PR TITLE
Only normalize data in public shares and not crud

### PR DESCRIPTION
**Pull request by CarlSchwan**

### CODE REVIEW

**Review by artonge — COMMENTED** [review]
Make sense

I can't find any occurrence of `publicUpload` in our code base, maybe we should deprecate it someday.

**Review by artonge — APPROVED** [review]

**Comment by blizzz** [comment]
@CarlSchwan integration-sharing-v1 failed

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@CarlSchwan please double check the failing sharing tests to see if related

**Comment by CarlSchwan** [comment]
> @CarlSchwan please double check the failing sharing tests to see if related

Tests work locally, so this seems to be a race condition as I saw the share link acceptance tests fail in other PR recently (probably caused by the redesign)

**Comment by mejo-** [comment]
@CarlSchwan are you ok with backporting this to stable24?

**Pull request merged**
