### PR TITLE
[stable17] Do not flood console when uploading files

### PR DESCRIPTION
**Pull request by danxuliu**
[Console logs take some time to be processed](https://jsperf.com/console-log1337/14), even if the developer tools of the browser are closed. The progress bar in the file upload uses deprecated functions whenever the progress is updated, which in big file uploads cause the console to be flooded with messages. In some cases (IE 11) this affects the upload performance and can even cause the upload to fail.

I have replaced the call to `humanFileSize` with `OC.Util.humanFileSize` and also cherry picked the commits to [move to the `escape-html` function from Nextcloud 18](https://github.com/nextcloud/server/pull/17405) (although it would have been enough to import the function in _l10n.js_, but this seemed better for consistency).

Finally I have also cherry picked the [fix for the progress bar tooltip](https://github.com/nextcloud/server/pull/17654).

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by rullzer** [comment]
ci is not happy

**Comment by gary-kim** [comment]
Umm, are you going to be able to delete this branch once you're done? `stable17-do-not-flood-console-when-uploading-files`

**Comment by gary-kim** [comment]
> /compile /

Did it for you

**Comment by skjnldsv** [comment]
> Umm, are you going to be able to delete this branch once you're done? `stable17-do-not-flood-console-when-uploading-files`

We have the admin ring, we can do whatever we want!
csqc

**Pull request merged**
