### PR TITLE
fix(actions): cypress

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix cypress actions for self hosted runners

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Seems to fix it :)

**Comment by szaimen** [comment]
backports?

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
Wait, backports won't be that easy, I think. Let's see wait happen with the first two…

**Comment by szaimen** [comment]
Drone failure unrelated

**Comment by szaimen** [comment]
> Lol, we don't have cypress on 25 folks! 🙈 https://github.com/nextcloud/server/tree/stable25/.github/workflows

Ah sorry 😅

**Pull request merged**
