### PR TITLE
Integration tests refactoring

### PR DESCRIPTION
**Pull request by MorrisJobke**
- a try to downstream https://github.com/owncloud/core/pull/26235 as best as possible

@rullzer Please have a good review of this :)

And first let's see what the CI thinks about it.

### CODE REVIEW

**Comment by rullzer** [comment]
Mmmm I have a feeling that failing test might be a timing issue...

**Comment by rullzer** [comment]
Ok indeed. Race condition. I can explain.
It is about https://github.com/nextcloud/server/blob/bcd7a9a03401dd7eb7ac8ef24a1869dcd9789f67/build/integration/features/sharing-v1.feature#L895-L924

That sometimes fails.

Pre:

* user0 exists
* user1 exists
* user1 is part of group1
* user0 has a folder `before`

Now if the following happens in the same second

1. user0 shares `before` with user1
2. user1 renames `before` to `after`
3. user0 shares `before` with group1

Now at this point the share table will have 2 entries.

1. user share that has as target `/after`
2. group share that has as target `/before`

However since they have the same time the merging logic kicks in. Which takes the group share as primary share.

Now if we flip the logic (which we could) then the reverse scenario would break (first group share then user share). Since we can't really compare id's properly here (abstracted away). The sharetime is really the only thing we have to go on.

Now all that said and done. I really think this scenario is not one that will pop up in real life. And if it does. Well bad luck you have to rename again. So I propose to just add a sleep of a second before sharing it to the group.

@MorrisJobke agreed?

**Comment by rullzer** [comment]
All good now from me. LGTM

**Comment by rullzer** [comment]
All good now from me. LGTM

**Comment by rullzer** [comment]
All good now from me. LGTM

**Comment by MorrisJobke** [comment]
> @MorrisJobke agreed?

:+1:

I'm fine with this now 👍

**Pull request merged**
