### PR TITLE
Header must contain a colon

### LINKED ISSUE #25230: Header must contain a colon at /apps/dav/lib/Connector/PublicAuth.php#114
- NC 20.0.5
- Log getting spammed with:

```
{
   "reqId": "TjkUpasoh5fKyNpuTUxJ",
   "level": 3,
   "user": "--",
   "app": "PHP",
   "method": "PROPFIND",
   "url": "/public.php/webdav/",
   "message": {
      "Exception": "Error",
      "Message": "Header must contain a colon at /apps/dav/lib/Connector/PublicAuth.php#114",
      "Code": 0,
      "Trace": [
         {
            "function": "onError",
            "class": "OC\\Log\\ErrorHandler",
            "type": "::",
            "args": [
               2,
               "Header must contain a colon",
               "/apps/dav/lib/Connector/PublicAuth.php",
               114,
               {
                  "username": "*** sensitive parameter replaced ***",
                  "password": "*** sensitive parameter replaced ***",
                  "share": {
                     "__class__": "OC\\Share20\\Share"
                  }
               }
            ]
         },
         {
            "file": "/apps/dav/lib/Connector/PublicAuth.php",
            "line": 114,
            "function": "header",
            "args": [
               "WWW-Authenticate",
               "DummyBasic realm=\"qerhqrge\""
            ]
         },
         {
            "file": "/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php",
            "line": 106,
            "function": "validateUserPass",
            "class": "OCA\\DAV\\Connector\\PublicAuth",
            "type": "->",
            "args": [
               "*** sensitive parameters replaced ***"
            ]
         },
         {
            "file": "/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php",
            "line": 192,
            "function": "check",
            "class": "Sabre\\DAV\\Auth\\Backend\\AbstractBasic",
            "type": "->",
            "args": [
               {
                  "__class__": "Sabre\\HTTP\\Request"
               },
               {
                  "__class__": "Sabre\\HTTP\\Response"
               }
            ]
         },
         {
            "file": "/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php",
            "line": 144,
            "function": "check",
            "class": "Sabre\\DAV\\Auth\\Plugin",
            "type": "->",
            "args": [
               {
                  "__class__": "Sabre\\HTTP\\Request"
               },
               {
                  "__class__": "Sabre\\HTTP\\Response"
               }
            ]
         },
         {
            "file": "/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line": 89,
            "function": "beforeMethod",
            "class": "Sabre\\DAV\\Auth\\Plugin",
            "type": "->",
            "args": [
               {
                  "__class__": "Sabre\\HTTP\\Request"
               },
               {
                  "__class__": "Sabre\\HTTP\\Response"
               }
            ]
         },
         {
            "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 458,
            "function": "emit",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": [
               "beforeMethod:PROPFIND",
               [
                  {
                     "__class__": "Sabre\\HTTP\\Request"
                  },
                  {
                     "__class__": "Sabre\\HTTP\\Response"
                  }
               ]
            ]
         },
         {
            "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 251,
            "function": "invokeMethod",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": [
               {
                  "__class__": "Sabre\\HTTP\\Request"
               },
               {
                  "__class__": "Sabre\\HTTP\\Response"
               }
            ]
         },
         {
            "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 319,
            "function": "start",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": []
         },
         {
            "file": "/apps/dav/appinfo/v1/publicwebdav.php",
            "line": 113,
            "function": "exec",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": []
         },
         {
            "file": "/public.php",
            "line": 81,
            "args": [
               "/apps/dav/appinfo/v1/publicwebdav.php"
            ],
            "function": "require_once"
         }
      ],
      "File": "/lib/private/Log/ErrorHandler.php",
      "Line": 91,
      "CustomMessage": "--"
   },
   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
   "version": "20.0.5.2",
   "id": "6008133f649ca"
}
```

### PR DESCRIPTION
**Pull request by solracsf**
Should fix https://github.com/nextcloud/server/issues/25230

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Whooooops indeed the function was used wrongly https://www.php.net/manual/en/function.header.php

I wonder if Psalm knew about it

Edit: yep

```
-  <file src="apps/dav/lib/Connector/PublicAuth.php">
-    <InvalidScalarArgument occurrences="1">
-      <code>'DummyBasic realm="' . $this-&gt;realm . '"'</code>
-    </InvalidScalarArgument>
-  </file>
```

**Comment by ChristophWurst** [comment]
`stable21` instead of `stable 21` :)

**Review by MorrisJobke — APPROVED** [review]
🙈

**Pull request merged**
