### PR TITLE
fix(files): open sidebar on sharing tab by default for files

### LINKED ISSUE #41567: Versions tab is opened by default when following a …/f/{fileId} link or clicking on the right end of the files list
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

---

For folders the activity app opens and I think that it is the best tab to open by default.
However for files the versions tab always opens, even if there is only the initial uploaded version.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/41567
Will fallback to first tab is app is disabled

### CODE REVIEW

**Comment by skjnldsv** [comment]
Slight bug, pushing fix :hourglass:

**Review by nfebe — APPROVED** [review]
Where is the code that opened the activity tab all the time in the past though? :thinking:

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
Alright, a slight change.
Seems like sharing was expected for both folder and files (legacy)

I'll raise that question on the linked ticket for the design team.
in the meantime, this fixes a few things, so let's get this in

**Pull request merged**
