### PR TITLE
Comment field fixes

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Respawn of https://github.com/nextcloud/server/pull/38501 (avoids conflicts of old PR and more complete fix)

**Testing from reviewers needed.**

## Fixes : 

- Field's height when empty
- Submit button's location

## Before
[Capture vidéo du 31-08-2023 10:51:47.webm](https://github.com/nextcloud/server/assets/33763786/4223a8b9-364f-4a04-91e5-39ec6a1eba7c)

## After
[Capture vidéo du 31-08-2023 10:52:10.webm](https://github.com/nextcloud/server/assets/33763786/87282d4c-d030-4075-b85a-c7a3fe004d6d)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — CHANGES_REQUESTED** [review]
I think that require a fix on the vue component directly
Setting a `position: relative;` on the `.rich-contenteditable__input` seems to do the trick and wrap the placeholder.

**Review by jancborchardt — COMMENTED** [review]
Visually looks good to me, but it would be best to use variables instead of fixed values here, based on `var(--default-grid-baseline)` (4px).

@Jerome-Herbinet a quick general note regarding reopening pull requests – it's always nicer to keep it in the existing pull request (stuff can be force pushed or rebased for example), because otherwise reviews are spread among multiple pull requests. And if you do absolutely need to do a new PR, make sure to delete the branch of the old one. :)

**Comment by Jerome-Herbinet** [comment]
> Visually looks good to me, but it would be best to use variables instead of fixed values here, based on `var(--default-grid-baseline)` (4px).
> 
> @Jerome-Herbinet a quick general note regarding reopening pull requests – it's always nicer to keep it in the existing pull request (stuff can be force pushed or rebased for example), because otherwise reviews are spread among multiple pull requests. And if you do absolutely need to do a new PR, make sure to delete the branch of the old one. :)

OK @jancborchardt I understand, and I'll delete all my closed PRs' branches.

**Comment by skjnldsv** [comment]
Fixed with 28 and the new activity/comments merge

**Pull request closed without merging**
