### PR TITLE
14.0.0 final

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by georgehrke** [comment]
🚧 🚧 https://github.com/nextcloud/server/pull/10958 is not fixed / merged yet 🚧 🚧

**Comment by ChristophWurst** [comment]
> construction construction #10958 is not fixed / merged yet construction construction

https://github.com/nextcloud/server/pull/10958#event-1828276073 :champagne:

**Comment by rullzer** [comment]
Rebased

**Review by nickvergessen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by ChristophWurst** [comment]
:fireworks: :champagne: :beers:

**Pull request merged**
