### PR TITLE
Fix user settings layout

### LINKED ISSUE #34148: [Bug]: NC 25 Users Layout missing check marks and layout is off
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Please see images between NC 24 & NC 25 

Tested on NC 25 Beta 7 & NC 24.0.5

image
image
image
image

### Steps to reproduce

1. Open settings
2.Users
3.Click on the user and add them to the group

### Expected behavior

There should be check marks next on the group that the user is a member off and the boxes should not be that close. 

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
NA
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #34784: [Bug]: User list's display broken on users with many groups
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Users without group or with 2-3 groups are fine.

Users with many groups displayed wrongly. Text on text, spacing errors.

kép
kép

### Steps to reproduce

1. Update to 25
2. Create eg. 10 groups
3. put a user in the created groups.

### Expected behavior

Should not overlay, should keep spacing.

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.15.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - geoblocker: 0.5.7
  - impersonate: 1.11.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2022.10.20
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.2
  - settings: 1.7.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.11.0
  - announcementcenter: 6.4.0
  - bruteforcesettings: 2.4.0
  - dashboard: 7.5.0
  - encryption
  - extract: 1.3.5
  - files_retention: 1.14.0
  - files_trackdownloads: 1.11.0
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - groupfolders: 13.0.0
  - logreader: 2.3.0
  - photos: 1.0.0
  - quota_warning: 1.14.0
  - ransomware_protection: 1.13.0
  - serverinfo: 1.8.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - user_retention: 1.8.0
  - user_usage_report: 1.9.0
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #35284: [Bug]: List of users gets warbled
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When opening list of users they gets warbled when users belongs to many Groups.  These lines belongs to 3 users.

image

### Steps to reproduce

1. Open NC 25.0.1
2.Go to Users
3.Look at list of users

### Expected behavior

Every user should have a section which adapt the height to the number of groups. 

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
v
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.1.0
  - cloud_federation_api: 1.8.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - groupfolders: 13.0.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.1.1
  - oauth2: 1.13.0
  - provisioning_api: 1.15.0
  - registration: 2.0.0
  - related_resources: 1.0.3
  - richdocuments: 7.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - apporder: 0.15.0
  - bruteforcesettings
  - circles: 23.1.1
  - comments: 1.8.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - encryption
  - federation: 1.6.0
  - files_external: 1.11.1
  - files_rightclick: 0.16.0
  - firstrunwizard: 2.5.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.11.1
  - onlyoffice: 7.6.8
  - password_policy: 1.10.1
  - photos: 1.5.0
  - privacy: 1.0.0
  - recommendations: 0.4.0
  - richdocumentscode: 22.5.802
  - sharebymail: 1.12.0
  - support: 1.0.0
  - survey_client: 1.7.0
  - suspicious_login: 3.2.1
  - systemtags: 1.6.0
  - twofactor_totp
  - user_ldap
  - user_status: 1.0.1
```

### Nextcloud Signing status

```shell
v
```

### Nextcloud Logs

```shell
v
```

### Additional info

v

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #34148 
Fix https://github.com/nextcloud/server/issues/34784
Fix https://github.com/nextcloud/server/issues/35284
Vue lib fix in https://github.com/nextcloud/nextcloud-vue/pull/3513

image

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks Barth! Will test later! Does this also fix https://github.com/nextcloud/server/issues/34784 ? :)

**Comment by skjnldsv** [comment]
> Thanks Barth! Will test later! Does this also fix #34784 ? :)

image

**Comment by szaimen** [comment]
Thanks! :)

--

@skjnldsv do we wanna push a possibly new vue release already to this branch?

**Comment by PVince81** [comment]
also fixes https://github.com/nextcloud/server/issues/35284, added to top post

**Review by PVince81 — APPROVED** [review]
:+1: fine to merge for me

overlap issue can be fixed separately, unless trivial

**Review by szaimen — CHANGES_REQUESTED** [review]
still some strange things happening:
image

1. The multiselect dropdown of the group selection seems to be not visible anymore
2. the quota field seems to overlap the edit and dropdown buttons 

---


also the multiselect needds the mentioned fix from the vue lib. so an update should be pushed to this branch or in a follow-up.

**Comment by szaimen** [comment]
@PVince81 why did you merge this? the group dropdown is now more broken then before...

**Comment by PVince81** [comment]
@szaimen is it ? I saw more fixed stuff than broken stuff

**Comment by PVince81** [comment]
> The multiselect dropdown of the group selection seems to be not visible anymore

alright. I only saw the other less important glitch

**Comment by szaimen** [comment]
I am on it with https://github.com/nextcloud/server/pull/35380

**Pull request merged**
