### PR TITLE
hide download button for public preview of audio files

### LINKED ISSUE #26086: Download link of audio file shared via public link is displayed also when 'hide download' option is enabled
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload an audio file to Nextcloud
2. Click on the share icon for that file
3. Click on "Share Link"
4. Click on the 3 dots next to the entry "Share Link"
5. Enable the option "Hide download" in the popup
6. Open the copied link in a new tab
7. On the new tab, click on the 3 dots next to the "audio line"
8. Option to download the file is displayed

### Expected behaviour
When the option, to hide the download, is selected for a public link, the ui should not display a link to download the file.

### Actual behaviour
When the option, to hide the download, is selected for a public link, the ui displays a link to download the file.

### Server configuration

**Operating system:** Docker Image

**Nextcloud version:** 20.0.8

### Screenshots
***Create share link***
image
***Open Share link and download the file***
image

### LINKED ISSUE #27872: Cannot hide download button
Nextcloud version (eg, 20.0.5): 20.0.5
Operating system and version : Debian 9
Apache 2.4.25
PHP: 7.3.29

If you want to share a file and hide the download button, it does not work on Vivaldi browser, which is based on Chrome.

If you include the file in a folder and share the folder, then the download button is hidden.

I have experienced it with mp3 and txt file

You can see more detailed information and screen shot [here](https://help.nextcloud.com/t/cannot-hide-download-button/119761/3)
Click on the 3 dots on the right
File-share1
When you click download is proposed
File-Share2
When you click download you  get this popup and can save the file
File-share3

This has been test with my server but also with the https://try.nextcloud.com/ server.

It looks like it is a client side issue.

### PR DESCRIPTION
**Pull request by fstorz**
When the option to hide downloads was selected at public link creation, the download button can be hidden by the audio html attribute controlsList="nodownload"

closes #26086
closes #27872 

code was not tested, due to lack of local php setup

### CODE REVIEW

**Comment by szaimen** [comment]
cc @nextcloud/server please review

**Comment by tcitworld** [comment]
The `controlsList` attribute [is not standard… at the moment at least](https://github.com/whatwg/html/pull/6715). Chrome has got it for a while, but both Webkit (Safari) and Firefox [voted against](https://www.chromestatus.com/feature/5737006365671424).

**Comment by fstorz** [comment]
* Safari does not show the "Download" button at all, that this PR should fix (Tested on MacOS).
* Don't Safari & Firefox just ignore the attribute when they don't support it?
* According to [Mozilla MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList) also Opera & Edge support the `controlsList` attribute

**Comment by tcitworld** [comment]
Yes, it was more about adding code that doesn't follow standards, even if it doesn't break anything that bothered me. It means support for it can be changed/removed at any time.

Opera & Edge use the same rendering engine as Chrome, so their support will always be the same than Chrome (except for feature flags activated at different times).

**Comment by szaimen** [comment]
Is there maybe another flag that could be added that follows standards?

**Comment by fstorz** [comment]
The "download" button is only implemented by Chrome (or Chromium based browsers), correct?
So from the discussions in the threads, @tcitworld linked in his comment above, there will be no "standard" in the near future.

Additional discussion on this topic in the ["HTML Standard" repository](https://github.com/whatwg/html/issues/2293)

**Review by szaimen — APPROVED** [review]
Just tested the patch successfully and it works on Chromium based browsers. 👍 
The download option doesnt get shown in firefox either way so it doesnt need to work in firefox.

**Review by Pytal — APPROVED** [review]
Looks good to me :) @skjnldsv @blizz @artonge @juliushaertl @ChristophWurst @eneiluj @ArtificialOwl @icewind1991 thoughts?

**Comment by blizz** [comment]
Please address correctly @blizzz

Sent from Yahoo Mail on Android 
 
  On Fri, Jun 25, 2021 at 5:44 PM, ***@***.***> wrote:   


@Pytal approved this pull request.

Looks good to me :) @skjnldsv @blizz @artonge @juliushaertl @ChristophWurst @eneiluj @ArtificialOwl @icewind1991 thoughts?

**Comment by artonge** [comment]
Not sure about how useful this is.

1. I agree with  @tcitworld about this not being a standard and that it will probably be replaced, or removed.
2. Only chromium browsers seems to offer a download button behind a three-dot menu.
3. The user still has the option to download the file by right-clicking on the audio element. So what's next, overriding right-click to prevent that too ?

But, if this comes with a comment pointing to this PR or other relevant info that adds context, then I won't oppose :).

**Comment by juliushaertl** [comment]
> Only chromium browsers seems to offer a download button behind a three-dot menu.
> The user still has the option to download the file by right-clicking on the audio element. So what's next, overriding right-click to prevent that too ?

I'd be ok getting this as it would fit the "hide download" feature which is kind of controversial anyways, as it always was ment to just affect UI elements since there is no real way we can be sure that downloading is not possible anymore (right click, network console, screenshotting, ...) The PR properly hides the element where it is shown, which is chromium only anyways.

**Review by szaimen — CHANGES_REQUESTED** [review]
So basically IIRC, @fstorz please add a comment that points to the discussion here in the code and everybody should be fine :)

**Comment by LukasReschke** [comment]
> The user still has the option to download the file by right-clicking on the audio element. So what's next, overriding right-click to prevent that too ?

FWIW: This is what [Gmail "Confidential Emails"](https://support.google.com/mail/answer/7674059) does. One can still bypass this with the developer console, but it is about making it harder :)

**Comment by szaimen** [comment]
@fstorz any update here? :)

**Comment by fstorz** [comment]
@szaimen is there any best practice in the nextcloud repo to add such a comment?

Sample 1
```
<audio tabindex="0" controls="" preload="none" style="width: 100%; max-width: <?php p($_['previewMaxX']); ?>px; max-height: <?php p($_['previewMaxY']); ?>px"
	<?php // See https://github.com/nextcloud/server/pull/27674 ?>
	<?php if ($_['hideDownload']) { ?>controlsList="nodownload" <?php } ?>>
```

Sample 2
```
<!-- See https://github.com/nextcloud/server/pull/27674 -->
<audio tabindex="0" controls="" preload="none" style="width: 100%; max-width: <?php p($_['previewMaxX']); ?>px; max-height: <?php p($_['previewMaxY']); ?>px"
	<?php if ($_['hideDownload']) { ?>controlsList="nodownload" <?php } ?>>
```

**Comment by szaimen** [comment]
Maybe @LukasReschke or @juliushaertl can comment on this one ⬆️? Thanks! :)

**Comment by LukasReschke** [comment]
Both methods would be ok to me. I'd probably tend more to 1.

**Comment by szaimen** [comment]
@nextcloud/server any idea why `Code scanning results / Psalm` is somehow suddenly failing?

**Review by szaimen — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Pull request merged**
