### PR TITLE
WIP: Redesign iMIP email to better format both HTML and plain text.

### PR DESCRIPTION
**Pull request by brad2014**
These iMIP emails are sent when calendar events are sent when
calendar events containing invitees are created, updated, or deleted.

Addresses issues #12391 and #13555

The event is now presented in the mail using a tabular format.
Features of new design:
- Tabular format is visually clearer than previous bullet list.
- Organizer and attendee list are now included as labeled elements.
- RSVP accept is indicated for organizer and each attendee with a ✔︎.
- Eliminating linked design icons removes most privacy-eroding
  beacons (partially addressing issue #17187). Logo still TBD.

Also:
- Corrected some wording/spelling issues in emails.
- Renamed $meetingInviteeName to $meetingOrganizerName (someone
  confused invitee and invitor).
- Minor refactoring.

Signed-off-by: Brad Rubenstein brad@wbr.tech

### CODE REVIEW

**Comment by brad2014** [comment]
NOTES:

- This PR has UX design changes, and I'm open to feedback on aesthetics.
- This does not yet include updated tests.
- The set of strings subject to localization (l10n) in iMIP emails has been changed.
- It is conceivable that the HTML wrangling for the event table should be abstracted in EMailTemplate.php, but I was concerned that would create a breaking interface change. 
- CalDav Reminder notification emails still use the bulleted list rather than the table - I'm not sure which is better for that purpose.  No other code uses EMailTemplate::addBodyListItem in the server repo (but that doesn't mean installations or apps haven't used it).

**Comment by brad2014** [comment]
This is how the email has changed (as it looks in Thunderbird, scrolling past the logo).

### Old HTML:
old - html

### New HTML:
new - html

### Old plain text:
old - text

### New plain text:
new - text

**Comment by brad2014** [comment]
FIX: Bug in gmail formatting:  table style border, shading, vertical alignment. 
new - gmail html

**Comment by brad2014** [comment]
Here is what the cancel messages look like:
### Cancel iMIP mail - HTML
new cancel - html

### Cancel iMIP mail - plain text
new cancel - text

**Comment by brad2014** [comment]
I'll wait until @georgehrke  or @nickvergessen  tells me that the look is in line with what you consider acceptable, then I'll finish the tests etc.  (one more commit).

**Comment by jospoortvliet** [comment]
@nextcloud/designers

**Comment by skjnldsv** [comment]
Hey! Thanks for your pr!

For me the plain text emails looks like a good improvement.
But the standard html are a huuge regression. We indeed need to update our designa bit, but we're going straight to a 1990 style here. This definitely doesn't fit our project designs :confused:

**Comment by brad2014** [comment]
> Hey! Thanks for your pr!
> 
> For me the plain text emails looks like a good improvement.
> But the standard html are a huuge regression. We indeed need to update our designa bit, but we're going straight to a 1990 style here. This definitely doesn't fit our project designs 😕

Don't be sad @skjnldsv  😄 !  I'm happy to build a different design, and the differences I'd like to preserve on the HTML side are 

- no remote images (for privacy, and for support of recipients that can't access server)
- the new information (organizer, attendees), with indicators of RSVP status
- something that properly accommodates longer multi-line descriptions properly.
- mobile friendly (neither the existing or my WIP really achieves that, but this would be the time to fix it)

Unfortunately, the current EmailTemplate API builds up the two HTML/Text versions in parallel, adding semantic elements to both HTML and text in each API call.  So it would be tough to leave the HTML as-is (as a list) and only upgrade the plain text (to a table), without some hack (e.g. let the EmailTemplate build both, then swap in upgraded plain text via a new EmailTemplate API point). I wouldn't do that unless a code reviewer recommended it.

Would anyone like to collaborate with me on an HTML design that fits your direction and addresses the above concerns? Even a screenshot of an idea would be useful for me to implement from.  (But if folks have other priorities, I fully understand).

**Comment by brad2014** [comment]
Superceded by PR #17456

**Pull request closed without merging**
