### PR TITLE
Improve error reporting on sharing errors

### LINKED ISSUE #20179: password policy error not shown correctly
If I set a password which is not accepted by the password policy I see this:

image

The request returns the correct error which was also shown in older Nextcloud versions:

image

Tested with Nextcloud 18.0.3

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Enable password policy app
2. Create a public link
3. Set link share password to `123456`

Fix #20179

Before | After
---|---
Bildschirmfoto von 2020-07-08 11-28-24 | Bildschirmfoto von 2020-07-08 11-25-49

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
17 is completely different it seems.

**Pull request merged**
