### PR TITLE
Also cache WOFF, SVG and GIF

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@josh4trunks Is it fine to update this NGINX config line:

```
  # Adding the cache control header for js and css files
  # Make sure it is BELOW the PHP block
  location ~* \.(?:css|js)$ {
```

**Comment by josh4trunks** [comment]
looks good to me.
those extension types should be removed from the static location at the end
`location ~* \.(?:svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$ {`

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
> looks good to me.
> those extension types should be removed from the static location at the end (of the nginx config example)

There is only one endpoint: preview.png that needs to be executed by PHP. Or am I wrong? cc @rullzer

**Comment by josh4trunks** [comment]
@MorrisJobke that's why this block has to be below the PHP block, since regex blocks are matched first.

**Comment by MorrisJobke** [comment]
> Actually, are we doing this? If so I don't understand how we know to pass preview.png to PHP based on the documented config.

These are the routes: https://github.com/nextcloud/server/blob/8c7d7d7746e76b77ad86cee3aae5dbd4d1bcd896/core/routes.php#L112-L115

@LukasReschke Where are the rules for excluding this in the apache config?

**Comment by josh4trunks** [comment]
ahh, yes this is handled correctly with the current nginx config. I was correct in my earlier statement, as long as the static location block is last. the nginx config will only match locations to actual files so since preview.png doesn't exist the request is given to index.php

**Pull request merged**
