### PR TITLE
targets 3rdparty submodule from Nc instead of oC

### LINKED ISSUE #243: Redirect 3rdparty to Nextcloud
Currently `3rdparty` directs to `owncloud/3rdparty`. Because we have `nextcloud/3rdparty` now, I think we can safely change that 😉 

cc @MorrisJobke

### PR DESCRIPTION
**Pull request by vincchan**
fixes #243 

this requires a `git submodule sync`

please review @MorrisJobke @mar1u5

### CODE REVIEW

**Comment by mar1u5** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by mar1u5** [comment]
Backport to `stable9`? @karlitschek

**Comment by karlitschek** [comment]
awesome. please backport

**Pull request merged**
