### PR TITLE
fix: Fix truncation on public page

### LINKED ISSUE #44405: Title on public pages is truncated
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
author name truncated in public share

form title author

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.1.5 AiO 7.12.1
- Forms-Version: 3.4.5

**Desktop (please complete the following information):**
 - OS: macos ventura
 - Browser safari and brave 1.62.165

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Fix https://github.com/nextcloud/server/issues/44405

Before | After
--- | ---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Review by jancborchardt — COMMENTED** [review]
This should actually be a subline of the title on the left, instead of being pushed to the right. Must have regressed at some point?

**Review by jancborchardt — APPROVED** [review]
Looks great, thanks @Pytal! :) 
Just to be sure – this will then also work on public pages of apps which don’t have a subline, right? (So that the main line is just vertically aligned correctly, and not up top.)

**Comment by Pytal** [comment]
> Looks great, thanks @Pytal! :) Just to be sure – this will then also work on public pages of apps which don’t have a subline, right? (So that the main line is just vertically aligned correctly, and not up top.)

Yes, without the subline the main line will still be vertically aligned :)

**Pull request merged**
