### PR TITLE
fix all modals after vue 5.0

### LINKED ISSUE #31246: Test all modals with vue 5.0
https://github.com/nextcloud/server/search?l=Vue&q=modal&type=

### PR DESCRIPTION
**Pull request by szaimen**
Close #31246

Tested:
- [x] dashboard modal
- [x] template picker modal
- [x] new user modal
- [x] set user status modal

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=fix/31246/fix-modals \
-e VIEWER_BRANCH=master \
-e TEXT_BRANCH=master \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks Carl and Louis! :)

**Comment by szaimen** [comment]
samba failure unrelated

**Pull request merged**
