### PR TITLE
Prevents the selection of encrypted folders when clicking on the "Select all" checkbox

### PR DESCRIPTION
**Pull request by TSI-kavitasonawane**

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
Needs compilation and DCO

**Comment by PVince81** [comment]
@TSI-kavitasonawane thanks. To move forward, you also need the following:
- make sure your commits respect the DCO, see https://github.com/nextcloud/server/pull/35299/checks?check_run_id=9614619584 for how to sign off commits
- run these command locally before checking in: `make dev-setup && make build-js-production && npm run sass && npm run sass:icons`, then check in the compiled assets. If you don't we can summon a bot that does it here after you pushed.

**Comment by TSI-kavitasonawane** [comment]
> @TSI-kavitasonawane thanks. To move forward, you also need the following:
> 
> * make sure your commits respect the DCO, see https://github.com/nextcloud/server/pull/35299/checks?check_run_id=9614619584 for how to sign off commits
> * run these command locally before checking in: `make dev-setup && make build-js-production && npm run sass && npm run sass:icons`, then check in the compiled assets. If you don't we can summon a bot that does it here after you pushed.

@PVince81 
I have updated commits with respect to DCO.
Also done compilation and added compiled files as well. Please check it.
Thanks

**Review by PVince81 — APPROVED** [review]
code and commit looks good, now waiting for CI :+1:

**Comment by PVince81** [comment]
stable24: https://github.com/nextcloud/server/pull/35349

**Pull request merged**
