### PR TITLE
Feedback on a redirect taking place after update

### PR DESCRIPTION
**Pull request by marncz**
Fixes issue #1559

image

Don't hide the loading circle when waiting 3 seconds for redirect, could not access the class of icon-checkmark-white so left the loading circle to give users feedback that something is happening "under the hood".

### CODE REVIEW

**Comment by marncz** [comment]
May also replace to top message to say that the update was successful 

Some examples:

**Comment by MorrisJobke** [comment]
Could you instead of removing the checkmark add a loading spinner below the message ... or a countdown from 3 to 0? cc @jancborchardt

**Comment by marncz** [comment]
@MorrisJobke

sure, so instead of that loading circle add a countdown 3 .. 0?

In my instance there was no white checkmark appearing and it only hid the loading circle so I kept it for the whole process, now will replace it with a countdown

**Comment by MorrisJobke** [comment]
> In my instance there was no white checkmark appearing and it only hid the loading circle so I kept it for the whole process, now will replace it with a countdown

There is. At least over here it was.

**Comment by MorrisJobke** [comment]
> There is. At least over here it was.

Yep - this was a regression. Fixed in https://github.com/nextcloud/server/pull/3603

**Comment by nickvergessen** [comment]
So I guess this is "obsolete" now?

**Comment by marncz** [comment]
@nickvergessen I think that issue #1559 is still valid, there is no feedback that the redirect is taking place

one possibility is to display the checkmark inside that loading circle

**Comment by MorrisJobke** [comment]
> So I guess this is "obsolete" now?

No. @jancborchardt Asked to have feedback before the redirect is happening.

**Comment by MorrisJobke** [comment]
> one possibility is to display the checkmark inside that loading circle

No. This would look weird.

**Comment by marncz** [comment]
@MorrisJobke 

ok, waiting on the decision then

**Comment by marncz** [comment]
@MorrisJobke @nickvergessen 

image

Added redirect time + 1 seconds so it look more smooth, please review if that is the right approach

**Pull request closed without merging**
