### PR TITLE
Fix upload remaining time

### PR DESCRIPTION
**Pull request by bekcpear**
This commit fixes a problem that the upload remaining time is always 'a few second' whatever a big or a small file uploading.

`new Date().getMilliseconds()` only return a three digits number, so when time arrived the next second, the millisecond start from ZERO again. 

`new Date().getTime()` is the righe choice.

And remaining time variables should be initialized when the file starts uploading, otherwise the remaining time of a new upload will always be 'Infinity years' until you refresh the page.

And to fix the bitrate in the value of `attribute 'original-title' under the #uploadprogressbar element`.

### CODE REVIEW

**Comment by oparoz** [comment]
@nickvergessen Any idea why this fails with MariaDB-MB4?

**Comment by nickvergessen** [comment]
@oparoz 
> ERROR: terminal inactive for 10m0s, build cancelled

"normal" random failure, ignore

> Regenerating core/vendor/core.js
The merged vendor file is not up to date
Please run: php build/mergejs.php

This however needs to be done

**Review by MorrisJobke — APPROVED** [review]
Tested and works a lot better 👍

**Review by icewind1991 — APPROVED** [review]

**Comment by icewind1991** [comment]
@Bekcpear thanks for you contribution.

Can you please run `php build/mergejs.php` and commit the result

**Comment by Bekcpear** [comment]
@icewind1991  thanks for your mention. 

I have done it.

**Comment by MorrisJobke** [comment]
Sorry to bother you again, but the sign-off is missing :/

See https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work for details.

**Comment by Bekcpear** [comment]
Sorry, I haven't read the contributing guide first. And I have added the signed-off message. Thanks for your remind.

**Comment by MorrisJobke** [comment]
@karlitschek do we want to backport this to stable12?

**Comment by karlitschek** [comment]
definitely. Annoying bug 👍

**Comment by MorrisJobke** [comment]
Hey @bekcpear could you do a branch based on stable12 and cherry pick your commits into this. Then open a pull request here against the stable12 branch? That would be nice 👍

**Comment by Bekcpear** [comment]
Okay, please wait a moment.

**Comment by MorrisJobke** [comment]
🙌 don't worry

**Comment by Bekcpear** [comment]
I opened a pr here https://github.com/nextcloud/server/pull/5442

**Comment by MorrisJobke** [comment]
@Bekcpear Thanks for this nice contribution. If you want to look in some other issues, maybe check out the other starter issues: https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22starter+issue%22

🚀

**Comment by MorrisJobke** [comment]
@karlitschek Should we also backport this to stable11?

**Comment by karlitschek** [comment]
yes please 👍

**Comment by MorrisJobke** [comment]
@Bekcpear Could you do the same for stable11? That would be nice :)

**Comment by Bekcpear** [comment]
I have finished. ;)

**Pull request merged**
