### PR TITLE
handle exceptions in SMB::stat

### PR DESCRIPTION
**Pull request by icewind1991**
Properly handle non existing/non readable files

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Sounds sane

**Review by MorrisJobke — APPROVED** [review]

**Comment by rik26** [comment]
With Nextcloud 16, the problem still appears with symlink on share, i tested the following code, and it works :
I put a comment here too :
https://github.com/nextcloud/server/issues/7332

```
/**
         * get the best guess for the modification time of the share
         *
         * @return int
         */
        private function shareMTime() {
                $highestMTime = 0;
                $files = $this->share->dir($this->root);
                foreach ($files as $fileInfo) {
                        try {
                                if ($fileInfo->getMTime() > $highestMTime) {
                                        $highestMTime = $fileInfo->getMTime();
                                }
                        } catch (NotFoundException $e) {
                                // Ignore this, can happen on unavailable DFS shares
                        } catch (ForbiddenException $e) {
                                // Ignore this too : symlink
                        }
                }
                return $highestMTime;
        }
```

**Comment by icewind1991** [comment]
@rik26 can you submit a PR with your change

**Comment by rik26** [comment]
@icewind1991 It's not i'm not willing to help, but i don't understand how to make a PR... And sorry for the duplicate but as the issue was closed i created a new one ... 

https://github.com/nextcloud/server/issues/15876

Sorry for being useless..

**Comment by MorrisJobke** [comment]
> Sorry for being useless..

You are not useless. Thanks for the hint already.

I opened a PR at https://github.com/nextcloud/server/pull/16195

**Pull request merged**
