### PR TITLE
`SharingEntrySimple` needs `ul` or `ol` around it

### LINKED ISSUE #42694: [BITV]: HTML Structure inside of sharing tab is not correct
`sharing-entry sharing-entry__reshare` inside of the `sharingTab__content` element should not be a list element (`<li>`). There is only one element which is present and that means that `sharing-entry sharing-entry__reshare` can be a simple `<div>`.

Screenshot from 2024-01-11 09-36-20

cc @Fenn-CS

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/42694

This is best reviewed like this: https://github.com/nextcloud/server/pull/42709/files?diff=unified&w=1

| Before | After |
|---|---|
| image | image |
| image | image |

<details>
<summary>For my own testing</summary>

```
docker run -it --rm ^
--name nextcloud-easy-test ^
-p 8443:443 ^
-e SERVER_BRANCH=enh/42694/put-li-into-ul ^
-e COMPILE_SERVER=1 ^
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" ^
ghcr.io/szaimen/nextcloud-easy-test:latest

```

</details>

### CODE REVIEW

**Review by ShGKme — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]
LGTM!

**Comment by szaimen** [comment]
/backport 420b3d085e3cb8e8f2ce317121904a2dfc536a0c to stable28

**Pull request merged**
