### PR TITLE
Add indeterminate state to share permission checkbox

### PR DESCRIPTION
**Pull request by dasisdormax**
This PR adds the 'indeterminate' checkbox state to the general "can edit" checkbox if some, but not all of the 'create', 'update', and 'delete' prermissions are given for that share. See issue #8371

### CODE REVIEW

**Comment by MorrisJobke** [comment]
The JSUnit tests fail: Could you have a look at https://drone.nextcloud.com/nextcloud/server/4940/216 (roughly line 900+)?

**Comment by dasisdormax** [comment]
@MorrisJobke it seems that my change in the render function revealed a bug we haven't found before (slashes in the sharee's federation URL weren't escaped).

Fixed that and updated the test for the new desired behaviour. Let's see if there's more ...

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@dasisdormax Thanks for the pull request. That is a really nice improvement. :+1:

**Review by MorrisJobke — APPROVED** [review]
Code change looks good and works nicely 👍

**Comment by MorrisJobke** [comment]
Swift CI failure is known -> from CI point of view it's good to merge.

@ChristophWurst @skjnldsv @danxuliu @rullzer Mind to review this one her?

**Comment by MorrisJobke** [comment]
Hey @dasisdormax we would like to invite you to the IRC channel #nextcloud-dev on freenode. Maybe also have a look at the other "good first issues": https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Pull request merged**
