### PR TITLE
Add :+1: in UTF-8

### PR DESCRIPTION
**Pull request by LukasReschke**
Let's see whether that works :see_no_evil:

cc @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by blizzz** [comment]
LGTM

**Comment by schiessle** [comment]
LGTM

**Comment by schiessle** [comment]
seems that :+1: doesn't work :cry:

**Comment by vincchan** [comment]
@schiessle Wouldn't you need to merge it before it works?

**Comment by schiessle** [comment]
@vincchan hehe... good point :D

**Pull request merged**
