### PR TITLE
Fix a bunch of deprecation in the phpunit for core

### PR DESCRIPTION
**Pull request by CarlSchwan**

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by CarlSchwan** [comment]
Needs https://github.com/nextcloud/server/pull/31761 to kill old phpunit version

**Review by nickvergessen — APPROVED** [review]

**Comment by CarlSchwan** [comment]
integration tests are still using phpunit 8 :(

**Comment by PVince81** [comment]
there are still some test failures

**Comment by nickvergessen** [comment]
> There was 1 error:
> --
> /drone/src/tests/Core/Service/LoginFlowV2ServiceUnitTest.php:353

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
