### PR TITLE
Non-blocking session handler

### PR DESCRIPTION
**Pull request by andreas-p**
I'm firing 4 ajax requests from an app simultaneously, and found them to be executed serially. This is caused by OC\Session\Internal keeping the session open for the whole request, which makes the php session blocking.
Reading http://php.net/manual/en/class.sessionhandlerinterface.php , I implemented that sample MySessionHandler, and found that this works in most situations, except for the login process which will create several sessions, but none workable.
So I derived the FileSessionHandler from the default SessionHandler, which checks if the session file is already present. If not, the standard blocking SessionHandler methods are called; otherwise, simple non-blocking reads and writes are used.
AFAICS, on a running session, only LAST_ACTIVITY will be set regularly, to limit session lifetime, so this appears quite safe to me.

### CODE REVIEW

**Comment by LukasReschke** [comment]
I'm not a fan of this approach. Can you share your app code and what you're doing there? We're closing the session for writes as soon as the actual controller is hit which shouldn't be late. (unless you use `@UseSession`)

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Blocking merge due to general concerns about the architectural approach.

**Comment by andreas-p** [comment]
I instrumented the Session\Internal code with some timestamping, and found that it takes 250-300ms on my test server between session_start and session_write_close. The ajaxController does virtually nothing:
<?php
namespace OCA\Partner\Controller;
use OCP\AppFramework\Controller, OCP\AppFramework\Http\JSONResponse, OCP\IRequest;

class TestController extends Controller {
	/**
	 * @NoAdminRequired
	 */
	public function execTest()	{
		return new JSONResponse([]);
	}
}

Releasing the session much earlier would certainly be a better aproach, but this might not be possible because @UseSession is checked right before running the controller, which is way too late. Maybe a two-step approach should be used:
- do a quick session; just read and update LAST_ACTIVITY and close immediately.
- If the Controller has @UseSession, start the session again and let it open for the controller.

**Comment by LukasReschke** [comment]
> I instrumented the Session\Internal code with some timestamping, and found that it takes 250-300ms on my test server between session_start and session_write_close. The ajaxController does virtually nothing:

Then there is some problem in some other part in the code. A request should not take 250-300ms. Have you enabled a cache? Also can you run a trace with blackfire.io and share the result?

**Comment by andreas-p** [comment]
I'm developing without cache.
Here are some numbers, the second column is milliseconds since session creation:
Standard SessionHandler, no cache
5811f9207c531 2.3 -  Session start wait 
5811f9207c531 4.3 -  Session started 
5811f9207e58c 0.6 -  Session start wait 
5811f9207fd3e 0.8 -  Session start wait 
5811f920821f0 0.5 -  Session start wait 
5811f9207c531 359.5 -  Session end 
5811f920821f0 336.5 -  Session started 
5811f920821f0 654.7 -  Session end 
5811f9207e58c 671.4 -  Session started 
5811f9207e58c 967.0 -  Session end 
5811f9207fd3e 961.8 -  Session started 
5811f9207fd3e 1239.2 -  Session end 

Standard-handler, APCu memcache
58120c177b004 0.5 -  Session start wait 
58120c177b004 1.3 -  Session started 
58120c178038b 0.8 -  Session start wait 
58120c1784e8a 0.6 -  Session start wait 
58120c17866cf 0.9 -  Session start wait 
58120c177b004 174.6 -  Session end 
58120c178038b 153.8 -  Session started 
58120c178038b 281.4 -  Session end 
58120c1784e8a 262.8 -  Session started 
58120c1784e8a 388.5 -  Session end 
58120c17866cf 383.4 -  Session started 
58120c17866cf 521.9 -  Session end


Non-Blocking handler, no cache
5811f92c8c554 0.6 -  Session start wait 
5811f92c8c554 1.9 -  Session started 
5811f92c94a64 0.9 -  Session start wait 
5811f92c94a64 11.7 -  Session started 
5811f92c98d80 0.8 -  Session start wait 
5811f92c98d80 2.2 -  Session started 
5811f92c9b157 0.4 -  Session start wait 
5811f92c9b157 1.1 -  Session started 
5811f92c8c554 356.1 -  Session end 
5811f92c94a64 428.7 -  Session end 
5811f92c9b157 414.8 -  Session end 
5811f92c98d80 456.1 -  Session end 

Non-blocking handler, APCu memcache
58120ca281800 1.6 -  Session start wait 
58120ca281800 2.9 -  Session started 
58120ca2843ef 0.4 -  Session start wait 
58120ca2843ef 1.3 -  Session started 
58120ca284c32 1.6 -  Session start wait 
58120ca284c32 3.3 -  Session started 
58120ca294a77 3.8 -  Session start wait 
58120ca294a77 5.3 -  Session started 
58120ca281800 231.8 -  Session end 
58120ca2843ef 234.7 -  Session end 
58120ca284c32 273.3 -  Session end 
58120ca294a77 264.0 -  Session end 

The last situation leads to a total response time of 400ms for all 4 ajax requests completed.

So yes, caching helps, reducing the session lock time from 400ms to 250ms, but the app will take some more concurrent ajax requests in the future, and the controller used above does nothing valuable so far.

Development web server (VirtualBox VM) and database server are slow machines, so absolute numbers will be much better on decent machines, but the locking problem remains.

**Comment by rullzer** [comment]
Can you share your benchmark code?

**Comment by andreas-p** [comment]
I just added the benchmarking code to Session/Internal.php, with FileSessionHandler commented out so the default behaviour will be logged to /tmp/session.log.

**Comment by LukasReschke** [comment]
I've discussed this a bit more in detail with @rullzer et al and we believe that this has the risk to seriously break stuff as at the moment that is code that is actually expecting sessions to be blocking. This is a change that I'm quite uncertain with implementing as it also is not the PHP default behaviour and may confuse app developers. – We can however look into making the session close faster or so.

**Pull request closed without merging**
