### PR TITLE
fix(files): disable size containment on headers

### PR DESCRIPTION
**Pull request by pulsejet**
Fixes a regression caused by the header being variable height: see https://github.com/nextcloud/server/pull/40958#issuecomment-1772366976

cc @juliushaertl

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
AH, yes, makes more sense indeed :)

**Review by susnux — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Thanks for the quick fix 💙

**Review by susnux — APPROVED** [review]

**Comment by juliushaertl** [comment]
Sorry to bug again, unfortunately this still seems to cause issues with the popover menu that text might show:

Screenshot 2023-10-24 at 15 34 03

Any chance you could have another look at that as well?

**Pull request merged**
