### PR TITLE
Revert "First attempt to check against core routes before loading all app routes"

### PR DESCRIPTION
**Pull request by PVince81**
Reverts nextcloud/server#24295

Fixes https://github.com/nextcloud/guests/issues/654

Unless there's a better reliable short term solution, see https://github.com/nextcloud/server/pull/24295#discussion_r659685182

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by PVince81** [comment]
amended the commit message to make DCO bot happy

**Review by artonge — APPROVED** [review]

**Comment by PVince81** [comment]
test failure probably unrelated:
```
SettingsContext::iSeeThatTheDropdownForTagsInTheSettingsEventuallyContainsTheTag()
      Select2 dropdown mask in Settings could not be found (NoSuchElementException)
```
it didn't fail in the previous run before I amended the commit text: https://drone.nextcloud.com/nextcloud/server/6729/57/4

please force-merge, then...

**Pull request merged**
