### PR TITLE
Mark Smb tests as skipped for now because of the old samba version we…

### PR DESCRIPTION
**Pull request by nickvergessen**
… use

So we can have back green CI

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
+1 as discussed

**Comment by nickvergessen** [comment]
Samba green, can we merge? @PVince81 @icewind1991

**Comment by icewind1991** [comment]
it seems like just bumping the images has worked: https://drone.nextcloud.com/nextcloud/server/14901/7/4

**Comment by nickvergessen** [comment]
> it seems like just bumping the images has worked: https://drone.nextcloud.com/nextcloud/server/14901/7/4

Fine by me. Can we backport that to 23?

**Pull request closed without merging**
