### PR TITLE
[stable17] Bump serialize-javascript and handlebars

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by kesselb** [comment]
Milestone `Nextcloud 18` and target branch `stable17`? :thinking:

**Comment by ChristophWurst** [comment]
Fixed!

**Review by blizzz — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Ah but handlebars is out of date.
And the webpack bundle as well...

**Comment by ChristophWurst** [comment]
@skjnldsv I can also not build `stable17` without changes. These files have modifications:

 * core/js/dist/login.js
 * core/js/dist/login.js.map
 * core/js/dist/main.js
 * core/js/dist/main.js.map
 * core/js/dist/maintenance.js
 * core/js/dist/maintenance.js.map
 * settings/js/vue-5.js
 * settings/js/vue-5.js.map

and yes, I tried with npm ci as well.

**Comment by gary-kim** [comment]
> @skjnldsv I can also not build `stable17` without changes. These files have modifications:

Seems to have something to do with node version. My system also compiles with changes but those changes don't occur if I use Node 10 rather then 12 which is the default on my system.

**Pull request merged**
