### PR TITLE
[15] Add interface to allow storages from opting out of encryption

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/nextcloud/server/pull/12691

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Nice :+1:

**Comment by ChristophWurst** [comment]
https://drone.nextcloud.com/nextcloud/server/13084/116

```
1) Test\Encryption\EncryptionWrapperTest::testWrapStorage with data set #2 (false, array('OCA\Files_Sharing\SharedStorage'))
Asserted that the storage is (not) wrapped with encryption
Failed asserting that true matches expected false.

/drone/src/github.com/nextcloud/server/tests/lib/Encryption/EncryptionWrapperTest.php:84

2) Test\Encryption\EncryptionWrapperTest::testWrapStorage with data set #3 (false, array('OCA\Files_Sharing\External\Storage'))
Asserted that the storage is (not) wrapped with encryption
Failed asserting that true matches expected false.

/drone/src/github.com/nextcloud/server/tests/lib/Encryption/EncryptionWrapperTest.php:84

3) Test\Encryption\EncryptionWrapperTest::testWrapStorage with data set #4 (false, array('OC\Files\Storage\OwnCloud'))
Asserted that the storage is (not) wrapped with encryption
Failed asserting that true matches expected false.

/drone/src/github.com/nextcloud/server/tests/lib/Encryption/EncryptionWrapperTest.php:84

4) Test\Encryption\EncryptionWrapperTest::testWrapStorage with data set #5 (false, array('OCA\Files_Sharing\SharedStorage', 'OCA\Files_Sharing\External\Storage'))
Asserted that the storage is (not) wrapped with encryption
Failed asserting that true matches expected false.

/drone/src/github.com/nextcloud/server/tests/lib/Encryption/EncryptionWrapperTest.php:84

5) Test\Encryption\EncryptionWrapperTest::testWrapStorage with data set #6 (false, array('OCA\Files_Sharing\SharedStorage', 'OC\Files\Storage\OwnCloud'))
Asserted that the storage is (not) wrapped with encryption
Failed asserting that true matches expected false.

/drone/src/github.com/nextcloud/server/tests/lib/Encryption/EncryptionWrapperTest.php:84

6) Test\Encryption\EncryptionWrapperTest::testWrapStorage with data set #7 (false, array('OCA\Files_Sharing\External\Storage', 'OC\Files\Storage\OwnCloud'))
Asserted that the storage is (not) wrapped with encryption
Failed asserting that true matches expected false.

/drone/src/github.com/nextcloud/server/tests/lib/Encryption/EncryptionWrapperTest.php:84

7) Test\Encryption\EncryptionWrapperTest::testWrapStorage with data set #8 (false, array('OCA\Files_Sharing\SharedStorage', 'OCA\Files_Sharing\External\Storage', 'OC\Files\Storage\OwnCloud'))
Asserted that the storage is (not) wrapped with encryption
Failed asserting that true matches expected false.

/drone/src/github.com/nextcloud/server/tests/lib/Encryption/EncryptionWrapperTest.php:84
```

**Comment by icewind1991** [comment]
tests are happy again

**Review by MorrisJobke — APPROVED** [review]
👍

**Pull request merged**
