### PR TITLE
Avoid substr() error when strpos returns false

### PR DESCRIPTION
**Pull request by bladewing**
"Exception: substr() expects parameter 3 to be int, bool given" can occur on Line 378 $mimePart = substr($icon, 0, strpos($icon, '-'));
This happens, when '-' is not found and strpos returns false instead of an int.
When this occurs, e.g., Activity hangs.

Signed-off-by: Lukas Iffländer lukas.ifflaender@uni-wuerzburg.de

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Review by ChristophWurst — APPROVED** [review]

**Comment by acsfer** [comment]
Shouldn't this be already shipped with 19.0.5? I'm facing this exact error at https://github.com/nextcloud/server/issues/24365 🤔 
Maybe the @MorrisJobke backports hadn't been made?

**Comment by rullzer** [comment]
> Shouldn't this be already shipped with 19.0.5? I'm facing this exact error at #24365 thinking
> Maybe the @MorrisJobke backports hadn't been made?

seems so. let me try to trigger it again

**Pull request merged**
