### PR TITLE
feat: support "s3-accelerate" endpoint

### LINKED ISSUE #42675: Current S3 Implementation lacks support for different endpoints (e.g. S3 Transfer Acceleration)
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently, if a customer wants to mount an external S3 storage, it works as documented here: https://docs.nextcloud.com/server/26/admin_manual/configuration_files/external_storage/amazons3.html

However, to make buckets available across several regions, customers might want to use S3 Transfer acceleration as described here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html?icmpid=docs_amazons3_console

When enabled, the transfer accelerated endpoint is:
[bucket].[s3-accelerate.amazonaws.com](http://s3-accelerate.amazonaws.com/)

But the external storage app converts the settings to:
[bucket].s3.[region].[amazonaws.com](http://amazonaws.com/)
and adds a .s3 to the url.

This problem might not be solely related to S3 Transfer Acceleration, but any situation when the endpoints differs from what the current implementation expects.

**Describe the solution you'd like**
We would need to modify the s3 implementation to tell the aws sdk to use the different endpoint.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by icewind1991**
* Resolves https://github.com/nextcloud/server/issues/42675

When the S3 hostname is set to `s3-accelerate.amazonaws.com`, enable the `use_accelerate_endpoint`.

### CODE REVIEW

**Comment by joshtrichards** [comment]
Relevant issue: #42675

**Comment by solracsf** [comment]
Will this handle also:
```
bucketname.s3-accelerate.amazonaws.com
bucketname.s3-accelerate.dualstack.amazonaws.com
```
?

**Comment by icewind1991** [comment]
added dualstack support

**Comment by sorbaugh** [comment]
> added dualstack support

🤩

**Review by artonge — APPROVED** [review]

**Review by sorbaugh — APPROVED** [review]

**Pull request merged**
