### PR TITLE
[stable9] Make sure the UID is correctly cased

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #1766 #1142

@MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I tested this and it only works with lower case user names. If I try `./occ files:transfer-ownership Test1 Test` it still shows the wrong casing:

```             
Analysing files of Test1 ...
    1 [============================]
Collecting all share information for files and folder of Test1 ...
    0 [>---------------------------]
Transferring files to Test2/files/transferred from Test1 on 2016-10-17T15:45:28+00:00 ...
Restoring shares ...
    0 [>---------------------------]
```

**Comment by MorrisJobke** [comment]
> If I try ./occ files:transfer-ownership Test1 Test it still shows the wrong casing:

to clarify: The user names are lower case in Nextcloud. The files are not transfered and the output also shows the reason: the casing is somehow still wrong.

**Comment by nickvergessen** [comment]
Added backport of #1142 now it works.

**Comment by MorrisJobke** [comment]
Tested and works now 👍 

cc @rullzer please review

**Comment by rullzer** [comment]
Yep.
LGTM!

**Pull request merged**
