### PR TITLE
Reset and init new user form language

### LINKED ISSUE #16522: Users have wrong locale/language when creating multiple users consecutively
I have an issue when adding users consecutively, without reloading the users page.
I'm using Nextcloud with the config.php options
`'default_language' => 'de',`
and
`'default_locale' => 'de',`
and when adding users (without a password) the first gets the german welcome email and his account will be in german. But when adding directly a second (or third/fourth/...) user he will get the english welcome email and his account settings will be set to english!
If I reload the users page before creating the next user he will get the german welcome email and his account will be set to german again!

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #16522 
cc @konwin

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Needs manual backports.

**Comment by skjnldsv** [comment]
Done in https://github.com/nextcloud/server/pull/17653
https://github.com/nextcloud/server/pull/17652

**Pull request merged**
