### PR TITLE
Always use the folder icon depending on the mount type if not a share mount

### PR DESCRIPTION
**Pull request by juliusknorr**
As discussed with @jancborchardt the mount type (like groupfolder) should always take precedence of the share folder icon

Steps to reproduce:
- Create a groupfolder
- Share it with a user using the regular sharing
- Reload the page
- Open the sharing sidebar
- See the groupfolder icon stay instead of the folder with sharing icon

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by juliushaertl** [comment]
Pushed a fixup to still handle folders without a mountType properly

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Needs a rebase

**Comment by rullzer** [comment]
Master is no 18 development. If this needs to go into 17 please follow the normal backport procedures after merging.

**Comment by rullzer** [comment]
jsunit fails

**Comment by juliushaertl** [comment]
Yay, works again: https://drone.nextcloud.com/nextcloud/server/21612/1/3

Rebased and ready for review.

**Pull request merged**
