### PR TITLE
Remove config change hook that deletes link shares (#26612)

### PR DESCRIPTION
**Pull request by LukasReschke**
Downstream of https://github.com/owncloud/core/pull/26612.

Requires some more work though because the public WebDAV endpoint still works… I'm looking into this… Might also be the case in older releases let's see…

### CODE REVIEW

**Comment by LukasReschke** [comment]
Also the public preview controller needs to be adjusted to catch disabled sharing.

**Comment by LukasReschke** [comment]
>  I'm looking into this… Might also be the case in older releases let's see…

Will open a new PR for this.

**Comment by LukasReschke** [comment]
LGTM for me

**Comment by LukasReschke** [comment]
> Will open a new PR for this.

=> https://github.com/nextcloud/server/pull/2761

**Review by schiessle — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
