### PR TITLE
Fix ShareLink Upload UI for Folders

### LINKED ISSUE #27962: Allow upload and editing on sharing results in read only
### Steps to reproduce
1. Set share link on a folder you wish to share
2. click read only
3. open in private window of browser to see what you can do with the files
4. change to allow upload and editing
5. open in private window of browser to see what you can do with the files

### Expected behaviour
It should change to edit mode, so one can edit and upload.

### Actual behaviour
It stays the same as on read only mode. One can only download or read the files.

### Server configuration

**Operating system:** Ubuntu 20.04

**Database:** mysql

**PHP version:** 7.4.3

**Nextcloud version:** (see Nextcloud admin page) 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 20.0.8

**Where did you install Nextcloud from:** Docker

### PR DESCRIPTION
**Pull request by jotoeri**
Simple fix of a quite old bug i stumbled upon today. The Upload-options for folders are shown only if the user has permissions to do so. If permissions are not given, until now it fell back to the option for files instead of showing nothing.

Fixes #27962

Corresponding v-if: https://github.com/nextcloud/server/blob/e006491b852aedb9dcaf8651e37ca2e287cdc681/apps/files_sharing/src/components/SharingEntryLink.vue#L155

Showing the bug: files option on folder
grafik

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by artonge — APPROVED** [review]

**Comment by jotoeri** [comment]
> The backport to stable21 failed. Please do this backport manually.

Somebody knows, why this happens? 🤔

**Pull request merged**
