### PR TITLE
Merge tips & tricks section into setup checks

### PR DESCRIPTION
**Pull request by MorrisJobke**
bildschirmfoto 2018-06-12 um 23 41 37

~~Maybe needs some polishing.~~

Just for some first feedback - cc @nextcloud/designers @rullzer 

That is the old tips and tricks section:

bildschirmfoto 2018-06-11 um 18 45 20

* SQLite warning should be moved to the general setup hints on the overview page
* "Improving the config.php" is more or less helpless because it only links to the full documentation of the config.php options
* "Theming" should be dropped, because it links to the old way of theming
* performance tuning is already fully covered by the setup checks - https://docs.nextcloud.com/server/14/admin_manual/configuration_server/server_tuning.html
* [general hardening and security guidelines](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/harden_server.html) - not too helpful IMO

The only valid ones are the links to:

* [how to do backups](https://docs.nextcloud.com/server/14/admin_manual/maintenance/backup.html)
* scan.nextcloud.com

This only adds the link to the scan and drops the backup one.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Maybe needs some polishing.

@nextcloud/designers I added underlines for the links in the "security & setup warnings" section to make it more clear where to get more information. I hope this is okay for this part of the UI to have underlines.

**Review by skjnldsv — DISMISSED** [review]
Got an error :)

```js
Uncaught TypeError: data.hasMissingIndexes.forEach is not a function
    at Object.afterCall (setupchecks.js:188)
    at Object.<anonymous> (jquery.min.js:2)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

**Comment by MorrisJobke** [comment]
> Got an error :)

Fixed.

**Comment by MorrisJobke** [comment]
@skjnldsv Any idea why the cue build step fails?

**Comment by MorrisJobke** [comment]
> @skjnldsv Any idea why the cue build step fails?

Found it - rebase failed. Thanks @skjnldsv

**Comment by MorrisJobke** [comment]
Ready for review! :)

**Comment by MorrisJobke** [comment]
> Ci failiure.

Fixed them. Where basically missing ` ↗` that I added to the external links.

**Review by juliusknorr — APPROVED** [review]
:+1: Looks good

**Comment by blizzz** [comment]
> The only valid ones are the links to:
>
>    how to do backups
>    scan.nextcloud.com


The backups-link was no dropped – intentionally? Since you state it is valid.

**Comment by MorrisJobke** [comment]
> The backups-link was no dropped – intentionally? Since you state it is valid.

I don't have a good place where to put it. And it also makes very little sense to put it in the setup checks, because backups are a completely different topic. I would drop it for now and look if it could be added somewhere else with more hints.

**Comment by MorrisJobke** [comment]
Failing acceptance test is unrelated (add new user in user management)

**Review by rullzer — APPROVED** [review]
Fine by me :+1:

**Comment by skjnldsv** [comment]
:+1:

**Pull request merged**
