### PR TITLE
Rename collections to projects

### PR DESCRIPTION
**Pull request by juliusknorr**
- [x] Rename collections to projects
- [x] Add hint text
- [x] Requires https://github.com/juliushaertl/nextcloud-vue-collections/pull/81

As discussed with @jancborchardt @jospoortvliet 

image

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Webpack complains about changes in the compiled assets.

**Review by ghost — COMMENTED** [review]
Is `escapeHTML` not marked deprecated?

**Comment by nickvergessen** [comment]
It is, but there is no replacement yet, so using it is still fine

**Comment by juliushaertl** [comment]
> Webpack complains about changes in the compiled assets.

Updated.

**Review by jancborchardt — APPROVED** [review]
Much better, easier to understand! :)

**Pull request merged**
