### PR TITLE
Move files_sharing additionalscripts over to webpack

### PR DESCRIPTION
**Pull request by rullzer**
Related to https://github.com/nextcloud/server/pull/13649 However that PR tries to do more.

This just moves the additionalscripts bundling from our own bundling to webpack.
Saves an additional request as we bundle the scss now as well.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Isn't the compiled asset missing here?

**Comment by MorrisJobke** [comment]
> Isn't the compiled asset missing here?

Yep - no sharing anymore in the files app 😉

**Comment by rullzer** [comment]
details... yeah let me add it

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
