### PR TITLE
Federation share popover fix

### PR DESCRIPTION
**Pull request by skjnldsv**
|From|To|
|:--:|:--:|
|capture d ecran_2018-05-03_17-06-12|capture d ecran_2018-05-03_17-05-41|

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This works right now, but not once #9332 is merged. Could you have a look at this in combination with the linked PR? cc @juliushaertl

**Comment by skjnldsv** [comment]
@MorrisJobke Putting onhold, I'll adapt once Julius's pr is merged :)

**Comment by MorrisJobke** [comment]
#9332 is merged ;)

**Comment by skjnldsv** [comment]
Fixed:

|From|To|
|:--:|:--:|
|capture d ecran_2018-05-03_17-06-12|capture d ecran_2018-05-03_17-05-41|

and yes, the popover is 100% on the right :laughing:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by juliusknorr — APPROVED** [review]

**Comment by skjnldsv** [comment]
Failure related?

**Comment by juliushaertl** [comment]
@skjnldsv Doesn't look so, the checkers seem to fail because of some network error and jsunit fails on master as well :/

**Comment by MariusBluem** [comment]
39585126-579e4e70-4ef4-11e8-8e25-3d62a5166b1f

Isn't this a bit misaligned? 🤔

**Comment by MariusBluem** [comment]
> Feels weird?

For me, yes. But lets hear what the others say.

**Comment by MorrisJobke** [comment]
> @MariusBluem I centered it on the click handler, not the arrow yes :)

I like it how it is right now.

**Review by danxuliu — COMMENTED** [review]
The label next to the menu handler has a pointer cursor, but clicking on the label does nothing, so either a default cursor is shown when the cursor is on that element, or a click on the label is handled and the menu shown.

Regarding the position of the menu I have no preference.

**Comment by skjnldsv** [comment]
> The label next to the menu handler has a pointer cursor, but clicking on the label does nothing,

It focus the input text for me :)

**Comment by danxuliu** [comment]
>  >  The label next to the menu handler has a pointer cursor, but clicking on the label does nothing,

>  It focus the input text for me :)

:facepalm: Indeed it does. I was so focused on the menu that I ignored everything else, sorry :-)

**Review by danxuliu — APPROVED** [review]

**Pull request merged**
