### PR TITLE
27.1.0 beta 3

### PR DESCRIPTION
**Pull request by skjnldsv**
* #39919
* #39930
* #39934
* #39947
* #39949
* #39962
* #39993
* #39997
* #40007
* nextcloud/files_pdfviewer#801
* nextcloud/files_pdfviewer#807
* nextcloud/nextcloud_announcements#226
* nextcloud/photos#2011
* nextcloud/recommendations#643
* nextcloud/text#4675
* nextcloud/text#4680
* nextcloud/text#4694
* nextcloud/text#4697
* nextcloud/text#4705
* nextcloud/text#4706
* nextcloud/text#4708
* nextcloud/text#4709
* nextcloud/text#4710

## Pending PRs
* Various
  * [x] #39953
* @kesselb
  * [x] #39939
* @miaulalala
  * [x] #40013
* @szaimen
  * [x] #39952

### CODE REVIEW

**Comment by szaimen** [comment]
Should we wait for https://github.com/nextcloud/server/pull/39952 or will there be another beta version?

**Comment by skjnldsv** [comment]
This is the last beta!

**Review by nickvergessen — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
Good from my side then

**Review by AndyScherzinger — APPROVED** [review]

**Comment by susnux** [comment]
Just waiting for drone: https://github.com/nextcloud/server/pull/40030

**Pull request merged**
