### PR TITLE
feat(db): remove workaround for pqsql 9.4 and older

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: noid

## Summary
The workaround was required because "ON CONFLICT DO NOTHING" was added with pqsql 9.5.

PostgreSQL 9.4 is eol since 2020-02-13 and thus everyone should use a version with upsert support nowadays.

## TODO

- [x] CI
- [x] Review

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
🧹

**Review by solracsf — APPROVED** [review]

**Review by solracsf — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/server/blob/474797f91415563041098fb8bf74428df41e5d6b/lib/private/DB/AdapterPgSql.php#L11 should be removed too.

**Comment by blizzz** [comment]
Should be added to release notes  https://github.com/nextcloud/documentation/blob/master/admin_manual/release_notes/upgrade_to_30.rst

**Comment by kesselb** [comment]
> Should be added to release notes https://github.com/nextcloud/documentation/blob/master/admin_manual/release_notes/upgrade_to_30.rst

PR: https://github.com/nextcloud/documentation/pull/11881

**Review by blizzz — APPROVED** [review]

**Review by solracsf — APPROVED** [review]

**Pull request merged**
