### PR TITLE
EntitiesManager

### LINKED ISSUE #10292: Generic share API to share files with apps
We are adding more and more share types to the server component for apps that need to share files depending on the apps data and ownership model. 

Right now we have the following ones, that I think could also be moved to a common apps share:

- SHARE_TYPE_GUEST
- SHARE_TYPE_CIRCLE
- SHARE_TYPE_ROOM

As it would also make sense for other apps like calendar, tasks or deck to access files and share them with users inside there, it would make sense to think about a common share type for apps.

Permission handling would need to be done by the app somehow. Should files that a user got access to by sharing though apps be visible in the file tree? If not, how can users access/download/edit it?

@nextcloud/sharing

### PR DESCRIPTION
**Pull request by ArtificialOwl**
#13478: EntitiesManager
Fix #10292

###  :warning: Note about Visibility :warning: 
Currently, the visibility of all groups is a checkbox to allow sharing from people outside a group to the people within a group. This will be changed in EntitiesManager:

- on migration, the settings will be used when create new Entities, based on the existing groups
- then, default visibility on group creation will be based on a setting.
- visibility of a group can be switched per group, not a global value anymore.

### CODE REVIEW

**Comment by daita** [comment]
**Status update** about EntitiesManager. Please note that this is a WIP and the main purpose of the command lines is to test and see how everything handling together.

Missing features:

- [ ] Comments
- [ ] Viewer and Visibility.
- [ ] Access, Request and Invites
- [ ] Limit to the number of member in an entity.
- [ ] Entity as Member of an entity.
- [ ] Migrate Circles.


### ./occ entities:install

will reset all data from the entities_* tables and create the basic implementation of the interfaces used to manage entities and accounts:

Selection_046

_A quick overview on the basic implementations:_
* implementations of **IEntities**:
  - _'User'_ represents a single local user with access to the Nextcloud, it is using the _'LocalUser'_ implementation of IEntitiesAccounts for the identification of the Nextcloud account (set as the _'Owner'_ of the _'User'_). The display name is saved here during the migration so it is available in the search process. 
  - _'Account'_ represents an account with no access to Nextcloud and limited to the visibility of the _'Owner'_ only. 
  - _'Group'_ manage a list of accounts.
  - _'AdminGroup'_ manage a list of accounts with Nextcloud admin rights.

* implementations of **IEntitiesAccounts**:
 - _'LocalUser'_: used by _'User'_ entities to identify local accounts,
 - _'MailAddress'_: any email address. If multiple users adds the same mail address as contact, we will have one unique entry as entities_accounts and as many entries as needed as entities.

Visibility, membership and ownership will be used when searching for a contact/account/group when sharing an object (file ?).
Of course, any 'out-of-the-box user management' app will be able to add their own implementation.



### ./occ entities:migration

will migrate current users and groups into the Entities Manager.

Selection_044

This example shows all type of Ids used in the Entities Manager:

- **EntityIds** are used to identify any entity, could be a single local user and its account, a 'non-local' account, or a group/cluster/list of any type of accounts. 
  The _EntityId_ will helps to identify a list of users from _any upper layer_; it will be used for shares, chatroom members, access rights, resharing rights but also Nextcloud Admin rights. (Please note that the list is not comprehensive)
  _A Visibility and a Access flag are assigned to EntityIds._

- **AccountIds** are used to identify accounts in the Entities Manager. 
  Please remember that an account in the entity manager is NOT an account on the Nextcloud. However, the list of 'local users' in the entities manager can be used _by lower layer_ to allow/provide access to the Nextcloud. This would require some small edits but in the long term a migration to use the entity manager in the auth/login process could be imaginated.

- **MemberIds** will mostly be used within the Entities Manager, it is the link between _EntityId_ and _AccountId_. 
  _A Level and a Status is assigned to MemberIds._




### ./occ entities:manage:create

a command line to create entity, account or member. The basic syntax is:

>     ./occ entities:manage:create item type

**item** can be entity, account or member
**type** will depend on the item itself, and available type will be displayed: 

Selection_050

Based on the chosen item, some Options are available (and some are mandatory):

- **entity** will accept **--name**, **--access**, **--visibility**, **--owner**
- **account** will require **--account**
- **member** will accept **--account**, **--slave**, **--entity**, **--level**


_As an example, we will add a Mail account in the database._

Selection_051


As a side note, the duplicity is managed by the implementation of the IEntitiesAccountsSearchDuplicate interface. Our class [MailAddress](https://github.com/nextcloud/server/blob/fec47f9e31038bb31344608b003e8e00a15cd945/lib/private/Entities/Classes/EntitiesAccounts/MailAddress.php) check if type and account does not exists already: 

Selection_048

Once the Mail account is added to the database, we will create an entity that will allow the 'cult' user to search for this mail address when sharing a file:

>         ./occ entities:manage:create entity account --owner ACCOUNT_ID \
>           --name "Maxence Lange <maxence@artificial-owl.com>" \
>           --access limited --visibility none

Selection_054


Then, we add the account of the mail address as a normal member of the generated entity.

>       ./occ entities:manage:create member member --level member \
>          --entity ENTITY_ID --account ACCOUNT_ID


Selection_056



### ./occ entities:search

Used to search an entity. This is the typical result to be expected when sharing a file:

Selection_059


It can also be used to search for an account:

Selection_061


### ./occ entities:details 

returns details about an entity or an account:

Selection_060

Selection_062

**Comment by MorrisJobke** [comment]
> Need to add `"daita/nc-small-php-tools": "v1.0.4"` to composer in 3rdparty.

Then do this - add a PR to the 3rdparty repo, check out the branch in the server repo's 3rdparty folder and add this updated submodule to this PR here. Then for testing only "git submodule update" is needed 😉

**Comment by daita** [comment]
@MorrisJobke will do. I just wanted a quick review/first tests before adding 3rd party to the core !

**Comment by daita** [comment]
Viewers and Visibility is a thing when using the `./occ entities:search` command.

**Comment by daita** [comment]
###  :warning: Note about Visibility :warning: 
Currently, the visibility of all groups is a checkbox to allow sharing from people outside a group to the people within a group. This will be changed in EntitiesManager:

- on migration, the settings will be used when create new Entities, based on the existing groups
- then, default visibility on group creation will be based on a setting.
- visibility of a group can be switched per group, not a global value anymore.

**Comment by MorrisJobke** [comment]
Let's move this to 18.

**Comment by rullzer** [comment]
I'm going to close this due to lack of activity.
Feel free to reopen if anybody wants to continue.

**Pull request closed without merging**
