### PR TITLE
Improve the share link password error feedback with a red border

### PR DESCRIPTION
**Pull request by ChristophWurst**
I got the feedback that users occasionally miss the feedback that the password is to weak, and therefore sharing data without a password. This makes the error stick out more.

@skjnldsv as discussed the sharing dialogue should be migrated to a real dialog (as opposed to all the settings in the popover menu) where I user picks the important settings before the link is even generated. But we're not there yet.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Code looks good!

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by ChristophWurst** [comment]
> The backport to stable15 failed. Please do this backport manually.

https://github.com/nextcloud/server/pull/15128

**Comment by ChristophWurst** [comment]
> /backport to stable14

stable15 is sufficient for me

**Pull request merged**
