### PR TITLE
Set the default log rotate size to 100 MB

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Review by blizzz — APPROVED** [review]
:elephant:

**Comment by MorrisJobke** [comment]
:+1: for the changes of @rullzer

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Fixed the tests.

**Comment by blizzz** [comment]
@WNYmathGuy it's implemented for upcoming Nc 14:

screenshot_20180604_094537

**Comment by Gatak** [comment]
Is there a setting for how many rotations that should be kept?

**Comment by blizzz** [comment]
Please ask questions like this in help.nextcloud.com, thx!

**Pull request merged**
