### PR TITLE
Change script loading order in worflowengine

### LINKED ISSUE #31709: [Bug]: System tags workflows not working anymore
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The systemtags workflow component throws an error in the console:
```
 Uncaught TypeError: e.Files is undefined
    53076 systemtagmodel.js:28
    53076 systemtagmodel.js:75
    Webpack 7
```

https://github.com/nextcloud/server/blob/14e57bf70a612c16eccdd733b3562d46053419c5/core/src/systemtags/systemtagmodel.js#L28-L34

The problem seems that this bit is loaded before the OC.Files one in 
https://github.com/nextcloud/server/blob/b664aad7abdca5327684b1218ac78fa172f8acb3/apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php#L44

### Steps to reproduce

1. Have a workflow app installed, e.g. https://github.com/nextcloud/files_automatedtagging
2. Go to the admin settings
3. Open the console

### Expected behavior

All good

### Installation method

Other

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Master of all components
```

### List of activated Apps

```shell
files_automatedtagging + default install
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by artonge**
Fix: https://github.com/nextcloud/server/issues/31709

Signed-off-by: Louis Chemineau <louis@chmn.me>

### CODE REVIEW

**Comment by szaimen** [comment]
@artonge I grepped for `script(` in our codebase and code these places potentially be broken as well?
See 
<details>
<summary>click to expand</summary>

```
./core/templates/login.php:script('core', 'login');
./core/templates/publicshareauth.php:   script('core', 'publicshareauth');
./core/templates/recommendedapps.php:script('core', 'recommendedapps');
./core/templates/installation.php:script('core', 'install');
./core/templates/loginflow/grant.php:script('core', 'login/grant');
./core/templates/loginflow/authpicker.php:script('core', 'login/authpicker');
./core/templates/loginflowv2/grant.php:script('core', 'login/grant');
./core/templates/loginflowv2/authpicker.php:script('core', 'login/authpicker');
./apps/user_ldap/templates/renewpassword.php:script('user_ldap', 'renewPassword');
./apps/user_ldap/templates/settings.php:script('user_ldap', [
./apps/federation/templates/settings-admin.php:script('federation', 'settings-admin');
./apps/theming/templates/settings-admin.php:script('theming', 'settings-admin');
./apps/theming/templates/settings-admin.php:script('theming', '3rdparty/jscolor/jscolor');
./apps/settings/templates/settings/admin/security.php:script('settings', 'vue-settings-admin-security');
./apps/settings/templates/settings/admin/server.php:script('settings', [
./apps/settings/templates/settings/admin/delegation.php:script('settings', 'vue-settings-admin-delegation');
./apps/settings/templates/settings/frame.php:script('settings', 'settings');
./apps/settings/templates/settings/frame.php:script('core', 'setupchecks');
./apps/settings/templates/settings/frame.php:script('files', 'jquery.fileupload');
./apps/settings/templates/settings/personal/security/password.php:script('settings', [
./apps/settings/templates/settings/personal/security/password.php:      script('settings', 'security_password');
./apps/settings/templates/settings/personal/security/webauthn.php:script('settings', 'vue-settings-personal-webauthn');
./apps/settings/templates/settings/personal/security/authtokens.php:script('settings', 'vue-settings-personal-security');
./apps/settings/templates/settings/personal/personal.info.php:script('settings', [
./apps/settings/templates/settings-vue.php:script('settings', 'vue-settings-apps-users-management');
./apps/systemtags/templates/admin.php:script('core', 'systemtags');
./apps/systemtags/templates/admin.php:script('systemtags', 'admin');
./apps/twofactor_backupcodes/templates/personal.php:script('twofactor_backupcodes', 'settings');
./apps/files_sharing/templates/Settings/personal.php:script(\OCA\Files_Sharing\AppInfo\Application::APP_ID, 'personal-settings');
./apps/updatenotification/templates/admin.php:script('updatenotification', 'updatenotification');
./apps/encryption/templates/settings-admin.php:script('encryption', 'settings-admin');
./apps/encryption/templates/settings-personal.php:script('encryption', 'settings-personal');
./apps/encryption/appinfo/app.php:\OCP\Util::addscript('encryption', 'encryption');
./apps/files/templates/settings-personal.php:script(\OCA\Files\AppInfo\Application::APP_ID, 'personal-settings');
./apps/oauth2/templates/admin.php:script('oauth2', 'oauth2');
./apps/federatedfilesharing/templates/settings-admin.php:script('federatedfilesharing', 'settings-admin');
./apps/federatedfilesharing/templates/settings-personal.php:script('federatedfilesharing', 'settings-personal');
./apps/dav/templates/settings-admin-caldav.php:script('dav', 'settings-admin-caldav');
./apps/dav/templates/settings-personal-availability.php:script('dav', 'settings-personal-availability');
./apps/sharebymail/templates/settings-admin.php:script('sharebymail', 'settings-admin');
./apps/files_external/templates/settings.php:   script('files_external', [
./apps/files_external/templates/settings.php:                   script('files_external', $script);
./apps/files_external/templates/settings.php:                   script('files_external', $script);
./apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php:           script('core', 'systemtags');
./apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php:           script(Application::APP_ID, [
./lib/private/legacy/template/functions.php:function script($app, $file = null) {
./lib/private/legacy/template/functions.php:function vendor_script($app, $file = null) {
./build/stubs/intl.php:function locale_get_script($locale) { }
./build/stubs/intl.php:function locale_get_display_script($locale, $in_locale = null) { }
./build/stubs/redis.php:     * $sha = $redis->script('load', $script);
./build/stubs/redis.php:     * $redis->script('load', $script);
./build/stubs/redis.php:     * $redis->script('flush');
./build/stubs/redis.php:     * $redis->script('kill');
./build/stubs/redis.php:     * $redis->script('exists', $script1, [$script2, $script3, ...]);
./build/stubs/redis.php:    public function script($command, $script)
./build/stubs/redis_cluster.php:     * $sha = $redisCluster->script('load', $script);
./build/stubs/redis_cluster.php:     * $redisCluster->script(['127.0.0.1',6379], 'load', $script);
./build/stubs/redis_cluster.php:     * $redisCluster->script(['127.0.0.1',6379], 'flush');
./build/stubs/redis_cluster.php:     * $redisCluster->script(['127.0.0.1',6379], 'kill');
./build/stubs/redis_cluster.php:     * $redisCluster->script(['127.0.0.1',6379], 'exists', $script1, [$script2, $script3, ...]);
./build/stubs/redis_cluster.php:    public function script($nodeParams, $command, $script) { }
./3rdparty/aws/aws-sdk-php/src/ConnectParticipant/ConnectParticipantClient.php: * @method \Aws\Result getTranscript(array $args = [])
```

</details>

**Comment by artonge** [comment]
> @artonge I grepped for `script(` in our codebase and could these places potentially be broken as well?

Hopefully not, I upgraded to `Util::addScript` as `script` is deprecated, but it would have worked with `script` as the problem was only in the order that the scripts were added.

**Review by blizzz — APPROVED** [review]

**Comment by szaimen** [comment]
> > @artonge I grepped for `script(` in our codebase and could these places potentially be broken as well?
> 
> Hopefully not, I upgraded to `Util::addScript` as `script` is deprecated, but it would have worked with `script` as the problem was only in the order that the scripts were added.

Good to know! But this looks still wrong to me:


> ./apps/encryption/appinfo/app.php:\OCP\Util::addscript('encryption', 'encryption');

**Comment by artonge** [comment]
> Good to know! But this looks still wrong to me:

First argument is the app, second one is the script, so the line targets [apps/encryption/js/encryption.js](https://github.com/nextcloud/server/blob/master/apps/encryption/js/encryption.js)

**Comment by szaimen** [comment]
> > Good to know! But this looks still wrong to me:
> 
> First argument is the app, second one is the script, so the line targets [apps/encryption/js/encryption.js](https://github.com/nextcloud/server/blob/master/apps/encryption/js/encryption.js)

Yes, I understood that but it looks to me like it should be `addScript` instead of `addscript` or do both work?

**Review by szaimen — APPROVED** [review]

**Pull request merged**
