### PR TITLE
File modification date shine through on scroll

### PR DESCRIPTION
**Pull request by hamza221**
## Summary
Steps to reproduce: 

1. go to  files
2. make sure you have enough files to scroll
3. scroll
4. Look at the top right corner
Before :
image
After :
image
## TODO

- [x] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — CHANGES_REQUESTED** [review]
I fear this will reintroduce https://github.com/nextcloud/server/issues/33872

**Comment by hamza221** [comment]
It's not the case as far as i see
https://user-images.githubusercontent.com/40746210/233688960-4583d1a6-cd2f-4870-a97b-5503efc7b757.mov

**Review by szaimen — CHANGES_REQUESTED** [review]
See 

https://user-images.githubusercontent.com/42591237/233722166-95442222-93bb-4564-b2c7-9cc256ff1a39.mp4

**Comment by hamza221** [comment]
It should be good now, It looks good on my end. Can you please give it a test

**Comment by hamza221** [comment]
https://user-images.githubusercontent.com/40746210/233849024-f1ffae33-f51d-4e00-a630-746a7203d727.mov

**Review by szaimen — CHANGES_REQUESTED** [review]
Alternative, less intrusive approach in https://github.com/nextcloud/server/pull/37895

**Comment by hamza221** [comment]
This is the only work around I found without any side effects on other components. I'm open for other suggestions

**Review by szaimen — CHANGES_REQUESTED** [review]
This seems to break on the public share link page:
image

**Review by szaimen — APPROVED** [review]
Works now

**Comment by HannesJo0139** [comment]
So is anything happening here? Just updated 2 major versions to current 27.1.1 and it is still broken?

**Comment by hamza221** [comment]
the bug fixed on 28 with #39808 I think, But still exists on stable versions, should I change base then  backport it once merged ? what do you think @szaimen

**Comment by szaimen** [comment]
> the bug fixed on 28 with #39808 I think, But still exists on stable versions, should I change base then backport it once merged ? what do you think @szaimen

yes, I guess so. However the approach seems to be a bit scary to me...

**Pull request closed without merging**
