### PR TITLE
fix: Drop unnecessary exit

### PR DESCRIPTION
**Pull request by artonge**
This is making the CI stop for no good reason.

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
I will push commits here to fix the tests if needed because I broke at least ServerTest in the mean time.

**Review by provokateurin — APPROVED** [review]

**Comment by provokateurin** [comment]
Looks like it also hid some errors from the PR that caused this @artonge

**Comment by come-nc** [comment]
Tests from https://github.com/nextcloud/server/pull/47986 were completely broken, I fix the most obvious errors but for the rest I leave it up to @icewind1991 or anyone willing.

**Comment by come-nc** [comment]
```
PHP Fatal error:  Cannot redeclare print_exception() (previously declared in /home/runner/actions-runner/_work/server/server/core/templates/xml_exception.php:8) in /home/runner/actions-runner/_work/server/server/core/templates/xml_exception.php on line 8
72
Script phpunit --configuration tests/phpunit-autotest.xml handling the test event returned with error code 255
73
Script @composer run test -- --group DB,SLOWDB handling the test:db event returned with error code 255
```

**Comment by come-nc** [comment]
> ```
> PHP Fatal error:  Cannot redeclare print_exception() (previously declared in /home/runner/actions-runner/_work/server/server/core/templates/xml_exception.php:8) in /home/runner/actions-runner/_work/server/server/core/templates/xml_exception.php on line 8
> Script phpunit --configuration tests/phpunit-autotest.xml handling the test event returned with error code 255
> Script @composer run test -- --group DB,SLOWDB handling the test:db event returned with error code 255
> ```

This is from `apps/dav/tests/unit/Connector/Sabre/RequestTest/UploadTest.php` but I do not understand the issue.

**Comment by cfiehe** [comment]
> Tests from #47986 were completely broken, I fix the most obvious errors but for the rest I leave it up to @icewind1991 or anyone willing.

Thanks for fixing and sorry for the trouble. The test runs were blocked on my fork, otherwise I would have tried to fix the issues before. I have not found a way to get them running locally. Is there any way to see, if the new tests succeed or still cause trouble?

**Comment by come-nc** [comment]
> > Tests from #47986 were completely broken, I fix the most obvious errors but for the rest I leave it up to @icewind1991 or anyone willing.
> 
> @come-nc Thanks for fixing and sorry for the trouble. The test runs were blocked on my fork, otherwise I would have tried to fix the issues before. I have not found a way to get them running locally. Is there any way to see, if the new tests succeed or still cause trouble?

They still fail, you cannot see the failures in CI yet because there is a crash but @artonge just fixed it so next run should show them hopefully.
You should be able to run them locally with: ./autotest.sh sqlite tests/lib/Files/ObjectStore/
I do not remember if `composer install` first is needed and if it is enough to setup phpunit though.

**Comment by icewind1991** [comment]
> > > Tests from #47986 were completely broken, I fix the most obvious errors but for the rest I leave it up to @icewind1991 or anyone willing.
> > 
> > 
> > @come-nc Thanks for fixing and sorry for the trouble. The test runs were blocked on my fork, otherwise I would have tried to fix the issues before. I have not found a way to get them running locally. Is there any way to see, if the new tests succeed or still cause trouble?
> 
> They still fail, you cannot see the failures in CI yet because there is a crash but @artonge just fixed it so next run should show them hopefully. You should be able to run them locally with: ./autotest.sh sqlite tests/lib/Files/ObjectStore/ I do not remember if `composer install` first is needed and if it is enough to setup phpunit though.

https://github.com/nextcloud/server/pull/48160 fixes them

**Comment by artonge** [comment]
/backport d2bf3613f6c9210a720bebdcf82284bbfc604319 to stable30

**Comment by artonge** [comment]
/backport d2bf3613f6c9210a720bebdcf82284bbfc604319 to stable29

**Comment by artonge** [comment]
/backport d2bf3613f6c9210a720bebdcf82284bbfc604319 to stable28

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/48205 for a backport that includes all the fixes needed to get ci green

**Pull request merged**
