### PR TITLE
CalDAV: Add ability to limit sharing to owner

### PR DESCRIPTION
**Pull request by georgehrke**
|User| Before | After |
|:---------:|:-------:|:------:|
|Owner|700E4FDB-DB30-45DF-981D-FF18FDA23132|700E4FDB-DB30-45DF-981D-FF18FDA23132|
|Sharee|D25015FC-F299-443F-B465-CD7BCBC5C08A|A0062825-CC7F-4828-AFAA-51C89B72C134|

### CODE REVIEW

**Comment by georgehrke** [comment]
Rebased and squashed

**Review by rullzer — APPROVED** [review]
Didn't test but looks good

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
This fixed some psalm warnings: https://github.com/nextcloud/server/pull/22287

**Comment by georgehrke** [comment]
@MorrisJobke @rullzer Would you mind if we backport this? It's only needed on 19

**Comment by MorrisJobke** [comment]
Fine with me

**Pull request merged**
