### PR TITLE
30.0.0 RC3

### PR DESCRIPTION
**Pull request by blizzz**
Could not find base or head reference on twofactor_nextcloud_notification.

* #47219
* #47398
* #47404
* #47422
* #47429
* #47434
* #47436
* #47437
* #47442
* #47454
* #47471
* #47475
* #47483
* #47492
* #47498
* #47499
* #47505
* #47512
* #47514
* #47518
* #47528
* #47533
* #47539
* #47542
* #47543
* #47545
* #47547
* #47550
* #47559
* #47561
* #47564
* #47574
* #47578
* #47583
* #47587
* #47588
* #47593
* #47597
* #47607
* nextcloud/activity#1759
* nextcloud/files_pdfviewer#1026
* nextcloud/files_pdfviewer#1032
* nextcloud/firstrunwizard#1328
* nextcloud/firstrunwizard#1329
* nextcloud/firstrunwizard#1334
* nextcloud/firstrunwizard#1339
* nextcloud/firstrunwizard#1340
* nextcloud/notifications#2017
* nextcloud/photos#2626
* nextcloud/recommendations#778
* nextcloud/related_resources#464
* nextcloud/text#6238
* nextcloud/text#6260
* nextcloud/text#6261
* nextcloud/text#6262
* nextcloud/text#6263
* nextcloud/text#6270
* nextcloud/text#6278
* nextcloud/text#6279
* nextcloud/viewer#2444

## Pending PRs:
* @akhil1508
  * [ ] nextcloud/activity#1635
* @ArtificialOwl
  * [ ] nextcloud/circles#1089
  * [ ] nextcloud/circles#1090
  * [ ] nextcloud/circles#1148
  * [ ] nextcloud/circles#1214
  * [ ] nextcloud/circles#1217
  * [ ] nextcloud/circles#1394
  * [ ] nextcloud/circles#891
  * [ ] nextcloud/circles#980
* @backportbot
  * [ ] #47484
* @danxuliu
  * [ ] nextcloud/files_pdfviewer#654
* @grnd-alt
  * [ ] nextcloud/text#5690
* @Jerome-Herbinet
  * [ ] nextcloud/circles#1422
* @joshtrichards
  * [ ] nextcloud/suspicious_login#875
  * [ ] nextcloud/updater#571
* @madmas
  * [ ] nextcloud/activity#460
* @makoehr
  * [ ] nextcloud/updater#471
* @onny
  * [ ] nextcloud/circles#1349
* @rotdrop
  * [ ] nextcloud/circles#1297
* @ShGKme
  * [ ] nextcloud/viewer#1711
* @susnux
  * [ ] nextcloud/photos#2312
* @tortuetorche
  * [ ] nextcloud/circles#395
* (generated)
  * [ ] nextcloud/files_pdfviewer#1024
  * [ ] nextcloud/files_pdfviewer#1028

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by susnux** [comment]
If possible:
- [ ] https://github.com/nextcloud/firstrunwizard/pull/1340
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/1026

**Comment by solracsf** [comment]
Nice to have to:
[ ] https://github.com/nextcloud/server/pull/47607

**Comment by blizzz** [comment]
> Nice to have to:
> 
>     * [ ]  [[stable30] fix(files): Remove margin and width to not break layout #47607](https://github.com/nextcloud/server/pull/47607)


Mh, wanted to build soon, let me check. otherwise it will be in rc4 next week.

**Comment by blizzz** [comment]
also needed:

- https://github.com/nextcloud/server/pull/47612

**Pull request merged**
