### PR TITLE
fix(S3ConfigTrait): Allow proxy field to take false

### PR DESCRIPTION
**Pull request by provokateurin**
https://github.com/nextcloud/server/pull/47984

## Summary

Can be false: https://github.com/nextcloud/server/blob/01478f1c406cdbed7e5f6a52c0ebed040405ff29/lib/private/Files/ObjectStore/S3ConnectionTrait.php#L40

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by sorbaugh — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]

**Comment by provokateurin** [comment]
In stable28 the field is still in S3ConnectionTrait and not strongly typed, so no backport then.

**Pull request merged**
