### PR TITLE
Do not connect to database before creating it

### LINKED ISSUE #2646: 11: Installer does not create database
### Steps to reproduce
1. Get Ubuntu 16.04 server, install dependencies (mysql + apache2)
2. Move folder from tar.gz in your web root 
3. Open installer page
4. Enter valid mysql credentials (with CREATE priv) e.g. debian-sys-maint
5. for mysql but use a DB name that does not yet exist

[As ansible](https://github.com/lightonflux/ansible-nextcloud)

### Expected behaviour

NC 11 should create that database. And does that in 10.

### Actual behaviour

NC 11 complains that no database of that name exists 

### Server configuration
**Operating system**:
Ubuntu 16.04 on Digital Ocean (not sure if they use unchanged Ubuntu Server)
 
**Web server:**
Apache2 from repos
**Database:**
Mysql from repos
**PHP version:**
From Ubuntu Repos
**Nextcloud version:** (see Nextcloud admin page)
11
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh tar.gz. install
**Where did you install Nextcloud from:**
The tar file
**Signing status:**
OK

**List of activated apps:**
Default after fresh 11 install

**Are you using encryption:** 

no

**Are you using an external user-backend, if yes which one:** 
no

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #2646 

broken by https://github.com/nextcloud/server/pull/381/files#diff-93de257bbddb07009f7fd887790d0b5cL96 through @icewind1991 

Please test @enoch85 @lightonflux @ greyltc

### CODE REVIEW

**Comment by enoch85** [comment]
:+1: This solves https://github.com/nextcloud/server/issues/2661

Now I can use root password and DB + user is created.

Thanks for the fix, I spent 6 hours on this yesterday thinking I was doing something wrong...

**Comment by enoch85** [comment]
Btw, this should be 11.0.1 IMHO as it worked on 10.0.2 and broke in 11, so this is a bugfix for 11.0.1, right?

**Comment by nickvergessen** [comment]
This goes into 12 and is then backported for 11.0.1 (hence the backport-request label)

**Review by icewind1991 — APPROVED** [review]

**Comment by enoch85** [comment]
@nickvergessen Missed that ;)

**Pull request merged**
