### PR TITLE
replace ownCloud with Nextcloud

### PR DESCRIPTION
**Pull request by schiessle**
Replace "ownCloud" with "Nextcloud" in welcome.txt. This only affect stable10 branch, previews and newer branches are OK

### CODE REVIEW

**Review by MariusBluem — APPROVED** [review]

**Comment by LukasReschke** [comment]
This breaks the DAV integration tests. Care to take a look? THX.

**Comment by schiessle** [comment]
There are exceptions like "Insufficient Storage" don't think this has something to do with replacing ownCloud with Nextcloud in the welcome.txt. 😉 

Let's try once more...

**Comment by LukasReschke** [comment]
> There are exceptions like "Insufficient Storage" don't think this has something to do with replacing ownCloud with Nextcloud in the welcome.txt. 😉

You would be surprised 😉 

https://github.com/nextcloud/server/search?utf8=%E2%9C%93&q=%22welcome.txt%22

**Comment by schiessle** [comment]
> You would be surprised

I will never understand why we use real data for testing. Shouldn't be to hard to use a dedicated test file to avoid such situations. Anyway I adjusted the tests, let's see what happens...

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
