### PR TITLE
Set proper defaults for v-tooltip usages

### PR DESCRIPTION
**Pull request by juliusknorr**

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by juliushaertl** [comment]
Needs another fix in the settings app

**Comment by juliushaertl** [comment]
Done, settings needed to be specified with `Vue.use(VTooltip, { defaultHtml: false })` instead of overwriting the options default, since they use the provided vue plugin instead of the directive.

**Pull request merged**
