### PR TITLE
Fix duplicated UUID detection when there are empty uuids

### PR DESCRIPTION
**Pull request by come-nc**
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Review by skjnldsv — COMMENTED** [review]
Could we cover that through tests?

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by CarlSchwan — APPROVED** [review]

**Comment by come-nc** [comment]
> Could we cover that through tests?

Not that easily and not in a useful way I think.

**Pull request merged**
