### PR TITLE
Add more keys as sensitive values

### LINKED ISSUE #12925: nextcloud issue template `occ config:list system` fails to remove all domain sensitive data
### Steps to reproduce
Per the template (this exact one), later in the template it directs the user to run `sudo -u www-data php occ config:list system`, this is awesome to wipe sensitive data, and things are replaced with "***REMOVED SENSITIVE VALUE***".

### Expected behaviour
config dumper SHOULD also remove DOMAIN/HOST sensitive data.
i.e. in reverse proxy configurations

specifically, I think we're talking about:

1. entries in `trusted_domains`
2. entry for `overwritehost` 

### Actual behaviour
Ran this:
```
root@nextcloud:/srv/nextcloud# sudo -u www-data php occ config:list system
```
, and the output was this:
(!) NOTE: I snipped my domain MANUALLY and replaced it with: "mydomain.snipped.for.reasons.but.was.not.snipped.by.tool"
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud",
            "mydomain.snipped.for.reasons.but.was.not.snipped.by.tool"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "mydomain.snipped.for.reasons.but.was.not.snipped.by.tool",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/cloud",
        "overwritecondaddr": "^1\\.0\\.0\\.52$",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "https:\/\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "updater.release.channel": "stable"
    }
}
```

### Server configuration

**Operating system**: `Ubuntu 16.04 LTS`
**Web server:** `Apache2?`
**Database:** `mysql 14.0.X`
**PHP version:** `7.0.32-0ubuntu0.16.04.1`
**Nextcloud version:**  `Nextcloud 14.0.3`
**Updated from an older Nextcloud/ownCloud or fresh install:** `Upgraded a few times so far`

### PR DESCRIPTION
**Pull request by kesselb**
Close #12925

### CODE REVIEW

**Comment by nickvergessen** [comment]
I still disagree on the cli url, its the point of trouble for a lot of issues

**Comment by danielkesselberg** [comment]
Ok. What do you suggest?

**Comment by nickvergessen** [comment]
I suggest to close the issue + pr

**Comment by MorrisJobke** [comment]
> I suggest to close the issue + pr

Closing this PR here then.

**Pull request closed without merging**
