### PR TITLE
l10n: Spelling unification

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Transifex.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks :+1: 

https://github.com/nextcloud/server/blob/ecbc009e2fc8aa7fd078634f4cb2271fded69fb6/apps/dav/tests/unit/Connector/Sabre/MaintenancePluginTest.php#L58 needs an update.

**Comment by Valdnet** [comment]
@kesselb Thanks. System updated 😉.

**Review by rakekniven — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
