### PR TITLE
Allow stdClass in XML responses

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

Allows returning `\stdClass()` in DataResponse that are encoded to XML.
JSON can already to it and converts it to `{}`, but for XML special handling is required.

This change is required in order to properly describe APIs using empty JSON objects (`[]` gets converted to `[]` in JSON instead of `{}`). XML just also needs to support it.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Review by ChristophWurst — COMMENTED** [review]
Could this be tested in ``\Test\AppFramework\Middleware\BaseResponseTest``?

**Review by ChristophWurst — APPROVED** [review]

**Comment by AlexM4H** [comment]
Many thanks for the PR. A backport to Nextcloud 27.1.0 would be desirable.

**Comment by provokateurin** [comment]
@AlexM4H does it fix a bug for you? This was only meant as a feature, so it doesn't get any backport

**Comment by AlexM4H** [comment]
It fixes #33330  for me.

**Comment by provokateurin** [comment]
On a technical level this is still a bug with the respective apps and not the core as this was never supported. @ChristophWurst @come-nc shall we backport it anyway?

**Comment by come-nc** [comment]
Hard to say. Backporting API change is always dangerous as it may trigger subtle sideeffects.
On the other hand if it fixes bugs…

Without this an stdClass is just stripped from XML output?

@provokateurin I think you’re more knowledgeable than me to decide whether to backport.

**Comment by provokateurin** [comment]
It's not breaking at all, but if an app returns stdClass the output without this patch would just be empty thus broken.

I still feel like the apps should fix it themselves as any version before this patch is broken. That would mean apps can target <28 if they rely on this.

**Comment by AlexM4H** [comment]
Please keep in mind that Forms is a featured app. "Featured apps are developed by and in the community. They provide core functionality and are ready for production use."

The fix would be necessary for some app developers for NC 26 / 27, as NC 28 already includes the fix as a new feature.

**Comment by AlexM4H** [comment]
The corresponding issue is still open 

https://github.com/nextcloud/forms/issues/1469

**Comment by Chartman123** [comment]
@AlexM4H yes, I know. We're waiting for a server fix there 😆 

My question was for @provokateurin 😉

**Comment by provokateurin** [comment]
> Please keep in mind that Forms is a featured app. "Featured apps are developed by and in the community. They provide core functionality and are ready for production use."

Sorry, this is not helpful. This is a bug with the app and not the core.

As I said the behavior the forms app is relying on was never intended to work (in previous versions). I added this as a feature but it is only available in >=28. If you target 28 and higher you can surely rely on it.

For example Talk also had to work around it like this: https://github.com/nextcloud/spreed/blob/eaf04bbe5a7626cc1565cc455124f8a10b2ff078/lib/Model/Message.php#L163

cc @DaphneMuller

**Comment by Chartman123** [comment]
> For example Talk also had to work around it like this

Thanks I'll have a look at it :)

**Comment by provokateurin** [comment]
In the future when you target >=28 you can of course drop the workaround.

**Pull request merged**
