### PR TITLE
fix(OC_Helper): Use correct binary notation for calculating human file sizes

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

Follows proper IEC 60027-2 notation.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by provokateurin** [comment]
Ok let's just stick to the wrong but established notation.

**Comment by susnux** [comment]
@provokateurin yes it was decided not to confuse existing users by switch the naming schema: https://github.com/nextcloud/server/pull/40621

In general it is a bit difficult, most users are spoiled by Windows using the wrong notation. But then there is Mac which is even weirder.

**Pull request closed without merging**
