### PR TITLE
Add option to set overwrite.cli.url for occ install

### LINKED ISSUE #6313: 'occ maintenance:install' sets 'overwrite.cli.url' to 'http://localhost'
Hello,

for some reason, `overwrite.cli.url` is always set to `http://localhost` after manual installation of Nextcloud via `occ maintennce:install`.

### Steps to reproduce
1. Download nextcloud-12.0.2.zip, unzip and move into folder
2. php occ maintenance:install --database=mysql --database-name=nextcloud --database-user=nextcloud --database-pass=... --admin-pass=...
3. cat config/config.php

```
[...]
  'overwrite.cli.url' => 'http://localhost',
[...]
```

### Expected behaviour
`overwrite.cli.url` should not be set

### Server configuration

**Operating system:** Debian 9.0 Stretch
**Web server:** Apache2
**Database:** MariaDB
**PHP version:** 7.0.19
**Nextcloud version:** 12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install
**Where did you install Nextcloud from:** zip file

### PR DESCRIPTION
**Pull request by kesselb**
Set overwrite.cli.url for occ maintenance:install

Close #6313

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Is really the option needed or can't we just fix the breaking statement? Because I would avoid to put more options in the install command.

Alternative way is to create a file `config/NAME.config.php` with this as content:

```php
<?php

$CONFIG = [
	'overwrite.cli.url' => 'https://cloud.example.org',
];
```

This file will then be merge in the config by default and will overwrite the one in config.php.

**Comment by danielkesselberg** [comment]
> Alternative way is to create a file `config/NAME.config.php` with this as content:

For an automated setup i guess there is no huge difference (appending another option vs. prepare config.php). I took the issue because of https://github.com/nextcloud/server/labels/Hacktoberfest :see_no_evil:

**Comment by MorrisJobke** [comment]
> For an automated setup i guess there is no huge difference (appending another option vs. prepare config.php).

It's not about admins, but about us. Because we then need to maintain multiple ways of doing it. 😉

**Comment by danielkesselberg** [comment]
> > For an automated setup i guess there is no huge difference (appending another option vs. prepare config.php).
> 
> It's not about admins, but about us. Because we then need to maintain multiple ways of doing it. wink

Fine for me  :+1:

**Comment by MorrisJobke** [comment]
> Fine for me 👍

But the general fix in here is still nice to have. Or did it only fix the issue when the option was provided?

**Comment by danielkesselberg** [comment]
The issue is only fixed when option provided. https://github.com/nextcloud/server/blob/c0a283fefb166e7ca09ef74898564fdd968cc2b1/lib/private/AppFramework/Http/Request.php#L816-L822
`localhost` is coming from this place because there is no way to detect url when using occ.

**Pull request closed without merging**
