### PR TITLE
fix: Show error message when CSRF check fails at login

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Helps with: https://github.com/nextcloud/server/issues/32538

## Summary

This is also known as the "double login"

## How to test

0. Be logged out
1. Open the login page
2. Clear browser cookies
3. Enter credentials and submit the form

master: you see the same page again, no changes
here: you see the same page again but with an error message

| Before | After |
|--------|--------|
| Bildschirmfoto vom 2023-10-06 10-52-06 | Bildschirmfoto vom 2023-10-06 12-41-26 | 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by solracsf** [comment]
I would recommend a message like "**Internal checks failed. Please try again.**".
Why ? Because at least user knows this is not a password or user problem, but a temporary server (internal) issue.

**Comment by ChristophWurst** [comment]
Adjusted. I also fixed that the NcNoteCard was used incorrectly.

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
