### PR TITLE
Add mimetype application/internet-shortcut for .url files

### PR DESCRIPTION
**Pull request by te-online**
If you create a shortcut file on a Windows system to a internet-resource it will have the format .url with one of the mime-types being application/internet-shortcut. This adds a nice icon for these files.

For reference see https://en.wikipedia.org/wiki/Bookmark_(World_Wide_Web)#Storage, http://www.lyberty.com/encyc/articles/tech/dot_url_format_-_an_unofficial_guide.html and http://justsolve.archiveteam.org/wiki/Internet_Shortcut.

Example:
bildschirmfoto 2017-08-29 um 12 04 02

### CODE REVIEW

**Comment by raghunayyar** [comment]
@nextcloud/designers

**Review by jancborchardt — APPROVED** [review]
Seems a reasonable addition, since no other icon really fits. :)

**Review by MariusBluem — APPROVED** [review]

**Comment by rullzer** [comment]
I guess we will need a repair step here as well. To update existing ones. I can look once not on my phone.

**Comment by te-online** [comment]
@rullzer I have no idea on how to add a repair step. if you have any guidance on that, I can look into that myself. :-)

**Comment by MorrisJobke** [comment]
> @rullzer I have no idea on how to add a repair step. if you have any guidance on that, I can look into that myself. :-)

Add it here: https://github.com/nextcloud/server/blob/master/lib/private/Repair/RepairMimeTypes.php

**Comment by pixelipo** [comment]
cool! Nice work optimizing/standardizing SVG, too :+1:

**Comment by te-online** [comment]
For the sake of completeness I added the macOS .webloc filetype as well (when we already need to add a new repair step...).

I also checked Linux. On Linux weblinks seem to be stored in .desktop files, which can hold links to local resources as well (like programs), if I remember correctly? So the .desktop file doesn't have a single usecase, hence no single mimetype, right? (See also  https://askubuntu.com/questions/353932/equivalent-of-url-file-on-ubuntu).

Hope this works as expected now. Change the version in the repair script if necessary, I wasn't sure about that.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by te-online** [comment]
@MorrisJobke Working on it... 😓 😅

**Pull request merged**
