### PR TITLE
Various comments fixes

### PR DESCRIPTION
**Pull request by skjnldsv**
- Prevent submitting empty messages
- Fix white-spacing
- Hide long messages like it was before (click to unroll)
- Fix undo timeout by bumping the nextcloud dialogs
- Add mentions data
  Capture d’écran_2020-10-21_16-29-51

Follow-up #23173

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by blizzz** [comment]
from the screenshots, does it fix a bug where the display name was not shown, or does it now show the internal user id?

**Comment by skjnldsv** [comment]
> from the screenshots, does it fix a bug where the display name was not shown, or does it now show the internal user id?

I have no idea what bug you are refering to. We're now using the data provided by the comments>mentions dav properties. SO it should render as it used to :)

**Comment by blizzz** [comment]
> > from the screenshots, does it fix a bug where the display name was not shown, or does it now show the internal user id?
> 
> I have no idea what bug you are refering to. We're now using the data provided by the comments>mentions dav properties. SO it should render as it used to :)

I think I misinterpreted the screenshot from the description. Never mind :)

**Review by jancborchardt — APPROVED** [review]

**Comment by skjnldsv** [comment]
Jsunit tests fixed

**Pull request merged**
