### PR TITLE
Increase timeout of the appstore requests

### PR DESCRIPTION
**Pull request by nickvergessen**
We all know the appstore can have bad days

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by georgehrke** [comment]
@nickvergessen Should we backport?

**Comment by georgehrke** [comment]
Some tests in `Test\App\AppStore\Fetcher\CategoryFetcherTest` seem to be failing

**Comment by nickvergessen** [comment]
Tests fixed and yeah should backport

**Review by JanDragon — APPROVED** [review]

**Comment by hast0011** [comment]
This time nextcloud 18.06-->18.07
Still not working for me when installing openoffice app from appstore. I have 16Mbit DSL and no chance to install because of the annoying timeout I get when trying with every new version.

**Comment by nickvergessen** [comment]
The problem was our server. the appstore and download of the desktop client were/are on the same physical machine and apparently a desktop client release fully satisfied the connection for some days.

**Pull request merged**
