### PR TITLE
dont hold a transaction during the move to trash

### PR DESCRIPTION
**Pull request by icewind1991**
because moving to trash can take a long time, keeping a transaction active for the duration can lead to issues

Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
@icewind1991 should this fix the deadlock things?

**Comment by icewind1991** [comment]
Yes

**Review by rullzer — APPROVED** [review]
Lets do it I guess!

**Review by nickvergessen — APPROVED** [review]

**Comment by axheli** [comment]
@nickvergessen I just appied the fix and still nothing getting the errors when deleting? or is the fix still being worked on? 

image

**Comment by acsfer** [comment]
I can confirm this **does not fix** https://github.com/nextcloud/server/issues/22482 on 19.0.3.

**Comment by DanScharon** [comment]
can we also get a backport to stable18?

**Comment by axheli** [comment]
hello any updates on this and the DeadlockException executing UPDATE `oc_filecache` #22482 issue?

**Comment by Broekman** [comment]
Also confirm that this does not fix the Deadlock issue. Any updates on this?

**Comment by upmferraz** [comment]
Also facing the same issue on version 19.05, running a occ filles:cleanup. My oc_filecache table is using 4Gb of space.

**Pull request merged**
