### PR TITLE
enh(users): send welcome email when using occ

### LINKED ISSUE #25319: No "Welcome" email sent when using `occ`.
Using the latest version of NextCloud, we discovered a problem that might be a bug.
We're using a CSV file to import our users into the system, via a small bash script that we created.

```
#!/bin/bash
USERS_CSV="$HOME/nextcloud-users.csv"
OCC="$HOME/public_html/occ"
OLDIFS=$IFS
IFS=","
while read username password displayName email group
 do
    export OC_PASS=$password
    echo "Adding user ${username} (${displayName} | ${password} | ${group})..."
    $OCC user:add --password-from-env --display-name "$displayName" --group "$group" "$username"
    echo "Setting ${username}'s email to ${email}..."
    $OCC user:setting "$username" settings email "$email"
done < $USERS_CSV
 IFS=$OLDIFS
```

This works great, and all users from the CSV file are added. However, none of them receive the "Welcome" email inviting them to set / reset their password.

### PR DESCRIPTION
**Pull request by helmo**
Enhance PR #40726

* Resolves: #25319 

## Summary

This PR tries to solve the remaining issues in #40726
Specifically from the comment https://github.com/nextcloud/server/pull/40726#pullrequestreview-1666910957

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by come-nc** [comment]
Changed target to master to see the whole diff, my comment on original PR still applies:

> This needs to work and set email:
> `occ user:add --password-from-env --email bob@example.com bob`

-> This you fixed, I think

> This needs to work and set email, if `newUser.sendEmail` is off it should ask for password same as without `--email`:
> `occ user:add --email bob@example.com bob`

-> This you did not, if `newUser.sendEmail` is off, a temporary password is printed to the output instead of asking for the password in interactive mode. Passing `--email` option when `newUser.sendEmail` is off should not prevent entering a password.

I’m not sure what the correct behavior is here, maybe simply add an other option `--generate-password`?
Because people may want the welcome email to be sent while still setting the password.

**Review by come-nc — CHANGES_REQUESTED** [review]
See above

**Comment by kyteinsky** [comment]
> I’m not sure what the correct behavior is here, maybe simply add an other option --generate-password?

Yeah it would be better to set a generated password when explicitly asked rather than implicitly based on other options.

dropped password printing commit and pushed the requested changes in [`feat/new-user-email` branch](https://github.com/nextcloud/server/pull/40726). Maybe I will add more tests later.

**Comment by kyteinsky** [comment]
merged here: #40726

**Pull request closed without merging**
