### PR TITLE
Don't try a transaction for the migrator on MySQL

### PR DESCRIPTION
**Pull request by nickvergessen**
As per https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html
CREATE TABLE statements automatically commit always. The only reason
this worked in the past was that PHPs PDO connection didn't check the
actual state on commit, but only checked their internal state.
But in PHP8 this was fixed:
https://github.com/php/php-src/blob/PHP-8.0/UPGRADING#L446-L450
So now commit() fails because the internal PDO connection implicitly
commited already.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Proof is at https://github.com/nextcloud/mail/pull/4319

**Review by blizzz — APPROVED** [review]
had successful CI runs as well, against both  7.4 and 8.0

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Comment by rullzer** [comment]
But CI says no https://drone.nextcloud.com/nextcloud/server/1195/11/5

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
