### PR TITLE
Add support for files with no permissions

### PR DESCRIPTION
**Pull request by danxuliu**
Until now it was safe to assume that every file was readable by its owner, but with the introduction of end to end encryption that is no longer the case. Therefore, the server now must explicitly return whether a file is readable or not, and the web UI has to be prepared to handle files with no permissions (which is simply a matter of fixing some code that assumed that the file would always have at least the read permission).

This is a requisite for proper handling of encrypted folders in #6670.

### CODE REVIEW

**Review by schiessle — APPROVED** [review]

**Comment by LukasReschke** [comment]
I'd love to have some thoughts of @icewind1991 or/and @rullzer on this. Is this the best approach? Or should we have a dedicated flag for the E2E? :)

**Comment by rullzer** [comment]
Mmmm I'm not sure this is right. Because the file is still readable by the owner. It is just encrypted.

If I'm not mistaken the folder that is encrypted has the encrypted flag set. @schiessle 

So the js should check for that...

**Comment by danxuliu** [comment]
>  Mmmm I'm not sure this is right. Because the file is still readable by the owner. It is just encrypted.

It is not readable, at least not from the point of view of the web UI (or any other insecure client). When installed in the server, the [E2E encryption app](https://github.com/nextcloud/end_to_end_encryption) blocks all the permissions in responses to `PROPFIND` requests, no matter the actual permissions of the file. So if an encrypted file can not be updated, deleted, shared... it should not be seen as readable either.

But encryption aside this pull request simply makes the readable permission more consistent with the other permissions; the other permissions are explicitly returned by the server if they are set for a file, but _readable_ was never returned and the web UI simply assumed that it was always set. Now the server explicitly returns the _readable_ permission if it is set for a file and the web UI honours the returned permissions.

>  If I'm not mistaken the folder that is encrypted has the encrypted flag set.
>  
>  So the js should check for that...

The reason to use the permissions instead of the encrypted flag was to avoid introducing specific cases and to use the general code instead (after the needed fixes, I mean ;-) ).

**Comment by rullzer** [comment]
Ok so if the app actually sets the permissions to non readable for files. Then yes lets just properly display this.

**Comment by blizzz** [comment]
@rullzer is this a +1?

**Comment by schiessle** [comment]
@rullzer can we merge this?

As explained by @danxuliu correctly. The end-to-end encryption app has a SabraDAV plugin which removes the read permission for all clients which don't support e2e encryption.

**Review by icewind1991 — APPROVED** [review]

**Pull request merged**
