### PR TITLE
More workflow frontend polishing

### PR DESCRIPTION
**Pull request by juliusknorr**
Another round of polishing for workflows as discussed at the contributor week:

- Rename to Flow
- Available actions as top header
- Configured flows as rule header
- green border around active, cursor should not be a pointer in active
- Move tags to basic settings, when working on the ui, move it to a dedicated section
- Add "More actions" button to the end, link to the app store
- add link to documentation for app developers

image

## ToDo for later polishing

- The icons in the action boxes can be a bit closer to the text below. Should have same distance from the text as the button below
- when a second row of operations is shown, don't hide its elements (the + is visible after all anyway)
- on wide windows, show more than 3 operations per row

### CODE REVIEW

**Comment by jancborchardt** [comment]
Great stuff! Only tiny things:
- [ ] The icons in the action boxes can be a bit closer to the text below. Should have same distance from the text as the button below
- [ ] "check out" is 2 words, and the sentence needs a dot at the end. Also, is "development documentation" linked → if not it should be.
- [ ] "Create a new rule" on the button should better be "Add new flow". We never use the word "rule" anywhere, and the 2 words "action" and "flow" are already enough terminology.
- [ ] "Configured flows" better "Your flows"?
- [ ] "Your flows" heading needs more whitespace to top. Usually we do this via a `class="section"` container, but since we use that for the flow list themselves we need to add it manually?


:+1:

**Comment by jancborchardt** [comment]
I’m also thinking to totally drop the "actions" term in favor of only saying "flow" everywhere.

- Headings: "Available flows" and "Your flows".
- Button: "Add new flow"
- Text; "For details on how to write your own flow, …"
- Box: "More flows" "Browse the app store"

This makes it much simpler and understandable. We don’t need to differentiate between "unfinished flows" and "flows". What do you think @karlitschek @jospoortvliet?

**Comment by blizzz** [comment]
Also needs https://github.com/nextcloud/appstore/pull/628

**Review by blizzz — APPROVED** [review]
for further polishing:
* when a second row of operations is shown, don't hide its elements (the + is visible after all anyway)
* on wide windows, show more than 3 operations per row

**Review by rullzer — APPROVED** [review]
Lets do this. And fix the rest in follow ups

**Comment by juliushaertl** [comment]
Fixed wording issues and rebase. Leaving the rest for polishing later.

**Comment by rullzer** [comment]
tests do :boom:

**Comment by juliushaertl** [comment]
Should run fine now, let's see

**Comment by rullzer** [comment]
Done!

@juliushaertl can you make issues out of the open todos?

**Pull request merged**
