### PR TITLE
Update Login with device page styles

### LINKED ISSUE #27530: Login with device page is not properly styled
* click on the "Login with device" link on the login page
* expect properly designed and styled page - white text, proper border radius for inputs, darker background for errors, error with icon
* actual:
Bildschirmfoto 2021-06-16 um 16 18 13
Bildschirmfoto 2021-06-16 um 16 23 46

Expected design:

Bildschirmfoto 2021-06-16 um 16 25 27
Bildschirmfoto 2021-06-16 um 16 25 38

cc @nextcloud/designers

### PR DESCRIPTION
**Pull request by Pytal**
Closes #27530

image
image
image

@nextcloud/designers

### CODE REVIEW

**Review by artonge — CHANGES_REQUESTED** [review]
Looks good !

Can you update the css selectors to use [BEM](http://getbem.com/introduction) ?

**Comment by Pytal** [comment]
> Looks good !
> 
> Can you update the css selectors to use [BEM](http://getbem.com/introduction) ?

Scoped class has been updated to use BEM, other classes used from `guest.css` have been left unchanged. Is this good or would copying `guest.css` style declarations into the scoped style section be preferred?

**Review by ChristophWurst — APPROVED** [review]

**Comment by artonge** [comment]
> Scoped class has been updated to use BEM, other classes used from `guest.css` have been left unchanged. Is this good or would copying `guest.css` style declarations into the scoped style section be preferred?

Yes, fine, lets not make this PR bigger than necessary :).

**Review by artonge — APPROVED** [review]

**Pull request merged**
