### PR TITLE
Fix default missing initial state for templates

### LINKED ISSUE #25790: Nextcloud 21 - Warning	no app in context	 "Invalid data provided to provideInitialState by files"
I am having this warning, and exhausted my search ability to find out what it is 

Warning | no app in context | Invalid data provided to provideInitialState by files

Every time file app is open, logs generate this

Is this a bug or can be ignored or what can i do?

### PR DESCRIPTION
**Pull request by skjnldsv**
fix #25790

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by Flaschenzug** [comment]
how do I fix this problem? Just had this error today, actual version is 21.0.3

**Comment by nickvergessen** [comment]
Should be fixed since 21.0.1, I guess you might have a slightly different error message or something which can then be from another app.
Best is to open a new issue with your exact error message, after making sure you updated your server and all the apps to the latest version

**Pull request merged**
