### PR TITLE
Show message if no other users with access are found

### LINKED ISSUE #18632: [18beta4] [Others with access] bad UX on empty list
When there are no _Others with access_, there's quite little feedback about that fact when you invoke the listing action.

others

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #18632
Show a small subtitle if no other users with access are found.

In action:

Peek 2020-01-06 21-51

### CODE REVIEW

**Review by wiswedel — APPROVED** [review]

**Comment by kesselb** [comment]
Hmm. You already know how many other people have access. Why don't we show this as subtitle otherwise? This would prevent this little jump.

**Comment by rullzer** [comment]
Yeah the title jump is not ideal. But good enough for a quick fix.
@nextcloud/designers for better ideas for 18.0.1 ;)

**Review by skjnldsv — APPROVED** [review]
:heart:

**Comment by jancborchardt** [comment]
> @nextcloud/designers for better ideas for 18.0.1 ;)

- Show the subtitle directly
- Don’t even show the triangle toggle on the right if there’s no others with access

**Comment by rullzer** [comment]
> > @nextcloud/designers for better ideas for 18.0.1 ;)
> 
>     * Show the subtitle directly
> 
>     * Don’t even show the triangle toggle on the right if there’s no others with access

We can't do that. The toggle triggers a request to the backend. And since this can be very costly. We don't want to do it on all openings of the sidebar.

**Comment by jancborchardt** [comment]
Ok, then different proposal:
If there are no others with access, on opening the "Others with access" menu, show an entry like a person entry saying:

> **No others with access**
> People with access to parent folders will show up here

**Comment by wiswedel** [comment]
> If there are no others with access, on opening the "Others with access" menu, show an entry like a person entry saying:
> 
> > **No others with access**
> > People with access to parent folders will show up here

I find that very user friendly and self-documenting

**Comment by rullzer** [comment]
@jancborchardt fine by me. Please fill an issue. And we'll see if we can tackle it for 18. Or if it has to wait for 18.0.1 because of time constraints.

**Pull request merged**
