### PR TITLE
[stable20] Update 3rdparty after Archive_Tar

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by mtierltd** [comment]
Hi

This change breaks installing some applications due to the changes in Archive_Tar,
if there are symlinks present in the archive, because extract() will return false.

**Comment by ChristophWurst** [comment]
Mind elaborating what kind of applications you are talking about? Nextcloud apps? Why would they have symlinks? Do you have any tickets?

**Comment by mtierltd** [comment]
A nextcloud application yes that has a symlink in the vendor directory, which was not a problem before.
This can be removed from the tarball, so no problem there, but I can tell you that the behavior of Archive_TAR
has changed and now extract() returns false on perfectly fine tarballs, breaking nextcloud application installation with Error: Could not extract app. (timetracker in this case).

We have been having issues after updating to 20.0.6 and I've done a test with Archive_Tar 1.4.12 which 
is included in 20.0.6 and it indeed returns false on extract, however Archive_Tar 1.4.11 and earlier versions
return true.

**Comment by ChristophWurst** [comment]
> timetracker

Please let the authors of that apps know that they are not supposed to put symlinks into their tarballs.

**Comment by ChristophWurst** [comment]
It's already known as per https://github.com/mtierltd/timetracker/issues/86 and https://github.com/mtierltd/timetracker/issues/90

**Comment by mtierltd** [comment]
Can you elaborate on why symlinks are not to be used? What is the technical reason behind it?

**Comment by ChristophWurst** [comment]
See the 3rdparty bump https://github.com/nextcloud/3rdparty/pull/603 for details

**Comment by mtierltd** [comment]
Okay so no technical reason. Thanks.

**Pull request merged**
