### PR TITLE
Rename parameter in OCP.Toast for consistency with OC.Notification

### LINKED ISSUE #16367: OCP.Toast mismatch to old OC.Notifications options
@juliushaertl There is a mismatch in the options received by OC.Notification and OCP.Toast: [OC.Notification uses isHTML](https://github.com/nextcloud/server/blob/2d0337332d64065c5bf36dfb775c48976c0f730d/core/src/OC/notification.js#L142), while [OCP.Toast uses showHtml](https://github.com/nextcloud/server/blob/6d848b545df054b994ca056a90c72661e4ef6e95/core/src/OCP/toast.js#L59). Either [`OCP.Toast.message` is adjusted](https://github.com/nextcloud/server/blob/6d848b545df054b994ca056a90c72661e4ef6e95/core/src/OCP/toast.js#L59-L64) to use `isHTML` too, or [`OC.Notification.showTemporary` is adjusted](https://github.com/nextcloud/server/blob/2d0337332d64065c5bf36dfb775c48976c0f730d/core/src/OC/notification.js#L147-L149) to set `options.showHtml` based on `options.isHTML` (and also the unit tests to reflect that [`OC.Toast.message` expects `showHtml` instead of `isHTML`](https://github.com/nextcloud/server/blob/6d848b545df054b994ca056a90c72661e4ef6e95/core/js/tests/specs/coreSpec.js#L941)).

_Originally posted by @danxuliu in https://github.com/nextcloud/server/pull/15124#issuecomment-510539647_

### PR DESCRIPTION
**Pull request by danxuliu**
Follow up to #15124
Fixes #16367

This fixes HTML messages in `OC.Notification.showTemporary` (as `showHtml` was not set based on `isHTML`), and also makes OCP.Toast to keep the old OC.Notification API when used directly.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
sure

**Comment by MorrisJobke** [comment]
JSUnit fails

**Comment by danxuliu** [comment]
> JSUnit fails

It should be fixed now.

**Comment by MorrisJobke** [comment]
Rebased and autosquashed.

**Pull request merged**
