### PR TITLE
getJailedPath expects $path to have a trailing /

### PR DESCRIPTION
**Pull request by icewind1991**
Downstream of https://github.com/owncloud/core/pull/25703

### CODE REVIEW

**Comment by rullzer** [comment]
LGTM

**Comment by LukasReschke** [comment]
LGTM

**Comment by LukasReschke** [comment]
We should also downstream https://github.com/owncloud/core/pull/25737 and https://github.com/owncloud/core/pull/25738 once merged

**Comment by schiessle** [comment]
stable10: https://github.com/nextcloud/server/pull/817
stable9: https://github.com/nextcloud/server/pull/818

**Pull request merged**
