### PR TITLE
Add back the total used space per user

### LINKED ISSUE #11217: 14.0.0.19 Hover over User Quota doesn't show used space anymore
### Steps to reproduce
1. As Admin go to Users an hover over the quota

### Expected behaviour
Up to NC 13 there was shown the used space in the Hoverbox:
hover-nc-13

### Actual behaviour
No hover-box with used space is shown:
hover-nc-14

### Server configuration
Tested on different servers.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #11217

### CODE REVIEW

**Review by JSoko — APPROVED** [review]
Yes, it works, thank You!

**Review by ChristophWurst — APPROVED** [review]
Code looks good :+1: 

Can be merged once CI is happy

**Comment by JSoko** [comment]
One small thing:
For users who use 0kb ist shows "unknown Space used"
Bug or feauture?
grafik

**Comment by skjnldsv** [comment]
@JSoko feature. The user did not logged in yet so the user folder doesn't exists.
Though I can say it's better for the user to see 0kb used even if it's not really true :)

I'll change this!

**Comment by skjnldsv** [comment]
Backport on #11425

**Pull request merged**
