### PR TITLE
set birthday year to 1970 if no year, take X-APPLE-OMIT-YEAR into account

### LINKED ISSUE #9849: Birthday without birthyear
From https://github.com/nextcloud/calendar/issues/842: should be opened on server.

Some apps, e.g. contacts on samsung allow to store the birthday without birthyear (in case you do not know how old somebody is).
These contacts are synced fine to NC, but the dates are not shown in the birthday calendar.
Those dates should be shown, e.g. with in a given date range (1970-2030).

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #9849

### CODE REVIEW

**Comment by tessus** [comment]
@georgehrke ok, so what happens, if someone is born in 1970?

also, a date w/o a year is specified as `--MMDD`, see https://tools.ietf.org/html/rfc6350#section-6.2.5

**Comment by georgehrke** [comment]
@tessus someone born in 1970 will simply by shown as „Name (*1970)“

Parsing of --MMDD should be taken care of by `DateTimeParser::parseVCardDateTime`, not by the code in question. 

Please note that all the dates you can see in the code are iCalendar dates, not vCard dates.

**Comment by tessus** [comment]
Ah, I see. Thanks a lot for the explanation.

**Comment by tobiasKaminsky** [comment]
@georgehrke can I test this? Then I'll give it a try with the Samsung S9 tomorrow.

**Comment by georgehrke** [comment]
@tobiasKaminsky Yes please :) 
But I have yet to add a migration step that cleans up old events.

**Comment by tobiasKaminsky** [comment]
I tested adding a new contact on Samsung S9+, once with stable14 and once with this PR: set birthday to 14.10. without a year.

Both time, I see "1604-10-14" as date in contacts app: :+1: 
In calendar I do see both contacts as "Name *", occurring every year: :+1: 

But on calendar of Samsung S9, I do not see any birthday entry.
Also on businness calendar 2 I do not see it.

This is what I get when exporting the contacts in question via contacts app on NC14.
```
BEGIN:VCARD
VERSION:4.0
PRODID:+//IDN bitfire.at//DAVdroid/1.10.1.1-ose ez-vcard/0.10.3
UID:c50ad44e-b48e-460f-abdc-9143df54a505
FN:Test Geburtstag 
N:Geburtstag;Test;;;
BDAY:--1014
REV:20181017T202813Z
END:VCARD

BEGIN:VCARD
VERSION:4.0
PRODID:+//IDN bitfire.at//DAVdroid/1.10.1.1-ose ez-vcard/0.10.3
UID:09bcda7d-e60d-47a4-b877-60c76d972744
FN:Test 2
N:2;Test;;;
BDAY:--1015
REV:20181017T203412Z
END:VCARD
```

**Comment by MorrisJobke** [comment]
@georgehrke What about this? Is this ready by tomorrow evening?

**Comment by tobiasKaminsky** [comment]
Unfortunately I cannot bring the device to hackweek :/
Maybe I can get the contacts apk from device.

**Comment by tobiasKaminsky** [comment]
:+1: works for Samsung :-)

**Comment by georgehrke** [comment]
* -> 🎂
† -> ⚰️
⚭ -> 💍

**Comment by georgehrke** [comment]
@nickvergessen Do we create mysql database with 4 byte support by default now?

**Comment by MorrisJobke** [comment]
> @nickvergessen Do we create mysql database with 4 byte support by default now?

Yes.

**Comment by MorrisJobke** [comment]
@georgehrke Ready to review, right?

**Comment by georgehrke** [comment]
Needs a repair job, no showstopper, so it goes into 15.0.1 anyway

**Comment by MorrisJobke** [comment]
needs to move to 15.0.2

**Comment by georgehrke** [comment]
added the migration step. Please test

**Comment by tobiasKaminsky** [comment]
Hm. For some reason this is not working anymore:
- created a contact with Samsung S9+
- added birthday to it without year, e.g. 10.02. 
- synced to server
- see it on web ui in contacts and in calendar
- do not see it on calendar on Samsung S9+ (its own calendar app) :-/
- see it on Business Calendar 2 

I am now unsure if this was working with the first version of this PR.

This is what I see as calendar entry:
```
Displaying `/nc/remote.php/dav/calendars/livi/contact_birthdays/contacts-399ad5f2-ea67-44b7-b9d0-618a88c4594d.vcf.ics':
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20190218T080919Z
DTSTART;VALUE=DATE:19000211
DTEND;VALUE=DATE:19000212
UID:399ad5f2-ea67-44b7-b9d0-618a88c4594d
RRULE:FREQ=YEARLY
SUMMARY:Test 2 *
TRANSP:TRANSPARENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT0M
ACTION:DISPLAY
DESCRIPTION:Test 2 *
END:VALARM
END:VEVENT
END:VCALENDAR
```

Shouldn't there be something like 1970? Apple omit year?

**Comment by tobiasKaminsky** [comment]
So this is what I get when I create a contact "Georg" with birthday set to 18. February:

```
dav:/nc/remote.php/dav/addressbooks/users/livi/contacts/> cat 890673d4-4601-47c0-9b21-829d69981986.vcf 
Displaying `/nc/remote.php/dav/addressbooks/users/livi/contacts/890673d4-4601-47c0-9b21-829d69981986.vcf':
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:890673d4-4601-47c0-9b21-829d69981986
FN:Georg
N:;Georg;;;
BDAY;X-APPLE-OMIT-YEAR=1604:1604-02-18
REV:20190219T222329Z
END:VCARD
```

This is the calendar entry:
```
Displaying `/nc/remote.php/dav/calendars/livi/contact_birthdays/contacts-890673d4-4601-47c0-9b21-829d69981986.vcf.ics':
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20190219T222329Z
DTSTART;VALUE=DATE:19000218
DTEND;VALUE=DATE:19000219
UID:890673d4-4601-47c0-9b21-829d69981986
RRULE:FREQ=YEARLY
SUMMARY:Georg *
TRANSP:TRANSPARENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT0M
ACTION:DISPLAY
DESCRIPTION:Georg *
END:VALARM
END:VEVENT
END:VCALENDAR
```

And this is not shown in Business Calendar 2 nor in Samsung's Calendar.
However it is shown in both apps when they parse addressbook and create their own birthday calendar (but this is independent from this issue).

For reference this is a contact T1 with birthday set to 18.02.2018:
```
Displaying `/nc/remote.php/dav/addressbooks/users/livi/contacts/39c4cfba-41ca-4096-b6f5-b6801eb46dbc.vcf':
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:39c4cfba-41ca-4096-b6f5-b6801eb46dbc
FN:T1
N:;T1;;;
BDAY:20180218
REV:20190219T224557Z
END:VCARD
```

And this is the corresponding calendar entry:
```Displaying `/nc/remote.php/dav/calendars/livi/contact_birthdays/contacts-39c4cfba-41ca-4096-b6f5-b6801eb46dbc.vcf.ics':
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20190219T224558Z
DTSTART;VALUE=DATE:20180218
DTEND;VALUE=DATE:20180219
UID:39c4cfba-41ca-4096-b6f5-b6801eb46dbc
RRULE:FREQ=YEARLY
SUMMARY:T1 (*2018)
TRANSP:TRANSPARENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT0M
ACTION:DISPLAY
DESCRIPTION:T1 (*2018)
END:VALARM
END:VEVENT
END:VCALENDAR
```

This is shown in "contacts birthday" calendar synced via DavX5, both in Samsung's calendar app and Business Calendar 2.

**Comment by tobiasKaminsky** [comment]
The big question is now why does DavX5 (or whatever) not sync/parse the birthday event in such a way that it is shown in Business Calendar 2 / Samsung's Calendar.

On DavX5 I set to sync all calendar events and not only latest 90 days, but still no success.

**Comment by tobiasKaminsky** [comment]
Yehaaa.
I tested it with a fresh installation and clean DB, now it works.
Dunno know what was wrong last night…

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Can we backport this also to 15? :heart:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Let's then not do the backport.

**Pull request merged**
