### PR TITLE
Add extensionpoint to sharedialogview

### PR DESCRIPTION
**Pull request by MorrisJobke**
* downstream of https://github.com/owncloud/core/pull/27253

cc @nextcloud/javascript

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1: from my side

**Review by ChristophWurst — APPROVED** [review]
Fine by me, although it's not used anywhere yet https://github.com/nextcloud/server/search?utf8=%E2%9C%93&q=%22OCA.Share.ShareDialogView%22&type=Code

**Comment by MorrisJobke** [comment]
> Fine by me, although it's not used anywhere yet https://github.com/nextcloud/server/search?utf8=%E2%9C%93&q=%22OCA.Share.ShareDialogView%22&type=Code

It's just there to allow future apps to hook in ;) Would be weird if there is already code that works with not yet existing code ;)

**Comment by ChristophWurst** [comment]
> It's just there to allow future apps to hook in ;) Would be weird if there is already code that works with not yet existing code ;)

Well, it could have been the case that we already register similar plugins and this one was missing. I was just trying to understand the impact of this change :)

**Pull request merged**
