### PR TITLE
Move to @nextcloud/webpack-vue-config

### PR DESCRIPTION
**Pull request by skjnldsv**
- [x] Implement stylelint
- [x] Release and use @nextcloud/webpack-vue-config stable
- [x] Release and use @nextcloud/eslint-config stable
- [x] It seems that webpack 5 have conflicts with vue-loader.
  Waiting for better explanations https://github.com/vuejs/vue-loader/issues/1643
- [ ] ~~Requires mochapack compatibility to v5 
  https://github.com/sysgears/mochapack/pull/83~~

### CODE REVIEW

**Comment by skjnldsv** [comment]
Aaaaw dang it!
We need mochapack compatibility with webpack 5 https://github.com/sysgears/mochapack/pull/83...
@ChristophWurst we only run one test there :see_no_evil: 

I'm having trouble understanding what is this about: https://github.com/nextcloud/server/blob/d7845570c05f5c2640ce1ff8e27d0b881d950c86/core/webpack.test.js#L27
We take the first module to test? The first module is accessibility, but we test core?
I'm confused :thinking:

**Comment by skjnldsv** [comment]
@MorrisJobke @rullzer `ERROR: Please remove or add those files again or inform the release team about those now files to be included or excluded from the release tar ball`: `stylelint.config.js`, whatshallIdo™ ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke @rullzer, what shall I do ?
> `ERROR: Please remove or add those files again or inform the release team about those now files to be included or excluded from the release tar ball`: **stylelint.config.js**

They need to be in the root? If so I will add this to the files to be removed on release packaging and you can add this to `build/files-checker.php` Then the warning will go away.

**Comment by MorrisJobke** [comment]
> If so I will add this to the files to be removed on release packaging

Done.

**Comment by rullzer** [comment]
What is the state here?

**Comment by skjnldsv** [comment]
We need mochapack compatibility with webpack 5 sysgears/mochapack#83...

**Comment by skjnldsv** [comment]
Rebased

**Comment by skjnldsv** [comment]
I think I found a way :O

**Comment by rullzer** [comment]
image

**Comment by skjnldsv** [comment]
> I think I found a way :O

Now everything else is failing! :angry:

**Comment by skjnldsv** [comment]
Checker need a bump

```

ERROR: There were 3 additional files:
--
123 | .mocharc.yml
124 | stylelint.config.js
125 | webpack.js
126 | ERROR: There were 3 missing files:
127 | webpack.common.js
128 | webpack.dev.js
129 | webpack.prod.js
130 | ERROR: Please remove or add those files again or inform the release team about those now files to be included or excluded from the release tar ball.

```

**Comment by skjnldsv** [comment]
Let's do it step by step
https://github.com/nextcloud/server/pull/28115

Changing the babel config seems to cause issues with the OC/globals exports

**Pull request closed without merging**
