### PR TITLE
Changed mapping to font

### LINKED ISSUE #24603: Icons for font files are incorrect in Files app
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload a file that is .ttf or .woff
2. See the the icon displayed in files app (same as pictures)

### Expected behaviour
Have an icon that represent font formats

### Actual behaviour
Icon displayed is a "picture" icon

### Server configuration

**Nextcloud version:** 20.0.2

### Screenshot

image

### PR DESCRIPTION
**Pull request by dos-2**
* Resolves https://github.com/nextcloud/server/issues/24603

old
Previous code had "application/font-woff": "image"
which caused the error.
new
New code has fixed the mapping.

### CODE REVIEW

**Review by juliusknorr — CHANGES_REQUESTED** [review]
Thanks for your pull request.

This should also get adjusted in core/js/mimetypelist.js

In addition it might make sense for other font related mime types as well

**Comment by juliushaertl** [comment]
@jancborchardt Maybe you can come up with a nice icon for font files?

**Comment by jancborchardt** [comment]
Yes, `format-font` would be a good icon. (Not in Material Design core apparently, but from https://mdisearch.com/ )

**Comment by susnux** [comment]
I rebased the PR and pushed a commit providing the icon @jancborchardt suggested, it looks like this now:

image

**Review by susnux — APPROVED** [review]

**Review by nfebe — APPROVED** [review]

**Comment by kesselb** [comment]
The failing CheckerTest looks related

Screenshot from 2023-08-03 21-55-13

**Comment by kesselb** [comment]
Fix: https://github.com/nextcloud/server/pull/39705

**Pull request merged**
