### PR TITLE
Fix the user remove from group in UI

### LINKED ISSUE #23237: Can't remove group from a user
Can't Remove group assigned to a user with nextcloud 20.0.0

### Steps to reproduce
1. Create group in the admin user page
2. assign this group then try to remove it

### Expected behaviour
group must be cleared

### Actual behaviour
group stay attached to the user

### Server configuration

**Operating system:**
Debian 10.6
Docker version 19.03.12

**Web server:** (Official docker container)
Server version: Apache/2.4.38 (Debian)
Server built:   2020-08-25T20:08:29

**Database:** (Official docker container)
Mariadb 10.5.5 

**PHP version:**
PHP 7.4.11 (cli) (built: Oct  1 2020 19:35:35) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 19.0.3 nextcloud version

**Where did you install Nextcloud from:**
Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - deck: 1.1.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.5.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.0.2
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - riotchat: 0.6.11
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.3
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - announcementcenter
  - drawio
  - encryption
  - external
  - fulltextsearch
  - rainloop
  - richdocuments
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.domain.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.0.9",
        "overwrite.cli.url": "https:\/\/nextcloud.domain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "onlyoffice": {
            "verify_peer_off": true
        },
        "maintenance": false,
        "loglevel": 0,
        "overwriteprotocol": "https",
        "theme": "",
        "app_install_overwrite": [
            "spreed",
            "onlyoffice",
            "calendar",
            "drawio"
        ]
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.13.1",
            "types": "filesystem"
        },
        "announcementcenter": {
            "enabled": "no",
            "installed_version": "4.0.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "21"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "dav"
        },
        "core": {
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1599158953.3778",
            "lastcron": "1602013184",
            "lastupdateResult": "[]",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_only_share_with_group_members": "yes",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.0.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.16.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "dav"
        },
        "drawio": {
            "DrawioAutosave": "yes",
            "DrawioLang": "auto",
            "DrawioOffline": "no",
            "DrawioTheme": "kennedy",
            "DrawioUrl": "https:\/\/drawio.domain.com",
            "DrawioXml": "yes",
            "enabled": "no",
            "installed_version": "0.9.7",
            "types": "filesystem"
        },
        "external": {
            "enabled": "no",
            "installed_version": "3.7.0",
            "max_site": "2",
            "sites": "***REMOVED SENSITIVE VALUE***",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem",
            "watermark_allGroups": "no",
            "watermark_allGroupsList": "",
            "watermark_allTags": "no",
            "watermark_allTagsList": "",
            "watermark_enabled": "no",
            "watermark_linkAll": "no",
            "watermark_linkRead": "no",
            "watermark_linkSecure": "no",
            "watermark_linkTags": "no",
            "watermark_linkTagsList": "",
            "watermark_shareAll": "no",
            "watermark_shareRead": "no",
            "watermark_text": ""
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.11.1",
            "types": "filesystem"
        },
        "files_markdown": {
            "enabled": "yes",
            "installed_version": "2.3.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.17.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": "logging"
        },
        "fulltextsearch": {
            "enabled": "no",
            "installed_version": "1.4.2",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "levels": "01111",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "4.0.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "https:\/\/onlyoffice.domain.com\/",
            "DocumentServerUrl": "https:\/\/onlyoffice.domain.com\/",
            "StorageUrl": "https:\/\/nextcloud.domain.com\/",
            "customizationChat": "true",
            "customizationCompactHeader": "true",
            "customizationFeedback": "true",
            "customizationForcesave": "false",
            "customizationHelp": "true",
            "customizationReviewDisplay": "original",
            "customizationToolbarNoTabs": "true",
            "defFormats": "{\"csv\":\"true\",\"doc\":\"true\",\"docm\":\"false\",\"docx\":\"true\",\"dotx\":\"false\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"true\",\"ods\":\"true\",\"odt\":\"true\",\"otp\":\"false\",\"ots\":\"false\",\"ott\":\"false\",\"pdf\":\"false\",\"potm\":\"false\",\"potx\":\"true\",\"ppsm\":\"false\",\"ppsx\":\"false\",\"ppt\":\"true\",\"pptm\":\"false\",\"pptx\":\"true\",\"rtf\":\"false\",\"txt\":\"false\",\"xls\":\"false\",\"xlsm\":\"false\",\"xlsx\":\"true\",\"xltm\":\"false\",\"xltx\":\"false\"}",
            "demo": "{\"available\":false,\"enabled\":false,\"start\":{\"date\":\"2020-09-03 19:18:14.655868\",\"timezone_type\":3,\"timezone\":\"UTC\"}}",
            "editFormats": "{\"csv\":\"true\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"rtf\":\"false\",\"txt\":\"true\"}",
            "enabled": "yes",
            "groups": "[]",
            "installed_version": "6.0.2",
            "jwt_secret": "",
            "sameTab": "false",
            "settings_error": "",
            "types": "filesystem",
            "verify_peer_off": "false"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "prevent_group_restriction"
        },
        "rainloop": {
            "enabled": "no",
            "installed_version": "7.0.3",
            "types": ""
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": ""
        },
        "richdocuments": {
            "disable_certificate_verification": "",
            "enabled": "no",
            "installed_version": "3.7.4",
            "public_wopi_url": "https:\/\/collabora.domain.com",
            "types": "filesystem,dav,prevent_group_restriction",
            "wopi_url": "https:\/\/collabora.domain.com:443"
        },
        "riotchat": {
            "enabled": "yes",
            "installed_version": "0.6.11",
            "server_name": "NAS nextcloud",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "has_reference_id": "yes",
            "installed_version": "10.0.0",
            "project_access_invalidated": "1",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.13.3",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.1.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "files_markdown": "2.3.1",
            "installed_version": "1.10.0",
            "onlyoffice": "6.0.0",
            "riotchat": "0.6.11",
            "spreed": "9.0.4",
            "types": "",
            "update_check_errors": "0"
        },
        "user_external": {
            "enabled": "no",
            "installed_version": "0.10.0",
            "types": "prelogin,authentication"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": "filesystem"
        }
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes - local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Brave

**Operating system:**
Debian

### Logs

</details>

#### Nextcloud log (from interface)
<details>
<summary>Nextcloud log</summary>

```
[no app in context] Error: Exception: Argument 2 passed to OCA\Provisioning_API\Controller\UsersController::removeFromGroup() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 169 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Provisioning ... {}, "removeFromGroup")
1. /var/www/html/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Provisioni ... r", "removeFromGroup", OC\AppFramework\ ... {}, {action: null,us ... "})
2. /var/www/html/ocs/v1.php line 88
   OC\Route\Router->match("/ocsapp/cloud/users/test/groups")
3. /var/www/html/ocs/v2.php line 24
   require_once("/var/www/html/ocs/v1.php")

DELETE /ocs/v2.php/cloud/users/test/groups
```
```
{"reqId":"2lI24o4vqoNnMmAOXpUZ","level":3,"time":"2020-10-06T19:57:09+00:00","remoteAddr":"192.168.1.50","user":"admin","app":"no app in context","method":"DELETE","url":"/ocs/v2.php/cloud/users/test/groups","message":{"Exception":"Exception","Message":"Argument 2 passed to OCA\\Provisioning_API\\Controller\\UsersController::removeFromGroup() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 169","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"removeFromGroup"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","removeFromGroup",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"userId":"test","_route":"ocs.provisioning_api.Users.removeFromGroup"}]},{"file":"/var/www/html/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users/test/groups"]},{"file":"/var/www/html/ocs/v2.php","line":24,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Provisioning_API\\Controller\\UsersController::removeFromGroup() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 169","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"removeFromGroup","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["test",null]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"removeFromGroup"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"removeFromGroup"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","removeFromGroup",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"userId":"test","_route":"ocs.provisioning_api.Users.removeFromGroup"}]},{"file":"/var/www/html/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users/test/groups"]},{"file":"/var/www/html/ocs/v2.php","line":24,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/apps/provisioning_api/lib/Controller/UsersController.php","Line":802},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9","id":"5f7cd0be5a8dc"}
```
</details>

### PR DESCRIPTION
**Pull request by sharidas**
Fix the removal of user from the group in UI.

Signed-off-by: Sujith Haridasan <sujith.h@gmail.com>

### CODE REVIEW

**Comment by sharidas** [comment]
### Summary

Removal of user from the group in the UI was not working. This change set helps fix the issue.

### Description

The removal of user from the group in the user management page was not happening because axios.delete expects `param` to be the object key in the config to get the data we are passing, i.e, the group id or gid.

### Steps done to test

1. Create a group `Group1`
2. Add user `user1` to `Group1` in the web UI.
3. Remove `user1` from `Group1` from UI. No errors are logged in the console or logfile.
4. Verify the same with the occ, if the user is removed or not.

**Review by GretaD — APPROVED** [review]
tested and works

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Ah, shit, we moved the settings app, I forgot

**Comment by skjnldsv** [comment]
stable19 https://github.com/nextcloud/server/pull/23282

**Pull request merged**
