### PR TITLE
[stable10] fix missing semicolon to fix themed logo on log in page

### PR DESCRIPTION
**Pull request by jancborchardt**
Backport of https://github.com/nextcloud/server/pull/682, please review @nextcloud/theming

### CODE REVIEW

**Comment by juliushaertl** [comment]
@jancborchardt unit tests failed here as well ;)

**Comment by jancborchardt** [comment]
@juliushaertl @nickvergessen aaand fixed here as well ;)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by juliushaertl** [comment]
:+1:

**Pull request merged**
