### PR TITLE
Check if screenshot is available before showing it

### PR DESCRIPTION
**Pull request by juliusknorr**
Try to preload the screenshot in the apps management and show an icon otherwise

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:rocket:

**Review by gary-kim — APPROVED** [review]
LGTM

**Comment by rullzer** [comment]
conflicts and weird CI state...

**Comment by juliushaertl** [comment]
Let's see

**Pull request merged**
