### PR TITLE
Fix creation of new user and display the correct error message

### LINKED ISSUE #33572: [Bug]: Creating new (database) user show misleading error message and loses data
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Screencast from 17.08.2022 11:37:45.webm](https://user-images.githubusercontent.com/3902676/185087099-bdc6e7e2-7501-43af-abd3-da2c0dd03f83.webm)

### Steps to reproduce

Tested on

[38037c8de461e6605b96383f841f91593226a54f](https://github.com/nextcloud/server/pull/33001/commits/38037c8de461e6605b96383f841f91593226a54f)

 [312b719acf686f51065e83290cd88704d703a50c](https://github.com/nextcloud/server/commit/312b719acf686f51065e83290cd88704d703a50c)
 (hard to reproduce as something with the password confirmation dialog is broken)

1. Go to users manager
2. Click New User
3. Fill out the form (use a available user name)
4. Click Add a new user
5. See a warning "User already exist"
6. Reload the page
7. User is there but email is missing

### Expected behavior

- No "User already exist" warning
- Attributes like email is saved

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Doom 2
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

Looks like a regression of https://github.com/nextcloud/server/pull/33052

setDisplayName returns false for various cases. For example:
- the display name is already up to date
- backend does not support editing a display name

Example request:

```fetch("http://__SERVERURL__/ocs/v2.php/cloud/users", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json",
    "requesttoken": "__REQUESTTOKEN__"
  },
  "referrerPolicy": "no-referrer",
  "body": "{\"userid\":\"user3\",\"password\":\"rohkohYe7osh\",\"displayName\":\"user3\",\"email\":\"test+user3@kesselb.dev\",\"groups\":[],\"subadmin\":[],\"quota\":\"default\",\"language\":\"en\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

### PR DESCRIPTION
**Pull request by Pytal**
Fix https://github.com/nextcloud/server/issues/33572

- [x] Fix creation of new user (either with the same or different values entered for Username and Display name)
- [x] Rollback user creation on invalid displayname
- [x] Display the correct error message

### Out-of-scope
Rollback user creation on other exceptions

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by kesselb — COMMENTED** [review]
LGTM :+1: 

The problem itself is present on 24 and 23 too. I guess it's kinda hard to backport the api changes. However the issue only occurs when userId = displayName so the impact is hopefully not to big.

**Review by come-nc — APPROVED** [review]

**Comment by ArtificialOwl** [comment]
Can't we just catch and ignore OcsException() on editUser() ? 

Before this patch, the error message when creating a user with displayName == userId `[1]` were wrong, but at least the user were created. With this patch, user creation is reversed because some data were ignored during user creation:

[1] https://github.com/nextcloud/server/blob/c37bad1ce424fd1b478788e5bc22e0d7a48bfe30/lib/private/User/User.php#L161

**Comment by ArtificialOwl** [comment]
should we backport this one to stable24 ?

**Comment by Pytal** [comment]
We don't backport public API changes though?

**Pull request merged**
