### PR TITLE
Set Edge < 16 as incompatible with css vars

### PR DESCRIPTION
**Pull request by skjnldsv**
See https://caniuse.com/#feat=css-variables

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Review by rullzer — APPROVED** [review]
sure... :elephant:

**Comment by skjnldsv** [comment]
Stable15 https://github.com/nextcloud/server/pull/15421

**Comment by skjnldsv** [comment]
Follow up (forgot something) https://github.com/nextcloud/server/pull/15422

**Comment by skjnldsv** [comment]
Stable14 https://github.com/nextcloud/server/commit/021fcc50117cd80064dcc6eebb366375cffc4fb3

... creating branch failed without me noticing, I thought I was on the new one, but still on stable14...

**Pull request merged**
