### PR TITLE
Merge all babelrc into one file

### PR DESCRIPTION
**Pull request by skjnldsv**
Thanks to our dear @danxuliu, I now realise we only need one! :see_no_evil:

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
one .babelrc to rule them all!

**Review by rullzer — APPROVED** [review]
And then I said....

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
:+1:

**Review by ChristophWurst — APPROVED** [review]
:+1:

**Review by danxuliu — APPROVED** [review]
Cool, I intended to do this after dinner, and now I come back and it is magically done xD

> one .babelrc to rule them all!

Ash .babelrc durbatulûk!

**Pull request merged**
