### PR TITLE
enh: Send empty expireDate when not expireDate set

### LINKED ISSUE #44219: [Bug]: When creating email share expiry date is set by default without enforcement
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating an email share with the option "Set expiration date" unchecked and "Enforce expiry date" unchecked, the default expiry date is set anyway.
You can see it by clicking "customize link".

This is how it looks like when creating the email share:
grafik

This is how it looks like when customizing the share afterwards:
grafik

After unchecking "Set expiration date" and updating share again, the values stays ok.

### Steps to reproduce

1. Configure the Sharing options like this.
    - [x] Allow users to share via link end emails
    - [x] Always ask for a password
    - [x] Enforce password protection
    - [x] Set default expiry date -> Expire after 30 day(s)
    - [ ] Enforce expiry date
2. Create an email share and uncheck the option "Set expiration date"
3. Click on "customize link" and see that it's wrong.
4. Uncheck "Set expiration date" again and update the link.
5. Click on "customize link" again and see that now it worked how it should work in first place.

### Expected behavior

If the option "Set expiration date" is unchecked when creating the share, it should be stored correctly in the database like this and not only at the second updating

### Nextcloud Server version

27.1.7 28.0.3

### PR DESCRIPTION
**Pull request by nfebe**
When creating a new share, if the user unchecks "Set expiry date" no `expireDate` is sent to the server.

However, the server then assumes the default configured, hence better to send an empty value.

Resolves : https://github.com/nextcloud/server/issues/44219

### CODE REVIEW

**Review by Pytal — APPROVED** [review]
Makes sense

**Review by nfebe — COMMENTED** [review]
Looks like the backend still ignores the empty value and uses the default. So, converted to draft.

Context : https://github.com/nextcloud/server/issues/44219#issuecomment-2004131439

cc: @Altahrim

**Review by emoral435 — APPROVED** [review]
LGTM :)!

**Review by Altahrim — APPROVED** [review]

**Comment by ElSi-DVT** [comment]
This bug still exists in NC 27.1.9

**Comment by Fenn-CS** [comment]
Should be fixed with backport of https://github.com/nextcloud/server/pull/44912

**Pull request merged**
