### PR TITLE
Document frontend sass compilation

### PR DESCRIPTION
**Pull request by ChristophWurst**
Resolves: n/a

## Summary

https://github.com/nextcloud/server/pull/32261 changes the compilation of styles but misses documentation for developers.

## TODO

- [x] Document the changes

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM but should we also document `npm run sass:icons` somewhere?

**Comment by ChristophWurst** [comment]
> LGTM but should we also document `npm run sass:icons` somewhere?

I lack the knowledge to document what it does but makes sense to cover that as well if it's important for contributors.

**Comment by szaimen** [comment]
> I lack the knowledge to document what it does but makes sense to cover that as well if it's important for contributors.

I think it is important if you change some icons but probably makes sense to ask e.g. @skjnldsv for what it does in detail...

**Comment by skjnldsv** [comment]
> > I lack the knowledge to document what it does but makes sense to cover that as well if it's important for contributors.
> 
> I think it is important if you change some icons but probably makes sense to ask e.g. @skjnldsv for what it does in detail...

It generate the legacy icons.css from https://github.com/nextcloud/server/blob/b9bbb25771fc704d0f5a9de7bc2ae0cae73cf81b/core/src/icons.js

**Review by skjnldsv — APPROVED** [review]

**Comment by PVince81** [comment]
also when buildling for production, one also needs to run `npm run sass && npm run sass:icons`, otherwise the diff bot will complain

or is that not necessary any more ?

**Comment by skjnldsv** [comment]
> or is that not necessary any more ?

still is

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/35622

**Review by JuliaKirschenheuter — APPROVED** [review]

**Pull request merged**
