### PR TITLE
Fixed some LGTM alerts

### PR DESCRIPTION
**Pull request by imsolost**
Hi! I found some [alerts on LGTM.com](https://lgtm.com/projects/g/nextcloud/server/alerts/?mode=tree) for your project. This may not be the type of contribution you normally receive, but I figured I could help clean up the codebase. 

(Full disclosure: I'm part of the team behind LGTM.com)

Let me know if you have any questions.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Looks good :+1:

**Review by skjnldsv — APPROVED** [review]
Nice!! :)

**Comment by MorrisJobke** [comment]
@skjnldsv The JSUnit tests look really broken: https://drone.nextcloud.com/nextcloud/server/14969/265 was this fixed on master?

**Comment by ChristophWurst** [comment]
> was this fixed on master?

I guess this is also related to #13743

**Comment by rullzer** [comment]
A lot of the acceptance tests do not look happy

**Comment by skjnldsv** [comment]
@MorrisJobke no idea! :woman_shrugging:

**Comment by MorrisJobke** [comment]
@imsolost Could you rebased this Pr on the current master by any chance to see if the tests pass?

**Comment by MorrisJobke** [comment]
> @imsolost Could you rebased this Pr on the current master by any chance to see if the tests pass?

I did this - let's see if this solves the issues in here.

**Comment by MorrisJobke** [comment]
This seem to really break a lot of things 😢

**Comment by imsolost** [comment]
I fixed some of the issues that were preventing a successful CI, but I am unsure as to what the current issue is that is preventing the build. I will continue looking into it. Perhaps one of you might have some better insight into this issue.

**Comment by MorrisJobke** [comment]
> I fixed some of the issues that were preventing a successful CI, but I am unsure as to what the current issue is that is preventing the build. I will continue looking into it. Perhaps one of you might have some better insight into this issue.

Looks good now. The files-tag acceptance tests sometimes fails and is quite unreliable :( From the code changes I can't see any interfering cause so this is good to go in.

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Pull request merged**
