### PR TITLE
[master] Update psalm-baseline.xml

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated update psalm-baseline.xml with fixed psalm warnings

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
Rebased, updated baseline and attempted to fix baseline updating workflow.

The baseline I pushed is full of `CDATA` because of https://github.com/vimeo/psalm/issues/10632
It should not be a problem, let’s see what CI thinks of it.

**Comment by nickvergessen** [comment]
While on it, can we enforce the correct PHP version as baseline: https://github.com/nextcloud/spreed/blob/main/psalm.xml#L8
Otherwise you can use PHP 8.2 functions and psalm will not complain :P

**Review by nickvergessen — APPROVED** [review]

**Comment by come-nc** [comment]
> While on it, can we enforce the correct PHP version as baseline: [nextcloud/spreed@`main`/psalm.xml#L8](https://github.com/nextcloud/spreed/blob/main/psalm.xml?rgh-link-date=2024-02-01T17%3A40%3A31Z#L8) Otherwise you can use PHP 8.2 functions and psalm will not complain :P

The psalm jobs already run on 8.0, and our composer.json lists 8.0 as php platform, should be enough, no?

**Review by nickvergessen — APPROVED** [review]

**Comment by come-nc** [comment]
/backport 40ab40de30ee90ded277065da206aa3830a2f796to stable28

**Pull request merged**
