### PR TITLE
Copy to clipboard with button instead of link

### PR DESCRIPTION
**Pull request by Pytal**
Before | After
--- | ---
image | image

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by GretaD — APPROVED** [review]

**Comment by Pytal** [comment]
Fixed tests

**Comment by skjnldsv** [comment]
Noooooooo
There was a good reason :)
If the copy fails for browser security reason, you cannot get the link.
The fact that it was a link also allowed you to right click and copy or open in a new tab.
It also make readers and accessibility tools understand the data. :)

It should be reverted imho

**Comment by skjnldsv** [comment]
On a subsidiary note, it also prevent us from doing testing and retrieving the link.
Copy link is very unreliable on automated e2e testing 

Viewer is failing because of this PR, that's how I found it

**Comment by Pytal** [comment]
Good points @skjnldsv

Will confirm with the a11y reviewer as this was a specific request made during the audit which we would fail if not done

**Pull request merged**
