### PR TITLE
Fix adding x-requested-with header for relative URLs in some cases

### PR DESCRIPTION
**Pull request by julien-nc**
When NC is at the root path of the web server, `getRootUrl()` returns an empty string and `isNextcloudUrl()` always returned true for relative URLs.

The condition to know if a URL points to NC is now:
* the URL starts with the absolute NC base URL (this implicitly checks if the URL is absolute)
* OR the URL is relative and start with NC's root URL (the sub path)

This broke the OpenStreetMap integration in instances that are accessible at the root of the webserver.

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]
Looks good to me!

**Review by juliusknorr — APPROVED** [review]

**Comment by julien-nc** [comment]
@juliushaertl @emoral435 @susnux Cypress test failure seems unrelated (theming app). Can someone force merge this? :pray:

**Pull request merged**
