### PR TITLE
Move multiple files

### PR DESCRIPTION
**Pull request by tcitworld**
Move multiple selected files (previously at #6014)

Fixes https://github.com/nextcloud/server/issues/2779

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]

**Comment by jasonbayton** [comment]
This is amazing, thank you @tcitworld!

**Comment by Q-Storm** [comment]
Thanks @tcitworld. I have been waiting for that feature.

**Comment by tcitworld** [comment]
TODO: when movement is cancelled inside the picker popup, the rolling animation on the move button doesn't stop.

**Comment by Larsene** [comment]
Thanks @tcitworld ! I can't understand how users deals without this feature !

**Comment by jasonbayton** [comment]
> I can't understand how users deals without this feature!

With great difficulty.

**Pull request merged**
