### PR TITLE
refactor(files): Drop unneeded initial state

### PR DESCRIPTION
**Pull request by susnux**
* :warning:  Chained on (based on) #47015 

## Summary

The initial state is no longer used, it was only used in legacy UI and in the f2v rewrite it was only used for the `id` which can be loaded just from the URL.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Comment by nickvergessen** [comment]
The rebase broke

**Comment by susnux** [comment]
> The rebase broke

That was the UI toggle :eyes:

**Comment by susnux** [comment]
Fixed.

**Review by st3iny — APPROVED** [review]
Looks good.

To make eslint happy:
```patch
diff --git a/apps/files/src/components/FilesListVirtual.vue b/apps/files/src/components/FilesListVirtual.vue
index f0ac8ba3d70..cb38d744738 100644
--- a/apps/files/src/components/FilesListVirtual.vue
+++ b/apps/files/src/components/FilesListVirtual.vue
@@ -64,7 +64,6 @@ import type { UserConfig } from '../types'

 import { getFileListHeaders, Folder, View, getFileActions, FileType } from '@nextcloud/files'
 import { showError } from '@nextcloud/dialogs'
-import { loadState } from '@nextcloud/initial-state'
 import { translate as t } from '@nextcloud/l10n'
 import { defineComponent } from 'vue'

@@ -198,7 +197,7 @@ export default defineComponent({
                },

                openFile: {
-                       handler(open: boolean) {
+                       handler() {
                                // wait for scrolling and updating the actions to settle
                                this.$nextTick(() => {
                                        if (this.fileId && this.openFile) {
```

**Pull request merged**
