### PR TITLE
Show current weather and forecast in the weather widget

### PR DESCRIPTION
**Pull request by julien-nc**
refs #23399 #30436 

Instead of showing a 6 hours forecast, the current weather is now the main information. The first action item is a 6 hours forecast.
wwwww

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looks great, nice compromise. :)

**Review by artonge — APPROVED** [review]

**Review by artonge — APPROVED** [review]
The code could probably be streamlined but ok.

**Comment by eneiluj** [comment]
@artonge You mean with some factorization like in 0f83159b871c09bf7335740699b9317106fd210c?
Plus there was an issue with index check :sweat_smile:

**Comment by Naaktgeboren** [comment]
Nicely done, looking forward to the new version.

**Comment by masterwishx** [comment]
i have no time in widget nectloud v24

**Comment by masterwishx** [comment]
image

**Pull request merged**
