### PR TITLE
Header acceptance features

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Review by danxuliu — CHANGES_REQUESTED** [review]
I will make some minor amending.

Edit: I also found a false positive; fixing that needs a feature introduced in #8594, so I will rebase once that one is merged.

**Review by danxuliu — APPROVED** [review]
Done!

**Review by MorrisJobke — APPROVED** [review]

**Comment by skjnldsv** [comment]
Thanks again @danxuliu 
I really love the acceptance tests now! :)

**Comment by danxuliu** [comment]
@skjnldsv Glad to help :-)

**Pull request merged**
