### PR TITLE
Do not try to contact lookup server if not needed

### PR DESCRIPTION
**Pull request by rullzer**
In some cases (for example you never send data to the lookup server)
there is no need for this job to even try.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@rullzer I guess we backport this?

**Comment by rullzer** [comment]
> @rullzer I guess we backport this?

yes but I guess it will fail

**Pull request merged**
