### PR TITLE
Fix checkboxes on login

### PR DESCRIPTION
**Pull request by skjnldsv**
I removed all lines about radio (since it's not used in the installation page nor login) and removed everything concerning the default checkbox (not white) since it's not used either.

Before / After
capture d ecran_2017-01-25_13-34-25
capture d ecran_2017-01-25_13-34-01

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks good! Only one thing: Is the checkmark black? Previously that part was transparent, and it will look nicer (also with themes) cause the background color shines through.

**Comment by skjnldsv** [comment]
It's black. It was easier to do.
The other possibility is to but a white background on the svg and a transparent checkbox and set an overflow hidden on the checkbox. Like to we will have a transparent checkbox, but we won't be able to use css to change the colour (in case of someone wants to customise its checkbox) 😃

**Comment by skjnldsv** [comment]
Please merge #3341 before continuing this pr! :)

**Comment by jancborchardt** [comment]
@skjnldsv can we merge this first, because it fixes an important bug? The other thing is polishing.

**Comment by skjnldsv** [comment]
I would prefer to merge the transparent checkbox and then I will update this pr accordingly :)

**Comment by jancborchardt** [comment]
@skjnldsv can you update this? :)

Also, on the login page it’s a bit strange: The »Stay logged in« text is white and on hover slightly transparent. The checkbox however is slightly transparent and then on hover white. The other way around. Can you adjust it so it fits the text?

**Comment by skjnldsv** [comment]
@jancborchardt Updated.
I did a quick cleanup of the quotes too.

**Comment by skjnldsv** [comment]
kazam_screencast_00001

**Comment by skjnldsv** [comment]
kazam_screencast_00000

**Comment by skjnldsv** [comment]
@nextcloud/designers Please review! 🚀

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
