### PR TITLE
DAV custom props: catch Exception and rollback transaction in case

### PR DESCRIPTION
**Pull request by blizzz**
- before exceptions were not caught, a started transaction might not have
  been finished
- also resolve depractions and use IQueryBuilder

### CODE REVIEW

**Comment by blizzz** [comment]
> Possible performance regression detected

No queries were actually added.

**Comment by szaimen** [comment]
> Possible performance regression detected

I fear this is a flaky test :/

**Review by CarlSchwan — APPROVED** [review]
So much nicer :heart:

**Comment by CarlSchwan** [comment]
> > Possible performance regression detected
> 
> No queries were actually added.

the reason is that query using raw SQL are not watched by the profiler, that's a reason why it's good to port then to IQueryBuilder

**Review by ChristophWurst — APPROVED** [review]

**Review by tcitworld — APPROVED** [review]

**Pull request merged**
