### PR TITLE
Use a normal string to translate.

### LINKED ISSUE #19952: Untranslated strings
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Expected behaviour
Strings should be translated

### Actual behaviour
Some strings are not translated in Accessibility and Security settings
Screenshot_20200314_113547

Screenshot_20200314_114646

**Operating system:**
Centos 7

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.1

**Nextcloud version:**
17.0.4

### PR DESCRIPTION
**Pull request by kesselb**
Fix #19952 

Somehow the multi line strings are still a problem for t.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
@kesselb mind to backport manually?

**Pull request merged**
