### PR TITLE
[stable22] Add quota restrictions options

### PR DESCRIPTION
**Pull request by julien-nc**
Manual backport of #28009

### CODE REVIEW

**Comment by eneiluj** [comment]
Hmmm I don't get how to fix the build CI here.

**Comment by eneiluj** [comment]
@Pytal Can something similar to #28202 be applied in stable22 too?

**Comment by Pytal** [comment]
> @Pytal Can something similar to #28202 be applied in stable22 too?

Will make some backports :)

**Comment by skjnldsv** [comment]
@dependabot recreate

**Comment by skjnldsv** [comment]
Nope, there are conflicts, needs a manual rebase

**Comment by Pytal** [comment]
Previously chunkhashed files needed to be manually removed as amend does not remove files :)

**Comment by eneiluj** [comment]
The remaining failing CI check seems unrelated. Wow, maybe we can finally merge this :grin:.
@Pytal @skjnldsv

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Pull request merged**
