### PR TITLE
Validate expire share days in settings (issue: #11930)

### PR DESCRIPTION
**Pull request by MasterOfDeath**
https://github.com/nextcloud/server/issues/11930

### CODE REVIEW

**Comment by MasterOfDeath** [comment]
Prevent input not digit

**Comment by skjnldsv** [comment]
Hello @MasterOfDeath 
You need to sign your commits for us to be able to merge your work into nextcloud :)

**Comment by rullzer** [comment]
> Hello @MasterOfDeath
> You need to sign your commits for us to be able to merge your work into nextcloud :)

Yep. Just run:

1. git checkout expire-share-days-validate
2. git commit --amend -s
3. git push -f

**Comment by MasterOfDeath** [comment]
> Hello @MasterOfDeath
> You need to sign your commits for us to be able to merge your work into nextcloud :)

Hmm, but i did 
image

**Comment by rullzer** [comment]
Ah signing is not the right terminology aplogies. Sign-off.
See https://github.com/nextcloud/server/blob/master/contribute/developer-certificate-of-origin

**Comment by MasterOfDeath** [comment]
Signed-off commit

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
