### PR TITLE
Fix overflow in Nextcloud Files meat ball menus (grid)

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet 33763786+Jerome-Herbinet@users.noreply.github.com

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Here is a fix for an overflow in the meat balls menus in the NC Files in grid view.
**No problem here in English but, there is a problem in other languages like German and French which use longer wordings.**
In Nextcloud 24, there was an ellipsis (difficult to read and guess hidden words). In Nextcloud 25 (ugly), there is no more ellipsis, and we have an overflow instead. 
I propose to enlarge the box to guaranty real wordings' visibility in most languages. What do you think ?

Before  : 

After : 

When I talked about visibility in Nextcloud 24, here is an example :

### CODE REVIEW

**Comment by skjnldsv** [comment]
I would prefer to break-word :)

**Comment by Jerome-Herbinet** [comment]
> I would prefer to break-word :)

OK @skjnldsv I think you are right, and I didn't think about this solution. I'll make the necessary changes in a new commit. 
We keep in touch.

**Comment by Jerome-Herbinet** [comment]
@skjnldsv : 

Before : 
Capture d’écran de 2022-10-28 14-09-33

After : 
Capture d’écran de 2022-10-28 14-09-40

**Comment by Jerome-Herbinet** [comment]
@skjnldsv, however, I found a problem with the OpenProject button that should not be implemented like the others (it may not respect a certain integration standard).

**Comment by Jerome-Herbinet** [comment]
@skjnldsv I took advantage of this graphic modification to make the button take up the whole width, which can be seen when you move the cursor over it.

**Comment by Jerome-Herbinet** [comment]
@szaimen I invite you to check the last changes (following @skjnldsv suggestion) which replace what I did first. 
If everything is OK and approved, I suggest to backport this to Nextcloud 25 (this would be nice). Thanks.

**Comment by Jerome-Herbinet** [comment]
Please help me, I have troubles with some commits that don't belong to me. Thanks by advance.

**Comment by szaimen** [comment]
> Please help me, I have troubles with some commits that don't belong to me. Thanks by advance.

hm... maybe it is easier to create a new branch and PR with your changes?

**Comment by Jerome-Herbinet** [comment]
@szaimen 
I close this PR and have created a new one : #34891

**Pull request closed without merging**
