### PR TITLE
Add accessibility entry in user menu

### PR DESCRIPTION
**Pull request by PVince81**
For https://github.com/nextcloud/server/issues/33736

image

Note: if the theming app is disabled the entry will remove itself.

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by szaimen** [comment]
> image

cc @CarlSchwan what happened to the right margin/padding?

**Review by szaimen — CHANGES_REQUESTED** [review]
I think when in that section also the entry in the nav manager should be highlighted, no?
See 
image

**Comment by szaimen** [comment]
> > image
> 
> cc @CarlSchwan what happened to the right margin/padding?

Seems like removing overflow-y: scroll fixes it.

image

**Review by nimishavijay — COMMENTED** [review]
Looks good, a suggestion: we use the A11y icon instead of the theming icon https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aaccessibility_new%3A

**Comment by PVince81** [comment]
@szaimen I thought of this but don't think it's critical. It would also mean that whenever you manually click on that navigation, the entry on the top right would also need to be highlighted. Might need a hacky solution for this.

**Comment by szaimen** [comment]
> @szaimen I thought of this but don't think it's critical. It would also mean that whenever you manually click on that navigation, the entry on the top right would also need to be highlighted. Might need a hacky solution for this.

look at https://github.com/nextcloud/server/pull/33756/files#diff-0fc396967e1f9523319e6bbfd0d6877a8a6e5db7a7896697404c19ea896f734dR137-R140. Maybe it helps figuring out a solution

**Comment by PVince81** [comment]
here we go:
image

@nimishavijay 

@szaimen as per screenshot, the active item is now fixed, thanks a lot for the useful pointer

please re-review!

**Review by nimishavijay — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
lgtm now but acceptance-header failure is related!

**Comment by PVince81** [comment]
solved

**Comment by szaimen** [comment]
S3 failure unrelated

**Comment by jancborchardt** [comment]
@nursoda yes, understandable – however all of the requirements for having each of the entries quickly accessible are valid. Initially we only had "Settings", then it was cumbersome for admins to get to admin settings quickly, or not clear that this was also there. And "Appearance and accessibility" needs to be reachable quickly to help people in need of assistive technology.

Regarding the icon, yes for sure. @szaimen could you change the icon of "Appearance & accessibility" in the settings to the one we use in the menu (the "human")? Admin theming can keep its icon to distinguish.

**Comment by szaimen** [comment]
WIP: https://github.com/nextcloud/server/pull/34170

**Pull request merged**
