### PR TITLE
[12] Update aws sdk + s3 improvements

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/nextcloud/server/pull/4410 and https://github.com/nextcloud/server/pull/6602

- [ ] requires https://github.com/nextcloud/3rdparty/pull/69

### CODE REVIEW

**Comment by icewind1991** [comment]
@rullzer @schiessle please review

**Comment by rullzer** [comment]
Why?

This only fixes something that never worked before right (>5gb uploads)? So it is a new feature. Why backport? Also I'm really not that comfortable merging such huge changes into a maintenance release.

**Comment by karlitschek** [comment]
This needs to be backported because of an external requirement.

**Comment by icewind1991** [comment]
This is for a customer and has to be merged asap

**Comment by MorrisJobke** [comment]
As this does not have a single review and it caused serious damage on a minor upgrade from 12.0.3 to 12.0.4 (see #7569) I will open a revert for this PR.

**Comment by MorrisJobke** [comment]
> As this does not have a single review and it caused serious damage on a minor upgrade from 12.0.3 to 12.0.4 (see #7569) I will open a revert for this PR.

@icewind1991 Could you take care of this as it seems to be non-trivial, because other backports like #7186 and #7079 went in as well.

**Pull request merged**
