### PR TITLE
Use correct plural implementation for upload estimation

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix https://www.transifex.com/nextcloud/nextcloud/translate/#de/files/91001485

@MorrisJobke @LukasReschke

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
This is fixed on maste?

**Comment by nickvergessen** [comment]
Master uses completly different code it seems, at least I couldn't find the strings.

**Review by LukasReschke — APPROVED** [review]

**Comment by rakekniven** [comment]
@LukasReschke Old code is still present at transifex.
See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/91001440

**Comment by rakekniven** [comment]
Ah, ok. Would you enlighten me on how to do this? Transifex magic?

**Comment by MorrisJobke** [comment]
> Ah, ok. Would you enlighten me on how to do this? Transifex magic?

Not that much magic: https://github.com/nextcloud/docker-ci/blob/master/translations/handleTranslations.sh#L14-L36

We iterate over "stable10 stable11 master" and extract the l10n files, concatenate them with msgcat (which does de-duplication) and use this as resource for transifex.

And the reverse works similar: fetch the translations and then play in the translation into stable10 stable11 and master git branches: https://github.com/nextcloud/docker-ci/blob/master/translations/handleTranslations.sh#L51-L53

**Comment by MorrisJobke** [comment]
> @LukasReschke Old code is still present at transifex.

Next night they will be gone https://github.com/nextcloud/docker-ci/commit/87ab8c15243c089d12db9a5e9660bb2ca3ed2bee 😉

**Pull request merged**
