### PR TITLE
feat: add request id as comment to all queries

### PR DESCRIPTION
**Pull request by icewind1991**
Having the request id in the sql can be useful for various database debugging

### CODE REVIEW

**Comment by icewind1991** [comment]
Silly me, expecting various SQL implementations to support the same comment format...

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
After todays call with the db expert we could even consider this for selects (if the query cache is disabled), which would be recommended anyways these days for MySQL/MariaDB.

**Comment by juliushaertl** [comment]
I think we should not have the request id there by default but could consider it as a config option if an admin is sure that they have the query cache enabled, otherwise there might be quite an overhead invalidating it with every query.

**Comment by icewind1991** [comment]
Put the request id behind the `db.log_request_id` system flag

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
