### PR TITLE
Added test for 26182

### PR DESCRIPTION
**Pull request by MorrisJobke**
Downstream of https://github.com/owncloud/core/pull/26183

cc @LukasReschke @rullzer

### CODE REVIEW

**Comment by rullzer** [comment]
:+1: 
Lets see if CI passes.

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
👍

**Review by nickvergessen — APPROVED** [review]

**Comment by rullzer** [comment]
@MorrisJobke  You didn't sign off!

**Comment by MorrisJobke** [comment]
> @MorrisJobke You didn't sign off!

Because it's an upstream fetch and there I can't sign-off ;)

**Pull request merged**
