### PR TITLE
Select2 adjustments: ellipsize, and adjust height

### PR DESCRIPTION
**Pull request by jancborchardt**
- ellipsize long names with no line break
- make sure dropdown always shows a last half entry to hint at more (instead of having the height contain exactly 4 entries which doesn’t make it immediately obvious there’s more)

Before & after
capture du 2016-11-17 17-26-32capture du 2016-11-17 17-25-56

Please review @nextcloud/designers cc @skjnldsv also something for the inputs SCSS PR I needed to fix right now though ;)

cc @Ivansss @MorrisJobke cause it fixes Spreed style

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Review by Ivansss — APPROVED** [review]
Works for me too 👍

**Comment by jancborchardt** [comment]
Also added cursor: pointer ;D

**Comment by MorrisJobke** [comment]
Still :+1:

**Comment by skjnldsv** [comment]
👍

**Pull request merged**
