### PR TITLE
[stable9] theming app

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/nextcloud/server/pull/59

please do some short tests, the backport needed quite some manual adjustments. 

cc @LukasReschke @jancborchardt

### CODE REVIEW

**Comment by schiessle** [comment]
hm, for some reasons the file system tests fail on the backport. I tried to debug it and the difference between this branch with the last commit and without it is, that with the theming app the storage for the file system tests get wrapped by the trash bin and encryption storage which then fail because of the "dummy paths". Without the theming app this storage wrappers are not applied to the test storage... Does anyone has a idea why this could happen?

**Comment by MorrisJobke** [comment]
> Does anyone has a idea why this could happen?

Sadly not :(

**Comment by nickvergessen** [comment]
Will have a look

**Comment by nickvergessen** [comment]
Fixed, doesn't happen on master because of the `LazyRootFolder`.

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by schiessle** [comment]
all tests successfully passed... Thanks @nickvergessen ! :+1:

**Comment by mar1u5** [comment]
Great to see you here at Nextcloud btw 👊 @nickvergessen

**Pull request merged**
