### PR TITLE
[drone] Give redis a change to fireup

### PR DESCRIPTION
**Pull request by rullzer**
Since the last few errors were 'CLUSTER DOWN'

### CODE REVIEW

**Comment by rullzer** [comment]
It is segfaulting... (at least no 'CLUSTER DOWN'): https://drone.nextcloud.com/nextcloud/server/953/72/memcache-redis-cluster

However, where does the `zend_mm_heap corrupted` come from?

**Comment by rullzer** [comment]
@MorrisJobke ^^

**Comment by MorrisJobke** [comment]
diff between 3.1.1 (installed) and 3.1.3 (latest) have some segfault fixes: https://github.com/gplessis/dotdeb-php-redis/issues/2

**Comment by rullzer** [comment]
GREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEENNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

https://drone.nextcloud.com/nextcloud/server/977/72/memcache-redis-cluster

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
