### PR TITLE
fix(dav): allow multiple organizers if possible

### LINKED ISSUE #41767: [Bug]: "Every instance of the event must have the same organizer."
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Unknown what happens. But there is a recurring error on a production system.

### Steps to reproduce

1. Upload a meeting ics with two organizers

### Expected behavior

No error logged

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
{
  "reqId": "rDTk3zPi12OFt9vTx1Nk",
  "level": 3,
  "time": "2023-11-27T10:18:50+00:00",
  "remoteAddr": "1:2:3",
  "user": "theuser",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/calendars/theuser/default/abcdefg1234%40google.com.ics",
  "message": "Every instance of the event must have the same organizer.",
  "userAgent": "macOS/14.2 (23C5047e) dataaccessd/1.0",
  "version": "28.0.0.7",
  "exception": {
    "Exception": "Sabre\\VObject\\ITip\\SameOrganizerForAllComponentsException",
    "Message": "Every instance of the event must have the same organizer.",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/vobject/lib/ITip/Broker.php",
        "line": 195,
        "function": "parseEventInfo",
        "class": "Sabre\\VObject\\ITip\\Broker",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\Component\\VCalendar",
            "*** sensitive parameters replaced ***",
            "VCALENDAR"
          ]
        ]
      },
      "..."
    ],
    "File": "/var/www/nextcloud/3rdparty/sabre/vobject/lib/ITip/Broker.php",
    "Line": 847,
    "message": "Every instance of the event must have the same organizer.",
    "exception": {},
    "CustomMessage": "Every instance of the event must have the same organizer."
  }
}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by st3iny**
* Resolves: https://github.com/nextcloud/server/issues/41767

## Summary

This is very hacky! However, we want to allow saving events with multiple organizers. Those events are not RFC compliant, but sometimes imported from major external calendar services (e.g. Google). If the current user is not an organizer of the event we ignore the exception as no scheduling messages will be sent anyway.

I'm not very comfortable touching scheduling code so please have a good look. I can provide test ICS files if necessary.

## TODO

- [ ] Test, test and test

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by tcitworld — APPROVED** [review]
Logic is fine to me

**Review by miaulalala — APPROVED** [review]
Looks fine to me.  Psalm isn't happy :)

**Comment by gohrner** [comment]
@st3iny: Regarding:

> It would be cleaner to patch Sabre to validate organizers *after* checking if
> scheduling messages are necessary. Currently, organizers are validated first and
> afterwards the broker checks if messages should be scheduled. So the code will throw
> even if the organizers are not relevant. This is to ensure compliance with RFCs but
> a bit too strict for real world usage.

Did you file an CR for SabreDAV to adjust this and get their feedback?

**Pull request merged**
