### PR TITLE
fix(SetupChecks): Add hint about dns/firewall if `mjs` check can't run

### PR DESCRIPTION
**Pull request by joshtrichards**
## Summary

Helps cut down on troubleshooting time with:

* #43872
* #43757 
* some of the queries that arose in #42989 
* numerous queries that arise on the Help Forum

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by szaimen — APPROVED** [review]

**Comment by susnux** [comment]
@joshtrichards can you change the commit to `fix(...)` which reflects the changes better and complies with conventional commits.

**Comment by joshtrichards** [comment]
Done. Other test failures don't so far appear to be related.

**Pull request merged**
