### PR TITLE
fix: Fix ServiceWorker scope when Nextcloud installed in subfolder

### PR DESCRIPTION
**Pull request by Koc**
## Summary
1. Install Nextcloud into subfolder, e.g. `nc`
2. Open files app

Expected result: ServiceWorker registered only for subfolder
Actual result:  ServiceWorker registered for whole domain

<details><summary>:mag: Screenshot after fix</summary>
<p>

image

</p>
</details> 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by provokateurin** [comment]
I think this is broken, we now register a service worker for each path:
image
There only should be one service worker, otherwise we will consume a lot of resources after navigating through a few folders and so on.

**Comment by provokateurin** [comment]
Fix is at https://github.com/nextcloud/server/pull/49917

**Pull request merged**
