### PR TITLE
Do not send imip email to invalid recipients

### LINKED ISSUE #18941: Bug in saving a meeting when no email address is suppiied
**Steps to reproduce**:

1. Use a calendar app (I use [Evolution](https://en.wikipedia.org/wiki/GNOME_Evolution)) 
2. Create a new [meeting]( https://help.gnome.org/users/evolution/stable/calendar-meetings-sending-invitation.html.en) and add a person to invite **without an email address**
3. Click on _save_

**Expected behaviour**:

The meeting gets saved.

**Actual behaviour**:

The server responds with an error 500. The follwing can be found in the logs:

```
[remote] Error: TypeError: idn_to_ascii() expects parameter 1 to be string, null given at <<closure>>

 0. /var/www/html/lib/private/Mail/Message.php line 78
    idn_to_ascii(null, 0, 1)
 1. /var/www/html/lib/private/Mail/Message.php line 143
    OC\Mail\Message->convertAddresses({foobar: null})
 2. /var/www/html/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php line 233
    OC\Mail\Message->setTo({foobar: null})
 3. <<closure>>
    OCA\DAV\CalDAV\Schedule\IMipPlugin->schedule(Sabre\VObject\IT ... e})
 4. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\DAV\CalDAV\ ... "], [Sabre\VObject\I ... }])
 5. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 384
    Sabre\Event\EventEmitter->emit("schedule", [Sabre\VObject\I ... }])
 6. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 665
    Sabre\CalDAV\Schedule\Plugin->deliver(Sabre\VObject\IT ... e})
 7. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 367
    Sabre\CalDAV\Schedule\Plugin->processICalendarChange(null, Sabre\VObject\Co ... l}, ["mailto:daniel. ... "], [], true)
 8. /var/www/html/apps/dav/lib/CalDAV/Schedule/Plugin.php line 129
    Sabre\CalDAV\Schedule\Plugin->calendarObjectChange(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {}, Sabre\VObject\Co ... l}, "calendars/-l/personal", true, true)
 9. <<closure>>
    OCA\DAV\CalDAV\Schedule\Plugin->calendarObjectChange(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {}, Sabre\VObject\Co ... l}, "calendars/-/personal", true, true)
10. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([OCA\DAV\CalDAV\ ... "], [Sabre\HTTP\Requ ... e])
11. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 943
    Sabre\Event\EventEmitter->emit("calendarObjectChange", [Sabre\HTTP\Requ ... e])
12. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 801
    Sabre\CalDAV\Plugin->validateICalendar("BEGIN:VCALENDAR ... n", "calendars/-", false, Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {}, true)
13. <<closure>>
    Sabre\CalDAV\Plugin->beforeCreateFile("calendars/-", "BEGIN:VCALENDAR ... n", OCA\DAV\CalDAV\Calendar {}, false)
14. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([OCA\DAV\CalDAV\ ... "], ["calendars/-])
15. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1094
    Sabre\Event\EventEmitter->emit("beforeCreateFile", ["calendars/-])
16. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
    Sabre\DAV\Server->createFile("calendars/-", "BEGIN:VCALENDAR ... n", null)
17. <<closure>>
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
18. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
19. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
20. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
21. /var/www/html/apps/dav/lib/Server.php line 317
    Sabre\DAV\Server->exec()
22. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
23. /var/www/html/remote.php line 163
    require_once("/var/www/html/a ... p")

PUT /remote.php/dav/calendars/-/personal/5f279e307a0e32e52689f5cc27b1b37c8b881ff2.ics
from 181.18.0.1 by - at 2020-01-16T18:23:22+00:00
```

My Nextcloud version is `17.0.2.1`

**Note** If you think this is a problem with Evolution instead of Nextcloud, please notify me and I will file a bug report for Evolution.

### PR DESCRIPTION
**Pull request by ChristophWurst**
I just had an error caused by Calendar as I trued to save this vcard:

```
BEGIN:VCALENDAR
PRODID:-//IDN nextcloud.com//Calendar app 2.1.3//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
CREATED:20210211T120406Z
DTSTAMP:20210211T121704Z
LAST-MODIFIED:20210211T121704Z
SEQUENCE:3
UID:4d5ce95b-a3b3-48cd-bf3b-1d66d5560f98
DTSTART;TZID=Europe/Vienna:20210211T100000
DTEND;TZID=Europe/Vienna:20210211T173000
SUMMARY:Busy
TRANSP:OPAQUE
ATTENDEE;CN=otheruser;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTIC
 IPANT;RSVP=FALSE:mailto:
ORGANIZER;CN=admin:mailto:myemail@domain.com
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Vienna
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```
<details>

```json
{
  "reqId": "nQnCxyq0HNQqfZZFuxWv",
  "level": 4,
  "time": "2021-02-11T12:18:06+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "admin",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/calendars/admin/personal/7A27E6FF-0910-46B1-A0CF-429B35126D4D.ics",
  "message": {
    "Exception": "TypeError",
    "Message": "idn_to_ascii() expects parameter 1 to be string, null given",
    "Code": 0,
    "Trace": [
      {
        "file": "/home/christoph/workspace/nextcloud/lib/private/Mail/Message.php",
        "line": 84,
        "function": "idn_to_ascii",
        "args": [
          "*** sensitive parameter replaced ***",
          0,
          1
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/lib/private/Mail/Message.php",
        "line": 149,
        "function": "convertAddresses",
        "class": "OC\\Mail\\Message",
        "type": "->",
        "args": [
          {
            "": "otheruser"
          }
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php",
        "line": 238,
        "function": "setTo",
        "class": "OC\\Mail\\Message",
        "type": "->",
        "args": [
          {
            "": "otheruser"
          }
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "schedule",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\IMipPlugin",
        "type": "->",
        "args": [
          {
            "uid": "4d5ce95b-a3b3-48cd-bf3b-1d66d5560f98",
            "component": "VEVENT",
            "method": "REQUEST",
            "sequence": 3,
            "sender": "mailto:myemail@domain.com",
            "senderName": {
              "name": "CN",
              "noName": false,
              "parent": null,
              "__class__": "Sabre\\VObject\\Parameter"
            },
            "recipient": "mailto:",
            "recipientName": "otheruser",
            "scheduleStatus": "3.7;Could not find principal.",
            "message": {
              "name": "VCALENDAR",
              "parent": null,
              "__class__": "Sabre\\VObject\\Component\\VCalendar"
            },
            "significantChange": true,
            "__class__": "Sabre\\VObject\\ITip\\Message"
          }
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 350,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "schedule",
          [
            {
              "uid": "4d5ce95b-a3b3-48cd-bf3b-1d66d5560f98",
              "component": "VEVENT",
              "method": "REQUEST",
              "sequence": 3,
              "sender": "mailto:myemail@domain.com",
              "senderName": {
                "name": "CN",
                "noName": false,
                "parent": null,
                "__class__": "Sabre\\VObject\\Parameter"
              },
              "recipient": "mailto:",
              "recipientName": "otheruser",
              "scheduleStatus": "3.7;Could not find principal.",
              "message": {
                "name": "VCALENDAR",
                "parent": null,
                "__class__": "Sabre\\VObject\\Component\\VCalendar"
              },
              "significantChange": true,
              "__class__": "Sabre\\VObject\\ITip\\Message"
            }
          ]
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 626,
        "function": "deliver",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          {
            "uid": "4d5ce95b-a3b3-48cd-bf3b-1d66d5560f98",
            "component": "VEVENT",
            "method": "REQUEST",
            "sequence": 3,
            "sender": "mailto:myemail@domain.com",
            "senderName": {
              "name": "CN",
              "noName": false,
              "parent": null,
              "__class__": "Sabre\\VObject\\Parameter"
            },
            "recipient": "mailto:",
            "recipientName": "otheruser",
            "scheduleStatus": "3.7;Could not find principal.",
            "message": {
              "name": "VCALENDAR",
              "parent": null,
              "__class__": "Sabre\\VObject\\Component\\VCalendar"
            },
            "significantChange": true,
            "__class__": "Sabre\\VObject\\ITip\\Message"
          }
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 337,
        "function": "processICalendarChange",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          {
            "name": "VCALENDAR",
            "parent": null,
            "__class__": "Sabre\\VObject\\Component\\VCalendar"
          },
          {
            "name": "VCALENDAR",
            "parent": null,
            "__class__": "Sabre\\VObject\\Component\\VCalendar"
          },
          [
            "mailto:myemail@domain.com",
            "/remote.php/dav/principals/users/admin/"
          ],
          [],
          true
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/apps/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 150,
        "function": "calendarObjectChange",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          },
          {
            "name": "VCALENDAR",
            "parent": null,
            "__class__": "Sabre\\VObject\\Component\\VCalendar"
          },
          "calendars/admin/personal",
          true,
          false
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "calendarObjectChange",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          },
          {
            "name": "VCALENDAR",
            "parent": null,
            "__class__": "Sabre\\VObject\\Component\\VCalendar"
          },
          "calendars/admin/personal",
          true,
          false
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
        "line": 897,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "calendarObjectChange",
          [
            {
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            },
            {
              "name": "VCALENDAR",
              "parent": null,
              "__class__": "Sabre\\VObject\\Component\\VCalendar"
            },
            "calendars/admin/personal",
            true,
            false
          ]
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
        "line": 739,
        "function": "validateICalendar",
        "class": "Sabre\\CalDAV\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameter replaced ***",
          "*** sensitive parameter replaced ***",
          false,
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          },
          false
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "beforeWriteContent",
        "class": "Sabre\\CalDAV\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameter replaced ***",
          {
            "__class__": "OCA\\DAV\\CalDAV\\CalendarObject"
          },
          "*** sensitive parameter replaced ***",
          false
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1133,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "beforeWriteContent",
          [
            "*** sensitive parameter replaced ***",
            {
              "__class__": "OCA\\DAV\\CalDAV\\CalendarObject"
            },
            "*** sensitive parameter replaced ***",
            false
          ]
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 492,
        "function": "updateFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:PUT",
          [
            {
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/home/christoph/workspace/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/home/christoph/workspace/nextcloud/apps/dav/lib/Server.php",
        "line": 332,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/home/christoph/workspace/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/home/christoph/workspace/nextcloud/remote.php",
        "line": 167,
        "args": [
          "/home/christoph/workspace/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/home/christoph/workspace/nextcloud/lib/private/Mail/Message.php",
    "Line": 84,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0",
  "version": "22.0.0.0"
}
```

</details>

This smells very related to https://github.com/nextcloud/server/pull/25310.

Fixes https://github.com/nextcloud/server/issues/18941 https://github.com/nextcloud/server/issues/15243

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
seems sane. Is it easy to add some tests?

**Review by tcitworld — CHANGES_REQUESTED** [review]
Needs tests changes into `IMipPluginTest.php`.

**Comment by tcitworld** [comment]
Makes me think we could first check in `validateMailAddress` that the `$email` length is > 0 without even loading the validators.

**Comment by ChristophWurst** [comment]
> Makes me think we could first check in `validateMailAddress` that the `$email` length is > 0 without even loading the validators.

https://github.com/nextcloud/server/pull/25585 :)

**Review by tcitworld — APPROVED** [review]

**Pull request merged**
