### PR TITLE
Group shares with same source and target 

### PR DESCRIPTION
**Pull request by rullzer**
From https://github.com/owncloud/core/pull/25534 (original https://github.com/owncloud/core/pull/25113)

Please test carefully.
Including upgrading from 9.0

CC: @schiessle @nickvergessen @icewind1991 @LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by rullzer** [comment]
Rebased.
Needs to get in after https://github.com/nextcloud/server/pull/500

**Comment by rullzer** [comment]
I'll prepare a backport for NC10

**Comment by nickvergessen** [comment]
#500 is merged

**Comment by rullzer** [comment]
Also need https://github.com/owncloud/core/pull/25567

**Comment by rullzer** [comment]
Rebased and added https://github.com/owncloud/core/pull/25567

Lets see what CI says

**Comment by schiessle** [comment]
- [ ] if this is merged we probably also want to cherry-pick this upstream fix: https://github.com/owncloud/core/pull/25568

**Comment by rullzer** [comment]
@schiessle already added here ;)

**Comment by rullzer** [comment]
Aah failing intergration tests. I'll look at this later.

**Comment by schiessle** [comment]
@rullzer perfect :smiley:

**Comment by rullzer** [comment]
@schiessle @LukasReschke @icewind1991 @MorrisJobke @nickvergessen 

please review

**Comment by schiessle** [comment]
I found a problem.

0. login as admin
1. create two groups G1 and G2
2. share a folder with both groups
3. create a user user1 and add it to both gorups G1 and G2
4. login as user1
5. user1 sees the folder only once, this is correct
6. login again as admin
7. remove share with G1
8. login as user1
9. share is gone even if the folder is still shared with G2 and user1 is a  member of G2

**Comment by schiessle** [comment]
Didn't which doesn't work as well:

1. create user1 and add him to the group G1 and G2
2. admin shares folder with G1
3. login as user1 and you will see the shared folder
4. login as admin and share the folder additionally with G2
5. go back to user1 -> shared folder is no longer visible

**Comment by schiessle** [comment]
tested, works :+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍 

@rullzer But there is a merge conflict.

**Comment by MorrisJobke** [comment]
@rullzer Do we want this to be shipped with 10?

**Comment by rullzer** [comment]
Yes I'll prepare a backport

**Pull request merged**
