### PR TITLE
Show pending popover menu when password is enabled by default

### PR DESCRIPTION
**Pull request by danxuliu**
When `Enforce password protection` is enabled in the sharing settings a popover menu is shown to set a password before the share is created. On the other hand, when `Always ask for a password` was enabled in the sharing settings and a new link share was created the share was immediately created with a default password; the user was not able to specify a password (nor create the share without password).
    
The component template [already provided the needed elements](https://github.com/nextcloud/server/blob/8633f13e0af8c803cd419af2a611c41708e9c7c1/apps/files_sharing/src/components/SharingEntryLink.vue#L70-L88) to also ask for the password without enforcing it, but the popover menu was not shown due to `enableLinkPasswordByDefault` being missing in `if` conditions.

## How to test

- Open the Sharing section in the admin settings
- Wait until the page has fully loaded (otherwise you could hit the issue fixed in #38163)
- Enable "Always ask for a password"
- Open the Files app
- Create a link share for a file

### Result with this pull request

A popover menu is shown to set or remove the password of the share; a default password is pre-filled

### Result without this pull request

The share is immediately created with a default password, and even if the menu of the share is opened the password can not be shown (_●●●●●●●●●●●●●●●_ is replaced by _***************_)

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Comment by danxuliu** [comment]
Rebased and rebuilt to solve conflicts.

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
/backport d80f8fc84f0e548ebf7520ee0995d6e06ec00c1d,d4631921b4f4ab2832bc6698def47aa16d60c621 to stable26

**Pull request merged**
