### PR TITLE
Mark compiled CSS as binary

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Mark compiled CSS as binary in the `.gitattributes` file as viewing the textual diff of a single long line in e.g. https://github.com/nextcloud/server/blob/4caa90dfb643aea958b10d0741a8f21be5e18f39/core/css/server.css and https://github.com/nextcloud/server/blob/4caa90dfb643aea958b10d0741a8f21be5e18f39/core/css/server.css.map is not necessary when the source SCSS files e.g. https://github.com/nextcloud/server/blob/4caa90dfb643aea958b10d0741a8f21be5e18f39/core/css/styles.scss are much more readable

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by ChristophWurst — APPROVED** [review]
Might also make sense to move generated css files to /dist and leave core/css for source files only

**Comment by skjnldsv** [comment]
> Might also make sense to move generated css files to /dist and leave core/css for source files only

Won't work with our `addScript` php handler

**Review by artonge — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> Won't work with our `addScript` php handler

yet ;)

**Pull request merged**
