### PR TITLE
Add a repair step to fix broken mounts

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref #2397

### CODE REVIEW

**Comment by schiessle** [comment]
any chance to add a simple unit test? would feel more comfortable with it.

**Comment by icewind1991** [comment]
This should also be doable with a single nested query, which should make it a lot faster if you have hunders or thousands of users

**Comment by nickvergessen** [comment]
IIRC mysql has problems (does not allow) joins on update and delete, so better save then sorry. Also this is only done on update and only for broken storages, so should be more of a one time thing.

**Comment by nickvergessen** [comment]
Adding tests now

**Comment by LukasReschke** [comment]
@nickvergessen Also needs a rebase and an updated autoloader file.

**Review by LukasReschke — APPROVED** [review]
LGTM and will also test this later on c.nc.c with some more real-life data.

I'd anyways appreciate final reviews of @schiessle and @icewind1991

**Review by icewind1991 — APPROVED** [review]

**Review by schiessle — APPROVED** [review]

**Pull request merged**
