### PR TITLE
Handle limit offset and sorting in files search

### PR DESCRIPTION
**Pull request by icewind1991**
- Use Node search api directly from files' search provider, skipping a few deprecated layers
- Unify handling of node search methods by transforming all search methods into "new" search queries
- Handle limit, offset and order in node search api (in a somewhat suboptimal way)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Thanks for this @icewind1991 !

**Review by MorrisJobke — APPROVED** [review]
Tested and still works 👍

**Pull request merged**
