### PR TITLE
[stable12] Update Opcache recommendation

### LINKED ISSUE #4838: Recommendation for php.ini mistake in nc 12 beta 2
The admin screen warns about unoptimized php settings, but the first value mentioned seems broken:
```php_value opcache.enable=on```
That should, I believe, be:
```php_value opcache.enable=1```

This is Nextcloud 12 Beta 2.

See:
screenshot_20170509_124940

### PR DESCRIPTION
**Pull request by MorrisJobke**
* update to the setting value as it is written in the PHP documentation
* fixes #4838
* backport of #5014 
* tested here and works fine

cc @riegercloud @jospoortvliet 

@LukasReschke Would be nice to get this into the 12.0.0 because it contains updated recommendations. ;)

### CODE REVIEW

**Comment by riegercloud** [comment]
the statement in /nextcloud/.user.ini

> .user.ini

regarding output_buffer haave to be adjusted to

> 'Off'

instead of 

> 0

either.

**Comment by riegercloud** [comment]
the statement in /nextcloud/.user.ini

> .user.ini

regarding output_buffer have to be adjusted to

> 'Off'

instead of 

> 0

either.

**Comment by MorrisJobke** [comment]
@riegercloud Could you open a new ticket for this, because this is completely unrelated.

**Comment by riegercloud** [comment]
apologize, i did [#478](https://github.com/nextcloud/documentation/issues/478) it.

**Comment by MorrisJobke** [comment]
> apologize, i did #478 it.

Don't worry :) Thanks for the feedback

**Review by rullzer — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
