### PR TITLE
Stop sending deprecated Pragma header

### PR DESCRIPTION
**Pull request by solracsf**
## Summary
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma
image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by szaimen** [comment]
Thanks! But arent there further places? https://github.com/search?q=repo%3Anextcloud%2Fserver%20Pragma&type=code

**Comment by solracsf** [comment]
True. I'll take care of these ASAP.

**Review by ChristophWurst — APPROVED** [review]

**Comment by tcitworld** [comment]
There's also another occurrence in `apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php`

**Comment by nickvergessen** [comment]
Tests are failing:
grafik

**Review by miaulalala — CHANGES_REQUESTED** [review]
Nice :+1:  Thanks for taking care of this.

Can you squash your commits pls?

**Comment by solracsf** [comment]
Well...i tried but i got errors.
> Unable to squash. Squashing replays all commits up to the last one required for the squash. A merge commit cannot exist among those commits.

I can't event hard reset the branch :\
Should I open a clean PR?

**Review by miaulalala — APPROVED** [review]

**Comment by susnux** [comment]
Cypress unrelated

**Pull request merged**
