### PR TITLE
feat(files): refresh preview on etag change

### LINKED ISSUE #44630: [Bug]: Thumbnail doesn't update when source image is changed
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If you upload an image to Nextcloud (via external storage), the thumbnail will load as normal. 
However when you replace the source image, Nextcloud will sitll use the old thumbnail for the image. 

This wasn't the case a few years ago

### Steps to reproduce

1. Upload an image to NC via SMB or external storage method
2. Open NC on an iPad, goto the directory and the thumbnail will generate
3. Upload a new image or tweaked image to NC via SMB or external method, as long as original image is replace
4. Open NC again and the old image thumbnail will still be used even though NC will show the image is modified

### Expected behavior

NC should always be showing the thumbnail that represents the source image

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

None

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/44630

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Tested and works. :) 

However the sidebar still seems to have the old picture:
image

**Review by susnux — COMMENTED** [review]
Works but also needs to be fixed on `apps/files/src/views/Sidebar.vue::getPreviewIfAny`

**Comment by skjnldsv** [comment]
> Works but also needs to be fixed on `apps/files/src/views/Sidebar.vue::getPreviewIfAny`

Sure :sweat_smile:

**Review by szaimen — APPROVED** [review]
Tested and works. However the conflict picker also has the problem:
image

**Comment by skjnldsv** [comment]
> the conflict picker also has the problem

https://github.com/nextcloud-libraries/nextcloud-upload/pull/1214

**Review by artonge — APPROVED** [review]

**Review by susnux — COMMENTED** [review]
Nice!

**Pull request merged**
