### PR TITLE
[Small] Hint should not be clickable

### PR DESCRIPTION
**Pull request by ArtificialOwl**
Signed-off-by: Maxence Lange <maxence@nextcloud.com>

### CODE REVIEW

**Comment by daita** [comment]
selection_024

The hint from the App Menu is clickable and the UX can be really frustrating on a trackpad if your mouse went slightly over the App Menu and put the hint box right over the button you just clicked.

**Comment by MariusBluem** [comment]
I‘d love to see this backported 👍

**Review by juliusknorr — APPROVED** [review]
Never experienced an issue with that myself, but fine by me. :+1:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
