### PR TITLE
Improve performance of external storage config UI

### PR DESCRIPTION
**Pull request by icewind1991**
greatly improves the performance of the external storage web ui when a large amount of storages are configured.

This takes loading the UI from ~5m to ~10s when having 1000 storages configured.

(long term this needs to be ported to vue but that's for another day)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: nice catch

I'm guessing that with 1000 storages the UX will anyway suffer and some kind of search would need to be implemented eventually

**Review by artonge — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by CarlSchwan** [comment]
> +1 nice catch
> 
> I'm guessing that with 1000 storages the UX will anyway suffer and some kind of search would need to be implemented eventually

with 1000 storages, I'm guessing that it's starting to also be a good idea to define this configuration in Ansible or similar. Usually, these are not configured manually or I hope so.

**Comment by skjnldsv** [comment]
jsunit says no

**Comment by icewind1991** [comment]
fixed jsunit

**Review by Pytal — APPROVED** [review]

**Pull request merged**
