### PR TITLE
Allow to call the files even when you are in another instance atm

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Have Nextcloud 11 installed in 11/server/
2. Have Nextcloud 10 installed in 10/server/
3. Open terminal in 10/server/
4. Run `../../11/server/occ config:system:get apps_paths`
### Expected

Path should be `11/server/apps/`
### Actually

Path is `10/server/apps/`

Problem is we are including the wrong `lib/base.php` Oo

@MorrisJobke @LukasReschke @BernhardPosselt 
@karlitschek should backport this

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport 👍

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
> Problem is we are including the wrong lib/base.php Oo

and this is officially not supported :cry: 

Let me test this nevertheless.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
