### PR TITLE
Set proper web title for apple

### PR DESCRIPTION
**Pull request by rullzer**
Easy one: @LukasReschke @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> we should use the instance name from OC_Defaults/ThemingDefaults here: $theme->getName()

You are right - I just forgot about that.

**Comment by nickvergessen** [comment]
Updated

**Comment by juliushaertl** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by jancborchardt** [comment]
@rullzer @nickvergessen should be backported to the stable branches as important name change, right? cc @karlitschek

**Comment by karlitschek** [comment]
Should be low risk. Please backport! 👍

**Comment by MorrisJobke** [comment]
Let me backport this

**Comment by MorrisJobke** [comment]
stable10: #1697 
stable9: #1699

**Pull request merged**
