### PR TITLE
Fix missing translation of "Personal" calendar in activities

### LINKED ISSUE #6842: Feature: Possibility to change name of default calendar
### Steps to reproduce
1. Login to Nextcloud
2. It is created a new calendar "personal" automatically

### Expected behaviour
It should be possible to change the name of the default calendar by (e.g.) config.php-setting. In German the word "Personal" is also the name of the human resource department. This means that an user gets the notification that he created a calendar for the HR-department....

### Actual behaviour
The default calendar is always "personal".

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0.19

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh installation

**Where did you install Nextcloud from:** from Website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #6842

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by blizzz** [comment]
How long do we need to carry the legacy with us?

**Comment by nickvergessen** [comment]
> How long do we need to carry the legacy with us?

Until we don't care that these events are not parsed in the stream + email anymore.

I would just keep them until I don't feel like anymore, because the thing is they are still generated like that in 12 (11) so when you update and got one generated on the day before, it will still show, but not render anymore. So the longer the better.

**Comment by blizzz** [comment]
> > How long do we need to carry the legacy with us?

> Until we don't care that these events are not parsed in the stream + email anymore.
>
> I would just keep them until I don't feel like anymore, because the thing is they are still generated like that in 12 (11) so when you update and got one generated on the day before, it would still show, but not render anymore. So the longer the better.

Imho it's worth to have this in a code comment, so this piece of knowledge does not get lost over time.

**Comment by nickvergessen** [comment]
Added a comment

**Comment by nickvergessen** [comment]
@blizzz re-review?

**Review by blizzz — APPROVED** [review]

**Pull request merged**
