### PR TITLE
fix(files): url used to retrive storage stats

### PR DESCRIPTION
**Pull request by max-nextcloud**
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- No tests - sorry. I assume this will be rewriten as part of files to vue rework anyway.
- Documentation is not required
- Backports are not required as this is not a **critical** bugfix. At least i have not found any impact of the requests returning an html response.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@max-nextcloud backports?

**Comment by max-nextcloud** [comment]
> @max-nextcloud backports?

I'd say no as this is not a **critical** bugfix. At least i have not found any impact of the requests returning an html response other than funny content in the network tab.

**Comment by max-nextcloud** [comment]
Well... I guess stable27 might still make sense as that will be around for a while and I also don't see any downside to backporting this.

**Pull request merged**
