### PR TITLE
remove old logging section

### PR DESCRIPTION
**Pull request by icewind1991**
Is replaced with https://github.com/nextcloud/logreader

cc @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by icewind1991** [comment]
fixes #2210

**Comment by LukasReschke** [comment]
LGTM

**Comment by LukasReschke** [comment]
Tests failing though, @icewind1991 can you take a look?

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
