### PR TITLE
also compare storage ids when checking for changed mounts

### LINKED ISSUE #2397: Incomplete mounts table
@icewind1991 last week you found an issue with the incomplete mount table.

I just upgraded my personal installation to the beta2. And was hit with the same issue (previews breaking, direct links failing). Only on my installation the files_sharing app was still enabled. Disabling and reenabling fixed the issue.

I have been unable to reproduce it since. But this is not good for UX.
Do we need a repair step or something?

CC: @LukasReschke

### PR DESCRIPTION
**Pull request by icewind1991**
Fix #2397

### CODE REVIEW

**Comment by nickvergessen** [comment]
Also fixes #2397 👍

**Comment by schiessle** [comment]
Tested and works! 👍

**Review by schiessle — APPROVED** [review]

**Comment by schiessle** [comment]
@icewind1991 your last commit brokes it. Now all storage_id's are set to '0' on my oc_mounts table

**Comment by schiessle** [comment]
Tested and still works! 👍

**Comment by LukasReschke** [comment]
Will just fast-forward the branch.

**Pull request merged**
