### PR TITLE
fix filename overlapping on mobile

### PR DESCRIPTION
**Pull request by GretaD**
ref #17364

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
@Bables55 @Octopus2 @AndyFx12 @DmDS @elpraga @justasomeone since you reported this in issue #17364, could you try testing and reviewing this fix? That helps a lot, thanks! :)

**Comment by Octopus2** [comment]
Screenshot_20191012-123741_Chrome

I changed the scss-file on my 17.0 installation. I used "maintenance:repair"in the console and cleared the browsercache to see this change. It looks now like this and can be used. But there is no 3-doots-menu in root....

**Comment by Octopus2** [comment]
Screenshot_20191012-123555_Chrome

Interesting: Subfolders have a 3-dot-menu....

**Comment by Octopus2** [comment]
I played around on root: when i change the view from details to thumbnail and then back i get the three-dots-menu.... But its gone after reloading the page....

**Comment by elpraga** [comment]
I've just applied the patch. And everything seems to be working as expected. I can see even the three dot menu in the root folder.

**Comment by AndyFx12** [comment]
Sorry - but this fix seems not to work (or I did something wrong ...).

NC17.0 with fixes
Screenshot_20191013-203429

NC16.05:
Screenshot_20191013-203630

Andy

**Review by juliusknorr — APPROVED** [review]
Tested and works :+1:

**Comment by juliushaertl** [comment]
@AndyFx12 We cache css files pretty heavily on production systems. Try running occ maintenance:repair after the patch is applied.

**Comment by jancborchardt** [comment]
What about the Drone failure here? :)

**Comment by AndyFx12** [comment]
After occ maintenance:repair AND clear browser-cache it works fine:
Screenshot_20191025-143510

**Comment by skjnldsv** [comment]
> What about the Drone failure here? :)

timeouts :)

**Comment by jancborchardt** [comment]
Hmm, it actually looks a bit strange, the share icon and the avatars are not horizontally aligned, but right-aligned?

**Comment by juliushaertl** [comment]
@jancborchardt Please open a new issue. It is not really related as it was like that before. :wink:

**Pull request merged**
