### PR TITLE
Allow multiple names and description

### LINKED ISSUE #1466: Bug: info.xml interpretation not the latest
### Steps to reproduce
1. Install for example the next notes app from the appstore. (An app with language attribute and multiple name tags in the info.xml is required)
2. got to `/index.php/settings/apps?category=enabled#`

### Expected behaviour
I would expect the app list.

### Actual behaviour
Enabled site shows loading state forever.

### Server configuration
**Operating system**: Linux (Debian 8)

**Web server:** Php Test server

**Database:** Postgre 9.4

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page)
11.0 alpha / but seems to be the same on 10 (because this [issue](https://github.com/janis91/nextnotes/issues/31) for my app was reported with version 10)

**Updated from an older Nextcloud/ownCloud or fresh install:**
no

**Where did you install Nextcloud from:**
git

The other topics of the report template are not necessary. I know the reason of the bug.

### Client configuration
**Browser:**
Firefox 45

**Operating system:**
Debian 8

#### Web server error log
<details>
<summary>Web server error log</summary>
```
[Tue Sep 20 15:43:20 2016] Array to string conversion at /server/settings/Controller/AppSettingsController.php#204
[Tue Sep 20 15:43:20 2016] Array to string conversion at /server/settings/Controller/AppSettingsController.php#203
```
</details>

#### Nextcloud log (data/nextcloud.log)
(I know the time of the webserver is set wrong, but it's the same call.)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"I+cw\/09tssdKURXaW\/Fd","remoteAddr":"::1","app":"PHP","message":"Array to string conversion at \/server\/settings\/Controller\/AppSettingsController.php#204","level":0,"time":"2016-09-20T13:43:20+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=0","user":"admin"}
{"reqId":"I+cw\/09tssdKURXaW\/Fd","remoteAddr":"::1","app":"PHP","message":"Array to string conversion at \/server\/settings\/Controller\/AppSettingsController.php#203","level":0,"time":"2016-09-20T13:43:20+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=0","user":"admin"}
```
</details>

#### Browser log
Actually I don't know exactly if this has the same reason.
<details>
<summary>Browser log</summary>
```
TypeError: t.charAt is not a function
OC.Util._chunkify()
 js.js:1881
OC.Util.naturalSortCompare()
 js.js:1904
OC.Settings.Apps<.loadCategory/this._loadCategoryCall<.success/<()
 apps.js:103
OC.Settings.Apps<.loadCategory/this._loadCategoryCall<.success()
 apps.js:100
n.Callbacks/j()
 jquery.min.js:2
n.Callbacks/k.fireWith()
 jquery.min.js:2
x()
 jquery.min.js:4
.send/b/<()
```
</details>

#### Recommended Solution
I would recommend to change the necessary lines of code, which read the info.xml, because the defintion changed in some points [(info.xsd)](https://apps.nextcloud.com/schema/apps/info.xsd).
The reason of this specific bug is the following: in lines 203 and 204 (also 238/239 and maybe other lines as well) of the AppSettingsController.php (method: listApps) the tags of the info.xml are read.

```
$apps = $this->getInstalledApps($includeUpdateInfo);
					usort($apps, function ($a, $b) {
						$a = (string)$a['name'];
						$b = (string)$b['name'];
						if ($a === $b) {
							return 0;
						}
						return ($a < $b) ? -1 : 1;
					});
```

The new name tag's max occurrences number is unbounded as of the info.xsd:
`<xs:element name="name" type="l10n-string" minOccurs="1" maxOccurs="unbounded"/>`
 
Because of this the method has to be changed in a way, that supports multiple name tags. (l10n support)

_Maybe there are other occurrences and other interpreted tags as well, which have to be changed._

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Fix translatable name
- [x] Fix translatable summary
- [x] Fix translatable description
- [x] Fix multiple authors
- [x] Fallback from de_DE to de

Fix #1466 

@janis91 @JSoko feel free to test.

@BernhardPosselt since you introduced this new feature with the app store.

@MorrisJobke @LukasReschke 
I think we should backport this, because otherwise an app with such values renders the app management page useless

### CODE REVIEW

**Comment by janis91** [comment]
For me the page shows up now and the app is listed. BUT: As the specification of the appstore fields for the description suggests, my app is using markdown. And as you can see, this is not supported yet:
[http://imgur.com/a/JolnG](http://imgur.com/a/JolnG)

**Comment by janis91** [comment]
And maybe it would be even nicer to show the correct language if available.

**Comment by JSoko** [comment]
> For me the page shows up now and the app is listed.
Works here too! :-)

**Comment by nickvergessen** [comment]
Yeah we don't support any mark up yet...

**Comment by nickvergessen** [comment]
> And maybe it would be even nicer to show the correct language if available.

That is already done

**Comment by janis91** [comment]
> That is already done

As you can see in the screenshot I mentioned above, this isn't the case for me.

**Comment by nickvergessen** [comment]
Maybe you use the language `de_DE` which is not defined for this app?

**Comment by janis91** [comment]
I don't provide any translation files for this app, yet. But the info.xml has a description and a summary tag present. In a "en" and "de" version. Is this wrong?

**Comment by BernhardPosselt** [comment]
@janis91 no, if you run de_DE it should fall back to de if de_DE is not present as translation.

**Comment by janis91** [comment]
How do I actually run "de_DE" ? I just work with a browser setup in german. And the whole nextcloud shows up in german. The only thing that is not used is the german translation in the appinfo/info.xml of my app. It is present like follows:

<description lang="en"></description> and 
<description lang="de"></description>

The only thing which is completely missing (I don't know if that has an influence on that) is the transifex setup and therefore the appropriate en.json and de.json files, because it is only requested yet.

**Comment by BernhardPosselt** [comment]
You can switch the language in your profile

**Comment by nickvergessen** [comment]
Added todo "Fallback from de_DE to de"

**Comment by janis91** [comment]
I looked into it and this definetly causes the problem. I think the fallback is the right way! Thanks!

**Comment by nickvergessen** [comment]
Added the language fallback from `de` to `de_DE` and the other way around.

**Comment by janis91** [comment]
tested it. and it works! nice :+1:
(although the markdown is not supported yet)

**Comment by nickvergessen** [comment]
Markdown is being discussed in https://github.com/nextcloud/server/pull/1594

**Comment by MorrisJobke** [comment]
Tested and works :

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
