### PR TITLE
l10n: Change plural to singular

### PR DESCRIPTION
**Pull request by rakekniven**
Here you can select the default theme image, not images.

Reported at Transifex.

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
After rebasing, you can trigger the compile bot like this (see following comments)

**Comment by skjnldsv** [comment]
> /compile

No! You have to wait for the rebase to make sure your compile action will not have conflicts.
I [canceled your run](https://github.com/nextcloud/server/actions/runs/2855054285) :wink:

**Comment by skjnldsv** [comment]
Now that you're rebased, you can use the compile (please use amend to avoid creating unnecessary commit)

**Comment by skjnldsv** [comment]
> Where do I find documentation about this steps?
> Are they GitHub features or does Nextcloud define these steps?

They're Nextcloud tools mostly designed to help and accelerate our processes.
It's not really official or anything :shrug:

**Comment by jancborchardt** [comment]
So actually it is intended to be "Default images", as for dark mode there is a different image (maybe not obvious). But since with the next version we are moving away from that, it’s actually correct to use the singular. :) Just for reference @juliushaertl

**Pull request merged**
