### PR TITLE
Use a proper upload file so propfinds return 404

### LINKED ISSUE #20235: Instant upload from Android app fails
I took a multiple photos today with my mobile phone and for one photo the instant upload from Android fails repeatingly.

I chose the server repository because the error in the nextcloud.log looks like a server issue:

````
{"reqId":"lO6ofag5CjHNz9xxnwq7","level":4,"time":"2020-03-30T17:50:48+00:00","remoteAddr":"89.247.35.166","user":"bjoern","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/uploads/bjoern/4e4452a6ee37a7444aaf6649f25293c8","message":{"Exception":"OCP\\Files\\NotFoundException","Message":"/bjoern/files/4e4452a6ee37a7444aaf6649f25293c8/0000000000000000-0000000005494087","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":137,"function":"get","class":"OC\\Files\\Node\\Root","type":"->","args":["/bjoern/files/4e4452a6ee37a7444aaf6649f25293c8/0000000000000000-0000000005494087"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/SharesPlugin.php","line":157,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->","args":["/4e4452a6ee37a7444aaf6649f25293c8/0000000000000000-0000000005494087"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/SharesPlugin.php","line":210,"function":"getShares","class":"OCA\\DAV\\Connector\\Sabre\\SharesPlugin","type":"->","args":[{"__class__":"OCA\\DAV\\Connector\\Sabre\\File"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":98,"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\SharesPlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/SharesPlugin.php","line":213,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{http://nextcloud.org/ns}sharees",{"__class__":"Closure"}]},{"function":"handleGetProperties","class":"OCA\\DAV\\Connector\\Sabre\\SharesPlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\File"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\SharesPlugin"},"handleGetProperties"],[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\File"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1059,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\File"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":981,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\File"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/bjoern/4e4452a6ee37a7444aaf6649f25293c8",["{DAV:}creationdate","{DAV:}getetag","{http://owncloud.org/ns}permissions","{DAV:}getlastmodified","{http://owncloud.org/ns}id","{DAV:}getcontentlength","{http://owncloud.org/ns}favorite","{DAV:}resourcetype","{http://nextcloud.org/ns}sharees","{DAV:}displayname","{DAV:}getcontenttype","{http://nextcloud.org/ns}has-preview","{http://owncloud.org/ns}size"],1]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://wolke.schiessle.org/remote.php/dav/uploads/bjoern/4e4452a6ee37a7444aaf6649f25293c8","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https://wolke.schiessle.org/remote.php/dav/uploads/bjoern/4e4452a6ee37a7444aaf6649f25293c8","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https://wolke.schiessle.org/remote.php/dav/uploads/bjoern/4e4452a6ee37a7444aaf6649f25293c8","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://wolke.schiessle.org/remote.php/dav/uploads/bjoern/4e4452a6ee37a7444aaf6649f25293c8","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":165,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Files/Node/Root.php","Line":203,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.11.0","version":"18.0.3.0"}
````

As you can see I get a file not found exception for `/bjoern/files/4e4452a6ee37a7444aaf6649f25293c8/0000000000000000-0000000005494087` which looks strange because the right path would be `bjoern/uploads/4e4452a6ee37a7444aaf6649f25293c8/0000000000000000-0000000005494087`

I'm running Nextcloud 18.0.3

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #20235, Closes #20569

By using an UploadFile we make sure that we don't need to have another
check everywhere for the path. But we just have ot check (which we have
to anyway) if it is a proper Connector/File (or directory).

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by kesselb** [comment]
Nice 👍 That works because sabreNode is not a instance of Node anymore 👏

**Comment by kesselb** [comment]
```
Index: apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php	(revision 8730cc6764d6e6c030602088835e473268d3a384)
+++ apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php	(date 1587461360870)
@@ -32,6 +32,7 @@
 use OCA\DAV\Connector\Sabre\Directory;
 use OCA\DAV\Connector\Sabre\File;
 use OCA\DAV\Connector\Sabre\Node;
+use OCA\DAV\Upload\UploadFile;
 use OCP\Files\Folder;
 use OCP\IUser;
 use OCP\IUserSession;
@@ -189,7 +190,7 @@
 		$this->userFolder->method('get')
 			->with('/subdir')
 			->willReturn($node);
-		
+
 		$dummyShares = array_map(function ($type) {
 			$share = $this->getMockBuilder(IShare::class)->getMock();
 			$share->expects($this->any())
@@ -282,4 +283,24 @@
 			[[\OCP\Share::SHARE_TYPE_USER, \OCP\Share::SHARE_TYPE_REMOTE]],
 		];
 	}
+
+	public function testGetPropertiesSkipChunks(): void {
+		$sabreNode = $this->getMockBuilder(UploadFile::class)
+			->disableOriginalConstructor()
+			->getMock();
+
+		$propFind = new \Sabre\DAV\PropFind(
+			'/dummyPath',
+			[self::SHARETYPES_PROPERTYNAME],
+			0
+		);
+
+		$this->plugin->handleGetProperties(
+			$propFind,
+			$sabreNode
+		);
+
+		$result = $propFind->getResultForMultiStatus();
+		$this->assertCount(1, $result[404]);
+	}
 }
```

**Review by kesselb — APPROVED** [review]
LGTM :+1:

**Comment by rullzer** [comment]
@kesselb feel free to directly push to the branch :)

**Review by georgehrke — APPROVED** [review]
Code makes sense 👍

**Comment by tobiasKaminsky** [comment]
Can we have a backport of this?
It is fixed in latest Android version, but I am sure that not all update their mobile.
So having it fixed on both sides is more safe :-)

**Pull request merged**
