### PR TITLE
Init user's file system if not existing on ownership transfer

### PR DESCRIPTION
**Pull request by CarlSchwan**
This makes it a bit easier to transfer ownership when the new user
hasn't already logged in. This still doesn't support encrypted storage because the keys are not generated yet (this is already checked at the beginning of the method).

### CODE REVIEW

**Comment by PVince81** [comment]
with "still doesn't support storage" do you mean encrypted storage ?

**Comment by CarlSchwan** [comment]
> with "still doesn't support storage" do you mean encrypted storage ?

yes

**Review by PVince81 — APPROVED** [review]
:+1: as discussed

**Review by come-nc — APPROVED** [review]

**Pull request merged**
