### PR TITLE
Install Select2 via npm

### PR DESCRIPTION
**Pull request by ChristophWurst**
For https://github.com/nextcloud/server/pull/16956#issuecomment-527175378

There was something about Select2 that made me install via git at https://github.com/nextcloud/server/pull/13156, but I can't remember what version at that time cause the problems.

@nextcloud/javascript where do we even use it? Couldn't find a single usage in server :)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
I think it is used by other apps ^^'

**Comment by ChristophWurst** [comment]
Yeah. Would be pretty awesome if we tested at least with one app :)

**Review by GretaD — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]
Tagging and the workflow app still use it :wink: Just tested and it seems to be working as before.

**Comment by skjnldsv** [comment]
> Tagging and the workflow app still use it  Just tested and it seems to be working as before.

I'll see what I can do about tagging for 18

**Pull request merged**
