### PR TITLE
l10n: HTTP in capital letters

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by szaimen — CHANGES_REQUESTED** [review]
NC19-15 are EOL

**Comment by Valdnet** [comment]
> NC19-16 are EOL

@szaimen Thanks for the information. So a change only in version 20 😉.

**Review by szaimen — APPROVED** [review]
The l10n issue seems to be already fixed in stable21 and above

**Review by rakekniven — APPROVED** [review]

**Pull request merged**
