### PR TITLE
Use correct filter for app icons in the right sidebar of app management 

### PR DESCRIPTION
**Pull request by nickvergessen**
Before | After
---|---
Bildschirmfoto vom 2022-11-24 09-28-02 | Bildschirmfoto vom 2022-11-24 09-28-02
Bildschirmfoto vom 2022-11-24 09-28-19 | Bildschirmfoto vom 2022-11-24 09-28-35

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
/backport 822c10d61c5a55816399e382f81a1d97cbc3b3d0 to stable25

**Review by artonge — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
seems to work

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
conflicts...

**Comment by nickvergessen** [comment]
/backport 3e3eaa42820fed3d49470cee2406ad72c5ec6d3d to stable25

**Pull request merged**
