### PR TITLE
Do not allow OPTIONS request against / from Windows Explorer

### LINKED ISSUE #2979: HTTPS-WebDAV mount on Windows failes if NC is installed to webserver-root
### Steps to reproduce
1. Install Nextcloud to the webroot on the webserver
2. Try to mount a webdav folder from nextcloud

### Expected behaviour
The webdav folder should be mounted.

### Actual behaviour
Error 0x80070043 “The network name cannot be found.” occurs

### Server configuration
**Operating system**: CentOS 7
**Web server:** Apache 2.4
**Database:** MySQL
**PHP version:** 5.4
**Nextcloud version:** 10.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** OC8.2 -> NC 9.0 -> NC 10.0.1
**Where did you install Nextcloud from:** tar from website
**Signing status:** No errors have been found.

### Client configuration
**Operating system:**
Windows 8.1 / Windows 10

### Additional Informations
For ownCloud the problem is discussed here:
https://github.com/owncloud/core/issues/26350
And here are the workarounds documented:
https://doc.owncloud.org/server/latest/admin_manual/issues/general_troubleshooting.html#troubleshooting-webdav
https://doc.owncloud.org/server/latest/user_manual/files/access_webdav.html?highlight=webdav#known-problems

Maybe Windows is not the only client that works this way:
https://www.ibm.com/support/knowledgecenter/SSHRKX_8.0.0/admin/webdav_http_options.html

The Windows Webdav Client Sends an OPTIONS to the root of the URL.
NC redirects to the login form (/index.php/login). The client sends an OPTIONS to this URL und gets 405 Method not allowed because there is no defined route in core/routes.php.

### Possible Solution
If we add a route for / with method OPTIONS that redirects to /remote.php/webdav everything should work fine.

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #2979 

cc @michag86 

- [ ] add integration tests

### CODE REVIEW

**Comment by michag86** [comment]
### User agents used by windows webdav client:
windows 7 - webclient is not running
aaa.bbb.ccc.ddd - - [09/Jan/2017:14:27:36 +0100] "OPTIONS / HTTP/1.1" 302 309 "-" "DavClnt"
windows 7 - webclient is running
aaa.bbb.ccc.ddd - - [09/Jan/2017:14:27:43 +0100] "OPTIONS / HTTP/1.1" 302 3287 "-" "Microsoft-WebDAV-MiniRedir/6.1.7601"

windows 8.1 - webclient is not running
aaa.bbb.ccc.ddd - - [09/Jan/2017:14:09:54 +0100] "OPTIONS / HTTP/1.1" 302 4433 "-" "DavClnt"
windows 8.1 - webclient is running
aaa.bbb.ccc.ddd - - [09/Jan/2017:14:09:57 +0100] "OPTIONS / HTTP/1.1" 302 4433 "-" "Microsoft-WebDAV-MiniRedir/6.3.9600"

windows 10 - webclient is not running
aaa.bbb.ccc.ddd - - [09/Jan/2017:14:15:58 +0100] "OPTIONS / HTTP/1.1" 302 4433 "-" "DavClnt"
windows 10 - webclient is running
aaa.bbb.ccc.ddd - - [09/Jan/2017:14:16:02 +0100] "OPTIONS / HTTP/1.1" 302 4433 "-" "Microsoft-WebDAV-MiniRedir/10.0.14393"

**Because we need to get the WebClient running, it's only needed to check for agend "DavClnt".**

**Comment by MorrisJobke** [comment]
> Because we need to get the WebClient running, it's only needed to check for agend "DavClnt".

Done :)

**Comment by michag86** [comment]
Changes tested on NC 10.0.1 👍

**Comment by Flole998** [comment]
This code is violating the HTTP Code specifications. You're returning 200 on an empty result, that is discouraged in favor of using code 204. Anyways, I propose to use a redirect in htaccess as dav is an app and no app code should be included in the base installation. In htaccess also other webdav stuff is handled. See #3370

**Comment by MorrisJobke** [comment]
You are right. And it's also a major hack. Let's go for the cleaner redirect.

**Pull request closed without merging**
