### PR TITLE
22.2.9 RC1

### PR DESCRIPTION
**Pull request by blizzz**
* #31707
* #32080
* #32446
* #32458
* #32623
* #32626
* #32652
* #32678
* #32694
* #32707
* #32712
* #32727
* #32760
* #32762
* #32772
* #32788
* #32796
* #32809
* #32812
* #32815
* #32835
* #32851
* #32856
* nextcloud/3rdparty#1044
* nextcloud/3rdparty#1078
* nextcloud/3rdparty#965
* nextcloud/activity#818
* nextcloud/notifications#1213
* nextcloud/text#2417
* nextcloud/text#2490
* nextcloud/text#2491
* nextcloud/text#2500
* nextcloud/text#2504
* nextcloud/viewer#1251

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by kesselb** [comment]
:warning: Heads up! 

AWS SDK update https://github.com/nextcloud/server/pull/29607 also updated Guzzle PSR7 to Version 2. While the server pr is not merged yet the 3rdparty pull request is and sneaked in with some other dependency update (if anyone of you know please let me know - I couldn't figure out which one).

Our version of azure-storage-common is not fully compatible yet with Guzzle PSR7 2 but an updated version is available: https://github.com/Azure/azure-storage-blob-php/releases/tag/v1.5.3

In addition `tests/lib/Http/Client/ResponseTest.php` needs a update because `stream_for` (dropped with Guzzle PSR7 2) is also gone.  

cc @CarlSchwan

**Comment by st3iny** [comment]
@kesselb @nickvergessen 

I think I found it: https://github.com/nextcloud/server/pull/32652

It pulls an update of aws-sdk accidentally: 
```
Submodule 3rdparty fd0d5d72f4..b9b7832960:
> Merge pull request #1044 from nextcloud/bump/symfony/translation-22
> Merge pull request #1005 from nextcloud/dependabot/composer/stable22/aws/aws-sdk-php-3.212.2
> Merge pull request #972 from nextcloud/backport/970/stable22                                            
```

**Comment by blizzz** [comment]
> @kesselb @nickvergessen
> 
> I think I found it: #32652
> 
> It pulls an update of aws-sdk accidentally:
> 
> ```
> Submodule 3rdparty fd0d5d72f4..b9b7832960:
> > Merge pull request #1044 from nextcloud/bump/symfony/translation-22
> > Merge pull request #1005 from nextcloud/dependabot/composer/stable22/aws/aws-sdk-php-3.212.2
> > Merge pull request #972 from nextcloud/backport/970/stable22                                            
> ```

The 3rdparty PR is https://github.com/nextcloud/3rdparty/pull/1044 which does not pull any other deps

**Comment by nickvergessen** [comment]
It's actually https://github.com/nextcloud/3rdparty/pull/1005

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/29607 never was merged in server

**Pull request merged**
