### PR TITLE
Fix first run wizzard

### PR DESCRIPTION
**Pull request by CarlSchwan**
Before:
image

After:

image

### CODE REVIEW

**Comment by artonge** [comment]
What was the issue ?

**Comment by CarlSchwan** [comment]
> What was the issue ?

I added a before screenshot, the header was missing an image

**Review by miaulalala — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
I like the smell of css inside php :smiling_face_with_tear:

**Comment by skjnldsv** [comment]
This broke other things, the fix could have been sent to the firstrunwizard only :)

```scss
.modal-header .firstrunwizard-header {
	padding: 20px 12px;
	background-size: var(--image-background-size);
	background-position: center;
	color: var(--color-primary-text);
	text-align: center;
	background-image: var(--image-background, var(--image-background-plain, url("../../../core/img/background.svg"), linear-gradient(
40deg, #0082c9 0%, #30b6ff 100%)));
	background-color: var(--color-primary);
	.logo[data-v-10738c5b] {
		background: var(--image-logo, url("../../../core/img/logo/logo.svg")) no-repeat center;
		background-size: contain;
	}
}
```

**Pull request merged**
