### PR TITLE
Bugfix/32630/get access list use correct array key

### LINKED ISSUE #32630: [Bug]: getAccessList in ShareByMailProvider uses incorrect array key
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Per documentation https://github.com/nextcloud/server/blob/master/lib/private/Share20/Manager.php#L1671 -- share by mail should use the array key "mail". Instead, it is using the array key "public", which collides with array key used in DefaultShareProvider for share by link; https://github.com/nextcloud/server/blob/master/lib/private/Share20/DefaultShareProvider.php#L1368

Change is required here;
https://github.com/nextcloud/server/blob/master/apps/sharebymail/lib/ShareByMailProvider.php#L1211

### Steps to reproduce

Not applicable

### Expected behavior

ShareByMailProvider should use "mail" as array key.

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
N/A
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ASerbinski**
* Resolves: #32630 

## Summary
Switch to correct array key in ShareByMailProvider/getAccessList -- should be 'mail' not 'public'.

### CODE REVIEW

**Comment by kesselb** [comment]
Thank you very much :+1: 

Can you have a look at the failing test:

```
1) OCA\ShareByMail\Tests\ShareByMailProviderTest::testGetAccessList
Failed asserting that an array has the key 'public'.

/home/runner/work/server/server/apps/sharebymail/tests/ShareByMailProviderTest.php:1089
```

**Comment by kesselb** [comment]
Thank you :+1: 

Please revert the changes to composer.lock

**Comment by ASerbinski** [comment]
Hi @kesselb ; that commit changing composer.lock seems to be somehow added by github, not by me. I'm not sure how to prevent it from being added.

**Comment by kesselb** [comment]
Thank you :+1: 

I read https://github.com/nextcloud/server/pull/2834 to understand `public` and `mail`. 
If I understand it correct, public is fine and the documentation is wrong. 

https://github.com/nextcloud/server/blob/f5c361cf44739058b79f322576a1bad2d8c142d9/lib/private/Share20/Manager.php#L1761-L1763

The above code will "merge" the values together. 
If something is shared by MailShareProvider or LinkShareProvider public should be true. 

I believe that's good news for your other pull request.

**Comment by ASerbinski** [comment]
Hi @kesselb ; I believe that the documentation is correct and that the PR #2834 you referenced is from a more primitive state before the 'mail' key was added.

Per @schiessle ; "... To make it more generic we could also add another key 'mail' to the array, which would probably be the better solution."

**Comment by kesselb** [comment]
> I believe that the documentation is correct and that the PR https://github.com/nextcloud/server/pull/2834 you referenced is from a more primitive state before the 'mail' key was added.

The documentation for `mail` was added with the mentioned pr.  

> To make it more generic we could also add another key 'mail' to the array, which would probably be the better solution.

I guess that was an idea, but not done. 

The takeaway for your pull request to list the mail shares for a node is to keep the current behavior (add public = true when at least one mail share exist) and add the mail attribute to the result. 

I'm unsure if we need this pr. There is nothing broken to be fixed apart from the documentation. Sorry, for asking you to create a pull request for this change.

**Comment by ASerbinski** [comment]
Hi @kesselb ; I added a commit to https://github.com/nextcloud/server/pull/32631 to comply with your directive to both preserve the prior behavior with respect to the 'public' array key, and to use the 'mail' key per proposed new usage.

**Pull request closed without merging**
