### PR TITLE
fix(settings): users settings cypress

### PR DESCRIPTION
**Pull request by skjnldsv**
Resolves regression from https://github.com/nextcloud/server/pull/43804

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]
Works, but I'd consider having custom `data-cy` attributes a flag of issue with semantics.

**Comment by Pytal** [comment]
/backport b5b658c0d024b708690d89bb1f14b13858b4d059 to stable28

**Pull request merged**
