### PR TITLE
Only allow removing existing shares that would not be allowed due to reshare restrictions

### PR DESCRIPTION
**Pull request by juliusknorr**
Steps to reproduce:
- User A creates a file "LinkShare.txt" and shares it by link
- User B shares a folder "WithoutReshare/" without reshare permissions to User A
- User A moves a file "LinkShare.txt" into the incoming share "WithoutReshare/"

The share link still exists in the user interface though it is no longer accessible due to the missing reshare permissions on the parent share.

This PR makes sure that the UI doesn't offer to modify the link share and only remove it which is still possible.

However I'm still wondering if we should either indicate that this share is stale in the UI or even remove the share link if the node is moved to a share without reshare permissions, but not sure if dropping those shares automatically would be something feasible.

### CODE REVIEW

**Comment by juliushaertl** [comment]
I've pushed two more commits to get the discussion for my proposal some example here to
- remove shares when they are moved into a directory where the share owner hasn't allowed resharing
- downgrade permissions when the owner is changed to not end up with link shares that have higher permissions than the parent share. Even though this might be checked, it feels safer to have the proper permissions set then in the child share as well. Also the share update was failing in that case with the following exception:


```

**Comment by juliushaertl** [comment]
@rullzer Maybe you can share your opinion on this :)

**Comment by skjnldsv** [comment]
Is it still "to review" ?
Or still developing?

**Comment by juliushaertl** [comment]
Would be ready for review, though after my rebase today i guess i need to have another look at the one failing acceptance test which seems related, which would cover exactly that case where now a share would be cleaned up:

```
Scenario: sharee can unshare a reshare by link if resharing is disabled in the settings after the reshare is created # /drone/src/tests/acceptance/features/app-files-sharing-link.feature:195
```

**Review by artonge — APPROVED** [review]
I probably don't have the full picture, but the code looks fine :).

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
do we need backports?

**Pull request merged**
