### PR TITLE
Cache images on browser

### LINKED ISSUE #26851: Missing cache control for (some) static resources
Is there any reason why extensions like `jpg` or `png` are not included here?
https://github.com/nextcloud/server/blob/5cccbbdd453c742ba13b3a0fd01aba406389411f/.htaccess#L41-L44

### PR DESCRIPTION
**Pull request by solracsf**
Fix #26851

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Review by szaimen — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Also needs an update on the nginx docs then:
https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx-root.conf.sample#L135-L139

**Comment by acsfer** [comment]
Done at https://github.com/nextcloud/documentation/pull/6953

**Pull request merged**
