### PR TITLE
Don't update packages in build/package-lock.json when running js-tests

### PR DESCRIPTION
**Pull request by nickvergessen**
I find it quite distrubing to always end up with a modified `build/package-lock.json` file after running autotest-js.sh
Updating should be done explicitly (or automatically with dependabot) and then be commited like that to the repo, not running locally when you run tests

### CODE REVIEW

**Comment by juliushaertl** [comment]
Makes sense though we should also commit that properly then in the first run https://github.com/nextcloud/server/blob/master/build/package-lock.json and remove it from .gitignore

**Comment by nickvergessen** [comment]
> Makes sense though we should also commit that properly then in the first run https://github.com/nextcloud/server/blob/master/build/package-lock.json and remove it from .gitignore

Done, please review

**Review by marcoambrosini — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by nickvergessen** [comment]
Are failing JS tests related? Works locally

**Review by skjnldsv — COMMENTED** [review]
jsunit fails ?

**Comment by nickvergessen** [comment]
So anyone from @nextcloud/server-frontend wants to pick this up? Otherwise I would close it any we still have the updates happening

**Comment by artonge** [comment]
The .gitignore part should be nice to have though

**Pull request closed without merging**
