### PR TITLE
Master is now 31

### PR DESCRIPTION
**Pull request by nickvergessen**
# ⚠️ To be merged only

- [x] After stable30 creation
- [x] By release manager: @skjnldsv

## Todos

possible "up front"

- [x] https://github.com/nextcloud/docker-ci/pull/650
- [x] https://github.com/nextcloud/.github/pull/418

---

"live"

- [x] `.github/dependabot.yml`
  - [x] Add a new section about the new `stableY` branch
- [x] `.github/workflows/update-cacert-bundle.yml`
  - [x] Adjust backport list of cacert automation to include `stableY`
- [x] `.github/workflows/update-code-signing-crl.yml`
  - [x] Adjust backport list of cacert automation to include `stableY`
- [x] `.github/workflows/update-psalm-baseline.yml`
  - [x] Adjust backport list of psalm automation to include `stableY`
- [x] `.github/workflows/npm-audit-fix.yml`
  - [x] Adjust backport list of psalm automation to include `stableY`
- [x] `apps/settings/lib/WellKnown/SecurityTxtHandler.php`
  - [x] Bump `Expires` date to be 5 months in the future
  - [x] Trigger the backport bot for all still supported versions
- [x] `version.php`
  - [x] Increase the major version in `$OC_Version` and 0-ify the other digits
  - [x] Set `$OC_VersionString` to `Major.0.0 dev`
  - [x] Add the newest major to `$OC_VersionCanBeUpgradedFrom`
  - [x] Remove the oldest major to `$OC_VersionCanBeUpgradedFrom`
- [x] `apps/*/appinfo/info.xml`
  - [x] Update Minor version of all apps and 0ify the patch version
  - [x] Bump version requirement to the new Major
- [x] Rebuilt frontend `npm ci && npm run build`
- [x] Add stable30 to 3rdparty dependabot master
    - [x] https://github.com/nextcloud/3rdparty/pull/1914
    - [ ] Update version in 3rdparty/composer.json (dev-master => dev->stable30)
    - [x] Commit 3rdparty/ with the merge commit of above PR
- [x] Fix other apps on stable branch:
    - [x] Create stable branch in https://github.com/nextcloud-deps/ocp
    - [x] Add stable branch to cron: https://github.com/nextcloud-deps/ocp/pull/24
    - [x] Adjust version alias on stable30 https://github.com/nextcloud-deps/ocp/pull/25
    - [x] Run the cron (only after stable30 of server was branched off for real)
- [x] Branch-off the stable30 branch in all affected apps, before sending this PR
    - [x] https://github.com/nextcloud/server/pull/47235
- [ ] https://github.com/nextcloud/server/commit/e7bcc7535bc2573a051434467b36c20d3a1c50f7

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Needs more reviewers

**Review by skjnldsv — APPROVED** [review]

**Review by mejo- — APPROVED** [review]

**Review by marcelklehr — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]
🚀

**Review by st3iny — APPROVED** [review]

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/tree/stable30 created

**Comment by nickvergessen** [comment]
/backport 04944aaa23d7f986ad62d8710b4f4d02fab224bc to stable30

**Comment by nickvergessen** [comment]
/backport 04944aaa23d7f986ad62d8710b4f4d02fab224bc to stable29

**Comment by nickvergessen** [comment]
/backport 04944aaa23d7f986ad62d8710b4f4d02fab224bc to stable28

**Pull request merged**
