### PR TITLE
Fix ObjectStoreStorage#file_put_contents

### PR DESCRIPTION
**Pull request by marcelklehr**
This is the same as #16397 but with a signed off commit.

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks again :+1: 

https://github.com/nextcloud/server/blob/06a119242e9e26a0076adc1558c8a3009a1c6b1f/lib/private/Files/ObjectStore/ObjectStoreStorage.php#L295-L303

Make sense somehow. A resource created by `$this->fopen($path, 'w+');` uses a temporary file the `LazyOpenStream` can reuse later. Sounds hacky :hankey: (not your code - the fact that we write all the data into a temp file and delete it later. there is a way to pass the raw data to s3 uploader but we don't expose this feature from the sdk to the `IObjectStore` interface).

**Comment by korelstar** [comment]
@MorrisJobke
Please backport this to Nextcloud 15 and 16, too.

**Comment by rullzer** [comment]
It looks sane indeed.
But there are a lot of failing tests.

**Comment by marcelklehr** [comment]
Superseded by https://github.com/nextcloud/server/pull/16440 (finally from my own fork, so I can force-push)

**Pull request closed without merging**
