### PR TITLE
Settings design polishing

### PR DESCRIPTION
**Pull request by juliusknorr**
From https://github.com/nextcloud/server/issues/10094

- [x] User management: Table headers should be lighter font color than the rest of the text
- [x] External storages: Could use a settings-hint text like "You can mount different storage services as folders into your Nextcloud." Global credentials also needs explanation
- [x] External storages: Settings menu should use 3-dot-icon, and delete action should go in there too (as last entry)
- [x] Personal info: Vertical whitespace is a bit much. If it's cause of the region format, put time and date on one row.
- [x] Merge Server-side encryption into "Security" section?
- [x] Groupware: "Calendar settings" instead of "CalDAV server", and more whitespace between settings.
- [x] Workflow: Create a new tag input field should also create the tag on pressing enter

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
:+1:

**Review by rullzer — APPROVED** [review]

**Review by rullzer — DISMISSED** [review]
Unit tests fail

**Comment by juliushaertl** [comment]
@rullzer Unit tests fixed.

**Comment by skjnldsv** [comment]
LGTM! :motor_boat:

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
@juliushaertl are you sure: https://drone.nextcloud.com/nextcloud/server/9390/251

**Comment by juliushaertl** [comment]
@rullzer Sorry, missed that when scrolling though the drone report, I've just recognized the files-acceptance failure. :see_no_evil: will fix

**Pull request merged**
