### PR TITLE
Use proper casing

### PR DESCRIPTION
**Pull request by LukasReschke**
The unit tests are failing locally for me and working on Drone, looking at the code: This seems to me like Drone isn't executing all tests 😱 

My bet is that it's caused because the casing of said folders got renamed and because I work on OS X it doesn't matter, but it does on Linux…

### CODE REVIEW

**Comment by LukasReschke** [comment]
:bomb: :bomb: :bomb:

**Comment by LukasReschke** [comment]
cc @rullzer @nickvergessen 😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱  😱 😱 😱

**Comment by LukasReschke** [comment]
Tests run through, please review @nickvergessen @rullzer @schiessle @karlitschek 

I'll prepare a backport to stable10. On stable9 the casing hasn't been changed and thus the unit tests run through…

**Comment by LukasReschke** [comment]
Backport at https://github.com/nextcloud/server/pull/884, let's see what fails on stable10…

**Comment by karlitschek** [comment]
prefect. please backport 👍

**Comment by LukasReschke** [comment]
```
Time: 6.38 minutes, Memory: 258.75Mb

There were 3 failures:

1) Tests\Core\Controller\AvatarControllerTest::testPostAvatarFile
Array (...) does not match expected type "string".

/drone/src/github.com/nextcloud/server/tests/Core/Controller/AvatarControllerTest.php:265

2) Tests\Core\Controller\AvatarControllerTest::testPostAvatarFileGif
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Unknown filetype'
+'Invalid file provided'

/drone/src/github.com/nextcloud/server/tests/Core/Controller/AvatarControllerTest.php:302

3) Tests\Core\Controller\AvatarControllerTest::testFileTooBig
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'File is too big'
+'Invalid file provided'

/drone/src/github.com/nextcloud/server/tests/Core/Controller/AvatarControllerTest.php:433
```

And some more test fails, cc @rullzer.

**Comment by rullzer** [comment]
Passes!

:+1: for the commits from @LukasReschke

**Comment by LukasReschke** [comment]
👍 for the stuff from @rullzer

**Pull request merged**
