### PR TITLE
Installation details for README

### PR DESCRIPTION
**Pull request by aroseartist**
Per issue: https://github.com/nextcloud/server/issues/16
Added installation link guides per the already established documentation rather than attempting to re-create the documentation here.

### CODE REVIEW

**Comment by LukasReschke** [comment]
Thanks for your contribution, @aroseartist. Much appreciated 🚀 ⭐ 🎉 

Normally, we'd require you to add a "Signed-Off-By" to your commit. But since this only covers the README this should be ok without :)

LGTM 👍

**Comment by LukasReschke** [comment]
Oh, and you may also want to join us in #freenode-dev on IRCCloud in case you want to work on more contributions. We're happy to help :)

**Review by LukasReschke — APPROVED** [review]

**Comment by ChristophWurst** [comment]
@LukasReschke I guess you meant #nextcloud-dev 😉

**Comment by jancborchardt** [comment]
@aroseartist thanks a lot for helping make the installation process simpler to understand! :) I also added you to the Nextcloud organization now.

**Pull request merged**
