### PR TITLE
[stable29] fix: Update Nextcloud libraries

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: Ticket#9662534

## Summary

* Update `@nextcloud/dialogs` to 5.3.5
* Update `@nextcloud/capabilities` to 1.2.0
* Update `@nextcloud/sharing` to 0.2.0

`@vueuse/*` is updated to reduce duplicated dependencies as the newer libraries need newer vueuse versions, but it is compatible so nothing breaking.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by SystemKeeper — APPROVED** [review]
Seems to work fine, thanks!

**Review by nfebe — APPROVED** [review]

**Pull request merged**
