### PR TITLE
Makes the notifications area width equal to the contents

### LINKED ISSUE #10705: The notification container partially overlapping the header bar actions
### Steps to reproduce
1. Have a notification not taking the entire width
2. Try to click the (the top half) search action or your avatar in the header

### Expected behaviour
The actions should work.

### Actual behaviour
Can't click the actions.

### Server configuration
**Nextcloud version:** 14 beta

The notification container takes the entire width. It should only take the width it needs.

image

### PR DESCRIPTION
**Pull request by weeman1337**
closes #10705

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]
Nice. Works like a charm. :+1:

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Shouldn't it uses the standard of the .menu behaviour?
I cannot test right now. @juliushaertl ?

**Comment by skjnldsv** [comment]
@juliushaertl this or touches the notification area in the header right?
If so we should make sure to use the mobile menu header standard we use for the other menus, right?

**Comment by juliushaertl** [comment]
@skjnldsv Not sure about adding them to the notifications area, since those are rather temporary notifications, but yes, we should improve the rendering for that. There already was an issue about that but I cannot find it right now. However I'd still just get this into 14 and improve the general rendering later.

**Comment by weeman1337** [comment]
@skjnldsv this just changes, that the notifications take the full width (see issue #10705). It doesn't change any behavior or rendering.

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
@weeman1337 sorry, I was reading on my mobile, I mistaken the code for something else :)

**Pull request merged**
