### PR TITLE
Don't save translated predefined user status as custom status

### PR DESCRIPTION
**Pull request by nickvergessen**
- Regression from https://github.com/nextcloud/server/pull/43248

## Summary

Couple of times I saw "predefined" user statuses like "Out sick" and "Vacationing" flying by in what I assumed is the user's language and not mine. Turns out that happens when you select a predefined status and then change the "Clear at".

Can be confirmed by doing the following steps:
1. Select a predefined status
2. Optionally: Reload the page
3. Open status dialog again and change the "Clear at"
4. Check database state

### Before
grafik

### After
grafik

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
/backport 50c48aa538b20213f112d74e11e9f340ee662e8a to stable30

**Comment by nickvergessen** [comment]
/backport 50c48aa538b20213f112d74e11e9f340ee662e8a to stable29

**Comment by nickvergessen** [comment]
/backport 50c48aa538b20213f112d74e11e9f340ee662e8a to stable28

**Review by Antreesy — APPROVED** [review]
Tested

**Review by Pytal — APPROVED** [review]

**Pull request merged**
