### PR TITLE
Improve upload progress visualization

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/pull/30147 

I extended the origin PR as follows:
* Fixed initial value of `smooth*` (check for undefined)
* Only show the remaining time if the buffer is fully filled to prevent inconsistent forecasts
* Show number of finished and total uploads, this is required if you upload many files. Otherwise you might not see any progress.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Tested and seems to work in general, there might be some edge cases though that do not work perfect but that has possibly already been there before. Also didnt review the code

**Review by skjnldsv — DISMISSED** [review]
Let's wait for https://github.com/nextcloud/server/pull/39808 please

**Review by AndyScherzinger — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Shall this be done for https://github.com/nextcloud-libraries/nextcloud-upload too?

**Comment by susnux** [comment]
> Shall this be done for https://github.com/nextcloud-libraries/nextcloud-upload too?

If it is relevant for the library then yes

**Comment by skjnldsv** [comment]
> If it is relevant for the library then yes

We're using a dedicated library that calculates remaining time and such :thinking: :shrug:

**Comment by susnux** [comment]
Cypress seems unrelated

**Pull request merged**
