### PR TITLE
Files : Left panel dropdown improvement for NC 25

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
* Resolves:  #38155

(from @Clementine46)

**/!\ Testing is welcome in order to make sure it's not doing side effects elsewhere in the UI.**

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by szaimen** [comment]
Hi @Jerome-Herbinet do you have a before - after screenshot?

**Comment by Jerome-Herbinet** [comment]
I noticed that things have change in Nextcloud 26 in comparison with Nextcloud 25. So I did an equivalent PR for Nextcloud 26 in /nextcloud/nextcloud-vue which is https://github.com/nextcloud/nextcloud-vue/pull/4103

**Comment by szaimen** [comment]
@Jerome-Herbinet I think this PR should target the stable25 branch then instead of master, no?

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet I think this PR should target the stable25 branch then instead of master, no?

Yes you are right. I'll look how to do it ; is it possible to target another branch without doing a new PR ?

**Comment by szaimen** [comment]
> Yes you are right. I'll look how to do it ; is it possible to target another branch without doing a new PR ?

You can use the cherry-pick feature of git for this

**Comment by Jerome-Herbinet** [comment]
> > Yes you are right. I'll look how to do it ; is it possible to target another branch without doing a new PR ?
> 
> You can use the cherry-pick feature of git for this

Impossible, I got this : 

Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 8 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 29.94 KiB | 696.00 KiB/s, done.
Total 9 (delta 5), reused 3 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.        
remote: error: GH006: Protected branch update failed for refs/heads/stable25.        
remote: error: At least 2 approving reviews are required by reviewers with write access. 13 of 13 required status checks are expected.        
To https://github.com/nextcloud/server.git
 ! [remote rejected]         stable25 -> stable25 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/nextcloud/server.git'

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Nice tackling this @Jerome-Herbinet! Design feedback:
- [ ] Shouldn't this use an actual action button component on the right if the entry, also for accessibility?
- [ ] The arrow pointing to the right by default looks a bit strange. By default it should point down to indicate a dropdown. When opened, it can point up (or still pointing down is also fine).

**Review by szaimen — CHANGES_REQUESTED** [review]
Also blocking since this needs to target thr stable25 branch

**Comment by Jerome-Herbinet** [comment]
I close this PR and have created a new one on stable25 branch #38338
@juliushaertl @jancborchardt

**Pull request closed without merging**
