### PR TITLE
Replacing startpage.com

### PR DESCRIPTION
**Pull request by Milokita**
Replacing startpage.com with mozilla.org so that China user can use it

### CODE REVIEW

**Comment by danielkesselberg** [comment]
Thank you for your contribution :tada: 

Is www.nextcloud.com not working for you? If the connection to at least one page from $sites is possible nextcloud assumes a working internet connection.

**Comment by Milokita** [comment]
www.nextcloud.com now is unstable in China

**Comment by ChristophWurst** [comment]
> Is [www.nextcloud.com](http://www.nextcloud.com) not working for you?

I think @jospoortvliet knows more about this.

**Comment by JonasT** [comment]
Might be a silly question, but why not add `mozilla.org` instead of replacing an entry?

**Comment by MorrisJobke** [comment]
Fixed by #12571

**Pull request closed without merging**
