### PR TITLE
l10n: Spelling unification in Transifex.

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
Looks like CI needs some string fixes

**Comment by Pytal** [comment]
CI needs some string changes

**Comment by artonge** [comment]
Unit tests fixed, and CI error unrelated, merging

**Comment by Valdnet** [comment]
Thanks a lot 👍.

**Pull request merged**
