### PR TITLE
Update federation and update notification icon

### PR DESCRIPTION
**Pull request by MorrisJobke**
- cc @nextcloud/designers @nickvergessen @LukasReschke 
- fixes part of #856

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I also added the update icon (the simple bell) as commented by @jancborchardt

**Comment by LukasReschke** [comment]
LGTM

**Comment by rullzer** [comment]
:+1:

**Comment by nickvergessen** [comment]
Btw contacts and calendar have micro images :see_no_evil:

**Comment by MorrisJobke** [comment]
> Btw contacts and calendar have micro images 🙈

Pull latest master ;) I fixed this 2 days ago :P

**Comment by mar1u5** [comment]
> Pull latest master ;) I fixed this 2 days ago :P

We should release new versions of contacts and calendar before the release of Nextcloud 10 😉 
Then we could also promote **Public Calendar Sharing** etc. 😜 @georgehrke @Henni

**Pull request merged**
