### PR TITLE
Add illustrator icon

### LINKED ISSUE #24861: Add a thumbnail for adobe illustrator files
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I would like to recognize adobe illustrator files based on the thumbnail.

**Describe the solution you'd like**
I would like to commit an icon for illustrator files.

**Describe alternatives you've considered**
How can I commit it?

**Additional context**
Here is the icon that I've made. Does it fit the overall thumbnail style? Or do I need to change something?
image

Here is the code:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   width="16"
   height="16"
   version="1.1"
   viewBox="0 0 16 16"
   id="svg12">
  <metadata
     id="metadata18">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs
     id="defs16" />
  <path
     d="m2.5 1c-0.28 0-0.5 0.22-0.5 0.5v13c0 0.28 0.22 0.5 0.5 0.5h11c0.28 0 0.5-0.22 0.5-0.5v-10.5l-3-3z"
     fill="#dc5047"
     id="path2"
     style="fill:#ff7802;fill-opacity:1" />
  <text
     xml:space="preserve"
     style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:5.33333px;line-height:1.25;font-family:Arial;-inkscape-font-specification:'Arial Bold';"
     x="3.9401362"
     y="8.5551023"
     id="text849"><tspan
       id="tspan847"
       x="3.9401362"
       y="8.5551023" /></text>
  <text
     xml:space="preserve"
     style="font-size:7.00022px;line-height:1.25;font-family:Arial;-inkscape-font-specification:Arial;stroke-width:2.62508"
     x="4.9511542"
     y="10.245911"
     id="text857"><tspan
       id="tspan855"
       x="4.9511542"
       y="10.245911"
       style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:condensed;font-family:Arial;-inkscape-font-specification:'Arial Bold Condensed';fill:#ffffff;fill-opacity:1;stroke-width:2.62508">Ai</tspan></text>
</svg>
```

### PR DESCRIPTION
**Pull request by szaimen**
Close #24861

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=enh/noid/add-illustrator-icon \
-e PDFVIEWER_BRANCH=master \
-e VIEWER_BRANCH=master \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.130 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks Carl but I need help fixing the following test first:

Do you have any idea how to do that?

**Comment by szaimen** [comment]
I've got an answer from Julius:
```
php occ integrity:sign-core --privateKey=./tests/data/integritycheck/core.key --certificate=./tests/data/integritycheck/core.crt --path=./tests/data/integritycheck/mimetypeListModified
```

**Comment by szaimen** [comment]
Maay help here: https://github.com/nextcloud/server/issues/3248

**Comment by skjnldsv** [comment]
Iirc this has been suggested before and we have no permission to distribute this copyrighted icon

Same for https://github.com/nextcloud/server/pull/29643

**Pull request closed without merging**
