### PR TITLE
Fix file public link permissions if public upload is not enabled

### PR DESCRIPTION
**Pull request by julien-nc**
When "Administration -> Share -> Public upload" admin setting is disabled:
* We refuse to
    * create a share with update permissions
    * add update permissions to an existing share
* We remove PERMISSION_CREATE and PERMISSION_UPDATE when getting the share permissions

It makes perfect sense when sharing a directory but not when sharing a file which can then only be accessed in read-only by Text, NC Office and OnlyOffice.

If this is the intended behaviour, we should at least make it very explicit in the admin settings.

### CODE REVIEW

**Comment by blizzz** [comment]
milestone was wrong, master is 25.

**Review by artonge — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by artonge** [comment]
> 1) Test\Share20\ManagerTest::testLinkCreateChecksNoPublicUpload
> Failed asserting that exception message '' contains 'Public upload is not allowed'.

**Comment by eneiluj** [comment]
> PHPUnit failure:
> 
> > 1. Test\Share20\ManagerTest::testLinkCreateChecksNoPublicUpload
> >    Failed asserting that exception message '' contains 'Public upload is not allowed'.

@artonge I duplicated this test to check this works with files and fails with folders.
I also fixed the 3 other failing tests for which the share was just missing a target user and a Node.

**Comment by juliushaertl** [comment]
Failure unrelated

**Pull request merged**
