### PR TITLE
Make sure MySQL is not saying 'this' = 'this ' is true

### PR DESCRIPTION
**Pull request by nickvergessen**
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿
🍿🍿🍿🍿🍿🍿🍿🍿🍿🍿

100 popcorn, take one and have a look while I perform a magic trick:

```
SELECT 'jan' = 'jan ', BINARY 'jan' = 'jan ';
+----------------+-----------------------+
| 'jan' = 'jan ' | BINARY 'jan' = 'jan ' |
+----------------+-----------------------+
|              1 |                     0 |
+----------------+-----------------------+
```

### CODE REVIEW

**Comment by gary-kim** [comment]
Tried testing and to add to the amusement, 
#### MySQL 5.7
```
mysql> SELECT 'jan' = 'jan ', BINARY 'jan' = 'jan ';
+----------------+-----------------------+
| 'jan' = 'jan ' | BINARY 'jan' = 'jan ' |
+----------------+-----------------------+
|              1 |                     0 |
+----------------+-----------------------+
1 row in set (0.00 sec)
```

#### MySQL 8
```
mysql> SELECT 'jan' = 'jan ', BINARY 'jan' = 'jan ';
+----------------+-----------------------+
| 'jan' = 'jan ' | BINARY 'jan' = 'jan ' |
+----------------+-----------------------+
|              0 |                     0 |
+----------------+-----------------------+
1 row in set (0.00 sec)
```

**Comment by nickvergessen** [comment]
Okay, so they fixed it for mysql8 on your machine? Im pretty sure I have 8 too locally and I could reproduce it there

**Comment by gary-kim** [comment]
I just tested on `mysql:8` on Docker Hub, `8.0.19-0ubuntu0.19.10.3` on Ubuntu, and `8.0.17 Source distribution` on RHEL 8 and they all seem to return the proper value.

**Comment by nickvergessen** [comment]
Okay, seems to be the case for me now too.

MariaDB seems to be affected:
```sql
MariaDB [(none)]> SELECT 'jan' = 'jan ', BINARY 'jan' = 'jan ';
+----------------+-----------------------+
| 'jan' = 'jan ' | BINARY 'jan' = 'jan ' |
+----------------+-----------------------+
|              1 |                     0 |
+----------------+-----------------------+
1 row in set (0.00 sec)

MariaDB [(none)]> SELECT VERSION();
+----------------------------------+
| VERSION()                        |
+----------------------------------+
| 10.1.44-MariaDB-0ubuntu0.18.04.1 |
+----------------------------------+
1 row in set (0.00 sec)
```

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by MorrisJobke** [comment]
Conflicts :/

**Comment by MorrisJobke** [comment]
> Conflicts :/

Let me fix them.

**Comment by rullzer** [comment]
Basically this made my production instance do boom... I'll have to see why... but for now we can't really release beta3 with this...

**Pull request merged**
