### PR TITLE
do not use deprecated API for LDAP paged results

### LINKED ISSUE #19127: ldap_control_paged_result() is deprecated spam
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Enable user_ldap authentication
2. See the log

### Expected behaviour
LDAP works

### Actual behaviour
LDAP works but it spams hundreds of such error messages.

`[PHP] Error: Function ldap_control_paged_result() is deprecated at /usr/share/webapps/nextcloud/apps/user_ldap/lib/LDAP.php#310`

### Server configuration

**PHP version:**
7.4.1

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

### PR DESCRIPTION
**Pull request by blizzz**
fixes #19127

Adds an adapter to serve old an new API. Lifted the Access class of the paged results state handling and left it all to the adapters. 

* [x] adjust ldap_read, if applicable
* [x] clean up cookie handling bits in Access.php
* [x] find a way for offset handling with multiple bases 
  * [x] seems to work already, figure out why :) – fixed it a long time ago on a higher level :)
* [x] adapt unit tests
* [x] fix whatever makes old API integration tests fail
* [x] polish adapter interface 
* [x] stash the commits

### CODE REVIEW

**Comment by blizzz** [comment]
```
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"jsunit","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"checkers","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"litmus","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"caldavtester-new-endpoint","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"caldavtester-old-endpoint","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"carddavtester-new-endpoint","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"carddavtester-old-endpoint","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"samba","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"sqlite-php7.3-webdav-apache","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"nodb","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"sqlite","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mariadb10.1-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mariadb10.2-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mariadb10.3-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mariadb10.4-php7.3","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mysql8.0-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mysql5.7-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mysql5.7-php7.3","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mysql5.6-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"postgres9-php7.3","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"postgres10-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"postgres11-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mysqlmb4-php7.2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"mysqlmb4-php7.3","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-capabilities_features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-federation_features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-auth","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-maintenance-mode","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-ratelimiting","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-carddav","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-dav-v2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-ocs-v1","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-checksums-v1","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-external-storage","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-provisioning-v1","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-tags","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-caldav","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-comments","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-comments-search","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-favorites","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-provisioning-v2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-webdav-related","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-sharees-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-sharees-v2-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-sharing-v1","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-sharing-v1-part2","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-sharing-v1-part3","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-setup-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-filesdrop-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-transfer-ownership-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-ldap-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-ldap-openldap-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-ldap-openldap-uid-features-old-ldap-api","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-ldap-openldap-uid-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-ldap-openldap-numerical-id-features","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-trashbin","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-remote-api","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"integration-download","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-access-levels","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-app-comments","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-app-files","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-app-files-sharing","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-app-files-sharing-link","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-app-files-tags","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-app-theming","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-header","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-login","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-users","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"acceptance-apps","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"nodb-codecov","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"db-codecov","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"object-store-s3","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"object-store-azure","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"memcache-memcached","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
Mar 19 16:54:32 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","event":"push","level":"info","msg":"trigger: skipping build, no matching pipelines","pipeline":"memcache-memcached","ref":"refs/heads/fix/19127/deprecated-ldap_control_paged_result_1","repo":"nextcloud/server","time":"2020-03-19T15:54:32Z"}
```

:man_shrugging:

**Comment by blizzz** [comment]
^ apparently this is normal as it goes against the feature branch, not master. still missing my build

**Comment by blizzz** [comment]
```
Mar 19 16:55:02 drone drone[1134]: {"commit":"5ac3ce0307af303f7b3ab0fbcc7777cea2d28301","error":"Error 1406: Data too long for column 'stage_name' at row 1","event":"pull_request","level":"error","msg":"trigger: cannot create build","pipeline":"db-codecov","ref":"refs/pull/20037/head","repo":"nextcloud/server","time":"2020-03-19T15:55:02Z"}
```

:tada:

**Review by rullzer — APPROVED** [review]
:elephant:

**Comment by blizzz** [comment]
another review? I'd rather have it in earlier than later.

**Review by nickvergessen — APPROVED** [review]
:elephant:

**Pull request merged**
