### PR TITLE
Revert the 'broken' public page changes

### LINKED ISSUE #31017: [Bug]: mb file calculation error
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

as you can see in the attached file circled in red, during a file sharing URL, the download item bears an incorrect wording of the weight in mb of the file itself

Screenshot_20220204-231144_Chrome

### Steps to reproduce

1. Open share link
2. Click menù 
3. View description mb file

### Expected behavior

Up

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

_No response_

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Up
```

### List of activated Apps

```shell
Up
```

### Nextcloud Signing status

```shell
Up
```

### Nextcloud Logs

```shell
Up
```

### Additional info

_No response_

### LINKED ISSUE #31040: [Bug]: File drop (Upload Only) styling issue starting from version 23
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to the new version (23) Hub II, I've seen this issue and I was thinking that this is only my instance so I've freshly started a new demo instance to test if that a public problem or just me and here is the results

### Steps to reproduce

docker-compose Deployment

### Expected behavior

with the nextcloud:apache tag for the image which installs the 23.0.1 image I got this.
Screenshot 2022-02-07 090622

And then I started another fresh instance with the tag nextcloud:22-apache and I got this and it was correct.
Screenshot 2022-02-07 091023

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

_No response_

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
only the default installation
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #31076: [Bug]: Public link page broken
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Tried on c.cn.com (version 23.0.1.2), when sharing a folder as public link the page for the visitor is broken

### Steps to reproduce

1. share a folder as public link, read only
2. open the public link

What I see in list view (huge empty space at the top):

grafik

What I see in grid view (tiny grid view and huge empty space around it):

grafik

### Expected behavior

Nice looking file view without all the empty space

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
-
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by CarlSchwan**
Reverts https://github.com/nextcloud/server/pull/30655 and https://github.com/nextcloud/server/pull/30719 
Fix #31076
Fix https://github.com/nextcloud/server/issues/31040
Fix https://github.com/nextcloud/server/issues/31017

Let's revert it for now and see if we can later rework that in a better way. ~~This keeps the change about the fileSize variable containing a nonbreaking space but reverts all the CSS changes~~ This reverts all changes.

### CODE REVIEW

**Comment by szaimen** [comment]
Carl maybe we should also think about reverting the hidden space change because it might introduce this?
https://github.com/nextcloud/server/issues/31017

**Comment by acsfer** [comment]
Related to https://github.com/nextcloud/server/issues/31040?

**Comment by szaimen** [comment]
@CarlSchwan I've also reverted "Add non-breaking space in the file size" because of https://github.com/nextcloud/server/issues/31017. I hope thats fine!

**Review by szaimen — APPROVED** [review]
tested and works 👍
(it fixes all mentioned issues)

**Comment by acsfer** [comment]
This should be pushed to the Hotfix to come as a regression IMO.

**Comment by szaimen** [comment]
> This should be pushed to the Hotfix to come as a regression IMO.

@PVince81 on that

**Review by max-nextcloud — APPROVED** [review]
I ran the text app cypress tests for sharing against this branch of the server and they pass.
They caught the initial regression but were also fixed by the workaround commit in the meantime. So this test run only means this branch did not introduce another regression for sharing in text.
I did not look at the code as i assume it just reverts the commits and i did not check the error reports and check if they are fixed by this as it sounds like @szaimen already did so.

**Comment by szaimen** [comment]
Samba failure unrekated

**Comment by PVince81** [comment]
@CarlSchwan seems one of the PRs made it to stable22: https://github.com/nextcloud/server/pull/30697 but not the other one.
Can you do a manual backport if applicable ?

**Comment by szaimen** [comment]
/backport f0424378f68ee222bc9914af6e391624d9f3c711 to stable22

**Pull request merged**
