### PR TITLE
Allow setting favicon with a .ico file

### LINKED ISSUE #15954: Theming app does not allow *.ico file types for favicon
**Nextcloud version:** 15.0.8

Results in a 'Unsupported image type' message. PNG works fine.

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #15954 

This change allows the favicon to be set with a `.ico` file.

### CODE REVIEW

**Comment by skjnldsv** [comment]
Code looks good but I have no idea about this.
Is this part of the html standards? I indeed often saw ico as favicons, but no idea how things are actually supposed to be done! :thinking:

**Comment by juliushaertl** [comment]
The main issue with this is that the favicon image is also used for mobile integration like the apple-touch-icon. According to the docs they need a PNG, so I'm not sure if just shipping a big enough ICO file works. If that keeps working, I'm fine to add this, but this would need some test on iOS/Android.

**Comment by gary-kim** [comment]
> The main issue with this is that the favicon image is also used for mobile integration like the apple-touch-icon. According to the docs they need a PNG, so I'm not sure if just shipping a big enough ICO file works. If that keeps working, I'm fine to add this, but this would need some test on iOS/Android.

Okay, I'll try to find an iOS device to test on. If someone else can try this as well, thank you very much.

**Comment by ChristophWurst** [comment]
> Okay, I'll try to find an iOS device to test on. If someone else can try this as well, thank you very much.

@skjnldsv don't you have some magic trick for testing on other platforms? :wink:

**Comment by ChristophWurst** [comment]
sooooo … what do we want to do with this?

**Comment by skjnldsv** [comment]
Let's rebase & merge

**Comment by ChristophWurst** [comment]
> Let's rebase & merge

@gary-kim :)

**Comment by ChristophWurst** [comment]
> Okay, I'll try to find an iOS device to test on. If someone else can try this as well, thank you very much.

@gary-kim did you test? :)

**Comment by gary-kim** [comment]
No, I haven't tested

**Comment by MorrisJobke** [comment]
@gary-kim Let's do a deal: you rebase and I test it on iDevices once it is done, okay?

**Comment by gary-kim** [comment]
Deal

**Review by MorrisJobke — APPROVED** [review]
Tested - works at least on the devices I never connected to this server, because Safari really heavily caches the favicon (at least I was not able to clear it on my desktop Safari). But works fine on the tablet and phone Safari 👍

**Comment by MorrisJobke** [comment]
@skjnldsv @ChristophWurst Review time 🚀

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
