### PR TITLE
fix(files): navigation exact

### LINKED ISSUE #41737: Multiple highlighted / active elements in left sidebar for favorites
Currently favorites sub items in left sidebar when active also have the parent element highlighted, this is not the case for active sub items of other categories, like shared with...
2023-11-24 16_00_04-Files - Nextcloud – Mozilla Firefox

cc @nextcloud/designers on which way to implement it, I tend to say only highlight one item - don't highlight the parent element in addition.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/41737

### CODE REVIEW

**Comment by szaimen** [comment]
Can you please post a screenshot of before and after?

**Comment by skjnldsv** [comment]
> Can you please post a screenshot of before and after?

It's straightforward, no need for a screenshot. Before the parent and children gets the active display, after only the selected children get the focus.

See linked issue: 
image

**Review by szaimen — APPROVED** [review]
LGTM then :)

**Review by emoral435 — APPROVED** [review]
Tested it on my dev setup and it works 👍 LGTM as well!

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
