### PR TITLE
Change styles on active, hover and focus state for background buttons

### LINKED ISSUE #40682: [BITV]: Add more visibility on background buttons
This is an accesibility issue.

For now we have different preview-buttons with odifferent backgrounds. Selected one have to be more visible with enough contrasts. A black check-icon is not visible on different backgrounds and that have to be replaced with another solution.

Screenshot from 2023-09-28 16-46-02

@nimishavijay would we have a quick design and implementation change in this place? Which way is a "cheapest" one? Thank you!

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
* Resolves:  https://github.com/nextcloud/server/issues/40682

## Summary

Before:

Peek 2023-10-24 09-41

After:

Peek 2023-10-24 09-40

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Comment by ShGKme** [comment]
Border looks better, but in the issue it was also mentioned that the "✔️" icon is not visible.

**Review by Pytal — APPROVED** [review]

**Comment by JuliaKirschenheuter** [comment]
failed Cypress is unrelated

**Comment by JuliaKirschenheuter** [comment]
> Border looks better, but in the issue it was also mentioned that the "✔️" icon is not visible.

This issue was already resolved here https://github.com/nextcloud/server/issues/40687

**Pull request merged**
