### PR TITLE
Change screenshot in README.md

### PR DESCRIPTION
**Pull request by MariusBluem**
New screenshot, using `nextcloud/screenshots` as repository for the screenshots 😉

cc @jancborchardt

### CODE REVIEW

**Comment by tchncs** [comment]
I think, for international users, a screenshot fully in english would be nice :)

**Comment by MorrisJobke** [comment]
> I think, for international users, a screenshot fully in english would be nice :)

Yep. We should have english screenshots

**Comment by jancborchardt** [comment]
Got some, will open a new PR to the screenshots repo and we can use it from there.

**Comment by mar1u5** [comment]
Done. THX @jancborchardt  😉 - Merging 💪

**Comment by mar1u5** [comment]
Missed an filename change 😒 ... Fix is out #30 and will be merged as soon as the tests passed 😉

**Pull request merged**
