### PR TITLE
Fix main bundle on IE11

### LINKED ISSUE #21316: Production build not working on IE11
The production build of core/js/dist/main.js is failing on current master/stable19 with IE11 as terser seems to not use quoted properties:

image

```
SCRIPT1014: Invalid character
main.js (1005,21360)
```

Might be that the default changed or that this is a dependency update that pulled in the new object with the unicode properties. It works fine with the dev build so I assume that it is terser needs to get the `keep_quoted` setting passed somehow.

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes https://github.com/nextcloud/server/issues/21316

Make sure that properties are always quoted on production builds during terser optimization as unicode properties from our js dependencies are otherwise breaking the main bundle on IE11.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant: :heart:

**Comment by rullzer** [comment]
> /backport [5aef97c](https://github.com/nextcloud/server/commit/5aef97cfa7c81b00859f7e2966c77cbe42e66d0a) to stable19

does that work?

**Review by nickvergessen — APPROVED** [review]
Confirmed it fixes the login on IE11

**Review by MorrisJobke — APPROVED** [review]
Checke the output and it looks good 👍

**Pull request merged**
