### PR TITLE
Properly fetch translation for remote wipe confirmation dialog

### PR DESCRIPTION
**Pull request by juliusknorr**
The translations are part of the settings app, otherwise the strings in the confirmation dialog will stay untranslated.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Rebased.

**Comment by juliushaertl** [comment]
stable18 https://github.com/nextcloud/server/pull/22035
stable19 https://github.com/nextcloud/server/pull/22036

**Pull request merged**
