### PR TITLE
Raise timeout for Fetcher to work on slow internet connections

### LINKED ISSUE #14926: can not retrive apps.json, request timed out after 10 seconds
### Steps to reproduce
1. using a slow internet (less than 1Mbps)
2. set the log level to 1
3. visit the **Apps** section in NextCloud server panel and its sub parts.

### Expected behaviour
The apps from app store should be shown.

### Actual behaviour
For online apps from app store, a page with the text: **No apps found for your version** appears.

### Server configuration
Raspberry Pi 3 (1G RAM + 4 Core CPU ARMv7 Processor rev 4 (v7l))
**Operating system**:
Debian 9  (Raspbian)
**Web server:**
Nginx 1.10.3
**Database:**
MariaDB 10.1
**PHP version:**
PHP 7.3 
**Nextcloud version:** 
15.0.5.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
No
**Where did you install Nextcloud from:**
Official archived file from site, manually.
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'passwordsalt' => 'd+u+YFEoHATQnpIQEda9rp8MNhLjPy',
  'secret' => 'GrBJzreYaPAUb2995kVFM/eOPMUB4n1LWzPf3xcU6s88JwYh',
  'trusted_domains' => 
  array (
    0 => 'localhost', 'nextcloud.myhostname.xyz'
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '15.0.5.3',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'mysecretpassword',
  'installed' => true,
  'instanceid' => 'ocv0i43mq4vh',
  'loglevel' => 1,
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome 72

**Operating system:**
Debian 9
#### Web server error log
<details>
<summary>Web server error log</summary>

```
No error logs are generated.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Y4ILqYWLxVnVsuoCWicV","level":1,"time":"2019-04-01T09:58:06+00:00","remoteAddr":"192.168.1.1","user":"mehdi","app":"appstoreFetcher","method":"GET","url":"\/settings\/apps\/monitoring","message":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Operation timed out after 10000 milliseconds with 1050304 out of 1215078 bytes received (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/CurlFactory.php","line":149,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":[{"sink":{"__class__":"GuzzleHttp\\Psr7\\Stream"},"headers":["Date: Mon, 01 Apr 2019 09:57:56 GMT","Server: nginx\/1.10.3 (Ubuntu)","Strict-Transport-Security: max-age=15768000; includeSubDomains; preload","Content-Type: application\/json","Content-Length: 1215078","Content-Language: en","Vary: Accept-Language,Cookie","ETag: \"2019-04-01 09:00:10.955060+00:00\"","x-xss-protection: 1; mode=block","x-content-type-options: nosniff","Allow: GET, DELETE, HEAD, OPTIONS","X-Frame-Options: SAMEORIGIN","Content-Security-Policy: img-src *; style-src 'self'; form-action 'self'; connect-src 'self'; script-src 'self'; default-src 'none'; font-src 'self'"],"response":{"__class__":"GuzzleHttp\\Psr7\\Response"},"request":{"__class__":"GuzzleHttp\\Psr7\\Request"},"options":{"verify":"\/var\/www\/nextcloud\/data\/files_external\/rootcerts.crt","timeout":10,"synchronous":true,"handler":{"__class__":"GuzzleHttp\\HandlerStack"},"allow_redirects":{"max":5,"protocols":["http","https"],"strict":false,"referer":false,"track_redirects":false},"http_errors":true,"decode_content":true,"cookies":false},"errno":28,"onHeadersException":null,"__class__":"GuzzleHttp\\Handler\\EasyHandle"},{"errno":28,"error":"Operation timed out after 10000 milliseconds with 1050304 out of 1215078 bytes received","url":"https:\/\/apps.nextcloud.com\/api\/v1\/platform\/15.0.5\/apps.json","content_type":"application\/json","http_code":200,"header_size":591,"request_size":170,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":10.000916,"namelookup_time":7.9e-5,"connect_time":0.133558,"pretransfer_time":0.520545,"size_upload":0,"size_download":1050304,"speed_download":105020,"speed_upload":0,"download_content_length":1215078,"upload_content_length":-1,"starttransfer_time":0.754305,"redirect_time":0,"redirect_url":"","primary_ip":"88.198.160.138","certinfo":[],"primary_port":443,"local_ip":"192.168.1.90","local_port":41028,"http_version":2,"protocol":2,"ssl_verifyresult":0,"scheme":"HTTPS"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/CurlFactory.php","line":102,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":[{"__class__":"GuzzleHttp\\Handler\\CurlHandler"},{"sink":{"__class__":"GuzzleHttp\\Psr7\\Stream"},"headers":["Date: Mon, 01 Apr 2019 09:57:56 GMT","Server: nginx\/1.10.3 (Ubuntu)","Strict-Transport-Security: max-age=15768000; includeSubDomains; preload","Content-Type: application\/json","Content-Length: 1215078","Content-Language: en","Vary: Accept-Language,Cookie","ETag: \"2019-04-01 09:00:10.955060+00:00\"","x-xss-protection: 1; mode=block","x-content-type-options: nosniff","Allow: GET, DELETE, HEAD, OPTIONS","X-Frame-Options: SAMEORIGIN","Content-Security-Policy: img-src *; style-src 'self'; form-action 'self'; connect-src 'self'; script-src 'self'; default-src 'none'; font-src 'self'"],"response":{"__class__":"GuzzleHttp\\Psr7\\Response"},"request":{"__class__":"GuzzleHttp\\Psr7\\Request"},"options":{"verify":"\/var\/www\/nextcloud\/data\/files_external\/rootcerts.crt","timeout":10,"synchronous":true,"handler":{"__class__":"GuzzleHttp\\HandlerStack"},"allow_redirects":{"max":5,"protocols":["http","https"],"strict":false,"referer":false,"track_redirects":false},"http_errors":true,"decode_content":true,"cookies":false},"errno":28,"onHeadersException":null,"__class__":"GuzzleHttp\\Handler\\EasyHandle"},{"__class__":"GuzzleHttp\\Handler\\CurlFactory"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/CurlHandler.php","line":43,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":[{"__class__":"GuzzleHttp\\Handler\\CurlHandler"},{"sink":{"__class__":"GuzzleHttp\\Psr7\\Stream"},"headers":["Date: Mon, 01 Apr 2019 09:57:56 GMT","Server: nginx\/1.10.3 (Ubuntu)","Strict-Transport-Security: max-age=15768000; includeSubDomains; preload","Content-Type: application\/json","Content-Length: 1215078","Content-Language: en","Vary: Accept-Language,Cookie","ETag: \"2019-04-01 09:00:10.955060+00:00\"","x-xss-protection: 1; mode=block","x-content-type-options: nosniff","Allow: GET, DELETE, HEAD, OPTIONS","X-Frame-Options: SAMEORIGIN","Content-Security-Policy: img-src *; style-src 'self'; form-action 'self'; connect-src 'self'; script-src 'self'; default-src 'none'; font-src 'self'"],"response":{"__class__":"GuzzleHttp\\Psr7\\Response"},"request":{"__class__":"GuzzleHttp\\Psr7\\Request"},"options":{"verify":"\/var\/www\/nextcloud\/data\/files_external\/rootcerts.crt","timeout":10,"synchronous":true,"handler":{"__class__":"GuzzleHttp\\HandlerStack"},"allow_redirects":{"max":5,"protocols":["http","https"],"strict":false,"referer":false,"track_redirects":false},"http_errors":true,"decode_content":true,"cookies":false},"errno":28,"onHeadersException":null,"__class__":"GuzzleHttp\\Handler\\EasyHandle"},{"__class__":"GuzzleHttp\\Handler\\CurlFactory"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/Proxy.php","line":28,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/Proxy.php","line":51,"function":"GuzzleHttp\\Handler\\{closure}","class":"GuzzleHttp\\Handler\\Proxy","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/PrepareBodyMiddleware.php","line":37,"function":"GuzzleHttp\\Handler\\{closure}","class":"GuzzleHttp\\Handler\\Proxy","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Middleware.php","line":30,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RedirectMiddleware.php","line":70,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Middleware.php","line":60,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/HandlerStack.php","line":67,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php","line":277,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php","line":125,"function":"transfer","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php","line":131,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["get",{"__class__":"GuzzleHttp\\Psr7\\Uri"},{"verify":"\/var\/www\/nextcloud\/data\/files_external\/rootcerts.crt","timeout":10,"synchronous":true,"handler":{"__class__":"GuzzleHttp\\HandlerStack"},"allow_redirects":{"max":5,"protocols":["http","https"],"strict":false,"referer":false,"track_redirects":false},"http_errors":true,"decode_content":true,"cookies":false,"_conditional":{"User-Agent":"GuzzleHttp\/6.3.3 curl\/7.52.1 PHP\/7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2"}}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Http\/Client\/Client.php","line":161,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["get","https:\/\/apps.nextcloud.com\/api\/v1\/platform\/15.0.5\/apps.json",{"verify":"\/var\/www\/nextcloud\/data\/files_external\/rootcerts.crt","timeout":10,"synchronous":true}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/App\/AppStore\/Fetcher\/Fetcher.php","line":106,"function":"get","class":"OC\\Http\\Client\\Client","type":"->","args":["https:\/\/apps.nextcloud.com\/api\/v1\/platform\/15.0.5\/apps.json",{"timeout":10}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/App\/AppStore\/Fetcher\/AppFetcher.php","line":80,"function":"fetch","class":"OC\\App\\AppStore\\Fetcher\\Fetcher","type":"->","args":["",""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/App\/AppStore\/Fetcher\/Fetcher.php","line":170,"function":"fetch","class":"OC\\App\\AppStore\\Fetcher\\AppFetcher","type":"->","args":["",""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Installer.php","line":385,"function":"get","class":"OC\\App\\AppStore\\Fetcher\\Fetcher","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/settings\/Controller\/AppSettingsController.php","line":156,"function":"isUpdateAvailable","class":"OC\\Installer","type":"->","args":["logreader"]},{"file":"\/var\/www\/nextcloud\/settings\/Controller\/AppSettingsController.php","line":139,"function":"getAppsWithUpdates","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"viewApps","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"viewApps"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"viewApps"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\AppSettingsController","viewApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"category":"monitoring","id":"","_route":"settings.AppSettings.viewApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"category":"monitoring","id":"","_route":"settings.AppSettings.viewApps"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"category":"monitoring","id":"","_route":"settings.AppSettings.viewApps"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/apps\/monitoring"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/CurlFactory.php","Line":185,"CustomMessage":"Could not connect to appstore"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.119 Safari\/537.36","version":"15.0.5.3"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No javascript console error, No any http error codes.
```
</details>

### PR DESCRIPTION
**Pull request by small1**
The timeout in the appstore fetcher is to low. So i raised it to 30 seconds. 

Closes #14926

### CODE REVIEW

**Comment by kesselb** [comment]
Thank you and welcome to the club :tada: 

Looks good to me because the result is cached. We could consider to increase the lifetime of the cached value to a higher value.

https://github.com/nextcloud/server/blob/3a75ea7fa4358feab994f72f1280ee907655b323/lib/private/App/AppStore/Fetcher/Fetcher.php#L42

Would you mind to sign off your commits? https://github.com/nextcloud/server/pull/16149/checks?check_run_id=157989419

**Comment by small1** [comment]
> Thank you and welcome to the club 
> 
> Looks good to me because the result is cached. We could consider to increase the lifetime of the cached value to a higher value.
> 
> https://github.com/nextcloud/server/blob/3a75ea7fa4358feab994f72f1280ee907655b323/lib/private/App/AppStore/Fetcher/Fetcher.php#L42
> 
> Would you mind to sign off your commits? https://github.com/nextcloud/server/pull/16149/checks?check_run_id=157989419

I thought i did that ... seems like i did not do the amend right in some way.

**Comment by small1** [comment]
I'm going to stop and try to fix that mistake. It was to long since i used git :P

**Comment by kesselb** [comment]
> I'm going to stop and try to fix that mistake. It was to long since i used git :P

https://github.com/nextcloud/server/pull/16149/checks?check_run_id=158029855 it should be enough to follow this two commands.

**Review by kesselb — APPROVED** [review]

**Comment by jancborchardt** [comment]
The commits should probably be squashed before merging. Not sure if we do this automatically or there’s a command for it @kesselb @rullzer?

**Comment by small1** [comment]
> The commits should probably be squashed before merging. Not sure if we do this automatically or there’s a command for it @kesselb @rullzer?

@jancborchardt now i think i got my git commands in the right order. I did remove all the merging stuff that should not be in the commit and squashed my own.

**Comment by MorrisJobke** [comment]
Also the 30 seconds there has some side effects: most web servers have a default timeout of 30 seconds - so if the timeout hits in it is 30s + the request timeout. Which then is over 30s and thus the response is always a 50x (most likely bad gateway) error. Thus we set this to 10 seconds. The better approach would be to fetch this in a background job so it is not bound to a user facing request and also makes the app management a lot more snappy.

**Comment by small1** [comment]
> Also the 30 seconds there has some side effects: most web servers have a default timeout of 30 seconds - so if the timeout hits in it is 30s + the request timeout. Which then is over 30s and thus the response is always a 50x (most likely bad gateway) error. Thus we set this to 10 seconds. The better approach would be to fetch this in a background job so it is not bound to a user facing request and also makes the app management a lot more snappy.

php has an execution timeout of 30 seconds as default yes that can be changed with set_time_limit to increase with a few seconds if needed. Apache and nginx has a timeout of requests for 60 seconds if im not mistaken so setting this would not really be a problem. I never tested with a smaller timeout than 30 for my clients that are on slow connections. But perhaps 20 or 25 would work as well. 10 is to low. 

But yes the better way would be to have a background job for this. It would make everything work much smoother. But also a bigger rewrite.

**Comment by MorrisJobke** [comment]
> php has an execution timeout of 30 seconds as default yes that can be changed with set_time_limit to increase with a few seconds if needed. Apache and nginx has a timeout of requests for 60 seconds if im not mistaken so setting this would not really be a problem. I never tested with a smaller timeout than 30 for my clients that are on slow connections. But perhaps 20 or 25 would work as well. 10 is to low.

Yep something below 30 is fine, but 30 is extremely bad, because it interferes with the default setup (and to be honest a lot of instances out there run with a default setup ;)).

I still fear, that the app management is then super slow to use and just gives a bad user experience. To really tackle this we should fix it properly and not with yet another workaround. Sorry for the bad news here. You could use your patch in the meantime to avoid issues on your instance, but we have thousands of other instances out there about which we also need to think.

**Comment by small1** [comment]
Yeah breaking stuff is not the motive here. Only fixing broken stuff. What it says right now is that an app cant be downloaded. Or you get an empty app store in some cases. 

But i agree. Breaking installations is not an option. AS this is a small patch i can manage to work around with fixing this manually.

**Comment by small1** [comment]
And actually when i tinkered around now ani found that sometimes the problem occurs in guzzles curl factory. So more than this was needed anyway.

**Comment by small1** [comment]
I'm closing this.

**Comment by MorrisJobke** [comment]
Thanks for your help anyways 👍

**Comment by andrewperry** [comment]
This suggests that the Nextcloud team may be able to help resolve the underlying issue by increasing the responsiveness of the apps server: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fapps.nextcloud.com%2Fapi%2Fv1%2Fapps.json

**Comment by fwolfst** [comment]
@kesselb I understand you locking #14926, but maybe you could include this one-liner in the "solution". I will apply it after every update and it might be worth sharing for people with automated setups.

    sed -i "s/'timeout' => 10,/'timeout' => 90/" lib/private/App/AppStore/Fetcher/Fetcher.php #as of NC 16.0.6

**Pull request closed without merging**
