### PR TITLE
Make search popup usable on mobile, too

### LINKED ISSUE #25037: android & firefox: search popup not visible (out of screen)
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. open Nextcloud on firefox mobile 84.1.3 on android 8.0.0 (maybe other browsers/platforms too)
2. tap the search icon and type something

### Expected behaviour
search popup is centered, search results are visible

### Actual behaviour
search popup is beyond the screen on left side, can't see the search results

### Server configuration
Nextcloud 20.0.4

Tell me if you need more info.

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/25037

## Desktop
| Before | After |
|---|---|
| image | image |

## Mobile
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]

**Review by JayceeCorson1023 — APPROVED** [review]

**Comment by JayceeCorson1023** [comment]
What the holly fuck shits

**Comment by Choice45** [comment]
I need some funds bro
I don't have a dime pls

**Pull request merged**
