### PR TITLE
Make sure the UID is correctly cased

### PR DESCRIPTION
**Pull request by nickvergessen**
Try to transfer files from user `test1` to `test2` with the command `occ files:transfer-ownership Test1 Test2`

@MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
👍

**Review by LukasReschke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Doesn't work for me - the transfer then doesn't work at all after checking out this branch. No folder `transferred from test1 on 2016-10-17T11:22:25+00:00` is created with this branch even if the correct naming is used. 👎

**Comment by nickvergessen** [comment]
Fixed

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
