### PR TITLE
Fix group restriction regression

### LINKED ISSUE #4952: Group restriction are not saved
### Steps to reproduce
1. upgrade to NC12b4
2. open apps
3. restrict "password policy" or "text editor" app to group admin (check mark in checkbox, select admin group)
4. reload apps page

### Expected behaviour
password policy app should be set to group admin only

### Actual behaviour
checkmark is removed

### Server configuration
**Operating system**: debian 8.8, up-to-date
**Web server:** apache 2.4
**Database:** mySQL 5.5
**PHP version:** 5.6
**Nextcloud version:** 12.0 beta 4, updated from NC 11.0.3
**Where did you install Nextcloud from:** NC updater app (beta channel)
**Signing status:** "No errors have been found." (after removing(!) ownbackup, rescanning, and reinstalling it)
**List of activated apps:** Irrelevant here
**Nextcloud configuration:** Should be irrelevant here
**Are you using external storage:** no
**Are you using encryption:** no
**Are you using an external user-backend:** no

### Client configuration
Irrelevant here.

#### Web server error log
nothing during above actions

#### Nextcloud log (data/nextcloud.log)
nothing during above actions

#### Browser log
nothing during above actions

### PR DESCRIPTION
**Pull request by MorrisJobke**
* use the group restriction feature
* before: after refresh it was reset (as in "never saved")
* after: the group restriction for apps works again
* fixes #4952 

I also fixed the "never use one ID multiple times on a page". I will also create a backport to stable12.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@nursoda Could I ask you to test this?

**Comment by MorrisJobke** [comment]
Backport for 12 is in #4973

**Comment by nursoda** [comment]
@MorrisJobke, is it OK to wait for the [daily](https://download.nextcloud.com/server/daily/latest.tar.bz2) to be built? When is it built / what time tomorrow shall I test? I'm not a dev and I would rather use the updater app with the daily channel instead of git and build myself. Will I be able to switch back to beta channel and receive b5 once ready?

**Review by LukasReschke — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@nursoda You can also apply the patch by doing this:

cd /tmp
wget https://github.com/nextcloud/server/pull/4972.patch
cd /var/www/nextcloud
patch -p1 < /tmp/4972.patch

**Comment by nursoda** [comment]
Did that, works for me as expected / as it should. Thanks, that was quick :-)

**Pull request merged**
