### PR TITLE
Resolves #15694, Improves clarity of the high contrast theme

### LINKED ISSUE #15694: Left sidebar w/ high contrast theme
### Steps to reproduce
1. Go to the Settings.
2. Check ``Enable high contrast theme`` in the Accessibility section of the Personal Settings. 
3. Open the Files app.

### Expected behaviour
The clarity of the navigation in the left sidebar should be increased.

### Actual behaviour
In the Files app the left sidebar of the main user interface still looks with normal font and/or contrast after enabling the accessibility setting. Only the lower Settings area and the disk usage have a higher contrast.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
16.0.1
**Updated from an older Nextcloud or fresh install:**
15.0.7
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 67.0
**Operating system:**
Windows 10 1903

### PR DESCRIPTION
**Pull request by Steve2955**
@juliushaertl As promised I made all the changes suggested in #15694 to improve the clarity of the sidebar when using the high contrast theme. The screenshots below show the changes. (left = before; right = after; both with high contrast enabled)

Because the navbar-menu has a design very similar to the sidebar I decided to change its opacity as well.

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks 👍

**Comment by jancborchardt** [comment]
@Steve2955 thanks a lot! Actually this is something we would want in the main design, not only in the high contrast theme. :)

See the Talk app left AppNavigation for how it should be:

- Using `--color-main-text` for the main text and `--color-text-maxcontrast` for any subline or details.
- Background for hover/focus: grey `--color-background-dark`, for the selected entry: `--color-primary-light`
- The inset box-shadow on the left can then be removed as obsolete
- No use of transparency/opacity

Would you like to adjust your pull request? Then everyone would get the proper contrast and it would look more consistent. :)

cc @ma12-co @nextcloud/designers

**Comment by Steve2955** [comment]
@jancborchardt Thank you for your feedback to my first PR. 

So what I need to do next is revert my changes to the high contrast theme and instead do some changes, like you described, directly within the theme of the Files and Settings app?

**Comment by jancborchardt** [comment]
> So what I need to do next is revert my changes to the high contrast theme and instead do some changes, like you described, directly within the theme of the Files and Settings app?

Yes, exactly. :) The code in question is at:

AppNavigation for apps not using the [Vue components](https://github.com/nextcloud/nextcloud-vue) yet (like Files):
https://github.com/nextcloud/server/blob/master/core/css/apps.scss#L155-L166

Settings menu in the header:
https://github.com/nextcloud/server/blob/master/core/css/header.scss#L127-L171

**Comment by GretaD** [comment]
@Steve2955 all good with this one? Do you need any other help to continue?

Thanks again

**Comment by Steve2955** [comment]
@GretaD Everything fine so far, thank you very much for asking. All the changes are clear to me, but I had some exams last week and will have the last ones in the next few days so I hadn't much time implementing the changes. I will start working on this again at the end of the week.

**Comment by GretaD** [comment]
oh no pressure, just making sure all was good, good luck on your exams. :)

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Hello @Steve2955 did you experienced an issue while pushing?

**Comment by Steve2955** [comment]
@skjnldsv I tried deleting my last commit so can do the changes in different files, but I think I did something wrong. I'm not very experienced with git but thought I knew what I was doing. Is there anything I need to do to fix this or will pushing a new commit to my branch and reopening the PR be fine?

**Comment by skjnldsv** [comment]
> Is there anything I need to do to fix this or will pushing a new commit to my branch and reopening the PR be fine?

Nope, all good :)
You can do that or if it doesn't work, open a new pr ;)

**Comment by Steve2955** [comment]
Very short update: My RPi which I used as a dev environment for this project broke down a few days ago. I need to get a new sd-card to start working on this again, but I am still wanting to do it. I'm very sorry this is taking so long.

**Comment by Steve2955** [comment]
Honestly, I am about to give up on this. I spend the last two days setting up my local development environment and trying to implement the changes. As suggested I started editing this file [/core/css/apps.scss#L155-L166](https://github.com/nextcloud/server/blob/master/core/css/apps.scss#L155-L166). To test my changes I clear the scss cache using ```occ maintenance:repair```. However after making some changes the ```server.css``` starts failing to load. I tried reverting all my changes, made sure the file permissions are right and cleared my browser cache, but nothing worked. I recreated my development environment twice already.

Are there any logs which I could check? `\data\nextcloud.log` didn't contain any usefull info.

**Pull request closed without merging**
