### PR TITLE
fix styling of renaming system tags

### PR DESCRIPTION
**Pull request by icewind1991**
Before:

After:

cc @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by nickvergessen** [comment]
You don't have the height problem from my screenshot?

**Comment by skjnldsv** [comment]
@nickvergessen I didn't have it either!
@icewind1991 Nice work, could we have a validation button too? I think this looks weird and the user don't really now what to do after finishing the edition. We need a feedback! :)

**Comment by MorrisJobke** [comment]
> @icewind1991 Nice work, could we have a validation button too? I think this looks weird and the user don't really now what to do after finishing the editing. We need a feedback! :)

I would say this could also go into a seperate PR. This already fixes something and we want to have an RC today ;)

**Comment by MorrisJobke** [comment]
* [ ] while editing the checkmark icon is shifted a bit upwards (editing an applied tag):

bildschirmfoto 2016-12-06 um 10 20 39

**Comment by MorrisJobke** [comment]
* [ ] input field only partially visible in Firefox:

bildschirmfoto 2016-12-06 um 10 22 39

**Comment by nickvergessen** [comment]
> input field only partially visible in Firefox:

That was my actual report which I wanted to have fixed with this 💃

**Comment by icewind1991** [comment]
Should be fine in ff now to

**Comment by MorrisJobke** [comment]
Tested and works now in FF 👍

**Comment by skjnldsv** [comment]
It's all on the same line now right?
I can't figured out if this is supposed to look like the first post's screenshots 😆

**Comment by MorrisJobke** [comment]
> I can't figured out if this is supposed to look like the first post's screenshots 😆

It should :)

**Comment by skjnldsv** [comment]
Well I don't know what's happening then! 😕

**Comment by MorrisJobke** [comment]
@nickvergessen quick review?

**Comment by nickvergessen** [comment]
works 👍

**Pull request merged**
