### PR TITLE
Fix missing label of Search function

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixes the remaining issue reported by Lighthouse by moving the aria-label from the icon to the link itself.

### CODE REVIEW

**Review by marcoambrosini — APPROVED** [review]
Code seems ok but can't test atm, so...

giphy

**Comment by jancborchardt** [comment]
Now works thanks to @juliushaertl! The issue was that due to the `v-if`, the target of the `aria-controls` doesn’t actually exist in the DOM unless opened. Replacing it with `v-show` fixed it. :tada:

**Review by juliusknorr — APPROVED** [review]
:rocket:

**Pull request merged**
