### PR TITLE
[10] Fix shared storage recursive setup

### LINKED ISSUE #986: Cannot log in after upgrade to NC10 RC1, php-fpm segfaults
### Steps to reproduce
1. Upgrade to NC10 RC1
2. Try to log in
3. Face a 502 warning

### Expected behaviour
Be logged in.

### Actual behaviour
Not being logged in, but facing a 502 instead.

### Server configuration
**Operating system**:
Centos 7

**Web server:**
Nginx 1.8

**Database:**
Postgres 9.4

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
10 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Latest 9.1

**Where did you install Nextcloud from:**
Git

**Signing status:**
<details>
<summary>Signing status</summary>
if only i could reach this site...
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
quite a few
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oceefae26795",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.brainflush.org"
        ],
        "datadirectory": "\/media\/owncloud-storage",
        "dbtype": "pgsql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "brainflush.org",
        "asset-pipeline.enabled": false,
        "theme": "",
        "maintenance": false,
        "appstoreenabled": true,
        "updatechecker": false,
        "loglevel": 0,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NOPE

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
2016/08/19 19:35:54 [error] 23777#0: *1472 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: cloud.brainflush.org, request: "POST /index.php/login?redirect_url=%252Findex.php%252Fsettings%252Fintegrity%252Ffailed HTTP/1.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "cloud.brainflush.org"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"ZzIU4ne95+Spn8XQmx40","remoteAddr":"127.0.0.1","app":"admin_audit","message":"Login attempt: \"florian\"","level":1,"time":"2016-08-19T17:35:51+00:00","method":"POST","url":"\/index.php\/login?redirect_url=%252Findex.php%252Fsettings%252Fintegrity%252Ffailed","user":"--"}
{"reqId":"ZzIU4ne95+Spn8XQmx40","remoteAddr":"127.0.0.1","app":"admin_audit","message":"Login successful: \"florian\"","level":1,"time":"2016-08-19T17:35:51+00:00","method":"POST","url":"\/index.php\/login?redirect_url=%252Findex.php%252Fsettings%252Fintegrity%252Ffailed","user":"florian"}
</details>

aaaand php-fpm:

<details>
[19-Aug-2016 19:35:54] WARNING: [pool www] child 1142 exited on signal 11 (SIGSEGV) after 63.479760 seconds from start
[19-Aug-2016 19:35:54] NOTICE: [pool www] child 1671 started
</details>

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #1007

Fixes #986

@mrflow can you check if this fixes the problem for you

### CODE REVIEW

**Comment by rullzer** [comment]
LGTM

**Comment by mrflow** [comment]
checked out 58b810a5477fc18c2b99a714da7f84199cc02ee6
did not solve the problem for me.

php-fpm still segfaulting.

**Comment by icewind1991** [comment]
@mrflow can you retry with the latest commit

**Comment by mrflow** [comment]
@icewind1991  that solved the problem. many thanks!

**Comment by LukasReschke** [comment]
:bomb:

```
  Scenario: Retrieving folder quota of shared folder with quota when no quota is set for recipient        # /drone/src/github.com/nextcloud/server/build/integration/features/webdav-related.feature:44
    Given using dav path "remote.php/webdav"                                                              # FeatureContext::usingDavPath()
    And As an "admin"                                                                                     # FeatureContext::asAn()
[Mon Aug 22 18:35:21 2016] ::1:58202 [404]: /ocs/v2.php/cloud/users/user0
[Mon Aug 22 18:35:21 2016] ::1:58203 [200]: /ocs/v1.php/cloud/users
[Mon Aug 22 18:35:22 2016] ::1:58204 [200]: /ocs/v1.php/cloud/users/user0
[Mon Aug 22 18:35:22 2016] ::1:58205 [200]: /ocs/v2.php/cloud/users/user0
    And user "user0" exists                                                                               # FeatureContext::assureUserExists()
[Mon Aug 22 18:35:22 2016] ::1:58206 [404]: /ocs/v2.php/cloud/users/user1
[Mon Aug 22 18:35:22 2016] ::1:58207 [200]: /ocs/v1.php/cloud/users
[Mon Aug 22 18:35:23 2016] ::1:58208 [200]: /ocs/v1.php/cloud/users/user1
[Mon Aug 22 18:35:23 2016] ::1:58209 [200]: /ocs/v2.php/cloud/users/user1
    And user "user1" exists                                                                               # FeatureContext::assureUserExists()
[Mon Aug 22 18:35:23 2016] ::1:58210 [200]: /ocs/v1.php/cloud/users/user0
    And user "user0" has unlimited quota                                                                  # FeatureContext::userHasUnlimitedQuota()
[Mon Aug 22 18:35:23 2016] ::1:58211 [200]: /ocs/v1.php/cloud/users/user1
    And user "user1" has a quota of "10 MB"                                                               # FeatureContext::userHasAQuotaOf()
    And As an "user1"                                                                                     # FeatureContext::asAn()
[Mon Aug 22 18:35:24 2016] ::1:58212 [201]: /remote.php/webdav/testquota
    And user "user1" created a folder "/testquota"                                                        # FeatureContext::userCreatedAFolder()
[Mon Aug 22 18:35:24 2016] ::1:58213 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
    And as "user1" creating a share with                                                                  # FeatureContext::asCreatingAShareWith()
      | path        | testquota |
      | shareType   | 0         |
      | permissions | 31        |
      | shareWith   | user0     |
[Mon Aug 22 18:35:24 2016] ::1:58214 [401]: /remote.php/webdav/testquota
[Mon Aug 22 18:35:24 2016] call_user_func_array() expects parameter 1 to be a valid callback, class 'OC\Files\Storage\Home' does not have a method 'getSourceStorage' at /drone/src/github.com/nextcloud/server/lib/private/Files/Storage/Wrapper/Wrapper.php#497
[Mon Aug 22 18:35:24 2016] Exception: {"Exception":"Error","Message":"Call to a member function instanceOfStorage() on null","Code":0,"Trace":"#0 \/drone\/src\/github.com\/nextcloud\/server\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php(298): OC_Helper::getStorageInfo('\/user0\/files\/te...', Object(OC\\Files\\FileInfo))\n#1 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(808): OCA\\DAV\\Connector\\Sabre\\Directory->getQuotaInfo()\n#2 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/PropFind.php(98): Sabre\\DAV\\CorePlugin->Sabre\\DAV\\{closure}()\n#3 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(811): Sabre\\DAV\\PropFind->handle('{DAV:}quota-ava...', Object(Closure))\n#4 [internal function]: Sabre\\DAV\\CorePlugin->propFind(Object(Sabre\\DAV\\PropFind), Object(OCA\\DAV\\Connector\\Sabre\\Directory))\n#5 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(999): Sabre\\Event\\EventEmitter->emit('propFind', Array)\n#7 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(919): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(OCA\\DAV\\Connector\\Sabre\\Directory))\n#8 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(334): Sabre\\DAV\\Server->getPropertiesForPath('testquota', Array, 0)\n#9 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#10 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#11 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#12 \/drone\/src\/github.com\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/drone\/src\/github.com\/nextcloud\/server\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#14 \/drone\/src\/github.com\/nextcloud\/server\/remote.php(165): require_once('\/drone\/src\/gith...')\n#15 {main}","File":"\/drone\/src\/github.com\/nextcloud\/server\/lib\/private\/legacy\/helper.php","Line":599}
[Mon Aug 22 18:35:24 2016] ::1:58215 [500]: /remote.php/webdav/testquota
    Then as "user0" gets properties of folder "/testquota" with                                           # FeatureContext::asGetsPropertiesOfFolderWith()
      | {DAV:}quota-available-bytes |
      HTTP error: 500 (Sabre\DAV\Exception)
    And the single response should contain a property "{DAV:}quota-available-bytes" with value "10485429" # FeatureContext::theSingleResponseShouldContainAPropertyWithValue()
[Mon Aug 22 18:35:24 2016] ::1:58216 [200]: /ocs/v1.php/cloud/users/user0
[Mon Aug 22 18:35:24 2016] ::1:58217 [404]: /ocs/v2.php/cloud/users/user0
[Mon Aug 22 18:35:24 2016] ::1:58218 [200]: /ocs/v1.php/cloud/users/user1
[Mon Aug 22 18:35:25 2016] ::1:58219 [404]: /ocs/v2.php/cloud/users/user1
[Mon Aug 22 18:35:25 2016] ::1:58220 [401]: /remote.php/webdav/myFileToComment.txt
[Mon Aug 22 18:35:25 2016] ::1:58221 [207]: /remote.php/dav/systemtags/
[Mon Aug 22 18:35:25 2016] ::1:58222 [401]: /remote.php/webdav/myFileToTag.txt
[Mon Aug 22 18:35:25 2016] ::1:58223 [404]: /remote.php/dav/addressbooks/users/admin/MyAddressbook
[Mon Aug 22 18:35:25 2016] ::1:58224 [404]: /remote.php/dav/calendars/admin/MyCalendar
```

**Comment by icewind1991** [comment]
tests all green, please review @LukasReschke @rullzer

**Comment by rullzer** [comment]
Whee :+1:

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
