### PR TITLE
Don't set up full filesystem to check for certificates

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref:
https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Security/CertificateManager.php#L90-L93

### Case
* Set up Talk with HPB
* Join a call => sends HPB message to inform all users => sets up your FS

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
Make sense 👍

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by nickvergessen** [comment]
Could backport to 22 as well when the backport of icewind's PR is merged

**Pull request merged**
