### PR TITLE
l10n: Spelling unification

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Transifex.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
lgtm

**Comment by rakekniven** [comment]
String freeze is active. Please make no changes to code which causes changes at Transifex.

**Comment by szaimen** [comment]
> String freeze is active. Please make no changes to code which causes changes at Transifex.

cc @Pytal

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
> There is a file conflict. How can this be fixed?

`git pull --rebase origin master`
and then
`git push --force-with-lease`

**Comment by szaimen** [comment]
> @szaimen And from GitHub? Is `/rebase` enough?

No that won't work unfortunately because there are conflicts...

**Comment by Valdnet** [comment]
I am asking for help in removing the conflict from within Git. I do not have it installed on my machines.

It would be good to merge this PR 😉.

**Review by rakekniven — APPROVED** [review]

**Comment by Valdnet** [comment]
@szaimen Thank you for doing the rebase 😉. There are two more conflicts that I cannot deal with. Can I ask for tips or solve them?

**Comment by szaimen** [comment]
> @szaimen Thank you for doing the rebase 😉. There are two more conflicts that I cannot deal with. Can I ask for tips or solve them?

I fear it needs another rebase

**Comment by szaimen** [comment]
And another rebase. Its getting exhausting

**Comment by Valdnet** [comment]
> And another rebase. Its getting exhausting

Would it be better to close this PR and open a new one?

**Comment by szaimen** [comment]
> > And another rebase. Its getting exhausting
> 
> Would it be better to close this PR and open a new one?

Nope the same would hapen to that as well...

**Comment by Valdnet** [comment]
Thank you @szaimen for your help 👍.

Please merge 😉.

**Pull request merged**
