### PR TITLE
27.0.0 beta 2

### PR DESCRIPTION
**Pull request by skjnldsv**
Could not find base or head reference on text.

* #31469
* #31660
* #33381
* #35092
* #36118
* #36893
* #36895
* #37691
* #37734
* #37838
* #37870
* #37933
* #37944
* #37954
* #37961
* #37971
* #38048
* #38063
* #38067
* #38068
* #38069
* #38073
* #38077
* #38085
* #38088
* #38095
* #38097
* #38099
* #38100
* #38102
* #38104
* #38107
* #38109
* #38111
* #38112
* #38124
* #38125
* #38133
* #38140
* #38144
* #38147
* #38148
* #38152
* #38159
* #38163
* #38169
* #38170
* #38174
* #38194
* #38200
* #38207
* #38214
* #38218
* nextcloud/activity#1154
* nextcloud/activity#1161
* nextcloud/circles#1307
* nextcloud/firstrunwizard#836
* nextcloud/firstrunwizard#865
* nextcloud/logreader#827
* nextcloud/logreader#858
* nextcloud/logreader#864
* nextcloud/nextcloud_announcements#192
* nextcloud/nextcloud_announcements#194
* nextcloud/notifications#1539
* nextcloud/notifications#1540
* nextcloud/notifications#1541
* nextcloud/notifications#1544
* nextcloud/password_policy#456
* nextcloud/password_policy#465
* nextcloud/photos#1337
* nextcloud/photos#1664
* nextcloud/photos#1693
* nextcloud/photos#1704
* nextcloud/photos#1771
* nextcloud/photos#1774
* nextcloud/photos#1777
* nextcloud/photos#1781
* nextcloud/photos#1782
* nextcloud/photos#1787
* nextcloud/recommendations#611
* nextcloud/related_resources#220
* nextcloud/serverinfo#443
* nextcloud/viewer#1643
* nextcloud/viewer#1645
* nextcloud/viewer#1648
* nextcloud/viewer#1651
* nextcloud/viewer#1654
* nextcloud/viewer#1655
* nextcloud/viewer#1656

## Pending PRs:
* @2lar
  * [ ] #37878
* @AaronDewes
  * [ ] #37201
* @Abijeet
  * [ ] nextcloud/logreader#476
* @Adambean
  * [ ] #34141
* @akhil1508
  * [ ] #35459
  * [ ] #35867
  * [ ] #37328
* @Al2Klimov
  * [ ] #29423
* @aleixq
  * [ ] #37896
* @alpapan
  * [ ] #35701
* @ArtificialOwl
  * [ ] #32827
  * [ ] #35030
  * [ ] #35526
  * [ ] #35915
  * [ ] nextcloud/circles#891
  * [ ] nextcloud/circles#980
* @artonge
  * [ ] #32257
  * [ ] #34586
  * [ ] #34956
  * [ ] nextcloud/photos#1785
  * [ ] nextcloud/photos#1786
  * [ ] nextcloud/photos#1793
* @avinash-0007
  * [ ] #35553
* @blizzz
  * [ ] #32197
  * [ ] #37969
* @blkqi
  * [ ] nextcloud/recommendations#354
* @CarlSchwan
  * [ ] #27961
  * [ ] #29430
  * [ ] #31160
  * [ ] #31346
  * [ ] #32961
  * [ ] #35324
* @cdammanintopix
  * [ ] #34115
* @Cdisk2022
  * [ ] nextcloud/files_rightclick#135
* @charleypaulus
  * [ ] #35189
* @chrisfritsche
  * [ ] nextcloud/activity#504
* @ChristophWurst
  * [ ] #37965
  * [ ] #38013
* @clivinghouse
  * [ ] #35691
* @cneukom
  * [ ] #33397
* @come-nc
  * [ ] #37209
  * [ ] #38080
  * [ ] #38195
* @CommanderRoot
  * [ ] #31699
* @danxuliu
  * [ ] #28911
  * [ ] #38082
  * [ ] #38164
  * [ ] nextcloud/files_pdfviewer#654
* @Dany1718
  * [ ] #34419
* @DerGenaue
  * [ ] #38115
* @dnviti
  * [ ] nextcloud/files_rightclick#62
* @Dreamsorcerer
  * [ ] #27613
* @european
  * [ ] #24095
* @Fenn-CS
  * [ ] #37458
* @fgsl
  * [ ] nextcloud/circles#226
  * [ ] nextcloud/circles#229
* @FreesphereTom
  * [ ] nextcloud/files_rightclick#129
* @fsamapoor
  * [ ] #36742
  * [ ] #37665
* @fschrempf
  * [ ] nextcloud/activity#693
* @hoxia
  * [ ] nextcloud/circles#338
* @icewind1991
  * [x] #36592
  * [ ] #38179
* @individual-it
  * [ ] #37761
* @inet-cologne
  * [ ] #37477
* @itmanagerro
  * [ ] #31038
* @J0WI
  * [ ] #35587
* @jbmolle
  * [ ] #36791
* @Jerome-Herbinet
  * [ ] #34290
  * [ ] #34891
  * [ ] #36831
  * [ ] #37585
  * [ ] #37599
  * [ ] #37823
  * [ ] #38101
* @jkellerer
  * [ ] nextcloud/photos#1417
* @jlssmt
  * [ ] #35461
* @joshtrichards
  * [ ] #37581
  * [ ] nextcloud/logreader#866
* @julien-nc
  * [ ] #29143
  * [ ] #29729
* @juliushaertl
  * [ ] #26540
  * [ ] #27531
  * [ ] #27820
  * [ ] #30359
  * [ ] #30472
  * [ ] #33239
  * [ ] #36808
  * [ ] #36830
  * [ ] #37621
  * [ ] #37709
  * [ ] #37736
  * [ ] #38030
* @JustAdamHere
  * [ ] #33546
* @justin-sleep
  * [ ] #33928
* @kominoshja
  * [ ] #30980
* @madmas
  * [ ] nextcloud/activity#460
* @Mazhoon
  * [ ] #35270
* @mdoggydog
  * [ ] #30895
* @miaulalala
  * [ ] #37624
* @MichaIng
  * [ ] #29988
* @michielbdejong
  * [ ] #35555
* @moan0s
  * [ ] #37953
* @mrvahedi68
  * [ ] #37914
* @mstolf
  * [ ] #32308
* @niloc132
  * [ ] #37020
* @overhacked
  * [ ] nextcloud/serverinfo#331
* @p5n
  * [ ] #27806
* @pavelkryl
  * [ ] #30654
* @pboguslawski
  * [ ] #33795
* @peschmae
  * [ ] nextcloud/serverinfo#434
* @provokateurin
  * [ ] #37506
  * [ ] #37512
  * [ ] #37722
  * [ ] #37723
  * [ ] #37725
  * [ ] #38143
* @Pytal
  * [ ] #32466
  * [ ] #32775
  * [ ] #36812
* @R0Wi
  * [ ] #36316
* @rexbron
  * [ ] nextcloud/circles#971
* @RonaldBarnes
  * [ ] #35451
* @rotdrop
  * [ ] #30957
* @rubo77
  * [ ] #34425
* @RyanAveritt
  * [ ] #34391
* @schlimmchen
  * [ ] #26686
* @simonspa
  * [ ] #36220
* @smesterheide
  * [ ] #34132
  * [ ] #35732
* @solracsf
  * [ ] #37350
  * [ ] #37540
  * [ ] #37959
  * [ ] nextcloud/circles#1298
* @sreith1
  * [ ] #36776
* @sshambar
  * [ ] #20757
* @starypatyk
  * [ ] #34918
* @StCyr
  * [ ] #32647
* @sualko
  * [ ] nextcloud/recommendations#458
* @summersab
  * [ ] #36337
  * [ ] #36572
* @SuperSandro2000
  * [ ] #37773
* @susnux
  * [ ] #36462
  * [ ] #38127
* @szaimen
  * [ ] #31938
  * [ ] #38177
* @takahiro-blab
  * [ ] #31001
* @tarunsamanta2k20
  * [ ] #37470
* @tcitworld
  * [ ] #31790
  * [ ] #32321
  * [ ] #33221
  * [ ] #34873
  * [ ] #35754
  * [ ] #36252
  * [ ] #36522
  * [ ] #37193
  * [ ] #37303
  * [ ] #37326
  * [ ] #38065
* @the-djmaze
  * [ ] #36239
* @thomasrockhu-codecov
  * [ ] #32006
* @tintou
  * [ ] nextcloud/activity#530
* @tortuetorche
  * [ ] nextcloud/circles#384
  * [ ] nextcloud/circles#392
  * [ ] nextcloud/circles#395
  * [ ] nextcloud/circles#398
  * [ ] nextcloud/circles#399
  * [ ] nextcloud/circles#400
  * [ ] nextcloud/circles#401
* @unteem
  * [ ] #32781
* @vitormattos
  * [ ] #36505
  * [ ] #37348
* @w9n
  * [ ] #37778
* @xerc
  * [ ] #32839
* @zevlee
  * [ ] #36769

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Today is Tuesday... just sayin' 😁

**Comment by skjnldsv** [comment]
> Today is Tuesday... just sayin' grin

We never be too careful! :see_no_evil: 
I figured the ping would help get people merge stuff faster instead of having a cazry thursday for CI.

Also gives me time to clean some draft or developing PR

**Comment by AndyScherzinger** [comment]
Smart move @skjnldsv - I just tried to be funny here 😅

**Comment by skjnldsv** [comment]
| Author | Pull requests |
|:---------|:------|
|2lar|<ul><li>[ ] #37878</li></ul>|
|AaronDewes|<ul><li>[ ] #37201</li></ul>|
|Abijeet|<ul><li>[ ] nextcloud/logreader#476</li></ul>|
|akhil1508|<ul><li> [ ] #35459</li><li>[ ] #35867</li><li>[ ] #37328</li></ul>|

**Comment by blizzz** [comment]
## Required PRs:

* [ ] https://github.com/nextcloud/server/pull/38013
* [ ] https://github.com/nextcloud/server/pull/37734
* [ ] waiting for new nextcloud-vue release (delayed due to current github reliability issues)

**Pull request merged**
