### PR TITLE
fix Github link in Personal and Admin settings Version note

### PR DESCRIPTION
**Pull request by jancborchardt**
Seems we forgot to change one Github link. ;)

Please review @karlitschek @LukasReschke @MorrisJobke
Needs backport too.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by rullzer** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by LukasReschke** [comment]
👍

**Comment by MorrisJobke** [comment]
Backport is in #546

**Pull request merged**
