### PR TITLE
Fix install page

### PR DESCRIPTION
**Pull request by CarlSchwan**
- Use normal labels instead of hiding them
- Fix position of the eye button (this is still very hacky)
- Define width on the box and not on the text fields

This really needs to be ported to vue

image

Less likely to break stuff compared to #34197 as everything is prefixed with a class specific to the installer

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by szaimen — APPROVED** [review]
🐘

**Comment by PVince81** [comment]
it is likely that adding an "Oracle" option will shift the whole thing again, but not a big issue anyway

**Review by Pytal — APPROVED** [review]

**Comment by CarlSchwan** [comment]
ci failure unrelated

**Pull request merged**
