### PR TITLE
Clear appstore cache on version upgrade

### PR DESCRIPTION
**Pull request by rullzer**
* Add version to cached json
* Compare version
* Updated calls
* Updated tests

Fixes: #2666

### CODE REVIEW

**Comment by schiessle** [comment]
tested... works and code looks good 👍

**Review by schiessle — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]
Let's get this in for 12. I don't see a need to backport this though as this won't really have any effect until the next major release :)

**Comment by nickvergessen** [comment]
Well it helps for everyone updating from 10 to 11.0.1 directly. So I'd say please backport?

**Comment by schiessle** [comment]
Yes, I agree with @nickvergessen. Upgrading from 10 to 11 was the way I noticed the issue. I would suggest to backport it.

**Comment by MorrisJobke** [comment]
> Yes, I agree with @nickvergessen. Upgrading from 10 to 11 was the way I noticed the issue. I would suggest to backport it.

cc @karlitschek

**Comment by karlitschek** [comment]
good catch. please backport

**Comment by rullzer** [comment]
So after thinking about it more and discussing with @LukasReschke this actually doesn't fix #2666. Or well it does. but not on the upgrade from 10 to 11.

Since on 10 there was no new appstore. And thus also no cache. So on upgrade to 11 there is nothing cached. So @schiessle you must have hit a different bug.

Which means no need for a backport.

**Comment by LukasReschke** [comment]
Original issue sounds more like https://github.com/nextcloud/server/issues/2403 to me. 
@schiessle from what version did you update and whaz was the target version?

**Comment by MorrisJobke** [comment]
@rullzer @LukasReschke Bring this to 11.0.2 or wait for the next maintenance release or abandon the backport?

**Pull request merged**
