### PR TITLE
Min height 100% on content-wrapper

### PR DESCRIPTION
**Pull request by skjnldsv**
Make sure loaders or stuff are always taking full height on content-details as well :)

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Fixes my issue :+1:

**Comment by skjnldsv** [comment]
Failures unrelated. Want to restart the build @rullzer ?

**Comment by rullzer** [comment]
https://drone.nextcloud.com/nextcloud/server/9422

**Comment by ChristophWurst** [comment]
Failures look unrelated to me too

https://drone.nextcloud.com/nextcloud/server/9422/119

**Pull request merged**
