### PR TITLE
Update AppFrameworkTainter to use non-deprecated interface

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

Split out from https://github.com/nextcloud/server/pull/37390

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Early returns, maybe?

**Comment by provokateurin** [comment]
Yeah that would make the code more readable. I just adapted it to the new interface. I can add another commit to refactor it if you want

**Comment by nickvergessen** [comment]
> I can add another commit to refactor it if you want

sounds like a good idea

**Review by ChristophWurst — APPROVED** [review]
Best code I've seen today

**Comment by provokateurin** [comment]
Haha thank you :)

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
