### PR TITLE
Remove old hide modules option for webpack

### PR DESCRIPTION
**Pull request by ChristophWurst**
```
$ npm run build

> nextcloud@1.0.0 build /home/christoph/workspace/nextcloud
> NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js

[webpack-cli] Unknown argument: --hide-modules
? Which flags do you want to use? … 
✔ --entry: The entry point(s) of your application e.g. ./src/main.js
✔ --config: Provide path to a webpack configuration file e.g. ./webpack.config.js
✔ --color: Enable/Disable colors on console
✔ --merge: Merge two or more configurations using webpack-merge e.g. -c ./webpack.config.js -c ./webpack.test.config.js --merge
✔ --progress: Print compilation progress during build
✔ --help: Outputs list of supported flags
✔ --output-path: Output location of the file generated by webpack e.g. ./dist/
✔ --target: Sets the build target e.g. node
✔ --watch: Watch for files changes
✔ --hot: Enables Hot Module Replacement
✔ --devtool: Determine source maps to use
✔ --prefetch: Prefetch this request
✔ --json: Prints result as JSON or store it in a file
✔ --mode: Defines the mode to pass to webpack
✔ --version: Get current version
✔ --stats: It instructs webpack on how to treat the stats e.g. verbose
✔ --env: Environment passed to the configuration when it is a function
✔ --name: Name of the configuration. Used when loading multiple configurations.
✔ --config-name: Name of the configuration to use
✔ --analyze: It invokes webpack-bundle-analyzer plugin to get bundle information
```

Fixes @MorrisJobke's computer.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> Uncommited changes in webpack build

:eye: :lips: :eye:

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> Fixes @MorrisJobke's computer.

Finally no broken screen anymore 🚀

**Comment by MorrisJobke** [comment]
Not yet working 😢

**Comment by MorrisJobke** [comment]
> Not yet working 😢

See failed CI job for node.

**Pull request merged**
