### PR TITLE
Fix design and layout of notification mails

### PR DESCRIPTION
**Pull request by jancborchardt**
- Fix notification mails height issue in Nextcloud Mail → @Bables55 @alexanderdd please test this because it fixes the issue you reported at https://github.com/nextcloud/mail/issues/599 :)
- Adjust vertical spacing
- Logo bar/box to circle so it stands nicely on its own
- Change font to native font stack

Also is a step towards simplifying the email template as per https://github.com/nextcloud/server/issues/9119

Just a question: How best to trigger the mails for testing? So far I did it inline in the browser.

### Before
Notification mail old top
----------------------
**When reading notifications mails with the Mail app, you have to scroll down to see any content:**
Notification mail old bottom

### New
Notification mail new

### CODE REVIEW

**Comment by szaimen** [comment]
@jancborchardt I think it looks much better then before but I would center-align the activity notification if there is only one. It would look then like this:
image

**Review by ChristophWurst — APPROVED** [review]

**Comment by jancborchardt** [comment]
> I would center-align the activity notification if there is only one. It would look then something like this:

Sure – but let’s do it in a follow-up, already touched this beast enough for now. :) There’s plenty of other stuff to fix as well still.

**Review by GretaD — APPROVED** [review]

**Comment by ChristophWurst** [comment]
``Test\Mail\EMailTemplateTest`` fails

**Comment by jancborchardt** [comment]
> `Test\Mail\EMailTemplateTest` fails

So do I need to manually copy all the changes to:
- tests/data/emails/new-account-email.html
- tests/data/emails/new-account-email-custom.html
- tests/data/emails/new-account-email-single-button.html

Or is there a simpler way?

**Comment by kesselb** [comment]
Logo needs a lot of space now. For me it's to much present. That email should be about the activity and not the instance logo.

**Comment by jancborchardt** [comment]
> Logo needs a lot of space now. For me it's to much present. That email should be about the activity and not the instance logo.

I can reduce the padding a bit. Do you know something regarding my question on fixing the tests? :)

**Comment by kesselb** [comment]
**master**
Screenshot from 2020-04-14 17-03-36

**this pr**
Screenshot from 2020-04-14 17-03-21

The email settings test mail looks a bit broken.

**Comment by kesselb** [comment]
> Do you know something regarding my question on fixing the tests? :)

The tests compare the generated html with the one saved at `tests/data/emails/`. You may update the expected output there.

**Comment by jancborchardt** [comment]
Ok, so as asked I need to just manually copy it over into these files?

- tests/data/emails/new-account-email.html
- tests/data/emails/new-account-email-custom.html
- tests/data/emails/new-account-email-single-button.html
- apps/settings/tests/Mailer/NewUserMailHelperTest.php

Or is there a simpler way?

----------

As for the layout bug, I will remove that box-shadow – thanks for catching it!

**Comment by kesselb** [comment]
I'm not aware of a simpler way.

**Comment by simonspa** [comment]
> Logo needs a lot of space now. For me it's to much present. That email should be about the activity and not the instance logo.

I do like the large logo because in most cases these e-mails are received out-of-context (i.e. I'm not currently working on anything related to this cloud), so it sets the subject. Then, the details follow.

**Review by georgehrke — APPROVED** [review]

**Comment by georgehrke** [comment]
> As for the layout bug, I will remove that box-shadow – thanks for catching it!

Bump

**Comment by jancborchardt** [comment]
Rebased, removed the box-shadow, and fixed the tests. @georgehrke @kesselb @ChristophWurst

**Comment by jancborchardt** [comment]
The test `sudo NOCOVERAGE=1 ./autotest.sh sqlite tests/lib/Mail/EMailTemplateTest.php` passes locally, so I don’t understand why https://drone.nextcloud.com/nextcloud/server/28545/10/4 shows errors?

**Comment by kesselb** [comment]
@jancborchardt `OCA\Settings\Tests\Mailer\NewUserMailHelperTest` is the failing test. There is also some html markup to adjust.

**Comment by jancborchardt** [comment]
> @jancborchardt `OCA\Settings\Tests\Mailer\NewUserMailHelperTest` is the failing test. There is also some html markup to adjust.

How can I run this test locally? Sorry for the stupid questions, but the documentation was not very clear or gave me commands that didn’t work, and it’s not very obvious how to run the tests. (Also I’m a designer, not dev. ;)

**Comment by kesselb** [comment]
Good question. I think the same command as for the other test should work. 

The test is located here: apps/settings/tests/Mailer/NewUserMailHelperTest.php

**Comment by gary-kim** [comment]
Yeah, `NOCOVERAGE=1 ./autotest.sh sqlite apps/settings/tests/Mailer/NewUserMailHelperTest.php` will work.

**Comment by jancborchardt** [comment]
> The test is located here: apps/settings/tests/Mailer/NewUserMailHelperTest.php

Aaah ok, didn’t know it was somewhere else. :) Thank you both @kesselb @gary-kim! :)

**Comment by jancborchardt** [comment]
Aaand all tests fixed now! :) That is, both of these:
- `NOCOVERAGE=1 ./autotest.sh sqlite apps/settings/tests/Mailer/NewUserMailHelperTest.php`
- `NOCOVERAGE=1 ./autotest.sh sqlite tests/lib/Mail/EMailTemplateTest.php`

**Pull request merged**
