### PR TITLE
Allow automatic DI for the View

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @BernhardPosselt

### CODE REVIEW

**Comment by rullzer** [comment]
I still think we should use the Node API more. But admittedly this is not possible everywhere.

I had the discussion a bit with @BernhardPosselt where we do the DI of private classes. Still need to think about that a bit more and write it down somewhere.

**Comment by nickvergessen** [comment]
Well people use the view today, this here is just a matter of automating it...

**Comment by BernhardPosselt** [comment]
👍

**Comment by rullzer** [comment]
Yeah but it is also currently working. Adding this kind of legitimises the use of the view for Apps. Which is not really true. Apps should only use stuff from OCP

**Comment by LukasReschke** [comment]
I do second @rullzer

**Pull request closed without merging**
