### PR TITLE
Inidicate preview availability in share api responses

### LINKED ISSUE #14849: Border around mime icon in file list
image

Added by https://github.com/nextcloud/server/pull/14637 but we should limit this to the grid view only.

@nextcloud/designers

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #14849

The share api does not indicate if a preview is available for a share. This causes `data-has-preview="true"` for every entry in the share file list. The border around items without a preview is a consequence of this missing indication.

### CODE REVIEW

**Comment by st3iny** [comment]
@juliushaertl This PR is ready to be reviewed.

**Review by juliusknorr — APPROVED** [review]
Nice catch :+1:

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Nice!!

**Comment by skjnldsv** [comment]
Please rebase :)

**Comment by MorrisJobke** [comment]
> Please rebase :)

Done

**Comment by skjnldsv** [comment]
> /compile /

No, this goes in first https://github.com/nextcloud/server/pull/23323
PLease wait before compile

**Comment by skjnldsv** [comment]
@MorrisBot recreate

**Comment by skjnldsv** [comment]
Oh right,  no conflicts because that is only hanging apps/files_sharing/js/dist/files_sharing.js
Cool! LGTM then! :rocket:

**Comment by MorrisJobke** [comment]
PHUnit tests are broken:

```
There were 124 errors:
94	
95	1) OCA\Files_Sharing\Tests\Controller\ShareAPIControllerTest::testDeleteShareShareNotFound
96	ArgumentCountError: Too few arguments to function OCA\Files_Sharing\Controller\ShareAPIController::__construct(), 13 passed in /drone/src/apps/files_sharing/tests/Controller/ShareAPIControllerTest.php on line 151 and exactly 14 expected
```

**Comment by st3iny** [comment]
Oops ... Just saw the tests. I'm on it but fixing this might take some time.

**Comment by skjnldsv** [comment]
> but fixing this might take some time.

Take all you need, there is no rush :)

**Comment by st3iny** [comment]
I fixed all the existing tests by always expecting no preview and added an new test data set to `ShareApiControllerTest::testFormatShare` to test a file with a preview available (should return `has_preview=true`).

**Comment by skjnldsv** [comment]
`Lint / php-cs check` is failing

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
