### PR TITLE
Fix unresponsive legacy password confirmation dialog when another modal is open with new dialog in Vue

### PR DESCRIPTION
**Pull request by Pytal**
Without this the focus would remain on the previously opened modal and prevent confirmation of your password

Also improves accessibility

### Steps

1) Open user management page
2) Create a new user with the modal
3) Confirm your password

> The `appendChild` console error can be ignored and is fixed upstream in https://github.com/nextcloud/nextcloud-vue/pull/3219

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by ChristophWurst — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by PVince81** [comment]
```
error    Unable to resolve path to module '@nextcloud/password-confirmation/style.css'
```

**Comment by PVince81** [comment]
I'll investigate the issue

**Comment by PVince81** [comment]
very strange, compilation actually works and the dialog also works
it's only eslint that doesn't seem to be able to load the password-confirmation lib

**Comment by PVince81** [comment]
possibly https://stackoverflow.com/q/67648680

I also didn't find any other place where we'd be importing css modules from a non-local module.
Not sure if we should change it to `require()` now or something else.

**Comment by Pytal** [comment]
Analysis and upstream fix in https://github.com/nextcloud/nextcloud-password-confirmation/pull/393

Pending next package release to resolve all errors

**Pull request merged**
