### PR TITLE
Move server apps to dedicated autoloader

### PR DESCRIPTION
**Pull request by rullzer**
- [x] admin_audit
- [x] comments
- [x] dav
- [x] encryption
- [x] federatedfilesharing
- [x] federation
- [x] files
- [ ] files_external
- [x] files_sharing
- [x] files_trashbin
- [x] files_versions
- [x] lookup_server_connector
- [x] oauth2
- [x] provisioning_api
- [x] sharebymail
- [x] systemtags
- [x] testing
- [ ] theming
- [x] twofactor_backupcodes
- [x] updatenotification
- [x] user_ldap

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@rullzer could you add the CI checks for those apps as well (like we have for the core already)? 👍

**Comment by rullzer** [comment]
The check is already there @MorrisJobke :)

**Comment by rullzer** [comment]
Ok moving over the theming app is tricky because we do magic in Server.php

**Comment by rullzer** [comment]
files_external still needs the old autoloader

**Review by MorrisJobke — APPROVED** [review]
Tested, works and makes sense 👍

**Pull request merged**
