### PR TITLE
slight animation for the sidebar for better feedback what happens

### PR DESCRIPTION
**Pull request by jancborchardt**
Instead of just having the right sidebar appear out of nowhere, there’s now a small animation sliding in from the right. 200ms for sliding in, and a faster 100ms for sliding out when closing.

Please review @nextcloud/designers @nextcloud/javascript

### CODE REVIEW

**Comment by icewind1991** [comment]
It looks a bit weird atm since #app-content is resized immediately

**Comment by MorrisJobke** [comment]
Just to be aware of it: this causes JSUnit test failures:


..
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Files.FileList tests Details sidebar closes sidebar whenever the currently highlighted file was removed from the list FAILED
	Expected false to equal true.
	/drone/src/github.com/nextcloud/server/apps/files/tests/js/filelistSpec.js:2074:59
.
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Files.FileList tests Details sidebar closes the sidebar when switching folders FAILED
	Expected false to equal true.
	/drone/src/github.com/nextcloud/server/apps/files/tests/js/filelistSpec.js:2096:59

**Comment by MorrisJobke** [comment]
I like it 😄

**Comment by schiessle** [comment]
looks really nice :smile:

**Comment by mar1u5** [comment]
works with Safari 💪

**Comment by MorrisJobke** [comment]
> It looks a bit weird atm since #app-content is resized immediately

@jancborchardt Do we still want to get this in? Then I would try to fix the JS tests.

**Comment by jancborchardt** [comment]
@MorrisJobke I’d be grateful for that, yeah! My JS-fu ends somewhere here, but am learning! (See latest PR to the Mail app ;D)

**Comment by juliushaertl** [comment]
@jancborchardt shouldn't be that hard, would it be ok if i take over to animate the #app-content as well?

**Comment by jancborchardt** [comment]
@juliushaertl that would be very cool, thank you!

**Comment by juliushaertl** [comment]
Done. I've added the animation and fixed the tests as well.

@jancborchardt @MorrisJobke @icewind1991

**Comment by jancborchardt** [comment]
Awesome, good stuff as always @juliushaertl :+1: works like a charm

**Comment by jancborchardt** [comment]
@MorrisJobke @schiessle @mar1u5 we need additional reviews, and actual thumbs up ;)

**Comment by mar1u5** [comment]
Just wanted to test Edge ... then you get my thumb 😜

**Comment by mar1u5** [comment]
👍

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
