### PR TITLE
Use non-absolute logout URL to fix wrong URL in reverse proxy scenario

### LINKED ISSUE #13713: Redirecting bug since 15.0.2
Whenever a redirect happens, like from the `/apps/` to the `/apps/files/` path, NextCloud now redirects using the server provided hostname and port instead of the one requested by the client.

For instance, if running via Docker on `localhost:8000` and using a proxy pass with `cloud.example.com`, the address `cloud.example.com/apps/` will redirect to `localhost:8000/apps/files/`.

This happens with the `/` to `/login` redirect as well, so this bug completely prevents access to the instance from the web interface, unless you manually correct the URL afterwards.

Also discussed here: https://help.nextcloud.com/t/nextcloud-15-redirect-to-local-ip/45352

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #13713 

I tested it and it still works. Also the original introduction doesn't give any further details about this: https://github.com/owncloud/core/pull/24056

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
I get the fix. But this does't mean that people with reverse proxies should fix their setup

**Review by ChristophWurst — APPROVED** [review]
Fine by me

**Comment by ChristophWurst** [comment]
> I get the fix. But this does't mean that people with reverse proxies should fix their setup

:+1: seconded. I also saw reports for lots of wrongly set up instances behind reverse proxies with U2F and Mail because it's critical there.

Can we check that in the admin settings? As in, comparing the front-end host with an absolute URL from the back-end?

**Comment by MorrisJobke** [comment]
> Can we check that in the admin settings? As in, comparing the front-end host with an absolute URL from the back-end?

Sure. But let's unify this here. No need to make the URL absolute, because it is always shown within our user interface.

**Comment by MorrisJobke** [comment]
Unit tests fail. Let me check them.

**Comment by MorrisJobke** [comment]
> Unit tests fail. Let me check them.

Done.

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
