### PR TITLE
Add InitialState Appframework service

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:rocket:

**Comment by ChristophWurst** [comment]
> Lint / php-cs check

:eyes:

**Comment by MorrisJobke** [comment]
> Lint / php-cs check

I pushed a fix. :)

**Comment by ChristophWurst** [comment]
Pleaes use the docs label for changes like this so it's easier to compile the critical changes and upgrade docs for the next release :pray:

**Comment by skjnldsv** [comment]
Docs by Louis at https://github.com/nextcloud/documentation/pull/6952

**Pull request merged**
