### PR TITLE
chore: Bump @nextcloud/vue + @nextcloud/dialogs + @nextcloud/calendar-availability-vue

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Bump @nextcloud/vue + @nextcloud/dialogs + @nextcloud/calendar-availability-vue
- Adapt to breaking changes
- Fix acceptance tests

## To Do

- [x] Resolve bundler CI errors

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- Screenshots before/after for front-end changes
- Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by st3iny** [comment]
> ERROR in ./node_modules/@nextcloud/dialogs/dist/chunks/FilePicker-fe2ce33f.mjs 155:217-219
export 'NcDatetime' (imported as 'ee') was not found in '@nextcloud/vue'

It seems that dialogs (and probably any other dependency that makes use of `nextcloud/vue`) as well. It should be `NcDateTime`.

Ref https://github.com/nextcloud-libraries/nextcloud-vue/pull/4560

**Comment by ShGKme** [comment]
Both `@nextcloud/calendar-availability-vue` and `@nextcloud/dialogs` updates were published, so we can upgrade `@nextcloud/vue` now

**Review by ShGKme — APPROVED** [review]
🎉

**Review by JuliaKirschenheuter — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by ShGKme** [comment]
~~crying~~

Working under a fix for tests

**Pull request merged**
