### PR TITLE
Various user settings fixes

### LINKED ISSUE #18560: User management view: Stay usuable on smaller screen
### Steps to reproduce
1. Change resolution to 1440 (Laptop L chromium developer tools)
2. Enable at least one additional column (eg. user backend)
3. Try to edit a user

nextcloud test_settings_users (1)

nextcloud test_settings_users (2)

### Expected behaviour

I can click the edit button without using the arrow keys

### Actual behaviour

I need to use the arrow keys to make the edit button visible

### LINKED ISSUE #18920: Group list is overlapping if you are part of too many groups
Bildschirmfoto von 2020-01-16 09-46-57

cc @GretaD

### LINKED ISSUE #19503: Users Page - Dropdown menu issue
### Steps to reproduce
1. Goto users page.
2. Click on any user's storage quota dropdown.
3. The list comes beneath the info of other users so you cannot select options from dropdown menu.

### Expected behavior
Normally the list should allow selecting options from it.

### Actual behaviour
As the list is placed beneath the text of other user's information, it is not possible to select an option.

### Server configuration

**Operating system:** Ubuntu Server 18

**Web server:** Amazon EC2

**Database:** MySQL 5.7

**PHP version:** PHP 7.3

**Nextcloud version:** 18.0.1 Build:2020-02-15T23:01:50+00:00 e092141b6e03d35ccdc4b523b2ca99a775b79f93

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from : ** SNAP Repository

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

  'secret' => ,
  'trusted_domains' =>
  array (
    0 => ,
  ),
  'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '18.0.1.3',
  'overwrite.cli.url' => ,
  'dbname' => ,
  'dbhost' => 'localhost:/tmp/sockets/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => ,
  'dbpassword' => ,
  'installed' => true,
  'app_install_overwrite' =>
  array (
    0 => 'admin_notifications',
    1 => 'dashboard',
    2 => 'printer',
  ),
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' =>
  array (
    0 => 'admin',
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
  ),
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...  NO

**Are you using encryption:** yes/no   NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...   NO

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10 Professional

error

### LINKED ISSUE #19513: users page: long usernames overflow into display name
Long usernames overflow into the display name, at least when additional columns like "show storage location" or "show last login" are activated and each column gets less space:

image

NC 18.0.1

ref (but no dup): https://github.com/nextcloud/server/issues/18158

### PR DESCRIPTION
**Pull request by juliusknorr**
- Give columns a bit more space and fix overlaying issues
- Show user/displayname when backend does not offer saving
- Do not overlay single select boxes over userActions
- Add tooltip to storage location
- Properly position popovermenu for user actions

Fixes https://github.com/nextcloud/server/issues/19503
Fixes https://github.com/nextcloud/server/issues/18920
Fixes https://github.com/nextcloud/server/issues/18560
Fixes https://github.com/nextcloud/server/issues/19513

image

The grid view is still a pain to get properly here, but i think most urgent issues should be fixed by that PR.

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
Action menu stays open after you try to delete/wipe/disable a user, but we can fix that with another PR. Lets merge this one.
Everything else looks good. Great work! Thank you Julius.

**Review by ChristophWurst — APPROVED** [review]

**Comment by wiswedel** [comment]
Great set of fixes. Can we backport them to 18?

**Comment by ankurghai** [comment]
> Great set of fixes. Can we backport them to 18?

I think these are for 18.

**Comment by juliushaertl** [comment]
> Can we backport them to 18?

Yes, definitely.

> I think these are for 18.

The master branch is already heading towards Nextcloud 19. Fixes for upcoming 18 releases need to be backported to the stable18 branch.

**Comment by kesselb** [comment]
nextcloud test_settings_users (4)

The row is very high with a few users ;)

**Comment by rollanders** [comment]
I cannot use NC18 because of these issues. I cannot add new users as I cannot change their group permissions or quotas.

**Comment by alexanderdd** [comment]
I think it is very important to backport to 18.0 and 18.1? Cause these releases have a non-usable interface, it is not possible to add/remove users to/from groups. Really bad IMHO.

**Comment by rollanders** [comment]
Agree. I did a similar comment which was marked as spam. I am waiting for 18.0.2 before upgrading the production server. Hope it has been fixed in that version.

**Pull request merged**
