### PR TITLE
Clear comment on successful post

### LINKED ISSUE #19585: entering file comments does not clear the input field
### Steps to reproduce
1. open NC in file view
2. on any file, press the 3 dots to show extra options
3. select (i) details
4. enter a comment in the comment field and press enter (or click the arrow)
5. observe that the comment field is not cleared. The same comment can be entered by pressing the arrow)

### Expected behaviour
After a comment, the input field should be cleared.

### Actual behaviour
The input field is not cleared.
image

### Server configuration

**Operating system:**
Linux

**Web server:**
Nginx

**Database:**
Mysql

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
19.0.0 alpha

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - lookup_server_connector: 1.7.0
  - mail: 1.1.2
  - oauth2: 1.7.0
  - provisioning_api: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - systemtags: 1.9.0
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - contacts
  - encryption
  - files_external
  - testing
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.sanderr.dev"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.0",
        "overwrite.cli.url": "https:\/\/nc.sanderr.dev",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

### Client configuration
**Browser:**
Opera

**Operating system:**
Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
N/A
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
n/a
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Request URL: https://nc/remote.php/dav/comments/files/7/
Request Method: POST
Status Code: 201 Created
Remote Address: [::1]:443
Referrer Policy: no-referrer-when-downgrade
{"actorType":"users","objectType":"files","actorId":"admin","actorDisplayName":"admin","verb":"comment","message":"comment","creationDateTime":"Sat, 22 Feb 2020 16:36:47 GMT"}
```
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #19585

### CODE REVIEW

**Comment by skjnldsv** [comment]
Easy review folks!

**Review by georgehrke — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
backport in https://github.com/nextcloud/server/pull/20382

**Pull request merged**
