### PR TITLE
make the share icon in the filelist visible again

### LINKED ISSUE #2277: Sharing icon seems missing
Is it intended that no sharing icon is shown anymore in the three dot menu or elsewhere? The DOM has it but I don't happen to see it on master.

cc @jancborchardt 

screen shot 2016-11-23 at 14 21 20
screen shot 2016-11-23 at 14 22 50

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #2277

cc @LukasReschke

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]
LGTM

**Comment by LukasReschke** [comment]
Works fine LGTM

**Comment by skjnldsv** [comment]
:+1:

**Comment by MorrisJobke** [comment]
The hover style doesn't work anymore - I will fix this in here too.

**Comment by MorrisJobke** [comment]
Tested and works now 👍 

The style is now darker when hovered/focused and existing shares are also darker. Also when hovering the menu icon it's shown darker. ;)

**Comment by jancborchardt** [comment]
Thanks, that was of course not intentional. :D Thought it was an Adblock plus thing again initially.

**Comment by skjnldsv** [comment]
@jancborchardt We all know you dit it! Don't lie!

**Comment by jancborchardt** [comment]
@skjnldsv maybe it’s time to start using PhantomCSS or smth like that https://css-tricks.com/visual-regression-testing-with-phantomcss/ :D

**Comment by skjnldsv** [comment]
Isn't there too much hidden stuff on nextcloud to implement this?

**Comment by jancborchardt** [comment]
Probably yes – all these visual CI systems seem to be mainly for static websites without much JS or interactivity. :\

**Pull request merged**
