### PR TITLE
[stable23] Use npm ci when running JS tests

### PR DESCRIPTION
**Pull request by PVince81**
Manual backport of https://github.com/nextcloud/server/pull/30567 to stable23.
Ran "npm i" again to update the lock file, and recompiled the assets.

### CODE REVIEW

**Comment by PVince81** [comment]
some complications :-/

I'll have a look.

**Comment by eneiluj** [comment]
Can we run those test locally only by running `autotest-js.sh`?
I get this on `master` and `bugfix/noid/npm-ci-for-karma/stable23` branches:
```
1) generates plural with default function when no forms specified
     OC.L10N tests plurals
     Expected '0 Datei herunterladen' to equal '0 Dateien herunterladen'.
    at checkPlurals (core/js/tests/specs/l10nSpec.js:74:6)
    at Object.<anonymous> (core/js/tests/specs/l10nSpec.js:109:4)
```

**Comment by PVince81** [comment]
> Can we run those test locally only by running `autotest-js.sh`? I get this on `master` and `bugfix/noid/npm-ci-for-karma/stable23` branches:
> 
> ```
> 1) generates plural with default function when no forms specified
>      OC.L10N tests plurals
>      Expected '0 Datei herunterladen' to equal '0 Dateien herunterladen'.
>     at checkPlurals (core/js/tests/specs/l10nSpec.js:74:6)
>     at Object.<anonymous> (core/js/tests/specs/l10nSpec.js:109:4)
> ```

yes you can.

and I'm sad to see that you're getting even different errors that I see locally :cry:

**Comment by artonge** [comment]
> Can we run those test locally only by running `autotest-js.sh`?

They have to be run with npm 6.

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
