### PR TITLE
[stable29] fix(files): undefined displayname for outdated `@nextcloud/files`<3.6.0 apps

### PR DESCRIPTION
**Pull request by skjnldsv**
## How to reproduce

1. on stable29, create a new document
2. enter the name
3. document opens
4. close office app
5. filelist show empty file in row and errors
image

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by skjnldsv** [comment]
let's wait for https://github.com/nextcloud/server/pull/47747

**Pull request merged**
