### PR TITLE
Fix parsing of language code

### LINKED ISSUE #20453: Plural translations don't seem to work
### Steps to reproduce
1. Inside the server, set the language to a translation, for example, Spanish Argentina
2. Find some plural translations. For example the summary of the current folder.
3. Just check if the plural works.

### Expected behaviour
In summary expect:
> 6 carpetas y 5 archivos 	8,5 GB

### Actual behaviour
In summary i see:

> 6 carpeta y 5 archivo 	8,5 GB

imagen
:disappointed: 

Note that the translation is programmed correctly:

https://github.com/nextcloud/server/blob/2b913de41706aae531d476d80f64c4fd2fd91b92/apps/files/js/filesummary.js#L223-L226

..and also is translated.

https://github.com/nextcloud/server/blob/df463f90be01be2d38f6cdd5b2b1a20900696b54/apps/files/l10n/es_AR.js#L61-L62

But use the singular, with the number greater than 1. 

## Server configuration detail

**Operating system:** Linux 5.5.10-200.fc31.x86_64 #1 SMP Wed Mar 18 14:21:38 UTC 2020 x86_64

**Webserver:** Apache/2.4.43 (Fedora) OpenSSL/1.1.1d (fpm-fcgi)

**Database:** mysql 10.3.22

**PHP version:** 

7.3.16
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, imagick, msgpack, pcov, pdlib, smbclient, zip, redis, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.2 - 18.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```

```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

### PR DESCRIPTION
**Pull request by kesselb**
Fix #20453

image

https://github.com/nextcloud/server/blob/677d4bfbf017b5f6cdb04659aa4f11baf37e090d/core/src/OC/l10n.js#L333-L338

OC.getLanguage() uses the html property `lang`.

https://github.com/nextcloud/server/blob/cbd20867b59779d7aff5a024e4287206e3c028e0/lib/private/TemplateLayout.php#L158-L159

https://github.com/nextcloud/server/blob/72b8083c11e8a406f585e13a4312438d88d8da53/core/templates/layout.base.php#L2

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:see_no_evil:

**Review by MorrisJobke — APPROVED** [review]
Nice finding 👍

**Comment by MorrisJobke** [comment]
Webpack CI job fails

**Comment by MorrisJobke** [comment]
Amend failed :/

**Review by juliusknorr — APPROVED** [review]
Works, was also the case for formal german

**Comment by kesselb** [comment]
> Amend failed :/

Rebased and recompiled.

**Comment by rullzer** [comment]
and rebase :S

**Comment by kesselb** [comment]
> and rebase :S

Not again :)

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
