### PR TITLE
fix look of personal global credentials settings

### LINKED ISSUE #41614: [Bug]: External storage settings layout is mixed emptycontent + actual interface
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The current external storage emptycontent view is a bit messy. It sort of looks like a combination of an emptycontent view and an actual settings view:
image

### Steps to reproduce

1. Have no external storages in your Nextcloud
2. Open the external storage settings

### Expected behavior

Have a nice emptycontent view while it is clear what to do next. For example by having the "Global credentials" behind a button like this (or with a primary button, couldn’t get components to work here):

image

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/41614

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Review by marcoambrosini — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/pull/42058

**Pull request merged**
