### PR TITLE
perf(workflowengine): Cache query that is performed on every request

### PR DESCRIPTION
**Pull request by juliusknorr**
This will save a query for available workflow engine events. The query itself is also not optimal as it does a not equal check on a text field which cannot use an index, however using caching is probably the easiest for now.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by blizzz** [comment]
labels?

**Review by blizzz — APPROVED** [review]

**Comment by juliushaertl** [comment]
Sorry, laggy wifi lost them it seem.

**Comment by blizzz** [comment]
Could add test conditions that cache is read, set and unset.

**Review by nickvergessen — APPROVED** [review]
Had that one on my Todo as well for way too long.

**Review by come-nc — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Could add test conditions that cache is read, set and unset.

@juliushaertl you are up for that? *cough*

**Comment by juliushaertl** [comment]
Added and also covered getAllConfiguredEvents with a test now.

**Comment by juliushaertl** [comment]
Failure unrelated

**Pull request merged**
