### PR TITLE
Fix search ordering

### PR DESCRIPTION
**Pull request by icewind1991**
- [x]  Requires https://github.com/nextcloud/3rdparty/pull/41

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by icewind1991** [comment]
@mario @rullzer please review

**Comment by mario** [comment]
👍  If it works, I approve :)

**Review by mario — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I updated the 3rdparty module

**Pull request merged**
