### PR TITLE
[stable10] Add feedback for password change

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #978 

Second commit is not necessary

@mar1u5 @LukasReschke

### CODE REVIEW

**Comment by mar1u5** [comment]
> Second commit is not necessary

Why not?! We have Password Policy also in `stable9` and `stable10`. @nickvergessen

**Comment by nickvergessen** [comment]
@mar1u5 because in stable10 and stable9 the ajax endpoint already translates the hint exception to a json response, this was basically a regression from "moving change password to a controller"

**Comment by rullzer** [comment]
:+1:

**Comment by mar1u5** [comment]
Works :+1:

**Pull request merged**
