### PR TITLE
Remake profile picture saving with Vue

### PR DESCRIPTION
**Pull request by Pytal**
Remake profile picture saving with Vue for accessibility purposes

Legacy code is removed

- `OC.Settings.updateAvatar` is dropped and is an API break but low impact as it is [unused](https://github.com/search?q=org%3Anextcloud+OC.Settings.updateAvatar&type=code)
- Drop deprecated [@nextcloud/jcrop](https://www.npmjs.com/package/@nextcloud/jcrop) dependency

### Screenshots

Before | After
--- | ---
image | image
image | image

### CODE REVIEW

**Comment by Pytal** [comment]
The cropper part was put inline in the page to be inline edited like other fields but we can put it back in a modal like before if desired @jancborchardt @nimishavijay?

**Review by CarlSchwan — APPROVED** [review]

**Comment by skjnldsv** [comment]
> The cropper part was put inline in the page to be inline edited like other fields but we can put it back in a modal like before if desired @jancborchardt @nimishavijay?

Not sure we gain that much to be in a modal? Maybe just a little more focus? I think it's fine both ways, so if it's technically easier inline, so be it.
But since this is design let's still wait for the design team confirmation :)

**Comment by Pytal** [comment]
Rebased

> Not sure we gain that much to be in a modal? Maybe just a little more focus? I think it's fine both ways, so if it's technically easier inline, so be it.

Not necessarily technically easier just that editing stuff inline in the same place that it's displayed seems more intuitive, other than that don't have a strong leaning either way

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Integration is failing 
https://drone.nextcloud.com/nextcloud/server/22585/22/3

**Review by CarlSchwan — APPROVED** [review]

**Comment by Pytal** [comment]
Rebased

**Comment by Pytal** [comment]
If there are any further changes we should make @jancborchardt @nimishavijay just ping here

**Pull request merged**
