### PR TITLE
Fix label for allow download share permission

### PR DESCRIPTION
**Pull request by juliusknorr**
Maybe I missed parts of the discussion on this, but couldn't see anything in the original PR.

The permission flag will allow or deny download on any filetype, therefore it doesn't make sense to limit the label to office files for shared folders.

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]
/compile amend /

**Comment by juliushaertl** [comment]
@CarlSchwan Probably can be cherry-picked directly to https://github.com/nextcloud/server/pull/33416

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
