### PR TITLE
the user always may modify their additional emails

### PR DESCRIPTION
**Pull request by blizzz**
`allow_user_to_change_display_name` is supposed to only lock the display name and system mail address.

### CODE REVIEW

**Review by szaimen — COMMENTED** [review]
I suppose after this change is there no way anymore to disable changing mail addresses?

**Review by julien-nc — APPROVED** [review]
> `allow_user_to_change_display_name` is supposed to only lock the display name and system mail address.

I trust you on that even if it's kind of strange that is has an effect on the system mail address.

Code looks good.

**Comment by blizzz** [comment]
> I trust you on that even if it's kind of strange that is has an effect on the system mail address.

yeah the name of this setting is misleading

**Comment by blizzz** [comment]
> I suppose after this change is there no way anymore to disable changing mail addresses?

The system email address maybe changed or not. Either by this configuration flag (`allow_user_to_change_display_name`), or mails from LDAP are read only, for instance. 

But the additional email addresses work independent from it, are user controlled and can always be set. The latter was not possible for it was part of that generic if-statement.

**Comment by szaimen** [comment]
> > I suppose after this change is there no way anymore to disable changing mail addresses?
> 
> The system email address maybe changed or not. Either by this configuration flag (`allow_user_to_change_display_name`)

Fine by me then 👍

**Review by szaimen — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Pull request merged**
