### PR TITLE
Remove old button to submit the apppassword login

### LINKED ISSUE #12404: Weblogin: strange submit button
Please see this video: https://cloud.nextcloud.com/s/mzESF9wXNsdwZSM

Happens on NC15 beta1 and NC master.

### PR DESCRIPTION
**Pull request by skjnldsv**
@nextcloud/designers 
Fix #12404 

Basically we now have this step before that have this 'Grant access' button, so we do not need to submit anything again :)

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Review by MorrisJobke — DISMISSED** [review]
Seems to cause issues ...

**Review by tobiasKaminsky — COMMENTED** [review]
:+1:

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@schiessle Could you test this with SSO?

**Pull request merged**
