### PR TITLE
fix(settings): Add back create group icon

### PR DESCRIPTION
**Pull request by Pytal**
## Resolves

- Regression of https://github.com/nextcloud/server/pull/44092

Before | After
--- | ---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by Pytal** [comment]
/backport e6b57e076d7f4af2dfcb1a21c209f4af41611428 to stable20

**Comment by Pytal** [comment]
/backport e6b57e076d7f4af2dfcb1a21c209f4af41611428 to stable30

**Comment by Pytal** [comment]
/backport e6b57e076d7f4af2dfcb1a21c209f4af41611428 to stable29

**Comment by Pytal** [comment]
> /backport [e6b57e0](https://github.com/nextcloud/server/commit/e6b57e076d7f4af2dfcb1a21c209f4af41611428) to stable30

Seems commit backports are being ignored @skjnldsv ?

**Pull request merged**
