### PR TITLE
When logged in then just redirect to redirected page

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/nextcloud/server/issues/754

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice, finally fixes the issue! :) :+1: 

@raghunayyar @MorrisJobke @AndyScherzinger  you reacted to the original post, mind giving it a review? ;)

**Comment by MorrisJobke** [comment]
Tested and works 👍 

Code makes sense

**Comment by MorrisJobke** [comment]
@LukasReschke @karlitschek Backport to stable10?

**Comment by AndyScherzinger** [comment]
Looks good :+1:

**Comment by jancborchardt** [comment]
@karlitschek @LukasReschke I would really like a backport of this to stable10 as it is quite a technical and annoying issue.

**Comment by karlitschek** [comment]
absolutely. please backport

**Comment by jancborchardt** [comment]
Backport at https://github.com/nextcloud/server/pull/858

**Pull request merged**
