### PR TITLE
improve status modal

### PR DESCRIPTION
**Pull request by szaimen**
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=enh/noid/improve-status-modal \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Super nice, looks much better!

**Comment by szaimen** [comment]
⚙ failure unrelated

**Pull request merged**
