### PR TITLE
Make user list pagination more tolerant

### LINKED ISSUE #25442: Pagination issues in user list with multiple backends
### Steps to reproduce
Note: this was reported to me so I'm only guessing the steps

1. Have a LDAP server with more than 30 users
2. Have two local users
3. Setup LDAP to have the users in NC
4. Go to the users page
5. Try scrolling down
6. Inspect the "/details?offset=0&limit=25" network call

### Expected result
The network call must return exactly 25 results.
The UI allows for scrolling down to load further pages.

### Actual result
The network call returned 28 results.
The UI doesn't allow for scrolling down any more and believes that there are no further results.

### Version
NC 20.0.5

### Analysis

There are two bugs here.

#### Backend bug

The code path of the backend goes to the provisioning API and reaches the UsersController which in turn calls the UserManager->search() method with offset and limit.

The UserManager doesn't properly handle pagination across multiple user backends. It simply calls `getUsers()` on each backend with the same offset and limit.

See https://github.com/nextcloud/server/blob/v20.0.5/lib/private/User/Manager.php#L262

This will cause more than the limit (here 25) to be returned.

#### Frontend bug

The frontend uses the following approach to find out whether it should load additional results: https://github.com/nextcloud/server/blob/v20.0.5/apps/settings/src/store/users.js#L240

Here it verifies whether the number of results is **exactly** the same as the limit.
So if there are more users than the limit it also considers that there aren't any more.

### Possible fixes

As a quickfix, I suggest to look at all occurrences of the "Frontend bug" where `.length === limit` is used and replace it to `.length >= limit` to at least allow for scrolling further, despite the clumsy backend.

Please note that fixing the backend isn't trivial at all as it might require adding more stages, like merging the user list into a single list and paginate on that, with a higher risk of inconsistencies when going to page 2, etc. So probably not something for a quick fix.

### PR DESCRIPTION
**Pull request by PVince81**
In case the server returns more results than expected by the limit, it
is now still interpreted as there being more results to query.

This situation can happen when there are multiple user backends in
place.

Fixes https://github.com/nextcloud/server/issues/25442

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant:

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
@PVince81 rebase

**Comment by PVince81** [comment]
I'll solve this

**Pull request merged**
