### PR TITLE
Fix edit tag textbox size

### LINKED ISSUE #7586: Rename tag textbox too big
### Steps to reproduce
1. Add a tag to a file
2. Edit the tag from the tag auto complete

### Expected behaviour
The textbox should fit into the autocomplete selection box.

### Actual behaviour
The textbox is too big for the  autocomplete selection box.

### Server configuration

**Nextcloud version:** Nc 13 beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** from git

### Client configuration
**Browser:** FF 57

**Operating system:** Windows 10

tags

### PR DESCRIPTION
**Pull request by AasthaGupta**
Fixes #7586

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@AasthaGupta Could you open a backport PR with the commit cherry picked against stable12 and stable13? Thanks :)

**Comment by AasthaGupta** [comment]
@MorrisJobke Can you guide me with how to open a backport PR??

**Comment by danxuliu** [comment]
@AasthaGupta This is how I do them (command line examples; if you use a GUI you will have to _translate_ them to it ;-) ):
- First I checkout the branch I want to backport; in this case, `git checkout devgals`
- Then I create a new branch, which is the one that will be backported; I usually use _stableXX-YYY-original-branch-name_, where _XX_ is the version and _YYY_ the original pull request (but that is just how I name them; others use different schemes). In this case, `git checkout -b stable13-8376-devgals`
- Now I rebase onto the _stableXX_ branch with `git rebase --onto stableXX commit-where-my-branch-diverged-from-its-parent-branch stableXX-YYY-original-branch-name`; in this case `git rebase --onto stable13 HEAD~1 stable13-8376-devgals`. `HEAD~1` means _1 commit back from the tip of the current branch_; the number of commits to go back would be the number of commits in your branch. Instead of `HEAD~ZZZ` you could also use an explicit commit ID, in this case, cd2e5b549c882473eef74b759b0e3f6af0acb3a8
- Depending on the changes the commits will be applied cleanly on the _stableXX_ branch, or conflicts may need to be fixed; follow Git instructions in that case ;-)
- Time to test to ensure that everything works as expected in the _stableXX_ branch
- Finally, I push the branch to the server and I create a new pull request named _[stableXX] Name of the original pull request_ and with text _Backport of #YYY_; in this case, _[stable13] Fix edit tag textbox size_ and _Backport of #8376_. And done :-)

**Comment by AasthaGupta** [comment]
@danxuliu Thanks a lot :)

**Comment by danxuliu** [comment]
@AasthaGupta You are welcome, and thanks for the fix :-)

**Pull request merged**
