### PR TITLE
Correctly log failed attempts

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Federation tests pass when rebasing on https://github.com/nextcloud/server/pull/32847

**Review by CarlSchwan — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by PVince81** [comment]
failure unrelated, merging (failure is handled in #32847)

**Pull request merged**
