### PR TITLE
Fix Error: Call to a member function instanceOfStorage() on null #10316

### LINKED ISSUE #10316: Error: Call to a member function instanceOfStorage() on null
### Steps to reproduce

`sudo -u www-data php occ files:scan --all`

### Expected behaviour

No exception.

### Actual behaviour

An unhandled exception has been thrown:
Error: Call to a member function instanceOfStorage() on null in /var/www/html/apps/files_sharing/lib/Cache.php:81

### Server configuration

Official docker image: nextcloud:13.0.4-apache

Related PR: Fix Error: Call to a member function instanceOfStorage() on null #10315

### PR DESCRIPTION
**Pull request by ranqiangjun**
Fixes #10316

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Thanks for the contribution. @icewind1991 @schiessle @rullzer Could you have a look at this?

**Comment by rullzer** [comment]
I'm a bit puzzled as to why this could be null.

@icewind1991 any idea?

**Comment by blizzz** [comment]
you don't have a backtrace for that error, by chance?

**Comment by jospoortvliet** [comment]
Hi guys,

wouldn't it be good to get this in 14 in any case? Note that this had to do with a migration from oC - no reason not to make that smoother :smile:

**Comment by blizzz** [comment]
@jospoortvliet this hides the symptom, but does not fix (or at least explain) the cause. Therefore @rullzer's and my questions.

**Comment by MorrisJobke** [comment]
To trace the issue following patch can be used: https://github.com/nextcloud/server/issues/10316#issuecomment-426350329


This PR only hides the problem but does not fix it thus I will close it. Thanks for the help nevertheless.

**Pull request closed without merging**
