### PR TITLE
Rename personal Groupware settings section to "Availability"

### PR DESCRIPTION
**Pull request by ChristophWurst**
As discussed internally.

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by tcitworld** [comment]
There's a number of calendar-related settings that should come to this section in the future: https://github.com/nextcloud/server/pull/33397 https://github.com/nextcloud/calendar/pull/4310.

These are really unrelated to availability, so it wouldn't make much sense to rename it afterwards. Should they use another section?

**Comment by ChristophWurst** [comment]
> Should they use another section?

I would say so

**Review by nickvergessen — APPROVED** [review]

**Comment by ChristophWurst** [comment]
I scanned our own apps for settings sections that rendered on the old *groupware* page. If there are any other apps that make use of the section then the backport will break them.

**Comment by AndyScherzinger** [comment]
@ChristophWurst so for the backport we could the just do the label and icon change but not the file renames? Or is the issue with the label too?

**Comment by ChristophWurst** [comment]
> @ChristophWurst so for the backport we could the just do the label and icon change but not the file renames? Or is the issue with the label too?

There is a human readable label that we can change. We can leave the code label to "groupware". The only strange situation we could create is that groupware-related settings would show in "Availability".

This is also the reason why I've added the documentation label. We have to warn app devs about this change in 26.

**Review by jancborchardt — APPROVED** [review]

**Comment by jancborchardt** [comment]
> There's a number of calendar-related settings that should come to this section in the future: https://github.com/nextcloud/server/pull/33397 https://github.com/nextcloud/calendar/pull/4310.
> These are really unrelated to availability, so it wouldn't make much sense to rename it afterwards. Should they use another section?

Thanks for pointing these out – FYI the first one should be in Calendar rather than Personal settings, and the second one shouldn’t be a setting but automatic. I commented on both to that effect. :)

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Makes sense and due to @ChristophWurst comment about app devs I think it makes sense to start a ticket to track any app changes relevant for communication to app devs right away, just to have it in place right from the start of v26

**Review by tcitworld — CHANGES_REQUESTED** [review]
EDIT: oops, confused admin sections with personal sections

**Review by tcitworld — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Documented at https://github.com/nextcloud/documentation/pull/9249

**Pull request merged**
