### PR TITLE
Fixed Bug with Background Color in some Menus like 2FA

### LINKED ISSUE #18077: two factor login color issue with bright colors (theming)
### Steps to reproduce
1. set a bright color in the theming app (e.g. #ffac00)
2. enable two factor auth for a user
3. login as this user

### Expected behaviour
Login looks like this:
nc-twofactor-light-background

### Actual behaviour
Login should look like this:
nc-twofactor-light-background-readable

### Cause of the Problem:
https://github.com/nextcloud/server/blob/3860373fd42091790ac2b00039cccd22e59d0ea5/apps/theming/css/theming.scss#L181

I've deleted this line for my instance. I haven't found any problems yet.

cc @juliushaertl @MorrisJobke

### PR DESCRIPTION
**Pull request by JanDragon**
Fix #18077 

Signed-off-by: Jan-Laurin Frey  <janlaurinfrey@gmail.com>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
@JanDragon could you show before/after screenshots? Neither "Expected behavior" nor "Actual behavior" in the issue at https://github.com/nextcloud/server/issues/18077#issue-527264857 look good.

How it should be:
- Dark slightly transparent background, regardless of theming color
- White text
- White icons

**Comment by ChristophWurst** [comment]
> @JanDragon could you show before/after screenshots? Neither "Expected behavior" nor "Actual behavior" in the issue at [#18077 (comment)](https://github.com/nextcloud/server/issues/18077#issue-527264857) look good.

:ping_pong:

**Review by jancborchardt — APPROVED** [review]
Only looking at the code this seems fine, as the color of `.body-login-container`should indeed not be modified through theming.

**Comment by skjnldsv** [comment]
@JanDragon any news?

**Comment by MorrisJobke** [comment]
fixed via #21988

**Pull request closed without merging**
