### PR TITLE
Add attribute “tabindex” to login form (fixes #1110)

### LINKED ISSUE #1110: Tabindex of login form inputs
The current login form does not specify any [tabindex](http://www.w3schools.com/tags/att_global_tabindex.asp) attribute. The tab order is therefore “username”, “password”, “submit”, “stay logged in”.

Wouldn’t it be better to have the “submit button” as last tab index so that the final order would be “username”, “password”, “stay logged in”, “submit”?

### Steps to reproduce
1. Navigate to server login page in a webbrowser
2. Use tab-key on your keyboard

### Expected behaviour
Order of selected fields is expected to be “username”, “password”, “stay logged in”, “submit”.

### Actual behaviour
Order of selected fields is currently “username”, “password”, “submit”, “stay logged in”.

### Server configuration
**Nextcloud version:** 10.0

### Client configuration
**Browser:** Epiphany 3.20.3
**Operating system:** Arch Linux

### PR DESCRIPTION
**Pull request by coderkun**
Implement #1110: “tabindex” for login form.

### CODE REVIEW

**Comment by rullzer** [comment]
CC: @nextcloud/designers

**Comment by rullzer** [comment]
@coderkun thanks a lot for your PR!
I've pinged our designers to have a look.

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by rullzer** [comment]
LGTM!

**Comment by rullzer** [comment]
Thanks a lot @coderkun :rocket: 
Feel free to join our [IRC](https://webchat.freenode.net/?channels=nextcloud-dev) and [Forum](https://help.nextcloud.com)

**Comment by MorrisJobke** [comment]
@coderkun Maybe give some starter issues a try: https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aopen+label%3A%22starter+issue%22 🙌

**Comment by coderkun** [comment]
@MorrisJobke @rullzer thanks for testing and merging. @MorrisJobke not enough time currently.

**Pull request merged**
