### PR TITLE
fixes possible override of uniqueMember by autodetection

### LINKED ISSUE #12682: group-user association attribute changed after click on "count groups"
In the LDAP configuration, the user-group-association is set on uniqueMember (the default). Also available is "memberUid", which has downsides. Groups are checked and available.

After a while revisit the configuration. When you click on “Count Groups”, it kicks off the detection of the association attribute (when it is set to default, which happens to be uniqueMember). If the more or the same amount of users (→ sorting) are returned for both attributes, memberUid will be used instead of uniqueMember. 

It should not change in this case.

From https://help.univention.com/t/nextcloud-13-group-sync-issues/10337

### PR DESCRIPTION
**Pull request by blizzz**
* uniqueMember was the default so we did not know whether this setting is
  desired or the initial value
* autodetection of the user-group association attribute runs only when it
  was not set (as far as we knew)
* the default is now empty
* thus LDAPProvider might return this value as well (in exceptional cases)
* if a group base is given (edge case), use this instead of general base
* resolves #12682

It changes behaviour  a bit:
* previously "uniqueMember" was the default and any LDAP config would work OOTB without hitting the test button after configuring groups. `uniqueMember` is not so common, and neither is not hitting "count groups". Imho, only impact for auto-installations were the attribute is not set specifically.
* LDAPProvider can – in edge cases – return '' next to the known attributes

I would say it is still OK to backport… more to the rules is to keep for 17 only though. The impact is small and rather beneficial.

# What's left

*  [x] fix integration tests

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code change makes sense 👍

**Review by rullzer — APPROVED** [review]
I could not test. But it makes some sense to me with my limited LDAP knowledge

**Comment by blizzz** [comment]
Still unsure about the backports. It's not the proper way.

**Comment by blizzz** [comment]
Let's leave it for 17. I'll just respond it's fixed but not backportable since default values change.

**Pull request merged**
