### PR TITLE
Update dashboard icon

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Resolves: none

## Summary

replace icon with the exact sizes of other icons, like activity, so the original viewport size matches height/width, to be rendered more crisp

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by susnux** [comment]
@AndyScherzinger where did you take the icon from? It seems to be not the Material Symbol with `grade: 0`, `optical size: 20` `weight: 400`.

Especially optical size of 20px is very important as the icon will in 99% of all places be rendered 20px.

So for consistent style we need to use the 20px optical size version everywhere.

**Comment by susnux** [comment]
Moreover this again breaks theming as you have removed the `fill="#fff"`

**Comment by AndyScherzinger** [comment]
@susnux I took the icon from Material Symbols. Can't say for sure which size though.
I can just do another PR on Monday with the optical size 20 yet when I checked other app icons their svg size was 32,no matter the optical size.
Can't say if that makes a difference here.

Also with the other apps I might even say the files app icon is the one smaller than the others?

**Comment by susnux** [comment]
> Also with the other apps I might even say the files app icon is the one smaller than the others?

Thats a bug. In the menu all icons should be 20px but a styling update broke the selector so that now the original size is shown.

**Comment by AndyScherzinger** [comment]
Ah, okay. Now I got it. Thanks for explaining it again. So what is the way forward? Style gets fixed or also the icon needs to be changed in size within the svg?

**Comment by susnux** [comment]
Well I would say if you selected this style of the icon for all other apps now, then lets stick with it.
I will see if I find some time fixing styles, but lets keep it consistent :)

**Comment by AndyScherzinger** [comment]
Well, the actual size might have been slightly to big. So I adjusted it to match the others, i.e. the photos app icon  #46360

**Pull request merged**
