### PR TITLE
Do not show action menu if no actions are available

### LINKED ISSUE #10514: Remove "View in folder" action for deleted shares
The deleted share view currently has a '...' menu with the action "View in folder:

image

We should remove this action and probably the complete '...' menu for now (later I would like to add there a "unshare permanently" action to finally unshare the file completely)

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #10514

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Good once the jsunit tests are fixed :+1:

**Review by schiessle — APPROVED** [review]
works as expected, but js tests need to be fixed

**Comment by skjnldsv** [comment]
https://twitter.com/iamstarkov/status/758316450532749312?lang=fr

Dammit!

**Comment by skjnldsv** [comment]
Okay, polyfill added

**Pull request merged**
