### PR TITLE
Use png icons in caldav reminder emails

### PR DESCRIPTION
**Pull request by st3iny**
CalDAV reminder notification emails still contain svg icons which won't be displayed by some email clients. The icons in most activity notification emails were replaced with pngs (#5483). 

All new png icons were converted using inkscape and optimized using `build/image-optimization.sh`.

See https://css-tricks.com/a-guide-on-svg-support-in-email/ for a list of email clients which do not support svgs.

Feedback is appreciated.

### CODE REVIEW

**Comment by st3iny** [comment]
cc @ChristophWurst 

This fixes the svg icon issue we discussed the other day.

**Review by ChristophWurst — APPROVED** [review]

**Review by julien-nc — APPROVED** [review]

**Comment by MorrisJobke** [comment]
comments integration tests and missing JS assets are both fixed on master in the meantime -> merge

**Comment by MorrisJobke** [comment]
@ChristophWurst @eneiluj Should we backport this?

**Comment by pirate** [comment]
As of 20.0.8 it looks like the invite emails are still using svgs instead of pngs (e.g. `core/img/caldav/time.svg`), should I open a new issue for that?

image

**Pull request merged**
