### PR TITLE
hide settings menu when ctrl+click'ing on an entry

### LINKED ISSUE #616: Ctrl-click on entries in the user menu will keep spinner spinning
When you Ctrl-click on entries in the Apps menu on the top left, the spinner does not show and the menu closes directly – which is the correct behavior.

When you Ctrl-click on entries in the User menu on the top right, the menu stays open and the spinner is shown indefinitely. This should be fixed to behave as the apps menu does. :)

cc @nextcloud/javascript

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes https://github.com/nextcloud/server/issues/616

cc @jancborchardt @nextcloud/javascript

### CODE REVIEW

**Comment by jancborchardt** [comment]
Awesome stuff, works perfectly! :+1: 

cc @skjnldsv @nickvergessen for review

**Comment by schiessle** [comment]
Great stuff @ChristophWurst! I just have one small request, could you extend it to also work with the middle click? I think the middle click is still the most used way to open something in a new tab if you work with a real mouse.

**Comment by MorrisJobke** [comment]
Duplicate of #652 -> please try to get your stuff into the other PR. I will close this for now.

**Comment by MorrisJobke** [comment]
@ChristophWurst Next time just check to open PRs that are linked to an issue first ;) Would have avoid duplicates ;)

**Pull request closed without merging**
