### PR TITLE
Deprecate global jQuery

### PR DESCRIPTION
**Pull request by ChristophWurst**
Migrating away will be hard. But so is updating to v3. As briefly discussed at the last contributor week it's time to deprecate the global variable, at least. This won't be a breaking change but devs can start to think about their migration path, while we also have some time to fix our code.

Maybe this sounds crazy, but what if we announce that jQuery will be upgraded to v3 in Nextcloud 21? This would be a soft-break. Like most scripts will still work. But some might need fine adjustments. And then completely remove the global variable in a later release?

cc @nextcloud/javascript

### CODE REVIEW

**Comment by rullzer** [comment]
Upgrading will also be hard.
So I'm not sure yet what we'll do.

In any case this is a good step!

**Review by rullzer — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> Upgrading will also be hard.

Depends. Biggest breaking change I've seen is when the load event (`$(function() { ... })`) fires. The rest is reasonable to fix.

**Comment by ChristophWurst** [comment]
We can also announce the upgrade. And if it doesn't work we don't do it. But better to announce and have people migrate away than having to break it short notice.

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
