### PR TITLE
add LDAP integr. test for receiving share candidates with group limitation

### PR DESCRIPTION
**Pull request by blizzz**
* adds integration tests that verify group limitation on sharing works with LDAP groups (we have a regression :( ) – first commit
* fixes it – second commit

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Code looks good! Let's see tests :)

**Comment by blizzz** [comment]
> Code looks good! Let's see tests :)

test case was added to  `integration-ldap-openldap-uid-features` and all other integration tests (needed to move some things to traits) still pass. What fails is unrelated or times out.

**Comment by skjnldsv** [comment]
Rebased to trigger drone

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
