### PR TITLE
Use the same `setup-php` version on all tests

### PR DESCRIPTION
**Pull request by solracsf**
## Summary

- Use same version on all tests (no need to run some old versions on some tests)
- This versions ships a fallback mirror for ondrej/php PPA when launchpad is down wich can improve test reliability. See https://github.com/shivammathur/setup-php/releases/tag/2.31.0

## TODO

- [x] CI

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by joshtrichards** [comment]
I wonder if it's worth either:

- using the `v2` tag (I get we may not want to let it float to even minor patch version changes to avoid test diffs; though I guess we already have been using inconsistent hashes since we're doing this all manually at the moment)
- go ahead and use a specific `2.x.y` version tag and integrate with dependabot

?

Refs:
- https://github.com/shivammathur/setup-php/tree/2.31.0?tab=readme-ov-file#bookmark-versioning
- https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot

**Comment by solracsf** [comment]
To read also: https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash

**Review by joshtrichards — APPROVED** [review]
Makes sense

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
Could you please use conventional commits, in this case probably:
`ci: Use the same setup-php version on all tests`

**Pull request merged**
