### PR TITLE
Fix my-apps view on mobile

### PR DESCRIPTION
**Pull request by szaimen**
Address part of https://github.com/nextcloud/server/issues/36965

### before
image

### After

https://github.com/nextcloud/server/assets/42591237/0d4d2615-ec4c-4f69-b674-42304dd270a9

### CODE REVIEW

**Comment by ShGKme** [comment]
> Address part of #36965

Note: for tables it's also allowed to use horizontal scrolling

> Exceptions apply to content that requires a two-dimensional layout, e.g. B. Images, maps, diagrams, videos, games, presentations, data tables and application interfaces in which the processing of content requires the permanent availability of toolbars.

https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-1-4-10-inhalte-brechen-um

**Comment by ShGKme** [comment]
I'm not sure this is a good approach to removing the data on a small screen. From the issue:

> some information and functions are not available without users having to scroll horizontally

In this solution, we don't have the scroll, but some information is not available at all.

Maybe we can have a horizontal scrolling here, or switch to a list layout (using isMobile util from nextcloud/vue)?

**Review by skjnldsv — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]

**Comment by JuliaKirschenheuter** [comment]
> In this solution, we don't have the scroll, but some information is not available at all.

Which functionality is missing? 

> Maybe we can have a horizontal scrolling here, or switch to the grid layout (using isMobile util from nextcloud/vue)?

The issue is that sticky header had not full width and action buttons were not fully available, like

Screenshot from 2023-10-12 10-50-04

**Comment by szaimen** [comment]
> I'm not sure this is a good approach to remove the data on a small screen. From the issue:
> 
> > some information and functions are not available without users having to scroll horizontally
> 
> In this solution, we don't have the scroll, but some information is not available at all.

Actually I did not change the behaviour. Data was already removed before. I only adjusted the css so that it looks good on mobile :)

**Review by JuliaKirschenheuter — CHANGES_REQUESTED** [review]
sorry, tested again and it doesn't seems to be fixed ;(

Screenshot from 2023-10-12 10-52-39

**Comment by ShGKme** [comment]
> Actually I did not change the behaviour. Data was already removed before. I only adjusted the css so that it looks good on mobile :)

Oh, sorry, I missed the "Before" section =D

But still, hiding the information seems to be the a11y issue here

**Comment by szaimen** [comment]
> But still, hiding the information seems to be the a11y issue here

Are you sure that was the problem here? I thought only the sticky header?

**Review by JuliaKirschenheuter — APPROVED** [review]

**Comment by ShGKme** [comment]
> Are you sure that was the problem here? I thought only the sticky header which is not going to the right?

I'm not...

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
