### PR TITLE
fix(ocp): Add deprecation version to ILogFactory::getCustomLogger

### PR DESCRIPTION
**Pull request by ChristophWurst**
## Summary

Leftover of https://github.com/nextcloud/server/pull/25588

Seen in https://github.com/nextcloud/server/pull/37458. cc @Fenn-CS

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by vitormattos — APPROVED** [review]

**Review by solracsf — APPROVED** [review]

**Comment by vitormattos** [comment]
@ChristophWurst I think that maybe you started to type the issue number but didn't finished. The description of this issue only have `Resolves: # ` without the issue number.

**Review by susnux — APPROVED** [review]

**Comment by vitormattos** [comment]
Only to check if was a punctual problem form backportbot.

**Pull request merged**
