### PR TITLE
Add distraction free backgrounds for Nextcloud 26

### PR DESCRIPTION
**Pull request by jancborchardt**
## Summary
Adding 4 distraction free backgrounds for Nextcloud 26. 2 lean more towards being used with the light theme, 2 more towards the dark theme. They are already compressed and each only around 600 kB.
Also added clear guidelines about the backgrounds for the future.

Please review @juliushaertl @skjnldsv @karlitschek @nimishavijay

### Demo with light theme

https://user-images.githubusercontent.com/925062/222676760-2834a704-9e24-4de0-aa8f-47b5da549617.mp4

### Demo with dark theme

https://user-images.githubusercontent.com/925062/222676787-c31f305f-b577-49e2-96b4-e1e279e10ae6.mp4

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by jancborchardt** [comment]
stable25 doesn’t seem to exist yet, so not requesting a backport yet.

**Comment by karlitschek** [comment]
Nice +1

**Review by nimishavijay — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
We're so close to master, why would it fail! :thinking:

**Comment by skjnldsv** [comment]
Aaah! Good!

**Pull request merged**
