### PR TITLE
Ungroup `placeholder` css rules to prevent browsers from removing all rules

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: # 

## Summary
When rules are grouped using the comma operator and one selector is invalid / unknown then the whole group is invalidated[1].
In this case `::-ms-input-placeholder` is unknown to Firefox and Chrome, so the `::placeholder` rule is never applied.

[1]: https://www.w3.org/TR/selectors-3/#grouping

## Screenshots
See default color (`--color-text-main`) is applied also for the placeholder on the before image, and note the missing `::placeholder` selector on the before image (on the "pseudo elements" section of the inspector).

before | after
---|---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Comment by susnux** [comment]
Rebased to resolve conflicts.

/backport to stable26
/backport to stable25

**Comment by susnux** [comment]
@solracsf rebased it manually :)

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by susnux** [comment]
> The backport to stable25 failed. Please do this backport manually.

Manually done in #37829

**Pull request merged**
