### PR TITLE
Allow apps to have their own autoloader

### PR DESCRIPTION
**Pull request by rullzer**
On our current setup we do over 500 calls to find_file for autoloading. This seems a bit to excessive and is not required IMO.

In case there is a file called: `<appdir>/composer/autoload.php` we will load that as the autoloader for this app.

If you have this autoloader file we will no longer load via the legacy autoloader.

* First commit is the actual change
* Second commit moves over files_sharing

Comments are welcome.

Todo:
- [x] Add to `build/autoloa.....sh`
- [x] Exclude composer stuff from phan

### CODE REVIEW

**Comment by nickvergessen** [comment]
Can we add the generation of this to `build/autoloa.....sh` please?

**Comment by rullzer** [comment]
@nickvergessen updated

**Review by nickvergessen — APPROVED** [review]
Sharing still works

**Comment by rullzer** [comment]
K lets do this. Then I can slowly migrate the other apps later :)

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
