### PR TITLE
Fix excessive increase of cachebuster value

### LINKED ISSUE #34457: [Bug]: cachebuster value rising infinitely
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The app config value for cachbuster of theming is constantly rising. This prevents caching on frontend resources, and has side effects on Talk. Because this is used in calculating a hash, it appears that resources were changed and requires a reload. This happens infinitely.

This was introduced in https://github.com/nextcloud/server/pull/34432 specifically the added lines 227 and 230 in `apps/theming/lib/ThemingDefaults.php`. The behaviour becomes normal when the lines are commented out, alas this may have other side effects I am not aware of.

### Steps to reproduce

1. Run Nextcloud 25 RC3 (earlier versions not affected)
2. Have Nextcloud Talk open

### Expected behavior

Talk does not think the instances was updated every 30s.

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [x] Other

### Configuration report

_No response_

### List of activated Apps

```shell
not relevant
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Pytal**
Fix https://github.com/nextcloud/server/issues/34457

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Tests fail:
> TypeError: Argument 6 passed to OCA\Theming\Controller\UserThemeController::__construct() must be an instance of OCA\Theming\ThemingDefaults, instance of Mock_BackgroundService_9c6977f9 given, called in /drone/src/apps/theming/tests/Controller/UserThemeControllerTest.php on line 94

**Comment by szaimen** [comment]
Alternative fix in https://github.com/nextcloud/server/pull/34437
 IIRC

**Comment by blizzz** [comment]
> Alternative fix in #34437 IIRC

very brief look seems it suffers of the same problem, but i really only spend two seconds on it.

**Comment by szaimen** [comment]
@Pytal can you please fix the tests? :)

**Review by szaimen — APPROVED** [review]
🐘

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
