### PR TITLE
Fix : Share Expire After N Days width

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Box will inherit the same size of other input boxes on that page.

## After
image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by solracsf** [comment]
Why such a big difference between boxes?
Having a big width like in the boxes above could handle bigger dates (like `3650`).

image

**Comment by Jerome-Herbinet** [comment]
> Why such a big difference between boxes? Having a big width like in the boxes above could handle bigger dates (like `3650`). At the very least, they should all have the same size thinking
> 
> image

You are right, I'll take a look at this.

**Comment by Jerome-Herbinet** [comment]
> > Why such a big difference between boxes? Having a big width like in the boxes above could handle bigger dates (like `3650`). At the very least, they should all have the same size thinking
> > image
> 
> You are right, I'll take a look at this.

Done @solracsf ; it's now more relevant with other fields, despite I think they are unnecessarily wide regarding their content.

**Comment by solracsf** [comment]
Thanks. Please just update your main screenshots on 1st post :)

**Comment by Jerome-Herbinet** [comment]
> Thanks. Please just update your main screenshots on 1st post :)

By removing the 40px width originally specified, the field inherits an upstream property with a width of 130px.

**Review by solracsf — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM but didn test

**Pull request merged**
