### PR TITLE
Make lookup search explicit

### PR DESCRIPTION
**Pull request by rullzer**
Speedsup sharee lookup quite a bit.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Nice performance improvement 🚀

**Comment by MorrisJobke** [comment]
Bildschirmfoto 2021-04-19 um 21 46 53

**Comment by MorrisJobke** [comment]
Retriggered CI to check if this is related.

**Comment by rullzer** [comment]
I thinkthis one is failing since some time now?

**Comment by nickvergessen** [comment]
Yes there is an issue by vincent about it

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/server/issues/26314 for reference

**Comment by MorrisJobke** [comment]
@rullzer MInd to do the backports?

**Pull request merged**
