### PR TITLE
Various css fixes

### LINKED ISSUE #6654: The quota button in the user settings table is not aligned vertically
To see the problem login as the admin and open the _Users_ settings.

Example:
usertable-quota

@nextcloud/designers

### PR DESCRIPTION
**Pull request by skjnldsv**
| Use [filter](https://caniuse.com/#feat=css-filters) instead of box-shadow | Better contrast (includes the top arrow) |
|:-------:|:-------:|
| kazam_screenshot_00001 | kazam_screenshot_00000 |

| Implement progress theming (html5) | Also revert text on quota bar and use primary |
|:-------:|:-------:|
| kazam_screenshot_00003 | 30912986-d9f0c54a-a38e-11e7-9274-6322d6eb89e5 |
| kazam_screenshot_00005 | 30912983-d9d9d632-a38e-11e7-8ba6-e90f2cc18b5c |

| Rebuilt quota on user list | Fixed some invalid colors too & fix #6654  |
|:-------:|:-------:|
| kazam_screenshot_00008 | kazam_screenshot_00007 |
| kazam_screenshot_00009 | kazam_screenshot_00006 |

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Also revert text on quota bar and use primary

The default background of the quota bar should be white instead of grey (like in the files sidebar).

**Comment by skjnldsv** [comment]
@MorrisJobke This has been requested by @jancborchardt :)

**Comment by skjnldsv** [comment]
Quota update pushed!
capture d ecran_2017-09-27_16-47-59
capture d ecran_2017-09-27_16-47-41 capture d ecran_2017-09-27_16-48-13 capture d ecran_2017-09-27_16-48-24

**Comment by skjnldsv** [comment]
Okay, let's review @nextcloud/designers 
I don't want to make too bigs pr with fixes. I will create new ones if I need!

CC @jancborchardt @MorrisJobke

**Comment by jancborchardt** [comment]
Wow, looks great, all of it! :+1:

**Review by MorrisJobke — APPROVED** [review]
I like ti a lot 👍

**Comment by MorrisJobke** [comment]
Integration tests fail:

```
Scenario: log in with invalid user once fixed by admin              # /drone/src/github.com/nextcloud/server/tests/acceptance/features/login.feature:32
    Given I act as John                                               # ActorContext::iActAs()
    And I can not log in with user unknownUser and password 123456acb # LoginPageContext::iCanNotLogInWithUserAndPassword()
    When I act as Jane                                                # ActorContext::iActAs()
    And I am logged in as the admin                                   # LoginPageContext::iAmLoggedInAsTheAdmin()
    And I open the User settings                                      # SettingsMenuContext::iOpenTheUserSettings()
    And I create user unknownUser with password 123456acb             # UsersSettingsContext::iCreateUserWithPassword()
    And I see that the list of users contains the user unknownUser    # UsersSettingsContext::iSeeThatTheListOfUsersContainsTheUser()
      Row for user unknownUser in Users Settings could not be found after 100 seconds (NoSuchElementException)
    And I act as John                                                 # ActorContext::iActAs()
    And I log in with user unknownUser and password 123456acb         # LoginPageContext::iLogInWithUserAndPassword()
    Then I see that the current page is the Files app                 # FilesAppContext::iSeeThatTheCurrentPageIsTheFilesApp()
```

And the upload progress bar is now grey instead of blue.

**Comment by skjnldsv** [comment]
- [ ] fix the upload progress!

**Comment by skjnldsv** [comment]
Simple idea too, what do you think @jancborchardt @MorrisJobke ?
capture d ecran_2017-09-28_10-58-26

**Comment by danxuliu** [comment]
>  fix tests, need help on this. @danxuliu?

Here I am! First of all, @skjnldsv thank you a lot for work, it is really cool! :-D

Now... the problem is that in commit f09a70e9b56a7f83857dad684cc4574a08db3421 __*__ you broke refreshing the users page when a new user is created :-P

If you try to add a new user yourself you can see that the list is not refreshed, but if you insist on clicking `Create` you will receive a message saying `Error creating user: A user with that name already exists.`. In the JavaScript console you can see `TypeError: Value being assigned to HTMLProgressElement.value is not a finite floating-point value.` (in Firefox; in Chromium the message is different but basically says the same). If you then manually refresh the page then the table will contain the new user.

__*__ Although in this case it is not of a lot of help because there are not a lot of commits in this pull request, for reference, you can automatically find in which commit the acceptance tests started to fail using `git bisect` (and giving it some time ;-) ).

First, run `git bisect start various-css-fixes $(git merge-base master various-css-fixes)` to start the bisection. `git merge-base master various-css-fixes` returns the commit where the _various-css-fixes_ branch diverged from the _master_ branch; in this case, a90b046a1 (you could also write the commit ID directly instead of calling merge-base, of course ;) ).

And then, run `git bisect run tests/acceptance/run.sh features/login.feature:32`. This will automatically run `tests/acceptance/run.sh features/login.feature:32` for each step of the bisection and, depending on whether the script succeeds or fails, mark that commit as good or bad and go on with the next steps until the first bad commit is found.

Once the offending commit was found if you are on GNU/Linux (in macOS it has been reported that it does not work, sorry) you can run `tests/acceptance/run.sh features/login.feature:32` and see by yourself what the test is doing and where it fails by connecting to the VNC server created by the acceptance tests, for example, using `vncviewer 127.0.0.1:5900` and using _secret_ as the password.

**Comment by danxuliu** [comment]
I have also noticed a problem when the menu appears over the quota button:
menuonquota

**Comment by skjnldsv** [comment]
Thank you so much @danxuliu ! :)
Will fix asap!!

**Comment by jancborchardt** [comment]
@skjnldsv just one detail I noticed: It looks strange that the quota bar (filling) has a border-radius on the top right and bottom right too. It wasn’t there before and looks much better without it. It’s ok for the small progress bars, but on the big quota bar this is strange. :)

**Comment by skjnldsv** [comment]
Simple idea too, what do you think @jancborchardt @MorrisJobke ?
capture d ecran_2017-09-28_10-58-26

We could also implement this in the file list when dropping in a folder. Displaying a progressbar on the bottom of the row? :)

**Comment by MorrisJobke** [comment]
> Simple idea too, what do you think @jancborchardt @MorrisJobke ?

Mmmmh ... I don't like the shadow around the time and the black theme is confusing. I need to see it also in real life to properly judge if it feels right. 😉

**Comment by MorrisJobke** [comment]
I'm also fine with getting this in now and fix the progress bar design afterwards, if it gets an overhaul anyways. (to not make this even bigger and bigger)

**Comment by skjnldsv** [comment]
>Mmmmh ... I don't like the shadow around the time and the black theme is confusing. I need to see it also in real life to properly judge if it feels right. 😉

@MorrisJobke Completely agree, I won't add the progressbar into this one anyway, was just an idea like this :)
Will push the color fix in a moment!

**Comment by skjnldsv** [comment]
@MorrisJobke @jancborchardt @danxuliu please review! :)
cc @nextcloud/designers ❤️

**Comment by jancborchardt** [comment]
@skjnldsv The loong bar on the top is a bit much. Let’s just keep it a short progress bar where you can quickly see the percentage. :)

Otherwise good! :)

**Comment by skjnldsv** [comment]
@jancborchardt is it a review? 😆

**Comment by enoch85** [comment]
This is great!I really like that someone is paying attention to details.Best regardsDaniel HanssonTech and MeSent from mobile, sorry for typos.Den 28 sep. 2017 17:48 skrev John Molakvoæ <notifications@github.com>:Merged #6669.

**Pull request merged**
