### PR TITLE
Fix error on delete in ChunkingV2Plugin

### LINKED ISSUE #37578: [Bug]:  When uploading a file from browser or windows desktop app, it give following error getUploadStorage(): Argument #1 ($targetPath) must be of type string, null given
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My docker install of Nextcloud 26.0 with mysql was starting normally.
Even bookmarks app works as expect.
However when I upload file from browser or windows desktop app, it give following error :

```
[webdav] Error: TypeError: OCA\DAV\Upload\ChunkingV2Plugin::getUploadStorage(): Argument #1 ($targetPath) must be of type string, null given, called in /var/www/html/apps/dav/lib/Upload/ChunkingV2Plugin.php on line 263 at <<closure>>

0. /var/www/html/apps/dav/lib/Upload/ChunkingV2Plugin.php line 263
   OCA\DAV\Upload\ChunkingV2Plugin->getUploadStorage(null)
1. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   OCA\DAV\Upload\ChunkingV2Plugin->beforeDelete(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
2. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 456
   Sabre\DAV\Server->emit("beforeMethod:DELETE", [["Sabre\\HTTP\\ ... ]])
3. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
   Sabre\DAV\Server->invokeMethod(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
4. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
   Sabre\DAV\Server->start()
5. /var/www/html/apps/dav/lib/Server.php line 366
   Sabre\DAV\Server->exec()
6. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
7. /var/www/html/remote.php line 171
   require_once("/var/www/html/a ... p")
```

In [help.nextcloud.com](https://help.nextcloud.com/t/need-help-with-docker-install-nextcloud-26-0-0/159437/3), [a user](https://help.nextcloud.com/t/need-help-with-docker-install-nextcloud-26-0-0/159437/2?u=fnaith) suggest a solution by adding checkPrerequisites() call before calling getUploadStorage().

### Steps to reproduce

1. Create a CentOS 7(maybe by aws lightsail) and deploy Nextcloud 26 with docker compose.
2. Login to Nextcloud as admin to finish initiation setup.
3. Upload a file and check the error log.

### Expected behavior

Upload file successfully.

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "drive.fnaith.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "http:\/\/drive.fnaith.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https"
    }
}
```

### List of activated Apps

```shell
nabled:
  - activity: 2.18.0
  - bookmarks: 13.0.1
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0
  - comments: 1.16.0 (installed 1.16.0)
  - contactsinteraction: 1.7.0 (installed 1.7.0)
  - encryption: 2.14.0
  - federation: 1.16.0 (installed 1.16.0)
  - files_external: 1.18.0
  - recommendations: 1.5.0 (installed 1.5.0)
  - suspicious_login: 4.4.0
  - twofactor_totp: 8.0.0-alpha.0
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.6.0)
  - weather_status: 1.6.0 (installed 1.6.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
[webdav] Error: TypeError: OCA\DAV\Upload\ChunkingV2Plugin::getUploadStorage(): Argument #1 ($targetPath) must be of type string, null given, called in /var/www/html/apps/dav/lib/Upload/ChunkingV2Plugin.php on line 263 at <<closure>>

0. /var/www/html/apps/dav/lib/Upload/ChunkingV2Plugin.php line 263
   OCA\DAV\Upload\ChunkingV2Plugin->getUploadStorage(null)
1. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   OCA\DAV\Upload\ChunkingV2Plugin->beforeDelete(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
2. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 456
   Sabre\DAV\Server->emit("beforeMethod:DELETE", [["Sabre\\HTTP\\ ... ]])
3. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
   Sabre\DAV\Server->invokeMethod(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
4. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
   Sabre\DAV\Server->start()
5. /var/www/html/apps/dav/lib/Server.php line 366
   Sabre\DAV\Server->exec()
6. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
7. /var/www/html/remote.php line 171
   require_once("/var/www/html/a ... p")

DELETE /remote.php/dav/uploads/fnaith/3925943308
from 36.225.143.72 by fnaith at 2023-04-04T16:48:25+00:00
```

### Additional info

docker-compose.yml :

```
version: "3"
services:
  nextcloud:
    image: nextcloud:26.0.0-apache
    restart: always
    ports:
      - 9009:80
    volumes:
      - ./data:/var/www/html
    environment:
      - MYSQL_PASSWORD=a_pwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=a_user
      - MYSQL_HOST=a_db.com
```

### PR DESCRIPTION
**Pull request by tanganellilore**
* Resolves: #37578 

## Summary

This PR fix the error on "delete" call when is used and storage class that is not `IChunkedFileWrite::class`.
Implementation is the same of other "before" method

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by blizzz — APPROVED** [review]
Seems reasonable

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Thanks for the pull request, could you add a signoff message to your commit to fix the DCO check?

https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work has more details about taht.

**Comment by tanganellilore** [comment]
@juliushaertl change message on commit close this pull request.
Can you re-open it?

Sorry for that

**Comment by juliushaertl** [comment]
Hm I could not do that, maybe you can open a fresh one?

**Comment by tanganellilore** [comment]
i publish new one: https://github.com/nextcloud/server/pull/38100

DCO continue to not pass, but I have added my email and username (official one)

**Comment by tanganellilore** [comment]
should be fixed now....

**Pull request closed without merging**
