### PR TITLE
[stable26] fix semaphore unguarding

### PR DESCRIPTION
**Pull request by szaimen**
Manual backport of https://github.com/nextcloud/server/pull/41263 to stable26

### CODE REVIEW

**Comment by szaimen** [comment]
Needs an update to the baseline

**Comment by blizzz** [comment]
moving to 26.0.10

**Comment by blizzz** [comment]
moving to 26.0.11

**Review by tcitworld — APPROVED** [review]
Seems to have fixed php-fpm hanging for me.

**Comment by blizzz** [comment]
It's still in draft state. @szaimen ?

**Comment by szaimen** [comment]
> It's still in draft state. @szaimen ?

Yes, see https://github.com/nextcloud/server/pull/41290#issuecomment-1793803858

**Comment by blizzz** [comment]
Are you waiting for an auto-update?

**Comment by szaimen** [comment]
> Are you waiting for an auto-update?

If you would update the psalm baseline, I would be greatful! 😉

But actually no customer has reauested this backport which is the main reason I didnt work on completing it yet...

**Comment by blizzz** [comment]
> > It's still in draft state. @szaimen ?
> 
> Yes, see [#41290 (comment)](https://github.com/nextcloud/server/pull/41290#issuecomment-1793803858)

Actually … the results looks wrong. It's as if github runs it with PHP 7 (but why). This is not our psalm result.

**Comment by DanScharon** [comment]
> But actually no customer has requested this backport afaik which is the main reason I didnt work on completing it yet...

We haven't yet, because we saw there is this open pr scheduled for a release. But if necessary we would open an issue via portal.nextcloud.com 😄

**Comment by szaimen** [comment]
So I tried to update the baseline but it seems like updating that is failing. See https://github.com/nextcloud/server/actions/runs/7502981657/job/20426751313. @blizzz any idea how to proceed with this PR?

**Comment by szaimen** [comment]
Seems to work. Thanks a lot for the help @come-nc ! :)

**Review by come-nc — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
