### PR TITLE
Update check for outdated php version.

### PR DESCRIPTION
**Pull request by kesselb**
Show warning for PHP 7.2

Screenshot from 2020-02-23 18-07-42

### CODE REVIEW

**Comment by rullzer** [comment]
I think we should rather update it. Right now that would mean php7.2 there since that is no longer developed etc.

**Comment by kesselb** [comment]
> I think we should rather update it. Right now that would mean php7.2 there since that is no longer developed etc.

Fine by me.

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
CI says no...

**Comment by MorrisJobke** [comment]
Is there a technical reason for this? Because the version check was not raised: https://github.com/nextcloud/server/blob/master/lib/versioncheck.php#L28

We just noticed it in #22507.

**Pull request merged**
