### PR TITLE
allow to execute multiple tests in a directory at once

### PR DESCRIPTION
**Pull request by schiessle**
Let you execute all tests in a given directory and it subfolders, for example `./autotest.sh sqlite apps/federation/tests` would execute all federation tests

### CODE REVIEW

**Comment by schiessle** [comment]
@MorrisJobke @LukasReschke opportunity to check if the latest change to the LGTM-bot works :wink:

**Comment by LukasReschke** [comment]
👍

**Comment by LukasReschke** [comment]
Seems to do 😄

**Comment by MorrisJobke** [comment]
Wait? Self approval is turned off right? Why could this be merged?

**Pull request merged**
