### PR TITLE
[3rdparty] Migrate to Opis/Closure

### PR DESCRIPTION
**Pull request by rullzer**
Required:
- [x] Fix usage
- [x] Fix tests
- [x] https://github.com/nextcloud/3rdparty/pull/538
- [x] rebase

### CODE REVIEW

**Comment by rullzer** [comment]
@MorrisJobke I have no clue why psalm is saying no.
I guess we just ignore that for now?

**Comment by rullzer** [comment]
Ah for reference. this is needed for the php8 bump.
Also superclosure has been discontinues for some time.

**Comment by rullzer** [comment]
@MorrisJobke could you rebuild psalm?

**Comment by MorrisJobke** [comment]
The only problem I see with this is that there might be problems with not yet executed jobs that are still in the queue. 🤔

**Comment by rullzer** [comment]
> The only problem I see with this is that there might be problems with not yet executed jobs that are still in the queue. thinking

As far as I can tell this does work just fine.
I ran a few tests. Converting with superclosure to text. And then unserializing with this. And all worked.

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
