### PR TITLE
fix(user_status): separate user menu and dashboard status layout for HTML validation

### LINKED ISSUE #41022: [BITV] User menu set status button
The "Set status" entry is currently an `a` tag but should be a `button`

image

### PR DESCRIPTION
**Pull request by ShGKme**
* Resolves: A part of https://github.com/nextcloud/andy/issues/5

> Error: Attribute `href` not allowed on element [`button`](https://html.spec.whatwg.org/multipage/#the-button-element) at this point.

## Summary

`UserStatus` component is used in both User Menu (2 entries) and Dashboard status widget. It reuses layout, but the usage is quite different.

User Menu Entries | Dashboard Status Widget
---|---
image | image

## TODO

- [x] Separate layout for user menu and dashboard. This allows to:
  - Remove `href="#"` from a button for HTML validation
  - Use `@nextcloud/vue` `NcButton` instead of custom button in Dashboard for better looking (status icon is in the center, button size is the same as other buttons)

Before | After
---|---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Comment by ShGKme** [comment]
Rebased onto master, resolve assets conflicts

**Review by JuliaKirschenheuter — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by JuliaKirschenheuter** [comment]
failed Cypress is unrelated

**Comment by ShGKme** [comment]
> /backport to stable28

This PR was done before 29, it is in 28 already.

**Pull request merged**
