### PR TITLE
Add detailed users listing in occ user:info command

### PR DESCRIPTION
**Pull request by skjnldsv**
```yaml
# occ user:list --info
  - admin:
    - user_id: admin
    - display_name: admin
    - email: 
    - cloud_id: admin@dev.skjnldsv.com
    - enabled: true
    - groups:
      - 0: admin
    - quota: none
    - last_seen: 2019-10-15T19:33:00+00:00
    - user_directory: /var/www/nextcloud/data/admin
    - backend: Database
  - Test1:
    - user_id: Test1
    - display_name: Test1
    - email: 
    - cloud_id: Test1@dev.skjnldsv.com
    - enabled: true
    - groups:
    - quota: none
    - last_seen: 2019-10-14T19:35:14+00:00
    - user_directory: /var/www/nextcloud/data/Test1
    - backend: Database

```

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Looks good. And saw it in action :+1:

**Comment by blizzz** [comment]
I'm getting a `Lost connection to LDAP server.`, but all active LDAP's are reachable.

**Comment by blizzz** [comment]
I am investigating it. Does not make much sense to me.

**Review by blizzz — APPROVED** [review]
works

**Pull request merged**
