### PR TITLE
Remove useless ini_set calls

### PR DESCRIPTION
**Pull request by solracsf**
They're all PHP_INI_SYSTEM.
See comments below 👍

### CODE REVIEW

**Comment by kesselb** [comment]
Did you run into an issue because the value is wrong?

- The default for max_file_uploads is 20 and that seems enough. It's not relevant anyway because max_file_uploads limits the number of uploaded files per request. Each file is uploaded in a own request usually. 
- Afaik a positive integer is considered as true. I think we should remove the `ini_set` call for file_uploads. That's something for htaccess or user.ini.

**Comment by acsfer** [comment]
I was simply checking what ini_set calls Nextcloud was making in a ini_set disabled host to set those values manually.

It should be either fixed with this PR or (re)moved as you've said.

**Comment by kesselb** [comment]
| | `file_uploads` | `max_file_uploads` |
| --- | --- | --- |
| Master | On | 20 |
| This PR | On | 50 |

I don't see why we need to increase `max_file_uploads`.

**Comment by acsfer** [comment]
As far as i understand, this can't even be changed trough .htaccess our ini_set...
https://bugs.php.net/bug.php?id=50684

So the best option is to **remove it**.

**Comment by kesselb** [comment]
>  As far as i understand, this can't even be changed trough .htaccess our ini_set...

That's correct. `file_uploads` is also PHP_INI_SYSTEM and not changeable via ini_set. Please remove it.

**Comment by kesselb** [comment]
And if your are on it please remove `upload_max_filesize` and `post_max_size` because they are PHP_INI_SYSTEM too.

**Comment by kesselb** [comment]
I found another one :see_no_evil: 

`max_input_time` is PHP_INI_PERDIR (https://www.php.net/manual/en/info.configuration.php)

Would be nice to squash all commits together (or drop the old ones) and sign off (https://github.com/nextcloud/server/pull/24934/checks?check_run_id=1637306644 for some hints)

Thanks for cleaning this up :+1:

**Review by kesselb — APPROVED** [review]

**Comment by rullzer** [comment]
Could you squash this to 1 commit?
Then lets get it in.

**Pull request merged**
