### PR TITLE
fix LDAP User deletion (cleanup), fixes #3365

### LINKED ISSUE #3365: ldap: remnants from previous ldap configuration are undeletable if ldap uid also exists in new ldap configuration
We are using Nextcloud 10.0.1.

We have two ldap services, servicing the same users but with differents attributes and different DNs.
During the setup of our nextcloud instance, I started by using one of our ldap server, let's call it ldap1. Nextcloud populated the ldap user mapping table with the DNs from ldap1 using the uid's as owncloud usernames.

I noticed this server wouldn't do because it lacked the memberOf overlay I needed to filter users, so I changed the server address for ldap2, base dn from ldap2, etc. **without deleting the configuration just by modifying the current configuration from the admin interface**.  Nextcloud, like previously, populated the ldap user mapping table with the content of ldap2 but this time uuids were generated.

So, now, in the ldap user mapping table users from both ldap servers are stored and since both ldap servers had the same users but with different DN and different owncloud_name/directory_uuid:

```
+-------------------------------+----------------------+-----------------------+
| ldap_dn                          | owncloud_name   | directory_uuid     |
+-------------------------------+-----------------------+----------------------+
| uid=doe-j,o=dn1             | doe-j                     | doe-j                    |
| uid=doe-j,o=dn2             | 3da3ab4e-.....       | 3da3ab4e-....      |
+-------------------------------+-----------------------+----------------------+

```
occ ldap:show-remnants actually lists users from ldap1 
```
+------------------------+-------------------------+-----------------+-----------------------+
| ownCloud name     | Display Name         | LDAP UID      | LDAP DN             ....
+------------------------+-------------------------+-----------------+-----------------------+
| doe-j                       | John Doe                | doe-j             |  uid=doe-j,o=dn1  ....
+------------------------+-------------------------+-----------------+-----------------------+
```
but occ user:delete can't delete them:

>The specified user could not be deleted. Please check the logs.

and in the log:

> {"reqId":"2GT2OrIJgQugOKf6eohL","remoteAddr":"","app":"user_ldap","message":"User 3da3ab4e-..... is not marked as deleted, not cleaning up.","level":1,"time":"2017-02-03T12:40:32+00:00","method":"--","url":"--","user":"--"}

Notice it got the user wrong?

Indeed, the user:delete command does a ldap lookup of the user's loginname against the current ldap configuration to retrieve the user's ldap dn in order to get the owncloud_name from  the ldap user mapping table: so nextcloud looks up doe-j in ldap2 which is the current ldap server and gets uid=doe-j,o=dn2 as a result. From this ldap_dn it gets the wrong owncloud_name which is of course not marqued as deleted in the oc_preferences table.

### PR DESCRIPTION
**Pull request by blizzz**
I investigated another  case at #3365 and despite the recent PR,  there was still  a small detail  wrong (unfortunately also with the integration  test that returned a  false positive)… 😿 

```
$ ./occ ldap:check-user b9bf0cf3-52f1-4d96-b2a7-da76f660d754
The user is still available on LDAP.
$ ldapdelete  -H ldap://localhost:7770 -D cn=root,dc=nc,dc=zara -W "uid=user_1160,ou=users,ou=medium,dc=nc,dc=zara"
$ ./occ ldap:check-user b9bf0cf3-52f1-4d96-b2a7-da76f660d754
The user does not exists on LDAP anymore.
Clean up the user's remnants by: ./occ user:delete "b9bf0cf3-52f1-4d96-b2a7-da76f660d754"
$ ./occ user:delete b9bf0cf3-52f1-4d96-b2a7-da76f660d754
The specified user was deleted
```

Before:

```
$ ./occ user:delete d4549eb6-9495-499a-97c0-48ad45e8aed5

                                                                    
  [OC\User\NoUserException]                                         
  d4549eb6-9495-499a-97c0-48ad45e8aed5 is not a valid user anymore                                                        
```

please test and review @nextcloud/ldap @ArnY

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Does not trigger the cleanup for me. :/

```bash
$ occ ldap:check-user 43a8f5d2-88b9-1036-9a6b-e592489785b8
The user is still available on LDAP.
$ # delete user from LDAP
$ occ ldap:check-user 43ab49f4-88b9-1036-9a71-e592489785b8
The user does not exists on LDAP anymore.
Clean up the user's remnants by: ./occ user:delete "43ab49f4-88b9-1036-9a71-e592489785b8"
$ occ -v user:delete 43ab49f4-88b9-1036-9a71-e592489785b8
User does not exist
```

**Comment by MorrisJobke** [comment]
I used https://github.com/owncloud/core/wiki/How-to-test-user_ldap to setup my LDAP

**Comment by blizzz** [comment]
As discussed on IRC, it works for me with that docker image. I rebased and pushed a fix for failing User_Proxy test.

**Comment by MorrisJobke** [comment]
> As discussed on IRC, it works for me with that docker image. I rebased and pushed a fix for failing User_Proxy test.

Somehow it still does not work for me :/

**Comment by MorrisJobke** [comment]
> Somehow it still does not work for me :/

Tested again and worked.

**Review by MorrisJobke — APPROVED** [review]
Works now 👍

**Pull request merged**
