### PR TITLE
Add link to real changelog

### LINKED ISSUE #5773: Do something with CHANGELOG.md
The CHANGELOG.md should maybe updated or deleted if not used...?

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #5773

### CODE REVIEW

**Review by MariusBluem — COMMENTED** [review]
Change Log or **Changelog** 😬

**Comment by MorrisJobke** [comment]
> Change Log or Changelog 😬

Don't care

**Review by radiantwave — CHANGES_REQUESTED** [review]
"change log" -> "Changelog" ^-^

**Comment by MorrisJobke** [comment]
> "change log" -> "Changelog" ^-^

Fixed

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
