### PR TITLE
Don't pretend we can add/remove users to/from groups when we can't

### PR DESCRIPTION
**Pull request by icewind1991**
Properly blocks the group multiselect from pretending to make changes that can't be made

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense and works 👍

**Comment by skjnldsv** [comment]
I would prefer to disable the option in the select rather than still propagating the event but saying NO! :)

**Review by skjnldsv — CHANGES_REQUESTED** [review]
I would prefer to disable the option in the select rather than still propagating the event and saying NO! :)
https://vue-multiselect.js.org/#sub-single-select-object

**Comment by skjnldsv** [comment]
Hum, the vue multiselect is throwing errors when properly setting up the disabled state.
I opened an issue https://github.com/shentao/vue-multiselect/issues/759

Let's keep this like it is. We'll see later once the lib is fixed

**Comment by skjnldsv** [comment]
Here, I pushed the proper changes anyway.
An  error is thrown in the console when clicking a disabled entry and the vue-multiselect library does not allow disabled selected state apparently. Seems like a bug.

We'll see. Behaviour is ok now though.

**Review by skjnldsv — APPROVED** [review]

**Comment by Link1988** [comment]
Hi @skjnldsv I found a workaround to avoid the errors when you click in disabled values I create a reference in the component something like this.
<multiselect
                    ref="sendToContacts"
                    v-model="selectedContactLists"
                    placeholder="None"
                    label="Name"
                    open-direction="bottom"
                    track-by="uniqueID"
                    :options="contactLists"
                    :multiple="true"
                    :close-on-select="false"
                    :clear-on-select="false"
                    :show-labels="false"
                    :show-pointer="false"
                    :preserve-search="true"
                    @open="removePlaceholder('sendToContacts')"
                    @search-change="searchQuery"
                    @select="selectContactOption"
                    @remove="selectContactOption"
                    @input="checkDetails">

And in the beforeUpdate lifecycle method you can overwrite those functions :)

this.$refs.sendToContacts.selectGroup = function () {
 return;
}

this.$refs.sendToContacts.wholeGroupDisabled = function () {
 return;
}

this.$refs.sendToContacts.wholeGroupSelected = function () {
 return;
}

I know that is not the best solution but works for now

**Comment by skjnldsv** [comment]
@Link1988 what issue are you referring to? :)

**Comment by Link1988** [comment]
Hi @skjnldsv I was referring to this one shentao/vue-multiselect#759 :)

**Pull request merged**
