### PR TITLE
Fix filename and popover menu misalignment

### PR DESCRIPTION
**Pull request by GretaD**
Dirty hack to fix the regression
before

filepopover_bad
After

filepopovermenu

### CODE REVIEW

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Sorry, no dirty hacks on files anymore, we broke it too much with tht headers for 18 ^^

**Comment by GretaD** [comment]
> Sorry, no dirty hacks on files anymore, we broke it too much with tht headers for 18 ^^

I agree but i have no other idea how to fix this. Did you check the code, its not that dirty ;)

**Comment by juliushaertl** [comment]
> Sorry, no dirty hacks on files anymore, we broke it too much with tht headers for 18 ^^

The real dirty hack is actually the stick headers for the table, since the sticky css property doesn't work with `display: table;` this is why the display of that was currently set to flex, but that breaks the table rendering on firefox. I spent some time looking into this with Greta and I also see no other way to fix this with the current filelist layout, but feel free to dig in further. :wink:

**Review by juliusknorr — APPROVED** [review]
Fine from my side :+1:

**Comment by skjnldsv** [comment]
Sorry, I don't want to take any more risks here, I don't want to go back and have 3 pr opened after this again ^^
I'm too scared and we lost lots of time last release for those :/

I'm ok to approve, but I warned you if it goes wrong :see_no_evil:

**Review by skjnldsv — APPROVED** [review]

**Comment by GretaD** [comment]
> Sorry, I don't want to take any more risks here, I don't want to go back and have 3 pr opened after this again ^^
> I'm too scared and we lost lots of time last release for those :/
> 
> I'm ok to approve, but I warned you if it goes wrong see_no_evil

Thank you Bath, let discuss during the hackweek how to fix stuff like this one without dirty hacks. Because every time we do something on files, regression like this one happen.

**Review by gary-kim — APPROVED** [review]
Not a nice solution but if it's necessary, then sure

**Pull request merged**
