### PR TITLE
Correctly handle displaynames returned from the sharee API

### PR DESCRIPTION
**Pull request by nickvergessen**
Proper fix from #13576

### CODE REVIEW

**Comment by nickvergessen** [comment]
Regression from https://github.com/nextcloud/server/commit/e5cae301ebeb472d8c635b479fb5971530122f81

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
Make sense!

**Comment by MorrisJobke** [comment]
CI failure on jsunit tests are due to codecov.

**Pull request merged**
