### PR TITLE
fix(files_sharing): federated shares avatar

### PR DESCRIPTION
**Pull request by skjnldsv**
We fallback to `?guestFallback=true` only for the normal AvatarController
If we already know this is a guest user, we do not need to fallback at all, we can go straight to the GuestAvatarController

| Before | After |
|:---------:|:------:|
|||

### CODE REVIEW

**Comment by skjnldsv** [comment]
Added tests

**Review by nfebe — APPROVED** [review]

**Review by provokateurin — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
30: https://github.com/nextcloud/server/pull/48888
29: https://github.com/nextcloud/server/pull/48889
28: https://github.com/nextcloud/server/pull/48955

**Pull request merged**
