### PR TITLE
fix(auth): Fix logging in with email and app password

### LINKED ISSUE #42961: [Bug]: DAV login with email address: Call to a member function getUID() on null
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://nextcloud-gmbh.sentry.io/issues/4892762928 popped up with the deployment of a 28.0.2.0 setup.

Bildschirmfoto vom 2024-01-19 12-52-33

### Steps to reproduce

1. Send DAV request using the email address as username

### Expected behavior

Login works

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Resolves: https://github.com/nextcloud/server/issues/42961

## Summary

Logging in with email and app password is only allowed if the token was created in a web session authenticated with the email. That's because Nextcloud enforces the login name to match when logging in with an app password.

``\OCA\DAV\Connector\Sabre\Auth::validateUserPass`` calls ``\OC\User\Session::logClientIn``, which tries to log in with `\OC\User\Session::login`, which validates the token. Because of the login name mismatch login "fails". Yet `\OC\User\Session::logClientIn` continues the email login fallback. Since https://github.com/nextcloud/server/pull/42651 there is a shortcut to not do a second login. But the return value indicates a successful login that never happened.

### Tested

* [x] Log in with username and password -> works as expected
* [x] Log in with username and app password generated with username login -> works as expected
* [x] Log in with email and password -> works as expected
* [x] Log in with email and app password generated with username login -> fails gracefully as expected
* [x] Log in with email and app password generated with email login -> fails gracefully as expected

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Log in with email and app password generated with email login

Weirdly enough that is not possible anymore. If I log in using email+password on web, any generated app token receives my user's UID as login name, not the email address. This is another regression.

**Comment by ChristophWurst** [comment]
> If I log in using email+password on web, any generated app token receives my user's UID as login name, not the email address. This is another regression.

That has even been the case since https://github.com/nextcloud/server/pull/15365. I guess sessions with email login names are not possible unless it's ldap.

**Comment by blizzz** [comment]
> > If I log in using email+password on web, any generated app token receives my user's UID as login name, not the email address. This is another regression.
> 
> That has even been the case since #15365. I guess sessions with email login names are not possible unless it's ldap.

IIRC we have a questionable design where mail login is attempted independent of the user backends. The LDAP backend passes on the provided login name, and by configuration it could be compared against a user id, email, both, or other attributes as well.

**Review by blizzz — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
LGTM and login using the email still works for me, but didn't test with app passwords.

**Review by Altahrim — APPROVED** [review]

**Comment by ChristophWurst** [comment]
mysql killed after 1h. rest passed.

**Pull request merged**
