### PR TITLE
fix(files_sharing): List of share type during recipient lookup

### PR DESCRIPTION
**Pull request by artonge**
ShareType lists both names and ids so Object.entries return too much.

This was also making useless the following condition adding ShareType.Email

Partial revert of https://github.com/nextcloud/server/pull/49351

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
:elephant:

**Review by nfebe — APPROVED** [review]

**Comment by nfebe** [comment]
Manually backported by adding here : https://github.com/nextcloud/server/pull/49631

**Pull request merged**
