### PR TITLE
Fix filerow avatars

### PR DESCRIPTION
**Pull request by blizzz**
Reasons: Only the displayname was provided as information to send the share to. This can include ", " which was used to split users apparent. In my example this lead to duplicating the count of avatars. Also, the avatar must be fetched by userid, otherwise a random placeholder is returned. Finally, just one avatar was requested and set for everybody. All resolved.

Before:

screenshot_20171119_164047

screenshot_20171119_164155

Now:

screenshot_20171119_163937

screenshot_20171119_163858

### CODE REVIEW

**Comment by blizzz** [comment]
some more test issues… looking into it

**Comment by pixelipo** [comment]
@blizzz I don't know if you noticed this issue - open the Shared with others page:
image

click on the "Shared" item button (open sidebar):
image

Avatars disappear...

**Comment by blizzz** [comment]
@pixelipo thanks for testing, i confirm. looking into it.

**Comment by blizzz** [comment]
The rendering is weird in that case… the avatars are rendered properly first, but then then the table gets emptied, and refilled and the necessary data has vanished. Pretty pretty sure it was there before, but you would not notice it. Now it's an issue.  Annoying to debug, lunch first.

**Comment by blizzz** [comment]
…and it only happens once after a browser refresh. then, switching between the file views never looses avatars. The FileInfo object is not extended, which is probably done in the reload callback.

Essentially, updateRow() is executed which drops the existing file row and renders  a new one. At this stage, we have the fileinfo. The reloadCallback of OCA.Sharing.FileList would extend the file info with the missing data… but reload does not happen here. Well, and updateRow is fired twice, the second time uselessly… getting closer. tbc.

**Comment by blizzz** [comment]
Slowly this drives me nuts 🌰🌰🌰 the fix fixing this violates another test.

> PhantomJS 2.1.1 (Linux 0.0.0) OCA.Sharing.Util tests ShareTabView interaction updates fileInfoModel when shares changed FAILED

😩 

@pixelipo @jancborchardt btw, also in master the avatars only appear in the "Shared With xxx" sections for me, but not in general view. Do you see the same?

**Comment by pixelipo** [comment]
@blizzz I share your frustration: https://github.com/nextcloud/server/pull/6094#pullrequestreview-64261848 :expressionless: 

In master, avatars appear in `Shared with ***`, but also in `All files` view if you are the one receiving the shares.

**Comment by blizzz** [comment]
> In master, avatars appear in Shared with ***, but also in All files view if you are the one receiving the shares.

As the sharer, i see the avatars in  Shared with ***, but not in All files (also in master)

**Comment by blizzz** [comment]
As for `_formatRemoteShare`, the name alone is misleading, as it formats anything.

**Comment by blizzz** [comment]
Long story short (aka another day wasted) I check what ever fileInfo is provided and when pulling and applying size information of the file, we make sure to not lose the sharing data. This should be the final nail. 🤞 🍀

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Unit test fails:

```
PhantomJS 2.1.1 (Linux 0.0.0) OC.Share tests markFileAsShared displaying the recipients display multiple with divergent displaynames FAILED
	Expected 'Shared with Green, Mina Shared with Yoko Ono two@…' to equal 'Shared with Green, Mina two@… Shared with Yoko Ono'.
	checkRecipients@core/js/tests/specs/shareSpec.js:164:42
	core/js/tests/specs/shareSpec.js:330:20
```

**Comment by blizzz** [comment]
remaining failing test is due to phantomjs, which should be fixed in 2.5 according to https://github.com/ariya/phantomjs/issues/14496. we're using 2.1. Looking into it…

**Comment by blizzz** [comment]
Gosh, despite the comments, 2.5 never saw the light of day. phantomjs is dead ⚰️

**Comment by blizzz** [comment]
fix pushed, i am expecting green lights now 🏁

**Comment by blizzz** [comment]
Failing thing is timeout, unrelated and passed before.  💃

**Comment by MorrisJobke** [comment]
> Failing thing is timeout, unrelated and passed before. 💃

Can confirm 👍

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
@blizzz this broke the sharing sidebar when you're in the share view.
`OCA.Sharing.SharedFileInfo` does not exists and generate an error in the logs because this is undefined:
```
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object
    at FileList.updateRow (sharedfilelist.js:169)
    at child.<anonymous> (filelist.js:490)
    at triggerEvents (backbone.js:370)
    at triggerApi (backbone.js:356)
    at eventsApi (backbone.js:155)
    at child.Events.trigger (backbone.js:346)
    at child.set (backbone.js:526)
    at Object.<anonymous> (fileinfomodel.js:109)
    at Object.<anonymous> (jquery.min.js:2)
    at j (jquery.min.js:2)
```

Because of this, we have #10516 :)
Any clue you can give me on where the SharedFileInfo was supposed to be?

**Pull request merged**
