### PR TITLE
[13] Expired tokens should not trigger bruteforce protection 

### PR DESCRIPTION
**Pull request by rullzer**
Backport of #12140

### CODE REVIEW

**Comment by rullzer** [comment]
Lets see what CI tells us

**Comment by MorrisJobke** [comment]
> Lets see what CI tells us

💚

**Review by MorrisJobke — APPROVED** [review]
Code change is fine with me 👍

**Comment by rullzer** [comment]
Nice then lets do it!

**Review by Dagefoerde — APPROVED** [review]
:shipit:

**Pull request merged**
