### PR TITLE
Revert "Fix quota calculation on new dav upload endpoint"

### PR DESCRIPTION
**Pull request by MorrisJobke**
Reverts nextcloud/server#6483

Let's see if the CI failures go away or if it is something else.

cc @rullzer @skjnldsv

### CODE REVIEW

**Comment by skjnldsv** [comment]
CI still fails `Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network`

**Comment by MorrisJobke** [comment]
> CI still fails Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

That is not related to the actual unit test failures. And I also know why it happens again 🙈

**Comment by MorrisJobke** [comment]
Even reverted the quota stuff fails: https://drone.nextcloud.com/nextcloud/server/1481/102

**Comment by rullzer** [comment]
:S

**Pull request closed without merging**
