### PR TITLE
Operation progress improvements

### PR DESCRIPTION
**Pull request by tomasz-grobelny**
More operations controlled by rate limiting (delete, copy)
Progress bar
Better error handling

### CODE REVIEW

**Comment by tomasz-grobelny** [comment]
@danxuliu, @rullzer, @juliushaertl, @MorrisJobke, @skjnldsv - any thoughts on this one? This is basically a followup to https://github.com/nextcloud/server/pull/12128

**Comment by MorrisJobke** [comment]
Can someone from @nextcloud/javascript have a look at this?

**Comment by tomasz-grobelny** [comment]
> Can someone from @nextcloud/javascript have a look at this?

Any way to get this reviewed in some reasonable timeframe? We are approaching two months now...

**Comment by ChristophWurst** [comment]
Hey @tomasz-grobelny,

sorry for the delay. Can you please provide some steps for testing? There's *a lot* that has changed here.

On the semaphore: is it really necessary? Can't you synchronize the concurrent operations via a simple promise (which are used internally anyway)?

Thanks :v:

**Comment by tomasz-grobelny** [comment]
> sorry for the delay. Can you please provide some steps for testing? There's _a lot_ that has changed here.
> 
This change is mostly about operations (move, copy, delete) on multiple files. Therefore the best way to get started is to have a folder with many files (range of hundreds should be good) and then try to select all/many of them and perform these operations. You should get a progress bar, when any on the files gets an error from the server it should be properly handled (stay on the list and be checked), etc.

Please note that not everything might work yet (cancellation, how it behaves when going between folders during operation), but I didn't want to get the pull request even bigger and harder to understand.

> On the semaphore: is it really necessary? Can't you synchronize the concurrent operations via a simple promise (which are used internally anyway)?
> 
I was wondering if we could use some lib to perform that but anyway the mechanism itself comes from my previous commit - now it has just been moved to a separate file. But why is it needed? If not for this my server got overloaded because all several hundred requests were sent to the server at once. You may ask: how so if browsers limit number of concurrent connections to some fairly small number (6 or so). Well yes, but only for HTTP/1.x - HTTP 2.0 allows all requests to be send at once.

**Comment by ChristophWurst** [comment]
You can still serialize async operations with just promises:

```js
function doAsync(val) { return new Promise((res, rej) => setTimeout(() => { console.log(val); res(); }, 1500)) }
[1, 2, 3, 4].forEach(x => all = all.then(() => doAsync(x)))
```

^ that will execute the async operations one after another. Isn't that enough?

**Comment by tomasz-grobelny** [comment]
> You can still serialize async operations with just promises:
> 
The point here is to execute several operations in parallel, but not all at once (so a mix between serial and parallel). For now it is a fixed number of operations, but in future it could automatically detect server capacity (flow control). To observe this it is best to have a look how many operations are in progress on server side in browser's dev tools' network tab.

**Comment by ChristophWurst** [comment]
> To jump into this: In general I like the idea of the semaphore. It's a not that common concept (at least on the practical side) but it is the one that you should use to solve exactly this problem. I'm fine with this approach +1

Not really. JavaScript executes concurrently but not in parallel. It's single-threaded. You don't need any of the multithreading synchronization techniques.

**Comment by MorrisJobke** [comment]
> Not really. JavaScript executes concurrently but not in parallel. It's single-threaded. You don't need any of the multithreading synchronization techniques.

But isn't the idea to have a concurrency of n and not only one at a time? 5 is fine, but 100 would be too much in this scenario.

**Comment by ChristophWurst** [comment]
Yeah, of course shouldn't send off too many requests at one. That is also doable with promises. Either with a bit of concurrent logic or by using an existing library like https://github.com/rxaviers/async-pool or https://www.npmjs.com/package/es6-promise-pool.

In any case it will get a bit tricky/complicated. But I'd rather use the native promises than a concept that isn't necessary in js.

**Comment by MorrisJobke** [comment]
> In any case it will get a bit tricky/complicated. But I'd rather use the native promises than a concept that isn't necessary in js.

I would prefer the 20 lines semaphore code, which - to be fair - is not super trivial, but after some thinking you can wrap your head around the concept. Otherwise we include a dependency and need to maintain it to be up to date and we would have more code than is needed. Does that make sense to you?

**Comment by ChristophWurst** [comment]
I'm fine with either. But to be fair with an existing lib we'd use a known to work component rather than our own. And including it into our new webpack bundle is more performant than yet another script to include on the files app page. And keeping it up to date is trivial with Dependabot.

I'm fine with the semaphore for now.

**Comment by MorrisJobke** [comment]
> I'm fine with either. But to be fair with an existing lib we'd use a known to work component rather than our own. And including it into our new webpack bundle is more performant than yet another script to include on the files app page. And keeping it up to date is trivial with Dependabot.

Sure - I just want to avoid the "let's use a lib for every small problem" 😉 But if there is something the works perfectly fine and we automate everything else, then go for it. 👍

**Comment by tomasz-grobelny** [comment]
@MorrisJobke , @ChristophWurst - ok, then how do we proceed with this? Should I make any changes in code or are we fine to merge?

**Comment by ChristophWurst** [comment]
How *complete* is this change? Do we need any follow-up PRs? Is the code testable? I would be great to have this complex logic tested. But it's not my call if we want this in our code base. I can't tell if this makes the files app code more or less maintainable.

**Comment by tomasz-grobelny** [comment]
> How _complete_ is this change? Do we need any follow-up PRs?
> 
It does not make Nextcloud Files a perfect app, but improves on several aspects (error handling, UI feedback, reliability). It is useful on its own already. So in this sense no follow-up PRs are needed. Are there more improvements that can be done in related code? Yes, for sure. And I have a few ideas in my head. But as already mentioned above:

Please note that not everything might work yet (cancellation, how it behaves when going between folders during operation), but I didn't want to get the pull request even bigger and harder to understand.

> Is the code testable? I would be great to have this complex logic tested. 
> 
The changes can be seen from user perspective (it is not just refactoring) so in this aspect it is testable. Did I write new automated tests? No, it does not provide new functionality as such so I didn't consider that. Existing tests were adapted though.

> But it's not my call if we want this in our code base. I can't tell if this makes the files app code more or less maintainable.
> 
Any idea whose call it might be then? Is there any list of app maintainers that I could refer to? As for maintainability I believe I have improved it, eg. by making some code paths reusable (see eg. reportOperationProgress, OperationProgressBar, Semaphore).

**Comment by skjnldsv** [comment]
> @MorrisJobke , @ChristophWurst - ok, then how do we proceed with this? Should I make any changes in code or are we fine to merge?

I'll be honest, touching this piece of code is quite a hard task here. Not only because of the tech used, but mostly because this is a solid mess that have repercussions ll over the place.
I'm really afraid to merge such big changes since it will most likely blow up somewhere else like it always do :(

**Comment by tomasz-grobelny** [comment]
> > @MorrisJobke , @ChristophWurst - ok, then how do we proceed with this? Should I make any changes in code or are we fine to merge?
> 
> I'll be honest, touching this piece of code is quite a hard task here. Not only because of the tech used, but mostly because this is a solid mess that have repercussions ll over the place.
> I'm really afraid to merge such big changes since it will most likely blow up somewhere else like it always do :(

I understand your hesitance yet at the same time I think it would be for everyone's benefit to finally rework this piece of code. I do agree that it is a mess from developer viewpoint and that's why I took attempt to give it some structure (as mentioned above: separate components/files/function/move jQuery/html out of file-upload.js) which benefits developers. For users we have more reliability and UI feedback.

Unfortunately without some changes in the Files app Nextcloud is nearly unusable if operating on significant number of files and issues start popping up eg. https://github.com/nextcloud/server/issues/13696. I guess fixing that one will also require mechanism such as Semaphore (separated in this PR). Next issue is requesting file previews which is not managed in any way and creates too much load on the server.

I am aware that it may blow up. I offer that I will fix the issues that arise from this PR (and related). Also the sooner this gets merged in the release cycle the more time we have for testing. Is there anything more I could do to give more confidence in merging this PR?

**Review by MorrisJobke — APPROVED** [review]
I tested this and it works nicely 👍 The code looks good and I would merge this as it is. It's fine to overhaul this later, but who knows when we will find the time - so better improve in little steps instead of waiting for the big change that may come in a more distant future.

**Comment by danielkesselberg** [comment]
I would like to ask a question ;-) As far as I can see this code is not compiled by babel or webpack. How should this semaphore thing work in ie11 if promises [are not supported](https://caniuse.com/#feat=promises)? :thinking:

**Comment by tomasz-grobelny** [comment]
> I would like to ask a question ;-) As far as I can see this code is not compiled by babel or webpack. How should this semaphore thing work in ie11 if promises [are not supported](https://caniuse.com/#feat=promises)? thinking Is there some kind of polyfill?

I have not tested this on IE11, will do so in the next few days. Maybe we include something like Bluebird? Also, I wasn't aware that IE11 should still be supported - but I see it in Nextcloud system requirements that IE11 is still there. Is it still supposed to be supported for Nextcloud 16?

**Comment by MorrisJobke** [comment]
> Maybe we include something like Bluebird?

There was AFAIK another ponyfill to provide that - cc @nextcloud/javascript 



> Is it still supposed to be supported for Nextcloud 16?

Yes and will also not be dropped in the near future as too many people are still using it 🙈

**Comment by tomasz-grobelny** [comment]
> > Maybe we include something like Bluebird?
> 
> There was AFAIK another ponyfill to provide that - cc @nextcloud/javascript
> 
Yes indeed, polyfill is used. I have just now tested deleting and copying files on IE11 and it works ok.

**Comment by danielkesselberg** [comment]
Amazing 👍

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Failure is unrelated! :ship:

**Pull request merged**
