### PR TITLE
Move deprecation warnings to debug

### PR DESCRIPTION
**Pull request by szaimen**
Same as https://github.com/nextcloud/server/pull/37816 but for js

### CODE REVIEW

**Review by szaimen — COMMENTED** [review]
Alternatively we might want to check for window.oc_debug and only show the warning in that case. WDYT @skjnldsv @ChristophWurst ?

**Comment by ChristophWurst** [comment]
Yes, showing this only to devs would be preferred

**Comment by szaimen** [comment]
> Yes, showing this only to devs would be preferred

@ChristophWurst so which version shall we choose? the current one by moving the warnings to debug or checking for window_oc_debug and then printing a warning?

**Comment by ChristophWurst** [comment]
Debug logs and debug mode only

**Review by susnux — APPROVED** [review]

**Comment by szaimen** [comment]
@ChristophWurst addressed

**Comment by szaimen** [comment]
> And there will be no difference between important deprecation warning messages from the libs and verbose debug logs for app/lib in terms of log levels.

that is what I was wondering about as well. So my suggestion would be to show these as warnings if debug mode is enabled. WDYT?

**Comment by ShGKme** [comment]
> that is what I was wondering about as well. So my suggestion would be to show these as warnings if debug mode is enabled. WDYT?

I'd either keep `console.warn` for deprecation warnings or make something more high-level.

**Comment by szaimen** [comment]
> I'd either keep `console.warn` for deprecation warnings or make something more high-level.

please check out https://github.com/nextcloud/server/pull/38852/commits/6dd433a8f6b8166131ca004ccebaaf99e2595cee

**Review by ShGKme — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/pull/38980

**Pull request merged**
