### PR TITLE
Updated documentation go.php to 15 and adjusted copyright year.

### LINKED ISSUE #14650: LDAP App in Nextcloud 15 Links to Nextcloud 11 Help Docs
### Steps to reproduce
1. install the 'LDAP user and group backend' app
2. click Help in the app

### Expected behaviour
Links to: https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_auth_ldap.html

### Actual behaviour
Links to: https://docs.nextcloud.org/server/11/go.php?to=admin-ldap

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Source

### PR DESCRIPTION
**Pull request by Faldon**
# Updated stable version
- The stable version number now is 15
- Updated copyright year to 2019

Fixes #14650

### CODE REVIEW

**Comment by kesselb** [comment]
> Fixes #14650

Only if someone uses "example" as theme :sunglasses:

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/11304 we had some discussions about this (see the resolved conversation). I think we should go for `\OC_Util::getVersion()[0]` instead of 14,15,16...

**Comment by Faldon** [comment]
Dynamic resolving would be definitely better. :smiley: 
The reason why I thought "If any, it should go to the stable branch."

Of course, if the version number can be resolved dynamically, than that's the better approach. Is this just legacy remains or is there a reason that anything in the affected file is hardcoded respectively has no dependency on any other file?

**Comment by kesselb** [comment]
> Is this just legacy remains or is there a reason that anything in the affected file is hardcoded respectively has no dependency on any other file?

This file is not used anywhere. It's an example for a custom theme.

**Comment by Faldon** [comment]
Ah, I see.
But to reproduce the issue #14650 I referenced, I set up a complete new development instance. If this file is for example themes, a fresh installation without any modification theme-wise should not call this code then, should it?

**Comment by Faldon** [comment]
It seems, the LDAP plugin does not use any curious method but the buildDocLinkToKey function in the legacy/defaults file.
After the copyright year in footer is already made dynamic in master branch and dynamically resolving the current version is indeed the much better approach, I will close this PR later that day.

**Review by rullzer — APPROVED** [review]
Fine for 15 IMO

**Review by MorrisJobke — APPROVED** [review]
Fine with me 👍

**Comment by MorrisJobke** [comment]
Fixed on master already

**Pull request merged**
