### PR TITLE
Make close icon fill more space

### PR DESCRIPTION
**Pull request by pixelipo**
While working on cleaning up @nextcloud/gallery iconset, I noticed that the .icon-close SVG is disproportionately smaller. It turns out it had a lot more empty space in SVG than other icons. This is only visible when that icon is placed inline with another icon, as is the case in the gallery app.

EDIT: outdated screenshots; look  at next comment
Old `close.svg` had more than 3px margin within SVG; after this PR, it will have 1px. Here's a before:
before

before0

and after:
after

after0

Please notice that in the searchbox, icon gets bigger. @nextcloud/designers is this OK? If not, let me know so I can add:
`background-size: 12px;`
in styles.scss (line 202)

P.S. I think in the sidebar, this icon should be as large as it is in this PR, because it doesn't make sense for the most-clicked icon to be smaller than purely visual ones.

### CODE REVIEW

**Comment by pixelipo** [comment]
Sorry, I think I went overboard with the initial commit; I've pushed a smaller version version, here's a new before/after:
image
image

**Review by MorrisJobke — APPROVED** [review]
I like it 👍

**Review by jancborchardt — APPROVED** [review]
Good catch! :)

**Comment by skjnldsv** [comment]
👍

**Pull request merged**
