### PR TITLE
Fix icons cacher regex for compressed output

### LINKED ISSUE #11131: Accessibility dark theme unusable
In the new accessibility menu, users are presented with new themes which may cater for their preferences, but unfortunately the dark theme is unusable.

Icons are black on a dark grey background.

It should work out of the box or instructions should be provided and the themes disabled until they have been applied

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

Fix #11131

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@skjnldsv many acceptance tests fail

**Comment by MorrisJobke** [comment]
Old CI job: https://drone.nextcloud.com/nextcloud/server/9903
Retriggered one: https://drone.nextcloud.com/nextcloud/server/9908

**Comment by skjnldsv** [comment]
Wow, this change is generating an error 500 on every acceptance test! :confused:

**Comment by skjnldsv** [comment]
@danxuliu any ideas?

**Comment by vwbusguy** [comment]
Does the test environment have the Bookmarks app enabled or one of the others that currently causes 500s in 14rc1?  That would explain the missing element on the apps page, etc. Re: #10920  
I can't imagine how this valid regex change for CSS would have any of these effects.

**Comment by rullzer** [comment]
14 or 15?

**Comment by skjnldsv** [comment]
@rullzer this is a required fix for 14, but I cannot find a proper way to do so :(
This is not a hardbreaking change though. Just affect the dark theme that is set as 'beta' anyway.

**Comment by MorrisJobke** [comment]
> @rullzer this is a required fix for 14, but I cannot find a proper way to do so :(
> This is not a hardbreaking change though. Just affect the dark theme that is set as 'beta' anyway.

Let's not block the 14.0.0 release then.

**Comment by skjnldsv** [comment]
I'm fine with that!

**Comment by rullzer** [comment]
@danxuliu any idea why this breaks everything?

**Comment by danxuliu** [comment]
> any idea why this breaks everything?

[Finally I do](https://github.com/nextcloud/server/pull/11268); the acceptance tests in this pull request _should_ no longer fail if it is rebased after #11268 is merged.

**Comment by blizzz** [comment]
set milestone to 15 as it is against master.

**Comment by danxuliu** [comment]
Rebased onto master now that #11268 was merged.

**Comment by skjnldsv** [comment]
Failure unrelated, I restarted just in case.

**Comment by skjnldsv** [comment]
That's what I thought @nickvergessen can you merge? :)

**Comment by bisherbas** [comment]
Same issue? https://github.com/nextcloud/tasks/issues/214

**Pull request merged**
