### PR TITLE
Delete max-width parameter from alternate-login tag

### PR DESCRIPTION
**Pull request by Becker-Asano**
This time, I signed the commit. Sorry..

Resubmit of https://github.com/nextcloud/server/pull/18998

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@nextcloud/designers Please review :)

**Comment by jancborchardt** [comment]
This was added by @ochorocho via https://github.com/nextcloud/server/pull/16832 – could you review? :)

**Comment by zorn-v** [comment]
Not good idea. I have something like this if remove max-width
изображение

**Comment by kesselb** [comment]
Hmm. This should be fixed by https://github.com/pellaeon/registration then? They might have a look at https://github.com/zorn-v/nextcloud-social-login how to do it properly.

**Comment by zorn-v** [comment]
This was broken here https://github.com/nextcloud/server/commit/7e5956a90632fc2904471ce5c25dd3950bf8d8ab
by setting `width: 100%`

**Comment by ochorocho** [comment]
I think @zorn-v is right. Removing this is not a good idea.

**Review by zorn-v — COMMENTED** [review]
I think some styles of guest page must be rewritten (with cleanup). Maybe with layout change.
Currently one style affect another in unpredictable way, after mixing flexbox with old styles.

**Comment by pellaeon** [comment]
I'm not quite understanding the exact details of this, but this seems to be about the "Register" button issue in pellaeon/registration . This issue was also raised to me by @nickvergessen and it's on our roadmap to be fixed.

**Comment by zorn-v** [comment]
@pellaeon
not related on this issue, but can you increase `max-version` ? )
https://github.com/nextcloud/registration/issues/210

**Comment by nickvergessen** [comment]
Fixing in the registration app with https://github.com/nextcloud/registration/pull/219
It will trim the length when it's the only option to the width of the login button and otherwise it will be as before.

**Comment by MorrisJobke** [comment]
> Fixing in the registration app with [nextcloud/registration#219](https://github.com/nextcloud/registration/pull/219)
> It will trim the length when it's the only option to the width of the login button and otherwise it will be as before.

As there seem to be a fix in another code part I will close this. If this still applies then we can reopen it and check out the issue again.

**Pull request closed without merging**
