### PR TITLE
Fix empty content icons in header on darktheme

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Open notifications dropdown when there are no notifications
2. Open contact search and search for non-existing user

### Before
icons are black/invisible

### After
icons are white/visible

### CODE REVIEW

**Comment by jancborchardt** [comment]
This works for the emptycontent icons, but for the contacts menu the other action icons are dark still:
contacts menu icons

And this needs rebasing onto master because https://github.com/nextcloud/server/pull/13648 was mergd. :)

**Comment by nickvergessen** [comment]
Rebased.

Also working fine here:

> bildschirmfoto von 2019-01-23 12-55-57

But the default rebase solution broke to what you pointed out, so please check again

**Review by jancborchardt — APPROVED** [review]
Not sure what was wrong, looks great now!

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@jancborchardt @skjnldsv @nickvergessen Mind to do the back ports?

**Comment by MorrisJobke** [comment]
> #13648 is missing, should be backported too?

As this one is also not back ported I would leave it in master only.

**Pull request merged**
