### PR TITLE
fix right-click img tags

### LINKED ISSUE #36154: [Bug]: stable25, nextcloud/server@d4b4135 breaks file action menu items using an img tag
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

See #35517, from there:

IMHO, the changes to apps.scss break file-actions which use an img-tag for their icons: the width is now 0, what remains is two times the padding which only makes for 28px instead of the necessary 44px.

And:

What I see is that removing the dimensions of the img tag make it size 0. There two different "icon-providers" in the file-actions menu, the correctly working ones use a span:

```
<a href="#" class="menuitem action action-download permanent" data-action="Download">
    <span class="icon icon-download"></span>
    <span>Herunterladen</span>
</a>
```

The other ones have an img tag:

```
<a href="#" class="menuitem action action-mount-archive permanent" data-action="mount-archive">
  <img class="icon" src="/core/img/actions/external.svg">
  <span>Archiv einhängen</span>
</a>
```

In my view the img has width and height 16px and a padding of 14px. Now, as we have box-sizing=border-box the actual width is then set to 0 and just the padding remains.

### Steps to reproduce

1. Clone the the stable25 nextcloud server branch (used: f74ba9cb5d1)
2. Have a look at a file action menu item for an using an img tag to display its icon
Screenshot_20230116_105510
Screenshot_20230116_105553

### Expected behavior

Icon should have the appropriate size (that it is not visible at all is caused by the padding consuming all of the 16px of available space, caused by box-sizing=border-box).

### Installation method

None

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dev1.home.claus-justus-heine.de"
        ],
        "default_phone_region": "DE",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.1",
        "overwrite.cli.url": "https:\/\/dev1.home.claus-justus-heine.de",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "query_log_file": "",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 0,
        "logfilemode": 432,
        "theme": "",
        "maintenance": false,
        "debug": true,
        "verbose_exceptions": true,
        "session_lifetime": 300,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.debug": false,
        "files_no_background_scan": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\OpenDocument"
        ],
        "app_install_overwrite": [
            "dokuwikiembedded",
            "roundcube",
            "keeporsweep",
            "bruteforcesettings",
            "whiteboard",
            "gpgmailer",
            "cafevdb",
            "redaxo4embedded",
            "ocr",
            "appointments",
            "bav",
            "ownpad",
            "polls",
            "tasks",
            "user_sql",
            "ldap_contacts_backend",
            "forms",
            "files_external_ftp",
            "audioplayer",
            "apporder",
            "circles",
            "richdocumentscode",
            "twofactor_admin",
            "files_texteditor",
            "files_markdown"
        ],
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - announcementcenter: 6.4.0
  - appointments: 1.14.9
  - audioplayer: 3.3.1
  - bav: 0.0.3
  - cafevdbmembers: 0.0.1
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - collectives: 2.1.1
  - comments: 1.15.0
  - contacts: 5.1.0-alpha.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - dokuwikiembedded: 0.0.3
  - event_update_notification: 2.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_archive: 1.1.0
  - files_external: 1.17.0
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.15.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - forms: 3.0.3
  - groupfolders: 13.1.0
  - ldap_write_support: 1.7.0
  - libresign: 6.2.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - maps: 0.2.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - pdf_downloader: 1.1.1-rc1
  - photos: 2.0.1
  - polls: 4.1.0-beta6
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - redaxo4embedded: 0.0.3
  - richdocuments: 7.1.0
  - richdocumentscode: 22.5.802
  - roundcube: 1.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - suspicious_login: 4.2.1
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - terms_of_service: 2.0.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_admin: 4.1.9
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.7.1
  - twofactor_gateway: 0.20.0
  - twofactor_nextcloud_notification: 3.5.0
  - twofactor_totp: 6.4.1
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_sql: 4.7.1
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit: 1.9.0
  - apporder: 0.15.0
  - bruteforcesettings: 2.4.0
  - cafevdb: 8.0.1
  - documentserver_community: 0.1.13
  - electronicsignatures: 2.0.1
  - encryption
  - external: 5.0.0
  - fileslibreofficeedit: 1.1.0
  - gpgmailer: 0.0.4
  - ldap_contacts_backend: 1.4.0
  - scanner: 0.2.3
  - side_menu: 3.5.0
  - testing
  - twofactor_u2f: 6.3.0
  - user_backend_sql_raw: 1.3.0
  - whiteboard: 0.0.3
  - workflow_pdf_converter: 1.10.0
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #36832: [Bug]: Nextcloud 25 : The "Edit locally" icon is a SVG file called like a regular img file (<img src="...) : Does not appear.
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Everything is in explained in the title and in the screenshots bellow : 

### Steps to reproduce

1. Go to Files
2. Click on [⋅⋅⋅]
3. See that the local editing icon doesn't appear.

### Expected behavior

The "Edit locally" icon is a SVG file called like a regular img file (<img src="...) : Does not appear.

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc25.test.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "25.0.3.2",
    "overwrite.cli.url": "https:\/\/nc25.test.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nc25.test.mydomain.fr\/nextcloud.log",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 8,
        "timeout": 0
    },
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "skeletondirectory": "",
    "logtimezone": "Europe\/Paris",
    "updater.release.channel": "stable",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "default_language": "fr",
    "default_phone_region": "FR",
    "defaultapp": "files",
    "trashbin_retention_obligation": "20,40",
    "versions_retention_obligation": "auto,40",
    "check_for_working_wellknown_setup": false,
    "quota_include_external_storage": false,
    "cron_log": true,
    "has_internet_connection": true,
    "updatechecker": true,
    "appstoreenabled": true,
    "filelocking.enabled": true,
    "session_keepalive": true,
    "knowledgebaseenabled": true,
    "allow_user_to_change_display_name": true,
    "enable_previews": true,
    "enable_avatars": true,
    "auth.bruteforce.protection.enabled": true,
    "loglevel": 1,
    "log_rotate_size": 104857600,
    "mail_smtpauth": 1,
    "mail_smtpport": 465,
    "session_lifetime": 86400,
    "remember_login_cookie_lifetime": 1296000,
    "preview_max_filesize_image": 50,
    "activity_expire_days": 120,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "maintenance": false,
    "app_install_overwrite": [
        "workspace",
        "impersonate",
        "files_trackdownloads",
        "rocketchat_nextcloud"
    ]
}
```

### List of activated Apps

```shell
Enabled:
 - activity: 2.17.0
 - admin_audit: 1.15.0
 - announcementcenter: 6.5.0
 - calendar: 4.2.3
 - circles: 25.0.0
 - cloud_federation_api: 1.8.0
 - collectives: 2.3.0
 - contacts: 5.1.0
 - contactsinteraction: 1.6.0
 - cookbook: 0.10.1
 - dashboard: 7.5.0
 - data_request: 1.12.0
 - dav: 1.24.0
 - deck: 1.8.3
 - drop_account: 2.1.0
 - federatedfilesharing: 1.15.0
 - federation: 1.15.0
 - files: 1.20.1
 - files_downloadactivity: 1.15.0
 - files_external: 1.17.0
 - files_lock: 24.0.1
 - files_pdfviewer: 2.6.0
 - files_rightclick: 1.4.0
 - files_sharing: 1.17.0
 - files_trashbin: 1.15.0
 - files_versions: 1.18.0
 - firstrunwizard: 2.14.0
 - forms: 3.1.0
 - groupfolders: 13.1.1
 - guests: 2.3.0
 - impersonate: 1.11.0
 - logreader: 2.10.0
 - lookup_server_connector: 1.13.0
 - mail: 2.2.3
 - metadata: 0.17.0
 - nextcloud_announcements: 1.14.0
 - notes: 4.6.0
 - notifications: 2.13.1
 - oauth2: 1.13.0
 - onlyoffice: 7.6.8
 - password_policy: 1.15.0
 - photos: 2.0.1
 - privacy: 1.9.0
 - provisioning_api: 1.15.0
 - recognize: 3.5.0
 - recommendations: 1.4.0
 - related_resources: 1.0.4
 - richdocuments: 7.1.1
 - rocketchat_nextcloud: 0.9.6
 - serverinfo: 1.15.0
 - settings: 1.7.0
 - sharebymail: 1.15.0
 - snappymail: 2.26.3
 - spreed: 15.0.3
 - support: 1.8.0
 - systemtags: 1.15.0
 - text: 3.6.0
 - theming: 2.0.1
 - theming_customcss: 1.12.0
 - twofactor_backupcodes: 1.14.0
 - updatenotification: 1.15.0
 - user_ldap: 1.15.0
 - user_migration: 2.0.1
 - user_status: 1.5.0
 - viewer: 1.9.0
 - weather_status: 1.5.0
 - welcome: 1.0.8
 - workflowengine: 2.7.0
 - workspace: 2.0.0
Disabled:
 - bruteforcesettings
 - comments: 1.15.0
 - encryption
 - group_everyone: 0.1.11
 - survey_client: 1.13.0
 - suspicious_login
 - twofactor_totp
 - unsplash: 2.2.0
 - workflow_pdf_converter: 1.10.0
 - workflow_script: 1.10.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Can be provided if necessary
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by szaimen**
Follow-up to https://github.com/nextcloud/server/pull/35484

Fix https://github.com/nextcloud/server/issues/36832
Fix https://github.com/nextcloud/server/issues/36154

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Comment by szaimen** [comment]
doesnt seem to work in my testing...

**Comment by rotdrop** [comment]
Are you sure that this fixes #36154? We  have still the width and height of the image tag set to 16px and its padding set to 14px. And box-sizing border-box. But this means that regardless of your change the following lines:

https://github.com/nextcloud/server/blob/86c102ed9961121bba0cef00e0d35ad2935b41cf/core/css/apps.scss#L1144-L1147

will still result in total size of 28px ("border-box" means that content + padding make up for the size, doesn't it?)

I have only tested your changes with NC25 and it does not seem to change anything. BTW, also the "Edit locally" menu item is affected and does not show the icon.

Is maybe the ":not()" wrong? At least #36154 talks about the very filesActionMenu and the :not() excludes it. So your CSS rules changes do not affect the filesActionMenu. If I remove the `not(...)` then the issues with the files-action menu described in #36154 seem to be fixed for NC 25.

**Review by rotdrop — APPROVED** [review]
This seems to fix the issue. However, I suppose the lines 

https://github.com/nextcloud/server/blob/86c102ed9961121bba0cef00e0d35ad2935b41cf/core/css/apps.scss#L1144-L1147

should be revisited as my impression is that these settings do not make sense with box-sizing `border-box`. Just mentioned it here because that rule makes the reviewed changes "necessary" and maybe are bogus. But this is probably something for a separate new issue.

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
