### PR TITLE
Remove unused import statements

### PR DESCRIPTION
**Pull request by MorrisJobke**
Found via PHPStorm PHP inspections

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Fine by me

**Review by ChristophWurst — DISMISSED** [review]
Please just remove those lines and not insert a blank one 😉

**Comment by MorrisJobke** [comment]
> Please just remove those lines and not insert a blank one 😉

What did PHPStorm do there -.-

**Review by ChristophWurst — APPROVED** [review]
Better ;)

**Pull request merged**
