### PR TITLE
Cancel user search requests to avoid duplicate results being added

### PR DESCRIPTION
**Pull request by juliusknorr**
Fixes issues where users where added multiple times when typing into the search due to slow requests still pending when the new search request for the updated query was issued.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
This will go before https://github.com/nextcloud/server/pull/24721

**Comment by ChristophWurst** [comment]
> This will go before #24721

Will it?

Bildschirmfoto von 2020-12-16 13-27-48

**Comment by skjnldsv** [comment]
> Will it?

I had an automerge enabled on this one ;)

**Pull request merged**
