### PR TITLE
Caching and compression for app store requests

### PR DESCRIPTION
**Pull request by MorrisJobke**
While looking into our apps.nextcloud.com server I realized that the requests are not compressed. Even if the server supports it the clients don't request it. Thus the server sends out 5 MB instead of the compressed 2 MB. This and the raised cache time of 60 instead of 5 minutes should reduce the overall load of the app store server quite a lot.

As those are quite small changes I would backport them down to stable16.

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
LGTM :+1:

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by rullzer** [comment]
The tests say no

**Comment by MorrisJobke** [comment]
> The tests say no

I fixed them :) Wasn't as easy as a lot of logic was hidden in `getTime` values.

**Comment by ChristophWurst** [comment]
I wonder if this should be generally the default for our http client. Would there be any downside to that?

**Comment by rullzer** [comment]
> I wonder if this should be generally the default for our http client. Would there be any downside to that?

Not really actually. Saying that we support gzip is fine IMO

**Comment by MorrisJobke** [comment]
> I wonder if this should be generally the default for our http client. Would there be any downside to that?

I would keep it like that for the backports and enable it for 20 in the default client?

**Comment by MorrisJobke** [comment]
CI is fine -> merge

**Comment by MorrisJobke** [comment]
> I would keep it like that for the backports and enable it for 20 in the default client?

https://github.com/nextcloud/server/pull/21054

**Pull request merged**
