### PR TITLE
Add PHP 5.4 and 5.5 jobs to CI

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @rullzer

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1: 

btw, would it be possible to split the jobs so they show up separately so it's easy to see which one failed

**Comment by MorrisJobke** [comment]
This is planned for the new UI of drone (ETA mid July, but you know how releases in projects behave). But I will have an eye on it. 😉

**Comment by LukasReschke** [comment]
Thanks, @nextcloud-bot!

**Comment by MorrisJobke** [comment]
stable9: #329

**Pull request merged**
