### PR TITLE
more efficient querying of numeric storage ids

### PR DESCRIPTION
**Pull request by icewind1991**
- [x] requires #1245

Saves 2 queries for every external storage configured

Not the nicest code but I blame the existing `Cache\Storage` for that

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> requires #1245

@icewind1991 This is in now. Could you rebase and resolve the conflict?

**Comment by icewind1991** [comment]
rebased, fixed tests, ready for review

**Comment by MorrisJobke** [comment]
@rullzer Mind to take a look?

**Comment by rullzer** [comment]
Code makes sense. Indeed not the cleanest but no real way around it at the moment.

Quick test with external storages showed they still works.

Fine by me :+1:

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
