### PR TITLE
Fix UX of renaming token

### LINKED ISSUE #34245: [Bug]: Cannot rename session under Devices & Sessions
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Cannot rename session/device in Settings > Security > Devices & Sessions

Nextcloud 25 RC

### Steps to reproduce

1. Navigate to Settings > Security > Devices & Settings 
2. Click ellipsis icon and choose "Rename" 
3. Nothing happens (no prompt for new name)

### Expected behavior

Clicking "Rename" should prompt for a new name.

### Installation method

Community VM appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.0.0-alpha.1
  - circles: 25.0.0-alpha.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.0-alpha.3
  - contactsinteraction: 1.6.0
  - cookbook: 0.9.15
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.0-beta.2
  - external: 4.1.0
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - files: 1.20.0
  - files_antivirus: 3.3.1
  - files_automatedtagging: 1.15.0
  - files_fulltextsearch: 24.0.1
  - files_pdfviewer: 2.6.0
  - files_retention: 1.13.2
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_videoplayer: 1.14.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.14.0
  - forms: 3.0.0-beta.1
  - fulltextsearch: 24.0.0
  - holiday_calendars: 0.1.0
  - imageconverter: 1.3.2
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.0-beta.7
  - maps: 0.2.1
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - occweb: 0.1.0
  - password_policy: 1.15.0
  - pdf_downloader: 1.0.6
  - photos: 1.7.1
  - previewgenerator: 5.1.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - radio: 1.0.3
  - recognize: 3.0.0-beta.3
  - recommendations: 1.4.0
  - related_resources: 1.0.0
  - richdocuments: 7.0.0-beta.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 2.5.1
  - socialsharing_email: 2.5.0
  - systemtags: 1.15.0
  - tasks: 0.14.4
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_migration: 1.1.0
  - user_status: 1.5.0
  - video_converter: 1.0.5
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflow_ocr: 1.24.5
  - workflow_pdf_converter: 1.10.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.4.0
  - drawio: 1.0.3
  - encryption: 2.13.0
  - facerecognition
  - federation: 1.13.0
  - files_external: 1.15.0
  - files_fulltextsearch_tesseract: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - guests: 2.3.0
  - impersonate: 1.11.0
  - metadata: 0.16.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - suspicious_login
  - user_ldap
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by CarlSchwan**
Now this get's instant applied and escaping will reset to the previous state

Fix #34245

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by szaimen** [comment]
Does this fix https://github.com/nextcloud/server/issues/34245?

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
> Does this fix #34245?

@CarlSchwan ?

**Comment by CarlSchwan** [comment]
> Does this fix #34245?

yes

**Pull request merged**
