### PR TITLE
Set the moment locale even earlier

### PR DESCRIPTION
**Pull request by ChristophWurst**
We did this early, but not early enough.

Steps to reproduce
* Set locale and language to anything but English
* Open personal security settings
* See the sessions/devices list

Master: (Relative) time shown in English
Here: (Relative) time shown in your set language/locale

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by ChristophWurst** [comment]
jsunit passes. I'm so relieved.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by kesselb** [comment]
Very nice. I think there are some reports around for that problem.

**Comment by nickvergessen** [comment]
No, it's not about the issue you have in mind

**Comment by kesselb** [comment]
> No, it's not about the issue you have in mind

I know which issue you are talking about ;) For the sake of completeness: https://github.com/nextcloud/server/issues/14907 (that seems pretty much what is fixed with this pr)

**Pull request merged**
