### PR TITLE
Replace submit-icon with icon-confirm-white / icon-loading-small

### LINKED ISSUE #19939: [Design] Password reset arrow
Check this screenshot, arrow is far away from the button.
Both Firefox and Chrome, **fresh install of NC 18.0.2.**

image

**On NC 17.0.3** (not great but at least they're inline)
image

### PR DESCRIPTION
**Pull request by kesselb**
Fix #19939 

I believe using a class to attach such icon is the preferred way instead of using a dedicated element.

### CODE REVIEW

**Review by danxuliu — COMMENTED** [review]
This fixes the layout in the password reset screen, but breaks the animation that moves [the arrow to the right when hovering on the input](https://github.com/nextcloud/server/blob/c97aa97814ec31234bd7edb8f57c8ecaca976b05/core/css/guest.css#L217-L221) in the main login screen.

I do not know if it is possible to get that animation with the icon class. If it is not personally I have no preference about having an animation or using the preferred icon class.

**Comment by kesselb** [comment]
Thanks @danxuliu for review :+1: 

You are right the fancy animation is gone :fearful: 

```
	.icon-confirm-white:hover,
	.icon-confirm-white:focus,
	.icon-confirm-white:active {
		background-position: right 12px center
	}
```

I can fix that by adding above to `Login.vue`. Unfortunately the styles in that component are not scoped. The alternative is to add the block to `LoginForm.vue`, `ResetPassword.vue` and `UpdatePassword.vue`.

**Comment by nickvergessen** [comment]
Before | After
---|---
Peek 2020-03-24 21-02 | Peek 2020-03-24 21-02a

I think it looks worse than before?

**Comment by kesselb** [comment]
Primary goal of this PR is not the fancy loading animation ;) I wanted to fix the arrow on the password reset page. I'm happy to pass this on the a frontend developer :art:

**Comment by skjnldsv** [comment]
@kesselb 

> Primary goal of this PR is not the fancy loading animation ;)

We're using pseudo elements for the loader, and it cannot work on inline elements like button. There is no support of ::after/::before :)

**Comment by kesselb** [comment]
What do you suggest to fix the linked issue?

**Comment by skjnldsv** [comment]
Change the icons, but do not replace the <div class="submit-icon">

**Pull request closed without merging**
