### PR TITLE
fix(files): cancel renaming on enter if no file name changes

### PR DESCRIPTION
**Pull request by skjnldsv**
If no changes have been made, pressing enter should also cancel the rename.
- [x] Test for ESC press
- [x] Test for Enter press without changes

### CODE REVIEW

**Comment by skjnldsv** [comment]
Cypress will pass once the compiled assets are commited

**Review by artonge — APPROVED** [review]

**Review by nfebe — APPROVED** [review]

**Comment by provokateurin** [comment]
I think this broke CI: https://github.com/nextcloud/server/actions/runs/12255492578/job/34190215905?pr=49747

**Comment by skjnldsv** [comment]
Weird, this passed :thinking:

**Comment by skjnldsv** [comment]
Rebase your PR, seems like it works :thinking:

**Pull request merged**
