### PR TITLE
Fix dark theme in file exists dialog

### LINKED ISSUE #22748: Dark theme : black on black in file conflict popup
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Please excuse me if there is a duplicate I couldn't find.

### Steps to reproduce
1. Enable dark theme
2. Upload an already existing file

### Expected behaviour
I can read the text in the confict popup

### Actual behaviour
The text is in a black font, so I can't read it

image

Nextcloud version : 19.0.2

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/22748

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
Failing test is unrelated

**Review by Pytal — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Review by julien-nc — APPROVED** [review]
Nice catch!

**Comment by szaimen** [comment]
@eneiluj do you have force-merge rights?

**Comment by eneiluj** [comment]
@szaimen Nowpe :grin:

**Comment by szaimen** [comment]
> Nowpe 😁

Okay

**Comment by szaimen** [comment]
Merging because failing test is unrelated

**Pull request merged**
