### PR TITLE
Move log out and backup codes link into 2fa box for better readability

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/2538

## Without backup codes
bildschirmfoto von 2016-12-12 10-13-17
bildschirmfoto von 2016-12-12 10-12-09
## With backup codes
bildschirmfoto von 2016-12-12 10-17-27
bildschirmfoto von 2016-12-12 10-17-19

### CODE REVIEW

**Comment by skjnldsv** [comment]
Could we use buttons for the "cancel login" and "use backup code" ? :)

Otherwise: 👍

**Comment by jancborchardt** [comment]
Also, the »Authenticate with a TOTP app« doesn’t look clickable really. We should use a button there, which should be as big as the input field (or button on the log in page).

Then smaller side-by-side buttons for the options below.

**Comment by ChristophWurst** [comment]
> Also, the »Authenticate with a TOTP app« doesn’t look clickable really. We should use a button there, which should be as big as the input field (or button on the log in page).

https://github.com/nextcloud/server/blob/master/core/templates/twofactorselectchallenge.php have fun :-)

> Then smaller side-by-side buttons for the options below.

That's what we had before but depending on the language the text can be too long for one line. For example the German translation caused it to break, which looked odd. I'd prefer to have one below the other because that's easier to read IMO.

**Comment by ChristophWurst** [comment]
@jancborchardt could you please help me with the styling here? I don't know what it should look like :-)

**Comment by rullzer** [comment]
Can we get this in and fix additional styling later or close this?

**Comment by skjnldsv** [comment]
@rullzer please wait for my login-update-install css fix.
Then it will be easier :)

**Comment by skjnldsv** [comment]
Okay, see #3004

**Comment by jancborchardt** [comment]
#3004 is merged, so we can go ahead here? :)

@ChristophWurst just using class="button primary" for the primary button (»Auth with TOTP app«) and class="button" for the other two ones (»Cancel log in« and »Use backup code«) should work nicely. :)

**Comment by ChristophWurst** [comment]
blocked by #3207

**Comment by MorrisJobke** [comment]
> blocked by #3207

Merged -> unblocked 😝

**Comment by MorrisJobke** [comment]
@ChristophWurst Any news here? I would love to see this merged ;)

**Comment by skjnldsv** [comment]
While you're at it, could you set the default mobile keyboard to number only @ChristophWurst  :)
http://mobileinputtypes.com/#tel

**Comment by ChristophWurst** [comment]
@jancborchardt I've changed the links to buttons. Doesn't look good IMO. Could you please help me with the styling? Thanks
bildschirmfoto von 2017-03-06 11-00-46

**Comment by rullzer** [comment]
@jancborchardt please have a look here. Else I'll just merge it and you have to fix master :wink:

**Comment by ChristophWurst** [comment]
@rullzer so… merge? 😉

**Pull request merged**
