### PR TITLE
Add comicbook mimetypes

### PR DESCRIPTION
**Pull request by rullzer**
Cherry picked from #9496 

Then we can move that to a separate app for 14.

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Comment by icewind1991** [comment]
Note that apps can register their own mimetypes

```php
\OC::$server->getMimeTypeDetector()->registerType('foo', 'application/foo');
```

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
@rullzer Signoff-missing, but I guess that's fine for such a minor change.

**Comment by MorrisJobke** [comment]
What about repair steps? Otherwise there are old entries in the index.

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Repair steps for existing mime types is missing.

**Comment by NoMoreNicksLeft** [comment]
It's been awhile since i checked, but I remember entries with the old mime types being updated to the new ones once this was in the codebase. I wasn't running an occ scan either. I didn't explore which mechanism was doing it either, since it just worked... assumed you guys were doing something clever there.

**Comment by MorrisJobke** [comment]
> It's been awhile since i checked, but I remember entries with the old mime types being updated to the new ones once this was in the codebase. I wasn't running an occ scan either. I didn't explore which mechanism was doing it either, since it just worked... assumed you guys were doing something clever there.

Kind of ;) https://github.com/nextcloud/server/blob/master/lib/private/Repair/RepairMimeTypes.php#L208-L210

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
