### PR TITLE
Use GHCR PHP 7.3 Acceptance Container

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by gary-kim** [comment]
Do they have the correct extensions enabled? All the acceptance containers seem to be failing: https://drone.nextcloud.com/nextcloud/server/5578/64/4

**Review by gary-kim — CHANGES_REQUESTED** [review]
See above

**Comment by gary-kim** [comment]
Should be fixed once https://github.com/nextcloud/docker-ci/pull/285 is merged then `php7.3` gets rebuilt then `acceptance-php7.3` gets rebuilt.

**Comment by LukasReschke** [comment]
Thanks @gary-kim. I've bumped all the versions :)

**Comment by LukasReschke** [comment]
Merging as this mitigates CI issues in master.

**Pull request merged**
