### PR TITLE
Small improvements for personal settings

### PR DESCRIPTION
**Pull request by juliusknorr**
- Add icon to the group list
- Move quota bar from the top below the users group list and make it look less bold

Further I implemented the comments from #9218 by @jancborchardt:
- Fix avatar details text alignment
- Move visibility settings from the right side to the text 

image

Please review @nextcloud/designers 

@karlitschek

### CODE REVIEW

**Comment by MariusBluem** [comment]
I think this will need some adjustments for the `external`-app and its quota link 🤔 @nickvergessen

**Comment by karlitschek** [comment]
awesome! 👍

**Comment by jancborchardt** [comment]
Great, looks much better! Also good choice on putting the quota bar down. :)

Just one thing: It looks a bit strange how between the fields like name, email, phone etc there's very little horizontal space, but a lot of vertical space. I assume that's a lot due to the password section being so tall? How about we change the password section from all fields being visible to just a button saying "Change password", expanding to show the fields? Or even just a text link in the "Details" section? Cause it's different from the other details in this list.

**Comment by jancborchardt** [comment]
Same for the language dropdown btw, it doesn't fit with the rest of the details which are possibly visible to others. Should also go into the Details section.

**Comment by rullzer** [comment]
@juliushaertl what is you call here. Merge and make issues for the rest? Or fix now?

**Comment by juliushaertl** [comment]
> Let's get this in now and continue with the other stuff later.

:+1: I'll open issues for the remaining stuff, so we can discuss them a bit further.

**Comment by nickvergessen** [comment]
Only minor thing, but since we show the icon for the group memberships, should we also show `icon-quota` next to the quota bar?

**Comment by nickvergessen** [comment]
> I think this will need some adjustments for the external-app and its quota link thinking 

Thanks @MariusBluem , opened an issue at https://github.com/nextcloud/external/issues/94

**Comment by juliushaertl** [comment]
> Only minor thing, but since we show the icon for the group memberships, should we also show icon-quota next to the quota bar?

That was the intention. I forgot to add the icon to the commit. Should be fixed now.

**Comment by MorrisJobke** [comment]
Just want to let you know - this is not fully supported in Edge/IE and thus it is full with for all entries:

bildschirmfoto 2018-05-03 um 10 35 02

**Comment by nickvergessen** [comment]
> That was the intention. I forgot to add the icon to the commit. Should be fixed now.

Yeah works very well now :)

**Comment by juliushaertl** [comment]
@MorrisJobke https://github.com/nextcloud/server/pull/9218#pullrequestreview-113112186 :grin: 

We could support IE with some additional vendor prefixed rules, not sure if it is worth the work here.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
I just added one commit that fixed the quota text for "unlimited quota" users:

Before:
bildschirmfoto 2018-05-03 um 10 49 29

After:
bildschirmfoto 2018-05-03 um 10 49 21

**Review by rullzer — APPROVED** [review]
Lets do it!

**Pull request merged**
