### PR TITLE
Fix german spelling

### PR DESCRIPTION
**Pull request by Bloodsoul**
... for when no compatible app version is available

### CODE REVIEW

**Comment by kesselb** [comment]
Thank you for reporting :+1: 

We are using Transifex to manage translations. Please join https://www.transifex.com/nextcloud/nextcloud/ to help. It's also possible to sign up with your GitHub account.

Translations are synced daily from Transifex to GitHub. Any change related to translation must be done there otherwise they are lost.

**Comment by Bloodsoul** [comment]
Thanks for the replay. Please feel free to take it over.
I don't really know how to work with transifex myself.

**Comment by kesselb** [comment]
cc @rakekniven

**Comment by rakekniven** [comment]
Just applied your fix to Transifex resource. Closing here.

**Pull request closed without merging**
