### PR TITLE
fix(settings): emails actions a11y and design

### PR DESCRIPTION
**Pull request by ShGKme**
## Summary

* Revert, a part of refactoring of `FederationActions.vue` from https://github.com/nextcloud/server/pull/43488/
  * `NcActions` doesn't support having `non-NcAction*` as direct children which causes a11y issues
* Change the design of additional emails and their actions, close to the old design
  * Use 2 buttons instead of 2-level menu
  * Show "This address is not confirmed" as input description instead of a caption in a menu
  * Add a gap between additional emails, otherwise they overlaps
  * Remove a margin on the right after actions
  * Renamed label "Additional email address N" with "Additional email N"

## Screenshots

All screenshots are taken on the layout with the smallest width of inputs

Old design | Before | After
---|---|---
emails-old | emails-before | emails-new

After design discussions:

image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ShGKme** [comment]
> Then we either should throw / show an error when non NcAction* components are used

Yep, though about it, should be added

> or fix the NcActions component to properly handle those. Otherwise this sounds like a hack.

I don't see any reliable way to fully fix this case, except quite complex solutions. Having several days before the final a11y testing and only a single place with this issue I'd prefer to go with a simple solution in place.

> Is this accessibility related?

Both.

From a design perspective, I'd try to avoid multi-level menus for simplicity and having a short way to the required action. It makes sense in a large menu, but here we have only 1-2 actions outside of the federation scope.

From an a11y perspective, I'm not sure. Neither submenu button nor the back button has anything except a text telling the user that it changes the menu, and I don't know if it is fine or not. 

For example, in Files "Set reminder" has a bit broken focus behavior and no labeling that "Set reminder" on submenu is actually a Back button.

In this place, for me, NVDA doesn't react on moving to the submenu and back until I press an arrow key.

In general, I'd say we should have an interface to provide submenus out of the box in `NcActions`.

> @nextcloud/designers whats your opinion here? Asking because for me it looks odd that the secondary email input fields now are a different width than the primary email.

We can also make the first input shorter 😀

**Comment by ShGKme** [comment]
> Or use label outside for additional emails same as other labels on this page. Then scope federation menu can be on the label.

Draft:

image

**Comment by susnux** [comment]
Or make the federation scope the trailing button? Then all input fields have the same width.

**Comment by ShGKme** [comment]
> Or make the federation scope the trailing button? Then all input fields have the same width.

But we cannot put `NcActions` to the trailing button, `NcInputField` slot is only for an icon

**Review by jancborchardt — COMMENTED** [review]
> Or make the federation scope the trailing button? Then all input fields have the same width.

The federation scope looks better next to the label, and also makes more sense next to it as it is closer to its description.

---

@ShGKme I would be fine with your draft too. If accessibility-wise it is fine to have the button floating inside the input (on the right) like in the old design, then we could do that?
It would accomodate the actions, and ensure that all fields have the same width. It is also commonly done with e.g. password input visibility buttons.

**Comment by ShGKme** [comment]
> If accessibility-wise it is fine to have the button floating inside the input (on the right) like in the old design, then we could do that?

It is a problem implementation-wise with our input fields.

First, we can only specify an icon for the trailing button but not the button. So we cannot put an actions menu there.

Second, on error/success state there is always an icon.

image

All these problems are solvable, but with dirty hacks.

**Comment by ShGKme** [comment]
@jancborchardt Is it fine?

image

**Review by JuliaKirschenheuter — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Yeah, that looks great in fact! :) The error icon was just duplicated so good on removing it.

**Review by susnux — APPROVED** [review]
Designers said looks good, code looks fine, so :+1:  :smile:

**Comment by ShGKme** [comment]
- Rebased onto `master`
- Squashed `fixup` commits
- A small change - keep original input top padding to be consistent with all of the other inputs
- A small change - moved styles with margin between additional emails from `Email` component to `EmailSection` component

**Review by Pytal — APPROVED** [review]
Tested, and is much nicer!

**Comment by Pytal** [comment]
Cypress is related

**Comment by skjnldsv** [comment]
Thanks for this @ShGKme !! :bow: :hugs:

**Comment by ShGKme** [comment]
Backport is not needed, at least, unless #43488 is backported

**Pull request merged**
