### PR TITLE
[stable11] LDAP's checkPassword should only catch when a user was not found

### LINKED ISSUE #2431: App passwords vanish
### Steps to reproduce
1. Enable TOTP Plugin in 
2. Create 2 or more App Passwords
3. After some time the Desktop App starts asking for the per-device Token.

### Expected behaviour
App Passwords (per-device passwords) should work infinite, 

### Actual behaviour
somehow the app passwords vanish from the personal menu in NC. I have to genereate a new App Password, then the Desktop Client works again.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mysql

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page) 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** NC tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
		- lib/private/Share/MailNotifications.php
	- EXTRA_FILE
		- resources/config/mimetypemapping.json

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 013e97237eeb9627ac398a50d0924621f1faa5d84ba94ab7bcc4970fbf6af55232afcf9bdef601f7f8fd6663e8e59bcb32877fd6353e893fde2c63c0893f537c
                            [current] => 1533e80c77d5eb738008b5c4c045ea014fe3653053c4c118e1eca267c4e56102788ed31a5d79d6041f1e639fa5ab55d060ea0035980fbb4915989a36ebcf96f0
                        )

                    [lib/private/Share/MailNotifications.php] => Array
                        (
                            [expected] => ff4d6280890f3d370907086c8f920a51674c72224ab5cf865b1ae42140ea2c614bb03cc0547a59205810d62e35a3d365925738d7983375e272acf826bce1633f
                            [current] => 1875a25f8593737e2e3e00b0e2ecccb14471a844922f5232275cc69ceddc144b5b6bbde350aad5f817164e390808c3c3b9ca8fe76ad6cb037e4ad7498a1a5366
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [resources/config/mimetypemapping.json] => Array
                        (
                            [expected] => 
                            [current] => e98fd0313bc3ced2ab0d92d87d73cf38b3104c93cafce38ebd079d2c0b419378831b9d7635df8e078dc2bd56ef7b141e78fdea6a8012c471843509cef6a427bc
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: true
  - dav: 1.0.0
  - documents: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_external
  - firstrunwizard
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'nc.niedermayr.net',
    1 => 'oc.niedermayr.net',
    2 => 'nct.niedermayr.net',
  ),
  'datadirectory' => '/var/www/nc.niedermayr.net/data',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'oc_niedermayr_net',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_niedermayr_ne',
  'dbpassword' => '',
  'installed' => true,
  'defaultapp' => 'activity',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'secret' => '',
  'mail_from_address' => 'oc',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'niedermayr.net',
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    0 => '/tmp/redis.sock',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{XXXX:993/imap/ssl}INBOX',
      ),
    ),
  ),
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'updater.release.channel' => 'stable',
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

yes, user_external (imap)

### Client configuration
**Browser:**

Palemoon X64 / Linux

**Operating system:**

Ubuntu 16.04

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by blizzz**
Backport of #3324 fixes #2431 (at least partly for LDAP users)

Would be good to get it into today's RC 2

@karlitschek backport granted?

### CODE REVIEW

**Comment by blizzz** [comment]
summoning @nextcloud/ldap :)

**Comment by karlitschek** [comment]
please backport 👍

**Review by LukasReschke — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by oparoz** [comment]
:dancer::dancers::dancers::dancers::dancer:

**Pull request merged**
