### PR TITLE
[stable25] fix NC25 for 32-bit

### LINKED ISSUE #34674: [Bug]: TypeError: Return value of OCA\DAV\Connector\Sabre\FilesPlugin::OCA\DAV\Connector\Sabre\{closure}() must be of the type int or null, float returned
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to Nextcloud version 25 today, I was unable to view my files getting this error:
```
This directory is unavailable, please check the logs or contact the administrator
```

### Steps to reproduce

1. Upgrade to Nextcloud version 25
2. Try to access files

### Expected behavior

I expect the file app to work normally

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{                                  
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "klapstuhl.maxicarlos.de"
        ],
        "default_phone_region": "ES",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.0.18",
        "overwrite.cli.url": "https:\/\/klapstuhl.maxicarlos.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "enable_previews": true,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }   
}
```

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - previewgenerator: 5.1.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.16.0
  - calendar: 4.0.1
  - circles: 24.0.1
  - dashboard: 7.4.0
  - deck: 1.7.1
  - drawio: 1.0.3
  - encryption
  - federation: 1.14.0
  - files_external
  - files_texteditor: 2.14.0
  - mail: 2.0.3
  - maps: 0.2.1
  - music: 1.6.0
  - nextcloud_announcements: 1.13.0
  - recommendations: 1.3.0
  - spreed: 15.0.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - suspicious_login
  - tasks: 0.14.5
  - user_ldap
  - weather_status: 1.4.0
```

### Nextcloud Signing status

```shell
Does not work, it redirects to /apps/files (which gives me the above error)
```

### Nextcloud Logs

```shell
[webdav] Error: TypeError: Return value of OCA\DAV\Connector\Sabre\FilesPlugin::OCA\DAV\Connector\Sabre\{closure}() must be of the type int or null, float returned at <<closure>>

 0. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 95
    OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 1. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 356
    Sabre\DAV\PropFind->handle()
 2. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties()
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit()
 4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode()
 5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath()
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus()
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus()
 8. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind()
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
11. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
12. /var/www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
13. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
14. /var/www/nextcloud/remote.php line 167
    require_once("/var/www/nextcl ... p")

PROPFIND /remote.php/dav/files/maxi/
from 192.168.1.1 by maxi at 2022-10-19T17:26:42+00:00
```

### Additional info

I'm running Nextcloud on a 64 bit raspberry pi 4b, however `https://server.url/settings/admin/overview` tells me that:
```
It seems like you are running a 32-bit PHP version. Nextcloud needs 64-bit to run well. Please upgrade your OS and PHP to 64-bit! For further details read [the documentation page about this ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-system-requirements).```
And the documentation link is broken (file not found)

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/34674

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by sunjam** [comment]
Does this mean 32-bit is still supported @szaimen ?

**Comment by szaimen** [comment]
> Does this mean 32-bit is still supported @szaimen ?

Only for 25. NC26 has the compatibility officially removed.

**Comment by sunjam** [comment]
@szaimen Thank you, I've seen it.  I want to know if this fix means 32-bit support is now available in nc25 or not.

**Comment by szaimen** [comment]
The fix will be available in 25.0.2

**Comment by lapineige** [comment]
Problem still here after an upgrade from 25.0.1.
It's even worse: Internal Server Error, and no longer access to any app (instead of Files app not working alone)

> "File":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","Line":68,"message":"Cannot assign float to property OC\\Files\\Storage\\Wrapper\\Quota::$quota of type ?int","exception":{},"CustomMessage":"Cannot assign float to property OC\\Files\\Storage\\Wrapper\\Quota::$quota of type ?int"

**Comment by lapineige** [comment]
Fixed by changing the Quota.
It was 50GB.

`sudo -u nextcloud phpVERSIONnumber occ user:setting accountName files quota 50000000000` did fix it.
In fact a quota with "GB" inside and not a number trigger the bug.

**Comment by userloris** [comment]
@lapineige I got the same error after the upgrade to NC 25.0.2. I solved replacing "int" with "float" into the file Quota.php, as following
diff /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php.bak
44c44
<       protected ?float $quota;
---
>       protected ?int $quota;
62c62
<       public function getQuota(): float {
---
>       public function getQuota(): int {
104c104
<        * @return float|bool
---
>        * @return int|bool
131c131
<        * @return float|false
---
>        * @return int|false

**Comment by lapineige** [comment]
The formatting is broken but I managed to find those lines.
The quota is now working, a 5GB quota is clearly displayed as such.

Thanks a lot ! :tada:

**Comment by j-be** [comment]
Just for completeness, as already mentioned in #34674 I managed to get a quick and dirty 32 Bit CI running at https://github.com/j-be/nextcloud-ci and even though there are definitely false positives in there, there is also a very distinct hint to the Quota thingy reported above as:

```
7) Test\User\UserTest::testSetQuota
Expectation failed for method name is "setUserValue" when invoked 1 time(s)
Parameter 3 for invocation OCP\IConfig::setUserValue('foo', 'files', 'quota', '0 B', null) does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@

-'23 TB'
+'0 B'
```

There are 11 more issues I get on i386, but not on AMD64 (and there are 6 I get on both, so omitted) in [nextcloud_i386_ci.log](https://github.com/nextcloud/server/files/10244949/nextcloud_i386_ci.log). Just in case someone wants to have a look at it.

**Comment by come-nc** [comment]
@j-be Could you run that CI on https://github.com/nextcloud/server/pull/35734 and tell me if it fixes quota errors on 32bits?

**Comment by MichaIng** [comment]
PR up to fix 32-bit support for NC25 with quota enabled: #35832

**Comment by lapineige** [comment]
Replaced by https://github.com/nextcloud/server/pull/35734

**Comment by j-be** [comment]
@come-nc Sorry for the delay, christmas and stuff.

I ran the CI against `stable25` branch:
* **AMD64**: 6 failures, 5 of which with share links. Not sure what is wrong. Log attached as [stable25_amd64.log](https://github.com/nextcloud/server/files/10360288/stable25_amd64.log)
* **i386** 16 failures, including `Test\User\UserTest::testSetQuota` and all 6 of AMD64. Log  attached as [stable25_i386.log](https://github.com/nextcloud/server/files/10360289/stable25_i386.log)

But what I didn't notice previously: There are some "errors" in i386 which apparently do NOT cause test failures:

```
8) Test\MemoryInfoTest::testMemoryLimit with data set "2G" ('2G', 2147483648.0)
TypeError: Argument 2 passed to Test\MemoryInfoTest::testMemoryLimit() must be of the type int, float given, called in /usr/share/php/PHPUnit/Framework/TestCase.php on line 1526

/server/tests/lib/MemoryInfoTest.php:77

[ ... ]

24) OCA\Files_Trashbin\Tests\BackgroundJob\ExpireTrashTest::testConstructAndRun
PHPUnit\Framework\MockObject\IncompatibleReturnValueException: Method getTime may not return value of type double, its return declaration is "int"

/server/apps/files_trashbin/tests/BackgroundJob/ExpireTrashTest.php:64

25) OCA\Files_Trashbin\Tests\BackgroundJob\ExpireTrashTest::testBackgroundJobDeactivated
PHPUnit\Framework\MockObject\IncompatibleReturnValueException: Method getTime may not return value of type double, its return declaration is "int"

/server/apps/files_trashbin/tests/BackgroundJob/ExpireTrashTest.php:64

26) OCA\Files_Versions\Tests\BackgroundJob\ExpireVersionsTest::testBackgroundJobDeactivated
PHPUnit\Framework\MockObject\IncompatibleReturnValueException: Method getTime may not return value of type double, its return declaration is "int"

/server/apps/files_versions/tests/BackgroundJob/ExpireVersionsTest.php:73

27) OCA\Provisioning_API\Tests\Controller\UsersControllerTest::testAddUserSuccessfulGenerateUserID
rand() expects parameter 2 to be int, float given

/server/apps/provisioning_api/tests/Controller/UsersControllerTest.php:500
/server/apps/provisioning_api/lib/Controller/UsersController.php:309
/server/apps/provisioning_api/lib/Controller/UsersController.php:348
/server/apps/provisioning_api/tests/Controller/UsersControllerTest.php:505
```

If you want to run the CI yourself: Just clone https://github.com/j-be/nextcloud-ci/ and assuming you have Docker up and running anyway do `docker build --platform=i386 --build-arg NEXTCLOUD_VERSION=stable25 .`.

If you want to do anything else with it: feel free, it is MIT licensed on purpose.

I'll see if I can somehow upload the reports to gh-pages.

**Comment by j-be** [comment]
I managed to upload the reports to GitHub pages, see https://j-be.github.io/nextcloud-ci/

When accessing, please keep in mind, that gh-pages does heavy caching.

**Pull request merged**
