### PR TITLE
Allow to change avatar when groups are disables

### PR DESCRIPTION
**Pull request by MorrisJobke**
* password form overlaps upload button and doesn't allow to click it
* regression from #5259

How to test:

* disable groups
* go to personal settings and try to click the avatar upload button

### CODE REVIEW

**Comment by nickvergessen** [comment]
When you disable password change (hack `if($_['passwordChangeSupported'])` in the template), the problem continues with the language drop down blocking the name and email field:
> bildschirmfoto vom 2017-06-07 09-31-20

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Fix is incomplete when password change is disabled

**Comment by schiessle** [comment]
I pushed a update which should always work. Not sure if it is the most elegant version, though.

@MorrisJobke feel free to replace it if you know a better way to solve it.

**Comment by MorrisJobke** [comment]
Thanks @schiessle - I condensed the CSS rules and squashed everything.

**Comment by MorrisJobke** [comment]
:+1: from me, because it's mostly Björns code

**Review by LukasReschke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
CSS and HTML only -> merge

**Pull request merged**
