### PR TITLE
fix(files): open menu on right click position

### LINKED ISSUE #41721: [Bug]: Right click menu should open at cursor position
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In NC 28 the right click menu always opens at the "..." menu, not at the cursor location.

### Steps to reproduce

1. Go to the files app
2. Right click on a file / folder

### Expected behavior

Right click menu should open at cursor location

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

https://github.com/nextcloud/server/assets/1580193/c0bcf1cb-aa20-46bf-81e4-dfb0d99b6c6f

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #41721

image

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]
Tried on my dev browser, and LGTM! Really clean solution :)

**Comment by SystemKeeper** [comment]
Is it expected to always open the menu to the left, when the sidebar is open?

Also, depending on where you click, the menu is hidden behind the left sidebar:
image


https://github.com/nextcloud/server/assets/1580193/fe741de4-839f-4836-96e2-5df1f13abf54

Tested on MacOS with Chrome 120.

**Comment by susnux** [comment]
> the menu is hidden behind the left sidebar:

I think this happens because files is not using NcContent but some custom mounting of NcAppContent and NcAppSidebar instead?

**Comment by skjnldsv** [comment]
> Is it expected to always open the menu to the left, when the sidebar is open?

Yes and no. I'll see if I can improve this further today :)

**Comment by skjnldsv** [comment]
@SystemKeeper @susnux fixed!

**Comment by SystemKeeper** [comment]
Way better now, thank you :-) 

But now the y-position seems a bit off to me: 

image

I right clicked on Media, but it is shown a bit too low?


https://github.com/nextcloud/server/assets/1580193/c877e57b-e162-4cfb-82d1-289171da01d7

**Comment by skjnldsv** [comment]
Done @SystemKeeper

**Review by SystemKeeper — APPROVED** [review]

**Comment by skjnldsv** [comment]
/backport dd0fb2e76b109caa1107bc78cc2a1f03ddef5865 to stable28

**Pull request merged**
