### PR TITLE
Adjust PHPUnit version

### PR DESCRIPTION
**Pull request by miaulalala**
This kills the Drone

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Drone images run 8.5 :/

**Review by blizzz — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by max-nextcloud** [comment]
rebased and resolved the conflict. No idea if drone these days can provide phpunit >9.5... i guess we'll see from the CI run.

**Comment by max-nextcloud** [comment]
grafik
memcached test is the only one failing on this right now.

**Comment by come-nc** [comment]
> memcached test is the only one failing on this right now.

```
  image: ghcr.io/nextcloud/continuous-integration-php8.0-memcached:latest
```
The problem must be in this image then.

**Comment by szaimen** [comment]
Apparently the version is pinned to 9.5:https://github.com/nextcloud/docker-ci/blob/4483aa1bdc728e1cccc8f174b437e3406f26a667/php8.0/Dockerfile#L16

**Comment by nickvergessen** [comment]
Done via https://github.com/nextcloud/server/commit/3294bbe3bb73f6e5089fc0f3b95a28ffca7d1faa in the meantime

**Pull request closed without merging**
