### PR TITLE
fix overlapping of elements in certain views

### LINKED ISSUE #33855: gallery/list view icon/toggle sometimes overlaps in some views
See e.g.
image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/33855

inspired by https://github.com/nextcloud/server/pull/28015/files

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
