### PR TITLE
Drop bootstrap

### PR DESCRIPTION
**Pull request by nickvergessen**
* Resolves: # 

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]
Didn't see any breakage from a very light test

**Comment by juliushaertl** [comment]
Haven't tested yet, but as far as I remember it was only used for tooltips which might already have been migrated away to use browser-native ones.

**Review by ChristophWurst — APPROVED** [review]
🫡

**Review by Pytal — APPROVED** [review]

**Comment by DaphneMuller** [comment]
hello @nickvergessen 
Thank you so much for your work on this pull request! This ticket seems to have the tag 'pending documentation'. 
Is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

**Comment by nickvergessen** [comment]
Was added in https://github.com/nextcloud/server/issues/34692#issuecomment-1410018051

**Pull request merged**
