### PR TITLE
Apply patch for scssphp

### PR DESCRIPTION
**Pull request by kesselb**
Requires:
- [x] https://github.com/nextcloud/3rdparty/pull/441
- [x] Rebase

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@kesselb This is to fix the variable undefined log message for the SCSS compiler?

**Comment by kesselb** [comment]
> @kesselb This is to fix the variable undefined log message for the SCSS compiler?

I think so. At least on my instance they are gone.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Waiting for CI now :)

**Comment by MorrisJobke** [comment]
@kesselb Backport to stable18?

**Comment by kesselb** [comment]
@MorrisJobke up to you. I patched my instance and do not care about the integrity warning ;)

**Comment by MorrisJobke** [comment]
We should check if this fix the problems with PHP 7.4 it seems.

**Comment by timm2k** [comment]
Actually I can't find the backuport to stable18. Seems to stuck somewhere...

**Comment by blizzz** [comment]
in 18  it is under a different namespace (leafo/scssphp)

**Comment by Wotisrv** [comment]
Why do we have to do it manually? Perhaps a little bit more informasjon on  would be very helpful.

**Comment by blizzz** [comment]
> Why do we have to do it manually? Perhaps a little bit more informasjon on would be very helpful.

It does not fit to the version in 18 series, so it is not possible to do it automatically. From playing around a bit earlier, it seems that it might not catch all the cases that cause this debug messages.

**Pull request merged**
