### PR TITLE
adjust add button

### LINKED ISSUE #37207: Upload/add button style and discoverability
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The upload button in Files is not super present, and looks old compared to our other buttons.

**Describe the solution you'd like**
We should upgrade it to the `secondary` NcButton from the components. And a simple text "Add" next to the "+" in the upload button would be good.

**Additional context**
Current:
image

Proposed:
image

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/37207
| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Comment by susnux** [comment]
Can we make the button look like a `NcButton` with primary styling? So increase the gap between icon and text and remove the border. As with a NcButton it looks like this:

image

**Comment by szaimen** [comment]
How many pixel should the border be?

**Review by AndyScherzinger — APPROVED** [review]

**Comment by susnux** [comment]
> How many pixel should the gap be?

For vue buttons it seems there is no gap but the icon is 44px by 44px.
Maybe assign to `.button.new .icon`:
```css
width: 44px;
background-size: 20px 20px;
```

and to the button (`.button.new`:
```css
padding: 0 16px 0 4px;
```

This should emulate the vue button styling.
```

**Review by susnux — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Looks very nice! :)

**Pull request merged**
