### PR TITLE
Prevent your own status from replacing another user's status on profile

### PR DESCRIPTION
**Pull request by Pytal**
See title 👆

### CODE REVIEW

**Comment by artonge** [comment]
Would it make more sens to have that directly in the `handleStatusUpdate` method ?

```js
		handleStatusUpdate(status) {
			if (!this.isCurrentUser) {
				return
			}

			this.status = status
		},
```

**Review by artonge — COMMENTED** [review]
Would it make more sens to have that directly in the `handleStatusUpdate` method ?

```js
		handleStatusUpdate(status) {
			if (!this.isCurrentUser) {
				return
			}

			this.status = status
		},
```

**Comment by Pytal** [comment]
> Would it make more sens to have that directly in the `handleStatusUpdate` method ?

Had considered that as well, but I think preventing the subscription higher up in `mounted()` is better as otherwise we'd have an arbitrary event listener

**Review by juliusknorr — APPROVED** [review]

**Comment by artonge** [comment]
> Had considered that as well, but I think preventing the subscription higher up in `mounted()` is better as otherwise we'd have an arbitrary event listener

Can't help thinking that in one way or another, the state during `mounted` and during `beforeDestroy` could be different.

**Comment by Pytal** [comment]
> Can't help thinking that in one way or another, the state during `mounted` and during `beforeDestroy` could be different.

Good point, changed it to add checks to the `handleStatusUpdate` method instead :)

**Review by artonge — APPROVED** [review]

**Pull request merged**
