### PR TITLE
Fix language typo

### PR DESCRIPTION
**Pull request by nickvergessen**
See https://www.transifex.com/nextcloud/nextcloud/translate/#de/files_sharing/101548774

@LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by LukasReschke** [comment]
LGTM

**Review by LukasReschke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen Backport to stable10? (keep in mind: translations are also backported already ;))

**Comment by nickvergessen** [comment]
No, this is new

**Pull request merged**
