### PR TITLE
fix: show toggle grid view button with open sidebar

### LINKED ISSUE #33872: gallery/lisit view toggle/button vanishes behind sidebar
See 

https://user-images.githubusercontent.com/42591237/188127054-eabc4d9b-ac87-4cf4-9a80-a69d6e06e8b8.mp4

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: https://github.com/nextcloud/server/issues/33872

## Summary

| Before | After |
| --- | --- |
| Screenshot from 2023-01-05 19-45-01 |Screenshot from 2023-01-05 19-44-46 |

## TODO

- [x] :tada: 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
Seems to work, great! I wouldnt have thought that it is so easy to fix :D

**Comment by Jerome-Herbinet** [comment]
I still have the issue on Nextcloud 25.0.6 for example.

**Comment by szaimen** [comment]
Something else was fixed with this. See the linked issue.

**Pull request merged**
