### PR TITLE
Also cancel XHR when cancelling uploads

### LINKED ISSUE #32354: [Bug]: Unable to cancel upload that contains a lot of files
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When im uploading multiple files, or a folder that contains a lot of files, and I want to cancel that upload it tells me “Uploading canceled” but the upload bar is still visible and its still uploading.
Pressing cancel many times makes no difference in this.
The only thing that actually stops the upload is reloading the page wich results in an error in the log.
The unresponsive cancel shows nothing in the log whatsoever.

I also noticed that the size of the upload is “NaN” and shows "only a couple seconds remaining."

Also additional information performed by other user here: https://help.nextcloud.com/t/unable-to-cancel-large-upload/138639

### Steps to reproduce

1. Upload a forlder with many sub folders/files (for example the documents folder of windows)
2. Try to cancel the upload after a couple seconds
3. Message appears the upload has been canceled but upload is still going.

### Expected behavior

When you cancel the upload of many files and or folders, it should actually cancel the upload.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "default_phone_region": "NL",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - cloud_federation_api: 1.7.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - event_update_notification: 1.5.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_downloadactivity: 1.13.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - previewgenerator: 4.0.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.0.0
  - richdocumentscode: 21.11.402
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - survey_client: 1.12.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - unsplash: 1.2.5
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - circles: 24.0.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - encryption: 2.12.0
  - federation: 1.14.0
  - support: 1.7.0
  - systemtags: 1.14.0
  - user_ldap: 1.14.1
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Google drive link because logfile is too large for anything like pastebin
https://drive.google.com/file/d/1zpYPY6Bf5q86Oq6Ys4t9XQJnMTe4svxH/view?usp=sharing
```

### Additional info

https://help.nextcloud.com/t/unable-to-cancel-large-upload/138639

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/nextcloud/server/issues/32354

Fixes issue when cancelling a long list of uploads.

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Tested and works!

Finally a fix was found 🎉🎉🎉

**Comment by skjnldsv** [comment]
Touching legacy upload code ? :ghost: :grin:

**Review by skjnldsv — APPROVED** [review]
:elephant:

**Comment by PVince81** [comment]
> Touching legacy upload code ? ghost grin

I had no choice :gloves: 

and just now looking at the history I realized that the line `this.data.abort()` was already there 7 years ago and got lost somehow :scream_cat:

**Pull request merged**
