### PR TITLE
optimize builtin storage wrappers

### PR DESCRIPTION
**Pull request by icewind1991**
Mostly replacing `$storage->instanceOfStorage` with `$mount instance` which is significantly faster

### CODE REVIEW

**Review by come-nc — APPROVED** [review]
Not tested, but looks sane.

**Comment by icewind1991** [comment]
merged #41056 into this due to the code overlap

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
stable 26 has conflicts with the commits applied

**Comment by AndyScherzinger** [comment]
stable 27 has conflicts with the commits applied

**Pull request merged**
