### PR TITLE
Implement IAPIWidget, IButtonWidget and IIconWidget in user status

### PR DESCRIPTION
**Pull request by julien-nc**
This is based on #33658

requires:

- [x] https://github.com/nextcloud/server/pull/33658

No buttons for this widget. Use the app svg icon for `getIconUrl()`.

### CODE REVIEW

**Comment by eneiluj** [comment]
@tobiasKaminsky The text includes the status unicode character (the UTF-8 emoji). So when there is no emoji, title starts with a space. This is fixed now.

About the round icon, tough decision to make. Potential solutions, just elaborating what you said:
1. The dashboard api returns an extra attribute to let the client know if the image should be displayed rounded or not... I would go with that.
2. Provide it round: It means we have to add a parameter to the avatar server endpoint to optionally get a round image
3. Dark magic, meh...:grin:

I prefer 1. because it is generic and implemented one single time in each client rather than potentially making the effort of rounding the image in each server widget class.
What do you think?

**Comment by tobiasKaminsky** [comment]
Then let us go with 1.
Can I ask you to implement this on main server PR https://github.com/nextcloud/server/pull/33658
I think we can make this optional, so by default it is not rounded, and only if rounded the apps has to set it, else API will always send rounded: false.
This is possible nowadays with php, right?

**Comment by tobiasKaminsky** [comment]
This lacks IItemOptionWidget so that we have item_icons_round:true ?

**Comment by icewind1991** [comment]
rebased on dashboard-api-widgets and set `item_icons_round`

**Comment by tobiasKaminsky** [comment]
Tested & worked :+1: 
Many thanks @eneiluj @icewind1991

**Comment by eneiluj** [comment]
@icewind1991 Thanks for the adjutments!
The target branch of this PR is `dashboard-api-widgets` so we can merge now.

**Comment by eneiluj** [comment]
Rebased on `dashboard-api-widgets`.
@tobiasKaminsky One last test and we can merge :pray:

**Comment by eneiluj** [comment]
Or we can make the final review in the original PR #33658

**Pull request merged**
