### PR TITLE
Restore innocent code from IE purge

### PR DESCRIPTION
**Pull request by artonge**
Some code was wrongly removed during IE purge, this PR restores it.

PR where the code was removed: code https://github.com/nextcloud/server/pull/29966/files#diff-792c35877ef47f0038761f64e662a3e778e0a6ace6ca8a8dd048e510520cd826L315

Usage of`$showGridView` in the same file: https://github.com/nextcloud/server/blob/master/core/src/OC/dialogs.js#L1032

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
lgtm

**Review by CarlSchwan — APPROVED** [review]

**Comment by szaimen** [comment]
@artonge please rebase :)

**Comment by artonge** [comment]
CI failure is unrelated

**Review by skjnldsv — COMMENTED** [review]
My bad, nice catch @artonge !!

**Pull request merged**
