### PR TITLE
Cast to int

### LINKED ISSUE #32837: [Bug]: occ files:scan error Implicit conversion from float
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using occ files:scan the error message **Implicit conversion from float** will come up sometimes.

### Steps to reproduce

1. occ files:scan

### Expected behavior

Completion message.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.gamesucker.de"
        ],
        "enable_previews": true,
        "preview_max_x": 100,
        "preview_max_y": 100,
        "preview_max_scale_factor": 1,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.1.1",
        "overwrite.cli.url": "http:\/\/nc.gamesucker.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "app_install_overwrite": [
            "files_clipboard",
            "files_accesscontrol",
            "previewgenerator",
            "files_frommail",
            "keeporsweep"
        ],
        "mail_smtpmode": "sendmail",
        "mail_smtpauth": false,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "pipe",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "DE",
        "data-fingerprint": "a81bfb9632e22f1a3c13b862c6d38f1f"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - apporder: 0.15.0
  - audioplayer: 3.3.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.0
  - duplicatefinder: 0.0.14
  - external: 4.0.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_external: 1.16.1
  - files_frommail: 0.4.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - keeporsweep: 0.2.1
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.3
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - phonetrack: 0.7.0
  - photos: 1.6.0
  - polls: 3.6.1
  - previewgenerator: 5.0.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - registration: 1.5.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - socialsharing_email: 2.5.0
  - socialsharing_facebook: 2.5.0
  - socialsharing_twitter: 2.5.0
  - spreed: 14.0.2
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_external: 3.0.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - drawio: 1.0.1
  - encryption: 2.4.0
  - files_trackdownloads: 1.9.0
  - flowupload: 1.1.2
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by markuszeller**
Fix https://github.com/nextcloud/server/issues/32837

### CODE REVIEW

**Comment by markuszeller** [comment]
Issue #32837

**Comment by kesselb** [comment]
Thanks @markuszeller ,

looks like https://github.com/nextcloud/server/pull/32059 / https://github.com/nextcloud/server/pull/32841?

**Review by CarlSchwan — APPROVED** [review]

**Comment by kesselb** [comment]
> > Thanks @markuszeller ,
> > looks like #32059 / #32841?
> 
> Line 292 needs to be casted as well.

See https://github.com/nextcloud/server/security/code-scanning/14138

**Comment by markuszeller** [comment]
> See https://github.com/nextcloud/server/security/code-scanning/14138

Getting a 404.

**Comment by kesselb** [comment]
> > See [RedundantCast](/nextcloud/server/security/code-scanning/14138)
> 
> Getting a 404.

Added a screenshot.

**Comment by kesselb** [comment]
Thanks :+1: 

Would you mind to sign off your commits? https://github.com/nextcloud/server/pull/32838/checks?check_run_id=6857948898

**Review by markuszeller — COMMENTED** [review]
Need to cast $secs.

**Comment by kesselb** [comment]
Hi @markuszeller,

Could you please rebase your branch to pull in the latest changes?

Thanks and sorry it took so long from our side.

**Comment by tcitworld** [comment]
The rebase seems to have gone wrong :(

**Comment by markuszeller** [comment]
> The rebase seems to have gone wrong :(

It asked me to merge master into my branch. Should I redo and force a rebase?

**Comment by miaulalala** [comment]
Hi @markuszeller can you please checkout your master branch, then do a `git pull`, then switch back to this branch and do the rebase again? Then you should have a clean commit history.

**Comment by kesselb** [comment]
Hi, please run to fix the dco check:

`git rebase HEAD~1 --signoff`
`git push --force-with-lease origin bugfix/32837/implicitFloatConversion`

**Review by kesselb — APPROVED** [review]

**Comment by markuszeller** [comment]
> Hi, please run to fix the dco check:
> 
> `git rebase HEAD~1 --signoff` `git push --force-with-lease origin bugfix/32837/implicitFloatConversion`

Thank you for your assistance. Hopefully that's working now.

Can you help me understanding why to do `HEAD~1 --signoff`, because I think the commit was already signed? At least my PHPStorm is configured to do so.

**Review by szaimen — APPROVED** [review]
Fine by me

**Comment by kesselb** [comment]
> Can you help me understanding why to do HEAD~1 --signoff, because I think the commit was already signed? At least my PHPStorm is configured to do so.

I guess the sign-off was lost due to the rebase.

**Pull request merged**
