### PR TITLE
add text/org mimetype

### PR DESCRIPTION
**Pull request by zzkt**
The text app (or any future editor) should be able to edit .org files when `text/org` and `text/plain` MIME types are set and the webserver is correctly configured (based on comments from nextcloud/text#1205 )

### CODE REVIEW

**Review by juliusknorr — CHANGES_REQUESTED** [review]
We also need to add this to the repair step as in https://github.com/nextcloud/server/commit/9708b004f75b543ed95f29e3a2993b5ee532a61c, otherwise existing files will not get the new mimetype.

**Comment by zzkt** [comment]
sure. what would be a reasonable version number for the test `(version_compare($ocVersionFromBeforeUpdate, '20.0.0.5', '<')`

**Comment by juliushaertl** [comment]
The current one on master would be 21.0.0.7 https://github.com/nextcloud/server/blob/master/version.php#L32. So taking that makes sure that once 21 is released every instance upgraded from below will run the mimetype repair.

**Comment by zzkt** [comment]
i've added another commit. let me know if anything else is needed...

**Review by kesselb — APPROVED** [review]

**Comment by juliushaertl** [comment]
Looks good to me now :+1: 

There is only one thing missing - you need to add a sign-off message to the commits you made. Read more about this in https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work

**Comment by zzkt** [comment]
i've amended the commits (or branch?) and it looks ok with `git log --show-signature` but it's a bit messy...

**Comment by kesselb** [comment]
```
git rebase HEAD~6 --signoff
git push --force-with-lease origin patch-1
```

https://github.com/nextcloud/server/pull/24488/checks?check_run_id=1536789034 for more details.

**Comment by zzkt** [comment]
thanks for the pointer @kesselb

**Comment by kesselb** [comment]
Mind to do another rebase? 3 out 5 commit seems unrelated.

**Comment by kesselb** [comment]
@juliushaertl :ping_pong:

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
