### PR TITLE
fix size of template picker

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

| Before | After |
|---|---|
| image | image |
| image | image |

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=enh/noid/template-picker-size \
-e TEXT_BRANCH=master \
-e VIEWER_BRANCH=master \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Comment by skjnldsv** [comment]
Screenshots?

**Comment by szaimen** [comment]
> Screenshots?

Is this really needed here?

**Comment by skjnldsv** [comment]
> > Screenshots?
> 
> Is this really needed here?

Helps approving without setting this up.
Especially because you removed `height: fit-content;`. needs to be tested with 1, 5 or 15 templates files so we know how it looks :stuck_out_tongue: 

Helps get PR in faster :wink: 
I think any design change should have screenshots, it helps :shrug:

**Comment by szaimen** [comment]
> > > Screenshots?
> > 
> > 
> > Is this really needed here?
> 
> Helps approving without setting this up. Especially because you removed `height: fit-content;`. needs to be tested with 1, 5 or 15 templates files so we know how it looks 😛
> 
> Helps get PR in faster 😉 I think any design change should have screenshots, it helps 🤷

Fine by me. Will add screenshots later :)

**Comment by szaimen** [comment]
> Helps approving without setting this up.

Btw: not sure if you've seen this but there is a one-liner available that sets this up easily ;)

```
docker run -it \
-e SERVER_BRANCH=enh/noid/template-picker-size \
-e TEXT_BRANCH=master \
-e VIEWER_BRANCH=master \
-p 127.0.0.1:8443:443 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

**Comment by szaimen** [comment]
> Fine by me. Will add screenshots later :)

done

**Comment by artonge** [comment]
What's the motivation behind this change?

**Comment by szaimen** [comment]
> What's the motivation behind this change?

It was wrongly changed during the upgrade to vue 5.0 from my side...

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
