### PR TITLE
perf(dashboard): Stop loading the viewer on the dashboard

### PR DESCRIPTION
**Pull request by susnux**
## Summary

Viewer is ~4MB of JS assets for loading, this is not needed on the dashboard and the sidebar is also not used on the dashboard - there is no sidebar at all.

before | after
---|---
Screenshot_20240206_220934|Screenshot_20240206_221022
Screenshot_20240206_221121|Screenshot_20240206_221059

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ShGKme — APPROVED** [review]
BTW, should it be considered a breaking change?

For example, if some community app uses dashboard api v1 and Viewer

**Comment by nickvergessen** [comment]
> BTW, should it be considered a breaking change?
> For example, if some community app uses dashboard api v1 and Viewer

I would say mentioning it in the developer docs doesn't hurt. The fix is also easy (emit the event yourself)

**Review by nickvergessen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
> I would say mentioning it in the developer docs doesn't hurt. The fix is also easy (emit the event yourself)

Which is also not really a fix, they should have done that since the beginning.
never rely on others triggering events for you :)

**Comment by susnux** [comment]
Documentation: https://github.com/nextcloud/documentation/pull/11513

**Pull request merged**
