### PR TITLE
Add occ versions:cleanup --path option

### LINKED ISSUE #7687: Possibility to cleanup versions per path
I'd like to cleanup the old versions for a specific path. It's now possible to do it for a specific user:
`sudo -u www-data php occ versions:cleanup john`

But I'd like to specify also a path. Like the file:scan function:
`sudo -u www-data php occ files:scan --path="/john/files/Pictures" john`

Then we would have something like:
`sudo -u www-data php occ versions:cleanup --path="john/files_versions/Pictures" john`

My use-case: a program modified all the pictures of a specific folder. I downloaded all the files directly from the server in order to recover the former version. But now I'd like to cleanup the old versions, specifically for this folder.

Manual is here: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/occ_command.html#versions-label

### PR DESCRIPTION
**Pull request by PhrozenByte**
Add `-p, --path=PATH` option to `occ versions:cleanup` to delete file versions within a particular path only.

Inspired by `occ files:scan --path`.

Just 16 days after #7687 has been closed - I didn't know exist until I was finished. What a coincidence :smile:

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Fine by me

**Comment by PhrozenByte** [comment]
Sorry for the heads up, we need a second review for this actually pretty small addition here :wink: :rocket: :+1: I know, too many review requests and thus nobody feels responsible :smile: Thanks Christoph btw! :+1: 

@schiessle @nickvergessen @eneiluj @skjnldsv @ArtificialOwl @CarlSchwan @juliushaertl @PVince81

**Review by PVince81 — CHANGES_REQUESTED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
