### PR TITLE
[stable27] Consider share type for enforced share expiry dates 

### PR DESCRIPTION
**Pull request by nfebe**
Manual backport #40500

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by blizzz** [comment]
@Fenn-CS I am a irritated. Do we need another compile, or is it actually good? It looks to me like that, with CI being green.

**Comment by Fenn-CS** [comment]
@blizzz I don't think we need another compile :)

**Comment by blizzz** [comment]
failing test is unrelated → merging

**Pull request merged**
