### PR TITLE
[downstream] Fix colon issue

### PR DESCRIPTION
**Pull request by LukasReschke**
From https://github.com/owncloud/core/pull/26773
Requires https://github.com/nextcloud/3rdparty/pull/23

### CODE REVIEW

**Comment by rullzer** [comment]
3rdparty merged.
Rebased.

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@karlitschek Backport requested in #3699

**Comment by MorrisJobke** [comment]
@benediktg If the backport gets approved: feel free to do the cherry pick and open the PR against stable11 ;)

**Comment by karlitschek** [comment]
makes sense. please backport

**Pull request merged**
