### PR TITLE
Use Image class from public API

### PR DESCRIPTION
**Pull request by Pytal**
Use the public Image class in place of the private OC_Image class https://github.com/nextcloud/server/blob/4e5ed32025398e006f40e819428270d209994e03/lib/public/Image.php#L34

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:broom:

**Comment by ChristophWurst** [comment]
I don't think we should backport this. Rule of thumb is to only port bugfixes.

**Review by juliusknorr — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Pull request merged**
