### PR TITLE
27.1.0 RC4

### PR DESCRIPTION
**Pull request by blizzz**
* #40390
* #40402
* #40405
* #40412
* #40414
* #40415
* #40417
* nextcloud/text#4794

### CODE REVIEW

**Comment by Fenn-CS** [comment]
Since we are here 

- https://github.com/nextcloud/server/pull/40393
- https://github.com/nextcloud/server/pull/40389
(the backports)

Would be nice go inside this release too.

**Comment by blizzz** [comment]
### Required PRs

* [ ] https://github.com/nextcloud/updater/pull/490

**Comment by AndyScherzinger** [comment]
Especially the guest fix is important since this breaks functionality working on pre-27.1.
All the others would still also be requested especially but not limited by designers.

**Comment by juliushaertl** [comment]
Also required https://github.com/nextcloud/text/pull/4794

**Comment by blizzz** [comment]
> all added up top

@Fenn-CS the description will be overwritten by a script. If the 27.1.0 milestone is applied there, they will show up (relevant repos only), but if something is required keep a list in a comment, so it can be tracked and won't be skipped.

**Pull request merged**
