### PR TITLE
Use Webdav PUT for uploads

### PR DESCRIPTION
**Pull request by rullzer**
See https://github.com/owncloud/core/pull/21237

Please test carefully:
- [x] Test upload via button
- [x] Test upload drag/drop
- [x] Test upload link share
- [x] Test files_drop

CC: @nickvergessen @MorrisJobke @LukasReschke @blizzz @icewind1991 @schiessle

### CODE REVIEW

**Comment by nickvergessen** [comment]
- [ ] Test activities which broke last time we tried this

**Comment by icewind1991** [comment]
Ok, the name of the PR is misleading since it's implementing webdav POST, not using webdav PUT

From what I understand from reading the spec this is not actually implementing RFC5995 as it says it is, but instead doing something that somewhat looks like the spec on the surface. according to the RFC every collection has a (possibly) separate endpoint where it allows POST requests to create new files in the collection, this endpoint url is static for the collection and does not contain any filename suggestion for the created file, if the client wants to suggest a filename it can use the `Slug` header.

As it's currently implemented it uses a "magic path" `/path/to/folder/&suggested_file_name` instead of having a per-collection endpoint for adding files to a collection

Imo it would be better if we properly follow the rfc

**Comment by rullzer** [comment]
@icewind1991 so close this and you fix it according to the RFC ;)?

**Comment by LukasReschke** [comment]
@icewind1991 I'd either like to have this fixed or merged. 🙈

**Comment by LukasReschke** [comment]
Blocks https://github.com/nextcloud/server/pull/1511

**Comment by blizzz** [comment]
Needs rebase

**Comment by MorrisJobke** [comment]
@icewind1991 @rullzer How to proceed here? stalled PRs doesn't help neither.

**Comment by LukasReschke** [comment]
Rebase and just merge and enhance latter? Keeps the diff smaller 🙈

**Comment by LukasReschke** [comment]
Will rebase.

**Comment by icewind1991** [comment]
I'm fine with this as long as it has some documentation about how the magic path works (and doesn't suggest it's RFC5995)

**Comment by MorrisJobke** [comment]
I rebased this and want to get this in, because it blocks soo many other downstream PRs.

**Comment by MorrisJobke** [comment]
- [ ] fix anonymous upload feature (`files/ajax/upload.php` doesn't exist anymore)

**Comment by rullzer** [comment]
Files_drop is kind of working again.

@icewind1991 do you agree with https://github.com/nextcloud/server/pull/1283/commits/35f9d3cc8adf19b83e510ef529edc825d9bb5be9 Else it is not possible to upload via webdav with only create permissions since rename is not allowed.

**Comment by nickvergessen** [comment]
Some tests are failing

**Comment by rullzer** [comment]
Ok files_drop works here.
Lets get this in and fiddle with the details later.

CC: @MorrisJobke @icewind1991 @nickvergessen @LukasReschke @blizzz

**Comment by MorrisJobke** [comment]
Works 👍 

Tested in IE, Safari and Chrome

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen we should get this in as fast as possible - other downstreams are depending on this

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
