### PR TITLE
Add ldap:reset-group command to unmap groups from LDAP

### PR DESCRIPTION
**Pull request by come-nc**
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by come-nc** [comment]
@blizzz Do you know why the return of deleteGroup is ignored in https://github.com/nextcloud/server/blob/master/lib/private/Group/Group.php#L357-L358 ? A boolean is returned but it’s ignored.

**Comment by blizzz** [comment]
> @blizzz Do you know why the return of deleteGroup is ignored in https://github.com/nextcloud/server/blob/master/lib/private/Group/Group.php#L357-L358 ? A boolean is returned but it’s ignored.

I am not aware of a reason of doing so, and I concur that instead of setting result blindly to true, I would OR it with the result of deleteGroup.

**Review by blizzz — APPROVED** [review]

**Comment by come-nc** [comment]
> > @blizzz Do you know why the return of deleteGroup is ignored in https://github.com/nextcloud/server/blob/master/lib/private/Group/Group.php#L357-L358 ? A boolean is returned but it’s ignored.
> 
> I am not aware of a reason of doing so, and I concur that instead of setting result blindly to true, I would OR it with the result of deleteGroup.

I will open an other PR for this.

**Review by CarlSchwan — APPROVED** [review]

**Pull request merged**
