### PR TITLE
[stable13] Use a phan version instead of master

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #8172

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by danxuliu — CHANGES_REQUESTED** [review]
Phan 0.11.1 requires PHP 7.2, but its image version was not bumped (~~second commit from original pull request was not included in this one~~ **edit:** well, second commit would not be valid on its own either; it would require the bump from the third one anyway to use the latest PHP 7.2 image).

**Comment by MorrisJobke** [comment]
also 7.2-11 contains already a newer PHPUnit - so I used the old php 7.2-9 image ;) Let's see

**Comment by danxuliu** [comment]
Phan needs Redis and Imagick, which were included in 7.2-11. Is the newer PHPUnit incompatible with Phan tests in _stable13_? In that case I guess that we will have to use Phan 0.10.x for _stable13_, as [Phan 0.10.x is compatible with PHP 7.1](https://github.com/phan/phan/releases/tag/0.10.3).

**Comment by rullzer** [comment]
Aaah right... yeah just use the one compatible with 7.1 for 13 then i think.

**Comment by MorrisJobke** [comment]
> Phan needs Redis and Imagick, which were included in 7.2-11. Is the newer PHPUnit incompatible with Phan tests in stable13? In that case I guess that we will have to use Phan 0.10.x for stable13, as Phan 0.10.x is compatible with PHP 7.1.

I just wanted to keep the versions the same. Let me try with 7.2-11 and if this does not work we will use 0.10.x of phan.

**Review by danxuliu — APPROVED** [review]

**Comment by danxuliu** [comment]
Drone is happy with 7.2-11 :-D

**Pull request merged**
