### PR TITLE
Update acceptance tests dependencies

### PR DESCRIPTION
**Pull request by danxuliu**
This should be rebased on master once #25975 is merged (it is set as draft to prevent that, but it is ready for review nevertheless).

This pull request updates the acceptance tests dependencies, which requires some syntax changes (mostly `PHPUnit_Framework_Assert` to `Assert`). Due to that, and to ease future backports I would suggest to backport it (so please do not merge before the backports of #25975 are also merged to ensure that backportbot can do its magic :-) ). In any case if the backport fails feel free to ignore it ;-)

### CODE REVIEW

**Comment by danxuliu** [comment]
I have rebased to fix (and document in the commit message, so that is why I did not use a fixup commit) a couple of acceptance test failures that only happened with the Docker container used in CI.

**Comment by danxuliu** [comment]
I have run the failing test several times locally and it always passed, so it *should* be just a hiccup in CI.

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/pull/25975 merged

**Comment by skjnldsv** [comment]
acceptance-access-levels fails

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Good to go, the acceptance acceptance-app-files-sharing  failure is on master as well

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Pull request merged**
