### PR TITLE
Add X-Frame-Options header to .htaccess

### PR DESCRIPTION
**Pull request by J0WI**
This addresses the some major points of #8207.

This should not change the behavior of a normal request to NextCloud. But it changes the following:

<table>
<tr>
<th>Before</th><th>After</th>
</tr>
<tr>
<td><code>X-Frame-Options</code> is only sent by PHP responses</td><td><code>X-Frame-Options</code> is sent on all responses</td>
</tr>
<tr>
<td>security headers are only sent on 2xx responses</td><td>security headers (except dynamically generated CSP) are sent on all responses</td>
</tr>
<tr>
<td>If the <code>X-Frame-Options</code> header is added to the <a href="https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst#nextcloud-in-the-webroot-of-nginx">nginx example</a>, it's sent twice for PHP responses</td><td>The <code>X-Frame-Options</code> header should be added to the <a href="https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst#nextcloud-in-the-webroot-of-nginx">nginx example</a></td>
</tr>
</table>

This should not affect installations without `modHeadersAvailable`.

### CODE REVIEW

**Comment by kesselb** [comment]
There is a setupcheck that tests `x-frame-options` so nginx users should see a warning after upgrade. We should add some hint release notes about that.

**Comment by J0WI** [comment]
https://github.com/nextcloud/server/issues/4605#issuecomment-298321537
I'd suggest they shouldn't use iframes or use a dedicated endpoint with a suitable .htaccess/nginx config 
But I can't see a benefit if some apps are allowed to change the policy for the whole NextCloud.

**Comment by kesselb** [comment]
> [#4605 (comment)](https://github.com/nextcloud/server/issues/4605#issuecomment-298321537)
> I'd suggest they shouldn't use iframes or use a dedicated endpoint with a suitable .htaccess/nginx config
> But I can't see a benefit if some apps are allowed to change the policy for the whole NextCloud.

I see the point of the comment but how should an app overwrite the x-frame-options with the current code?

cc @georgehrke because some calendar sharing/embedding.

**Comment by J0WI** [comment]
I think meanwhile this is done by the `frame-ancestors` CSP, but I didn't found a source for this.

**Comment by J0WI** [comment]
Docs are already merged.

**Review by rullzer — APPROVED** [review]
Fine by me. Altough my apache fu is rather limited.

**Review by juliusknorr — APPROVED** [review]
Makes sense, also seems to work fine to still set different headers on the Nextcloud side. :+1:

**Review by juliusknorr — APPROVED** [review]
Makes sense, also seems to work fine to still set different headers on the Nextcloud side. :+1:

**Comment by MichaIng** [comment]
@J0WI 
Might I asked for the reason to have these headers sent as well with non 2xx responses? If the request fails due to permissions, missing file or is redirected, then those headers have no practical effect, do they? For an attacker they at best provide some additional information about the webserver config and the webserver has a tiny bid more to do for 30x/40x answers.

**Comment by J0WI** [comment]
> Might I asked for the reason to have these headers sent as well with non 2xx responses?

Why would you disable X-Frame-Options, XSS protection or any other security header on non 2xx responses?

> For an attacker they at best provide some additional information about the webserver config

Security through obscurity is no good practice. Admins should just keep their services secure.

> and the webserver has a tiny bid more to do for 30x/40x answers.

I don't think that this change has a measurable effect on performance.

**Comment by MichaIng** [comment]
@J0WI 
> Why would you disable X-Frame-Options, XSS protection or any other security header on non 2xx responses?

As said, because it does not have any practical effect that I am aware of, security-wise. No content is sent by the webserver with 30x/40x answers, so nothing can be done by the client where any of the headers could kick in.

> Security through obscurity is no good practice. Admins should just keep their services secure.

Of course, but sending out information for no reason is as well no good practice.

> I don't think that this change has a measurable effect on performance.

I think so, however I did not say that there are measurable or strong reasons to remove "always", I was just wondering what was your reason to **explicitly do** add it. As of above, I just see disadvantages, probably not measurable ones or deal-breakers, but I think you added it for a certain reason, any practical advantage that comes with it, and this is what I was asking for 😉.

**Pull request merged**
