### PR TITLE
Add an OCS endpoint for the hovercard contact actions

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref #28751
Ref nextcloud/files-clients#1

Alternate attempt to https://github.com/nextcloud/server/pull/29249

* Less intrusive
* Only populating data that is needed now (since OCS has to stay compatible 3 years)
* Instead of shareTypes and POST, the userId is a url parameter and therefor much more straight forward
* In case hovercards get extended in the future, we can add more details to it and just bump the version parameter in the URL

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
```
curl --request GET \
  --url 'http://localhost/nc/ocs/v2.php/hovercard/v1/admin?format=json' \
  --header 'Authorization: Basic dG9iaTpTSGZ6ZC04YkQyNC1xOUtSaS1zU2NRay03ZHh4eA==' \
  --header 'OCS-APIRequest: true'
```

I receive a 404:
```
{
  "ocs": {
    "meta": {
      "status": "failure",
      "statuscode": 404,
      "message": null
    },
    "data": []
  }
}
```

I think I understood that @skjnldsv said that addressbook is populated too late…?

**Comment by tobiasKaminsky** [comment]
> > I think I understood that @skjnldsv said that addressbook is populated too late…?
> 
> `occ dav:sync-system-addressbook`

Tried it, still the same 🤔

**Comment by tobiasKaminsky** [comment]
> No errors in log?

No. I do not have a debugger available, but it seems that it just throws 404 as expected, like when you search for a non-existing userId.
We can have a short debug session, if you think it is needed, just ping me in Talk :)

**Comment by skjnldsv** [comment]
> No. I do not have a debugger available, but it seems that it just throws 404 as expected, like when you search for a non-existing userId. We can have a short debug session, if you think it is needed, just ping me in Talk :)

I can actually reprouce, but this only fails on the admin user! :thinking:

**Comment by nickvergessen** [comment]
Same issue happens btw with the current avatar menu.

* As user 1 go to personal settings
* Set all privacies to "Local"
* `occ dav:sync-system-addressbook`
* As user 2 open the avatar menu of user 1
* 💥

**Pull request merged**
