### PR TITLE
Consider link shares in removeShare method in SharingTab

### LINKED ISSUE #40396: share link not removed from share overview when using delete button
See 

https://github.com/nextcloud/server/assets/42591237/5b5404ec-d2bb-415d-b2e5-fa202848e825

### PR DESCRIPTION
**Pull request by nfebe**
Currently, the `removeShare` method in the `SharingTab` view, does not take into account `linkShares`.

Since link shares now shares the same detail view with other share types, it should therefore be considered hence this commit.

Resolves : https://github.com/nextcloud/server/issues/40396

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by szaimen — COMMENTED** [review]
Tested and works

**Review by szaimen — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Are these on purpose?

2023-09-15 18_14_16-Consider link shares in removeShare method in SharingTab by Fenn-CS · Pull Reque

Just asking because I am no frontend dev, so sorry for simple questions... :S

**Comment by Fenn-CS** [comment]
> Are these on purpose?

I did a run build for benefit of doubt and seems like it.

**Pull request merged**
