### PR TITLE
hide storage wrapper warning for the readonly storage

### PR DESCRIPTION
**Pull request by MorrisJobke**
One part of #1652 

cc @icewind1991 @nickvergessen

### CODE REVIEW

**Comment by LukasReschke** [comment]
Signed-off 🙈 

But LGTM otherwise

**Comment by MorrisJobke** [comment]
> Signed-off 🙈

Done

**Comment by rullzer** [comment]
it gets the job done but... :see_no_evil: :speak_no_evil: 

LGTM

**Comment by MorrisJobke** [comment]
@icewind1991 @karakayasemi  should we backport this? Currently there are thousands of those log lines here in our log 🙈

**Comment by enoch85** [comment]
Please backport! :)

**Comment by nickvergessen** [comment]
Let's also add `sharePermissions`. Seems to also be intended

**Comment by MorrisJobke** [comment]
backported via #2186

**Pull request merged**
