### PR TITLE
feat(app-framework): Add native argument types for middleware

### PR DESCRIPTION
**Pull request by ChristophWurst**
Resolves: n/a

## Summary

PHP allows us to add types to a base class that is extended elsewhere without breaking an interface: https://3v4l.org/JDX4H. So let's make use of this.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
But Psalm might cry?

**Comment by ChristophWurst** [comment]
> But Psalm might cry?

Always has

**Comment by ChristophWurst** [comment]
> But Psalm might cry?

Only INFO, no ERROR: https://psalm.dev/r/ccd19c3340

**Review by nickvergessen — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by ChristophWurst** [comment]
tests fail because we pass `null` as method name

**Comment by szaimen** [comment]
What is missing here?

**Comment by nickvergessen** [comment]
So?

- [ ] Fix up
- [ ] Mark as ready to review
- [ ] Merge

**Pull request merged**
