### PR TITLE
Some phpstorm inspection fixes

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Comment by enoch85** [comment]
Backport please?

**Comment by rullzer** [comment]
Why what does this fix?

**Comment by enoch85** [comment]
This is on stable12: https://github.com/nextcloud/server/issues/5838 doesn't it need to be backported to solve issues on 12 or am I too tired here?

**Comment by MorrisJobke** [comment]
> This is on stable12: #5838 doesn't it need to be backported to solve issues on 12 or am I too tired here?

You are too tired and I'm too tired. I referenced the wrong issue: fixed in #5821

**Pull request merged**
