### PR TITLE
Fix mobile menu over app-content

### LINKED ISSUE #15874: WebUI: Left pane of Users page is not shown in Safari of iPad portrait mode or any mode in iPhone
** 1st edited for URLs
** 2nd edited for images and additional information

### Steps to reproduce
1. open the nextcloud server domain in Safari on an iPad in portrait mode or an iPhone in whatever mode
2. login into the nextcloud server
3. click the user avatar from the upper right corner
4. select "Users" from the menu

### Expected behaviour
1. a  way to show the left pane, which contents a "Create User" button, such as a hamburger or a button. Or
2. show the left pane directly.

### Actual behaviour
1. no way to show the left pane on portrait mode of an iPad nor any mode on an iPhone.

As suggested by @tflidd  on [the other forum](https://help.nextcloud.com/t/webui-left-pane-of-users-page-is-not-shown-in-safari-of-ipad-portrait-mode-or-any-mode-in-iphone/54086), I have tried to use the [demo site](https://demo.nextcloud.com/) and it reproduced a similar result that the left pane is missing from the UI.

I have started to notice this behavior since Nexcloud v.16.0 but I could have missed it on v.15 as I did not add user which I didn't open the user page.

### Server configuration

**Operating system**: FreeNAS-11.2-U4.1

**Web server:** nginx 1.14.0_13,2

**Database:** mysql 5.6.42

**PHP version:** 7.1.23

**Nextcloud version:** (see Nextcloud admin page) 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from ownCloud 10.0.2

**Where did you install Nextcloud from:** FreeNAS 11.2 plugins Nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .well-known/acme-challenge/d01moX7P_WiIw0Wg0uhr3tW_xHqwIxe6t-eZ8NcEQ58
		- .well-known/acme-challenge/t_Kxhz_O03Lv6BbsxHFw2Mr2sZfzicuC9akX5wYADvo
		- .well-known/acme-challenge/oBdEJiczFDGQW6s1G7jLUqiPw8tSgWeJEq6Yv_-NpmQ
		- .well-known/acme-challenge/T33_ZYFA4KvY0oAtF3ORtC9Xd2atIcLKsAUP_wChvdc

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.well-known/acme-challenge/d01moX7P_WiIw0Wg0uhr3tW_xHqwIxe6t-eZ8NcEQ58] => Array
                        (
                            [expected] => 
                            [current] => 6bff1439ed78baf983246c90a5911a031ee547a5b5fe3fc5e81a4bb920e74f978c31c1d04c33449e72d774075ddece82718c5ea44f7eab24aa3e90e29dd0bd0c
                        )

                    [.well-known/acme-challenge/t_Kxhz_O03Lv6BbsxHFw2Mr2sZfzicuC9akX5wYADvo] => Array
                        (
                            [expected] => 
                            [current] => a17e41a7322fa40f90aaf9b07024be777030650954f0af35dcf926868622bff23f86765098dc7eb4188bbc648911d52f2fc066f58ddb1176ac4bf8143fb110ab
                        )

                    [.well-known/acme-challenge/oBdEJiczFDGQW6s1G7jLUqiPw8tSgWeJEq6Yv_-NpmQ] => Array
                        (
                            [expected] => 
                            [current] => 0da5e023c66c45a3b078ce1050c95395139e6a59d38036722449959f581ea0b545afb82f32f2a5e3258a268456eb550698d96367e5771fde237792b6d07e78ea
                        )

                    [.well-known/acme-challenge/T33_ZYFA4KvY0oAtF3ORtC9Xd2atIcLKsAUP_wChvdc] => Array
                        (
                            [expected] => 
                            [current] => c86d87ab08234bb358497723f228dd8030e59911a4cc6e5a3f279da45f0c10b9e42ebf74ab1d2c070bb9b916b2855fc0721ca535b8c0b65af77045d198f26d31
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)


The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "htaccess.RewriteBase": "\/",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "janusng.asuscomm.com",
            "nextcloud.ngs",
            "10.27.0.23"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/janusng.asuscomm.com",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Asia\/Hong_Kong",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** yes, smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari 

**Operating system:** iOS 12.3.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here

Error	index	TypeError: Argument 1 passed to OC\Security\Crypto::decrypt() must be of the type string, null given, called in /usr/local/www/nextcloud/core/Controller/LostController.php on line 189		2019-05-28T22:57:46+0800
Error	index	TypeError: Argument 1 passed to OC\Security\Crypto::decrypt() must be of the type string, null given, called in /usr/local/www/nextcloud/core/Controller/LostController.php on line 189		2019-05-28T22:57:35+0800
Warning	core	Login failed: 'christine' (Remote IP: '221.127.15.165')		2019-05-28T22:57:12+0800
Warning	core	Login failed: 'christine' (Remote IP: '221.127.15.165')		2019-05-28T22:56:27+0800
Warning	core	Login failed: 'christine' (Remote IP: '221.127.15.165')		2019-05-28T22:30:55+0800
Warning	core	Login failed: 'christine' (Remote IP: '221.127.15.165')		2019-05-28T22:30:55+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-28T22:15:22+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-28T20:58:31+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-26T14:35:27+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-26T12:24:11+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-25T17:23:58+0800
Error	no app in context	Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Theming.getImage" as such route does not exist.		2019-05-25T17:23:22+0800
Error	jsresourceloader	Could not find resource js/config.js to load		2019-05-25T17:23:22+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-25T17:02:20+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-25T16:54:33+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-25T16:52:06+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-25T16:48:29+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-24T14:29:17+0800
Error	PHP	stat(): stat failed for /mnt/data/appdata_ocjvk6h9as5n/preview/65608/3072-4096-max.jpg at /usr/local/www/nextcloud/lib/private/Files/Storage/Local.php#142		2019-05-24T11:40:53+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-23T15:01:43+0800
Error	PHP	unlink(/mnt/data/appdata_ocjvk6h9as5n/css/activity/062a-b512-style.css): No such file or directory at /usr/local/www/nextcloud/lib/private/Files/Storage/Local.php#227		2019-05-23T14:38:55+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-23T01:32:58+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-21T23:51:05+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-21T19:07:47+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-21T19:07:47+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-21T09:03:11+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-20T23:15:12+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-20T20:03:33+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-20T13:38:22+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-19T01:00:31+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T15:40:03+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T15:40:03+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T15:27:45+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T14:34:12+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T14:32:45+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T14:31:33+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T14:16:57+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T14:03:17+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T14:03:04+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T13:12:16+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T13:12:16+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T13:10:05+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T13:10:05+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T13:09:14+0800
Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\Forbidden: No read permissions		2019-05-18T13:09:04+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T13:09:02+0800
Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\Forbidden: No read permissions		2019-05-18T13:09:00+0800
Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\Forbidden: No read permissions		2019-05-18T13:08:52+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T13:08:51+0800
Error	index	OCP\Files\NotFoundException: Node for share not found, fileid: 75629		2019-05-18T13:08:51+0800

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #15874

### CODE REVIEW

**Review by georgehrke — APPROVED** [review]
Code change looks good 👍

**Review by ChristophWurst — APPROVED** [review]
:see_no_evil:

**Comment by Octopus2** [comment]
@skjnldsv I have the same behavior in 15.0.8. Is it possible to backport the fix to 15?

**Pull request merged**
