### PR TITLE
Fix default redirect on successful WebAuthn login

### PR DESCRIPTION
**Pull request by st3iny**
* Resolves: ---

A quick search didn't show a related ticket but there might be some.

## Summary

A user is redirected to `/false` after logging in succesfully when no redirect url parameter is specified. I added a default url as a fallback.

### Before

The user is redirected to the page specified via the `redirect_url` parameter. If it isn't set, the user is redirected to `/false`.

image

### After

The user is redirected to the page specified via the `redirect_url` parameter. If it isn't set, the user is redirected to the configured default page.

## TODO

- [x] Probably fix tests

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
This might be an old bug. Before https://github.com/nextcloud/server/pull/34662 we'd still redirect to the default page.

**Review by ChristophWurst — APPROVED** [review]
:see_no_evil:

**Review by come-nc — APPROVED** [review]

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by st3iny** [comment]
> This might be an old bug. Before #34662 we'd still redirect to the default page.

Ahh, that would explain why it was broken but nobody noticed until recently.

**Comment by szaimen** [comment]
This was only a problem in master so no need for backports

**Pull request merged**
