### PR TITLE
Check share attributes on preview endpoints

### PR DESCRIPTION
**Pull request by juliusknorr**
Signed-off-by: Julius Härtl <jus@bitgrid.net>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by come-nc — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by PVince81** [comment]
test failures are related:
```
1) Tests\Core\Controller\PreviewControllerTest::testNoPreview
Error: Call to a member function instanceOfStorage() on null

/drone/src/core/Controller/PreviewController.php:134
/drone/src/core/Controller/PreviewController.php:84
/drone/src/tests/Core/Controller/PreviewControllerTest.php:190

2) Tests\Core\Controller\PreviewControllerTest::testValidPreview
Error: Call to a member function instanceOfStorage() on null

/drone/src/core/Controller/PreviewController.php:134
/drone/src/core/Controller/PreviewController.php:84
/drone/src/tests/Core/Controller/PreviewControllerTest.php:223
```

@juliushaertl can you have a look ?

**Comment by juliushaertl** [comment]
Failure seems unrelated, but restarted because I haven't seen that specific acceptance test failure yet on CI.

**Pull request merged**
