### PR TITLE
Define constants for the talk user agents

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Review by mario — APPROVED** [review]

**Comment by mario** [comment]
This will have to be backported to 12 so we can use Talk on 12 as well.

**Comment by nickvergessen** [comment]
Nop, because the server app will also not be backported...

**Comment by mario** [comment]
Ah ok, then I either misunderstood something or the plans changed :)

**Review by rullzer — APPROVED** [review]
sure

**Pull request merged**
