### PR TITLE
Properly calculate primary element based on background luminance

### PR DESCRIPTION
**Pull request by skjnldsv**
| Dark primary with dark theme | Bright primary on light theme |
|:---------:|:------:|
|||
|||

supersede #32500 
closes https://github.com/nextcloud/server/pull/32500

### CODE REVIEW

**Comment by skjnldsv** [comment]
For 24 and below, https://github.com/nextcloud/server/pull/32510

**Review by CarlSchwan — APPROVED** [review]

**Comment by artonge** [comment]
Ok code wise, but this does not respect the primary color.

Maybe [`elementColor`](https://github.com/nextcloud/server/blob/d64a63abc68ec50530b7b0cbf21cec9c31e1e178/apps/theming/lib/Util.php#L78) should try to use a darker or a lighter color based on the primary color instead of defaulting to dark or light gray ?

Perhaps a question for @jancborchardt : Should we default to gray when the primary color does not have enough luminance, or should we try to derive a new color from the primary color ? A third option would be to have a new setting to specify a primary color for dark themes.

**Comment by jancborchardt** [comment]
We do need to fall back to gray when the contrast would be too low otherwise, e.g. for light yellow or plain white.

This seems to look good, but the folder icons on dark primary with dark theme should probably not be black as it's almost not visible?

**Comment by skjnldsv** [comment]
> Maybe [`elementColor`](https://github.com/nextcloud/server/blob/d64a63abc68ec50530b7b0cbf21cec9c31e1e178/apps/theming/lib/Util.php#L78) should try to use a darker or a lighter color based on the primary color instead of defaulting to dark or light gray ?

I agree, but this is a different topic ;)
Improving this should be a followup.
This just fixes the behaviour by using something we created for this purpose.

Adapting the Util logic and methods can be discussed afterwards.
I think we need to sit down with the design team and make an update on how we use use to do things ans what we are not able to do with 25 (technically speaking)

**Review by artonge — APPROVED** [review]

**Pull request merged**
