### PR TITLE
[stable12] Also make sure remote.php and public.php don't work on 7.2

### LINKED ISSUE #7415: WebDav still works with PHP 7.2
Hello,

I am part of the unfortunate ArchLinux community who upgraded PHP to 7.2 when NC12 is not compatible... See #7384 for more details!

When I open NC, I have the following message:
`This version of Nextcloud is not compatible with PHP 7.2.
You are currently running 7.2.0.`

So I expect NC not to work at all. Fortunately for me, NC Android Apps and desktop sync agents can still access data on my server.

It is not suppose to works but it does so that make it a bug :wink:

PS: thank to NextCloud developers and community for a such great app!! :relaxed:

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #7415

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by danxuliu — COMMENTED** [review]
Wouldn't it be better to backport #6830 (as it covers too other files like _cron.php_ or _status.php_)?

**Comment by rullzer** [comment]
in theory I guess...

**Comment by MorrisJobke** [comment]
> Wouldn't it be better to backport #6830 (as it covers too other files like cron.php or status.php)?

Please do that.

**Comment by rullzer** [comment]
see https://github.com/nextcloud/server/pull/8216

**Pull request closed without merging**
