### PR TITLE
Remove svg shadows

### LINKED ISSUE #5593: Better handling of inverted icons
My thoughts related to #5450 - which is just one example of problems with icons in NC.

I don't think using `icon-more-white` to display dark variant of the icon is a very elegant approach. I'm wondering if we can come up with a better solution for such situations ( #5450 is only an example). Here are several proposals that we might want to consider in future releases:

1. SVG: use inline SVG as icon source (many pros and cons, I'm not going to list them here), set `fill` in CSS as needed
2. JS: toggle between `icon-more` and `icon-more-white` classes using JS
3. CSS: use CSS `filter: invert(100%)` property, which is quite nicely [supported](http://caniuse.com/#feat=css-filters) already

My personal favourite of those is `fill`, but `filter()` would also be neat. Both of these would allow us to deprecate a considerable amount of existing icons. They would also give us possibility to theme icons (I guess folder icon is the only obvious candidate here).
SVG-based solution would additionally allow us to have icons-within-icons without maintaining a separate asset, such as core/img/filetypes/folder-public.svg - but it might not be feasible just yet :cry: 

I would like to hear your thoughts @nextcloud/designers @nextcloud/theming

### PR DESCRIPTION
**Pull request by pixelipo**
@nextcloud/designers next step in cleaning up icons.

- drop-shadow is stronger to make white, shaded icons more visible on white backgrounds
- allow 3 extra icon variants (in addition to default black) - white, shadow and white+shadow
- old classes are still working as expected for backwards compatibility (should be deprecated in the future)
- @nextcloud/gallery templates updated to use new classes https://github.com/nextcloud/gallery/pull/331
- @nextcloud/talk templates updated to use new classes https://github.com/nextcloud/spreed/pull/509
- removed deprecated SVG icons
- migrated apps/gallery/img/toggle.svg to core/img/actions/toggle-background.svg

Fixes #5593

### CODE REVIEW

**Comment by pixelipo** [comment]
Gallery and Talk apps are known to use icons that were affected by this PR;
I've created PRs for them as well:
https://github.com/nextcloud/spreed/pull/509
https://github.com/nextcloud/gallery/pull/331

Other apps should not be affected by this change (but please test if you know of icons being used elsewhere)

**Comment by nickvergessen** [comment]
I think the play and pause icons are also used by the audio player app (dont remember the name).

Would also be nice to not remove icons in the late beta/rc phase.
Devs already submitted updates to the appstore, so they should still work...

**Comment by pixelipo** [comment]
I generally agree, @nickvergessen 

but (there's always a but) :smile: 

- audio app is using custom icons
- audio, video, screen and fullscreen icons are still backwards-compatible for all apps that are using existing "official" icon classes (defined in global icons.scss)
- :arrow_up: do break for apps that have custom classnames, but no app should do things that way...
- view-* icons will break compatibility since they were never defined in icons.scss
- this doesn't have to be merged in 13 if it's too late

If keeping the icons will allow this to be merged in 13, then I will do it right away. So?

**Comment by MorrisJobke** [comment]
> If keeping the icons will allow this to be merged in 13, then I will do it right away. So?

Yes - I would not merge it if it breaks with existing apps. Having the css classes there already would be a nice improvement. So apps can adjust but don't loose support. I would say, that dropping of the images is fine for 14 only.

**Comment by pixelipo** [comment]
Done, @MorrisJobke @nickvergessen those icons are 90% not used anywhere (so they will not be loaded on pages at all), but it's better to keep them here for safety reasons in NC13.

In general, this is part of the #5157 task. When I'm finished with it, I'll add documentation so it will be official/obligatory from NC14

**Comment by nickvergessen** [comment]
@pixelipo thanks, the main issue is that our icons have no "defined" public. Some APIs for example use the images directly without CSS, so removing them breaks no matter which fallbacks you add for CSS. If there was no beta out, I'd be fine with dropping images etc. But after a beta people test their apps once and assume they will just continue to work fine ;)

**Comment by skjnldsv** [comment]
The icon-white filter isn't suitable for buttons with icon and text since it will revert the text too.
The idea is great but we need a workaround for this :)

**Comment by pixelipo** [comment]
@skjnldsv I'm not sure that is an actual problem. If a text is black, than it means the button has white background, so nobody would use `.icon-white` on it.

You only need `.icon-white` icons that are on dark backgrounds, so if that icon happens to be a button with text, then text should also be inverted.

Perfect example is the searchbox in the header. I just did a quick test and it can easily be made to use icon-white property.

**Comment by skjnldsv** [comment]
@pixelipo Hum, good point. So we should add this in the documentation to explain that you should not change the font colour as everything will be handled by the filter. :)

**Comment by jancborchardt** [comment]
@pixelipo icon-shadow only makes sense in connection with icon-white anyway, no (or if the icon is white itself, in which case it should have the icon-white class)? So icon-shadow should be a subitem of icon-white, not the other way around. Cause not all white icons need shadow, but all shadowed icons are white.

**Comment by pixelipo** [comment]
That makes sense, @jancborchardt - I've pushed the simplified CSS definitions.

Please test again, especially in Talk and Gallery apps.

**Comment by skjnldsv** [comment]
Makes more sense yes! :)

**Review by skjnldsv — APPROVED** [review]

**Comment by pixelipo** [comment]
Any plans to merge this soon? Please keep in mind that related PR was already merged in Gallery, so that app is broken on master until this is merged, too...

**Review by MorrisJobke — APPROVED** [review]
I fixed a syntax error in the scss. 👍

**Comment by skjnldsv** [comment]
@MorrisJobke was the test failing before your fix?

**Comment by MorrisJobke** [comment]
> @MorrisJobke was the test failing before your fix?

No - it was a drone issue.

**Pull request merged**
