### PR TITLE
chore: Bump @nextcloud/vue to v8 beta 6

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Release notes https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.0.0-beta.6

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- Screenshots before/after for front-end changes
- Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by Pytal** [comment]
All component styling is broken

This is because styles are no longer embedded in the js dist since https://github.com/nextcloud-libraries/nextcloud-vue/pull/4386, with the css being separated into the assets folder https://unpkg.com/browse/@nextcloud/vue@8.0.0-beta.6/dist/assets/

Webpack should handle these css imports, i.e. https://unpkg.com/browse/@nextcloud/vue@8.0.0-beta.6/dist/Components/NcButton.mjs, with css-loader but is not working here and I'm not sure why 🤔

Any ideas @ShGKme @susnux ?

**Comment by susnux** [comment]
> Any ideas @ShGKme @susnux ?

Webpack is working fine, the styles are included... But there is a bug:
When running development build for the vue library the assets are named correctly, but when running production build the CJS and MJS build will emit two sets of assets with different naming.
Meaning CJS overrides MJS assets (the css files), so that the wrong styles are loaded when using mjs.

I will work on a fix.

**Comment by susnux** [comment]
@Pytal resolved the issue, see https://github.com/nextcloud-libraries/nextcloud-vue/pull/4531

(Tested on current server master and works :) )

**Comment by ShGKme** [comment]
@susnux Is the server compatible now with `@nextcloud/vue@8.0.0-beta.6`?

**Comment by susnux** [comment]
> @susnux Is the server compatible now with `@nextcloud/vue@8.0.0-beta.6`?

No but we `@nextcloud/vue` master -> we need to release a beta.7 and then update server

**Pull request closed without merging**
