### PR TITLE
set 'no-store' cache header if we do not want FF to cache

### PR DESCRIPTION
**Pull request by ChristophWurst**
I noticed that FF often restores tabs either after closing the whole browser or a single tab and going back with (ctrl+shift+t). Those pages loaded faster, but could also lead to unexpected errors in single page apps like Mail because the complete browser state is saved. In fact, I even saw that FF caches ajax requests/responses in its bfcache which is totally weird IMO.
We even set 'no-store' already, but only if someone calls 'cacheFor(0)', so this was kind of incosistent https://github.com/nextcloud/server/blob/fe6416072d417b6ef166695008d9f94f07775dc9/lib/public/AppFramework/Http/Response.php#L86-L101

ref http://stackoverflow.com/questions/1195440/ajax-back-button-and-dom-updates/1195934#1195934 https://developer.mozilla.org/en-US/Firefox/Releases/1.5/Using_Firefox_1.5_caching http://stackoverflow.com/questions/866822/why-both-no-cache-and-no-store-should-be-used-in-http-response

cc @jancborchardt @Gomez maybe you guys have experienced this too

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Now I understand why we never had such issues in Files: as soon as the page uses an unload handler, the browser disables cache too http://stackoverflow.com/questions/2638292/after-travelling-back-in-firefox-history-javascript-wont-run

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
See https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.1 for the corresponding RFC

**Comment by rullzer** [comment]
Failing tests

**Comment by ChristophWurst** [comment]
> Failing tests

fixed.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
