### PR TITLE
Fix display of DTEND for multi-day all-day event

### LINKED ISSUE #19135: Invitation Mail shows the wrong end date on a multi day full day event
### Steps to reproduce
1. Make sure that invitations for events are sent to participants.
2. Create a multi day full day event (e. g. from 15.02.20 to 16.02.20) 
3. Add a participant for that event
4. Save the event

### Expected behaviour
The Participant should get a mail message inviting her for an event from 15.02.20 until 16.02.20 

### Actual behaviour
The Participant gets a mail message inviting her for an event from 15.02.20 until 17.02.20, which is one day longer as expected

### Calendar app
2.0.1
**CalDAV-clients used:** ( macOS Calendar) but also when entered at the Nextcloud web frontend

### Client configuration
**Browser:** (Safari 13.0.4)

**Operating system:** (e.g. OS X)

### Server configuration

**Operating system**: (e.g. OS X)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, S)

**PHP version:** (e.g. 7..1.32)

**Nextcloud Version:** (17.0.2)

**Updated from an older installed version or fresh install:** fresh install

**List of activated apps:**
Accessibility	1.3.0	Offiziell	
Activity	2.10.1	Offiziell	
Brute-force settings	1.5.0	Offiziell	
Calendar	2.0.1	Offiziell	
Collaborative tags	1.7.0	Offiziell	
Comments	1.7.0	Offiziell	
Contacts	3.1.8	Offiziell	
Deleted files	1.7.0	Offiziell	
Federation	1.7.0	Offiziell	
File sharing	1.9.0	Offiziell	
First run wizard	2.6.0	Offiziell	
Gallery	18.4.0	Offiziell	
Log Reader	2.2.0	Offiziell	
Monitoring	1.7.0	Offiziell	
Nextcloud announcements	1.6.0	Offiziell	
Notifications	2.5.0	Offiziell	
Notifications for calendar event updates	1.0.1
Password policy	1.7.0	Offiziell	
PDF viewer	1.6.0	Offiziell	
Privacy	1.1.0	Offiziell	
Recommendations	0.5.0	Offiziell	
Right click	0.15.1	Offiziell	
Share by mail	1.7.0	Offiziell	
Support	1.0.1	Offiziell	
Talk	7.0.2	Offiziell	
Text	1.1.1	Offiziell	
Theming	1.8.0	Offiziell	
Update notification	1.7.0	Offiziell	
Usage survey	1.5.0	Offiziell	
Versions	1.10.0	Offiziell	
Video player	1.6.0	Offiziell	
Viewer	1.2.0	Offiziell

**Nextcloud configuration:**
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' =>
  array (
    0 => '***',
  ),
  'datadirectory' => '/Library/Server/Web/Data/Sites/***/data',
  'dbtype' => 'mysql',
  'version' => '17.0.2.1',
  'overwrite.cli.url' => 'http://***',
  'dbname' => '***',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'installed' => true,
  'maintenance' => false,
  'mail_from_address' => '***',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '***',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '***',
  'mail_smtpport' => '25',
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpname' => '***',
  'mail_smtppassword' => '***',
);

{"reqId":"XZvVTdcA4Eqg9iiBW07S","level":3,"time":"**2020-01-25T16:09:39+00:00**","remoteAddr":"127.0.0.1","user":"***","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/calendars\/***\/test\/F4B015D6-18ED-41E7-BA56-7B1E28CD2CE8.ics","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/Library\/Server\/Web\/Data\/Sites\/cloud.britzke.berlin\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/13.0.4 Safari\/605.1.15","version":"17.0.2.1"}

Note:
The time logged here is exactly on our bevor the time, my system clock. My system clock tells Sa 25 Jan 2020 17:12:52 CET now (some minutes after the log event). It seems that the time logged is UTC and we are here at CET. May be this depends?

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #19135

### CODE REVIEW

**Review by tcitworld — APPROVED** [review]
Indeed, works properly now.

**Review by rullzer — APPROVED** [review]

**Pull request merged**
