### PR TITLE
Log the route not found exception on a lower level

### PR DESCRIPTION
**Pull request by rullzer**
This should be logged but it is not that critical to wanner level 3

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by kesselb** [comment]
Should fix #20572 (by not logging the error anymore) but https://github.com/nextcloud/server/pull/14266#issuecomment-618874270 is still happening.

**Review by MorrisJobke — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by simonspa** [comment]
@rullzer could this be backported to stable19 too?

**Comment by florom** [comment]
Hi Devs,

I encountered this issue again with
21.0.1
php 7.3.latest
mariadb 10.latest

Probably something is wrong (again)

Inf

Inf

Info | no app in context |

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "phonetrack.page.index" as such route does not exist.

/var/www/nextcloud/lib/private/Route/Router.php - line 365:

Symfony\Component\Routing\Generator\UrlGenerator->generate("phonetrack.page.index", [], 1)

/var/www/nextcloud/lib/private/Route/CachingRouter.php - line 60:

OC\Route\Router->generate("phonetrack.page.index", [], false)

/var/www/nextcloud/lib/private/URLGenerator.php - line 85:

OC\Route\CachingRouter->generate("phonetrack.page.index", [])

/var/www/nextcloud/apps/phonetrack/lib/AppInfo/Application.php - line 58:

OC\URLGenerator->linkToRoute("phonetrack.page.index")

/var/www/nextcloud/lib/private/NavigationManager.php - line 110:

OCA\PhoneTrack\AppInfo\Application->OCA\PhoneTrack\AppInfo\{closure}("*** sensiti ... *")

/var/www/nextcloud/apps/theming/lib/ThemingDefaults.php - line 184:

OC\NavigationManager->getAll("guest")

/var/www/nextcloud/lib/private/legacy/OC_Defaults.php - line 263:

OCA\Theming\ThemingDefaults->getShortFooter()

/var/www/nextcloud/lib/public/Defaults.php - line 169:

OC_Defaults->getLongFooter()

/var/www/nextcloud/core/templates/layout.guest.php - line 55:

OCP\Defaults->getLongFooter()

/var/www/nextcloud/lib/private/Template/Base.php - line 178:

include("/var/www/ne ... p")

/var/www/nextcloud/lib/private/Template/Base.php - line 150:

OC\Template\Base->load("/var/www/ne ... p", null)

/var/www/nextcloud/lib/private/legacy/OC_Template.php - line 180:

OC\Template\Base->fetchPage(null)

/var/www/nextcloud/lib/private/legacy/OC_Template.php - line 211:

OC_Template->fetchPage(null)

/var/www/nextcloud/lib/private/Template/Base.php - line 132:

OC_Template->fetchPage()

/var/www/nextcloud/lib/private/legacy/OC_Template.php - line 332:

OC\Template\Base->printPage()

/var/www/nextcloud/index.php - line 63:

OC_Template::printExceptionErrorPage(Exception {}, 500)

-- | -- | -- |

2021-04-12T09:47:57+0200

Thank you.

**Pull request merged**
