### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by tcitworld**
Just a quick typo fix.

See `Sabre\DAV\Xml\Service`

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Backport down to stable9 needed.

**Comment by MorrisJobke** [comment]
Tags works 👍

**Comment by MorrisJobke** [comment]
> Tags works 👍

And PHPStorm doesn't complain anymore.

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer

**Comment by nickvergessen** [comment]
👍

**Pull request merged**
