### PR TITLE
[upstream] Adding quota plugin to new dav endpoint

### PR DESCRIPTION
**Pull request by LukasReschke**
Sync from https://github.com/owncloud/core/pull/25615

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by schiessle** [comment]
:+1:

**Comment by schiessle** [comment]
should we backport it to stable10?

**Comment by LukasReschke** [comment]
Would say so. Otherwise quota is completely ignored on that endpoint. Will open a backport PR.

**Comment by LukasReschke** [comment]
stable10: https://github.com/nextcloud/server/pull/654
stable9: https://github.com/nextcloud/server/pull/655

cc @karlitschek

**Comment by karlitschek** [comment]
backport makes sense 👍

**Pull request merged**
