### PR TITLE
Fallback to root if the picker folder doesn't exists

### PR DESCRIPTION
**Pull request by skjnldsv**
Working on the Photos default folder picker, I noticed that if you call the `getFilePickerBuilder` with an invalid value/folder, it just exploded without loading anything.

Adding this make sure we fallback to the user root `/` if the provided directory i non-existent 

```js
const updatePhotosFolder = '/fake/unknown/path'
const picker = getFilePickerBuilder(t('photos', 'Select the default location for your Photos'))
	.setMultiSelect(false)
	.setModal(true)
	.setType(1)
	.addMimeTypeFilter('httpd/unix-directory')
	.allowDirectories()
	.startAt(updatePhotosFolder)
	.build()

picker.pick()
	.then(updatePhotosFolder)
```

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by skjnldsv** [comment]
Ping everyone :)

**Review by CarlSchwan — APPROVED** [review]

**Comment by szaimen** [comment]
conflicts

**Comment by skjnldsv** [comment]
> /compile amend /

Please don't add the missing files if you don't plan to merge straight away :see_no_evil: 

> conflicts

Rebasing 😬

**Comment by ShGKme** [comment]
Is it complex to backport it to stable23?

**Comment by szaimen** [comment]
stable23 is EOL

**Pull request merged**
