### PR TITLE
Added security and games icons

### LINKED ISSUE #7174: Games & security category in app management don't have icons
bildschirmfoto 2017-11-14 um 23 25 52

cc @nextcloud/designers @skjnldsv Mind to fix that easy one?

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #7174 
capture d ecran_2017-11-15_16-47-57

@nextcloud/designers

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looking good!

**Comment by jancborchardt** [comment]
We do not have any games though, so not sure why that category shows up again. cc @BernhardPosselt?

**Comment by BernhardPosselt** [comment]
@georgehrke is working on one

**Comment by MariusBluem** [comment]
The icon should be included as the category is available in the appstore, but as long as there are no apps in there - it should be hidden :)

**Comment by pixelipo** [comment]
Games icon needs some work. I'll add a commit to this PR tomorrow, ok?

**Review by LukasReschke — APPROVED** [review]

**Review by pixelipo — CHANGES_REQUESTED** [review]
Blocking merge till tomorrow to clean up games icon

**Comment by georgehrke** [comment]
but the games icon should ideally be hidden if there are non compatible apps

**Comment by ChristophWurst** [comment]
> We do not have any games though

We not have any games *yet*. https://github.com/christophWurst/nextcloud_game

**Comment by skjnldsv** [comment]
> Games icon needs some work. I'll add a commit to this PR tomorrow, ok?

What kind of work? :(
I liked my icon! :)

**Comment by pixelipo** [comment]
It is a good icon, @skjnldsv , but it had a lot of redundant code - like transformation matrix, some styling etc. I removed that (filesize down from 1.6 kB to 583 B) and also made its features a bit more distinct - check before:
games-before

and after:
games-after

Is that OK?

**Review by pixelipo — APPROVED** [review]
@skjnldsv looks good now :)

**Review by MorrisJobke — APPROVED** [review]
Looks awesome now 👍

**Comment by skjnldsv** [comment]
@pixelipo you're the svg master!

**Comment by jancborchardt** [comment]
Good work @skjnldsv and @pixelipo!

**Pull request merged**
