### PR TITLE
Add WebAuthn support

### PR DESCRIPTION
**Pull request by rullzer**
This adds basics support for webauthn.

* Allow users to register a webauthn device on the settings page
* ALlow users to login with a webauthn device

TODO:
- [x] Handle actual login (chain)
- [x] Make the login page not look so hiddeous
- [x] Show registered FIDO2 devices on settings page
- [x] Allow deletion of devices
- [x] Update 3rdparty https://github.com/nextcloud/3rdparty/pull/391
- [X] Config flag to disable FIDO2 logins system wide
- [x] Don't show webauthn if it is not available on the server
  * [x] Settings
  * [x] login
- [x] Show warning if it is used over http (it needs https)
  * [x] settings
  * [x] login
- [x] Check if PublicKeyCredential is available in this browser
  * [x] settings
  * [x] login
- [x] Check if the possible credentials returned are empty. If so show an error.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Tested & works :)

**Review by ChristophWurst — APPROVED** [review]

**Comment by juliushaertl** [comment]
@rullzer Seems there are most of the changes lost since the last push:

image

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
We should add the required php modules bcmath and gmp to the documentation once merged.

**Comment by g6094199** [comment]
would also be [usefull for this ](https://github.com/nextcloud/server/issues/20817)

**Comment by bentolor** [comment]
Thanks for this great feature.

I just updated to NC 19 and **was able to register devices as admin user** but **not as standard user**. I even created a new, vanilla user.

As admin user the server returns a valid HTTP 200 and JSON document in its XHR request to `/settings/api/personal/webauthn/registration`.

As existing or newly created standard user I only get a HTTP 403 Forbidden. The response payload does contain HTML page with a internationlized "Permission denied" message.

Do I miss something, @rullzer ?

**Comment by acsfer** [comment]
This also Fix https://github.com/nextcloud/server/issues/17038

**Comment by ChristophWurst** [comment]
Hi,

let's not spam this pull request :)

For any issues or questions please use https://help.nextcloud.com/. Bugs can be opened here on github :v:

**Pull request merged**
