### PR TITLE
Nmc 434-changed the process of sharing

### PR DESCRIPTION
**Pull request by TSI-yogeshshejwadkar**
Step 1:
Folders
Internal Share:
we removed the checkboxes "Allow editing", "Allow creating" and "Allow deleting"
we added a radio button group containing the options: "Read only" (Nur Lesen), "Allow upload and editing" (Hochladen & Bearbeiten)
External Share: no changes
Link Share: no changes

Files
Internal Share:
we removed the checkbox "Allow editing"
we added a radio button group containing the options: "Read only" (Nur lesen), "Editing" (Bearbeiten)
External Share:
we removed the checkbox "Allow editing"
we added a radio button group containing the options: "Read only" (Nur lesen), "Editing" (Bearbeiten)
Link Share:
we removed the checkbox "Allow editing"
we added a radio button group containing the options: "Read only" (Nur lesen), "Editing" (Bearbeiten)

Step 2:
We added a new dropdown button under the display of the email-address or account name of the recipient

For folders
Internal user - Ready only and Allow upload and editing
External user - Read only, allow upload and editing, file drop
Share link - Read only, allow upload and editing, file drop
For files
Internal user - Read only, editing
External user - Read only ,editing
Share link - Read only ,editing
Ignored hasStatus which is having message and icon below user name or email address. We are removing this functionality in sharing 4. Also Nextcloud will change something with that function after we added this new button as discussed with Jens.
Also keeping the existing options in hamburger menu, as we will remove those in sharing 3.

In Step 3:
we want to change the conplete process of sharing. Let's explain it also in small steps:
-> We don't want to send directly an Email for internal and external shares to the recipient after we entered the Email address
->instead of sending directly the Email, the user will now get lead to a full right menu view with the sharing and premission options first
-> after the first page of sharing and permission options, there will be a second full right menu view for entering a message to the Email (note to recipient option of Nextcloud)

Please ignore as well the shown permission options in the full right menu views. Please concentrate to extract existing sharing options of the different sharing systems (internal, external & link shares). So we are extracting all existing options (except "note to recipeient") to build the first full right menu view and we use the existing "note to recipient" function to create a second full right menu view. We combine them to the flow, which is drafted within the attached screens.

Acceptance Criteria:
if the user enters an Email-address and confirms it by pressing 'enter', the autofill function of Nextcloud will provide suggestions (it is already like this in Nextcloud and we keep that)
when the user now tabs on a provided Email-Address, we are not anymore sending directly an Email to the repient
we are instead leading the user to a first full right menu view with the permission and sharing options containing:
Radio button group with permission options (Read only, Upload and editing, Filedrop if it is a folder)
we group up under a small headline called "Advanced settings" (ger: "Erweiterte Einstellungen") all the rest of the sharing options e.g. password, expiration date, hide download, and so on) but not the "note to recipient" option!
on this full right menu view ** the user can "Cancel" or "Next" by having two buttons
if the user continues by clicking on "Next" he will get lead to another full right menu view ** with the last sharing option of "note to recipient" of Nextloud. Here the user can enter text.
on this view the user can "Cancel" or "Send share" by having two buttons
we removing all options from the exisitng "..."-menu except "unshare"
hide download should disable on file drop permission
 
After the process
clicking on the "..."-menu will slide in a button menu (like on the big "add" button n Nextcloud) with the following options:**
"Open in..." (ger: "Öffnen mit...") -> will open the Android share screen for sharing with other applications
we added"Advanced permissions" (ger: "Erweiterte Berechtigungen")
"Advanced permissions" will lead to the first new full right menu view ** with all the permission option (except note to recipient) with 2 Button: "Cancel" (ger: "Abbrechen") and "Confirm" (ger: "Übernehmen")
we added to the existing "..."-menu "Send new email" (ger: "Neue Email versenden")
"Send new email" will lead to the second new full right menu view ** with the text field to enter a message; we added two buttons: "Cancel" (ger: "Abbrechen") and "Send email" (ger: "Email senden")
"Unshare" (ger: "Freigabe beenden") will remove the share
we removed all the other remaining options by hiding them
clicking on the new permission button ot of Sharing #2 will lead to standard Nextccloud dialog box with the radio button options (read only, can edit, file drop if it is a folder)

Screenshot from 2021-09-16 11-28-52
Screenshot from 2021-09-16 11-28-16
Screenshot from 2021-09-16 11-27-58
Screenshot from 2021-09-16 11-27-42
Screenshot from 2021-09-16 11-27-26
Screenshot from 2021-09-16 11-27-14

### CODE REVIEW

**Comment by jancborchardt** [comment]
Hi @TSI-yogeshshejwadkar could you add screenshots for easier design review? Thanks a lot! :)

**Comment by TSI-yogeshshejwadkar** [comment]
> Hi @TSI-yogeshshejwadkar could you add screenshots for easier design review? Thanks a lot! :)

Updated :)

**Comment by AndyScherzinger** [comment]
@juliushaertl @skjnldsv can you provide to review feedback here? Also if merged it should get backported to 22+

**Comment by juliushaertl** [comment]
Also @jancborchardt for feedback on the updated UI.

**Comment by AndyScherzinger** [comment]
Superseeded by #26691

**Pull request closed without merging**
