### PR TITLE
Remove the escape-html global

### PR DESCRIPTION
**Pull request by rullzer**
Already announced for 19 that it would go. So now it realy does go.

:broom:

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by MorrisJobke** [comment]
JS unit failures and conflicts.

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:broom: :broom:  :broom:

**Comment by ChristophWurst** [comment]
Documented at https://github.com/nextcloud/documentation/pull/5160

**Pull request merged**
