### PR TITLE
Revert "Update guzzlehttp/guzzle requirement from 6.5.2 to 6.5.3 in /build/integration"

### PR DESCRIPTION
**Pull request by rullzer**
Reverts nextcloud/server#20554

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Please commit the composer.lock too

**Comment by rullzer** [comment]
Lets fix that all after the tests pass again ;)

**Review by danxuliu — APPROVED** [review]
Fixes the integration-remote-api tests :+1: Other test failures are unrelated.

The issue seemed to be a mismatch between the Guzzle version in _/build/integration_ and [the one in _/3rdparty_](https://github.com/nextcloud/3rdparty/blob/f7b86b6e3abc0804de9c281003172f67960392f4/composer.json#L21). I do not know if there is an automatic way to keep both in sync.

**Comment by rullzer** [comment]
> Fixes the integration-remote-api tests +1 Other test failures are unrelated.
> 
> The issue seemed to be a mismatch between the Guzzle version in _/build/integration_ and [the one in _/3rdparty_](https://github.com/nextcloud/3rdparty/blob/f7b86b6e3abc0804de9c281003172f67960392f4/composer.json#L21). I do not know if there is an automatic way to keep both in sync.

Yeah shitty php stuff

**Pull request merged**
