### PR TITLE
l10n: Spelling unification

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Transifex.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by rakekniven** [comment]
@Valdnet Here I not agree. Why addings these spaces? Strings will be wrapped if needed. 

What is your reason for adding these spaces?

**Comment by Valdnet** [comment]
@rakekniven Transifex has slash sentences that are spelled differently. Some words with slashes are separated by a space, not which aren't.

For example:
[LDAP / AD](https://www.transifex.com/nextcloud/nextcloud/translate/#pl/$/91002408?q=text%3A%2F)
[LDAP/AD](https://www.transifex.com/nextcloud/nextcloud/translate/#pl/$/91002345?q=text%3A%2F)

After checking the spelling for English, words separated by a slash should be spelled like this: xxx / yyy.
Referring to linguistics, the sign "/" replaces the word "and", "or".

But I can be wrong 😉.

Please review by other users and comment on this matter.

**Comment by rakekniven** [comment]
> After checking the spelling for English, words separated by a slash should be spelled like this: xxx / yyy.
> Referring to linguistics, the sign "/" replaces the word "and", "or".

Do you have any reference for it?

**Comment by Valdnet** [comment]
@rakekniven We will stick to this manual: [English Style Guide](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjfx4jml5LwAhUZwAIHHRdnCW04ChAWMAB6BAgDEAM&url=https%3A%2F%2Fec.europa.eu%2Finfo%2Fsites%2Finfo%2Ffiles%2Fstyleguide_english_dgt_en.pdf&usg=AOvVaw0iA1WqeeTQwV_s3ORyscpT).
According to this instruction, single words should be separated only by a slash, e.g. `xxx/zzz`. However, two-part words should be separated additionally by a space ,e.g. `yyy yyy / zzz zzz`.

In this case, what do we do with the words in Transifex? They should be thoroughly checked and standardized in order to improve the translation mechanism and, above all, to standardize the text strings in the Nextcloud instance.

**Pull request closed without merging**
