### PR TITLE
Don't set Content-Disposition header if one already exists

### PR DESCRIPTION
**Pull request by LukasReschke**
If a Content-Disposition header is already set by another plugin we don't need to set another one as this breaks clients.

Fixes https://github.com/nextcloud/server/issues/1992

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]
looks good

**Comment by LukasReschke** [comment]
Failing JSUnit is unrelated.

**Review by rullzer — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Thanks!

**Comment by jancborchardt** [comment]
Please also backport to stable11 @LukasReschke

**Comment by MorrisJobke** [comment]
> Please also backport to stable11 @LukasReschke

ing

**Comment by nickvergessen** [comment]
Backport in https://github.com/nextcloud/server/pull/2949

**Pull request merged**
