### PR TITLE
Prevent duplicate entries in file sidebar

### LINKED ISSUE #18744: duplicate entries in file's activity tab
### Steps to reproduce
1. Create a file
2. change that file
3. share the file
4. refresh the page
5. open file's activity sidebar tab

### Expected behaviour
- 1 entry for creation
- 1 entry for editing
- 1 entry for sharing

### Actual behaviour
- 2 entries for creation
- 2 entries for editing
- 2 entries for sharing

Peek 2020-01-08 13-25

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #18744 

The watcher on `activeTab` will call `setFileInfo` when mounting so the `beforeMount` hook is not required.
Tested on my machine with the activity app and haven't run into issues but not entirely sure if there are maybe other cases in which the hook is required?

### CODE REVIEW

**Comment by rullzer** [comment]
master is NC19 now.
Please backport if it needs to go into 18

**Review by skjnldsv — APPROVED** [review]
:elephant:

**Review by juliusknorr — APPROVED** [review]
Makes sense :+1:

**Comment by kesselb** [comment]
Conflicts :fearful:

**Comment by gary-kim** [comment]
Rebased

**Review by ChristophWurst — APPROVED** [review]
Code makes sense

**Pull request merged**
