### PR TITLE
Fix grid toggle button on public page

### LINKED ISSUE #13375: Add a thumbnail/grid view to folders shared via public link
NC 15

Share folder via public link.
Open the link.

There is no way to choose grid view, only thumbnail view available.
image

### PR DESCRIPTION
**Pull request by skjnldsv**
Broken by #12385
Fix #13375

### CODE REVIEW

**Comment by jancborchardt** [comment]
Please review @R0maNNN @myevit @Bellusterra as it fixes the issue you reported at https://github.com/nextcloud/server/issues/13375 :)

**Comment by Bellusterra** [comment]
Thank you @jancbochardt

**Review by juliusknorr — DISMISSED** [review]
We still need to keep the check, otherwise we have the button on single file shares as well:

image

**Review by jancborchardt — DISMISSED** [review]
Also, the button should not have the button style (background and border), just like when logged in. :)

**Comment by skjnldsv** [comment]
@weeman1337 sure! Wanna help? :D

**Comment by weeman1337** [comment]
> sure! Wanna help? :D

I knew that would come :) A ticket for me: #13613

**Comment by myevit** [comment]
Hi guys, so sharing link though the gallery app has toggle button, once I press it it goes to file list and the button disappears

Also "Download" and "Download all files" :-)

https://victorsea.photography/nextcloud/index.php/apps/gallery/s/6iRrgxTNTmdF5eJ#
screen shot 2019-01-17 at 14 59 13
screen shot 2019-01-17 at 14 59 25

**Comment by skjnldsv** [comment]
This one slipped through!
@nextcloud/designers please review!
@jancborchardt @juliushaertl please update :bowing_woman:

**Review by jancborchardt — APPROVED** [review]
Looks good now!

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by digitall-it** [comment]
Old behavior of the toggle was to change the URL on the top, so that it was possible to permalink to gallery view, so that the link always points to gallery view by default. Latest versions of NextCloud do not allow that anymore because the toggle does not change add any URL fragment to account for that. Is there a way to at least manipulate the URL manually to achieve the same result? Tried on v18.0.6.

**Comment by PatriceVigier** [comment]
It would be great to be able to decide how we want to share a folder, list or thumb

**Pull request merged**
