### PR TITLE
Fix for issue #29433

### LINKED ISSUE #5406: Use LDAP user name instead of UUID for federated cloud id
Nextcloud (up to version 12.0.0) generates federated cloud ids of the shape uid@server. This leads to inconvenient cloud ids in case of LDAP users because the LDAP user app configures the UUID as Nextcloud uid per default. This is changeable via the LDAP configuration panel but changes only behaviour for new users (because I cannot clear the LDAP user mapping in a production environment).

It would be nice if this would be configurable on the federation cloud id level to generate cloud ids for LDAP users from the LDAP username.

Maybe the new cloud id api from pull request #3297 can be handy to implement this feature?

(s. also Nextcloud Forum here: https://help.nextcloud.com/t/changing-the-internal-user-name/8924)

### LINKED ISSUE #29433: MacOSX CalDAV/CardDAV + LDAP not working ===> Nextcloud UUID used in LDAP authentication instead of Username
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Enable LDAP Authentication
2. Generate new users ==> UUID
3. Export "Nextcloud Profile" to iOS and install it
4. "Unable to authenticate with username/password"

### Expected behaviour
CalDav/CardDav should work with LDAP auth backend

### Actual behaviour
Nextcloud does not know the "UUID" of the LDAP generated (only available inside Nextcloud)

### Server configuration

**Operating system:** Doesn't matter

**Web server:** Nginx

**Database:** SQL

**PHP version:** 7.4

**Nextcloud version:** 22

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated gradually from 14

**Where did you install Nextcloud from:** Source

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by itmanagerro**
Fix #29433

### CODE REVIEW

**Comment by acsfer** [comment]
Can you please fix the DCO?

**Review by itmanagerro — COMMENTED** [review]
Signed-off-by: ITManager <github.com@itmanager.ro>

**Comment by itmanagerro** [comment]
Not really sure if this worked or not :|

**Comment by itmanagerro** [comment]
New PR raised #31037 with DCO

**Pull request closed without merging**
