### PR TITLE
fix: consider all paths the user has for a share source when considering max permissions

### PR DESCRIPTION
**Pull request by icewind1991**
To test

- Create an external storage "Storage" for all users with sharing enabled
- As `user1` create folder "Storage/folder" and share it read-only with `user2`
- As `user2` attempt to share "Storage/folder" with edit permissions to `user3`

### CODE REVIEW

**Comment by icewind1991** [comment]
> when sharing Folder/Sub as user2, the api call has /Sub as the path.

I'm pretty sure this is because the share ui knows it's a reshare so this should be fine

**Review by Altahrim — APPROVED** [review]

**Review by come-nc — APPROVED** [review]
I cannot find it but you made a PR not long ago to use the node the user tried to share instead of the first one when checking reshare permission, is that a different fix for the same thing or two different cases?

**Comment by come-nc** [comment]
> I cannot find it but you made a PR not long ago to use the node the user tried to share instead of the first one when checking reshare permission, is that a different fix for the same thing or two different cases?

Ok I’m not crazy I think you forced push over it in this very PR :see_no_evil:

**Comment by icewind1991** [comment]
> > I cannot find it but you made a PR not long ago to use the node the user tried to share instead of the first one when checking reshare permission, is that a different fix for the same thing or two different cases?
> 
> Ok I’m not crazy I think you forced push over it in this very PR 🙈

Yeah that approach didn't end up working with in cases

**Pull request merged**
