### PR TITLE
Fix apppassword dropdown issues

### LINKED ISSUE #2526: Minor design issues with browser sessions and device passwords
Just updated my private installation to beta2 and notice some minor design issues on the personal settings page:

- [ ] multiple popover menu of sessions/passwords can be opened (they should close if I click somewhere outside the menu, there's a ``OC.registerMenu`` helper or similar)
- [ ] the popover's arrow is not aligned to the three dots, it's too much on the right

bildschirmfoto von 2016-12-06 11-23-32

cc @icewind1991 @nextcloud/designers

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #2526

cc @ChristophWurst

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍 

Either something for this PR or another one (because also broken on master):

* [ ] clicking somewhere outside of the menu or the 3 dots again should also close the current menu

**Comment by icewind1991** [comment]
> clicking somewhere outside of the menu or the 3 dots again should also close the current menu

Done

**Comment by MorrisJobke** [comment]
Tested in Firefox, Chrome, Safari, Edge and IE11 and it works 👍

**Comment by MorrisJobke** [comment]
@nickvergessen @skjnldsv @rullzer @nextcloud/designers Mind to review this one?

**Comment by skjnldsv** [comment]
👍 Perfect!

Just a small question, shouldn't we always display the three dots? Because on mobile the user won't know there is an option! 😕

**Comment by MorrisJobke** [comment]
> Just a small question, shouldn't we always display the three dots? Because on mobile the user won't know there is an option! 😕

Makes sense

**Pull request merged**
