### PR TITLE
Fix casing of exception string

### PR DESCRIPTION
**Pull request by MorrisJobke**
Change to capital letters in an abbreviation.

Rebase of #26580 to re-run the CI tests.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Critical change!

**Comment by rakekniven** [comment]
> 
> 
> Critical change!

Why is this a critical change?

**Comment by ChristophWurst** [comment]
> Why is this a critical change?

I think Roeland was being sarcastic

**Comment by rullzer** [comment]
> > Why is this a critical change?
> 
> I think Roeland was being sarcastic

I would never do that! :wink:

**Comment by MorrisJobke** [comment]
As this is green and just a straight rebase I will merge the other pr because it was from a first time contributor.

**Pull request closed without merging**
