### PR TITLE
Apply password policy on user creation

### PR DESCRIPTION
**Pull request by michag86**
Fix for #538

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
cc @schiessle @rullzer @nickvergessen

**Comment by nickvergessen** [comment]
integration tests fail

**Comment by michag86** [comment]
I do not understand how the error is related to my modification. :pensive:

**Comment by nickvergessen** [comment]
@rullzer is something broken thereon master?

**Comment by rullzer** [comment]
Yes will rebase when "fix"  is in master

**Comment by schiessle** [comment]
tested, works! Thanks for your contribution!

**Comment by schiessle** [comment]
:+1:

**Comment by schiessle** [comment]
failing tests are unrelated

**Comment by nickvergessen** [comment]
Should backport this @schiessle ?

**Pull request merged**
