### PR TITLE
[stable14] Just update password hash without validating

### PR DESCRIPTION
**Pull request by rullzer**
Backport of #11568

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by JB1985** [comment]
Version: 14.0.2 RC1

If I change from PHP7.2 to PHP7.0 I cant still login. I get the error Password wrong.

**Comment by MorrisJobke** [comment]
Downgrade of the PHP version is not supported. At least we never build it with that in mind.

**Comment by JB1985** [comment]
Interesting. That means if someone wants to test a PHP version, he can not do that because he can not go back?

never heard anything like that.

If someone changes their hoster and can not get the php version, then he has bad luck and can no longer use his cloud?

This is absolutely not user friendly. does not seem to want nc14 either.

👎🏼

**Comment by ChristophWurst** [comment]
> Interesting. That means if someone wants to test a PHP version, he can not do that because he can not go back?

Wrong. You can always restore a backup. Every reasonable admin will do a backup before a major system change.

> Please update your documentation. That's an important piece of information.

The documentation is actually available for everyone to improve, see https://github.com/nextcloud/documentation/. You can even use the GitHub UI to file your changes :v:

**Pull request merged**
