### PR TITLE
[stable27] fix(CardDAV): set owner-principal, displayname properties for SAB

### PR DESCRIPTION
**Pull request by miaulalala**
Manual backport of https://github.com/nextcloud/server/pull/39525

### CODE REVIEW

**Comment by miaulalala** [comment]
Not sure if this is missing a backport for the authentication fix? cc @JohannesGGE

**Comment by JohannesGGE** [comment]
https://github.com/nextcloud/server/pull/38397 got in on 18th July (2 days before 27.0.1). So I'm not sure as well, if we have to backport here. :sweat_smile: 
@ChristophWurst

**Comment by miaulalala** [comment]
looks like this was after branch off to stable27 then. Backport it is :slightly_smiling_face:

**Comment by miaulalala** [comment]
Needs https://github.com/nextcloud/server/pull/39904

**Review by skjnldsv — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]

**Comment by skjnldsv** [comment]
```
There was 1 failure:
295 |  
296 | 1) OCA\DAV\Tests\unit\CardDAV\AddressBookTest::testPropPatchShared
297 | OCA\DAV\CardDAV\CardDavBackend::updateAddressBook(666, Sabre\DAV\PropPatch Object (...)) was not expected to be called.
298 |  
299 | /drone/src/3rdparty/sabre/dav/lib/CardDAV/AddressBook.php:184
300 | /drone/src/apps/dav/lib/CardDAV/AddressBook.php:230
301 | /drone/src/apps/dav/tests/unit/CardDAV/AddressBookTest.php:118

```

**Pull request merged**
