### PR TITLE
Do not allow adding file drop shares to your own cloud

### PR DESCRIPTION
**Pull request by rullzer**
There is no reason for this and you can't create such shares normally
anyway.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Review by LukasReschke — APPROVED** [review]
Is it also possible to add another check within `$this->federatedShareProvider->create($share);`? I am afraid that there are otherwise similar issues in the future :)

**Comment by rullzer** [comment]
> Is it also possible to add another check within `$this->federatedShareProvider->create($share);`? I am afraid that there are otherwise similar issues in the future :)

You mean as extra? lets first get this in for the easy backport.

**Pull request merged**
