### PR TITLE
Fixed occ files:scan crashes on StorageNotAvailableException

### LINKED ISSUE #18864: NC 15.0.14 occ files:scan crashes on StorageNotAvailableException
### Steps to reproduce
1. Download and install NC 15.0.14
2. Run occ files:scan -all 
3. If a storage is not available it crashes

### Expected behaviour
Handle exception instead of crash

### Actual behaviour
Crashes because its calling a function that is only introduced in NC 16!

Error: Call to undefined method OC\AllConfig::getSystemValueInt() in/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php:454

```
	protected function setUnavailable(StorageNotAvailableException $e) {
		$delay = self::RECHECK_TTL_SEC;
		if($e instanceof StorageAuthException) {
			$delay = max(
				// 30min
	--->			$this->config->getSystemValueInt('external_storage.auth_availability_delay', 1800),
				self::RECHECK_TTL_SEC
			);
		}
		$this->getStorageCache()->setAvailability(false, $delay);
		throw $e;
	}
}

### PR DESCRIPTION
**Pull request by JanDragon**
Fix #18864

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks :+1: 

1) This pull request is against the wrong branch. `stable15` would be the one for Nextcloud 15. Usually pull request are against `master`. But `master`, `stable17` and `stable16` are fine. Only `stable15` is broken.
2) https://github.com/nextcloud/server/blob/5621c10cda7e64b9406f25a224de579b617ff9b6/lib/private/Files/Storage/Wrapper/Availability.php#L454 This place must be changed. `config.sample.php` needs to stay as before.

**Comment by jancborchardt** [comment]
@hagbartus can you review this as it fixes the issue you reported at https://github.com/nextcloud/server/issues/18864 – thanks! :)

**Comment by rullzer** [comment]
@icewind1991 please have a look as well

**Comment by blizzz** [comment]
> Only stable15 is broken.

15 is already EOL: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by kesselb** [comment]
> 15 is already EOL: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

I know. What do you suggest? If someone would update this pr to fix the actual bug (using a 16+ method to access system configuration) is there a change that you are going to release 15.0.15?

**Comment by blizzz** [comment]
it's not an upgrade blocker, right? Then it is: upgrade to 16.

**Comment by kesselb** [comment]
Thanks @JanDragon :+1: Closing this pull request. 15.0.15 release is not planned :disappointed:

**Comment by gmright2** [comment]
Is this pull request done to be pulling it

**Pull request closed without merging**
