### PR TITLE
LDAP: announce display name changes so that addressbook picks it up

### LINKED ISSUE #9112: Nextcloud 13: User changes do not get displayed
Hello,

I'm using LDAP as user source. Now I had to change some users last names und logins because of marrige. But the changes do not get into Nextcloud.

### Steps to reproduce
1. Change a users last/first name in LDAP
2. Log into Netzcloud
3. Search for the "new" user in Contacts

### Expected behaviour
The user should be displayed with the new values

### Actual behaviour
The user is show with his old data. On CLI occ display the new data.

### Server configuration

**Operating system**: Debian 8.10

**Web server:**  Apache

**Database:** MySQL

**PHP version:** 5.6.33

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Migrated from OC

**Where did you install Nextcloud from:** tar ball

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - audioplayer: 2.2.5
  - bruteforcesettings: 1.0.3
  - checksum: 0.3.5
  - circles: 0.13.6
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - richdocuments: 2.0.5
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - federation
  - files_external
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "loglevel": 3,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 30,
        "preview_max_x": 100,
        "preview_max_y": 100,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "overwrite.cli.url": ***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/"

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                  |
+-------------------------------+------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                  |
| homeFolderNamingRule          |                                                                                                                  |
| lastJpegPhotoLookup           | 0                                                                                                                |
| ldapAgentName                 |                                                                                                                  |
| ldapAgentPassword             | ***                                                                                                              |
| ldapAttributesForGroupSearch  |                                                                                                                  |
| ldapAttributesForUserSearch   | sn;givenname                                                                                                     |
| ldapBackupHost                |                                                                                                                  |
| ldapBackupPort                |                                                                                                                  |
| ldapBase                      | ***REMOVED SENSITIVE VALUE***                                                                            |
| ldapBaseGroups                | ou=Klassen,ou=Verteiler,***REMOVED SENSITIVE VALUE*** |
| ldapBaseUsers                 | ou=Benutzer,***REMOVED SENSITIVE VALUE***                                                                |
| ldapCacheTTL                  | 600                                                                                                              |
| ldapConfigurationActive       | 1                                                                                                                |
| ldapDefaultPPolicyDN          |                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                  |
| ldapEmailAttribute            | mailLocalAddress                                                                                                 |
| ldapExperiencedAdmin          | 0                                                                                                                |
| ldapExpertUUIDGroupAttr       |                                                                                                                  |
| ldapExpertUUIDUserAttr        |                                                                                                                  |
| ldapExpertUsernameAttr        |                                                                                                                  |
| ldapGidNumber                 | gidNumber                                                                                                        |
| ldapGroupDisplayName          | cn                                                                                                               |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))                                                                                   |
| ldapGroupFilterGroups         |                                                                                                                  |
| ldapGroupFilterMode           | 0                                                                                                                |
| ldapGroupFilterObjectclass    | posixGroup                                                                                                       |
| ldapGroupMemberAssocAttr      | memberUid                                                                                                        |
| ldapHost                      | localhost                                                                                                        |
| ldapIgnoreNamingRules         |                                                                                                                  |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid))                                                                      |
| ldapLoginFilterAttributes     |                                                                                                                  |
| ldapLoginFilterEmail          | 0                                                                                                                |
| ldapLoginFilterMode           | 0                                                                                                                |
| ldapLoginFilterUsername       | 1                                                                                                                |
| ldapNestedGroups              | 0                                                                                                                |
| ldapOverrideMainServer        | 0                                                                                                                |
| ldapPagingSize                | 500                                                                                                              |
| ldapPort                      | 389                                                                                                              |
| ldapQuotaAttribute            | ownCloudQuota                                                                                                    |
| ldapQuotaDefault              | 209715200                                                                                                        |
| ldapTLS                       | 0                                                                                                                |
| ldapUserDisplayName           | displayname                                                                                                      |
| ldapUserDisplayName2          |                                                                                                                  |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                                                   |
| ldapUserFilterGroups          |                                                                                                                  |
| ldapUserFilterMode            | 1                                                                                                                |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                                             |
| ldapUuidUserAttribute         | auto                                                                                                             |
| turnOffCertCheck              | 0                                                                                                                |
| turnOnPasswordChange          | 0                                                                                                                |
| useMemberOfToDetectMembership | 0                                                                                                                |
+-------------------------------+------------------------------------------------------------------------------------------------------------------+

</details>

### PR DESCRIPTION
**Pull request by blizzz**
fixes #9112 (and refs #5212)

Test is: 
1. Have LDAP enabled and configured
2. Ensure User A and B show up on users page
3. As User A (or admin, does not matter), look up User B in the contacts menu on the upper right
4. Change the displayName of User B in LDAP
5. Log in as User B to ensure the displayname is fetched from LDAP and updated
6. Again as User A look up User B again. 

Now the new displayname should be presented, previously it did not.

@nextcloud/ldap

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by blizzz** [comment]
Causes `Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Message":"An exception occurred while executing 'INSERT INTO \"oc_accounts\"` on the integratiion test, just … how and why? Cannot reproduce it locally.

**Comment by blizzz** [comment]
should do now

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
CI is not happy

**Comment by blizzz** [comment]
Indeed, I missed to adjust the tests with the last commit.

**Pull request merged**
