### PR TITLE
Add JS unit test execution

### PR DESCRIPTION
**Pull request by LukasReschke**
Let's see… :see_no_evil:

### CODE REVIEW

**Comment by LukasReschke** [comment]
Okay. @MorrisJobke needs to adjust the Docker 😉

**Comment by LEDfan** [comment]
I locally played a bit with it (using the Drone CLI (http://readme.drone.io/devs/cli/#local-testing:b659b046131d4024ab5e2d3675716bf0) and I think this Dockerfile should work:
````
FROM debian
RUN apt-get update && apt-get install -y php5-intl php5-gd git curl \
	php5-cli php5-curl php5-imagick php5-pgsql php5-mcrypt php5-ldap \
	php5-apcu php5-redis php5-sqlite nodejs npm
RUN ln -s /usr/bin/nodejs /usr/bin/node # https://github.com/Medium/phantomjs/issues/157
ENV PHANTOMJS_BIN ./build/node_modules/phantomjs/bin/phantomjs
RUN php5enmod zip intl gd
RUN curl -O -L https://phar.phpunit.de/phpunit-4.8.24.phar \
	&& chmod +x phpunit-4.8.24.phar \
	&& mv phpunit-4.8.24.phar /usr/local/bin/phpunit

ADD nextcloud.ini /usr/local/etc/php/conf.d/nextcloud.ini
````
It only needs to install node en sets some paths correctly.

**Comment by MorrisJobke** [comment]
> It only needs to install node en sets some paths correctly.

Awesome :) I will try it :)

**Comment by MorrisJobke** [comment]
I always get following error, where the execution then stucks:

```
WARN [plugin]: Error during loading "/drone/src/build/node_modules/karma-phantomjs-launcher" plugin:
  Cannot find module 'phantomjs-prebuilt'
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?
```

**Comment by LEDfan** [comment]
Mm. Looks like the NPM module `phantomjs-prebuilt` must be installed.

**Comment by MorrisJobke** [comment]
> Mm. Looks like the NPM module phantomjs-prebuilt must be installed.

I'm already on it :)

**Comment by MorrisJobke** [comment]
```
PhantomJS 2.1.1 (Linux 0.0.0): Executed 799 of 802 (skipped 3) SUCCESS (11.328 secs / 11.015 secs)
```

\o/

**Comment by MorrisJobke** [comment]
LGTM

**Comment by blizzz** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Let me port this to stable9 :)

**Pull request merged**
