### PR TITLE
 Fix open_basedir issues by AWS SDK

### PR DESCRIPTION
**Pull request by jasperweyne**
This PR sets the 'use_aws_shared_config_files' option to false in the S3ConnectionTrait, in order to disable configuration loading from ~/.aws/config by the AWS SDK. It is a continuation of #27040, as that PR only changed the behaviour of the CredentialsProvider; this change affects the ConfigurationProvider as well, fully disabling any access to ~/.aws/config and solving all open_basedir issues. It intends to solve the issues stated in #23555.

### CODE REVIEW

**Comment by kesselb** [comment]
Some of the integrations tests are also failing on master. Should be safe to ignore it.

**Review by juliusknorr — APPROVED** [review]
Makes sense. Failing test definitely seems unrelated 👍

**Comment by jasperweyne** [comment]
@juliushaertl Thanks for the review! I see that you've added the Nextcloud 25 milestone, I assume this is standard for a PR to master? In any case, I'd like to note that this fix would be applicable to versions 22-24 as well and shouldn't introduce any merge conflicts, as the relevant portion of code hasn't changed since (looking at the stable22 branch).

**Comment by jasperweyne** [comment]
@icewind1991 If you have any feedback, I'd love to hear it!

**Comment by jasperweyne** [comment]
Hi @icewind1991 do you perhaps have a chance to review this? I'd like to avoid this PR becoming stale. If there's anything I can do to help, please let me know!

**Comment by jasperweyne** [comment]
Hi @CarlSchwan , you've assigned the reviewers for this PR, but unfortunately @icewind1991 's review has been left open for more than two months now. I'm assuming he's unavailable to review this, can you perhaps assign another reviewer?

**Review by PVince81 — APPROVED** [review]
:+1: makes sense

**Review by icewind1991 — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]
Ci failure unrelated

**Pull request merged**
