### PR TITLE
fix(SharingEntryLink): Show default password before create if any

### LINKED ISSUE #41373: [Bug]: GUI of Sharing Tab > heading for Password and Checkbox are missing (at least in German GUI)
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If you have activated the option „always ask for sharing password“ and then add an external link the attached dialog is displayed. Here nothing about a password is told which leads to errors – though the functionality is here. It’s just about the dialog.

### Steps to reproduce

1. Activate „always ask for sharing password“ in …/index.php/settings/admin/sharing
2. Add an external link in files app.
3. see screenshot
Bildschirmfoto 2023-11-10 um 11 32 42

### Expected behavior

I would expect two things:
1. heading „Password“
2. Checkbox to add a link without a password.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trusted_domains": [
            "nc.irex.uni-tuebingen.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "overwrite.cli.url": "https:\/\/nc.irex.uni-tuebingen.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "emlviewer",
            "extract",
            "transmission"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "skeletondirectory": "",
        "auth.webauthn.enabled": "false",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "21b8cb97ed73b8ebc1d6b9820ffd7b8b"
    }
}
```

### List of activated Apps

```shell
- activity: 2.19.0
  - admin_audit: 1.17.0
  - analytics: 4.11.0
  - approval: 1.1.0
  - auto_groups: 1.5.2
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.3
  - calendar_resource_management: 0.5.0
  - call_summary_bot: 1.0.0
  - cfg_share_links: 4.2.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - collectives: 2.9.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - emlviewer: 1.0.8
  - external: 5.2.1
  - extract: 1.3.6
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_automatedtagging: 1.17.0
  - files_linkeditor: 1.1.16
  - files_lock: 27.0.2
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - files_zip: 1.4.0
  - firstrunwizard: 2.16.0
  - forms: 3.3.1
  - groupfolders: 15.3.1
  - impersonate: 1.14.0
  - integration_openstreetmap: 1.0.6
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.4
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - polls: 5.4.1
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quickaccesssorting: 3.0.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.2
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.11.0
  - sketch_picker: 1.0.1
  - spreed: 17.1.2
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_admin: 4.3.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_email: 2.7.4
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_migration: 4.0.1
  - user_status: 1.7.0
  - users_picker: 0.2.2
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - welcome: 1.0.10
  - workflow_kitinerary: 1.3.0
  - workflow_pdf_converter: 1.12.0
  - workflowengine: 2.9.0
Disabled:
  - assistant: 1.0.1 (installed 1.0.1)
  - contactsinteraction: 1.8.0 (installed 1.8.0)
  - encryption: 2.15.0 (installed 2.15.0)
  - files_archive: 1.1.3 (installed 1.1.3)
  - files_external: 1.19.0
  - integration_openai: 1.0.13 (installed 1.0.13)
  - picker: 1.0.7 (installed 1.0.7)
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
—
```

### Additional info

OS: Linux 5.14.0-284.30.1.el9_2.x86_64 x86_64

### LINKED ISSUE #44220: [Bug]: Missing hint of default expiration date on link shares
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When in the settings a value for "Set default expiry date" is set and "Enforce expiry date" unchecked, there is no hint at creating a link share that an expiration date will be set.
The user thinks that the link share will be valid forever but when clicking on "Customize link" he sees that a expiration date was set automatically.
grafik

### Steps to reproduce

1. Configure the Sharing settings like this
    - [x] Allow users to share via link and emails
    - [x] Allow public uploads
    - [x] Always ask for a password
    - [x] Enforce password protection
    - [x] Set default expiry date -> Expire after 30 day(s)
    - [ ] Enforce expiry date
2. Create a link share.
3. Click on "Customize link" and see that there was set an expiration date.

### Expected behavior

It should be like when the option "Enforce expiry date" is enabled, that the user sees in the pop-up when creating the link share that an expiration date is set.
He should be able to change the date or completely uncheck the option.
grafik

Or at least a notice should be displayed that an expiry date is set and that it can then be adjusted afterwards.

### Nextcloud Server version

27.1.7 28.0.3

### LINKED ISSUE #48860: [Bug]: Show default expiration date on public share link creation
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A default 7-day expiration is set for shares, but many users don’t notice it when creating shares. This leads to issues when shares expire, especially if the link was shared widely.

### Steps to reproduce

1. Create a public share link.
2. Default expiration date is not shown in the share creation dialog.

 Image

### Expected behavior

Default expiration date should be shown in the share creation dialog.

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
   "instanceid": "***REMOVED SENSITIVE VALUE***",
   "passwordsalt": "***REMOVED SENSITIVE VALUE***",
   "secret": "***REMOVED SENSITIVE VALUE***",
   "trusted_domains": [
   ],
   "datadirectory": "***REMOVED SENSITIVE VALUE***",
   "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
   "dbtype": "mysql",
   "version": "28.0.10.2",
   "dbname": "***REMOVED SENSITIVE VALUE***",
   "dbhost": "***REMOVED SENSITIVE VALUE***",
   "dbtableprefix": "oc_",
   "dbuser": "***REMOVED SENSITIVE VALUE***",
   "dbpassword": "***REMOVED SENSITIVE VALUE***",
   "logtimezone": "Europe\/Berlin",
   "loglevel": 2,
   "log_authfailip": true,
   "log_rotate_size": 104857600,
   "installed": true,
   "memcache.local": "\\OC\\Memcache\\APCu",
   "mail_smtpmode": "smtp",
   "mail_from_address": "***REMOVED SENSITIVE VALUE***",
   "mail_domain": "***REMOVED SENSITIVE VALUE***",
   "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
   "mail_smtpport": "25",
   "force_language": "de_DE",
   "skeletondirectory": "",
   "singleuser": false,
   "maintenance": false,
   "updatechecker": false,
   "trashbin_retention_obligation": "30, 40",
   "htaccess.RewriteBase": "\/",
   "memcache.locking": "\\OC\\Memcache\\Redis",
   "redis": {
       "host": "***REMOVED SENSITIVE VALUE***",
       "port": 0
   },
   "updater.release.channel": "enterprise",
   "simpleSignUpLink.shown": false,
   "sort_groups_by_name": true,
   "mail_sendmailmode": "smtp",
   "theme": "",
   "defaultapp": "files",
   "mysql.utf8mb4": true,
   "default_phone_region": "DE",
   "maintenance_window_start": 2,
   "preview_max_memory": 256,
   "profile.enabled": false,
   "mail_template_class": "OCA\\EmailTemplateTLRZ\\EMailTemplate",
   "default_language": "de_DE",
   "memcache.distributed": "\\OC\\Memcache\\Redis",
   "htaccess.IgnoreFrontController": true,
   "updater.server.url": "***REMOVED SENSITIVE VALUE***",
   "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
}

### List of activated Apps

Enabled:
- activity: 2.20.0
- announcementcenter: 7.0.0
- bruteforcesettings: 2.8.0
- calendar: 4.7.16
- circles: 28.0.0
- cloud_federation_api: 1.11.0
- collectives: 2.14.4
- comments: 1.18.0
- contacts: 5.5.3
- contactsinteraction: 1.9.0
- dashboard: 7.8.0
- dav: 1.29.2
- deck: 1.12.5
- email_template_tlrz: 1.0.1
- external: 5.3.1
- federatedfilesharing: 1.18.0
- federation: 1.18.0
- files: 2.0.0
- files_antivirus: 5.5.7
- files_pdfviewer: 2.9.0
- files_reminders: 1.1.0
- files_sharing: 1.20.0
- files_trashbin: 1.18.0
- files_versions: 1.21.0
- forms: 4.2.4
- logreader: 2.13.0
- lookup_server_connector: 1.16.0
- nextcloud_announcements: 1.17.0
- notifications: 2.16.0
- oauth2: 1.16.4
- password_policy: 1.18.0
- photos: 2.4.0
- provisioning_api: 1.18.0
- recommendations: 2.0.0
- related_resources: 1.3.0
- richdocuments: 8.3.11
- security_guard: 1.2.1
- serverinfo: 1.18.0
- settings: 1.10.1
- sharebymail: 1.18.0
- spreed: 18.0.11
- support: 1.11.1
- survey_client: 1.16.0
- systemtags: 1.18.0
- tasks: 0.16.1
- text: 3.9.2
- theming: 2.3.0
- twofactor_backupcodes: 1.17.0
- twofactor_totp: 10.0.0-beta.2
- updatenotification: 1.18.0
- user_status: 1.8.1
- user_usage_report: 1.12.1
- viewer: 2.2.0
- weather_status: 1.8.0
- workflowengine: 2.10.0

Disabled:
- admin_audit: 1.18.0
- encryption
- files_confidential
- files_external
- files_lock
- firstrunwizard: 1.1
- globalsiteselector
- privacy: 1.1.0
- suspicious_login
- user_ldap
- user_saml

### Nextcloud Signing status

* SIP dialin is disabled
* SIP dialout is disabled

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
Prevent silent addition of expiration date to shares.

Resolves : https://github.com/nextcloud/server/issues/48860

# Screenshots

| No default expiration set | Expiration enforced | Default expiration set BUT not enforced |
| -- | -- | -- |
| Screenshot from 2024-11-07 06-25-03 | Screenshot from 2024-11-07 06-19-48 | Screenshot from 2024-11-07 06-18-49 |

### CODE REVIEW

**Comment by joshtrichards** [comment]
Looks good!

Related: #46837 (not sure if this fixes that too)

**Review by susnux — APPROVED** [review]

**Comment by nfebe** [comment]
> Related: https://github.com/nextcloud/server/issues/46837 (not sure if this fixes that too)

Not exactly might require a separate PR. Took it.

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
```
VM1567 core-common.js:150691 [Vue warn]: Error in mounted hook: "TypeError: Cannot set properties of null (setting 'expireDate')"

found in

---> <SharingEntryLink> at apps/files_sharing/src/components/SharingEntryLink.vue
       <SharingLinkList> at apps/files_sharing/src/views/SharingLinkList.vue
         <SharingTab> at apps/files_sharing/src/views/SharingTab.vue
           <NcAppSidebarTab>
             <SidebarTab> at apps/files/src/components/SidebarTab.vue
               <NcAppSidebarTabs>
                 <NcAppSidebar>
                   <Root>
```

**Comment by skjnldsv** [comment]
Will fix

**Comment by DanScharon** [comment]
the backport to stable29 has not made the cut, correct? Can you retry backporting please?

**Pull request merged**
