### PR TITLE
Deprecate OC router helpers that are provided by packages

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
This also fixes https://github.com/orgs/nextcloud/projects/31#card-21153825

**Review by juliusknorr — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
yeeehaaa!

**Comment by rullzer** [comment]
jsunit says no

**Comment by ChristophWurst** [comment]
> jsunit says no

Whoopsie broke something while cleaning up the code before the push. Fixed.

**Pull request merged**
