### PR TITLE
Sessions fixes

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixes a bunch of things in the Sessions view in the personal settings (Security), including accessibility and this unnecessary tooltip:
delete tooltip for revoking devices

And this duplication of text in the tooltip:
device tooltips

Now looks like this:
sessions now

### CODE REVIEW

**Comment by rullzer** [comment]
Would it be possible to break this down into small commits that we can get in quickly?

**Comment by jancborchardt** [comment]
> Would it be possible to break this down into small commits that we can get in quickly?

@rullzer are you being sarcastic? ;D I mean really, it is very broken down, no? Or do you want me to squash something? Or do you mean "broken down into small PRs"?

**Comment by rullzer** [comment]
@jancborchardt I meant small PRs. I'm on a quest to get out PR count down. So ideally we can merge small fixes very quickly.

I know how it is when you start working on something... ooo and then I need to fix this as well. And this doesn't look right etc. And especially so close to the freeze I rather have everything in that we can ;)

So no sarcasm :)

**Comment by jancborchardt** [comment]
We could also simply merge it at this stage. The keyboard enter-functionality could be done in a follow-up PR, but there’s nothing half-done here really. :)

**Comment by jancborchardt** [comment]
Opened a separate issue for the keyboard enter accessibility at https://github.com/nextcloud/server/issues/12243

This is ready to review @nextcloud/designers :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]

**Pull request merged**
