### PR TITLE
Fix : Hides hidden files an folder in grid view

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

## Summary

Hides hidden files an folder in grid view (replace calls to ".hidden" by ".hidden-file" class)

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — COMMENTED** [review]
I wonder wasnt this fixed with https://github.com/nextcloud/server/pull/37269?

**Comment by Jerome-Herbinet** [comment]
> I wonder wasnt this fixed with #37269?

@szaimen I use NC 25.0.5 and the problem still occurs. So, https://github.com/nextcloud/server/pull/37269 and/or https://github.com/nextcloud/server/pull/37287 don't solve the issue in the case I describe, or it's not solving the same problem.

**Comment by szaimen** [comment]
> @szaimen I use NC 25.0.5 and the problem still occurs. So, #37269 and/or #37287 don't solve the issue in the case I describe, or it's not solving the same problem.

Did you already try to clear the browser cache?

**Comment by Jerome-Herbinet** [comment]
> > @szaimen I use NC 25.0.5 and the problem still occurs. So, #37269 and/or #37287 don't solve the issue in the case I describe, or it's not solving the same problem.
> 
> Did you already try to clear the browser cache?

Yes I did.

**Comment by szaimen** [comment]
> Yes I did.

Apparently https://github.com/nextcloud/server/pull/37287 will be included in 25.0.6: https://github.com/nextcloud/server/pull/37287

**Comment by Jerome-Herbinet** [comment]
OK, do I close this PR now, or do we wait for NC 25.0.6 to do it ? (after checking front-end behaviour) ?

**Comment by szaimen** [comment]
I'd wait for 25.0.6 and 26.0.1 first

**Comment by skjnldsv** [comment]
Fixed with 28 and above

**Pull request closed without merging**
