### PR TITLE
Ie11 grid fixes

### LINKED ISSUE #12034: IE11 not compatible with grid view
@nextcloud/designers @jancborchardt

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #12034 

@nextcloud/designers IE11 does not have a grid auto positionning.
That means we need to pre-compile every case possible for a specific numbers of scenario.
This is what this algorithm do. Nonetheless there is a finite amount of files we can support. I set the limit to 1000 files. Anything above will generate display issues on the grid. But I'm pretty sure anything above will anyway crash internet explorer ^^

Thoughts?

For the record: Not fan of this solution. And flex is not working fine here as well.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Especially with all the possible breakage and workaround you mentioned, I’m inclined to stand by what I said at https://github.com/nextcloud/server/issues/12034#issuecomment-433094896

> Simple fix would be to simply have list view as default for IE11 and not showing the grid view toggle.

Especially cause you say:

> Nonetheless there is a finite amount of files we can support. I set the limit to 1000 files. Anything above will generate display issues on the grid. But I'm pretty sure anything above will anyway crash internet explorer ^^

We should be very wary of slipping down an IE11-fixing slope cause yeah, these edge-cases (and more) will probably appear. :\

What do you think @MorrisJobke @rullzer @karlitschek? Worth it or not?

**Comment by MorrisJobke** [comment]
> What do you think @MorrisJobke @rullzer @karlitschek? Worth it or not?

I'm totally fine with disallow the grid in IE11. It's still usable. For better experience use a newer browser.

**Comment by karlitschek** [comment]
In general we should always avoid it to have different user experiences/features on different platforms, Operating Systems, Browsers, ... But in this case it is O.K. I think. Let's see if people complain ;-)

**Comment by MorrisJobke** [comment]
> In general we should always avoid it to have different user experiences/features on different platforms, Operating Systems, Browsers, ... But in this case it is O.K. I think. Let's see if people complain ;-)

True ... maybe also show the toggle and just give a hint for IE11 to not hide it too much and give proper user feedback. On the other side just hiding it is maybe better. 🤔

**Comment by jancborchardt** [comment]
@MorrisJobke just hiding it is better. What was never there will not be missed. But if we say "hey there's grid view and you can't have it" it's shitty UX – no matter if the reason is the browser.

**Pull request closed without merging**
