### PR TITLE
Fix the syntax of the federation ID share buttons

### PR DESCRIPTION
**Pull request by nickvergessen**
There is also another problem with the gnu button: `div` is not allowed inside `p`.

But I can't fix this.

### CODE REVIEW

**Comment by LukasReschke** [comment]
LGTM

**Comment by LukasReschke** [comment]
cc @ChristophWurst @jancborchardt Please review.

**Comment by jancborchardt** [comment]
Yeah, good reordering :+1:

**Comment by nickvergessen** [comment]
Should backport the syntax fix to 10, the reordering as well? @jancborchardt

**Comment by jancborchardt** [comment]
Nah, just backport the fix there.

**Pull request merged**
