### PR TITLE
Allow adding array content directly in export interface

### PR DESCRIPTION
**Pull request by Pytal**
For ease of testing

Implemented in https://github.com/nextcloud/user_migration/pull/196

### CODE REVIEW

**Comment by CarlSchwan** [comment]
this is an api break, but probably not an issue if user_migration has a branch per major NC version

**Comment by Pytal** [comment]
> this is an api break, but probably not an issue if user_migration has a branch per major NC version

It does, think this should only be in 25 and up then? Or would it be safe to backport to 24?

**Comment by come-nc** [comment]
This change is weird, and loosen the typing of the variable.
The export interface should not impose json encoding.

If you really need it it should be an other method like addFileContentsJsonArray, but it does not feel right to me to add these kind of things in there.
Maybe instead add (static?) methods for json encoding/decoding that takes care of passing the usual flags and throw on errors, so that they can be encapsulated directly in calls to addFileContents?

**Comment by Pytal** [comment]
> Maybe instead add (static?) methods for json encoding/decoding that takes care of passing the usual flags and throw on errors, so that they can be encapsulated directly in calls to addFileContents?

Not sure I get it, could you elaborate?

**Comment by come-nc** [comment]
The current way of doing things is:
`$exportDestination->addFileContents($path, json_encode($array));`

I’m trying to understand what you want to avoid by adding a method that does the json encoding. The only difference I see in your implementation is that it throws on error so I was thinking you could add a method for this to be able to do:
`$exportDestination->addFileContents($path, $exportDestination->jsonEncode($array));`

But this is actually not needed since there already is a flag you can use on json_encode for throwing on error, so:
`$exportDestination->addFileContents($path, json_encode($array, JSON_THROW_ON_ERROR));`
Should do what you want.

**Comment by Pytal** [comment]
This was done so that in tests like https://github.com/nextcloud/server/pull/33177/files#diff-d0b73cdb13ad70e10a605cc3361b879e3b7f314c58b7beb2c1835974d72733beR167 equality could be checked directly on the associative array instead of on the stringified json, without this the string equality check would fail because associative array keys are not necessarily in the same order @come-nc

**Comment by come-nc** [comment]
> This was done so that in tests like https://github.com/nextcloud/server/pull/33177/files#diff-d0b73cdb13ad70e10a605cc3361b879e3b7f314c58b7beb2c1835974d72733beR167 equality could be checked directly on the associative array instead of on the stringified json, without this the string equality check would fail because associative array keys are not necessarily in the same order @come-nc
> 
> Any suggestions welcome :)

https://phpunit.readthedocs.io/en/9.5/assertions.html#assertjsonstringequalsjsonstring ?
There is also a contraint class you can use with expects I think: https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/Constraint/JsonMatches.php

**Comment by Pytal** [comment]
Closing in favour of using the existing `JsonMatches` constraint directly

**Pull request closed without merging**
