### PR TITLE
Pass old value to user triggerChange hook & do not update unchanged attributes

### PR DESCRIPTION
**Pull request by MorrisJobke**
Part of #14967 and #14566 that only passes the additional value for the old value of the attribute.

Also includes that some attributes should not be updated if their value hasn't changed.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Okay - this is already causing the issue. Let's shrink it down furthermore.

**Comment by MorrisJobke** [comment]
This is ready to be reviewed. It contains two commits:

* one to only pass oldvalue to the change event
* one that modifies the code to only change the attribute if the value actually has changed

**Review by ChristophWurst — APPROVED** [review]
Code looks good and change makes sense :+1:

**Review by rullzer — APPROVED** [review]
If CI is happy I'm fine with this

**Pull request merged**
