### PR TITLE
Techdebt/noid/dedicated method to get a users language

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x]  Based on https://github.com/nextcloud/server/pull/21535
- [x] Added a dedicated method in the factory to get the language of another user
- [x] Make sure all other places use the new method

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
code looks good.
didn't test. But I can see the bug this solves.

**Comment by blizzz** [comment]
Mh, what about making the LanguageIterator accepting null-users and just returning it's first value?

**Comment by nickvergessen** [comment]
I guess it also should take an appid then as that could influence the result too.
But yeah this was just a end of workday push, i will continue tomorrow.

Also i never saw this iterator before and parta of the fix need backporting till 17 :/

**Comment by blizzz** [comment]
> I guess it also should take an appid then as that could influence the result too.
> But yeah this was just a end of workday push, i will continue tomorrow.

Yeah, could be integrated right away, too.

> Also i never saw this iterator before and parta of the fix need backporting till 17 :/

I added it for the what's new thing. Haven't seen that anyone picked it up, but it was also rather a corner case.

**Comment by nickvergessen** [comment]
Now based on https://github.com/nextcloud/server/pull/21535 which is backportable easily
And using the new method everywhere.

I'm not sure about the iterator usage, especially as it falls back to the current user and therefor e.g. always sends share related emails in the sharers language instead of default for guests.

**Review by blizzz — APPROVED** [review]

**Comment by rullzer** [comment]
CI does not agree https://drone.nextcloud.com/nextcloud/server/30037/10/4

**Comment by rullzer** [comment]
CI still says no

**Comment by nickvergessen** [comment]
Fixed

**Comment by nickvergessen** [comment]
Docs at https://github.com/nextcloud/documentation/pull/9309

**Pull request merged**
