### PR TITLE
Move svg api endpoint

### LINKED ISSUE #11179: Safari shows high CPU load
### Steps to reproduce
1. Login to Nextcloud
2. Wait

### Expected behaviour
Safari is in idle mode when nothing happens

### Actual behaviour
Safari on macOS 10.13.6 shows high CPU load

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache2

**Database:** MariaSQL

**PHP version:** 7.2

**Nextcloud version:** 14.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Web-Updater

**List of activated apps:**
Shouldn't be the problem

**Are you using external storage, if yes which one:** local, smb

**Are you using encryption:** no

### Client configuration
**Browser:** Safari

**Operating system:** macOS 10.13.6

#### Web server error log

No log. I do nothing. Only being logged in.

#### Browser log

I see some lines like this:
```
[324 <private> stream, pid: 33527, url: https://my.nextcloud.domain/ocs/v2.php/apps/notifications/api/v2/notifications, tls] cancelled
	[324.1 BB809A76-3379-4FC8-BE86-F7F9DC8C4630 <private>.50637<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 6.359s, DNS @0.000s took 0.010s, TCP @0.013s took 0.011s, TLS took 0.005s
	bytes in/out: 866/1404, packets in/out: 8/8, rtt: 0.010s, retransmitted packets: 0, out-of-order packets: 0
```

bildschirmfoto 2018-09-11 um 21 58 18

### PR DESCRIPTION
**Pull request by skjnldsv**
~~Fix #11179~~

@MorrisJobke with this pr, could you try and tell me if this is also the search svg that break on your side?

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Does not solve the issue. But if I click on the search icon -> inspect and delete the node the re-rendering stops (156,5s):

bildschirmfoto 2018-10-24 um 18 47 04

**Comment by skjnldsv** [comment]
Actually, without fixing the safari issue, this is a great addition! LGTI

**Comment by juliushaertl** [comment]
Needs some adjustments on the icon inlining, I'll have a look.

**Comment by juliushaertl** [comment]
I fixed the icon cacher matching as well as the color replacement in the accessibility app. Ready for review.

**Review by rullzer — APPROVED** [review]
quick :smoking:-test looks good.

**Comment by skjnldsv** [comment]
@juliushaertl do you approve your own work? :D

**Comment by skjnldsv** [comment]
`sh: 1: kill: No such process
`

**Review by juliusknorr — APPROVED** [review]
> @juliushaertl do you approve your own work? :D

Sure, fine by me :wink:

**Pull request merged**
