### PR TITLE
flicker-free permission change in share dialog

### PR DESCRIPTION
**Pull request by blizzz**
When a permission is changed, the sharing sidebar was re-rendered, causing flickering with the Avatars. #2368 

This PR only updates the permissions of the changed sharee.

Things left to do:

* [x] "can edit" is not updated
* [x] race condition unsafe

### CODE REVIEW

**Comment by blizzz** [comment]
To avoid race conditions in a user friendly way, UI work is needed. For instance by showing a spinner on the permissions related input elements of the share and/or disabling these elements. Essentially it is the "can-edit" checkbox and the contents of the pop over menu. Replacing any checkbox with a spinner is too much, putting an spinner of the whole row would hide-and-show the popover menu again, thus too noisy. Additional safety can be reached by locking down the model, but it isn't really necessary.

Perhaps the better approach is to only show a spinner on the specific permission and implement the PATCH request on client (model) and server side.

**Comment by blizzz** [comment]
I went for dis- and enabling check boxes during save.

@schiessle @nickvergessen @ChristophWurst @rullzer ready for review

**Review by schiessle — CHANGES_REQUESTED** [review]
works great for user and group shares but not for mail shares of a folder

**Comment by blizzz** [comment]
> works great for user and group shares but not for mail shares of a folder

Do you mean changing "can edit" for mail shares (of a folder)? That does not even work with master.

**Comment by blizzz** [comment]
@schiessle see https://github.com/nextcloud/server/pull/2398#issuecomment-265129906

**Comment by schiessle** [comment]
:+1: for this one

**Review by schiessle — APPROVED** [review]

**Comment by blizzz** [comment]
mah, that rebasing did not turn out that well

**Comment by blizzz** [comment]
@schiessle another fix for the selector (cf. https://github.com/jquery/learn.jquery.com/pull/737) and this should work fine for mail shares now as well.

**Comment by schiessle** [comment]
tested once more... works great! 👍

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
