### PR TITLE
Check connection status and attempt to reconnect each each minute

### PR DESCRIPTION
**Pull request by icewind1991**
An attempt to prevent "mysql has gone away" errors when there is a long time between database requests

### CODE REVIEW

**Comment by rullzer** [comment]
How will this work with transactions?

**Comment by icewind1991** [comment]
It explicitly doesn't do anything while in a transaction since there is no way to resume a transaction or do any other kind of automated safe recovery.

**Review by rullzer — APPROVED** [review]
Simple enough and makes sense to me.

Lets give it a try!

**Review by ChristophWurst — APPROVED** [review]
Change is fine by me, code looks good :+1:

**Pull request merged**
