### PR TITLE
Fix replacing external storage password during debug log

### PR DESCRIPTION
**Pull request by ChristophWurst**
This is untested and unverified. Apparently the logging replaces the password.

Ref https://github.com/nextcloud/server/issues/32598#issuecomment-1143269327

Fixes https://github.com/nextcloud/server/issues/32598

Regression of https://github.com/nextcloud/server/pull/31826

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by phreaker0** [comment]
i applied this patch after the 22.2.7 -> 22.2.8 upgrade, and login works again for me

**Comment by ChristophWurst** [comment]
:ping_pong: for reviews

We have one approval already and confirmation that this works in production :shipit:

**Review by miaulalala — APPROVED** [review]

**Comment by blizzz** [comment]
Good for a quick fix as it deals with the symptoms. Alas, this will pop up again in future, if it is not taken care of fundamentally.

**Pull request merged**
