### PR TITLE
Added kinetic scrolling for iOS to apps dropdown menu

### PR DESCRIPTION
**Pull request by kevin147147**
this is tested with nc14

### CODE REVIEW

**Comment by kevin147147** [comment]
#10281

**Comment by ChristophWurst** [comment]
Btw, nice pull request id :wink:

**Comment by skjnldsv** [comment]
@kevin147147 I thought we already checked on the last pr and the kinetic scroll was already by default on the apple browsers? :thinking:

**Comment by kevin147147** [comment]
Kinetic scroll is always opt in as far as i know

**Comment by skjnldsv** [comment]
Great addition for ios yes :)

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
@kevin147147 You need to sign your commit for the tests to pass :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works nicely 👍

**Review by rullzer — APPROVED** [review]
saw it working @MorrisJobke

**Pull request merged**
