### PR TITLE
allow apps to set custom mount types

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
sure... but why?

**Comment by icewind1991** [comment]
Show I can show fancy folder icons in the web ui

folders

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Allll righty then!

**Review by MorrisJobke — APPROVED** [review]
👍  (I fixed the PHPDoc @since tag 😉 )

**Comment by MorrisJobke** [comment]
JSUnit fails:

```
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Files.FileList tests file previews does not render preview for directories FAILED
100s
910
	Expected 'http://localhost/core/img/filetypes/file.svg' to equal 'http://localhost/core/img/filetypes/folder.svg'.
100s
911
	apps/files/tests/js/filelistSpec.js:1328:67
```

**Comment by rullzer** [comment]
Fixed the js part

**Pull request merged**
