### PR TITLE
Bump the Symfony family from 4.4.15 to 4.4.18

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] https://github.com/nextcloud/3rdparty/pull/569
- [x] rebase

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Bildschirmfoto von 2020-12-29 16-43-43

one single failure. unrelated?

**Comment by ChristophWurst** [comment]
Drone restarted :crossed_fingers: :crossed_fingers: :crossed_fingers:

**Comment by geep33** [comment]
No weno

**Comment by ChristophWurst** [comment]
The same sharing test fails in other PRs https://github.com/nextcloud/server/pull/24890#issuecomment-752157514

**Comment by ChristophWurst** [comment]
CI fails because of https://github.com/nextcloud/notifications/pull/824

**Pull request merged**
