### PR TITLE
Migrate to @nextcloud/vue 1.x.x

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Comment by skjnldsv** [comment]
This is ready to review :)
I migrated apps and users, please have a look!

@nextcloud/vuejs everyone who coded in server, please check your code, that would help cleaning this up!

**Review by ChristophWurst — APPROVED** [review]
PR of the day

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
