### PR TITLE
Remove appmenu limit

### PR DESCRIPTION
**Pull request by patschi**
Will remove the appmenu limit as discussed in #5121.

### CODE REVIEW

**Comment by MariusBluem** [comment]
**Screenshot:**
bildschirmfoto 2017-05-27 um 20 05 51

**Review by MariusBluem — APPROVED** [review]
I think thats OK 👍

**Comment by MariusBluem** [comment]
Please review @nextcloud/designers

**Review by ChristophWurst — APPROVED** [review]
LGTM

**Comment by jancborchardt** [comment]
Yup, good point, good change. :+1: :) Now that we have the dynamic sizing always it’s good to also use the space dynamically.

**Comment by juliushaertl** [comment]
Should we backport that change? @jancborchardt @karlitschek

**Comment by karlitschek** [comment]
Backport is fine in general. But I would like to request a change. I think it looks bad and super crowded if every available pixel in the header is used. Can we make sure that we have a bit more whitespace between the most right app icon and the search icon?

**Comment by jancborchardt** [comment]
Sounds good @karlitschek. Let’s keep a minimum of 1 icon width space between the rightmost app icon and the search icon.

What do you think @juliushaertl?

**Comment by karlitschek** [comment]
I still think this looks super crowded. What's wrong with some whitespace in the UI? Now we have a web application that is completely filled with buttons. 
Saying all of that it is the decision of the design team. Whatever you guys decide is fine with me.

**Comment by patschi** [comment]
When an user installs quite a lot of apps it may look a bit overloaded:
image

IMO using about 1/3 of the space would be okay:
image

I don't know about the possibilities to manage the appmenu behavior through apps, but someday the appmenu could be managed more flexible using an own app: Ordering the icons, setting the procentual space to use, limit app icons count, hiding specific apps or even overwrite specific app icons, showing up icons only for specific users/groups/devices/resolution, different appmenu settings on different pages, etc.

Until then I'd suggest limiting the icons to 1/3 (or 1/2) of the available space in the navigation. For me the space between each app is fine. The situations were so many apps are installed that it may fill up the whole navigation should be quite rare anyway.

**Comment by jancborchardt** [comment]
Right, trying it out for longer it is way too much, and especially since you don’t have the labels. But even with labels there would be way too much noise.

@juliushaertl @eppfel what do you think? I would actually reduce it down to the 8 limit we had before again. It was a nice balance between showing the most important apps, and not having too many.

**Comment by patschi** [comment]
What about the idea to dynamically set the app limit based on actual window size than on a static limit? On bigger resolutions (QHD, 4k, etc) there is much more space available, so we could use something of that additional space aswell. Showing up to 10-12 apps on a 1920x1080 resolution, more at 4K res, for example. Sadly I don't have any comparisons nor experience with that many different resolutions, or how it may look like on QHD or 4K screens - I'm just having 1080p here.

**Comment by icewind1991** [comment]
>  It was a nice balance between showing the most important apps, and not having too many.

The problem is that we dont show the most important apps, we show a random set of apps

**Comment by eppfel** [comment]
I'm really for the solution @patschi proposed, as the numerical amount is not the actual issue here, but the available space. Using 1/2 the width on desktop, seems to be a good call, as this will show a lot more than 8, but help with the visual distinction between the left and right navigation.

**Comment by jancborchardt** [comment]
Ok, then let's try out that »use half of the width of the header as maximum« approach. @patschi could you open a pull request? :)

**Comment by patschi** [comment]
PR #5244 for percentual appLimit. I've choosen to use 33% for now.

As comparison on a 1080p width resolution:
**33%**
image

**40%**
image

**50%**
image

**Comment by MorrisJobke** [comment]
Keep in mind that it should still work on mobile and small screens. I would love to see this as a max-width setting for bigger screens.

**Comment by jancborchardt** [comment]
Yeah, on a phone the percentage doesn’t fully work. On narrow widths it should work like before. On bigger screens the 33% rule can work.

**Comment by juliushaertl** [comment]
How about using the percentage rule if there is space for more that 8 apps and on smaller screens just show as much as possible with a 2-3x icon-width as space.

**Comment by Espina2** [comment]
Since the first day I am against this approach, and again in just use the icon to identify an app. Like @karlitschek said this interface look chaotic and have too many entries all over the place, actions on the left sidebar on top bar, on the files. 

I know this comment doesn't solve anything but just want to know that I 100% against this solution at first hand.

I keep thinking that Nextcloud is no longer a file sharing software but more like a suite of applications. Like the claim on Homepage "Your Secure Workspace". 

Why not have instead of files on the first screen something that you can choose what do you want to go. (just thinking out loud).

I don't mean to disrespect the work of anybody here, this is are better than it has before.

**Comment by jancborchardt** [comment]
@juliushaertl exactly.


> I keep thinking that Nextcloud is no longer a file sharing software but more like a suite of applications. Like the claim on Homepage "Your Secure Workspace".

@Espina2 That's exactly the case, and that was our goal since very early on.

**Pull request merged**
