### PR TITLE
Read encrypted session data again on reopen

### PR DESCRIPTION
**Pull request by juliusknorr**
This should avoid working with outdated session data after reopening the PHP session

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Good find.

* Together with https://github.com/nextcloud/spreed/pull/8265 that finally solves https://github.com/nextcloud/spreed/issues/4670

**Comment by nickvergessen** [comment]
This actually seems to break the login

**Comment by szaimen** [comment]
And we have some performance regressions

**Comment by szaimen** [comment]
Does this potentially fix https://github.com/nextcloud/server/issues/33919?

**Review by nickvergessen — APPROVED** [review]
Login works again

**Review by blizzz — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Comment by szaimen** [comment]
Does this fix https://github.com/nextcloud/server/issues/33919?

**Comment by juliushaertl** [comment]
Tests are passing again, rebased and squashed

**Comment by juliushaertl** [comment]
> Does this fix https://github.com/nextcloud/server/issues/33919?
> Edit: seems like not

Yes, doesn't seem related to that.

**Comment by juliushaertl** [comment]
Failure unrelated, fix is in #34954

**Comment by skjnldsv** [comment]
This broke viewer.
image

**Comment by skjnldsv** [comment]
Confirmed, reverting the two commits makes cypress pass again.

**Comment by juliushaertl** [comment]
@skjnldsv Can you reproduce that outside of cypress as well? There it seems to work for me. Will try to run the viewer cypress tests and see if I can reproduce that

**Comment by juliushaertl** [comment]
I can reproduce but only when running the cypress test. Seems somehow the `AUTHENTICATED_TO_DAV_BACKEND`attribute is preserved in the session from the previous api call to create the user. Will investigate further:

```
  "cryptSessionData Decrypted: {\"LAST_ACTIVITY\":1667570009,\"requesttoken\":\"y69YQJ4OJ6zWUN2oyFD\\/GXDuPwNVWQGx\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"echitrb1\\\",\\\"loginName\\\":\\\"echitrb1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667570003,\"user_id\":\"echitrb1\",\"loginname\":\"echitrb1\",\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true}}"
```

**Comment by juliushaertl** [comment]
A few debugging insights:
- The cookie is being reused from the previous OCS request to create the user which still has the previous session data contained
- The webdav failure is expected in that case as per https://github.com/owncloud/core/issues/13245
	- https://github.com/nextcloud/server/blob/f7be76125f885d66caac4a8d6697e121dce52708/apps/dav/lib/Connector/Sabre/Auth.php#L87
- Options to mitigate
	- Clear the session in viewer cypress tests
	- Clean the session during login
	- Only clean the relevant fields when detecting invalid authentication (e.g. before redirecting to login)
	- Only clean the relvant fields after login

I'll need to think a bit about what the best approach there would be.


<details>
<summary>Session data after login with a different user</summary>

```json
{
  "LAST_ACTIVITY": 1667572677,
  "requesttoken": "wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh",
  "checkServer_succeeded": true,
  "login_credentials": {
    "run": true,
    "uid": "rzeketu1",
    "loginName": "rzeketu1",
    "password": "password",
    "isTokenLogin": false
  },
  "AUTHENTICATED_TO_DAV_BACKEND": "admin",
  "last-password-confirm": 1667572674,
  "user_id": "rzeketu1",
  "loginname": "rzeketu1",
  "timezone": "1",
  "token_scope": {
    "filesystem": true
  }
}
```
</details>

<details>
<summary>Full list of session write calls for a cypress run</summary>

```
cat data/nextcloud.log | grep "set session" | jq "[.url, .message]"
[
  "/ocs/v2.php/apps/notifications/api/v2/notifications",
  "set session {\"LAST_ACTIVITY\":1667572665,\"requesttoken\":\"b\\/moV8eCbs26rgCJAE6YdpOgiXGiz3ZQ\",\"checkServer_succeeded\":true,\"user_id\":\"admin\",\"loginname\":\"admin\",\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"last-password-confirm\":1667567734,\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true},\"two_factor_auth_passed\":\"admin\"}"
]
[
  "/ocs/v1.php/cloud/users?format=json",
  "set session {\"LAST_ACTIVITY\":1667572671}"
]
[
  "/ocs/v1.php/cloud/users?format=json",
  "set session {\"LAST_ACTIVITY\":1667572671,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\"}"
]
[
  "/ocs/v1.php/cloud/users?format=json",
  "set session {\"LAST_ACTIVITY\":1667572671,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true}"
]
[
  "/ocs/v1.php/cloud/users?format=json",
  "set session {\"LAST_ACTIVITY\":1667572671,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"user_id\":\"admin\",\"loginname\":\"admin\",\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572672,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"user_id\":\"admin\",\"loginname\":\"admin\",\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572672,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"loginname\":\"admin\",\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572672,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572672,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572672,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572672,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/login?redirect_url=/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572672,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/login",
  "set session {\"LAST_ACTIVITY\":1667572674,\"requesttoken\":\"rxpY4Im8HA+ETkF5imst7bUHCAEg9\\/7D\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572671}"
]
[
  "/index.php/login",
  "set session {\"LAST_ACTIVITY\":1667572674,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\"}"
]
[
  "/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572676,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\"}"
]
[
  "/index.php/apps/files",
  "set session {\"LAST_ACTIVITY\":1667572676,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true}}"
]
[
  "/index.php/avatar/rzeketu1/64?v=0",
  "set session {\"LAST_ACTIVITY\":1667572677,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true}}"
]
[
  "/ocs/v2.php/search/providers?from=%2Fapps%2Ffiles",
  "set session {\"LAST_ACTIVITY\":1667572678,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true}}"
]
[
  "/ocs/v2.php/apps/notifications/api/v2/notifications",
  "set session {\"LAST_ACTIVITY\":1667572681,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true}}"
]
[
  "/index.php/apps/files_sharing/api/externalShares",
  "set session {\"LAST_ACTIVITY\":1667572682,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true}}"
]
[
  "/remote.php/dav/files/rzeketu1/",
  "set session {\"LAST_ACTIVITY\":1667572682,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true},\"two_factor_auth_passed\":\"rzeketu1\"}"
]
[
  "/index.php/avatar/rzeketu1/64/dark?v=0",
  "set session {\"LAST_ACTIVITY\":1667572683,\"requesttoken\":\"wOirYlodceLJwwObK2nqX\\/LMGiGSoBsh\",\"checkServer_succeeded\":true,\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"rzeketu1\\\",\\\"loginName\\\":\\\"rzeketu1\\\",\\\"password\\\":\\\"password\\\",\\\"isTokenLogin\\\":false}\",\"AUTHENTICATED_TO_DAV_BACKEND\":\"admin\",\"last-password-confirm\":1667572674,\"user_id\":\"rzeketu1\",\"loginname\":\"rzeketu1\",\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true},\"two_factor_auth_passed\":\"rzeketu1\"}"
]
[
  "/ocs/v2.php/apps/notifications/api/v2/notifications",
  "set session {\"LAST_ACTIVITY\":1667572695,\"requesttoken\":\"b\\/moV8eCbs26rgCJAE6YdpOgiXGiz3ZQ\",\"checkServer_succeeded\":true,\"user_id\":\"admin\",\"loginname\":\"admin\",\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"last-password-confirm\":1667567734,\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true},\"two_factor_auth_passed\":\"admin\"}"
]
[
  "/ocs/v2.php/apps/notifications/api/v2/notifications",
  "set session {\"LAST_ACTIVITY\":1667572725,\"requesttoken\":\"b\\/moV8eCbs26rgCJAE6YdpOgiXGiz3ZQ\",\"checkServer_succeeded\":true,\"user_id\":\"admin\",\"loginname\":\"admin\",\"login_credentials\":\"{\\\"run\\\":true,\\\"uid\\\":\\\"admin\\\",\\\"loginName\\\":\\\"admin\\\",\\\"password\\\":\\\"admin\\\",\\\"isTokenLogin\\\":false}\",\"last-password-confirm\":1667567734,\"timezone\":\"1\",\"token_scope\":{\"filesystem\":true},\"two_factor_auth_passed\":\"admin\"}"
]
```
</details>

**Pull request merged**
