### PR TITLE
Place ```<h1>``` into main content

### LINKED ISSUE #35138: h1 should instead be in the app content, ideally displayed visually
```<h1>``` should be never in ```<span>```.

In this issue ```<h1>``` should be moved to a content. Could i left ```<h1>```- text in ```<span>```and move actual ```<h1> ``` behind the image? 

image

https://github.com/nextcloud/server/blob/81ea283752aec200c17dded4aa1abf1b817f0910/core/templates/layout.public.php#L39-L49

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes #35138

### CODE REVIEW

**Review by Pytal — APPROVED** [review]
Looks good and seems the global styles keeps them in the same positions

**Review by ChristophWurst — APPROVED** [review]
Code changes look good

**Comment by JuliaKirschenheuter** [comment]
@dependabot rebase

**Comment by ChristophWurst** [comment]
I just restarted Drone. The rebase is not necessary.

**Comment by szaimen** [comment]
> I just restarted Drone. The rebase is not necessary.

Sorry

**Comment by ChristophWurst** [comment]
Sharing integration test failure unrelated.

**Pull request merged**
