### PR TITLE
Stable9 smb cherry-pciks

### PR DESCRIPTION
**Pull request by LukasReschke**
From https://github.com/owncloud/core/pull/25808, https://github.com/owncloud/core/pull/25808 and https://github.com/owncloud/core/pull/25734

### CODE REVIEW

**Comment by icewind1991** [comment]
:-1: a lot of this is bad, I'll take some time to sort trough the changes later

**Comment by LukasReschke** [comment]
@icewind1991 Any update?

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/1678

**Comment by rullzer** [comment]
@icewind1991 so this can be closed?

**Comment by icewind1991** [comment]
Yes

**Pull request closed without merging**
