### PR TITLE
Fix border color contrast

### LINKED ISSUE #33843: [BITV] Dark mode needs higher contrast
e.g. for input field placeholders on log in

Need to check if this still applies with the new design and if yes, what changes are required to fix this.

@jancborchardt @nimishavijay

### PR DESCRIPTION
**Pull request by Pytal**
### Border color contrast requirements
To meet WCAG AA contrast requirements for border colors, categorized under “Graphical Objects and User Interface Components”, a minimum 3:1 foreground-background contrast ratio is required

### Primary color borders
Original color is lightened slightly
`#00639a` → `#006aa3`

<details>
<summary>Before/After contrast ratios</summary>

Dark mode
Before | After
--- | ---
image | image

Light mode
Before | After
--- | ---
image | image

</details>

### General-purpose borders
Dark mode
`--color-border`: `#292929` → `#646464`
`--color-border-dark`: `#3b3b3b` → `#787878` (greater contrast on dark backgrounds due to being lighter than `--color-border`)

Light mode
`--color-border`: `#ededed` → `#949494`
`--color-border-dark`: `#dbdbdb` → `#808080` (greater contrast on light backgrounds due to being darker than `--color-border`)

<details>
<summary>Before/After contrast ratios</summary>

Dark mode
Before | After
--- | ---
image | image

Light mode
Before | After
--- | ---
image | image

</details>

### Examples

Primary + general border colors
Before | After
--- | ---
image | image

General border color usage
Before | After
--- | ---
image | image

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
> OCA\Theming\Tests\Service\DefaultThemeTest::testThemindDisabledFallbackCss
Failed asserting that two strings are equal.

Tests fail

**Review by AndyScherzinger — APPROVED** [review]

**Comment by PVince81** [comment]
@Pytal theming tests are failing on master now, please fix them. I'll ignore them for now as we need to ship the RC soon.

**Comment by Pytal** [comment]
> @Pytal theming tests are failing on master now, please fix them. I'll ignore them for now as we need to ship the RC soon.

Rather, `master` is passing e.g. https://drone.nextcloud.com/nextcloud/server/26432 and CI for this PR was all green in https://drone.nextcloud.com/nextcloud/server/26173

They are failing on `stable25` since https://github.com/nextcloud/server/pull/35346 in https://drone.nextcloud.com/nextcloud/server/26177

Fixed in https://github.com/nextcloud/server/pull/35415

**Comment by jancborchardt** [comment]
@Pytal the contrast is good for the input fields – unfortunately it makes regular borders like divider lines much too present, like here in Talk.

It would be best if we would use a separate variable like `--color-border-input` for this new value, and keep `--color-border` at the old one. cc @nimishavijay as discussed, and @AndyScherzinger @PVince81 @skjnldsv FYI


image

**Pull request merged**
