### PR TITLE
fix: Use correct unit for file sizes and fix user quota

### PR DESCRIPTION
**Pull request by susnux**
## Summary
We always used binary file sizes (base 2, meaning 2048 bytes = 2KiB), but we added the wrong unit (we used the decimal (base 10) unit e.g. 2KB).

This fixes the user management showing a wrong quota (https://github.com/nextcloud/server/issues/38874 for master)

Also the OC_Helper now supports base 10 and base 2 in `computerFileSize`, for backwards compatibility it defaults to force even units like `KB` to be binary.

### Screenshots
Screenshot | comment
---|---
Screenshot_20230925_163450 | As discussed during the Nextcloud conf, we always expect the user to mean the binary size (mostly they are confused by windows using the wrong unit)
Screenshot 2023-09-25 at 16-33-31 Aktive Benutzer - Benutzer - Benutzer - Nextcloud|Quota is now displayed correctly
Screenshot 2023-09-25 at 16-32-58 Dateien - Nextcloud|The file list automatically adapted to the correct unit

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by susnux** [comment]
cc @sorbaugh and @AndyScherzinger 

The problem:
- On Nextcloud up to (including) 26 we used decimal units like `10 KB` or `20 GB` but we always meant `10 KB = 10 * 1024 bytes` and not `10 KB = 10 * 1000 bytes`.
- On Nextcloud 27 there was a regression (`@nextcloud/files`) that switched to even decimal values, meaning `10KB = 10 * 1000 bytes` but our backend was and is always using binary values (1024).
- On Nextcloud 27.1 we patched this and reverted back to binary values (10* 1024) but with decimal units (`KB` instead of the proper `KiB`).

But for current master the frontend is still broken, we have to options:
1. Everything stays like it was on Nextcloud 26 and below, this requires the `@nextcloud/files` library to be adjusted again.
2. Move to decimal values (we should not do this the only people doing this are hard drive manufacturers and Apple)
3. Show the proper units (`KiB` instead of `KB`, `GiB` instead of `GB`...) this is what this PR is about.

From my point of view only 1 and 3 are really considerable solutions.
Pro 1:
- Everything stays the same UI wise
- Windows is using the wrong units for decades now, so the majority of users are used to them
Con 1:
- See the confusion in the linked issue, having one unit used for multiple different things confuses

Pro 3 (this PR):
- It is clear what unit and file sizes to expect, so less confusion
Con 3:
- Non technical users might choke on the `i` in the unit (but probably it will even not attract attention)
- Changing UI

**Comment by sorbaugh** [comment]
While it's true that lots of users are conditioned to read KB, GB, etc, I think switching to the correct units would be a "soft enough" change UX wise so I would vote for option 3 (but would be fine with option 1).

**Comment by jancborchardt** [comment]
I’d say it’s best in this case to go with what Windows does since @susnux as you say that is what the majority of people are used to. Yes it is not correct, but it is sort of convention on a topic where many people are confused anyway.

**Comment by sorbaugh** [comment]
I don't have a strong opinion on this, so option 1 is fine as well if we can foresee that option 3 would be confusing to people.

**Comment by susnux** [comment]
It was decided to keep current style.

**Comment by artonge** [comment]
@nextcloud/designers can one of you tell us why we should stick to the current style?
The current situation is creating confusion for user and admins as the size does not match what they see in other softwares.

**Comment by jancborchardt** [comment]
My last comment on it is 3 years old https://github.com/nextcloud/server/pull/40621#issuecomment-1766098807

So I am fine to switch if that is also an established way of showing things e.g. in MS and Google products. For details like this it’s best to have least surprise.

**Comment by artonge** [comment]
> So I am fine to switch if that is also an established way of showing things e.g. in MS and Google products. For details like this it’s best to have least surprise.

Neither of them are consistent, they are both displaying GiB values next to the GB unit. So I would rather move away from what they are doing.

**Comment by provokateurin** [comment]
> For details like this it’s best to have least surprise.

I think the current way is the biggest surprise, because it is inconsistent and regularly leads to problems if you actually have to deal with these values (e.g. quotas).

**Pull request closed without merging**
