### PR TITLE
Fix AppSettingsController.php overwriting currentLanguage

### LINKED ISSUE #42042: [Bug]: Cannot obtain the list of apps
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Today I found that the lists of apps is empty: none of categories is shown. There are errors in the log file, see below. 

### Steps to reproduce

1. Proceed at `/settings/apps`
2. Observe empty area

### Expected behavior

There should be lists of apps

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.cloud",
            "ncoffice.my.cloud",
            "office.my.cloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "overwrite.cli.url": "https:\/\/my.cloud\/",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_send_plaintext_only": false,
        "default_phone_region": "UA",
        "force_locale": "uk_UA",
        "force_language": "uk",
        "allow_user_to_change_display_name": false,
        "auth.webauthn.enabled": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 21600,
        "session_relaxed_expiry": false,
        "session_keepalive": false,
        "auto_logout": false,
        "skeletondirectory": "\/media\/server\/ncdata\/skeleton",
        "maintenance": false,
        "sort_groups_by_name": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "app_install_overwrite": [
            "files_fulltextsearch",
            "fulltextsearch_elasticsearch",
            "fulltextsearch",
            "files_fulltextsearch_tesseract",
            "twofactor_gateway",
            "files_downloadactivity",
            "holiday_calendars",
            "twofactor_reminder"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "logtype": "file",
        "logfile": "\/media\/server\/ncdata\/nextcloud.log",
        "loglevel": 2,
        "activity_use_cached_mountpoints": true,
        "trashbin_retention_obligation": "auto, 30",
        "logtimezone": "Europe\/***",
        "profile.enabled": false,
        "onlyoffice": {
            "verify_peer_off": false,
            "jwt_secret": "seKCret",
            "jwt_header": "AuthorizationJwt"
        },
        "enable_previews": true,
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image"
        ],
        "jpeg_quality": "75",
        "preview_concurrency_new": "1",
        "twofactor_enforced": true,
        "allow_local_remote_servers": true,
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": []
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - dav: 1.27.0
  - event_update_notification: 2.3.0
  - external: 5.2.1
  - extract: 1.3.6
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_downloadactivity: 1.16.0
  - files_fulltextsearch: 27.0.1
  - files_fulltextsearch_tesseract: 27.0.0
  - files_linkeditor: 1.1.16
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_scripts: 3.0.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - files_zip: 1.4.0
  - firstrunwizard: 2.16.0
  - fulltextsearch: 27.0.2
  - fulltextsearch_elasticsearch: 27.0.5
  - group_everyone: 0.1.13
  - groupfolders: 15.3.1
  - holiday_calendars: 0.3.0
  - limit_login_to_ip: 4.0.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - onlyoffice: 8.2.4
  - password_policy: 1.17.0
  - previewgenerator: 5.4.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.18.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - tables: 0.6.4
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - thesearchpage: 1.2.2
  - twofactor_admin: 4.4.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_gateway: 0.20.0
  - twofactor_reminder: 1.1.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0 (installed 1.17.0)
  - assistant: 1.0.2 (installed 1.0.2)
  - circles: 27.0.1 (installed 24.0.0)
  - contactsinteraction: 1.8.0 (installed 1.5.0)
  - dashboard: 7.7.0 (installed 7.4.0)
  - encryption: 2.15.0 (installed 2.15.0)
  - end_to_end_encryption: 1.13.1 (installed 1.13.1)
  - federation: 1.17.0 (installed 1.14.0)
  - files_archive: 1.1.3 (installed 1.1.3)
  - files_confidential: 2.0.1 (installed 2.0.1)
  - files_external: 1.19.0
  - files_lock: 27.0.2 (installed 27.0.2)
  - files_reminders: 1.0.0 (installed 1.0.0)
  - files_trackdownloads: 1.11.0 (installed 1.11.0)
  - flow_notifications: 1.7.0 (installed 1.7.0)
  - geoblocker: 0.5.11 (installed 0.5.11)
  - nextcloud_announcements: 1.16.0 (installed 1.13.0)
  - photos: 2.3.0 (installed 2.2.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - recommendations: 1.6.0 (installed 1.5.0)
  - related_resources: 1.2.0 (installed 1.0.3)
  - richdocuments: 8.2.3 (installed 8.2.3)
  - secrets: 1.5.2 (installed 1.5.2)
  - sharebymail: 1.17.0 (installed 1.14.0)
  - support: 1.10.0 (installed 1.7.0)
  - survey_client: 1.15.0 (installed 1.12.0)
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0 (installed 1.17.0)
  - twofactor_email: 2.7.4 (installed 2.7.4)
  - twofactor_webauthn: 1.3.2 (installed 1.3.2)
  - user_ldap: 1.17.0
  - user_status: 1.7.0 (installed 1.4.0)
  - weather_status: 1.7.0 (installed 1.4.0)
  - workflow_ocr: 1.27.5 (installed 1.26.1)
  - workflow_pdf_converter: 1.12.0 (installed 1.12.0)
  - workflow_script: 1.12.1 (installed 1.12.1)
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
[PHP] Error: Undefined array key "en" at /var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php#373

GET /settings/apps/list

[PHP] Error: Undefined array key "en" at /var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php#374

GET /settings/apps/list

[PHP] Error: Undefined array key "en" at /var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php#375

GET /settings/apps/list

[PHP] Error: Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php#375

GET /settings/apps/list
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by 1manprojects**
Fix for currentLanguage being overwritten by currentVersion thus breaking App-View

* Resolves: #42042 #42037

## Summary
Fixes Issue where the currentLanguage is being overwritten in certain cases by the currentVersion of the App thus breaking the App View in Nextcloud.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by kesselb — COMMENTED** [review]
Wow, this has been sitting in our code for quite a while now ;)

**Review by nickvergessen — APPROVED** [review]
5y old bug Oo

**Review by juliusknorr — APPROVED** [review]

**Comment by solracsf** [comment]
Backport?

**Pull request merged**
