### PR TITLE
Run phan tests only on high memory machines

### PR DESCRIPTION
**Pull request by MorrisJobke**
This should fix the out of memory issues we are seeing with this job.

Currently only one of our servers has this, but it should be enough for this test here.

Let's see if it is scheduled correctly.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Worked: https://drone.nextcloud.com/nextcloud/server/18392/5/6 🚀

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Administrative only -> merging.

**Pull request merged**
