### PR TITLE
Keep group restrictions when reenabling apps after an update

### LINKED ISSUE #4538: Group restrictions for an app are lost when disabling it
### Steps to reproduce

1. Enable an app and chose the option to "Enable only for specific groups" (specifying 1+ valid group(s))
2. Disable the app
3. Enable the app again

*Notes:* 
- Steps 2 and 3 can be carried out using `occ app:` with the same result
- Between steps 2 and 3, if you don't refresh the page you'll notice that the group selector stays visible, with the groups you selected still shown. It is probably only a display bug and should warrant its own issue in the tracker.

### Expected behaviour
If the option of enabling "only for specific groups" was used before the app is disabled, enabling the app again should by default enabling it for the same previously chosen groups

### Actual behaviour
The app is enabled for all groups.

As apps are disabled during the update process, you're then forced to reconfigure the group permissions for each app.

### Server configuration

**Operating system**: Debian 8 "Jessie"

**Nextcloud version:** 11.0.3

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix https://github.com/nextcloud/server/issues/4538

Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by szaimen** [comment]
Great to see this getting fixed :)
Will this be backported?

**Comment by nickvergessen** [comment]
> Great to see this getting fixed :)

I wasn't aware it was actually broken. I think this is quite sever 😬

**Comment by szaimen** [comment]
> I wasn't aware it was actually broken. I think this is quite sever 😬

Define broken ;)
But there was an issue open about this https://github.com/nextcloud/server/issues/4538

**Comment by szaimen** [comment]
Additionally, I wonder if this line shouldn't be called also if an operation before fails because otherwise it would not reset the old PUSH_KEY, no? 
https://github.com/nextcloud/android/blob/247d422b3748f0c2b6ea270bdf3613dba0abe6cc/src/gplay/java/com/owncloud/android/utils/PushUtils.java#L181

**Comment by szaimen** [comment]
Sry, wrong ticket

**Review by kesselb — APPROVED** [review]

**Comment by blizzz** [comment]
why is the interface removed?

**Review by blizzz — APPROVED** [review]

**Pull request merged**
