### PR TITLE
Fix mention bubbles not rendered in comment editor

### PR DESCRIPTION
**Pull request by danxuliu**
The NcRichContenteditable requires [the `userData` property to be given to render the mention bubbles](https://github.com/nextcloud/nextcloud-vue/blob/b1cb5715d51f7000c250675a4d5dfa4fe44a02ba/src/components/NcRichContenteditable/NcRichContenteditable.vue#L61-L63). Otherwise after selecting a candidate mention just `@` followed by the user id is shown in plain text.

To solve that now the data of the candidate mentions is cached whenever the autocomplete list is shown, and reset once a comment has been sent.

## How to test

- Open the Files app
- Show the sidebar for any file
- Open the _Comments_ tab
- In the new comment text, type `@` and mention any user

### Result with this pull request

A mention bubble is added

### Result without this pull request

The user id is written in plain text

### CODE REVIEW

**Comment by artonge** [comment]
Hey @danxuliu very sorry, I saw this PR notification but didn't make the link.

When fixing it, I noticed that the issue also occurs when editing an existing comment and adding a mention. To fix it, I also had to add this: https://github.com/nextcloud/server/pull/35187/files#diff-b569f730b67ed3363f41a268df4d68e6693d02b2eddb278194ddb7326f8b041aL178-R194

Can you check your PR and add it too if necessary ?

**Comment by danxuliu** [comment]
> Hey @danxuliu very sorry, I saw this PR notification but didn't make the link.

No problem at all :-)
 
> When fixing it, I noticed that the issue also occurs when editing an existing comment and adding a mention. To fix it, I also had to add this: https://github.com/nextcloud/server/pull/35187/files#diff-b569f730b67ed3363f41a268df4d68e6693d02b2eddb278194ddb7326f8b041aL178-R194
> 
> Can you check your PR and add it too if necessary ?

That is a very good point, my pull request only fixes new comments, but not editing existing ones. Moreover, as the user data is shared between all comments at all time it is not possible to reset the candidate mentions when a comment is sent like done here. Therefore, if you are OK with that, I would instead close my pull request in favour of yours :-)

**Comment by danxuliu** [comment]
Closed in favour of #35187

**Pull request closed without merging**
