### PR TITLE
Do not send a body for "No content", "Not modified" and others

### PR DESCRIPTION
**Pull request by nickvergessen**
Also moved the OCSController away from the methods of the deprecated class.

This sometimes causes problems for the Talk mobile apps, because 304 should not have a body, but sometimes had:
`{"ocs":{"meta":{"status":"failure","statuscode":304,"message":null},"data":[]}}`

cc @mario

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by patagfa** [comment]
noticed issue on Nextcloud 15.0.7
(https://help.nextcloud.com/t/f5-loadbalancer-log-server-sends-too-much-data/49772)

**Comment by patagfa** [comment]
problem if fixed by adding aditional check:
        if ($status === Http::STATUS_NO_CONTENT ||
                        $status = 204 ||
                        $status = 304 ||
                        $status === Http::STATUS_NOT_MODIFIED ||

**Comment by kesselb** [comment]
$status = 204 is not a comparison. Your code change $status to 304.

**Comment by kesselb** [comment]
Does it work if you restore the original version und replace === with == ?

**Comment by patagfa** [comment]
No using == still produces error on loadbalancer

**Comment by kesselb** [comment]
Could you open a bug report https://github.com/nextcloud/server/issues/new/choose? Please provide one example (which url is called)

**Comment by patagfa** [comment]
created bug report 16100

**Pull request merged**
