### PR TITLE
[stable23] Fix apps settings error message timeout

### PR DESCRIPTION
**Pull request by Pytal**
Backport of https://github.com/nextcloud/server/pull/31359, including refactor from https://github.com/nextcloud/server/pull/31116/files#diff-ef3ffcc0045532b590135a9a184996ea35cbf55a6366737aa4f8c87cfc45c19a

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by blizzz** [comment]
conflicts, moving to 23.0.4

**Comment by blizzz** [comment]
still conflicts, moving to 23.0.5

**Comment by artonge** [comment]
Samba tests failing, but unrelated

**Pull request merged**
