### PR TITLE
Automatically cut the token name on the first level

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up to #31658

### CODE REVIEW

**Review by max-nextcloud — COMMENTED** [review]
I can confirm this fixes the failing cypress runs in text. I do not (yet) understand the implications of these changes. Mainly wondering if truncated names will always be unique. But i won't be able to think this through tonight. So just commenting and not approving.

**Comment by nickvergessen** [comment]
Backports added to:
* https://github.com/nextcloud/server/pull/31677
* https://github.com/nextcloud/server/pull/31678
* https://github.com/nextcloud/server/pull/31680

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Mainly wondering if truncated names will always be unique.

It's just the labels shown in the list of index.php/settings/user/security
They are not unique, e.g. every token created with `occ user:add-app-password` is called "cli"

**Review by max-nextcloud — APPROVED** [review]
Okay... since the name is just for identifying the source of the token and tokens are not identified by it this seems save to me.

**Pull request merged**
