### PR TITLE
[stable10] Increase version to 10.0 RC1

### PR DESCRIPTION
**Pull request by LukasReschke**
Let's get ready for that. So we can build later today :-)

cc @karlitschek @MorrisJobke

### CODE REVIEW

**Comment by rullzer** [comment]
LGTM

**Comment by mar1u5** [comment]
:shipit:

**Comment by karlitschek** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
We should get all in https://github.com/nextcloud/server/pull/905 in before the RC to have not weirdly looking app management for the RC. I will also do a smoke testing of the tar ball before releasing it into the wild together with @LukasReschke later this evening.

**Pull request merged**
