### PR TITLE
Honor avatar visibility settings

### LINKED ISSUE #5456: Privacy: Avatar public available
### Steps to reproduce
1. Get to know any username of an nextcloud instance
2. Get avatar image by using `https://<domain>/nextcloud/index.php/avatar/USER/<size>`

### Expected behaviour
Configurable by admin
* User image
* Some default image
* require login / Show access denied

### Actual behaviour
Avatar image is available to public

### Server configuration
**Nextcloud version:** 12

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #5456
Only when an avatar is set to public should we show it to the public.
For now this has an open question as to how to solve federated avatars.
But I assume a dedicated paramter or endpooint would make sense there.

Todo:
- [x] Fix tests (most likely)
- [x] Think about federated avatars

### CODE REVIEW

**Comment by rullzer** [comment]
For federated avatars we need a new endpoint anyways to verify their token etc. Lets leave that till later.

**Comment by rullzer** [comment]
To test. Set your avatar level in the personal settings.
And request the avatar. Depending how it is set you should see it or get a 404.

**Review by skjnldsv — APPROVED** [review]
Works!

**Review by ChristophWurst — APPROVED** [review]
Code looks good!

**Comment by rullzer** [comment]
@nickvergessen you first wanted to test something right?

**Comment by nickvergessen** [comment]
The `Contacts` level does not work. Should we just remove it? Since we don't send any referrers, we can not know if the image was requested by a remote instance in the allowed space. Or are avatars uploaded to the lookup server?

**Comment by skjnldsv** [comment]
I have no clue what that means Joas!
I'll follow you to what you think is best

**Comment by rullzer** [comment]
> The `Contacts` level does not work. Should we just remove it? Since we don't send any referrers, we can not know if the image was requested by a remote instance in the allowed space. Or are avatars uploaded to the lookup server?

We should fix it. I'd leave it for now. And see if we can come up with and endpoint to request remote avatars where you send your share token for example.

**Comment by nickvergessen** [comment]
Okay, then lets merge

**Comment by tobiasKaminsky** [comment]
Damn, I saw this too late.
@rullzer this will break our clients as they assume that we get an image back.
Returning something else was previously also the case (then you got the userId back).

Can we adjust this to show the generic colored round avatar with first char in it?

**Comment by rullzer** [comment]
@tobiasKaminsky no it won't. As long as you send your credentials you should get back the image.

**Comment by tobiasKaminsky** [comment]
Clients also use https://<domain>/nextcloud/index.php/avatar/USER/<size> this to get avatars from other users (on the same instance [currently no federation]) when we do a search, or show it in file list if file was shared by an user.

**Comment by rullzer** [comment]
> Clients also use https:///nextcloud/index.php/avatar/USER/ this to get avatars from other users (on the same instance [currently no federation]) when we do a search, or show it in file list if file was shared by an user.

yes I know. But read the code. 

https://github.com/nextcloud/server/pull/17715/files#diff-17d17c6a954f29c12717db921f235531R134-R137

If the avatar is not public. And you do an anonymous request we return the 404.
So as long as you authenticated request your avatars all is fine.

**Comment by tobiasKaminsky** [comment]
True, stupid from me, I read only have of the code :-(
Sorry for the noise

**Pull request merged**
