### PR TITLE
Fix ldap css and jquery ui css fix for menu dropdown

### PR DESCRIPTION
**Pull request by skjnldsv**
refs: #1932 #1780 #2524 

capture d ecran_2016-12-06_13-14-42

@MorrisJobke @nextcloud/designers

### CODE REVIEW

**Comment by skjnldsv** [comment]
Rebased and ready to merge!

**Comment by MorrisJobke** [comment]
@blizzz Could you have a look at this?

**Comment by blizzz** [comment]
Advanced tab does not use the available space properly:

spectacle a18316

Looks good otherwise!

**Comment by LukasReschke** [comment]
@skjnldsv Can we move that to 12? I'd prefer to consider 11 closed for any non-critical merges.

**Comment by skjnldsv** [comment]
@LukasReschke If you want! :)
It'w not really a game-changing pr ;)

**Comment by LukasReschke** [comment]
Ok. – Master is open again so I suppose we need to fix https://github.com/nextcloud/server/pull/2529#issuecomment-265415604 and then can merge this?

**Comment by skjnldsv** [comment]
@LukasReschke Exactly. I didn't had the time yet.

**Comment by LukasReschke** [comment]
@skjnldsv Is this still interesting? If not we should probably close this 😉

**Comment by skjnldsv** [comment]
I need to rework this with the scss :)
Let it open 🎉

**Comment by jancborchardt** [comment]
Moving to Nextcloud 13 then as we have feature freeze tomorrow. :)

**Comment by MorrisJobke** [comment]
@skjnldsv I guess most of this in here was fixed by #6341 - can we close this then?

**Comment by skjnldsv** [comment]
Ehheh, yes we can! 💪

**Pull request closed without merging**
