### PR TITLE
Fix uninitialized variable $this->params

### PR DESCRIPTION
**Pull request by william-p**
Use directly $params for build correct cache key.

### CODE REVIEW

**Comment by william-p** [comment]
Humm sorry, my commit was signed, where i wrong ?

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> Humm sorry, my commit was signed, where i wrong ?

The sign-off is missing - see https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work for details

**Review by nickvergessen — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]

**Comment by nickvergessen** [comment]
Needs backporting to 12

**Comment by MorrisJobke** [comment]
> Needs backporting to 12

#6944

**Pull request merged**
