### PR TITLE
Add redis cluster tests to our CI jobs

### LINKED ISSUE #4511: Add drone tests for redis cluster
* add drone tests for #4061

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #4511

### CODE REVIEW

**Comment by rullzer** [comment]
CI is not happy  :disappointed:

**Comment by MorrisJobke** [comment]
> CI is not happy 😞

I know - I forgot the essential part: adding the redis cluster xD

**Comment by MorrisJobke** [comment]
Background: the RedisCluster only seems to implement `del` and not `delete` as well. https://github.com/phpredis/phpredis/blob/develop/redis_cluster.h#L134

**Comment by MorrisJobke** [comment]
This is failing in the normal unit tests:

```
Time: 3.67 minutes, Memory: 288.25MB
There was 1 failure:
1) OCA\Files_Sharing\Tests\SharedStorageTest::testGetPermissions
Failed asserting that 11 is identical to 9.
/drone/src/github.com/nextcloud/server/apps/files_sharing/tests/SharedStorageTest.php:213
```

And this is the only stuff that fails for the clustered test:

```
There were 2 failures:
1) Test\Memcache\RedisTest::testCadNotChanged
Failed asserting that true is false.
/drone/src/github.com/nextcloud/server/tests/lib/Memcache/Cache.php:116
2) Test\Memcache\RedisTest::testClear
Failed asserting that true is false.
/drone/src/github.com/nextcloud/server/tests/lib/Cache/TestCache.php:62
```

**Comment by MorrisJobke** [comment]
@icewind1991 Do you have any ideas why those tests fail?

**Comment by MorrisJobke** [comment]
> 1) OCA\Files_Sharing\Tests\SharedStorageTest::testGetPermissions
> Failed asserting that 11 is identical to 9.

That one is also present on other PRs 🙈

**Comment by MorrisJobke** [comment]
> Test\Memcache\RedisTest::testClear
> Failed asserting that true is false.
> /drone/src/github.com/nextcloud/server/tests/lib/Cache/TestCache.php:62

On my local instance I only see this one here. Let me check if this is a race condition that was caused by the cluster.

**Comment by MorrisJobke** [comment]
Weird stuff happening here.

This is the prefix for clear(): `Umu6gv139cMIN1_*`

Those keys are returned for this prefix:

```
Array (
    [0] => b3af84910daab2213dc371721ac31adb/core.appinfo/drone/src/apps/encryption/appinfo/info.xml1493753956
    [1] => Umu6gv139cMIN3_value1
    [2] => Umu6gv139cMIN2_value1
    [3] => b3af84910daab2213dc371721ac31adb/core.appinfo/drone/src/apps/updatenotification/appinfo/info.xml1493753957
    [4] => b3af84910daab2213dc371721ac31adb/core.appinfo/drone/src/apps/twofactor_backupcodes/appinfo/info.xml1493753957
    [5] => b3af84910daab2213dc371721ac31adb/core.appinfo/drone/src/apps/user_ldap/appinfo/info.xml1493753957
    [6] => b3af84910daab2213dc371721ac31adb/core.appinfo/drone/src/apps/sharebymail/appinfo/info.xml1493753957
    [7] => vU0LD4uAVc9GUVP0QQ3xijLpht
    [8] => b3af84910daab2213dc371721ac31adb/core.appinfo/drone/src/apps/gallery/appinfo/info.xml1492807515
    [9] => b3af84910daab2213dc371721ac31adb/core.appinfo/drone/src/apps/files_versions/appinfo/info.xml1493753957
    [10] => b3af84910daab2213dc371721ac31adb/core.appinfo/drone/src/apps/dav/appinfo/info.xml1493753963
)
```

And it should contain only:

```
Array (
    [0] => Umu6gv139cMIN1_value1
    [1] => Umu6gv139cMIN1_value2
)
```

What is wrong with this redis cluster :/


And everytime I execute it again it will delete other keys, but never the ones I expected:

```
[memcache-redis-cluster:L56:14s]  Array (
[memcache-redis-cluster:L57:14s] -    '1_value1' => null
[memcache-redis-cluster:L58:14s] +    '1_value1' => 'ipsum lorum1'
[memcache-redis-cluster:L59:14s]      '1_value2' => null
[memcache-redis-cluster:L60:14s] -    '2_value1' => 'ipsum lorum3'
[memcache-redis-cluster:L61:14s] -    '3_value1' => 'ipsum lorum4'
[memcache-redis-cluster:L62:14s] +    '2_value1' => null
[memcache-redis-cluster:L63:14s] +    '3_value1' => null
[memcache-redis-cluster:L64:14s]  )
```

vs

```
[memcache-redis-cluster:L70:16s]  Array (
[memcache-redis-cluster:L71:16s]      '1_value1' => null
[memcache-redis-cluster:L72:16s] -    '1_value2' => null
[memcache-redis-cluster:L73:16s] -    '2_value1' => 'ipsum lorum3'
[memcache-redis-cluster:L74:16s] +    '1_value2' => 'ipsum lorum2'
[memcache-redis-cluster:L75:16s] +    '2_value1' => null
[memcache-redis-cluster:L76:16s]      '3_value1' => 'ipsum lorum4'
[memcache-redis-cluster:L77:16s]  )
```

I will test with another setup here. 🙈

**Comment by MorrisJobke** [comment]
I tested this with a normal setup of the redis and there it works fine. And I have no idea, why it is not working here.

**Comment by MorrisJobke** [comment]
> 1) OCA\Files_Sharing\Tests\SharedStorageTest::testGetPermissions

Rebased to fix that one - see #4684

**Comment by MorrisJobke** [comment]
I extracted the fixes into #4700

**Comment by MorrisJobke** [comment]
Should be fixed now. See #4821 for details

**Comment by ChristophWurst** [comment]
CI is still not happy 😢 
```
There was 1 failure:
1) Test\Memcache\RedisTest::testClear
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    '1_value1' => null
+    '1_value1' => 'ipsum lorum1'
     '1_value2' => null
     '2_value1' => 'ipsum lorum3'
     '3_value1' => 'ipsum lorum4'
 )
/drone/src/github.com/nextcloud/server/tests/lib/Cache/TestCache.php:83
FAILURES!
Tests: 18, Assertions: 55, Failures: 1.
```

**Comment by MorrisJobke** [comment]
And I have no idea why. When I use a non-docker cluster the tests run reliable and fine every single time -.-

**Comment by rullzer** [comment]
Ok fixed now I think :pray:

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
It is green :balloon: https://drone.nextcloud.com/nextcloud/server/8060/48

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I restarted to verify it was not just luck ;)

**Comment by rullzer** [comment]
Luck had nothing to do with it https://drone.nextcloud.com/nextcloud/server/8060/48

**Comment by MorrisJobke** [comment]
> Luck had nothing to do with it https://drone.nextcloud.com/nextcloud/server/8060/48

:wink:

**Pull request merged**
