### PR TITLE
Fix db selection design and fix #2511

### LINKED ISSUE #2511: Install page - hover glitch for radio button group
When the option is hovered it is some pixel smaller than the others which causes a weird jumping effect:

bildschirmfoto 2016-12-05 um 15 50 20

It's not the hovered state itself but seems to be the ui-state-hovered class that is added by jquery-ui.

cc @nextcloud/designers @juliushaertl @skjnldsv Could one of you look into this? Thanks :)

### PR DESCRIPTION
**Pull request by skjnldsv**
capture d ecran_2016-12-06_09-56-55

@MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Sadly now the LDAP wizard is a bit broken (Just enable the app and go to the admin settings - you don't need an LDAP server):

Discussed on IRC: will get addressed in a separate PR, because it's also broken on master.

**Comment by MorrisJobke** [comment]
:+1: from me for this

**Comment by rullzer** [comment]
LGTM

**Comment by skjnldsv** [comment]
Thanks @rullzer 😍

**Comment by jancborchardt** [comment]
Dude @skjnldsv thank _you_ :) You’ve been fixing the hell out of all these design issues the last days! :metal:

**Pull request merged**
