### PR TITLE
add audio and video icons

### PR DESCRIPTION
**Pull request by jancborchardt**
Check it @nextcloud/designers @LukasReschke 

capture du 2016-09-19 23-40-41
Simple forms which fit on a 16*16 grid, as usual. :)

### CODE REVIEW

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
👍

**Comment by Bugsbane** [comment]
Where are/will these be used? From the look of them, I'm assuming that they're more for turning the microphone/webcam on and off in Spreed than for mime types etc. Is this accurate?

**Comment by MorrisJobke** [comment]
> Where are/will these be used? From the look of them, I'm assuming that they're more for turning the microphone/webcam on and off in Spreed than for mime types etc. Is this accurate?

Yes. These are for apps like these.

**Pull request merged**
