### PR TITLE
fix(files_versions): renaming file version when its not a string

### LINKED ISSUE #45642: [Bug]: Naming File Version a number removes ability to edit version
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When naming the version of a file to a number: e.g. 1.0
1) it gets renamed to 1 after refresh
2) the version can't be renamed as the input field is not rendered

Console throws:
t.innerversionlabel.trim is not a function
and: 
this.$refs.labelInput is not defined

### Steps to reproduce

1. create a file
2. open sharing side menu
3. go to versions
4. click `edit version name` in three dots menu
5. insert a float
6. reload page
7. try to edit version name

### Expected behavior

version name should stay editable
probably 1.0 should not be renamed to 1

### Nextcloud Server version

27, 28,29 master

### PR DESCRIPTION
**Pull request by susnux**
* Merge of https://github.com/nextcloud/server/pull/45733
* Resolve https://github.com/nextcloud/server/issues/45642

Needed to run Cypress CI

cc @sanskar-soni-9

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by artonge** [comment]
@sanskar-soni-9 I think one e2e test is legitimately failing. Can you take a look at it? :)

**Comment by sanskar-soni-9** [comment]
@artonge Its failing when undefined, oops... 😅
240619_21h31m18s_screenshot

I fixed it now in original PR

**Comment by artonge** [comment]
> @artonge original PR is merged and I updated the fix and rebased with current master in my branch so do I need to create new PR?

Can you try to update this PR? Not sure whether you have the permission.

**Pull request merged**
