### PR TITLE
Add nonce for Safari 12+

### PR DESCRIPTION
**Pull request by rullzer**
As far as I can tell this should work now.

Please test with Safari of course ;)

### CODE REVIEW

**Comment by rullzer** [comment]
Ah so small tests steps

without this patch if you look at the source there is no `nonce-<LONG CODE>` with this patch there is. for all loaded JS etc.

Of course also everything should continue to work with this patch :wink:

**Comment by rullzer** [comment]
Ah my bad. That is what you get when writing this late at night.

The nonce is already there all the time.
It is just that now it is enforced in the CSP.

So

1. open your developer console
2. see the request to the main page you are on
3. Check the content security policy header
4. There should be a none-<LONG TOKEN> element there

**Review by Ivansss — APPROVED** [review]
Tested and works 👍 I get the `nonce-<LONG CODE>` in the Content-Security-Policy header of the response.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
