### PR TITLE
Support subdir in the OCS v2 endpoint

### PR DESCRIPTION
**Pull request by rullzer**
Backport of #606 

CC: @MorrisJobke @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Umm what?

```
Time: 8.71 minutes, Memory: 236.75Mb

There was 1 failure:

1) Test\Log\OwncloudTest::testMicrosecondsLogTimestamp
Failed asserting that '000000' is not equal to 0.

/drone/src/github.com/nextcloud/server/tests/lib/Log/OwncloudTest.php:75

--
```

**Comment by rullzer** [comment]
Let me rebase and push...

**Pull request merged**
