### PR TITLE
Add getID function to the simplefile implementation

### PR DESCRIPTION
**Pull request by rullzer**
Sometimes it is useful to get the actual fileid

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by juliusknorr — CHANGES_REQUESTED** [review]
Ah wait, should be added to the public interface as well then I guess :wink:

**Comment by rullzer** [comment]
> Ah wait, should be added to the public interface as well then I guess wink

Not for now. I'm not sure yet how to do it with the other implementations.
But also would like to backport this part. It is mainly for internal use this getId anyway.

**Review by ChristophWurst — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
