### PR TITLE
[stable23] Avoid use of iconv to get rid of unicode

### PR DESCRIPTION
**Pull request by MichaIng**
Manual backport of: #29470

### CODE REVIEW

**Comment by CarlSchwan** [comment]
> How to correctly sign-off when manually backporting someone else's commit? thinking

Probably by using `git commit --amend --author 'Author name <email>'` or something similar. And add a `Co-authored-by:` tag

**Comment by MichaIng** [comment]
`Co-authored-by:` did the trick 👍.

**Comment by MichaIng** [comment]
Not sure why backportbot failed as I don't see any difference in the code. Let's see whether it works from here.

**Comment by MichaIng** [comment]
Requires manual backport of: #29958

**Review by blizzz — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Pull request merged**
