### PR TITLE
Use the new Events in Flow

### PR DESCRIPTION
**Pull request by rullzer**
IMO the new events are much cleaner.
But lets be pragmatic and just emit both now and kill the legacy stuff for 19.

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by juliusknorr — CHANGES_REQUESTED** [review]
```
PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterOperationsEvent::RegisterOperationsEvent
15 | PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterOperationsEvent::__construct
16 | PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterOperationsEvent::registerOperation
17 | PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterChecksEvent::RegisterChecksEvent
18 | PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterChecksEvent::__construct
19 | PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterChecksEvent::registerCheck
20 | PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterEntitiesEvent::RegisterEntitiesEvent
21 | PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterEntitiesEvent::__construct
22 | PHPDoc is needed for OCP\WorkflowEngine\Events\RegisterEntitiesEvent::registerEntity
23
```

**Comment by rullzer** [comment]
Fixed

**Comment by gary-kim** [comment]
Looks like the tests need fixing :)
<https://drone.nextcloud.com/nextcloud/server/24680/16/5>

**Comment by rullzer** [comment]
And finally all fixed.

**Comment by blizzz** [comment]
i'll review tomorrow

**Review by blizzz — APPROVED** [review]
looks good and works

**Pull request merged**
