### PR TITLE
Kinetic scrolling in files for iOS

### PR DESCRIPTION
**Pull request by kevin147147**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by juliushaertl** [comment]
Makes sense, but probably would be nice to have this on #app-content for all apps, not just files.

@skjnldsv I guess there will be some changes regarding the container in https://github.com/nextcloud/server/pull/9982 that might influence the div we apply the `-webkit-overflow-scrolling` attribute to.

**Comment by skjnldsv** [comment]
@juliushaertl yeah, maybe not merge this one, but make sure we have it on #9982 :)

**Comment by MorrisJobke** [comment]
This was fixed by #10363 and works now on iOS as well. I will close this here, but thanks for the PR anyways 👍

**Pull request closed without merging**
