### PR TITLE
fix share side bar icon and text overlapping

### PR DESCRIPTION
**Pull request by GretaD**
_Internal link_ and _add to projects_ overlap with each other in small screens. 

smallscreendysleks
smallscreennormal

**after my change:
big screen:**

bigscreenfix

**Small screen**
smallscreenfix

My proposal is that the top margin between the last 2 elements to be a bit bigger than the others above since the last 2 ones have text description. @jancborchardt @juliushaertl @skjnldsv what do you think?

### CODE REVIEW

**Review by skjnldsv — CHANGES_REQUESTED** [review]
The 3rd screenshot looks odd.
We should not change the spacing between entries if it's not needed :)

If you want to fix this, you should rather allow the entry height to expand if there is too much data to it (min-height instead of heigh or something)

**Comment by GretaD** [comment]
> The 3rd screenshot looks odd.
> We should not change the spacing between entries if it's not needed :)
> 
> If you want to fix this, you should rather allow the entry height to expand if there is too much data to it (min-height instead of heigh or something)

I tried with height but its still overlapping when the theme is for dyslexia. But maybe i missed smth. Will try some more

**Comment by jancborchardt** [comment]
Yep, on the 3rd screenshot the 2 lines of text should be vertically aligned with the icon on the left (that is they should be moved up a bit).

**Comment by GretaD** [comment]
> The 3rd screenshot looks odd.
> We should not change the spacing between entries if it's not needed :)
> 
> If you want to fix this, you should rather allow the entry height to expand if there is too much data to it (min-height instead of heigh or something)

Never mind, you are totally right, in the screenshot I have also edited the element for "add to a project" which is in another repo. Thats why was not working. <<'hidesbelowthedesk'>>

smallscreen1

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
It looks good, except that the "Add to a project" text should not be maxcontrast grey, but full text color just like the "Internal link". :)

**Comment by skjnldsv** [comment]
@jancborchardt this might be for https://github.com/juliushaertl/nextcloud-vue-collections/ :)

**Comment by GretaD** [comment]
> @jancborchardt this might be for https://github.com/juliushaertl/nextcloud-vue-collections/ :)

yes, and PR is here [274](https://github.com/juliushaertl/nextcloud-vue-collections/pull/274) (to be fixed the margin :) )

**Pull request merged**
