### PR TITLE
fix(share): Send correct share attributes upon share creation

### LINKED ISSUE #44131: [Bug]: Share settings not persisted on new shares
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Sometimes (depending on the options) items set while creating a new share won't be respected and the share would be created with a different set of defaults.

#### Screencast

1. Visit share menu on particular file and select user to share with
2. Uncheck allow downloads
3. Set custom permission (allow re-sharing)

https://github.com/nextcloud/server/assets/14317775/3f19e4f8-58bf-47c9-82ac-a1b82e9cfd92

### Expected behavior

New share should be created with whatever settings the user sets upon creation

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
- Send correct share attributes (`share.attributes`) to server upon creation.
- Delete parts of code that create or reference, `share.hasDownloadPermission` (Not required by Share API)

Resolves : https://github.com/nextcloud/server/issues/44131

| Before | After |
| --------- | ------ |
| Screenshot from 2024-03-26 13-58-24 | Screenshot from 2024-03-26 13-58-00 |

### CODE REVIEW

**Review by susnux — APPROVED** [review]
makes sense

**Review by emoral435 — APPROVED** [review]
LGTM!

**Review by Altahrim — APPROVED** [review]

**Pull request merged**
