### PR TITLE
always allow moving mountpoints inside the same mountpoint

### LINKED ISSUE #13451: Rename shared file within read-only external storage fails with error
### Steps to reproduce
1. have userA and userB
2. create an external storage mount that is read-only, does not have any files and is mounted to `/` for userB
3. as userA create a file `foo.txt` and share it with userB
4. as userB try to rename the received shared file `foo.txt` to `bar.txt`

### Expected behaviour

* file should be renamed

### Actual behaviour

* there is an error that says "there is not file 'foo.txt'" and the file is removed from the file list
* after a reload the file `foo.txt` is still there.

cc @icewind1991 @rullzer

### PR DESCRIPTION
**Pull request by icewind1991**
even if that mountpoint isn't normally a valid target for moving mounts into

Fixes #13451

### CODE REVIEW

**Comment by icewind1991** [comment]
Fixes #13451

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]
:rocket: :elephant:

**Review by MorrisJobke — APPROVED** [review]
Retested and still works 👍

**Pull request merged**
