### PR TITLE
Don't call apc_delete_file and apc_clear_cache anymore

### PR DESCRIPTION
**Pull request by kesselb**
There is no apc for PHP7+ so there is no need to check if exist.
accelerator_reset looks even more ancient.

https://en.wikipedia.org/wiki/List_of_PHP_accelerators#Compatibility_chart

Only used by `writeData` (e.g. some config value changed). There is no need to backport it.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I would say: remove both methods and move them to `OC\Config::writeData`.

**Comment by danielkesselberg** [comment]
> I would say: remove both methods and move them to `OC\Config::writeData`.

Sounds good. 

> Returns TRUE if the opcode cache for script was invalidated or if there was nothing to invalidate, or FALSE if the opcode cache is disabled. 

https://secure.php.net/manual/en/function.opcache-invalidate.php

```
		if (function_exists('opcache_invalidate')) {
			@opcache_invalidate($this->configFilePath, true);
		}
```
opcache_invalidate returns false if opcache is disabled and there is no need to call opcache_reset right? So above should do the trick. Not sure if we need to call opcache_reset somewhere.

**Review by MorrisJobke — APPROVED** [review]
Tested and work

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/local/bin/phpunit/php-code-coverage/Driver/Xdebug.php on line 86
```

but only in one test -> let's merge it and see if this is happening again.

**Pull request merged**
