### PR TITLE
fix: restore AppsSlideToggle feature

### LINKED ISSUE #1199: `Activity Settings` button does not open settings menu
### Steps to reproduce
1. Install, configure and activate activities app
2. Open settings app from dashboard and click on "Activity Settings" (Check bottom left)

### Expected behaviour
Should open activity settings menu

### Actual behaviour
Does nothing

**Operating system**: Ubuntu 22

**Web server:** Apache2

**Database:** PostgresSQL

**PHP version:** PHP 8.0.28

**Nextcloud version:** Nextcloud Hub 5 (28.0.0 dev)

### LINKED ISSUE #38981: [Bug]: Regression in apps using data-apps-slide-toggle for settings toggle button
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The settings can't be opened anymore some apps with NextCloud 27 (and newer). In apps that use the data-apps-slide-toggle attribute for implementing the settings toggle button the settings button doesn't work anymore.
Affects at least the News (https://github.com/nextcloud/news/issues/2242) and Activity (https://github.com/nextcloud/activity/issues/1199) apps.

The issue has been introduced in https://github.com/nextcloud/server/pull/36534, which removed the code handling the data-apps-slide-toggle attribute. This attribute is still documented for NextCloud 27 (https://docs.nextcloud.com/server/27/developer_manual/html_css_design/navigation.html#settings) so it was probably removed unintentionally and should be added back.

This is the code that needs to be added back:
- https://github.com/nextcloud/server/pull/36534/files#diff-ef8ad78d200f5a9cb815161aa620ca6ef324f9c5d9cd1453ac72bb9447174fe8
- https://github.com/nextcloud/server/pull/36534/files#diff-3c9d8a8e67f44448736aac4deec4137721dff26ad5deb9c885518b43e410f66e

### Steps to reproduce

1. Install news (beta) or activity app on NextCloud 27
2. Click the settings button in the left bottom corner
3. -> nothing happens

### Expected behavior

When clicking the settings button, the settings should open.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/38981
Fix https://github.com/nextcloud/activity/issues/1199
Fix https://github.com/nextcloud/news/issues/2242

cc @AsamK

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Is `OC` not (theoretically) private API? (just asking because in this case probably those apps should migrate?)

**Comment by skjnldsv** [comment]
> Is `OC` not (theoretically) private API? (just asking because in this case probably those apps should migrate?)

Those apps should indeed migrate, but we need to properly deprecate and publish some documents with an alternative

**Review by szaimen — APPROVED** [review]
🐘

**Comment by ShGKme** [comment]
> Those apps should indeed migrate, but we need to properly deprecate and publish some documents with an alternative

@skjnldsv So, should we deprecate it in Nextcloud 29?

**Pull request merged**
