### PR TITLE
style strong correctly as semibold

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixing https://github.com/nextcloud/mail/pull/57#r79066775, please review @skjnldsv @ChristophWurst 

Also thoroughly check other aspects of Nextcloud @nextcloud/designers ;)

### CODE REVIEW

**Comment by raghunayyar** [comment]
Can you put this style along with the above elements like (p,a etc.)
This makes it easier to locate. Currently it is hidden in between ids and classes.
Works well otherwise.

**Comment by raghunayyar** [comment]
(Closed by mistake)

**Comment by jancborchardt** [comment]
Where are the above elements like you mentioned? I of course also checked for that but they do not exist in their raw form. :)

**Comment by MorrisJobke** [comment]
> Can you put this style along with the above elements like (p,a etc.)
> This makes it easier to locate. Currently it is hidden in between ids and classes.
> Works well otherwise.

Those are the reset styles. So grouping it there makes no sense.


👍 for this

**Review by MorrisJobke — APPROVED** [review]

**Comment by jancborchardt** [comment]
So apparently this is not needed after all because it works without it. Closing hence

**Pull request closed without merging**
