### PR TITLE
ignore readonly flag for directories

### LINKED ISSUE #23462: Write access to external SMB folders with flag "Read-Only" not possible
After an upgrade from nextcloud18 to version 19.0.3 it is no longer possible to save files in SMB directories (external storage) flagged with the "Read-Only" DOS attribute.

Even though this sounds like expected behaviour, it actually is a bug and should be changed.

 
> Unlike the Read-only attribute for a file, the Read-only attribute for a folder is typically ignored by Windows, Windows components and accessories, and other programs. For example, you can delete, rename, and change a folder with the Read-only attribute by using Windows Explorer.

Reference: http://support.microsoft.com/kb/326549

 
**Affected Nextcloud version:** 19.0.3, 19.0.4, 20.0.0

### PR DESCRIPTION
**Pull request by icewind1991**
see http://support.microsoft.com/kb/326549

Fixes #23462

### CODE REVIEW

**Review by blizzz — APPROVED** [review]
:elephant:

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
