### PR TITLE
ci: pin setup-php to avoid a regression

### PR DESCRIPTION
**Pull request by blizzz**
Temporarily, until https://github.com/shivammathur/setup-php/issues/743 is solved.

Those files are not (at least not all :sweat_smile:) distributed via our workflow-templates.

### CODE REVIEW

**Review by SystemKeeper — APPROVED** [review]

**Comment by szaimen** [comment]
Lint php-cs apparently alao needs a pinning...

**Comment by szaimen** [comment]
Apparently https://github.com/shivammathur/setup-php/issues/743 is now already fixed

**Comment by solracsf** [comment]
Fixed at https://github.com/shivammathur/setup-php/releases/tag/2.25.4

**Comment by skjnldsv** [comment]
We still should pin as security measure. 
We're doing it in the templates too

**Review by skjnldsv — APPROVED** [review]

**Comment by szaimen** [comment]
So merge?

**Pull request merged**
