### PR TITLE
Fix getDirectoryContent implementation for Jail wrapper

### PR DESCRIPTION
**Pull request by icewind1991**
:see_no_evil:

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
:elephant:

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
CI says no

**Comment by icewind1991** [comment]
> CI says no

Fixed

**Comment by rullzer** [comment]
backports?

**Comment by icewind1991** [comment]
I don't think this needs backports, the api it fixes only exists in 19 iirc

**Pull request merged**
