### PR TITLE
Make possible to focus grid/list view toggle via keyboard

### PR DESCRIPTION
**Pull request by jancborchardt**
Needs help from @nextcloud/javascript to actually make the toggle also work on pressing enter when focused. :)

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by jancborchardt** [comment]
> Needs help from @nextcloud/javascript to actually make the toggle also work on pressing enter when focused. :)

**Comment by skjnldsv** [comment]
Hum, actually this is the wrong way to go.
The label should not receive the focus on keyboard nav.
The checkbox should. That way you don't loose the element indicator on screen readers and you get the default behaviour everywhere :)

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Hum, actually I think this is the wrong way to go.
The label should not receive the focus on keyboard nav.
The checkbox should. That way you don't loose the element indicator on screen readers and you get the default behaviour everywhere :)

**Comment by jancborchardt** [comment]
@skjnldsv tried giving the checkbox the tab focus, but it seems to conflict with our custom checkboxes. What would your approach be?

**Comment by skjnldsv** [comment]
> tried giving the checkbox the tab focus

But the checkbox should already have the focus, right? Since this is a hidden and not display:none element?
If you're talking about the focus visual feedback of the label, then I guess there is a css issue?  :thinking:

**Comment by jancborchardt** [comment]
> > tried giving the checkbox the tab focus
> 
> But the checkbox should already have the focus, right? Since this is a hidden and not display:none element?
> If you're talking about the focus visual feedback of the label, then I guess there is a css issue? thinking

Please test. :) It does not receive the focus at all at the moment.

**Comment by skjnldsv** [comment]
Nice catch!
This needs to be removed indeed:
https://github.com/nextcloud/server/blob/b6376b7bd601607d76d8e73ab44fd9b04afd5db5/apps/files/css/files.scss#L1084-L1086

**Comment by rullzer** [comment]
So 17 or 18?

**Comment by jancborchardt** [comment]
I would say 17 since it fixes the accessibility of an essential part of the software. As said, needs JS help. @skjnldsv?

**Comment by skjnldsv** [comment]
> As said, needs JS help

No, only what is mentioned on my comment.
Nothing related to js here :)

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Here, can you review @jancborchardt :)

**Comment by jancborchardt** [comment]
Nice, this works! :)

The only thing is that the toggle is focused _before_ the home and upload icons in the controls bar? This seems strange and it should rather be between the upload button and the Recommendations.

**Comment by skjnldsv** [comment]
> The only thing is that the toggle is focused _before_ the home and upload icons in the controls bar? This seems strange and it should rather be between the upload button and the Recommendations.

then we should move the input and label after the home button (in the html order)

**Comment by rullzer** [comment]
Lets fix that separatly so this at least is in

**Pull request merged**
