### PR TITLE
[11] Do not connect to database before creating it

### PR DESCRIPTION
**Pull request by enoch85**
Backport of https://github.com/nextcloud/server/pull/2670/files to stable 11

 **Signed-off-by: Daniel Hansson <daniel@techandme.se>**

### CODE REVIEW

**Comment by nickvergessen** [comment]
Missing sign-off

**Comment by enoch85** [comment]
@nickvergessen Sign-off?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by enoch85** [comment]
@nickvergessen --^

**Comment by nickvergessen** [comment]
Fixed both PRs

**Review by rullzer — APPROVED** [review]

**Pull request merged**
