### PR TITLE
Add self-test for files_external:notify

### PR DESCRIPTION
**Pull request by icewind1991**
Gives users that warm feeling in their hart with the knowledge that everything will be OK

self-test

- Add some files that I missed with #2676 :see_no_evil: 
- Changed to a more powerful notify mechanism that allows for non-blocking ways to get detected changes
- Adjusted the notify command to use said mechanism
- Added self-test to the notify command
- Added unit tests to the smb notify implementation

The self-test works by triggering some test changes on the smb share while listening and checking that we got all the notifications we expect.

### CODE REVIEW

**Comment by rullzer** [comment]
@icewind1991 failing tests (missing since annotation at least it seems)

**Comment by rullzer** [comment]
Still CI is not happy

**Comment by icewind1991** [comment]
@rullzer all happy

**Comment by MorrisJobke** [comment]
Needs a rebase

**Comment by icewind1991** [comment]
rebased

**Review by blizzz — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
