### PR TITLE
add twofactor_backupcodes to l10n

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @christophwurst @rullzer @lukasreschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
On the next transifex run this will automatically upload the twofactor_backupcodes strings to transifex

**Comment by ChristophWurst** [comment]
:+1: thx

**Comment by rullzer** [comment]
LGTM

**Comment by MorrisJobke** [comment]
Ummm what?!?!

```
$ NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
Using PHP executable /usr/bin/php
Parsing all files in lib/public for the presence of @since or @deprecated on each method...

Using database oc_autotest
Setup environment for sqlite testing on local storage ...
Installing ....
Nextcloud is not installed - only a limited number of commands are available
creating sqlite db
Nextcloud was successfully installed
Testing with sqlite ...
No coverage
/usr/local/bin/phpunit --configuration phpunit-autotest.xml --exclude-group DB --log-junit autotest-results-sqlite.xml  
PHP Fatal error:  Call to undefined method Test\Share20\ManagerTest::createMock() in /drone/src/github.com/nextcloud/server/tests/lib/Share20/ManagerTest.php on line 160
[info] build failed (exit code 255)
```

the very first PHP unit test crashes?!? ... I will restart it. Lets see :)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/1242 was merged 20mins ago, maybe that is causing it

**Comment by MorrisJobke** [comment]
> the very first PHP unit test crashes?!? ... I will restart it. Lets see :)

cc @rullzer

**Comment by MorrisJobke** [comment]
> cc @rullzer

Maybe we revert the changes in .drone.yml and retest everything.

**Comment by MorrisJobke** [comment]
I rebased on current master. Maybe that is the cause.

**Pull request merged**
