### PR TITLE
Handle long dav property paths by hashing them

### PR DESCRIPTION
**Pull request by icewind1991**
Alternative to extending the column (#18126).

Even ignoring the migration problems with extending the problem, we then run into issues where we can't have an index on long string columns, which would require adding a separate `path_hash` column to query on.

Since we don't actually ever query the path from the table and only use it for searching, simply storing only the hash works just fine.

PR includes

- Getting rid of a nearly duplicate version of the custom properties backend
- Make the tests run against a real DB, not just expect specific queries
- Extend the tests to cover more code paths
- Hash paths when they are to long to store

### CODE REVIEW

**Review by georgehrke — CHANGES_REQUESTED** [review]
This breaks custom properties for CalDAV (and probably CardDAV as well) for me:

To reproduce, just open the calendar app and click a calendar to hide it. When reloading, it should still be hidden, but it's not.

**Comment by georgehrke** [comment]
Neither [Calendar](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Calendar.php) nor [AddressBook](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CardDAV/AddressBook.php) are extending [Node](https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/Node.php)

**Comment by icewind1991** [comment]
switch to `INode`

**Comment by icewind1991** [comment]
nevermind `INode` doesn't have `getPath` switched back to just using the path

**Comment by icewind1991** [comment]
cc @georgehrke @rullzer

**Review by georgehrke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
Lets do this!

**Pull request merged**
