### PR TITLE
feat(files): Allow more than 50 favorite views

### LINKED ISSUE #42059: [Bug]: Favorites in Files navigation not expandable anymore
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Expanding the favorites folders does not work:
I’m not entirely sure what causes this though. I noticed that the "Conduct" folder is duplicated, once as my own folder and once as a share, if it has something to do with that?
image

### Steps to reproduce

1. Have a bunch of favorites
2. Expect that you can expand them in the left navigation
3. The expander does not show

### Expected behavior

For few folders it works fine:
image

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Our cloud.nc.com
```

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Resolve #42059

Technically this is a feature but could also be considered a fix. Favorites were being loaded with a hardcoded limit https://github.com/nextcloud/server/blob/c3ad469750b195f91a8c7d1a05f4d696e45f6182/apps/files/lib/Activity/Helper.php#L17 of 50, so once a user had >=50 favorites none would be loaded. To fix this we no longer block page load with the server-side retrieval and load them from the frontend instead.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Nice! Fix, cleanup and semi-feature :smile:

**Review by skjnldsv — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Thanks for fixing this!

**Comment by susnux** [comment]
For 29: https://github.com/nextcloud/server/pull/53643

**Pull request merged**
