### PR TITLE
remove unneeded getDirectoryContent when getting share types for a folder

### PR DESCRIPTION
**Pull request by icewind1991**
Saves 4 queries plus 1 for every receiving share in the folder

cc @rullzer @MorrisJobke

### CODE REVIEW

**Comment by rullzer** [comment]
Failing tests

**Comment by icewind1991** [comment]
> Failing tests

All fixed

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
For me it saved 8 instead of 7 queries, but I'm fine and it still works 👍

**Pull request merged**
