### PR TITLE
MySQL 8.0+ and MariaDB 10.3+ are large prefix and barracuda by default

### LINKED ISSUE #10163: db:convert-mysql-charset and MariaDB 10.3
Dear devs,

I've tried to use `occ db:convert-mysql-charset` with MariaDB 10.3. MariaDB 10.3 doesn't know global variables like `innodb_large_prefix` and `innodb_file_format` because they were removed and deprcated since MariaDB 10.2. These settings are default and hardcoded in MariaDB 10.3. 

So `db:convert-mysql-charset` fails to run with message 
"The database is not properly setup to use the charset utf8mb4.
For more information please read the documentation at https://docs.nextcloud.com/server/13/go.php?to=admin-mysql-utf8mb4"

`db:convert-mysql-charset` needs to check the db server's version. MariaDB 10.3 is ready to use utf8mb4.

### Steps to reproduce
1. install NC without utf8mb4 support. Use MariaDB 10.3
2.  `occ db:convert-mysql-charset` 

### Expected behaviour
Database is converted to utf8mb4

### Actual behaviour
convert fails

Kind regards
Timm :-)

### PR DESCRIPTION
**Pull request by nickvergessen**
MySQL docs has those removed: https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html
For MariaDB we got a report

Fix #10163

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Makes sense

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen To backport or not to backport?

**Comment by nickvergessen** [comment]
Since it would install without utf8mb4 support, I would backport it.

**Comment by MorrisJobke** [comment]
> Since it would install without utf8mb4 support, I would backport it.

Could you prepare the PR?

**Pull request merged**
