### PR TITLE
Allow to skip data dir permission checks by config

### PR DESCRIPTION
**Pull request by blizzz**
Solves #3245

@jarofgreen @tobru @tilosp @darkneo29 can you confirm?

### CODE REVIEW

**Comment by karlitschek** [comment]
nice 👍 please also backport

**Comment by darkneo29** [comment]
Does backport mean work on existing installs?

**Review by icewind1991 — APPROVED** [review]

**Review by tilosp — APPROVED** [review]
Works on docker for windows

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
Let me do the backport

**Comment by MorrisJobke** [comment]
Backport is in #7362

**Comment by jospoortvliet** [comment]
@darkneo29 backporting means porting the code back to older releases. So this was for master, if you want it on 12, it has to be turned into a patch that applies there... Sometimes trivial, sometimes near impossible 💃

**Comment by darkneo29** [comment]
Need a hand if possible.  Reinstalled Nextcloud and added 'check_data_directory_permissions' => true, to line 39 on my config.php file.  same error...

**Comment by jarofgreen** [comment]
@darkneo29 I don't think it's been released into V12 yet. Looks like it'll be in V12.0.5.

**Pull request merged**
