### PR TITLE
Limit parameter count per query in Cache.removeChildren

### LINKED ISSUE #25732: php occ files:scan exceeds maximal number of parameters while deleting files with PostgreSQL
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Many files ((incl. previews)
2. Run php occ files:scan

### Expected behaviour
The filecache is cleaned up.

### Actual behaviour
I'm getting this exception:

```
Exception during scan: An exception occurred while executing 'DELETE FROM "oc_filecache" WHERE "parent IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  
… 1MB of query …
SQLSTATE[HY000]: General error: 7 number of parameters must be between 0 and 65535
#0 /srv/nc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /srv/nc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(149): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /srv/nc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1071): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM "oc...', Array)
#3 /srv/nc/lib/private/DB/Connection.php(222): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM "oc...', Array, Array)
#4 /srv/nc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(209): OC\DB\Connection->executeUpdate('DELETE FROM "oc...', Array, Array)
#5 /srv/nc/lib/private/DB/QueryBuilder/QueryBuilder.php(217): Doctrine\DBAL\Query\QueryBuilder->execute()
#6 /srv/nc/lib/private/Files/Cache/Cache.php(591): OC\DB\QueryBuilder\QueryBuilder->execute()
#7 /srv/nc/lib/private/Files/Cache/Cache.php(537): OC\Files\Cache\Cache->removeChildren(Object(OC\Files\Cache\CacheEntry))
#8 /srv/nc/lib/private/Files/Cache/Scanner.php(273): OC\Files\Cache\Cache->remove('files_encryptio...')
#9 /srv/nc/lib/private/Files/Cache/Scanner.php(460): OC\Files\Cache\Scanner->removeFromCache('files_encryptio...')
#10 /srv/nc/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren('', true, 3, 255, true, 0)
#11 /srv/nc/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanChildren('', true, 3, 255, true)
#12 /srv/nc/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan('', true, 3)
#13 /srv/nc/apps/files/lib/Command/Scan.php(152): OC\Files\Utils\Scanner->scan('/frlan', true, NULL)
#14 /srv/nc/apps/files/lib/Command/Scan.php(208): OCA\Files\Command\Scan->scanFiles('frlan', '/frlan', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#15 /srv/nc/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /srv/nc/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /srv/nc/apps/bookmarks/vendor/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /srv/nc/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /srv/nc/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /srv/nc/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /srv/nc/console.php(100): OC\Console\Application->run()
#22 /srv/nc/occ(11): require_once('/srv/nc/console...')
#23 {main}
```

### Server configuration

**Operating system:**

Debian Buster

**Web server:**

--

**Database:**

PostgrSQL 

**PHP version:**

PHP 7.3.x

**Nextcloud version:** (see Nextcloud admin page)

20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>No errors have been found.</summary>

``
</details>

**List of activated apps:**

```
<details>
<summary>Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - apporder: 0.11.0
  - bookmarks: 4.1.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - camerarawpreviews: 0.7.10
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - cookbook: 0.8.1
  - dashboard: 7.0.0
  - dav: 1.16.2
  - event_update_notification: 1.2.0
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_external: 1.11.1
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - firstrunwizard: 2.9.0
  - gpxpod: 4.2.6
  - integration_discourse: 0.0.9
  - integration_github: 0.0.20
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - metadata: 0.12.0
  - music: 1.0.2
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - previewgenerator: 3.1.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - socialsharing_facebook: 2.1.0
  - socialsharing_twitter: 2.1.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - checksum
  - encryption
  - files_automatedtagging
  - files_readmemd
  - files_videoplayer
  - gpxedit
  - theming
  - user_ldap</summary>
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
--
**Operating system:**
--
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by vijfhoek**
Fixes #25732 by limiting the amount of IDs in `Cache.removeChildren`'s `IN` clauses to ~2048~ 1000. 

~This number was determined by the reported (but untested by me) parameter limit of mssql being 2100 (which way under the parameter limits of the other database engines), rounding it down to the next power of 2 to provide a nice safety margin.~ 1000 was used [elsewhere](https://github.com/nextcloud/server/pull/27187) in the code, so that was used instead

In limited performance testing, this did not seem to have any negative impact on performance, with PostgreSQL benchmarks (on my laptop on battery power) even reporting a significant positive impact.

### Testing
To test this, I've first created a bunch of folders, each with a bunch of subfolders, with a single file in each of those by running the following bash command in the `data/admin/files/` directory:

```bash
for i in {0..100}; do
    mkdir -p test/spam$i/{0..1000}
    touch test/spam$i/{0..1000}/file
done
```

Now scan the directory (`php occ files:scan --all`) - this is gonna take a while, I recommend making a back-up of the database at this point to return to this state later). When this is done remove the `test` directory, then scan again.

This results in a `$parentIds` element count of over 100,000, which consistently reproduces the issue.

### CODE REVIEW

**Review by kesselb — COMMENTED** [review]
Thanks :+1: 

The query should stay outside the loop if possible. https://github.com/nextcloud/server/pull/27187 as example.

**Comment by vijfhoek** [comment]
@kesselb Ah, thanks for the example. I'll edit this to make it more alike that one

**Review by nickvergessen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
