### PR TITLE
Make OCP\IL10N strict

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by rullzer** [comment]
Mmmm errors. lets me dive into that.

**Comment by rullzer** [comment]
Only https://drone.nextcloud.com/nextcloud/server/5077/244 fails which is unrelated

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
I wonder  how many apps have the wrong usage of the parameter (not array) :see_no_evil:

**Comment by rullzer** [comment]
@nickvergessen yeah it is a shame that we can't het real function overloading. Then we could just write two.

But the phpdoc has been like this for ages. So I would say we are fine here. We just need to make sure people test their apps well ahead of 14

**Pull request merged**
