### PR TITLE
Respect user locale in natural sort comparator

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
For testing set your lang to Swedish. Then umlauts should be sorted *after* Z: ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖ

**Review by rullzer — APPROVED** [review]
sems to do the trick

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
