### PR TITLE
Add SPDX header - batch 17

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Resolves: SPDX headers on further files

## Summary

working on finalizing the REUSE work for the server repo

## TODO

- [x] compile
- [x] finish up remaining files to have headers for them
- [ ] review & merge

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

**Review by susnux — APPROVED** [review]

**Pull request merged**
