### PR TITLE
add invalidateOldTokens to IProvider interface

### PR DESCRIPTION
**Pull request by ChristophWurst**
This removes the dependency to the specific `DefaultTokenProvider` implementation.

### CODE REVIEW

**Comment by rullzer** [comment]
I think you are missing a commit.
I see no changes to the IProvider

**Comment by ChristophWurst** [comment]
> I think you are missing a commit.
> I see no changes to the IProvider

Whoops, sorry. That was not intended :see_no_evil:

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
