### PR TITLE
Ignore NoUserException for shares from ghosts

### PR DESCRIPTION
**Pull request by MorrisJobke**
* downstream of https://github.com/owncloud/core/pull/27027
* I adjusted the code a bit to the current layout and ported the comment, because one exception was already catched previously

cc @rullzer @icewind1991

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Makes sense

**Review by ChristophWurst — APPROVED** [review]
Looks good to me

**Comment by MorrisJobke** [comment]
Okay the unit tests fail ... Anybody interested in looking into it?

**Comment by MorrisJobke** [comment]
```
1) OCA\Files_Sharing\Tests\SharedStorageTest::testInitWithNonExistingUser
Undefined index: path
lib/private/Files/Cache/CacheEntry.php:70
apps/files_sharing/lib/Cache.php:63
apps/files_sharing/lib/SharedStorage.php:360
apps/files_sharing/tests/SharedStorageTest.php:580

2) OCA\Files_Sharing\Tests\SharedStorageTest::testInitWithNotFoundSource
Undefined index: path
lib/private/Files/Cache/CacheEntry.php:70
apps/files_sharing/lib/Cache.php:63
apps/files_sharing/lib/SharedStorage.php:360
apps/files_sharing/tests/SharedStorageTest.php:597
```

**Comment by MorrisJobke** [comment]
@icewind1991 Could you look into the error? Thanks

**Comment by MorrisJobke** [comment]
👍

**Comment by nickvergessen** [comment]
Should backport the relevant changes to 11:
https://github.com/nextcloud/server/issues/3110

**Comment by LukasReschke** [comment]
Downstream at https://github.com/nextcloud/server/pull/5052

**Pull request merged**
