### PR TITLE
Add autoloaders for shipped apps

### PR DESCRIPTION
**Pull request by rullzer**
For a basic tests on my dev instance this dropped the number of requests to `findFile` in the (composer) autolaoders from 8089 to 6813

6813 is still insanely high.
But baby steps.

### CODE REVIEW

**Comment by juliushaertl** [comment]
Some test failures:

### Phan

```
+ ./lib/composer/phan/phan/phan -k build/.phan/config.php
--
37 | apps/accessibility/composer/composer/autoload_real.php:26 PhanUndeclaredFunction Call to undeclared function \zend_loader_file_encoded()
38 | apps/accessibility/composer/composer/autoload_static.php:35 PhanAccessPropertyPrivate Cannot access private property \Composer\Autoload\ClassLoader::$prefixLengthsPsr4
39 | apps/accessibility/composer/composer/autoload_static.php:36 PhanAccessPropertyPrivate Cannot access private property \Composer\Autoload\ClassLoader::$prefixDirsPsr4
40 | apps/accessibility/composer/composer/autoload_static.php:37 PhanAccessPropertyPrivate Cannot access private property \Composer\Autoload\ClassLoader::$classMap
41 | apps/cloud_federation_api/composer/composer/autoload_real.php:26 PhanUndeclaredFunction Call to undeclared function \zend_loader_file_encoded()
42 | apps/cloud_federation_api/composer/composer/autoload_static.php:33 PhanAccessPropertyPrivate Cannot access private property \Composer\Autoload\ClassLoader::$prefixLengthsPsr4
43 | apps/cloud_federation_api/composer/composer/autoload_static.php:34 PhanAccessPropertyPrivate Cannot access private property \Composer\Autoload\ClassLoader::$prefixDirsPsr4
44 | apps/cloud_federation_api/composer/composer/autoload_static.php:35 PhanAccessPropertyPrivate Cannot access private property \Composer\Autoload\ClassLoader::$classMap
```

### sqlite 

```
There was 1 failure:
95 |  
96 | 1) Test\ServerTest::testQuery with data set #93 ('ThemingDefaults', '\OCA\Theming\ThemingDefaults')
97 | Service "ThemingDefaults"" did not return the right class
98 | Failed asserting that OC_Defaults Object (...) is an instance of class "\OCA\Theming\ThemingDefaults".
99 |  
100 | /drone/src/tests/lib/ServerTest.php:173
101
```

I guess the second one is because we have ThemingDefaults registered as a service in Server.php?

**Comment by MorrisJobke** [comment]
Mind to add it to the autoloader test in /build?

**Comment by rullzer** [comment]
> Mind to add it to the autoloader test in /build?

It is already ;)

**Comment by rullzer** [comment]
Ok let me ripout the theming one for now...

**Review by MorrisJobke — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
