### PR TITLE
Install page design fixes

### PR DESCRIPTION
**Pull request by jancborchardt**
This fixes **Recommended apps unclear #18631**:
recommended apps hint

Also on the way found an issue with the database switcher being stuck to the left, fixed that too.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by wiswedel — APPROVED** [review]

**Comment by jancborchardt** [comment]
The drone failures seem unrelated cause the only JS code I touched was deletion?

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
I cannot see the jsunit failure locally, rebased to current master.

**Comment by jancborchardt** [comment]
@ChristophWurst @juliushaertl so we merge?

**Comment by rullzer** [comment]
https://drone.nextcloud.com/nextcloud/server/25153/1/2 passed

**Pull request merged**
