### PR TITLE
15.0.1 RC 1

### PR DESCRIPTION
**Pull request by MorrisJobke**
Changelog to 15.0.0 (#12847):
* #12961 Only run PUSH drone runs on stable15 branch
* #12963 Change doc link for 15
* #12984 Use strengthify.min on personal settings page
* #13007 Use default cursor for disabled primary buttons
* #13029 Better activities for systemtags that are removed by CLI
* #13076 Ie11 compatibility updatenotifications
* #13119 Fix exception on LDAP mapping during login
* #13123 Fix SAML Client login flow on Apple devices
* #13150 Only trust the X-FORWARDED-HOST header for trusted proxies
* #13151 Prevent special characters from breaking the file drop remote url
* #13155 0.1] allow content provider to generate new Index
* #13169 Make the footer "Get your own free account" translatable
* #13179 Use a case insensitive search for email
* #13206 Fix ie11 checkboxes
* #13209 SCSS cache buster is a combination of apps/theming/scc_vars
* #13215 Files list not rendering if user has favorites navigation unfolded
* #13218 Do not forgot to store the second displayname portion
* #13252 Add default values when parsing account data
* #13253 Fix opening search results for comments
* #13278 Fetch lastInsertId only when id null
* #13328 Add caching headers for public previews
* #13329 Unbundle user_external to release it via appstore
* #13335 Rewrite getNumberOfUnreadCommentsForFolder query
* #13349 Fix can change password check in case of encryption is enabled
* #13352 Update the CRL
* #13354 Check anonymous OPTIONS requests file in root (not in subdir)
* #13355 Re add the uploaded file list to file drops
* #13357 Returns a 404 instead of exception if app is not installed - #13088
* #13360 Transpile arrow function for ie11 compatibility
* #13361 IE fix for apps menu
* #13366 Allow URI as data for vcard PHOTO
* [files_pdfviewer#114](https://github.com/nextcloud/files_pdfviewer/pull/114) Fix PDF sidebar shown in PDF thumbnails
* [files_videoplayer#74](https://github.com/nextcloud/files_videoplayer/pull/74) Do not get the url from the download links
* [firstrunwizard#94](https://github.com/nextcloud/firstrunwizard/pull/94) Use proper slogan from theming app
* [firstrunwizard#96](https://github.com/nextcloud/firstrunwizard/pull/96) Update info.xml

Pending PRs:

* [x] #13368 Throttle with correct metadata
* [x] #13370 Fix loginflow with apptoken enter on iOS
* [x] #13372 Register and show when an LDAP user was detected as unavailable/deleted

cc @rullzer @skjnldsv @juliushaertl

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Note for myself: don't ship user_external: https://github.com/nextcloud/user_external/pull/26

**Review by blizzz — APPROVED** [review]

**Comment by MorrisJobke** [comment]
rebased to include the latest merged PRs.

**Review by violoncelloCH — APPROVED** [review]

**Comment by violoncelloCH** [comment]
@MorrisJobke why is `user_external` `v0.4` still in the current archive for 15.0.1?

**Comment by MorrisJobke** [comment]
> @MorrisJobke why is `user_external` `v0.4` still in the current archive for 15.0.1?

Because I forgot to fetch the latest release script 🙈 Let's fix this with the other fixes for 15.0.2 today.

**Comment by MorrisJobke** [comment]
Done now 😉

**Pull request merged**
