### PR TITLE
occ commands to clean up addressbook and calendar changes table

### PR DESCRIPTION
**Pull request by georgehrke**
Signed-off-by: Georg Ehrke <developer@georgehrke.com>

### CODE REVIEW

**Comment by ChristophWurst** [comment]
:ping_pong: @georgehrke could you shed some light on the progress? Are you planning on finishing this? :)

**Comment by georgehrke** [comment]
There was some issue in Sabre/DAV that needed debugging. 
Let me put it on my list for 18.

**Comment by tcitworld** [comment]
Instead of deleting synctokens globally shouldn't we delete them per calendar/addressbook (i.e keeping the last 10 for each calendar/addressbook)?

The default value of keeping 1000 tokens doesn't makes much sense depending on your number of users.

**Comment by rullzer** [comment]
I'm going to close this due to lack of activity.
Feel free to reopen if anybody wants to continue.

**Pull request closed without merging**
