### PR TITLE
replaces upsert with traditional catch

### PR DESCRIPTION
**Pull request by blizzz**
cf. https://github.com/nextcloud/server/pull/16461#issuecomment-513117204

If that's all that is necessary, we can forward port it to master actually. Also since Stretch will be around for a while. Then we undo the >=9.5 check.

### CODE REVIEW

**Comment by blizzz** [comment]
@oole  would be nice if you could check this, too

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/f889beae7eb3c55a28a6d9798a7aadfd0f2336ad/lib/private/DB/Adapter.php#L133-L144

Looks similar. Why don't you remove the child implementation?

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
We can then also revert the required postgres version to 9?

**Comment by blizzz** [comment]
> We can then also revert the required postgres version to 9?

that's against 16 now, there we didn't increase it yet.

**Comment by blizzz** [comment]
> Looks similar. Why don't you remove the child implementation?

Yes, why, I actually looked at it. You're right, we can get rid of it.

**Comment by blizzz** [comment]
Anyhow, on UCS with 9.4 it works at least in regular operation, did not come across an error case here. Let me get this done in master properly and we backport it. Messy affair, could have been solved more elegantly, sorry :-/

**Pull request closed without merging**
