### PR TITLE
Make all CalDAV PHP classes strict

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/groupware/issues/17

This caught a previously implicit cast from a Sabre parameter to a string. Upstream code was annotated so our tools can detect this earlier next time: https://github.com/sabre-io/vobject/pull/560

### CODE REVIEW

**Comment by ChristophWurst** [comment]
- [ ] BUG `DateTimeImmutable::setTimestamp(): Argument #1 ($timestamp) must be of type int, string given`

**Review by miaulalala — APPROVED** [review]
LGTM, I checked out the branch and played around in Calendar. If I should test anything specific, let me know.

**Comment by ChristophWurst** [comment]
stale

**Comment by tcitworld** [comment]
But still useful, right?

**Pull request closed without merging**
