### PR TITLE
Set etag for capabilities endpoint

### LINKED ISSUE #20693: Enhance caching capabilities for capabilities-endpoint
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

## Feature Request

The `capabilities`-endpoint () is a quiet important endpoint for nearly every app that integrates with a Nextcloud instance. It is used for applying theming, detecting active apps and supported API versions, hence it is important for clients to keep it up to date.

Though it looks like this endpoint does not support **`ETags`**. This means for 3rd party clients (e. g. Android apps) that each request transfers the complete `JSON`-response. This means that every client has to transfer (at the sample of my small cloud with only a few apps) **`3.1 kB`** each and every time a request is made.

**Describe the solution you'd like**

This is a request to implement **`ETags`** and **`If-None-Match`** headers which allow the 3rd party applications to safely cache the response and only download the payload if it is actually needed. Especially mobile applications with a limited data quota will profilt enormously.

**Describe alternatives you've considered**
Well, proceeding like now, sucking each users mobile data quota :laughing: 

**Additional context**
Sample response headers from the `capabilities`-endpoint (Missing `ETag`-Header):

```
HTTP/1.1 200 OK
Date: Mon, 27 Apr 2020 17:03:36 GMT
Server: Apache
X-Powered-By: PHP/7.3.17
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Cache-Control: no-cache, no-store, must-revalidate
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self'
Feature-Policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
Set-Cookie: oc_sessionPassphrase=xxxxxx; path=/; secure; HttpOnly
Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
Set-Cookie: ocqot8q2lp2m=g89qbvr49l7ei9grsfc752isdq; path=/; secure; HttpOnly
Set-Cookie: cookie_test=test; expires=Mon, 27-Apr-2020 18:03:36 GMT; Max-Age=3600
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
Content-Length: 3126
Content-Type: application/json; charset=utf-8
```

### PR DESCRIPTION
**Pull request by kesselb**

### CODE REVIEW

**Comment by rullzer** [comment]
Lets do this early in 20. And then we make it nice and solid

**Review by rullzer — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@rullzer You said "Move to 20" but you changed the milestone to 19? Merge or no merge?

**Comment by MorrisJobke** [comment]
> @rullzer You said "Move to 20" but you changed the milestone to 19? Merge or no merge?

He commented in chat, that he was thinking of a more general way, but as this is a trivial change and helps the clients, we can get it in now.

**Comment by stefan-niedermann** [comment]
Thanks everybody :)

**Pull request merged**
