### PR TITLE
Fixed grammar

### PR DESCRIPTION
**Pull request by rakekniven**
Reported at Transifex.

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Review by MichaIng — APPROVED** [review]

**Review by szaimen — APPROVED** [review]

**Comment by rakekniven** [comment]
Most times it was backported to the last three supported major versions.
This time only upcoming v23. What is the reason for?

**Comment by MichaIng** [comment]
No specific reason, I just didn't check yet whether the same string is present on older versions.

**Comment by rakekniven** [comment]
Understood.

**Comment by MichaIng** [comment]
Interestingly on NC21 this was correct: https://github.com/nextcloud/server/blob/stable21/apps/files_external/templates/settings.php#L210

Ah here is the commit: https://github.com/nextcloud/server/commit/35d978c
I guess search&replace / `sed -i` used while in this one case it was part of a sentence and hence broke grammar 😄.

**Comment by rakekniven** [comment]
Good catch

**Comment by rakekniven** [comment]
@szaimen Please be careful next time you do some `sed` action like this ;-)

**Comment by szaimen** [comment]
I was careful but didn't see this one place where it was correct ;)

**Comment by MichaIng** [comment]
As mentioned above, there are some some cases. But most are code comments, hence harmless/not visible to users 😉.

**Pull request merged**
