### PR TITLE
Specify accept argument to avatar upload input field

### PR DESCRIPTION
**Pull request by MorrisJobke**
This filters the upload input field already for images only.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by kesselb** [comment]
We also validate it on server right?

**Review by kesselb — APPROVED** [review]

**Comment by rullzer** [comment]
> We also validate it on server right?

of course

**Comment by MorrisJobke** [comment]
> We also validate it on server right?

Yep - it's just for the file picker.

**Pull request merged**
