### PR TITLE
#1953 add can to subshare options

### PR DESCRIPTION
**Pull request by hechi**
@jancborchardt i hope this was what you wanted :)

### CODE REVIEW

**Comment by rullzer** [comment]
Nice stuff :+1: 

To get this in you need to sign-off on your commits (see https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work)

To do this run: `git commit --amed --sign-off` and force push.

**Comment by rullzer** [comment]
@hechi ping :) please sign off your commit so we can merge this :wink:

**Comment by jancborchardt** [comment]
@hechi yes, looks perfect, thanks a lot! :) Please sign the commit – easy as described by @rullzer and then we can get it in :)

:+1:

**Comment by LukasReschke** [comment]
Added the sign-off.

**Pull request merged**
