### PR TITLE
log version number in each log line

### PR DESCRIPTION
**Pull request by MorrisJobke**
Makes it a lot easier to analyze log files, because then you see if the log was fixed with a recent version or was caused by a recent version for example.

cc @nickvergessen @LukasReschke @schiessle @blizzz

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]
Good stuff :)

**Comment by LukasReschke** [comment]
LGTM

**Comment by blizzz** [comment]
Personally, I don't like it, it's an excuse for doing proper bug reports. If version is missing, then other necessary information is probably missing, too, and you'd need to ask for other stuff anyway.

**Comment by LukasReschke** [comment]
> Personally, I don't like it, it's an excuse for doing proper bug reports. If version is missing, then other necessary information is probably missing, too, and you'd need to ask for other stuff anyway.

It's also helpful in case you want to quickly take a look in your log monitoring systems when an error appeared and on what versions :)

… not really super awesome to always have to look up when one updated etc…

**Comment by nickvergessen** [comment]
I can see the point, but I don't really like to invoke yet another class when writing a log.

**Comment by LukasReschke** [comment]
> I can see the point, but I don't really like to invoke yet another class when writing a log.

IConfig is already used in that function, maybe manually read from the config version?

**Comment by MorrisJobke** [comment]
> I can see the point, but I don't really like to invoke yet another class when writing a log.

I also checked it and all it does it reads the current session. And the version is loaded anyways before. I feared also to add another dependency there, but it would really help to make looking at logs easy - especially when doing upgrade testing.

**Comment by MorrisJobke** [comment]
@blizzz @nickvergessen Yes or no? I would love to see this included.

**Comment by MorrisJobke** [comment]
Maybe others also have an opinion on this? @schiessle @rullzer @icewind1991

**Comment by nickvergessen** [comment]
I'm okay, when we use `$config->getValue('version')` so no session stuff is called, etc.

**Comment by MorrisJobke** [comment]
> I'm okay, when we use $config->getValue('version') so no session stuff is called, etc.

Done :)

**Comment by nickvergessen** [comment]
👍

**Comment by MorrisJobke** [comment]
stable10: #1646 
stable9: #1647

**Pull request merged**
