### PR TITLE
Fix core depending on theming app

### LINKED ISSUE #29676: [23.0.0 RC1] Upgrade fails if theming app is disabled
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Start with NC 22.2.1.2
2. Disable theming app
3. Attempt to update to NC 23.0.0 RC1 via beta channel

### Expected behaviour
Update succeeds.

### Actual behaviour
Update fails with:
```
2021-11-12T01:59:26+01:00 Checking for update of app ransomware_protection in appstore
2021-11-12T01:59:26+01:00 Checked for update of app "ransomware_protection" in App Store
2021-11-12T01:59:26+01:00 OCP\AppFramework\QueryException: Could not resolve defaults! Class defaults does not exist
2021-11-12T01:59:26+01:00 Update failed
```
Luckily trying the repair step finally gave the hint that the disabled theming app is the reason, so I was able to finish the upgrade by enabling the theming app:
```
# ncc maintenance:repair
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

In SimpleContainer.php line 100:

  Could not resolve defaults! Class defaults does not exist


In SimpleContainer.php line 120:

  Could not resolve OCA\Theming\ThemingDefaults! Class OCA\Theming\ThemingDefaults does not exist
```

### Server configuration

**Operating system:** Debian Bookworm

**Web server:** Apache/2.4.51

**Database:** 10.5.12-MariaDB

**PHP version:** 7.4.21

**Nextcloud version:** 22.2.1.2 => 23.0.0 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

**Signing status:**
<details>
<summary>Signing status</summary>

```
all good
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - apporder: 0.13.0
  - calendar: 2.3.4
  - cloud_federation_api: 1.6.0
  - contacts: 4.0.6
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - impersonate: 1.9.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - notes: 4.1.1
  - notifications: 2.11.1
  - notify_push: 0.2.4
  - oauth2: 1.11.0
  - photos: 1.5.0
  - previewgenerator: 3.2.0
  - provisioning_api: 1.13.0
  - ransomware_protection: 1.11.0
  - settings: 1.5.0
  - spreed: 13.0.0-rc.1
  - survey_client: 1.11.0
  - tasks: 0.14.2
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - circles
  - comments
  - contactsinteraction
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - password_policy
  - privacy
  - recommendations
  - serverinfo
  - sharebymail
  - support
  - systemtags
  - text
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "micha.gnoedi.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.0.7",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "logtimezone": "Europe\/Berlin",
        "default_phone_region": "DE",
        "filesystem_check_changes": 0,
        "hashingThreads": 4,
        "hashingMemoryCost": 16384,
        "hashingTimeCost": 3,
        "trashbin_retention_obligation": "disabled",
        "versions_retention_obligation": "disabled",
        "skeletondirectory": "",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/my.domain.org\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "knowledgebaseenabled": false,
        "mysql.utf8mb4": true,
        "updater.release.channel": "beta",
        "tempdirectory": "\/mnt\/sda\/ncdata\/tmp",
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "jpeg_quality": 60,
        "app_install_overwrite": [
            "apporder",
            "calendar",
            "impersonate",
            "ransomware_protection",
            "contacts",
            "spreed",
            "notify_push",
            "previewgenerator",
            "tasks"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
none
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"jwts8GRid68oBR2Z2G6O","level":3,"time":"2021-11-12T02:01:48+01:00","remoteAddr":"192.168.1.10","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/core/ajax/update.php?requesttoken=PUtnxVQnU3WDEYIoppK2U%2Bi65A6Fp3J2S%2FlIoJ8LqWQ%3D%3ADgk%2B%2FBFrCwzqfeNBwPuCFJrqoX3J6hcPEpsmkOt8wiM%3D","message":"Could not resolve defaults! Class defaults does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4676.0 Safari/537.36 OPR/83.0.4232.0 (Edition developer)","version":"22.2.1.2","exception":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve defaults! Class defaults does not exist","Code":0,"Trace":[{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":161,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/Repair.php","line":189,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":292,"function":"getRepairSteps","class":"OC\\Repair","type":"::"},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":133,"function":"doUpgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/nextcloud/core/ajax/update.php","line":200,"function":"upgrade","class":"OC\\Updater","type":"->"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","Line":100,"Previous":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCA\\Theming\\ThemingDefaults! Class OCA\\Theming\\ThemingDefaults does not exist","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":161,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\ServerContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":161,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/Repair.php","line":189,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":292,"function":"getRepairSteps","class":"OC\\Repair","type":"::"},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":133,"function":"doUpgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/nextcloud/core/ajax/update.php","line":200,"function":"upgrade","class":"OC\\Updater","type":"->"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","Line":120},"CustomMessage":"Could not resolve defaults! Class defaults does not exist"},"id":"618dc03dd4d10"}
{"reqId":"jwts8GRid68oBR2Z2G6O","level":3,"time":"2021-11-12T02:01:48+01:00","remoteAddr":"192.168.1.10","user":"--","app":"updater","method":"GET","url":"/nextcloud/core/ajax/update.php?requesttoken=PUtnxVQnU3WDEYIoppK2U%2Bi65A6Fp3J2S%2FlIoJ8LqWQ%3D%3ADgk%2B%2FBFrCwzqfeNBwPuCFJrqoX3J6hcPEpsmkOt8wiM%3D","message":"\\OC\\Updater::failure: OCP\\AppFramework\\QueryException: Could not resolve defaults! Class defaults does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4676.0 Safari/537.36 OPR/83.0.4232.0 (Edition developer)","version":"22.2.1.2","id":"618dc03dd46d9"}
```
</details>

### PR DESCRIPTION
**Pull request by CarlSchwan**
This was introduced in https://github.com/nextcloud/server/commit/309354852f12ae88d5eef05d311d6ebcba8ee762
to fix a bug but I can't reproduce the bug after reverting this change.

Ideally, we would need to create an interface in OCP and cleanup OC_Defaults
instead of depending on OC_Defaults.

This needs testing of the new profile feature with this patch. 

Fix #29676

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Comment by MichaIng** [comment]
I can confirm this fixes the upgrade issue:
1. Did a fresh NC22 install
2. Disabled theming app
3. Switch to beta channel
4. Upgrade to NC23 (needed to download and install manually, as `occ update:check` and web UI didn't offer NC23 yet on beta channel 🤔)
5. Run web UI (database) upgrade
6. Reported failure
7. Applied the changes from this PR
8. Rerun web UI upgrade
9. Success

I guess in line 409:
```php
* @return string SCSS code for variables from ThemingDefaults
```
should be updated as well to
```php
* @return string SCSS code for variables from \OC_Defaults
```
as well.

The original reason for this change and the problem with it were recognised already: https://github.com/nextcloud/server/pull/28751#discussion_r729298352
Looks like it was fixed [here](https://github.com/nextcloud/guests/pull/724) already?

Just recognised another issue, as the theming settings are still shown even if the theming app is disabled. Applying any changes of course fails with following browser console errors:
<details>

```
jquery.js:9600 POST http://192.168.1.23/nextcloud/index.php/apps/theming/ajax/updateStylesheet 412 (Precondition Failed)
send @ jquery.js:9600
ajax @ jquery.js:9206
e.ajax.e.ajax @ jquery-migrate.min.js:2
C.each.C.<computed> @ jquery.js:9355
setThemingValue @ settings-admin.js?v=5e730a6d:29
(anonymous) @ settings-admin.js?v=5e730a6d:197
u @ jquery.js:3534
c @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
l @ jquery.js:3268
add @ jquery.js:3327
(anonymous) @ jquery.js:3660
e.Deferred.e.Deferred @ jquery-migrate.min.js:2
then @ jquery.js:3645
onChange @ settings-admin.js?v=5e730a6d:196
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
msg.js:86 Uncaught TypeError: Cannot read properties of undefined (reading 'message')
    at Object.finishedAction (msg.js:86)
    at Object.finishedSaving (msg.js:69)
    at Object.<anonymous> (settings-admin.js?v=5e730a6d:35)
    at l (jquery.js:3268)
    at Object.fireWith [as rejectWith] (jquery.js:3398)
    at k (jquery.js:9307)
    at XMLHttpRequest.<anonymous> (jquery.js:9548)
finishedAction @ msg.js:86
finishedSaving @ msg.js:69
(anonymous) @ settings-admin.js?v=5e730a6d:35
l @ jquery.js:3268
fireWith @ jquery.js:3398
k @ jquery.js:9307
(anonymous) @ jquery.js:9548
load (async)
send @ jquery.js:9567
ajax @ jquery.js:9206
e.ajax.e.ajax @ jquery-migrate.min.js:2
C.each.C.<computed> @ jquery.js:9355
setThemingValue @ settings-admin.js?v=5e730a6d:29
(anonymous) @ settings-admin.js?v=5e730a6d:197
u @ jquery.js:3534
c @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
l @ jquery.js:3268
add @ jquery.js:3327
(anonymous) @ jquery.js:3660
e.Deferred.e.Deferred @ jquery-migrate.min.js:2
then @ jquery.js:3645
onChange @ settings-admin.js?v=5e730a6d:196
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
jquery.js:9600 POST http://192.168.1.23/nextcloud/index.php/apps/theming/ajax/updateStylesheet 412 (Precondition Failed)
send @ jquery.js:9600
ajax @ jquery.js:9206
e.ajax.e.ajax @ jquery-migrate.min.js:2
C.each.C.<computed> @ jquery.js:9355
setThemingValue @ settings-admin.js?v=5e730a6d:29
(anonymous) @ settings-admin.js?v=5e730a6d:206
u @ jquery.js:3534
c @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
l @ jquery.js:3268
add @ jquery.js:3327
(anonymous) @ jquery.js:3660
e.Deferred.e.Deferred @ jquery-migrate.min.js:2
then @ jquery.js:3645
onChange @ settings-admin.js?v=5e730a6d:205
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
msg.js:86 Uncaught TypeError: Cannot read properties of undefined (reading 'message')
    at Object.finishedAction (msg.js:86)
    at Object.finishedSaving (msg.js:69)
    at Object.<anonymous> (settings-admin.js?v=5e730a6d:35)
    at l (jquery.js:3268)
    at Object.fireWith [as rejectWith] (jquery.js:3398)
    at k (jquery.js:9307)
    at XMLHttpRequest.<anonymous> (jquery.js:9548)
```
</details>
Enabling the theming app of course fixes it. Now I wanted to check whether it works with guest accounts, but I cannot find the way how to create a guest account 😅.

**Review by skjnldsv — APPROVED** [review]

**Comment by artonge** [comment]
A linter rule preventing usage of `use OCA\*` in core PHP files could be nice to have. Could this be possible?

**Review by artonge — APPROVED** [review]

**Comment by CarlSchwan** [comment]
> A linter rule preventing usage of `use OCA\*` in core PHP files could be nice to have. Could this be possible?

That would indeed be a good idea, but I'm not sure how feasible it is. I could read the php-cs-fixed doc

**Pull request merged**
