### PR TITLE
Modified the SQLite warning of server/settings/templates/admin/tiptri…

### PR DESCRIPTION
**Pull request by xcellardoor**
Modified the SQLite warning of server/settings/templates/admin/tiptricks.php to be more understandable and legible

### CODE REVIEW

**Comment by rullzer** [comment]
Thanks for your PR @xcellardoor!

Looks good to me. :+1: 

We do require all commits to be signed of (see https://github.com/nextcloud/server/blob/master/contribute/developer-certificate-of-origin for why).

To do so:

1. checkout your branch
2. git commit --amed -s
3. git push -f

**Comment by xcellardoor** [comment]
Hi rullzer,

I've run the commands, and signed with GPG I believe. Would you like me to submit another pull request or is this now okay?

Thanks

**Comment by rullzer** [comment]
@xcellardoor no git is smart enough :)

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@xcellardoor Thanks a lot for your contribution :) Feel free to join our IRC channel at freenode: #nextcloud-dev or just have a look at other starter issues: https://github.com/nextcloud/server/labels/starter%20issue 🙌

**Comment by xcellardoor** [comment]
I will, thank you :)

**Pull request merged**
