### PR TITLE
Reload page instead of file list when getting 401 authentification error

### PR DESCRIPTION
**Pull request by CarlSchwan**
When getting a 401 error, instead of reloading the file list and hopping we are now
authenticated, we reload the page completely. This triggers a redirection to the login
page automatically with the correct ?redirect_url= in the URL, so that once logged the
user goes back to the place they were previously.

## Test plan

1. Open file webui in two tabs
2. Logout in one of the two tabs
3. In the other tabs, try to open an folder

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by CarlSchwan** [comment]
Hmm actually this only handle the case there we are one folder deep.

**Comment by CarlSchwan** [comment]
> Hmm actually this only handle the case there we are one folder deep.

I changed that to not even checking if we are on the root directory. A 401 should be enough to detect an authentication problem.

From my local testing, 401 only happens when there is an authentication problem. 404 is when the folder is missing, 403 is when the user doesn't have access to the folder (e.g. file_accesscontrol)

**Comment by CarlSchwan** [comment]
We also need to had error handling in apps/viewer/src/services/FileInfo.js...

**Review by julien-nc — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure unrelated

**Pull request merged**
