### PR TITLE
[oc] Sync deathdate and anniversary to birthday calendar

### PR DESCRIPTION
**Pull request by rullzer**
From https://github.com/owncloud/core/pull/25655

CC: @nickvergessen @MorrisJobke @icewind1991 @LukasReschke

### CODE REVIEW

**Comment by tcitworld** [comment]
Not sure the death date of someone is something people want to see in their calendars, just saying.

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by tcitworld** [comment]
> You already added it to the contact ... and in the end you could disable this calendar

Well, maybe you just got it from somewhere else... and you still enjoy having your contacts birthdays. It was just a remark though.

**Comment by LukasReschke** [comment]
👍

**Pull request merged**
