### PR TITLE
[11] fix moving folders out of a cache jail

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #5424

I originally thought that the problem that this fixes was introduced by move optimizations in 12, thus the original backport was only to 12.

### CODE REVIEW

**Review by rullzer — CHANGES_REQUESTED** [review]
Failing tests

**Comment by icewind1991** [comment]
ci is finally happy

**Review by rullzer — APPROVED** [review]
Fine by me

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
