### PR TITLE
[stable19] LDAP: fix inGroup for memberUid type of group memberships

### PR DESCRIPTION
**Pull request by tofuSCHNITZEL**
backport for stable19 of https://github.com/nextcloud/server/pull/24402

### CODE REVIEW

**Comment by tofuSCHNITZEL** [comment]
> ### Status of [557](https://drone.nextcloud.com/nextcloud/server/557): failure

@blizzz to the rescue - I don't really understand whats going on ;) also it seems to affect the files_sharing app not LDAP?

**Comment by blizzz** [comment]
> > ### Status of [557](https://drone.nextcloud.com/nextcloud/server/557): failure
> 
> @blizzz to the rescue - I don't really understand whats going on ;) also it seems to affect the files_sharing app not LDAP?

I believe we have here an older phpunit running. The newer one makes the mocks return an empty value based on the return type hint, e.g. an empty array for arrays. The older runs just returns null. So the mocks in the tests needs to be adjusted and any important method that is call has to be made to return what is expected later on.

**Comment by tofuSCHNITZEL** [comment]
I fear I don't understand enough about these tests to fix this....

**Comment by DanScharon** [comment]
any chance to get this backport into 19?

**Comment by MichaIng** [comment]
I mark this as closed, as Nextcloud 19 won't get any further releases. For the future, this repository has a backport bot to easily create backports to any branch by simply writing a comment like:
```
/backport to stable22
```
Check out how it was used here: #27354

But in some cases it might not work as of conflicts, when the affected lines have changed between master and target branch, of course.

**Pull request closed without merging**
