### PR TITLE
Fix the Talk verification

### PR DESCRIPTION
**Pull request by ChristophWurst**
Requires #21143 

When enabling Talk verification the server expects also a new password
to be set. As we always just update one property at a time this means
the Talk verification was impossible to activate. With this patch, we
send the talk option AND the new password. If there is no new password,
the Talk option is disabled. When we finally have descriptive text on
ActionCheckbox'es we should definitely add some explanatory text for the
user. Right now this is as good as it gets. We'll have to backport to
18.

### CODE REVIEW

**Review by danxuliu — CHANGES_REQUESTED** [review]
Preventing to enable _Video verification_ if no new password is set should be applied only to mail shares. In public link shares it should be possible to enable and disable the video verification without changing the password.

Similarly, in mail shares it should be possible to disable _Video verification_ without having to change the password. Only enabling _Video verification_ should be prevented if a new password is not set.

**Comment by nickvergessen** [comment]
@danxuliu re-review, so we can backport it for 19.0.1 at least?

**Comment by danxuliu** [comment]
Although the password was sent along with _sendPasswordByTalk_ it was always the password already set, so enabling video verification in mail shares still failed (well, it does after rebasing on #21143; before it did not, but if was a bug in the server, it should have failed :-P ). To fix this now the new password is sent (provided a new one has been set; otherwise the existing one is still sent, although this only happens for link shares).

Also, in #21143 the backend was changed to require a new password also when video verification was disabled (because otherwise only the hashed version of the existing password was available, which made no sense when sent in the e-mail). This pull request was also updated to require a new password also when disabling video verification.

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Review by rullzer — APPROVED** [review]
:elephant:

**Pull request merged**
