### PR TITLE
Less ILogger

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
white page....

**Review by ChristophWurst — APPROVED** [review]

**Review by kesselb — APPROVED** [review]
Awesome :broom:

**Comment by kesselb** [comment]
I was about to ask if we could squash the commits ;)

**Comment by skjnldsv** [comment]
@nickvergessen lots of tests still have the logException

Ref failures in https://github.com/nextcloud/server/pull/27362 && https://github.com/nextcloud/server/pull/27362/commits/e22a626c5f126e2ac3b380ecb0dfda6d93d1dd86

**Comment by nickvergessen** [comment]
Weird enough if the tests then still passed 🤔

**Comment by skjnldsv** [comment]
image

**Comment by nickvergessen** [comment]
Ah.... the warnings it is....

Fixed in https://github.com/nextcloud/server/pull/27374

**Pull request merged**
