### PR TITLE
PHP 7.0 is end of life

### PR DESCRIPTION
**Pull request by MorrisJobke**
See https://secure.php.net/supported-versions.php

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

**Comment by nickvergessen** [comment]
Weeeeell , yes for master, no for backport?

**Comment by MorrisJobke** [comment]
> Weeeeell , yes for master, no for backport?

We should show it at least in 15. Also the PHP doc says so:

```php
/*
 * Whether the php version is still supported (at time of release)
 * according to: https://secure.php.net/supported-versions.php
```

**Comment by MorrisJobke** [comment]
And to clarify: this is only an entry in the setup checks of the admin settings.

**Comment by nickvergessen** [comment]
> And to clarify: this is only an entry in the setup checks of the admin settings.

Ah okay, I thought the check in base.php, fine then

**Review by nickvergessen — APPROVED** [review]

**Comment by xf-** [comment]
I'm no fan of EOL versions, but major distributions like Debian stretch provide only 7.0 and no Backport of 7.1 or 7.2. Buster will release with 7.2 or/and 7.3
https://packages.debian.org/search?keywords=php

**Comment by MorrisJobke** [comment]
> I'm no fan of EOL versions, but major distributions like Debian stretch provide only 7.0 and no Backport of 7.1 or 7.2. Buster will release with 7.2 or/and 7.3

Nevertheless we need to tell administrators that they run a version that is not officially supported. I don't want to start a discussion about distributions and that they maybe back port fixes. This is about giving the admin the opportunity to plan for the future and see where potential problems occur. We need to upgrade our dependencies as well and run into problems because they don's support PHP 7.0 anymore. (see #12021)

**Comment by MorrisJobke** [comment]
This is how it looks like:

bildschirmfoto 2018-12-04 um 16 07 37

**Review by rullzer — APPROVED** [review]

**Pull request merged**
