### PR TITLE
Svgo optimization

### PR DESCRIPTION
**Pull request by skjnldsv**
Big optimisation of all svg with svgo

> Stats:
> Old size: 177.536Ko
> New size: 101.352Ko
> **Size reduced by: 44,49%**

Not sure if really necessary. Did it in 30sec. 

```
find -name "*.svg" -exec svgo {} \;
```

Only the /core/img/desktopapp.svg is not worth optimising.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Same here, to make tests pass, see https://github.com/nextcloud/server/pull/1535#issuecomment-249822424

**Comment by skjnldsv** [comment]
@nickvergessen Rebased with signature :)

**Comment by MorrisJobke** [comment]
I tested this especially with Firefox because there we had the biggest problems with SVGs. Works fine :+1:

**Comment by LukasReschke** [comment]
Clicked around in Safari and all seemed fine 👍

**Review by LukasReschke — APPROVED** [review]

**Comment by jancborchardt** [comment]
@skjnldsv this caused big issues with lots of source files: https://github.com/nextcloud/server/issues/4076 it would be good if we can revert that and use Scour instead of Svgo, as we did so far without issue.

**Pull request merged**
