### PR TITLE
Fit newFileMenu to css guidelines

### PR DESCRIPTION
**Pull request by skjnldsv**
Following #3114 

Two bugs to fix:
- [x] Why is the label link to the input not working?
- [x] Why is the new Folder button not working?

@nextcloud/designers please review

### CODE REVIEW

**Comment by skjnldsv** [comment]
Before/After
capture d ecran_2017-01-21_20-10-05
capture d ecran_2017-01-21_20-10-32

**Review by MorrisJobke — DISMISSED** [review]
If the input field for new file/folder is not hovered anymore it will hide:

bildschirmfoto 2017-01-21 um 17 17 01

**Comment by MorrisJobke** [comment]
> Works fine with #3187. :)

It's still there. Let's wait for #3187 to be in and then we can continue this one here.

**Comment by MorrisJobke** [comment]
I rebased this because #3187 was merged.

**Comment by skjnldsv** [comment]
No conflicts? Lucky you! 😉

**Comment by MorrisJobke** [comment]
As said: the weird hidden on hover is still there 😢

**Comment by skjnldsv** [comment]
😕 
kazam_screencast_00001

**Review by MorrisJobke — APPROVED** [review]
Works now fine 👍 (I guess some caching issues before, but I really refreshed hard multiple times)

**Review by LukasReschke — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> Before/After
> capture d ecran_2017-01-21_20-10-32 capture d ecran_2017-01-21_20-10-05

The top left corner is not rounded. @skjnldsv could you please fix that? :-)
Also the menu seems to be broken in Gallery (now)

**Comment by skjnldsv** [comment]
@ChristophWurst I saw that for the gallery. Needed to be fixed in the gallery app. On it! :)

**Pull request merged**
