### PR TITLE
Be sure to get the jailed path if the storage is a jail

### LINKED ISSUE #583: Cache can not get the parent
# Steps

1. Create a group folder
2. Create a folder inside this group folder and apply a tag `folder`
3. Create an automated tagging rule
    + If file (or parent) is tagged with `folder` apply tag `file`

4. Upload a file in the tagged folder from 2.
5. Expect the file to be tagged with `file`, but it's not :boom: 

The problem is that
https://github.com/nextcloud/server/blob/738730f7b280884cc89c272bbab2a21caa8a24dd/apps/workflowengine/lib/Check/FileSystemTags.php#L156

Can not find the parents.
Due to the CacheJail, you end up with `__groupfolders/1/__groupfolders/1/folder` in https://github.com/nextcloud/server/blob/0487144b2679f83f9a6b59b55561af062f692836/lib/private/Files/Cache/Wrapper/CacheWrapper.php#L148

### PR DESCRIPTION
**Pull request by rullzer**
Fixes https://github.com/nextcloud/groupfolders/issues/583

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Works for shares and group folders

**Review by juliusknorr — APPROVED** [review]
Tested and works.

**Comment by juliushaertl** [comment]
I've amended to also use the same approach in the mime type check.

**Comment by nickvergessen** [comment]
Should this then just happen outside this method and we only ever inject the jailed path?

**Comment by rullzer** [comment]
> Should this then just happen outside this method and we only ever inject the jailed path?

would make sense yes.

**Comment by nickvergessen** [comment]
Done, please re-review @rullzer @juliushaertl

**Comment by rullzer** [comment]
Perfect :)

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
