### PR TITLE
Adding custom sso for our project

### PR DESCRIPTION
**Pull request by willianm**
Hi, this is a very specific change we did on top of Release 11. We are trying to achieve single sign on by providing an encrypted token. I know the code is not good, but it can give an idea of our use case.

Basically we wanted to integrate the ldap login with an encrypted token. This way people can login seamlessly.

I don't expect you to accept this pull request, but if you are interested to know more, please let me know.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @blizzz @LukasReschke @nickvergessen for feedback

**Comment by MorrisJobke** [comment]
cc @ChristophWurst

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Interesting work.  You can likely achieve most of this by using `\OCP\Authentication\IApacheBackend` without custom adjustments. 

See also https://github.com/nextcloud/user_saml for an app that implements the IApacheBackend :)

**Comment by willianm** [comment]
Thanks Lukas, good advice. I'm going to take a look.

**Pull request closed without merging**
