### PR TITLE
Remove old perl script to update l10n files

### PR DESCRIPTION
**Pull request by MorrisJobke**
Thanks @jakobsack

### CODE REVIEW

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/travis_ci/pull/4

**Comment by nickvergessen** [comment]
Can we avoid the new folder in root?
And maybe reuse the l10n folder instead?

**Comment by MorrisJobke** [comment]
> And maybe reuse the l10n folder instead?

The idea is to drop the l10n because in all other cases (all apps out there and also all folders in the server) this holds the actual l10n stuff - except in the root of the server, which is quite cumbersome.

Also the logic of the extraction code now uses this folder as indication of the root and therefore is a lot easier to understand, because this is the only way it works and it works for all apps and the server. I will do additional tests later on this.

**Comment by nickvergessen** [comment]
Okay then ping @LukasReschke to adjust the packaging script

**Comment by MorrisJobke** [comment]
> Okay then ping @LukasReschke to adjust the packaging script

Once it is ready :)

**Comment by rullzer** [comment]
CI not happy

**Comment by MorrisJobke** [comment]
> CI not happy

I know - release script needs to be touched as well. Let me do a final test

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen This is now good to go in. Please review

**Review by ChristophWurst — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
