### PR TITLE
Kill repair step for cypress

### PR DESCRIPTION
**Pull request by kesselb**
image

PhpStorm always complains :man_shrugging:

### CODE REVIEW

**Comment by rullzer** [comment]
I guess we could also just kill that job. As it is already no longer shipped @skjnldsv

**Comment by skjnldsv** [comment]
Yep

**Review by skjnldsv — APPROVED** [review]

**Comment by kesselb** [comment]
> I guess we could also just kill that job. As it is already no longer shipped @skjnldsv

Fine by me but please take note of

> @deprecated - can be removed in 18 because this is the first version where no migration from 16 can happen

**Comment by rullzer** [comment]
@kesselb ah right...

Ok then what we should do is the same as for the avatar step
check from what version we are updating and only run it in that case.

**Comment by kesselb** [comment]
Let's kill it ;) For someone updating today from nc 15 the viewer app is already fixed. Is there any other case to consider?

**Pull request merged**
