### PR TITLE
Fix js search in undefined ocs response

### LINKED ISSUE #510: Getting message "Error creating the share" when sharing a file despite the share is created correctly
I'm getting a strange error when sharing files/folders in nextcloud 20.
On adding the share the following popup comes up:
error_creating_the_share

The JavaScript Console gives the following:
js_error

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/circles/issues/510

If the backend fail, the search cannot work on an undefined variable.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Needs a rebase

**Review by MorrisJobke — APPROVED** [review]

**Comment by skjnldsv** [comment]
Rebased

**Pull request merged**
