### PR TITLE
Allow searching for favorites

### PR DESCRIPTION
**Pull request by icewind1991**
Using

```xml
<d:eq>
     <d:prop>
          <oc:favorite/>
     </d:prop>
     <d:literal>yes</d:literal>
</d:eq>
```

As part of the search query

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@mario Is this the only change needed for the android app or is there more to come?

**Comment by mario** [comment]
@MorrisJobke I won't know until I start working on "Recently modified" and stuff like that. But maybe I can workaround it for now and not require more server changes...

**Comment by mario** [comment]
👍  - works as advertised.

**Review by mario — APPROVED** [review]

**Comment by mario** [comment]
@icewind1991 two more questions/requests:

1) Searching for shared files/folders
2) Searching by date created (uploaded?) if creationdate is the right attribute?

Would appreciate it, otherwise I have to do propfind and do it manually...

**Comment by mario** [comment]
@nickvergessen told me that creationdate isn't the right thing for no. 2 requirement. Please link me up when you get the time to relevant issue. 

I still need both somehow implemented though.

**Comment by mario** [comment]
1) So to clarify my first requirement:

 All files shared by you, with you, and by link, in a single flat list.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@mario Please open separate issues for your requests. And is this now all for the search feature? Or is there still something missing on the server side?

**Comment by mario** [comment]
@MorrisJobke I opened three relevant issues, and we'll see if it can be achieved using existing implementation or not.

**Pull request merged**
