### PR TITLE
Enable binary protocol again

### LINKED ISSUE #32541: [Bug]: Directory not available / Error loading data
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have one folder which I cannot view using the web interface (my standard user; not admin). The error messages read:

* if I like to open the directory:
[DE] Dieses Verzeichnis ist nicht verfügbar, bitte die Logdateien überprüfen oder den Administrator kontaktieren. (This directory is not available, please see log files or contact the admin.)
* if I view details:
[DE] Fehler beim Laden der Datei-Daten (Error loading file data.)

This is the folder with all shared data (using 'share_folder' option of config.php). I can access most of the data by using the direct link(s) via Shares => Shared with me. However, it is not working for all - the error message is the same as above.

Nevertheless, access is working fine if I'm using webdav - this way I can access all data. Therefore, I also noticed it just now. I can not say for sure at which version it occurred. Furthermore, this happens only for one user.

I updated the nextcloud server to version 24.0.1.0 to check if a bugfix exists but it did not help.

I did run the rescan for the user without any effect (occ files:scan USER)

I also searched and found the following page: https://help.nextcloud.com/t/after-migration-to-nextcloud-24-some-directories-will-not-be-shown-in-browser/138663 with a similar message.

### Steps to reproduce

1. See the above listed ways to get the error.

### Expected behavior

View content of the directory / details

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "URL",
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/URL\/",
        "dbtype": "mysql",
        "version": "24.0.1.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "installed": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "memcached_options": {
            "14": 120,
            "15": 120,
            "19": 120,
            "20": 120,
            "8": 120
        },
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "loglevel": 0,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": true,
        "forcessl": true,
        "asset-pipeline.enabled": true,
        "appcodechecker": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "mysql.utf8mb4": true,
        "mail_smtpauthtype": "LOGIN",
        "updater.release.channel": "stable",
        "token_auth_enforced": true,
        "tempdirectory": "\/var\/tmp\/",
        "filesystem_check_changes": 1,
        "share_folder": "\/SharedData",
        "mail_sendmailmode": "smtp",
        "migrate_guest_user_data": true,
        "app.mail.verify-tls-peer": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "default_phone_region": "DE"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - analytics: 4.2.1
  - announcementcenter: 6.3.0
  - apporder: 0.15.0
  - bookmarks: 10.3.1
  - breezedark: 24.0.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.1
  - checksum: 1.1.4
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.0
  - event_update_notification: 1.5.0
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_automatedtagging: 1.14.0
  - files_downloadactivity: 1.13.0
  - files_external: 1.16.1
  - files_fulltextsearch: 24.0.0
  - files_fulltextsearch_tesseract: 24.0.0
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.5.0
  - files_readmemd: 1.2.2
  - files_retention: 1.13.1
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - fileslibreofficeedit: 1.0.4
  - firstrunwizard: 2.13.0
  - forms: 2.5.0
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.0
  - group_everyone: 0.1.10
  - groupfolders: 12.0.0
  - groupquota: 0.1.8
  - guests: 2.2.0
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.0-beta1
  - maps: 0.1.10
  - metadata: 0.16.0
  - music: 1.5.2
  - news: 18.0.1
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - notify_push: 0.4.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - passwords: 2022.5.10
  - phonetrack: 0.7.0
  - photos: 1.6.0
  - polls: 3.7.0-beta2
  - previewgenerator: 5.0.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quicknotes: 0.7.6
  - quota_warning: 1.14.0
  - ransomware_protection: 1.13.0
  - recommendations: 1.3.0
  - richdocuments: 6.1.0
  - richdocumentscode: 21.11.402
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.1
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_nextcloud_notification: 3.4.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - user_usage_report: 1.8.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit: 1.7.0
  - browser_warning: 1.0.0
  - dropit: 0.4.0
  - encryption
  - files_trackdownloads: 1.11.0
  - flowupload: 1.1.3
  - issuetemplate: 0.7.0
  - occweb: 0.1.0
  - suspicious_login: 4.1.0
  - twofactor_admin: 3.2.0
  - twofactor_gateway: 0.19.0
  - uppush: 1.0.0
  - user_ldap: 1.9.0
  - whiteboard: 0.0.3
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
[webdav] Fatal: Exception: Error 33 interacting with memcached : A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE at <<closure>>

 0. /srv/www-extern/apps/nextcloud/lib/private/Memcache/Memcached.php line 123
    OC\Memcache\Memcached->verifyReturnCode()
 1. /srv/www-extern/apps/nextcloud/lib/private/User/DisplayNameCache.php line 67
    OC\Memcache\Memcached->set("USER ... /", "USER ... /", 600)
 2. /srv/www-extern/apps/nextcloud/lib/private/User/LazyUser.php line 55
    OC\User\DisplayNameCache->getDisplayName("USER ... /")
 3. /srv/www-extern/apps/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 379
    OC\User\LazyUser->getDisplayName()
 4. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 95
    OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 5. /srv/www-extern/apps/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 381
    Sabre\DAV\PropFind->handle("{http://ownclou ... e", Closure {})
 6. /srv/www-extern/apps/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties(Sabre\DAV\PropFind {}, OCA\DAV\Connector\Sabre\Directory {})
 7. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit("propFind", [Sabre\DAV\PropF ... }])
 8. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\DAV\Connector\Sabre\Directory {})
 9. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath("files/USER/SharedData", ["{DAV:}getlastm ... "], 1)
10. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus(Sabre\Xml\Writer ... ]}, Generator {}, false)
11. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
12. /srv/www-extern/apps/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
13. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
14. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
15. /srv/www-extern/apps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
16. /srv/www-extern/apps/nextcloud/apps/dav/lib/Server.php line 352
    Sabre\DAV\Server->exec()
17. /srv/www-extern/apps/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
18. /srv/www-extern/apps/nextcloud/remote.php line 166
    require_once("/srv/www-extern ... p")

PROPFIND /-/cloud/remote.php/dav/files/USER/SharedData
from 83.125.99.146 by USER at 2022-05-22T17:53:07+02:00
```

### Additional info

Send me a note if I should run any tests ...

### PR DESCRIPTION
**Pull request by CarlSchwan**
Fix #32541

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by CarlSchwan** [comment]
need another +1 :)

**Review by come-nc — APPROVED** [review]

**Comment by PVince81** [comment]
@CarlSchwan @blizzz the backport failed

**Comment by blizzz** [comment]
created backport, went smoothly.

**Pull request merged**
