### PR TITLE
Check for grant permission before adding database user, fixes #13628

### LINKED ISSUE #13628: Install fails if database user has no grant permission
### Steps to reproduce
1. Install Apache and MariaDB through apt
2. Create database user:
```sql
create user 'next'@'localhost' identified by 'secret';
grant all privileges on *.* to 'next'@'localhost';
flush privileges;
```
3. Create database:
```sql
create database next;
```
4. Attempt to install Nextcloud in Web browser:

Username: _[any]_

Password: _[any]_

Data directory: _[default]_

Database user: `next`

Database password: `secret`

Database name: `next`

Database host: `localhost:5432`

### Expected behaviour
Install should happen as normal, with the specified database user. Nextcloud should not attempt to add its own user if grant permission is missing.

### Actual behaviour
Error message in Web browser:

> Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user 'oc_next'@'localhost' to database 'next'

Subsequent error messages:

> Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user 'oc_next1'@'localhost' to database 'next'

`oc_next2` etc.

### Server configuration

**Operating system**: Ubuntu 16.04.5 LTS

**Web server:** Apache/2.4.18

**Database:** mysql  Ver 15.1 Distrib 10.0.36-MariaDB

**PHP version:** PHP 7.2.14

**Nextcloud version:** (see Nextcloud admin page) `53c077afc9077dcadcaf4b8ad62590fb549947b0`

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** directly from GitHub repository

### Details

This bug occurs because the database user created for Nextcloud has permission to create new users, but is not allowed to grant permissions. 

If privileges are granted `with grant option`, the install proceeds as expected (Nextcloud adds its own user):

```sql
grant all privileges on *.* to 'next'@'localhost' with grant option;
```

The bug is also described by this user: https://help.nextcloud.com/t/mariadb-refuse-me-sqlstate-hy000-1044-access-denied-for-user-oc-sylvain-to-database-nextcloud/35677

### PR DESCRIPTION
**Pull request by thomasheller**
Fixes https://github.com/nextcloud/server/issues/13628

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Test failures are unrelated.

**Review by MorrisJobke — APPROVED** [review]
Code change looks good 👍

**Comment by kesselb** [comment]
Granted `oc_admin` the permission to create a user. Work as expected (still running into the exception).

image

Can reproduce your case if `oc_admin` has the permission to read `mysql.user`. This looks more like a configuration issue? Why should `oc_admin` read `mysql.user`?

**Review by kesselb — COMMENTED** [review]
I'm not sure about this "fix". If you setup a user for nextcloud yourself (without global permissions) but grant the right to create a user and select permission for mysql.user you run into an invalid case (**and this case is fixed by this pr**). Not really related to this pr but it's questionable why there is some "create custom user, grant permission stuff" at all. Setup a database should be done before installing nextcloud. This is sysadmin stuff like setting memory limit, etc.

**Comment by thomasheller** [comment]
I referenced the bug description #13628 -- which includes a link to a post where another user ran into the problem -- in the PR description. Sorry I didn't make that more obvious. Please let me know if you need any additional information.

Rationale for the PR: "Home users" (contrasting with professional sysadmins) are one of Nextcloud's user groups mentioned specifically on the public website: https://nextcloud.com/athome/ So I'd say Nextcloud should be robust enough to handle environments set up by semi-professionals.

From a technical perspective, the current code is kind of deceptive: "this should be enough to check for admin rights in mysql" This simply doesn't hold true. Any database user can query the `mysql.user` table, if permissions are sufficient. That doesn't necessarily mean that the user is an "admin".

**Comment by kesselb** [comment]
> Nextcloud should be robust enough to handle environments set up by semi-professionals.

No. Nextcloud should provide a good setup guide and advice semi-professionals howto setup a secure system. Magic is not the right approach here. There a many of these discussions here on github because nextcloud does sysadmin stuff (e.g. change memory limits, set headers, etc...)

> From a technical perspective, the current code is kind of deceptive: "this should be enough to check for admin rights in mysql" This simply doesn't hold true. Any database user can query the mysql.user table, if permissions are sufficient. That doesn't necessarily mean that the user is an "admin".

What is the point of a setup like this? On a shared hosting select on mysql.user is bad. I'm not against this pr but for me it looks like a configuration issue. If you create a dedicated user for nextcloud without permission for mysql.user everything work as expected.

**Comment by thomasheller** [comment]
> Nextcloud should provide a good setup guide and advice semi-professionals howto setup a secure system. Magic is not the right approach here.

Well, by that logic, that whole "Nextcloud magically creates its own database if it can, but uses the specified database if it can't" thing should go away entirely. Instead, Nextcloud would try to use the specified database, regardless of admin privileges. That would also be a clean way of doing it -- leaving the choice of running Nextcloud via a privileged database user or not to the hopefully informed user. So what I'm saying is that if Nextcloud tries to check permissions, it should do so in a thorough and robust way.

**Comment by kesselb** [comment]
> Well, by that logic, that whole "Nextcloud magically creates its own database if it can, but uses the specified database if it can't" thing should go away entirely. Instead, Nextcloud would try to use the specified database, regardless of admin privileges.

That would be my preferred approach.

> So what I'm saying is that if Nextcloud tries to check permissions, it should do so in a thorough and robust way.

I see your point but i doubt that your special edge case (a dedicated user for nextcloud with permission to read mysql.user) is true for a lot of people out there. Why would someone setup something like this?

Note: I'm not blocking this pr. Technically it works and for this edge case it makes sense.

**Comment by thomasheller** [comment]
> That would be my preferred approach.

I agree that simplifying the database setup would have its pros. But I'm not sure if that should be discussed (and possibly changed) in the scope of this fix? Sure that would also remedy the original problem described in #13628, but I don't know if there are any other side effects to consider.

> Why would someone setup something like this?

The point is, it happens, even if only by accident. It's actually described this way in some popular tutorials, just as an example: https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql (from 2012, but linked in newer tutorials, and ranking well on search engines -- maybe they'll change it now if someone reads this comment... :wink:)

**Comment by ChristophWurst** [comment]
@thomasheller can we get this in? Otherwise I would suggest to close beacuse it's been since the last activity.

**Pull request closed without merging**
