### PR TITLE
Add PHP missing message to index.php

### PR DESCRIPTION
**Pull request by MariusBluem**
As discussed with @karlitschek and @schiessle 🤣 

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by karlitschek** [comment]
👍

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@karlitschek Be aware of the GitHub review feature - then I don't need to forcefully merge this, but the merge button actually gets green because of two approvals ;)

bildschirmfoto 2018-05-08 um 17 00 26

**Comment by MorrisJobke** [comment]
@MariusBluem Please backport to stable13

**Comment by karlitschek** [comment]
@MorrisJobke Got it. Sorry :-)

**Pull request merged**
