### PR TITLE
Re-enable upload button after updating Avatar fixes #8623

### LINKED ISSUE #8623: Can not to upload avatar after upload one picture right now ,must reload the page first.
### Steps to reproduce
1.go to personal settings page
2.click the upload button and select an image
3.after the image is complete
4.if you want to change avatar,if you don't reload page first,you can't upload image,the upload buttoon is disabled.If you click the delete button,then you click the upload button,it's the same.

### Server configuration
Database:10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
PHP version:PHP 7.0.22
cloud server:Nextcloud
cloud version: 14.0.0.1 alpha

### PR DESCRIPTION
**Pull request by LEDfan**
Signed-off-by: Tobia De Koninck <LEDfan@users.noreply.github.com>

Fixes #8623

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Make sense yes :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@LEDfan Could you create a back port PR for stable14 at least (this was report for a 14 instance)

**Comment by LEDfan** [comment]
@MorrisJobke here it is #11451. Should I create one for 13 too?

**Comment by MorrisJobke** [comment]
Feel free to do so 🙂

**Pull request merged**
