### PR TITLE
Remove old code from comment to not trigger automatic scanners more than needed

### PR DESCRIPTION
**Pull request by nickvergessen**
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
/backport 24afcda471a5968af3b88ae7454fdbe10a09066f to stable25

**Comment by nickvergessen** [comment]
/backport 24afcda471a5968af3b88ae7454fdbe10a09066f to stable24

**Review by szaimen — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by nickvergessen** [comment]
/backport 24afcda471a5968af3b88ae7454fdbe10a09066f to stable24

**Comment by nickvergessen** [comment]
Okay, then only 25+

**Pull request merged**
