### PR TITLE
fixes issue #12383

### LINKED ISSUE #12383: Password reset encrypted-continue checkbox not visible due to CSS
### Steps to reproduce
1. Create and open password reset link on server with encryption enabled
2. Enter new password and click reset button
3. Now the encryption note appears but the 'I know what I'm doing' checkbox is not visible.

### Expected behaviour
Checkbox should be visible.

### Actual behaviour
The bug seems to have to do with guest.css file.
If I remove line 188 '-webkit-appearance: none' the checkbox becomes visible again.

input,
input:not([type='range']),
a.button {
	font-size: 20px;
	margin: 5px;
	padding: 11px 10px 9px;
	outline: none;
	border-radius: 3px; /* --border-radius */
	-webkit-appearance: none;
}

### Server configuration

**Operating system**:
Ubuntu 16/18

**Web server:**
nginx

**Database:**
MariaDB

**PHP version:**
7.0/7.2

**Nextcloud version:** (see Nextcloud admin page)
14.0.3/15.0beta1

**Updated from an older Nextcloud/ownCloud or fresh install:**
both

**Where did you install Nextcloud from:**
nextcloud.com download

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox/Chrome/Safari

**Operating system:**
OS X

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by RandieM**
fixes #12383

### CODE REVIEW

**Comment by rullzer** [comment]
Thanks for the PR @RandieM!

**Review by skjnldsv — COMMENTED** [review]
Thanks for the pr! :)
What if the primary colour is white?

**Comment by RandieM** [comment]
@skjnldsv, I am not sure what you mean by "primary colour". Are you referring to the background of the log-in page being white? In this case, the checkbox changes automatically to black and it still looks good (screenshot below).
reset-on-whitebg

**Review by skjnldsv — APPROVED** [review]
Then it's perfect! :)

**Comment by RandieM** [comment]
@skjnldsv, is signing a "must" or did you just mention it for future commits?

**Comment by skjnldsv** [comment]
> @skjnldsv, is signing a "must" or did you just mention it for future commits?

It's mandatory, the DCO pass cannot pass without signed commit :)
https://github.com/nextcloud/server/pull/13033/checks?check_run_id=40414963

**Comment by rullzer** [comment]
For such small changes it is fine. But for future fixes it is appreciated :)

**Review by rullzer — APPROVED** [review]

**Pull request merged**
