### PR TITLE
Parse multiple navigation items

### LINKED ISSUE #14052: Multiple Navigation En
In nextcloud 14 app we can add navigations entries via info.xml.
When I add only one entry everything is working but when I add two or more entries, nothing is appearing in the menu. 
Entry type = settings

### PR DESCRIPTION
**Pull request by kesselb**
Close #14052 

### Test

Pick any app with `<navigations>` in `info.xml` (e.g. activity) and add a second `<navigation>` item.

### Expected

Two navigation items for this app

### Actual

No navigation entry for this app

### ~~Known limitation~~

~~If `id` is not defined for navigation app name is used as fallback. At least one navigation item needs the id element with a value not equal to app name.~~

### CODE REVIEW

**Comment by nickvergessen** [comment]
We could fallback to `<appid><$i>`

**Comment by kesselb** [comment]
> We could fallback to `<appid><$i>`

Don't have a strong opinion on that. Do you think someone would bind application logic to an navigation item and use `<li data-id="activity">`for it?

`$id = isset($nav['id']) ? $nav['id'] : $app . ($navKey === 0 ? '' : $navKey);`

Not nice but backwards compatible :see_no_evil:

**Comment by nickvergessen** [comment]
Good news, master is 7.1+
So I would go for that.

Well I think at least items should have a unique ID.

**Review by MorrisJobke — APPROVED** [review]
Code looks good, tested and works 👍

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failures unrelated.

**Pull request merged**
