### PR TITLE
Do not set indeterminate state for file shares

### PR DESCRIPTION
**Pull request by juliusknorr**
Files just have one edit permission checkbox, so having an indeterminate state there doesn't make sense and actually broke updating the edit permission on file shares. Found this while checking the failing tests in #12105. 

Fixes https://github.com/nextcloud/server/issues/11730

@nextcloud/javascript

### CODE REVIEW

**Comment by skjnldsv** [comment]
Stop editing the sharing!! :cry:

**Review by skjnldsv — APPROVED** [review]

**Comment by juliushaertl** [comment]
@skjnldsv I can't, it's broken. :see_no_evil: But we can wait until your changes are merged :wink: this one is probably a bit easier to rebase.

**Comment by skjnldsv** [comment]
@juliushaertl you can also merge on my pr if you want :)
#11844

**Comment by juliushaertl** [comment]
Let's keep it separate so we can properly track the changes. This one needs a backport, since it is broken on 14 as well.

**Comment by juliushaertl** [comment]
I've added some tests as well.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
CI failures are unrelated and are fixed on master already

**Pull request merged**
