### PR TITLE
Show warning if slash is entered as filename

### LINKED ISSUE #6594: Special characters in file name cause fatal exception in webdav
When you try to rename a file with special characters inside (like `<`) you get an exception in protocol:

```json
{
   "reqId":"<removed>",
   "level":4,
   "time":"<removed>",
   "remoteAddr":"<removed>",
   "user":"<removed>",
   "app":"webdav",
   "method":"MOVE",
   "url":"\/remote.php\/webdav\/Photos\/Coast.jpg",
   "message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Message\":\"The destination node is not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(624): Sabre\\\\DAV\\\\Server->getCopyAndMoveInfo(Object(Sabre\\\\HTTP\\\\Request))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":749}",
   "userAgent":"<removed>",
   "version":"12.0.3.3"
}
```

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #6594 when creating or renaming a file.

### CODE REVIEW

**Comment by MariusBluem** [comment]
For now, fine :wink: But what do you think about creating a directory with that file when somebody types in "testfolder/testdoc.docx" as document name :thinking: @MorrisJobke

**Comment by MorrisJobke** [comment]
> For now, fine 😉 But what do you think about creating a directory with that file when somebody types in "testfolder/testdoc.docx" as document name 🤔 @MorrisJobke

Something for later and also a bit over the top from my point of view.

**Comment by MorrisJobke** [comment]
The second commit fixes all the cases of https://github.com/nextcloud/server/issues/6594#issuecomment-354983844 and logs them as debug logs.

**Review by blizzz — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
Strange it was not already implemented! 🤔

**Review by rullzer — APPROVED** [review]

**Pull request merged**
