### PR TITLE
Improve layout for the public download page

### PR DESCRIPTION
**Pull request by CarlSchwan**
This centers the content inside the pages, while also not hardcoded the
size of the footer and removing an annoying small vertical scroll.

Before:

mobile before
desktop before

After:

image
image

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Comment by acsfer** [comment]
@CarlSchwan Your screenshot does not have the 3 lines at the bottom (just enter a disclaimer on the `settings/theming` option to have it) but i presume everything is fine?

**Comment by CarlSchwan** [comment]
> 

Works fine :)

image

Also added a non-breaking space in the file size displays, I noticed in my screenshot that it was needed

**Review by solracsf — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by CarlSchwan** [comment]
Tests are failing due to the non breaking space, i will look into it

**Review by szaimen — APPROVED** [review]
works

**Comment by CarlSchwan** [comment]
Should I do a backport? Since this fixes the issue with the footer size not working correctly then there is a privacy policy

**Comment by szaimen** [comment]
> Should I do a backport?

I vote for yes

**Comment by acsfer** [comment]
Ok for backport to me @CarlSchwan

**Pull request merged**
