### PR TITLE
Show app version in app detail sidebar

### PR DESCRIPTION
**Pull request by tcitworld**
Show either installed version or first release found in app store data.

Version is shown in the list view but not in the detail sidebar.

It shows on the next line but maybe we can decide a better display.

Screenshot_2020-01-15 Applications - Nextcloud

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Can we just show it in the same row of the license for simplicity?

> Version 1.1.4, AGPL-licensed

**Comment by skjnldsv** [comment]
Well, to be fair the app sidebar is not even using the appsidebar component properly, so moving to it could put both of them on the same line as the subtitle ;)

**Comment by tcitworld** [comment]
> Can we just show it in the same row of the license for simplicity?

Fixed
Screenshot_2020-01-16 Applications - Nextcloud-2

> Well, to be fair the app sidebar is not even using the appsidebar component properly, so moving to it could put both of them on the same line as the subtitle ;)

@skjnldsv I gave a look but unfortunately we have the app icon in the title, so we're blocked with this right now.

Screenshot_2020-01-16 Applications - Nextcloud

**Review by jancborchardt — APPROVED** [review]
Looking great now! :)

**Comment by skjnldsv** [comment]
Could we instead wait for #18969 :see_no_evil: 
Or base those changes on it? :D

**Comment by tcitworld** [comment]
@skjnldsv Yeah feel free to put the commit into #18969 and close this.

**Review by gary-kim — APPROVED** [review]
I like this!

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Blocking

**Comment by tcitworld** [comment]
This is probably not needed anymore since we have the Changelog tab in the sidebar. I'd be happy to bring it back if needed.

@skjnldsv @jancborchardt

**Pull request closed without merging**
