### PR TITLE
fix: Move cloud id into readonly input

### LINKED ISSUE #48410: Sharing settings: Use input with copy button
Could look like this with `CopyContent` icon and `NcInputField` with trailing button.

image

Currently:

image

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Fix https://github.com/nextcloud/server/issues/48410

Before | After
--- | ---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
Conflicts on vue file

**Comment by susnux** [comment]
> Conflicts on vue file

Was only indention, fixed.

**Pull request merged**
