### PR TITLE
Fix referrer policy meta tags.

### LINKED ISSUE #14374: `Referrer-Policy` changes within the `.htaccess` file will not be applied.
`Referrer-Policy` changes within the `.htaccess` file will not be applied.

### Steps to reproduce
1. Change referrer policy in your `.htaccess` file from `no-referrer` to `strict-origin-when-cross-origin`.
```
Header set Referrer-Policy "strict-origin-when-cross-origin"
```
2. Place somewhere a `.php` file on a webserver with the following contents:
```php
<?php

var_dump($_SERVER);
```
3. Use the browser development tools to place a link on `DOMAIN.TLD/login` which points to your `.php` file on your webserver.
4. Click on that link and search for the `HTTP_REFERER` key in the output that the `.php` file you created produces.

### Expected behaviour
You should be able to see the `HTTP_REFERER` field.

### Actual behaviour
There is no `HTTP_REFERER` field.

### Server configuration

**Operating system**:
Linux

**Web server**:
Apache

**Nextcloud version:** (see Nextcloud admin page)
15.0.4

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using encryption:** yes

### Client configuration
**Browser:**
Firefox 66.0b10 & 65.0.1  
Chrome 72.0.3626.119

**Operating system:**
Windows

### PR DESCRIPTION
**Pull request by DominikWA**
Close #14374

Hello everybody,

I have change the referrer policy in the .htaccess file in the nextcloud root. I noticed that the setting does not work because there are still meta tags that manipulate the referrer policy. 

In this PR I want to remove the unnecessary meta tags from the layout files so changes at the .htaccess referrer policy will work.

Best,
Dominik

### CODE REVIEW

**Comment by kesselb** [comment]
Could you rebase your branch to master and change target? Backportbot will do the backport if possible.

**Comment by kesselb** [comment]
> First-time contributor

:tada: Thank you for your contribution!

**Comment by DominikWA** [comment]
I have redone my changes based on current master.

Best,
Dominik

**Review by MorrisJobke — APPROVED** [review]
I'm fine with that 👍

**Comment by MorrisJobke** [comment]
What about this?

https://github.com/nextcloud/server/blob/master/core/templates/layout.public.php#L12

**Comment by DominikWA** [comment]
> 
> 
> What about this?
> 
> https://github.com/nextcloud/server/blob/master/core/templates/layout.public.php#L12

I have also removed this tag, I believe that this is totally unnecessary since there is no referrer-policy `Never`.
See:  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
