### PR TITLE
Allow php 8.2

### PR DESCRIPTION
**Pull request by come-nc**
## Summary

PHP 8.2 is now tested enough to be allowed to be used with master.
There should be no big problems with it, apart from the mailer, until the migration to symfony mailer is finished.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> PHP 8.2 is now tested enough to be allowed to be used with master.

I've been running it locally for over a week with a modified version check. There are a few deprecation logs here and there but so far I have not found any breakage :+1:

**Review by ChristophWurst — APPROVED** [review]
:shipit:

**Comment by come-nc** [comment]
> > PHP 8.2 is now tested enough to be allowed to be used with master.
> 
> I've been running it locally for over a week with a modified version check. There are a few deprecation logs here and there but so far I have not found any breakage +1

Please do open issues or PR for these deprecation warnings though :-P

Our CI is not catching them it seems, oci on 8.2 is passing while on my test PR it’s not: https://github.com/nextcloud/server/actions/runs/4013641040/jobs/6893223191
I think it’s the ini development thing, I’ll try adding it here.

**Comment by ChristophWurst** [comment]
> Please do open issues or PR for these deprecation warnings though :-P

You were too fast. Earlier I checked my logs for dynamic property warnings and you took care of them already in the meantime.

The remainders are 

```
"Creation of dynamic property ScssPhp\\ScssPhp\\Block::$name is deprecated at /nextcloud/3rdparty/scssphp/scssphp/src/Parser.php#854"
"Creation of dynamic property ScssPhp\\ScssPhp\\Compiler\\Environment::$parentStore is deprecated at /nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php#5039"
"Creation of dynamic property ScssPhp\\ScssPhp\\Compiler\\Environment::$selectors is deprecated at /nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php#1872"

```

**Review by blizzz — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
Woohoo, once merged I shall bump all CIs of apps again

**Comment by nickvergessen** [comment]
```
There were 22 errors:

1) Test\Files\Cache\ScannerTest::testBackgroundScan
trim(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Storage/Common.php:762
/home/runner/work/server/server/lib/private/Files/Cache/Scanner.php:327
/home/runner/work/server/server/lib/private/Files/Cache/Scanner.php:529
/home/runner/work/server/server/lib/private/Files/Cache/Scanner.php:541
/home/runner/work/server/server/lib/private/Files/Cache/Scanner.php:528
/home/runner/work/server/server/tests/lib/Files/Cache/ScannerTest.php:163

2) Test\Files\ObjectStore\ObjectStoreStorageTest::testMove with data set #0 ('/source.txt', '/target.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:95

3) Test\Files\ObjectStore\ObjectStoreStorageTest::testMove with data set #1 ('/source.txt', '/target with space.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:95

4) Test\Files\ObjectStore\ObjectStoreStorageTest::testMove with data set #2 ('/source with space.txt', '/target.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:95

5) Test\Files\ObjectStore\ObjectStoreStorageTest::testMove with data set #3 ('/source with space.txt', '/target with space.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:95

6) Test\Files\ObjectStore\ObjectStoreStorageTest::testMove with data set #4 ('/source.txt', '/tärgét.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:95

7) Test\Files\ObjectStore\ObjectStoreStorageTest::testMove with data set #5 ('/sòurcē.txt', '/target.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:95

8) Test\Files\ObjectStore\ObjectStoreStorageTest::testMove with data set #6 ('/sòurcē.txt', '/tärgét.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:95

9) Test\Files\ObjectStore\ObjectStoreStorageTest::testMove with data set #7 ('/single ' quote.txt', '/tar'get.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:95

10) Test\Files\ObjectStore\ObjectStoreStorageTest::testRenameDirectory
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:113

11) Test\Files\ObjectStore\ObjectStoreStorageTest::testRenameOverWriteDirectory
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:144

12) Test\Files\ObjectStore\ObjectStoreStorageTest::testRenameOverWriteDirectoryOverFile
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/ObjectStore/ObjectStoreStorageTest.php:162

13) Test\Files\ObjectStore\ObjectStoreStorageTest::testMoveOverwrite with data set #0 ('/source.txt', '/target.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:273

14) Test\Files\ObjectStore\ObjectStoreStorageTest::testMoveOverwrite with data set #1 ('/source.txt', '/target with space.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:273

15) Test\Files\ObjectStore\ObjectStoreStorageTest::testMoveOverwrite with data set #2 ('/source with space.txt', '/target.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:273

16) Test\Files\ObjectStore\ObjectStoreStorageTest::testMoveOverwrite with data set #3 ('/source with space.txt', '/target with space.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:273

17) Test\Files\ObjectStore\ObjectStoreStorageTest::testMoveOverwrite with data set #4 ('/source.txt', '/tärgét.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:273

18) Test\Files\ObjectStore\ObjectStoreStorageTest::testMoveOverwrite with data set #5 ('/sòurcē.txt', '/target.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:273

19) Test\Files\ObjectStore\ObjectStoreStorageTest::testMoveOverwrite with data set #6 ('/sòurcē.txt', '/tärgét.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:273

20) Test\Files\ObjectStore\ObjectStoreStorageTest::testMoveOverwrite with data set #7 ('/single ' quote.txt', '/tar'get.txt')
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:273

21) Test\Files\ObjectStore\ObjectStoreStorageTest::testRenameOverWriteFile
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:476

22) Test\Files\ObjectStore\ObjectStoreStorageTest::testPartFile
md5(): Passing null to parameter #1 ($string) of type string is deprecated

/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:448
/home/runner/work/server/server/lib/private/Files/Cache/Cache.php:364
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:413
/home/runner/work/server/server/lib/private/Files/ObjectStore/ObjectStoreStorage.php:388
/home/runner/work/server/server/tests/lib/Files/Storage/Storage.php:647

```

**Comment by nickvergessen** [comment]
Some debugging was done in https://github.com/nextcloud/server/pull/36496

**Comment by DaphneMuller** [comment]
hello @come-nc 
Thank you so much for your work on this pull request! This ticket seems to have the tag 'pending documentation'. 
Is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

**Pull request merged**
