### PR TITLE
Fix checkbox left margin glitch

### LINKED ISSUE #1782: Checkbox glitch in user management
When the checkbox is checked, it moves to the left:
capture du 2016-10-18 16-21-50

cc @Henni @juliushaertl @nextcloud/designers :)

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix checkbox left margin glitch

Fix #1782
@jancborchardt

### CODE REVIEW

**Comment by LukasReschke** [comment]
Also requires adjusting the unit tests :)

**Comment by skjnldsv** [comment]
@LukasReschke Forgot :)

**Comment by MorrisJobke** [comment]
I fixed the remaining unit tests and signed it off

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by jancborchardt** [comment]
@skjnldsv please ideally add a before/after screenshot or reference the issue being fixed in the summary so it’s linked. :)

**Comment by MorrisJobke** [comment]
> @skjnldsv please ideally add a before/after screenshot or reference the issue being fixed in the summary so it’s linked. :)

There is the reference in the very first comment ;) Just check it out:

bildschirmfoto 2016-11-02 um 15 23 22

**Comment by jancborchardt** [comment]
@MorrisJobke ty! Just checked the comments and file changes, didn’t catch that

**Comment by skjnldsv** [comment]
😆

**Comment by rullzer** [comment]
LGTM

**Pull request merged**
