### PR TITLE
[stable12] Fix #4789: Group admins cannot see disabled users

### LINKED ISSUE #4789: Group admins cannot see disabled users
### Steps to reproduce
1. Create user `ray` and `paul`
2. create group `marketing`
3. assign `paul` to group `marketing`
4. make `ray` to group admin of `marketing`
5. login as `ray` and go to user management
6. disable `paul`
7. Click on Disabled to list the disabled users

### Expected behaviour
`ray` should appear under disabled

### Actual behaviour
`ray` does not appear under disabled (empty response)

### Server configuration
**Nextcloud version:** 12 beta 2
**Updated from an older Nextcloud/ownCloud or fresh install:** update from 12 beta 1

#### Nextcloud log (data/nextcloud.log)
```
no errors logged
```

#### Browser log
```
/index.php/settings/users/users?offset=0&limit=50&gid=_disabledUsers&pattern=
HTTP Code 200
Empty response
```

### PR DESCRIPTION
**Pull request by blizzz**
Backport of #7292 

I place it to 12.0.6 since .5 is almost out of the door.

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
> I place it to 12.0.6 since .5 is almost out of the door.

Correct - let's wait for 12.0.6

**Comment by michag86** [comment]
Works for me 👍

**Review by michag86 — APPROVED** [review]
works for me 👍

**Comment by MorrisJobke** [comment]
@blizzz Sign-off missing ;)

**Comment by blizzz** [comment]
@MorrisJobke  Sacré bleu! Fixed.

**Comment by MorrisJobke** [comment]
12.0.5 is out -> merge

**Comment by MorrisJobke** [comment]
@michag86 To give you a rough ETA for 12.0.6: we aim for mid march

**Comment by michag86** [comment]
@MorrisJobke Thank you!

**Pull request merged**
