### PR TITLE
Fix json_decode expecting a string

### LINKED ISSUE #36894: [Bug]: error when upgrading from 25.0.3 to 25.0.4
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```
sudo -u nginx php ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Starting code integrity check...
An unhandled exception has been thrown:
TypeError: json_decode(): Argument #1 ($json) must be of type string, bool given in /var/www/website.com/lib/private/IntegrityCheck/Checker.php:443
Stack trace:
#0 /var/www/website.com/lib/private/IntegrityCheck/Checker.php(443): json_decode()
#1 /var/www/website.com/lib/private/IntegrityCheck/Checker.php(459): OC\IntegrityCheck\Checker->getResults()
#2 /var/www/website.com/lib/private/IntegrityCheck/Checker.php(581): OC\IntegrityCheck\Checker->storeResults()
#3 /var/www/website.com/lib/private/IntegrityCheck/Checker.php(592): OC\IntegrityCheck\Checker->verifyCoreSignature()
#4 /var/www/website.com/lib/private/Updater.php(309): OC\IntegrityCheck\Checker->runInstanceVerification()
#5 /var/www/website.com/lib/private/Updater.php(141): OC\Updater->doUpgrade()
#6 /var/www/website.com/core/Command/Upgrade.php(225): OC\Updater->upgrade()
#7 /var/www/website.com/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#8 /var/www/website.com/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#9 /var/www/website.com/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#10 /var/www/website.com/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#11 /var/www/website.com/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#12 /var/www/website.com/console.php(100): OC\Console\Application->run()
#13 /var/www/website.com/occ(11): require_once('...')
#14 {main}
```

### Steps to reproduce

 ./occ upgrade

### Expected behavior

```
sudo -u nginx php ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Resetting log level
```

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
sudo -u nginx php ./occ app:list
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - flowupload: 1.1.2
  - suspicious_login
  - testing
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by apasov**
* Resolves: #36894

fixes #36894

### CODE REVIEW

**Comment by solracsf** [comment]
Can't the whole `if` be replaced with a simple:

`return json_decode($cachedResults ?? false, true);`

**Comment by ChristophWurst** [comment]
The `$json` parameter is typed `string`

**Review by icewind1991 — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
