### PR TITLE
Set double outline on checked state for radio buttons

### LINKED ISSUE #36981: [BITV] 9.2.1.1/3.3 - Dialog "Online status"  - Sighted keyboard users may have trouble selecting status since the affordance of the status controls will make them think the controls are buttons while it is in fact a radio group (which is logically correct) and thus not tabbable - and the focus on the first (selected) element is not visible since it is not differentiated from the visual indication of selected state (see rating in 9.2.4.7 Focus visible). (5)
<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6bd94ebc49-v3-n3

</details>

- [ ] 9.2.1.1/5.2 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6bd94ebc49-v5-n2
- [ ] 9.2.1.1/7.4 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6bd94ebc49-v7-n4
- [ ] 9.2.1.1/8.2 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6bd94ebc49-v8-n2
- [ ] 9.2.1.1/10.3 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6bd94ebc49-v10-n3

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
* Resolves: https://github.com/nextcloud/server/issues/36981

## Summary
Set double outline on checked state for radio buttons for user status modal.

**Before:** 

Peek 2023-06-29 10-33

**After:**

Peek 2023-08-11 13-33
Peek 2023-08-11 13-32

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
Dear @michaelnissenbaum 

Could you please have a look a bit if i resolved that issue: https://github.com/nextcloud/server/issues/36981?

Additionally I'm not sure about this part:
> and the focus on the first (selected) element is not visible since it is not differentiated from the visual indication of selected state

I thought it is a goal of radio buttons: as far next option from radio buttons group will be checked, a focus state from previous one will dissapear: 

Peek 2023-07-12 11-02

Could you please tell me if this implementation (see captures above) is correct and if i understood you right? 
Thanks a lot!

**Review by nimishavijay — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter , visually the group of radio buttons looks good. What still needs to be clarified is the keyboard navigation as I cannot verify it based on the image. The correct functionality can be observed very well on the page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio. I hope this has been helpful. If not, please let me know.

**Review by Pytal — APPROVED** [review]

**Comment by JuliaKirschenheuter** [comment]
> The correct functionality can be observed very well on the page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio.

Thanks @michaelnissenbaum! Now i got a point!

Now i'm pretty sure that this version is correct:

Peek 2023-07-13 14-20
Peek 2023-07-13 14-19

**Review by nimishavijay — APPROVED** [review]
Looks good!

**Review by Pytal — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Review by marcoambrosini — CHANGES_REQUESTED** [review]
Actually @JuliaKirschenheuter if we do this we need to remove the original blue border that becomes is confusing now.

**Comment by JuliaKirschenheuter** [comment]
> Actually @JuliaKirschenheuter if we do this we need to remove the original blue border that becomes is confusing now.

That was an issue and because of this: https://github.com/nextcloud/server/pull/39332#issuecomment-1633044454 i've added blue border together with double outline to different between selected state and focused / hovered state.

**Comment by marcoambrosini** [comment]
I would just drop the hover state here. There is no focus state in radio buttons. What do you think @nextcloud/designers?

**Comment by szaimen** [comment]
> I would just drop the hover state here. There is no focus state in radio buttons. What do you think @nextcloud/designers?

Makes sense 👍

**Comment by JuliaKirschenheuter** [comment]
> I would just drop the hover state here. There is no focus state in radio buttons. What do you think https://github.com/orgs/nextcloud/teams/designers?

you mean to drop hover styles completely? Then it won't be possible to different between all of radio buttons on hover

**Comment by JuliaKirschenheuter** [comment]
> It doesnt need to as long as the mouse changes to pointer type afaik?

it is a visual change, actually don't needed. @marcoambrosini @nimishavijay should i take hover styles away?

**Comment by JuliaKirschenheuter** [comment]
I will finish this PR after my vacation

**Comment by marcoambrosini** [comment]
[I proposed a call to discuss the strategy with radio buttons when @JuliaKirschenheuter is back ](https://github.com/nextcloud/nextcloud-vue/pull/4347#issuecomment-1649166446)

**Comment by JuliaKirschenheuter** [comment]
@marcoambrosini I've updated focused / selected state and created more suitable solution which looks better and is accessible too. @nimishavijay what do you think? Is it ok for both of you?

**Review by marcoambrosini — APPROVED** [review]

**Review by nimishavijay — APPROVED** [review]
Looks good Julia!

**Pull request merged**
