### PR TITLE
Allow status.php before install

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Remove config.php
2. `curl -v http://nextcloud11.local/status.php`
### Expected

```
{"installed":false,"maintenance":false,"version":"9.2.0.3","versionstring":"11.0 alpha","edition":"","productname":"Nextcloud"}
```
### Actual

```
HTTP/1.1 302 Found
```

@MorrisJobke @LukasReschke 
@longsleep as discussed

### CODE REVIEW

**Comment by rullzer** [comment]
I'm fine with this. But what is the reason ;)?

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by nickvergessen** [comment]
@rullzer spreedbox needs a reliable way to check whether nextcloud is installed

**Comment by rullzer** [comment]
Fair enough. Ah and of course :+1:

**Comment by longsleep** [comment]
Nice thanks :+1:

**Pull request merged**
