### PR TITLE
Restrict DAV share handling to the owner only

### PR DESCRIPTION
**Pull request by nickvergessen**
Otherwise group members can remove the share for the complete group,
remove edit permissions and even single user shares for other users.

@georgehrke you can use this PR to adjust the calendar app
@irgendwie you can use this PR to adjust the contacts app

### CODE REVIEW

**Comment by georgehrke** [comment]
Reminder to myself:
- make sure that `<oc:invite>` is still populated with one `<oc:user>` of the sharer, so the calendar can get their displayname

**Comment by rullzer** [comment]
Conflicts

**Comment by nickvergessen** [comment]
@georgehrke what's the status? Can we proceed this?

**Comment by georgehrke** [comment]
will review later today, can you please rebase? :)

**Comment by georgehrke** [comment]
`<oc:invite>` is actually only populated with one `<oc:user>` for the owner if the owner (themselves) shared it publicly. Instead we should add `nc:owner-displayname` property. But that's something for a different PR (which I will send).

otherwise 👍

**Review by georgehrke — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code looks good :+1:

**Comment by MorrisJobke** [comment]
Unit tests are failing - @georgehrke @nickvergessen Could you fix them?

**Comment by nickvergessen** [comment]
Done

**Comment by MorrisJobke** [comment]
10 of those errors:

```
10) OCA\DAV\Tests\unit\CardDAV\AddressBookTest::testAcl with data set "read-only property is true and no owner" (false, true, false)
Undefined index: {DAV:}displayname
/drone/src/github.com/nextcloud/server/apps/dav/lib/CardDAV/AddressBook.php:50
/drone/src/github.com/nextcloud/server/apps/dav/tests/unit/CardDAV/AddressBookTest.php:109
```

**Comment by MorrisJobke** [comment]
> 10 of those errors:

I fixed them.

**Pull request merged**
