### PR TITLE
fix(files): Fix having to resolve conflicts twice when dropping files

### PR DESCRIPTION
**Pull request by Pytal**
## Resolves

When dragging and dropping some files into a folder with identically named files, a conflict resolution dialog will pop up and after submitting your selection subsequent conflict dialogs will be shown for each file individually. We want to proceed with the users initial selection instead of repeating the conflict resolution.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
makes sense (we should also implement recursive conflict resolution for internal moves similar we do with uploads).

**Review by szaimen — APPROVED** [review]
Tested and works. Thanks for fixing this! :)

**Pull request merged**
