### PR TITLE
[stable13] Fix ellipsis in filename column

### PR DESCRIPTION
**Pull request by juliusknorr**
backport of #9248

@nextcloud/designers

### CODE REVIEW

**Comment by johnyb0y** [comment]
Thanks!

**Comment by MorrisJobke** [comment]
JS failure seems unrelated, because this is an SCSS only change.

**Comment by skjnldsv** [comment]
@MorrisJobke restarted to be sure :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by skjnldsv** [comment]
Same error, it might be good to look at it:

```
PhantomJS 2.1.1 (Linux 0.0.0) DeleteHandler tests deletes first entry and reshows notification on second delete FAILED
	TypeError: undefined is not a function (evaluating 'showNotificationSpy.reset()') in settings/tests/js/users/deleteHandlerSpec.js (line 82)
	settings/tests/js/users/deleteHandlerSpec.js:82:28

```

**Comment by juliushaertl** [comment]
@skjnldsv It seems that it is also failing on master/stable13 since the test dependency sinon has removed a deprecated method in their new release 3 days ago.

Fix is in https://github.com/nextcloud/server/pull/9348

**Review by rullzer — APPROVED** [review]

**Pull request merged**
