### PR TITLE
Fix Nextcloud Android app not showing proper name

### PR DESCRIPTION
**Pull request by provokateurin**

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
🙈

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by skjnldsv — APPROVED** [review]

**Comment by jld3103** [comment]
Done. Didn't know I had to compile the files.

**Comment by jld3103** [comment]
Sorry, what is DCO?

**Comment by artonge** [comment]
https://github.com/nextcloud/server/pull/32583/checks?check_run_id=6656435890

**Pull request merged**
