### PR TITLE
Only trust the X-FORWARDED-HOST header for trusted proxies

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by nickvergessen** [comment]
should also patch getServerProtocol

Other than that :+1: good hardening

**Review by nickvergessen — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

**Comment by ChristophWurst** [comment]
>  [rullzer](/rullzer) added [enhancement](/nextcloud/server/labels/enhancement) [2. developing](/nextcloud/server/labels/2.%20developing) labels [a day ago](#event-2030026190)

Anything missing?

**Comment by rullzer** [comment]
Litmus is failing. But unrelated I think

**Comment by rullzer** [comment]
Yep fails becaus of https://github.com/nextcloud/server/commit/740ea0d30e8e

**Pull request merged**
