### PR TITLE
Fix user and group listing with users that have an integer user id

### LINKED ISSUE #11178: User List Not Shown If Any User Has Numeric ID
### Steps to reproduce
1. Create user with numeric ID
2. Go to userlist
3. Fail

### Expected behaviour
User list should display

### Actual behaviour
User list does not display

### Server configuration

**Operating system**: CentOS 7

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.2

**Nextcloud version:** 14.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Official release zip

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
PHP TypeError: Argument 1 passed to OCA\Provisioning_API\Controller\AUserData::getUserData() must be of the type string, integer given, called in /var/www/sprycloud/http/apps/provisioning_api/lib/Controller/UsersController.php on line 180 at /var/www/sprycloud/http/apps/provisioning_api/lib/Controller/AUserData.php#81
```
</details>

This commit fixes the issue: https://github.com/nextcloud/server/pull/11157/commits/3d566dd5aeaf26b8e9d78d17545c27612690895f

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #11178

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Make sense!

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
I could swear i saw it working, but the code changes make total sense. Subsequently (separate PR) some tests would be nice to not fall into this trap again.

**Comment by blizzz** [comment]
@nickvergessen can you do the backport, pls?

**Comment by nickvergessen** [comment]
>  I could swear i saw it working, but the code changes make total sense. Subsequently (separate PR) some tests would be nice to not fall into this trap again.

Yeah same here, we fixed it a couple of times already....
I guess it is time for integration tests on the provisioning api

**Comment by nickvergessen** [comment]
Backport in https://github.com/nextcloud/server/pull/11186

**Pull request merged**
