### PR TITLE
Show Delete Icon in Breadcrumb in Trashbin

### LINKED ISSUE #15155: Change the home icon when looking at the trashbin
**Is your feature request related to a problem? Please describe.**

I find it a bit strange that the "home" icon is being shown when I'm in the trash bin view

**Describe the solution you'd like**

I'd like the Home icon to be replaced with a trash icon when I'm in the trash bin view

**Describe alternatives you've considered**

None. It's not logical to see a home icon there.

**Additional context**

Nothing to add.

### PR DESCRIPTION
**Pull request by gary-kim**
Closes #15155

New
Screenshot from 2019-10-05 16-07-05

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Please rebase :)

**Review by juliusknorr — CHANGES_REQUESTED** [review]
The regular icon-delete class turns the icon to red when hovering, because we used it for the delete action until now. I think we should not have this behavior for the breadcrumb.

**Comment by gary-kim** [comment]
> The regular icon-delete class turns the icon to red when hovering, because we used it for the delete action until now. I think we should not have this behavior for the breadcrumb.

Removed the red on hover for the icon. What do you think?

**Comment by juliushaertl** [comment]
I think the no-hover class is a bit more descriptive.

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
