### PR TITLE
Add email addresses to contacts menu

### PR DESCRIPTION
**Pull request by kesselb**
Add the email addresses to the contacts menu
 
image

### CODE REVIEW

**Comment by blizzz** [comment]
cc @nextcloud/designers this PR makes the contacts menu more similar to the share dialog, where we show the email since 21

**Comment by tcitworld** [comment]
Wasn't the plan to get rid of the contact menu ?
https://github.com/nextcloud/server/issues/15586#issuecomment-901268383

**Comment by blizzz** [comment]
> Wasn't the plan to get rid of the contact menu ?
> [#15586 (comment)](https://github.com/nextcloud/server/issues/15586#issuecomment-901268383)

For 22 and 21 it still makes sense. And it is not gone from master yet.

**Review by ChristophWurst — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
Screenshot_20210915_165118

**Pull request merged**
