### PR TITLE
Mark split database configs as sensitive

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up to #30973

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by szaimen — APPROVED** [review]

**Review by MautkamManjar — APPROVED** [review]
Can you guys elaborate it more

**Comment by nickvergessen** [comment]
See https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/splitting.html @MautkamManjar

**Pull request merged**
