### PR TITLE
Fix app menu flicker

### LINKED ISSUE #34591: Flickering header menu
Peek 2022-10-13 21-09

FPS is low on the recording

### LINKED ISSUE #38511: [Bug]: Menu toggles multiple times per second when hovering with mouse in bottom of menu
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It's more of an annoyance but a minor bug nonetheless and noteworthy i guess.

Hovering slightly below the menu items in the menubar toggles the movement and text under the icons multiple times per second.

Just watch the attached movie to see what I mean.

Tested with Firefox and Chrome based browsers. 

https://github.com/nextcloud/server/assets/3179748/b1984e13-4565-4c55-a3a1-0b904534295b

### Steps to reproduce

1. login to Nextcloud
2. Move mouse to almost the bottom of the menu bar
3. See the menubar toggeling tens of times per second.

### Expected behavior

toggle menu bar text under icon on or off depending on position of mouse.

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - announcementcenter: 6.6.1
  - bookmarks: 13.0.1
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.4
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - collectives: 2.5.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.2
  - drawio: 2.1.1
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_antivirus: 5.0.0
  - files_external: 1.18.0
  - files_fulltextsearch: 26.0.0
  - files_lock: 27.0.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - flow_notifications: 1.6.0
  - forms: 3.3.0
  - fulltextsearch: 26.0.0
  - fulltextsearch_elasticsearch: 26.0.0
  - groupfolders: 14.0.2
  - integration_openai: 1.0.8
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - maps: 1.0.2
  - memories: 5.1.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - notify_push: 0.6.3
  - oauth2: 1.14.0
  - onlyoffice: 7.8.0
  - password_policy: 1.16.0
  - passwords: 2023.5.30
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - quota_warning: 1.17.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - sociallogin: 5.4.3
  - systemtags: 1.16.0
  - tasks: 0.15.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - welcome: 1.0.9
  - workflowengine: 2.8.0
Disabled:
  - encryption: 2.14.0
  - firstrunwizard: 2.15.0 (installed 2.7.0)
  - snappymail: 2.27.3 (installed 2.27.3)
  - spreed: 16.0.4 (installed 16.0.4)
  - support: 1.9.0 (installed 1.0.1)
  - survey_client: 1.14.0 (installed 1.7.0)
  - suspicious_login: 4.4.0 (installed 3.2.1)
  - twofactor_totp: 8.0.0 (installed 6.1.0)
  - user_ldap: 1.16.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
not relevant
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ZetaTom**
* Resolves: #38511
* Fixes https://github.com/nextcloud/server/issues/34591
* Closes https://github.com/nextcloud/server/issues/34591

## Summary
This fixes a small annoyance when hovering over the app menu. Previously hovering just below the app menu bar would lead to the labels flickering.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Thanks a lot for fixing this! Works well in my testing! :)

**Comment by ZetaTom** [comment]
Apologies; I forgot to sign off my commit.

**Review by Pytal — APPROVED** [review]

**Pull request merged**
