### PR TITLE
add changelog link to update notification section

### PR DESCRIPTION
**Pull request by violoncelloCH**
as requested in #6117

Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
bildschirmfoto 2018-11-28 um 20 17 05


Should we maybe place the "Open changelog" somewhere else?

cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
Also the package-lock.json should not be updated in here.

**Comment by enoch85** [comment]
> Should we maybe place the "Open changelog" somewhere else?

I think it should be next to "Open updater" in the same style box.

**Comment by violoncelloch** [comment]
As there is a link to the changelog inside the "Whats new?"-popover already (I didn't see this until testing) I will close this.
However the "Whats new?"-thing is quite hidden as it is only text which can be clicked at. I would suggest to change the style of this. Should we make a button out of it and place it beside the "Open updater" button?

**Comment by MorrisJobke** [comment]
> However the "Whats new?"-thing is quite hidden as it is only text which can be clicked at. I would suggest to change the style of this. Should we make a button out of it and place it beside the "Open updater" button?

That's what also @skjnldsv said.

**Comment by MorrisJobke** [comment]
@violoncelloch Could you add this to the polishing ticket in #12694?

**Comment by violoncelloch** [comment]
> @violoncelloch Could you add this to the polishing ticket in #12694?
@MorrisJobke of course; done!

**Pull request closed without merging**
