### PR TITLE
[stable9] Print error message again, when 3rdparty submodule is not initialized

### PR DESCRIPTION
**Pull request by blizzz**
Could not find base or head reference on 3rdparty.

Could not find base or head reference on activity.

Could not find base or head reference on circles.

Could not find base or head reference on example-files.

Could not find base or head reference on files_pdfviewer.

Could not find base or head reference on files_rightclick.

Could not find base or head reference on files_videoplayer.

Could not find base or head reference on firstrunwizard.

Could not find base or head reference on logreader.

Could not find base or head reference on nextcloud_announcements.

Could not find base or head reference on notifications.

Could not find base or head reference on password_policy.

Could not find base or head reference on photos.

Could not find base or head reference on privacy.

Could not find base or head reference on recommendations.

Could not find base or head reference on serverinfo.

Could not find base or head reference on survey_client.

Could not find base or head reference on text.

Could not find base or head reference on updater.

Could not find base or head reference on viewer.

Could not find base or head reference on privacy.

Could not find base or head reference on recommendations.

Could not find base or head reference on viewer.

* #1004
* #1141
* #1149
* #1152
* #1153
* #1155
* #1175
* #1182
* #1208
* #1232
* #1281
* #1289
* #1295
* #1313
* #1321
* #1325
* #1344
* #1388
* #1390
* #1392
* #1403
* #1416
* #1501
* #1542
* #1556
* #1647
* #1650
* #1687
* #1690
* #1696
* #1698
* #1699
* #1719
* #1770
* #1799
* #1819
* #1900
* #2049
* #2057
* #2060
* #2120
* #2439
* #2446
* #2450
* #2453
* #2455
* #2458
* #2461
* #2467
* #2488
* #2795
* #2883
* #2996
* #334
* #3434
* #3442
* #3563
* #370
* #406
* #4226
* #4232
* #442
* #4421
* #447
* #463
* #469
* #491
* #511
* #514
* #516
* #518
* #546
* #549
* #552
* #570
* #587
* #589
* #594
* #615
* #623
* #629
* #655
* #690
* #707
* #749
* #793
* #818
* #826
* #888
* #901
* #911
* #933
* #962

### CODE REVIEW

**Comment by mar1u5** [comment]
👍

**Comment by LukasReschke** [comment]
> Question about the procedure: Why are we not merging the commit into stable9 form master, or from the origin brach - instead we create a fix-3rdparty-notice-stable9 branch 😕

We want to review every change to our stable or master branch manually. And since stable and master are often so different it's not feasible to do it that way since it would also get in new features etc :)

@blizzz Please review so that CI runs on this as well :)

**Comment by blizzz** [comment]
*rebased*

**Comment by mar1u5** [comment]
All Tests passed - Backport merged :wink:

**Comment by blizzz** [comment]
Yay, thx @mar1u5 :bow:

**Pull request merged**
