### PR TITLE
Lazy register the navigation

### PR DESCRIPTION
**Pull request by rullzer**
This makes sure that we do not translate unneeded strings on for example
webdav requests.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:rocket:

**Comment by ChristophWurst** [comment]
To be even lazier you could move `$l10n = $context->getAppContainer()->query(IL10N::class);` into the callbacks and have that also constructed only when needed and as late as possible

**Comment by rullzer** [comment]
> To be even lazier you could move `$l10n = $context->getAppContainer()->query(IL10N::class);` into the callbacks and have that also constructed only when needed and as late as possible

yeah yeah baby steps ;)

**Comment by ChristophWurst** [comment]
:koala: steps

**Review by MorrisJobke — APPROVED** [review]
Tested, works and reduces load time for normal PROPFIND by 5-8% on my machine  👍

**Comment by rullzer** [comment]
> Tested, works and reduces load time for normal PROPFIND by 5-8% on my machine +1

with out without xdebug?

**Comment by MorrisJobke** [comment]
I pushed a fix for the CS failure.

**Comment by MorrisJobke** [comment]
> with out without xdebug?

with xdebug. Let me try without.

**Comment by MorrisJobke** [comment]
Without it is a bit less. Then it's 2-4% less wall time, but with and without the memory footprint is constantly less (around 9-10% less).

**Comment by nickvergessen** [comment]
I had so high hopes when seeing the title.
But yeah, better than nothing I guess.

**Comment by rullzer** [comment]
> I had so high hopes when seeing the title.
> But yeah, better than nothing I guess.

what where you hoping for?

**Comment by nickvergessen** [comment]
To be able to register without `getNavigationManager` which itself sets up: session, l10n factory, config, group manager, url generator, …

**Comment by MorrisJobke** [comment]
> To be able to register without `getNavigationManager` which itself sets up: session, l10n factory, config, group manager, url generator, …

Maybe something for the registration context: https://github.com/nextcloud/server/blob/4488e846a526ed8de37e9756621b7c008d7a9466/lib/public/AppFramework/Bootstrap/IRegistrationContext.php

cc @ChristophWurst

**Comment by rullzer** [comment]
> > To be able to register without `getNavigationManager` which itself sets up: session, l10n factory, config, group manager, url generator, …
> 
> Maybe something for the registration context: https://github.com/nextcloud/server/blob/4488e846a526ed8de37e9756621b7c008d7a9466/lib/public/AppFramework/Bootstrap/IRegistrationContext.php
> 
> cc @ChristophWurst

yeah this is just the quick win. But indeed we should kill that and make it lazy as well

**Pull request merged**
