### PR TITLE
Do not show general warning on free space error

### LINKED ISSUE #12588: "An unknown error has occurred" when not enough quota
Happens on master:

1. Set the quota of a user to 0 or a few bytes
1. Upload a file as that user
1. Expected :question: https://github.com/nextcloud/server/blob/a793b1027c6fdf0cade31bf84cf64d378f2727b4/apps/files/js/file-upload.js#L1027-L1030 or https://github.com/nextcloud/server/blob/a793b1027c6fdf0cade31bf84cf64d378f2727b4/apps/files/js/file-upload.js#L947-L955
1. Actually throws :boom: https://github.com/nextcloud/server/blob/a793b1027c6fdf0cade31bf84cf64d378f2727b4/apps/files/js/file-upload.js#L1032-L1040

Works fine in stable14

@skjnldsv can you have a look? You modified the upload stuff in general lately?

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #12588
Probably needs more fixing for the other cases. But this is the quick
fix I could come up with for now.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Review by skjnldsv — COMMENTED** [review]
:crocodile:

**Review by skjnldsv — APPROVED** [review]
:crocodile:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
JSUnit test fail

**Comment by MorrisJobke** [comment]
Let me look into the js unit tests.

**Comment by MorrisJobke** [comment]
> Let me look into the js unit tests.

Fixed.

**Pull request merged**
