### PR TITLE
dont use part files for dav writes when the target folder doesn't have create permissions

### PR DESCRIPTION
**Pull request by icewind1991**
Signed-off-by: Robin Appelman <robin@icewind.nl>

### CODE REVIEW

**Comment by skjnldsv** [comment]
@icewind1991 is there an existing issue this pr fixes? :)
Code looks good to me!

**Review by skjnldsv — APPROVED** [review]
Looks good to me! Make sense!

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by MorrisJobke** [comment]
PHPUnit tests for comments failed. Thus I rebased this to fetch potential fixes.

**Pull request merged**
