### PR TITLE
fix(theming): Fix layout of themes

### LINKED ISSUE #48407: Theme previews / selector looks to crowded
Alignment of screenshots, description and radio buttons looks weird and broken.

The section should not be limited in width and the theme options should take a reasonable width.
For example if there is space then all should look like the "system default" entry.

image

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Fix https://github.com/nextcloud/server/issues/48407

Before | After
--- | ---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by ShGKme** [comment]
If I'm not mistaken, @marcoambrosini had some plans here, was discussed when `NcSettingsSection` become force limited

**Review by susnux — APPROVED** [review]
Better :)
Yet I think limiting the width is an mistake here, like with the profile settings it should take more horizontal space as 1920px is basically the norm today.

**Comment by marcoambrosini** [comment]
Nice improvement!

**Comment by marcoambrosini** [comment]
> Yet I think limiting the width is an mistake here, like with the profile settings it should take more horizontal space as 1920px is basically the norm today.

Since there can be long paragraphs in the settings, I'd like to limit the width to improve readability

**Comment by Pytal** [comment]
> > Yet I think limiting the width is an mistake here, like with the profile settings it should take more horizontal space as 1920px is basically the norm today.
> 
> Since there can be long paragraphs in the settings, I'd like to limit the width to improve readability

The width is force-limited to 900px already on 30+ but do you think we should limit it more?

**Comment by marcoambrosini** [comment]
I think that's ok @Pytal !

**Pull request merged**
