### PR TITLE
Getting rid of openssl_seal and rc4 in server side encryption

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: # 

## Summary

Get rid of the intermediate fileKey and the obsolete RC4 encryption used on it.
Also used the opportunity to change the padding used to OAEP.
Files encrypted with previous version can still be read but upon write they will get migrated to the new encryption.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by yahesh** [comment]
> So the version in the header would only be written by the normal process, and would be read only for recovery scenarios?

Yes, exactly. I remember that someone wrote a fix-file-version-in-database command which tests through a bunch of version numbers to find the correct one. I wrote one such script myself in the past as well. Having the version number within the file header would obsolete that brute-force approach. And as the file header is rewritten with any re-encryption anyway...

> But in any case I think this would need to go in a follow-up PR as it is not tied to this one.

Fine for me.

**Comment by come-nc** [comment]
Follow-up task: write an occ command to migrate all files to the new key format, when master key is used. (it only needs to open/write/close all encrypted files.)

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by come-nc** [comment]
> @come-nc Hi and thanks for this work, could the follow-up task be tracked by an issue or draft PR ?

https://github.com/nextcloud/server/issues/37918

**Comment by biboc** [comment]
Hi,

Does it break recover-tool? 
https://github.com/nextcloud/encryption-recovery-tools

New files added with Nextcloud 27 have no fileKey and the script does not work anymore

**Comment by biboc** [comment]
Also, the documentation needs to be updated: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html

**Comment by yahesh** [comment]
> Does it break recover-tool? https://github.com/nextcloud/encryption-recovery-tools
> 
> New files added with Nextcloud 27 have no fileKey and the script does not work anymore

This should be fixed.

**Comment by come-nc** [comment]
> Also, the documentation needs to be updated: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html

I read this page and I am not sure which part you are referring to which should be updated?
What I’ve read is still true I think.

**Comment by biboc** [comment]
I don't remember, someone may have removed the part I mentioned. I should have link to a specific Nextcloud version

**Comment by come-nc** [comment]
@joshtrichards Can you explain why you added the pending documentation label back?

**Comment by joshtrichards** [comment]
Oops missed this first time around. Not sure now. I seem to remember fixing the encryption tools link, but that was a different issue. Fine by me.

**Pull request merged**
