### PR TITLE
fix for sharing

### PR DESCRIPTION
**Pull request by enoch85**
Signed-off-by: Daniel Hansson <daniel@techandme.se>

Fixes https://github.com/nextcloud/server/issues/3455

### CODE REVIEW

**Comment by enoch85** [comment]
Can someone backport to 12 and 11 as well please? Didn't figure out how to push to stable12, git said the branch was protected.

**Comment by nickvergessen** [comment]
@encho85 you need to create a branch based on stable12 and then send a PR against stable12

**Comment by enoch85** [comment]
@nickvergessen How do I fix the errors? Timeout...

**Comment by nickvergessen** [comment]
You don't, its fine

**Review by nickvergessen — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
