### PR TITLE
Show upload menu in folders' emptycontent

### LINKED ISSUE #40205: Should the empty folder button ask to upload something instead of going back?
Should the empty folder button ask to upload something instead of going back?

See 
image

cc @nextcloud/designers

### PR DESCRIPTION
**Pull request by marcoambrosini**
* Resolves: #40205 

## Before
Screenshot 2024-03-18 at 12 48 37

## After
Screenshot 2024-03-18 at 12 58 06

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Tested and seems to work. Really nice UX improvement! :)

**Review by susnux — APPROVED** [review]
LGTM nice UX!

**Review by Pytal — APPROVED** [review]

**Comment by susnux** [comment]
@marcoambrosini can you please adjust your commit message to comply with conventional commits? :)

**Review by skjnldsv — CHANGES_REQUESTED** [review]
This error message does not mean the folder truly exists

**Comment by skjnldsv** [comment]
## There are many factors you need to check to show an UploadPicker
1. Does the directory exists (see `currentFolder`)
2. Does the user have create permissions on that folder ?

### Additional data:
What you are editing is shared between _ALL_ views, the deleted files, the tags, the shares, favorites.... etc. We need to keep the `Go Back` feature alongside the upload picker.

**Comment by jancborchardt** [comment]
@marcoambrosini do you still want to have this in beta 6? If so, the last call for that is happening now, otherwise we have to move it to 30.

**Comment by skjnldsv** [comment]
@jancborchardt we're far into features freeze (3 weeks) and Rc1 is this week

**Comment by susnux** [comment]
@skjnldsv @marcoambrosini I pushed a commit to bring back the *back* button if upload is not possible.

**Review by skjnldsv — APPROVED** [review]
Code looks good

**Comment by marcoambrosini** [comment]
I can't figure out what's wrong with the failures

**Comment by skjnldsv** [comment]
Thanks @susnux !

**Comment by marcoambrosini** [comment]
What was it @susnux ?

**Comment by susnux** [comment]
> What was it @susnux ?

Just flaky and needed to be restarted

**Pull request merged**
