### PR TITLE
feat(files): quota warning and disabled upload button

### LINKED ISSUE #41020: [F2V]  Show storage almost full and full warning
Closes https://github.com/nextcloud/server/issues/25293

Just a temporary `showWarning` and `showError` is fine I guess. It will be displayed for a short amount of time, but closable
I would add this to the [Quota Component](https://github.com/nextcloud/server/blob/dbeb526bbab64e051958e1194e32903c2420e40d/apps/files/src/components/NavigationQuota.vue), and maybe a watcher so that if there is a change, we show the warning again (only if it wasn't warned before)

### LINKED ISSUE #41113: [Bug]: Hint for no space in files is gone for >= NC26
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If a user has no storage space left NC25 shows a warning:
SCR-20231025-nhyv

Starting with NC26 this is gone:
SCR-20231025-nibd

The FE looks for free_space to calculate the state for this hint.
This one looks like in NC25: `<input type="hidden" id="free_space" value="0">`
And in NC26: `<input type="hidden" id="free_space" value="">`

### Steps to reproduce

1. create a user with quota 0
2. login as new user
3. open files app

### Expected behavior

There should be a hint that nothing can be created. But I am not sure if the hint for the permissions is correct, because it's based on missing storage not on missing permissions?! Just my 50cents.

### Installation method

None

### Nextcloud Server version

25

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

https://support.nextcloud.com/#ticket/zoom/52686

### PR DESCRIPTION
**Pull request by skjnldsv**
Missing from F2V
Fix https://github.com/nextcloud/server/issues/41113
Fix https://github.com/nextcloud/server/issues/41020

## Quota warning
- This is now just a closable tooltip
- This is shown:
	- on page load if quota is reached
	- on upload or navigating ONLY ONCE; and if free space changes from `> 0` to `0`
	  This will prevent spamming with notifications and still warn people on sudden change

## Upload button
This PR also fixes the Upload button not being disabled on quota exceeded

## Upload error handling
Last commit also adds some better error handling
Unfortunately most of the server error messages remains [untranslated](https://github.com/nextcloud/server/blob/83f04b093ceeb4d567d6633230adff51bfcc932f/apps/dav/lib/Connector/Sabre/QuotaPlugin.php#L216), so we will use our own, despite the server potentially providing a bit more context.
- [x] Needs https://github.com/nextcloud-libraries/nextcloud-upload/pull/953
  but we can still merge already. This will automatically works on the next dependency update

Example: 
> Insufficient space in /Folder, 156416515 required, 0 available

Versus
> Not enough free space

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]
Really liked these changes. Only comment would be if there is any way there is any way that there is less than 0 free storage space, the strict comparison with " === 0 " might not pass, and " <= 0" might be better. 

But if not, I really liked the changes committed here!

**Comment by skjnldsv** [comment]
> Really liked these changes. Only comment would be if there is any way there is any way that there is less than 0 free storage space, the strict comparison with " === 0 " might not pass, and " <= 0" might be better.

`quota-available-bytes` can be negative yep :)

**Comment by solracsf** [comment]
Issues with S3 or external mounts: https://github.com/nextcloud/server/pull/42591

**Pull request merged**
