### PR TITLE
always return numeric storage id as int, also check type equality in …

### PR DESCRIPTION
**Pull request by LukasReschke**
…test asserts

From https://github.com/owncloud/core/pull/25896

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
Backport?

**Comment by rullzer** [comment]
:+1:

**Comment by LukasReschke** [comment]
I don't see a big reason for a backport. Only has the risk to introduce regressions. I'd say only 11.

**Pull request merged**
