### PR TITLE
Principal property search for users and groups with {DAV:}display name

### PR DESCRIPTION
**Pull request by georgehrke**
## What does this pull-request introduce:
- proper calendar-user-type reporting for principals
- allow to search for users by their displayname
- allow to search for groups by their display name
- append localised `(group)` to displayname of group. (I can also remove this again if not wanted)

## What do i need this for?
- I need this for implementing a proper `principal-property-search` in the [c-dav library](https://github.com/nextcloud/cdav-library/pull/25/files?utf8=✓&diff=unified#diff-1fdf421c05c1140f6d71444ea2b27638R207)
- I need this for the attendee / resource search in the calendar app
- This will later on allow sharing calendars straight from macOS' calendar with a user's displayname

## Privacy considerations
- All implementations take the sharing API rules into consideration.
  - If sharing API is disabled, principal property search will always return empty list
  - If sharing API is restricted to groups, only groups / users from the same group are returned

=> This change will not provide more information than already provided by the OCS Share API

@MorrisJobke @rullzer @nickvergessen Any opinion on this change?

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> 🚧 🚧 🚧 This PR is currently based on #11822 🚧 🚧 🚧

Please rebase 😉

**Comment by georgehrke** [comment]
> Please rebase 😉

Rebased and base-branch of PR updated.

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Comment by MorrisJobke** [comment]
CI failure is unrelated.

**Review by rullzer — APPROVED** [review]
Code looks good. ANd makes sense. Lets get this in

**Pull request merged**
