### PR TITLE
Remove unneeded sidebar animation

### PR DESCRIPTION
**Pull request by skjnldsv**
The transitions are not working since a long time on the sidebar.
Time to cleanup unnecessary delay.

@nextcloud/designers

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by skjnldsv** [comment]
Bump :)

**Review by ChristophWurst — APPROVED** [review]

**Comment by jancborchardt** [comment]
But now there’s no animation at all? This is very janky and needs to be nicer. Nothing should just appear out of the blue. (Or is it something for the ominous Files app moving to Vue? :D)

**Comment by skjnldsv** [comment]
@jancborchardt it was not working anyway, so it was just adding a weird delay before showing and preventing other apps to properly detect the sidebar when transitioning :)

**Comment by jancborchardt** [comment]
Yes – but then we should fix it instead of removing. ;)

**Pull request merged**
