### PR TITLE
Bump icewind/searchdav

### LINKED ISSUE #17447: High CPU load with DAV related components
### Steps to reproduce
1. Start up Nextcloud on Apache 2.4 with Calendar, Contacts plugins
2. Wait - with DAVx5 Android client (v 2.5.5) querying for events periodically

### Expected behaviour
Noting :)

### Actual behaviour
Server is going on high load on one of the cores - if waiting long enough it can spread to other cores as well - I assume that each error leads to high load on single CPU

### Server configuration

**Operating system**:
Gentoo Linux with kernel 4.19.72

**Web server:**
Apache 2.4.4.1

**Database:**
mysql Ver 15.1 Distrib 10.2.22-MariaDB

**PHP version:**
7.2.22

**Nextcloud version:** (see Nextcloud admin page)
16.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 16.0.4

**Where did you install Nextcloud from:**
Initial install was from gentoo portage but later was updated using built-in webupdate 

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bookmarks: 2.2.0
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.6
  - dav: 1.9.2
  - deck: 0.6.6
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.10.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - polls: 0.10.2
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - richdocuments: 3.4.2
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.4
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.somedomain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "overwrite.cli.url": "https:\/\/cloud.comedomain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "theme": "",
        "loglevel": 2,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\SVG",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\BMP",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\PNG",
            "OC\\Preview\\XBitmap"
        ]
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome 77.0.3865.90

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"XZlvJQhoUxX8xwGWHu9tQgAAAEY","level":3,"time":"2019-10-06T04:35:50+00:00","remoteAddr":"someIP","user":"user_x","app":"PHP","method":"SEARCH","url":"\/remote.php\/dav","message":"Undefined offset: 0 at \/var\/www\/somedomain.com\/htdocs\/nextcloud\/3rdparty\/icewind\/searchdav\/src\/XML\/Operator.php#71","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.8.0","version":"16.0.5.1"}
{"reqId":"XZlvJS7ZfjNWPg5BWl6jYAAAAA0","level":3,"time":"2019-10-06T04:35:50+00:00","remoteAddr":"someIP","user":"user_x","app":"PHP","method":"SEARCH","url":"\/remote.php\/dav","message":"Undefined offset: 0 at \/var\/www\/somedomain.com\/htdocs\/nextcloud\/3rdparty\/icewind\/searchdav\/src\/XML\/Operator.php#71","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.8.0","version":"16.0.5.1"}
{"reqId":"XZlvTghoUxX8xwGWHu9tQwAAAEQ","level":3,"time":"2019-10-06T04:36:30+00:00","remoteAddr":"someIP","user":"user_x","app":"PHP","method":"SEARCH","url":"\/remote.php\/dav","message":"Undefined offset: 0 at \/var\/www\/somedomain.com\/htdocs\/nextcloud\/3rdparty\/icewind\/searchdav\/src\/XML\/Operator.php#71","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.8.0","version":"16.0.5.1"}
{"reqId":"XZlvUy7ZfjNWPg5BWl6jaQAAAAY","level":3,"time":"2019-10-06T04:36:35+00:00","remoteAddr":"someIP","user":"user_x","app":"PHP","method":"SEARCH","url":"\/remote.php\/dav","message":"Undefined offset: 0 at \/var\/www\/somedomain.com\/htdocs\/nextcloud\/3rdparty\/icewind\/searchdav\/src\/XML\/Operator.php#71","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.8.0","version":"16.0.5.1"}
{"reqId":"XZlvdi7ZfjNWPg5BWl6jbQAAABY","level":3,"time":"2019-10-06T04:37:11+00:00","remoteAddr":"someIP","user":"user_x","app":"PHP","method":"SEARCH","url":"\/remote.php\/dav","message":"Undefined offset: 0 at \/var\/www\/somedomain.com\/htdocs\/nextcloud\/3rdparty\/icewind\/searchdav\/src\/XML\/Operator.php#71","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.8.0","version":"16.0.5.1"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Not applicable
</details>

### PR DESCRIPTION
**Pull request by kesselb**
Fix #17447  

Bump icewind/searchdav to fix a infinite loop discovered by @NaofumiHonda caused by xml parsing issues. 

- [x] Requires https://github.com/nextcloud/3rdparty/pull/349

I think we should backport it to 17.0.2 if possible.

### CODE REVIEW

**Comment by kesselb** [comment]
Scary. The build passed ;)

**Review by icewind1991 — APPROVED** [review]

**Comment by rullzer** [comment]
Rebased

**Review by rullzer — APPROVED** [review]

**Review by gary-kim — APPROVED** [review]

**Comment by gary-kim** [comment]
> Scary. The build passed ;)

Seems to have been getting a lot more reliable recently. Well, I say that, we went from passing being rare to being uncommon. Is someone doing work on getting the build agents more reliable?

**Comment by foremon** [comment]
Please also backport to 16.0.7.

**Pull request merged**
