### PR TITLE
Add users and apps inner search and add HeaderMenu cancel

### PR DESCRIPTION
**Pull request by skjnldsv**
- [x] Add back search with the following UX flow:
  - Searching within the Unified Search also filters inner content
  - Pressing escape just closes the header menu and does NOT reset the search
  - Clicking outside just closes the header menu and does NOT reset the search
  - Pressing the reset search button clears everything AND reset the unified search state

This was requested by @jancborchardt and should be the default behaviour for other apps.

___
Alongside I added a `cancel` event to the HeaderMenu component that could be use by other apps once I moved it to https://github.com/nextcloud/nextcloud-vue

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@skjnldsv I guess this fixes the issue discussed in https://github.com/nextcloud/server/pull/22526#issuecomment-684206459, right?

**Review by ChristophWurst — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
>    * Pressing the reset search button clears everything AND reset the unified search state

I can not see any reset search button. Where is it supposed to be?

Screenshot_2020-09-11 Inventar - Nextcloud

**Comment by raimund-schluessler** [comment]
It would be nice if it could be somehow indicated when a search is still "active", i.e. the search string is not empty. Maybe with a red dot or at least the opacity of the search icon could be set to 1.

**Comment by skjnldsv** [comment]
> It would be nice if it could be somehow indicated when a search is still "active", i.e. the search string is not empty. Maybe with a red dot or at least the opacity of the search icon could be set to 1.

why?


> I can not see any reset search button. Where is it supposed to be?

What browser?
Capture d’écran_2020-09-12_11-24-33

**Comment by raimund-schluessler** [comment]
> What browser?
> Capture d’écran_2020-09-12_11-24-33

This is with latest Firefox 80.0.1. In Chrome is indeed visible.

**Comment by skjnldsv** [comment]
I'll add a dedicated reset button for firefox.
Thanks Mozilla... 
image

**Comment by raimund-schluessler** [comment]
> > It would be nice if it could be somehow indicated when a search is still "active", i.e. the search string is not empty. Maybe with a red dot or at least the opacity of the search icon could be set to 1.
> 
> why?

Because it is currently not obvious when a search/filter is active and users might be confused why certain content is not shown.

No search:
Screenshot_2020-09-12 Tasks - Nextcloud(1)


With filter/search:
Screenshot_2020-09-12 Tasks - Nextcloud

**Comment by jancborchardt** [comment]
> Because it is currently not obvious when a search/filter is active and users might be confused why certain content is not shown.

Good point … this is unfortunately where the drawback of showing the search field only in the dropdown comes in. The way we did it before with the search field being directly in the header, this was obvious.

- So ideally, we could move again to that, showing the search field part of the search in the header. The results popover can be directly below. This is also how it’s commonly done in other apps like Google products, as well as on Android for example.
- Or as a step inbetween, when the app does inline filtering and you click somewhere else and the popover closes, the popover doesn’t fully close but the search field still shows?
- Or we really do clear the search when the popover closes, although that is unexpected and would be quite frustrating.

**Comment by skjnldsv** [comment]
> * So ideally, we could move again to that, showing the search field part of the search in the header. The results popover can be directly below. This is also how it’s commonly done in other apps like Google products, as well as on Android for example.

The issue we had was on small screens. But I'm fine if you prefer than. Though I would be also fine just adding an indicator like the white triangle under? or a red dot like notifications? :thinking: :grinning: 

> * Or as a step inbetween, when the app does inline filtering and you click somewhere else and the popover closes, the popover doesn’t fully close but the search field still shows?

I'm afraid it could conflict with other elements on page, especially mobile

> * Or we really do clear the search when the popover closes, although that is unexpected and would be quite frustrating.

You asked not to, so we're good there, no clearing on close :)

**Comment by jancborchardt** [comment]
> The issue we had was on small screens. But I'm fine if you prefer than. Though I would be also fine just adding an indicator like the white triangle under? or a red dot like notifications?

So the search would initially be an icon, but as soon as you click or focus, it would expand (like before).

On mobile, it’s fine to do it like on Android: Search can take the full heading width (at least on smartphone sizes) and go back to icon-only when you clear the search. (On tablet or intermediate sizes, it’s fine if search takes as much space as it needs away from the list of app icons.)

An indicator on the search icon is something that can easily be missed and also something I haven’t seen elsewhere before.

**Comment by skjnldsv** [comment]
@raimund-schluessler this will wait for21, Jan have a bit more in-depth requests for this that will create too much changes for 20 :)

**Comment by raimund-schluessler** [comment]
> 
> 
> @raimund-schluessler this will wait for21, Jan have a bit more in-depth requests for this that will create too much changes for 20 :)

@skjnldsv What exactly will have to wait? The whole PR or indicating that a search is active?
Maybe as a compromise before not doing anything we could at least increase the opacity of the search icon to 1 when the search is active.

**Comment by raimund-schluessler** [comment]
And adding a reset button for Firefox is not controversial as well, right?

**Comment by skjnldsv** [comment]
> Maybe as a compromise before not doing anything we could at least increase the opacity of the search icon to 1 when the search is active.

> * Or as a step inbetween, when the app does inline filtering and you click somewhere else and the popover closes, the popover doesn’t fully close but the search field still shows?

This will be implemented in a followup for 20

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
* [ ] changing sections in the apps management doesn't work for me anymore.

**Pull request merged**
