### PR TITLE
Add a repair step to drop the account_terms table on oc migration

### PR DESCRIPTION
**Pull request by nickvergessen**
Abusing the backport label for a forward port to master.

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Comment by nickvergessen** [comment]
Fixed the updater itself, it held a copy of the array...

**Review by MorrisJobke — APPROVED** [review]

**Comment by jospoortvliet** [comment]
testing in progress...

**Comment by jospoortvliet** [comment]
Tested, works here. Go for it :+1:

**Comment by MorrisJobke** [comment]
> Tested, works here. Go for it 👍

Waiting for CI.

**Comment by MorrisJobke** [comment]
@nickvergessen 🏓 backport pending

**Comment by nickvergessen** [comment]
I will do the FORWARD port on monday

**Comment by MorrisJobke** [comment]
> I will do the FORWARD port on monday

You and your backport-requests that are already backports :P

**Pull request merged**
