### PR TITLE
fix(dashboard): remove duplicated IDs on the dashboard page

### LINKED ISSUE #37098: [BITV] 9.4.1.1/0.2  On the page, there are multiple IDs that are identical - see "resourceNameFintestExplorer".
<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3fd73cfb9c-v0-n2

</details>

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3fd73cfb9c-v0-n1

</details>

---

- [x] Page 1 — Login (_seems to be fixed already_)
  Anmelden – Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/login
- [x] Page 2 — Dashboard
  https://github.com/nextcloud/server/pull/40768
  Dashboard - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/dashboard/
- [x] Page 3 — Files
  https://github.com/nextcloud-libraries/nextcloud-vue/pull/4606
  https://github.com/nextcloud-libraries/nextcloud-vue/pull/4607
  https://github.com/nextcloud/server/pull/40771
  Files - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/files/
- [x] Page 4 — Photos (incl. Viewer) (_same as files_)
  All your media - Photos - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/photos/
- [x] Page 5 — Activity (_seems to be fixed already_)
  All activities - Activity - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/activity/
- [x] Page 6 — Personal info (_seems to be fixed already_)
  Personal info - Personal settings - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/settings/user
- [x] Page 7 — Logging (_seems to be fixed already_)
  Logging - Administration settings - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/settings/admin/logging
- [x] Page 8 — Active users
  https://github.com/nextcloud-libraries/nextcloud-vue/pull/4607
  Active users - Users - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/settings/users
- [x] Page 9 — User documentation (_seems to be fixed already_)
  User documentation - Help - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/settings/help
- [x] Page 10 — Documents (_same as Files_)
  Documents - Files - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/files/?dir=/Documents&fileid=689

### PR DESCRIPTION
**Pull request by ShGKme**
* Resolves: https://github.com/nextcloud/server/issues/37098 (Page 2 — Dashboard)

## Summary

Dashboard used the same ID for header icons in every panel (dashboard widget).

This PR makes them unequal by using panel id as a part of ID

## TODO

- [x] Use panel id as a part of ID

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by JuliaKirschenheuter — APPROVED** [review]

**Review by susnux — APPROVED** [review]
wild ID naming, but makes sense :+1:

**Comment by ShGKme** [comment]
> wild ID naming

not the work of my hands ༼ つ ◕_◕ ༽つ

**Comment by ShGKme** [comment]
Failed dron test is unrelated, I don't have rights to restart

**Comment by susnux** [comment]
Drone unrelated

**Pull request merged**
