### PR TITLE
Add featured category

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

Note: I have no idea what I'm doing, therefore need mentorship from the masters!

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Code looks good!

**Review by juliusknorr — APPROVED** [review]
Tested and works.

**Comment by juliushaertl** [comment]
I'm also thinking, since this is an app store category, should we exclude the shipped apps from it and just show the ones coming from the app store? Having the file sahring, federation apps, etc. in there doesn't make much sense imo.

**Comment by mario** [comment]
Possibly, but it's really a virtual category - it doesn't exist in reality. I guess it's a good way to show that it's "official"/"supported" since that's pretty much what we use the "Featured" flag for?

**Comment by mario** [comment]
cc @wiswedel so you can track this :)

**Comment by juliushaertl** [comment]
@mario The comitted bundles seem to be outdated. Rebasing and running a fresh `npm ci` and `MODULE=settings npm run build` should bring them to a state where the CI is happy with it. :wink:

**Comment by blizzz** [comment]
Locally it does not work until a rebuild with `npm ci && npm run build`

**Comment by mario** [comment]
@juliushaertl done, thanks for the hint. Let's see if this works :D

**Comment by blizzz** [comment]
it also differs from the other categories by showing a list instead of the tiled view

**Comment by mario** [comment]
@blizzz we also show shipped apps in here and they don't have screenshots, so tiled view might look off/strange? But that depends on what exactly we want here, like @juliushaertl mentioned :)

**Comment by mario** [comment]
> I'm also thinking, since this is an app store category, should we exclude the shipped apps from it and just show the ones coming from the app store? Having the file sahring, federation apps, etc. in there doesn't make much sense imo.

@wiswedel thoughts? We leave the current PR as-is anyway, but we can always open a separate issue to adjust this.

**Comment by blizzz** [comment]
Shipped apps can still be enabled or disabled. It's ok to leave them imho.

**Comment by wiswedel** [comment]
> Shipped apps can still be enabled or disabled. It's ok to leave them imho.

I agree

**Comment by mario** [comment]
Okay then - merge away? :)

**Comment by rullzer** [comment]
Lets do this and then we continue with improvements later :)

**Pull request merged**
