### PR TITLE
Send new password instead of empty string

### PR DESCRIPTION
**Pull request by kesselb**
Password reset does not work for me on master.

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

**Comment by kesselb** [comment]
After a successful password reset i see the login form but the url looks weird. A login form submit leads to a http exception sometimes because it tries to open the password reset page again. Can someone with more vue knowledge please have a look?

**Comment by juliushaertl** [comment]
Let me have a look then

**Comment by juliushaertl** [comment]
@kesselb Should be fine now.

**Review by skjnldsv — APPROVED** [review]

**Comment by kesselb** [comment]
> @kesselb Should be fine now.

Looks good :+1:

**Pull request merged**
