### PR TITLE
Add Gnome Nautilus agent and DAVdroid agent to incompatible user agents

### PR DESCRIPTION
**Pull request by olivierkeke**
Needed for OVH shared server. See #223.

### CODE REVIEW

**Comment by rfc2822** [comment]
Just for curiosity: what are "incompatible user agents" and is this a DAVdroid problem?

**Comment by LukasReschke** [comment]
As said also at https://github.com/nextcloud/server/pull/1601#issuecomment-250927757 this seems rather contra-productive to me. Can you send me a traffic dump of the Nautilus WebDAV transfers?

**Comment by olivierkeke** [comment]
@LukasReschke I agree it's contra-productive. But patching this file at each nextcloud update and having code integrity warning is annoying. I suggested in #223 to use config.php file to store the incompatible UA, could it be a solution ?

I have an internet problem on my gnome computer so I can't send you traffic dump now.

@rfc2822 I don't really understand technical aspect of this problem: something with cookies and some client / OVH server combination... So I can't say if there is something that can/must be done on DAVdroid side.

**Comment by djibux** [comment]
I am hosted at OVH and I couldn't get the agenda to sync with my phone. That patch solved the issue.  Thanks.

Are there any plans to include it in an upcoming release?

**Comment by MorrisJobke** [comment]
> As said also at #1601 (comment) this seems rather contra-productive to me. Can you send me a traffic dump of the Nautilus WebDAV transfers?

Sorry for this, but I will close this PR. we need to find a proper way to fix this. Just removing more and more security checks doesn't solve this problem. As @LukasReschke stated above: could we get a traffic dump to see what is actually send to the server and why it is broken? Thanks

**Comment by djibux** [comment]
I'm not sure what kind of dump you need but I enabled debug mode in DAVDroid.  I get a 503 without @olivierkeke patch, and it works fine with it.

```
2017-08-12 23:51:04 315 [dav4android.BasicDigestAuthHandler] Adding Basic authorization header for https://example.com/remote.php/dav/addressbooks/users/me/contacts/
2017-08-12 23:51:04 315 [HttpClient] <-- 503 Service Unavailable https://example.com/remote.php/dav/addressbooks/users/me/contacts/ (117ms)
2017-08-12 23:51:04 315 [HttpClient] Set-Cookie: 60gp=R477012350; path=/; expires=Sat, 12-Aug-2017 22:52:52 GMT
2017-08-12 23:51:04 315 [HttpClient] Date: Sat, 12 Aug 2017 21:51:03 GMT
2017-08-12 23:51:04 315 [HttpClient] Server: Apache
2017-08-12 23:51:04 315 [HttpClient] X-Powered-By: PHP/7.0.21
2017-08-12 23:51:04 315 [HttpClient] Expires: Thu, 19 Nov 1981 08:52:00 GMT
2017-08-12 23:51:04 315 [HttpClient] Cache-Control: no-store, no-cache, must-revalidate
2017-08-12 23:51:04 315 [HttpClient] Pragma: no-cache
2017-08-12 23:51:04 315 [HttpClient] Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'nonce-R25kcDJpNGxWR3FNY1hvaDkyZWxDa1ZvMmRvVm9aNHhNa0VGYjM4NTk2Zz06ZGpnZG5SaG5Nank4RlJ4bnhCUFZTQ002NjZrZythdG9ZeGx3QkNocW85OD0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
2017-08-12 23:51:04 315 [HttpClient] X-XSS-Protection: 1; mode=block
2017-08-12 23:51:04 315 [HttpClient] X-Content-Type-Options: nosniff
2017-08-12 23:51:04 315 [HttpClient] X-Frame-Options: Sameorigin
2017-08-12 23:51:04 315 [HttpClient] X-Robots-Tag: none
2017-08-12 23:51:04 315 [HttpClient] X-Download-Options: noopen
2017-08-12 23:51:04 315 [HttpClient] X-Permitted-Cross-Domain-Policies: none
2017-08-12 23:51:04 315 [HttpClient] Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
2017-08-12 23:51:04 315 [HttpClient] Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
2017-08-12 23:51:04 315 [HttpClient] X-Content-Type-Options: nosniff
2017-08-12 23:51:04 315 [HttpClient] X-XSS-Protection: 1; mode=block
2017-08-12 23:51:04 315 [HttpClient] X-Robots-Tag: none
2017-08-12 23:51:04 315 [HttpClient] X-Frame-Options: SAMEORIGIN
2017-08-12 23:51:04 315 [HttpClient] X-Download-Options: noopen
2017-08-12 23:51:04 315 [HttpClient] X-Permitted-Cross-Domain-Policies: none
2017-08-12 23:51:04 315 [HttpClient] Vary: Accept-Encoding
2017-08-12 23:51:04 315 [HttpClient] Transfer-Encoding: chunked
2017-08-12 23:51:04 315 [HttpClient] Content-Type: text/html; charset=UTF-8
2017-08-12 23:51:04 315 [HttpClient] X-IPLB-Instance: 1050
2017-08-12 23:51:04 315 [HttpClient] 
2017-08-12 23:51:04 315 [HttpClient] 
2017-08-12 23:51:04 315 [HttpClient] <-- END HTTP (0-byte body)
2017-08-12 23:51:04 315 [syncadapter.SyncManager] Got 503 Service unavailable, trying again later
EXCEPTION at.bitfire.dav4android.exception.ServiceUnavailableException: 503 Service Unavailable
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.kt:329)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.kt:295)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.kt:271)
	at at.bitfire.davdroid.syncadapter.ContactsSyncManager.listRemote(ContactsSyncManager.kt:231)
	at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.kt:144)
	at at.bitfire.davdroid.syncadapter.ContactsSyncAdapterService$ContactsSyncAdapter.sync(ContactsSyncAdapterService.kt:43)
	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:48)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```

Please let me know how I can further help.

**Comment by djibux** [comment]
Hello,
I am sorry to revive an old thread but I just saw a new user agent has been added: ``'/^Microsoft-WebDAV-MiniRedir/'``.
What could be done about Nautilus and DAVDroid?  I find it frustrating to have to manually patch Nextcloud after each upgrade.
Thanks.

**Pull request closed without merging**
