### PR TITLE
Unset user PHOTO before setting new one in OCA\DAV\CardDAV\Converter:…

### LINKED ISSUE #1572: Unset user PHOTO before setting new one in OCA\DAV\CardDAV\Converter::updateCard
A bug + PR in owncloud that can be backported to NextCloud, see owncloud/core#26242 and owncloud/core#26243

### PR DESCRIPTION
**Pull request by MorrisJobke**
…:updateCard (#26243)

Signed-off-by: Olivier Mehani shtrom@ssji.net

fixes #1572

Downstream of owncloud/core#26243

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @nickvergessen @blizzz @LukasReschke

**Comment by MorrisJobke** [comment]
I tested this and it works :+1:

**Comment by LukasReschke** [comment]
LGTM

**Comment by MorrisJobke** [comment]
stable9 #1719 
stable10: #1717

**Pull request merged**
